### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by jason5149** [youzan/vant#1]
1.放一些demo效果，让开发者可以先预览一下对于UI框架会更好吧
2.可以申明一下Vue的版本支持例如：support Vue1.x&2.x

**Comment by cookfront** [comment]
1. demo效果还没对外公布，这两天就会有一个官网了，还在内测。
2. Vue版本稍后在readme中加一下，谢谢建议哦

**Comment by jason5149** [comment]
不客气，好的UI还是要支持的
