### ISSUE TITLE
[Bug Report] vant 3.3.5 使用 unplugin-vue-components 按需 启动报错

### ISSUE THREAD

**Issue by Yacj** [youzan/vant#10000]
### 重现链接

https://github.com/Yacj/vite-news

### Vant 版本

3.3.5

### 描述一下你遇到的问题。

用最新的3.3.5 在vite.config.js 配置  unplugin-vue-components 启动报错 log如下：
 [vite] Internal server error: Failed to resolve import "vant/es/tabs/style" from "src\pages\home\index.vue". Does the file exist?
 Plugin: vite:import-analysis
退回到 3.3.1 启动没问题

### 重现步骤

直接下载项目 vant改版本就可以重现

**Comment by chenjiahan** [comment]
这个问题出现的原因是 Vant 在 package.json 中添加了 `exports` 字段，这个字段主要是为了规范 exports 内容，同时对 nuxt3 提供支持。

目前验证下来，Vant 这边的字段定义是没问题的，是符合规范的写法。要解决这个问题，应该要在 unplugin-vue-components 插件内部进行处理。

从现象上看，应该是 import 时路径没写全的问题，我试了下，把 `vant/es/tabs/style` 改成 `vant/es/tabs/style/index` 的话，是没问题的。

**Comment by Yacj** [comment]
好的 那就是要等 unplugin-vue-components 更新 或者 自己修改下 unplugin-vue-components 源码 就可以了 对吧。

**Comment by chenjiahan** [comment]
嗯嗯，是的

**Comment by Yacj** [comment]
好的 我这边修改了 unplugin-vue-components 的引用方法 可以正常跑起来 谢谢帮助 bug可以bug

**Comment by chenjiahan** [comment]
已提 PR 到 unplugin-vue-components 仓库

**Comment by Yacj** [comment]
好的 谢谢 麻烦了
