### ISSUE TITLE
【ViewPager功能】

### ISSUE THREAD

**Issue by zhangliangming** [youzan/vant#10002]
### 这个功能解决了什么问题？

1.类似tab菜单，可通过左右滑动切换tab界面。
2.ViewPager+（router-view），就是通过左右滑动，切换界面显示对应router-view功能。

### 你期望的 API 是什么样子的？

<v-vpager><v-vpager>

**Comment by chenjiahan** [comment]
暂无计划支持喔，目前 Tab 组件也是支持左右滑动的。
