### ISSUE TITLE
图片预览中vant中插槽使用不了

### ISSUE THREAD

**Issue by cxlogin** [youzan/vant#10003]
### 重现链接

https://chuxin@code.99bx.cn/huibaoweb/koala.git

### Vant 版本

2.12.35

### 描述一下你遇到的问题。

图片预览时插槽在哪里怎么使用呢？又没有详细的介绍

### 重现步骤

点击不能添加内容

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/144813431-e72350f6-8379-49ac-b43a-f007b7537acb.png)

**Comment by chenjiahan** [comment]
插槽的用法可以参考 Vue 官方文档
