### ISSUE TITLE
[Bug Report] vue3 版本 ts环境下 vant3 问题

### ISSUE THREAD

**Issue by yuelinghunyu** [youzan/vant#10015]
### 重现链接

import { default } from "vant/es/image";

### Vant 版本

3.36

### 描述一下你遇到的问题。

按需引用 图片 import { Button, Field, Image as VanImage } from 'vant'

编译直接报错 
Syntax Error: Unexpected keyword 'default'. (5:9)

  3 | import Field from "vant/es/field";
  4 | import "vant/es/field/style/index.js";
> 5 | import { default } from "vant/es/image";
    |          ^
  6 | import "vant/es/image/style/index.js";
  7 | const components = [Field, Button, VanImage];

### 重现步骤

按需引用ts的方式

**Comment by chenjiahan** [comment]
default 是 js 关键字，不能拿来当变量名，没有这种写法。

**Comment by chenjiahan** [comment]
如果是编译产生了问题代码，建议你排查下编译逻辑
