### ISSUE TITLE
Pagination 分页change 无法触发

### ISSUE THREAD

**Issue by 360060316** [youzan/vant#10017]
### 重现链接

https://youzan.github.io/vant/v3/#/zh-CN/pagination

### Vant 版本

3.3.6

### 描述一下你遇到的问题。

Pagination 分页change 无法触发 据网友说是源码里 emitChange 没传 所以change事件没有外抛出来

### 重现步骤

点击无触发

**Comment by chenjiahan** [comment]
已在 3.3.7 版本修复
