### ISSUE TITLE
[Bug Report] 时间选择插件中实例方法setColumnValue，setColumnIndex设置了选中项之后,confirm值不更新

### ISSUE THREAD

**Issue by wensc1996** [youzan/vant#10013]
### 重现链接

https://codesandbox.io/embed/vant-issue-mo-ban-forked-yhv7h?fontsize=14&hidenavigation=1&theme=dark

### Vant 版本

2.12.36

### 描述一下你遇到的问题。

1.时间选择插件中实例方法setColumnValue，setColumnIndex设置了选中项之后，再点击“确认”触发confirm，拿到的值还是之前的值，不是setColumnValue，setColumnIndex设置之后的值。

2.关于动态过滤的功能上体验不好，比如9点我只能选10-20分钟，10点只能选30-40分钟，目前通过:filter="filter"只能单独设置某一项，比如只能控制分钟，而不知道目前小时是选的多少。或者通过@change去监听，再通过setColumnValues来设置备选项，但是如果这个时间选择插件包含在actionSheet中时，该时间选择插件不能初始加载，只有打开了actionSheet之后才能拿到实例，通过这个方法还必须等待actionSheet渲染完成，才能进行过滤操作，就会造成页面每次都有重置的效果展示在页面上，体验不好。综上，动态过滤上，哎一言难尽

### 重现步骤

时间选择插件，有1-30号
1.手动滑动到非1号，比如15号
2.点击上面的重置按钮调用setColumnIndex，
3.点击右上角确认，触发confirm，拿到的值不正确

### 设备/浏览器

Chrome

**Comment by chenjiahan** [comment]
1. 下个版本会修复
2. 你这个场景比较复杂了，目前的 filter 确实难以满足，建议基于 Picker 自行封装一下。

**Comment by chenjiahan** [comment]
已在 2.12.37 版本修复

**Comment by wensc1996** [comment]
> 已在 2.12.37 版本修复

谢谢
