### ISSUE TITLE
[Feature Request] @vant-cli 2.x是不是不会自动生成d.ts声明文件

### ISSUE THREAD

**Issue by toesbieya** [youzan/vant#10016]
### 这个功能解决了什么问题？

目前我下载vant2.12.36的release后，如果删除types目录，再运行`npm run build`，在构建`Build Packed Outputs`任务时会报错，搜issue时看到@vant-cli 4.x是可以的，所以就是问问哈

### 你期望的 API 是什么样子的？

无

**Comment by chenjiahan** [comment]
不会的喔，这个功能是 v3 以上版本才支持的
