### ISSUE TITLE
van-field 的 required 校验对 van-rate 不起作用

### ISSUE THREAD

**Issue by Dora36** [youzan/vant#10023]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-4eibc?file=/src/App.vue

### Vant 版本

2.12.21

### 描述一下你遇到的问题。

```
<van-field name="rate" label="评分"  :rules="[ { required: true, message: '必填' ]"  >
   <template #input>
      <van-rate v-model="rate" />
    </template>
</van-field>
```

### 重现步骤

Rate 评分组件设置了 rules 校验，但并没有起效果，点击提交按钮，依旧会提交数据 0。

### 设备/浏览器

Chrome 浏览器

**Comment by chenjiahan** [comment]
数字 0 是一个合法的输入值，因此对于 required 来说是能校验通过的喔，可以通过 validate 函数来进行校验。
