### ISSUE TITLE
[Bug Report] 通过touchend事件展示popup时，popup会立刻被关闭

### ISSUE THREAD

**Issue by dislido** [youzan/vant#10020]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-vqttj?file=/src/App.vue

### Vant 版本

2.12.36

### 描述一下你遇到的问题。

通过touchend点击打开popup，touchend后的click事件会立刻触发popup的close-on-click-overlay，导致弹窗关闭

### 重现步骤

使用touchend事件打开一个:close-on-click-overlay="true"的popup

### 设备/浏览器

任何移动端，或pc浏览器的移动端调试模式

**Comment by chenjiahan** [comment]
组件内部不会考虑处理这种特殊情况，建议自行兼容。

可以考虑通过 preventDefault 把 touchend 后续的 click 事件取消掉。
