### ISSUE TITLE
[Bug Report] vite  script setup 语法，打包后的效果是全量引入的，不是按需的

### ISSUE THREAD

**Issue by tudou0099** [youzan/vant#10031]
### 重现链接

https://github.com/tudou0099/demos.git

### Vant 版本

3.3.5

### 描述一下你遇到的问题。

未能配置出按需引入的效果
Vant 默认支持通过 Tree Shaking 实现 script 的按需引入。

### 重现步骤

一个空项目 这样写，但是打包后的大小是全量的。我没弄清楚是我配置不对还是vant本身导致的。
```js
<template>
  <Button type="primary">主要按钮</Button>
</template>
<script setup lang="ts">
import { Button } from "vant";
</script>

//dist/index.html                   0.50 KiB
//dist/assets/index.78fd0fd1.js     0.93 KiB / gzip: 0.55 KiB
//dist/assets/vendor.929ff521.css   59.51 KiB / gzip: 29.29 KiB
//dist/assets/vendor.9aa0b82f.js    225.10 KiB / gzip: 81.02 KiB
```
手动导入的话 打包后是正常的
```js
<template>
  <Button type="primary">主要按钮</Button>
</template>
<script setup lang="ts">
import Button from "vant/es/button/index";
import "vant/es/button/style/index";
</script>

//dist/index.html                   0.50 KiB
//dist/assets/index.ab43b2aa.js     0.93 KiB / gzip: 0.55 KiB
//dist/assets/vendor.929ff521.css   59.51 KiB / gzip: 29.29 KiB
//dist/assets/vendor.da57632b.js    57.14 KiB / gzip: 23.06 KiB
```

**Comment by Jungzl** [comment]
`with plugin`:![image](https://user-images.githubusercontent.com/35426360/145684524-82f74446-3a37-4f71-8909-6f447246fb82.png)
`direct import`:![image](https://user-images.githubusercontent.com/35426360/145684582-95adf730-89fc-4f72-8e9b-40f60ad6df86.png)

**Comment by tudou0099** [comment]
> `with plugin`:![image](https://user-images.githubusercontent.com/35426360/145684524-82f74446-3a37-4f71-8909-6f447246fb82.png)
> `direct import`:![image](https://user-images.githubusercontent.com/35426360/145684582-95adf730-89fc-4f72-8e9b-40f60ad6df86.png)
> 

我没太明白什么意思，是指第一张图片是我第一种写法，第二张图片是我第二种写法吗。

第一种写法没有实现按需引入的效果，打包体积很大
第二种写的的打包大小是正常的

**Comment by chenjiahan** [comment]
下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 3.3.7 版本修复
