### ISSUE TITLE
[Bug Report] VanField 的 FieldType 不严谨 

### ISSUE THREAD

**Issue by joo1es** [youzan/vant#10039]
### 重现链接

https://codesandbox.io/s/m5v3f

### Vant 版本

^3.2.0

### 描述一下你遇到的问题。

目前，FieldType的类型为 'tel' | 'text' | 'digit' | 'number' | 'search' | 'password' | 'textarea'，
然而，FieldType应当是继承自 HTMLInputElement 的 type 字段的，原生的type字段还有 'date' | 'month' | 'week' 等，这会导致填写 FieldType 字段以外类型的时候 ts 会报错
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input

### 重现步骤

import { Field } from 'vant'
<Field type="date" />

**Comment by chenjiahan** [comment]
已在 3.4.0 版本修复
