### ISSUE TITLE
[Bug Report] vant Swipe 固定宽度 循环轮播 出现空白

### ISSUE THREAD

**Issue by JianDaRui** [youzan/vant#10038]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-co6co?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675

### Vant 版本

2.12.36

### 描述一下你遇到的问题。

swiper组件，设置固定宽度，新的一轮循环开始的时候，下一张没有展示出来。出现空白。

### 重现步骤

1. 配置项：
    height="300"
    width="270"
    touchable="true"
    loop="true"
滚动轮播。
预期：第一张全部展示，后一张展示部分。
实际：仅展示出第一张

### 设备/浏览器

chrome、小米浏览器h5

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/145788045-78f1b3f2-ee15-402c-b262-823898852e34.png)

**Comment by JianDaRui** [comment]
好的 感谢
