### ISSUE TITLE
vant3.0 在vue3 + vite中，使用Tabs和Tab组件，当Tab组件中加入title-style属性时，打包之后改页面会死循环

### ISSUE THREAD

**Issue by chenjingquan1234** [youzan/vant#10030]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-lnu7r?file=/src/App.vue

### Vant 版本

3.2

### 描述一下你遇到的问题。

vant3.0 在vue3 + vite中，使用Tabs和Tab组件，当Tab组件中加入title-style属性时，打包之后改页面会死循环

### 重现步骤

新增页面
引入Tabs Tab组件
Tab组件加入title-style=“{fontSize: '16px'}”
路由模式改为history
yarn build
yarn serve

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
请提供有效的复现链接。

**Comment by helixcg** [comment]
<van-tab
        v-for="(value, key, index) in tab"
        :title="value"
        :key="key"
        :title-style="{
          borderRight: tab.length - 1 === index ? '0px' : '1px solid #e9e9e9'
        }"
      > 
相同的问题
有解决思路吗

**Comment by helixcg** [comment]
<van-tab
        v-for="(value, key, index) in tab"
        :title="value"
        :key="key"
        :title-style="{
          margin: '10px 0',
          borderRight: tab.length - 1 === index ? '0px' : '1px solid #e9e9e9'
        }"
      >

**Comment by helixcg** [comment]
van-tab
        v-for="(value, key, index) in tab"
        :title="value"
        :key="key"
        :title-style="{
          margin: '10px 0',
          borderRight: tab.length - 1 === index ? '0px' : '1px solid #e9e9e9'
        }"
      这个问题有解决思路吗

**Comment by helixcg** [comment]
> <van-tabs
      v-model:active="active"
      @change="onClickTab"
      class="vantab"
      :ellipsis="false"
    >
      <van-tab
        v-for="(value, key, index) in tab"
        :title="value"
        :key="key"
        :title-style="{
          margin: '10px 0',
          borderRight: tab.length - 1 === index ? '0px' : '1px solid #e9e9e9'
        }"
      >

**Comment by helixcg** [comment]
`
<van-tabs
      v-model:active="active"
      :ellipsis="false"
    >
      <van-tab
        v-for="(value, key, index) in tab"
        :title="value"
        :key="key"
        :title-style="{
          margin: '10px 0',
          borderRight: tab.length - 1 === index ? '0px' : '1px solid #e9e9e9'
        }"
      >
`

**Comment by helixcg** [comment]
###  
<van-tabs
      v-model:active="active"
      :ellipsis="false"
    >
      <van-tab
        v-for="(value, key, index) in tab"
        :title="value"
        :key="key"
        :title-style="{
          margin: '10px 0',
          borderRight: tab.length - 1 === index ? '0px' : '1px solid #e9e9e9'
        }"
      >

**Comment by Liuqian-12** [comment]
我也遇到了 一个组件一个组件排除 结果是title-class 一加上打包到线上就会卡住白屏 死循环，而且不报错什么信息都没有

**Comment by AAaNEIgeiDEItao** [comment]
使用了title-style属性打包，打开页面就会死循环，请问这个bug哪时候能修复？感谢

**Comment by tom-hanks** [comment]
> 我也遇到了 一个组件一个组件排除 结果是title-class 一加上打包到线上就会卡住白屏 死循环，而且不报错什么信息都没有

我也同样遇到这个问题了
```
```
