### ISSUE TITLE
[Bug Report] Field组件留言展示字数统计未考虑emoji表情或繁体字

### ISSUE THREAD

**Issue by CatsAndMice** [youzan/vant#10032]
### 重现链接

https://vant-contrib.oschina.io/vant/v3/#/zh-CN/field

### Vant 版本

3.3.6

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/58327088/145710568-6cf33c6e-8a5f-44a6-86d0-b4e77638cf55.png)
`'😀'.length`长度为2，但留言展示长度应该为1才对

### 重现步骤

留言输入😀

### 设备/浏览器

edge

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 3.3.7 版本修复
