### ISSUE TITLE
[Bug Report] van-image use lazy-load

### ISSUE THREAD

**Issue by Fitz-Wen** [youzan/vant#10046]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-lgkvw?file=/src/Home.vue

### Vant 版本

3.3.7

### 描述一下你遇到的问题。

van-image 组件结合transition的out-in模式使用，图片未正确加载

### 重现步骤

1、访问/home页面，点击‘to about’按钮
2、点击’to home‘按钮，首页的图片未加载

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
已在 3.4.2 版本修复
