### ISSUE TITLE
area-data数据一处code错误

### ISSUE THREAD

**Issue by wangguangyou** [youzan/vant#10040]
### 这个功能解决了什么问题？

![image](https://user-images.githubusercontent.com/34791673/145914073-3618d364-517d-4494-b7c2-c9924a2a1c64.png)
临平区与钱塘区行政code错了

### 你期望的 API 是什么样子的？

行政code正常

**Comment by chenjiahan** [comment]
已在 @vant/area-data@1.1.5 版本修复
