### ISSUE TITLE
Field在部分中文输入法报错 

### ISSUE THREAD

**Issue by xuannanxan** [youzan/vant#10047]
### 重现链接

https://github.com/youzan/vant/blob/dev/packages/vant/src/field/utils.ts

### Vant 版本

3.3.7

### 描述一下你遇到的问题。

Field在部分中文输入法报错 
可能是使用其他JS改变了input事件
直接参考VUE的方法可以恢复
修改field中utils.js
export function endComposing(_ref2) {
  var {
    target
  } = _ref2;

  if (target.composing) {
    target.composing = false;
    trigger(target, 'input');
    //target.dispatchEvent(new Event('input'));
  }

}
function trigger(el, type) {    
  var e = document.createEvent('HTMLEvents');
  e.initEvent(type, true, true);
  el.dispatchEvent(e);
}
恢复正常

### 重现步骤

使用field或search组件
输入中文，按下空格选中文字报错TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.

### 设备/浏览器

chome

**Comment by chenjiahan** [comment]
initEvent 是一个被废弃的方法，所以我们迁移到了 new Event 上，按理说两者的效果是基本等价的。你是使用什么输入法会报错？

**Comment by xuannanxan** [comment]
qq拼音，苹果手机也异常，中文打不进去，需要额外敲一个空格才行，安卓手机正常
这个不是vant单方面的原因，因为我还用了其他第三方的JS 
<script src="../o2_core/bundle.js"></script>

[o2oa](https://www.yuque.com/o2oa/course/cf5r3h)

**Comment by chenjiahan** [comment]
你是使用了其他三方 JS 才出现问题的吗？那 Vant 这边不会考虑兼容的。
