### ISSUE TITLE
[IOS 15] footer 不能固定到最下面。

### ISSUE THREAD

**Issue by yh17838** [youzan/vant#10054]
### 重现链接

暂时没有

### Vant 版本

2.7.1

### 描述一下你遇到的问题。

footer 不能固定到最下面。
![Uploading image.png…]()

### 重现步骤

切换页面之后

### 设备/浏览器

ios 15 版本以后 safari

**Comment by chenjiahan** [comment]
没有复现链接，图片也挂了。

**Comment by yh17838** [comment]
图片来了。 谢谢大佬

https://livesola-dev.s3-ap-northeast-1.amazonaws.com/photo/ip1/669631119049822208.jpg

**Comment by chenjiahan** [comment]
从这里图片无法看出问题，建议给一个 codesandbox 复现链接，或者检查下你页面内的样式是否可能影响。

**Comment by yh17838** [comment]
在 ios 15 的 safari浏览器中。 切换路由的时候 footer 本身在页面的最下方。使用了绝对定位。footer 浮动了上来。 下面出现图片中的空白。

**Comment by chenjiahan** [comment]
你用的是 Tabbar 组件把？这个组件本身只是做了基本的 fixed + bottom 0 布局，并没有特殊逻辑。

**Comment by yh17838** [comment]
van-tabbar 是的。  那可能就是浏览器的问题或者我的css 的影响。ios15 safari 下 绝对定位位置错误的问题，您有遇到过吗。

**Comment by chenjiahan** [comment]
目前没有遇到过哈，你可以去 google 搜下看看有没有类似的问题喔

**Comment by yh17838** [comment]
好滴。google 查 说是这个safari浏览器的工具栏 影响。 哈哈 谢谢您。我在去查查看。

**Comment by zhuxuda** [comment]
我也遇到了 但是是ios chrome并且地址栏在上方才会出现
