### ISSUE TITLE
[Bug Report] van-swipe 延迟创建,图片不轮播

### ISSUE THREAD

**Issue by JustTestCode** [youzan/vant#10052]
### 重现链接

https://codesandbox.io/s/vue3-vant3-forked-exyi7

### Vant 版本

3.3.7

### 描述一下你遇到的问题。

van-swipe 延迟创建,图片不轮播,只有下面的圆点在动,图片一动不动
如果改变浏览器大小,当前的轮播会动,其他Tab下的还是不动

### 重现步骤

打开等一秒即可

### 设备/浏览器

Chrome

**Comment by yuhengshen** [comment]
好像放在tab下的swipe都只有indicator在滚动，swipe-item总是不轮播的。
https://codesandbox.io/s/vue3-vant3-forked-do108?file=/src/App.vue

**Comment by chenjiahan** [comment]
已在 3.4.0 版本修复
