### ISSUE TITLE
[Bug Report] SwipeCell滑动宽度不能动态变化

### ISSUE THREAD

**Issue by Fitz-Wen** [youzan/vant#10051]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-xoi0z?file=/src/App.vue

### Vant 版本

3.3.7

### 描述一下你遇到的问题。

右侧滑动区域的节点动态变化时，滑动计算的距离不是实时计算的，导致滑动距离不足或过多

### 重现步骤

1、右滑后点击收藏按钮
2、再次右滑即会出现上述问题

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
组件内部没法动态监听 slot 内容的宽度，建议你动态传入 rightWidth 属性，然后再调用 open 方法进行重绘。
