### ISSUE TITLE
可横向滚动的Tab组件，ios的webview中上下滚动，组件会短暂消失

### ISSUE THREAD

**Issue by satawait** [youzan/vant#1005]
可横向滚动的Tab组件，在真机ios的webview中上下滚动页面，组件会消失，或者消失后一会儿又出现。

官网Demo在IOS真机webview中即可重现，https://www.youzanyun.com/zanui/vant/examples#/zh-CN/tab。
![wechatimg92](https://user-images.githubusercontent.com/4058233/39683055-faa1e0f2-51e5-11e8-8a27-417b00d44e24.jpeg)

Vant：1.1.1
vue：2.5.2
ios：11.2.1

**Comment by chenjiahan** [comment]
用美团 WebView 试了下没这个问题
