### ISSUE TITLE
[Feature Request] vant3关于组合式API需要安装另一个第三方包文档上给出说明

### ISSUE THREAD

**Issue by SimoralX** [youzan/vant#10057]
### 这个功能解决了什么问题？

解决了文档描述不够详细的问题。

### 你期望的 API 是什么样子的？

[**我们从 @vant/use 这个包**](https://vant-contrib.gitee.io/vant/v3/#/zh-CN/vant-use-intro#shi-li) 加上安装说明：
就是把github仓库里的readme复制一份出来。

```bash
# with npm
npm i @vant/use

# with yarn
yarn add @vant/use

# with pnpm
pnpm add @vant/use
```

**Comment by chenjiahan** [comment]
默认情况下不需要单独安装 @vant/use，除非你使用了 pnpm

**Comment by SimoralX** [comment]
> 默认情况下不需要单独安装 @vant/use，除非你使用了 pnpm

感谢答复，是的我使用的pnpm😂

**Comment by chenjiahan** [comment]
嗯嗯，我文档里还是标注下
