### ISSUE TITLE
[Bug Report] 样式表cdn地址无法访问

### ISSUE THREAD

**Issue by zxt-0709** [youzan/vant#10066]
### 重现链接

https://github.com/

### Vant 版本

2.12

### 描述一下你遇到的问题。

访问 https://cdn.jsdelivr.net/npm/vant@2.12/lib/index.css  失败,如下图
![image](https://user-images.githubusercontent.com/53303627/146713819-5dfc1242-39ce-484a-bd79-a257262e5ce6.png)

### 重现步骤

访问 https://cdn.jsdelivr.net/npm/vant@2.12/lib/index.css  失败,如下图
![image](https://user-images.githubusercontent.com/53303627/146713819-5dfc1242-39ce-484a-bd79-a257262e5ce6.png)

**Comment by lzt9977** [comment]
+1

**Comment by zxt-0709** [comment]
收到，辛苦你们了。。。

**Comment by imzhongran** [comment]
+1 cdn访问不了了

**Comment by imzhongran** [comment]
> 收到了，辛苦你们了。。。

可以发我一份js和css吗

**Comment by ccqwert** [comment]
换成以下地址
https://unpkg.com/vant@2.12/lib/index.css
https://unpkg.com/vant@2.12/lib/vant.min.js

**Comment by imzhongran** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月20日(星期一) 下午2:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant] [Bug Report] 样式表cdn地址无法访问 (Issue #10066)





 
换成以下地址
 ***@***.***/lib/index.css
 ***@***.***/lib/vant.min.js
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zxt-0709** [comment]
好的,辛苦了,应该是cdn挂了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月20日(星期一) 下午2:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant] [Bug Report] 样式表cdn地址无法访问 (Issue #10066)





 
换成以下地址
 ***@***.***/lib/index.css
 ***@***.***/lib/vant.min.js
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenjiahan** [comment]
看起来是 jsdelivr 崩了，可以换其他 CDN 试试

![image](https://user-images.githubusercontent.com/7237365/146723160-836f2fdb-0bfb-4e4c-b77e-51e9d585af70.png)

**Comment by cangyu1993** [comment]
jsdelivr 崩了，使用https://unpkg.com/vant@2.12.22/lib/index.css替代，js -- https://unpkg.com/vant@2.12.22/lib/vant.min.js

我用的2.12.22版本，亲测可用，这种cdn网站奔溃很难搞，echarts官网都乱七八糟的

**Comment by MyCodeMyWorld** [comment]
+1

**Comment by chenjiahan** [comment]
jsdelivr 已恢复

**Comment by cangyu1993** [comment]
这次这个问题cdn也没说明，突然崩溃太难搞了

**Comment by chenjiahan** [comment]
这次 jsdelivr 的问题只影响了中国用户，twitter 上有官方说明

![image](https://user-images.githubusercontent.com/7237365/146857533-bc0d55f3-7cbd-47af-975a-622d4b7a0d9c.png)
