### ISSUE TITLE
关于form标签

### ISSUE THREAD

**Issue by sancojiang** [youzan/vant#1006]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by sancojiang** [comment]
<template>
  <form name='loginForm'>
  ......
<template>

<script>
    methods:{
      login:function(){
        onLogin(loginForm,self);
      }
    }
</script>

提示不能识别loginForm，请问是否form标签名写错了，还是其它原因？

**Comment by chenjiahan** [comment]
不是很理解这个问题

**Comment by sancojiang** [comment]
在 2018-05-08 19:47:50，"neverland" <notifications@github.com> 写道：


不是很理解这个问题
