### ISSUE TITLE
[Bug Report] 使用文档种的CDN地址不能使用了

### ISSUE THREAD

**Issue by guanyueyun** [youzan/vant#10067]
### 重现链接

https://youzan.github.io/vant/?source=vuejsorg#/zh-CN/quickstart

### Vant 版本

2.12

### 描述一下你遇到的问题。

使用文档种的CDN地址不能使用了

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/vant@2.12/lib/index.css"
/>

<script src="https://cdn.jsdelivr.net/npm/vue@2.6/dist/vue.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vant@2.12/lib/vant.min.js"></script>

### 重现步骤

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/vant@2.12/lib/index.css"
/>

<script src="https://cdn.jsdelivr.net/npm/vue@2.6/dist/vue.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vant@2.12/lib/vant.min.js"></script>

**Comment by chenjiahan** [comment]
看起来是 jsdelivr 崩了，可以换其他 CDN 试试

![image](https://user-images.githubusercontent.com/7237365/146723160-836f2fdb-0bfb-4e4c-b77e-51e9d585af70.png)
