### ISSUE TITLE
[Bug Report] van-swipe 组件报 Cannot read properties of null (reading 'width')

### ISSUE THREAD

**Issue by lfchao** [youzan/vant#10075]
**vant 版本:  2.12.30**
**vue 版本:2.6.11**
**设备/浏览器:  Chrome, iOS, android**
**问题描述及报错图片**
在初始化并展示数据后, 触发van-swipe滑动事件报 Cannot read properties of null (reading 'width')错误
<img width="1326" alt="WeChat579522c38a57cf31c3a0b0c49842ec2c" src="https://user-images.githubusercontent.com/19701282/146920945-f7063f4b-6e08-479e-8eb0-d00e6a3a98fc.png">
<img width="1271" alt="WeChate5d4bde950b14b41c93071c321960794" src="https://user-images.githubusercontent.com/19701282/146920955-fd02765c-b876-48ce-ac3b-0ae86ae77e27.png">
，

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by lfchao** [comment]
问题原因：父组件使用v-show,页面跳转后goback会出现此问题，父组件改用v-if即可解决问题
