### ISSUE TITLE
[Feature Request] Picker 选项为空时隐藏选择条

### ISSUE THREAD

**Issue by exworth** [youzan/vant#10084]
### What problem does this feature solve?

当前Picker 中的 columns 为空数组的时候，会展示一个空的选择条，很奇怪
希望当 Picker 中的 columns 为空数组的时候，不展示 选择条，用户可以通过slot插槽自定义一个空数组交互

### What does the proposed API look like?

此项不需要

**Comment by chenjiahan** [comment]
已在 3.4.0 版本修复
