### ISSUE TITLE
[Bug Report] Pagination 分页组件change事件不生效

### ISSUE THREAD

**Issue by Adaer** [youzan/vant#10083]
### 重现链接

https://youzan.github.io/vant/v3/#/zh-CN/pagination

### Vant 版本

3.3.4

### 描述一下你遇到的问题。

官方文档指示分页组件的事件为change事件，但是这个事件不生效，然后我绑定click事件居然有效，是否是官网文档有误？

`
       <van-pagination
            v-model="currentPage"
            :total-items="30"
            :show-page-size="5"
            @change="onPageChange"   // 不生效的
            @click="onPageClick"   // 有效的
          />
`

### 重现步骤

`
 import { Pagination } from 'vant';
 ...
 
     components: {
      [Pagination.name]: Pagination
    }
   ... 
           <van-pagination
            v-model="currentPage"
            :total-items="30"
            :show-page-size="5"
            @change="onPageChange"   // 不生效的
            @click="onPageClick"   // 有效的
          />
`
 

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
该问题已经在 v3.3.7 版本修复

**Comment by chenjiahan** [comment]
click 事件是原生事件，默认会继承并生效。
