### ISSUE TITLE
Van Cli 使用vue3最新版本，在组件里面使用组件，导致打包不能打包到组件里面使用的组件

### ISSUE THREAD

**Issue by weilkss** [youzan/vant#10098]
### 重现链接

https://github.com/weilkss/taktak-h5-ui.git

### Vant Cli 版本

3.9.0

### 描述一下你遇到的问题。

在写组件的时候，抽离了逻辑组件，打包的时候没有打包到抽离的组件，目前是个空文件夹

### 重现步骤

1.克隆仓库
2.安装依赖包
3.npm run build 构建成功，但是缺少文件

**Comment by weilkss** [comment]
原因：没有导出组件名称

**Comment by chensbox** [comment]
是用script setup写法吗？

**Comment by chensbox** [comment]
是用script setup写法吗？
