### ISSUE TITLE
<van-dialog v-model="show" title="标题" show-cancel-button>  </van-dialog>如何监听确定和取消

### ISSUE THREAD

**Issue by lixiusen** [youzan/vant#10093]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/dialog#zu-jian-diao-yong-2

### Vant 版本

3.2.0

### 描述一下你遇到的问题。

<van-dialog v-model="show" title="标题" show-cancel-button>  </van-dialog>如何监听确定和取消

### 重现步骤

点击确定

**Comment by lixiusen** [comment]
使用confirm
<van-dialog v-model="buyDialog" @confirm="confirmBuy" theme="round-button" confirm-button-text="确认购买" close-on-click-overlay="true">

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/147412060-f1555292-c0bc-4c4b-a620-ee3f4207f952.png)
