### ISSUE TITLE
[Bug Report] popup组件关闭时，触发两次close事件

### ISSUE THREAD

**Issue by FreedomFoolt** [youzan/vant#10100]
### 重现链接

https://codesandbox.io/s/vant-issue-tx53g?file=/src/App.vue

### Vant 版本

3.3.7

### 描述一下你遇到的问题。

popup组件关闭时，触发两次close事件

期望的是只触发一次@close事件

### 重现步骤

点击按钮，关闭Popup，查看控制台，触发两次close事件

### 设备/浏览器

Chrome

**Comment by chenjiahan** [comment]
已在 3.4.0 版本修复
