### ISSUE TITLE
English Version of tags.json, web-types.json, attributes.json

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10105]
### What problem does this feature solve?

Good day

I kindly request full english version of the above mentioned files. I have discovered that its far more easier for me to learn and adopt Vant for my needs using these files. More importantly is the web-types file.

Do you have these available please? I am using the CDN version of Vant is its awesome.

Thanks.

### What does the proposed API look like?

This will help me adopting Vant to create Apps. Thanks

**Comment by chenjiahan** [comment]
Supported in v3.4.2.

**Comment by chenjiahan** [comment]
Vant for Vue2 currently only provides bugfix updates, we currently  focus on Vant 3 developing.
