### ISSUE TITLE
分页插件上下页按钮点击时没有锁住按钮，重复点击造成数据叠加

### ISSUE THREAD

**Issue by zhuangchongyi** [youzan/vant#10109]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/pagination#yin-ru

### Vant 版本

2.12.37

### 描述一下你遇到的问题。

https://vant-contrib.gitee.io/vant/#/zh-CN/pagination#yin-ru
分页插件上下页按钮点击时没有锁住按钮，重复点击造成数据叠加

### 重现步骤

![image](https://user-images.githubusercontent.com/50283491/147535746-12157883-1a5f-4055-abab-e768ae804ce0.png)

### 设备/浏览器

谷歌浏览器

**Comment by chenjiahan** [comment]
组件本身不会锁定事件的，你可以通过一个内部状态来进行判断
