### ISSUE TITLE
[Feature Request] 支持 Volar 的全局组件类型提示

### ISSUE THREAD

**Issue by jiyingzhi** [youzan/vant#10102]
### 这个功能解决了什么问题？

支持 Volar 的全局组件类型提示，目前的全局组件提示只支持 WebStorm 和 Vetur，不支持 Volar

### 你期望的 API 是什么样子的？

参考：
https://github.com/vueComponent/ant-design-vue/blob/next/typings/global.d.ts
https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#using

**Comment by chenjiahan** [comment]
已在 3.4.0 版本支持
