### ISSUE TITLE
[文档BUG] Popup文档应该是 v-model:show="show"

### ISSUE THREAD

**Issue by l1shu** [youzan/vant#10112]
### 重现链接

0

### Vant 版本

3.3.5

### 描述一下你遇到的问题。

<img width="727" alt="wecom-temp-20b6ac090355c298a4f005daf7bea32e" src="https://user-images.githubusercontent.com/48285873/147570422-d6b90fe1-cba2-412c-a710-90ea779429a1.png">

### 重现步骤

如图

**Comment by chenjiahan** [comment]
注意文档版本，Vant 3 对应的是 https://vant-contrib.gitee.io/vant/v3/#/zh-CN
