### ISSUE TITLE
datetime-picker 在动态设置minDate和maxDate后，currentDate绑定无效

### ISSUE THREAD

**Issue by wjw-gavin** [youzan/vant#10110]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-enz2x?file=/src/App.vue:93-112

### Vant 版本

2.12.37

### 描述一下你遇到的问题。

datetime-picker 在动态设置minDate和maxDate后，currentDate绑定无效

### 重现步骤

1、点击按钮，打开时间弹框
2、选择一个不同的时间（确定或不确定都可以），关闭时间弹框
3、再次点击按钮，绑定的当前时间 currentDate 失效

**Comment by chenjiahan** [comment]
可以加个 nextTick 来解决

```js
handleDatePicker2() {
    this.maxDate = new Date(2020, 1, 1);
    this.maxDate = new Date(2030, 1, 1);
    this.$nextTick(() => {
      this.currentDate = new Date("2022.12.12");
    });
    this.datePopupShow = true;
  },
```

**Comment by wjw-gavin** [comment]
> 可以加个 nextTick 来解决
> 
> ```js
> handleDatePicker2() {
>     this.maxDate = new Date(2020, 1, 1);
>     this.maxDate = new Date(2030, 1, 1);
>     this.$nextTick(() => {
>       this.currentDate = new Date("2022.12.12");
>     });
>     this.datePopupShow = true;
>   },
> ```

经过我自己试验，结果并不是这样。如果是你上面写的那样的话，currentDate 会默认成当前时间，像下面这样，currentDate首次会生效
```js
   handleDatePicker2() {
      this.maxDate = new Date(2020, 1, 1);
      this.maxDate = new Date(2030, 1, 1);
      // this.currentDate = new Date("2020.11.11");
      // this.datePopupShow = true;
      this.$nextTick(() => {
        this.currentDate = new Date("2022.12.12");
        this.datePopupShow = true;
      });
      // this.datePopupShow = true;
   }
```
但是这样，又会出现最开始的问题，当第二次切换后，currentDate又会失效，还烦请再看下。
@chenjiahan
