### ISSUE TITLE
[Bug Report] IOS  van-tabs 无法左右滑动，安卓下正常

### ISSUE THREAD

**Issue by sunhao0313** [youzan/vant#10119]
### 重现链接

暂无

### Vant 版本

2.12.36

### 描述一下你遇到的问题。

IOS  van-tabs 无法左右滑动，安卓下正常

### 重现步骤

IOS  van-tabs 无法左右滑动，安卓下正常

**Comment by chenjiahan** [comment]
请提供有效的复现链接

**Comment by yehoan** [comment]
想问一下van-tab 必须占满整行嘛  
![image](https://user-images.githubusercontent.com/22631753/147725518-5527fd56-36cb-4f34-9dbb-9d78c9c706df.png)
类似这种左边是tab 右边又不是tab 这样得怎么设置 发现我们得都是自动占满得

**Comment by chenjiahan** [comment]
@yehoan 目前可以通过覆盖样式来实现，后续我们会加一个对应的 props 来控制

**Comment by yehoan** [comment]
覆盖样式有个BUG

**Comment by yehoan** [comment]
我发现就是如果tab 占80% 筛选占20%
那么里面的content 就只能占80%  不能占100%

**Comment by yehoan** [comment]
这样也不行 哎

**Comment by yehoan** [comment]
而且props 不是简单的 一个按钮 还可以展开 选择 这个好想还很难
