### ISSUE TITLE
[Bug Report] @vant/area-data 一处数据错误

### ISSUE THREAD

**Issue by flamura** [youzan/vant#10115]
### 重现链接

w/o repro

### Vant 版本

@vant/area-data@1.1.5

### 描述一下你遇到的问题。

桃园县已改制直辖市
https://github.com/youzan/vant/blob/fff5fa9fa7b70de45ef11f4a819445b9e7db490a/packages/vant-area-data/src/index.ts#L393

### 重现步骤

w/o repro

### 设备/浏览器

all

**Comment by chenjiahan** [comment]
已发布 1.2.1 版本
