### ISSUE TITLE
[Bug Report] indexBar的sticky-offset-top设置在IOS手机中有问题

### ISSUE THREAD

**Issue by FAOfao931013** [youzan/vant#10118]
### 重现链接

https://49bxg.csb.app/

### Vant 版本

2.12.2

### 描述一下你遇到的问题。

在ios手机中 设置 `sticky-offset-top` 为 64 
类名为 `van-index-anchor van-index-anchor--sticky van-hairline--bottom` 的元素的 style 为 `width: 375px; transform: translate3d(0px, 128px, 0px); color: rgb(10, 132, 255);`

这里有问题：translate3d 的 Y 值 为 设置值的2倍 

有截图
![15911640772370_ pic](https://user-images.githubusercontent.com/16414167/147652132-357a7895-be07-4938-b06f-cdf31bc9273e.jpg)
![15921640772371_ pic](https://user-images.githubusercontent.com/16414167/147652167-dd170013-fb88-4caf-ad6d-2c956c0a2472.jpg)

### 重现步骤

设置 `van-index-bar` 的 `sticky-offset-top` 为 64 然后在 ios 手机中查看

### 设备/浏览器

ios手机

**Comment by chenjiahan** [comment]
使用 iphoneXR 打开上述链接，未复现该问题喔，建议排查下是不是项目中的其他逻辑引起的问题
