### ISSUE TITLE
Search组件部分事件类型缺失

### ISSUE THREAD

**Issue by wubiandaxian** [youzan/vant#10114]
### 重现链接

https://vant-contrib.gitee.io/vant/v3/#/zh-CN/search

### Vant 版本

3.3.7

### 描述一下你遇到的问题。

Search组件一些事件没有类型，jsx下缺失类型提示

### 重现步骤

```
<Search onClear={()=>console.log(123)} />
```

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
已在 3.4.0 版本修复

**Comment by wubiandaxian** [comment]
> 已在 3.4.0 版本修复

看了下提交的修改，增加了事件的触发处理，但是没有完善事件的类型，生成的类型文件里面依旧只有三个事件，其他事件依旧是获取不到类型提示的

源码类型文件, search/index.d.ts:
```
 & {
    "onUpdate:modelValue"?: ((...args: any[]) => any) | undefined;
    onCancel?: ((...args: any[]) => any) | undefined;
    onSearch?: ((...args: any[]) => any) | undefined;
},
```

**Comment by chenjiahan** [comment]
@wubiandaxian 类型定义是根据 emits 自动生成的，我看了下没问题

https://cdn.jsdelivr.net/npm/vant@3.4.0/lib/search/index.d.ts
