### ISSUE TITLE
Uploader ios15上传图片过大无法上传

### ISSUE THREAD

**Issue by hyssopu** [youzan/vant#10117]
### 重现链接

 <van-uploader             v-model="imgList"             :after-read="afterRead"             :max-count="subData.type === '1' ? 9 : 3"             @delete="deleteImg($event)"           />

### Vant 版本

2.12.35_vue@2.6.14

### 描述一下你遇到的问题。

在ios15系统的手机无法上传4.6M以上的图片

### 重现步骤

上传图片，无照片回显；体积较小的图片没问题

### 设备/浏览器

ios15

**Comment by chenjiahan** [comment]
请提供有效的复现链接

**Comment by hyssopu** [comment]
邮件已收到，谢谢

**Comment by yangtoude** [comment]
同问，我也遇到这个问题了，vant版本：2.12.30，图片大小8M以上，在微信浏览器里操作。

iphoneXS --  有问题，选择图片没有触发回调
ios 15.3
微信wx 8.0.18

**Comment by hyssopu** [comment]
邮件已收到，谢谢

**Comment by zb188** [comment]
同问，我也遇到这个问题了，vant版本：2.12.48，图片大小10M以上，在微信浏览器里操作。

iphoneXS -- 有问题，选择图片没有触发回调
ios 15.2
微信wx 8.0.18
