### ISSUE TITLE
[Bug Report] Vue3 script setup 引入组件 会报警告

### ISSUE THREAD

**Issue by sc544177047** [youzan/vant#10122]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-ty8zz

### Vant 版本

3

### 描述一下你遇到的问题。

非app.vue文件 其他script setup 引入vant非全局注册组件会报警告 如以下
runtime-core.esm-bundler.js:6591 [Vue warn]: Failed to resolve component: van-action-sheet
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <StoreQuene onVnodeUnmounted=fn<onVnodeUnmounted> ref="child" > 
  at <RouterView key=1 > 
  at <VanPullRefresh disabled=false onRefresh=fn<onPullDownRefresh> modelValue=false  ... > 
  at <App>

### 重现步骤

参考重现链接代码以及遇到问题

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
`import { ActionSheet } from "vant";` 对应的标签名是 `<action-sheet />`，建议再读下 Vue 文档。

**Comment by accardo** [comment]
我也有这个问题，无法解决

**Comment by lovefeng0709** [comment]
import { Button as VanButton } from "vant";   <van-button type="primary">主要按钮</van-button> like this,   I use vant4  vite3  done!
