### ISSUE TITLE
van-tabs 怎么实现和非 tabs 得组件并列一行显示

### ISSUE THREAD

**Issue by yehoan** [youzan/vant#10124]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-plh56?file=/src/App.vue

### Vant 版本

2.12.37

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/22631753/147727281-3febf40a-e814-4db1-bbe1-9d76bf4a5f30.png)
现在有个需求就是希望同一行中vant-tab可以不占满一整行 

### 重现步骤

codesandbox 

### 设备/浏览器

每个设备

**Comment by yehoan** [comment]
发现tab必须占满一整行  虽然用CSS flex可以实现但是下面得内容又会出现不粘满整行得情况

**Comment by yehoan** [comment]
能不能告诉一下这个源码功能看看能不能写一个...

**Comment by chenjiahan** [comment]
已在 3.4.0 版本新增 shrink 属性

**Comment by bbhxwl** [comment]
> 已在 3.4.0 版本新增 shrink 属性

    "vant": "^2.12.44",
我这个版本能实现么？我使用vue2，不是3
