### ISSUE TITLE
[Bug Report] picker自定义 Columns 的结构

### ISSUE THREAD

**Issue by LiuYuLu** [youzan/vant#10120]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-p2k73?file=/src/App.vue:0-561

### Vant 版本

3.3.2

### 描述一下你遇到的问题。

自定义columns-field-names 后组件报错
```
const columns = [
      { label: "浙江", value: "浙江" },
      { label: "福建", value: "福建" },
];
const customFieldName = { text: "label", values: "value" };
```

### 重现步骤

使用后报错

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/9846

**Comment by LiuYuLu** [comment]
问题解决了，如果是单列的选择框 values 不能随意指定，只指定label，处理事件时参数是Object对象，可以从中获取value值。
