### ISSUE TITLE
[Bug Report] Button 组件 disabled Props 特定设备上无效

### ISSUE THREAD

**Issue by DesBisous** [youzan/vant#10126]
### 重现链接

https://codesandbox.io/s/trusting-shockley-qgwj7?file=/src/App.vue

### Vant 版本

2.12.16

### 描述一下你遇到的问题。

Button 组件在特定设备上，设置了disabled 为 true 无效：
`<van-button :disabled="true">`

设备信息：
- Product：iPhone 12
- Version：v15.1.1

目前本人解决方案：对 Button 设置 disable 的时候，设置 CSS：
```
.van-button--disabled {
    pointer-events: none;
}
```

### 重现步骤

1. 将 Button 组件设置为 :disable="true"
2. 在上述设备 Safari 打开校验

### 设备/浏览器

iPhone 12

**Comment by chenjiahan** [comment]
无效指的是样式失效还是事件触发问题呢？

**Comment by DesBisous** [comment]
> 不是指样式失效还是事件触发问题呢？

您好，是事件触发问题，禁止了但是还能触发

**Comment by chenjiahan** [comment]
使用一台 iOS 15.1.0 的设备未复现此问题，并且事件触发是由 JS 逻辑控制的，不太可能出现问题描述中的兼容问题。

![image](https://user-images.githubusercontent.com/7237365/149441244-fad09627-e838-4dc6-9241-220ca98762f3.png)

**Comment by mengxiaodi** [comment]
@chenjiahan 你好，你提的确实没问题。代码层面没问题。但事实上，确实存在此bug。因为你写的代码只绑定了click，但是click这个方法绑定后，在小程序上点击无效。所以，我们都用@click.native="方法名"。你试试

**Comment by chenjiahan** [comment]
这个 Issue 聊的是 Vue 组件的问题，跟小程序没关系

**Comment by mengxiaodi** [comment]
@chenjiahan 真好，回复这么快。我使用的是vue+uniapp+vant，在开发的时候碰到这个问题。我看网上也有类似的问题。现在在看你们封装的组件

**Comment by chenjiahan** [comment]
噢噢，Vant 本身没有对 uni-app 作过专门的适配，所以遇到相关问题需要自行解决了哈

**Comment by mengxiaodi** [comment]
好的，我查下。回头把解决方案及详细搞出来。感谢！

**Comment by mengxiaodi** [comment]
bug找到了，其实我们在使用vue中的事件的时候，习惯性的将v-bind简写为@，比如`<div @click="xx">a</div>`。但是在vant+uniapp+vue开发的时候，绑定事件是bind:onclick='xx'。这个改完后，基本上disabled和onclick没有问题了。ps：官网确实也是让用 :bind 绑定。而我使用的是@onclick.native='xx'，就会导致disabled之后，还能点击。
正确代码：`<van-button bind:click="buy" type="primary">vantbutton</van-button>`
错误代码：`<van-button @click="buy" type="primary">vantbutton</van-button>
<van-button @click.native="buy" type="primary">vantbutton</van-button>`,
