### ISSUE TITLE
[Bug Report] TabBar 组件, 在 IOS 实机中, 底部安全区适配的问题

### ISSUE THREAD

**Issue by lacker159** [youzan/vant#10131]
### 重现链接

https://github.com/lacker159/21211230

### Vant 版本

2.12.37

## 问题描述:  
在 苹果12 的微信 webview 中测试时, TabBar 设置 fixed , 参数 placeholder 值为 true. TabBar 位置生成的占位元素高度是 TabBar 原始高度 ( 新的高度 = 原始高度 + 底部操作条的高度 ? ) , 导致部分内容被遮挡. 但是手动点击 微信webview 自带的刷新后, 占位元素的高度就显示正常了. 

### 重现步骤

苹果10及以上的手机, 通过微信打开演示网址

### 设备/浏览器

苹果10及以上 / 微信webview

**Comment by chenjiahan** [comment]
这个问题确实存在，应该是 iOS 系统本身的问题，没有即时返回正确的高度值，参见 https://stackoverflow.com/questions/64891541/get-safe-area-inset-bottom-on-page-load。

后续会在组件内兼容一下。

**Comment by chenjiahan** [comment]
已在 2.12.39 版本修复
