### ISSUE TITLE
[Bug Report] uniapp 打包时报错  'isVNode' is not exported 

### ISSUE THREAD

**Issue by Tursun-jan** [youzan/vant#10159]
### 重现链接

https://codesandbox.io/s/m5v3f

### Vant 版本

3

### 描述一下你遇到的问题。

uniapp 可正常运行 打包时报错  'isVNode' is not exported by node_modules\@dcloudio\uni-mp-vue\dist\vue.runtime.esm.js, imported by node_modules\@vant\use\dist\esm\index.js

### 重现步骤

uniapp 打包

**Comment by chenjiahan** [comment]
vant 没有单独适配 uni-app 喔，请到 uni-app 侧进行反馈。

**Comment by xionghaizhi** [comment]
> ### 重现链接
> https://codesandbox.io/s/m5v3f
> 
> ### Vant 版本
> 3
> 
> ### 描述一下你遇到的问题。
> uniapp 可正常运行 打包时报错 'isVNode' is not exported by node_modules@dcloudio\uni-mp-vue\dist\vue.runtime.esm.js, imported by node_modules@vant\use\dist\esm\index.js
> 
> ### 重现步骤
> uniapp 打包
> 
> ### 设备/浏览器
> _No response_

有解决吗？

**Comment by WEBwynn** [comment]
有人解决了吗😅

**Comment by xionghaizhi** [comment]
主人正在开机自检，键盘鼠标看好机会出去凉快去了，我是他的电冰箱，我打字比较慢，你慢慢说，别急…… 哦，对于您的邮件呀，我会先放在冷冻层冷冻起来，放心。

**Comment by Suminger** [comment]
现在还是这样 emm

**Comment by xionghaizhi** [comment]
> > ### 重现链接
> > https://codesandbox.io/s/m5v3f
> > ### Vant 版本
> > 3
> > ### 描述一下你遇到的问题。
> > uniapp 可正常运行 打包时报错 'isVNode' is not exported by node_modules@dcloudio\uni-mp-vue\dist\vue.runtime.esm.js, imported by node_modules@vant\use\dist\esm\index.js
> > ### 重现步骤
> > uniapp 打包
> > ### 设备/浏览器
> > _No response_
> 
> 有解决吗？

没有

**Comment by ouyangzx** [comment]
h5预览正常,
打包成微信小程序时，爆出同样的问题。2022年7月18日。

**Comment by a798032825** [comment]
打包成微信小程序时，爆出同样的问题。2022年7月25日。

**Comment by M-cheng-web** [comment]
打包成微信小程序时，爆出同样的问题。2022年9月8日。

**Comment by JuYiYang** [comment]
vant不是给微信小程序用的 它有一个专门的版本 vant-weapp
文档链接 ：https://vant-contrib.gitee.io/vant-weapp/#/home

**Comment by lazy1213099151** [comment]
vant-weapp 版本适配不了uniapp+vue3搭建的项目架构，只限于原生小程序版本
