### ISSUE TITLE
[Bug Report] van-tabs开启scrollspy后的bug

### ISSUE THREAD

**Issue by zhoup-x** [youzan/vant#10152]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-w3z7m?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675

### Vant 版本

2.0.12

### 描述一下你遇到的问题。

快速点击两下tab,内容区滚动到正确位置,但是tab选中状态会变成上一个

### 重现步骤

van-tabs开启scrollspy和sticky模式，快速点击两下tab

重现：请在真机浏览器中打开链接，快速点击两下标题b-tab

### 设备/浏览器

真机浏览器 android/ios

**Comment by chenjiahan** [comment]
这里 `标题 c` 的内容高度是不足一屏的，滚动到页面底部后，实际的位置仍然处于 `标题 b` 的区域范围内，因此会出现这个现象是正常的。

**Comment by Pentium286** [comment]
> 这里 `标题 c` 的内容高度是不足一屏的，滚动到页面底部后，实际的位置仍然处于 `标题 b` 的区域范围内，因此会出现这个现象是正常的。

有解决办法吗？

**Comment by yoyo837** [comment]
> 这里 `标题 c` 的内容高度是不足一屏的，滚动到页面底部后，实际的位置仍然处于 `标题 b` 的区域范围内，因此会出现这个现象是正常的。

这个逻辑应该还可以优化一下：如果是主动点击的，即便不足也按照点击的来显示，如果滚动了，则按计算的。
