### ISSUE TITLE
vant组件样式没有使用:root中的变量，而是具体的数值，导致修改:root变量无效

### ISSUE THREAD

**Issue by jiaxing-1994** [youzan/vant#10162]
### 重现链接

暂无

### Vant 版本

v3.0.11

### 描述一下你遇到的问题。

修改:root中的样式变量，没有生效。我对比了一下官网和我的项目，发现官网中的样式采用的是:root中的变量，而我的项目却是具体的值。
官网:
![image](https://user-images.githubusercontent.com/26563716/148502969-933f8730-998b-40e4-94ef-876228d983a9.png)
我的项目:
![image](https://user-images.githubusercontent.com/26563716/148502921-59bda99a-d6cf-4b70-82b2-02bf130729e6.png)

### 重现步骤

暂无

**Comment by chenjiahan** [comment]
升级一下 vant 版本
