### ISSUE TITLE
Uploader - 文件在线预览功能

### ISSUE THREAD

**Issue by zengfanyu1** [youzan/vant#10168]
### 这个功能解决了什么问题？

当使用uploader组件，上传pdf、doc、xlsx文件时只能先下载这些文件才能查看它们，这样操作久了计较麻烦而且费流量。希望可以新增像图片预览的文件预览功能

### 你期望的 API 是什么样子的？

<van-uploader :image_preview="" />

**Comment by chenjiahan** [comment]
暂无计划支持呢
