### ISSUE TITLE
希望新增一个uploader文件预览功能

### ISSUE THREAD

**Issue by zengfanyu1** [youzan/vant#10169]
### 这个功能解决了什么问题？

在项目中，上传doc、pdf、xlsx、txt文件后需下载之后才能预览，比较麻烦，希望新增一个像上传图片之后预览的功能。

### 你期望的 API 是什么样子的？

<van-uploader :image_preview=""></van-uploader>

**Comment by chenjiahan** [comment]
暂无计划支持
