### ISSUE TITLE
[Bug Report] vant3的Area 省市区选择组件没有选中效果

### ISSUE THREAD

**Issue by wg5945** [youzan/vant#10160]
### 重现链接

https://youzan.github.io/vant/v3/#/zh-CN/area

### Vant 版本

3.4.0

### 描述一下你遇到的问题。

应该和picker组件一样，选中的行有颜色加深效果

下面这块结构没有了

```
<div class="van-picker__mask" style="background-size: 100% 110px;"></div>
<div class="van-hairline-unset--top-bottom van-picker__frame" style="height: 44px;"></div>
```

### 重现步骤

官网demo

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
已在 3.4.1 版本修复
