### ISSUE TITLE
[Feature Request] indeterminate prop for van-progress component

### ISSUE THREAD

**Issue by adarshmadrecha** [youzan/vant#10167]
### What problem does this feature solve?

Showing a "loading" progress bar when Network Request is running. This is specially required when we know particular API request is going to take time and we still want uses interact with the app. 

Example: https://vuetifyjs.com/en/components/progress-linear/#indeterminate

### What does the proposed API look like?

```xml
<van-progress indeterminate />
```

`indeterminate`  is `Boolean` prop which when applied shows loading.
See Example link above for the exact effect.

**Comment by chenjiahan** [comment]
Thanks for your suggestion, but we don't currently have plans to support this feature, it's not in our UI specs.
