### ISSUE TITLE
Swipe 轮播 怎么实现点击跳转?

### ISSUE THREAD

**Issue by YoungJudge** [youzan/vant#1016]
`  <van-swipe :autoplay="3000">
         <van-swipe-item v-for="(content, index) in slider" :key="index">
          <a :href="content.linkUrl">
              <img v-lazy="content.picUrl" @/>
          </a>
         </van-swipe-item>`

我尝试给他加了个超链接但是只要一滑动就跳转了。我希望的是用户点击跳转，滑动不跳转。请问应该怎么做?

**Comment by shi995548347** [comment]
我的是fastclik冲突

**Comment by chenjiahan** [comment]
未复现此问题，可能是其他插件导致。
