### ISSUE TITLE
[Bug Report]  Overlay组件在初始化时并未渲染

### ISSUE THREAD

**Issue by hxzAugustinus** [youzan/vant#10171]
### 重现链接

https://codesandbox.io/s/xenodochial-clarke-ty75s

### Vant 版本

3.4.1

### 描述一下你遇到的问题。

Overlay组件在vue3里, 初始化时并未渲染元素，表现形式类似于v-if ; 当show=true渲染一次后，后续多次展示隐藏，表现形式类似于v-show;
Overlay组件在vue2里,初始化和后续切换保持一致

### 重现步骤
 重现链接需要点一下刷新编译
![image](https://user-images.githubusercontent.com/14306029/148749261-ddf4f7e4-3277-42a5-afd9-38475e3490c1.png)
1.初始化无法查找到Overlay里的子元素；
2.点击渲染一次后，后续可以拿到Overlay里的子元素

### 设备/浏览器

谷歌浏览器

**Comment by hxzAugustinus** [comment]
我看了一下源码，貌似是因为lazy-render 引起的；但有些业务可能需要初次加载时就渲染，方便控制；
我这边需要做一个lottie 动画，需要尽快初始化 lottie 对象，初始化对象时，需要传入一个dom元素，来启动该对象下载资源；
所以能否把 是否启用 lazy-render 作为参数传入？

**Comment by chenjiahan** [comment]
确实是 lazy-render 引起的现象，后续可以加一个属性来控制

**Comment by jiangyong1998** [comment]
我在使用pullrefresh时也遇到了这个问题，同样需要使用Lottie初始化加载动画，看了一下源码里面是每次都push新的节点，能否也加一下这个功能
