### ISSUE TITLE
van-tabs 的 粘性布局offset-top在安卓中有效;offset-top在ios中无效,向上滑动后会始终吸附在页面最顶部

### ISSUE THREAD

**Issue by zh4242** [youzan/vant#10178]
### 重现链接

暂无链接

### Vant 版本

3.2.5

### 描述一下你遇到的问题。

van-tabs 的 粘性布局offset-top在安卓中有效;offset-top在ios中无效,向上滑动后会始终吸附在页面最顶部

### 重现步骤

van-tabs 的 粘性布局offset-top在安卓中有效;offset-top在ios中无效,向上滑动后会始终吸附在页面最顶部

**Comment by chenjiahan** [comment]
未复现此问题，请提供有效的 codesandbox 复现链接或复现视频
