### ISSUE TITLE
van-image组件width和height如何转换成rem

### ISSUE THREAD

**Issue by yaojin2070** [youzan/vant#10179]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-kv1y5?file=/src/App.vue:0-259

### Vant 版本

3.0.18

### 描述一下你遇到的问题。

`
<van-image
      width="100"
      height="100"
      src="https://img.yzcdn.cn/vant/cat.jpeg"
    />
`
van-image组件虽然提供了width 和 height 的props传递, 但是它是通过内联样式设置的, px无法转换成rem, 有更好的办法吗?

### 重现步骤

查看链接即可

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
width 和 height 可以带单位的，比如 `width="2rem"`。

如果不带单位，是没法自动转成 rem 的。
