### ISSUE TITLE
vant 文档显示不准确

### ISSUE THREAD

**Issue by Sincenir** [youzan/vant#10170]
### 重现链接

https://youzan.github.io/vant-weapp/#/tab

### Vant 版本

2.12.37

### 描述一下你遇到的问题。

我在使用 tab 组件的 info 功能时，提示我 info 参数已弃用，请使用 badge 参数，但文档中并无该参数。
我在 sidebar 中才找看到该参数的用法。

最新的文档地址文档版本为 1.1.0。
有更新的文档地址吗？

### 重现步骤

文档错误。

**Comment by chenjiahan** [comment]
Vant 2.x 的文档地址是：https://vant-contrib.gitee.io/vant/#/zh-CN/
