### ISSUE TITLE
[Bug Report] Calendar 日历组件 选择日期区间问题

### ISSUE THREAD

**Issue by popring** [youzan/vant#10194]
### 重现链接

https://codesandbox.io/s/strange-forest-jj0s5?file=/src/App.vue

### Vant 版本

3.4.1

### 描述一下你遇到的问题。

日历组件，类型为选择区间(tyupe="range")，选择开始开始时间为 disabled 的前一天，然后选择结束日期为 disabled 后的任意一天，就会自动选择为开始和结束日期为同一天，而此时 allow-same-day 为false。

### 重现步骤

1、首先打开一个选择日期组件，日历组件设置不可选择同一天 `allow-same-day="false"`

2、如demo所示，日期为17、19、21日被disabled，此时如果开始时间选择16日，结束时间选择18日。

3、点击后效果，如下图所示。（最终选中的开始和结束时间都为 16日，且确定按钮可点击）。

![image](https://user-images.githubusercontent.com/31247906/149648530-f5945de6-7758-428a-b2fa-1295dff3989e.png)

### 设备/浏览器

移动端和PC预览均会出现

**Comment by popring** [comment]
如果 codesanbox demo 链接打开，显示 `Cannot use import statement outside a module` ，刷新右侧阅览区域即可

**Comment by chenjiahan** [comment]
已在 3.4.2 版本修复
