### ISSUE TITLE
[Feature Request] Cascader 支持隐藏 header 

### ISSUE THREAD

**Issue by shawn2016** [youzan/vant#10200]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vant@2.12.4` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vant/es/cascader/index.js b/node_modules/vant/es/cascader/index.js
index 865e60d..680c6bc 100644
--- a/node_modules/vant/es/cascader/index.js
+++ b/node_modules/vant/es/cascader/index.js
@@ -183,6 +183,9 @@ export default createComponent({
       this.$emit('close');
     },
     renderHeader: function renderHeader() {
+      if(!this.title){
+        return null
+      }
       var h = this.$createElement;
       return h("div", {
         "class": bem('header')
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by chenjiahan** [comment]
header 的内容包括了 props.title，slots.title 和 close 图标，因此在 title 不存在的情况下不应该直接隐藏 header。

后续会添加一个 show-header 属性来进行控制。
