### ISSUE TITLE
遍历checkbox之后，点击一个checkbox操作其他的checkbox的true或false 均触发change事件，然后其他checkbox点击没反应

### ISSUE THREAD

**Issue by jyx12138** [youzan/vant#1020]
<li v-for="(item,index) in billList">
          <van-checkbox v-model="item.checked" v-if="item.status == 0" @change="check(item.checked,index,item)"></van-checkbox>
          <div class="periodLeft">
            <p class="title"><span>第{{index+1}}期</span><img src="~@/assets/img/mall/order/expire.png" alt="" v-if="item.overdueStatus == 1"></p>
            <p class="date"><span>{{$formatDateYear(item.gmtPlanRepay) }} 应还</span></p>
          </div>
        </li>

**Comment by chenjiahan** [comment]
描述不清

**Comment by qiugu** [comment]
用一个checkbox捞控制其他的checkbox的全选或者是都不选，一旦点击控制全选的checkbox的话，再次点击其他的被控制的checkbox则不会生效，change方法也不能触发
