### ISSUE TITLE
[Feature Request] van-number-keyboard 配合van-field双向绑定时并且van-field设置了readonly时想要显示光标

### ISSUE THREAD

**Issue by zanghuohua256791** [youzan/vant#10209]
### 这个功能解决了什么问题？

ios输入手机号登陆时需要全数字键盘使用了组件后并且设置了readonly不会出现光标，如果不设置readonly，ios的原生键盘又会弹出来，很烦恼

### 你期望的 API 是什么样子的？

<van-field
          readonly
          clickable
          name="telephone"
          autocomplete="off"
          label=""
          :value="telephone"
          placeholder="请输入手机号"
          @touchstart.native.stop="keyboardShow('numShow', 'codeShow')"
          :rules="[{ required: true, trigger: 'onChange',validator: phoneValidator, message: '请输入正确的手机号' }]"
        />
          <van-number-keyboard
            v-model.trim="telephone"
            maxlength="11"
            :show="numShow"
            @blur="numShow = false"
            @focus="numShow"
          />

**Comment by chenjiahan** [comment]
readonly 时没法显示光标的，这个是浏览器决定的。

可以通过 div 模拟一个实现输入框。
