### ISSUE TITLE
[Bug Report] Vue2移动端van-search组件在http中的微信中样式丢失，并且滑动掉不出来

### ISSUE THREAD

**Issue by zoechen94** [youzan/vant#10215]
### Reproduction Link

http://zh-mobile-qa.ajmd-med.com/mobile-login.html

### Vant Version

2

### Describe the Bug

项目是vant移动端非webapp，开发时通过192.168局域网在手机微信中测试，van-search展示正常，侧滑单元格功能也正常。
but在项目到了Http上时候再从微信中使用，van-search错位，并且侧滑单元格功能也失效了，请问这会是什么原因呢
#

### Reproduce Steps

<van-search v-model="value" placeholder="请输入搜索关键词" />

<van-swipe-cell>
  <template #left>
    <van-button square type="primary" text="选择" />
  </template>
  <van-cell :border="false" title="单元格" value="内容" />
  <template #right>
    <van-button square type="danger" text="删除" />
    <van-button square type="primary" text="收藏" />
  </template>
</van-swipe-cell>
![2351642602145_ pic](https://user-images.githubusercontent.com/24960027/150150718-2b4ee30b-7eba-4026-a3dc-94009bd5223d.jpg)

### Device / Browser

安卓手机/微信端浏览

**Comment by chenjiahan** [comment]
建议你检查一下打包相关的逻辑，确保组件的 JS 和样式被正确打包进去了。

**Comment by zoechen94** [comment]
thank you

**Comment by sir-ran** [comment]
我也我遇到这个问题了，van-search 样式被van-cell的样式覆盖了，导致van-search样式错位

**Comment by xu-Aurora** [comment]
> 我也我遇到这个问题了，van-search 样式被van-cell的样式覆盖了，导致van-search样式错位

我也遇到了，请问最后你是怎么解决的？
