### ISSUE TITLE
[Bug Report] van-field 组件 类型为textarea时 v-show切换组件 autosize 没有重新计算高度

### ISSUE THREAD

**Issue by 879226489** [youzan/vant#10213]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-1md9i?file=/src/App.vue

### Vant 版本

2.12.39

### 描述一下你遇到的问题。

![6c9e8c8066a6ce4a116bea7dbd4a1b3](https://user-images.githubusercontent.com/54408067/150079869-607857f6-5056-49d4-92c0-cd27a6e2accd.png)

### 重现步骤

1. 点击切换2 按钮 输入框还是滚动展示 并没有全部展示内容

### 设备/浏览器

Chrome

**Comment by chenjiahan** [comment]
组件内部是无法感知到外部 v-show 的变化的，可以使用 v-if

**Comment by 879226489** [comment]
@chenjiahan 您好我看了一下源码 有监听值来动态计算 高度的 就算是v-show切换但是值是存在的 也没有进行重绘 高度却减少了 想问一下您可能是什么原因

**Comment by chenjiahan** [comment]
可能是 hidden 状态下设置的值，hidden 状态无法拿到正确的元素高度
