### ISSUE TITLE
更新 @vant/eslint-config

### ISSUE THREAD

**Issue by l-zoy** [youzan/vant#10219]
### 这个功能解决了什么问题？

我看升级了eslint 8 版本, 目前`@vant/eslint-config` test是跑不通的, 我准备提一下依赖更新及test更新, 涉及影响 `vue-eslint-plugin` 新增一条`vue/valid-next-tick`(https://github.com/vuejs/eslint-plugin-vue/issues/1399) 对组件库两个文件有lint报错, Area.tsx 313行 / CollapseItem.tsx 84行, 分别改写成`nextTick().then(xxx)` test 通过  ~~  看行不行

### 你期望的 API 是什么样子的？

empty

**Comment by chenjiahan** [comment]
可以滴，欢迎~
