### ISSUE TITLE
通过v-for遍历生成checkbox无法使用change事件

### ISSUE THREAD

**Issue by yaojin2070** [youzan/vant#10225]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-0ut1l?file=/src/App.vue

### Vant 版本

3.4.1

### 描述一下你遇到的问题。

业务通过v-for生成checkbox, 需要监听每个checkbox的事件,可是无法绑定change事件, 应该是每个checked没有改变导致的, 应该如何让change事件执行 ? 

### 重现步骤

打开连接, 点击单选框按钮

### 设备/浏览器

hrome

**Comment by chenjiahan** [comment]
用 reactive 定义 list

**Comment by yaojin2070** [comment]
> reactive

我尝试了并不行, 链接已经更新最新的代码

**Comment by yaojin2070** [comment]
目前解决办法只能绑定click事件并且并且调用实例的toggle事件, 拿到每个实例的数据

**Comment by chenjiahan** [comment]
使用 checkboux-group 时，change 事件要绑定要 checkboux-group 上。
