### ISSUE TITLE
[Feature Request] List组件不支持局部滚动？希望可以支持局部滚动的组件

### ISSUE THREAD

**Issue by wungjyan** [youzan/vant#10229]
### What problem does this feature solve?

尝试 `List` 组件做局部滚动，但没生效，是否是不支持？还是我没找到方法呢。。

### What does the proposed API look like?

`List` 组件是否会支持局部滚动呢，给 `List` 组件包一个固定高度的容器，使得组件实现局部滚动，类似这样：
```html
<div class="list-wrapper">
  <van-list>...</van-list>
</div>
```

**Comment by chenjiahan** [comment]
目前是支持的，如果遇到问题， 可以提供一个 codesandbox 复现链接看下

**Comment by wungjyan** [comment]
> 目前是支持的，如果遇到问题， 可以提供一个 codesandbox 复现链接看下

复现链接在这里：https://codesandbox.io/s/prod-snowflake-s93ct?file=/src/App.vue

我并没有实现出局部滚动，是我用错了方法？

**Comment by chenjiahan** [comment]
局部滚动对应的 overflow 是 scroll 或者 auto，不是 hidden。
