### ISSUE TITLE
area-data  缺少一个河北邢台市  信都区

### ISSUE THREAD

**Issue by zhanglingg** [youzan/vant#10226]
### 重现链接

无

### Vant 版本

area-data 1.2.1

### 描述一下你遇到的问题。

area-data 1.2.1   缺少一个河北邢台市  信都区

### 重现步骤

  缺少一个河北邢台市  信都区

**Comment by zhanglingg** [comment]
![image](https://user-images.githubusercontent.com/16555349/150713519-d6973e6c-ee0c-4482-8804-08af594a8de6.png)

**Comment by chenjiahan** [comment]
欢迎提 PR 帮忙完善数据

**Comment by chenjiahan** [comment]
已发布 @vant/area-data 1.2.2
