### ISSUE TITLE
node_modules 代码警告

### ISSUE THREAD

**Issue by cyanwin** [youzan/vant#10223]
### 重现链接

无

### Vant 版本

3.4.2

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/45061152/150538868-b9c50851-dedc-4b6f-be86-c1f2272e3d8d.png)

### 重现步骤

vue-cli 启动项目

**Comment by chenjiahan** [comment]
从报错上看与 Vant 无关，建议自行解决
