### ISSUE TITLE
ImagePreview 

### ISSUE THREAD

**Issue by mayday97** [youzan/vant#10233]
### 重现链接

http://152.136.26.182:90/hmc/test/list

### Vant 版本

3.3.5

### 描述一下你遇到的问题。

使用ImagePreview  函数调用预览图片（使用了teleport指定挂在节点），第一次进入页面可以正常预览，当返回列表在进入页面点击图片无法正常预览

### 重现步骤

1.进入test/list页面 点击详情一按钮进入详情页
2.点击富文本的图片，正常图片预览
3.返回列表
4.再次进入详情页点击图片预览

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接
