### ISSUE TITLE
[Bug Report] vant tab 不展示dom 问题

### ISSUE THREAD

**Issue by Yacj** [youzan/vant#10230]
### 重现链接

https://github.com/Yacj/read-novel-app

### Vant Cli 版本

3.4.2

### 描述一下你遇到的问题。

场景：一个父tab 里面有一个子 tab 每次切换父tab 子tab的数据 都会变化 
bug：每次切换 父 tab 后 子 tab 默认第一个 第二个的 van-tab__panel 这个dom 没有显示 只有第三 四 个 才有   以为是actived的问题 但是监听修改tab的active都没有用，尝试着把 tab 的 animated 改成 false 又有这个dom了  请问这个是不是 动态计算的问题

### 重现步骤

1 下载运行
2 有bug的tab 在 views/home/index.vue 第23行 修改animated 就可以复现

**Comment by Yacj** [comment]
又测试了下 bug 产生的场景  
父tab 默认第一个 正常
父tab 切换 且 animated swipeable 这两个属性 任何 一个为true  子tab的an-tab__panel 就没有展示
两个都是false 就正常

**Comment by chenjiahan** [comment]
下个版本会修复此问题
