### ISSUE TITLE
cell-swipe样式问题

### ISSUE THREAD

**Issue by 760157714** [youzan/vant#1023]
![image](https://user-images.githubusercontent.com/21232859/39793022-189d8d54-5376-11e8-9da6-ba0770660331.png)
![image](https://user-images.githubusercontent.com/21232859/39793052-40b61dd8-5376-11e8-8f6b-006760600858.png)
我在源码里没有找到这段样式代码，请问这哪块啊？

**Comment by rex-zsd** [comment]
看下你的引入方式是不是有问题

**Comment by chenjiahan** [comment]
这块的样式目前组件内没有提供的，完全由用户自己定义
