### ISSUE TITLE
ImagePreview

### ISSUE THREAD

**Issue by mayday97** [youzan/vant#10238]
### 重现链接

https://github.com/mayday97/vant-bug

### Vant 版本

3.3.5

### 描述一下你遇到的问题。

使用ImagePreview 函数调用预览图片（使用了teleport指定挂在节点），第一次进入页面可以正常预览，当返回列表在进入页面点击图片无法正常预览

### 重现步骤

1.进入test/list页面 点击详情一按钮进入详情页
2.点击富文本的图片，正常图片预览
3.返回列表
4.再次进入详情页点击图片预览

**Comment by chenjiahan** [comment]
这个是使用 Vue Teleport 时符合预期的现象。

按照上述的用法，ImagePreview 被挂载到了 `.report-detail` 节点下，随着返回上级列表，`.report-detail` 节点被销毁，内部的 ImagePreview 节点也同时被销毁了。

因此再次进入页面时，无法正常渲染 ImagePreview。

解决方法是把 `router-view` 与 `keep-alive` 结合使用，这样可以保留 ImagePreview 节点。

```xml
<router-view v-slot="{ Component }">
  <keep-alive>
    <component :is="Component" />
  </keep-alive>
</router-view>
```
