### ISSUE TITLE
[Bug Report] 引入报错

### ISSUE THREAD

**Issue by YYL1999** [youzan/vant#10231]
### 设备 / 浏览器
Mac版本微信开发者工具

### Vant 版本
3.4.2

### Vue 版本
3.2.29

### 重现链接
<a href="https://codesandbox.com" target="_blank">https://codesandbox.com</a>

### 描述问题
canIUseGroupSetData这个找不到

**Comment by chenjiahan** [comment]
Vant 里没有相关代码，建议自行排查下
