### ISSUE TITLE
[Feature Request] 只能用键盘或遥控操作的时候就废了

### ISSUE THREAD

**Issue by yondwell** [youzan/vant#10249]
### 这个功能解决了什么问题？

不支持触控的设备 只能用键盘操作，或遥控器操作的时候 可以响应键盘事件

### 你期望的 API 是什么样子的？

当然是支持纯键盘操作了，也更方便残障人士，对吧。

**Comment by chenjiahan** [comment]
你说的键盘指的是什么设备？手机上的虚拟键盘吗，能否具体描述下

**Comment by xmut** [comment]
> 你说的键盘指的是什么设备？手机上的虚拟键盘吗，能否具体描述下

我感觉他提的问题，跟我的需求类似：#10257

**Comment by chenjiahan** [comment]
了解，那统一在 10257 中跟进，这个 issue 先关了
