### ISSUE TITLE
[Bug Report] Stepper 步进器  before-change 参数获取问题bug

### ISSUE THREAD

**Issue by yemaozi999** [youzan/vant#10254]
### 重现链接

....

### Vant 版本

3.4.2

### 描述一下你遇到的问题。

Stepper 步进器       

使用异步改变,  无法取得第二个参数
before-change

van-stepper v-model="item.num" :name="item.id" :before-change="beforeChange" theme="round" button-size="22" disable-input /

const beforeChange = (value,detail) => {
  console.log(value);
  console.log(detail.name);
};

### 重现步骤

点击Stepper 步进器    +按钮

**Comment by chenjiahan** [comment]
before-change 并没有提供第二个参数，你可以仔细看下文档

**Comment by trkjoy** [comment]
如果有多个 Stepper 的情况下,只有一个value,如何区分到底是哪个呢?
