### ISSUE TITLE
[Feature Request] Dialog 弹出框能响应键盘回车事件

### ISSUE THREAD

**Issue by xmut** [youzan/vant#10257]
### 这个功能解决了什么问题？

感谢Vant，我们采用它构建一套移动端的仓储管理客户端，并安装到PDA终端上，类似京东等快递员界面。

现在碰到一个问题：某些录入操作时，可能弹出校验或警告信息对话框，仓管员需要手指去触摸屏幕上的【确认】按钮才能关闭它。而实际上，他们更想直接通过键盘回车键关闭它，这样操作更快捷，谢谢！

### 你期望的 API 是什么样子的？

```xml
<van-dialog title="警告" @keydown.enter="enterHandler">
```

**Comment by chenjiahan** [comment]
了解了，后续会考虑适配下。

**Comment by l-zoy** [comment]
这个api需要暴露出去么, 还是只需要支持enter/esc 就可以了

**Comment by chenjiahan** [comment]
从描述的场景看，应该不需要支持其他事件

**Comment by xmut** [comment]
> 这个api需要支持除enter/esc意外的事件么

暂不需要
