### ISSUE TITLE
Popup组件在oppo 手机兼容性显示异常

### ISSUE THREAD

**Issue by cyanwin** [youzan/vant#10269]
### 重现链接

无

### Vant 版本

3.4.2

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/45061152/152959218-a67e57e2-1a77-4175-b876-e02177981859.png)
在此oppo 机型上使用 Popup 组件 position="bottom" 从底部弹出会正常显示，但是输入内容后会被键盘遮挡

### 重现步骤

![image](https://user-images.githubusercontent.com/45061152/152959460-61b09048-c7a4-44cc-8f4f-40350a52efb9.png)
![image](https://user-images.githubusercontent.com/45061152/152959498-6227eee2-da29-41a6-8adf-12f823a9f63a.png)
![image](https://user-images.githubusercontent.com/45061152/152962192-14c34f34-9562-4dd0-b6dd-e4a9319b50e0.png)

### 设备/浏览器

安卓Oppo

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/7230
