### ISSUE TITLE
[Feature Request] 浮动动作按钮（Floating Action Button）

### ISSUE THREAD

**Issue by ArnoZWang** [youzan/vant#10264]
### 这个功能解决了什么问题？

浮动动作按钮作为鲜明的页面元素，可以用于强调某一种交互类型（引： [Material Design 中的浮动动作按钮](https://material.io/components/buttons-floating-action-button#usage)）。
此外，浮动动作按钮可以作为底部标签栏（Tabbar）的组成部分（引： [Material Design 中的底部标签栏](https://material.io/components/app-bars-bottom#usage)）。

### 你期望的 API 是什么样子的？

Vuetify 中有[类似设计](https://vuetifyjs.com/zh-Hans/components/floating-action-buttons/)。

**Comment by chenjiahan** [comment]
暂无计划支持喔
