### ISSUE TITLE
van-search 会有一个叉号是什么情况

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#10278]
### 重现链接

暂无

### Vant 版本

2.12.39

### 描述一下你遇到的问题。

![4EDCCB05-EB07-4338-92B0-6B44AF3071CB](https://user-images.githubusercontent.com/42430384/153359718-11a339ff-84ea-4df9-a94c-246e00b82b5c.png)

### 重现步骤

van-search 会有一个叉号是什么情况，，

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接
