### ISSUE TITLE
[Bug Report] Toast组件样式异常

### ISSUE THREAD

**Issue by FeiFanLiang** [youzan/vant#10283]
### 重现链接

复现图片

### Vant 版本

3.2.0

### 描述一下你遇到的问题。

在生产环境使用import {Toast}在当前页面引入时，如果下一个页面使用了Dialog组件，此时点击返回上一页，会导致.van-popup的上的background-color覆盖住当前页面的.van-toast 中的background-color，导致toast背景色变成白色，只能显示出白色方框

### 重现步骤

![image](https://user-images.githubusercontent.com/30872365/153538634-03e8bd91-98ba-4c7f-83ff-42fcc5f94313.png)

A页面使用Toast,B页面使用Dialog，A -> B再返回A页面，此时样式出现覆盖，A页面Toast样式不能正常显示

**Comment by chenjiahan** [comment]
建议检查下是不是引入了两份 van-popup 的样式，正常引入一份的话是不会出现这个现象的。

**Comment by Ali-Libra** [comment]
> 建议检查下是不是引入了两份 van-popup 的样式，正常引入一个词是不会出现这种现象的。

你好 我也出现了这个问题 我的样式是vite自动导入的

**Comment by Ali-Libra** [comment]
你好 我也出现了这个问题 我的样式是vite自动导入的

**Comment by FeiFanLiang** [comment]
目前项目中使用方法是按照官网的按需加载示例使用的，没有进行全局引入，全部使用在文件中import单组件方式使用

**Comment by Ali-Libra** [comment]
> 目前项目中使用方法是按照官网的按需加载示例使用的，没有进行全局引入，全部使用在文件中import单组件方式使用

我的解决方案是 给这个提示框给定一个自定义类名 然后在全局样式中把这个类名的背景颜色设置成黑色 这样提示框出来就不会是白屏的了

**Comment by starlet0822** [comment]
我现在也是遇到这个BUG

**Comment by atearsan** [comment]
我的处理方式：在```index.html```的```style```里覆盖.van-toast的background样式：
```css
.van-toast {
    background: var(--van-toast-background-color);
}
```
