### ISSUE TITLE
[Bug Report] Calendar 日历组件初始化后，month-show事件会触发两次

### ISSUE THREAD

**Issue by ma-lihui** [youzan/vant#10281]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-dwdjx?file=/src/App.vue

### Vant 版本

2.12.30

### 描述一下你遇到的问题。

Calendar 日历组件，设置一个最小日期，month-show事件会触发两次，一次是最小日期的那个月，一次是当前这个月

### 重现步骤

1. 日历组件，设置一个最小日期
2. 查看month-show触发次数

![image](https://user-images.githubusercontent.com/16605318/153528495-62da700a-b150-45e8-ae9f-4d1bd6c9c3bf.png)

**Comment by chenjiahan** [comment]
这个是符合预期的，因为 2 月和 3 月都展示出来了，所以会分别触发一次事件。

**Comment by ma-lihui** [comment]
> 这个是符合预期的，因为 2 月和 3 月都展示出来了，所以会分别触发一次事件。

@chenjiahan 并不是的，触发的是minDate的那个月，和当前月。minDate那个月，不应该触发。我猜测可能原因是日期组件初始化后滚动条在第一个月也就是minDate那里，然后滚动到当前月，所以造成了这个问题。

**Comment by chenjiahan** [comment]
你说的这个情况确实也可能存在喔
