### ISSUE TITLE
van-tab排序之后不会刷新页面

### ISSUE THREAD

**Issue by cpf121** [youzan/vant#10284]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-nhp2j?file=/src/App.vue

### Vant 版本

2.12.39

### 描述一下你遇到的问题。

改变数组排序之后，tab的排序不会变
![Uploading image.png…]()

### 重现步骤

1.点击按钮
2.排序不变

### 设备/浏览器

PC

**Comment by nemo-shen** [comment]
使用问题哦
试一下以下代码，**注意你的index使用**
```js
<van-tabs v-model="activeNames">
  <van-tab
    v-for="(item, index) in items"
    :key="index"
    :title="item.name"
    :name="item.name"
  >{{ item.name }}</van-tab>
</van-tabs>
```
