### ISSUE TITLE
van-datetime-picker发布后显示时会导致页面卡死

### ISSUE THREAD

**Issue by ljlivw** [youzan/vant#10282]
### 重现链接

暂时没有

### Vant 版本

3.4.2-3.4.4

### 描述一下你遇到的问题。

![Uploading image.png…]()

### 重现步骤

调试时没问题，发布后出现就会卡死界面。

### 设备/浏览器

所有浏览器

**Comment by chenjiahan** [comment]
请提供有效的复现链接或复现问题的最小仓库
