### ISSUE TITLE
[Bug Report] van-buttun在和tailwind3一起使用时, 使用type没法显示颜色

### ISSUE THREAD

**Issue by wodexintailuan** [youzan/vant#10280]
### 重现链接

暂无

### Vant 版本

3.4.3

### 描述一下你遇到的问题。

vue项目,使用tailwind3.0.8, 在代码中使用 van-button type="primary" , background被tailwind覆盖,无法显示蓝色
![image](https://user-images.githubusercontent.com/43602621/153401422-2628fe46-680b-4b55-9387-b2b1ea80c48a.png)

### 重现步骤

暂无

### 设备/浏览器

google

**Comment by chenjiahan** [comment]
这个和 Vant 没关系，你可以调整下样式表的引入顺序

**Comment by zzh948498** [comment]
@chenjiahan 我也遇到同样的问题
![image](https://user-images.githubusercontent.com/35091020/154885510-f78751b2-46dc-481a-bc45-7f47a6764fc4.png)
build完tailwind总是在vantcss之后，请问如何调整？
最小示例代码地址： https://github.com/zzh948498/vue-template

**Comment by jiriyao** [comment]
我也遇到这个问题了，有没有解决方案？

**Comment by jiriyao** [comment]
修改文件 tailwind.config.js
module.exports = {
  ...
  ...
  corePlugins: {
    preflight: false
  }
}

It 's worked for me.

**Comment by yoyo837** [comment]
> 修改文件 tailwind.config.js module.exports = { ... ... corePlugins: { preflight: false } }
> 
> It 's worked for me.

如果仍然需要这个样式的, 可以在关闭后, 手动在最前面引入`node_modules/tailwindcss/lib/css/preflight.css`, 从而降低优先级.
