### ISSUE TITLE
vant swipe 自定义滑块大小 移动端无法滑动

### ISSUE THREAD

**Issue by rendidi** [youzan/vant#10297]
### 重现链接

swipe  自定义滑块大小

### Vant 版本

3.2.5

### 描述一下你遇到的问题。

```xml
<div style="width: 400px;overflow: hidden;">
    <van-swipe :loop="false" :width="300">
      <van-swipe-item>1</van-swipe-item>
      <van-swipe-item>2</van-swipe-item>
      <van-swipe-item>3</van-swipe-item>
      <van-swipe-item>4</van-swipe-item>
    </van-swipe>
  </div>
```

### 重现步骤

移动端无法滑动

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by rendidi** [comment]
<div style="width: 400px;overflow: hidden;"&gt;
  <van-swipe :loop="false" :width="300"&gt;
    <van-swipe-item&gt;1</van-swipe-item&gt;
    <van-swipe-item&gt;2</van-swipe-item&gt;
    <van-swipe-item&gt;3</van-swipe-item&gt;
    <van-swipe-item&gt;4</van-swipe-item&gt;
  </van-swipe&gt;
</div&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月14日(星期一) 下午4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant] vant swipe 自定义滑块大小 移动端无法滑动 (Issue #10297)





 
麻烦提供一下 codesandbox 复现链接
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
