### ISSUE TITLE
vant-cli可以支持ts吗

### ISSUE THREAD

**Issue by ywymoshi** [youzan/vant#10293]
### 这个功能解决了什么问题？

更好的类型支持

### 你期望的 API 是什么样子的？

增加ts配置

**Comment by chenjiahan** [comment]
目前就支持的

https://github.com/youzan/vant/blob/dev/packages/vant-cli/docs/directory.md#%E7%94%9F%E6%88%90%E7%B1%BB%E5%9E%8B%E5%A3%B0%E6%98%8E
