### ISSUE TITLE
vant组件按需引入时的全局引入和在组件中局部引入有什么区别，性能上哪个会好一点？

### ISSUE THREAD

**Issue by dj835638078** [youzan/vant#10290]
### 重现链接

https://testonline-us.vesync.com/

### Vant 版本

2.12.22

### 描述一下你遇到的问题。

一般情况下按需使用是这样的：
  import Vue from 'vue'
import { Button } } from 'vant'
Vue.use(Button)
组件中这样单独引入：
import { IndexAnchor } from 'vant'
components: {
    'van-index-anchor': IndexAnchor
  }
想问一下两种引入方式性能方面的优缺点，以及建议的使用方式

### 重现步骤

想要咨询一下这两种不同的引入方式，对性能的影响，链接可忽略不记

**Comment by chenjiahan** [comment]
优缺点在 Vue 官方文档中有说明，可以参考：https://vuejs.org/guide/components/registration.html#local-registration
