### ISSUE TITLE
[Bug Report] 国际化部分代码写错了 导致私有化自己部署的vant 中文readme不能出来

### ISSUE THREAD

**Issue by fangkyi03** [youzan/vant#10296]
### 重现链接

https://github.com/youzan/vant

### Vant Cli 版本

3.4.5

### 描述一下你遇到的问题。

国际化报错

### 重现步骤

<img width="842" alt="image" src="https://user-images.githubusercontent.com/30390014/153808769-114d6640-3c5b-44d8-9952-c10b10def3b7.png">
defaultLang 这个值设置错误 会导致一直使用英文文档 不能使用中文的

**Comment by chenjiahan** [comment]
没懂你的意思，你设置的 defaultLang 是什么值

**Comment by fangkyi03** [comment]
我没有做多余操作 就是启动时候选择一下中文 然后就出现开发指南中设计资源上面的都是中文 下面的所有进去都是英文的情况 我后来自己代码追踪一下 发现是这里导致的 我这个时候的defaultLang 跟我的lang是相同的 然后就直接读取了默认的英文内容 没有按照语言读取想要的

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/153821314-f5cd5dde-a78f-412e-b6e2-57c16cd8086e.png)
这边语言切换可以正常使用 切换英文就是英文 切换中文就是中文 但是下面以后的都不会随着切换而改变 不过我现在改了你的代码 重新编译一次 已经可以了

**Comment by fangkyi03** [comment]
https://user-images.githubusercontent.com/30390014/153822300-0a0afefc-a06a-4cdb-9c76-42e589f95892.mp4

这是我没改之前的样子 不管这么设置 下面的都是英文 不会随着语言切换变化

**Comment by chenjiahan** [comment]
这个问题没复现哈，已经解决了我就 close 咯

**Comment by fangkyi03** [comment]
我只是觉得那个代码有问题 直接取语言不就好了 为啥还要跟默认语言配置去比较一次呢 谁说默认的就一定是英文的呢？

**Comment by chenjiahan** [comment]
defaultLang 是项目里配置的，不是写死的
