### ISSUE TITLE
[Bug Report] van-tab在使用v-if延迟渲染更新问题

### ISSUE THREAD

**Issue by zhq195** [youzan/vant#10292]
### 重现链接

https://jsrun.net/AB9Kp

### Vant 版本

3.3.7

### 描述一下你遇到的问题。

两个相邻的van-tab组件第一个使用v-if来判断是否显示，初始值为false在mounted之后再设置为true，第二个van-tab使用了title插槽。
结果：第一个的title显示成了第二个title的内容

### 重现步骤

1、mounted之后显示第一个van-tab组件

### 设备/浏览器

与浏览器无关

**Comment by nemo-shen** [comment]
看起来的确有问题，CDN使用场景，vant2没有问题，vant3必现
