### ISSUE TITLE
滑动单元格组件  阻止滑动事件冒泡无效？

### ISSUE THREAD

**Issue by Abyss-QAQ** [youzan/vant#10304]
<div
            v-for="(i, k) in customers"
            :key="k"
            @click="openDetail(i.userUuid)"
          >
            <van-swipe-cell stop-propagation>
              <van-cell :title="i.userName">
                <template #label> {{ i.customerRemark }} </template>
              </van-cell>
              <template #right>
                <van-button square type="danger" text="删除" />
              </template>
            </van-swipe-cell>
          </div>

滑动事件会正常触发  移动端操作效果正常  但是在pc端鼠标控制滑动后会触发外层的 click 事件

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接

**Comment by Abyss-QAQ** [comment]
> 
https://2tp27v.csb.app/
