### ISSUE TITLE
[Bug Report] Toast的type切换时渲染内容错误

### ISSUE THREAD

**Issue by FeiFanLiang** [youzan/vant#10302]
### 重现链接

描述

### Vant 版本

3.4.1

### 描述一下你遇到的问题。

页面同时存在多个Toast调用时，在使用`type:html`后其他类型的Toast提示内容均无法显示，只能显示空白内容

### 重现步骤

`Toast({type:'html',message:'<b>1</b>'})`
`Toast({type:"fail",message:"1"})`

**Comment by Ali-Libra** [comment]
你好 我也出现了这个问题 我的样式是通过vite自动导入的

**Comment by FeiFanLiang** [comment]
> ### 重现链接
> 描述
> 
> ### Vant 版本
> 3.4.1
> 
> ### 描述一下你遇到的问题。
> 页面同时存在多个Toast调用时，在使用`type:html`后其他类型的Toast提示内容均无法显示，只能显示空白内容
> 
> ### 重现步骤
> `Toast({type:'html',message:'<b>1</b>'})` `Toast({type:"fail",message:"1"})`
> 
> ### 设备/浏览器
> _No response_

![image](https://user-images.githubusercontent.com/30872365/154196318-174ecdae-6eb2-4e69-8588-46fbfb908ec2.png)

本地调试了一下，发现Toast组件内的renderMessage函数在Toast重新调用时重新执行了，但是实际渲染出的dom元素没有渲染出`type:text`中的message，猜测原因可能是vnode的复用导致没有正常进行更新，如上图分别使用key值后，此时进行不同类型的调用，行为正常

**Comment by Ali-Libra** [comment]
> > ### 重新链接
> > 描述
> > ### Vant 版本
> > 3.4.1
> > ### 描述一下你遇到的问题。
> > 页面同时存在多个 Toast 调用时，在使用`type:html`后显示其他内容类型的 Toast 提示内容均无法显示，只能空白处
> > ### 返回步骤
> > `Toast({type:'html',message:'<b>1</b>'})` `Toast({type:"fail",message:"1"})`
> > ### 设备/浏览器
> > _没有反应_
> 
> ![图片](https://user-images.githubusercontent.com/30872365/154196318-174ecdae-6eb2-4e69-8588-46fbfb908ec2.png)
> 
> 调试了一下，Toast 组件内的renderMessage 函数在Toast 重新调用时重新执行，但是实际上渲染出的dom 没有渲染出`type:text`的消息，估计原因可能是vnode 的复用导致没有正常进行图分别使用关键值后，此时进行不同类型的调用，行为正常

你这个问题应该是类名重复 导致你提示框的背景颜色为白色 
我的解决方案是 给这个提示框给定一个自定义类名 然后在全局样式中把这个类名的背景颜色设置成黑色 这样提示框出来就不会是白屏的了

**Comment by 1365436742** [comment]
> ### 重现链接
> 描述
> 
> ### Vant 版本
> 3.4.1
> 
> ### 描述一下你遇到的问题。
> 页面同时存在多个Toast调用时，在使用`type:html`后其他类型的Toast提示内容均无法显示，只能显示空白内容
> 
> ### 重现步骤
> `Toast({type:'html',message:'<b>1</b>'})` `Toast({type:"fail",message:"1"})`
> 
> ### 设备/浏览器
> _No response_
![112](https://user-images.githubusercontent.com/51362520/154445782-8d640237-1b0f-4451-87c3-9af01f33c6ab.gif)
在这里是了这个例子未发现呀

**Comment by 1365436742** [comment]
>`const showMultipleToast = () => {
  Toast.allowMultiple();
  Toast({
    type: 'html',
    message: '<b>1</b>',
    position: 'top',
  });
  Toast({
    type: 'fail',
    message: t('text3'),
    position: 'bottom',
  });
};`
这里的写法是这样的

**Comment by 1365436742** [comment]
`const showMultipleToast = () => {
  Toast.allowMultiple();
  Toast({
    type: 'html',
    message: '<b>1</b>',
    position: 'top',
  });
  Toast({
    type: 'fail',
    message: t('text3'),
    position: 'bottom',
  });
};
`
这里的写法是这样的

**Comment by Ali-Libra** [comment]
> 



> > `const showMultipleToast = () => {   Toast.allowMultiple();   Toast({     type: 'html',     message: '<b>1</b>',     position: 'top',   });   Toast({     type: 'fail',     message: t('text3'),     position: 'bottom',   }); };`
> > 这里的写法是这样的



> > ### 重现链接
> > 描述
> > ### Vant 版本
> > 3.4.1
> > ### 描述一下你遇到的问题。
> > 页面同时存在多个Toast调用时，在使用`type:html`后其他类型的Toast提示内容均无法显示，只能显示空白内容
> > ### 重现步骤
> > `Toast({type:'html',message:'<b>1</b>'})` `Toast({type:"fail",message:"1"})`
> > ### 设备/浏览器
> > _No response_
> > ![112](https://user-images.githubusercontent.com/51362520/154445782-8d640237-1b0f-4451-87c3-9af01f33c6ab.gif)
> > 在这里是了这个例子未发现呀

我是这样使用出现的问题 A->B页面 然后B页面在返回A的同时 进行Toast提示 就会出现这个问题

**Comment by 1365436742** [comment]
> > 
> 
> > > `const showMultipleToast = () => {   Toast.allowMultiple();   Toast({     type: 'html',     message: '<b>1</b>',     position: 'top',   });   Toast({     type: 'fail',     message: t('text3'),     position: 'bottom',   }); };`
> > > 这里的写法是这样的
> 
> > > ### 重现链接
> > > 描述
> > > ### Vant 版本
> > > 3.4.1
> > > ### 描述一下你遇到的问题。
> > > 页面同时存在多个Toast调用时，在使用`type:html`后其他类型的Toast提示内容均无法显示，只能显示空白内容
> > > ### 重现步骤
> > > `Toast({type:'html',message:'<b>1</b>'})` `Toast({type:"fail",message:"1"})`
> > > ### 设备/浏览器
> > > _No response_
> > > ![112](https://user-images.githubusercontent.com/51362520/154445782-8d640237-1b0f-4451-87c3-9af01f33c6ab.gif)
> > > 在这里是了这个例子未发现呀
> 
> 我是这样使用出现的问题 A->B页面 然后B页面在返回A的同时 进行Toast提示 就会出现这个问题

你这里可能是生命周期运用的问题，可以贴出你的代码

**Comment by Ali-Libra** [comment]
> 

就很简单的一个点击事件 然后 toast提示 然后router.go(-2) 
![image](https://user-images.githubusercontent.com/67216143/154447463-88d91e8f-7bd7-4f3d-a865-625fbd484b92.png)

**Comment by FeiFanLiang** [comment]
> > > 
> > 
> > 
> > > > `const showMultipleToast = () => {   Toast.allowMultiple();   Toast({     type: 'html',     message: '<b>1</b>',     position: 'top',   });   Toast({     type: 'fail',     message: t('text3'),     position: 'bottom',   }); };`
> > > > 这里的写法是这样的
> > 
> > 
> > > > ### 重现链接
> > > > 描述
> > > > ### Vant 版本
> > > > 3.4.1
> > > > ### 描述一下你遇到的问题。
> > > > 页面同时存在多个Toast调用时，在使用`type:html`后其他类型的Toast提示内容均无法显示，只能显示空白内容
> > > > ### 重现步骤
> > > > `Toast({type:'html',message:'<b>1</b>'})` `Toast({type:"fail",message:"1"})`
> > > > ### 设备/浏览器
> > > > _No response_
> > > > ![112](https://user-images.githubusercontent.com/51362520/154445782-8d640237-1b0f-4451-87c3-9af01f33c6ab.gif)
> > > > 在这里是了这个例子未发现呀
> > 
> > 
> > 我是这样使用出现的问题 A->B页面 然后B页面在返回A的同时 进行Toast提示 就会出现这个问题
> 
> 你这里可能是生命周期运用的问题，可以贴出你的代码

[https://codesandbox.io/s/angry-mcclintock-duydys?file=/src/App.vue](url)Toast调用时使用不同type造成的渲染异常，另外一个Toast和Dialog引起的样式问题，需要在生产模式进行按需加载的情况才会出现

**Comment by FeiFanLiang** [comment]
> > > ### 重新链接
> > > 描述
> > > ### Vant 版本
> > > 3.4.1
> > > ### 描述一下你遇到的问题。
> > > 页面同时存在多个 Toast 调用时，在使用`type:html`后显示其他内容类型的 Toast 提示内容均无法显示，只能空白处
> > > ### 返回步骤
> > > `Toast({type:'html',message:'<b>1</b>'})` `Toast({type:"fail",message:"1"})`
> > > ### 设备/浏览器
> > > _没有反应_
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/30872365/154196318-174ecdae-6eb2-4e69-8588-46fbfb908ec2.png)
> > 调试了一下，Toast 组件内的renderMessage 函数在Toast 重新调用时重新执行，但是实际上渲染出的dom 没有渲染出`type:text`的消息，估计原因可能是vnode 的复用导致没有正常进行图分别使用关键值后，此时进行不同类型的调用，行为正常
> 
> 你这个问题应该是类名重复 导致你提示框的背景颜色为白色 我的解决方案是 给这个提示框给定一个自定义类名 然后在全局样式中把这个类名的背景颜色设置成黑色 这样提示框出来就不会是白屏的了

这个issue讨论的不是这个bug，那个在另外一个

**Comment by FeiFanLiang** [comment]
> > ### 重现链接
> > 描述
> > ### Vant 版本
> > 3.4.1
> > ### 描述一下你遇到的问题。
> > 页面同时存在多个Toast调用时，在使用`type:html`后其他类型的Toast提示内容均无法显示，只能显示空白内容
> > ### 重现步骤
> > `Toast({type:'html',message:'<b>1</b>'})` `Toast({type:"fail",message:"1"})`
> > ### 设备/浏览器
> > _No response_
> > ![112](https://user-images.githubusercontent.com/51362520/154445782-8d640237-1b0f-4451-87c3-9af01f33c6ab.gif)
> > 在这里是了这个例子未发现呀

[复现链接](https://codesandbox.io/s/angry-mcclintock-duydys?file=/src/App.vue)
