### ISSUE TITLE
不兼容火狐浏览器手机版。

### ISSUE THREAD

**Issue by 332lfgb6** [youzan/vant#10316]
### 重现链接

https://github.com/332lfgb6/firefox-bug

### Vant 版本

2.12.44

### 描述一下你遇到的问题。

上划手机屏幕会隐藏firefox手机版的地址栏，此时，底部的`van-tabbar`会消失，并且会出现不明的黑色区域。
有地址栏时：
![图片](https://user-images.githubusercontent.com/51245335/155286183-f1d15a8e-b354-4274-9e5d-75f4e2f02af7.png)
无地址栏时：
![图片](https://user-images.githubusercontent.com/51245335/155286207-f2f359b3-dc6a-454d-a49a-d6217ad5580e.png)

### 重现步骤

1. `yarn serve`
2. 用火狐手机浏览器打开。

### 设备/浏览器

三星a6s/火狐浏览器

**Comment by chenjiahan** [comment]
Tabbar 本身只是用了 CSS 的 fixed 布局，如果浏览器上无法正常展示，属于浏览器自身的 bug，我们不计划进行特殊兼容。
