### ISSUE TITLE
时间选择器添加12小时制功能

### ISSUE THREAD

**Issue by coderwyd** [youzan/vant#10324]
### 这个功能解决了什么问题？

可以直接进行选择12和24小时制，12小时制包括am/pm

### 你期望的 API 是什么样子的？

```html
  <van-datetime-picker use12-hours />
```

**Comment by chenjiahan** [comment]
如果是 12 小时制的话，还需要增加一类对 AM/PM 进行选择吗？

**Comment by coderwyd** [comment]
有必要，不然不知道所选择的是上午12点还是下午12点




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月24日(星期四) 中午1:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant] 时间选择器添加12小时制功能 (Issue #10324)





 
如果是 12 小时制的话，还需要增加一列对 AM/PM 进行选择吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenjiahan** [comment]
我们暂时没有计划支持这个交互喔，建议通过 Picker 组件自行封装
