### ISSUE TITLE
button 禁用时移动端未禁用

### ISSUE THREAD

**Issue by susu1205065402** [youzan/vant#10326]
### 重现链接

https://codesandbox.io/s/m5v3f?file=/src/App.vue

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

button 禁用时移动端未禁用  loading 也未禁用

### 重现步骤

<van-button disabled loading  loading-text="加载中..."  type="primary">禁用状态</van-button>

**Comment by susu1205065402** [comment]
添加禁用disabled、loading属性，按钮还可点击

**Comment by xinconan** [comment]
重现链接不对吧？

**Comment by nemo-shen** [comment]
1. 重现链接不对
2. 分别测试demo中的loading和disabled均没有遇到还能点击的问题

**Comment by susu1205065402** [comment]
是在移动端测试的吗




在 2022-02-24 22:45:18，"nemo-shen" ***@***.***> 写道：

重现链接不对
分别测试demo中的loading和disabled均没有遇到还能点击的问题

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
