### ISSUE TITLE
NoticeBar 文字过多会造成抖动，卡顿问题

### ISSUE THREAD

**Issue by Cifferni** [youzan/vant#10325]
### 重现链接

https://github.com/youzan/vant

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

我在使用NoticeBar 组件时候 文字过多会造成抖动，卡顿问题

### 重现步骤

使用后通知文字多一点就能复现了

### 设备/浏览器

移动端

**Comment by susu1205065402** [comment]
也遇到了

**Comment by nemo-shen** [comment]
@Cifferni 是什么设备

**Comment by Cifferni** [comment]
我们公司是混合式开发，在安卓壳子上发现这个问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月3日(星期四) 晚上11:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant] NoticeBar 文字过多会造成抖动，卡顿问题 (Issue #10325)






@齐弗尼是什么设备

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
你收到这个，因为你被提到了。留言 ID ***@***.***与&gt;

**Comment by chenjiahan** [comment]
如果是 App WebView 内有问题，普通浏览器没问题，建议从 App 侧寻找解决方案哈。
