### ISSUE TITLE
轮播图开始第一张轮播，后面的图一起轮播了

### ISSUE THREAD

**Issue by onloner2012** [youzan/vant#10333]
### 重现链接

http://localhost:8080/

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

最基础的轮播图，开始是1轮播，后面就是3，4，5一起划过去了

### 重现步骤

轮播无法展示

**Comment by chenjiahan** [comment]
重新连接无效，请提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
