### ISSUE TITLE
[Bug Report] Vant3 Dialog默认显示 Uploader 图片删不掉

### ISSUE THREAD

**Issue by Swarz** [youzan/vant#10331]
### 重现链接

https://codesandbox.io/s/gracious-dew-uh7w17?file=/src/App.vue

如遇页面出错，请多次刷新

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

1. Dialog默认显示 （只能在main.js 引入 没这个问题）
2. 本次反馈重点 Uploader 图片删不掉，无法继续使用

### 重现步骤

Dialog默认显示点击确认

使用第一个Uploader
1. 上传图片
2. 删除图片
3. 文本框输入文字  ----图片预览重新显示
（点击打印list。显示已删除）

使用第二个Uploader
1. 上传图片
2. 删除图片  ----图片预览依然显示
（点击打印list。显示已删除）
3. 文本框输入文字  ----图片预览消失

### 设备/浏览器

都可以

**Comment by nemo-shen** [comment]
你使用有问题
uploader上既然已经用了 `v-model` 了，为什么 `afterRead` 的时候还要重复 `push` 一次文件？
可以设想一下
- upload file ===> fileList = [file]
- emit afterRead
- afterRead push file ====> fileList = [file, file]
- emit beforeDelete
- beforeDelete split fileList ====> fileList = [file]

[这是我已经给你修复过的代码，**只修复了第一个uploader以便你做对比**](https://codesandbox.io/embed/amazing-zhukovsky-3wuc9d)

**Comment by LOADINGG** [comment]
> 你使用有问题 uploader上既然已经用了 `v-model` 了，为什么 `afterRead` 的时候还要重复 `push` 一次文件？ 可以设想一下
> 
> * upload file ==============> fileList = [file]
> * emit afterRead
> * afterRead push file ========> fileList = [file, file]
> * emit beforeDelete
> * beforeDelete split fileList ====> fileList = [file]
> 
> [这是我已经给你修复过的代码，**只修复了第一个uploader以便你做对比**](https://codesandbox.io/embed/amazing-zhukovsky-3wuc9d)

afterRead的file是个文件对象，真正上传服务器后的图片地址才是要存到数据库的，这个afterRead后的file对象传给后端没有用。
遇到同样问题，fileList  push上传成功后服务端返回的图片地址后显示两份一样图片。
