### ISSUE TITLE
[Feature Request] Vant 3的sku 组件 期待

### ISSUE THREAD

**Issue by westchinago** [youzan/vant#10336]
### 这个功能解决了什么问题？

vue 2的时候 我们就选择了vant sku组件 
后来vue升级到3  找遍了vant 都没有找到sku

这么好的功能 居然没有了  
我们的业务都无法进展了 

官方仍然会推出sku 吗?

### 你期望的 API 是什么样子的？

vant sku 3

**Comment by chenjiahan** [comment]
暂时没有计划在 Vue 3 版本中提供 Sku 组件哈，这个组件的业务属性太重了，你可以基于 Vue 2 版本的源码进行迁移：https://github.com/youzan/vant/tree/2.x/src/sku

**Comment by lixiaofa** [comment]
> 暂时没有计划在 Vue 3 版本中提供 Sku 组件哈，这个组件的业务属性太重了，你可以基于 Vue 2 版本的源码进行迁移：https://github.com/youzan/vant/tree/2.x/src/sku

迁移是什么意思 ，意思是我根据vant2 自己改吗

**Comment by chenjiahan** [comment]
> 根据vant2 自己改吗

对的

**Comment by lixiaofa** [comment]
> > 根据vant2 自己改吗
> 
> 对的

能给点思路吗， 从来没干过 ，很有意愿...
谢谢 ，大佬

**Comment by chenjiahan** [comment]
把这个目录下的源代码拷贝出来（以及一些相关的 utils），按照你的需要改造就可以咯

源代码：https://github.com/youzan/vant/tree/2.x/src/sku

**Comment by lixiaofa** [comment]
> 把这个目录下的源代码拷贝出来（以及一些相关的 utils），按照你的需要改造就可以咯
> 
> 源代码：https://github.com/youzan/vant/tree/2.x/src/sku

但是 ， 它api 是 option api  , 这样的话 ， 是不是要重构？
我比较倾向composition api

**Comment by chenjiahan** [comment]
option api 在 Vue 3 里还能用的

**Comment by lixiaofa** [comment]
> option api 在 Vue 3 里还能用的
我比较倾向composition api ,  我们后面要不断迭代的 ， sku 是个长期的业务组件。
大佬，你觉得怎样比较合适

**Comment by lixiaofa** [comment]
> option api 在 Vue 3 里还能用的

我比较倾向composition api , 我们后面要不断迭代的 ， sku 是个长期的业务组件。
大佬，你觉得怎样比较合适

**Comment by chenjiahan** [comment]
可以的呀，肯定是 composition api 更好

**Comment by lixiaofa** [comment]
> 可以的呀，肯定是 composition api 更好

但是我感觉难度有点大， 有相关的 建议吗？

**Comment by lixiaofa** [comment]
> 可以的呀，肯定是 composition api 更好

在sku 迁移的过程中 ， 遇到这样的问题
![image](https://user-images.githubusercontent.com/23230215/210967336-5bdacb6e-34a6-4c2e-8733-4c559ae01018.png)
能帮我看一下吗， 谢谢
@chenjiahan 
项目地址： https://github.com/lixiaofa/vant-sku-next

**Comment by chenjiahan** [comment]
暂时没时间看哈，建议自行排查下

**Comment by lixiaofa** [comment]
> ### 这个功能解决了什么问题？
> vue 2的时候 我们就选择了vant sku组件 后来vue升级到3 找遍了vant 都没有找到sku
> 
> 这么好的功能 居然没有了 我们的业务都无法进展了
> 
> 官方仍然会推出sku 吗?
> 
> ### 你期望的 API 是什么样子的？
> vant sku 3

@westchinago  我迁移了vant2.x 的sku 

https://www.npmjs.com/package/vant-sku?activeTab=readme
