### ISSUE TITLE
[Feature Request] 如何自定义异步加载图片?

### ISSUE THREAD

**Issue by JustTestCode** [youzan/vant#10335]
### 这个功能解决了什么问题？

需要自定义异步加载图片,van-img :src能否接受一个异步方法?

### 你期望的 API 是什么样子的？

现在我只能使用伪方法,先设置 :src为一个空白图片的base64,再通过指令修改img的src,感觉不是很好

例子:[https://codesandbox.io/s/exyi7?file=/src/App.vue](https://codesandbox.io/s/exyi7?file=/src/App.vue)

有没有更好的解决方案?如果src可以接受一个promise 就太好了

**Comment by chenjiahan** [comment]
组件层面暂时不计划支持异步 src，这种场景用动态设置 src 就足够了
