### ISSUE TITLE
tabbar组件路由模式to='/'时切换不正常

### ISSUE THREAD

**Issue by yutons** [youzan/vant#10330]
vant版本：3.4.5
代码配置如下：
![6862D74D-E6E8-4d4c-8E9B-A1FF837872D1](https://user-images.githubusercontent.com/25010191/155693132-d4c43402-fa99-46af-96b3-69516d518679.png)
默认打开页面
![0844258F-B4A0-4222-9122-C0ED76582D0A](https://user-images.githubusercontent.com/25010191/155693164-a2691291-11ff-4fc9-8227-80a3ad63e647.png)
切换以后的效果，首页和我的页面都被选中
![0398A63F-4C52-4a98-9A3B-DE0994E4F358](https://user-images.githubusercontent.com/25010191/155693167-98621a5b-0d98-4a63-8c91-ffffa9ad12ba.png)

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接。

https://codesandbox.io/s/m5v3f

**Comment by yutons** [comment]
demo地址：https://github.com/yutons/vant3-h5-demo
演示地址：https://static-4ca3919d-85d6-4792-8507-3b7267c385b5.bspapp.com/
演示动画：
![GIF 2022-2-28 11-09-54](https://user-images.githubusercontent.com/25010191/155917767-fd8d7967-b970-41b4-a1fa-202c0c3d9a30.gif)
