### ISSUE TITLE
[Feature Request] vue-cli 5 初始化的 vue3 的 typescript 项目，按需载入样式的文档

### ISSUE THREAD

**Issue by tevooli** [youzan/vant#10345]
### 这个功能解决了什么问题？

新的 vue-cli 5 初始化的 vue3+typescript 项目中，需要按需载入 vant 的样式，按照原有的配置，已无法载入样式：
```
  chainWebpack: config => {
    config.module
      .rule('ts')
      .use('ts-loader')
      .tap(options => {
        options = merge(options, {
          transpileOnly: true,
          getCustomTransformers: () => ({
            before: [
              tsImportPluginFactory({
                libraryName: 'vant',
                libraryDirectory: 'es',
                style: true
              })
            ]
          }),
          compilerOptions: {
            module: 'es2015'
          }
        });
        return options;
      });
  }
```

### 你期望的 API 是什么样子的？

期望给出 vue-cli 5 初始化的 typescript 项目，整合 vant 时，如何配置按需载入样式的配置文档。

**Comment by sneptune-love** [comment]
> 

使用这个配置，dev模式下没有问题。但是打包production环境时，会出现vant样式丢失。

**Comment by tcstory** [comment]
> nodejs 版本回退下试试，我记得之前踩到过这个坑。

回退版本只是一个临时方案而已, 目前我已经锁死版本在 3.4.x 了, 我的 node 版本是 node 16.x

**Comment by yao8384** [comment]
在 vue-cli 5 中使用 ts 和  vant 3.5.2 不再需要 ts-import-plugin 了；
按官网使用推荐的插件 项目 直接 使用 ' <van-button></van-button> ' 这种形式的用法就可以了
不再需要 import {Button} from ‘vant' 了
