### ISSUE TITLE
🚀 Vant 4.0 alpha 版本发布，支持深色模式

### ISSUE THREAD

**Issue by chenjiahan** [youzan/vant#10341]
Vant 4.0 alpha 版本已发布，欢迎体验~

## 安装

通过以下方式安装 Vant 4.0 alpha 版本：

```bash
npm i vant@4.0.0-alpha.0
```

## 文档

Vant 4.0 文档已部署上线，访问地址：https://vant-contrib.gitee.io/vant/v4/

## 深色模式

将 ConfigProvider 组件的 `theme` 属性设置为 `dark`，可以开启深色模式。

深色模式会全局生效，使页面上的所有 Vant 组件变为深色风格。

```html
<van-config-provider theme="dark">...</van-config-provider>
```

同时，Vant 文档也支持切换到深色模式：

![](https://user-images.githubusercontent.com/7237365/155883938-102dcf45-43b9-44cb-9d6a-aefb8eb236cc.png)

### Picker 组件重构

在之前的版本中，Picker 组件的 API 设计存在一些不合理的设计，比如：

- columns 数据格式定义不合理，容易产生误解
- 数据流不清晰，暴露了过多的实例方法来对数据进行操作

为了解决上述问题，我们在 v4 版本中对 Picker 组件进行了重构。

#### 主要变更

- 支持通过 `v-model` 绑定当前选中的值，移除 `default-index` 属性
- 重新定义了 `columns` 属性的结构
- 移除了操作内部数据的实例方法，仅保留 `confirm` 方法
- 新增 `getSelectedOptions` 实例方法
- 调整了 `confirm`、`cancel`、`change` 事件的参数
- 重命名 `item-height` 属性为 `option-height`
- 重命名 `visible-item-count` 属性为 `visible-option-num`

详细用法请参见 [Picker 组件文档](#/zh-CN/picker)。

### DatetimePicker 组件重构

DatetimePicker 组件被拆分为：

- TimePicker: 用于时间选择。
- DatePicker: 用于日期选择。

同时，这两个组件也基于新版 Picker 组件进行重构，并优化了部分 API 设计。

> 在后续的测试版本中，会提供基于这两个组件提供一个新的 DatetimePicker 组件。

#### 主要变更

- `v-model` 绑定的值调整为数组格式
- 新增 `columns-type` 属性，用于控制选项类型和顺序
- 移除 `type` 属性和 `columns-order` 属性
- 移除 `getPicker` 方法
- 调整 `confirm`、`cancel`、`change` 事件的参数，与 Picker 组件保持一致

### Area 组件重构

Area 组件是基于 Picker 组件进行封装的，因此本次升级也对 Area 组件进行了内部逻辑的重构，并优化了部分 API 设计。

#### 主要变更

- 支持通过 `v-model` 绑定当前选中的值
- 移除 `reset` 方法，现在可以通过修改 `v-model` 来进行重置
- 移除 `is-oversea-code` 属性
- 调整 `confirm`、`cancel`、`change` 事件的参数，与 Picker 组件保持一致
- 重命名 `value` 属性为 `modelValue`
- 重命名 `item-height` 属性为 `option-height`
- 重命名 `visible-item-count` 属性为 `visible-option-num`

详细用法请参见 [Area 组件文档](#/zh-CN/area)。

### 事件命名调整

从 Vant 4 开始，所有的事件均采用 Vue 官方推荐的**驼峰格式**进行命名。

```js
// Vant 3
emit('click-input');

// Vant 4
emit('clickInput');
```

这项改动**不影响原有的模板代码**，Vue 会自动在模板中对事件名进行格式转换：

```html
<!-- 以下代码可以照常运行，无须做任何更改 -->
<van-field @click-input="onClick" />
```

如果你在 JSX 中使用 Vant 组件，需要将监听的事件名调整为驼峰格式，新的监听方式更加符合 JSX 本身的规范：

```jsx
// Vant 3
<Field onClick-input={onClick} />

// Vant 4
<Field onClickInput={onClick} />
```

### 其他 API 调整

在 Vant 4.0 版本中，以下 API 进行了不兼容更新：

#### Tabs

- 移除了 `click` 和 `disabled` 事件，请使用 `click-tab` 事件代替

#### AddressEdit

- `change-area` 事件的参数调整为 `PickerOption[]` 类型
- 移除未在文档中标注的 `getArea` 实例方法

### 移除 Less 变量

目前 Vant 已经支持了基于 CSS 变量的主题定制能力，因此后续将不再提供基于 Less 的主题定制方式。

如果你的项目正在使用旧版的 Less 主题定制，请使用 [ConfigProvider 全局配置](#/zh-CN/config-provider) 组件进行替换。

### 简化 CSS 变量名

考虑到 **代码体积** 和 **使用便捷性**，我们对部分 CSS 变量的名称进行了简化，在变量名中使用更简短的单词，涉及以下变更：

```less
animation-duration               ->  duration
animation-timing-function-enter  ->  ease-out
animation-timing-function-leave  ->  ease-in
background-color                 ->  background
background-color-light           ->  background-2
border-radius                    ->  radius
border-width-base                ->  border-width
box-shadow                       ->  shadow
font-family                      ->  font
font-weight-bold                 ->  font-bold
price-integer-font               ->  price-font
text-link                        ->  link
transition-duration              ->  duration
```

由于涉及的 CSS 变量较多，建议在代码仓库中进行全局匹配和替换。

### 统一主色调

在之前的版本中，Vant 组件有两种色彩风格，一部分采用红色作为主色调，另一部分采用蓝色。为了保持色彩规范的统一，我们在 Vant 4 中对组件的主色调进行了统一，所有组件均采用蓝色作为主色调。

以下组件的默认色值风格由红色调整为蓝色：

- AddressEdit
- AddressList
- Card
- Calendar
- Cascader
- ContactList
- ContactEdit
- CouponList
- Dialog
- DropdownMenu
- IndexBar
- Sidebar
- Steps
- Tabs
- TreeSelect

### 其他样式改动

- `--van-font-bold` 的默认值由 `500` 调整为 `600`
- ActionBar: 调整 `--van-action-bar-icon-text-color` 变量的默认值为 `--van-text-color`
- AddressList: 重命名 `--van-address-list-item-radio-icon-color` 为 `--van-address-list-radio-color`
- Button: 默认圆角大小从 `2px` 调整为 `4px`
- Button: 默认按钮的边框颜色调整为 `--van-gray-4`
- Button: 调整 `font-smoothing`，默认使用粗体文字
- Cell: 只设置 `value` 时，内容不再会靠左对齐
- Card: 调整 `--van-card-background` 变量的默认值为 `--van-background`
- Card: 调整 `--van-card-price-color` 变量的默认值为 `--van-text-color`
- Card: 调整 `--van-card-desc-color` 变量的默认值为 `--van-text-color-2`
- ContactList: 重命名 `--van-contact-list-item-radio-icon-color` 为 `--van-contact-list-radio-color`
- CouponList: 重命名 `--van-coupon-corner-checkbox-icon-color` 为 `--van-coupon-checkbox-color`
- Field: 调整 `--van-field-label-color` 变量的默认值为 `--van-text-color`
- Switch: 移除 `--van-switch-border` 变量
- Switch: 调整 `--van-switch-size` 变量的默认值为 `26px`
- Switch: 调整 `--van-switch-background` 变量的默认值为 `rgba(120, 120, 128, 0.16)`
- Tabbar: 调整 `--van-tabbar-item-text-color` 变量的默认值为 `--van-text-color`
- GridItem: 调整 `--van-grid-item-text-color` 变量的默认值为 `--van-text-color`

**Comment by sunkint** [comment]
🎉

**Comment by cklwblove** [comment]
👍 💯

**Comment by ghostcode** [comment]
文档链接把句号也放里面了，改下。

**Comment by chenjiahan** [comment]
@ghostcode 已修改

**Comment by julytian** [comment]
👍 💯

**Comment by l-zoy** [comment]
🎉

**Comment by wltj920** [comment]
太棒了，支持

**Comment by cff-github** [comment]
能不能提供一个select选择框组件

**Comment by chenjiahan** [comment]
@cff-github 移动端应该用 Picker

**Comment by Likunone** [comment]
👍👍👍

**Comment by along-web** [comment]
到时候直接往3.0叠加还是直接就4.0了

**Comment by chenjiahan** [comment]
> 到时候直接往3.0叠加还是直接就4.0了

有不兼容更新，因此是单独的 4.0 版本，不会放到 3.x 上

**Comment by daowojia** [comment]
如何便捷的覆盖body 里的全局变量 ?  同样的js覆盖方法,在element和miut 都有效, 在van 4.0 无效,  除非自定义key, 那还有什么意义,请问想通过全局css变量 切换主题, 目前有好的办法吗,  我覆盖的var 又总是被vant 官方覆盖, 很恼火

**Comment by chenjiahan** [comment]
没懂你说的被 vant 官方覆盖是什么意思，可以给个 codesandbox 链接看下

**Comment by Airkro** [comment]
后续新功能只会添加到V4吗

**Comment by chenjiahan** [comment]
是的，等 v4 正式版发布后，会主要迭代 v4 版本

**Comment by shijunti19** [comment]
v4的主要目的是不是就是为了模仿ant

**Comment by baboon-king** [comment]
🥳

**Comment by baixiaoyu2997** [comment]
你好，建议在`Discussions` 开个`roadmap`,可以写一下相关的`TODO`或者`issue`, 不知道要等多久啊

**Comment by chenjiahan** [comment]
目前没有确定 Roadmap 喔，我们会基于社区的反馈来确定最终发布正式版的时间。

当前版本虽然是 alpha，但功能都是比较稳定的，可以放心使用，在版本升级时注意是否有 breaking change 就好。

**Comment by buyouzzj** [comment]
v4里面要使用date-time-picker，怎么使用，还是说要等到新的date-time-picker组件出来才能使用

**Comment by chenjiahan** [comment]
> v4里面要使用date-time-picker，怎么使用，还是说要等到新的date-time-picker组件出来才能使用

可以再等等，后续会加上

**Comment by hqwlkj** [comment]
v4 目前和 nuxt3 存在build之后有错，

#10589

**Comment by loca-spirit** [comment]
datetimepicker能尽快嘛，，，等不及了。。。。

**Comment by juzijun2020** [comment]
请问SKU组件会在新版本里面出现么？

**Comment by leosin** [comment]
> 
最近用了一下nuxt3发现几乎没有能支持的ui framework，所以应该不是vant的个例，并且vant也是主打移动端的，压根儿就是往seo那个方向走的。看来只能自己造轮子了。

**Comment by baixiaoyu2997** [comment]
> > 
> 
> 最近用了一下nuxt3发现几乎没有能支持的ui framework，所以应该不是vant的个例，并且vant也是主打移动端的，压根儿就是往seo那个方向走的。看来只能自己造轮子了。

element-plus可以用

**Comment by leosin** [comment]
> element-plus可以用

是的，我刚刚也发现了。他们用的这个方法，不知道在vant能否借鉴

```ts
const lifecycle = process.env.npm_lifecycle_event

export default defineNuxtConfig({
  build: {
    transpile:
      lifecycle === 'build' || lifecycle === 'generate' ? ['element-plus'] : [],
  },
})
```

另外是不是页面上组件部分都要加 <client-only>这个呢。

**Comment by chenjiahan** [comment]
@leosin vant 3.5.0 已经优化了对 nuxt 3 的支持，可以试下有没有什么问题

**Comment by CharleeWa** [comment]
请问dark mode主题，只是vant组件的？还是说配置了这种模式，整个应用，包括自己写的自定义组件也会是dark theme 吗？

**Comment by chenjiahan** [comment]
> 请问dark mode主题，只是vant组件的？还是说配置了这种模式，整个应用，包括自己写的自定义组件也会是dark theme 吗？

只针对 Vant 组件的哈

**Comment by CharleeWa** [comment]
> > 请问dark mode主题，只是vant组件的？还是说配置了这种模式，整个应用，包括自己写的自定义组件也会是dark theme 吗？
> 
> 只针对 Vant 组件的哈

现在在做一个应用的dark mode。但是我对dark mode构成还不是很明白，所以请问只要应用了vant4提供的dark mode组件，就可以了。还是说需要一种插件，比如darkreader插件配合vant4去做dark theme?  简言之，vant4 之 dark mode 不能做到哪些？谢谢

**Comment by chenjiahan** [comment]
Vant 4 的 dark mode 是针对 Vant 组件的样式进行深色适配，但是你应用中的其他样式是由你自己的 CSS 代码控制的，这部分需要你通过 CSS 变量等形式去进行适配。

**Comment by chenjiahan** [comment]
如果对怎么做 dark mode 不了解，可以阅读这篇文章：https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

**Comment by CharleeWa** [comment]
> 

非常感谢！

**Comment by itsmyturn** [comment]
v4啥时候能出稳定版本

**Comment by aaronlamz** [comment]
nice 🎉

**Comment by wangjing013** [comment]
👍

**Comment by itsmyturn** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by qqcbqqkcel** [comment]
您好请问：datetime-picker 什么时候可以有

**Comment by itsmyturn** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by PXRace** [comment]
"vant": "4.0.0-alpha.4"。indexBar 组件崩了怎么办呢，

**Comment by itsmyturn** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by hqwlkj** [comment]
> "

具体错误信息呢？

**Comment by qiaozhu** [comment]
> 您好请问：datetime-picker 什么时候可以有

+1

**Comment by chenjiahan** [comment]
> datetime-picker 什么时候可以有

@qiaozhu 升级文档里有介绍

![image](https://user-images.githubusercontent.com/7237365/194994696-67fb0006-0ac4-4a0e-ab46-d3cba48e8b8f.png)

**Comment by qiaozhu** [comment]
> > datetime-picker 什么时候可以有
> 
> @qiaozhu 升级文档里有介绍
> 
> ![image](https://user-images.githubusercontent.com/7237365/194994696-67fb0006-0ac4-4a0e-ab46-d3cba48e8b8f.png)

nice🎉👍

**Comment by JunheeZ** [comment]
👍

**Comment by CracKerMe** [comment]
审核模式如何与 VueUSE结合使用啊，https://vueuse.org/core/useColorMode/
`useColorMode` 是动态需改 html 标签的class，而 vant 目前是给body增加了`van-theme-dark`的class名，有考虑变成 vueUse 的方式么？
求解答

**Comment by itsmyturn** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by CracKerMe** [comment]
bug: 日历组件暗色模式显示异常，https://vant-contrib.gitee.io/vant/v4/mobile.html#/zh-CN/calendar
官网提供了 `body {color: var(--van-doc-text-color-2);}`显示正常；
而 `--van-doc-text-color-2`值为：rgba(255, 255, 255, .9)
"vant": "4.0.0-rc.6" 依旧未修复

**Comment by chenjiahan** [comment]
@CracKerMe 单独提 issue，别在这个 issue 下面回复
