### ISSUE TITLE
[Bug Report] tabbar组件路由模式to='/'时切换不正常

### ISSUE THREAD

**Issue by yutons** [youzan/vant#10343]
### 重现链接

https://static-4ca3919d-85d6-4792-8507-3b7267c385b5.bspapp.com/

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

tabbar组件路由模式to='/'时切换不正常
demo地址如下：https://github.com/yutons/vant3-h5-demo

### 重现步骤

打开https://static-4ca3919d-85d6-4792-8507-3b7267c385b5.bspapp.com/
点击底部问答、视频、我的等按钮，底部左侧的首页一直处于激活状态

**Comment by BeatoLiu** [comment]
换成 to={name: 'Home'}试试

**Comment by yutons** [comment]
这个办法果然可以哦，能解释下什么原因或者什么原理吗

**Comment by chenjiahan** [comment]
只要 name 或 path 匹配上当前 route 对象，就会高亮喔
