### ISSUE TITLE
[Bug Report] vant button组件设置hairline属性为true后，安卓手机边框不显示

### ISSUE THREAD

**Issue by zhangqiangzgz** [youzan/vant#10349]
### 重现链接

暂无

### Vant 版本

3.3.5

### 描述一下你遇到的问题。

vant button组件设置hairline属性为true后，安卓手机边框不显示

### 重现步骤

vant button组件设置hairline属性为true后，安卓手机边框不显示

### 设备/浏览器

安卓手机

**Comment by chenjiahan** [comment]
使用小米 11 未复现此问题。

建议提供一下具体的型号，以及打开官网示例后的截图。
