### ISSUE TITLE
[Bug Report] Tabbar 标签栏加上route属性后选中状态失效

### ISSUE THREAD

**Issue by JacksMaster** [youzan/vant#10355]
### 重现链接

https://codesandbox.io/s/m5v3f

### Vant 版本

4.0.0-alpha.0

### 描述一下你遇到的问题。

Tabbar 标签栏加上route属性后选中状态失效

### 重现步骤

![image](https://user-images.githubusercontent.com/85353476/156732862-945657b2-b8ab-49db-85be-c4ecd26735fe.png)

这个是我的代码  

这个是我的相关插件版本
"vant": "4.0.0-alpha.0",
 "vue": "^3.2.31",
 "typescript": "~4.5.5",
构建工具：webpack

尝试将组件上的route属性去除 选中状态就恢复正常显示切换也是可以的 但是加上route属性选中状态失效，并且点击也没用。奇怪的是在codesandbox上是正常的 但是在我本地环境就不行  我尝试将node_modules依赖删除 重新pnpm install然后再运行 问题依旧存在

去除route属性的效果是这样的
![image](https://user-images.githubusercontent.com/85353476/156733355-07b4eac2-d728-448f-b580-178904c4d82c.png)

加上route属性的效果是
![image](https://user-images.githubusercontent.com/85353476/156733312-4d5e8683-45f2-44bc-82a0-5adc1725b52f.png)

### 设备/浏览器

Chrome 100

**Comment by chenjiahan** [comment]
route 模式下需要设置 to 属性，否则无法匹配到路由。
