### ISSUE TITLE
[Bug Report] 关于组件中引入type的写法问题

### ISSUE THREAD

**Issue by cumtchj** [youzan/vant#10352]
### 重现链接

无重现链接

### Vant 版本

3.4.5，3.4.3

### 描述一下你遇到的问题。

组件中有很多d.ts 文件引入了type，在引入type的时候出现三种写法

-  1、import { PropType }  from 'vue' 
-  2、import type { PropType }  from 'vue'  
-  3、import { type PropType }  from 'vue' ;

这三种写法在 NODE_ENV === 'development' 的时候打包运行都没有问题，但是在 NODE_ENV === 'production' 下打包第三种情况会报语法错误，在3.3.0版本中因为所有的type引入都没有加type关键字，也就是都是第一种引入方式，所以各个环境打包都没有问题。
附上typescript v3.8关于import type类型的语法文档地址：[https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html)

### 重现步骤

贴上package.json文件的依赖：
 "dependencies": {
    "axios": "^0.24.0",
    "core-js": "^3.6.5",
    "dayjs": "^1.10.7",
    "echarts": "^5.2.2",
    "html2canvas": "^1.3.2",
    "lodash": "^4.17.21",
    "mescroll.js": "^1.4.2",
    "normalize.css": "^8.0.1",
    "nprogress": "^0.2.0",
    "register-service-worker": "^1.7.1",
    "uuid": "^8.3.2",
    "vant": "3.3.0",  //     如果是 "vant": "^3.3.0" 拉到最新的版本，打production环境的包就会报type引入的语法问题
    "vue": "^3.0.0",
    "vue-axios": "^3.4.0",
    "vue-class-component": "^8.0.0-0",
    "vue-eslint-parser": "^8.3.0",
    "vue-loader-v16": "^16.0.0-beta.5.4",
    "vue-router": "^4.0.0-0",
    "vue-wechat-title": "^2.0.7",
    "vuex": "^4.0.0-0",
    "yarn": "^1.22.17"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-pwa": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.4.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "babel-eslint": "^10.1.0",
    "commitizen": "^4.2.4",
    "conventional-changelog-cli": "^2.1.1",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.20.0",
    "prettier": "^2.2.1",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "typescript": "~4.1.5",
    "uglifyjs-webpack-plugin": "^2.2.0"
  },

**Comment by chenjiahan** [comment]
这几个都是合法的语法，建议你升级下 TS 版本。
