### ISSUE TITLE
[Bug Report] Cannot find name 'VisibilityState' export declare function usePageVisibility(): Ref<VisibilityState>;

### ISSUE THREAD

**Issue by zhujunel** [youzan/vant#10362]
### Reproduction Link

https://github.com/youzan/vant

### Vant Version

3.4.5、4.0.0-alpha.0

### Describe the Bug

运行没有问题，在执行 yarn build 时报错
<img width="1006" alt="yarn beildiprol" src="https://user-images.githubusercontent.com/6083708/157031936-4e978dd3-bed2-428e-9f4e-bb4505eb659b.png">

### Reproduce Steps

直接yarn build
`{
    "name": "vite-vue3-template",
    "private": true,
    "version": "0.0.0",
    "scripts": {
        "mock": "vite --mode mock",
        "dev": "vite --mode development",
        "test": "vite --mode test",
        "build": "vue-tsc --noEmit && vite build",
        "build:test": "vue-tsc --noEmit && vite build --mode test",
        "build:prod": "vue-tsc --noEmit && vite build --mode production",
        "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore",
        "preview": "vite preview",
        "prepare": "husky install",
        "lint:stylelint": "stylelint --cache --fix \"**/*.{vue,less,postcss,css,scss}\" --cache --cache-location node_modules/.cache/stylelint/"
    },
    "dependencies": {
        "axios": "^0.26.0",
        "dayjs": "^1.10.8",
        "pinia": "^2.0.11",
        "vant": "^3.4.5",
        "vconsole": "^3.12.1",
        "vue": "^3.2.25",
        "vue-router": "^4.0.13"
    },
    "devDependencies": {
        "@types/mockjs": "^1.0.6",
        "@types/node": "^17.0.21",
        "@typescript-eslint/eslint-plugin": "^5.13.0",
        "@typescript-eslint/parser": "^5.13.0",
        "@vitejs/plugin-vue": "^2.2.0",
        "@vitejs/plugin-vue-jsx": "^1.3.8",
        "autoprefixer": "^10.4.2",
        "eslint": "^8.10.0",
        "eslint-config-prettier": "^8.4.0",
        "eslint-define-config": "^1.2.5",
        "eslint-plugin-prettier": "^4.0.0",
        "eslint-plugin-vue": "^8.5.0",
        "husky": "^7.0.4",
        "less": "^4.1.2",
        "lint-staged": "^12.3.4",
        "mockjs": "^1.1.0",
        "postcss-html": "^1.3.0",
        "prettier": "^2.5.1",
        "stylelint": "^14.5.3",
        "stylelint-config-html": "^1.0.0",
        "stylelint-config-prettier": "^9.0.3",
        "stylelint-config-recommended": "^7.0.0",
        "stylelint-config-standard": "^25.0.0",
        "stylelint-order": "^5.0.0",
        "typescript": "^4.5.4",
        "unplugin-icons": "^0.13.2",
        "unplugin-vue-components": "^0.17.21",
        "vite": "^2.8.0",
        "vite-plugin-compression": "^0.5.1",
        "vite-plugin-html": "^3.1.0",
        "vite-plugin-mock": "^2.9.6",
        "vite-plugin-style-import": "1.4.1",
        "vite-plugin-vconsole": "^1.2.0",
        "vite-svg-loader": "^3.1.2",
        "vue-tsc": "^0.29.8"
    }
}
`

**Comment by nemo-shen** [comment]
复现代码提供下

**Comment by zhujunel** [comment]
通过命令创建的项目:
`yarn create vite my-vue-app --template vue-ts`

然后就导入了 vant，yarn build 就报错


复现代码：https://codesandbox.io/s/nervous-varahamihira-l1f48r?file=/src/main.ts

**Comment by zhujunel** [comment]
测试了几个版本 `vant@3.1.0` 没有问题，可以 build

**Comment by flycj** [comment]
+1
```
yarn build
yarn run v1.22.10
$ vue-tsc --noEmit && vite build
node_modules/@vant/use/dist/usePageVisibility/index.d.ts:2:50 - error TS2304: Cannot find name 'VisibilityState'.

2 export declare function usePageVisibility(): Ref<VisibilityState>;
                                                   ~~~~~~~~~~~~~~~


Found 1 error in node_modules/@vant/use/dist/usePageVisibility/index.d.ts:2

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
出现相同的错误

**Comment by nejinn** [comment]
`
> vue-tsc --noEmit && vite build

node_modules/@vant/use/dist/usePageVisibility/index.d.ts:2:50 - error TS2304: Cannot find name 'VisibilityState'.

2 export declare function usePageVisibility(): Ref<VisibilityState>;
                                                   ~~~~~~~~~~~~~~~


Found 1 error in node_modules/@vant/use/dist/usePageVisibility/index.d.ts:2`

**Comment by destiny-glith** [comment]
warning ..\..\..\package.json: No license field
$ vue-tsc --noEmit && vite build --mode uat
node_modules/@vant/use/dist/usePageVisibility/index.d.ts:2:50 - error TS2304: Cannot find name 'VisibilityState'.
                                                                                                                 
2 export declare function usePageVisibility(): Ref<VisibilityState>;                                             
                                                   ~~~~~~~~~~~~~~~                                               


Found 1 error in node_modules/@vant/use/dist/usePageVisibility/index.d.ts


同样的错误，咋解决

**Comment by izhaong** [comment]
vant@vant/use包对typescript的版本有限制，typescript4.5.5版本以后，不在支持VisibilityState状态，所以需要修改typescript版本的依赖

```
"devDependencies": {
   "typescript": "~4.5.2",
}
```

@flycj @zhujunel @nemo-shen @nejinn @destiny-glith

**Comment by zhujunel** [comment]
@izhaong 👍，可以了

**Comment by destiny-glith** [comment]
> 

本地试好了，但是线上linux系统构建 还是报那个错误。不知道你们是不是

**Comment by destiny-glith** [comment]
@izhaong 本地试好了，但是线上linux系统构建 还是报那个错误。不知道你们是不是

**Comment by chenjiahan** [comment]
看起来是 TS 4.6 进行了一个 breaking change，把 `VisibilityState` 类型重命名为了 `DocumentVisibilityState`，我们会适配下。

https://github.com/microsoft/TypeScript/issues/47908#:~:text=%27-,VisibilityState,-%27%20(got%20renamed%20to

**Comment by chenjiahan** [comment]
已发布 @vant/use 1.3.6 修复版本
