### ISSUE TITLE
swipe没有点击事件啊

### ISSUE THREAD

**Issue by dhx1213** [youzan/vant#1036]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
Swipe 只是一个容器，事件可以在内容里绑定
