### ISSUE TITLE
[Bug Report] Toast先调用type="html"类型的提示之后，再调用type="loading"类型，loading提示文字缺失

### ISSUE THREAD

**Issue by zengweigui** [youzan/vant#10366]
### 重现链接

https://codesandbox.io/embed/vant-issue-mo-ban-forked-e3xhpi?fontsize=14&hidenavigation=1&theme=dark

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

Toast 轻提示 调用type=“html”类型的提示后，再调用type="loading"类型提示，loading文字不展示问题

### 重现步骤

先点“HTML类型”按钮，再点“LOADING类型”按钮，可重现

### 设备/浏览器

微信开发者工具、手机浏览器，微信内置浏览器

**Comment by chenjiahan** [comment]
这个问题已经修复过了，待 3.4.6 版本发布即可

相关 PR: https://github.com/youzan/vant/pull/10311
