### ISSUE TITLE
[Bug Report] 在ActionSheet中嵌套Calendar首次渲染时控制台抛出opened事件错误

### ISSUE THREAD

**Issue by dreammaker7** [youzan/vant#10360]
### 重现链接

https://codesandbox.io/s/modern-haze-vb7qre?file=/src/App.vue

### Vant 版本

2.12.44

### 描述一下你遇到的问题。

在ActionSheet组件中嵌套Calendar组件，渲染Calendar后控制台抛出：[Vue warn]: Error in event handler for "opened": "TypeError: Cannot use 'in' operator to search for 'scrollTop' in undefined"

### 重现步骤

上方给出codesandbox示例的复现步骤
1. 首次点击 Toggle ActionSheet

### 设备/浏览器

Chrome/98.0.4758.102

**Comment by chenjiahan** [comment]
你好，Vant 2 版本已经不再主动进行迭代，且 Vant 3 中未复现此问题。

如果需要在 Vant 2 进行修复，欢迎提 Pull Request。

**Comment by pencilcheck** [comment]
is there a pointer to guide for a fix? i am new to the project and I want this fixed, but I don't know which files to look into.

**Comment by pencilcheck** [comment]
looks like the workaround is to move vant-calendar outside vant-popup. It would be nice if there is a "portal" vant element that move the calendar out automatically.

**Comment by chenjiahan** [comment]
> is there a pointer to guide for a fix in vant 2?

See: https://vant-contrib.gitee.io/vant/v2/#/zh-CN/contribution

> It would be nice if there is a "portal" vant element

We should not move calendar outside popup, this will break the component style. And there is already a `Teleport` component in Vue 3.

**Comment by supuwoerc** [comment]
同样也遇到了这个问题，v-if做了次条件渲染处理掉了

**Comment by fengyun2** [comment]
> 同样也遇到了这个问题，v-if做了次条件渲染处理掉了

添加了v-if还是会遇到这个问题
```vue
<ActionSheet v-model="actionShow">
      <div class="content">
        <button @click="show = !show">Toggle Calendar</button>
        <Calendar
          v-if="show"
          v-model="show"
          color="#1989fa"
          :show-confirm="false"
        />
      </div>
    </ActionSheet>
```
