### ISSUE TITLE
[Bug Report] van-search有键盘方法吗

### ISSUE THREAD

**Issue by wangdongzuopin** [youzan/vant#10369]
### 重现链接

https://github.com/youzan/vant/issues/new

### Vant 版本

2.12.36

### 描述一下你遇到的问题。

van-search有键盘方法吗

### 重现步骤

van-search有键盘方法吗

### 设备/浏览器

app

**Comment by nemo-shen** [comment]
要知道 **vant是移动端组件库**，移动端没有快捷键搜索，因此vant也不会增加任何快捷键来方便桌面端操作
