### ISSUE TITLE
[Bug Report] 具名插槽slot 中使用空的template会被默认渲染出来，在vant2中没有这个表现，因为两个版本的判断是否通过slot渲染的条件不同导致

### ISSUE THREAD

**Issue by MGRookie** [youzan/vant#10361]
### 重现链接

v2版本：https://codesandbox.io/s/vant-issue-mo-ban-forked-mc16nt v3版本：https://codesandbox.io/s/vant-issue-mo-ban-forked-yvsb23

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

在vant2的时候用空的tempalge不会被渲染出来，vant3的空的templage会被渲染出来，看了vant2和vant3的源代码，发现是两者在判断是否使用slot渲染时候有差别。
在vant2的是：
```js
slots: function slots(name, props) {
      if (name === void 0) {
        name = 'default';
      }
      var $slots = this.$slots,
          $scopedSlots = this.$scopedSlots;
      var scopedSlot = $scopedSlots[name];
      if (scopedSlot) {
        return scopedSlot(props);
      }
      return $slots[name];
    }
```
在vant3的是:
```js
setup({slots}){
      if (slots.left) { 
          return slots.left();
      }
}
```

### 重现步骤

1.使用navbar 设置相同的slot 和 props
2.在vant2中如果templat为空时，显示props；在vant3中始终会显示空的tanplate
v2版本：https://codesandbox.io/s/vant-issue-mo-ban-forked-mc16nt v3版本：https://codesandbox.io/s/vant-issue-mo-ban-forked-yvsb23

**Comment by chenjiahan** [comment]
这个是符合预期的，在 Vue 3 中，scopedSlot 和 slot 被统一了，当 slots.xxx 存在的时候，我们就认为需要使用 slot 传入的内容。

如果这不符合你的预期，请避免使用空的 template。
