### ISSUE TITLE
按需引用的button这么大么？

### ISSUE THREAD

**Issue by bbhxwl** [youzan/vant#10363]
vue2 安装下面的这个。
npm i vant@latest-v2
我下面这样引用的。只用了button，捆绑包也是1M这么大么？
新手不太明白是不是我这不是按需引用的？
![image](https://user-images.githubusercontent.com/26525599/157042127-4726e43c-b8fc-4c07-a5ad-1c3054772c2c.png)
![image](https://user-images.githubusercontent.com/26525599/157042183-e128e02a-9a36-4cc1-b3cf-f11338480132.png)
![image](https://user-images.githubusercontent.com/26525599/157042223-263cad68-b257-4360-a847-ac8975df5014.png)

**Comment by nemo-shen** [comment]
[hello-world.zip](https://github.com/youzan/vant/files/8198765/hello-world.zip)
