### ISSUE TITLE
[Bug Report] 4.0.0-alpha.0的一些BUG

### ISSUE THREAD

**Issue by wltj920** [youzan/vant#10364]
### 重现链接

没有链接

### Vant 版本

4.0.0-alpha.0

### 描述一下你遇到的问题。

* DatePicker组件无法给v-model赋值
* DatePicker组件的formatter无效
* ConfigProvider组件的themeVars无效
* 深色模式中，Dialog组件的标题未适配（本人已提PR解决：[#10379 ]）
* Picker组件中，v-model应该如何绑定，绑定为value值会报错

### 重现步骤

* DatePicker组件无法给v-model赋值
* DatePicker组件的formatter无效
* ConfigProvider组件的themeVars无效

> 按官方的例子操作也不行

### 设备/浏览器

Edge/Chrome/小米浏览器

**Comment by chenjiahan** [comment]
> DatePicker组件无法给v-model赋值

已在 4.0.0-alpha.1 修复

> DatePicker组件的formatter无效

文档写错了，已更新文档

> ConfigProvider组件的themeVars无效

没复现，可以给个 codesandbox 链接看下

> Picker组件中，v-model应该如何绑定

已补充文档
