### ISSUE TITLE
[Bug Report] van-button 当 loading 或 disabled 时，.stop 无效

### ISSUE THREAD

**Issue by Elvmx** [youzan/vant#10371]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-cio9kg?file=/src/App.vue

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

van-button 组件使用 .stop 修饰符，阻止冒泡。
但是在 设置了  loading 或 disabled 时无效。

### 重现步骤

1. 点击按钮
2. 期望不触发 fn2 函数

**Comment by nemo-shen** [comment]
默认行为，实际你使用 `<button />` 也会得到同样的结果，这是我基于你的codesandbox 调整的，你可以点一下原生的 button试试（在禁用状态）
https://codesandbox.io/s/vant-issue-mo-ban-forked-x2zdke?file=/src/App.vue

**Comment by Elvmx** [comment]
我有使用普通 `<button />` 来测试来着。不知道是不是因为你在 button 中增加了 div 的原因

https://codesandbox.io/s/vant-issue-mo-ban-forked-x2zdke?file=/src/App.vue
