### ISSUE TITLE
[Bug Report] 在自定义组件中使用了vant组件和useParent获取vant-form组件的props时，表单校验报错

### ISSUE THREAD

**Issue by J-Yowane-Haku** [youzan/vant#10372]
### 重现链接

https://github.com/J-Yowane-Haku/vant

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

App.vue:
![image](https://user-images.githubusercontent.com/53861402/157575089-b058b8f8-841d-44f8-a046-035e425c4357.png)

HelloWord.vue:
![image](https://user-images.githubusercontent.com/53861402/157575219-ee815fb8-f248-47ec-927f-5b1f03b46fea.png)

错误信息：
![image](https://user-images.githubusercontent.com/53861402/157575310-c5fc6177-bfd9-4d5d-bc5e-b5816896c655.png)

### 重现步骤

1. 在自定义组件中使用vant-field组件
2. 自定义组件中使用useParent获取form组件的属性
3. 使用 van-form包裹自定义组件
4. 调用form组件的validate方法

### 设备/浏览器

edge

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by J-Yowane-Haku** [comment]
解决了，看了下 useParent 和 useChildren 的代码，不使用 useParent ，直接使用 inject 就行了
