### ISSUE TITLE
为什么shrink 不能靠左显示呢？

### ISSUE THREAD

**Issue by bbhxwl** [youzan/vant#10376]
···

import Vue from 'vue';
import { Tab, Tabs } from 'vant';
import 'vant/lib/index.css'
Vue.use(Tab);
Vue.use(Tabs);
···
···
<van-tabs  shrink>
    <van-tab  v-for="index in 4" v-bind:key="index" :title="'选项 ' + index">
      内容 {{ index }}
    </van-tab>
  </van-tabs>
···

**Comment by nemo-shen** [comment]
按规范提issue
