### ISSUE TITLE
[Bug Report] <van-nav-bar>中的双击事件失效

### ISSUE THREAD

**Issue by liuyingqq123** [youzan/vant#10375]
### 重现链接

//

### Vant 版本

2.12.42

### 重现步骤

双击没有走定义的toTop方法  
```html
<div>
    <van-nav-bar>
      <template slot="title">
        <div @dblclick.native="toTop">
          {{ title }}
        </div>
      </template>
    </van-nav-bar>
  </div>
```

**Comment by nemo-shen** [comment]
1. vant是移动端框架，像双击这种场景移动端不太会去做
2. 你这代码看起来有问题，为什么在一个div标签上要用 .native 做修饰？去掉不是就能正常双击了吗？

**Comment by liuyingqq123** [comment]
> 1. vant是移动端框架，像双击这种场景移动端不太会去做
> 2. 你这代码看起来有问题，为什么在一个div标签上要用 .native 做修饰？去掉不是就能正常双击了吗？

1. 其实想加一个双击title区域, 滚动到最上面.
2. 肯定试过的啊, 不可能冒冒失失的来提问的.
