### ISSUE TITLE
[Bug Report] van-field 组件 无论设置什么type 得到的modelValue类型不匹配

### ISSUE THREAD

**Issue by jayzch** [youzan/vant#10377]
### 重现链接

https://github.com/youzan/vant

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

van-field 组件 无论设置什么type 得到的modelValue类型 永远是  String

### 重现步骤

设置了type不同的 值
并且通过函数强制设置了对应 绑定字段  值为数字类型

**Comment by chenjiahan** [comment]
Field 内部是统一使用 string 类型的喔，如果需要 number 类型，可以使用 `.number` 修饰符。

https://vuejs.org/guide/essentials/forms.html#number

**Comment by jayzch** [comment]
> Field 内部是统一使用 string 类型的喔，如果需要 number 类型，可以使用 `.number` 修饰符。
> 
> https://vuejs.org/guide/essentials/forms.html#number

好吧。之前用:value 时 类型是正常的。
