### ISSUE TITLE
[Bug Report] Skeleton设置class会有警告

### ISSUE THREAD

**Issue by yifengyoujian** [youzan/vant#10378]
### 重现链接

https://codesandbox.io/s/vant-3-6-5-forked-edqkrx?file=/src/App.vue

### Vant 版本

3.6.5

### 描述一下你遇到的问题。

skeleton组件使用了默认插槽并且设置了class的情况下vue3会有警告, 其他两种情况下没有警告

### 重现步骤

查看console打印日志

**Comment by chenjiahan** [comment]
下个版本会修复此问题
