### ISSUE TITLE
日历组件 自定义文案 formatter 暂时无法支持异步

### ISSUE THREAD

**Issue by lookwe** [youzan/vant#10380]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/calendar#zi-ding-yi-ri-qi-wen-an

### Vant 版本

^2.12.37

### 描述一下你遇到的问题。

* 如果遇到异步需求，则无法实现自定义文本
* ``formatter``函数里获取不到异步读取数据
* 希望``formatter``可以支持异步操作

### 重现步骤

1. 日程文字需要从后端接口获取
2. 对比日期，并在对应天数，加上对于后端返回文本信息
3. ``created()`` 钩子获取的后端数据，发现在formatter函数里则为`undefined`

### 设备/浏览器

* 谷歌

**Comment by k186** [comment]
先加锁绕过去吧，异步结果没回来之前不允许展开

**Comment by chenjiahan** [comment]
如果需要在 formatter 中使用异步返回的数据，可以使用计算属性动态创建 formatter 函数，示例如下：

```js
const asyncData = ref();

const formatter = computed(() => {
  if (!asyncData.value) {
    return (day) => day;
  }
  return (day) => {
    day.bottomInfo = asyncData.value;
    return day;
  };
});

setTimeout(() => {
  asyncData.value = '后端文案';
}, 3000);
```
