### ISSUE TITLE
[Feature Request] Popover 限制高度支持滚动条

### ISSUE THREAD

**Issue by ydc544696000** [youzan/vant#10381]
### 这个功能解决了什么问题？

我们公司的需求是点击出现下拉框的选项，但是选项比较多，而popover没有限制高度，我通过全局样式限制高度后确实出现了滚动条，也将overflow设置成了socll，但是在真机操作时滑动会有失灵的现象，如果前边已将滚动条滚动，再次打开就很流畅，只要是滚动条在顶部，就会有问题，现在具体问题还没查明，就算我自己限制高度了，还得在关闭的时候让滚动条至0，相对的tree-select就没有滑动失效的问题，只是缺少一个让滚动条置顶的api

### 你期望的 API 是什么样子的？

<van-popover scoll scoll-top:0><van-popover>

**Comment by chenjiahan** [comment]
由于 Popover 弹出的位置是不确定的，因此不适合在组件内部置一个固定的默认最大高度，还是根据实际情况进行设置比较合适。

至于你说的滑动问题，可以在滚动元素上添加以下样式属性试试：

```css
overflow-y: auto;
-webkit-overflow-scrolling: touch;
```

**Comment by ydc544696000** [comment]
> Popover 屋顶的位置是置放的，因此不适合在内部组件的一个默认最大高度，还是根据实际情况进行设置比较合适的。
> 
> 你说的滑动问题，可以在滚动元素上添加以下样式属性：
> 
> ```css
> 溢出-y ：自动；
> -webkit-overflow-scrolling ：触摸；
这个属性已经设置了，因为我发现组件内部样式.van-popover__content overflow：hiden 我用全局样式把他覆盖了还是不行，vue的版本2.6.11，vant版本2.12.37，也没有用fastclick组件，我在想是不是popover里面的touch事件影响的滑动，tree-select超过高度就会出现滚动条而且滑动很丝滑，但是popover就不行，要滑很多次才有效

**Comment by chenjiahan** [comment]
Popover 里只有一个 touchstart 事件，应该没什么影响的，你可以注释掉 touchstart 的逻辑试试

**Comment by chenjiahan** [comment]
了解👌🏻

**Comment by supuwoerc** [comment]
> > Popover 里只有一个 touchstart 事件，应该没什么影响的，你可以注释掉 touchstart 的逻辑试试
> 
> 问题已找到并解决，我们的业务逻辑需求是在Dialog的弹框中点击Field组件出现Popover，而且popover里面是个列表需要出现滚动条，滚动有时失灵的原因是因为，Dialog默认lockScoll锁定了背景滚动，阻止了touchmove的默认行为，把Dialog的lockScroll设为false，再解决下背景滑动穿透的问题就可以了...

你好，我也遇到了类似的问题，在真机上popover滚动卡顿/失效，但是我做的需求是一个输入联想的功能，没出现你的dialog，请教下你解决问题的具体方法，如果方便的话能简单看些下面代码出现的问题吗？万分感谢~  
```
<van-popover
    :value="showPopover"
    :offset="[-8, 0]"
    placement="bottom-start"
>
    <template #reference>
        <input
            v-model="labelValue"
            placeholder="请填写"
            type="text"
            class="keyword"
            @input="search"
        />
    </template>
    <div class="suggestions">
        <van-cell
            v-for="(item, index) in suggestions"
            :key="index"
            value="内容内容内容内容内容内容内容内容内容内容内容内容"
        />
    </div>
</van-popover>
```

**Comment by ydc544696000** [comment]
> > > Popover 里只有一个 touchstart 事件，应该没什么影响的，你可以注释掉 touchstart 的逻辑试试
> > 
> > 
> > 问题已找到并解决，我们的业务逻辑需求是在Dialog的弹框中点击Field组件出现Popover，而且popover里面是个列表需要出现滚动条，滚动有时失灵的原因是因为，Dialog默认lockScoll锁定了背景滚动，阻止了touchmove的默认行为，把Dialog的lockScroll设为false，再解决下背景滑动穿透的问题就可以了...
> 
> 你好，我也遇到了类似的问题，在真机上popover滚动卡顿/失效，但是我做的需求是一个输入联想的功能，没出现你的dialog，请教下你解决问题的具体方法，如果方便的话能简单看些下面代码出现的问题吗？万分感谢~
> 
> ```
> <van-popover
>     :value="showPopover"
>     :offset="[-8, 0]"
>     placement="bottom-start"
> >
>     <template #reference>
>         <input
>             v-model="labelValue"
>             placeholder="请填写"
>             type="text"
>             class="keyword"
>             @input="search"
>         />
>     </template>
>     <div class="suggestions">
>         <van-cell
>             v-for="(item, index) in suggestions"
>             :key="index"
>             value="内容内容内容内容内容内容内容内容内容内容内容内容"
>         />
>     </div>
> </van-popover>
> ```

抱歉 很久没关注邮箱，你可以尝试设置全局样式设置
/* popover组件和 #app 是同一级只能通过全局样式修改 */

/* 1.通过给actions中的每一项添加className自定义全局类名，但有局限性 */

/* .my-popover__item {
  width: 288px;
  height: 32px;
  } */

/* 2.直接修改组件的全局样式 */
.van-popover--light .van-popover__content {
  width: 288px;

  /* 限制选项容器高度，让其出现滚动条 */
  max-height: 128px;
  overflow: auto;
  overflow-y: scroll;
  -webkit-overflow-scrolling: touch;
  box-sizing: border-box;
}

.van-popover__action {
  /* 设置展示的选项的宽度和输入框保持一致 */
  width: auto;
  height: 32px;
  font-size: 14px;
  line-height: 20px;
}

.van-popover__action-text {
  /* 更改选项文字的对齐方式 */
  justify-content: start;
}

如果看了popover的源码你会发现他是基于popup 封装的，popup里面针对touchmouve等时间做了处理，我的那个场景就是这样个原因，而默认是锁定背景滚动的，那这样popover里面的滑动就会被阻止，所以你打开背景滚动，如果你的背景也跟着一起滚动，再解决滚动穿透，看能否解决，滚动穿透可以参考https://www.cnblogs.com/padding1015/p/10568070.html（网上搜索到的帖子）
