### ISSUE TITLE
[Bug Report] 2的版本里面，Tab 能靠左显示么。

### ISSUE THREAD

**Issue by bbhxwl** [youzan/vant#10394]
### 重现链接

·

### Vant 版本

2.12.44

### 描述一下你遇到的问题。

我看vant3里面，设置shrink 属性可以让他靠左，但是我暂时升级不了vant3，能实现么。

### 重现步骤

我看vant3里面，设置shrink 属性可以让他靠左，但是我暂时升级不了vant3，能实现么。

**Comment by chenjiahan** [comment]
可以参考 Vant 3 里的样式，自行添加对应的 CSS
