### ISSUE TITLE
[Bug Report] 小米8青春版 使用vant-uploader 组件上传 点击无反应

### ISSUE THREAD

**Issue by Battle-on** [youzan/vant#10396]
### 重现链接

https://user-images.githubusercontent.com/22757801/158593174-ab874aac-a3d3-4fb2-946c-cc8d231bbf9a.mp4

### Vant 版本

2.12.36

### 描述一下你遇到的问题。

点击上传弹不出照片

`   <van-uploader
            :before-read="beforeRead"
            :after-read="afterRead"
            :multiple="false"
            v-model="fileList"
            @delete="handleDelete"
          >
          </van-uploader>`

### 重现步骤

https://codesandbox.io/embed/vant-issue-mo-ban-forked-0ibnlu?fontsize=14&hidenavigation=1&theme=dark

### 设备/浏览器

小米8青春版本

**Comment by Battle-on** [comment]
https://codesandbox.io/embed/vant-issue-mo-ban-forked-0ibnlu?fontsize=14&hidenavigation=1&theme=dark

**Comment by Battle-on** [comment]
> 提供复现代码

https://codesandbox.io/embed/vant-issue-mo-ban-forked-0ibnlu?fontsize=14&hidenavigation=1&theme=dark
麻烦大佬看一下

**Comment by chenjiahan** [comment]
这边没有对应的机型，我用小米 11 试了下正常的，建议你用原生 input type="file" 试一下能否上传
