### ISSUE TITLE
[Feature Request] 下拉选择组件

### ISSUE THREAD

**Issue by Soumns777** [youzan/vant#10393]
### 这个功能解决了什么问题？

希望出一个像element类似的el-select类似的功能,可以实现下拉选择的效果。

### 你期望的 API 是什么样子的？

<van-select :options=''>

</van-select>

**Comment by chenjiahan** [comment]
移动端请使用 Picker 组件喔

**Comment by lxqgithub** [comment]
> 

Picker 不支持多选的嘛
