### ISSUE TITLE
field 的自定义按钮不能显示

### ISSUE THREAD

**Issue by 635663429** [youzan/vant#1039]
<van-cell-group>
  <van-field
    center
    v-model="sms"
    label="短信验证码"
    placeholder="请输入短信验证码"
    icon="clear"
    @click-icon="sms = ''"
  >
    <van-button slot="button" size="small" type="primary">发送验证码</van-button>
  </van-field>
</van-cell-group>

**Comment by chenjiahan** [comment]
请升级到最新版本再试
