### ISSUE TITLE
麻烦问一下tab怎么让内容高度百分百，

### ISSUE THREAD

**Issue by bbhxwl** [youzan/vant#10405]
body已经是百分百了。
<img width="765" alt="image" src="https://user-images.githubusercontent.com/26525599/158847125-1a547ea9-84c9-44d0-a7c8-69da8c587622.png">
<img width="697" alt="image" src="https://user-images.githubusercontent.com/26525599/158847246-126a662d-b28f-402c-97c0-02f10894da92.png">

**Comment by chenjiahan** [comment]
```css
height: calc(100vh-50px)
```

**Comment by bbhxwl** [comment]
> ```css
> height: calc(100vh-50px)
> ```
没有成功，求指点。
![image](https://user-images.githubusercontent.com/26525599/158927460-9bcf67fa-1469-4073-a24e-9e5d535473b3.png)
![image](https://user-images.githubusercontent.com/26525599/158927543-1e4b9e66-36d2-4300-9b13-c42a8b93d4f9.png)
![image](https://user-images.githubusercontent.com/26525599/158927578-373edbf1-a38d-449b-b5ab-16ca9c21f0c2.png)

**Comment by chenjiahan** [comment]
设置到 content 节点上

**Comment by bbhxwl** [comment]
> ```css
> ```css
> height: calc(100vh-50px)
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```
我最外层已经能看出来是百分百了。但是很难设置van-tabs__content的属性，我在浏览器把van-tabs__content 设置百分百就可以用，但是style一直设置不上。
![image](https://user-images.githubusercontent.com/26525599/158928171-5f5766c0-6603-4a12-a3e7-ed8e4ea594be.png)
![image](https://user-images.githubusercontent.com/26525599/158928193-a65dc839-ead5-4365-a916-f6e4373f73d5.png)

**Comment by bbhxwl** [comment]
> 设置到 content 节点上
我在浏览器这样加可以，但是样式里面怎么加都不行，不知道什么原因。class就是van-tabs__content 啊

![image](https://user-images.githubusercontent.com/26525599/158928694-0f6c2ece-380b-488e-b5e3-66260546fa8f.png)

**Comment by bbhxwl** [comment]
> 设置到 content 节点上
是不是因为这个没有data-v- 的属性，才不能设置上的？

![_{ XYXR 25W9N SH~4{QRC6](https://user-images.githubusercontent.com/26525599/158929190-59983438-bcb9-4a55-a9f6-c52dae6cbf5e.png)

**Comment by bbhxwl** [comment]
确实因为这个原因。
![image](https://user-images.githubusercontent.com/26525599/158929700-fd663e3a-8966-4b1c-a7c1-a7773054fdbc.png)
