### ISSUE TITLE
[Bug Report]  VantResolver 自动导入打包后会导致css加载顺序错误 

### ISSUE THREAD

**Issue by yanbowe** [youzan/vant#10408]
### 重现链接

https://github.com/yanbowe/vite-vant-demo

### Vant 版本

3.4.6

### 描述一下你遇到的问题。

1.当Button组件和ActionBar和组件一起使用后本地运行正常，打包后ActionBar样式顺序错乱，与本地开发不一致。

线上：
![image](https://user-images.githubusercontent.com/43030980/158920466-22bb195f-343b-49bd-9570-43774b4dcdd8.png)

本地： 
![image](https://user-images.githubusercontent.com/43030980/158920488-d02b02eb-a5b7-4eb9-a2e8-b5c990457242.png)

### 重现步骤

1.pnpm安装依赖
2.执行pnpm build 和 pnpm preview命令
3.运行查看效果与本地运行不一致

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
Vant 自身的样式是保证了正确顺序的，这属于打包工具的问题，建议你到打包工具相关的仓库下反馈

**Comment by verynong** [comment]
so 靓仔你怎么解决 @yanbowe

**Comment by Deeyu** [comment]
有好的解决方案吗？search组件今天也碰到这个问题了，刷新页面css加载顺序就不对了

![image](https://user-images.githubusercontent.com/33755522/205780773-7d8be5af-b5c7-4893-be0b-d16ec7d558e9.png)
![image](https://user-images.githubusercontent.com/33755522/205780807-83bb0c52-119b-4b21-b162-154e45ba3cc1.png)

**Comment by TzcTzcTzc** [comment]
> search
遇到同样的问题，用vite打包

**Comment by xu-Aurora** [comment]
> 有好的解决方案吗？search组件今天也碰到这个问题了，刷新页面css加载顺序就不对了
> 
> ![image](https://user-images.githubusercontent.com/33755522/205780773-7d8be5af-b5c7-4893-be0b-d16ec7d558e9.png) ![image](https://user-images.githubusercontent.com/33755522/205780807-83bb0c52-119b-4b21-b162-154e45ba3cc1.png)

我也遇到了一样的这个问题，请问最后怎么解决的？

**Comment by coderszh** [comment]
我也遇到了一样的这个问题，请问最后怎么解决的？

**Comment by Airkro** [comment]
Search 和 Cell 的样式就是会相互冲突，因为 Search 用了 Cell 的样式

**Comment by TXLkb** [comment]
我解决了，在导入里面加上参数importStyle: false就可以了。

```javascript
VantResolver({
  importStyle: false,
})
```

因为他会导入样式，而vant的样式本身就要自己在导入：
```javascript
import 'vant/lib/index.css';
```
如果没有添加参数就会像这样：
<img width="943" height="764" alt="Image" src="https://github.com/user-attachments/assets/891db7cc-62e7-4677-adbd-7948a3a5a05f" />
正常情况的：
<img width="989" height="705" alt="Image" src="https://github.com/user-attachments/assets/82f0c27f-b020-4851-87b4-1907c48bd2fe" />

解决后又用百度搜了一下`VantResolver importStyle`,已经有人遇到并解决过了。
