### ISSUE TITLE
[Bug Report] 初始化设置深色模式无效

### ISSUE THREAD

**Issue by yanbowe** [youzan/vant#10409]
### 重现链接

https://github.com/yanbowe/vite-vant-demo

### Vant 版本

4.0.0-alpha.0

### 描述一下你遇到的问题。

van-config-provider 设置theme默认为dark不生效，只有切换的时候才有效

### 重现步骤

进入复现查看demo

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
已在 4.0.0-alpha.1 版本修复
