### ISSUE TITLE
Sku组件的none_sku无效

### ISSUE THREAD

**Issue by uax** [youzan/vant#1040]
参数中设置了none_sku: true,
但是点击购买，还是提示要选择规格。
![image](https://user-images.githubusercontent.com/10324413/39903171-6d0e88d6-5504-11e8-9393-131b692414d3.png)

**Comment by w91** [comment]
@uax 可能是你数据结构的问题，你这边再和样例数据比较下？或者提供个jsfiddle的demo看看
