### ISSUE TITLE
[Bug Report] From表单组件配合多选框中的输入框（用v-if控制显隐），rules校验会多次记录

### ISSUE THREAD

**Issue by 316374157** [youzan/vant#10411]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/form

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

第一次表单validate调用结果
![1](https://user-images.githubusercontent.com/46001074/158984005-ee64d794-c19f-4218-9b61-9ef2ef8f40d0.png)
通过v-if控制显隐一次后表单validate调用结果
![2](https://user-images.githubusercontent.com/46001074/158984281-1781dd0e-5347-4e0a-9d48-021ba40a98b2.png)
通过v-if控制显隐两次后表单validate调用结果
![image](https://user-images.githubusercontent.com/46001074/158984406-a94fdd1b-4b2b-47c9-9c0c-2fbfcbb2c230.png)

### 重现步骤

大概代码
![image](https://user-images.githubusercontent.com/46001074/158985136-74c09ee7-ab01-472b-a18d-35f31e1d8012.png)

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接

https://codesandbox.io/s/vant-3-issue-template-8fuq5o

**Comment by Iongtao** [comment]
我也遇到了这样的问题 我会尝试提供工程项目

**Comment by Iongtao** [comment]
> 请提供 codesandbox 复现链接
> 
> https://codesandbox.io/s/vant-3-issue-template-8fuq5o

可能与浏览器兼容性有关。我发现此问题存在安卓钉钉浏览器中，ios钉钉和web浏览器无此问题。
写的测试工程无法复现

**Comment by csorz** [comment]
@Iongtao 请问你是如何解决的，我也遇到这个问题

**Comment by csorz** [comment]
在钉钉中复现，android 11、12，荣耀 60

**Comment by zhuanglee** [comment]
我在鸿蒙 2.0 和 鸿蒙 3.0 遇到了相同的问题（  vant 3.6.5 版本），请问如何解决？
