### ISSUE TITLE
Documentation: attributes.json file to please include "options" for all attributes

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10420]
### What problem does this feature solve?

Hi there

I kindly request that the attributes.json file should please include an "options" key which will contain all options per attribute. Currently there are 1 or 2 attributes that have "options"

For example, for the van-button, the type attribute, the "options" key will have ['primary', 'success', 'default', 'danger', 'warning']

Thank you in advance.

### What does the proposed API look like?

For example, for the van-button, the type attribute, the "options" key will have ['primary', 'success', 'default', 'danger', 'warning']

**Comment by nemo-shen** [comment]
duplicate issues
