### ISSUE TITLE
Documentation: tags.json file to please include "description" with details of the tag for all tags

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10421]
### What problem does this feature solve?

Currently the tags.json file does not include the description of what that component is. I kindly request that this feature is added.
This helps in the understanding of the tags and what they do for developers using this library.

Thanks in advance.

### What does the proposed API look like?

Including the "description" key with the details of the tag functionality.

**Comment by nemo-shen** [comment]
duplicate issues
