### ISSUE TITLE
Documentation: web-types.json file to please include tag "description" key, events "arguements" keys with details

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10422]
### What problem does this feature solve?

This improves the documentation of the api for developers using the json files to build tools.

I kindly request the inclusion of the "description" key with details for each tag in the web-types.json file. This could also include the "docs-url" key which could point to the reference location of the tag content on your website.

The "arguements" key for the "events" per tag could also help, These could be the arguments passed to that event.

Thanks in advance.

### What does the proposed API look like?

"description": 'what this component does'

events.arguements: ["name":'doThis', "arguements":["name":'xxx', "type":"bbb"]]

**Comment by chenjiahan** [comment]
We have already provide descriptions for props:

![image](https://user-images.githubusercontent.com/7237365/161408365-a4bc573c-fbfa-4086-9405-a5d8204150f8.png)

And the description for component is not really necessary, the component names are very clear.

Also we have no plan to provide the "arguments" key for the "events" yet, maybe you can make a pull request to help us complete this job ^_^

**Comment by nemo-shen** [comment]
@chenjiahan 
Well, I have a different opinion, I think it is necessary to have a component with a description, cause it helps developers who are new to it to understand more quickly what the component does, without having to open the browser specifically. sometimes, switching between as few windows as possible can improve productivity.🤔

**Comment by chenjiahan** [comment]
> I think it is necessary to have a component with a description.

For component names, I think there needs to be a general way of hinting, try not to be limited to a specific IDE.

Maybe JSDoc is a better alternative.

**Comment by chenjiahan** [comment]
Added event arguments in v3.4.8.
