### ISSUE TITLE
[Bug Report] vant 3 的文档中 Grid组件的reverse 属性被描述为是 grid item的属性

### ISSUE THREAD

**Issue by Snoopy-Li** [youzan/vant#10435]
### 重现链接

https://vant-contrib.gitee.io/vant/?msclkid=2e4c40b1acaa11ecaab61f5511e3dc8d#/zh-CN/grid

### Vant 版本

3

### 描述一下你遇到的问题。

vant 3 的文档中 Grid组件的reverse 属性被描述为是 grid item的属性

### 重现步骤

打开中文官方文档
查看 grid 的属性
 Grid组件的reverse 属性被描述为是 grid item的属性

期望：reverse应该是Grid的属性，不应该写在grid item的属性中

**Comment by chenjiahan** [comment]
感谢反馈，已修正
