### ISSUE TITLE
ImagePreview 图片预览组件点击关闭不了bug

### ISSUE THREAD

**Issue by search-inner** [youzan/vant#1043]
ImagePreview(['https://img.yzcdn.cn/2.jpg']); 
当图片地址只有一个时，点击图片不会关闭，多张时关闭正常

**Comment by chenjiahan** [comment]
下个版本修复此问题

**Comment by chenjiahan** [comment]
已在 1.1.3 版本修复

**Comment by lengyehan** [comment]
并没有完全修复，在微信公众号pc和ios端打开 点击图片还是未关闭，开发者工具里面正常

**Comment by wwzill0928** [comment]
ios 10 点击预览图片后不能关闭。 ios12正常

**Comment by MrWooz** [comment]
ios11 微信6.7.4 不能关闭预览图片，麻烦修复bug

**Comment by Iceseas** [comment]
版本 2.12.54  图片为一张时点击图片外及图片 均无法关闭  麻烦修复bug。
```HTML
<van-image-preview
	v-model="avatarPreview.visible" 
        :images="avatarPreview.url">
</van-image-preview>
```
