### ISSUE TITLE
[Bug Report] TreeSelect 在Andriod 9版本下activeIndex有问题

### ISSUE THREAD

**Issue by chuan920826** [youzan/vant#10433]
### 重现链接

无

### Vant 版本

3.4.6

### 描述一下你遇到的问题。

TreeSelect 在安卓9下activeIndex会出现问题

### 重现步骤

1、先给treeselect 赋值 `[{text:'123',children:['222','333']},{text:"222",children:['444','5555']}]`,并让activeIndex=0；
2、然后给treeselect复制`[{text:'QQQ',children:['TTT','DDD']},{text:"YYY",children:['BBB','KKK']}]`，并让activeIndex=0；
3、最后再给treeselect复制`[{text:'123',children:['222','333']},{text:"222",children:['444','5555']}]`,点击**text=222**这一栏时，即activeIndex=1了，就会发现右边渲染不出来

### 设备/浏览器

andriod 9

**Comment by nemo-shen** [comment]
看下 [TreeSelectItem 数据结构](https://vant-contrib.gitee.io/vant/#/zh-CN/tree-select#treeselectitem-shu-ju-jie-gou)

**Comment by chuan920826** [comment]
``> 看下 [TreeSelectItem 数据结构](https://vant-contrib.gitee.io/vant/#/zh-CN/tree-select#treeselectitem-shu-ju-jie-gou)

我写在这的数据它的结构确实有问题，只是我实际的数据在安卓9和安卓10上的表现不一致，在安卓10上是符合我的预期的。
我看了在安卓9上的问题，
` <template #content>
      <template v-for="(item, index) in vinList" :key="index">
        <template v-if="activeIndex === index">
          <span>{{ item.children.map((x) => x.vin).join("\n") }}</span>
          
        </template>
      </template>
    </template>`
注释这段，会造成左边的text的activeIndex（main-active-index）自增长。
具体表现为：
1、先赋初始值---没问题（如，vinlist是2条数据，activeindex也应该只有0和1）
2、重新赋值时，就会出现自增长（vinlist重新赋值2条数据，activeindex就会变成1，2，但是页面显示text还是2条数据--这个text的2条数据符合我的预期）。就相当于activeindex为1时才是vinlist的第[0]条数据，这就造成了页面和数据严重错位
3、但是不用注释这段，如果只有一个标签，就是正常的
4、注释这段在安卓10上符合我的预期
