### ISSUE TITLE
[Bug Report] TreeSelect 在Andriod 9版本下ActiveIndex的问题#10433

### ISSUE THREAD

**Issue by chuan920826** [youzan/vant#10449]
### 重现链接

无

### Vant 版本

3.2.3

### 描述一下你遇到的问题。

请注意看activeIndex
https://user-images.githubusercontent.com/13793160/160584619-cc2d016d-507f-4923-a7fe-5b3c4ded6761.mp4

非要看视频吗？
这个跟数据没关系了吧
![2](https://user-images.githubusercontent.com/13793160/160585709-852029c8-813d-4d05-abe7-7aa0ecf3bbdf.png)
![1](https://user-images.githubusercontent.com/13793160/160585726-e78bbfcb-b2b8-4aa9-b8ea-4563433a5593.png)
数据没问题吧？

### 重现步骤

看视频

### 设备/浏览器

andriod 9

**Comment by chenjiahan** [comment]
没有 codesandbox 复现链接，无法复现该问题。
