### ISSUE TITLE
Uploader 文件上传中的preview-options

### ISSUE THREAD

**Issue by LinkerM** [youzan/vant#10443]
### 这个功能解决了什么问题？

Uploader 文件上传中的preview-options这个功能是重新传一个list过去。预览图就是预览的新list的数据吗？目前我传list进去只是黑屏没有图片显示。const images = [
      'https://cdn.jsdelivr.net/npm/@vant/assets/apple-1.jpeg',
      'https://cdn.jsdelivr.net/npm/@vant/assets/apple-2.jpeg',
    ];

### 你期望的 API 是什么样子的？

preview-options:[
      'https://cdn.jsdelivr.net/npm/@vant/assets/apple-1.jpeg',
      'https://cdn.jsdelivr.net/npm/@vant/assets/apple-2.jpeg',
    ];

**Comment by JakeLaoyu** [comment]
preview-options 是一个 object，不是 array

```
:preview-options="{
        images: [
          'https://cdn.jsdelivr.net/npm/@vant/assets/apple-1.jpeg',
          'https://cdn.jsdelivr.net/npm/@vant/assets/apple-2.jpeg',
        ],
      }"
```

**Comment by LinkerM** [comment]
已解决谢谢
