### ISSUE TITLE
[Feature Request] Calendar组件在可多选/可选择日期区间模式下的样式优化

### ISSUE THREAD

**Issue by 34205037** [youzan/vant#10440]
### 这个功能解决了什么问题？

日期选择具有圆角样式，当多选或区间选择的情况下，上下相邻的选择紧密贴合在一起，此时带有圆角有点不美观。
![image](https://user-images.githubusercontent.com/44354736/160275262-de24b732-d3c4-4284-9694-0ea18df38a1c.png)
![image](https://user-images.githubusercontent.com/44354736/160275289-9db263d7-8de7-40de-a6df-455b6ced0179.png)

### 你期望的 API 是什么样子的？

两个可能的调整：
加一个margin
![image](https://user-images.githubusercontent.com/44354736/160275406-63da4a3d-2e81-4e88-acf6-a8d58dc5709e.png)
去除圆角
![image](https://user-images.githubusercontent.com/44354736/160275553-78a8a94d-c120-4061-b2b0-9c2fb335d85f.png)

个人感觉，这样看起来是不是更好一点？也或许官方可以有更好的方案。
当然，这在外部可以简单的通过css强行覆盖，只是这种方式显得不那么干净。

**Comment by nemo-shen** [comment]
嗯，的确是一个样式优化的点
参考了 `美团` 和 `携程` 都有类似的 `margin`

![meituan](https://user-images.githubusercontent.com/13480805/160275673-6ffe6475-718f-4569-8296-b3e38ff0e00d.jpeg)
![xiecheng](https://user-images.githubusercontent.com/13480805/160275676-eead1fd3-a023-443c-9a0d-8a0100bcafac.jpeg)
