### ISSUE TITLE
[Bug Report] 2.x TabBar 的匹配问题

### ISSUE THREAD

**Issue by Hill-98** [youzan/vant#10446]
### 重现链接

https://github.com/Hill-98/vant-tabbar-issue

### Vant 版本

2.12.45

### 描述一下你遇到的问题。

2.x Tabbar 组件目前的匹配方式无法匹配 `/` 及其子路径，这源于 VueRouter 的内部行为。详见 vuejs/vue-router#3734

PS: VueRouter 4.x 没这个问题

### 重现步骤

1. 运行重现链接
2. 跳转到 / 或 /children
3. 查看 / 的 TabBarItem 是否高亮

**Comment by Hill-98** [comment]
那我如果提交 PR 会被合并吗？

**Comment by chenjiahan** [comment]
会的，我看下
