### ISSUE TITLE
toast的宽度css变量不能被修改

### ISSUE THREAD

**Issue by xiaoxiaohuayu** [youzan/vant#10451]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-8niech?file=/src/main.js

### Vant 版本

3.0.0

### 描述一下你遇到的问题。

不是说
`
/* 添加这段样式后，Primary Button 会变成红色 */
:root {
  --van-button-primary-background-color: red;
  --van-toast-default-width: 8rem !important;
}
`
这样就可以修改了吗

### 重现步骤

就直接设置--van-toast-default-width 的宽度

**Comment by Alanscut** [comment]
升级vant版本就可以了
