### ISSUE TITLE
[Bug Report] 手机真机vant中popup搭配indexbar无法固定

### ISSUE THREAD

**Issue by Soumns777** [youzan/vant#10452]
### 重现链接

https://b04hd3.csb.app/

### Vant 版本

2.12.36

### 描述一下你遇到的问题。

在手机上真机测试时,搭配vant的popup组件使用indexbar组件时,滑动时右侧的sidebar会跟着滑动，indexbar添加了sticky-offset-top属性后也无法解决问题。

### 重现步骤

滑动popup

### 设备/浏览器

iphone8p

**Comment by chenjiahan** [comment]
用安卓真机打开复现链接看了下，没复现『右侧的sidebar会跟着滑动』这个现象哈

**Comment by chenjiahan** [comment]
用安卓真机打开复现链接看了下，没复现『右侧的sidebar会跟着滑动』这个现象哈

**Comment by Soumns777** [comment]
你好，我是用的iphone11和iphone8p。结果都复现了，这个是安卓和ios的兼容性问题嘛？







发自我的iPhone


------------------ 原始邮件 ------------------
发件人: neverland ***@***.***&gt;
发送时间: 2022年4月4日 09:26
收件人: youzan/vant ***@***.***&gt;
抄送: 凤梨杨枝甘露 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[youzan/vant] [Bug Report] 手机真机vant中popup搭配indexbar无法固定 (Issue #10452)





 
用安卓真机打开复现链接看了下，没复现『右侧的sidebar会跟着滑动』这个现象哈

**Comment by chenjiahan** [comment]
不好说哦，你可以覆盖一些自定义的样式试试，看看能否通过调整布局方式来避免这个问题
