### ISSUE TITLE
[Feature Request] please wrap all vant elements with async components

### ISSUE THREAD

**Issue by ssibrahimbas** [youzan/vant#10450]
### What problem does this feature solve?

I'm writing a mobile app with 'vue + vant + vite'. I made a very performance application by taking advantage of the subtleties of vue, vue-router and vi. But when I debug my app, the vant items are loaded unnecessarily. Instead, dynamic loading can be introduced. It's pretty simple!

All you have to do is create a module called promise in the main directory and enable us to do the optional asynchronous installation with this module.

What do I mean?

```javascript
import VantAsync from "vant/async";

app.use(VantAsync);
```

With the above code I should be able to load all the vant items asynchronously!

Below is an appendix on how to do this.

### fix 

When I examine the ```node_modules/vant/index.js``` file, I see this:

```javascript

import blabla from "./blabla"
import blabla2 from "./blabla2"

function install(app) {
const components = [
     blabla,
     blabla2
    ]

  components.forEach((item) => {
    if (item.install) {
      app.use(item);
    } else if (item.name) {
      app.component(item.name, item);
    }
  });
}

```

but this is not efficient. Instead, a solution like this is much nicer!

```javascript

import {defineAsyncComponent} from "vue"

const install = (app) => {
     [
     {
          name: "blabla",
          source: "./blabla"
      },
      {
          name: "blabla2",
          source: "./blabla2"
      }
     ].forEach(comp => {
         app.component('vant-' + comp.name, defineAsyncComponent(() => import(comp.source)))
      })
}

```

I think it's pretty effective! What do you think?

### What does the proposed API look like?

// main.js
```javascript
import {VantAsync} from "vant";
import {createApp} from "vue"; 
import App from "./app.vue";

const app = createApp(App);
app.use(VantAsync); // this should not install all components. Instead it should load components as I use them.
app.mount("#app")
```

// app.vue

```vue
<script setup>
const greeting = () => {
   alert("Hello world")
}
</script>

<template>
<van-button type="primary" @click="greeting">Say Hello!</van-button>
</template>
```

I haven't specifically imported the button yet. But since I use VantAsync, it should load automatically when I use it!

**Comment by chenjiahan** [comment]
1. If you turn all base components into async components, the user experience of first screen rendering will be bad, user needs to wait to load async chunks.

2. You should only import the components that are used, and Vite will remove unused components through tree shaking.

```js
// Good
import { Button } from 'vant';

// Bad
import Vant from 'vant';
```

3. Developers should define async chunks according to their own usage scenarios, and Vant has no plans to provide entry files for full async components.
