### ISSUE TITLE
[Feature Request] Access to the complete source code that is on live demos on documentation.

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10453]
### What problem does this feature solve?

Hi there, thanks again for this lib

I am currently learning this library, it would however help to get access to the code examples that run live on your documentation website, these seem to be more concise and extended compared to the documentation notes.

Is it possible to access the documentation live demo source code please for enhanced learning purposes?

I am trying to reproduce the live demos with what I learn and at times my results dont work or dont look the same, with comparing with your documentation live demo source it will be easier to understand and find issues on my side and help with all the "globe" needed moments.

I thank you.

### What does the proposed API look like?

Documentation Live Demo Source Code.

**Comment by chenjiahan** [comment]
Every component folder contains a `demo` folder, you can find the source code of demo here.

For example, the demo of button is at https://github.com/youzan/vant/tree/dev/packages/vant/src/button/demo
