### ISSUE TITLE
Field组件插入模板icon和input。本地无问题，线上有问题

### ISSUE THREAD

**Issue by zbk6** [youzan/vant#10457]
### 重现链接

无法重现链接

### Vant 版本

3.2.8

### 描述一下你遇到的问题。

<Field
							v-model="fromData"
							:formatter="formatter"
							name="profit"
							type="number"
							label="name"
							maxlength="8"
							placeholder="（）"
							label-width="70"
						>
							<template #input>
								<Icon
									class-prefix="myIcon"
									:name="isAddOrMinus ? 'jiahao1' : 'jianhao'"
									:color="themeColors.color"
									@click="isAddOrMinus = !isAddOrMinus"
									size="16"
								/>
								<input
									style="border: none; background: transparent"
									type="text"
									:value="fromData.profit"
									@input="profitChange"
								/>
							</template>
						</Field>

### 重现步骤

本地没有问题，发布至线上出现问题。 点击input框。会撑开icon。导致左侧标题缩进。
项目环境为小程序内嵌的h5

### 设备/浏览器

手机端

**Comment by chenjiahan** [comment]
无法重现的问题我们也没法排查，建议你先自己调试下
