### ISSUE TITLE
[Bug Report] Action Sheet 和 Tab 组件在特定情况下会出现遮罩层级错误

### ISSUE THREAD

**Issue by mogody** [youzan/vant#10466]
### 重现链接

https://codesandbox.io/s/vue2-vant2-forked-ci4chn?file=/src/App.vue

### Vant 版本

2.12.46

### 描述一下你遇到的问题。

在同时使用 Action-Sheet 和 Tab 组件，Tab Item 的内容会出现滚动的时候，滚动 tab item 的内容，再打开 action sheet，action sheet 的 overlay 遮罩的层级会低于 tab，导致 tab 也会被高亮

<img width="565" alt="image" src="https://user-images.githubusercontent.com/10496478/161472677-91129a0f-8258-4bc0-9f15-55aae6227ce5.png">

### 重现步骤

1. 点击“打开”
2. 查看tab

### 设备/浏览器

随便

**Comment by mogody** [comment]
测试发现，只有把 action sheet 放在 sticky 中才会出现

**Comment by chenjiahan** [comment]
这个和 z-index 的生效规则有关，组件本身是保证了 z-index 大小的正确性的。

在 ActionSheet 上设置 `get-container="body"` 即可解决。
