### ISSUE TITLE
enterkeyhint for vue-field

### ISSUE THREAD

**Issue by pencilcheck** [youzan/vant#10467]
### 这个功能解决了什么问题？

改keyboard bottom right button 顯示以及功能
https://www.geeksforgeeks.org/html-enterkeyhint-attribute/#:~:text=The%20enterkeyhint%20attribute%20is%20an,it%20more%20helpful%20for%20users.

### 你期望的 API 是什么样子的？

```
<van-field enterkeyhint="values" />
```

**Comment by chenjiahan** [comment]
enterkeyhint 属性的仅在 Chrome >= 77 和 Safari >= 13.1 支持，不符合 Vant 的兼容性要求，因此我们不计划加入到官方的 API 中。

**Comment by pencilcheck** [comment]
> enterkeyhint 属性仅在 Chrome >= 77 和 Safari >= 13.1 支持，不符合 Vant 的兼容性要求，因此我们不计划加入到官方的 API 中。

如果vant不支持，寫的軟件需要，哪麼要怎麼使用？vant field 沒有ref可以直接修改props

**Comment by chenjiahan** [comment]
后续会支持这个 prop，并写明存在兼容性问题
