### ISSUE TITLE
[Feature Request] Please consider adding loading properties for Dialog: Cancel & Confirm Buttons

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10463]
### What problem does this feature solve?

This will make it easier to turn off the loading indicators for both the cancel and confirm buttons.

https://youzan.github.io/vant/#/en-US/dialog

For example: 

cancelButtonLoading / Boolean /False
confirmButtonText / Boolean / False

One can just set these to true/false at runtime depending on need.

### What does the proposed API look like?

cancelButtonLoading / Boolean /False
confirmButtonText / Boolean / False

**Comment by chenjiahan** [comment]
We recommend to using the `beforeClose` prop to control the loading status of confirm and cancel button.

```js
const beforeClose = (action) =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve(action === 'confirm');
    }, 1000);
  });

Dialog.confirm({
  title: 'Title',
  message: 'Content',
  beforeClose,
});
```
