### ISSUE TITLE
[Feature Request] nuxt引入vant不能在服务端渲染数据

### ISSUE THREAD

**Issue by LLLiuRX** [youzan/vant#10476]
### 这个功能解决了什么问题？

版本2.12.43

<img width="645" alt="image" src="https://user-images.githubusercontent.com/44798850/162149496-983b0c15-0f83-42a0-8714-dd2baa2a6aaa.png">

而数据并不能在服务端渲染出来 看到的html就是这个样子的
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/44798850/162149787-f7188ef8-34bb-4278-aa0c-94e00dccbafb.png">

### 你期望的 API 是什么样子的？

想问下有什么办法可以解决吗 期望在服务端渲染整个html页面

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5278
