### ISSUE TITLE
[Bug Report] pnpm i 运行报错

### ISSUE THREAD

**Issue by EvinqWang** [youzan/vant#10486]
### 重现链接

大萨达

### Vant Cli 版本

最新的

### 描述一下你遇到的问题。

│ src/compiler/compile-script.ts(2,19): error TS7016: Could not find a declaration file for module '@babel/core'. '/home/wlq/vant/node_modules/.pnpm/@babel+core@7.16.0/node_modules/@babel/c
│   If the '@babel/core' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/babel__core'
│  ELIFECYCLE  Command failed with exit code 2.

### 重现步骤

pnpm i 
in file packages/vant-cli/src/compiler/compile-script.ts
import babel from '@babel/core';

**Comment by JakeLaoyu** [comment]
pnpm 使用 最新稳定版
```shell
pnpm add -g pnpm
```

**Comment by JakeLaoyu** [comment]
你可能用了  7.X RC
