### ISSUE TITLE
field设置宽度无效

### ISSUE THREAD

**Issue by oyeaono** [youzan/vant#10485]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-ffkp9i?file=/src/App.vue

### Vant 版本

2.11.0

### 描述一下你遇到的问题。

设置最小宽度无效，默认有一个最小宽度，怎么能自定义最小宽度

### 重现步骤

无法设置最小宽度

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
Field 组件的默认样式中没有设置最小宽度的，你可以通过 min-width 属性来设置。

**Comment by oyeaono** [comment]
> Field 组件的默认样式中没有设置最小宽度的，你可以通过 min-width 属性来设置。

field 组件有默认的min-width: 0，设置了还是有个默认宽度 并不能根据内容自适应

**Comment by oyeaono** [comment]
> Field 组件的默认样式中没有设置最小宽度的，你可以通过 min-width 属性来设置。

问的有问题，是field有个默认的宽度，不能根据内容自适应宽度，设置了max-content无效

**Comment by oyeaono** [comment]
> Field 组件的默认样式中没有设置最小宽度的，你可以通过 min-width 属性来设置。

代码中的红色背景宽度应该和内容一样宽，实际大概有150px的宽度

**Comment by chenjiahan** [comment]
我觉得这个不是组件的问题，组件的 CSS 你都能看到的，自己尝试覆盖样式解决就行。

**Comment by oyeaono** [comment]
> 我觉得这个不是组件的问题，组件的 CSS 你都能看到的，自己尝试覆盖样式解决就行。

但是设置了根据内容适应宽度的属性max-content之后，能看到有一个默认的宽度，只能通过写固定宽度或者用js去解决，为什么组件会有默认宽度呢
