### ISSUE TITLE
[Feature Request] van-list: immediate check = default = true

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10482]
### What problem does this feature solve?

Hi there

In the documentation, the immediate-check by default is set to true. This has an effect of updating the binding of v-model:loading automatically, if it gets set to true via code. I am using the v-bind directive and just playing around learning how the library works.

I could be wrong, but perhaps indicating immediate-check updating the v-model should be specified in the docs.

Thanks

### What does the proposed API look like?

See notes.

**Comment by JakeLaoyu** [comment]
To check that the list is scrolled to the bottom and the load event is fired. Most of the time the home page data load is dependent on the load event. But sometimes the user does not rely on the load event to get the home page data.

**Comment by chenjiahan** [comment]
Added some FAQs.
