### ISSUE TITLE
[Bug Report] 当van-radio :name="false" 且选中时rules required: true 校验不通过。

### ISSUE THREAD

**Issue by yaoba18** [youzan/vant#10481]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-43hnfb?file=/src/App.vue

### Vant 版本

4.0.0-alpha.1

### 描述一下你遇到的问题。

当radio组件 :name="false" 被选中时
`:rules="[{ required: true, message: '请选择' }]"`
无法通过

### 重现步骤

选中否，点提交，校验无法通过。

**Comment by JakeLaoyu** [comment]
@chenjiahan  按单测来看这个 value 是 false，required 不通过是符合预期的？

https://github.com/youzan/vant/blob/881f742818f677e1a2d282ddcb2a28e798e4c161/packages/vant/src/form/test/field-type.spec.tsx#L65

**Comment by JakeLaoyu** [comment]
@yaoba18 看起来最好你这边自己转换一下比较合适，否则对于checkbox等场景会有问题

**Comment by chenjiahan** [comment]
> 需要对 radio boolean 场景特殊处理吗

不建议特殊处理哈
