### ISSUE TITLE
[Feature Request] Vant3: Address Edit to default to English locale

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10497]
### What problem does this feature solve?

Hi

The Address edit does not default to English for labels whilts its buttons are in English. Please consider changing the labels to be in line with the rest of the functionality.

<img width="247" alt="AddressEdit" src="https://user-images.githubusercontent.com/5799306/163052877-552fd518-dc15-4f93-9356-fa10959ebcc3.png">

### What does the proposed API look like?

Please see notes..

**Comment by JakeLaoyu** [comment]
Please provide vant version

**Comment by Mashiane** [comment]
3.4.7

**Comment by JakeLaoyu** [comment]
Hi, I can not reproduce, can you provide an example

https://codesandbox.io/s/vant-3-issue-template-8fuq5o

**Comment by chenjiahan** [comment]
Same as https://github.com/youzan/vant/issues/10504
