### ISSUE TITLE
calendar 在安卓版本11和12会出现首次进入页面，打开日历后页面闪屏，重新渲染

### ISSUE THREAD

**Issue by dingxu369** [youzan/vant#10499]
### 重现链接

暂无

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

calendar 在安卓版本11和12会出现首次进入页面，打开日历后页面闪屏，重新渲染，首次打开页面，会出现1-2次

### 重现步骤

唤起日历

### 设备/浏览器

安卓版本11、12

**Comment by chenjiahan** [comment]
使用官网示例能复现么？如果可以复现，请提供一下复现视频
