### ISSUE TITLE
[Feature Request] 希望List组件支持虚拟列表

### ISSUE THREAD

**Issue by Satio-vision** [youzan/vant#10498]
### 这个功能解决了什么问题？

现在已经很多业务需要虚拟列表的支持了，希望List组件能兼容虚拟列表，以对长列表有更好的性能支持

### 你期望的 API 是什么样子的？
<van-list :is-virtual ="true">
</van-list>

**Comment by chenjiahan** [comment]
暂无计划支持哈，建议考虑使用社区里现成的库来实现。
