### ISSUE TITLE
[Bug Report] 2.x uploader组件bug

### ISSUE THREAD

**Issue by kaiGG00** [youzan/vant#10494]
### 重现链接

null

### Vant 版本

2.12.44

### 描述一下你遇到的问题。

在安卓端选择文件退回后再次点击组件没有反应

### 重现步骤

1. 在安卓端点击选择文件
2. 不选择任何文件直接返回
3. 再次点击uploader组件无反应

### 设备/浏览器

安卓10

**Comment by chenjiahan** [comment]
Uploader 使用 HTML 原生的 input type="file" 实现，请验证一下原生标签是否存在同样问题，如果存在，则表明是浏览器兼容问题。

**Comment by kaiGG00** [comment]
> Uploader 使用 HTML 原生的 input type="file" 实现，请验证一下原生标签是否存在同样问题，如果存在，则表明是浏览器兼容问题。
好的，我去看一下是不是安卓端webview的问题
