### ISSUE TITLE
[Feature Request] Vant 3 - Calendar to use System Locale

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10495]
### What problem does this feature solve?

Hi there

The calendar uses another locale in terms of titles etc, is there a setting to make it use system locale titles or this has to be done manually? Please see image.

<img width="292" alt="DateLocale" src="https://user-images.githubusercontent.com/5799306/162960333-ede1bd30-c965-4513-a60f-066751d1ec69.png">

Thanks.

### What does the proposed API look like?

Please see notes..

**Comment by Mashiane** [comment]
Version 3.4.7

**Comment by chenjiahan** [comment]
Same as https://github.com/youzan/vant/issues/10504
