### ISSUE TITLE
[Bug Report] [van rate] 当评分组件有多行并且允许半选时，点击任意一行都会选中最后一行

### ISSUE THREAD

**Issue by Snoopy-Li** [youzan/vant#10493]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-4269qd?file=/src/App.vue

### Vant 版本

3.4.6

### 描述一下你遇到的问题。

当评分组件有多行并且允许半选时，点击任意一行都会选中最后一行

### 重现步骤

1. 打开重现链接，点击第一行

### 设备/浏览器

any

**Comment by chenjiahan** [comment]
会在 3.4.8 版本修复
