### ISSUE TITLE
[Bug Report] [van rate] 评分组件有多行时，通过滑动选择分值只能选择最后一行的分值

### ISSUE THREAD

**Issue by Snoopy-Li** [youzan/vant#10490]
### 重现链接

只能真机复现

### Vant 版本

3.4.6

### 描述一下你遇到的问题。

 评分组件有多行时，通过滑动选择分值只能选择最后一行的分值

### 重现步骤

1. 设置评分组件图标数，使其超过父容器的宽度而换行
2. 在真机上通过手势滑动选择分值
3. 只能选择最后一行的分值

### 设备/浏览器

any

**Comment by JakeLaoyu** [comment]
#10493 重复
