### ISSUE TITLE
[Feature Request] 3.4.7 Coupon Labels Language

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10505]
### What problem does this feature solve?

Hi there, how can I make the coupon labels be in another langauge not the default?

<img width="276" alt="CouponLabels3" src="https://user-images.githubusercontent.com/5799306/163491719-99c2c10e-ef64-4de4-9c41-0b84a17cba5b.png">
<img width="272" alt="CouponLabels2" src="https://user-images.githubusercontent.com/5799306/163491723-c5a96f43-7c10-4ded-8048-3dfd2589917d.png">
<img width="273" alt="CouponLabels" src="https://user-images.githubusercontent.com/5799306/163491728-276b0c78-0528-4c2d-a2d7-8eccc26350d8.png">

### What does the proposed API look like?

See notes, thank you.

**Comment by JakeLaoyu** [comment]
The coupon label is custom

```js
const coupon = {
      available: 1,
      originCondition: 0,
      reason: '',
      value: 150,
      name: 'Coupon name',
      startAt: 1489104000,
      endAt: 1514592000,
      valueDesc: '1.5',
      unitDesc: '$',
      condition: 'No-limit'
    };
```

**Comment by JakeLaoyu** [comment]
Looks like you're building your own library？

**Comment by Mashiane** [comment]
Thanks. Actually I'm trying to reproduce your examples so that I can learn how your library works first and then use it.

But even if I follow your examples at times, from the website or looking at the examples on the download, I can't seem to reproduce the same as what shows as output on the preview screen.

For example the text below 1.5 or 8.8 does not show in your example, I applied the same code as per example and I have it showing on my side. So I'm confused.

Which key value pair in your object addresses the text below 8.8?

Thanks.

**Comment by JakeLaoyu** [comment]
https://github.com/youzan/vant/blob/8dc8c54bca9086028ae2992d7475a07ccd615451/packages/vant/src/coupon-list/demo/index.vue#L38

`condition`

**Comment by chenjiahan** [comment]
Same as https://github.com/youzan/vant/issues/10504
