### ISSUE TITLE
[Feature Request] 3.4.7 Contact Card Default Label Language

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10503]
### What problem does this feature solve?

The Contact Card Labels Language is not English, how can I change the Labels to use English?

<img width="275" alt="ContactCard" src="https://user-images.githubusercontent.com/5799306/163423962-ed18908e-8eb0-46d1-9e59-1e12daf66cb0.png">

On the provided example in the documentation, these are the labels that are shown. How can I reproduce?

![Uploading ContactCardExample.png…]()

### What does the proposed API look like?

See notes..

**Comment by chenjiahan** [comment]
Same as https://github.com/youzan/vant/issues/10504
