### ISSUE TITLE
[Feature Request] 3.4.7 Contact Edit Label Language

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#10504]
### What problem does this feature solve?

The contact edit label language is not English by default, how can I make this to use English. Thank you.

<img width="280" alt="ContactEdit" src="https://user-images.githubusercontent.com/5799306/163431838-98cbea94-b2fb-4791-9db1-e23348d69c13.png">

### What does the proposed API look like?

See notes?

**Comment by alleluya-young** [comment]
https://youzan.github.io/vant/#/en-US/locale
does this isn't work?

**Comment by Mashiane** [comment]
Thanks, I have not used a locale as yet, reason being almost all the components are using a default English language by design. This is rather an issue of being consistent that I'm also highlighting. I hope it makes sense.

As soon as I also am comfortable with my learning curve I will play around with using different locales. Thanks.

**Comment by chenjiahan** [comment]
If you want to display english label, you should use Locale component and use `en-US` language.

**Comment by Mashiane** [comment]
Thank you so much. I have studied the Locale usage code, applied it and everything is in English.
