### ISSUE TITLE
[Uploader组件]afterRead后为什么要塞到绑定的v-model里

### ISSUE THREAD

**Issue by LOADINGG** [youzan/vant#10510]
### 重现链接

看描述里

### Vant 版本

3.4.7

### 描述一下你遇到的问题。

<van-uploader
  v-model="formData.fileList"
  accept="image/png, image/gif, image/jpeg"
  preview-size="60"
  :max-size="4 * 500 * 1024"
  :max-count="9"
  @oversize="onOversize"
  :before-read="beforeRead"
  :after-read="afterRead"
  :disabled="formData.fileList.length > 8"
/>

afterRead() {
//上传图片
}

afterRead方法为什么要把file对象默认塞到formData.fileList数组中，而且file是个文件对象，塞入并没什么用，如果此时在将服务端返回的图片地址塞入formData.fileList.push({url:res.data.data.name})就出现两份一样图片了。

### 重现步骤

无

**Comment by chenjiahan** [comment]
这个是为了默认提供图片预览效果，如果你不需要的话，可以把 v-model 拆分为 `modelValue` prop 和 `update:modelValue` event，然后自行处理相关逻辑。
