### ISSUE TITLE
[Bug Report] 拉取下来dev之后报错

### ISSUE THREAD

**Issue by HZZformGD** [youzan/vant#10517]
### 重现链接

无

### Vant Cli 版本

4.0.1

### 描述一下你遇到的问题。

vant-cli 拉下来安装好依赖 yarn dev 之后报错
![image](https://user-images.githubusercontent.com/26340739/163753685-bd21b6c6-9446-4214-85de-908ffd15be0a.png)
```
TypeError: Cannot read properties of null (reading 'parentNode')
```

### 重现步骤

1.yarn create vant-cli-app
2.yarn 安装依赖
3.yarn dev

**Comment by GRAMMAC1** [comment]
看一下本地的 node 版本，如果版本号小于 14，可以切换到 14 版本后重试一下

**Comment by HZZformGD** [comment]
> 看一下本地的 node 版本，如果版本号小于 14，可以切换到 14 版本后重试一下

14.17.0 我的解决办法是，进入到node_modudes里面，把site里面的desktop 里的 ```main.js``` 里的 ```setTimeout```
![image](https://user-images.githubusercontent.com/26340739/163771976-934d5d5b-6fb1-430c-87cd-00dc92147f5f.png)

另外，求助另一个问题，为什么到node_modules配置自定义元素解析会导致白屏. plugin-vue里面的配置

**Comment by HZZformGD** [comment]
> > 看一下本地的 node 版本，如果版本号小于 14，可以切换到 14 版本后重试一下
> 
> 14.17.0 我的解决办法是，进入到node_modudes里面，把site里面的desktop 里的 `main.js` 里的 `setTimeout`删掉 ![image](https://user-images.githubusercontent.com/26340739/163771976-934d5d5b-6fb1-430c-87cd-00dc92147f5f.png)
> 
> 另外，求助另一个问题，为什么到node_modules配置自定义元素解析会导致白屏. plugin-vue里面的配置

@GRAMMAC1

**Comment by GRAMMAC1** [comment]
> > > 看一下本地的 node 版本，如果版本号小于 14，可以切换到 14 版本后重试一下
> > 
> > 
> > 14.17.0 我的解决办法是，进入到node_modudes里面，把site里面的desktop 里的 `main.js` 里的 `setTimeout`删掉 ![image](https://user-images.githubusercontent.com/26340739/163771976-934d5d5b-6fb1-430c-87cd-00dc92147f5f.png)
> > 另外，求助另一个问题，为什么到node_modules配置自定义元素解析会导致白屏. plugin-vue里面的配置
> 
> @GRAMMAC1

`node@14.17.0` 执行 `yarn dev` 没有复现出来。至于另外一个问题可以单独开 issue 去描述，看起来像是个 feature

**Comment by HZZformGD** [comment]
> > > > 看一下本地的 node 版本，如果版本号小于 14，可以切换到 14 版本后重试一下
> > > 
> > > 
> > > 14.17.0 我的解决办法是，进入到node_modudes里面，把site里面的desktop 里的 `main.js` 里的 `setTimeout`删掉 ![image](https://user-images.githubusercontent.com/26340739/163771976-934d5d5b-6fb1-430c-87cd-00dc92147f5f.png)
> > > 另外，求助另一个问题，为什么到node_modules配置自定义元素解析会导致白屏. plugin-vue里面的配置
> > 
> > 
> > @GRAMMAC1
> 
> `node@14.17.0` 执行 `yarn dev` 没有复现出来。至于另外一个问题可以单独开 issue 去描述，看起来像是个 feature
我试过重头用yarn create vant-cli-app 一个个步骤试下来 依旧有这个问题，很奇怪，你也是用create vant-cli-app 尝试复现吗？
另一个问题开了个issue，就是暴露一些vite的设置出来，不过目前想自己尝试进入node_modules配置，可是配置就报错了。至

**Comment by GRAMMAC1** [comment]
> > > > > 看一下本地的 node 版本，如果版本号小于 14，可以切换到 14 版本后重试一下
> > > > 
> > > > 
> > > > 14.17.0 我的解决办法是，进入到node_modudes里面，把site里面的desktop 里的 `main.js` 里的 `setTimeout`删掉 ![image](https://user-images.githubusercontent.com/26340739/163771976-934d5d5b-6fb1-430c-87cd-00dc92147f5f.png)
> > > > 另外，求助另一个问题，为什么到node_modules配置自定义元素解析会导致白屏. plugin-vue里面的配置
> > > 
> > > 
> > > @GRAMMAC1
> > 
> > 
> > `node@14.17.0` 执行 `yarn dev` 没有复现出来。至于另外一个问题可以单独开 issue 去描述，看起来像是个 feature
> 
> 我试过重头用yarn create vant-cli-app 一个个步骤试下来 依旧有这个问题，很奇怪，你也是用create vant-cli-app 尝试复现吗？ @GRAMMAC1 另一个问题开了个issue，就是暴露一些vite的设置出来，不过目前想自己尝试进入node_modules配置，可是配置就报错了。

`vant.config.mjs` 可以通过 `configureVite` 来修改 `vite` 配置

```js
// vant.config.mjs
export default {
 configureVite(config) {
     // vite config
      return config;
    }
}
```

**Comment by GRAMMAC1** [comment]
https://github.com/youzan/vant/blob/dev/packages/vant-cli/docs/config.md#buildconfigurevite 参考一下 `vant config` 的配置

**Comment by HZZformGD** [comment]
> https://github.com/youzan/vant/blob/dev/packages/vant-cli/docs/config.md#buildconfigurevite 参考一下 `vant config` 的配置

虽然这个很棒，我也看过，但是不知道是不是我的食用方法有丢丢问题，我只要在vant.config.mjs 引用plugin-vue，跑dev的时候就会报错。因为我的需求是想要开发一个webcomponent，需要在site和lib都设置，但是在dev的时候就无法启动了。 
```
vue({
      template: {
        compilerOptions: {
          // 将所有包含短横线的标签作为自定义元素处理
          isCustomElement: tag => tag.includes('-')
        }
      }
    })
```

@GRAMMAC1

**Comment by GRAMMAC1** [comment]
> > https://github.com/youzan/vant/blob/dev/packages/vant-cli/docs/config.md#buildconfigurevite 参考一下 `vant config` 的配置
> 
> 虽然这个很棒，我也看过，但是不知道是不是我的食用方法有丢丢问题，我只要在vant.config.mjs 引用plugin-vue，跑dev的时候就会报错。因为我的需求是想要开发一个webcomponent，需要在site和lib都设置，但是在dev的时候就无法启动了。
> 
> ```
> vue({
>       template: {
>         compilerOptions: {
>           // 将所有包含短横线的标签作为自定义元素处理
>           isCustomElement: tag => tag.includes('-')
>         }
>       }
>     })
> ```
> 
> @GRAMMAC1

1. 通过 `configureVite` 这个配置可以满足你的业务场景，在 `build-site` 和 `build` 的时候都会生效
2. 为什么引入 `@vitejs/plugin-vue` 报错？`vant-cli` 内置了 `@vitejs/plugin-vue`，并且 `configureVite` 传入的 `config` 是已经初始化完的插件。所以需要手动遍历 `config.plugins` 删除内置的 `plugin-vue` 插件，然后自己重新初始化一个。应该可以实现你的需求。

**代码大概长这样**
```js
configureVite(config) {
      const index = config.plugins.findIndex(item => item.name === 'vite:vue')
      if (index > -1) {
        config.plugins.splice(index, 1)
      }

      config.plugins.push(new vuePlugin({
        // vant-cli 内置配置，需要保留
        include: [/\.vue$/, /\.md$/],
        customElement: /\.ce\.vue$/,
      }))

      return config;
    }
```

**Comment by HZZformGD** [comment]
> ```js
> ew vuePlugin({
>         // vant-cli 内置配置，需要保留
>         include: [/\.vue$/, /\.md$/],
>         
> ```

我这就是试试看

**Comment by HZZformGD** [comment]
> > > https://github.com/youzan/vant/blob/dev/packages/vant-cli/docs/config.md#buildconfigurevite 参考一下 `vant config` 的配置
> > 
> > 
> > 虽然这个很棒，我也看过，但是不知道是不是我的食用方法有丢丢问题，我只要在vant.config.mjs 引用plugin-vue，跑dev的时候就会报错。因为我的需求是想要开发一个webcomponent，需要在site和lib都设置，但是在dev的时候就无法启动了。
> > ```
> > vue({
> >       template: {
> >         compilerOptions: {
> >           // 将所有包含短横线的标签作为自定义元素处理
> >           isCustomElement: tag => tag.includes('-')
> >         }
> >       }
> >     })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @GRAMMAC1
> 
> 1. 通过 `configureVite` 这个配置可以满足你的业务场景，在 `build-site` 和 `build` 的时候都会生效
> 2. 为什么引入 `@vitejs/plugin-vue` 报错？`vant-cli` 内置了 `@vitejs/plugin-vue`，并且 `configureVite` 传入的 `config` 是已经初始化完的插件。所以需要手动遍历 `config.plugins` 删除内置的 `plugin-vue` 插件，然后自己重新初始化一个。应该可以实现你的需求。
> 
> **代码大概长这样**
> 
> ```js
> configureVite(config) {
>       const index = config.plugins.findIndex(item => item.name === 'vite:vue')
>       if (index > -1) {
>         config.plugins.splice(index, 1)
>       }
> 
>       config.plugins.push(new vuePlugin({
>         // vant-cli 内置配置，需要保留
>         include: [/\.vue$/, /\.md$/],
>         customElement: /\.ce\.vue$/,
>       }))
> 
>       return config;
>     }
> ```

不对， 我在文件顶部import plugin-vue 的时候就报错了貌似 我也做过这个操作， 删除原本的(同时也保留了原有的.md.vue解析) 但是顶部一引用就报错

**Comment by thiszhong** [comment]
@GRAMMAC1 我在使用 vant cli 想自定义标签（微信的wx-open-launch-weapp）的时候，只要在 vant.config.mjs 里 `import vue from '@vitejs/plugin-vue'` 就会报错：`Uncaught SyntaxError: Invalid left-hand side in assignment`，类似这个：https://segmentfault.com/q/1010000041007589。
复现的话我刚试了下，按 vant cli 的文档创建一个 vue3 的组件库项目，然后在 vant.config.mjs 顶部加个 `import vue from '@vitejs/plugin-vue'` 即可。
所以是不是不可以这样用....
