### ISSUE TITLE
vite运行 tsconfig 位置配置错误

### ISSUE THREAD

**Issue by MildSYang** [youzan/vant#10525]
### 重现链接

没有上传
### Vant 版本

3.2.0

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/11704527/163990115-7c3ed734-8042-4974-8a23-b75db31b872d.png)

直接npm i
只有通过vite运行会死循环，tsconfig获取不到
node_modules/@vant/area-data/tsconfig
../../tsconfig
只能到node_modules这一层

### 重现步骤

直接拉去代码运行

**Comment by chenjiahan** [comment]
已在 1.2.4 版本修复
