### ISSUE TITLE
[Feature Request] Picker 选择器是否可以提供key-value的形式？

### ISSUE THREAD

**Issue by Ryoui** [youzan/vant#10526]
### 这个功能解决了什么问题？

key-value的形式能快速互相找到对应的值。我是一个后端开发，在使用picker时，发现很麻烦，显示的value，但传值是传key

### 你期望的 API 是什么样子的？

类似这种，可以快速获取key或根据key回显value：
`export default {
  data() {
    return {
      columns: [{ key: '18', value: '张三'}, { key: '20', value: '李四' },{ key: '21', value: '王五' }],
    };
  },
  methods: {
    onConfirm(value, key) {
      Toast(`当前值：${value}, 当前key：${key}`);
    }
};`

**Comment by chenjiahan** [comment]
可以使用 4.0 版本的 Picker：https://youzan.github.io/vant/v4/#/zh-CN/picker
