### ISSUE TITLE
[Bug Report] 某些情况下 pull-refresh 无法滚动

### ISSUE THREAD

**Issue by cheese-git** [youzan/vant#10529]
### 重现链接

https://github.com/cheese-git/vant-pull-refresh-pr-example

### Vant 版本

4.0.0-alpha.2

### 描述一下你遇到的问题。

当外层容器为动态高度(如 `flex`), 且 `<van-pull-refresh />` 设置为 `height: 100%` 时，元素内容无法滚动。但如果设置 `min-height: 100%`，又会导致空白区域无法下拉。

### 重现步骤

pnpm serve

### 设备/浏览器

Chrome

**Comment by xhc-code** [comment]
@chenjiahan 你好，这个issue的问题给出的示例就是问题。

@see https://github.com/youzan/vant/issues/8991

我现在在vant4也遇到了，这个问题就是矛盾，首先想在一个固定高度div盒子里展示列表，给div盒子设置一个100%高度，van-pull-refresh组件也设置100%高度？这时下拉刷新是可以了，但是当元素过多，不会出现滚动条。因为van-pull-refresh 组件是监测父dom的滚动条，而下拉刷新滑动是基于van-pull-refresh的内容元素的高度而定。van-pull-refresh下的列表组件，进行上滑的时候，会导致直接触发下滑刷新，无法进行上滑数据。我也不清楚有没有给描述明白。。。
