### ISSUE TITLE
2.10.11版本 validate 传入 name的list返回走reject, 传字符串name 或者不传则正常

### ISSUE THREAD

**Issue by Zhangsc-js** [youzan/vant#10521]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-t8gmyn?file=/src/App.vue:744-745

### Vant 版本

2.10.11

### 描述一下你遇到的问题。

validate 传入name数组  报错

### 重现步骤

详见例子

**Comment by JakeLaoyu** [comment]
demo 没出现报错

**Comment by Zhangsc-js** [comment]
我上面的例子,点下一步按钮他走的是.catch方法即使输入了用户名, 打印了undefined, 红色的校验文字也没出来, 不知道您为啥会出现红色的校验文字,我是windows系统

**Comment by JakeLaoyu** [comment]
@Zhangsc-js 你的意思是如果传入 "username" 校验通过应该走道 then 是吗

**Comment by Zhangsc-js** [comment]
是的, 现在不管有没有输入username 点击下一步都没有任何反应。把validate里面传入的数组替换成字符串或者不传就正常了。 之前用的2.6.0的vantUI是可以的，代码没改过，昨天因为需要用到高版本的功能升级了一下，就出现问题了。

**Comment by JakeLaoyu** [comment]
@Zhangsc-js 可以升级到  2.12.1 版本以上，这个版本才支持  `string[]` 的

https://github.com/youzan/vant/pull/7810
