### ISSUE TITLE
[Bug Report] Field输入框组件在vite版本clearable无法清空

### ISSUE THREAD

**Issue by YunHeWebGit** [youzan/vant#10538]
### 重现链接

https://gitee.com/WebYunKaiFa/issue-tmp.git

### Vant 版本

3.4.8

### 描述一下你遇到的问题。

Field输入框组件: 在vite版本clearable无法清空
Search搜索组件: 在vite版本clearable无法清空
package.json
{
  "dependencies": {
      "axios": "0.26.0",
      "js-web-screen-shot": "1.6.2",
      "vant": "^3.4.8",
      "vue": "3.2.25",
      "vue-router": "4.0.13",
      "vuex": "4.0.2"
    },
  "devDependencies": {
      "@types/node": "16.11.14",
      "@vitejs/plugin-legacy": "^1.8.1",
      "@vitejs/plugin-vue": "2.0.1",
      "less": "4.1.2",
      "sass": "1.45.0",
      "stylus": "0.57.0",
      "typescript": "4.5.5",
      "vite": "^2.7.3",
      "vite-plugin-style-import": "^1.4.0"
    }
}

### 重现步骤

Field组件设置了clearable，绑定了@click-right-icon事件

1.当输入内容后，显示清空按钮
2.当点击清空按钮后，无法清空，且不会触发@click-right-icon绑定事件

### 设备/浏览器

Google Chrome 版本 98.0.4758.102（正式版本） （64 位）

**Comment by YunHeWebGit** [comment]
我怀疑是"vue": "3.2.25",的版本问题，我自己定义组件emit('input', value);也无法清空;

**Comment by Alanscut** [comment]
点击后无法清空，是因为要[桌面端适配](https://youzan.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei)
不会触发@click-right-icon绑定事件，是因为要点击右侧图标时才触发
![image](https://user-images.githubusercontent.com/21104054/164674289-818c45e8-a8c0-4d81-a973-f6523494ac0c.png)

**Comment by chenjiahan** [comment]
https://youzan.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei
