### ISSUE TITLE
vant tabbar Use vue2 version The route cannot be redirected （vant tabbar使用vue2 路由出现问题）  

### ISSUE THREAD

**Issue by lzt-0501** [youzan/vant#10531]
vue2移动端使用Vant插件的时候，tabbar导航栏组件想配置路由，
设置了route属性，界面出现问题，（如果删除route属性，界面能正常跳转，就是刷新后下面的导航栏图标是第一个而不是当前页面的）
下部的导航栏第一个一直是激活状态，而且第一个无法跳转，具体请看截图，希望能得到大家的指导！！卡在这里好久了，找不出问题
（When using the Vant plugin on vue2 mobile, the Tabbar navigation component wanted to configure routing.  
(If route attribute is deleted, the interface can jump normally, that is, after the refresh, the following navigation bar icon is the first one instead of the current page)  
The first one in the lower navigation bar is always active, and the first one cannot jump, please see the screenshot for details, I hope to get your guidance!!  Stuck here for a long time, can't find the problem  ）
![image](https://user-images.githubusercontent.com/76934980/164354710-94c1928e-c8ad-4d82-b62c-10f8418d5cd0.png)
![image](https://user-images.githubusercontent.com/76934980/164354724-662cf647-7b8d-4f90-b522-c0b8ca09fca9.png)
![image](https://user-images.githubusercontent.com/76934980/164354745-99870cb7-279e-440d-9ba5-da48c7f478de.png)
![image](https://user-images.githubusercontent.com/76934980/164354753-de2dacb4-8887-45f7-9b96-57beadebff33.png)
![image](https://user-images.githubusercontent.com/76934980/164354763-f569a7e8-b7ca-432e-ace0-bc36c74919f3.png)
![image](https://user-images.githubusercontent.com/76934980/164354770-f42c4474-4f96-46d7-bf72-ee0a357f3b13.png)

**Comment by lzt-0501** [comment]
help me！

**Comment by chenjiahan** [comment]
请使用 issue 模板创建，并提供复现链接
