### ISSUE TITLE
[Feature Request] List 组件 direction设置为 up, 加载完数据后，能固定在原来位置，不被新增的数据顶下去

### ISSUE THREAD

**Issue by zy017** [youzan/vant#10535]
### 这个功能解决了什么问题？

类似聊天的列表，是需要上拉加载历史数据，加载完数据能保持页面不跳动，应该可以记录滚动位置来实现

### 你期望的 API 是什么样子的？

List 组件 direction设置为 up, 加载完数据后，能固定在原来位置

**Comment by chenjiahan** [comment]
请自行控制滚动位置，组件本身不负责这块

**Comment by stoneylc** [comment]
给你个建议, 下拉第N次前, 记录下list的scrollHeight,  装载完第N次数据到list后, scrollHeight会增加, 
list如果时上滑加载    scrollTop = 现在scrollHeitht - 之前scrollHeight
list如果时下拉加载    scrollTop = 之前scrollHeight
