### ISSUE TITLE
[Feature Request] switch 希望可以设置custom icon或text

### ISSUE THREAD

**Issue by valpa** [youzan/vant#10542]
### 这个功能解决了什么问题？

在现有的swtich里面有loading 属性可以显示loading的图标

类似，希望可以分别设置active-icon/active-text/ inactive-icon/ inactive-text

应用场景举例，在移动端里面设置dark mode switch
比如[这个图片](https://cdn5.vectorstock.com/i/1000x1000/26/29/day-night-mode-switch-ui-button-light-dark-mode-vector-34572629.jpg)

### 你期望的 API 是什么样子的？

```xml
<van-switch active-icon="closed-eye" active-text="Dark">
```

**Comment by valpa** [comment]
@

> 图片打不开哈。

现在可以打开了

**Comment by chenjiahan** [comment]
依然不行。是内网么

**Comment by chenjiahan** [comment]
你直接在 GitHub 输入框上传就行的

**Comment by tappmarket** [comment]
![day-night-mode-switch-ui-button-light-dark-mode-vector-34572629](https://user-images.githubusercontent.com/90168103/164878401-792a5275-6bbc-4363-a868-76b8a9039563.jpg)

**Comment by valpa** [comment]
在vuejs的网页上就有类似的swtich
![image](https://user-images.githubusercontent.com/713110/164960344-74967933-7cd1-4e4d-9240-bdfa41bb7d5f.png)
