### ISSUE TITLE
[Bug Report] vite build 无法通过

### ISSUE THREAD

**Issue by swey01** [youzan/vant#10549]
### Reproduction Link

无

### Vant Version

3.4.8

### Describe the Bug

使用vite build项目的时候报错，ts版本已经升级vant相同或者更高了
[](url
<img width="569" alt="WechatIMG304" src="https://user-images.githubusercontent.com/30410341/165216615-c8634217-7708-41ce-93f3-1f16bcc5fc77.png">
)

### Reproduce Steps

npm run build

**Comment by swey01** [comment]
vue-tsc忘记升级

**Comment by QianTangrong** [comment]
遇到了同样的问题，vue-tsc 需要哪个版本

**Comment by QianTangrong** [comment]
哈喽，能告诉我这个问题怎么解决的吗
