### ISSUE TITLE
Uploader 文件上传 pwa项目在安卓中点击无效果

### ISSUE THREAD

**Issue by zzh948498** [youzan/vant#10551]
### 重现链接

https://youzan.github.io/vant/#/zh-CN/uploader

### Vant 版本

3.4.7

### 描述一下你遇到的问题。

Uploader 文件上传 在安卓pwa中点击无效果
安卓浏览器可以，添加到主屏就不行
普通input也不行
pwa项目  无安卓代码，请问怎么实现

### 重现步骤

1.安装vite-plugin-pwa
2. 安卓手机添加到主屏

### 设备/浏览器

安卓手机

**Comment by chenjiahan** [comment]
普通 input 也不行，那就不是组件库的问题了，建议自行寻找解决方案
