### ISSUE TITLE
vant-field name='test[]'  提交后只有最后一个值

### ISSUE THREAD

**Issue by lovermylover** [youzan/vant#10553]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-3tqqu4?file=/src/App.vue

### Vant 版本

3.2.7

### 描述一下你遇到的问题。

vant-field name='test[]'  提交后只有最后一个值

### 重现步骤

点击按钮

**Comment by Alanscut** [comment]
`name` 属性在这里是作为标识符，应该是具有唯一性的吧？而且submit接收到的 `values` 是 `object` 类型，同名属性的值肯定会被后来的覆盖。

**Comment by lovermylover** [comment]
普通的form表单, 加个中括号是可以提交数组的.
<form>
 <input name="test[]" value ="test1">
 <input name="test[]" value ="test2">
</form>



***@***.***
 
发件人： Alan Wang
发送时间： 2022-04-27 10:36
收件人： youzan/vant
抄送： lovermylover; Author
主题： Re: [youzan/vant] vant-field name='test[]' 提交后只有最后一个值 (Issue #10553)
name 属性在这里是作为标识符，应该是具有唯一性的吧？而且submit接收到的 values 是 object 类型，同名属性的值肯定会被后来的覆盖。

**Comment by chenjiahan** [comment]
Vant 的 name 属性不支持中括号写法，暂时不计划支持。
