### ISSUE TITLE
[Bug Report] vite按需引入样式路径不对

### ISSUE THREAD

**Issue by 981011512** [youzan/vant#10566]
### 重现链接

https://blog.csdn.net/qq_41228789/article/details/124493096?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22124493096%22%2C%22source%22%3A%22qq_41228789%22%7D&ctrtid=439x4

### Vant 版本

3.4.8

### 描述一下你遇到的问题。

具体的我写了一个文章 
https://blog.csdn.net/qq_41228789/article/details/124493096?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22124493096%22%2C%22source%22%3A%22qq_41228789%22%7D&ctrtid=439x4

### 重现步骤

使用官方文档 vite按需引入 无法找到样式文件 文件路径不对

**Comment by chenjiahan** [comment]
vite 插件的问题请到对应的仓库下提 issue 进行反馈。
