### ISSUE TITLE
van-field slot 使用动态数据会导致input预输入状态被清空

### ISSUE THREAD

**Issue by RonLeeLi** [youzan/vant#10563]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-xismrw?file=/src/App.vue

### Vant 版本

3.4.6

### 描述一下你遇到的问题。

van-field slot 使用动态数据会导致input预输入状态被清空

### 重现步骤

van-field slot 使用动态数据会导致input预输入状态被清空

**Comment by weiyuc** [comment]
看了一下源码，定位到是
<img width="485" alt="image" src="https://user-images.githubusercontent.com/16641422/165924544-484a5560-8736-42e8-99d8-8cd4506da96a.png">
这两行导致的。当slot值变化时，会导致无法触发input的onCompositionend事件。
onCompositionStart跟onCompositionend是否可以交给用户自己处理。
