### ISSUE TITLE
[Feature Request] stepper希望支持value为undefined的情况

### ISSUE THREAD

**Issue by loca-spirit** [youzan/vant#10567]
### 这个功能解决了什么问题？

stepper希望支持value为undefined的情况
目前value为undefined的，组件内部居然还有defaultValue，我defaultValue传入undefined，居然还给我设置一个默认值，太可恶了。目前只能copy一份代码，自己重写这个组件了。

### 你期望的 API 是什么样子的？

希望有一个属性可以取消默认值，默认值只是你们内部的起始值，比如是0或者1，它在点击加减号的时候有作用，但是不要直接显示出来。

**Comment by chenjiahan** [comment]
把 allow-empty 属性设置为 true，并传入空字符串就可以了，此时输入框不会展示任何内容。

**Comment by loca-spirit** [comment]
> 把 allow-empty 属性设置为 true，并传入空字符串就可以了，此时输入框不会展示任何内容。

这个是可以，但是还是略有不变，对于数据对象初始化我还需要设置空字符串才能清空stepper上面的值。
感觉undefined也应该可以清空比较合理，举例如下：

比如我定义的模型obj的age字段是number类型，那我合情合理的设置obj.age = 数字或者undefined或者null（一般都是undefined）去清空比较合理。如果设置obj.age = ‘’是不符合typescript的类型校验，听起来也不合理。

希望能支持设置undefined去清空这个字段！
