### ISSUE TITLE
Steps步骤条想要一个居中的功能

### ISSUE THREAD

**Issue by wodexintailuan** [youzan/vant#10575]
### 这个功能解决了什么问题？

类似于element-ui 的 el-steps的align-center <el-steps :active="2" align-center>

### 你期望的 API 是什么样子的？

<van-steps :active="2" align-center>

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/166860488-19b2e52f-90b9-4627-bcfc-2df31a26c103.png)
现在的样式不就是默认居中（排除首尾）吗

**Comment by wodexintailuan** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/43602621/166928712-1a02b6f5-a398-48c2-be82-b7ddbb1ce4b8.png">
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/43602621/166928962-23cf39f4-8480-4f98-8fbd-51a00702b2b1.png">
如果step里是个有高度的块级元素,  想要一个居中的效果,  比如第一个图,加上了align-center, 步骤对应的图标  红色的 就到蓝色的位置

**Comment by wodexintailuan** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/43602621/166934947-797fd1a4-0795-48e4-9f1e-84f2f5c96094.png">
如果能做到首尾也居中,  那当然也是极好的

**Comment by 13725102796** [comment]
建议：
像这种样式问题，不一定要通过官方的API去解决。
在多样化的页面实现上，可以通过` /deep/ `去深度修改样式, 以达到想要的效果。
