### ISSUE TITLE
下拉刷新问题，不知道是不是就是这样的设计？

### ISSUE THREAD

**Issue by 270034480** [youzan/vant#1057]
demo的list组件，下拉刷新后会重载整个页面，页面会闪到空白再出列表，这是问题还是设计就是如此，感觉体验有点奇怪

**Comment by chenjiahan** [comment]
设计如此，Demo 里下拉刷新的时候把列表清空了

**Comment by 270034480** [comment]
好的，用了以后就知道了，下拉其实不是list组件的功能，有个单独的下拉组件，需要配合使用。谢谢！
