### ISSUE TITLE
[Feature Request] DropdownItem 能否新增 beforeOpen事件

### ISSUE THREAD

**Issue by veartoyu** [youzan/vant#10579]
### 这个功能解决了什么问题？

页面有多个DropdownMenu组件，需要动态改变DropdownMenu 的direction 属性。
当DropdownMenu处于页面底部时。需要修改direction 为up，现在在open事件中进行修改direction 时，首次展示无法及时更新到正确的显示位置。

### 你期望的 API 是什么样子的？

能否在DropdownItem  中新增beforeOpen 事件。可以对DropdownMenu 的  direction  进行修改后。再触发组件渲染。

**Comment by Alanscut** [comment]
有尝试过在你那个页面的onMounted函数里面更新一次DropdownMenu 的direction吗

**Comment by veartoyu** [comment]
> 有尝试过在你那个页面的onMounted函数里面更新一次DropdownMenu 的direction吗 或者直接在监听页面滚动的事件里修改direction

现在是基于DropdownItem做了一次封装。然后在封装后的组件内监听页面滚动来做。但是因为同一个页面会存在多个封装后组件的情况。所以不知道性能会不会有影响。

**Comment by Alanscut** [comment]
> > 有尝试过在你那个页面的onMounted函数里面更新一次DropdownMenu 的direction吗 或者直接在监听页面滚动的事件里修改direction
> 
> 现在是基于DropdownItem做了一次封装。然后在封装后的组件内监听页面滚动来做。但是因为同一个页面会存在多个封装后组件的情况。所以不知道性能会不会有影响。

担心性能的话应该可以加一下防抖

**Comment by chenjiahan** [comment]
这种情况推荐使用上面的做法哈，beforeOpen 事件不好加的，因为点击 -> open 是一个同步过程。
