### ISSUE TITLE
popover自定义挂载节点后的关闭问题

### ISSUE THREAD

**Issue by supuwoerc** [youzan/vant#10578]
### 重现链接

https://codesandbox.io/embed/vant-3-issue-template-forked-bk9uxm?fontsize=14&hidenavigation=1&theme=dark

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

popover在使用get-container指定挂载元素之后会导致close-on-click-action失效

### 重现步骤

点击popover中任意action按钮

### 设备/浏览器

all

**Comment by Alanscut** [comment]
应该是挂载到插槽内的元素上会导致close-on-click-action失效，挂载到外部元素上没问题

**Comment by supuwoerc** [comment]
> 应该是挂载到插槽内的元素上会导致close-on-click-action失效，挂载到外部元素上没问题

嗯，我没做这块验证，只是恰巧发现了这个问题~

**Comment by supuwoerc** [comment]
> > > 应该是挂载到插槽内的元素上会导致close-on-click-action失效，挂载到外部元素上没问题
> > 
> > 
> > 嗯，我没做这块验证，只是恰巧发现了这个问题~
> 
> 感觉像是click冒泡导致的，点击action关闭，然而因为挂在button下click事件冒泡上来又触发button，所以又打开了。

是的，应该是这个原因，我手动设置来关闭popover时会发现一次闪烁，应该能确认就是这个原因。

**Comment by chenjiahan** [comment]
我觉得把 Popover 移动到 reference 内是一种错误用法，没必要为了这种情况而禁用事件冒泡。

大部分情况下，最好是让事情冒泡按照默认方式触发，这是符合预期的。
