### ISSUE TITLE
vant-area-data行政编码对应不上

### ISSUE THREAD

**Issue by incess** [youzan/vant#10584]
### 重现链接

http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/index.html

### Vant 版本

3.0.0

### 描述一下你遇到的问题。

vant-area-data行政编码跟国家统计局的行政编码对于不上

### 重现步骤

vant-area-data行政编码跟国家统计局的行政编码对于不上，主要存在海南省儋州市下级的行政编码完全不一样

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/167243886-c996b5a0-f0a9-4834-86d7-ffda2424ee71.png)

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/167245447-c4b742cd-f67a-4b18-a710-0699832a883c.png)
有点奇怪，所有的镇前六位都是460400了

**Comment by chenjiahan** [comment]
这块比较特殊，先不调整了，参见 https://github.com/youzan/vant/pull/10592
