### ISSUE TITLE
[Bug Report] van-date-picker 组件设置 min-date 无效

### ISSUE THREAD

**Issue by zarvin** [youzan/vant#10583]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-4fjssh?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675

### Vant 版本

4.0.0-alpha.3

### 描述一下你遇到的问题。

van-date-picker 组件设置min-date，只有年份生效，设置月份和日期无效，比如min-date设置成2022-03-05，日期选择依旧能选2022-01-01

### 重现步骤

日期能选择小于设置的最小日期

### 设备/浏览器

firfox 100

**Comment by Alanscut** [comment]
这看起来是个bug，为啥关了？
