### ISSUE TITLE
sku商品规格怎么修改默认选中？？

### ISSUE THREAD

**Issue by erenjun** [youzan/vant#1059]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by w91** [comment]
@erenjun 没看懂你的问题，能否具体说下

**Comment by erenjun** [comment]
比如尺码规格里有尺码1，尺码2，尺码3，尺码4的选项，默认是选中尺码1，但我想选中尺码3。这个怎么弄？

**Comment by erenjun** [comment]
比如尺码规格里有尺码1，尺码2，尺码3，尺码4的选项，默认是选中尺码1，但我想选中尺码3。这个怎么弄？

**Comment by erenjun** [comment]
@w91 比如尺码规格里有尺码1，尺码2，尺码3，尺码4的选项，默认是选中尺码1，但我想选中尺码3。这个怎么弄？

**Comment by w91** [comment]
https://jsfiddle.net/dfarLdko/91/  参考下这个，使用initialSku对象可以解决
