### ISSUE TITLE
vant资源包没有Popover

### ISSUE THREAD

**Issue by AUG98** [youzan/vant#10597]
### 重现链接

https://github.com/youzan/vant-weapp.git

### Vant 版本

vant

### 描述一下你遇到的问题。

https://github.com/youzan/vant-weapp.git
该链接clone下来没有Popover组件

### 重现步骤

git clone https://github.com/youzan/vant-weapp.git
查看dist文件夹，不包括Popover

**Comment by chenjiahan** [comment]
小程序版 Vant 里没有提供 popover 组件，Vue 版本有。

**Comment by AUG98** [comment]
> 小程序版 Vant 里没有提供 popover 组件，Vue 版本有。

vue2版本的地址有吗

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/tree/2.x
