### ISSUE TITLE
[Bug Report] Cascader组件在手机端滚动到底部后，再向上滚动出现卡顿情况

### ISSUE THREAD

**Issue by guoxupu** [youzan/vant#10594]
### 重现链接

http://st-eshop.cnhotgb.com/user/profile/create?telephone=17721828828

### Vant 版本

2.0.0-dev.30-8

### 描述一下你遇到的问题。

Cascader组件在手机端滚动到底部后，再向上滚动出现卡顿情况

### 重现步骤

1.点击链接进入注册页面后，选择商户类型
2.打开商户类型弹窗后，滚动列表至底部，再向上滚动出现卡顿情况

### 设备/浏览器

安卓和ios

**Comment by chenjiahan** [comment]
Vant 没有 2.0.0-dev.30-8 版本喔，在提供的链接中没有复现你描述的情况

**Comment by guoxupu** [comment]
请问您是按照我说的步骤进行操作的嘛，我身边的人测都是有问题的

**Comment by guoxupu** [comment]
> Vant 没有 2.0.0-dev.30-8 版本喔，在提供的链接中没有复现你描述的情况


请问您是按照我说的步骤进行操作的嘛，我身边的人测都是有问题的

**Comment by guoxupu** [comment]
> > Vant 没有 2.0.0-dev.30-8 版本喔，在提供的链接中没有复现你描述的情况
> 
> 请问您是按照我说的步骤进行操作的嘛，我身边的人测都是有问题的
![f204c213290dcc8fad5b9c917be029a](https://user-images.githubusercontent.com/48340982/168408581-d25bb3a1-c322-44ae-b5e8-2aaddd316a34.jpg)
滚动到最底部，再向上滚动就出卡顿
