### ISSUE TITLE
执行npm run build命令构建完成之后组件目录下没有js文件

### ISSUE THREAD

**Issue by chensbox** [youzan/vant#10596]
### 重现链接

https://github.com/chensbox/TDesign

### Vant Cli 版本

4.0.1

### 描述一下你遇到的问题。

vue版本 3.2，script setup写法。
执行npm run build命令 构建的es和lib目录下的组件目录只有css文件，没有js文件， 
执行npm run build：site命令构建的文档站点正常。

### 重现步骤

npm run build
查看es和lib目录

**Comment by chenjiahan** [comment]
已发布 vant-cli 4.0.2 版本
