### ISSUE TITLE
van-field特定输入法，输入顺序颠倒

### ISSUE THREAD

**Issue by CheneyChenCode** [youzan/vant#10602]
### 重现链接

https://github.com/CheneyChenCode/Exam/blob/main/Ht-Shool_front/src/views/TestView.vue

### Vant 版本

2.12.44

### 描述一下你遇到的问题。

特定手机输入法，在van-field输入文字，顺序会颠倒
看起来像光标被强制往前跳了
目前测试出有此问题机型
1.vivo：vivo输入法，搜狗输入法
2.小米:搜狗输入法
3.华为：微软输入法

### 重现步骤

![mmexport1652335192432](https://user-images.githubusercontent.com/13464187/168003821-35e7b08b-6895-4c14-956b-405962bda2e6.jpg)

### 设备/浏览器

vivo

**Comment by chenjiahan** [comment]
建议试一下原生 input 标签是否有问题

**Comment by chenjiahan** [comment]
另外我用小米搜狗输入法在官网示例中未复现，建议提供 codesandbox 复现链接
