### ISSUE TITLE
在 js 中使用 Loading

### ISSUE THREAD

**Issue by toplyb** [youzan/vant#10608]
### 这个功能解决了什么问题？

- 如: 当在封装 `http` 请求的时候, 想要在请求前添加 `Loading`, 请求成功后结束 `Loading`, 此时该怎么在 `js/ts` 文件中使用 `Loading` 组件呢

### 你期望的 API 是什么样子的？

- 如: 像 `Element-plus` 一样, 可以使用服务来调用组件
```javascript
import { ElLoading } from 'element-plus'
ElLoading.service(options)
```

**Comment by chenjiahan** [comment]
通常使用 Toast 组件即可。
