### ISSUE TITLE
[Bug Report] Cascader组件在手机端滚动到底部后，再向上滚动出现卡顿情况

### ISSUE THREAD

**Issue by guoxupu** [youzan/vant#10607]
### 重现链接

http://st-eshop.cnhotgb.com/user/profile/create?telephone=17721828828

### Vant 版本

2.0.0-dev.30-8

### 描述一下你遇到的问题。

Cascader组件在手机端滚动到底部后，再向上滚动出现卡顿情况

### 重现步骤

1.点击链接进入注册页面后，选择商户类型
2.打开商户类型弹窗后，滚动列表至底部，再向上滚动出现卡顿情况

PS: 滚动到最底部，再向上滚动就会出现卡顿,参考下方图片
![f204c213290dcc8fad5b9c917be029a](https://user-images.githubusercontent.com/48340982/168408794-5e4c2949-198d-4c0c-afd6-d43ab7c59ec5.jpg)

### 设备/浏览器

安卓和ios

**Comment by chenjiahan** [comment]
看了下这个页面用的不是 Vant，或许是某个 fork 后的版本，不在我们处理的范围内。
