### ISSUE TITLE
再van-popup中使用表单使用van-calendar报错

### ISSUE THREAD

**Issue by fengshansam** [youzan/vant#10614]
### 重现链接

没有链接，问题里面有简易代码

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

  <van-popup
      v-model="isShow"
      :position="position"
      :style="{ height: height }"
      @click-overlay="overlay"
      :transition-appear="true"
    >
      <van-form @submit="onSubmit" ref="form">
        <div v-for="item in config" :key="item.filed">
          <div v-if="tem.type === 'date'">
            <van-field
              v-model="item[item.filed]"
              :name="item.filed"
              :label="item.label"
              :label-align="item.labelAlign || 'left'"
              :placeholder="item.placeholder"
              :input-align="item.inputAlign || 'right'"
              :required="item.required"
              :readonly="item.readonly"
              :colon="item.colon"
              :right-icon="item.rightIcon || ''"
              @click="handlerClick(item)"
            />
            <calendar
              v-if="item.type === 'date' && item.show"
              :isShow="item.show"
              @confirm="
                (e) => {
                  timeSure(e, item)
                }
              "
            ></calendar>

### 重现步骤

 再van-popup中使用vant-form，然后再vant-form包含van-calendar，弹出van-calendar，接着隐藏van-popup，再次打开van-popup，报错Error in event handler for "opened": "TypeError: Cannot use 'in' operator to search for 'scrollTop' in undefined"

**Comment by 13725102796** [comment]
不清楚你怎么实现的，你贴的代码也有问题。calendar组件名称是van-calendar。
``` bash 
<div>
<van-cell @click="showPop = true" />
      <van-popup
        v-model="showPop"
      >
        <van-form  ref="form" >
          <van-cell @click="showCa = true" />
          <van-calendar v-model="showCa" />
        </van-form>
  </van-popup>
</div>
```
我在vant 2.x版本用这个代码
按照： 打开van-popup -> 打开van-calendar -> 关闭 van-popup   -> 打开 van-popup 
这时候显示的是 弹出状态的 van-calendar
可以正常关闭van-calendar，也可以正常关闭 van-popup，关闭后打开依然能正常显示。
