### ISSUE TITLE
[Feature Request] Area组件设置value的时候希望调用下change

### ISSUE THREAD

**Issue by leewithyuan** [youzan/vant#10610]
### 这个功能解决了什么问题？

在`Area`组件设置默认地区码的时候可以显示文字

### 你期望的 API 是什么样子的？

在设置默认地区码的时候调用下`change`方法

**Comment by chenjiahan** [comment]
change 事情目前的设计是仅由用户的行为触发，你可以在设置 value 的时候自行调用一次
