### ISSUE TITLE
[Bug Report] 使用自动导入，dialog样式丢失，必须手动引入样式

### ISSUE THREAD

**Issue by wChenonly** [youzan/vant#10618]
### 重现链接

https://github.com/wChenonly/ceshivant

### Vant 版本

4.0.0-alpha.3

### 描述一下你遇到的问题。

<img width="365" alt="image" src="https://user-images.githubusercontent.com/37658262/169231413-76d14428-62e3-447c-ad4d-dbe7b136a9d8.png">

使用了unplugin-vue-components自动导入，对于函数室组件，无法自动加载样式，必须使用import 'vant/es/Dialog/style/index'

有无更好的解决方案，不想手动引样式。

### 重现步骤

1，下载仓库代码
2，npm install && npm run dev 
3，点击测试dialog按钮，dialog无样式。代码在app.vue

**Comment by chenjiahan** [comment]
Vant 基于统一的目录结构提供了所有组件的样式文件，这个问题建议到 unplugin-vue-components 仓库进行反馈。
