### ISSUE TITLE
图片预览有没有手势缩放？

### ISSUE THREAD

**Issue by erenjun** [youzan/vant#1061]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
没有，暂无计划支持，有需要的话可以提个 PR 帮助我们完善
