### ISSUE TITLE
[Feature Request] 希望vant官方可以考虑增加1个新的功能

### ISSUE THREAD

**Issue by flowerwOw0316** [youzan/vant#10612]
### 这个功能解决了什么问题？

像百度搜索框这样的输入1个文字，在输入框的下方能有1个提示的区域，里面是内容，还有picker组件也希望能增加搜索里面的项的名称，比如在picker里面弄1个搜索框 输入1个字 下面就检索对应的内容

### 你期望的 API 是什么样子的？

```
搜索建议性输入框例如
<van-field-search :data=['a','b','c']></van-field-search>
picker的搜索
```

**Comment by chenjiahan** [comment]
暂无计划支持这两个交互哈，建议自行实现
