### ISSUE TITLE
[Bug Report] Title vue-cli项目无法引入vant组件

### ISSUE THREAD

**Issue by keanuhouse** [youzan/vant#10623]
### Reproduction Link

<template>  <div>  <van-button type="primary">主要按钮</van-button>  <van-button type="success">成功按钮</van-button>  <van-button type="default">默认按钮</van-button>  <van-button type="warning">警告按钮</van-button>  <van-button type="danger">危险按钮</van-button>  </div> </template>  <script> import { Button } from 'vant'  export default {   components: {     'van-button':Button,   } } </script>

### Vant Version

3.4.9

### Describe the Bug

 warning  in ./node_modules/@vant/use/dist/index.esm.js

117:25-33 "export 'reactive' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

118:27-35 "export 'reactive' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

119:17-36 "export 'getCurrentInstance' (imported as 'getCurrentInstance2') was not found in 'vue'

 warning  in ./node_modules/vant/es/loading/Loading.js

12:4-16 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

133:4-11 "export 'provide' was not found in 'vue'

 warning  in ./node_modules/vant/es/button/Button.js

154:13-25 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/vant/es/badge/Badge.js

15:15-30 "export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/vant/es/button/Button.js

161:24-36 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

181:17-21 "export 'ref' (imported as 'ref3') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

182:18-27 "export 'computed' (imported as 'computed2') was not found in 'vue'

 warning  in ./node_modules/vant/es/icon/Icon.js

20:15-30 "export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/vant/es/config-provider/ConfigProvider.js

20:15-30 "export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

241:2-17 "export 'onBeforeUnmount' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

242:2-13 "export 'onActivated' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

249:2-15 "export 'onDeactivated' was not found in 'vue'

 warning  in ./node_modules/vant/es/composables/use-route.js

25:11-29 "export 'getCurrentInstance' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

273:2-11 "export 'onMounted' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

275:4-12 "export 'nextTick' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

279:2-14 "export 'onActivated' (imported as 'onActivated2') was not found in 'vue'

 warning  in ./node_modules/vant/es/loading/Loading.js

27:15-30 "export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/vant/es/config-provider/ConfigProvider.js

28:16-24 "export 'computed' was not found in 'vue'

 warning  in ./node_modules/vant/es/icon/Icon.js

28:17-23 "export 'inject' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

28:18-23 "export 'unref' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

294:20-26 "export 'unref' (imported as 'unref2') was not found in 'vue'

 warning  in ./node_modules/vant/es/icon/Icon.js

29:22-30 "export 'computed' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

301:20-26 "export 'unref' (imported as 'unref2') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

307:2-14 "export 'onUnmounted' (imported as 'onUnmounted2') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

308:2-16 "export 'onDeactivated' (imported as 'onDeactivated2') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

310:6-11 "export 'isRef' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

311:4-9 "export 'watch' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

325:20-26 "export 'unref' (imported as 'unref3') was not found in 'vue'

 warning  in ./node_modules/vant/es/button/Button.js

32:15-30 "export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

339:12-16 "export 'ref' (imported as 'ref4') was not found in 'vue'

 warning  in ./node_modules/vant/es/config-provider/ConfigProvider.js

33:4-11 "export 'provide' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

340:13-17 "export 'ref' (imported as 'ref4') was not found in 'vue'

 warning  in ./node_modules/vant/es/config-provider/ConfigProvider.js

34:17-29 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/vant/es/loading/Loading.js

35:23-31 "export 'computed' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

374:23-27 "export 'ref' (imported as 'ref5') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

375:2-12 "export 'onMounted' (imported as 'onMounted2') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

388:17-21 "export 'ref' (imported as 'ref6') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

404:16-23 "export 'inject' (imported as 'inject2') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

407:4-10 "export 'watch' (imported as 'watch2') was not found in 'vue'

 warning  in ./node_modules/vant/es/icon/Icon.js

40:13-25 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/vant/es/icon/Icon.js

40:33-44 "export 'mergeProps' (imported as '_mergeProps') was not found in 'vue'

 warning  in ./node_modules/vant/es/loading/Loading.js

43:15-27 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

43:16-19 "export 'ref' was not found in 'vue'

 warning  in ./node_modules/vant/es/button/Button.js

49:13-25 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/vant/es/locale/index.js

4:11-14 "export 'ref' was not found in 'vue'

 warning  in ./node_modules/vant/es/icon/Icon.js

50:89-101 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/vant/es/utils/dom.js

52:11-16 "export 'unref' was not found in 'vue'

 warning  in ./node_modules/vant/es/badge/Badge.js

56:16-24 "export 'computed' was not found in 'vue'

 warning  in ./node_modules/vant/es/loading/Loading.js

58:13-25 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

59:17-23 "export 'inject' was not found in 'vue'

 warning  in ./node_modules/vant/es/locale/index.js

5:15-23 "export 'reactive' was not found in 'vue'

 warning  in ./node_modules/vant/es/loading/Loading.js

5:54-66 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

61:21-39 "export 'getCurrentInstance' was not found in 'vue'

 warning  in ./node_modules/vant/es/loading/Loading.js

62:10-22 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/vant/es/button/Button.js

62:15-27 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

64:4-15 "export 'onUnmounted' was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

65:18-26 "export 'computed' was not found in 'vue'

 warning  in ./node_modules/vant/es/button/Button.js

68:15-27 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

73:11-15 "export 'ref' (imported as 'ref2') was not found in 'vue'

 warning  in ./node_modules/vant/es/badge/Badge.js

83:15-27 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/vant/es/button/Button.js

86:15-27 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/@vant/use/dist/index.esm.js

90:12-19 "export 'isVNode' was not found in 'vue'

 warning  in ./node_modules/vant/es/badge/Badge.js

98:15-27 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

 warning  in ./node_modules/vant/es/loading/Loading.js

9:19-31 "export 'createVNode' (imported as '_createVNode') was not found in 'vue'

### Reproduce Steps

安装vant
npm install vant

配置插件
{
  "plugins": [
    [
      "import",
      {
        "libraryName": "vant",
        "libraryDirectory": "es",
        "style": true
      }
    ]
  ]
}

引入组件
<script>
import { Button } from 'vant'

export default {
  components: {
    'van-button':Button,
  }
}
</script>

**Comment by chenjiahan** [comment]
看起来你用的不是 Vue 3，建议检查下 Vue 版本
