### ISSUE TITLE
sku 商品规格层隐藏后不重置所选参数

### ISSUE THREAD

**Issue by jyx12138** [youzan/vant#1062]
:reset-selected-sku-on-hide="resetSelectedSkuOnHide"

将resetSelectedSkuOnHide设为true不好用

**Comment by w91** [comment]
@jyx12138 麻烦提供个能复现问题的jsfiddle看下

**Comment by 492525217** [comment]
问一下这个问题解决了么？我用的vue-admin-template+vant 2.0.7，也是出现这种情况，已经设置了:reset-selected-sku-on-hide=“true”，但是关闭sku并不会重置所选参数，而且我显示sku之后不做任何选中再关闭sku，再打开会默认选中第一个，重置数量的却没有问题

**Comment by chenjiahan** [comment]
@492525217 麻烦提供下复现链接

https://youzan.github.io/vant-issue-generater
