### ISSUE TITLE
[Bug Report] Calendar动态设置max-date后无法渲染新增date

### ISSUE THREAD

**Issue by lh1125** [youzan/vant#10628]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-1hbjhe?file=/src/App.vue

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

场景：日历组件max-date根据其他组件关联设置
问题：当max-date增加时，新增日期无法渲染

### 重现步骤

1.日历组件lazy-render默认为true，先打开显示比较小的max-date日期。
2.关闭后增加max-date再打开日历组件，新增加的日期没有渲染。

![Snipaste_2022-05-23_10-43-03](https://user-images.githubusercontent.com/58623889/169733424-9671699c-76d7-4e5e-8a21-28f96d2e8623.png)

### 设备/浏览器

所有

**Comment by goo-yyh** [comment]
在calendar隐藏状态下修改maxDate，导致getBoundingReact获取到的height为0，使新增的几个month的visible计算错误，没有render出来
