### ISSUE TITLE
网站的CDN链接挂了，无法访问

### ISSUE THREAD

**Issue by huayang0304** [youzan/vant#10627]
### 重现链接

https://cdn.jsdelivr.net/npm/vant@3/lib/index.css

### Vant 版本

3

### 描述一下你遇到的问题。

https://cdn.jsdelivr.net/npm/vant@3/lib/index.css
cdn挂了

### 重现步骤

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vant@3/lib/index.css" />
    
    <script src="https://cdn.jsdelivr.net/npm/vue@3"></script>
    <script src="https://cdn.jsdelivr.net/npm/vant@3/lib/vant.min.js"></script>
挂了cdn 访问不了

**Comment by chenjiahan** [comment]
CDN 是第三方服务哈，参见

![image](https://user-images.githubusercontent.com/7237365/169737751-9595b8f7-80aa-4e57-9257-bfd49d1bc2f1.png)
