### ISSUE TITLE
pnpm i command failed

### ISSUE THREAD

**Issue by mortezasabihi** [youzan/vant#10636]
I ran this command to install dependencies:
```
pnpm i
```
After downloading finished, this error appear on the terminal:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/35567646/170694838-cb026d13-aec8-4e0f-a4fe-487c247cc211.png">

**Comment by chenjiahan** [comment]
pnpm v7 has some breaking changes that cause these issues.

I have fixed it, so we can use pnpm v7 in vant now.
