### ISSUE TITLE
[Bug Report] 删除docsearch的相关引用

### ISSUE THREAD

**Issue by 0muxi0** [youzan/vant#10631]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/

### Vant Cli 版本

2.x

### 描述一下你遇到的问题。

建议2.x版本删除docsearch的相关引用.或者切换最新地址。 目前这两个cdn已失效。最终结果导致打开文档地址时页面阻塞，卡顿时间很长。因此使用2.x的版本的组件库工程打包后的文档网站都会阻塞。
https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js
https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css

### 重现步骤

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/
直接打开你们gittee   文档地址，页面非常慢。控制台能看到docsearch相关的引用不能下载阻塞页面。

**Comment by chenjiahan** [comment]
我这边访问是正常的，可能是网络问题？

**Comment by 0muxi0** [comment]
尝试了用手机网络去打开该cdn资源   也无法打开

**Comment by chenjiahan** [comment]
看起来 jsdelivr 访问出现了问题： https://www.v2ex.com/t/854324，近期要找一下替代的免费 CDN

**Comment by chenjiahan** [comment]
已去除。
