### ISSUE TITLE
[Bug Report] area-data1.3.0版本没有生成编译后的省市区数据，无法import

### ISSUE THREAD

**Issue by xiaofei3062** [youzan/vant#10632]
### 重现链接

https://github.com/youzan/vant/tree/dev/packages/vant-area-data

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

area-data1.3.0版本没有生成编译后的省市区数据，无法import

### 重现步骤

area-data1.3.0版本没有生成编译后的省市区数据，无法import

**Comment by chenjiahan** [comment]
有的哈，只是 esmodule 产物改成了 .mjs 后缀

![image](https://user-images.githubusercontent.com/7237365/170443337-95c3717a-9ec3-4023-96d9-54af3d9b1c06.png)

**Comment by xiaofei3062** [comment]
但是没有Index.js 怎么import {areaList} 呢

**Comment by chenjiahan** [comment]
构建工具（webpack/rollup/vite）会自动识别 package.json 中的 main/module 字段，不存在无法 import 的问题

**Comment by xiaofei3062** [comment]
uni-app里面使用import {areaList} 会报exports is not defined

**Comment by chenjiahan** [comment]
可以参考 https://github.com/dcloudio/uni-app/issues/2412 配置一下

**Comment by xiaofei3062** [comment]
用的不是uni-app的cli方式，hbuilderx自带的那种创建的项目

**Comment by chenjiahan** [comment]
不太清楚，可以参考下对应的文档，或者给他们提 issue。

esm 文件改成 mjs 后缀是为了支持 nuxt 3，这块的支持比较重要，暂时不计划回退文件格式
