### ISSUE TITLE
[Bug Report] Popup组件在oppo,vivo和华为某些手机上显示异常

### ISSUE THREAD

**Issue by xiaosennote** [youzan/vant#10633]
### 重现链接

无

### Vant 版本

3.1.5

### 描述一下你遇到的问题。

在oppo,vivo和华为部分手机上无法正常显示弹出框，其他手机显示正常

点击显示弹出框后，遮罩层正常显示，但弹出框内容无法显示
异常显示图片如下：
![微信图片_20220526180801](https://user-images.githubusercontent.com/20164541/170467183-0433b986-2359-465b-ba48-3eff07ebc4c9.png)
![1653559905(1)](https://user-images.githubusercontent.com/20164541/170467678-cf42c930-5bad-40f2-b5f5-c73517723d85.png)

正常显示应如下：
![image](https://user-images.githubusercontent.com/20164541/170471039-fa526776-e15e-46d2-afc7-266899c96874.png)

### 重现步骤

Popup组件在main.js全局注册

弹出框代码如下：
`<van-popup v-model:show="showRevisitPopup" round position="bottom" teleport="body" :style="{ maxHeight: '75vh' }">`
`<div class="popCon">`
      `<div class="titleBl">`
        `<div class="tit">回访话术</div>`
      `</div>`
其他代码
`</van-popup>`

### 设备/浏览器

oppo，vivo，华为部分手机

**Comment by chenjiahan** [comment]
无法复现这个问题，建议提供一个可复现的 codesandbox 链接
