### ISSUE TITLE
checkbox与cell一起使用时 不支持点击cell时选中 官网示例可重现 或希望实现

### ISSUE THREAD

**Issue by artiely** [youzan/vant#1064]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
计划在下个版本给出方案

**Comment by chenjiahan** [comment]
已在 1.1.12 版本给出解决方案，详见文档示例
