### ISSUE TITLE
[Bug Report] van-field在oppo reno6上显示会多一个小块

### ISSUE THREAD

**Issue by hi-zd** [youzan/vant#10655]
### 重现链接

无

### Vant 版本

2.12.21

### 描述一下你遇到的问题。

van-field在oppo reno6上显示会多一个小块
 `<van-field
          v-model="formData.remark"
          rows="1"
          autosize
          input-align="right"
          label="备注"
          type="textarea"
          readonly
        />`
![image](https://user-images.githubusercontent.com/37653297/171322252-979f0fee-08d3-4119-9896-3b1fda5e9df1.png)

### 重现步骤

type为"textarea"并且readonly时

### 设备/浏览器

oppo reno6

**Comment by chenjiahan** [comment]
<img width="684" alt="截屏2022-06-11 下午7 11 15" src="https://user-images.githubusercontent.com/7237365/173187713-9574736e-cdc1-4d41-9fdf-2ae519ffcf51.png">
