### ISSUE TITLE
uniapp引入vant报错require is not defined

### ISSUE THREAD

**Issue by PrincesFeather** [youzan/vant#10653]
### 重现链接

import Vant from "vant"; Vue.use(Vant)

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

uniapp引入vant后编译报错chunk-vendors.js:34847 Uncaught ReferenceError: require is not define
去掉引入vant的代码后恢复正常
上个礼拜还是好的，昨天来重新下载了一遍依赖，就开始报错

### 重现步骤

npm i vant@latest-v2 -S

main.js里
import Vant from "vant"; 
Vue.use(Vant)

### 设备/浏览器

谷歌浏览器

**Comment by PrincesFeather** [comment]
![Uploading 1653967053(1).jpg…]()

**Comment by chenjiahan** [comment]
可以看看是不是这个问题 https://github.com/youzan/vant/issues/10632

**Comment by PrincesFeather** [comment]
> 可以看看是不是这个问题 #10632

![1654047343(1)](https://user-images.githubusercontent.com/83740034/171310570-2adea388-8c27-4c71-8ddd-fdd5bafad4fb.jpg)
那这应该怎么修改呢，我这package.json里好像不是那样的

**Comment by fatfacecat** [comment]
解决了吗
