### ISSUE TITLE
[Feature Request] 组件库小程序编译模式

### ISSUE THREAD

**Issue by DaDanLiu** [youzan/vant#10657]
### 这个功能解决了什么问题？

用vant-cli 写一个微信小程序组件库，有做这种支持么，做语法树转换

### 你期望的 API 是什么样子的？

怎么做

**Comment by chenjiahan** [comment]
不支持嘞，没有相关计划。

**Comment by DaDanLiu** [comment]
> 不支持嘞，没有相关计划。
那如果在现有vant cli基础上改造 好整不 或者有什么思路推荐嘛

**Comment by DaDanLiu** [comment]
那如果在现有vant cli基础上改造 好整不 或者有什么思路推荐嘛 @chenjiahan

**Comment by chenjiahan** [comment]
不好整，建议看看 taro 之类的多端框架

**Comment by DaDanLiu** [comment]
> 不好整，建议看看 taro 之类的多端框架

谢了 老哥

**Comment by DaDanLiu** [comment]
> 不好整，建议看看 taro 之类的多端框架

老哥 还想问下 vantweapp 的组件预览嵌的iframe 里的js 是怎么从微信小程序端的 转换到web端的，是babel插件么 有开源出来么

**Comment by chenjiahan** [comment]
不是，直接放的 H5 版本

**Comment by DaDanLiu** [comment]
@chenjiahan 把vant-cli那套文档生成的整合到uni-app的框架里可行么，大概想了一下两个包一个放组件库源码，一个是编译后的h5 然后通过iframe 导入，可行不

**Comment by chenjiahan** [comment]
没试过，可以试试

**Comment by DaDanLiu** [comment]
> 不是，直接放的 H5 版本

是有做小程序版本和h5版本的组件映射么，是怎么关联的勒
