### ISSUE TITLE
[Bug Report] Dialog 组件调用，初始化 v-modole:show绑定的boolean值无效

### ISSUE THREAD

**Issue by bluecai520** [youzan/vant#10654]
### 重现链接

https://codesandbox.io/s/zealous-moore-m11jrm?file=/src/App.vue:379-385&resolutionWidth=1024&resolutionHeight=765

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

使用官方https://youzan.github.io/vant/#/zh-CN/dialog#zu-jian-diao-yong-1示例中的组件调用，发现即便初始化绑定了show值为false。弹窗还是默认显示出来，无法通过show属性进行控制。
控制台也出现警告。

### 重现步骤

只复现文档上的示例

### 设备/浏览器

Google Chrome 102.0.5005.63（正式版本） （64 位）

**Comment by chenjiahan** [comment]
Dialog 是函数，不是组件，Dialog.Component 才是组件。

**Comment by Aircity** [comment]
> Dialog 是函数，不是组件，Dialog.Component 才是组件。

我知道引用 Dialog.Component 并引进style后可以用。但是这样难道是理所当然的吗？
一个违反常识性的东西，对使用的用户来说就是bug了。

**Comment by chenjiahan** [comment]
我觉得文档里已经写的很清楚了，另外这块已有优化计划。
