### ISSUE TITLE
[Bug Report] 使用keepAlive时 ActionSheet 动作面板表现异常

### ISSUE THREAD

**Issue by tudou99** [youzan/vant#10656]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-ghb7z7?file=/src/App.vue

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

启用keepalive的时候  从动作面板离开页面，下一次进入的时候 动作面板无法关闭，遮罩和取消也无效。

如果设置了:close-on-popstate="false"，遮罩和取消仍然无效。如果在onActivated里面主动关闭之后，这样遮罩和取消才能正常工作

### 重现步骤

当使用keepalive缓存的时候。
1.从`/`进入`/test`页面，打开动作面板
2.点击动作面板中的返回上一页
3.重新进入test页面的时候。点击遮罩和取消按钮关不掉面板 、主动设置 show.value = false; 也关不掉。

如果设置了:close-on-popstate="false"  在主动设置show.value=false 是可以正常生效的
感觉是这个属性和keepalive有冲突 导致出现响应问题

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
确实是有冲突，因为你调用 $router.back 的时候，ActionSheet 还在关闭的动画过程中，离开页面时没有完全关闭，keep-alive 记录的是关闭前的 DOM 状态。而 ActionSheet 组件实例内部的 show 属性状态已经变为 false 了，因此无法再次关闭。

组件内部目前没有合适的解决方法，可以考虑延迟一下 $router.back() 的时机，加个 setTimeout 500ms 就可以。

**Comment by huxiguo** [comment]
这个问题还是没有解决吗
