### ISSUE TITLE
[Bug Report] webstorm中，所有vant组件的属性都提示错误

### ISSUE THREAD

**Issue by languanghao** [youzan/vant#10652]
### 重现链接

无

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

vant的所有组件的属性，在webstorm中都提示类型错误，element plus就不会，这个算vant的bug还是webstorm的bug?

webstorm 2022.1, 2022.2 都有这个问题

![image](https://user-images.githubusercontent.com/3765379/170901756-e797d087-3e0b-4cf0-bcc3-146afc94792a.png)

![image](https://user-images.githubusercontent.com/3765379/170901772-73bb3bad-8c86-4b3e-bb7d-6f382bde1b3e.png)

### 重现步骤

1. 打卡webstorm
2. 随便写一个vant组件，如`<van-field label="123" />`
3. 看webstorm提示

**Comment by goo-yyh** [comment]
![image](https://user-images.githubusercontent.com/45666106/172132067-2a7c4c04-6171-4aa3-99fc-bdb535e14306.png)

是不是插件没装好还是啥，我也是webstorm好像都没问题

**Comment by languanghao** [comment]
@goo-yyh 需要装什么插件？

**Comment by languanghao** [comment]
@goo-yyh  https://github.com/languanghao/vant-webstorm

代码文件: src/h5/App.vue

![image](https://user-images.githubusercontent.com/3765379/172274851-832f6a1a-ae80-4cdd-94fe-c50eca31eba1.png)

**Comment by goo-yyh** [comment]
> @goo-yyh https://github.com/languanghao/vant-webstorm
> 
> 代码文件: src/h5/App.vue
> 
> ![image](https://user-images.githubusercontent.com/3765379/172274851-832f6a1a-ae80-4cdd-94fe-c50eca31eba1.png)

你试试把项目弄成能跑起来，我试了没有这个问题

**Comment by languanghao** [comment]
@goo-yyh 抱歉，有个配置写错了，现在可以跑起来了

webstorm 版本：
![image](https://user-images.githubusercontent.com/3765379/172287218-dd553aa6-fc1b-41cf-85ae-1a713d7e396d.png)

**Comment by languanghao** [comment]
@chenjiahan 问题并没有解决，webstorm还是会提示类型错误

**Comment by goo-yyh** [comment]
> @chenjiahan 问题并没有解决，webstorm还是会提示类型错误

这应该是webstorm的问题吧

**Comment by languanghao** [comment]
@goo-yyh 可能是webstorm的问题，不过同一个项目里引入的element-plus就不会有这个问题

**Comment by Woshiajuana** [comment]
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/22786166/174997031-6c31e596-1ab1-4cf5-b89c-403a565565ba.png">
我也遇到了这种问题，element-plus 不会出现。webstorm 版本是2022.1.2

**Comment by Woshiajuana** [comment]
> > @goo-yyh https://github.com/languanghao/vant-webstorm
> > 代码文件: src/h5/App.vue
> > ![image](https://user-images.githubusercontent.com/3765379/172274851-832f6a1a-ae80-4cdd-94fe-c50eca31eba1.png)
> 
> 你试试把项目弄成能跑起来，我试了没有这个问题

你好，请问你的webstorm 版本是多少

**Comment by goo-yyh** [comment]
> > > @goo-yyh https://github.com/languanghao/vant-webstorm
> > > 代码文件: src/h5/App.vue
> > > ![image](https://user-images.githubusercontent.com/3765379/172274851-832f6a1a-ae80-4cdd-94fe-c50eca31eba1.png)
> > 
> > 
> > 你试试把项目弄成能跑起来，我试了没有这个问题
> 
> 你好，请问你的webstorm 版本是多少

确实是有问题的

**Comment by languanghao** [comment]
@goo-yyh 所以到底是webstorm的问题还是vant的问题？

**Comment by jayzch** [comment]
我也遇到了

**Comment by KeterVM** [comment]
我也遇到这个情况了:(

升级至以下版本后还是会复现：
webstorm : 2022.1.4
vant: "^3.6.0"

神奇的是用vscode打开一次项目后又奇迹般的好了。。。。

**Comment by chenjiahan** [comment]
我用 MacOS 下的 WebStorm 2022.2.2 未能复现该问题哈。

Vant 也没什么可以针对 WebStorm 进行适配的地方，对于出现这个问题的用户，我建议还是使用 vscode + volar 这个官方推荐组合。
