### ISSUE TITLE
[Feature Request] van-picker选中值不是对象

### ISSUE THREAD

**Issue by dyubo2005** [youzan/vant#10667]
### 这个功能解决了什么问题
解决了前端显示和后台需求数据分离的痛点

### 描述您想要的解决方案
@confirm="confirm"

confirm(value, index) {
    console.log(value)
}

期望得到：[{text: '选项一', value: 1}, {text: '选项二', value: 2}]
现在居然：['选项一', '选项二']

### 建议的API是什么样的
@confirm="confirm"

confirm(value, index) {
    console.log(value)
}

期望得到：value: [{text: '选项一', value: 1}, {text: '选项二', value: 2}]
现在居然：value: ['选项一', '选项二']

**Comment by chenjiahan** [comment]
已经改了，可以使用 vant 4.0 alpha 版本
https://youzan.github.io/vant/v4
