### ISSUE TITLE
2.12.47这个版本还是不能跳转到当前日期，之前2.5.4版本已经解决过这个问题，但是在这个版本又出现了，麻烦兼容下，Calendar组件，我在平铺展示的时候，设置了日期的范围，并且设置了default-date，能否有办法主动跳转到default-date所在的日期，而非日期范围的开始日期呢

### ISSUE THREAD

**Issue by yangzhenggit** [youzan/vant#10660]
2.12.47这个版本还是不能跳转到当前日期，之前2.5.4版本已经解决过这个问题，但是在这个版本又出现了，麻烦兼容下

<van-calendar :show-confirm="false" :min-date="new Date(2020, 1, 1)" :max-date="new Date()" :default-date="new Date()" @confirm="onTimeStartConfirm" :poppable="false" />

**Comment by chenjiahan** [comment]
请按照模板创建 issue，并提供复现的 codesandbox 链接。
