### ISSUE TITLE
[Feature Request] field希望lable输入框能换行展示

### ISSUE THREAD

**Issue by gongml123** [youzan/vant#10675]
### 这个功能解决了什么问题
当lable过长列如（请输入身份证号码），这样在一些长的lable上会出现后面展示不全

### 描述您想要的解决方案
lable与内容框能换行展示

### 建议的API是什么样的
列如el可以控制lable展示在上方或者左侧右侧

**Comment by chenjiahan** [comment]
暂无计划支持哈，这块可以自己覆盖样式来实现
