### ISSUE TITLE
[Bug Report] vant Field 组件在@blur事件中, ios键盘无法消失

### ISSUE THREAD

**Issue by hsapphire** [youzan/vant#10678]
### 重现链接

https://codepen.io/

### Vant 版本

4.0.0-alpha.3

### 描述一下你遇到的问题。

 vant Field 组件在@blur事件中, ios键盘无法消失

### 重现步骤

 vant Field 组件在@blur事件中, ios键盘无法消失

**Comment by chenjiahan** [comment]
请提供有效的复现链接。
