### ISSUE TITLE
van-image 能不能像el-image 一样，为什么要改变原有img的风格呢，从img改成van-image后样式一团乱

### ISSUE THREAD

**Issue by tanzheng231** [youzan/vant#10679]
### 重现链接

1

### Vant 版本

all

### 描述一下你遇到的问题。

van-image 能不能像el-image 一样，为什么要改变原有img的风格呢，从img改成van-image后样式一团乱

### 重现步骤

van-image 能不能像el-image 一样，为什么要改变原有img的风格呢，从img改成van-image后样式一团乱

**Comment by chenjiahan** [comment]
van-image 对 img 标签做了简单的包装，没有设置过多的样式。
