### ISSUE TITLE
V3.5.0 vite-plugin-style-import报错

### ISSUE THREAD

**Issue by yuyinws** [youzan/vant#10671]
### 重现链接

https://codesandbox.io/s/objective-river-0ovrsy

### Vant 版本

3.5.0

### 描述一下你遇到的问题。

vant：v3.5.0
vite-plugin-style-import：v1.4.1

```js
// main.js
import { createApp } from 'vue'
import App from './App.vue'
import { Button } from 'vant'

createApp(App).use(Button).mount('#app')
```

```js
// vite.config.js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport, { VantResolve } from 'vite-plugin-style-import';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(),
    styleImport({
      resolves: [VantResolve()],
    }),
  ]
})
```

报错信息：
[vite] Internal server error: Failed to resolve import "/sandbox/node_modules/vant
/lib/vant/es/button/style" from "src/main.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /sandbox/src/main.js
  3  |  import { Button } from 'vant'
  4  |
  5  |  import '/sandbox/node_modules/vant/lib/vant/es/button/style';
     |          ^
  6  |
  7  |

### 重现步骤

打开[codesandbox](https://codesandbox.io/s/objective-river-0ovrsy)即可

**Comment by abumphy** [comment]
vite-plugin-style-import现在的版本是2.0.x，升级之后报其他的错

**Comment by yuyinws** [comment]
> vite-plugin-style-import现在的版本是2.0.x，升级之后报其他的错

vant3.4.9 + vite-plugin-style-import 1.4.1 正常
vant3.4.9 + vite-plugin-style-import 2.x 报错

**Comment by HuangChen9** [comment]
我用vant3.4.9 + vite-plugin-style-import 2.x 使用button可以，但是引入toast的时候报错了，多了个“/vant/lib/”不知道哪来的

**Comment by NickBang** [comment]
有同样的问题  
vant：v3.5.0
vite-plugin-style-import：v1.4.1

**Comment by Adaer** [comment]
> vant3.4.9 + vite-plugin-style-import 1.4.1

vant3.5.0 + vite-plugin-style-import 2.0 报错
vant3.5.0 + vite-plugin-style-import 1.4.1 报错

**Comment by chenjiahan** [comment]
遇到问题的同学可以先不使用 vite-plugin-style-import ，直接手动引入 Vant 的样式文件。

我们近期会处理该问题。

**Comment by Adaer** [comment]
> 
组件有如下错误，项目已经迭代几次了，突然出现这种报错；请教各位大佬，是我的类型声明有问题吗，但是其他组件没发现这种问题
`
 <van-skeleton title :row="15" :loading="loading">
 <van-cell v-for="(item, key) in mapData" :key="key" :title="`${item.label}：`">
`
const VanSkeleton: WithInstall<DefineComponent<{
    row: {
        type: (NumberConstructor | StringConstructor)[];
        default: number;
    };
    title: BooleanConstructor;
    round: BooleanConstructor;
    ... 6 more ...;
    rowWidth: {
        ...;
    };
}, ... 10 more ..., {
    ...;
}>> | (ComponentPublicInstanceConstructor<...> & ... 5 more ... & Plugin_2)
没有与此调用匹配的重载。
  第 1 个重载(共 2 个)，“(...args: any[]): ({ $: ComponentInternalInstance; $data: {}; $props: Partial<{ dynamicId: string; theme: PopoverTheme; placement: PopoverPlacement; }> & Omit<...>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; } & ... 5 more ... & { ...; }) | ({ ...; } & ... 5 more ... & { ...; })”，出现以下错误。
  第 2 个重载(共 2 个)，“(): ({ $: ComponentInternalInstance; $data: {}; $props: Partial<{ dynamicId: string; theme: PopoverTheme; placement: PopoverPlacement; }> & Omit<...>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; } & ... 5 more ... & { ...; }) | ({ ...; } & ... 5 more ... & { ...; })”，出现以下错误。ts(2769)

**Comment by CharleeWa** [comment]
这个问题出现已经大半年了。

https://github.com/vbenjs/vite-plugin-style-import/issues/52  当时的版本是1x左右，但是不知道作者为什么自己关闭了issue.

https://github.com/youzan/vant/issues/10147  现在vant3.5，v-p-s-i 2.x 也是会报错。

等待社区解决再按需引入

**Comment by chenjiahan** [comment]
vite-plugin-style-import 看起来已经不太维护了，问题比较多，后续我们推荐使用 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)。



#### 1. 安装插件

```bash
# 通过 npm 安装
npm i unplugin-vue-components -D

# 通过 yarn 安装
yarn add unplugin-vue-components -D

# 通过 pnpm 安装
pnpm add unplugin-vue-components -D
```

#### 2. 配置插件

安装完成后，在 `vite.config.js` 文件中配置插件：

```js
import vue from '@vitejs/plugin-vue';
import Components from 'unplugin-vue-components/vite';
import { VantResolver } from 'unplugin-vue-components/resolvers';

export default {
  plugins: [
    vue(),
    Components({
      resolvers: [VantResolver()],
    }),
  ],
};
```

**Comment by liwenfengg** [comment]
> vite-plugin-style-import 看起来已经不太维护了，问题比较多，后续我们推荐使用 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)。
> 
> #### 1. 安装插件
> ```shell
> # 通过 npm 安装
> npm i unplugin-vue-components -D
> 
> # 通过 yarn 安装
> yarn add unplugin-vue-components -D
> 
> # 通过 pnpm 安装
> pnpm add unplugin-vue-components -D
> ```
> 
> #### 2. 配置插件
> 安装完成后，在 `vite.config.js` 文件中配置插件：
> 
> ```js
> import vue from '@vitejs/plugin-vue';
> import Components from 'unplugin-vue-components/vite';
> import { VantResolver } from 'unplugin-vue-components/resolvers';
> 
> export default {
>   plugins: [
>     vue(),
>     Components({
>       resolvers: [VantResolver()],
>     }),
>   ],
> };
> ```

我的项目目前这样是没问题的(依赖更新后会报上面一样的错误)
请问我这是重复配置了吗
VantResolver 
VantResolve
```js

import { VantResolver } from 'unplugin-vue-components/resolvers'
import { VantResolve, createStyleImportPlugin } from 'vite-plugin-style-import'

  return defineConfig({
  plugins: [
      Components({
        resolvers: [
          VantResolver(),
        ],
        // allow auto load markdown components under `./src/components/`
        extensions: ['vue'],
        // allow auto import and register components used in markdown
        include: [/\.vue$/, /\.vue\?vue/],
        dts: 'src/components.d.ts',
      }),

      createStyleImportPlugin({
        resolves: [
          VantResolve(),
        ],
      }),
  ]
})
```

**Comment by yuyinws** [comment]
> 
是的 之前的`vite-plugin-style-import`已经不需要配置了

**Comment by Adaer** [comment]
import { VantResolve, createStyleImportPlugin } from 'vite-plugin-style-import'
这个插件不需要了

**Comment by Ttou** [comment]
@chenjiahan 用 unplugin-vue-components 插件样式会自动引入吗？试了下不行
![image](https://user-images.githubusercontent.com/4298437/180118498-911dbd9e-22e7-4e05-a0c8-9dbf5664b44b.png)

**Comment by GauharChan** [comment]
> @chenjiahan 用 unplugin-vue-components 插件样式会自动引入吗？试了下不行 ![image](https://user-images.githubusercontent.com/4298437/180118498-911dbd9e-22e7-4e05-a0c8-9dbf5664b44b.png)

+1

**Comment by GauharChan** [comment]
> vite-plugin-style-import 看起来已经不太维护了，问题比较多，后续我们推荐使用 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)。
> 
> #### 1. 安装插件
> ```shell
> # 通过 npm 安装
> npm i unplugin-vue-components -D
> 
> # 通过 yarn 安装
> yarn add unplugin-vue-components -D
> 
> # 通过 pnpm 安装
> pnpm add unplugin-vue-components -D
> ```
> 
> #### 2. 配置插件
> 安装完成后，在 `vite.config.js` 文件中配置插件：
> 
> ```js
> import vue from '@vitejs/plugin-vue';
> import Components from 'unplugin-vue-components/vite';
> import { VantResolver } from 'unplugin-vue-components/resolvers';
> 
> export default {
>   plugins: [
>     vue(),
>     Components({
>       resolvers: [VantResolver()],
>     }),
>   ],
> };
> ```

```vue
<Circle
    :current-rate="currentRate"
    color="#219EFF"
    layer-color="#E5E8ED"
    start-position="right"
    v-bind="$attrs"
    :stroke-width="strokeCom"
    :size="sizeCom"
  >
import { Circle } from 'vant';
```
这样,样式并不会引入。但之前的`vite-plugin-style-import`不就是这么简单就可以使用了吗
是否必须使用app.use(Circle)来注册组件？然后页面中使用<van-circle>的方式，那我想问要这个插件有啥用？ @chenjiahan
