### ISSUE TITLE
Calendar 日历控件在type为range的情况下仍存在空白的情况，滑动后才出现的问题

### ISSUE THREAD

**Issue by XKF** [youzan/vant#10670]
### 重现链接

https://txjh8x.csb.app/

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

浏览器模拟器里的机型暂时都没复现，目前出现空白这种问题的主要是iphone13pro且ios版本15的用户，也是一点开日历就空白，需要滑动下才会出现，测了2台ios15的iphone13pro都复现了，暂时没有多的空闲测试机不知道其他机型情况，可能跟ios版本有关，建议排查下ios15

### 重现步骤

1、点击按钮

### 设备/浏览器

iphone13pro的safari

**Comment by XKF** [comment]
![e566abfc-5147-4f6e-a495-954cd95ad9d3](https://user-images.githubusercontent.com/23168302/172125533-25a6cb58-84ec-4333-baf4-a9491ee9448f.png)

**Comment by chenjiahan** [comment]
**Vant 2 维护提示**

目前 Vant 3 已经发布超过 18 个月。对于 Vant 2，我们会将维护投入降低至最小范围，这意味着：

- 不再主动迭代新的功能。
- 致命 bug 依然会被处理和修复。
- 非致命 bug 或兼容性等问题将不在官方团队的处理范围内。
- 欢迎来自社区的 Pull Request 进行代码贡献。

**Comment by XKF** [comment]
您好~您的邮件我已收到，谢谢！

**Comment by yangtoude** [comment]
同问，我也复现了，这个问题该咋解决呀
iPhone 8P ios 11.4 无问题
ios13.3.1 iphoneXR 有问题
ios 16.0.2 iphone 11 Pro Max 有问题

**Comment by XKF** [comment]
您好~您的邮件我已收到，谢谢！

**Comment by JuanJuanZhang123** [comment]
请问大家有解决方案嘛？应该怎么解决？

**Comment by XKF** [comment]
您好~您的邮件我已收到，谢谢！

**Comment by JuanJuanZhang123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
你好，我是张娟娟，邮件已经收到，我会尽快给与答复
