### ISSUE TITLE
[Bug Report] vant-dialog组件与html2canvas存在冲突

### ISSUE THREAD

**Issue by fllsdds** [youzan/vant#10673]
### 重现链接

暂无复现链接，不过有个链接可以证明不少人遇上了这个bug https://blog.csdn.net/jinxi1112/article/details/101285998

### Vant 版本

vant@2.12.24

### 描述一下你遇到的问题。

目前html2canvas作为一个比较热门的html->图片的js库，和vant的dialog组件似乎存在冲突，当我使用html2canvas转化dialog组件上的html为图片时，产生了文字偏移，重叠以及模糊，而自己原生写的dialog则不存在这个问题
第一次提交issue，如有什么不规范的地方还请见谅

### 重现步骤

import html2canvas from "html2canvas";

<van-dialog>
<div ref="test">一些文字图片</div>
</van-dialog>

html2canvas(this.$refs.test, {}).then((canvas) => {
          let imageUrl = canvas.toDataURL("image/png"); // 将canvas转成base64图片格式
          this.canvasImageUrl = imageUrl;
});

通过这种方式渲染的图片和原dom差异很大

### 设备/浏览器

目前仅在微信开发者工具上测试过

**Comment by fllsdds** [comment]
一些图片文字那里的标签没了，我补上
“<van-dialog>
 <div ref="test">一些图片文字</div>
</van-dialog>”

**Comment by chenjiahan** [comment]
html2canvas 相关的问题不在我们的兼容范围内，建议自行处理哈。

可以看看是不是 transform 之类的 CSS 引起该问题。
