### ISSUE TITLE
van-calendar 设置min-date 时，会默认跑到最小值，应该是当前年月

### ISSUE THREAD

**Issue by smz8023** [youzan/vant#10672]
### 重现链接

https://codesandbox.io/s/vant-2-issue-template-forked-0gme5y?file=/src/App.vue

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

van-calendar 设置min-date 时，会默认跑到最小值，应该是当前年月

### 重现步骤

点击按钮

### 设备/浏览器

所有

**Comment by goo-yyh** [comment]
把:default-date="null"去掉就好了吧，默认选中今天会有什么问题吗

**Comment by smz8023** [comment]
和默认不选中功能冲突了。有min-date就无法使用默认不选中功能了

**Comment by goo-yyh** [comment]
> 和默认不选中功能冲突了。有min-date就无法使用默认不选中功能了

不理解这个意思，如果需要到当前年月，把default-date="null"去掉就好了呀。

**Comment by smz8023** [comment]
![image](https://user-images.githubusercontent.com/31838004/172524827-fb4f4561-29a8-49e1-bbb5-5fda7df5f848.png)
加上default-date="null" 是为了默认不选中，如果去掉default-date="null" 会默认选中当前日，

**Comment by goo-yyh** [comment]
> ![image](https://user-images.githubusercontent.com/31838004/172524827-fb4f4561-29a8-49e1-bbb5-5fda7df5f848.png) 加上default-date="null" 是为了默认不选中，如果去掉default-date="null" 会默认选中当前日，

既然设置了min-date，又没有设置default-date，从min-date开始显示并没有什么问题吧。

**Comment by smz8023** [comment]
应该是当前的年吧，我只是设置了最小的开始时间，CurrentMount 应该是当前年的当前月，不应该在循环的时候直接就给CurrentMount赋值吧

**Comment by nemo-shen** [comment]
@smz8023 
哈喽，很高兴看到你为vant提的issue，我来解释一下

### Calendar组件内部逻辑

1. 当你什么都不设置时，`<Calendar />` 在初始化时**会默认以当前日期作为默认选中日期**
2. 当有默认日期时（无论是开发者手动通过 `default-date` 设置，还是组件的默认日期），初始化时，我们会滚动到对应的选中日期上。[可以从这里开始看代码逻辑](https://github.com/youzan/vant/blob/2.x/src/calendar/index.js#L190)
3. `default-date` 允许为 `null`，当为 `null` 时，则表示开发者不希望组件初始化默认日期 [#7013](https://github.com/youzan/vant/issues/7013)
4. 当组件初始化时取不到默认日期时，则不会触发 `scrollIntoView`

### 结论

根据上述的这些逻辑条件，当你设置了一个 `min-date` 但是 `default-date` 又为 `null` 时，由于不会触发 `scrollIntoView` 因此组件初始化之后一定是在你的最小那个月份（即日期滚动列表的最顶端）

**Comment by nemo-shen** [comment]
issue 先关了，如果还有疑问可以继续提

**Comment by nanbingxyz** [comment]
版本：2.12.52
当 min-date 发生变动，会跑到最小值而不是当前年月。如果一开始就确定 min-date 且不变不会有问题，视图会显示当前年月，但比如 min-date 的值是computed中的属性，变动后视图就会跑到最小值。
