### ISSUE TITLE
[Bug Report] vue3 版本 van-datetime-picker

### ISSUE THREAD

**Issue by lucky0lonely** [youzan/vant#10685]
### 重现链接

https://codesandbox.io/s/great-bird-7tqhhx?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675

### Vant 版本

3.2.6

### 描述一下你遇到的问题。

Maximum recursive updates exceeded in component <BaseTransition>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

年份变大，递归会出问题。

### 重现步骤

点击 van-field 会导致页面卡顿。

codesanbox.io 链接
https://codesandbox.io/s/great-bird-7tqhhx?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675

手机端展示地址
https://7tqhhx.csb.app/

在 van-datetime-picker 上加上 v-model="currentDate"就会卡顿

### 设备/浏览器

所有

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/173186079-909da8ad-ac63-4f10-9055-cdc0807b0462.png)
