### ISSUE TITLE
[Bug Report] 细边框不兼容firefox浏览器

### ISSUE THREAD

**Issue by sleiphur** [youzan/vant#10682]
### 重现链接

https://youzan.github.io/vant/#/zh-CN/button

### Vant 版本

3.5.0

### 描述一下你遇到的问题。

细边框按钮在firefox下显示不正确。
![image](https://user-images.githubusercontent.com/32027461/172746753-61d91c06-dd0b-469a-ac89-62577f670e2b.png)

### 重现步骤

firefox下访问https://youzan.github.io/vant/#/zh-CN/button页面

### 设备/浏览器

Windows 10 专业版 21H2,  firefox 101.0 (64 位)

**Comment by chenjiahan** [comment]
试了下 mac 的 firebox 没问题，这个应该是浏览器渲染问题，没啥好方法解决，而且 Vant 主要以兼容移动端浏览器为主。

不过你可以在边框对应的伪类上添加以下样式试试：

```css
transform: translateZ(0);
```
