### ISSUE TITLE
GoodsActionMiniBtn中info属性在数字过大时会被遮挡

### ISSUE THREAD

**Issue by pylee** [youzan/vant#1068]
效果如图：
![image](https://user-images.githubusercontent.com/965874/40036536-8cdf2362-583a-11e8-8c42-c44452f12e10.png)
当数字3位数时，数字指示就会被遮挡。
辛苦了。

**Comment by chenjiahan** [comment]
后续会优化这个问题

**Comment by chenjiahan** [comment]
已在 1.1.4 版本修复
