### ISSUE TITLE
Dialog 弹出框 beforeClose 定时异步关闭时一直闪烁

### ISSUE THREAD

**Issue by lookwe** [youzan/vant#10688]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/dialog#yi-bu-guan-bi

### Vant 版本

3.2.0

### 描述一下你遇到的问题。

* 提示框中点击确认，需要定时30秒后关闭
* 在定时倒计时，弹框一直闪烁

### 重现步骤

* 点击确定按钮

**Comment by chenjiahan** [comment]
请提供有效的复现链接。
