### ISSUE TITLE
[Bug Report] van-field 点击清除按钮不生效

### ISSUE THREAD

**Issue by 461450432** [youzan/vant#10683]
### 重现链接

http://4s228r4016.zicp.fun/mobile.html#/zh-CN/field

### Vant 版本

3.5.0

### 描述一下你遇到的问题。

在浏览器上手机调试模式下， 点击van-field 的清除图标不生效。

### 重现步骤

1.打开谷歌浏览器
2.打开开发者工具
3.设置成手机调试模式
4.输入框van-field 的 clearable属性设为true
5. 输入内容点击清除图标， 没有生效

### 设备/浏览器

谷歌浏览器，edge浏览器

**Comment by chenjiahan** [comment]
https://youzan.github.io/vant/#/zh-CN/field#zai-zhuo-mian-duan-dian-ji-qing-chu-an-niu-wu-xiao

**Comment by dududu123456** [comment]
```
 <van-field
      v-model="val"
      clearable
      @clear="clickToClear"
  />
```
点击clear回调不生效，移动端，版本如下
```
"vant": "^3.6.4",
"vue": "^3.2.40",
```

最终通过right-icon侧面解决
```
<van-field
      v-model="val"
      :right-icon="val && 'clear'"
      @click-right-icon="clickToClear"
  />
```
