### ISSUE TITLE
[Bug Report] v3.5.0 打包样式丢失

### ISSUE THREAD

**Issue by longdan** [youzan/vant#10681]
### 重现链接

v3.5.0 打包样式丢失

### Vant 版本

3.5.0

### 描述一下你遇到的问题。

v3.5.0 打包样式丢失  装v3.4.9版本没问题

### 重现步骤

config.module
      .rule("ts")
      .use("ts-loader")
      .tap(options => {
        options = merge(options, {
          transpileOnly: true,
          getCustomTransformers: () => ({
            before: [
              tsImportPluginFactory({
                libraryName: "vant",
                libraryDirectory: "es",
                style: name => `${name}/style/less`
                //style: true
              })
            ]
          }),
          compilerOptions: {
            module: "es2015"
          }
        });
        return options;
      });

### 设备/浏览器

v3.5.0 打包样式丢失

**Comment by kwSir-chen** [comment]
刚遇到，那个路径怎么看都很奇怪

**Comment by yisky77** [comment]
v3.5.0 我也遇到了, 样式丢失

**Comment by chenjiahan** [comment]
请提供可以复现问题的仓库哈
