### ISSUE TITLE
Toast文字小且无法覆盖样式

### ISSUE THREAD

**Issue by weiiz** [youzan/vant#10697]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-zypjyf

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

Toast文字小且无法覆盖样式,v-deep,less覆盖都不行

### 重现步骤

Toast文字小且无法覆盖样式,v-deep,less覆盖都不行

### 设备/浏览器

所有

**Comment by weiiz** [comment]
![image](https://user-images.githubusercontent.com/57380836/173175215-0798f332-526c-49dd-a194-0cacc6ccc950.png)

**Comment by weiiz** [comment]
![image](https://user-images.githubusercontent.com/57380836/173175228-a16b0c33-d172-496a-b3c2-d14a695ccc3f.png)

**Comment by chenjiahan** [comment]
可以使用 className 属性添加自定义类型来进行覆盖
