### ISSUE TITLE
van-tabbar-item标签的to 不能写 / 

### ISSUE THREAD

**Issue by MaoSource** [youzan/vant#10696]
vue版本：2.6.14
vant版本：2.12.47
vue-router版本：3.5.1

to写 / 会一直处于选中状态

![image](https://user-images.githubusercontent.com/56857029/173042585-0e3c964d-d67c-4ad0-a979-cc23bd498ade.png)
![image](https://user-images.githubusercontent.com/56857029/173042644-43aa0b86-4e89-4bdf-a6bd-7779ef760c28.png)

**Comment by MaoSource** [comment]
![image](https://user-images.githubusercontent.com/56857029/173043659-70ede6b1-c5d5-4318-a72a-77259b64a6ef.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，并提供复现链接。另外你可以搜索一下历史 issue，应该有人提过类似的问题
