### ISSUE TITLE
时间控件，maxDate和设置的不一致

### ISSUE THREAD

**Issue by PuRonglong** [youzan/vant#1069]
**时间控件，maxDate和设置的不一致**

**https://jsfiddle.net/puronglong/dfarLdko/88/**

**chrome 60 brower**

**Comment by rex-zsd** [comment]
@PuRonglong 这个表现是正常的，`new Date(2019, 12, 30)`实际返回的是2020年1月30号，可以参考下[mozilla](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date#.E5.8F.82.E6.95.B0)
