### ISSUE TITLE
[Feature Request] vant3日期时间范围选择控件，Calendar 控件能自定义日期选择范围么？目前业务中经常会有选择过去某个时间段的功能需求~谢谢

### ISSUE THREAD

**Issue by lzq-dingyuan** [youzan/vant#10695]
### 这个功能解决了什么问题？

目前业务中经常会有选择过去某个时间段，然后通过返回的日期来获取数据的需求，我想这个场景应该很多业务都会遇到~目前没有看到合适的api能实现这个功能。

### 你期望的 API 是什么样子的？

暂无

**Comment by chenjiahan** [comment]
Calendar 提供了 max-date 和 min-date 属性来设置时间范围
