### ISSUE TITLE
[Bug Report] popup组件希望提供一个配置，允许自定义选择是否关闭弹窗，而不是默认重新打开

### ISSUE THREAD

**Issue by ywymoshi** [youzan/vant#10692]
### 重现链接

暂无

### Vant 版本

3.0.0

### 描述一下你遇到的问题。

如下
![image](https://user-images.githubusercontent.com/46644748/173009438-59e6dcff-3fd8-4751-b3fc-fb6beedd30ed.png)

期望的效果是：
不希望有关闭、打开的动作，希望提供一个配置

### 重现步骤

1. 弹窗显示
2. 路由跳转至其他页面，自动关闭了弹窗
3. 路由返回弹窗页，会重新弹出弹窗，会有一个弹出动画

跳转时不想关闭弹窗，回来时不想有弹出的动画

**Comment by chenjiahan** [comment]
这种情况建议你把 Popup 组件放在弹窗页的外部，通过状态来控制，

因为 Popup 本身是弹窗页的一个子组件，当离开弹窗页时，弹窗页的所有组件都会被销毁，包括 Popup 组件。

**Comment by ywymoshi** [comment]
假设我放在弹窗页外，我离开弹窗页时，我不关掉，那么他会始终存在最顶层，因为我是希望他是被keep-alive缓存状态的，所以我希望他存在在弹窗页里面，但是不希望页面返回回来时会有关闭打开的动作。这在ios中手机侧滑返回时会造成动画异常

**Comment by chenjiahan** [comment]
目前这个自动关闭的行为主要是为了保证 teleport 的弹窗能够被正确关闭，后续会加个判断优化下，仅在使用 teleport 时触发该行为。

这样应该能解决你的问题。
