### ISSUE TITLE
日期选择 van-calendar 渲染问题

### ISSUE THREAD

**Issue by cll123456** [youzan/vant#10708]
### 重现链接

https://codesandbox.io/embed/vant-3-issue-template-forked-pjyd0z?fontsize=14&hidenavigation=1&theme=dark

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

大佬，您好，我在使用van-calendar 发现了一个bugger, **日期选择器渲染失败**，bugger效果如下：

![image](https://user-images.githubusercontent.com/41314419/173267282-cab0df2a-2e63-47a8-b434-2a5e5432d84f.png)

>此时，如果您手动滚动日历内部滚动条，则恢复正常

![image](https://user-images.githubusercontent.com/41314419/173267498-966a60d4-650a-425c-9f52-4c9f61547b8b.png)

### 重现步骤

1. 点击按钮，然后关闭日期弹框
2. 点击switch,切换到右边
3. 在点击按钮，则出现问题

### 设备/浏览器

chrome102.0.5005.63

**Comment by goo-yyh** [comment]
重复issue #10668

**Comment by goo-yyh** [comment]
重复issue，已经合并代码

**Comment by chenjiahan** [comment]
已经发布 3.5.1 修复版本

**Comment by cll123456** [comment]
@chenjiahan @goo-yyh 感谢您的回复！ 就是说，拉3.5.1版本的代码就好了吗？

**Comment by chenjiahan** [comment]
嗯，升级下试试

**Comment by cll123456** [comment]
@chenjiahan 非常感谢，好了🎉🎉🎉

**Comment by liangH1997** [comment]
[@chenjiahan](https://github.com/chenjiahan) 已升级到3.5.1，安卓10还是有一样的问题，滑动屏幕后正常展示，大佬帮忙看看吗
![微信图片_20221014122604](https://user-images.githubusercontent.com/65057566/195763231-d4aebef9-771a-4eef-84ed-bf3aadb408fe.jpg)

**Comment by YYzoneYY** [comment]
> 已经发布 3.5.1 修复版本

vant2 也存在这个问题 是否给予修复?
