### ISSUE TITLE
[Bug Report] Field type 为textarea autosize 高度自适应无效。

### ISSUE THREAD

**Issue by f43310** [youzan/vant#10705]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-q5opzy?file=/src/App.vue

### Vant 版本

"vant": "^3.5.0",

### 描述一下你遇到的问题。

文本框出现滚动条，而不是自适应高度。

### 重现步骤

输入多行文本后。

### 设备/浏览器

chrome-v102.0.5005.63

**Comment by chenjiahan** [comment]
把 `rows="1"` 去掉

**Comment by chenjiahan** [comment]
你没定义 message 变量

**Comment by f43310** [comment]
谢谢，确实是这样的
