### ISSUE TITLE
vant-doc 里面使用better-scoroll 无法滚动

### ISSUE THREAD

**Issue by lixiang** [youzan/vant#1070]
如题，自己写了一个组件库，用到了better-scroll，用vant-doc做展示，但是bs在vant-doc无法滚动。有解决思路吗？vant-doc有开源计划吗？

**Comment by chenjiahan** [comment]
暂无计划支持 better-scoroll 喔，可以去对应的仓库下提问。vant-doc 后续会考虑开源，但是优先级比较低
