### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by Azul-04** [youzan/vant#10711]
### 重现链接

https://codesandbox.io/embed/vant-3-issue-template-forked-0g4fbp?fontsize=14&hidenavigation=1&theme=dark

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

tabs的swipeable属性和popup冲突

### 重现步骤

1.加入swipeable属性
2.点击弹窗

**Comment by chenjiahan** [comment]
这个是浏览器本身的限制，暂时无解。可以手动把 Popup 的布局由 fixed 改为其他布局方式
