### ISSUE TITLE
编译无法通过的问题

### ISSUE THREAD

**Issue by QianTangrong** [youzan/vant#10714]
### Reproduction Link

https://github.com/youzan/vant/issues/10549

### Vant Version

 "vant": "^3.4.9",

### Describe the Bug

vue3+vite+ts+vant3
"vue": "^3.0.5",
 "vite": "^2.4.4",
 "vue-tsc": "^0.37.8"
  "typescript": "^4.3.2",
 "vant": "^3.4.9",
tsconfig配置设置跳过modules文件和设置了skipLibCheck，还是编译不通过
版本信息如上，请问这种问题原因是什么哩
![image](https://user-images.githubusercontent.com/39990310/173982104-d337e6d3-52a2-47fb-9062-b6f09c241075.png)

### Reproduce Steps

run build

**Comment by chenjiahan** [comment]
可以升级 typescript 到最新版试下
