### ISSUE TITLE
[Bug Report] van-calendar组件formatter函数ios设备在打开日历只会触发一次，安卓设备点击任意日期都会触发

### ISSUE THREAD

**Issue by wjf743108664** [youzan/vant#10719]
### 重现链接

http://cms.wuyeface.com/wechatyfb/#/atDinnerFor?metaTitle=%E6%8A%A5%E9%A4%90%E7%94%B3%E8%AF%B7

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

案例场景：微信公众号（手机浏览器也能复现）：van-calendar组件formatter函数ios设备在打开日历只会触发一次，安卓设备和PC调试时正常点击任意日期都会触发，
需要使用formatter函数在选择不同日期时按照周选择格式化日历，更新日历的ui

### 重现步骤

1，报餐方式选择-按周
2，点击用餐时间
3，出现日历之后点击任意日期可复现
4，用ios和安卓设备看对比很明显

### 设备/浏览器

ios设备都能重现

**Comment by wjf743108664** [comment]
安卓手机图：![019cb2c28f255722159163fbb18b3d9](https://user-images.githubusercontent.com/49603044/174047852-46a8635d-b021-4c13-b08b-b5f21d55c230.jpg)
![cb0ff677710af48228328c4806a6095](https://user-images.githubusercontent.com/49603044/174048272-e05fcbf3-998b-443f-b263-500e53802dac.jpg)
![a4e021f0b7f780bc60e8100e8502ef0](https://user-images.githubusercontent.com/49603044/174048292-db431891-0449-4577-aa95-41854296f709.jpg)
ios手机图：
![add5abd5d2c9e8cbec574836194d55d](https://user-images.githubusercontent.com/49603044/174048346-170b37e9-47f8-47de-ba8f-5afa1564f72e.jpg)
![7222180a7d41f1f9e7c0029d290df0c](https://user-images.githubusercontent.com/49603044/174048370-114182d5-4713-4654-a1e6-c292ad7d9327.jpg)
![d42da76adf57aeea6afc13632e84c0f](https://user-images.githubusercontent.com/49603044/174048381-ce773e81-cdcc-4939-9aaf-dfdfe1489450.jpg)

**Comment by chenjiahan** [comment]
<img width="684" alt="vant-2" src="https://user-images.githubusercontent.com/7237365/174434018-76091dec-9363-458c-9f1d-12375f030b01.png">

**Comment by wb121017405** [comment]
记笔记：ios 日历组件 max-date 动态绑定时间传入new Date(time)

time 格式不能是 YY-MM-DD！否则是无效时间导致卡死

转换为YY/MM/DD
