### ISSUE TITLE
[Feature Request] 官方可否提供一个支持vite按需引入的插件

### ISSUE THREAD

**Issue by yanbowe** [youzan/vant#10712]
### 这个功能解决了什么问题？

支持按需引入，目前有unplugin-vue-components和vite-plugin-style-import缺乏对vant组件库的维护，有bug基本没人回复，所以希望官方提供一个插件
例如https://github.com/antfu/unplugin-vue-components/issues/327

### 你期望的 API 是什么样子的？

unplugin-vant-components

**Comment by yanbowe** [comment]
> 我倾向于提 PR 到 unplugin-vue-components 来解决哈，没必要造个新轮子，我会抽空看一下这个问题

收到

**Comment by zaxlct** [comment]
引入 Toast ，功能正常，但是没有样式...
@chenjiahan

**Comment by yanbowe** [comment]
> 引入 Toast ，功能正常，但是没有样式... "unplugin-vue-components": "^0.19.6", "vant": "^4.0.0-alpha.4", @chenjiahan

通知型组件需要手动引入样式

**Comment by chenjiahan** [comment]
unplugin-vue-components 的问题统一在这个 issue 中跟进：https://github.com/youzan/vant/issues/10709
