### ISSUE TITLE
[Bug Report] Vue3项目中Swiper、Slider组件拖动问题

### ISSUE THREAD

**Issue by ZhengTZ-Max** [youzan/vant#10713]
### 重现链接

https://test-vant.vercel.app/

### Vant 版本

3.4.8

### 描述一下你遇到的问题。

 Swiper、Slider组件
 在PC端手势滑动无效、无法左右滑动。
 
 备注：如该组件只针对移动端，不对PC端进行适配 那就直接把问题关闭吧。

### 重现步骤

1. 使用浏览器进入网址。
2. 不用移动端模拟器，切换到PC模式。
3. 尝试操作 Swiper、Slider组件。
4. 在PC端手势滑动无效、无法左右滑动。

### 设备/浏览器

PC端浏览器

**Comment by chenjiahan** [comment]
https://youzan.github.io/vant/#/zh-CN/faq#bu-fen-zu-jian-wu-fa-zai-zhuo-mian-duan-jin-xing-cao-zuo

**Comment by ZhengTZ-Max** [comment]
好的 看到了 谢谢你
