### ISSUE TITLE
[Bug Report] 使用unplugin-vue-components后组件形式使用Dialog报错

### ISSUE THREAD

**Issue by wht300** [youzan/vant#10718]
### 重现链接

https://github.com/wht300/vant-dialog-error-store

### Vant 版本

3.5.1

### 描述一下你遇到的问题。

当使用按需加载unplugin-vue-components后
在使用Dialog 组件形式使用时，v-model:show无效，
页面渲染后Dialog 会默认弹出，且当v-model:show="true"时，
控制台中抛出错误
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parentNode')
```

### 重现步骤

1、进入页面后show 设为false,但Dialog默认展示
2、关闭dialog后，点击toggleShow将show置为true时，控制台将会弹出错误
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parentNode')
```

**Comment by chenjiahan** [comment]
Dialog 是一个函数而非组件，需要手动注册下 Dialog.Component
