### ISSUE TITLE
输入框如何自定义icon 

### ISSUE THREAD

**Issue by zxbigdevil** [youzan/vant#1071]
<van-field
    v-model="username"
    label="用户名"
    icon="clear"
    placeholder="请输入用户名"
    required
    @click-icon="username = ''"
  />

    icon="clear"这个icon怎么自定义 求求~~~

**Comment by LynanBreeze** [comment]
https://www.youzanyun.com/zanui/vant#/zh-CN/field
文档上不是写得很清楚吗

**Comment by LynanBreeze** [comment]
用自带的icon就把name填入icon=“name”，
如果自己的icon就用一个slot=“icon” 啊
