### ISSUE TITLE
[Bug Report] Vant4 switch 自定义按钮icon没有效果

### ISSUE THREAD

**Issue by CharleeWa** [youzan/vant#10717]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-yco5zb

### Vant 版本

vant: 4.0.0-alpha.4

### 描述一下你遇到的问题。

 Vant4 switch 自定义按钮icon没有效果

### 重现步骤

1: 引入
`
<van-switch v-model="checked" size="20px">
  <div class="icon-wrapper">
    <van-icon :name="checked ? 'success' : 'cross'" />
  </div>
</van-switch>
`

### 设备/浏览器

chrome 版本 102.0.5005.63（正式版本） （64 位）

**Comment by chenjiahan** [comment]
这里是文档写错了，正确写法为：

```html
<van-switch v-model="checked">
  <template #node>
    <div class="icon-wrapper">
      <van-icon :name="checked ? 'success' : 'cross'" />
    </div>
  </template>
</van-switch>
```

后续会修正下文档
