### ISSUE TITLE
希望增加 `statistic统计数值` 组件

### ISSUE THREAD

**Issue by deajax** [youzan/vant#10716]
### 这个功能解决了什么问题？

可以方便的展示统计数值，具体请参考ant-design-vue 的 [a-statistic](https://www.antdv.com/components/statistic-cn) 组件

移动端h5页面经常会用到 【数据统计】 这一功能，statistic组件可以方便的对一些简单的数据进行展示，如：

今日反馈率 &#12288;&#12288; 今日销售额
**45%**   &#12288;&#12288;&#12288;&#12288; &#12288; **¥3.98**

### 你期望的 API 是什么样子的？

```
<van-statistic column-num="2">
        <van-statistic-item title="今日反馈率" value="45" suffix="%" />
        <van-statistic-item title="今日销售额(元)" value="3.98" prefix="¥" />
</van-statistic>
```

**Comment by chenjiahan** [comment]
暂无计划支持哈
