### ISSUE TITLE
[Bug Report] van-list 组件 load未执行

### ISSUE THREAD

**Issue by babalrlr** [youzan/vant#10727]
### 重现链接

https://stackblitz.com/edit/nuxt-starter-4ykunz

### Vant 版本

3.5.1

### 描述一下你遇到的问题。

van-list 组件 load未执行

### 重现步骤

进入首页后，然后点击【go b.vue】，load未执行

**Comment by chenjiahan** [comment]
可以手动调用一下 List 组件的 check 方法来进行滚动状态检测

**Comment by babalrlr** [comment]
`onMounted(() => {
      setTimeout(() => {
        refVanList.value.check();
      },100);
    });`

业务代码里，必须要加上 setTimeout才行。


跟踪组件代码后，发现组件内，onMounted时会执行check方法，isHidden(root) 的结果是true。

组件不是已经挂载了吗，为什么 el.offsetParent === null 的结果是true。

@chenjiahan 老板方便解答一下吗

**Comment by chenjiahan** [comment]
估计和 Nuxt 切换 route 的实现有关，可以把 setTimeout 改成 nextTick 或 requestAnimationFrame 试试

**Comment by babalrlr** [comment]
好的吧。
@chenjiahan 感谢感谢😁

**Comment by babalrlr** [comment]
根据大佬的指点，在nuxt中有找到这个问题，[相关链接](https://github.com/nuxt/framework/issues/3587)。
