### ISSUE TITLE
van-tabs组件，不想默认选中任意一个，只想点击时再选中

### ISSUE THREAD

**Issue by gdutwyg** [youzan/vant#10722]
### 重现链接

https://codesandbox.io/s/3hxokl

### Vant 版本

3.5.1

### 描述一下你遇到的问题。

van-tabs组件，不想默认选中任意一个，只想点击时再选中，v-model:active设置-1，null等都会选中第一个

### 重现步骤

设置v-model:active为-1。不想选中默认
但是还是选中第一个

**Comment by chenjiahan** [comment]
对于 Tabs 组件来说，目前不应该存在「没有选中」的交互。

如果在个别场景下确实有这个需求，可以使用 CSS 把第一个 Tab 隐藏掉，模拟实现未选中的效果。
