### ISSUE TITLE
[Bug Report] field输入框的clearable属性不生效

### ISSUE THREAD

**Issue by omgcx1222** [youzan/vant#10721]
### 重现链接

复制官方文档的demo都不行：https://vant-contrib.gitee.io/vant/#/zh-CN/field

### Vant 版本

"vant": "^3.5.1",

### 描述一下你遇到的问题。

field输入框的时候clearable属性不生效

### 重现步骤

直接贴代码
```
<template>
  <van-cell-group inset>
    <van-field v-model="value1.v1" clearable label="文本" left-icon="music-o" placeholder="显示清除图标" />
    <van-field v-model="value2" clearable label="文本" left-icon="music-o" placeholder="显示清除图标" />
  </van-cell-group>
</template>

<script lang="ts">
import { reactive, ref } from "vue"

export default {
  setup() {
    const value1 = reactive({
      v1: ""
    })
    const value2 = ref("123")
    return {
      value1,
      value2
    }
  }
}
</script>

<style scoped></style>
```

"vant": "^3.5.1",
"unplugin-vue-components": "^0.19.6"

### 设备/浏览器

谷歌浏览器

**Comment by omgcx1222** [comment]
手机浏览器测试可以清除，谷歌浏览器的手机模拟器不生效

**Comment by chenjiahan** [comment]
https://youzan.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei

**Comment by omgcx1222** [comment]
> https://youzan.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei

刚刚在文档看到这了，不过不是这个原因，是谷歌浏览器的问题，模拟器使用iphone 12 pro时会出现这个bug，使用其它机型不会
