### ISSUE TITLE
时间组件默认值初始化不正确

### ISSUE THREAD

**Issue by Rickykurt** [youzan/vant#1072]
**What is the current behavior?**
详见：https://jsfiddle.net/dfarLdko/90/
设置currentDate为09:00或者9:00时，小时一项始终默认到00上
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/90/ or similar.**

**What is the expected behavior?**
设置currentDate为09:00或者9:00时，小时一项应默认至对应的值上
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by rex-zsd** [comment]
发现当minHour或者maxHour小于10的时候就可以复现，稍候我会提个pr解决这个问题
