### ISSUE TITLE
van-search 组件清空搜索框clear-icon点击无效

### ISSUE THREAD

**Issue by 380023777** [youzan/vant#10737]
### Vant 版本

3.5.1

### 描述一下你遇到的问题。

van-search点击clear-icon叉号，无法清除文本框内容

### 重现步骤

1、输入搜索内容
2、点击清空图标叉号无效，无法清除文本框内容

### 设备/浏览器

edge

**Comment by chenjiahan** [comment]
https://youzan.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei

**Comment by silent-wood** [comment]
我这里也是无法点击icon去清除Search的内容，已经按照了文档中适配桌面端的方法尝试过
dependencies：{
   "@vant/touch-emulator": "^1.4.0",
  "vant": "^3.5.2",
    "vue": "^3.2.37",
}
devDependencies:{
"@vitejs/plugin-vue": "^3.0.0",
"vite": "^3.0.0"
}

**Comment by xiaotiandada** [comment]
> https://youzan.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei

有效
