### ISSUE TITLE
[Bug Report] swipe用v-show控制，默认为false时，swipe-item轮播失效，左右滑动也无法切换tab

### ISSUE THREAD

**Issue by qljjun666** [youzan/vant#10734]
### 重现链接

无

### Vant 版本

3.5.0

### 描述一下你遇到的问题。

swipe用v-show控制，默认为false时，swipe-item轮播失效，左右滑动也无法切换tab

### 重现步骤

1、swipe用v-show控制，默认值为false
2、点击按钮显示swipe
3、swipe-item轮播失效，左右滑动也无法切换tab

**Comment by goo-yyh** [comment]
默认为false的话，看起来是不是用v-if来替代这种场景更好呢

**Comment by qljjun666** [comment]
用v-if是没问题的，因为这是一个tab栏，需要频繁切换，所以用了v-show

**Comment by goo-yyh** [comment]
> 用v-if是没问题的，因为这是一个tab栏，需要频繁切换，所以用了v-show

如果一定要使用v-show的话，推荐首次出现用v-if控制，后续切换用v-show，就不会有问题了。
