### ISSUE TITLE
[Bug Report] countdow 初始化的时候就会触发 finish 方法

### ISSUE THREAD

**Issue by ChaseWindYoungs** [youzan/vant#10735]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-42cwvl?file=/src/App.vue

### Vant 版本

2.12.25

### 描述一下你遇到的问题。

countdown 无论设置time为何值的时候，都会触发finish事件

### 重现步骤

count down的time是接口请求的参数，
在data中的默认值是 空字符串

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
因为你的 time 一开始设置为了 0，所以会立即触发 finish 事件。

对于这种场景，建议把 auto-start 属性设置为 false，然后根据时机手动调用 start 方法。

**Comment by ChaseWindYoungs** [comment]
我就算不是零，是null，是 ''， 也一样会触发finish

**Comment by FH0904** [comment]
可以默认设置一个值 比如1000
