### ISSUE TITLE
[Bug Report] vant-tab 造成其他容器的滚动bug

### ISSUE THREAD

**Issue by 799189288** [youzan/vant#10731]
### 重现链接

https://github.com/799189288/vant-bug

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

当tabs的子组件tab的长度超过默认的5个时，在其他容器中使用element.scrollIntoView Api 会导致失效的bug

### 重现步骤

在顶部放置一个tabs 内置超过5个tab，然后给tabs绑定点击事件，点击时，给另一容器中的对应子元素绑定scrollIntoView({behavior: 'smooth'}) 将会导致scrollIntoView 不生效。 vant raf.js中内置的滚动方法requestAnimationFrame 阻止了这一API的作用

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
<img width="684" alt="vant-2" src="https://user-images.githubusercontent.com/7237365/175759231-afc55a09-3924-4804-ac73-ab6a78219781.png">
