### ISSUE TITLE
unplugin-vue-components/webpack 按需引入后报Module not found

### ISSUE THREAD

**Issue by KID-joker** [youzan/vant#10738]
### 版本：
webpack 5.73.0
vue 3.2.37
vant 3.5.1
unplugin-vue-components 0.19.6

### 遇到的问题：
报错：
Module not found: Error: Can't resolve 'vant/es'
Module not found: Error: Can't resolve 'vant/es/tabbar/style/index'
Module not found: Error: Can't resolve 'vant/es/tabbar-item/style/index'

### 步骤：
1、按照官网配置了webpack
```
ComponentsPlugin({
    resolvers: [VantResolver()],
})
```
2、在app.vue使用van-tabbar组件

请问是哪里配置不对吗

**Comment by KID-joker** [comment]
是因为mjs的问题吗

**Comment by chenjiahan** [comment]
未能复现该问题，需要提供一个复现仓库看下喔

**Comment by Alanscut** [comment]
@KID-joker webpack配置extensions加上.mjs
![image](https://user-images.githubusercontent.com/21104054/176615394-32c637d5-68eb-43bd-a326-98310d1ce389.png)

**Comment by littleomar** [comment]
> > @KID-joker webpack配置extensions加上.mjs ![image](https://user-images.githubusercontent.com/21104054/176615394-32c637d5-68eb-43bd-a326-98310d1ce389.png)
> 
> 引入可以了，但是报了`postcss-custom-properties: variable '--van-white' is undefined and used without a fallback` ![image](https://user-images.githubusercontent.com/42445388/176631815-1897f72b-2b6d-412b-a982-26c7f02019fb.png)

vant引入的css文件和你webpack的postcss-loader配置冲突了，不要让你的postcss-loader处理vant的css就行

**Comment by Alanscut** [comment]
或者可以弃用postcss-cssnext，改用postcss-preset-env
https://moox.io/blog/deprecating-cssnext

**Comment by KID-joker** [comment]
> 或者可以弃用postcss-cssnext，改用postcss-preset-env ![image](https://user-images.githubusercontent.com/21104054/176844275-03b737c0-b6c4-479d-8062-36d7dce4876c.png)
> 
> https://moox.io/blog/deprecating-cssnext

可以了，谢谢
