### ISSUE TITLE
[Bug Report] ios端 微信浏览器中 tab 组件选中最后一个时，选中文字被高亮。

### ISSUE THREAD

**Issue by akaili** [youzan/vant#10736]
### 重现链接

https://github.com/akaili/vant-tab-bug

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

在 ios 端，微信中打开页面时，选中最后一个 tab 选项是，文字颜色貌似被高亮了，通过更改 `swipe-threshold `数值发现，在该数值后一个会出现此情况，比如默认是5，第六个选中就会高亮。

### 重现步骤

使用 ios 系统，微信客户端访问
切换到最后一个 tab 

### 设备/浏览器

IOS, 微信客户端

**Comment by akaili** [comment]
https://user-images.githubusercontent.com/42698757/174997069-0e4fb6b6-89ac-408f-9d80-9cb72dbb02a6.mp4

**Comment by littleomar** [comment]
个人认为这个不是vant的问题，可以用一些手段避免这个问题，换种字体或者取消加粗等
本地测试选中类`.van-tab--active`字体大小从增加到31px时颜色会变正常，像是一个IOS渲染的问题吧，移动端safari chrome都有这问题

**Comment by chenjiahan** [comment]
楼上正解~
