### ISSUE TITLE
使用unplugin-vue-components/vite按需加载组件，无法控制组件css加载顺序

### ISSUE THREAD

**Issue by yasuomang** [youzan/vant#10730]
### 重现链接

https://codesandbox.io/s/admiring-poitras-ulfpw4

### Vant 版本

3.5.1

### 描述一下你遇到的问题。

修改主题变量时，应该无法控制css加载顺序，导致无法提升变量优先级，使覆盖失效
![image](https://user-images.githubusercontent.com/62331159/174558619-0c6c0b62-4b3b-4dbb-926a-2e2f482b20d1.png)

### 重现步骤

1. vite中配置按需引入组件
![image](https://user-images.githubusercontent.com/62331159/174559256-668ce3f6-d1b8-4b67-9145-9a74a21dcd46.png)

2. 在root节点下覆盖css变量van-primary-color

**Comment by chenjiahan** [comment]
unplugin-vue-components 确实有这个问题，建议直接全量引入组件样式好了，体积也不会大很多。

```js
import 'vant/lib/index.css';
```

**Comment by chenjiahan** [comment]
相关 issue：https://github.com/antfu/unplugin-vue-components/issues/327
