### ISSUE TITLE
[Bug Report] 关于Tab组件的问题

### ISSUE THREAD

**Issue by cloudmoonocus** [youzan/vant#10745]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/tab

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

我在使用tab组件时，先让它渲染，我这时是通过**v-show**让它隐藏了，当我获取后台数据完成后将v-show变为true，但是这时我**第一个**标签栏的数据是**正常**的，**其他标签栏却全没了**。
之后我一开始渲染数据就**不使用v-show，就恢复正常**了。
**（不是标签栏下面的颜色条，是标签里面的内容不显示）**

### 重现步骤

1.引入组件
2.标签写入内容
3.v-show先隐藏再展示
4.发现除第一个标签里的内容全消失

**Comment by chenjiahan** [comment]
请提供复现问题的 codesandbox 链接。
