### ISSUE TITLE
[Feature Request] 希望field,stepper组件支持null值

### ISSUE THREAD

**Issue by leewithyuan** [youzan/vant#10746]
### 这个功能解决了什么问题？
不输入的时候是null 输入的时候是输入后的值

其他框架，例如element ui plus 是支持默认值为null,不操作时就是null的

### 你期望的 API 是什么样子的？

希望支持

**Comment by chenjiahan** [comment]
建议空值使用空字符串。

Stepper 提供了 allow-empty 属性来进行设置。

**Comment by leewithyuan** [comment]
> 建议空值使用空字符串。
> 
> Stepper 提供了 allow-empty 属性来进行设置。

但是在强类型语言里面有问题
例如 golang里的*int32 空字符串就会解析失败，但是null是允许的

**Comment by chenjiahan** [comment]
这种状况需要前端再做一次转换了。

Vant 的输入框行为是和 HTML 原生输入框一致的，你可以试下把原生 input 标签的 value 设置为 null，会自动转换为空字符串。
