### ISSUE TITLE
[Bug Report] 组件使用 setup 开发后，打包出来的包存在子组件被渲染为原生组件问题

### ISSUE THREAD

**Issue by 17838963114wu** [youzan/vant#10741]
### 重现链接

https://github.com/17838963114wu/smForm

### Vant Cli 版本

4.0.2

### 描述一下你遇到的问题。

组件使用setup语法糖开发,组件中引入了子组件后，打包出来的组件代码是生成了_resolveComponent("sm-test")；这样就导致了子组件被加载成原生组件。
![image](https://user-images.githubusercontent.com/28945892/175447382-4529b8d6-a685-4d95-80dc-14f428339ba9.png)
`import { defineComponent as _defineComponent } from "vue";
import SmTest from "../sm-test/components/index";
const __vue_sfc__ = /* @__PURE__ */ _defineComponent({
  __name: "index",
  setup(__props, { expose }) {
    expose();
    const __returned__ = { SmTest };
    Object.defineProperty(__returned__, "__isScriptSetup", { enumerable: false, value: true });
    return __returned__;
  }
});
import { resolveComponent as _resolveComponent, createVNode as _createVNode, createTextVNode as _createTextVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue";
const _hoisted_1 = { class: "demo-button" };
const _hoisted_2 = /* @__PURE__ */ _createTextVNode(" \u6309\u94AE ");
function __vue_render__(_ctx, _cache) {
  const _component_sm_test = _resolveComponent("sm-test");
  return _openBlock(), _createElementBlock("div", _hoisted_1, [
    _hoisted_2,
    _createVNode(_component_sm_test)
  ]);
}
__vue_sfc__.render = __vue_render__;
var stdin_default = __vue_sfc__;
export {
  stdin_default as default
};
`

### 重现步骤

1.克隆项目
2.执行 yarn build
3. 将组件按需引入到项目

**Comment by littleomar** [comment]
您能再详细描述一下吗？我把项目down下来 认为生成  `_resolveComponent("sm-test")；`是正常逻辑

**Comment by chenjiahan** [comment]
@Alanscut 感觉在编译 script setup 时，没有正确处理 .vue 组件引用，有空可以看下这个问题~

**Comment by CWZJ** [comment]
@chenjiahan 好的，我来处理

**Comment by Alanscut** [comment]
@chenjiahan 好的，我看一下怎么解决
