### ISSUE TITLE
[Bug Report] van-popup如果使用:value，close事件无法被触发

### ISSUE THREAD

**Issue by wenduli** [youzan/vant#10756]
### 重现链接

无

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

vue2 使用van-popup不适用v-model用:value之后，@close事件无法触发，@open可以使用。

### 重现步骤

<van-popup :value="show" closeable close-icon="close" position="bottom" :style="{ height: '65%'}" @close="handleClose" />

**Comment by Alanscut** [comment]
close事件是关闭弹出层时触发，你这样写并没有关闭弹出层

**Comment by wenduli** [comment]
> 关闭事件是弹出层时触发，你这样写并关闭没有弹出层

close事件里不应该去修改show的值为false么，但是我这边试的是如果写成:value，就close事件就直接无法触发了，@click-overlay这些是可以的。

**Comment by Alanscut** [comment]
不是的哈，close事件里不应该去修改show的值为false，value控制弹出层的关闭，当value为false才触发的close事件，click-overlay事件是点击遮罩层的时候触发的，文档里面有写
https://youzan.github.io/vant/v2/#/zh-CN/popup#events
