### ISSUE TITLE
uploader 无法在小程序 web-view 使用上传功能

### ISSUE THREAD

**Issue by sunchir** [youzan/vant#10762]
### 重现链接

http://vant-contrib.gitee.io/vant/#/zh-CN/uploader

### Vant 版本

3.4.7

### 描述一下你遇到的问题。

在微型小程序嵌入webview 然后使用上传功能无法弹出图片选择，浏览器可以正常使用

### 重现步骤

在微型小程序嵌入webview 然后使用上传功能无法弹出图片选择

### 设备/浏览器

微信 8.0.23 webview

**Comment by chenjiahan** [comment]
应该是小程序本身的问题，可以用原生 input type=file 试一下。另外也可以考虑用微信 sdk 提供的 API 进行上传
