### ISSUE TITLE
[Bug Report] 有关popup和index-bar结合使用的问题

### ISSUE THREAD

**Issue by mhxy13867806343** [youzan/vant#10761]
### Reproduction Link

https://codesandbox.io/s/vant-3-issue-template-forked-9who7d?file=/src/App.vue

### Vant Version

^3.5.1

### Describe the Bug

有关popup和index-bar结合使用后，当高度为100%时，无法进行滚动操作了 

### Reproduce Steps

有关popup和index-bar结合使用后，当高度为100%时，无法进行滚动操作了 

### Device / Browser

mac12.3.1. edge103

**Comment by littleomar** [comment]
1. `<van-index-bar :index-list="countrycodeList"></van-index-bar>`这里的`countrycodeList`应该是字符串列表
2. `<van-index-bar :index-list="countrycodeList">
        <van-index-anchor
          :index="item.label"
          v-for="(item, index) in countrycodeList"
          :key="index"
          >{{ item.label }}
          <div v-for="(a1, b1) in item.countryList" :key="b1">
            <van-cell :title="a1.zh"></van-cell>
          </div>
        </van-index-anchor>
      </van-index-bar>` 应该是 `van-index-anchor`使用不当导致滚动问题的吧，请参考官方文档
3. `popup`中的`transferm`会导致`IndexBar`中`fixed`布局失效导致异常，如果`popup`全局使用建议将其`style`设置为`{
          width: '100%',
          height: '100%',
          position: 'fixed',
          transform: 'unset',
          left: 0,
          top: 0
        }`

**Comment by mhxy13867806343** [comment]
@littleomar 您，可以测试下，数据在上面的连接中的data.js里面，你可以这么做加个按钮 ，然后用我那个代码测试，会出现，右边那几个会随着 popup向上滚动，并且滚动的时候 van-index-anchor它会出现空白，如果不用popup，放在一个页面上，发现正常的情况

**Comment by mhxy13867806343** [comment]
@littleomar 我试试您的方案
