### ISSUE TITLE
打包后样式错误

### ISSUE THREAD

**Issue by Yudongxin** [youzan/vant#10766]
### 重现链接

https://gdodc.zone139.com/meeting-h5/#/home/index

### Vant 版本

3.5.1

### 描述一下你遇到的问题。

toast的样式在本地时候正常,打包后却用的白色的背景--van-popup-background-color

### 重现步骤

打开页面即可请求

### 设备/浏览器

所有栏

**Comment by huzhujiang2014** [comment]
+1

**Comment by huzhujiang2014** [comment]
+ 1 本地也不正常，-van-popup-background-color 覆盖导致了  van-toast的background不生效

**Comment by Alanscut** [comment]
我这边试了是正常的
![image](https://user-images.githubusercontent.com/21104054/176983618-c53cb290-2daa-400c-bccd-84e558fa483c.png)

**Comment by kerry0955** [comment]
![image](https://user-images.githubusercontent.com/40793942/177740031-9ea497f3-d300-4899-9f32-b5d86d536d7f.png)

我的是这种样子

**Comment by JakeLaoyu** [comment]
能否提供一个复现demo源码。
