### ISSUE TITLE
Uploader 组件 after-read 无法取得 上传文件名。

### ISSUE THREAD

**Issue by highmore** [youzan/vant#1076]
代码如下：
`	<van-uploader accept="image/gif, image/jpeg, image/*" :before-read="onStartReadFile" :after-read="onReadFile">
		<van-icon name="photograph"></van-icon>
	</van-uploader>`
`        methods: {
			onReadFile(file) {
				console.log('File: '+JSON.stringify(file.file));
				this.upload_picture = file.content;
			},
			onStartReadFile() {
				this.$toast.loading({
					mask	: true,
					message	: '上传中...'
				});
				return true;
			}
        }`

onReadFile 结果 "file:{}"

**Comment by junwei1114** [comment]
安卓调取图库的时候  直接点击图片  还没等点击确定按钮就直接上传了,

**Comment by chenjiahan** [comment]
@highmore File 对象中是包含 name 字段的
@junwei1114 这个可以自己研究下有没有属性能控制

**Comment by Safisun** [comment]
console.log可以打印出file，但是放formdata里面就没有值，debugger状态下file会闪下才出来
