### ISSUE TITLE
[Bug Report] popup设置get-container="body" 遇到并列v-for时无法重新渲染数组

### ISSUE THREAD

**Issue by zjunhui** [youzan/vant#10760]
### 重现链接

https://x9ncpv.csb.app/

### Vant 版本

2.12.31

### 描述一下你遇到的问题。
`<div v-for="item in testArr" :key="item">{{ item }}</div>`
`<van-popup v-model="show" get-container="body">vant弹出层</van-popup>`

也就是popup紧邻v-for时，且get-container="body" ，改变数组不会触发渲染。
如果是vue的问题，能否方便告知下原因?

### 重现步骤

动态改变被循环的数组即可

**Comment by littleomar** [comment]
测试链接：https://codesandbox.io/s/vant-3-issue-template-forked-dybhok?file=/src/App.vue
这个应该属于vant的一个bug，如果组件设置参数`get-container="body"`时vant会直接操作dom并把相关dom插入到body中，这样会导致vue框架渲染异常，异常情况具体如下：
首先在向数组中push元素时候，vue会根据变化的数据生成新的vnode，这里就拿上述例子进行探讨，push后新旧vnode对比如下，可以看出来vnode的生成是没有问题的。
![WX20220629-175039@2x_edit](https://user-images.githubusercontent.com/42726829/176411003-d04dafdc-4e22-4517-badf-934ab1d35cd7.png)

下一步根据新旧vnode对比patch的过程，在对`testArr`中新push的元素进行渲染时执行的以下逻辑：
<img width="1031" alt="WX20220629-181314@2x" src="https://user-images.githubusercontent.com/42726829/176412318-6071b4d0-13c1-47c2-91e7-568b91dab071.png">
然而此时的插入参考节点已经被 vant组件添加到body下面了，由于参考节点找不到所以新元素插入失败。
<img width="619" alt="WX20220629-181622@2x" src="https://user-images.githubusercontent.com/42726829/176413062-9a9c7380-6af9-4264-8a2e-8212a2f17a53.png">
vant会在popup组件`mounted`的时候的时候执行dom操作逻辑：
![image](https://user-images.githubusercontent.com/42726829/176413252-6014e81e-83bd-4090-b5d8-c5e94a967171.png)

以上就是bug出现的原因，表述可能不清楚，如有不理解的地方请指出

**Comment by zjunhui** [comment]
@littleomar 很清楚了，感谢解惑。也就是更新以popup注释为参考节点为都会存在问题，难怪我尝试给v-for或者popup包裹div可以避免这个问题。非常感谢

**Comment by KAWATAAAAAA** [comment]
🙏🙏🙏 今天发现这个问题，还好找到这个bug解决了，感谢， 就是不知道为什么要这么设计，直接把同层的全传送走了，感觉直接在组件里边 把this.$el 给挂到body上就好了
