### ISSUE TITLE
Icon图标组件使用本地字体文件无效,还是引用 yzcdn.cn 域名下的字体文件

### ISSUE THREAD

**Issue by Saber-tgb** [youzan/vant#1077]

**Comment by ansonhorse** [comment]
@Saber-tgb 请问你是怎么引用的，我根据官方文档引入，但并没有成功[请看#1008](https://github.com/youzan/vant/issues/1008)

**Comment by ansonhorse** [comment]
@Saber-tgb @chenjiahan @cookfront 
版本：1.1.3，发现`vant/lib/vant-css/index.css`里引用font的url是`https://img.yzcdn.cn/zanui/icon/vant-icon-03d6f2.ttf`，而`vant/lib/vant-css/icon-local.css`里的url是`vant-icon-4c3245.ttf`，实际上，本地只有`vant-icon-03d6f2.ttf`这个文件，所以导致我遇到的这个问题[#1008](https://github.com/youzan/vant/issues/1008)

**Comment by chenjiahan** [comment]
@ansonhorse 感谢反馈，近期会看一下这个问题

**Comment by chenjiahan** [comment]
已在 1.1.4 版本修复

**Comment by chenjiahan** [comment]
经查证是 yarn 缓存的问题，删除 yarn.lock 和 node_modules 并重新安装，就正常了

**Comment by tinaxu-come-on** [comment]
官方可以给个详细的配资例子吗，删除了yarn.lock 和 node_modules 依旧不行，还是引入的是cdn的字体

**Comment by tinaxu-come-on** [comment]
> 经查证是 yarn 缓存的问题，删除 yarn.lock 和 node_modules 并重新安装，就正常了

官方可以给个详细的配资例子吗，删除了yarn.lock 和 node_modules 依旧不行，还是引入的是cdn的字体

**Comment by chenjiahan** [comment]
@tinaxu-come-on 最新版没这个问题了，已经切到到本地字体，不再依赖 yzcdn.cn。

你可以升级 Vant 版本试一下。
