### ISSUE TITLE
useCustomFieldValue官网示例不生效

### ISSUE THREAD

**Issue by itsmyturn** [youzan/vant#10770]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-28s6in?file=/src/App.vue

### Vant 版本

3.5.1

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/11573322/176996511-0172aa79-62f6-4280-b3cd-85839fc8dd75.png)
和官网写的一样，表单提交的时候并没有取到my-field的值

### 重现步骤

点击提交，看控制台打印没有取到值

### 设备/浏览器

chrome

**Comment by Alanscut** [comment]
没有注册组件
```
import MyComponent from '../myComponent.vue';
export default {
  name: "App",
  components: {
    MyComponent,
  },
  methods: {
    onSubmit(values) {
      console.log(values);
    },
  },
};
```
