### ISSUE TITLE
[Bug Report] Vant 2.x 使用 Form rules 校验 Field 的 input 插槽无效

### ISSUE THREAD

**Issue by xiafeifei** [youzan/vant#10789]
### 重现链接

> https://github.com/xiafeifei/vant_2.x_issue/tree/master

### Vant 版本

> vant 2.12.48

## Form Rules 校验BUG

> 编写表单校验时，发现 form 组件无法校验 field 的 input 插槽 value。

<img src="https://github.com/xiafeifei/vant_2.x_issue/raw/master/01.png">
<img src="https://github.com/xiafeifei/vant_2.x_issue/raw/master/04.png">

## 依据

> 根据官方文档描述会使用子组件的 vlaue，实际子组件是有值的。

<img src="https://github.com/xiafeifei/vant_2.x_issue/raw/master/02.png">

## 个人分析

> 分析官方 vant 源码后发现 field 源码 computed 的 formValue 有个 if 判断逻辑始终为空，不清楚是否此处问题导致。

<img src="https://github.com/xiafeifei/vant_2.x_issue/raw/master/03.png">

### 重现步骤

> 1.点击提交按钮触发 Form submit

### 设备/浏览器

> chrome

**Comment by xiafeifei** [comment]
上面问题，已经个人处理了。

# 解决思路

> 自定义input插槽组件混入 mixin

```js
import { FieldMixin } from 'vant/lib/mixins/field.js'
```

# 个人建议

> 此处写到文档中，如果不是官方源码很难知道需要这样处理。

**Comment by chimmyKyu** [comment]
请问怎么解决的，是子组件中import { FieldMixin } from 'vant/lib/mixins/field.js'; mixins:{FieldMixin }吗？

**Comment by xiafeifei** [comment]
是的，因为有段时间，我现在也记不清具体细节了，我记得还需要在data属性里有个 value 节点，你可以看看官方的 这个mixin 代码。

> 请问怎么解决的，是子组件中import { FieldMixin } from 'vant/lib/mixins/field.js'; mixins:{FieldMixin }吗？
