### ISSUE TITLE
[Bug Report] dialog通过函数调用方法无法使用，函数式api没有暴露出来

### ISSUE THREAD

**Issue by yanbowe** [youzan/vant#10792]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-8159jp?file=/src/App.vue

### Vant 版本

4.0.0-alpha.4

### 描述一下你遇到的问题。

dialog函数式api无法使用
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/43030980/177303256-4e8a1ebb-d2a2-41ec-a8ae-e2be0fcdc30d.png">

### 重现步骤

showDialog) is not a function

**Comment by Alanscut** [comment]
dialog最新的更新还没发版，可以先参考 [vant 3 的文档](https://youzan.github.io/vant/#/zh-CN/dialog)

**Comment by chenjiahan** [comment]
这块确实还没发版，文档站点自动更新了，所以出现了偏差。

本周会处理下。

**Comment by yanbowe** [comment]
收到

**Comment by zaxlct** [comment]
还没解决呢。。。

**Comment by chenjiahan** [comment]
已发布 4.0.0-beta.0 版本，升级后可以使用 v4 文档中的最新 API。

**Comment by xieguo** [comment]
> 
这个4.0.0-beta.0 版本还是没有解决问题，import {showDialog} from 'vant'; 后，在 mounted函数中直接：showDialog('message'); 直接提示找不到样式文件：。。。 /node_modules/vant/es/show-dialog/style" from "src\App.vue". Does the file exist?  查看 node_nodules/vant/es/目录，也没有发现有show-dialog目录。
![image](https://user-images.githubusercontent.com/12163194/182518141-f5e41d2b-161f-4947-868c-b1b362faa1b3.png)
![image](https://user-images.githubusercontent.com/12163194/182518255-06f02bee-f71c-4556-b89e-e084833c1f07.png)

**Comment by xieguo** [comment]
> > 
> 
> 这个4.0.0-beta.0 版本还是没有解决问题，import {showDialog} from 'vant'; 后，在 mounted函数中直接：showDialog('message'); 直接提示找不到样式文件：。。。 /node_modules/vant/es/show-dialog/style" from "src\App.vue". Does the file exist? 查看 node_nodules/vant/es/目录，也没有发现有show-dialog目录。 ![image](https://user-images.githubusercontent.com/12163194/182518141-f5e41d2b-161f-4947-868c-b1b362faa1b3.png) ![image](https://user-images.githubusercontent.com/12163194/182518255-06f02bee-f71c-4556-b89e-e084833c1f07.png)

@chenjiahan @zaxlct

**Comment by xieguo** [comment]
> 这块确实还没发版，文档站点自动更新了，所以出现了偏差。
> 
> 本周会处理下。

都一个月了，还没处理好？

**Comment by chenjiahan** [comment]
https://vant-ui.github.io/vant/v4/#/zh-CN/migrate-from-v3#yi-chu-babel-plugin-import

**Comment by xieguo** [comment]
> https://vant-ui.github.io/vant/v4/#/zh-CN/migrate-from-v3#yi-chu-babel-plugin-import

![image](https://user-images.githubusercontent.com/12163194/182558032-df5f8f28-a78c-4ece-9064-dce7bd4e06a0.png)

使用了 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 插件，所有样式都没有了，我没有全局引入样式，是否可以给过示例代码

**Comment by xieguo** [comment]
> > https://vant-ui.github.io/vant/v4/#/zh-CN/migrate-from-v3#yi-chu-babel-plugin-import
> 
> ![image](https://user-images.githubusercontent.com/12163194/182558032-df5f8f28-a78c-4ece-9064-dce7bd4e06a0.png)
> 
> 使用了 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 插件，所有样式都没有了，我没有全局引入样式，是否可以给过示例代码

@chenjiahan @zaxlct

**Comment by onthedesk** [comment]
还没解决吗？
main.js中引用了index.css但是 Module not found: Error: Can't resolve 'vant/es/show-fail-toast/style'

**Comment by cnsimplo** [comment]
uniapp 框架,在H5模式下弹出正常 , 在Android与iOS真机运行的时候无法弹出.
