### ISSUE TITLE
[Bug Report] 不支持 pnpm workspace

### ISSUE THREAD

**Issue by squallliu** [youzan/vant#10793]
### Vant Cli 版本

2.x、3.x

### 描述一下你遇到的问题。

模块之间依赖，例如
```json
{
  "dependencies": {
    "moduleA": "workspace:^"
  }
}
```
在 install dependencies 阶段会失败
看了下源码，install dependencies 是使用的 npm install，它并不能识别 "workspace:" 写法
建议提供配置能够跳过 install dependencies，它并不应该是 cli 的职责，应该由外部构建脚本决定什么时候 install dependencies

**Comment by chenjiahan** [comment]
Vant Cli v4 支持了 pnpm。

v3 已经不再维护了哈，感兴趣可以提 PR 到 2.x 分支上进行支持。
