### ISSUE TITLE
运行jest或vitest测试时，报错TypeError: Unknown file extension ".css" for node_modules\vant\es\style\base.css

### ISSUE THREAD

**Issue by liuyao552** [youzan/vant#10791]
运行jest或vitest测试时，报错TypeError: Unknown file extension ".css" for node_modules\vant\es\style\base.css
我不知道时jest配置问题还是vant3问题，但换成其他ui库并没有报这个错
该如何解决？

**Comment by Alanscut** [comment]
请提供复现问题的 codesandbox 链接

**Comment by chenjiahan** [comment]
@Alanscut 给你添加了 issue 权限~ 后续处理完成的 issue 可以直接 close 哈

**Comment by Alanscut** [comment]
好的~

**Comment by jerrywu001** [comment]
我发现3.4.9是可以的
