### ISSUE TITLE
vant cli 引入 element-ui 报错

### ISSUE THREAD

**Issue by liuxsen** [youzan/vant#10808]
### 重现链接

x

### Vant Cli 版本

2.11.7

### 描述一下你遇到的问题。

需要基于element-ui 封装业务组件

1. 引入element-ui 报错，我是在组件script部分引入的；

**没看到哪里还可以引入，希望官方能给个提示，在哪里引入第三方组件库**

### 重现步骤

1. 没其他改动，就引入了element-ui
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/12598696/178156970-89518cc4-beeb-4a50-8310-c4d1015e0278.png">

3.  报错信息1
<img width="846" alt="image" src="https://user-images.githubusercontent.com/12598696/178156987-04bce00b-7713-4c8a-8ae8-d9bb6fe62b4d.png">

4.  报错信息2
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/12598696/178157017-94739a00-cfd9-4b4f-876c-df58d42dfec7.png">

**Comment by chenjiahan** [comment]
Vant Cli 2.x 已经不再维护了，如果有相关需要可以提 PR 哈。
