### ISSUE TITLE
Tab 标签页开启粘性布局，新增触摸屏幕界面往下滚动功能

### ISSUE THREAD

**Issue by mr-hmf** [youzan/vant#10809]
### 这个功能解决了什么问题？

<van-tabs v-model:active="active" scrollspy sticky>
  <van-tab v-for="index in 8" :title="'选项 ' + index">
    内容 {{ index }}
  </van-tab>
</van-tabs>

当前配置只能通过点击标签栏切换到下一页，无法实现触摸手机屏幕往下滚动时也能切换到下一页。希望实现该功能。

### 你期望的 API 是什么样子的？

<van-tabs v-model:active="active" scrollspy sticky touchScroll>
  <van-tab v-for="index in 8" :title="'选项 ' + index">
    内容 {{ index }}
  </van-tab>
</van-tabs>

**Comment by chenjiahan** [comment]
可以看一下文档中的 滚动导航 示例，应该符合你描述的场景。

**Comment by mr-hmf** [comment]
<van-tabs v-model:active="active" scrollspy sticky>
  <van-tab v-for="index in 8" :title="'选项 ' + index">
    内容 {{ index }}
  </van-tab>
</van-tabs>
就是按照文档设置了，当前配置只能通过点击标签栏切换到下一页，无法实现触摸手机屏幕往下滚动时也能切换到下一页。一开始以为是未实现该功能，难道是bug?

**Comment by chenjiahan** [comment]
没生效的话可能是 bug，可以检查下是不是使用了 better-scroll 之类的滚动库，或是其他原因导致组件对滚动检测不生效。
