### ISSUE TITLE
Tab 标签页并不能通过v-modal来设置选中项，不知道文档是否有问题

### ISSUE THREAD

**Issue by MartinLongYW** [youzan/vant#1080]
我看官网的右侧示例可以实现，但根据示例左侧的代码并不能实现这个功能，是否文档有问题，麻烦处理一下。

**Comment by 18679452286** [comment]
同学， 找到解决方案了吗 ？我这边也碰到了同样的问题

**Comment by 18679452286** [comment]
文档写错了，，  把v-model 改成  :active   ;  应该就可以了

**Comment by leileizhao** [comment]
> 文档写错了，， 把v-model 改成 :active ; 应该就可以了

麻烦，请教一下！后台返回数据赋值给v-for，为啥tab的title的offset不居中呢 ？
