### ISSUE TITLE
[Bug Report] ConfigProvider无法修改Popover的样式

### ISSUE THREAD

**Issue by gdutwyg** [youzan/vant#10812]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-m64x27?file=/src/App.vue

### Vant 版本

3.5.1

### 描述一下你遇到的问题。

使用ConfigProvider想修改Popover的样式，但是设置了宽度和背景色后，还是没有生效。

### 重现步骤

点击复现链接的icon，可以看到Popover的背景色和宽度都没改变。

### 设备/浏览器

chrome浏览器即可。

**Comment by thgames908** [comment]
popover 挂载在body上, 怎么用:deep覆盖样式呀

**Comment by chenjiahan** [comment]
ConfigProvider 只能影响子组件的样式哈。

你可以在 Popover 上设置 teleport 属性，通过 teleport 移动到 ConfigProvider 的子节点。
