### ISSUE TITLE
vant 3.3.2. Toast.loading. forbidClick属性在iphone XR上无效，系统版本IOS 14.6，事件能穿透遮罩层

### ISSUE THREAD

**Issue by LiHuZhou** [youzan/vant#10816]
### 重现链接

公司项目，不方便发连接

### Vant 版本

3.3.2

### 描述一下你遇到的问题。

. Toast.loading. forbidClick属性在iphone XR上无效，系统版本IOS 14.6，事件能穿透遮罩层，其他手机正常

### 重现步骤

弹出loading。但是loading下面的按钮可以点击，iphone XR上，系统版本IOS 14.6，其他手机正常

**Comment by chenjiahan** [comment]
目前 forbidClick 是通过 CSS 的 `pointer-events: none` 样式来实现的，如果该 CSS 在特定的系统上不生效，说明是特定系统的 bug，影响面有限，组件层面不考虑做兼容哈。
