### ISSUE TITLE
[Bug Report] 关于nav-bar的getBoundingClientRect().height不能准确获取高度的问题

### ISSUE THREAD

**Issue by zhang1024899756** [youzan/vant#10815]
### 重现链接

https://stackoverflow.com/questions/64891541/get-safe-area-inset-bottom-on-page-load%E3%80%82

### Vant 版本

2.12.48

### 描述一下你遇到的问题。

看到源码里面使用了100的延时，在实际真机应用中仍然不能准确获取高度，会出现有时不能获取的情况
建议可以使用多次询问进行高度纠正
![image](https://user-images.githubusercontent.com/22297910/178455954-a8d3fe1a-ed1e-45df-91ea-d575ac8172e7.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/22297910/178455954-a8d3fe1a-ed1e-45df-91ea-d575ac8172e7.png)

### 设备/浏览器

部分ios机型

**Comment by Adaer** [comment]
感觉使用nextTick更靠谱一些，特别是在异步的情况下

**Comment by chenjiahan** [comment]
nextTick 没法处理这个场景，属于系统 bug ，返回正确值的时间并不固定，参见 https://github.com/youzan/vant/issues/10131

多次询问是可以解决此问题。
