### ISSUE TITLE
[Bug Report] swipe滚动文字时设置width不适应ipad

### ISSUE THREAD

**Issue by yan7011** [youzan/vant#10810]
### 重现链接

https://gitee.com/yanjj/tp-test/wikis/vant%E4%B8%ADswipe%E8%AE%BE%E7%BD%AE%E5%AE%BD%E5%BA%A6%E9%97%AE%E9%A2%98?sort_id=5803274

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

当使用Swipe滑动文字在设置:width的时候，出现ipad屏幕大的设置不兼容，因为我这边使用的是rem这种模式，默认vant给的是px，而且哪怕使用了postcss-px2rem-exclude进行转化，也是不行的，应为在swipe中设置的是行内style，动态给van-swipe-item赋值width。建议官方能优化此模块。

### 重现步骤

                    <van-swipe :show-indicators="false" :width="50" :loop="false">
                        <van-swipe-item>推荐</van-swipe-item>
                        <van-swipe-item>国际</van-swipe-item>
                        <van-swipe-item>国内</van-swipe-item>
                        <van-swipe-item>体育</van-swipe-item>
                        <van-swipe-item>本地</van-swipe-item>
                        <van-swipe-item>娱乐</van-swipe-item>
                        <van-swipe-item>军事</van-swipe-item>
                        <van-swipe-item>互联网</van-swipe-item>
                        <van-swipe-item>科技</van-swipe-item>
                        <van-swipe-item>生活</van-swipe-item>
                        <van-swipe-item>汽车</van-swipe-item>
                        <van-swipe-item>财经</van-swipe-item>
                        <van-swipe-item>房产</van-swipe-item>
                        <van-swipe-item>时尚</van-swipe-item>
                        <van-swipe-item>教育</van-swipe-item>
                        <van-swipe-item>人文</van-swipe-item>
                        <van-swipe-item>图片</van-swipe-item>
                    </van-swipe>

### 设备/浏览器

ipad等大屏幕移动设备

**Comment by chenjiahan** [comment]
在设置 Swipe 组件的 width 的时候，你可以基于当前的屏幕尺寸来设置对应的值（映射比例可以和 rem 一样），而不是设置固定的 50。

**Comment by yan7011** [comment]
> 在设置 Swipe 组件的 width 的时候，你可以基于当前的屏幕尺寸来设置对应的值（映射比例可以和 rem 一样），而不是设置固定的 50。

这个是vant3中动态加在内联style样式的，并且给的是px，对于rem来说，特别是ipa这种大屏幕，根本没有比例映射(可以看我给的上面链接)，比如XR苹果手机和ipa，他们尺寸都不一样的。如果vant3中那个:width属性可以设置rem就完美了，可惜只能是int.
