### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by wmy94827** [youzan/vant#10814]
### 重现链接

无

### Vant 版本

4.0.0-alpha.4

### 描述一下你遇到的问题。

<img width="947" alt="image" src="https://user-images.githubusercontent.com/25683492/178441175-df43462d-4559-4058-8a3e-b60edd056782.png">
4.0.0-alpha.4版本按照文档显示没有导出 showToast 
还是需要按照3里面的写法么，好像和文档不一致。

### 重现步骤

<img width="947" alt="image" src="https://user-images.githubusercontent.com/25683492/178441175-df43462d-4559-4058-8a3e-b60edd056782.png">
<img width="389" alt="image" src="https://user-images.githubusercontent.com/25683492/178441492-4007fd67-2a76-47ec-8add-aff0f7db1fa0.png">

**Comment by Adaer** [comment]
文档有这样写吗？ 文档里 都是 导出 Toast

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/10792

**Comment by wmy94827** [comment]
> 参见 #10792

好的，我先降级到3吧~

**Comment by chenjiahan** [comment]
不用降级的，先按 Vant 3 文档里的用法，可以继续使用的
