### ISSUE TITLE
[Bug Report] Uploader组件 demo 错误

### ISSUE THREAD

**Issue by xujintai123** [youzan/vant#10813]
### 重现链接

https://vant-ui.github.io/vant/v2/#/zh-CN/uploader 

### Vant 版本

2.12.48

### 描述一下你遇到的问题。

https://vant-ui.github.io/vant/v2/#/zh-CN/uploader 
### v2.12.48的demo错误
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/66779465/178250750-82f289c4-5001-48c9-9527-b1cf9536b6ac.png">

### 重现步骤

https://vant-ui.github.io/vant/v2/#/zh-CN/uploader 

### 设备/浏览器

*

**Comment by chenjiahan** [comment]
感谢反馈，已修正
