### ISSUE TITLE
vant从3.4.8更新到3.5.2后编译的时候就会出现常量没有初始化问题

### ISSUE THREAD

**Issue by wlinglinux** [youzan/vant#10817]
### 重现链接

https://testjianye.hd.weibo.com/site/?id=2557#/

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

编译报错

### 重现步骤

把vant库文件更新为3.5.2后将vite.config.ts里的配置文件按照文档那样配置后Components({
        resolvers: [VantResolver()],
      }),就会报错，在store中引入常量就会报错
Cannot access 'GSAP_EASE_TYPES_MAP' before initialization

**Comment by wlinglinux** [comment]
我又试了，3.4.9我使用的是vite-plugin-style-import这个插件的createStyleImportPlugin配置，运行项目没有问题，但是到3.5.0这个配置就会报错了无法引用vant中的嘴贱，只能使用文档中的配置，但是使用文档配置后常量pinia(store) 中的常量引用就会报错；说常量没有初始化

**Comment by chenjiahan** [comment]
vite-plugin-style-import 插件现在已经不维护了，因为不推荐使用哈。

建议参考最新官方文档，使用 unplugin-vue-components 来进行按需引入。

**Comment by wlinglinux** [comment]
我就是想使用最新的版本官方推荐的VantResolver，然后在浏览器预览的时候所有的常量都不能初始化了，不知道是什么原因
![31658199824_ pic_hd](https://user-images.githubusercontent.com/286261/179658394-79bef376-8123-427b-8a7c-52826f6af529.jpg)

**Comment by wlinglinux** [comment]
使用vant4.9.0就没有问题，常量都可以出初始化的
![image](https://user-images.githubusercontent.com/286261/179658585-38190020-f913-443b-a6fc-42212cec0d79.png)

**Comment by wlinglinux** [comment]
我不使用VantResolver这个，整个vant都引入就没有问题了，常量编译都是正常的，是VantResolver有问题吗？
