### ISSUE TITLE
选择器可以增加一个多选的功能么

### ISSUE THREAD

**Issue by 719257898** [youzan/vant#10826]
### 这个功能解决了什么问题？

选择器多选可以满足一些需求！

### 你期望的 API 是什么样子的？

1

**Comment by 719257898** [comment]
对于一个后端接口仔来说 遇到这种需求完全开摆了

**Comment by chenjiahan** [comment]
选择器的交互是不支持多选的哈，你可以看一下 TreeSelect 组件能否满足你的需求。

**Comment by 719257898** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 719257898** [comment]
> 选择器的交互是不支持多选的哈，你可以看一下 TreeSelect 组件能否满足你的需求。

OK,感谢
