### ISSUE TITLE
[Feature Request] 建议出一个工具函数，用于方便获取地区码和名称

### ISSUE THREAD

**Issue by liyuan1125** [youzan/vant#10820]
### 这个功能解决了什么问题？

此函数用于解决只有一个地区码的时候，方便获取所有地区码与名称
例如现在有一个areaCode：110106,
想在获取省，市，区的名称和编码

### 你期望的 API 是什么样子的？

todo

**Comment by chenjiahan** [comment]
感觉不是很有必要哈，这个逻辑挺简单的，自行实现一下就好。

假设区的 areaCode 是 110106，那么市对应的编码就是 110100（后两位变 0），省的编码是 110000（后四位变 0）

拿到编码后，可以直接从 areaList 中读取对应的名称。
