### ISSUE TITLE
[Bug Report] 通过yarn create vant-cli-app命令创建出来的项目无法识别自定义组件

### ISSUE THREAD

**Issue by dyh333** [youzan/vant#10829]
### 重现链接

https://github.com/dyh333/biz-vant

### Vant Cli 版本

4.0.3

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/1221313/179483630-1d5045e6-84ff-4fb7-8cf1-b891126d3436.png)
如图，demo-button未被正确识别出来，导致样式丢失。

### 重现步骤

1. 克隆仓库
2. pnpm install
3. pnpm run dev
4. 打开localhost:3000

**Comment by chenjiahan** [comment]
demo/index.vue 里需要加一段注册组件的逻辑，我们修正下模板

```html

<script setup>
import DemoButton from '../index.vue';
</script>
```
