### ISSUE TITLE
PasswordInput 密码输入框在ios上双击数字键会放大缩小

### ISSUE THREAD

**Issue by labike** [youzan/vant#10832]
### 重现链接

无

### Vant 版本

3.2.x

### 描述一下你遇到的问题。

PasswordInput 密码输入框在ios上双击数字键会自动放大缩小

### 重现步骤

双击密码框上的数字键会自动放大缩小密码框

### 设备/浏览器

ios safari

**Comment by chenjiahan** [comment]
这个和组件库没关系，可以在 HTML 里加上 viewport 设置来解决

```html
<meta
  name="viewport"
  content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, viewport-fit=cover"
/>
```
