### ISSUE TITLE
Uploader 在ios低版本下无法点击拍照和相册，点击文件后整个页面卡死

### ISSUE THREAD

**Issue by 18247033708** [youzan/vant#10835]
### 重现链接

https://youzan.github.io/vant/v2/#/zh-CN/uploader

### Vant 版本

^2.12.0

### 描述一下你遇到的问题。

Uploader 在ios低版本下无法点击拍照和相册，点击文件后整个页面卡死

### 重现步骤

加个组件点击Uploader 
手机 ：iphone Xs   软件版本12.3

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/180600374-d9a1f318-0582-4f8c-a24a-c25621c5b0d3.png)
