### ISSUE TITLE
Dialog.alert 在 ts 中缺少类型

### ISSUE THREAD

**Issue by toplyb** [youzan/vant#10838]
### 重现链接

https://youzan.github.io/vant/v2/#/zh-CN/dialog

### Vant 版本

2.8.6

### 描述一下你遇到的问题。

在 ts 中使用 `Dialog.alert(options)` 的时候, `options` 的类型为 `DialogOptions`, 但是 `DialogOptions` 中没有定义 `theme` 属性, 导致如下代码会报错
```js
Dialog.alert({
  message: '弹窗内容',
  theme: 'round-button',
}).then(() => {
  // on close
});
```
<img width="802" alt="image" src="https://user-images.githubusercontent.com/38663116/180375679-b801540b-934f-438b-ae4f-df2ebea91b8e.png">

### 重现步骤

在 ts 中使用 `Dialog.alert`
```js
Dialog.alert({
  message: '弹窗内容',
  theme: 'round-button',
}).then(() => {
  // on close
});
```

**Comment by sztu-wtr** [comment]
`npm install vant@v3 -S -D`即可
