### ISSUE TITLE
[Feature Request] vant cli 2.11.11如何指定发布到npm私服

### ISSUE THREAD

**Issue by zhiyouai** [youzan/vant#10834]
### 这个功能解决了什么问题？

通过create-vant-cli-app搭建的工程，vantCli 2.11.11版本。看了下cli相关的配置，publishConfig指定的registry是https://registry.npmjs.org/。如果想发布到自己公司私服，应如何操作？

### 你期望的 API 是什么样子的？

release命令支持配置发布地址

**Comment by chenjiahan** [comment]
@vant/cli v2 已经不维护了，有需求的话可以自行提 PR 喔
