### ISSUE TITLE
请问一下 van-popover 的offset是否支持动态配置

### ISSUE THREAD

**Issue by cplcurry3035** [youzan/vant#10833]
### 重现链接

无

### Vant 版本

2.0+

### 描述一下你遇到的问题。

现在是使用了popover 可是遇到了 我在底部使用popover 出现了 被挡住了的情况，但是我采用动态设置placement由left-start为left-end，可是offset一直设置不成功，有什么办法 在底部的时候怎么不被挡住吗

### 重现步骤

底部点击按钮出现popover的时候被挡住 ，希望是它一整个都在可视区域，而不是需要滚动页面才可以看到，这样以为交互不好

### 设备/浏览器

所有

**Comment by chenjiahan** [comment]
Vant 2 不支持哈，Vant 3 下个版本会支持。
