### ISSUE TITLE
[Bug Report] 按需加载启动报错

### ISSUE THREAD

**Issue by Ttou** [youzan/vant#10836]
### 重现链接

https://github.com/Ttou/vant-issue-0720.git

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

<img width="918" alt="image" src="https://user-images.githubusercontent.com/4298437/179972832-ebb30282-c68f-4761-85f0-c1645cf18a39.png">

### 重现步骤

1. npm run dev
2. 访问  http://localhost:8080/

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/10671
