### ISSUE TITLE
IOS操作系统使用AddressEdit时键盘挡住了输入框

### ISSUE THREAD

**Issue by dqzonline** [youzan/vant#1089]
可重新的IOS设备：IPHONE 7
![_20180517155848](https://user-images.githubusercontent.com/3873571/40164093-393bafe8-59eb-11e8-980c-7d4716253390.jpg)

**Comment by dqzonline** [comment]
怎么没有人回复一下的？？

**Comment by rex-zsd** [comment]
可以贴个能复现问题的jsfiddle吗？

**Comment by dqzonline** [comment]
https://jsfiddle.net/rLo6yhps/

**Comment by dqzonline** [comment]
https://jsfiddle.net/rLo6yhps/ @rex-zsd

**Comment by dqzonline** [comment]
@rex-zsd 你好，我发现的这个BUG是否已经在验证了？能重现 吗？

**Comment by Nick-Tsao** [comment]
this.inputTimer = setInterval(() => {
        document.body.scrollTop = 600;
        if (document.body.scrollTop == 600) {
          clearInterval(this.inputTimer)
        }
      }, 200)

**Comment by Nick-Tsao** [comment]
聚焦后 执行这个方法可以试试.

**Comment by dqzonline** [comment]
非常感谢，我尝试一下，如有疑问再请教你 @Nick-Tsao

**Comment by Nick-Tsao** [comment]
不客气,我是路人.哈哈哈 很巧,也遇到过这个问题.
