### ISSUE TITLE
省市县三级联动

### ISSUE THREAD

**Issue by 18510758841** [youzan/vant#1090]
省市县三级联动的数据格式可否写成点击省的去请求接口，返回市的列表，在点击市的列表返回县的这样的一种操作？如果不行的话可以发下 Area.json 文件，下载文档点击进去页面404错误

**Comment by rex-zsd** [comment]
@18510758841 如果你指的是area组件的话，是可以异步插入选项的，change事件会返回picker实例，可以参考下[picker](https://www.youzanyun.com/zanui/vant#/zh-CN/picker)的文档，不过area和picker数据结构不太一样，需要注意一下，大致这个样子
![image](https://user-images.githubusercontent.com/8767877/40168888-44245db8-59f7-11e8-921e-8705db51b476.png)

**Comment by 18510758841** [comment]
好的多谢

**Comment by 18510758841** [comment]
还是上面调用接口的方法，能否给出一个具体的实例参考，Array(31)
0
:
{citycode: "1000", cityname: "北京市"}
1
:
{citycode: "1100", cityname: "天津市"}
2
:
{citycode: "1200", cityname: "河北省"}
3
:
{citycode: "1600", cityname: "山西省 "}
4
:
{citycode: "1900", cityname: "内蒙古自治区"}
5
:
{citycode: "2200", cityname: "辽宁省"}
6
:
{citycode: "2400", cityname: "吉林省"}
7
:
{citycode: "2600", cityname: "黑龙江省"}
8
:
{citycode: "2900", cityname: "上海市"}
9
:
{citycode: "3000", cityname: "江苏省"}
10
:
{citycode: "3300", cityname: "浙江省"}
11
:
{citycode: "3600", cityname: "安徽省"}
12
:
{citycode: "3900", cityname: "福建省"}
13
:
{citycode: "4200", cityname: "江西省"}
14
:
{citycode: "4500", cityname: "山东省"}
15
:
{citycode: "4900", cityname: "河南省"}
16
:
{citycode: "5200", cityname: "湖北省"}
17
:
{citycode: "5500", cityname: "湖南省"}
18
:
{citycode: "5800", cityname: "广东省"}
19
:
{citycode: "6100", cityname: "广西自治区"}
20
:
{citycode: "6400", cityname: "海南省"}
21
:
{citycode: "6500", cityname: "四川省"}
22
:
{citycode: "6900", cityname: "重庆市"}
23
:
{citycode: "7000", cityname: "贵州省"}
24
:
{citycode: "7300", cityname: "云南省"}
25
:
{citycode: "7700", cityname: "西藏自治区"}
26
:
{citycode: "7900", cityname: "陕西省"}
27
:
{citycode: "8200", cityname: "甘肃省"}
28
:
{citycode: "8500", cityname: "青海省"}
29
**:**
{citycode: "8700", cityname: "宁夏自治区"}
30
:
{citycode: "8800", cityname: "新疆自治区"}

**# 拿到当前的 citycode 去获取市的列表 如何写？**

**Comment by rex-zsd** [comment]
@18510758841 上面的示例应该比较清楚了，根据index来判断当前选择的是省、市还是区，然后调用setColumnValues重设当前列的选项

**Comment by 18510758841** [comment]
好的，明白了

**Comment by 18510758841** [comment]
用Area,版本"vant": "^1.1.10",change事件，拿不到picker，还有一个问题就是change省列表，要拿到code,渲染市列表，市列表change,之后"TypeError: Cannot read property 'code' of undefined"报错，拿不到code,麻烦告之下

**Comment by 18510758841** [comment]
更严重的的问题，Area组件直接调用change事件直接报错

**Comment by chenjiahan** [comment]
@18510758841 可以单独提个 issue，附上你的问题和复现步骤

**Comment by 18510758841** [comment]
提交了，麻烦看下




发自网易邮箱大师


在2018年06月29日 15:03，neverland<notifications@github.com> 写道：

@18510758841 可以单独提个 issue，附上你的问题和复现步骤
