### ISSUE TITLE
[Bug Report] Vant Cli 首次yarn dev 失败及新增组件不能查看

### ISSUE THREAD

**Issue by Gintangible** [youzan/vant#10930]
### 重现链接

使用yarn create vant-cli-app 构建项目即可复现

### Vant Cli 版本

^4.0.0

### 描述一下你遇到的问题。

使用vant-cli 初次构建项目时，需要先执行 yarn build，这样才能正常访问 yarn dev 创建的服务
新建组件不能运行，必须要在新增组件内部添加README.md 文件

如果以上是怎么设计的，麻烦在文档里做个说明，跑了一下午，才发现的。

### 重现步骤

1. yarn create vant-cli-app
2. yarn dev
3. 可以访问，内部不能正常使用
4. yarn build && yarn dev ok
5. 新增组件，如果不添加README.md 文件，此组件不能正常访问。

**Comment by chenjiahan** [comment]
试了下确实有问题，第二次运行 dev 的时候才会正常，如果降级 vite 到 ~2.8.0 则不会有问题，后续我们再排查下

**Comment by chenjiahan** [comment]
经排查是 vite 的 optimizeDeps 机制存在 bug，在第一次运行时，会同时引入两份 Vue 代码，导致 Vue 组件无法正常渲染。

目前把 `vue` 加入到 `optimizeDeps.include` 来解决了此问题，可以升级 @vant/cli 5.0.2 版本试下。
