### ISSUE TITLE
[Feature Request] Cli 支持桌面端组件

### ISSUE THREAD

**Issue by kekexunxun** [youzan/vant#10944]
### 这个功能解决了什么问题？

能够使用vant-cli构建桌面端组件库

### 你期望的 API 是什么样子的？

非api，是将原废弃的桌面端组件呈现补充实现

**Comment by chenjiahan** [comment]
精力有限，暂时不会去支持桌面端组件了（之前版本的实现也是社区同学贡献的）

如果有需要的话，欢迎提 PR 来支持哈

**Comment by kekexunxun** [comment]
你好,我已收到你所发的邮件,并会及时回复.谢谢
