### ISSUE TITLE
Tabs组件sticky有问题

### ISSUE THREAD

**Issue by shx1545** [youzan/vant#1095]
![f82e79ca-3c64-4bc2-8eb0-d54dbdb65c7e](https://user-images.githubusercontent.com/29303050/40207911-74ec0618-5a69-11e8-88d5-82b7c8ad9bbf.gif)

到达顶部时，瞬间会变成fixed，但是继续往上滑动，fixed就消失了。

**Comment by rex-zsd** [comment]
可以贴下你的demo吗？
tabs的sticky吸顶只在tab内容块在屏幕内时才有效，tab内容块滑出屏幕顶部时会自动取消吸顶的。
如果下面的123都不在tab组件内，这个效果是正常的。

**Comment by shx1545** [comment]
必须要在tab内容快中才能吸顶？好，那样是正常的。谢谢了。
