### ISSUE TITLE
[Feature Request] 导出themeVars类型

### ISSUE THREAD

**Issue by Nakus0426** [youzan/vant#10973]
### 这个功能解决了什么问题？

使用 `ConfigProvider` 组件时可通过 `themeVars` 变量修改主题，希望可以导出一份 `themeVars` 的类型，方便自定义主题。
可参考 [Naive UI](https://www.naiveui.com/zh-CN/light/docs/customize-theme) 的实现方式

### 你期望的 API 是什么样子的？

![image](https://user-images.githubusercontent.com/41540888/186872286-ceab952c-8613-41b8-8e20-8df752e8599c.png)

**Comment by chenjiahan** [comment]
可以的，后面加一下

**Comment by chenjiahan** [comment]
已在 4.0.0-rc.3 版本支持
