### ISSUE TITLE
Rate评分组件可否出一个change event 返回改变后的数值

### ISSUE THREAD

**Issue by maoqiwu** [youzan/vant#1099]
如题

**Comment by rex-zsd** [comment]
分值是通过`v-model`绑定的，监听input事件即可，可以参考[vue官方文档](https://cn.vuejs.org/v2/guide/components.html#%E5%9C%A8%E7%BB%84%E4%BB%B6%E4%B8%8A%E4%BD%BF%E7%94%A8-v-model)

**Comment by chenjiahan** [comment]
已在 1.1.5 版本支持
