### ISSUE TITLE
popup lock-scroll属性不生效

### ISSUE THREAD

**Issue by LynanBreeze** [youzan/vant#1101]
设置成true和false背景都可以滚动。
```
<van-popup v-model="menuVisible" position="bottom" :lock-scroll="true">
我的popup内容
<van-popup>
```

**Comment by LynanBreeze** [comment]
版本 1.1.3

**Comment by chenjiahan** [comment]
未能复现这个问题

**Comment by gzxxy110506** [comment]
我的版本是1.14，也出现了这个问题，
就是如果主页的内容是可以滚动的长度，点开popup之后依然还能滚动主页的内容，无法锁定

**Comment by cocody** [comment]
安卓有效， 但是 IOS 无效

**Comment by chinahuarvin** [comment]
我的也不行，报错[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
，应该是这块报错

**Comment by chinahuarvin** [comment]
貌似是这样的，popup的内容如果有个输入框，弹出键盘后，输入内容，关闭键盘，再次滚动的时候lock-scroll="true" 就不生效后

**Comment by wananzys** [comment]
我也遇到同样的问题,主页内容可以滚动的话,弹出层无法实现背景锁定,而且左右滑动还能切换主页的tabs

**Comment by aoyangyang** [comment]
目前lock-scroll好像还是不生效
