### ISSUE TITLE
[Bug Report] 在uc浏览器中，点击浏览器的返回按钮会自动跳到浏览器首页，无法正常返回上一页

### ISSUE THREAD

**Issue by Orange8** [youzan/vant#11013]
### 重现链接

https://vant-ui.github.io/vant/mobile.html#/zh-CN

### Vant 版本

3.6.2

### 描述一下你遇到的问题。

在uc浏览器中访问vant3.x或4.x组件，点击进入其中一个组件，后再点击浏览器的返回键，正常应该返回上一页，但是却返回了浏览器主页。

### 重现步骤

1、uc浏览器访问vant3组件库；
2、点击进入button按钮组件；
3、点击浏览器返回按钮；
4、点击进入button按钮组件；
5、点击浏览器返回按钮；
6、正常应该返回上一页，但是却返回了浏览器主页
多次点击即可重现
![RPReplay_Final1662469108.gif](https://s2.loli.net/2022/09/06/iwHNMIGqklDoL7V.gif)

### 设备/浏览器

ios15.4.1、uc浏览器最新版

**Comment by chenjiahan** [comment]
Vant 的示例用的是 vue-router 的标准 API 进行跳转的，这个现象估计是 UC 的 bug 了
