### ISSUE TITLE
[Bug Report] ImagePreview的onScale方法ts类型丢失

### ISSUE THREAD

**Issue by freak-jacker** [youzan/vant#11046]
### 重现链接

无

### Vant 版本

2.12.20

### 描述一下你遇到的问题。

ImagePreview的ts文件声明中缺失onScale类型的方法，onClosed应该也没有
![image](https://user-images.githubusercontent.com/76548533/190112946-93719611-588f-4aa3-80fb-81e6d918bce6.png)
![image](https://user-images.githubusercontent.com/76548533/190113046-84cf771b-4640-4bdb-a213-f7736b289634.png)

### 重现步骤

import { ImagePreview } from 'vant';

// then...
ImagePreview({
        images:[],
        onScale: () => {
         // 并且“onScale”不在类型“ImagePreviewOptions”中
        },
      });

### 设备/浏览器

vscode

**Comment by chenjiahan** [comment]
onScale 的类型后续会加上。

onClosed 目前是没有对外暴露的，所以没有类型
