### ISSUE TITLE
[Feature Request] navbar希望可以支持是否需要点击反馈

### ISSUE THREAD

**Issue by wChenonly** [youzan/vant#11047]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-rwku7v?file=/src/App.vue

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

在navbar组件中，如果插槽中使用2个div块，由于van-haptics-feedback 这个类的点击反馈，会导致我点任意一个按钮，另一个也会出现闪烁效果。另外即便去掉van-haptics-feedback这个类中的cursor: pointer，点击反馈效果依然在，只有把这个类名去掉，才会点击反馈效果也消失

希望可以支持，是否需要点击反馈的props。 

### 重现步骤

无

**Comment by chenjiahan** [comment]
可以的，我们评估下

**Comment by wChenonly** [comment]
当前我要解决这个闪烁，有无好的办法

**Comment by chenjiahan** [comment]
```css
.van-haptics-feedback:active {
  opacity: 1;
}
```

**Comment by GRAMMAC1** [comment]
提供一个是否开启反馈的 `props`，比如 `useFeedback`，默认是开启的，如果关闭的话开发者手动添加 `van-haptics-feedback` 这个类名来增加点击的反馈，这样可行不？

**Comment by chenjiahan** [comment]
可以滴，props 建议命名为 clickable，与 Cell/Grid 保持一致
