### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by likailun101929** [youzan/vant#11055]
### 重现链接

https://mobile.jingyingbang.com/joinTeam?no=1552145334912815104

### Vant 版本

2.6.12

### 描述一下你遇到的问题。

图片上传组件不会让input失去焦点

### 重现步骤

1.点击添加证书
2.点击证书名称让输入框获取焦点弹出软键盘
3.在不失去焦点的情况下点击上传附件
4.之后页面底部会出现空白 高度为软键盘高度

### 设备/浏览器

华为荣耀

**Comment by chenjiahan** [comment]
<img width="693" alt="截屏2022-09-17 下午1 42 13" src="https://user-images.githubusercontent.com/7237365/190842398-d0284804-0bfb-455c-be2d-0baa2ee7dd96.png">
