### ISSUE TITLE
[Bug Report] Van-tabs组件 使用swipeable、animated选项时，导致点击切换tab时，出现视图滚动定位错误Bug（严重）

### ISSUE THREAD

**Issue by tangs8dj** [youzan/vant#11050]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-s0xner?file=/src/App.vue&resolutionWidth=375&resolutionHeight=675

### Vant 版本

3.4.6

### 描述一下你遇到的问题。

Van-tabs组件 使用swipeable、animated选项时, 切换tab 视图滚动错位必现:
1.刷新页面,使用手机容器
<img width="684" alt="image" src="https://user-images.githubusercontent.com/42624042/190535642-063fb15e-e8dc-45c0-8d52-d697eb627c80.png">
2.滚动tabs组件至视图顶部,sticky生效
![sticky](https://user-images.githubusercontent.com/42624042/190535136-77cb0f06-a27b-45c3-989a-5fc756177818.jpg)
3.点击『标签2』之后的tab
<img width="430" alt="image" src="https://user-images.githubusercontent.com/42624042/190535411-e1068757-de09-4c38-b534-a14591f4eefd.png">
4. 视图错误🔽
![sticky2](https://user-images.githubusercontent.com/42624042/190535471-3903fe90-637a-4335-b8bf-e47445d8ae5f.jpg)

**发现sticky使不使用, 相同复现操作都会有定位错误问题**

### 重现步骤

1.每次刷新页面后
2.点击『标签2』之后的tab
3. 视图错误🔽

### 设备/浏览器

所有

**Comment by tangs8dj** [comment]
@chenjiahan 嗨喽，你好
想问一下，为能回复这个问题是发现有什么问题吗？😂

想知道是提问格式还是未能复现问题，好让我这边能根据问题进行改进，谢谢😁

**Comment by chenjiahan** [comment]
在 codesandbox 链接里没复现你说的问题呢，可以录个屏看下吗

**Comment by tangs8dj** [comment]
> 在 codesandbox 链接里没复现你说的问题呢，可以录个屏看下吗

录屏怎么发送给你呢

**Comment by chenjiahan** [comment]
可以发我邮箱: jait.chen@foxmail.com

**Comment by tangs8dj** [comment]
> 可以发我邮箱: [jait.chen@foxmail.com](mailto:jait.chen@foxmail.com)

好的，
我也上传了一份到哔哩哔哩https://www.bilibili.com/video/BV1qt4y1A72o/?vd_source=2c070b4cb16d4325722a89d536dd8dd0
邮箱也会发送一份，谢谢

**Comment by chenjiahan** [comment]
收到，我看下

**Comment by chenjiahan** [comment]
说明下问题原因：

背景 1： Tabs 默认开启了 lazy render 机制，初始化时，默认只有第一和第二个 Tab 会被渲染，其他 Tab 只有选中时才会渲染。
背景 2： 当开启 swipeable 和 animated 时，为了保证 Tabs 高度符合预期，会将未选中的 Tab 的高度设置为 0，这样 Tabs 的高度等同于当前选中的标签页的高度。

在上面的链接中，滚动位置变化的原因是：点击第三个 Tab 时，第一个 Tab 变为 inactive 状态，因此高度变成了 0，而此时第三个 Tab 由于触发 lazy render 机制，内容尚未渲染完成，导致浏览器判定页面高度不足，滚动到了上方的位置。

这个问题的解决方法我再考虑下，主要需要保证渲染完成的时机早于将其他 Tab 高度设置为 0 的时机。

**Comment by chenjiahan** [comment]
临时解决方法是在 Tabs 上设置 :lazy-render="false"，关闭 lazy render

**Comment by tangs8dj** [comment]
好的，还有个tab闪屏问题，我另起一个issue

**Comment by chenjiahan** [comment]
刚发布了 3.6.3 版本，可以试下，闪屏问题应该也一并修复了
