### ISSUE TITLE
在钉钉的APP中的iOS8.3版本下,样式错乱

### ISSUE THREAD

**Issue by GEOHOTIOS** [youzan/vant#1105]
#[所有的vant组件样式不会自动增加] -webkit-
.van-tabbar-item {
flex: 1;
color: #666;
display: flex;
line-height: 1;
font-size: 12px;
align-items: center;
flex-direction: column;
justify-content: center;

不支持flex布局 所有flex相关的 全部都是Unsupported property name\value
我这边已经配置过autoprefixer了 但是好像不生效

**Comment by chenjiahan** [comment]
vant 的样式会自动加上 webkit 的。这里应该是你项目配置的问题
