### ISSUE TITLE
[Feature Request] display-format prop in datePicker

### ISSUE THREAD

**Issue by Hfutsora** [youzan/vant#11067]
### 这个功能解决了什么问题？

通过 `display-formatter` 只用于展示，不影响原始数据。

同时：
- 配置了 `display-formatter` 时，原有的 `formatter` 将作为 `value-formatter` 只用于转化值的格式
- 未配置 `formatter` 时，绑定值应保留原始状态

### 你期望的 API 是什么样子的？

```ts
<date-picker v-model="date" formatter="yyyy-MM-dd" display-formatter="MM-dd" />
```

此时 `date-picker` 的展示日期应为 `MM-dd` 格式， 但是存储的值格式为 `yyyy-MM-dd`。

**Comment by chenjiahan** [comment]
DatePicker 现在并没有 format 属性，你指的是 formatter 吗

**Comment by Hfutsora** [comment]
是 `formatter `，另外我们希望有一个新的 prop 能将值和显示的格式化分开。

**Comment by chenjiahan** [comment]
可以的，我们评估下

**Comment by chenjiahan** [comment]
v4 的 DatePicker 本身就是把值和显示的文本分开处理的，你是在使用 v4 吗

**Comment by Hfutsora** [comment]
发现是 field 和 date-picker 一起用的时候，给 field 上加了 [formatter](https://youzan.github.io/vant/#/en-US/field#format-value) 导致值的变化和 date-picker 无关，是我弄错了。
