### ISSUE TITLE
vann-sku

### ISSUE THREAD

**Issue by bigpoanda** [youzan/vant#11068]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/sku

### Vant 版本

2.12.32

### 描述一下你遇到的问题。

van-sku 中price除了默认会默认换算成分 计算格式 这个如果不想让换算有什么好的解决方案吗 

### 重现步骤

sku中 list 中的price 默认会安分计算 可以价格属性 来控制不强制按分计算的吗 ， 谢谢

**Comment by chenjiahan** [comment]
不行的哈，你可以把价格转换为分，然后再传入组件。

**Comment by bigpoanda** [comment]
好的👌🏻 了解




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月22日(星期四) 上午9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant] vann-sku (Issue #11068)





 
不行的哈，你可以把价格转换为分，然后再传入组件。
