### ISSUE TITLE
搜索组件的删除按钮在谷歌浏览器的手机预览模式下点击不灵敏

### ISSUE THREAD

**Issue by gdutwyg** [youzan/vant#11060]
### 重现链接

https://vant-contrib.gitee.io/vant/mobile.html#/zh-CN/search

### Vant 版本

3.6.2

### 描述一下你遇到的问题。

在谷歌浏览器的手机预览模式下，点击删除按钮，反应并不灵敏，方向要点击右上角才能删除
![image](https://user-images.githubusercontent.com/11848087/191154912-f786c4be-7705-4ea1-859d-9a9629b7037f.png)

### 重现步骤

1. 点击[链接](https://vant-contrib.gitee.io/vant/mobile.html#/zh-CN/search)，打开谷歌浏览器的手机预览模式
2. 输入文本，点击删除，反应并不灵敏，需要点击右上角才能删除

### 设备/浏览器

谷歌浏览器，手机预览模式

**Comment by wjw-gavin** [comment]
试了下，确实在“谷歌浏览器的手机预览模式”有这个情况，不过在手机上表现正常...

**Comment by chenjiahan** [comment]
我的 Chrome 还挺正常的，可能是特定版本 Chrome 的问题吧，手机上正常就行，模拟器可以忽略
