### ISSUE TITLE
van-stepper 组件，设置min和max属性之后，输入不在范围内的数字，在onBlur时能否不自动修正

### ISSUE THREAD

**Issue by liubin595338764** [youzan/vant#11065]
### 这个功能解决了什么问题？

交互上尽量不改变用户输入的内容。

van-stepper 组件，设置min和max属性之后，输入不在范围内的数字，在onBlur时能否不主动修正。

尤其是用户输入完之后立马点击提交按钮，会提交修正后的数字，而不是用户自己输入的数字。

### 你期望的 API 是什么样子的？

```xml
<van-stepper :auto-correct="false" />
```

**Comment by wjw-gavin** [comment]
不太理解你这个需求点....，既然已经设置了`min`和`max`，为什么还能提交超过限制的数值呢？这样设置限制还有意义么。。（既设置了限制，又要求能超过限制...）

**Comment by liubin595338764** [comment]
应该是不能提交的。
比如我设置了`min:10, max:100`, 当用户输入`5`的时候，离开输入框之后，van-stepper组件自动把`5`改成了`10`，变成合法的数字了，所以就可以提交了。
所以van-stepper组件不能去修复用户输入的数字

**Comment by wjw-gavin** [comment]
> 

哦哦哦，这么一说我明白了，那回头看下作者怎么说...

**Comment by chenjiahan** [comment]
可以的，我们加个开关控制该行为

**Comment by liubin595338764** [comment]
@chenjiahan  感谢。
然后能不能把点击+-按钮步长的计算也优化下，点击+-按钮计算的结果是步长的整数倍。
比如我设置的步长是 `5`，输入框里面的`7`，
点击+按钮之后，
现在的效果是将输入框里面计算成`12`，
期望的效果是将输入框里面计算成`15`(5的整数倍，向上约位)

点击-按钮之后，
现在的效果是将输入框里面计算成`2`，
期望的效果是将输入框里面计算成`5`(5的整数倍，向上约位)

也将此行为加一个开关控制下。

**Comment by wjw-gavin** [comment]
> @chenjiahan 感谢。 然后能不能把点击+-按钮步长的计算也优化下，点击+-按钮计算的结果是步长的整数倍。 比如我设置的步长是 `5`，输入框里面的`7`， 点击+按钮之后， 现在的效果是将输入框里面计算成`12`， 期望的效果是将输入框里面计算成`15`(5的整数倍，向上约位)
> 
> 点击-按钮之后， 现在的效果是将输入框里面计算成`2`， 期望的效果是将输入框里面计算成`5`(5的整数倍，向上约位)
> 
> 也将此行为加一个开关控制下。

我觉得这个在满足步长是 5 且结果是 5 的倍数的时候才成立吧？
你是理解为既然步长是5，那结果理应就是5的倍数是么

**Comment by liubin595338764** [comment]
@chenjiahan 是的。
> 既然步长是5，那结果理应就是5的倍数

或者`vant-stepper`还可以支持一个自定义函数，在每次`vant-stepper`的值发生变化时调用这个函数，函数的返回结果可以再覆盖`vant-stepper`的值，这样的话使用者就可以根据自己的业务逻辑来修正`vant-stepper`的值了。
这个函数接收两个参数：

```
/**
 * @param {String} value  vant-stepper组件改变后的值
 * @param {String} action  plus 点击+按钮触发， minus 点击-按钮触发， input 手动输入触发
 * @return {String} newval  函数执行后返回的值，填充到vant-stepper组件的输入框内
```

**Comment by wjw-gavin** [comment]
“既然步长是5，那结果理应就是5的倍数“，这个说法不太合理吧？

举个例子：如果拍卖会一件商品拍95w，但是每次加价不低于10w（如果每次都是10w），那结果也不是10的倍数哇？

**Comment by liubin595338764** [comment]
@chenjiahan  你说的也对哈，我不是说所有的场景，所以这个是有开关配置的，开发者根据自己的业务场景去配置使用

**Comment by wjw-gavin** [comment]
> @wjw-gavin 你说的也对哈，我不是说所有的场景，所以这个是有开关配置的，开发者根据自己的业务场景去配置使用

是有你这种场景，只是我觉得步长其实在跟倍数没什么关系的时候，这种情况可以自己来控制，比如自己写个方法来限制用户输入，亦或者在提交时提示用户输入数值是“5的倍数”，否则限制提交。
