### ISSUE TITLE
list组件会在loading为true的情况下再次请求

### ISSUE THREAD

**Issue by gdutwyg** [youzan/vant#11064]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-zwt9q8

### Vant 版本

3.6.2

### 描述一下你遇到的问题。

list组件，在loading为true的情况下，还会触发load方法。导致再次请求。

### 重现步骤

我在load方法中，先设置loading为true，接着往list中push数据，但是load方法会再次执行，导致push了2次。如图
![image](https://user-images.githubusercontent.com/11848087/191253657-0869ee69-d17a-4cdf-bdc4-b0fdbc59f063.png)

### 设备/浏览器

谷歌浏览器

**Comment by wjw-gavin** [comment]
[看下这里](https://youzan.github.io/vant/#/zh-CN/list#wei-shi-me-list-chu-shi-hua-hou-hui-li-ji-chu-fa-load-shi-jian)
![image](https://user-images.githubusercontent.com/19986739/191398896-1b6e741e-52da-43a9-9664-be486ae1fb0a.png)

**Comment by wjw-gavin** [comment]
![image](https://user-images.githubusercontent.com/19986739/191399116-41e41c16-3f1a-4812-9739-e38a870d795d.png)

**Comment by gdutwyg** [comment]
> ![image](https://user-images.githubusercontent.com/19986739/191399116-41e41c16-3f1a-4812-9739-e38a870d795d.png)

为什么不能分开写呢？
