### ISSUE TITLE
[Feature Request] Van-field的end-validate事件 能否把消息一起返回

### ISSUE THREAD

**Issue by mudoo** [youzan/vant#11070]
### 这个功能解决了什么问题？

单独使用Van-field的场景，已经提供了end-validate事件但是没有消息，使用贼难受

### 你期望的 API 是什么样子的？

```xml
<van-field v-model="name" @end-validate="handleChangeName"
```
```script
handleChangeName({ status, message }) {
  if (status === 'failed') {
    alert(message)
    return
  }
  // postSave
}
```

**Comment by wjw-gavin** [comment]
这样吗？
![image](https://user-images.githubusercontent.com/19986739/191719258-36964b09-93fe-43f4-ae2e-71140b21a873.png)

**Comment by mudoo** [comment]
> 这样吗？ ![image](https://user-images.githubusercontent.com/19986739/191719258-36964b09-93fe-43f4-ae2e-71140b21a873.png)

是的，end-validate事件回调需要message，可以满足单字段修改实时保存的需求
