### ISSUE TITLE
[Bug Report] missing site.headHtml option

### ISSUE THREAD

**Issue by Moudicat** [youzan/vant#11072]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-zvozzh?file=/vant.config.mjs

### Vant Cli 版本

4.0.4

### 描述一下你遇到的问题。

文档中提到Vant-cli支持site.headHtml选项，但实际上v4.0.4版本的vant-cli并不支持
需要将 #10807 合并到发布分支，谢谢~

### 重现步骤

在 vant.config.mjs 中新增 site.headHtml 选项并测试

**Comment by chenjiahan** [comment]
我发布了 5.0.0-beta.0 版本，建议直接使用 v5 吧~ 里面还包含了 vite 3.0 的更新。

更新日志：https://github.com/youzan/vant/blob/main/packages/vant-cli/changelog.md
