### ISSUE TITLE
[Feature Request] vant field 实例方法支持change

### ISSUE THREAD

**Issue by vw331** [youzan/vant#11077]
### 这个功能解决了什么问题？

因为 v-model 绑定的值变化并不会触发change事件（我知道事情是反过来的），但在某些情况下我们确实需要在 vant-field 的值变化时手动触发change事件以达到校验和联动等其它需求（我正在做一个动态表单）

Field.tsx 314行 似乎不允许使用new Event('input')触发 change， 希望能提供一个方法手动触发change
`const onInput = (event: Event) => {
      // skip update value when composing
      if (!event.target!.composing) {
        updateValue((event.target as HTMLInputElement).value);
      }
    };`

### 你期望的 API 是什么样子的？

`
value.value = 'new Value'
fieldRef.value.change()

<van-field
   ref="fieldRef"
    v-model="value"
    :change="onChange"
/>
`

**Comment by chenjiahan** [comment]
1. 表单联动的话，应该基于 v-model 绑定的响应式值，不应该基于事件的形式
2. 校验可以通过方法来主动触发，`fieldRef.value.validate`，实际上现在已经提供了该方法，只是没在文档里说明

**Comment by vw331** [comment]
> 

谢谢，我们的表单设计需要支持用户自定义的 onChange、onClick等事件，Field 组件虽然可以通过“update:model-value” 的方式实现 onchange，但 picker选择器等组件 与 Field 组合使用时却无法实现这个逻辑。我知道通过监听 v-model的变化也可以变相实现，但这完全反过来了。如果有什么更好的方法请赐教

**Comment by chenjiahan** [comment]
「反过来」是啥意思嘞，我理解基于数据驱动才是符合大部分场景的

**Comment by vw331** [comment]
单靠数据驱动无法区分来源，表单内的数据既可能是用户输入，也可以是js赋值，也可以是一些辅助插件通过dom的方式插入（此时需要自定义input事件触发自定义的change函数）

**Comment by chenjiahan** [comment]
区分来源这个需求可以理解，不过还是不太理解为什么需要反过来去调用 Field 内部的 change 事件，事实上 Field 压根没有一个名叫 change 的事件，或许你可以具体描述一下需要触发 FIeld 内部的哪段逻辑
