### ISSUE TITLE
vant-use  里面 麻烦更新一个版本， 需要更新下useEventListener 导出的类型

### ISSUE THREAD

**Issue by FANZHETWO** [youzan/vant#11073]
### 重现链接

https://github.com/youzan/vant/blob/main/packages/vant-use/src/useEventListener/index.ts

### Vant Cli 版本

4.0.4

### 描述一下你遇到的问题。

构建组件库时，用到了vant-use 里面  useEventListener 方法，但是    "@vant/use": "^1.4.2", 版本 useEventListener  定义的类型没有更新， 需要升级下版本导出下 export declare function useEventListener<K extends keyof DocumentEventMap>(type: K, listener: (event: DocumentEventMap[K]) => void, options?: UseEventListenerOptions): void;

### 重现步骤

错误提示如下图：
<img width="580" alt="IMG20220922-173307214" src="https://user-images.githubusercontent.com/22415838/191716823-d07306d6-d3b8-4931-bca6-00ce337b3f39.png">

yarn build

**Comment by chenjiahan** [comment]
已经更新 1.4.3 了哈
