### ISSUE TITLE
在使用unplugin-vue-components按需引入组件样式中，使用intellij idea或者webstorm无法提示语法

### ISSUE THREAD

**Issue by E-10000** [youzan/vant#11089]
### 这个功能解决了什么问题？

在[官方介绍](https://vant-contrib.gitee.io/vant/v4/#/zh-CN/quickstart#fang-fa-yi.-chang-gui-yong-fa)的方法中，使用常规方法导入，在编辑器是可以看到语法提示的
![image](https://user-images.githubusercontent.com/52124130/192143306-fc462699-7718-4149-b208-aab053eb1e23.png)
![image](https://user-images.githubusercontent.com/52124130/192143477-befcc9bb-4f6f-4e7c-9712-6676bcfa091a.png)

而使用[按需引入组件样式](https://vant-contrib.gitee.io/vant/v4/#/zh-CN/quickstart#fang-fa-er.-an-xu-yin-ru-zu-jian-yang-shi)的方法，没有任何的提示
![image](https://user-images.githubusercontent.com/52124130/192143432-5ba0a4a9-8b4c-46b4-b023-282cb9af6a6b.png)
希望能够加入语法提示，不然写代码很麻烦，

### 你期望的 API 是什么样子的？

如上所示

**Comment by chenjiahan** [comment]
这个你看下 unplugin-vue-components 的文档就好，里面有说明：https://github.com/antfu/unplugin-vue-components#typescript

**Comment by E-10000** [comment]
> 这个你看下 unplugin-vue-components 的文档就好，里面有说明：https://github.com/antfu/unplugin-vue-components#typescript

那文档只写了支持vscode的[Volar](https://github.com/johnsoncodehk/volar)，没有写到支持idea或者webstorem的

**Comment by chenjiahan** [comment]
原理是一样的吧，无非是加个全局的类型声明

**Comment by E-10000** [comment]
> 原理是一样的吧，无非是加个全局的类型声明

已解决，谢谢。又可以快乐地写代码了。
```js
//vite.config.js
import Components from 'unplugin-vue-components/vite';
import { VantResolver } from 'unplugin-vue-components/resolvers';


export default defineConfig({
  plugins: [
    vue(),
    //导入vant组件
    Components({
      resolvers: [VantResolver()],
      dts:true //开启idea或者vscode中的vant语法提示
    }),
  ],
})

```
重启的话就会生成components.d.ts文件

**Comment by darkchan** [comment]
> > 原理是一样的吧，无非是加个全局的类型声明
> 
> 已解决，谢谢。又可以快乐地写代码了。
> 
> ```js
> //vite.config.js
> import Components from 'unplugin-vue-components/vite';
> import { VantResolver } from 'unplugin-vue-components/resolvers';
> 
> 
> export default defineConfig({
>   plugins: [
>     vue(),
>     //导入vant组件
>     Components({
>       resolvers: [VantResolver()],
>       dts:true //开启idea或者vscode中的vant语法提示
>     }),
>   ],
> })
> ```
> 
> 重启的话就会生成components.d.ts文件
你好，我想请问你设置了之后，有没有感觉输入代码后，要等一下才出来代码提示，而不是迅速出来，我初步排查是因为检索的文件过多，包括在css中输入基础样式后，也是需要等一会才出提示，我尝试删除vant的相关引入之后，css的输入变得响应极快，不知道你是否也存在同样的问题

**Comment by E-10000** [comment]
> > > 原理是一样的吧，无非是加个全局的类型声明
> > 
> > 
> > 已解决，谢谢。又可以快乐地写代码了。
> > ```js
> > //vite.config.js
> > import Components from 'unplugin-vue-components/vite';
> > import { VantResolver } from 'unplugin-vue-components/resolvers';
> > 
> > 
> > export default defineConfig({
> >   plugins: [
> >     vue(),
> >     //导入vant组件
> >     Components({
> >       resolvers: [VantResolver()],
> >       dts:true //开启idea或者vscode中的vant语法提示
> >     }),
> >   ],
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 重启的话就会生成components.d.ts文件
> > 你好，我想请问你设置了之后，有没有感觉输入代码后，要等一下才出来代码提示，而不是迅速出来，我初步排查是因为检索的文件过多，包括在css中输入基础样式后，也是需要等一会才出提示，我尝试删除vant的相关引入之后，css的输入变得响应极快，不知道你是否也存在同样的问题

我这里的话没有要检索很慢才出代码提示，你可以试着提高IDE在内存的占用比，或者增大内存试试。我电脑16G，i7-10700，代码提示速度很快

**Comment by darkchan** [comment]
我是大成，你的邮件我已经收到了，会尽快回复哦~

**Comment by darkchan** [comment]
> 我这里的话没有要检索很慢才出代码提示，你可以试着提高IDE在内存的占用比，或者增大内存试试。我电脑16G，i7-10700，代码提示速度很快
我用的是mac book pro 2019款 16G的，webstorm也设置-Xms1024m -Xmx8192m，这个应该不是内存问题，因为我发现在代码提示弹窗内有很多vant相关的css类名称，具体的我写了一个求助帖，大佬可以移步看一下 [这里](https://juejin.cn/post/7282587833596264507)
