### ISSUE TITLE
The cell label layout does not have an exclusive row

### ISSUE THREAD

**Issue by lixiaofa** [youzan/vant#11081]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-ufroi0?file=/src/App.vue

### Vant 版本

3.x

### 描述一下你遇到的问题。

The cell label layout does not have an exclusive row.      
Layout error

### 重现步骤

The cell label layout does not have an exclusive row.

**Comment by chenjiahan** [comment]
Yes, this is limited by the Cell's DOM structure, but we do not plan to adjust the Cell's DOM structure yet.

**Comment by xiaofuyesnew** [comment]
Is it possible to add a content slot for adjusting full width cell?
