### ISSUE TITLE
vue3用了vant的UI组件打包成npm包后，引用npm报无效节点

### ISSUE THREAD

**Issue by chenguanQ** [youzan/vant#11093]
### 重现链接

-

### Vant 版本

3.2.0

### 描述一下你遇到的问题。

[Vue warn]: Invalid VNode type: Symbol(Text) (symbol) 
  at <PendantEvaluationa> 
  at <App>

### 重现步骤

-

**Comment by chenjiahan** [comment]
请提供有效的 codesandbox 重现链接
