### ISSUE TITLE
[Feature Request] uploader组件是否支持连续拍照，将拍照得到的照片放在暂存列表中，最后再统一上传

### ISSUE THREAD

**Issue by yaogenimeiyouai** [youzan/vant#11091]
### 这个功能解决了什么问题？

选择上传图片时，可以连续拍照，将拍照得到的照片放在暂存列表中，最后再统一上传

### 你期望的 API 是什么样子的？

无

**Comment by chenjiahan** [comment]
上传这个操作是使用者完成的，你可以自行封装相关的逻辑。
