### ISSUE TITLE
vant-popup结合vant-picker,在IOS设备上在一个长列表的vant-form页面时，设置vant-popup的position="bottom"不是从屏幕底部弹出，而是从form的实际底部弹出，导致vant-picker看不到，在安卓设备上一切正常

### ISSUE THREAD

**Issue by 1601463525** [youzan/vant#11104]
### 重现链接

http://css.telecomjs.com/pages/wwk-khzf-h5/#/buildingView?buildingId=250527853186&latnId=250&managerId=25000008969&staffId=800913816&staffName=%E4%B9%94%E6%A2%A6%E7%92%90&areaId=250000001&staffPhone=15301582135

### Vant 版本

3.3.6

### 描述一下你遇到的问题。

vant-popup结合vant-picker,在IOS设备上在一个长列表的vant-form页面时，设置vant-popup的position="bottom"不是从屏幕底部弹出，而是从form的实际底部弹出，导致vant-picker看不到，在安卓设备上一切正常

### 重现步骤

1、该页面是内嵌在iframe中打开的。
2、当打开vant-popup时在IOS设备上不是从设备底部弹出的

### 设备/浏览器

IOS设备上

**Comment by chenjiahan** [comment]
可以确认下是不是父级元素有 transform 的样式，导致 Popup 的 fixed 布局失效了
