### ISSUE TITLE
picker级联选择功能的bug

### ISSUE THREAD

**Issue by GitHumburger** [youzan/vant#11103]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/picker

### Vant 版本

2.12.50

### 描述一下你遇到的问题。

使用级联选择功能时，如果数组的第一项的子项（children）为空字符串，会导致渲染不出来第二列。 如果某一项的子项为空字符串，此项的子项在页面上会显示之前的子项。
![企业微信截图_20220930142331](https://user-images.githubusercontent.com/49260937/193204193-05502177-fa7a-408f-b2ff-a39d7fb34325.png)

如上图，医疗的子项为空字符串，显示的是运营商的子项。
如果第一列第一项的子项为空字符串，整个第二列就不会渲染。

### 重现步骤

把数组的第一项或某一项设的子项（children）置为空字符串即可复现

### 设备/浏览器

任意浏览器的移动设备模式

**Comment by chenjiahan** [comment]
Vant 2 的问题欢迎提 PR 修复喔，参见：https://github.com/youzan/vant/discussions/11108
