### ISSUE TITLE
自定义数字键盘没有完成按钮的点击事件

### ISSUE THREAD

**Issue by limengke123** [youzan/vant#1110]
**What is the current behavior?**

自定义数字键盘(NumberKeyboard)没有提供**完成按钮**的点击事件。

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

vue@2.5.2  vant@1.1.4

**Comment by chenjiahan** [comment]
已在 1.1.5 版本支持
