### ISSUE TITLE
indexBar组件的交互+功能错误

### ISSUE THREAD

**Issue by PXRace** [youzan/vant#11101]
### Discussed in https://github.com/youzan/vant/discussions/11099

<div type='discussions-op-text'>

<sup>Originally posted by **PXRace** September 29, 2022</sup>
4.0.0-alpha.4、4.0.0-rc.4版本，indexBar组件的交互功能失效是怎么回事，吸顶、自定义索引列表跳转功能都无效了</div>

**Comment by chenjiahan** [comment]
没复现你说的问题哈，麻烦提供有效的 codesandbox 复现链接
