### ISSUE TITLE
uniapp vue3 引入vant，输入框没有值

### ISSUE THREAD

**Issue by zz541843** [youzan/vant#11113]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-8fuq5o?file=/src/App.vue

### Vant 版本

3.6.3

### 描述一下你遇到的问题。

v-model绑定van-field，只要输入值就会清空value

### 重现步骤

hbuilderx创建个v3默认项目就行了，我自己拉项目复测过

**Comment by zz541843** [comment]
App环境，浏览器环境可以，其他没测过

**Comment by zz541843** [comment]
等等，第一次用这个，有没有可能是你们本来就不支持app环境....

**Comment by chenjiahan** [comment]
Vant 没有适配 uni-app 哈，建议你向 uni-app 提 issue，保证正确实现 Vue 3 的能力即可。
