### ISSUE TITLE
是否可以再优化下van-progress组件，谢谢

### ISSUE THREAD

**Issue by 270034480** [youzan/vant#1111]
首先非常感谢您的辛勤付出，我们团队目前打算深度使用vant改造现有产品；
目前产品用van-progress组件，遇到产品组过不去的问题，不知道是否有方案可以解决
如下图：
![tim 20180519234903](https://user-images.githubusercontent.com/36993759/40270396-3f3e998e-5bbf-11e8-8ca4-b63c7a741b5b.png)
妥协方案是类似demo，两边留白，但是产品组过不去，因为中间文字我们不是百分比，是动态文字，造成如果留白也不知道该留多少合适，很尴尬！
请教一下是否有现成解决方案，如果没有，是否考虑会响应我们这个需求，谢谢！

**Comment by chenjiahan** [comment]
感谢反馈，后续会优化这块，避免文字超出进度条范围

**Comment by 270034480** [comment]
辛苦了~这回复速度真是太牛了，点赞！！！
您可以考虑一下加个参数设置，让想超出的需求也能兼容，万分感谢！

**Comment by chenjiahan** [comment]
嗯嗯~ 目前来看超出边界是比较不合理的，下个版本会优化掉

**Comment by 270034480** [comment]
好的，谢谢！~

**Comment by chenjiahan** [comment]
已在 1.1.5 版本优化

**Comment by 270034480** [comment]
谢谢！！！
