### ISSUE TITLE
分类选择官网demo实例和代码演示,代码对应不上

### ISSUE THREAD

**Issue by lixiaoyao711** [youzan/vant#11127]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/tree-select

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

分类选择官网demo实例和代码演示,代码对应不上

### 重现步骤

打开vant官网,找到分类选择组件,查看单选模式代码

### 设备/浏览器

任意设备/浏览器

**Comment by wjw-gavin** [comment]
[demo例子的代码看这里](https://github.com/youzan/vant/blob/main/packages/vant/src/tree-select/demo/index.vue)
