### ISSUE TITLE
[Feature Request] 请在此填写标题

### ISSUE THREAD

**Issue by Princekk** [youzan/vant#11126]
### 这个功能解决了什么问题？

If you restrict camera functionality on your phone, can you add a prompt method to the [van-uploader] component to make it easier to call and improve the experience

### 你期望的 API 是什么样子的？

```xml
<van-uploader @before-authority='xxx'></van-uploader>
```

**Comment by Yacj** [comment]
try this  [https://vueuse.org/core/usePermission/](url)

**Comment by chenjiahan** [comment]
Maybe you can call the `usePermission` method when the `click-upload` event is emiited.
