### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by zhaoke2021** [youzan/vant#11128]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/tree-select#treeselectitem-shu-ju-jie-gou

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

TreeSelect左侧选项无法禁用，官网代码不匹配

### 重现步骤

[
  {
    // 导航名称
    text: '所有城市',
    // 导航名称右上角徽标
    badge: 3,
    // 是否在导航名称右上角显示小红点
    dot: true,
    // 导航节点额外类名
    className: 'my-class',
 // **禁用选项**
        disabled: true,
    // 该导航下所有的可选项
    children: [
      {
        // 名称
        text: '温州',
        // id，作为匹配选中状态的标识符
        id: 1,
        // 禁用选项
        disabled: true,
      },
      {
        text: '杭州',
        id: 2,
      },
    ],
  },
];

### 设备/浏览器

手机/浏览器

**Comment by wjw-gavin** [comment]
未复现你说的“左侧选项无法禁用”

https://codesandbox.io/s/vant-3-issue-template-forked-z82rw3?file=/src/App.vue

**Comment by chenjiahan** [comment]
The document is fixed by https://github.com/youzan/vant/pull/11136
