### ISSUE TITLE
van-radio组件，文字多了之后会使radio错位

### ISSUE THREAD

**Issue by 270034480** [youzan/vant#1113]
![image](https://user-images.githubusercontent.com/36993759/40275243-3a9311a4-5c1d-11e8-898f-2e8f55262f4e.png)
如图，文字多了之后会使radio，错位；
期望的效果是radio选择框始终在左侧，上下居中，文字及图片在右侧；

感谢贵团队的辛勤付出，辛苦了~

**Comment by chenjiahan** [comment]
这种情况是需要手动覆盖样式的，如果没法覆盖的话应该是你的 css 选择器写的有问题
