### ISSUE TITLE
[Feature Request] Calendar可否抛出事件获取滚动到当前区域的date

### ISSUE THREAD

**Issue by LinhZeng** [youzan/vant#11135]
### 这个功能解决了什么问题
可以改造副标题显示当前滚动区域的年份月份

### 描述您想要的解决方案
当前只有month-show这个事件可以获取某个月份进入可视区域，
但想要的是滚动到某个月份区域时能获取当前date，即副标题的响应

### 建议的API是什么样的
类month-show事件

**Comment by chenjiahan** [comment]
这个需求通过事件来支持不是很适合。

我可以在 subtitle 这个插槽中传入当前 Date 对象和 subtitle 文本内容，不知道是否能满足你的需求
