### ISSUE TITLE
[Bug Report] 安卓的浙里办app以及支付宝小程序中图片预览组件多次预览以后工作不正常

### ISSUE THREAD

**Issue by ltinerary** [youzan/vant#11132]
### 重现链接

https://github.com/ltinerary/reportBug/tree/main/vant3/imagePreview

### Vant 版本

3.6.0

### 描述一下你遇到的问题。

在浙里办环境中使用Vant，使用了图片预览的组件。第一次进去预览正常。但第二次预览，一直滑动会导致出现指示器超出所有预览的图片的数量。当出现这种情况的时候，第三次点击预览会有部分图片预览失败，且指示器的数量会在前一次的基础上再次加1。

![e759aefea18ea526c9eea3ec5543836](https://user-images.githubusercontent.com/79144923/194999143-1427b03c-85a5-4e8c-9f3d-a607e3503c6d.png)

浙里办安卓环境的 浙里办App以及浙里办支付宝小程序中会出现此问题。
浙里办的安卓的微信小程序不会出现此问题 
浙里办ios环境工作正常
浏览器中不会出现此问题

### 重现步骤

1.使用安卓的浙里办app扫描[此二维码](https://github.com/ltinerary/reportBug/blob/main/vant3/imagePreview/QRcode.png)
2.点击资格认定申请，完成申请后，点击我的材料
3.第一次预览大图正常
4.第二次预览大图 一直向右滑动会出现没有正确回到第一张图片，且指示器超出图片的数量
5.在4的步骤复现的情况下，有些图片就无法被预览

### 设备/浏览器

安卓的 浙里办App以及安卓的浙里办支付宝小程序

**Comment by chenjiahan** [comment]
对于一个特定系统的 WebView 下出现的问题，建议先定位下是不是该 WebView 下的某些 JS 行为出现了偏差，一般要 Native 同学来进行解决

**Comment by chenjiahan** [comment]
另外上面的重现步骤有点复杂，我们不好排查，如果希望协助排查的话，最好是通过 codesandbox 提供一个可复现的 demo

**Comment by ltinerary** [comment]
> 另外上面的重现步骤有点复杂，我们不好排查，如果希望协助排查的话，最好是通过 codesandbox 提供一个可复现的 demo

好的麻烦了。个人觉得不太好复现，不过我尽量能够脱离浙里办环境尝试复现。

**Comment by chenjiahan** [comment]
嗯嗯，把 codesandbox 生成的链接放在浙里办的 WebView 里跑也可以

**Comment by ltinerary** [comment]
> 嗯嗯，把 codesandbox 生成的链接放在浙里办的 WebView 里跑也可以

我推测是和支付宝的webview有关系。

所以我将网站部署到了[公网](http://123.56.20.102:8014/#/ssoLocal)上，生成一个网址二维码，使用支付宝的扫一扫进入此页面，能够复现这个问题。

![image](https://user-images.githubusercontent.com/79144923/195032317-bf47a4c1-5716-4a31-8b92-32504f742b36.png)

复现步骤：

1. 使用支付宝扫一扫扫描上面的二维码，使之在支付宝中打开当前网页【如果二维码没有加载出来，可以点击进入该[网站](http://123.56.20.102:8014/#/ssoLocal)，使用工具再生成一个新的网址二维码】
2. 点击**联调环境测试登录按钮**
3. 点击 **我的材料** 模块
4. 点击一张图片，进入预览组件。第一次预览一直向右滑，可以正常循环展示
5. 关闭预览，再次点击图片预览，一直向右滑，此时会出现超出图片数量的预览指示器
6. 之后再点击预览就会出现预览组件不显示图片（部分）的问题，并且也无法循环展示

这是我脱离浙里办环境复现的办法，麻烦协助排查下，多谢~

**Comment by ltinerary** [comment]
此外我在 [codesandbox](https://codesandbox.io/s/long-butterfly-cqgm7c?file=/public/index.html&resolutionWidth=320&resolutionHeight=675) 也建了一个。不过复现的步骤任然需要生成一个网站二维码，然后在支付宝【安卓】扫码查看，复现步骤如上一条评论

![image](https://user-images.githubusercontent.com/79144923/195044361-7daeb0f2-bcf7-42b3-92e7-c9e5c61d0f4d.png)

**Comment by ltinerary** [comment]
此外我使用[nutui3.2.3搭建了一个图片预览的demo](https://codesandbox.io/s/serene-visvesvaraya-bslknk?file=/src/App.vue)，在安卓的支付宝和安卓微信中没有出现问题。

![image](https://user-images.githubusercontent.com/79144923/195082303-50b086e1-a52d-47ae-acbf-5a240d3b3bde.png)

**Comment by chenjiahan** [comment]
收到，这几天比较忙，周末看下

**Comment by ltinerary** [comment]
> 收到，这几天比较忙，周末看下

辛苦麻烦了，我最近也在看这个源码，尝试解决🤝🏻

**Comment by chenjiahan** [comment]
> 个人根据一些表现来猜测的话，nutui组止了系统默认事件，但vant没有。

这个描述不太准确，因为 Vant 默认也会在缩放的时候阻止系统默认事件。参加 https://github.com/youzan/vant/blob/main/packages/vant/src/image-preview/ImagePreviewItem.tsx#L171-L173

不过我现在身边没有 iOS 设备，暂时没法验证这个问题

**Comment by chenjiahan** [comment]
排查发现支付宝/钉钉的 WebView 下，Vue 3 不能正常触发 unmount 事件。

比如 ImagePreview 中生成了四个 SwipeItem 组件，在正常的浏览器下，打开 ImagePreview 时会触发四次 mount 事件，关闭时会触发四次 unmount 事件。

但是在支付宝 WebView 中，打开 ImagePreview 时会触发四次 mount 事件，关闭时只触发了三次 unmount 事件。

![image](https://user-images.githubusercontent.com/7237365/196016368-922648e8-4b83-41db-a63b-ce98345c14f9.png)

**Comment by chenjiahan** [comment]
@ltinerary 支付宝里没法打开 localhost，我当时用 codesandbox 验证的这个问题

**Comment by chenjiahan** [comment]
另外这个问题的表现是框架/WebView 层面的，组件库这边无法处理，先 close 了哈，后续可以关注 Vue 版本升级或 WebView 迭代后会不会得到修复。
