### ISSUE TITLE
[Feature Request] 一些具有跳转属性的组件能不能兼容下SSR模式

### ISSUE THREAD

**Issue by vincenthou2016** [youzan/vant#11130]
### 这个功能解决了什么问题？

一些具有跳转属性的组件能不能兼容下SSR模式，比如cell等可以选择使用a标签来构建，这样在SSR模式下更有利于seo。

### 你期望的 API 是什么样子的？

<van-cell center title="单元格" value="内容" is-link url="" to="" />
当有url或to属性时 van-cell使用a标签来构建

**Comment by chenjiahan** [comment]
暂时不计划调整默认行为，我给 Cell 加一个 tag 属性来手动控制根节点的标签名吧
