### ISSUE TITLE
[Bug Report] vant小程序版本点击左侧菜单出现偶发性bug

### ISSUE THREAD

**Issue by studeyer** [youzan/vant#11134]
### 重现链接

https://gitee.com/striveCai/vant---click-menu-bug/blob/master/653_1665581478.mp4

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

1.无意中发现的bug ,猜测会不会资源没加载完，陷入循环，路由和页面一直刷新变更
2.bug就如视频里面复现了，有这个有问题的期间，在点击某个左侧组件，点击的那个组件也会陷入相应的 路由和页面循环摔加载
3.刷新完之后就浮现不了了

### 重现步骤

1.在官网点击中从导航组件里面的IndexBar 索引栏 组件依次倒数点击到PullRefresh 下拉刷新 组件，
2.bug就如视频里面复现了，有这个有问题的期间，在点击某个左侧组件，点击的那个组件也会陷入相应的 路由和页面循环摔加载

### 设备/浏览器

Chrome

**Comment by chenjiahan** [comment]
视频链接打不开哈，不过你描述的这个现象我偶尔也会碰到，路由陷入死循环了，刷新一下页面可以解决。

这个我们后续看看能不能优化下，但大部分时候不影响阅读文档
