### ISSUE TITLE
[Bug Report] tabs组件数据排序，数据未更新

### ISSUE THREAD

**Issue by aiyadingya** [youzan/vant#11146]
### 重现链接

https://codesandbox.io/s/restless-wave-ygf1gm?file=/src/App.vue

### Vant 版本

2.12.51

### 描述一下你遇到的问题。

对绑定的数组进行重新排序，vant未更新显示

### 重现步骤

1. 点击 “打乱顺序”
2. tabs数据变化，组件未更新

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
Vue 2 应该不支持 array.sort 方法的响应式更新，建议你重新对数组赋值一下

**Comment by hengwujun128** [comment]
vue3 也有此问题
