### ISSUE TITLE
[Feature Request] Toast组件无法控制英文的换行样式

### ISSUE THREAD

**Issue by JiuSword** [youzan/vant#11145]
### 这个功能解决了什么问题？

目前英文提示内容过多时会自动换行，但是自动的换行会把一个单词截断，不支持word-wrap:break-word; 设置

### 你期望的 API 是什么样子的？

增加自定义样式控制或一个Options以控制css换行样式

**Comment by wjw-gavin** [comment]
看了下，最初的样式是 `word-wrap:break-word;`，后来因为[这个问题](https://github.com/youzan/vant/issues/8959) 作者给改成了 `word-break: break-all;`

所以我们是否可以提供一个`prop`来设置具体使用那种换行？

**Comment by chenjiahan** [comment]
嗯嗯，可以通过 props 来控制，不同场景的诉求不太一样
