### ISSUE TITLE
[Feature Request] Skeleton 支持自定义模板 并且增加skeletonItem 组件

### ISSUE THREAD

**Issue by liyuan1125** [youzan/vant#11141]
### 这个功能解决了什么问题？

目前的骨架屏自定义很麻烦
而且内容很难做到理想的效果

希望自定义模板 并且增加`skeletonItem` 组件 用来达到理想布局的效果

例如这样的列表，用目前的组件是无法完成的
![image](https://user-images.githubusercontent.com/91421824/196031923-f897ed42-aa30-412a-b573-061a7185f152.png)

但是有了自定义模板之后 是可以完成的
```vue
<template>
  <van-skeleton :loading="loading">
    <template #template>
      <div class="thumb">
        <van-skeleton-item type="image" class="news-item-thumb" />
      </div>
      <div class="content">
        <van-skeleton-item type="cell" height="0.4rem" />
        <van-skeleton-item type="cell" height="0.35rem" />
      </div>
    </template>
    <template>
      内容列表
    </template>
  </van-skeleton>
</template>

<script lang="ts" setup>
import { ref } from "vue";

const loading = ref(false);
</script>
```

### Props
|参数|说明|类型|默认值|
|:---:|:---:|:---:|:---:|
| loading |是否显示骨架屏，传 false 时会展示子组件内容|boolean|false|
| animate |是否开启动画|boolean|true|
| row |段落占位图行数|number\|string|0|

### Slots

|名称|说明|
|:---: | :---: |
|default | 正在渲染的DOM |
|template | 自定义渲染 skeleton 模板 |

### Props
|参数|说明|类型|默认值|
|:---:|:---:|:---:|:---:|
| type |当前渲染 skeleton 类型|`cell` `image` `avatar` |`cell`|
| height| 当前渲染的skeleton高度|number\|string | 0|
| width| 当前渲染的skeleton宽度 | number\|string|0|

**Comment by chenjiahan** [comment]
目前 Skeleton 确实不够通用，我们后续评估下

**Comment by GRAMMAC1** [comment]
`Skeleton` 是有点死板，布局写死在组件内部，很难灵活的自定义。如果做修改的话

* 增加 `Skeleton-item` 组件，通过组合 `Skeleton-item` 完成自定义的布局
* `Skeleton` 部分 `props` 可以移除（比如 `row` 可以放在 `Skeleton-item` 里面）

`Skeleton` 保留 `loading ` `animate`

`Skeleton-item` 如下
| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
| type | 骨架屏占位图类型，默认 `cell` | `cell` \| `title` \| `image` \| `avatar` | `cell` |
| row | 段落占位图行数，搭配 `cell` 一起使用 | _number \| string_ | `0` |
| row-width | 段落占位图宽度，搭配 `cell` 一起使用 | _number \| string | `100%` |
| round | 是否将标题和段落显示为圆角风格，搭配 `cell` 或 `title` 一起使用 | _boolean_ | `false` |
| title-width | 标题占位图宽度，搭配 `title` 一起使用 | _number \| string_ | `40%` |
| avatar-size | 头像占位图大小，搭配 `avatar` 一起使用 | _number \| string_ | `32px` |
| avatar-shape | 头像占位图形状，可选值为 `square`，搭配 `avatar` 一起使用 | _string_ | `round` |

**Comment by chenjiahan** [comment]
@GRAMMAC1 SkeletonItem 如果是通过 type 区分的话，用户还得去分别哪些 type 对应哪些可用的 props。

建议像 antd 一样，直接拆分成 SkeletonAvatar、SkeletonTitle、SkeletonImage、SkeletonParagraph（命名为 Paragraph 比 Cell 更准确） 等组件，这样 props 可以被明确区分，以后扩展新的 SkeletonXXX 也比较方便。

**Comment by GRAMMAC1** [comment]
@chenjiahan 拆分成独立的组件心智负担确实小一些，我改一下。
