### ISSUE TITLE
[Bug Report] vant2全局引入报错

### ISSUE THREAD

**Issue by s980711272** [youzan/vant#11159]
### 重现链接

无

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

![1666339379383](https://user-images.githubusercontent.com/24401815/197145139-34ed4a01-c9c4-41e7-85ab-225bef29ff22.png)

### 重现步骤

npm i vant@latest-v2 -S

import Vue from 'vue';
import Vant from 'vant';
import 'vant/lib/index.css';

Vue.use(Vant);

安装vant后全局引入，就会报错误了

**Comment by chenjiahan** [comment]
建议检查下 Vue 是否使用了 2.x 版本，如果安装正确版本后还有问题，可以提供一个重现该问题的链接
