### ISSUE TITLE
[Bug Report] 关于van-uploader 在ios16下的问题

### ISSUE THREAD

**Issue by hongweixun** [youzan/vant#11150]
### 重现链接

1

### Vant 版本

2.12.19

### 描述一下你遇到的问题。

van-uploader 直接调起摄像头拍照上传，在升级到ios16之后，点击选择照片会强制刷新页面（bug），目前使用的是2.12.19版本。不确定3以上的版本是否同样有此问题！安卓跟鸿蒙系统均已测试，不存在这个问题。ios15以下，同样正常！目前无法确定是如何触发这个bug，当单个van-uploader组件拍照上传时，并不一定每次都会强制刷新页面，但试多几次，总会有出现的时候。当多个van-uploader组件依次在ios16下拍照上传时，100%触发强制刷新页面！

### 重现步骤

（ios16系统）
1.点击组件上传
2.选择拍照上传
3.点击使用照片

### 设备/浏览器

ios 16

**Comment by hongweixun** [comment]
补充说明：出问题的ios具体版本为16.2，今天继续升级到16.4以后，问题消失了

**Comment by chenjiahan** [comment]
系统问题没什么解决方法~ 因为 Uploader 用的也是原生的 HTML input 标签
