### ISSUE TITLE
vite+uniapp+vue3 引入vant3运行报错

### ISSUE THREAD

**Issue by AnonymXXX** [youzan/vant#11164]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/icon

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

icon组件

[vite]: Rollup failed to resolve import "@vant/use" from "node_modules/vant/es/action-bar/ActionBar.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

### 重现步骤

pnpm dev:mp-weixin

**Comment by chenjiahan** [comment]
参见 https://vant-ui.github.io/vant/#/zh-CN/faq#shi-fou-zhi-chi-zai-uni-app-zhong-shi-yong
