### ISSUE TITLE
行动按钮 弹出层上面  使用请提示toast，在禁止背景点击的时候会出现 遮罩层关闭

### ISSUE THREAD

**Issue by dzcms** [youzan/vant#1116]
行动按钮 弹出层上面  使用请提示toast，在禁止背景点击的时候会出现 行动按钮的遮罩层关闭
forbidClick:true 这个是关键 

https://jsfiddle.net/58xxdjvz/

**Comment by chenjiahan** [comment]
已在 1.1.5 版本修复
