### ISSUE TITLE
图片预览偶尔会出现白色背景问题

### ISSUE THREAD

**Issue by Do-Eternally** [youzan/vant#11160]
### Reproduction Link

null

### Vant Version

3.6.0

### Describe the Bug

![image](https://user-images.githubusercontent.com/42773712/197154210-315f51b6-da44-4ab6-9b5f-86842d8fac35.png)
![image](https://user-images.githubusercontent.com/42773712/197155108-78e519eb-7c96-4a67-ba23-9fb8d2605872.png)
.van-popup类名的样式会覆盖.van-image-preview的样式

### Reproduce Steps

并不能完全复现，直接使用ImagePreview函数生成预览可能是白色背景。图片上传组件预览会是黑色背景，然后ImagePreview函数生成预览也会变成黑色

### Device / Browser

Chrome/106.0.0.0

**Comment by chenjiahan** [comment]
这个是 CSS 顺序的问题，默认情况下，Vant 内的 CSS 是按照 Vant 声明的顺序来引入的，不会出现上述问题。

如果项目打包时使用的打包工具错误处理了 CSS 顺序，就可能出现 Popup 样式覆盖其他组件的情况，建议检查下打包工具的配置和版本，如果在使用 vite，可以参考 https://github.com/youzan/vant/issues/11049
