### ISSUE TITLE
[Bug Report] CountDown 倒计时组件首次渲染时触发finish方法且在ios端微信内置浏览器内不会在首次渲染时触发

### ISSUE THREAD

**Issue by stakusir** [youzan/vant#11167]
### 重现链接

无法提供

### Vant 版本

2.12.25

### 描述一下你遇到的问题。

在使用vant2开发移动端h5时countdown倒计时组件会在首次渲染时触发finish方法，但在ios端微信内置浏览器却不会首次渲染时触发，两者均能正常在倒计时结束时触发finish方法。

### 重现步骤

首次渲染时触发

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/197394286-1a3e1c70-c385-434a-92d9-718a4742aa27.png)
