### ISSUE TITLE
[Bug Report] nuxt3 中用路由跳转到有tab页面，tab样式错误

### ISSUE THREAD

**Issue by 578838516** [youzan/vant#11170]
### 重现链接

https://codesandbox.io/p/github/578838516/nuxt3-vant/draft/priceless-lehmann?file=%2Fpages%2Findex.vue&selection=%5B%7B%22endColumn%22%3A34%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A34%2C%22startLineNumber%22%3A2%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl9mfh5c1000ulqiv86bc3k0t%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpages%252Findex.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl9mfi84q00gs3b6h0b1juxic%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Fb%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl9mfi6qe00eu3b6hwjquknmg%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

在nuxt3（v3.0.0-rc.11）中通过路由跳转页面，跳转到有tab标签页的页面中，tab的样式有错误。
<img width="491" alt="image" src="https://user-images.githubusercontent.com/42484399/197466879-30eb9f37-acf5-404c-9a02-bbd50a6dff0f.png">
打开控制台发现.van-tabs__line 元素缺少style="transform: translateX(47px) translateX(-50%);

### 重现步骤

1、从a页面路由跳转到b就会有问题

**Comment by 578838516** [comment]
nuxt3 的nuxt-link 跳转和vue3 router.push()都一样会出现上述问题

**Comment by taokepppooo** [comment]
可能是animated导致的原因，我去掉的话样式就正常了

**Comment by 578838516** [comment]
> 
你从a页面点击到b页面就会有这个问题，我刚刚看了codesandbox 链接上可以复现这个问题

**Comment by 578838516** [comment]
> codesandbox 链接未能复现 issue 中描述的问题，建议看下 codesandbox 的内容是不是没正确提供
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/42484399/198947039-471d16c8-2c09-4aad-afd7-40cd6d55c9ab.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/42484399/198947097-b7f9d162-0c44-4ddc-acf8-ff9549679f9a.png">

**Comment by 578838516** [comment]
> 
我没添加animated

**Comment by f-soud** [comment]
俺也一样，顺带加个将list固定在屏幕进行局部滚动，list滚动至底部@load不触发，刷新又是正常的，一切换页面就凉，你这边可以resize，就是会有个恢复正常的的动画，脑袋有点大，看起来list的滑动底部触发走到body滚动条上去了，完蛋

**Comment by chenjiahan** [comment]
用最新版的 Nuxt + Vant 不再有此问题了
