### ISSUE TITLE
[Bug Report] tabbar组件safe-area-inset-bottom属性无效

### ISSUE THREAD

**Issue by FrontEndDog** [youzan/vant#11172]
### 重现链接

https://gitee.com/GaoWeiQiang1996/vue3-ts-template

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

安装依赖后，启动项目，用真机在微信中打开项目地址，如图所示
![4aeae4102f4d06262f4a98930b8b254](https://user-images.githubusercontent.com/46493087/197715702-c7f6b93d-e4a3-4c62-a5df-dc84408df31d.jpg)
IOS底部适配区域没有生效
在点击一次跳转之后，微信底部会多出一个前进后退的按钮，此时展示正常
![93fcc0e86fe2e76018066464c99004e](https://user-images.githubusercontent.com/46493087/197718573-072f7d0c-4014-4d56-93d6-b96e5eccbc56.jpg)

这个现象在2.x版本中是正常的

### 重现步骤

安装依赖后，启动项目，用真机在微信中打开项目地址，在vant 2.x版本中   不会有这个问题

### 设备/浏览器

iPhone X   iPhone 13

**Comment by wjw-gavin** [comment]
https://gitee.com/GaoWeiQiang1996/vue3-ts-template/blob/master/index.html#L6

viewport 加上 `viewport-fit=cover`就行了

**Comment by wjw-gavin** [comment]
![2951666689704_ pic](https://user-images.githubusercontent.com/19986739/197736030-3649320e-2aec-4c43-8eb3-2318bd45255b.jpg)

**Comment by FrontEndDog** [comment]
> https://gitee.com/GaoWeiQiang1996/vue3-ts-template/blob/master/index.html#L6
> 
> viewport 加上 `viewport-fit=cover`就行了

确实  我两个项目viewport的值不一样   加上之后就正常了    Thank you very much
