### ISSUE TITLE
vue3+vite+uniapp导入vant^3.6.4报错

### ISSUE THREAD

**Issue by AnonymXXX** [youzan/vant#11171]
### 重现链接

https://codesandbox.io/p/github/AnonymXXX/vant-demo/draft/broken-cdn

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

vite打包的时候报错
'isVNode' is not exported by node_modules/@dcloudio/uni-mp-vue/dist/vue.runtime.esm.js, imported by node_modules/@vant/use/dist/index.esm.mjs
at ../node_modules/@vant/use/dist/index.esm.mjs:79:2
  77: // src/useRelation/useChildren.ts
  78: import {
  79:   isVNode,
        ^
  80:   provide,
  81:   reactive,

### 重现步骤

yarn dev:mp-weixin

**Comment by chenjiahan** [comment]
https://vant-ui.github.io/vant/#/zh-CN/faq#shi-fou-zhi-chi-zai-uni-app-zhong-shi-yong

**Comment by renzhenqi** [comment]
请问这个问题解决了吗

**Comment by AnonymXXX** [comment]
> 请问这个问题解决了吗

没有解决, 编译小程序会报错, h5正常

**Comment by littledenny** [comment]
小程序不应该用@vant/weapp嘛? vant是不支持小程序的呀

**Comment by xeoshow** [comment]
@vant/weapp在uni-app使用后，可以支持多端小程序吗？比如抖音小程序等等
