### ISSUE TITLE
Tab标签页在Iphone13上选择标签后会跳回上一个标签

### ISSUE THREAD

**Issue by SunQQQ** [youzan/vant#11179]
### 重现链接

暂无链接

### Vant 版本

2.12.45

### 描述一下你遇到的问题。

Tab标签页过多，出现滚动的情况下。在Iphone13上选择标签后会跳回上一个标签，安卓手机没有问题
![image](https://user-images.githubusercontent.com/24430020/198026024-3db7003d-d785-43f1-9851-97d093e64f19.png)
![Uploading image.png…]()

各位老师帮忙指点下，因不是所有设备都会复现，不知道从何下手
### 重现步骤

1、多个tab标签出现横向滚动场景下
2、使用Iphone13，点击一个标签，会跳回上一个标签

### 设备/浏览器

iphone13

**Comment by wjw-gavin** [comment]
最好提供一个复现链接或者仓库，看下你是怎么写的。

**Comment by SunQQQ** [comment]
我们后来在部分安卓手机（小米9）和chrome模拟器上，通过快速切换标签也复现了该情况。
我们怀疑是第一个动画还未执行完毕，就开始第二个动画的原因。
后来我们把动画属性给关了，就没有该情况后就上线了

**Comment by Pentium286** [comment]
> 我们后来在部分安卓手机（小米9）和chrome模拟器上，通过快速切换标签也复现了该情况。 我们怀疑是第一个动画还未执行完毕，就开始第二个动画的原因。 后来我们把动画属性给关了，就没有该情况后就上线了

解决了，`scrollspy` 在苹果下的问题

**Comment by zongzi-creator** [comment]
> > 我们后来在部分安卓手机（小米9）和chrome模拟器上，通过快速切换标签也复现了该情况。 我们怀疑是第一个动画还未执行完毕，就开始第二个动画的原因。 后来我们把动画属性给关了，就没有该情况后就上线了
> 
> 解决了，`scrollspy` 在苹果下的问题

怎么解决的啊 老师 把duration=0？还是什么别的方案？求指教
