### ISSUE TITLE
Steps横向排列时不支持多个滚动

### ISSUE THREAD

**Issue by Abyss-QAQ** [youzan/vant#11187]
### 这个功能解决了什么问题？

当步骤过多时，横向样式会挤在一起，不支持横向滚动和当前选择的active定位

### 你期望的 API 是什么样子的？

<van-steps :active="active" scroll />

**Comment by chenjiahan** [comment]
暂时没有计划支持这个场景哈，一般来说 Steps 建议控制在一屏以内，如果超出一屏，可以考虑自己写一个对应的组件。
