### ISSUE TITLE
[Bug Report] DatePicker|TimePicker组件的v-model赋值比onConfirm取值慢

### ISSUE THREAD

**Issue by devlemoe** [youzan/vant#11186]
### 重现链接

https://codesandbox.io/s/vant4-0-0-rc6-time-picker-qozqp9?file=/src/App.vue:67-71&resolutionWidth=320&resolutionHeight=675

### Vant 版本

v4.0.0-rc.6

### 描述一下你遇到的问题。

onConfirm中返回selectedValues和v-model绑定的值不一致，必须要等待滚动动画结束v-model才能获取到相同的值。
<img width="508" alt="image" src="https://user-images.githubusercontent.com/87158834/198463849-9dd21ac8-60aa-4a4b-b79f-82a19c55e18b.png">

### 重现步骤

1. 打开[https://qozqp9.csb.app/](url)
2. 控制台设置为手机查看
3. 在滚动动画未结束前点击确定
4. 查看打印数据

### 设备/浏览器

*

**Comment by wjw-gavin** [comment]
这....我觉得就好像是在create生命周期获取dom一样吧...

**Comment by devlemoe** [comment]
> 这....我觉得就好像是在create生命周期获取dom一样吧...

当我在配合popup一块使用的时候会发现popup被关闭了，但是并没有附上正确的值（本次想选择的值）。
不然每次我都在onConfirm中去手动赋值的话，v-model好像就失去了原本的意义。

**Comment by chenjiahan** [comment]
这里确实应该保持一致，我修一下
