### ISSUE TITLE
rem布局很多组建样式都乱了

### ISSUE THREAD

**Issue by nmxiaowei** [youzan/vant#1118]
![image](https://user-images.githubusercontent.com/35983068/40287475-1a19891c-5ce0-11e8-976e-ecc04819316f.png)

**Comment by MinosIE** [comment]
求问使用 babel-plugin-import 插件按需加载之后，如何转换vant样式里面的px到rem

**Comment by MinosIE** [comment]
@nmxiaowei 求问使用 babel-plugin-import 插件按需加载之后，如何转换vant样式里面的px到rem

**Comment by chenjiahan** [comment]
rem 配置请参见文档 https://youzan.github.io/vant/#/zh-CN/quickstart

**Comment by lixiangbiao** [comment]
@chenjiahan 就是按照文档配置的啊
vant的样式都乱乱
