### ISSUE TITLE
cell在某些分辨率边框显示不全。 两个框的高度显示一条border

### ISSUE THREAD

**Issue by LynanBreeze** [youzan/vant#1119]
![qq 20180521103647](https://user-images.githubusercontent.com/24271362/40287905-288f8fd4-5ce3-11e8-9496-0c707b82339a.png)
如图所示，红圈内有两个cell，但是cell之间没有分割线。
使用浏览器变换窗口大小可以重现。

**Comment by Alex1990** [comment]
请问这个问题解决了吗？在三星S8上面也存在，就是 cell 的高度不为整数像素的情况下可能会出现
