### ISSUE TITLE
[Bug Report] Search 搜索 文本框内有两个取消按钮

### ISSUE THREAD

**Issue by Kerryta** [youzan/vant#11190]
### 重现链接

--

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

Search 搜索 文本框内有两个取消按钮
![f555c2fb3cfa3abad174ee4a36505ef](https://user-images.githubusercontent.com/78243391/198522826-4b512c05-b7c5-4647-9884-49bb446579be.jpg)

### 重现步骤

<van-search
			shape="round"
			placeholder="输入科室或医生名称"
			v-model="searchValue"
			@search="headleSearch"
		/>

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
右边的取消按钮是 Vant 提供的，左边的不是，建议看下是不是项目中其他的逻辑加上去的
