### ISSUE TITLE
Uploader上传图片 VIVO手机不支持上传图片。

### ISSUE THREAD

**Issue by xiehaizheng** [youzan/vant#11191]
### 重现链接

内部软件，无法提供链接

### Vant 版本

2.12.45

### 描述一下你遇到的问题。

点击uploader组件之后，会调起【照片图库】【拍照】【选择文件】的弹窗。但是点击弹窗之后无反应。在issue里面https://github.com/youzan/vant/issues/8422看到有出现过能调起图片但是返回之后无上传问题。但是此次问题不完全一样。谢谢您的解答。

### 重现步骤

点击uploader组件之后，会调起【照片图库】【拍照】【选择文件】的弹窗。但是点击弹窗之后无反应

### 设备/浏览器

VIVO手机：Vivox50pro+、vivo iQOO、Neo vivoY33s。App里面

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/198834168-cc5f6435-e15c-4cc8-8365-e7b5a092618c.png)
