### ISSUE TITLE
[Feature Request] 希望增加FormItem组件，用于解决其他组件的数据验证

### ISSUE THREAD

**Issue by liyuan1125** [youzan/vant#11200]
### 这个功能解决了什么问题？

用于解决其他组件的数据验证

例如
```vue
  <van-form :model="form">
    <van-form-item prop="name" :rules="[{ required: true, message: '请输入姓名' }]" required>
      <van-field
        
        v-model="form.name"
        :rules="[{ required: true, message: '请输入姓名' }]"
      />
    </van-form-item>

    <van-form-item prop="number" :rules="[{ required: true, message: '请输入数量' }]"  required>
    <van-stepper v-model="form.number"  />
    </van-form-item>
  </van-form>

```

### Props

参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
|model表单数据对象| Object|-|
|rules|表单验证规则|Array|-|
|errors|错误内容|Map<String,String>,例如后端可以返回 `{"name":"请输入姓名","mobile":"请输入手机号码"}`，通过`Form`组件下发给`FormItem`|-|

### Props
参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
|rules|表单验证规则|Array|-|
|prop|model 的键名|String|-|
|error|错误内容|String|-|

**Comment by chenjiahan** [comment]
暂时没有计划添加类似的组件。

如果要提供一个 FieldItem，那必然要提供「展示错误信息」的 UI，那其实跟 Field 组件也差不多了。建议直接用 Field，再调整下样式。

**Comment by liyuan1125** [comment]
> 暂时没有计划添加类似的组件。
> 
> 如果要提供一个 FieldItem，那必然要提供「展示错误信息」的 UI，那其实跟 Field 组件也差不多了。建议直接用 Field，再调整下样式。

但是如果用Field的话 数据不会验证，不知道设计就是这样还是bug?

```vue
 <van-field
      required
      label-align="top"
      v-model="form.avatar"
      :rules="[{ required: true, message: '请上传头像' }]"
    >
      <template #input>
        <van-uploader />
      </template>
    </van-field>

const form = ref({
    avatar: 'default.png',
  })
```

一直显示错误请上传头像 数据貌似不会被验证

**Comment by FAOfao931013** [comment]
官方文档有示例
https://vant-contrib.gitee.io/vant/#/zh-CN/form#biao-dan-xiang-lei-xing---wen-jian-shang-chuan
又或者你想自定义 这个能解决你的问题
https://vant-contrib.gitee.io/vant/#/zh-CN/use-custom-field-value
