### ISSUE TITLE
vant3.4.4  vue3.2.0   script-setup下发下 van-tab中无法渲染子组件，写多条时可以正常渲染

### ISSUE THREAD

**Issue by z1050729352** [youzan/vant#11208]
### 重现链接

无

### Vant 版本

3.4.4

### 描述一下你遇到的问题。

vue3.2.0 script-setup写法下 van-tab中无法渲染子组件，连着写两遍时可以正常渲染两次，只有一条时无法正常渲染，切换到defineComponent写法就能展示正常

### 重现步骤

1、创建父、子组件  script-setup写法
2、父组件引入tab组件
3、tab中镶嵌子组件
4、子组件无法正常渲染，同位置多复制一次子组件就能正常渲染

### 设备/浏览器

chrome

**Comment by wjw-gavin** [comment]
我这未能复现，麻烦提供提供一个可复现链接： https://codesandbox.io/s/vant-3-issue-template-8fuq5o

**Comment by llblax** [comment]
同样的问题，您是怎么解决的。
