### ISSUE TITLE
treeSelect的active-id参数类型校验建议不要限制为Number

### ISSUE THREAD

**Issue by Moerj** [youzan/vant#1120]
treeSelect的activeId参数,被强制校验类型Number
但是通常业务使用中, 此id会使用字符串类型, 如"0012" "EC223" 等等
这会导致treeSelect组件抛出警告.

所以我强烈建议, activeId的类型校验要么关掉,要么改为String

![image](https://user-images.githubusercontent.com/13795438/40288338-58141020-5ce5-11e8-8cf9-141d6eddc7ae.png)

Vue @2.5.2
vant @1.1.3
Mac OS

**Comment by chenjiahan** [comment]
已在 1.1.5 版本优化
