### ISSUE TITLE
[Bug Report] 所有组件在iOS微信环境内无动画

### ISSUE THREAD

**Issue by ikilobyte** [youzan/vant#11203]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/home

### Vant 版本

3.6.6

### 描述一下你遇到的问题。

demo就是vant官网，反馈组件下的大部分组件出现动画很僵硬，没有过渡效果

### 重现步骤

直接iOS微信环境内打开官网，找到有动画的组件（如：反馈组件）就能复现，没有动画，非常生硬

### 设备/浏览器

iphone13、微信环境内

**Comment by wjw-gavin** [comment]
我这iPhone13、微信内未复现。

**Comment by ikilobyte** [comment]
@wjw-gavin 
我这边是版本是
iOS微信版本：8.0.28
iOS版本：15.5

**Comment by chenjiahan** [comment]
@ikilobyte 可以重启微信或手机试试。

Vant 里的 CSS 都是正确声明了 animation/transition 的，这个一般是 APP/系统层面的问题。
