### ISSUE TITLE
[Bug Report] pull-refresh无法下拉刷新

### ISSUE THREAD

**Issue by Andrea954** [youzan/vant#11205]
### 重现链接

https://github.com/Andrea954/reportBug

### Vant 版本

2.12.51

### 描述一下你遇到的问题。

无法下拉刷新
device:三星 S10 
Android Version:Android12
WebView: Android System WebView 96.0.4664.61

### 重现步骤

在Vant 2.x 上选择 pull-refresh 基础用法demo 下拉刷新即可

### 设备/浏览器

三星 S10 Android12  Android System WebView 96.0.4664.61

**Comment by wjw-gavin** [comment]
![image](https://user-images.githubusercontent.com/19986739/199421342-846bc547-b6ed-41e4-a771-82106b19df02.png)
