### ISSUE TITLE
[Feature Request] vant-popover 支持非受控状态

### ISSUE THREAD

**Issue by nooooooom** [youzan/vant#11209]
### 这个功能解决了什么问题？

一些只用于触发 `popover` 的场景里不再需要定义变量来支持 `show` 的双向绑定

### 你期望的 API 是什么样子的？

```tsx
<vant-popover [?:default-show=""] />
```

**Comment by chenjiahan** [comment]
可以的，后续支持下

**Comment by nooooooom** [comment]
> 

是的，但是我觉得既然做成非受控的形式，非受控的默认值还是可以考虑的，虽然使用场景可能不太常见

**Comment by wygwyggit** [comment]
vue2版本的-vant-popover不支持受控状态吗

**Comment by wygwyggit** [comment]
vue版本的vant-popover不支持非受控状态吗
