### ISSUE TITLE
form组件内submit类型按钮功能问题

### ISSUE THREAD

**Issue by Do-Eternally** [youzan/vant#11207]
### 重现链接

null

### Vant 版本

3.6.0

### 描述一下你遇到的问题。

     在van-form组件中点击submit类型的按钮会触发验证，验证通过会触发submit事件。表单外有一个不参加验证的upload组件。我在submit事件处理函数内判断是否有上传的图片，没有该图片我会return，并显示toast提示。
     但是return掉submit事件函数后，再次点击按钮没有效果。该submit类型按钮组件上绑定的点击事件函数也不执行。

### 重现步骤

阻止form表单submit事件，再次提交没有任何作用

**Comment by wjw-gavin** [comment]
麻烦提供提供一个可复现链接 https://codesandbox.io/s/vant-3-issue-template-8fuq5o


另外我写了一个简单的，不知道是不是你描述的效果 [Demo](https://codesandbox.io/s/vant-3-issue-template-forked-lbcq49?file=/src/App.vue)

**Comment by Do-Eternally** [comment]
在复现中精简代码时突然发现。表单提交时会给按钮添加disabled防止重复提交。return表单组件的submit事件处理函数之前没有给disabled属性值置为true。

**Comment by Do-Eternally** [comment]
昨天没深究通过一个隐藏的field组件把图片上传的校验加到表单验证中。并把issues关闭，可能是网络不好没有关闭成功。很抱歉耽误您的时间了。
