### ISSUE TITLE
[Bug Report]  ActionSheet组件在苹果手机谷歌浏览器上关闭不了

### ISSUE THREAD

**Issue by Whualong** [youzan/vant#11211]
### 重现链接

https://codepen.io/codewen666/pen/LYrVypw

### Vant 版本

2.12.51

### 描述一下你遇到的问题。

ActionSheet组件在苹果手机谷歌浏览器上关闭不了（微信内置浏览器也关闭不了）
注意：
1、title 属性设置为一个带空格的字符串是为了让组件显示关闭的icon
2、经测试title不为空可以使用关闭icon能正常关闭

### 重现步骤

1、点击关闭icon （需要运行在苹果设备的浏览器,我在微信内置浏览器测试的）
2、组件不关闭（安卓手机表现正常）

### 设备/浏览器

苹果13mini等苹果系统上谷歌浏览器、微信内置浏览器

**Comment by wjw-gavin** [comment]
已复现，稍后会修复哈
