### ISSUE TITLE
[Bug Report] uploader组件 当show-upload="false"的时候 uploader.chooseFile() 无法调用

### ISSUE THREAD

**Issue by pocketChao** [youzan/vant#11217]
### 重现链接

https://codesandbox.io/s/keen-nobel-to5vne?file=/src/components/HelloWorld.vue

### Vant 版本

2.12.37

### 描述一下你遇到的问题。

Vue版本2.6.10当show-upload="false"的时候 uploader.chooseFile() 无法调用

### 重现步骤

https://codesandbox.io/s/keen-nobel-to5vne?file=/src/components/HelloWorld.vue 点击上传附件

### 设备/浏览器

Chrome

**Comment by wjw-gavin** [comment]
看了下代码，现在是如果`show-upload="false"`，则不渲染`Input`，因此无法触发`chooseFile()`。

@chenjiahan  是否可以改成 `show-upload`只控制是否显示，不影响渲染？

或者需要完善下文档？不然确实会造成误解...（只是隐藏了）
![image](https://user-images.githubusercontent.com/19986739/199696197-a4c20f2d-bbee-4347-b65a-4957a54e7241.png)

**Comment by chenjiahan** [comment]
@wjw-gavin 确实只控制显示更合理些，可以改一波

**Comment by wjw-gavin** [comment]
> @wjw-gavin 确实只控制显示更合理些，可以改一波

ok

**Comment by cy920820** [comment]
觉得可以加控制，比如是否只是控制显隐，这个场景还是蛮常见的

**Comment by wjw-gavin** [comment]
已修复~

**Comment by chenjiahan** [comment]
已发布 vant@2.12.52 版本
