### ISSUE TITLE
[Bug Report] Title

### ISSUE THREAD

**Issue by xiangdream** [youzan/vant#11210]
### Reproduction Link

TabBar 下面的 几个页面如何切换 tabbar item 页面只实例化一次

### Vant Version

2.X

### Describe the Bug

2个tabitem 页面 分别对应A页面，B页面，当在A页面切换到B 页面，再切换到A页面，此时点击浏览器的返回按钮，会先到B页面，再点击返回又到A页面，会导致 A页面 不能直接点击返回 退出应用，请问这个问题如何解决

### Reproduce Steps

1. 默认进入A页面
2. 切换到 tabbar 到B页面
3. 切换tabbar 到 A 页面
4. 此时点击浏览器的返回 会进入到B页面，能不能此时在A页面点击返回的时候退出tabbar 的页面，而不是进入到B页面

**Comment by wjw-gavin** [comment]
你的意思应该是tabbar的相关页面共用一个url的`history 栈`吧？`replace`可以实现你要的效果
![image](https://user-images.githubusercontent.com/19986739/199633887-8da55274-341a-402a-9484-fd568ffe44ba.png)
