### ISSUE TITLE
vant4在使用vite3.0.9后，发出警告

### ISSUE THREAD

**Issue by cjh-store** [youzan/vant#11219]
### 重现链接

https://github.com/cjh-store/demo

### Vant 版本

4.0.0

### 描述一下你遇到的问题。

启动过程中发出警告 排除后是因为@rollup/plugin-inject导致 只要使用，就会发出警告
![image](https://user-images.githubusercontent.com/88535245/199860815-a57dddc4-33a4-4bb3-84e9-6ece0f1b8ec4.png)

### 重现步骤

创建vite基础项目
按需引入vant
使用@rollup/plugin-inject

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
看起来跟 Vant 没有直接关系，建议自行排查下。
