### ISSUE TITLE
[Bug Report] van-image 在瀏覽器過度捲動時有性能問題

### ISSUE THREAD

**Issue by wwwtony5488** [youzan/vant#11227]
### 重现链接

無

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

頁面中包含 van-image 組件，且長度足夠捲動時，將頁面捲至底部，並向上繼續過度捲動到頁面產生延展效果後放開，回縮的頁面有非常明顯的延遲效果。

暫時使用 CSS 阻止瀏覽器可以過度捲動，避免此問題。
overscroll-behavior: none

### 重现步骤

步驟如上述，使用 Android 的 Chrome 瀏覽器即可重現。經測試 iPhone 裝置皆無此問題。

### 设备/浏览器

Android / Chrome

**Comment by chenjiahan** [comment]
1. 能提供个复现问题的 codesandbox 链接吗?
2. 原生 img 标签是否有类似的问题？
