### ISSUE TITLE
Picker 选择器，添加支持数据循环滚动功能

### ISSUE THREAD

**Issue by Nancy2013** [youzan/vant#11220]
### 这个功能解决了什么问题？

使用Picker选择器组件展示数据，希望滑动数据触底，或者滑到顶之后，可以循环滚动展示数据

### 你期望的 API 是什么样子的？

给Picker 选择器添加loop属性，可以支持循环滚动

```xml
<van-picker  :loop="true" />
```

**Comment by chenjiahan** [comment]
没有计划支持呢，这个不太好实现

**Comment by Nancy2013** [comment]
> 没有计划支持呢，这个不太好实现

在已有picker组件的基础上，自己可以扩展这个功能么，能不能提供下解决思路，谢谢了

**Comment by chenjiahan** [comment]
应该没法扩展，可以考虑 fork 代码搞一下

**Comment by Nancy2013** [comment]
> 应该没法扩展，可以考虑 fork 代码搞一下

有其他vue组件可以实现的么，能不能推荐下，网上没有找到vue框架下的

**Comment by chenjiahan** [comment]
暂时没看到类似的

**Comment by Nancy2013** [comment]
好的，谢谢了
