### ISSUE TITLE
[Bug Report] Area组件当地区码的中间两位相同时，无法正确选择

### ISSUE THREAD

**Issue by novaalone** [youzan/vant#11231]
### 重现链接

https://codesandbox.io/s/trusting-snow-jpuelj?file=/src/App.vue

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

以湖北省和海南省为例，存在以下这些省级直辖县、区的情况，他们的中间两位地区码是相同的，但是数据是归属于市这一层级的，市这一级只取了中间两位做为key，导致他们的key相同，无法作出正确选择

- 湖北省
    - 429004: "仙桃市",
    - 429005: "潜江市",
    - 429006: "天门市",
    - 429021: "神农架林区",
- 海南省
    - 469001: '五指山市',
    - 469002: '琼海市', 
    - 469005: '文昌市',
    -  469006: '万宁市',
    -  469007: '东方市', 
    - 469021: '定安县',
    -  469022: '屯昌县',
    -  469023: '澄迈县', 
    - 469024: '临高县', 
    - 469025: '白沙黎族自治县',
    -  469026: '昌江黎族自治县',
    -  469027: '乐东黎族自治县', 
    - 469028: '陵水黎族自治县',
    -  469029: '保亭黎族苗族自治县', 
    - 469030: '琼中黎族苗族自治县'

### 重现步骤

1. areaList数据如下：
const areaList ={
        province_list: {
          420000: "湖北省",
        },
        city_list: {
          420100: "武汉市",
          420200: "黄石市",
          420300: "十堰市",
          420500: "宜昌市",
          420600: "襄阳市",
          420700: "鄂州市",
          420800: "荆门市",
          420900: "孝感市",
          421000: "荆州市",
          421100: "黄冈市",
          421200: "咸宁市",
          421300: "随州市",
          422800: "恩施土家族苗族自治州",
          429004: "仙桃市",
          429005: "潜江市",
          429006: "天门市",
          429021: "神农架林区",
        },
        county_list: {
          420102: "江岸区",
          420103: "江汉区",
          420104: "硚口区",
          420105: "汉阳区",
          420106: "武昌区",
          420107: "青山区",
          420111: "洪山区",
          420112: "东西湖区",
          420113: "汉南区",
          420114: "蔡甸区",
          420115: "江夏区",
          420116: "黄陂区",
          420117: "新洲区",
          420202: "黄石港区",
          420203: "西塞山区",
          420204: "下陆区",
          420205: "铁山区",
          420222: "阳新县",
          420281: "大冶市",
          420302: "茅箭区",
          420303: "张湾区",
          420304: "郧阳区",
          420322: "郧西县",
          420323: "竹山县",
          420324: "竹溪县",
          420325: "房县",
          420381: "丹江口市",
          420502: "西陵区",
          420503: "伍家岗区",
          420504: "点军区",
          420505: "猇亭区",
          420506: "夷陵区",
          420525: "远安县",
          420526: "兴山县",
          420527: "秭归县",
          420528: "长阳土家族自治县",
          420529: "五峰土家族自治县",
          420581: "宜都市",
          420582: "当阳市",
          420583: "枝江市",
          420602: "襄城区",
          420606: "樊城区",
          420607: "襄州区",
          420624: "南漳县",
          420625: "谷城县",
          420626: "保康县",
          420682: "老河口市",
          420683: "枣阳市",
          420684: "宜城市",
          420702: "梁子湖区",
          420703: "华容区",
          420704: "鄂城区",
          420802: "东宝区",
          420804: "掇刀区",
          420822: "沙洋县",
          420881: "钟祥市",
          420882: "京山市",
          420902: "孝南区",
          420921: "孝昌县",
          420922: "大悟县",
          420923: "云梦县",
          420981: "应城市",
          420982: "安陆市",
          420984: "汉川市",
          421002: "沙市区",
          421003: "荆州区",
          421022: "公安县",
          421023: "监利市",
          421024: "江陵县",
          421081: "石首市",
          421083: "洪湖市",
          421087: "松滋市",
          421102: "黄州区",
          421121: "团风县",
          421122: "红安县",
          421123: "罗田县",
          421124: "英山县",
          421125: "浠水县",
          421126: "蕲春县",
          421127: "黄梅县",
          421181: "麻城市",
          421182: "武穴市",
          421202: "咸安区",
          421221: "嘉鱼县",
          421222: "通城县",
          421223: "崇阳县",
          421224: "通山县",
          421281: "赤壁市",
          421303: "曾都区",
          421321: "随县",
          421381: "广水市",
          422801: "恩施市",
          422802: "利川市",
          422822: "建始县",
          422823: "巴东县",
          422825: "宣恩县",
          422826: "咸丰县",
          422827: "来凤县",
          422828: "鹤峰县",
        },
      },
2、选择天门市，点击确定
3、会变成仙桃市

**Comment by chenjiahan** [comment]
我用 vant v4 试了下没复现，建议你直接升级 vant v4 哈
![image](https://user-images.githubusercontent.com/7237365/201502458-c4cbced2-4ff2-4997-98dd-93079d1b77bf.png)

目前 v4 的最新版是 4.0.0-rc.6，迁移指南：https://vant-ui.github.io/vant/v4/#/zh-CN/migrate-from-v3
