### ISSUE TITLE
Vant2.12.15使用loading报错

### ISSUE THREAD

**Issue by lvzhiming0808** [youzan/vant#11237]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-688ihr?file=/src/App.vue

### Vant 版本

v1.12.15

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/31882502/200756161-8fdb6285-77eb-49f8-a024-0ed8cc7a4bc1.png)
![image](https://user-images.githubusercontent.com/31882502/200756187-30d0a629-67e0-4b78-b2f8-41e14793347c.png)

### 重现步骤

引入就报错

**Comment by lxchuan12** [comment]
你这个重现链接好像不太对吧~不是你截图中的demo

**Comment by lvzhiming0808** [comment]
> 你这是这个链接的对吧~不是你截图中的demo

更新了

**Comment by lxchuan12** [comment]
这个版本下都可能没有 Loading.name，你输出 Loading 看看 。没必要加。另外你可以点开报错看看具体情况，大概率是你写法问题不是组件库的问题

**Comment by lvzhiming0808** [comment]
![image](https://user-images.githubusercontent.com/31882502/200774245-5e102a80-9f78-499c-bc6a-8fa9010633e3.png)
更改后you又报另一个错误
![image](https://user-images.githubusercontent.com/31882502/200774348-eb64c3a7-0b26-48b5-b3db-1abd6f2e1a59.png)

**Comment by lxchuan12** [comment]
如果是 `vant 2.x` 版本，这样注册应该是对的。

```js
import { Loading } from "vant";

@Component({
  components: {
    [Loading.name]: Loading,
  },
})
```

你提升下 `vant`的版本试试，会不会报 `key` 的这个错。

标题写的是 `Vant 2.12.15` 内容又写的是 `1.12.15` 。

**Comment by lxchuan12** [comment]
用 `TS`，其实可以用 `vue3` 啊。关键你提供的 `demo` 也不对呀。别人不好复现这个问题。

或许你可以把你现在的项目，最小化的可复现的提交到 `github` ，然后发这个链接到这里。

这样才能更好的帮助别人复现问题，从而解决问题。

**Comment by lvzhiming0808** [comment]
> 用 `TS`，其实可以用 `vue3` 啊。关键你提供的 `demo` 也不对呀。别人不好复现这个问题。
> 
> 或许你可以把你现在的项目，最小化的可复现的提交到 `github` ，然后发这个链接到这里。
> 
> 这样才能更好的帮助别人复现问题，从而解决问题。

嗯你说的没错 vue可以用ts，但是我们公司规定只能用vue2所以也只能对标vant2x版本

**Comment by lxchuan12** [comment]
嗯嗯，那有空提供下最小化可复现的代码，提交到 `github`，便于复现解决问题

**Comment by chenjiahan** [comment]
先 close 咯，有复现 demo 的话再 reopen

**Comment by johe-a** [comment]
遇到了同样的问题，请问有解决方案吗？
