### ISSUE TITLE
[Bug Report] 使用 bael-loader 导致样式文件(less)失效

### ISSUE THREAD

**Issue by luozejian** [youzan/vant#11233]
### Reproduction Link

/

### Vant Version

2.12.51

### Describe the Bug

babel-plugin-import配置:  ["import", {
    "libraryName": "vant",
    "libraryDirectory": "es",
    "style": (name)=>{
      return `${name}/style/less.js`;
    }
  }

### Reproduce Steps

单独使用babel-loader正常,加上 thread-loader 就失效

**Comment by chenjiahan** [comment]
1. 建议别用 thread-loader
2. 这个是编译配置的问题，和 vant 没啥关系
