### ISSUE TITLE
reopen#8863：vant样式优先级太高

### ISSUE THREAD

**Issue by scarsu** [youzan/vant#11235]
你可以把 CSS 变量设置在其他节点上，这些节点可以覆盖 root 节点，比如 `#app`

```css
#app {
  ....
}
```

_Originally posted by @chenjiahan in https://github.com/youzan/vant/issues/8863#issuecomment-861946351_

**Comment by scarsu** [comment]
在main.js最后引入自定义的:root变量，还是会被vant覆盖(用了vite+VantResolver)，看了生成的代码发现是因为vant样式引入的时机很晚。
为了覆盖vant自带的:root变量，要用优先级更高的#app去定义变量，这合理吗？
作为一个基础ui库，样式应该最早引入，而不是让使用者费尽心力去覆盖样式啊。

**Comment by chenjiahan** [comment]
引入的时机是你自己决定的，和 Vant 有什么关系

**Comment by scarsu** [comment]
引入时机是VantResolver决定的

**Comment by chenjiahan** [comment]
VantResolver 是社区里的插件，不是 Vant 提供的

**Comment by scarsu** [comment]
不是你官方文档里推荐的吗

**Comment by chenjiahan** [comment]
你可以到这个仓库下面反馈 https://github.com/antfu/unplugin-vue-components

**Comment by chenjiahan** [comment]
另外 unplugin-vue-components 在文档里并不是最推荐的用法，对于初级用户，你用最简单的用法就行

![image](https://user-images.githubusercontent.com/7237365/200730840-85e16f7e-cbb3-4b0b-aec4-ea4a28d26650.png)
