### ISSUE TITLE
[Feature Request] ImagePreview 增加长按事件

### ISSUE THREAD

**Issue by pocketChao** [youzan/vant#11238]
### 这个功能解决了什么问题？

ImagePreview有计划增加长按监听吗，因为这个场景还是很常见的

### 你期望的 API 是什么样子的？

<van-image-preview v-model="show" :images="images" @long-press="onLongPress">
  <template v-slot:index>第{{ index }}页</template>
</van-image-preview>

**Comment by chenjiahan** [comment]
可以的，后续会在 v4 版本支持

**Comment by qyn980427** [comment]
您好 v2版本是否也可以支持这个功能，因为有些图片具有版权，不太想让预览的时候可以唤起菜单保存或者转发图片

**Comment by chenjiahan** [comment]
v2 不再迭代新功能了哈，有需要可以提 PR 喔
