### ISSUE TITLE
震惊 , Overlay.mjs竟然出现这个bug

### ISSUE THREAD

**Issue by Verdicts-ye** [youzan/vant#11239]
### 重现链接

附件 uni小程序项目 install 后 运行项目出现这个错误

### Vant 版本

4.0.0-rc.6

### 描述一下你遇到的问题。

'vShow' is not exported by node_modules/.pnpm/registry.npmmirror.com+@dcloudio+uni-mp-vue@3.0.0-alpha-3060720221018006/node_modules/@dcloudio/uni-mp-vue/dist/vue.runtime.esm.js, imported by node_modules/vant/es/overlay/Overlay.mjs
at ../node_modules/vant/es/overlay/Overlay.mjs:1:73
1: import { withDirectives as _withDirectives, createVNode as _createVNode, vShow as _vShow } from "vue";
2: import { ref, Transition, defineComponent } from "vue";
3: import { isDef, extend, truthProp, numericProp, unknownProp, preventDefault, createNamespace, getZIndexStyle } from "../utils/index.mjs";

### 重现步骤

再配置import { VantResolver } from 'unplugin-vue-components/resolvers' 时候
被提示需要build.rollupOptions.external 
之后vite配置了

build: {
		rollupOptions: {
			external: ['@vant/use','@vant/popperjs']
		}
	},
[uni-preset-vue-vite-ts.zip](https://github.com/youzan/vant/files/9976852/uni-preset-vue-vite-ts.zip)

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
震惊之前先看下文档😂  

https://vant-ui.github.io/vant/#/zh-CN/faq#shi-fou-zhi-chi-zai-uni-app-zhong-shi-yong

![image](https://user-images.githubusercontent.com/7237365/200995553-f090ba7e-0321-4a4d-8407-0aeace4cbbd9.png)

**Comment by Verdicts-ye** [comment]
我看了呀,这个问题vite在build编译时候就出现问题了,这个是uniapp导致的吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月10日(星期四) 中午11:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant] 震惊 , Overlay.mjs竟然出现这个bug (Issue #11239)





 
震惊之前先看下文档😂
 
https://vant-ui.github.io/vant/#/zh-CN/faq#shi-fou-zhi-chi-zai-uni-app-zhong-shi-yong

**Comment by Nakus0426** [comment]
你觉得uni-app的vue是完整的吗 :)
