### ISSUE TITLE
使用van-swipe，纵向滚动，ios端没有动画效果，安卓端是好的「严重BUG」

### ISSUE THREAD

**Issue by lvzhiming0808** [youzan/vant#11240]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-lqgy87?file=/src/main.js

### Vant 版本

v2.12.51

### 描述一下你遇到的问题。

使用van-swipe，纵向滚动，ios端没有动画效果，安卓端是好的「严重BUG」

### 重现步骤

展示即可出现

### 设备/浏览器

ios手机

**Comment by wjw-gavin** [comment]
iphone 12 未复现

**Comment by lvzhiming0808** [comment]
> iphone 12 未复现


https://user-images.githubusercontent.com/31882502/200990833-ea4d7ac9-f1c3-4ea5-a69a-1dda9f6e571c.mp4

iphone 11的 直接切换没有上翻的动画

**Comment by lvzhiming0808** [comment]
比较着急

**Comment by lvzhiming0808** [comment]
官方可以给个结论吗

**Comment by wjw-gavin** [comment]
<img width="710" alt="image" src="https://user-images.githubusercontent.com/19986739/201252812-09db4ca6-4803-478e-946d-de5ad8da074c.png">

非致命 bug 或兼容性等问题将不在官方团队的处理范围内。

你可以尝试修复下然后提交PR~

**Comment by lvzhiming0808** [comment]
> PR~

但是vant3 不支持vue2啊，有没有可能vant3支持vue2呢，或者咱们官方有没有计划？

**Comment by wjw-gavin** [comment]
> 但是vant3 不支持vue2啊，有没有可能vant3支持vue2呢，或者咱们官方有没有计划？

vant3 有个分支是2.x，这个分支是vue2版本的，修复后提交合并到这个分支就OK~

**Comment by chenjiahan** [comment]
Vant 3 没有计划支持 Vue 2 哈

**Comment by Huang8013** [comment]
哎, 我也遇到了这个问题... 无解, 头疼
