### ISSUE TITLE
[Feature Request] 请问vue 3的sku组件什么时候能出？

### ISSUE THREAD

**Issue by juzijun2020** [youzan/vant#11241]
### 这个功能解决了什么问题？

请问vue 3的sku组件什么时候能出？现在一直用vant 2 想升级，又没有SKU组件

### 你期望的 API 是什么样子的？

请问vue 3的sku组件什么时候能出？现在一直用vant 2 想升级，又没有SKU组件

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/10336
