### ISSUE TITLE
[Bug Report]  useCustomFieldValue 在Uploader 组件不起作用，只能返回Uploader的默认属性。

### ISSUE THREAD

**Issue by guozl1984** [youzan/vant#11256]
### 重现链接

git 上面没有， codesandbox 打不开，按照文档的标准用法。我再下面描述中详细说明。

### Vant 版本

v3.6.5 

### 描述一下你遇到的问题。

同样的功能，我从vant最新版本到较久版本，挨着尝试，直到v3.4.9 是正常的，和文档描述一直。 3.5.4 、3.6.5均有问题，无法返回自定义值，跟踪打印日志不会触发自定义的useCustomFieldValue 内容。 
![image](https://user-images.githubusercontent.com/50489864/201850856-ab2bfcb9-fc00-4c1e-a391-c2f197b2fd0b.png)

UploaderCustom 的组件
![image](https://user-images.githubusercontent.com/50489864/201851429-c17cf2ae-9859-4591-849c-27d648caf042.png)

### 重现步骤

正常流程的必现问题。按照你们的官方文档编写代码就能复现。

### 设备/浏览器

任意设备和浏览器上。

**Comment by lxchuan12** [comment]
如果打不开 `codesandbox`，可以把你的代码最小化复现，把粘贴到 `issue`，或者提交到  `github` 。也方便别人复现验证问题~只截图不好复现。问题描述的更明白更容易得到解决。

可能是你没有注册自己写的组件？参考这个 `issue` 试试：[useCustomFieldValue官网示例不生效](https://github.com/youzan/vant/issues/10770)

**Comment by A-Ning-a** [comment]
这个bug最后为什么被关闭了?貌似还没有修复吧？
最后楼主是怎么解决的呢？我目前最新3.6.11版本也存在无法取得自定义表单项数据的问题，我很确定我是按照官方文档的方式写的，像楼主所说的，退回到3.4.9是能够正常使用的，非常希望官方能够尽快修复，3q~
