### ISSUE TITLE
[Bug Report] 使用unplugin-vue-components后，Chrome代码调试错位

### ISSUE THREAD

**Issue by jayzch** [youzan/vant#11250]
### 重现链接

-

### Vant 版本

3.6.5

### 描述一下你遇到的问题。

在vue组件中  键入 debug，在浏览器中无法准确定位到代码所在行。
在发生错误时，堆栈所显示的代码行数也有这样的问题。

感觉好像是，使用了unplugin-vue-components后，从某个版本开始就这样了。

### 重现步骤

![image](https://user-images.githubusercontent.com/5292764/201502688-2f7ce268-c11a-4547-af3f-7614c2c5cb7b.png)

**Comment by chenjiahan** [comment]
关于 unplugin-vue-components 的问题，请到对应仓库反馈：https://github.com/antfu/unplugin-vue-components
