### ISSUE TITLE
[Feature Request] filed组件在ios上没有失焦

### ISSUE THREAD

**Issue by chengfengfengwang** [youzan/vant#11259]
### 这个功能解决了什么问题？

在ios上点击输入框的其他区域期望可以让光标失焦

### 你期望的 API 是什么样子的？

修改field输入默认行为

**Comment by wjw-gavin** [comment]
iPhone 12  16.1.1  表现正常

**Comment by chenjiahan** [comment]
可能是点击到 label 了吧？ 点击 label 会聚焦到输入框，这个是 HTML 规范。

**Comment by whc0326** [comment]
有方案吗，点击其他区域软键盘不收起
