### ISSUE TITLE
vant 3.6.5 unplugin-vue-components/resolvers import 引入报错

### ISSUE THREAD

**Issue by zhonglin0829** [youzan/vant#11258]
### vant版本
3.6.5
### 问题
通过 import 按需 导入 unplugin-vue-components  vant 失败，
### 配置如下
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import Pages from 'vite-plugin-pages'

import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
// ele-Ui
import { VantResolver } from 'unplugin-vue-components/resolvers'

export default defineConfig({
  plugins: [
    vue(),
    Pages({
      dirs: 'src/views',  // 需要生成路由的文件的目录,
      exclude: ['**/components/*.vue']  // 排除在外的目录，将所有 components 目录下的 .vue 文件排除
    }),
    AutoImport({
      dts:'src/auto-imports.d.ts',// 可以自定义文件生成的位置，默认是根目录下，使用ts的建议放src目录下
      dirs: ['src/utils','src/store','src/utils'],//js全局Api挂载
      imports: ['vue','vue-router'],
    }),
    Components({
      resolvers:[EVantResolver()],
      dts: 'src/components.d.ts'
    })
  ],
  },
  resolve:{
    extensions:['.js', '.ts', '.jsx', '.tsx', '.json', '.vue'],//忽略导入文件的后缀名
  }
})

### 报错信息
[plugin:vite:import-analysis] Failed to resolve import "vant/es" from "src\views\login\index.vue". Does the file exist?
F:/product/testVant/template/src/views/login/index.vue:2:52
1  |  /* unplugin-vue-components disabled */import __unplugin_components_2 from 'F:/product/testVant/template/src/components/HelloWorld.vue';
2  |  import { Button as __unplugin_components_1 } from 'vant/es';import 'vant/es/button/style/index';
   |                                                     ^
3  |  import { ElButton as __unplugin_components_0 } from 'element-plus/es';import 'element-plus/es/components/button/style/css';
4  |  import { apiGet } from 'F:/product/testVant/template/src/utils/api.js';

**Comment by chenjiahan** [comment]
麻烦提供一个复现该问题的最小仓库链接。

**Comment by zhonglin0829** [comment]
> 麻烦提供一个复原该问题的最小仓库链接。

https://github.com/zhonglin0829/vantSubmitProblem-import.git

**Comment by chenjiahan** [comment]
@zhonglin0829 项目里自定义了 resolve.extensions，但是漏掉了 .mjs 后缀，所以找不到 vant 里的 .mjs 模块

<img width="1766" alt="image" src="https://user-images.githubusercontent.com/7237365/203686008-4ca3aa0d-2172-43f7-ae7a-1ee61abe0d7c.png">
