### ISSUE TITLE
[Bug Report] van-list loading参数初始化问题

### ISSUE THREAD

**Issue by LoveofRedMoon** [youzan/vant#11266]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-e4v9c7?file=/src/App.vue

### Vant 版本

3.6.5

### 描述一下你遇到的问题。

文件：vant/tree/main/packages/vant/src/list
问题：loading 参数为异步参数，但是它只在updated的时候与props.loading进行同步，未进行初始化设置

```js
// 原
const loading = ref(false)
// 需修正
const loading = ref(props.loading || false)
```

引发问题：若外部组件在setup阶段就进行数据加载，将props.loading置为true时，但是loading为false，会导致又触发一次load方法

### 重现步骤

打开链接即可看到，一开始加载了两次

**Comment by chenjiahan** [comment]
确实有这个问题，下个版本会修复哈
