### ISSUE TITLE
自动按需引入组件-文档描述有问题

### ISSUE THREAD

**Issue by hexiaokang** [youzan/vant#11263]
### 重现链接

https://vant-ui.github.io/vant/v2/#/zh-CN/quickstart#fang-shi-yi.-zi-dong-an-xu-yin-ru-zu-jian-tui-jian

### Vant 版本

2.XX

### 描述一下你遇到的问题。

<img width="552" alt="image" src="https://user-images.githubusercontent.com/16911432/202466595-c0fd680b-b331-4b96-9db4-f3f51dd1b97a.png">
`直接引入 Vant 组件`是什么意思？不用注册么？不注册直接报错。

### 重现步骤

<img width="552" alt="image" src="https://user-images.githubusercontent.com/16911432/202466595-c0fd680b-b331-4b96-9db4-f3f51dd1b97a.png">

**Comment by lxchuan12** [comment]
要注册啊。我觉得这里指的直接引入 `Vant` 不需要像像下面这样分开引入 `js` 和 `css`。

### 方式二. 手动按需引入组件
在不使用插件的情况下，可以手动引入需要的组件。

```
import Button from 'vant/lib/button';
import 'vant/lib/button/style';
```

**Comment by chenjiahan** [comment]
嗯嗯，楼上正解。

此处文档指的只是「引入方式」差异，与注册组件无关。

**Comment by hexiaokang** [comment]
OKThanks♪(･ω･)ﾉ
