### ISSUE TITLE
[Bug Report] Field组件在设置type="textarea"的情况下不能输入，点击无法聚焦到输入框

### ISSUE THREAD

**Issue by JanYork** [youzan/vant#11264]
### 重现链接

https://github.com/JanYork/ToTimeMail/tree/TestDemo

### Vant 版本

^3.6.5

### 描述一下你遇到的问题。

在VitePress中，每个组件使用单独的手动导入，如：
import CellGroup from 'vant/es/cell-group/index';
import 'vant/es/cell-group/style/index';
import Field from 'vant/es/field/index';
import 'vant/es/field/style/index';
这样情况下，这样使用：
<Field
            v-model="data.addressDetailed"
            label="详细地址"
            placeholder="详细地址"
            maxlength="35"

            rows="1"
            autosize
            type="textarea"
        />

出现鼠标点击输出框鼠标不聚焦，光标不显示，placeholder属性的内容也一样不显示的问题

### 重现步骤

鼠标点击输出框鼠标不聚焦，光标不显示，placeholder属性的内容也一样不显示。

### 设备/浏览器

Win11，Edge浏览器，移动端模拟

**Comment by chenjiahan** [comment]
看起来是项目里的 CSS 把输入框隐藏了，与 Vant 无关
![image](https://user-images.githubusercontent.com/7237365/202846735-2c1d25ba-b3b4-4f25-94e5-824e88816dca.png)

**Comment by JanYork** [comment]
> 看起来是项目里的 CSS 把输入框隐藏了，与 Vant 无关
> ![image](https://user-images.githubusercontent.com/7237365/202846735-2c1d25ba-b3b4-4f25-94e5-824e88816dca.png)
> 

确实是，感谢感谢
