### ISSUE TITLE
ts使用Toast

### ISSUE THREAD

**Issue by leehiuching** [youzan/vant#11281]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-ri85l1?file=/src/request.ts

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

ts 使用 Toast，提示“Toast is not defined at eval”

### 重现步骤

import {Toast} from 'vant';
Toast.fail('xxx')

### 设备/浏览器

chrome

**Comment by wjw-gavin** [comment]
这不是正常么？

![image](https://user-images.githubusercontent.com/19986739/203187551-30dea66f-e5de-4032-93f0-0b21d83d79ef.png)
