### ISSUE TITLE
[Bug Report] popup弹出层组件的z-index为什么会持续增加。请看附图

### ISSUE THREAD

**Issue by hexiaokang** [youzan/vant#11285]
### 重现链接

请看图

### Vant 版本

latest-v2

### 描述一下你遇到的问题。

popup组件在关闭重新打开后，z-index会持续增加。如图，这样会导致需要高优展示自身代码组件的地方难以控制z-index。
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/16911432/203557932-5a01aa71-4706-4b9a-91c6-4926b59b3d96.png">

### 重现步骤

展示、关闭、展示、关闭，，，，

### 设备/浏览器

Mac-Chrome

**Comment by chenjiahan** [comment]
Vant 中所有弹窗类组件的 z-index 都会自动递增，这主要是为了保证同时使用多个 Vant 弹窗类组件时，可以正确地显示最后打开的弹窗。

通常来说，你可以把所有需要弹窗的内容都通过 Popup 组件来管理。如果有一些特殊情况需要自己设置 z-index，可以设置一个较大的数字，比如 3000。

**Comment by lizyChy0329** [comment]
有没有导出类似 antDesign 的 useZIndex 的 Composables?
