### ISSUE TITLE
[Bug Report] Field 输入框设置maxlength后，到达限制长度后从中间输入一个字符，光标会自动到最后一位，原生input框焦点不会变

### ISSUE THREAD

**Issue by wanglei19921105** [youzan/vant#11289]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/field

### Vant 版本

3.6.5

### 描述一下你遇到的问题。

Field 输入框设置maxlength后，到达限制长度后从中间输入一个字符，光标会自动到最后一位，原生input框焦点不会变

### 重现步骤

设置maxlength
输入到最大长度
从焦点在中间区域
输入字符
光标就会跳到最后一位

**Comment by chenjiahan** [comment]
后续会优化下，不过用 JS 实现的时候，光标会后移一位，不能像原生 maxlength 那样保持不动
