### ISSUE TITLE
vant2.0自定义类名前缀，现在默认是van且无法修改

### ISSUE THREAD

**Issue by adndyxu** [youzan/vant#11280]
### 这个功能解决了什么问题？

规避npm包中的vant样式对 其他项目的影响

### 你期望的 API 是什么样子的？

prefix:'myclass'

**Comment by chenjiahan** [comment]
没有计划支持修改类名前缀哈。

如果有多个项目引用了不同版本的 Vant，建议你看下社区里的微前端样式隔离方案。
