### ISSUE TITLE
[Bug Report] @vant/area-data数据大连市缺少 金普新区 这一条数据

### ISSUE THREAD

**Issue by imsole** [youzan/vant#11288]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/area

### Vant 版本

1.10.7

### 描述一下你遇到的问题。

如标题，area/data数据缺少数据，大连市 缺少 金普新区

### 重现步骤

这个就不用重现了吧。我吧地址贴出来https://www.dl.gov.cn/col/col3555/index.html

### 设备/浏览器

小程序

**Comment by chenjiahan** [comment]
跟金州区是同一个吧：

<img width="554" alt="image" src="https://user-images.githubusercontent.com/7237365/203712385-98e1a3ee-3402-46e2-aa07-afd20c724a2a.png">

而且国家的行政区划表里也没有单独划分 金普新区

https://www.mca.gov.cn/article/sj/xzqh/1980/
