### ISSUE TITLE
求支持uniapp

### ISSUE THREAD

**Issue by 2017lhy** [youzan/vant#11286]
### 这个功能解决了什么问题？

uniapp 本身就具有跨端功能，且基于vue，与其弄好几个版本（h5、微信小程序、支付宝小程序），不如做一版uniapp的

### 你期望的 API 是什么样子的？

uniapp support

**Comment by chenjiahan** [comment]
暂时没有这个计划哈，我们的精力有限，并且跨端框架对组件的能力会有很多限制，因此倾向于维护现有的 vant/vant-weapp。
