### ISSUE TITLE
小米手机oppo手机上传图片没问题就是喊醒没有文件，上传没有文件，有没有大佬能解决一下

### ISSUE THREAD

**Issue by 13253561651** [youzan/vant#11282]
### 重现链接

小米oppo手机无法上传文件

### Vant 版本

小米oppo手机无法上传文件

### 描述一下你遇到的问题。

小米oppo手机无法上传文件

### 重现步骤

小米oppo手机无法上传文件

**Comment by chenjiahan** [comment]
https://vant-ui.github.io/vant/#/zh-CN/uploader#uploader-zai-bu-fen-an-zhuo-ji-xing-shang-wu-fa-shang-chuan-tu-pian
