### ISSUE TITLE
uniapp引入vant2以后,在微信小程序报错

### ISSUE THREAD

**Issue by Eternaldream** [youzan/vant#11293]
### 重现链接

https://github.com/youzan/vant

### Vant 版本

2.12.53

### 描述一下你遇到的问题。

app.js错误:
 TypeError: Cannot read property 'userAgent' of undefined
    at isIOS (vant.js:4346)
    at Module.<anonymous> (vant.js:4355)
    at __webpack_require__ (vant.js:30)

### 重现步骤

对照官网的快速上手,引入uniapp后,运行在微信小程序开发者工具会出现

**Comment by wjw-gavin** [comment]
vant 本身并不兼容uni-app哈，而且像window或者document也无法在小程序中使用。

**Comment by aimaolizi** [comment]
请问有解决吗

**Comment by Eternaldream** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    没有,官方说不支持uniapp
    
        
            
        
    
    
    
    

    

    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月25日 11:53
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [youzan/vant] uniapp引入vant2以后,在微信小程序报错 (Issue #11293)
        
      
    
  
  

请问有解决吗
