### ISSUE TITLE
grid重大bug

### ISSUE THREAD

**Issue by wp135** [youzan/vant#11295]
### 重现链接

无

### Vant 版本

2.12.53

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/39770163/203890671-f26f5bcc-8e9e-4e29-b6e4-d0658116b535.png)

### 重现步骤

grid的线条怎么层级这么高！！！！！！

### 设备/浏览器

谷歌浏览器

**Comment by chenjiahan** [comment]
grid 线条的 z-index 是 1，并没有比 Popup 的层级高。

z-index 的生效机制比较复杂，建议你看下是不是其他 CSS 问题。
