### ISSUE TITLE
控件显示异常，且无法点击

### ISSUE THREAD

**Issue by flyOfYW** [youzan/vant#11298]
### 重现链接

https://github.com/flyOfYW/YWKeyboardKit

### Vant 版本

2.12.4

### 描述一下你遇到的问题。

UI控件显示异常，且无法点击，
比如：Button
<img width="465" alt="image" src="https://user-images.githubusercontent.com/17938752/203924662-6d1e4859-db53-4ffc-867e-a73b2c78b00a.png">

手机信息
![334e74bf1728aad0e629aab2e26342d](https://user-images.githubusercontent.com/17938752/203924714-72d4e130-cdc3-49bf-a892-ab2e466d0042.jpg)

### 重现步骤

这个是正常的效果
![11669361403_ pic](https://user-images.githubusercontent.com/17938752/203925182-5364eb22-05d3-4832-9588-49cf237c44d3.jpg)
异常效果
![7d706f371469cec5f3742cad604aa8c(1)](https://user-images.githubusercontent.com/17938752/203925227-85b7cfe2-2bab-40ae-81db-f6224edf385b.jpg)

**Comment by chenjiahan** [comment]
没遇到过类似的现象，建议看下是不是页面中植入了一些其他 CSS 导致组件的样式被覆盖了。

**Comment by flyOfYW** [comment]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/17938752/204174653-23029a91-a9ae-4164-b920-5460bb9e16c5.png">
每天其他de的css,这里只有当前页面的css，目前用户反馈，用两款安卓机出现这个，而且即使css样式覆盖的，那点击事件不可能不响应吧! @chenjiahan

**Comment by flyOfYW** [comment]
我今天一个个调试了一下，最后发现问题地方，
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/17938752/205594198-3603461b-b0d9-4787-8cbb-e8c4b1df9819.png">
首先 van-button是写死在页面上，并没有通过字段显示和隐藏
getList这个函数里面有await，如果没有去掉await， van-button样式显示正常，同时点击事件生效，如果我不去掉，样式则会错乱，点击事件也不生效，即使我没有调用getList，请问为啥会这样，js为啥会影响css，难道是因为await属于es7的写法吗
