### ISSUE TITLE
什么时候VUE3版本能兼容安卓啊

### ISSUE THREAD

**Issue by Akimixu-19897** [youzan/vant#11294]
### 这个功能解决了什么问题？

赶紧兼容安卓啊

### 你期望的 API 是什么样子的？

赶紧兼容安卓啊

**Comment by chenjiahan** [comment]
一直都兼容的，你遇到什么问题了吗？

**Comment by Akimixu-19897** [comment]
> 一直都兼容的，你遇到什么问题了吗？

我是用vue3+vite+ts创建的uniapp项目，引入的vant3，运行到手机上时间选择器都在报错，提示add、remove方法不存在

**Comment by chenjiahan** [comment]
https://vant-ui.github.io/vant/#/zh-CN/faq#shi-fou-zhi-chi-zai-uni-app-zhong-shi-yong
