### ISSUE TITLE
[Bug Report] 本地启动项目后，无法切换版本了。

### ISSUE THREAD

**Issue by wjw-gavin** [youzan/vant#11306]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN

### Vant 版本

vant@4.0.0-rc.9

### 描述一下你遇到的问题。

本地启动项目后，切换版本报错。
貌似还多了一个`IP`端口

![image](https://user-images.githubusercontent.com/19986739/204081605-d73d92db-fae4-4377-bf68-ee4d4a16b7e0.png)

![image](https://user-images.githubusercontent.com/19986739/204081591-47e82759-7cc1-45c2-b399-8c1d4cde3973.png)

### 重现步骤

1、download 项目，安装依赖
2、pnpm dev 启动
3、右上角切换版本

**Comment by chenjiahan** [comment]
本地开发 vant 的时候默认就是没法切换版本的哈，因为本地只有当前版本的文档，没有其他版本。

切换版本的按钮是按相对路径来替换的。

**Comment by wjw-gavin** [comment]
好吧，，，我记得之前是可以啊...难道是我记混了么，哈哈
