### ISSUE TITLE
关于Filed 组件 clearable 属性添加，点击清除Icon无法清除输入框内容

### ISSUE THREAD

**Issue by dengweijing** [youzan/vant#11301]
### 重现链接

https://codesandbox.io/s/young-cookies-ud85nw

### Vant 版本

2.12.53

### 描述一下你遇到的问题。

关于Filed 组件 clearable 属性添加，点击清除Icon无法清除输入框内容

### 重现步骤

输入框输入内容，聚焦时出现清除图标，但是点击清除图标，清除事件未生效，同时清除图标隐藏

### 设备/浏览器

Google Chrome 107.0.5304.108

**Comment by dengweijing** [comment]
我已定位并发现这个问题，这个问题的发生是由于，监听是否聚焦的过程中，失去焦点的状态变更在清除图标消失之前，所以onClear事件永远不会触发

**Comment by wjw-gavin** [comment]
浏览器切换成手机模式就可以了。
vant本身是应用于移动端，很多事件都是基于触摸事件触发的，所以看上去的'click'事件并不会生效。

**Comment by chenjiahan** [comment]
嗯嗯，Field 组件文档底部有相关解答。

https://vant-ui.github.io/vant/#/zh-CN/field#chang-jian-wen-ti

**Comment by dengweijing** [comment]
事件这个，主要我在手机上没有生效，所以我改了，但是内部有个很关键的逻辑是清除图标失去焦点就被移除了，这个时候即使触发点击了也无效，最关键的是这里


&nbsp;


Gary
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月26日(星期六) 下午5:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant] 关于Filed 组件 clearable 属性添加，点击清除Icon无法清除输入框内容 (Issue #11301)





 
浏览器切换成手机模式就可以了。
 vant本身是应用于移动端，很多事件都是基于触摸事件触发的，所以看上去的'click'事件并不会生效。

**Comment by chenjiahan** [comment]
touchstart 早于 blur 触发，正常来说不会有你描述的现象，可以再试一下

**Comment by dengweijing** [comment]
我就是在手机上有这个问题，所以才改，不然不会去想改这个，你可以直接拿最新的2.x版本去测试，看看是不是复现
&nbsp;


Gary
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月26日(星期六) 晚上9:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant] 关于Filed 组件 clearable 属性添加，点击清除Icon无法清除输入框内容 (Issue #11301)





 
touchstart 早于 blur 触发，正常来说不会有你描述的现象，可以再试一下

**Comment by chenjiahan** [comment]
没复现。
