### ISSUE TITLE
dialog作为组件使用时报错

### ISSUE THREAD

**Issue by zhonglin0829** [youzan/vant#11323]
### 重现链接

https://github.com/zhonglin0829/problem-dialog.git

### Vant 版本

3.6.5

### 描述一下你遇到的问题。

dialog作为组件使用时，变量绑定，通过变量控制显示与否无效，初始化，会直接显示该dialog，dialog组件包裹的内容无法显示出来，且控制台会报错如下内容
runtime-core.esm-bundler.js:38 [Vue warn]: Extraneous non-props attributes (show, title, show-cancel-button) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <Dialog show=false onUpdate:show=fn title="标题"  ... > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:38
renderComponentRoot @ runtime-core.esm-bundler.js:977
componentUpdateFn @ runtime-core.esm-bundler.js:5615
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5729
setupRenderEffect @ runtime-core.esm-bundler.js:5743
mountComponent @ runtime-core.esm-bundler.js:5525
processComponent @ runtime-core.esm-bundler.js:5483
patch @ runtime-core.esm-bundler.js:5085
mountChildren @ runtime-core.esm-bundler.js:5269
processFragment @ runtime-core.esm-bundler.js:5442
patch @ runtime-core.esm-bundler.js:5078
componentUpdateFn @ runtime-core.esm-bundler.js:5622
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5729
setupRenderEffect @ runtime-core.esm-bundler.js:5743
mountComponent @ runtime-core.esm-bundler.js:5525
processComponent @ runtime-core.esm-bundler.js:5483
patch @ runtime-core.esm-bundler.js:5085
componentUpdateFn @ runtime-core.esm-bundler.js:5695
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5729
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:388
Promise.then（异步）
queueFlush @ runtime-core.esm-bundler.js:280
queuePostFlushCb @ runtime-core.esm-bundler.js:302
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1589
scheduler @ runtime-core.esm-bundler.js:1811
triggerEffect @ reactivity.esm-bundler.js:396
triggerEffects @ reactivity.esm-bundler.js:386
triggerRefValue @ reactivity.esm-bundler.js:1002
（匿名） @ reactivity.esm-bundler.js:1136
triggerEffect @ reactivity.esm-bundler.js:396
triggerEffects @ reactivity.esm-bundler.js:381
triggerRefValue @ reactivity.esm-bundler.js:1002
（匿名） @ reactivity.esm-bundler.js:1136
triggerEffect @ reactivity.esm-bundler.js:396
triggerEffects @ reactivity.esm-bundler.js:381
triggerRefValue @ reactivity.esm-bundler.js:1002
set value @ reactivity.esm-bundler.js:1047
finalizeNavigation @ vue-router.mjs:3334
（匿名） @ vue-router.mjs:3207
Promise.then（异步）
pushWithRedirect @ vue-router.mjs:3174
push @ vue-router.mjs:3099
install @ vue-router.mjs:3530
use @ runtime-core.esm-bundler.js:4365
（匿名） @ main.js?t=1669616678259:11
runtime-core.esm-bundler.js:38 [Vue warn]: Invalid VNode type: undefined (undefined) 
  at <Dialog show=false onUpdate:show=fn title="标题"  ... > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

点击取消后，再次点击按钮，控制打开dialog，无法打开，报错如下信息
runtime-dom.esm-bundler.js:35 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parentNode')
    at parentNode (runtime-dom.esm-bundler.js:35:30)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5697:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
    at instance.update (runtime-core.esm-bundler.js:5729:56)
    at updateComponent (runtime-core.esm-bundler.js:5554:26)
    at processComponent (runtime-core.esm-bundler.js:5487:13)
    at patch (runtime-core.esm-bundler.js:5085:21)
    at patchBlockChildren (runtime-core.esm-bundler.js:5390:13)
    at processFragment (runtime-core.esm-bundler.js:5453:17)
    at patch (runtime-core.esm-bundler.js:5078:17)

### 重现步骤

1.运行项目即可，
2.点击按钮

**Comment by wjw-gavin** [comment]
看这里：https://github.com/youzan/vant/issues/10858#issuecomment-1200395766
