### ISSUE TITLE
[Feature Request] 希望V4中Picker组件触发confirm事件时回调参数增加columnIndex

### ISSUE THREAD

**Issue by Leslie-Luo** [youzan/vant#11326]
### 这个功能解决了什么问题？

在项目实际应用中使用Picker触发confirm确认事件时，会使用到当前选中项在columns中的索引值。
目前V4版的事件中没有这个值，希望能添加一下

### Events

| 事件名 | 说明 | 回调参数 |
| --- | --- | --- |
| confirm | 点击完成按钮时触发 | _{ selectedValues, selectedOptions, columnIndex }_ |
| cancel | 点击取消按钮时触发 | _{ selectedValues, selectedOptions }_ |
| change | 选项改变时触发 | _{ selectedValues, selectedOptions, columnIndex }_ |
| click-option | 点击选项时触发 | _{ currentOption, selectedValues, selectedOptions, columnIndex }_ |

**Comment by wjw-gavin** [comment]
感觉你说的像是`selectedIndexs`?

**Comment by Leslie-Luo** [comment]
> 感觉你说的像是`selectedIndexes`？

是的
