### ISSUE TITLE
van-swipe bug

### ISSUE THREAD

**Issue by ArtUltimate** [youzan/vant#1132]
使用van-swipe自动播放时img单位是rem,会随机导致下方的van-cell的文字 和 轮播图同节奏上下跳动,用V-FOR的多条van-cell随机某一条文字跳动,后来调整图片尺寸和单位(van-swipe播放时尺寸是固定的还会跳),虽然van-cell的文字不跳了,但是van-tag的绘制出问题,会根据轮播图的播放节奏一起闪烁,闪烁效果是文字颜色加重,又恢复,又加重....希望给一个解决方案

**Comment by chenjiahan** [comment]
你这个描述太复杂了，最好提供一个复现的 jsffdile
