### ISSUE TITLE
[Bug Report] 使用Field字段，type设置为color，选择颜色后丢失数据绑定，内部报错

### ISSUE THREAD

**Issue by yomaGit** [youzan/vant#11337]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-1sszlc?file=/src/App.vue

### Vant 版本

v4.0.0

### 描述一下你遇到的问题。

field组件在设置type为color时，报错

### 重现步骤

1. 调用van-field组件，设置type为color
2. 选择颜色后，控制台会报错

**Comment by wjw-gavin** [comment]
应该是发版后就好了。

![image](https://user-images.githubusercontent.com/19986739/205020097-5392e551-94c5-4304-8efe-d55dc94f299a.png)

**Comment by chenjiahan** [comment]
已发布 vant@4.0.1，可以升级试一下

**Comment by yomaGit** [comment]
升级vant@4.0.1后修复了
