### ISSUE TITLE
van-field 外部样式类 input-class不生效

### ISSUE THREAD

**Issue by CutTheCrapZ** [youzan/vant#11334]
### 重现链接

1

### Vant 版本

1.10.8

### 描述一下你遇到的问题。

<view class="container">
  <headFit showImg="{{false}}" vTitle="Entry of new words"></headFit>
  <view class="body">
    <view>
        <van-field input-class="new-words" value="{{ value }}" placeholder="new words" input-align="center" border="{{ false }}" bind:change="onChange" />
    </view>
    <van-popup show="{{ show }}" position="bottom" custom-style="height: 40%;" bind:close="onClose">
      <van-picker columns="{{ partOfSpeech }}" bind:cancel="onClose" bind:confirm="selectPartOfSpeech" show-toolbar title="标题" />
    </van-popup>
  </view>
</view>

.new-word{
  background-color: transparent !important;
  width: 60vw !important;
  border-bottom: 6rpx solid #ccc;
  margin: 0;
  padding: 20rpx !important;
  height: 40rpx !important;
}

### 重现步骤

1

### 设备/浏览器

开发过程

**Comment by CutTheCrapZ** [comment]
<view class="container">
  <headFit showImg="{{false}}" vTitle="Entry of new words"></headFit>
  <view class="body">
    <view>
        <van-field input-class="new-words" value="{{ value }}" placeholder="new words" input-align="center" border="{{ false }}" bind:change="onChange" />
    </view>
    <van-popup show="{{ show }}" position="bottom" custom-style="height: 40%;" bind:close="onClose">
      <van-picker columns="{{ partOfSpeech }}" bind:cancel="onClose" bind:confirm="selectPartOfSpeech" show-toolbar title="标题" />
    </van-popup>
  </view>
</view>

**Comment by lxchuan12** [comment]
目测你用的是 vant-weapp 小程序组件库。你提 `issue` 提错了地方。

之后碰到 `vant-weapp` 的问题可以到[vant-weapp issue 区](
https://github.com/youzan/vant-weapp/issues)提。


大概率是你没有用对。

或许可以把你怎么使用的代码附上来。比如：你的环境，用的什么小程序框架。taro、uniapp、原生小程序、还是其他。
页面结构部分、样式部分、`wxml`、`wcss` 开发者调试截图，看看节点和样式是否对应上了，或者是否写对地方了。 
提的问题描述的越详细越容易被解决。

---

我用官方示例添加 input-class 正常

```bash
# 克隆
git clone https://github.com/vant-ui/vant-weapp.git
# 安装项目依赖
npm install

# 执行组件编译
npm run dev
```

打开[微信开发者工具](https://developers.weixin.qq.com/miniprogram/dev/devtools/download.html)，把`vant-weapp/example`目录添加进去就可以预览示例了。

```html
// vant-weapp/packages/field/demo/index.wxml
<demo-block title="基础用法">
  <van-cell-group>
    <van-field input-class="input-class" value="{{ value }}" placeholder="请输入用户名" border="{{ false }}" clearable />
  </van-cell-group>
</demo-block>
```

```css
// vant-weapp/packages/field/demo/index.wxml
.input-class{
  height: 100px;
}
```

我的截图。
![image](https://user-images.githubusercontent.com/15962539/204951735-cd306e21-6291-4b79-9f18-f9a07100ec49.png)

**Comment by chenjiahan** [comment]
解释的很详细了~ 这个 issue 先 close 了哈，如果还是有问题，可以到 vant-weapp issue 反馈
