### ISSUE TITLE
[Feature Request] 希望V4的Picker组件Props添加V3版本中的 default-index 即单列选择时，默认选中项的索引

### ISSUE THREAD

**Issue by Leslie-Luo** [youzan/vant#11330]
### 这个功能解决了什么问题？

在使用Picker组件经常需要设置默认选中值，目前V4版本中没有这个Props属性，希望能移植到V4中。
还有就是V3中Picker很多的实用方法希望也能移植过来
<img width="1836" alt="image" src="https://user-images.githubusercontent.com/22937782/204746582-893703c1-da09-4e9a-bf5e-ed16572899e5.png">

### Props

| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
| default-index | 单列选择时，默认选中项的索引 | _number \| string_ | `0` |

**Comment by Leslie-Luo** [comment]
> * 默认值用 v-model 来设置就可以的，不需要新增属性了。
> * 实例方法不会再提供了，建议通过 props/events 来实现相关需求，更符合 Vue 的设计理念。

好的 Thanks♪(･ω･)ﾉ

**Comment by Cleam** [comment]
@chenjiahan 
有个问题请教下：
通过`v-model`设置默认值确实可以同步选择的值，但是如果通过`v-model`来**获取选中的值**，会有问题。

因为用户如果打开`picker`，滑动几下，点了取消按钮，这个时候`v-model`对应的值也改变了。这个时候如果开发者如果用这个值去提交，其实是和用户本意不符的。

一般用`v-model`就是为了省事，直接来同步用户选择的值，但上面描述的场景确有违用户意愿。不知道大佬们一般怎么处理这种情况。

我目前做法就是用户取消的时候，还原`v-model`的值。但是感觉不够优雅且很麻烦。

**Comment by chenjiahan** [comment]
v-model 指的是 Picker 当前选中的值。

你可以另外用一个变量来保存用户在 confirm 时选中的值，这个值是用来提交的。

**Comment by Cleam** [comment]
只是觉得有点麻烦了，不能直接使用v-model的值，得在confirm里面去加逻辑。

OK，那就先这么实现。感谢大佬！
