### ISSUE TITLE
[Bug Report] Toast.fail 报错

### ISSUE THREAD

**Issue by blankzust** [youzan/vant#11332]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-jpic7i?file=/src/App.vue

### Vant 版本

4.0.0

### 描述一下你遇到的问题。

Toast.fail调用的时候提示Toast.fail is not a function

### 重现步骤

打开codesandbox链接即可重现

**Comment by blankzust** [comment]
![image](https://user-images.githubusercontent.com/8541906/204766571-1a54ca8b-062e-4f86-87a9-f0e3c0defdec.png)

**Comment by blankzust** [comment]
![image](https://user-images.githubusercontent.com/8541906/204766664-44812f98-23a0-4866-a0a0-da8f3788f55b.png)

**Comment by blankzust** [comment]
想用showToast，但是本地是ts的，会提示类型错误

**Comment by chenjiahan** [comment]
这个方法在 4.0 版本有调整，麻烦看一下迁移文档哈 https://vant-ui.github.io/vant/#/zh-CN/migrate-from-v3#toast-diao-yong-fang-shi-diao-zheng

**Comment by chenjiahan** [comment]
什么类型错误？

**Comment by blankzust** [comment]
![image](https://user-images.githubusercontent.com/8541906/204767212-66b5db98-d4d3-4a05-8ba8-a1d896401181.png)

**Comment by blankzust** [comment]
哦，pnpm的问题，pnpm升级版本可能会出现缓存问题

**Comment by blankzust** [comment]
要删除node_modules

**Comment by chenjiahan** [comment]
ok
