### ISSUE TITLE
[Bug Report] calendar 日历 round 属性没有效果

### ISSUE THREAD

**Issue by ErHu1993** [youzan/vant#11338]
### 重现链接

https://vant-contrib.gitee.io/vant/mobile.html#/zh-CN/calendar

### Vant 版本

4.0.0

### 描述一下你遇到的问题。

日历设置 round 属性无效，在你们demo页面，自定义弹出位置，demo 源码中 设置了 round 属性为false，但实际结果底部按钮依然是 round 按钮，实际使用设置 round 也是无效的。

### 重现步骤

[你们的Demo页点击“自定义弹出位置” 应该是无圆角按钮的](https://vant-contrib.gitee.io/vant/mobile.html#/zh-CN/calendar)

demo 源码内容：
![image](https://user-images.githubusercontent.com/15101170/205016948-3b89e535-fa33-48be-a174-98fb259a7c01.png)

**Comment by haiweilian** [comment]
那是设置弹出层的圆角，不是设置按钮的。

**Comment by wjw-gavin** [comment]
嗯嗯  楼上说的是对的~

**Comment by ErHu1993** [comment]
不好意思，没仔细看描述  理解错了
