### ISSUE TITLE
[Bug Report] nuxt3+vant 页面刷新image组件一直处于加载中

### ISSUE THREAD

**Issue by f-soud** [youzan/vant#11335]
### Reproduction Link

https://codesandbox.io/p/github/f-soud/nuxt3-vant/draft/cranky-ellis?file=%2Fpages%2Findex.vue

### Vant Version

nuxt3.0.0 vant(尝试了3.6.1，3.6.8，4.0.0)

### Describe the Bug

刷新页面image组件一直处于加载中，切换页面后恢复正常
![image](https://user-images.githubusercontent.com/52237907/204947527-7d61afbe-7be1-4713-b8ae-5b80e349f5cf.png)

### Reproduce Steps

项目中遇到的问题，然后自己从官方下个dome出来测试也是一样一样的，刷新image组件就会一直处在加载中
链接里有四个页面index就是正常从官方下的dome,abc根据自己想法改了一下，
a是把image组件放到自己组件里并只让客户端加载
b,c是延迟给image组件src赋值
自己也封装了个image尝试，个人感觉是nuxt3刷新时服务器和客户端都会去加载setup,服务器会比客户端快一点加载setup,服务器获取的ref是一个对象，触发不了image的onLoad，页面切换服务器不会加载setup，延迟给image赋值会触发image组件的watch，重新触发onLoad

### Device / Browser

win10,chrome

**Comment by chenjiahan** [comment]
Nuxt 3 里 Image load 事件可能不会触发，下个版本适配下
