### ISSUE TITLE
dialog弹窗，添加了before-close之后，取消了对话框，再次打开，取消按钮文案消失，一直转圈，无法点击

### ISSUE THREAD

**Issue by Kristy373664682** [youzan/vant#11347]
### 重现链接

wu

### Vant 版本

2.12.47

### 描述一下你遇到的问题。

dialog弹窗，添加了before-close之后，取消了对话框，再次打开，取消按钮文案消失，一直转圈，无法点击

### 重现步骤

1.点击dialog的取消
2.再次打开弹窗

### 设备/浏览器

浏览器

**Comment by mxyhi** [comment]
详细地址不到一定长度就会这样，超过长度就没事
![image](https://user-images.githubusercontent.com/78336556/205281383-b033e674-4f96-4c1f-90ed-bc71fb552e16.png)

**Comment by Kristy373664682** [comment]
您的邮件已经收到！感谢您的来件！

**Comment by chenjiahan** [comment]
麻烦提供有效的 codesandbox 重现链接哈
