### ISSUE TITLE
[Feature Request] 希望组件添加 一个【浮动面板】的功能 或者 【拓展 ActionSheet 动作面板】

### ISSUE THREAD

**Issue by qq735675958** [youzan/vant#11344]
### 这个功能解决了什么问题？

[在一些常用的地图导航页面常用到显示一些具体的详情信息，参考 https://mobile.ant.design/zh/components/floating-panel  这个功能。

### 你期望的 API 是什么样子的？

<van-floating-panel>
  <slot></slot>
</van-floating-panel>

**Comment by GRAMMAC1** [comment]
这个组件确定要加的话，我可以尝试提个 PR @chenjiahan

**Comment by chenjiahan** [comment]
@GRAMMAC1 可以的，搞起

**Comment by qq735675958** [comment]
大佬牛逼，大佬威武，大佬霸气，加油！鳄梨给💪

**Comment by MaybeQHL** [comment]
希望有回弹效果类似https://mobile.ant.design/zh/components/floating-panel/ 这样的

**Comment by yanbowe** [comment]
有没有上线计划时间呢？

**Comment by chenjiahan** [comment]
@GRAMMAC1 这个组件我 assign 给 @zhousg 了哈

**Comment by GRAMMAC1** [comment]
> 

可以的，sorry，我写了一部分，后面就没了。。。

**Comment by chenjiahan** [comment]
> 可以的，sorry，我写了一部分，后面就没了。。。

👋🏻👋🏻
