### ISSUE TITLE
DatetimePicker不显示，引用之后废掉

### ISSUE THREAD

**Issue by CaoKejian** [youzan/vant#11346]
### 重现链接

https://github.com/CaoKejian/mangosteen.git

### Vant 版本

3.4.8

### 描述一下你遇到的问题。

日历选择器引用后使用报错，如果使用引用的名字DatetimePicker 作为标签名，会报出 does not provide an export named 'DatetimePicker' 的错误；如果使用van-datetime-picker作为标签名（官方引用） 则什么也不显示。 测试弹出层是没有问题的。
![image](https://user-images.githubusercontent.com/113025542/205261291-697da47e-d8d4-4712-b62d-34b32a0cb7fc.png)

### 重现步骤

组件不显示

### 设备/浏览器

chrome、edge

**Comment by chenjiahan** [comment]
没复现你说的问题哈

![image](https://user-images.githubusercontent.com/7237365/205439484-2ae042a2-1ef2-4faa-be54-437eb2b4af3e.png)
