### ISSUE TITLE
请问 源码中  :class="b()"  这个b 是怎么导入的?

### ISSUE THREAD

**Issue by Nick-Tsao** [youzan/vant#1134]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
参考 https://github.com/youzan/vant/issues/1030

**Comment by Nick-Tsao** [comment]
谢谢,是我没看仔细.已经看到了 createBasic. 再往上瞅瞅其实就能找到的. 代码写的有深度 给你们点赞.

**Comment by chenjiahan** [comment]
谢谢支持~
