### ISSUE TITLE
Vant 4.0 正式发布：步履不停

### ISSUE THREAD

**Issue by chenjiahan** [youzan/vant#11356]
Vant 4.0 正式版已发布，完整介绍请移步知乎文章~  

[Vant 4.0 正式发布：步履不停](https://zhuanlan.zhihu.com/p/589088487)。

**Comment by wjw-gavin** [comment]
congratulations~

**Comment by Airkro** [comment]
暗黑模式下的样式目前不太合理，很多颜色看不清，是不是该弄个集中反馈帖？

**Comment by chenjiahan** [comment]
@Airkro 直接新开 issue 反馈就行

**Comment by laowenlu** [comment]
支持一下

**Comment by jiesir** [comment]
vant会使用vite吗

**Comment by chenjiahan** [comment]
> vant会使用vite吗

Vant 很早就在使用 vite 进行构建了，@vant/cli 是基于 vite 实现的

**Comment by jiesir** [comment]
> > vant会使用vite吗
> 
> Vant 很早就在使用 vite 进行构建了，@vant/cli 是基于 vite 实现的

抱歉，没注意cli在3.3.0之后就用了vite，sorry。
