### ISSUE TITLE
[Feature Request] Collapse希望能提供label的slot

### ISSUE THREAD

**Issue by wiexin** [youzan/vant#11366]
### 这个功能解决了什么问题？

有些折叠的内容 需要先显示一步分作为预览，这个时候最好可以自定义label 可以放自定义的图片等

### 你期望的 API 是什么样子的？

```html
<van-collapse-item name="1">
    <view slot="label"><image src="xxxx"/></view>
  </van-collapse-item>
```

**Comment by chenjiahan** [comment]
目前就支持的哈，vant@3.1.1 版本

![image](https://user-images.githubusercontent.com/7237365/206854504-242c1fad-cdc0-4266-93c4-8c78e7307e84.png)
