### ISSUE TITLE
[Feature Request] date-picker 日期选择器，返回值为数组

### ISSUE THREAD

**Issue by jenny86** [youzan/vant#11365]
### 这个功能解决了什么问题？

date-picker 现在的日期选择器返回的时间为数组还需要手动转化为时间戳。一般选择时间后也需要展示，再转化为具体时间
设置初始值的时候也要时间戳，并且日需要两位例如['2022','12','07'] 很不方便

### 你期望的 API 是什么样子的？

直接使用时间戳，并且选定后可以直接展示时间

**Comment by chenjiahan** [comment]
数组的形式更加通用一些，比如要选择「年月」、「月日」，转换成时间戳就不太方便了。

对于需要 Date 的场景，建议自行转换一下哈，包一个 computed 转换下就可以。
