### ISSUE TITLE
Empty 空状态

### ISSUE THREAD

**Issue by xiaowenwei0622** [youzan/vant#11378]
### 重现链接

https://github.com/youzan/vant

### Vant 版本

vant 4.0.2

### 描述一下你遇到的问题。

打包部署后，空状态的图片没有显示出来

### 重现步骤

![image](https://user-images.githubusercontent.com/66290437/207213095-420489d8-63b9-4ca3-a17a-2b56115b14ce.png)
![image](https://user-images.githubusercontent.com/66290437/207213127-7d92ea4a-7ee7-42bf-af44-848fc6f280ae.png)
![image](https://user-images.githubusercontent.com/66290437/207217493-1cbcb392-18b2-4171-a53d-f90ca49d9a36.png)

**Comment by chenjiahan** [comment]
麻烦提供一个复现问题的 codesandbox 链接或最小复现仓库地址哈，否则不太好排查这个问题
