### ISSUE TITLE
van-search 定义 ref 绑定v-model clear会出现两个x

### ISSUE THREAD

**Issue by huqinggui-piex** [youzan/vant#11372]
### 重现链接

https://user-images.githubusercontent.com/68435990/206842887-28c1830f-2d56-4ae9-919d-3c5d286126bb.png

### Vant 版本

4.0.2

### 描述一下你遇到的问题。

看图片 ![lQLPJxs6Nxp2ZGzMyc0B-rAGzqlceo_nJgOQYU0oQFoA_506_201](https://user-images.githubusercontent.com/68435990/206842887-28c1830f-2d56-4ae9-919d-3c5d286126bb.png)

### 重现步骤

用uni-app编译到h5

### 设备/浏览器

谷歌浏览器

**Comment by chenjiahan** [comment]
uni-app 问题请参考：
![image](https://user-images.githubusercontent.com/7237365/206854437-5a41a4aa-551c-45dd-bc72-553cef92ce63.png)

如果在非 uni-app 中也有方法复现，请提供对应的 codesandbox 复现链接。
