### ISSUE TITLE
[Feature Request] 建议改善级联回显问题，以及多选

### ISSUE THREAD

**Issue by lei940324** [youzan/vant#11385]
### 这个功能解决了什么问题？

级联选择器回显非常麻烦，而且没有多选功能

### 你期望的 API 是什么样子的？

级联回显类似element-plus的样子

**Comment by lei940324** [comment]
补充一下，主要是针对异步加载的多级回显，因为vant只保存最后一个value值，使用列表value并不会触发默认加载，需要手动点击，并且很希望有多选功能

**Comment by chenjiahan** [comment]
关于回显麻烦的问题，能提供一段示例代码看下吗
