### ISSUE TITLE
upload 组件添加自定义渲染

### ISSUE THREAD

**Issue by PoliWen** [youzan/vant#11389]
![image](https://user-images.githubusercontent.com/28656609/207549094-a75c7f9a-5b2d-4c7a-800e-e4947668d098.png)
上传组件需要添加一些与图片相关的表单信息，怎么实现呢？

### 你期望的 API 是什么样子的？

<van-upload>
  <slot name="customComponent" :fileList="fileList"></slot>
<van-upload>

**Comment by chenjiahan** [comment]
这种布局基于 Uploader 现有的 UI 比较难实现，建议把 `preview-image` 设置为 false，然后自行渲染整个预览区域
