### ISSUE TITLE
DatetimePicker 组件没有秒单位

### ISSUE THREAD

**Issue by MarkXu-Lin** [youzan/vant#11393]
### 这个功能解决了什么问题？

希望可以自由组合年月日时分秒

### 你期望的 API 是什么样子的？

<van-datetime-picker
  v-model="currentDate"
  :custom-ype="type"
  title="选择年月"
  :min-date="minDate"
  :max-date="maxDate"
  :formatter="formatter"
/>
export default {
  data() {
    return {
      minDate: new Date(2020, 0, 1),
      maxDate: new Date(2025, 10, 1),
      currentDate: new Date(),
      type: ["YYYY", "MM", "DD", "hh", "mm", "ss"]
    };
  },
};

**Comment by JakeLaoyu** [comment]
什么场景需要精确到秒

**Comment by chenjiahan** [comment]
Vant 4 已经支持了哈。

https://vant-contrib.gitee.io/vant/#/zh-CN/time-picker

**Comment by wangzhongshun** [comment]
vant4里面只有DatePicker 日期选择 和TimePicker 时间选择，以前vant3里面有DatetimePicker 组件，现在的情况就是年月日和 时分秒只能分开写，不知道为什么 要把DatetimePicker 给砍掉了

**Comment by chenjiahan** [comment]
升级指南不是有写吗
https://vant-ui.github.io/vant/#/zh-CN/migrate-from-v3#datetimepicker-zu-jian-chong-gou

**Comment by tanghaitao** [comment]
> 升级指南不是有写吗
> https://vant-ui.github.io/vant/#/zh-CN/migrate-from-v3#datetimepicker-zu-jian-chong-gou

这控件也太滑稽了
