### ISSUE TITLE
预览图片报错

### ISSUE THREAD

**Issue by An-001** [youzan/vant#11395]
### 重现链接

https://github.com/youzan/vant/pull/11376

### Vant 版本

4.0.3

### 描述一下你遇到的问题。

这个bug 貌似在 4.0.2出现的； bug号 ：#11376
但是到4.0.3 还是有问题
<img width="808" alt="image" src="https://user-images.githubusercontent.com/38935226/208614473-c7eea457-7eb6-4a9e-9f0b-b98b55458ab4.png">

### 重现步骤

  const previewImg = (arr, index = 0) => {
    showImagePreview({
      images: arr,
      closeable: true,
      startPosition: index
    });
  }

### 设备/浏览器

目前是谷歌

**Comment by jackjtr** [comment]
谷歌68可重现
临时解决方案是回退4.0.1

**Comment by wjw-gavin** [comment]
移动端的谷歌吗？我这未复现啊。

**Comment by jackjtr** [comment]
> 移动端的谷歌吗？我这未复现啊。

试试谷歌浏览器，版本68

**Comment by An-001** [comment]
请问 什么时候修复呢？谢谢

**Comment by MrXwq** [comment]
看了下代码，第一次进入页面打开时，imageRef.value?.complete的值是false，但是刷新页面后，再打开时，这个值就为true了，所以刷新后打开时，就先触发了onMounted里的onLoad()
![1671762256019](https://user-images.githubusercontent.com/43991889/209258443-7092b0f4-944c-47ee-84fa-d72184df3916.jpg)
导致loading.value为false了，等图片加载完成时再次触发这个onLoad，就不进入判断触发里面的emit了，是不是得修改下onMounted里complete的判断
![1671762467066](https://user-images.githubusercontent.com/43991889/209258813-ee77ac8b-cf77-4f53-81db-f1d20789755c.jpg)

**Comment by chenjiahan** [comment]
已经在 4.0.4 版本修复了哈，可以升级试一下

**Comment by An-001** [comment]
已测试，ok
