### ISSUE TITLE
vant-list 计算高度的公式有歧义.

### ISSUE THREAD

**Issue by Nick-Tsao** [youzan/vant#1140]
查看了list中定义的 method ,onScroll 方法.  是根据

**Comment by Nick-Tsao** [comment]
reachBottom = scroller.scrollHeight - targetBottom < this.offset;
来判断的.  这个计算公式表示,即使用户滑动没有触底,也会加载执行load.

虽然我现在写的是直接使用load加载第一页. 但是有这个疑问.
正常的逻辑,不是应该用户滑动到底部了再执行么?  希望帮忙解答一下.谢谢

**Comment by chenjiahan** [comment]
把 offset 设置成 0，就是触底加载
默认会有一定的 offset 距离，这样可以适当的预加载
