### ISSUE TITLE
[Feature Request] 车牌输入虚拟键盘

### ISSUE THREAD

**Issue by johnscliang** [youzan/vant#11403]
### 这个功能解决了什么问题？

目前有数字键盘，密码键盘，希望可以有一个车牌输入键盘。
我自己写的太丑，希望vant官方可以出一个van风格的输入车牌号的虚拟键盘。

### 你期望的 API 是什么样子的？

组件API可以与密码键盘，数字键盘一致，我们用来与弹出层组件配合就行。

支持传统车牌，新能源车牌的输入。

**Comment by chenjiahan** [comment]
抱歉，暂时没有这个计划哈，Vant 的 UI 规范里没有车牌输入键盘。
