### ISSUE TITLE
[Bug Report] DropdownMenu Cannot read properties of null (reading 'zIndex')

### ISSUE THREAD

**Issue by lolhezihehe** [youzan/vant#11408]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-6ppfqc?file=/src/App.vue

### Vant 版本

2.12.53

### 描述一下你遇到的问题。

DropdownMenu DropdownItem 手动按需引入报错
```
 TypeError: Cannot read properties of null (reading 'zIndex')
```

### 重现步骤

根据官方文档 手动按需引入组件，打开f12报错，详见codesandbox console报错信息，本地使用2.12.53版本也报同样的错

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/209422653-6b3b2696-8819-4bf1-a8fc-ea40b43978c9.png)

组件注册错了
