### ISSUE TITLE
[Bug Report] image-preview滑动的时候放大，会卡在中间

### ISSUE THREAD

**Issue by MrXwq** [youzan/vant#11411]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/image-preview

### Vant 版本

4.0.4

### 描述一下你遇到的问题。

当我滑动的时候进行放大操作，会出现下面这种情况，能不能当我滑动的时候放大的话，切换到放大的那个swiper，卡在中间感觉挺怪的
https://user-images.githubusercontent.com/43991889/209319133-ef34d2c8-7a52-4aad-b37f-dda2534d3b28.MP4

### 重现步骤

滑动的时候进行放大

### 设备/浏览器

No response

**Comment by chenjiahan** [comment]
下个版本会调整下交互，在滑动过程中不允许进行缩放，这块就不会出现错位的问题了
