### ISSUE TITLE
[Bug Report] count-down组件显示错误

### ISSUE THREAD

**Issue by sakurasuki** [youzan/vant#11413]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-42x6kn?file=/src/App.vue

### Vant 版本

4.0.4

### 描述一下你遇到的问题。

期望显示的时间应为30:59:59，实际显示5:59:59

### 重现步骤

显示问题

**Comment by chenjiahan** [comment]
timeData 里面还有一个 days 字段，表示剩余天数
