### ISSUE TITLE
[Bug Report] 在vue3的组合式API中使用Toast，为什么会说"Toast is not a function"？

### ISSUE THREAD

**Issue by i-jiajia** [youzan/vant#11421]
### Reproduction Link

https://github.com/i-jiajia/ReactNewsSystem.git

### Vant Version

4.0.4

### Describe the Bug

按照官方文档引入后，在使用时出现了问题，已知在选项式API中可以使用'this.$toast'，那么在组合式API中的问题该如何解决？

### Reproduce Steps

<script setup>
import {Toast} from 'vant'

const xxxxxx = ( ) => Toast(' xxxx ')  // Toast is not a function.
</script>

### Device / Browser

chrome

**Comment by MrXwq** [comment]
改名了，按下面这样使用

import { showToast } from 'vant';

showToast('提示内容');
