### ISSUE TITLE
Uploader图片预览报错  Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by chanStudent** [youzan/vant#11428]
### 重现链接

https://codesandbox.io/embed/vant-3-issue-template-forked-13xsvh?fontsize=14&hidenavigation=1&theme=dark

### Vant 版本

4.0.6

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/33553614/209784896-f1bbcca8-6eaf-4467-ad8d-b5e54b423293.png)

### 重现步骤

图片上传，第二次点击预览报错

**Comment by MrXwq** [comment]
你重现链接的版本描述的不对，我用4.0.6没有报错，你这问题可能是这个原因https://github.com/youzan/vant/issues/11395，4.0.4作者貌似修复了，可以试试
![image](https://user-images.githubusercontent.com/43991889/209814874-580137e2-202f-43a5-8a46-ebff7c61fd85.png)

**Comment by chanStudent** [comment]
我项目是4.0.6的
![image](https://user-images.githubusercontent.com/33553614/209890150-7e6fe8d0-efc5-4487-a179-cb77f7e9ac74.png)
请看我上传的视频
https://hlcg.fjoss.xstore.ctyun.cn/Video_00038.wmv

**Comment by wjw-gavin** [comment]
我这试了 微信、Chrome、Safari、小程序web-view都正常....

**Comment by SplendidDream** [comment]
猜测可能是 Image 组件中延迟加载，在  onLazyLoaded 和 onMounted/nextTick函数中 onLoad() 调用没有传 event参数，导致 ImagePreview组件下面代码：
```js
const onLoad = (event) => {
  const {
	naturalWidth,
	naturalHeight
  } = event.target;
  state.imageRatio = naturalHeight / naturalWidth;
};
```
中 的 event是 undefined。

**Comment by chenjiahan** [comment]
@SplendidDream 你说的这个问题已经修复过咯

**Comment by chenjiahan** [comment]
由于未复现，这个 issue 先 close 了。

如果有复现链接的话再 re-open。
