### ISSUE TITLE
[Bug Report] v4.0.5 is missing `lib/index.d.ts` file

### ISSUE THREAD

**Issue by Cphayim** [youzan/vant#11422]
### Reproduction Link

https://github.com/youzan/vant/tree/v4.0.5

### Vant Version

4.0.5

### Describe the Bug

升级到 `4.0.5` 后 VSCode 报找不到 vant 的模块声明文件
根据 `node_modules/vant/package.json` 中的描述，我尝试查找并确认了 `node_modules/vant/lib/index.d.ts` 文件确实不存在
降级回 `4.0.4` 则正常，对比两个版本的结构后判断是否 `4.0.5` 中没有正确构建输出 `lib/` 目录下的文件？

### Reproduce Steps

- tag `v4.0.5` https://github.com/youzan/vant/tree/v4.0.5
- `pnpm i`
- `pnpm build`
- `packages/vant/lib/` 目录没有生成类型文件和组件目录
- `packages/vant/es/` 正常

**Comment by chenjiahan** [comment]
看了下是升级 vite v4 导致的，我修复下

**Comment by chenjiahan** [comment]
已在 4.0.6 版本修复
