### ISSUE TITLE
[Bug Report] vant2.12.20 版本中calendar组件 在ios12上15.4系统版本上拿不到date

### ISSUE THREAD

**Issue by lss-33** [youzan/vant#11433]
### 重现链接

https://codesandbox.io/s/vant-2-issue-template-forked-op7x8m?file=/src/App.vue

### Vant 版本

2.12.20

### 描述一下你遇到的问题。

calendar组件拿不到date

### 重现步骤

ios 12机型，系统版本为15.4版本必现，选择完日期，confirm回调中date为空，其他新版本都正常

### 设备/浏览器

ios 12机型，系统版本为15.4版本必现

**Comment by wjw-gavin** [comment]
![image](https://user-images.githubusercontent.com/19986739/209937753-15a6aa47-be00-4cc9-be60-0aa9789191f5.png)
