### ISSUE TITLE
[Bug Report] 联级选择器 异步加载时 市级进入区进需要点击两下

### ISSUE THREAD

**Issue by lfz9527** [youzan/vant#11432]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/cascader

### Vant 版本

^2.12.26

### 描述一下你遇到的问题。

联级选择器 异步加载时 市级进入区进需要点击两下，希望能想element 一样只需要点一下就可以进入下一级

### 重现步骤

<template>
  <div>
    <van-field
      v-model="fieldValue"
      is-link
      readonly
      label="地区"
      placeholder="请选择所在地区"
      @click="show = true"
    />
    <van-popup v-model="show" round position="bottom">
      <van-cascader
        v-model="cascaderValue"
        title="请选择所在地区"
        :options="options"
        @close="show = false"
        @change="onChange"
        @finish="onFinish"
        :field-names="fieldNames"
      />
    </van-popup>
  </div>
</template>
<script>
import { listAreaTree } from "@/api/enterprise";

export default {
  data() {
    return {
      show: false,
      fieldValue: "",
      cascaderValue: "",
      options: [],
      fieldNames: {
        text: 'areaName',
        value: 'areaCode',
        children: 'children'
      },
    };
  },
  created() {
    this.getArea("");
  },
  methods: {
    async getArea(code) {
      const res = await listAreaTree({
        parentAreaCode: code,
      });
      const { data } = res;
      this.options = data.map((item) => {
        return {
          areaName: item.areaName,
          areaCode: item.areaCode,
          children: item.children || null, // 这个很关键
        };
      });
    },
    onFinish() {},
    onChange({ value, selectedOptions, tabIndex }) {
        listAreaTree({parentAreaCode:value}).then(res => {
        if (res.data.length > 0 ) {
            this.addTree(selectedOptions, res.data, value)
        }
        console.log(this.options);
      })
    },
    addTree(selectedOptions, children, areaCode) {
      selectedOptions.forEach(item => {
        if (item.areaCode === areaCode) {
          item.children = children
        }
      })
    }
  },
};
</script>
<style scoped lang="scss">
</style>

### 设备/浏览器

移动端H5

**Comment by wjw-gavin** [comment]
欢迎PR~
![image](https://user-images.githubusercontent.com/19986739/209937976-96e8d7c0-20c5-403c-8596-cb54f765a2d9.png)

**Comment by donghainan** [comment]
检查下你的树形key，key要是string类型，number类型会有这个问题，我改成string就好了

**Comment by yeszhanov** [comment]
@lfz9527 Hello, did you fix your problem? I have same issue , don't know what to do
