### ISSUE TITLE
Tab中嵌套Tab时，二级的Tab无法进行粘性定位。

### ISSUE THREAD

**Issue by checkwoodson** [youzan/vant#11451]
### 这个功能解决了什么问题？

做个开关，保证两个tab都可以进行粘性定位，还有滑动也可以做个优先级开关， 控制子tab的滑动。

### 你期望的 API 是什么样子的？

有就可以了 。

**Comment by chenjiahan** [comment]
暂时没有计划支持这种场景哈。
