### ISSUE TITLE
官网打不开了，在报错

### ISSUE THREAD

**Issue by guagezuishuai** [youzan/vant#11455]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/

### Vant 版本

3.2.0

### 描述一下你遇到的问题。

官网地址打不开了。

### 重现步骤

打开地址：https://vant-contrib.gitee.io/vant/#/zh-CN/

**Comment by chenjiahan** [comment]
我这边正常访问哈，可能是网络抖动，可以刷新再试下
