### ISSUE TITLE
showtoast与van-popup样式冲突 导致showtoast显示问题

### ISSUE THREAD

**Issue by zmb95** [youzan/vant#11456]
### 重现链接

https://blog.csdn.net/weixin_45474019/article/details/128491561

### Vant 版本

4.0.6

### 描述一下你遇到的问题。

组件内同时使用van-popup组件 再使用showToas(‘提示’) showToast就会有显示问题（空白的）  

### 重现步骤

1、在组件中使用van-popup组件
2、引用 import { showToast } from 'vant'
3、在使用showToast(‘提示’)

### 设备/浏览器

所以设备上

**Comment by wjw-gavin** [comment]
参见：https://github.com/youzan/vant/issues/11049
