### ISSUE TITLE
[Bug Report] BackTop 回到顶部 设置taget 无效果

### ISSUE THREAD

**Issue by xiaoyi510** [youzan/vant#11458]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-sdfu5s?file=/src/App.vue

### Vant 版本

"vant": "^4.0.7"

### 描述一下你遇到的问题。

设置taget 为 #id 
点击无跳转效果

### 重现步骤

设置taget 为 #id 
点击无跳转效果

**Comment by wjw-gavin** [comment]
使用错误哈：
https://codesandbox.io/s/vant-4-issue-template-forked-dk3xjk?file=/src/App.vue

**Comment by xiaoyi510** [comment]
https://codesandbox.io/s/vant-3-issue-template-forked-e6uwlj?file=/src/App.vue
那我为啥这样就不行  将id 设置到 van-cell上 且 回到顶部按钮也不见了

**Comment by wjw-gavin** [comment]
> https://codesandbox.io/s/vant-3-issue-template-forked-e6uwlj?file=/src/App.vue 那我为啥这样就不行 将id 设置到 van-cell上 且 回到顶部按钮也不见了

![image](https://user-images.githubusercontent.com/19986739/210754047-3a34fc10-81a8-4eca-a383-6b0f7d14cf63.png)

你的 target 设置为 '#test1'，你的#test1容器要是个滚动区域啊。
看图片设置的target为 .container， .container 是个滚动区域

**Comment by wjw-gavin** [comment]
> https://codesandbox.io/s/vant-3-issue-template-forked-e6uwlj?file=/src/App.vue 那我为啥这样就不行 将id 设置到 van-cell上 且 回到顶部按钮也不见了

![image](https://user-images.githubusercontent.com/19986739/210754047-3a34fc10-81a8-4eca-a383-6b0f7d14cf63.png)

你的 target 设置为 '#test1'，你的#test1容器要是个滚动区域啊。
看图片设置的target为 .container， .container 是个滚动区域
