### ISSUE TITLE
组件类型未加Partial导出

### ISSUE THREAD

**Issue by agileago** [youzan/vant#11466]
### 重现链接

https://github.com/vueComponent/ant-design-vue/blob/75c65e094fc74b0fa4ee6937730d756ab1d6a926/components/button/buttonTypes.ts#L47

### Vant 版本

4.0.7

### 描述一下你遇到的问题。

想封装vant组件的高阶组件，需要使用到vant导出的组件属性类型， 比如 `ButtonProps` , 但是发现类型里面很多字段都是必填的，然后`ant-design-vue` 没这个问题， 发现他都加了  `Partial`

https://github.com/vueComponent/ant-design-vue/blob/75c65e094fc74b0fa4ee6937730d756ab1d6a926/components/button/buttonTypes.ts#L47

### 重现步骤

https://github.com/youzan/vant/blob/f32e3d99900e9ecaf91b007c553152692f6ff278/packages/vant/src/button/Button.tsx#L55

### 设备/浏览器

all

**Comment by chenjiahan** [comment]
defineComponent 本身就会把 props 变成 partial 的，只有设置了 required: true 的 props 才会变成必填属性。因此组件库没必要在 props 上声明 Partial。

我也跟 antdv 的作者交流过，antdv 里的 Partial 是 Vue 3 早期添加的，那个时候 defineComponent 的类型不完整，所以手动处理了一下，现在是不需要的。

**Comment by agileago** [comment]
defineComponent是给推断出的是对的，但是 `ExtractPropTypes` 是错的

<img width="659" alt="image" src="https://user-images.githubusercontent.com/11799110/211201588-cd6da636-2235-47e2-a896-2904c1cbba27.png">

这些非必填的都给推断成必填的了

**Comment by chenjiahan** [comment]
感觉还是在需要的地方手动加一下 Partial 吧，不是所有场景都希望设置 Partial 的。
