### ISSUE TITLE
vant 4.0.6 +vite 4.0 生产环境 toast 样式错乱

### ISSUE THREAD

**Issue by 736180352** [youzan/vant#11461]
### 重现链接

-

### Vant 版本

4.0.6

### 描述一下你遇到的问题。

toast组件样式错乱，回退vite3.0正常，仅在生产环境出现

### 重现步骤

main.ts引入
`import 'vant/es/toast/style';`
页面调用
`showToast({
      message: '。。。',
      position: 'bottom',
    });`

**Comment by chenjiahan** [comment]
如果是 vite 版本的问题，麻烦到 vite 仓库下反馈喔，Vant 本身是保证了样式顺序正确的。
