### ISSUE TITLE
button 按下无反馈

### ISSUE THREAD

**Issue by w611363303798** [youzan/vant#11460]
### 重现链接

*

### Vant 版本

4.0.6

### 描述一下你遇到的问题。

在Safari、微信、企微环境下几点van-button，点击无反馈
在支付宝环境下点击有反馈

### 重现步骤

点击按钮
颜色加深反馈

### 设备/浏览器

ios16

**Comment by w611363303798** [comment]
好像是ios的问题，body添加touchstart事件解决了

**Comment by gc87** [comment]
重现链接
Vant 版本
4.6.6

描述一下你遇到的问题。
在Safari、微信无反馈，ios版edge正常。

重现步骤
点击按钮
颜色加深反馈

设备/浏览器
ios16.6

另外微信打开文档页面demo无异常，添加touchstart解决
