### ISSUE TITLE
vant添加下拉刷新组件后Tab组件无法吸顶

### ISSUE THREAD

**Issue by MuRongXiaoDouBi** [youzan/vant#1146]
vant添加下拉刷新组件后Tab组件无法吸顶

**Comment by Fyerl** [comment]
tabs与pull-refresh的层级关系是怎样设置的，能否提供下复现步骤

**Comment by MuRongXiaoDouBi** [comment]
`<div class="h-header">
    <van-pull-refresh v-model="isLoading" @refresh="onRefresh">
        <van-tabs swipeable sticky>
          <van-tab title="动态">
              <H-Slider :img="img[0]"></H-Slider>
              <h-main></h-main>
          </van-tab>
          <van-tab title="行程">
            <H-Slider :img="img[1]"></H-Slider>
          </van-tab>
          <van-tab title="活动">
            活动
          </van-tab>
        </van-tabs>
    </van-pull-refresh>
  </div>`

**Comment by Nick-Tsao** [comment]
这样就可以了, pull-refresh 下拉刷新 会将自身dom translateY 一定位移. 以为tab包含在pull-refresh组件里.会同时下移. 切换层级就可以了
<van-tabs swipeable sticky>
      <van-tab title="动态">
          <H-Slider :img="img[0]"></H-Slider>
          <h-main></h-main>
      </van-tab>
      <van-tab title="行程">
        <H-Slider :img="img[1]"></H-Slider>
      </van-tab>
      <van-tab title="活动">
        活动
      </van-tab>
    </van-tabs>
  <van-pull-refresh v-model="isLoading" @refresh="onRefresh">
      
  </van-pull-refresh>

**Comment by Nick-Tsao** [comment]
<van-tabs swipeable sticky>
      <van-tab title="动态">
          <H-Slider :img="img[0]"></H-Slider>
          <h-main></h-main>
      </van-tab>
      <van-tab title="行程">
        <H-Slider :img="img[1]"></H-Slider>
      </van-tab>
      <van-tab title="活动">
        活动
      </van-tab>
    </van-tabs>
  <van-pull-refresh v-model="isLoading" @refresh="onRefresh">
      
  </van-pull-refresh>

**Comment by Nick-Tsao** [comment]
![2018-05-24 4 13 50](https://user-images.githubusercontent.com/31433951/40472948-789b9df6-5f6d-11e8-9a8b-102665f13d19.png)

**Comment by chenjiahan** [comment]
transform 与 fixed 不兼容，参见这篇文章 http://www.zhangxinxu.com/wordpress/2015/05/css3-transform-affect/
楼上是正解

**Comment by jackyon** [comment]
但是这样又导致到swiperable属性不能用了。

**Comment by dobetterdomore** [comment]
这样操作并没有解决吸顶的同时兼容下拉刷新的需求，如果不再同一层的时候，下拉刷新是整个页面往下，但是唯独tabs不懂，很奇怪！！

**Comment by guigui730** [comment]
<van-pull-refresh v-model="isLoading" @refresh="onRefresh">
    
      <van-tab title="动态">
         <van-tabs swipeable sticky>
            <H-Slider :img="img[0]"></H-Slider>
             <h-main></h-main>
          </van-pull-refresh>
      </van-tab>
      <van-tab title="行程">
        <H-Slider :img="img[1]"></H-Slider>
      </van-tab>
      <van-tab title="活动">
        活动
      </van-tab>
    </van-tabs>


这样就可以了
