### ISSUE TITLE
[Bug Report]  无法找到 <van-skeleton-paragraph /> 组件

### ISSUE THREAD

**Issue by Aaron3S** [youzan/vant#11469]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-9t0j4i

### Vant 版本

4.0.7

### 描述一下你遇到的问题。

无法导入<van-skeleton-paragraph /> 组件

### 重现步骤

1.安装 vant4
2.使用 <van-skeleton-paragraph />

**Comment by yimao009** [comment]
是啊， 为啥找不到啊。 头大

**Comment by GRAMMAC1** [comment]
可以先通过手动注册解决，下一个版本会修复

```js
import Vant, { SkeletonParagraph, SkeletonImage } from "vant";

app.use(Vant);
app.use(SkeletonParagraph);
app.use(SkeletonImage);
```

**Comment by Aaron3S** [comment]
手动仍然无法工作。

**Comment by yimao009** [comment]
> 

样式是不是也得手动倒入啊，unplugin-vue-components 插件自动解析不了啊

**Comment by yimao009** [comment]
> 可以先通过手动注册解决，下一个版本会修复
> 
> ```js
> import Vant, { SkeletonParagraph, SkeletonImage } from "vant";
> 
> app.use(Vant);
> app.use(SkeletonParagraph);
> app.use(SkeletonImage);
> ```

样式是不是也得手动倒入啊，unplugin-vue-components 插件自动解析不了啊

**Comment by Aaron3S** [comment]
![image](https://user-images.githubusercontent.com/34506289/211454943-9f8e8062-8007-4b06-bdf4-249e3e7afef3.png)

**Comment by wjw-gavin** [comment]
![image](https://user-images.githubusercontent.com/19986739/211472677-5979619b-7521-4909-bb2c-7632dcc4e37c.png)

**Comment by Aaron3S** [comment]
感谢支持。

**Comment by Aaron3S** [comment]
> 可以先这样手动导入注册 ![image](https://user-images.githubusercontent.com/19986739/211472677-5979619b-7521-4909-bb2c-7632dcc4e37c.png)

可以分享sandbox 链接给我吗。 我这里仍然提示 SkeletonTitle 是 undefined

**Comment by wjw-gavin** [comment]
> > 可以先这样手动导入注册 ![image](https://user-images.githubusercontent.com/19986739/211472677-5979619b-7521-4909-bb2c-7632dcc4e37c.png)
> 
> 可以分享sandbox 链接给我吗。 我这里仍然提示 SkeletonTitle 是 undefined

https://codesandbox.io/s/vant-3-issue-template-forked-49xpiw?file=/src/App.vue

![image](https://user-images.githubusercontent.com/19986739/211481745-86118ef7-da12-4b4b-b3ca-5d3e6871414e.png)
这里版本要改下
