### ISSUE TITLE
[Feature Request] pickergroup 能够支持设置当前激活的tab页

### ISSUE THREAD

**Issue by thehappymouse** [youzan/vant#11471]
### 这个功能解决了什么问题？

拿日期-时间选择器来讲， 选择日期后，点【确认】进入时间选择。 因为实际过程中用户不选会手动去点【选择时间】

### 你期望的 API 是什么样子的？

<van-picker-group
        title="预约取件时间"
        :tabs="['选择日期', '选择时间']"
        :tab-active="pickerDTIndex"
        @confirm="onDateTimeConfirm"
        ref="pickerDT"
        @cancel="showTakeTimePopup = false"
>

**Comment by wjw-gavin** [comment]
- 选择日期后，点【确认】，这个时候已经是选择后的日期+时间了吧，此时该关闭picker了；
- 我理解正常应该是：选择日期-切换tab-选择时间-点击【确定】-  关闭picker

**Comment by thehappymouse** [comment]
选择日期后，你两个路径：
1，去切换Tab，选择时间
2，点击【确认】，认为已选择好日期和时间。 
两个路径的行为是不一样的。

路径2，此时用户并没有明确的选择时间，确认的时间，也只是默认的时间罢了。 

所以才需要可以开发可以控制路径，是否强制确认时间的选项。

**Comment by wjw-gavin** [comment]
我是觉得有点奇怪，你描述的这样，必须是tab在时间选择器时，才能点击【确定】取到想要的结果吧？
如果我在确认时间后想修改日期怎么办呢？修改完日期后，还需要切换到时间项再点【确定】？

**Comment by thehappymouse** [comment]
是的，我想要的就是用户，必须做完 1-2，才能点【确定】。

如果你先确认日期，然后在选择时间后，还想再修改日期，   也就是 Tab顺序是  1-2-1 ，可以看到，你有了明确的修改预期，也就会去切换Tab，直接录入自己想要的结果。 而不会通过【确定】去尝试切换。

**Comment by wjw-gavin** [comment]
嗯嗯，能明白你的意思，我是自己感觉有点奇怪。😂

等作者评估下吧

**Comment by chenjiahan** [comment]
目前交互上确实存在这个问题，@thehappymouse 对于如何约束用户的交互路径，你有什么建议吗，我不是很理解怎么通过 `tab-active` 来限制这个操作路径。

**Comment by thehappymouse** [comment]
好的，非常感谢。  @wjw-gavin 

@chenjiahan 那个字段是我假想的，官方还没有提供功能。另外，我这边将尝试：一次性选择日期和时间，不想要Tab切换。
如果效果可以，我也将尝试贡献代码。

**Comment by thehappymouse** [comment]
@chenjiahan  把两个组件直接下下拼接 用户不迷路了。
currentDateTimeString： 拼接data和time

    <van-popup close-on-popstate safe-area-inset-bottom v-model:show="showTakeTimePopup" position="bottom">
      <div>
        <van-nav-bar
          :title="currentDateTimeString"
          left-text="取消"
          right-text="确认"
          @click-left="showTakeTimePopup = false"
          @click-right="onDateTimeConfirm"
        />
        <van-divider>选择日期</van-divider>
        <van-date-picker
          :swipe-duration="0.5"
          :formatter="pickerFormatter"
          :min-date="minDate"
          :max-date="maxDate"
          v-model="currentDate"
          visible-option-num="3"
          :show-toolbar="false"
        />
        <br />
        <van-divider>选择时间</van-divider>
        <van-time-picker
          :swipe-duration="0.5"
          :formatter="pickerFormatter"
          v-model="currentTime"
          :filter="filterTakeTime"
          visible-option-num="3"
          :show-toolbar="false"
        />
      </div>
    </van-popup>

**Comment by chenjiahan** [comment]
直接拼接两个 Picker 会有点奇怪嘞，我们倾向于默认使用 Tab 交互，对多个 Picker 的场景更加便捷。

**Comment by chenjiahan** [comment]
下一个版本会支持在 PickerGroup 中启用「下一步」按钮：

<img width="368" alt="截屏2023-01-15 上午10 22 26" src="https://user-images.githubusercontent.com/7237365/212520393-20c93fee-d273-48e0-aa1c-24a42fa282d4.png">
