### ISSUE TITLE
在安卓某些机型中Picker 选择器的样式兼容问题

### ISSUE THREAD

**Issue by hsuehy** [youzan/vant#11476]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-jnkd92?file=/src/App.vue

### Vant 版本

4.0.7

### 描述一下你遇到的问题。

Picker 选择器
初始化之后，高度为自动移100px 。在第一项类似下拉加载的动作触发滚动后，该列所有的选项就消失了，然后在触发滑动再次出现

### 重现步骤

1.三级联动默认请选择
2.设置高度为自动移100px
3.下拉放开
4.就会出现
5.必显

电脑模拟没问题，手机端有问题

### 设备/浏览器

华为p30的机型下，浏览器版本为80

**Comment by chenjiahan** [comment]
手动没有对应的机型，要不给个复现视频看看
