### ISSUE TITLE
[Feature Request] 能否提供文档所示的案例源码

### ISSUE THREAD

**Issue by 2b0x** [youzan/vant#11474]
### 这个功能解决了什么问题？

在翻阅文档的时候，有些参数想进行调试，发现文档没有提供线上调试代码。去仓库(https://github.com/youzan/vant)翻了一圈，也没找到相关的。然后clone了vant案例(https://github.com/vant-ui/vant-demo)的仓库，也没看到有相关的案例

### 你期望的 API 是什么样子的？

文档案例的源码或者线上调试代码片段

**Comment by wjw-gavin** [comment]
每个组件的示例源码，都在对应组件的Demo文件夹下哈
[比如 Button](https://github.com/youzan/vant/tree/main/packages/vant/src/button/demo)
