### ISSUE TITLE
[Bug Report] 使用vant-cli 初始化的组件库项目下的 .gitignore 内容不准确

### ISSUE THREAD

**Issue by jc-yang** [youzan/vant#11477]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-7tbpxz?file=/.gitignore

### Vant Cli 版本

5.1.0

### 描述一下你遇到的问题。

vant-cli-app 搭建组件库后，站点打包生成的目录为 site-dist，但在模板默认生成的 .gitignore 中，未将目录 site-dist 忽略，可能需要修改模板中的 .gitignore 的内容

### 重现步骤

1. 构建组件库项目
```
yarn create vant-cli-app
```
2. 构建组件库文档站点
```
yarn build:site
```
构建打包后的内容目录为 site-dist
3. .gitignore 中未添加 site-dist 目录，添加的却是 site，

**Comment by chenjiahan** [comment]
已更新模板👌🏻
