### ISSUE TITLE
[Feature Request] Calendar 日历组件 加一个显隐月份标题的props或slot

### ISSUE THREAD

**Issue by FAOfao931013** [youzan/vant#11473]
### 这个功能解决了什么问题？

1、可以自己控制月份标题的显隐
2、可以自定义月份标题的格式，方便实现需求

### 你期望的 API 是什么样子的？

props 就 show-month-title
slot 就 month-title 或 monthtitle 参数和subtitle保持一致

**Comment by chenjiahan** [comment]
目前都是支持的

![image](https://user-images.githubusercontent.com/7237365/212461348-6840c088-d3a7-4712-83fb-fcb95819d531.png)


![image](https://user-images.githubusercontent.com/7237365/212461344-1b27fb10-a672-4d69-a46f-c3dd24955599.png)

**Comment by FAOfao931013** [comment]
@chenjiahan 这个是控制副标题的并非 每月的标题
![image](https://user-images.githubusercontent.com/16414167/212582065-38f9cb62-4909-4f80-8228-fc72b12f6b46.png)
你说的绿框的控制 我说的是红框的控制

**Comment by chenjiahan** [comment]
红框标题如果被隐藏了，岂不是很奇怪吗，用户在滚动的时候都不知道滚动到哪个月了

**Comment by FAOfao931013** [comment]
@chenjiahan 最好是给个能格式化的slot或者参数啥的 因为 我要显示成 YYYY-MM 的样子 而不是 YYYY年MM月

**Comment by chenjiahan** [comment]
slot 可以的，后续加一个
