### ISSUE TITLE
VueCompilerError: v-model cannot be used on a prop, because local prop bindings are not writable.

### ISSUE THREAD

**Issue by long20150122** [youzan/vant#11481]
vant 3.6.11 

<van-number-keyboard
  v-model="value"
  :show="show"
  :maxlength="6"
  @blur="show = false"
/>

VueCompilerError: v-model cannot be used on a prop, because local prop bindings are not writable.
Use a v-bind binding combined with a v-on listener that emits update:x event instead.

**Comment by chenjiahan** [comment]
Please follow the issue template and provide a reproduce link.
