### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by SUXHK** [youzan/vant#11480]
### 重现链接

https://user-images.githubusercontent.com/33438399/212034184-adf28982-71fb-47ba-ae2e-618c9c501aee.png

### Vant 版本

4.0.7

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/33438399/212034184-adf28982-71fb-47ba-ae2e-618c9c501aee.png)

### 重现步骤

1.使用unplugin-vue-components插件无法自动导入van-skeleton-paragraph、van-skeleton-image等
2.提示这个报错，看了下目录，没有skeleton-paragraph、skeleton-image...，只有skeleton，其中在skeleton里面有

**Comment by wjw-gavin** [comment]
参考：https://github.com/youzan/vant/issues/11469

**Comment by chenjiahan** [comment]
重复 issue 先 close 咯
