### ISSUE TITLE
Stepper 样式失效

### ISSUE THREAD

**Issue by lixiaofa** [youzan/vant#11483]
### 重现链接

https://github.com/lixiaofa/vant-sku-next/blob/master/src/components/test-stepper/index.tsx

### Vant 版本

"vant": "^4.0.2",

### 描述一下你遇到的问题。

import Stepper from 'vant/lib/stepper';
这样引入 , 样式会失效在tsx中

### 重现步骤

pnpm dev

**Comment by chenjiahan** [comment]
代码里没引用样式，建议再看一遍快速上手文档

https://vant-contrib.gitee.io/vant/#/zh-CN/quickstart

**Comment by lixiaofa** [comment]
> 代码里没引用样式，建议再看一遍快速上手文档
> 
> https://vant-contrib.gitee.io/vant/#/zh-CN/quickstart

我是按需 加载 ， 且其他的组件没有引入样式  ，也是正常的


![image](https://user-images.githubusercontent.com/23230215/212464181-4cb0625d-d9b1-437b-b021-a17e522cc4d2.png)
