### ISSUE TITLE
[Bug Report] Cascader在二级以上，跨级切换tab节点时，再次选择已选择的选项，tab节点未激活能取消-wrapper--inactive样式

### ISSUE THREAD

**Issue by johnlucita** [youzan/vant#11498]
### Reproduction Link

none

### Vant Version

4.0.8

### Describe the Bug

![图片](https://user-images.githubusercontent.com/10844665/213062981-34ff04fd-1f25-4700-895a-af239fdeae14.png)
![图片](https://user-images.githubusercontent.com/10844665/213063017-cc27daa7-df4b-46f6-a73f-07518eeaa674.png)
![图片](https://user-images.githubusercontent.com/10844665/213063347-3ff8a412-0dfa-439c-9245-9f91db0a742a.png)

### Reproduce Steps

1、异步加载子节点
2、二级以上
3、跨级点击tab节点（例如，选项已到第三级，通过点击返回第一级）
4、再次选择该级下已选择过的节点

**Comment by chenjiahan** [comment]
没复现你描述的问题，可以提供复现链接看下

**Comment by johnlucita** [comment]
![图片](https://user-images.githubusercontent.com/10844665/215662044-4a8c5e79-6613-4141-8ce1-d0c438fb8bcb.png)
![图片](https://user-images.githubusercontent.com/10844665/215662105-efd48595-a876-462c-92dd-728f57e1149d.png)
![图片](https://user-images.githubusercontent.com/10844665/215662143-e18d7a4d-6367-415f-b8fc-6a7a9ce9c58b.png)
![图片](https://user-images.githubusercontent.com/10844665/215662166-ecd9c16d-6df0-453d-8184-469dfe308319.png)
![图片](https://user-images.githubusercontent.com/10844665/215662196-7bacf696-e62d-421a-b06c-30f71bc1063c.png)
![图片](https://user-images.githubusercontent.com/10844665/215662229-7fb79683-def8-462c-b544-ed46ffb3921a.png)
