### ISSUE TITLE
[Feature Request] 希望Vant 3/4 新增sku组件

### ISSUE THREAD

**Issue by zhoukaiyue** [youzan/vant#11492]
### 这个功能解决了什么问题？

业务中经常会遇到商品规格选择的场景

### 你期望的 API 是什么样子的？

就像v2一样

**Comment by chenjiahan** [comment]
重复 issue，https://github.com/youzan/vant/issues/11491

**Comment by lixiaofa** [comment]
> ### 这个功能解决了什么问题？
> 业务中经常会遇到商品规格选择的场景
> 
> ### 你期望的 API 是什么样子的？
> 就像v2一样

@zhoukaiyue 我迁移vant2.x 的sku  
https://www.npmjs.com/package/vant-sku?activeTab=readme
