### ISSUE TITLE
希望在v3/v4上面添加sku组件

### ISSUE THREAD

**Issue by zhoukaiyue** [youzan/vant#11491]
### 这个功能解决了什么问题？

业务中经常会遇到商品规格选择的需求。

### 你期望的 API 是什么样子的？

就像v2一样

**Comment by wjw-gavin** [comment]
参见： https://github.com/youzan/vant/issues/10336

**Comment by yuninf** [comment]
vant背后是有赞,有赞本身就是搞商城起来的.

估计是上面要求不能有业务冲突，啊哈哈
