### ISSUE TITLE
Tab 和 List 组件一起使用时，List 组件 onscroll 事件同时触发

### ISSUE THREAD

**Issue by ffx0s** [youzan/vant#1151]
每个 tab 项对应一个 list 组件，当切换的时候，会触发之前所有 tab 项下 list onscroll 事件。看了下 list 组件只有在未激活或销毁的时候才会移除滚动事件，而 tab 切换的时候只改变了 display 属性，不会触发移除事件。目前解决方案是使用 overflow: auto，将事件绑定在元素上或者切换的时候手动移除上一个 list 事件。但是前者性能不太好，后者太繁琐了。想问一下有没更好的解决方案？

**Comment by Nick-Tsao** [comment]
1. 可以给List绑定ref .  手动解绑scroll事件this.$refs.*.handler(false);
2.每个tab 都对应同一个List.  每个tab对应保存一个data,根据tab的切换.渲染对应的data
