### ISSUE TITLE
[Bug Report] DatePicker 会选择出2月31号

### ISSUE THREAD

**Issue by fshihu** [youzan/vant#11528]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-fp6sog?file=/src/App.vue

### Vant 版本

4.0.9

### 描述一下你遇到的问题。

先选择1月31号，再切换月份到2月，change事件返回的值就不对

### 重现步骤

先选择1月31号，再切换月份到2月，change事件返回的值就不对

**Comment by owen800q** [comment]
Safari 15.5无法复现

**Comment by fshihu** [comment]
![dec3c1d71d0d5096aa6ad7bf70538b1d](https://user-images.githubusercontent.com/970547/215943502-c28b2580-e6ef-4035-a85d-959ea9e3ce93.jpg)
我用华为手机浏览器还是有问题，pc chrome浏览器也有问题

**Comment by wChenonly** [comment]
> ![dec3c1d71d0d5096aa6ad7bf70538b1d](https://user-images.githubusercontent.com/970547/215943502-c28b2580-e6ef-4035-a85d-959ea9e3ce93.jpg) 我用华为手机浏览器还是有问题，pc chrome浏览器也有问题

我用chrome实验，确实是有问题的
