### ISSUE TITLE
Swipe & DropDownMenu don't work well together.

### ISSUE THREAD

**Issue by tolbxela** [youzan/vant#11524]
### Reproduction Link

https://stackoverflow.com/questions/70981010/vant-ui-mobile-swipe-dropdown-not-working

### Vant Version

4

### Describe the Bug

Swiping destroys DropDownMenu

### Reproduce Steps

After the Swipe event the DropDownMenu items are not present.

![image](https://user-images.githubusercontent.com/4910589/214841603-7473bf3a-e56a-45ea-95a1-b16e33cd8f50.png)

**Comment by aooiuu** [comment]
https://codepen.io/aooiuu/pen/wvxORZO

add ` get-container="body"`

` <van-dropdown-item v-model="value1" :options="option1" get-container="body"></van-dropdown-item>`

**Comment by tolbxela** [comment]
Unfortunately, it still does not work with v4

`get-container="body"` doesn't help to fix the problem

https://codepen.io/tolbxela/pen/ExpJzPN

**Comment by aooiuu** [comment]
> Unfortunately, it still does not work with v4
> 
> `get-container="body"` doesn't help to fix the problem
> 
> [codepen.io/tolbxela/pen/ExpJzPN](https://codepen.io/tolbxela/pen/ExpJzPN)

https://vant-contrib.gitee.io/vant/#/zh-CN/dropdown-menu

v2: `get-container="body"`
v4: `teleport="body"`

**Comment by tolbxela** [comment]
Thanks again!
