### ISSUE TITLE
Cascader跨级切换tab节点时，再次选择已选择的选项，tab节点数据被隐藏

### ISSUE THREAD

**Issue by johnlucita** [youzan/vant#11527]
> **重现问题步骤**

![图片](https://user-images.githubusercontent.com/10844665/215664616-6608779d-5391-4ba4-9654-b822179e4718.png)
![图片](https://user-images.githubusercontent.com/10844665/215662105-efd48595-a876-462c-92dd-728f57e1149d.png)
![图片](https://user-images.githubusercontent.com/10844665/215662143-e18d7a4d-6367-415f-b8fc-6a7a9ce9c58b.png)
![图片](https://user-images.githubusercontent.com/10844665/215662166-ecd9c16d-6df0-453d-8184-469dfe308319.png)
![图片](https://user-images.githubusercontent.com/10844665/215662196-7bacf696-e62d-421a-b06c-30f71bc1063c.png)

> **产生问题点**

![图片](https://user-images.githubusercontent.com/10844665/215662229-7fb79683-def8-462c-b544-ed46ffb3921a.png)
![图片](https://user-images.githubusercontent.com/10844665/215666249-2c74256b-c2e7-4e32-bc59-760f5bf4e0e2.png)

_Originally posted by @johnlucita in https://github.com/youzan/vant/issues/11498#issuecomment-1409733494_

**Comment by johnlucita** [comment]
重现的步骤，我已经写的很清楚了，别跟我说你重现不了

**Comment by chenjiahan** [comment]
issue 模板已经写的很清楚了，别跟我说你看不懂。

**Comment by jhzqq2003** [comment]
我也可以复现
