### ISSUE TITLE
[Bug Report] 支付宝安卓版本打开空白

### ISSUE THREAD

**Issue by Harry-Cat** [youzan/vant#11530]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/

### Vant 版本

4.0.9

### 支付宝安卓版打开空白，无法加载，其它微信、浏览器能正常访问
相关版本：
支付宝安卓版本：10.3.36 
项目依赖：
 "dependencies": {
    "axios": "^1.2.6",
    "vant": "^4.0.9",
    "vue": "^3.2.45",
    "vue-router": "^4.1.6"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "less": "^4.1.3",
    "unplugin-vue-components": "^0.22.11",
    "vite": "^4.0.0"
  }

### 重现步骤

使用支付宝打开链接空白，无法加载
---
经测试，v3版本可以打开
https://vant-ui.github.io/vant/v3/#/zh-CN/

### 设备/浏览器

安卓系统手机

**Comment by chenjiahan** [comment]
这个应该是 vite 4 的兼容性问题，Vant v3 版本用了 vite v3 是正常的

**Comment by Harry-Cat** [comment]
验证了，还真是vite问题

**Comment by chenjiahan** [comment]
嗯嗯，可以到 vite 仓库反馈下
