### ISSUE TITLE
[Feature Request] 新增 `Nuxt3` modules

### ISSUE THREAD

**Issue by evanlong0926** [youzan/vant#11539]
### 这个功能解决了什么问题？

1. 更好的兼容 `Nuxt3` ❤️
2. 更好的解锁流量密码 🙌

### 你期望的 API 是什么样子的？

我希望 `Vant4` 能和官方提供的规范案例新增一个 `@nuxtjs/vant` 的 [module](https://nuxt.com/modules)

**Comment by chenjiahan** [comment]
流量密码这个理由不错😄 后续我们调研下

**Comment by tolking** [comment]
前段时间我为 Element Plus 写过模块，如果需要我可以完成这个。

[项目链接](https://github.com/element-plus/element-plus-nuxt)

**Comment by chenjiahan** [comment]
@tolking 太棒咯，期待你的贡献~ 代码可以直接放到 Vant 仓库的 pacakges 目录下面

**Comment by tolking** [comment]
> 代码可以直接放到 Vant 仓库的 pacakges 目录下面

了解
