### ISSUE TITLE
日期时间范围选择时，需要切换4个tab，操作不够友好，能否将日期、时间放入同一个tab中

### ISSUE THREAD

**Issue by yexiaodong** [youzan/vant#11543]
### 这个功能解决了什么问题？

![image](https://user-images.githubusercontent.com/13914749/216864994-b8353599-a63a-4527-9650-24940e528e95.png)
tab太多，用户体验不够友好

### 你期望的 API 是什么样子的？

类似DatetimePicker可以同时选择日期和时间

**Comment by chenjiahan** [comment]
后续不会再增加类似 DatetimePicker 的交互了呢，你可以把上图中的组件拆成两个 PickerGroup，一个用于选择开始日期时间，一个用于选择结束日期时间
