### ISSUE TITLE
rate组件不能通过value绑定吗？只能通过v-model？

### ISSUE THREAD

**Issue by lvan-zhang** [youzan/vant#11546]
### 重现链接

暂无

### Vant 版本

4.0.6

### 描述一下你遇到的问题。

这样写没问题：`<van-rate v-model="score" />`
这样没效果：`<van-rate :value="score" />`
在vue中如果要把这个写成一个组件，父组件传递score参数进来，怎么写啊？

### 重现步骤

同上

**Comment by jackjtr** [comment]
vant3以后v-model的默认属性名称是modelValue
你需要写成
`<van-rate :model-value="score" />`
