### ISSUE TITLE
Radio组件的RadioGroup的change事件在vue3中没有起作用

### ISSUE THREAD

**Issue by yhhyu2015** [youzan/vant#11548]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/radio

### Vant 版本

3.4.7

### 描述一下你遇到的问题。

Radio组件的RadioGroup的change事件在vue3中setup中没有起作用

### 重现步骤

Radio组件的RadioGroup的change事件在vue3中setup中没有起作用

### 设备/浏览器

谷歌

**Comment by wjw-gavin** [comment]
可以的哈，看看是否写法有误。

https://codesandbox.io/s/vant-4-issue-template-forked-dk3xjk?file=/src/App.vue
