### ISSUE TITLE
vue被默认导入 import xx, {h, defineComponent,...} from vue

### ISSUE THREAD

**Issue by lixiaofa** [youzan/vant#11551]
### 重现链接

https://github.com/lixiaofa/vant-sku-next

### Vant 版本

"vant": "^4.0.2",

### 描述一下你遇到的问题。

库模式下：打包之后报错

![image](https://user-images.githubusercontent.com/23230215/217187401-bdd77875-3d66-44aa-8542-a8e55e7d5397.png)
![image](https://user-images.githubusercontent.com/23230215/217187441-ffccd660-ef3d-4631-84be-ac29e6fa249d.png)
![image](https://user-images.githubusercontent.com/23230215/217187516-e0825fc3-d4ec-4e7f-8be2-c6f29aaa17ce.png)

### 重现步骤

pnpm build
pnpm dev

**Comment by wChenonly** [comment]
我这用你的代码没有复现，页面正常

**Comment by lixiaofa** [comment]
> 我这用你的代码没有复现，页面正常

![image](https://user-images.githubusercontent.com/23230215/217441573-88464ba4-ea5d-4146-9528-c1b7d5b2dfd9.png)

**Comment by wChenonly** [comment]
把vite打包的默认压缩关掉，报错的那一行 的h 也就是  require$$0  在vant-sku.es.js 里面大概搜下require$$0。可以看到这个是类似于全局的vue实例一样，上面挂的都是vue所有属性方法，依靠这个默认导出提供一些东西。
但是在vue3 已经没有默认导出了，也就是肯定报错 没有default
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/37658262/217510889-29eeff16-1ed2-47bc-908f-77a4cbf8af9f.png">


看了下components里面的tsx代码，感觉是写法不对，导致打包的时候，按照有默认导出的打包了。建议 把tsx的代码 都换成vue3的函数。无论Options还是Composition风格



另我把require$$0 挂在vue3 getCurrentInstance 函数上，然后根据报错提示，删除不在 getCurrentInstance()的属性，如ref，defineComponent等。
页面就可以显示出来了。也可以证明上面说的
<img width="746" alt="image" src="https://user-images.githubusercontent.com/37658262/217511452-4519c79d-6960-45b2-8442-48c993316991.png">

**Comment by lixiaofa** [comment]
> 把vite打包的默认压缩关掉，报错的那一行 的h 也就是 require$$0 在vant-sku.es.js 里面大概搜下require$$0。可以看到这个是类似于全局的vue实例一样，上面挂的都是vue所有属性方法，依靠这个默认导出提供一些东西。 但是在vue3 已经没有默认导出了，也就是肯定报错 没有default <img alt="image" width="1534" src="https://user-images.githubusercontent.com/37658262/217510889-29eeff16-1ed2-47bc-908f-77a4cbf8af9f.png">
> 
> 看了下components里面的tsx代码，感觉是写法不对，导致打包的时候，按照有默认导出的打包了。建议 把tsx的代码 都换成vue3的函数。无论Options还是Composition风格，这样就肯定OK了
> 
> 另我把require$$0 挂在vue3 getCurrentInstance 函数上，然后根据报错提示，删除不在 getCurrentInstance()的属性，如ref，defineComponent等。 页面就可以显示出来了。也可以证明上面说的 <img alt="image" width="746" src="https://user-images.githubusercontent.com/37658262/217511452-4519c79d-6960-45b2-8442-48c993316991.png">

我 解决了 ， 原因是vant 包引入的错误。
 你说的换， 换不了， 因为我是 迁移vant2.x 的sku 。
感谢你的帮助， 谢谢

**Comment by lixiaofa** [comment]
@wChenonly 大佬， 
能帮我看看这个问题吗
https://github.com/vitejs/vite/discussions/11978

**Comment by lixiaofa** [comment]
> 我这用你的代码没有复现，页面正常

@wChenonly 大佬，
能帮我看看这个问题吗
https://github.com/vitejs/vite/discussions/11978

**Comment by wChenonly** [comment]
> > 我用你的代码没有恢复，页面正常
> 
> @wChenonly大佬， 能帮我看看这个问题吗 [vitejs/vite#11978](https://github.com/vitejs/vite/discussions/11978)

打包的时候，排除less文件，然后文件复制出来，单独用less.render去处理，在放回。 可以参考这个。https://juejin.cn/post/7117886038126624805#heading-25

**Comment by lixiaofa** [comment]
> > > 我用你的代码没有恢复，页面正常
> > 
> > 
> > @wChenonly大佬， 能帮我看看这个问题吗 [vitejs/vite#11978](https://github.com/vitejs/vite/discussions/11978)
> 
> 打包的时候，排除less文件，然后文件复制出来，单独用less.render去处理，在放回。 可以参考这个。https://juejin.cn/post/7117886038126624805#heading-25

大佬  ， 你好像没理解我意思。
我想把index.less 打包成index.css 

但是你如果sku里面不引入index.less
vite 是不会给你打包的

我想实现的结果是 
sku里面不引入index.less ，
index.less也 打包成index.css  
我vite 该怎么配置
@wChenonly

**Comment by lixiaofa** [comment]
> > > 我用你的代码没有恢复，页面正常
> > 
> > 
> > @wChenonly大佬， 能帮我看看这个问题吗 [vitejs/vite#11978](https://github.com/vitejs/vite/discussions/11978)
> 
> 打包的时候，排除less文件，然后文件复制出来，单独用less.render去处理，在放回。 可以参考这个。https://juejin.cn/post/7117886038126624805#heading-25

@wChenonly  谢谢大佬解惑

**Comment by wChenonly** [comment]
还可以这么整。建一个vite.config.css.ts 文件，运行vite build --config vite.config.css.ts 只打包css 。

 
<img width="444" alt="image" src="https://user-images.githubusercontent.com/37658262/217689377-bb5fa1c9-362c-44a4-a729-88254f0931a0.png">


```javascript
/* eslint-disable space-before-function-paren */
/* eslint-disable @typescript-eslint/explicit-function-return-type */
import { resolve } from 'path'
import fg from 'fast-glob'
import type { UserConfigExport } from 'vite'
import fse from 'fs-extra'

const { readFileSync, writeFileSync, removeSync } = fse

// 找路径
const input: string = resolve(__dirname, 'packages/fighting-design')

// 匹配下面所有的scss文件
// src/a/a.scss  src/a2/a2/a2.scss  src/a3/a3/a3/a3.scss
const inputArr = fg.sync(`${input}/**/*.scss`)

export default (): UserConfigExport => {
  return {
    //  打包。默认回会在根项目的dist文件
    build: {
      rollupOptions: {
        input: inputArr,
        output: {
          entryFileNames: '[name].js',
          chunkFileNames: '[name].js',
          assetFileNames: '[name].[ext]'
        }
      }
    }
  }
}

// 获取 ./src/a/a.scss 里面的a.scss
const getLastItem = (thePath: string) => thePath.substring(thePath.lastIndexOf('/') + 1)

// 获取 a.scss 里面的a
const getFileName = (data: string) => data.substring(0, data.indexOf('.'))

const EXT_REGEXP = /\.\w+$/

const replaceExt = (path: string, ext: string) => path.replace(EXT_REGEXP, ext)

// 思路，将dist里面的在替换回前面路径找到的inputArr
// 先读dist，然后读inputArr。2个文件名一样，就把dist里面的内容写回去inputArr,并且要将scss后缀替换成css
// 在删除原先的scss文件
// 延时（不是好办法）是为了等前面打包走完，再执行这个

setTimeout(async () => {
  const inputD: string = resolve(__dirname, 'dist')
  const css = fg.sync(`${inputD}/*.css`)
  for await (const key of inputArr) {
    const fileName = getFileName(getLastItem(key))
    for await (const source of css) {
      const cssFileName = getFileName(getLastItem(source))
      if (fileName === cssFileName) {
        const data = readFileSync(source, 'utf-8')
        writeFileSync(replaceExt(key, '.css'), data)
        removeSync(key)
      }
    }
  }
}, 2000)

```

**Comment by lixiaofa** [comment]
> 还可以这么整。建一个vite.config.css.ts 文件，运行vite build --config vite.config.css.ts 只打包css 。
> 
> <img alt="image" width="444" src="https://user-images.githubusercontent.com/37658262/217689377-bb5fa1c9-362c-44a4-a729-88254f0931a0.png">
> 
> ```js
> /* eslint-disable space-before-function-paren */
> /* eslint-disable @typescript-eslint/explicit-function-return-type */
> import { resolve } from 'path'
> import fg from 'fast-glob'
> import type { UserConfigExport } from 'vite'
> import fse from 'fs-extra'
> 
> const { readFileSync, writeFileSync, removeSync } = fse
> 
> // 找路径
> const input: string = resolve(__dirname, 'packages/fighting-design')
> 
> // 匹配下面所有的scss文件
> // src/a/a.scss  src/a2/a2/a2.scss  src/a3/a3/a3/a3.scss
> const inputArr = fg.sync(`${input}/**/*.scss`)
> 
> export default (): UserConfigExport => {
>   return {
>     //  打包。默认回会在根项目的dist文件
>     build: {
>       rollupOptions: {
>         input: inputArr,
>         output: {
>           entryFileNames: '[name].js',
>           chunkFileNames: '[name].js',
>           assetFileNames: '[name].[ext]'
>         }
>       }
>     }
>   }
> }
> 
> // 获取 ./src/a/a.scss 里面的a.scss
> const getLastItem = (thePath: string) => thePath.substring(thePath.lastIndexOf('/') + 1)
> 
> // 获取 a.scss 里面的a
> const getFileName = (data: string) => data.substring(0, data.indexOf('.'))
> 
> const EXT_REGEXP = /\.\w+$/
> 
> const replaceExt = (path: string, ext: string) => path.replace(EXT_REGEXP, ext)
> 
> // 思路，将dist里面的在替换回前面路径找到的inputArr
> // 先读dist，然后读inputArr。2个文件名一样，就把dist里面的内容写回去inputArr,并且要将scss后缀替换成css
> // 在删除原先的scss文件
> // 延时（不是好办法）是为了等前面打包走完，再执行这个
> 
> setTimeout(async () => {
>   const inputD: string = resolve(__dirname, 'dist')
>   const css = fg.sync(`${inputD}/*.css`)
>   for await (const key of inputArr) {
>     const fileName = getFileName(getLastItem(key))
>     for await (const source of css) {
>       const cssFileName = getFileName(getLastItem(source))
>       if (fileName === cssFileName) {
>         const data = readFileSync(source, 'utf-8')
>         writeFileSync(replaceExt(key, '.css'), data)
>         removeSync(key)
>       }
>     }
>   }
> }, 2000)
> ```

靠谱 

@wChenonly 

好像直接把less 文件引入组件更方便

![image](https://user-images.githubusercontent.com/23230215/217703684-89bfe017-dcc4-4e98-ad51-01d267a7eab7.png)
