### ISSUE TITLE
[Bug Report] van-image开启lazy-load以后van-image__loading未正常加载

### ISSUE THREAD

**Issue by jackjtr** [youzan/vant#11557]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-kj6it0?file=/src/App.vue

### Vant 版本

4.0.4

### 描述一下你遇到的问题。

van-image懒加载状态下加载中提示不能正常显示

### 重现步骤

重现链接打开后刷新预览界面

### 设备/浏览器

Chrome 110.0.5481.78（正式版本） （64 位）

https://user-images.githubusercontent.com/6552755/217779518-1d9557f5-1a0c-4210-82aa-e1e2baa4ad39.mp4

**Comment by wjw-gavin** [comment]
能显示，但是会出现短暂空白，猜测和vue-lazyload有关系吧...

https://user-images.githubusercontent.com/19986739/217759975-81c00ced-7dc2-4a7b-b040-e40e1ecb774a.mp4

**Comment by reuwi** [comment]
这个空白看起来和懒加载没关系，是浏览器加载图片时候的空白

**Comment by jackjtr** [comment]
添加了一段视频，如果图片较大，带lazy-load的图片组件在下载过程中只显示空白

**Comment by jackjtr** [comment]
![image](https://user-images.githubusercontent.com/6552755/218804652-49c07171-aad0-442d-adbe-eeda5a362d17.png)
通过查看元素可以发现用了lazy-load的组件div.van-image__loading没有渲染出来

![image](https://user-images.githubusercontent.com/6552755/218805505-a0f99f2e-66fc-4d4a-84c0-42d8c3c5007e.png)
结合源码可以认为一开始loading.value就一直是false

**Comment by mfts2048** [comment]
vant4.1.0 我看是已经修好了的

**Comment by classfang** [comment]
更新vant4.1.0仍然有该问题

**Comment by huihuilovekuikui** [comment]
遇到了同样的问题，使用的是4.1.2

**Comment by leggod** [comment]
4.1.2 没修复，有时候这个loading 会出来，有时候没有，导致是白的，很烦

**Comment by chenjiahan** [comment]
已在 4.3.0 版本修复

**Comment by lixiaofa** [comment]
> 已在 4.3.0 版本修复

![image](https://github.com/youzan/vant/assets/23230215/90a9829c-5174-443d-ba70-3900ca788d5d)
![image](https://github.com/youzan/vant/assets/23230215/af385013-f684-4f4a-b8e7-d50d69969a10)
![image](https://github.com/youzan/vant/assets/23230215/395381c3-71f4-435b-afdf-df6cf3a69ff5)
好像并没有修复
@chenjiahan

**Comment by chenjiahan** [comment]
@lixiaofa 有问题的话提个新 issue 吧，给个复现链接
