### ISSUE TITLE
[Bug Report] BackTop 组件在KeepAlive页面出现之后，跳转到其他页面之后仍然存在

### ISSUE THREAD

**Issue by wduoyu0617** [youzan/vant#11552]
### 重现链接

https://github.com/wanglt0617/vant-feedback

### Vant 版本

4.0.10

### 描述一下你遇到的问题。

正如上面提供的项目效果一样，在Vue的KeepAlive缓存效果下，首页页面滚动在出现BackTop之后进行页面跳转，发现在chilren页面也仍然存在BackTop组件，我的期望是BackTop组件能够不受KeepAlive组件的影响，正确的显示或者隐藏

### 重现步骤

运行项目
在首页滑动页面到底部，出现 children的按钮，点击按钮跳转到children页面出现bug效果

### 设备/浏览器

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by wanglt0617** [comment]
明白了，谢谢大佬
