### ISSUE TITLE
可以将picker中的v-text改为v-html吗

### ISSUE THREAD

**Issue by runningdoubi** [youzan/vant#1155]
使用v-text的话不能自定义每个item中的格式，比如下图的效果就不好实现
![5m_ 9oqz myc 8_8 x uc8](https://user-images.githubusercontent.com/22936818/40468250-6df43466-5f5f-11e8-978d-97fcc5ec401f.png)

**Comment by chenjiahan** [comment]
后续会支持选项的灵活定制

**Comment by chenjiahan** [comment]
已在 1.1.6 版本改为 v-html
