### ISSUE TITLE
[Bug Report] lazyRender = false don't work on van-collapse-item

### ISSUE THREAD

**Issue by xfolder** [youzan/vant#11555]
### Reproduction Link

https://codesandbox.io/s/vant-4-0-10-lazy-render-bug-s1nwvj?file=/src/App.vue:219-228

### Vant Version

4.0.10

### Describe the Bug

The content of van-collapse-item is always loaded in lazy-mode even when setting lazy-render to false

![image](https://user-images.githubusercontent.com/13942856/217515722-0824dad1-9bc9-477b-8ed6-11f96de69cc4.png)

### Reproduce Steps

https://codesandbox.io/s/vant-4-0-10-lazy-render-bug-s1nwvj?file=/src/App.vue:219-228

**Comment by wjw-gavin** [comment]
It looks correct? 

![image](https://user-images.githubusercontent.com/19986739/217527863-52d79aae-1c7f-41f7-b387-abe5bc66877e.png)

**Comment by xfolder** [comment]
My bad. Thanks
