### ISSUE TITLE
[Feature Request] van-tree-select 最左侧希望可以插入html

### ISSUE THREAD

**Issue by Tanglan123** [youzan/vant#11565]
### 这个功能解决了什么问题？

希望最左侧可以插入html片段，或者其它非纯text内容

### 你期望的 API 是什么样子的？

<van-tree-select></van-tree-select>
api不变更，可以自动检测插入的内容，进行相应的展示

**Comment by chenjiahan** [comment]
是希望左侧导航栏的选项可以通过 slot 来定制吗？

**Comment by Tanglan123** [comment]
> 是希望左侧导航栏的选项可以通过 slot 来定制吗？

是的
