### ISSUE TITLE
jest测试，获取不到vant-list的load事件

### ISSUE THREAD

**Issue by lyanerzhang** [youzan/vant#11573]
### Reproduction Link

https://gitee.com/ether123/vant-unit-test

### Vant Version

vant@3.6.10

### Describe the Bug

vue@3.2.13，jest@27.0.4
![image](https://user-images.githubusercontent.com/38914404/218444530-fb38e7fa-0560-4041-b546-7c5148d313ca.png)
默认情况下会触发list的load事件，但是这里没有触发，因此wrapper.emitted('load')取到的结果为 undefiend
![image](https://user-images.githubusercontent.com/38914404/218444795-fe6a4ca9-f34d-47ed-baa3-884ff2044341.png)

### Reproduce Steps

npm i 
npm run test:unit list.spec.ts

**Comment by lyanerzhang** [comment]
请问是什么原因呢？

**Comment by chenjiahan** [comment]
Jest 测试环境没有提供完整的 DOM 属性，需要添加一些额外的 mock 代码到 list.spec.ts 文件里

```ts
function mockHTMLElementOffset() {
  Object.defineProperties(HTMLElement.prototype, {
    offsetParent: {
      get() {
        return this.parentNode || {};
      },
    },
    offsetLeft: {
      get() {
        return parseFloat(window.getComputedStyle(this).marginLeft) || 0;
      },
    },
    offsetTop: {
      get() {
        return parseFloat(window.getComputedStyle(this).marginTop) || 0;
      },
    },
    offsetHeight: {
      get() {
        return parseFloat(window.getComputedStyle(this).height) || 100;
      },
    },
    offsetWidth: {
      get() {
        return parseFloat(window.getComputedStyle(this).width) || 100;
      },
    },
  });
}

mockHTMLElementOffset();
```
