### ISSUE TITLE
[Bug Report] 使用vant-cli打包报错

### ISSUE THREAD

**Issue by sukebin** [youzan/vant#11575]
### 重现链接

使用vant-cli打包报错

### Vant Cli 版本

5.1.0

### 描述一下你遇到的问题。

组件中的README.md文档中的内容是
### Events

```
| 方法名  | 说明                 | 参数                                             |
| ------- | -------------------- | ------------------------------------------------ |
| confirm | 确认选择地理位置事件 | 返回选中的地理位置信息，包括地理坐标，位置名称等 |
```
会报错

然后将内容修改为
```
| 方法名  | 说明                 | 参数                                             |
| ------- | -------------------- | ------------------------------------------------ |
```

| confirm | 确认选择地理位置事件 | 返回选中的地理位置信息，包括地理坐标，位置名称等 |
打包不会报错

### 重现步骤

组件中的README.md文档中的内容是
### Events

```
| 方法名  | 说明                 | 参数                                             |
| ------- | -------------------- | ------------------------------------------------ |
| confirm | 确认选择地理位置事件 | 返回选中的地理位置信息，包括地理坐标，位置名称等 |
```
会报错

报错信息：
(node:21456) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at formatArguments (file:///D:/git/sm-form-libraryV3/node_modules/@vant/cli/lib/compiler/web-types/formatter.js:32:52)
    at file:///D:/git/sm-form-libraryV3/node_modules/@vant/cli/lib/compiler/web-types/formatter.js:108:32
    at Array.forEach (<anonymous>)
    at file:///D:/git/sm-form-libraryV3/node_modules/@vant/cli/lib/compiler/web-types/formatter.js:103:24
    at Array.forEach (<anonymous>)
    at formatter (file:///D:/git/sm-form-libraryV3/node_modules/@vant/cli/lib/compiler/web-types/formatter.js:74:12)
    at file:///D:/git/sm-form-libraryV3/node_modules/@vant/cli/lib/compiler/web-types/index.js:23:9
    at Array.forEach (<anonymous>)
    at parseAndWrite (file:///D:/git/sm-form-libraryV3/node_modules/@vant/cli/lib/compiler/web-types/index.js:21:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

然后将内容修改为
```
| 方法名  | 说明                 | 参数                                             |
| ------- | -------------------- | ------------------------------------------------ |

| confirm | 确认选择地理位置事件 | 返回选中的地理位置信息，包括地理坐标，位置名称等 |
```
打包不会报错

**Comment by chenjiahan** [comment]
没复现呢，可以提供一个复现问题的仓库地址看下

**Comment by sukebin** [comment]
仓库地址： https://github.com/sukebin/vant-test

**Comment by chenjiahan** [comment]
已在 @vant/cli 6.0.0 版本修复
