### ISSUE TITLE
[Feature Request] 实现一个floating-panel 浮动面板组件

### ISSUE THREAD

**Issue by MaybeQHL** [youzan/vant#11577]
### 这个功能解决了什么问题？

有一些特定的页面需要这种面板

### 你期望的 API 是什么样子的？

类似这个组件 https://mobile.ant.design/zh/components/floating-panel/

**Comment by chenjiahan** [comment]
这个需求已经有 issue 在跟进了：https://github.com/youzan/vant/issues/11344
