### ISSUE TITLE
vant  DatetimePicker如何实现分钟自定义？

### ISSUE THREAD

**Issue by gwping** [youzan/vant#11570]
DatetimePicker中完整时间 如何实现自定义显示分钟值，例如只显示00,30这样，只能选择整点和半点

多谢帮忙，如看到及时回复谢谢

**Comment by chenjiahan** [comment]
可以参考这个示例：https://vant-ui.github.io/vant/v2/#/zh-CN/datetime-picker#xuan-xiang-guo-lu-qi
