### ISSUE TITLE
[Feature Request] 写了uni-app版本的vant，支持H5、微信小程序、QQ小程序

### ISSUE THREAD

**Issue by novlan1** [youzan/vant#11576]
写了一个uni-app版本的vant：

1. 基础组件50+ 
2. 支持H5、微信小程序、QQ小程序
3. 零外部依赖，不依赖三方 npm 包
4. 丰富的文档和示例
5. 支持主题定制
6. 支持国际化

![image](https://user-images.githubusercontent.com/41728540/218771030-e7a11c56-9d30-4edd-abc0-7a17859c15f6.png)

**Comment by chenjiahan** [comment]
可以贴一下开源仓库的地址呢

**Comment by rhymedys** [comment]
这个有地址吗？

**Comment by novlan1** [comment]
> 这个有地址吗？

https://github.com/novlan1/press-ui

**Comment by xeoshow** [comment]
> > 这个有地址吗？
> 
> https://github.com/novlan1/press-ui

@novlan1 你好啊，这个仓库打不开了，404报错。是否也支持抖音小程序和小红书小程序？谢谢
