### ISSUE TITLE
移除项目中依赖的 babel-plugin-import 插件后，运行报错useWindowSize 是 undefined

### ISSUE THREAD

**Issue by XiZev** [youzan/vant#11583]
### 重现链接

https://github.com/youzan/vant/issues

### Vant 版本

4.0.9

### 描述一下你遇到的问题。

移除项目中依赖的 babel-plugin-import 插件后，运行报错useWindowSize 是 undefined

### 重现步骤

移除项目中依赖的 babel-plugin-import 插件后，运行报错：useWindowSize 是 undefined

**Comment by chenjiahan** [comment]
麻烦提供有效的复现链接
