### ISSUE TITLE
步进器输入框大小偏小

### ISSUE THREAD

**Issue by shuliuzhenhua** [youzan/vant#1158]
步进器，中间这个输入框，会比边上的加减偏小。。不好意思我css很菜，我是后台学的 vue
，所以找不到问题

**Comment by shuliuzhenhua** [comment]
把 .van-stepper__input 设置一个 padding: 1.5px 就解决了。还是不知道为什么会这样。

**Comment by shuliuzhenhua** [comment]
额没听懂上面那兄弟说的啥意思。

**Comment by chenjiahan** [comment]
请问出现这个问题的浏览器和系统版本是？

**Comment by shuliuzhenhua** [comment]
@chenjiahan google 浏览器，vant是直接下载的最新版。你们没问题么。

**Comment by chenjiahan** [comment]
未复现的问题
