### ISSUE TITLE
[Feature Request] 图片上传支持覆盖上传

### ISSUE THREAD

**Issue by Lazydd** [youzan/vant#11587]
### 这个功能解决了什么问题？

当上传图片设置不展示删除按钮且最大个数为1或其他值时，我希望当上传完成后，再次点击图片可以进行覆盖上传，而不是无法操作，在这个问题里[https://github.com/youzan/vant/issues/11217](url)，我尝试使用chooseFile进行操作，但是因为上传的input不见了，导致这个方法没效果

### 你期望的 API 是什么样子的？

<van-uploader cover deletable/>

**Comment by zhousg** [comment]
点击覆盖上传，和预览功能会冲突吧？

**Comment by chenjiahan** [comment]
> 点击覆盖上传，和预览功能会冲突吧？

确实有这个问题，如果我们要在 Uploader 中支持覆盖上传的话，可以提供一个 prop 来开启覆盖上传的功能，同时告诉使用者这样会关闭预览功能
