### ISSUE TITLE
[Bug Report] van-field只初始化了第一个组件

### ISSUE THREAD

**Issue by fu827707013** [youzan/vant#11585]
### 重现链接

http://demo.ultimus.com.cn:8101/modules/uwf/CustomDemo/Form/demo2

### Vant 版本

2.12

### 描述一下你遇到的问题。

van-field控件只实例化了第一个出来
其他控件，包括van-field都不继续实例化显示了

### 重现步骤

从官方文档直接copy的代码，

`

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="https://unpkg.com/vant@2.12/lib/index.css" />
    
    <script src="https://unpkg.com/vue@2.6/dist/vue.min.js"></script>
    <script src="https://unpkg.com/vant@2.12/lib/vant.min.js"></script>

</head>

`

body；
`
    <div id="app">
        <van-form @submit="onSubmit">
            <van-field v-model="username" name="用户名" label="用户名" placeholder="用户名" />
            <van-field v-model="password" type="password" name="密码" label="密码" placeholder="密码" />
            <div style="margin: 16px;">
                <van-button round block type="info" native-type="submit">提交</van-button>
            </div>
        </van-form>
    </div>
`

script:
`
 // 在 #app 标签下渲染一个按钮组件
        new Vue({
            el: '#app',
            data() {
                return {
                    title: '基础',
                    card: '卡片',
                    username: '',
                    password: '',
                };
            },
            methods: {
                onSubmit(values) {
                    console.log('submit', values);
                },
            },
        });

        // 调用函数组件，弹出一个 Toast
        // vant.Toast('提示');

        // 通过 CDN 引入时不会自动注册 Lazyload 组件
        // 可以通过下面的方式手动注册
        Vue.use(vant.Field);
        Vue.use(vant.Form);
        Vue.use(vant.Lazyload);
        Vue.use(vant.Button);
`

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/219845492-bbd3d147-829d-4df6-9106-63698e5c5a0d.png)

https://vant-contrib.gitee.io/vant/#/zh-CN/faq#zai-html-zhong-wu-fa-zheng-que-xuan-ran-zu-jian
