### ISSUE TITLE
[Bug Report] number-keyboard 触控设备无效

### ISSUE THREAD

**Issue by 202780181** [youzan/vant#11580]
### 重现链接

null

### Vant 版本

2.10.12

### 描述一下你遇到的问题。

https://user-images.githubusercontent.com/27540653/218974776-3cc7bd07-5f0a-4095-9a91-996d9646cb16.mp4

### 重现步骤

* 我在触控设备上使用number-keyboard键盘点击时无法触发输入事件，我在想是否未支持触控点击事件？

**Comment by 202780181** [comment]
使用的模式是双向数据绑定

<van-field
  readonly
  clickable
  :value="value"
  @touchstart.native.stop="show = true"
/>
<van-number-keyboard
  v-model="value"
  :show="show"
  :maxlength="6"
  @blur="show = false"
/>

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/219845709-2d09c7c2-99e4-4877-a363-7a64a40b7519.png)

https://vant-contrib.gitee.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei

**Comment by Corgis** [comment]
有效
