### ISSUE TITLE
IOS 12.4.1 iPhone Xs          van-search 无法输入

### ISSUE THREAD

**Issue by guda-art** [youzan/vant#11586]
### 重现链接

https://jelly.cnfschool.net/help_dist/#/helpCenter

### Vant 版本

^2.12.53

### 描述一下你遇到的问题。

IOS 12.4.1 iPhone Xs
van-search 可以唤起键盘不能聚焦输入框(无光标闪烁)无法输入   (Field组件) 也是一样
其它机型系统上很正常  

### 重现步骤

点击搜索组件即可复现问题

### 设备/浏览器

IOS 12.4.1 iPhone Xs  真机环境

**Comment by chenjiahan** [comment]
麻烦验证下 Vant 官网示例能否复现该问题

**Comment by guda-art** [comment]
> 麻烦验证下 Vant 官网示例能否复现该问题

官网并没有此问题......

**Comment by chenjiahan** [comment]
那应该是项目里其他代码影响的，可以排查下
