### ISSUE TITLE
[Feature Request] Vant 组合式 API 继承 `VusUse`

### ISSUE THREAD

**Issue by evanlong0926** [youzan/vant#11581]
### 这个功能解决了什么问题？

我发现我安装 `Vant` 和 `VueUse` 后，`useWindowSize` 方法存在冲突
1.  防止于 `VueUse` 函数冲突，做多余的重复工作
2.  更加丰富的组合式API（包含蓝牙连接、设备连接状态及设备名称等功能、非常适合移动端）
3.  可以基于 `VusUse` 封装更多新奇和实用的组件，比如二维码组件等等

### 你期望的 API 是什么样子的？

```ts
import { useFetch } from '@vant/vueuse';
import { useWindowSize } from '@vant/vueuse';
```

**Comment by chenjiahan** [comment]
Vant 不计划引入任何三方依赖呢。

如果需要额外的组合式 API，直接从 VueUse 里引用就好，没必要让 Vant 再封装一层。

**Comment by evanlong0926** [comment]
那安装 Vant 和 VueUse 后，useWindowSize 方法存在冲突怎么处理呢？

**Comment by chenjiahan** [comment]
具体啥冲突？

**Comment by evanlong0926** [comment]
> 具体啥冲突？

同名了，且使用方法也是一样

**Comment by chenjiahan** [comment]
你区分下引用位置就行

**Comment by evanlong0926** [comment]
> 你区分下引用位置就行

Ok.

**Comment by Oshibuki** [comment]
> 具体啥冲突？

没有直接使用useWindowSize,只是同时引入了vant和vueuse，之后可以通过编译，但打开页面就一直白屏，控制台报错：
`Uncaught TypeError: RefImpl is not a constructor
    createRef reactivity.esm-bundler.js:1046
    ref reactivity.esm-bundler.js:1037
    useWindowSize index.esm.mjs:382
    <anonymous> dom.mjs:54`

**Comment by mixin1997** [comment]
> update:已解决，取消vueuse的自动导入，改为手动导入即可
> 
> > 具体啥冲突？
> 
> 没有直接使用useWindowSize,只是同时引入了vant和vueuse，之后可以通过编译，但打开页面就一直白屏，控制台报错： ` Uncaught TypeError: RefImpl is not a constructor
> 
> ```
> createRef reactivity.esm-bundler.js:1046
> 
> ref reactivity.esm-bundler.js:1037
> 
> useWindowSize index.esm.mjs:382
> 
> <anonymous> dom.mjs:54
> ```
> 
> 

> update:已解决，取消vueuse的自动导入，改为手动导入即可
> 
> > 具体啥冲突？
> 
> 没有直接使用useWindowSize,只是同时引入了vant和vueuse，之后可以通过编译，但打开页面就一直白屏，控制台报错： ` Uncaught TypeError: RefImpl is not a constructor
> 
> ```
> createRef reactivity.esm-bundler.js:1046
> 
> ref reactivity.esm-bundler.js:1037
> 
> useWindowSize index.esm.mjs:382
> 
> <anonymous> dom.mjs:54
> ```
> 
> `

你好，这个怎么解决的呀，我们没有自动引入，还是报错😭

**Comment by Yueyanc** [comment]
> > update:已解决，取消vueuse的自动导入，改为手动导入即可
> > > 具体啥冲突？
> > 
> > 
> > 没有直接使用useWindowSize,只是同时引入了vant和vueuse，之后可以通过编译，但打开页面就一直白屏，控制台报错： ` Uncaught TypeError: RefImpl is not a constructor
> > ```
> > createRef reactivity.esm-bundler.js:1046
> > 
> > ref reactivity.esm-bundler.js:1037
> > 
> > useWindowSize index.esm.mjs:382
> > 
> > <anonymous> dom.mjs:54
> > ```
> 
> > update:已解决，取消vueuse的自动导入，改为手动导入即可
> > > 具体啥冲突？
> > 
> > 
> > 没有直接使用useWindowSize,只是同时引入了vant和vueuse，之后可以通过编译，但打开页面就一直白屏，控制台报错： ` Uncaught([网络] 没有保护) TypeError: RefImpl is not a constructor(构造函数)
> > ```
> > createRef reactivity.esm-bundler.js:1046
> > 
> > ref reactivity.esm-bundler.js:1037
> > 
> > useWindowSize index.esm.mjs:382
> > 
> > <anonymous> dom.mjs:54
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `
> 
> 你好，这个怎么解决的呀，我们没有自动引入，还是报错😭

移动
`import { createApp } from "vue";`
为第一个导入

**Comment by zaxlct** [comment]
> > > update:已解决，取消vueuse的自动导入，改为手动导入即可
> > > > 具体啥冲突？
> > > 
> > > 
> > > 没有直接使用useWindowSize,只是同时引入了vant和vueuse，之后可以通过编译，但打开页面就一直白屏，控制台报错： ` Uncaught TypeError: RefImpl is not a constructor
> > > ```
> > > createRef reactivity.esm-bundler.js:1046
> > > 
> > > ref reactivity.esm-bundler.js:1037
> > > 
> > > useWindowSize index.esm.mjs:382
> > > 
> > > <anonymous> dom.mjs:54
> > > ```
> > 
> > 
> > > update:已解决，取消vueuse的自动导入，改为手动导入即可
> > > > 具体啥冲突？
> > > 
> > > 
> > > 没有直接使用useWindowSize,只是同时引入了vant和vueuse，之后可以通过编译，但打开页面就一直白屏，控制台报错： ` Uncaught([网络] 没有保护) TypeError: RefImpl is not a constructor(构造函数)
> > > ```
> > > createRef reactivity.esm-bundler.js:1046
> > > 
> > > ref reactivity.esm-bundler.js:1037
> > > 
> > > useWindowSize index.esm.mjs:382
> > > 
> > > <anonymous> dom.mjs:54
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `
> > 
> > 
> > 你好，这个怎么解决的呀，我们没有自动引入，还是报错😭
> 
> 移动 `import { createApp } from "vue";` 为第一个导入

泪目....此 BUG 耽误了我三个多小时
