### ISSUE TITLE
[Feature Request] 选择时间的组件支持部分时间高亮

### ISSUE THREAD

**Issue by west-yc** [youzan/vant#11590]
### 这个功能解决了什么问题？

在我们的项目需求中用户一次可以知道那些时间是有数据的以此告知用户选择这些时间。

### 你期望的 API 是什么样子的？

<van-date-picker
  v-model="currentDate"
  title="选择日期"
  :min-date="minDate"
  :max-date="maxDate"
  :highLight="highLight"
/>

**Comment by chenjiahan** [comment]
建议用 filter 属性把不支持的时间过滤掉，或者用 option 插槽来自定义高亮样式
