### ISSUE TITLE
vant2文档打不开了 404

### ISSUE THREAD

**Issue by 208895638** [youzan/vant#11591]
### 重现链接

https://vant-contrib.gitee.io/vant/v2

### Vant 版本

2.x

### 描述一下你遇到的问题。

文档地址打不开了

### 重现步骤

文档地址打不开了

**Comment by chenjiahan** [comment]
有时候 Gitee Page 不太文档，可以访问 GitHub 版本：https://vant-ui.github.io/vant/#/zh-CN
