### ISSUE TITLE
[Feature Request] Key icon

### ISSUE THREAD

**Issue by tintin10q** [youzan/vant#11596]
### What problem does this feature solve?

Having icons for keys.

### What does the proposed API look like?

```xml
        <van-icon name="key-o"/>
        <van-icon name="key"/>
```

**Comment by chenjiahan** [comment]
Sorry, we have no plan to add a new `key` icon, maybe you can use the `custom iconfont`: https://vant-ui.github.io/vant/#/en-US/icon#add-custom-iconfont
