### ISSUE TITLE
复选框和步进器共用问题

### ISSUE THREAD

**Issue by shuliuzhenhua** [youzan/vant#1159]
我在 van-checkbox-group 中放入了一个 van-stepper ，想实现类似淘宝购物车的效果，左边是复选框，右边有一个步进器，可是当我的步进器的值发送变动的时候，会触发 复选框的计算属性 ，这是后复选框的值也会发生改变，然后复选框就会取消，或者勾选。

**Comment by shuliuzhenhua** [comment]
额。我已经解决了。偶然间发现的，其实不是点击了进度条触发了。复选框事件，刚刚不小心点了右边的图片也触发了，然后我看了下文档 在 复选框中 加入 label-disabled 就可以了。

**Comment by chenjiahan** [comment]
嗯，是这样的
