### ISSUE TITLE
请问captain-ui 开源了吗？

### ISSUE THREAD

**Issue by PetelZhang** [youzan/vant#116]
请问captain-ui开源了吗？

**Comment by cookfront** [comment]
captain-ui的许多组件已经陆续迁移到了vant了，请问你是需要用到captain-ui的哪个组件么

**Comment by PetelZhang** [comment]
嗯，captain-ui的组件很多我们都用的到，所以在下个项目中想使用这个组件库，但是怕captain-ui没有开源，到时候出了Bug不好修改。

**Comment by cookfront** [comment]
嗯嗯 你可以说下你们用到的哪些组件，我们可以优先开源出来

**Comment by PetelZhang** [comment]
觉得都挺实用的，因为基础类的组件其他的Vue开源的组件库都有。想用你们这个是因为你们的captain-ui的组件库，很多电商业务场景都能直接使用，避免再去开发。很适合我们这种小型的项目型开发，毕竟需要快嘛，一点不成熟的建议哈。

**Comment by cookfront** [comment]
嗯嗯 那你可以先用起来，有bug我们也会跟进的

**Comment by pangxie1991** [comment]
@PetelZhang captain-ui使用问题，可以扫码进微信群，在群里直接问~
![vant&captain-ui使用答疑群](https://img.yzcdn.cn/public_files/2017/09/07/9e0423174bee6f116acf32a808a68d23.jpeg)

**Comment by liucyi** [comment]
能否把上传多图片的控件迁移过去？

**Comment by chenjiahan** [comment]
@liucyi ImgUploader 组件已列入迁移计划中，请关注 Vant 后续的版本更新
