### ISSUE TITLE
[Bug Report] Search组件update:model-value 最后清空时的回调不会触发

### ISSUE THREAD

**Issue by Panda2Chan** [youzan/vant#11604]
### 重现链接

无

### Vant 版本

4.0.10

### 描述一下你遇到的问题。

Search组件update:model-value 最后清空时的回调不会触发

### 重现步骤

```vue
 <van-search @update:model-value="(value: string) => searchEvent(value)" placeholder="点击搜索" />

searchEvent最后清空时回调不会触发

### 设备/浏览器

edge浏览器

**Comment by chenjiahan** [comment]
清空指的是「点击清空按钮」吗？我这边是可以正常触发事件的。

如果是其他情况的话，可以提供一个 codesandbox 复现链接看下

**Comment by Zheng-Shuo** [comment]
我也遇到了，应该是用键盘的删除按键将内容完全删除之后最后一次空的事件不触发
