### ISSUE TITLE
[Bug Report] swipe的内容是动态的时候,最后一个再下滑就会出问题

### ISSUE THREAD

**Issue by tckxjzc** [youzan/vant#11608]
### 重现链接

https://snackdrama.com/

### Vant 版本

4.0.2

### 描述一下你遇到的问题。

swipe的内容是动态的时候,最后一个再下滑就会出问题,
swipe里面的元素固定时就没问题

### 重现步骤

滑到最后一个(链接中最后一个是5)再下滑就能重现

### 设备/浏览器

谷歌浏览器

**Comment by chenjiahan** [comment]
链接里没看到有 Swipe 组件呢，麻烦提供一个 codesandbox 复现链接吧
