### ISSUE TITLE
Swiper 组件 在钉钉浏览器中 ios 16.3 不会有滚动效果~

### ISSUE THREAD

**Issue by wiscgazf** [youzan/vant#11613]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/swipe

### Vant 版本

2.12.6

### 描述一下你遇到的问题。

Swiper 组件 在钉钉浏览器中 ios 16.3 不会有滚动效果~，其他ios手机没试， 在16.3 没有滑动切换，而是直接换成下一个swiper-item内容~，官网链接也是如此

### 重现步骤

1、复制 官方链接 https://vant-contrib.gitee.io/vant/v2/#/zh-CN/swipe 到钉钉浏览器
2、ios 16.3 打开
3、滚动效果失效

**Comment by chenjiahan** [comment]
这种一般是浏览器的 bug，组件层面不好做兼容哈。

可以尝试重启浏览器或者升级浏览器 or 系统版本试试
