### ISSUE TITLE
van-field组件当label是动态值时，is-link的值也是动态并且来源于接口，v-model绑定的值不更新页面

### ISSUE THREAD

**Issue by zengjie911** [youzan/vant#11625]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-37rz0x?file=/src/App.vue

### Vant 版本

3.6.11

### 描述一下你遇到的问题。

van-field组件当label是动态值时，is-link的值也是动态并且来源于接口，v-model绑定的值不更新页面，例子上没法加接口请求，就大概写的字段都是本地提前申明的了

### 重现步骤

使用表单van-field组件，将label设置成动态的，然后is-link属性设置成动态的，并且来源是接口（如果是本地直接申明不会有问题），接口的数据是放在ref申明的字段里面的，这时候v-model绑定的值在页面上就不会显示出来，但是v-model的值是绑定上了，再结合picker组件，去选值的时候，页面也不再更新，如果将接口拿到的值赋值给事先在本地申明的字段上，再放到is-link上一样也页面展示位置变成了空白

### 设备/浏览器

谷歌浏览器

**Comment by chenjiahan** [comment]
用 setTimeout 模拟了一下你说的问题，没有复现呢

![Uploading image.png…]()

**Comment by zengjie911** [comment]
> 用 setTimeout 模拟了一下你说的问题，没有复现呢
> 
> ![image](https://user-images.githubusercontent.com/7237365/224545836-6fbd1300-5ea4-4e33-bf28-8848d992939f.png)

数据从接口过来就会有问题，这种模拟的本地也不会有问题，都试过了，换了好几个接口试了都是有问题的

**Comment by chenjiahan** [comment]
从逻辑上来，说数据是从接口获得，还是通过其他方式 mock，对组件而言是一样的，没有区别。

**Comment by zengjie911** [comment]
> 从逻辑上来说，数据是从接口获得，还是通过其他方式 mock，对组件而言是一样的，没有区别。

![1](https://user-images.githubusercontent.com/15998521/224623384-d89c7148-96b4-42e5-bb87-1f1b6eb4d0f7.png)
![2](https://user-images.githubusercontent.com/15998521/224623405-138c0bbd-ea0d-46a3-90a5-f86abe736555.png)
![3](https://user-images.githubusercontent.com/15998521/224623421-ecf1f7c0-8190-4641-8ed9-0d374a8b4b3d.png)
![4](https://user-images.githubusercontent.com/15998521/224623431-50533507-959c-4340-9bdd-3fb3bbe3ba0d.png)
![5](https://user-images.githubusercontent.com/15998521/224623445-68025cae-5059-4137-aea6-3d37dc9d84b4.png)
接口数据的文本是文，label和is-link都是动态的时候，页面没更新，但是打印了一下绑定的值是有的，后面把label换成写死的，is-link还是动态的，页面就更新了，并且还试了label动态，is-link写死，页面也正常更新显示，上面数据都是来源于接口，不能本地申明的字段，才会又这样的问题，通过settimeout的方式mock出来的数据也是正常的，只有接口来的数据有问题
