### ISSUE TITLE
[Bug Report] @vant/cli@6.0.0 build vant@4.0.11+vue@3.2.47 时在 `Build Type Declarations` 阶段报错

### ISSUE THREAD

**Issue by jellyfishgh** [youzan/vant#11627]
### 重现链接

https://github.com/jellyfishgh/vant.git

### Vant 版本

4.0.11

### 描述一下你遇到的问题。

@vant/cli@6.0.0 build vant@4.0.11+vue@3.2.47 时在 `Build Type Declarations` 阶段报错

### 重现步骤

pnpm i
pnpm build

### 设备/浏览器

macos, node 18

**Comment by chenjiahan** [comment]
vant 是一个 monorepo 仓库，你升级依赖的时候，最好统一升级各个包下面的 Vue 版本，如果只升级了其中一个目录的依赖版本，是可能出现版本不一致导致类型报错的。

这里是一个正确升级的示例：https://github.com/youzan/vant/pull/11665
