### ISSUE TITLE
[Bug Report] Circle无法重复设置rate值

### ISSUE THREAD

**Issue by meesii** [youzan/vant#11623]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/circle

### Vant 版本

4.0.11

### 描述一下你遇到的问题。

`currentRate.value = 0;
rate.value = 0;

const t = setInterval(() => {
    if (rate.value < 100) {
        rate.value += 10;
    } else {
        clearInterval(t);
    }
}, 100);`

通过如下代码设置了一个加载动画，但是如果这个动作重复执行的话，进度条不会有任何变化。
监控currentRate的值也不会再发生变化

### 重现步骤

如上

**Comment by wjw-gavin** [comment]
我这试的没问题哈
https://codesandbox.io/s/vant-4-issue-template-forked-dk3xjk?file=/src/App.vue
