### ISSUE TITLE
text-ellipsis组件使用异常

### ISSUE THREAD

**Issue by wypbin** [youzan/vant#11634]
### 重现链接

0

### Vant 版本

4.0.11

### 描述一下你遇到的问题。

4.0.11的npm包里面无text-ellipsis组件
![image](https://user-images.githubusercontent.com/48672496/222319551-1af64eee-2c75-4375-89dd-d1c235c47df9.png)
![image](https://user-images.githubusercontent.com/48672496/222319576-42962bd6-5a0c-438b-9278-d0e80c4e534b.png)
![image](https://user-images.githubusercontent.com/48672496/222319679-b3847948-05cf-4de1-9f7e-14aa1291a719.png)
![image](https://user-images.githubusercontent.com/48672496/222319740-d3a2a610-c5b4-4325-9655-4474c4cad454.png)

### 重现步骤

0

**Comment by wjw-gavin** [comment]
还没发版哈，等发版就有了

**Comment by chenjiahan** [comment]
本周末会发布 4.1.0 版本，届时可以使用 TextEllipsis 组件

**Comment by wypbin** [comment]
老哥们   还没发布吗

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chenjiahan** [comment]
昨天已经发布了

**Comment by wypbin** [comment]
Npm包和网站上还是4.0.11

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wjw-gavin** [comment]
对的哈

![image](https://user-images.githubusercontent.com/19986739/223016139-ead3eb01-5d80-4f80-b7a8-b61090d8c902.png)
![image](https://user-images.githubusercontent.com/19986739/223016199-46e1cce8-5a0c-4311-a82c-a8d6a77a8591.png)

**Comment by wypbin** [comment]
奇怪   我重新创建了个项目   现在npm下来的还是4.0.11

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
