### ISSUE TITLE
[Feature Request] cascader 组件若使用异步加载，加在后发现没数据，当前tab会显示为空

### ISSUE THREAD

**Issue by popring** [youzan/vant#11633]
### 这个功能解决了什么问题？

如题，使用popup嵌套cascader时，自己手动关闭显示还好，但用户重新唤起后不重置，当前tab会仍然为空，这种体验不太好

### 你期望的 API 是什么样子的？

能有一种方式，在异步加载完成时，当前没有数据，直接当作最后一层数据处理吗？

**Comment by chenjiahan** [comment]
这个问题目前没有很合适的 API 来处理。

因为 Cascader 组件里没有定义 ”无数据“ 这个状态，对组件来说，数据为空可能只是在请求过程中，不代表一定没有。
