### ISSUE TITLE
vant4.0.3版本代码在使用vite搭建的框架中，打包前没有问题，打包后样式被覆盖

### ISSUE THREAD

**Issue by alittlesister** [youzan/vant#11631]
### 重现链接

https://postimg.cc/gallery/fMLWKhK

### Vant 版本

4.0.3

### 描述一下你遇到的问题。

1、popup和toast组件样式冲突
2、import引入的函数式调用带icon的toast的icon字体大小被覆盖

### 重现步骤

直接触发就会出现
局部组件引用方式，VantResolver

### 设备/浏览器

网页打开

**Comment by wjw-gavin** [comment]
参考下这个：https://github.com/youzan/vant/issues/11049
