### ISSUE TITLE
"vant^4.0.10""vue^3.2.45""vite^4.1.0""tailwindcss^3.2.6"开发时以及打包后均出现样式覆盖的问题

### ISSUE THREAD

**Issue by HQ222222** [youzan/vant#11635]
### Reproduction Link

https://postimg.cc/cr29QLhM

### Vant Version

4.0.10

### Describe the Bug

[![VUM0-BS-LM-G-OF-OT-KDECN.png](https://i.postimg.cc/rwFB2dtb/VUM0-BS-LM-G-OF-OT-KDECN.png)](https://postimg.cc/cr29QLhM)
### Reproduce Steps

版本："vant^4.0.10"，"vue^3.2.45"，"vite^4.1.0"，"tailwindcss^3.2.6", "unplugin-vue-components^0.23.0"
直接使用会出现如上情况，使用unplugin-vue-components按需引入，（我测试过全量引入，也会存在样式覆盖的问题）

*参考[11049](https://github.com/youzan/vant/issues/11049) issue 暂未找到解决方法：https://github.com/youzan/vant/issues/11049*

### Device / Browser

谷歌浏览器

**Comment by wjw-gavin** [comment]
给个复现仓库，抽空帮你看下哈

**Comment by HQ222222** [comment]
https://github.com/HQ222222/hq_testcss
这是项目代码地址，非常感谢😁

**Comment by HQ222222** [comment]
> 给个复现仓库，抽空帮你看下哈

https://github.com/HQ222222/hq_testcss
这是项目代码地址，非常感谢😁

**Comment by wjw-gavin** [comment]
`import 'vant/lib/toast/style/index'` 改为 `import 'vant/es/toast/style'`  从 es module 中导入就好了。
https://vant-ui.github.io/vant/#/zh-CN/quickstart#4.-yin-ru-han-shu-zu-jian-de-yang-shi

![image](https://user-images.githubusercontent.com/19986739/222432482-66fc1186-a843-4788-9809-11850ee0510a.png)

**Comment by HQ222222** [comment]
好的，问题完美的解决了，是我盲目的引入样式导致的，非常感谢您能在百忙之中修正我这个低级的错误，非常感谢👍这是我第一次提交issue，也非常感谢您能耐心的为我解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月2日(星期四) 晚上8:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant] "vant^4.0.10""vue^3.2.45""vite^4.1.0""tailwindcss^3.2.6"开发时以及打包后均出现样式覆盖的问题 (Issue #11635)





 
import 'vant/lib/toast/style/index' 改为 import 'vant/es/toast/style'  从 es module 中导入就好了。
 https://vant-ui.github.io/vant/#/zh-CN/quickstart#4.-yin-ru-han-shu-zu-jian-de-yang-shi
