### ISSUE TITLE
vant2升级vant3后弹框类样式丢失

### ISSUE THREAD

**Issue by maojindao55** [youzan/vant#11646]
### 重现链接

暂无

### Vant 版本

3.6.11

### 描述一下你遇到的问题。

代码如下，并且按照文档已经手动引入dialog style, 但是样式依旧无法生效
```
import { Dialog } from 'vant';
import 'vant/es/dialog/style';
Dialog({ message: '提示' });


```
![image](https://user-images.githubusercontent.com/6436125/223286744-4595bd90-cc5b-4bf2-b556-aa5d6602b228.png)

### 重现步骤

1. vue2升级vue3  

1. vant2升级vant3
2. 
```
import { Dialog } from 'vant';
import 'vant/es/dialog/style';
Dialog({ message: '提示' });

```

### 设备/浏览器

chrome

**Comment by maojindao55** [comment]
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/6436125/223354450-40603de8-dc0f-4f2e-8799-c2db061606ca.png">
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/6436125/223354688-86e95ac0-19f4-455e-bc89-0648a14c8fc3.png">
对比了下，是样式残缺。具体不知道原因

**Comment by wjw-gavin** [comment]
我这正常，建议排查一下哈~
https://codesandbox.io/s/vant-4-issue-template-forked-dk3xjk?file=/src/App.vue

![image](https://user-images.githubusercontent.com/19986739/223654150-b1352c47-226b-4b2b-a255-35061f83e0a8.png)

![image](https://user-images.githubusercontent.com/19986739/223654195-640aeed5-c872-4928-9054-74b15233ec64.png)
