### ISSUE TITLE
[Feature Request] DatetimePicker(日期时间选择器)可选时间参数能否支持多段时间数组

### ISSUE THREAD

**Issue by jackliliang** [youzan/vant#11652]
### 这个功能解决了什么问题？

DatetimePicker(日期时间选择器)可选时间参数能否支持多段时间数组
现在遇到一个场景，需要对多段时间（time）进行校验，同时满足不能小于当前时间

### 你期望的 API 是什么样子的？

      <van-datetime-picker
        :selectableRange="[
            ["09:40:00-12:00:00"],
            ["14:40:00-16:00:00"]
         ]"
      />

**Comment by 875817196** [comment]
+1，遇到过类似的场景，当时是二次封装了该组件解决的

**Comment by 875817196** [comment]
小白问个问题，可以通过解决该问题提交PR吗

**Comment by chenjiahan** [comment]
用 filter 属性不能实现嘛

**Comment by jackliliang** [comment]
> 用 filter 属性不能实现嘛

哈哈哈，仔细看了下文档，filter好像也能够，不过稍微麻烦了些

**Comment by 851543671** [comment]
> > 用filter属性不能现实嘛
> 
> 哈哈哈哈，仔仔细看了下文档，滤镜好像也能够，不过瘾微麻了一些

  if (type === 'hour') {
     const index = options.findIndex((item) => item.text === hour)
     return index !== -1 ? options.slice(index) : []
   }
文档的filter 判断传入的时间 截取一下就好了

**Comment by 851543671** [comment]
> > 用filter属性不能现实嘛
> 
> 哈哈哈哈，仔仔细看了下文档，滤镜好像也能够，不过瘾微麻了一些

  if (type === 'hour') {
     const index = options.findIndex((item) => item.text === hour)
     return index !== -1 ? options.slice(index) : []
   }
文档的filter 判断传入的时间 截取一下就好了

**Comment by chenjiahan** [comment]
嗯嗯，用 filter 来处理就好，目前不计划提供新的 props 哈
