### ISSUE TITLE
[Feature Request] vant/use 增加 peerDependencies vue

### ISSUE THREAD

**Issue by agileago** [youzan/vant#11659]
### What problem does this feature solve?

在monorepo项目中同时有项目使用了vue2和vue3会导致报错

![image](https://user-images.githubusercontent.com/11799110/223911681-ba9d95fd-a564-4be5-9a74-3bc98d7d6bbb.png)

### What does the proposed API look like?

增加peerDependencies

**Comment by chenjiahan** [comment]
已发布 1.5.1 修复版本咯
