### ISSUE TITLE
[Bug Reporth] H5 vant3.6.5 所以弹出按钮框默认文字丢失 比如picker Dialog

### ISSUE THREAD

**Issue by Lbt777** [youzan/vant#11657]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-ivuth0

### Vant 版本

3.6.5

### 描述一下你遇到的问题。

打包后手机上运行就会出现

### 重现步骤

点击按钮

**Comment by Lbt777** [comment]
![微信图片_20230308155450](https://user-images.githubusercontent.com/46510415/223660700-67f229f6-dfe8-4e3c-b79e-305677e14076.jpg)
写法
<van-popup v-model:show="show" position="bottom">
    <van-picker title="" :columns="columns"
      :columns-field-names="{ text: 'label', }" @confirm="onConfirm" @cancel="show = false" />
  </van-popup>

**Comment by chenjiahan** [comment]
这个问题应该和 Vant 没关系，建议看看是不是其他地方把 Vant Button 的样式给覆盖掉了
