### ISSUE TITLE
[Feature Request] vant-cli创建基于vant的项目(按照方法二. 按需引入组件样式)，build:site 静态站展示正常，build时 van-* 组件异常。

### ISSUE THREAD

**Issue by quliangen** [youzan/vant#11653]
### 这个功能解决了什么问题？

实际业务中，一般会使用 vant 二次封装业务组件库。
使用 vant-cli创建的项目按照方法二. 按需引入组件样式，引入组件；
build:site css展示正常，
build时 template 中 van-* 组件未打包，手动导入组件，组件打包正常、css未自动导入，需手动导入。
查看源码：build:site支持 vite 自定义配置，commands/build.ts 未使用 vite ，也不支持自定义配置。
    const config = await mergeCustomViteConfig(
      getViteConfigForSiteDev(),
      'development'
    );

### 你期望的 API 是什么样子的？

期望 vant-cli 构建基于vant的项目(按照方法二. 按需引入组件样式)时 ，支持 template van-*， 及 手动引入组件是自动导入样式。

**Comment by chenjiahan** [comment]
首先，文档里的按需引入方式是针对「应用类型」项目的，如果基于 Vant / VantCli 来二次封装组件库，其实没法依赖 unplugin-vue-components。

之所以不能依赖 unplugin-vue-components，是因为 Vant Cli 的构建流程并非只用到了 vite，大部分模块是直接走 babel 等 compiler 编译的，没经过 vite 处理，所以 vite 插件是没法正确生效的。

建议二次封装组件库时，手动引入 Vant 的组件和样式就好，不要依赖其他方式。

**Comment by quliangen** [comment]
🤝 感谢大佬，目前是手动引入的。
