### ISSUE TITLE
在ios 或者safari 中 由于defer的执行时机问题，导致tabs 底部选中条展示不准确 

### ISSUE THREAD

**Issue by yixinagqingyuan** [youzan/vant#11658]
### 重现链接

https://gitee.com/yangyongsheng/test-vant-tabs/tree/master/

### Vant 版本

v2.12.53

### 描述一下你遇到的问题。

在ios 或者safari 中 由于defer的执行时机问题，导致tabs 底部选中条展示不准确 ，有时候，会居中，有时候会居中，经过反复复现是苹果的兼容问题(以上仓库代码，必须要放到服务器才能复现，本地服务由于传输问题，无法复现)
![image](https://user-images.githubusercontent.com/31228587/223909151-ce9deb81-c385-43d9-90c7-5805b469e2bd.png)

### 重现步骤

直接刷新页面，即可复现

### 设备/浏览器

ios所有设备

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/224545269-8c47f871-189c-4d15-a48d-cfac9e3fe40a.png)
