### ISSUE TITLE
[Bug Report] 按需引入组件样式

### ISSUE THREAD

**Issue by qqlcx5** [youzan/vant#11668]
### 重现链接

https://github.com/qqlcx5/vue-neo-template

### Vant 版本

4.1.4

### 描述一下你遇到的问题。

我初始化一个vue3项目，但是根据你提供https://vant-ui.github.io/vant/#/zh-CN/quickstart#fang-fa-er.-an-xu-yin-ru-zu-jian-yang-shi 使用后各种报错，也根据其他issue 添加了这extensions，所以是你们技术能力有问题还是unplugin-vue-components/resolvers 仓库对你不友好，我使用ElementPlusResolver 就不会出现这个问题。
```
 resolve: {
        alias: {
            '@': fileURLToPath(new URL('./src', import.meta.url))
        },
        extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json', '.vue']
    },
```

### 重现步骤

npm run dev

**Comment by chenjiahan** [comment]
试了下没问题，有没有可能是你的技术能力不行？

![image](https://user-images.githubusercontent.com/7237365/224864825-78351ca6-fb44-4704-82e6-ff4dc9209cbc.png)

**Comment by qqlcx5** [comment]
我去查看一下源码，安装vant时出现异常，导致里面目录有问题，还有就是我在package.json删除vant，so @chenjiahan

**Comment by chenjiahan** [comment]
异常指的是啥？ 在使用上还有问题吗
