### ISSUE TITLE
Radio组件第一次勾选视图不更新

### ISSUE THREAD

**Issue by zhangpengyushibaba** [youzan/vant#11660]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/radio

### Vant 版本

3.3.2

### 描述一下你遇到的问题。

使用Radio组件第一次点击视图未更新(实际应该已经选中了，加了缓存测试，退回上级页面再回来会默认选中之前点击选择的数据)，并且在只在某些特殊机型出现（出现的手机型号：iphone13 ios 16.3.1，试了机型一样系统不一样、机型不一样的手机均未出现）

### 重现步骤

使用Radio组件第一次点击视图未更新(实际应该已经选中了，加了缓存测试，退回上级页面再回来会默认选中之前点击选择的数据)。或第一次进页面点击a选项无反应，在点击b选项会迅速选中的a选项然后在取消勾选a选项再选中b选项。

### 设备/浏览器

phone13 ios16.3.1

**Comment by chenjiahan** [comment]
从你的描述看，不是 Vant 组件逻辑的问题哈。应该是特殊机型/系统本身的 bug，属于个例。

组件层面没法提供兼容方案，建议升级系统版本试试

**Comment by dunhuang** [comment]
一样问题，分析了很久，发现直接原因是ios16设置background背景色和border-radius可能渲染时不兼容。van-radio,van-checkbox给了border-radius:100%，导致背景色渲染出不来。
解决方案：用背景图片或van-icon字体替换van-radio的背景
