### ISSUE TITLE
[Bug Report] 日历区间选择组件起止日期选择同一天点击确认后返回两个不关联的日期对象

### ISSUE THREAD

**Issue by zhoufenfens** [youzan/vant#11678]
### 重现链接

https://stackblitz.com/edit/vitejs-vite-ptkjpn?file=src/App.vue

### Vant 版本

4.1

### 描述一下你遇到的问题。

您好，我不太确认这应不应该算作一个bug，但是它确实会带来一些困扰。
当日期起止日期选择同一天的，confirm函数返回了一个开始和结束日期对象是同一个， 当对日期对象进行一些格式化处理时，比如设置具体的时分秒，导致开始日期和结束日期完全一致，从而拿到非预期的结果。

### 重现步骤

1. 点击按钮
2. 开始结束日期都选择当天
3. 看页面上的输出

### 设备/浏览器

所有浏览器

**Comment by chenjiahan** [comment]
这个不属于 bug 哈，因为确实只选中了一天，返回两个 Date 不同对象并不是很有必要。

如果想隔离一下两个 Date 对象，可以使用  `new Date(date)` 来重新生成一个。
