### ISSUE TITLE
[Bug Report] 官方文档中ios微信浏览器 Field密码框设置password会影响到上一个数字输入框

### ISSUE THREAD

**Issue by renhuan** [youzan/vant#11677]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/field

### Vant 版本

4.1.0

### 描述一下你遇到的问题。

![f885cec3aaaa5f72d4c80c79c3d2230](https://user-images.githubusercontent.com/15374282/225565916-31b8ad60-1155-4ba8-b050-9a93ea7f6e09.jpg)
![e41480f7d20fbb610ccd9cedbd3ec7c](https://user-images.githubusercontent.com/15374282/225565943-660121f8-fed1-4d3f-9cb1-c2e2e0587023.jpg)

### 重现步骤

用ios微信浏览器 打开官方文档 [https://vant-contrib.gitee.io/vant/#/zh-CN/field](url)，查看数字和密码输入法

### 设备/浏览器

ios 15.7.1  ios 15.2

**Comment by renhuan** [comment]
ios只会影响上个输入框，android没有问题

**Comment by renhuan** [comment]
我发现原生的input 也有这种情况，现在解决办法是`  <van-field style="padding: 0;height: 0;line-height: 0"/>` 加个空的给它玩o(*￣︶￣*)o

**Comment by renhuan** [comment]
```
      <van-field
          v-model="obj.realName"
          required
          label="姓名"
          placeholder="请输入姓名"/>

      <van-field style="padding: 0;height: 0;line-height: 0"/>

      <van-field
          v-model="obj.password"
          required
          label="密码"
          type="password"
          placeholder="请输入至少8位数密码"/>
```
这样“密码框“就不会影响到“姓名“输入了

**Comment by Ohmygodd** [comment]
> ```
>       <van-field
>           v-model="obj.realName"
>           required
>           label="姓名"
>           placeholder="请输入姓名"/>
> 
>       <van-field style="padding: 0;height: 0;line-height: 0"/>
> 
>       <van-field
>           v-model="obj.password"
>           required
>           label="密码"
>           type="password"
>           placeholder="请输入至少8位数密码"/>
> ```
> 
> 这样“密码框“就不会影响到“姓名“输入了

6

**Comment by chenjiahan** [comment]
我感觉这属于 iOS 系统的一个 Feature 吧，确实原生 input 也是这样的，目前看没必要在组件内部做特殊处理
