### ISSUE TITLE
[Bug Report] van-sticky+van-tabs，tab数量过多或者长度过长，IOS滚动回弹时，van-tabs消失

### ISSUE THREAD

**Issue by 769184896** [youzan/vant#11672]
### 重现链接

https://github.com/769184896/demo

### Vant 版本

4.0.11

### 描述一下你遇到的问题。

代码如下：
`<van-sticky>
    <van-tabs v-model:active="active">
      <van-tab v-for="item in 30" :key="item" :title="`title${item}`"></van-tab>
    </van-tabs>
  </van-sticky>`

场景描述：
tabs吸顶，tab渲染个数达到一定的时候，将tabs滚动到后面，iOS滚动到底部，触发滚动回弹，tabs消失

效果演示：
https://user-images.githubusercontent.com/28753653/224732652-0e4c5202-b3bd-4de8-a638-649baefea38e.mp4

### 重现步骤

1. van-sticky+van-tabs
2. 当tab数量达到一定的时候（我渲染的是30个）
3. 将tabs滚动到后面
4. 在iOS中触发滚动回弹
5. tabs消失

### 设备/浏览器
iOS11、iOS12

**Comment by wjw-gavin** [comment]
参考：https://github.com/youzan/vant/issues/10550
