### ISSUE TITLE
[Bug Report] van-field组件is-link配合label-align="top"样式错误

### ISSUE THREAD

**Issue by wangming-0215** [youzan/vant#11675]
### 重现链接

https://codesandbox.io/s/condescending-pine-e8nuq1?file=/src/App.vue

### Vant 版本

4.1.0

### 描述一下你遇到的问题。

van-field组件is-link配合label-align="top"样式错误。期望是input输入框和箭头在一行上，现在是label，input，箭头分成了三行。
![image](https://user-images.githubusercontent.com/21071580/225186682-256860cd-9ce3-4281-84fe-5bcaebeac976.png)

目前是将`van-cell__value van-field__value`类中的 `flex: none`改为`flex: 1`，暂时达到预期。
![image](https://user-images.githubusercontent.com/21071580/225187202-572ee2e6-019c-469b-a35b-038d2d963b0b.png)

### 重现步骤

1. 使用van-field组件
2. 添加`is-link` prop
3. 添加`label-align="top"`

### 设备/浏览器

chrome 111

**Comment by Yuiai01** [comment]
貌似是类多加了一个横杠，我来改下~

**Comment by Yuiai01** [comment]
我发现问题了，我来提个 pr ~
