### ISSUE TITLE
我也是同样的现象，capture和accept都加了也调起不了摄像头，场景是在android的WebView里面。

### ISSUE THREAD

**Issue by Ssmalllucky** [youzan/vant#11673]
<vant-uploader
          v-model="picList"
          :max-count="1"
          :after-read="afterRead"
          :before-delete="deleteImage"
          upload-text="活动启动拍照"
          capture="camera"
          accept="image/*"
        /> 我这样写有什么问题吗？安卓上打开不了相机，小米10 华为手机

_Originally posted by @1601463525 in https://github.com/youzan/vant/issues/3622#issuecomment-1279140228_

**Comment by chenjiahan** [comment]
请按照 issue 模板反馈，谢谢
