### ISSUE TITLE
[Bug Report] popover非受控模式下，自定义内容无法手动关闭

### ISSUE THREAD

**Issue by duowb** [youzan/vant#11686]
### 重现链接

https://stackblitz.com/edit/vue-xniwfq?file=src/App.vue

### Vant 版本

4.1.1

### 描述一下你遇到的问题。

popover非受控模式下，点击自定义内容，无法关闭

### 重现步骤

点击‘自定义内容之非受控模式2’,点击弹出框内容，无法关闭popover

**Comment by Yuiai01** [comment]
应该是使用 `v-model:show`，而不是 `:show`，我换了一下就好使了，可见 https://stackblitz.com/edit/vue-jq84ar?file=src/App.vue

**Comment by duowb** [comment]
我描述不详细哈，**我想要点击按钮手动控制popover的显隐**。使用了`:show`。
点击按钮，手动设置为`true`，但是不会显示，再次点击，才会出现
[https://stackblitz.com/edit/vue-d6xodn?file=src/App.vue](https://stackblitz.com/edit/vue-d6xodn?file=src/App.vue)

**Comment by duowb** [comment]
已解决，可以通过
```
 v-model:show 和  trigger='manual'
```
来手动控制显影

[https://stackblitz.com/edit/vue-d6xodn?file=src/App.vue](https://stackblitz.com/edit/vue-d6xodn?file=src/App.vue)
