### ISSUE TITLE
[Bug Report] vantcli最新版6.1 中使用unplugin-vue-components引入vant组件失败，无法基于vantui进行二次组件封装

### ISSUE THREAD

**Issue by Aresnine** [youzan/vant#11685]
### 重现链接

runtime-core.esm-bundler.js:40 [Vue warn]:Failed to resolve component: van-button If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

### Vant 版本

4.1

### 描述一下你遇到的问题。

runtime-core.esm-bundler.js:40 [Vue warn]:Failed to resolve component: van-button If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

### 重现步骤

根据官方文档搭建vantcli项目，再根据vant自动引入，运行则出现对应问题

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
麻烦提供一个可以复现问题的 demo 仓库呢
