### ISSUE TITLE
关于pnpm运行vant/cli2.x版本webpage依赖报错问题

### ISSUE THREAD

**Issue by wanshneyin** [youzan/vant#11688]
### Discussed in https://github.com/youzan/vant/discussions/11687

<div type='discussions-op-text'>

<sup>Originally posted by **wanshneyin** March 20, 2023</sup>
pnpm版本：7.30.0

背景：monorepo+pnpm

问题描述：pnpm dev vant/cli2.x项目时会报找不到webpack运行依赖，重新pnpm install还是会报相同错误。但是换成npm install后再dev是没问题的，求大佬们帮帮孩子！感谢大佬们！

报错： ERROR  Failed to compile with 1 errors                                                                                  18:41:09

This dependency was not found:

* /Users/sq/Desktop/drawer/private/project/test1/node_modules/.pnpm/registry.npmmirror.com+webpack-dev-server@3.11.0_2ab46yiyhoea7iz2mzk66zi75q/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8089 in multi ./node_modules/.pnpm/registry.npmmirror.com+webpack-dev-server@3.11.0_2ab46yiyhoea7iz2mzk66zi75q/node_modules/webpack-dev-server/client?http://0.0.0.0:8089 ./node_modules/.pnpm/registry.npmmirror.com+@vant+cli@2.11.11_vi5yn5abfzxjtact6sfj563kfa/node_modules/@vant/cli/site/desktop/main.js

To install it, you can run: npm install --save /Users/sq/Desktop/drawer/private/project/test1/node_modules/.pnpm/registry.npmmirror.com+webpack-dev-server@3.11.0_2ab46yiyhoea7iz2mzk66zi75q/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8089
</div>

**Comment by chenjiahan** [comment]
vant/cli 2.x 不支持 pnpm 呢，最新版是支持的

**Comment by wanshneyin** [comment]
您好，请问下是因为vant/cli2.x改了webpack的包里面的东西吗，pnpm是不支持引用修改了的包的嘛。

**Comment by Jean-Jacques-Nuoan** [comment]
我也遇到了，这个问题还能解决吗
