### ISSUE TITLE
[Bug Report] TreeSelect组件在数据量大时会出现明显卡顿

### ISSUE THREAD

**Issue by kongde7** [youzan/vant#11696]
### 重现链接

https://github.com/kongde7/vant0323/blob/master/src/components/Test.vue

### Vant 版本

4.0.10

### 描述一下你遇到的问题。

TreeSelect组件在数据量大时会出现明显卡顿：
1、页面加载卡顿，如果用路由跳转至此页面时，会出现3秒左右的卡死；
2、Tab页签切换卡顿，比如点击【全部】和【汽水饮料】，均会有2秒左右的卡顿。
![image](https://user-images.githubusercontent.com/62908419/227125749-32b21090-5761-4c21-83bf-53d75e3df1b1.png)

### 重现步骤

已将复现代码上传至Github，链接见上方。
![image](https://user-images.githubusercontent.com/62908419/227126946-5b180fdc-92a7-457a-a51b-5598e347cc1c.png)

**Comment by chenjiahan** [comment]
TreeSelect 组件目前是没有实现类似虚拟滚动的功能的，所以在大数据量时确实可能存在性能问题。

我们目前不计划为 TreeSelect 提供虚拟滚动，所以你的场景可能需要使用社区中的其他组件，或者基于 Vant 的 TreeSelect 封装一个符合你们需求的组件。
