### ISSUE TITLE
[Bug Report] 使用vant Cli 封装的vant组件，使用unplugin-vue-components按需引入不到样式

### ISSUE THREAD

**Issue by sukebin** [youzan/vant#11692]
### 重现链接

无

### Vant Cli 版本

5.1.0

### 描述一下你遇到的问题。

使用vant Cli 开发组件库会使用到vant组件，项目使用unplugin-vue-components按需引入样式，但是会出现vant组件丢失样式，应该是unplugin-vue-components工具找不到在封装后的vant组件导致的。
请小伙伴遇到了相同的问题，有没有解决的办法。

### 重现步骤

使用vant Cli 封装的vant组件，使用unplugin-vue-components按需引入不到样式

**Comment by wChenonly** [comment]
如果是函数式的组件，如toast 或Dialog，会有这个问题
这种的自己手动引入下
import 'vant/es/toast/style'
import 'vant/es/Dialog/style'

**Comment by Joyboo** [comment]
希望尽早修复，已降级使用3.6版本

**Comment by chenjiahan** [comment]
这个不算是 bug，因为 unplugin-vue-components 是基于 template 里的组件来自动引入样式的，目前无法根据 showToast 等方法来引入对应的样式，Vant v4 的文档里有相关说明，手动引入一下相关样式就可以的。

![image](https://user-images.githubusercontent.com/7237365/229289892-afe457c7-387f-4638-8b32-c2da1e78af6d.png)

**Comment by yoyo837** [comment]
> 这个不算是 bug，因为 unplugin-vue-components 是基于 template 里的组件来自动引入样式的，目前无法根据 showToast 等方法来引入对应的样式，Vant v4 的文档里有相关说明，手动引入一下相关样式就可以的。
> 
> ![image](https://user-images.githubusercontent.com/7237365/229289892-afe457c7-387f-4638-8b32-c2da1e78af6d.png)

没找到这个问题，文档仓库是哪个？官网无法搜索关键字，只能去仓库找找了
