### ISSUE TITLE
[Bug Report] vant4的Cascader 级联选择，快速点击选项的时候，会导致数据错乱

### ISSUE THREAD

**Issue by xiaofei3062** [youzan/vant#11695]
### 重现链接

暂无

### Vant 版本

4.1.1

### 描述一下你遇到的问题。

vant4的Cascader 级联选择，快速点击选项的时候，会导致数据错乱

### 重现步骤

vant4的Cascader 级联选择，快速点击选项的时候，会导致数据错乱

**Comment by xiaofei3062** [comment]
来回反复的快速点击，切换的tab内容，会左右摇摆

**Comment by chenjiahan** [comment]
能否录个屏看看？

**Comment by xiaofei3062** [comment]
https://user-images.githubusercontent.com/51069900/228706350-34bbfe0c-2f7f-4293-8e9c-50ef5bcca92a.mp4

**Comment by xiaofei3062** [comment]
> 能否录个屏看看？

已录屏看上面的评论

**Comment by chenjiahan** [comment]
我在 Vant 官网的示例中没能复现这个问题，可能和你的业务代码逻辑有关，建议先自行排查下，或者提供一个可以复现该问题的 codesandbox 复现链接

**Comment by xiaofei3062** [comment]
> 我在 Vant 官网的示例中没能复现这个问题，可能和你的业务代码逻辑有关，建议先自行排查下，或者提供一个可以复现该问题的 codesandbox 复现链接

你在异步操作的时候，快速点击即可复现
