### ISSUE TITLE
[Feature Request] 增加弹幕，签名和水印组件

### ISSUE THREAD

**Issue by yanbowe** [youzan/vant#11697]
### 这个功能解决了什么问题？

1.弹幕组件：有些场景需要弹幕形式展示滚动文案
2.签名组件：在h5中签合同或者一些文件之类的，需要签名。
3.水印组件：需要在某个区域或者全屏下展示登录人的名称作为标识

### 你期望的 API 是什么样子的？

Barrage [弹幕](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/barrage)
Signature [签名](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/signature)
Watermark[水印](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/watermark)

**Comment by HuberTRoy** [comment]
占坑试试watermark~(ˊ•͈ ꇴ •͈ˋ)。
