### ISSUE TITLE
[Feature Request] 滚动列表多列、虚化

### ISSUE THREAD

**Issue by wf-soft** [youzan/vant#11691]
### 这个功能解决了什么问题？

无限加载图像列表，应该有许多的项目都需要用到这样的列表，而移动端主流UI框架几乎没有一个这样的可用组件，作为现代移动端UI有很多场景下使用翻页非常影响使用体验

### 你期望的 API 是什么样子的？

无限滚动、虚化、多列、懒加载

**Comment by chenjiahan** [comment]
目前 Vant 没有计划提供类似的能力，可以到社区中找一下，应该有一些独立的 Vue 库能够实现虚拟列表。
