### ISSUE TITLE
[Bug Report] action bar placeholder属性在特定情况下不生效

### ISSUE THREAD

**Issue by AnLiBoBo** [youzan/vant#11704]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-o2gbcv

### Vant 版本

4.1.1

### 描述一下你遇到的问题。

usePlaceholder会获取传入的dom高度,然后用div包住传入的dom,最后返回一个渲染函数
但是当dom高度有变化的时候,最外层的包住的div高度还是最开始的值,也没有跟着变化

### 重现步骤

1. 创建两个 action bar
2. 初始时显示action bar1
3. 切换到显示action bar2
4. 此时action bar2的placeholder是不生效的

**Comment by wjw-gavin** [comment]
Replace `v-show`  with  `v-if` can solve your problem temporarily.

**Comment by AnLiBoBo** [comment]
> Replace `v-show` with `v-if` can solve your problem temporarily.

用v-if后是可以解决,但是我觉得这个问题可能还是在usePlaceholder没有去做size的变动监听

**Comment by wjw-gavin** [comment]
> > Replace `v-show` with `v-if` can solve your problem temporarily.
> 
> 用v-if后是可以解决,但是我觉得这个问题可能还是在usePlaceholder没有去做size的变动监听
嗯嗯，我意思是可以先暂时这么解决，我们后续修复😂，平常会比较忙。

**Comment by wjw-gavin** [comment]
嗯嗯，我意思是可以先暂时这么解决，我们后续修复😂，平常会比较忙。

**Comment by chenjiahan** [comment]
虽然我们可以通过 IntersectionObserver 来监听相应的变化，但 IntersectionObserver 本身是存在兼容性问题的，在低版本系统下仍然会存在问题。

所以使用 `v-if` 来解决会更加合适一些，在不同机型上的表现更一致。
