### ISSUE TITLE
[Bug Report] 异步校验规则

### ISSUE THREAD

**Issue by FE-tree** [youzan/vant#11700]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/form#xiao-yan-gui-ze

### Vant 版本

2.12.22

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/24875382/227455506-e29d5810-dc76-4473-847d-6ea54e4cbd10.png)

### 重现步骤

demo里面校验好像出错了，我自己在使用接口做异步调用时，就算直接resolve(false)输入框也没红

**Comment by wjw-gavin** [comment]
![image](https://user-images.githubusercontent.com/19986739/227496860-a4f642eb-fec5-4b05-9ff4-f09b21a6f597.png)
