### ISSUE TITLE
[Feature Request] vant4支持安卓最低多少版本？

### ISSUE THREAD

**Issue by Grrrr-sc** [youzan/vant#11706]
### 这个功能解决了什么问题？

vant4在低版本Android里无法显示，白屏
![Screenshot_20230315-113935](https://user-images.githubusercontent.com/1262247/227723045-d5a9d019-a980-4209-b061-09c8850bffc1.png)

### 你期望的 API 是什么样子的？

希望能支持低版本Android和iOS，尤其是国产Android系统😭

**Comment by chenjiahan** [comment]
README 里有写

<img width="615" alt="Screen Shot 2023-03-26 at 11 30 56" src="https://user-images.githubusercontent.com/7237365/227753706-9472598b-ce08-4492-8797-e9b8775023d4.png">


https://github.com/youzan/vant/blob/main/README.zh-CN.md#%E6%B5%8F%E8%A7%88%E5%99%A8%E6%94%AF%E6%8C%81
