### ISSUE TITLE
van-tab title slot 绑定数据更新异常

### ISSUE THREAD

**Issue by ansonhorse** [youzan/vant#1170]
**What is the current behavior?**
RT

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**
```vue
<template>
  <van-tabs>
    <van-tab :key="index" v-for="(tab, index) in tabs">
      <template slot="title">
        {{ tab.title}} {{ tab.num }}
      </template>
    </van-tab>
  </van-tabs>
</template>

<script>
  export default {
    components: {},
    data() {
      return {
        tabs: [
          {
            title: 'tab 1---',
            num: 0,
          },
          {
            title: 'tab 2---',
            num: 1,
          }
        ]
      }
    },
    mounted() {
      setTimeout(() => {
        this.tabs[0].num = 5
      }, 2000)
    }
  }
</script>
```

**What is the expected behavior?**
2秒后，视图更新。但实际上并没有，如果再更新一次`this.tabs[0].num = 6`，这时候视图会更新，但数字是`5`，而不是`6`，如果一直这样更新`num`为一个跟上次不一样的值，视图显示就是上一次的值。

另外，如果如果是如下这样的更新：
```
this.tabs[0].num = 6 // 视图数字更新为5
this.tabs[0].num = 6 // 视图数字仍是5
// ...省略N个相同的赋值，结果同楼上，视图数字停留在5
```

~~更新：~~
~~使用Vue Devtools查看，van-tab的title是`undefined`，问题大概挺明了了~~

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
Vue: v2.5.16 
Vant: 1.1.3

**Comment by ansonhorse** [comment]
如果使用`:title="tab.title + ' ' + tab.num"`这种方式，是正常的

**Comment by chenjiahan** [comment]
目前 title slot 的实现方式有问题，下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.1.6 版本修复

**Comment by try6** [comment]
我是2.2.6版本，依然有这个问题？
