### ISSUE TITLE
[Bug Report]Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant#11711]
### 重现链接

https://github.com/youzan/vant/issues/11574

### Vant 版本

2.12.53

### 描述一下你遇到的问题。

在执行 vue-cli-service serve --mode test 时才会出现这个问题。但是执行 vue-cli-service serve --mode production 或者 vue-cli-service serve 时不会有问题

![image](https://user-images.githubusercontent.com/23445650/227968341-2f5c15f2-b6c6-4085-9057-e7f5147e829c.png)

- 

### 重现步骤

运行模式不一样不是`production`或者 `development`时，运行控制台会报错，例如使用如下配置

`.env.test`

```
# 开发环境配置
ENV='test'

#baseUrl
VUE_APP_BASE_API='/prod-api'
```

在执行 `vue-cli-service serve --mode test` 时浏览器就会报错

### 设备/浏览器

chrome 版本 111.0.5563.64（正式版本） (x86_64)

**Comment by Gitsifu** [comment]
bug复现最小案例仓库：https://github.com/Gitsifu/vant-bug-11711
运行 `vue-cli-service serve --mode test` 报错如下：
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/23445650/228103856-749d4052-9461-4b73-a7e1-93504776c01c.png">

**Comment by Gitsifu** [comment]
问题已解决：

不要使用 `vue-cli-service serve --mode test` ，将`test`模式改为其他的模式，例如：

`.env.staging`
```
NODE_ENV='staging'

#baseUrl
VUE_APP_BASE_API='/prod-api'
```

`package.json`

```
{
     ...
      "scripts": {
            "serve": "vue-cli-service serve",
            "serve:staging": "vue-cli-service serve --mode staging",
            ...
       },
       ...
}
```

运行 `npm run serve:staging` 将不会报错

**Comment by wangxiaoze-view** [comment]
这个"exports"问题我最近也是在"vant": "^3.6.2"版本发现的；只有"vue-cli-service serve --mode test"会有这样的情况，其他的不会有；
目前也是将"--model test"换成了其他的；
