### ISSUE TITLE
[Bug Report] nuxt3中使用tabbar组件，打包后与生产环境效果不一致

### ISSUE THREAD

**Issue by huihuilovekuikui** [youzan/vant#11719]
### 重现链接

无

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/66559869/228721513-bacd271d-fff9-457c-82a5-3375b72c9f77.png)
开发环境显示正常
![image](https://user-images.githubusercontent.com/66559869/228721781-ca2bc20c-b96c-4f11-bf5b-a5816a0eb4b8.png)
build之后样式被覆盖

### 重现步骤

nuxt版本3.3.2

**Comment by chenjiahan** [comment]
麻烦提供下复现问题的 codesandbox 链接

**Comment by Jarvis2018** [comment]
我也遇到这个问题了，请问怎么解决的呢
