### ISSUE TITLE
vite4 + vant4.1.2 van-cell 展示位置不对

### ISSUE THREAD

**Issue by sm0210** [youzan/vant#11716]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/popup

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

按照官网使用vant4 van-cell ，结果显示的文字位置不对
**官网：**

![image](https://user-images.githubusercontent.com/10410886/228472858-140e3101-6a65-41d7-9905-217a612f1ad4.png)

**本地使用：**
````html
<van-cell is-link @click="showPopup">展示弹出层</van-cell>
````
**本地效果：**
![image](https://user-images.githubusercontent.com/10410886/228476055-d9a8db9c-8daa-4398-9927-19e398f39688.png)

使用的 import 'vant/lib/index.css'; 全局方式引入的，可以看到官网文本引入的是“van-cell__title”样式， 本地引入的是“van-cell__value ”样式，文本（“展示弹出层”）的位置插槽写在value位置上 这是什么情况？

### 设备/浏览器

Chrome 111.0.5563.64（正式版本） (x86_64)

**Comment by wh-if** [comment]
看这个`https://vant-contrib.gitee.io/vant/#/zh-CN/cell#dai-ma-yan-shi`

**Comment by wh-if** [comment]
![image](https://user-images.githubusercontent.com/59309934/228483381-5a013dde-9189-4010-a5e7-e37d3cb0d030.png)
它是文档忘改了
