### ISSUE TITLE
[Bug Report] number-keyboard blur事件没有触发

### ISSUE THREAD

**Issue by kkkisme** [youzan/vant#11714]
### 重现链接

https://stackblitz.com/edit/vue-wnosiy?file=src%2FApp.vue,src%2Fcomponents%2Ffield-number.vue

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

在来回切换输入框时，虚拟键盘无法收起

### 重现步骤

1、打开重现链接，点击[open in new tab], 设置成手机预览模式
2、来回点击两个输入框，发现虚拟键盘无法收起

**Comment by wjw-gavin** [comment]
没明白你说的无法收起：

1. 展开并来回切换后都无法收起？
2. 来回切换无法收起上一个展示的？

如果是情况1，我这没复现...
https://user-images.githubusercontent.com/19986739/228457806-a2276b75-fb6b-4a0e-bbc2-daa56e0d6f08.mp4

如果是情况2
删除`@touchstart.stop` 中的 .stop，这样在展开下一个时，会收起上一个。

**Comment by kkkisme** [comment]
> 没明白你说的无法收起：
> 
> 1. 展开并来回切换后都无法收起？
> 2. 来回切换无法收起上一个展示的？
> 
> 如果是情况1，我这没复现... https://user-images.githubusercontent.com/19986739/228457806-a2276b75-fb6b-4a0e-bbc2-daa56e0d6f08.mp4
> 
> 如果是情况2 删除`@touchstart.stop` 中的 .stop，这样在展开下一个时，会收起上一个。

你的视频中其实已经复现了，你的视频中虚拟键盘并没有来回切换，只是两个键盘重叠覆盖了。

---

以下是符合预期的切换：




https://user-images.githubusercontent.com/18638401/228709097-f3edf03f-2605-48ee-9152-418428385e8d.mp4

**Comment by wjw-gavin** [comment]
所以你的是我说的情况2啊...，看下我说的第二条撒...（如果是情况2 删除`@touchstart.stop` 中的 `.stop`，这样在展开下一个时，会收起上一个。）

**Comment by kkkisme** [comment]
> 所以你的是我说的情况2啊...，看下我说的第二条撒...（如果是情况2 删除`@touchstart.stop` 中的 `.stop`，这样在展开下一个时，会收起上一个。）

删除stop连第一个键盘都打不开呢

**Comment by wjw-gavin** [comment]
> > 所以你的是我说的情况2啊...，看下我说的第二条撒...（如果是情况2 删除`@touchstart.stop` 中的 `.stop`，这样在展开下一个时，会收起上一个。）
> 
> 删除stop连第一个键盘都打不开呢

确实你的复现链接是这样，我是在本地试的...
<img width="747" alt="image" src="https://user-images.githubusercontent.com/19986739/228715469-1990cad2-6b88-4d2e-875b-55bc28fb5421.png">

https://user-images.githubusercontent.com/19986739/228714402-f5565268-564d-4b59-90cd-4a9f675a4ac7.mp4

**Comment by wjw-gavin** [comment]
切换成手机模式  就不行了😂

**Comment by wjw-gavin** [comment]
> > 所以你的是我说的情况2啊...，看下我说的第二条撒...（如果是情况2 删除`@touchstart.stop` 中的 `.stop`，这样在展开下一个时，会收起上一个。）
> 
> 删除stop连第一个键盘都打不开呢

换成`click`好了，你再试试呢
 https://stackblitz.com/edit/vue-lhuuce?file=src%2FApp.vue,src%2Fcomponents%2Ffield-number.vue

**Comment by guominfang** [comment]
这里在 pc环境下，无法触发
