### ISSUE TITLE
官网 > 基础组件 > ConfigProvider 全局配置

### ISSUE THREAD

**Issue by AmalsCode** [youzan/vant#11718]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/config-provider

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

官网 > 基础组件 > ConfigProvider 全局配置 下 右侧界面展示 深色模式 > 切换深色模式 浏览器第一次进入未选中状态下默认应为浅色模式.

### 重现步骤

官网 > 基础组件 > ConfigProvider 全局配置 下 右侧界面展示 深色模式 > 切换深色模式

### 设备/浏览器

Chrome

**Comment by chenjiahan** [comment]
get，我们修复下
