### ISSUE TITLE
vant2【tabs组件在ios12和ios14pro上面出现下划线定位回滚问题】

### ISSUE THREAD

**Issue by xy0514** [youzan/vant#11710]
### 重现链接

11111111

### Vant 版本

2.12.44

### 描述一下你遇到的问题。

111111111

### 重现步骤

`

https://user-images.githubusercontent.com/48755622/227828410-6a11b719-575c-40d6-8017-d796ba1a7bd9.mp4

`

### 设备/浏览器

ios 12,ios 14pro

**Comment by wjw-gavin** [comment]
![image](https://user-images.githubusercontent.com/19986739/227917686-7c279c9c-7231-4e6f-8296-2568ec08d859.png)

**Comment by xinlei3166** [comment]
@wjw-gavin  vant4 tabs组件在  iphone14promax(ios16) 上面出现下划线定位回滚问题，使用的vw单位，postcss 8.4.21。

![IMG_4764](https://user-images.githubusercontent.com/22881872/229664769-b0e0d7aa-4374-49d5-9e39-caea1705738f.jpg)

**Comment by wjw-gavin** [comment]
> @wjw-gavin vant4 tabs组件在 iphone14promax(ios16) 上面出现下划线定位回滚问题，使用的vw单位，postcss 8.4.21。
> 
> ![IMG_4764](https://user-images.githubusercontent.com/22881872/229664769-b0e0d7aa-4374-49d5-9e39-caea1705738f.jpg)

能提供个复现链接或者代码仓库吗？

**Comment by xinlei3166** [comment]
@wjw-gavin 你好，代码仓库地址：https://github.com/xinlei3166/vant-issue

**Comment by wjw-gavin** [comment]
经过试验，我发现如果滑动过快时，确实会出现问题

https://user-images.githubusercontent.com/19986739/229741588-32cffa51-19a1-46f9-9e95-741e5c1d98b7.mp4 


经过调试滑动过快时：https://github.com/youzan/vant/blob/1927c7462b2563c78dd28dc5349c317185d3e4df/packages/vant/src/tabs/utils.ts#L14
这个计算会不准确，如果 frames 固定为 1 时位置正确，但是体验差；

同样https://github.com/youzan/vant/blob/1927c7462b2563c78dd28dc5349c317185d3e4df/packages/vant/src/tabs/Tabs.tsx#L477
这里滚动增加个 throttle 300 也能正常渲染，但是滚动动画看起来还是会有点怪...

**Comment by FiShelly** [comment]
似乎并没有解决，我在4.6.8的版本依然存在这个问题。

**Comment by inottn** [comment]
> FiShelly

可以提供一个复现链接
