### ISSUE TITLE
max-range无法使用？

### ISSUE THREAD

**Issue by xuyhtuuio** [youzan/vant#11729]
### 重现链接

 <van-calendar v-model:show="show" type="range" @confirm="onConfirm" ref="calendar"
                          :max-range="31"
            />

### Vant Weapp 版本

4.1.1

### 描述一下你遇到的问题。

弹窗无法显示

### 重现步骤

1.点击日历
2.设置最大选择范围
3.没有提示

### 设备/浏览器

谷歌

**Comment by wjw-gavin** [comment]
[我这里试的可以呢](https://codesandbox.io/s/vant-4-issue-template-forked-dk3xjk?file=/src/App.vue)
