### ISSUE TITLE
rate 评分组件

### ISSUE THREAD

**Issue by louie-liang** [youzan/vant#1172]
Rate评分组件的问题：经常会报错  
**[Vue warn]: Invalid prop: type check failed for prop "value". Expected Number, got String.**
传过来的数据的string型 ， 我在mouted 里面转换类型后还会报这个错误
html
`<van-rate v-model="list.res.quality_rating" />`
js 
`let quality_rating = parseInt(this.list.res.quality_rating);`

**Comment by ansonhorse** [comment]
感觉应该在`created`里转换

**Comment by chenjiahan** [comment]
请确保传入的类型正确

**Comment by louie-liang** [comment]
@ansonhorse  放created 里面也一样

**Comment by louie-liang** [comment]
@chenjiahan 觉得吧那个验证的去掉就可以了  希望能修正下。传过来的数据是string   我已经转成number了 还会报错

**Comment by chenjiahan** [comment]
1. 验证是不能去掉的。
2. 在第一次传入时就需要保证是正确的类型
