### ISSUE TITLE
[Feature Request] Field type="textarea"监听readonly变化时可以重新计算input高度

### ISSUE THREAD

**Issue by lyanerzhang** [youzan/vant#11723]
### 这个功能解决了什么问题？

比如：
可编辑态时，指定rows=5，并且支持autosize
希望只读态时，可以根据绑定value字数自适应高度

### 你期望的 API 是什么样子的？

无需新增api

**Comment by chenjiahan** [comment]
目前最新版是支持 readonly 自适应高度的，我试了下没问题
