### ISSUE TITLE
[Bug Report] `van-list` 上拉加载更多后 如何回到之前的位置

### ISSUE THREAD

**Issue by evanlong0926** [youzan/vant#11724]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-vi7w02?file=/src/main.js&resolutionWidth=320&resolutionHeight=675

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

回不到之前进入的位置

### 重现步骤

1. 上拉加载更多后，看到30的数字列表项
2. 点击30进入新的页面
3. 再点击返回

### 设备/浏览器

Chrome 111.0.5563.147（正式版本）（64 位）

**Comment by chenjiahan** [comment]
你可以使用 Vue 提供的 KeepAlive 来缓存组件状态

**Comment by evanlong0926** [comment]
> 你可以使用 Vue 提供的 KeepAlive 来缓存组件状态

我使用了KeepAlive，还是不对

tip：更新在最小示例的 `Home.vue` 文件中

**Comment by chenjiahan** [comment]
组件不会记录滚动条的位置呢，你可以自行控制

**Comment by evanlong0926** [comment]
ok.
