### ISSUE TITLE
Uploader 文件上传图片后被压缩了

### ISSUE THREAD

**Issue by yypswfwq123** [youzan/vant#11720]
### 重现链接

:before-read和:after-read文件size变小了

### Vant 版本

4.1.1

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/129355345/228723748-f33d3f75-3d42-4b62-ad06-261c21d9faff.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/129355345/228723972-3d7533a5-2993-4a9a-832d-a2c87760b812.png)

**Comment by chenjiahan** [comment]
Uploader 组件不会对图片进行压缩处理呢

唯一的操作是使用 FileReader.readAsDataURL 来转化图片为 base64 string，如果有疑问可以直接看组件的源代码：https://github.com/youzan/vant/tree/main/packages/vant/src/uploader
