### ISSUE TITLE
[Bug Report] 安卓上传长图（高度很高的长图）时，上传无反应

### ISSUE THREAD

**Issue by zhaohmail** [youzan/vant#11722]
### 重现链接

暂无

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

安卓上传长图（高度很高的长图）时，上传无反应，且页面其他位置无法点击

### 重现步骤

安卓上传长图（高度很高的长图）时，上传无反应

### 设备/浏览器

安卓

**Comment by chenjiahan** [comment]
参考 https://github.com/youzan/vant/issues/9375
