### ISSUE TITLE
vant tab active 绑定无效

### ISSUE THREAD

**Issue by lmbelievein** [youzan/vant#1173]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
升级到最新版再试
