### ISSUE TITLE
Nuxt3使用Vant4 打包后 在百度APP访问有概率出现500报错 其它浏览器正常

### ISSUE THREAD

**Issue by OnePsycho** [youzan/vant#11736]
### 重现链接

https://gitee.com/OnePsycho/xlmy_nuxt.git

### Vant 版本

4.0.2 

### 描述一下你遇到的问题。

项目写完了，我用 npm run build打包之后 直接用node本地运行打包后的mjs文件，就出现了这样的问题 ： 百度APP访问 会出现报500的错误  其它浏览器都正常访问。并且报错信息还有几种 和下图所示。 而且只有在百度APP这个应用访问才出现，百度极速版都没有问题，其它浏览器更没问题。 如果我把部分使用Tab组件或者Field组件代码注释掉 就不会报错。
![image](https://user-images.githubusercontent.com/43296632/230259322-882f8b77-67ec-46bd-a699-6526052e3751.png)

![image](https://user-images.githubusercontent.com/43296632/230259370-ff051ee7-bf2f-4eb9-b7fb-9afc674889a5.png)

### 重现步骤

打包后 直接运行打包文件的index.mjs 然后 用百度APP访问 192的地址

### 设备/浏览器

IOS 百度APP

**Comment by chenjiahan** [comment]
提供的链接无法访问：

![image](https://user-images.githubusercontent.com/7237365/235572559-39af1f3a-763f-4249-946a-8f6662aa999e.png)

麻烦提供一个最小复现仓库哈，并提供可访问的链接
