### ISSUE TITLE
[Bug Report] 使用van-popup的teleport挂载body失败

### ISSUE THREAD

**Issue by sukebin** [youzan/vant#11735]
### 重现链接

无

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

正常项目使用popup的teleport挂载body是成功的。但是使用vant-cli封装的组件中使用popup的teleport挂载body失败。
挂载失败的html标签有teleportr="body"
<div role="dialog" tabindex="0" class="van-popup van-popup--bottom sm-picker-popup" teleportr="body" style="z-index: 2016;"></div>

### 重现步骤

正常项目使用popup的teleport挂载body是成功的。但是使用vant-cli封装的组件中使用popup的teleport挂载body失败。

**Comment by chenjiahan** [comment]
请提供有效的复现链接
