### ISSUE TITLE
[Bug Report] vant 组件 onChange 行为/时机不正确

### ISSUE THREAD

**Issue by xinhaoxx** [youzan/vant#11731]
### 重现链接

https://codesandbox.io/embed/vant-3-issue-template-forked-pr2fjn

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

vant 组件 onChange 行为/时机不正确

预期行为：组件 onChange 事件应该是由用户主动点击或操作触发，而不是 v-model 值变更后触发
当前行为：通过其他方法将 radio-group 的值变更后，也能触发 radio-group 的onChange 事件

### 重现步骤

1. 点击按钮修改 v-model 值
2. 见 console 输出，触发了 radio-group 的 onChange

**Comment by chenjiahan** [comment]
目前 RadioGroup 的 change 事件指的是“当绑定值变化时触发的事件”，这个行为是符合预期的。

修改 change 事件的触发时机属于 breaking change，因此我们暂时不计划调整该行为。
