### ISSUE TITLE
[Bug Report] IndexBar 自定义索引列表栏不与滑动列表栏一致。

### ISSUE THREAD

**Issue by lucky0lonely** [youzan/vant#11739]
### 重现链接

https://code.juejin.cn/pen/7219220768910934053

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

滑动组件，索引栏无法同步，只能自增式高亮。

### 重现步骤

直接向下滑。

### 设备/浏览器

Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1

**Comment by wjw-gavin** [comment]
你需要设置 `indexList` 和你的数据匹配哈（比如微信联系人，首字母没有的也会不显示的）
建议从 `contact` 中遍历取出 `letter` 作为 `indexList`。

![image](https://user-images.githubusercontent.com/19986739/230585208-a26f6753-8954-424a-b806-58ded923fc98.png)
