### ISSUE TITLE
[Bug Report] vant3 DatetimePicker 选择完整时间 v-model 的值初始化错误

### ISSUE THREAD

**Issue by rpdg** [youzan/vant#11749]
### 重现链接

https://vant-contrib.gitee.io/vant/v3/#/zh-CN/datetime-picker

### Vant 版本

3.6.11

### 描述一下你遇到的问题。

官方示例中 【选择完整时间】 的sample
v-model 绑定 const currentDate = ref(new Date());
控件初始化应该是停留在当天，实际是 new Date(0)

### 重现步骤

![微信截图_20230413133404](https://raw.githubusercontent.com/rpdg/PicBed/master/TyporaPic202304131337357.png)

### 设备/浏览器

chrome v111 win64

**Comment by wjw-gavin** [comment]
感谢反馈~ 文档错误已修改

**Comment by rpdg** [comment]
哦，可能是我没解释清楚。
情况是在这个组件的初始化时，并未使用了v-model 所设的值，导致初始化后显示的是在minDate所设的最小值。
其实需要修改的是组件代码，而非文档示例，文档只是显示出了这个issue所在。

**Comment by rpdg** [comment]
谢谢回复，我创建了sandbox的链接如下：
https://codesandbox.io/p/sandbox/cool-sound-c6ru0e?file=%2Fsrc%2FApp.tsx

**Comment by rpdg** [comment]
谢谢指出，确实是我的问题
