### ISSUE TITLE
[Bug Report] field在Safari浏览器显示异常

### ISSUE THREAD

**Issue by ChengLi-forCode** [youzan/vant#11746]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-mv1plk?file=/src/App.vue

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

field在Safari浏览器显示异常   其他浏览器没问题

### 重现步骤

在Safari 浏览器打开，在field输入数字，然后点击空白页让field失去焦点 ，就能看到输入框内文字错位   点击清空也失效

### 设备/浏览器

ios 16.4.1  safari16.4

**Comment by chenjiahan** [comment]
文字错位的问题我在 codesandbox 里复现了，但是在官网示例里没法复现，推测是页面缩放导致的系统 bug，在移动端通常需要添加 viewport 配置来禁用页面缩放：

```html
<meta
  name="viewport"
  content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, viewport-fit=cover"
/>
```

而 "点击清空失效" 的问题我没能复现，建议你再试试。

**Comment by ChengLi-forCode** [comment]
viewport 配置就是按照上面的配置的   依然会出现文字错位的问题。

**Comment by chenjiahan** [comment]
Vant 官网能复现吗？截图看看

**Comment by ChengLi-forCode** [comment]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/23072342/236096236-d2583126-1607-491f-9949-2c4c9e5c9605.png">
<img width="693" alt="image" src="https://user-images.githubusercontent.com/23072342/236096312-9ce7eb14-c83b-4450-868b-a40802aa916c.png">
这样清晰吗？

**Comment by chenjiahan** [comment]
麻烦验证下 Vant 官网呢

**Comment by ChengLi-forCode** [comment]
[https://codesandbox.io/s/vant-3-issue-template-forked-s83u52?file=/src/App.vue](url)
验证官网是什么意思？ 我弄了个复现连接，viewport 配置 也添加了

**Comment by chenjiahan** [comment]
打开这个页面验证 https://vant-contrib.gitee.io/vant/mobile.html#/zh-CN/field

**Comment by ChengLi-forCode** [comment]
这个页面没有类似属性的组件 (clearable clear-trigger="focus" input-align="right")

**Comment by ChengLi-forCode** [comment]
这个官网页面没有完全一样属性的Field，我找了个类似的添加上 input-align="right"属性  在Safari浏览器打开输入文字就会错位
[https://codesandbox.io/s/vant-3-issue-template-forked-nctl57?file=/src/App.vue:72-91](url)
这是复现链接

**Comment by chenjiahan** [comment]
Safari bug 挺多的，这种情况组件库大概率也没法处理，你可以研究看看有没有什么 hack 方案

**Comment by ChengLi-forCode** [comment]
嗯嗯   好的  谢谢您！

**Comment by githubtuxedo** [comment]
@ChengLi-forCode 你好，请问显示异常是 文字类似重叠的样子吗
![image](https://github.com/youzan/vant/assets/16253849/c739e0f1-3254-483e-9a31-ed3e03cab54f)
我的版本是3.5.2，存在这样的情况，请问找到什么好的办法了吗

**Comment by xylmoon** [comment]
您好，我也是碰到了这个问题， 有什么好的解决方案吗

**Comment by xylmoon** [comment]
`.van-field__clear {
  padding-top: 0.1px;
}`

我通过修改clear图标的高度，间接的改变了input的高度就不会出现重叠

**Comment by zy017** [comment]
我也遇到这个问题了，有什么好的解决办法吗？
