### ISSUE TITLE
[Feature Request] van-tab 滑动切换动画

### ISSUE THREAD

**Issue by liudake** [youzan/vant#1174]
**van-tab 滑动切换**

**切换显示子页面可否有左右滑动动画**

**案例地址：http://elemefe.github.io/mint-ui/#/tab-container**

**Comment by chenjiahan** [comment]
后续会支持此功能

**Comment by deepkolos** [comment]
实现的时候, 注意左右swipe和垂直滚动的互斥哦, 还有tab嵌套的情况

![swipe scroll](https://user-images.githubusercontent.com/12824616/40782491-181d4af6-6512-11e8-8aa6-9df2012c6554.gif)

**Comment by liudake** [comment]
其实我自己已经用  vue的<transition>动画组件实现了。
但是有个问题：用户第一次滑动或者点击切换tab，没有任何效果，然后第二次滑动或者点击切换tab，就有滑动切换tab的动画效果了。
个人认为问题根源出在： tab组件的 <slot v-if="inited" />。
在线案例地址：https://jsfiddle.net/2fgw8pay/1/

**Comment by liudake** [comment]
其实我自己已经用  vue的<transition>动画组件实现了。
但是有个问题：用户第一次滑动或者点击切换tab，没有任何效果，然后第二次滑动或者点击切换tab，就有滑动切换tab的动画效果了。
个人认为问题根源出在： tab组件的 <slot v-if="inited" />。
在线案例地址：https://jsfiddle.net/2fgw8pay/1/

**Comment by liudake** [comment]
其实我自己已经用  vue的 `< transition >`动画组件实现了。
但是有个问题：用户第一次滑动或者点击切换tab，没有任何效果，然后第二次以后滑动或者点击切换tab，就有滑动切换tab的动画效果了。
个人认为问题根源出在： tab组件的 `<slot v-if="inited" />`。
在线案例地址：https://jsfiddle.net/2fgw8pay/1/

**Comment by SkyLightIn** [comment]
为啥我的tab嵌套了list之后list无法滑动了呀。。

**Comment by bln7** [comment]
滑动切换的体验不够好。

**Comment by ShingLi** [comment]
用vux + betterscroll 改造了一个效果还不错

**Comment by bln7** [comment]
官方有没有想过升级一下，让tab的切换更加好呢？像ant移动版的一样

**Comment by zhaoshuan** [comment]
tab组件加上滑动和动画后，体验不行，没有过渡效果，ios下，右滑直接返回退出了当前webView，希望可以优化一下，tab滑动使用场景太多了

**Comment by zhaoshuan** [comment]
tabs组件 content内容部分，每个内容块的滚动高度是一样，可否优化一下。
举个例子，标签1和标签2内容部分都有20条数据，选中标签1，内容部分往下滚动5条数据，此时切换到标签2，显示的也是滚动到的第5条数据，这是不合理的，此时的标签2应该是从头开始，从第一条数据开始显示。
不知道我表达清楚没

**Comment by chenjiahan** [comment]
@zhaoshuan 
1. 右滑退出这个问题会看下
2. 切换动画变更较大，会影响现有用户，所以暂时没动工
3. sticky 模式下，滚动位置会自动回到顶部，非 sticky 模式下，没有这个必要

**Comment by ystarlongzi** [comment]
> 举个例子，标签1和标签2内容部分都有20条数据，选中标签1，内容部分往下滚动5条数据，此时切换到标签2，显示的也是滚动到的第5条数据，这是不合理的，此时的标签2应该是从头开始，从第一条数据开始显示

@zhaoshuan 这个是由于滚动条是 window 的，而不是每一个 tab 导致的。如果希望在切换 tab 后，也能滚动到正确位置，你可以在切换之前，保存下当前窗口的滚动位置，然后再切换回来后，在滚动到这个位置即可

**Comment by ystarlongzi** [comment]
@chenjiahan 感觉 tab 组件可以暴露出一个属性，让用户决定是否自动滚到到切换前的位置。这种交互在业务开发中，也经常和产品讨论，大多数情况下，产品都更希望滚动到切换前的位置

**Comment by chenjiahan** [comment]
@ystarlongzi 这个需求大部分情况下可以用局部滚动容器来解决，组件内控制滚动条位置可行，但是不倾向于这样做

**Comment by Roly-poly-toy** [comment]
这个问题还没解决吗？

**Comment by OnlyLady** [comment]
> @ystarlongzi 这个需求大部分情况下可以用局部滚动容器来解决，组件内控制滚动条位置可行，但是不倾向于这样做

tabs目前的点击事件只是返回了固定值？个人建议是直接返回当前点击的所有数据对象。这样可以方便然后用户决定需要取什么

**Comment by zhaoshuan** [comment]
@chenjiahan  经过测试，开启动画后，左右滑动的时候，需要禁止默认行为 e.preventDefault ，否则ios端，很容易滑动返回上一层，不知道有什么方法可以规避这个bug，全局监听touchmove倒是可以，不过这样会把上下滚动同样禁止了......

**Comment by chenjiahan** [comment]
@zhaoshuan 可以只在水平方向滑动的时候 preventDefault

**Comment by ereddate** [comment]
tabs的滑动与tabs内的内容滑动有冲突，tabs内的内容滑动不是用的vant的组件，如何解决？

**Comment by chenjiahan** [comment]
@ereddate 在内部可以加一层阻止冒泡的逻辑，防止 touch 事件冒泡到上层

**Comment by SuiFengErQu** [comment]
我在使用tab的sticky遇到一个问题，不知道怎么解决，就是在ios上滑动到吸顶以后，再滑动，滚定过程中tab标签就隐藏消失了，等滑动停止了，才会出现，浏览器上没有问题，不知道是我自己写的不对，还是bug

**Comment by chenjiahan** [comment]
@SuiFengErQu 如果是 UIWebView 的话，滚动事件是停止滚动后触发的，升级到 WKWebView 可以避免这个问题

**Comment by SuiFengErQu** [comment]
@chenjiahan 还有其他的解决方案吗

**Comment by Orow** [comment]
@chenjiahan 請問目前有計畫要支援 - Tab 内容的左右滑動嗎？

**Comment by chenjiahan** [comment]
@Orow 目前我们主要投入在 Vant Weapp 1.0 和 Vant Cli 开发，暂时没精力支持左右滑动功能

欢迎提 PR 来完善这个功能

**Comment by chenxi5211993** [comment]
2.x版本是不是不支持了哇？各位有啥好办法嘛？现在tab里面嵌套的swiper，里面又用bscroll，体验不是很好啊。各位有好办法做这个嘛？或者做好的案列

**Comment by zhaoshuan** [comment]
2.x应该不会支持了吧，遗憾，这功能期待很久了

**Comment by Orow** [comment]
上面已經看到把這需求加到 3.0.0 的 milestone 裡了

**Comment by zhaoshuan** [comment]
强烈建议官方给2.x版本也支持一下，毕竟升级到vue3.0还需要时间过渡，短时间内也不太现实

**Comment by zhaoshuan** [comment]
给各个tab页设置局部滚动后，ios下面，左右滑动切换时，容易触发当前tab页的上下滚动，体验感觉不是太好，官方在后续优化时，可否关注一下这点

**Comment by zhaoshuan** [comment]
> > 举个例子，标签1和标签2内容部分都有20条数据，选中标签1，内容部分往下滚动5条数据，此时切换到标签2，显示的也是滚动到的第5条数据，这是不合理的，此时的标签2应该是从头开始，从第一条数据开始显示
> 
> @zhaoshuan 这个是由于滚动条是 window 的，而不是每一个 tab 导致的。如果希望在切换 tab 后，也能滚动到正确位置，你可以在切换之前，保存下当前窗口的滚动位置，然后再切换回来后，在滚动到这个位置即可

试了一下，给各个tab用css设置局部滚动，即可实现

**Comment by xingqiliudemao** [comment]
tab的标签栏不能手动滑动选择切换了吗现在只能点击切换 之前1.x的是可以的  
- [ ] ![1596075528(1)](https://user-images.githubusercontent.com/42839745/88872982-22b83100-d24e-11ea-953f-9e83b2460064.jpg)

**Comment by 634019392** [comment]
微信小程序中，横向滚动标签超过4个，就会出现标签不对称，比如点第6个标签在点第5个标签

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.3 版本支持，拖延了两年终于加上了😂
