### ISSUE TITLE
[Bug Report] IndexBar索引高亮计算有问题

### ISSUE THREAD

**Issue by RainyLiao** [youzan/vant#11752]
### 重现链接

https://codesandbox.io/p/sandbox/zealous-star-rluefk?selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A18%2C%22startColumn%22%3A19%2C%22startLineNumber%22%3A18%7D%5D&file=%2Fsrc%2FApp.vue

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

如果给IndexBar包裹了一层div，使用padding撑开了与indexBar的距离，给顶部navBar留有空间，就会造成需要滚动相应padding撑开的高度，才会高亮第一个索引。

### 重现步骤

demo里描述了

**Comment by chenjiahan** [comment]
IndexBar 组件是无法感知到自己被 navbar 元素”挡住“了的，因此组件默认基于页面顶部来计算当前的高亮索引，而不是基于其他元素的位置。

如果需要处理这个场景，IndexBar 组件可以考虑添加一个 props 来设置距离顶部的距离，类似于现在的 `sticky-offset-top` 属性

**Comment by RainyLiao** [comment]
好的，多谢解惑，之前本想能不能在getScrollTop获取到的距离上默认加上index-bar容器的厚度（padding+margin+border）
