### ISSUE TITLE
[Bug Report] Uploader ios16上传图片过大无法上传

### ISSUE THREAD

**Issue by decadef20** [youzan/vant#11759]
### 重现链接

https://vant-ui.github.io/vant/v2/#/en-US/uploader

### Vant 版本

2.X

### 描述一下你遇到的问题。

20M的图片，上传时 `after-ready`没有正确回调

### 重现步骤

在移动端打开复现链接，也就是官方文档，在 `Basic Usage`上传一张超过20M的图片，`after-ready`方法没有回调

### 设备/浏览器

iOS 16

**Comment by chenjiahan** [comment]
大文件在转为 dataUrl 时可能会有问题，可以调整 resultType 来处理这个文件

<img width="701" alt="Screen Shot 2023-04-22 at 11 03 56" src="https://user-images.githubusercontent.com/7237365/233758552-a0d9710a-f40d-4df8-81f6-7fbf7c9e4eae.png">

**Comment by decadef20** [comment]
改为file依旧没有回调

**Comment by chenjiahan** [comment]
要不提供一张可以复现该问题的图片

**Comment by chenjiahan** [comment]
或者你用原生的 input type="file" 标签试试，Uploader 也是基于原生标签来做的
