### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by mkcx** [youzan/vant#11758]
### 重现链接

<van-uploader :after-read="afterRead" />

### Vant 版本

4.1.1

### 描述一下你遇到的问题。

同一个页面引入uploader组件和Toast 组件，Toast背景会变为白色

### 重现步骤

只要页面使用了的uploader组件，Toast背景就会变为白色。

**Comment by wjw-gavin** [comment]
参考：https://github.com/youzan/vant/issues/11732#issuecomment-1495582982
