### ISSUE TITLE
[Bug Report] 在Tabs和Tab里使用title-class后打包到线上就会卡住白屏 死循环，而且不报错什么信息都没有

### ISSUE THREAD

**Issue by tom-hanks** [youzan/vant#11763]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-vtpl6z?file=/src/App.vue

### Vant 版本

4.2.0

### 描述一下你遇到的问题。

在Tabs和Tab里使用title-class后打包到线上就会卡住白屏 死循环，而且不报错什么信息都没有

### 重现步骤

本地编译都是正常的

不少人都遇到这个问题，希望官方能够解决
"vite": "^4.2.0"+ "vue": "^3.2.47",+"vant": "^4.2.0",)
打包发布到线上 使用这个组件的title-class页面就白屏卡死，应该是内存溢出了，不使用title-class就没事

### 设备/浏览器

chrome

**Comment by tom-hanks** [comment]
结果排查发现，title-class只能穿入字符串，通过其他技巧可暂时解决这个问题，处理方法如下，供大家参考
第一种：
`
旧的：  
             <Tab
               v-for="item in priceList" :key="item.id"
             :title-class="(() => {
                if (item.id === active) {
                  return 'sele activeClass'
               }
                if (item.id === 3) {
                 return 'sele lastchildsele'
               }
             })()" type="card"
            >
`

**Comment by wjw-gavin** [comment]
确实有这个问题，在开发环境已经回警告了
![image](https://user-images.githubusercontent.com/19986739/234452726-3e2410dd-9a73-4b0d-b544-0849a4eaef08.png)

title-class 传入字符串组合就可以，如果是数组就会有问题。
