### ISSUE TITLE
IndexBar 使用v-show的时候，只保留根元素(display:none)，子元素全部不加载

### ISSUE THREAD

**Issue by iamxiaojuan** [youzan/vant#11769]
### 重现链接

暂无

### Vant 版本

^4.2.0

### 描述一下你遇到的问题。

IndexBar 使用v-show的时候，只保留根元素(display:none)，子元素全部不加载。
![image](https://user-images.githubusercontent.com/13642031/234160644-3b346c39-533f-4cda-a4d6-6311a4bd385b.png)
但如果只是普通的div就不会出现这种情况
![image](https://user-images.githubusercontent.com/13642031/234160709-b40d6fb4-73a4-45ba-96e9-228382019cc6.png)
有没有办法让子元素也渲染？

### 重现步骤

。。

### 设备/浏览器

移动端

**Comment by chenjiahan** [comment]
麻烦提供一个有效的 codesandbox 复现链接喔
