### ISSUE TITLE
[Feature Request] generate:component

### ISSUE THREAD

**Issue by LDXu** [youzan/vant#11765]
### 这个功能解决了什么问题？

使用vant-cli搭建组件库后，如何新增组件，使用脚本创建非业务行的标准规范文件，组件开发者只需要关注业务逻辑即可。
类似https://github.com/Tencent/tdesign-vue-next/blob/develop/package.json的命令generate:component。
请问一下已经有了吗？找了一下没有找到。有了的话，资料或者链接回复一下，谢谢。

### 你期望的 API 是什么样子的？

类似https://github.com/Tencent/tdesign-vue-next/blob/develop/package.json的命令generate:component

**Comment by chenjiahan** [comment]
目前没有这个自动 generate 的 CLI 命令哈，可以直接 copy 已有组件的目录。

后续我们评估下是否要添加一个命令

**Comment by LDXu** [comment]
好的
