### ISSUE TITLE
[Bug Report] watermark水印组件在iphone12自带的safari浏览器上不显示

### ISSUE THREAD

**Issue by BizhiGHost** [youzan/vant#11761]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/watermark

### Vant 版本

4.2.0

### 描述一下你遇到的问题。

<van-watermark
      :image="base64图片字符串"
      :width="280"
      :height="220"
      rotate="0"
      opacity="1"
      :z-index="99999"
      :full-page="true"
    />
在iphone12自带的safari浏览器上无法显示，直接访问官网demo也可复现

### 重现步骤

用iphone12自带的safari浏览器预览，不显示水印。直接访问官方demo也可以复现出来

### 设备/浏览器

iphone12自带的safari浏览器

**Comment by chenjiahan** [comment]
@HuberTRoy 帮忙看一下这个兼容性问题哈

**Comment by AllenWalke** [comment]
麻烦问一下  这个修复什么时候发版

**Comment by chenjiahan** [comment]
这两天会发一个
