### ISSUE TITLE
[Feature Request] Cascader 级联选择优化需求：期望级联选择回显的时候能定位到选中的地方

### ISSUE THREAD

**Issue by Mrwangfan** [youzan/vant#11770]
### 这个功能解决了什么问题？

用户体验会更好
我选中山西了
![image](https://user-images.githubusercontent.com/22339042/234163072-8da19ad8-8c78-4ab1-9e0e-e6518b3da7ef.png)
回显的时候我需要滚动才能看见山西
![image](https://user-images.githubusercontent.com/22339042/234163129-2da7e221-6ebf-4156-b1de-ce3f03d1b9ee.png)

### 你期望的 API 是什么样子的？

期望可以定位到山西
![image](https://user-images.githubusercontent.com/22339042/234163194-db2c8890-336b-4ad9-bd59-041583f3c082.png)

**Comment by chenjiahan** [comment]
确实能自动定位到选中位置会比较好。

不过由于 Tabs 的水平可滑动结构，这个功能直接使用原生的 scrollintoview 方法实现时遇到了一些问题，后续考虑自行实现一个 scrollintoview 来处理该场景。
