### ISSUE TITLE
[Feature Request] vant组件内部均使用setup写法，没有使用defineExpose暴露内部方法，无法从外部通过ref控制组件内部行为

### ISSUE THREAD

**Issue by xiaofei3062** [youzan/vant#11774]
### 这个功能解决了什么问题？

vant组件内部均使用setup写法，没有使用defineExpose暴露内部方法，无法从外部通过ref控制组件内部行为

### 你期望的 API 是什么样子的？

vant组件内部均使用setup写法，没有使用defineExpose暴露内部方法，无法从外部通过ref控制组件内部行为

**Comment by chenjiahan** [comment]
Vant 只暴露在文档中标注的组件方法，其他内部方法是私有的，不属于对外 API，也无法保证 API 的向前兼容性。

如果有哪个需要对外暴露的方法，可以在 Issue 中进行沟通，我们会酌情添加。

**Comment by xiaofei3062** [comment]
希望van4的van-cascader，添加一个可以控制内部tabs的方法和tabIndex的方法

**Comment by chenjiahan** [comment]
我们评估下

**Comment by chenjiahan** [comment]
有一个相似的 issue：https://github.com/youzan/vant/issues/11499

这个 issue 先 close 咯，可以到 [#11499] 中一起讨论
