### ISSUE TITLE
[Feature Request] 能否实现css自定义命名空间，类似element ui的自定义命名空间

### ISSUE THREAD

**Issue by thunderstreak** [youzan/vant#11782]
### 这个功能解决了什么问题？

在使用qiankun做微前端接入的时候，主应用使用的是vant^2.10.10版本，接入的微应用使用的是vant^4.2.0版本，子应用渲染出来后对父应用样式产生了影响（子应用的样式覆盖了主应用），现在在通过启用乾坤的sandbox配置做样式隔离，由于启用了shadow dom，发现vite生成的样式全部注入到了主应用的head中，无法应用到子应用上，不启用又会导致样式覆盖，现在想要一个区分vant样式名的功能，提供自定义的样式命名空间，感谢！

### 你期望的 API 是什么样子的？

```
<template>
  <van-config-provider namespace="custom">
  </van-config-provider>
</template>
```

**Comment by chenjiahan** [comment]
Vant 不支持自定义 CSS 命名空间。

如果要自定义 CSS 命名空间，势必会涉及到对 CSS className 的定制，而这依赖特定的编译逻辑来实现。但目前 Vant 是不依赖任何编译逻辑的，后续也会尽量避免引入对编译逻辑的依赖，因此目前没有提供相关能力的计划。

对于这个问题，我倾向于使用微前端框架的样式隔离能力来实现，如果微前端的样式隔离能力有问题，建议到微前端框架的仓库中寻找解决方法。

**Comment by thgames908** [comment]
> 空间

我遇到跟你一模一样的问题,  你解决没...

**Comment by thgames908** [comment]
我也遇到了  你解决没...

**Comment by thunderstreak** [comment]
> @thunderstreak 我也遇到了 你解决没...

暂时没有，目前能想到的是使用webpack搭建应该会规避这个问题

**Comment by Leovenn** [comment]
我现在想主应用使用vant 但是如果子应用也使用vant 主应用的样式会影响子应用
现在想到的解决方案就是 给主应用的vant 增加 css namespace 
有没有其他的解决方案 大佬 @chenjiahan
