### ISSUE TITLE
calender 打开空白，scroll后恢复

### ISSUE THREAD

**Issue by wsi18n** [youzan/vant#11783]
### 重现链接

https://github.com/youzan/vant/issues/11783

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

# 错误现象：iPhone only
![3c78d8eac54b1a23fddf6b118e44b1cd](https://user-images.githubusercontent.com/44825794/234837762-aac394b9-b7b8-4779-8972-d958749c98dd.jpg)

# BUG定位：
``` js
bottom > heightSum
```

看了这几行代码的几次commit 没看明白这个判断的用途

![image](https://user-images.githubusercontent.com/44825794/234836610-b5a580c6-0f25-4c68-897a-7dd2aa48bc9e.png)
![8ddf18763de9dda968051daac4b82e6c](https://user-images.githubusercontent.com/44825794/234836631-793083b4-3880-40b9-a06a-7bf7887f3cdb.jpg)

### 重现步骤

打开calender,
props:
![image](https://user-images.githubusercontent.com/44825794/234839472-f84998cc-5c44-43f2-97fc-8eba77d1f30e.png)

**Comment by chenjiahan** [comment]
这个判断是用于 lazy-render 优化的，即只渲染当前可视区域的 DOM 节点。

对于你这个问题，可以把 lazy-render 设置为 `false` 来处理，也可以提供一个 codesandbox 复现链接来方便我们排查

**Comment by JerryWang24** [comment]
我也碰到这个问题了~~van-calendar放在van-popup默认是隐藏的状态，poppable设置为false，不管 lazy-render设置什么都，显示van-calendar都是空白的！
再说，lazy-render设置什么值都时全部节点加载的。可以看看我提的issue

**Comment by wsi18n** [comment]
这个问题只有iphone会出现 (bottom > heightSum）, codesandbox 无法复现

**Comment by RedStarGroup** [comment]
> 这个问题只有iphone会出现 (bottom > heightSum）, codesandbox 无法复现

该问题与屏幕宽高比有关，与机型无关，不局限于iPhone，在自定义左侧第一列为周一时，比如宽高为196*399、1016*2532 在PC Chrome也可以必现该问题

iPhone13 下 设置first-day-of-week属性为1，必现该问题，如果调整用法，默认自然排列从周日开始，可一定程度避免，但宽高比还是会导致初次显示无法触发lazy-render。

个人认为日历的懒加载逻辑过于依赖宽高尺寸导致触发渲染的条件过于苛刻，容易出现bug，建议官方考虑修复，可以考虑提供类似reset的方法支持用户主动调用渲染逻辑。
虽然lazy-render设置为false可以解决该问题，但是无法解决渲染性能问题，毕竟较大间隔的范围限制是比较正常的需求。

用例参考：
`
  <van-calendar
    v-model:show="showDatePicker"
    :default-date="defaultRange"
    :min-date="minDate"
    :max-date="maxCalendarDate"
    type="range"
    :max-range="7"
    :allow-same-day="false"
    @confirm="onCalendarConfirm"
    @close="onCancel"
  />
`

**Comment by zhaodengping** [comment]
这个问题还存在，设置高度为75%只解决了部分手机白屏的问题，还有手机复现。。有没有彻底解决的方案呀，在线等，急
