### ISSUE TITLE
[Bug Report] Vant 4.x 中的 细边框按钮 在 Firefox 中显示异常

### ISSUE THREAD

**Issue by QuestionMark001** [youzan/vant#11788]
### 重现链接

https://github.com/QuestionMark001/WebEx/tree/main/src/Vant%20UI/01_Button

### Vant 版本

4.2.0

### 描述一下你遇到的问题。

使用 `Vue 3` + `Vant 4.2.0` 写了几个按钮组件，发现 `细边框按钮` 在 **`Firefox`** 浏览器中 **边框无法被完全正常显示**，如下图所示：  

![截图 2023-04-30 21-03-24](https://user-images.githubusercontent.com/53328516/235354944-75ce93a8-da31-4771-b2f6-6b079ea8ee18.png)

经复现排查，当 **`Firefox 浏览器缩放`** <= **`130%`** 时，则会出现该问题，如图所示：  

![截图 2023-04-30 21-47-30](https://user-images.githubusercontent.com/53328516/235356356-d0002c7c-de84-4616-8316-d214ab0e9f48.png)

![截图 2023-04-30 21-41-21](https://user-images.githubusercontent.com/53328516/235356063-86de4871-5a42-4a07-8778-77f86000da87.png)

![截图 2023-04-30 21-42-12](https://user-images.githubusercontent.com/53328516/235356077-fb264e5b-a844-45c4-acef-51826aa629ab.png)

当 **`Firefox 浏览器缩放`** > **`130%`** 时，就不会出现该问题，如图所示：

![截图 2023-04-30 21-44-18](https://user-images.githubusercontent.com/53328516/235356189-d4271256-7864-4a23-b9a9-907d1570f4d6.png)

![截图 2023-04-30 21-43-08](https://user-images.githubusercontent.com/53328516/235356193-350a45eb-2e35-4684-b467-e487b91b2596.png)

`Firefox` 版本为 `112.0.2`：  

![截图 2023-04-30 21-05-14](https://user-images.githubusercontent.com/53328516/235355064-9ddeec6d-224a-491a-83e1-c8fde31ac5c1.png)

涉及该 `Bug` 的主要代码如下：

```vue
<van-button hairline plain type="primary" class="button">细边框主要按钮</van-button>
<van-button hairline plain type="success" class="button">细边框成功按钮</van-button>
```

可复现该 `Bug` 的示例项目地址：  
[https://github.com/QuestionMark001/WebEx/tree/main/src/Vant%20UI/01_Button](https://github.com/QuestionMark001/WebEx/tree/main/src/Vant%20UI/01_Button)

### 重现步骤

1. 使用 `npm run dev` 运行
2. `Firefox` 打开该项目即可复现该问题

### 设备/浏览器

ArchLinux/Firefox

**Comment by chenjiahan** [comment]
参考：https://github.com/youzan/vant/issues/10682
