### ISSUE TITLE
[Feature Request] 可否把官网“文档”的代码也分享出来的呢？我想帮忙加一个检索的板块～

### ISSUE THREAD

**Issue by martianmartian** [youzan/vant#11802]
### What problem does this feature solve?

通过menu的文字检索有点慢，很多时候找不到合适的组建，希望能有个集合的页面，可以一目了然的看到所有的组建大概有哪些（通过图形的方式）

### What does the proposed API look like?

nothing here

**Comment by inottn** [comment]
这个仓库已经包含文档的代码了，可以在对应组件文件夹下查阅 README.md 文件。

**Comment by chenjiahan** [comment]
嗯嗯，欢迎添加一个 Overview 页面~ 

可以参考官网的贡献指南：https://vant-contrib.gitee.io/vant/#/zh-CN/contribution
