### ISSUE TITLE
[Bug Report] van-calendar组件lazy-render属性无效

### ISSUE THREAD

**Issue by JerryWang24** [youzan/vant#11821]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-nx8se8?file=/src/App.vue

### Vant 版本

4.2.0

### 描述一下你遇到的问题。

`<van-calendar
  :poppable="false"
  :show-confirm="false"
  :lazy-render="true"
  :min-date="minDate"
  :max-date="maxDate"
  :style="{ height: '500px' }"
  />`
  展示时，使用lazy-render为true时，全部日期节点都加载了。

### 重现步骤

例子F12查看节点

**Comment by inottn** [comment]
目前的设计是这样的，不在可视区域的内容会渲染占位节点，可视区域的内容会渲染真实的日期节点。

**Comment by JerryWang24** [comment]
> 目前的设计是这样的，不在可视区域的内容会渲染占位节点，可视区域的内容会渲染真实的日期节点。

那这个lazy的作用并不大？加载两年的日期都很卡了！
看来只能选择其他日期插件了

**Comment by inottn** [comment]
> > 目前的设计是这样的，不在可视区域的内容会渲染占位节点，可视区域的内容会渲染真实的日期节点。
> 
> 那这个lazy的作用并不大？加载两年的日期都很卡了！ 看来只能选择其他日期插件了

嗯，后续可以考虑优化一下 `lazy-render` 的逻辑

**Comment by chenjiahan** [comment]
目前 lazy-render 后的 DOM 树不太好再继续简化了，以后考虑通过「点击切换年份/月份」的交互来支持年份较多的场景。

参考：https://github.com/youzan/vant/issues/11228
