### ISSUE TITLE
TextEllipsis 组件的兼容性问题

### ISSUE THREAD

**Issue by blisssayyid** [youzan/vant#11826]
### 重现链接

https://cdn.tathatasoft.com/gispro/web/v11/#/upgrade

### Vant 版本

^4.3.1

### 描述一下你遇到的问题。

无法展开

![image](https://user-images.githubusercontent.com/11463194/236715076-5c01fdcf-3b77-472f-83a3-83131af8d2f0.png)

### 重现步骤

打开即可复现

### 设备/浏览器

Android9.0设备，对应的版本为 chromium 66

**Comment by wjw-gavin** [comment]
....我看代码也没啥兼容性的 api 啊...  我身边也没这种设备调试

**Comment by blisssayyid** [comment]
> ....我看代码也没啥兼容性的 api 啊... 我身边也没这种设备调试

我刚刚又尝试了下， 问题出在 van-cell 组件上，低版本浏览器的高度感觉被固定住了，高版本没事。

**Comment by blisssayyid** [comment]
> ....我看代码也没啥兼容性的 api 啊... 我身边也没这种设备调试

刚解决，其实是 van-cell 的问题，需要加上 `flex-shrink: 0` 属性，阻止 flex 项目缩小，否则在低版本的浏览器就会发生这个问题
