### ISSUE TITLE
van-search点击清除的icon不生效

### ISSUE THREAD

**Issue by zhouzhi-zz** [youzan/vant#11824]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-tdlhzy?file=/src/App.vue

### Vant 版本

4.2.0

### 描述一下你遇到的问题。

van-search输入内容后，点击清除不生效，但是点击清除的右上角多一点就生效了，发生了偏移。。。。 不知道是否和vue版本有问题"vue": "^3.2.45"。在连接中已经设置好版本号了。

### 重现步骤

van-search引入
输入文本，点击清除的icon无效，点击右上角生效。

### 设备/浏览器

谷歌

**Comment by wjw-gavin** [comment]
桌面端需要适配： https://youzan.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei

**Comment by zhouzhi-zz** [comment]
我使用vant是移动端的，在谷歌的iphone6/7/8plus模拟器开发的。

**Comment by androidlsl** [comment]
> 桌面端需要适配： https://youzan.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei

按文档配置了  还是没效果
