### ISSUE TITLE
[Bug Report] Steps 步骤条 只有一个节点时会样式错位

### ISSUE THREAD

**Issue by uu109** [youzan/vant#11820]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-4mbmh6?file=/src/App.vue

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

当Steps组件只有一个数据节点的时候，UI显示不完整。

### 重现步骤

```
<van-steps :active="0">
  <van-step>买家下单</van-step>
</van-steps>
```

**Comment by inottn** [comment]
嗯，是有这个问题，要看下只有一个节点时的样式，应该居左还是居中🤔。@chenjiahan 

居左：
<img width="361" alt="image" src="https://user-images.githubusercontent.com/18509404/236393393-6eded735-ef08-45f6-b2d0-1cf13568aeb4.png">
居中：
<img width="361" alt="image" src="https://user-images.githubusercontent.com/18509404/236393097-d7f4dda6-4730-4806-aa60-e5e7f8bd4a44.png">

**Comment by chenjiahan** [comment]
感觉居左比较合理哈
