### ISSUE TITLE
PullRefresh组件性能问题

### ISSUE THREAD

**Issue by 2678642922** [youzan/vant#11825]
### 重现链接

暂无

### Vant 版本

3.6.11

### 描述一下你遇到的问题。

PullRefresh下拉的时候会频繁触发子组件重绘
这可能对性能影响较大，希望能解决

这是Demo
![image](https://user-images.githubusercontent.com/73087873/236712705-182e0211-9d9a-47e8-b2ed-aedb29972921.png)

### 重现步骤

**1、什么都不操作，初始状态如下**
![image](https://user-images.githubusercontent.com/73087873/236712849-6f250652-9735-4e31-aa40-44e6f317a6fb.png)

**2、下拉拖拽**
![image](https://user-images.githubusercontent.com/73087873/236712971-29656f25-642b-47df-8990-9b0c15f6250b.png)

**3、松开拖拽，完成下拉**
![image](https://user-images.githubusercontent.com/73087873/236713031-e41fac10-aecc-40e7-8d7f-a55460742886.png)

### 设备/浏览器

谷歌浏览器

**Comment by inottn** [comment]
会触发重绘应该是 `Vue` 的逻辑，可以把传入的 `slot` 封装成组件试试

**Comment by 13725102796** [comment]
官方用例是用computed，去缓存相同的结果
``` bash 
const getText = computed(() => {
  console.log('rendered');
  return 'test';
});

# div
<pull-refresh v-model="loading" @refresh="onRefresh(true)">
   <p>{{ getText }}</p>
</pull-refresh>
```

**Comment by 2678642922** [comment]
> 官方用例是用computed，去缓存相同的结果
> 
> ```shell
> const getText = computed(() => {
>   console.log('rendered');
>   return 'test';
> });
> 
> # div
> <pull-refresh v-model="loading" @refresh="onRefresh(true)">
>    <p>{{ getText }}</p>
> </pull-refresh>
> ```

可是computed不能传值啊

**Comment by chenjiahan** [comment]
> 会触发重绘应该是 Vue 的逻辑，可以把传入的 slot 封装成组件试试

用这个方法就可以哈
