### ISSUE TITLE
[Bug Report] Popup在Tabs加了animated属性下 Popup宽度会有问题

### ISSUE THREAD

**Issue by LuckyQ7** [youzan/vant#11834]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-id0egl?file=/src/App.vue

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

1. Tabs 加 animated
2. Popup 是放在 tab里面的
3. 唤起的选择器 van-popup的宽度将会是 van-swipe__track 的宽度

### 重现步骤

1.点击选择器 选择城市

### 设备/浏览器

Google Chrome

**Comment by inottn** [comment]
原因：应用了 transform 属性的元素会导致该元素形成一个新的包含块，然后其后代元素如果有 fixed 定位的属性，那么其元素将会以该父元素作为包含块。

解决方法：可以将 popup 组件放到 tabs 外，或者使用 teleport 属性。
