### ISSUE TITLE
无法在钉钉及支付宝打开

### ISSUE THREAD

**Issue by Larry-lb** [youzan/vant#11833]
### 重现链接

无法在钉钉及支付宝打开

### Vant 版本

4.0.11

### 描述一下你遇到的问题。

vant4在支付宝上无法打开

### 重现步骤

vant4在支付宝上无法打开

### 设备/浏览器

钉钉支付宝

**Comment by inottn** [comment]
是某个组件无法正常显示吗，有能够复现问题的链接吗？更具体的信息有助于更快的解决问题。

**Comment by Larry-lb** [comment]
> 是某个组件无法正常显示吗，有能力复现问题的链接吗？更全面的信息有助于更快的解决问题。

https://vant-ui.github.io/vant/#/zh-CN/home 我们这个网站在钉钉和支付宝上就无法打开

**Comment by inottn** [comment]
> > 是某个组件无法正常显示吗，有能力复现问题的链接吗？更全面的信息有助于更快的解决问题。
> 
> https://vant-ui.github.io/vant/#/zh-CN/home 我们这个网站在钉钉和支付宝上就无法打开

可以提供一下安卓版本和支付宝版本吗

**Comment by Larry-lb** [comment]
> > > 是某个组件无法正常显示吗，有能力复现问题的链接吗？更全面的信息有助于更快的解决问题。
> > 
> > 
> > https://vant-ui.github.io/vant/#/zh-CN/home 我们这个网站在钉钉和支付宝上就无法打开
> 
> 可以提供一下安卓版本和支付宝版本吗
华为手机鸿蒙系统3.0.0.212    支付宝版本10.3.76  钉钉版本7.0.25

**Comment by inottn** [comment]
看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。

**Comment by Larry-lb** [comment]
> 看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。

我在使用van-tabs组件后就无法在支付宝和钉钉中正常展示、其它浏览器正常

**Comment by Nakus0426** [comment]
试一下更新系统内置的WebView版本，如果这几个软件没有内置内核的话应该可以解决问题

**Comment by jianchaozhuang** [comment]
> > 看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。
> 
> 我在使用van-tabs组件后就无法在支付宝和钉钉中正常展示、其它浏览器正常

大佬解决了嘛？我也遇到这个问题。 van-tabs 在支付宝和钉钉浏览器显示异常

**Comment by inottn** [comment]
> > > 看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。
> > 
> > 
> > 我在使用van-tabs组件后就无法在支付宝和钉钉中正常展示、其它浏览器正常
> 
> 大佬解决了嘛？我也遇到这个问题。 van-tabs 在支付宝和钉钉浏览器显示异常

有具体的报错信息吗，或者可以提供最小能够复现的 demo 吗

**Comment by jianchaozhuang** [comment]
> > > > 看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。
> > > 
> > > 
> > > 我在使用van-tabs组件后就无法在支付宝和钉钉中正常展示、其它浏览器正常
> > 
> > 
> > 大佬解决了嘛？我也遇到这个问题。 van-tabs 在支付宝和钉钉浏览器显示异常
> 
> 有具体的报错信息吗，或者可以提供最小能够复现的 demo 吗

看不到报错信息，vConsole都没有出现。

![9c1c36d64cd661ea76bde76ddcb8175c](https://github.com/youzan/vant/assets/124876472/a451c976-c1f9-4398-82bd-7d592c171453)
![7e7167db78c25e1c78de76571d133a24](https://github.com/youzan/vant/assets/124876472/9c4c641e-d8dc-41b9-a01b-7fa3f1bf4fc0)
![9a32d17235f9b0118bfec3cec15c000e](https://github.com/youzan/vant/assets/124876472/9e0af644-b048-4ad2-83f4-e25c348fef0d)

图一是安卓系统截图
图二是钉钉浏览
图三是内置浏览器浏览

**Comment by jianchaozhuang** [comment]
> > > > 看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。
> > > 
> > > 
> > > 我在使用van-tabs组件后就无法在支付宝和钉钉中正常展示、其它浏览器正常
> > 
> > 
> > 大佬解决了嘛？我也遇到这个问题。 van-tabs 在支付宝和钉钉浏览器显示异常
> 
> 有具体的报错信息吗，或者可以提供最小能够复现的 demo 吗

![9c1c36d64cd661ea76bde76ddcb8175c](https://github.com/youzan/vant/assets/124876472/1f98ea78-b86f-4718-a89a-25a1a28f0341)
手机型号
![image](https://github.com/youzan/vant/assets/124876472/1eff948c-91b2-4d76-ab99-25a108e1c189)
钉钉预览
![image](https://github.com/youzan/vant/assets/124876472/bb9b43e2-2169-4bc9-86f8-53808d9c4e7a)
内置浏览器预览


感觉是钉钉内置浏览器的版本问题，vConsole都显示不出来了。。。。。

**Comment by inottn** [comment]
> > > 看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。
> > 
> > 
> > 我在使用van-tabs组件后就无法在支付宝和钉钉中正常展示、其它浏览器正常
> 
> 大佬解决了嘛？我也遇到这个问题。 van-tabs 在支付宝和钉钉浏览器显示异常

嗯，项目用的构建工具是什么？

**Comment by jianchaozhuang** [comment]
> > > > > 看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。
> > > > 
> > > > 
> > > > 我在使用van-tabs组件后就无法在支付宝和钉钉中正常展示、其它浏览器正常
> > > 
> > > 
> > > 大佬解决了嘛？我也遇到这个问题。 van-tabs 在支付宝和钉钉浏览器显示异常
> > 
> > 
> > 有具体的报错信息吗，或者可以提供最小能够复现的 demo 吗
> 
> ![9c1c36d64cd661ea76bde76ddcb8175c](https://user-images.githubusercontent.com/124876472/246067696-1f98ea78-b86f-4718-a89a-25a1a28f0341.jpg) 手机型号 ![image](https://user-images.githubusercontent.com/124876472/246067847-1eff948c-91b2-4d76-ab99-25a108e1c189.png) 钉钉预览 ![image](https://user-images.githubusercontent.com/124876472/246067938-bb9b43e2-2169-4bc9-86f8-53808d9c4e7a.png) 内置浏览器预览
> 
> 感觉是钉钉内置浏览器的版本问题，vConsole都显示不出来了。。。。。

vite

> > > > 看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。
> > > 
> > > 
> > > 我在使用van-tabs组件后就无法在支付宝和钉钉中正常展示、其它浏览器正常
> > 
> > 
> > 大佬解决了嘛？我也遇到这个问题。 van-tabs 在支付宝和钉钉浏览器显示异常
> 
> 嗯，项目用的构建工具是什么？

vite

**Comment by jianchaozhuang** [comment]
> > > > 看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。
> > > 
> > > 
> > > 我在使用van-tabs组件后就无法在支付宝和钉钉中正常展示、其它浏览器正常
> > 
> > 
> > 大佬解决了嘛？我也遇到这个问题。 van-tabs 在支付宝和钉钉浏览器显示异常
> 
> 嗯，项目用的构建工具是什么？

vite

**Comment by inottn** [comment]
> > > > > 看了下应该是兼容性问题，不影响用户自己的项目使用vant组件。
> > > > 
> > > > 
> > > > 我在使用van-tabs组件后就无法在支付宝和钉钉中正常展示、其它浏览器正常
> > > 
> > > 
> > > 大佬解决了嘛？我也遇到这个问题。 van-tabs 在支付宝和钉钉浏览器显示异常
> > 
> > 
> > 嗯，项目用的构建工具是什么？
> 
> vite

vite 的兼容性要求较高，[参考](https://cn.vitejs.dev/guide/build.html#browser-compatibility)。

**Comment by inottn** [comment]
参考 #11958 ，如果使用 vite 构建的话，兼容性要求会更高。不是的话，需要一个能够重现的链接。
