### ISSUE TITLE
van-field组件在点击label位置时，绑定的click事件会执行两次

### ISSUE THREAD

**Issue by n19ht** [youzan/vant#11831]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-0re33r?file=/src/App.vue

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

van-field组件在点击label位置时，绑定的click事件会执行两次

### 重现步骤

van-field组件在点击label位置时，绑定的click事件会执行两次

**Comment by n19ht** [comment]
> 可以使用 @click.prevent 先解决触发两次事件的问题。
> 
> 原因：这是因为 label 和 input 通过使用 for 和 id 属性将它们绑定在一起后，在点击 label 元素后的默认行为是将 for 属性绑定的元素聚焦，并触发点击事件。
> 
> 当然组件内部可以禁止 label 的默认行为，但是这样点击 label后，input 也不会聚焦了。

后续会修复组件的这个问题吗

**Comment by inottn** [comment]
> > 可以使用 @click.prevent 先解决触发两次事件的问题。
> > 原因：这是因为 label 和 input 通过使用 for 和 id 属性将它们绑定在一起后，在点击 label 元素后的默认行为是将 for 属性绑定的元素聚焦，并触发点击事件。
> > 当然组件内部可以禁止 label 的默认行为，但是这样点击 label后，input 也不会聚焦了。
> 
> 后续会修复组件的这个问题吗

这个属于浏览器的默认行为，看了下其它组件库也存在这个问题。在发现有较好的解决方法前，可能还是需要用户自行处理。

**Comment by 13725102796** [comment]
> 可以使用 @click.prevent 先解决触发两次事件的问题。
> 
> 原因：这是因为 label 和 input 通过使用 for 和 id 属性将它们绑定在一起后，在点击 label 元素后的默认行为是将 for 属性绑定的元素聚焦，并触发点击事件。
> 
> 当然组件内部可以禁止 label 的默认行为，但是这样点击 label后，input 也不会聚焦了。

通过阻止stopPropagation，可以解决两次触发点击事件的问题，input也可以正常聚焦
