### ISSUE TITLE
[Bug Report] 表单中使用带图标的<van-field />，校验失败后错误信息【对齐方式】显示异常

### ISSUE THREAD

**Issue by cgbin24** [youzan/vant#11840]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-j24pwh?file=/src/App.vue

### Vant 版本

v4.3.1

### 描述一下你遇到的问题。

1、表单中使用右侧带有图标的 `van-field` 输入框组件
2、同时为该组件设置 `input-align="right"` 和 `error-message-align="right"`
3、校验失败时错误信息显示异常，【错误信息没有右对齐】，未能与表单中其它项保持一致
4、经检查后得知由于使用 `flex` 布局且右侧内容被图标占据导致无法实现【右对齐】功能

![image](https://github.com/youzan/vant/assets/46283404/a2bbb29f-4151-4391-bfc5-2313f4c270b0)
![image](https://github.com/youzan/vant/assets/46283404/2421f5d8-9ccb-4b77-8d06-0876bfd907cf)

### 重现步骤

1、进入复现链接、等待内容加载完成
2、点击表单中的【提交】按钮查看错误信息位置

**Comment by yanbowe** [comment]
这应该是正常表现，dom结构分为了3部分，提示信息与value的dom结构是一起的，有图标的情况下可以考虑靠左显示

**Comment by cgbin24** [comment]
> 这应该是正常表现，dom结构分为了3部分，提示信息与value的dom结构是一起的，有图标的情况下可以考虑靠左显示

保持这样的结构布局设计，确实是正常显示的；但是这样放在整个表单中来看，同时通过API描述`error-message-align="right"`【靠右对齐】就显得不是很得当了，如上问题，在表单中无法与其余字段保持一致布局；目前的解决方案确实可以靠左显示、或者自己实现、亦或者官方能出更好的方案

**Comment by chenjiahan** [comment]
在 Field 目前的 DOM 结构设计中，这个布局是符合预期的，目前也没有调整该布局的计划哈。

如果希望 error-message 是对齐到最右侧的话，可以添加一些自定义 CSS 样式，比如添加适当的负 margin，来让它对齐到最右侧。
