### ISSUE TITLE
vant4.x van-image Lazyload 不能正确加载图片

### ISSUE THREAD

**Issue by lixiaofa** [youzan/vant#11849]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-6gi99s

### Vant 版本

4.12

### 描述一下你遇到的问题。

根据文档配置， 不能正确加载图片报错

### 重现步骤

无

**Comment by inottn** [comment]
```js
import { Lazyload } from 'vant';
app.use(Lazyload);
```
加上试试

**Comment by lixiaofa** [comment]
> ```js
> import { Lazyload } from 'vant';
> app.use(Lazyload);
> ```
> 
> 加上试试
他本来就是全局注册的呀 ， 在实例中

**Comment by lixiaofa** [comment]
![image](https://github.com/youzan/vant/assets/23230215/2d60bf71-bd46-4c2a-b4d9-69a3fac1f63c)

且代码检查也过不了

**Comment by inottn** [comment]
> > ```js
> > import { Lazyload } from 'vant';
> > app.use(Lazyload);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 加上试试
> > 他本来就是全局注册的呀 ， 在示例中
> 
> @inottn

https://codesandbox.io/s/vant-4-issue-template-forked-pbef3p

**Comment by lixiaofa** [comment]
> > > ```js
> > > import { Lazyload } from 'vant';
> > > app.use(Lazyload);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 加上试试
> > > 他本来就是全局注册的呀 ， 在示例中
> > 
> > 
> > @inottn
> 
> https://codesandbox.io/s/vant-4-issue-template-forked-pbef3p

我不明白为什么要写两遍 ， 这不是bug吗
@inottn

**Comment by inottn** [comment]
> > > > ```js
> > > > import { Lazyload } from 'vant';
> > > > app.use(Lazyload);
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 加上试试
> > > > 他本来就是全局注册的呀 ， 在示例中
> > > 
> > > 
> > > @inottn
> > 
> > 
> > https://codesandbox.io/s/vant-4-issue-template-forked-pbef3p
> 
> 我不明白为什么要写两遍 ， 这不是bug吗 @inottn

由于 Lazyload 组件在注册时可以传入一些配置项，所以我们不会自动注册 Lazyload 组件，需要手动进行注册

**Comment by lixiaofa** [comment]
> 

![image](https://github.com/youzan/vant/assets/23230215/dd600bc2-882e-414a-958d-b8cb339c6493) 
局部注册也不行

https://codesandbox.io/s/vant-4-issue-template-forked-6gi99s
@inottn
我应该怎么用这个组件，局部注册

**Comment by lxchuan12** [comment]
<img width="1146" alt="image" src="https://github.com/youzan/vant/assets/15962539/dbbed855-c667-447a-a904-3da210ea6fee">

你应该是写错了指令。`v-lazy` 指令可用。

[vant lazyload 官方文档](https://vant-contrib.gitee.io/vant/#/zh-CN/lazyload)

我曾经写过一篇源码文章，也可供参考。
[vant4.0 正式发布了，分析其源码学会用 vue3 写一个图片懒加载组件！](https://juejin.cn/post/7171227417246171149)

**Comment by lixiaofa** [comment]
> <img alt="image" width="1146" src="https://user-images.githubusercontent.com/15962539/238198874-dbbed855-c667-447a-a904-3da210ea6fee.png">
> 你应该是写错了指令。`v-lazy` 指令可用。
> 
> [vant lazyload 官方文档](https://vant-contrib.gitee.io/vant/#/zh-CN/lazyload)
> 
> 我曾经写过一篇源码文章，也可供参考。 [vant4.0 正式发布了，分析其源码学会用 vue3 写一个图片懒加载组件！](https://juejin.cn/post/7171227417246171149)

![image](https://github.com/youzan/vant/assets/23230215/938d4bce-0807-4be6-91f7-239fc2223168)
你是说文档写错了吗
@lxchuan12 
@inottn

**Comment by lixiaofa** [comment]
> <img alt="image" width="1146" src="https://user-images.githubusercontent.com/15962539/238198874-dbbed855-c667-447a-a904-3da210ea6fee.png">
> 你应该是写错了指令。`v-lazy` 指令可用。
> 
> [vant lazyload 官方文档](https://vant-contrib.gitee.io/vant/#/zh-CN/lazyload)
> 
> 我曾经写过一篇源码文章，也可供参考。 [vant4.0 正式发布了，分析其源码学会用 vue3 写一个图片懒加载组件！](https://juejin.cn/post/7171227417246171149)

![image](https://github.com/youzan/vant/assets/23230215/d61cc034-9ce7-4b76-813a-c9afe840aa9a)
你也确定不了 img 组件应用了 lazy-load
@lxchuan12

**Comment by lxchuan12** [comment]
文档没写错，初步发现是`image`组件中的代码`v-lazy` （setup）[Image.tsx#L167](https://github.com/youzan/vant/blob/main/packages/vant/src/image/Image.tsx#L167) 写法不支持导致的。有空我继续看下如何修复~

**Comment by lixiaofa** [comment]
> 文档没写错，初步发现是`image`组件中的代码`v-lazy` （setup）[Image.tsx#L167](https://github.com/youzan/vant/blob/main/packages/vant/src/image/Image.tsx#L167) 写法不支持导致的。有空我继续看下如何修复~

我是该写  lazy-load 还是v-lazy


v-lazy 是没有应用 lazy-load 的
@lxchuan12

**Comment by lxchuan12** [comment]
先不写吧，或者你用 img v-lazy 来替代 van-image

> > 文档没写错，初步发现是`image`组件中的代码`v-lazy` （setup）[Image.tsx#L167](https://github.com/youzan/vant/blob/main/packages/vant/src/image/Image.tsx#L167) 写法不支持导致的。有空我继续看下如何修复~
> 
> 我是该写 lazy-load 还是v-lazy
> 
> v-lazy 是没有应用 lazy-load 的 @lxchuan12

**Comment by lixiaofa** [comment]
> 先不写吧，或者你用 img v-lazy 来替代 van-image
> 
> > > 文档没写错，初步发现是`image`组件中的代码`v-lazy` （setup）[Image.tsx#L167](https://github.com/youzan/vant/blob/main/packages/vant/src/image/Image.tsx#L167) 写法不支持导致的。有空我继续看下如何修复~
> > 
> > 
> > 我是该写 lazy-load 还是v-lazy
> > v-lazy 是没有应用 lazy-load 的 @lxchuan12

好的

**Comment by nemo-shen** [comment]
> > > > ```js
> > > > import { Lazyload } from 'vant';
> > > > app.use(Lazyload);
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 加上试试
> > > > 他本来就是全局注册的呀 ， 在示例中
> > > 
> > > 
> > > @inottn
> > 
> > 
> > [codesandbox.io/s/vant-4-issue-template-forked-pbef3p](https://codesandbox.io/s/vant-4-issue-template-forked-pbef3p)
> 
> 我不明白为什么要写两遍 ， 这不是bug吗 @inottn

@lixiaofa 

上面 @inottn 提供给你的代码中已经是正确的使用方式了
核心代码是

main.js
```js
import Vant, { Lazyload } from 'vant';
import App from "./App.vue";

const app = createApp(App);
app.use(Vant);
app.use(Lazyload);
```

接下来我解答下你的疑惑

## 文档是否有错误？
文档没有错误，你可以结合 [Lazyload](https://vant-ui.github.io/vant/#/zh-CN/lazyload#yin-ru) 和 [Image 图片懒加载](https://vant-ui.github.io/vant/#/zh-CN/image#tu-pian-lan-jia-zai) 一起看，文档已经明确的告诉了你：如果你希望期望使用图片懒加载能力，需要先通过 `app.use(Lazyload)` 进行注册。

---

## 为什么要写两遍 `app.use()` ？
首先，你需要明白 `Lazyload` 并不是一个组件，而是 [**一个Vue插件**](https://cn.vuejs.org/guide/reusability/plugins.html)。 `Lazyload` 包含：组件和[指令](https://cn.vuejs.org/guide/reusability/custom-directives.html)
- `lazyComponent` 组件，`<lazy-component />` 用于组件懒加载
- `lazyImage` 组件，用于 `<lazy-image />` 用于普通图片懒加载(这个不常用，文档也没写)
- `v-lazy` 指令，用于 `<img />` 懒加载，你可以用 `<img v-lazy src="" />` 实现普通img标签的懒加载
- `v-lazy-container` 指令，用于批量图片懒加载，比如 `<div v-lazy-container><img /><img /></div>`（这个也不常用，文档不写）

对外，他抛出了 `install` 方法，因此你可以用 `app.use()` 直接批量把这些能力都注册到你的应用上。

---

## 为什么我们要用插件的形式提供懒加载，而不是直接在Image组件上支持？

1. 从组件库的角度考虑，我们需要尽可能覆盖更多的异步加载场景，组件和图片一样，都有可能通过异步下发的形式拉取
2. 组件库不知道具体的异步会在哪里发生，无论是提供 `lazy-component` 还是 `v-lazy` 都是这个原因

如果我们在具体的组件中增加异步代码，这会造成两个问题：
1. 冗余代码
2. 体积问题

而且我们必定要提供v-lazy，因为我们要支持 `<img />` 原生图片标签的懒加载。直接在组件上写指令的形式已经被否了，所以我们要用插件的形式去处理。

---

## 不注册 `app.use(Lazyload)` 能不能在组件里直接写？
**如果是vant组件库**
不支持局部组件去写，你可以自己考虑下，如果是你编写了一个指令，你肯定也希望在尽可能多的场景上使用对吧

**如果你一定要在局部组件上写**
可以做，你可以自己写一个类似的指令
指令的文档参考：[Vue Directives](https://cn.vuejs.org/api/options-misc.html#directives)
代码实现可以参考vant源码：[lazy.js](https://github.com/youzan/vant/blob/main/packages/vant/src/lazyload/vue-lazyload/lazy.js)

---

希望能帮到你:)

**Comment by nemo-shen** [comment]
@chenjiahan 帮忙看下，我对 `skipInstall` 跳过 `lazyload` 的理解对么？

**Comment by chenjiahan** [comment]
没问题～ 还有一个主要原因，就是上面写的 "由于 Lazyload 组件在注册时可以传入一些配置项，所以我们不会自动注册 Lazyload 组件，需要手动进行注册"

**Comment by djzgit666** [comment]
vant 4.8.7，问题依然存在
