### ISSUE TITLE
[Bug Report] backtop组件在tab标签页内显示位置有bug

### ISSUE THREAD

**Issue by hzlzsm** [youzan/vant#11842]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-s2zjey

### Vant 版本

4.0.9、4.1.2、4.3.1

### 描述一下你遇到的问题。

 backtop组件在tab标签页内，tab一旦开启swipeable或者animated属性，全部tab内的backtop组件会全部出现在最后一个tab中

### 重现步骤

初始tab 组件swipeable和animated属性为false，标签1和2列表下拉滚动，backtop组件正常在各自相应的tab中显示。点击按钮，开启tab任意属性，所有tab内的backtop组件全部显示在最后一个tab内，位置计算错误。

**Comment by hzlzsm** [comment]
较为麻烦的解决方法就是backtop走默认挂在body上，再用v-if判断当前tab页来控制相应的backtop是否显示。但是在组件化下，再和PullRefresh和list组件组合，处理方法较为繁琐麻烦，不知是否有更简单的方法或者可以修改backtop位置的计算方法

**Comment by zhousg** [comment]
`
<van-tabs
      v-model:active="activeName"
      :animated="animated"
      :swipeable="swipeable"
      class="test-tabs"
    >
      <van-tab title="标签 1" name="a" class="test-tab1">
        <div class="h-120" v-for="(item, index) in 12" :key="index">
          1-{{ index + 1 }}
        </div>
        <van-back-top bottom="100" target=".test-tabs .van-tab__panel:nth-child(1)" />
      </van-tab>
      <van-tab title="标签 2" name="b" class="test-tab2">
        <div class="h-120" v-for="(item, zindex) in 12" :key="zindex">
          2-{{ zindex + 1 }}
        </div>
        <van-back-top bottom="100" target=".test-tabs .van-tab__panel:nth-child(2)"/>
      </van-tab>
      <van-tab title="标签 3" name="c" class="test-tab3">
        <div class="h-120" v-for="(item, sindex) in 1" :key="sindex">
          3-{{ sindex + 1 }}
        </div>
        <van-back-top bottom="100" target=".test-tabs .van-tab__panel:nth-child(3)" />
      </van-tab>
    </van-tabs>
`

`
.van-tab__panel{
  width: 100%;
  height: 100%;
  overflow: auto;
  padding: 16px;
}
`

目前可以这么解决。

现在 `animated` 或 `swipeable` 后或使用 SwipeItem 组件包裹  VanTab 组件，而且 VantTab 组件没有继承组件的 attrs 导致，你在的 test-tab 类型无效，如果有效后加上 `test-tab1|2|3` 对应对应的 BackTop 组件的 target 属性即可。

**Comment by hzlzsm** [comment]
我觉得你指向的issue跟我这个问题所涉及的内容是不一样的。我这个应该是开启这两个属性后，外层的transform属性影响了backtop组件的fixed属性

**Comment by zhousg** [comment]
是的，关闭了哈。

> 最后只能采用原有的处理方法，挂在transform外面，判断当前tab页，用v-if来控制相应的backtop是否显示
如果你是给 test-tab 指定的 `overflow: auto` 也是好使吗？

**Comment by hzlzsm** [comment]
是的，tab里滚动也可以这样处理

**Comment by hzlzsm** [comment]
> 是的，关闭了哈。
> 
> > 最后只能采用原有的处理方法，挂在transform外面，判断当前tab页，用v-if来控制相应的backtop是否显示
> 
> 如果你是给 test-tab 指定的 `overflow: auto` 也是好使吗？滚动容器不是 window 的时候。
是的，tab里滚动也可以这样处理
