### ISSUE TITLE
[New Component]增加浮动气泡组件

### ISSUE THREAD

**Issue by yanbowe** [youzan/vant#11843]
### 这个功能解决了什么问题？

增加浮动气泡组件，全局类的快捷操作会用浮动气泡组件展示

### 你期望的 API 是什么样子的？

1.可以自由拖拽滑动，也可以限制在X轴或Y轴方向滑动
2.可自动吸附X轴最近的一边
3.可以限制拖拽边界
[Ant Design Mobile的浮动气泡](https://mobile.ant.design/zh/components/floating-bubble#floatingbubble)
[nutui的drag](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/drag)

**Comment by chenjiahan** [comment]
有兴趣实现这个组件的同学可以在这个 issue 下面留言~

我们可以参考 Ant Design Mobile 的交互进行实现，不过 Antd 的组件在拖拽时有一些延迟，这一点可以优化下。

**Comment by zhousg** [comment]
@chenjiahan 我来试试
