### ISSUE TITLE
Image组件，当src不存在的情况下，我使用了error插槽，但是结果还是loading插槽中的内容

### ISSUE THREAD

**Issue by YTaoger** [youzan/vant#11859]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-b0qd79?file=/src/App.vue

### Vant 版本

4.1.0

### 描述一下你遇到的问题。

在Image组件中，使用error插槽以及loading插槽，如果src属性值为空时，目前会显示loading插槽中的内容，为什么不是error插槽中的内容呢

### 重现步骤

```
<van-image width="100" height="100" :src="null">
    <template #error> 图片加载出错 </template>
    <template #loading> 图片加载中 </template>
</van-image>
```
<img width="1077" alt="image" src="https://github.com/youzan/vant/assets/35984856/85a79c23-0fd2-47b5-9bc6-a181227b3674">

**Comment by inottn** [comment]
src 为空，浏览器不会发起图片请求，自然也不会触发 onError 事件

**Comment by YTaoger** [comment]
> src 为空，浏览器不会发起图片请求，自然也不会触发 onError 事件
那当src为空，组件怎么才能显示error的插槽而不是loading的插槽呢？

**Comment by inottn** [comment]
目前是无法显示的，你可以根据需求对van-image进行二次封装。

**Comment by YTaoger** [comment]
> 

好吧，谢谢了🙏
