### ISSUE TITLE
vant-uploader在ios系统的webview下添加文件右上角的字体（打开、取消）显示不清晰需要滑动文件页才出现

### ISSUE THREAD

**Issue by MrLoster** [youzan/vant#11853]
### 重现链接

http://vant-contrib.gitee.io/vant/v2/#/zh-CN/uploader

### Vant 版本

2.12.25

### 描述一下你遇到的问题。

【上传附件】【ios】添加附件后跳转到【我的iPhone】页面，选取文件后发现“”“添加”按钮被隐藏

### 重现步骤

【上传附件】【ios】添加附件后跳转到【我的iPhone】页面，选取文件后发现“”“添加”按钮被隐藏

**Comment by chenjiahan** [comment]
听起来是系统界面，和组件库没关系
