### ISSUE TITLE
[Bug Report] SSR 报错

### ISSUE THREAD

**Issue by anjiacm** [youzan/vant#11860]
### 重现链接

view-source:https://mb2.costway.com/55-inch-modern-upholstered-sofa-couch-with-cloth-cushion.html

### Vant 版本

v4.1.0

### 描述一下你遇到的问题。

<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">我们使用vite4 中使用了vant4<br style="box-sizing: border-box;">然后就会提示如下错误：</p>

  | Error: ERR_UNKNOWN_FILE_EXTENSION .css /app/node_modules/vant/es/style/base.css
-- | --
  | at defaultGetFormat (/app/node_modules/ts-node/dist-raw/node-internal-modules-esm-get_format.js:93:15)
  | at defer (/app/node_modules/ts-node/src/esm.ts:296:7)
  | at entrypointFallback (/app/node_modules/ts-node/src/esm.ts:304:22)
  | at getFormat (/app/node_modules/ts-node/src/esm.ts:338:26)
  | at /app/node_modules/ts-node/src/esm.ts:245:17
  | at addShortCircuitFlag (/app/node_modules/ts-node/src/esm.ts:409:21)
  | at load (/app/node_modules/ts-node/src/esm.ts:239:12)
  | at load (/app/node_modules/ts-node/src/child/child-loader.ts:18:36)
  | at nextLoad (node:internal/modules/esm/loader:163:28)
  | at ESMLoader.load (node:internal/modules/esm/loader:605:26)

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">我们的加载方式是<br style="box-sizing: border-box;">import vue from "@vitejs/plugin-vue";<br style="box-sizing: border-box;">import Components from "unplugin-vue-components/vite";<br style="box-sizing: border-box;">import { VantResolver } from "unplugin-vue-components/resolvers";</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(31, 35, 40); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">export default {<br style="box-sizing: border-box;">plugins: [<br style="box-sizing: border-box;">vue(),<br style="box-sizing: border-box;">Components({<br style="box-sizing: border-box;">resolvers: [VantResolver()],<br style="box-sizing: border-box;">}),<br style="box-sizing: border-box;">],<br style="box-sizing: border-box;">};</p>

### 重现步骤

服务端加载
客户端正常

### 设备/浏览器

chrom

**Comment by chenjiahan** [comment]
unplugin-vue-components 会根据环境变量来判断是否为 SSR，如果是 SSR，就不会引入组件库的样式，避免此问题

参考：https://github.com/antfu/unplugin-vue-components/blob/413dc0c4a9729f53dd06f3e44a1016cfb0abe8a8/src/core/utils.ts#L13
