### ISSUE TITLE
[Bug Report] 路由跳转后！showConfirmDialog函数弹窗不生效！

### ISSUE THREAD

**Issue by qq517739813** [youzan/vant#11861]
### 重现链接

无

### Vant 版本

4.3.2

### 描述一下你遇到的问题。

在实现一个退出弹窗功能时，需要自定义样式所以挂载到了当前类
// 点击退出
const logOut = () => {
  showConfirmDialog({
    title: '提示',
    // teleport: '.userInfo',
    cancelButtonColor: 'red',
    closeOnPopstate: true,
    className: 'logOutDialog',
    message:
      '确定要退出登录吗？',
  })
    .then(() => {
      redirectLogin()
    }).catch((err) => { return err })
};。
但是一但路由改变，弹窗无法弹出

### 重现步骤

如上问题

### 设备/浏览器

Google游览器

**Comment by YH390389859** [comment]
我有遇到一个类似的，我是用的是showDialog，手动选择了teleport，在进入页面弹出以后再也无法打开弹窗
以下是错误代码
`showDialog({
    title:'标题',
    message:'错误信息',
    teleport:'#test'
})`
以上代码在我将teleport的值改为document.getElementById('test')后就没有上述问题了，你可以试试？

**Comment by qq517739813** [comment]
123

**Comment by qq517739813** [comment]
> 我有遇到一个类似的，我是用的是showDialog，手动选择了teleport，在进入页面弹出以后再也无法打开弹窗 以下是错误代码 `showDialog({ title:'标题', message:'错误信息', teleport:'#test' })` 以上代码在我将teleport的值改为document.getElementById('test')后就没有上述问题了，你可以试试？

我尝试你的方法把类改成id后生效了，但是如果我是通过获取类名的方式却报错了以下是报错代码
const handleDelgood = (id: string) => {
    showConfirmDialog({
        title: '删除',
        message:
            '确定删除投入品吗?',
        teleport: document.getElementsByClassName('addfarm')
    })
        .then(() => {
            // console.log('cancel');

            deleteActGoods({ id: [id] }).then(() => {
                init()
                showToast('删除成功')
            })
        })
        .catch(() => {
        });
}

**Comment by inottn** [comment]
`getElementsByClassName` 获取的是类数组

**Comment by HuangChengtuo** [comment]
https://vant-ui.github.io/vant/#/zh-CN/dialog#zai-beforerouteleave-li-diao-yong-dialog-wu-fa-zhan-shi  
大概率是 closeOnPopstate 导致的，我设置成 false 就正常了
