### ISSUE TITLE
swipe组件滑动时会触发item内的点击事件

### ISSUE THREAD

**Issue by Saber-tgb** [youzan/vant#1186]
What is the current behavior?
开启swipe 手势滑动时，滑动会同时触发内部自定义的点击事件

        <van-swipe v-if="selected===0" :autoplay="3000">
                   <van-swipe-item v-for="(item,index) in bannerList" :key="index">
                                <img :src="item.picUrl" @click="goAdvert(item.type, item.skipName, item.id, item.shopId)" :alt="item.name">
                            </van-swipe-item>
                   </van-swipe>
What is the expected behavior?
手势滑动时，不应同时触发内部点击

Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?
"vant": "^1.1.3",
"vue": "^2.5.13",

**Comment by xiaobingMa** [comment]
遇到了同样的问题  请问 是怎么解决的？？？

**Comment by xiaobingMa** [comment]
我发现了 是因为我用了fastclick插件的问题，  不知道该如何解决，郁闷

**Comment by xiaobingMa** [comment]
解决了

**Comment by xiaojia21190** [comment]
怎么解决的 @xiaobingMa

**Comment by youdianfan** [comment]
@xiaobingMa  请问上如何解决的

**Comment by wuxn** [comment]
> fastclick

请问是如何解决的呢

**Comment by qianzhaoy** [comment]
@youdianfan

**Comment by qianzhaoy** [comment]
![image](https://user-images.githubusercontent.com/14267409/48995396-a02ac480-f182-11e8-8d1f-e840fc06794a.png)

**Comment by SunXinFei** [comment]
同遇到这个问题

**Comment by iwen-pengh** [comment]
怎么解决 @有赞官方

**Comment by huozhenwei** [comment]
同问，我改用了这个插件 vue-concise-slider

**Comment by huozhenwei** [comment]
同问，我改用了这个插件 vue-concise-slider

**Comment by zhuogx** [comment]
@Saber-tgb 我用另一个轮播组件，也遇到了同样的问题。首先想到的是touch事件禁止冒泡，禁止冒泡后可以解决滑动时触发的点击事件，但是轮播图本身的点击事件捕获不到了。。。。
解决方法是绑定俩个事件：
handleTouchMove(e) {
  e.stopPropagation()
  this.moved = true
}
handleTouchEnd(e) {
  // 滑动时禁止冒泡，正常点击不会禁止
  if (this.moved) {
    this.moved = false
    e.stopPropagation()
  }
}

**Comment by jakietwo** [comment]
@zhuogx  我借用你的方法会将swipe-item的滚动都禁止了，然后我通过实现一个标志位可以解决
` handleTouchMove() {
      this.moved = true;
    },
`
`
  clickNoteItem() {
      if (this.moved === true) {
        this.moved = false;
        return;
      }
    },
`
只需要监听touchmove 和 click 就可以了

**Comment by jingguangyan** [comment]
@jakietwo  这种方式在ios端会有问题，滑动后需要点击两下才能响应

**Comment by GHUserZ** [comment]
@Saber-tgb 请问怎么解决的

**Comment by jingguangyan** [comment]
我给Table组件加一个 :key="show"， show 就是 控制Modal显示或隐藏的value




------------------ 原始邮件 ------------------
发件人: "ZhaoXiaoLin"<notifications@github.com>; 
发送时间: 2019年8月27日(星期二) 上午10:06
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "梧桐"<392151426@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [youzan/vant] swipe组件滑动时会触发item内的点击事件 (#1186)




@Saber-tgb 请问怎么解决的

**Comment by seric705** [comment]
为什么在touchmove时，用的是event.stopPropagation，而不是event.preventDefault();，导致拖动的过程中被触发click事件@chenjiahan

**Comment by kufei88** [comment]
我也遇到这个问题，换成其它组件了

**Comment by octopus3** [comment]
你们如果用vantUI建议看看vant官方文档 swiper组件文档有写
![image](https://user-images.githubusercontent.com/26821910/92465456-3073b580-f201-11ea-950d-8a2327e12d4d.png)

**Comment by ZhipengYang0605** [comment]
看了下帖子的回复，我也遇到这种问题，双击VanSwipe会触发@drag-end事件，我们项目里面没有依赖fastclick。"vant": "^4.0.9"版本

**Comment by Saber-tgb** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by zangbianxuegu** [comment]
我遇到的是，在进行了桌面端适配 https://vant-ui.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei 之后，滑动事件很容易触发点击事件，在拖动距离过小时。没有使用 fastclick。解决是增加了 touchstart touchend 事件，拖动开始记录位置，拖动结束计算移动的距离，小于特定的值才触发点击事件。

**Comment by Saber-tgb** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
