### ISSUE TITLE
vant/cli2.0封装组件库后导入到vue2项目中使用，toast被popup覆盖住了

### ISSUE THREAD

**Issue by wanshneyin** [youzan/vant#11876]
### Discussed in https://github.com/youzan/vant/discussions/11875

<div type='discussions-op-text'>

<sup>Originally posted by **wanshneyin** May 17, 2023</sup>
背景：vant/cli2.x二次封装vant组件库在vue2项目中使用（vue2项目cdn全局引入了vant）

问题描述：在vant/cli2.x封装的组件中按需引入vant组件库的组件，当我publish后，再将我二次封装的包引入到vue2项目中使用时，项目中之前使用的vant组件的样式发生了改变（比如：toast被popup覆盖住了，因为toast的z-index从2000开始了，而popup是2002）

报错：
![image](https://github.com/youzan/vant/assets/67151403/9fb1ea64-b380-4013-973c-fba866f86fa7)

</div>

**Comment by wanshneyin** [comment]
我知道原因是因为后面二次封装组件库中按需引入了popup组件，导致重新加载了popup组件，如果我在vant/cli的项目中build打包的时候将components的代码注释掉，就可以解决这个问题，想问下有没有更好的解决方法

**Comment by chenjiahan** [comment]
这个问题不属于 bug report，在讨论区沟通吧
