### ISSUE TITLE
filed组件中设置动态label-width的宽度

### ISSUE THREAD

**Issue by haohao809** [youzan/vant#11877]
### 这个功能解决了什么问题？

移动端的宽度本身不同，根据屏幕vm的宽度换算，现在的label-with仅支持固定值，不支持函数变量

### 你期望的 API 是什么样子的？

```
                <van-field
                  v-model="message"
                  rows="2"
                  autosize
                  label="审批建议:"
                  type="textarea"
                  placeholder="请输入"
                  maxlength="50"
                  show-word-limit
                  :label-width="px2vm(70)"
                />
const px2vm = (px: number) => {
  return (window.screen.width / 375) * px
}
```

**Comment by inottn** [comment]
`<van-field label-width="18vw" />` 这样不行吗

**Comment by haohao809** [comment]
> `<van-field label-width="18vw" />` 这样不行吗

不能写死的，根据屏幕宽度动态计算的

**Comment by inottn** [comment]
> > `<van-field label-width="18vw" />` 这样不行吗
> 
> 不能写死的，根据屏幕宽度动态计算的

不是很理解，vw 这个单位不就是根据屏幕宽度来的吗。

**Comment by haohao809** [comment]
> > > `<van-field label-width="18vw" />` 这样不行吗
> > 
> > 
> > 不能写死的，根据屏幕宽度动态计算的
> 
> 不是很理解，vw 这个单位不就是根据屏幕宽度来的吗。

是我想偏了，按照设计稿尺寸换算，可以直接设置vm
