### ISSUE TITLE
[Feature Request] 确保van-search__field样式不会被van-cell覆盖

### ISSUE THREAD

**Issue by fuhuabin** [youzan/vant#11881]
### What problem does this feature solve?

<img width="343" alt="image" src="https://github.com/youzan/vant/assets/9332729/020b18cb-da3c-43e7-b43b-7a30809a52d4">
我们项目是vite 4.3.8，vant 4.2.0，编译后的样式，存在上面的问题，.van-cell的样式在.van-search__field后加载，导致van-search__field的padding被覆盖从而样式异常了。为何不给.van-search__field加权重，确保它的优先级高于.van-cell呢？

### What does the proposed API look like?

.van-search__field.van-cell {}

**Comment by Mikasa33** [comment]
试了一下，没复现出来 😂

"vant": "^4.2.0",
"vite": "^4.3.8",

<img width="605" alt="image" src="https://github.com/youzan/vant/assets/29498153/803a2e43-95ea-432a-94b3-4c361074734f">

**Comment by chenjiahan** [comment]
> 为何不给.van-search__field加权重，确保它的优先级高于.van-cell呢

正常情况下，是不会出现顺序错误的，因为组件库内部已经对样式引入的 import 进行了排序。如果这种情况下有样式顺序错误，那么属于构建工具的问题，应该找构建工具处理。

在组件库内部不应该通过「增加权重」来覆盖样式，因为这会导致用户侧很难覆盖样式（用户侧需要使用更高的权重），这不是我们推荐的实践方式。
