### ISSUE TITLE
Field 当 type 是 number 时，输入框 type 仍然是 text

### ISSUE THREAD

**Issue by wensonsmith** [youzan/vant#11885]
### 重现链接

https://vant-contrib.gitee.io/vant/#/en-US/field

### Vant 版本

4.3.2

### 描述一下你遇到的问题。

<img width="1917" alt="image" src="https://github.com/youzan/vant/assets/2544185/9dfb54e1-8cfe-4047-bd5a-add0efb3b88d">

### 重现步骤

打开官网的示例， inspect 类型为 number 的 field

**Comment by inottn** [comment]
https://vant-contrib.gitee.io/vant/#/zh-CN/field#she-zhi-type-wei-number-hou-wei-shi-me-input-biao-qian-de-lei-xing-reng-wei-text
