### ISSUE TITLE
以前的产品 橱窗组件怎么没有了？

### ISSUE THREAD

**Issue by dzcms** [youzan/vant#119]
以前的产品 橱窗组件怎么没有了？

**Comment by chenjiahan** [comment]
@dzcms 我们目前正在对业务组件进行梳理和优化，并陆续将业务组件从 Captain 迁移到 Vant 中，因此暂时关闭了 Captain 的文档入口。如果你的项目中已经在使用 Captain，可以照常使用；如果你还未开始使用 Captain，请关注 Vant 后续的版本更新。
此外，你可以将你目前需要的组件列出来，我们会优先给予支持。

**Comment by psychokiller666** [comment]
@chenjiahan 有了NavBar组建，如果再有个底部的那种Tabbar和Infinite scroll，你就好了
