### ISSUE TITLE
使用van-config-provider中:theme="theme"报错

### ISSUE THREAD

**Issue by w-p-l** [youzan/vant#11907]
### 重现链接

无

### Vant 版本

"vant": "^4.4.0",

### 描述一下你遇到的问题。

vue3+ts中，使用van-config-provider中theme="light"可正常使用，但是使用v-bind绑定就会报错，打包也会报错

### 重现步骤

 <van-config-provider :theme="theme" ></van-config-provider>

<script setup lang="ts">
const theme = ref('light'); 
</script>

### 设备/浏览器

谷歌

**Comment by wjw-gavin** [comment]
是类型报错吗？

<img width="684" alt="image" src="https://github.com/youzan/vant/assets/19986739/9f465e5b-ed4e-4d3c-9b0c-95970cd4e5b3">

把类型加上试试呢？

```ts
import type { ConfigProviderTheme } from 'vant';

const theme = ref<ConfigProviderTheme>('light')
```
