### ISSUE TITLE
Stepper 步进器 多次触发事件

### ISSUE THREAD

**Issue by flygirls** [youzan/vant#1190]
```
<div class="reducePlus">
<van-stepper integer class="flex" v-model="indexmax" :change.stop="changeNum(1)" plus="plus()" />
</div>
<div>
<van-stepper integer class="flex" v-model="testnum" :change.stop="changeNum2(2)"/>
</div>
```
触发 一个 事件changeNum(1) 为什么 changeNum2(2)也触发   而且 plus  minus 事件也一样  购物车会循环出多个 步进器  用户修改数量后 肯定要 提交请求 更改购物车商品数量  我在 change 或者 plus 里 禁止 不掉 他的 增加  
问题一  多次触发 change plus minus  
问题二  怎么在change 或者其他事件里 禁止掉 他的增加或者修改

后来发现 任何一次 触发数据的变动 步进器的change 事件  会全部触发一遍 
触发change 事件 我都不知道 他触发出来的 是哪一个商品

**Comment by flygirls** [comment]
额  我以为  是我数据都在 一个 对象下 引起的。 但是 我上面 给的 例子 是 分开的 。现在已经 没问题了  怀疑 是编译的问题。  已经把商品 数组 从对象下 拆出 。不打算研究下去了 好了就好

**Comment by chenjiahan** [comment]
change 是事件，正确写法是 `@change="changeNum(1)"`

**Comment by flygirls** [comment]
@change  压根就不触发   大哥
