### ISSUE TITLE
[Bug Report]  DateTimePicker设置minDate和maxDate后调起日期插件展示的不是选中的值

### ISSUE THREAD

**Issue by hyacinth1210** [youzan/vant#11906]
### Reproduction Link

https://github.com/Pasoul/vant-bug

### Vant Version

2.12.29

### Describe the Bug

使用minDate和maxDate后，先设置开始时间再设置结束时间，再去操作开始时间，开始时间时间插件展示的时间不是当前时间（上次设置的时间）

### Reproduce Steps

使用minDate和maxDate后，先设置开始时间再设置结束时间，再去操作开始时间，开始时间时间插件展示的时间不是当前时间（上次设置的时间）

**Comment by chenjiahan** [comment]
![image](https://github.com/youzan/vant/assets/7237365/e4044338-002a-47bd-b63d-af458ce996c3)
