### ISSUE TITLE
androidn 8.0.0 webView  加载Vant4 空白

### ISSUE THREAD

**Issue by SunShRui** [youzan/vant#11905]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN

### Vant 版本

 "vant": "^4.3.1",

### 描述一下你遇到的问题。

小米5 系统8.0.0 webView 加载vant4界面空白，使用默认浏览器加载同样问题，并且使用默认浏览器加载https://vant-contrib.gitee.io/vant/#/zh-CN 同样空白，使用uc，加载正常。
webView 加载错误信息
I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token ?", source: http://lmbt.newzf.net/web/lmb/assets/vant-7b360585.js (1)

### 重现步骤

默认浏览器加载 https://vant-contrib.gitee.io/vant/#/zh-CN  就可以重现，

### 设备/浏览器

小米 8.0.0 webView 还有三星 盖世7

**Comment by chenjiahan** [comment]
看一下 Chrome 版本是多少呢？Vue 3 最低兼容 Chrome 53
