### ISSUE TITLE
【Picker】在使用option插槽时，如果未指定columns-field-names将会导致@confirm传参错误

### ISSUE THREAD

**Issue by qq326943819** [youzan/vant#11900]
### 重现链接

https://stackblitz.com/edit/vitejs-vite-x3urrg?file=src%2FApp.vue&terminal=dev

### Vant 版本

4.4.0

### 描述一下你遇到的问题。

在使用option插槽时，如果未指定columns-field-names将会导致@confirm传参错误

### 重现步骤

见链接

**Comment by inottn** [comment]
这个行为符合预期，和 option 插槽无关。

**Comment by qq326943819** [comment]
> 这个行为符合预期，和 option 插槽无关。

场景需要直接选择option对象作为值  所以会利用到confirm事件的selectedOptions，此时columns-field-names其实对于场景来说是没有作用的

**Comment by inottn** [comment]
> > 这个行为符合预期，和 option 插槽无关。
> 
> 场景需要直接选择option对象作为值 所以会利用到confirm事件的selectedOptions，此时columns-field-names其实对于场景来说是没有作用的

不太理解，columns-field-names 的作用是让 confirm 事件的 selectedOptions 的值正确，不然当你的数据结构和默认的不一致时要怎么知道选中的是哪个 option。

**Comment by qq326943819** [comment]
> 不太理解，columns-field-names 的作用是让 confirm 事件的 selectedOptions 的值正确，不然当你的数据结构和默认的不一致时要怎么知道选中的是哪个 option。

我以为是通过下标判断返回选中的option，因为场景没有使用v-model，而且直接需求返回的option，所以特意地没有去指定value的field

**Comment by inottn** [comment]
> > 不太理解，columns-field-names 的作用是让 confirm 事件的 selectedOptions 的值正确，不然当你的数据结构和默认的不一致时要怎么知道选中的是哪个 option。
> 
> 我以为是通过下标判断返回选中的option，因为场景没有使用v-model，而且直接需求返回的option，所以特意地没有去指定value的field

通过下标确认选中的 option 是不准确的，当你改变了传入 options 时，下标是有可能变化的。可以类比 vue 中 key 的作用。

**Comment by qq326943819** [comment]
> 通过下标确认选中的 option 是不准确的，当你改变了传入 options 时，下标是有可能变化的。可以类比 vue 中 key 的作用。

了解了，所以columns-field-names其实是指定options里的唯一值来做选中判断
