### ISSUE TITLE
[Bug Report] picker的双向数据绑定问题 选择数据会报错

### ISSUE THREAD

**Issue by huangwei-yan** [youzan/vant#11903]
### 重现链接

https://codesandbox.io/s/dreamy-darwin-5rbw0x?file=/src/App.vue

### Vant 版本

4.3.1

### 描述一下你遇到的问题。

表单搭配 picker 使用 picker里面的双向数据绑定有问题，选择数值后报错Cannot assign to read only property '0' of string '1' 只可以读无法修改

### 重现步骤

点击input 切换一个其他数据

### 设备/浏览器

Google，微信开发者工具

**Comment by inottn** [comment]
https://vant-ui.github.io/vant/#/zh-CN/picker#shuang-xiang-bang-ding

Picker 的 v-model 的值是一个数组。你应该在 confirm 事件中同步数据到表单。

**Comment by huangwei-yan** [comment]
> 如果是这样的话，那我双向数据绑定不就没有意义

**Comment by huangwei-yan** [comment]
> https://vant-ui.github.io/vant/#/zh-CN/picker#shuang-xiang-bang-ding
> 
> Picker 的 v-model 的值是一个数字组。你应该在确认事件中同步数据到表格。
如果是这样的话，那我双向数据绑定不就没有意义

**Comment by inottn** [comment]
> > https://vant-ui.github.io/vant/#/zh-CN/picker#shuang-xiang-bang-ding
> > Picker 的 v-model 的值是一个数字组。你应该在确认事件中同步数据到表格。
> > 如果是这样的话，那我双向数据绑定不就没有意义

嗯，是的。
