### ISSUE TITLE
[Bug Report] van-image 组件error 事件，有时候不触发，4.3.1 版本

### ISSUE THREAD

**Issue by leggod** [youzan/vant#11919]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-vcejqu?file=/src/App.vue

### Vant 版本

4.3.1

### 描述一下你遇到的问题。

在我的项目里，这两张图片，第一种会一直loading 状态，第二张会触发error 事件，很奇怪，我使用的nuxt3 最新版 ,vant 版本4.3.1

<van-image
      src="http://s3.xchuxing.com/xchuxing/ins/2022/11/12/1da54202211122202253349.png?imageView2/2/w/300/q/100"
      @error="onError"
    />
    <van-image
      src="http://s3.xchuxing.com/xchuxing/ins/2022/11/12/55778202211122229473662.png?imageView2/2/w/300/q/100"
      @error="onError"
    />

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

### 重现步骤

![image](https://github.com/youzan/vant/assets/20152324/c9581972-c7b2-448e-bf19-a1a2a19bfaab)

**Comment by zhousg** [comment]
@leggod 没有复现
<img width="634" alt="image" src="https://github.com/youzan/vant/assets/15833290/3c1f8bf2-c085-4625-9e31-46ca5202569a">

**Comment by leggod** [comment]
> @leggod 没有复现 <img alt="image" width="634" src="https://user-images.githubusercontent.com/15833290/241655435-3c1f8bf2-c085-4625-9e31-46ca5202569a.png">

https://codesandbox.io/s/vant-4-issue-template-forked-vcejqu?file=/src/App.vue  ,  从这里看，好像也是这样，第一张没显示，没进error, 一直显示 loading 图

**Comment by leggod** [comment]
找到问题了，我把图片在 放在 nuxt3 的 ，onMounted 里面 ，再给van-image  src 赋值， 就正常了，可能和ssr有关系
