### ISSUE TITLE
vant2 使用 postcss-px-to-viewport-8-plugin 会报错

### ISSUE THREAD

**Issue by webchenjie** [youzan/vant#11929]
### 重现链接

https://www.npmjs.com/package/postcss-px-to-viewport-8-plugin

### Vant 版本

2.12.54

### 描述一下你遇到的问题。

使用 postcss-px-to-viewport-8-plugin 会报以下的错

Syntax Error: Error: PostCSS plugin postcss-px-to-viewport requires PostCSS 8.

如果使用 postcss-px-to-viewport 就不会

### 重现步骤

把 postcss-px-to-viewport 插件换成 postcss-px-to-viewport-8-plugin 就会

**Comment by chenjiahan** [comment]
这个和 Vant 没关系，是插件版本与 PostCSS 大版本不一致导致的报错。
