### ISSUE TITLE
希望使用文档能有小版本选择

### ISSUE THREAD

**Issue by ouweicong** [youzan/vant#11936]
### What problem does this feature solve?

有时候下载的版本和官方文档最新版不匹配，某些功能文档上有，但是使用起来没有，找问题很难找到的。
例子：van-picker-group，v-model:active-tab，4.2.0是没有的，但是文档没有4.2.0对应的版本，使用起来就很麻烦

### What does the proposed API look like?

版本选择

**Comment by zhousg** [comment]
可以在 `props` 上补齐 `tag`

**Comment by chenjiahan** [comment]
嗯嗯，这个场景补齐 tag 就好，文档区分小版本没有必要，维护成本太高
