### ISSUE TITLE
Barrage 弹幕[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by maidij** [youzan/vant#11939]
### 重现链接

git@github.com:maidij/vue-element-admin-site.git

### Vant 版本

4.4.1

### 描述一下你遇到的问题。

获取弹幕组件的ref元素为null

### 重现步骤

获取弹幕组件的ref元素为null

### 设备/浏览器

谷歌

**Comment by zhousg** [comment]
确定使用了 vant ?
