### ISSUE TITLE
[Bug Report] swipe慢速滑动不超过一半的时候回弹，在谷歌浏览器本地调试的时候，模拟设备选iphone等机型ok，但是选择添加自定义设备的时候，不会回弹，慢拖拽也都会切换下一页

### ISSUE THREAD

**Issue by xiamengjun** [youzan/vant#11931]
### 重现链接

<van-swipe class="my-swipe" :autoplay="3000" indicator-color="white">   <van-swipe-item>1</van-swipe-item>   <van-swipe-item>2</van-swipe-item>   <van-swipe-item>3</van-swipe-item>   <van-swipe-item>4</van-swipe-item> </van-swipe>直接使用官方用法，只是需要在浏览器的自定义设备上调试重现

### Vant 版本

V4.4.1

### 描述一下你遇到的问题。

 swipe慢速滑动不超过一半的时候回弹，在谷歌浏览器本地调试的时候，模拟设备选iphone等机型ok，但是选择添加自定义设备的时候，不会回弹，慢拖拽也都会切换下一页

### 重现步骤

1、安装vant
2、vue项目页面引用swipe组件
3、本地项目运行，谷歌浏览器打开，切换到移动端模式，选择自定义设备

### 设备/浏览器

goole浏览器的移动设备模拟

**Comment by inottn** [comment]
切换由拖拽距离和速度决定。慢是相对的，在浏览器调试时，可能相同时间滑动的距离更长。你可以在拖拽时多停留几秒试试。

**Comment by xiamengjun** [comment]
请问能否暴露出来一个参数，让我们自己去定义这个滑动的快慢呢？因为可能不同系统自己的产品对这个灵敏度要求不一样，现在是因为我们那个移动端的屏幕尺寸比较大，确实我自己觉得我是慢划的（就是操作了同样的速度，在iphone手机上会回弹，在我们这个自定义设备上就会被认为是快速滑动，只慢慢拖拽了一点点距离就已经切换了，我需要拖拽结束，按你说的，停留一会儿才会回弹）

**Comment by inottn** [comment]
> 请问能否暴露出来一个参数，让我们自己去定义这个滑动的快慢呢？因为可能不同系统自己的产品对这个灵敏度要求不一样，现在是因为我们那个移动端的屏幕尺寸比较大，确实我自己觉得我是慢划的（就是操作了同样的速度，在iphone手机上会回弹，在我们这个自定义设备上就会被认为是快速滑动，只慢慢拖拽了一点点距离就已经切换了，我需要拖拽结束，按你说的，停留一会儿才会回弹）

这个还需要评估一下，短时间内应该不会支持。

**Comment by xiamengjun** [comment]
那能否帮忙指导一下，如果去改源码，这个判断手指开始拖拽以及离开的时间和拖拽距离的计算比例，相关代码在哪个文件，涉及哪几个方法函数，能帮忙粘一下或者截图么

**Comment by xiamengjun** [comment]
那能否帮忙指导一下，如果去改源码，这个判断手指开始拖拽以及离开的时间和拖拽距离的计算比例，相关代码在哪个文件，涉及哪几个方法函数，能帮忙粘一下或者截图么

**Comment by inottn** [comment]
> 那能否帮忙指导一下，如果去改源码，这个判断手指开始拖拽以及离开的时间和拖拽距离的计算比例，相关代码在哪个文件，涉及哪几个方法函数，能帮忙粘一下或者截图么

https://github.com/youzan/vant/blob/63a8e4443e7cfaa99fa8c24f587c6bf80207d656/packages/vant/src/swipe/Swipe.tsx#LL351C1-L352C74
