### ISSUE TITLE
vant-search组件的 clearable 不生效, 无法清空输入框内容

### ISSUE THREAD

**Issue by Xshaodong2018** [youzan/vant#11949]
### 重现链接

无

### Vant 版本

4.4.1

### 描述一下你遇到的问题。

vant-search组件的 clearable 不生效, 无法清空输入框内容

### 重现步骤

vant-search组件的 clearable 不生效, 无法清空输入框内容

### 设备/浏览器

ios

**Comment by inottn** [comment]
参考 https://vant-ui.github.io/vant/#/zh-CN/search#zai-zhuo-mian-duan-dian-ji-qing-chu-an-niu-wu-xiao
如果没有解决，请提供复现链接

**Comment by jsoncode** [comment]
同样遇到了
```
<van-search
    v-model="searchValue"
    clearable
    clear-trigger="always"
    @clear="()=>onClear()"
/>
```
onClear并未触发

**Comment by jsoncode** [comment]
我找到了一个解决方案：
```
<van-search
    v-model="searchValue"
    clearable
    clear-trigger="always"
    @clear="()=>onClear()"
>
    <template #right-icon v-if="searchValue">
        <van-icon name="cross" @click="()=>onClear()" />
    </template>
</van-search>
```

**Comment by inottn** [comment]
> 同样遇到了
> 
> ```
> <van-search
>     v-model="searchValue"
>     clearable
>     clear-trigger="always"
>     @clear="()=>onClear()"
> />
> ```
> 
> onClear并未触发

clear 的触发时机是 touchstart

**Comment by GGupzHH** [comment]
这bug还在
