### ISSUE TITLE
datePicker4.0版本无法选择年月日时分秒

### ISSUE THREAD

**Issue by pitilesszgw** [youzan/vant#11944]
### 这个功能解决了什么问题？

datePicker4.0版本无法选择年月日时分秒 4.0以下是可以的 根据type 4.0中columns-type无法定义年月日时分秒

### 你期望的 API 是什么样子的？

columns-type可以为year month day hour minute second

**Comment by inottn** [comment]
参考[这个](https://vant-ui.github.io/vant/#/zh-CN/release-note-v4#picker-zu-jian-chong-gou)，可以使用 PickerGroup 组件实现
