### ISSUE TITLE
[Bug Report] row和col组件在多行展示时，最后一行的宽度问题

### ISSUE THREAD

**Issue by cunzaizhuyi** [youzan/vant#11948]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-v77vm3?file=/src/App.vue

### Vant 版本

4.4.1

### 描述一下你遇到的问题。

row和col组件在多行展示时的宽度问题；

第二行的内容宽度50%，第一行的两个的内容宽度其实不足50%；

导致没有对齐。

### 重现步骤

如链接所示

**Comment by inottn** [comment]
参考这个 https://github.com/youzan/vant/discussions/11934
