### ISSUE TITLE
[Bug Report] vant4 v4.3.2 在IOS 12.4.9  上无法访问，应用白屏

### ISSUE THREAD

**Issue by mingyong-g** [youzan/vant#11958]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/faq

### Vant 版本

vant4 v4.3.2

### 描述一下你遇到的问题。

整个UI库在 IOS 12.4.9上无法访问，对应safari 版本为12.1.2，现象为应用白屏。

### 重现步骤

通过IOS 12 设备访问vant4 文档地址就可重现，
vant3 版本的文档地址是可以通过 IOS 12 设备（同一台设备）访问的，基于vant3 开发的应用也是可以正常访问的

### 设备/浏览器

IOS12.4.9  / safari  12.1.2

**Comment by inottn** [comment]
引用了 vant4 组件的应用会白屏吗

**Comment by inottn** [comment]
有报错的信息吗

**Comment by mingyong-g** [comment]
> 有报错的信息吗

我集成vConsole 但是没有发现任何报错日志。
我通过esbuild 将目标环境指定为ios12 ，应用可以访问了。
为了确认是否为vant4 引发的白屏问题，我准备在纯净环境里安装vant4进行验证。
不过我依然疑惑的是vant4 的官方文档为什么也不能在ios12 的设备上访问呢？

**Comment by inottn** [comment]
> > 有报错的信息吗
> 
> 我集成vConsole 但是没有发现任何报错日志。 我通过esbuild 将目标环境指定为ios12 ，应用可以访问了。 为了确认是否为vant4 引发的白屏问题，我准备在纯净环境里安装vant4进行验证。 不过我依然疑惑的是vant4 的官方文档为什么也不能在ios12 的设备上访问呢？

文档使用了 vite 构建，参考 vite 的[兼容性](https://cn.vitejs.dev/guide/build.html#browser-compatibility)。

**Comment by mingyong-g** [comment]
的确是 vite 的兼容性问题，感谢提供的解决方向！

**Comment by TzcTzcTzc** [comment]
> 

你好 我遇到相同的问题 最后怎么解决的 谢谢

**Comment by mingyong-g** [comment]
> > 
> 
> 你好 我遇到相同的问题 最后怎么解决的 谢谢

如前面所述，这个是vite 的兼容性问题，[vite 的兼容性说明](https://cn.vitejs.dev/guide/build.html#browser-compatibility)  可以参考官方说明通过esbuild解决
