### ISSUE TITLE
[Feature Request] Collapse 手风琴模式 优化

### ISSUE THREAD

**Issue by heyi-core** [youzan/vant#11956]
### 这个功能解决了什么问题？

点击van-collapse-item后, 上面展开的van-collapse-item会收缩当前点击的van-collapse-item
觉得非常不舒服

### 你期望的 API 是什么样子的？

正常情况下 应该是: 上面展开的van-collapse-item会自动往下收缩 并 固定当前点击的van-collapse-item

**Comment by inottn** [comment]
如果页面已经滚动到顶部，要怎么实现这个效果呢。或许你可以提供几个实现了这个效果的 UI 库供参考。

**Comment by chenjiahan** [comment]
我认为目前的交互没问题，"往下收缩" 需要滚动整个页面了，反而会更奇怪（而且很难实现）
