### ISSUE TITLE
[Bug Report] nuxt3中的vant，生产环境和开发环境，构建出来的css样式错乱问题

### ISSUE THREAD

**Issue by Maxbsy** [youzan/vant#11950]
### 重现链接

暂无复现链接

### Vant 版本

4.2.0

### 描述一下你遇到的问题。

文档地址：https://vant-contrib.gitee.io/vant/#/zh-CN/quickstart

开发环境：
<img width="1063" alt="image" src="https://github.com/youzan/vant/assets/50442277/72e5fe0a-7acf-40ba-aa3b-efa9c864312e">
<img width="288" alt="image" src="https://github.com/youzan/vant/assets/50442277/62201d56-2a08-4afc-9bb9-d0bd4bfc13aa">

生产环境：
<img width="1051" alt="image" src="https://github.com/youzan/vant/assets/50442277/3269a0d1-13c7-431a-8126-0ed3b0f226db">
<img width="283" alt="image" src="https://github.com/youzan/vant/assets/50442277/f8a7f996-7e94-4462-96e3-b4d0698af12d">

注意：开发环境，生产环境，右边的样式顺序都倒过来了

### 重现步骤

`<van-field
            v-model.trim="loginInfo.userName"
            class="field-class"
            placeholder="请输入手机号/账号"
            type="text"
            maxlength="18"
            :formatter="formatter.trim"
          >
            <template #label>
              <icon-font class="field-left-icon" type="icon-iphone" />
            </template>
          </van-field>`

### 设备/浏览器

Chrome
```[tasklist]
### Tasks
```

**Comment by Maxbsy** [comment]
<van-field
            v-model.trim="loginInfo.userName"
            class="field-class"
            placeholder="请输入手机号/账号"
            type="text"
            maxlength="18"
            :formatter="formatter.trim"
          >
            <template #label>
              <icon-font class="field-left-icon" type="icon-iphone" />
            </template>
          </van-field>

**Comment by Maxbsy** [comment]
`<van-field
            v-model.trim="loginInfo.userName"
            class="field-class"
            placeholder="请输入手机号/账号"
            type="text"
            maxlength="18"
            :formatter="formatter.trim"
          >
            <template #label>
              <icon-font class="field-left-icon" type="icon-iphone" />
            </template>
          </van-field>`

**Comment by Maxbsy** [comment]
我这个问题和#11049 这个里面的大致相同，但不同的点是，我这个是nuxt3，而#11049 问题中没有nuxt3的解决方案

**Comment by chenjiahan** [comment]
Nuxt 3 也是基于 Vite 构建的，问题的原因类似。

首先需要明确的是，这是框架层的问题，不是组件层面的问题，即使你不是用 Vant，引用其他组件，也一样会碰到类似的问题。

具体到解决方式，在这几个 issue 中都有一些可行的方案/探讨：

- https://github.com/vant-ui/vant-nuxt/issues/19
- https://github.com/youzan/vant/issues/11049
- https://github.com/youzan/vant/issues/10953
