### ISSUE TITLE
[Bug Report] 无法关闭弹出的日期控件

### ISSUE THREAD

**Issue by e33693288** [youzan/vant#11951]
### 重现链接

http://vuedemo.2qmall.com/Vant_Calendar.html

### Vant 版本

https://fastly.jsdelivr.net/npm/vant@4/lib/vant.min.js

### 描述一下你遇到的问题。

能正常弹出，但点击日期控件后无法关闭，只会闪一下

### 重现步骤

点击弹出日期控件后，选择日期无法关闭日期控件

### 设备/浏览器

360，QQ浏览器

**Comment by e33693288** [comment]
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, viewport-fit=cover" />




  <title>VantDemo calendar</title>



</head>

<body>
  
  <link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/vant@4/lib/index.css" />

  
  <script src="https://fastly.jsdelivr.net/npm/vue@3"></script>
  <script src="https://fastly.jsdelivr.net/npm/vant@4/lib/vant.min.js"></script>


  <div id="app">

    {{ date }}
    {{ show }}


    <van-cell title="选择日期区间" :value="date" @click="show = true" />
    <van-calendar v-model:show="show" @close="onClose" @confirm="onConfirm"  />




  </div>


  <script>

    const app = Vue.createApp({
      data() {
        return {
          date: ''
          , show: false,
        }
      },
      methods: {
        formatDate(date) {
          return `${date.getMonth() + 1}-${date.getDate()}`;
        },

        onConfirm(date) {
          this.show = false;
          this.date = this.formatDate(date)
          console.log('show', this.show)
        },
        onClose() {
          this.show = false;
          console.log('onClose', this.show)
        }
      },

    })
    app.use(vant);

    app.use(vant.Lazyload);
    vant.showToast('hello Vant');
    app.mount('#app')
  </script>

</body>

</html>

**Comment by e33693288** [comment]
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, viewport-fit=cover" />




  <title>VantDemo calendar</title>



</head>

<body>
  
  <link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/vant@4/lib/index.css" />

  
  <script src="https://fastly.jsdelivr.net/npm/vue@3"></script>
  <script src="https://fastly.jsdelivr.net/npm/vant@4/lib/vant.min.js"></script>


  <div id="app">

    {{ date }}
    {{ show }}


    <van-cell title="选择日期区间" :value="date" @click="show = true" />
    <van-calendar v-model:show="show" @close="onClose" @confirm="onConfirm"  />




  </div>


  <script>

    const app = Vue.createApp({
      data() {
        return {
          date: ''
          , show: false,
        }
      },
      methods: {
        formatDate(date) {
          return `${date.getMonth() + 1}-${date.getDate()}`;
        },

        onConfirm(date) {
          this.show = false;
          this.date = this.formatDate(date)
          console.log('show', this.show)
        },
        onClose() {
          this.show = false;
          console.log('onClose', this.show)
        }
      },

    })
    app.use(vant);

    app.use(vant.Lazyload);
    vant.showToast('hello Vant');
    app.mount('#app')
  </script>

</body>

</html>

**Comment by inottn** [comment]
参考[这个](https://cn.vuejs.org/guide/essentials/component-basics.html#dom-template-parsing-caveats)，你需要了解在 DOM 中写模板和 SFC 的不同。

简而言之，你可以将标签闭合解决这个问题。

**Comment by e33693288** [comment]
> 参考[这个](https://cn.vuejs.org/guide/essentials/component-basics.html#dom-template-parsing-caveats)，你需要了解在 DOM 中写模板和 SFC 的不同。
> 
> 简而言之，你可以将标签闭合解决这个问题。

感谢解答，方案可行，问题已解决，谢谢！
