### ISSUE TITLE
 van-cell    的  is-link 突然不显示右箭头

### ISSUE THREAD

**Issue by yin450561200** [youzan/vant#11955]
### 重现链接

无

### Vant 版本

1.10.9

### 描述一下你遇到的问题。

 van-cell    的  is-link 突然不显示右箭头，项目一直在线上，没动过任何代码。

### 重现步骤

 van-cell    的  is-link 突然不显示右箭头，项目一直在线上，没动过任何代码。

### 设备/浏览器

微信小程序

**Comment by inottn** [comment]
在 [vant-weapp](https://github.com/youzan/vant-weapp) 这里反馈
