### ISSUE TITLE
[Feature Request] vate希望能允许0分

### ISSUE THREAD

**Issue by luffywz** [youzan/vant#11968]
### 这个功能解决了什么问题？

如题，现在的评分组件vate一旦选择后就无法归零，只能通过其它方式置零

### 你期望的 API 是什么样子的？

x

**Comment by zhousg** [comment]
是 Rate 评分 组件吗？@chenjiahan 是可以增加一个选中点击取消评分功能，参考 https://ant.design/components/rate-cn

**Comment by inottn** [comment]
嗯，这个需求比较常见 🤔，之前本地有临时实现过，感觉可以加。
