### ISSUE TITLE
van-pull-refresh下拉刷新标签有个问题

### ISSUE THREAD

**Issue by VICTORYGS** [youzan/vant#1196]
凡是下拉就会刷新 ，也不看看滚动条是不是在最上面额..
<van-pull-refresh v-model="isLoading" @refresh="">
refresh不写东西 下拉 顶部照样出现加载图标
想自己抓滚动条位置，去控制是否执行 刷新的想法也落空了

**Comment by chenjiahan** [comment]
能否提供一个复现问题的 jsfiddle?

**Comment by zknbo** [comment]
van-pull-refresh  和 van-list 组合使用刷新 是在一个div 的下面 感觉很不好  能否解决
