### ISSUE TITLE
vant 组件兼容性

### ISSUE THREAD

**Issue by liuchunyong1996** [youzan/vant#11967]
### 重现链接

本地开发，还未上线

### Vant 版本

2.10.10

### 描述一下你遇到的问题。

vant 分页组件，在ios手机上，浏览器开启无痕模式，点击分页组件跳转页码后样式丢失，导致页码看不见了

### 重现步骤

vant 分页组件，在ios手机上，浏览器开启无痕模式，点击分页组件跳转页码后样式丢失，导致页码看不见了

### 设备/浏览器

ios，自带浏览器开启无痕模式

**Comment by inottn** [comment]
@chenjiahan 发现缺一个 2.x 的 label

**Comment by liuchunyong1996** [comment]
手机问题

**Comment by chenjiahan** [comment]
> @chenjiahan 发现缺一个 2.x 的 label

@inottn 加好咯

![image](https://github.com/youzan/vant/assets/7237365/d124dd01-858f-4747-9db9-9c006f34b253)
