### ISSUE TITLE
IndexBar使用后，页面滚动的时候右边索引没有随着变化；而且点击右侧索引，页面虽然滚动了，但是页面显示不了当前激活的索引名

### ISSUE THREAD

**Issue by fangwei0701** [youzan/vant#11977]
### 重现链接

暂无

### Vant 版本

4.5.0

### 描述一下你遇到的问题。

源码：
`<template>   <div class="location">     <van-nav-bar       title="位置"       left-arrow       z-index="1000"       :fixed="true"       :placeholder="true"     />     <section class="section">       <van-index-bar :index-list="IndexList.list" :sticky-offset-top="46">         <div v-for="item in dataList.list" :key="item.lable">           <van-index-anchor :index="item.lable" />           <van-cell v-for="(v, i) in item.list" :key="i" :title="v" />         </div>       </van-index-bar>     </section>   </div> </template>  <script lang="ts" setup> import { reactive } from "vue"; // 索引列表 const IndexList = reactive({   list: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K"], }); // 索引数据 const dataList = reactive({   list: [     {       lable: "A",       list: ["文本", "文本", "文本", "文本", "文本", "文本1"],     },     {       lable: "B",       list: ["文本", "文本", "文本", "文本", "文本", "文本2"],     },     {       lable: "C",       list: ["文本", "文本", "文本", "文本", "文本", "文本3"],     },     {       lable: "D",       list: ["文本", "文本", "文本", "文本", "文本", "文本4"],     },     {       lable: "E",       list: ["文本", "文本", "文本", "文本", "文本", "文本5"],     },     {       lable: "F",       list: ["文本", "文本", "文本", "文本", "文本", "文本6"],     },     {       lable: "G",       list: ["文本", "文本", "文本", "文本", "文本", "文本7"],     },     {       lable: "H",       list: ["文本", "文本", "文本", "文本", "文本", "文本8"],     },     {       lable: "I",       list: ["文本", "文本", "文本", "文本", "文本", "文本9"],     },     {       lable: "J",       list: ["文本", "文本", "文本", "文本", "文本", "文本10"],     },     {       lable: "K",       list: ["文本", "文本", "文本", "文本", "文本", "文本11"],     },   ], }); </script>  <style lang="scss" scoped> .section {   min-height: calc(100vh - var(--van-nav-bar-height));   background: linear-gradient(#fafafa, #f0f0f0);   box-sizing: border-box; } </style>`

### 重现步骤

无

### 设备/浏览器

谷歌浏览器：113.0.5672.93
```[tasklist]
### Tasks
```

**Comment by HUANGDIS** [comment]
同遇到这个问题，有好的解决办法吗
