### ISSUE TITLE
[Feature Request] 请在此填写标题

### ISSUE THREAD

**Issue by Youky1** [youzan/vant#11975]
### 这个功能解决了什么问题？

Swipe组件设置自定义滑块大小后，滑动至第N个swipe-item时会滑到贴边的状态。
希望提供设置元素在滑动后停留位置的API（如居中）

### 你期望的 API 是什么样子的？

```html
<swipe :width="80" position="center"></swipe>
```

**Comment by inottn** [comment]
Swipe 目前的设计是比较轻量的，需要评估下提供相应功能的成本。

**Comment by chenjiahan** [comment]
是的，Swipe 应该不会支持这个功能，参考这个 FAQ：

![image](https://github.com/youzan/vant/assets/7237365/b67819ad-1183-4c84-a0cd-33bb4798d17f)
