### ISSUE TITLE
[Bug Report] 按照文档，使用默认命令快速生成的@vant/cli 升级到最新版本后，项目无法启动

### ISSUE THREAD

**Issue by GuangChao-Yu** [youzan/vant#11986]
### 重现链接

公司内部项目无法提供

### Vant Cli 版本

6.1.0

### 描述一下你遇到的问题。

![image](https://github.com/youzan/vant/assets/25799270/def2ee60-ece4-4104-a7b9-71a6b264af67)
通过快速上手的 命令安装后，发现配置不满足，
于是升级了@vant/cli的版本 到最新，
启动项目后，项目报错
![image](https://github.com/youzan/vant/assets/25799270/b060f25d-e074-40b0-b850-3d09d77011c0)

### 重现步骤

1. 使用 yarn create vant-cli-app
2. npm install 
3. npm run dev (项目正常）
4.npm install @vant/cli@latest --save-dev  (更新到最新版本)
5.npm run dev (项目报错)

**Comment by chenjiahan** [comment]
是的，Vue 2 需要使用 @vant/cli 2.x 版本
