### ISSUE TITLE
[Feature Request] dropdown-menu是否考虑增加placeholder,fixed

### ISSUE THREAD

**Issue by AnLiBoBo** [youzan/vant#11997]
### 这个功能解决了什么问题？

大部分使用场景中,dropdown-menu可能都会在最上方,并且下面是个列表,那么是不是可以跟navbar一样,增加fixed和palceholder属性

### 你期望的 API 是什么样子的？

```html
<van-dropdown-menu fixed placeholder>
</van-dropdown-menu>
```

**Comment by PestLee** [comment]
placeholder有必要加，当界面位置没有那么多，只能放一个dropdown-menu时，而它还是必填项，且不能由你给用户一个默认值，这时就需要有一个让用户看到，这里有一项需要去选择的提醒。
