### ISSUE TITLE
radio 单选，在safari浏览器(包含苹果手机微信)下显示不正常

### ISSUE THREAD

**Issue by abitnt** [youzan/vant#1199]
radio 单选，在safari浏览器(包含苹果手机微信)下显示不正常

https://www.youzanyun.com/zanui/vant#/zh-CN/radio

**Comment by chenjiahan** [comment]
能否提供一下截图？

**Comment by abitnt** [comment]
不懂上传图片。安装一个safari浏览器，打开 https://www.youzanyun.com/zanui/vant#/zh-CN/radio，就看到打勾部分没有显示出来了。

**Comment by chenjiahan** [comment]
未复现这个问题，vant 中的 Iconfont 使用 ttf 格式，在移动端浏览器都能正常展示
