### ISSUE TITLE
[Bug Report] Tabs 在Swipeable模式下，搭配popup会有宽度问题

### ISSUE THREAD

**Issue by atom-git** [youzan/vant#11999]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-2hh6px?file=/src/App.vue

### Vant 版本

4.5.0

### 描述一下你遇到的问题。

tabs组件为swipeable模式时，其中的popup弹出的picker宽度计算错误

### 重现步骤

点击弹出后弹出窗显示为两个tab加起来的宽度

### 设备/浏览器

chrome113

**Comment by inottn** [comment]
使用 teleport 属性，例如 teleport="body"
