### ISSUE TITLE
van-field 的自动适配高度无法设置最大高度和最小高度，一直报错

### ISSUE THREAD

**Issue by jieruian** [youzan/vant#11996]
### 重现链接

暂无

### Vant 版本

2.12.54

### 描述一下你遇到的问题。

 <van-field  autosize="{{{maxHeight: 80, minHeight: 50}}}" type="textarea" rows="1" v-model="sendMessage"  placeholder="请输入问题..." />
按照设置配置了autosize后面的参数，只要配置后面的参数，直接开始报错
<img width="985" alt="image" src="https://github.com/youzan/vant/assets/16176391/27b88c1e-b3c6-4022-b79e-3c595d6fa03d">

### 重现步骤

按照设置配置了autosize后面的参数，只要配置后面的参数，直接开始报错

### 设备/浏览器

mac和iPhone

**Comment by inottn** [comment]
<img width="1420" alt="image" src="https://github.com/youzan/vant/assets/18509404/88cba527-a5a0-4f3d-b401-ff4d3e216cda">
我看这个提示说的挺清楚了，按这个修改就行了。
