### ISSUE TITLE
[Bug Report] LazyLoad每张图片请求两次

### ISSUE THREAD

**Issue by cunzaizhuyi** [youzan/vant#12004]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/lazyload#ji-chu-yong-fa

### Vant 版本

4.5

### 描述一下你遇到的问题。

<img width="1737" alt="image" src="https://github.com/youzan/vant/assets/20167257/7e5ccd54-9be8-48bc-8e1d-f53e33a2327c">

### 重现步骤

打开devtools， 在示例页面往下滚动，每张图片都是网络请求两次。

这个问题是已知的吗？是不可避免的吗？

**Comment by inottn** [comment]
LazyLoad 只是基于 vue-lazyload 封装了一层。

加载流程如下：
LazyLoad 会通过 new Image 的方式异步加载图片（第一次加载），当加载完成后将 img 元素的 src 属性替换为对应的值（这里可能会发生第二次加载）。

如流程所示，如果浏览器能正常的缓存图片的话（这可能和开发者模式下是否禁用了缓存或其它原因有关），则不会发生二次加载。你可以在 Safari 中也试试。

后续有任何结论，欢迎在此继续探讨。

**Comment by cunzaizhuyi** [comment]
确实开了disable cache，疏忽这个了。

一般cdn图片都会设置强缓存，所以第二次都会从客户端本地直接取到资源。

关了😁
