### ISSUE TITLE
van-search在van-action-sheet中时，实现自动聚焦后键盘会将van-action-sheet顶上去

### ISSUE THREAD

**Issue by pitilesszgw** [youzan/vant#12000]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-van-search-focus-6t7cy9

### Vant 版本

4.5.0

### 描述一下你遇到的问题。

pc端访问没问题，iOS移动端上出现该bug，键盘将van-action-sheet顶上去,用定时器focus将直接失效

### 重现步骤

点击按钮
弹窗被顶上去

### 设备/浏览器

ios11

**Comment by inottn** [comment]
这和 vant 组件无关，或许是一个由 IOS 系统引发的问题。

可以简单的描述一下问题的原因，你可以根据原因选择合适的解决方法。

当输入框的字体大小小于 16px，在 IOS 上，会缩放任何获得焦点的输入框。缩放后的视图会产生一定的偏移，正如你问题描述的那样。

这样看解决方法有两种，一是使用 meta 标签控制缩放，二是将输入框的字体大小设为 16px。

**Comment by pitilesszgw** [comment]
@inottn 输入框字体大小改为12没有用，这个跟字体大小没有关系吧。这边的问题场景就是van-search由van-action-sheet包裹，点击页面某个按钮时期望是van-action-sheet显示并且van-search被聚焦，但是出现的问题是整个van-action-sheet被键盘顶上去了，pc端上测试是没问题的，目前用的手机为ios，出现以上的问题

**Comment by inottn** [comment]
> @inottn 输入框字体大小改为12没有用，这个跟字体大小没有关系吧。这边的问题场景就是van-search由van-action-sheet包裹，点击页面某个按钮时期望是van-action-sheet显示并且van-search被聚焦，但是出现的问题是整个van-action-sheet被键盘顶上去了，pc端上测试是没问题的，目前用的手机为ios，出现以上的问题

参考回复【二是将输入框的字体大小设为 16px】，你设成 12 当然没有用了。

**Comment by inottn** [comment]
你也可以在 focus 后，通过 `window.scrollTo` 重置页面滚动行为。

但这个行为是 ios 原生行为，需要你自行编写逻辑控制。

**Comment by pitilesszgw** [comment]
> 你也可以在 focus 后，通过 `window.scrollTo` 重置页面滚动行为。
> 
> 但这个行为是 ios 原生行为，需要你自行编写逻辑控制。

设置的是12px
设置window.scroll之前也有试过 但是效果都是一样
await nextTick();
  vanSearchRef.value.focus();
  window.scroll(0, 0);
  感觉是整个webview被顶上去了

**Comment by inottn** [comment]
> > 你也可以在 focus 后，通过 `window.scrollTo` 重置页面滚动行为。
> > 但这个行为是 ios 原生行为，需要你自行编写逻辑控制。
> 
> 设置的是12px 设置window.scroll之前也有试过 但是效果都是一样 await nextTick(); vanSearchRef.value.focus(); window.scroll(0, 0); 感觉是整个webview被顶上去了

focus 和滚动是有一定时间间隔的，在定时器中执行 `window.scroll` 试试。

**Comment by pitilesszgw** [comment]
> > > 你也可以在 focus 后，通过 `window.scrollTo` 重置页面滚动行为。
> > > 但这个行为是 ios 原生行为，需要你自行编写逻辑控制。
> > 
> > 
> > 设置的是12px 设置window.scroll之前也有试过 但是效果都是一样 await nextTick(); vanSearchRef.value.focus(); window.scroll(0, 0); 感觉是整个webview被顶上去了
> 
> focus 和滚动是有一定时间间隔的，在定时器中执行 `window.scroll` 试试。

在定时器中执行window.scroll确实可以解决webview被顶上去的问题，但是体验上不是很好，会有一闪而过的一个效果，虽然这个效果很短暂，还有更好的方案么

**Comment by inottn** [comment]
> > > > 你也可以在 focus 后，通过 `window.scrollTo` 重置页面滚动行为。
> > > > 但这个行为是 ios 原生行为，需要你自行编写逻辑控制。
> > > 
> > > 
> > > 设置的是12px 设置window.scroll之前也有试过 但是效果都是一样 await nextTick(); vanSearchRef.value.focus(); window.scroll(0, 0); 感觉是整个webview被顶上去了
> > 
> > 
> > focus 和滚动是有一定时间间隔的，在定时器中执行 `window.scroll` 试试。
> 
> 在定时器中执行window.scroll确实可以解决webview被顶上去的问题，但是体验上不是很好，会有一闪而过的一个效果，虽然这个效果很短暂，还有更好的方案么

你可以在 stackoverflow 中寻求更多解决方法

**Comment by pitilesszgw** [comment]
> 

好的 谢谢🙏
