### ISSUE TITLE
Stepper 在 iPhone X 中点击输入框会唤起键盘，但是修改数值不生效

### ISSUE THREAD

**Issue by FangKaimo** [youzan/vant#12027]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/stepper

### Vant 版本

4.0.10

### 描述一下你遇到的问题。

Stepper 在 iPhone X 中点击输入框会唤起键盘，无法修改输入框数值，左右加减按钮可以修改

### 重现步骤

在iPhone X Safari 浏览器中使用Stepper会复现

### 设备/浏览器

iPhone X

**Comment by zhousg** [comment]
在iPhone X Safari 浏览器中使用Stepper会复现，未复现呢

**Comment by FangKaimo** [comment]
确实，在我的项目中复现了，

**Comment by FangKaimo** [comment]
且没有看到光标，点击键盘也没有反应

**Comment by FangKaimo** [comment]
你好，我换了另一种写法，谢谢你的回复
