### ISSUE TITLE
[Bug Report] IOS 17环境下多个组件异常无法正常使用

### ISSUE THREAD

**Issue by zy94xhn** [youzan/vant#12028]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/tree-select

### Vant 版本

4

### 描述一下你遇到的问题。

无法切换选项。
无联动效果，
包括pop弹窗偶尔出现无法关闭的结果

### 重现步骤

1. 点击组件
2. 卡住

### 设备/浏览器

iphone 14 pro max，IOS 17.2

**Comment by chenjiahan** [comment]
IOS 17 还是 beta 版本吧，可能会有很多系统级的 bug

**Comment by zy94xhn** [comment]
@chenjiahan 是的，不只是vant出现问题了，我发现我用IOS 17 beta2版本访问多个网站都出现了颜色反转的问题。应该是beta版本的问题，我在16、15版本的IOS中均未出现这个问题
