### ISSUE TITLE
[Bug Report] 通过@touchstart 事件打开的 van-popup，会自动执行 onClose 导致 popup 立即关闭

### ISSUE THREAD

**Issue by zaxlct** [youzan/vant#12036]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-w56kff?file=/src/App.vue

### Vant 版本

4.4.1

### 描述一下你遇到的问题。

通过@touchstart 事件打开的 van-popup，会自动执行 onClose 导致 popup 立即关闭

### 重现步骤

https://github.com/youzan/vant/issues/4185
这个问题应该很早就有了

**Comment by zaxlct** [comment]
临时解决办法，把 touchstart 改成click 事件就好了

**Comment by inottn** [comment]
使用 @touchstart.prevent 绑定 touchstart 事件
