### ISSUE TITLE
Error: Failed to resolve import "vant/es/Image/style"

### ISSUE THREAD

**Issue by lixiaofa** [youzan/vant#12038]
### 重现链接

https://github.com/lixiaofa/fast-plus/actions/runs/5385822513/jobs/9780918878

### Vant 版本

 "vant": "^4.4.1"

### 描述一下你遇到的问题。

 
![image](https://github.com/youzan/vant/assets/23230215/a370ff31-6602-43ac-bfc4-246823e78dae)
本地这样引入没问题， 但放cicd 有问题
![image](https://github.com/youzan/vant/assets/23230215/59f74b6c-1682-471e-bbf6-44e717c8d30f)

### 重现步骤

none

**Comment by zhousg** [comment]
你把 Image 和 Divider 改成小写试试吧

**Comment by chenjiahan** [comment]
CI 环境的文件系统对于路径大小写是严格限制的，本地机器可能没这个限制。

**Comment by lixiaofa** [comment]
非常感谢 解惑， 困扰我一天了  @zhousg @chenjiahan
