### ISSUE TITLE
Popup 嵌套 AddressEdit 背景蒙层问题

### ISSUE THREAD

**Issue by haiqinJack** [youzan/vant#1203]
x

**Describe the bug**
Popup 嵌套 AddressEdit ,背景蒙层正常，在点击‘收件地区’，最上级背景蒙层消失，AddressEdit蒙层显示，很难看- -

**Screenshots**
[图片1](http://p8p8yzlxl.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-05-31%20%E4%B8%8A%E5%8D%8812.48.23.png)[图片1](http://p8p8yzlxl.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-05-31%20%E4%B8%8A%E5%8D%8812.48.14.png)
**Environment**
 - Device: All
 - Browser: All
 - Vant Version: ^1.0.5

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 1.1.6 版本修复
