### ISSUE TITLE
[Bug Report] vant2.12.54安卓微信浏览器下，van-uploader上传3m图片后整体页面近乎卡死，请大神解决

### ISSUE THREAD

**Issue by lwm98** [youzan/vant#12048]
### 重现链接

https://codesandbox.io/s/vant-bug-demo-7yxrsj?file=/src/App.vue

### Vant 版本

2.12.54

### 描述一下你遇到的问题。

在安卓微信浏览器打开，点击uploader上传文件后，field输入框近乎卡死，无法输入（其实整个页面都很卡了已经）。
但是在用uploader上传之前，都是正常的，使用原生input上传文件也是不卡的。
在别的浏览器，或者别的webview中是不会出现这样的问题的，请大佬看下什么情况，万分感谢。
貌似和图片的即时预览有很大关系，看了别的issue，说已经修复了这个卡顿问题，但是好像并没有完全修复，该状况下还是卡的不行。

### 重现步骤

1.网址发送到微信，点击网址打开该demo
2.点击uploader上传图片，我用的是3M的图片
3.点击field输入框，输入，近乎卡死

### 设备/浏览器

安卓、微信浏览器

**Comment by lwm98** [comment]
如果复现链接预览不了，附带其中代码。请大神看看是啥情况

`<template>
  <div id="app">
    <van-field v-model="form.username" label="文本" placeholder="请输入用户名" />

    <van-uploader v-model="fileList" :after-read="afterRead" />

    <input type="file" name="" id="">
  </div>
</template>

<script>
export default {
  name: 'App',
  components: {},
  data() {
    return {
      fileList:[],
      form:{
      }
    }
  },
  methods: {
    afterRead(file) {
      // 此时可以自行将文件上传至服务器
      console.log(file)
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
  overflow-x: hidden;
}
</style>
`

**Comment by lwm98** [comment]
@chenjiahan

**Comment by chenjiahan** [comment]
我试了下安卓微信确实有这个问题（安卓 Chrome 正常），把 `overflow-x: hidden;` 去掉就正常了

猜测是 img 加载 base64 图片的场景，在微信 WebView 内触发了某个 bug，所以导致该问题

**Comment by chenjiahan** [comment]
vant v4.6.1 会修复此问题，参考 https://github.com/youzan/vant/pull/12051

**Comment by jungre19** [comment]
> vant v4.6.1 会修复此问题，参考 #12051

请问vant2版本不修复了吗？

**Comment by chenjiahan** [comment]
有需要的话可以参考 https://github.com/youzan/vant/pull/12051 提一个 PR 到 Vant 的 2.x 分支
