### ISSUE TITLE
[Feature Request] 请在此填写标题 级联选择器点开默认选择一级省份功能（带上二级城市也可以） 

### ISSUE THREAD

**Issue by scallopsF** [youzan/vant#12050]
### 这个功能解决了什么问题？

因为我现在要选择一个地点的学校。 我可以根据SIM卡的归属地来进行定位在那个省份，来实现点开组件已经选择了对应的省份的选中。

### 你期望的 API 是什么样子的？

不太会写哈哈

**Comment by scallopsF** [comment]
我是想着点开组件 可以直接已经选择了 省份 。但是现在只有先选择了省份，关闭但不刷新页面，二次点开组件就会默认选中上次选中的省份。

**Comment by scallopsF** [comment]
希望可以通过传入参数的方式来匹配对应的省份选项并选中。

**Comment by wjw-gavin** [comment]
https://codesandbox.io/s/vant-4-issue-template-forked-dk3xjk?file=/src/App.vue

给 `cascader` 绑定对应的值，不就可以默认选中吗？

**Comment by scallopsF** [comment]
总共三级数据 我只想默认选中第一级数据省份，“给 cascader 绑定对应的值” 没有对应的值主要是

**Comment by wjw-gavin** [comment]
哦哦哦，“根据SIM卡的归属地来进行定位在那个省份” 意思是刚开始只有省份名字么

**Comment by scallopsF** [comment]
就是现在全国的省份列表，我点开组件，组件可以默认选中了北京

**Comment by wjw-gavin** [comment]
是我理解有误吗😂，你已经定位到省份，有了省份及其 id，然后把 id 绑定到 cascader 上，组件不是可以默认当前省份吗...

**Comment by wjw-gavin** [comment]
> 总共三级数据 我只想默认选中第一级数据省份，“给 cascader 绑定对应的值” 没有对应的值主要是

id  不是对应的值么

**Comment by scallopsF** [comment]
“ id 绑定到 cascader 上”， 这个是用那个 东西 进行绑定呢？ （v-model么？）

**Comment by scallopsF** [comment]
我有id ，然后我用那个方法进行绑定么

**Comment by scallopsF** [comment]
哥 我用的vue2  这个用vue2也可以实现么  或者方便发下vue2的代码呢 感谢大哥！

**Comment by scallopsF** [comment]
我用vue2 写了下，就是给cascaderValue 赋值，谢谢！！谢谢！ vant真好用，六边形UI组件！
