### ISSUE TITLE
轮播图不能纵向轮播

### ISSUE THREAD

**Issue by NEOHOOO** [youzan/vant#1205]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/
****

**Comment by NEOHOOO** [comment]
<van-swipe :autoplay="3000" vertical  :show-indicators= false>
					<van-swipe-item  v-for="(item,index) in bannerData" :key="index"><a :href="'//'+item.bannerUrl"><img  :src="item.bannerImg" alt=""></a></van-swipe-item>					
			</van-swipe>

**Comment by chenjiahan** [comment]
不规范的 issue
