### ISSUE TITLE
There are cyclic references between `basic.ts` and `validate.ts`

### ISSUE THREAD

**Issue by xboy2012** [youzan/vant#12063]
As I commented on this line.

https://github.com/youzan/vant/commit/cd439c04f305e323865e87940266c7764ade1731#r120808580

```
import { isObject } from './validate';
```
This line just introduce cyclic references between `basic.ts` and `validate.ts`,
which would cause serious issues, such as building into commonjs.

Maybe need to organize the something like `utils` in a better way.

Possible approaches:

1. Split every atomic util method/function into a single file, and avoid gethering them.
2. Gethering every atomic util method/function into only one file.

As for best practices, approach 2 is obviously unaccepatable, which defeats the purpose of module system, and harm treeshaking.

So my recommendation is to use approach 1.

**Comment by chenjiahan** [comment]
Thanks for the feed back! This issue has been fixed.
