### ISSUE TITLE
TreeSelect 分类选择 

### ISSUE THREAD

**Issue by VICTORYGS** [youzan/vant#1206]
{
        // 可选项的名称
        text: '温州',
        // 可选项的id，高亮的时候是根据id是否和选中的id是否相同进行判断的
        id: 1002
      },
      {
        // 可选项的名称
        text: '杭州',
        // 可选项的id，高亮的时候是根据id是否和选中的id是否相同进行判断的
        id: 1001
      }
    ]

# 希望text里面不光可以写str  可以写写html 或者组件 这样就更完美了

**Comment by chenjiahan** [comment]
不规范的 issue
