### ISSUE TITLE
cdn引入vant 白屏文件  节点未加载 急急急！！！

### ISSUE THREAD

**Issue by fanzuwang** [youzan/vant#12077]
### 重现链接

http://m-test2.yaochufa.com/travel/order/SubmitReserveV5?productId=13&channelLinkId=120786&c=1&no=aqLzBvjkznJRAA2pb0wPxw%3d%3d

### Vant 版本

2.12

### 描述一下你遇到的问题。

ios12打开链接，节点并未渲染。控制台也没有报错，对应的vue版本为2.5.16

### 重现步骤

1.打开页面
2.白屏
3.查看节点#combined并不存在
4.该项目是通过cdn引入的方式实现

### 设备/浏览器

ios12都可以

**Comment by chenjiahan** [comment]
请提供一个复现仓库或 codesandbox 复现链接，从问题描述中无法定位你的问题（大概率是写法问题，而不是 bug）
