### ISSUE TITLE
[Bug Report] vant 文档的右侧组件demo效果，部分组件无法显示，控制台报错了：TypeError: Failed to fetch dynamically imported module: https://vant-contrib.gitee.io/vant/assets/index-918381a9.js

### ISSUE THREAD

**Issue by kido050313** [youzan/vant#12072]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/picker-group

### Vant 版本

4.6.2

### 描述一下你遇到的问题。

日期组件无法查看组件demo效果，
![image](https://github.com/youzan/vant/assets/29145782/c4c98156-f0d9-4d08-b0b7-89cc5b3b22d5)

### 重现步骤

1. 打开vant4 文档
2. 点击PickerGroup 选择器组
3. 右边的demo未显示，控制台报错

**Comment by inottn** [comment]
服务器的问题吧，现在看好像没有问题了
