### ISSUE TITLE
Dialog注册不正确的报错提示

### ISSUE THREAD

**Issue by Fairfarren** [youzan/vant#1207]
**Describe the bug**
```html
<template>
  <div>
    <button @click="toggleShow">button</button>
    <van-dialog
      v-model="show"
      show-cancel-button
      :before-close="beforeClose"
    >
      <van-field
        v-model="content"
        label="用户名"
        placeholder="请输入用户名"
      />
    </van-dialog>
  </div>
</template>
```

```javascript
import Vue from 'vue'
import { Dialog, Field } from 'vant'
Vue.use(Dialog).use(Field)
export default {
  data () {
    return {
      show: false,
      content: ''
    }
  },
  methods: {
    toggleShow () {
      this.show = true
    },
    beforeClose (action, done) {
      if (action === 'confirm') {
        setTimeout(done, 1000)
      } else {
        done()
      }
    }
  }
}
```

报错信息：**Unknown custom element: <van-dialog> - did you register the component correctly? For recursive components, make sure to provide the "name" option.**

**Screenshots**
![WechatIMG86.jpeg](https://i.loli.net/2018/05/31/5b0f9bd510509.jpeg)
![WechatIMG87.jpeg](https://i.loli.net/2018/05/31/5b0f9bd591546.jpeg)

**Environment**
 - Device: pc
 - Browser:  chrome
 - Vant Version: 0.12.0

**Comment by Fairfarren** [comment]
我看了一下源码。。。好像是我的vant版本低了，看到了版本比较高的文档。。。希望文档上面能添加一个当前的版本号。。。

**Comment by chenjiahan** [comment]
@Fairfarren 后续会在文档里标注最新版本
