### ISSUE TITLE
AddressEdit 地址编辑 地址编辑的业务组件   可以不可以支持 输入框的label 和 placeholder 可配置?

### ISSUE THREAD

**Issue by zhaoyunchong** [youzan/vant#12088]
### 这个功能解决了什么问题？

<img width="437" alt="截屏2023-07-14 16 22 01" src="https://github.com/youzan/vant/assets/52824245/1dcf61a0-15df-4ee1-8ba5-30156fb2edd5">

虽然 无伤大雅  但希望还是可以支持下   这样可能更好贴近不同公司的业务

### 你期望的 API 是什么样子的？

<van-address-edit
  {...props}
 name-label="我的姓名"
name-placeholder="请输入我的姓名"
tel-label="我的电话"
tel-placeholder="请输入我的电话"
/>

**Comment by chenjiahan** [comment]
这个场景直接用 Locale 组件来修改内置的文案就可以，参考 https://vant-contrib.gitee.io/vant/#/zh-CN/locale
