### ISSUE TITLE
[Bug Report] picker组件，级联选择的数据嵌套深度问题

### ISSUE THREAD

**Issue by DZTZ** [youzan/vant#12082]
### 重现链接

https://codesandbox.io/s/vant-4-pickerji-lian-xuan-ze-de-shu-ju-qian-tao-wen-ti-tqgqww?file=/src/App.vue:33-43

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

**使用picker级联选择时，如果其中一条数据没有children或者等于[]就会报错**
重现链接中展示了我遇到的问题

关于picker组件官网文档的描述：**“级联选择的数据嵌套深度需要保持一致，如果部分选项没有子选项，可以使用空字符串进行占位。”**
我不太清楚这是什么意思，怎么进行占位？能提供一个简单的代码demo吗？

### 重现步骤

1、进入重现链接
2、切换picker选项

### 设备/浏览器

所有浏览器

**Comment by wjw-gavin** [comment]
级联选择的数据**嵌套深度**需要保持一致。  [示例](https://codesandbox.io/s/vant-4-pickerji-lian-xuan-ze-de-shu-ju-qian-tao-wen-ti-forked-229ppn?file=/src/App.vue)

![image](https://github.com/youzan/vant/assets/19986739/78b205de-45cf-4d0a-9e73-b40dd1b997a9)
