### ISSUE TITLE
AddressList 地址列表组件 希望通过props控制底部新增的地址按钮显示      

### ISSUE THREAD

**Issue by zhaoyunchong** [youzan/vant#12087]
### 这个功能解决了什么问题？

![WechatIMG4](https://github.com/youzan/vant/assets/52824245/592fc2e0-d0dc-44a3-945a-add1358caca9)

而且吧  可不可以做下ios 底部安全区适配

### 你期望的 API 是什么样子的？

 <van-address-list {...props} :show-add-button="false">  // 默认是true
           
   </van-address-list>

**Comment by wjw-gavin** [comment]
“可不可以做下ios 底部安全区适配”

看了下组件是支持安全区域的，可以检查下是不是自己的 css 给覆盖掉了
https://github.com/youzan/vant/blob/e42500070bc3ae85a3ec8c67cd214ef3c563bc69/packages/vant/src/address-list/AddressList.tsx#L92
