### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by userchun** [youzan/vant#12080]
### 重现链接

https://youzan.github.io/vant/#/zh-CN/action-sheet

### Vant 版本

4.6.2

### 描述一下你遇到的问题。

vant4在iphone14 pro max ios 16.3.1上动画失效

### 重现步骤

ios升级到16.3以上

**Comment by chenjiahan** [comment]
未复现此问题，建议重启浏览器试试
