### ISSUE TITLE
<van-form>表单通过validate方法进行全局表单校验过程中报错

### ISSUE THREAD

**Issue by AKAking23** [youzan/vant#12085]
### 重现链接

https://57f8tj.csb.app/

### Vant Cli 版本

4.6.2

### 描述一下你遇到的问题。

<van-form>表单通过validate方法进行全局表单校验过程中报错
![image](https://github.com/youzan/vant/assets/82486465/628da1fb-fb17-4df0-8384-ff7d3c8c7487)
具体代码可见codesandbox链接查看
ref 、rule、submit事件等都具备
请尽快查看解决下 谢谢～

### 重现步骤

1.[https://57f8tj.csb.app/](url)
2.点击按钮打开弹窗是通过van-dialog嵌套的van-form表单
3.点击确定的时候应该对其进行非空校验
4.会出现错误  如上图

**Comment by zhousg** [comment]
建议在关闭 Dialog 之前去进行表单校验，而不是在 confirm 事件中

**Comment by AKAking23** [comment]
> 建议在关闭 Dialog 之前去进行表单校验，而不是在 confirm 事件中

此问题与dialog显示应该无关吧

**Comment by inottn** [comment]
```js
formRef.value?.validate()
  .then(() => {
    // success
  })
  .catch(e => {
    // fail
  });
```
catch 一下

**Comment by AKAking23** [comment]
> ```js
> formRef.value?.validate()
>   .then(() => {
>     // success
>   })
>   .catch(e => {
>     // fail
>   });
> ```
> 
> catch 一下

catch可以成功校验  谢谢各位！！thank you～

**Comment by yinjiaotou** [comment]
哎呀妈！总算在这找到答案了！
