### ISSUE TITLE
[Bug Report] vue3 使用vant4 日历组件 白屏 性能消耗过大

### ISSUE THREAD

**Issue by lonlygods** [youzan/vant#12083]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/calendar

### Vant 版本

4.4.0

### 描述一下你遇到的问题。

vue3 使用vant4 日历组件 需求mindate1970年 性能消耗巨大 并且van-calendar__days中的节点始终是空白的

### 重现步骤

<van-calendar v-model:show="show" :min-date="new Date(1970)" />
给组件标签添加 :min-date="new Date(1970)" 就可以复现

**Comment by inottn** [comment]
这个场景后续会增加月份，年份切换功能

**Comment by chenjiahan** [comment]
参考 https://github.com/youzan/vant/issues/11228
