### ISSUE TITLE
rate的change事件

### ISSUE THREAD

**Issue by louie-liang** [youzan/vant#1208]
rate的change事件怎么用？
`<van-rate v-model="params.speed_rating" @change="changeval"/>`
我绑定了一个事件 当分值变化的时候 ，changeval什么都没打印出来

**Comment by jerryni** [comment]
@louie-liang params.speed_rating 这个值会变

**Comment by louie-liang** [comment]
@jerryni 当然会变了，我需要得到这个值

**Comment by chenjiahan** [comment]
不规范的 issue
