### ISSUE TITLE
Swipe  想要一个控制轮播的props  我并不想让他自动轮博  想通过js手动控制滑动

### ISSUE THREAD

**Issue by zhaoyunchong** [youzan/vant#12096]
### 这个功能解决了什么问题？

文档上面有一个autoplay 的属性 但是好像只是控制轮博间隔秒数的属性

### 你期望的 API 是什么样子的？

<van-swipe :loop="false" :width="300" :autoplay="false">   
</van-swipe>

// 默认是 true

**Comment by inottn** [comment]
可以将 autoplay 设置为 0

**Comment by zhaoyunchong** [comment]
> 可以将 autoplay 设置为 0

确实可以 谢谢哈   但是为什么官网没说明呢

**Comment by inottn** [comment]
> > 可以将 autoplay 设置为 0
> 
> 确实可以 谢谢哈 但是为什么官网没说明呢

我猜因为默认值是 0 不会轮播，只有在需要轮播的时候才会设置具体 autoplay 值，所以之前没有人问过相似问题吧。

**Comment by chenjiahan** [comment]
Swipe 不设置 autoplay 就不会自动轮播，这个应该是符合直觉的
