### ISSUE TITLE
[Bug Report] DatePicker 自定义确定事件文档未显示方法调用

### ISSUE THREAD

**Issue by lijinbin** [youzan/vant#12097]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-v3jlxm

### Vant 版本

4.6.0

### 描述一下你遇到的问题。

DatePicker 日期选择， 点击自定义确定事件 方法调用失败

### 重现步骤

DatePicker 日期选择， 点击自定义确定事件 方法调用失败

**Comment by inottn** [comment]
未提供 getPicker 方法

**Comment by lijinbin** [comment]
> 未提供 getPicker 方法



> 未提供 getPicker 方法

4这个版本会提供吗

**Comment by inottn** [comment]
> 4这个版本会提供吗

目前没有提供的计划
