### ISSUE TITLE
[Bug Report] 单独按需'import Row from vant/es/Row/index.mjs'时，gutter属性会失效？

### ISSUE THREAD

**Issue by gxy5202** [youzan/vant#12094]
### 重现链接

https://github.com/gxy5202/vant-row-import-issue

### Vant 版本

4.6.2

### 描述一下你遇到的问题。

main.ts文件通过
`import { Row } from 'vant'`和`import Row from 'vant/es/Row/index.mjs`的结果不同
`import { Row } from 'vant'`的方式，gutter属性会生效，`import Row from 'vant/es/Row/index.mjs`的方式gutter属性会失败

### 重现步骤

1. `pnpm install`
2. `pnpm run dev`

main.ts文件可以测试两种方式的引入结果
`import { Row } from 'vant'`和`import Row from 'vant/es/Row/index.mjs`的结果不同
`import { Row } from 'vant'`的方式，gutter属性会生效，`import Row from 'vant/es/Row/index.mjs`的方式gutter属性会失败

F12直接审查元素即可看到是否生效

### 设备/浏览器

Chrome 114.0.5735.199

**Comment by chenjiahan** [comment]
在这个仓库里没有复现你描述的问题呢，两种情况 gutter 都是生效的

![image](https://github.com/youzan/vant/assets/7237365/11e53230-2eaf-4628-b3b9-8d79f9b94320)
