### ISSUE TITLE
[Bug Report] Field组件自定义input导致验证无法通过

### ISSUE THREAD

**Issue by liyuan1125** [youzan/vant#12093]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-5nn98r

### Vant 版本

4.6.2

### 描述一下你遇到的问题。

Field组件自定义input导致验证无法通过，是正常行为还是bug？？？

### 重现步骤

示例

**Comment by inottn** [comment]
参考文档的使用方法，当使用自定义 input 时，表单项的值不会从 Field 组件读取
