### ISSUE TITLE
normalizeClass 方法的导入路径错了，应该是从 @vue/shared 导入，而不是 vue

### ISSUE THREAD

**Issue by JunmeiChen** [youzan/vant#12102]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-rr8fm2?file=/src/main.js&resolutionWidth=320&resolutionHeight=675

### Vant 版本

4.6.0

### 描述一下你遇到的问题。

van-cascader 组件无法使用，直接拿官方的例子来试就能重现，但是codesandbox上无法重现

![image](https://github.com/youzan/vant/assets/138839098/a4b83908-0c85-4454-958e-94ce5f697847)

normalizeClass 为undefined，因为
![image](https://github.com/youzan/vant/assets/138839098/90d28c7e-713f-4e5a-9957-47a3023ccea6)

![image](https://github.com/youzan/vant/assets/138839098/5846655c-b77e-4cc8-8e4c-222870970a92)

### 重现步骤

van-cascader 组件无法使用，直接拿官方的例子来试就能重现

但是codesandbox上无法重现

### 设备/浏览器

chrome

**Comment by inottn** [comment]
你用的 vue 的版本是多少 🤔
