### ISSUE TITLE
图片预览image-preview提供了展示关闭按钮，但是没有任何作用，点击蒙层仍然可以关闭预览窗口

### ISSUE THREAD

**Issue by zhangkang412326** [youzan/vant#12108]
### 这个功能解决了什么问题？

图片预览image-preview在之前的版本中有一个closeOnClickOverlay，当closeable为true的时候，将closeOnClickOverlay设为false可以让用户点击closeIcon的时候才关闭弹窗。但是vant4.x之后，这个属性移除了。那现在不管展示不展示关闭icon，点击蒙层都会关闭预览界面。那整个closeable还有什么作用呢。

### 你期望的 API 是什么样子的？

请在vant4.x中恢复closeOnClickOverlay这个api。这样可以设置只有点击关闭icon的时候才关掉预览窗口

**Comment by chenjiahan** [comment]
> image-preview 在之前的版本中有一个 closeOnClickOverlay

之前有这个 API 吗？具体是哪个版本，我没找到
