### ISSUE TITLE
[Bug Report] TextEllipsis组件 `position ` 为 `middle`时, dots会出现两次.

### ISSUE THREAD

**Issue by muzaisimao** [youzan/vant#12119]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-3nyc6x?file=/src/App.vue

### Vant 版本

4.6.3

### 描述一下你遇到的问题。

如题, 官网示例即可重现问题.

### 重现步骤

<img width="303" alt="image" src="https://github.com/youzan/vant/assets/31382094/24628fe5-a7b5-44fb-88b2-96de8265bce7">

---

<img width="421" alt="image" src="https://github.com/youzan/vant/assets/31382094/5b47cf2f-6d9e-4d96-ad8e-0cfe51737077">

### 设备/浏览器

Chrome

**Comment by wjw-gavin** [comment]
这其实不算一个 bug 吧...  中间省略特意做的如此，[NutUI](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/ellipsis)，   [ant-design-mobile](https://mobile.ant.design/zh/components/ellipsis) 也是如此。

**Comment by chenjiahan** [comment]
确实中间省略用更长的字符会比较明显，那这个细节可以再讨论下。

 @muzaisimao 这里出现 dot 两次有造成什么其他影响吗

**Comment by muzaisimao** [comment]
目前出现两次 dot 会导致宽度计算有问题, 具体可以看这里:
https://codesandbox.io/s/vant-4-issue-template-forked-3nyc6x?file=/src/App.vue

**Comment by muzaisimao** [comment]
Ant Design Mobile 不支持自定义 `dots`, Nut UI 确实也是这样, 使用自定义省略符号时, 重复两次会很奇怪 😂

**Comment by muzaisimao** [comment]
@chenjiahan  @wjw-gavin 

我对比了一下 Vant 和 Nut, 同样的宽度下, 使用 middle 时显示的有问题. 可以讨论下要用那种方式解决这个问题.

Vant: https://codesandbox.io/s/vant-4-issue-template-forked-8hd98y?file=/src/App.vue

Nut: https://codesandbox.io/p/sandbox/nutui4-vite-demo-forked-dy4w7l?file=%2Fsrc%2FApp.vue%3A17%2C1

**Comment by wjw-gavin** [comment]
> 使用 middle 时显示的有问题

嗯嗯，确实使用 middle 时存在显示的问题😂，感谢 @muzaisimao  细心指出。
我个人还是倾向不改变 dots 哈，看看作者的决策

**Comment by chenjiahan** [comment]
考虑到上述问题，组件还是保持默认设置一次 dot 好了，用户有需要的话，可以手动把 dot 设置为更长的值。

这样保持默认行为一致性，避免产生困惑。

**Comment by wjw-gavin** [comment]
ok~
