### ISSUE TITLE
Popover 气泡弹出框组件在手机端h5页面可以正常显示，但通过webview嵌入到小程序无法显示

### ISSUE THREAD

**Issue by zzzzuurdf** [youzan/vant#12118]
### 重现链接

https://

### Vant 版本

2.12.54

### 描述一下你遇到的问题。

Popover 气泡弹出框组件在手机端h5页面可以正常显示，但通过webview嵌入到小程序无法显示

### 重现步骤

h5链接：https://
小程序链接复制发送到到微信会话点击：#小程序://
点击任一页面中的问号触发Popover 显示，但小程序中不能显示

**Comment by chenjiahan** [comment]
<img width="747" alt="Screenshot 2023-07-29 at 11 42 59" src="https://github.com/youzan/vant/assets/7237365/17c1cf21-33fc-4ab2-b4d1-ebb918c590bb">
