### ISSUE TITLE
van-picker中级联选择不可回选

### ISSUE THREAD

**Issue by zls0910** [youzan/vant#12131]
### 重现链接

https://codepen.io/zls0910/pen/VwVVwZM

### Vant 版本

4.6.3

### 描述一下你遇到的问题。

--

### 重现步骤

--

**Comment by wjw-gavin** [comment]
你提供的是一个四级结构的数据，但是你 `selectedValues` 提供的只有三位，正常使用没问题的。

https://codesandbox.io/s/vant-4-issue-template-forked-dk3xjk?file=/src/App.vue

![image](https://github.com/youzan/vant/assets/19986739/9220a1d9-a12c-4fd2-a04e-75e519380dbb)
