### ISSUE TITLE
表格每一页最多只能显示90条记录，能不能设置显示全部数据？

### ISSUE THREAD

**Issue by anranq** [youzan/vant#12148]
### 这个功能解决了什么问题？

表格每一页最多只能显示90条记录，能不能设置显示全部数据？

### 你期望的 API 是什么样子的？

表格每一页最多只能显示90条记录，能不能设置显示全部数据？

**Comment by anranq** [comment]
打印也只能打印90条记录，没办法一次性打印完呢。微信小程序版

**Comment by inottn** [comment]
可以去对应项目下反馈
