### ISSUE TITLE
[Bug Report] FloatingPanel 组件有列表时卡顿

### ISSUE THREAD

**Issue by yue1123** [youzan/vant#12146]
### 重现链接

文档里面的demo就可以触发这个问题

### Vant 版本

4.6.3

### 描述一下你遇到的问题。

FloatingPanel 组件内的列表滚动，先向下滚动一点，然后不松手向上滚动到顶部触发，这时候触发高度减小，会巨卡，只是安卓手机上有这个问题，ios没有

### 重现步骤

先向下滚动一点，然后不松手向上滚动到顶部

### 设备/浏览器

安卓手机，Chrome

**Comment by zhousg** [comment]
可以提供下安卓手机的型号和谷歌浏览器版本哈

**Comment by yue1123** [comment]
Chrome106，测试机型小米11，我测试的几台安卓手机，鸿蒙都有这个问题

**Comment by zhousg** [comment]
我测试了一下没有复现，可以提供一个操作录屏吗

**Comment by yue1123** [comment]
https://github.com/youzan/vant/assets/61490799/0e3b8229-9c69-4237-84c6-e2a95d65dbf7

**Comment by yue1123** [comment]
前面是正常不卡顿操作，后面是卡顿操作
https://github-production-user-asset-6210df.s3.amazonaws.com/61490799/257991946-0e3b8229-9c69-4237-84c6-e2a95d65dbf7.MOV

**Comment by zhousg** [comment]
get ~

**Comment by yue1123** [comment]
我已经有解决方案了，我可以尝试修复一下，提一个pr

**Comment by zhousg** [comment]
```diff
        if (-startY < boundary.value.max) {
          if (e.cancelable) e.preventDefault();
          e.stopPropagation();
        } else if (
          !(contentRef.value.scrollTop <= 0 && touch.deltaY.value > 0)
        ) {
          return;
+        } else if (startScrollTop > 0 && touch.deltaY.value > 0) {
+         return;
        }
```

你再加一个判断，测试下

**Comment by yue1123** [comment]
> ```diff
> +    let startY: number, startScrollTop: number;
>     const touch = useTouch();
> 
>     // ....
> 
>         if (-startY < boundary.value.max) {
>           if (e.cancelable) e.preventDefault();
>           e.stopPropagation();
>         } else if (
>           !(contentRef.value.scrollTop <= 0 && touch.deltaY.value > 0)
>         ) {
>           return;
> +        } else if (startScrollTop > 0 && touch.deltaY.value > 0) {
> +         return;
>         }
> ```
> 
> 你再加一个判断，测试下

这样貌似是不能完全屏蔽先向下滚动，再向上滚动的情况

**Comment by zhousg** [comment]
> 这样貌似是不能完全屏蔽先向下滚动，再向上滚动的情况

这种情况，没有必要处理，正常效果吧

**Comment by yue1123** [comment]
但是这样也会触发卡顿，和滑动时滚动条位置不在顶部触发卡顿一样，而且这个手势操作用户触发的情况也不少。你可以看我之前的视频，有演示这个效果。其次，屏蔽这个操作手势，在 ios 上会表现的更加自然点，与 ios 原生的滚动回弹效果冲突的概率会小很多

**Comment by chenjiahan** [comment]
这个 issue 有两个相关 PR

@zhousg @yue1123 你们要不互相 review 一下，看看最终用哪一个实现

**Comment by yue1123** [comment]
> 这个 issue 有两个相关 PR
> 
> @zhousg @yue1123 你们要不互相 review 一下，看看最终用哪一个实现

我的实现包含了@zhousg的实现，只是换了个判断方式，还兼容了另一种情况，和我这个比较好点
