### ISSUE TITLE
van-swipe 没有提供自定义滑动到指定slider的方法，即常见的slideTo(index)

### ISSUE THREAD

**Issue by kangyanyan** [youzan/vant#1214]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
下个版本会支持此 api

**Comment by chenjiahan** [comment]
已在 1.1.7 版本支持
