### ISSUE TITLE
[Bug Report] Unable to scroll List behind after FloatingPanel hidden

### ISSUE THREAD

**Issue by anonimusprogramus** [youzan/vant#12156]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-ts8qd9?file=/src/App.vue

### Vant 版本

4.6.3

### 描述一下你遇到的问题。

Please refer to codesandbox, sorry if it's not well-written, thanks

### 重现步骤

1. When FloatingPanel hidden, we can't scroll List behind. But when FloatingPanel unloaded, we can scroll. Is this on purpose?
2. Can we drag down and close FlotingPanel?
3. Can we just hide FloatingPanel (using v-show) so the last state/position of content preserved?

Thank you, please correct me if I choose wrong category

**Comment by inottn** [comment]
`lock-scroll` prop will be supported, with a default value of true. You can set it to false according to your needs at an appropriate time.

**Comment by anonimusprogramus** [comment]
man, that was fast! thanks, gonna check it out later

**Comment by chenjiahan** [comment]
I'm wondering why the FloatingPanel component needs to lock the page scrolling. Perhaps we should allow users to scroll the page content by default. @inottn @zhousg

**Comment by inottn** [comment]
> I'm wondering why the FloatingPanel component needs to lock the page scrolling. Perhaps we should allow users to scroll the page content by default. @inottn @zhousg

Based on the actual usage scenario of this component, there is no need to lock page scrolling. In my opinion, we can modify the default value of `lock-scroll` to false.

**Comment by chenjiahan** [comment]
I agree with you, we can change the default value in the next version.

**Comment by zhousg** [comment]
At that time, it was thought to be used for the map floating layer, and it was added when writing the floating-panel component. Without the application scenario more

**Comment by anonimusprogramus** [comment]
I can confirm, by adding `:lock-scroll="false"`,
- now I'm able to scroll any list behind/beneath
- using v-show rather than v-if as it's faster to show/hide than recreate/loop content using v-if

thanks a lot :+1:

**Comment by chenjiahan** [comment]
> Does the next version refer to 5.0 ?

No, I mean the next minor or patch version...

This can be considered a small "breaking change", but I think changing the default value will not affect most users. If some users want to lock the page scrolling, they can manually set the `lock-scroll` prop.
