### ISSUE TITLE
[Bug Report] showToast 不能用了

### ISSUE THREAD

**Issue by gxjcoo** [youzan/vant#12163]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN

### Vant 版本

4.6.4

### 描述一下你遇到的问题。

使用showToast组件不能够展示提示信息

### 重现步骤

1、官网demo 点击Toast按钮。没有提示

**Comment by chenjiahan** [comment]
哪个 demo？

**Comment by zhujunel** [comment]
showToast没有样式 "vant": "^4.8.1"
