### ISSUE TITLE
Stepper 如果存在于checkbox中 会存在click事件冒泡

### ISSUE THREAD

**Issue by evanyangg** [youzan/vant#1216]
**Describe the bug**
当stepper组件嵌套在checkbox组件中时, 调用onChange 方法时, 同时调用checkbox方法改变其值

**Screenshots**
图片不太好显示, 很容易复现
临时解决方案是: 在源码中简单改了一下
![image](https://user-images.githubusercontent.com/22952321/40870222-95751366-665d-11e8-89f4-c08f95368ede.png)
![image](https://user-images.githubusercontent.com/22952321/40870224-9c294cfe-665d-11e8-8850-1b37425f718d.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.1.5

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by wenjayliu** [comment]
picker 里的确定取消也同样存在事件冒泡

**Comment by chenjiahan** [comment]
事件冒泡是正常行为，如果不想要事件冒泡，可以这样处理

```html
<van-stepper @click.native.stop />
```

**Comment by Candane** [comment]
> 
> 
> 事件冒泡是正常行为，如果不想要事件冒泡，可以这样处理
> 
> ```
> <van-stepper @click.native.stop />
> ```

weapp中不可以使用@click.native.stop吧

**Comment by chenjiahan** [comment]
小程序可以使用 catch:tap=“noop” ，绑定一个空函数

**Comment by Candane** [comment]
好的，谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 上午9:36
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"星光大道"<396785031@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] Stepper 如果存在于checkbox中 会存在click事件冒泡 (#1216)





 
小程序可以使用 catch:tap=“noop” ，绑定一个空函数
