### ISSUE TITLE
[Bug Report] FloatingBubble贴边定位异常

### ISSUE THREAD

**Issue by alinquan** [youzan/vant#12167]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/floating-panel

### Vant 版本

4.6.4

### 描述一下你遇到的问题。

一级页面使用了FloatingBubble，且设置属性magnetic=x, 固定在屏幕最右边
进入二级页面后微信浏览器出现底部返回栏，返回一级页面，点击FloatingBubble组件，此时FloatingBubble在屏幕右边看不见了
由于微信浏览器二级页面返回一级页面出现底部导航栏，高度变化触发updateState，

以下为FloatingBubble组件源码片段，目前解决办法在62行下面加if(!width)renturn

![70bb5fa7bbed8167ede894799646316](https://github.com/youzan/vant/assets/33288621/29bb37ef-2760-429c-a45e-54558b6cfd85)

### 重现步骤

https://github.com/youzan/vant/assets/33288621/cdd8de69-a1b6-4d7f-99a0-5ee7b73a34b6

### 设备/浏览器

ios/微信内置浏览器

**Comment by zhousg** [comment]
可以提供一下你的最小复现代码，我也实现了一下视频功能，但是未复现

**Comment by alinquan** [comment]
> 可以提供一下你的最小复现代码，我也实现了一下视频功能，但是未复现

页面使用了keep-alive 缓存，试了下不使用keep-alive不会出现以上问题

![0166fbf6a9e8e59cc36782cf28d8375](https://github.com/youzan/vant/assets/33288621/d3197437-fb43-4a75-98d4-310affac1999)

**Comment by alinquan** [comment]
https://github.com/alinquan/test.git 需在ios手机微信浏览器里调试，复现步骤：点击蓝色按钮 -》点击进入详情 -》返回上一页 -》 再次点击蓝色按钮
