### ISSUE TITLE
[Bug Report] 使用 vant-cli 搭建组件库时，使用 pnpm 包管理，构建后报错。

### ISSUE THREAD

**Issue by wjw-gavin** [youzan/vant#12168]
### 重现链接

https://github.com/wjw-gavin/vant-cli-test

### Vant Cli 版本

6.0

### 描述一下你遇到的问题。

组件使用 setup&ts 方式编写，在 build 后报错。测出来两个结果：
1、如果一开始使用 pnpm 包管理，修改代码并执行 build 后报错（defineProps 赋值给 props，并使用了 props）
![WeChatd7aa311a944791fe0e10b5d1968c71fc](https://github.com/youzan/vant/assets/19986739/da761c19-9bd5-4181-b982-782edea6badd)

测试发现问题出在这个  `defineProps` 上，如果我把代码修改如下（或者直接删掉 `defineProps` 代码）
```js
// 未赋值变量
defineProps({
  color: String,
  type: {
    type: String,
    default: 'primary',
  },
})
```
再执行 build，结果正常
![WeChat3d96bfe9c8d85fe2f7fdd967b389bc74](https://github.com/youzan/vant/assets/19986739/11c75a61-80f4-41e3-89bc-8b5dfdd81124)

2、还有一种情况是：在开始不修改 `build.packageManager`，使用默认的 yarn，这个时候无论 defineProps 怎么写都不报错，build 正常。
![WeChatf7b4720f4e1380da7e05a522b4861d35](https://github.com/youzan/vant/assets/19986739/58b6b528-54a0-415f-85b7-06fa7500fd5d)

### 重现步骤

1. 执行 pnpm create vant-cli-app 初始化项目
2. pnpm i 安装依赖
3. 使用 ts，仓库添加了 tsconfig.json 和 tsconfig.declaration.json
4. 修改 vant.config.mjs 使用 pnpm 包管理
5. 修改 demo-button 代码为 setup 方式，使用 defineProps
6. 执行 pnpm build

**Comment by wChenonly** [comment]
tsc 编译类型的时候，不能在继续编译   打包后的es和lib文件了


![image](https://github.com/youzan/vant/assets/37658262/a12f49a7-480a-4300-828a-fc3b5ca98cfb)

**Comment by chenjiahan** [comment]
这个问题其实和 Vant CLI 没关系，是 TypeScript 在 pnpm monorepo 下的常见问题，有一些相关 issue 可以参考：

- https://github.com/microsoft/TypeScript/issues/42873
- https://github.com/microsoft/TypeScript/issues/47663
