### ISSUE TITLE
[Feature Request] "DropdownItemOption" supports boolean value.

### ISSUE THREAD

**Issue by baboon-king** [youzan/vant#12164]
### What problem does this feature solve?

```ts
export type DropdownItemOption = {
    text: string;
    icon?: string;
    value: Numeric;
};
```

"value" only is number or string.

Would like to support boolean types, or more

### What does the proposed API look like?

```vue
<script setup lang="ts">
import { ref } from "vue";

/**
 * from vant
 */
export type Numeric = number | string;

/**
 * from vant
 */
export type DropdownItemOption = {
  text: string;
  icon?: string;
  value: Numeric | boolean;
};

const options: DropdownItemOption = [
  { text: "yes", value: true },
  { text: "no", value: false },
];

const value = ref(false);
</script>
<template>
  <van-dropdown-menu>
    <van-dropdown-item v-model="value" :options="options" />
  </van-dropdown-menu>
</template>
```
added: 
value: Numeric | boolean;

**Comment by baboon-king** [comment]
If this recommendation is accepted.
I'd be happy open a PR

**Comment by inottn** [comment]
The `value` will be used as the key for v-node in the internal implementation, but `key` does not support boolean type.

**Comment by baboon-king** [comment]
> The `value` will be used as the key for v-node in the internal implementation, but `key` does not support boolean type.

lol.
I see.

But this severely limits the scope of `value`... any new ideas?

Let the user provide the `key`?

**Comment by chenjiahan** [comment]
Boolean value support is a reasonable request, feel free to submit a pull request for it.

As for the `key`, you can just use `String(value)` because there should not be two same boolean values.

**Comment by baboon-king** [comment]
I see 
I'll start on that soon.
