### ISSUE TITLE
Tab与List一起使用时，点击Tab后， list 会一直执行load事件

### ISSUE THREAD

**Issue by fayuanliu** [youzan/vant#1217]
初始化的时候，没有问题，当我点击另一个tab想重新初始化内容的时候，在没有向下滑动的情况下，list也会一直处于Load中！

**Comment by chenjiahan** [comment]
不规范的 issue

**Comment by shufangjian** [comment]
@fayuanliu 同样的问题请问下怎么解决的

**Comment by fayuanliu** [comment]
@shufangjian  list放在tab外层

**Comment by shufangjian** [comment]
@fayuanliu 是指整个van-tabs 外面吗
