### ISSUE TITLE
@vant/touch-emulator会影响其它插件

### ISSUE THREAD

**Issue by ouweicong** [youzan/vant#12173]
### 重现链接

不需要

### Vant 版本

4.4.11

### 描述一下你遇到的问题。

@vant/touch-emulator会影响其它插件，能不能做一个只对vant适用的

### 重现步骤

只要有插件有touch事件在pc端都有问题

**Comment by chenjiahan** [comment]
是的，touch-emulator 是全局生效的，暂时没计划做一个针对 Vant 的版本。

个别不需要 touch-emulator 的场景，可以试试用 data-no-touch-simulate 属性：https://github.com/youzan/vant/tree/main/packages/vant-touch-emulator#%E7%A6%81%E7%94%A8-touch-%E6%A8%A1%E6%8B%9F
