### ISSUE TITLE
[Bug Report] vant-search的placeholder太长添加text-overflow无效。原生input是可以生效的。

### ISSUE THREAD

**Issue by TianVast** [youzan/vant#12185]
### 重现链接

https://github.com/youzan/vant/blob/main/packages/vant/src/search/test/index.spec.ts

### Vant 版本

3.6.4

### 描述一下你遇到的问题。

vant-search 提示文字placeholder超长，我想添加text-overflow让他超出省略号。
原生是可以的  但是vant-search查看dom最后也是个input，为何不生效呐
只能修改颜色这种。

### 重现步骤

浏览器随意修改 除了text-overflow在原生input生效，在vant-search dom的input不生效

### 设备/浏览器

chrome

**Comment by wjw-gavin** [comment]
我这试的正常的哈

https://codesandbox.io/s/vant-3-issue-template-forked-flgtsz?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675
