### ISSUE TITLE
FloatingPanel能加一个左右滑动的浮动面板吗？

### ISSUE THREAD

**Issue by cjy816618** [youzan/vant#12191]
### 这个功能解决了什么问题？

FloatingPanel现在只能上下滑动，想要一个左右滑动的

### 你期望的 API 是什么样子的？

<van-floating-panel v-model:width="width" :anchors="anchors" direction='right'>
  <div style="text-align: center; padding: 15px">
    <p>面板显示宽度 {{ width.toFixed(0) }} px</p>
  </div>
</van-floating-panel>

**Comment by zhousg** [comment]
@chenjiahan 场景不多吧，需要支持吗？

**Comment by cjy816618** [comment]
现在我是自己写了一个左右滑动的

**Comment by zhousg** [comment]
好的，暂时关闭哈，看看需求多不多

**Comment by chenjiahan** [comment]
嗯嗯，可以再观察下，目前感觉不是很有必要
