### ISSUE TITLE
[Bug Report]PC端使用浮动气泡组件，拖拽时会触发子元素点击事件

### ISSUE THREAD

**Issue by f-s2** [youzan/vant#12194]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-7qjx8x?file=/src/App.vue

### Vant 版本

4.6.4

### 描述一下你遇到的问题。

PC端网页使用悬浮气泡组件时，给里面的子元素绑定点击事件，拖拽组件会触发子元素的点击事件

### 重现步骤

1. 在 PC 端使用悬浮气泡组件
2. 给组件内部子元素绑定点击事件
3. 拖拽组件

**Comment by zhousg** [comment]
https://codesandbox.io/s/vant-4-issue-template-forked-cg764r?file=/src/App.vue

**Comment by f-s2** [comment]
> https://codesandbox.io/s/vant-4-issue-template-forked-cg764r?file=/src/App.vue

这样拖拽时确实不会触发点击事件了，但不拖拽时的点击事件也不能触发了

**Comment by zhousg** [comment]
再看看，刚才代码不是最新的

**Comment by zhousg** [comment]
请教下 @chenjiahan @inottn 如果组件内部实现有没有思路？

**Comment by f-s2** [comment]
> 再看看，刚才代码不是最新的

好的，非常感谢您提供的解决方案，但感觉这样使用有些麻烦，同时我也很好奇组件内部如何能够解决这个问题🤔

**Comment by chenjiahan** [comment]
#12201 已经有一个修复方案了，可以等新版本发布后试一下，预计一两周内发版

**Comment by f-s2** [comment]
> #12201 已经有一个修复方案了，可以等新版本发布后试一下，预计一两周内发版

好的，谢谢🙏
