### ISSUE TITLE
[Bug Report] 部分变量泄露到全局变量里，还用的是关键词

### ISSUE THREAD

**Issue by 707939754** [youzan/vant#12193]
### 重现链接

在引用vant后，直接console.log(bottom)，可以直接打印出字符串'bottom'

### Vant 版本

4.0.3

### 描述一下你遇到的问题。

在引用vant后，直接console.log(bottom)，可以直接打印出字符串'bottom'

### 重现步骤

在引用vant后，直接console.log(bottom)，可以直接打印出字符串'bottom'

### 设备/浏览器

chorme

**Comment by 707939754** [comment]
![image](https://github.com/youzan/vant/assets/54610087/bd59c79a-eae6-4441-84f3-8d2a05969133)

**Comment by 707939754** [comment]
这些变量全部都可以打印，不用定义，虽然不会导致报错。如果你的变量名也使用bottom等的话，会影响项目内部分动态加载的变量

**Comment by chenjiahan** [comment]
这是模块作用域里的变量，为啥会影响全局？可能你需要检查下你的打包工具配置
