### ISSUE TITLE
useCustomFieldValue如何在<script setup>中使用

### ISSUE THREAD

**Issue by ChenghuanX** [youzan/vant#12196]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-58cgnd?file=/src/App.vue

### Vant 版本

4.6.4

### 描述一下你遇到的问题。

useCustomFieldValue如何在<script setup>中使用, 直接使用会报inject() can only be used inside setup() or functional components.

### 重现步骤

在输入框中输入内容报inject() can only be used inside setup() or functional components.

**Comment by zhousg** [comment]
```
// ok
useCustomFieldValue(() => value.value);

const onInput = (v) => {
  // useCustomFieldValue(() => v);
};
```
