### ISSUE TITLE
van-field type=“number”时 会报错

### ISSUE THREAD

**Issue by HannibalKcc** [youzan/vant#1220]
**Describe the bug**
```
<van-field type="number" v-model.number="myNum"/>
```

**Screenshots**
![default](https://user-images.githubusercontent.com/26264400/40907407-531c9218-6816-11e8-9cd4-7aabd9577f4b.png)

**Environment**
 - Vant Version: 1.0.4

**Reproduce**
https://jsfiddle.net/we2pso8z/
https://jsfiddle.net/ky5vw24k/ (当然 去掉.number修饰符也会有这个问题)

报错的原因是value为数字类型而强求indexOf方法。

现有方案，源码部分修改为：
```
let allowPoint = typeof this.value === 'string'
          ? this.value.indexOf('.') === -1
          : this.value.toString().indexOf('.') === -1
```

**Comment by chenjiahan** [comment]
已在 1.1.7 版本支持
