### ISSUE TITLE
FloatingPanel 在ios上滑动卡顿，不流畅，antdesign-mobile 浮动面板组件没有这个问题

### ISSUE THREAD

**Issue by cjy816618** [youzan/vant#12202]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/floating-panel

### Vant 版本

4.6.5

### 描述一下你遇到的问题。

在ios16.0.2( iphone13)的chrome浏览器里面版本114.0.5735.124上打开滑动卡顿

### 重现步骤

滑动面板

### 设备/浏览器

 iphone13

**Comment by zhousg** [comment]
antd-mobile 使用了 react-spring 加了弹簧效果，Vant 是实时位移。

**Comment by inottn** [comment]
未复现，可以提供复现视频看看。卡顿可能和是否开启了省电模式有关。

**Comment by chenjiahan** [comment]
@zhousg 不考虑引入三方依赖哈，有需要的话可以我们自行实现一个精简的版本
