### ISSUE TITLE
怎么手动引入组件样式 

### ISSUE THREAD

**Issue by lixiaofa** [youzan/vant#12219]
### 重现链接

https://github.com/lixiaofa/fast-plus/blob/master/packages/components/sku/src/sku.vue

### Vant 版本

"vant": "^4.4.1"

### 描述一下你遇到的问题。

打包错误
![image](https://github.com/youzan/vant/assets/23230215/65ed238d-6549-4f7b-9ca8-6f98905d71b4)

### 重现步骤

pnpm docs:build

**Comment by chenjiahan** [comment]
引用 'vant/es/xxx/style` 或 'vant/lib/xxx/style` 都可以，es 目录是 ESModule 格式，lib 目录是 CommonJS 格式。

如果引用报错了，应该和你的打包配置有关系，可以自行排查下

**Comment by lixiaofa** [comment]
> 引用 `vant/es/xxx/style` 或 'vant/lib/xxx/style` 都可以，es 目录是 ESModule 格式，lib 目录是 CommonJS 格式。
> 
> 如果引用报错了，应该和你的打包配置有关系，可以自行排查下

这是配置文件：
![image](https://github.com/youzan/vant/assets/23230215/fe49900c-c836-4c24-b2d9-3781173ed542)
没看到有可疑的 ， 我奇怪的是pnpm dev 正常， pnpm build 就会报 上面的错误， 也没做环境判断 ， 同一份配置

@chenjiahan   能帮我看看吗， 谢谢

**Comment by chenjiahan** [comment]
没时间，自查下吧😂

**Comment by lixiaofa** [comment]
> 没时间，自查下吧😂

那好吧，  能给我 方向吗，  浅谈一下， 谢谢 @chenjiahan

**Comment by chenjiahan** [comment]
应该是 Vite build 的时候 SSG 挂了吧，dev 的时候不会触发 SSG
