### ISSUE TITLE
手机关闭摄像头权限，点击拍照没有反应 

### ISSUE THREAD

**Issue by zhouzhi-zz** [youzan/vant#12218]
### 这个功能解决了什么问题？

上传图片时  没有拍照权限，点击没反应，没有回调

### 你期望的 API 是什么样子的？

点击拍照失败时给出回调提示

**Comment by wjw-gavin** [comment]
这个建议自己处理哈，可以使用 [getUserMedia](https://developer.mozilla.org/zh-CN/docs/Web/API/MediaDevices/getUserMedia) 判断下是否有权限使用。

<img width="588" alt="image" src="https://github.com/youzan/vant/assets/19986739/0c11c330-d320-4c8b-8978-d86f16b02656">
