### ISSUE TITLE
[Feature Request] 新增playground功能

### ISSUE THREAD

**Issue by chenyulun** [youzan/vant#12217]
### 这个功能解决了什么问题？

可以在线调试vant功能和预览自定义使用方式，就像
案例页面：https://nutui.jd.com/playground/#
案例源码：https://github.com/jdf2e/nutui/tree/v4/packages/nutui-playground
参考vue官网源码： https://github.com/vuejs/core/tree/main/packages/sfc-playground
关联npm源码`@vue/repl`: https://github.com/vuejs/repl

### 你期望的 API 是什么样子的？

案例里面有跳转功能，如下：
https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/button

**Comment by chenjiahan** [comment]
感觉 Nut 这个 Playground 只能做一些基础的调试，和 IDE 的开发体验没法比，也不如直接用 codesandbox

**Comment by chenyulun** [comment]
现在提供了这个文档案例跳转codesandbox功能吗？
还是需要使用者自己去建立codesandbox项目
确定不做这个功能的话就关闭吧，感谢支持

**Comment by chenjiahan** [comment]
现在有一个基础的 codesandbox 模板哈：https://codesandbox.io/s/vant-3-issue-template-8fuq5o

> 确定不做这个功能的话就关闭吧，感谢支持

嗯嗯，这个 issue 先关闭了
