### ISSUE TITLE
关于unplugin-vue-components，是否需要将解析器迁移到vant包内部

### ISSUE THREAD

**Issue by wChenonly** [youzan/vant#12221]
### 这个功能解决了什么问题？

看到unplugin-vue-components不在接受新的Resolvers，并且建议已经有的也可以迁移到自己包内部

迁移到自己包内部的好处是有问题,我们自己随时修改发布。

<img width="1271" alt="image" src="https://github.com/youzan/vant/assets/37658262/864ccaba-e237-48a6-a344-cc5b24571c06">

如果接受这个issue,我可以来迁移。名字叫vant-auto-resolver，可行？

### 你期望的 API 是什么样子的？

无

**Comment by chenjiahan** [comment]
嗯嗯，可以迁移到 Vant 仓库里作为一个单独的子包，包名的话可以使用 `@vant/auto-import-resolver`

**Comment by ixqbar** [comment]
@wChenonly  请问截图用的什么字体

**Comment by wChenonly** [comment]
> @wChenonly 请问截图用的什么字体

 "editor.fontFamily": "Hermit-Regular, 霞鹜文楷"
