### ISSUE TITLE
vant密码输入框

### ISSUE THREAD

**Issue by xiaohuooo** [youzan/vant#12229]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/field

### Vant 版本

4.6.5

### 描述一下你遇到的问题。

密码输入框的小眼睛，在失焦后再次点击输入框小眼睛不显示

### 重现步骤

密码输入框的小眼睛，在失焦后再次点击输入框小眼睛不显示

### 设备/浏览器

edge

**Comment by inottn** [comment]
密码输入框有这个功能吗 🤔

**Comment by xiaohuooo** [comment]
![image](https://github.com/youzan/vant/assets/96033527/43cd7970-407a-4aca-bc67-fde376e9063b)

**Comment by xiaohuooo** [comment]
好吧，后续会有密码显示隐藏的功能吗

**Comment by inottn** [comment]
> 好吧，后续会有密码显示隐藏的功能吗

需要评估一下吧，目前是可以通过 slot 自行实现这个功能的

**Comment by chenjiahan** [comment]
暂时不考虑，容易和浏览器原生控件冲突
