### ISSUE TITLE
FloatingBubble如何设置在窗口的右下角，但是距离底部有60rem的距离？

### ISSUE THREAD

**Issue by 11003** [youzan/vant#12236]
### 这个功能解决了什么问题？

FloatingBubble对于各种手机端初始化显示的时候更灵活

### 你期望的 API 是什么样子的？

``html
<template>
    <van-floating-bubble
        v-model:offset="offset"
        :inheritAttrs="true"
        axis="xy"
        magnetic="x"
        :gap="0"
        icon="xxx"
    />
</template>
```

**Comment by 11003** [comment]
```html
<template>
    <van-floating-bubble
        v-model:offset="offset"
        :inheritAttrs="true"
        axis="xy"
        magnetic="x"
        :gap="0"
        icon="xxx"
    />
</template>

<script setup>
// 如果用之前的x、y，我不知道x的要多少，因为每个手机的尺寸都不一样
const offset = ref({
    right: 20,
    bottom: 50
});
</script>
```

**Comment by zhousg** [comment]
```ts
import { useWindowSize } from '@vant/use';

const { height } = useWindowSize()
const offset = ref<FloatingBubbleOffset>({ x: -1, y: -1 });
onMounted(()=>{
  // 60rem 可以自己计算
  offset.value.y = height.value - 60
})
```

**Comment by hzlzsm** [comment]
> ```ts
> import { useWindowSize } from '@vant/use';
> 
> const { height } = useWindowSize()
> const offset = ref<FloatingBubbleOffset>({ x: -1, y: -1 });
> onMounted(()=>{
>   // 60rem 可以自己计算
>   offset.value.y = height.value - 60
> })
> ```

我使用了useElementBounding和useWindowSize，都不起效果，依旧是初始设置的offset

**Comment by Student414** [comment]
> > ```ts
> > import { useWindowSize } from '@vant/use';
> > 
> > const { height } = useWindowSize()
> > const offset = ref<FloatingBubbleOffset>({ x: -1, y: -1 });
> > onMounted(()=>{
> >   // 60rem 可以自己计算
> >   offset.value.y = height.value - 60
> > })
> > ```
> 
> 我使用了useElementBounding和useWindowSize，都不起效果，依旧是初始设置的offset

的确，onMounted中自己计算的xy坐标确实无法更新bubble的offset，导致bubble仍然在默认位置，需要后期手动调用一下函数方能生效（例如我这边监听到window resize会更新bubble offset，能生效），不确定是不是bug。
