### ISSUE TITLE
[Bug Report] 浮动气泡无法通过config provider修改样式

### ISSUE THREAD

**Issue by WilliamLin1990** [youzan/vant#12235]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-hp3gc7?file=/src/App.vue

### Vant 版本

4.6.6

### 描述一下你遇到的问题。

修改浮动气泡的背景颜色，没有变化

### 重现步骤

1. 页面使用浮动气泡组件；
2. ConfigProvider 使用floatingBubbleBackground 自定义颜色；

**Comment by zhousg** [comment]
![image](https://github.com/youzan/vant/assets/15833290/ecffbb46-550c-419e-9082-f833fa0c6555)

ConfigProvider 添加的 css vars 是在 van-config-provider 元素上，无法作用于使用了 teleport 组件的的组件，因为默认是 to body 元素内容

**Comment by zhousg** [comment]
@chenjiahan 其他使用 teleport 的组件有相同的问题（大概10个），是否考虑使用 `CONFIG_PROVIDER_KEY` 注入，在组件根元素加上？

**Comment by zhousg** [comment]
> 我也有考虑给 ConfigProvider 添加一个全局模式
我加下？
