### ISSUE TITLE
文档无法访问问题反馈

### ISSUE THREAD

**Issue by zhangxiaoshang** [youzan/vant#1223]
**Describe the bug**
克隆项目安装依赖后执行 `npm run dev` 后 文件`docs/src/docs-entry.js`发生变化，然后访问 `0.0.0.0:[port]/#/zh-CN/intro` 无法查看组件文档，即点击左侧的导航没有效果。执行 `git checkout docs/src/docs-entry.js` 后再访问文档就不会有该问题。

这种现象是特例还是普遍现象，什么原因呢！

**Environment**
 - Device: IMAC
 - Browser: Chrome
 - Vant Version: 1.1.4

**Comment by jerryni** [comment]
更新到最新的试试，或者直接重新clone
