### ISSUE TITLE
[Bug Report] iOS端日历有一定概率不显示内容

### ISSUE THREAD

**Issue by kjlamuro** [youzan/vant#12245]
### 重现链接

无法百分百重现

### Vant 版本

4.6.6

### 描述一下你遇到的问题。

iOS端 safari 日历有一定概率不显示内容(参考附件),使用使用浏览器刷新当前页时,完全无法重现.

出现时机:杀掉safari后台后,从iPhone桌面快捷方式打开链接,但是出现的频率也很低,十次里有一次

此时只要稍微一滑动日历,显示就正常了.

总感觉是formatter没有被触发的问题.

 const formatter = computed(() => {
     //  dataFetchedCount.value 是用来查看数据是否准备好了
      if (dataFetchedCount.value < 3) {
        return (day) => day;
      }
      return (day) => {
        day.topInfo = calendarType.value[dayjs(day.date).format("YYYY-MM-DD")];
        day.bottomInfo = monthCalendarData.value[
          dayjs(day.date).format("YYYY-MM-DD")
        ]
          ? true
          : false;
        return day;
      };   });

显示空白如图:
![IMG_2644](https://github.com/youzan/vant/assets/17349317/a0d4e6e4-459c-4a8c-8c46-aacd607afc82) 

正常显示时如图:
![IMG_2647](https://github.com/youzan/vant/assets/17349317/15c709a6-d550-42ff-bdb1-a01777cb36bf)

### 重现步骤

杀掉safari后台后,从iPhone桌面快捷方式打开链接,但是出现的频率也很低,十次里有一次

### 设备/浏览器

iPhone 12 ios16及iOS17

**Comment by kjlamuro** [comment]
试图用scrollToDate来触发,也还是会出现问题

**Comment by chenjiahan** [comment]
把 lazy-render 属性设置为 false 试试呢

**Comment by kjlamuro** [comment]
> 把 lazy-render 属性设置为 false 试试呢

谢谢🙏，改成false后目前为止没问题了
