### ISSUE TITLE
useCustomFieldValue使用无效

### ISSUE THREAD

**Issue by ChaoqiYin** [youzan/vant#12259]
### 重现链接

https://mmn-cn.coding.net/public/odoo-mobile-suite/odoo-mobile-vue/git

### Vant 版本

4.6.6

### 描述一下你遇到的问题。

按照官网示例使用useCustomFieldValue进行自定义form内字段时，useCustomFieldValue无法使form内的表单值更新，使用表单的getValues时无法获取到对应的字段值，且useCustomFieldValue传入的函数在任何时候都未被调用

### 重现步骤

跑起示例代码后，点击【+1】按钮修改自定义字段内的值，点击【提交】按钮。在浏览器控制台看输出值始终为{}

### 设备/浏览器

chrome latest

**Comment by ChaoqiYin** [comment]
问题解决了，使用的是import { Field as VantField } from 'vant/lib/field';   
provides找Symbol['van-field']时Symbol不同导致找不到。

应该为import { Field as VantField } from 'vant';
但是想知道为什么从lib里引入就会导致这个问题

**Comment by inottn** [comment]
> 问题解决了，使用的是import { Field as VantField } from 'vant/lib/field'; provides找Symbol['van-field']时Symbol不同导致找不到。
> 
> 应该为import { Field as VantField } from 'vant'; 但是想知道为什么从lib里引入就会导致这个问题

因为有 cjs 和 esm 两份打包产物

**Comment by ChaoqiYin** [comment]
> > 问题解决了，使用的是import { Field as VantField } from 'vant/lib/field'; provides找Symbol['van-field']时Symbol不同导致找不到。
> > 应该为import { Field as VantField } from 'vant'; 但是想知道为什么从lib里引入就会导致这个问题
> 
> 因为有 cjs 和 esm 两份打包产物

明白了  thanks
