### ISSUE TITLE
vant的Tabbar 标签栏组件有问题

### ISSUE THREAD

**Issue by ruoyuSSY** [youzan/vant#12262]
### 重现链接

没有上传github

### Vant 版本

Vant4

### 描述一下你遇到的问题。

vant的Tabbar 标签栏组件使用路由模式时，to=“/”的标签会一直显示

     <van-tabbar route>
            <van-tabbar-item replace to="/" icon="home-o">标签</van-tabbar-item>
            <van-tabbar-item replace to="/qa" icon="search">标签</van-tabbar-item>
            <van-tabbar-item replace to="/video" icon="video-o">标签</van-tabbar-item>
            <van-tabbar-item replace to="/my" icon="contact">标签</van-tabbar-item>
        </van-tabbar>
![Snipaste_2023-09-08_00-37-21](https://github.com/youzan/vant/assets/67770449/d22946da-27dd-486e-8563-e3d89f88fbe9)

### 重现步骤

路由模式下 根路由和当前路由同时会active,也就是说路由模式下不能to="/"

### 设备/浏览器

chrome

**Comment by Jungzl** [comment]
```typescript
{
  path: '/',
  // ...
  name: 'home'
}
```

```vue
<van-tabbar-item replace to="{ name: 'home' }" icon="home-o">标签</van-tabbar-item>
```
