### ISSUE TITLE
Slider 滑块

### ISSUE THREAD

**Issue by 18510758841** [youzan/vant#1226]
最大值和最小值只能在100以内么？如果max为1000的话滑动超出屏幕

**Comment by jerryni** [comment]
@18510758841  value 指的是当前滑动位置在整体进度中的百分比，所以只会在0-100之间

**Comment by 18510758841** [comment]
onChange(value) {
            console.log(value)
            this.value=value
          }
这个得到的也是百分比么？那当前滑块的值是多少？  我测试把min:100  max :1000  step:100  滑动直接超出页面

**Comment by chenjiahan** [comment]
change 事件返回的 value 也是百分比喔，min 和 max 都应该在 0-100 内
