### ISSUE TITLE
在nuxt3使用van-tabs，里面的内容不会渲染真实DOM，无法做SEO

### ISSUE THREAD

**Issue by 11003** [youzan/vant#12266]
### 重现链接

https://codesandbox.io/p/sandbox/nuxt-starter-z4660?file=/app.vue:7,16

### Vant 版本

^4.6.1

### 描述一下你遇到的问题。

在nuxt3使用van-tabs，里面的内容不会渲染真实DOM，无法做SEO
![image](https://github.com/youzan/vant/assets/35055270/10eb2418-fc39-439a-ab14-6e917aa8b033)

### 重现步骤

点击重现链接即可看到：[链接](https://codesandbox.io/p/sandbox/nuxt-starter-z4660?file=/app.vue:7,16)

**Comment by chenjiahan** [comment]
参考：https://github.com/youzan/vant/issues/5278

**Comment by codeblockhead** [comment]
> 参考：#5278

4年了，这个问题不管了吗

**Comment by qingtianyu** [comment]
刚入坑就碰到这个问题，不知道现在有没有解决方案？

**Comment by 11003** [comment]
> 刚入坑就碰到这个问题，不知道现在有没有解决方案？

自己写一个元素，隐藏即可
