### ISSUE TITLE
Vant Tab标签页隐藏后显示底部条有问题以及点击滚动导航定位有偏差

### ISSUE THREAD

**Issue by Caveolaes** [youzan/vant#12263]
### 重现链接

https://codesandbox.io/s/shy-worker-zfrthv?file=/src/App.vue

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

Tab标签页初始化时隐藏，当滚动高度超过某个值显示，出现问题如下
1、底部条位置不对
2、点击滚动导航tab，定位不准确

### 重现步骤

滚动页面，tab显示，点击tab-item看相对应的content内容的位置

### 设备/浏览器

chrome

**Comment by Simon-He95** [comment]
Hi @Caveolaes , 顶部的标题栏一般来说是要占高度的，如果要隐藏的话建议使用visibility来控制

**Comment by Caveolaes** [comment]
> Hi @Caveolaes , 顶部的标题栏一般来说是要占高度的，如果要隐藏的话建议使用visibility来控制

visibility还会占位隐藏，我需要的是完全隐藏

**Comment by Simon-He95** [comment]
暂时可以通过这个方法解决，
你可以给item元素除了第一个元素其他加padding-top:44px,然后在滚动的时候去控制display的同时跟着改变第一个元素的paddingTop

**Comment by Caveolaes** [comment]
> 暂时可以通过这个方法解决， 你可以给item元素除了第一个元素其他加padding-top:44px,然后在滚动的时候去控制display的同时跟着改变第一个元素的paddingTop, https://codesandbox.io/s/vigorous-swartz-szl6lj?file=/src/App.vue

点击到选项1的时候，tab标签栏就没有啦

**Comment by Simon-He95** [comment]
你不是希望默认隐藏吗所以到顶了第一个不就消失了嘛🤔️

**Comment by Caveolaes** [comment]
> 你不是希望默认隐藏吗所以到顶了第一个不就消失了嘛🤔️

上面还有其他内容的，他不会直接到顶部的

**Comment by chenjiahan** [comment]
`document.querySelector(".van-tabs__wrap").style.display = "none";` 这种直接操作 DOM 的行为不是标准用法，组件目前不考虑兼容。
