### ISSUE TITLE
[Bug Report] iOS viewport 更新不触发 resize 事件，导致 useWindowSize 错误，FloatingBubble 显示在视窗外

### ISSUE THREAD

**Issue by xuyimingwork** [youzan/vant#12276]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-p6yn9w?file=/src/App.vue

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

业务上通过代码动态更改 head 标签下 meta name="viewport" 标签的 content 内容，在 iOS 端，viewport content 的更新不会触发 window 的 resize 事件，导致 useWindowSize 返回的 width 数值错误，导致 FloatingBubble 无法展示。

另外：iOS 端 viewport content 修改后并不会立即触发 window.innerWidth 的更改，大约几十到几百毫秒后，window.innerWidth 才发生变化。

### 重现步骤

codesandbox 代码：https://codesandbox.io/s/vant-4-issue-template-forked-p6yn9w?file=/src/App.vue
1. 手机端 iOS 访问：https://p6yn9w.csb.app/
2. 点击 update viewport 按钮

结果：window.innerWidth 发生改变，但 useWindowSize 导出的 width 并未改变
期待：useWindowSize 导出的 width 改变

### 设备/浏览器

iOS 设备 Safari 浏览器，需要在手机上复现，PC 端 Safari 无法复现

**Comment by xuyimingwork** [comment]
目前暂时通过 MutationObserver 监听 meta content 变化，重新触发 resize 解决。
该问题在 vueuse 中同样存在。

**Comment by xuyimingwork** [comment]
这个要放在 vant 里面改吗？还是要作为浏览器兼容性问题由组件库外自行解决？

**Comment by zhousg** [comment]
最好修改 vant use

**Comment by chenjiahan** [comment]
> 业务上通过代码动态更改 head 标签下 meta

Vant 似乎没法感知到这个变化

**Comment by xuyimingwork** [comment]
> > 业务上通过代码动态更改 head 标签下 meta
> 
> Vant 似乎没法感知到这个变化

相当于 useWindowSize 需要监听 `head meta[name="viewport"]` 元素的变化，因为它的变化会触发 window size 的变化，这个可以通过 MutationObserver 实现，但我不确定这个实现是否应该在 vant 中做。

如果不在 vant 中做的话，相当于 useWindowSize 在这种情况下并不能准确反映窗口大小。

**Comment by chenjiahan** [comment]
useWindowSize 没法监听 `head meta[name="viewport"]` 元素的变化

这个 case 太特殊了，还是建议自行处理一下哈，比如手动 trigger 一下 window 的 resize 事件
