### ISSUE TITLE
upload组件上传图片

### ISSUE THREAD

**Issue by XU1029** [youzan/vant#12284]
### 重现链接

https://hldc-test.obs.cn-east-3.myhuaweicloud.com/enrollcrm-front/enrollcrm-front/20230913/docs/file0000046153.jpg

### Vant 版本

4.6.4

### 描述一下你遇到的问题。

upload组件上传其他平台（比如微博）的图片保存到本地然后上传到OBS上之后，上传成功，但是img的图是裂开的，单独访问线上图片的地址是可以打开的，这是上传之后线上图片的地址  https://hldc-test.obs.cn-east-3.myhuaweicloud.com/enrollcrm-front/enrollcrm-front/20230913/docs/file0000046153.jpg

### 重现步骤

微博上找一个图片保存手机本地，然后upload组件上传图片到服务器上，图是裂开的

### 设备/浏览器

android ios

**Comment by inottn** [comment]
图片的响应的Content-Type不对吧，正常的图片用浏览器打开不会触发下载的

**Comment by inottn** [comment]
这个图片格式是HEIC，目前主流浏览器是不支持的
