### ISSUE TITLE
安卓手机在APP内拉起相册之后，滑动返回，再次点击上传，无法拉起上传

### ISSUE THREAD

**Issue by zhanjiangmrlu** [youzan/vant#12287]
### 重现链接

https://vant-ui.github.io/vant/v2/#/zh-CN/uploader

### Vant 版本

2.12.54

### 描述一下你遇到的问题。

安卓手机在APP内，内嵌webview使用van-uploader上传组件，点击上传，不上传图片，滑动返回，再次点击上传，无法调用相册功能。

### 重现步骤

1. 点击上传图片
2. 拉起相册，不选择图片，滑动返回
3. 再次点击上传图片，无法调用起相册功能

### 设备/浏览器

安卓手机

**Comment by caoyuee** [comment]
我也遇到这个严重的bug了，离谱，这bug不修吗？
