### ISSUE TITLE
[Feature Request] 希望可以增加一个书本翻页功能

### ISSUE THREAD

**Issue by javaofferss** [youzan/vant#12296]
### 这个功能解决了什么问题？

1. 想在app中添加一个书本翻页的功能. 向前翻页,向后翻页.  但是vant中好像没有. 希望能提供一个.

### 你期望的 API 是什么样子的？

1. 想在app中添加一个书本翻页的功能. 向前翻页,向后翻页.  但是vant中好像没有. 希望能提供一个.
2. 可以监听向前,向后翻页事件,

**Comment by chenjiahan** [comment]
这个组件不是很通用，建议自行实现下
