### ISSUE TITLE
[Feature Request] Popup + DatePicker组件性能

### ISSUE THREAD

**Issue by feifanshijie** [youzan/vant#12295]
### What problem does this feature solve?

      
状态更新肉眼可见的延时 这个组件可以优化一下吗?

### What does the proposed API look like?

<Popup
          v-model:show="state.show.end_at"
          position="bottom">
      <DatePicker
          v-model="end_at"
          title="选择结束时间"
          :min-date="minDate"
          :max-date="maxDate"
          @cancel="state.show.end_at = false"
          @confirm="e => HandleSelectData(e, 'end_at')"
      />
</Popup>

**Comment by chenjiahan** [comment]
提供个 codesandbox 复现链接看看？
