### ISSUE TITLE
想问下  @vant/area-data 这份省市区数据不是最新的

### ISSUE THREAD

**Issue by rouyuanfang** [youzan/vant#12305]
### 重现链接

http://www.stats.gov.cn/sj/tjbz/tjyqhdmhcxhfdm/2023/index.html

### Vant 版本

2.12.54

### 描述一下你遇到的问题。

![image](https://github.com/youzan/vant/assets/34623199/5935873c-b08d-43e2-a799-19c896a7dd3f)

这里可忽略，因为创建issue这里是必填，又不知道填什么，就随便放了张图

### 重现步骤

![image](https://github.com/youzan/vant/assets/34623199/2aa866b9-cb02-48c6-a492-5383e70fff55)

这里可忽略，因为创建issue这里是必填，又不知道填什么，就随便放了张图

**Comment by ruochuan12** [comment]
看你填写的 `vant` 是 2.12.54 版本。

这个 `@vant/area-data` 组件不知道你用的什么版本。

目前最新的版本是 `v1.5.0` 基本应该是最新的（2个月前更新的），你可以安装使用最新的版本

```bash
npm i @vant/area-data
```

主要用的是这个变量 [areaList](https://github.com/youzan/vant/blob/main/packages/vant-area-data/src/index.ts#L1)。

```js
import { areaList } from '@vant/area-data';
```

如果你发现某些省份或者城市不是最新，可以提交PR修改。
