### ISSUE TITLE
v2版本 van-field 组件没有内边框

### ISSUE THREAD

**Issue by All8926** [youzan/vant#12312]
### 重现链接

https://codesandbox.io/s/serene-rain-xqgfgd?file=/index.html

### Vant 版本

2.12

### 描述一下你遇到的问题。

Vant2.12版本通过cdn引入的 js 和 css，van-field 组件不显示内边框，默认情况下应该是要显示的，现在不管 border 有没有设置为true 都不显示
![image](https://github.com/youzan/vant/assets/95400480/7efb46e1-08bf-4dc2-9be2-f22a87d96d47)

### 重现步骤

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="https://unpkg.com/vant@2.12/lib/index.css" />
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <script src="https://unpkg.com/vant@2.12/lib/vant.min.js"></script>
  </head>
  <body>
    <div id="app">
      <van-field v-model="text" placeholder="请输入文本" label="文本" />
      <h2>4</h2>
    </div>
    <script>
      var app = new Vue({
        el: "#app",
        data: function () {
          return {
            text: "",
          };
        },
      });
    </script>
  </body>
</html>

**Comment by inottn** [comment]
只有一个 van-field 不会展示内边框，参考文档
