### ISSUE TITLE
[Bug Report] 在van-popup上使用scoped的class，不生效

### ISSUE THREAD

**Issue by Mrmantou** [youzan/vant#12326]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-kwkzff?file=/src/App.vue

### Vant 版本

4.7.0

### 描述一下你遇到的问题。

在van-popup上使用scoped的class，不生效

在2.x版本下的使用是没有问题的

### 重现步骤

点击button

**Comment by chenjiahan** [comment]
这个是 Vue 3 框架本身存在的 bug，一直没修复，参考：https://github.com/vuejs/core/issues/2669

**Comment by chenjiahan** [comment]
下个版本会兼容下
