### ISSUE TITLE
van-field  在ios手机上  超出宽度的文字不能滑动查看

### ISSUE THREAD

**Issue by shenyaolin** [youzan/vant#12321]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/field

### Vant 版本

2.12.53

### 描述一下你遇到的问题。

![image](https://github.com/youzan/vant/assets/84455066/312d595a-20f9-4803-9860-72fbeedbf94f)
点击弹出框  选中后回显  安卓手机可以滑动查看所有信息   ios滑动不生效

### 重现步骤

1, 点击弹出框， 选中后回显；
2, ios手机浏览器不能滑动查看全部内容

### 设备/浏览器

ios手机自带浏览器

**Comment by xiaoshuai121** [comment]
解决了吗，我还是不行
