### ISSUE TITLE
DatetimePicker 选择事件后，清空绑定值不生效

### ISSUE THREAD

**Issue by aizhelas** [youzan/vant#12352]
### 重现链接

https://vant-contrib.gitee.io/vant/v3/#/zh-CN/datetime-picker

### Vant 版本

3.6.12

### 描述一下你遇到的问题。

DatetimePicker  选择时间后，调用方法把v-model绑定值置为空字符串时，组件会先把绑定值置为00：00，再调用一次才会为空字符串

### 重现步骤

![image](https://github.com/youzan/vant/assets/88351816/6133a686-0940-4489-9993-717888e7c7c7)
点击清空
![image](https://github.com/youzan/vant/assets/88351816/b26a9caf-2d3d-4163-b5b5-b47afebbad4f)
再次点击
![image](https://github.com/youzan/vant/assets/88351816/12b215a2-a4a8-461e-b4ff-c874c49ef5a1)

**Comment by cc-hearts** [comment]
Can you provide a minimal reproduction code？

**Comment by aizhelas** [comment]
![image](https://github.com/youzan/vant/assets/88351816/1b0c5c1d-5b58-46df-9ae8-a341c5b22458)
![image](https://github.com/youzan/vant/assets/88351816/c8897c00-d962-4bef-96a4-799e125d823f)

**Comment by aizhelas** [comment]
> Can you provide a minimal reproduction code？

1

**Comment by chenjiahan** [comment]
需要提供 codesandbox 复现链接哈，光看上面的图片是无法定位问题的。

https://codesandbox.io/s/vant-4-issue-template-forked-ts8qd9?file=/src/App.vue
