### ISSUE TITLE
[Feature Request] 希望支持 ESM 在 SSR 时导入组件

### ISSUE THREAD

**Issue by yoyo837** [youzan/vant#12369]
### What problem does this feature solve?

ssr 开启会报错: module is not defined

```js
        resolvers: [
          VantResolver(
            importStyle: false,
            ssr: true,
          }),
        ],
```

### What does the proposed API look like?

None

**Comment by yoyo837** [comment]
引入到了lib包, 如何能引用到es包呢?

**Comment by chenjiahan** [comment]
已在 @vant/auto-import-resolver v1.0.2 版本支持 `module` 选项。

参考 https://github.com/youzan/vant/blob/main/packages/vant-auto-import-resolver/README.zh-CN.md#%E9%80%89%E9%A1%B9

**Comment by yoyo837** [comment]
废弃SSR是默认支持SSR的意思了吗大佬?

**Comment by yoyo837** [comment]
> 废弃SSR是默认支持SSR的意思了吗大佬?

看了下 PR , 大致明白了, 谢谢.
