### ISSUE TITLE
[Feature Request] Cell组件能否加入之前van-cell__value--alone样式，text-align设置为css变量，可以主题修改

### ISSUE THREAD

**Issue by zhoucan38** [youzan/vant#12372]
### 这个功能解决了什么问题？

Cell组件能否加入之前van-cell__value--alone样式，text-align设置为css变量，可以主题修改

### 你期望的 API 是什么样子的？

无

**Comment by chenjiahan** [comment]
有什么场景是必须使用 van-cell__value--alone 的嘛？左侧文案直接通过 title 就可以设置

**Comment by zhoucan38** [comment]
> 有什么场景是必须使用 van-cell__value--alone 的嘛？左侧文案直接通过 title 就可以设置

主要是历史项目升级，太多页面了，不好排查

**Comment by chenjiahan** [comment]
Vant 4 不会再加入这个样式了，属于冗余的代码，你可以在 Cell 的基础上简单封装一个组件，然后加一下需要的兼容逻辑哈
