### ISSUE TITLE
[Bug Report] npm安装的vant依赖包里面有alicdn的线上图标文件的链接在内网环境无法下载

### ISSUE THREAD

**Issue by 1007029335** [youzan/vant#12378]
### 重现链接

https://github.com/youzan/vant/blob/main/packages/vant-icons/src/index.less

### Vant 版本

2.12.54

### 描述一下你遇到的问题。

依赖alicdn文件离线状态无法下载，希望能把图标文件集成在依赖里面，使用npm安装的时候一起下载下来
以下为图标资源链接：
//at.alicdn.com/t/c/font_2553510_kfwma2yq1rs.woff2?t=1694918397022
//at.alicdn.com/t/c/font_2553510_kfwma2yq1rs.woff?t=1694918397022

### 重现步骤

打开重现链接，其中既有图标资源链接

**Comment by chenjiahan** [comment]
vant-icons/src/index.less 并没有被 Vant 的 Icon 组件引用。

Vant 的 Icon 组件引用的是 base64 内联后的 woff2 图标，对应的文件是https://github.com/youzan/vant/blob/main/packages/vant-icons/src/encode-woff2.less。

只有在不支持 woff2 的浏览器上，Vant 才会降级到 iconfont 上的 CDN 图标。对于  Vant 3 / 4 的浏览器范围来说，所有浏览器都是支持 woff2 的，所以这个降级逻辑基本上不会触发。

**Comment by M69W** [comment]
> > vant-icons/src/index.less 并没有被 Vant 的 Icon 组件引用。
> > Vant 的 Icon 组件引用的是 base64 内联后的 woff2 图标，对应的文件是[https://github.com/youzan/vant/blob/main/packages/vant-icons/src/encode-woff2.less。](https://github.com/youzan/vant/blob/main/packages/vant-icons/src/encode-woff2.less%E3%80%82?rgh-link-date=2023-10-22T13%3A18%3A59Z)
> > 只有在不支持 woff2 的浏览器上，Vant 才会降级到 iconfont 上的 CDN 图标。对于 Vant 3 / 4 的浏览器范围来说，所有浏览器都是支持 woff2 的，所以这个降级逻辑基本上不会触发。
> 
> 这两条外链对某些库来说是灾难，例如 dom-to-svg https://github.dev/felixfbecker/dom-to-svg/blob/208eb3b5d0544f5b48bcc1efe627990278696a41/src/inline.ts#L121 这两条傻玩意返回 application/octet-stream 导致这个库识别不了，出错
> 
> 组件就尽量别参和外链了，特别是阿里的链接，公司都快挂了


竟然碰到一样的问题，找到此处。
开始还以为是 dom-to-image 的问题，找遍了代码都没 出现 at.alicdn.com
```
"dom-to-image": "^2.6.0",
"vant": "^4.8.7",
```
报错：
```
Access to XMLHttpRequest at 'http://at.alicdn.com/t/c/font_2553510_ciljc7axaw7.woff?t=1705587463221' from origin 'http://localhost:8400' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

cannot fetch resource: //at.alicdn.com/t/c/font_2553510_ciljc7axaw7.woff?t=1705587463221, status: 0

GET http://at.alicdn.com/t/c/font_2553510_ciljc7axaw7.woff?t=1705587463221 net::ERR_FAILED 302 (Moved Temporarily)
```

请问这个情况，怎么解决？

**Comment by M69W** [comment]
> vant-icons/src/index.less 并没有被 Vant 的 Icon 组件引用。
> 
> Vant 的 Icon 组件引用的是 base64 内联后的 woff2 图标，对应的文件是[https://github.com/youzan/vant/blob/main/packages/vant-icons/src/encode-woff2.less。](https://github.com/youzan/vant/blob/main/packages/vant-icons/src/encode-woff2.less%E3%80%82)
> 
> 只有在不支持 woff2 的浏览器上，Vant 才会降级到 iconfont 上的 CDN 图标。对于 Vant 3 / 4 的浏览器范围来说，所有浏览器都是支持 woff2 的，所以这个降级逻辑基本上不会触发。

@chenjiahan 在一些特殊网络环境下，如内网，vant  遇到这种情况下怎么本地化？

**Comment by lizyChy0329** [comment]
> > vant-icons/src/index.less 并没有被 Vant 的 Icon 组件引用。
> > Vant 的 Icon 组件引用的是 base64 内联后的 woff2 图标，对应的文件是[https://github.com/youzan/vant/blob/main/packages/vant-icons/src/encode-woff2.less。](https://github.com/youzan/vant/blob/main/packages/vant-icons/src/encode-woff2.less%E3%80%82?rgh-link-date=2023-10-22T13%3A18%3A59Z)
> > 只有在不支持 woff2 的浏览器上，Vant 才会降级到 iconfont 上的 CDN 图标。对于 Vant 3 / 4 的浏览器范围来说，所有浏览器都是支持 woff2 的，所以这个降级逻辑基本上不会触发。
> 
> 这两条外链对某些库来说是灾难，例如 dom-to-svg [github.dev/felixfbecker/dom-to-svg/blob/208eb3b5d0544f5b48bcc1efe627990278696a41/src/inline.ts#L121](https://github.dev/felixfbecker/dom-to-svg/blob/208eb3b5d0544f5b48bcc1efe627990278696a41/src/inline.ts#L121) 这两条傻玩意返回 application/octet-stream 导致这个库识别不了，出错
> 
> 组件就尽量别参和外链了，特别是阿里的链接，公司都快挂了

针对外链 alicdn icon 的问题，使用 dom-to-svg 这个库可能会有解析错误的问题，可以使用 `pnpm i @lizychy0329/dom-to-svg` 来兼容这个错误
