### ISSUE TITLE
[Bug Report] van-swipe-cell在linux下无法左右滑动

### ISSUE THREAD

**Issue by vangork** [youzan/vant#12379]
### 重现链接

https://github.com/vangork/test-swipte-cell

### Vant 版本

4.7.2

### 描述一下你遇到的问题。

感谢提供此优秀的UI库。

目前借助于tauri框架开发跨平台桌面应用，前端使用vue + vite, UI库使用Vant UI。

van-swipe-cell组件在linux环境下无法左右滑动，在windows和mac下均正常。
Linux测试环境 ubuntu 20.04，libwebkit2gtk-4.0-dev

望测试修复。

### 重现步骤

1. 下载运行https://github.com/vangork/test-swipte-cell/releases/download/linux/test-swipe-cell_0.0.0_amd64.AppImage
2. 滑动`hello world` swipe cell。 

### 设备/浏览器

Linux webkit2gtk

**Comment by chenjiahan** [comment]
sorry，Vant 是面向移动端的组件库，没有计划主动适配 Tauri + Linux。

当然你有相关需求的话，欢迎自行排查原因，如果适配成本是较低的，那我们会接受相关的 PR 贡献。
