### ISSUE TITLE
[Feature Request] tab支持完全不显示内置title, 由用户完全个性化

### ISSUE THREAD

**Issue by yoyo837** [youzan/vant#12389]
### 这个功能解决了什么问题？

ref: https://github.com/youzan/vant/issues/7651

这个功能还是很常用的, 就是需要完全定制title, 无法通过title的slot轻易做到的那种:

<img width="452" alt="image" src="https://github.com/youzan/vant/assets/6134547/7c9c1cd4-6f4b-4652-91af-09cbd2df38fa">

<img width="485" alt="image" src="https://github.com/youzan/vant/assets/6134547/e54225de-7c5f-49c2-b8bc-208a36424708">

希望支持, 如果接受, 我可以PR.

虽然可以通过样式做到,  它在里层, 不在 van-tabs, 只能新增层级选择器样式来覆盖, 也没有 css vars 可以看直接覆盖, 很多人的习惯是在vue中尽量不用style标签使用tailwind等原子类样式库, 此时想要隐藏就显得很麻烦.

### 你期望的 API 是什么样子的？

添加一个  css vars , 或者一个 props属性来内置此功能.

**Comment by chenjiahan** [comment]
可以加一个 props 来控制
