### ISSUE TITLE
文档radio组件，示例代码问题-与 Cell 组件一起使用

### ISSUE THREAD

**Issue by bluegeek** [youzan/vant#1238]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**

图里面标注的地方应该是 title="something"  而不是  :title="摸个字符串" 。文档的小问题。
**Screenshots**
![image](https://user-images.githubusercontent.com/3932305/41077446-2fec0fb4-6a49-11e8-92d7-c586055e0eb9.png)

**
英文文档地址：https://www.youzanyun.com/zanui/vant#/en-US/radio
中文文档地址：https://www.youzanyun.com/zanui/vant#/zh-CN/radio
**Environment**
 - Device:  mac
 - Browser:  chrome
 - Vant Version: latest

**Reproduce**
不需要

**Comment by chenjiahan** [comment]
提个 PR 帮忙修复一下呗~

**Comment by chenjiahan** [comment]
文档已更新
