### ISSUE TITLE
[Bug Report] TextEllipsis word-break属性问题

### ISSUE THREAD

**Issue by LemonAppleMo** [youzan/vant#12390]
### 重现链接

https://github.com/youzan/vant/blob/main/packages/vant/src/text-ellipsis/index.less#L9

### Vant 版本

4.7.2

### 描述一下你遇到的问题。

关于word-break属性：https://github.com/youzan/vant/blob/main/packages/vant/src/text-ellipsis/index.less#L9

https://developer.mozilla.org/zh-CN/docs/Web/CSS/word-break#break-word

MDN 文档中标识此属性已废弃，可能在后续的浏览器中不再支持，是否考虑替换为 `overflow-wrap:  break-word`

Link: https://developer.mozilla.org/zh-CN/docs/Web/CSS/overflow-wrap#break-word 

### 重现步骤

无

**Comment by inottn** [comment]
没看到 word-break 被标识已废弃？

**Comment by LemonAppleMo** [comment]
> 没看到 word-break 被标识已废弃？

<img width="854" alt="image" src="https://github.com/youzan/vant/assets/32638462/98816690-75cc-4a95-86aa-401b3a9ded7c">

我看到了这个

**Comment by inottn** [comment]
> > 没看到 word-break 被标识已废弃？
> 
> <img alt="image" width="854" src="https://user-images.githubusercontent.com/32638462/277925130-98816690-75cc-4a95-86aa-401b3a9ded7c.png">
> 我看到了这个

明白了，你是指 break-word 这个具体的值

**Comment by chenjiahan** [comment]
已处理咯

**Comment by LemonAppleMo** [comment]
> 已处理咯

赞😁😁

**Comment by LemonAppleMo** [comment]
> > > 没看到 word-break 被标识已废弃？
> > 
> > 
> > <img alt="image" width="854" src="https://user-images.githubusercontent.com/32638462/277925130-98816690-75cc-4a95-86aa-401b3a9ded7c.png">
> > 我看到了这个
> 
> 明白了，你是指 break-word 这个具体的值

嗯嗯，是我表达的问题
