### ISSUE TITLE
[Bug Report] Tabs 组件 v-model:active 值变化异常

### ISSUE THREAD

**Issue by violetjack** [youzan/vant#12392]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-thz5x9?file=/src/App.vue

### Vant 版本

4.1.2

### 描述一下你遇到的问题。

当我把 Tabs 组件中的选项和默认值都改变后，v-model 会瞬间发生多次变化。引起业务上的问题。

### 重现步骤

1. 写个简单 tabs 组件
2. 将 tabs 组件中的 tab 选项和 `v-model:active` 值切换成例外一组数据。
3. 通过监听 `v-model:active` 绑定的值可以看到它发生了多次变化。

**Comment by wjw-gavin** [comment]
tabs 默认会选中第一个 tab，所以 active 的值默认绑定第一个 item 的 value。如果想要默认第一个，你完全不需要手动设置 tabName 的值。

<img width="948" alt="image" src="https://github.com/youzan/vant/assets/19986739/af18dce9-02a8-45f3-97af-17468fdb0304">
