### ISSUE TITLE
[Bug Report] van-address-edit组件 在show-area设置为false，无法触发onSave问题

### ISSUE THREAD

**Issue by liuliko** [youzan/vant#12391]
### 重现链接

https://codesandbox.io/s/vant-4-issue-template-forked-p8zyl8?file=/src/App.vue

### Vant 版本

4.6.8

### 描述一下你遇到的问题。

van-address-edit组件在设置show-area为false时，保存按钮点击仍然判断了区域不能为空，导致无法触发onSave事件

### 重现步骤

1 输入姓名 张三
2 输入电话 12312341234
3 点击保存

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
感谢反馈，已修复
