### ISSUE TITLE
请问AddressEdit收件地区选择如何做到反选？因为我做的是编辑页面

### ISSUE THREAD

**Issue by DeeBoo-Chan** [youzan/vant#1240]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
请问AddressEdit收件地区选择如何做到反选？因为我做的是编辑页面。

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by DeeBoo-Chan** [comment]
已解决，原来是area_code类型有误。area_code必需是字符串。感谢vant的无私贡献~

**Comment by chenjiahan** [comment]
哈哈^_^
