### ISSUE TITLE
组件库使用了微软雅黑（Microsoft Yahei）字体，这个需要方正授权才能用吧

### ISSUE THREAD

**Issue by GreatAuk** [youzan/vant#12416]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/button

### Vant 版本

4.7.3

### 描述一下你遇到的问题。

微软雅黑（Microsoft Yahei）是商用字体

### 重现步骤

访问重现链接，审查文字元素，能看到 `font-family` 中含有：`Microsoft Yahei`

**Comment by inottn** [comment]
使用css指定字体和图片使用字体是两回事

**Comment by chenjiahan** [comment]
https://www.uisdc.com/microsoft-yahei-use-way

**Comment by GreatAuk** [comment]
好的，谢谢科普
