### ISSUE TITLE
uniapp 引入 vant2 , 运行报错 Module build failed (from ./node_modules/postcss-loader/src/index.js):

### ISSUE THREAD

**Issue by Git-lei** [youzan/vant#12421]
### Reproduction Link

*************************

### Vant Version

2.13.2

### Describe the Bug

npm i  之后， 运行 uniapp 项目， 就会提示 Module build failed (from ./node_modules/postcss-loader/src/index.js):
如图： 
![image](https://github.com/youzan/vant/assets/57174229/e7cf204e-9628-45bc-947b-739fb9b6d554)
解决办法 也很简单

修改 ~node_modules\vant\lib\index.css 文件， 
将 文件中的 “url” 改为 “ url”  
你没看错，加个空格就好了

### Reproduce Steps

npm i  之后， 运行 uniapp 项目， 就会提示 Module build failed (from ./node_modules/postcss-loader/src/index.js):
如图： 
![image](https://github.com/youzan/vant/assets/57174229/e7cf204e-9628-45bc-947b-739fb9b6d554)
解决办法 也很简单

修改 ~node_modules\vant\lib\index.css 文件， 
将 文件中的 “url” 改为 “ url”  
你没看错，加个空格就好了

### Device / Browser

uniapp-Hbuilderx

**Comment by wjw-gavin** [comment]
https://vant-ui.github.io/vant/#/zh-CN/faq#shi-fou-zhi-chi-zai-uni-app-zhong-shi-yong

**Comment by 13114871605** [comment]
改了还是没用啊
