### ISSUE TITLE
打包后，在安卓4.4系统打开空白 混合app+vant

### ISSUE THREAD

**Issue by zheng1013757145** [youzan/vant#1243]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
安卓4.4系统 利用打包工具打包 白屏.

**Screenshots**

**Environment**
 -华为4.4系统: 
 -无: 
 - Vant Version: 最新版

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
vant 本身是支持 android 4.4 的，建议你看下是不是代码中使用了一些比较新的特性

**Comment by zheng1013757145** [comment]
好的，我是直接引入的 

`<van-row>
  <van-col span="8">span: 8</van-col>
  <van-col span="8">span: 8</van-col>
  <van-col span="8">span: 8</van-col>
</van-row>`

这种形式能编译？

**Comment by chenjiahan** [comment]
可以编译滴
