### ISSUE TITLE
passwordinput的value值无法重置或清空

### ISSUE THREAD

**Issue by artiely** [youzan/vant#1244]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
passwordinput的在输入密码后设置value=""其实还是会保留之前输入的值，应该要清空

**Describe the solution you'd like**
passwordinput的在输入密码后设置value=""其实还是会保留之前输入的值

**What does the proposed API look like?**
当设置value=""时密码框清空

**Comment by chenjiahan** [comment]
试了一下没复现这个问题噢，直接设置 this.value = ''; 就可以重置的
