### ISSUE TITLE
[Feature Request] vant cell组件能够识别出图片url

### ISSUE THREAD

**Issue by JarvisChan666** [youzan/vant#12446]
### 这个功能解决了什么问题？

更统一一点，功能更完善，方便用户页面开发存头像

### 你期望的 API 是什么样子的？

不用这样实现
`
 <van-cell title="用户头像" to="/user/edit">
      <img :src="user.avatarUrl" style="height: 40px" />
    </van-cell>
`
而是
`
 <van-cell title="用户头像" :value="user.avatarUrl" to="/user/edit" />
`

**Comment by chenjiahan** [comment]
组件本身没法判断开发者是需要渲染一个「字符串」还是一个「图片」，所以还是由开发者处理比较合适 😄
