### ISSUE TITLE
Popover 气泡弹出框 只想实现 tooltip文字提示的功能

### ISSUE THREAD

**Issue by woniu99** [youzan/vant#12459]
### 这个功能解决了什么问题？

![image](https://github.com/youzan/vant/assets/17584813/338c9c3e-b73b-4bac-859b-622315bf1691)
文字超出后会显示异常

### 你期望的 API 是什么样子的？

可以只显示文字说明

**Comment by inottn** [comment]
可以通过默认插槽自定义内容和样式
