### ISSUE TITLE
[Bug Report]docs : Inconsistent translation of examples in`collapse`

### ISSUE THREAD

**Issue by RSS1102** [youzan/vant#12463]
### 重现链接

https://vant-ui.github.io/vant/#/en-US/collapse

### Vant 版本

4.8.0

### 描述一下你遇到的问题。

The translation of the example in `collapse`is inconsistent, and I'm not sure if it needs to be modified.

### 重现步骤

![image](https://github.com/youzan/vant/assets/81673017/18f1e7ff-d823-40cd-aeea-fed5dc86520f)

![image](https://github.com/youzan/vant/assets/81673017/4e1e9c62-1fa1-4e16-9ea5-5cb6f49bab6e)

**Comment by chenjiahan** [comment]
you can update that~ be consistent is better

**Comment by RSS1102** [comment]
> you can update that~ be consistent is better

I am happy to make it better.
I found that `showDialog` also has the same issue. Is it fixed on a new PR or this this PR?
> There is this sample code on showDialog：
```ts
const beforeClose = (action) =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve(action === 'confirm');
    }, 1000);
  });
 ```
 ```ts
const beforeClose = (action) =>
  new Promise((resolve) => {
    setTimeout(() => {
      if (action === 'confirm') {
        resolve(true);
      } else {
        // 拦截取消操作
        resolve(false);
      }
    }, 1000);
  });
  ```
  Their results are consistent, but which writing method should I follow?

**Comment by RSS1102** [comment]
I will divide it into two submissions to facilitate the marking of ci tags（i think）.
