### ISSUE TITLE
API文档页面嵌套手机模型怎么实现？

### ISSUE THREAD

**Issue by WaveStill** [youzan/vant#1246]
大佬：
       看到API文档页的 嵌套的iframe 手机模型很酷， 想问一下怎么实现的手机外壳， 求大佬指个方向

**Comment by chenjiahan** [comment]
手机外壳就是一个 fixed 的 iframe 元素，顶上放一张浏览器顶部条的图片~
实现的时候，要通过 iframe 同步父窗口和子窗口的路由，可以参考这个文件 https://github.com/youzan/vant/blob/dev/docs/src/utils/iframe-router.js

**Comment by WaveStill** [comment]
大概看了下， 不是太懂，把代码拉下来 跑跑吧，  谢谢大佬

**Comment by chenjiahan** [comment]
客气~
