### ISSUE TITLE
[Bug Report] css 旋转列表后,列表组件一直执行 load 事件

### ISSUE THREAD

**Issue by pangxieju** [youzan/vant#12468]
### 重现链接

https://codesandbox.io/p/sandbox/vant-4-issue-template-forked-m5jsm6

### Vant 版本

v4.6.4

### 描述一下你遇到的问题。
最近做的项目需求是内容横屏显示，且锁定了屏幕方向；
最后只能旋转元素来适配显示；
css 旋转列表后，列表组件一直触发 load 事件。

阅读源码后看到 useRect  方法里面获取的 width,height 使用的是 getBoundingClientRect 方法;
getBoundingClientRect  方法获取的是相对 viewport  值, 父节点旋转方向后，宽高交换了；
查阅了下文档，找到了 getComputedStyle 方法。该获取的是元素自身值，不受 css 旋转影响。

### 重现步骤

1.设置父元素旋转；
2.列表组件一直触发 load 事件。

### 设备/浏览器

所有浏览器

**Comment by chenjiahan** [comment]
这个不属于 bug，组件本身没有考虑适配 CSS 旋转这种特殊情况，如果有这个需求，建议自行封装组件来实现滚动加载。

getComputedStyle 和 getBoundingClientRect 所拿到的信息是不一样的，没法直接替换
