### ISSUE TITLE
[Bug Report] index-bar组件加上sticky-offset-top后 点击索引栏后高亮的字母不是选中的字母

### ISSUE THREAD

**Issue by jyp0912** [youzan/vant#12462]
### 重现链接

https://codesandbox.io/p/devbox/priceless-shape-nwvn49?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A22%2C16

### Vant 版本

4.8.0

### 描述一下你遇到的问题。

indexbar上方预留一个div实现其他功能，在点击索引栏字母后不会高亮点击的字母

### 重现步骤

在顶部时点击索引栏会正确定位，但高亮字母错误。滑动到底部后点击索引字母定位也错误。但是将cell组件增加到三个时，高亮字母正确，麻烦告知一下原因，感谢

### 设备/浏览器

Chrome

**Comment by inottn** [comment]
和 #12388 是同一个问题，这个先 close 了，后续会修复，谢谢反馈~
