### ISSUE TITLE
van-list    从其他页面返回时van-list页面，:immediate-check=“false”属性无效？

### ISSUE THREAD

**Issue by Fanaiwen** [youzan/vant#1247]
van-list    从其他页面返回时van-list页面，:immediate-check=“false”属性好像是无效的，还是会执行默认load事件

**Comment by yangguojin** [comment]
> van-list 从其他页面返回时van-list页面，:immediate-check=“false”属性好像是无效的，还是会执行默认load事件

请问你后来是怎么处理的？
