### ISSUE TITLE
[Bug Report] ImagePreview 无法添加`class-name`类名

### ISSUE THREAD

**Issue by RSS1102** [youzan/vant#12489]
### 重现链接

https://github.com/youzan/vant/issues/12488

### Vant 版本

 "vant": "^4.8.0",

### 描述一下你遇到的问题。

https://github.com/youzan/vant/issues/12488

在文档上说 `className`: 自定义类名。但是实际在代码里是添加到外层`<Popup/>`组件上的。
让用户会产生误会。
是否应该挂载在`ImagePreview.tsx`上。
或者是否应该在文档详细说明。

### 重现步骤

1.点击预览按钮
2.打开开发者模式，查看图片元素是否含有添加的类名

**Comment by inottn** [comment]
这里文档的描述可以优化下
