### ISSUE TITLE
[Bug Report] row gutter 数组+col span配置bug

### ISSUE THREAD

**Issue by yoyo837** [youzan/vant#12480]
### 重现链接

https://codesandbox.io/p/sandbox/vant-4-issue-template-forked-y9v57g?file=%2Fsrc%2FApp.vue%3A8%2C9

### Vant 版本

4.8.0

### 描述一下你遇到的问题。

gutter 数组配置，col为单个时最后一个可能没有padding-right， 导致内容不一样宽

<img width="1385" alt="image" src="https://github.com/youzan/vant/assets/6134547/8ad08fa9-ae89-4abd-a94f-082fece0fb78">

### 重现步骤

无

### 设备/浏览器

Chrome latest

**Comment by chenjiahan** [comment]
这个是已知问题，在这个话题下讨论：https://github.com/youzan/vant/discussions/11934

**Comment by chenjiahan** [comment]
因为目前没有合适的解决方案，discussion 不代表不解决，而是需要讨论有什么能解决的方法。
