### ISSUE TITLE
ImagePreview 无法添加class-name类名

### ISSUE THREAD

**Issue by xiangrikuil** [youzan/vant#12488]
### 重现链接

https://codesandbox.io/p/devbox/summer-voice-9fy3kz?file=%2Fsrc%2FApp.vue%3A5%2C6&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clprzc0b300073b6m30w46e71%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clprzc0b200023b6mut3m4q0a%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clprzc0b200043b6mrflbwac2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clprzc0b300063b6m9gaxjuko%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clprzc0b200023b6mut3m4q0a%2522%253A%257B%2522id%2522%253A%2522clprzc0b200023b6mut3m4q0a%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clprznkus00023b6myh3pj6gk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A6%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A6%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clprznkus00023b6myh3pj6gk%2522%257D%252C%2522clprzc0b300063b6m9gaxjuko%2522%253A%257B%2522id%2522%253A%2522clprzc0b300063b6m9gaxjuko%2522%252C%2522activeTabId%2522%253A%2522clprzc0b200053b6mfexdjsu6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clprzc0b200053b6mfexdjsu6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clprzhqjr00jh3b6mufbm8uve%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clprzc0b200043b6mrflbwac2%2522%253A%257B%2522id%2522%253A%2522clprzc0b200043b6mrflbwac2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clprzc0b200033b6m8uqu9qgf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%252C%257B%2522id%2522%253A%2522clprzhlw900ie3b6m0y7p8zpz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clprznl3g0015eehu95ybdyxj%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clprzc0b200033b6m8uqu9qgf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Vant 版本

4.8

### 描述一下你遇到的问题。

我想给ImagePreview 添加类名，但是在开发者模式下查下元素，看不到添加的类名
![image](https://github.com/youzan/vant/assets/80461300/d0b3eddb-e150-49ac-b1b7-d039c06318d7)

### 重现步骤

1.点击预览按钮
2.打开开发者模式，查看图片元素是否含有添加的类名

### 设备/浏览器

macOS/chrome /版本 119.0.6045.199（正式版本） (arm64)

**Comment by chouchouji** [comment]
你写的className不是挂到具体的每个image preview item或者 image preview 上的，是应用在popup上的
![image](https://github.com/youzan/vant/assets/70570907/5cd3d1fe-541c-42dc-b51b-10b474c2726f)
![image](https://github.com/youzan/vant/assets/70570907/e576b3a4-f8dc-443d-aced-35adeb221876)

**Comment by xiangrikuil** [comment]
> 你写的className不是挂到具体的每个image preview item或者 image preview 上的，而是被应用到popup上了 ![image](https://private-user-images.githubusercontent.com/70570907/287960570-5cd3d1fe-541c-42dc-b51b-10b474c2726f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjI1MzAsIm5iZiI6MTcwMTc2MjIzMCwicGF0aCI6Ii83MDU3MDkwNy8yODc5NjA1NzAtNWNkM2QxZmUtNTQxYy00MmRjLWI1MWItMTBiNDc0YzI3MjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA3NDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYmM2ZTU5MmY4YmI3MzEzNTI3YzJkODhlNTM3MWM1YjIyODMzZGIwNmNmMGFhNTEwNTEyMmRiNDYzOGNkMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BGY0uFoChjiQG8GwqgI-pSv71PQ1ymzwBWAtXp_AzEo) ![image](https://private-user-images.githubusercontent.com/70570907/287961253-e576b3a4-f8dc-443d-aced-35adeb221876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjI1MzAsIm5iZiI6MTcwMTc2MjIzMCwicGF0aCI6Ii83MDU3MDkwNy8yODc5NjEyNTMtZTU3NmIzYTQtZjhkYy00NDNkLWFjZWQtMzVhZGViMjIxODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA3NDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZjMzYjVjMTY4OTM2ZWEyZDkwMTk4MjQzZDJjYjI5NGYwZmM4MzU4ODQ2NDQyMmVmNGQ2MmEzNjJmNWMzYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kOne2b17kPIlQIgdPGX60YZwNcdNLvu_EdD8oBQ-YLI)

奥奥，这样子，不好意思
