### ISSUE TITLE
van-list 从其他页面返回时van-list页面，:immediate-check=“false”属性无效？

### ISSUE THREAD

**Issue by Fanaiwen** [youzan/vant#1248]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
van-list 从其他页面返回van-list页面时候，:immediate-check=“false”属性无效，仍旧会触发默认load事件。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device:  win10
 - Browser:  chrome
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
immediate-check 只能保证组件初始化的时候不会触发 load 事件，但是浏览器 scroll 事件触发的时候，依然会执行 load 的检查
