### ISSUE TITLE
[Feature Request] vant cli 不能配置顶部导航栏右侧的配置么，比如主题色切换

### ISSUE THREAD

**Issue by lmmmy** [youzan/vant#12490]
### 这个功能解决了什么问题？

我期望用vant cli 开发一个vue3组件库，目前主题色默认是dark，我想有切换能力，我看文档是传入darkModeClass，但是不生效

- [ ] 

### 你期望的 API 是什么样子的？

darkModeClass

**Comment by inottn** [comment]
可以提供一个能复现的代码仓库看看

**Comment by luyanghtml** [comment]
同问 怎么自定义导航栏
