### ISSUE TITLE
[Bug Report] Vant仓库main分支下载下来无法解析报@rsbuild+core@0.1.8无法解析

### ISSUE THREAD

**Issue by yueyunkeji** [youzan/vant#12495]
### 重现链接

无

### Vant 版本

4.8.0

### 描述一下你遇到的问题。

Vant仓库main分支下载下来无法解析报@rsbuild+core@0.1.8无法解析

### 重现步骤

下载源码使用node16.16版本，安装pnpm，接着pnpm install，最后pnpm dev

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
具体报错是什么，可以截图看下不

**Comment by yueyunkeji** [comment]
error   Compile error: 
Failed to compile, check the errors for troubleshooting.
error[internal]: Failed to resolve /Users/fly/Documents/中电项目/杭银项目/杭州银行移动端项目/组件库项目/vant/node_modules/.pnpm/@rsbuild+core@0.1.8/node_modules/@rsbuild/core/dist/client/hmr.js?&path=/rsbuild-hmr&port=8080 in project root

**Comment by yueyunkeji** [comment]
error   Compile error: 
Failed to compile, check the errors for troubleshooting.
error[internal]: Failed to resolve /Users/fly/Documents/组件库项目/vant/node_modules/.pnpm/@rsbuild+core@0.1.8/node_modules/@rsbuild/core/dist/client/hmr.js?&path=/rsbuild-hmr&port=8080 in project root

**Comment by yueyunkeji** [comment]
<img width="1427" alt="image" src="https://github.com/youzan/vant/assets/21034570/b900b281-e998-49b4-ae50-64024351fafd">

**Comment by yueyunkeji** [comment]
<img width="1434" alt="image" src="https://github.com/youzan/vant/assets/21034570/d93df98f-bab8-45ae-9fd3-f5b59bd7bf70">

**Comment by yueyunkeji** [comment]
然后我不下你们官方的源码，我找了一个别人上传的版本为4.0.0版本的就能正常安装依赖并运行，没有任何问题，我搞不懂你们最新版本怎么会有问题，或者你告诉我我应该用哪个版本比较好？

**Comment by chenjiahan** [comment]
这是 Rspack 某个版本不兼容「中文路径」导致的，我已经推送了升级版本到 Vant 仓库的主分支，你可以再试下

**Comment by yueyunkeji** [comment]
好的感谢
