### ISSUE TITLE
Field 里面的 slot 如果是 van-icon的话，点击触发区域偏离

### ISSUE THREAD

**Issue by syncml** [youzan/vant#1249]
**Describe the bug**
Field 里面的 slot 如果是 van-icon的话，点击触发区域偏离。要点icon的右边才能触发，好像我点击图标的时候，触发的是`@click-icon="message = ''"`

**Environment**
 - Device: 浏览器或者手机
 - Browser: chrome （手机上也是）
 - Vant Version: 1.1.5

**Reproduce**
```
    <van-cell-group>
      <van-field
        v-model="message"
        label="留言"
        placeholder="请输入留言"
        icon="clear"
        @click-icon="message = ''"
      >
        <van-icon slot="icon" name="play" @click="play"/>
      </van-field>
    </van-cell-group>
```

**Comment by chenjiahan** [comment]
Field 中的图标是禁用了 click 事件并使用 touch 事件的
之所以这么做，是为了防止点击图标后输入框失去焦点（click 时会触发 input 的 blue）
所以这个场景里直接使用 click-icon 事件就好

**Comment by syncml** [comment]
使用
```
<van-field
...
  placeholder="请输入留言"
      icon="clear"
        @click-icon="message = ''"
      >
```
这种方式的话，icon默认是不显示的，我想让它默认显示，有什么办法吗？

**Comment by chenjiahan** [comment]
@syncml 目前没有办法，下个版本优化一下这个问题

**Comment by chenjiahan** [comment]
已在 1.1.9 版本优化这个问题
