### ISSUE TITLE
nuxt3打包.van-popup会将.van-image-preview背景色覆盖，开发环境则不会

### ISSUE THREAD

**Issue by Fcode4** [youzan/vant#12494]
### 重现链接

无

### Vant 版本

4.0.0

### 描述一下你遇到的问题。

nuxt3打包.van-popup会将.van-image-preview背景色覆盖，开发环境则不会

### 重现步骤

打包后执行node .output/server/index.mjs

**Comment by chenjiahan** [comment]
参考 https://github.com/youzan/vant/issues/11950
