### ISSUE TITLE
Sku商品购买组件，基础用法例子里，（安卓手机微信浏览器）输入input在上半屏幕里，会出现看不到输入框的位置。。。

### ISSUE THREAD

**Issue by wwb568109135** [youzan/vant#125]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
你们的在线demo例子，Sku商品购买组件，基础用法例子里，（安卓手机微信浏览器）输入input在上半屏幕里，会出现看不到输入框的位置。。。

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**
可以看到输入框的位置
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by w91** [comment]
@wwb568109135 你好，能提供下你的安卓手机系统版本和手机型号吗，我这边找了几个没试出来
