### ISSUE TITLE
[Bug Report] van-uploader预览bug

### ISSUE THREAD

**Issue by boyla** [youzan/vant#12507]
### 重现链接

无链接，以实际现象为准

### Vant 版本

4.7.1

### 描述一下你遇到的问题。

图片上传组件的大图预览有bug, pc浏览器进入大图预览页，点击任意地方均不能退出预览页；手机浏览器可以正常退出

### 重现步骤

1.上传图片
2.点击图片，进入大图预览

**Comment by inottn** [comment]
参考 https://vant-ui.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei

**Comment by boyla** [comment]
不认可这个解决方案，因为vant本来就是一个库，有责任保持基本自洽，用户为了解决因为使用这个库而引入的问题，不得不引入其他库，这是不对的

**Comment by inottn** [comment]
> 不认可这个解决方案，因为vant本来就是一个库，有责任保持基本自洽，用户为了解决因为使用这个库而引入的问题，不得不引入其他库，这是不对的

Vant 是一个面向移动端的组件库，如果你需要在PC端使用，可以考虑其它PC端组件库。

**Comment by boyla** [comment]
估计现在的开发自己都不会研究代码，给出的方案也是毫无卵用。
多次求证后，给出pc版解决方案，适用于 4.7.1及以后版本：
为van-uploader组件添加属性 :preview-options="{ closeable: true }" ，此配置会在预览页右上方显示退出按钮，给pc用户提供退出出口
