### ISSUE TITLE
[Feature Request] Popup + Floating Panel

### ISSUE THREAD

**Issue by ManasMadrecha** [youzan/vant#12503]
### What problem does this feature solve?

Thanks for this amazing library 😊🙏🏻

Popup component pop ups from the bottom of the screen on some button click, but is not draggable or to be specific resizable. While Floating Panel is resizable with anchors but is always visible at the bottom of the screen. Can we have something that combines these two?

So basically, a component exactly like popup but is resizable with anchors and looks good with bouncy animation similar to Floating panel.

If already available, can you kindly provide some documentation. 

Thanks

### What does the proposed API look like?

.

**Comment by inottn** [comment]
Perhaps you can show or hide the Panel by changing the value of the `height` prop.
Here is a [demo](https://codesandbox.io/p/sandbox/vant-4-issue-template-forked-ksfz38), I'm not sure if this is the effect you are looking for.

**Comment by ManasMadrecha** [comment]
@inottn Thanks, works good, only one thing: it doesn't hide if clicked elsewhere at the top. 

Can we add Overlay component somehow into this demo so that perhaps the Panel closes if clicked elsewhere at the top, and not just the Hide button?

**Comment by inottn** [comment]
Of course, the demo has been updated. Vant provides overlay component that you can combine according to your needs.

**Comment by ManasMadrecha** [comment]
@inottn The demo link is not working. 😕
