### ISSUE TITLE
自定引入组件案例中基于vue-cli的vue.config.js进行配置后运行项目报ComponentsPlugin is not a function

### ISSUE THREAD

**Issue by yueyunkeji** [youzan/vant#12505]
### 重现链接

无

### Vant 版本

4.8.0

### 描述一下你遇到的问题。

<img width="1000" alt="image" src="https://github.com/youzan/vant/assets/21034570/b02817be-1f39-439d-9f0c-ca671170ecab">

### 重现步骤

1、新建vue-cli项目选择vue3;
2、安装本地npm pack打包的tgz文件，文件如vant-4.8.0.tgz;
3、yarn add @vant/auto-import-resolver unplugin-vue-components -D
4、基于 vue-cli 的项目，在 vue.config.js 文件中配置插件：
const { VantResolver } = require('@vant/auto-import-resolver');
const ComponentsPlugin = require('unplugin-vue-components/webpack');

module.exports = {
  configureWebpack: {
    plugins: [
      ComponentsPlugin({ resolvers: [VantResolver()] }), // 当 unplugin-vue-components 版本小于 0.26.0
      ComponentsPlugin.default({ resolvers: [VantResolver()] }), //当 unplugin-vue-components 版本大于等于 0.26.0
    ],
  },
};
然后 yarn serve，报ComponentsPlugin is not a function，具体如下图
<img width="1000" alt="image" src="https://github.com/youzan/vant/assets/21034570/b02817be-1f39-439d-9f0c-ca671170ecab">

### 设备/浏览器

谷歌

**Comment by wChenonly** [comment]
<img width="676" alt="image" src="https://github.com/youzan/vant/assets/37658262/6475a476-7b07-4d69-a173-4d6bc8db504d">
当unplugin-vue-components的版本号 小于0.26.0使用第一个，大于等于0.26.0使用第二个。   这2个不是共存的

**Comment by chenjiahan** [comment]
😂

**Comment by yueyunkeji** [comment]
那等于用那个，卧槽我眼瞎了，sorry，那么这个问题给我删了，有点丢人哈哈

**Comment by xuedengkui** [comment]
我也眼瞎了
