### ISSUE TITLE
优化CheckBox的最大可选数属性

### ISSUE THREAD

**Issue by mark3h** [youzan/vant#12504]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/checkbox#xian-zhi-zui-da-ke-xuan-shu

### Vant 版本

4.8.0

### 描述一下你遇到的问题。

现状：
目前CheckboxGroup如果设置了最大可选数，那么当选中的数目等于最大可选数时，剩余的Checkbox会自动被添加上disabled的属性（添加上.van-checkbox--disabled的类）。

优化：
我在业务层做了处理，实现了一种效果，当目前选择的数量，等于最大可选数时，再次点击其他Checkbox，会把之前选中的Checkbox，依次剔除掉。（类似于队列的效果）。

所以能不能添加一个属性，那么当选中的数目等于最大可选数时，可以通过属性控制其他Checkbox是否自动添加disabled的属性。

### 重现步骤

如上

**Comment by chenjiahan** [comment]
嗯嗯，可以有一个 props 来控制这个行为

**Comment by RSS1102** [comment]
`maxDisabled`?

**Comment by inottn** [comment]
有个疑问，当选中的数目等于最大可选数时，不想自动被添加上 disabled 的属性的原因是什么？是不想添加被禁用的样式吗，那不使用 max prop，而是通过外部去控制最大可选数的逻辑会不会更简单一点。

**Comment by RSS1102** [comment]
> 有个疑问，当选中的数目等于最大可选数时，不想自动被添加上 disabled 的属性的原因是什么？是不想添加被禁用的样式吗，那不使用 max prop，而是通过外部去控制最大可选数的逻辑会不会更简单一点。

他的想法可能是假设item=[1,2,3,4],max=3，他可以选中[1,2,3]之后，再选4的时候 modelValue[2,3,4],将第一个选中的取消。

**Comment by inottn** [comment]
> > 有个疑问，当选中的数目等于最大可选数时，不想自动被添加上 disabled 的属性的原因是什么？是不想添加被禁用的样式吗，那不使用 max prop，而是通过外部去控制最大可选数的逻辑会不会更简单一点。
> 
> 他的想法可能是假设item=[1,2,3,4],max=3，他可以选中[1,2,3]之后，再选4的时候 modelValue[2,3,4],将第一个选中的取消，以此类推。

我想了下，这类逻辑如果由开发者去实现的话似乎会更简单，而且可定制化的空间会更大些，比如[这样](https://codesandbox.io/p/sandbox/vant-4-issue-template-forked-p78xvz?file=%2Fsrc%2FApp.vue%3A21%2C36) 🤔

**Comment by RSS1102** [comment]
> > > 有个疑问，当选中的数目等于最大可选数时，不想自动被添加上 disabled 的属性的原因是什么？是不想添加被禁用的样式吗，那不使用 max prop，而是通过外部去控制最大可选数的逻辑会不会更简单一点。
> > 
> > 
> > 他的想法可能是假设item=[1,2,3,4],max=3，他可以选中[1,2,3]之后，再选4的时候 modelValue[2,3,4],将第一个选中的取消，以此类推。
> 
> 我想了下，这类逻辑如果由开发者去实现的话似乎会更简单，而且可定制化的空间会更大些，比如[这样](https://codesandbox.io/p/sandbox/vant-4-issue-template-forked-p78xvz?file=%2Fsrc%2FApp.vue%3A21%2C36) 🤔

是挺简单的，其实就是数组长度，然后对当长度超过，然后挨个移除modelValue的数组数据。
当然可能是为了用户更方便，让max的扩展性更大一点（毕竟max的实现方式从外部实现也是如此）

---
那我先不提pr了，写了一半了。等明天@chenjiahan 再评估一下再说咯。

**Comment by chenjiahan** [comment]
同意 @inottn 的观点，上述例子实现起来是比较简单的，也比较灵活
