### ISSUE TITLE
showImagePreview

### ISSUE THREAD

**Issue by a2734961** [youzan/vant#12518]
### 这个功能解决了什么问题？

images: string[]  的类型声明写死了 只能是
['jpg1','jpg2']
我想传入更多的参数比如
[{id:1,url:'jpg1'}]

这样我能做更多的拓展，比如chat聊天，如果只能给图片地址，服务器同样的图，地址是一样的，我只能在图片地址后面标记id，但是这样消耗性能，能否拓展一二？

### 你期望的 API 是什么样子的？

如上！！！

**Comment by inottn** [comment]
传入的更多的参数会在哪消费到
