### ISSUE TITLE
预览图片组件,横屏显示(1232*568)的时候, 对于长图,无法显示完整图片,不能向上滑动查看

### ISSUE THREAD

**Issue by lwy1152011997** [youzan/vant#12517]
### 重现链接

https://codesandbox.io/p/devbox/h8qsz6?file=%2Fsrc%2FApp.vue

### Vant 版本

4.7.2

### 描述一下你遇到的问题。

预览图片组件,横屏显示(1232*568)的时候, 对于长图,无法显示完整图片,不能向上滑动查看

### 重现步骤

一张670*945的长图,使用预览组件进行预览时候, 显示图片不完整, 放大后只能部分拖动
 <van-image-preview
      v-model:show="showPreview"
      :images="[imgUrl]"
      :show-index="false"
      :loop="false"
      :close-on-click-overlay="false"
      @close="previewClose"
    >

const imgUrl = ref(""); // 600*1000的图
const handleImgPreview = (url: string) => {
  showPreview.value = true;
  imgUrl.value = url;
};

const previewClose = () => {
  console.log("预览关闭");
  showPreview.value = false;
  }
};

### 设备/浏览器

移动端

**Comment by inottn** [comment]
重现的链接好像不对

**Comment by lwy1152011997** [comment]
我自己解决了问题,我的设备是1232*568的 长图的大小尺寸是500*1000的
我是这么处理的, 然后就可以了, 很奇怪.
  // vant  对长图预览时候不能滑动查看完整图的问题
  :deep(.van-image-preview__swipe-item) {
    overflow: auto;
    // overflow-scrolling: touch;
    // -webkit-overflow-scrolling: touch;
  }

  :deep(.van-image__img) {
    // object-fit: cover !important;
    max-width: 1232px;
    max-height: 568px;
    // height: auto!important;
  }

**Comment by inottn** [comment]
我这里无法复现，这会和设备有关系吗，有测试过在其他设备上也会复现这个问题吗。
当然如果能提供一个在线的重现示例，能更好的排查这个问题。
