### ISSUE TITLE
[Bug Report] ios 圆角属性 在cordava 嵌套的H5上 ，样式丢失导致的元素空白问题

### ISSUE THREAD

**Issue by LeungWinly** [youzan/vant#12514]
### 重现链接

无

### Vant 版本

3.5.2，

### 描述一下你遇到的问题。

 ios 圆角属性 在cordava 嵌套的H5上 ，样式丢失导致的元素空白问题

### 重现步骤

 ios 圆角属性 在cordava 嵌套的H5上 ，样式丢失导致的元素空白问题

### 设备/浏览器

iOS
```[tasklist]
### Tasks
```

**Comment by LeungWinly** [comment]
> ### 重现链接
> 无
> 
> ### Vant 版本
> 3.5.2，
> 
> ### 描述一下你遇到的问题。
> ios 圆角属性 在cordava 嵌套的H5上 ，样式丢失导致的元素空白问题
> 
> ### 重现步骤
> ios 圆角属性 在cordava 嵌套的H5上 ，样式丢失导致的元素空白问题
> 
> ### 设备/浏览器
> iOS
> 
> ### Tasks
> 
> Beta
> [Give feedback](https://github.com/community/community/discussions/39106)
> 
> No tasks being tracked yet.
> 1. [ ] 
>                    
>                  
>    
>                  
>                    
>                      
>    
>                    
>                      
>                  
>                
>                
>                  
>      
>          
>        
>    
>    Options
>    
>    
>    
>      
>        
>                    
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
> 2.

![image](https://github.com/youzan/vant/assets/26197079/0ccd819a-6dcb-43d8-88ca-b198eaff57da)

**Comment by LeungWinly** [comment]
这样写就可以解决
![image](https://github.com/youzan/vant/assets/26197079/9ed63bc3-1674-4067-b58e-34f9053ca968)

**Comment by chenjiahan** [comment]
这个问题可以给 cordava 反馈，圆角这种常见的 CSS 样式不应该通过特殊样式 hack 才能支持
