### ISSUE TITLE
van-address-list和van-address-edit文字显示乱码

### ISSUE THREAD

**Issue by linfayi** [youzan/vant#12510]
### 重现链接

https://github.com/youzan/vant

### Vant 版本

2.12.27

### 描述一下你遇到的问题。

![image](https://github.com/youzan/vant/assets/93806747/2f71a428-2c00-4289-aa6c-bc04bec32912)
![image](https://github.com/youzan/vant/assets/93806747/d009bc79-7aee-416b-a2b1-250c3af557c3)

### 重现步骤

本地环境显示正常，生产环境显示乱码

### 设备/浏览器

微信浏览器

**Comment by boogie713** [comment]
我也出现了这种乱码的问题 连续两天了 有什么解决办法啊
![Snipaste_2023-12-16_15-20-00](https://github.com/youzan/vant/assets/49613141/f8b292cc-d4aa-4e64-8af5-64781042c565)

**Comment by chenjiahan** [comment]
这个应该是特定 CDN 服务的问题，而不是 Vant 代码的问题。

目前我访问上述链接是正常的：

![image](https://github.com/youzan/vant/assets/7237365/bbe80f41-5759-4e26-ac2d-1abaa501e8e0)
