### ISSUE TITLE
[Feature Request] TreeSelect 分类选择 左侧区域自定义插槽

### ISSUE THREAD

**Issue by Wdam** [youzan/vant#12515]
### 这个功能解决了什么问题？

希望组件左侧能出自定义插槽，通过点击事件可以全选右侧，也可以弥补vant没有树形组件的问题

### 你期望的 API 是什么样子的？

```
```

**Comment by inottn** [comment]
可以试试 `nav-text` 这个插槽

**Comment by inottn** [comment]
> > 可以试试 `nav-text` 这个插槽
> 
> 我并没有搜索到相关用法，请问是可以在vant2里使用的吗

在 vant4 支持，vant2 目前已经停止迭代新功能了

**Comment by Wdam** [comment]
> > > 可以试试 `nav-text` 这个插槽
> > 
> > 
> > 我并没有搜索到相关用法，请问是可以在vant2里使用的吗
> 
> 在 vant4 支持，vant2 目前已经停止迭代新功能了

好吧
