### ISSUE TITLE
密码框和数字键盘搭配使用，华为机型出现监听bug

### ISSUE THREAD

**Issue by tianci-06** [youzan/vant#12513]
### Vant 版本

4.0.10

### 描述一下你遇到的问题。

输入5位之后就输入不了了，后面好像又输入了个4，但input值没有监听同步到。

https://github.com/youzan/vant/assets/153273926/78050bd4-478f-463c-bcd0-7d9ad645941d

### 重现步骤

附上视频

### 设备/浏览器

华为:型号：ALP-AL00

**Comment by inottn** [comment]
可以确认一下，最新版的 vant 还会复现这个问题吗

**Comment by tianci-06** [comment]
好的，谢谢，问题原因已找到，不是组件的原因。
