### ISSUE TITLE
[Bug Report] cdn报错

### ISSUE THREAD

**Issue by boogie713** [youzan/vant#12511]
### Reproduction Link

无

### Vant Version

2.12.12 

### Describe the Bug

![4511e67c153772f9efec2589f9e36ed2](https://github.com/youzan/vant/assets/49613141/21c29c28-e22d-44ef-90f2-30974b3e5897)

### Reproduce Steps

cdn引入后页面组件乱码

**Comment by chenjiahan** [comment]
参考：https://github.com/youzan/vant/issues/12510
