### ISSUE TITLE
在使用AddressEdit的时候,地址无法显示

### ISSUE THREAD

**Issue by yuantongkang** [youzan/vant#1252]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在使用AddressEdit的时候,地址无法显示,一直显示loading

**Screenshots**
![](http://onb5ufwvw.bkt.clouddn.com/ll.gif)

**Environment**
 - Device: windows PC
 - Browser: chrome Version 66.0.3359.181 (Official Build) (32-bit)
 - Vant Version: 1.1.7

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.

**Comment by chenjiahan** [comment]
请确认是否传入了 area-list 数据
