### ISSUE TITLE
[Bug Report] 在钉钉内使用安卓手机上传文件名内包含%2f(/的url转义)时，上传组件没有反应

### ISSUE THREAD

**Issue by zzzmm11111** [youzan/vant#12537]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-9r5lnj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqnntcwm00073b6iypizhgqh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqnntcwl00023b6i1pdhlmmb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqnntcwl00043b6i5zpvcwgl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqnntcwm00063b6i8lvljuzw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqnntcwl00023b6i1pdhlmmb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqnntcwl00013b6i80b1nrnt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqnnwqbm004j3b6iq79uptcl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A6%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A6%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqnntcwl00023b6i1pdhlmmb%2522%252C%2522activeTabId%2522%253A%2522clqnnwqbm004j3b6iq79uptcl%2522%257D%252C%2522clqnntcwm00063b6i8lvljuzw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqnntcwm00053b6isygt5zla%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8080%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqnntcwm00063b6i8lvljuzw%2522%252C%2522activeTabId%2522%253A%2522clqnntcwm00053b6isygt5zla%2522%257D%252C%2522clqnntcwl00043b6i5zpvcwgl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqnntcwl00033b6iw7zrzwt0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clqnntcwl00043b6i5zpvcwgl%2522%252C%2522activeTabId%2522%253A%2522clqnntcwl00033b6iw7zrzwt0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

在钉钉内使用上传组件时，使用安卓手机，使用上传组件上传文件名内包含%2f、%2F(/的url转义)时，上传组件会没有任何反应，before-read也没有反应

### 重现步骤

1. 准备一个安卓手机，复制重现链接到钉钉里，打开这个链接
2. 准备一个文件名里包含%2f的文件，比如test%2ftest.jpg，把他上传
3. 他不会添加到上传列表里，也不会触发before-read

### 设备/浏览器

钉钉7.1.17、安卓12

**Comment by zzzmm11111** [comment]
为什么我的重现链接这么长？希望我复制对了

**Comment by wwhwwhwwh** [comment]
钉钉的bug，文件名为`test%2ftest.jpg`，没有触发  `input` 的`onChange` 事件

**Comment by chenjiahan** [comment]
可以反馈给钉钉哈，Vant 无法处理这类问题
