### ISSUE TITLE
van-list loading 设为false还是显示加载中,如果数据为空直接finished=false还是继续显示加载中

### ISSUE THREAD

**Issue by CharlesSong** [youzan/vant#1253]
**Describe the bug**
van-list loading 设为false还是显示加载中,如果数据为空直接finished=false还是继续显示加载中

**Screenshots**

**Environment**
 - Device: 
 - Browser:  微信开发者工具
 - Vant Version: 1.1.7

**Reproduce**
```
<template>
    <div>
        <van-list v-model="loading" :loading="loading" :finished="finished" @load="onLoad">
            <van-cell v-for="item in list" :key="item" :title="item + ''" />
        </van-list>
    </div>
</template>
<script>
import { List, Cell } from 'vant'
export default {
  data() {
    return {
      loading: false,
      finished: false,
      list: []
    }
  },
  components: {
    [List.name]: List,
    [Cell.name]: Cell
  },
  methods: {
    onLoad() {
      setTimeout(() => {
        this.finished = true
      }, 3000)
    }
  }
}
</script>

```

**Comment by chenjiahan** [comment]
处于 loading 状态时，设置 loading = false 或者 finished = true 都可以结束加载状态噢

**Comment by Ikarows** [comment]
> 处于loading状态时，设置loading = false或者finished = true都可以结束加载状态噢

你好，我设置了loading为false之后，还是显示了正在加载中是怎么回事?

**Comment by chenjiahan** [comment]
@Ikarows 理论上不会出现这样的情况，建议看下是否正确设置了 loading

**Comment by Ikarows** [comment]
> @Ikarows 理论上不会出现这样的情况，建议看下是否正确设置了 loading
`<van-list v-model="loading" :finished="finished"></van-list>`
`data () {
    return {
      loading: false, // 显示加载更多
      finished: false
   }
}`

**Comment by FOOSO** [comment]
> > @Ikarows 理论上不会出现这样的情况，建议看下是否正确设置了 loading
> 
> 代码是这样的：
> 
> `<van-list v-model="loading" :finished="finished"></van-list>`
> `data () { return { loading: false, // 显示加载更多 finished: false } }`
> 
> finished 的控制能正常，但 loading 无效

同样的问题,可以用finished去控制,但是改变loading的状态无法改变
