### ISSUE TITLE
[Bug Report] van-tabs 使用 sticky 后，切换 tab sticky 展示问题

### ISSUE THREAD

**Issue by Sirros** [youzan/vant#12535]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-xpdnz8?file=%2Fsrc%2FApp.vue%3A7%2C38

### Vant 版本

4.8.1

### 描述一下你遇到的问题。

在 van-tabs 中使用了 sticky，在某个 tab 下滚动后，吸顶成功，切换 tab 后，会回到顶部，tab title 被 van-nav-bar 覆盖，不太清楚这是正确的展示还是说是bug

### 重现步骤

在某个 tab 下滚动后，切换 tab，观察顶部吸顶效果

**Comment by inottn** [comment]
NavBar 的 z-index prop 设置为 0 试试

**Comment by wwhwwhwwh** [comment]
Sticky 组件的 `offset-top` 可以解决
第一种:透传属性, 传入 nav-bar的高度,默认是`46` 
```js
<van-tabs  v-model="tabActive"  sticky  :offset-top="46" >
```
第二种: css覆盖，这种视觉上会闪一下
```css
.box .van-tabs .van-sticky.van-sticky--fixed {
  top: var(--van-nav-bar-height) !important;
}
``

**Comment by nemo-shen** [comment]
初步判断这是一个bug

## 现象描述：
1. 当滚动列表时 tabs sticky 生效，会增加 class `van-sticky--fixed`
2. 当手动点击 tabs 上的 `van-sticky--fixed` 被移除

van-sticky--fixed 的默认 `z-index` 值是 `99`
van-tab 组件的默认 `z-index` 值是 `1`

## 修复方法是：
手动点击 `tab` 时，应该判断 当前 `sticky` 状态，如果是吸顶状态则不应该移除 class `van-sticky--fixed`

**Comment by Sirros** [comment]
> @Sirros
> 
> 使用姿势本身也存在问题，`<VanNavBar fixed title="pageTitle" />` 本身也是固定在顶部的，必定会出现重叠的情况，最好的做法是增加 tab 偏移量，例如 `<Tabs sticky :offset-top="46" />`

是的，使用姿势有点问题，已经做出调整

**Comment by Sirros** [comment]
> NavBar 的 z-index prop 设置为 0 试试

这个设置在当前场景下可以解决，感谢
