### ISSUE TITLE
[Bug Report] 在vue3.4x && nuxt3.9.0 版本中使用van-field组件出现水合错误

### ISSUE THREAD

**Issue by yapengsoft** [youzan/vant#12548]
### 重现链接

https://stackblitz.com/edit/github-wbtk3d-9vyncy

### Vant 版本

4.8.2

### 描述一下你遇到的问题。

我在nuxt3.9.0版本中（版本依赖vue最新的3.4版本）出现水合错误 目前只发现使用van-filed组件有这个问题
我确定是使用了vue最新版本导致问题 当我使用vue3.3版本则没有这个错误
![image](https://github.com/youzan/vant/assets/75244754/2bd5a4f6-e405-40c3-810c-00da2640c377)
看报错是因为每次刷新van-field-数字-input  这个数字每刷新一次在服务端会递增一次 在客户端则一直是van-field-1-input 导致的问题
我不确定组件是否存在兼容问题什么的所以反馈一下   谢谢你们辛苦工作🙏

### 重现步骤

直接使用van-field 组件

### 设备/浏览器

浏览器

**Comment by inottn** [comment]
看上去像 vue 的 bug

**Comment by RSS1102** [comment]
> 看上去像 vue 的 bug

是`current` 在nuxt内没有正确重置嘛？（还是说又重新累加了？）

**Comment by yapengsoft** [comment]
[https://github.com/vuejs/core/issues/10000](url)
应该就是vue的问题了  别的ui框架也出现类似的问题 等修复叭

**Comment by chenjiahan** [comment]
嗯嗯，可以等 Vue 处理，当前 issue 先关闭了哈

**Comment by yapengsoft** [comment]
vue修复了 好像还是存在这个问题 （最新的vue版本）

**Comment by yapengsoft** [comment]
这个水合问题麻烦你们再看看吧  不止field组件
![image](https://github.com/youzan/vant/assets/75244754/25fed6ac-0504-4044-b610-aa2aee6c9be2)
![image](https://github.com/youzan/vant/assets/75244754/63fd8f66-e7f0-4e87-8d9c-c7c31f33f038)
虽然它不影响组件显示  但是真的开发看这一堆黄色警告很难受  @chenjiahan

**Comment by inottn** [comment]
看了下，应该和 vue 没有关系。这个问题应该一直都有，只不过 vue3.4.x 把这个提示在开发环境抛出来了。

**Comment by yapengsoft** [comment]
那准备怎么解决还是就这样保持下去

**Comment by inottn** [comment]
如果有任何人对这个问题感兴趣，欢迎尝试解决。

**Comment by inottn** [comment]
> 那准备怎么解决还是就这样保持下去

会尝试解决这个问题，如果你有任何好的解决方案，欢迎在此讨论。

**Comment by yapengsoft** [comment]
谢谢  我是没时间了 写着nuxt 还要写后端  留给你们和挑战者吧  这些警告太影响开发调试了 辛苦你们了

**Comment by yapengsoft** [comment]
nuxt3.10.0 已解决该问题  测试了一下已经不再有水合警告错误
![image](https://github.com/youzan/vant/assets/75244754/f3047c56-738f-4ce7-adfd-0a853c6c2f9e)

**Comment by yapengsoft** [comment]
> > nuxt3.10.0 已解决该问题 测试了一下已经不再有水合警告错误![图像](https://private-user-images.githubusercontent.com/75244754/301025481-f3047c56-738f-4ce7-adfd-0a853c6c2f9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDY0NDgsIm5iZiI6MTcxNzE0NjE0OCwicGF0aCI6Ii83NTI0NDc1NC8zMDEwMjU0ODEtZjMwNDdjNTYtNzM4Zi00Y2U3LWFkZmQtMGE4NTNjNmMyZjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA5MDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NWI4MTU2MGQ1ZjE0NDliODMxMzQ3YjkyNmIyYzk0YTFjYjJkZThmMDA2MzA4ODIxZTk5M2YxN2QwZmJkYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VNCccrlqZSkby-fT5JDC9_qbPwQzaIRatOL8_2rRbo)
> 
> @yapengsoft 请问有尝试过更新的nuxt版本吗？我这边nuxt为3.11.2，vant为4.9.0，还是会有这个问题，Field组件有同样的警告。

没  我们项目经理要求我们换 其他 ui 了  没再试过了  有空我本地再折腾看看
