### ISSUE TITLE
useCountDown 建议新增缓存功能

### ISSUE THREAD

**Issue by Cyan-963852** [youzan/vant#12545]
### 这个功能解决了什么问题？

作为网页来讲，倒计时一般都是真实时间，如果不设置浏览器缓存或者本地缓存，当用户刷新后倒计时会清零从而越过程序判断进行下一步操作会产生意想不到的bug。建议新增缓存机制，使得用户刷新后倒计时也会继续进行。

### 你期望的 API 是什么样子的？

storage="session | local"

**Comment by nemo-shen** [comment]
我不认为这是 `countdown` 应该提供的能力，这会造成逻辑冲突
试想一下，你既定义了 `time` 又开启了组件缓存能力，那么初始的 time 应该拿你提供的 `prop time` 的值，还是 `cache time` 的值？

我提供给你一个方案，你可以直接赋值，并使用它
```ts
<script setup lang="ts">
import VanCountDown, { type CountDownCurrentTime } from 'vant';
import { ref } from 'vue';

const time = ref(
  Number(localStorage.getItem('van-count-down-time')) || 30 * 60 * 60 * 1000,
);
const remainTime = ref(time.value);

const onChange = (currentTime: CountDownCurrentTime) => {
  remainTime.value = currentTime.total;
  localStorage.setItem('van-count-down-time', remainTime.value.toString());
};
</script>
```

```html
<template>
  <van-count-down :time="time" @change="onChange" />
</template>
```

**Comment by inottn** [comment]
有没有缓存，都不应该仅依赖客户端的时间保证程序能正常运行。useCountDown 只是提供基础的倒计时管理能力。你可以基于此封装更高级的功能。
