### ISSUE TITLE
[Bug Report] 表单validator选填，不填写内容触发校验

### ISSUE THREAD

**Issue by jackjtr** [youzan/vant#12557]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-mcm25d?file=%2Fsrc%2FApp.vue%3A23%2C1

### Vant 版本

4.8.0

### 描述一下你遇到的问题。

表单字段校验规则，required: false的情况下触发校验，提交失败

根据 https://github.com/youzan/vant/issues/7067 的描述，不填写应该可以提交，只有填写了且校验失败才提示

### 重现步骤

打开重现链接，不输入任何内容，点击提交按钮

### 设备/浏览器

Windows Chrome

**Comment by inottn** [comment]
设置 validateEmpty 为 false

**Comment by jackjtr** [comment]
> 设置 validateEmpty 为 false

没注意到这个配置，但是这样做感觉和在validator里面判断效果相同……
因为情景是不填可以(required=false)，但是填了必须符合格式(触发validator)

**Comment by inottn** [comment]
因为这个场景假定了 required 的优先级要更高。但其实所有校验项的优先级是一样的，必须都满足才通过校验。

**Comment by jackjtr** [comment]
> 因为这个场景假定了 required 的优先级要更高。但其实所有校验项的优先级是一样的，必须都满足才通过校验。

代码执行顺序难道不就代表优先级吗
不纠结，毕竟又不是不允许validator处理空值
