### ISSUE TITLE
[Bug Report] When use van-notify component call. The mounted dom is parent dom, But function call mounted dom is document body.

### ISSUE THREAD

**Issue by summercongcong** [youzan/vant#12555]
### Reproduction Link

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-zt4hgn?file=%2Fsrc%2FApp.vue%3A31%2C7

### Vant Version

4.6.4

### Describe the Bug

When use van-notify component call. The mounted dom is parent dom, But function call mounted dom is document body.

### Reproduce Steps

Please look "Reproduction Link"

**Comment by nemo-shen** [comment]
@summercongcong 
This is not a bug. Functional call will create a new vue app using `createApp` and mount it to document.
You can see: https://github.com/youzan/vant/blob/main/packages/vant/src/notify/function-call.tsx#L12-L19
Additionally, all `function-call` are used in a similar way, for example: `dialog` `toast`

**Comment by nemo-shen** [comment]
@summercongcong

I can't get your issue, if your want the notify dom mount to body, you can use `<Teleport />`

like this:
```ts
<script setup lang="ts">
import { ref } from 'vue';
import { Notify as VanNotify } from '..';

const show = ref(false);

const showNotifyComponent = () => {
  show.value = true;
};
</script>
```

```html
<template>
  <button @click="showNotifyComponent">show notify component</button>

  <Teleport to="body">
    <van-notify v-model:show="show" type="success">
      <span>Notify Content</span>
    </van-notify>
  </Teleport>
</template>
```

**Comment by inottn** [comment]
I understand your question. Toast, a component similar to Notify that is also based on Popup, supports the teleport prop. However, Notify does not support it. To maintain consistency, and considering that this prop is useful in certain scenarios, the teleport prop can be added to the Notify component. In the meantime, you can use the approach provided by @nemo-shen to solve this problem.

**Comment by summercongcong** [comment]
Certainly Teleport can solve my problem. In the meantime @inottn suggetion is also correct.
