### ISSUE TITLE
官网关于Lazyload的使用，在初始化Lazyload时，注册时可选的配置参数preload应为preLoad，类型为number  

### ISSUE THREAD

**Issue by wuchuzhengzhong** [youzan/vant#12553]
### Reproduction Link

https://vant-contrib.gitee.io/vant/#/zh-CN/lazyload

### Vant Version

4.0

### Describe the Bug

官网关于Lazyload的使用，在初始化Lazyload时，注册时可选的配置参数preload应为preLoad，类型为number  

### Reproduce Steps

官网可见

**Comment by RSS1102** [comment]
好像是的：https://github.com/youzan/vant/blob/b6a1c00e95da1ef4055326f42e06e6a9ff4a92e2/packages/vant/src/lazyload/vue-lazyload/index.d.ts#L33
