### ISSUE TITLE
DropdownMenu嵌套在 Tabs 等组件内部使用时下拉菜单位置错误

### ISSUE THREAD

**Issue by youpeng-863** [youzan/vant#12559]
### Discussed in https://github.com/youzan/vant/discussions/12558

<div type='discussions-op-text'>

<sup>Originally posted by **youpeng-863** January  9, 2024</sup>
![企业微信截图_17048020136408](https://github.com/youzan/vant/assets/54803062/2d1be304-3a81-489e-83b1-d138c7d92403)
如图所示使用的vant版本为4.8.2，按照官网描述分别在DropdownItem和DropdownMenu设置了teleport="body"和auto-locate，每次进入系统时显示是正常的，如下图所示：
![image](https://github.com/youzan/vant/assets/54803062/305aeb0c-0a26-41d1-8fca-55d389e36e25)
但是如果跳转到下一个路由再使用history.back()返回（返回后的页面重新加载数据），那么下拉菜单的位置就会错乱，如下图所示
![image](https://github.com/youzan/vant/assets/54803062/e1d85982-bd29-4b0c-bd8b-8f299daab82f)
![image](https://github.com/youzan/vant/assets/54803062/a7c6ae2d-2fe2-48bb-8b9f-2c0c108bf78a)
ps：如果仅仅从上一个路由进入的时候并不会发生这样的问题
</div>

**Comment by inottn** [comment]
一般 teleport 和 auto-locate 不会同时使用，你可以试一下只使用 teleport 还会有这个问题吗。

auto-locate 适用于修正父级元素应用了 transform 样式时可能出现的定位偏差。

**Comment by youpeng-863** [comment]
在线的测试实例已经提供 https://weixin.zjcarcb.cn/QWApp/#/TestListHome；进入测试页后正常，但是点击新增按钮到下一个路由再返回就会出现问题，目前该实例中仅仅使用了auto-locate，关于你的建议如果需要我可以再次提供另一个测试实例。
但是有个很奇怪的问题，我在本地测试的时候并没有发现此问题，打包部署上线后就会出现。

**Comment by youpeng-863** [comment]
以下是两个测试实例的具体代码，与真实环境的差别就是去掉了鉴权和载入的数据是静态数据const listData = ref(Test.list);
[TestListHome.txt](https://github.com/youzan/vant/files/13882171/TestListHome.txt)
[TestReportHome.txt](https://github.com/youzan/vant/files/13882172/TestReportHome.txt)

**Comment by youpeng-863** [comment]
仅使用teleport 的实例也已经提供 https://weixin.zjcarcb.cn/QWApp/#/TestListHome2
但似乎存在同样的问题。

**Comment by youpeng-863** [comment]
> 一般 teleport 和 auto-locate 不会同时使用，你可以试一下只使用 teleport 还会有这个问题吗。
> 
> auto-locate 适用于修正父级元素应用了 transform 样式时可能出现的定位偏差。
两个实例都已经提供但都没有解决问题

**Comment by inottn** [comment]
看了一下，和 teleport 或是 auto-locate 属性无关，因为跳转返回后，.van-dropdown-item__content 类的样式被覆盖掉了。

不清楚你项目具体的构建配置，你可以暂时通过设置 van-dropdown-item__content 的样式解决这个问题：

```css
.van-dropdown-item__content {
  position: absolute !important;
}
```

**Comment by youpeng-863** [comment]
暂时使用teleport="body"并添加样式
`.van-dropdown-item__content {
  position: absolute !important;
}
.van-dropdown-item__option--active {
	color: var(--van-dropdown-menu-option-active-color) !important;
}`
解决了问题，但样式为什么被覆盖暂时没找到问题，我们会在后续工作中持续关注这个问题，这两个测试实例将持续开放至1月15日，如果您有兴趣可以继续查看，需要配合也可以尽管留言或联系微信13849103232，我们将尽力配合调查，或者您可以直接关闭这个问题。
