### ISSUE TITLE
tabs设置sticky后，当tab吸顶后再次切换tab不会自动置顶

### ISSUE THREAD

**Issue by yanbowe** [youzan/vant#12568]
### Reproduction Link

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-kswrjp?file=%2Fsrc%2FApp.vue%3A5%2C44

### Vant Version

4.8.1

### Describe the Bug

NavBar设置fixed和placeholder后，设置tabs为sticky，第一个标签向下滚动至tabs吸顶，切换至第二个tab发现tabs无法吸顶，会隐藏至NavBar下，容易产生误解
<img width="1436" alt="image" src="https://github.com/youzan/vant/assets/43030980/44b599ec-b14b-4377-9d17-76294789dc22">

### Reproduce Steps

希望tabs吸顶后，再次切换tab可以保持吸顶（内容足一屏的情况下）

### Device / Browser

Chrome

**Comment by inottn** [comment]
这个问题可能已经解决了，等 4.8.3 发布后可以再试一下

**Comment by yanbowe** [comment]
已看到相关[PR](https://github.com/youzan/vant/pull/12547)
