### ISSUE TITLE
[Feature Request] Allow `cancel-button-text` and `confirm-button-text` etc to be false

### ISSUE THREAD

**Issue by mahnunchik** [youzan/vant#12562]
### What problem does this feature solve?

It would be helpful to be able to hide cancel/confirm text from Picker.

### What does the proposed API look like?

```js
<van-picker
  :confirm-button-text="false"
  :columns="columns"
/>
```

**Comment by mahnunchik** [comment]
Current solution is to override `confirm` slot but it is requires more code.

**Comment by mahnunchik** [comment]
https://github.com/youzan/vant/blob/dbf8027c2d9b538694ffd5889ba9f4010d93fb6a/packages/vant/src/picker/PickerToolbar.tsx#L55-L63

**Comment by chenjiahan** [comment]
We can add new show-confirm-button and show-cancel-button props and keep confirm-button-text as string type

**Comment by mahnunchik** [comment]
@chenjiahan Yes, it is one of possible solutions.

But my point of view, that `show-*` props for all `*-text` texts may encrise amount of props almost twice.

Another option is to fix handling **empty** strings here https://github.com/youzan/vant/blob/dbf8027c2d9b538694ffd5889ba9f4010d93fb6a/packages/vant/src/picker/PickerToolbar.tsx#L55 to be able to render empty sting by `:confirm-button-text=""` as expected.

I mean something like the following:

```js
const text = props.confirmButtonText !== undefined ?  props.confirmButtonText : t('confirm');
```

**Comment by chenjiahan** [comment]
Yes, this is also a feasible solution, and I remain open to it.
