### ISSUE TITLE
vue 升级到3.4.5 后 showLoadingToast  出现【vue warn】

### ISSUE THREAD

**Issue by suncohey** [youzan/vant#12563]
### 重现链接

/

### Vant 版本

4.8.2

### 描述一下你遇到的问题。

vconsole@3.14.6.min.js:10  [Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 
  at <BaseTransition onAfterEnter=fn<onOpened> onAfterLeave=fn<onClosed> appear=false  ... > 
  at <Transition name="van-fade" appear=false onAfterEnter=fn<onOpened>  ... > 
  at <VanPopup class="van-toast van-toast--middle van-toast--text" lockScroll=false onClick=fn<onClick>  ... > 
  at <VanToast show=false onClosed=fn<onClosed> onUpdate:show=fn<toggle> > 

### 重现步骤

`https://codesandbox.io/p/devbox/github/suncohey/vue3ye/tree/vantBug/?file=%2Fsrc%2FProject%2Fbc_a_1%2FApp.vue`

yarn dev
### 设备/浏览器

_No respo

**Comment by li-wanbin** [comment]
重现示例：https://stackblitz.com/edit/vitejs-vite-ry4cmm?file=package.json,src%2FApp.vue&terminal=dev

**Comment by inottn** [comment]
初步看了下是 vue 3.4.6 和 3.4.7 版本之间的一个改动引入了这个问题，它仅在开发环境会出现。根据改动的目的来看，在这个场景下触发警告应该是意料之外的。

因为这个问题涉及到上游，目前还不确定如何解决以及何时能够解决。如果有任何人对这个问题感兴趣，欢迎尝试解决。

**Comment by chaselen** [comment]
我也遇到这个，不知有没有什么影响

**Comment by inottn** [comment]
@chenjiahan 需要增加一个 upstream 的 label

**Comment by chenjiahan** [comment]
@inottn 已加～ https://github.com/youzan/vant/labels/upstream

**Comment by inottn** [comment]
vue 3.4.15 已经修复这个问题
