### ISSUE TITLE
能否增加如flex，transform等css属性的厂商前缀，以兼容如ios8等系统

### ISSUE THREAD

**Issue by 19910622** [youzan/vant#1257]
注意到许多css3属性没有webkit前缀，导致ios8中出现大面积的无法使用的情况，是否可以酌情增加必要的厂商前缀

**Comment by chenjiahan** [comment]
请问哪个属性没加前缀喔

**Comment by 19910622** [comment]
目前遇到主要是popup组件，包括但不限于van-picker__toolbar的flex属性，van-popup--bottom的transform属性以及van-picker-column内ul元素的行内transform属性

**Comment by chenjiahan** [comment]
https://unpkg.com/vant@1.1.7/es/vant-css/popup.css
https://unpkg.com/vant@1.1.7/es/vant-css/picker.css
这些前缀都是有的，估计是你项目里的 autoprefixer 配置有问题，把前缀移除了
