### ISSUE TITLE
[Bug Report] vite5.0 按需引入

### ISSUE THREAD

**Issue by a2734961** [youzan/vant#12574]
### 重现链接

没法复现，开发环境才有

### Vant 版本

5.0.11

### vue 版本

3.4.14

代码在vite.config.ts里
Components({
  resolvers: [VantResolver()]
})
这个按需引入会导致在 vite5.0 只要触发按需加载，页面就会重新加载。 vite4.0.0没有问题

### 重现步骤

~~~@@@@@@@@

### 设备/浏览器

_No response_

**Comment by a2734961** [comment]
我现在都不太敢升级vite5.0+。官方大大有什么处理经验和办法吗？

**Comment by wChenonly** [comment]
可以搞一个简单复现仓库，发出来
