### ISSUE TITLE
Coupon 优惠券选择器的选中效果希望可以增加多选的选中效果

### ISSUE THREAD

**Issue by XINGXINGLX** [youzan/vant#12580]
### 这个功能解决了什么问题？

 <van-coupon-list
    :coupons="coupons"
    :chosen-coupon="chosenCoupon"
    :disabled-coupons="disabledCoupons"
    @change="onChange"
    @exchange="onExchange"
  />的 :chosen-coupon="chosenCoupon"可传入数组，根据数组中的值，展示勾选效果。

### 你期望的 API 是什么样子的？

<van-coupon-list
    :coupons="coupons"
    :chosen-coupon="[1,2,3]"
    :disabled-coupons="disabledCoupons"
    @change="onChange"
    @exchange="onExchange"
  />

**Comment by RSS1102** [comment]
有疑问个是否有一个api控制是否多选`multiple`，还是根据`chosen-coupon`的类型进行判断？

**Comment by XINGXINGLX** [comment]
> 有疑问个是否有一个api控制是否多选，还是根据的类型进行判断？`multiple``chosen-coupon`
根据现APi的chosen-coupon参数类型只支持传入number类型，不支持数组；multiple 该属性我有添加过，但并没有效果

**Comment by XINGXINGLX** [comment]
> 啊这。。。我指的是新的api开发，支持多选的状态，是不是应该添加一个`multiple`.

可以添加 multiple 属性，然后 chosen-coupon 支持数组传入

**Comment by Lgowen** [comment]
你好想请教一下如果想认领这个issue的话有什么条件嘛

**Comment by CatsAndMice** [comment]
已提交相关PR
