### ISSUE TITLE
van-tab 底部条在title变化时的宽度问题

### ISSUE THREAD

**Issue by ansonhorse** [youzan/vant#1258]
**Describe the bug**
你好！
van-tab的底部条宽度估计是计算得到的，这对于不变title的情况来说是没问题的，但如果title是动态的，比如字符个数有变化，这时候底部条的宽度并没有跟随改变，所以就会出现如图2的情况。
不知道是否可以在`title`改变后，自动更新底部条的宽度呢？

**Screenshots**
![image](https://user-images.githubusercontent.com/7548142/41200316-f7e319ee-6cd4-11e8-910e-8abf209c7826.png)
![image](https://user-images.githubusercontent.com/7548142/41200319-0760b908-6cd5-11e8-982b-468b66815fe3.png)

**Environment**
 - Device: PC
 - Browser: Chrome
 - Vant Version: 1.1.7

**Reproduce**
https://jsfiddle.net/ansonhorse/pa5v1zsu/1/

**Comment by chenjiahan** [comment]
下个版本会支持 title prop 改变时，自动更新底部条的宽度
但是组件内部无法监听到 slot="title" 改变，所以使用 slot 的情况下是无法自动更新的

**Comment by ansonhorse** [comment]
@chenjiahan 谢谢！
想请问一下，可以手动触发么？

**Comment by chenjiahan** [comment]
```html
```

**Comment by ansonhorse** [comment]
谢谢，这样我的需求就解决了。
`title`是可控的，所以写一个触发也是很简单的事情。
