### ISSUE TITLE
[Bug Report] 我现在尝试在PC端使用Picker组件，但是发现无法使用拖动功能

### ISSUE THREAD

**Issue by BlueBoyC** [youzan/vant#12585]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-8fuq5o?file=%2Fsrc%2FApp.vue%3A2%2C17-6%2C69&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrkbi6a700073j6xirgj9o54%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrkbi6a700023j6xqw5fycxr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrkbi6a700043j6xy0zovdy4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrkbi6a700063j6x6dvz7yi2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrkbi6a700023j6xqw5fycxr%2522%253A%257B%2522id%2522%253A%2522clrkbi6a700023j6xqw5fycxr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkbkcnp005y3j6xqgor1ggx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A69%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrkbkcnp005y3j6xqgor1ggx%2522%257D%252C%2522clrkbi6a700063j6x6dvz7yi2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkbi6a700053j6xyollzfhf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8080%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrkbi6a700063j6x6dvz7yi2%2522%252C%2522activeTabId%2522%253A%2522clrkbi6a700053j6xyollzfhf%2522%257D%252C%2522clrkbi6a700043j6xy0zovdy4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkbi6a700033j6xtcjzms9r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrkbi6a700043j6xy0zovdy4%2522%252C%2522activeTabId%2522%253A%2522clrkbi6a700033j6xtcjzms9r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Vant 版本

4.8.2

### 描述一下你遇到的问题。

在移动端无法拖动Picker组件

### 重现步骤

正常引入，就用不了，但是官方在线Demo案例，可以正常使用，在库里没有找到mousedown事件监听

### 设备/浏览器

PC/Edge

**Comment by inottn** [comment]
可以参考 https://vant-ui.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei
