### ISSUE TITLE
[Bug Report] IONIC-CLI使用unplugin-vue-components引入组件报错

### ISSUE THREAD

**Issue by yincangshiwei** [youzan/vant#12582]
### 重现链接

https://github.com/yincangshiwei/ionic-vant

### Vant 版本

"@vant/auto-import-resolver": "^1.0.2","unplugin-vue-components": "^0.26.0",

### 描述一下你遇到的问题。

![image](https://github.com/youzan/vant/assets/8185843/97050d4c-4f34-4617-89b7-74d196987c86)
![image](https://github.com/youzan/vant/assets/8185843/16e727a0-280c-441a-8507-71b5195cd5c3)

### 重现步骤

ionic serve

**Comment by inottn** [comment]
https://github.com/yincangshiwei/ionic-vant/blob/master/package.json 你有安装 vant 吗？

**Comment by yincangshiwei** [comment]
> https://github.com/yincangshiwei/ionic-vant/blob/master/package.json 你有安装 vant 吗？
按照vant官方文档，无需安装vant。
![image](https://github.com/youzan/vant/assets/8185843/cd1e179b-b4be-4b31-a53c-cbc1b47dd78d)

**Comment by yincangshiwei** [comment]
> https://github.com/yincangshiwei/ionic-vant/blob/master/package.json 你有安装 vant 吗？

我的ionic-cli用的就是vite

**Comment by yincangshiwei** [comment]
> https://github.com/yincangshiwei/ionic-vant/blob/master/package.json 你有安装 vant 吗？

还以为不用安装vant，直接使用unplugin-vue-components就行。
