### ISSUE TITLE
v4.8.3  版本 tab 添加了 stick 属性之后，头部样式会默认多了 top: 0px, 导致样式错乱

### ISSUE THREAD

**Issue by JunmeiChen** [youzan/vant#12593]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-gh8spv?file=%2Fsrc%2FApp.vue%3A13%2C6

### Vant 版本

v4.8.3

### 描述一下你遇到的问题。

最新的  v4.8.3 版本的bugfix，导致了tab头部样式问题

![image](https://github.com/youzan/vant/assets/138839098/f821fc5b-1dfb-40ce-89c3-17e5146beadc)

![image](https://github.com/youzan/vant/assets/138839098/1a8bc1b4-1273-4496-8adf-5ba2ffa5c5af)

![image](https://github.com/youzan/vant/assets/138839098/773c732f-4d64-4967-ba7e-af20cae44b2e)

![image](https://github.com/youzan/vant/assets/138839098/39c9c0b0-233f-4de4-97cb-9a3d40e79441)

### 重现步骤

在tabs的上方放一张异步图片，便会出现问题

```[tasklist]
### Tasks
```

**Comment by chenjiahan** [comment]
@nemo-shen 关注下~

**Comment by nemo-shen** [comment]
> @nemo-shen 关注下~

ok

**Comment by nemo-shen** [comment]
@JunmeiChen #12547 引入的问题，会在下一个版本修复这个问题
