### ISSUE TITLE
[Bug Report] 必填的星号在icon的右侧

### ISSUE THREAD

**Issue by enjoy-myLife** [youzan/vant#12592]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-rvxwx2?file=%2Fsrc%2FApp.vue%3A8%2C16

### Vant 版本

4.8.2

### 描述一下你遇到的问题。

![image](https://github.com/youzan/vant/assets/73453769/811ad605-8f7f-4783-bd5a-a8a3f0c26455)

在form表单里同时使用required必填和left-icon的时候，icon在星号左边

### 重现步骤

<van-field required  left-icon="question-o" label-"test"/>

**Comment by wChenonly** [comment]
不知道vant是不是就这么设计的

**Comment by inottn** [comment]
嗯，就是这样设计的
