### ISSUE TITLE
[Feature Request] 希望官方能提供vant-use的构建版本

### ISSUE THREAD

**Issue by dizheyoulan** [youzan/vant#12596]
### 这个功能解决了什么问题？

我需要使用useCountDown这个函数。
因场景限制，只能用script标签引入vant，
但是script标签引入的vant不含有组合式api，
尝试使用vant.useCountDown时提示TypeError: vant.useCountDown is not a function

### 你期望的 API 是什么样子的？

<script src="https://fastly.jsdelivr.net/npm/vant@4/lib/vant-use.min.js"></script>

**Comment by wChenonly** [comment]
see https://www.jsdelivr.com/package/npm/@vant/use

**Comment by chenjiahan** [comment]
vant 包是有提供 UMD 产物的，可以在 vant 里导出一下 @vant/use 的方法。

@vant/use 这个包暂时不准备改造构建脚本，所以没有提供 UMD 产物。
