### ISSUE TITLE
[Bug Report] ConfigProvider组件在对FloatingBubble 浮动气泡组件进行自定义样式时，不起作用。

### ISSUE THREAD

**Issue by MillionMindFU** [youzan/vant#12598]
### 重现链接

https://codesandbox.io/p/sandbox/vant-4-issue-template-forked-rqg3qx

### Vant 版本

4.8

### 描述一下你遇到的问题。

 ConfigProvider 组件在对FloatingBubble 浮动气泡进行自定义样式的时候，没有生效。

### 重现步骤

链接中的代码里有，里面floatingBubbleSize属性不管改成什么，都无法生效。
该错误也在沙盒中重现了。

### 设备/浏览器

edge浏览器

**Comment by inottn** [comment]
参考这个 https://vant-ui.github.io/vant/#/zh-CN/config-provider#css-bian-liang-sheng-xiao-fan-wei
