### ISSUE TITLE
ImagePreview 图片预览，有bug，滑动就没有图片了！

### ISSUE THREAD

**Issue by wwb568109135** [youzan/vant#126]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
ImagePreview 图片预览，有bug，滑动就没有图片了！
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**
别隐藏图片，正常滑动，可以切换显示图片！
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by pangxie1991** [comment]
这个我fix下

**Comment by pangxie1991** [comment]
#134
