### ISSUE TITLE
Search 搜索 支持电脑端

### ISSUE THREAD

**Issue by live-in-a-dream** [youzan/vant#12602]
### 这个功能解决了什么问题？

电脑端能否兼容一下Search 搜索 的clear事件

### 你期望的 API 是什么样子的？

修改在电脑端 clear无法清空文字的问题

**Comment by inottn** [comment]
参考这个 https://vant-ui.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei，不知道是不是你想要的？

**Comment by live-in-a-dream** [comment]
多谢。OK
