### ISSUE TITLE
[Bug Report] vant 4 preview has  breaked

### ISSUE THREAD

**Issue by andbridge** [youzan/vant#12609]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/col

### Vant 版本

4.8.3

### 描述一下你遇到的问题。

组件预览失效

### 重现步骤

随机选中一个组件

### 设备/浏览器

edge

**Comment by inottn** [comment]
未复现，可以控制台看一下有没有资源加载失败

**Comment by andbridge** [comment]
有资源加载失败的报错。

**Comment by andbridge** [comment]
1.我已经确认本机网络状态良好。
2.我多次刷新网站或关闭浏览器重新进入网站，尝试恢复均未能生效。
3.只有Button组件可以正常预览。

**Comment by andbridge** [comment]
1.存在资源加载失败的情况。
2.我确保本机网络状态良好，并多次刷新或关闭浏览器重新进入网站，以尝试恢复。
3.只有button 组件的预览是正常的。




发自我的iPhone


------------------ Original ------------------
From: inottn ***@***.***&gt;
Date: Fri,Feb 2,2024 10:33 AM
To: youzan/vant ***@***.***&gt;
Cc: andbridge ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [youzan/vant] [Bug Report] vant 4 preview has  breaked (Issue#12609)





 
未复现，可以控制台看一下有没有资源加载失败

**Comment by chenjiahan** [comment]
资源加载失败通常是网络因素导致的，你可以在以下两个域名中选择可访问的域名：

https://vant-contrib.gitee.io/vant/#/zh-CN
https://vant-ui.github.io/vant/
