### ISSUE TITLE
[Bug Report] van-dialog :close-on-click-overlay="true" 和 :closeOnClickOverlay="true" 都不生效

### ISSUE THREAD

**Issue by zzzzzzcc** [youzan/vant#12610]
### 重现链接

<van-dialog :show="true" title="标题" show-cancel-button  :close-on-click-overlay="true">       <h1>起飞了~</h1>     </van-dialog>

### Vant 版本

4.8.0

### 描述一下你遇到的问题。

点击蒙版关闭弹窗，属性设置不生效 close-on-click-overlay
`<van-dialog :show="true" title="标题" show-cancel-button  :close-on-click-overlay="true">
      <h1>起飞了~</h1>
    </van-dialog>`

### 重现步骤

复制粘贴，添加属性相关点击蒙版关闭弹窗属性close-on-click-overlay就能重现

### 设备/浏览器

谷歌浏览器

**Comment by inottn** [comment]
你的 show 已经绑定了 true，所以 dialog 不会关闭，你应该在 update:show 事件中控制 dialog 的显隐。也可以使用 v-model:show 简化这一逻辑，具体可以参考文档示例。
