### ISSUE TITLE
vue3 + vite 第一次导航到某个页面的时候会触发重载

### ISSUE THREAD

**Issue by pocketChao** [youzan/vant#12638]
### 重现链接

无链接 有日志

### Vant 版本

4.7.1

### 描述一下你遇到的问题。

项目第一次启动的时候  进入新页面 会触发重载  vite 会打印日志 是关于vant引发的重载
[vite] ✨ new dependencies optimized: vant/es/skeleton/style/index, vant/es/skeleton-image/style/index, vant/es/skeleton-paragraph/style/index, vant/es/skeleton-avatar/style/index, vant/es/swipe-cell/style/index, vant/es/badge/style/index
10:51:53 AM [vite] ✨ optimized dependencies changed. reloading

### 重现步骤

[vite] ✨ new dependencies optimized: vant/es/skeleton/style/index, vant/es/skeleton-image/style/index, vant/es/skeleton-paragraph/style/index, vant/es/skeleton-avatar/style/index, vant/es/swipe-cell/style/index, vant/es/badge/style/index
10:51:53 AM [vite] ✨ optimized dependencies changed. reloading

**Comment by pocketChao** [comment]
感觉像是自动导入的问题

**Comment by chenjiahan** [comment]
这个不属于组件库本身的问题，麻烦到 Vite 仓库反馈
