### ISSUE TITLE
[Bug Report] Calendar 点击某个日期会自动滑动到第一行

### ISSUE THREAD

**Issue by cccisbug** [youzan/vant#12637]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-gdcczx?workspaceId=acf85d90-a21b-4640-ba64-c57f335b8365&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsv5mq4k00073b6jwgs7jm9k%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsv5mq4k00023b6j1dv341p7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsv5mq4k00043b6jss0k19nj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsv5mq4k00063b6jzw8hrs9r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsv5mq4k00023b6j1dv341p7%2522%253A%257B%2522id%2522%253A%2522clsv5mq4k00023b6j1dv341p7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsv5tr1a00023b6ihk7eck3t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsv5tr1a00023b6ihk7eck3t%2522%257D%252C%2522clsv5mq4k00063b6jzw8hrs9r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsv5mq4k00053b6jhkx27974%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8080%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsv5mq4k00063b6jzw8hrs9r%2522%252C%2522activeTabId%2522%253A%2522clsv5mq4k00053b6jhkx27974%2522%257D%252C%2522clsv5mq4k00043b6jss0k19nj%2522%253A%257B%2522id%2522%253A%2522clsv5mq4k00043b6jss0k19nj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsv5mq4k00033b6j77htyowh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsv5mq4k00033b6j77htyowh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Vant 版本

4.7.2

### 描述一下你遇到的问题。

Calendar设置为平铺展示，poppable为false，页面为Vue上面一个calendar下面一个html table展示数据，点击日期后查询更新table。
当setData后，Calendar会发生滑动，Calendar定位到了选中的日期所在行，能否不滑动。
试了将table 脱离文档流也不管用

### 重现步骤

Calendar设置为平铺展示，poppable为false，页面为Vue上面一个calendar下面一个html table展示数据，点击日期后查询更新table。
当setData后，Calendar会发生滑动，Calendar定位到了选中的日期所在行，能否不滑动。
试了将table 脱离文档流也不管用

### 设备/浏览器

安卓 iOS pcchrome 等

**Comment by xuyimingwork** [comment]
没明白问题在哪

**Comment by xiandanchaorenguagua** [comment]
遇到了同样的问题：

版本：vant@4.9.1
使用的功能：Calendar
插件代码：
```
                <van-calendar
                    :formatter="formatterDateContent"
                    :poppable="false"
                    :show-title="false"
                    :show-confirm="false"
                    :show-mark="false"
                    :min-date="minDate"
                    :max-date="maxDate"
                    :default-date="currentDate"
                    :safe-area-inset-bottom="false"
                    :style="{ height: '400px' }"
                    @month-show="monthShow"
                    @click-subtitle="clickSubtitle"
                    @select="clickDate"
                />
```
问题描述：
平铺日历，设置了固定高度400px，页面上点击选中任一日期，**该日期自动滚动到日历顶部（也就是星期的下面）**。若去掉这行代码：:style="{ height: '400px' }"，就不会有这样的问题

**Comment by inottn** [comment]
未复现，可以试下最新版本还会有这个问题吗
