### ISSUE TITLE
van-search和van-field组件都被使用，先后被加载的时候，van-search的样式被覆盖

### ISSUE THREAD

**Issue by DULANGHAI** [youzan/vant#12643]
### 重现链接

暂无

### Vant 版本

4.6.4

### 描述一下你遇到的问题。

2个页面，第一个页面使用van-search组件，点击第一个页面进入第二个页面，第二个页面使用van-field组件，回退到第一个页面，van-search的样式会被第二个组件的van-cell类名给覆盖，原本van-search的类名层级是van-search__field大于van-cell，但是加载了van-field组件后，页面会多van-cell，van-search类名变为van-cell、van-search__field、van-cell。具体重现步骤里的图

### 重现步骤

![WechatIMG44786](https://github.com/youzan/vant/assets/14758859/5cbcd169-ab89-4d15-ac6d-61e64e911c9a)

### 设备/浏览器

任何浏览器

**Comment by iamleehom** [comment]
确实有这个问题，我们也遇到了，希望官方可以修复

**Comment by chenjiahan** [comment]
关于样式顺序的问题可以参考：

- https://github.com/youzan/vant/issues/11881
- https://github.com/youzan/vant/issues/11049
