### ISSUE TITLE
[Bug Report] postcss-pxtorem didn't work as envisaged 

### ISSUE THREAD

**Issue by Zoeyxyz** [youzan/vant#12640]
### Reproduction Link

https://stackblitz.com/edit/vitejs-vite-rdai5m?file=vite.config.js,package.json,index.html,package-lock.json,src%2Fmain.js&terminal=dev

### Vant Version

4.8.4

### Describe the Bug

```
css: {
    postcss: {
      plugins: [
        postCssPxToRem({
          rootValue({ file }) {
            return file.indexOf("vant") !== -1 ? 37.5 : 75;
          },
          propList: ["*"],
        }),
      ],
    },
},
server: {
```

使用vite构建项目，全局引入，偶现转换错误

### Reproduce Steps

使用vite创建一个空白项目即可复现
node版本
18.19.0

**Comment by chenjiahan** [comment]
这个问题和 Vant 无关，可以反馈给 postCssPxToRem or Vite

**Comment by li-shifeng** [comment]
使用 "postcss-pxtorem": "^5.1.1" 降低 postcss-pxtorem 的版本可以解决，参考：https://github.com/cuth/postcss-pxtorem/issues/87
