### ISSUE TITLE
[Bug Report] Uploader的chooseFile使用模拟点击，导致maxCount为1时无法触发chooseFile

### ISSUE THREAD

**Issue by ducheng1** [youzan/vant#12642]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-fx2fcf?workspaceId=c0a28bf1-02ea-4892-a484-d3515e77a2d4

### Vant 版本

4.0.4

### 描述一下你遇到的问题。

 Uploader的chooseFile使用模拟点击，导致maxCount为1时无法触发chooseFile

### 重现步骤

1. 设置VanUploader的maxCount为1
2. 先上传一张图片，然后调用uploaderRef.value!.chooseFile()
3. 问题复现

**Comment by inottn** [comment]
chooseFile 不适用于重新上传的场景，这个是符合预期的现象。倒是可以提供一个用于重新上传的方法。
