### ISSUE TITLE
[Bug Report] PC端Uploader组件可通过拖拽上传的方式绕过文件类型校验

### ISSUE THREAD

**Issue by chan-we** [youzan/vant#12649]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/uploader 官网示例可复现

### Vant 版本

4.8.1

### 描述一下你遇到的问题。

Uploader默认接受image/*类型的组件，通过点击打开文件选择器，不符合文件类型的文件会被禁用。但直接打开文件夹，将文件拖拽到Uploader组件上，无论文件是否符合accept的文件类型，都能被上传

### 重现步骤

用的是官网的示例
![图片](https://github.com/youzan/vant/assets/50741609/2df6e710-d270-45d6-892f-feb1d19b9dbb)

如果直接点击，不符合文件类型的文件会被禁用选择
![图片](https://github.com/youzan/vant/assets/50741609/724c95a4-0f8c-47d9-a937-e5bd4cc895f3)

但是拖拽上传可绕过限制
1. 打开电脑的文件管理器
![图片](https://github.com/youzan/vant/assets/50741609/b356e3cc-f62e-4908-bf15-1d627156c089)

2. 文件拖拽到组件上
![图片](https://github.com/youzan/vant/assets/50741609/fca4573d-8f66-41a2-bd36-7305c5938c56)

3. 绕过限制上传成功了
![图片](https://github.com/youzan/vant/assets/50741609/3b31ba97-8bef-40f1-91d4-b6ee5a8472ba)

### 设备/浏览器

系统：macOS 14.1.1  浏览器：Firefox 123.0 / Chrome 122.0

**Comment by chenjiahan** [comment]
accept 是浏览器原生属性，并不是 Vant 实现的，所以这个问题 Vant 内部是无法解决的，只能由浏览器去支持

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept
