### ISSUE TITLE
组件van-pull-refresh 与组件van-list组合使用，切换页面时list没有保持滚动位置

### ISSUE THREAD

**Issue by zhoudaobo** [youzan/vant#12648]
页面使用了keep-alive 来保持页面状态，一下是一个列表页，组件van-pull-refresh 与组件van-list组合使用。这样会出现一个问题，当从该页面切换道其他页面并返回时发现list并没有保持上一次的滚动位置。
测试代码：[test.txt](https://github.com/youzan/vant/files/14431457/test.txt)
测试视频：

https://github.com/youzan/vant/assets/46515072/7d40ce52-e8d5-4c1f-8869-0eb0dcbb6a0f

**Comment by chenjiahan** [comment]
参考 https://github.com/youzan/vant/issues/8596
