### ISSUE TITLE
使用AddressEdit的时，输入的 addressInfo 的数据无法获取。

### ISSUE THREAD

**Issue by HangCheung** [youzan/vant#1265]
**Describe the bug**
在使用AddressEdit的时，输入的 addressInfo 的数据无法获取到。

**Screenshots**

![issue](https://user-images.githubusercontent.com/22117280/41261725-a2767ac8-6e0f-11e8-8c30-018460fae849.png)
![default](https://user-images.githubusercontent.com/22117280/41261728-a7c6ba06-6e0f-11e8-8b00-1deaca85a8c6.png)

**Environment**
 - Device: Windows PCW
 - Browser: Google Chrome 66.0.3359.139（正式版本） （64 位）
 - Vant Version: 1.0.1

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
在 save 事件的回调参数中获取
