### ISSUE TITLE
[Bug Report] ImagePreview缩放问题

### ISSUE THREAD

**Issue by alinquan** [youzan/vant#12652]
### 重现链接

*

### Vant 版本

4.8.3

### 描述一下你遇到的问题。

ImagePreview组件使用image插槽后缩放失效问题，由于缩放功能写在imagePreviewItem组件里，使用image插槽后未使用imagePreviewItem导致缩放失效， 展示了图片与视频，使用image插槽后能否支持缩放？

### 重现步骤

*

**Comment by lqins** [comment]
使用了插槽后，原来的插槽那里的缩放是有问题的，再多调用一次调取方法加上 maxZoom就能解决这个问题。亲测有效，和微信头像点击后的图片效果一样

**Comment by chenjiahan** [comment]
现在 slot 可以获取到 style 和 onLoad 参数了，绑定参数后即可支持缩放，参考：https://github.com/youzan/vant/issues/12656
