### ISSUE TITLE
[Bug Report] Feedback on the Issue Where the `close-on-click-outside` Prop Does Not Work in the Popover Component Under Nuxt3.

### ISSUE THREAD

**Issue by WuChenDi** [youzan/vant#12650]
### Reproduction Link

https://stackblitz.com/edit/github-v31wpp?file=app.vue

### Vant Version

"@vant/nuxt": "^1.0.4"

### Describe the Bug

![image](https://github.com/youzan/vant/assets/31385662/65c16bd0-36a4-40b8-8b38-426522bb0ca5)

### Reproduce Steps

please check https://stackblitz.com/edit/github-v31wpp?file=app.vue

**Comment by inottn** [comment]
I couldn't reproduce it, are you using it on a mobile device?

**Comment by WuChenDi** [comment]
No, the issue is specific to the desktop version; it is not present on the mobile platform.

**Comment by WuChenDi** [comment]
okay, thanks,
