### ISSUE TITLE
[Bug Report] Layout 布局显示异常问题

### ISSUE THREAD

**Issue by liub1934** [youzan/vant#12662]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-kkqgln

### Vant 版本

4.8.5

### 描述一下你遇到的问题。

van-row设置gutter属性后，上下的布局显示会有点异常，由于只有一个van-col的时候好像忽略了padding的设置，导致上下显示有点错位不对齐了，而且元素设置的padding好像都不一样。
<img width="637" alt="image" src="https://github.com/youzan/vant/assets/29849550/3907b3d4-3fc8-43d3-9a8c-ba3edf532ebb">
<img width="764" alt="image" src="https://github.com/youzan/vant/assets/29849550/3e26e767-3dd6-492f-becd-b73645ab5d50">
<img width="638" alt="image" src="https://github.com/youzan/vant/assets/29849550/67097474-529e-407e-b803-dc241c1b2f85">
<img width="771" alt="image" src="https://github.com/youzan/vant/assets/29849550/04bae241-3471-4124-aa3b-cf773420e16c">

### 重现步骤

直接打开复现链接看效果

### 设备/浏览器

Macos 13.5.2     Chrome 122.0.6261.112

**Comment by chenjiahan** [comment]
参考 https://github.com/youzan/vant/discussions/11934
