### ISSUE TITLE
Tabs什么时候支持左右模式，需要支持滑动

### ISSUE THREAD

**Issue by jbhvip** [youzan/vant#12668]
### 这个功能解决了什么问题？

Tabs什么时候支持左右模式，需要支持滑动

### 你期望的 API 是什么样子的？

Tabs什么时候支持左右模式，需要支持滑动

**Comment by chenjiahan** [comment]
支持的

![image](https://github.com/youzan/vant/assets/7237365/c13a5916-b16c-4bb3-a1ec-26aa863695fe)

**Comment by jbhvip** [comment]
其实我想要的是这种模式，之前我表达错误了
<img width="404" alt="311481504-fc189161-3805-4e97-8f3f-142eebfc9445" src="https://github.com/youzan/vant/assets/32460302/ee851c04-b2a4-4472-bbba-08102ebb425a">
