### ISSUE TITLE
Tabs什么时候支持左右布局模式，如图，支持上下滑动来切换Tab标签

### ISSUE THREAD

**Issue by jbhvip** [youzan/vant#12669]
其实我想要的是这种模式，之前我表达错误了
<img width="404" alt="311481504-fc189161-3805-4e97-8f3f-142eebfc9445" src="https://github.com/youzan/vant/assets/32460302/ee851c04-b2a4-4472-bbba-08102ebb425a">

_Originally posted by @jbhvip in https://github.com/youzan/vant/issues/12668#issuecomment-1987058093_

**Comment by suncohey** [comment]
其实这种布局 在你自己的项目中 你稍微改下css样式就可以了
