### ISSUE TITLE
[Bug Report] 在 tsx 文件里，使用 PascalCase 形式的 Tabbar 组件无法自动引入对应样式

### ISSUE THREAD

**Issue by RunningCoderLee** [youzan/vant#12672]
### 重现链接

<del>https://stackblitz.com/edit/vitejs-vite-lr7ple?file=vite.config.ts,src%2FApp.vue,src%2Fmain.ts&terminal=dev</del>

https://stackblitz.com/edit/vitejs-vite-lr7ple?file=src%2FDemo.tsx,src%2Fmain.ts,src%2FApp.tsx&terminal=dev

### Vant 版本

4.8.5

### 描述一下你遇到的问题。

使用 PascalCase 形式的 Tabbar 组件，无法自动引入对应的样式，使用 kebab-case 形式的 Tabbar 组件可以自动引入样式

### 重现步骤

打开 kebab-case 形式组件的注释，样式即可自动引入

### 设备/浏览器

 edge

**Comment by inottn** [comment]
自动导入是 unplugin-vue-components 的功能，和 vant 无关。你可以查阅下对应文档，不知道这个配置https://github.com/unplugin/unplugin-vue-components/issues/323#issuecomment-1411746477 对你有没有帮助。

**Comment by RunningCoderLee** [comment]
这个配置没有效果

换了 [vite-plugin-imp](https://github.com/onebay/vite-plugin-imp) 配合自定义 resolver 解决了

```ts
export default defineCongi({
    plugins: [
        vitePluginImp({
        libList: [
          {
            libName: 'vant',
            replaceOldImport: false,
            style: (name) => {
              if (name.includes('toast')) {
                return 'vant/es/toast/style/index'
              }

              if (name.includes('dialog')) {
                return 'vant/es/dialog/style/index'
              }

              if (name.includes('image-preview')) {
                return 'vant/es/image-preview/style/index'
              }

              return `vant/es/${name}/style/index`
            },
          },
        ],
        exclude: ['vant'],
      }),
    ]
)
```
