### ISSUE TITLE
[Bug Report] AddressList 组件 edit 事件 会连带触发 click-item 事件 

### ISSUE THREAD

**Issue by jiangzenong** [youzan/vant#12680]
### 重现链接

暂无链接地址

### Vant 版本

4.8.5

### 描述一下你遇到的问题。

冒泡无法通过.stop禁止
我应该怎么做

### 重现步骤

1.添加edit事件
2.添加click-item事件
3.点击edit，先触发edit，紧接着就触发了click-item

**Comment by chenjiahan** [comment]
下个版本会在 `click-item` 里暴露原生的 event 对象，这样可以通过 event.target 来进行区分

```js
const onClickItem = (item, index, { event }) => {
  console.log('click-item', item, index, event.target);
};
```

**Comment by jiangzenong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chenjiahan** [comment]
在点击 edit 的时候不触发 `click-item` 会更加合理，不过这个属于 breaking change，目前不会进行这个变更。
