### ISSUE TITLE
请求新增表单校验

### ISSUE THREAD

**Issue by jahnli** [youzan/vant#1268]
能不能在点击按钮的时候或者change的时候 增加表单验证  比如： 现在设置了  required   如果不自己写判断方法 并没有什么实际用处

**Comment by BreezeDealer** [comment]
推荐使用[vee-validate](https://baianat.github.io/vee-validate/)，虽然没有中文文档，英文文档看起来还有些吃力，能搜到的中文博客里面的用法已经比较老了。

**Comment by chenjiahan** [comment]
暂无计划在组件内支持表单验证

**Comment by zhengchenghui** [comment]
表单验证天哪噜
