### ISSUE TITLE
Badge 徽章达不到想要的效果

### ISSUE THREAD

**Issue by hello-lun** [youzan/vant#1269]
想用Badge 徽章做美团外卖，或者饿了么外卖的效果。点左边的按钮，右边显示相应的内容。可badge只有简单的几个api选项，根本做不到。怎么办呢
![image](https://user-images.githubusercontent.com/34638158/41273072-8195ac44-6e4a-11e8-93f9-a95a186ccc92.png)

**Comment by LynanBreeze** [comment]
badge+tab可以解决你的问题

**Comment by hello-lun** [comment]
badge+tabs标签页怎么实现这种布局呢

**Comment by LynanBreeze** [comment]
@hello-lun 上面一个tabs下面左边一个badge，内容在下面右边tab-content里面（和你的图一模一样），用css处理tabs和badge的位置关系。
