### ISSUE TITLE
你们页面上（譬如底部区域），能不能github上查看这个框架的issues入口，每次都是点更新日志切换到issues的！

### ISSUE THREAD

**Issue by wwb568109135** [youzan/vant#127]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**
建议可以看看elementUi的issues 入口！

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
感谢反馈，我们会在后续的文档站点更新中添加
