### ISSUE TITLE
[Bug Report] v4.8.6 中组件的 TypeScript 类型被识别为 any

### ISSUE THREAD

**Issue by zhaojjiang** [youzan/vant#12705]
### Reproduction Link

https://github.com/zhaojjiang/vant-issue-v486-bug-type

### Vant Version

4.8.6

### Describe the Bug

例如组件 Button, 在 v4.8.5 中类型识别正常，但是在 v4.8.6 中是 any

### Reproduce Steps

package.json

```text
"dependencies": {
    ...
    "vant-v485": "npm:vant@4.8.5",
    "vant-v486": "npm:vant@4.8.6"
},
```

App.vue

```vue
<script setup lang="ts">
// TODO 鼠标悬浮获取类型，可以看到两个类型不一样，一个正常，一个是 any
import { Button as ButtonFive } from 'vant-v485';
import { Button as ButtonSix } from 'vant-v486';
</script>

<template>
</template>

<style scoped></style>
```

**Comment by chenjiahan** [comment]
This problem is caused by upgrading typescript. 

Fixed in vant@4.8.7
