### ISSUE TITLE
[Bug Report] cell 组件 label 的类型 文档和代码 没有保持一致

### ISSUE THREAD

**Issue by chouchouji** [youzan/vant#12710]
### Reproduction Link

https://vant-ui.github.io/vant/#/en-US/cell

### Vant Version

latest

### Describe the Bug

![image](https://github.com/youzan/vant/assets/70570907/f151293f-b6ec-4285-b5cd-db23e78e156b)
![image](https://github.com/youzan/vant/assets/70570907/4dd7eee6-580f-4926-b1f6-9bedaf2750dd)

### Reproduce Steps

- 打开官方文档
- 查看main分支代码

**Comment by chouchouji** [comment]
如果确定为问题，我可以开pr修复

**Comment by chenjiahan** [comment]
嗯嗯，欢迎 PR～
