### ISSUE TITLE
[Bug Report] vant cli 6.0 组件使用script setup进行开发 build指令打包后没有导出组件

### ISSUE THREAD

**Issue by wangKBweb** [youzan/vant#12729]
### 重现链接

https://github.com/wangKBweb/vant-cli-test

### Vant 版本

@vant/cli 6.0

### 描述一下你遇到的问题。

组件开发使用script setup
build指令打包无法正常导出组件

### 重现步骤

yarn create vant-cli-app
project-name: xxx
vue3
less
yarn下载依赖
yarn build
此时打包发现 es/index.js 中是正常的
![image](https://github.com/youzan/vant/assets/85718018/27ba5efb-76e4-4731-be6d-b8a6c87be6c8)

修改 src/demo-button/index.vue 
删除export default
更改为script setup
![image](https://github.com/youzan/vant/assets/85718018/bb0f2afb-4dd0-4288-8a6b-dcaaa4511b7e)

yarn build
此时es/index.js中已经缺失了demo-button的引入与导出
![image](https://github.com/youzan/vant/assets/85718018/d4404c81-1021-4f79-93c2-be4fc2a0b092)

**Comment by wangKBweb** [comment]
https://github.com/youzan/vant/issues/10741

**Comment by wangKBweb** [comment]
我找到了 https://github.com/youzan/vant/issues/10741 这条issue 但我不确定是不是同样的问题 而且当年的版本应该比较低

**Comment by wChenonly** [comment]
https://github.com/youzan/vant/blob/41fb2cc9ed0041afd3684b98593de9153fefa0fd/packages/vant-cli/src/common/index.ts#L27-L29
是因为这里判断了是不是默认导出
@chenjiahan 我们要不要在这里加上defineOptions定义name名字，因为现在是支持宏的

`<script setup>

defineOptions({ name: 'DemoButton' })
</script>`

**Comment by chenjiahan** [comment]
嗯嗯，可以加一下判断

**Comment by wangKBweb** [comment]
辛苦辛苦

**Comment by wangKBweb** [comment]
@chenjiahan 佳涵哥 这个什么时候发版 如果短期不准备发的话 我先fork过去自己发一个用着哦

**Comment by wangKBweb** [comment]
@chenjiahan 佳涵哥 cli什么时候发版呀

**Comment by chenjiahan** [comment]
短期没计划，你可以先 fork 哈 ❤️

**Comment by wangKBweb** [comment]
好的 辛苦

**Comment by wangKBweb** [comment]
佳涵哥 这个已经被merge的pr为什么在新版cli代码里消失了 是7.x考虑不再支持defineOptions了吗 还是说合并的时候出了什么问题

**Comment by wukongyang** [comment]
es/index.js 这个文件中正常导入了组件，但是会报错 组件文件没有被导出 is not exported
<img width="687" alt="image" src="https://github.com/user-attachments/assets/557b6f13-334d-4317-a3cc-803eccefb6e1">
