### ISSUE TITLE
[Bug Report] uniapp 使用vant4.8.7 搜索栏出现多个关闭图标

### ISSUE THREAD

**Issue by ufffnwfn** [youzan/vant#12725]
### 重现链接

https://8fuq5o-8080.csb.app/

### Vant 版本

4.8.7

### 描述一下你遇到的问题。

uniapp 使用vant4.8.7 搜索栏出现多个关闭图标
![image](https://github.com/youzan/vant/assets/48238732/63c6ab5c-0c09-49e7-ad4e-3478df1ed464)
![5ca433fab8e65d3e0f608abf0884d4c](https://github.com/youzan/vant/assets/48238732/84a01569-74c6-4591-ad0a-9a3edf823e36)

### 重现步骤

uniapp 使用vant4.8.7 搜索栏出现多个关闭图标

**Comment by inottn** [comment]
参考 #11372 #11190，或者提供能够复现的链接。

**Comment by llt3677** [comment]
css可解决

`/* --清除谷歌浏览器下的 search 叉号  */
.van-field__control::-webkit-search-cancel-button {
  display: none;
}
/* --清除IE下的 search 叉号  */
.van-field__control[type="search"]::-ms-clear {
  display: none;
}
`

**Comment by blueju** [comment]
> css可解决
> 
> ```
> /* --清除谷歌浏览器下的 search 叉号  */
> .van-field__control::-webkit-search-cancel-button {
>   display: none;
> }
> /* --清除IE下的 search 叉号  */
> .van-field__control[type="search"]::-ms-clear {
>   display: none;
> }
> ```

实测有用
