### ISSUE TITLE
[Bug Report] tab开启scrollspy后ellipsis失效

### ISSUE THREAD

**Issue by jackjtr** [youzan/vant#12738]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-sticky-tab-with-navbar-68q5xs

### Vant 版本

4.8.7

### 描述一下你遇到的问题。

如题，标题很长时不太美观，官方文档也没有相关说明，用css去侵入式修改效果不理想，希望能提供相关api

### 重现步骤

见重现链接

**Comment by pany-ang** [comment]
`ellipsis` 仅在 `shrink` 为 `false` 且 `tab` 数量小于等于 `swipe-threshold` 时才生效
