### ISSUE TITLE
npm run build:lib编译错误

### ISSUE THREAD

**Issue by HeGangSZ** [youzan/vant#1273]
**Describe the bug**
编译错误：运行命令npm run build:lib编译源码发生2个错误，错误如下
(1)build:style-entry编译错误，错误截图如下，一直无法通过编译
(2)build:vant-css编译错误，错误截图如下，后面发现是安装依赖的问题，将npm安装依赖改为cnpm安装依赖后解决，但是npm的方式安装一直不成功

**Screenshots**
build:style-entry编译错误
![image](https://user-images.githubusercontent.com/15183304/41290188-a5d39a1a-6e7e-11e8-81bc-d55b5b116cbd.png)

build:vant-css编译错误
![image](https://user-images.githubusercontent.com/15183304/41291905-82bc716e-6e83-11e8-9703-e56112b14355.png)

**Environment**
 - Device: macbook pro 2015
 - Browser: chrome
 - Vant Version: 1.1.7

**Comment by chenjiahan** [comment]
node 版本是？ 可能是 node 版本过低导致的

**Comment by HeGangSZ** [comment]
@chenjiahan 将node版本由10.2.1升到最新版本10.4.0问题依然存在，我试下在其他机器上的编译情况

**Comment by HeGangSZ** [comment]
找到原因了，如果项目目录名不是vant就会报错 @chenjiahan 

![image](https://user-images.githubusercontent.com/15183304/41292098-206e15ca-6e84-11e8-9a0c-3950aca5c4cd.png)

**Comment by chenjiahan** [comment]
@HeGangSZ 了解了~ 明天修复一下这个问题

**Comment by chenjiahan** [comment]
已在 dev 分支修复这个问题
