### ISSUE TITLE
picker 和弹出层配合使用，v-model 没有支持label 值，目前只支持value 显示

### ISSUE THREAD

**Issue by yw8820** [youzan/vant#12733]
### 这个功能解决了什么问题？

<van-field
v-model="fieldValue"
is-link
readonly
label="城市"
placeholder="选择城市"
@click="showPicker = true"
/>

<van-picker
:columns="columns"
@cancel="showPicker = false"
https://github.com/confirm="onConfirm"
/>
在很多情况下 fieldValue 应该在页面中显示text 值，传后端是value 值，但目前没有text 值展示的逻辑，以及picker 不支持多选模式

### 你期望的 API 是什么样子的？

外层的field 可以支持text 展示，而不是value

**Comment by yw8820** [comment]
yyy

**Comment by jianfei0220** [comment]
怎样解决的呢？

**Comment by ByteTerminator** [comment]
有人解决吗？
