### ISSUE TITLE
希望Swipe 组件 自定义滑块大小新增间隔配置

### ISSUE THREAD

**Issue by Cyan-963852** [youzan/vant#12742]
### 这个功能解决了什么问题？

Swipe 组件在自定义滑块大小的情况下使用了间距（如margin， gap）会导致最后的元素展示被裁切

### 你期望的 API 是什么样子的？

--van-swipe-item-gap: 10px 或者 --van-swipe-item-margin: 10px

**Comment by chenjiahan** [comment]
可以试试在滑块内部设置 right-padding，而不是在滑块外部设置 margin
