### ISSUE TITLE
van-swipe @change function trigger repeatedly

### ISSUE THREAD

**Issue by Penggggg** [youzan/vant#1276]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

van-swipe @change function trigger repeatedly，this will happen only on swiping on the <van-swipe-item> that has not shown. When swiping on the <van-swipe-item> that has shown, @change function will trigger once as normal.

tips: this will happen on v1.1.7 VanSwipe.swipeTo method

van-swipe 的 @change 函数会在滑动时多次触发，并且这个情况只在滑动到未滑动过的<van-swipe-item>才会出现，即滑动到已经滑动过的<van-swipe-item>， @change 函数会只执行一次，即正常。

补充：该现象在 v1.1.7 VanSwipe组件的swipeTo方法 也会出现

**Screensots**
Add screenshots to help explain your problem.

Here is the pictures，please wait

![pic1](https://images2018.cnblogs.com/blog/896425/201806/896425-20180613120515470-837523021.png)
![pic2](https://images2018.cnblogs.com/blog/896425/201806/896425-20180613115637196-1875973150.png)
![pic3](https://images2018.cnblogs.com/blog/896425/201806/896425-20180613115648271-436390335.png)
![pic4](https://images2018.cnblogs.com/blog/896425/201806/896425-20180613115658589-1051166820.png)
![pic5](https://images2018.cnblogs.com/blog/896425/201806/896425-20180613115709324-1076890796.png)

**Environment**
 - Device: Mac 10.13.3
 - Browser: Chrome 67.0.3396.79（正式版本） （64 位）
 - Vant Version: 1.1.7

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
试了一下没复现这个问题，能否提供一下复现问题的 jsfiddle?
