### ISSUE TITLE
vant文档可以添加一个搜索组件功能

### ISSUE THREAD

**Issue by yg-YuanXi** [youzan/vant#12763]
### 这个功能解决了什么问题？

找一个组件 要找一会，可不可以做一个 搜索组件的功能，像elementui一样，可以搜索
如图：
![K8XZERU`TKDD9X@HUGE(%GI](https://github.com/youzan/vant/assets/51600219/b0370c64-946c-4c10-92c9-e59362ac70e0)

### 你期望的 API 是什么样子的？

111

**Comment by chenjiahan** [comment]
参考 https://github.com/youzan/vant/discussions/11778
