### ISSUE TITLE
van-circle 中如果进度为0 这个地方如何不显示

### ISSUE THREAD

**Issue by yujunhua93** [youzan/vant#12764]
### 这个功能解决了什么问题？

![微信截图_20240402153321](https://github.com/youzan/vant/assets/18146113/aef613fe-2778-4b54-90a2-cfc6ea3ffc2d)

### 你期望的 API 是什么样子的？

给一个解决方法

**Comment by wangKBweb** [comment]
![image](https://github.com/youzan/vant/assets/85718018/1077d42e-f625-4841-bfe4-5fa4cbab7ee4)
![image](https://github.com/youzan/vant/assets/85718018/4563b20d-b508-45ca-9fad-f38ff7ef0d9d)
可以试一下隐藏这个元素

**Comment by yujunhua93** [comment]
可以，这个方法有效

**Comment by yg-YuanXi** [comment]
添加 watch 监听 rate 的值
![040217473038_01](https://github.com/youzan/vant/assets/51600219/6aa3ea74-1004-46de-b9e1-f673913c325a)
