### ISSUE TITLE
Picker 期望增加一个索引绑定至

### ISSUE THREAD

**Issue by Cyan-963852** [youzan/vant#12770]
### 这个功能解决了什么问题？

有时候使用Picker组件时，只想单纯的获取选中的索引

### 你期望的 API 是什么样子的？

```<van-picker v-model:index="selected" />```

**Comment by chenjiahan** [comment]
感觉同时支持两种 v-model 不是一个好的选择，因为 v-model 和 v-model:index 容易冲突。如果需要索引的话可以通过 change 或 confirm 事件来获取
