### ISSUE TITLE
vue3+vant+vite empty 默认图片不显示

### ISSUE THREAD

**Issue by 2741421630** [youzan/vant#12779]
### Reproduction Link

https://vant-contrib.gitee.io/vant/#/zh-CN/empty

### Vant Version

3.4.7

### Describe the Bug

<img width="1213" alt="image" src="https://github.com/youzan/vant/assets/59333473/9c954326-decb-45a0-8ffd-47995c4e29c4">
<img width="1326" alt="image" src="https://github.com/youzan/vant/assets/59333473/b550a34a-dc0d-4684-a24e-fac3361bbf52">

### Reproduce Steps

同样的版本，内网解析为http，公网是svg

### Device / Browser

chrome

**Comment by wangjue666** [comment]
@2741421630  
我看了下 3.4.7的 empty 组件的确是用的图片链接， 你更新依赖到3.6.12 就好了
https://github.com/youzan/vant/blob/0483305eddd424a3a0343566461d35d659947646/packages/vant/src/empty/Empty.tsx#L40

https://github.com/youzan/vant/blob/e6f788172c7a309c022c83a7ddade42993a8d10d/packages/vant/src/empty/Empty.tsx#L207
