### ISSUE TITLE
vue3 项目，我只引入并使用了 vantImage 一个 vant ui 组件，配置了按需引入组件样式，为什么打包后包括了其他 UI 组件模块？

### ISSUE THREAD

**Issue by beileixinqing** [youzan/vant#12776]
### 重现链接

https://codesandbox.io/p/devbox/vant-test-gcjjdl?file=%2Fsrc%2Fmain.ts

### Vant 版本

4.0.0

### 描述一下你遇到的问题。

vue3 项目，我只引入并使用了 vantImage 一个 vant ui 组件，配置了按需引入组件样式，为什么打包后包括了其他 UI 组件模块？

![image](https://github.com/youzan/vant/assets/22930400/7cf4afb2-62e4-4bd9-a1be-5bb242578555)

### 重现步骤

`
main.js
import { createApp } from 'vue';
import { Image as VanImage } from 'vant';

const app = createApp();
app.use(VanImage);

App.vue
<van-image  :src="xxx" />

vue.config.js
// 按需引入vant组件样式
const { VantResolver } = require('unplugin-vue-components/resolvers')
const ComponentsPlugin = require('unplugin-vue-components/webpack')

module.exports = {
  configureWebpack: config => {
      config.devtool = 'source-map'
      config.plugins.push(ComponentsPlugin({
        resolvers: [VantResolver()]
      }))
  }
}
`

**Comment by chouchouji** [comment]
vant 的 `image` 组件 引入了 `icon` 组件，`icon` 组件 引入了 `badge` 组件
