### ISSUE TITLE
[Bug Report] List 组件，加载错误之后，依旧会有loading转圈圈

### ISSUE THREAD

**Issue by JunmeiChen** [youzan/vant#12777]
### Reproduction Link

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-kf3xf2?file=%2Fsrc%2FApp.vue%3A20%2C30&workspaceId=08f8d3bf-2b10-4430-9f4b-5d75381866d8

### Vant Version

4.8.10

### Describe the Bug

 List 组件，加载错误之后，依旧会有loading转圈圈

### Reproduce Steps

 List 组件，加载错误之后，依旧会有loading转圈圈

### Device / Browser

chrome

**Comment by wangjue666** [comment]
@JunmeiChen  文档代码少写一句, 改成这样就好了

```
fetchSomeThing().catch(() => {
        loading.value = false;
        error.value = true;
 });
```
