### ISSUE TITLE
[Bug Report] image preview组件在自定义图片插槽的时候，按照文档缩提供的示例使用没达到预期效果，依旧不能通过缩放图片

### ISSUE THREAD

**Issue by tanglongyan** [youzan/vant#12780]
### Reproduction Link

暂时没有链接

### Vant Version

4.8.4

### Describe the Bug

 image preview组件在自定义图片插槽的时候，按照文档缩提供的示例使用没达到预期效果，依旧不能通过缩放图片
如果不使用图片插槽的形式可正常使用

### Reproduce Steps

这是一个nuxt3搭建的项目，依赖安装使用都正常，vant其他组件都可正常使用
![image](https://github.com/youzan/vant/assets/44485600/9a23c6cf-6a6f-483e-b21b-c999c7cf1be9)
![image](https://github.com/youzan/vant/assets/44485600/1bfc06cd-e9f0-4f5f-bc63-3f644c767dd2)

文档描述：
![image](https://github.com/youzan/vant/assets/44485600/6b59ad75-d946-4409-aa95-f5bec49a38df)

**Comment by inottn** [comment]
更新到最新版本试一下

**Comment by tanglongyan** [comment]
> 更新到最新版本试一下

更新了依赖问题还是没有得到解决，现在是插槽中传出来的值接不到（src的值能正确拿到）
![image](https://github.com/youzan/vant/assets/44485600/acbffa3f-fa8a-4a44-820d-db07bd40183b)
想问下这个style跟onLoad函数是在什么时机暴露出来的呢？

**Comment by inottn** [comment]
> > 更新到最新版本试一下
> 
> 更新了依赖问题还是没有得到解决，现在是插槽中传出来的值接不到（src的值能正确拿到） ![image](https://private-user-images.githubusercontent.com/44485600/321950186-acbffa3f-fa8a-4a44-820d-db07bd40183b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTgwMTAsIm5iZiI6MTcxMjkxNzcxMCwicGF0aCI6Ii80NDQ4NTYwMC8zMjE5NTAxODYtYWNiZmZhM2YtZmE4YS00YTQ0LTgyMGQtZGIwN2JkNDAxODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMjgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OWRkZjYyMGRlMWI3ZTFmYWEyZjIyZGU1ZGVmMjU1N2Q1NjhkYWFmYTYxNWNkOGZmNmY1YjNiOWZiZGJkOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cZDwLSft3bD0PARND1mnlrUqXzcw2Fb_PXYjWczS_0U) 想问下这个style跟onLoad函数是在什么时机暴露出来的呢？

参考文档，代码看上去没有问题。需要提供一个复现链接。

**Comment by tanglongyan** [comment]
> > > 更新到最新版本试一下
> > 
> > 
> > 更新了依赖问题还是没有得到解决，现在是插槽中传出来的值接不到（src的值能正确拿到） ![image](https://private-user-images.githubusercontent.com/44485600/321950186-acbffa3f-fa8a-4a44-820d-db07bd40183b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTgwMTAsIm5iZiI6MTcxMjkxNzcxMCwicGF0aCI6Ii80NDQ4NTYwMC8zMjE5NTAxODYtYWNiZmZhM2YtZmE4YS00YTQ0LTgyMGQtZGIwN2JkNDAxODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMjgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OWRkZjYyMGRlMWI3ZTFmYWEyZjIyZGU1ZGVmMjU1N2Q1NjhkYWFmYTYxNWNkOGZmNmY1YjNiOWZiZGJkOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cZDwLSft3bD0PARND1mnlrUqXzcw2Fb_PXYjWczS_0U) 想问下这个style跟onLoad函数是在什么时机暴露出来的呢？
> 
> 参考文档，代码看上去没有问题。需要提供一个复现链接。

确实是vant版本问题，4.8.3->4.8.11解决
