### ISSUE TITLE
【Field】支持添加标签的功能

### ISSUE THREAD

**Issue by CatsAndMice** [youzan/vant#12781]
### 这个功能解决了什么问题？

解决选择多标签场景，为给级联选择器增加多选功能 https://github.com/youzan/vant/issues/12047 做准备

### 你期望的 API 是什么样子的？
参考：https://arco.design/vue/component/cascader#multiple

**Comment by chenjiahan** [comment]
FIeld 暂时没有计划支持这个功能，可以考虑用 slot 自行实现一下
