### ISSUE TITLE
swiper+lazyload只显示第一张图片？？

### ISSUE THREAD

**Issue by LLily7** [youzan/vant#1278]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by LLily7** [comment]
就按照官网给的示例来做的，但是轮播起来只有第一张图片显示出来了。有小伙伴知道该怎么解决吗？

**Comment by chenjiahan** [comment]
能否提供一个复现问题的 jsffidle
