### ISSUE TITLE
SSR项目中@vant/auto-import-resolver能导入组件，但是还是无法按需导入样式

### ISSUE THREAD

**Issue by Ben-Ben-B** [youzan/vant#12782]
### Reproduction Link

https://gitee.com/Ben4/vant-ssr

### Vant Version

4.8.10

### Describe the Bug

SSR项目中@vant/auto-import-resolver能导入组件，但是还是无法按需导入样式

### Reproduce Steps

npm run start

**Comment by inottn** [comment]
对应的哪个文件的哪个组件样式没有按需导入？

**Comment by Ben-Ben-B** [comment]
https://gitee.com/Ben4/vant-ssr @inottn 这是地址

**Comment by Ben-Ben-B** [comment]
我知道了谢谢 @winglechen

**Comment by hyflzh1314** [comment]
大佬，ssr基于vite怎么配置vant4 按需引入
