### ISSUE TITLE
有没有头像组组件？

### ISSUE THREAD

**Issue by master006** [youzan/vant#12789]
### 这个功能解决了什么问题？

报名、拼团等应用该组件 
![1713061503340](https://github.com/youzan/vant/assets/25217361/12a1923d-c910-487a-8902-b3c85dcdc183)

### 你期望的 API 是什么样子的？

好用简单，很多组件库都有，可参考其它组件库

**Comment by chenjiahan** [comment]
目前没有哈，这个实现起来还是比较容易的，可以自行实现
