### ISSUE TITLE
动态绑定 field 的Error 属性不生效

### ISSUE THREAD

**Issue by FinchJohnRen** [youzan/vant#1279]
**Describe the bug**
             <van-field
                v-for="(item, idx) in invoiceForm" :key="idx"
                v-model="item.value"
                :label="item.name"
                :error="item.showError"
                :placeholder="item.placeholder"
                required
                @click-icon="username = ''"
              />
这是我写在计算属性的代码，动态改变showError input框没有变红
invoiceForm () {
      // 普票
      let plainInvoiceForm = [
        {
          name: '发票抬头',
          placeholder: '请填写发票抬头',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '税号',
          placeholder: '请填写税号',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '邮寄地址',
          placeholder: '请填写邮寄地址',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '收件人',
          placeholder: '请填写收件人',
          showError: false,
          isValid: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '手机号',
          placeholder: '请填写手机号',
          showError: false,
          isValid: false,
          value: '',
          regexp: /^1[0-9]\d{9}$/,
        },
      ]
      // 专票
      let specialInvoiceForm = [
        {
          name: '发票抬头',
          placeholder: '请填写发票抬头',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '税号',
          placeholder: '请填写税号',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '开户行',
          placeholder: '请填写开户行',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '银行卡号',
          placeholder: '请填写银行卡号',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '户名',
          placeholder: '请填写户名',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '公司地址',
          placeholder: '请填写公司地址',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '公司电话',
          placeholder: '请填写公司电话',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '邮寄地址',
          placeholder: '请填写邮寄地址',
          isValid: false,
          showError: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '收件人',
          placeholder: '请填写收件人',
          showError: false,
          isValid: false,
          value: '',
          regexp: new RegExp,
        },
        {
          name: '手机号',
          placeholder: '请填写手机号',
          showError: false,
          isValid: false,
          value: '',
          regexp: /^1[0-9]\d{9}$/,
        },
      ]
      return this.ticket.Invoice_Type == 1 ? plainInvoiceForm : specialInvoiceForm
    },

**Environment**
 - Browser: 谷歌
 - Vant Version: 1.1.4

**Comment by chenjiahan** [comment]
请确保你传入的 error 的值是否正确
