### ISSUE TITLE
tabs桌面端无法滑动，安装了桌面端适配也不行

### ISSUE THREAD

**Issue by smlieto** [youzan/vant#12800]
### 重现链接

https://dp.fanzhuo.net.cn/zhjl/studio/online-booking/view/1764548924063514626/MULTIPLE

### Vant 版本

4.6.4

### 描述一下你遇到的问题。

桌面端tabs滑动不了，touch失效，安装桌面端适配也没效果

### 重现步骤

1.打开链接https://dp.fanzhuo.net.cn/zhjl/studio/online-booking/view/1764548924063514626/MULTIPLE
2.打开控制台关闭手机模式
3.滑动tab滑不动

### 设备/浏览器

谷歌浏览器

**Comment by wChenonly** [comment]
![Jietu20240418-130434-HD](https://github.com/youzan/vant/assets/37658262/58c43515-de50-4e75-bc1c-7cc4739107a7)
试了下，没问题呢

**Comment by smlieto** [comment]
你这是鼠标滑动吧，鼠标移动tabs跟着滑动支持吗
