### ISSUE TITLE
[Bug Report] vant-cli dev没有执行build.configureVite方法

### ISSUE THREAD

**Issue by LomyCool** [youzan/vant#12804]
### 重现链接

https://codesandbox.io/p/github/LomyCool/test-css-bind/main?file=%2Fvant.config.mjs&workspaceId=b692d5d9-9349-485b-b45a-aff272de85c1

### Vant 版本

@vant/cli 7.0.1

### 描述一下你遇到的问题。

<img width="1444" alt="图片" src="https://github.com/youzan/vant/assets/16275856/63f11e54-c659-4521-a52d-48347364ecf6">
vant-cli dev没有执行build.configureVite方法；
同级目录下创建 vite.config.ts，vant-cli dev也不会执行vite.config.ts的配置
-- 但是打包是执行的

### 重现步骤

1. 配置build.configureVite，输出日志
  build: {
    packageManager: 'pnpm',
    configureVite(config) {
      const { BUILD_TARGET } = process.env;
      console.log("🚀 ~ configureVite ~ BUILD_TARGET:", BUILD_TARGET)

      if (BUILD_TARGET === 'package') {
        // 修改组件库构建配置
      }

      if (BUILD_TARGET === 'site') {
        // 修改文档站点构建配置
      }

      return config;
    }}
3. pnpm dev ，日志没输出

**Comment by chenjiahan** [comment]
这个是符合预期的，v7 的 dev 不再基于 Vite。

参考更新日志：

![image](https://github.com/youzan/vant/assets/7237365/eecdefaf-c8f2-4d0a-b1e4-8d3bc6fef116)

https://github.com/youzan/vant/blob/main/packages/vant-cli/changelog.md

**Comment by LomyCool** [comment]
> 这个是符合预期的，v7 的 dev 不再基于 Vite。
> 
> 参考更新日志：
> 
> ![image](https://private-user-images.githubusercontent.com/7237365/323574429-eecdefaf-c8f2-4d0a-b1e4-8d3bc6fef116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDMwMzcsIm5iZiI6MTcxMzQ0MjczNywicGF0aCI6Ii83MjM3MzY1LzMyMzU3NDQyOS1lZWNkZWZhZi1jOGYyLTRkMGEtYjFlNC04ZDNiYzZmZWYxMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMTIxODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjEyN2U1MTM3NmZkYzRjZGNkMzk0Mjk3YjFmYmMyODdmYmJlZWU2NzQ4YWNlNzUxZGRmMTlhOTM1NDIxN2UwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-DS7UVgSJ_WCODj0jKrFUVeadu9vcvnr4FJZE1IaLSc)
> 
> https://github.com/youzan/vant/blob/main/packages/vant-cli/changelog.md

好的，那有开放RSbuild的钩子吗，我想添加公共样式
<img width="561" alt="图片" src="https://github.com/youzan/vant/assets/16275856/2546688b-7ca6-491a-938c-1339a8206545">

**Comment by chenjiahan** [comment]
暂时还没有，我近期加一个

**Comment by chenjiahan** [comment]
已在 7.0.2 版本支持，直接创建 `rsbuiid.config.mjs` 或 `rsbuiid.config.ts` 文件即可
