### ISSUE TITLE
[Bug Report] van-watermark 组件水印全页显示

### ISSUE THREAD

**Issue by boringmj** [youzan/vant#12825]
### 重现链接

https://github.com/boringmj/zy_chaxun

### Vant 版本

4.8.11

### 描述一下你遇到的问题。

控件`<van-watermark :full-page=false content="这是水印" />` 设置 `full-page`为`ture`或为`false`均全页面显示水印
![QQ截图20240424151123](https://github.com/youzan/vant/assets/44385165/00c96fa0-f1af-4959-9212-1f8119e67a62)

### 重现步骤

使用`van-watermark`组件,设置`full-page`属性

### 设备/浏览器

windows 10/chrome 122.0.6261.95

**Comment by inottn** [comment]
这个 `:full-page=false` 改成 `:full-page="false"`

**Comment by boringmj** [comment]
> 这个`:full-page=false`改成`:full-page="false"`

实测并没有实质变化,还是不行

**Comment by boringmj** [comment]
> 你代码写的有问题吧，:full-page=false的关注呢？

实测并没有实质变化，还是不行

**Comment by boringmj** [comment]
经过测试,需要给父容器加上定位器才可以正常在容器内显示而不全页显示

```css
#list {
  position: relative;
}
```
