### ISSUE TITLE
关于 uniapp

### ISSUE THREAD

**Issue by 17612884976** [youzan/vant#12828]
### 这个功能解决了什么问题？

什么时候可以可以兼容 uniapp vue3 呀

### 你期望的 API 是什么样子的？

能够兼容 uniapp vue3 就好了

**Comment by inottn** [comment]
参考 https://vant-ui.github.io/vant/#/zh-CN/faq#shi-fou-zhi-chi-zai-uni-app-zhong-shi-yong ，暂时没有计划支持
