### ISSUE TITLE
[Bug Report]SwipeCell 滑动单元格点击事件错误捕获

### ISSUE THREAD

**Issue by shiya-she** [youzan/vant#12834]
### 重现链接

https://codesandbox.io/p/github/shiya-she/mobile/main?import=true&workspaceId=8506f6e1-3ff1-4e9b-b721-0089fa9b3c84

### Vant 版本

4.8.11

### 描述一下你遇到的问题。

swipecell捕获了其他组件点击

### 重现步骤

多个swipcell滑动某一个swipcell时其他swipeCell点击会被触发
只有一个swipCell时点击外部也会触发click

**Comment by inottn** [comment]
对应链接无法查看
