### ISSUE TITLE
国内站点地址挂了

### ISSUE THREAD

**Issue by dufu1991** [youzan/vant#12832]
### 重现链接

https://vant-contrib.gitee.io/vant/

### Vant 版本

all

### 描述一下你遇到的问题。

国内地址挂了，是不是 Gitee 不给用了？

### 重现步骤

打不开 https://vant-contrib.gitee.io/vant/

### 设备/浏览器

all

**Comment by Hexcpp** [comment]
臣附议

**Comment by BinScript1004** [comment]
你都进了github，开代理可以进呀

**Comment by chenjiahan** [comment]
是 Gitee 的问题，正在处理，可以先访问 GitHub 上部署的站点 https://vant-ui.github.io/vant/#/zh-CN

**Comment by chenjiahan** [comment]
参考 https://gitee.com/oschina/git-osc/issues?utf8=%E2%9C%93&state=all&issue_search=pages

![image](https://github.com/youzan/vant/assets/7237365/580f067c-6347-424a-9bfa-5ab60683804f)

**Comment by dufu1991** [comment]
静态部署到你们自己的服务器上好点吧，背后有赞公司支持，应该不差这点钱吧。我的个人开源 [STDF](https://stdf.design) 都是自掏腰包。

**Comment by chenjiahan** [comment]
Vant 目前是社区驱动的

**Comment by dufu1991** [comment]
好像又打不开了。哭

**Comment by chenjiahan** [comment]
参考 https://github.com/youzan/vant/issues/12846
