### ISSUE TITLE
AddressEdit组件addressInfo数据格式的key值自定义

### ISSUE THREAD

**Issue by JohnVSD** [youzan/vant#1284]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
由于后端返回的JSON数据key值与addressInfo的格式不一样，导致前端还要逐个进行赋值。
**Describe the solution you'd like**
提供可以自定义addressInfo数据格式的方法

**Comment by chenjiahan** [comment]
暂无计划支持喔，在组件外写个转换函数就行
