### ISSUE TITLE
Gitee 文档站下线通知 & 解决方法

### ISSUE THREAD

**Issue by chenjiahan** [youzan/vant#12846]
## Gitee 文档站下线

大家好，过去 Vant 的文档站采取了 **GitHub Pages + Gitee Pages 双部署**的方式，以方便国内开发者访问文档。

然而，近期 Gitee 在没有通知的情况下，下线了所有 Gitee Pages 的服务，因此我们已经无法访问 https://vant-contrib.gitee.io/vant/ 这个域名。

> 关于 Gitee Pages 下线的背景，可以参考 https://gitee.com/oschina/git-osc/issues/I9L5FJ?from=project-issue

## 解决方法

请访问 Vant 部署在 GitHub Pages 上的网站：

- Vant：https://vant-ui.github.io/vant/
- Vant Weapp：https://vant-ui.github.io/vant-weapp/

## 2024.05.13 更新

我们正在部署新的国内镜像站点，敬请期待

## 2024.05.31 更新

欢迎试用我们新部署的国内站点：

- Vant 4: https://vant.pro/vant/#/zh-CN
- Vant 2: https://vant.pro/vant/v2/#/zh-CN/
- Vant Weapp: https://vant.pro/vant-weapp/#/zh-CN

感谢 @delai 提供域名和部署支持 ❤️

**Comment by wumuu** [comment]
无语，我说怎么找不到，国内有没有可以替代的服务，GitHub真的太慢

**Comment by chenzhengduan** [comment]
太坑了

**Comment by xiangshiyun** [comment]
怎么把文档部署到本地，我拉gh-pages分支，打不开里面的html，打开是空白的。我是直接打开html文件，需要做其他的什么操作吗？

**Comment by miaosen** [comment]
> 怎么把文档部署到本地，我拉gh-pages分支，打不开里面的html，打开是空白的。我是直接打开html文件，需要做其他的什么操作吗？

得用http服务部署，idea直接预览html就好了，或者使用ngnix部署，最新文档在 https://github.com/vant-ui/vant-ui.github.io/tree/gh-pages

**Comment by flyweb291** [comment]
怎么在本地部署2.x版本的文档站点

**Comment by xiangshiyun** [comment]
> > 怎么把文档部署到本地，我拉gh-pages分支，打不开里面的html，打开是空白的。我是直接打开html文件，需要做其他的什么操作吗？
> 
> 得用http服务部署，idea直接预览html就好了，或者使用ngnix部署，最新文档在 https://github.com/vant-ui/vant-ui.github.io/tree/gh-pages

我没有idea，所以用nginx部署，但是也不行诶，您那边有教程吗？ 我就把gh-pages的内容放到了html文件夹下面了。

**Comment by chenjiahan** [comment]
欢迎试用我们新部署的国内站点：

- Vant 4: https://vant.pro/vant/#/zh-CN
- Vant 2: https://vant.pro/vant/v2/#/zh-CN/
- Vant Weapp: https://vant.pro/vant-weapp/#/zh-CN

**Comment by delai** [comment]
有个稳定的文档站点是最基本的，大家放心用： [https://vant.pro](https://vant.pro)  ，我会保证他长期稳定

**Comment by miaosen** [comment]
> > > 怎么把文档部署到本地，我拉gh-pages分支，打不开里面的html，打开是空白的。我是直接打开html文件，需要做其他的什么操作吗？
> > 
> > 
> > 得用http服务部署，idea直接预览html就好了，或者使用ngnix部署，最新文档在 https://github.com/vant-ui/vant-ui.github.io/tree/gh-pages
> 
> 我没有idea，所以用nginx部署，但是也不行诶，您那边有教程吗？ 我就把gh-pages的内容放到了html文件夹下面了。

把vant-ui下的vant文件夹放到nginx的html文件夹，启动然后访问http://localhost/vant/index.html#/zh-CN/cell即可

**Comment by suncohey** [comment]
> 有个稳定的文档站点是最基本的，大家放心用： https://vant.pro ，我会保证他长期稳定

更新 有些滞后啊

**Comment by alongcai** [comment]
> > 有个稳定的文档站点是最基本的，大家放心用： https://vant.pro ，我会保证他长期稳定
> 
> 更新 有些滞后啊

为什么 网站经常打开呀

**Comment by hanjialin** [comment]
> 有个稳定的文档站点是最基本的，大家放心用： https://vant.pro ，我会保证他长期稳定

单纯的v4环境为什么没有办法访问到这个网站呢？

**Comment by javascripet** [comment]
gitee真的太草台了 今天莫名其妙宕机也没说明的

**Comment by delai** [comment]
> > > 有个稳定的文档站点是最基本的，大家放心用： https://vant.pro ，我会保证他长期稳定
> > 
> > 
> > 更新 有些滞后啊
> 
> 为什么 网站经常打不开呀

可能是你国内网络访问 Cloudflare 间歇性抽风，我给他搞成国内国外双 CDN 吧
