### ISSUE TITLE
[Bug Report]  useCountDown倒计时总时长被本地时间影响

### ISSUE THREAD

**Issue by SZGG2333** [youzan/vant#12842]
### 重现链接

www.baidu.com

### Vant 版本

vant 3.6.0 @vant/use 1.5.1

### 描述一下你遇到的问题。

倒计时开始后，修改本地时间，倒计时的时间会根据本地时间变化

### 重现步骤

1、正常开始倒计时
2、修改本地时间
3、倒计时总时长变化

### 设备/浏览器

all

**Comment by inottn** [comment]
在前端进行倒计时计算，依赖本地时间是预期行为
