### ISSUE TITLE
van-field在自适应高度时，同时添加max-height属性，在超出限高再输入中文时，内容总是滚动到顶部。

### ISSUE THREAD

**Issue by hls-33** [youzan/vant#12859]
### 重现链接
https://codesandbox.io/p/devbox/hls-33-z7l9gy?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw4seowg00073b6ix0z38zv8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw4seowg00023b6i61l9ivas%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw4seowg00043b6inxepjeam%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw4seowg00063b6i4ebwhp9b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw4seowg00023b6i61l9ivas%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw4seowg00013b6i3o5rt33p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clw4seowg00023b6i61l9ivas%2522%252C%2522activeTabId%2522%253A%2522clw4seowg00013b6i3o5rt33p%2522%257D%252C%2522clw4seowg00063b6i4ebwhp9b%2522%253A%257B%2522id%2522%253A%2522clw4seowg00063b6i4ebwhp9b%2522%252C%2522activeTabId%2522%253A%2522clw4st4hg012v3b6ifhyt5un5%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A8080%252C%2522id%2522%253A%2522clw4st4hg012v3b6ifhyt5un5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clw4seowg00043b6inxepjeam%2522%253A%257B%2522id%2522%253A%2522clw4seowg00043b6inxepjeam%2522%252C%2522activeTabId%2522%253A%2522clw4ss6iv010t3b6ijzxgd5dw%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw4ss6iv010t3b6ijzxgd5dw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clw4ss6r6001idhhueuot6m1n%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
#

### Vant 版本

4.1.0

### 描述一下你遇到的问题。

van-field在自适应高度时，同时添加max-height属性，在web端macos系统上，在超出限高再输入中文时，内容总是滚动到顶部。
`<van-field
					class="massage-input max-h-293"
					ref="inputField"
					v-model="inputMassage"
					rows="1"
					autosize
					type="textarea"
					placeholder="请输入消息"
				>
			</van-field>`

### 重现步骤

1.给van-field设置rows="1"，autosize和max-height；
2.在输入超出限高 内容滚动时 输入中文；
3.会出现内容回滚到顶部效果；

### 设备/浏览器

web端/macos/Chrome

**Comment by inottn** [comment]
autosize 可传入对象，如 { maxHeight: 100 }，用这个就没问题了。
