### ISSUE TITLE
[Bug Report] Area组件中columns-placeholder属性在选择省份和城市数据后出现展示问题

### ISSUE THREAD

**Issue by Script-Xia** [youzan/vant#12856]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-p8wc2v?file=%2Fsrc%2FApp.vue%3A33%2C16&workspaceId=5185fe42-fd94-47cb-bb86-4d084afd2bc3

### Vant 版本

4.8.11

### 描述一下你遇到的问题。

首先，我不确认这是否是一个bug，但是确实不符合使用逻辑。
我将`Area`组件中的`columns-placeholder`属性设置成`['省份', '城市', '区县']`，在选取了省份数据后，第二列也就是城市列的`placeholder`变成了**省份**，选取城市数据后，第三列区县列的`placeholder`变成了**城市**。这不符合使用逻辑。
![image](https://github.com/youzan/vant/assets/61466689/494d938f-6b11-45ad-84b7-e2f33d484d9a)
![image](https://github.com/youzan/vant/assets/61466689/ed6d4fe6-1d68-4bb9-b963-0a46c4515302)

### 重现步骤

1. 点击表单元素浮现弹窗
2. 选择省份
3. 选择城市
4. 查看`placeholder`

### 设备/浏览器

Google Chrome 124.0.6367.119（正式版本)

**Comment by inottn** [comment]
提供的重现链接没有权限访问

**Comment by Script-Xia** [comment]
https://codesandbox.io/p/devbox/vant-4-issue-template-forked-p8wc2v?file=%2Fsrc%2FApp.vue%3A33%2C16&workspaceId=5185fe42-fd94-47cb-bb86-4d084afd2bc3&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw1eb8o20007356kptspu17b%2522%252C%2522sizes%2522%253A%255B77.83749184953214%252C22.162508150467858%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw1eb8o10002356k0jl8b1wy%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw1eb8o10004356k4odpmrk3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw1eb8o20006356kgad1dcn4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw1eb8o10002356k0jl8b1wy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw1eb8o10001356kf7tsbekd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clw1ee9mx0050356kqt1tb1v6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A33%252C%2522startColumn%2522%253A16%252C%2522endLineNumber%2522%253A33%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clw1eb8o10002356k0jl8b1wy%2522%252C%2522activeTabId%2522%253A%2522clw1ee9mx0050356kqt1tb1v6%2522%257D%252C%2522clw1eb8o20006356kgad1dcn4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw1eb8o10005356klhaimf7u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8080%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw1eb8o20006356kgad1dcn4%2522%252C%2522activeTabId%2522%253A%2522clw1eb8o10005356klhaimf7u%2522%257D%252C%2522clw1eb8o10004356k4odpmrk3%2522%253A%257B%2522id%2522%253A%2522clw1eb8o10004356k4odpmrk3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw1eb8o10003356kqxy5ujhx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clw1eb8o10003356kqxy5ujhx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
