### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by chanzea** [youzan/vant#1286]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

地址编辑里面的省市区三级联动能否抽离出来

**Comment by chenjiahan** [comment]
有滴 https://youzan.github.io/vant/#/zh-CN/area

**Comment by chanzea** [comment]
我的意思是没有点击从底下弹出一个弹窗，然后里面有三级联动的那种

**Comment by chanzea** [comment]
文档说是配合弹出层一起使用，就是现在点击确认那里获取不到数据，有一个是popup的确认，有一个是三级联动的确认，有点混乱。

**Comment by chenjiahan** [comment]
@chanzea popup 并没有确认按钮喔
