### ISSUE TITLE
[Bug Report] Tab内嵌套滚动Tab，滚动Tab点击下标响应不正确

### ISSUE THREAD

**Issue by DaYang816** [youzan/vant#12870]
### 重现链接

https://stackblitz.com/edit/vitejs-vite-btfcfw?file=src%2Fcomponents%2FHelloWorld.vue

### Vant 版本

"vant": "^4.9.0",

### 描述一下你遇到的问题。

在Tab做了3个内容，在A的Tab内容中嵌套滚动Tab，不会出现问题，但是在后续B，或者C内容中嵌套会出现嵌套的滚动Tab下标不准确。
1.不管A内容中嵌套Tab是否存在都会出现。
2.只有在不是A内容中嵌套的才会出现下标不准
3.出现问题的滚动Tab下标会出现2个问题
3.1 从aa点击到bb，下标会直接飞到dd
3.2 不论点击哪个tab都要点击2遍下标才会正确

### 重现步骤

在Tab做了3个内容，在A的Tab内容中嵌套滚动Tab，不会出现问题，但是在后续B，或者C内容中嵌套会出现嵌套的滚动Tab下标不准确。
在A的tab中点击无问题
在B的tab中点击出现问题，再回到A，A也出问题
把A中嵌套删除，单独在B中嵌套，问题复现

### 设备/浏览器

手机浏览器，PC浏览器都会出现

**Comment by inottn** [comment]
```vue
<van-tab v-for="item in 2">
  <div v-if="active == 0">
    <!-- tabs -->
  </div>
</van-tab>
```
等同于
```vue
<van-tab>
  <div v-if="active == 0">
    <!-- tabs -->
  </div>
</van-tab>
<van-tab>
  <div v-if="active == 0">
    <!-- tabs -->
  </div>
</van-tab>
```
你在同一时间加载了多个 tabs 组件，但关联的状态是同一个，所以会有这个问题。

**Comment by DaYang816** [comment]
那这没办法做动态的tab栏了么，目前好像没有什么参数能区分里面的内容

**Comment by inottn** [comment]
> 那这没办法做动态的tab栏了么，目前好像没有什么参数能区分里面的内容

可以根据 index 或者 item 多做一层判断

**Comment by DaYang816** [comment]
好的谢谢解答
