### ISSUE TITLE
查看文档，总是自动跳转之前页面

### ISSUE THREAD

**Issue by f5l5y5** [youzan/vant#12888]
### Reproduction Link

https://vant-ui.github.io/vant/#/zh-CN/

### Vant Version

4.9.0

### Describe the Bug

例如：查看文档时，初始页面在button上，点击其他组件文档，自动给我跳回button文档，必现

### Reproduce Steps

例如：查看文档时，初始页面在button上，点击其他组件文档，自动给我跳回button文档，必现

### Device / Browser

谷歌125

**Comment by wChenonly** [comment]
没复现，能录个视频么

**Comment by inottn** [comment]
未复现，可以关闭所有浏览器插件再试试
