### ISSUE TITLE
dialog 无蒙层  完全相同的代码结果一个有蒙层一个没有

### ISSUE THREAD

**Issue by shidiyanmo** [youzan/vant#1288]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.
dialog 无蒙层  完全相同的代码结果一个有蒙层一个没有
**Environment**
 - Device: win10 vscode1.24.1
 - Browser: chrome
 - Vant Version: 1.12

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/
https://github.com/shidiyanmo/33.git

**Comment by Fyerl** [comment]
能否补全下jsfiddle
