### ISSUE TITLE
[Bug Report] @vant/auto-import-resolver加上VantImports后，函数式组件样式不会引入

### ISSUE THREAD

**Issue by XiaopingHu** [youzan/vant#12889]
### 重现链接

https://github.com/XiaopingHu/vant-issue.git

### Vant 版本

4.9.0

### 描述一下你遇到的问题。

使用vant官方自动引入组件的教程，在vite.config.ts中加入VantImports选项后，函数式组件的样式不能正常引入，注释后可正常引入

### 重现步骤

1、不注释VantImports选项
AutoImport({
    // 注释此选项，可正常导入函数式组件的样式
    imports:[VantImports()],
    resolvers:[VantResolver()]
  })
2、运行 npm run dev，此时hello world页面的showToast功能正常，但样式没有引入
3、注释VantImports后，showToast功能正常，样式也正常

### 设备/浏览器

Chrome

**Comment by zhaojjiang** [comment]
大概知道原因了，应该是 imports 选项自动导入和 resolver 的判断冲突了，大佬 @chenjiahan  帮忙确认下，看是不是要回滚 #12861

**Comment by zhaojjiang** [comment]
> 大概知道原因了，应该是 imports 选项自动导入和 resolver 的判断冲突了，大佬 @chenjiahan 帮忙确认下，看是不是要回滚 #12861

或者我们在现在的基础上，对 VantResolver 添加一个强制自动导入样式的参数，以做兼容和修复，这样是不是也可？

**Comment by chenjiahan** [comment]
好的，已经移除了 VantImports 相关的文档，后续问题修复后可以再加回来

**Comment by jiangyong1998** [comment]
一样的问题，我在首页引入标签组件，后面使用函数方法就有样式了
