### ISSUE TITLE
[Feature Request] 希望支持vue3和vue2导出

### ISSUE THREAD

**Issue by seven0404** [youzan/vant#12882]
### 这个功能解决了什么问题？

4年前使用了 "@vant/cli": "^2.0.0" 编写了一个vue2组件库。
现在又使用"@vant/cli": "^7.0.0" 编写了一个vue3的组件库。但是因为公司主项目还是vue2的，新项目都是vue3的了，新旧项目都需要使用这个组件库。这个现状或许是很多公司都面临的问题吧，要么写两套要么使用vue-demi类似的库导出两套。希望vant-cli能够支持类似vue-demi类似的功能来解决vue2和vue3并存的尴尬局面。

### 你期望的 API 是什么样子的？

	"dependencies": {
		"vue-demi": "latest"
	},

**Comment by chenjiahan** [comment]
没有这个计划哈，Vant CLI 最新版是面向 Vue 3 的，有相关需求可以直接 fork Vant CLI。
