### ISSUE TITLE
[Feature Request] 新增右边字母索引导航栏 Indexer 组件

### ISSUE THREAD

**Issue by syncml** [youzan/vant#1289]
能否出一个类似mui里面的索引列表 indexed list组件吗？还是想用官方的。

或者类似这样的 ：https://github.com/rt-zhangxuefei/vue2-index-list

**Comment by chenjiahan** [comment]
后续会考虑加入类型的组件

**Comment by chenjiahan** [comment]
会在 2.0 版本加入

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.0 版本支持
