### ISSUE TITLE
[Bug Report] TitleVite打包之后，生产环境Uploader提交时报错，dev没有该报错

### ISSUE THREAD

**Issue by baozhuming** [youzan/vant#12898]
### Reproduction Link

http://113.59.48.141:9081/report/DZXC130601

### Vant Version

4.9.0

### Describe the Bug

使用 Vite + Vant + Vue3 开发打包之后，生产环境 Uploader上传选择完文件后报错
TypeError: Assignment to constant variable.
    at X.length.Qe.onUpdate:modelValue.i.<computed>.i.<computed> (:9081/assets/index-f14a0f86.js:1:53423)
    at mr (:9081/assets/index-e90e4a93.js:13:38)
    at Ct (:9081/assets/index-e90e4a93.js:13:109)
    at U1 (:9081/assets/index-e90e4a93.js:13:2212)
    at g (:9081/assets/index-f14a0f86.js:1:38218)
    at :9081/assets/index-f14a0f86.js:1:38707

### Reproduce Steps

<img width="1240" alt="image" src="https://github.com/youzan/vant/assets/20451418/8b893bd6-88da-4374-8f75-253281358d70">

<img width="1236" alt="image" src="https://github.com/youzan/vant/assets/20451418/b4fbe750-bea3-482c-9e5e-f899885334ba">

**Comment by baozhuming** [comment]
···
<van-uploader
                  style="padding: 10px 16px;"
                  preview-size="5rem"
                  :max-count="10"
                  multiple
                  accept=".bmp,.bmp,.gif,.jpg,.jpeg,.png"
                  v-model="imageFileList"
                  :max-size="30 * 1024 * 1024"
                  @oversize="imageOnOversize"
                  :after-read="imageAfterRead"
                  :upload-text="`${imageFileList.length}/10`"
                  :before-delete="imageBeforeDelete">
              </van-uploader>


// 佐证图片列表
const imageFileList = reactive<Array<FileItem>>([]);

// 上传图片超过大小提示
const imageOnOversize = (file:UploaderFileListItem) => showFailToast('佐证图片文件大小不能超过 30M');

// 上传文件读取后调用后端
const imageAfterRead = (file:UploaderFileListItem) => uploadFile(file, imageFileList);

// 删除文件
const imageBeforeDelete = (file:any, indexInfo: any) => commonBeforeDelete(file, indexInfo, imageFileList);
···

**Comment by baozhuming** [comment]
mac Apple M1 14.4.1 ，google 浏览器125.0.6422.112（正式版本） (arm64)

**Comment by inottn** [comment]
可以使用 ref 替换 reactive 的相关逻辑
