### ISSUE TITLE
[Bug Report] popup组件在同一个页面存在多个会同时唤起

### ISSUE THREAD

**Issue by setube** [youzan/vant#12895]
### 重现链接

https://jsrun.net/A45Kp

### Vant 版本

2.12

### 描述一下你遇到的问题。

我在同一个页面里使用了两个popup组件,分别是父组件里的popup和子组件里的popup,然后当我点击唤起了子组件的popup之后再去点击父组件的popup就会同时唤起子组件和父组件的popup

### 重现步骤

点击按钮就能快速复现

**Comment by inottn** [comment]
提供的代码中子组件关闭的时候，状态没有同步至父组件。可以修改下对应的逻辑看看。
