### ISSUE TITLE
area组件数据格式能否加个配置选项？通用的地址json数据格式都是嵌套的

### ISSUE THREAD

**Issue by yangcong1012** [youzan/vant#1290]
您好，area组件中数据格式为省市区三个列表，但是一般的地址json数据格式都是嵌套的，不知道以后是否会有类似于elementui中的config api

**Comment by Fyerl** [comment]
目前可以做一层 filter 对业务数据做下处理兼容 vant 的数据格式，感谢建议

**Comment by yangcong1012** [comment]
谢谢回复，已解决
