### ISSUE TITLE
[Feature Request] 表单没有重置事件

### ISSUE THREAD

**Issue by DaYang816** [youzan/vant#12901]
### 这个功能解决了什么问题？

我表单提交后需自己手动重置，from = {..initFrom};
应该是调用from表单自己的reset事件就直接清空会好点。

### 你期望的 API 是什么样子的？

可以通过ref或缺from对象进行重置，
类似这样formRef.value.resetFields();

**Comment by chouchouji** [comment]
![image](https://github.com/youzan/vant/assets/70570907/eb0d0f8b-c4a3-4ed2-84d1-1fbeb66b7b2e)

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/issues/6058

**Comment by DaYang816** [comment]
> ![image](https://private-user-images.githubusercontent.com/70570907/335541300-eb0d0f8b-c4a3-4ed2-84d1-1fbeb66b7b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjg5ODQsIm5iZiI6MTcxODA2ODY4NCwicGF0aCI6Ii83MDU3MDkwNy8zMzU1NDEzMDAtZWIwZDBmOGItYzRhMy00ZWQyLTg0ZDEtMWZiZWI2NmI3YjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAxMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YmU1ZjZkYTg3ZTIxYWM1MWNlOTJjMzlhYzAzNTlkY2RiMTZkNjEwNDIwNzRjYzcxZmIyOGIyYTc3NDdlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GU5w8lSEaBKIr-3d9Ypk-XJE7MPMcNSnMzKaaSm-_rk)

这个是验证信息的清除，不是完全重置表单
