### ISSUE TITLE
[Feature Request] Uploader手动填充数据时仅有base64也可以预览

### ISSUE THREAD

**Issue by jackjtr** [youzan/vant#12913]
### 这个功能解决了什么问题？

在给Uploader组件的v-model手动填充仅包含content字段的对象时，缩略图可以显示但是点击无法预览，需要额外将base64数据转换成file和blobUrl并加入数据才可以正常预览
主要用于只读不可编辑但可预览

### 你期望的 API 是什么样子的？

```
<van-uploader v-model="fileList" />
```
```
const fileList = ref([
  { content: `data:image/png;base64/...` },
]);
```

**Comment by day-xue** [comment]
你把base64 赋值给url 并且 isImage 为true就行

**Comment by inottn** [comment]
参考 https://vant-ui.github.io/vant/#/zh-CN/uploader#wen-jian-yu-lan

**Comment by jackjtr** [comment]
> 参考 https://vant-ui.github.io/vant/#/zh-CN/uploader#wen-jian-yu-lan

要不更新一下文档吧，列一下url支持哪些类型，反正我看文档是看不出支持base64
