### ISSUE TITLE
[Bug Report] 在popup二次封装的组件上使用scoped的class，不生效

### ISSUE THREAD

**Issue by vito24** [youzan/vant#12927]
### 重现链接

https://stackblitz.com/edit/vitejs-vite-2hryqf?file=src%2FApp.vue

### Vant 版本

4.9.1

### 描述一下你遇到的问题。

对popup进行二次封装，然后在这个二次封装的my-popup组件上使用scoped的class，不生效

### 重现步骤

1. 点击按钮
2. 查看popup的class，虽然class属性中有red，但是red不生效
![image](https://github.com/youzan/vant/assets/13133596/a510623d-5303-4ed1-ab77-ddc094d47b42)
![image](https://github.com/youzan/vant/assets/13133596/09f236fa-cd18-45b8-b734-795b7374659b)

**Comment by inottn** [comment]
看了下，这和 vue scoped 功能相关，不属于 vant 的 bug。可查阅 https://cn.vuejs.org/api/sfc-css-features.html#scoped-css
