### ISSUE TITLE
swiper 组件，一个页面中，多次使用，出现不显示问题，应该怎么解决？

### ISSUE THREAD

**Issue by liukaiqun** [youzan/vant#1292]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by Fyerl** [comment]
请补充下 jsfiddle
文档 swipe demo 就是一个页面使用多个 swipe, 可以参考下使用姿势

**Comment by liukaiqun** [comment]
一个页面多次使用，图片出不来啊

在 2018-06-19 15:31:50，"neverland" <notifications@github.com> 写道：


Closed #1292.
