### ISSUE TITLE
[Bug Report] 关闭Loading Toast的同时会把其他消息Toast组件的实例给关闭。

### ISSUE THREAD

**Issue by ayuana6691** [youzan/vant#12929]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-rz4sc9?workspaceId=31f5e01d-3aee-461f-bf83-84f05e81a781&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxa25noc00073b6i8x6bzng6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxa25noc00023b6ib9atlule%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxa25noc00043b6i2e7c820h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxa25noc00063b6ichf5cio2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxa25noc00023b6ib9atlule%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxa25nob00013b6ivmkeyt78%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxa25noc00023b6ib9atlule%2522%252C%2522activeTabId%2522%253A%2522clxa25nob00013b6ivmkeyt78%2522%257D%252C%2522clxa25noc00063b6ichf5cio2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxa25noc00053b6ih41x22u1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8080%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxa25noc00063b6ichf5cio2%2522%252C%2522activeTabId%2522%253A%2522clxa25noc00053b6ih41x22u1%2522%257D%252C%2522clxa25noc00043b6i2e7c820h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxa25noc00033b6i9pjeungt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clxa25noc00043b6i2e7c820h%2522%252C%2522activeTabId%2522%253A%2522clxa25noc00033b6i9pjeungt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Vant 版本

4.9.0

### 描述一下你遇到的问题。

关闭Loading Toast的同时会把其他消息Toast组件的实例给关闭。

### 重现步骤

先使用一个变量loading保存showLoadingToast返回的实例，然后再把自动关闭Toast的时间设置为0，然后同时显示其他的Toast，比如showFailToast，然后调用loading.close();会发现showFailToast方法显示的Toast实例也会被关闭。
**复现的前提是loading.close() 需要再调用showFailToast之前。**

**Comment by inottn** [comment]
参考 https://vant-ui.github.io/vant/#/zh-CN/toast#dan-li-mo-shi
