### ISSUE TITLE
开发指南 -  快速上手

### ISSUE THREAD

**Issue by zcy7688** [youzan/vant#12931]
### 这个功能解决了什么问题？

在【按需引入样式】中并没有说明 showDialog 等 API 在使用时需要引入样式 import 'vant/es/toast/style' 才可以正常使用，或者是我的自动引入样式有问题，但是我的其他任何组件都可以正常使用，唯独 showDialog showToast 等 API 直接调出的组件无法正常显示

### 你期望的 API 是什么样子的？

在开发指南的快速上手中明确指出哪些 API 需要按需引入哪个样式

**Comment by CherishTheYouth** [comment]
![image](https://github.com/user-attachments/assets/ea2e033f-01b1-4d70-988c-7f4b9f002267)
这里有说哦，哈哈

**Comment by chenjiahan** [comment]
参考 https://github.com/youzan/vant/issues/13109
