### ISSUE TITLE
[Bug Report] uploader组件，展示预览上传图片时，不能设置横向滚动条

### ISSUE THREAD

**Issue by dyjx2004** [youzan/vant#12932]
### 重现链接

无

### Vant 版本

4.9.1

### 描述一下你遇到的问题。

展示预览上传图片时，不能设置横向滚动条，如果把.van-uploader__wrapper的flex-wrap设置nowrap;  并且设置固定宽度和滚动条，那么上传的图片会被压缩
![QQ截图20240614134149](https://github.com/youzan/vant/assets/50478064/cfcadd30-222f-4c08-ae90-e1f373e27dbb)

### 重现步骤

/deep/ .van-uploader__wrapper{
    width: 7rem;
    overflow-x: scroll;
    flex-wrap: nowrap;
}

**Comment by dyjx2004** [comment]
[vite.zip](https://github.com/user-attachments/files/15856278/vite.zip)
已上传附件，请查看

**Comment by dyjx2004** [comment]
重现链接  https://github.com/dyjx2004/uploader.git

**Comment by chenjiahan** [comment]
这个问题和 Vant 没问题，是你添加自定义样式引入的问题。

在你的 case 里，如果需要横向滚动，那么不应该使用 flex 布局

**Comment by dyjx2004** [comment]
> 这个问题和 Vant 没问题，是你添加自定义样式引入的问题。
> 
> 在你的 case 里，如果需要横向滚动，那么不应该使用 flex 布局

那请问 横向滚动应该怎样设置  因为原来van-uploader__wrapper上就是flex布局     后续官方会考虑加上横向滚动展示上去吗

**Comment by chenjiahan** [comment]
你可以覆盖 flex 布局。没有计划哈
