### ISSUE TITLE
[Bug Report] van-popover组件运行在Android Studio模拟器中无法正常使用

### ISSUE THREAD

**Issue by czh1998yr** [youzan/vant#12941]
### 重现链接

https://github.com/czh1998yr/van-popover-bug-android-studio

### Vant 版本

4.9.1

### 描述一下你遇到的问题。

在Android Studio模拟器中使用van-popover时，报错如下：
1、 Current renderer does not support string target for Teleports. (missing querySelector renderer option)
2、Invalid Teleport target on mount:null(object)
页面能正常显示，但是点击按钮时有很多报错：
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core .
 at <VanPopupref=Ref<{"show":true,"overlay":false,"teleport":"body","lockScroll":false,"lazyRender":true,"transitionAppear":false,"closeOnClickOverlay":true,"round":false,"position":"","closeIcon":"cross","closeable":false,"transition":"van-popover-zoom","closeOnPopstate":false,"closeIconPosition":"top-right","safeAreaInsetTop":false,"safeAreaInsetBottom":false,"popupRef":{"__v_isShallow":false,"dep":{},"__v_isRef":true}}>show=trueclass="van-popover van-popover--light" ...>

### 重现步骤

1、使用HBuilderX运行项目至Android Studio模拟器基座，观察控制台报错
2、点击按钮，观察控制台报错

### 设备/浏览器

Android Studio模拟器基座

**Comment by chenjiahan** [comment]
Vant 是针对 mobile web 场景的，不适配 HBuilderX
