### ISSUE TITLE
[Bug Report] <van-image-preview>组件会报警告，并且使传递的参数、插槽等功能失效

### ISSUE THREAD

**Issue by KanzakiHaru** [youzan/vant#12959]
### 重现链接

https://gitee.com/kanzakiharu/test-img-preview.git

### Vant 版本

"vant": "^3.6.2",

### 描述一下你遇到的问题。

当vant使用 unplugin-vue-components 插件引入时，<van-image-preview>通过组件方式引入时，组件会报警告“Extraneous non-props attributes (show, images) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.”，并且使传递的参数、插槽等功能失效
![无标题](https://github.com/youzan/vant/assets/54618359/86d8101d-f4f1-4059-8586-493585038c34)

### 重现步骤

官方例子就可复显

### 设备/浏览器

chrome移动端模拟器

**Comment by chenjiahan** [comment]
Vant 3 不维护了，建议升级到 Vant 4

**Comment by wangxiaoze-view** [comment]
> 当vant使用 unplugin-vue-components 插件引入时，通过组件方式引入时，组件会报警告“Extraneous non-props attributes (show, images) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.”，并且使传递的参数、插槽等功能失效

今天我同时遇到了类似的问题，二次封装的参数失效了，爆了一堆警告问题，并且页面打开就是黑色背景；
如果升级4的版本，代价有点大；

不过我暂时是这样解决的

``` js
import { ImagePreview } from 'vant';
app.component('v-image-preview', ImagePreview.Component);
```

项目是按需加载的， 就把该组将自定义为全局的，名字不要和vant的一样；

我不清楚这样到底可行不；
