### ISSUE TITLE
TextEllipsis 文本省略 组件自定义操作内容会掉到第二行

### ISSUE THREAD

**Issue by sushi-su** [youzan/vant#12958]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/text-ellipsis

### Vant 版本

4.9.1

### 描述一下你遇到的问题。

TextEllipsis 文本省略 组件自定义操作内容会掉到第二行

### 重现步骤

打开官网demo可复现

**Comment by ddzy** [comment]
+1 ，`4.9.1`版本，自定义action里面的内容会掉到第二行
![image](https://github.com/youzan/vant/assets/33921398/31a01e58-8f2b-4b6d-b9bd-e2b7a15ad188)

```html
<TextEllipsis :content="v.receive_condition">
	<template #action="{ expanded }">
		展开
	</template>
</TextEllipsis>
```
