### ISSUE TITLE
[Bug Report] van-uploader 组件 after-read 绑定函数时，参数无法追踪类型

### ISSUE THREAD

**Issue by linhaihero** [youzan/vant#12960]
### Reproduction Link

-

### Vant Version

4.9.1

### Describe the Bug

![image](https://github.com/youzan/vant/assets/8591451/3416d723-e837-4964-8dcb-557a3f9b80b5)

我使用 UploaderFileListItem （import type { UploaderFileListItem } from 'vant';）没能通过类型检查，请问我要如何写才能正确的表示到这个回调参数的类型？

### Reproduce Steps

-

**Comment by chenjiahan** [comment]
完整类型是这个：

![image](https://github.com/youzan/vant/assets/7237365/5835bf8c-3f93-4f0f-91bd-10985d45e54f)
