### ISSUE TITLE
[Bug Report] van-col是否支持自适应布局，如lg md sm

### ISSUE THREAD

**Issue by xkkjiayou** [youzan/vant#12979]
### Reproduction Link

https://ai.zscampus.com/robottoy

### Vant Version

4.2.0

### Describe the Bug

![image](https://github.com/youzan/vant/assets/38376865/9a9061a8-7982-4f24-b20d-bd3018abb361)

### Reproduce Steps

试了一下没有用，也找不到任何资料

**Comment by chenjiahan** [comment]
文档里没有写就是不支持的
