### ISSUE TITLE
Uploader 的 UploaderFileListItem 对象应该添加 id 字段

### ISSUE THREAD

**Issue by ion1ze** [youzan/vant#12974]
### Discussed in https://github.com/youzan/vant/discussions/12973

<div type='discussions-op-text'>

<sup>Originally posted by **ion1ze** June 29, 2024</sup>
自定义上传时候，后端返回文件编号，可以通过监听 FileList 编号来改变 id，现在需要手动在上传逻辑里再维护一遍 id</div>

**Comment by inottn** [comment]
没太理解你的业务场景需要 id 来做什么
