### ISSUE TITLE
tab 标签 ，路由模式下

### ISSUE THREAD

**Issue by cg123456** [youzan/vant#12981]
### Reproduction Link

xxx

### Vant Version

4.9.0

### Describe the Bug

tab 标签 ，路由模式下，点击已经选择的tab标签，需要暴露一个参数 ：执行自定义方法,点击更多的时候，需要执行特定的逻辑
![example](https://github.com/youzan/vant/assets/49542520/9f121176-bfa7-47d5-9b2a-7f37416bd8f4)

### Reproduce Steps

<img width="801" alt="image" src="https://github.com/youzan/vant/assets/49542520/285f7fa2-6ea3-427e-966d-befe09578f3f">

### Device / Browser

all

**Comment by inottn** [comment]
你可以给 tabbar-item 绑定点击事件，从 dataset 中拿到需要的参数
