### ISSUE TITLE
vant2 Dialog 可以不要自动在 Vue 的 prototype 上挂载 $dialog 方法吗，项目里本身已经注册了自己的$dialog

### ISSUE THREAD

**Issue by CzyYYDS** [youzan/vant#12987]
### Reproduction Link

vant2 Dialog 可以不要自动在 Vue 的 prototype 上挂载 $dialog 方法吗，项目里本身已经注册了自己的$dialog

### Vant Version

2.13.2

### Describe the Bug

vant2 Dialog 可以不要自动在 Vue 的 prototype 上挂载 $dialog 方法吗，项目里本身已经注册了自己的$dialog

### Reproduce Steps

vant2 Dialog 可以不要自动在 Vue 的 prototype 上挂载 $dialog 方法吗，项目里本身已经注册了自己的$dialog

**Comment by chenjiahan** [comment]
Vant 2 已停止维护
