### ISSUE TITLE
自定义 ICON 和自带 ICON 加载错误

### ISSUE THREAD

**Issue by abj3ct10n** [youzan/vant#1298]
自定义新增了一个ICON，和 vant 自带的 ICON 共用，但是发现我引入 `@import 'vant/lib/vant-css/icon-local.css';` 页面加载 font 的时候首先自定义的 ICON 引入是从本地引入没有问题的。

但是 vant 自带的 ttf 是从 CDN 远端：`https://img.yzcdn.cn/vant/vant-icon-9b71af.ttf` 加载

难道不是应该都是从本地加载吗，如果不自定义图标的话，确实是从本地加载，如果自定义了ICON那UI自带的会去请求远端的。。。

**Environment**
 - Device: Window
 - Browser: Chrome
 - Vant Version: 1.1.8

**Comment by chenjiahan** [comment]
不是很清楚这个问题，可以提供一个复现的仓库吗
