### ISSUE TITLE
[Bug Report] 表单验证方法的问题。直接使用 ref获取表单实例，然后使用 ref.valud.validate 方法时报错。

### ISSUE THREAD

**Issue by zhenghaiyang** [youzan/vant#12989]
### 重现链接

我没有这个链接不好意思。

### Vant 版本

4.9.1

### 描述一下你遇到的问题。

vant4 版本是 4.9.1 
这是官网给出的文档。 validate ：验证表单，支持传入一个或多个 name 来验证单个或部分表单项，不传入 name 时，会验证所有表单项。 不传name时应该会校验所有表单项。
但是我看了源码，发现。    
`const validate = (name2) => {
      if (typeof name2 === "string") {
        return validateField(name2);
      }
      return props.validateFirst ? validateSeq(name2) : validateAll(name2);
    };
`
走后面的 validateAll方法，还是需要一个入参。 
然后会导致 getFieldsByNames方法报错
`
    const getFieldsByNames = (names) => {
      if (names) {
        return children.filter((field) => names.includes(field.name));
      }
      return children;
    };
`
。TypeError: names.includes is not a function 

### 重现步骤

1.使用form表单
2.使用ref获取表单实例，然后调用方。formRef.value.validate() 方法

**Comment by wangfpp** [comment]
遇到了同样的问题  没发现问题原因

**Comment by lvzhenbo** [comment]
> 遇到了同样的问题 没发现问题原因

我想，我找到问题原因了，关键字`useExpose`
