### ISSUE TITLE
[Bug Report] css file always exist van-icon

### ISSUE THREAD

**Issue by Blithe07** [youzan/vant#12995]
### 重现链接

https://github.com/vant-ui/vant-demo/vant/vite

### Vant 版本

4.1.9

### 描述一下你遇到的问题。

只要进行了按需导入的配置，打包出来的CSS文件体积就已经达到60KB，且很多无用的css样式。
![20240711-155054](https://github.com/youzan/vant/assets/65998645/b63a34ff-3308-436b-b32b-59e35c0ce67a)

### 重现步骤

官方demo验证

**Comment by chenjiahan** [comment]
这个不是 bug，Vant 图标库是使用 iconfont 实现的，默认需要引入一定体积的 CSS 样式。

**Comment by Blithe07** [comment]
> 这个不是 bug，Vant 图标库是使用 iconfont 实现的，默认需要引入一定体积的 CSS 样式。

但是项目中没有使用到vant图标(template中就只是一个div)，是否可以在生成CSS代码的时候进行剔除？

**Comment by chenjiahan** [comment]
不支持哈，因为 Button 等组件也依赖了 Icon
