### ISSUE TITLE
Tab 标签页在视窗宽度变化后，没有自适应地  重新计算  底部条的位置

### ISSUE THREAD

**Issue by hello-lun** [youzan/vant#1299]
我在做移动端开发的时候，用到Tab 标签页。奇怪的是当我设置了的底部条宽度为20后，改变设备的视口宽度会导致底部条的位置没有重新计算。出现了下图奇怪的现象。
（1）正常的如下：
![image](https://user-images.githubusercontent.com/34638158/41569398-aba9c846-739d-11e8-8e9b-b2bed0e7ed14.png)
（2）当视口宽度变化后如下：
![image](https://user-images.githubusercontent.com/34638158/41569463-de609c88-739d-11e8-8db2-766c99feff1c.png)

**Comment by chenjiahan** [comment]
目前组件内没有监听 resize 事件，下个版本优化一下

**Comment by hello-lun** [comment]
@chenjiahan  那现在有什么权宜之计呢。现在的项目要解决喔

**Comment by chenjiahan** [comment]
已在 1.1.9 版本支持
