### ISSUE TITLE
[Bug Report] Title van-calendar 日历控件切换问题

### ISSUE THREAD

**Issue by Romio-L** [youzan/vant#12994]
### Reproduction Link

https://vant-ui.github.io/vant/#/zh-CN/calendar

### Vant Version

4.9.1

### Describe the Bug

平铺模式下，switch-mode=“month” 的情况下，当设置了min-date 时，切换月份的时候，无法切回当前月份。

### Reproduce Steps

设置min-date为7月5日， 把月份切换到8月份，控件则无法切回7月份

**Comment by Romio-L** [comment]
https://github.com/Romio-L/vant-calendar-demo

这是一个Vant Calendar 月份切换 BUG 的演示代码工程

**Comment by inottn** [comment]
> https://github.com/Romio-L/vant-calendar-demo
> 
> 这是一个Vant Calendar 月份切换 BUG 的演示代码工程

嗯，感谢反馈，后续会修复这个问题

**Comment by Aaron216215** [comment]
设置max-date后，当选择day 大于max-date设置的day时，也会出现无法切换回max-date的月份

**重现链接**
https://codesandbox.io/p/devbox/vant-4-issue-template-forked-ct5z3c?file=%2Fsrc%2FApp.vue%3A23%2C21&workspaceId=6205d4c6-c28c-490e-b9e1-d04f0ad54b58

**描述**
![20240716171227_rec_](https://github.com/user-attachments/assets/492fac1b-0c4b-4427-9e12-6199b7a83a40)

**步骤**
1.选择某月大于20号的日期
2.重新打开日历，发现无法再切换到7月

**Comment by inottn** [comment]
> 设置max-date后，当选择day 大于max-date设置的day时，也会出现无法切换回max-date的月份
> 
> **重现链接** https://codesandbox.io/p/devbox/vant-4-issue-template-forked-ct5z3c?file=%2Fsrc%2FApp.vue%3A23%2C21&workspaceId=6205d4c6-c28c-490e-b9e1-d04f0ad54b58
> 
> **描述** max-date设置的（2024,6,20） ![20240716171227_rec_](https://private-user-images.githubusercontent.com/87625509/349020438-492fac1b-0c4b-4427-9e12-6199b7a83a40.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg1MzYsIm5iZiI6MTcyMTEyODIzNiwicGF0aCI6Ii84NzYyNTUwOS8zNDkwMjA0MzgtNDkyZmFjMWItMGM0Yi00NDI3LTllMTItNjE5OWI3YTgzYTQwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExMTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTEwMzM3MjUwZGUxNzZmMWJkMjc2NzU0NDFiMmYyYmQ2MjU5YzIzODMyNGI2OWUyNGQ1ODQ2YjI2MTI4ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SH6E677RMJgpWMiLsr78mvGYqblLcYIwY06iBRZHOg4) [ ![20240716171227_rec_](https://private-user-images.githubusercontent.com/87625509/349020438-492fac1b-0c4b-4427-9e12-6199b7a83a40.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg1MzYsIm5iZiI6MTcyMTEyODIzNiwicGF0aCI6Ii84NzYyNTUwOS8zNDkwMjA0MzgtNDkyZmFjMWItMGM0Yi00NDI3LTllMTItNjE5OWI3YTgzYTQwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExMTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTEwMzM3MjUwZGUxNzZmMWJkMjc2NzU0NDFiMmYyYmQ2MjU5YzIzODMyNGI2OWUyNGQ1ODQ2YjI2MTI4ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SH6E677RMJgpWMiLsr78mvGYqblLcYIwY06iBRZHOg4) ](https://private-user-images.githubusercontent.com/87625509/349020438-492fac1b-0c4b-4427-9e12-6199b7a83a40.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg1MzYsIm5iZiI6MTcyMTEyODIzNiwicGF0aCI6Ii84NzYyNTUwOS8zNDkwMjA0MzgtNDkyZmFjMWItMGM0Yi00NDI3LTllMTItNjE5OWI3YTgzYTQwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExMTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTEwMzM3MjUwZGUxNzZmMWJkMjc2NzU0NDFiMmYyYmQ2MjU5YzIzODMyNGI2OWUyNGQ1ODQ2YjI2MTI4ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SH6E677RMJgpWMiLsr78mvGYqblLcYIwY06iBRZHOg4) [ ](https://private-user-images.githubusercontent.com/87625509/349020438-492fac1b-0c4b-4427-9e12-6199b7a83a40.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg1MzYsIm5iZiI6MTcyMTEyODIzNiwicGF0aCI6Ii84NzYyNTUwOS8zNDkwMjA0MzgtNDkyZmFjMWItMGM0Yi00NDI3LTllMTItNjE5OWI3YTgzYTQwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExMTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTEwMzM3MjUwZGUxNzZmMWJkMjc2NzU0NDFiMmYyYmQ2MjU5YzIzODMyNGI2OWUyNGQ1ODQ2YjI2MTI4ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SH6E677RMJgpWMiLsr78mvGYqblLcYIwY06iBRZHOg4)
> 
> **步骤** 1.选择某月大于20号的日期 2.重新打开日历，发现无法再切换到7月

嗯，同一个原因导致的

**Comment by Kunkka0229** [comment]
请问修复了吗
