### ISSUE TITLE
mac 下 安装vant  全局引用，同时也引入饿了么的mint-ui，控制台报错了vant没有定义。。。。

### ISSUE THREAD

**Issue by wwb568109135** [youzan/vant#130]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**
mac 下 安装vant  全局引用，报错了vant没有定义
**What is the current behavior?**
（1）vue-cli 安装自己的项目
（2）全局引入vant的写法，入口文件main.js 里写
import Vue from 'vue';
import vant from 'vant';
import 'vant/lib/vant-css/index.css';

Vue.use(vant);

pageage.json
{
  "name": "hxsapp-fe",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "wuwanbin <568109135@qq.com>",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "node build/build.js"
  },
  "dependencies": {
    "mint-ui": "^2.2.9",
    "vant": "^0.9.3",
    "vue": "2.4.2",
    "vue-router": "^2.7.0",
    "vuex": "^2.4.0"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-loader": "^7.1.1",
    "babel-plugin-component": "^0.10.0",
    "babel-plugin-import": "^1.4.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^2.0.1",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "cssnano": "^3.10.0",
    "es2015": "0.0.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.11.1",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "opn": "^5.1.0",
    "optimize-css-assets-webpack-plugin": "^2.0.0",
    "ora": "^1.2.0",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "url-loader": "^0.5.8",
    "vant-css": "^0.9.3",
    "vue-loader": "^13.0.4",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "2.4.2",
    "webpack": "^2.6.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.18.0",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

报错如下：
main.js?1c90:21 Uncaught ReferenceError: vant is not defined

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@wwb568109135  无法复现你的问题，能否提供一个能够复现该问题的代码仓库？

**Comment by w91** [comment]
@wwb568109135 是不是babelrc里用了babel-plugin-import插件，如果是全局注册vant组件，就不要加这个插件。

@chenjiahan 后面文档也备注下吧

**Comment by chenjiahan** [comment]
@w91 好的，后续会在文档中标注。
