### ISSUE TITLE
头部底部无法固定、底部被内容遮挡

### ISSUE THREAD

**Issue by zhengmenglin** [youzan/vant#1300]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
用该组件库的NavBar作为头部、Tabbar作为底部，页面内容滚动时头部无法固定，页面内容多于页面高度时，底部被遮挡。

**Screenshots**
页面未滚动时：
![image](https://user-images.githubusercontent.com/38604167/41585591-2077659a-73dd-11e8-9ff2-e651dac059b2.png)
页面滚动时：
![image](https://user-images.githubusercontent.com/38604167/41585812-b1070250-73dd-11e8-8c11-44fa1476cfa2.png)
内容多于页面高度时：
![image](https://user-images.githubusercontent.com/38604167/41585724-78183e00-73dd-11e8-9e7a-74a9ac2ea84b.png)
底部被遮挡：
![image](https://user-images.githubusercontent.com/38604167/41585791-9f8d2310-73dd-11e8-9816-f7b40be63734.png)

**Environment**
 - Device:  iPhone
 - Browser: Chrome
 - Vant Version: 1.1.8

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
NavBar 是否固定是由 fixed 属性控制的
Tabbar 目前是默认不带 z-index 的，下个版本会加个属性支持配置

**Comment by hello-lun** [comment]
我现在是将导航栏fixed定位，然后还要把导航条的width：100%；top：0；left：0；然后下面的内容raletive定位，再给内容top：xx；就可以了

**Comment by chenjiahan** [comment]
已在 1.1.9 版本支持
