### ISSUE TITLE
[Bug Report] [Calendar 日历] 选中31号时，月份切换bug

### ISSUE THREAD

**Issue by Aaron216215** [youzan/vant#13007]
### 重现链接
https://codesandbox.io/p/devbox/vant-4-issue-template-forked-cc3ngj?file=%2Fsrc%2FApp.vue&workspaceId=6205d4c6-c28c-490e-b9e1-d04f0ad54b58

### Vant 版本

4.9.2

### 描述一下你遇到的问题。

![20240716165603_rec_](https://github.com/user-attachments/assets/ea5df375-a00e-4166-8ffa-222c011804b0)

### 重现步骤

1.选中某个月31号
2.再次打开日历，点击切换下个月（会出现直接跳到下下个月的问题）

### 设备/浏览器

chrome

**Comment by inottn** [comment]
感谢反馈，后续会修复这个问题
