### ISSUE TITLE
Field type="textarea"时，在数字或字母中间输入emoji表情包，换行错位。

### ISSUE THREAD

**Issue by ban-xian** [youzan/vant#13013]
### 重现链接

https://vant.pro/vant/#/zh-CN/field

### Vant 版本

4.7.3

### 描述一下你遇到的问题。

Field type="textarea"时，在数字或字母中间输入emoji表情包，换行后emoji表情包后的数字或字母不跟随在表情包后面，会单独占一行。
![field](https://github.com/user-attachments/assets/ed798393-9fa3-4c83-b97a-93ace67a7509)

### 重现步骤

官方文档demo可复现
1、输入多行数字或字母
2、在其中一行输入emoji表情包，一直输到换行可复现

**Comment by inottn** [comment]
原生 textarea 的默认行为就是这样的，你可以设置 word-break 样式改变这一行为，可以参考 https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
