### ISSUE TITLE
[Feature Request] 更新原生标签初始化样式

### ISSUE THREAD

**Issue by io-o** [youzan/vant#13014]
### What problem does this feature solve?

当同一个仓库，存在 element-plus vant两个组件库时，vant的初始化样式会导致 element-plus样式异常。

```
input, button, textarea {
  color: inherit;
}
```

### What does the proposed API look like?

```
input, button, textarea {
  color: inherit;
}
```

这个样式，可否不用原生标签，加上vant的类名？

为啥同一个仓库为啥存在两个组件库， 没办法，客户只给了一套流水线（😭）

**Comment by inottn** [comment]
具体会影响哪些组件

**Comment by io-o** [comment]
> 具体会影响哪些组件

目前已知，会影响element-plus的button组件

**Comment by inottn** [comment]
> > 具体会影响哪些组件
> 
> 目前已知，会影响element-plus的button组件

可以提供复现链接，或者复习代码吗

**Comment by io-o** [comment]
> > > 具体会影响哪些组件
> > 
> > 
> > 目前已知，会影响element-plus的button组件
> 
> 可以提供复现链接，或者复现代码吗

现在没有，周末可以搞一个出来， 现在一般很少用原生标签初始化样式了吧，这样做，感觉不太好

**Comment by inottn** [comment]
> > > > 具体会影响哪些组件
> > > 
> > > 
> > > 目前已知，会影响element-plus的button组件
> > 
> > 
> > 可以提供复现链接，或者复现代码吗
> 
> 现在没有，周末可以搞一个出来， 现在一般很少用原生标签初始化样式了吧，这样做，感觉不太好

不确定，不过看 antd、element-plus 都有用原生标签初始化样式。

element-plus 的 button 组件是有 color 样式，按理说优先级会更高一些，等有复现链接了，再看看是什么原因吧。
