### ISSUE TITLE
swipe里面如果img包含上a标签跳转滑动过程中直接出发a标签的跳转事件

### ISSUE THREAD

**Issue by chenchu001** [youzan/vant#1301]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
不规范的 issue
