### ISSUE TITLE
在safari浏览器，"@vant/touch-emulator"，"vue-draggable-plus",拖动组件冲突

### ISSUE THREAD

**Issue by xuexirong** [youzan/vant#13024]
### 重现链接

https://github.com/xuexirong/vite.git

### Vant 版本

4.9.3

### 描述一下你遇到的问题。

在safari浏览器，引入@vant/touch-emulator后，拖动vue-draggable-plus内的组件，组件会一直粘在鼠标上放不下，需要点击一下页面才能放下
"@vant/touch-emulator": "^1.4.0" 和"vue-draggable-plus": "^0.4.0",
https://vue-draggable-plus.pages.dev/

### 重现步骤

https://vue-draggable-plus.pages.dev/
vue-draggable-plus 组件创建一个列表，然后拖动组件

### 设备/浏览器

safari浏览器

**Comment by xuexirong** [comment]
@inottn 提供了github项目demo地址

**Comment by inottn** [comment]
你的业务场景需要 @vant/touch-emulator 做什么？

**Comment by xuexirong** [comment]
@inottn 需要用vant里面的图片上传组件uploader，图片预览的时候，需要兼容pc和手机端的点击预览，然后点击消失。如果不引入touch-emulator，在pc模式下，预览图片打开后，关不掉

**Comment by inottn** [comment]
可以看下这个能解决你的问题吗 https://github.com/youzan/vant/tree/main/packages/vant-touch-emulator#%E7%A6%81%E7%94%A8-touch-%E6%A8%A1%E6%8B%9F

**Comment by xuexirong** [comment]
@inottn 加到uploader标签上么？这样就能兼容pc和手机端的图片预览功能和缩放功能了？我明天试试

**Comment by xuexirong** [comment]
> 可以看下这个能解决你的问题吗 https://github.com/youzan/vant/tree/main/packages/vant-touch-emulator#%E7%A6%81%E7%94%A8-touch-%E6%A8%A1%E6%8B%9F

不行，会导致拖拽组件卡顿，可不可以把@vant/touch-emulator 只影响vant4呢？

**Comment by xuexirong** [comment]
> > @inottn 加到uploader标签上么？这样就能兼容pc和手机端的图片预览功能和缩放功能了？我明天试试
> 
> 加到 vue-draggable-plus 组件的外层 div 上试试

可以了，我再观察观察
