### ISSUE TITLE
[Bug Report] PullRefresh is not working. How to fix it?.

### ISSUE THREAD

**Issue by HtetLinThu** [youzan/vant#13027]
### Reproduction Link

https://github.com/HtetLinThu/vant_test/blob/main/src/views/StationView.vue

### Vant Version

^4.9.3

### Describe the Bug

<img width="1059" alt="Screenshot 2024-07-28 at 2 30 44 PM" src="https://github.com/user-attachments/assets/801b8268-4282-49e2-831d-033157004d3d">
<img width="1052" alt="Screenshot 2024-07-28 at 2 30 22 PM" src="https://github.com/user-attachments/assets/abb85435-629b-47ce-8532-5cfe76f7b2c2">

I set up in my vant_test project like the above ss. But PullRefresh is not working. Please help, how to fix it?.

## Issue Description

**Title**: "PullRefresh is not working"

**Context**: 
- Version: ^4.9.3
- Browser: Chrome

## Screenshots / Logs

<img width="300" alt="Screenshot 2024-07-28 at 2 38 21 PM" src="https://github.com/user-attachments/assets/d8888c21-7eee-4d17-8fd8-9f8776235ccc">

### Device / Browser

Chrome Browser

**Comment by inottn** [comment]
<img width="293" alt="image" src="https://github.com/user-attachments/assets/1953df0f-65cd-4029-b362-45171c95eb42">

You can set a minimum height for PullRefresh.

**Comment by HtetLinThu** [comment]
It is ok. Thank You
