### ISSUE TITLE
[Bug Report] Text Ellipsis 无法在ionic下面使用

### ISSUE THREAD

**Issue by agileago** [youzan/vant#13036]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-ionic-3kk459?file=%2Fsrc%2FApp.vue%3A15%2C16&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz81sq3300073b6lhtl9z1r4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz81sq3300023b6l4rmbr34k%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz81sq3300043b6lnv7mebks%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz81sq3300063b6lmpv3avf5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50.367838993807084%252C49.632161006192916%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz81sq3300023b6l4rmbr34k%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz81sq3200013b6ldkdru7d9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A20%257D%255D%257D%252C%257B%2522id%2522%253A%2522clz82rtct00023b6j4p4op5ho%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A16%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clz81sq3300023b6l4rmbr34k%2522%252C%2522activeTabId%2522%253A%2522clz82rtct00023b6j4p4op5ho%2522%257D%252C%2522clz81sq3300063b6lmpv3avf5%2522%253A%257B%2522id%2522%253A%2522clz81sq3300063b6lmpv3avf5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz81sq3300053b6l6a5lnnu4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8080%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clz81sq3300053b6l6a5lnnu4%2522%257D%252C%2522clz81sq3300043b6lnv7mebks%2522%253A%257B%2522id%2522%253A%2522clz81sq3300043b6lnv7mebks%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz81sq3300033b6l8ui7gq21%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clz81sq3300033b6l8ui7gq21%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Vant 版本

latest

### 描述一下你遇到的问题。

无法正确展示....

### 重现步骤

查看复现链接即可，貌似自定义元素下面的vue组件在mounted时是获取不到dom的尺寸信息

### 设备/浏览器

all

**Comment by inottn** [comment]
mounted 时是获取不到 dom 的尺寸信息就没办法了，你可以延迟渲染 Text Ellipsis 组件

**Comment by agileago** [comment]
框架是否换一种监听方式？resizeobserver?

**Comment by inottn** [comment]
> 框架是否换一种监听方式？resizeobserver?

涉及到兼容性问题，暂不考虑，下个大版本可能会支持吧。

**Comment by agileago** [comment]
给后来人个解决方案， 使用resizeObserver来判断dom什么时候有尺寸然后再装载页面：
```typescript
import { useResizeObserver } from '@vueuse/core'

const IonicWrapper = defineComponent((props, ctx) => {
  const contentRef = ref()
  const showContent = ref(false)
  let now = 0

  onMounted(() => (now = Date.now()))

  const rob = useResizeObserver(contentRef, entries => {
    const entry = entries[0]
    const { width } = entry.contentRect
    if (showContent.value) return
    if (width !== 0) {
      console.log('rect gap time', Date.now() - now)
      showContent.value = true
      rob.stop()
    }
  })
  if (!rob.isSupported.value) {
    onMounted(() => setTimeout(() => (showContent.value = true), 50))
  }

  return () => (
    <IonPage>
      <IonContent>
        <div ref={contentRef} class={'h-full'}>{showContent.value ? ctx.slots.default?.() : null}</div>
      </IonContent>
    </IonPage>
  )
})

const PageRoute = defineComponent(() => {
  return () => (
    <IonicWrapper>
      <div>this child is main logic and other component</div>
    </IonicWrapper>
  )
})
```
