### ISSUE TITLE
[Feature Request] nuxt3项目中按需引用vant组件

### ISSUE THREAD

**Issue by li-tao-tao** [youzan/vant#13035]
### 这个功能解决了什么问题？

您好，我在nuxt3项目中使用vant组件，想要按需引入组件，但是文档里给的引入方法在nuxt中都不行，尝试了很多方法都报错，可以支持一下nuxt3按需引入功能吗

### 你期望的 API 是什么样子的？

按需引入需要的组件

**Comment by chenjiahan** [comment]
参考 https://github.com/vant-ui/vant-nuxt
