### ISSUE TITLE
关于picker的问题

### ISSUE THREAD

**Issue by linwenfeng122** [youzan/vant#1303]
picker对于想要高亮显示的defaultIndex动态添加，发生问题。代码如下：
   <van-popup v-model="pickerShow" position="bottom" :overlay="true" >
        <van-picker ref="picker" show-toolbar :columns="pickerList" @cancel="pickerCancel" @confirm="pickerConfirm" />
      </van-popup>
   我根据官方文档里面的通过ref设置setIndexes()，会经常性发生this.refs.picker找不到。
 希望解决的方法：
      在组件里面添加props。来响应动态的index

**Comment by 18510758841** [comment]
你如何解决？

**Comment by linwenfeng122** [comment]
之前的是一个picker去填充多个数据，后面改成一个picker对应一个

**Comment by zyf540860996** [comment]
我也遇到this.refs.picker找不到，我需要动态替换整个联动数据，实在是不知道怎么处理了
