### ISSUE TITLE
vant Rate评分在v-for循环里设置半星allow-half属性有bug

### ISSUE THREAD

**Issue by zsxjotion** [youzan/vant#13030]
### 重现链接

https://github.com/youzan/vant

### Vant 版本

2.13.2

### 描述一下你遇到的问题。

设置半星allow-half属性后，导致每个item里都会出现五个完整星和五个半颗星，正常应该加起来数量一共是五个才对。去掉半星allow-half属性后，每个item个数正常

### 重现步骤

代码例子：
ratingItems: [
        {label: '服务态度', value: 0},
        {label: '服务质量', value: 0},
        {label: '响应速度', value: 0},
        {label: '总体评价', value: 0}
      ],
<div v-for="(item, index) in ratingItems" :key="index" class="rating-item">
        <span class="rating-label">{{ item.label }}:</span>
        <van-rate
          v-model="item.value"
          size="40"
          allow-half
          :readonly="ratingItems.length - 1 === index"
          color="#ffd21e"
          :icon="require('@/assets/common/stara.png')"
          :void-icon="require('@/assets/common/star.png')"
          void-color="#eee"
          @change="rateChange"
        />
      </div>

**Comment by zsxjotion** [comment]
> Hi @zsxjotion. Current version (2.x) is off the maintenance period. We will only fix critical bugs. This issue will be auto closed.
> 
> 你好 @zsxjotion，当前版本（2.x）已经过了维护期。我们仅会修复重要 bug。当前 issue 会被自动关闭。

这个bug不严重吗，已经影响到了项目功能了

**Comment by inottn** [comment]
2.x 版本已经不再维护了，推荐使用 4.x 版本。如果是已有项目的话，可以 fork 后自行修复相关问题。
