### ISSUE TITLE
[Bug Report] checkbox 选择器对象无法自动选中 

### ISSUE THREAD

**Issue by 2084796919** [youzan/vant#13043]
### 重现链接

代码在重现步骤中

### Vant 版本

4.9.1

### 描述一下你遇到的问题。

具体代码如下 
<template>
<van-checkbox-group v-model="checked">
        <van-cell-group inset>
          <van-cell
            v-for="(item, index) in list"
            clickable
            :key="item"
            :title="`复选框 ${item.lable}`"
            @click="toggle(index)"
          >
            <template #right-icon>
              <van-checkbox
                :name="item"
                :ref="(el) => (checkboxRefs[index] = el)"
                @click.stop
              />
            </template>
          </van-cell>
        </van-cell-group>
      </van-checkbox-group>
</template>
<script setup lang="ts">
const checkboxRefs = ref([]);
const checked = [{lable: "a"}, {lable: "b"}];
const list = [{lable: "a"}, {lable: "b"}];
const toggle = (index) => {
  checkboxRefs.value[index].toggle();
};
</script>
是否可以将判断相等的逻辑优化一下

### 重现步骤

无法自动选中对象的

**Comment by inottn** [comment]
参考文档示例 https://vant-ui.github.io/vant/#/en-US/checkbox#inside-a-cell
