### ISSUE TITLE
[Bug Report] 函数式调用 showNotify(); 样式全部丢失

### ISSUE THREAD

**Issue by BocaiheDabaicai** [youzan/vant#13065]
### Reproduction Link

qqeee

### Vant Version

4

### Describe the Bug

我在axios的响应守卫那里调用，以及组件里使用这个函数式调用，均是消息显示，样式全部丢失
![image](https://github.com/user-attachments/assets/fb723319-c8c7-42fd-9b43-e229fab838ae)

### Reproduce Steps

问题已定位，就是挂载的结点不在#app下，使用teleport属性进行修复

**Comment by BocaiheDabaicai** [comment]
中途又能显示，过一会样式有全部丢失

**Comment by s3xysteak** [comment]
+1 ，不知道是不是和unplugin-vue-components有关，因为他在使用组件时才会触发对应resolver，然而`showNotify`函数不在`vite-plugin-vue`编译中被认为是组件

**Comment by s3xysteak** [comment]
在unplugin-auto-import中用resolvers导入可以解决
