### ISSUE TITLE
上传组件被套在v-for循环中，会自动重复触发

### ISSUE THREAD

**Issue by lvkunpeng** [youzan/vant#1306]
**bug描述**

在一个v-for循环的dom结构中，循环出了n个van-uploader组件，每次需要明确的知道触发的index从而渲染到对应的data中，我利用了:before-read="setIndex(index)" 方法设置了一个全局变量index。但是每次结果都是这个行为会触发n次（也就是上传组件的length的数目）最后得到的index永远是length。请问这个是不是有其他的解决办法

**Screenshots**
![image](https://user-images.githubusercontent.com/21191782/41604582-2f30b3c2-7412-11e8-8e7a-3a9ebc4f7129.png)

**Environment**
 - Device: mobile
 - Browser: chrome
 - Vant Version: ^1.1.0

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
这样的写法是有问题的，在 Vue 模板中通过 props 传入带括号的函数会立即执行
可以使用下面的写法：
```js
export default {
  methods: {
    beforeRead(index) {
      return file => {
        console.log(index, file);
      };
    }
  }
}
```

**Comment by TKYV** [comment]
![image](https://user-images.githubusercontent.com/40451314/81480151-5476b880-925a-11ea-9005-b55dd5b2db7e.png)

**Comment by TKYV** [comment]
![image](https://user-images.githubusercontent.com/40451314/81480174-72dcb400-925a-11ea-9529-9d0aae37d15c.png)
![image](https://user-images.githubusercontent.com/40451314/81480178-7b34ef00-925a-11ea-9915-bc6023cd1ca7.png)
![image](https://user-images.githubusercontent.com/40451314/81480182-82f49380-925a-11ea-8f2b-d667df416823.png)
这个怎么解决
