### ISSUE TITLE
Swipe 组件在移动端内部嵌套了一个有横向滚动条的dom，横向滑动的时候会触发swipe的滑动不会触发内部的横向滚动。

### ISSUE THREAD

**Issue by WangJiaBin-LGX** [youzan/vant#13073]
### 重现链接

https://codesandbox.io/p/live/f8477d12-0caf-481f-a7e6-cca2ddad92e4

### Vant 版本

4.2.0

### 描述一下你遇到的问题。

Swipe 组件在移动端内部嵌套了一个有横向滚动条的dom，横向滑动的时候会触发swipe的滑动不会触发内部的横向滚动。

### 重现步骤

1、切换到移动端
2、左右滑动

**Comment by inottn** [comment]
可以监听内部元素的 touch 事件，并在合适的时机阻止事件冒泡
