### ISSUE TITLE
[Bug Report] 有DOM泄漏： swipe 组件用到了 usePageVisibility，'visibilitychange'事件没销毁；

### ISSUE THREAD

**Issue by HerokunTan** [youzan/vant#13076]
### 重现链接

https://github.com/youzan/vant/blob/main/packages/vant/src/swipe/Swipe.tsx

### Vant 版本

4.9.3

### 描述一下你遇到的问题。

swipe ,tabs，tab ; 在上一个路由使用过，切换到下一个路由；在chrome 和 Edge 内存快照都能找到Detached HTMLDivElement 节点；

### 重现步骤

https://vant-ui.github.io/vant/#/zh-CN/swipe
这个例子中，切换路由也有30个 Detached HTMLDivElement

### 设备/浏览器

chrome 127.0.6533.120

**Comment by inottn** [comment]
设计如此，visibilitychange 全局只会监听一次，但是不会取消监听
