### ISSUE TITLE
[Bug Report] Tabs组件切换问题

### ISSUE THREAD

**Issue by YH-82** [youzan/vant#13072]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-llg2kc?file=%2Fsrc%2FApp.vue%3A34%2C21

### Vant 版本

4.9.4

### 描述一下你遇到的问题。

<img width="1381" alt="image" src="https://github.com/user-attachments/assets/ab79b55a-802f-4bdd-a510-bf633ffeb90f">

### 重现步骤

1. 存在两个tab item，第一个高度300，第二个高度100，从第一个切换到第二个的时候，第二个底部存在空白
<img width="1381" alt="image" src="https://github.com/user-attachments/assets/43aba0e3-ca76-4f92-93eb-0a12b14aef52">
2. 经检验：是由于.van-swipe-item中height: 100%覆盖了.van-tab__panel-wrapper--inactive中height:0的样式，导致出现以上问题

注意：codesandbox的链接只是示例，在实际代码中，本地环境的代码.van-tab__panel-wrapper--inactive中height:0会覆盖.van-swipe-item中height: 100%，因此是正常的，如下图
<img width="1338" alt="image" src="https://github.com/user-attachments/assets/4fb04263-c19d-4dce-a126-00090b5af2ad">
然而打包到了测试环境后，就出现问题；
看了源码，这两个样式并没有先后顺序，导致了打包后的先后顺序不确定。或许inactive的样式应该多加一些前缀来保证它的权重
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/97af0eff-a093-41c5-940c-c348ec90eec3">
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/32f25ac7-68f8-4e65-af66-e50524419d7e">

**Comment by pany-ang** [comment]
从你的截图上来看，你在 build 后出现了两份相同的 css：

![d9b8011e-5320-4b8d-a510-4ae69fa10650](https://github.com/user-attachments/assets/09d8fa51-d1de-4e1d-8295-b1e09a213bc7)

所以，这可能和你的构建工具以及构建配置有关，你可以再提供一个最小复现的仓库，这样我才能更好的帮助你找到问题。

**Comment by Alkaidcc** [comment]
https://x.com/Alkaidcc992/status/1813754570331549780?t=YLGU4fZnKOrK_VY9XtQ1bA&s=19

同一个问题，我的解决方法是强制覆盖样式

**Comment by YH-82** [comment]
> https://x.com/Alkaidcc992/status/1813754570331549780?t=YLGU4fZnKOrK_VY9XtQ1bA&s=19
> 
> 同一个问题，我的解决方法是强制覆盖样式

是的，目前是这么解决的。但我的项目不是vite，还是用的webpack，打包后也会出现同样的问题

**Comment by YH-82** [comment]
> https://x.com/Alkaidcc992/status/1813754570331549780?t=YLGU4fZnKOrK_VY9XtQ1bA&s=19
> 
> 同一个问题，我的解决方法是强制覆盖样式

是的，目前是这么解决的。但我的项目不是vite，还是用的webpack，打包后也会出现同样的问题

**Comment by YH-82** [comment]
> https://x.com/Alkaidcc992/status/1813754570331549780?t=YLGU4fZnKOrK_VY9XtQ1bA&s=19
> 
> 同一个问题，我的解决方法是强制覆盖样式

是的，目前是这么解决的。但我的项目不是vite，还是用的webpack，打包后也会出现同样的问题

**Comment by YH-82** [comment]
> https://x.com/Alkaidcc992/status/1813754570331549780?t=YLGU4fZnKOrK_VY9XtQ1bA&s=19
> 
> 同一个问题，我的解决方法是强制覆盖样式

是的，目前是这么解决的。但我的项目不是vite，还是用的webpack，打包后也会出现同样的问题

**Comment by inottn** [comment]
参考 https://github.com/youzan/vant/issues/12643
