### ISSUE TITLE
dialog组件高级用法无法正常使用

### ISSUE THREAD

**Issue by Hellosyikai** [youzan/vant#1308]
问题描述：根据文档提供的dialog组件高级用法，当我把dialog用组件方式引入时，v-model=“show”会出现`'v-model' directives aren't supported on <dialog> elements.` 错误提示，点击改变show=true时，无法触发dialog显示。

浏览器：Google Chrome 65.0.3325.181（正式版本） （64 位）
"vant": "^1.1.8"

![tim 20180620161152](https://user-images.githubusercontent.com/17266095/41646023-50831810-74a5-11e8-969d-afffbd89763a.png)
![tim 20180620161211](https://user-images.githubusercontent.com/17266095/41646031-593aa090-74a5-11e8-9286-51da4ed95b50.png)

**Comment by chenjiahan** [comment]
dialog 是原生标签，请使用 van-dialog
