### ISSUE TITLE
[Bug Report] VanDialog 组件方式的部分样式和属性不生效

### ISSUE THREAD

**Issue by zhaojjiang** [youzan/vant#13088]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-nk98yv

### Vant 版本

4.9.4

### 描述一下你遇到的问题。

- 使用 VantDialog 组件方式时，样式表现与 showDialog 方式不一致，包括但不限于缺少一些默认样式等
- 同时文档中标注的 message-align 也不生效，所以认为这是一个 bug，以待确认

![image](https://github.com/user-attachments/assets/c96aa1b7-decd-4730-aa7c-2591465d9495)

### 重现步骤

代码复现

```html
<van-dialog
      :show="true"
      title="知情同意书"
      show-cancel-button
      message-align="right"
      allow-html
    >
      请先确认<span
        style="color: blue; text-decoration: underline"
        @click="console.log(111)"
        >《知情同意书》</span
      >，点击“同意”按钮代表您已同意前述协议。
</van-dialog>
```

**Comment by inottn** [comment]
message-align 和 allow-html 在使用 message 属性时生效。使用 slot 的方式展示内容时，样式需要自己实现。

**Comment by zhaojjiang** [comment]
- 文档中没有提到需要自己实现
- 文档中 Dialog 组件的 props 列表中有 allow-html 和 message-align 这两个支持项

- 假设文档已被修正的情况下，有没有什么方式可以获取到函数式调用生成的 html 结构和类名，目前只能是先调用一次函数，把生成的结构和样式类名复制到组件的 slot 里

**Comment by inottn** [comment]
你的场景不能使用 message 属性吗

**Comment by zhaojjiang** [comment]
我需要在 message 里的某些文本上加一个事件，我刚试了下 message 属性的函数类型 + jsx/h 也可以实现这个需求，不需要组件形式了

**Comment by inottn** [comment]
> 作为需求可以关闭，但是文档我仍认为是有问题的，可以考虑完善下文档

PR welcome
