### ISSUE TITLE
[Feature Request] 大数据量分页选择加搜索

### ISSUE THREAD

**Issue by 785029615** [youzan/vant#13098]
### 这个功能解决了什么问题？

分页数据多选

### 你期望的 API 是什么样子的？

<el-select
    v-model="value"
    filterable
    placeholder="Select"
    style="width: 240px"
  >

**Comment by inottn** [comment]
移动端的交互和 PC 不同，暂时没有打算增加这个组件

**Comment by kooriookami** [comment]
![image](https://github.com/user-attachments/assets/e4d85ef5-df46-4868-9cbf-2ec260253cc9)
https://wot-design-uni.pages.dev/component/select-picker.html
我感觉这样的形式很可以
