### ISSUE TITLE
[Feature Request] SelectPicker 单复选选择器

### ISSUE THREAD

**Issue by 785029615** [youzan/vant#13099]
### 这个功能解决了什么问题？

表单选择数据
![微信截图_20240903132110](https://github.com/user-attachments/assets/1b9a0c3d-7dc1-49b5-8573-c588c07b9193)

### 你期望的 API 是什么样子的？

https://wot-design-uni.pages.dev/component/select-picker

**Comment by chenjiahan** [comment]
Vant 暂时没有计划提供这个组件，它可以组合 Popup 和 Checkbox 组件来实现
