### ISSUE TITLE
[Feature Request] FloatingBubble 浮动气泡能有一个主动设置气泡位置的api么？

### ISSUE THREAD

**Issue by alittlesister** [youzan/vant#13091]
### 这个功能解决了什么问题？

1、我想从外面就能动态改动气泡的位置，方便我们去设置当出现一些其他的交互的时候，可以去设置气泡的位置
2、我想给气泡加初始化出现时的动效，不好加，因为transform属性冲突

### 你期望的 API 是什么样子的？

<FloatBubbles ref="floatRef" animation="{动效相关属性}"></FloatBubbles>

floatRef.value.offset = {x:10,y:400}

**Comment by inottn** [comment]
可以通过设置 v-model:offset 的值解决这个问题吗

**Comment by inottn** [comment]
> 不行，v-model只能从组件内部响应式，组件外面赋值没有效果

设计上是可以的，如果不行的话，可以提供一下复现代码看看
