### ISSUE TITLE
[Bug Report] 荣耀100 pro ,支付宝小程序内嵌套Vue页面。点击相册，小程序会崩溃。

### ISSUE THREAD

**Issue by udofly** [youzan/vant#13101]
### Reproduction Link

支付宝搜索氪金兽、我的。意见与反馈。可以测试上传图片

### Vant Version

4.9.0

### Describe the Bug

荣耀100 pro ,支付宝小程序内嵌套Vue页面。点击上传照片，选择相册，小程序会崩溃。

### Reproduce Steps

荣耀100 pro ,支付宝小程序内嵌套Vue页面。点击上传照片，选择相册，小程序会崩溃。可以在支付宝搜索氪金兽、我的。意见与反馈等很多上传图片的地方，测试上传图片，即可复现。可以用云真机复现。

**Comment by zhaojjiang** [comment]
你这个信息太少了，甚至都不一定和 vant 有关系，哪怕真的复现了作者也不知道为什么，需要由你通过调试和日志等方式进一步定位

**Comment by chenjiahan** [comment]
可以用原生 input 标签试下

![image](https://github.com/user-attachments/assets/5ea91a1a-9291-4a78-847e-00c3d2e519ce)
