### ISSUE TITLE
使用 auto-import-resolver 自动导入方案，showToast 样式异常

### ISSUE THREAD

**Issue by LLoyou00** [youzan/vant#13109]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-krwnzx?workspaceId=9400e5bf-025d-413b-b67a-67f1c3e8592a

### Vant 版本

4.9.5

### 描述一下你遇到的问题。

首先，auto-import-resolver 好像没法自动导入 toast 的 css 文件，所以我进行了手动导入，但出现了另一个问题，如果我在 main.js 中导入 toast 的 css 文件，由于 toast 本质是一个 popup，而 popup 的样式文件是在  toast 之后导入的，优先级更高，所以会覆盖掉 toast 的样式，导致 toast 无法正常显示。

给的链接没有配置 auto-import-resolver，只是通过手动导入 css 文件模拟了一下上述的情况。

### 重现步骤

RT

**Comment by zhaojjiang** [comment]
问题还存在吗，给出的链接失效了

**Comment by LLoyou00** [comment]
> 问题还存在吗，给出的链接失效了

是的，而且我发现不仅 showToast 有这个问题，showDialog 也有同样的问题，同样是没法通过 auto-import-resolver 自动导入CSS 文件，手动在 main.js 导入的话，又有会被自动导入的 popup 的CSS文件影响，我现在是又把 toast 和 dialog 的样式重新定义了一次，加上 important 提高优先级。

**Comment by zhaojjiang** [comment]
按你的描述，我之前手动导入，以及现在自动导入，两种情况下都没有遇见过你说的问题，所以还是需要一个示例

**Comment by LLoyou00** [comment]
> 按你的描述，我之前手动导入，以及现在自动导入，两种情况下都没有遇见过你说的问题，所以还是需要一个示例

不好意思，重新检查了一下代码，发现是我又通过 import 手动导入了 showToast 函数，
![image](https://github.com/user-attachments/assets/6befc804-2a04-40d2-b1c7-5768e4e11e0f)
大概是这样，然后查看页面，确实没有导入 toast 的 css 文件 
![image](https://github.com/user-attachments/assets/9cb96ebc-a3e5-4b18-a814-49481d2498f7)

删除 import 语句后就正常了，通过 auto-import 自动导入的话没有问题。

**Comment by zhaojjiang** [comment]
这个问题在初始 PR #12679 中有提到过，即手动/显式导入时不会处理样式，只有在 auto-import 自动导入时才会处理，但我查阅文档发现好像没有这一部分的说明

**Comment by chenjiahan** [comment]
欢迎补充文档～

**Comment by CherishTheYouth** [comment]
![image](https://github.com/user-attachments/assets/1ea4840f-7137-4b61-818b-5da625e45c95)

**Comment by MayfliesST** [comment]
单独在main.ts中引入样式：
  import "vant/es/toast/style";
  import "vant/es/dialog/style";
  import "vant/es/image-preview/style";
参考：openim-h5
不知道是否有其他影响

**Comment by wenxutao** [comment]
自动导入组件后，在页面中不能再 import { showToast } from 'vant'; 了，再引入的话样式就会异常

**Comment by lelouch-xue** [comment]
但如果是在request.js 页面，非sfc 里面，必须得导入  import { showToast } from 'vant'; 这样也会导致样式问题的

**Comment by aboutZZ** [comment]
> 但如果是在request.js 页面，非sfc 里面，必须得导入 import { showToast } from 'vant'; 这样也会导致样式问题的

我现在就遇到这种问题了，封装网络请求request.js，引入了 `import { showToast } from 'vant';` 
结果导致toast背景变成白的，toast文字看不见了

请问您是怎么解决的？
