### ISSUE TITLE
DropdownMenu 和 Popup 组合使用，在 Popup 上单击会导致  DropdownMenu 被关闭。

### ISSUE THREAD

**Issue by LLoyou00** [youzan/vant#13104]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-j7m7tp?workspaceId=9400e5bf-025d-413b-b67a-67f1c3e8592a

### Vant 版本

4.9.4

### 描述一下你遇到的问题。

![image](https://github.com/user-attachments/assets/d26cca68-3a14-4c57-bf4d-c7d2545537aa)
点击红框区域，Popup 会保留，但 DropdownMenu 会被关闭，点击红框之外的区域，Popup 和 DropdownMenu 都会被关闭，期望的情况应该是 Popup 先关闭。

### 重现步骤

1.展开 DropdownMenu 
2.点击 Open Popup 显示 Popup
3.点击任意区域

**Comment by inottn** [comment]
这个行为是符合预期的，你可以设置 DropdownMenu 的 close-on-click-outside 属性改变这一行为

**Comment by LLoyou00** [comment]
> 这个行为是符合预期的，你可以设置 DropdownMenu 的 close-on-click-outside 属性改变这一行为

好的
