### ISSUE TITLE
Stepper 值为空

### ISSUE THREAD

**Issue by GodStream** [youzan/vant#1311]
**Describe the bug**
目前在Stepper的input中输入值时，如果将值退格掉，值就为空了。

**Screenshots**
![image](https://user-images.githubusercontent.com/23089466/41693641-d98d7fea-7538-11e8-8baa-cd3e83fd0c54.png)

**Environment**
 - Vant Version: 1.1.8

**Comment by chenjiahan** [comment]
本身就允许删除操作的
