### ISSUE TITLE
Field组件密码输入框显示隐藏问题

### ISSUE THREAD

**Issue by suifeng156** [youzan/vant#13119]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-qs5w8x

### Vant 版本

4.9.4

### 描述一下你遇到的问题。

![111111111](https://github.com/user-attachments/assets/6c32d0be-8ee4-460d-b10f-4e8e0ee3f248)

### 重现步骤

数入一个字符或者多个字符反复点击

**Comment by inottn** [comment]
有什么问题？
