### ISSUE TITLE
[Bug Report] showImagePreview横屏时无法上下滑动

### ISSUE THREAD

**Issue by IndexLibrary** [youzan/vant#13134]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-4my6jl

### Vant 版本

4.9.7

### 描述一下你遇到的问题。

页面旋转90度，设置teleport到旋转的元素，图片放大后只能左右滑动，无法上下滑动

### 重现步骤

双指放大图片，上下滑动查看图片，结果无法上下滑动

**Comment by inottn** [comment]
实现上没有考虑这个场景
