### ISSUE TITLE
[Bug Report] Picker 的 option 插槽没有回传参数

### ISSUE THREAD

**Issue by evil-li** [youzan/vant#13139]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-cv35tq

### Vant 版本

4.9.7

### 描述一下你遇到的问题。

 Picker 的 option 插槽没有按照文档描述的那样回传 option 和 index

### 重现步骤

不需要任何操作

**Comment by inottn** [comment]
参考https://github.com/youzan/vant/issues/11972

**Comment by bijiazhume** [comment]
这个问题修复了吗 在TimePick 的option插槽只拿到了 option 没有index的值
