### ISSUE TITLE
[Bug Report] FloatingPanel 浮动面板无法横向滚动

### ISSUE THREAD

**Issue by zqzq1217** [youzan/vant#13158]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/floating-panel

### Vant 版本

4.9.8

### 描述一下你遇到的问题。

FloatingPanel 浮动面板无法横向滚动如果开启了content-draggable 为true的话，子元素overflow: auto, 好像会导致子元素无法横向滚动

### 重现步骤

FloatingPanel 浮动面板设置属性 content-draggable=true 子元素overflow: auto

### 设备/浏览器

ios

**Comment by zqzq1217** [comment]
https://codesandbox.io/p/devbox/vant-4-issue-template-8fuq5o

**Comment by inottn** [comment]
> https://codesandbox.io/p/devbox/vant-4-issue-template-8fuq5o

The link doesn't seem to be related to this issue.
