### ISSUE TITLE
[Bug Report] 4.9.6版本Field组件type="number"时出现多种交互问题

### ISSUE THREAD

**Issue by yuwuwu** [youzan/vant#13154]
### 重现链接

https://vant-ui.github.io/vant/#/zh-CN/field

### Vant 版本

4.9.6

### 描述一下你遇到的问题。

1.一直输入数字，当大于16位后，失焦后16位之后会被自动修改为0，但是打印对应的value还是正确的值
2.一直输入数字，会自动转换为科学输入法，但是变成了1.xx
package里相关配置为`"vant": "^4.9.0"`,所以流水线每次都会，拉取最新小版本，该问题目前一直存在，只能先采用锁版本方式，希望后续版本修复该问题。

### 重现步骤

`npm install vant@4.9.6`
```
<van-field
            v-model="form.accountNo"
            type="number"
            name="accountNo"
            placeholder="请输入银行账户"
          />
```
安装4.9.6版本，然后设置field的type="number"稳定复现

### 设备/浏览器

all

**Comment by aBrightWorld** [comment]
锁4.9.2 版本 我也遇到了

**Comment by yuwuwu** [comment]
可以锁住版本为4.9.0，这个版本未复现该问题
