### ISSUE TITLE
Stepper 步进器

### ISSUE THREAD

**Issue by louie-liang** [youzan/vant#1315]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
步进器输入数值可以清空。
- 点击输入框，如果有值的话。按退格键删除，完全删除的时候，输入框就为空了
- 全删除的清空下，默认应该是 1 吧
- 版本用的1.15，在官网测试了下也有这个问题

**Screenshots**
Add screenshots to help explain your problem.
**Environment**
 - Device: 手机， pc
 - Browser:   chrome
 - Vant Version: 1.15

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
首先这个不是 bug，Stepper 本身就是允许退格删除的，比如用户想把 5 改成 10，必然会先删除 5 再输入 10

为了避免用户输入完成后 Stepper 里的值为空的情况，下个版本会加上这样的逻辑：
若输入框 blur 时内容为空，则自动填写为最小值

**Comment by louie-liang** [comment]
@chenjiahan 我做了一个判断 当为空的时候，绑定的值 为1  。第一次操作是可行的，第二次就还是为空了。目前有什么别的解决办法吗

**Comment by chenjiahan** [comment]
@louie-liang 直接升级至 1.1.9 版本就行，已经加上了上面我说的逻辑，应该能符合你的需求
