### ISSUE TITLE
[Bug Report] 键盘输入“Enter” 会导致 Dialog 的被 Confirm

### ISSUE THREAD

**Issue by baijunjie** [youzan/vant#13164]
### Reproduction Link

https://vant-ui.github.io/vant/#/zh-CN/dialog

### Vant Version

4.9.3

### Describe the Bug

官方文档中的 Demo 就可以重现，在右侧的 Preview 中，打开一个 Dialog，然后敲击键盘的“Enter”键，Dialog会被关闭。
这应该不属于Bug，可能是开发人员为 Dialog 实现的键盘辅助能力。
但是这个功能在移动设备中并没有实际意义。
同时在使用扫码仪的设备上会引发一个Bug，因为大部分扫码设备都是通过 keyborad 事件进行输入的，并且会在输入完成时输入“Enter”, 这就会导致 Dialog 被确认。

是否可以提供一个选项来关闭这个键盘控制的能力？

### Reproduce Steps
<img width="394" alt="image" src="https://github.com/user-attachments/assets/2a2ec0d9-b0d7-438d-8248-0a1fe37f03ef">
<img width="389" alt="image" src="https://github.com/user-attachments/assets/c1a01383-5d43-4a18-9b46-236c14611e92">
官方文档中的 Demo 就可以重现，在右侧的 Preview 中，打开一个 Dialog，然后敲击键盘的“Enter”键，Dialog会被关闭。

**Comment by inottn** [comment]
可以提供一个在移动端可以复现的链接

**Comment by baijunjie** [comment]
> 可以提供一个在移动端可以复现的链接

你好，要完整复现这个问题需要外接扫码设备，这本身和代码无关，所以单独建立的线上最小demo没有意义。
官方文档中的Demo就可以复现，只要敲击回车键，Dialog就会被关闭。

**Comment by inottn** [comment]
> > 可以提供一个在移动端可以复现的链接
> 
> 你好，要完整复现这个问题需要外接扫码设备，这本身和代码无关，所以单独建立的线上最小demo没有意义。 官方文档中的Demo就可以复现，只要敲击回车键，Dialog就会被关闭。

我想确认一下扫码设备这个场景下的交互流程是怎么样的，Dialog 是在键盘输入前就会弹出吗

**Comment by baijunjie** [comment]
> > > 可以提供一个在移动端可以复现的链接
> > 
> > 
> > 你好，要完整复现这个问题需要外接扫码设备，这本身和代码无关，所以单独建立的线上最小demo没有意义。 官方文档中的Demo就可以复现，只要敲击回车键，Dialog就会被关闭。
> 
> 我想确认一下扫码设备这个场景下的交互流程是怎么样的，Dialog 是在键盘输入前就会弹出吗

是这样的，我们的业务中，用户扫码枪扫票一个有效的条形码后，会有一个Dialog的确认，用于让用户确认是否要变更该码的状态。但是如果此时用户继续使用扫码枪扫描这一个条形码，这个Dialog就会被确认。这在扫码枪识别比较灵敏的时候非常容易发生。
由于扫码枪的输入行为是系统级的，所以仅通过网页前端无法解决这个问题。

**Comment by inottn** [comment]
了解了，我觉得可以提供一个选项
