### ISSUE TITLE
出现重复的主题类名

### ISSUE THREAD

**Issue by Marco-hui** [youzan/vant#13179]
### 重现链接

https://vant.pro/vant/mobile#/zh-CN/config-provider

### Vant 版本

4.9.5

### 描述一下你遇到的问题。

![image](https://github.com/user-attachments/assets/9e33f1a4-e746-44f3-8f23-acb5072d50e5)
把vant主题切到暗色模式后，html节点上的class改成‘van-theme-dark’，但是当再次切换页面时，会在html再次添加'van-theme-light'类名，出现了‘van-theme-dark’和'van-theme-light'共存的现象

### 重现步骤

https://github.com/user-attachments/assets/0f22faba-4748-4661-9d5d-776bc5c6dc87

如上录屏所示

### 设备/浏览器

任意

**Comment by chenjiahan** [comment]
Fixed, thank you
