### ISSUE TITLE
[Feature Request] 请在未来版本增加一个【Selector 选择组】组件

### ISSUE THREAD

**Issue by chenghanqq** [youzan/vant#13173]
### 这个功能解决了什么问题？

对标Ant Mobile [https://mobile.ant.design/zh/components/selector](https://mobile.ant.design/zh/components/selector)
产品筛选时常用到。

### 你期望的 API 是什么样子的？

已经有了TreeSelector组件，或者请扩展该组件

**Comment by chenjiahan** [comment]
目前没有这个计划，有需要的话建议基于 Checkbox 组件定制一下
