### ISSUE TITLE
组件类型丢失any

### ISSUE THREAD

**Issue by linyongjun213** [youzan/vant#13185]
### Reproduction Link

https://gitee.com/linyongjun213/vue3-template-vant

### Vant Version

4.9.6

### Describe the Bug

![vant4 9 5](https://github.com/user-attachments/assets/df625de8-82e3-4302-938c-c24ca60f25f9)
![vant4 9 6](https://github.com/user-attachments/assets/8f7e71b8-66ba-4d45-ad78-b8ccbb0a7583)

### Reproduce Steps

4.9.5升级4.9.6

**Comment by linyongjun213** [comment]
最新的4.9.8也是这样

**Comment by wChenonly** [comment]
![image](https://github.com/user-attachments/assets/dbd57b56-38d6-42ae-a569-bd3265460244)
没看到问题

**Comment by linyongjun213** [comment]
不好意思 给你添麻烦了 升级了下typescript就可以了
