### ISSUE TITLE
[Feature Request] 给popup弹出框添加关闭时，销毁其中的元素功能

### ISSUE THREAD

**Issue by PeyFon** [youzan/vant#13199]
### 这个功能解决了什么问题？

添加destroy-on-close属性布尔值，能够在popup关闭的时候自动销毁其内部的元素。

### 你期望的 API 是什么样子的？

<van-popup v-model:show="show" :style="{ padding: '64px' }" destroy-on-close><van-picker>picker组件</van-picker></van-popup>
```[tasklist]
### Tasks
```

**Comment by 7hao123** [comment]
借题问一下，进行编辑操作，popup里面的子组件主要是一个input用户会修改，由于第二次进去不会触发mounted，如果用户修改了input但是没有保存，子组件没有销毁，就会导致再次编辑拉起popup的时候input的值有bug，使用了v-if强制刷新的话会有样式bug，有什么解决方案吗？

**Comment by inottn** [comment]
> 借题问一下，进行编辑操作，popup里面的子组件主要是一个input用户会修改，由于第二次进去不会触发mounted，如果用户修改了input但是没有保存，子组件没有销毁，就会导致再次编辑拉起popup的时候input的值有bug，使用了v-if强制刷新的话会有样式bug，有什么解决方案吗？

样式的 bug 是指什么

**Comment by 7hao123** [comment]
给子组件加v-if，会导致关闭的时候，关闭动画过程中popup的内容为空

![019E1199-DD74-470E-E718-9D5F08386F81](https://github.com/user-attachments/assets/4a8845e1-2cdc-4b7c-a4cf-a9f5ed79e555)

**Comment by 7hao123** [comment]
目前通过给子组件加随机key解决了

**Comment by inottn** [comment]
> 目前通过给子组件加随机key解决了

理解了，这个 issue 提到的功能应该可以解决这个问题
