### ISSUE TITLE
[Feature Request] DropdownMenu 可以加个标签吗

### ISSUE THREAD

**Issue by faddei** [youzan/vant#13190]
### 这个功能解决了什么问题？

![image](https://github.com/user-attachments/assets/5a7e8d79-099c-48f1-ab37-5661c4c275eb)

### 你期望的 API 是什么样子的？

```
<van-dropdown-menu>
  <van-dropdown-item v-model="value1" :options="option1" label="标签1" />
  <van-dropdown-item v-model="value2" :options="option2" label="标签2"  />
</van-dropdown-menu>
```

**Comment by lzxiaoqi** [comment]
现在的title插槽应该就可以实现您的需求

**Comment by inottn** [comment]
> @lzxiaoqi 现在的title插槽可以实现,但是选中时会加active

你可以尝试使用样式解决这个问题，暂时没有计划增加这个属性。
