### ISSUE TITLE
[Bug Report] ActionSheet 多次跳转页面再返回面板不会关闭

### ISSUE THREAD

**Issue by gitlibingchen** [youzan/vant#13193]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-8t2q48

### Vant 版本

4.9.8

### 描述一下你遇到的问题。

多次跳转页面再返回面板不会关闭，点遮罩和取消按钮没有响应，页面卡死

### 重现步骤

1. 点击跳转
2. 点击返回
3. 点击跳转
4. 点击返回
5. 面板关闭不了

### 设备/浏览器

edge
```[tasklist]
### Tasks
```

**Comment by lzxiaoqi** [comment]
您好，问题应该是当路由切换时,组件会被销毁和重建,但 ActionSheet 的显示状态可能未正确重置。
有两种办法：
1、路由变化的时候修改对应组件状态
const show = ref(false);
const route = useRoute();
watch(
  () => route.name,
  () => {
    show.value = false;
  }
);

2、生命周期调整组件状态

onUnmounted(() => {
  show.value = false;
});

这个我理解最好不要修改ActionSheet组件源码，因为涉及到路由的监听会增加组件的复杂度和耦合度，我们外部使用的时候注意组件状态即可。

**Comment by gitlibingchen** [comment]
路由切换 show 只要改变就会出现问题，
onActivated 倒是可以，但是会遮罩动画会闪一下

**Comment by lzxiaoqi** [comment]
<template>
  page1
  <van-cell is-link title="跳转" @click="show = true" />
  <van-action-sheet
    close-on-popstate
    cancel-text="取消"
    v-model:show="show"
    :actions="actions"
  />
</template>

<script setup>
import { ref, onActivated, onUnmounted, watch } from "vue";
import { useRouter, onBeforeRouteLeave, useRoute } from "vue-router";

defineOptions({ name: "page1" });

const router = useRouter();
const show = ref(false);
const actions = [
  {
    name: "page2",
    callback() {
      router.push({ name: "page2" });
    },
  },
];
const route = useRoute();
watch(
  () => route.name,
  () => {
    show.value = false;
  }
);
</script>     参考下这个代码，我测试是正常的。
