### ISSUE TITLE
field组件在iOS16.6，16.7等版本中输入内容重叠

### ISSUE THREAD

**Issue by lutan8673** [youzan/vant#13192]
### 重现链接

https://codesandbox.io/p/sandbox/vant-4-issue-template-forked-d9frc6

### Vant 版本

4.2.0

### 描述一下你遇到的问题。

field组件在iOS16.6，16.7等版本中输入内容重叠

### 重现步骤

1.“<van-field v-model="text1" label="文本1" input-align="right" placeholder="请输入" :clearable="true"></van-field>”
设置input-align="right", clearable="true"。
2.在iOS版本为16.6等版本的设备浏览器中输入文本即可复现。
![test](https://github.com/user-attachments/assets/6a6274ec-c903-498d-ac8d-2d6a59b18ed4)

### 设备/浏览器

iOS版本为16.6, 16.7版本的设备浏览器中运行

**Comment by lutan8673** [comment]
close

**Comment by giimlhd** [comment]
@lutan8673  请问这个问题解决了吗 ？ 我也遇到了。

**Comment by lutan8673** [comment]
> [@lutan8673](https://github.com/lutan8673) 请问这个问题解决了吗 ？ 我也遇到了。

css设置一下overflow: hidden;
