### ISSUE TITLE
[Feature Request] field组件搭配picker等弹出层使用时的问题

### ISSUE THREAD

**Issue by yuhengshen** [youzan/vant#13207]
### 这个功能解决了什么问题？

# 场景
使用field搭配弹出层时，此时一般field为`readonly`状态，此时我想要给field增加`clearable`不生效。
# 方案
1. 不使用readonly，额外通过ref操作dom的方式给input加`inputmode`属性，此时`clearable`可以生效，但是移动端会有额外的光标显示出来，不够好。(另外希望能暴露inputmode这个原生属性在field上)
![Screenshot_2024-11-15-10-06-28-456_com microsoft](https://github.com/user-attachments/assets/9b3d8761-4054-4a38-ab57-2793da2b3f47)
3. 希望在readonly状态下，clearable默认为false，但可以通过prop修改为true

### 你期望的 API 是什么样子的？

<van-field inputmode="none" />

<van-field readonly clearable />
```[tasklist]
### Tasks
```

**Comment by yuhengshen** [comment]
希望能实现一下两种情况
```vue
<van-field inputmode="none" />
<van-field readoly clearable />
```

**Comment by inottn** [comment]
在列举的这个场景下，不使用 Field 会不会更好一些，或者你可以使用 input slot 自定义相关的属性和事件。

**Comment by yuhengshen** [comment]
好的，但是我希望能增加inputmode属性，这个应该是可以的吧。

**Comment by yuhengshen** [comment]
> 在列举的这个场景下，不使用 Field 会不会更好一些，或者你可以使用 input slot 自定义相关的属性和事件。

因为这里是要搭配form组件进行处理的，所以是需要用到field与form进行交互

**Comment by inottn** [comment]
可以尝试使用 input slot 来解决这个问题，因为 type prop 在组件内部和 inputmode 有一定关联。在这种情况下，我不太倾向于将这个属性暴露给用户。

**Comment by yuhengshen** [comment]
我看了代码，里面确实有个mapInputType，但是我认为应该优先使用用户的inputmode，mapInputType应该作为备选

**Comment by yuhengshen** [comment]
用户应该有选择键盘弹出的主动权
