### ISSUE TITLE
[Bug Report] vant-field type=number 首位是0的时候 0就被自动删除了 0应该也是number吧

### ISSUE THREAD

**Issue by Xhyen** [youzan/vant#13211]
### Reproduction Link

无

### Vant Version

4.9.6

### Describe the Bug

vant-field type=number 首位是0的时候 0就被自动删除了 0应该也是number吧

### Reproduce Steps

输入0开头的就行

**Comment by inottn** [comment]
用最新版本试一下

**Comment by inottn** [comment]
这个问题之前修复了，所以这个 issue 先关闭了。如果最新版本也有问题，你可以附带重现链接 reopen 这个 issue。

**Comment by Xhyen** [comment]
> 这个问题之前修复了，所以这个 issue 先关闭了。如果最新版本也有问题，你可以附带重现链接 reopen 这个 issue。

https://vant-ui.github.io/vant/#/zh-CN/field

你们官网就能复现 4.9.6的版本 在右侧field是数字类型输入01234 然后失焦 就可以看了

**Comment by inottn** [comment]
> > 这个问题之前修复了，所以这个 issue 先关闭了。如果最新版本也有问题，你可以附带重现链接 reopen 这个 issue。
> 
> https://vant-ui.github.io/vant/#/zh-CN/field
> 
> 你们官网就能复现 4.9.6的版本 在右侧field是数字类型输入01234 然后失焦 就可以看了

https://github.com/youzan/vant/releases/tag/v4.9.9 你可以用最新版本试试，官网有时候部署失败了，不一定是最新版本。

**Comment by Xhyen** [comment]
> > > 这个问题之前修复了，所以这个 issue 先关闭了。如果最新版本也有问题，你可以附带重现链接 reopen 这个 issue。
> > 
> > 
> > https://vant-ui.github.io/vant/#/zh-CN/field
> > 你们官网就能复现 4.9.6的版本 在右侧field是数字类型输入01234 然后失焦 就可以看了
> 
> https://github.com/youzan/vant/releases/tag/v4.9.9 你可以用最新版本试试，官网有时候部署失败了，不一定是最新版本。

ok好的我去试试
