### ISSUE TITLE
Vite打包突然报错，vite和vant版本号没变，业务代码没变

### ISSUE THREAD

**Issue by BNK-ALONG** [youzan/vant#13210]
### What problem does this feature solve?

![image](https://github.com/user-attachments/assets/eb39d0e4-33d7-475b-9a7b-07aeaf0285a9)

只要含有Vant组件的页面就是构建失败。

### What does the proposed API look like?

xxx

**Comment by moriachan12** [comment]
同样遇到了这个问题

**Comment by Mgooddard** [comment]
me too

**Comment by inottn** [comment]
从给出的信息看不出问题在哪里，可以用对应的 issue 模板重新创建一个 issue 进行 Bug 反馈。

**Comment by Mgooddard** [comment]
升级版本就可以了
