### ISSUE TITLE
vite 项目引入 vant 后 run build 报错

### ISSUE THREAD

**Issue by Cewr** [youzan/vant#13212]
### Reproduction Link

https://github.com/Cewr/vue3_demo.git

### Vant Version

4.9.8

### Describe the Bug

vite 项目引入 vant 后执行 build 时报错
![image](https://github.com/user-attachments/assets/5f2e0414-2152-4bde-85ef-bf258a0bf50e)

### Reproduce Steps

npm run build

**Comment by inottn** [comment]
可能和某个依赖有关，你可以执行 npm update 升级相关依赖，然后再试试。

**Comment by Cewr** [comment]
npm update 之后可以了谢谢
