### ISSUE TITLE
[Feature Request] Calendar的formatter希望增加className支持数组

### ISSUE THREAD

**Issue by 7hao123** [youzan/vant#13238]
### 这个功能解决了什么问题？

目前我有一个场景，是需要改造日历的样式，分别是有数据的时候，没有数据的时候，还需要区分是否选中是否是今天，这些样式，需要排列组合所有的情况，比较麻烦。

### 你期望的 API 是什么样子的？

className = ['className1','className2']

**Comment by inottn** [comment]
可以使用 `['className1','className2'].join(" ")`  解决，暂时不考虑支持这个功能
