### ISSUE TITLE
[Bug Report] 在浮动面板中使用下拉菜单，下拉菜单显示会有问题

### ISSUE THREAD

**Issue by lammyself** [youzan/vant#13248]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-tyrrh4

### Vant 版本

4.9.4

### 描述一下你遇到的问题。

因为浮动面板使用了 ```transform```，导致类名为```van-dropdown-item van-dropdown-item--up```的元素相对于浮动面板定位。

### 重现步骤

1. 将浮动面板展开；
2. 展开下拉菜单；

### 设备/浏览器

Chrome@131.0.6778.86

**Comment by inottn** [comment]
可以使用 auto-locate prop 试一试

**Comment by lammyself** [comment]
> 可以使用 auto-locate prop 试一试

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/cd0a19ae-d8c6-4e7b-871c-038630820f1b">
还是不行，teleport设为body也不行。唯一可行的：van-dropdown-menu direction="up" + van-dropdown-item :teleport="bodyEl"。
但是这样也没有解决问题，而是因为浮动面板的bottom：0和body一样

**Comment by inottn** [comment]
> 可以使用 auto-locate prop 试一试

重现链接里 vant 的版本比较低，可以使用 4.8.1 以上的版本。

**Comment by lammyself** [comment]
> > 可以使用 auto-locate prop 试一试
> 
> 重现链接里 vant 的版本比较低，可以使用 4.8.1 以上的版本。

4.9.2可以
