### ISSUE TITLE
[Bug Report] vant-weapp van-search 自定义组件中使用时插槽样式无法修改

### ISSUE THREAD

**Issue by coderfqw** [youzan/vant#13243]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-forked-ddln2w?file=%2Fsrc%2FApp.vue%3A5%2C19

### Vant 版本

^1.11.7

### 描述一下你遇到的问题。

vant-weapp van-search 自定义组件中使用时插槽样式无法修改

### 重现步骤

在自定义组件 UseSearch 中使用了 van-search 组件 在自定义组件中对插槽样式进行修改无法生效
在Page中一样的代码是可以对插槽样式进行修改的
代码片段：
```html
<van-search shape="round" value="{{ value }}" placeholder="输入搜索" use-left-icon-slot use-right-icon-slot>
    <view slot="left-icon">
      <image mode="aspectFit" src="*****.svg"></image>
    </view>
    <view slot="right-icon">搜索</view>
</van-search>
```
我也尝试了在我的 UseSearch 组件中 添加了addGlobalClass
```javascript
Component({
  options: {
    addGlobalClass: true
  },
})
```
添加后可以继承Page中的样式对van-search 插槽样式进行调整。
但是我希望的是可以直接在我的 UseSearch 组件中对van-search 插槽样式直接进行调整，以便于统一管理。

### 设备/浏览器

微信小程序

**Comment by inottn** [comment]
可以在 vant-weapp 的仓库上报这个问题
