### ISSUE TITLE
[Bug Report] FloatingPanel 浮动面板不是最大高度时，里面的内容不能完全展示

### ISSUE THREAD

**Issue by xuewuzhanmeng** [youzan/vant#13278]
### Reproduction Link

https://vant-ui.github.io/vant/#/zh-CN/floating-panel

### Vant Version

4.9.15

### Describe the Bug

浮动面板不是最大高度时，里面的内容不能完全展示，vant文档中的基础示例也是这种情况，不是最大高度时，列表只能滚动到列表T，面板拉到最大高度时，才能展示出列表底部的Z；
<img width="433" alt="image" src="https://github.com/user-attachments/assets/fcadff84-db2e-4d4c-933f-bf4a72660380" />
<img width="383" alt="image" src="https://github.com/user-attachments/assets/904206ce-2179-41df-9dd0-df88a41877a1" />

### Reproduce Steps

FloatingPanel 浮动面板文档中基础用法已展现相关问题

**Comment by inottn** [comment]
Duplicated with #13162
