### ISSUE TITLE
[Bug Report] van-field type number 0.000000001失去焦点后直接变成1

### ISSUE THREAD

**Issue by amshiro** [youzan/vant#13272]
### Reproduction Link

https://vant-ui.github.io/vant/#/zh-CN/field

### Vant Version

4.9.7

### Describe the Bug

van-field 类型number时输入0.000001（小数点6位） 时正常，0.0000001（小数点7位）  onblur后框里面的值直接变成1，这是为啥，我自己感觉时触发了科学计数法

### Reproduce Steps

van-field 类型number时输入0.000001（小数点6位） 时正常，0.0000001（小数点7位）  onblur后框里面的值直接变成1，这是为啥，我自己感觉时触发了科学计数法

### Device / Browser

ios
```[tasklist]
### Tasks
```

**Comment by amshiro** [comment]
我在官网试确实小数input 时是正常的，我的库用在nuxt 上版本 "@vant/nuxt": "^1.0.6",  "vant": "^4.9.6", 最终下载的版本是"@vant/nuxt@^1.0.6":
  version "1.0.6"

**Comment by inottn** [comment]
这个问题应该修复了，你可以使用 Vant 的最新尝试一下。

**Comment by amshiro** [comment]
> 这个问题应该修复了，你可以使用 Vant 的最新版本尝试一下。

哇哦，谢谢你哦，真的哎哈哈哈哈哈 "vant": "^4.9.10", 完美～～～～～
