### ISSUE TITLE
Sku 样式出现bug

### ISSUE THREAD

**Issue by GodStream** [youzan/vant#1327]
**Describe the bug**
商品缩略图超出部分，被截断

**Screenshots**
![image](https://user-images.githubusercontent.com/23089466/41828495-15e78260-7868-11e8-91a2-3df08ff6e1c9.png)

.van-popup 的 overflow-y: auto 影响了样式

**Environment**
 - Browser: chrome
 - Vant Version: 1.1.9

**Reproduce**
文档就可以复现

**Comment by chenjiahan** [comment]
感谢反馈，下个版本修复此问题

**Comment by ccbox** [comment]
临时解决办法：
.van-sku-container {overflow-y: inherit;}

**Comment by chenjiahan** [comment]
已在 1.1.10 版本修复此问题
