### ISSUE TITLE
Uploader 文件上传，上传前置处理的函数返回值为true时，没有往下执行

### ISSUE THREAD

**Issue by canger123** [youzan/vant#13283]
### 重现链接

https://github.com/canger123/vant-bug

### Vant 版本

4.9.4

### 描述一下你遇到的问题。

Uploader 文件上传，在上传前置处理的函数（before-read）当中进行二次确认弹窗，返回的值为Promise时，resolve(true）不会继续执行（after-read），而是需要resolve(false）才可以

### 重现步骤

1.设置resolve(true）
2.点击文件上传
3.选择文件，
4.点击确认弹窗，
5.设置resolve(tfalse）
6.点击文件上传
7.选择文件，
8.点击确认弹窗，

### 设备/浏览器

PC和手机都可以重现

**Comment by inottn** [comment]
参考文档示例部分，resolve 接收的参数应该是 File（或者不传参数），而不是 boolean。需要中断上传的话，可以调用 reject。

**Comment by inottn** [comment]
不过文档 API 部分的描述可以更清楚一些，如果感兴趣的话，欢迎 PR。
