### ISSUE TITLE
Android Chrome里绝对定位组件(van-goods-action,van-tabbar)触摸位置发生偏移

### ISSUE THREAD

**Issue by ansonhorse** [youzan/vant#1328]
**Describe the bug**
RT，在Android Google Chrome 里，可能会出现这个奇怪的问题。

暂时只在Android的Google Chrome上发现。

> 在某种情况下，绝对定位的元素触摸不到，详细点说，就是在视觉上是触摸这个元素，但实际上是触摸到了另一个地方。

至于这个"某种情况"，暂时没有确定，也就是这个问题的重现方式我暂时也说不定。这个大致给一些操作逻辑，但不确保可以触发：
1. 快速滑动到底部，再向上滑动一段距离；
2. 随意上下滑动；
3. 在滑动之前附带一些随机触摸操作；

[查看视频](https://github.com/ansonhorse/vant-touch-skewing/raw/master/screenshots/2018-06-25_12_02_54.mp4)

**Screenshots**
请看我创建的重现项目
https://github.com/ansonhorse/vant-touch-skewing

**Environment**
 - Device: Android 360 N6 Pro
 - Browser: Chrome 67.0.3396.87
 - Vant Version: 1.1.9

**Reproduce**
https://github.com/ansonhorse/vant-touch-skewing

**Comment by ansonhorse** [comment]
@chuangbo 写了一个不引用其他东西的示例，发现也有这个问题，这可能是Chrome的bug。
不过如果有空的话，还是请看一下，谢谢！

**Comment by ansonhorse** [comment]
在一台旧机器上(红米Note3)，也有这个问题😳

**Comment by ansonhorse** [comment]
已确认是新版Chrome for Android的bug，跟Vant无关

**Comment by chenjiahan** [comment]
没有遇到过这个问题噢，如果是 Chrome 的问题，我们这边应该也没有什么解决方法
