### ISSUE TITLE
Vant is not defined

### ISSUE THREAD

**Issue by Pamki** [youzan/vant#1330]
vue项目，引入vant报错Vant is not defined

如题，按照官网文档导入所有组件

import Vue from 'vue';
import Vant from 'vant';
import 'vant/lib/vant-css/index.css';

Vue.use(Vant)

控制台报错Vant is not defined

**Comment by fightingFan** [comment]
npm i vant -S

**Comment by fisher7757** [comment]
先执行：vue init youzan/vue-cli-template-vant my-project
再执行：cd  my-project
再执行：npm i vant -S
再执行：npm install
再执行：npm run dev
最后引用
import Vue from 'vue';
import Vant from 'vant';
import 'vant/lib/vant-css/index.css';

Vue.use(Vant);

仍然提示**Vant is not defined**
