### ISSUE TITLE
折叠面板问题不能动态循环数据后指定打开某一项面板

### ISSUE THREAD

**Issue by tan2009216028** [youzan/vant#1335]
**Describe the bug**
折叠面板问题不能动态循环数据后指定打开某一项面板，判定name这个key有问题，不能动态赋值，示例代码如下

        <van-collapse v-model="active" @change="onClick">
            <van-collapse-item v-for="(item, index) in data" :title="item.title" :key="index" :name="index">
                    <van-cell v-for="(cell, number) in item.data" :key="number" :title="cell.title" :value="cell.value" />
            </van-collapse-item>
        </van-collapse>

期望看看，另外官方的有赞小秘书没反应，不能加入你们讨论组，没法直接反馈问题

**Comment by chenjiahan** [comment]
没复现这个问题，请确认下你绑定的 v-model 是否正确，比如你要默认打开第一、二项，v-model 传 `[0, 1]` 就行

**Comment by chenjiahan** [comment]
PS 小秘书的账号可能回复不是那么及时，我们会定期处理~
