### ISSUE TITLE
line-width支持根据标题宽度自适应

### ISSUE THREAD

**Issue by jackyon** [youzan/vant#1339]
**请问什么时候支持动态根据标题的长短进行宽度自适应？*
例如我的tabar:

标题1    标题2一般长    标题3特别长特别长

假如用line-width的话，目前好像只能是固定的。

**Comment by chenjiahan** [comment]
暂无计划支持噢

**Comment by ziv0210** [comment]
可以通过长度乘以子的fontsize 
:line-width="tabName.length * 15"
