### ISSUE TITLE
关于Lazyload的使用文档是否有不恰当的地方

### ISSUE THREAD

**Issue by xuejiangjun** [youzan/vant#1340]
文档地址：[lazyload](https://youzan.github.io/vant/#/zh-CN/lazyload)
使用指南中说到Lazyload是Vue指令，所以需要使用它必须将它注册到Vue的指令中。

> import Vue from 'vue';
import { Lazyload } from 'vant';
Vue.use(Lazyload, options);

这里是不是应该是说Lazyload是<del>Vue</del>**Vant**指令,然后注册的应该是
> Vue.use(vant.Lazyload)

如有错误恳请指正。

**Comment by chenjiahan** [comment]
这里表达可能有点歧义，正确的说法是 `Lazyload 是 Vue 指令，使用前需要对指令进行注册。`

另外注册的写法是没有问题的，`Vue.use(vant.Lazyload)` 这个是 CDN 引入的写法

**Comment by chenjiahan** [comment]
文档已更新
