### ISSUE TITLE
tabs+list的BUG

### ISSUE THREAD

**Issue by shiyuegongsui** [youzan/vant#1342]
**Describe the bug**
`
<van-tabs v-model="active">
  <van-tab  title="'选项1">
      <van-list></van-list>
  </van-tab>
  <van-tab  title="'选项2">
      <van-list></van-list>
  </van-tab>
</van-tabs>
`

我的结构类似上面这样子，选项卡都切换一遍，无论最终停留到那个tab下，滚动到最底部，所有的tab里面的van-list的上拉加载都会执行。

**Comment by 112297720** [comment]
我也遇见相同的问题，1个页面多个van-list就冲突，互相影响。

**Comment by chenjiahan** [comment]
确实有这个问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 1.1.10 版本修复

**Comment by shiyuegongsui** [comment]
@Fanaiwen  1.1.10版本才修复的。亲测可以啦。

**Comment by lkoma** [comment]
> @Fanaiwen 1.1.10版本才修复的。亲测可以啦。
@shiyuegongsui   1.1.11版本还是这样，还是几个tab同时滚动。请问是我用的问题吗？

**Comment by YuBilai** [comment]
为什么我的2.0.8的也是不行呢？是我们的使用姿势不对吗？当第一个tab上拉加载了物业之后，切换到第二个tab的时候立马页面就加载5页数据、

**Comment by gikeihi** [comment]
van-tab之间为啥滚动要互相影响？
