### ISSUE TITLE
Stepper 的事件如何传递参数？

### ISSUE THREAD

**Issue by mal5338** [youzan/vant#1346]
在步进器的事件中想要传递参数，但获取到的参数是event，请问如何处理？
这是<template>里的代码：
```
<van-stepper 
    v-show="wear.wearNum>0" 
    v-model="wear.wearNum" 
    min="0" 
    @minus="decreaseCart()" 
    @plus='addCart(wear)' />
```

这是methods的代码：
```
addCart(event,currentWear) {
  if (!event._constructed) {
    return;
  }
  console.log(currentWear);  // 输出undefined
  this.$store.commit({
    type: 'wears/addCart',
    currentWear
  });
},
decreaseCart(event,currentWear) {
  if (!event._constructed) {
    return;
  }
  console.log(currentWear);   // 输出undefined
  this.$store.commit({
    type: 'wears/decreaseCart',
    currentWear
  });
}
```

**Comment by chenjiahan** [comment]
参见 https://cn.vuejs.org/v2/guide/events.html#%E5%86%85%E8%81%94%E5%A4%84%E7%90%86%E5%99%A8%E4%B8%AD%E7%9A%84%E6%96%B9%E6%B3%95

**Comment by mal5338** [comment]
在<template>中增加参数的接收
<img width="979" alt="image" src="https://user-images.githubusercontent.com/5944407/42069902-ca4c288e-7b86-11e8-8744-19603a7fae6f.png">

在methods里输出参数
<img width="192" alt="image" src="https://user-images.githubusercontent.com/5944407/42069974-087f39a2-7b87-11e8-8668-53d25613ff89.png">

但是输出的却是
<img width="760" alt="image" src="https://user-images.githubusercontent.com/5944407/42069995-2039808e-7b87-11e8-928d-7bb6e072124b.png">

**Comment by mal5338** [comment]
传多个参数的话，第一个参数获取的一直是Event对象，后面的参数输出都是undefined @chenjiahan
