### ISSUE TITLE
建议丰富form表单控件和布局

### ISSUE THREAD

**Issue by tiankejun** [youzan/vant#1348]
1、希望添加 select控件，以及二级、三级联动
2、在form表单布局能够在丰富点，比如左边title，右边select框或其他控件的布局
3、在alert的时候希望添加关闭事件

**Comment by chenjiahan** [comment]
1. 移动端一般很少使用 Select ，可以用 Picker 组件
2. 下个版本会支持 title 和 input 的对齐控制
3. 不知道你说的 alert 是啥
