### ISSUE TITLE
<van-field label="用户名" v-model="value" placeholder="请输入用户名" /> 怎么设置input内容右对齐

### ISSUE THREAD

**Issue by fightingFan** [youzan/vant#1351]
<van-field label="用户名" v-model="value" placeholder="请输入用户名" /> 
中怎么设置input内容右对齐

**Comment by tiankejun** [comment]
有赞没有设置文本框里面内容，以及外面lable 对齐的属性

**Comment by chenjiahan** [comment]
下个版本支持

**Comment by chenjiahan** [comment]
已在 1.1.10 版本增加 `label-align` 和 `input-align` 属性

**Comment by fightingFan** [comment]
辛苦。
