### ISSUE TITLE
Toast success / fail / loading 没有图标显示

### ISSUE THREAD

**Issue by grapewheel** [youzan/vant#1355]
**Describe the bug**
vue2使用babel-plugin-import方式调用vant，页面import Toast模块，调用Toast.loading Toast.success Toast.fail 都能调起提示，但就是没有了图标，即使在App.vue里import vant 的 icon-local.css 也没用

**Screenshots**
![here](https://user-images.githubusercontent.com/490426/42036877-653fee5c-7b19-11e8-9416-6654cabf47af.png)

**Environment**
 - Device: pc和手机
 - Browser: 所有现代浏览器
 - Vant Version: 1.1.10

**Comment by chenjiahan** [comment]
没能复现这个问题，能否提供一个复现的 jsfiddle 或仓库

**Comment by ysjlovecode** [comment]
看一下network，可能是网络问题，没有获取到对应的icon
