### ISSUE TITLE
滚动出现顶部返回调的功能

### ISSUE THREAD

**Issue by BIGTURKEY** [youzan/vant#1358]
![image](https://user-images.githubusercontent.com/19204717/42070063-57f79d1c-7b87-11e8-97bf-8e43335f4d5d.png)
![image](https://user-images.githubusercontent.com/19204717/42070070-601c7e4a-7b87-11e8-8b2f-2e39166359e4.png)
就是淘宝的这种详情页，一滚动内容就会出现这样的顶部返回，不知道vant目前是否有类似的功能，有的话能否告知我是哪个组件，没有的话建议可以添加此功能，谢谢，如果我描述的没看明白，可以打开淘宝天猫京东这些app的商品详情页参考下，麻烦了

**Comment by chenjiahan** [comment]
Vant 里目前没有这样的功能，暂时没有计划在组件内集成
如果需要的话，可以自己在组件外部监听 scroll 事件，然后设置 opacity
