### ISSUE TITLE
Area 使用change 获取Picker 实例错误

### ISSUE THREAD

**Issue by 18510758841** [youzan/vant#1362]
```html
<van-popup v-model="show" position="bottom">
        <van-area
          :area-list="areaList"
          title="标题"
          @change="selectCity"
          @confirm="onAreaConfirm"
          @cancel="showAreaSelect=false"
          :loading="loading"
        />
      </van-popup>
```

```js
 import {Cell, CellGroup, Popup, Toast, Area, Field} from 'vant';
  import Api from '../api/register'
data() {
      return {
        title: 'adsasd',
        loading: false,
        show: false,
        areaList: {
          province_list: {},
          city_list: {},
          county_list: {}
        }
      }
    },
  methods: {
      pop() {
        this.show = true;
        this.loading = true
        let data = {
          userId: 'UCP151565464174200001',
          token: '1',
          client: 1,
        };
        Api.getCityList(data).then((data) => {
          if (data) {
            this.loading = false
          }
          let res = data.data;
          let tmp = {};
          for (let i = 0; i < res.length; i++) {
            tmp[res[i].citycode] = res[i].cityname;
          }
          this.areaList.province_list = tmp;
          console.log(this.areaList.province_list)
        })

      },
      selectCity(picker, values,index) {
        console.log(222);
        this.loading = true;
        let data = {
          userId: 'UCP151565464174200001',
          token: '1',
          client: 1,
          citycode:values[0].code
        };
        Api.getCityList(data).then((data) => {
          if (data) {
            this.loading = false
          }
          let res = data.data;
          let cityName = {};
          for (let i = 0; i < res.length; i++) {
            cityName[res[i].citycode] = res[i].cityname;
          }
          console.log(cityName)
          picker.setColumnValues(index+1, cityName)
        // this.areaList. city_list= tmp;        这里为什么不能这写？
        })
      },
```
在 1.1.5的版本中 滑动 省 获取code 可以渲染处 市的列表，如果在市的列表上面change事件触发的话返回code为nudefin,2018.6.29 升级版本到 "vant": "^1.1.10",  直接绑定change事件直接报错如下

vue.esm.js?efeb:591 [Vue warn]: Error in event handler for "change": "TypeError: Cannot read property 'code' of undefined"

found in

---> <VanPicker>
       <VanArea>
         <VanPopup>
           <QuickPayment> at src/page/quickPayment.vue
             <App> at src/App.vue
               <Root>
warn @ vue.esm.js?efeb:591
logError @ vue.esm.js?efeb:1737
globalHandleError @ vue.esm.js?efeb:1732
handleError @ vue.esm.js?efeb:1721
Vue.$emit @ vue.esm.js?efeb:2540
onChange @ index.js?a961:98
change @ index.js?a961:16
invoker @ vue.esm.js?efeb:2027
Vue.$emit @ vue.esm.js?efeb:2538
setIndex @ PickerColumn.js?367a:137
onTouchEnd @ PickerColumn.js?367a:113
invoker @ vue.esm.js?efeb:2027
fn._withTask.fn._withTask @ vue.esm.js?efeb:1826
vue.esm.js?efeb:1741 TypeError: Cannot read property 'code' of undefined
    at VueComponent.onChange (index.js?8938:114)
    at VueComponent.invoker (vue.esm.js?efeb:2027)
    at VueComponent.Vue.$emit (vue.esm.js?efeb:2538)
    at VueComponent.onChange (index.js?a961:98)
    at change (index.js?a961:16)
    at VueComponent.invoker (vue.esm.js?efeb:2027)
    at VueComponent.Vue.$emit (vue.esm.js?efeb:2538)
    at VueComponent.setIndex (PickerColumn.js?367a:137)
    at VueComponent.onTouchEnd (PickerColumn.js?367a:113)
    at invoker (vue.esm.js?efeb:2027)

我的change事件里面只是打印了个console.log('1');并没有写东西

**Comment by chenjiahan** [comment]
下个版本会修复报错的问题，同时支持直接修改 city_list 后触发渲染

**Comment by chenjiahan** [comment]
已经在 1.1.11 版本中修复

**Comment by chengqiang1992** [comment]
非常感谢

**Comment by chengqiang1992** [comment]
你好，之前我的问题麻烦你们了。现在可以用了。不过又有一个小问题：
```HTML
<popup v-model="showAreaSelect" position="bottom">
    <van-area
        ref="area"
        :value="addressInfo.area_code"
        :area-list="areaList"
        @change="selectCity"
        @confirm="onAreaConfirm"
        @cancel="showAreaSelect = false"
        />
    </popup>
```
如果市是直辖市如北京、天津、上海等，如下，不会触发 onChange 事件：
![](http://ww1.sinaimg.cn/large/006nn93Fgy1ft4rfexd98j30ko0egmxw.jpg)

**Comment by chenjiahan** [comment]
@chengqiang1992 这个问题可以单独提一个 issue 喔

**Comment by chengqiang1992** [comment]
@chenjiahan  好的，又要麻烦你了。
