### ISSUE TITLE
Area 组件在未给定初始value时 首次弹出地址信息正常 当滑动省列右侧数据乱码

### ISSUE THREAD

**Issue by LucaMK** [youzan/vant#1363]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Area 组件在未给定初始value时 首次弹出地址信息正常 当滑动省列右侧数据乱码 **

点击按钮 弹出 选择省市区地址选择框  此次为正常显示，
此时 滑动左侧省 列表 右侧 市区 或者其一 数据变成 对象数据 而非相应的名称，
但是当绑定默认 地区value 后 就显示正常 。
虽然不是特别大bug 但是文档并没有提示必须添加默认value

Click the button to pop up. Select the provincial address selection box. This time is normal display.
At this point, slide the left province list and then the  right side list what its data becomes object data instead of the corresponding name.
However, it is normal when the default region value is binded.
Although it is not a particularly big bug, the documentation does not prompt you to add a default value.

**Screenshots**
点击按钮弹出
First click button pop ,it is normal
![first](https://user-images.githubusercontent.com/23350291/42084290-d3b4b3d0-7bbf-11e8-9883-b4f63d943711.png)
当滑动左侧 省份列表
After slide left province list
![scroll_after](https://user-images.githubusercontent.com/23350291/42084346-fe29dfbe-7bbf-11e8-8e81-5727c29a8ae2.png)

**Environment**
 - Device:手机 iphone6
 - Browser: 微信浏览器
 - Vant Version: 1.1.9

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by LucaMK** [comment]
在 iphone6手机 微信浏览器中 不传value 选择左侧省份 后 市区变乱码  添加value后 就不会出现乱码
https://jsfiddle.net/dfarLdko/186/

**Comment by chenjiahan** [comment]
试了一下木有复现这个问题
