### ISSUE TITLE
change 获取 picker 时间值错误

### ISSUE THREAD

**Issue by GinsiberDylan** [youzan/vant#1366]
<van-datetime-picker
	v-model="currentDate"
	type="date"
	:min-date="minDate"
	class='vant_datetime_picker'
	@confirm='pickConfirm'
	 @change='getColumnValue'
/>

methods: {
	getColumnValue (e){
		let valArr = e.getValues();
		console.log(valArr)
		this.pickSelectTime = valArr;
	}
}

每次选择月份更改，打印的日期天的值为01；
年份更改或者日期更改不会这个bug;

**Comment by GinsiberDylan** [comment]
getColumnValue 和 getColumnValue 都会发生这个bug

**Comment by chenjiahan** [comment]
确实有这个问题，下个版本会修复

**Comment by chenjiahan** [comment]
已经在 1.1.11 版本中修复
