### ISSUE TITLE
希望SwitchCell组件可以自定义size

### ISSUE THREAD

**Issue by munimrwu** [youzan/vant#1368]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
`<1.1.10` SwitchCell组件不支持自定义size，默认的高度与 **Cell组件** 的高度不一致

**Describe the solution you'd like**
希望SwitchCell组件可以自定义size

**What does the proposed API look like?**
参数|说明|类型|默认值
-----|-----|-----|-----
size|开关尺寸|`String`|`30px`

![44](https://user-images.githubusercontent.com/33760888/42129672-430a7c80-7cfe-11e8-8b9a-4065e2380ef7.png)

![52](https://user-images.githubusercontent.com/33760888/42129678-4bc6a98e-7cfe-11e8-9d1d-d866904a3213.png)

![46](https://user-images.githubusercontent.com/33760888/42129680-51684780-7cfe-11e8-8771-63197209c811.png)

**Comment by chenjiahan** [comment]
下个版本会支持，同时 SwitchCell 的默认高度会和 Cell 保持一致，这样比较合理

**Comment by munimrwu** [comment]
感谢开源！

**Comment by chenjiahan** [comment]
已经在 1.1.11 版本中支持
