### ISSUE TITLE
希望Field组件添加验证码图片

### ISSUE THREAD

**Issue by munimrwu** [youzan/vant#1369]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
![111](https://user-images.githubusercontent.com/33760888/42129718-a7b11f12-7cff-11e8-91a8-f8dea02b40f0.png)
图片来自 [Mint UI](http://elemefe.github.io/mint-ui/#/field)

**Describe the solution you'd like**
希望Field组件添加验证码图片

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
暂无计划支持，可以通过 slot=button 插入自定义内容
