### ISSUE TITLE
关于单、复选框组件API的小建议

### ISSUE THREAD

**Issue by munimrwu** [youzan/vant#1373]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
![225](https://user-images.githubusercontent.com/33760888/42129987-a53e619c-7d07-11e8-8138-2c6c46c5fc80.png)

**Describe the solution you'd like**
上图中手误应该是 `slot`, 或者可以参考 [muse-ui](https://muse-ui.org/#/zh-CN/select-control) 的方案。

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
下个版本会强化 checkbox  的定制性

**Comment by chenjiahan** [comment]
1.1.11 版本已支持 label-position

**Comment by chenjiahan** [comment]
下个版本会支持自定义图标

**Comment by chenjiahan** [comment]
已在 1.1.12 版本支持

**Comment by munimrwu** [comment]
感谢采纳，
建议单选也添加同样的功能，API的一致性更有利于项目的发展。
另外问一下下，有赞助项目的方式吗？

**Comment by chenjiahan** [comment]
嗯，后续会让 Radio 也支持对应的 API
目前没有赞助方式喔，提 issue 和 PR 就是最好的支持^_^
