### ISSUE TITLE
1.1.10版本Area组件遇到的问题

### ISSUE THREAD

**Issue by 18510758841** [youzan/vant#1376]
![image](https://user-images.githubusercontent.com/23565370/42131302-f8b90d02-7d31-11e8-9448-c98659f29a8f.png)
首先这是我的view 
点击按钮触发pop层弹起，获取数据的格式为
![image](https://user-images.githubusercontent.com/23565370/42131314-2ed9ea82-7d32-11e8-8fec-b3e7060bbf2c.png)
**然后转化为官方文档格式为**
![image](https://user-images.githubusercontent.com/23565370/42131325-6a0b4830-7d32-11e8-821e-794ade5f7058.png)
### ok,sheng省级列表完美的展示出来了
![image](https://user-images.githubusercontent.com/23565370/42131328-7d418086-7d32-11e8-8002-05db1f17eb9b.png)
触发change事件直接报错
![image](https://user-images.githubusercontent.com/23565370/42131383-95da00b8-7d33-11e8-87d7-4c826654e3ac.png)

**Comment by 18510758841** [comment]
报错原因为
![image](https://user-images.githubusercontent.com/23565370/42131392-bd8e4114-7d33-11e8-8bbf-0a1aff0fa98f.png)

**Comment by chenjiahan** [comment]
重复 issue https://github.com/youzan/vant/issues/1362
