### ISSUE TITLE
建议 Dialog 高级用法中增加 api 点击按钮不关闭弹窗

### ISSUE THREAD

**Issue by GinsiberDylan** [youzan/vant#1377]
https://youzan.github.io/vant/#/zh-CN/dialog 高级用法

在点击确认时，想请求校验 input 输入后的值的正确性，正确时才关闭弹窗，但是点击确认就关闭弹窗了；

建议在可以增加个API，点击按钮不要关闭弹窗；

图片上传老是失败.....

**Comment by Fyerl** [comment]
关于 beforeClose 文档可能是没有补充详细，可以在校验错误的时候可以对 done 传参 false，来使其结束 loading 且不关闭
```javascript
beforeClose(action, done) {
  if (action === 'confirm') {
    setTimeout(function() {
      done(false);
    }, 1000);
  } else {
    done();
  }
}
```

**Comment by chenjiahan** [comment]
后续会完善文档

**Comment by chenjiahan** [comment]
文档已更新
