### ISSUE TITLE
area组件现在省市二级选择时，无法只选择省了，之前选择省份不选择市会返回省份 现在怎么就默认直接返回默认市了

### ISSUE THREAD

**Issue by Fanaiwen** [youzan/vant#1378]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
area组件现在省市二级选择时，无法只选择省了，之前选择省份不选择市会返回省份 现在怎么就默认直接返回默认市了

**Describe the solution you'd like**
之前版本的不是很好吗，area选中省份不选择市，市一栏默认的是选择城市，这样就可以筛选全省数据了，新的版本直接导致这种功能丧失啊。。。

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
不是很懂你的需求，只选择省的话，可以设置 columnNum

**Comment by Fanaiwen** [comment]
![_20180711111848](https://user-images.githubusercontent.com/37430039/42548942-3e4d3a60-84fc-11e8-9478-1245de5a7109.png)
这样子，在选择省，市 的时候，我在选择省后，以前会有一个 “选择省份”排在市一列顶部，而现在没有了，会默认选择第一个市，这样的话 我想做省份一及的筛选就不好做了。
我还是觉得以前的版本gen更合理啊
