### ISSUE TITLE
希望添加一个是否现在底部显示按钮的属性与bottom-action 属性区分开

### ISSUE THREAD

**Issue by tiankejun** [youzan/vant#1379]
button组件中有 bottom-action	属性，以下是描述
“bottom-action	是否为底部行动按钮	Boolean	false”

个人觉得对这个描述不是是很清楚，期初，我以为加上 bottom-action 这个属性是让按钮在页面底部显示，其实只是让按钮显示成底部按钮的样式
希望添加一个属性，让这个按钮是否显示在底部，与bottom-action 这个属性区分开

**Comment by chenjiahan** [comment]
bottom-action 这个命名确实比较奇怪，后续会在大版本中改掉
另外暂无计划增加属性让按钮显示在底部
