### ISSUE TITLE
使用Field组件报莫名其妙的错，无法处理，是与其他ui冲突了吗？

### ISSUE THREAD

**Issue by yuxiaoxiong** [youzan/vant#1382]
[Vue warn]: Error in render function: "TypeError: Cannot read property 'disabled' of undefined"

found in

---> <VanField>
       <VanCellGroup>

代码
”<van-field v-model="value" placeholder="请输入用户名" />”
<script type="text/javascript">
  export default {
    data () {
      return {
        value: ''
      }
    }
  }
</script>

main.js引入
import { Area, Cell, CellGroup, Field } from 'vant'
Vue.use(Area).use(Cell).use(CellGroup).use(Field)

但是其他组件可以正常使用

**Comment by yuxiaoxiong** [comment]
前端代码<van-cell-group>
      <van-field v-model="value" placeholder="请输入用户名" />
    </van-cell-group>

**Comment by chenjiahan** [comment]
依赖 Vue >= 2.4.0 版本
