### ISSUE TITLE
希望内置样式添加左右滑动

### ISSUE THREAD

**Issue by munimrwu** [youzan/vant#1384]
已有的内置样式中1px边框，淡入动画等都很实用，省了兼容Retina和Animate，希望再添加一个左右滑动的功能，基本的滑动前进和滑动后退也用的比较多，[vue-touch](https://github.com/vuejs/vue-touch/tree/next)会直接在行内加上`touch-action: none; user-select: none;`禁用默认的滑动，虽然可以解决这个问题但还是比较麻烦，而且也很久没更新了。看了下源码里的[touch.js](https://github.com/youzan/vant/blob/dev/packages/mixins/touch.js)可以很容易的抽离出来，这样就不需要用户手动import这个文件了。

**Comment by chenjiahan** [comment]
不是很清楚你具体要的是什么东东

**Comment by munimrwu** [comment]
可以关闭这个 Issue 了，
通过 `Swipe` 可以实现，只是代码有些冗余，但是考虑到组件库的轻量化，还是不要添加差异比较小的组件了。

**Comment by chenjiahan** [comment]
了解了~
