### ISSUE TITLE
Picker配合Field使用弹出键盘

### ISSUE THREAD

**Issue by weihongyu12** [youzan/vant#1385]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
也许我这个并不是个bug，但是我实在是找不到解决办法。在Picker配合Field使用的时候，在手机上总是会弹出系统键盘，这个应该如何解决？

Maybe this is not a bug, but I really can't find a solution. When the Picker is used with the Field, the system keyboard will always pop up on the phone. How should this be solved?

**Screenshots**
![image](https://user-images.githubusercontent.com/19792747/42197015-68956ed6-7eb3-11e8-8687-1e810f1d3692.png)
![image](https://user-images.githubusercontent.com/19792747/42197030-7450af42-7eb3-11e8-8d62-5b569c0cddcb.png)

**Environment**
 - Device: iPhone 7/iOS 11.4
 - Browser: weixin
 - Vant Version: 1.1.10

**Reproduce**
```vue
<template>
  <div>
    <div class="cell-group">
      <van-cell-group>
        <van-field
          label="最高学历"
          @focus="show = true"
          @blur="show = false"/>
      </van-cell-group>
    </div>
    <div  v-if="show">
      <van-picker :columns="columns"/>
    </div>
  </div>
</template>

<script>
import Vue from 'vue';
import { Toast } from 'vant';

const BasePicker = () => import('@/components/base-picker.vue');
const DatetimePicker = () => import('@/components/datetime-picker.vue');

export default Vue.extend({
  data() {
    return {
      columns: ['初中及以下', '中专', '高中', '大专', '本科', '研究生及以上'],
      show: false,
    };
  },
});
</script>
```

**Comment by chenjiahan** [comment]
可以使用 `readonly` 属性
