### ISSUE TITLE
更新版本1.1.10后lazyLoad报错

### ISSUE THREAD

**Issue by HowardTangHw** [youzan/vant#1386]
![image](https://user-images.githubusercontent.com/22932158/42199043-8f419aea-7ebe-11e8-96a0-e52af96b5831.png)

还原版本1.1.9后就没有问题了

**Comment by chenjiahan** [comment]
可以重装 node_modules 试试

**Comment by HowardTangHw** [comment]
@chenjiahan 重装了,我和另一个同事的电脑都出现这种情况,只有固定了版本为1.1.9的情况下才不会报错
