### ISSUE TITLE
关于 picker 选择器的建议

### ISSUE THREAD

**Issue by tiankejun** [youzan/vant#1387]
picker 选择器渲染数据是通过一个数来渲染选项的，如下：

columns | 对象数组，配置每一列显示的数据 | Array | [ ]

希望改进成键值对的形式，类似于下拉框，有的业务场景确实需要显示的值与给后台传送的值不一样，

**Comment by chenjiahan** [comment]
支持键值对的，具体看文档

**Comment by androidxu** [comment]
> 支持键值对的，具体看文档

我查看了下，没有发现支撑键值对的，能否明示下，谢谢！

**Comment by tiankejun** [comment]
@androidxu  如下：
value-key | 选项对象中，文字对应的 key
columns: [{lable: '西安', value: '1'}, {lable: '长安', value: '2'}]

<van-field
  readonly
  clickable
  label="城市"
  :value="columns"
  value-key=“lable”
  placeholder="选择城市"
  @click="showPicker = true"
/>

**Comment by androidxu** [comment]
> @androidxu 如下：
> value-key | 选项对象中，文字对应的 key
> columns: [{lable: '西安', value: '1'}, {lable: '长安', value: '2'}]
> 
> <van-field
> readonly
> clickable
> label="城市"
> :value="columns"
> value-key=“lable”
> placeholder="选择城市"
> @click="showPicker = true"
> />
多谢~

**Comment by zjjjjjjjjjjd** [comment]
> > @androidxu 如下：
> > value-key | 选项对象中，文字对应的 key
> > columns: [{lable: '西安', value: '1'}, {lable: '长安', value: '2'}]
> > <van-field
> > readonly
> > clickable
> > label="城市"
> > :value="columns"
> > value-key=“lable”
> > placeholder="选择城市"
> > @click="showPicker = true"
> > />
> > 多谢~

没啥用吧，confirm返回的还是label，压根没value啥事，这里应该设计成confirm返回整个对象才对
