### ISSUE TITLE
Field组件type设置为number，ios中文全键盘，联想的中文可以输入

### ISSUE THREAD

**Issue by wjq7712** [youzan/vant#1389]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**

Field组件type设置为number，ios中文全键盘的时候，虽然不能输入非数字字符，但是输入法联想的中文可以选中并显示在输入框中。如图。

![0](https://user-images.githubusercontent.com/5425465/42203803-7f2367c4-7ed2-11e8-9ca7-c179d18c62e6.png)

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
无法解决
