### ISSUE TITLE
pull-refresh 下拉成功后如何关闭加载，给的例子关闭不了

### ISSUE THREAD

**Issue by Obacm** [youzan/vant#139]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by badlq** [comment]
onRefresh中延时0.5秒
