### ISSUE TITLE
上拉菜单无法显示

### ISSUE THREAD

**Issue by lanhaiyou** [youzan/vant#1390]
main.js里
import { Actionsheet } from 'vant';
Vue.use(Actionsheet);

然后component里按照开发文档
<van-actionsheet v-model="show" :actions="actions" />
script也是照着开发文档直接复制的。
然而上拉菜单没有出现
请问是还需要配置什么吗

**Comment by chenjiahan** [comment]
不规范的 issue
ps: 可以看下是否正确引入样式，是否配置了 babel-plugin-import

**Comment by lanhaiyou** [comment]
抱歉，我不太熟悉这上面的发帖规则
开始我为了方便用的是用引入所有组件的方式，用到的所有组件中只有上拉菜单是显示不出来的

现在，我换到配置 babel-plugin-import的方式
这次我是在main.js里将用到的组件一个个Import进来，然后，标签组件又不行了。。。
我在main.js配置了以下两句：
import { Tabbar, TabbarItem } from 'vant'
Vue.use(Tabbar).use(TabbarItem);
所有用到标签栏的页面都报了这个组件没定义

其他组件也是一样的方法在main.js中引入，它们并没有报错。不知道什么情况了。。。
