### ISSUE TITLE
在 typescript 下使用遇到 vscode 提示类型不正确

### ISSUE THREAD

**Issue by SilenceM** [youzan/vant#1397]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
在 typescript 下引入用了 ts-import-plugin
vscode 会报如下图的错误。
**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/20535309/42253100-b26324d0-7f72-11e8-8963-9c10592ddbe2.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
请问这个问题是引入 ts-import-plugin 才导致的，还是在 TS 下普遍存在的？

**Comment by chenjiahan** [comment]
已在 1.1.12 版本优化
