### ISSUE TITLE
Field标签输入框 全局注册后 在子组件里显示van-cell-group未注册

### ISSUE THREAD

**Issue by pk110** [youzan/vant#1400]

**Comment by pk110** [comment]
![_20180704131543](https://user-images.githubusercontent.com/26643078/42258064-6be7550c-7f8c-11e8-83aa-cd75144920c6.png)
![_20180704131552](https://user-images.githubusercontent.com/26643078/42258066-6f035b3c-7f8c-11e8-9961-e69d84f982f1.png)
![_20180704131556](https://user-images.githubusercontent.com/26643078/42258067-71491fbc-7f8c-11e8-9a8c-50b3b574b337.png)

**Comment by LynanBreeze** [comment]
van-cell-group也是一个组件，需要引入的，你可以在组件内引入使用或者全局引入使用
