### ISSUE TITLE
定制主题的边框色，修改的应当是$border-color，而不是$gray-light

### ISSUE THREAD

**Issue by qidaneix** [youzan/vant#1401]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在vant@1.1.5中，使用文档介绍的[定制主题](https://youzan.github.io/vant/#/zh-CN/theme)的方法（方案一. PostCSS 插件）修改主题，发现修改组件的边框的颜色不是通过`$border-color`属性修改，而是通过`$gray-light`属性修改。不是很合理。

**Screenshots**
![1adacd85e8089041a9fc75d2f785110f](https://user-images.githubusercontent.com/13130795/42257826-1295235e-7f8b-11e8-8b73-022051cc4f7c.png)

**Environment**
 - Device: windows 7
 - Browser: chrome
 - Vant Version: 1.1.5

**Reproduce**
run on webpack, sorry for no reproduce

**Comment by chenjiahan** [comment]
已在 1.1.12 版本优化
