### ISSUE TITLE
请问DatetimePicker的类型为datetime的时候，如何设置默认时间？

### ISSUE THREAD

**Issue by Mikasa33** [youzan/vant#1403]
**Describe the bug**
请问 DatetimePicker 的类型为 datetime 的时候，如何设置默认时间？
我看到最后一个选择时间的例子中 currentDate: '12:00' ，于是 DatetimePicker 中默认时间就从12开始，而不是 min-hour="10" 开始，但是换成 datetime 类型的时候就不知道如何书写了

**Screenshots**
![image](https://user-images.githubusercontent.com/29498153/42258195-14e3ca0a-7f8d-11e8-9056-b50eb9a0ab26.png)

**Comment by chenjiahan** [comment]
```js
currentDate: new Date(2019, 10, 1)
```

**Comment by Mikasa33** [comment]
这样写，DatetimePicker 中默认还是会显示 2018 01 01 00 00，而不是 2019 10 01 00 00，是我写的有问题吗？
`<van-field v-model="time" />`
`data: { time: new Date(2019, 10, 1), }`
![image](https://user-images.githubusercontent.com/29498153/42316147-ac110eee-807b-11e8-9bbd-52c019a81a55.png)`

**Comment by Mikasa33** [comment]
可以显示默认时间了，非常感谢
