### ISSUE TITLE
vant Area 组件遇到的问题

### ISSUE THREAD

**Issue by 18510758841** [youzan/vant#1404]
首先
![image](https://user-images.githubusercontent.com/23565370/42269148-f692e82e-7faf-11e8-8249-07964a719678.png)
选择开户地点击渲染出第一个市级列表
开始滑动执行change事件

![image](https://user-images.githubusercontent.com/23565370/42269451-c1481c24-7fb0-11e8-8db5-d7a234215e20.png)
![image](https://user-images.githubusercontent.com/23565370/42269610-2b660f4e-7fb1-11e8-8eee-1c4ce3905a9b.png)
![image](https://user-images.githubusercontent.com/23565370/42269753-94a55fe6-7fb1-11e8-9804-354ed6b05d16.png)
确认已经赋值了

**Comment by chenjiahan** [comment]
areaList.city_list 需要有一个初始值，比如 `{}`，还有地区码应该是六位数字
