### ISSUE TITLE
tab组件的sticky属性在ios上会出现短暂消失

### ISSUE THREAD

**Issue by VenusPP** [youzan/vant#1405]
使用tab组件的sticky属性时在安卓手机上滑动正常,在ios下滑动会出现短暂的消失现象,在ios中滑动时只有当滑动停止时才会吸顶容器.这个问题原因是在ios上的"ios scroll event delay" 不知有什么方法解决不,google上给的方法是position：sticky，当直接使用会影响tab组件的其他属性.

**Comment by chenjiahan** [comment]
iOS 的 UIWebview 不会即时触发 scroll 事件，只有用户停止滑动后才会触发。解决方法是升级至 WKWebview
