### ISSUE TITLE
progress当pivot-text设置为空的时候，进度条长度有问题

### ISSUE THREAD

**Issue by miluduo** [youzan/vant#1407]
**Describe the bug**
progress当pivot-text设置为空的时候，进度条长度有问题

**Reproduce**
`<van-progress pivot-text="" percentage="100" />`

**Comment by chenjiahan** [comment]
下个版本优化此问题，当前版本可以把 `show-pivot` 设置成 `false` 来避免这个问题

**Comment by chenjiahan** [comment]
已在 1.1.12 版本优化
