### ISSUE TITLE
npm无法安装 npm WARN vant@0.9.7 requires a peer of vue@2.4.2 but none was installed.  

### ISSUE THREAD

**Issue by gaiai** [youzan/vant#141]
$ npm i vant -S

npm WARN vant@0.9.7 requires a peer of vue@2.4.2 but none was installed.

+ vant@0.9.7
updated 1 package in 5.834s

总是出现这样的提示，没有安装。我的vue全局安装的。

**Comment by chenjiahan** [comment]
@gaiai npm peer dependencies 的提示只是对依赖 Vue 版本的提示，不会影响 vant 正常安装

**Comment by gaiai** [comment]
谢谢
