### ISSUE TITLE
vant-css缺少依赖配置

### ISSUE THREAD

**Issue by if2er** [youzan/vant#1416]
**描述**
主题定制，安装`vant-css`依赖时缺少`fs-extra`和`postcss-calc`包，执行`npm run build`报错如下图：
![image](https://user-images.githubusercontent.com/3774016/42359059-746a4342-8112-11e8-86d6-64e97f56c376.png)

**建议**
建议将依赖加上

**Comment by chenjiahan** [comment]
感谢反馈，已经补齐这几个依赖
