### ISSUE TITLE
van-swipe和van-swipe-item使用，页面内容比较多的情况，可以滚动，当触发了滚动事件的同时也触发左滑或者右滑事件

### ISSUE THREAD

**Issue by CqjGitHub** [youzan/vant#1417]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
van-swipe和van-swipe-item使用，页面内容比较多的情况，可以滚动，当触发了滚动事件的同时也触发左滑或者右滑事件

**Screenshots**
  <van-swipe style="height: 100%; width: 100%"
                 @change="onChange" :show-indicators="false" :loop="false"
                 :initial-swipe="$store.getters.status.currentCount">
        <van-swipe-item v-for="(cardData, index) in allCardData" :key="index">
           <div style="text-align: center; margin-top: 50%;">
             <span style="font-size: 16px; color: #b2b2b2">努力加载中…</span>
           </div>
        </van-swipe-item>
      </van-swipe>

**Environment**
 - Device: 魅蓝note2
 - Browser: 360极速浏览器
 - Vant Version: 1.1.7

**Reproduce**
![z f5 48u lckq7d zr9 nj](https://user-images.githubusercontent.com/7675221/42359375-0a29e6c0-8114-11e8-8167-f8cc6183fc80.png)

**Comment by chenjiahan** [comment]
下个版本优化此问题

**Comment by chenjiahan** [comment]
已在 1.1.12 版本优化
