### ISSUE TITLE
Area 组件显示问题

### ISSUE THREAD

**Issue by SnowZhangXl** [youzan/vant#1419]
**Describe the bug**
Area组件在部分安卓机型上，显示出现异常，内容撑不起高度（44px），会导致选取的和实际显示的内容有差别。

**Screenshots**
安卓部分机型，RN webview。
![screenshot_2018-07-06-11-42-25](https://user-images.githubusercontent.com/30932683/42361368-b61021aa-8120-11e8-97dd-3a85aaf7c2df.jpg)

**Environment**
 - 安卓（中兴）: 
 -webview: 
 - 1.1.11:

**Comment by chenjiahan** [comment]
请问设置 height 能解决这个问题吗

**Comment by SnowZhangXl** [comment]
![image](https://user-images.githubusercontent.com/30932683/42457049-f9ccc182-83c8-11e8-9aea-135bc2e02d33.png)
本地删除这个文件，重新npm test 不会报错。

**Comment by chenjiahan** [comment]
已在 1.1.13 版本修复
