### ISSUE TITLE
Area组件默认第一个选中，再次选择也是第一个选中，

### ISSUE THREAD

**Issue by 18510758841** [youzan/vant#1421]
![image](https://user-images.githubusercontent.com/23565370/42363918-f4f42ab4-812b-11e8-97a9-5828527f7c3d.png)
第一次进来
![image](https://user-images.githubusercontent.com/23565370/42363934-fe3386e2-812b-11e8-9bbb-b7e24e78ce1f.png)
选数据
确定弹框消失
再次进来

**默认选中上次选中的，而我想要选中北京，而不是上次选中的**
我试过清空数据还有使用picker里的方法都没有效果
this.$refs.picker.setColumnValues()
this.$refs.picker.setColumnIndex() 
都没有效果，麻烦写个示列

**Comment by 18510758841** [comment]
Area组件

**Comment by chenjiahan** [comment]
下个版本会加个 reset 方法

**Comment by chenjiahan** [comment]
已在 1.1.12 支持，详见文档

**Comment by 18510758841** [comment]
👌
