### ISSUE TITLE
[bug report] Swipe 多指触控问题

### ISSUE THREAD

**Issue by xuelian0518** [youzan/vant#1422]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
食指中指同时从外往里快速滑动，图片消失，轮播处空白

**Screenshots**
![image](https://user-images.githubusercontent.com/10432354/42365195-5cf54964-8130-11e8-9c48-dbf8a5b45ab2.png)

**Environment**
 - Device: ios
 - Browser: safari
 - Vant Version: v1.1.11

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
请问这个问题是只在图片懒加载上出现，还是普遍现象

**Comment by chenjiahan** [comment]
下个版本修复

**Comment by chenjiahan** [comment]
已在 1.1.13 版本修复
