### ISSUE TITLE
List列表，手动触发onload事件时，当首页数据高度低于屏幕高度时不能继续加载

### ISSUE THREAD

**Issue by klaZzz** [youzan/vant#1423]
Describe the bug
当有筛选条件的时候，点击筛选条件，初始化所有参数并手动触发onload事件，不知道为什么当第一页数据高度低于屏幕高度的时候，就不能继续加载了...是不是我写的有问题,我觉得这不是bug，可能是我写的有问题。求指点... 
![_20180706173611](https://user-images.githubusercontent.com/27330311/42371797-13770c74-8143-11e8-8b30-f039ac1c48d0.png)

**Comment by klaZzz** [comment]
![_20180706174250](https://user-images.githubusercontent.com/27330311/42372117-00b49894-8144-11e8-87a6-39f095396b70.png)
我这么做筛选是不是有问题

**Comment by chenjiahan** [comment]
list 只有触发 scroll 事件的时候才会去加载，建议初始数据内容的长度要超过屏幕高度
