### ISSUE TITLE
swiper纵向滚动不能使用

### ISSUE THREAD

**Issue by huihui-zhou** [youzan/vant#1424]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

纵向滚动下，外部大盒子translateY的值始终为0px
      <van-swipe :autoplay="3000" vertical>
  <van-swipe-item>1</van-swipe-item>
  <van-swipe-item>2</van-swipe-item>
  <van-swipe-item>3</van-swipe-item>
  <van-swipe-item>4</van-swipe-item>
</van-swipe>

![image](https://user-images.githubusercontent.com/30570126/42372227-459bf074-8144-11e8-8eb1-25ec5691645c.png)
纵向滚动下，外部大盒子translateY的值始终为0px

**Comment by chenjiahan** [comment]
不规范的 issue，需要有复现的 jsfiddle
