### ISSUE TITLE
请问框架为什么我全局安装后不能适应移动端。

### ISSUE THREAD

**Issue by gaiai** [youzan/vant#143]
网页拉拽没问题，可一到移动端高分屏就按像素，这个在哪里设置呢？

<img width="557" alt="2017-09-24 8 17 14" src="https://user-images.githubusercontent.com/16616174/30782494-d8acdafe-a0f8-11e7-8887-0c695c123f54.png">

<img width="583" alt="2017-09-24 8 18 56" src="https://user-images.githubusercontent.com/16616174/30782497-e7bf1ee4-a0f8-11e7-9937-eceae23fa0d5.png">

**Comment by chenjiahan** [comment]
@gaiai 不是很明白你的意思，请问你需要的效果是什么样的？

**Comment by gaiai** [comment]
@chenjiahan 就是手机端因为高分屏，会变的很小。

这我的效果
<img width="474" alt="2017-09-24 10 48 14" src="https://user-images.githubusercontent.com/16616174/30783727-89bd6990-a17a-11e7-8677-5a50faa46d80.png">

官方的理想效果：

<img width="356" alt="2017-09-24 10 47 57" src="https://user-images.githubusercontent.com/16616174/30783732-98252414-a17a-11e7-8456-162843487b65.png">

**Comment by chenjiahan** [comment]
@gaiai 这与组件库适配无关，请在你的 HTML 中添加 viewport 设置
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```
