### ISSUE TITLE
List组件 滑动顶部或底部 是否可以加上 bounce 回弹的效果？这样体验是否会更好？

### ISSUE THREAD

**Issue by q759410559** [youzan/vant#1432]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

List组件 滑动顶部或底部 是否可以加上 bounce 回弹的效果？这样体验是否会更好？

**Comment by chenjiahan** [comment]
不计划在组件内加入

**Comment by Airkro** [comment]
IOS和某些安卓系统自带回弹效果，会有不可预知的问题
