### ISSUE TITLE
Tab功能如何自定义每一个tab栏对应的content内容

### ISSUE THREAD

**Issue by lxiaosky** [youzan/vant#1438]
我需要点击每个tab展示不同布局的内容

比如说第一个tab显示的是一个列表
第二个tab显示的是轮播图等等

目前tab的写法是
`<van-tabs v-model="active">
  <van-tab v-for="index in 4" :title="'选项 ' + index">
    内容 {{ index }}
  </van-tab>
</van-tabs>`
而这个内容在所有tab下的布局都是一样的,只是可以动态的改变数据
我希望能改成
`<van-tabs v-model="active">
  <van-tab v-for="index in 4" :title="'选项 ' + index">
      <van-item name='1'>
        内容 {{ 1}}
      </van-item>
      <van-item name='2'>
        内容 {{ 2}}
      </van-item>
      <van-item name='3'>
        内容 {{ 3}}
      </van-item>
      <van-item name='4'>
        内容 {{ 4}}
      </van-item>
  </van-tab>
</van-tabs>`

**Comment by chenjiahan** [comment]
不使用 `v-for` 就行
