### ISSUE TITLE
时间选择器change事件，getValues()获取返回的数组有错误

### ISSUE THREAD

**Issue by zhYAO** [youzan/vant#1440]
将 时间选择组件 放入 弹出框，
![1531127118 1](https://user-images.githubusercontent.com/9971884/42441225-59aa4356-839a-11e8-9d77-ef0978dc2850.jpg)
![w d q nkn 8vd eex ut](https://user-images.githubusercontent.com/9971884/42441357-84ea9d04-839a-11e8-8224-04ce0ebc85b9.png)

刚开始没有选择：
![2pmunnh1q2 1 773 d07oj](https://user-images.githubusercontent.com/9971884/42441405-abe09710-839a-11e8-9c7c-cef5e536ba48.png)

选择月后返回的数组：
![4 0 ng2h r 7j3 f75n](https://user-images.githubusercontent.com/9971884/42441697-64590584-839b-11e8-9c76-05cc76cc9bb3.png)

选择年后返回的数组：
![z a80vkw6k6g8t zts vj g](https://user-images.githubusercontent.com/9971884/42441762-88cb0962-839b-11e8-86f0-76b021727b55.png)

**Comment by chenjiahan** [comment]
最新版已经修复了这个问题
