### ISSUE TITLE
.van-field .van-cell__title {     max-width: 90px; }   这个 max-width的值是否可以由自己配置？

### ISSUE THREAD

**Issue by fightingFan** [youzan/vant#1442]
.van-field .van-cell__title {     max-width: 90px; }   这个 max-width的值是否可以由自己配置？

**Comment by chenjiahan** [comment]
暂不支持，可以直接覆盖样式

**Comment by Hideer** [comment]
你好我重置 van-cell__title的样式并不生效
您能帮我看看么
