### ISSUE TITLE
Area丢失数据

### ISSUE THREAD

**Issue by 18510758841** [youzan/vant#1454]
![1431531207383_ pic_hd](https://user-images.githubusercontent.com/23565370/42495362-6f1b5886-8455-11e8-971d-4a467b56aee2.jpg)
这是请求回来的数据
![1441531207394_ pic](https://user-images.githubusercontent.com/23565370/42495377-7d8ab308-8455-11e8-838a-607ac756b863.jpg)
渲染出来4条

![image](https://user-images.githubusercontent.com/23565370/42495537-ece73370-8455-11e8-8ffa-baf9afefc717.png)

**Comment by 18510758841** [comment]
明白官方文档定义的code是6位，我们后台请求接口定义的code是4位，拿到code 后去请求数据，为什么没有渲染到列表中？官方对数据做了处理的话，麻烦告之如何解决，谢谢

**Comment by 18510758841** [comment]
![image](https://user-images.githubusercontent.com/23565370/42505678-0f1188f8-8472-11e8-9ede-84bd7b150c26.png)

**Comment by 18510758841** [comment]
拿code的前两位判断···

**Comment by chenjiahan** [comment]
Area 现在是要求 6 位地区码的，具体逻辑可以看源码，一共就 100 多行
