### ISSUE TITLE
关于AddressEdit部分数据绑定的文档说明

### ISSUE THREAD

**Issue by hnsxxscyx** [youzan/vant#1459]
**What problem does this feature solve?**
AddressEdit部分数据绑定的文档api

address-info 为收货人信息，但这个对象并非双向绑定的（表单更新与之绑定的对象不会自动更新）

**Describe the solution you'd like**
建议文档中说明由save事件获取表单各项参数

**What does the proposed API look like?**
文档中添加一个注明即可。
谢谢大大维护库。

**Comment by chenjiahan** [comment]
感谢反馈，后续会优化一下文档

**Comment by chenjiahan** [comment]
文档已更新
