### ISSUE TITLE
area

### ISSUE THREAD

**Issue by Fanaiwen** [youzan/vant#1460]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
van-picker多栏的时候，第二栏选择时候会回弹，无法选择默认以外的选项

**Screenshots**
![gif](https://user-images.githubusercontent.com/37430039/42550106-404bab66-8502-11e8-935b-acf0cd67913c.gif)

**Environment**
 - Device: win10 
 - Browser: chrome ,firefox
 - Vant Version: 1.1.9/1.1.12

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by SnowZhangXl** [comment]
数据格式是不是和事例不一致。

**Comment by Fanaiwen** [comment]
数据格式从后台获取的，是一致的，但是好像把county-list融合到city-list里面了

**Comment by Fanaiwen** [comment]
这个能不能解决了？
