### ISSUE TITLE
AddressEdit收件地区没有显示

### ISSUE THREAD

**Issue by KaivOU** [youzan/vant#1469]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
进入编辑地址组件，在生命周期created()给address-info里赋值好的地址信息，其他的电话详细地址都可以显示，就收件地区没有显示，为什么？

**Screenshots**
![wechatimg3420](https://user-images.githubusercontent.com/36435545/42580061-3883314c-855c-11e8-9640-0325515192f2.jpeg)

**Environment**
 - Device: 微信公众号
 - Browser: 微信公众号开发者工具
 - Vant Version: V1.1.12

**Reproduce**

**Comment by chenjiahan** [comment]
还需要传递 area_code 参数
