### ISSUE TITLE
使用lib-flexible样式问题

### ISSUE THREAD

**Issue by zhujunel** [youzan/vant#1471]
设计稿都是按照iPhone6作为基准设计尺寸，rem基准值:75,组件都特别的小，这个怎么破

**Comment by Fangsiyu** [comment]
因为你用的 rem 单位，官方文档写了：vant 用的 px 为单位，而且目前我没找到官方是否适配各个移动端了代码（我估计没有适配），酱

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/1181
