### ISSUE TITLE
list组件load方法执行多次

### ISSUE THREAD

**Issue by zxbigdevil** [youzan/vant#1475]
js:
![image](https://user-images.githubusercontent.com/20895193/42626570-406643b2-85fd-11e8-8952-b9f9bc8ba078.png)
html:
![image](https://user-images.githubusercontent.com/20895193/42626591-4b9601f0-85fd-11e8-9461-8d74d21ccf37.png)
接口：
![image](https://user-images.githubusercontent.com/20895193/42626708-942aed9a-85fd-11e8-9b46-c9b717e629fc.png)
![image](https://user-images.githubusercontent.com/20895193/42626738-a60cf292-85fd-11e8-80e7-102a78e4f039.png)

求各位大神帮忙指点下，为什么会这样一下加载好多次方法，看了之前的这个问题但是还没有解决，求帮助

**Comment by SnowZhangXl** [comment]
![image](https://user-images.githubusercontent.com/30932683/42637755-93549e0e-861e-11e8-97ef-643f7d329f86.png)
