### ISSUE TITLE
list中load无限执行

### ISSUE THREAD

**Issue by zxbigdevil** [youzan/vant#1479]
html：
![image](https://user-images.githubusercontent.com/20895193/42671562-2cd95d02-8693-11e8-96c5-4718e9cbf56c.png)
js:
![image](https://user-images.githubusercontent.com/20895193/42671564-31860364-8693-11e8-9f5d-ab3183d0228a.png)
console：
![image](https://user-images.githubusercontent.com/20895193/42671575-3f211e14-8693-11e8-9b01-7243510181f2.png)

求大神帮忙看一下怎么修改，我找个一进来页面他就开始无限执行下去，求助js怎么改

**Comment by rex-zsd** [comment]
`list` 组件会在滚动条与底部距离大于offset的时候再次出发 `load`事件，除非显示的设置 `loading` 或者 `finished` 为 `true`。
所以这个现象是正常的，你这里并没有无限执行，执行到第5次 `finished` 设成 `true` 了就没再执行了。
