### ISSUE TITLE
address_edit trim is not a function

### ISSUE THREAD

**Issue by tielei60** [youzan/vant#1485]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
地址编辑功能，点击保存时候，报错：this.data[key].trim is not a function

**Screenshots**

![bug](https://user-images.githubusercontent.com/12453480/42722079-4300909c-8778-11e8-8453-5ee3f13e4bef.png)

**Environment**
 - Device: Mac Pro
 - Browser: Google Chrome V67
 - Vant Version: 1.1.13

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
目前手机号、邮政编码都必须为 `string` 格式，下个版本会支持下 `number` 格式

**Comment by tielei60** [comment]
搞定了，非常感谢
