### ISSUE TITLE
弹层中用滚动报错

### ISSUE THREAD

**Issue by tjsome** [youzan/vant#1490]
警告提示：index.js?ff82:173 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
[[](url](url
[
![image](https://user-images.githubusercontent.com/23496133/42744262-aaefce80-88fd-11e8-81ba-88446045a1bb.png)
](![image](https://user-images.githubusercontent.com/23496133/42744257-9b81d920-88fd-11e8-98d4-789f32e87590.png))
)
![image](https://user-images.githubusercontent.com/23496133/42744245-870204b6-88fd-11e8-8809-829ebad82562.png)
)

**Comment by tjsome** [comment]
警告提示：index.js?ff82:173 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.[](url
![image](https://user-images.githubusercontent.com/23496133/42744214-531f41ae-88fd-11e8-820e-418bef79f1f7.png)
)

**Comment by chenjiahan** [comment]
能否提供一个 jsfiddle?

**Comment by tjsome** [comment]
暂时不能，是在弹层中使用了，就是单纯的css样式[](url
[
![image](https://user-images.githubusercontent.com/23496133/42790197-464c477a-899c-11e8-9930-5c6c3071f359.png)
](![image](https://user-images.githubusercontent.com/23496133/42790190-3a3534e2-899c-11e8-864b-7c156767c097.png))
)

**Comment by chenjiahan** [comment]
未能复现这个问题，这个报错应该是浏览器的提示，不会影响代码运作
