### ISSUE TITLE
用了懒加载和swpier这两个组件，后面的几个图片都一直lazy="loading"出不来

### ISSUE THREAD

**Issue by lyseky** [youzan/vant#1491]
`<van-swipe :autoplay="3000">
              <van-swipe-item v-for="image in groupList.group_item" :key="image.group_item_id">
                <div @click="goProduct(image)">
                  <img v-lazy="image.item_img1" />
                </div>
              </van-swipe-item>
            </van-swipe>`

**Comment by chenjiahan** [comment]
麻烦给个 jsfiddle
