### ISSUE TITLE
Checkbox 复选框自定义图标不生效

### ISSUE THREAD

**Issue by lxiaosky** [youzan/vant#1493]
`<van-checkbox v-model="checked">
  自定义图标
  <img
    slot="icon"
    slot-scope="props"
    :src="props.checked ? icon.active : icon.normal"
  >
</van-checkbox>`
`export default {
  data() {
    checked: true,
    icon: {
      normal: '//img.yzcdn.cn/icon-normal.png',
      active: '//img.yzcdn.cn/icon-active.png'
    }
  }
}`
安装官方给出的案例,自定义图标不生效,还是显示的默认图标

我是通过script直接引入的vant.js
`<script type="text/javascript" src="../../script/vant.js"></script>`

**Comment by chenjiahan** [comment]
可以确认下引入的是否是最新版本的 vant
