### ISSUE TITLE
没有Scroll滚动组件????

### ISSUE THREAD

**Issue by mixingyu** [youzan/vant#1498]
还是我没有找到????
类似这个https://wangdahoo.github.io/vonic/docs/#/advanced/scroll

**Comment by SnowZhangXl** [comment]
https://youzan.github.io/vant/#/zh-CN/list

**Comment by mixingyu** [comment]
不是这个 我想要一个scroll 里面随便放东西 这个太简陋了

**Comment by SnowZhangXl** [comment]
这个scroll是可以放list之外的东西的。

**Comment by SnowZhangXl** [comment]
这个scroll是可以放list之外的东西的。
