### ISSUE TITLE
when the button actived we can see 1px blank

### ISSUE THREAD

**Issue by ZWkang** [youzan/vant#150]
当按钮被点击/常按的时候可以很明显看到有一部分空白

原因是因为button contaniner宽高定了之后。
用的是before，占据宽高百分百以后最大也会减去contaniner的1px。
before又使用的inherit 父级的border-radius。
所以导致了空白的出现。。
个人暂时想到两种解决方案
1.是active时候的border-radius为0；父contaniner的overflow:hidden;
2.active时候after的top right bottom left的调整
这样子的会导致border的像素值稍微有一些加深。

已经提交pr用的是第二种方法。因为overflow:hidden的话可能对一些现有使用者影响较大些。

**Comment by zongzi531** [comment]
我的iPhone 8也遇到了同样的问题，我用同事的iPhone 7 Plus显示正常。
我试着去修改样式，为button:active添加了一个background-color属性，手机上看起来似乎奏效了，但是pc上却不尽人意。
我试着修改button.css下的&--bottom-action的border-radius: 4px 似乎也是这样的效果。

**Comment by chenjiahan** [comment]
感谢反馈，即将在下个版本中修复
