### ISSUE TITLE
请问移动端300ms延迟怎么解决?

### ISSUE THREAD

**Issue by lxiaosky** [youzan/vant#1501]
在ios端,有延迟,用了网上的方法都没有用,如果不使用vant框架,倒是可以解决300ms延迟,但是在vant上用就会有延迟,比如
`<van-tabs v-model='frmTabActive'
                  :swipe-threshold='6'
                  @click="onTabs"
                  :line-width='lineWidth'>
            <van-tab v-for="(n,i) in frmTabs" :title="n" :key='i'></van-tab>
        </van-tabs>`
建议把所以click事件替换成touchstart事件,
我修改vant.js源码后,可以解决延迟问题
`
<van-tabs v-model='frmTabActive'
                  :swipe-threshold='6'
                  @touchstart="onTabs"
                  :line-width='lineWidth'>
            <van-tab v-for="(n,i) in frmTabs" :title="n" :key='i'></van-tab>
</van-tabs>
`
以下是截取的van-tabs组件点击事件的源码,我修改为touchstart后,300ms延迟问题得到解决
`
on: {
       touchstart: function (e) {
             t.onClick(i)
       }
}
onClick: function (t) {
           var e = this.tabs[t], n = e.title;
           e.disabled ? this.$emit("disabled", t, n) : (this.$emit("touchstart", t, n), this.setCurActive(t))
}
`
该框架主要针对移动端的,建议都替换成touchstart

**Comment by chenjiahan** [comment]
目前只有 UIWebView 有 300ms 延迟，占比很小，组件内不计划使用 touchstart 事件，touchstart 在滚动时会导致误触

**Comment by lxiaosky** [comment]
可是我在useWKWebView里面测试一样的会有300ms延迟,不知道你们测试过了没

**Comment by lxiaosky** [comment]
我手机的iphone7plus  系统版本是10.3.2

**Comment by lxiaosky** [comment]
如果不使用touchstart事件,那有别的办法处理300ms 延迟吗?因为有些组件是在click事件里进行回调的,那300ms延迟体验不太好

**Comment by chenjiahan** [comment]
WK 需要设置 viewport user-scalable=0
```html
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
```

**Comment by plqin-xiaohao** [comment]
关于移动端300ms的事件延迟, vant是如何处理的呢
