### ISSUE TITLE
Tab 组件 sticky 增加一个 距离顶部的高度功能

### ISSUE THREAD

**Issue by yajore** [youzan/vant#1504]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
sticky 的粘性布局是否提供一个额外的参数，offsetTop 去控制Tab 距离顶部的高度，现实场景还是有很多这种需求的

**Describe the solution you'd like**

**What does the proposed API look like?**
props:{
offsetTop :String | Number
}

**Comment by chenjiahan** [comment]
后续会考虑支持

**Comment by dhx1213** [comment]
对的，我正准备提这个请求

**Comment by chenjiahan** [comment]
已在 1.1.15 版本支持

**Comment by xiaoshidetaikuai** [comment]
我尝试了这个属性，但是为什么滚动的时候会tab会上移一段位移？我用了number
