### ISSUE TITLE
图片预览组建ImagePreview 返回不销毁问题

### ISSUE THREAD

**Issue by xiaobingMa** [youzan/vant#1506]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
ImagePriview组建预览后点击物理返回键，并不销毁，而是依然显示预览状态
**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/28527661/42875785-45bd9388-8ab7-11e8-8daf-16e87bcbbee5.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
这块逻辑不会在组件内实现，建议自己监听并手动关闭
