### ISSUE TITLE
popup和picker一起使用的时候，css样式冲突，弹出层显示不了选择器

### ISSUE THREAD

**Issue by hello-lun** [youzan/vant#1507]
项目中，popup和picker一起使用的时候，css样式冲突，弹出层显示不了选择器。
（1）代码如下：
![image](https://user-images.githubusercontent.com/34638158/42917177-094594c6-8b3b-11e8-95e2-b14033180f10.png)
出错效果如下：
![image](https://user-images.githubusercontent.com/34638158/42917129-ddfbfaa8-8b3a-11e8-9064-fa51ea9eb0ea.png)；

（2）当我把class   van-picker__frame的样式修改成下图就可以成功显示了：
![image](https://user-images.githubusercontent.com/34638158/42917224-413ef6d8-8b3b-11e8-975e-c730671eb8c3.png)

![image](https://user-images.githubusercontent.com/34638158/42917260-61ded836-8b3b-11e8-8524-835ef8c70282.png)

**Comment by lin-xin** [comment]
使用 DatetimePicker 也遇到同样的问题，需要自己定义样式解决

**Comment by chenjiahan** [comment]
没能复现此问题，能否提供一个 jsfiddle?

**Comment by nailuoGG** [comment]
是否进行了自定义主题，注释掉 import base.css 看看
```css
 import 'vant/packages/vant-css/src/base.css'
```

**Comment by marsprince** [comment]
import vanPopup from 'vant/lib/popup';
    import vanPicker from 'vant/lib/picker';

    import 'vant/lib/vant-css/base.css';
    import 'vant/lib/vant-css/popup.css';
    import 'vant/lib/vant-css/picker.css';
我是这样引入的，Picker没有内容，用楼主的方法可行

**Comment by chenjiahan** [comment]
注意一下 css 引入的先后顺序，应该不会有这个问题

**Comment by hello-lun** [comment]
@nailuoGG   真的是引入了base.css的问题

**Comment by zzw118** [comment]
@lin-xin 我也遇到这个问题了，在ios，弹出的时候日期选择出不来，只有一个遮罩层在，android倒是可以。你是怎么解决的呢？

**Comment by heihei001** [comment]
@zzw118 我也是在ios弹出日期选择，只有这招，么有选择器，搞不懂。

**Comment by leiwensu** [comment]
> @lin-xin 我也遇到这个问题了，在ios，弹出的时候日期选择出不来，只有一个遮罩层在，android倒是可以。你是怎么解决的呢？

我也遇到这个问题了，请问您解决了吗？

**Comment by TY-LIU** [comment]
@leiwensu @heihei001 @zzw118  我终于找到原因了，到mac Safari上控制台一看，报错信息是minDate的错误，但是我代码中都设置了的:
`:min-date="new Date('1900-1-1')"
:max-date="new Date()"`
就这样，但是就是报minDate的错。后来我一google Date+IOS关键字，才发现，Safari踏马居然不支持在Date对象中用横杠字符串自定义时间，后来改成 new Date('1900/1/1')就正常了。
龟龟，Safari也太秀了

**Comment by Luohaoran** [comment]
@TY-LIUnice啊兄弟

**Comment by lzxhyry** [comment]
官方说法，如果你遇到了在 iOS 上无法渲染组件的问题，请确认在创建 Date 对象时没有使用new Date('2020-01-01')这样的写法，iOS 不支持以中划线分隔的日期格式，正确写法是new Date('2020/01/01')。

**Comment by geng130127** [comment]
> 官方说法，如果你遇到了在 iOS 上无法渲染组件的问题，请确认在创建 Date 对象时没有使用new Date('2020-01-01')这样的写法，iOS 不支持以中划线分隔的日期格式，正确写法是new Date('2020/01/01')。

ios还是真秀啊
