### ISSUE TITLE
请问会开源Design组件嘛

### ISSUE THREAD

**Issue by PENG199** [youzan/vant#1508]
请问下会开源Design组件嘛

**Comment by chenjiahan** [comment]
见 https://youzan.github.io/zent/zh/component/design

**Comment by PENG199** [comment]
那个是react版本的，请问会考虑开源vue版本的嘛

**Comment by chenjiahan** [comment]
没有 Vue 版本喔

**Comment by bolechen** [comment]
最近也在做类似的后台，搜索到这里了。
zent 的 Design 组件是怎么跟 vant 的前端对应起来的？能简单分享一下实现思路吗？
不胜感激 @chenjiahan

**Comment by chenjiahan** [comment]
Design 组件内部会渲染若干个 Vue 组件，用户拖拽组件后，产生一个组件列表数组，

然后 C 端通过 v-for 遍历这个数组，渲染出对应的组件。

大致就是这样 ^_^
