### ISSUE TITLE
htc 手机  andrio 6.5 

### ISSUE THREAD

**Issue by Anikinly** [youzan/vant#1510]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
![image](https://user-images.githubusercontent.com/9296136/42923031-09d9bce4-8b56-11e8-9efe-9fc98ef24ce6.png)

ju居中失效  translate 失效
**Screenshots**
Add screenshots to help css3 手机 transform 不支持 your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
问题描述不清晰
