### ISSUE TITLE
评论组件不能用？显示-您是否正确注册了组件?对于递归组件，请确保提供“name”选项。

### ISSUE THREAD

**Issue by lijinqun** [youzan/vant#1515]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by eviem** [comment]
没有评论的组件把？你应该说的是评分组件，应该是你没有在component里面注册组件。
需要这么注册的。
`components:{
          [Rate.name]:Rate
      },`
