### ISSUE TITLE
Tabbar和Navbar固定定位后，高度问题

### ISSUE THREAD

**Issue by eviem** [youzan/vant#1517]
Tabbar 和 Navbar 固定后，都需要自己写一个空的DIV高度去把内容顶出来，不然会被 Tabbar 和 Navbar 挡住内容。

**Comment by nailuoGG** [comment]
正常情况。可以设置padding-bottom解决。或者也可以将组件fixed值设置为false，放在内容下方，然后内容做局部滚动
