### ISSUE TITLE
可以设置是否使用同一个van-modal？

### ISSUE THREAD

**Issue by marsprince** [youzan/vant#1522]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
当前多个popup都是复用一个modal，同时使用多个包含popup（类似dialog等）的组件就会出现层级BUG，最下面的modal丢失了，内容和弹窗混在了一起

**Describe the solution you'd like**
在用户希望的时候应该可以使用多个modal，弹出一个新的popup的时候保存前一个popup的状态

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
能否给个 jsfiddle 复现一下你说的问题？
