### ISSUE TITLE
Stepper 的integer 参数 为true 不生效

### ISSUE THREAD

**Issue by dajohnny** [youzan/vant#1525]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
Stepper 的integer 参数 为true 不生效

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 
上面参数详细见：jsfiddle地址

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/227/

**Comment by SnowZhangXl** [comment]
我试了下，是能够输入的。现在是有个输入小数点的bug
#1521

**Comment by dajohnny** [comment]
是的，我期待下次更新能将它解决。谢谢！

**Comment by chenjiahan** [comment]
已在 1.1.15 版本修复
