### ISSUE TITLE
微信上浏览文字垂直不局中

### ISSUE THREAD

**Issue by lx3xun** [youzan/vant#1526]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.
在微信上浏览官网的示例会有样式错乱的情况，请看下图按钮的文字。请问，有什么解决办法吗？
![image](https://user-images.githubusercontent.com/6147862/43046304-7b322f8e-8df9-11e8-92b1-b7cbacb5b237.png)

**Environment**
 - Device: 
 - Browser:  微信
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by CocoChen917** [comment]
@lx3xun 安卓手机？

**Comment by lx3xun** [comment]
IOS的偏下，安卓的偏上。 






在2018年07月23日 15:51，CocoChen917<notifications@github.com> 写道：

@lx3xun 安卓手机？

**Comment by chenjiahan** [comment]
没遇到过这个问题，可以看下是不是某些设置导致的

**Comment by lx3xun** [comment]
我知道什么问题了，如果调整了字体大小就会出现这样的情况，你可以试下。






在2018年07月23日 20:17，neverland<notifications@github.com> 写道：

没遇到过这个问题，可以看下是不是某些设置导致的

**Comment by chenjiahan** [comment]
已在 1.1.15 版本修复
