### ISSUE TITLE
文档有错

### ISSUE THREAD

**Issue by liupei1995** [youzan/vant#1527]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/
Loading加载的API参数color，可选颜色为black，white
文档中写成了block white
![1532306729 1](https://user-images.githubusercontent.com/21356797/43052175-b6a916de-8e55-11e8-9a64-daad253ea7e0.png)

**Comment by chenjiahan** [comment]
后续修正

**Comment by chenjiahan** [comment]
文档已更新
