### ISSUE TITLE
vant的官方demo中是如何实现PC端对touch事件的支持？

### ISSUE THREAD

**Issue by gyrate** [youzan/vant#1529]
最近在使用vant时发现如果不开启chrome浏览器的移动端尺寸模式（toggle device toolbar），某些仅监听了touch事件的组件是无法正常使用的，如图所示。

![menu saveimg savepath20180723114155](https://user-images.githubusercontent.com/1127991/43056269-e01824f2-8e6d-11e8-8c4a-cd161d4f9b01.jpg)

然而vant的官方demo，不管切换到任何网模式均可以如移动端一样正常使用，不知道是如何做到的。

**Comment by gyrate** [comment]
![qq 20180723171547](https://user-images.githubusercontent.com/1127991/43068112-1170afe6-8e9c-11e8-9a38-15d50f6f0016.png)

翻了一下代码发现这个东西，可以提供源代码么

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/issues/637
