### ISSUE TITLE
友情支持一下

### ISSUE THREAD

**Issue by marsprince** [youzan/vant#153]
美团同事，内网里看了你写的Payui，很不错，看了你的经历很有感触，支持一个

**Comment by chenjiahan** [comment]
哈哈，谢谢支持😆 PayUI 就靠你们维护了

**Comment by marsprince** [comment]
我不是支付部门的，Payui上一次提交是7月份，好像没人管了😆

**Comment by chenjiahan** [comment]
应该是有人管的，现在他们都在维护 PayUI 的 Vue 版本~

**Comment by marsprince** [comment]
加油加油
