### ISSUE TITLE
webpack版本不一致导致每人页面结构不一致

### ISSUE THREAD

**Issue by jackie-cheng** [youzan/vant#1530]
webpack 2.0+  和webpack3.0+编译后HTML结构不一样!!!!!同事版本是3.0+的，我2.0+，两人代码一样，但是看了浏览器html 不一样，导致样式都乱了

**Comment by jackie-cheng** [comment]
出现组件   为
<van-cell-group>
        <van-cell >

**Comment by jackie-cheng** [comment]
van-cell-group
        van-cell

**Comment by jackie-cheng** [comment]
卸载重装了一下午，发现不是webpack和node版本不一致导致，不知道什么原因。现在还没解决 。样式在那边是好的  在我这里是乱的。 vue文件编译后的html 结构都不一样

**Comment by jackie-cheng** [comment]
![qq 20180723150007](https://user-images.githubusercontent.com/26160530/43061777-1f0628ce-8e89-11e8-8832-7317808841ce.png)

**Comment by jackie-cheng** [comment]
![qq 20180723150056](https://user-images.githubusercontent.com/26160530/43061820-42be4ef4-8e89-11e8-94b1-ea84e4d17bcf.png)

**Comment by chenjiahan** [comment]
这个问题应该和组件库无关

**Comment by jackie-cheng** [comment]
我把vant 版本更新到最新版现在样式好了，可是之前我和同事都是1.07的，package.json声明的有版本号，但是他的样式就是和我不一样 ，唉。不知道你们npm库有没有存历史代码啊
