### ISSUE TITLE
日期控件（datetimepicker）可以对时分设置范围

### ISSUE THREAD

**Issue by ShowJoy** [youzan/vant#1531]
**What problem does this feature solve?**
日期控件（datetimepicker）不能对时分设置区间范围

**Describe the solution you'd like**
日期控件（datetimepicker）type= datetimes时 能对时分设置区间范围

**What does the proposed API look like?**
min-hour="5"
max-hour="20"
min-minutes="0"
max-minutes="0"

**Comment by ShowJoy** [comment]
请问下版本会支持吗？谢谢

**Comment by chenjiahan** [comment]
下个版本应该会支持~

**Comment by chenjiahan** [comment]
已在 1.1.15 版本支持

**Comment by ShowJoy** [comment]
大佬，目前还是针对type=time类型日期控件才可以设置吧？

**Comment by chenjiahan** [comment]
其他类型直接用 max-date 就行
