### ISSUE TITLE
轮播图swipe设置为垂直滚动的时候整个轮播图不显示

### ISSUE THREAD

**Issue by Smile-shop** [youzan/vant#1535]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
轮播图swipe设置为垂直滚动的时候整个轮播图不显示

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.114

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by LynanBreeze** [comment]
需要设置父级高度。
