### ISSUE TITLE
CellSwipe 滑动单元格 可以实现点击一个按钮,多个cellswip向右滑动吗?

### ISSUE THREAD

**Issue by hghwill** [youzan/vant#1538]
场景是一个list 包含多个cellswipe 
通过点击导航栏的'批量删除' 按钮
促发cellswipe全部向右滑动,显示出每个cell的删除按钮

**Comment by chenjiahan** [comment]
下个版本支持手动控制 CellSwipe 的滑动状态

**Comment by hghwill** [comment]
期待，啥时候更新版本啊

**Comment by chenjiahan** [comment]
本周内会更新喔

**Comment by chenjiahan** [comment]
已在 1.1.15 版本支持 open 方法
