### ISSUE TITLE
npm 包里没有navbar组件。

### ISSUE THREAD

**Issue by linqiang007** [youzan/vant#154]
npm 包里没有navbar组件。

node_modules文件夹
![image](https://user-images.githubusercontent.com/12245095/30952932-747fe78e-a3ef-11e7-94fd-27f42f5997a7.png)

git文件夹
![image](https://user-images.githubusercontent.com/12245095/30952957-9052350c-a3ef-11e7-8ff0-a150940f7900.png)

**Comment by chenjiahan** [comment]
@linqiang 能确认下你的 vant 版本吗，NavBar 组件是在 Vant 0.9.2 版本添加的

**Comment by linqiang007** [comment]
@chenjiahan 用脚手架搭了一个没注意版本，0.8.9。你们更新下脚手架的版本吧。

**Comment by chenjiahan** [comment]
@linqiang007 好的，后续会及时同步版本

**Comment by chenjiahan** [comment]
脚手架已更新
