### ISSUE TITLE
在钉钉的内置浏览器中，Tabbar 标签栏中使用router-link无法使用

### ISSUE THREAD

**Issue by yoking-shi** [youzan/vant#1541]
**Describe the bug**
在钉钉的内置浏览器中，Tabbar 标签栏中使用router-link无法使用，点击之后图标效果是存在的。但是页面不会切换
ios基本不会出现问题，但是安卓的钉钉app上边会出现这个问题

**Environment**
 - Device:  安卓 + 钉钉app内置浏览器
 - Vant Version:  1.1.14

**Comment by chenjiahan** [comment]
这个应该是 vue-router 的问题，与组件库木有关系
