### ISSUE TITLE
以$toast、$dialog 形式调用 toast和dialog在prod环境莫名undefined 

### ISSUE THREAD

**Issue by LynanBreeze** [youzan/vant#1542]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在dev环境下也有时也无法调用。（大部分情况可以，有些组件内不可以）
不知是为什么。打包后所有的this.$dialog、this.$toast均undefined

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device:  PC
 - Browser:  Chrome x64 latest
 - Vant Version:  1.1.14

**Reproduce**

**Comment by chenjiahan** [comment]
可能你 Import 了 Dialog/Toast 组件，但是没有在代码中使用，所以被当做 unused variable 被 uglify 移除了
手动调用  Vue.use(Dialog).use(Toast) 可以避免这种情况
