### ISSUE TITLE
popup 组件中 lock-scroll 功能 在 ios 中失效

### ISSUE THREAD

**Issue by cocody** [youzan/vant#1544]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

popup 组件中 lock-scroll 功能，在 web/安卓（小米6） 都有效， 但是在 IOS6（11.3）下无效

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device:  小米6/IOS6（11.3）
 - Browser:  微信最新版
 - Vant Version:  1.1.14

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
试了一下没复现这个问题噢，机型 iphone 6s
