### ISSUE TITLE
怎么修改弹出层样式

### ISSUE THREAD

**Issue by zhou2811** [youzan/vant#1547]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by Fyerl** [comment]
可以直接覆盖样式
