### ISSUE TITLE
有些组件直接拿出来就可以用，真的方便，希望下一步支持ssr（nuxt） rua!

### ISSUE THREAD

**Issue by psychokiller666** [youzan/vant#155]
如题

**Comment by chenjiahan** [comment]
@psychokiller666 Vant 已经添加了对 SSR 的支持，如果你在 SSR 使用过程中遇到问题欢迎反馈~

**Comment by psychokiller666** [comment]
@chenjiahan 有qq或者微信交流群吗，一起搅基啊

**Comment by chenjiahan** [comment]
@psychokiller666 有的哈，欢迎一起玩耍~
![wechatimg86](https://user-images.githubusercontent.com/7237365/30954576-5053c7f2-a3f6-11e7-8966-2579a1560f09.jpeg)
