### ISSUE TITLE
DatetimePicker  默认值绑定不成功，api中没有currentDate的说明 跪求回答！！项目正在使用

### ISSUE THREAD

**Issue by zhengcaifeng** [youzan/vant#1550]
使用 "vant": "^1.1.14", 版本
DatetimePicker  组件中的  type="datetime"   v-model="currentDate"  ，在data中设置
currentDate: new Date(),  绑定不成功
如果 type="datetime"   v-model="currentDate"   v-model="currentDate"   在data中设置
currentDate: '12:00'   就可以绑定成功，

**Comment by SnowZhangXl** [comment]
![image](https://user-images.githubusercontent.com/30932683/43388867-dc2cc83e-941c-11e8-9962-0bbd482ea4da.png)

**Comment by zhengcaifeng** [comment]
![1533004834 1](https://user-images.githubusercontent.com/27950890/43434490-6ea77a1a-94ae-11e8-82ec-485c06f3b633.jpg)
![2](https://user-images.githubusercontent.com/27950890/43434491-6edbf7ae-94ae-11e8-91e5-4a7d2b2be3fe.jpg)
![3](https://user-images.githubusercontent.com/27950890/43434497-738bf970-94ae-11e8-87af-f1a3f3817efb.jpg)
如果要绑定当前时间，怎么办，绑定不成功啊

**Comment by SnowZhangXl** [comment]
formatter你用到了吗？没用到删掉试下

**Comment by chenjiahan** [comment]
这个问题是 formatter 逻辑有误导致的，下个版本会修复

**Comment by chenjiahan** [comment]
已在 1.1.16 版本修复
