### ISSUE TITLE
npm install 下来的css，里边有的icon font文件，是cdn引用的，而不是本地的。

### ISSUE THREAD

**Issue by wfxiaolong** [youzan/vant#1552]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**源码有远程cdn文件**
里边有的icon font文件，是cdn引用的，而不是本地的。

**icon font**
会引起一个问题就是海外的访问速度其实原来的cdn是比较慢的。

**Comment by chenjiahan** [comment]
可以使用本地文件的，详见 Icon 文档
