### ISSUE TITLE
slider props's max=900时，slider的width=900%，宽度超出父级元素

### ISSUE THREAD

**Issue by dajohnny** [youzan/vant#1553]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
例如value2参数的slider组件为例，当设置大于100时，拉动拉杆可以向右拉动直至超出父元素的宽度。
希望：当用户有设定 min(不设定，默认0)和max时，当前值所对应的进度时根据他们的区间百分比计算来对应显示，且对应显示在父级元素内。

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/17939743/43376982-e39541f2-93e3-11e8-89b1-98cd1ed9fb61.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 
    详细参数请查看：https://jsfiddle.net/dfarLdko/250/

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/250/

**Comment by chenjiahan** [comment]
slide 的 value 必须在 0 ~ 100 范围内噢
