### ISSUE TITLE
Please give an english translation for the API

### ISSUE THREAD

**Issue by eladcandroid** [youzan/vant#156]

**Comment by pangxie1991** [comment]
Noticed! We are working on that.

**Comment by francishero** [comment]
I can help with translation

**Comment by pangxie1991** [comment]
@francishero That's Great! I will add some translation examples in `docs/examples-docs` these days. After that, maybe you can help us~

**Comment by francishero** [comment]
ok cool tell me when you are done

**Comment by pangxie1991** [comment]
@francishero 
Hi~ I finished some examples. All English docs are located under `docs/examples-docs/en-US` . Maybe you can start from `actionsheet.md`, `button.md`, `cell.md`.

Thanks for your help~

**Comment by francishero** [comment]
Ok cool. Tomorow i will get started

**Comment by chenjiahan** [comment]
done
