### ISSUE TITLE
能否分享icon 字体库的图标原始文件或iconfont 

### ISSUE THREAD

**Issue by zhuangxiaohui** [youzan/vant#1561]
能否分享icon 字体库的图标原始文件或iconfont （http://iconfont.cn/）

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/tree/dev/packages/icon/assets

**Comment by zhuangxiaohui** [comment]
谢谢分享

**Comment by zhuangxiaohui** [comment]
http://iconfont.cn/collections/detail?cid=11511

**Comment by chenjiahan** [comment]
@zhuangxiaohui 很赞喔，辛苦了~
