### ISSUE TITLE
全局导入组件，使用Lazyload 图片懒加载时，lazy指令无法解析

### ISSUE THREAD

**Issue by kbgyf** [youzan/vant#1563]
代码如图，抛出了异常
![image](https://user-images.githubusercontent.com/37326126/43440456-f27518a0-94c9-11e8-87e5-d190280ec1fe.png)
![image](https://user-images.githubusercontent.com/37326126/43440303-5f845fb0-94c9-11e8-8c69-d7dfdf6b598f.png)
![image](https://user-images.githubusercontent.com/37326126/43440316-6e065958-94c9-11e8-8c94-8a7159756004.png)

**Comment by chenjiahan** [comment]
Lazyload 需要手动注册喔
