### ISSUE TITLE
建议给TAB组件增加一个功能把tab和content分开

### ISSUE THREAD

**Issue by lxiaosky** [youzan/vant#1564]
比如设置isContent='false'
那样只渲染tab而不要content

比如我有个需求就是点击tab动态改变一下里面的数据,tab可以滑动,tab超过一定数量可以横向滚动等这些功能

但是我不需要给每个tab渲染一个content,只需要一个content,我点击content里面的内容,然后通过tab的id去获取

我现在动态渲染了100多个tab,但是content也跟着创建了100多,我觉得这样是不是很耗性能

**Comment by chenjiahan** [comment]
暂时没计划这样修改，content 不会很影响性能，因为默认是隐藏的空 div
