### ISSUE TITLE
建议upload组件多增加几种样式

### ISSUE THREAD

**Issue by maomi20150102** [youzan/vant#1566]
建议，上传组件可不可以多出几个预览样式，比如像下面这样的
http://element-cn.eleme.io/#/zh-CN/component/upload
https://weui.io/#uploader

请原谅我这个被老板压迫兼职前端的手残后端开发

**Comment by chenjiahan** [comment]
后续会支持一下预览，参见这个 issue：https://github.com/youzan/vant/issues/1536
