### ISSUE TITLE
[Feature Request] 希望【单选框】组件可以自定义图标

### ISSUE THREAD

**Issue by ghost** [youzan/vant#1567]
希望 **Radio 单选框** 也可以像 **Checkbox 复选框** 一样有自定义图标的功能。

**Comment by chenjiahan** [comment]
后续版本支持

**Comment by zhfish** [comment]
没差别。。Checkbox设置最多选一个

**Comment by jiangzhenggeng** [comment]
> 没差别。。Checkbox设置最多选一个

radio意味可以强制选择当前，其他的强制取消选择，但checkbox不能，max=1，的时候，选择了一项，再选择其他项就不能选择，使用场景不同，虽然做一下出来可以达到效果，但是失去了radio组件的意义

**Comment by zenonux** [comment]
同需要。不然每次还要自己改源码

**Comment by chenjiahan** [comment]
已在 1.6.0 版本支持
