### ISSUE TITLE
List 列表控件显示第一页时，删除掉其中几项后，不会自动加载第二页

### ISSUE THREAD

**Issue by mib23** [youzan/vant#1568]
**Describe the bug**
List 列表控件显示第一页时，删除掉其中几项后，不会自动加载第二页。

**Screenshots**
![Alt text](http://www.feidaosoft.com/wp-content/uploads/2018/08/vanlist.png)
图片上是第一页，已经被我删掉了2条记录，没有自动加载第二页，
或者有什么办法可以判断滚动条高度后手动加载第二页

**Environment**
 - Device: PC（Window）
 - Browser: Chrome 67
 - Vant Version: 1.1.14

**Comment by chenjiahan** [comment]
这种情况暂时没法处理，下个版本会增加一个手动触发检测的 api

**Comment by chenjiahan** [comment]
已在 1.1.16 版本支持
