### ISSUE TITLE
Tabbar 标签没有改变也会触发change事件

### ISSUE THREAD

**Issue by SweetJun** [youzan/vant#1569]
**Describe the bug**

既然是change事件，应该只有当标签改变后才会触发吧。。。点击当前活动标签应该不会触发的吧。。
下面截图   活动页为首页时，再次点击首页还会触发Toast，虽然自己可以判断active来实现程序执行，但还是觉得应该完善下。。。

**Screenshots**

![1533107252 1](https://user-images.githubusercontent.com/19986739/43506511-ddc58bfa-959c-11e8-8582-e832d6810cdf.jpg)

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.1.15 版本修复
