### ISSUE TITLE
Tab组件type为card时，sticky属性设置无效

### ISSUE THREAD

**Issue by gorden301** [youzan/vant#1570]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Tab组件type为card时，sticky属性设置无效

**Environment**
 - Device: iphone和安卓
 - Browser: google
 - Vant Version: 1.1.8

**Comment by chenjiahan** [comment]
未能复现此问题
