### ISSUE TITLE
打包vant UI组件没有自动添加-webkie兼容前缀，导致ios8版本ui排版以及加载框和弹窗出现了问题

### ISSUE THREAD

**Issue by 735086039** [youzan/vant#1573]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
打包vant UI组件没有自动添加-webkie兼容前缀，导致ios8版本ui排版以及加载框和弹窗出现了问题

**Screenshots**
打包vant UI组件没有自动添加-webkie兼容前缀，导致ios8版本ui排版以及加载框和弹窗出现了问题

**Environment**
 -vue 打包时发现ui组件中的css样式没有浏览器兼容前缀，是不是哪些地方没有配置呢？

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/1257
