### ISSUE TITLE
Vant 用户小调查 「powered by vant」

### ISSUE THREAD

**Issue by chenjiahan** [youzan/vant#1582]
非常感谢大家对 Vant 的支持，如果贵司在生产环境中使用 Vant，欢迎在本 issue 中留下公司或产品名😆

如果可以的话，请提供以下信息：
```
- 公司名
- 公司 Logo
- 公司网站 or 产品链接
```

**Comment by chenjiahan** [comment]
先抛砖引玉^_^

---

公司：有赞
官网：https://www.youzan.com/
在使用 Vant 的产品：有赞微商城，有赞零售，有赞美业等

<img src="https://avatars2.githubusercontent.com/u/11404085?s=200&v=4" width="100" height="100" >

**Comment by chaituan** [comment]
微旅游（demo）
网址：http://lv.chaituans.com/mobile/home.html
![q10](https://user-images.githubusercontent.com/26025563/43586549-7f9ac398-969a-11e8-8e6d-de567301c2ca.png)

**Comment by dzcms** [comment]
信阳长远科技开发有限公司
官网：[](http://www.chang-yuan.com)
![4189761](https://user-images.githubusercontent.com/4189761/43644316-eaa89162-9760-11e8-8b9c-3807ea64cffe.jpg)

在使用 Vant 的产品

- [北京家政公司](http://bj.vcong.cn)
- [信阳文化中心](http://piao.vcong.cn)

**Comment by zaxlct** [comment]
## 矿云科技
官网：https://k.2l.cn
新路由三一站式监工托管平台
![LOGO](https://user-images.githubusercontent.com/14342431/43875162-1323e83e-9bc2-11e8-9e35-f7b2e08727f7.png)

### 在使用 Vant 的产品
- [矿云移动端](https://m.2l.cn)
![二维码](https://ws4.sinaimg.cn/large/006tNbRwgy1fu39gghfodj307s07sdfl.jpg)

**Comment by readyou** [comment]
**水滴互助**

官网：http://www.shuidihuzhu.com/

在使用 Vant 产品:

竹子好课后台

**Comment by xland** [comment]
衡水浩伦科技有限公司
产品还没上线

**Comment by LIAOTOW** [comment]
> [](http://www.shuidihuzhu.com/)
> 
> 在使用 Vant 产品:



> **水滴互助**
> 
> 官网：http://www.shuidihuzhu.com/
> 
> 在使用 Vant 产品:
> 
> 竹子好课后台

scoped属性慎用

**Comment by 1215708470** [comment]
微信小程序，巴巴腾儿童机器人

**Comment by ialmost** [comment]
### 腾飞网络
暂无官网
#### 在使用 Vant 的产品
* [好免街](http://www.haomianjie.com)

## 期待小程序版本的 Vant 能尽快跟上 Vue 版，下一个项目打算用 Vant Weapp

**Comment by zhangchao828** [comment]
发现vant一直在维护，star也慢慢稳步增长，不知道会不会一直维护下去，在观察中，准备下个项目使用

**Comment by chenjiahan** [comment]
@zhangchao828 会一直维护下去，请问明显的 bug 是指什么呢，可以提出来

**Comment by ialmost** [comment]
> 发现vant一直在维护，star也慢慢稳步增长，但是有好些明显的bug没有处理，不知道会不会一直维护下去，在观察中，准备下个项目使用

整个项目做完，1.4.8这个版本没有发现什么明显BUG

**Comment by budflower** [comment]
长级到1.5版本后，为什么TreeSelect还有ImagePrieview都用不了，出现一堆的错误，这是啥原因？

**Comment by chenjiahan** [comment]
@budflower 提问请新建 issue

**Comment by bolechen** [comment]
新做了一个基于有赞的社交电商系统，用 Vant 再好不过了，哈哈
扫码可以体验
![img_2061](https://user-images.githubusercontent.com/195015/50725543-f0118980-1139-11e9-8f70-f1160407e572.JPG)

**Comment by ZhengXiaowei** [comment]
@ialmost 之前ios有成功聚焦，但是在ios聚焦的时候 会出现内容容器无法撑开 只有到键盘弹出那个位置的高度的问题（部分ios机型会这样，其他的会正常，苦于项目着急上线，之后没去怎么优化）

**Comment by ialmost** [comment]
> @ialmost 之前ios有成功聚焦，但是在ios聚焦的时候 会出现内容容器无法撑开 只有到键盘弹出那个位置的高度的问题（部分ios机型会这样，其他的会正常，苦于项目着急上线，之后没去怎么优化）

这一块，我之前也是做成了一个通用页面来跳转实现，并且按照 vant 的 api 来自动聚焦，但是 ios 不再支持这种体验了，只能通过用户在当前页触发事件才能聚焦，所以我现在把搜索这一块直接集成到了需要使用到的页面，用show来实现，暂时也没有想到其它的好办法

**Comment by lwpassvoice** [comment]
做了个表情包相关小程序，用了vant
![_20190125142111](https://user-images.githubusercontent.com/22510735/51729225-bd5e0f80-20ad-11e9-9381-2bc0416df919.jpg)

**Comment by xiaoxintang** [comment]
> 先抛砖引玉 ^_^
> 
> ### 有赞
> 官网：https://www.youzan.com
> 
> <img alt="" width="32" height="32" src="https://camo.githubusercontent.com/a562f33a0d560c2f3e2e73027bb9938ebd8030c6/68747470733a2f2f696d672e797a63646e2e636e2f7075626c69635f66696c65732f323031372f30322f30392f65383461613863626266373835323638386338363231386331663362626631372e706e67">
> 
> #### 在使用 Vant 的产品
> * 有赞微商城
> * 有赞零售
> * 有赞美业
> * ...

请问贵公司所提供的产品中哪里使用了vant?搜索页面中好像没有van相关样式

**Comment by chenjiahan** [comment]
@xiaoxintang 移动端的页面都是

**Comment by xiaojia21190** [comment]
垃圾水滴互助 @readyou 狗玩意公司，别出来逼逼了

**Comment by zzyseven** [comment]
环形进度条的旋转中心点貌似不对，应该是transform-origin:50% 50%才对,今天调试这个问题弄了好久

**Comment by chenjiahan** [comment]
@zzyseven 有问题请单独提 issue

**Comment by inlics** [comment]
个人站长，准备入坑

**Comment by ilofxyt123** [comment]
嘉兴宝骏信息科技有限公司
![logo](https://user-images.githubusercontent.com/19810169/53947730-4e8ac200-4101-11e9-839c-8379fb678ed8.png)

微信公众号：马上办卡

公众号首页链接：https://91k.91kab.com/oauth/index4

**Comment by jasconchen** [comment]
建议Toast组件增加onClose回调函数

**Comment by DaDaDaDaDaBocai** [comment]
猎宝网络科技股份有限公司

官网：https://www.7881.com
[](url)
在使用 Vant 的产品
[m.7881.com](url)
...

**Comment by DaDaDaDaDaBocai** [comment]
> <h3>江苏猎宝网络科技股份有限公司</h3>**
> 
> 官网：https://www.7881.com
> 
> ![logo](https://user-images.githubusercontent.com/25682361/55210911-a4481b00-5224-11e9-82f0-9dc00428ec8a.png)
> 
>  <h4>在使用 Vant 的产品 <h4>
> [m.7881.com](url)
> ...

****

**Comment by RinaDad** [comment]
**南京轻速云信息科技有限公司**
官网：[https://www.qingsuyun.com](https://www.qingsuyun.com)
![image](https://user-images.githubusercontent.com/36993759/57455528-e5106680-729d-11e9-95d8-362fecfceb05.png)

**在使用 Vant 的产品：**
在线考试系统 
学员手机端 [https://www.qingsuyun.com/h5/m/](https://www.qingsuyun.com/h5/m/)
手机管理端 [https://www.qingsuyun.com/site/m/](https://www.qingsuyun.com/site/m/)
