### ISSUE TITLE
Low android version compatibility issues

### ISSUE THREAD

**Issue by CrazyProgrammer12138** [youzan/vant#1585]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Low android version compatibility issues, HUAWEI the Version is 4.4

**Screenshots**
Add screenshots to help explain your problem.
![500610785452044951](https://user-images.githubusercontent.com/29749377/43625222-6bdecd2a-971e-11e8-8a82-6d07e126bb15.jpg)

**Environment**
 - Device: HUAWEI
 - Browser: 
 - Vant Version: 1.1.16

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
建议检查下你的项目 autoprefixer 配置是否移除了一些 css 前缀
