### ISSUE TITLE
[Feature Request] List Scroll Top / List滚动至顶事件

### ISSUE THREAD

**Issue by LynanBreeze** [youzan/vant#1592]
**What problem does this feature solve?**
当list滚动至顶部时，触发事件。
actions actived when scroll ‘vant list’ to top

**Describe the solution you'd like**
场景：例如聊天窗口这种，通常我们是从最底部开始往上滑的，滑至顶部可以触发事件加载云端的记录。
To load more historical data

**What does the proposed API look like?**
@action="method()"

**Comment by chenjiahan** [comment]
后续支持~

**Comment by chuckyo** [comment]
```math

**Comment by chenjiahan** [comment]
这个需求拖延症了很久😂主要是没考虑好 API 怎么设计。
现在在 1.6.17 版本加了 direction 属性，可以指定滚动方向为顶部，应该能满足需求

**Comment by gm-fire** [comment]
> 这个需求拖延症了很久😂主要是没考虑好 API 怎么设计。
> 现在在 1.6.17 版本加了 direction 属性，可以指定滚动方向为顶部，应该能满足需求

大佬能否给个示例,现在遇到滚动到顶部会一直触发@load

**Comment by k186** [comment]
> > 这个需求拖延症了很久😂主要是没考虑好 API 怎么设计。
> > 现在在 1.6.17 版本加了 direction 属性，可以指定滚动方向为顶部，应该能满足需求
> 
> 现在的情景是和微信对话窗口一样的历史记录获取效果,direction="up"后获取的到的数据是unshift 到 list 上的,但是页面无非保持ajax请求时候的高度.导致一直触发@load

创建一个空白的 节点 让他高度无限高，加载完第一屏吧这个div v-if 干掉 然后滚动容器 在请求后 让他 滚动出 offset 的高度就可以了
