### ISSUE TITLE
upload到底怎么使用啊,怎么把得到的参数替换掉默认图片的路径呢?

### ISSUE THREAD

**Issue by zhou2811** [youzan/vant#1596]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
上传图片后会得到一个 
File 对象，你可以把对象 log 出来看一下，里面有图片文件对应的一些属性
