### ISSUE TITLE
单元格组件的border-bottom随机性的消失

### ISSUE THREAD

**Issue by NeverMore-KL** [youzan/vant#1597]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在安卓机的uc浏览器 微信内置浏览器中,使用单元格组件的时候下边框随机消失.

**Screenshots**
![766f44f6dfcb9c1ae7e38514e7ed05dd](https://user-images.githubusercontent.com/25167742/43702117-3ed68024-998b-11e8-8299-9eb87a28b677.jpg)

**Environment**
 - Device: 安卓机
 - Browser: uc浏览器 微信浏览器
 - Vant Version: 1.1.12

**Reproduce**
see pic

**Comment by LynanBreeze** [comment]
同有这个问题。

**Comment by ffeif** [comment]
安卓机器，微信浏览器也有这问题

**Comment by GodStream** [comment]
我这边也遇到安卓机出现此问题

**Comment by chenjiahan** [comment]
暂时没有复现这个问题呢，可能是低端机的渲染问题

**Comment by superliyy** [comment]
安卓机的谷歌浏览器也会出现这个问题，跪求大神解决下呀
