### ISSUE TITLE
ImagePreview最新版本v1.1.15 预览图片报错

### ISSUE THREAD

**Issue by xiaobingMa** [youzan/vant#1598]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
今天下载最新vant, 预览图片就报一下错误
实现场景就是一般的商品详情图片预览，没有更新vant的同事都是完好的
现在我怀疑是版本问题,其他同事没更新都是正确的

**Screenshots**
![image](https://user-images.githubusercontent.com/28527661/43702071-202449cc-998b-11e8-8537-126475871435.png)
![image](https://user-images.githubusercontent.com/28527661/43702180-80e3bfea-998b-11e8-8ccb-732259b6c68f.png)

**Environment**
 - Device: 
 - Browser: chrome
 - Vant Version: 1.1.15

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
麻烦给一下 jsfiddle
