### ISSUE TITLE
ios8 微信6.5环境下Dialog兼容性问题

### ISSUE THREAD

**Issue by wuxn** [youzan/vant#1602]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
1、手机系统是iOS8，微信版本是6.5；
2、在微信公众号中使用Vue的vant组件库；
3、使用Dialog组件不兼容这个环境，问题是：弹出框会错位右移（大概右移弹出框的一半左右）；

**Screenshots**
因为用的是同事的手机，所以现在暂时不方便再次借用，但是问题确定一定以及肯定是存在。为此我换了原生的弹出框。

**Environment**
 - Device: iPhone
 - Browser: 微信内置浏览器
 - Vant Version: 1.1.8

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
建议检查下是不是你的项目配置中有 autoprefixer，移除了一些 webkit 前缀导致此问题

**Comment by wuxn** [comment]
是我这边配置的问题，谢谢啦~~~

**Comment by wuxn** [comment]
@chenjiahan 是我这边配置的问题，谢谢啦~~~

**Comment by adminljc** [comment]
@wuxn 我这边也遇到同样的问题，请问具体是什么配置导致的？

**Comment by adminljc** [comment]
@wuxn 我找到那个配置了，问题已解决。是package.json文件里的
"browserslist": [
    "> 1%",
    "last 7 versions",
    "not ie <= 8",
    "ios >= 8",
    "android >= 4.0"
  ],

**Comment by wuxn** [comment]
> @wuxn 我找到那个配置了，问题已解决。是package.json文件里的
> "browserslist": [
> "> 1%",
> "last 7 versions",
> "not ie <= 8",
> "ios >= 8",
> "android >= 4.0"
> ],

嗯嗯嗯，我刚看到，就是酱解决哒~~~
