### ISSUE TITLE
van-icon size属性如何使用？

### ISSUE THREAD

**Issue by Pineapple86** [youzan/vant#1604]
**Describe the bug**
vant 1.1.15出来的新特性：van-icon size属性如何使用？

官方doc只有size，但是没有可选项

**Screenshots**
![image](https://user-images.githubusercontent.com/15771380/43761721-761ad3be-9a58-11e8-8157-5be3017a07af.png)

**Comment by chenjiahan** [comment]
比如 '20px' `100%`，后续会在文档里备注

**Comment by bert1100** [comment]
@chenjiahan  van-icon 中的size属性似乎不能正常工作，见下图
![image](https://user-images.githubusercontent.com/189849/44130398-e34094d8-a07f-11e8-8ffb-0cadbd839b4f.png)

**Comment by chenjiahan** [comment]
@bert1100 这里确实犯了一个比较低级的错误，会在下个版本修复

**Comment by Pineapple86** [comment]
是的，CSS里并没有size这个属性呀。期待早点修复，我现在正需要这个功能呢^_^

**Comment by chenjiahan** [comment]
已在 1.2.0 版本修复
