### ISSUE TITLE
报错: Can't resolve 'postcss-loader' 

### ISSUE THREAD

**Issue by tuoxie15** [youzan/vant#1605]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
报错：ERROR in ./node_modules/vant/es/icon/style/index.js
Module not found: Error: Can't resolve 'postcss-loader'
问题：使用vant组件就直接报错，postcss.config.js里面配置了自动转rem，尝试照着官网的配置autoprefixer & postcss-pxtorem，同样不行，感觉是webpack转换的问题...使用mint-ui没发现此问题
vue文件:
```
import { Cell, CellGroup, Icon } from 'vant'
export default {
  components: {
    [Cell.name]: Cell,
    [CellGroup.name]: CellGroup,
    [Icon.name]: Icon
  }
}
```

```
postcss.config：
module.exports = {
  plugins: [
    require('postcss-px2rem')({
      remUnit: 37.5, 
      unitPrecision: 5,
      propList: ['*'], 
      selectorBlackList: [], 
      replace: true,
      mediaQuery: false,
      minPixelValue: 12
    })
  ]
}
```

**Environment**
 - Device: chrome
 - Browser: 浏览器
 - Vant Version: 67.0.3396.99

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
建议看下你的 webpack 里面是否正确配置了 `postcss-loader`
