### ISSUE TITLE
Area组件可否兼容父子关系类别的地址或者分类结构

### ISSUE THREAD

**Issue by jiangtiger** [youzan/vant#1607]
目前的Area组件数据格式很死，只能通过固定的格式使用，然而我相信地址编码结构很多人都是使用父子结构的而不是使用行政规划来做的，如果可以兼容父子结构，这个Area组件也可以在其他的方面使用，希望开发大大能够考虑一下

**Comment by chenjiahan** [comment]
这个确实是一个优化点~ 不过暂时没有精力来做这个，可以帮忙提个 PR 喔
