### ISSUE TITLE
Custom Swipe Item's width/ SwipeItem的自定义宽度支持

### ISSUE THREAD

**Issue by LynanBreeze** [youzan/vant#1609]
**What problem does this feature solve?**
现在的Swipe是宽度100%进行轮播。
希望能够自定义轮播项宽度，类似下图的效果。
Custom swipe item's width needed.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/24271362/43827984-d815ba2c-9b2d-11e8-8386-a61716f8cc76.png)

**What does the proposed API look like?**
新增宽度属性。
width attribute needed.

（轮子已经很多了，不想再造了。捂脸 (-ω- ) ）

**Comment by chenjiahan** [comment]
暂时没有计划支持呢~ 如果需要这种复杂的 Swipe，建议去用第三方的组件
