### ISSUE TITLE
DatetimePicker的formatter失效

### ISSUE THREAD

**Issue by liupei1995** [youzan/vant#1610]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/
![2018-08-09_085926](https://user-images.githubusercontent.com/21356797/43872146-cd909c54-9bb2-11e8-8bd0-b09849fa7e3e.png)
![2018-08-09_085945](https://user-images.githubusercontent.com/21356797/43872150-d14b6c20-9bb2-11e8-8fdb-2c5c4c7d6eab.png)
![2018-08-09_090009](https://user-images.githubusercontent.com/21356797/43872178-e7bb5f42-9bb2-11e8-8403-d2c352390b28.png)

如图所示，设置了formatter，但是显示效果还是没加上

**Comment by chenjiahan** [comment]
请升级到最新版本再试
