### ISSUE TITLE
Tabs line 初始时错位

### ISSUE THREAD

**Issue by banxi1988** [youzan/vant#1612]
**Describe the bug**
Tab line 初始时错位

**Screenshots**
![image](https://user-images.githubusercontent.com/726774/43886862-a0d3294c-9bef-11e8-9685-148bdf790876.png)

**Environment**
 - Device: 
 - Browser:  Chrome 
 - Vant Version: 1.1.14

**Reproduce**
尝试在其他地方重现但是没得。

相关代码如下：

```vue
<template>
  <van-tabs class="moment-tabs"
    v-model="tabIndex"
    ref="tab"
    :line-width="48"
    sticky>
    <van-tab v-for="tab in momentTabs"
      :key="tab.value"
      :title="tab.title">
      <moment-list :moment-tab="tab.value" />
    </van-tab>
  </van-tabs>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { VuePage } from "@/common-services/vue-page";
import MomentList from "@/components/moment/MomentList.vue";
import { MomentTab } from "@/services/moment";

@Component({
  components: {
    MomentList
  }
})
export default class MomentTabView extends VuePage implements vet.VueLifecycle {
  tabIndex = 0;
  momentTabs: any[] = [];
  mounted() {
    this.momentTabs = [
      { title: "", value: MomentTab.follow },
      { title: "热门", value: MomentTab.hot }
    ];
    setTimeout(() => {
      this.momentTabs[0].title = "关注";
      (this.$refs.tab as any).setLine();
    }, 100);
  }
}
</script>
<style lang="less" scoped>
.page-body {
  background: #fafafa;
}
.moment-tabs {
  /deep/ .van-tabs__nav {
    width: 96px;
    margin: 0 auto;
  }
  /deep/ .van-tabs__wrap {
    background: rgb(248, 248, 248);
  }
  /deep/ .van-tab {
    background: rgb(248, 248, 248);
    font-size: 17px;
    color: #444;
  }
}
</style>

```

做了不少尝试，比如在 mounted 再给一个 `setTimeout` 中再更新标题，然后调用 `setLine`。
比如本来 van-tab 没有用 v-for 用 v-for 是想尽量延迟绑定。

用 Chrome 查看，初始的 van-tab__line 的内联样式如下：

```css
width: 48px; transform: translateX(-24px); transition-duration: 0.2s;
```
但是正常的应该是 
```css
transform:translateX(0px); 
```

看了一下源代码的计算逻辑。

```js
const tab = this.$refs.tabs[this.curActive];
        const width = this.lineWidth || tab.offsetWidth;
        const left = tab.offsetLeft + (tab.offsetWidth - width) / 2;
```
估计是因为初始时 tab.offsetLeft = 0 及 tab.offsetWidth = 0 这样值会变成 -24px.

但是此时我用 Chrome 得到元素的 offsetWidth 为 48.

![image](https://user-images.githubusercontent.com/726774/43888730-f2b4a380-9bf4-11e8-98b2-16c07f8682d5.png)

暂时没有头绪看要怎么调试这个问题了。 希望得到点帮助，谢谢。

**Comment by banxi1988** [comment]
也许这个问题根这整个 MomentTab 组件是在另一个  tabbar 的一个标签页中有关。

```
      <div class="tab-content"
        v-show="activeTab == 1">
        <moment-tab />
      </div>
```
这里用的是 `v-show` 也就是说，可能是在 moment-tab mounted 的时候由于这个标签页并没有显示。
所以此时 offsetWidth 是为0的。

于是我想了个办法。

1. 给组件加上引用。

```ts
      <div class="tab-content"
        v-show="activeTab == 1">
        <moment-tab ref="moment-tab" />
      </div>
```

2. 当点击对应的 tabbar item 时，再调用更新方法。

```ts
  onTapMoment() {
    this.activeTab = 1;
    (this.$refs["moment-tab"] as any).updateTabLine();
  }
```

这样就 OK 了。

不知道还有没有更好的做法。 还是我这里 tabbar 的使用不合理。

如果没有更好的解法的话，我稍后再关闭此问题。

**Comment by ialmost** [comment]
`<van-tabs
        type="line"
        line-width="0"
      >`
当我这样设置line-width为0时，虽然有效，但是控制台报错： Invalid prop: type check failed for prop "lineWidth". Expected Number, got String.
`<van-tabs
        type="line"
        :line-width="0"
      >`
当我给line-width加上绑定修饰符后，props中的0变成了Number类型，但是这个效果不会生效，请问如何解决

**Comment by banxi1988** [comment]
@ialmost 这个道理其实很简单。
首先 `:line-width="1"` 这样写才是正常的因为 lineWidth 是 Number 类型。所以得使用 `v-bind` 语法。

另外你说的设置成 `0` 不生效。这个其实很好理解。因为它的源代码是这样的。

`const width = this.lineWidth || tab.offsetWidth;`
当 `this.lineWidth === 0` 时。它是一个 `false` 的值，这样当设置为0 时其实取的是  `tab.offsetWidth`
如果你是不想显示低部的 line 的话，你可以尝试设置一个非0值。比如 0.0001 这样。 来绕过这个判断。

**Comment by ialmost** [comment]
当时我也看到这句源码了，但完全没想到是类型被转换了，你一点拔立马反应过来了，多谢🙏

**Comment by chenjiahan** [comment]
这个问题出现的原因是 Tab 一开始处于 hidden 状态，获取不到元素宽度。
比较合适的解决方法是延迟这个组件的渲染，通过 v-if 控制，在组件首次 display 时再进行渲染

**Comment by banxi1988** [comment]
@chenjiahan 那看来是我使用上的一个问题了。像我上面在显示后调用  `setLine` 算是比较正确的做法，那可以关闭此 issue 了。
