### ISSUE TITLE
折叠面板组件在IOS9.3中的交互问题

### ISSUE THREAD

**Issue by feng138168** [youzan/vant#1617]
**Describe the bug**
折叠面板组件在IOS9.3中，点击展开折叠面板，出现内容先展开，然后收缩，然后再展开的情况

**Screenshots**

**Environment**
 - Device: IOS9.3 
 - Browser: 微信浏览器；safari
 - Vant Version: 1.1.16

**Reproduce**

**Comment by chenjiahan** [comment]
能否提供一下视频？ 其他版本的 iOS 系统能复现吗

**Comment by feng138168** [comment]
@chenjiahan 留一个邮箱？我把视频发给你

**Comment by feng138168** [comment]
@chenjiahan 只有ios9的版本有这个问题

**Comment by feng138168** [comment]
发了，注意查收 @chenjiahan

**Comment by chenjiahan** [comment]
视频已收到，但是没有环境复现这个问题，issue 先关闭了，如果可以的话，请帮忙定位一下这个问题~

**Comment by sideFlower** [comment]
我今天也遇到这个问题了， 也是ios9，  点击关闭状态的 折叠面板 
先展开 ---》 再收缩 --- 》 在展开

@chenjiahan

**Comment by sideFlower** [comment]
1.6.14 和2.1.4  在ios9.3上 都会有这个问题

**Comment by chenjiahan** [comment]
@sideFlower 可以自行调试下，我这没有复现环境
