### ISSUE TITLE
Swipe 组建的分页按钮不支持自定义颜色，希望可以加一个属性，用来控制分页按钮的颜色

### ISSUE THREAD

**Issue by 744521168** [youzan/vant#1619]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
这里直接覆盖样式就好
