### ISSUE TITLE
为什么我的Actionsheet select事件不触发

### ISSUE THREAD

**Issue by liufeisprit** [youzan/vant#1623]
![image](https://user-images.githubusercontent.com/25600325/44028586-e6f6a62a-9f2c-11e8-83b8-8127868a9e2f.png)
把文档的例子复制下来试了一遍 还是没触发事件 不知道为什么啊 写的和demo一模一样 求解答 谢谢

**Comment by liufeisprit** [comment]
![image](https://user-images.githubusercontent.com/25600325/44028659-1f9445b4-9f2d-11e8-94aa-3df980f9a0ee.png)

**Comment by chenjiahan** [comment]
请升级 vant 到最新版再试
