### ISSUE TITLE
van-stepper iOS8下无法正常使用

### ISSUE THREAD

**Issue by wikimo** [youzan/vant#1633]
**问题描述**
在iOS8下van-stepper组件无法正常使用。

**参考截图**
http://p20japdoe.bkt.clouddn.com/20180815153432148358592.png

**测试环境**
 - Device: iPhone6 iOS8.3
 - Browser:  Safari
 - Vant Version:  1.1.13

**Comment by chenjiahan** [comment]
具体问题是？

**Comment by wikimo** [comment]
@chenjiahan iOS8下，van-stepper组件无法正常使用，如截图那样报错了，控件显示不了，未使用该组件时，默认加减商品数1没有问题。不知这么描述能理解了么？

**Comment by chenjiahan** [comment]
截图里面没有任何有用的信息，没法定位呀

**Comment by wikimo** [comment]
```Javascript
<van-stepper
    class="van-sku__stepper"
    v-model="selectedNum"
    integer
    :step="setStep(props.selectedSkuComb.s1)"
    :min="setStep(props.selectedSkuComb.s1)"
    :max="sku.stock_num"
    :disable-input="false"
    @blur="checkNum(props.selectedSkuComb.s1)"
  ></van-stepper>
```
在<van-sku />中内嵌使用<van-stepper/>组件就会报截图错误，使用环境iOS8.3下，移除该组件可正常使用<van-sku />组件。

也可以使用https://youzan.github.io/vant/#/zh-CN/stepper在iOS8.3 Safari下无法使用。

@chenjiahan 谢谢

**Comment by wikimo** [comment]
自行修复了，发现库存0的时候会报错，我们的情况是这样的。 @chenjiahan

**Comment by chenjiahan** [comment]
@wikimo 可以提个 pr 吗

**Comment by wikimo** [comment]
没有从前端修复，后端改了API返回数据。不知 http://p20japdoe.bkt.clouddn.com/20180919153728996173404.png  这个错误信息是否能协助排查。主要是这个sku.js  sku.stock_num=0时，就会报错，组件无法弹出。能不能组件仍然弹出，但给到一个友好的提示。 @chenjiahan

**Comment by chenjiahan** [comment]
看了下截图应该是你直接访问 selectedSkuComb.si 时报错了，不是组件内部的报错，建议加个空值判断

**Comment by wikimo** [comment]
是的，补充下问题，selectedSkuComb使用不当引起的，如果遇到类似问题，仔细阅读下这个地方，很有可能selectedSkuComb初始化错误引起的。
