### ISSUE TITLE
list 滚动到底部加载更多，你们目前是使用body的滚动条判断高度，但是我局部div使用list组件的时候就无法使用了

### ISSUE THREAD

**Issue by zicong-zhang** [youzan/vant#1638]
如题

你们目前是使用body的滚动条判断高度，但是我局部div使用list组件的时候就无法使用了
不适用局部滚动加载更多的场景

**Comment by chenjiahan** [comment]
List 支持局部滚动的，并没有取 body 的滚动条，具体可看源码
