### ISSUE TITLE
Vant 在开发过程中没有用热替换吗？npm run dev 后修改代码需要刷新才能生效。坐等回复！

### ISSUE THREAD

**Issue by dficonfont** [youzan/vant#1641]
**Describe the bug**
vant 的代码结构看起来不错，想要修改一些组件发现没有热替换，能不能热替换来提高效率？
clone 到本地 npm run dev 修改 packages 下的组件不能热替换。需要刷新才能看到修改。

麻烦解答一下我的疑惑，谢谢！

**Environment**
 - Device: macOS 10.13
 - Browser: opera
 - Vant Version: 最新
 - NodeJS: v8.11.2

坐等回复！

**Comment by chenjiahan** [comment]
感谢反馈，已经优化热替换的配置，参见 [https://github.com/youzan/vant/pull/1649](https://github.com/youzan/vant/pull/1649)

不过在 iframe 下还是会偶尔不生效，可以切换到 chrome 手机模式进行开发
