### ISSUE TITLE
BUG：点击Popup弹窗频繁报错$attr is readonly、$listener is readonly等

### ISSUE THREAD

**Issue by LLily7** [youzan/vant#1642]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
点击弹窗频繁报错$attr is readonly、$listener is readonly等，之前一直是好的，就是今天打开突然就这样了。没有更改任何内容。求解～

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: mac
 - Browser: chrome
 - Vant Version: 1.1.15

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by LLily7** [comment]
根进：打包后的文件是正常的。但打包前使用poup依然频繁报错，

**Comment by LLily7** [comment]
跟进：是我的锅，自己找到原因了。在所有页面引入Vue都是写import Vue from 'vue',但是在某个页面我写成了import Vue from 'Vue'。太粗心了！！给其他马大哈参考

**Comment by chenjiahan** [comment]
哈哈，找到原因就好
