### ISSUE TITLE
用CDN引用vant, Toast无法使用

### ISSUE THREAD

**Issue by 515783034** [youzan/vant#1646]
**Describe the bug**
如题，使用CDN引用vant，无法使用Toast组件，其他组件正常。

**Screenshots**
抱歉，上传图片一直失败
onClickHis() {
      Toast('按钮');
}

ReferenceError: Toast is not defined
    at hn.onClickHis ((index):216)
    at o.i (vue:6)
    at o.cn.$emit (vue:6)
    at click (vant.min.js:7)
    at i (vue:6)
    at HTMLDivElement.Rr.t._withTask.o._withTask (vue:6)

**Environment**
 - Device: macOS
 - Browser: safari
 - Vant Version: v1.1.16

**Reproduce**
必现

**Comment by chenjiahan** [comment]
vant.Toast

**Comment by 515783034** [comment]
感谢感谢！问题已解决

**Comment by plqin-xiaohao** [comment]
👍 
mark : cdn 下使用 toast , cdn 下使用 组件
