### ISSUE TITLE
需要一个可以设置Radio图标的功能

### ISSUE THREAD

**Issue by lszh25229** [youzan/vant#1647]
需要一个可以设置Radio图标的功能，所有Radio都使用一个图标辨识度比较低，尤其是在一个选项比较多的页面中。
项目中设置项比较多的话都会用到这个功能。现在改了源码，但是升级就不方便了。
感谢作者开发出这么好的组件库。

**Comment by chenjiahan** [comment]
重复 issue，请移步 https://github.com/youzan/vant/issues/1567，后续会支持这个功能
