### ISSUE TITLE
预览大图不能实现预览指定位置图片

### ISSUE THREAD

**Issue by superJinx** [youzan/vant#1651]
`ImagePreview({
images: ["https://img.yzcdn.cn/upload_files/2017/03/15/FkubrzN7AgGwLlTeb1E89-T_ZjBg.png", "https://img.yzcdn.cn/upload_files/2017/03/14/FmTPs0SeyQaAOSK1rRe1sL8RcwSY.jpeg"],
startPosition: 1,
 });`

按照文档格式传入配置对象，编写报错

**Comment by LynanBreeze** [comment]
我有在项目里用到这个
```
preview(index) {
      ImagePreview(this.imgPreviewList, index);
    }
```
imgPreviewList是计算属性，是src组成的数组。点击图片传入index，可以预览

**Comment by superJinx** [comment]
原来是这样用的，哇塞，文档有些误导，多谢指导，万分感谢
