### ISSUE TITLE
dependencies were not found:  * vant/lib/swipe-cell 

### ISSUE THREAD

**Issue by LynanBreeze** [youzan/vant#1657]
**Describe the bug**
import { SwipeCell } from 'vant';

Vue.use(SwipeCell);
引用出现dependencies were not found: * vant/lib/swipe-cell
是不是把这个组件移除了，在node_modules/vant/lib内无此组件。

**Screenshots**

**Environment**
 - Device:  PC Chrome
 - Browser:  lateast X64
 - Vant Version: 1.1.16

**Reproduce**

**Comment by LynanBreeze** [comment]
找到了，lib内还是cell-swipe

**Comment by chenjiahan** [comment]
看更新日志哈，是 1.2.0 版本才改的名字
