### ISSUE TITLE
有关vant-tabs使用better-scroll问题

### ISSUE THREAD

**Issue by mhxy13867806343** [youzan/vant#1658]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在tabs中使用了better-scroll，无法进行滚动（也就是不能进行上拉加载和下拉刷新）

**Screenshots**
![1234](https://user-images.githubusercontent.com/4418166/44332300-55702100-a49e-11e8-855a-a026e950cb28.png)
![2548](https://user-images.githubusercontent.com/4418166/44332476-bac41200-a49e-11e8-9f49-7bb08b0adf2c.png)

可以使用的情况
![1222222](https://user-images.githubusercontent.com/4418166/44332496-c6afd400-a49e-11e8-9546-6bf033e94e1f.png)

不能正常使用的情况
![333333](https://user-images.githubusercontent.com/4418166/44332545-e0e9b200-a49e-11e8-9a0a-20a84087cac6.png)

**Environment**
 - Device: pc端
 - Browser: 谷歌浏览器
 - Vant Version: ^1.1.9版本

**Comment by chenjiahan** [comment]
建议到 better-scroll 仓库下提问，Vant 没有对 better-scroll 做单独适配
