### ISSUE TITLE
vant 引入SwipeCell 滑动单元格报错？

### ISSUE THREAD

**Issue by MrLinwei** [youzan/vant#1662]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by MrLinwei** [comment]
![image](https://user-images.githubusercontent.com/26562857/44396028-3e006900-a56e-11e8-9e67-5c394c6bd365.png)

**Comment by chenjiahan** [comment]
请升级到最新版本再试

**Comment by MrLinwei** [comment]
是引入vant的最新版是吗？

**Comment by chenjiahan** [comment]
是的

**Comment by MrLinwei** [comment]
好的，谢谢
