### ISSUE TITLE
一次性导入所有组件的情况下，能定制主题吗？

### ISSUE THREAD

**Issue by leiwensu** [youzan/vant#1663]
1. 采用引入组件的方式三引入所有的组件，然后尝试定制主题，定制主题失败（无效）
2. 采用引入组件的方式一，使用babel-plugin-import来自动引入样式，定制主题失败（无效）
@chenjiahan 请问大佬，是这两个方式都不支持定制主题吗？只能自己一个一个引入对应的样式才能实现自定义主题？

**Comment by chenjiahan** [comment]
对的，目前自定义主题还不支持通过插件自动引入

**Comment by leiwensu** [comment]
好的，谢谢您的回复。不支持的话就有点麻烦了
