### ISSUE TITLE
ImagePreview 图片预览中传入配置项无法预览

### ISSUE THREAD

**Issue by xiaojinwen** [youzan/vant#1666]
## 问题
ImagePreview 图片预览功能中的 传入配置项
不能达到预览图片效果
预览访问的图片链接数组被逗号连接起来了

![image](https://user-images.githubusercontent.com/23392673/44440163-916bc900-a5f9-11e8-87a9-7bd42069ac0a.png)

## 环境
window 10
vue.js
 "vant": "^1.1.7",

**Comment by VenusPP** [comment]
methods: {
     showImagePreview(imgs,index) {
            ImagePreview(imgs, index )
          }
}
showImagePreview：图片点击预览事件
imgs: 传入的图片数组,
index: 点击每张图片时的索引

**Comment by xiaojinwen** [comment]
可以了  感觉vant的文档得改下 非常感谢
