### ISSUE TITLE
Stepper默认值不能为0

### ISSUE THREAD

**Issue by tielei60** [youzan/vant#1682]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Stepper默认值不能为0

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: moc os
 - Browser: google chrome
 - Vant Version: 1.2.0

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
下个版本修复此问题

**Comment by chenjiahan** [comment]
已在 1.2.1 版本修复
