### ISSUE TITLE
Van-field in custom component

### ISSUE THREAD

**Issue by Julien-Leos** [youzan/vant#1689]
**Describe the bug**
I want to use van-field in a custom component. But I have to replace v-model by v-bind:value and v-on:input. When I try, the value by default is set but when I want to write in the field, I have the error

> "Cannot read property 'value' of undefined" 

**Screenshots**
<img width="1066" alt="capture d ecran 2018-08-24 a 14 06 40" src="https://user-images.githubusercontent.com/34244193/44583871-5e673800-a7a7-11e8-89e7-05d434486200.png">
<img width="1140" alt="capture d ecran 2018-08-24 a 14 07 06" src="https://user-images.githubusercontent.com/34244193/44583875-60c99200-a7a7-11e8-8b2b-3064eb8d3979.png">
<img width="1434" alt="capture d ecran 2018-08-24 a 14 07 20" src="https://user-images.githubusercontent.com/34244193/44583876-632bec00-a7a7-11e8-9f20-1e43717990de.png">

And when I try to write in the field

<img width="647" alt="capture d ecran 2018-08-24 a 14 07 33" src="https://user-images.githubusercontent.com/34244193/44583878-64f5af80-a7a7-11e8-89d6-1ef79216c52c.png">

**Environment**
 - Device: MacBook Pro 2017
 - Browser: Chrome
 - Vant Version: the latest one (I install it Yesterday)

**Reproduce**
Actually, it doesn't make the error, but the code doesn't update the span
https://jsfiddle.net/dfarLdko/287/

**Comment by Zenser** [comment]
I think it is not a bug...
I use your jsfiddle demo, now you can change your code like [https://jsfiddle.net/eywraw8t/300640/](https://jsfiddle.net/eywraw8t/300640/). 
I just change this line:
`$event.target.value` -> `arguments[0]`
Here is the reason:
Vue will compile template
```js
// template
v-on:click="$emit('input', $event.target.value)"
```
to
```js
// in js render function to generate vdom
on: {
   click($event) {
     // now `$event` is just a String
     // so throw error
     return this.$emit('input', $event.target.value)
  }
}
```

**Comment by Julien-Leos** [comment]
Hi @Zenser !

It works ! Thank-you very much, I do not know how I would have done without you.
