### ISSUE TITLE
依据开发指南的指令启动失败

### ISSUE THREAD

**Issue by zxc5800** [youzan/vant#1691]
依据开发指南文档的操作, 克隆了git上的源文件, 先运行了npm run bootstrap, 然后运行了npm run dev, 却不能启动, 以下图片是我控制台的报错信息, 
![image](https://user-images.githubusercontent.com/22065842/44638487-b2615f00-a9e9-11e8-830f-b4f8246990a4.png)
这是我的姿势问题吗, 还是其他什么原因, 第一次写issues, 如果不符合规范的话我后续改正

**Comment by chenjiahan** [comment]
手头没有 windows 环境，所以没法复现这个问题，可以参考下 https://github.com/youzan/vant/issues/176

**Comment by yashonting** [comment]
@zxc5800 @chenjiahan  #在windows环境中生成的docs\src\docs-entry.js中，路径里的‘\’被当成转义字符，需要改build\build-entry.js。跟之前 #176 情况差不多。
![_20180914162840](https://user-images.githubusercontent.com/28426418/45539168-85aba500-b83b-11e8-9db6-445693c45976.png)
