### ISSUE TITLE
Picker 的多级联动无法设置第一列的默认值

### ISSUE THREAD

**Issue by 80sky** [youzan/vant#1695]
Picker 的多级联动无法设置第一列的默认值

<van-picker :columns="columns1" @change="onChange" />
  const citys = {
    '浙江': ['杭州', '宁波', '温州', '嘉兴', '湖州'],
    '福建': ['福州', '厦门', '莆田', '三明', '泉州']
  };
        columns1: [
          {
            values: Object.keys(citys),
            className: 'column1'
          },
          {
            values: citys['福建'],
            className: 'column2',
            defaultIndex: 3
          }
        ],

设置 “福建” 为默认的时候 左边第一列 显示不正确

**Comment by 80sky** [comment]
![image](https://user-images.githubusercontent.com/22342011/44699086-2583d780-aab5-11e8-8229-37e66e5f86fe.png)

如果使用  ref.setValues 是包裹在 popup里面的，初始化的时候不能调用到 refs  无法设置默认值

**Comment by chenjiahan** [comment]
关闭 Popup 的 lazy-render 即可
