### ISSUE TITLE
van-tab组件的tab文字在安卓机不水平垂直居中

### ISSUE THREAD

**Issue by hello-lun** [youzan/vant#1697]
![image](https://user-images.githubusercontent.com/34638158/44649609-fae34180-aa16-11e8-809e-33abc219da30.png)
如上图所示，tab文字在ios是水平垂直居中的，但在安卓机就会不垂直居中了，很多地方都会存在垂直居中不正确的问题

**Comment by chenjiahan** [comment]
未复现这个问题
