### ISSUE TITLE
引入vant base.css为什么后面加了随机参数 

### ISSUE THREAD

**Issue by liufeisprit** [youzan/vant#1702]
![image](https://user-images.githubusercontent.com/25600325/44656450-7e0e9280-aa2b-11e8-89a2-f0e753bdea02.png)
 导致样式出不来呀 
![image](https://user-images.githubusercontent.com/25600325/44656475-8f579f00-aa2b-11e8-8500-17af639e1a15.png)
这样引入的 因为用了vue-cli 3.0 所以在babel.config里面配置的 
![image](https://user-images.githubusercontent.com/25600325/44656502-ab5b4080-aa2b-11e8-9f72-b7929ba516ba.png) 求解！谢谢

**Comment by chenjiahan** [comment]
配置插件后不需要手动引入 base.css
具体可以参考 https://github.com/youzan/vant-demo 这个仓库
