### ISSUE TITLE
优惠券 组件  根据文档  优惠券字段说明  传值  部分字段显示NaN 

### ISSUE THREAD

**Issue by jackycaojiaqi** [youzan/vant#1709]
**Describe the bug**
优惠券组件  根据文档的优惠券字段说明  传值的时候  部分字段显示NaN 

**Screenshots**
显示结果如下图：
![image](https://user-images.githubusercontent.com/10323100/44707614-8e7c4700-aad7-11e8-9c15-f042294d026a.png)
我的数据如下：
![image](https://user-images.githubusercontent.com/10323100/44707622-976d1880-aad7-11e8-8cfe-b29bf2929a02.png)
界面代码如下：
![image](https://user-images.githubusercontent.com/10323100/44707671-bf5c7c00-aad7-11e8-914e-188cb67b1535.png)
data如下：
![image](https://user-images.githubusercontent.com/10323100/44707717-df8c3b00-aad7-11e8-9158-e1e2f7cb1bb5.png)

**Environment**
 - Device:  chrom浏览器
 - Browser:   chrom浏览器
 - Vant Version: 1.2.1

**Reproduce**
按照官方文档 引入 优惠券组件  传数据的时候 ，不显示日期 和 满减数字   但是能显示  满减金额和 优惠券名字。

**Comment by chenjiahan** [comment]
你的截图上是旧版优惠券组件，并不是 1.2.0 之后的版本，请升级一下 vant

**Comment by jackycaojiaqi** [comment]
我用的就是 1.2.1版本的vant 
![image](https://user-images.githubusercontent.com/10323100/44778130-c6a28900-abae-11e8-8e05-4f037bcd7f39.png)
界面我没有完全用你们的组件  我用了 van-tabs +van-coupon-list
![image](https://user-images.githubusercontent.com/10323100/44778172-ecc82900-abae-11e8-940f-19e2bd82fd48.png)
