### ISSUE TITLE
<i>display: inline-block 有一些由字体大小造成的空白，使用calc（100%/3）后一行只有两个元素，第三个元素换行

### ISSUE THREAD

**Issue by vin395685361** [youzan/vant#171]
https://github.com/youzan/vant/blob/64ec6ce5ac8e7809a32fa69faee0b520ab564bd5/packages/vant-css/src/number-keyboard.css#L21

**Comment by vin395685361** [comment]
建议： 在父元素van-number-keyboard上设置 font-size: 0

**Comment by chenjiahan** [comment]
@vin395685361 感谢建议，将在下个版本中修复

**Comment by chenjiahan** [comment]
@vin395685361 vant@0.9.10 中 calc(100%/3) 已经修正为 33.3333%，麻烦确认下是否还存在该问题
