### ISSUE TITLE
官网文档示例有误

### ISSUE THREAD

**Issue by smilefishes** [youzan/vant#1714]
您好，在Vant文档页面的Actionsheet部分有一个错别字。
取消事件应该是 @cancel，但是文档写的是 @calcel 。

`<van-actionsheet
  v-model="show"
  :actions="actions"
  cancel-text="取消"
  @select="onSelect"
  @calcel="onCancel"
/>`

[https://youzan.github.io/vant/#/zh-CN/actionsheet](url)

**Comment by chenjiahan** [comment]
感谢反馈，后续会更正文档
