### ISSUE TITLE
tabs的change事件不触发

### ISSUE THREAD

**Issue by hehuangz** [youzan/vant#1715]
```
 <van-tabs v-model="tabIndex" @click="navMenuFn" @change="navMenuChange" swipeable>
        <van-tab v-for="(classifyitem, index) in classifyList" :title="classifyitem.name" :key="index" >
          <!-- 列表内容 -->
        </van-tab>
  </van-tabs>
```
@change="navMenuChange" 在滑动内容进行tab切换时不触发，请问是什么问题呢？求解

**Comment by chenjiahan** [comment]
未复现这个问题，建议升级 vant 版本再试

**Comment by yonghui666** [comment]
老哥你解决了吗‘我今天也遇到了’

**Comment by chy240030488** [comment]
我也有这个问题

**Comment by miaogulu** [comment]
我今天也遇到了，从其它项切回默认的首项不触发change事件

**Comment by lifangliang-aaa** [comment]
<van-tabs v-model={active} class={!pageData.ellipsis?'tabSubTitle':''} onChange={onChange}>
      {tabList}
  </van-tabs>
change第0个打印不到数据。。。

**Comment by lihuangshuaige** [comment]
> van-tabs v-model={active} onChange={onChange}
> 
> change第0个不触发，后面的都可以触发

我也是这个情况，，咋解决啊

**Comment by lihuangshuaige** [comment]
fuck   第一个tab默认name是0，，，改个name就可以触发了

**Comment by yang1978u** [comment]
第一个tab默认name是0，，，改个name就可以触发了
