### ISSUE TITLE
ImagePreview，当页面较长时，如果在页面底部调用了图片预览，关闭图片预览弹层后，页面会回到顶部

### ISSUE THREAD

**Issue by xlano** [youzan/vant#1718]
问题描述：
当页面较长时，如果在页面底部调用了图片预览，关闭图片预览弹层后，页面会回到顶部。

截图：无

环境：
设备：PC , windows 10
浏览器：chrome 68.0
vue：2.5.2
vant：1.2.0

**Comment by chenjiahan** [comment]
未复现这个问题，建议看下是不是其他原因导致的

**Comment by VenusPP** [comment]
在配置项里添加 lockScroll: false即可
"vant": "^1.6.15"
建议在文档里也写上^_^

**Comment by ZhangNinth** [comment]
是因为ImagePreview在打开时会给body添加overflow:hidden导致的，按照楼上说的添加 lockScroll: false确实可以生效，不再锁定滚动行为，建议这个属性可以加到文档上

> 未复现这个问题，建议看下是不是其他原因导致的
