### ISSUE TITLE
Rate 评分组件能否加一个只读状态

### ISSUE THREAD

**Issue by cn-zx** [youzan/vant#1726]
Rate 评分组件能否加一个只读状态

预计效果是设置好分数后，便不能点击

现在设置disabled后 整体是灰色，设置的分数看不出来了

**Comment by cn-zx** [comment]
好像现在也能实现

**Comment by chenjiahan** [comment]
目前可以通过 `disabled` 和 `disabled-color` 配合实现，下个版本会加个 `readonly` 属性

**Comment by chenjiahan** [comment]
已在 1.3.0 版本支持
