### ISSUE TITLE
在单独引用vue.js和vantUI,发现图片预览功能并没有实现,反而报错404;我使用CDN上面的图片请求同样是这样

### ISSUE THREAD

**Issue by JackingLuo** [youzan/vant#1728]
getBigPic(index){//这是一个事件
		        let arr=[]
		        for(let i = 0;i<this.list.length;i++){
		            arr.push(this.baseUrl+this.list[i].url)//这里是图片拼接的路径
                }
               console.log(arr);//通过打印,这是一个储存了图片地址的数组
                vant.ImagePreview({
                    images:arr,
                    startPosition:index,
                    // onClose() {
                    //     // do something
                    // }
                });
            },
结果是黑色的遮罩层是出现了,但是图片没有显示,通过Network发现请求了这个数组里面所有的url地址栏且报错404
![image](https://user-images.githubusercontent.com/37296875/44851446-e90dd280-ac92-11e8-86ad-ce24d52492ed.png)

**Comment by chenjiahan** [comment]
建议升级 vant 版本后再试
