### ISSUE TITLE
Popup组件与vue-touch结合bug

### ISSUE THREAD

**Issue by DerekYeung** [youzan/vant#1733]
**Describe the bug**
在IOS平台中，当项目中同时使用vue-touch（或其他tap事件处理）与Popup组件时，点击显示Popup会出现显示后立即关闭的情况
具体原因为IOS中的click事件有300ms的延迟，而vue-touch使用的tap事件并无此延迟，导致发生以下场景：
1. @tap事件 => showStatus = true，此时调用了open进行展示
2. 过了300ms之后
3. 触发了@click事件 => showStatus = false，此时Popup被关闭

解决办法：
将modal.$on('click', this.onClick);放置于Modal创建并展示完全之后即可解决此问题
此时流程会变为：
1. @tap事件 => showStatus = true，调用open进行展示
2. 当展示完毕后监听modal的click事件
3. 当用户触发@click事件 => showStatus = false，此时Popup被关闭

在我们的项目中目前使用了自行修改代码的方式来解决该问题，希望官方可以支持并调整，谢谢

另希望vant中也可将click事件替换为tap，这样可以去除300毫秒延迟所带来的滞后感

**Screenshots**
无

**Environment**
 - Device: iphone X
 - Browser: safari
 - Vant Version: 1.2.1

**Reproduce**
无

**Comment by chenjiahan** [comment]
目前 iOS WKWebView 和安卓系统均无点击延迟，因此没有计划再去兼容 tap 事件

**Comment by DerekYeung** [comment]
@chenjiahan 不一定要兼容tap，主要是把click的监听事件放到show之后，主要现在还有很多app里使用的是UIWebview
