### ISSUE TITLE
提供Poptip和Tooltip  气泡提示

### ISSUE THREAD

**Issue by zhuangxiaohui** [youzan/vant#1736]
功能需求类似这个：https://www.iviewui.com/components/poptip

Poptip 与 Tooltip 类似，具有很多相同配置，不同点是 Poptip 以卡片的形式承载了更多的内容，比如链接、表格、按钮等。
Poptip 还 confirm 确认框，与 Modal 不同的是，它会出现在就近元素，相对轻量。

类似需求，类似微信的功能
![1](https://user-images.githubusercontent.com/5791725/44890750-5f034f80-ad0e-11e8-88e2-07a32806ffa8.png)

**Comment by chenjiahan** [comment]
暂无计划支持，可以基于 Popup 实现
