### ISSUE TITLE
PullRefresh 下拉刷新组件问题

### ISSUE THREAD

**Issue by malinadmin** [youzan/vant#1740]
**Describe the bug**
 @使用下拉刷新组件的时候配合list组件当页面只有一条数据的时候下拉刷新会多触发一次导致页面会出现重复数据(数据量多的时候不会出现此情况)
**Screenshots**
![image](https://user-images.githubusercontent.com/21358026/44898152-a3074c00-ad30-11e8-9f9c-b9869cc35060.png)
![image](https://user-images.githubusercontent.com/21358026/44898165-ab5f8700-ad30-11e8-9ce5-814707481b4a.png)
**Environment**
 - maxos: 
 - google: 
 - v70.0.3534.4（正式版本）dev （64 位）:

**Comment by chenjiahan** [comment]
麻烦提供一下 jsfiddle

**Comment by malinadmin** [comment]
@chenjiahan  我的问题，下拉的时候把finished去掉就行了
