### ISSUE TITLE
怎么在数据加载完成前全局使用loading组件啊

### ISSUE THREAD

**Issue by zhou2811** [youzan/vant#1743]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
直接按文档使用就行，和数据加载没有关系

**Comment by zhou2811** [comment]
啊?怎么关闭啊,在数据加载完成后关闭怎么做呢?
