### ISSUE TITLE
最新的vant 升级了 babel 7 如果在nuxt 项目用编译不报错 运行的时候就会报错 这个问题是要怎么解决？

### ISSUE THREAD

**Issue by lubaihong** [youzan/vant#1748]
![image](https://user-images.githubusercontent.com/13359932/44945367-80516200-ae1a-11e8-8a76-a8e2773fa65a.png)

**Comment by chenjiahan** [comment]
1.3.0 在 webpack1 下打包会有问题，下个版本会修复

**Comment by minatocou** [comment]
降级到1.2.1

**Comment by hunghoo** [comment]
亲测降级可行

**Comment by hunghoo** [comment]
@minatocou 亲测可行，多谢

**Comment by chenjiahan** [comment]
已在 1.3.1 版本修复
