### ISSUE TITLE
图片预览组件建议增加手势缩放功能

### ISSUE THREAD

**Issue by cmmer** [youzan/vant#1749]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
可以用手势缩小/放大图片

**Describe the solution you'd like**
用手势缩小/放大图片

**Comment by chenjiahan** [comment]
重复 issue
https://github.com/youzan/vant/issues/1616

**Comment by licairen** [comment]
建议新增手势缩放功能
