### ISSUE TITLE
安卓4.4.4版本，popup右移了50%

### ISSUE THREAD

**Issue by liupei1995** [youzan/vant#1759]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.
![_20180906102901](https://user-images.githubusercontent.com/21356797/45131495-b480a600-b1bf-11e8-9d62-ce41f40a22cc.jpg)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/
在本地run的时候，样式正常
但打包以后popup右移了50%
![_20180906102901](https://user-images.githubusercontent.com/21356797/45131543-f7db1480-b1bf-11e8-8a20-ee93e821abd6.jpg)

**Comment by chenjiahan** [comment]
建议检查下你的 autoprefixer 配置

**Comment by liupei1995** [comment]
我是按照vant文档创建的项目，也需要添加autoprefixer配置吗，我现在看见是不存在css配置的

**Comment by liupei1995** [comment]
@chenjiahan

**Comment by chenjiahan** [comment]
可以参考 vue-cli 的文档

**Comment by VenusPP** [comment]
这是安卓低版本兼容问题
在css中设置样式并覆盖
left: 0
-webkit-transform: translate3d(0,0,0);
transform: translate3d(0%,0,0);

**Comment by VenusPP** [comment]
@liupei1995
