### ISSUE TITLE
vue-cli 3.x 求一套开箱即用的配置

### ISSUE THREAD

**Issue by skyshirt** [youzan/vant#1760]
**What problem does this feature solve?**
升级到vue-cli 3.x，按官方配置，postcss precss3.x 不生效

**Describe the solution you'd like**
基于vue-cli 3.x 建立项目
precss
使用postcss-pxtorem转换rem单位
使用一个variables.css保存全局变量，每个.css和.vue都可以使用，不用@import
都需要哪些依赖
哪些文件里配置

**Environment**
Android > 4 / iOS >= 7
vue-cli 3.0.1
vant 1.3.0
precss 3.1.2

**Comment by Insua** [comment]
co-ask，我主要需求的是rem适配 vue cli 3.0配置 rem适配一直不成功

**Comment by qbob** [comment]
看这个能不能用的上 https://github.com/qbob/vue-startup

**Comment by skyshirt** [comment]
@qbob 十分感谢，但你的推荐并未解决我的问题

**Comment by Xujkstra** [comment]
@skyshirt  在vue.config.js里面配置css.loaderOptions设置

**Comment by skyshirt** [comment]
@Xujkstra 我试过，可是不生效，很苦恼，可以来一份配置好的代码吗

**Comment by js5323** [comment]
文档写的挺清楚的：
使用postcss-pxtorem转换rem单位的配置如下：
```
module.exports = {
  plugins: {
    'autoprefixer': {
      browsers: ['Android >= 4.0', 'iOS >= 7']
    }
    'postcss-pxtorem': {
      rootValue: 37.5,
      propList: ['*']
    }
  }
}
```

**Comment by skyshirt** [comment]
@js5323 非常感谢!

还请教这个配置怎样写呢
使用一个variables.css保存全局变量，每个.css和.vue都可以使用，不用@import

**Comment by js5323** [comment]
@skyshirt  配置写在项目根目录的 postcss.config.js 
vue 文件中的样式和 import 进来的样式都能应用到

**Comment by Insua** [comment]
谢谢，我的问题也解决了
