### ISSUE TITLE
area组件，二级为直辖市时，三级联动没有加载

### ISSUE THREAD

**Issue by millerhamburger** [youzan/vant#1764]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
当二级列表为上海市，天津市的时候，三级列表并没有加载

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.2.0

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/issues/1453 里面已经解答了
