### ISSUE TITLE
时间选择器，选择年份带动月日滑动后，点击确定，获取的时间有误

### ISSUE THREAD

**Issue by webcaoyx** [youzan/vant#1772]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by webcaoyx** [comment]
#时间选择器，选择年份带动月日滑动后，点击确定，获取的时间有误

**Comment by chenjiahan** [comment]
麻烦提供下复现代码

**Comment by DaDaDaDaDaBocai** [comment]
vant 态度好好啊！！！ 已经从VUX坑跳到vant了！

**Comment by chenjiahan** [comment]
@DaDaDaDaDaBocai 哈哈，感谢支持 ^_^
