### ISSUE TITLE
地址编辑组件, 若不需要邮政编码编辑即倒数第二行为"详细地址"时, 详细地址没有下边框

### ISSUE THREAD

**Issue by onjuju** [youzan/vant#1777]
这似乎是为了搜索功能导致的, 详细地址的van-cell被一个div包住, 使得:not(:last-child)没有选中. 而之前的处理方法是给邮政编码加上边框, 如果取消输入邮政编码则会出现这个问题

 - Vant Version: 1.0.15

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复这个问题

**Comment by juice157** [comment]
> 感谢反馈，下个版本会修复这个问题

你好，打扰一下，请问我可以在h5页面单独引入vue的js文件，然后再用cdn引入vant框架可以使用框架里面的组件吗？

**Comment by chenjiahan** [comment]
已在 1.3.2 版本修复
