### ISSUE TITLE
van-hairline消失

### ISSUE THREAD

**Issue by LynanBreeze** [youzan/vant#1778]
**Describe the bug**
A clear description of what the bug is.
自定义的div，使用van-hairline加上底部边框，会出现2格只有一条线的问题。（中间的细到几乎看不见）
div使用flex布局。
问题：固定高度时出现此情况。
当使用自适应高度时，用padding撑开列表项，在单数padding例如（padding: 11px 0;）可正常显示van-hairline, 双数（padding: 12px 0）hairline异常

**Screenshots**
![app fccn cc_8080_ iphone 6_7_8](https://user-images.githubusercontent.com/24271362/45336793-9946d980-b5b7-11e8-92b6-faaebcdef2aa.png)

**Environment**
 - Device:  Chrome latest、iPhone 6/7/8
 - Browser: Chrome, Safari
 - Vant Version: 1.3.0

**Reproduce**

**Comment by chenjiahan** [comment]
这个问题会在下个版本修复

**Comment by chenjiahan** [comment]
已在 1.3.2 版本修复
