### ISSUE TITLE
Add countdown component.建议增加倒计时组件

### ISSUE THREAD

**Issue by youdianfan** [youzan/vant#1779]
It is recommended to add countdown components to the server time.
建议增加倒计时组件，可以传入服务器时间
currentTime - If the current timestamp is not transmitted, the user's local time is obtained by default (the current time of the server is recommended).
currentTime - 当前时间戳,如果不传,默认获取用户本地的时间(建议传服务器的当前时间)
type: Number
required : false
default : ( new Date() ).getTime()

This countdown demand is needed in many electricity suppliers to snap up and spike activities.
这种倒计时需求，在很多电商抢购，秒杀活动都需要用到

An example
一个示例
链接：https://github.com/cgygd/vue2-countdown
[https://github.com/cgygd/vue2-countdown](https://github.com/cgygd/vue2-countdown)

**Comment by youdianfan** [comment]
The reason is that if the user modifies the local time, it will cause the countdown to end ahead of schedule. If the server timestamp is used and a timestamp is passed in by the user himself, then the comparison will not occur. Can the author consider doing so?
原因是这样的,如果用户修改了本地时间,就会造成倒计时提前结束,如果使用服务器时间戳,自己传入一个时间戳,进行对比的话,就不会出现此类问题,作者是否可以考虑一下,这样去做?

**Comment by chenjiahan** [comment]
感谢你的意见，倒计时组件更多是逻辑层的封装，组件 UI 的话比较难抽象出通用性高的组件，所以暂时没有计划加入到组件库中

**Comment by chenjiahan** [comment]
@youdianfan 收到，我们会参考下

**Comment by youdianfan** [comment]
@chenjiahan   谢谢你们回复!
