### ISSUE TITLE
微信支付中使用Toast

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#178]
请问在微信支付的回调函数里可以直接使用Toast('something')或者是Dialog吗？蟹蟹！！

**Comment by pangxie1991** [comment]
可以的，只要引入 Toast 即可。这个和具体在什么回调函数里是无关的~

**Comment by YYQ8023** [comment]
@pangxie1991 蟹蟹，因为微信支付的success函数里访问不到当前vue实例，我的处理是在外面把this赋值给一个变量 vm,然后通过vm.xxx来访问当前实例的一些变量或者方法。按照你的意思是在success里只需要直接Toast('支付成功')就可以是吗？不需要vm.Toast或者是window.Toast什么的是吗？因为是公司项目，所以还是想确认一下，蟹蟹~

**Comment by w91** [comment]
@YYQ8023 只要
```js
import { Toast } from 'vant'
```
后面就可以直接使用Toast('something')。你的问题是你那边不能在那个文件里不能把Toast import进来吗？

**Comment by YYQ8023** [comment]
@w91 可以import，其实我主要问的是微信支付里面，因为开发过程中发现微信支付有很多坑，而且测试必须要部署之后，所以想问一下有没有在微信支付实际开发中测试可用，我等一下自己也测试一下，蟹蟹~~
