### ISSUE TITLE
时间选择器，为什么不能单独展示年份列？加个type='year'可好？

### ISSUE THREAD

**Issue by zicong-zhang** [youzan/vant#1783]
## 有需求是只选择年份的

**Comment by chenjiahan** [comment]
这种情况直接用 Picker 组件就行

**Comment by BrandCai** [comment]
> 这种情况直接用 Picker 组件就行



> ### 时间选择器，为什么不能单独展示年份列？加个type='year'可好？
> ## 有需求是只选择年份的

同意，那你后来是怎么解决这个需求的，用picker组件自己封装的吗

**Comment by BrandCai** [comment]
> ### 时间选择器，为什么不能单独展示年份列？加个type='year'可好？
> ## 有需求是只选择年份的

同意！请问你后来怎么解决你这个需求的，用Picker组件吗？
