### ISSUE TITLE
[TypeScript] dialog 组件 DialogOptions typings 遗漏 'className' 属性

### ISSUE THREAD

**Issue by Jancat** [youzan/vant#1787]
**Describe the bug**
**dialog.d.ts** - `DialogOptions` types:
https://github.com/youzan/vant/blob/dev/types/dialog.d.ts#L4
缺少 `className` 属性声明

Dialog 文档中有 `className` 选项：
https://youzan.github.io/vant/#/zh-CN/dialog

**Comment by chenjiahan** [comment]
感谢反馈，会在下个版本修复

**Comment by chenjiahan** [comment]
已在 1.3.2 版本修复
