### ISSUE TITLE
Toast 文字换行~

### ISSUE THREAD

**Issue by shiyuegongsui** [youzan/vant#1789]
Toast('我是提示文案，建议不超过十五字~');

能否支持文字的换行。

**Comment by chenjiahan** [comment]
支持的

**Comment by shiyuegongsui** [comment]
@chenjiahan  Toast('<p>我是提示文案，</p><p>建议不超过十五字~</p>');  类似这样子~ 两行居中显示~

**Comment by JingYihhh** [comment]
![image](https://user-images.githubusercontent.com/31948533/46244740-052d9c80-c416-11e8-9e86-2857ffe4bdc3.png)
@shiyuegongsui
