### ISSUE TITLE
vue打包时 area.json会被打包到app.js里

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#179]
vue-cli项目，一些工具的版本都是最新的。
然后run build后会发现地址列表会出现在app.xxxxx.js里。

![image](https://user-images.githubusercontent.com/22813922/31367193-2ab4141e-ada8-11e7-86c2-6d8c0aed370f.png)
是我webpack没有配置对吗，还是说一定会打包进去呢。
json文件是这样导入的
![image](https://user-images.githubusercontent.com/22813922/31367207-4ed49850-ada8-11e7-98f1-df7f6ff935a1.png)

**Comment by chenjiahan** [comment]
@YYQ8023 你在代码中 import 了地址列表对应的 json 文件，所以打包进 app.js 是正常现象。建议将引入方式改成异步加载，可以使用 webpack 提供的 require.ensure 或者通过 ajax get json 文件。

**Comment by YYQ8023** [comment]
@chenjiahan 好的我试试，多谢。
