### ISSUE TITLE
field组件clearable问题

### ISSUE THREAD

**Issue by looxii** [youzan/vant#1791]
clearable后，field输入内容点击其他位置后消失。并非官方demo显示在field内容后面出现x按钮可全部清空。请问怎么调整？

**Comment by looxii** [comment]
> talk is cheap(...), show me your code.
> 第一次看到有人有这个问题，请把代码贴上来看一下吧~

<template>
    <div class="login">
        <van-row>
            <van-col offset="1">
                <h2>用户登录</h2>
            </van-col>
        </van-row>
        <van-cell-group class="login-group">
            <van-field label="用户名" label-align="left" required></van-field>
            <van-field label="密码" label-align="left" type="password" required/>
        </van-cell-group>
        <div style="text-align: center">
            <van-button  type="primary" style="width: 80%">登录</van-button>
        </div>
        <div style="position: fixed; bottom: 1rem; width: 100%; text-align: center">
            <small>
                <router-link to="/register">快速注册</router-link>
            </small>
            <small> | </small>
            <small>
                <router-link to="/findpassword">找回密码</router-link>
            </small>
        </div>
    </div>

</template>

<script>
    export default {
        name: "Login"
    }
</script>

<style lang="scss" scoped>
    $margin_h : 0.5rem;
    $margin_w : 1rem;
    .login {
        &-group {
            margin: {
                top: $margin_h;
                bottom: $margin_h
            }
        }

    }
</style>

**Comment by looxii** [comment]
<template>
    <div class="login">
        <van-row>
            <van-col offset="1">
                <h2>用户登录</h2>
            </van-col>
        </van-row>
        <van-cell-group class="login-group">
            <van-field label="用户名" label-align="left" required></van-field>
            <van-field label="密码" label-align="left" type="password" required/>
        </van-cell-group>
        <div style="text-align: center">
            <van-button  type="primary" style="width: 80%">登录</van-button>
        </div>
        <div style="position: fixed; bottom: 1rem; width: 100%; text-align: center">
            <small>
                <router-link to="/register">快速注册</router-link>
            </small>
            <small> | </small>
            <small>
                <router-link to="/findpassword">找回密码</router-link>
            </small>
        </div>
    </div>

</template>

<script>
    export default {
        name: "Login"
    }
</script>

<style lang="scss" scoped>
    $margin_h : 0.5rem;
    $margin_w : 1rem;
    .login {
        &-group {
            margin: {
                top: $margin_h;
                bottom: $margin_h
            }
        }

    }
</style>

**Comment by wuxinabc** [comment]
> clearable后，field输入内容点击其他位置后消失。并非官方demo显示在field内容后面出现x按钮可全部清空。请问怎么调整？

您好，我也遇到这个问题，点击后内容没有清除，请问您找到问题了嘛
