### ISSUE TITLE
tabs粘性吸顶条在ios系统下会出现延迟吸顶的情况

### ISSUE THREAD

**Issue by wangyuan0108** [youzan/vant#1795]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
使用tab组件的sticky属性时在安卓手机上滑动正常,在ios下滑动会出现短暂的消失现象,在ios中滑动时只有当滑动停止时才会吸顶容器

**Screenshots**
问题貌似iOS 的 UIWebview 不会即时触发 scroll 事件，只有用户停止滑动后才会触发。

**Environment**
 - Device: ios
 - Browser: 
 - Vant Version: 1.3.1

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
这个问题确实是 UIWebview scroll 事件未实时触发导致的，目前 js 这边没有解决方法，只能通过升级到 WKWebView 解决

**Comment by AKclown** [comment]
请问楼主解决了吗？  我这里也是这个问题Android没啥问题
