### ISSUE TITLE
Field组件中Clearable属性问题

### ISSUE THREAD

**Issue by looxii** [youzan/vant#1796]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
调用Field组件使用clearable属性，无法像Demo一样在后面显示X按钮全部删除填写内容。而是输入后点击其他地方后，自动删除已在field中填写内容。

**Code**
`

    
        
            
                
            
        
        
            
            
        
        
            
        
        
            
                
            
            
            
                
            
        
    

<script>
    export default {
        name: "Login"
    }
</script>

<style lang="scss" scoped>
    $margin_h : 0.5rem;
    $margin_w : 1rem;
    .login {
        &-group {
            margin: {
                top: $margin_h;
                bottom: $margin_h
            }
        }

    }
</style>
`

**Environment**
 - Device: Mac OS X
 - Browser: Chrome 69
 - Vant Version: Vant 1.3.1

**Comment by chenjiahan** [comment]
请绑定 v-model
