### ISSUE TITLE
建议DatePicker的列配置封装得更有灵活性，目前挺多close的issue都是提到他们需要灵活的时间列搭配

### ISSUE THREAD

**Issue by zicong-zhang** [youzan/vant#1797]
建议DatePicker的列配置封装得更有灵活性，目前挺多close的issue都是提到他们需要灵活的时间列搭配
如：有些需要单独展示年，有些需要单独展示分秒。。。
目前灵活性不太好，虽然都是统一回复 简单的场景使用picker

**Comment by chenjiahan** [comment]
感谢反馈，这个问题的原因是 DatetimePicker 组件早期的 API 设计比较死板，导致用起来不够灵活。
后续在大版本更新的时候，我们会考虑重构这个组件
