### ISSUE TITLE
轮播高度自适应

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#180]
轮播组件可以添加高度自适应功能吗？主要是为了适应不同大小的屏幕，高度可以跟随宽度改变，可以采用轮播的高度与宽度成比例。目前测试发现轮播默认高度是0，必须给定一个高度才能显示，但是当屏幕宽度改变的时候，高度不变的话，图片显示效果就异常了。
蟹蟹大佬。

**Comment by chenjiahan** [comment]
@YYQ8023 感谢反馈，近期会对轮播组件做一次重构，解决现有的一些问题

**Comment by leftstyle** [comment]
谢谢，希望能参考这个组件，它可以自适应高度：
[vue-awesome-swiper](https://github.com/surmon-china/vue-awesome-swiper)

另一个可自适应高度的jQuery的组件：
[Flexslider](https://github.com/woocommerce/FlexSlider)

祝早日发布新版

**Comment by YYQ8023** [comment]
@leftstyle 我目前用的是 “vue-m-carousel”，不过还是很期待官方的可以更好用，蟹蟹/

**Comment by chenjiahan** [comment]
@YYQ8023 已在 vant 0.10.0 中完成了 Swipe 的重构，该问题已修复

**Comment by xiaochegnzi0** [comment]
> @YYQ8023已经在vant 0.10.0中完成了Swipe的重构，该问题已修复

大佬，我使用2.0测试版，轮播图加载时
![微信截图_20190530171706](https://user-images.githubusercontent.com/27406973/58622750-ec57ec80-82fe-11e9-906e-aec6cc97b27e.png)
需要设置一个默认高度，不然会出现很长的空白
