### ISSUE TITLE
list组件Load触发的逻辑问题✋

### ISSUE THREAD

**Issue by liuvigongzuoshi** [youzan/vant#1801]
**Describe the bug**
原本是解决第一次初始化时，load加载动画不想看到，直接在onLoad里面先写一个 this.loading = false 再写业务代码，但碰巧解决了初始化触发两次加载的情况，offset 没有改，不管怎样就只会触发一次
```
onLoad() {
       this.loading = false
        .....
    }
```
切换到其他选项也一样触发一次，不知到为什么，源码里面watch loading，改变loading按理说也会触发一次啊！🤫
这样写还要一个问题，刷新浏览器（此时还是会触发一次），将页面滚动到底部，点击切换到其他选项卡，它又会触发两次了！😮
**Environment**
* Device: Chrome 模拟的 iPhone 6 页面
* Browser: Chrome 69
* Vant Version: 1.3.1

**Reproduce**
代码沙箱 随意fork
 [![Edit vant list  load twice](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ppmklx0l8x)

**Comment by chenjiahan** [comment]
不是很理解你具体要解决什么问题？ 直接在 onLoad 里面写 this.loading = false 是错误做法。正确做法是在异步请求结束后再设置 loading = false

**Comment by liuvigongzuoshi** [comment]
嗯，是错误的做法，初衷是第一次触发load时不展示loading动画，so...

**Comment by liuvigongzuoshi** [comment]
> 不是很理解你具体要解决什么问题？ 直接在 onLoad 里面写 this.loading = false 是错误做法。正确做法是在异步请求结束后再设置 loading = false
嗯，是错误的做法，初衷是第一次触发load时不展示loading动画，so...

**Comment by liuvigongzuoshi** [comment]
@chenjiahan 
嗯，是错误的做法，初衷是第一次触发load时不展示loading动画，so...

**Comment by chenjiahan** [comment]
@liuvigongzuoshi 最新版本里有 loading 的插槽，可以自己控制想要的逻辑效果，建议用那个
