### ISSUE TITLE
transition 封装List组件的bug💢🎃

### ISSUE THREAD

**Issue by liuvigongzuoshi** [youzan/vant#1803]
**Describe the bug**
切换选项卡，对应选项卡的内容切换一切正常
但，将页面滚动到底部让再回到顶部，点击切换到其他选项卡，该选项卡页面的的内容为空 🤨
```
<transition>
      <router-view></router-view>
</transition>
```
如果注释掉transition标签则不会出现这个问题🎃
组件List判断滚动条位置的时候，是不是要提前判断一下动画是否已经执行完？
[transitionend 或 animationend](https://cn.vuejs.org/v2/guide/transitions.html#%E5%90%8C%E6%97%B6%E4%BD%BF%E7%94%A8%E8%BF%87%E6%B8%A1%E5%92%8C%E5%8A%A8%E7%94%BB)

**Environment**
* Device: Chrome 模拟的 iPhone 6 页面
* Browser: Chrome 69
* Vant Version: 1.3.1

**Reproduce**
代码沙箱
[![Edit vant list ](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mo027q8oyj)

**Comment by chenjiahan** [comment]
加个 keep-alive 就行

**Comment by liuvigongzuoshi** [comment]
加了keep-alive，并不能解决，是不是动画影响滚动条

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26923747/45857306-ae2b2600-bd8a-11e8-8e6d-6a247ae50efd.gif)

以下是加了keep-alive的代码实例

[![Edit vant list ](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mo027q8oyj)
