### ISSUE TITLE
PullRefresh 下拉刷新 报错

### ISSUE THREAD

**Issue by wqb2017** [youzan/vant#1809]
**Describe the bug**
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Screenshots**
![image](https://user-images.githubusercontent.com/25101583/45583474-7ab54b00-b8f5-11e8-96a2-4a4803cebdc7.png)

**Environment**
 - Browser: 

**Reproduce**

**Comment by chenjiahan** [comment]
下个版本会处理一下这里的 warning

**Comment by chenjiahan** [comment]
已在 1.3.3 版本修复
