### ISSUE TITLE
file组件 里 textarea 获取不了scrollHeight

### ISSUE THREAD

**Issue by muiccc** [youzan/vant#181]
file组件 里 textarea 获取不了scrollHeight
顺带 提个建议 vant文档 里面的demo 建议贴上https://jsfiddle.net  发现文档写的一些demo 和 旁边 展示的例子 出入

**Comment by chenjiahan** [comment]
@muiccc 能详细描述一下你的问题吗，在什么情况下无法获取 scrollHeight

**Comment by muiccc** [comment]
@chenjiahan 在调用 van-address-list 和  van-address-edit 这两个组件 完成 用户 增加地址 修改地址的时候

**Comment by muiccc** [comment]
还有 van-address-edit组件,文档里面  <addressInfo 数据格式>  中的一个字段 name  ,应该是user_name,不然传进去 是无法显示 收件人姓名 @chenjiahan

**Comment by lysk** [comment]
我是在用popup显示AddressEdit的时候高度为0

**Comment by lysk** [comment]
另外问一下AddressEdit和AddressList为什么不统一下数据格式呢

**Comment by chenjiahan** [comment]
@muiccc @lysk 
1. AddressEdit 中的姓名字段已修正为 name，与 AddressList 保持一致
2. textarea scrollHeight 为 0 的问题已修复，出现原因是 display none 时无法获取 scrollHeight

以上改动在 vant@0.9.11 中可用

**Comment by wangminglmm** [comment]
textarea scrollHeight 为 0 的问题已修复，出现原因是 display none 时无法获取 scrollHeight, 以上改动在 vant@0.9.11 中可用  我用的是1.0.1版本textarea的高度还是0，这个组件我是放在一个弹窗中

**Comment by chenjiahan** [comment]
@wangminglmm 可以提供一个复现问题的 jsfiddle 吗

**Comment by wangminglmm** [comment]
<transition name="van-slide-bottom">
          <div class="edit-address-prop" v-if="showEdit||newAddress">
              <van-address-edit
                :area-list="areaList"
                :address-info="addressInfo"
                show-delete
                show-set-default
                show-search-result
                @save="onSave"
                @delete="onDelete"
              />
          </div>
        </transition>

代码就是这个，用v-if就ok，用v-show不可以

**Comment by wangminglmm** [comment]
<transition name="van-slide-bottom">
          <div class="edit-address-prop" v-if="showEdit||newAddress">
              <van-address-edit
                :area-list="areaList"
                :address-info="addressInfo"
                show-delete
                show-set-default
                show-search-result
                @save="onSave"
                @delete="onDelete"
              />
          </div>
        </transition>

**Comment by wangminglmm** [comment]
《》<transition name="van-slide-bottom">
          <div class="edit-address-prop" v-if="showEdit||newAddress">
              <van-address-edit
                :area-list="areaList"
                :address-info="addressInfo"
                show-delete
                show-set-default
                show-search-result
                @save="onSave"
                @delete="onDelete"
              />
          </div>
        </transition>
《》

**Comment by chenjiahan** [comment]
@wangminglmm 现在的版本里确实有这个问题，将在 1.0.4 版本中修复
