### ISSUE TITLE
轮播组件在使用左右点击调用swiperTo方法和手指滑动混合使用时,左右点击会出现白屏的问题!

### ISSUE THREAD

**Issue by JackingLuo** [youzan/vant#1810]
leftRun(){
                if(this.swiperIndex > 0){
                    --this.swiperIndex;
                    this.$refs.mySwiper.swipeTo(this.swiperIndex)
                }
            },
            changeOne(index){
                //console.log(index)
                this.swiperIndex = index
            },
            rightRun(){
                if(this.swiperIndex < this.swipeItemList.length-1){
                    ++this.swiperIndex;
                    this.$refs.mySwiper.swipeTo(this.swiperIndex)
                }
            },
具体代码就是在里   这两个方法就是左右箭头的方法,点击的时候会切换,我尝试打印这个索引值,发现是没有问题的;但是轮播到当前页面是白屏!求解决方法

**Comment by chenjiahan** [comment]
不规范的 issue
