### ISSUE TITLE
有一个疑问

### ISSUE THREAD

**Issue by ShingLi** [youzan/vant#1811]
我在看address-edit 这个组件源码，把省 市区混入到data的时候是这么写的
assignAreaValues(values) {
      Object.assign(this.data, {
        province: values[0] ? values[0].name : '',
        city: values[1] ? values[1].name : '',
        county: values[2] ? values[2].name : ''
      });
    },
计算属性下
 areaText() {
      const { province, city, county, areaCode } = this.data;
    }
如果按照上面那么写 那么怎么检测到 data的变化 从而让下面的计算属性执行呢？ 不应该下面这样吗？很不解。
this.data = assignAreaValues(values) {
      Object.assign({},this.data, {
        province: values[0] ? values[0].name : '',
        city: values[1] ? values[1].name : '',
        county: values[2] ? values[2].name : ''
      });
    },

**Comment by chenjiahan** [comment]
Vue 会 observe 对象属性的变化，从而触发计算属性
