### ISSUE TITLE
打包后组件的样式丢失问题

### ISSUE THREAD

**Issue by zhn4** [youzan/vant#1812]
在开发微信公众号页面
- 使用1.3.2的addressList组件，在开发环境和build后，组件的那个编辑icon出现错位
- 使用1.3.2的cell组件，在测试环境正常，build后样式丢失

 - 设备: ，小米6，iphone x
 - 浏览器: chrome69.0.3497.81，微信内置浏览器，微信开发者工具
 - Vant版本: 1.3.2

**Comment by chenjiahan** [comment]
建议看下是不是你的打包配置有问题
