### ISSUE TITLE
Collapse 和 PullRefresh 一起使用时，Collapse 展开关闭动画有时会失效

### ISSUE THREAD

**Issue by Mikasa33** [youzan/vant#1817]
**Describe the bug**
Collapse 和 PullRefresh 一起使用时，Collapse 展开关闭动画有时会失效，有办法解决这个问题吗？

**Screenshots**
![test](https://user-images.githubusercontent.com/29498153/45609934-aa4a8b80-ba8c-11e8-9380-9036f2431342.gif)

**Environment**
 - Device: 
 - Browser: Google chrome
 - Vant Version: v1.3.2

**Reproduce**
https://jsfiddle.net/c0qf93b7/

**Comment by Mikasa33** [comment]
刚才尝试在 `van-collapse-item__wrapper` 上给了个 `height: auto;` 样式，暂时解决了这个问题。。

**Comment by chenjiahan** [comment]
应该是浏览器的问题，目前没有好的解决方法
