### ISSUE TITLE
SwipeCell 滑动单元格

### ISSUE THREAD

**Issue by ToggDream** [youzan/vant#1818]
我已经全局引入了 vant ，但是用到SwipeCell 这个组件的时候  会报未注册的错误，其他组件没有问题
[Vue warn]: Unknown custom element: <van-swipe-cell> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by LynanBreeze** [comment]
升级vant到1.3.0以上版本

**Comment by ToggDream** [comment]
我已经更新到了1.3.2版本 但是还是报相同的错，其他组件都可以使用，就这个swipeCell不行

**Comment by chenjiahan** [comment]
请确认下你是否正确升级了版本
