### ISSUE TITLE
变更DatetimePicker的max-date导致column的index置0

### ISSUE THREAD

**Issue by coder-layne** [youzan/vant#1821]
**Describe the bug**
动态改变 DatetimePicker 的 max-date 时，会出现 column 的 index 置 0，与 DatetimePicker 当前值不一致的情况

**Environment**
 - Vant Version: 1.3.2

**Reproduce**
https://codepen.io/coder-layne/pen/wEYLzb

**Comment by TDayBreak** [comment]
感觉跟#1793的问题很像

**Comment by chenjiahan** [comment]
同个问题 https://github.com/youzan/vant/issues/1793，
会在下个版本修复
