### ISSUE TITLE
Swipe 轮播不显示图片

### ISSUE THREAD

**Issue by Fury-Life** [youzan/vant#1822]
**img标签不显示**
使用HTML直接引用线上CSS和JS文件，但是图片地址违背渲染出来。

**Screenshots**

 <div id="app">
        <van-swipe :autoplay="3000">
          <van-swipe-item v-for="(image, index) in images" :key="index">
            <img v-lazy="image"/>
          </van-swipe-item>
        </van-swipe>
    </div>
    
    <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
    <script src="https://unpkg.com/vant/lib/vant.min.js"></script>
    <script>
        var vm = new Vue({
               el: '#app',
               data: {
                   images: [
                          'https://img.yzcdn.cn/1.jpg',
                          'https://img.yzcdn.cn/2.jpg'
                        ]
               }
           })
    </script>

**Environment**
HTML 在线引用

**Comment by chenjiahan** [comment]
不规范的 issue
