### ISSUE TITLE
当List数据较少的时候，下拉刷新底部会遮盖，目前有什么方法让List100%么？

### ISSUE THREAD

**Issue by darling-shadow** [youzan/vant#1823]
当List数据较少的时候，下拉刷新底部会遮盖，目前有什么方法让List100%么？

**Comment by Caijt** [comment]
我也遇到这个问题，我是这样解决的
<van-pull-refresh><div style='min-height:100vh'><van-list></van-list></div> </van-pull-refresh>

**Comment by darling-shadow** [comment]
在最下面加了一个空div；
<div style="width:100%;height:100px" v-if="list.length < 5"/>
希望开发者有更简洁的方法；先关闭了。

**Comment by darling-shadow** [comment]
在最下面加了一个空div；
`<div style="width:100vw;height:50vw" v-if="list.length < 5"/>`
希望开发者有更简洁的方法；先关闭了。

**Comment by darling-shadow** [comment]
> 我也遇到这个问题，我是这样解决的

呃，貌似代码没加代码块，被吞了。

**Comment by Caijt** [comment]
是的，昨晚回复的，刚才才发现我发的代码不见了。。。
