### ISSUE TITLE
在Android4.4.2版本下collapse动画出现闪烁异常

### ISSUE THREAD

**Issue by talenHuang** [youzan/vant#1824]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在Android4.4.2版本下collapse动画出现闪烁异常

**Screenshots**
![ezgif-4-f664b7323d](https://user-images.githubusercontent.com/22046308/45728401-72f9ed00-bbfa-11e8-9147-d5a7fefa2bfa.gif)

**Environment**
 - Device: huawei CHM-TL100
 - Browser: webview内核 chromium33
 - Vant Version: 1.3.2
请问下有没有什么好的解决办法？谢谢！

**Comment by chenjiahan** [comment]
木有办法解决
