### ISSUE TITLE
list组件为什么会在初始化的时候自动执行两次onLoad方法

### ISSUE THREAD

**Issue by zicong-zhang** [youzan/vant#1827]
![f767b65a-5349-4a1a-9d97-020aec76c098](https://user-images.githubusercontent.com/32116218/45737120-879cac00-bc1f-11e8-81e3-db020459b968.png)
![image](https://user-images.githubusercontent.com/32116218/45737195-b7e44a80-bc1f-11e8-8282-2e0715ab7873.png)
![image](https://user-images.githubusercontent.com/32116218/45737217-c894c080-bc1f-11e8-82ea-25b79c5543f8.png)

直接复制文档示例代码跑的，会执行两次

**Comment by chenjiahan** [comment]
距离底部小于 offset 时就会触发 load
