### ISSUE TITLE
如何再次触发list的onLoad

### ISSUE THREAD

**Issue by liupei1995** [youzan/vant#1828]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/
首次进页面的时候是可以触发list的load事件的，然后我清空页面，没有再次触发，此时的finished和loading都为false。
之前我是设置loading为true，是可以再次请求的，但现在貌似不可以了
我现在的解决方法是手动调用load事件，请问有其他方法吗
![2018-09-19_173715](https://user-images.githubusercontent.com/21356797/45745203-e9b2dc80-bc32-11e8-8bcd-7a17405df800.png)

**Comment by chenjiahan** [comment]
可以使用 list 的 check 方法

**Comment by yeyi361936738** [comment]
兄弟你解决了吗？可以提供一下思路吗
