### ISSUE TITLE
field输入框maxlength属性无效

### ISSUE THREAD

**Issue by CantFindItAnymore** [youzan/vant#1829]
**Describe the bug**
field输入框maxlength属性无效，dom中已经渲染成功，可是没有效果。

**Screenshots**
![qq 20180919182828](https://user-images.githubusercontent.com/31693925/45748099-57163b80-bc3a-11e8-96a0-805efb4c2a0d.png)

**Environment**
 - Device: 
 - Browser: chorm
 - Vant Version: 1.3.2

**Comment by LynanBreeze** [comment]
number类型的input不支持maxlength属性。

**Comment by CantFindItAnymore** [comment]
我知道，可是这并不合理。我认为应该支持该属性。

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 1.3.3 版本修复

**Comment by lujunpeng** [comment]
这里有个bug ，当type=text maxlength=4 时， 输入 无法输入超过4个拼音的汉字
@chenjiahan

**Comment by lujunpeng** [comment]
format(target = this.$refs.input) {
      let { value } = target;
      const { maxlength } = this.$attrs;

      if (this.isDef(maxlength) && value.length > maxlength) {
        value = value.slice(0, maxlength);
        target.value = value;
      }

      return value;
    }
这个地方要做个判断 吧 当type是number 才执行
