### ISSUE TITLE
全局引入后，AddressEdit使用报错

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#183]
报错内容：
![image](https://user-images.githubusercontent.com/22813922/31376417-7ca2e6e0-add7-11e7-9e90-a67a9df49fea.png)

遇到过这个错误，意思是组件未注册就使用了，但是我使用其它的组件没有问题。
代码是用官网的：
![image](https://user-images.githubusercontent.com/22813922/31376378-57293f04-add7-11e7-91ab-142de2462449.png)
![image](https://user-images.githubusercontent.com/22813922/31376397-63ca4e88-add7-11e7-93fd-ac29481a1745.png)

**Comment by chenjiahan** [comment]
@YYQ8023 请检查下你的 vant 版本， address-edit 组件在 vant@0.9.8 版本后才加入

**Comment by YYQ8023** [comment]
@chenjiahan 
![image](https://user-images.githubusercontent.com/22813922/31379085-e7da434c-addf-11e7-9723-17b7dc3a2947.png)

**Comment by chenjiahan** [comment]
@YYQ8023 抱歉，刚确认了下，AddressEdit 是在 vant@0.9.10 中加入的，麻烦升级 vant 后再试~
