### ISSUE TITLE
area省市区直辖市报错

### ISSUE THREAD

**Issue by millerhamburger** [youzan/vant#1830]
根据官方小哥哥的方法
//选择城市
    async selectCity (picker, values, index) {
      if(index < 2){
        let province_id = values[index].code;
        let city_list = await this.$api.getListById(province_id,0)
        this.areaList.city_list = city_list.data
        if(index == 0){
          let code = JSON.stringify(city_list.data).slice(2,8)
          let county_list = await this.$api.getListById(code,1)
          this.areaList.county_list = county_list.data
        }
      }
    },
写了一个重新加载的方法但是没用，第三级还是出不来

**Comment by chenjiahan** [comment]
不规范的 issue
