### ISSUE TITLE
<van-swipe-cell> solt 为right时，class设置不生效

### ISSUE THREAD

**Issue by AFAP** [youzan/vant#1836]
**Describe the bug**
<van-swipe-cell>组件，设置右侧滑出区域的样式时，采用class形式不会生效，采用style就会生效.

**Screenshots**
Add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/11977837/45798421-6e0d6a00-bcdc-11e8-9deb-5db35469cda7.png)
![image](https://user-images.githubusercontent.com/11977837/45798446-7bc2ef80-bcdc-11e8-8f3e-07ff58aedcb1.png)
此处“mail-swipe-right”未生效，style中的height生效了

**Environment**
 - Device:  MacBook Pro
 - Browser:  Chrome 69
 - Vant Version:  1.3.1

**Comment by chenjiahan** [comment]
class 拼错了兄弟

**Comment by AFAP** [comment]
我……………………日狗了
不好意思了，耽误宝贵时间。
我检查了class的名字一遍又一遍，复制，剪切，愣是没看到class写错……

**Comment by chenjiahan** [comment]
🤣
