### ISSUE TITLE
SwiperCell组件无法自定义点击事件

### ISSUE THREAD

**Issue by onjuju** [youzan/vant#1838]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
SwiperCell组件无法自定义点击事件

**Describe the solution you'd like**
该组件的点击事件只在拉出来的状态下才会触发, 若没有位移时则无法发生点击事件.
但比如在京东app的商品列表, 可以点击进入商品详情或是左滑选择加入购物车/关注, 在京东的地址选择也是如此, 我认为该需求是有必要的.
在该组件下, 还希望能够将某侧滑动内容的选项数目增加, 而不是仅判断左边右边, 虽然现在通过slot也能实现, 但效果比较粗糙以及有一些bug无法解决

**Comment by chenjiahan** [comment]
1.3.3 版本增加了点击事件，点击事件也可以在 default slot 的元素上监听。
还有内容的选项数目完全可以自定义的。
