### ISSUE TITLE
AddressList 中select事件无效

### ISSUE THREAD

**Issue by 353170753** [youzan/vant#184]
### 为什么在methods中添加了onSelect方法，但是无效，add事件和edit事件是可以的。

**<van-address-list
                v-model="chosenAddressId"
                :list="list"
                @edit="onEdit"
                @select="onSelect"
        />**

**Comment by chenjiahan** [comment]
@353170753 麻烦将 vant 升级到 0.9.10 版本后再试，select 事件是在后续版本中添加的

**Comment by YYQ8023** [comment]
@353170753 0.9.9确实没用。

**Comment by 353170753** [comment]
升级到0.9.10后解决，谢谢
