### ISSUE TITLE
swipe与popup组件一起使用,swipe初始化的时候,每个swipe-item获取不到宽度

### ISSUE THREAD

**Issue by youdianfan** [youzan/vant#1843]
**Describe the bug**
swipe与popup组件一起使用,swipe初始化的时候,每个swipe-item获取不到宽度

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/27018910/45865020-b432fe00-bdae-11e8-91e6-63bfcbe476da.png)
 

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: "vant": "^1.3.2",

popup组件后展示的话,是不是影响了swipe初始化?

**Comment by youdianfan** [comment]
![image](https://user-images.githubusercontent.com/27018910/45865151-2277c080-bdaf-11e8-874c-5f9bf146fe16.png)

**Comment by chenjiahan** [comment]
打开 lazy-render 不会有这个问题

**Comment by ghostcode** [comment]
@chenjiahan 打开还是存在此问题，不知道如何解决。

**Comment by liaorende** [comment]
打开 lazy-render，首次弹出popup，swipe组件层级要等1秒才会高于popup组件

**Comment by chenjiahan** [comment]
上面是口误哈，sorry，应该是设置`lazy-render="false"`
