### ISSUE TITLE
List组件当style设置为scoped时，会有部分push进去的数据样式没生效

### ISSUE THREAD

**Issue by Kennersky** [youzan/vant#1844]
**Describe the bug**
在组件里使用List，当组件里的样式style添加scoped时，数据push进去出来的样式部分没有私有化不生效.
不使用scoped时则正常。
**Screenshots**
![1](https://user-images.githubusercontent.com/2129521/45866571-e2ffa300-bdb3-11e8-9798-d8c0682626bd.png)

![2](https://user-images.githubusercontent.com/2129521/45866390-3d4c3400-bdb3-11e8-8480-23e9c3e6d647.png)

![3](https://user-images.githubusercontent.com/2129521/45866492-9d42da80-bdb3-11e8-89fd-fc5aeb1c19f6.png)

**Environment**
 - Device: win10 64位
 - Browser: 谷歌浏览器手机模式
 - Vant Version: 1.3.2

**Reproduce**
jsfiddle 不支持设置scoped方式加载样式，无法提供线上代码。

**Comment by chenjiahan** [comment]
跟组件无关
