### ISSUE TITLE
组件添加图片不显示

### ISSUE THREAD

**Issue by 867588763** [youzan/vant#1845]
**Describe the bug**
    van-cell van-tabbar-item组件添加图片不显示

**Screenshots**
![image](https://user-images.githubusercontent.com/17881190/45874913-b5712480-bdc8-11e8-8ffa-5fadea3c0786.png)
![image](https://user-images.githubusercontent.com/17881190/45874938-ccb01200-bdc8-11e8-9155-8ea8baf03bd6.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version:

**Comment by chenjiahan** [comment]
icon 属性不支持传入图片，需要使用 Icon 组件支持的 name
