### ISSUE TITLE
list组件设置了finished为true以后，还是请求了一次

### ISSUE THREAD

**Issue by liupei1995** [youzan/vant#1851]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/
我请求进error的时候设置finished为true，但是还是会加载一次
![2018-09-25_154758](https://user-images.githubusercontent.com/21356797/46000472-3dae3d00-c0db-11e8-88d9-6bc52142dcab.png)
![2018-09-25_154824](https://user-images.githubusercontent.com/21356797/46000478-4141c400-c0db-11e8-9a46-4c91c2afb4ce.png)

**Comment by zhangcuihua** [comment]
我也遇到了，找到原因了吗？

**Comment by huihui91** [comment]
是数据赋值还是什么赋值。我的是在赋值后才设置loading为false的

**Comment by liupei1995** [comment]
> 是数据赋值还是什么赋值。我的是在赋值后才设置loading为false的

数据赋值

**Comment by lhtuling** [comment]
你的问题解决了没,我也是这个情况!求回复 超感谢!

**Comment by liupei1995** [comment]
> 你的问题解决了没,我也是这个情况!求回复 超感谢!

解决了，我在数据赋值之前就设置了loading为false，就请求了两次
