### ISSUE TITLE
提一个小小的建议,团队是否后期考虑做vw适配方案?

### ISSUE THREAD

**Issue by youdianfan** [youzan/vant#1857]
lib         # 编译后，样式单位px，一般用于自定义适配方案等（默认）
lib-vw      # 编译后，样式单位vh/vw，一般用于非兼容场景，无需额外配置

滴滴的组件库
https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=%E5%AE%89%E8%A3%85
[滴滴的组件库](https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=%E5%AE%89%E8%A3%85)

可以了解下.我现在项目目前用的就是vw方案

**Comment by chenjiahan** [comment]
暂时没有计划直接生成 vw 的文件包，目前可以通过 postcss 插件进行转换

**Comment by youdianfan** [comment]
好的,我目前就是postcss 使用你们组件,进行转换的.赞!

**Comment by nongzhenli** [comment]
> 好的,我目前就是postcss 使用你们组件,进行转换的.赞!

请问，我现在也是通过 postcss-top-vw 转换px 成 vw，参照750的，遇到的一个问题就是 vant css样式单位转换成vw了，但是并没有放大2倍（因为我是按照750的设计稿的）。导致凡是vant原来的css样式，都缩小的一倍的，
**配置如下图**
![image](https://user-images.githubusercontent.com/19389294/77155032-d6a6f400-6ad7-11ea-994b-541e1a463efe.png)

遇到效果问题如下图
