### ISSUE TITLE
HTML直接引用Vant，Swipe组件无法使用？

### ISSUE THREAD

**Issue by Fury-Life** [youzan/vant#1858]
新手小白，看了官方教程，尝试使用，发现在Header和body前引用了最新版本的 CDN 链接后，网页上直接引用IMG地址无法被渲染出来。

示例代码：

HTML部分-----
<van-swipe :autoplay="3000"> <van-swipe-item v-for="(image, index) in images" :key="index"> <img v-lazy="image" />  </van-swipe-item> </van-swipe>

JS部分--------
var app = new Vue({
  el: '#app',
  data: {
      images: [
        'https://img.yzcdn.cn/1.jpg',
        'https://img.yzcdn.cn/2.jpg'
      ]
  }
})

最终只显示两个点点，图片地址无法显示

**Comment by chenjiahan** [comment]
不规范的 issue
