### ISSUE TITLE
能不能考虑增加一个  “选择图片” 的功能

### ISSUE THREAD

**Issue by vin395685361** [youzan/vant#186]

**Comment by cookfront** [comment]
具体是怎么`选择图片`呢？能具体描述下这个功能么

**Comment by vin395685361** [comment]
[http://element.eleme.io/#/zh-CN/component/upload](url)

移动端考虑增加一个“上传图片”的功能

**Comment by cookfront** [comment]
不知道`Uploader`组件是否能满足你的需求
