### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by kangzhongyao** [youzan/vant#1860]
1.card 卡片 能不能增加一些自定义属性？
    比如我在标题 ，描述下面还要增加一个时间，这个要怎么弄。
2.cell 单元格 能不能 和 Actionsheet 上拉菜单 整合在一起？
    我需要点击单元格的时候弹出Actionsheet 上拉菜单 
3.导航栏加一个API 将搜索加入导航内
 4. Slider 滑块 可以变成两个圆圈，往中间拖动那种吗，
 需要一个范围拖动，例如 10- 20  20 -30 这样的功能

**Comment by chenjiahan** [comment]
1. 可以使用 slot
2. 搭配使用即可
3. 不计划支持
4. 后续会支持
