### ISSUE TITLE
ImagePreview的一个bug

### ISSUE THREAD

**Issue by Qymh** [youzan/vant#1861]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
用手指左右同时滑动附件图片，会导致图片消失，遮罩却不消失

**Screenshots**

![wechatimg37](https://user-images.githubusercontent.com/29172211/46135099-02487580-c277-11e8-837a-19842698dcf0.jpeg)

**Environment**
 - Device: ios
 - Browser:  app webview
 - Vant Version:  1.3.0

**Reproduce**
暂无

**Comment by 1429880240** [comment]
.

**Comment by chenjiahan** [comment]
下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 1.3.5 版本修复
