### ISSUE TITLE
在无法连通接口的情况下，项目无法启动问题

### ISSUE THREAD

**Issue by Aric-sky** [youzan/vant#1862]
**Describe the bug**
Error: connect ECONNREFUSED 192.168.61.199:8086

**Screenshots**
![image](https://user-images.githubusercontent.com/30253442/46135939-fe1d5780-c278-11e8-81aa-8e80ce1e52ee.png)
![image](https://user-images.githubusercontent.com/30253442/46135965-15f4db80-c279-11e8-9c38-7925031e8f74.png)

**Environment**
 - Device: PC
 - Browser: Chrome
 - Vant Version: 

**Reproduce**
yarn run dev无法启动

**Comment by chenjiahan** [comment]
不规范的 issue
