### ISSUE TITLE
tab切换没有触发list的load事件

### ISSUE THREAD

**Issue by liupei1995** [youzan/vant#1864]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1
tab和list组件混用时，只有当前的tab中的list会触发load，切换其他tab时，没有触发其中list的load事件

**Comment by chenjiahan** [comment]
这种情况检测不到，可以手动调用 check 方法

**Comment by yeyi361936738** [comment]
兄弟解决没？共享下思路呗  谢谢

**Comment by liupei1995** [comment]
> 兄弟解决没？共享下思路呗 谢谢

我是手动触发list的onLoad事件

**Comment by yeyi361936738** [comment]
我的解决方案
[image: image.png]

liupei1995 <notifications@github.com> 于2018年12月13日周四 下午3:36写道：

**Comment by yeyi361936738** [comment]
如果触发了loading会被设置为false，没有触发loading就是true我就可以自己执行函数

yi ye <yeyi361936738@gmail.com> 于2018年12月26日周三 上午9:36写道：

**Comment by feelslive** [comment]
问题：
请问如何手动调用check方法，this.$refs.list.check()并不起作用?
解决：
setTimeout(()=>{
     this.$refs.list.check()
 },100)
