### ISSUE TITLE
swipe-item__track的宽度内联样式为0

### ISSUE THREAD

**Issue by skLeo** [youzan/vant#1865]
**What problem does this feature solve?**
使用swipe组件，每一个swipe-item是一个菜单列表，列表中的每一个元素是通过flex布局的，因为swipe-item__track的内联样式是0，导致我的item中无法展开，自己设置了！importan，回导致swipe本身无法滑动

**Describe the solution you'd like**
希望滑块的宽度是100%

**What does the proposed API look like?**
swipe中的width可以接收String，width:{type:Number|String default:100%}

**Comment by chenjiahan** [comment]
麻烦提供下 jsfiddle

**Comment by zhengxsFE** [comment]
我也遇到这个问题，最近出现的比较频繁，就是轮播图遇到 tab 组件，或者页面切换的时候就可能会出现
