### ISSUE TITLE
全部引入了但是Toast等好多一用就说找不到

### ISSUE THREAD

**Issue by 1429880240** [youzan/vant#1868]
Toast('我是提示文案，建议不超过十五字~');

**Comment by zhuangxiaohui** [comment]
没认真看API  这个是单独组件[toast](https://youzan.github.io/vant/#/zh-CN/toast)
import { Toast } from 'vant';
```
组件内调用
引入 Toast 组件后，会自动在 Vue 的 prototype 上挂载 $toast 方法，便于在组件内调用。
```
