### ISSUE TITLE
npm run dev 后本地文档无法正常访问

### ISSUE THREAD

**Issue by openks** [youzan/vant#1869]
**Describe the bug**

由于公司不能访问github,本地搭建文档时 npm run dev 后本地文档主页可以打开但是左侧国际化菜单及之后的所有菜单都无法正常访问，点击后会跳转到介绍页
注： 
windows 系统需手动修改解决\u问题后才可以正常启动。
由于公司使用代理，0.0.0.0 无法找到，同时修改了webpack.dev.js里serve的host为127.0.0.1
文档里的模拟手机可以正常操作
chrome控制台及node控制台无任何报错信息
mac上一切正常

**Screenshots**
不需要截图

**Environment**
 - Device: windows 10
 - Browser:  chrome 62
 - Vant Version: 1.3.3

**Reproduce**
本地无线上重现环境

**Comment by chenjiahan** [comment]
可能是 host 配置问题？

**Comment by openks** [comment]
> 可能是 host 配置问题？

前面几个菜单可以点击 后面菜单不能点击 跟host有关？
