### ISSUE TITLE
Swipe 轮播的swipeTo

### ISSUE THREAD

**Issue by LiGuoBi** [youzan/vant#1870]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
swipe 刷新页面（不通过手势滑动）通过 swipeTo 方法滑动，swipeTo 没有任何问题，但是 通过手势滑动
后再去调用 swipeTo 就会出现 swipe-item 不见的情况 （不见的原因 swipe-item 添加了 transform: translateX(-750px); css样式）

**Screenshots**
![image](https://user-images.githubusercontent.com/37058788/46241843-4d3ac800-c3f2-11e8-8722-2c5de495a898.png)
![image](https://user-images.githubusercontent.com/37058788/46241850-680d3c80-c3f2-11e8-8997-506e580b3bfd.png)

**Environment**
 - Device: 
 - Browser:  谷歌浏览器
 - Vant Version:  v1.3.3

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
未复现这个问题
