### ISSUE TITLE
Collapse 折叠面板是否支持多级折叠

### ISSUE THREAD

**Issue by jinggk** [youzan/vant#1873]
想请问一下，Collapse 折叠面板是否支持多级折叠或者嵌套折叠？api没有发现这个功能，目前测试再item下再放一层会有问题~，点击收起和展开的时候，错乱了~

**Comment by chenjiahan** [comment]
Collapse 目前不支持嵌套折叠喔，后续会考虑支持

**Comment by lm16** [comment]
借楼，如题。2020
