### ISSUE TITLE
Collapse折叠面板嵌套使用，子面板的图标展示不正确

### ISSUE THREAD

**Issue by andyhuang15** [youzan/vant#1874]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

手风琴面板嵌套，当打开父级某一个item时，父级展示icon显示的是向上箭头，但是该item下面包含的子面板的所有item的icon也是向上箭头，无论子面板上的item当时状态是否展开。

**Screenshots**
Add screenshots to help explain your problem.
![_20180930094050](https://user-images.githubusercontent.com/17907328/46252025-0eaa1980-c495-11e8-92da-5360eb51c822.jpg)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 
     CDN获取的最新版本

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

demo代码如下
    <van-collapse v-model="activeName" accordion>
        <van-collapse-item title="有赞微商城" name="1">
            提供多样店铺模板，快速搭建网上商城
            <van-collapse v-model="activeChildName" accordion>
                <van-collapse-item title="有赞微商城child1" name="4">
                    zishangchneg
                </van-collapse-item>
            </van-collapse>
        </van-collapse-item>
        <van-collapse-item title="有赞零售" name="2">
            网店吸粉获客、会员分层营销、一机多种收款，告别经营低效和客户流失
        </van-collapse-item>
        <van-collapse-item title="有赞美业" name="3">
            线上拓客，随时预约，贴心顺手的开单收银
        </van-collapse-item>
    </van-collapse>

export default {
  data() {
    return {
      activeName: '1'，
      activeChildName: '0'
    };
  }
};

**Comment by chenjiahan** [comment]
Collapse 目前不支持嵌套折叠喔，后续会考虑支持
