### ISSUE TITLE
SwipeCell 滑动单元格 API 能增加一个开关按钮

### ISSUE THREAD

**Issue by LiGuoBi** [youzan/vant#1875]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
我需要把 Collapse 嵌套在 SwipeCell 中使用，在 Collapse 打开时不能滑动 SwipeCell，需要关闭时才可以
滑动 SwipeCell

**Describe the solution you'd like**

**Comment by chenjiahan** [comment]
在 1.3.4 版本中增加了 `disabled` 属性
