### ISSUE TITLE
vant-list 问题疑惑

### ISSUE THREAD

**Issue by hackerslizc** [youzan/vant#1876]
![sz v1 b _8bxs 08lx6z4](https://user-images.githubusercontent.com/7309720/46252903-466b8e00-c4a2-11e8-8c35-26e991980024.png)
页面中调用vant-list 组件，但是发现组件的 load 方法 会一直加载，接口刚刚取到数据 还没滚动呢 就立马加载下一页了

想用户滚动到页面底部之后再加载下一页。

**Comment by hackerslizc** [comment]
版本 1.3.2

**Comment by Kellercai** [comment]
@hackerslizc 我的版本是1.3.2，一开始也是会调用load方法

**Comment by hackerslizc** [comment]
> @hackerslizc 我的版本是1.3.2，一开始也是会调用load方法

你有没有出现这样的问题哇

**Comment by hackerslizc** [comment]
@Kellercai 你有没有出现这样的问题哇

**Comment by chenjiahan** [comment]
重复 issue https://github.com/youzan/vant/issues/1882

**Comment by GHUserZ** [comment]
问题解决了吗
