### ISSUE TITLE
vantUI移动端开发遇到的问题和bug

### ISSUE THREAD

**Issue by try6** [youzan/vant#1880]
**Describe the bug**
van-tabs在赋予sticky属性后，在ios上出现布局错误。

在安卓设备是可以正常显示

**Screenshots**
正常是应该出现在这个位置
![image](https://user-images.githubusercontent.com/30166209/46256687-b7319b00-c4e0-11e8-8dad-2f26c44bd95c.png)

使用ios打开后，有时候会出现在顶部
![image](https://user-images.githubusercontent.com/30166209/46256691-c1ec3000-c4e0-11e8-9fcf-20be55009623.png)

有时候出现在底部，非常不稳定
![image](https://user-images.githubusercontent.com/30166209/46256696-cf091f00-c4e0-11e8-996a-cdc1b3feab7e.png)

**Environment**
 - Device: ios系统,版本为最新版的12
 - Browser: 微信和所有浏览器都出现这种情况
 - Vant Version: v1.3.3

**Reproduce**

**Comment by chenjiahan** [comment]
未复现这个问题，建议看下是否是其他原因导致

**Comment by xiaolongGitHub1498** [comment]
同样有这个问题
