### ISSUE TITLE
swiper图片在移动端无法长按保存

### ISSUE THREAD

**Issue by hr799** [youzan/vant#1881]
**swiper图片在移动端无法长按保存**
swiper轮播在移动端无法长按保存，在微信端里点“发送给朋友”也无反应

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device:  iPhone *
 - Browser:  Chrome + Safari + Wechat Browser
 - Vant Version: 1.3.1

**Reproduce**
任意一个swipe空间，在微信里打开，长按图片

**Comment by chenjiahan** [comment]
可以长按保存的，建议你看下是不是其他原因导致无法保存
