### ISSUE TITLE
首次加载,会不停的加载数据,滚动条距离底部很远它自己就发起请求了,这是什么原因呢

### ISSUE THREAD

**Issue by hackerslizc** [youzan/vant#1882]
**Describe the bug**
首次加载,会不停的加载数据,滚动条距离底部很远它自己就发起请求了，每次都会自动进入searchProductsFn 方法，进去 loading 是true, 我在searchProductsFn 方法设置为false 也没用
**Screenshots**
![image](https://user-images.githubusercontent.com/7309720/46265861-306ed380-c55d-11e8-9d47-ca02996a0844.png)
![image](https://user-images.githubusercontent.com/7309720/46265869-42e90d00-c55d-11e8-80dd-381e129d4468.png)
![image](https://user-images.githubusercontent.com/7309720/46265891-69a74380-c55d-11e8-9f67-c36f69886cf0.png)
最后这张图是 searchProductsFn 请求API

**Environment**
 - Device: PC端和手机端
 - Browser: 各个浏览器
 - Vant Version: 1.3.3

**Comment by chenjiahan** [comment]
在数据加载完成后设置 loading 为 false 即可
可以通过 offset 控制滚动加载的距离

**Comment by hackerslizc** [comment]
大佬，我是设置了的 。 但是还是一直在加载数据呢

**Comment by hackerslizc** [comment]
> 在数据加载完成后设置 loading 为 false 即可
> 可以通过 offset 控制滚动加载的距离

不行的，不然我也不会提问题啦

**Comment by chenjiahan** [comment]
@hackerslizc 可以提供个 jsfiddle

**Comment by linwenfeng122** [comment]
这个loading触发机制有问题吧，遇到同样问题

**Comment by shen-lan** [comment]
解决了吗？

**Comment by GHUserZ** [comment]
解决了吗？
