### ISSUE TITLE
van-goods-action 和 Steps 有样式穿透的问题

### ISSUE THREAD

**Issue by CGerAJ** [youzan/vant#1883]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
van-goods-action 和 Steps 有样式穿透的问题
**Screenshots**
Add screenshots to help explain your problem.
![wx20181002-112636](https://user-images.githubusercontent.com/20548301/46327835-5caa5300-c636-11e8-8cb5-9108253d2ef5.png)

**Environment**
 - Device: macos 10.13.6
 - Browser:  chorme  69.0.3497.100
 - Vant Version: 1.3.2

**solution**
css层级穿透
.van-goods-action{
  z-index: 999;
}

**Comment by chenjiahan** [comment]
这种情况手动设置 z-index 就可以
