### ISSUE TITLE
checkbox的change事件逻辑

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#189]
当外部改变checkbox的值时，不应该触发change事件。
应该是checkbox本身点击后才触发change事件。
目前要实现一个全选功能，通过计算属性去检测checkboxGroup中选中的数组和所有数组是否一样，一样就让另外一个单独的checkbox的值变为true，即打上勾，如果不一样，则不打勾。可是当计算属性中改变全选checkbox值之后，触发了这个change事件。以前在iview的checkbox组件中是可以实现上述功能的。
求帮助，蟹蟹。

**Comment by YYQ8023** [comment]
改变全选按钮的时候，备份一下已选择列表，先这样解决了。。。

**Comment by ansonhorse** [comment]
@YYQ8023 你好，我在做一个购物车页面，也是进了这个坑，这个组件好像还是有这个问题？
请问你除了上面说的，还有没有新的处理方式？

**Comment by ansonhorse** [comment]
@YYQ8023 一怒之下，不用`change`事件了，用`click`也可以达到我的需求😅
