### ISSUE TITLE
升级ios12之后，icon图标显示不出

### ISSUE THREAD

**Issue by baymaxxjf** [youzan/vant#1898]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by baymaxxjf** [comment]
未升级时：![_20181008144811](https://user-images.githubusercontent.com/28503672/46595063-3b030d00-cb09-11e8-896f-4df7bba62ec6.jpg)
升级到ios12后图标不见了。小米手机还正常
![_20181008144928](https://user-images.githubusercontent.com/28503672/46595098-61c14380-cb09-11e8-8ba3-66f1dba232f4.jpg)
Environment
Device:iphone5s
Browser:微信内置浏览器
Vant Version:：1.3.3

**Comment by chenjiahan** [comment]
请确认下是否正确加载了图标文件

**Comment by lifuyao** [comment]
I also met this issue, have you got the solution ?
