### ISSUE TITLE
移动端如何自适应宽度？

### ISSUE THREAD

**Issue by Alexis374** [youzan/vant#190]
我看到现在vant里面似乎只是用的px 来标注width，padding等，为何不考虑rem方案自适应屏幕的宽度呢。我想知道不这么做的原因是什么，因为我最近也在考虑做组件库，所以参考各个开源库，故有此问

**Comment by chenjiahan** [comment]
@Alexis374 考虑到通用性，Vant 目前不会默认采用 rem 作为单位，自适应可以通过 flex、百分比、media query 等方式完成
