### ISSUE TITLE
rol col  type="flex" justify="space-around" 间距不平分

### ISSUE THREAD

**Issue by tosslife** [youzan/vant#1900]
**设置 row type="flex" justify="space-around"**
_rol col  type="flex" justify="space-around" 间距不平分_

```
<van-row type="flex" justify="space-around">
          <van-col span="6">span: 6</van-col>
          <van-col span="6">span: 6</van-col>
          <van-col span="6">span: 6</van-col>
</van-row>
```
![image](https://user-images.githubusercontent.com/7598390/46602061-b83a7c00-cb21-11e8-8047-7a0d8502ea32.png)

**Comment by chenjiahan** [comment]
space-around 本身就是这样的，可以去看下 flex 的文档
