### ISSUE TITLE
Dose Vant have any design resource like components' sketch template ?

### ISSUE THREAD

**Issue by waynecz** [youzan/vant#1903]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
Want design resource help to design application base on vant

**Describe the solution you'd like**
A sketch template should be perfect

**What does the proposed API look like?**
none

**Comment by chenjiahan** [comment]
参加 https://github.com/youzan/vant/issues/1137
