### ISSUE TITLE
swiper没有点击事件吗?

### ISSUE THREAD

**Issue by 597410004** [youzan/vant#1911]
vue使用swiper的时候设置@click没效果?是没有点击事件还是我的写法有错误
` <div class="image-swipe">
    <van-swipe :autoplay="3000" @click="onClick">
      <van-swipe-item v-for="(image, index) in images" :key="index" @click="onClick">
        <img v-lazy="image.image" width="100%"/>
      </van-swipe-item>
    </van-swipe>
  </div>`

**Comment by chenjiahan** [comment]
建议在子元素上监听事件，或者使用 click.native

**Comment by TingYinHelen** [comment]
如果在子元素上监听，滑动的时候就触发点击事件，滑动就是失效了

**Comment by TingYinHelen** [comment]
@chenjiahan 如果在子元素上监听，滑动的时候就触发点击事件，滑动就是失效了
