### ISSUE TITLE
[Bug Report]swipe横向滚动height属性不生效

### ISSUE THREAD

**Issue by ibubbo** [youzan/vant#1915]
**异常**
swipe横向滚动height属性不生效，只有是纵向滚动的时候才生效。

**代码图**
![image](https://user-images.githubusercontent.com/32586819/46786087-6afb1c00-cd66-11e8-83f2-25300cc9e0b9.png)
![image](https://user-images.githubusercontent.com/32586819/46786111-7b12fb80-cd66-11e8-8ddd-5fd7096ee28c.png)

**环境**
 - vue 2.5
 - vant 1.3.5

**Comment by zhuangxiaohui** [comment]
目前解决先设置`style =“height：100%;”`

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 1.3.10 版本修复
