### ISSUE TITLE
[Feature Request]希望Button组件能直接加url

### ISSUE THREAD

**Issue by ywfwj2008** [youzan/vant#1918]
现在按钮点击跳转都需要用一个click事件去完成，很不方便，希望大老板改进一下，button里面加个url属性就可以当做链接使用

**Comment by chenjiahan** [comment]
将 `native-type` 属性设置成 a 标签，就可以使用 url

**Comment by ywfwj2008** [comment]
怎么设置？下面这样也不行啊？
`<van-button native-type="a" url="http://www.baidu.com">确认</van-button>`

**Comment by chenjiahan** [comment]
sorry 上面打错了，正确用法是这样：
```html
<van-button tag="a" href="http://www.baidu.com">确认</van-button>
```

**Comment by ywfwj2008** [comment]
明白了，感谢 ^_^
