### ISSUE TITLE
样式初始化中的box-sizing

### ISSUE THREAD

**Issue by leftstyle** [youzan/vant#192]
为什么要设置
```
* {
  box-sizing: content-box;
}
```

这样设置导致了很多问题。这个属性设置为`border-box`，更合理一些。

**Comment by YYQ8023** [comment]
@leftstyle 在自己项目的reset.css中设置一下 border-box即可。不过官方能改是最好的。

**Comment by leftstyle** [comment]
@YYQ8023 直接修改会不会影响vant组件的使用呢？

**Comment by YYQ8023** [comment]
@leftstyle 我目前的项目覆盖了没有产生影响，我之前用的一个UI组件库的resetCss里也是 
`* {
  box-sizing: content-box;
}`

**Comment by leftstyle** [comment]
@YYQ8023 OK，多谢。希望官方能回应一下这个问题。

**Comment by chenjiahan** [comment]
@leftstyle Vant 的所有组件都是不依赖 reset.css 中的样式的，因此在项目中使用 border-box 还是 content-box 完全取决于使用者，对组件样式不会产生影响。

目前只存在一种方式会引入 vant 中 reset.css，就是直接在项目中完整地引入 vant-css。对于这种情况，建议将引入方式改为按需引入，减少不必要的代码引入。vant-css 这边也会在下个大版本中移除对 reset.css 的默认引用。

**Comment by leftstyle** [comment]
@chenjiahan I see.谢谢。
