### ISSUE TITLE
Slider滑块不能自定义区间值?

### ISSUE THREAD

**Issue by cn-zx** [youzan/vant#1920]
Slider滑块的区间值只能是0-100？
不能自定义设置？
min 和 max 是设置滑动最大最小值

**Comment by chenjiahan** [comment]
不行喔，Slider 用于 0 - 100 的范围选择，其他数值可以自行转换

**Comment by yintaofeng** [comment]
> 不行喔，Slider 用于 0 - 100 的百分比选择，其他数值可以按照百分比自行转换

那怎么转换百分比呢 转换百分比就走不动了

**Comment by chenjiahan** [comment]
现在可以指定区间值了

**Comment by yintaofeng** [comment]
我想除以 然后结果让百分比一点一点上加&nbsp; 走不动




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午3:59
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"爱里承欢"<1214686818@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] Slider滑块不能自定义区间值? (#1920)





 
现在可以指定区间值了
