### ISSUE TITLE
[Bug Report]Card组件中的 desc 内容如果过长的话会导致页面错位

### ISSUE THREAD

**Issue by ywfwj2008** [youzan/vant#1928]
**问题描述**
Card组件中的 desc 内容如果过长的话会导致页面错位

**截图**
<img width="416" alt="wechatimg623" src="https://user-images.githubusercontent.com/3824330/46878783-b43a9100-ce76-11e8-8d9d-76662f858bac.png">

**Comment by chenjiahan** [comment]
感谢反馈，下个版本修复此问题

**Comment by chenjiahan** [comment]
已在 1.3.8 版本修复
