### ISSUE TITLE
小程序省市区选择器的第一个选择不了

### ISSUE THREAD

**Issue by dxlani** [youzan/vant#1929]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: iphone8p
 - Browser: 谷歌
 - Vant Version: 最新

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
Vant Weapp 0.4.0 版本已修复这个问题
