### ISSUE TITLE
使用 babel-plugin-import 引入组件报错

### ISSUE THREAD

**Issue by liudake** [youzan/vant#193]
按照官网的作法
安装 babel-plugin-import 插件
npm i babel-plugin-import -D
// 在 .babelrc 或 babel-loader 中添加插件配置
{
  "plugins": [
    ["import", { "libraryName": "vant", "style": true }]
  ]
}
问题 在 .babelrc中只要添加 
 ["import", { "libraryName": "vant", "style": true }]
然后npm run dev 就开始报错了

报错主要说是在 main.js 找不到 “import” 相对于目录

报错的代码

 error  in ./src/main.js
Module build failed: Error: Couldn't find preset "import" relative to directory "/Users/xxxxxxx/Desktop/xxxxxx"

**Comment by chenjiahan** [comment]
@liudake 请确认你的 node_modules 中是否已安装了 babel-plugin-import

**Comment by liudake** [comment]
谢谢，已解决了
