### ISSUE TITLE
返回当前页后Swipe的图片显示不了

### ISSUE THREAD

**Issue by ibubbo** [youzan/vant#1931]
**Describe the bug**
使用vue写移动端的网页时，进入详情页有一个video标签，我把视频全屏播放后返回列表页，此时列表页的轮播图就没有了

**Screenshots**
这是刚开始的列表页：
![image](https://user-images.githubusercontent.com/32586819/46924765-49e24600-d05a-11e8-9227-98456d43d30d.png)
点击进去查看详情，并且把视频全屏播放后：
![image](https://user-images.githubusercontent.com/32586819/46924769-51a1ea80-d05a-11e8-85d3-11c57521ba20.png)
返回，列表页就变成这样了，轮播图不见（我没有给swipe任何样式）
![image](https://user-images.githubusercontent.com/32586819/46924773-5b2b5280-d05a-11e8-8322-8138acbbbaab.png)
调整高度也没有用，检查了img数组也都是存在的，为啥会显示成这样

**Environment**
 - vue 2.5
 - Vant 1.3.5

**Comment by wungjyan** [comment]
我也是轮播组件问题，点击输入框时，轮播图消失

**Comment by chenjiahan** [comment]
不规范的 issue，建议提供 jsfiddle
