### ISSUE TITLE
Card 组件 desc 过长时，文字溢出

### ISSUE THREAD

**Issue by zaxlct** [youzan/vant#1933]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Card 组件 desc 过长时，文字溢出
![image](https://user-images.githubusercontent.com/14342431/46996005-a1151300-d14d-11e8-928c-c3cf5716119c.png)

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: Mac OS 
 - Browser: chrome
 - Vant Version: 1.3.7

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
重复 issue https://github.com/youzan/vant/issues/1928
