### ISSUE TITLE
Slider max 参数大于一百时，元素宽度超出父元素

### ISSUE THREAD

**Issue by xxyuze** [youzan/vant#1936]
**Describe the bug**
A clear description of what the bug is.
Slider max 参数大于一百时，元素宽度超出父元素

**Screenshots**
Add screenshots to help explain your problem.

![default](https://user-images.githubusercontent.com/17399581/47004336-e6dcd600-d163-11e8-9580-ea9abf79b8f0.gif)

**Environment**
 - Device: 微信开发者工具
 - Browser:  微信开发者工具
 - Vant Version: 1.3.5

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/xxyuze/kmwre3y4/

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/1920
