### ISSUE TITLE
picker在ios中滑动效果有点卡，不流畅，可否增加一下动画效果

### ISSUE THREAD

**Issue by itrui** [youzan/vant#1937]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
在picker中滑动数据不流畅

**Describe the solution you'd like**
希望能滑动流畅，mintui

**What does the proposed API look like?**

**Comment by chenjiahan** [comment]
暂无计划支持
