### ISSUE TITLE
用按需引入的方式引入vant

### ISSUE THREAD

**Issue by leejunwong** [youzan/vant#1939]
如题：按照官网快速入手中的按需引入后，报错：
node_modules/vant/es/button/style/index.js:1
(function (exports, require, module, __filename, __dirname) { import '../../vant-css/base.css';
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at r (/Users/wanglijun/Desktop/works/bishijie/coinness_vue/node_modules/vue-server-renderer/build.js:8341:16)
    at Object.<anonymous> (webpack:/external "vant/es/button/style":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 006da965049718bc4d7e:25:0)
    at Object.<anonymous> (server-bundle.js:969:79)
    at __webpack_require__ (webpack:/webpack/bootstrap 006da965049718bc4d7e:25:0)
    at Object.module.exports.__webpack_exports__.a (src/entry-server.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 006da965049718bc4d7e:25:0)

我的框架是vue的ssr，并没有用nuxt，我使用官方的ssr demo  [HackerNews Demo](https://github.com/vuejs/vue-hackernews-2.0/)

**Comment by chenjiahan** [comment]
webpack1 请勿配置 `libraryDirectory ` 属性

**Comment by leejunwong** [comment]
@chenjiahan 我的是webpack 3
`"dependencies": {
    "axios": "^0.18.0",
    "compression": "^1.7.1",
    "cross-env": "^5.1.1",
    "es6-promise": "^4.1.1",
    "express": "^4.16.2",
    "extract-text-webpack-plugin": "^3.0.2",
    "js-md5": "^0.7.3",
    "lru-cache": "^4.1.1",
    "qs": "^6.5.2",
    "route-cache": "0.4.3",
    "serve-favicon": "^2.4.5",
    "vant": "^1.3.7",
    "vue": "^2.5.16",
    "vue-i18n": "^8.0.0",
    "vue-router": "^3.0.1",
    "vue-server-renderer": "^2.5.16",
    "vuex": "^3.0.1",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.6",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-import": "^1.9.1",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "chokidar": "^1.7.0",
    "css-loader": "^0.28.7",
    "file-loader": "^1.1.5",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "less": "^3.0.1",
    "less-loader": "^4.1.0",
    "rimraf": "^2.6.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "sw-precache-webpack-plugin": "^0.11.4",
    "url-loader": "^0.6.2",
    "vue-loader": "^15.0.0-beta.1",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.8.1",
    "webpack-dev-middleware": "^1.12.0",
    "webpack-hot-middleware": "^2.20.0",
    "webpack-merge": "^4.1.1",
    "webpack-node-externals": "^1.6.0",
    "yaml-loader": "^0.5.0"
  }`

**Comment by FJHou** [comment]
差不多的问题，我在用使用vue官网提供的ssr教程配置项目。当我使用babel-plugin-import引入vant的时候会出现
![import-err](https://user-images.githubusercontent.com/22517598/64677398-0d0d1200-d4aa-11e9-9fc5-c98949e653c6.png)
如果我用手动按需引入组件的时候会出现
![import-err2](https://user-images.githubusercontent.com/22517598/64677729-bbb15280-d4aa-11e9-86f0-65c8442c615f.png)
我分析的原因是在js文件里使用import引入css文件导致的，官方提供了[解决办法](https://ssr.vuejs.org/zh/guide/css.html#%E4%BB%8E%E4%BE%9D%E8%B5%96%E6%A8%A1%E5%9D%97%E5%AF%BC%E5%85%A5%E6%A0%B7%E5%BC%8F)，但是这个办法比较古老了，使用的插件（extract-text-webpack-plugin）是只支持webpack3.x，最新脚手架是4.x。在git里找了好几脚基于cli3改造ssr的项目，使用自动按需引入都出现了上面的问题。不知道能否提供下解决思路。

**Comment by StriverF** [comment]
我用vue-cli4 搭建SSR同构项目，按需引入Vant也遇到类似报错，我的解决方案是
项目根目录文件babel.config.js配置如下
```
plugins: [
  ["import", {
    "libraryName": "vant",
    "style": true
  }, 'vant']
]

// or
plugins: [
  ['import', {
    libraryName: 'vant',
      style: (name) => {
        return `${name}/style/less.js`
      },
    }, 'vant']
]
```
具体效果可以参考我的[demo](https://github.com/StriverF/vue-cli4-ssr)
