### ISSUE TITLE
AddressEdit已传入areaList但编辑数据无法显示地址

### ISSUE THREAD

**Issue by Licoy** [youzan/vant#1941]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
使用AddressEdit已传入areaList，并设置好addressInfo中的数据，其他的数据正常显示唯独地区不会显示：

**Screenshots**
![111.png](https://i.loli.net/2018/10/17/5bc6ad86db168.png)

**Environment**
 - Device: Windows 7
 - Browser:  Chrome 69
 - Vant Version:  1.3.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
需要传入 areaCode

**Comment by NBAUser** [comment]
解决了嘛。我传入areaCode也不行

**Comment by XJayXU** [comment]
是不是地址列表arealist都没加载完成就直接赋值addressInfo了呢，给300毫秒后再获取地址详情接口是不是好了呢？
