### ISSUE TITLE
field 通过ref 获取焦点 报错。

### ISSUE THREAD

**Issue by uddsoft** [youzan/vant#1943]
` <van-field
            v-model="phone"
            label="手机号"
            placeholder="请输入手机号"
            :error-message=errormessage
            type="tel"
            required
            error
            ref="UserTel"
          />`
获取焦点代码：
`this.$refs.UserTel.focus()`

**Comment by chenjiahan** [comment]
不规范的 issue

**Comment by 750973092** [comment]
请问解决了吗
