### ISSUE TITLE
滑动单元格问题

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#195]
我的滑动单元格里是一个地址：
![image](https://user-images.githubusercontent.com/22813922/31430632-0c0cb802-aea4-11e7-9bbe-8e9a467d9391.png)
向左滑之后会出现“删除”按钮：
![image](https://user-images.githubusercontent.com/22813922/31430669-25abb826-aea4-11e7-9eb3-e5d103fea713.png)
点击右侧的小箭头ye'ke'y也可以出现“删除”按钮：
![image](https://user-images.githubusercontent.com/22813922/31430702-3ba38d52-aea4-11e7-85ba-c0e6debe87e9.png)
实现的原理是修改translate3d值，例如给一个 `translate3d(-100px, 0px, 0px)` ，就会左滑出100px，再点一次会清零translate3d，就是说会弹回去。
问题来了：通过点击弹出来，不能滑回去，滑出来的可以点击弹回去。
怎么才能让滑动和点击都通用呢？

**Comment by chenjiahan** [comment]
@YYQ8023 不是很理解你的意思，请问你的滑动单元格是自己实现的还是使用了 Vant 中的 CellSwipe 组件？

**Comment by YYQ8023** [comment]
@chenjiahan 使用了CellSwipe组件，这个组件也是通过修改 ‘van-cell-swipe__wrapper’这个元素的translate3d来实现效果的（？），修改的方式是touch事件（？），而我给这个cellswipe里面的内容加了一个click事件，点击之后修改translate3d值，来实现和touch相同的效果。可是问题是click修改translate3d之后，touch事件不起作用了，即不能再以滑动的方式滑回去。

**Comment by chenjiahan** [comment]
@YYQ8023 组件的 translate3d 是由内部变量控制的，不能直接在外部修改 DOM 上的 translate3d 值。你可以给 CellSwipe 组件提个 PR，加上你所需要的 click 事件

**Comment by YYQ8023** [comment]
@chenjiahan 好的，明白了。我再去review一下。
