### ISSUE TITLE
address-edit 中的areaPopup不可控制

### ISSUE THREAD

**Issue by Sliect** [youzan/vant#1953]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
addressEdit模块里建议将showAreaPopup改为props属性, 不然如果其值为true时，后退则areaPopup不可控制
**Describe the solution you'd like**
开放showAreaPopup的值

**What does the proposed API look like?**
showAreaPopup: Boolean

**Comment by chenjiahan** [comment]
暂无计划支持，改为 props 的话会造成不兼容更新

**Comment by Sliect** [comment]
是否只能自己拼接各个组件？
