### ISSUE TITLE
[Bug Report]Toast多实例模式内存泄露

### ISSUE THREAD

**Issue by gongzhibin** [youzan/vant#1954]
**Describe the bug**
Toast多实例模式存在内存泄露的问题，实例可以复用，toast清除之后应该删除浏览器生成的DOM

**Screenshots**
![image](https://user-images.githubusercontent.com/4123433/47153394-1fbaad80-d312-11e8-91df-f46ed7e8db2c.png)

**Comment by chenjiahan** [comment]
后续会优化这个问题

**Comment by gongzhibin** [comment]
好的，太棒了。之前忙没注意看，可以的话我也试着给你们提交一些代码

**Comment by chenjiahan** [comment]
已经在 1.3.9 版本修复咯

**Comment by gongzhibin** [comment]
点赞
