### ISSUE TITLE
轮播组件与输入框冲突

### ISSUE THREAD

**Issue by wungjyan** [youzan/vant#1955]
**Describe the bug**
项目首页使用了轮播组件，在其他页面使用了输入框组件，当我点击输入框时，回到首页的时候轮播图消失，不知道是不是我个例，还是我使用方法不对

**Comment by wungjyan** [comment]
好像跟页面缓存了有关系，用了keep-alive，但是只有输入框这个组件会影响

**Comment by chenjiahan** [comment]
从描述来看应该不是组件的问题，建议看下是不是其他原因
