### ISSUE TITLE
Area组件，切换省以后，在不切换二级市的情况下，获取的数据不对

### ISSUE THREAD

**Issue by jang-git** [youzan/vant#1957]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by jang-git** [comment]
onChangea (picker, value, index) {
      this.$toast(JSON.stringify(value))
}
只切换省，获取的市 不对，怎么解决

**Comment by chenjiahan** [comment]
不规范的 issue
