### ISSUE TITLE
Collapse 折叠面板content里有图片时，高度计算错误

### ISSUE THREAD

**Issue by nsnds** [youzan/vant#1960]
![image](https://user-images.githubusercontent.com/25788175/47292234-eeefb680-d638-11e8-9df9-7fb9376d777f.png)
展开时图片已插入dom，但样式还未生效(应该可以这样说吧)，此时获取的高度并不包含图片。

版本：v1.3.8

**Comment by chenjiahan** [comment]
不规范的 issue
