### ISSUE TITLE
vant的设计稿宽度是多少?

### ISSUE THREAD

**Issue by mz5210** [youzan/vant#1962]
我是一个Vue初学者,我把项目中的单位都转化为了vm,可是vant的显示效果出现了问题,所以想问一下vant的设计稿宽度是多少?或者我这样的情况有其他的解决方法么

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/1181

**Comment by f43310** [comment]
vant 的设计稿应该是375px 的。
