### ISSUE TITLE
下拉加载组件中使用tabs组件, sticky定位无效

### ISSUE THREAD

**Issue by leo-wj910729** [youzan/vant#1963]
**Describe the bug**
下拉加载组件中使用tabs组件, sticky定位无效
**Screenshots**
因为下拉组件会生成一个带行内css属性的包裹元素,其元素上会有transfrom属性
而transfrom属性为父元素时,Position:fixed属性定位无效
**Environment**
 - Device: 所有
 - Browser: 所有
 - Vant Version: 1.3.8

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/1146
