### ISSUE TITLE
AddressEdit 地址编辑 希望增加 默认地址值变化事件

### ISSUE THREAD

**Issue by tudanqz** [youzan/vant#1966]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
默认值按钮切换的时候希望有事件触发
A clear description of what the problem is.

**Describe the solution you'd like**
场景：切换默认地址

**What does the proposed API look like?**
@action="method()"
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
在 1.3.9 版本新增了 change-default 事件
