### ISSUE TITLE
ImagePreview 图片预览

### ISSUE THREAD

**Issue by w550** [youzan/vant#1968]
ImagePreview 图片预览 既然复用了 Swipe 轮播 可以考虑把 "自定义指示器" 也一起 带过来吗？

**Comment by chenjiahan** [comment]
具体想要的 API 形式是？

**Comment by xujiujiu** [comment]
> 具体想要的 API 形式是？

既然已经把指示器带来了，能不能把指令暴露出去？比如图片预览的show-indicators这个值我们的业务就非常需要

**Comment by chenjiahan** [comment]
不是有 showIndex 属性吗

**Comment by chenjiahan** [comment]
已在 1.3.10 版本支持 showIndicators 属性
