### ISSUE TITLE
在UC浏览器使用input框有问题

### ISSUE THREAD

**Issue by seekei** [youzan/vant#1975]
**Describe the bug**
在UC浏览器使用input框有问题，如果input框靠页面下方，弹出系统键盘时会遮住输入内容。

**Screenshots**
![img_4195](https://user-images.githubusercontent.com/19527355/47440098-1cc32f80-d7e0-11e8-9fa0-4ff8924fdea3.PNG)

**Environment**
 - Device: IOS系统12.0
 - Browser:UC浏览器 
 - Vant Version: 官网demo

**Reproduce**
在iphone8打开UC浏览器查看VANT官网的fields，拉到下方input框输入，弹出系统键盘时会遮住输入内容。

**Comment by chenjiahan** [comment]
浏览器本身的问题，Field 不会单独去做兼容

**Comment by seekei** [comment]
但是为什么别的一些ui框架却没这个问题咧
