### ISSUE TITLE
官方文档的picker 的一个方法写错了

### ISSUE THREAD

**Issue by abaozhizhong** [youzan/vant#1980]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/
![image](https://user-images.githubusercontent.com/22359458/47500974-db418b80-d896-11e8-861a-20260c9fc78f.png)

**Comment by chenjiahan** [comment]
感谢反馈，后续修正

**Comment by chenjiahan** [comment]
已在 1.3.10 版本修复
