### ISSUE TITLE
ImagePreview文档貌似错了

### ISSUE THREAD

**Issue by guweicong55** [youzan/vant#1981]
传入Object图片会不显示

**Comment by chenjiahan** [comment]
请升级到最新版再试

**Comment by budflower** [comment]
我已经长组，但依然不显示图片，但页码会显示。会报以下错误
vue.runtime.esm.js?2b0e:587 [Vue warn]: Error in beforeCreate hook: "TypeError: Cannot read property 'push' of undefined"

found in

---> <VanSwipeItem>
       <Root>
