### ISSUE TITLE
[Feature Request] Card组件增加点击事件，或者Url属性

### ISSUE THREAD

**Issue by ywfwj2008** [youzan/vant#1988]
**What problem does this feature solve?**
有个需求，订单列表中使用到了Card组件，点击组件就跳转到订单详情，目前虽然图片能加链接，还是不太方便

**Describe the solution you'd like**
Card组件增加点击事件，或者Url属性

**Comment by chenjiahan** [comment]
@click.native 即可

**Comment by VcStrong** [comment]
不管用，我试了一下，下列代码card中只有thumb-link点击图片管用。
`<van-panel>
      <van-card
                v-for="(grouponGood ,index) in shopInfos.grouponList"
                :key="index"
                :title="grouponGood.name"
                :desc="grouponGood.brief"
                :origin-price="grouponGood.retailPrice"
                :price="grouponGood.grouponPrice +'.00'"
                :thumb="grouponGood.picUrl"
                :thumb-link="goDetail(grouponGood.id)"
                :click-thumb="goDetail(grouponGood.id)"
                :click="goDetail(grouponGood.id)"
                @click.native="goDetail(grouponGood.id)">
        <div slot="tags"
             class="card__tags"
             @click.native="goDetail(grouponGood.id)">
          <van-tag plain
                   type="primary">
            {{grouponGood.grouponMember}}人成团
          </van-tag>
          <van-tag plain
                   type="danger">
            {{grouponGood.grouponDiscount}}元再减
          </van-tag>
        </div>
      </van-card>
      <div slot='header'>
        <van-cell-group>
          <van-cell title="团购专区"
                    isLink>
            <router-link to="/items/groupon"
                         class="text-desc">更多团购商品</router-link>
          </van-cell>
        </van-cell-group>
      </div>
    </van-panel>`
