### ISSUE TITLE
下拉刷新无法在谷歌浏览器调试模式下使用

### ISSUE THREAD

**Issue by liuyingbin19222** [youzan/vant#1989]
**Describe the bug**
A clear description of what the bug is.
我使用了vant ui  @的下拉刷新组件，在谷歌浏览器调试模式下调试时，鼠标下拉无法实现刷新。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: chrome 
 - Browser: chrome 
 - Vant Version: 1.3.9

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
`    <van-pull-refresh v-model="isLoading" @refresh="onRefresh">
            <p>刷新次数{{count}}</p>
        </van-pull-refresh>

 export default {
        name:'mycourse',
        data(){
            return {
                datalist:[],
                allCourse:[],
                courseCurent:[],
                count: 0,
                index:0,
                courseNumber:[],
                isLoading:false
            }
        },
methods:{
onRefresh() {
                console.log("调用");
                setTimeout(() => {
                    this.$toast('刷新成功');
                    this.count++;
                    this.isLoading = false;
                    this.index++;
                    this.getAllCourse()
                // this.$toast('刷新成功');
                }, 500);
            },
}

`

**Comment by chenjiahan** [comment]
打开 chrome 手机模式就行
