### ISSUE TITLE
Toast实例clear后没有清除页面的禁止背景点击状态

### ISSUE THREAD

**Issue by lldf1984** [youzan/vant#1990]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Toast在1.3.9修复了多实例模式内存泄露，如果某一实例使用forbidClick属性，在实例被删除后没有清除页面不可点击状态。

**Screenshots**

![qq 20181029150053](https://user-images.githubusercontent.com/32194663/47634175-784c3f00-db8b-11e8-923f-88837bda3e97.jpg)

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.3.10 版本修复
