### ISSUE TITLE
van-tabs中吸顶offset-top设置后，滚动页面就沪出现闪现，总是在底部和顶部不停切换

### ISSUE THREAD

**Issue by dobetterdomore** [youzan/vant#1997]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
<van-tabs @click="onClick" sticky offset-top="50">
我把代码已经上传到https://jsfiddle.net/dfarLdko/453/，请查看一下，不停闪现
**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: Chrome 版本 3.0.8.8
 - Vant Version: vant 1.3.10

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/453/

**Comment by chenjiahan** [comment]
offset-top 写错了，不是 string 类型，是 number 类型
请使用 :offset-top="50"

**Comment by xiaoshidetaikuai** [comment]
我试了offset-top 为什么chrome切换分辨率的时候会上移一段位置呢？
