### ISSUE TITLE
AddressEdit  中Area 如何赋值初始值

### ISSUE THREAD

**Issue by smilexlong** [youzan/vant#2000]
**What problem does this feature solve?**
AddressEdit  无法通过addressInfo 中的province，city，county，areaCode赋值初始值

**Describe the solution you'd like**
能通过回调方法或者值对Area 组件进行初始化赋值

**What does the proposed API look like?**
addressInfo  中有可以直接初始化值得地方

**Comment by smilexlong** [comment]
需要传areaCode string ，已解决

**Comment by ialmost** [comment]
为何我传的时 string 也不行
