### ISSUE TITLE
希望添加List和picker结合的组件

### ISSUE THREAD

**Issue by wucuida** [youzan/vant#2001]
**What problem does this feature solve?**
当使用picker时，有时候不希望一次加载完全部数据，而想边刷新边请求数据

**Describe the solution you'd like**
当picker选择时，随着下拉选择，能像list一样触发onload, 动态增加数据.

**What does the proposed API look like?**

| 参数 | 类型 |  说明 |
| ----  | ---- | ---- |
|onload| function | 动态加载数据的函数 |
| bottom | int| 距离底部多少刷新数据 |

**Comment by chenjiahan** [comment]
暂无计划支持
