### ISSUE TITLE
希望 Area 省市区选择 的数据格式能支持用对象的形式

### ISSUE THREAD

**Issue by lijiliang** [youzan/vant#2002]
希望 Area 省市区选择 的数据格式能支持用对象的形式

类似这样：
[
  {
      "value": "1",
      "label": "北京",
      "children": [
        {
          "value": "1",
          "label": "北京市",
          "children": [
            {
              "value": "2",
              "label": "西城区",
              "children": []
            },
            {
              "value": "3",
              "label": "崇文区",
              "children": []
            },
            {
              "value": "4",
              "label": "宣武区",
              "children": []
            },
            {
              "value": "5",
              "label": "朝阳区",
              "children": []
            },
            {
              "value": "6",
              "label": "丰台区",
              "children": []
            },
            {
              "value": "7",
              "label": "石景山区",
              "children": []
            },
            {
              "value": "8",
              "label": "海淀区",
              "children": []
            },
            {
              "value": "9",
              "label": "门头沟区",
              "children": []
            },
            {
              "value": "10",
              "label": "房山区",
              "children": []
            },
            {
              "value": "11",
              "label": "通州区",
              "children": []
            },
            {
              "value": "12",
              "label": "顺义区",
              "children": []
            },
            {
              "value": "13",
              "label": "昌平区",
              "children": []
            },
            {
              "value": "14",
              "label": "大兴区",
              "children": []
            },
            {
              "value": "15",
              "label": "怀柔区",
              "children": []
            },
            {
              "value": "16",
              "label": "平谷区",
              "children": []
            },
            {
              "value": "17",
              "label": "密云县",
              "children": []
            },
            {
              "value": "18",
              "label": "延庆县",
              "children": []
            },
            {
              "value": "2999",
              "label": "东城区",
              "children": []
            }
          ]
        }
      ]
    }
]

**Comment by lijiliang** [comment]
类型： Array<{value, label, children: Array}>

**Comment by chenjiahan** [comment]
暂无计划支持，可以自己转换数据格式喔

**Comment by lijiliang** [comment]
好
