### ISSUE TITLE
datetimepicker组件的currentdate不生效

### ISSUE THREAD

**Issue by yopeng** [youzan/vant#2009]
![qq 20181101105852](https://user-images.githubusercontent.com/17605103/47830053-2ee73400-ddc5-11e8-9431-93f8dca2557f.png)
如附件截图，currentDate指定为当前时间了，但在手机上看到的datetimepicker弹出层的默认时间是系统mindate；不知道是bug还是使用问题，还请帮忙解答下，谢谢！

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle
