### ISSUE TITLE
1rem=多少px

### ISSUE THREAD

**Issue by xiaomiwujiecao** [youzan/vant#2015]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
1rem=?px

**Describe the solution you'd like**
vant默认的转换是1rem=多少px

**What does the proposed API look like?**

**Comment by litmonw** [comment]
Vant 没有规定 1rem = ?px。
rem 与 px 比例 是由 html 根元素的 font-size 决定的，通常浏览器默认 font-size: 16px，即 1rem = 16px;

**Comment by xiaomiwujiecao** [comment]
> Vant 没有规定 1rem = ?px。
> rem 与 px 比例 是由 html 根元素的 font-size 决定的，通常浏览器默认 font-size: 16px，即 1rem = 16px;

非常感谢
