### ISSUE TITLE
slot delimiter问题

### ISSUE THREAD

**Issue by circlewang** [youzan/vant#2016]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
我在js中定义delimiter为['[[',']]']，防止与php的模板冲突，在<van-tab>组件中套了三层循环，数据却不能展示出来,但在首页，组件中套了一层循环就可以用[[]]将数据进行展示，我不确定是循环次数多的问题还是组件的问题，所以希望您看到后给我一个答复

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/38183866/47889146-63212a00-de83-11e8-9a66-e53493100f63.png)
![image](https://user-images.githubusercontent.com/38183866/47889160-73390980-de83-11e8-8035-b0c064d00f28.png)
转换为{{}}后就可以了，
![image](https://user-images.githubusercontent.com/38183866/47889192-9e235d80-de83-11e8-8c0c-734d9dad712c.png)
![image](https://user-images.githubusercontent.com/38183866/47889196-aa0f1f80-de83-11e8-887c-f79a7542a3ff.png)

**Environment**
 - 普通的html页面加vant组件
 - Browser: 
 - Vant Version: 最新版

**Comment by circlewang** [comment]
希望可以尽快给一个答复，邮箱2353541159@qq.com

**Comment by chenjiahan** [comment]
这个问题应该与组件无关
