### ISSUE TITLE
能多加些加载图标就好了

### ISSUE THREAD

**Issue by Obacm** [youzan/vant#202]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by cookfront** [comment]
加载图标是指loading的样式，还是多加一些icon呀？

**Comment by Obacm** [comment]
loading的样式

**Comment by cookfront** [comment]
嗯，你那边有喜欢的loading样式么？我们后期会补充一些

**Comment by Obacm** [comment]
微信的loading样式我挺喜欢的。

**Comment by chenjiahan** [comment]
在 0.10.8 中新增了一种 loading 样式
