### ISSUE TITLE
vant的ImagePreview动画有时候会在微信失效

### ISSUE THREAD

**Issue by wuxn** [youzan/vant#2020]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
1、vant的ImagePreview动画有时候会在微信失效
2、会不会是transition和transform没加前缀，微信浏览器是webkit内核，如果没加上-webkit-前缀，是不是会出现动画失效的情况？

**Screenshots**
![image](https://user-images.githubusercontent.com/13825446/47903342-874e2c80-debe-11e8-8cb7-88be599af7e5.png)

**Environment**
 - Device: iPhone 7
 - Browser: 微信
 - Vant Version: 1.3.9

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
Vue 会自动补全前缀，所以应该不是这个问题，建议重启微信试试
