### ISSUE TITLE
复选框 group 组合时候，max 是1的时候，无法勾选 复选框

### ISSUE THREAD

**Issue by zlzdp** [youzan/vant#2022]
**Describe the bug**
<van-checkbox-group v-model="result2" :max="1">
        <van-checkbox>
复选框 group 组合时候，max 是1的时候，无法勾选 复选框，每一个都点不动。
不知道怎么了。
max 不能是1？

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: windows
 - Browser: chrome
 - Vant Version: 1.3.10

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by tigerluhu1** [comment]
我也觉得这是个Bug,但是官方说不支持这么用，想用单选去用单选框

**Comment by chenjiahan** [comment]
目前的逻辑，max = 1 的时候只能取消勾选，不能选中第二个 checkbox。如果是单选的话可以用 Radio，或者自己控制 Checkbox v-model 绑定的值
