### ISSUE TITLE
期望van-field组件增加属性autocomplete

### ISSUE THREAD

**Issue by fengxinming** [youzan/vant#2029]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
目前van-field没有支持全部的input属性

**Describe the solution you'd like**
目前我想加一个属性autocomplete，但是发现api上不支持

**What does the proposed API look like?**
期望可以支持所有的input属性

**Comment by chenjiahan** [comment]
文档中有标注的，field 默认支持所有原生属性

**Comment by fengxinming** [comment]
props: {
    value: [String, Number],
    icon: String,
    label: String,
    error: Boolean,
    center: Boolean,
    isLink: Boolean,
    leftIcon: String,
    readonly: Boolean,
    required: Boolean,
    clearable: Boolean,
    labelAlign: String,
    inputAlign: String,
    onIconClick: Function,
    autosize: [Boolean, Object],
    errorMessage: String,
    type: {
      type: String,
      default: 'text'
    },
    border: {
      type: Boolean,
      default: true
    }
  }
 
这里没有`autocomplete `属性@chenjiahan
