### ISSUE TITLE
tabs标签个数建议

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#203]
组件默认是4个，超过4个就需要左右滑动，可是有些时候不希望滑动。
期望：组件可以接收一个阈值，超出了才是滑动。
目前我是这样解决的：

`.van-tabs__swipe
 {
    transform: translate3d(0, 0, 0) !important;
}
.van-tabs__swipe .van-tab {
    flex: 0 0 20% !important
/* 默认4个的时候是 flex:0 0 22% ，我是5个*/
}`

**Comment by cookfront** [comment]
嗯嗯 谢谢建议，我加个参数的配置，超过这个数量就可以滑动。

**Comment by YYQ8023** [comment]
@cookfront 其实用处不大，不过还是蟹蟹！点赞！
