### ISSUE TITLE
swipe

### ISSUE THREAD

**Issue by xiao0413** [youzan/vant#2031]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by xiao0413** [comment]
swipe 滑动触发点击事件

**Comment by qianzhaoy** [comment]
使用了 fastclick 了吧. 在 swipe 上加 `needsclick` 的 class. 应该能解决. 或者别用 fastclick 了
