### ISSUE TITLE
tag无点击事件吗？

### ISSUE THREAD

**Issue by yatniel7** [youzan/vant#2034]
**Describe the bug**
tag没有点击事件吗？

**Screenshots**
tag没有点击事件吗？

**Environment**
 - Device: mac
 - Browser: chrome 
 - Vant Version:  1.4.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by ywfwj2008** [comment]
可以用click.native
