### ISSUE TITLE
[Feature Request] Swiper的滑动步长(offset)可否改成在配置中设置，目前源码中默认是50

### ISSUE THREAD

**Issue by jerry1991** [youzan/vant#2035]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by jerry1991** [comment]
当swiper整屏切换时，swiper内部是div，div是垂直滚动， 在移动端上下滑动的时候，会触发swiper的左右滚动， 用户体验会很不好

**Comment by chenjiahan** [comment]
这个体验问题我们下个版本直接在组件内部优化下，offset 暂时没计划抽象成 api

**Comment by chenjiahan** [comment]
已在 1.4.3 版本优化手势操作
