### ISSUE TITLE
环形进度条微信内置浏览器中位置跑偏

### ISSUE THREAD

**Issue by geng452654716** [youzan/vant#2037]
bug描述
真机测试时，微信内置浏览器 环形进度条位置跑偏
机型： 荣耀9,
微信版本：6.7.3

**Comment by geng452654716** [comment]
![679831151731712904](https://user-images.githubusercontent.com/20813301/48050109-ec19c780-e1db-11e8-9c9d-83e51c68ae2a.jpg)

**Comment by blogape** [comment]
这个BUG啥时候能解决啊 我昨天也提了。。。。

**Comment by blogape** [comment]
@chenjiahan  您好这个问题啥时候能解决哟 我昨天也出现了这个问题

**Comment by chenjiahan** [comment]
已在 1.4.3 版本修复

**Comment by lvlvlv1** [comment]
> 我现在最新版的也是这样  1.6.4

**Comment by lvlvlv1** [comment]
我用的最新版1.6.4  还是没有兼容哦
