### ISSUE TITLE
在iphone手机，QQ内置浏览器使用popup组件内插入多个field时，获取焦点软键盘弹起时底部会被多顶上去一部分。

### ISSUE THREAD

**Issue by comeOutBing** [youzan/vant#2038]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在iphone手机，QQ内置浏览器使用popup组件内插入多个field时，获取焦点软键盘弹起时底部会被多顶上去一部分。

**Screenshots**
![_20181106170154](https://user-images.githubusercontent.com/22164796/48053447-b8439f80-e1e5-11e8-9bac-9fce69fada07.jpg)
![_20181106170154](https://user-images.githubusercontent.com/22164796/48053458-bd085380-e1e5-11e8-8fb9-8b2f0f5b1cef.jpg)

**Environment**
 - Device:  ios12，
 - Browser: QQ内置浏览器
 - Vant Version: 1.4.2

**Reproduce**
1.如图片所示，一个Popup组件内插入多个field组件，如果 我从上往下获取点击是没啥问题的，但如果我直接获取最后一个Field组件的焦点的话，会出现上图光标显示在外面的情况

**Comment by comeOutBing** [comment]
![_20181106170200](https://user-images.githubusercontent.com/22164796/48053708-52a3e300-e1e6-11e8-95be-066cc28384b5.jpg)
图片重复了一张，补上

**Comment by chenjiahan** [comment]
这个是浏览器的问题，一般在  fixed 元素内部的有输入框的时候出现，我们没有什么解决方法

**Comment by comeOutBing** [comment]
感觉可以开个入口配置position 因为在用户在body下无滚动条的情况选择absolute可能更好
