### ISSUE TITLE
badge

### ISSUE THREAD

**Issue by budflower** [youzan/vant#2040]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
badge做不了交互，key索引值获取不到。

**Screenshots**
<img width="689" alt="image" src="https://user-images.githubusercontent.com/18157644/48057740-bda5e780-e1ef-11e8-9da4-6d7badee206a.png">

<img width="423" alt="image" src="https://user-images.githubusercontent.com/18157644/48057807-e75f0e80-e1ef-11e8-9c1c-be07b21281b4.png">

**Environment**
 - Device: MAC
 - Browser: google
 - Vant Version: v1.4.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle

**Comment by budflower** [comment]
什么是 jsfiddle ？
