### ISSUE TITLE
SwipeCell 滑动单元格，划出部分内的组件能对齐吗？

### ISSUE THREAD

**Issue by donething** [youzan/vant#2041]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
在SwipeCell划出部分内，添加了van-button和van-switch两个组件。请问怎么让这两个组件左右水平对齐呢？
![vant-swip-cell-comp-align](https://user-images.githubusercontent.com/11867885/48072330-39675a80-e217-11e8-8b2b-7993b4c91003.png)

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by qianzhaoy** [comment]
组件库只提供 slot . 该怎么对齐, 你自己去布局呀. 百度一下 水平垂直居中对齐的方法, 太多了. 跟组件库没关

**Comment by donething** [comment]
> 组件库只提供 slot . 该怎么对齐, 你自己去布局呀. 百度一下 水平垂直居中对齐的方法, 太多了. 跟组件库没关

谢谢，我找找。
