### ISSUE TITLE
在list 下拉加载时如果让cell宽度设为50%、float:left；这样的话就会让页面打开时加载所有页面，一次性全部加载完，这个怎么处理！

### ISSUE THREAD

**Issue by LuSir001** [youzan/vant#2042]
**Describe the bug**
在list 下拉加载时如果让cell宽度设为50%、float:left；这样的话就会让页面打开时加载所有页面，一次性全部加载完，这个怎么处理！

**Comment by chenjiahan** [comment]
不规范的 issue
