### ISSUE TITLE
IE EDGE浏览器 报错 SCRIPT1028: Expected identifier, string or number

### ISSUE THREAD

**Issue by xjf348060793** [youzan/vant#2044]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
IE EDGE浏览器 报错 SCRIPT1028: Expected identifier, string or number，
错误指向 popup里面的 manager.js 54行
其他浏览器无问题

**Screenshots**
Add screenshots to help explain your problem.
![Uploading image.png…]()
![6c70a5b9-7cb7-4d38-a6f5-60ba6a29ee4f](https://user-images.githubusercontent.com/22151955/48116117-06b57480-e2a0-11e8-8eb9-9b6ccd415b8f.png)

**Environment**
 -DELL PC
 - IE EDGE: 
 -  v1.3.4: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
请升级到 1.4.2 版本
