### ISSUE TITLE
Field 输入框没有很多属性，比如On-change事件，min-length\max-length事件

### ISSUE THREAD

**Issue by maxiaoqu** [youzan/vant#2045]
Field 输入框没有很多属性，比如On-change事件，min-length\max-length事件，这样操作起来很麻烦

方法名 | 参数 | 返回值 | 介绍
-- | -- | -- | --
focus | - | - | 获取输入框焦点
blur | - | - | 取消输入框焦点
-------------------------------------------------
但是没返回值啊！

**Comment by LynanBreeze** [comment]
**文档**
```
API
Field 默认支持 Input 标签所有的原生属性，比如 maxlength、placeholder、autofocus 等
Event
Field 默认支持 Input 标签所有的原生事件，如 focus、blur、keypress 等
```
onchange事件可以@change="yourMethod()"
值得话取v-model绑定的data

**Comment by LynanBreeze** [comment]
至于你上面的focus和blur是操作field的焦点的事件（主动），不是input的聚焦失焦事件（被动）。
