### ISSUE TITLE
vue-cli 3 下的van swipe 无法

### ISSUE THREAD

**Issue by qwe6499683** [youzan/vant#2049]
![1541579971 1](https://user-images.githubusercontent.com/30947867/48120035-e2f82b80-e2ab-11e8-9b3a-9ac8ee3eb4b0.jpg)

**Comment by qwe6499683** [comment]
![image](https://user-images.githubusercontent.com/30947867/48120074-00c59080-e2ac-11e8-9913-1a566eb2ab0c.png)

**Comment by chenjiahan** [comment]
不规范的 issue

**Comment by xuejiangjun** [comment]
通过外链形式引入vant，我也出现了同样的问题
