### ISSUE TITLE
iphone7，地址编辑组件中，弹出的选择地区的窗口左侧会显示不全

### ISSUE THREAD

**Issue by 383366204** [youzan/vant#2052]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
iphone7，地址编辑组件中，弹出的选择地区的窗口左侧会显示不全

**Screenshots**
![2q q n bvpjc 7c_f22x](https://user-images.githubusercontent.com/24775980/48130675-61fb5d00-e2c8-11e8-970f-ff24986e0c02.jpg)

**Environment**
 - Device: iphone7
 - Browser: 微信内置浏览器
 - Vant Version: 1.4.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
未复现这个问题，建议看下是不是页面其他样式导致的
