### ISSUE TITLE
imagePreview click时会触发当前组件的scroll事件

### ISSUE THREAD

**Issue by jonnyshao** [youzan/vant#2054]
Bug 描述
点击图片预览时会触发当前组件的scroll事件
` mounted () {
    window.addEventListener('scroll', this.onScroll)
  }`

`@click.stop="onImagePreview"`
机型
目前测试的机型都有这个问题，chrome模拟器也会触发

**Comment by chenjiahan** [comment]
这个是浏览器行为喔，我们没法处理
