### ISSUE TITLE
popup下的list不触发load事件

### ISSUE THREAD

**Issue by Candytt** [youzan/vant#2055]
在popup弹出层里添加一个list，顶部又固定位置的查询，还有一个固定在底部的按钮，要实现顶部底部组件固定显示，list需要一个固定高度，但是高度固定后就不能触发list事件，怎么在list高度固定的时候触发load事件？

**Comment by chenjiahan** [comment]
可以使用容器局部滚动

**Comment by Candytt** [comment]
什么意思 我之前固定了list高度 显示是正常的 可以滚动 底部按钮也固定，但是不触发load事件 不固定list高度可以触发load事件 但是底部按钮 随着滚动条一块滑动，怎么让按钮固定在底部 list可以滑动触发load事件


来自 魅蓝 Note5

-------- 原始邮件 --------
发件人：neverland <notifications@github.com>
时间：周四 11月8日 22:28
收件人：youzan/vant <vant@noreply.github.com>
抄送：beigege <1729476222@qq.com>,Author <author@noreply.github.com>
主题：Re: [youzan/vant] popup下的list不触发load事件 (#2055)

**Comment by Candytt** [comment]
我明白你的意思了 谢谢！


来自 魅蓝 Note5

-------- 原始邮件 --------
发件人：neverland <notifications@github.com>
时间：周四 11月8日 22:28
收件人：youzan/vant <vant@noreply.github.com>
抄送：beigege <1729476222@qq.com>,Author <author@noreply.github.com>
主题：Re: [youzan/vant] popup下的list不触发load事件 (#2055)
