### ISSUE TITLE
[Bug Report] 关于DatetimePicker时间选择器的问题

### ISSUE THREAD

**Issue by tdlbond** [youzan/vant#2058]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
时间选择器的type为time时，当自定义formatter（给小时和分钟加上时、分）后，在confirm中拿到的value是aN:aN

**Screenshots**
public formatter(type: string, value: string): string {
    if (type === 'hour') {
      return `${value}时`;
    } else if (type === 'minute') {
      return `${value}分`
    }
    return value;
  }

**Environment**
 - Device: 
可以返回正确的时间或者直接返回new Date()格式
 - Browser: 
 - Vant Version: 
1.3.8

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.4.3 版本修复
