### ISSUE TITLE
在断网情况下icon的资源无法显示

### ISSUE THREAD

**Issue by TyroneYvesChen** [youzan/vant#2068]
**Describe the bug**
在断网情况下icon的资源无法显示

**Screenshots**
![_20181112134200](https://user-images.githubusercontent.com/24521134/48328871-0f7fbf00-e681-11e8-9d56-472411445f12.png)

**Environment**
 - Device: 
希望默认引入本地的资源文件，或者有可选项。
 - Browser: 
Chrome 70.0.3538.67
 - Vant Version: 
"vant": "^1.4.2"

**Reproduce**
断网即可看到...

**Comment by chenjiahan** [comment]
断网没法展示是正常的，文档里有引用本地图标的方法
