### ISSUE TITLE
标签页 能提供纵向布局吗？现在只有横向布局 能灵活配置就好了

### ISSUE THREAD

**Issue by H5DevHoward** [youzan/vant#207]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by cookfront** [comment]
移动端暂时还没有纵向布局标签页的场景哦。后期如有需要会考虑支持纵向布局。

**Comment by deepkolos** [comment]
有纵向布局的例子么? 不知道和理解的相不相同
