### ISSUE TITLE
DatetimerPicker希望增加对周功能的扩展

### ISSUE THREAD

**Issue by tdlbond** [youzan/vant#2070]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
我司的项目中对日期选择器的功能涉及到了周的选择，但是vant中没有扩展此功能

**Describe the solution you'd like**
希望可以扩展对周的显示，如第x周或是2018-11-12~2018-11-18

**What does the proposed API look like?**
type='week'

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议使用 Picker 实现
