### ISSUE TITLE
官网定制化主题没有效果

### ISSUE THREAD

**Issue by cklwblove** [youzan/vant#2073]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
`vant 1.4.3` 版本中，发现官网定制化主题的描述有些问题，首先如果工程里 引用的是`babel6`，按照文档: 
```
{
  "plugins": [
    ["import", {
      "libraryName": "vant",
      "libraryDirectory": "es",
      "style": true  
    }]
  ]
}
```
这种设置是不起作用的。

`babel7` 的话，在 `babel.config.js` 里设置 `style: name => `${name}/style/less``。官方给的 `vant-demo` 是可以的。

所以有个疑问，想要定制主题，必须要把 `babel` 的版本升级到7吗？如果是这样的化，建议**官方文档重点提示下**。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 
1.4.3

**Comment by chenjiahan** [comment]
目前的方式是需要升级到 babel7 的，我们后续看下 babel6 有没有合适的方案

**Comment by chenjiahan** [comment]
babel 6 暂时没找到合适的方案，文档已更新，增加了 babel 版本的提示
