### ISSUE TITLE
radio 禁止状态时，是否可以考虑，将文字也处于禁用状态

### ISSUE THREAD

**Issue by asd8855** [youzan/vant#2079]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
radio 处于禁用状态时，未将文字禁用

**Describe the solution you'd like**
希望将文字和图标一起禁用

**Comment by chenjiahan** [comment]
目前是会一起禁用点击事件的
