### ISSUE TITLE
tab切换应该加上左右切换的操作

### ISSUE THREAD

**Issue by Obacm** [youzan/vant#208]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by Obacm** [comment]
左划和右划

**Comment by cookfront** [comment]
默认情况下tab多于4个是支持左右滑动的呀？你是指的这个么？

**Comment by Obacm** [comment]
touch事件，目前的好像只有点击事件吧

**Comment by deepkolos** [comment]
感觉这个左右滑动指的位置没有说明清楚, 是指tab栏超过4个可以tab栏左右滑动, 这样可以选择大于4的tab? 还是指tab之间的切换支持通过滑动切换, 就像安卓微信那样

**Comment by cookfront** [comment]
@Obacm 目前是点击才会切换到对应的tab，你是指单个tab支持左滑和右滑么？能否说清楚一下你想要的效果

**Comment by Obacm** [comment]
针对tab内容的左右滑动，滑动tab内容，tab标签跟着切换

**Comment by deepkolos** [comment]
我之前想过, 有没有必要给tab添加路由状态? 还是做成可选的?

**Comment by cookfront** [comment]
@Obacm 我们会尽快把这个功能加上，或者你也可以提个PR哈。

**Comment by deepkolos** [comment]
还可以考虑支持tab的嵌套哦~

**Comment by chenjiahan** [comment]
已在 1.0.0 版本中支持 Tab 手势操作
