### ISSUE TITLE
[Feature Request] 下拉刷新PullRefresh能否增加一个加载已完成的状态

### ISSUE THREAD

**Issue by namet117** [youzan/vant#2082]
**What problem does this feature solve?**
当下拉刷新成功后，想要在顶部有一个刷新成功的提示，而不是使用Toast方式。但目前只有 下拉、释放、加载中这三个状态。
所以目前我只能通过在拿到响应结果之后，只能使用一个setTimeout来解决（十分生硬呀~）
```javascript
this.pullRefreshText = '加载成功';
setTimeout(() => {
  this.pullRefreshLoading = true;
}, 1000)
````

**Describe the solution you'd like**
望大佬考虑一下是否可以增加这样一个状态。

**Comment by chenjiahan** [comment]
后续会考虑支持

**Comment by chenjiahan** [comment]
已在 1.6.2 版本支持
