### ISSUE TITLE
van-tab 如果一个content滑动到哪第二个content也会跟着滑动

### ISSUE THREAD

**Issue by Axu96** [youzan/vant#2083]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
我有两个tab里面content都有很多内容，当第一个滑动一段距离，切换到第二个tab时第二个tab也滑动到了和第一个tab相同的位置

**Screenshots**
![image](https://user-images.githubusercontent.com/28865316/48455372-e16fbb80-e7f5-11e8-9dca-cbd6a9611c6d.png)
![image](https://user-images.githubusercontent.com/28865316/48455387-eaf92380-e7f5-11e8-92ce-19c9dcd4be05.png)

**Environment**
 - Device: iphone 5
 - Browser: chrome
 - Vant Version: V1.4.3

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/liuxu/01wce8gL/
当内容一滑动切换到内容二应该滑动顶部

**Comment by Axu96** [comment]
https://jsfiddle.net/liuxu/01wce8gL/6/

**Comment by chenjiahan** [comment]
已在 1.4.4 版本修复
