### ISSUE TITLE
v1.4.3 按需导入导入的所有东西都是空对象

### ISSUE THREAD

**Issue by BingKui** [youzan/vant#2087]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
最新版的按需导入和导入，导入的所有东西都是空对象，v1.3不是

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
未复现这个问题，建议看下是不是项目配置有问题
