### ISSUE TITLE
业务组件 - 购物车组件

### ISSUE THREAD

**Issue by muiccc** [youzan/vant#209]
业务组件: 购物车组件也是挺重要的哈

**Comment by chenjiahan** [comment]
@muiccc 感谢反馈，已纳入后续开发计划

**Comment by muiccc** [comment]
@chenjiahan 其实把 vuex 的官方加入购物车 demo 加进去 ,在结合vant-sku组件来做其实也不错,简单粗暴

**Comment by chenjiahan** [comment]
购物车已通过示例页面的方式给出，请参见[示例页面](https://www.youzanyun.com/zanui/vue#/zh-CN/component/demo)，后续会继续完善示例中的功能

**Comment by WuHuaJi0** [comment]
购物车组件，在demo中找了，似乎没看到呢？
是否后续又删掉了？

**Comment by chenjiahan** [comment]
@WuHuaJi0 没删，链接 https://github.com/youzan/vant-demo/tree/master/src/view/cart

**Comment by Skura23** [comment]
链接都不能用了, 是删了么?

**Comment by chenjiahan** [comment]
@Skura23 https://github.com/youzan/vant-demo/tree/master/vant/base/src/view/cart
