### ISSUE TITLE
[Feature Request] Dialog 组件希望增加内容过多时，出现滚动条的功能

### ISSUE THREAD

**Issue by litmonw** [youzan/vant#2094]
**What problem does this feature solve?**
当 Dialog 组件的 message 文字较多时，整个弹窗甚至会超过屏幕，能否有一个能够控制是否使用滚动条的参数。

**Comment by qianzhaoy** [comment]
自己加容器定高加滚动条不就行了吗

**Comment by chenjiahan** [comment]
1.4.4 版本中，message 过长时会出现滚动条
