### ISSUE TITLE
swiper组件在keep-alive中会出现图片消失的问题

### ISSUE THREAD

**Issue by ZhengXiaowei** [youzan/vant#2095]
**Describe the bug**
在使用了keep-alive的页面组件里使用swiper，切换回来后有几率会让swiper中的图片消失

**Comment by chenjiahan** [comment]
麻烦提供一下 jsfiddle

**Comment by wuxn** [comment]
我的也是这样的

**Comment by guozimo** [comment]
怎么解决的呢 可以聊下思路吗 感谢了 15321575546
