### ISSUE TITLE
ImagePreview  起始位置无用

### ISSUE THREAD

**Issue by BloLee** [youzan/vant#2096]
描述错误
初始预览图片索引正确，点击关闭，再次预览图片 索引 错误

屏幕截图
添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/28392958/48601316-51bf3e00-e9aa-11e8-87c2-e53ec38f9055.png)
![image](https://user-images.githubusercontent.com/28392958/48601330-5ab00f80-e9aa-11e8-99fa-85b3333c6981.png)
传入的是一个数组
![image](https://user-images.githubusercontent.com/28392958/48601497-00fc1500-e9ab-11e8-8fc8-c81f7a2be00c.png)

环境
win7
vue-cli  脚手架 

设备：
浏览器：
Vant版本：
![image](https://user-images.githubusercontent.com/28392958/48601430-b4183e80-e9aa-11e8-99f6-ff5e205f20ee.png)

**Comment by jonnyshao** [comment]
<img width="607" alt="imagepreview" src="https://user-images.githubusercontent.com/18613989/48659637-1480ac00-ea8f-11e8-877c-d3f2c84adb49.png"> 
要传一个对象，官方有demo的

**Comment by chenjiahan** [comment]
未复现这个问题，建议升级版本再试
