### ISSUE TITLE
省市级城市错误

### ISSUE THREAD

**Issue by guwei000** [youzan/vant#2097]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
TreeSelect 分类选择的组件中，为什么莆田和三明会归类到江苏？莆田和三明是福建的

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/26682207/48602283-91d3f000-e9ad-11e8-973d-a6155bd8dbc5.png)

**Environment**
 - Device: PC
 - Browser: Google Chrome
 - Vant Version: v1.4.3

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by xland** [comment]
朋友，这是个示例，示例而已，数据怎么设置是你自己的事儿~
@guwei000

**Comment by chenjiahan** [comment]
文档示例已更新
