### ISSUE TITLE
求个抽屉组件～

### ISSUE THREAD

**Issue by mintsweet** [youzan/vant#2099]
**What problem does this feature solve?**
在做手机网页的时候，使用tabbar比较占地方～～～希望用 drawer 组件替代 tabbar的导航作用

**Describe the solution you'd like**
增加 Drawer 抽屉组件

**What does the proposed API look like?**
类似 ant-design-mobile 的 props.[ant-design-mobile drawer](https://mobile.ant.design/components/drawer-cn/)

**Comment by chenjiahan** [comment]
暂无计划支持喔，可以用 Popup 自己封装
