### ISSUE TITLE
imagePreview  可以增加一下禁止循环滚动吗

### ISSUE THREAD

**Issue by jonnyshao** [youzan/vant#2101]
你好，我希望图片滑动到最后一张时，不再循环。目前我是基于你们组件改的，希望可以直接集成进去，不然我每一个项目都要复制一下文件 感觉很不方便 谢谢！

**Comment by chenjiahan** [comment]
在 1.4.4 版本增加 loop 属性，可以用来控制

**Comment by zhangyuanliang** [comment]
@chenjiahan 最新版本的 loop: false 怎么不好用呢？

**Comment by zhangyuanliang** [comment]
@chenjiahan 另外，imagePreview onClose可以获取当前显示图片的index吗？
