### ISSUE TITLE
ios拖动列表的时候，整个页面会跟着滚动（nav-bar和tab-bar也会跟着动）

### ISSUE THREAD

**Issue by xland** [youzan/vant#2102]
**What problem does this feature solve?**
ios快速拖动列表的时候，整个页面会跟着滚动（nav-bar和tab-bar也会跟着动）

**Describe the solution you'd like**
我尝试用如下脚本禁止IOS默认的页面行为
然而这样会导致list列表无法向上拖动
```
document.body.addEventListener('touchmove', function (e) {
        e.preventDefault();
    }, {passive: false})
```

**What does the proposed API look like?**
我觉得这应该是一个默认的设置
直接把IOS默认的表现给屏蔽掉，也能保证LIST正常的向上、向下拖动就好了

**Comment by xland** [comment]
官方示例也存在这个问题
截图是在IOS虚拟机里截的
![image](https://user-images.githubusercontent.com/2980915/48667491-96191e00-eb11-11e8-92ee-e3841d3cdb3d.png)

**Comment by xland** [comment]
我觉得必须得屏蔽掉IOS touchmove事件的默认行为，
（CSDN上有人说，把根元素设置成fixed的，我试过了，不行的）
然而屏蔽掉之后，van-list也没办法向上拖动了，
（van-pull-refresh向下拖动不受影响）

**Comment by chenjiahan** [comment]
这个问题和组件没有关系，建议自行寻找解决方法

**Comment by justdoitgo** [comment]
请问问题解决没？我的苹果也出现这个问题了~
