### ISSUE TITLE
sku组件只有一个规格时默认选中样式未生效，同时赋值不生效

### ISSUE THREAD

**Issue by zhouboluo** [youzan/vant#2109]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
data里设置initialSku: { s1: '2'}, 价格和剩余数量正确显示了相应list的值，但规格标签样式仍是未选中状态（不是红色）；同时，后续初始化修改this.initialSku.s1 = '1'，未生效。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser:  chrome
 - Vant Version:  1.4.4

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle
