### ISSUE TITLE
在tab和list两个组件，配合使用的时候出现bug

### ISSUE THREAD

**Issue by chinajoy** [youzan/vant#2112]
**Describe the bug**
在tab和list两个组件，在配合使用的时候，tab是display:none/block的方式实现的，如果我在想tab每个子项里面想实现下拉刷新这个是存在bug的，当其中一个tabItem数据请求完所有数据后，切换tab。再下拉请求数据，就失效了。。。

**Environment**
 - Vant Version: 1.4.4

**Comment by chenjiahan** [comment]
没明白你的意思，建议提供一下 jsfiddle
