### ISSUE TITLE
list无限加载和tab组件一起使用，利用check方法，无法再次触发load方法

### ISSUE THREAD

**Issue by SakuraDoramon** [youzan/vant#2115]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
当list无限加载和tab组件一起使用，刚开始进入页面，第一次切换各个tab的时候onload方法会触发，但是反复切换的时候，重置loading为false，finished为false，onload方法不再触发

**Screenshots**
list组件提供的check方法如何再次触发onload方法，改变finished和loading的值希望可以再次触发onload方法，已经加了check方法，但是并没有效果，点击几次后，还是像之前一样，问题依然存在。

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
https://jsfiddle.net/13814066642/eywraw8t/466609/

**Comment by chinajoy** [comment]
你跟我的问题一样，是因为当前页面的(其实tab实现就是一个页面)其中的某一个TabItem的数据已经加载完毕，所以你不管切换到任何一个tabItem都不会在触发load了。应该是一个bug，我是这样理解的

**Comment by SakuraDoramon** [comment]
> 你跟我的问题一样，是因为当前页面的(其实tab实现就是一个页面)其中的某一个TabItem的数据已经加载完毕，所以你不管切换到任何一个tabItem都不会在触发load了。应该是一个bug，我是这样理解的

所以如果有方法能够被动触发load就好了，因为如果主动触发很有可能load了两遍

**Comment by chenjiahan** [comment]
不建议多个 List 组件共用同一个 loading 和 finished 状态，建议通过不同变量区分

**Comment by qw789** [comment]
> > 不建议多个 List 组件共用同一个 loading 和 finished 状态，建议通过不同变量区分
> 
> 这个应该是常见功能吧，你一个tab下面只是数据不一样，布局一样。我总不能写好几个吧，而且tab数据还可能是动态的

你有解决办法 吗？

**Comment by futurehu** [comment]
请问 有什么解决办法吗 同样的问题
