### ISSUE TITLE
建议Toast.loading方法默认不自动关闭

### ISSUE THREAD

**Issue by xielingxiao** [youzan/vant#2117]
执行Toast.loading后，可能3秒数据并没有自动返回，直接自动关闭了，全局setDefaultOptions又无法判断type去设置对应的duration，全局设置为1500 就更痛苦了，这样全局设置就变得鸡肋了。
建议Toast.loading方法默认不自动关闭 或者 options里面给loading单独增加一个duration，希望考虑一下，谢谢

**Comment by chenjiahan** [comment]
暂无计划这样修改喔，如果默认不关闭的话，会对原先使用的人产生影响。

你可以这样简单封装一下

```js
function loading(options) {
  Toast({
    ...options,
    duration: 0
  })
}
```

**Comment by xielingxiao** [comment]
好吧，其实loading自动关闭的逻辑本就不合理，不存在这样的需求，请求超时也会手动关闭，先这样吧，谢谢

**Comment by grace618** [comment]
哇，这个默认关闭了，怎么解决啊，怎么手动关闭
