### ISSUE TITLE
PullRefresh希望可以配置 loading的type，size，color

### ISSUE THREAD

**Issue by jiaen188** [youzan/vant#2123]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
我在使用 PullRefresh 在请求接口过程中，loading-text文本前有个 loading组件，我想通过props来改变 这个loading组件的type ，size，color，但是我没找到相关说明

**Describe the solution you'd like**
我希望能够在 PullRefresh 组件中提供相关属性 能够改变这个loading的type等属性

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.
类似api像是loading-text，加一个loading，default是{type: 'circular', size:'30px', color: '#c9c9c9'}

**Comment by chenjiahan** [comment]
如果有对 loading 的定制需求，建议通过 loading slot 来实现
