### ISSUE TITLE
TabbarItem API 的 dot 和 info 参数是否应该 watch 一下？

### ISSUE THREAD

**Issue by brownliu** [youzan/vant#2125]
**目前 TabbarItem 组件的 dot 和 info 非要触发 change 事件之后才会改变，能否监听一下？**

**这里的 dot 和 info 一般用在消息提示，常常需要实时变化，建议watch一下**

**Comment by chenjiahan** [comment]
props 变化会自动触发更新的，建议看下是不是你的用法有问题
