### ISSUE TITLE
Toast在IOS中，文字很少时也会自动换行

### ISSUE THREAD

**Issue by chihai-chuck** [youzan/vant#2127]
正常应该文字长度达到屏幕宽度的80%才会换行，可是在IOS12中（其它IOS版本和机型也会），字数达到7个字时就会换行，此时文字长度很短并没有达到应该自动换行的宽度。

https://jsfiddle.net/chihai/sgzdtL07/

![qq 20181123173935](https://user-images.githubusercontent.com/9607128/48937516-54d9a180-ef49-11e8-925b-2aea3d1f5b17.jpg)

**Comment by chenjiahan** [comment]
这个问题已经在 1.4.4 版本修复，建议更新后再试

**Comment by chihai-chuck** [comment]
> 这个问题已经在 1.4.4 版本修复，建议更新后再试

目前使用的就是1.4.4，可以看我发的demo，使用的就是1.4.4版本，在IOS中依然会发生这种情况

**Comment by chenjiahan** [comment]
iOS 上确实会有换行的问题，下个版本修复

**Comment by chenjiahan** [comment]
已在 1.4.7 版本修复
