### ISSUE TITLE
Checkbox 复选框组件bug

### ISSUE THREAD

**Issue by muiccc** [youzan/vant#213]
Checkbox 复选框组件 ,在微信端浏览器显示出了问题 ,非checked时候,,微信版本 6.5.18;  iphone7 plus ios 11.0.2(15A421);

**Comment by chenjiahan** [comment]
@muiccc 感谢反馈，将在 vant@.0.10.1 中修复此问题~

**Comment by chenjiahan** [comment]
vant0.10.1 已发布
