### ISSUE TITLE
imagePreview 页码 NaN

### ISSUE THREAD

**Issue by jonnyshao** [youzan/vant#2144]
imagePreview 如果传入的对象，页码显示没有问题，如果传入的是数组，并且只有一张的时候，页面显示NAN
![vant-bug](https://user-images.githubusercontent.com/18613989/49001192-ebe76900-f196-11e8-9eed-31d57406c8be.png)
![vant-bug2](https://user-images.githubusercontent.com/18613989/49001196-ee49c300-f196-11e8-83e9-80c301dbdbc9.png)

**Comment by chenjiahan** [comment]
感谢反馈，下个版本修复

**Comment by chenjiahan** [comment]
已在 1.4.7 版本修复
