### ISSUE TITLE
引入TreeSelect组件后报icon没找到

### ISSUE THREAD

**Issue by CoderLQChou** [youzan/vant#215]
This dependency was not found:  
* packages/icon in ./~/vant/lib/tree-select/index.js

**Comment by chenjiahan** [comment]
@CoderLQChou 感谢反馈，将在明天发布的 vant@0.10.1 中修复此问题

**Comment by CoderLQChou** [comment]
另外左边分类菜单能否增加二级菜单，类似于管理后台的左树菜单，点击后展开二级菜单，点击二级菜单，在右边显示对应的商品。

**Comment by chenjiahan** [comment]
路径问题已修复，麻烦更新到 vant@0.10.1，二级菜单功能会加到后续的开发计划中
