### ISSUE TITLE
和下拉组件一起使用

### ISSUE THREAD

**Issue by Getzoo5** [youzan/vant#2157]
需要一级能点击进入的那种
![image](https://user-images.githubusercontent.com/31106608/49064174-f8ca9200-f254-11e8-9279-91c42d95ea4e.png)
使用的disabled 无效
![image](https://user-images.githubusercontent.com/31106608/49064198-17308d80-f255-11e8-916a-269b9437d2b2.png)
![image](https://user-images.githubusercontent.com/31106608/49064214-257ea980-f255-11e8-869a-7d22172a36bc.png)

**Comment by chenjiahan** [comment]
disabled 在 1.3.6 版本以上支持，请升级到最新版本再试
