### ISSUE TITLE
文档不一致

### ISSUE THREAD

**Issue by FishPlusOrange** [youzan/vant#2162]
**Describe the bug**

今天逛 Vant 官方和 Vant 的 github 时，发现好像官方和 github 上对于 Vant **特性-单元测试覆盖率**的介绍不一致，英文版中：

- 官方介绍（[源文件](https://github.com/youzan/vant/blob/dev/docs/markdown/intro.en-US.md)）是：90%+ Unit test coverage

- github 的 README 介绍（[源文件](https://github.com/youzan/vant/blob/dev/README.md)）是：80%+ Unit test coverage

中文版也是一样的情况。我看版本号都是1.4.5，是不是两边的文档木有统一？

**Screenshots**

- 官方介绍：

![doc-1](https://user-images.githubusercontent.com/22132265/49076508-270b9a00-f274-11e8-8b7b-33ced7e26111.png)

- github 的 README：

![doc-2](https://user-images.githubusercontent.com/22132265/49076517-2bd04e00-f274-11e8-93f3-b8449d329b40.png)

**Comment by chenjiahan** [comment]
感谢反馈，这里确实有疏漏，我们会修正下
