### ISSUE TITLE
Tab 标签页 为什么会自动隐藏掉

### ISSUE THREAD

**Issue by 1215708470** [youzan/vant#2164]
![3333_20181127201304](https://user-images.githubusercontent.com/35633250/49081204-f9791d80-f280-11e8-9ff9-25ef22605b75.png)

手机浏览器的效果
![6666_20181127201505](https://user-images.githubusercontent.com/35633250/49081242-29282580-f281-11e8-95b8-2ec4f42fac0c.png)
这是电脑的浏览器效果，
为什么会这样，已经没有办法解决，调不好

**Comment by chenjiahan** [comment]
麻烦提供一下 jsfiddle

**Comment by 1215708470** [comment]
可以加一下微信或者qq吗，这个问题很诡异了。我想让你访问一下我的项目

**Comment by 1215708470** [comment]
问题已经解决了，

**Comment by chenjiahan** [comment]
好的
