### ISSUE TITLE
可以增加国内的cdn么，unpkg.com有时会访问不了

### ISSUE THREAD

**Issue by cute001** [youzan/vant#2165]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
‘unpkg.com’网站有时会连接失败，导致加载不成功

**Describe the solution you'd like**
放到国内的一些免费CDN上，方便引入。

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
试了下， jsdelivr 提供了国内节点，在国内访问比较快，文档上的 CDN 已替换
