### ISSUE TITLE
单选框和多选框安卓端顶部却是一部分?

### ISSUE THREAD

**Issue by 312798** [youzan/vant#2171]
单选框和多选框安卓端顶部却是一部分
![screenshot_2018-11-28-09-34-25-628_com alibaba an](https://user-images.githubusercontent.com/33946924/49122799-fae22e80-f2f0-11e8-9a87-17105451fdd1.png)

**Comment by xielingxiao** [comment]
这是你自己的样式问题，父级超出隐藏了 checkbox组件的部分，对齐一下就好了
