### ISSUE TITLE
swipe组件在keepAlive页面中会出现图片消失的问题

### ISSUE THREAD

**Issue by wuxn** [youzan/vant#2172]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
1、在使用了keepAlive组件的页面中，切换到别的页面，再切换回来，swipe组件上的图片会消失；
2、这个问题在iPhone上必现，安卓上没问题。

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/13825446/49136114-a3a98180-f323-11e8-9026-b7c1c80e62cf.png)
![image](https://user-images.githubusercontent.com/13825446/49136142-b623bb00-f323-11e8-8ff8-38e26e5ecbd8.png)

**Environment**
 - Device: iPhone XR、iPhone 7
 - Browser: 微信浏览器
 - Vant Version: 1.4.4

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
试了下没复现，麻烦提供一下 jsfiddle

**Comment by wendiaoxu** [comment]
同样遇到问题，项目是单应用，切换路由，轮播图片会消失

**Comment by wendiaoxu** [comment]
我现在是在轮播外层再包裹个keepAlive

**Comment by wuxn** [comment]
> 试了下没复现，麻烦提供一下 jsfiddle

确认了一下，不是当前页面（使用了swipe组件的页面）开启keepAlive出现的问题，而且当跳到下一个页面的时候（这个页面开启了keepAlive），再返回当前页面，就会出现以上描述的问题。

**Comment by malong4251** [comment]
另外轮播图上如果有点击事件跳转链接，手指滑动时会直接触发，很尴尬

**Comment by wuxn** [comment]
> 另外轮播图上如果有点击事件跳转链接，手指滑动时会直接触发，很尴尬

先把那个fastclick插件注掉吧，是跟那个有冲突了

**Comment by chenjiahan** [comment]
按照你们的描述尝试了一下，还是没复现呢，能否给个 jsfiddle 喔

**Comment by malong4251** [comment]
> > 另外轮播图上如果有点击事件跳转链接，手指滑动时会直接触发，很尴尬
> 
> 先把那个fastclick插件注掉吧，是跟那个有冲突了

已解决，谢谢哈

**Comment by xjonson** [comment]
老哥们解决了么

**Comment by BoBo-Git** [comment]
给 `keep-alive` 中的 `Swipe` 组件添加 `v-if` 判断，在 `activated` 生命周期中，将 `Swipe` 的 show 置为 `true`，在 `deactivated` 生命周期中，将 `Swipe` 的 show 置为 `false`，以此来重新渲染 `Swipe`，亲测可以很好解决这个问题。
