### ISSUE TITLE
Area的item-height安卓和IOS H5页面高度差距较大

### ISSUE THREAD

**Issue by winterfall1121** [youzan/vant#2173]
我看了下源码，准确来说是picker里面的picker-colums的itemHeight, 默认44的话 安卓是比较正常的，IOS就非常窄。 

IOS设置80多才会比较正常（我估计是因为dpr的问题）。 但是DPR的问题px2rem应该是可以转化rem的， 但是就picker这个组件的itemHeight的px未转为rem。

itemHeight只准接收数字，如果可以接收String 直接传递rem，然后改一下源码里的某些部分是可以解决的(把项目fork到了自己的github,试了下)

   目前就是有个疑问：为什么webpack没有正常转化itemHeight的px呢？还是其他什么兼容性的原因？
   大神可否优化一下0.0

**Comment by winterfall1121** [comment]
是因为内联样式PX未转化为REM的原因，我自己写了个插件转了

**Comment by FunnyBoyCN** [comment]
请问可以吧插件的写法分享一下吗
