### ISSUE TITLE
picker组件的问题

### ISSUE THREAD

**Issue by is-liyiwei** [youzan/vant#2175]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
picker组件能够不联动的吗？就是类似DatetimePicker组件那样，但是里面的内容是自己定义的，好像picker都是联动的

**Comment by chenjiahan** [comment]
默认就是不联动的
