### ISSUE TITLE
提示缺少类型

### ISSUE THREAD

**Issue by haibosong** [youzan/vant#2177]
ERROR in F:/VSCode/widget/shareyue-apicloud-vue/node_modules/vant/types/notify.d.ts
 Subsequent property declarations must have the same type.  Property '$notify' must be of type 'ElNotification', but here has type 'Notify'.

**Comment by chenjiahan** [comment]
看起来是和 Element 的类型冲突了，建议看下是不是配置有问题

**Comment by haibosong** [comment]
> 看起来是和 Element 的类型冲突了，建议看下是不是配置有问题

我指定 1.4.5 版本就没有错误，新的就有错误
