### ISSUE TITLE
Circle model和rate有点问题

### ISSUE THREAD

**Issue by mynameismaosheng** [youzan/vant#2178]
**rate 无效 v-model这个属性用于什么**
api里 v-model说是当前进度. 
但是我rate写了80 
v-model是0 
出现的情况是  圆环100  进度80%  v-model的0没什么作用

**我需要rate 和 model各司其职**
设置rate就是总进度  model就是当前进度  api  rate把目标进度改成总进度是不是更好一点?

**What does the proposed API look like?**
现在这样子挺好

**Comment by chenjiahan** [comment]
文档里写的很清楚了，rate 指定目标进度，v-model 代表当前进度，中间有个动画过程

**Comment by fancyer** [comment]
这个组件的逻辑我也没弄明白。

我的理解是这样的：

> rate 指定目标进度 => 我想达到100%
> v-model 代表当前进度 => 现在是进度是20%

这个逻辑的进度变动应该体现为v-model的改变，而不是rate的改变。

现在官网的例子是改变rate而不是model, 并且 model 跟随 rate 变动。是不是因为动画效果的缘故，必须有一个model？所谓的“目标”和“当前”，意味着动画的“目标”和“当前”？

**Comment by chenjiahan** [comment]
@fancyer 确实有点难理解，可以帮助我们完善一下文档哈哈

**Comment by i38** [comment]
我也觉得这个组件的逻辑稍有问题，而不是文档有问题，model随rate变动，这点挺难理解的。

**Comment by acutbh** [comment]
我也觉得这个组件的逻辑稍有问题，而不是文档有问题，model随rate变动，实际上model是没有用的，因为rate就是进度完全是由我自己控制的。

**Comment by acutbh** [comment]
我也觉得这个组件的逻辑稍有问题，而不是文档有问题，model随rate变动，实际上model是没有用的，因为rate进度完全是由我自己控制的。
