### ISSUE TITLE
AddressEdit 组件  addressInfo 数据不能返回id 

### ISSUE THREAD

**Issue by tanx0709** [youzan/vant#2180]
AddressEdit 组件  addressInfo 数据不能返回id  addressDetail: "福建会馆"
areaCode: "110101"
city: "北京市"
country: ""
county: "东城区"
isDefault: true
name: "谭***"
postalCode: "100000"
province: "北京市"
tel: "18571224780"

**Comment by chenjiahan** [comment]
不规范的 issue
