### ISSUE TITLE
List 列表 运行一直报这个错误

### ISSUE THREAD

**Issue by catbea** [youzan/vant#2181]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Maximum call stack size exceeded

**Screenshots**

**Environment**
 - Device: PC
 - Browser: chrome
 - Vant Version: vant@1.4.4

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle
