### ISSUE TITLE
发现在Android4.4 系统上 Dialog 显示异常

### ISSUE THREAD

**Issue by Promise-leaves** [youzan/vant#2182]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
发现在Android4.4 系统上 Dialog 显示异常

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/34081173/49215524-ee022f80-f403-11e8-8136-5544db9a7044.png)
![image](https://user-images.githubusercontent.com/34081173/49215558-05d9b380-f404-11e8-8265-ae75ed6cb17f.png)

**Environment**
 - Device: Android
 - Browser: (Version/4.0 Chrome/30.0.0.0)
 - Vant Version: "vant": "^1.3.10",

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by chenjiahan** [comment]
请确认下你项目的 autoprefixer 配置是否正确

**Comment by Promise-leaves** [comment]
问题已解决，多谢您的提醒。
