### ISSUE TITLE
vant Collapse折叠面板引入报错

### ISSUE THREAD

**Issue by lpz1096** [youzan/vant#2185]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
折叠面板引入报错
按照官方文档，引入组件，使用报错

**Screenshots**
Add screenshots to help explain your problem.
![20181130114643](https://user-images.githubusercontent.com/37067547/49267468-a88e4280-f495-11e8-978b-8594a8571867.jpg)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/1/

**Comment by oahnus** [comment]
@lpz1096 我也遇到这个问题，我的原因是使用v-model="activeNames"时，activeNames不是数组类型，才引发的这个问题，some方法是用于检测Array是否满足条件的，非Array类型会报错。

**Comment by chenjiahan** [comment]
请按文档传入 v-model 绑定的数据格式，手风琴模式为 string，非手风琴模式为 array
