### ISSUE TITLE
时间选择控件滑动不流畅

### ISSUE THREAD

**Issue by dhj2020** [youzan/vant#2188]
时间选择控件滑动不流畅，滑动每次只能滑很小一段，一个月30天从1到30就要滑动15次左右，可参考下vux的滑动流畅度。
建议增加功能：1、日历控件   2、上拉刷新

**Comment by chenjiahan** [comment]
暂无计划支持喔

**Comment by PHenryy** [comment]
同样遇到了，比如从七月份滑到八月份，松手的时候又回弹到七月份，有什么解决方案吗

**Comment by PHenryy** [comment]
好像滑动没有惯性

**Comment by chenjiahan** [comment]
2.0 版本开始已经有惯性滚动了
