### ISSUE TITLE
省市区的json文件能放出来吗？

### ISSUE THREAD

**Issue by mantou-kk** [youzan/vant#219]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@mantou-kk 
https://github.com/youzan/vant/blob/dev/docs/mock/area.json
