### ISSUE TITLE
步进器加减样式失效

### ISSUE THREAD

**Issue by 823680621** [youzan/vant#2199]
当我的步进器用作循环体里面时，第一个会出现加减也就是伪类样式失效问题，安卓ios都出现这个问题，
![image](https://user-images.githubusercontent.com/41313775/49323341-b8209080-f554-11e8-9f3e-63f95a905ffa.png)
![image](https://user-images.githubusercontent.com/41313775/49323352-f28a2d80-f554-11e8-9005-7554e30a8a44.png)

**Comment by 823680621** [comment]
> 当我的步进器用作循环体里面时，第一个会出现加减也就是伪类样式失效问题
![image](https://user-images.githubusercontent.com/41313775/49323297-29137880-f554-11e8-8d5f-b248c79e3dd9.png)

![image](https://user-images.githubusercontent.com/41313775/49323286-0a14e680-f554-11e8-8466-fc484dd218e8.png)

**Comment by 823680621** [comment]
help me！！！

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle 链接
