### ISSUE TITLE
Uploader手机上无效

### ISSUE THREAD

**Issue by dxc0522** [youzan/vant#2200]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
电脑上可选择图片，手机上点击无效。
选择了图片后没反应，电脑上正常，手机上无反应。
**Screenshots**

`        <van-uploader
          @oversize="fillSize"
          :after-read="onRead"
          multiple="multiple"
        ></van-uploader>`

**Comment by chenjiahan** [comment]
未复现这个问题，建议看下是否是其他原因导致的，或者提供一下 jsfiddle
