### ISSUE TITLE
vant unpkg css 引用库

### ISSUE THREAD

**Issue by de1ck** [youzan/vant#2206]
本来想使用jsfiddle提交demo的 https://jsfiddle.net/dfarLdko/1/
发现这个地址是有问题的 https://unpkg.com/vant/lib/vant-css/index.css
官网上推荐的是这个https://cdn.jsdelivr.net/npm/vant@1.4/lib/index.css
github issue add new bug issue 引用的地址是: https://unpkg.com/vant/lib/vant-css/index.css
![_15438073731975](https://user-images.githubusercontent.com/26627486/49351316-cbb32f00-f6ed-11e8-9c80-e564a90f4f54.png)

**Comment by chenjiahan** [comment]
感谢反馈，之前的链接已经过时了，issue 模板已更新
新的 jsfiddle 地址：https://jsfiddle.net/dfarLdko/522/
