### ISSUE TITLE
Vant 顶部导航栏【van-tabs】Bug

### ISSUE THREAD

**Issue by lpz1096** [youzan/vant#2211]
如果在外面包裹div控制显示隐藏会出现导航条不准确的bug
代码

![_20181204111128](https://user-images.githubusercontent.com/37067547/49416564-5d39a400-f7b5-11e8-9eba-3cbcfe011c35.png)

效果

![_20181204110556](https://user-images.githubusercontent.com/37067547/49416353-a806ec00-f7b4-11e8-83d8-f2adbbcd19c5.jpg)
问题：因为要多次隐藏显示所以用v-show来控制，就会出现这样问题。
解决：用v-if代替就行，希望官方能解决这个问题

**Comment by chenjiahan** [comment]
这个问题无法解决，如果在 hidden 的时候初始化 tab，会导致无法获取导航条宽度

**Comment by lpz1096** [comment]
那这个导航条能不能用成%样式，如果有两个就导航条占总宽度一半
