### ISSUE TITLE
van-filed 组件的 使用多个slot无效

### ISSUE THREAD

**Issue by lisenz** [youzan/vant#2213]
微信浏览器页面，在van-filed组件中插入一个button尾部按钮和left-icon头部图标，只能正常显示left-icon的slot，button的slot没有显示，把left-icon去掉，只插入button的slot就正常。

结构代码如下：
`<van-field v-model="modelData.ValidateCode"
                       type="number"
                       label="验证码"
                       required
                       center
                       clearable
                       maxlength="6"
                       v-on:touchstart.native.stop="showKeyboard=true"
                       v-on:focus="doPhoneFocus"
                       placeholder="请输入短信验证码">
                <van-icon class-prefix="my-icon" name="code" slot="left-icon" />
                <van-button slot="button" v-bind:disabled="canGetCode" size="normal" type="primary" v-on:click="doGetCode">{{buttonText}}</van-button>
            </van-field>`

**Comment by chenjiahan** [comment]
目测应该是 HTML 模板，HTML 模板不支持自闭和标签

**Comment by lisenz** [comment]
@chenjiahan 确实是这个原因，<van-icon class-prefix="my-icon" name="code" slot="left-icon"></van-icon>这样使用就没问题了

**Comment by lisenz** [comment]
@chenjiahan 确实是这个原因，`<van-icon class-prefix="my-icon" name="code" slot="left-icon"></van-icon>`这样写就可以了
