### ISSUE TITLE
[Feature Request] swipe固定滑块宽度问题

### ISSUE THREAD

**Issue by ZAXHM** [youzan/vant#2214]
**Describe the bug**
想实现效果是显示当前轮播页时，能够看到下一个轮播的部分内容。
设置滑块宽度（:width=300）后，自动轮播到最后一个，最后追加第一个的时候空白间隔较长；关闭自动轮播，手动滑到最后一个，下一个是空白，需手动轻微滑动才可显示

**Screenshots**

**Environment**
 - Device:  PC、手机
 - Browser: 谷歌浏览器、微信内置浏览器
 - Vant Version:  v 1.4.7

**Reproduce**

**Comment by chenjiahan** [comment]
后续会看看能否优化固定宽度时的展示效果

**Comment by Josie-ljw** [comment]
我也遇到了这个问题

**Comment by JM5788** [comment]
我也是遇到这个问题，比如做横向滑动展示商品列表时（横向显示两个单位），最后始终会有一个单位的留白

**Comment by langlibaitiao** [comment]
swipe传入参数width="300"后swipe-item的单位为300px,请问这个怎么适配视口呢？

**Comment by zhaoqj008** [comment]
我也是遇到这个问题改成手写了

**Comment by zhaoqj008** [comment]
我也是遇到这个问题改成手写了

**Comment by zhaoshuan** [comment]
@chenjiahan 
大佬，可否将swiper组件扩展更多功能，类似swiper插件那样，这样遇到相关场景，就不需要再多引用其他插件，
相关场景，例如：
容器里面有多个slider块，在当前可视区域显示两个，左滑可显示更多slider块

**Comment by chenjiahan** [comment]
已经在 2.0.6 版本修复空白区域的问题，不过固定宽度滑块不支持和循环播放同时使用。

**Comment by chenjiahan** [comment]
@zhaoshuan 这个应该可以用 width 实现
