### ISSUE TITLE
版本升级之后，<van-tag>字体色和背景色无法控制

### ISSUE THREAD

**Issue by hzsrc** [youzan/vant#2219]
**What problem does this feature solve?**
版本升级之后，<van-tag>的字体颜色写在的dom节点的style属性上面（优先级最高），而且没有了van-tag--primary这样的className，导致原有的针对van-tag的样式完全失效，严重影响了现有功能。

**Describe the solution you'd like**
希望仍然保留van-tag--primary这类className。同时字体色和背景色通过样式来控制。

**What does the proposed API look like?**
通过van-tag--primary这类className来控制字体色和背景色

**Comment by chenjiahan** [comment]
className 其实不属于组件对外暴露的接口，所以我们还是倾向于提供 props 来控制颜色，请问 props 无法满足你的需求吗

**Comment by hzsrc** [comment]
我们原本是通过 css来控制颜色切换的，用props的话就必须要通过js了，比较麻烦。您说的通过props来控制颜色没问题的，关键是实现方式是通过dom上的style还是class，style优先级太高，我们现在只能自己加一个className再写!important来覆盖。其他组件像按钮之类的，就是通过el-button--primary这样的classname来实现的颜色，为啥不保持统一呢，这样会灵活很多的
