### ISSUE TITLE
请问如何跟手淘lib-flexible rem布局结合

### ISSUE THREAD

**Issue by lyseky** [youzan/vant#222]
开源的都是px，还得写很多样式，现在移动端都是用rem单位来适配

**Comment by chenjiahan** [comment]
@Alexis374 考虑到组件的通用性，Vant 目前不会默认采用 rem 作为单位，后续会考虑对 rem 作支持

**Comment by lyseky** [comment]
其实不用rem也可以，结合flex，不过没那么精确

**Comment by Anikinly** [comment]
不用弹性实现，就谈不上ui

**Comment by chenjiahan** [comment]
@Anikinly 这是去年的 issue 了，文档里已经有了 rem 适配方法 https://youzan.github.io/vant/#/zh-CN/quickstart
