### ISSUE TITLE
tabs 开启animated 后 高度不满一屏的tab也可以上下滚动

### ISSUE THREAD

**Issue by tuhe32** [youzan/vant#2222]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
tabs 开启animated 后 tabs的高度算的是最高的tab的高度，导致不满一屏的tab也可以上下滚动

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/18496264/49554984-05c44100-f939-11e8-9854-f06703b39eab.png)
![image](https://user-images.githubusercontent.com/18496264/49554991-0f4da900-f939-11e8-9887-77964a719261.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by tuhe32** [comment]
https://jsfiddle.net/dfarLdko/528/

**Comment by jerryachel** [comment]
问题依然存在，每个tabs的高度依然是取决最高的tabs

**Comment by feelslive** [comment]
至今问题依然存在，希望尽快修复谢谢！

**Comment by lpz1096** [comment]
看了vant的源码，他是把tabs下两个tab合成一个页面做成动画，宽度是两个tab的宽度之和，页面高度是最大的tab的高度

**Comment by lpz1096** [comment]
所以不好解决
