### ISSUE TITLE
关于文档国际化的部分

### ISSUE THREAD

**Issue by ChenGitHub126** [youzan/vant#2224]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
文档国际化部分写的太简略了，看完可以更改UI内部语言，然而还是不知道如何在自己的组件中引入和使用语言文件

**Describe the solution you'd like**
可以在demo中加入国际化的使用实例

**What does the proposed API look like?**
-----

**Comment by ChenGitHub126** [comment]
在组件中是这么引用吗 `this.$vantMessages['zh-CN']`

**Comment by chenjiahan** [comment]
目前 Vant 的国际化组件仅在组件库内部使用呢，如果是项目里需要适配国际化，建议使用 vue-i18n
