### ISSUE TITLE
popup嵌套在cell组件中，popup无法关闭

### ISSUE THREAD

**Issue by zhengmiaohua** [youzan/vant#2226]
vant: '1.4.7',
![image](https://user-images.githubusercontent.com/20886412/49561477-77f54f80-f952-11e8-8595-0cccf8026a27.png)

**Comment by chenjiahan** [comment]
事件冒泡了，在 popup 上加上 get-container="body" 即可解决

**Comment by zhengmiaohua** [comment]
> 事件冒泡了，在 popup 上加上 get-container="body" 即可解决

谢谢大佬
