### ISSUE TITLE
[Feature Request] ImagePreview能否新增双击放大呢

### ISSUE THREAD

**Issue by six-666** [youzan/vant#2227]
在移动端里这个功能是非常实用的，怎么会没有这个功能呢。

**Comment by chenjiahan** [comment]
后续会支持

**Comment by huanggengzhong** [comment]
有一个bug即在打开图片预览功能后，如果不关闭预览的图片，同时改变路由的话，会发现即使路由改变了，预览的图片还在文档的最顶层显示,这个怎么解决?

**Comment by bsaaa44** [comment]
双手操作放大图片的时候不流畅，会无缘无故变大变小

**Comment by chenjiahan** [comment]
已经在 2.0.8 版本支持双击放大

@huanggengzhong 这个需求可以使用 `close-on-popstate` 属性
