### ISSUE TITLE
官方文档中关于安装的一种方式路径有问题。希望官方修改文档。

### ISSUE THREAD

**Issue by sean5120scan** [youzan/vant#2230]
官方文档中关于安装的一种方式路径有问题。希望官方修改文档。避免给开发者带来困扰。
官方文档引入方式：
import Vant from 'vant'
import 'vant/lib/vant-css/index.css'
Vue.use(vant)

正确路径：
import Vant from 'vant'
import 'vant/lib/index.css'
Vue.use(vant)

**Comment by chenjiahan** [comment]
文档里是正确的路径，建议看下是不是浏览器缓存了，刷新页面试下
