### ISSUE TITLE
[ImagePreview] onClose回调函数中可不可以通过return false，来阻止关闭；增加一个函数能通过index动态改变当前显示图片

### ISSUE THREAD

**Issue by zhangyuanliang** [youzan/vant#2231]
**[ImagePreview] onClose回调函数中可不可以通过return false，来阻止关闭；增加一个函数能通过index动态改变当前显示图片**

**Comment by chenjiahan** [comment]
阻止关闭请使用 asyncClose 属性，然后通过 close 方法手动关闭
东南太改变当前显示图标的需求，具体是用于什么场景呢

**Comment by zhangyuanliang** [comment]
@chenjiahan 本来有一个通过“下一页”按钮控制切换的需求，现在不需要了，谢谢

**Comment by chenjiahan** [comment]
好的
