### ISSUE TITLE
<van-field type="number" /> 无法拦截输入“-”  

### ISSUE THREAD

**Issue by jzz4012650** [youzan/vant#2232]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
<van-field type="number" /> 组件无法拦截-（减号）的输入；
且在输入减号时，input事件收到的数据是个空字符串，导致无法自行处理减号的输入。

**Screenshots**
![image](https://user-images.githubusercontent.com/4429264/49572531-fcf26000-f976-11e8-87e8-4b3c1fa8368d.png)

**Environment**
 - Device: iPhoneXR
 - Browser: native webview
 - Vant Version: 1.4.7

**Reproduce**
- 使用`<van-field type="number" value="test" @input="handleInput">`
- 在`handleInput`中监听输入，当输入-号的时候，收到的数据为`""`

**Comment by jzz4012650** [comment]
![image](https://user-images.githubusercontent.com/4429264/49573721-a8041900-f979-11e8-89f5-1cee3e3bb381.png)
keypress 没法 prevent，考虑换 keydown 吧。

**Comment by chenjiahan** [comment]
收到，我们先看下

**Comment by chenjiahan** [comment]
目前的逻辑是允许减号输入的，因为 number 也包含了负数

**Comment by chenjiahan** [comment]
input 事件里的值是浏览器返回的，所以我们也不太好处理。请问你需要实现什么样的需求呢

**Comment by yepbug** [comment]
这个不算是一个bug 吧。因为原生 input 组件，当[`type=number`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number)的时候，input 本身就会阻止非数字的输入。先输入一个减号（-），`e.target.value` 本身就获取不到值，后续输入数字才能获得值，比如 -1，-123，这样。要实现你的效果，就不能用 `type=number`，或者有赞需要参照 [ant](https://github.com/vueComponent/ant-design-vue/blob/master/components/vc-input-number/src/index.js)的做法，单独建一个 `van-input-number` 组件，而不是依赖 `type=number`

**Comment by jzz4012650** [comment]
> input 事件里的值是浏览器返回的，所以我们也不太好处理。请问你需要实现什么样的需求呢

额，我这边的需求其实就是需要实现一个金额的输入框（0-9加小数点），但是vant并没有提供一个很好的解决方案，我是自己模拟输入框加虚拟数字键盘解决的。

**Comment by chenjiahan** [comment]
原生 input 的问题确实比较难处理，我们暂时没计划提供 van-input-number 这样的组件，所以自行模拟输入框是一个比较合适的解决方法^_^

**Comment by chenjiahan** [comment]
原生 input 的问题确实比较难处理，我们暂时没计划提供 van-input-number 这样的组件，所以自行模拟输入框是一个比较合适的解决方法^_^
