### ISSUE TITLE
tabbar用了闭包之后, props.active Change的不对哦

### ISSUE THREAD

**Issue by stack-wuh** [youzan/vant#2236]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
tabbar组件的change事件用了闭包之后, props.active不能跟随了,响应错误
![image](https://user-images.githubusercontent.com/34117238/49627129-126b9680-fa18-11e8-96c5-2e2e917df168.png)
![image](https://user-images.githubusercontent.com/34117238/49627137-22837600-fa18-11e8-8d9b-ea4ec4314de0.png)

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
不太清楚你这里使用的闭包和 props.active 有什么关联，建议提供下 jsfiddle
