### ISSUE TITLE
sku规格缩略图

### ISSUE THREAD

**Issue by ansonhorse** [youzan/vant#2240]
**What problem does this feature solve?**
sku组件里的规格选项暂时只有纯文本的显示形式，体验仍有待升级。

**What does the proposed API look like?**
希望能支持显示规格缩略图，最好能灵活决定显示的内容，文本、图片、或者两者一起。
![image](https://user-images.githubusercontent.com/7548142/49640886-a86be500-fa49-11e8-9b42-fd63c2f258fb.png)

**Comment by chenjiahan** [comment]
暂无计划支持，如果有这个需求的话，欢迎提 PR 喔

**Comment by sparGuan** [comment]
![image](https://user-images.githubusercontent.com/28480563/52052426-4fc05080-2591-11e9-8b78-de92cfb53f4c.png)
将源代码改成这样就行了
