### ISSUE TITLE
Tabbar的v-model值为字符串更合理些吧 ，因为有时需要根据不同情况显示不同的tabbar-item

### ISSUE THREAD

**Issue by qq124719010** [youzan/vant#2245]
有时需要根据不同情况显示不同的tabbar-item，当改变了tabbar-item的顺序或个数时，v-model值为数字时很难设置当前选中的tabbar-item，强烈建议改成string类型的值。

**Comment by chenjiahan** [comment]
暂无计划修改，这会导致破坏性更新
