### ISSUE TITLE
Tab标签加了animated。它其中的Popup 弹出层将不会显示

### ISSUE THREAD

**Issue by zbr826858040** [youzan/vant#2246]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Tab标签加了animated。它其中的Popup 弹出层将不会显示

**Screenshots**
我用了你们的Reproduce   ↓↓↓↓↓↓↓↓↓↓↓

**Environment**
 - Device: win7
 - Browser:  谷歌游览器 Google Chrome
 - Vant Version: V1.4.8

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
我用了jsfiddle哦~
https://jsfiddle.net/dfarLdko/552/

**Comment by zbr826858040** [comment]
tab的swipeable可以正常显示Popup 弹出层。用了animated就不行了。

**Comment by chenjiahan** [comment]
原因见：https://github.com/youzan/vant/issues/1146
解决方法：在 Popup 上添加 get-container="body"
