### ISSUE TITLE
选择器和时间选择器在vue-cli 3.x下滑动不正常

### ISSUE THREAD

**Issue by liuhuaxia** [youzan/vant#2249]
**Describe the bug**
滑动不正常，上下滑动一次只能移动很小的距离

**Screenshots**
![qq 20181209131159](https://user-images.githubusercontent.com/30068808/49693716-a030b880-fbb5-11e8-8a3b-e119871d2246.png)
![qq 20181209131321](https://user-images.githubusercontent.com/30068808/49693717-a3c43f80-fbb5-11e8-930d-eb645d9e19a1.png)
![gif](https://user-images.githubusercontent.com/30068808/49693718-a6269980-fbb5-11e8-82f8-315564566c40.gif)

**Environment**
 - Device: all
 - Browser: all
 - Vant Version:1.4.8 

**Reproduce**

**Comment by aqkj** [comment]
我最近也遇到这个问题了，vue版本换成2.5.17的就正常了

**Comment by xiaoweihuang** [comment]
是不是姿势不对，亲测不会有卡顿的问题，vue-cli version 3.2.1

**Comment by liuruidong1994** [comment]
我也遇到这个问题了，vuw 2.5.17

**Comment by hzsrc** [comment]
折腾了半天哦，早看下这里就好了
