### ISSUE TITLE
 ImagePreview 图片预览 组件使用后，点击图片无法显示大图

### ISSUE THREAD

**Issue by mcuking** [youzan/vant#225]
### ImagePreview 图片预览 组件使用后，点击图片无法显示大图
注意：当前点击后的图片链接是固定写死的，是来测试组件能否正常工作，实际需求是所点击图片的实际链接
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
相关代码如下：
![image](https://user-images.githubusercontent.com/22924912/31808385-83ca0300-b538-11e7-9927-369d91a34687.png)
![image](https://user-images.githubusercontent.com/22924912/31808398-9c04484a-b538-11e7-80e1-c8075c093bb3.png)
表现如下：
![image](https://user-images.githubusercontent.com/22924912/31808368-6ba8e804-b538-11e7-9669-8da6c692c23b.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**
希望能够点击之后正常显示原图
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
版本如下：
Vue: 2.2.2
Vant: 0.10.1
Browser: Chrome Version 61.0.3163.100 
OS: MacOS 10.13

在Vant 0.10.0也无法显示

**Comment by chenjiahan** [comment]
@mcuking 感谢反馈，此问题是由于 ImagePreview 没有默认引入 Swipe 组件样式导致的，将在 vant@0.10.2 中修复，在之前的版本中你可以通过手动引入 Swipe 样式的方式解决

```js
import 'vant/lib/vant-css/swipe.css';
```

**Comment by mcuking** [comment]
v-modal 样式 也没有（透明黑色的背景），还需要引用其他css文件么？
![image](https://user-images.githubusercontent.com/22924912/31810652-31adbd00-b542-11e7-8b81-6f0bc90a1170.png)

**Comment by muiccc** [comment]
@mcuking  vant-css

**Comment by mcuking** [comment]
@muiccc 具体是指哪个css文件呢？
![1508488079162](https://user-images.githubusercontent.com/22924912/31811969-11779a7e-b547-11e7-8978-c9a97adb2c85.jpg)

**Comment by cookfront** [comment]
`swipe.css`

**Comment by mcuking** [comment]
@cookfront 你好，已经引入了swipe.css，图片也显示出来了，但是当显示大图时，没有黑色透明阴影

**Comment by cookfront** [comment]
嗯 是指背景的遮罩没显示么？

**Comment by muiccc** [comment]
@mcuking   popup.css,  建议 在main.js 里面把 vant-css 装上

**Comment by mcuking** [comment]
@cookfront 嗯，是的

**Comment by mcuking** [comment]
@muiccc 问题解决了，十分感谢啊。
另外说下，有赞的UI真的很棒，之前做产品的时候也会经常参考你们的管理后台和移动端，很希望以后能和你们成为同事啊～
哈哈哈哈哈哈

**Comment by cookfront** [comment]
@mcuking  要来的时候可以到这投简历： [https://job.youzan.com/](https://job.youzan.com/)

**Comment by mcuking** [comment]
@cookfront 😂好的，得再修炼一段时间，提升下能力再投～
