### ISSUE TITLE
Tab 标签页下加入 search 后 Tab 失去滑动效果

### ISSUE THREAD

**Issue by zbr826858040** [youzan/vant#2252]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Tab 标签页下加入 search 后 Tab 失去滑动效果
我用了这个jsfiddle。页面都没有了。我在VScode上还能有个界面切换下才会卡死了

**Screenshots**
![xukfv7s055bu h19pw7b4 t](https://user-images.githubusercontent.com/29971926/49697199-68defd80-fbef-11e8-9d46-f074f55bb510.png)

**Environment**
 - Device: win7
 - Browser: google chrome
 - Vant Version: 1.4.8

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/566/

**Comment by chenjiahan** [comment]
未复现问题
