### ISSUE TITLE
Dialog不能弹出显示框

### ISSUE THREAD

**Issue by EwingDeng** [youzan/vant#2262]
之前开发的时候是可以的，今晚发现不能弹框了，以发到线上的代码也是没有看到弹框，是什么问题？
xx.vue代码如下：
this.$dialog.confirm({
                message: '确认取消绑定微信账号?'
            }).then(() => {
                // on confirm
             ).catch(() => {
                
            });

main.js已经引用了：
import { Progress, Dialog, Toast, Actionsheet } from 'vant';
Vue.use(Progress);
Vue.use(Dialog);
Vue.use(Toast);
Vue.use(Actionsheet);
import 'vant/lib/index.css'

请问，之前代码都没问题的，是否是在更新版本？还是其他问题？

**Comment by jerryachel** [comment]
在1.5.0中出现了同样的错误，已经全局注册了Dialog这个组件，在chrome中可以正确弹出comfirm显示框，打包到微信端就直接error了
然后换成组件内注册Dialog这个方法才可以正常显示
