### ISSUE TITLE
1.4.8 Area 省市区选择 & DatetimePicker 时间选择确定按钮消失！

### ISSUE THREAD

**Issue by wzc0x0** [youzan/vant#2263]
**Describe the bug**
1.4.8 Area 省市区选择 & DatetimePicker 时间选择确定按钮消失！应该是样式颜色白色了！

**Screenshots**
![image](https://user-images.githubusercontent.com/11566782/49744163-2bee3600-fcd7-11e8-9698-5a5258ce09e0.png)

**Environment**
 - Device: iOS12 & Android8.0
 - Browser: 微信浏览器
 - Vant Version: 1.4.8

**Comment by wzc0x0** [comment]
MMP 老子今天上线！测试好的！上线就炸了！线上用的最新1.4.8

**Comment by chenjiahan** [comment]
未复现这个问题，建议看下是不是项目里的其他样式干扰了

**Comment by wzc0x0** [comment]
查看源码 按钮文字发现是props 导出的 或$t函数 目前按钮文字是消失的

**Comment by chenjiahan** [comment]
建议看下是不是项目中引入了多份 Vue 代码导致的
