### ISSUE TITLE
使用CDN资源的时候，安卓老版本不渲染，怎么解决？

### ISSUE THREAD

**Issue by cherho0** [youzan/vant#2264]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

使用CDN资源开发的，没有用单页应用方式，在老版本安卓上不显示。代码如下，加了这些，没什么用。

` <script src="https://cdn.bootcss.com/babel-polyfill/6.23.0/polyfill.min.js"></script>
    <script>window.Promise || document.write('<script src="//img.yzcdn.cn/huiyi/build/h5/js/pinkie.min.js"><\/script>');</script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vant@1.4/lib/index.css">
    <style type="text/css">
        [v-cloak] { display: none; }

        * {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        input, textarea {
            -webkit-user-select: auto;
            margin: 0px;
            padding: 0px;
            outline: none;
        }

    </style>
    @RenderSection("css", required: false)
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vant@1.4/lib/vant.min.js"></script>`

**Comment by chenjiahan** [comment]
建议看下是不是在旧版本安卓上出现了兼容性导致的报错，推荐使用 webpack 构建的方式进行开发
