### ISSUE TITLE
在安卓手机上使用摄像头拍照上传图片，点击查看大图很卡顿（关闭卡顿，滑动下一张卡顿）

### ISSUE THREAD

**Issue by hfq-jiaxinjie** [youzan/vant#2265]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在安卓手机上使用摄像头拍照上传图片，点击查看大图很卡顿（关闭卡顿，滑动下一张卡顿）

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device:  Android
 - Browser: 微信浏览器
 - Vant Version: 1.3.4

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
这个是原生系统的问题吧，与组件库无关
