### ISSUE TITLE
自v1.4.5之后样式出现异常

### ISSUE THREAD

**Issue by cy920820** [youzan/vant#2266]
**Describe the bug**
将vant版本从v1.3.9 升级到最新发现样式出现异常，目前检测到 `<van-tabs />` 组件宽度样式出现不可控

再次排查是从v1.4.5开始出现样式混乱

**Screenshots**
## 正常现象
![image](https://user-images.githubusercontent.com/21211512/49800384-534e0d00-fd82-11e8-9d20-8a22324b13ae.png)

## 异常现象
![image](https://user-images.githubusercontent.com/21211512/49800339-3580a800-fd82-11e8-8de2-108b031111af.png)

**Environment**
 - Device: MAC pro 2017
 - Browser:  chrome
 - Vant Version: v1.4.5

**Reproduce**

**Comment by chenjiahan** [comment]
能否提供一下复现问题的 jsfiddle
