### ISSUE TITLE
van-tabs scroll event not work.

### ISSUE THREAD

**Issue by starry** [youzan/vant#2268]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
I copy the code from example.
```html
    <div class="main">
      <van-tabs @scroll="onScroll">
        <van-tab
          v-for="index in 8"
          :title="'tab' + index"
          :key="index"
        >
          content {{ index }}
        </van-tab>
      </van-tabs>
      <div></div>
     <div></div>
    <div></div>
  </div>
```
The method onScroll didn't work when I scroll page.  Please test the example code again.
**Screenshots**
![_20181212112448](https://user-images.githubusercontent.com/31642247/49845159-9222a800-fe00-11e8-825f-4089aae6064d.png)

**Environment**
 - Device:  iphone7
 - Browser:  chrome
 - Vant Version: 1.4.8

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
In current version, the scroll event is only turned on when you use sticky prop, we will optimize this in next version

**Comment by chenjiahan** [comment]
We decide to not support scroll event in unstikcy mode for performance consideration
https://github.com/youzan/vant/pull/2691
