### ISSUE TITLE
picker 组件，getValues  返回数据错误，组件版本为：1.4.8

### ISSUE THREAD

**Issue by AsherSun** [youzan/vant#2269]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
getValues 方法会返回上一个选项的数据
**数据源：**
![image](https://user-images.githubusercontent.com/28916706/49850073-30ba0380-fe17-11e8-8628-b3e7c2c12955.png)
![image](https://user-images.githubusercontent.com/28916706/49850083-3adc0200-fe17-11e8-90f3-3be08a86340a.png)
**console.log打印的结果：**
![image](https://user-images.githubusercontent.com/28916706/49850086-429ba680-fe17-11e8-886e-f141cac9471f.png)

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 
1.4.8
**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
未复现这个问题，建议看下是不是在多列联动的时候，setValue 和 getValue 的顺序有问题，或者提供一下 jsfiddle
