### ISSUE TITLE
popup中滚动报错

### ISSUE THREAD

**Issue by zwdgit** [youzan/vant#2270]
`<van-popup v-model="showDetail" position="right">
      <van-nav-bar title="汇报详情" left-text="取消" fixed></van-nav-bar>
      <task></task>
</van-popup>`

在一个子组件中使用了Popup，里面包含一个NavBar和task(子组件)，目前出现的问题有两个：

1. NavBar 定义了 fixed，但是在滚动的时候NavBar并没有固定在顶部
2. popup滚动到顶部和底部的时候，会报错，错误提示：[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by chenjiahan** [comment]
transform 与 fixed 不兼容，参见这篇文章 http://www.zhangxinxu.com/wordpress/2015/05/css3-transform-affect/

解决方法是关闭 Popup 的动画，设置 transition="none"

**Comment by a54552239** [comment]
感觉这个方案不是特别理想

**Comment by zwdgit** [comment]
试了一下，禁用了动画之后这两个问题都没有解决

**Comment by 723tree** [comment]
修改源码，在vant/es/mixins/popup/index.js 文件里的找到onTouchMove方法，找到e.preventDefault(); e.stopPropagation();的执行条件判断语句，在if里加入一条判断 e.cancelable，亲测有效。
if (status !== '11' &&  e.cancelable && this.direction === 'vertical' && !(parseInt(status, 2) & parseInt(direction, 2))) {
        e.preventDefault();
        e.stopPropagation();
      }
