### ISSUE TITLE
[Tab] 标签页，如果想要覆盖某些组件的css，怎么做比较好？

### ISSUE THREAD

**Issue by zhangyuanliang** [youzan/vant#2271]
1. [Tab] 标签页，如果想要覆盖某些组件的css，怎么做比较好？就拿Tab标签页为例...
2. [Icon]图标，自定图标中提到可以引入需要的 iconfont 对应的 ttf 文件和样式，想问一下这个ttf文件怎么制作？

**Comment by chenjiahan** [comment]
1. 可以直接通过 class 名覆盖样式
2. ttf 可以去 http://www.iconfont.cn/ 上面制作

**Comment by zhangyuanliang** [comment]
@chenjiahan Tab 标签页中覆盖 标签字体大小不管用呢？
```
.van-tab, .van-tag--large {
    font-size: 14px;
}
```
