### ISSUE TITLE
ImagePreview如果预览的图片较多时(如30张),预览第30张图片的时候,前面的(29张图)图片没有加载完,这预览的第30张图片就不会显示.

### ISSUE THREAD

**Issue by Lojaxin** [youzan/vant#2272]
如上述标题,因为业务需求,我在初始化获取数据的时候就把所有的图片装进了一个ImagePreview组件中,但是这些图片又属于不同的Swipe组件(假设有3个),点击图片时,获取当前图片路径然后比对ImagePreview组件中的图片拿到index 进行操作(比较low),但是问题出来了!点击最后一个Swipe组件的某张图片时,应该是前面的图片没有显加载完成,导致当前的这张图片无法预览,等待很长时间(前面图片加载完成了)才出现;所以想请问有没有什么相应的方法优化解决这个问题?

**Comment by chenjiahan** [comment]
我们可以给 ImagePreview 增加一个 lazy-load 属性，开启后配合 Lazyload 组件来进行懒加载，不知道能否满足你的需求

**Comment by JackingLuo** [comment]
好的   已经解,谢谢
