### ISSUE TITLE
在iphone上，van-picker组件无法获取数据

### ISSUE THREAD

**Issue by koudiddy** [youzan/vant#2278]
vant:"1.4.3"
在iphone上，van-field输入内容后，van-cell呼出的van-popup组件中的van-picker组件在不滚动选项时，直接点击确定，v-cell无法获取数据，且van-popup组件无法关闭。
![q1](https://user-images.githubusercontent.com/39359679/49863173-ae433b00-fe3a-11e8-9282-062aae8492f8.png)
![q2](https://user-images.githubusercontent.com/39359679/49863191-b7340c80-fe3a-11e8-9f74-d05f3b0c82f5.png)
![q3](https://user-images.githubusercontent.com/39359679/49863202-bbf8c080-fe3a-11e8-9143-959bedbd2ac4.png)
![q4](https://user-images.githubusercontent.com/39359679/49863207-bf8c4780-fe3a-11e8-9153-ee96dbf55c64.png)

**Comment by chenjiahan** [comment]
微信的问题，参见 https://github.com/youzan/vant/issues/2287

**Comment by koudiddy** [comment]
感谢大佬
