### ISSUE TITLE
ios 12.1.x 微信 dialog alert

### ISSUE THREAD

**Issue by kuma0605** [youzan/vant#2287]
**Describe the bug**
在微信中，输入键盘会把页面上移，输入完成后，软键盘消失，页面处于上移状态，点击按钮发送请求，得到请求后，调用dialog.alert，弹窗中的按钮触发区域错位。
如果输入完成后，把页面下移到正常位置，再调用dialog.alert，就不会有错位问题。

这个问题是 ios12.1.x 下微信特有，软键盘点击完成后，页面仍处于上移状态。
ios11下微信就没有该问题

**Screenshots**
![img_3390](https://user-images.githubusercontent.com/2958589/49981473-05f4ba00-ff93-11e8-9f10-818011ccb806.png)

**Environment**
 - Device: iphone6s/iphone x
 - Browser: safari
 - Vant Version: 1.4.8

**Reproduce**

**Comment by kuma0605** [comment]
找到一个解决方案，
https://blog.csdn.net/Mr__Fu/article/details/84862252
点击完成按钮时，滑倒页面顶部，或者 input失去焦点时，滑到顶部

**Comment by kuma0605** [comment]
主要原因，还是微信内置浏览器没有适配ios12.1.x 软键盘

**Comment by chenjiahan** [comment]
嗯，这个是微信的问题，参见这篇文章
https://juejin.im/post/5c07442f51882528c4469769

暂时不计划在组件内做兼容，建议在项目内处理
