### ISSUE TITLE
[Tab 标签页] vue页面中引用Tab无法覆盖属性？

### ISSUE THREAD

**Issue by zhangyuanliang** [youzan/vant#2289]
最近在项目中应用了Tab组件，因为UI设计需要修改样式，发现在当前页面中无法覆盖字体大小等相关属性，能否技术支持一下，或者给个小demo？

**Comment by liuchouchou0728** [comment]
vue的scoped私有化样式
可以试试给类名加/deep/

**Comment by zhangyuanliang** [comment]
@liuchouchou0728 @chenjiahan 确实是scoped原因，谢谢
