### ISSUE TITLE
Dialog蒙层样式没能正常加载

### ISSUE THREAD

**Issue by mantou-kk** [youzan/vant#229]
### Dialog蒙层样式没能正常加载

组件里引用import {  Dialog } from 'vant';
蒙层样式没有效果，需要在main.js里全局引用 
import 'vant/lib/vant-css/index.css';

更新到0.10.2后，组件引入又变成部分样式没效果，比如：弹框的确定按钮正常是绿色的，现在是黑色。

**Comment by chenjiahan** [comment]
@mantou-kk 由于 Dialog 组件的蒙层样式依赖 Popup.css，而当前版本引入 Dialog 时不会默认引入 Popup.css，导致了上述问题。建议先通过手动引入 popup 样式的方式解决，我们会在 0.10.3 中修复此问题。
```
import 'vant/lib/vant-css/popup.css';
```

至于按钮样式的问题不是很理解，能给个示例吗

**Comment by mantou-kk** [comment]
这边需要上图片才能完整示例，
其实就是0.10.2版本单独引用 Dialog 有蒙层，但是弹窗上的一个确定按钮的字体顔色本来是绿色的，现在变成了黑色;

**Comment by chenjiahan** [comment]
已在 0.10.3 中修复
