### ISSUE TITLE
Collapse 折叠面板组件 在IOS12 的Safari交互问题

### ISSUE THREAD

**Issue by slimingda** [youzan/vant#2294]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Collapse 折叠面板 在IOS12 的Safari 或者 微信浏览器 使用效果很粗糙，基本上影响使用

**Screenshots**
用iOS12系统Safari 12打开官网首页也是用Collapse 折叠面板布局的
可以访问网址 `https://youzan.github.io/vant/#/zh-CN/quickstart`看下效果

**Environment**
 - Device: iphone7
 - Browser: safari
 - Vant Version: V1.4.8

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by LynanBreeze** [comment]
没有理解哪里粗糙。-_-
