### ISSUE TITLE
fork之后如何在项目里使用？

### ISSUE THREAD

**Issue by F5F5** [youzan/vant#2298]
**What problem does this feature solve?**
fork的仓库npm install的时候没有进行编译

**Describe the solution you'd like**
引用修改后的vant

![image](https://user-images.githubusercontent.com/15978277/50041219-54d24a80-008c-11e9-8702-5f6c5c027943.png)
### npm install 的时候只有packages和types这两个文件夹，少了es等文件夹导致报错：
![image](https://user-images.githubusercontent.com/15978277/50041230-9105ab00-008c-11e9-863c-439f964b1537.png)
### 请问一下是少了哪一步呢？

**Comment by chenjiahan** [comment]
npm run build:lib 可以编译组件

**Comment by F5F5** [comment]
@chenjiahan install的时候本地没有build文件夹怎么破啊😭明明仓库里有的

**Comment by F5F5** [comment]
![image](https://user-images.githubusercontent.com/15978277/50073707-6fcfc680-0214-11e9-8a94-46bf7f4a8f17.png)

### windows下build存在路径问题，暂时放弃windows
