### ISSUE TITLE
Picker 选择器 问题

### ISSUE THREAD

**Issue by sunjian1996916** [youzan/vant#2309]
通过 ref 可以获取到 picker 实例并调用实例方法 Picker 选择器

这个怎么使用呢  求教程 
我是一个全局的弹出选择  但是我表单是批量添加 可能涉及到每次选择的结果都是不一样 但是这个监听的不能自定义当前该表单的index 只能获取这个选择的 指  index这些

**Comment by chenjiahan** [comment]
```html
<van-picker ref="picker" />
```

```js
export default {
  mounted() {
    this.$refs.picker.setValues(xxx);
  }
}
```

大致用法如上，可以调用文档里标注的 API

**Comment by HADB** [comment]
通过 this.$refs 获取到的实例为 {}，请问是啥情况

**Comment by chenjiahan** [comment]
@HADB 必须在 mounted 之后调用

**Comment by HADB** [comment]
> @HADB 必须在 mounted 之后调用

感谢回复。我是用的 vant-weapp，后来发现在小程序里面好像不支持ref。才发现我留言到 vant 的项目里了，打扰了。

**Comment by chenjiahan** [comment]
@HADB soga..
