### ISSUE TITLE
van-search 的@search事件无法捕获value ，老版本以前是可以的

### ISSUE THREAD

**Issue by lemongeek** [youzan/vant#232]
<van-search
    v-model="value"
    placeholder="请输入商品名称"
    :show-action="true"
    @search="onSearch"
    @cancel="onCancel">
  </van-search>
以上实例在方法中的value永远是undefined
 onSearch(value){
      console.log(value);
    }

**Comment by lemongeek** [comment]
已自行解决：在data中定义value,在取值value就可以，和原先的方法不一样了

**Comment by chenjiahan** [comment]
@lemongeek 感谢反馈，我们会在下个版本中修复 onSearch 回调的参数

**Comment by chenjiahan** [comment]
已在 0.10.3 中修复
