### ISSUE TITLE
sku缩略图不可点击，需要出现轮播sku大图，如何实现？

### ISSUE THREAD

**Issue by yinxun22** [youzan/vant#2326]
想实现京东商城商品的sku展示方式，
点击缩略图，出现sku图片并轮播，但是没有找到sku缩略图的点击事件；
点击属性值，商品详情页轮播大图也需要改变为sku图片，所以属性的事件该如何解决。

![image](https://user-images.githubusercontent.com/30425924/50194341-601bc380-0375-11e9-94d2-eec9baa0d131.png)

移动端微信公众号商城

**Comment by chenjiahan** [comment]
缩略图 ImagePreview 在最新版是支持的，
点击属性的事件暂无计划提供
