### ISSUE TITLE
请教一下下拉刷新写 tab 里不起作用怎么整?

### ISSUE THREAD

**Issue by send2012** [youzan/vant#2327]
<van-tabs sticky offset-top="46" v-model="activeTab" @click="getTabContent">
            <van-pull-refresh v-model="isLoading"
                                          @refresh="onRefresh">
                    <van-tab>
                        <section class="wrapper">

**Comment by F5F5** [comment]
```
<van-tabs>
  <van-tab>
    <van-pull-refresh>
      <list></list>
    </van-pull-refresh>
  </van-tab>
</van-tabs>
```
我这样可以

**Comment by F5F5** [comment]
@send2012 是不是样式的问题，我没设高度

**Comment by send2012** [comment]
不晓得   我再试试看吧

谢谢
