### ISSUE TITLE
在文档和代码库里面没有找到设计稿，请问一下能提供设计稿给设计师参考设计吗？

### ISSUE THREAD

**Issue by xhavit** [youzan/vant#2328]
#1137 提供的地址已经无法访问了

**Comment by xhavit** [comment]
#1137 提供的地址已经无法访问了

**Comment by chenjiahan** [comment]
有的，不过组件的设计稿会和线上效果有部分出入
组件设计稿：https://github.com/youzan/vant/tree/dev/docs/assets
图标设计稿：https://github.com/youzan/vant-icons/tree/master/assets
