### ISSUE TITLE
[Feature Request] Badge 徽章切换时，需要同时拿到标签信息

### ISSUE THREAD

**Issue by liuhann** [youzan/vant#2329]
因为badge本身会加上v-if判断， 所以单纯根据index还没法确认点击了哪个徽章。

**Comment by liuhann** [comment]
目前，我是通过 event.currentTarget.innerText 拿到的... 暂时只能这样了

**Comment by chenjiahan** [comment]
加上v-if判断是啥意思呀，理论上 index 是能满足的
