### ISSUE TITLE
Tab动态title宽度问题

### ISSUE THREAD

**Issue by ansonhorse** [youzan/vant#2330]
![image](https://user-images.githubusercontent.com/7548142/50198657-76327f80-0387-11e9-99e2-92e6cd5a366e.png)

**What problem does this feature solve?**
title是通过slot渲染的，文本更新后，title部分的宽度并没有变化。

**Describe the solution you'd like**
在title变化时可以更新title部分的宽度。
或者，手动方式去触发。

**Comment by chenjiahan** [comment]
title 这个 slot 由于实现机制的原因，目前是不会动态变化的，后续我们看下有没有办法手动触发下

**Comment by ansonhorse** [comment]
好的谢谢！期待有一个更灵活好使的Tab
