### ISSUE TITLE
SwitchCell组件开关时的背景色设置无效

### ISSUE THREAD

**Issue by didashine** [youzan/vant#2331]
**Describe the bug**
SwitchCell组件active-color，inactive-color属性设置后无效果

**Screenshots**
![image](https://user-images.githubusercontent.com/19238613/50202841-653f3980-039a-11e9-8eb7-760f400d5ee6.png)
![image](https://user-images.githubusercontent.com/19238613/50202851-6c664780-039a-11e9-9945-7322a0e7e617.png)

**Environment**
 - version: 1.4.8 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
请升级到 v1.5.0-beta2 再试
