### ISSUE TITLE
android 手机竖拍图片，用upload组件上改图片后，在android设备上图片显示方向发生旋转

### ISSUE THREAD

**Issue by q569608465** [youzan/vant#2332]
**Describe the bug**
使用小米8竖拍（横拍正常）一张图片，使用vant的Uploader组件上传图片，上传到服务器后，用img标签加载该图片，发现图片方向被旋转了。而在苹果7 （IOS 12.0）、微信6.7.4上，显示正常。并且直接在PC浏览器上下载该图片，该图片方向也正常。

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/12602541/50206868-c02b5d80-03a7-11e9-91fb-b9b0606ce016.png)
![image](https://user-images.githubusercontent.com/12602541/50206963-13051500-03a8-11e9-9fde-e5e8e7cd5d0b.png)

**Environment**
 - Device: 
手机型号： MI8 Lite （小米8） 
MIUI版本： 10.01 稳定版、
Android: 8.1.0
 - Browser: 
微信6.7.3 内置浏览器
 - Vant Version: 
1.4.7

**Comment by chenjiahan** [comment]
Uploader 里面嵌套的是原生的 input type="file"，所以这个问题是原生 input 框导致的，建议去网上查下解决方法，比如 https://zhuanlan.zhihu.com/p/27627436
