### ISSUE TITLE
list loading 一直显示

### ISSUE THREAD

**Issue by CreateClear** [youzan/vant#2334]
**Describe the bug**
当页面内容较少不足以占满整个屏幕时，loading会一直显示

**Screenshots**

**Environment**

**Reproduce**

**Comment by ansonhorse** [comment]
老实说，大部分需求里，每次获取到的数据渲染后，都应该是满屏的。
如果你的分页真的设定得较小，不足一屏，那按照list的设定，它应该是继续为你加载数据的。
所以从这一点看，我觉得没什么问题。
如果实际上是没数据了还在一直loading，那就是你没有设置`finished`为`true`了。

**Comment by chenjiahan** [comment]
楼上正解
