### ISSUE TITLE
[Feature Request] Card 提供 price 和 num 插槽

### ISSUE THREAD

**Issue by LetHergo** [youzan/vant#2338]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
需求就是数量那里需要添加input选择数量 
**Describe the solution you'd like**
所以未来能否添加一个slot自定义价格和数量那一块呢？
**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.
@chenjiahan

**Comment by chenjiahan** [comment]
后续会添加一个对应的 slot

**Comment by chenjiahan** [comment]
已在 1.5.1 版本支持
