### ISSUE TITLE
能否增加一个下拉菜单及上拉加载更多

### ISSUE THREAD

**Issue by mantou-kk** [youzan/vant#234]
感觉组件比较上拉加载在移动端用得还是比较多建议增加这两个组件

**Comment by chenjiahan** [comment]
@mantou-kk 上拉加载可以使用 Waterfall 组件，下拉菜单能否给出一个示例？

**Comment by mantou-kk** [comment]
@chenjiahan
Select选择器

**Comment by chenjiahan** [comment]
@mantou-kk 移动端建议使用 Picker 而不是 Select，更符合原生交互
