### ISSUE TITLE
可否考虑同vux一样新增一些工具类内置方法

### ISSUE THREAD

**Issue by ccj-mlp** [youzan/vant#2340]
**解决一些自己再去重复造轮子封装一些常用的工具函数**
1、base64、md5方法
2、cookie 封装
3、日期格式化（官方组件拿到的日期值需要转换）
4、格式化金额方法
5、trim方法

**Comment by chenjiahan** [comment]
暂无计划支持喔，Vant 是比较纯粹的组件库，不包含这些内容
