### ISSUE TITLE
tab的color属性好像刚进入页面时候会先闪烁显示默认颜色

### ISSUE THREAD

**Issue by ccj-mlp** [youzan/vant#2342]
**tab的color属性好像只是配置tab底部条的颜色，并且我在配置了color颜色，刚进入页面时候会先闪烁显示默认颜色**
1、可否考虑新增tab底部条颜色和tab文字颜色一致的选项配置，或者新增类似text-color的属性

**Comment by chenjiahan** [comment]
闪烁的问题下个版本会修复。文字颜色这块我们评估下，看怎么提供比较合适

**Comment by chenjiahan** [comment]
闪烁问题已经在 1.5.0 版本修复
