### ISSUE TITLE
vant-fied建议支持删除线

### ISSUE THREAD

**Issue by macmatilda** [youzan/vant#2343]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
vant-field目前不支持删除线，
类似核销卡券之类的场景，需要设置文字样式为删除线

如果通过class直接给vant-field设置 文字删除线，
会导致error-message的文字样式也带删除线。
所以需要开放接口出来

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
你的场景是什么样的，能给张图片嘛，是左侧文本上显示删除线，还是输入框内容显示删除线

**Comment by macmatilda** [comment]
<img width="213" alt="2018-12-21 12 40 26" src="https://user-images.githubusercontent.com/2151838/50298009-19cf7d00-04b9-11e9-9d17-01bb34770ade.png">

其实场景很简单，就是类似优惠券的注销，需要设置text带删除线，

我只能在van-field上面加class，但是会导致错误提示也是删除线，如上图，

`
                    <van-field v-model="couponCode1"
                               center
                               clearable
                               placeholder="请输入优惠码1"
                               :class="[inputCouponCodeClass]"
                               :error-message="couponCode1ErrorMessage"
                    >
inputCouponCodeClass
    text-decoration: line-through

`

**Comment by qianzhaoy** [comment]
感觉这并不是个常用的场景...  一般要点核销按钮才请求接口券号是否核销, 已核销的基本会弹窗提示的吧.

如果真的要改删除线, 直接加个全局样式覆盖好了

**Comment by qianzhaoy** [comment]
![image](https://user-images.githubusercontent.com/14267409/50319898-af442e80-0504-11e9-9785-81117e0cc01d.png)

```javascript
                    <van-field v-model="couponCode1"
                               center
                               clearable
                               placeholder="请输入优惠码1"
                               class="delete-line"
                               :error-message="couponCode1ErrorMessage"
                    >
```

```css
.van-cell.van-field.delete-line input {
  text-decoration: line-through
}
```

**Comment by macmatilda** [comment]
ok
