### ISSUE TITLE
更新v1.5.0-beta2版本打包项目后图标加载不出来

### ISSUE THREAD

**Issue by zwdgit** [youzan/vant#2346]

**Comment by zwdgit** [comment]
所有vant提供的icon全部失效，自己加的图标没事

**Comment by bolechen** [comment]
借楼反馈个 icon 问题

我是本地 css 方式加载的 van-icon
本地开发，和微信网页测试的时候，都显示正常，线上环境有一个图标显示异常，iOS 安卓都是这样，截图如下，就是「常见问题」那个图标

![img_1785](https://user-images.githubusercontent.com/195015/50322231-34344580-050f-11e9-9d63-866ec698ba2c.JPG)
![img_1784](https://user-images.githubusercontent.com/195015/50322235-35fe0900-050f-11e9-9f2d-afd6370c5afa.PNG)

**Comment by chenjiahan** [comment]
@zwdgit @bolechen 麻烦提供下 jsfiddle，不然无法定位问题

**Comment by zwdgit** [comment]
@chenjiahan 
打包之后提示两条错误：
1.Failed to load resource: net::ERR_FILE_NOT_FOUND  vant-icon-f7d8ac.woff
2.Failed to load resource: net::ERR_FILE_NOT_FOUND vant-icon-f7d8ac.ttf
自己添加的iconfont没问题，所有引用的官方的icon都失效了
更新v1.5.0-beta2后才出现的这个问题，代码没有变
