### ISSUE TITLE
ImagePreview在PC上无法滑动无法关闭

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#2347]
**Describe the bug**
因有特殊需求，移动端的1个页面，要求内嵌在PC后台，发现该页面的ImagePreview图片预览在PC上无法滑动也无法关闭。自己去看了下ImagePreview源码，发现使用的touch事件，只能在移动端下使用，我看其它UI库的ImagePreview组件PC移动都支持，希望Vant也能支持PC~

**Environment**
 - Windows 10: 
 - 谷歌浏览器: 
 - Vant 1.4.8:

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/637
