### ISSUE TITLE
progress + popup (lazy-render = false),无法正常显示

### ISSUE THREAD

**Issue by liuruidong1994** [youzan/vant#2349]
**Describe the bug**
progress 组件放在popup组件中使用，当popup 的 lazy-render 设置为false 时，进度条长度无法正确显示
可能是隐藏时无法获取宽度,类似 #1489 的问题
吐槽一下github上传图片是真的难。
**Screenshots**
![1545369418](https://user-images.githubusercontent.com/7451379/50326000-d3af0380-0522-11e9-80f6-dfc982b4ae8f.png)
![1545369850](https://user-images.githubusercontent.com/7451379/50326268-6d2ae500-0524-11e9-92cc-647102a95b7d.png)

**Environment**
 - Device: 
pc
 - Browser: 
chrome
 - Vant Version: 
1.4.8

**Comment by chenjiahan** [comment]
嵌套的情况下，需要使用 lazy-render = true,
或者在 progress 上添加 v-if="show"
