### ISSUE TITLE
能否把DEMO示例的代码全部放出？

### ISSUE THREAD

**Issue by J3DFox** [youzan/vant#235]
对于高级组件和业务组件 手册给出的示例代码并不完整。

**Comment by chenjiahan** [comment]
@J3DFox 示例的源代码可以在这个目录下查看：https://github.com/youzan/vant/tree/dev/docs/examples-docs/zh-CN

**Comment by aikeMax** [comment]
> @J3DFox 示例的源代码可以在这个目录下查看：https://github.com/youzan/vant/tree/dev/docs/examples-docs/zh-CN

您好，404了

**Comment by chenjiahan** [comment]
现在在每个组件的 demo 目录下。

https://github.com/youzan/vant/tree/dev/packages/vant/src/button/demo

**Comment by aikeMax** [comment]
> 现在在每个组件的 demo 目录下。
> 
> https://github.com/youzan/vant/tree/dev/packages/vant/src/button/demo

好的，谢谢~
