### ISSUE TITLE
picker 配合 popup出现卡顿现象 不报错

### ISSUE THREAD

**Issue by liwenda** [youzan/vant#2351]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
不规范的 issue

**Comment by mvity** [comment]
操蛋，解决不了的问题直接close

**Comment by chenjiahan** [comment]
@mvity 连问题都描述不清，指望谁帮你解答
