### ISSUE TITLE
新版本的vant如何在nuxt中按需引入?

### ISSUE THREAD

**Issue by gongzhibin** [youzan/vant#2352]
**What problem does this feature solve?**
新版本的vant如何在nuxt中按需引入? babel-plugin-import和babel-plugin-component都不好使了

**Describe the solution you'd like**
自己写个plugin

**What does the proposed API look like?**
实现可在nuxt运行的按需引入插件

**Comment by chenjiahan** [comment]
暂无计划自己写个 plugin，建议去 babel-plugin-import 或 babel-plugin-component 提需求

**Comment by gp0320** [comment]
我最近也在用nuxt, 按需加载已搞定，请看我的文章，如有问题可以讨论一下。
https://juejin.im/post/5e012778518825127f085da8
