### ISSUE TITLE
Typescript环境下开启Toast多例模式,返回的VanToast下没有clear定义

### ISSUE THREAD

**Issue by AgilityJin** [youzan/vant#2353]
**Describe the bug**
toast开启多例模式后,使用toast返回的实例下.clear()
方法关闭toast,tslint提示实例下不存在clear()方法,实测运行时clear是存在且有效的.经过检查发现toast返回的类型是VanToast,它继承自Vue, VanPopupMixin,但二者下均无clear类型定义,存在close方法,但是使用无效
**Screenshots**
![vant-iss](https://user-images.githubusercontent.com/31586885/50340519-41285780-0556-11e9-9c6c-0e1dda02c84a.jpg)
提示内容:Property 'clear' does not exist on type 'VanToast'.

**Environment**
 - Device: vue ^2.5.17
 - Vant Version: ^1.5.0-beta

**Comment by AgilityJin** [comment]
declare module 'vant/types/toast' {
  export interface VanToast {
    clear(): void;
  }
}

**Comment by chenjiahan** [comment]
这里确实漏了，下个版本修复

**Comment by chenjiahan** [comment]
已在 1.5.0 版本修复
