### ISSUE TITLE
[Feature Request] Tab组件可否暴露出增加底色、高亮颜色、默认颜色配置

### ISSUE THREAD

**Issue by zjcwill** [youzan/vant#2361]
**What problem does this feature solve?**
动态的配置Tab组件的样式。

**Describe the solution you'd like**
Tab组件暴露出更多内部样式可覆盖属性。

Tab组件可否暴露出增加底色、高亮颜色、默认颜色配置

类似于https://doc.vux.li/zh-CN/components/tab.html 
这些属性均可定制配置。

**Comment by chenjiahan** [comment]
已在 1.6.5 版本支持

**Comment by dongliang1993** [comment]
配置高亮色，会出现一个默认颜色到自己设置颜色的一个过渡态
