### ISSUE TITLE
Stepper步进器设置integer后一种情况下不起作用

### ISSUE THREAD

**Issue by Iamsuler** [youzan/vant#2363]
**Describe the bug**
Stepper步进器设置integer=true min=0。
默认值为0，之后输入-9，组件内value为0，但是显示0-9。

**Screenshots**
![image](https://user-images.githubusercontent.com/26576925/50383713-6652cc80-06f4-11e9-8b9a-1b6737ca1f11.png)
![image](https://user-images.githubusercontent.com/26576925/50383651-5dadc680-06f3-11e9-8b0d-c3c7a1eff452.png)

**Environment**
 - Device: PC
 - Browser: Chrome 70
 - Vant Version: 1.3.0

**Comment by chenjiahan** [comment]
数字和负号是允许输入的，所以会出现上面的情况，暂时没计划做特殊处理
