### ISSUE TITLE
file://协议下加载字体文件路径错误

### ISSUE THREAD

**Issue by royall** [youzan/vant#2366]
**Describe the bug**
cordova、ionic开发，加载的本地文件，以file://文件协议打开html，加载icon字体路径失败，看代码less文件里面路径为 `//img.yzcdn.cn/vant/vant-icon-776fa2.woff2`，所以最终加载字体文件加载路径为：`file://img.yzcdn.cn/vant/vant-icon-776fa2.woff2`，找不到。建议字体文件放本地或者完整路径。

**Screenshots**
GET file://img.yzcdn.cn/vant/vant-icon-776fa2.ttf net::ERR_FILE_NOT_FOUND

**Environment**
 - Device: Android
 - Browser: Chrome
 - Vant Version: 1.5.0

**Comment by zwdgit** [comment]
出现相同的问题

**Comment by chenjiahan** [comment]
下个版本会修复这个问题

**Comment by jackhuclan** [comment]
请问 1.5.1 milestone什么时候发布？

**Comment by jackhuclan** [comment]
> 下个版本会修复这个问题

请问 1.5.1 milestone什么时候发布？

**Comment by chenjiahan** [comment]
已在 1.5.1 版本修复

**Comment by fenglingzhi** [comment]
file://协议下加载字体文件路径错误1.51这个问题修复了么

**Comment by kalecgos0616** [comment]
我在 _vant@2.6.3_ 和 _cordova@9.0.0_ 仍然遇到这个问题
我的方法是把 _vant-icon-xxxxxx.woff2_ 字体下载到 _src/assets/vant-icon-xxxxxx.woff2_
然后将 _node_modules/vant/es/icon/index.css_ 的 _@font-face_ 粘到 _src/App.vue_  <style>标签中。改成
```css
@font-face {  
  ...  
  src: url("assets/vant-icon-db1de1.woff2") format('woff2')  
}
```
