### ISSUE TITLE
icon打包失败

### ISSUE THREAD

**Issue by zwdgit** [youzan/vant#2369]
<img width="1284" alt="icon" src="https://user-images.githubusercontent.com/28926324/50409132-06127680-082b-11e9-8cf9-6e16172fda3d.png">
配置和代码都没有变，升级到 1.5.0 版本之后出现的这个问题，开发者模式下运行正常，但是 build 打包后 icon 资源文件打包失败

**Comment by Jaction** [comment]
我也发现这个问题，查看node_modules的样式发现字母这样引入//img.yzcdn.cn/vant/vant-icon-776fa2.ttf，
打包后就直接变成file://img.yzcdn.cn/vant/vant-icon-776fa2.ttf了，所以报错误

**Comment by lu381090826** [comment]
这个解决了吗？我升级到1.5.0同样问题

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/2366
