### ISSUE TITLE
van-dialog 确认点击不了

### ISSUE THREAD

**Issue by cuiziwei** [youzan/vant#2375]
版本：1.5.0
设备：iPhone XS
弹窗相关代码：`<van-dialog><van-field /></van-dialog>`（弹出的 van-dialog 框里面包含输入框）
复现方法：聚焦输入框然后弹出了键盘，输入或者不输入任何东西点击键盘上的【完成】，再点击【确认】就点不了，看了下确认按钮元素实际跑弹窗标题上去了点标题就是确认，但是如果试图滚动页面【确认】又可以正常点击了。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/2287

**Comment by cuiziwei** [comment]
@chenjiahan 谢谢，我也是 blur 时候到顶部了
