### ISSUE TITLE
nuxt中npm run dev报错

### ISSUE THREAD

**Issue by zhangaichen** [youzan/vant#2376]

**Comment by zhangaichen** [comment]
<img width="943" alt="wen1" src="https://user-images.githubusercontent.com/24717970/50430087-ef3c5480-08fc-11e9-9dbd-571b82c73cf7.png">

**Comment by zhangaichen** [comment]
"vant": "^1.4.7" 这个版本

**Comment by chenjiahan** [comment]
试了下未复现这个问题
