### ISSUE TITLE
swipe手势和swipe同时使用出现展示空白情况

### ISSUE THREAD

**Issue by yanping-jessie** [youzan/vant#2378]
**Describe the bug**
先使用手势滑动到最后一屏，再swipeTo第一屏会出现空白
或者用手势滑动到第一屏，再swipeTo最后一屏会出现空白
空白是因为该swipe-item元素translateX到不可见区域了

**Environment**
 - Device:  win7 64位
 - Browser:  chrome
 - Vant Version: vant@1.4

**Reproduce**
demo: https://output.jsbin.com/wiwujiwiqu
steps:
1、打开例子，使用手机调试模式
2、先用手势滑动到最后一屏
3、点击按钮，期望展示第一屏，但其实是空白的

**Comment by chenjiahan** [comment]
感谢反馈，下个版本修复此问题
