### ISSUE TITLE
swipe轮播组件和lazyload懒加载组件按照官方实例书写报错

### ISSUE THREAD

**Issue by shiwanjun1994** [youzan/vant#2382]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by shiwanjun1994** [comment]
轮播组件结合懒加载组件按照官方的实例来书写报错 报错内容：[Vue warn]: Failed to resolve directive: lazy      我用的是这种 import Vue from 'vue';   import { Lazyload } from 'vant';
 components: {
        [Swipe.name]: Swipe,
        [SwipeItem.name]: SwipeItem,
        [Lazyload.name]: Lazyload,
    }, 请问为什么

**Comment by chenjiahan** [comment]
请看 Lazyload 组件文档

**Comment by nongzhenli** [comment]
> 请看 Lazyload 组件文档

请问局部组件按需引入的如何正确使用 Lazyload，
Lazyload 组件文档中并没有给出示例！谢谢呢
![image](https://user-images.githubusercontent.com/19389294/79089534-0cf32e80-7d79-11ea-9fe0-82c534210b02.png)
![image](https://user-images.githubusercontent.com/19389294/79089565-27c5a300-7d79-11ea-979e-5f9d72b0129e.png)

**Comment by chenjiahan** [comment]
Lazyload 不支持局部注册喔

**Comment by mengriri** [comment]
是vant自定义指令都不支持局部注册么

**Comment by mrleolg** [comment]
官方文档没有给局部注册的示例，
Lazyload 使用率比较高，全局注册比较方便一些吧。
