### ISSUE TITLE
[Bug Report] Tab 使用 animated 属性导致标签页高度错误的问题

### ISSUE THREAD

**Issue by lszh001** [youzan/vant#2387]
测试机型: 小米Note
问题1: 粘性布局下,当Tab自动吸顶时标题文字所在区域出现小幅度抖动.
问题2: Tab2的高度大于Tab1的高度时,Tab1下滑时出现空白.

**Comment by lszh001** [comment]
问题3: swipeable滑动切换标签页时,在所有标签页中最大高度区域之外无效.

补充: 桌面端Chrome模拟和vivo xplay没有出现问题2中的情况.

**Comment by lszh001** [comment]
![uc 20181227030909](https://user-images.githubusercontent.com/45568614/50454897-69b0b700-0985-11e9-8f5f-e500979f6234.png)

**Comment by lszh001** [comment]
![33](https://user-images.githubusercontent.com/45568614/50455351-666afa80-0988-11e9-8ddb-20221defcc62.png)

**Comment by ppg408331701** [comment]
我也出现这个问题,1.5.0的版本

**Comment by lanshengzhong** [comment]
是的 问题如上所述  是否有方法切换后重新计算高度呢？

**Comment by bolechen** [comment]
+1 animated 打开报 tab 会被撑开

**Comment by chenjiahan** [comment]
目前开启 animated 属性后，各个标签页会共用最大高度（最长的那个标签页把整个容器撑开了），建议先关闭 animated，或者使用局部滚动，后续我们看下怎么优化这个问题

**Comment by LJYes** [comment]
1.6.9，遇到同样问题，开启animated后，tab1的高度会被tab2撑开

**Comment by ihamlet** [comment]
请使用v-if  与 tab 的索引值 index 做判断比较 这样就不会出现这样的问题了

**Comment by webwuyou** [comment]
看来很多人都遇到这个问题了，tab里面使用上拉加载的场景还是非常多的，当开启animated后，切换tab时，内容很少的tab页高度也会被其他tab页撑开，导致内容很少也可以上下滚动，如果关掉animated确实不太好看，要么只能换第三方的上拉加载组件了，希望官方早点解决吧。

**Comment by bolechen** [comment]
> 请使用v-if 与 tab 的索引值 index 做判断比较 这样就不会出现这样的问题了

能具体说下解决方案吗？感谢

**Comment by chenjiahan** [comment]
这个问题会在 2.0 版本修复，由于对 TabPane 的样式有一定调整，所以放到大版本里更新

**Comment by ihamlet** [comment]
`    <van-tabs v-model="tabIndex">
      <van-tab v-for="(list,index) in tab" :title="list.title" :key="index" :disabled='list.title=="筛选"'>
        <van-pull-refresh v-model="loading" @refresh="onRefresh" v-if='index == tabIndex'>`

**Comment by ihamlet** [comment]
`<van-tabs v-model="tabIndex">`
      `<van-tab v-for="(list,index) in tab">`
           `<van-pull-refresh  v-if='index == tabIndex'>`
           `</van-pull-refresh>`
      `</van-tab>`
`</van-tabs>`

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.0 版本修复
