### ISSUE TITLE
使用DatetimePicker组件（type=time），currentDate Bug?

### ISSUE THREAD

**Issue by SweetJun** [youzan/vant#2388]
**Describe the bug**
使用DatetimePicker组件（type=time），currentDate是动态绑定，每次打开都是第一次绑定的值，求解答···

jsfiddle：http://jsrun.net/wmhKp

**Screenshots**
![1](https://user-images.githubusercontent.com/19986739/50463377-4fe39400-09c6-11e9-9f8e-0f0f97b4802a.jpg)
![2](https://user-images.githubusercontent.com/19986739/50463378-51ad5780-09c6-11e9-88e5-b2191d0f78d5.jpg)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version:  1.5.0

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by multics** [comment]
试试用computed属性而不是data里的属性来绑定currentDate

**Comment by multics** [comment]
得看你的代码，jsfiddle的代码不对

**Comment by SweetJun** [comment]
http://jsrun.net/wmhKp   @multics      jsfiddle打不开，这个地址写了个demo，请指点一哈，我把v-model的值换成computedDate这样吗？ 貌似不行，每次点开都是默认第一次打开的

**Comment by multics** [comment]
把你之前的代码贴到这里回复，这样才可以帮助你找到问题
