### ISSUE TITLE
期望可以设置Toast的大小

### ISSUE THREAD

**Issue by fengxinming** [youzan/vant#2389]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
目前loading类型的Toast的大小都是固定的

**Describe the solution you'd like**
期望可以通过参数控制大小

**What does the proposed API look like?**
期望支持跟Loading类似的配置参数

**Comment by fengxinming** [comment]
@chenjiahan 图标的大小，如果也支持设置文字的大小，那更好

**Comment by chenjiahan** [comment]
考虑了下这个需求不是很强，建议直接覆盖样式处理

**Comment by fengxinming** [comment]
@chenjiahan 不能这么说，解决问题的方法有很多，肯定是采用一个影响范围最小的处理方法，如果你做不了那就算了
