### ISSUE TITLE
希望你们所有的组件图标本地化

### ISSUE THREAD

**Issue by 91xtw** [youzan/vant#2397]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
在使用组件时发现图标全部是有赞的cdn这样很不好，如果像阿里一样出现你们内部图标问题，我们使用的人就惨了，希望图标本地化或者引入第三方cdn库；

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
图标可以用本地的，见 Icon 组件文档
