### ISSUE TITLE
Coupon 优惠券选择器 顶部兑换模块的 显隐开关

### ISSUE THREAD

**Issue by CoderLQChou** [youzan/vant#241]
希望能增加 Coupon 优惠券选择器 顶部兑换模块的 显隐开关，因为目前不需要，但是又没办法隐藏。

**Comment by chenjiahan** [comment]
@CoderLQChou 好的，会在下个版本中加入

**Comment by chenjiahan** [comment]
已在 0.10.3 中加入，showExchangeBar 属性

**Comment by chenjiahan** [comment]
抱歉，0.10.3 中的 couponList 存在展示问题，请等待 0.10.4 发布后再更新
