### ISSUE TITLE
v1.5.0 icon不兼容，风格不统一

### ISSUE THREAD

**Issue by macmatilda** [youzan/vant#2410]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
vant 1.4.8升级到 1.5.0
home  变成了 home-o，了解到原因是 线框风格加-o
但是很多线框风格的icon又没有加-o，后续和实底风格冲突的时候 会有要改名
建议统一加成-o
<img width="371" alt="2018-12-31 6 32 02" src="https://user-images.githubusercontent.com/2151838/50558561-6a9d6c00-0d2a-11e9-87dc-e2cb041eb045.png">

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
由于设计资源有限，部分图标还没有对应的实底图标，短期内应该不会再大规模修改 icon
