### ISSUE TITLE
ContactList按需引入报错

### ISSUE THREAD

**Issue by Zjinxing** [youzan/vant#2411]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
单独引入ContactList报错 ‘Unknown custom element: <van-button>’

**Screenshots**
Add screenshots to help explain your problem.
![contactlist](https://user-images.githubusercontent.com/27418964/50561313-77c75480-0d44-11e9-91eb-d026a687f5f5.jpg)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
感谢反馈，已在 1.5.1 版本修复
