### ISSUE TITLE
Card组件当desc内容过长导致页面样式错乱

### ISSUE THREAD

**Issue by Zjinxing** [youzan/vant#2412]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
当Card组件的desc内容过长时 title 和 desc 会被挤到 缩略图的下一行。版本 1.5.0
**Screenshots**
<img width="421" alt="van-card" src="https://user-images.githubusercontent.com/27418964/50561413-65014f80-0d45-11e9-9f93-cb2b1703f0f2.png">

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
感谢反馈，已在 1.5.1 版本修复
