### ISSUE TITLE
sku组件增加select组件或Picker

### ISSUE THREAD

**Issue by zhangfei8080** [youzan/vant#2423]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
SKU留言模块没有下拉选项,只有文本输入?

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
暂无计划支持
