### ISSUE TITLE
tab 自定义solt问题

### ISSUE THREAD

**Issue by RubbbbbY** [youzan/vant#2429]
**Describe the bug**
tab组件添加自定义solt后首个tab的列表数据不出来

**Screenshots**
<van-tabs v-model="active" animated color="#54a8f1">
        <van-tab title="未受理">
          <div class="title-item" slot="title">
            未受理
            <span class="dos" v-if="totalCount4!=0">{{totalCount4}}</span>
          </div>
          <div class="list" v-for="(item, index) in list1" :key="index">
            <List :item="item" state="未受理"/>
          </div>
        </van-tab>
        <van-tab>
          <div class="title-item" slot="title">
            待维修
            <span class="dos" v-if="totalCount2!=0">{{totalCount2}}</span>
          </div>
          <div class="list" v-for="(item, index) in list2" :key="index">
            <List url="serviceDetail" :item="item" state="待维修"/>
          </div>
        </van-tab>
        <van-tab>
          <div class="title-item" slot="title">
            已完成
            <span class="dos" v-if="totalCount3!=0">{{totalCount3}}</span>
          </div>
          <div class="list" v-for="(item, index) in list3" :key="index">
            <List :item="item" state="已完成"/>
          </div>
        </van-tab>
        <van-tab>
          <div class="title-item" slot="title">
            已评价
            <span class="dos" v-if="totalCount4!=0">{{totalCount4}}</span>
          </div>
          <div class="list" v-for="(item, index) in list4" :key="index">
            <List :item="item" state="已评价"/>
          </div>
        </van-tab>
      </van-tabs>

，
但是最后一个tab的列表数据又没问题，可以出来

![image](https://user-images.githubusercontent.com/19768528/50630373-91061600-0f7b-11e9-997a-c341ad6e7a31.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by RubbbbbY** [comment]
![image](https://user-images.githubusercontent.com/19768528/50630547-3de09300-0f7c-11e9-885a-5f58ed1f97fc.png)
bu补张代码截图

**Comment by chenjiahan** [comment]
能否提供一下 jsfiddle 呢
