### ISSUE TITLE
【重大bug，急急急】我使用Area组件，本地测试确定和取消按钮正常显示，但是打包上线后无确定取消按钮

### ISSUE THREAD

**Issue by aTong9** [youzan/vant#2431]
**Describe the bug**
![50635241-5c4e8a80-0f8c-11e9-9843-3ed4b09b4504](https://user-images.githubusercontent.com/8253709/50635609-d2072600-0f8d-11e9-9edf-30579b10ed05.png)

**Screenshots**
本地环境
![50635309-acc5e800-0f8c-11e9-8d5e-e183984f6d9d](https://user-images.githubusercontent.com/8253709/50635641-f400a880-0f8d-11e9-8c52-0428d9457389.png)
线上环境
![50635349-ca934d00-0f8c-11e9-88ea-659506b55da4](https://user-images.githubusercontent.com/8253709/50635651-fc58e380-0f8d-11e9-8e10-923f407d1f65.png)

**Environment**
 - Device: 
 - Browser: 微信浏览器，微信开发者工具
 - Vant Version: 1.3.5

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
请确认下是否打包了多份 Vue 代码，导致语言包加载错误
