### ISSUE TITLE
按需引入与eslint引入组件检测冲突 应该怎么处理好呢？

### ISSUE THREAD

**Issue by lanshengzhong** [youzan/vant#2434]
![image](https://user-images.githubusercontent.com/20151096/50676380-02eb6780-102f-11e9-9f83-d976dddfd11f.png)
![image](https://user-images.githubusercontent.com/20151096/50676384-08e14880-102f-11e9-9e00-876e150c7e66.png)
![image](https://user-images.githubusercontent.com/20151096/50676391-10a0ed00-102f-11e9-9687-7a4711101bb7.png)
页面上使用都是van-...
目前是吧eslint相关规则关闭了， 'vue/no-unused-components': 'off',
但有没有其它方法呢？

**Comment by chenjiahan** [comment]
这个是 eslint-plugin-vue 的 bug，想规避的话只能换个写法，比如

```js
components: {
  'van-cell': Cell
}
```
