### ISSUE TITLE
accept同时添加image和video,在移动端红米手机中只生效第一个

### ISSUE THREAD

**Issue by lujian001** [youzan/vant#2435]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26424266/50678258-cc1a4f00-1038-11e9-9d78-fde80f811c55.png)
**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
这个应该是浏览器的问题，暂时没啥办法
