### ISSUE TITLE
加入腾讯x5内核oppo手机uploader组件打开图库选择图片选中后无反应，同时列表中也没有文件。

### ISSUE THREAD

**Issue by lujian001** [youzan/vant#2436]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
ps：未打入腾讯x5内核时选择无问题。
**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: oppo
 - Browser: 
 - Vant Version: 1.4.8

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
Uploader 里面用的是原生的 input[type="file"]，如果是内核兼容性问题，建议去搜下有没有解决方法
