### ISSUE TITLE
Picker 选择器的问题

### ISSUE THREAD

**Issue by lemozhang** [youzan/vant#2441]
以 AddressEdit 地址编辑业务组件的示例演示：

![1](https://user-images.githubusercontent.com/46395678/50723006-cc871880-1112-11e9-9e63-4fa36dd5ae53.png)

1. 选择一个地址，然后点确认。

![2](https://user-images.githubusercontent.com/46395678/50723025-06f0b580-1113-11e9-8a89-f95074ac9a42.png)

2. 再打开地址选项， 选择器默认值 跟 已选择的值一样

![3](https://user-images.githubusercontent.com/46395678/50723044-3bfd0800-1113-11e9-9bd8-4175cfb1c06f.png)

3. 然后再重新选择一个地址 ，但是 点击取消，或者点击遮罩层 

![4](https://user-images.githubusercontent.com/46395678/50723053-618a1180-1113-11e9-8ef9-e914445adb91.png)

4. 再次打开地址，地址选择器默认值是上次重新选择的值，不是之前点确定选择的值。

现在需求是，点确定后的值就是下次打开选择器的默认值，如果重新选择后，但点击了取消，再次打开选择器还是第一次选择的默认值。

选择器的 cancel 事件 、 change事件  和 弹出层的 click-overlay 事件 设置 defaultIndex 无用。

**Comment by chenjiahan** [comment]
暂时实现不了这个需求噢
