### ISSUE TITLE
stepper max不能根据input的事件判断，只能通过blur事件，有存在没有失去焦点提交表单的时候，value值后变化的问题

### ISSUE THREAD

**Issue by aoyeQ** [youzan/vant#2460]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
不规范的 issue
