### ISSUE TITLE
vue cli 3 yarn run build 的时候报 The "name" component has been registered but not used 

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#2462]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
vue cli 3 yarn run build 的时候报 :
he "name" component has been registered but not used (vue/no-unused-components) at src\pages\index\index.vue:93:5。
**Screenshots**
Add screenshots to help explain your problem.
![v8y0bj 5ddxnlhx zg w](https://user-images.githubusercontent.com/42430384/50804934-2cf0a280-132b-11e9-8fcf-f81ea112e953.png)

**Environment**
 - Device: win10
 - Browser: chrome  71 
 - Vant Version: 1.5.1
**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by anihCevol** [comment]
使用组件不是 这样嘛：
![qq 20190108095526](https://user-images.githubusercontent.com/42430384/50805030-8c4eb280-132b-11e9-9e6e-de82be77e319.jpg)

**Comment by anrananran** [comment]
兄弟怎么解决的？

**Comment by anihCevol** [comment]
@anrananran #2434

**Comment by anrananran** [comment]
@anihCevol  谢谢老哥，我差点就准备把eslint关了 ！
