### ISSUE TITLE
flex flex-direction: column;

### ISSUE THREAD

**Issue by caicai199604** [youzan/vant#2463]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
flex的column 上下左右居中

**Describe the solution you'd like**
目前我没有找到布局实现这个 column 上下左右居中，主要是flex-direction: column; 属性提供的无法设置到这一层，如果有的话请尽快告知我，981900309@qq.com 

**What does the proposed API look like?**
感觉可以多加一个 主轴确定的api

**Comment by chenjiahan** [comment]
无关 issue

**Comment by caicai199604** [comment]
> 不规范的 issue
![image](https://user-images.githubusercontent.com/39294321/50889998-45001900-1434-11e9-90e6-29922e24d388.png)
这个布局怎么用vant实现 ，求解 不自己写flex-direction: column;  能做到吗

**Comment by caicai199604** [comment]
@chenjiahan
