### ISSUE TITLE
根据官方示例引入自定义图标info属性不能使用，其他的属性都能使用

### ISSUE THREAD

**Issue by ccj-mlp** [youzan/vant#2465]
**根据官方示例引入自定义图标info属性不能使用，其他的属性都能使用**
开发配置vue-cli2.x
引入方法：
1、在mian.js引入import 'vant/lib/icon/local.css';
2、在local.css引入阿里图标的xxx.ttf文件
如下：
@font-face {
  font-family: 'my-icon';
  src: url('../../../../src//assets/my-icon.ttf') format('truetype');
}
.my-icon {
  font-family: 'my-icon';
}
.my-icon-smile:before {
  content: "\e636";
}
这样使用的
` <van-icon class-prefix="my-icon" name="smile" info="9"  size='30px' color='#e92321'/>`

**Comment by chenjiahan** [comment]
在你自定义的 class 上添加 `position: relative;` 可以解决这个问题
