### ISSUE TITLE
list组件

### ISSUE THREAD

**Issue by StarCarrol** [youzan/vant#2473]
**Describe the bug**
list组件滚动到底部不触发函数更新数据，按照官网例子写了，也不触发
![1547013789 1](https://user-images.githubusercontent.com/32662238/50879875-6c94b880-1417-11e9-9e3d-0487624e30ec.jpg)

**Environment**
 - Device: 
 - Browser: Google Chrome
 - Vant Version: 1.3.8

**Comment by chenjiahan** [comment]
不规范的 issue
