### ISSUE TITLE
按需引入 vue-cli3 中不能开启 css.mudules ，否则 组件的样式会无法加载，希望在文档中注明

### ISSUE THREAD

**Issue by lwjcjmx123** [youzan/vant#2475]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
理论上从 node_modules 里 import 的样式不应该被处理成 css modules 的，建议去 vue-cli3 仓库下提 issue
