### ISSUE TITLE
button组件在项目中没有点击效果，是不是因为版本问题

### ISSUE THREAD

**Issue by dulaoc** [youzan/vant#2477]
button组件在项目中没有点击效果，是不是因为版本问题

**Comment by dulaoc** [comment]
而且其他的列表一类的点击的效果都没有

**Comment by chenjiahan** [comment]
移动端部分浏览器不会默认开启 active 选择器，常见的解决方法是在 body 标签上添加一个空的 touchstart 监听，示例如下：

```
<body ontouchstart>

</body>
```

参考链接：
https://stackoverflow.com/questions/3885018/active-pseudo-class-doesnt-work-in-mobile-safari
