### ISSUE TITLE
tab标签页切换 加动画属性时 高度不能自适应

### ISSUE THREAD

**Issue by 13858715583** [youzan/vant#2482]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
tab标签页切换 加动画属性时 高度不能自适应

**Screenshots**
Add screenshots to help explain your problem.
标签页第一页
![image](https://user-images.githubusercontent.com/36024348/50947181-f906b000-14d7-11e9-8f42-2548dec8ca0d.png)
切换标签页第二页  正常
![image](https://user-images.githubusercontent.com/36024348/50947228-31a68980-14d8-11e9-8c68-70b6d1f4917a.png)
从第二页切换回第一页 高度不正常
![image](https://user-images.githubusercontent.com/36024348/50947262-5dc20a80-14d8-11e9-857a-ea7372629334.png)
加了动画属性 animated 就出现这种情况     
 注（标签页第二页高度比第一页高度高）

**Environment**
 - Device: mobile
 - Browser: chrome
 - Vant Version: 1.5.0

**Reproduce**
无

**Comment by 13858715583** [comment]
tab标签页切换

**Comment by chenjiahan** [comment]
重复 issue
https://github.com/youzan/vant/issues/2387
