### ISSUE TITLE
AddressEdit 触发select-search后修改addressDetail导致收货人、电话消失

### ISSUE THREAD

**Issue by superlbr** [youzan/vant#2483]
**Describe the bug**
A clear description of what the bug is.
AddressEdit 在未保存之前，表单Content无法获取（收货人、电话等）
**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: PC
 - Browser: Chrome
 - Vant Version: 1.5.1

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/superlbr/f9L6mdtj/7/

**Comment by superlbr** [comment]
关于修改addressDetail可以调用内部方法setAddressDetail
给组件加个ref，搞定，但是不能提前拿到表单的值不太友好

**Comment by chenjiahan** [comment]
setAddressDetail 是满足需求的，暂时没计划添加新的 api 去获取其他表单项

**Comment by superlbr** [comment]
however it's not in document, found in source code
