### ISSUE TITLE
pc端微信兼容问题（无法正确点击按钮位置）

### ISSUE THREAD

**Issue by longjining** [youzan/vant#2486]
**Describe the bug**
使用微信web开发者工具打开demo，但是点击的事件无法触发，或者是点击区域发生偏离，如点击的是p(10,20)，但是响应的是另一个位置p(20,50)的按钮，
这样就导致 pc端微信无法正常使用；
请问你们是否有遇到类似的问题？ 如果有，是否有计划修复该问题？或者说有别的解决方案？ 谢谢

**Screenshots**
![20190110234222](https://user-images.githubusercontent.com/5483293/50979714-0cdf0000-1532-11e9-868f-86392f5591cf.png)

**Environment**
 - Device: PC
 - Browser: 微信web开发者工具
 - Vant Version: 1.5.2

**Reproduce**
1.安装微信web开发者工具
2.下载https://github.com/youzan/vant-demo，并把vant升级到1.5.2
3.运行demo，并在微信web开发者工具地址栏中打开demo

**Comment by chenjiahan** [comment]
这个是微信的问题，我们也木有办法

**Comment by longjining** [comment]
好的，谢谢。 我用vue官方的demo也有问题，确实不是你们vant的问题，不好意思，打扰了。
