### ISSUE TITLE
nuxt如何定制主题？

### ISSUE THREAD

**Issue by hopkinson** [youzan/vant#2488]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
我参考了文档中提供的方法定制主题，但似乎不能实现。

**Describe the solution you'd like**
能不能通过babel-plugin-import方式引用，还是可以通过其他？

**What does the proposed API look like?**

**Comment by chenjiahan** [comment]
手动引入组件对应的 less 文件，然后覆盖变量就可以

**Comment by 750973092** [comment]
如果不是less而是scss呢,怎么定制主题

**Comment by gp0320** [comment]
我最近也在用nuxt, 按需加载已搞定，请看我的文章
https://juejin.im/post/5e012778518825127f085da8
