### ISSUE TITLE
ios12.0 和12.1.2以下版本    Dialog.confirm  确定 取消 无反应

### ISSUE THREAD

**Issue by JulyChou** [youzan/vant#2489]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
  ios12.0 和12.1.2以下版本    Dialog.confirm  确定 取消 无反应

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 微信  ios  ios12.0 和12.1.2 
 - Vant Version:  13.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
不规范的 issue

**Comment by Hansuku** [comment]
这个问题确实存在 咋给关了

**Comment by JulyChou** [comment]
第一次提问，都没有解决，就给关了，-_-~

**Comment by chenjiahan** [comment]
类似的 issue 随便搜索下就有解答
https://github.com/youzan/vant/issues/2287
