### ISSUE TITLE
tabbar自定义的情况下 无法生成info 是否考虑添加这个功能

### ISSUE THREAD

**Issue by hnlinzhi19** [youzan/vant#249]
### tabbar自定义的情况下 无法生成info 是否考虑添加这个功能
**希望添加功能?**

**目前版本添加自定义的时候 info字段是没有意义的**

**Comment by chenjiahan** [comment]
@hnlinzhi19 目前确实有这个问题，会在下个版本中修复

**Comment by chenjiahan** [comment]
已在 0.10.5 中修复~
