### ISSUE TITLE
toast allowMultiple 会出现异常

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#2491]
`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

是什么原因呢? 是在两个方法中不能调用还是要独立引入后才可以使用 allowMultiple

```
methods1(){
 this.$toast.allowMultiple(true)
this.$toast({message: "操作成功"});
thisi.methods2();
}

methods2(){
let loading = this.$toast.loading({message: "正在加载...", duration: 10000});

xxxx().then((res)=>{
 loading.clear()
}).catch((e)=>{
 loading.clear()
})
}
```

**Comment by chenjiahan** [comment]
试了下没问题，建议升级版本或提供下 jsfiddle

**Comment by lihaotian0607** [comment]
> 试了下没问题，建议升级版本或提供下 jsfiddle

https://jsfiddle.net/LeeHaoTian/xajk35ny/29/ 
点击提交之后就可以看到

**Comment by chenjiahan** [comment]
感谢反馈，这里确实存在问题，已经修复，会在下个版本发布

**Comment by chenjiahan** [comment]
已在 1.6.0 版本修复
