### ISSUE TITLE
van-tabbar 在nuxt.js 会报vue-warn

### ISSUE THREAD

**Issue by linwenfeng122** [youzan/vant#2492]
如题在用全局引入后会出现：[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
![github](https://user-images.githubusercontent.com/19618653/51020211-e1532880-15b8-11e9-909f-7574a27313b7.png)

**Comment by chenjiahan** [comment]
这个问题应该和 vant 没什么关系，建议看下是不是有组件没正确注册

**Comment by axetroy** [comment]
同样的问题，关键是已经进行全局注册了，也就不应该有漏掉的，而且客户端正常显示
