### ISSUE TITLE
lazyLoad 背景图加载模式，路径解析异常小BUG？

### ISSUE THREAD

**Issue by cjsky666** [youzan/vant#2502]
我使用window10系统作为开发环境。 
系统默认存储的文件路径为反斜杠 \\ 
数据取回之后在lazyLoad 模块下的背景图模式渲染 
但是会解析错误。所有反斜杠 ’\‘ 均会被过滤掉。
亲测，手动改动数据的反斜杠为 / 。工作正常
[请开发组，解决一下]
图片的地址分别是
` /static/image/otherImage/20190102/40946912d7704466bc542ba58c1b5993.jpg，
/static\image\otherImage\20190106\d18c42abebec4fb79985010732a0a40athumbnail.png
`
第一张正常解析 。第二张所有反斜杠全部被忽略。解析结果如下：
`http://localhost:8006/staticimageotherImage%EF%BF%BD06%EF%BF%BDabebec4fb79985010732a0a40a.png`

**Comment by chenjiahan** [comment]
Vant 里的 LazyLoad 使用的是 vue-lazyload，可以到对应仓库提问喔
https://github.com/hilongjw/vue-lazyload
