### ISSUE TITLE
多个输入框需要输入数字，NumberKeyboard怎么应用最合适 

### ISSUE THREAD

**Issue by danywheeler** [youzan/vant#2507]
![image](https://user-images.githubusercontent.com/8910772/51070541-dca47800-167d-11e9-8f54-ab9aefd7f03a.png)
![image](https://user-images.githubusercontent.com/8910772/51070542-e62de000-167d-11e9-9fb5-a6823963624f.png)

这是我当前的实现，但是感觉上很怪异，Numberkeyboard是不是应该能实现某个机制和输入框绑定，还有input和delete是不是感觉有点多余，是不是可以实现和keypress类似的处理，keycode value啥的，刚从react还vue搞一个项目，手机端刚试试vant这个UI :)

**Comment by chenjiahan** [comment]
点击输入框的时候，用一个变量保存当前输入框的 name，这样你就知道键盘输入内容的时候对应的是哪个输入框了。
input 和 delete 相比于 keypress 比较直观一些
