### ISSUE TITLE
Contact 联系人组件bug

### ISSUE THREAD

**Issue by androidxu** [youzan/vant#2515]
新增的联系人列表长度超过页面的时候出现，官网可复现，截图如下
![image](https://user-images.githubusercontent.com/14267529/51085072-451f5200-176f-11e9-9201-42c1138c2c4e.png)

**Comment by androidxu** [comment]
个人处理方法，使用深度作用选择器，修改样式。

**Comment by chenjiahan** [comment]
已在 1.6.0 版本修复
