### ISSUE TITLE
建议优化一下Field组件样式

### ISSUE THREAD

**Issue by zwdgit** [youzan/vant#2518]
<img width="390" alt="wx20190114-105659 2x" src="https://user-images.githubusercontent.com/28926324/51094827-3fffe880-17eb-11e9-90b4-56e7447d5377.png">

Field 组件 title 和 value 文字总是对不齐，每次都要手动调一下，很是麻烦，建议官方可以优化一下

**Comment by chenjiahan** [comment]
没复现这个问题，建议看下是不是你项目的样式干扰了
