### ISSUE TITLE
Dialog组件点击蒙版关闭窗口时候未触发beforeClose事件

### ISSUE THREAD

**Issue by snowzijun** [youzan/vant#2519]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Dialog组件点击蒙版关闭窗口时候未触发beforeClose事件

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: window 10
 - Browser:  chrome 71
 - Vant Version: 1.5.0

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
后续会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.6.2 版本修复
