### ISSUE TITLE
样式名改动也顺便放到更新日志里T^T

### ISSUE THREAD

**Issue by ZhengXiaowei** [youzan/vant#2520]
之前遮罩层的名字是van-modal。。。原来有对遮罩的组件做了二次封装，关闭后 会从dom上进行移除的。。可是改了之后不知道。。。导致程序也报错了（和我写的也有关系 = =）
`this.$el.parentNode.removeChild(document.querySelector(".van-modal"))`

希望之后如果有改动的到样式名的。。也提个醒。。。

**Comment by chenjiahan** [comment]
手动操作 DOM 的方式是不推荐的呢
我们这边会尽量减少类名的改动，开放更多定义样式的 props

**Comment by ZhengXiaowei** [comment]
@chenjiahan 对了 你们有计划 针对这些pop或者toast开放一些关闭后的回调吗

**Comment by chenjiahan** [comment]
@ZhengXiaowei 可以加的，需要的话可以新开个 issue 描述下
