### ISSUE TITLE
van-swipe-cell，click事件的时候需要做交互，如何传参

### ISSUE THREAD

**Issue by z331364252** [youzan/vant#2521]
![image](https://user-images.githubusercontent.com/19758591/51100921-4904b000-1813-11e9-965a-d4e4d88d1b0f.png)
描述：close的时候，需要获取cell的当前数据，可以用闭包获取，但是click的时候，也需要获取当前点击对象的数据。

需求：click的时候，判断click的是cell,并且能获取当前的cell数据。

**Comment by chenjiahan** [comment]
同样可以用闭包实现吧？
