### ISSUE TITLE
加载NoticeBar之后，会破坏Actionsheet样式

### ISSUE THREAD

**Issue by zwdgit** [youzan/vant#2525]
单独使用Actionsheet组件是正常的，但是当加载过NoticeBar组件之后，Actionsheet就无法正常上滑显示

![111](https://user-images.githubusercontent.com/28926324/51156502-d6e5a700-18b6-11e9-99ba-78aaa3a2c12f.gif)

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle
