### ISSUE TITLE
SSR项目中，以按需引入的方式，在刷新页面的时候报错

### ISSUE THREAD

**Issue by zgh0711** [youzan/vant#2527]
如题，在SSR的项目中，以按需引入的方式引入了 list 组件，
```
  import 'vant/lib/list/style';
  import list from 'vant/lib/list';
```
正常使用没有问题，但是当在刷新页面的时候会报错，错误信息如下
![_20190115162930](https://user-images.githubusercontent.com/15401997/51167910-c3503580-18e2-11e9-9086-3da57da35c4d.png)
![_20190115163219](https://user-images.githubusercontent.com/15401997/51168058-2d68da80-18e3-11e9-82c2-dbf3bc320823.png)

请问下这问题如何解决。

**Comment by chenjiahan** [comment]
看起来是配置的问题呢，按需引入无非是在 js 文件中 import 对应的样式文件，没有什么特殊的逻辑

**Comment by chengz7** [comment]
我也遇到了同样的问题，这怎么解决呢
