### ISSUE TITLE
点击事件ios端不兼容的问题

### ISSUE THREAD

**Issue by Xshaodong2018** [youzan/vant#2528]
1. ios用了vant组件,凡是用到点击事件的地方,因为组件外面没有button或者a标签,ios端点击能检测到但是不能执行点击事件的一个动画效果,
2. 建议是有需要点击的地方外面加一层a标签或者是button按钮来兼容ios端
3. 问题出现的地方有(单元格模块)

**Comment by chenjiahan** [comment]
点击反馈效果参见 https://github.com/youzan/vant/issues/2477
