### ISSUE TITLE
popup组件内容超出屏幕高度时，滚动报错

### ISSUE THREAD

**Issue by zwdgit** [youzan/vant#2532]
当popup中的内容超出屏幕范围出现滚动条后，上下滑动会出现卡顿，偶尔滑动不了，并且控制台会报错

<img width="1275" alt="wx20190116-120228 2x" src="https://user-images.githubusercontent.com/28926324/51225727-da486380-1986-11e9-9870-6f13ff8818e2.png">

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle
