### ISSUE TITLE
van-tab 组件是否可以提供竖屏布局样式？

### ISSUE THREAD

**Issue by Sean-Wang** [youzan/vant#2533]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
van-tab 组件目前只有横屏布局样式。

**Describe the solution you'd like**
希望 van-tab 组件提供竖屏布局样式。

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
暂无计划支持
