### ISSUE TITLE
使用定制主题报错 Unrecognised input

### ISSUE THREAD

**Issue by yanpeng4665** [youzan/vant#2536]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
项目使用的是vue-cli2生成的
babel版本是6
使用的是手动引入样式文件
// 手动引入组件的样式源文件
import Button from 'vant/lib/button';
import 'vant/lib/button/style/less';

在 webpack.base.conf.js 文件里面复制
{
      test: /\.less$/,
      use: [
        // ...other loaders
        {
          loader: 'less-loader',
          options: {
            modifyVars: {
              red: '#03a9f4',
              blue: '#3eaf7c',
              orange: '#f08d49',
              'text-color': '#111'
            }
          }
        }
      ]
    }
**Screenshots**
Add screenshots to help explain your problem.
Module build failed:

// load the styles
var content = require("!!../../../_css-loader@0.28.11@css-loader/index.js??ref--9-1!../../../_postcss-loader@2.1.6@postcss-l
oader/lib/index.js??ref--9-2!../../../_less-loader@4.1.0@less-loader/dist/cjs.js??ref--9-3!./base.less");
          ^
Unrecognised input
      in /Users/yanpeng/work/***/web/trunk/patient_wei/node_modules/_vant@1.5.2@vant/lib/style/base.less (line 4, column
12)

 @ ./node_modules/_vant@1.5.2@vant/lib/tab/style/less.js 1:0-32
 @ ./src/modules/my_cases/my_cases.js
 @ multi ./node_modules/_webpack-dev-server@2.11.3@webpack-dev-server/client?http://192.168.1.119:8080 webpack/hot/dev-serve
r ./src/modules/my_cases/my_cases.js
**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.

**Comment by chenjiahan** [comment]
建议看下你的 loader 是否都配置正确

**Comment by woerouyang** [comment]
@yanpeng4665  我也遇到同样的问题，请问楼主怎么解决了呢？

**Comment by xiaorock** [comment]
这个问题解决了么

**Comment by yanpeng4665** [comment]
升级vue-cli3




            
            
                
                    
                            
                                
                            
                            
                                845543600
                            
                    
                        
                            
                                    邮箱：845543600@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2020年04月22日 11:15，xiaorock 写道： 
这个问题解决了么

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/youzan/vant/issues/2536#issuecomment-617523522",
"url": "https://github.com/youzan/vant/issues/2536#issuecomment-617523522",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
