### ISSUE TITLE
ImagePreview全局引入不能使用

### ISSUE THREAD

**Issue by tomorrow-here** [youzan/vant#2537]
全局引入的时候提示ImagePreview未定义
- index.vue?0dbc:71 Uncaught ReferenceError: ImagePreview is not defined
 - Device: pc, 手机
 - Browser: 谷歌浏览器，qq浏览器
 - Vant Version: vant1.5.1, vant1.5.2

- 代码段
> 地址：https://jsfiddle.net/6my70brs/16/

**Comment by tomorrow-here** [comment]
全局引入之后，必须在局部引入之后才能用，但是局部引入之后不需要再注册就可以用了...

**Comment by chenjiahan** [comment]
ImagePreview 是通过函数方式调用的，只能在局部引入

**Comment by tomorrow-here** [comment]
> ImagePreview 是通过函数方式调用的，只能在局部引入

奥奥，知道了

**Comment by JL-Code** [comment]
> ImagePreview 是通过函数方式调用的，只能在局部引入

import ImagePreview from "vant"; 引入的 时 输出 ImagePreview 
```js
{install: ƒ, version: "1.6.6"}
```
 是一个和文档示例的符合
