### ISSUE TITLE
Van-tab高度的Bug

### ISSUE THREAD

**Issue by coolRoger** [youzan/vant#2538]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Van-tab元素的高度只会取所有tabs中内容最多的tab作为高度,并不是取当前active tab的内容作为高度.

**Screenshots**
当选中"线上课程"时,tab-page底部留了大部分空白:
![_20190116175224](https://user-images.githubusercontent.com/33861624/51240993-ded94000-19b7-11e9-9bb4-7f52ec02bda7.png)
![_20190116175229](https://user-images.githubusercontent.com/33861624/51241171-337cbb00-19b8-11e9-8bc8-c0450b633334.png)

当选中"线下实训"时,tab-page底部没有留白:
![_20190116175233](https://user-images.githubusercontent.com/33861624/51241104-13e59280-19b8-11e9-8751-f5bb962fa47b.png)
![_20190116175236](https://user-images.githubusercontent.com/33861624/51241124-1c3dcd80-19b8-11e9-977d-fd349a930bc6.png)

即可得出结论: tab-page的高度是由内容最多的tab-page决定的.
**所以,请问如何使tab-page的高度是由当前选中的tab来决定的? 谢谢**

**Environment**
 - Device: 微信开发者工具
 - Browser: 
 - Vant Version: 0.4.10

**Comment by chenjiahan** [comment]
重复 issue
https://github.com/youzan/vant/issues/2387
