### ISSUE TITLE
加载NoticeBar之后，会破坏Actionsheet样式

### ISSUE THREAD

**Issue by zwdgit** [youzan/vant#2542]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
页面加载 NoticeBar 组件之后，所有vue实例中使用到的 Actionsheet 组件样式都会被破坏，原本平滑上拉动画会出现明显的错乱

**Screenshots**
![111](https://user-images.githubusercontent.com/28926324/51287560-10dbb800-1a33-11e9-913e-9c37f0edc095.gif)

**Environment**
 - Device: MacOS 10.14.2
 - Browser: Chrome 71.0.3578.98（正式版本） （64 位）
 - Vant Version:  v1.5.2

**Reproduce**
抱歉，没使用过jsfiddle，简单描述一下：
A 页面加载 Actionsheet 组件（按需引入）
B 页面加载 NoticeBar 组件 （按需引入）
首次加载A页面，组件正常，跳转B页面，加载过 NoticeBar 组件后，再来查看 Actionsheet 组件，就会出现上述描述的问题

**Comment by chenjiahan** [comment]
NoticeBar 组件理论上来说不会影响 Actionsheet 组件呢，是否有其他样式产生了干扰？

**Comment by zwdgit** [comment]
> NoticeBar组件理论上来说不会影响Actionsheet组件呢，是否有其他样式产生了干扰？

我取消使用 Actionsheet 组件之后，一切正常

**Comment by zwdgit** [comment]
`components: {
      [NoticeBar.name]: NoticeBar,
    },`

只要在 components 中引用了 NoticeBar 组件，不管有没有使用<van-notice-bar></van-notice-bar>，都会出现动态图中的bug

**Comment by chenjiahan** [comment]
未能复现这个问题，建议提供一下 jsfiddle，不然我们无法帮你定位问题
