### ISSUE TITLE
字体图标使用hbuilder打包成app后无法显示

### ISSUE THREAD

**Issue by yizhiyan** [youzan/vant#2545]
今天使用框架自带的字体图标写了个小项目，打算打包成app，使用hbuilder打包后，安装打开发现字体图标不显示了。

**Comment by AAADream** [comment]
这个问题解决了吗老哥，我也遇到这个问题求解决

**Comment by chenjiahan** [comment]
建议去 hbuilder 下面提 issue 呢，vant 使用的是标准的 iconfont 格式
