### ISSUE TITLE
 <van-tabbar-item icon="freinds-o"">标签</van-tabbar-item>    文档单词拼写错误  双字符串

### ISSUE THREAD

**Issue by zhanglongjiZLJ** [youzan/vant#2546]
<van-tabbar-item icon="home-o">标签</van-tabbar-item>
  <van-tabbar-item icon="search">标签</van-tabbar-item>
  <van-tabbar-item icon="freinds-o"">标签</van-tabbar-item>
  <van-tabbar-item icon="setting-o">标签</van-tabbar-item>

**Comment by chenjiahan** [comment]
感谢反馈，文档已更新
