### ISSUE TITLE
Dialog组件按需引用的时候很多属性都没效果

### ISSUE THREAD

**Issue by Shen-Yu** [youzan/vant#2548]
**Describe the bug**
Dialog组件的很多属性用了都没效果

**Screenshots**
[![kpw2od.png](https://s2.ax1x.com/2019/01/17/kpw2od.png)](https://imgchr.com/i/kpw2od)
[![kpwWFA.png](https://s2.ax1x.com/2019/01/17/kpwWFA.png)](https://imgchr.com/i/kpwWFA)

**Environment**
 - Device: 浏览器
 - Browser: chrome v63.0
 - Vant Version: v1.4.1
/

**Comment by chenjiahan** [comment]
具体是哪个属性没用？
