### ISSUE TITLE
图标库不方便管理，建议开源字体图标库

### ISSUE THREAD

**Issue by pangxieju** [youzan/vant#255]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@pangxieju 图标库是开源的，目录在 https://github.com/youzan/vant/tree/dev/packages/vant-css/scripts

**Comment by cookfront** [comment]
所有的图标都在： [https://github.com/youzan/vant/tree/dev/packages/vant-css/assets](https://github.com/youzan/vant/tree/dev/packages/vant-css/assets) 下的icons.sketch文件中

**Comment by pangxieju** [comment]
谢谢！

**Comment by bolechen** [comment]
> 所有的图标都在： https://github.com/youzan/vant/tree/dev/packages/vant-css/assets 下的icons.sketch文件中

打不开了？有最新的 sketch 文件吗？thx
