### ISSUE TITLE
Dialog组件高级用法报 [Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by wshuai222333** [youzan/vant#2552]
Dialog组件高级用法
beforeClose(action, done) {
      if (action === "confirm") {
        setTimeout(this.AddBankCard, 1000);
      } else {
        done();
      }
    },
AddBankCard（）{
this.$router.push("CardList");
}
当跳转路由的时候  页面就会报vue警告
[Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'id' of undefined"
我的页面没有id属性，应该是vant组件的问题

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle
