### ISSUE TITLE
请问支持自定义主题色或者有支持计划么？

### ISSUE THREAD

**Issue by xiaolongyuan** [youzan/vant#256]
类似 https://vux.li/#/?id=%E9%A2%9C%E8%89%B2%E9%85%8D%E7%BD%AE

**Comment by chenjiahan** [comment]
参见 [定制主题](https://www.youzanyun.com/zanui/vue#/zh-CN/component/theme)

**Comment by xiaolongyuan** [comment]
项目严重缺乏安利  才1k satr

**Comment by chenjiahan** [comment]
哈哈，目前还在专注打磨代码，欢迎帮忙一起宣传~
