### ISSUE TITLE
为什么标签van-button报错？

### ISSUE THREAD

**Issue by hhsacsb** [youzan/vant#2562]
问题说明：
"<van-button type="warning">警告按钮</van-button>"这段代码报错，说没有templateLoader.js的意思，为什么呢？

代码：
<template>
	   
	<button class="van-button van-button--primary van-button--normal">...</button>
	<van-button type="warning">警告按钮</van-button>
	
</template>

<script>
	// import Button from '../../vant/lib/button';
	// import '../../vant/lib/index.css';
	export default {
		data() {
			return {}
		},
		methods: {}
	}
</script>
</style>

控制台报错信息：
Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
16:57:12.021 (Emitted value instead of an instance of Error) 
16:57:12.024   Error compiling template:
16:57:12.024   <button class="van-button van-button--primary van-button--normal">...</button>
16:57:12.028   <van-button type="warning">警告按钮</van-button>
16:57:12.028   - Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

**Comment by chenjiahan** [comment]
看 Vue 的提示，和组件无关
```bash
Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.
```
