### ISSUE TITLE
van-coupon-cell 右边的显示自定义

### ISSUE THREAD

**Issue by pengbo37877** [youzan/vant#2566]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
优惠券现在只能显示负值，但是有时候要显示正值

**Comment by chenjiahan** [comment]
自定义的话，推荐直接用 Cell 组件，CouponCell 也是基于 Cell 简单封装了一下
