### ISSUE TITLE
希望直接支持按需引入组件

### ISSUE THREAD

**Issue by xiaolongyuan** [youzan/vant#257]
类似 vux 有一个 vux-loader 可以在这个里面进行

**Comment by chenjiahan** [comment]
@xiaolongyuan 请参考 [快速上手](https://www.youzanyun.com/zanui/vue#/zh-CN/component/quickstart) 中的按需引入组件

**Comment by xiaolongyuan** [comment]
回复真快  这种我看见了 我的意思是 不需要这个配置 直接支持

还有个问题 vant的设计稿尺寸是多大？

**Comment by chenjiahan** [comment]
@xiaolongyuan 
1. Babel Plugin 和 Vue Loader 做的工作是一样的，所以我们不会再去开发一个类似 vux-loader 的插件
2. 设计稿的尺寸是标准 iphone6

**Comment by xiaolongyuan** [comment]
好的 谢谢
