### ISSUE TITLE
addressedit 地址编辑器选择地区的问题

### ISSUE THREAD

**Issue by mghda** [youzan/vant#2577]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
你好：出现的问题是地址编辑器选择区域最上面的栏目没有显示“确认”和“取消”按钮，提示的警告是Locale not correctly registered，已经设置过国际化了而且系统默认的是中文。

**Screenshots**
Locale not correctly registered

**Environment**
 - Device: win10
 - Browser: chrome
 - Vant Version: 1.5.4

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
建议看下是不是打包了多份 Vue 代码
