### ISSUE TITLE
Card 卡片的origin-price请提供slot方便自定义

### ISSUE THREAD

**Issue by nnzbz** [youzan/vant#2580]
**What problem does this feature solve?**
我们需要自定义origin-price的文字描述

**Describe the solution you'd like**
我们需要在原始价格前面加上几个字

**What does the proposed API look like?**
将origin-price设置为slot

**Comment by chenjiahan** [comment]
下个版本支持

**Comment by chenjiahan** [comment]
已在 1.5.6 版本支持
