### ISSUE TITLE
van-field设置type为password输入的时候不显示星号

### ISSUE THREAD

**Issue by mike8625** [youzan/vant#2581]
**Describe the bug**
A clear description of what the bug is.
van-field设置type为password输入的时候不显示星号,还显示文字
**Screenshots**
Add screenshots to help explain your problem.
        <van-field
            v-model="password"
            type="password" //这里是password 但是输入的时候 还能看见文字
            label="密码"
            placeholder="请输入密码"
            required
        />
**Environment**
any
 - Device: 
any
 - Browser: 
any
 - Vant Version: 
1.5.4
**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://youzan.github.io/vant/#/zh-CN/field 你们官网的例子就有问题 type=password 竟然还能显示文字

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/issues/2575

**Comment by Lei0901** [comment]
1.5.5版本中没有解决
