### ISSUE TITLE
radio和checkbox样式不一致

### ISSUE THREAD

**Issue by Shiroyan** [youzan/vant#2583]
**Describe the bug**
radio和checkbox的样式不一样

**Screenshots**
![image](https://user-images.githubusercontent.com/26413534/51516061-e897f300-1e50-11e9-8233-cdb5da25ba80.png)

![image](https://user-images.githubusercontent.com/26413534/51516050-dcac3100-1e50-11e9-853d-d1f739552937.png)

**Environment**
 - Device: PC
 - Browser: chrome
 - Vant Version: 1.5.4

**Reproduce**
官网demo上就是这样的

**Comment by chenjiahan** [comment]
后续会统一掉

**Comment by chenjiahan** [comment]
已在 1.6.0 版本统一
