### ISSUE TITLE
这是一条咨询， 非技术issues

### ISSUE THREAD

**Issue by JETWLL** [youzan/vant#259]
朋友想购买有赞的小程序套餐，问认不认识有赞的朋友，可不可以搞个内部优惠价。
虽然不认识，但是有赞开源的代码咱是用过的，所以，前来咨询下各位大神，能不能帮帮忙！
(如果违反了 issues 规则，在这说声抱歉！)

**Comment by pangxie1991** [comment]
1. 内部员工在价格上面也没有任何优惠
2. 市场会不定期的推优惠套餐，看了下估计月底前都有，有兴趣可以联系销售，0571 - 8522 5188
3. 小程序支持有赞币抵扣的，订购及推荐及掌柜任务都可以获得有赞币~

早买早优惠~~

你可以把联系方式发我邮箱，我让负责的同事直接联系你
