### ISSUE TITLE
轮播图片懒加载

### ISSUE THREAD

**Issue by YangGoldDragon** [youzan/vant#2593]
**Describe the bug**
在使用v-lazy功能后，轮播有3个或以上的页面，只显示前两个页面，之后的页面都是空白的

**Screenshots**
![image](https://user-images.githubusercontent.com/22095365/51545812-be205700-1e9d-11e9-8388-11d579877aea.png)
![image](https://user-images.githubusercontent.com/22095365/51545838-caa4af80-1e9d-11e9-8acb-5dc777b6ec96.png)
![image](https://user-images.githubusercontent.com/22095365/51546010-2ff8a080-1e9e-11e9-8204-f58d59604678.png)

**Environment**
 - Device: win10 * 64
 - Browser: latest chrome
 - Vant Version: latest vant

**Reproduce**
在index.vue的组件里。你可以看一下我的代码，github地址是https://github.com/YangGoldDragon/dj

**Comment by StarryYang** [comment]
> **Describe the bug**
> 在使用v-lazy功能后，轮播有3个或以上的页面，只显示前两个页面，之后的页面都是空白的
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/22095365/51545812-be205700-1e9d-11e9-8388-11d579877aea.png)
> ![image](https://user-images.githubusercontent.com/22095365/51545838-caa4af80-1e9d-11e9-8acb-5dc777b6ec96.png)
> ![image](https://user-images.githubusercontent.com/22095365/51546010-2ff8a080-1e9e-11e9-8204-f58d59604678.png)
> 
> **Environment**
> 
> * Device: win10 * 64
> * Browser: latest chrome
> * Vant Version: latest vant
> 
> **Reproduce**
> 在index.vue的组件里。你可以看一下我的代码，github地址是https://github.com/YangGoldDragon/dj
您好，你的代码我看过了，需要去配置一下你的lazyload的请求次数：
![image](https://user-images.githubusercontent.com/27389941/51585885-0b400f80-1f16-11e9-8838-e3d407d6d7c4.png)

**Comment by YangGoldDragon** [comment]
fit it, thanks
