### ISSUE TITLE
sku组件initialSku数据变更，但界面不能即时响应变更！  如有颜色为黑色，白色，之前为黑色，但我改选了白色，再赋值给initailSku，但是再点击进去，还是显示白色。

### ISSUE THREAD

**Issue by blueskyxi3** [youzan/vant#2594]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
不规范的 issue
