### ISSUE TITLE
vue spa图片预览点开后，再点浏览器或安卓虚拟返回键跳转其他页面，之前打开的图片预览模态框还在

### ISSUE THREAD

**Issue by lanzengjie** [youzan/vant#2595]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
vue spa图片预览点开后，再点浏览器或安卓虚拟返回键跳转其他页面，之前打开的图片预览模态框还在

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: chrome手机模式
 - Browser:  chrome
 - Vant Version: 1.3.8

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
组件不会监听路由事件，这种情况可以手动关闭
