### ISSUE TITLE
this.$notify is not a function

### ISSUE THREAD

**Issue by sufangyu** [youzan/vant#2597]
build 后的项目，提示 this.$notify is not a function，开发环境是正常运行的

"vue": "^2.5.2",
"vant": "^1.5.2",

![qq 20190123152344](https://user-images.githubusercontent.com/1852629/51589780-f5851700-1f22-11e9-84b9-77c3e763e4ca.png)

**Comment by Zenser** [comment]
能否看下你notify怎么注册的？

**Comment by sufangyu** [comment]
@Zenser ，就全局引用
```
import Vant from 'vant';
import 'vant/lib/index.css';
Vue.use(Vant);
```
