### ISSUE TITLE
Card 卡片的图片能不能提供斜角标的功能？

### ISSUE THREAD

**Issue by nnzbz** [youzan/vant#2598]
**What problem does this feature solve?**
Card 卡片的图片能不能提供斜角标的功能，也就是图片的右上角可放置一个斜角标，并可以标上自定义的两三个字

**Describe the solution you'd like**
在商品卡片中通常需要显示一些特定标签，原有图片的flag太弱且不好看，斜角标比较常用

**What does the proposed API look like?**
提供API的形式可以与已经实现的tag参数类似

**Comment by chenjiahan** [comment]
已在 1.6.0 版本支持
