### ISSUE TITLE
van-swipe貌似有bug，只加载第一张图比较快，后面的图是一直转圈，如果手动滑动就好了。

### ISSUE THREAD

**Issue by darling-shadow** [youzan/vant#2600]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
使用如下代码加载，默认第一张图会加载，后续的图都不会自动记载，一直在转圈。
<van-swipe :autoplay="6666">
      <van-swipe-item v-for="(item, index) in dataResultBanner" :key="index">
        <img class="swiperimg" v-lazy="item.image" @click="showArticle(item.h5_url)" />
      </van-swipe-item>
    </van-swipe>

**Screenshots**

**Environment**
 - Device: nexus 5
 - Browser: 内嵌h5
 - Vant Version: 
    "vant": "^1.5.0",
    "vant-css": "^1.3.10",

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by LetHergo** [comment]
> 去掉v-lazy，换成v-bind:src=就能加载了。是懒加载的问题么？

懒加载轮播是要手动滑才触发替换真实图片地址的操作

**Comment by chenjiahan** [comment]
后续会看一下这个问题

**Comment by icytailu** [comment]
是真的有bug，在详情页使用swipe，如果从列表页进入，只会显示第一张图片，其他的完全不显示

**Comment by chenjiahan** [comment]
已在 1.6.2 版本修复
