### ISSUE TITLE
framewok7 vue 框架项目使用带蒙层的van-popup组件的bug

### ISSUE THREAD

**Issue by ChanJianxun** [youzan/vant#2603]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
framewok7 vue 框架项目使用带蒙层的van-popup组件时，下次进来该组件的当前页面f7路由会被复制。导致点击顶部navbar返回按钮无法返回，还是在当前页面。注意，只有当设置overlay="true"使用蒙层才会有这个bug.设置为false,没有bug.

**Screenshots**
第一步:一开始进去页面的路由是["/","/production/analysis-optimization/complaint/order-list"]正常
![Image text](https://raw.githubusercontent.com/ChanJianxun/picture/master/rf_worker/vant-pupup-bug-pic1.jpg)  
第二步：点击日期控件，日期控件是由vant-pupup和vant-datetimepicker组成，
![Image text](https://raw.githubusercontent.com/ChanJianxun/picture/master/rf_worker/vant-pupup-bug-pic2.jpg)  
第三步：退出该页面再进来，发现当前页面的路由被复制了，["/","/production/analysis-optimization/complaint/order-list","/production/analysis-optimization/complaint/order-list"]，这时候再点击上面的返回，发现返回不了，原因是返回的页面的路由地址是,"/production/analysis-optimization/complaint/order-list"也就是当前页面，所以无法返回了。
![Image text](https://raw.githubusercontent.com/ChanJianxun/picture/master/rf_worker/vant-pupup-bug-pic3.jpg)  
第四步：将overlay="false",再一次测试，点击控件返回再进来再返回发现可以正常，路由信息也正常。
![Image text](https://raw.githubusercontent.com/ChanJianxun/picture/master/rf_worker/vant-pupup-bug-pic4.jpg)  
![Image text](https://raw.githubusercontent.com/ChanJianxun/picture/master/rf_worker/vant-pupup-bug-pic5.jpg)  

**Environment**
 - Device: 安卓
 - Browser: 谷歌浏览器
 - Vant Version: 1.5.6

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
不太清楚这个 framewok7 的路由问题和 Popup 有什么关联，如果可以在浏览器复现的话，麻烦提供一下 jsfiddle
