### ISSUE TITLE
van-swipe和van-cell一起使用时，van-cell的border在轮播动画滚动的时候，border消失或变粗

### ISSUE THREAD

**Issue by zoutong123** [youzan/vant#2606]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
van-swipe和van-cell一起使用时，van-cell的border在轮播动画滚动的时候，border消失或变粗

**Screenshots**
![image](https://user-images.githubusercontent.com/24762954/51720557-1798a980-2089-11e9-92b7-fff07e3026c2.png)

**Environment**
 - Device: 小米8SE
 - Browser: wx
 - Vant Version: 1.5.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
这个应该是浏览器渲染的问题，暂时没有办法解决
