### ISSUE TITLE
van-col里嵌套动态img问题

### ISSUE THREAD

**Issue by mantou-kk** [youzan/vant#261]
```
<li v-for="(item,index) in actList"  :key="index" @click="toActivity(item)">
      <van-row>
                    <van-col span="6">
                        <img :src="item.img" alt="">
                    </van-col>
                    <van-col  span="18" class="pr" >
                        ...............
                    </van-col>
     </van-row>
</li>
```

` <img :src="item.img" alt="">`这句放在`<van-col>`里面首次进入页面动态图片无法加载出来，
把这句放到<van-col>外面正常，这个框架问题有点多哈，而且更是一种不正常的问题。

**Comment by chenjiahan** [comment]
经测试 van-col 内图片可以正常加载，请在提 issue 前确认是否为自身代码的问题

测试地址：https://jsfiddle.net/64Lrkbp8/

<img width="1032" alt="2017-10-26 9 30 09" src="https://user-images.githubusercontent.com/7237365/32055624-f41e2e08-ba27-11e7-962b-1818b7ce68ff.png">

**Comment by mantou-kk** [comment]
@chenjiahan 
在PC上没有任何问题，打包后放到移动端上就出现这个问题；
我再检查下，不好意思，辛苦了！！！

**Comment by slpcode** [comment]
碰到了相同的问题，接口获取的数据，在van-col标签外面正常显示，但是放到里面就报错 @chenjiahan

**Comment by chenjiahan** [comment]
@slpcode 可以按照模板创建 issue
