### ISSUE TITLE
使用 van-tabs 时 标记标签 van-tag 会出现重影是什么问题?

### ISSUE THREAD

**Issue by Ri-Forever** [youzan/vant#2628]
使用 标签页 van-tabs 固定在顶部时, 标记标签 van-tag 会出现重影请问是什么原因导致的问题?
![image](https://user-images.githubusercontent.com/40415299/51782316-4eda8980-2161-11e9-8f72-dfbe08464df2.png)

**Comment by chenjiahan** [comment]
小程序的问题请到 vant-weapp 仓库下提问
