### ISSUE TITLE
Tabbar 标签栏 页面切换标签第二次点击才会激活的问题 

### ISSUE THREAD

**Issue by w316431585** [youzan/vant#2629]
**Describe the bug**
标签栏点击后页面切换但是标签没有激活，需要再次点击激活！
**Screenshots**
![qq](https://user-images.githubusercontent.com/46295716/51782369-f5268f00-2161-11e9-8810-ec0fd2fca4d0.jpg)

**Environment**
 - Device: win7
 - Browser: google
 - Vant Version: 1.5.6

**Comment by cyy-1314** [comment]
请问你的问题解决了吗，我也出现了这种问题

**Comment by chenjiahan** [comment]
重复 issue https://github.com/youzan/vant/issues/2544
