### ISSUE TITLE
vant-icon建议把字体放到本地，不用外链的方式

### ISSUE THREAD

**Issue by lyseky** [youzan/vant#263]
@font-face {
    font-family:vant-icon;
    src:url(https://b.yzcdn.cn/zanui/icon/vant-icon-6b495bd63f.eot);
    src:url(https://b.yzcdn.cn/zanui/icon/vant-icon-6b495bd63f.eot?#iefix) format('embedded-opentype'),url(https://b.yzcdn.cn/zanui/icon/vant-icon-6b495bd63f.woff2) format('woff2'),url(https://b.yzcdn.cn/zanui/icon/vant-icon-6b495bd63f.woff) format('woff'),url(https://b.yzcdn.cn/zanui/icon/vant-icon-6b495bd63f.ttf) format('truetype')
  }

**Comment by chenjiahan** [comment]
@lyseky 好的，我们考虑会换成更灵活的方式

**Comment by liangxiaoxin** [comment]
+1 应该把icon放在本地

**Comment by chuangbo** [comment]
比如 svg symbol? http://iconfont.cn/help/detail?helptype=code

**Comment by yurizhang** [comment]
+1  src: url(https://b.yzcdn.cn/zanui/icon/vant-icon-75c072da.ttf) format('truetype') 
这个一定要换成本地，不然我们使用你们的项目会增加一个外部的Http请求~~

**Comment by chenjiahan** [comment]
@lyseky @liangxiaoxin @yurizhang 已支持本地字体文件，详见文档，建议搭配 url-loader 使用 https://www.youzanyun.com/zanui/vant#/zh-CN/component/icon

**Comment by aetherwu** [comment]
> @lyseky @liangxiaoxin @yurizhang 已支持本地字体文件，详见文档，建议搭配 url-loader 使用 https://www.youzanyun.com/zanui/vant#/zh-CN/component/icon

该链接已失效。

**Comment by chenjiahan** [comment]
https://youzan.github.io/vant/#/zh-CN/icon
