### ISSUE TITLE
在切换路由,进入路由之前请求sku数据,使用sku组件,会强制返回之前的路由

### ISSUE THREAD

**Issue by zpedku** [youzan/vant#2637]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
`beforeRouteEnter(to, from, next) {
            //console.log(to.query)
            next(vm => {
                if (!to.query.id) {
                    vm.$router.push('/')
                    return false
                }
                vm.fetchGood(to.query.id)
                vm.fetchSku();// this.sku={XXXXX} 这里设置sku,就会出现强制跳转
            });
        }`
**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: PC开发测试
 - Browser: Chrome
 - Vant Version: 1.5.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
目测这个问题和 Sku 没有关联
