### ISSUE TITLE
表单类型是password时，能否增加显示明文功能

### ISSUE THREAD

**Issue by wangquanli** [youzan/vant#2642]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
表单类型是password时，能否增加显示明文功能。

**Describe the solution you'd like**
增加一个显示密码的按钮图标。

**What does the proposed API look like?**
无

**Comment by chenjiahan** [comment]
暂无计划支持，这个可以自己控制的
