### ISSUE TITLE
List 列表：数据加载完，finished-text="没有更多了"，没有任何显示

### ISSUE THREAD

**Issue by PillarStone** [youzan/vant#2645]
问题来源：List 列表
具体问题：完全按照官方文档中的代码演示进行的操作，为什么 finished-text="没有更多了" 这项不起任何作用？？？数据完全加载完，没有任何提示？？？
<van-list
  v-model="loading"
  :finished="finished"
  finished-text="没有更多了"
  @load="onLoad"
>
  <van-cell
    v-for="item in list"
    :key="item"
    :title="item"
  />
</van-list>
export default {
  data() {
    return {
      list: [],
      loading: false,
      finished: false
    };
  },

  methods: {
    onLoad() {
      // 异步更新数据
      setTimeout(() => {
        for (let i = 0; i < 10; i++) {
          this.list.push(this.list.length + 1);
        }
        // 加载状态结束
        this.loading = false;

        // 数据全部加载完成
        if (this.list.length >= 40) {
          this.finished = true;
        }
      }, 500);
    }
  }
}

**Comment by chenjiahan** [comment]
升级到最新版再试
