### ISSUE TITLE
swipe 里的img 加上懒加载后，最后一张图片会显示空白， 要手动滑动才会加载出来

### ISSUE THREAD

**Issue by Miilu** [youzan/vant#2647]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/
<van-swipe-item v-for="(image, index) in allData.slides" :key="index">
        <img v-lazy="image.image" class="swip-img">
</van-swipe-item>

**Comment by chenjiahan** [comment]
重复 issue
https://github.com/youzan/vant/issues/2600
