### ISSUE TITLE
List组件如何手动触发onLoad

### ISSUE THREAD

**Issue by ollieSk8** [youzan/vant#2657]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
List的onLoad函数会再页面初始化时候立即被调用，但再真实场景中有些需要等待其他请求返回完成后，再触发List 的onLoad函数，请问如果实现？
**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by ollieSk8** [comment]
List的onLoad函数会再页面初始化时候立即被调用，但再真实场景中有些需要等待其他请求返回完成后，再触发List 的onLoad函数，请问如果实现？

**Comment by chenjiahan** [comment]
可以手动调用 check，或者在 onLoad 里面等待另一个 Promise
