### ISSUE TITLE
swipe 当swipe item 尺寸宽度小于容器的宽度时候，不能很好的，无缝循环播放

### ISSUE THREAD

**Issue by maomaoispan** [youzan/vant#2658]
swipe 当swipe item 尺寸宽度小于容器的宽度时候，不能很好的，无缝循环播放

我的暂时解决办法，不是太好，时间仓促，暂时可以结局。
move: function move(_move, offset) {
    if (_move === void 0) {
      _move = 0;
    }
    if (offset === void 0) {
      offset = 0;
    }
    var delta = this.delta,
        active = this.active,
        count = this.count,
        swipes = this.swipes,
        trackSize = this.trackSize;
    var atFirst = active === 0;
    var atLast = active === count - 1;
    var outOfBounds = !this.loop && (atFirst && (offset > 0 || _move < 0) || atLast && (offset < 0 || _move > 0));

    if (outOfBounds || count <= 1) {
      return;
    }

  //   if (swipes[0]) {
  //     swipes[0].offset = atLast && (delta < 0 || _move > 0) ? trackSize : 0;
  //   }

  //   if (swipes[count - 1]) {
  //     swipes[count - 1].offset = atFirst && (delta > 0 || _move < 0) ? -trackSize : 0;
  //   }
  //   if (swipes[count - 2]) {
  //     swipes[count - 1].offset =  swipes[count - 1].offset
  //   }
    // 新增
  
    //最最后一个
    if(active === 0){
        for(let item of swipes){
            item.offset = 0
        }
    }
    if(active > count-3){
      if (swipes[0]) {
          swipes[0].offset = trackSize;
        }
        if (swipes[1]) {
          swipes[1].offset = trackSize;
        }
    }
    if (_move && active + _move >= -1 && active + _move <= count) {
      this.active += _move;
    }

    this.offset = offset - this.active * this.size;
  },

**Comment by chenjiahan** [comment]
这个问题确实存在，我们后续会优化下

**Comment by chenjiahan** [comment]
跟这个 issue 重复了，https://github.com/youzan/vant/issues/2214 先关闭咯
