### ISSUE TITLE
Cell的url 只支持 mode: history的形式

### ISSUE THREAD

**Issue by CoderLQChou** [youzan/vant#266]
当url 为hashbang的时候，url得写成/#/order 才能生效，这样很不方便，建议优化。

**Comment by cookfront** [comment]
嗯 目前是只提供URL的方式，我们会看下怎么比较好的支持vue-router的方式

**Comment by chenjiahan** [comment]
已在 0.10.5 中支持 vue-router 对象的方式进行跳转，详见 https://www.youzanyun.com/zanui/vant#/zh-CN/component/cell
