### ISSUE TITLE
[Feature Request] 是否可以给ImageView组件添加自定义指示器或者指定图片标题的功能

### ISSUE THREAD

**Issue by snowzijun** [youzan/vant#2660]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
希望可以自定义页码样式，如果可以的话，希望在图片切换的时候显示图片的标题
**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.
images:[{url:'',title:''}]
indicator: function(){}

**Comment by chenjiahan** [comment]
后续会考虑支持

**Comment by chenjiahan** [comment]
已在 1.6.15 版本支持组件调用和自定义指示器，应该可以满足需求
