### ISSUE TITLE
vant 中的NavBar fixed固定没有效果

### ISSUE THREAD

**Issue by guanjiangtao** [youzan/vant#2662]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
顶部的NarBar无法固定，使用了fixed也没有效果，一旦滑动之后，顶部也会跟着滑动了。

**Screenshots**
未滑动的状态
![image](https://user-images.githubusercontent.com/23498943/52111327-56f16800-263e-11e9-98c6-121f1bdc4b8c.png)
滑动的时候
![image](https://user-images.githubusercontent.com/23498943/52111351-6bcdfb80-263e-11e9-9af4-5e1d1bd51259.png)

**Environment**
 - Device:vue2 node8.4
 - Browser: chrome73.0.3679.0
 - Vant Version: 1.5.7

**Reproduce**

    页面代码
    <van-nav-bar :title="title" :fixed="isFixed">
      <van-icon name="search" slot="right" />
      <span slot="left">头像</span>
    </van-nav-bar>

    js代码
    data(){
      return{
        isFixed:true
      }
    },

**Comment by chenjiahan** [comment]
未复现这个问题，请提供 jsfiddle

**Comment by chenguzhen87** [comment]
遇到同样的问题

**Comment by chenguzhen87** [comment]
测试出现的原因，自定义主题，
![image](https://user-images.githubusercontent.com/28331609/92228222-191f8a00-eeda-11ea-9584-03be8692d8f0.png)
![image](https://user-images.githubusercontent.com/28331609/92228244-23418880-eeda-11ea-9c7a-1ac72d536d05.png)

**Comment by chenguzhen87** [comment]
修改为下面正常
![image](https://user-images.githubusercontent.com/28331609/92228906-386ae700-eedb-11ea-8c61-985fc6a0203c.png)
