### ISSUE TITLE
lib/style/var.less中rgba函数使用了字符串导致打包失败

### ISSUE THREAD

**Issue by hnty545** [youzan/vant#2667]
"vant": "^1.5.7",

lib/style/var.less中rgba函数使用了字符串导致打包失败

@toast-background-color: rgba(@text-color, 0.88);

Error evaluating function `rgba`: color functions take numbers as parameters

**Comment by chenjiahan** [comment]
这是 less 预发，建议看下你的 less 版本是不是太低了
