### ISSUE TITLE
popup组件2个属性没实现

### ISSUE THREAD

**Issue by hnty545** [youzan/vant#2668]
popup组件这2个属性没有实现，我看过源码，库版本是
"vant": "^1.5.7",

overlay-class | 自定义蒙层类名 | String | - | -
overlay-style | 自定义蒙层样式 | Object | - | -

**Comment by chenjiahan** [comment]
在 mixin 里

**Comment by hnty545** [comment]
我是新手，请教一下怎么用mixin呢，谢谢

**Comment by chenjiahan** [comment]
看 Vue 文档
