### ISSUE TITLE
van-tab组件用v-for动态生成，无法左右滑动？

### ISSUE THREAD

**Issue by kevinchung1984** [youzan/vant#267]
`<van-tabs>
    <van-tab :title="item.cat_name" v-for="item in offerGoodsCatList"></van-tab>
</van-tabs>`

因为每次请求后台接口，传来的商品类别都不一样，所以title不能写死，这里title如果不加 ":"，读不出来item.cat_name，但是有个问题：不能拖动，不能左右滑，求解。。。？？？

**Comment by cookfront** [comment]
1. 如果是要绑定变量是必须要加`:`或者通过`v-bind`的
2. 不能拖动的问题确实存在，我们会尽快修复

**Comment by kevinchung1984** [comment]
嗯，期待着你们尽快完善，3Q~

**Comment by kevinchung1984** [comment]
还有个问题，v-for生成的van-tab页面，返回上一页面，再进来时，会多生成一遍tab，相当于有了2套tabs，我检查了数据，时没有重复的，但标签页重复了，每次切出去再进入，会多一套tabs，求解？

**Comment by cookfront** [comment]
里面的`van-tab`都是你来配置有多少个的，这个你打印看下是不是数据重复插入了，和组件应该没关系

**Comment by lizhiyao** [comment]
同遇到根据接口返回数据渲染 tab 后，不能左右滑动，此时 `navBarStyle` 为 `undefiend`

**Comment by cookfront** [comment]
@kevinchung1984  @lizhiyao  你们说的问题已经在`0.10.6`版本修复

**Comment by LiHongyao** [comment]
Hello, 我加载了多个tab，标签栏在手机屏幕上不可以手指触摸拖动，这个有法解决么？我期望的是用户可以拖动标签栏，也可以点击，当有多个tab选项的时候，如果没有拖动的效果，用户从第一个tab点最后一个tab体验就特别不好。如果有大神知道解决方案，还望告知，感激不尽。

**Comment by kevinchung1026** [comment]
> Hello, 我加载了多个tab，标签栏在手机屏幕上不可以手指触摸拖动，这个有法解决么？我期望的是用户可以拖动标签栏，也可以点击，当有多个tab选项的时候，如果没有拖动的效果，用户从第一个tab点最后一个tab体验就特别不好。如果有大神知道解决方案，还望告知，感激不尽。

很早就支持滑动了，请仔细阅读文档和示例

**Comment by angelDL** [comment]
还是无法滑动

**Comment by EdisonVan** [comment]
还是无法滑动+1

**Comment by 877170760** [comment]
+1

**Comment by liugaol** [comment]
存在多个tab，同时绑定有点击事件，就无法实现拖动效果，如果去掉点击事件就可以拖动，这个可以解决一下吗

**Comment by liugaol** [comment]
ios端无法滑动
