### ISSUE TITLE
van-swipe组件添加了一个class就无法触摸滚动了

### ISSUE THREAD

**Issue by lyseky** [youzan/vant#270]
`<van-swipe` :autoplay="3000" class="border-1px-top">
      <van-swipe-item v-for="(image, index) in images" :key="index">
        <img v-lazy="image" />
      </van-swipe-item>
    </van-swipe>**

**Comment by lyseky** [comment]
<van-swipe :autoplay="3000" class="border-1px-top">
      <van-swipe-item v-for="(image, index) in images" :key="index">
        <img v-lazy="image" />
      </van-swipe-item>
    </van-swipe>
    <div class="section-box">

**Comment by chenjiahan** [comment]
@lyseky 我这测试没问题，是否是因为你添加了其他样式导致的？

**Comment by lyseky** [comment]
@chenjiahan 和懒加载一起用

**Comment by lyseky** [comment]
.border-1px-bottom{
  position: relative;
  border:none;
}
.border-1px-bottom:after{
  content: '';
  position: absolute;
  bottom: 0;
  left: 0;
  border-bottom: 1px solid #e7e7e7;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  width: 200%;
  height: 200%;
  -webkit-transform: scale(0.5);
  transform: scale(0.5);
  -webkit-transform-origin: left bottom;
  transform-origin: left bottom;
}
好像是我的这个样式影响的，失误。。。

**Comment by chenjiahan** [comment]
@lyseky 如果要加的 1px 边框的话，可以在 swipe 外面套一层 div，在 div 上添加边框
