### ISSUE TITLE
collapse 组件未按预期计算高度

### ISSUE THREAD

**Issue by iyjian** [youzan/vant#2701]
在给collapse组件内的div增加css -webkit-user-select: none; 后，第一次异步获取组件内内容后未正确计算高度。

**Screenshots**
![image](https://user-images.githubusercontent.com/466985/52397828-daed9900-2af1-11e9-8fb2-b45444039dee.png)

 - Device: MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
 - Browser: Chrome  71.0.3578.98（正式版本） （64 位）
 - Vant Version: 1.6.1

**Reproduce** 运行后点击上方折叠面板即可重现。（折叠面板有点看不清楚，见谅哦）
https://jsfiddle.net/njyoqe0c/1/

**Comment by chenjiahan** [comment]
确实加上 user-select 后出现了这个问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 1.6.2 版本修复
