### ISSUE TITLE
新版本中有点小问题

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#2703]
新版本的 函数式组件(Button) 里面无法附加其他属性
` <van-button btn success>按钮</van-button>`

编译之后将 btn 和 success属性都过滤了?

因为之前修改样式的时候是使用的属性的方式去编写的css 现在都不生效了!!!

**Comment by chenjiahan** [comment]
下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.6.2 版本修复
