### ISSUE TITLE
 ImagePreview 图片预览 多张图片时，点击中间的某一张，放大后仍然从第一张开始

### ISSUE THREAD

**Issue by mcuking** [youzan/vant#271]
### ImagePreview 图片预览 
问题1： 多张图片时，点击中间的某一张，放大后仍然从第一张开始轮播大图
问题2:  当某一张图点击放大时，有时点击图片时仍能够点到图片背后的元素，如果该元素有点击事件，也会响应
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
相关代码如下：
![image](https://user-images.githubusercontent.com/22924912/32214567-432bae68-be5a-11e7-9f8c-002b8c1a017f.png)

表现如下：
![image](https://user-images.githubusercontent.com/22924912/32214990-962edff8-be5b-11e7-95f0-6642138c2dc6.png)

**What is the expected behavior?**
希望能够点击放大后展示相应的图片
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
版本如下：
Vue: 2.2.2
Vant: 0.10.1
Browser: Chrome Version 61.0.3163.100 
OS: MacOS 10.13

**Comment by chenjiahan** [comment]
@mcuking 感谢反馈，我们会在下个版本支持自定义初始播放位置

**Comment by mcuking** [comment]
@chenjiahan 点透那个问题时有发生，你们可以查下原因

**Comment by chenjiahan** [comment]
@mcuking ok

**Comment by chenjiahan** [comment]
@mcuking ImagePreview 增加了 startPosition 参数，同时修复了点透问题，请升级到 vant@0.10.7 版本
