### ISSUE TITLE
van-swipe在iphone6s上不能手指滑动

### ISSUE THREAD

**Issue by OffTheWaller** [youzan/vant#2711]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
iphone6s上<van-swipe>不能用手指滑动。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device:  iphone6s
 - Browser: safari
 - Vant Version: 1.6.1

**Reproduce**

**Comment by chenjiahan** [comment]
未复现此问题，建议看下是不是其他原因导致的

**Comment by lichaokun** [comment]
我是在iphone7上有这个兼容问题 不能手动滑

**Comment by tercel2018** [comment]
ios 11.1  ，iPhone7 都有问题
