### ISSUE TITLE
imagePreview 使用过程中内部组件报错

### ISSUE THREAD

**Issue by xujiujiu** [youzan/vant#2718]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
局部使用imagePreview组件时，打了断点看是先加载了swipeItem后加载了swipe，导致swipeItem内部调用父组件失败，后控制台报错

**Screenshots**
![image](https://user-images.githubusercontent.com/25719101/52608065-ac860a00-2eb3-11e9-8936-fb5eddc60ef1.png)
![image](https://user-images.githubusercontent.com/25719101/52608100-c889ab80-2eb3-11e9-91f7-111f6eebbf77.png)
使用 如下：
![image](https://user-images.githubusercontent.com/25719101/52608226-2b7b4280-2eb4-11e9-884f-2280326cc782.png)

**Environment**
 - Device:  移动端浏览器
 - Browser: 谷歌
 - Vant Version: 1.6.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
能否提供一下 jsfiddle

**Comment by xujiujiu** [comment]
https://jsfiddle.net/Ln0o7u28/10/
同样的代码在项目里使用了一波，然而发现还是会报错，
![image](https://user-images.githubusercontent.com/25719101/52758560-bd658580-3043-11e9-9cbc-8b604b955b41.png)
现在怀疑是不是依赖的问题，之前因为vant更新太频繁，导致项目中使用时会在莫名的情况下出现一些错误，最后固定了版本1.2.1，最近因为业务需要更新了一下vant，更新完就不能使用了

**Comment by chenjiahan** [comment]
看了一下 jsfiddle 是正常的呢，建议升级版本试下
升级版本的时候请留意更新日志中的 breaking change

**Comment by 450611** [comment]
请问这个问题解决了么， 我也碰到了 @xujiujiu

**Comment by xujiujiu** [comment]
> 请问这个问题解决了么， 我也碰到了 @xujiujiu

2种解决方法：1、项目中使用的vant的版本固定为某个没有问题的版本且不允许其自动升级：如vant:'1.4.2'；2、先升级项目在本地的vant版本进行测试，需要遍历所有使用vant组件的地方

我选择了第一种方式

**Comment by xujiujiu** [comment]
> 请问这个问题解决了么， 我也碰到了 @xujiujiu

第二个方式还要更新一下node版本，亲测node10版本是没问题的
