### ISSUE TITLE
[Feature Request] Toast插入到指定父容器中

### ISSUE THREAD

**Issue by hehuangz** [youzan/vant#2719]
**What problem does this feature solve?**
我的需求是在页面的左半边的显示Toast提示和loading，position配置并不能满足我的需求，所以如何修改Toast插入到我的容器内而不是body

**Describe the solution you'd like**
希望可以通过options指定插入到哪个父容器中

**What does the proposed API look like?**
无

**Comment by chenjiahan** [comment]
下个版本会支持 getContainer 属性（类似 Popup），配合 className 属性应该可以实现你要的效果

**Comment by hehuangz** [comment]
> 下个版本会支持 getContainer 属性（类似 Popup），配合 className 属性应该可以实现你要的效果

感谢

**Comment by chenjiahan** [comment]
已在 1.6.3 版本支持

**Comment by hehuangz** [comment]
> 已在 1.6.3 版本支持

我已将我的vant版本更新到最新1.6.5，源码中并没有实际对getContainer的实现：
![image](https://user-images.githubusercontent.com/32256818/53014377-408f3d00-3483-11e9-8a7c-ae58b9fc331b.png)
对了，Toast的英文文档这个地方写错了：
![image](https://user-images.githubusercontent.com/32256818/53014287-0160ec00-3483-11e9-8da0-ebd6a478b0e2.png)

**Comment by chenjiahan** [comment]
@hehuangz 收到~ 文档会更新下
