### ISSUE TITLE
van-action-sheet 滚动

### ISSUE THREAD

**Issue by yellowbang** [youzan/vant#2721]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在 van-action-sheet 上scroll 的时候，后面的内容也一同scroll.

**Screenshots**
<img width="374" alt="van-action-sheet" src="https://user-images.githubusercontent.com/6099830/52619700-48cdf380-2e57-11e9-9c0a-42c4d345bf2a.png">

**Environment**
 - Device: All
 - Browser: 
 - Vant Version: 

**Reproduce**
1 van-action-sheet .
2 scroll, you will see the bottom layer is scrolled as well.

There should be a mask when van-action-sheet is pop up so that the bottom layer is not scrollable.

**Comment by chenjiahan** [comment]
请到 vant-weapp 仓库下提问喔
