### ISSUE TITLE
多台服务器编译结果不一致

### ISSUE THREAD

**Issue by weison** [youzan/vant#2726]
**Describe the bug**
前端实现负载均衡，将代码同时部署到两台服务器上，通过git抽取然后进行编译打包，但发现在保持的webpack版本,node版本,依赖包，业务代码一致的情况下，两台服务器编译出来的结果仍然不一致，导致访问页面时，会出来资源查找不出的情况。

**Screenshots**
![image](https://user-images.githubusercontent.com/4506417/52682226-ab1f1500-2f79-11e9-9e09-8e71c9266ee0.png)

![image](https://user-images.githubusercontent.com/4506417/52682005-e836d780-2f78-11e9-95fd-373708c1f0a4.png)
![image](https://user-images.githubusercontent.com/4506417/52682012-f4229980-2f78-11e9-9506-27649b7d4603.png)
![image](https://user-images.githubusercontent.com/4506417/52682039-0a305a00-2f79-11e9-8ca8-632bcec7f720.png)
![image](https://user-images.githubusercontent.com/4506417/52682047-13212b80-2f79-11e9-963b-120060f318c8.png)

**Environment**
 - Vant Version: vant@1.4.3
 - node Version: v8.1.2
 - webpack Version: v4.25.1

**Comment by chenjiahan** [comment]
与 vant 无关的问题
