### ISSUE TITLE
Popup组件内部滚动问题

### ISSUE THREAD

**Issue by ollieSk8** [youzan/vant#2727]
**What is the current behavior?**
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**
用了Popup组件做弹框，弹框里面内容很多，超出了显示范围，然后我设定父级元素设置好max高度,然后 overflow-y:scroll 虽然可以滚动，但报错 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
**What is the expected behavior?**
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
谢谢！

**Comment by chenjiahan** [comment]
麻烦提供一下 jsfiddle
