### ISSUE TITLE
不同版本修改了目录结构导致出现构建失败

### ISSUE THREAD

**Issue by cocody** [youzan/vant#2728]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
查看npm上version
1.3.10 手动引入样式
import 'vant/lib/vant-css/base.css';
import 'vant/lib/vant-css/button.css';

1.4.10 手动引入样式改为
import 'vant/lib/button/style';

小版本lock不住，导致线上打包错误

改动目录结构的情况竟然在readme中毫无体现，牛逼

还有这诡异的 npm version 版本号提交记录，牛逼

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/52694121-a96a4700-2fa3-11e9-8e60-bac9dccccb30.png)
