### ISSUE TITLE
使用steps步骤条出现最后一个离得很远的问题

### ISSUE THREAD

**Issue by yeahTibbers** [youzan/vant#273]
![image](https://user-images.githubusercontent.com/10751521/32256453-1a385d36-beea-11e7-8bd9-05180ff513e7.png)

![image](https://user-images.githubusercontent.com/10751521/32256471-362ce002-beea-11e7-9a68-2be7d8b3d733.png)

**Comment by chenjiahan** [comment]
@yeahTibbers 目前 Step 大于等于五项时确实存在样式问题，我们会在下个版本中进行修复
