### ISSUE TITLE
为什么npm上的版本号如此混乱？

### ISSUE THREAD

**Issue by cocody** [youzan/vant#2731]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

现在最新的npm提交是1.4.10
但是官方最新的版本是1.6.2

诡异的是

1.4.10 - 21 hours ago
1.5.8 - a day ago
1.4.9 - a day ago
1.6.2 - 3 days ago
1.6.1 - 8 days ago
1.6.0 - 9 days ago
1.5.7 - 20 days ago

why?

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
针对 1.4 和 1.5 发布过两个小的 bugfix 版本

**Comment by Airkro** [comment]
这是一种正常，正确的操作。并不是非要按顺序来的，建议学习 Semantic Versioning

**Comment by cocody** [comment]
> 这是一种正常，正确的操作。并不是非要按顺序来的，建议学习 Semantic Versioning

明显就是错误操作，你要对之前的版本进行 fix，应该避免对主版本号造成影响，可以这样 1.4.5-hotfix
看看 vue 的版本号概览就清楚了

**Comment by cocody** [comment]
我想是宣布996后，程序员都慌了神 :)

**Comment by Airkro** [comment]
1.4.10 修复的对象是 1.4.9。
1.5.8 修复的对象是 1.5.7。

难道有什么问题吗？这样的 patch 版本号哪里影响主版本号了。对于已经安装 1.6.x 的开发者没有影响好吗？

**Comment by cocody** [comment]
> 1.4.10 修复的对象是 1.4.9。
> 1.5.8 修复的对象是 1.5.7。
> 
> 难道有什么问题吗？这样的 patch 版本号哪里影响主版本号了。对于已经安装 1.6.x 的开发者没有影响好吗？

但对新安装的用户有影响，npm install vant 默认安装 1.4.10 导致文档上很多功能都对不上号
