### ISSUE TITLE
van-swipe-cell create a textNode and render "0" when prop left-width or right-width equals to zero

### ISSUE THREAD

**Issue by FrankCheungCN** [youzan/vant#2734]
**Describe the bug**
If leftWidth or rightWidth equals to zero, then I will get an "0" there. A textNode has been created and rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/22819074/52734096-50300100-2fff-11e9-90fc-a776ac33d7ac.png)

**Environment**
 - Device: all
 - Browser: all
 - Vant Version:  1.6.2

**Reproduce**
https://jsfiddle.net/yg0Lcber/4/

**Comment by qqcbqqkcel** [comment]
我也遇到了。

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复

**Comment by FrankCheungCN** [comment]
> 感谢反馈，下个版本会修复

感谢

**Comment by chenjiahan** [comment]
已在 1.6.3 版本修复
