### ISSUE TITLE
steps传入icon无效

### ISSUE THREAD

**Issue by zhaorx** [youzan/vant#2738]
steps传入icon无效,依然是默认的checked图标
 <van-steps direction="vertical" :active="stepsActive" active-color="#3C90FE" icon="question" iconClass="van-icon">
                <van-step v-for="(item, index) in stepsData" :key="index">
                    <p class="p4" v-text="item.text"></p>
                    <p class="p3" v-text="item.time"></p>
                </van-step>
            </van-steps>

**Comment by chenjiahan** [comment]
icon 属性是用来设置状态栏图标的喔，不是选中图标，目前选中图标还不支持修改
