### ISSUE TITLE
npm包 怎么又回退到1.4.10版本了啊?

### ISSUE THREAD

**Issue by youdianfan** [youzan/vant#2739]
请问一下,目前是这个版本最稳定吗? 之前发的1.5.+的版本有啥问题吗?

**Comment by chenjiahan** [comment]
前天在 1.4 基础上发了一个修复版本，所以 npm 显示 1.4.10 是最新版，晚上会解决这个问题

目前最新的是 1.6.2，是可以使用的

**Comment by youdianfan** [comment]
等待你的更新,谢谢答疑!  我这两天我一直在关注 前天看还是1.5.8 然后今天我在看变1.4了 好奇 问问

**Comment by chenjiahan** [comment]
客气哈，版本已恢复正常
