### ISSUE TITLE
van-collapse-item value slot  unusable

### ISSUE THREAD

**Issue by qqcbqqkcel** [youzan/vant#2743]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

van-collapse-item
value slot  unusable，报TypeError: n is not a function

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: PC
 - Browser: chrome
 - Vant Version: 1.6.4

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/qqcbqqkcel/0sdb1479/5/

**Comment by qqcbqqkcel** [comment]
删除 <template slot="value">我是slot value</template>就正常了

**Comment by qqcbqqkcel** [comment]
删除
```html
<template slot="value">我是slot value</template>
```
就正常了

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 1.6.5 版本修复
