### ISSUE TITLE
实在受不了了，还是在提下吧

### ISSUE THREAD

**Issue by shijunti19** [youzan/vant#2744]
从vant开发出来到现在一直存在，实在太影响我们开发者了
https://youzan.github.io/vant/#/zh-CN/style-guide
![image](https://user-images.githubusercontent.com/5392211/52836309-34267f80-3125-11e9-968f-9475443d8b49.png)

我点了右边滚动zhe正常，然后我要滚动左边的导航树，我必须鼠标点击下还可以顺畅的滚动，实在是头疼死我
http://element-cn.eleme.io/#/zh-CN/component/card
你看element的就无比顺畅，用着也丝滑！！！！！！！！！！！！
windows10

谷歌浏览器最新版本

我要的效果是，鼠标移动到左边滚动就可以马上响应

**Comment by hustlzp** [comment]
我这边没问题，移上去就可以滚动。

**Comment by shijunti19** [comment]
@hustlzp 你看eleme 右边即使超过了也不会滚动，但是vant的，需要右边滚动到了底部，左边才会滚动，干扰

**Comment by shijunti19** [comment]
我觉得一个是浏览器滚动，一个div滚动导致的，建议右边也是div，这样应该就不会干扰了，或者屏蔽下浏览器的滚动，只处罚div的

**Comment by chenjiahan** [comment]
测试了 mac 的 chrome 和 windows 的 chrome，未复现这个问题

**Comment by shijunti19** [comment]
@chenjiahan 这个根本不需要看什么浏览器啊！他要满足2点

**Comment by shijunti19** [comment]
@chenjiahan 你再看下是不是这样

**Comment by shijunti19** [comment]
element完全和他不一样的，但是我还是觉得element用起来好，鼠标在左边就应该滚动左边的

唉，

**Comment by shijunti19** [comment]
@chenjiahan 新版还是这样，唉，我描述的真的不懂吗，我想滚动左边菜单，必须右边滚动到底部，如果右边有10000px必须等他滚动底部，左边的菜单才开始滚动！非常不方便
