### ISSUE TITLE
Collapse 折叠面板 slot="value"不执行

### ISSUE THREAD

**Issue by aiyuchen** [youzan/vant#2746]
**Describe the bug**
Collapse组件中使用`slot="value"`就不执行了

**Environment**
 - Device: Mac OS本地开发
 - Browser: Chrome 72
 - Vant Version: 1.6.4 

**Reproduce**
https://jsfiddle.net/n2ksfejp/2/

**Comment by chenjiahan** [comment]
重复 issue
https://github.com/youzan/vant/issues/2743
