### ISSUE TITLE
Button组件增加一个to的api吧

### ISSUE THREAD

**Issue by aiyuchen** [youzan/vant#2747]
**What problem does this feature solve?**
① Button组件增加一个to的api吧，和cell link一样，Button也有link的
② Button组件增加一个文字组件吧，就是纯文字那种

**Comment by chenjiahan** [comment]
下个版本会支持 to 属性，文字组件暂无计划支持

**Comment by chenjiahan** [comment]
已在 1.6.5 版本支持
