### ISSUE TITLE
Panel 组件中无法使用v-slot

### ISSUE THREAD

**Issue by Airkro** [youzan/vant#2749]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
目前发现 Panel 组件中无法使用 v-slot

```vue
<van-panel title="title" class="mb-2">
  <template v-slot:header> header </template>
  <div>不可用</div>
  <template v-slot:footer> footer </template>
</van-panel>
```

**Environment**
 - Device: Windows 10
 - Browser: Chrome 72
 - Vant Version: 1.6.4

**Reproduce**
示例：<https://codesandbox.io/s/n4570ojqkp>

**Comment by chenjiahan** [comment]
当前版本确实存在这个问题，会在下个版本修复

**Comment by chenjiahan** [comment]
已在 1.6.5 版本修复
