### ISSUE TITLE
Vant 下载

### ISSUE THREAD

**Issue by 353170753** [youzan/vant#275]
### 为什么我npm run dev的时候总是提示我没有装vant。

**我在服务器上安装了vue和vant，版本也都匹配，但是为什么总说我没安装vant**

![image](https://user-images.githubusercontent.com/22886647/32269354-1237f2e2-bec0-11e7-8dba-2dac232adba8.png)

![image](https://user-images.githubusercontent.com/22886647/32269363-1e415d58-bec0-11e7-8cc1-8b9a41a6811a.png)

**Comment by chenjiahan** [comment]
@353170753 注意大小写，vant 是小写的
