### ISSUE TITLE
Tab组件在隐藏的时候改变index，会导致“底部条”不显示

### ISSUE THREAD

**Issue by kobezhu** [youzan/vant#2750]
Tab组件在隐藏的时候改变index，会导致“底部条”不显示。

**Describe the bug**
把Tab组件放在Popup弹出层中，打开弹出层，Tab组件显示状态是正常的。关闭弹出层，改变Tab绑定的`index`，再打开Popup弹出层，会发现表示激活标签的下横线消失了。
此时下横线的dom节点长这样：
```html
<div class="van-tabs__line" style="width: 0px; transform: translateX(0px);"></div>
```
目前我给Popup的opened事件上加上下面代码可以修复：
```js
// 事先给Tabs组件加ref="tab"
const tabs = this.$refs.tabs;
if (tabs && tabs.lineStyle.width === '0px') 
    tabs.setLine();
```
但感觉这样不稳妥。

**Environment**
 - Device: Windows 10
 - Browser: Chrome
 - Vant Version: 1.6.4

**Reproduce**
```html
<van-popup v-model="show">
    <van-tabs v-model="active">
      <van-tab title="标签 1">内容 1</van-tab>
      <van-tab title="标签 2">内容 2</van-tab>
    </van-tabs>
</van-popup>
```
```js
this.active = 0;
this.show = true; // 此时Tab正常
this.show = false;
this.active = 1;
this.show = true; // 此时Tab异常
```

**Comment by chenjiahan** [comment]
这个问题出现的原因是底部条渲染是需要获取 Tab 宽度来计算的，而隐藏时无法正确获取 Tab 宽度。
建议不要在 Popup 隐藏时修改 index，或者在 van-tabs 上添加 v-if="show"
