### ISSUE TITLE
SKU 组件中的ImagePreview图片，单击返回键时，后退的是图片后方的页面，而不是关闭图片遮罩层

### ISSUE THREAD

**Issue by lghshiyan** [youzan/vant#2751]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

**What problem does this feature solve?**
SKU 组件中的ImagePreview图片，单击返回键时，后退的是图片后方的页面，而不是关闭图片遮罩层

**Describe the solution you'd like**
第一次单击返回键，关闭图片遮罩

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
组件不会修改浏览器的历史记录，如果有这个需求，可以在打开的时候添加 hash

**Comment by im-zhangxi** [comment]
> IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.
> 
> **What problem does this feature solve?**
> SKU 组件中的ImagePreview图片，单击返回键时，后退的是图片后方的页面，而不是关闭图片遮罩层
> 
> **Describe the solution you'd like**
> 第一次单击返回键，关闭图片遮罩
> 
> **What does the proposed API look like?**
> Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

我也遇到这个问题了， 你最后是怎么解决的那?

**Comment by VenusPP** [comment]
> IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.
> 
> **What problem does this feature solve?**
> SKU 组件中的ImagePreview图片，单击返回键时，后退的是图片后方的页面，而不是关闭图片遮罩层
> 
> **Describe the solution you'd like**
> 第一次单击返回键，关闭图片遮罩
> 
> **What does the proposed API look like?**
> Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

尝试过在destroyed周期里写入ImagePreview({}).overlay = false;即可销毁图片，但此方法使用后会导致页面出现轻微卡顿，且再次点击图片时第一次会失效。建议用组件的方式去使用。

**Comment by VenusPP** [comment]
> > IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.
> > **What problem does this feature solve?**
> > SKU 组件中的ImagePreview图片，单击返回键时，后退的是图片后方的页面，而不是关闭图片遮罩层
> > **Describe the solution you'd like**
> > 第一次单击返回键，关闭图片遮罩
> > **What does the proposed API look like?**
> > Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.
> 
> 我也遇到这个问题了， 你最后是怎么解决的那?

尝试过在destroyed周期里写入ImagePreview({}).overlay = false;即可销毁图片，但此方法使用后会导致页面出现轻微卡顿，且再次点击图片时第一次会失效。建议用组件的方式去使用。

**Comment by im-zhangxi** [comment]
@VenusPP     组件的形式怎么解决那？   我现在将代码 更换成了 组件形式了。。  但是还是不知道怎么处理?  求代码！ 万分感谢。

**Comment by im-zhangxi** [comment]
> 组件不会修改浏览器的历史记录，如果有这个需求，可以在打开的时候添加 hash

hash  什么意思？？？  能具体点吗？

**Comment by VenusPP** [comment]
> @VenusPP 组件的形式怎么解决那？ 我现在将代码 更换成了 组件形式了。。 但是还是不知道怎么处理? 求代码！ 万分感谢。

<van-image-preview
                v-model="imageShow"
                :images="images"
                :maxZoom="2"
                :showIndex="false"
            >
 </van-image-preview>
就这样使用，点击图片的时候跟换imsges就行了，路由切换时组件自动销毁，不需要再去做单独处理。不晓得你是这样使用的不，如果还不行贴一份你的代码看看

**Comment by VenusPP** [comment]
<van-image-preview
                v-model="imageShow"
                :images="images"
                :lockScroll="false"
                :maxZoom="2"
                :showIndex="false"
            >
     </van-image-preview>

**Comment by VenusPP** [comment]
<van-image-preview
                v-model="imageShow"
                :images="images"
                :lockScroll="false"
                :maxZoom="2"
                :showIndex="false"
            >
            </van-image-preview>

**Comment by im-zhangxi** [comment]
<van-image-preview
					v-model="show"
					:loop="false"
					:show-indicators="true"
					:images="item.info.imgs"
					@change="onChange"
					:start-position="index"
			>
`  data(){
            return {
                show: false,
                index: 0,
            }
	    },
        methods: {
            previewImg: function (index) {
                this.index = index;
                this.show = true;
            },`
 这是我的实现逻辑。

**Comment by VenusPP** [comment]
<van-image-preview
      v-model="imageShow"
      :images="images"
      :lockScroll="false"
      :maxZoom="2"
      :showIndex="false"
>
</van-image-preview>

**Comment by VenusPP** [comment]
> <van-image-preview
> v-model="show"
> :loop="false"
> :show-indicators="true"
> :images="item.info.imgs"
> @change="onChange"
> :start-position="index"
> >
> ` data(){ return { show: false, index: 0, } }, methods: { previewImg: function (index) { this.index = index; this.show = true; },`
> 这是我的实现逻辑。
你是把组件放在v-for里的么？

**Comment by im-zhangxi** [comment]
@VenusPP  lockScroll  是什么意思啊？  我看文档上面没有这个参数啊？

**Comment by im-zhangxi** [comment]
@VenusPP   老哥  加下QQ吧   834688422

**Comment by VenusPP** [comment]
> @VenusPP lockScroll 是什么意思啊？ 我看文档上面没有这个参数啊？

不加这个lockScroll属性预览完图片关闭时页面会回到顶部，文档里没有，看Dialog组件有这个属性试着加上，没想到就行了。
