### ISSUE TITLE
cell 组件能否给一个api 修改 flex大小 如 flex:2  flex:3

### ISSUE THREAD

**Issue by ihamlet** [youzan/vant#2755]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
cell 添加title 单元格就会被分成两半，有时候自定义的title div可能是多层的 会挤出来造成溢出

**Describe the solution you'd like**
cell 组件能否给一个api 方便修改 flex大小 如 flex:2  flex:3

**What does the proposed API look like?**
cell 添加一个 flexbox   如 <cell :title='`<div>盒子模型</div>`' :value='number' :flexbox='[2,1]'></cell>

这个时候title  div盒子flex样式大小为 flex:2 value 的flex:1   💯

**Comment by ihamlet** [comment]
> IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.
> 
> 注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.
> 
> **What problem does this feature solve?**
> cell 添加title 单元格就会被分成两半，有时候自定义的title div可能是多层的 会挤出来造成溢出
> 
> **Describe the solution you'd like**
> cell 组件能否给一个api 方便修改 flex大小 如 flex:2 flex:3
> 
> **What does the proposed API look like?**
> cell 添加一个 flexbox 如
> `<cell :title='`<div>盒子模型</div>`' :value='[2,1]'></cell>`
> 这个时候title div盒子flex样式大小为 flex:2 value 的flex:1 💯

**Comment by chenjiahan** [comment]
建议直接用 title-class 和 value-class 进行覆盖样式喔

**Comment by ihamlet** [comment]
> 建议直接用 title-class 和 value-class 进行覆盖样式喔

我目前也是这么做的
