### ISSUE TITLE
按需引入好像新版一大堆错误吧

### ISSUE THREAD

**Issue by shijunti19** [youzan/vant#2760]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
```js
<van-dialog :v-model="true" title="你好" show-cancel-button></van-dialog>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5392211/52897371-94ddb700-320e-11e9-9e2d-13a1e4982b4a.png)

![image](https://user-images.githubusercontent.com/5392211/52897400-e71ed800-320e-11e9-99c6-86f734378000.png)

**Environment**
 - Device: windows10
 - Browser: 最新
 - Vant Version:  最新

**Reproduce**
按需引入的，然后发现dialog的title全部通通无效，js弹窗正常的，组件的时候都有问题

**Comment by chenjiahan** [comment]
未复现此问题，请提供 jsfiddle

**Comment by windldream** [comment]
我也遇到这个问题了 使用组件的方式调用Dialog就会出现这个问题 使用函数调用的方式则不会出现问题

**Comment by CHENPINGCAI** [comment]
我也遇到这个问题了  不知道什么原因

**Comment by shijunti19** [comment]
就是啊，按需引入，我无法在 jsfiddle重复啊，也不知道咋弄，他是vue-cli复现啊

**Comment by chenjiahan** [comment]
@shijunti19 确认下你是不是用 Vue.use 注册的组件
