### ISSUE TITLE
实际使用中textarea边框默认为无，和API上不一致

### ISSUE THREAD

**Issue by wqq1235** [youzan/vant#2763]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
API文档中对于van-field组件的说明，border默认为true，即默认显示边内框，实际使用时边框却是默认隐藏的，且无法更改

**Screenshots**
![wx20190216-210917](https://user-images.githubusercontent.com/46141826/52900354-cd41bd00-322f-11e9-92aa-e579ad9cebe3.png)
![image](https://user-images.githubusercontent.com/46141826/52900368-f2363000-322f-11e9-959c-f8b3084c1ee4.png)

**Environment**
 - Device: Macbook Air
 - Browser: Chrome
 - Vant Version: 1.6.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
内边框是通过伪元素实现的，当元素不是列表的最后一项时，才会渲染内边框
