### ISSUE TITLE
Dialog 弹出框修改confirmButtonText问题

### ISSUE THREAD

**Issue by mantou-kk** [youzan/vant#277]
1、A页面调Dialog弹出框修改confirmButtonText文案，切换到B页面调起Dialog 弹出框，B页面的Dialog弹出框confirmButtonText文案还是前一次的confirmButtonText文案。

2、Dialog弹出框，弹出来后，不关闭弹框，切换其它页面，弹框不会自动关闭，一直停留在页面。

**Comment by chenjiahan** [comment]
1. confirmButtonText 的问题会在下个版本修复
2. 切换路由的时候需要手动关闭弹框，组件本身不会包含这个逻辑

**Comment by YYQ8023** [comment]
2，如果确定切换路由的时候不需要Dialog，可以在根页面watch一下路由，检测到路由变化就全局关闭弹窗。

**Comment by chenjiahan** [comment]
@mantou-kk 按钮文字问题已在 0.10.6 中修复
