### ISSUE TITLE
[Field组件]报错

### ISSUE THREAD

**Issue by lszh001** [youzan/vant#2774]
更新到v1.6.3以后,[Field组件]报错.
![1](https://user-images.githubusercontent.com/45568614/52917230-f0e62f80-3323-11e9-8b35-e54779e8a8a4.png)
![2](https://user-images.githubusercontent.com/45568614/52917231-f5aae380-3323-11e9-892f-333cc5c0581b.png)
![3](https://user-images.githubusercontent.com/45568614/52917232-f93e6a80-3323-11e9-806f-bf538c989874.png)

**Comment by chenjiahan** [comment]
感谢反馈，此处有个类型错误，不影响实际使用，会在下个版本修复

**Comment by chenjiahan** [comment]
已在 1.6.6 版本修复
