### ISSUE TITLE
tab中， pane内容在查看源码是没有渲染的

### ISSUE THREAD

**Issue by zgbbiao** [youzan/vant#2775]
做seo的时候， 需要被爬虫抓取， 但是在右键查看源码中， 却发现tab中pane内的内容是没有提前渲染，无法再源码中找到

**Comment by chenjiahan** [comment]
目前 tab 的内容默认是延迟渲染的，下个版本我们增加一个开关来控制

**Comment by chenjiahan** [comment]
已在 1.6.6 版本支持
