### ISSUE TITLE
popup在ios下，某些特殊的触摸事件无效

### ISSUE THREAD

**Issue by lulouis** [youzan/vant#2777]
**Describe the bug**
在使用了popup之后，IOS混生开发的应用，原本UIWebView天生具备的Bounce拽空能力，在某些情况下会失效(当scrolltop为0时，无法拽取下拉)。由于Andriod的ActiveView由于没有Bounce拽空效果，所以Andriod不存在此问题。

**Screenshots**

![](https://marisfrolg.nos-eastchina1.126.net/ODSAPP%2F20190218081718225.png#width-full)

**Environment**
 iOS cordova混生开发

**Reproduce**
在任何苹果手机，使用popup弹出一个hello world即可重现。
在非popup内，拽取下拉是有效的

**个人怀疑问题所在**
在查看了vant的源码后，怀疑这块逻辑或许导致某些条件下的触摸事件无效
    onTouchMove(e) {
      this.touchMove(e);
      const direction = this.deltaY > 0 ? '10' : '01';
      const el = scrollUtils.getScrollEventTarget(e.target, this.$el);
      const { scrollHeight, offsetHeight, scrollTop } = el;
      let status = '11';

      /* istanbul ignore next */
      if (scrollTop === 0) {
        status = offsetHeight >= scrollHeight ? '00' : '01';
      } else if (scrollTop + offsetHeight >= scrollHeight) {
        status = '10';
      }

      /* istanbul ignore next */
      if (
        status !== '11' &&
        this.direction === 'vertical' &&
        !(parseInt(status, 2) & parseInt(direction, 2))
      ) {
        /* 怀疑这种条件下取消事件的不良影响 */
        e.preventDefault();
        e.stopPropagation();
      }
    },

**Comment by chenjiahan** [comment]
这个问题我们没有能力复现，你可以注释掉一些代码来排查下

**Comment by mqy1023** [comment]
我也遇到了类似的问题，popup中有输入框，输入完毕后点击关闭按钮不可用。解决方案：软键盘关闭后将页面返回顶部就可以了，可以参考我的https://blog.csdn.net/mqy1023/article/details/101448165，希望有用，谢谢
