### ISSUE TITLE
弹层ios拖拽效果

### ISSUE THREAD

**Issue by tjsome** [youzan/vant#2787]
Describe the bug
混生开发的应用,在使用了popup之后，IOS拖拽效果，弹层列表每次要向下滑动一下，IOS的拖拽效果就会出现（类似于下拉刷新效果），如果不下滑，IOS拖拽效果不会出现，在安卓上面没有这种拖拽效果，如何把IOS的这种拖拽效果解决

Screenshots

Environment
 Vant Version: 1.5.5

Reproduce

**Comment by tjsome** [comment]
类似于下拉回弹效果

**Comment by chenjiahan** [comment]
可以试下添加 @touchmove.prevent
