### ISSUE TITLE
PasswordInput 密码输入框  可设置为明文显示

### ISSUE THREAD

**Issue by skyzfdance** [youzan/vant#2793]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
建议 PasswordInput 组件 可以设置，输入的文本显示为明文，由用户自由控制，不强制替换为 · 符号，这东西还可以用来实现 短信验证码 的输入。

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 1.6.6 版本支持
