### ISSUE TITLE
picker组件change事件中，传入的values有个bug

### ISSUE THREAD

**Issue by aiyuchen** [youzan/vant#2804]
**Describe the bug**
如果第一列数据不变，那么values返回的数组是对的
如果滑动第一列，values返回的数据第一个值是对的，第二个值就是错的，除非再滑动一下

**Screenshots**
![ezgif-2-6aa0311198c6](https://user-images.githubusercontent.com/578141/53069542-54847e80-3517-11e9-8704-f7aad09a896d.gif)

**Environment**
 - Device: OSX 10.14.3
 - Browser:  chrome
 - Vant Version: 72

**Reproduce**
这段是直接copy官方文档，在不滑动第二列，只滑动第一列的时候，values数据就能看到错误了（需要手机模式才能滑动）
https://jsfiddle.net/aiyuchen/d1ymu6hs/8/

**Comment by chenjiahan** [comment]
这个不是 bug，onChange 触发的时候，第二列的数据并没有更新，所以 values 是按更新前的状态给出的。
第二列的数据是由使用者自行修改的，在修改后，调用 picker.getValues() 就可以拿到最新的 values
