### ISSUE TITLE
Cell 单元格事件 click中无法使用$event变量

### ISSUE THREAD

**Issue by VictorWuSH** [youzan/vant#2805]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Cell 单元格事件 click中无法使用$event变量

**Screenshots**
无

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
最新版本是支持的
