### ISSUE TITLE
Picker多列联动时候， title需要支持多个标题

### ISSUE THREAD

**Issue by chenhonghui** [youzan/vant#2809]
当多级联动的时候，每一级的选择有个标题，而van-picker的title只能设置一个，而且是居中，还不能设置富文本的，
```
this.title && <div class={['van-ellipsis', bem('title')]}>{this.title}</div>,
```
就是这里希望可以支持一下
```
this.title && {this.title.map((item, index) => (
  <div class={['van-ellipsis', bem('title')]}>{item}</div>
))}
```
![1550650843494](https://user-images.githubusercontent.com/24955676/53076802-8a336280-352b-11e9-9de7-f7ba2d80f2d5.jpg)

**Comment by chenjiahan** [comment]
下个版本会添加一个 Title 的插槽，用来自定义标题栏

**Comment by chenjiahan** [comment]
已在 1.6.6 版本支持
