### ISSUE TITLE
waterfall瀑布流拉到最底之后无限触发事件

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#281]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
按照waterfall文档使用。

部分代码如下：
```
<van-pull-refresh v-model="isLoading" v-waterfall-lower="loadMore" waterfall-disabled="disabled">
//子组件，一个v-for列表
    <list />
  </van-pull-refresh>
data(){
return {
   disabled:false,
  }
}

loadMore() {
      this.disabled = true;
      setTimeout(() => {
        Toast({message:'没有更多了~~',duration:1500});
        alert('1');
        this.disabled = false;
      }, 200);
    },
```
目前遇到的问题：当滑动界面到最底部的时候，会无限触发： 
```
Toast({message:'没有更多了~~',duration:1500});
alert('1');
```
如果在没有更多数据时，不写这句：`this.disabled = false;`，那么就不会一直触发，可是当往上滑再往下滑的时候，也不能触发loadMore了。

**更新**：如果loadMore方法是这样的：
```
loadMore() {
      this.disabled1 = true;
      setTimeout(() => {
        //调用时去添加数据
        this.$store.commit('index/add');
        alert('加载完毕');
        this.disabled1 = false;
      }, 200);
    },
```

此时如果添加的数据比较少，比如只有1条，那么`alert('加载完毕');`还是会再次触发，可能加载了1条之后，还是判定距离底部很近？

**Comment by YYQ8023** [comment]
目前也就是这样的一个问题：当往下滑，去获取数据发现已经全部加载完了，没有更多了，就会一直触发loadMore，实际上应该是触发一次，无论是否有最新数据，都不再触发，而是等到再次往下滑（而且是滑动一定距离），才再次触发，对比了mint-ui也似乎有类似问题。不知道是不是我代码的问题。

**Comment by YYQ8023** [comment]
有其它情况出现，我检查整理后再反馈~~~~~~

**Comment by Fixels** [comment]
请问这个问题你解决了吗?
