### ISSUE TITLE
picker和swiper在 ios(11.4) 微信中无法正常滑动

### ISSUE THREAD

**Issue by rason560** [youzan/vant#2812]
发现picker和swiper在 ios(11.4) 微信中无法正常滑动，但奇怪的是，同样是ios11.4 ，iphone7 的safari浏览器里可以滑动，iphone8的不行。尝试改样式也解决不了。
具体是picker只能触摸空白处才能滚动（如图选项上方空白处），若触碰可选项是滚动不了的。
swiper的话是完全不能滑动。

另外还试过vant官网demo情况也一样

**Screenshots**
<img src=http://thyrsi.com/t6/672/1550712907x2890208847.jpg width="350" />

**Environment**
 - Device: IPhone 7/8
 - Browser: 微信/safari
 - Vant Version: 1.6.5

**Comment by chenjiahan** [comment]
微信的问题，参见 https://github.com/youzan/vant/issues/2287
