### ISSUE TITLE
希望Lazyload 图片懒加载可以使用过滤器

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#2814]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
Lazyload 图片懒加载可以使用过滤器

**Describe the solution you'd like**
Lazyload 图片懒加载可以使用过滤器

**What does the proposed API look like?**
```
<img v-lazy="url | imgUrlFormat">
```

**Comment by chenjiahan** [comment]
Vant 中的 lazyload 是使用的 vue-lazyload 这个库，建议到对应的仓库看下
