### ISSUE TITLE
tabs+list的BUG 

### ISSUE THREAD

**Issue by lkoma** [youzan/vant#2817]
选项卡的切换，无论最终停留到那个tab下，滚动到最底部，所有的tab都会滚动到最底部。
问题：假如我第一个选项卡的list有100条数据，第二个选项卡list有1条数据，那么这两个选项卡的list的高度是相同的。
版本： 1.6.5
期望： 每一个选项卡的list的高度都是自己的真实高度。

**Comment by chenjiahan** [comment]
重复 issue
https://github.com/youzan/vant/issues/2387
