### ISSUE TITLE
一个checkbox组件来控制v-for循环出来的checkbox组件全选或非全选，如果首先点击这个控制全选的checkbox的话，再点击循环出来的checkbox的话会无效，change事件不触发

### ISSUE THREAD

**Issue by qiugu** [youzan/vant#2818]
**Describe the bug**
如题，点击全选checkbox的话，点击循环出来的checkbox则无效，change事件不触发

**Screenshots**
![default](https://user-images.githubusercontent.com/33192247/53150836-7ac81e00-35ec-11e9-8bf1-bc2409797264.png)

**Environment**
 - Device: 
 - Browser: 谷歌浏览器
 - Vant Version: 1.4.8

**Reproduce**

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle

**Comment by imsole** [comment]
我擦，这都能被关闭，van是有多差？
你们自己也不测试一下全选，好用不？

**Comment by chenjiahan** [comment]
@imsole 提 issue 时按照规范是最基本的要求，别永远指望别人来帮你

**Comment by imsole** [comment]
没指望你们哦，好些组件，真的是坑
