### ISSUE TITLE
popup的close,open,closed,opened事件无效

### ISSUE THREAD

**Issue by lyq027** [youzan/vant#2819]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
popup的close,open,closed,opened事件无效

**Screenshots**
 
**Environment**
版本1.6.5

**Reproduce**

**Comment by chenjiahan** [comment]
未复现这个问题，建议看下安装的 vant 版本是否正确，可以重装 node_modules 试下
