### ISSUE TITLE
Uploader 图片上传组件不支持某些机型（vivo）

### ISSUE THREAD

**Issue by shiwanjun1994** [youzan/vant#2820]
Uploader 图片上传组件在引入一些外部的js已完成了图片上传 裁切 压缩等功能 现在到了测试阶段 发现大部分安卓机型是正常的 但是到了vivo X7 这个机型就不行 老哥 怎么破？@作者 辛苦你了 希望老哥能够回复一下 谢谢！

**Comment by chenjiahan** [comment]
可以试下在这个机型上原生 input type="file" 是否能上传喔，如果也不行的话，就是手机的坑了

**Comment by jang-git** [comment]
遇到了同样的问题，vivo部分型号手机确实上传不了图片，原生的是可以的

**Comment by shiwanjun1994** [comment]
@chenjiahan 

<img width="730" alt="_20190225182317" src="https://user-images.githubusercontent.com/38515714/53330999-d7984100-392a-11e9-9be6-c5044437df5e.png">
内部他就自动生成了 type="file" 属性哦 这个项目就差这个就结尾了 希望老哥可以解答一下！谢谢！

**Comment by shiwanjun1994** [comment]
> 遇到了同样的问题，vivo部分型号手机确实上传不了图片，原生的是可以的

你是咋破的 整出来了没？请教互相学习一下 咱也可以加个微信 哈哈

**Comment by jang-git** [comment]
@shiwanjun1994  是在after-read 发生的问题，生成的input file 是没有问题的，我看到的情况是，用户选择了图片，但是没有执行 after-read 的方法

**Comment by jang-git** [comment]
@shiwanjun1994  我也是今天用户反映上传不了图片，才知道的，目前也没有解决，实在不行，就不用这个组件了，自己用原生写吧！

**Comment by shiwanjun1994** [comment]
> @shiwanjun1994 我也是今天用户反映上传不了图片，才知道的，目前也没有解决，实在不行，就不用这个组件了，自己用原生写吧！
留个联系方式咱俩交流一下吗 哈哈 18852575417 我的微信

**Comment by shiwanjun1994** [comment]
> @shiwanjun1994 我也是今天用户反映上传不了图片，才知道的，目前也没有解决，实在不行，就不用这个组件了，自己用原生写吧！
用原生写的话 拍照会出现三种选择 （录像、浏览图片、拍照）

**Comment by chenjiahan** [comment]
由于找不到复现该问题的机型，这个 issue 先关闭了哈，有合适的解决方案欢迎提 PR 或回复到此 issue

**Comment by slipkinem** [comment]
华为p30 pro，vant 1.6.10版本，微信内置浏览器无法上传。

**Comment by LiuxiboShuiShui** [comment]
华为手机都不行
