### ISSUE TITLE
在ios手机中，一个父容器中显示一个超过父容器大小的popup，为什么超出部分会被遮挡

### ISSUE THREAD

**Issue by hehuangz** [youzan/vant#2821]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
example：
![image](https://user-images.githubusercontent.com/32256818/53172045-533e7900-361f-11e9-9c29-84c66e5b94e6.png)

**Screenshots**
在pc和安卓上都显示正常，在ios上popup四周会被遮挡；
解决办法我知道，可以用get-container指定到外部去；
可是我想知道bug的原因，为什么在ios上会遮挡呢，可以指点一下吗，困惑ing

**Environment**
 - Device: ios
 - Browser:  webview 和 qq浏览器，其他浏览器未测
 - Vant Version:  1.6.5

**Reproduce**

**Comment by chenjiahan** [comment]
用 iOS 微信 webview 试了下是正常的，建议看下是不是有什么属性导致的

**Comment by zengcul** [comment]
遇到相同问题
