### ISSUE TITLE
在tab标签页中应用弹层问题

### ISSUE THREAD

**Issue by tjsome** [youzan/vant#2823]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

Describe the bug
在tab标签页List列表页中应用弹层，在弹层页滚动后，点击返回，回到tab标签页中List列表页中，发现tab标签页中List列表页不是一开始点击进去弹层的地方，tab标签页中List列表页跟着滚动了,List列表页同时也运用了下拉刷新

Screenshots
在tab标签页List列表页中应用弹层，在弹层页滚动后，点击返回，回到tab标签页中List列表页中，发现tab标签页中List列表页不是一开始点击进去弹层的地方，tab标签页中List列表页跟着滚动了,List列表页同时也运用了下拉刷新

nvironment
 - Device: 
 - Browser: 
 - Vant Version: 1.5.5

**Comment by chenjiahan** [comment]
不规范的 issue
