### ISSUE TITLE
Vant貌似没有原生的滚动(scroll)组件

### ISSUE THREAD

**Issue by liuyielang** [youzan/vant#2826]
**Vant貌似没有原生的滚动(scroll)组件**
默认overflow:auto的滚动很生涩,是不是要配合其它滚动插件才能实现平滑的滚动?

**有没有像mescroll那样的滚动组件**
文档中列出的组件,没找到可以实现内容层溢出后,平滑滚动的插件.

**Comment by chenjiahan** [comment]
暂无计划支持，平滑滚动可以添加下面的属性

```css
-webkit-overflow-scrolling: touch;
```
