### ISSUE TITLE
iOS无网络Toast图标不展示

### ISSUE THREAD

**Issue by gitfortress** [youzan/vant#2829]
Describe the bug
H5+原生的Vue项目，引用vant 中的Toast控件，在iOS手机上面，如果无网络，Toast图标不展示，有网络正常显示（iOS其他系统版本没有测过）。
android和pc没问题。正常展示。

**Environment**

* Device: iOS12、iphone x ，IOS 的UIWebView嵌入H5
* Browser: safari 、chrome
* Vant Version: 1.4.8

**Comment by gitfortress** [comment]
![1](https://user-images.githubusercontent.com/21328401/53294934-6756c600-382b-11e9-8da9-3955568e66ba.jpg)

**Comment by gitfortress** [comment]
有遇到过的 请指教，谢谢~~~~

**Comment by chenjiahan** [comment]
可以考虑使用本地图标，参考 Icon 文档

**Comment by gilnuy** [comment]
这就是解决办法？

**Comment by chenjiahan** [comment]
@gilnuy 建议稍微了解一下 iconfont 的原理再发言

**Comment by gilnuy** [comment]
ok，谢谢回复，请教下为何 只有iOS有这个问题，而android不会呢

**Comment by chenjiahan** [comment]
理论上无网络的情况都是不会展示的，android 可能是之前访问缓存了文件

**Comment by gitfortress** [comment]
android首次安装app不会出现iconfont的显示问题,不是缓存，只有ios会出现，能解决下吗? @chenjiahan
