### ISSUE TITLE
[Feature Request] 可否图片预览增加关闭按钮或者删除按钮？

### ISSUE THREAD

**Issue by achabuhecha** [youzan/vant#2832]
请问，可否针对图片预览功能，增加关闭按钮或者删除按钮及其对应的事件？这个在新建表单上传图片时，有很大的作用。这样的话，可以在预览时进行相应操作。具体可参照微信发朋友圈时，点击相机后，选择好图片，点击图片进行放大预览时的操作形式和流程。谢谢

**Comment by chenjiahan** [comment]
后续会支持 ImagePreview 通过组件的方式调用，同时添加一些 slot，应该能实现这样的效果

**Comment by chenjiahan** [comment]
已在 1.6.15 版本支持组件调用和顶部的插槽，可以试下
