### ISSUE TITLE
Actionsheet 上拉菜单 lazyRender 属性未生效

### ISSUE THREAD

**Issue by kingslayer0o0** [youzan/vant#2833]

**Comment by kingslayer0o0** [comment]
是这个class van-actionsheet 没有加 van-popup van-popup--bottom 吗？

**Comment by kingslayer0o0** [comment]
`<van-actionsheet v-model="typeState" :actions="typeActions" :lazy-render="lazyRender" @select="onSelectType" />`
我给原来的组件加了个 :lazy-render="lazyRender"   lazyRender为false.
在mounted里面加了
```
let actionsheet = document.getElementsByClassName("van-actionsheet");
      if(actionsheet.length!=0){
        for(let i in actionsheet){
          if(actionsheet[i].className=="van-actionsheet"){
            actionsheet[i].classList.add("van-popup");
            actionsheet[i].classList.add("van-popup--bottom");
          }
        }
      }
```
菜单效果是正常了，可是我不知道为什么会导致这样。
我看更新日志是2018-07-04 Actionsheet: 支持 lazy-render #1365。
为什么昨天突然变了效果呢

**Comment by chenjiahan** [comment]
最新版本 Actionsheet 的 lazyRender 确实没生效，会在下个版本修复

**Comment by chenjiahan** [comment]
已在 1.6.7 版本修复
