### ISSUE TITLE
字体资源文件，框架加载的内置图片能否本地化加载？

### ISSUE THREAD

**Issue by QiuCaYu** [youzan/vant#2836]
问题：
字体资源文件，框架加载的内置图片能否本地化加载？

情况：
当出现网络不通的情况，无法查看在线加载的字体图片资源以及图片；
当 https://img.yzcdn.cn 无法连接时，会造成项目加载icon,图片显示问题。

建议：
建议资源从下载的包中加载，而不是请求 https://img.yzcdn.cn/  该域名获取。

**Comment by chenjiahan** [comment]
参见文档里的使用本地图标部分
