### ISSUE TITLE
Button组件的loading大小被写死了

### ISSUE THREAD

**Issue by aiyuchen** [youzan/vant#2843]
**Describe the bug**
想手动调整loading的大小，发现无效，看了下，样式被绑在Dom上写死了，这样没办法修改的

**Screenshots**
<img width="971" alt="_deedf5f1-fb3d-40cf-ace9-bb4926c68433" src="https://user-images.githubusercontent.com/578141/53355710-8dcc4c80-3964-11e9-9ba7-db5157cf5372.png">

**Comment by chenjiahan** [comment]
已在 1.6.7 版本新增 loading-size 属性，支持自定义大小
