### ISSUE TITLE
cell组件clickable为false的时候不要触发click事件

### ISSUE THREAD

**Issue by gaoshijun1993** [youzan/vant#2844]
**What problem does this feature solve?**
使用场景如下: cell可点击时显示箭头,点击时弹出popup弹出层, 不可点击时不触发点击事件.因为目前没有disabled之类的选项可以使用, 因此只能使用clickable来控制.

**Describe the solution you'd like**
clickable为false的时候不处罚clickable事件, 或者新增一个disabled的选项. 总的来说,目前cell-group/cell作为表单/表单项来说,功能都还太弱

**What does the proposed API look like?**
```<van-cell :disabled="true"/>```

**Comment by chenjiahan** [comment]
暂时没计划修改 clickable 的行为（会造成 breaking change），而 disabled 属性目前看来没有很强的必要性，建议在 onClick 的回调函数里自己判断一下

**Comment by gaoshijun1993** [comment]
cell组件对应的是pc端的form-item, 因此使用disabled的场景还是很多的

**Comment by wxwlcp** [comment]
这个问题只能在popup里面做判断吗？

**Comment by gaoshijun1993** [comment]
目前是的...想通过自定义指令来实现,但是因为van-cell有个伪类子元素,然后行不通

**Comment by halldong** [comment]
没有disabled，也没有show，看上去就像是一个残缺的半成品。
