### ISSUE TITLE
多选框和单选框搭配单元格使用时，点击图标选择无效

### ISSUE THREAD

**Issue by zwdgit** [youzan/vant#2846]
![c6c62fe5-c076-42fa-974b-2daa86cd3a05](https://user-images.githubusercontent.com/28926324/53387441-cf3f1500-39c1-11e9-99f4-506ade118d2f.png)
如图，在多选框和单选框搭配单元格使用时，点击图标（圆圈），点击事件无效，单元格的点击事件正常，试了一下官网的案例：
`https://youzan.github.io/vant/#/zh-CN/checkbox`，结果也是无效，但是官网的单选框没问题，我在自己的项目中，单选和复选都失效

**Comment by zwdgit** [comment]
1.6.5版本发现的，升级到1.6.6版本问题依然存在

**Comment by chenjiahan** [comment]
感谢反馈，已在 1.6.7 版本修复，这个问题是在 Vue 2.6+ 出现的兼容问题

**Comment by huandie2012** [comment]
我的Vant版本是1.6.9，但是还是会有这个问题，并没有修复

**Comment by huandie2012** [comment]
我的Vant版本是1.6.9，但是还是会有这个问题，并没有修复

> 感谢反馈，已在 1.6.7 版本修复，这个问题是在 Vue 2.6+ 出现的兼容问题
