### ISSUE TITLE
swipe 组件BUG

### ISSUE THREAD

**Issue by 328921371** [youzan/vant#2847]
**Describe the bug**
Swipe 轮播 BUG,三张图片的时候,显示出现问题,第一张和第三张一起显示出来

**Screenshots**

![qq 20190226143605](https://user-images.githubusercontent.com/30221150/53392269-dec75980-39d3-11e9-8126-5cbb746a38ff.png)

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle

**Comment by Lzy8** [comment]
怎么解决的？？
