### ISSUE TITLE
Area 组件  BUG

### ISSUE THREAD

**Issue by skyzfdance** [youzan/vant#2848]
**Describe the bug**
Area 组件 
1.自行组装地区数据，code 补足6位，如果子级地区ID，有出现三位数的时候，将无法选择，例如 区级code: 180000，下级街道code：1810100，此时将无法选择此条数据
2. value 属性 为 Array 时，检查类型失败，为 String 时，子级选项无法显示。

**Screenshots**
暂无截图

**Environment**
 - Vant Version:  1.5.7

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
不是 bug，目前 Area code 的格式是按照国家标准格式来的，不支持三位数的格式

**Comment by skyzfdance** [comment]
不能支持 自定义吗？这个东西 不可能因为为了适配组件来改变原始数据结构吧

**Comment by chenjiahan** [comment]
暂时没计划支持自定义

**Comment by dothin** [comment]
> 不是 bug，目前 Area code 的格式是按照国家标准格式来的，不支持三位数的格式

2. value 属性 为 Array 时，检查类型失败，为 String 时，子级选项无法显示。
你好，这个回显问题怎么处理呢，为String是，子级选项没有回显
![image](https://user-images.githubusercontent.com/14859497/91293672-f2bb6980-e7ca-11ea-8596-9a42dff0220c.png)

**Comment by chenjiahan** [comment]
@dothin 提供 codesandbox 复现链接看下
