### ISSUE TITLE
从 1.6.5 升级到 1.6.6 后，ActionSheet 的 get-container 属性无效

### ISSUE THREAD

**Issue by hustlzp** [youzan/vant#2849]
**Describe the bug**

从 1.6.5 升级到 1.6.6 后，ActionSheet 的 get-container 无效。

代码：

```html
<van-actionsheet
      v-model="showActionSheet"
      :actions="actions"
      cancel-text="取消"
      get-container="body"
      @select="onSelect"
    />
```

**Screenshots**

v1.6.5：

![2019-02-26 4 13 10](https://user-images.githubusercontent.com/1180240/53397292-bf372d80-39e1-11e9-8a83-3886cb04e525.png)

v1.6.6：

![2019-02-26 4 12 24](https://user-images.githubusercontent.com/1180240/53397307-c78f6880-39e1-11e9-8a83-3a79b6687f50.png)

**Environment**
 - Device: Mac OS
 - Browser: Chrome
 - Vant Version: 1.6.6

**Reproduce**
See Screenshots above.

**Comment by chenjiahan** [comment]
感谢反馈，已在 1.6.7 版本修复
