### ISSUE TITLE
能否给轻提示加个遮罩层做loading的时候会用到

### ISSUE THREAD

**Issue by lyseky** [youzan/vant#285]
Toast.loading({
          forbidClick: false, // 禁用背景点击
          position: "middle",
          message: 'Loading'，
          layer:true //开启遮罩
        })

**Comment by chenjiahan** [comment]
@lyseky 感谢反馈，已加入开发计划

**Comment by lyseky** [comment]
@chenjiahan 还有loading貌似不能主动关闭

**Comment by chenjiahan** [comment]
已在 0.10.8 中添加 mask 选项
