### ISSUE TITLE
Tab 组件默认滚动定位失效

### ISSUE THREAD

**Issue by qhbhq** [youzan/vant#2851]
**Describe the bug**
Tab 组件默认滚动定位失效，1.5.1 正常，升级到 1.6.6 后不正常。
```html
<template>
  <van-tabs v-model="active">
    <van-tab v-for="index in 30"
             :key="index"
             :title="'标签 ' + index">
      内容 {{ index }}
    </van-tab>
  </van-tabs>
</template>

<script>
export default {
  data() {
    return {
      active: 25
    }
  }
}
</script>
```

**Screenshots**
![2019-02-26 4 24 33](https://user-images.githubusercontent.com/17266004/53397877-3b7e4080-39e3-11e9-92db-67c2a354a7e4.png)

**Environment**
 - Device: 
 - Browser:  
 - Vant Version: 1.6.6

**Reproduce**
https://jsfiddle.net/3crkqzut/

**Comment by chenjiahan** [comment]
感谢反馈，已在 1.6.7 版本修复
