### ISSUE TITLE
Collapse 折叠面板  加载数据时 展开面板元素被隐藏

### ISSUE THREAD

**Issue by xiongxiaobo** [youzan/vant#2852]
**Describe the bug**
Collapse 折叠面板  加载数据时 展开面板元素被隐藏,渲染出来的元素 class为van-collapse-item__wrapper,有行内样式height=0 导致元素被隐藏

**Screenshots**
![3](https://user-images.githubusercontent.com/19607608/53406716-8012d780-39f5-11e9-9dae-b2128a0d1b31.png)
![2](https://user-images.githubusercontent.com/19607608/53406719-8012d780-39f5-11e9-980c-2f80d40ff40c.png)
![1](https://user-images.githubusercontent.com/19607608/53406721-80ab6e00-39f5-11e9-8b94-92175f67ac6b.png)

**Environment**
 - Device: PC端
 - Browser: 谷歌
 - Vant Version: 1.6.5

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by xiongxiaobo** [comment]
急急急

**Comment by chenjiahan** [comment]
能否贴下代码，看下你的渲染步骤

**Comment by lghshiyan** [comment]
![222](https://user-images.githubusercontent.com/16697054/53458989-22bd6b80-3a73-11e9-9cdb-4b2a122a970c.png)
![111](https://user-images.githubusercontent.com/16697054/53458990-23560200-3a73-11e9-8558-40fec108e6bf.png)

**Comment by xiongxiaobo** [comment]
![4](https://user-images.githubusercontent.com/19607608/53459066-69ab6100-3a73-11e9-8724-c0e5f35ab25c.png)
这个是我加载列表的代码,点击折叠面板,请求的是某天的订单信息,如下图:
![5](https://user-images.githubusercontent.com/19607608/53459065-6912ca80-3a73-11e9-9a0e-bc23e05fcdfd.png)
如图,点击函数异步请求接口拿回数据,渲染列表未果.

**Comment by xiongxiaobo** [comment]
经测试,此bug在安卓机与PC端出现,需要点击两次后才正常展开面板显示数据;
而苹果手机上显示正常,只需点击一次.  
不知道是哪里的错?

**Comment by chenjiahan** [comment]
按照你的代码写了一个简化的 demo，没复现问题，能否给下 jsfiddle

**Comment by xiongxiaobo** [comment]
好的 已解决

**Comment by VictorWuSH** [comment]
遇到了同样的问题，组件内部面板内容高度为0；
面板内容并非异步加载，但是是通过复杂计算渲染的；
望尽早改进

**Comment by qq1311256696** [comment]
我这也有这个问题，在安卓手机上这个组件消失了，其他的都是好的

**Comment by xiongxiaobo** [comment]
![999](https://user-images.githubusercontent.com/19607608/54273690-62cb3500-45c1-11e9-927a-30be52a9b20b.png)
这个是我点击面板时,获取点击元素,然后找到面板内容高度.并手动设为1,就解决此问题了. @VictorWuSH

**Comment by xiongxiaobo** [comment]
![888](https://user-images.githubusercontent.com/19607608/54273923-d8370580-45c1-11e9-8a6c-9f8988404e1a.png)
$event可以获取点击的DOM元素,同时为了避免点击事件冒泡,可以给子元素设置点击事件@click.stop.

**Comment by VictorWuSH** [comment]
感谢你@xiongxiaobo提供的解决方案
我的临时解决方案是只要给当前slot能添加一个必占空间元素，即可解决这个问题
【图1】
![F19E966A-1FF4-4BB2-8C2D-EEECF3B882A4](https://user-images.githubusercontent.com/7811456/54333903-29e19d80-465f-11e9-9716-e179f8e3ebd2.png)

@chenjiahan  当slot中的元素（如我图1中的es-template-cell-group组件）本身所有的内容和空间都是通过计算渲染而成的话，会导致contentHeight计算为空
【图2】
![D59159D9-B720-4E25-ADE1-DCF8D6C8A168](https://user-images.githubusercontent.com/7811456/54334053-b0967a80-465f-11e9-94bc-581db80f4baf.png)

@chenjiahan 望早点解决这个问题

**Comment by chenjiahan** [comment]
下个版本会针对 contentHeight 获取不到的情况加一个兼容处理，应该能解决这个问题

**Comment by chenjiahan** [comment]
已在 1.6.11 版本增加兼容处理
