### ISSUE TITLE
部分组件上绑定ref无效，不能获取元素

### ISSUE THREAD

**Issue by liseipi** [youzan/vant#2858]
**部分组件上绑定ref无效，不能获取**
在部分组件上绑定ref无效，不能获取元素，例：van-icon

**Environment**
 - Vant Version: 1.6.6

**Comment by chenjiahan** [comment]
函数式组件目前不能通过 ref 获取元素，下个版本会支持，但是跟非函数式组件有一定区别
- 函数式组件通过 ref 拿到的是组件 DOM 节点
- 非函数式组件通过 ref 拿到的是组件实例

**Comment by chenjiahan** [comment]
已在 1.6.8 版本支持
