### ISSUE TITLE
PullRefresh组件在有内容部分区域下拉无法触发事件

### ISSUE THREAD

**Issue by cd249745647** [youzan/vant#2859]
**Describe the bug**
PullRefresh组件在有内容部分区域下拉无法触发事件

**Screenshots**
一个列表会全屏显示，需要解决触发下拉刷新

**Environment**
 - Device: ios
 - Browser: 微信浏览器
 - Vant Version: "vant": "^1.6.6"

**Reproduce**

![_20190227122950](https://user-images.githubusercontent.com/20336340/53467316-aafe3980-3a90-11e9-92a8-90be145a2398.png)

**Comment by chenjiahan** [comment]
PullRefresh 的整个内容区域都是可以下拉的，不太清楚你的问题是什么

**Comment by cd249745647** [comment]
iphone6s，在使用list的时候，因为自带弹性滚动，所以有时无法触发下拉刷新事件。

**Comment by huangjinlangzi** [comment]
无内容区域怎么触发下拉刷新，比如说只有一条数据
