### ISSUE TITLE
Cell center 属性不生效

### ISSUE THREAD

**Issue by liuzhaowei55** [youzan/vant#2861]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Cell center 属性不生效，定义`:center="true"` 没有效果

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
属性名是 centered，不是 center

**Comment by liuzhaowei55** [comment]
@chenjiahan 可能是我没有表达清楚问题，
这个是源代码：https://github.com/youzan/vant/blob/ef06d058e62c16439b50ff86edf70128a928715c/packages/cell/index.tsx#L81

这个是我的示例代码，并没有出现居中效果。
https://jsfiddle.net/liuzhaowei55/nj1x07ce/

**Comment by chenjiahan** [comment]
sorry 看错了
Cell 组件的 center 属性是『是否使内容垂直居中』，不是水平居中
