### ISSUE TITLE
tab 吸顶同时设置offset-top时，切换tab，建议内容是在tab下

### ISSUE THREAD

**Issue by lyq027** [youzan/vant#2862]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
tab 吸顶同时设置offset-top时，切换tab，第二个tab的内容顶部应该是在tab下。现在是会被tab遮住。内容希望要加上offset-top+tab高度的效果

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.6.5

**Comment by chenjiahan** [comment]
下个版本会优化这个问题

**Comment by chenjiahan** [comment]
已在 1.6.8 版本优化
