### ISSUE TITLE
tabs切换时不要自动滚动到顶部

### ISSUE THREAD

**Issue by iamwelk** [youzan/vant#2864]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
目前使用tab标签页的功能，在切换tab时，每次都会自动滚动到当前tab的顶部。

**Describe the solution you'd like**
希望在切换tab时，可以记录原来的tab页的滑动位置，当切换回来时不要自动滚动到顶部

**What does the proposed API look like?**
开放一个属性，可以保留滚动位置，类似vue的keep-alive功能

**Comment by chenjiahan** [comment]
滚动到顶部是相对通用的做法。考虑到滚动位置有可能随着页面内容发生变化，我们没有暂时计划在组件内记录滚动位置，建议在业务中自行实现这样的逻辑

**Comment by SheepYang1993** [comment]
所以自行实现，是要怎么实现？？？
