### ISSUE TITLE
SwipeCell 在ios11.3的微信7.0.3无法滑动

### ISSUE THREAD

**Issue by pencil2014** [youzan/vant#2868]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
建议看下是不是这个系统问题：https://developers.weixin.qq.com/community/develop/doc/00044ae90742f8c82fb78fcae56800
