### ISSUE TITLE
1.6.5 Field组件 label slot 无效

### ISSUE THREAD

**Issue by edwards19900128** [youzan/vant#2871]
1.5.6版本给flied添加label slot无效，只能使用left-icon替代同样的效果。。。
![image](https://user-images.githubusercontent.com/11594850/53562313-06f9b880-3b8c-11e9-9ed0-70970426ee18.png)
![image](https://user-images.githubusercontent.com/11594850/53562516-87b8b480-3b8c-11e9-9f30-66e9c2656cf8.png)
使用left-icon
![image](https://user-images.githubusercontent.com/11594850/53562564-9f903880-3b8c-11e9-84ac-22756a7511cb.png)
![image](https://user-images.githubusercontent.com/11594850/53562579-aa4acd80-3b8c-11e9-9013-59cfbec67aae.png)

**Environment**
 - Device: macOS
 - Browser: 微信Web开发工具
 - Vant Version: 1.6.5

**Comment by chenjiahan** [comment]
感谢反馈，会在下个版本修复

**Comment by chenjiahan** [comment]
已在 1.6.8 版本修复
