### ISSUE TITLE
按照官网的做法，我的list组件 会一直执行load方法 不知道怎么回事

### ISSUE THREAD

**Issue by gaibian** [youzan/vant#2877]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
建议看下 load 方法里有没有正确加载数据并渲染内容

**Comment by lollipop7** [comment]
请问这个问题怎么解决的？

**Comment by lollipop7** [comment]
知道了，见问题#2248
