### ISSUE TITLE
Icon图标线性风格和实底风格 对不上

### ISSUE THREAD

**Issue by imsole** [youzan/vant#2880]
**What problem does this feature solve?**
图标在切换的时候，有的线性图标找不到对应的实底图标，还得自己打包

**Describe the solution you'd like**
希望 线性风格 和 实底风格 能都对应起来

**What does the proposed API look like?**
希望 线性风格 和 实底风格 能都对应起来

**Comment by chenjiahan** [comment]
设计资源有限，会逐步优化图标
