### ISSUE TITLE
uploader 希望能支持大文件分片上传，或者能否提供一个思路

### ISSUE THREAD

**Issue by lyq027** [youzan/vant#2882]
**Describe the bug**
uploader 希望能支持大文件分片上传，或者能否提供一个思路。
业务需要将视频通过h5上传至后台
 

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.6.5

**Comment by chenjiahan** [comment]
uploader 目前只提供基本的文件上传，建议自行搜索下解决方案

**Comment by territoryfan** [comment]
用手机上微信打开 ，android 无法上传文件如word ，pdf,   accept="image/*,.pdf,.docx,.doc", chrome 模拟器可以

**Comment by zhichao8756** [comment]
> 用手机上微信打开 ，android 无法上传文件如word ，pdf, accept="image/*,.pdf,.docx,.doc", chrome 模拟器可以

我也碰到了同样的问题,请问有什么好的解决方案吗?

**Comment by jasonzhupeng** [comment]
> > 用手机上微信打开 ，android 无法上传文件如word ，pdf, accept="image/*,.pdf,.docx,.doc", chrome 模拟器可以
> 
> 我也碰到了同样的问题,请问有什么好的解决方案吗?

同样的问题，通过安卓手机微信打开H5，无法选择pdf之类的文件，只能打开相册。苹果手机和模拟器都可以，求解决方案
