### ISSUE TITLE
Tabbar 不应该设置默认选中

### ISSUE THREAD

**Issue by shijunti19** [youzan/vant#2883]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Tabbar 不应该设置默认第一个选中，很多应用的Tabbar 就是让用户选择的，没有所谓的选中那个，现在因为这个我的app好丑，第一个一直蓝色，我又不需要设置选中状态

**Screenshots**
![1](https://user-images.githubusercontent.com/5392211/53632619-69b48800-3c50-11e9-8ed6-0669e58abad6.jpg)

这个上一页，根本就不需要蓝色文字
**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
不需要重现，官方打开就是
不应该通过选中颜色来解决这事情，他就应该默认不选中，选中默认是当我们给每个标签赋值，如one，然后active="one"才是
或者默认从1才是，不应该0

**Comment by chenjiahan** [comment]
如果你不需要选中，传 -1 就可以
