### ISSUE TITLE
[Feature Request] Sku组件 initial-sku 初始化值商品数量参数

### ISSUE THREAD

**Issue by imsole** [youzan/vant#2884]
**What problem does this feature solve?**
我看了你们的demo：`vant/packages/sku/demo/index.vue`，设置初始化值的时候，没有num这个参数

**Describe the solution you'd like**
加上num的话，就可以更新sku的数量了

**What does the proposed API look like?**
希望可以加上num这个参数
```
{
  // 键：skuKeyStr（sku 组合列表中当前类目对应的 key 值）
  // 值：skuValueId（规格值 id）
  s1: '30349',
  s2: '1193',
  num : 2
}
```

**Comment by chenjiahan** [comment]
后续会看一下能否支持这个属性

**Comment by imsole** [comment]
好的，谢谢

**Comment by chenjiahan** [comment]
已在 1.6.11 版本支持
