### ISSUE TITLE
[Bug Report] Swipe 轮播change事件不能监听到所有的swipeItem的改变

### ISSUE THREAD

**Issue by an-error** [youzan/vant#2885]
**Describe the bug**
使用swiper事件不能监听到所有的swipeItem的改变，在swipe change事件中打印当前swipeItem的当前索引值，并且只在两个swipeItem间来回滑动，出现监听间断的情况是无序的（如下图，图中连续出现多个1的期间我一直在左右滑动，但是并没有监听到从第二个swipeItem滑倒第一个swipe Item的改变）
![default](https://user-images.githubusercontent.com/14577816/53633078-708fca80-3c51-11e9-88da-8fc56aa06b65.png)

**Screenshots**
我的使用情况：
Add screenshots to help explain your problem.
![default](https://user-images.githubusercontent.com/14577816/53633291-062b5a00-3c52-11e9-8f8a-e80f39bca9e4.png)
![default](https://user-images.githubusercontent.com/14577816/53633323-193e2a00-3c52-11e9-9397-9e4cb7cc1553.png)
**Environment**
 - Device: pc
 - Browser: chrome
 - Vant Version: 1.4.3

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
感谢反馈，连续左右来回滑动的时候，确实会出现 change 的值是同一个的情况。下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.6.9 版本修复
