### ISSUE TITLE
修改源码再打包yarn build:vant报错，无法打包

### ISSUE THREAD

**Issue by 18300618319** [youzan/vant#2893]
yarn build:vant
yarn run v1.13.0
$ cross-env NODE_ENV=production webpack --color --config build/webpack.build.js && cross-env NODE_ENV=production webpack -p --color --config build/webpack.build.js
Build completed in 0.752s

Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: c6fe6bfd4177aebc3041
Version: webpack 4.29.3
Time: 760ms
Built at: 2019-03-04 10:46:54

ERROR in Entry module not found: Error: Can't resolve './es/index.js' in 'E:\vant'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

上面执行yarn build:vant编译打包时报的错

**Comment by chenjiahan** [comment]
请执行 yarn buiild:lib

**Comment by plqin-xiaohao** [comment]
请问, `2.0.0-beta.0` 版本中 : `build:entry` ,  `build:changelog` ,  `build:lib` ,  `build:site` ,  分别代表什么含义, 没有相关文档与注释  @chenjiahan

**Comment by chenjiahan** [comment]
`build:entry` -> 生成 vant 入口文件
`build:changelog` -> 生成更新日志
`build:lib` -> 生成 vant 编译后的所有代码
`build:site` -> 构建文档网站并上传

**Comment by plqin-xiaohao** [comment]
> `build:entry` -> 生成 vant 入口文件
> `build:changelog` -> 生成更新日志
> `build:lib` -> 生成 vant 编译后的所有代码
> `build:site` -> 构建文档网站并上传

非常感谢!  !
