### ISSUE TITLE
radio 作用域插槽icon报错

### ISSUE THREAD

**Issue by zhangchao828** [youzan/vant#2894]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
<van-radio
              v-for="item of stateList"
              :name="item.state"
              :key="item.state"
            >
              {{ item.title }}
              <template v-slot="icon">
                <img class="state-radio-icon" />
              </template>
            </van-radio>

**Screenshots**
Add screenshots to help explain your problem.
TypeError: Cannot create property 'default' on boolean 'true'
**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.6.7
- vue Version:2.6.7

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by zhangchao828** [comment]
![_20190304112312](https://user-images.githubusercontent.com/15683846/53708789-01dc8800-3e70-11e9-9387-5a404fa30aeb.png)
![_20190304112423](https://user-images.githubusercontent.com/15683846/53708808-14ef5800-3e70-11e9-8ae7-00c72cf05ed0.png)

**Comment by chenjiahan** [comment]
这个写法没问题的，建议看下是不是有什么数据传错了，或者提供一些 jsfiddle

**Comment by webzhouyan** [comment]
一样的问题 我是checkbox 报错
