### ISSUE TITLE
Icon 图标 实底风格 question 显示不正确

### ISSUE THREAD

**Issue by tudanqz** [youzan/vant#2898]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
本该显示问号 现在显示一个黑圆圈
**Screenshots**
Add screenshots to help explain your problem.
实底
![qq 20190304164115](https://user-images.githubusercontent.com/24580345/53720963-f3589580-3e9c-11e9-97de-1c25e63456a3.png)
线框
![qq 20190304164145](https://user-images.githubusercontent.com/24580345/53720977-fc496700-3e9c-11e9-9a78-b0772eae31c4.png)
**Environment**
 - Device: win7
 - Browser: Chrome 72.0.3626.121
 - Vant Version: 1.6.7

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
看了一下是正常的，建议清除浏览器缓存试试
![image](https://user-images.githubusercontent.com/7237365/53733524-32e2aa00-3ebc-11e9-94f7-95be1a35e885.png)
