### ISSUE TITLE
checkbox在文本被点击的时候如何可以不切换

### ISSUE THREAD

**Issue by chxuzzu** [youzan/vant#2899]
![20190304172447](https://user-images.githubusercontent.com/30339707/53723441-c14a3200-3ea2-11e9-8269-1c9a31502922.png)
如图所示，我想自定义一个产品数量+1，-1的功能，在点击的时候，checkbox的状态一直在切换。
我尝试使用了label-disabled属性，结果变成了，在点击+1或-1时，打印数据可以看到num发生了变化，但是变化没有显示出来，点击圆圈之后，才可以看到num的变化。
在没有使用label-disabled的时候，我也尝试了用了禁止局部冒泡的方法，好像也没有效果。

**Comment by chenjiahan** [comment]
听你的描述应该是业务代码写的有问题，label-disabled 属性本身是可以使用的

**Comment by chxuzzu** [comment]
嗯，我再看看自己的代码先。


| |
朝旭
|
|
chxuzzu@163.com
|
签名由网易邮箱大师定制
在2019年3月4日 20:42，neverland<notifications@github.com> 写道：

听你的描述应该是业务代码写的有问题，label-disabled 属性本身是可以使用的
