### ISSUE TITLE
stepper 当外界修改数值时，不触发change事件。

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#290]
本来想描述一下业务场景的，但是想想说太多更容易把问题弄复杂，就是简单的：只有点击加或减按钮时，才会触发change事件，其实自己封装过类似组件，但是不知道怎么PR。。。只能希望官方改了。

**Comment by chenjiahan** [comment]
@YYQ8023 收到，近期修复

**Comment by YYQ8023** [comment]
谢谢~~其实在触发父组件 input或者是change事件之前，判断一下type是不是 plus或者是minus就可以，不知道我会不会想得太简单。 @chenjiahan

**Comment by chenjiahan** [comment]
@YYQ8023 差不多是这个思路，监听输入框的 input 事件，然后向外层抛出 change 事件就行

**Comment by chenjiahan** [comment]
@YYQ8023 下个版本会增加 plug 和 minus 事件，应该能满足你的需求
