### ISSUE TITLE
vue-cli3升级vant 1.6.7报错。

### ISSUE THREAD

**Issue by hello-lun** [youzan/vant#2900]
vue-cli3脚手架升级vant 1.6.7报如下错误。说是找不到对应的文件
![image](https://user-images.githubusercontent.com/34638158/53724353-a7115380-3ea4-11e9-9370-af45504565f4.png)

如上图，报错信息是说找不到相关依赖。 
但我在node_modules里是可以找到vant/packages/utils对应的文件的。但里面的文件都是.ts文件，不是传统的.js文件。
![image](https://user-images.githubusercontent.com/34638158/53724783-9f05e380-3ea5-11e9-82ba-a23f2309cedb.png)

所有有没有可能是我的脚手架没有解析ts的loader呢

**Comment by chenjiahan** [comment]
正常情况下不会引用到 packages 下面的文件的

**Comment by hello-lun** [comment]
那这种情况之前在vant1.4.4版本都是好好的。升级到1.6.7就出了这个问题。按道理来说是你们做了什么改动之类的吧？？？

**Comment by hello-lun** [comment]
我看了一下，我们的项目里需要调用create之类的方法去修改vant的组件。旧版本1.4.4是有上面的那些文件的。现在1.6.7却不见了。
![image](https://user-images.githubusercontent.com/34638158/53774069-edf45d00-3f27-11e9-9693-1b6c9ddb434d.png)

**Comment by chenjiahan** [comment]
这个用法是错误且不规范的，create 是内部方法，并没有标注在文档中，不是给用户使用的。建议不要这样用
