### ISSUE TITLE
使用babel-plugin-import怎么把vant添加到nuxt

### ISSUE THREAD

**Issue by fanwenfu** [youzan/vant#2901]
**按照官方推荐配置，会报下图错误**

nuxt.config.js

```
build: {
    babel: {
        plugins: [
             ['import', {
                    libraryName: 'vant',
                    libraryDirectory: 'es',
                    style: true
                }, 'vant']
            ]
        }
}
```
**Screenshots**

![image](https://user-images.githubusercontent.com/25945917/53725049-26ebed80-3ea6-11e9-9875-f7d29cb0fa55.png)

**而如果按照以下方法配置，则没问题，但是这种做法会导致引入全局index.less文件过大，并且无法定制主题**

nuxt.config.js

```
plugins: [
        "~/plugins/vant.js",
    ],
 babel: {
            "plugins": [
                ["component", {
                    "libraryName": "vant",
                    "libraryDirectory": "es",
                    style: false
                }]
            ]
        },
```
在plugins新建vant
```
import 'vant/lib/vant-css/index.less';
```

**Environment**
 - Device: mac
 - Browser: chrome
 - Vant Version: v1.6.7
 - nuxt Version: v2.4.5

**Comment by 750973092** [comment]
同问

**Comment by chenjiahan** [comment]
你好，这个问题建议到 nuxt 仓库提问，因为这个问题本质上是由 nuxt 和 babel-plugin-import 两者不适配导致的，vant 这边无法提供出解决方案

**Comment by sideFlower** [comment]
这个问题解决了吗 ？

**Comment by JonSnow-JY** [comment]
同问

**Comment by fanwenfu** [comment]
> 这个问题解决了吗 ？

没解决

**Comment by fanwenfu** [comment]
> 同问

并没解决

**Comment by gp0320** [comment]
可以解决：
参考我的文章：https://juejin.im/post/5e012778518825127f085da8
