### ISSUE TITLE
Vant 1.6.8 field组件label参数label-align="left"失效

### ISSUE THREAD

**Issue by SailorF** [youzan/vant#2903]
**Describe the bug**
Vant 1.6.8 field组件参数label-align="left"失效， center & right 参数显示正常

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/24806389/53790746-a808ba80-3f62-11e9-9d42-5668274fbe80.png)
![image](https://user-images.githubusercontent.com/24806389/53790796-c1116b80-3f62-11e9-8cbd-2ba7223be5aa.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version:  1.6.8

**Comment by chenjiahan** [comment]
text-aligen 的默认值就是 left，所以没有再去刻意声明 left 这个值，你的情况是在父级元素设置了 text-align: center 吗？

**Comment by SailorF** [comment]
@chenjiahan 还真是, vue-cli3新建的项目默认App.vue 的Style设置text-align:center; 哈哈
