### ISSUE TITLE
你们提供了国际化多语言切换功能，却在内部的提示文案只使用的中文

### ISSUE THREAD

**Issue by mmm1118** [youzan/vant#2904]
**为什么你们提供了国际化多语言切换功能，却在内部的提示文案只使用的中文？**
例如sku里的提示“请先选择商品规格”，如果我使用了英文或者繁体中文，他的提示仍然是简体中文，能否把提示文案都提供多语言选择。

**Comment by chenjiahan** [comment]
Sku 比较特殊，是不支持国际化的，暂无计划改动
