### ISSUE TITLE
vant组件在微软微信客户端里面打开是空白的

### ISSUE THREAD

**Issue by gaoxiaopang** [youzan/vant#2905]
**vant组件在微软微信客户端里面打开是空白的**
最近做的网页是在微信端打开的，但是用微软微信客户端打开页面就会是空白在，在苹果微信客户端打开是正常的，最近调试的时候发现vant在微软微信客户端打开不了，还有 ios9手机版本也是打不开
![image](https://user-images.githubusercontent.com/8706879/53792478-c670b500-3f66-11e9-9041-a5f4f9b955fd.png)

**Environment**
 - Device: 微软微信客户端 && ios9手机版本
 - Browser: 手机，电脑
 - Vant Version: 1.5.1

**Comment by chenjiahan** [comment]
Vant 本身是支持 iOS9 的，建议看下你的代码是否使用了低版本浏览器不支持的 ES6 特性，如果使用了，请引入对应的 polyfill （比如 Promise，Array.prototype.find 之类的语法）
