### ISSUE TITLE
radio组件在二维数组遍历了之后不能正常操作，change事件不能触发

### ISSUE THREAD

**Issue by AK47-dadada** [youzan/vant#2907]
数据结构:
[
 {
   a: 'Jimmy',
   b: [1, 2, 3],
   result: ''
 }
]

希望给个准确的答案

**Comment by chenjiahan** [comment]
不规范的 issue

**Comment by AK47-dadada** [comment]
晕，这个有赞，叼

**Comment by Funtience** [comment]
初始化的时候,先把所有radio绑定的值置空一下,比如说,你的radio绑定了数组中每一项的selectRes, 那么在初始化的时候,先遍历数组然后把selectRes=''
试一下吧,我刚刚这样操作成功了
