### ISSUE TITLE
iphone6s，因为系统自带弹性滑动，有时无法触发PullRefresh组件下拉刷新事件

### ISSUE THREAD

**Issue by cd249745647** [youzan/vant#2908]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
iphone6s，因为系统自带弹性滑动，有时无法触发PullRefresh组件下拉刷新事件，会自动将整个页面下拉。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: iphone6s
 - Browser: 手机端微信浏览器
 - Vant Version:"^1.6.6",

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.

**Comment by chenjiahan** [comment]
页面滚动到顶部的时候，会触发下拉刷新，不会触发弹性滑动。若页面滚动条不在顶部，则不会触发下拉刷新

**Comment by xiabuyuanyu** [comment]
我也遇到了，ios的手机就无法触发下拉刷新事件
