### ISSUE TITLE
checkbox搭配单元格组件使用案例中v-for少写index

### ISSUE THREAD

**Issue by webzhouyan** [youzan/vant#2910]
**Describe the bug**
checkbox搭配单元格组件使用案例中v-for少写index
应该是
`v-for="(item,index) in list"`
https://youzan.github.io/vant/#/zh-CN/checkbox
**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/18736886/53852016-7132b300-3ffb-11e9-945e-4b506b74edcc.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.6.8

**Reproduce**

**Comment by chenjiahan** [comment]
在 v-for 中，key 应该标识为唯一的 id，用 index 索引作为 key 实际上对性能是没有帮助的，它不能正确的标识一个元素。所以没有在文档里添加
