### ISSUE TITLE
在app页面嵌入页面，tab组件默认显示在最顶层

### ISSUE THREAD

**Issue by 15521054523** [youzan/vant#2911]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
在app嵌入webviwe的情况下，tab组件如果设置了sticky属性默认就会在顶层，而微信中不会
代码如下：
![image](https://user-images.githubusercontent.com/19297519/53854612-24ec7080-4005-11e9-93fa-086431a69b72.png)

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/19297519/53854579-fc647680-4004-11e9-8d57-01539af71b7d.png)

**Environment**
 - Device:  iphone 6s Plus
 - Browser:  IOS 12.0
 - Vant Version: app 嵌入得webview

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
你好，这个问题看起来是 webview 导致的，建议你从 webview 方面入手排查问题，或者尝试用 z-index 等方式来控制层级

**Comment by shiuai0304** [comment]
一样的问题Device: iphone 6s Plus
Browser: IOS 12.0
Vant Version: app 嵌入得webview
