### ISSUE TITLE
升级版本，丢了国际化

### ISSUE THREAD

**Issue by liseipi** [youzan/vant#2913]
**升级版本，丢了国际化**
升级版本，丢了国际化，组件里的文字变中文了

**Comment by chenjiahan** [comment]
> 考虑到可维护性和实际需求，Sku 组件不再支持 i18n 国际化 #1734

目前 Vant 中只有 Sku 组件不支持国际化，在 1.3.0 版本的更新日志中有说明，主要原因是 Sku 组件内有较多的文本内容，放在语言包中会给大部分用户带来不必要的代码量负担。

**Comment by hwt9520** [comment]
吼吼 那国际化怎么办……我添加了i18n报错……
import { Locale } from "vant";
import enUS from "vant/lib/locale/lang/en-US";
import zhHK from "vant/lib/locale/lang/zh-HK"
Locale.use("zh-HK", zhHK);

写了这个没事 添加变量怎么都报错……
变量在页面上怎么添加呢？
