### ISSUE TITLE
[Feature Request] Actionsheet 在select事件中建议增加一个index

### ISSUE THREAD

**Issue by lyq027** [youzan/vant#2915]
**Describe the bug**
Actionsheet 在select事件中建议增加一个index，有时候需要判断是哪一个Index,执行相应操作。现在只能用文本对比，比较不优雅

 

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.6.8

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会支持

**Comment by chenjiahan** [comment]
已在 1.6.9 版本支持
