### ISSUE TITLE
sku 组件 里的price默认会除100？ 

### ISSUE THREAD

**Issue by liseipi** [youzan/vant#2916]
在使用sku组件里，价格显示总是0.01元， 默认会除100？

**Comment by liseipi** [comment]
price() {
      if (this.selectedSkuComb) {
        return (this.selectedSkuComb.price / 100).toFixed(2);
      }
      // sku.price是一个格式化好的价格区间
      return this.sku.price;
    }

**Comment by chenjiahan** [comment]
是这样的，文档中有标注
```js
price: 100, // 价格（单位分）
```
