### ISSUE TITLE
希望新增类似 mint-ui 中的 indicator组件

### ISSUE THREAD

**Issue by bringbcd** [youzan/vant#2919]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by bringbcd** [comment]
希望新增类似 mint-ui 中的 indicator组件

**Comment by chenjiahan** [comment]
在 Vant 中可以使用 Toast 组件（loading 功能），功能是类似的
