### ISSUE TITLE
使用Uploader单图/多图上传时，建议统一返回类型

### ISSUE THREAD

**Issue by KatyChenLu** [youzan/vant#2920]
![2019-03-08 2 06 52](https://user-images.githubusercontent.com/15972824/54011066-1f7d5a80-41ac-11e9-891c-434eeae7b3b0.png)

如图，单张上传时返回类型为对象。多图上传时返回类型为对象组成的数组。建议统一一下都用数组表示。谢谢

**Comment by chenjiahan** [comment]
你好，这个改动会造成破坏性改动，所以暂时没有计划做修改，sorry

**Comment by KatyChenLu** [comment]
好的，暂时方法为判断范围值是否为数组。谢谢回答☺
