### ISSUE TITLE
小程序Area省市区组件选择问题

### ISSUE THREAD

**Issue by ym0922** [youzan/vant#2922]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
省市区三级联选，确定设置value，重新弹出选择，选中项是设置的value，这时滑动区列，然后点击取消，再重新弹出选择，此时的选中项，是点取消时选中的那一项，这是本身设计就这样的吗？我希望的是只要弹出选择，如果设置了value，默认选中就是设置的value项。

**Screenshots**
Add screenshots to help explain your problem.
![1](https://user-images.githubusercontent.com/16172921/54014602-42ae0700-41b8-11e9-97a3-5377bc331666.png)
![2](https://user-images.githubusercontent.com/16172921/54014603-43469d80-41b8-11e9-8e21-45d72ed0d769.png)
![3](https://user-images.githubusercontent.com/16172921/54014604-43469d80-41b8-11e9-9dce-5ae9309bf40b.png)
![4](https://user-images.githubusercontent.com/16172921/54014605-43df3400-41b8-11e9-98ec-1ae905b8e6e8.png)

**Environment**
 - Device:  真机红米5plus
 - Browser:  
 - Vant Version:  0.5.4

**Comment by chenjiahan** [comment]
请到小程序组件库的仓库下提问，谢谢
https://github.com/youzan/vant-weapp
