### ISSUE TITLE
Popup 弹出层 报错

### ISSUE THREAD

**Issue by imsole** [youzan/vant#2923]
**Describe the bug**
第一个页面有一个popup，绑定了v-model值，
第二个页面也有一个popup，也绑定了v-model值

当第一个页面的popup显示，并点击 popup里面的一个按钮，跳转到第二个页面，控制台会报错：

**Screenshots**
相关图片
第一个页面
<img width="979" alt="111" src="https://user-images.githubusercontent.com/3367457/54014994-586ffc00-41b9-11e9-830a-2ee4e5b89f9d.png">

第二个页面
<img width="1223" alt="2" src="https://user-images.githubusercontent.com/3367457/54015011-632a9100-41b9-11e9-8461-8217df83b30c.png">

报错代码猜测位置
<img width="539" alt="3" src="https://user-images.githubusercontent.com/3367457/54015564-07f99e00-41bb-11e9-9a40-ffa7d144a255.png">

**Environment**
 - Device: Mac
 - Browser: chrome
 - Vant Version:  版本 72.0.3626.121（正式版本） （64 位）

**Reproduce**
因为需要两个页面才能演示，jsfiddle不知道如何设置，我写了一个demo，你们可以看看
[https://gitee.com/sole/vantpopup](https://gitee.com/sole/vantpopup)

**Comment by chenjiahan** [comment]
感谢反馈，这两天会看一下

**Comment by chenjiahan** [comment]
上面的报错内容提示是不能直接修改传入的 props，出现原因是下面这行代码：

```html
<van-popup v-model="showpopup" position="bottom">
```

你在 v-model 中绑定了一个 props 而不是 data 导致的报错。
v-model 是不能绑定 props 的，如果要传入 props，可以采用下面的写法：

```html
<van-popup :value="showpopup" position="bottom" @input="$emit('input', $event)">
```

**Comment by imsole** [comment]
原来如此，感谢🙏
