### ISSUE TITLE
建议增加类型小程序imgae标签的裁剪、缩放功能

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#2925]
**What problem does this feature solve?**
图片要适配设计图尺寸, 要进行裁剪缩放, 现在的解决方案是在img标签外套一层div.

**Describe the solution you'd like**
[微信小程序 - image
](https://developers.weixin.qq.com/miniprogram/dev/component/image.html)

**What does the proposed API look like?**
`<van-image mode="..." src="..."></van-image>`

**Comment by chenjiahan** [comment]
暂无计划支持喔，在 H5 上用 background-image 和 background-size 可以很方便的实现类似的效果
