### ISSUE TITLE
[Bug Report] Card组件自定义origin-price的slot，只出现一个空标签

### ISSUE THREAD

**Issue by chenyscys** [youzan/vant#2926]
**Describe the bug**
在1.6.5版本，Card组件中，配置了origin-price的slot，无法显示，代码只有一个class为van-card__origin-price的空div，无自定义的内容，即一个空标签

**Environment**
 - Device: PC
 - Browser: 谷歌63+
 - Vant Version: 1.6.5

**Comment by chenjiahan** [comment]
感谢反馈，会在下个版本修复

**Comment by chenjiahan** [comment]
已在 1.6.9 版本修复
