### ISSUE TITLE
在Collapse 折叠面板中van-collapse-item插槽中使用 box-shadow属性时，当展开面板时会产生不必要的边框

### ISSUE THREAD

**Issue by djinzhong** [youzan/vant#2929]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by djinzhong** [comment]
![image](https://user-images.githubusercontent.com/36908895/54066150-6def2f80-4266-11e9-9a70-9803912a3502.png)
![image](https://user-images.githubusercontent.com/36908895/54066203-3c2a9880-4267-11e9-8cec-d39bd968ebf2.png)

`<template>
  <van-collapse v-model="activeNames"
                class="box">
    <van-collapse-item title="阴影边框Bug"
                       label="123"
                       value="123"
                       name="1">
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
    </van-collapse-item>
  </van-collapse>
</template>

<script>
import Vue from 'vue'
import { Collapse, CollapseItem } from 'vant'

Vue.use(Collapse).use(CollapseItem)
export default {
  data () {
    return {
      activeNames: ['1']
    }
  }
}
</script>

<style lang='stylus' scoped>
.box
  padding 1rem
.box-shadow
  margin 1rem 0
  padding 1rem
  box-shadow 0 0.25rem 1.25rem rgba(0, 0, 0, 0.3)
</style>
`

**Comment by djinzhong** [comment]
<template>
  <van-collapse v-model="activeNames"
                class="box">
    <van-collapse-item title="阴影边框Bug"
                       label="123"
                       value="123"
                       name="1">
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
    </van-collapse-item>
  </van-collapse>
</template>

<script>
import Vue from 'vue'
import { Collapse, CollapseItem } from 'vant'

Vue.use(Collapse).use(CollapseItem)
export default {
  data () {
    return {
      activeNames: ['1']
    }
  }
}
</script>

<style lang='stylus' scoped>
.box
  padding 1rem
.box-shadow
  margin 1rem 0
  padding 1rem
  box-shadow 0 0.25rem 1.25rem rgba(0, 0, 0, 0.3)
</style>

**Comment by djinzhong** [comment]
`<van-collapse v-model="activeNames"
                class="box">
    <van-collapse-item title="阴影边框Bug"
                       label="123"
                       value="123"
                       name="1">
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
    </van-collapse-item>
  </van-collapse>`
<style lang='stylus' scoped>
.box
  padding 1rem
.box-shadow
  margin 1rem 0
  padding 1rem
  box-shadow 0 0.25rem 1.25rem rgba(0, 0, 0, 0.3)
</style>

**Comment by djinzhong** [comment]
`<template>
  <van-collapse v-model="activeNames"
                class="box">
    <van-collapse-item title="阴影边框Bug"
                       label="123"
                       value="123"
                       name="1">
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
      <div class="box-shadow">
        我需要有阴影边框
      </div>
    </van-collapse-item>
  </van-collapse>
</template>`
`<script>
import Vue from 'vue'
import { Collapse, CollapseItem } from 'vant'

Vue.use(Collapse).use(CollapseItem)
export default {
  data () {
    return {
      activeNames: ['1']
    }
  }
}
</script>`
`<style lang='stylus' scoped>
.box
  padding 1rem
.box-shadow
  margin 1rem 0
  padding 1rem
  box-shadow 0 0.25rem 1.25rem rgba(0, 0, 0, 0.3)
</style>`

**Comment by chenjiahan** [comment]
目前 Collapse 默认是有外边框的，下个版本会增加一个属性来控制是否显示外边框

**Comment by chenjiahan** [comment]
已在 1.6.9 版本新增 border 属性，用于控制边框的展示

**Comment by djinzhong** [comment]
并没有解决
![collapse](https://user-images.githubusercontent.com/36908895/54258808-bed09200-459e-11e9-9f76-64ed949ce0f0.gif)

**Comment by djinzhong** [comment]
border属性压根就不起作用

**Comment by HighWarmModel** [comment]
label-class 添加类这个东西根本不是CollapseItem的API 是Collapse 的Api
