### ISSUE TITLE
按钮的禁止后，如何开启

### ISSUE THREAD

**Issue by Obacm** [youzan/vant#293]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@Obacm 请准确描述你的问题

**Comment by Obacm** [comment]
<van-button size="small" type="primary" v-bind:disabled="isDisabled" @click="send">发送</van-button>
这个是我目前实现的禁用按钮和开启的方式
