### ISSUE TITLE
日历选择组件

### ISSUE THREAD

**Issue by skyzfdance** [youzan/vant#2931]
**What problem does this feature solve?**
目前vant 是不存在 月历选择器的 ，多选日期，不是目前官方的 DatetimePicker 选择器

**Describe the solution you'd like**
举个例子，制作一个商城，需要选择配送时间，业务逻辑上 完全可以 制作一个 月历选择器 ，多选日期，我哪几天在家，每一天在家的 是哪几个时间段，时间段可以由 DatetimePicker HH:MM 格式处理，或者是自己做一个 picker 选择器。按照目前官方提供的组件，在不考虑第三方组件的情况下，如果我需要 2019/03/09 - 2019/03/12的日期，但是期间有一个  2019/03/10  不在家，不能配送。目前这种的业务 是完全没办法实现起来的。
 
**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
你好，日历组件确实在某些场景下是需要的，但是由于这个组件复杂度比较高，且我们目前开发资源有限，所以短期内应该不会去支持，抱歉

**Comment by chenjiahan** [comment]
你好，日历组件确实在某些场景下是需要的，但是由于这个组件复杂度比较高，且我们目前开发资源有限，所以短期内应该不会去支持，抱歉
