### ISSUE TITLE
picker 和 list

### ISSUE THREAD

**Issue by hwt9520** [youzan/vant#2932]
UI做的很好，点赞！
有两个功能想问
1：list出来cell，只能竖列一排，我想让图片刷两排，怎么搞？？
2：还有就是单列picker，第一项和上面有一大块空白，怎么去掉啊……不显示那么大空白行么？我拿来选择语言的

**Comment by chenjiahan** [comment]
第一个问题，List 只是一个容器，里面的内容随便你怎么布局都可以滴
第二个问题，UI 规范就是这样的，你可以修改 visible-item-count，或者把 defailtIndex 设置成第二项或第三项

**Comment by hwt9520** [comment]
我后来又查了，发现有waterfall……但是官方资料找不到介绍，是不是停用了？
第二个，我发现actionsheet也挺好，就是想做个语言切换功能
