### ISSUE TITLE
iphone6s 整合PullRefresh and List下拉刷新将这个页面下拉，无法触发下拉刷新事件

### ISSUE THREAD

**Issue by cd249745647** [youzan/vant#2937]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
iphone6s 预览官网list组件，下拉将整个页面下拉了，无法触发下拉刷新事件

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: ios10.3.3
 - Browser: 微信浏览器
 - Vant Version: "vant": "^1.6.6"

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/
![微信图片_20190311102719](https://user-images.githubusercontent.com/20336340/54096897-c9492b00-43e8-11e9-9afc-692f5a85dcab.png)

**Comment by chenjiahan** [comment]
请问页面是否已经完全滚动到顶部了，PullRefresh 只有在页面滚动到顶部的时候才会触发

**Comment by cd249745647** [comment]
> 请问页面是否已经完全滚动到顶部了，PullRefresh 只有在页面滚动到顶部的时候才会触发

是从顶部开始滚动的。

**Comment by chenjiahan** [comment]
试了下没有复现这个问题，能否提供一下复现视频呢

**Comment by cd249745647** [comment]
> 试了下没有复现这个问题，能否提供一下复现视频呢

![微信图片_20190311102719](https://user-images.githubusercontent.com/20336340/54801708-296e8580-4ca3-11e9-9bd7-bbaceeec5993.png)
好像无法上传视频，我放到服务器上了，地址
http://mem.s.weshaketv.com/1234567/chendong/zze/vant-list-bug.mp4 可以点进去查看复现视频

**Comment by chenjiahan** [comment]
目测大概率是这个问题：https://github.com/youzan/vant/issues/3015 可以参考下

**Comment by cd249745647** [comment]
> 目测大概率是这个问题：#3015 可以参考下
自己项目升级了版本号，确实好了。不过你们官网，我手机端访问，list组件下拉刷新还是有问题的，你们是否也需要同步更新？因为大多数开发者，都是需要先访问你们官网，看实际效果。

**Comment by chenjiahan** [comment]
会不会是有缓存呢

**Comment by cd249745647** [comment]
> 会不会是有缓存呢
清了缓存，还是时不时出现问题，不过概率比之前小多了。还有就是切换tab刷新数据的时候，window.scroll(0, 0)滚动到顶部，这个时候有时候也不会触发下拉刷新，而是需要将页面滑动一下，然后才会触发下拉刷新。不知道window.scroll(0, 0)算不算是滑动到浏览器顶部。
