### ISSUE TITLE
[Bug Report] datetime-picker 官方提供的Demo不可用

### ISSUE THREAD

**Issue by tenbamboo** [youzan/vant#2939]
**Describe the bug**
A clear description of what the bug is.

官方文档提供的Demo在IP6s中不可用，具体到picker滑动无效果，
且直接触发了body的滚动事件。
备注：请不要把问题指向 https://github.com/youzan/vant/issues/2287
我感觉不是一个问题

**Screenshots**
https://youzan.github.io/vant/#/zh-CN/datetime-picker

**Environment**
 - Device: 苹果6s （11.4）
 - Browser: 微信浏览器（7.0.3）
 - Vant Version: 跟随 官方Demo版本

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.

https://youzan.github.io/vant/#/zh-CN/datetime-picker

**Comment by chenjiahan** [comment]
汇总至 https://github.com/youzan/vant/issues/2943
