### ISSUE TITLE
[Bug Report] swipe 官方提供的Demo不可用

### ISSUE THREAD

**Issue by tenbamboo** [youzan/vant#2940]
**Describe the bug**
A clear description of what the bug is.

官方文档提供的Demo在IP6s中不可用，具体到swipe手势滑动无效果。

备注：请不要把问题指向 https://github.com/youzan/vant/issues/2287
   我感觉不是一个问题

**Screenshots**
https://youzan.github.io/vant/#/zh-CN/swipe

**Environment**
 - Device: 苹果6s （11.4）
 - Browser: 微信浏览器（7.0.3）
 - Vant Version: 跟随 官方Demo版本

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.

https://youzan.github.io/vant/#/zh-CN/swipe

**Comment by chenjiahan** [comment]
汇总至 https://github.com/youzan/vant/issues/2943
