### ISSUE TITLE
Stepper 步进器当加减按钮变灰时，双击屏幕放大，怎么解决该问题？ meta 已经设置

### ISSUE THREAD

**Issue by FateRui** [youzan/vant#2944]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
Stepper 禁止的时候，不会去处理双击缩放的逻辑呢，如果需要禁止的话，建议自行去网上搜索解决方案
