### ISSUE TITLE
Tab组件，tab1的4000px导致了tab2，活动内容高度也是4000px.

### ISSUE THREAD

**Issue by mangoyi** [youzan/vant#2945]
**Describe the bug**
tab1内容的高度影响了tab2内容的高度，导致tab2标签页存在滚动条.

**Screenshots**
![image](https://user-images.githubusercontent.com/24558539/54117270-51502480-442b-11e9-8450-f72b57aee364.png)
未完成tab
![image](https://user-images.githubusercontent.com/24558539/54117307-63ca5e00-442b-11e9-9cf5-017003b6639e.png)
改派中tab

**Environment**
 - Device: mobile
 - Browser: google， 小米内置浏览器
 - Vant Version: v1.6.7

希望提供一个好的解决方案
谢谢thanks.

**Comment by chenjiahan** [comment]
重复 issue，请移步 https://github.com/youzan/vant/issues/2387
