### ISSUE TITLE
uploader组件，第一次阻止之后，第二次传相同文件，不触发事件了

### ISSUE THREAD

**Issue by aiyuchen** [youzan/vant#2947]
**Describe the bug**
使用`uploader`组件，在监听第一次上传的时候阻止，返回false，第二次传相同文件的时候，不触发任何事件了
测试结果：firefox没问题，chrome、Safari都不行

**Screenshots**
![ezgif-2-0777a7bed13b](https://user-images.githubusercontent.com/578141/54125333-abf37b80-443f-11e9-9fde-418594cf049b.gif)

**Environment**
 - Device: OS X 10.14
 - Browser:  Chrome、safari、Firefox
 - Vant Version: 1.6.8

**Reproduce**
https://jsbin.com/liqezaj/edit?html,js,output

**Comment by aiyuchen** [comment]
升级到1.6.9问题还是存在的

**Comment by chenjiahan** [comment]
下个版本(1.6.10)会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.6.10 版本修复
