### ISSUE TITLE
picker能支持绑定对象并获取对象

### ISSUE THREAD

**Issue by JCqiu** [youzan/vant#2949]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
picker能支持绑定对象

**Describe the solution you'd like**
picker能支持绑定对象

value

**Comment by chenjiahan** [comment]
能用简单的代码描述一下么

**Comment by JCqiu** [comment]
@chenjiahan columns: [{name:'a',id:1,...},{name:'b',id:2,...},{name:'c',id:3,...},{name:'d',id:4,...}]
<van-picker :columns="columns" @change="onChange($event)" />
onChange($event){
console.log($event); //{name:'a',id:1,...}
}

**Comment by chenjiahan** [comment]
@JCqiu 暂无计划支持呢，用索引就可以拿到相应的对象的
