### ISSUE TITLE
开发模式下使用轮播组件懒加载方式 页面至少等待3S 才会正确显示swipe高度

### ISSUE THREAD

**Issue by CGerAJ** [youzan/vant#295]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
![wx20171109-100936](https://user-images.githubusercontent.com/20548301/32584993-d10d69f8-c4c0-11e7-8bd1-0a1ba3b151d0.png)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**
template: https://jsfiddle.net/n879nke7/  这个地址是React版本地址 is not vue.js
**What is the expected behavior?**

希望不影响体验

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
lastst   vue-cli
vue init youzan/vue-cli-template-vant myRrojectName

**Comment by chenjiahan** [comment]
@CGerAJ 你可以指定图片的初始高度

**Comment by lyseky** [comment]
我也出现这种情况，我加了css才解决
.van-swipe-item {
    display: table-cell;
}
.van-swipe-item img {
    max-height: 100%;
    max-width: 100%;
    margin: auto;
    display: block;
}
