### ISSUE TITLE
field 组件 right-icon-slot 无法覆盖 默认 right-icon

### ISSUE THREAD

**Issue by FrankCheungCN** [youzan/vant#2952]
**Describe the bug**

field 组件添加 is-link 属性后，使用 right-icon-slot 无法覆盖默认的 right-icon

**Screenshots**

![image](https://user-images.githubusercontent.com/22819074/54170191-a4b88600-44b0-11e9-8a48-37e546d57809.png)

![image](https://user-images.githubusercontent.com/22819074/54170213-bd28a080-44b0-11e9-8670-1ee2d4701b7f.png)

**Environment**
 - Vant Version:  1.6.8

**Comment by chenjiahan** [comment]
由于内部实现的原因，is-link 生成的图标不属于 right-icon，如果你不需要的话，直接把 is-link 设置成 false 就可以
