### ISSUE TITLE
List组件没有内容时，会无限刷新@load事件

### ISSUE THREAD

**Issue by mangoyi** [youzan/vant#2954]
**Describe the bug**
List 组件中没有获取到内容时，@load事件会无限触发

**Screenshots**
![image](https://user-images.githubusercontent.com/24558539/54182749-5077cb00-44dd-11e9-8909-517397261585.png)
![image](https://user-images.githubusercontent.com/24558539/54182798-71402080-44dd-11e9-9fb7-ee0e1560c57d.png)
结果就是如下图，会无限刷新@load事件。
![image](https://user-images.githubusercontent.com/24558539/54182831-87e67780-44dd-11e9-9ad9-a4cc0960903b.png)

麻烦了，谢谢。

**Environment**
 - Browser: google
 - Vant Version: 1.6.7

**Comment by chenjiahan** [comment]
没有内容的情况下，把 finished 设置成 true，List 就不会再触发 load 事件
