### ISSUE TITLE
van-cell 组件添加 label slot

### ISSUE THREAD

**Issue by HellsingMatt** [youzan/vant#2955]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
当前 van-cell 组件的 label 只能实现一行纯文本内容，添加 label slot 后可以实现 icon + text，以及多行内容

**Describe the solution you'd like**
为 van-cell 组件添加 label slot

**What does the proposed API look like?**
`<van-cell title="标题" value="内容" is-link>
  <template slot="label">
    <div> {{ 内容摘要 }} </div>
    <van-icon name="clock-o" />
    <div> {{ 提交时间 }} </div>
  </template>
</van-cell>`

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 1.6.10 版本支持
