### ISSUE TITLE
安卓环境下百度app弹窗popup出错

### ISSUE THREAD

**Issue by gongzhibin** [youzan/vant#2957]
**Describe the bug**
安卓环境下百度app弹窗popup不显示内容

**Screenshots**
![微信图片_20190312201535](https://user-images.githubusercontent.com/4123433/54199340-9f385b80-4503-11e9-8269-82fa179b7706.png)

**Environment**
 - Device: 小米8
 - Browser: 百度app
 - Vant Version: 1.4.8

**Reproduce**
安卓环境内下载百度app打开https://youzan.github.io/vant/#/zh-CN/dialog 点击第一个弹窗进行查看

**Comment by chenjiahan** [comment]
能否提供一下报错信息

**Comment by chenjiahan** [comment]
你好，看了一下这个问题是百度浏览器的 bug，暂时没找到在组件内兼容的方法，但是在弹窗内容前后加几个空格可以解决这个问题

```html
<!-- 下面的写法无法渲染 -->
<van-popup>内容</van-popup>

<!-- 下面的写法正常渲染 -->
<van-popup>
  内容
</van-popup>
```
