### ISSUE TITLE
可否新增时间区间选择组件？

### ISSUE THREAD

**Issue by lvlingjie** [youzan/vant#2958]
目前有个需求是选一个时间段，这个时间段内可以被抢单
类似于这样，点击弹出 开始的年月日时分--结束的年月日时分
![image](https://user-images.githubusercontent.com/48229461/54211344-1974da00-451c-11e9-9ad6-9e4ba01f6992.png)

**Comment by chenjiahan** [comment]
暂无计划支持呢
