### ISSUE TITLE
获取不到折叠面板的items，TypeError: Cannot read property 'items' of null

### ISSUE THREAD

**Issue by shenxianweilai** [youzan/vant#2959]
用的vuecli3.0,

![图片](https://user-images.githubusercontent.com/19275929/54247241-2ec92300-4573-11e9-9963-194e3a306e32.png)

**Comment by chenjiahan** [comment]
请确认一下是否正确注册了 van-collapse 组件，如果注册了，麻烦提供一下复现问题的 jsfiddle

**Comment by shenxianweilai** [comment]
> 
> 
> 请确认一下是否正确注册了 van-collapse 组件，如果注册了，麻烦提供一下复现问题的 jsfiddle
注册了。
在jsfiddle是正常的，不用 vuecli 时也是正常的。
![图片](https://user-images.githubusercontent.com/19275929/54325837-276f4b80-463f-11e9-8b20-4fde8307e9c5.png)

我用是vuecli3.0，浏览器谷歌，cdn方式引入vant。
页面中van-collapse是有的，van-collapse-item没有
![图片](https://user-images.githubusercontent.com/19275929/54326149-75d11a00-4640-11e9-8397-0664ed236431.png)

**Comment by chenjiahan** [comment]
> 在jsfiddle是正常的，不用 vuecli 时也是正常的
这样看来不是 vant 的问题，建议自行排查下呢
