### ISSUE TITLE
van-collapse-item 插槽中使用box-shadow属性时会产生Bug

### ISSUE THREAD

**Issue by djinzhong** [youzan/vant#2960]
![image](https://user-images.githubusercontent.com/36908895/54259004-50d89a80-459f-11e9-9f39-4e3c14e22a1d.png)
![collapse](https://user-images.githubusercontent.com/36908895/54259079-89787400-459f-11e9-8b4b-8c143209cc29.gif)

**Comment by djinzhong** [comment]
vant 使用的是 1.6.9版本

**Comment by chenjiahan** [comment]
1.6.9 版本是支持 border 属性的，能否提供一下 jsfiddle 呢，或者删掉 node_modules 重新安装试下
