### ISSUE TITLE
tab组件(swipeable)内容中有滚动条的div不能滑动，会直接切换tab页签

### ISSUE THREAD

**Issue by cqmking** [youzan/vant#2962]
![isuue-1](https://user-images.githubusercontent.com/22020241/54273324-a5404200-45c0-11e9-96a3-bebe3cad93d5.png)
如图，如何处理这类问题

**Comment by chenjiahan** [comment]
可以在你的二级导航组件上阻止 touch 事件冒泡

<custom-nav @touchmove.native.stop />
