### ISSUE TITLE
Radio 单选按钮， 如何跟输入框一样。 跟title一样 在一排，更好的展示

### ISSUE THREAD

**Issue by YeJch** [youzan/vant#2965]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
图片这样 使用css  弄的， 但是会出现错位， 有没有办法能不错位， 而且跟上面的输入框并齐。好看一点呢。。  新手勿喷， 求大神给个Demo
![1552530845(1)](https://user-images.githubusercontent.com/46618278/54327345-bdf23b80-4644-11e9-9ef8-ae134b925600.jpg)

**Comment by chenjiahan** [comment]
如果是垂直居中的话，可以考虑用 vertical-align 或 flex 进行对齐
