### ISSUE TITLE
form 验证

### ISSUE THREAD

**Issue by rfjo18** [youzan/vant#2967]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by aiyuchen** [comment]
我将vant的`field`和`async-validator`（http://github.com/yiminghe/async-validator）结合成了一个form组件

你可以看看
https://gist.github.com/aiyuchen/dfcf18300eef79b9465f0719a813a7f7

**Comment by chenjiahan** [comment]
可以试试楼上的方案喔，Vant 里暂无计划支持

**Comment by rfjo18** [comment]
打不开呀，兄弟

**Comment by aiyuchen** [comment]
@rfjo18 你可能得翻墙
