### ISSUE TITLE
希望增加一个查看旧版本文档的入口

### ISSUE THREAD

**Issue by panwenxin** [youzan/vant#2969]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?*
怎么查看以前的旧版本的文档？项目以前用的是1.0的 但是现在官网上都是1.6+的内容了。
**Describe the solution you'd like**
希望有个入口能看以前的文档

**What does the proposed API look like?**
希望有个入口能看以前的文档

**Comment by chenjiahan** [comment]
1.0 和 1.6 版本在组件 API 上没有太多变动（具体看更新日志里的 breaking change），所以 1.x 版本只会提供一个文档入口
