### ISSUE TITLE
mpvue+vant tabs标签页使用echarts切换宽度无法适应

### ISSUE THREAD

**Issue by leleTang** [youzan/vant#2970]
使用mpvue创建微信小程序,用vant框架
把charts控件放在tabs标签页里时,后面的切换宽度崩溃

针对vue有lazy-render属性,但是针对小程序开发没有这个属性设置,不起效果
![image](https://user-images.githubusercontent.com/17635886/54345758-a637a900-467e-11e9-81c3-03beed76ab66.png)
![image](https://user-images.githubusercontent.com/17635886/54345768-ac2d8a00-467e-11e9-89a4-91efd5e0b0b7.png)

**Comment by chenjiahan** [comment]
你好，小程序组件库的问题请到 vant-weapp 仓库下提问

**Comment by leleTang** [comment]
> 你好，小程序组件库的问题请到 vant-weapp 仓库下提问

好的~ 谢谢~
