### ISSUE TITLE
ImagePreview图片预览组件，在iPhone X上面不显示页面数，其他机型正常

### ISSUE THREAD

**Issue by tjsome** [youzan/vant#2972]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
ImagePreview图片预览组件，在iPhone X上面不显示页面数，其他机型正常

**Screenshots**
ImagePreview图片预览组件，在iPhone X上面不显示页面数，其他机型正常

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**

**Comment by chenjiahan** [comment]
试了下是正常的，能否提供截图看下
