### ISSUE TITLE
Steps 设置direction="vertical"竖向步骤条时已激活的项没有样式

### ISSUE THREAD

**Issue by akebe** [youzan/vant#2973]
正常情况应该是与横向步骤条一样，小于avtive的step应该是激活样式才对
![图片](https://user-images.githubusercontent.com/23068436/54406608-b5b60100-4715-11e9-8fb9-3c5f8fdcab8d.png)

**Comment by akebe** [comment]
![图片](https://user-images.githubusercontent.com/23068436/54410988-aee4b980-4728-11e9-99f0-a7c7b22e4296.png)
尝试加上`hairline`的样式
`
  .van-step--vertical.van-step--finish .van-step__circle,
  .van-step--vertical.van-step--finish .van-step__line {
    background-color: #07c160;
  }
`
发现不是想要的效果 `van-step__line`的高度得重新计算才能实现

**Comment by chenjiahan** [comment]
下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.6.10 版本修复
