### ISSUE TITLE
Popup弹出层配合Picker选择器，如何引用全局dict字典呢

### ISSUE THREAD

**Issue by YeJch** [youzan/vant#2974]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

Popup弹出层配合Picker选择器，选择民族的时候，如何引用全局dict字典呢。
还有就是 如何前台显示 中文， 传给后端 变成 String类型 或 布尔值 呢， 
现在只是在往后台提交的时候， 利用 Switch  case 来转换， 好麻烦的。
这方面 建议给个Demo 或者 详细解说一下， 因为是新手， 很多逻辑达不到

**Comment by chenjiahan** [comment]
你好，不知道你说的全局 dict 字典是指的什么，看起来是数据转换的问题，建议多学习下 JS 的基础知识，应该不难做到
