### ISSUE TITLE
van-checkbox-group 全选时，只有最后一个van-checkbox会改变状态

### ISSUE THREAD

**Issue by breezern** [youzan/vant#2975]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
循环触发van-checkbox-group中van-checkbox列表的toggle()方法，最后一个van-checkbox会生效。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/breezern/6cok4eyg/24/

**Comment by breezern** [comment]
#533 
参考#533已实现全选效果。

**Comment by chenjiahan** [comment]
由于 Vue 的 event emit 是异步的，所以同步调用多次 toggle 会有问题
全选的话直接这样写就行

```js
checkAll() {
  this.result = ['a', 'b', 'c'];
}
```
