### ISSUE TITLE
Checkbox 复选框bug

### ISSUE THREAD

**Issue by DaDaDaDaDaBocai** [youzan/vant#2976]
Checkbox 复选框 搭配单元格组件使用时

如果点击圆圈 则触发不了cell 的click事件

https://jsfiddle.net/4jv235m8/3/

另外官网的例子 搭配单元格组件使用时 for循环的时候 少了 index 导致下面找不到index

希望大佬关注一下 么么哒

**Comment by DaDaDaDaDaBocai** [comment]
最新发现  Radio 单选框  与 Cell 组件一起使用 时 也有BUG 更为严重
点击 圆圈 则触发不了cell 的click事件
如果点击cell则改变不了选中事件  但是可以触发click 事件

**Comment by huangysss** [comment]
同遇到相同情况, m

**Comment by chenjiahan** [comment]
点圆圈的时候，click 事件是默认不冒泡的。
如果冒泡会出现这样一种情况：内部触发一次 toggle 后，Cell 的 click 事件中再次触发 toggle，导致负负得正。
如果需要在 toggle 的时候做一些操作，可以使用 change 事件

**Comment by suguoyao** [comment]
这种情况，给css里`.van-checkbox`加一个`pointer-events: none;`就能解决
