### ISSUE TITLE
在tab组件中，使用list组件并v-for cell组件样式异常

### ISSUE THREAD

**Issue by suguoyao** [youzan/vant#2978]
**Describe the bug**
在tabs组件里，使用list组件，遍历多个标签（任意），当设置一个为scoped定义的class时，v-for渲染的第一个标签样式不生效，其他标签没问题

**Screenshots**
![image](https://user-images.githubusercontent.com/16471605/54420964-56241980-4746-11e9-8e49-017b26d7382b.png)

**Environment**
 - Device: all device
 - Browser: chrome
 - Vant Version: 1.6.7

**Reproduce**
https://codesandbox.io/s/q3o8w1r786

**Comment by chenjiahan** [comment]
下个版本会修复该问题。
简单解释下，这个问题是 Vue 的渲染机制导致的，Vue 在渲染过程中把第一个 Cell 和 List 的 loading 元素当成了同一个元素进行处理，导致 scopeId 没正确渲染。
下个版本会在 loading 元素上添加一个 key 来解决这个问题。

**Comment by suguoyao** [comment]
@chenjiahan 原来如此，谢谢哈！

**Comment by chenjiahan** [comment]
已在 1.6.10 版本修复哈
