### ISSUE TITLE
AddressEdit动态修改addressInfo任意一项值其它填写数据都会清空。

### ISSUE THREAD

**Issue by xutianh** [youzan/vant#2979]
问题：AddressEdit动态修改addressInfo任意一项值其它填写数据都会清空。

现象：根据业务需求详细地址从高德选取，选取地址后修改addressInfo.addressDetail后，只有addressInfo.addressDetail有值，其它填写过的值全部被清空。

期望结果：在改变addressInfo.addressDetail值后其它填写过的值不清空。

谢谢解答。

**Comment by chenjiahan** [comment]
可以使用 setAddressDetail 接口来进行设置的，后续会在文档里补一下

```html
<van-address-edit ref="edit" />
```

```js
mounted() {
  this.$refs.edit.setAddressDetail('地址内容');
}
```

**Comment by chenjiahan** [comment]
文档已更新
