### ISSUE TITLE
checkbox 支持 click 点击事件

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#2987]
##**What problem does this feature solve?**
购物车场景下, 有一 checkbox 组和一个全选 checkbox, 当 checkbox 组在 {全选, 非全选} 的对应 全选checkbox {true, false}, 此时 chang 事件不能满足需求, 需要用到 click.native. #533;
但是点击圆圈触发不了click事件, #2976;

**Describe the solution you'd like**
点击checkbox可以监听到点击事件

**What does the proposed API look like?**
<checkbox @click="function" />

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 1.6.11 版本支持

**Comment by mudoo** [comment]
@chenjiahan 1.6.11版本改完更困扰了，click事件会拿到两种value，点击label的时候，拿到的是未切换的值，点击图标的时候拿到的是切换过的值...

其实我觉得这个应该跟原生的保持一致，不管是点击label还是点击icon，都先进行切换值后再触发click，这样click捕获的值肯定是对的，个人认为这样更合适。

**Comment by mudoo** [comment]
仔细看了下源码，发现是因为label没有设置，导致触发了父元素的click，是父元素click没有切换值

**Comment by mudoo** [comment]
判断下是否根元素触发的click
```javascript
onPickAllClick(e) {
    if(e.target.classList.contains('van-checkbox')) {
        this.pickAll = !this.pickAll
    }
    // ...
}
```

**Comment by chenjiahan** [comment]
@mudoo  我试了下是正常的，能不能提供下有问题的 jsfiddle 呢
