### ISSUE TITLE
Popup 弹出层在Chrome35+中字体变模糊

### ISSUE THREAD

**Issue by webfelix** [youzan/vant#2989]
弹出层使用 transform: translate3d(-50%,0,0)和transform: translate3d(-50%,-50%,0)，导致在Chrome35+中字体变模糊，建议使用transform: translate(-50%,0)，不使用3d渲染

**Comment by ly1102** [comment]
> 建议加上下面这行代码试试，能解决问题的话，我们会加入到 vant 中
> 
> ```css
> .van-popup {
>   backface-visibility: hidden;
> }
> ```

这个似乎没有用。。。我刚刚试过了好几个。这个模糊的问题好像和屏幕分辨率的奇偶数有关，在偶数分辨率屏幕上基本没问题，如果遇到奇数就会出问题。

**Comment by Zeks1990** [comment]
> 建议加上下面这行代码试试，能解决问题的话，我们会加入到 vant 中
> 
> ```css
> .van-popup {
>   backface-visibility: hidden;
> }
> ```
是transform的最终计算值存在小数造成的，居中的显示建议用flex布局处理，另外swipe也有这个问题，可以尝试移动距离取整来修复

**Comment by Zeks1990** [comment]
> 建议加上下面这行代码试试，能解决问题的话，我们会加入到 vant 中
> 
> ```css
> .van-popup {
>   backface-visibility: hidden;
> }
> ```

我直接在node_modules\vant\es\swipe\index.js这个文件中
210行修改了this.offset = Math.round(offset - this.active * this.size);
目前能够解决问题，望采纳

**Comment by chenjiahan** [comment]
@Zeks1990 可以提个 Pull Refresh~

**Comment by Zeks1990** [comment]
@chenjiahan 请问提到那个分支？

**Comment by chenjiahan** [comment]
提交到 dev 分支。

Popup 内容模糊的问题，建议使用偶数的宽高试下，暂时没计划去除 translate3d
Swipe 会在下个版本优化

**Comment by chenjiahan** [comment]
Swipe 相关修复已在 1.6.11 版本发布

**Comment by th666** [comment]
所以弹框字体模糊的暂时不准备解决吗

**Comment by chenjiahan** [comment]
@th666 目前没找到合适的组件内部解决方案，可以试下上面提供的方法
