### ISSUE TITLE
NoticeBar 通告栏 无平行移动效果， 反而按照中心点旋转 未按照官方示例运行 

### ISSUE THREAD

**Issue by elvisz2016** [youzan/vant#2995]
**Describe the bug**
NoticeBar 通告栏内容按照元素中心顺时针旋转

**Screenshots**
![微信图片_20190319141819](https://user-images.githubusercontent.com/24736504/54584314-f5505600-4a51-11e9-906f-e4b638bb4642.png)

**Environment**
 - Device:  无
 - Browser:  Chrome 72.0.3626.96
 - Vant Version: 1.6.9

**Comment by chenjiahan** [comment]
你好，没复现这个问题，建议看下是不是有什么全局样式干扰了

**Comment by elvisz2016** [comment]
不好意思，动画名被打包成 a，然后起冲突了。请问有没有这方面的解决方法呢？

**Comment by chenjiahan** [comment]
可以看下你的 css 压缩工具的配置项，把压缩动画名的选项关闭掉

**Comment by elvisz2016** [comment]
感谢！
将 cssnano 的 reduceIdents改为false就可以了。
