### ISSUE TITLE
GoodsAction 里的按钮颜色自定义

### ISSUE THREAD

**Issue by pengbo37877** [youzan/vant#2996]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
GoodsAction 里的按钮颜色自定义

**Describe the solution you'd like**
GoodsAction 里的按钮颜色自定义

**What does the proposed API look like?**
GoodsAction 里的按钮颜色自定义

**Comment by chenjiahan** [comment]
直接传入 style 或 class 覆盖颜色就可以的
