### ISSUE TITLE
折叠面板，在vue内引用vant的时候正常，放到外面单独引用出错

### ISSUE THREAD

**Issue by chuanhaisoft** [youzan/vant#2997]
折叠面板，在vue内引用vant的时候正常，放到外面单独引用：
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vant@1.6.10/lib/index.css" />
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.9/dist/vue.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vant@1.6.10/lib/vant.min.js"></script>
时，提示：TypeError: Cannot read property 'items' of null

vue@2.6.9
vant@1.6.10
谷歌浏览器

代码：

＜van-collapse >
  ＜van-collapse-item title="aaaaaa" name="1">
    aaaaaa
  ＜/van-collapse-item>
＜/van-collapse>

**Comment by chuanhaisoft** [comment]
放到外面单独引用，很多组件都出现问题了
＜van-tabbar v-model="active">
    ＜van-tabbar-item icon="shop" to="/">消息</van-tabbar-item>
    ＜van-tabbar-item icon="contact" to="/group">群</van-tabbar-item>
 ＜/van-tabbar>

也报错

**Comment by shenxianweilai** [comment]
我也遇到了Dialog组件好像也没法用

**Comment by chenjiahan** [comment]
collapse 组件需要绑定 v-model 的呢，请参考文档示例

**Comment by chuanhaisoft** [comment]
绑定后，照样出错，＜van-tabbar v-model="active"> 这个不就绑定了，也一样出错

**Comment by chenjiahan** [comment]
如果有问题的话，可以提供一下 jsfiddle 呢
