### ISSUE TITLE
tab+list 给tab设置animated后有bug

### ISSUE THREAD

**Issue by lvlingjie** [youzan/vant#2998]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在父组件放一个van-tabs，给tab设置animated属性，van-tabs中有两个van-tab，分别加载子组件1和子组件2，子组件中有各自的list。tab1第一次加载完毕后，点tab2，tab2的数据加载完毕后，滚动，当滚动到第二页的时候，会触发tab1中的onload事件，两个tab同时滚动，chrome控制台会打印两个组件的数据

**Screenshots**
![image](https://user-images.githubusercontent.com/48229461/54589954-030dd780-4a62-11e9-8dca-776c448abcdb.png)
![image](https://user-images.githubusercontent.com/48229461/54590009-1de04c00-4a62-11e9-8ad4-dc9b3da41ce8.png)
![image](https://user-images.githubusercontent.com/48229461/54590020-22a50000-4a62-11e9-8b75-c77ab98c77d6.png)
![image](https://user-images.githubusercontent.com/48229461/54590072-394b5700-4a62-11e9-9b93-3a9274fc126a.png)

**Environment**
 - Device: chrome
 - Browser: chrome
 - Vant Version: 1.6.10

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
目前确实存在这个问题，而且组件内不是很好解决，你可以先使用局部滚动或关闭 animated 来避免

后续我们如果有进展，会同步在 https://github.com/youzan/vant/issues/2387 这个 issue 里
