### ISSUE TITLE
dialog框点击确认后弹出层未自动关闭

### ISSUE THREAD

**Issue by 565871779** [youzan/vant#2999]
![aaa](https://user-images.githubusercontent.com/41174671/54590943-28034a00-4a64-11e9-8202-dbf03e384fe5.gif)
![TIM截图20190319162900](https://user-images.githubusercontent.com/41174671/54590966-2df92b00-4a64-11e9-831c-0dd7063f1dad.png)

**Comment by chenjiahan** [comment]
能否提供一下 jsfiddle 呢

**Comment by 565871779** [comment]
> 能否提供一下 jsfiddle 呢

问题解决了，我开始是把一个toast和dialog放在了同一个axios请求的回调函数里。先显示一个loading的toast，然后条件判断是否调用clear关闭toast，并同时打开dialog，就会出现上面这种情况。后来我发现，如果不调用clear，让toast自然隐藏的话，就不会出现上面的情况。所以我把toast和dialog分开放后，就显示正常了

**Comment by chenjiahan** [comment]
下个版本会优化下这个问题

**Comment by chenjiahan** [comment]
已在 1.6.11 版本修复
