### ISSUE TITLE
Swipe 轮播，懒加载报错

### ISSUE THREAD

**Issue by 744934982** [youzan/vant#3001]
![image](https://user-images.githubusercontent.com/18650301/54596256-31de7a80-4a6f-11e9-9467-6060b7a6d30e.png)
![image](https://user-images.githubusercontent.com/18650301/54596269-3a36b580-4a6f-11e9-8ece-d913842e9511.png)

**Comment by chenjiahan** [comment]
需要注册一下 Lazyload 组件，参考 Lazyload 文档
