### ISSUE TITLE
请问一下怎么在fork里面改组件内容

### ISSUE THREAD

**Issue by qikai713** [youzan/vant#3002]
有一些组件我想加几个字段 比如联系人 我在zh-CN文件下加了字段本地也可以打包lib上传到自己的npm上 引用 自定义的字段就不生效了  我看了es文件下跟lib文件下都有自定义的字段 这是为什么

**Comment by qikai713** [comment]
好心人 求帮忙 qq联系也行 多谢

**Comment by chenjiahan** [comment]
可能是你的打包发布流程不规范，发布可以跑 npm run release 脚本，也可以 npm run build:lib 后手动 publish
