### ISSUE TITLE
请问能不能实现类似原生打开新窗体的效果？

### ISSUE THREAD

**Issue by myplxdm** [youzan/vant#3003]
比如：在页面上搜索得出列表，点击其中一条会弹出新窗体去显示，点关闭原界面内容保存原样，新窗体也可以点击再弹出窗体。

**Comment by chenjiahan** [comment]
暂时没计划实现呢

**Comment by myplxdm** [comment]
谢谢答复，但是这个是手机端最基本的功能，不然返回数据就很难保存状态，这样体验非常差，这个功能应该是最基本的功能

**Comment by chenjiahan** [comment]
H5 和原生还是有区别的，H5 没法弹出一个完整的窗口，只能通过 Popup 这样的组件做一个弹出层
