### ISSUE TITLE
checkbox点击问题

### ISSUE THREAD

**Issue by didashine** [youzan/vant#3009]
之前写几个checkbox附带全选时因为勾选掉某个checkbox会触发全选的change事件导致所有的checkbox都被勾选掉，所以在checkbox组件上使用了click.native的方法而没用change，1.6.7版本之后是不能这样用了吗?

**Comment by chenjiahan** [comment]
这里确实有个问题，下个版本 checkbox 可以直接监听 click 事件，无须 native 修饰符，具体见 https://github.com/youzan/vant/issues/2987
