### ISSUE TITLE
Actionsheet 上拉菜单设置cancel-text，自定义内容不渲染

### ISSUE THREAD

**Issue by 15992033543** [youzan/vant#3011]
如下

    <van-actionsheet
       v-model="visible"
      cancel-text="取消">
      <div>自定义内容</div>
    </van-actionsheet>

**Comment by chenjiahan** [comment]
目前版本不支持 default slot 和 cancel-text 同时使用，下个版本会支持一下

**Comment by chenjiahan** [comment]
已在 1.6.11 版本支持

**Comment by 15992033543** [comment]
> 已在 1.6.11 版本支持

thanks!
