### ISSUE TITLE
switch组件样式错误

### ISSUE THREAD

**Issue by liupei1995** [youzan/vant#3014]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/
![1553068600(1)](https://user-images.githubusercontent.com/21356797/54668042-e2f51b80-4b28-11e9-996e-c3d54f168c15.png)
switch样式变成这样了，版本为1.4.7
![1553068627(1)](https://user-images.githubusercontent.com/21356797/54668048-e7213900-4b28-11e9-9115-31f824bb1903.png)

**Comment by chenjiahan** [comment]
请确认下是否有全局样式干扰了，或者升级到最新版试下，文档上是正常的
