### ISSUE TITLE
van-area  确认点击不了

### ISSUE THREAD

**Issue by zxyIsStudent** [youzan/vant#3018]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
van-area 嵌套在van-popup中选择省市区完成后点击“确认”没反应，最后发现他的光标在‘’确认‘按钮的’的上边一点
**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/46954827/54673394-22c20000-4b35-11e9-855a-635df3e261ea.png)

**Environment**
 - Device: iphone8p iphonex
 - Browser: 微信内置浏览器
 - Vant Version: 1.0.1

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
目测是这个问题，建议试下文章内的解决方案

https://juejin.im/post/5c07442f51882528c4469769
