### ISSUE TITLE
IOS 上 dialog 高级用法 样式会被虚拟键盘 顶乱

### ISSUE THREAD

**Issue by code-admin** [youzan/vant#3019]
**Describe the bug**

**Screenshots**
IOS 上 dialog 高级用法 样式会被虚拟键盘 顶乱
**Environment**
 - Device: iphone6s plus 
 - Browser: wechart
 - Vant Version:  ios 12.1.4

**Reproduce**

**Comment by chenjiahan** [comment]
不规范的 issue，请提供截图和复现步骤
