### ISSUE TITLE
使用rem适配,在SwipeCell中存在问题

### ISSUE THREAD

**Issue by Wy38722** [youzan/vant#3020]
在使用rem适配时候，使用SwipeCell时，right-width属性只可以传number类型，然后在transform中是px单位的，不能适配rem。

**Comment by chenjiahan** [comment]
因为 SwipeCell 内部有距离的计算，所以需要使用 px 作为单位，如果你是用 rem 布局的话，可以按你的 rem 基准值进行转换，换算成 px 传入
