### ISSUE TITLE
Tab控件line的位置和宽度出错

### ISSUE THREAD

**Issue by brettyin** [youzan/vant#3034]
Tab采用的line风格，UI初始化后line有时不在正确的Tab下，并且宽度也不对. 并不是每次刷新UI都会出错，出错概率约为50%
![1991553223554_ pic](https://user-images.githubusercontent.com/417249/54798005-8a8d5d80-4c91-11e9-80f8-3d71bc6af45e.jpg)

**Comment by chenjiahan** [comment]
能否提供一下 jsfiddle
