### ISSUE TITLE
Stepper 步进器，小数输入问题

### ISSUE THREAD

**Issue by zzhangyx** [youzan/vant#3035]
**Describe the bug**
Stepper 步进器，在不改变原有数值的情况下，直接输入小数点无法输入。比如原有数值2，我需要改成2.5，直接输入小数点无法输入。

**Screenshots**

**Environment**
 - Device: 
 - Browser: chrome
 - Vant Version: 1.6.10

**Reproduce**

**Comment by chenjiahan** [comment]
没复现这个问题，你是设置了 integer 属性吗
