### ISSUE TITLE
Toast轻提示，设置setDefaultOptions不生效

### ISSUE THREAD

**Issue by weishax** [youzan/vant#3036]
**Describe the bug**
无法使用setDefaultOptions对所有 Toast修改默认配置，必须每个Toast手动设置Options

**Screenshots**
![image](https://user-images.githubusercontent.com/40553114/54799319-9ed45900-4c97-11e9-839d-f286d9d3f0d0.png)

**Environment**
 - Browser: Chrome
 - Vant Version: 1.6.10

**Comment by chenjiahan** [comment]
setDefaultOptions 是一个函数喔，通过函数的第一个参数来设置默认选项
