### ISSUE TITLE
vant-list遍历数据 第一个子节点样式不生效

### ISSUE THREAD

**Issue by yibhou** [youzan/vant#3038]
**Describe the bug**
vant-list遍历数据 第一个子节点样式不生效，请问这个如何解决

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/10102594/54804189-8ff8a100-4cad-11e9-9f4c-cfa32eac612a.png)

![image](https://user-images.githubusercontent.com/10102594/54804221-a6066180-4cad-11e9-871c-23c3f98957ca.png)

![image](https://user-images.githubusercontent.com/10102594/54804147-77888680-4cad-11e9-9577-4c210493b0e3.png)

![image](https://user-images.githubusercontent.com/10102594/54804585-fc27d480-4cae-11e9-9633-698352e7bf20.png)

**Environment**
 - Browser: Chrome
 - Vant Version: 1.5.6
 - Vue Version: ^2.5.17

**Comment by chenjiahan** [comment]
请参考 https://github.com/youzan/vant/issues/2978

**Comment by yibhou** [comment]
问题已解决 谢谢~

**Comment by Huaci** [comment]
最新版本依然存在这个问题

**Comment by chenjiahan** [comment]
@Huaci 能否提供个 codesandbox 复现链接

**Comment by sbyps** [comment]
@chenjiahan vant 2.8.0 此问题出现

**Comment by chenjiahan** [comment]
@sbyps 2.8.0 没改 List，可以来个复现链接
