### ISSUE TITLE
直接引入CDN使用vant, area组件不可用

### ISSUE THREAD

**Issue by shiyuegongsui** [youzan/vant#304]
直接引入CDN使用vant, area组件不可用

**Comment by chenjiahan** [comment]
@shiyuegongsui 经测试没有问题，请确认是否按照文档方式使用
测试地址：https://jsfiddle.net/gu4ho7hh/

**Comment by shiyuegongsui** [comment]
@chenjiahan  感谢回复。
在VUE V2.1.10版本确有问题，升级到v2.5.3就没问题了。
