### ISSUE TITLE
[Bug Report] tag在部分手机如vivo x9上，边框显示不全

### ISSUE THREAD

**Issue by ylethe** [youzan/vant#3042]
**Describe the bug**
tag在部分手机如vivo x9上，边框显示不全

**Screenshots**
![image](https://user-images.githubusercontent.com/19504691/54816457-386b2d00-4ccf-11e9-8842-cc0f14754909.png)

**Environment**
 - Device: vivo x9
 - Browser: 
 - Vant Version: 1.5.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
近期会看一下如何兼容

**Comment by chenjiahan** [comment]
找了一台 X9 试了下，是能展示全的，建议看下项目里是否有 overflow hidden 之类的样式导致边框被裁剪了
