### ISSUE TITLE
van-uploader组件设置只拍照不选择本地图片无效问题

### ISSUE THREAD

**Issue by RubbbbbY** [youzan/vant#3043]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
![`9_0_)8HZUCS{QZW 6}J)ZR](https://user-images.githubusercontent.com/19768528/54819238-36f13300-4cd6-11e9-879c-f68c21fe8ee3.png)
这里设置了capture="camera"，
![1553253102(1)](https://user-images.githubusercontent.com/19768528/54819277-6142f080-4cd6-11e9-95e6-5a93dff43d45.jpg)
这里页面也显示有该属性了，但是手机上还是会弹出文件或者相册选择，并没有马上打开相机
![微信图片_20190322191348](https://user-images.githubusercontent.com/19768528/54819373-a8c97c80-4cd6-11e9-9961-278f87a3ddd0.jpg)

**Screenshots**
Add screenshots to help explain your problem.
希望得到解决方案，谢谢
**Environment**
 - Device: 小米8系列手机
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
uploader 里用的是原生的 input type="file"，capture="camera" 如果不生效，应该是系统兼容的问题，建议自行搜索下有没有解决方案

**Comment by zhujianxiong** [comment]
没有找到解决的方案实现
