### ISSUE TITLE
DatetimePicker组件设置最大或最小时间后，浏览器会卡死

### ISSUE THREAD

**Issue by aiyuchen** [youzan/vant#3046]
**Describe the bug**
设置了最大或者最小时间后，滑动日期会卡死

**Screenshots**
![ezgif-4-d5ac57e12f1b](https://user-images.githubusercontent.com/578141/54862633-86883b00-4d78-11e9-9b1f-09b52a5f9d4a.gif)

**Environment**
 - Device: OSX 10.14.3
 - Browser: chrome 73
 - Vant Version: 1.6.10

**Reproduce**
https://jsbin.com/cuwatuy/3/edit?html,js,output

**Comment by aiyuchen** [comment]
如果把标签里面这两行去掉就流畅了，麻烦解决一下
```
:max-date="new Date(currentDate - 86400)"
:min-date="new Date('2016-08-01')"
```

**Comment by chenjiahan** [comment]
正确写法是把 maxDate 和 minDate 放到 data 里，而不是每次 render 的时候都重新计算

因为 currentDate 是变量，如果每次渲染的时候都重新计算 `max-date="new Date(currentDate - 86400)"`，会导致 maxDate 一直在变化
