### ISSUE TITLE
<swipe-cell /> 处于 open 状态时，页面无法上下滑动

### ISSUE THREAD

**Issue by ystarlongzi** [youzan/vant#3047]
**Describe the bug**
当 `<swipe-cell />` 处于 open 状态时，手指再次触摸该项时，且上下滑动时页面不会滚动。而在微信里的交互，是允许上下滚动的

针对此种场景，不知道官方倾向于哪种交互？

**Screenshots**
- 无

**Environment**
 - Device: ALL
 - Browser: ALL
 - Vant Version: 1.6.11

**Reproduce**
 - 无

**Comment by chenjiahan** [comment]
这里允许上下滚动是比较合理的，需要优化一下

**Comment by chenjiahan** [comment]
已在1.6.12版本修复
