### ISSUE TITLE
vant-list组件load事件无限触发

### ISSUE THREAD

**Issue by qinqin772** [youzan/vant#3050]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
初始状态设置loading:false,finished:false,immediate-check:true 来触发数据加载任务，任务加载完成（成功或失败）设置loading为false，直到最后disable置为true，使用的async/await/finally方式 。上述步骤在请求正常的情况下工作的很好，但是如果网络异常/服务器端异常，由于loading置为false后，list组件又会自动检测一遍，再次触发load事件，一直反复下去，导致无限请求

**Screenshots**
无

**Environment**
 - Vant Version: 
1.4.2

**Comment by Gardent** [comment]
immediate-check设置成false，应该就不会这样了。

**Comment by qinqin772** [comment]
immediate-check设置为false也会这样

**Comment by chenjiahan** [comment]
设置 finished 或者 error 都可以停止触发 load 事件

**Comment by thiszhong** [comment]
@chenjiahan 有一种情况是：当列表中的 item 使用了浮动 `float` 时，可能会使 `van-list__placeholder` 位置错乱，从而导致
```
isReachEdge = placeholderRect.bottom - scrollerRect.bottom
```
是一个固定的负数 < offset，进而无限 `load`，不得不提前设置 `fiinished = true`。
我的解决方法是清除浮动，手动在 `items` 外面套了个 `<div style="overflow: hidden;">"`，当然也有其他清除浮动的方法。
因为 `van-list__placeholder` 和 `van-list__loading` 一般是组件后来自动追加的，所以用户可能不会想到在里面清除浮动，比如我一开始是直接在 `<van-list>` 上操作，是不管用的。
不知道这种情况是提醒用户还是组件内部针对 `slot.default` 做个清除浮动的处理好。下面是一些截图：
![image](https://user-images.githubusercontent.com/12380965/60701134-3602ab00-9f2d-11e9-8fec-a8cabf55285f.png)

**Comment by chenjiahan** [comment]
@thiszhong 这种情况确实需要清除浮动，但是组件内部目前不太好加，除非再套一层 div。可以由使用方手动来加，我在文档里说明一下

**Comment by thiszhong** [comment]
> 这种情况确实需要清除浮动，但是组件内部目前不太好加，除非再套一层 div。可以由使用方手动来加，我在文档里说明一下

嗯，方便排查问题所在就行。这个知道了也好解决，我是查了半天 [捂脸哭]，其他列表都是好的。

**Comment by hanliujun** [comment]
请问这个问题解决了么？

**Comment by Ai-arch** [comment]
请问这个问题解决了么？

**Comment by hanliujun** [comment]
已经解决了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ai-arch ***@***.***&gt;
发送时间: 2021年5月14日 10:56
收件人: youzan/vant ***@***.***&gt;
抄送: hanliujun ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[youzan/vant] vant-list组件load事件无限触发 (#3050)





 
请问这个问题解决了么？

**Comment by Ai-arch** [comment]
怎么解决的啊？求告知！！求告知！！

**Comment by Ai-arch** [comment]
怎么解决的啊？求告知！求告知！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 中午1:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant] vant-list组件load事件无限触发 (#3050)





 已经解决了 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: Ai-arch ***@***.***&amp;gt; 
 发送时间: 2021年5月14日 10:56 
 收件人: youzan/vant ***@***.***&amp;gt; 
 抄送: hanliujun ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: 回复：[youzan/vant] vant-list组件load事件无限触发 (#3050) 
 
 
 
 
 
   
 请问这个问题解决了么？

**Comment by hanliujun** [comment]
微信聊吧，我给你发代码，我现在是手机上邮件回复的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ai-arch ***@***.***&gt;
发送时间: 2021年5月14日 14:49
收件人: youzan/vant ***@***.***&gt;
抄送: hanliujun ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[youzan/vant] vant-list组件load事件无限触发 (#3050)





 怎么解决的啊？求告知！求告知！！ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年5月14日(星期五) 中午1:03 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [youzan/vant] vant-list组件load事件无限触发 (#3050) 
 
 
 
 
 
  已经解决了  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: Ai-arch ***@***.***&amp;amp;gt;  
  发送时间: 2021年5月14日 10:56  
  收件人: youzan/vant ***@***.***&amp;amp;gt;  
  抄送: hanliujun ***@***.***&amp;amp;gt;, Comment ***@***.***&amp;amp;gt;  
  主题: 回复：[youzan/vant] vant-list组件load事件无限触发 (#3050)  
   
   
   
   
   
     
  请问这个问题解决了么？

**Comment by hanliujun** [comment]
13070105655



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ai-arch ***@***.***&gt;
发送时间: 2021年5月14日 14:49
收件人: youzan/vant ***@***.***&gt;
抄送: hanliujun ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[youzan/vant] vant-list组件load事件无限触发 (#3050)





 怎么解决的啊？求告知！求告知！！ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年5月14日(星期五) 中午1:03 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [youzan/vant] vant-list组件load事件无限触发 (#3050) 
 
 
 
 
 
  已经解决了  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: Ai-arch ***@***.***&amp;amp;gt;  
  发送时间: 2021年5月14日 10:56  
  收件人: youzan/vant ***@***.***&amp;amp;gt;  
  抄送: hanliujun ***@***.***&amp;amp;gt;, Comment ***@***.***&amp;amp;gt;  
  主题: 回复：[youzan/vant] vant-list组件load事件无限触发 (#3050)  
   
   
   
   
   
     
  请问这个问题解决了么？
