### ISSUE TITLE
Checkbox不能使用动态v-model

### ISSUE THREAD

**Issue by xutianh** [youzan/vant#3051]
使用场景：购物车，商品是否选择数据保存在商品列表里。

代码：循环代码时代码```<van-checkbox :v-model="item.checked"></van-checkbox>```。item.checked值为boolean。

问题：使用:v-model时复选框不能使用（不能选择、Event事件无效）。

期望结果：使用:v-model时复选框可以正常使用。

谢谢解答。

**Comment by xutianh** [comment]
代码：循环代码时代码<van-checkbox :v-model="item.checked"></van-checkbox>。

**Comment by xutianh** [comment]
不知道为啥代码显示不出来。

**Comment by xutianh** [comment]
代码：循环代码时代码<van-checkbox :v-model="item.checked"></van-checkbox>

**Comment by xutianh** [comment]
循环代码时代码```<van-checkbox :v-model="item.checked"></van-checkbox>```

**Comment by chenjiahan** [comment]
只要 v-model 绑定的是在 data 上面的数据，都是可以使用的
