### ISSUE TITLE
stepper 数值较大时，宽度不能自适应

### ISSUE THREAD

**Issue by lyq027** [youzan/vant#3052]
stepper 数值较大时，宽度不能自适应 

希望：能随着数值变大，比如5位数时，自适应宽度

版本：1.6.5

**Comment by lyq027** [comment]
stepper  希望可以设置格式化显示2位小数，有时候会将stepper 当作金额输入框使用

**Comment by chenjiahan** [comment]
后续会看下怎么支持

**Comment by chenjiahan** [comment]
下个版本会支持控制输入框宽度，格式化暂时没计划支持

**Comment by chenjiahan** [comment]
已在 1.6.13 版本支持 input-width 属性
