### ISSUE TITLE
数字键盘

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#3059]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.
数字键盘样式在小米note3mix3上出错，出现长度不足

**Comment by chenjiahan** [comment]
能否提供一下截图呢

**Comment by cangyu1993** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    
    
        
        

        
    

    在2019年3月27日 22:30，neverland<notifications@github.com> 写道： 


能否提供一下截图呢

**Comment by chenjiahan** [comment]
加了上述样式试了下，不会有影响

**Comment by cangyu1993** [comment]
额，那个样式我没写，不知道是怎么出来的，我回复了邮件，截图在邮件里了，感谢回复

**Comment by cangyu1993** [comment]
![image](https://user-images.githubusercontent.com/42930030/55273255-d8ded400-5303-11e9-9bd1-c4b95ca9b126.png)
