### ISSUE TITLE
 iOS 系统点击反馈问题

### ISSUE THREAD

**Issue by ipumpkinbomb** [youzan/vant#3060]
**Describe the bug**
使用 vue-cli3 新建的项目，只加了一个 Cell 组件测试，在 iOS 系统上没有点击反馈，Android 上正常。但是官网的 demo 在 iOS 上点击反馈正常，没有找到是哪里引起的问题。

**Environment**
 - Device: iOS 12.1.4 / 12.2
 - Browser: WeChat 7.0.3 / Mobile Safari 12.1
 - Vant Version: 1.6.11
 - Vue Version: 2.6.10

**Comment by chenjiahan** [comment]
在 body 标签上添加 touch 事件即可，原理可以自行搜索下
<body touchstart>

**Comment by 1652045218** [comment]
<body ontouchstart="">
