### ISSUE TITLE
dialog中加field在ios下会存在位移问题

### ISSUE THREAD

**Issue by petersmu** [youzan/vant#3063]
**Describe the bug**
dialog组件中加入field组件，这是官方文档里的高级用法，但实际使用中在ios系统中会存在BUG。当弹窗弹出时，正常显示弹窗，但点击输入框聚焦后，再失焦收起键盘，这时弹窗后的window整体都会被键盘挤上去，并且此时弹窗的按钮和输入框也错位了，点击按钮无法操作。

**Screenshots**
![image](https://user-images.githubusercontent.com/12507715/55126412-f1a28a80-5147-11e9-918c-dce68ba5e3bc.png)

**Environment**
 - Device: iPhoneX
 - Browser: 微信webview
 - Vant Version: 1.6.11

**Reproduce**
点击弹窗->聚焦输入框->收起键盘

**Comment by chenjiahan** [comment]
iOS系统确实会有这样的问题，后续会改下示例，不推荐在 fixed 容器中使用输入框

**Comment by chenjiahan** [comment]
示例已更新

**Comment by petersmu** [comment]
我已经找到解决方案了，通过监听输入框的失焦和聚焦来做window的滚动归位操作。

**Comment by petersmu** [comment]
我已经解决了这个问题，通过监听全局的聚焦和失焦事件来处理，在失焦时window滚动归位就可以了。
`let windowScroll;
const isiOS = !!navigator.userAgent.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/);
if (isiOS) {
  document.body.addEventListener("focusout", () => {
    //软键盘收起的事件处理
    console.log("onblur");
    windowScroll = window.setTimeout(() => {
      window.scroll(0, 0);
    }, 100);
  });
  document.body.addEventListener("focusin", () => {
    //软键盘弹出的事件处理
    console.log("onfocus");
    if (windowScroll !== undefined) {
      window.clearTimeout(windowScroll);
    }
  });
}`
代码贴给你们看看，如果觉得有必要的话可以加到组件库中，我们现在自己加了这段全局监听

**Comment by chenjiahan** [comment]
嗯，业务中可以这样 hack 处理的，但是不太好加到组件库里

**Comment by HighWarmModel** [comment]
button也是有点坑
