### ISSUE TITLE
Tabbar 标签栏路由跳转到新页面中再次使用Tabbar无效果

### ISSUE THREAD

**Issue by 51350215** [youzan/vant#3065]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
首页使用Tabbar 标签创建底部导航栏，在其中一个导航链接的页面中再次使用Tabbar 标签没有任何作用，显示空白

**Describe the solution you'd like**
在多层路由跳转后的页面中都可以正常使用Tabbar 标签

**What does the proposed API look like?**
类似于京东APP点击“我的”后显示的页面中看到的“待付款”、“待收货”、“待评价”
，此类效果。而我在二级路由中的页面使用Tabbar 标签没有任何效果。

**Comment by 51350215** [comment]
发现问题：fixed=“false"无效，导致所有的Tabbar 标签全部固定在底部

**Comment by chenjiahan** [comment]
不知道你说的空白是什么意思，建议检查下是不是用法有误
