### ISSUE TITLE
Tabbar 标签属性fixed="false"无效

### ISSUE THREAD

**Issue by 51350215** [youzan/vant#3066]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Tabbar 标签属性fixed="false"无效，导致子组件与父组件的Tabbar全部固定在底部

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
建议确认下是否正确传值，fixed 前面要加冒号
