### ISSUE TITLE
pc微信van-swipe-cell 的滑动和点击事件冲突

### ISSUE THREAD

**Issue by InfaceMan** [youzan/vant#3067]
van-swipe-cell 上绑定了 click 事件，在pc微信上 滑动单元格会触发点击事件
代码如下图
![image](https://user-images.githubusercontent.com/32891469/55224634-e8024b00-524b-11e9-95ec-19ba61fd13d8.png)

**Comment by chenjiahan** [comment]
swipe-cell 是基于 touch 事件的，PC 端目前不支持喔
