### ISSUE TITLE
Popup 弹出层  使用input时候异常关闭

### ISSUE THREAD

**Issue by caicai199604** [youzan/vant#3070]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
 :close-on-click-overlay="true"
软键盘弹起输入完内容之后 双击弹窗内容会关闭软键盘并且关闭弹窗，单击的时候是正常的只是关闭了软键盘。
软键盘没有弹起时一切正常

使用蒙层点击事件，效果也是一样。
问题总结 软键盘弹起之后的**双击**弹窗内容之后的异常关闭与蒙层的点击事件有某种关联

**Screenshots**
![image](https://user-images.githubusercontent.com/39294321/55300855-35f59980-546c-11e9-97db-6cdc59798745.png)
![image](https://user-images.githubusercontent.com/39294321/55301000-ff6c4e80-546c-11e9-88be-f90e5f217725.png)

**Environment**
 - Device: vivo x9
 - Browser:  微信浏览器
 - Vant Version: 1.5.1

**Reproduce**

**Comment by chenjiahan** [comment]
看了一下没有发现问题呢，蒙层上绑定的也是正常的点击事件，要么就是浏览器对双击的处理出现了问题
