### ISSUE TITLE
Dialog can't exist both Advanced Usage and Function Usage

### ISSUE THREAD

**Issue by skyfore** [youzan/vant#3071]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

Dialog can't exist both Advanced Usage and Base Function Call
弹窗组件不能基础用法和高级用法并存。

**Describe the solution you'd like**

Now there is a scenario where I need both a basic popup and a custom popup form in one page. When both exist, they will throw a mistake.
现在有一个场景就是，我在一个页面中既需要基础的弹窗用法，又需要一个自定义的弹窗表单。当两者都存在的时候就会抛错。

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

None

**Comment by chenjiahan** [comment]
具体报什么错呢，文档的示例就是两种用法并存的，没发现问题
