### ISSUE TITLE
tabs 选中项丢失

### ISSUE THREAD

**Issue by Orialian** [youzan/vant#3073]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在使用 tabs时,如果进行了页面跳转,返回来即使设置 tabs 的选中默认值,还是会没有选中样式.只有重新点击tabs 的选项时才会出现.

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/34876408/55305755-503b7180-5484-11e9-8545-2a91fbfee385.png)

**Environment**
 - Device:  pc; 荣耀v10
 - Browser:  chrome; chrome
 - Vant Version: 1.6.8

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
http://tobefree.top/wo/#/home

**Comment by chenjiahan** [comment]
看了下你提供的页面，好像没有这个问题呢

**Comment by Orialian** [comment]
初始化进入页面后, 主页 中 所有是选中的, 此时切换没有问题, 然后点击到 我的, 点击任意链接进去后,再返回出来, 切换到 主页, 此时 tab 没有任意的 item 被选中了.
![image](https://user-images.githubusercontent.com/34876408/55550978-44fa7700-570c-11e9-8bde-543a10fb0b6f.png)
![image](https://user-images.githubusercontent.com/34876408/55551001-52affc80-570c-11e9-8403-e9d295262692.png)

**Comment by chenjiahan** [comment]
ok 复现了，我看下怎么处理

**Comment by Orialian** [comment]
好的, 谢谢

**Comment by chenjiahan** [comment]
已在 1.6.13 版本修复

**Comment by Orialian** [comment]
刚更新到1.6.13版,发现那个问题还在,已build更新了资源放在issue原链接中. 于是我尝试给标记底线给宽度, 但是返回的时候 标记底线的 偏移值不对. 
正常: http://tobefree.top/wo/img/normal.png
异常: http://tobefree.top/wo/img/error.png

**Comment by chenjiahan** [comment]
能给个复现的 jsfiddle 不

**Comment by Orialian** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        https://jsfiddle.net/389q75jo/1/   在jsfiddle 中复现不出来 , 项目中才会出现这种问题. 
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                651794793
                            
                    
                        
                            
                                    651794793@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年4月8日 11:25，neverland<notifications@github.com> 写道： 


能给个复现的 jsfiddle 不



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by chenjiahan** [comment]
建议确认下 vant 版本是否升级到最新了，以及项目里是否有一些特殊的用法导致这个问题

**Comment by Orialian** [comment]
vant 是最新版, 应该是这么回事: 项目中 tabs 是被包含在 tabs中的, 当我在首页中点链接跳转的时候再返回时没有问题的, 如果在 外层 tabs 的其他 tab中进行页面跳转再返回的时候并不是首页tab, 这时 首页tab的 display 为 none, 因此获取不到宽度, 那么 tab 的激活底线也就获取不到宽度了.无法显示

**Comment by chenjiahan** [comment]
目前是会在 activated 的时候重新获取宽度的，你的 display none 是自己手动控制的吗，那内部是监听不到的

**Comment by Orialian** [comment]
确实是自己控制的,  tabbar 没有对应的 container, 所以目前是用 tabbar 绑定的选项来控制 显隐.

**Comment by chenjiahan** [comment]
这种情况比较难处理呢，建议你用 `keep-alive` 加上 `v-if` 控制显隐试试

**Comment by Orialian** [comment]
嗯, 刚试过了,可以, 之前用的 v-show 不行. 谢谢

**Comment by chenjiahan** [comment]
客气哈
