### ISSUE TITLE
vant 更新之后样式问题 

### ISSUE THREAD

**Issue by chaode0620** [youzan/vant#3074]
之前使用vant框架做的一套项目。维护时发现vant更新，并且样式文件路径也改变。更重要的是，测试过程中。发现与之前的样式有绝大的变化。许多样式的class上下级转换，导致上次做的一些处理全部失效。

**Comment by chenjiahan** [comment]
你好，进行较大跨度的版本升级时，建议阅读更新日志的 breaking changes，并做好测试工作
