### ISSUE TITLE
输入框尾部图标无法自定义（无法显示）

### ISSUE THREAD

**Issue by DeveloperCharles** [youzan/vant#3075]
**Describe the bug**
A clear description of what the bug is.
输入框尾部图标无法自定义，无论是API形式，还是slot形式，都无法显示。
只有当is-link为true时，才会显示右侧箭头。

**Screenshots**
Add screenshots to help explain your problem.
![QQ截图20190401154631](https://user-images.githubusercontent.com/34536912/55311336-39514b00-5495-11e9-8b9c-a84db2829a7c.png)

**Environment**
 - Device: Windows
 - Browser: Google Chrome
 - Vant Version: v1.6.12

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by DeveloperCharles** [comment]
Field 组件

**Comment by DeveloperCharles** [comment]
![QQ图片20190401155745](https://user-images.githubusercontent.com/34536912/55311891-c2b54d00-5496-11e9-9ff8-024727999545.png)
补充代码截图

**Comment by chenjiahan** [comment]
试了一下没问题喔，建议确认下 vant 版本是不是最新的，或者重新安装 node_modules
