### ISSUE TITLE
组件的动画能否考虑使用translate减少对项目样式的侵入

### ISSUE THREAD

**Issue by yajore** [youzan/vant#3079]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
举个简单的列子popup带的动画transform样式，我项目中如果popup内有fixed定位就会失效，chrome下父容器如果有transform貌似fixed定位就跪了

**Describe the solution you'd like**
用translate，依赖leave，enter

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
不是很明白你的意思，translate 不也需要使用 transform 嘛

**Comment by yajore** [comment]
translate 用完就被remove，不是有进场class和离场class，vant用的样式还在，导致的一个结果就是我在popup中用fixed定位被父级的transform影响，无法fixed

**Comment by chenjiahan** [comment]
后续会看一下能否迁移到这个方案

**Comment by chenjiahan** [comment]
目前 Popup 居中依赖 transform，所以改不了这个方案
