### ISSUE TITLE
stepper

### ISSUE THREAD

**Issue by AutumnFor** [youzan/vant#3081]
步进器的异步变更中输入数字.会导致步进器输入框数字一直闪烁!

https://youzan.github.io/vant/#/zh-CN/stepper
官网的步进器异步的那个,快速输入两个数字.问题显示!

**Comment by chenjiahan** [comment]
没复现喔，具体机型是？

**Comment by AutumnFor** [comment]
![IMG_4547](https://user-images.githubusercontent.com/26239511/55569096-881c1080-5733-11e9-87d3-3be526a7146f.GIF)
![Uploading IMG_4547.GIF…]()

**Comment by chenjiahan** [comment]
后续会更新一下示例

**Comment by chenjiahan** [comment]
已更新
