### ISSUE TITLE
自定义Sku 商品规格弹层时，各个粉组件的props都是一样的，数据不对应

### ISSUE THREAD

**Issue by b2simpleman24** [youzan/vant#3083]
**Describe the bug**
自定义Sku 商品规格弹层时，各个子组件的 props 值一样，数据不对应

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/36991472/55393454-e4363780-556f-11e9-8e52-4005f065e756.png)
![image](https://user-images.githubusercontent.com/36991472/55393532-0465f680-5570-11e9-84df-61fe494d2d1d.png)

**Environment**
 - Device: Lenovo T440P
 - Browser: Chrome 73.0.3683.75
 - Vant Version: 1.6.12

**Reproduce**
正常运行，使用官网数据格式

**Comment by chenjiahan** [comment]
拿到的数据都是一样的格式喔，具体展示方式是自行处理的
