### ISSUE TITLE
van-datetime-picker日期时间组件选中后的时间怎么格式化

### ISSUE THREAD

**Issue by webwuyou** [youzan/vant#3084]
van-datetime-picker日期时间组件选中后的时间怎么格式化
popup结合van-datetime-picker  
默认情况下得到的是这样的时间，Mon Aug 03 2026 00:00:00 GMT+0800 (中国标准时间)

看文档有个formatter  但是用了还是不行。
日期组件获取2019-03-12这样的时候，获取时间戳都很常见，请问后面会有这样的配置项吗？或者是现在就有我的用法不对哦

而且在popup上下滑动年月日时，输入框里面的绑定的值会同步变化，正常应该是滑动时输入框的内容不变，点击popup的确认按钮时才改变输入框的值。

**Comment by chenjiahan** [comment]
1. 时间返回的是 Date 对象，可以直接使用 Date 对象的方法
2. 这个看你监听的是 change 事件还是 confirm 事件了

**Comment by tongxin2013** [comment]
楼主有解决方案了吗？

**Comment by tongxin2013** [comment]
> 而且在popup上下滑动年月日时，输入框里面的绑定的值会同步变化，正常应该是滑动时输入框的内容不变，点击popup的确认按钮时才改变输入框的值。

楼主这块儿有解决办法了吗？

**Comment by eMillet** [comment]
我也是使用Date对象的方法，例如toLocaleDateString()；先将日期转换成 yyyy/mm/dd格式，然后relpace替换  ‘/’ 为 ‘ - ’  转换成yyyy-mm-dd格式

**Comment by Corgis** [comment]
专门定义一个字段去v-model 用于 给 picker双向绑定    然后点确定时 去设置格式化的值 到 目标字段去
