### ISSUE TITLE
area组件 小程序 columns-num设置2和1都不起效，显示内容为空

### ISSUE THREAD

**Issue by Gaomengxuan** [youzan/vant#3085]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
area组件 小程序 columns-num设置2和1都不起效，显示内容为空

**Screenshots**

![image](https://user-images.githubusercontent.com/14121619/55460477-acd59280-5624-11e9-949e-0d0f42d93dfb.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
你好，小程序组件请到 vant-weapp 仓库下提问
