### ISSUE TITLE
iphone微信浏览器内弹出系统键盘后，页面上推后弹出的Dialog.alert无法关闭！

### ISSUE THREAD

**Issue by yujinping** [youzan/vant#3088]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

在苹果手机iPhone6S的最新版微信内嵌浏览器内，当页面有输入内容，且系统输入键盘弹出后将页面内容顶上去之后，关闭系统输入键盘，此时页面不回弹(或不关闭系统输入键盘)。点击页面内按钮激活Dialog.alert，此时点击Dialog.alert的关闭按钮无法关闭对话框。前述关闭系统输入法键盘后，手动将页面下拉使得页面回弹回原来的位置，点击页面内按钮激活Dialog.alert,再点击对话框内的关闭按钮此时就可以关闭对话框。

**Screenshots**

Add screenshots to help explain your problem.
这张是初始状态图，弹出的alert对话框可以关闭。
![IMG_4112](https://user-images.githubusercontent.com/2682073/55492299-97368c00-5669-11e9-8278-e27dede78772.PNG)

这张图是点击底部的输入框（例如输入收货地址）后弹出系统键盘，此时系统键盘将网页一部分部分推了上去！
![IMG_4113](https://user-images.githubusercontent.com/2682073/55492470-d7960a00-5669-11e9-9178-c39b24fdc3a2.PNG)

这张图是系统键盘弹出后或（系统键盘收缩后，页面不回弹）的时候，点击激活alert的按钮，弹出的alert对话框，无法关闭。
![IMG_4114](https://user-images.githubusercontent.com/2682073/55492673-2f347580-566a-11e9-8d9c-2b44fdc83879.PNG)

**Environment**
 - Device: iphone6s
 - Browser: 微信内嵌浏览器
 - Vant Version: 1.6.12

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
参见 https://developers.weixin.qq.com/community/develop/doc/00044ae90742f8c82fb78fcae56800
