### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by Karma1996** [youzan/vant#3089]
**Describe the bug**
引用tabbar组件后，启动项目终端会报错，达不到预期效果。

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/37733288/55495709-1b8c0d80-5670-11e9-95a8-5d1137b15a94.png)

**Environment**
 - Device: Windows 10
 - Browser: Google Chrome
 - Vant Version: 1.6.12

**Reproduce**
![image](https://user-images.githubusercontent.com/37733288/55532333-04850400-56e0-11e9-873a-98f282053163.png)

**Comment by Karma1996** [comment]
源码跟踪：
![Uploading image.png…]()

**Comment by Karma1996** [comment]
![image](https://user-images.githubusercontent.com/37733288/55531969-b02d5480-56de-11e9-90f0-e38e144c4f33.png)
![image](https://user-images.githubusercontent.com/37733288/55532181-87f22580-56df-11e9-8da1-ec24e60638ec.png)

**Comment by chenjiahan** [comment]
跟 this 没有关系，tabbar-item 必须要配合父组件 tabbar 的，请参考文档
