### ISSUE TITLE
`uploader`组件`before-read`和`after-read`中能否将组件的`ref`传回来呢？

### ISSUE THREAD

**Issue by aiyuchen** [youzan/vant#3091]
一组`uploader`组件，需要在回调函数中根据`ref`判断具体来自哪个组件

这个是演示地址
https://jsbin.com/bunamag/edit?html,js,console,output

![image](https://user-images.githubusercontent.com/578141/55537292-72d0c300-56ee-11e9-9191-8dd0524b22a9.png)

**Comment by chenjiahan** [comment]
ref 在命名上会有歧义，后续会在参数里加一个 name 字段

**Comment by chenjiahan** [comment]
已在 1.6.13 版本支持
