### ISSUE TITLE
Collapse IOS 展开闪烁

### ISSUE THREAD

**Issue by scsunyuan** [youzan/vant#3099]
**Describe the bug**
Collapse 在 IOS初次展开会闪烁，安卓测试没有问题
**Screenshots**
闪烁一次无法截图

**Environment**
 - Device: IOS
 - Browser: 微信浏览器（微信版本7.0.3）
 - Vant Version: 1.6.12

**Reproduce**

**Comment by chenjiahan** [comment]
试了下没问题喔，请问是什么机型呢

**Comment by scsunyuan** [comment]
iPhone6 系统版本 12.1.4。 未再次尝试官方示例。初次展开回闪烁。 Collapse嵌套Collapse for循环渲染

**Comment by yuhongda** [comment]
iPhone 5s 9.3 同样展开时有闪烁的问题

**Comment by chenjiahan** [comment]
目测是低版本机型的兼容问题，目前没找到合适的方案去兼容，这个问题应该只影响动画，不影响实际使用，先关闭了
