### ISSUE TITLE
Dialog添加getContainer属性，返回上个界面，再次进入不生效

### ISSUE THREAD

**Issue by Wujianjun92** [youzan/vant#3101]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
引入Dialog组件，使用getContainer属性把它挂载到div上，第一次进入该页面可以正常使用，
返回上一个界面后，再次进入该页面Dialog没有反应。 除非再次手动刷新才可以再次使用。

**Screenshots**
![TIM图片20190408144943](https://user-images.githubusercontent.com/32825948/55703954-9ad16680-5a0d-11e9-9fb6-74a35c9be828.png)
![微信图片_20190408150809](https://user-images.githubusercontent.com/32825948/55704981-37950380-5a10-11e9-9b96-1e11a8a1cdaf.png)

**Environment**
 - Device: PC、手机
 - Browser: Google Chrome 、 微信
 - Vant Version: 1.6.12

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.6.14 版本修复
