### ISSUE TITLE
van-picker @change 方法如何传递选中值和自定义参数?

### ISSUE THREAD

**Issue by chilejiang1024** [youzan/vant#3102]
**你需要的功能是？**
picker @change方法 现在要么是只能传自定义参数, 要么是只能是默认参数. 需要能够既能获得默认参数又能获得自定义参数.

**你期望 API 是什么样的？**
@change="function(picker, values, index, otherParams)"

**Comment by chenjiahan** [comment]
通过 index 可以获取到你想要的参数的

**Comment by chilejiang1024** [comment]
什么意思 ???? 你的意思是在function的实现里用 arguments[1] 来获取 ?
我试的时候获取到的是undefined啊 ...

**Comment by chilejiang1024** [comment]
能不能告知在页面里需要怎么写参数列表?

**Comment by chilejiang1024** [comment]
随便把没有回复明白的的issue关闭, 再追问就不管了, 真好, 别再github上给中国开发者丢人行么??? 真不知道8000多个star是怎么刷来的 .... 既然无力维护, 就干脆把issues区关了多好 ?

**Comment by chenjiahan** [comment]
不想用就别用，我没有义务秒回你的 issue

**Comment by chilejiang1024** [comment]
呦呦呦, 牛逼啊您吶, 你不会的东西, 可以等别人回, 要是没有别人, 就关了issues, 或者删了repo, 在这叫唤啥???
开源到社区, 你当是你家热炕头???

**Comment by chilejiang1024** [comment]
说不明白就close了issue, 牛逼啊 ... 还不想用就别用 ??? 有赞都是你这样的货色么 ???

**Comment by chilejiang1024** [comment]
不想别人用, 就别开源啊, 真是让人头大 .

**Comment by chilejiang1024** [comment]
还秒回, 我都懒得吐槽你, 哪个issue被秒回了??? 就这水平, 还是好好写写你的代码和文档在开源吧... 8000个star里恐怕没有几颗是真实的吧 .

**Comment by koibi2** [comment]
楼上不要吵啊。
我解决了，也许有人需要。

 我遇到了同样的需求：由于页面存在多个 `van-picker` 组件。需要传入一个索引号。

最后我放弃的默认的参数。传入自定义参数，根据 refs 来获取组件的值。
![image](https://user-images.githubusercontent.com/34370367/58615601-0f2dd500-82ee-11e9-8c7f-415173d35847.png)

但感觉用 refs 不是很优雅。允许自定义传参更方便~

**Comment by chilejiang1024** [comment]
昨天又遇到了 van-checkbox 的值 和 v-model绑定的值相反的问题, 在一个线上的项目里, 我也是服了.  checkbox 选中 ,页面上变量值为true, vue data里绑定的变量值为false, 有点强.

**Comment by shen-lan** [comment]
传入自定义参数
```
 @change="(picker, values,index) => {onChange('Start',picker, values,index)}"
```
这个和`vant`无关吧....

**Comment by Fhasghrge** [comment]
`id="{{item.id}}"
 bind:change="onChange"`
可以给每个开关都加上id属性
`onChange(event) { // 开关改变
    const healthinfo = this.data.healths
    healthinfo[event.target.id].checked = !healthinfo[event.target.id].checked
    this.setData({healths: healthinfo})
  },`
在通过**e.target.id**获取到点击开关的是哪一个

**Comment by Fhasghrge** [comment]
可以给每个开关都加上**id属性**
```JavaScript
id="{{item.id}}" 
bind:change="onChange"
```
在通过**e.target.id**获取到点击开关的是哪一个
```
onChange(event) { 
  const healthinfo = this.data.healths 
  healthinfo[event.target.id].checked = !healthinfo[event.target.id].checked 
  this.setData({healths: healthinfo}) },
```
