### ISSUE TITLE
van-swipe轮播的时候页面抖动

### ISSUE THREAD

**Issue by guanweitao** [youzan/vant#3105]
机型vivoY27，版本4.4.4
页面中引用van-swipe的时候，到时候页面抖动

**Comment by guanweitao** [comment]
> 机型vivo，版本4.4.4
> 页面中引用van-swipe的时候，到时候页面抖动

**Comment by chenjiahan** [comment]
具体是什么抖动，能提供视频或 jsfiddle 吗

**Comment by guanweitao** [comment]
> 具体是什么抖动，能提供视频或 jsfiddle 吗

![录屏_20190409_103420](https://user-images.githubusercontent.com/25758249/55771328-3c15f680-5aba-11e9-8ef0-5faba4a654de.gif)

**Comment by chenjiahan** [comment]
看起来是旧机型的渲染问题，暂时没有办法解决噢，先关闭了
