### ISSUE TITLE
关于建议van-address-edit组件的address-info中省市区回显参数的说明

### ISSUE THREAD

**Issue by xiariqingfengshiran** [youzan/vant#3106]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by xiariqingfengshiran** [comment]
按照官方文档的说法，显示初始的信息只需要给province，city，county，三个参数并给定地址字符串即可，但使用中发现必须要加areaCode，并传入对应code，而这点文档并没有做出任何说明。

**Comment by chenjiahan** [comment]
感谢反馈，后续会完善一下文档

**Comment by chenjiahan** [comment]
文档已更新

**Comment by xiariqingfengshiran** [comment]
好的，看到了
