### ISSUE TITLE
vant从1.5.2升级到1.6.13后报错

### ISSUE THREAD

**Issue by superPig20** [youzan/vant#3108]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
我在脚手架上把vant从1.5.2升级到1.6.13后启动vue项目报错，提示我依赖不存在
![TIM截图20190409101057](https://user-images.githubusercontent.com/46433463/55768527-d7ee3500-5aaf-11e9-815a-2e8113de785f.png)
但实际上它不是依赖项，它只是我的vue项目中的某个路由器

**Comment by chenjiahan** [comment]
这个报错看起来和 vant 没有关系，建议排查下是不是其他原因导致的
