### ISSUE TITLE
关于popup和Actionsheet 弹出层 中 再次弹出选择组件 遮罩显示问题 无法覆盖全屏

### ISSUE THREAD

**Issue by tidows** [youzan/vant#3109]
**Describe the bug**

使用 popup和Actionsheet 弹出层 后    再次弹出选择组件 遮罩层的显示 无法全屏，遮罩层只覆盖了第一次弹出popup或者Actionsheet组件，而无法全屏，超过popup或者Actionsheet组件的部分 弹出层会消失掉。

**Screenshots**

图片无法上传

**Environment**

 - Browser: 谷歌浏览器
 - Vant Version: 1.6.13

**Comment by chenjiahan** [comment]
能否提供一下 jsfiddle 呢，看起来是用法问题

**Comment by DivXPro** [comment]
如果底层的长度超过全屏长度， 新弹出的层就无法覆盖底层
