### ISSUE TITLE
启用本地字体图标后，会先尝试加载网络图标造成加载延迟

### ISSUE THREAD

**Issue by lenisleopold** [youzan/vant#3112]
**Describe the bug**
问题：启用本地字体图标后，依然会先尝试加载网络图标，
这样就有两种情况，一：如果没有网络连接，本地图标会被立即加载。
二：网络不畅的情况下，网络字体请求会一直处于pending的状态，大概四十秒之后处于failed状态时，才会加载出本地图标。

**Screenshots**
![360截图18270622095140](https://user-images.githubusercontent.com/23413798/55773486-543e4380-5ac3-11e9-9abb-4ef94c856cf1.jpg)

建议使用本地图标的情况下，不在尝试请求网络图标。

**Comment by chenjiahan** [comment]
按理说不会加载网络图标的呢，你是把 icon.css 和 local.css 分开两个文件加载的吗

**Comment by lenisleopold** [comment]
我又验证了一下，还是会加载网络图标的，我的项目结构是这样的
project/
  /build
  /node_modules
  /public
  /src
    /main.js
    /router.js
    /store.js
    /App.vue
  
引入本地图标的方式是按照文档 在main.js的第一行 import 'vant/lib/icon/local.css';

------------------------------------------------------------------------------------------------
但是我找到了一个解决办法。
找到项目的\node_modules\vant\es\icon\index.less，格式化这个文件，把最上面的@font-face{}给注释掉。就是这里面的定义的url，即使网络不通也会首先请求网络字体。注释之后，即使网络不通的情况下，也可以直接加载出本地图标。但是请注意，如果这样做了，就不会去请求网络图标了，必须启动本地图标， 也就是import 'vant/lib/icon/local.css'; 

// @font-face {
//     font-style: normal;
//     font-weight: 400;
//     font-family: 'vant-icon';
//     src: url(https://img.yzcdn.cn/vant/vant-icon-29f643.woff2) format('woff2'), url(https://img.yzcdn.cn/vant/vant-icon-29f643.woff) format('woff'), url(https://img.yzcdn.cn/vant/vant-icon-29f643.ttf) format('truetype')
// }

**Comment by vkboo** [comment]
![image](https://user-images.githubusercontent.com/17156560/87925496-f3b5f880-cab2-11ea-80ef-b79c0b3d6a8c.png)
加了`import 'vant/lib/icon/local.css';`之后，字体的网络请求依然存在。
