### ISSUE TITLE
tag组件 移动端文字没有垂直居中

### ISSUE THREAD

**Issue by amosforli** [youzan/vant#3113]
![image](https://user-images.githubusercontent.com/11626253/55784692-a68f5c80-5ae3-11e9-8692-67495a540b54.png)
tag组件在pc端显示基本正常  小尺寸的在手机端 （微信）没有垂直居中

**Comment by chenjiahan** [comment]
安卓浏览器的问题，暂时不是很好解决，可以用中尺寸的标签，或者参考这篇文章：

https://github.com/o2team/H5Skills/issues/4
