### ISSUE TITLE
 [Bug Report] ImagePreview 图片预览 图片放大的时候比原图模糊

### ISSUE THREAD

**Issue by jianyudahaoren** [youzan/vant#3116]
ImagePreview 图片预览组件，当图片放大的时候图片会失真，且放大比例会有个最大限制，图片放大的最大尺寸达不到原图尺寸。

**Comment by chenjiahan** [comment]
1. ImagePreview 缩放是基于 scale 来做的，理论上对图片质量没啥影响喔
2. 最大限制后续会加个配置参数，目前最大是 3 倍

**Comment by chenjiahan** [comment]
已在 1.6.14 版本支持配置缩放参数

**Comment by dududa2015** [comment]
我也遇到了放大模糊的情况，实际上原图是清楚的。大神有空用一张长图试试吧，感觉先被压缩了再放大的，失真严重！

**Comment by chenjiahan** [comment]
@dududa2015 这个问题在此 issue 中跟进：https://github.com/youzan/vant/issues/4553
