### ISSUE TITLE
Stepper步进器default-value属性 无法绑定动态值

### ISSUE THREAD

**Issue by futurehu** [youzan/vant#3117]
**Describe the bug**
Stepper步进器default-value属性 无法绑定动态值 

**Screenshots**
![image](https://user-images.githubusercontent.com/38276710/55806343-a65a8580-5b12-11e9-86bc-50cb9f3c639c.png)
![image](https://user-images.githubusercontent.com/38276710/55806816-9c855200-5b13-11e9-941f-9cfcb40fd3fe.png)

![image](https://user-images.githubusercontent.com/38276710/55806395-c0946380-5b12-11e9-84c8-b2b9829d41e1.png) 
![image](https://user-images.githubusercontent.com/38276710/55806738-71026780-5b13-11e9-88b9-aa5ea9c964d2.png)

**Environment**
 - Device: 移动端
 - Browser: Chrome 73
 - Vant Version: 1.6.13

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
default-value 是首次初始化时的默认值，不能动态绑定的，如果需要动态变化，直接修改 v-model 绑定的变量即可
