### ISSUE TITLE
Swipe轮播组件 通过 ref 获取swipe 实例并调用实例方法时报错

### ISSUE THREAD

**Issue by arronlovepudding** [youzan/vant#3120]
**Describe the bug**
swiper组件通过ref获取dom元素，使用swipeTo方法报错。

**Screenshots**
![image](https://user-images.githubusercontent.com/14148582/55854179-7b197a00-5b96-11e9-979f-f22f9c978df8.png)

**Environment**
 - Browser: Chrome
 - Vant Version:  1.6.12

**Reproduce**
通过 ref 可以获取到 swipe 实例并调用实例方法时报错：

![image](https://user-images.githubusercontent.com/14148582/55854268-c469c980-5b96-11e9-8af8-ee390d762a77.png)

**Comment by futurehu** [comment]
![image](https://user-images.githubusercontent.com/38276710/55854884-8bcaef80-5b98-11e9-810d-8aad5cc78aa8.png)
我的可以啊

**Comment by arronlovepudding** [comment]
> ![image](https://user-images.githubusercontent.com/38276710/55854884-8bcaef80-5b98-11e9-810d-8aad5cc78aa8.png)
> 我的可以啊
我这边还是一直报：
Invalid prop: type check failed for prop "initialSwipe". Expected Number with value 0, got String with value "0".

**Comment by futurehu** [comment]
> > ![image](https://user-images.githubusercontent.com/38276710/55854884-8bcaef80-5b98-11e9-810d-8aad5cc78aa8.png)
> > 我的可以啊
> > 我这边还是一直报：
> > Invalid prop: type check failed for prop "initialSwipe". Expected Number with value 0, got String with value "0".

数据类型错了  传一个数字类型

**Comment by futurehu** [comment]
> > ![image](https://user-images.githubusercontent.com/38276710/55854884-8bcaef80-5b98-11e9-810d-8aad5cc78aa8.png)
> > 我的可以啊
> > 我这边还是一直报：
> > Invalid prop: type check failed for prop "initialSwipe". Expected Number with value 0, got String with value "0".

加我qq吧

**Comment by arronlovepudding** [comment]
> > > ![image](https://user-images.githubusercontent.com/38276710/55854884-8bcaef80-5b98-11e9-810d-8aad5cc78aa8.png)
> > > 我的可以啊
> > > 我这边还是一直报：
> > > Invalid prop: type check failed for prop "initialSwipe". Expected Number with value 0, got String with value "0".
> 
> 加我qq吧
qq多少呀

**Comment by futurehu** [comment]
> > > > ![image](https://user-images.githubusercontent.com/38276710/55854884-8bcaef80-5b98-11e9-810d-8aad5cc78aa8.png)
> > > > 我的可以啊
> > > > 我这边还是一直报：
> > > > Invalid prop: type check failed for prop "initialSwipe". Expected Number with value 0, got String with value "0".
> > 
> > 
> > 加我qq吧
> > qq多少呀

912826754

**Comment by arronlovepudding** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/38276710/55854884-8bcaef80-5b98-11e9-810d-8aad5cc78aa8.png)
> > > > > 我的可以啊
> > > > > 我这边还是一直报：
> > > > > Invalid prop: type check failed for prop "initialSwipe". Expected Number with value 0, got String with value "0".
> > > 
> > > 
> > > 加我qq吧
> > > qq多少呀
> 
> 912826754

刚解决了！！！thanks～
