### ISSUE TITLE
picker只能点击，不能滑动

### ISSUE THREAD

**Issue by 944zhang** [youzan/vant#3121]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
vue-template-compiler和vue都已经升级到2.6.10。
打开vant官方demo，基础组件->popup弹出层->底部弹出，picker只能点击，不能滑动。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: ios 10.3.3
 - Browser: 微信
 - Vant Version: 1.6.5

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by leemoncn** [comment]
你需要从后台杀死微信程序（或者safari），然后再打开，就好了。

**Comment by 944zhang** [comment]
> 你需要从后台杀死微信程序（或者safari），然后再打开，就好了。

不行

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/3015
