### ISSUE TITLE
徽标组件info设置为0的时候可以不显示吗

### ISSUE THREAD

**Issue by aiyuchen** [youzan/vant#3127]
包含有icon，badge、tabbar这几个组件，目前是这样的
![image](https://user-images.githubusercontent.com/578141/55865192-75c92900-5bb0-11e9-8943-dea223386105.png)

设置`info`为0的时候是这样的
![image](https://user-images.githubusercontent.com/578141/55865235-87123580-5bb0-11e9-89af-8177019a13b4.png)

如果要做到0不显示的话，目前要做`if`判断，如下
```
<van-icon v-if="num > 0" name="chat" :info="num" />
<van-icon v-else name="chat" />
```

希望能够是当设置的info值为0的时候，默认不展示

**Comment by chenjiahan** [comment]
0 是要展示的喔，如果不想展示的话，把 0 转成 null 就行
