### ISSUE TITLE
picker 不能rem适配

### ISSUE THREAD

**Issue by dhx1213** [youzan/vant#3128]
picker 不能rem适配

**Comment by chenjiahan** [comment]
暂无计划支持喔

**Comment by cosyUI** [comment]
可以的话，希望能给一个临时的方案，可以在组件props中添加一个单位，这样起码我们也能可以自定义下单位。正常情况换算比例可以确定，我们只要传送换算好的尺寸以及自定义的单位，这样也能临时解决这个问题。

**Comment by chenjiahan** [comment]
后续看下能否支持

**Comment by chenjiahan** [comment]
由于 Picker 内部需要通过运算计算偏移量，暂时无法支持 rem 单位（rem 的基准值是未知的），建议自行转换
