### ISSUE TITLE
【ios11】better-scroll内使用swiper导致页面闪烁

### ISSUE THREAD

**Issue by yipjianbo** [youzan/vant#3129]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
iphone7 ios11.x 
better-scroll version 1.12.4
页面使用better-scroll组件布局时，banner初始化swiper，当banner图片多于1张时(触发loop？)，BS顶部和底部的回弹动画，将导致页面闪烁

**Environment**
 - Device: iphone7 ios11.x 
 - Browser: safari
 - Vant Version: 1.6.9

https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
你好，Vant 暂时没有兼容 better-scroll 的计划呢，建议到 better-scroll 仓库下看看是否有解决方案
