### ISSUE TITLE
switch 组件

### ISSUE THREAD

**Issue by dengshenkk** [youzan/vant#3132]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
switch 不支持写文字吗?
**Describe the solution you'd like**
希望增加一个slot 开放给用户自由
**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.
<vant-switch>text</vant-switch>

**Comment by dengshenkk** [comment]
`<vant-switch>text</vant-switch>`

**Comment by chenjiahan** [comment]
暂无计划支持喔，直接写在同一层级就行
