### ISSUE TITLE
List 组件上拉加载更多自动执行更多方法？

### ISSUE THREAD

**Issue by xyan988** [youzan/vant#3138]
List 组件上拉加载更多自动执行加载更多方法？

运行项目后，自动执行了 所有加载更多方法
<img width="720" alt="image" src="https://user-images.githubusercontent.com/12760375/56009931-2c91ea00-5d14-11e9-8c71-f8e0dfa40488.png">图片为初始化页面时，page 的加载次数，按理说不是应该只执行一次嘛

**Environment**
 - Device:  Mac  os
 - Browser: google 手机模式
 - Vant Version:  1.6.13

**Comment by xyan988** [comment]
我貌似找到区别了，我的页面布局是这样的
<img width="317" alt="image" src="https://user-images.githubusercontent.com/12760375/56010502-69f77700-5d16-11e9-892b-787ebab26759.png">
是不是不支持这种布局 ？

**Comment by chenjiahan** [comment]
只要滚动条的位置触达了底部，就会触发加载，可能是你每次加载的内容太少了，所以会触发多次 load

**Comment by HighWarmModel** [comment]
我的也是自动连续触发了 明明数据已经超过一屏幕的

**Comment by Licoy** [comment]
我也是，数据已经上千条了 但是还是一直在触发自动加载 list内部嵌套的van-col
