### ISSUE TITLE
在安卓4.0，IOS9.0上自带浏览器打不开官方文档

### ISSUE THREAD

**Issue by longting** [youzan/vant#3139]
**Describe the bug**
在`安卓4.0`，`IOS9.0`上自带浏览器打不开官方文档。  
安卓的我截图放下面了，至于IOS的，效果和安卓一样打不开
  
**Screenshots**  
![image](https://user-images.githubusercontent.com/5129611/56026485-d25e4c80-5d46-11e9-8196-bd5fabb56fd0.png)  

**Environment**  
 - Device: 安卓4.4  
 - Browser: 系统自带浏览器  
 - Vant Version: 最新版，估计任何版本都不行！  

**Reproduce**  
1. 打开系统自带浏览器  
2. 输入`https://youzan.github.io/vant/mobile.html#/zh-CN/`   
3. 回车

**Comment by chenjiahan** [comment]
你好，低版本浏览器需要通过 babel polyfill 兼容的（主要是 Promose），官方文档没有引入 polyfill，所以在低版本浏览器打不开
