### ISSUE TITLE
Dialog组件在iPhone7(iOS 12.1.4)微信中按钮可点击区域与显示区域不一致

### ISSUE THREAD

**Issue by dongnaebi** [youzan/vant#3141]
### 问题描述：
点按钮没反应，要点按钮上方大概20px的区域（红框内）才能正确触发
![image](https://user-images.githubusercontent.com/6902417/56032252-45ba8b00-5d54-11e9-92b0-6e0363727fde.png)

### 复现
目前只在iPhone7(iOS 12.1.4)微信中能偶然复现，我这边也没有更多的设备和系统版本来复现

### 我推测
这个问题让我想起iOS较老版本input在fixed元素中光标错位的问题，所以我推测是不是因为按钮使用的是button标签，属于表单元素，和之前的input错位是一个问题？

如果有人遇到过，望提供解决思路

**Comment by chenjiahan** [comment]
参见 https://developers.weixin.qq.com/community/develop/doc/00044ae90742f8c82fb78fcae56800
