### ISSUE TITLE
[Popup弹出层] 组件报错

### ISSUE THREAD

**Issue by lszh001** [youzan/vant#3142]
[Popup弹出层]的内容超出父级最大高度,在上下滑动时会报错,希望下个版本可以修正.
![111](https://user-images.githubusercontent.com/45568614/56077646-45cc9080-5e11-11e9-9297-41f38a1c692e.png)
![222](https://user-images.githubusercontent.com/45568614/56077647-4bc27180-5e11-11e9-9631-14eadc470720.png)

已解决:
找到报错位置，在执行e.preventDefault();e.stopPropagation();的if语句中加上一个条件判断 e.cancelable.

参考:
https://blog.csdn.net/cyx2350356668/article/details/88556821

**Comment by lszh001** [comment]
![333](https://user-images.githubusercontent.com/45568614/56077774-b2945a80-5e12-11e9-9650-2c1d77143c48.png)

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会加上

**Comment by chenjiahan** [comment]
已在 1.6.15 版本修复
