### ISSUE TITLE
如果Toast先弹出过，因为z-indx计算，会被后使用的popup组件遮住，如果在popup里面需要使用Toast的话，就会被遮住了，这该如何解决？

### ISSUE THREAD

**Issue by cao1987** [youzan/vant#3145]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
弹层的逻辑是这样的：后出现的弹层遮住先出现的弹层，每次弹出的时候 zIndex 都会增加，Toast 和 Popup 都属于弹层。

不过在目前版本，如果上一个 Toast 还未消失，再次调用 Toast 是不会增加 zIndex 的，你可以手动 clear 一下之前弹出的 Toast。

下个版本会看下能否优化 Toast zIndex 的逻辑，每次调用时都增加

**Comment by chenjiahan** [comment]
已在 1.6.15 版本修复

**Comment by umeitime** [comment]
> 已在 1.6.15 版本修复

没有啊，我用的都是最新2.10.12，还是会出现这个问题，如果第一次打开popup，notify正常，如果关闭以后，第二次打开popup，notify就在下面了。

**Comment by xintianyou** [comment]
> 已在 1.6.15 版本修复

^2.12.6 还是会出现这个问题，先打开Popup，在Popup中的点击事件调用Toast，此时Toast会被Popup遮挡
