### ISSUE TITLE
Sku组件里面添加message输入框，点击输入框的时候，页面不会自动上弹

### ISSUE THREAD

**Issue by laravelup** [youzan/vant#3146]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
Sku组件里面添加message输入框，点击输入框的时候，页面不会自动上弹
**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: ios
 - Browser: 微信，safari
 - Vant Version: 1.6.12

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
你好，页面是否上弹是浏览器本身的行为，理论上都会上弹的，如果没上弹那就是浏览器的问题了
我用 iOS 12 的 safari 试了下是 ok 的
