### ISSUE TITLE
提个临时方案，针对Picker这类组件用到行内样式的rem兼容问题

### ISSUE THREAD

**Issue by cosyUI** [youzan/vant#3156]
如果可以的话，组件中再多提供一个可以自定义单位的props，现在有提供自定义高度的，同时再多提供一个自定义单位，这样我们可以手动传入一个换算好的数据以及单位。

**Comment by chenjiahan** [comment]
这个 issue 里面已经回答过了，https://github.com/youzan/vant/issues/3128，不是单位的问题，Picker 是要对高度进行计算的，带单位的高度无法进行数字运算

**Comment by cosyUI** [comment]
嗯，刚刚实践了下，没有考虑到picker滚动时的计算，组件中onTouchMove中的event.touches这块获取到的还是以px进行计算的，在不知道rem基准值的时候确实不好转换

**Comment by chenjiahan** [comment]
是滴，issue 先关闭咯
