### ISSUE TITLE
list 组件与 PullRefresh 组件结合使用时会一直执行 onLoad 方法

### ISSUE THREAD

**Issue by zgh0711** [youzan/vant#3158]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
如题，在 list 组件外嵌套 PullRefreshList 组件，只要一滚动就会执行 onLoad 方法（并没有滚动到屏幕底部），而且 onLoad 方法会一直执行，直到全部数据加载完毕，finished 设为 true 才会停止。
还有一个现象就是当我在页面上做 tab 切换时（自己写的 tab 组件，非 vant 的 tab 组件），每次切换了 tab 之后也会一直执行 onLoad 方法（没有滚动屏幕）。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.6.13

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.

**Comment by chenjiahan** [comment]
官方示例就是在 PullRefresh 里嵌套的 List，没有问题呢，你的情况能否提供一下 jsfiddle

**Comment by heli5277** [comment]
在切换tab的时候把滚动条拉到顶部就不会出现无限加载了
