### ISSUE TITLE
按钮的box-shadow在IOS问题 

### ISSUE THREAD

**Issue by sym134** [youzan/vant#3159]
我在按钮上增加了箱阴影属性，安卓没有任何问题，但是在IOS回上退就会有问题
上一页的阴影回退以后依然在，只是阴影在，开发调试页看不到，但是刷新就没了

![image](https://user-images.githubusercontent.com/32946251/56178932-9a9d2080-6036-11e9-973c-5105c8413f21.png)

返回以后上一页的按钮的阴影依然在但是通过调试看不到任何标签样式，刷星以后就没了
![image](https://user-images.githubusercontent.com/32946251/56178939-a12b9800-6036-11e9-81ef-12c2c83e0658.png)

**Comment by chenjiahan** [comment]
你好，看起来是浏览器的渲染问题，你可以把 van-button 换成原生的 button 试下是不是也有同样的问题
