### ISSUE TITLE
List 组件不能触发@load事件

### ISSUE THREAD

**Issue by MaMaFish** [youzan/vant#3160]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
页面不能自动触发@load事件，一直显示加载中的提示。
初始化的时候设置immediate-check为False, 点击搜索按钮手动请求onLoad方法能够获取一次数据，但不能再自动触发onLoad方法了。
新手求助，Thanks in advance. : )
**Screenshots**
Add screenshots to help explain your problem.
![Screen Shot 2019-04-16 at 11 12 25](https://user-images.githubusercontent.com/15073228/56179881-dbe2ff80-6039-11e9-8f99-d8174ca879b7.png)
![Screen Shot 2019-04-16 at 11 12 53](https://user-images.githubusercontent.com/15073228/56179888-e1404a00-6039-11e9-8a84-4d0f6a532af7.png)
![Screen Shot 2019-04-16 at 11 13 24](https://user-images.githubusercontent.com/15073228/56179891-e3a2a400-6039-11e9-81ce-c88092dfaa31.png)

*
*Environment**
 - Device: Chrome 模拟器
 - Browser: Chrome
 - Vant Version: 1.6.14

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
load 在页面滚动的时候才会触发检测，如果你的数据量太少不足一屏，建议增加单次请求的数据条数，保证请求后页面内容超过一屏的范围

**Comment by MaMaFish** [comment]
有超过一屏的数据呢

**Comment by MaMaFish** [comment]
问题解决了，谢谢
