### ISSUE TITLE
编辑地址兼容性问题

### ISSUE THREAD

**Issue by PPPenny** [youzan/vant#3161]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
编辑地址兼容性问题

**Screenshots**
![image](https://user-images.githubusercontent.com/20984729/56193507-5e33e980-6063-11e9-8f16-9448221b1ea3.png)

**Environment**
 - Device: ios 11
 - Browser: 微信内部
 - Vant Version: 1.5.7

**Reproduce**
无

**Comment by chenjiahan** [comment]
Picker 里有使用 flex 布局，建议看下你的 autoprefixer 配置是否正确，如果配置的浏览器不对，会把 flex 兼容语法移除的

**Comment by PPPenny** [comment]
不是picker哟，是整个组件呢~

**Comment by PPPenny** [comment]
![image](https://user-images.githubusercontent.com/20984729/56277152-5f821680-6136-11e9-9f2f-90613163d186.png)
1：js里面的样式，这种的会加兼容样式吗？
2：优化意见:用户输入，键盘弹起来，点击picker，用户的键盘还没有缩回去的时候，picker弹出来哒

**Comment by chenjiahan** [comment]
第一个问题，Vue 会自动补全前缀
第二个，没看懂。。

**Comment by PPPenny** [comment]
用户输入，当使用中文输入法时，
![image](https://user-images.githubusercontent.com/20984729/56544206-5bc31980-65a6-11e9-976f-081d8fe48280.png)
，这种情况下点击picker，safari会先执行一次确认，这个时候页面还是聚焦在原来的输入框上,点击了原本为input的地区表单唤起地址选择组件，safari会判断仍然在输入状态，所以就会出现组件被软键盘遮盖的现象。就是这个优化，不知是否描述清楚？

**Comment by chenjiahan** [comment]
@PPPenny 明白你的意思了，不过我用 safari 试了是 ok 的呢，因为点击事件默认会让系统键盘收起，如果没收起可能是第三方输入法的问题

**Comment by PPPenny** [comment]
我觉得一个很神奇的问题，我这边用地址选择器，本人手机，6，ios10.0.1,遇到过这样的情景：进入页面，不能滚动选择省市，然后等一会儿过后，又能滚动了了！！！还有就是直接杀掉微信进程，再进来，也能解决滚动不了的问题。。（猜测是不是苹果6运行内存太小，里面有什么东西耗用内存太多引起的呢？）
