### ISSUE TITLE
【bug】Tag 组件在微信内部浏览器打开后，下边框不显示，亲测好几款手机了

### ISSUE THREAD

**Issue by sunjiaming** [youzan/vant#3162]
**Describe the   ##bug**
Tag 组件在微信内部浏览器打开后，下边框不显示，亲测好几款手机了

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
能否打开官方文档并提供一些截图呢

**Comment by sunjiaming** [comment]
<img src='http://static.weitui.online/2.png'>

**Comment by sunjiaming** [comment]
在手机自带浏览器里打开都一切正常，但是到微信浏览器打开就不行
