### ISSUE TITLE
Actionsheet希望有纯JS的使用方式

### ISSUE THREAD

**Issue by xxyuze** [youzan/vant#3163]
**What problem does this feature solve?**
希望有纯JS的方式使用Actionsheet，这样更容易使用动态变更的actions；

**Describe the solution you'd like**
在列表中使用弹出菜单的时候，不同的列表项需要显示不同数量的actions，弹出菜单和action点击是两个事件，这个时候需要保存上下文，写起来很繁杂。
希望可以用纯js呼出Actionsheet，就像Dialog一样。

**What does the proposed API look like?**
`
displayActionSheet(title: string, cancelText: string, actions: string[]): Promise<string>;
`

**Comment by chenjiahan** [comment]
暂无计划支持喔，ActionSheet 的使用频次没有 Dialog 那么高，不是很有必要做成函数式调用

**Comment by xxyuze** [comment]
现在的ActionSheet Api，在列表中触发非常难用，希望改进
