### ISSUE TITLE
Tabs使用的bug

### ISSUE THREAD

**Issue by Darcy-WYG** [youzan/vant#3164]
**Describe the bug**
使用jQuery load方式加载html,Tabs在chrome下会出现bug，firefox下不会

**Screenshots**
![image](https://user-images.githubusercontent.com/25013401/56256972-5cb6ff80-60fd-11e9-89c2-8299e2133f3d.png)

**Environment**
 - chrome: 73.0.3683.75
   firefox: 66.0.3
 - Vant Version: 1.6.14

**Reproduce**

在其他页面使用jQuery的load方法加载index.html
$("#div").load("./dist/index.html");
1、使用chrome首次打开页面
van-tabs__line出会现位置跟长度不匹配的异常情况
2、使用firefox未出现此异常

**Comment by chenjiahan** [comment]
能否提供一下 jsfiddle 呢，目前没遇到过用 jQuery 的场景。。
