### ISSUE TITLE
请问一下List组件滚动的问题

### ISSUE THREAD

**Issue by qhhuang** [youzan/vant#3165]
demo中的List滚动时连着导航栏一起滚动的
自己项目中手机上滚动时,手指离开屏幕后没有弹性滚动 不会接着滚动了
请问下这个是List组件没有的功能 需要自己实现的吗?

**Comment by chenjiahan** [comment]
你的疑问是局部滚动的时候如何实现弹性滚动吗，在滚动容器上添加一行样式即可

```css
-webkit-overflow-scrolling: touch;
```
