### ISSUE TITLE
icon 本地样式无效，仍然引用cdn资源

### ISSUE THREAD

**Issue by marsal1212** [youzan/vant#3166]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

**Describe the bug**
A clear description of what the bug is.
全局引入vant，仍然请求https://img.yzcdn.cn/vant/vant-icon-29f643.woff2

**Screenshots**
Add screenshots to help explain your problem.
引入代码：

`import Vant from 'vant';`
`import 'vant/lib/index.less';`
`Vue.use(Vant);`
`import 'vant/lib/icon/local.css';`

![image](https://user-images.githubusercontent.com/20449902/56265906-71a38b00-611d-11e9-84c3-1381d38dac54.png)

**Environment**
 - Device:  mac
 - Browser:  chrome
 - Vant Version: 1.6.14

**Comment by marsal1212** [comment]
发现这个问题之后，已经删除yarn.lock, vant ,重新install。

**Comment by bolechen** [comment]
先 import 再 use 吧，我这里正常

**Comment by marsal1212** [comment]
显示正常。但是仍会加载https://img.yzcdn.cn/vant/vant-icon-29f643.woff2，这个远程文件。在hybird app 中有些机型加载不了这个文件。图标就显示不出来。

**Comment by chenjiahan** [comment]
未能复现这个问题，能否给个复现问题的仓库呢
