### ISSUE TITLE
van-popup的closeOnClickOverlay 设置无效

### ISSUE THREAD

**Issue by shiyuegongsui** [youzan/vant#317]
CDN直接引入vant使用，
van-popup的closeOnClickOverlay 设置无效， 都会直接关闭弹窗

DEMO:https://jsfiddle.net/gu4ho7hh/4/

**Comment by chenjiahan** [comment]
Vue 语法规定，使用 HTML 模板时，需要使用中短线分割，而不是驼峰，所以属性名要携程 close-on-click-overlay

**Comment by shiyuegongsui** [comment]
@chenjiahan 感谢回复。
 希望在DEMO中也能加上close-on-click-overlay的使用案例, 会更加清晰，以免其他人遇到同样问题。

**Comment by chenjiahan** [comment]
好的，我们后续会在文档中标明
