### ISSUE TITLE
**Environment** Circle 环形进度条在手机上的适配问题，两个环形会分离。

### ISSUE THREAD

**Issue by lvlvlv1** [youzan/vant#3170]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by lvlvlv1** [comment]
我现在用的是最新的  ^1.6.4

**Comment by lvlvlv1** [comment]
@chenjiahan 我现在用的是最新的 ^1.6.4

**Comment by chenjiahan** [comment]
是否使用了 rem 布局，如果是，请参考 https://github.com/youzan/vant/issues/1948
如果未使用，能否提供下机型和截图

**Comment by lvlvlv1** [comment]
> 是否使用了 rem 布局，如果是，请参考 #1948
> 如果未使用，能否提供下机型和截图

是使用了rem布局，问题已经解决，感谢 #1948。

**Comment by chenjiahan** [comment]
好的👌

**Comment by lvlvlv1** [comment]
粗暴的方式  全局css里面
.van-circle__layer{
  transform-origin: 530PX 530PX;
  -webkit-transform-origin: 530PX 530PX;
}
大写PX不会被rem同化
