### ISSUE TITLE
IOS 微信上input,textarea,select在输入后部分机型点击错位

### ISSUE THREAD

**Issue by zhangfei8080** [youzan/vant#3178]
IOS 微信上input,textarea,select在输入后部分机型点击错位
能不能修复一下
或者增加全局的事件绑定接口,这样方便开发者不用在每个上面添加事件

**Comment by KevinMaHoTung** [comment]
same

**Comment by KevinMaHoTung** [comment]
help me

**Comment by zpedku** [comment]
same problems

**Comment by chenjiahan** [comment]
问题原因见：https://developers.weixin.qq.com/community/develop/doc/00044ae90742f8c82fb78fcae56800

近期会看下怎么在 Vant 内做兼容

**Comment by chenjiahan** [comment]
下个版本会在 Field 组件里增加兼容代码

**Comment by chenjiahan** [comment]
已在 1.6.16 版本修复
