### ISSUE TITLE
NumberKeyboard 数字键盘左上角留一个自定义的按钮

### ISSUE THREAD

**Issue by diandian654** [youzan/vant#3179]
**What problem does this feature solve?**
现在的NumberKeyboard 数字键盘，左上角是空的，添加一个用户自定义的按钮，方便用户自定义按钮和事件。
**Describe the solution you'd like**
在NumberKeyboard 数字键盘左上角添加一个自定义按钮。

**What does the proposed API look like?**

consumer-button-text | 自定义按钮文字

**Comment by chenjiahan** [comment]
下个版本会加个插槽

**Comment by chenjiahan** [comment]
已在 1.6.16 版本支持
