### ISSUE TITLE
希望给search组件加上focus方法

### ISSUE THREAD

**Issue by liuruidong1994** [youzan/vant#3181]
希望给search组件加上focus方法，可以方便在父组件中主动调用

**Comment by liuruidong1994** [comment]
已经是继承自field组件了，顺便继承一下field组件的focus方法吧，谢谢了

**Comment by chenjiahan** [comment]
文档里有写，Search 默认支持 Input 标签所有的原生事件，如 focus、blur、keypress 等

**Comment by liuruidong1994** [comment]
不是onFocus事件，是focus方法。手动主动聚焦输入框

**Comment by chenjiahan** [comment]
噢噢，

**Comment by chenjiahan** [comment]
由于 Search 组件是函数式组件，Vue 目前不支持函数式组件通过 ref 获取到组件实例（函数式组件没有实例），所以没有办法像 Field 一样提供 focus 方法。

建议先通过 querySelector 进行 DOM 操作来触发，等 Vue 3 出来后我们会调整这部分的实现
