### ISSUE TITLE
Steps无法自定义icon

### ISSUE THREAD

**Issue by lbl596038980** [youzan/vant#3182]
**Describe the bug**
Steps无法自定义icon，也无法通过class修改样式

**Screenshots**
![深度截图_选择区域_20190420101211](https://user-images.githubusercontent.com/37288019/56450121-38556000-6355-11e9-8507-03c3d1b349e7.png)
![深度截图_选择区域_20190420101223](https://user-images.githubusercontent.com/37288019/56450122-38556000-6355-11e9-829d-55a0e0ad0d9a.png)

**Environment**
 - Device: win10、deepin
 - Browser: chrome 版本 73.0.3683.86（正式版本） （64 位）、微信内置浏览器
 - Vant Version: 1.6.5

**Comment by chenjiahan** [comment]
你好，目前文档中提供的 icon 插槽是指顶部状态栏的图标，文档描述不是很清晰，后面会优化下

还有下个版本会支持单个步骤的 icon 插槽，应该能满足你的需求

**Comment by chenjiahan** [comment]
已在 1.6.16 版本支持

**Comment by benbenyao** [comment]
请问有没有使用案例？初学表示不会用，没效果。

**Comment by lbl596038980** [comment]
> 我翻看了源码，只能设置steps的icon，step的icon不能设置？

现在step的自定义icon的slot名称改为active-icon

**Comment by benbenyao** [comment]
这个，我试了下，是激活的节点设置的？其余的好像不能自定义？我其实想把每个点点都换成一个图片。

**Comment by lbl596038980** [comment]
> 这个，我试了下，是激活的节点设置的？其余的好像不能自定义？我其实想把每个点点都换成一个图片。

这个我也没试过，按理来说是可以的，你可以尝试一下

**Comment by benbenyao** [comment]
我再研究下，感觉比较难，slot不知道行不行，我看到真正生成的那个点是个circle的class。

**Comment by lbl596038980** [comment]
> 我再研究下，感觉比较难，slot不知道行不行，我看到真正生成的那个点是个circle的class。



> 已在 1.6.16 版本支持

大佬，能否自定义每个未选中step的icon

**Comment by chenjiahan** [comment]
@lbl596038980 目前还不支持喔，后续会加上

**Comment by wananzys** [comment]
> @lbl596038980 目前还不支持喔，后续会加上

每个step现在的版本还是不支持自定义图标吗? 我看文档上可以, 但是实现不了

**Comment by YangFeiLiang9836** [comment]
<template #active-icon>
    <img src="~images/zhuanxiu/step-icon.png" alt="">
</template>

**Comment by YangFeiLiang9836** [comment]
<template #active-icon>
  <img src="~images/zhuanxiu/step-icon.png" alt="">
</template>

**Comment by YangFeiLiang9836** [comment]
为什么这样写仍然显示不了
<template #active-icon>
  <img src="~images/zhuanxiu/step-icon.png" alt="">
</template>

**Comment by YangFeiLiang9836** [comment]
![微信截图_20200628104837](https://user-images.githubusercontent.com/45174648/85936395-f5195880-b92c-11ea-9c37-fbebf67f579c.png)
为什么这样无效啊
