### ISSUE TITLE
van-area change 省市数据不对应

### ISSUE THREAD

**Issue by YLQZ** [youzan/vant#3184]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
change事件返回的数据不对应的bug

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device:  vue 2.0架构
 - Browser: 谷歌浏览器 pc
 - Vant Version: 1.6.14

**Reproduce**
数据为有赞的 Area.json 跳转后的js文件内的数据 使用change事件获取到的value值，省市两级
在移动端弹出此选择界面后 只滑动选择省，界面上市的数据渲染是对的，但是change获取到的数据是错误的，根本不对应，另外初始化刚弹出界面时第一个北京是有一个子项，但是渲染不出来。望解决一下

**Comment by chenjiahan** [comment]
能否一共一下 jsfiddle

**Comment by leehave** [comment]
> 能否提供一下 jsfiddle

![image](https://user-images.githubusercontent.com/16717693/56559189-7069d680-65d3-11e9-8e05-2e468c3f57b3.png)
我也遇到这种问题了

**Comment by chenjiahan** [comment]
已复现此问题，会在下个版本修复

**Comment by chenjiahan** [comment]
已在 1.6.16 版本修复
