### ISSUE TITLE
tabs的title-active-color不生效

### ISSUE THREAD

**Issue by chinabin1993** [youzan/vant#3185]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
`van-tabs`的`title-active-color`以及`title-inactive-color`不起作用

**Screenshots**
![image](https://user-images.githubusercontent.com/25213840/56453781-c9d6c900-6379-11e9-8cae-14c54a90b39f.png)

![image](https://user-images.githubusercontent.com/25213840/56453762-80867980-6379-11e9-9567-a88590fa28f1.png)

**Environment**
 - Device: mac
 - Browser: google
 - Vant Version: 1.6.15

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
你好，我试了下没问题的，请确认下你安装的 vant 版本是大于 1.6.5 的，如果解决不了，请提供一下 jsfiddle
