### ISSUE TITLE
ios机型NumberKeyboard输入错位

### ISSUE THREAD

**Issue by 19950176558** [youzan/vant#3186]
按数字1 跑到了数字4 再去，整体单击事件偏下，头疼
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
跟这个是同个问题，先关闭咯
https://github.com/youzan/vant/issues/3186
