### ISSUE TITLE
ios 机型 用input输入框很难选中

### ISSUE THREAD

**Issue by AAADream** [youzan/vant#3189]

**Comment by chenjiahan** [comment]
不规范的 issue

**Comment by AAADream** [comment]
不规范什么意思
  
  

 

 ------------------ 原始邮件 ------------------
  发件人: "neverland"<notifications@github.com>;
 发送时间: 2019年4月22日(星期一) 晚上7:15
 收件人: "youzan/vant"<vant@noreply.github.com>;
 抄送: "Js_Le"<a1270816841@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [youzan/vant] ios 机型 用input输入框很难选中 (#3189)

 

 
不规范的 issue

**Comment by VenusPP** [comment]
这个应该不是vant的问题 如果有用fastclick，关于input框需要单独处理下。

**Comment by jane900618** [comment]
> 这个应该不是vant的问题 如果有用fastclick，关于input框需要单独处理下。

请问怎么单独处理啊？有文档吗？
