### ISSUE TITLE
Popup嵌套CouponList点击上层蒙版，蒙版消失，couponlist不消失

### ISSUE THREAD

**Issue by pengbo37877** [youzan/vant#3190]
Describe the bug
Popup 嵌套 CouponList ,背景蒙层正常，点击蒙版，最上级背景蒙层消失，CouponList显示

Environment

Device: iphone6s,ios11.2.6
Browser: 微信公众号内
Vant Version: 1.6.15

**Comment by chenjiahan** [comment]
麻烦提供一下 jsfiddle
