### ISSUE TITLE
希望tabs组件增加一个监控左右滑动切换事件

### ISSUE THREAD

**Issue by djinzhong** [youzan/vant#3192]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
在使用tab组件时,当一个页面同时引用两次tabs组件时,且两个tabs组件都开启swipeable = true,那滑动切换时会出现两个选项卡一起切换,希望能控制先后顺序
**Describe the solution you'd like**
增加一个监控左右滑动切换的事件接口,通过具体回调参数控制是否切换
**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.
`<template>
  <van-tabs v-model="active1"
            swipeable
            sticky>
    <van-tab v-for="index in 4"
             :key="index"
             :title="'选项 ' + index">
      <van-tabs v-model="active2"
                swipeable
                sticky>
        <van-tab v-for="index in 4"
                 :key="index"
                 :title="'选项 ' + index">
         <div style="height: 400px">
            内容 {{ index }}
         </div>
        </van-tab>
      </van-tabs>
    </van-tab>
  </van-tabs>
</template>

<script>
import Vue from 'vue'
import { Tab, Tabs } from 'vant'
Vue.use(Tab).use(Tabs)
export default {
  data () {
    return {
      active1: 0,
      active2: 0
    }
  }
}
</script>
`

在切换时,监控左右滑动切换事件,根据当前acive1,active2,首先判断子级选项卡active2是否滑到边界,如果没有就只滑动子选项卡,如果到了边界就滑动父选项卡

**Comment by chenjiahan** [comment]
这个需求建议自行实现呢
大致思路：Tab 的 v-model 可以拆分为 active 属性 和 input 事件，你在 input 事件的回调函数里做判断，按需修改 active 属性即可

**Comment by djinzhong** [comment]
@chenjiahan 那我在inpit事件的回调函数里如何得知是通过头部点击切换的还是滑动切换呢
