### ISSUE TITLE
swiper源码宽高获取错误

### ISSUE THREAD

**Issue by xiaoxintang** [youzan/vant#3200]
**Describe the bug**
A clear description of what the bug is.
源码中自动获取元素高度在第一次的时候可能没有执行，swiper无法获取宽高，swiper-item又存在float:left,元素挤在同一行
**Screenshots**
Add screenshots to help explain your problem.
van-swipe不设置width,height属性，源码中好像自动获取了元素宽高
![image](https://user-images.githubusercontent.com/24927686/56555647-1e6f8380-65c8-11e9-97ad-69b9676931af.png)
横向滚动会出现多个van-swiper-item平分页面展示区域
![image](https://user-images.githubusercontent.com/24927686/56555869-c422f280-65c8-11e9-855e-4b2237cccf55.png)
纵向滚动
swiper-item也会出现在同一行因为宽度获取不正确，还有float:left属性
![image](https://user-images.githubusercontent.com/24927686/56556154-c9cd0800-65c9-11e9-8c08-948cade9cf74.png)

**Environment**
 - Device: mac
 - Browser: 谷歌
 - Vant Version: v1.6.14

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
SwipeItem 的宽度是和 Swipe 保持一致的，默认情况下 Swipe 宽度是 100%，每个 SwipeItem 的宽度也会是一屏幕的宽度。

你的情况应该是布局有问题，建议参考文档的用法再排查下，或者提供一个 jsfiddle

**Comment by xiaoxintang** [comment]
> jsfiddle

 jsfiddle无法访问，我是否可以提供github项目链接
