### ISSUE TITLE
tabs在ios中，内容偶尔会出现空白情况

### ISSUE THREAD

**Issue by LGY-color** [youzan/vant#3202]
**Describe the bug**
如题所示，使用vant中的tabs组件，已经定义好了内容，RN内嵌H5开发中<van-tab></vant-tab>里得内容偶尔会出现空白，全部都不显示，偶尔又不会。想问问是什么原因

**Screenshots**
ios tabs组件

**Environment**
 - Device: ip xr
 - Browser: ios
 - Vant Version: 1.4.6 

**Reproduce**

**Comment by chenjiahan** [comment]
目前没遇到过这个问题呢，建议升级到最新版试下，或者用正常的 WebView 看看有没有问题

**Comment by LiHwsqh** [comment]
可能是safari的bug，试试把列表的position改为relative，z-index设置为大于0 @LGY-color

**Comment by 0123cf** [comment]
你内容白屏  我tabs栏白屏  （偶尔出现，但是我手机从来没遇到  但是测试几天就可以遇到一次）
