### ISSUE TITLE
Flex布局align="bottom", css不匹配

### ISSUE THREAD

**Issue by supremeley** [youzan/vant#3207]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
Flex布局中设置了align="bottom", css不匹配，应该是align-items:flex-end

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/29664653/56637302-e470b100-669d-11e9-8173-afb09f9c2a2c.png)
![image](https://user-images.githubusercontent.com/29664653/56637342-ff432580-669d-11e9-811a-8e19e7309bd7.png)

**Environment**
 - Device: win10
 - Browser:  chrome 版本 73.0.3683.103（正式版本） （64 位）、微信内置浏览器
 - Vant Version:  1.6.13

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
感谢反馈，会在下个版本修复

**Comment by chenjiahan** [comment]
已在 1.6.16 版本修复
