### ISSUE TITLE
1.6.15版本 Dialog组件before-close回调无法触发

### ISSUE THREAD

**Issue by karchinkong** [youzan/vant#3210]
**Describe the bug**
在1.6.15版本中, dialog组件使用@before-close 回调函数中，使用done(false)无法阻止关闭弹窗,仍然会关闭弹窗,并且没有进入关闭前的回调函数

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/16110331/56706114-5997c100-6746-11e9-830c-9b446be14670.png)
![image](https://user-images.githubusercontent.com/16110331/56706123-61effc00-6746-11e9-9949-53d2e7a8cf58.png)

**Environment**
 - Device: window 10
 - Browser: chrome
 - Vant Version: 1.6.15

**Comment by futurehu** [comment]
我也是这个问题

**Comment by futurehu** [comment]
before-close 是一个属性 动态绑定就可以了

**Comment by futurehu** [comment]
before-close 是一个属性 动态绑定就可以了
