### ISSUE TITLE
AddressList 里点击单选按钮的图标，没有触发 select 事件

### ISSUE THREAD

**Issue by jamieYou** [youzan/vant#3213]
**Describe the bug**
AddressList 里点击单选按钮的图标，没有触发 select 事件

**Screenshots**
重现地址
https://codesandbox.io/s/j3385236zy

**Environment**
 - Device: win10
 - Browser: chrome 
 - Vant Version: v1.6.15

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 1.6.16 版本修复
