### ISSUE TITLE
下拉刷新这个功能,可不可以设置内容距离顶部的距离??现在是不管在哪下拉都会刷新

### ISSUE THREAD

**Issue by YingZzz** [youzan/vant#3215]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
只要下拉就会刷新

**Screenshots**
无

**Environment**
-vue
-vant

**Reproduce**
```
<template>
<van-pull-refresh v-model="isLoading" @refresh="reLoad">
        <div class="charging">
            <v-header word="white"><span slot="back" @click="back">返回</span></v-header>
            <div class="content">
                  ....
            </div>
        </div>
    </van-pull-refresh>
<template>
```

**Comment by chenjiahan** [comment]
具体是要实现什么样的效果？

**Comment by YingZzz** [comment]
> 具体是要实现什么样的效果？

列表的时候, 当列表很长的时候,往上拉看下面的内容,当往下拉看上面的内容的时候,下拉就会被触发
按理说,应该是我列表内容到顶部的时候,再往下拉的时候,才会触发刷新

不知道我有没有表达清楚 - 0 -

**Comment by YingZzz** [comment]
现在的情况是只要下拉就刷新页面,
不知道能不能加判断条件,是否列表到了顶部下拉才刷新

**Comment by chenjiahan** [comment]
现在的逻辑就是列表到了顶部才会触发的，你的情况理论上不会遇到呢，能否提供一下 jsfiddle

**Comment by YingZzz** [comment]
我用vant的下拉刷新包裹了better-scroll的滚动,我不知道是不是这个引起的冲突..我现在已经分开来用了...

**Comment by chenjiahan** [comment]
应该 better-scroll 导致的冲突

**Comment by lingsang2** [comment]
> 应该 better-scroll 导致的冲突

我也有同样的问题，没有使用better-scroll

**Comment by lingsang2** [comment]
`.scroller
  van-pull-refresh(
    v-model="scrollRefresh"
    :head-height="headerHeight"
    @refresh="refresh"
    :disabled="disabledRefesh"
    pulling-text="下拉刷新"
    loosing-text="释放更新"
    
  )
    .scroller-wrapper
      .empty(v-if="!list.length")
        img(src="../assets/images/empty.png")
        p 空空如也
      van-list(
        v-model="scrollLoading"
        :finished="finished"
        :finished-text="finishedText"
        :immediate-check="immediateCheck"
        @load="load"
      )
        slot
        slot(name="listItem" v-for="item in list" :item="item")`
.scroller-wrapper是滚动容器

**Comment by lingsang2** [comment]
![image](https://user-images.githubusercontent.com/22805819/57212977-fcd6b900-7017-11e9-8809-8ba01604125f.png)
.scroller-wrapper是滚动容器
滚动到任意位置，即使不在顶部，下拉时都会触发下拉刷新

**Comment by lingsang2** [comment]
> > 应该 better-scroll 导致的冲突
> 
> 我也有同样的问题，没有使用better-scroll

解决了，滚动容器应该是下拉刷新组件的父级，如果是子级就会出现这个问题

**Comment by leemoncn** [comment]
> > > 应该 better-scroll 导致的冲突
> > 
> > 
> > 我也有同样的问题，没有使用better-scroll
> 
> 解决了，滚动容器应该是下拉刷新组件的父级，如果是子级就会出现这个问题

请问你说的滚动容器是什么意思，我现在也有这个问题，不管列表滑动到了哪个位置，只要一下拉就触发下拉刷新

**Comment by linhaihero** [comment]
> > > 应该 better-scroll 导致的冲突
> > 
> > 
> > 我也有同样的问题，没有使用better-scroll
> 
> 解决了，滚动容器应该是下拉刷新组件的父级，如果是子级就会出现这个问题

解决了。这个坑官方应该在文档里说明一下的，否则很容易搞不清。。

**Comment by Miazzy** [comment]
这个问题确实存在，应用的确实是最新版的下拉刷新组件，不应该用户改代码来实现。

举个例子，比较下拉刷新组件里面嵌套了100个列表，按理说，如果在顶部时监听下拉，也就是说我们在第一个第二个第三个等顶部的列表组里面进行下拉，应该触发下拉刷新，但是当页面往底部滑动，滑动到第20个，第50个，等等（就是说，下拉组件的底部时），这是用户下拉，查看先前的数据时，居然触发了下拉刷新，此时不应该触发下拉刷新，代码应该改成，下拉组件监听用户触发下拉刷新的位置，如果在顶部时才触发，现在使用者都是通过一些方法改了一下才可以使用的。

**Comment by chen734311539** [comment]
我也有这个问题 怎么解决的

**Comment by AudreyHepbur** [comment]
加上这个样式就可以了，附上链接

**Comment by AudreyHepbur** [comment]
.van-pull-refresh { 
	height: calc(100vh - 100px) !important;
 	overflow: auto !important;
} 
.van-list { height: auto !important; }

**Comment by nomanisaisland** [comment]
我把这个组件重写了，这个组件确实是有问题的，它监听的直接上级是你滚动区域的上级，所以不管你是哪个滚动区，只要下拉，它都会判断为可以刷新
