### ISSUE TITLE
Tab 标签页 优化

### ISSUE THREAD

**Issue by juchao110** [youzan/vant#3216]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
Tab 标签页 默认绑定当前的索引，能否增加配置，和绑定键值对的id之类的值

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
暂无计划支持喔，通过索引可以对应到其他数据的
