### ISSUE TITLE
vue-cli3.0使用vant1.6.5版本，ios9.x.x版本上面swiper不能滑动问题

### ISSUE THREAD

**Issue by mschange** [youzan/vant#3221]
问题描述：使用vue-cli3.0的脚手架，搭配vant1.6.5版本，移动端ios（9.x.x）上面swiper组件不能正常滑动；

代码示例：

<van-swipe @change="onChange" :initial-swipe="current">
        <van-swipe-item v-for="(swiperItem, swiperIndex) in swiperItem" :key="swiperIndex">
          <img :src="swiperItem" alt="">
        </van-swipe-item>
        <div class="custom-indicator" slot="indicator">     
        </div>
      </van-swipe>

**Comment by NeneM0** [comment]
是vue 升级之后事件冒泡的处理问题。把vue版本降到2.5.17 就行了

**Comment by mschange** [comment]
- [ ] 除了降低vue版本，还有别的办法解决这个问题没，还有Collapse组件也是这个问题

**Comment by chenjiahan** [comment]
建议先降级 Vue 试一下
