### ISSUE TITLE
使用 popup和Actionsheet 弹出层 后 再次弹出选择组件 遮罩层的显示 无法全屏

### ISSUE THREAD

**Issue by tidows** [youzan/vant#3224]
> **Describe the bug**
> 
> 使用 popup和Actionsheet 弹出层 后 再次弹出选择组件 遮罩层的显示 无法全屏，遮罩层只覆盖了第一次弹出popup或者Actionsheet组件，而无法全屏，超过popup或者Actionsheet组件的部分 弹出层会消失掉。
> 
> **Screenshots**
> 
> 图片终于可以上传了
> 
> **Environment**
> 
>     * Browser: 谷歌浏览器
> 
>     * Vant Version: 1.6.13
![WX20190409-101935](https://user-images.githubusercontent.com/8610014/56796075-64388000-6844-11e9-8cf1-32db8560652e.jpg)

**Comment by DivXPro** [comment]
我这里也是，当底部的层长度超出屏幕100%height的时候 新弹出的层将无法完全覆盖底部的层

**Comment by tidows** [comment]
> 我这里也是，当底部的层长度超出屏幕100%height的时候 新弹出的层将无法完全覆盖底部的层

你截个图看看呢 是不是我这样的   我这边是 嵌套弹出  mask 无法覆盖， vant 好像 全局只有一个mask 。

**Comment by chenjiahan** [comment]
建议不要嵌套使用，可以添加 getContainer="body" 挂载到根节点上

**Comment by benbenyao** [comment]
请问怎么挂载到根节点上哈？有没有写法案例哈，我不会写。

**Comment by aetherwu** [comment]
> 建议不要嵌套使用，可以添加 getContainer="body" 挂载到根节点上

同求问……
