### ISSUE TITLE
下拉刷新组件在 部分机型的浏览器上下拉后无法返回，会卡住。有解决方案吗

### ISSUE THREAD

**Issue by hkxxxx** [youzan/vant#3225]

**Comment by chenjiahan** [comment]
没遇到过喔，具体是什么机型呢，用官网示例能复现吗

**Comment by hkxxxx** [comment]
![微信图片_20190428142454](https://user-images.githubusercontent.com/23118101/56859764-f87c2180-69c1-11e9-8667-d217bee3921c.jpg)

**Comment by hkxxxx** [comment]
就是这种情况，机型是ipone7p，uc浏览器

**Comment by hkxxxx** [comment]
![df7b95ab6c9b2f64b1b9adfbc1618ba8](https://user-images.githubusercontent.com/23118101/56859852-2150e680-69c3-11e9-9a1c-42b674420dee.gif)

**Comment by hkxxxx** [comment]
![df7b95ab6c9b2f64b1b9adfbc1618ba8](https://user-images.githubusercontent.com/23118101/56859858-32015c80-69c3-11e9-95a9-b137efa9a5f5.gif)

**Comment by chenjiahan** [comment]
你的这个情况应该是手指滑到浏览器窗口外了，UC 浏览器的 touch 事件有 bug，滑到浏览器窗口外的时候不会触发 touchend 或者 touchcancel，所以下拉刷新不会结束。

这种情况比较难触发，一般不会滑到这么底部，暂时也没找到合适的兼容方案，所以 issue 先关闭咯

**Comment by hkxxxx** [comment]
好的，暂时只能这样了
