### ISSUE TITLE
手机浏览器无痕浏览时，icon不能显示

### ISSUE THREAD

**Issue by lvchaoyang** [youzan/vant#3226]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
试了下没问题的，无痕浏览对 icon 应该没有影响，建议看下是不是网络问题导致的
