### ISSUE TITLE
求一份最新的省市区编码格式文件

### ISSUE THREAD

**Issue by Ansxu** [youzan/vant#3227]
看到有好多市区被重新划分了，但是数据没有更新的。希望更新一下，因为真的真的真的很好用啊！！！

**Comment by chenjiahan** [comment]
更新了一下，参见：
https://github.com/youzan/vant/blob/dev/packages/area/demo/area.js

改动：https://github.com/youzan/vant/pull/3228

**Comment by lizy0329** [comment]
为什么不放上去 npm 呢？

**Comment by chenjiahan** [comment]
这个只是示例数据，不属于组件库的一部分

**Comment by lcyan** [comment]
> 这个只是示例数据，不属于组件库的一部分

这个数据不是最新，http://www.mca.gov.cn/article/sj/xzqh/2019/2019/201912251506.html

**Comment by chenjiahan** [comment]
@lcyan 具体缺了哪个，可以提 PR 喔
