### ISSUE TITLE
建议增加Toast.clear(type)方法

### ISSUE THREAD

**Issue by sscfaith** [youzan/vant#3230]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**

在项目中封装了axios请求，在请求前Toast.loading()，返回后Toast.clear()。但在多个请求一块执行时，Toast.clear()只能关闭第一个。[代码](https://codepen.io/sscfaith/pen/JVzYXE?editors=1000)
使用了Toast.clear(true)可以关闭所有toast，但Toast(message)也会被关闭。[代码](https://codepen.io/sscfaith/pen/qwvZgZ?editors=1000#0)

**Describe the solution you'd like**

建议增加Toast.clear(type)方法，可以指定关闭什么类型的toast

**What does the proposed API look like?**

Toast.clear(type)

**Comment by chenjiahan** [comment]
暂无计划新增这个参数，你这种情况建议使用 allowMultiple 方法来做

**Comment by sscfaith** [comment]
使用 allowMultiple 方法也只能关闭第一个
[代码](https://codepen.io/sscfaith/pen/JVzYXE?editors=1000)

**Comment by chenjiahan** [comment]
this.toast 是每次新创建的实例，调用 close 只会关闭这一个实例

**Comment by Pancho2wang** [comment]
> 
> 
> this.toast 是每次新创建的实例，调用 close 只会关闭这一个实例

toast不是单例模式么？为什么每次都会创建新实例，如果调用多次的话，页面上就会有多个dom，而且不能消除。这样子整个页面就会增大。怎么解决？
![图片](https://user-images.githubusercontent.com/6365417/57829483-b1739600-77e1-11e9-8eea-c79a3e1bfc0a.png)

**Comment by chenjiahan** [comment]
allowMultiple 后是多实例，会自动清除

**Comment by linhaihero** [comment]
> allowMultiple 后是多实例，会自动清除

实在忍不住吐槽一下，自从了vant，最多bug就是这个鸡毛loading，增加 Toast.clear(type) 非常合理，因为 allowMultiple 根本就是一堆坑，开了allowMultiple 之后，这样 abc = xxxxxx.loading(...) 创建实例，然后 abc.clear() 的时候根本没办法全部清除，加true又会影响其它的了。
根本没测试过久张口就来的，别人和你们说又当没听到，行吧，免费的东西，你们开心吧

**Comment by linhaihero** [comment]
Toast.allowMultiple();

show(){
    window.globalLoading = Toast.loading({duration:0});
}

上面代码 ，业务需要 时 show 会调用多次（假设就两次），之后调用

window.globalLoading.clear(); 或者 window.globalLoading.clear(true); 都根本没卵用，页面始终还残留着 至少一个loading。内存泄露到不知道哪去了。

别叫我建示例，就上面这样，爱理不理吧，心死了。

**Comment by chenjiahan** [comment]
像你这样瞎用的还喜欢喷，什么库都救不了你。
