### ISSUE TITLE
【ios】Fieid 在ios12.2下无法输入

### ISSUE THREAD

**Issue by frankHelens** [youzan/vant#3231]
`
<van-field
    v-model="username"
    required
    clearable
    label="用户名"
    right-icon="question-o"
    placeholder="请输入用户名"
    @click-right-icon="$toast('question')"
  />
`
npm 版本： 1.6.16
问题描述： 用ios12.2系统下输入内容，会失去焦点，导致无法输入，安卓正常

**Comment by chenjiahan** [comment]
我这正常，具体是什么机型，能提供 jsfiddle 么

**Comment by webxing** [comment]
请问是怎么解决的？

**Comment by chenjiahan** [comment]
@webxing 这个是 iOS 的 bug，最新版 vant 内置了兼容逻辑，可以升级试试

**Comment by webxing** [comment]
> @webxing 这个是 iOS 的 bug，最新版 vant 内置了兼容逻辑，可以升级试试

大佬你好 
    "vant": "^2.0.8",
    "vue": "^2.5.2",
我的版本是这样的
vant已经是最新的了
求救~
加了交流群那个微信 但是没人回复

**Comment by lany9527** [comment]
实测 升级了 也不行
