### ISSUE TITLE
van-step样式问题

### ISSUE THREAD

**Issue by Wy38722** [youzan/vant#3234]
**Describe the bug**
在使用横向Steps样式拥挤，每个van-step还是有间距的。 

**Screenshots**
![image](https://user-images.githubusercontent.com/29934627/56874590-75b0a080-6a6d-11e9-8206-83095d399506.png)

**Environment**
 - Device: 
 - Browser: v1.6.16
 - Vant Version:

**Comment by chenjiahan** [comment]
目前在小屏手机上有 5 个步骤的话会重叠，下个版本会修复

**Comment by chenjiahan** [comment]
已在 1.6.17 版本修复
