### ISSUE TITLE
请问文件上传支持进度吗?

### ISSUE THREAD

**Issue by jinkun2014** [youzan/vant#3236]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
想在文件上传的时候支持新增文件上传进度的回调方法

**Describe the solution you'd like**
文件上传显示文件上传进度百分比

**What does the proposed API look like?**

on-progress | 文件上传时的钩子 | function(event, file, fileList)
-- | -- | --

**Comment by chenjiahan** [comment]
不支持喔，暂时没计划实现这个能力
