### ISSUE TITLE
[Feature Request] Notify 增加onClick回调函数

### ISSUE THREAD

**Issue by jasconchen** [youzan/vant#3237]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
Notify 消息提示建议增加onClick回调函数

**Describe the solution you'd like**
Notify 消息提示建议增加onClick回调函数

**What does the proposed API look like?**

- [ onClick] [点击 Notify 时的回调函数][function]

**Comment by chenjiahan** [comment]
是什么场景下需要使用 onClick 函数呢

**Comment by jasconchen** [comment]
socket推送消息的时候，可以点击Notify操作

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.0 版本支持
