### ISSUE TITLE
van-address-list 中  点击左侧  icon 图标正常切换状态，但没有触发 select 事件，

### ISSUE THREAD

**Issue by xyuh111** [youzan/vant#3238]
van-address-list 中  点击左侧  icon 图标正常切换状态，但没有触发 select 事件，
icon 图标是绝对定位，没有触发 内容区域的 select 事件，需要给 span 标签“ van-radio__label ”设置 z-index:1 才能在点击 icon 图标时正常触发 select 事件，

**Comment by chenjiahan** [comment]
这个问题已经在 1.6.16 版本修复，麻烦升级试下
