### ISSUE TITLE
[Feature Request] sku 组件图片预览，返回直接退出当前页面

### ISSUE THREAD

**Issue by CrosheChen** [youzan/vant#3240]
sku 组件图片预览，返回直接退出当前页面
 
 添加imagePreview open和close事件，这样就能动态修改url,解决尴尬的返回直接退出当前页面

**Comment by chenjiahan** [comment]
后续版本会支持

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.0 版本增加对应的事件
