### ISSUE TITLE
Dialog 【组件调用】按需引入出现问题

### ISSUE THREAD

**Issue by CHENPINGCAI** [youzan/vant#3241]
**Describe the bug**

Dialog 【组件调用】按需引入出现问题
`<van-dialog />`
```
import { Dialog } from 'vant'
components: { VanDialog: Dialog }
```

一旦按需注册Dialog组件，不需要v-model=show页面就会自动弹出一个`确认`字样的弹窗

![image](https://user-images.githubusercontent.com/20519720/56893354-01015480-6ab5-11e9-9472-4eb3409bf7ac.png)

点击确认按钮后

![image](https://user-images.githubusercontent.com/20519720/56893456-4887e080-6ab5-11e9-9b4b-5e1300f88382.png)

**Environment**
 - Device:  mac pro
 - Browser: chrome  74.0.3729
 - Vant Version:  v1.6.14
 - 脚手架:  vue-cli 3.6.3

**Comment by chenjiahan** [comment]
Dialog 是一个函数，不是组件，因此不支持局部注册。正确的注册方法是 `Vue.use(Dialog)`
