### ISSUE TITLE
建议NoticeBar left-icon支持icon组件

### ISSUE THREAD

**Issue by superlbr** [youzan/vant#3244]
**What problem does this feature solve?**
当前的left-icon必须传入网址url

**Describe the solution you'd like**
left-icon可以支持slot，这样就可以使用icon组件

**Comment by chenjiahan** [comment]
已经支持了

**Comment by superlbr** [comment]
并不可以，看代码？
https://github.com/youzan/vant-weapp/blob/aa11cd0acc3caf2ce7bd95955d7b309ea5587cc7/packages/notice-bar/index.wxml#L7-L11

**Comment by chenjiahan** [comment]
你发错仓库了，这里是 Vant Vue 的仓库，不是小程序

**Comment by superlbr** [comment]
尴尬
