### ISSUE TITLE
Toast在出现多行内容时，文本未居中

### ISSUE THREAD

**Issue by ztyzbb** [youzan/vant#3246]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
当Toast中的内容出现多行时，内容未被居中，而是左对齐，有点丑

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/22043636/56949689-1e422b80-6b66-11e9-80aa-dd21bda4263c.png)

**Environment**
 - Device: All
 - Browser: All
 - Vant Version: 1.6.16

**Reproduce**
```
Toast.fail("服务器异常\n404")
```

**Comment by chenjiahan** [comment]
感谢反馈，后续版本会改成居中处理

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.0 版本调整
