### ISSUE TITLE
请问有没有项目框架的说明文档哈，类似spring框架那样的整体介绍，是如何加载，运行渲染顺序如何。谢谢。

### ISSUE THREAD

**Issue by benbenyao** [youzan/vant#3247]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
没有喔，组件库不需要这些，参考快速上手即可
