### ISSUE TITLE
能否请教一下用 vant 的情况下，单元测试应该如何测试比较好？

### ISSUE THREAD

**Issue by bolechen** [youzan/vant#3248]
目前用的是 mocha，dom 加载和判断都没有问题，但是类似于

```
this.$dialog.alert
this.$dialog.confirm
```
这种异步操作，获取不到更新后的 dom，我目前的做法是在回调内部设一个变量 this.lasterror，判断有值了就说明调用成功，感觉有点傻。。。

研究了一天了还没结果，能否在百忙中给点建议，比心~

**Comment by bolechen** [comment]
部分代码如下

```
  it('click have error', (done) => {
    const wrapper = factory('/qrcode')
    wrapper.find('button.van-button').trigger('click')

    expect(wrapper.vm.$refs.appView.lastError).toContain('您不是会员，无法生成二维码')

   //我期望在这里可以拿到 $dialog.alert 但是并没有
    wrapper.vm.$refs.appView.$nextTick(() => {
      // console.log(wrapper.html())
      done()
    })
  })

**Comment by chenjiahan** [comment]
可以参考一下`Vant`里`Dialog`的单元测试代码喔，[链接](https://github.com/youzan/vant/blob/dev/packages/dialog/test/index.spec.js)

简单来说就是检查 document 下面的 dialog 元素是否存在，display 是否为显示。由于是异步操作，所以要在 setTimeout 之后去检查

**Comment by bolechen** [comment]
感谢感谢，没想到可以直接用 document，之前一直用 wrapper 取不到
