### ISSUE TITLE
多个popup共享同一个ovelay，导致关闭一个，都触发click-overlay

### ISSUE THREAD

**Issue by lerit** [youzan/vant#3251]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
我用popup来调用组件，有可能同时出现一个popup中的组件，又弹出另外一个popup.
发现最顶级的popup被点中overlay后（每个popup都有各自的click-overlay事件），下面所有的popup的click-overlay都被触发了。
v1.6.5是最后一个正常的版本
v1.6.6开始出现此bug
**Screenshots**
Add screenshots to help explain your problem.
请直接看demo
**Environment**
 - Device: 
 - Browser: chrome
 - Vant Version: 1.6.16

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
http://jsrun.net/iuXKp/
打开demo后，连续点击两个按钮，模拟弹出两个popup
然后，点击overlay部分，看关闭popup的效果
可以在demo中，改变版本号，能看到之前的正常效果。

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 1.6.17 版本修复

**Comment by HighWarmModel** [comment]
> 1.6.17

我引用的是cdn问题还是在，点击蒙层，两个popop 同时关闭
