### ISSUE TITLE
NavBar 导航栏 增加返回首页按钮 和 返回上一页功能

### ISSUE THREAD

**Issue by 9007967** [youzan/vant#3252]
NavBar 导航栏 增加返回首页按钮 和 返回上一页功能
默认箭头点击结果要在每个pages里面写 为什么不直接指定
`onClickLeft(e) {
      wx.navigateBack({
        delta: 1
      })
    },`

另外增加返回首页按钮

**Comment by chenjiahan** [comment]
你好，小程序的需求请到 vant-weapp 仓库下提
