### ISSUE TITLE
van-cell的icon只能只用van-icon开头的图标？不能使用自定义的图标？我看源码const LeftIcon = slots.icon     ? slots.icon()     : icon && <Icon class={bem('left-icon')} name={icon} />;直接定义了name

### ISSUE THREAD

**Issue by benbenyao** [youzan/vant#3254]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
可以通过 slot 来使用任何你需要的图标

**Comment by benbenyao** [comment]
请问有没有案例哈，<van-cell slot="icon" ><slot name="icon"><van-icon name="close" /></slot></van-cell>   这么写没效果。

**Comment by benbenyao** [comment]
我看了van-icon和cell的icon，内部实现是不一样的，icon默认有个放左边的样式，用slot的话是没有，我是初学者，看到真的好痛苦。

**Comment by benbenyao** [comment]
是的，可以的，多谢指导，我是参照这个：https://github.com/youzan/vant/issues/3075
