### ISSUE TITLE
[Bug Report] 下拉刷新使用 transform 导致子元素的 position: fixed 不生效

### ISSUE THREAD

**Issue by phyng** [youzan/vant#3256]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**

下拉刷新组件使用 transform 实现，而 transform 属性会导致子节点中的 position: fixed 属性不再相对于屏幕(https://www.w3.org/TR/css-transforms-1/#transform-rendering)。

处理方法：当 transform 值为 `translate3d(0px, 0px, 0px)` 时，修改为 `unset`，`unset` 不会影响子节点中的 position: fixed 属性。

**Screenshots**

Reproduce:

![](https://s2.d2scdn.com/2019/5/5/8ce06293-9cc0-4b7c-99d0-2bf3fa6fed05/Jietu20190505-172142.png)

Use `unset` to fix it:

![](https://s2.d2scdn.com/2019/5/5/40c0c578-5f0b-4bf6-ac65-cd1c174c5030/Jietu20190505-172322.png)

**Environment**
 - Device: All
 - Browser: All
 - Vant Version: Latest

**Reproduce**

Reproduce and fix:  https://jsfiddle.net/gubajre4/3/

**Comment by chenjiahan** [comment]
已在 1.6.18 版本修复
