### ISSUE TITLE
在屏幕是375这种奇数的时候出现缝隙

### ISSUE THREAD

**Issue by liangShengSen** [youzan/vant#3259]
![image](https://user-images.githubusercontent.com/21200409/57203820-b8cac080-6fe5-11e9-9bf7-d63d5ff5142f.png)

**Comment by huangysss** [comment]
应该是.van-popup--bottom的transform: translate3d(-50%, 0, 0);这里的问题, 在chrome里会将.5px四舍五入掉.

**Comment by liangShengSen** [comment]
> 应该是.van-popup--bottom的transform: translate3d(-50%, 0, 0);这里的问题, 在chrome里会将.5px四舍五入掉.

那请问有解决办法吗？还是去到真机就不不会出现这个问题？

**Comment by huangysss** [comment]
> > 应该是.van-popup--bottom的transform: translate3d(-50%, 0, 0);这里的问题, 在chrome里会将.5px四舍五入掉.
> 
> 那请问有解决办法吗？还是去到真机就不不会出现这个问题？

我试了一下微信/小米/华为浏览器都没有出现缝隙

**Comment by liangShengSen** [comment]
> > > 应该是.van-popup--bottom的transform: translate3d(-50%, 0, 0);这里的问题, 在chrome里会将.5px四舍五入掉.
> > 
> > 
> > 那请问有解决办法吗？还是去到真机就不不会出现这个问题？
> 
> 我试了一下微信/小米/华为浏览器都没有出现缝隙

好的，谢谢您的解答
