### ISSUE TITLE
不能手势滑动的问题

### ISSUE THREAD

**Issue by rock53770** [youzan/vant#3261]
vant官方demo

ios10.3.2及以下  微信浏览器和UC浏览器    vue@2.6.10和vant@1.6.17 

基础组件->popup弹出层->底部弹出，picker只能点击，**偶现**不能滑动。不只是picker组件，包括左滑组件，轮播图，都会偶现不能手势滑动的问题

**Comment by changqing91** [comment]
生产遇到DatePicker不能滑动问题！！！！

**Comment by rock53770** [comment]
我有个项目使用vant@1.5.x是没有问题的，用1.6.x就有问题

**Comment by chenjiahan** [comment]
麻烦用 Vue 2.5 试下

**Comment by rock53770** [comment]
2.5可以

**Comment by chenjiahan** [comment]
那就说明 vue 2.6.10 还是有兼容问题，可以先暂时降级到 vue 2.5

**Comment by chenjiahan** [comment]
已在此 issue 中备注 https://github.com/youzan/vant/issues/3015
