### ISSUE TITLE
不用脚手架如何实现框架多语言

### ISSUE THREAD

**Issue by Give-me-sweets** [youzan/vant#3262]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
目前不支持 CDN 引入多语言，推荐用脚手架来搭建

一个不太推荐的方案：手动把 `vant/lib/locale/lang/en-US` 的内容拷贝到你自己的项目里
