### ISSUE TITLE
noticeBar双向绑定text的时候，会出现获取不到text的情况。

### ISSUE THREAD

**Issue by fackerZuo** [youzan/vant#3264]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
:text的时候，会出现内容无法获取的情况。但是比如接口已经返回，这时候写:text="text"的时候，热更新页面，就完全正常。刷新一下页面，:text就再也获取不到内容。

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/17962151/57212061-11658200-7015-11e9-9db8-28dda42f2a8a.png)
![image](https://user-images.githubusercontent.com/17962151/57212078-1fb39e00-7015-11e9-9b60-0a063f8798a0.png)

**Environment**
 - Device: PC
 - Browser: 谷歌
 - Vant Version: 1.6.17

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
试了下没复现问题，能否提供一下 jsfiddle

**Comment by fackerZuo** [comment]
> 试了下没复现问题，能否提供一下 jsfiddle

是我手写错了。应该是data  return,不是date。。。

**Comment by chenjiahan** [comment]
喔。。
