### ISSUE TITLE
tabs组件问题 里面的内容宽度超过1屏，滚动冲突

### ISSUE THREAD

**Issue by WhityLL** [youzan/vant#3265]
**Describe the bug**
tabs组件问题 里面的内容宽度超过1屏，滚动冲突，能否加一个滚动优先级字段

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/16092151/57213571-d1ed6480-7019-11e9-8af6-faa367832c72.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
在滚动的内容上面 catch 掉 touchmove 事件即可
