### ISSUE TITLE
row使用gutter属性且其父元素宽度为可视区域宽度时，底部出现横向滚动条

### ISSUE THREAD

**Issue by signuporin** [youzan/vant#3266]
row使用gutter属性且其父元素宽度为可视区域宽度时，底部出现横向滚动条；
参照bootstrap给row父元素添加对应左右padding滚动条消失。请问栅格系统是否有类似container和container-fluid的样式类？

![image](https://user-images.githubusercontent.com/29741546/57214300-2c87c000-701c-11e9-847d-8bc1732f1b9c.png)

![image](https://user-images.githubusercontent.com/29741546/57214349-4e814280-701c-11e9-9fae-6098e7e6184b.png)

**Comment by chenjiahan** [comment]
暂时没有计划提供父元素的样式类喔，目前比较主流的组件库都是这样设计的，还没找到更好的处理方案
