### ISSUE TITLE
vant什么时候适配uni-app

### ISSUE THREAD

**Issue by mengxianghan** [youzan/vant#3267]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
uni-app没有完整且风格统一的ui组件库，希望vant团队可以进行适配，可以提高工作效率

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
暂无计划适配喔，迁移成本比较大
