### ISSUE TITLE
期望DatetimePicker可增加循环滚动，以及选择分钟的粒度控制

### ISSUE THREAD

**Issue by phyLoveC** [youzan/vant#3268]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
选择器可控性变高，首位衔接去掉来回滑动的抄做，分钟较多，但是大多数不是必须出现的，增加粒度设置

**Describe the solution you'd like**
建议增加两个参数，一个是否循环滚动，一个控制分钟粒度

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
循环滚动暂时比较难实现，分钟粒度后续会看下

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.1 版本支持
