### ISSUE TITLE
支持 v-slot 

### ISSUE THREAD

**Issue by kid1412621** [youzan/vant#3270]
**What problem does this feature solve?**
vue 2.6.0 废弃了 slot 特性，取而代之的是 v-slot 希望能支持下

**Describe the solution you'd like**
还有 # 修饰符的支持

**What does the proposed API look like?**
https://cn.vuejs.org/v2/guide/components-slots.html#%E5%85%B7%E5%90%8D%E6%8F%92%E6%A7%BD%E7%9A%84%E7%BC%A9%E5%86%99

**Comment by benbenyao** [comment]
天哪，VUE升级了。

**Comment by chenjiahan** [comment]
这俩个都是默认支持的，可以直接用

**Comment by kid1412621** [comment]
> 这俩个都是默认支持的，可以直接用

不好意思，麻烦帮看下哪里有问题：
```html
<van-nav-bar title="标题" left-text="返回" left-arrow>
      <van-icon name="search" #right />
</van-nav-bar>
```
就是显示不出来，用 slot="right" 可以
