### ISSUE TITLE
提议增加table组件哦。

### ISSUE THREAD

**Issue by benbenyao** [youzan/vant#3271]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
暂无计划支持呢，移动端 Table 的场景比较少

**Comment by benbenyao** [comment]
众筹咯，看看大家意见，我赞助20张毛爷爷。

**Comment by chenjiahan** [comment]
😂目前没开放赞助喔，我们主要还是看需求的应用场景、使用频率来评估优先开发哪些功能

**Comment by dududa2015** [comment]
臣附议！

**Comment by cokery** [comment]
附议

**Comment by lvvlan** [comment]
附议

**Comment by fengyun2** [comment]
附议

**Comment by GoToBoy** [comment]
移动端 Table 的场景 在我这边还是有很大的需求的，出现频率就和picker 一样，建议考虑支持

**Comment by OverTree** [comment]
附议

**Comment by BrendanFich** [comment]
附议

**Comment by Joanna0001** [comment]
附议

**Comment by leaper1** [comment]
附议

**Comment by xsdhy** [comment]
附议

**Comment by iniwf** [comment]
附议

**Comment by edenleung** [comment]
附议

**Comment by jikoy** [comment]
强烈建议增加表格控件+1

**Comment by jikoy** [comment]
强烈建议增加表格控件

**Comment by lwm98** [comment]
附议

**Comment by llearn** [comment]
附议

**Comment by Eviwang** [comment]
附议

**Comment by zhuangxiaohui** [comment]
很大需求：建议参考table编写  https://okee.oceanengine.com/mobile/vue/#/zh-CN/table

**Comment by carryxiong** [comment]
真的需要啊

**Comment by lutianxiong** [comment]
2年了

**Comment by jikoy** [comment]
+1发自我的华为手机-------- 原始邮件 --------发件人： Echo ***@***.***>日期： 2021年10月19日周二 16:11收件人： youzan/vant ***@***.***>抄送： jikoy ***@***.***>, Comment ***@***.***>主    题： Re: [youzan/vant] 提议增加table组件哦。 (#3271)

2年了

**Comment by 0900304132** [comment]
表格还是需要的

**Comment by zhangbincheng1997** [comment]
+1

**Comment by Gzbox** [comment]
+1

**Comment by gofunbox** [comment]
附议

**Comment by DeanYang121** [comment]
真的需要呀 希望加上

**Comment by panyon** [comment]
希望有table组件

**Comment by baikai55** [comment]
附议

**Comment by YingXiaoMing** [comment]
表格还是需要的，我也觉得不应该有，但场景需要

**Comment by zburu** [comment]
+1 我觉得可以先提供一个基本的组件入口 van-table 
自己写的样式不能统一，比较丑
具体功能慢慢上

**Comment by 1186841621** [comment]
需要

**Comment by dream-sir** [comment]
建议支持啊

**Comment by lovesL** [comment]
臣附议

**Comment by zp29** [comment]
臣附议 💯

**Comment by 55555778** [comment]
臣附议

**Comment by Hexiaowu15** [comment]
附议

**Comment by ZedCoding** [comment]
附议

**Comment by 1436925197** [comment]
附议

**Comment by ColtonVan** [comment]
附议

**Comment by hfa5221697** [comment]
附议

**Comment by fuigui888** [comment]
附议 希望加个表格

**Comment by lee259** [comment]
附议
