### ISSUE TITLE
Picker 选择器是不是应该加一个v-model绑定方便默认选中

### ISSUE THREAD

**Issue by roywu888** [youzan/vant#3272]
Picker 选择器是不是应该加一个v-model绑定方便默认选中？
现在只有一个:default-index设置索引值，很不方便！！

**Comment by chenjiahan** [comment]
Picker 的 API 后续会看下能否优化，不过不一定是 v-model 的形式，因为 Picker 有单列和多列两种情况

**Comment by chenjiahan** [comment]
看了下改不了 v-model，先 close 咯
