### ISSUE TITLE
IOS 系统 transparent样式不生效 

### ISSUE THREAD

**Issue by 15669028801** [youzan/vant#3273]
**Describe the bug**
ios系统下，部分background 设置为transparent不能生效

**Screenshots**
![image](https://user-images.githubusercontent.com/35586321/57343456-0bd37d80-7176-11e9-802f-adab3ffcfb17.png)

**Environment**
 - Device:  苹果电脑
 - Browser: Google Chrome版本 74.0.3729.131（正式版本） （64 位）
 - Vant Version: 1.6.13

相关解决办法：
[解决方法](http://ask.dcloud.net.cn/question/4503)

**Comment by chenjiahan** [comment]
是生效了的，是你项目里的 text-shadow 样式导致还能看到箭头

**Comment by 15669028801** [comment]
我也不知道是哪个包写进来了，本地代码是没有的，UI框架就引了vant

其实是非常感谢你的回复。、

**Comment by chenjiahan** [comment]
哈哈，客气
