### ISSUE TITLE
submit-bar 默认的solt，不能加在价格后面

### ISSUE THREAD

**Issue by scpazq** [youzan/vant#3276]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
需要在submit-bar价格的后面加提示文字，例如：总价：¥550.00（包邮），但是组件不支持。

**Describe the solution you'd like**
希望在solt里面增加一个配置，可以选择在价格之前还是跟随在价格之后。 

**What does the proposed API look like?**
无

**Comment by chenjiahan** [comment]
后续会加一个 Price 对应的插槽

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.0 版本支持
