### ISSUE TITLE
tabs 切换动画会出现卡顿

### ISSUE THREAD

**Issue by NightCatSama** [youzan/vant#3277]
**What problem does this feature solve?**
目前是使用 `left` 来使用动画会出现卡顿，即使使用了 `will-change` 也仍然会出现卡顿。

https://github.com/youzan/vant/blob/21589c9b9fd70b750deed1d31226b8d2c74d62c0/packages/tabs/index.js#L114

我手动改了 `node_modules/vant/es/tabs/index.js`，就变流畅了。

![image](https://user-images.githubusercontent.com/13888962/57434990-d78fb800-726e-11e9-989f-cb8c140ebe58.png)

**Describe the solution you'd like**

**What does the proposed API look like?**
建议使用 `transform: translateX` 来实现。

也可以增加参数控制选择哪种方式动画 (`left` or `transform`，默认`left`)。

这是否可行，如果可以的话，我也可以提交 pr。

感谢开源 🎉。

**Comment by chenjiahan** [comment]
请问具体是在什么机型上会卡顿呢

**Comment by NightCatSama** [comment]
@chenjiahan chrome74 的移动端模拟器，使用 left 有顿挫感，使用 transform 就很流畅。

应该是使用 left 会页面重排导致的。

**Comment by NightCatSama** [comment]
小米 Note 自带浏览器有明显的卡顿，同样切换使用 transform 就好多了。

如果直接改成 transform 会存在什么问题吗

**Comment by chenjiahan** [comment]
改成 transform 的话，Tab 里面的所有 fixed 布局会失效

**Comment by NightCatSama** [comment]
我试了，fixed 元素在两种情景下行为一致。

如果两者在布局上存在差异，那加一个属性也是可以解决的。

卡顿感在移动端很影响体验。

**Comment by chenjiahan** [comment]
不一致的，fixed 的会被转换成 absolute，你可以用 chrome 测试下。

另外改成 transform 确实是更合理的，但是应该会放到大版本（2.0）里去改

**Comment by NightCatSama** [comment]
@chenjiahan 好的，谢谢

**Comment by NightCatSama** [comment]
2.0 虽然改成 transform 了，但是这个切换也改了。

切换下一页的时候，上一页直接就先消失了，看起来很奇怪。

**Comment by chenjiahan** [comment]
@NightCatSama 并不会直接消失呢，但是会设置 height: 0 (防止不同 Tab 高度冲突)。你是不是设置了其他样式（比如 overflow hidden）导致这个问题呢

**Comment by NightCatSama** [comment]
@chenjiahan 原来如此，因为我内部的高度是根据 100% 来计算的。

我加了 `height: 100%!important` 就好了。

谢谢回复
