### ISSUE TITLE
官方仓库 vant-doc 的依赖 touch-simulator.js 有一个严重问题，拖动会产生点击

### ISSUE THREAD

**Issue by papplefe3** [youzan/vant#3278]
**Describe the bug**
用demo时，在电脑上使用鼠标操作，touch-simulator.js 会使拖动变为点击事件。
具体重现是在 swipe 组件上创建一个click事件，拖动放手时（正常时拖动过远，click会自动失效），本应取消click事件，但是却触发了click事件

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 电脑
 - Browser: 都一样
 - Vant Version: 都会

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
这个不是 touch-simulator.js 的问题，即使移除这个文件也会有同样的现象。

准确来说，这个是 PC 端浏览器 click 事件触发的默认行为，是符合规范的。下面是规范原文：

> the click event may be dispatched if one or more of the event types mouseover, mousemove, and mouseout occur between the press and release of the pointing device button. 

参考链接：https://www.w3.org/TR/2014/WD-DOM-Level-3-Events-20140925/#event-type-click

**Comment by Cifer-Y** [comment]
我在 iOS 的 Safari 上也会遇到这个问题, 有什么解决办法吗?

**Comment by chenjiahan** [comment]
@Cifer-Y iOS 的话和这个库就没关系了，这个库只会在桌面端生效。建议你看下是不是引入了 fastclick 之类的库导致的
