### ISSUE TITLE
<van-icon name="question" /> 的问号显示不出来

### ISSUE THREAD

**Issue by liuruiqi1993** [youzan/vant#3280]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
`<van-icon name="question" />` 效果和示例图不一样诶？中间的问号丢了
```
<van-icon name="question-o" />
<van-icon name="question" />
<van-icon name="clock" />
```
**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/33003931/57497213-4faabc00-7309-11e9-9a50-c6b22c60f763.png)

**Environment**
 - Device: win10
 - Browser: 
![image](https://user-images.githubusercontent.com/33003931/57497013-6997cf00-7308-11e9-89fd-c68fd5a59980.png)
![image](https://user-images.githubusercontent.com/33003931/57497113-e0cd6300-7308-11e9-9785-71cca4634af5.png)

 - Vant Version: 1.6.15

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
这个问题已经在 1.6.17 版本修复
