### ISSUE TITLE
swipe组件在touchmove时报错

### ISSUE THREAD

**Issue by woodThunder** [youzan/vant#3281]
**问题描述**
swipe组件在touchmove时报错
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
官方demo上面也有此问题

**开发环境**
 - Browser: 谷歌
 - Vant Version: 1.6.16

**解决方法**
参考网上给的解决方案，请官方验证
-1.touch-action: none;
-2.if (e.cancelable) { e.preventDefault();}

**Comment by chenjiahan** [comment]
下个版本会加上第二个方案

**Comment by chenjiahan** [comment]
已在 1.6.18 版本修复
