### ISSUE TITLE
swipe 指示器不能隐藏

### ISSUE THREAD

**Issue by gjfei** [youzan/vant#3285]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
![7F1M~QH(4}@0B_E@(818`EA](https://user-images.githubusercontent.com/33827314/57524145-84466400-7359-11e9-9c8f-bcdc81fc26ee.png)
![YMK1W2_M4UF9SK3DR8%X6NA](https://user-images.githubusercontent.com/33827314/57524148-87d9eb00-7359-11e9-8b96-b4fef365aa9c.png)

Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
前面要加冒号，不然传的是字符串不是 boolean

**Comment by gjfei** [comment]
> 前面要加冒号，不然传的是字符串不是布尔值

谢谢
