### ISSUE TITLE
这到底要咋控制 van-checkbox-group 

### ISSUE THREAD

**Issue by eachann1026** [youzan/vant#3286]
<van-checkbox-group v-model="result">
  <van-checkbox
    v-for="(item, index) in list"
    :key="item"
    :name="item"
  >
    复选框 {{ item }}
  </van-checkbox>
</van-checkbox-group>

出现的问题: 该如何保存他的选中状态 ,

**Comment by eachann1026** [comment]
<van-checkbox-group v-model="result">
  <van-checkbox
    v-for="(item, index) in list"
    :key="item"
    :name="item"
  >
    复选框 {{ item }}
  </van-checkbox>
</van-checkbox-group>

**Comment by eachann1026** [comment]
van-checkbox-group v-model="result"

**Comment by chenjiahan** [comment]
不知道你说的保存是什么意思，checkbox 的选中状态是和数据双向绑定的

**Comment by eachann1026** [comment]
> 不知道你说的保存是什么意思，checkbox 的选中状态是和数据双向绑定的

已经知道问题了 , 我当时的使用场景是使用了数组对象来绑定check的状态 , 才发现原来不能使用对象来做checked 的绑定 , 这个我觉得应该在文档上注明一下

**Comment by chenjiahan** [comment]
这个感觉没必要说明哈

**Comment by Rotor1996** [comment]
碰到了同样的问题 数组状态 result = [{name:1,id:1},{name:2,id:2}]

**Comment by langjinren** [comment]
> 碰到了同样的问题 数组状态 result = [{name:1,id:1},{name:2,id:2}]
> 在选择的时候没有报异常，但当我想要去直接赋值result = [{name:3,id:3}]时，却没办法把3改成选中状态。

请问解决了吗

**Comment by lixiaofa** [comment]
@chenjiahan  不能用对象绑定吗
现实中 都是绑定对象的， 比如 购物车三级选中

**Comment by qwasfun** [comment]
当绑定对象时，可以选中，也可以取消选中。就是给不了默认值，神奇 😓

**Comment by qwasfun** [comment]
搞定，在 checkbox 使用 checked 赋值可以了 😄
