### ISSUE TITLE
van-uploader上传有隐藏input 无法修改宽度 影响界面

### ISSUE THREAD

**Issue by Helenla** [youzan/vant#3287]
![image](https://user-images.githubusercontent.com/28640118/57567329-ffffe980-7409-11e9-882c-d455f2abf863.png)

点击上传div外的部分也会唤起上传

**Comment by chenjiahan** [comment]
直接修改 Uploader 的宽度就可以，上传点击区域默认和 Uploader 大小一致

**Comment by Helenla** [comment]
修改uploader的宽段后还是无法改变上传区域大小，但修改图标font-size上传区域会变小
![image](https://user-images.githubusercontent.com/28640118/57592173-e1176980-7567-11e9-8439-729eee5c9526.png)
![image](https://user-images.githubusercontent.com/28640118/57592268-70bd1800-7568-11e9-8ca9-21655dab5538.png)
![image](https://user-images.githubusercontent.com/28640118/57592302-92b69a80-7568-11e9-96ff-c1952c649d37.png)

**Comment by chenjiahan** [comment]
上图的上传区域是 100x100 吧，有啥问题

**Comment by Helenla** [comment]
超出了100 实际是上传宽度112

**Comment by chenjiahan** [comment]
你使用的是什么浏览器呢，看起来是 Uploader 被设置了一个 padding

**Comment by Helenla** [comment]
微信开发者工具

**Comment by chenjiahan** [comment]
看了下部分浏览器会因为 `file-upload-button` 导致有最小宽度，后续会增加适配的 css

**Comment by chenjiahan** [comment]
已在 1.6.19 版本修复
