### ISSUE TITLE
card组件使用slot添加tags问题

### ISSUE THREAD

**Issue by cooe** [youzan/vant#329]
在使用card组件进行列表编写时，发现在列表中，通过slot添加tags时，在<van-card>标签中不添加centered属性时，每个card组件中都会出现tags，但是一旦添加此属性后，最后一个不会出现tags

**Comment by chenjiahan** [comment]
@cooe 能否提供一个简单的复现问题的 demo？ https://jsfiddle.net/dfarLdko/1/
