### ISSUE TITLE
[Bug Report] van-info为空值依然渲染导致组件占位

### ISSUE THREAD

**Issue by ppokemon** [youzan/vant#3290]
**Describe the bug**
van-info为空值依然渲染导致组件占位

**Screenshots**
![image](https://user-images.githubusercontent.com/50414099/57581747-78d87180-74ee-11e9-8519-228ee3db3479.png)

**Environment**
 - Device: iphonexs Max
 - Browser: 微信内置x5
 - Vant Version: 1.6.18

**Reproduce**

**Comment by ppokemon** [comment]
发现给undefined不会出现此情况，可否优化一波，传0 || '' 不渲染或者不显示

**Comment by chenjiahan** [comment]
空字符串不应该渲染的，下个版本会修复这个问题

**Comment by ppokemon** [comment]
> 空字符串不应该渲染的，下个版本会修复这个问题

ok~

**Comment by chenjiahan** [comment]
已在 1.6.19 版本修复
