### ISSUE TITLE
[Feature Request] Tabbar 支持路由匹配

### ISSUE THREAD

**Issue by lyq027** [youzan/vant#3291]
页面刷新或详情页返回，tabbar的激活index都默认在第一个。建议能否像element的菜单栏那样，根据path自动设置显示选中的index
 目前的做法是将tabbar切换的index缓存起来，要显示时，再重新赋值新的index,这样才能保证刷新时，index不会变到默认的第一个。不过这样显得很不优雅

**Comment by chenjiahan** [comment]
后续会加一个 route 的模式，用来处理这种场景

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.0 版本支持
