### ISSUE TITLE
PasswordInput在安卓机不能阻止默认键盘

### ISSUE THREAD

**Issue by siqi-g** [youzan/vant#3292]
**Describe the bug**
PasswordInput和NumberKeyboard配合使用时, 安卓机型上会触发原生键盘覆盖NumberKeyboard组件
**Screenshots**
安卓机上原生键盘会被吊起
![IMG20190513_122704](https://user-images.githubusercontent.com/30216717/57596066-42950380-757b-11e9-8e89-3d3d5abaf07e.jpg)

**Environment**
 - Device:  Android
 - Browser: 
 - Vant Version: 1.6.16

**Reproduce**

**Comment by chenjiahan** [comment]
PasswordInput 组件里面不包含 input 标签，所以不可能唤起系统键盘的，能贴下你的代码么

**Comment by siqi-g** [comment]
> PasswordInput 组件里面不包含 input 标签，所以不可能唤起系统键盘的，能贴下你的代码么
![image](https://user-images.githubusercontent.com/30216717/57618530-4b56fb00-75b6-11e9-8b78-482d2740559e.png)

**Comment by chenjiahan** [comment]
看起来没啥问题，能给个复现问题的 jsfiddle 吗

**Comment by siqi-g** [comment]
是我上一个field组件的focus状态未移除

**Comment by sldeng** [comment]
怎么解决的
