### ISSUE TITLE
ImagePreview在pc页面下点击无法关闭预览

### ISSUE THREAD

**Issue by kwdwkiss** [youzan/vant#3293]
ImagePreview在pc页面下点击无法关闭预览

可能是pc版下，.van-image-preview__overlay点击事件没有触发，而移动页面正常

![WX20190513-142715](https://user-images.githubusercontent.com/4627378/57600206-b3441c00-758b-11e9-8645-91dedccb7e25.png)

**Environment**
 - Device: macbook
 - Browser: chrome  74.0.3729.131
 - Vant Version: 1.6.18

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
Vant 组件默认适配的是移动端，PC 端可以引入这个库 
https://github.com/hammerjs/touchemulator

**Comment by edgexie** [comment]
@chenjiahan 引入这个库会影响到类似地图的点击事件。

**Comment by chenjiahan** [comment]
@edgexie 试试 https://github.com/chenjiahan/vant-touch-emulator
