### ISSUE TITLE
希望增加 Skeleton骨架屏 组件

### ISSUE THREAD

**Issue by ChangeZhang** [youzan/vant#3294]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
希望增加 Skeleton骨架屏 组件 提升网站的加载体验

**Describe the solution you'd like**
希望增加 Skeleton骨架屏 组件

**What does the proposed API look like?**
类似 ant design 的 Skeleton骨架屏

**Comment by chenjiahan** [comment]
Skeleton 已经开发完成，会在近期的 2.0 版本发布

**Comment by ihamlet** [comment]
我也墙裂需要骨架屏组件

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.0 版本支持

**Comment by 1429880240** [comment]
骨架屏看不出来效果莫
