### ISSUE TITLE
按需引入vant组件报错

### ISSUE THREAD

**Issue by SparkleChen** [youzan/vant#3295]
vue.esm.js:628 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VanPopup>
       <ElCol>
         <ElRow>
           <ElMain> at packages/main/src/main.vue
             <ElContainer> at packages/container/src/main.vue
               <Home> at src/component/home/Home.vue
                 <Root>

import Vue from 'vue';
import { Popup } from 'vant';
Vue.use(Popup);
<template>
<div>
 <van-popup v-model="popShow">内容</van-popup>
</div>
</template>

<script>
export default {
        name: 'Home',
        components : {
            'van-popup' : Popup
        },
        data() {
            return {
                popShow : true
            }
        },
        computed : {},
        methods: {}
    }
</script>

**Comment by SparkleChen** [comment]
<template><div><van-popup v-model="popShow">内容</van-popup></div></template>

**Comment by SparkleChen** [comment]
"<template><div><van-popup v-model="popShow"内容</van-popup></div></template>"

**Comment by SparkleChen** [comment]
`<template><div><van-popup v-model="popShow">内容</van-popup></div></template>`

**Comment by chenjiahan** [comment]
建议 `console.log(Popup)`看下是否正确引入组件

**Comment by SparkleChen** [comment]
> 建议 `console.log(Popup)`看下是否正确引入组件

打印出来是{}......空的

**Comment by chenjiahan** [comment]
那就是引入有问题，建议看下是不是构建配置有误

**Comment by SparkleChen** [comment]
> 那就是引入有问题，建议看下是不是构建配置有误

你那里有没有标准配合  发我看看

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant-demo

**Comment by SilentKc** [comment]
这部分demo里提供的组件，都能正常引入，就是其他的一些，引入的时候就报错
