### ISSUE TITLE
在Actionsheet中, 如何自定义action的样式?

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#3299]
我希望每个action可以显示图标+文字, 所以有以下代码
```
<van-actionsheet v-model="isActionsheetShow" :actions="[]">
    <ul>
        <li v-for="(item, index) in list" @click="onClick(item, index)">
            ...
        </li>
    </ul>
</van-actionsheet>
```
但是 actionsheet 本来就存在action & select属性. 这样让我觉得li里面的 v-for 和 click 的写法显得多余.
在文档中我发现get-container这个属性的存在, 好像能解决我的问题,  不过没有找到例子不知道用法.
请问是否可以通过get-container属性自定义action的样式, 如果可以, 需要怎么写. 如果不可以, 官方是否考虑支持?
谢谢.

**Comment by chenjiahan** [comment]
get-container 不能自定义 action 样式呢，是用来指定 ActionSheet 挂载的节点位置的。

这个需求暂时没计划在组件内支持哈，建议自己实现
