### ISSUE TITLE
为什么我进入页面后我的tabbar 点击不了 

### ISSUE THREAD

**Issue by Wyangsen** [youzan/vant#3301]
<template>
    <van-tabbar class="footer">
        <van-tabbar-item   :class="active=='1'?'active':''" to="/Home" id="footer-item" >
            <img slot="icon" :src="require('../assets/image/shouye'+(active=='1'?'_cur':'')+'.png')" >
              首页
        </van-tabbar-item>
        <van-tabbar-item :class="active==2?'active':''" to="/Management" id="footer-item">
            <img slot="icon" :src="require('../assets/image/licai'+(active=='2'?'_cur':'')+'.png')">
             
             理财
        </van-tabbar-item>
        
         <van-tabbar-item :class="active=='3'?'active':''" to="/Use" id="footer-item">
            <img slot="icon" :src="require('../assets/image/icony'+(active=='3'?'_cur':'')+'.png')">
           应用
        </van-tabbar-item>
        <van-tabbar-item :class="active=='4'?'active':''" to="/My" id="footer-item">
            <img slot="icon" :src="require('../assets/image/my'+(active=='4'?'_cur':'')+'.png')">
             我的
        </van-tabbar-item>
    </van-tabbar>
</template>
<script>

//  import  "../../assets/footer.less";
    export default {
        name: "Footer",
        data(){
            return{
                // user:{}
            }
        },
        props: {
            active: String
        }
    }
     
</script>

**Comment by Wyangsen** [comment]
<template>
    <van-tabbar class="footer">
        <van-tabbar-item   :class="active=='1'?'active':''" to="/Home" id="footer-item" >
            <img slot="icon" :src="require('../assets/image/shouye'+(active=='1'?'_cur':'')+'.png')" >
              首页
        </van-tabbar-item>
        <van-tabbar-item :class="active==2?'active':''" to="/Management" id="footer-item">
            <img slot="icon" :src="require('../assets/image/licai'+(active=='2'?'_cur':'')+'.png')">
             
             理财
        </van-tabbar-item>
        
         <van-tabbar-item :class="active=='3'?'active':''" to="/Use" id="footer-item">
            <img slot="icon" :src="require('../assets/image/icony'+(active=='3'?'_cur':'')+'.png')">
           应用
        </van-tabbar-item>
        <van-tabbar-item :class="active=='4'?'active':''" to="/My" id="footer-item">
            <img slot="icon" :src="require('../assets/image/my'+(active=='4'?'_cur':'')+'.png')">
             我的
        </van-tabbar-item>
    </van-tabbar>
</template>

**Comment by chenjiahan** [comment]
不规范的 issue
