### ISSUE TITLE
ImagePreview组件

### ISSUE THREAD

**Issue by djinzhong** [youzan/vant#3303]
使用 ImagePreview 组件在 vue 当页面应用中,如果使用物理返回键会发现页面返回了,但是组件并未关闭 , 我只是想1. 物理返回键实现关闭图片预览但是不退出当前路由,还有2. 一个单击图片关闭预览功能,类似微博,微信里面图片预览体验功能

**Describe the solution you'd like**
1.在 vue 组件内的守卫 beforeRouteLeave 里面进行手动关闭2.增加一个参数控制是否点击图片关闭图片预览

**What does the proposed API look like?**
在守卫 beforeRouteLeave 中如果简单判断是否有 ImagePreview  实例的话并不能确定有图片展开预览,我需要获取到当前组件内是否有图片展开预览,根据这个参数实现物理返回键关闭图层但不退出这个页面,如果没有图片展开的话就直接退出此路由

**Comment by chenjiahan** [comment]
你可以用一个变量来记录一下，调用 ImagePreview 时候设置为 true，onClose 的时候设置为 false
