### ISSUE TITLE
一直很喜欢用你们的组件库，开发3个项目了，希望出个react用的

### ISSUE THREAD

**Issue by yzbgyq** [youzan/vant#3304]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
Sorry 暂时没计划出移动端的 React 组件库喔，不过我们有 PC 端的，链接：https://github.com/youzan/zent
