### ISSUE TITLE
Tab 标签页 开启粘性布局 offset-top 只支持 px，Rem 适配会导致高度不准确

### ISSUE THREAD

**Issue by Mikasa33** [youzan/vant#3305]
如题，Tab 标签页 开启粘性布局 offset-top 只支持 px，Rem 适配会导致高度不准确

**Comment by Mikasa33** [comment]
目前通过修改样式解决布局问题

**Comment by chenjiahan** [comment]
offset-top 涉及数值计算，所以只能传 px 单位，建议传入前根据 rem 比例自行转换
