### ISSUE TITLE
RadioGroup v-model绑定值，必须是data里面的普通数据，而不能是computed里面的对象

### ISSUE THREAD

**Issue by hetingyi** [youzan/vant#3306]
例如computed里面有下面数据，当与  `<van-radio-group v-model="formData.area_id">` 绑定后，
会出现radio选中没有任何效果的情况发生，
换成data里面的普通字符串就没问题，
请问是bug？

`formData () {
      return {
        user_name: '',
        mobile_phone: '',
        area_id: '',
        wecha_id: 'abc123',
        token: 'yaqila1491377108',
        id: this.allData.id
      }
    }`

**Comment by chenjiahan** [comment]
不是 bug，v-model 是双向绑定，因此绑定的值必须有 getter 和 setter。

你可以在 computed 属性里面定义 setter，具体用法见 Vue 文档
