### ISSUE TITLE
2.0的vant预计多久上线啊，准备开新项目，纠结现在用还是换

### ISSUE THREAD

**Issue by silentchild** [youzan/vant#3307]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
预计下周会发布第一个 beta 版本，下个月发布正式版。

另外 2.0 绝大部分组件和接口是向前兼容的，从目前的 1.6 版本升级上来是很容易的，所以不必纠结哈

**Comment by silentchild** [comment]
> 预计下周会发布第一个beta版本，下个月发布正式版。
> 
> 另外2.0绝大部分组件和接口是向前兼容的，从目前的1.6版本升级上来是很容易的，所以不必纠结哈

好的，感谢。
