### ISSUE TITLE
多实例Toast.loadding在clear后依旧存在

### ISSUE THREAD

**Issue by YH390389859** [youzan/vant#3309]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在每次发起接口请求的时候实例一个Toast.loading,在每次接口返回数据的时候clear掉,但是目前的问题是只能清除最后一次(或第一次)的示例,在对接口进行了settimeOut之后问题解决,但是这不符合项目需求

**Screenshots**
![TIM截图20190516115950](https://user-images.githubusercontent.com/19208082/57825662-6605bb80-77d2-11e9-8fed-7fed45ef3f1d.png)

![E4O6YWH}1JSGE1Q`ZM9V)E9](https://user-images.githubusercontent.com/19208082/57825694-8fbee280-77d2-11e9-9b07-ac1913949db1.png)

**Environment**
 - Device:  Windows
 - Browser: chrome 版本 74.0.3729.157（正式版本） （64 位）
 - Vant Version: 1.6.18

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
调用 `toast.clear()` 只会清除这一个 toast 实例

清除所有实例，请调用 `Toast.clear(true)`

**Comment by YH390389859** [comment]
> 调用 `toast.clear()` 只会清除这一个 toast 实例
> 
> 清除所有实例，请调用 `Toast.clear(true)`

在第一个请求发起实例了一个Toast以后在没有被toast.clear的时候发起的二次请求，又实例一次就会导致第一次的实例无法被清除，如果在每次获取response的时候就Toast.clear()的话，如果有请求还未结束也会清除掉所有的toast实例，这好像不大对头吧？

**Comment by yoyo837** [comment]
同样的问题，既然是实例，实例和实例之间不应该互相不影响，各自支持各自的关闭吗？
