### ISSUE TITLE
局部引用vant按需加载NoticeBar报错

### ISSUE THREAD

**Issue by SilentKc** [youzan/vant#3310]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 import { NoticeBar } from 'vant';
export default {
  components: {
    [NoticeBar.name]:NoticeBar
  },

**Reproduce**
<van-notice-bar :text="leftScollNote" background="#ffffff" color="#545454" left-icon="volume-o" @click="goPage('Notice')"/>

Unknown custom element: <van-notice-bar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3295

**Comment by SilentKc** [comment]
demo里提供的都没问题，就是一些组件，比如dialog，NoticeBar 引入就报错了


------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年5月16日(星期四) 下午2:13
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "Silent、"<532511275@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] 局部引用vant按需加载NoticeBar报错 (#3310)




参见 #3295

**Comment by chenjiahan** [comment]
可以 `console.log(NoticeBar)` 试下

**Comment by SilentKc** [comment]
有值。

就是这样引入就报错了

其他的组件比如这些

都没有问题


------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年5月16日(星期四) 下午2:31
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "Silent、"<532511275@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] 局部引用vant按需加载NoticeBar报错 (#3310)




可以 console.log(NoticeBar) 试下

**Comment by chenjiahan** [comment]
理论上不会出现这样的问题。
另外注意下, Dialog 是不能这样注册的，因为 Dialog 是一个函数，只能通过 Vue.use 注册

**Comment by SilentKc** [comment]
dialog我放在main.js里面处理了




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年5月16日(星期四) 下午2:36
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "Silent、"<532511275@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] 局部引用vant按需加载NoticeBar报错 (#3310)




理论上不会出现这样的问题。
 另外注意下, Dialog 是不能这样注册的，因为 Dialog 是一个函数，只能通过 Vue.use 注册
