### ISSUE TITLE
van-tabs切换的时候，首次设置的那个底部有阴影 手机xr 系统12.2

### ISSUE THREAD

**Issue by guanweitao** [youzan/vant#3312]
6s手机上没有问题，目前只发现在xr上有问题
![101557990524_ pic_hd](https://user-images.githubusercontent.com/25758249/57833497-b7bb3f80-77ec-11e9-8901-d3fe6eb6a3d8.jpg)
![111557990539_ pic_hd](https://user-images.githubusercontent.com/25758249/57833510-bc7ff380-77ec-11e9-8b21-6eeb3fb24e7a.jpg)

**Comment by chenjiahan** [comment]
我用 XR 试了下没复现喔，能否提供下 jsfiddle，或者确认下是不是其他样式干扰了

**Comment by guanweitao** [comment]
> 我用 XR 试了下没复现喔，能否提供下 jsfiddle，或者确认下是不是其他样式干扰了
我这边把van-tabs__wrap固定定位了，就会出现这个问题，没有固定定位就是好的

**Comment by chenjiahan** [comment]
麻烦提供下 jsfiddle，不清楚你的布局具体是什么样的

**Comment by olocrew** [comment]
请问解决了吗？我也这问题

**Comment by gwt9502** [comment]
没有




| |
关卫涛
|
|
邮箱：gwt9502@163.com
|

签名由 网易邮箱大师 定制

在2020年01月03日 13:19，olocrew 写道：

请问解决了吗？我也这问题
