### ISSUE TITLE
vw 布局下，datetime-picker 不能适应

### ISSUE THREAD

**Issue by GQxQD** [youzan/vant#3318]
**What problem does this feature solve?**
vw 布局下，datetime-picker 不能适应，postcss-px-to-viewport 只替换了css的，不能替换掉js动态设置的

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
目前无法支持，建议自行将 vw 转换为 px 传入 `item-height`，参见 https://github.com/youzan/vant/issues/3128
