### ISSUE TITLE
field  选择type 为number的时候无法输入小数，issue里面没看到类似的问题

### ISSUE THREAD

**Issue by PasserbyFluid** [youzan/vant#3319]
**What problem does this feature solve?**
field  选择type 为number的时候无法输入小数

**Describe the solution you'd like**
希望在filed触发出来数字键盘的时候可以输入带小数的数字

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
这个是浏览器的默认行为，建议使用`tel`类型
