### ISSUE TITLE
van-datetime-picker组件 v-model 传入  Invalid Date  导致浏览器卡死和手机浏览器卡死

### ISSUE THREAD

**Issue by tangolivesky** [youzan/vant#332]
**What is the current behavior?**

van-datetime-picker组件 v-model 传入  Invalid Date  导致浏览器卡死和手机浏览器卡死

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

let _date =  new Date("foo");
console.log(_date);  //Invalid Date
然后把 _date 传入 van-datetime-picker 的 v-model 

**What is the expected behavior?**

我这边可以判断异常，如果不是日期格式不传入值
但是感觉最好  如果传入了不正确的数据，浏览器也不会导致卡死

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

    vue: 2.3.3
    vant: 0.10.7
    browser: chrome
    OS:windows 10

**Comment by chenjiahan** [comment]
@tangolivesky 感谢反馈，将在下个版本修复

**Comment by chenjiahan** [comment]
已在 0.11.1 中优化
