### ISSUE TITLE
请问支持动态增加表单吗，比如我现在添加地址，想批量添加，支持动态增加吗？

### ISSUE THREAD

**Issue by roneywei** [youzan/vant#3320]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
支持的喔

**Comment by roneywei** [comment]
你好，请问下demo在哪里呢？

**Comment by chenjiahan** [comment]
没有这样的 Demo 呢

**Comment by roneywei** [comment]
建议增加这样的demo，因为我觉得这个功能还是能常用的，现在购物商城也很多都这样的需求，批量下单

**Comment by ethan666** [comment]
> 支持的喔

实际应用会遇到问题。
vant-field需要绑定值，需要在vue的data中先声明。但是动态表单不确定field，不好在data中声明

`<van-field
        v-for="item in fields"
        :key="item.key"
        clearable
        v-model="this[item.key]"
        :name="item.key"
        :label="item.name"
        :rules="[{ required: item.required, message: `请填写${item.name}` }]"
      >
        <van-datetime-picker
          v-if="item.type === 'date'"
          v-model="currentDate"
          type="date"
          title="选择年月日"
        />
      </van-field>`

表单绑定的值需要怎么处理呢？

**Comment by chenjiahan** [comment]
可以通过 $set 动态添加 data
