### ISSUE TITLE
<Picker /> 列表在 touchEnd 后，滚动动画不自然

### ISSUE THREAD

**Issue by ystarlongzi** [youzan/vant#3321]
**What problem does this feature solve?**
 - 优化 `touchEnd` 后列表的滚动效果
 - `change` 事件触发的时机
    - 用户有可能在列表滚动结束前又快速滚动了列表，所以在列表滚动动画结束后，再去触发 `change` 事件，是否更为合理些？同时看了下其它（如：antd、better-scroll、小程序等）项目的实现，也都是在动画结束后触发的 `change` 事件 

**Describe the solution you'd like**
 - 无

**What does the proposed API look like?**
 - 无

**Comment by ystarlongzi** [comment]
@chenjiahan 如果没意见，稍后我会提个 pr

**Comment by chenjiahan** [comment]
欢迎提 PR 哈

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.1 版本发布
