### ISSUE TITLE
弹出框Dialog，我引用了官网例子，点击事件未执行弹框就显示出来了，是什么原因？

### ISSUE THREAD

**Issue by syy1992** [youzan/vant#3322]
<template>
  <div id="detail">
    <van-dialog v-model="show" title="标题"  show-cancel-button>
      <img src="https://img.yzcdn.cn/1.jpg">
    </van-dialog>
    <div class='foot' @click='prompt'>
      <div class='foot-left '>
        <img src='https://jinheui.oss-cn-qingdao.aliyuncs.com/juhuibao/icon_kefu.png'>
      </div>
      <div class='flex-1'>
      </div>
      <div class='flex-1 button'>
        Vip专线咨询
      </div>
    </div>
  </div>
</template>
<script>
import { Button,Dialog} from 'vant'; //按需加载
export default {
  name: 'detail',
  data () {
    return {
      show:false,
    }
  },
  components: {
    "van-button": Button,
    "van-dialog":Dialog
  },
  methods: {
      prompt(){
        this.show = true
      }
  },
  mounted () {
  }
}
</script>

**Comment by chenjiahan** [comment]
`"van-dialog":Dialog ` 这句话是错的，请使用 Vue.use(Dialog)
