### ISSUE TITLE
弹出框的组件调用是怎么用的？我用了以后报错为vue.esm.js?efeb:628 [Vue warn]: Error in render: "TypeError: Cannot read property 'model' of undefined"

### ISSUE THREAD

**Issue by syy1992** [youzan/vant#3323]

**Comment by chenjiahan** [comment]
文档里写的很清楚了，请按照文档引入

**Comment by syy1992** [comment]
感谢，调用正常显示了。


 
---原始邮件---
发件人: "neverland"<notifications@github.com>
发送时间: 2019年5月17日(星期五) 下午5:26
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"yangyangyang"<2556840353@qq.com>;
主题: Re: [youzan/vant] 弹出框的组件调用是怎么用的？我用了以后报错为vue.esm.js?efeb:628 [Vue warn]: Error in render: "TypeError: Cannot read property 'model' of undefined" (#3323)



文档里写的很清楚了，请按照文档引入

**Comment by chaishi** [comment]
官方引入方式确实不会出现上述问题，但是以下使用方法会导致上述错误，希望该 issue 重新打开：

```html
<template>
  <div> <v-dialog v-model="show" title="弹框关闭会报错"></v-dialog> </div>
</tempalte>
```

```js
<script>
import VDialog from "vant/lib/dialog";
export default {
  components: { VDialog },
  data() {
    return {
      show: false
    }
  },
}
</script>
```

PS: 其他组件（field/picker/form等）按照这种写法不会报错，就 dialog 会。

**Comment by chenjiahan** [comment]
@chaishi 给个 codesandbox 复现链接
