### ISSUE TITLE
node_modules\vant\packages\style\var.less下的Search只有一个search-background-color变量,所以定制主题很多变量不起作用

### ISSUE THREAD

**Issue by 750973092** [youzan/vant#3325]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
2.0 版本会增加更多变量

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.0 版本支持
