### ISSUE TITLE
问下项目rem处理是用手淘flexible+postcss-px2rem处理rem的。但是在vant的组件样式里会缩小的，我单位是75px=1rem

### ISSUE THREAD

**Issue by curryhh** [youzan/vant#3330]
css: {
        loaderOptions: {
            postcss: {
                plugins: [
                        require('postcss-px2rem')({
                         remUnit:75,
                         exclude: /node_modules|folder_name/i
                       })//换算基数
                ]
            }
        }
    },

上面是我的配置处理，由于我已经写了不少页面才引入vant的  如果像vant37.5的话我的样式会变
有解决方法吗？

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/1181
