### ISSUE TITLE
vant的NoticeBar 在工业平板上没效果~

### ISSUE THREAD

**Issue by junhunlrw** [youzan/vant#3332]
vant的NoticeBar 在工业平板上没效果~需要怎么兼容工业平板？

**Comment by chenjiahan** [comment]
没了解过工业平板，是否是基于安卓的系统呢？可以看下安卓版本是多少

**Comment by junhunlrw** [comment]
------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 上午10:01
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "RONG"<1154393746@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] vant的NoticeBar 在工业平板上没效果~ (#3332)




没了解过工业平板，是否是基于安卓的系统呢？可以看下安卓版本是多少
 
回复：平板的安卓系统是5.1.1;我之前试过网页不在平板上显示，就把es6的语法改成es5的，把vue暴露出口的export default 改成export{}就可以显示了，不知道vant.js怎么兼容

**Comment by chenjiahan** [comment]
理论上来说安卓 5.1.1 是支持的，由于我们也找不到对应的设备，所以比较难排查问题的原因。。

**Comment by junhunlrw** [comment]
------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 上午10:29
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "???? ??????"<1154393746@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] vant的NoticeBar 在工业平板上没效果~ (#3332)

会不会跟vant的语法有关系呢？

**Comment by chenjiahan** [comment]
没用到安卓 5.1 的不支持的语法

**Comment by junhunlrw** [comment]
------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 下午3:27
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "RONG"<1154393746@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] vant的NoticeBar 在工业平板上没效果~ (#3332)




尴尬。。。。。

**Comment by 643104191** [comment]
是不是css兼容问题?
或者vuecli脚手架最终转码出来之后带了es6语法代码?

**Comment by junhunlrw** [comment]
------------------ 原始邮件 ------------------
发件人: "643104191"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 下午3:07
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "RONG"<1154393746@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] vant的NoticeBar 在工业平板上没效果~ (#3332)




是不是css兼容问题?
 或者vuecli脚手架最终转码出来之后带了es6语法代码?
 
css 应该不影响，我用less写的；我页面连let都不敢用，直接用var（我之前引入swiper连页面都不显示，后来改成引入vue-awesome-swiper才变正常 ，不知道这有什么区别）

**Comment by chenjiahan** [comment]
建议引入 vconsole 调试， 看下是否有代码报错

**Comment by junhunlrw** [comment]
------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 下午4:11
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "RONG"<1154393746@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] vant的NoticeBar 在工业平板上没效果~ (#3332)




算了，我已经换成marquee标签了，虽然废弃了，但是比搞vant省时。。。。

**Comment by chenjiahan** [comment]
ok
