### ISSUE TITLE
Vant 更新之后旧版本样式问题

### ISSUE THREAD

**Issue by chaode0620** [youzan/vant#3333]
**vant 更新之后样式问题**
vant 每次更新  旧的样式布局总是会出现问题 ；

**Screenshots**
vant 每次更新。在旧的上线项目维护时，无法固定版本，总是会出现样式问题；

**Comment by chenjiahan** [comment]
无法固定版本的原因是什么呢，建议使用 `yarn.lock`，或者把 `package.json` 里写死版本

**Comment by chaode0620** [comment]
用的就是yarn ，版本也写死了  ，样式该出问题的还是会不对。  




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年5月20日(星期一) 上午10:28
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "紫痕丿"<844364771@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] Vant 更新之后旧版本样式问题 (#3333)




无法固定版本的原因是什么呢，建议使用 yarn.lock，或者把 package.json 里写死版本

**Comment by chenjiahan** [comment]
那你应该研究一下为什么没锁住版本

**Comment by chaode0620** [comment]
@chenjiahan   终究还是不行，还是会更新到最新的版本，然后样式都乱了 。在package.json中写死版本之后。再次yarn一次，还是会更新至最新的版本。

**Comment by chenjiahan** [comment]
能看下你的 package.json 不
