### ISSUE TITLE
Uploader 图片上传不能调摄像头吗？

### ISSUE THREAD

**Issue by marie0119** [youzan/vant#3336]
开发大佬 你好，Uploader 图片上传不能调摄像头吗？安卓端，用cordova打包后调不了摄像头，是我不会使用这个组件吗？

**Comment by sky185959** [comment]
我也遇到这样的情况了，在小米5X手机（相机访问权限已允许）安卓webview中打开页面点击Uploader 图片上传没有任何反应，但是用手机端浏览器打开页面可以用调用摄像头拍照展示，有知道的告诉一下

**Comment by chenjiahan** [comment]
可以看下是不是 web-view 设置的问题，图片上传里面用的是原生的 input type="file"，没有做特殊处理

**Comment by dengjinlong** [comment]
建议增加captrue="camera" 属性

**Comment by chenjiahan** [comment]
capture 支持的，后续会在文档里补充下

**Comment by chenjiahan** [comment]
文档已更新

**Comment by RookieDouby** [comment]
太难受啊，webview里边不能直接调用摄像头，怎么解决

**Comment by hWwXx** [comment]
安卓端，用cordova打包后调不了摄像头，不管我怎么加什么参数，都无法调用
