### ISSUE TITLE
style bug： vant-tabs 顶部的线没有API关闭

### ISSUE THREAD

**Issue by 0123cf** [youzan/vant#3338]
![image](https://user-images.githubusercontent.com/22963895/58073597-98018e00-7bd5-11e9-9859-ea216440e5a2.png)

复现代码（就是正常的加个背景色）
```
<van-tabs background="#5E8EFE"
        color="#FFFFFF"
        sticky
        :offset-top="43"
        v-model="tabindex"
        @click="checktab"
        swipeable
        title-active-color="#FFFFFF"
        title-inactive-color="#FFFFFF"
        >
        <van-tab v-for="(item,index) in tabsList"
            :key="index"
            :title="item.name">
   
        </van-tab>
    </van-tabs>
```

这个是由以下css样式控制：
.van-hairline--top-bottom::after

**Comment by chenjiahan** [comment]
后面会加个 api

**Comment by 0123cf** [comment]
nice

**Comment by hanjunqiang** [comment]
> 后面会加个 api

大哥，什么时候可以加api?

**Comment by chenjiahan** [comment]
@hanjunqiang border 属性

**Comment by hanjunqiang** [comment]
> @hanjunqiang border 属性

    <div style='background:rgb(35, 61, 135)' >sdkfasdj</div> 
          <van-tabs class='tabs' border='false' v-model="tabIndex" color='yellow' background='blue' line-width='20' line-height='5' title-active-color='white' title-inactive-color='gray'>
            <van-tab  title="首页"></van-tab>
            <van-tab title="中长协"></van-tab>
            <van-tab title="挂牌"></van-tab>
            <van-tab title="缴费"></van-tab>
          </van-tabs>
  </div>

**Comment by hanjunqiang** [comment]
> @hanjunqiang border 属性
type默认是line, 我设置了border没有作用

**Comment by hanjunqiang** [comment]
> 后面会加个 api

大哥，有空给指导下，谢谢

**Comment by chenjiahan** [comment]
前面要加冒号 :border="false"

**Comment by hanjunqiang** [comment]
谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: neverland <notifications@github.com&gt;
发送时间: 2020年1月27日 09:11
收件人: youzan/vant <vant@noreply.github.com&gt;
抄送: Mr.han <904410775@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[youzan/vant] style bug： vant-tabs 顶部的线没有API关闭 (#3338)




前面要加冒号 :border="false"
