### ISSUE TITLE
官网Actionsheet 上拉菜单跳转demo链接错误

### ISSUE THREAD

**Issue by dianjie** [youzan/vant#3339]
![微信图片_20190521150917](https://user-images.githubusercontent.com/16601627/58075503-7656d580-7bda-11e9-8a70-9833598c22de.png)

`actionsheet`中间少了`-`，应该是`action-sheet`
正确链接：https://github.com/youzan/vant/blob/dev/packages/action-sheet/demo/index.vue

**Comment by chenjiahan** [comment]
感谢反馈，已经修复咯
