### ISSUE TITLE
Uploader 图片上传时oversize可以也加上detail参数吗？否则经过压缩就取不到name了

### ISSUE THREAD

**Issue by gbyuxia** [youzan/vant#3340]
**What problem does this feature solve?**
希望Uploader 图片上传时oversize可以也加上detail参数

**Describe the solution you'd like**
目前Uploader 组件在图片上传时oversize的方法没法传递detail参数，经过压缩就取不到name了。在一个页面有多组上传、都需要图片大小判断自己压缩时有需要

**What does the proposed API look like?**
 onAfterRead: function onAfterRead(files, oversize) {
            if (oversize) {
                this.$emit('oversize', files, this.detail);
            } else {
                this.afterRead && this.afterRead(files, this.detail);
            }

            this.resetInput();
        },

**Comment by chenjiahan** [comment]
可以的，后续会加上

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.1 版本支持

**Comment by shen-lan** [comment]
兄弟你的图片压缩怎么做的
