### ISSUE TITLE
点击页面底部元素，弹出键盘或者选择框的时候挡住了输入框，有没有解决方案

### ISSUE THREAD

**Issue by PasserbyFluid** [youzan/vant#3341]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**
如图 http://app.itolddriver.com/1.png http://app.itolddriver.com/2.png
图一是开始元素的样子，点击日期选择框，弹出遮住了

**What does the proposed API look like?**
希望点击的时候元素能向上滚动一下，选择完成的时候再回来。

**Comment by chenjiahan** [comment]
这个建议自行控制哈，组件内不会封装这样的逻辑
