### ISSUE TITLE
全局引入$toast时,如果loading和success同时出现会报错.

### ISSUE THREAD

**Issue by caihuattkl** [youzan/vant#3342]
引起bug代码(无论加不加this.$toast.clear();都会有错误):
![image](https://user-images.githubusercontent.com/18523369/58153594-03b12d00-7ca2-11e9-9ba2-c292de3ee9a5.png)
错误信息:
![image](https://user-images.githubusercontent.com/18523369/58153715-57bc1180-7ca2-11e9-9cbb-b0418f2c550e.png)

**Comment by chenjiahan** [comment]
试了下没问题，能提供 jsfiddle 不

**Comment by caihuattkl** [comment]
检查了本地代码,是本地代码冲突了!

**Comment by caihuattkl** [comment]
不好意思!

**Comment by chenjiahan** [comment]
没事哈

**Comment by zhayes** [comment]
@caihuattkl  我遇到了一样的问题，请问你所谓的本地代码冲突是什么。我之前写法没问题的，是在往TS方向改造的过程中，报这个错，直接崩溃。一直没找到原因。
