### ISSUE TITLE
Picker slot插槽

### ISSUE THREAD

**Issue by chen-can** [youzan/vant#3346]
Picker slot插槽 columns可以部分文字内容可以突出显示如 “优惠2元” 日期100-000-000
优惠2元 可以显示为红色字体

**Comment by chenjiahan** [comment]
目前提供不了这样的插槽喔，不过 Picker 的文字是支持渲染 HTML 的，你直接用 HTML 就可以实现这样的效果

**Comment by chen-can** [comment]
可以了 谢谢
