### ISSUE TITLE
DropdownMenu的菜单标题（displayTitle）可以控制状态或者样式吗？

### ISSUE THREAD

**Issue by thiszhong** [youzan/vant#3347]
**What problem does this feature solve?**
现在是只有当这个菜单下拉展开时，才会触发标题的active-color

**Describe the solution you'd like**
想要的效果是：如果一个菜单的子菜单选中的不是第一个（第一个一般是默认），则该菜单为active状态（而不是只有展开时）。或者自定义模式下想要更灵活的去控制主菜单的样式及状态。
是否可以外部控制active状态，或者给个`titleStyle / titleClass`，我们可以去覆盖样式

**What does the proposed API look like?**
`<DropdownItem active style class... />`
 现在的style貌似默认挂到options的根结点上了

**Comment by chenjiahan** [comment]
可以的，下个版本会加一个 `titleClass` 属性

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.1 版本支持

**Comment by Lan-megumi** [comment]
> 已在 2.0.0-beta.1 版本支持

貌似在引用的父页的style加了 scoped会找不到对应的class，如果把自定义class放全局全重又不够自带的 '.van-dropdown-menu__title'高...
