### ISSUE TITLE
tab组件，如何触发tab头部选中底线的动画调整，有时候对不齐，

### ISSUE THREAD

**Issue by liangShengSen** [youzan/vant#3348]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by liangShengSen** [comment]
![image](https://user-images.githubusercontent.com/21200409/58219014-dd3fd000-7d3b-11e9-8109-840328dc6345.png)

**Comment by chenjiahan** [comment]
能提供下 jsfiddle 吗，得确认下引起对不齐的原因

**Comment by liangShengSen** [comment]
没有哦，我是改变了布局，设定了头部的宽度，然后给每个van-tab设定了最大宽度，超出就点点点，当反复切换就会出现对不齐的，特别是从短的文字切换到长的文字

**Comment by chenjiahan** [comment]
那能不能把你设定样式的 `css` 发下，我看下能否从代码层面兼容

**Comment by liangShengSen** [comment]
![image](https://user-images.githubusercontent.com/21200409/58222384-7248c600-7d48-11e9-8d34-3ec1d2ac693f.png)
之所以改了flex布局就是因为当头部的文字有长有短的时候两个tab之间文字的间距视觉上看的不统一，虽然他们宽度是一样的
![image](https://user-images.githubusercontent.com/21200409/58222798-d750eb80-7d49-11e9-96e0-1bd16a9bd6a8.png)

**Comment by liangShengSen** [comment]
还有几个问题就是有些组件查看源代码的时候没有吧节点渲染出来，有些又是可以，比如带链接的a标签，这样对seo又不友好，还有就是list这个组件在ios上滑动不平滑，安卓没问题。。

**Comment by chenjiahan** [comment]
别用 margin，用 padding 来设置间距，这样才能正确计算选项的宽度

> 还有几个问题就是有些组件查看源代码的时候没有吧节点渲染出来，有些又是可以，比如带链接的a标签，这样对seo又不友好，还有就是list这个组件在ios上滑动不平滑，安卓没问题。。

这个问题可以用`lazy-render`属性解决
