### ISSUE TITLE
下拉菜单无法正常使用

### ISSUE THREAD

**Issue by liujuesi** [youzan/vant#3349]
**Describe the bug**
DropdownMenu 下拉菜单 出现报错，找不到指定的模块

**Screenshots**
![image](https://user-images.githubusercontent.com/45506410/58220397-42e28b00-7d41-11e9-94b7-3b41496cf11a.png)
![image](https://user-images.githubusercontent.com/45506410/58220457-889f5380-7d41-11e9-928a-61613d19f8d7.png)

**Environment**
 - Device: windows10
 - Browser: 谷歌浏览器
 - Vant Version: 

**Reproduce**

**Comment by chenjiahan** [comment]
请确认你升级到了 vant@2.0.0-beta.0 版本
