### ISSUE TITLE
UC浏览器tabs无法滑动切换滚动

### ISSUE THREAD

**Issue by ChinaMars** [youzan/vant#3350]
UC浏览器tabs无法滑动切换滚动

**Screenshots**
![Screenshot_2019-05-23-10-08-19-808_com UCMobile](https://user-images.githubusercontent.com/29267545/58220808-e7190180-7d42-11e9-81cf-f989834a2494.png)

**Environment**
 - Device: 小米8（MIUI10.3）
 - Browser: UC浏览器（V12.4.6.1026）
 - Vant Version: ^1.6.15

**Reproduce**
查看我的github：https://github.com/ChinaMars/vue-archive

**Comment by ChinaMars** [comment]
有人碰到我这样的问题吗？

**Comment by chenjiahan** [comment]
我用 iOS 的 UC 试了下木有问题

**Comment by sjwwap** [comment]
我也遇到了，就安卓的UC浏览器有问题；
