### ISSUE TITLE
van-rate 重叠bug

### ISSUE THREAD

**Issue by AuthWang** [youzan/vant#3353]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
评分插件有时会出现重叠两颗星星现象

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/30521045/58221379-f1d49600-7d44-11e9-9f62-b07d06cf59c9.png)

**Environment**
 - Device: macbook pro
 - Browser: 谷歌
 - Vant Version: 1.6.19

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
能提供下 jsfiddle 吗

**Comment by AuthWang** [comment]
> 能提供下jsfiddle吗，可能是某些全局样式引起的

现在无法打开jsfiddle，稍晚一点我看看能不能打开，感谢您的跟进

**Comment by chenjiahan** [comment]
好的

**Comment by AuthWang** [comment]
> 好的

我试过开代理翻墙也无法打开jsfiddle, 找了个国内的jsrun 但不知道如何实现

**Comment by AuthWang** [comment]
![image](https://user-images.githubusercontent.com/30521045/58265963-51698a80-7db3-11e9-86a3-f8e9cac7b081.png)
找出了具体原因，因全局样式问题，但van-icon在移动端一直都会往下偏移一点点

**Comment by AuthWang** [comment]
![image](https://user-images.githubusercontent.com/30521045/58266128-a6a59c00-7db3-11e9-81c6-91ead0507176.png)

找出了具体原因，因全局样式问题，但van-icon图标在移动端一直都会往下偏移一点点

**Comment by AuthWang** [comment]
> ![图片](https://user-images.githubusercontent.com/30521045/58266128-a6a59c00-7db3-11e9-81c6-91ead0507176.png)
> 
> 找出了具体原因，因全局样式问题，但厢式图标图标在移动端一直都会往下偏移一点点

但是去掉了还是会出现重叠bug

**Comment by AuthWang** [comment]
已经检查没有其他任何公共样式影响

**Comment by chenjiahan** [comment]
这个 top 3px 是怎么来的呢，vant 样式里并没有这样写
