### ISSUE TITLE
下拉刷新在在手机上无效

### ISSUE THREAD

**Issue by SnowBeatRain** [youzan/vant#3354]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
按照官网方法通过按需引入写的下拉刷新，在电脑上正常，但是在手机上无效（只有我的手机无效，别人的ios和安卓的手机甚至和我的手机一样的6s都可以）

**Screenshots**
![image](https://user-images.githubusercontent.com/26265459/58223511-87275880-7d4c-11e9-9fe5-ceff8e4a9bb9.png)

**Environment**
 - Device: iphone 6s ios系统10.3.1 
 - Browser:  微信浏览器和钉钉 qq浏览器都试过
 - Vant Version: "vant": "^1.6.19",

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3015
