### ISSUE TITLE
steps步骤条每个step自定义图标无效

### ISSUE THREAD

**Issue by wananzys** [youzan/vant#3355]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
steps步骤条每个step自定义图标无效

**Screenshots**
![image](https://user-images.githubusercontent.com/44047260/58223709-64e20a80-7d4d-11e9-981f-19e683c9a3bc.png)
![image](https://user-images.githubusercontent.com/44047260/58223733-79260780-7d4d-11e9-85f9-34965ac7566b.png)

**Environment**
 - Device: webAPP
 - Browser: Chrome
 - Vant Version: 2.0.0-beta.0

**Comment by wananzys** [comment]
官方文档上没有示例,不知道是不是这样写的?

**Comment by chenjiahan** [comment]
slot 拼错了，是 slot="xxx"，不是 slots="xxx"
