### ISSUE TITLE
toast增加手动调用显示的方法 toast.show()

### ISSUE THREAD

**Issue by LeeRayno** [youzan/vant#3357]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
可以手动调用toast显示
**Describe the solution you'd like**
```js
const toast = Toast.loading({
  duration: 0,       // 持续展示 toast
  forbidClick: true, // 禁用背景点击
  loadingType: 'spinner',
  message: '倒计时 3 秒'
});

toast.clear()

toast.show() // 手动显示
```

**What does the proposed API look like?**
```js
toast.show()
```

**Comment by chenjiahan** [comment]
评估了一下，暂时不考虑提供这样的用法，建议再次调用`Toast.loading`去展示，效果是一样的

1. 这种用法容易产生混乱，不能明确的表示出本次调用对应的 duration、message 等信息
2. 多实例模式下，`toast.clear` 后实例就被回收了，没法再次展示

**Comment by LeeRayno** [comment]
再次调用 `Toast.loading`不会再次创建个实例吗。
我们目前是这样做的。
```js
// axios 请求拦截里面 显示 loading
let toast
if (!toast) {
  toast =Toast('第一个 Toast');
}  else {
  toast.value = true
}

// axios 相应拦截里面隐藏 loading
toast.clear()
```

**Comment by chenjiahan** [comment]
单例模式下（默认），再次调用 Toast.loading 不会重复创建实例，上面的操作没必要

**Comment by chenjiahan** [comment]
单例模式下（默认），再次调用 Toast.loading 不会重复创建实例，上面的操作没必要

**Comment by LeeRayno** [comment]
好吧。可能是我们的代码有问题，创建了多个。。。

**Comment by chenjiahan** [comment]
应该是这个问题，https://github.com/youzan/vant/issues/3448 后续会在 3448 issue 中跟进
