### ISSUE TITLE
van-dialog里面放van-field，在IOS8滑到底部后，点击van-field输入，发现Dialog组件是被输入法输入区域遮盖的，如果不滑到底进行同样操作，Dialog会被输入法区域顶上去不会遮盖，请问这个怎么解决哈？

### ISSUE THREAD

**Issue by benbenyao** [youzan/vant#3358]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
解决不了哈，这个是浏览器控制的，不过你可以自己调用 scrollTo 试试
