### ISSUE TITLE
Sku组件中，有其他子组件通过$emit传参，使用$refs修改selectedNum，修改成功，页面却未渲染？

### ISSUE THREAD

**Issue by q784744581** [youzan/vant#3360]
Describe the bug
Sku组件中，有其他子组件通过$emit传参，使用$refs修改selectedNum，修改成功，页面却未渲染？
**Environment**
 -环境：微信H5
 - Vant Version: 1.6.14

**Comment by ajie752369** [comment]
您好，请问你解决这个问题没，我也遇到了，不知如何解决，谢谢回答

**Comment by xinSanta** [comment]
解决了吗2024年了，我也遇到了这个问题
