### ISSUE TITLE
DropdownMenu 能否增加关闭动画

### ISSUE THREAD

**Issue by limscript** [youzan/vant#3361]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
关闭DropdownMenu时直接消失太不友好了
**Describe the solution you'd like**
能否像打开时一样加个动画效果，并且增加配置动画时长

**What does the proposed API look like?**
可参考van-popup组件

**Comment by chenjiahan** [comment]
下个版本加上

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.1 版本支持
