### ISSUE TITLE
按需导入组件后，DropdownMenu报错

### ISSUE THREAD

**Issue by shuai3709211** [youzan/vant#3362]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
 vant/es/dropdown-item in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/WavePicking.vue?vue&type=script&lang=js&
* vant/es/dropdown-item/style/less in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/WavePicking.vue?vue&type=script&lang=js&
* vant/es/dropdown-menu in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/WavePicking.vue?vue&type=script&lang=js&
* vant/es/dropdown-menu/style/less in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/WavePicking.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save vant/es/dropdown-item vant/es/dropdown-item/style/less vant/es/dropdown-menu vant/es/dropdown-menu/style/less   

**Screenshots**
![CD02CDAC560A3A2CDF87F6D7559991F4](https://user-images.githubusercontent.com/13127944/58251075-69caac80-7d95-11e9-8ae4-3a267ca1a952.jpg)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by azhengyongqin** [comment]
请问您解决了吗？ 我也是这个问题！
