### ISSUE TITLE
dropdown-menu弹出位置在手机浏览器不正确

### ISSUE THREAD

**Issue by linxun56** [youzan/vant#3363]
**Describe the bug**
chrome上dropdown-menu使用下拉正常弹出位置，在手机上弹出位置变成顶部弹出了

**Screenshots**
![微信截图_20190524093444](https://user-images.githubusercontent.com/50936829/58296845-07f75a80-7e08-11e9-8da7-48b96e7dbdc7.png)
![微信截图_20190524094021](https://user-images.githubusercontent.com/50936829/58296851-0cbc0e80-7e08-11e9-8f96-180e00ce1dd6.png)
![微信截图_20190524094000](https://user-images.githubusercontent.com/50936829/58296854-0d54a500-7e08-11e9-9062-96ebf43590da.png)

**Environment**
 - Device: nokia x6
 - Browser: chrome
 - Vant Version: 2.0

**Comment by chenjiahan** [comment]
文档示例中没问题，是特定机型的问题吗？可以用这个手机打开示例看下

**Comment by linxun56** [comment]
> 文档示例中没问题，是特定机型的问题吗？可以用这个手机打开示例看下

确实这个机型不行，示例也是一样的效果

**Comment by linxun56** [comment]
> 文档示例中没问题，是特定机型的问题吗？可以用这个手机打开示例看下

我试了其他手机，魅族的和IOS都不行啊，这个组件要修改嘛？

**Comment by chenjiahan** [comment]
能提供一下文档示例有问题的截图吗，还有系统版本

**Comment by linxun56** [comment]
> 能提供一下文档示例有问题的截图吗，还有系统版本

跟我上面的截图是一样的效果，都是从顶部弹出了。我用的iphone6p 微信扫的，还有魅族的系统是6.0，nokia的那个是9.0

**Comment by linxun56** [comment]
> 能提供一下文档示例有问题的截图吗，还有系统版本

你们使用的啥手机是正常的？

**Comment by chenjiahan** [comment]
我在 iOS9 上复现这个问题了，会在下个 beta 版本修复

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.1 版本修复

**Comment by Ghjsw** [comment]
手机上 只要滚动条滑动就会复现
