### ISSUE TITLE
van-action-sheet在项目中报错 提示未注册 

### ISSUE THREAD

**Issue by skymon4** [youzan/vant#3364]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/
全局引入的vant 其他的组件都可以 唯独上拉和下拉组件不行
![image](https://user-images.githubusercontent.com/33510540/58303176-8e6c6600-7e21-11e9-964d-88003c5048d6.png)
![image](https://user-images.githubusercontent.com/33510540/58303196-9f1cdc00-7e21-11e9-8a97-c06e5d92df80.png)

**Comment by skymon4** [comment]
找到了问题 官网demo中 为 van-action-sheet 我用van-actionsheet正常 无任何报错

**Comment by PasserbyFluid** [comment]
+1

**Comment by 643104191** [comment]
版本问题

**Comment by skymon4** [comment]
> 版本问题

我用是vant 最新版本
![image](https://user-images.githubusercontent.com/33510540/58313089-5aa03900-7e3f-11e9-8528-0501a6aae589.png)

**Comment by chenjiahan** [comment]
1.6 版本是 Actionsheet，2.0 版本是 ActionSheet，使用的时候请注意下文档版本，后续会加个版本提示

**Comment by cdscawd** [comment]
坑啊 出来挨打

**Comment by qianlanse** [comment]
提问：van-action-sheet页面渲染不出来，也不报错
版本：2.2.9
场景：nuxt
方式：自动按需引入组件
![WX20191025-134940](https://user-images.githubusercontent.com/13144533/67546210-5cdc2b80-f72e-11e9-840e-9eb3f1f52038.png)
