### ISSUE TITLE
popup中顶部和底部<div>fixed无效，请问有什么解决方案么

### ISSUE THREAD

**Issue by AtlantaCaesar** [youzan/vant#3365]
[IMPORTANT:](url) Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
`popup布局中顶部和底部的div设置fixed无效`

`<van-popup class="specification-popup" v-model="sku_specification_popup" position="bottom"
        v-bind:style="popup_height">

        <div class="good-info">
            <div class="div-1">
                <img src="/File/Imag/test.jpg" alt="">
            </div>
            <div class="div-2">
                <p class="good-title">商品名称商品名称商品名称商品名称商品名称商品名称商品名称商品名称商品名称商品名称</p>
                <p class="good-price price">零售价
                    <i class="CNY_left">100</i>
                </p>
                <p class="vip-price price">会员价
                    <i class="CNY_left">100</i>
                    <span class="inventory">库存1000</span>
                </p>
            </div>
            <div class="div-3">
                <i class="icon-close" @click="closeSKUSpec()"></i>
            </div>
        </div>
        <div class="scroll-mid">
            <dl class="specification">
                <dt>规格</dt>
                <dd v-if="ProductSpecs==null">
                    <div class="black">
                        <span class="def">该物品暂时下架</span>
                    </div>
                </dd>
                <dd v-else v-for="(item,index) in 10">
                    <div :class="{red: activeName == item}">
                        <span class="def" v-on:click="colour_span(item)">iphone7/8 plus 复古ins风橘子背景升级款</span>
                    </div>
                </dd>
            </dl>
            <dl class="stepper">
                <dt>数量</dt>
                <dd>
                    <van-stepper class="sku-stepper" v-model="sku_number" :integer="true" />
                </dd>
            </dl>
        </div>
        <button class="btn-buy-now">立即购买</button>
    </van-popup>`

**Screenshots**
![issue](https://user-images.githubusercontent.com/22053304/58308990-90402480-7e35-11e9-8e9f-1edfdb189b3e.gif)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.6.19 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
这个是浏览器限制的，transform 元素内部的 fixed 会变成 absolute
方案有两个：
1. 按钮 absolute 吸底，列表局部滚动
2. 升级到 vant 2.0，针对底部的 popup 去掉了 transform
