### ISSUE TITLE
新版本的vant2.x的文档建议在"快速上手"章节带上正确版本

### ISSUE THREAD

**Issue by 643104191** [youzan/vant#3366]
自从出了2.x版本之后
现在官方的qq群和git上的issues上每天都有粗心的人说vant怎么引入xxx组件不成功

![bug](https://user-images.githubusercontent.com/27074730/58310309-eb274b00-7e38-11e9-87e8-4621fc92f090.png)

所以建议像上图那样加上正确的版本号

**Comment by chenjiahan** [comment]
嗯呐，这里是要改下，今天会处理掉

**Comment by uyoungco** [comment]
想用2.0 可是NPM没有啊

**Comment by 643104191** [comment]
> 想用2.0 可是NPM没有啊

下面这个命令了解一下???
```bash
npm view vant versions
```
