### ISSUE TITLE
[Feature Request] 能否为IndexBar组件新增索引悬停和右侧高亮提示功能

### ISSUE THREAD

**Issue by dongj0316** [youzan/vant#3367]
**What problem does this feature solve?**
更好的交互效果

**What does the proposed API look like?**
效果类似于https://dongj0316.github.io/vue-address-book/demo/#/
用vant比较久了，自己粗略实现了下这个功能，现在发现vant支持了这个组件，希望越做越好哦

**Comment by chenjiahan** [comment]
计划是后续支持这俩功能，欢迎提 PR 实现 ^_^

**Comment by dongj0316** [comment]
大佬，我刚看了下现有的源码实现方式，我的思路可能和源码稍微有些差别，改动有点大能接受吗^_^

**Comment by chenjiahan** [comment]
具体是什么样的改动，可以描述下嘛

**Comment by dongj0316** [comment]
现有的api不会变动，主要是多一个滚动事件监听来支持悬停索引的平滑变化，影响IndexBar和IndexAnchor的布局

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.3 版本发布
