### ISSUE TITLE
调用ImagePreview组件   当页面发生变销毁,跳转等. ImagePreview组件不会跟随页面一起销毁

### ISSUE THREAD

**Issue by doyw** [youzan/vant#3370]
混合开发.  webview区域是无法覆盖原生header. 导致浏览大图时可以后退.  
后退后ImagePreview组件依然存在

**Comment by chenjiahan** [comment]
下个版本会加个`closeOnPopstate`属性，用于控制后退时是否关闭

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.2 版本支持
