### ISSUE TITLE
icon 使用报错

### ISSUE THREAD

**Issue by boogoogle** [youzan/vant#3371]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
使用2.0-beta的版本, icon在使用是报错

引入部分
`
import Vant from 'vant';
import 'vant/lib/index.css';
import 'vant/lib/icon/local.css';
Vue.use(Vant);
`

使用部分
`
<div class="now-date" @click="dateOpen">
                <div>{{currentDate}} <van-icon name="arrow" key="arrow"/> </div>
            </div>
`

**Screenshots**
![image](https://user-images.githubusercontent.com/23280284/58322608-0a7fa180-7e54-11e9-9815-0c3db9137e3d.png)

**Comment by chenjiahan** [comment]
看起来不是 vant 的问题，建议自行排查下，或者提供一下 jsfiddle
