### ISSUE TITLE
图片懒加载组件在google  disable cache后请求两次

### ISSUE THREAD

**Issue by huzewei** [youzan/vant#3372]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
google  disable cache后请求两次图片

**Screenshots**
![image](https://user-images.githubusercontent.com/19965528/58328960-06f51600-7e66-11e9-9d95-ce104699b0d7.png)

**Environment**
 - Device: iphone 6/7/8
 - Browser: google 74.0.3729.169
 - Vant Version: 1.6.9

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
1. 不是请求两次，而是两个 img 标签都发起了这个请求
2. disable cache 模式下这样是正常的，正常情况下只会有一次请求
