### ISSUE TITLE
[Feature Request] Area建议暴露setValues方法，回填表单

### ISSUE THREAD

**Issue by jasconchen** [youzan/vant#3373]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

What problem does this feature solve?
Area建议暴露setValues方法

Describe the solution you'd like
Area建议暴露setValues方法

What does the proposed API look like?

[ setValues] [设置所有列选中的值] [values]

**Comment by chenjiahan** [comment]
什么场景下需要呢？

**Comment by jasconchen** [comment]
最近二次封装Popup+Area+Field时发现表单回填时Area组件传入code没有正确显示。
vant版本 => "vant": "^1.6.19"

**Comment by chenjiahan** [comment]
能提供下 jsfiddle 吗

**Comment by jasconchen** [comment]
http://jsrun.net/AbyKp/play

**Comment by chenjiahan** [comment]
看了一下，代码比较多，没找到问题所在的地方，能简单解释下吗

**Comment by jasconchen** [comment]
![image](https://user-images.githubusercontent.com/16459997/58379696-bbfc0f80-7fd9-11e9-87e1-e5d4b7f39ce7.png)
场景是这样的：
1.有显示默认值（这一步实现了）
2.用户滑动Area组件，然后点击取消按钮（注意默认值没有改变）
3.再次打开Area组件，组件没有设置正确的位置

**Comment by jasconchen** [comment]
![image](https://user-images.githubusercontent.com/16459997/58379740-5e1bf780-7fda-11e9-83a2-c621640af118.png)
1.回显默认值的代码

**Comment by jasconchen** [comment]
现在代码是默认选中
`
currentText, 北京市-北京市-西城区
currentCode, 110102
`
但是用户滑动Area组件到东城区，然后点击取消按钮
第二次打开没有正确回显上述选中项

**Comment by chenjiahan** [comment]
明白咯，下个版本会加上 setValues 方法

**Comment by jasconchen** [comment]
好的，谢谢

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.2 版本支持

**Comment by lizy0329** [comment]
> 已在 2.0.0-beta.2 版本支持

如果2.0.0版本以下怎么做这个功能？
