### ISSUE TITLE
关于时间选择器

### ISSUE THREAD

**Issue by YeJch** [youzan/vant#3374]
强烈要求 把时间选择器 和 弹出层或者是field  二合一 一块用。

**Comment by YeJch** [comment]
现在用的时候  必须 field + picker + popup 才能用  多次嵌套 好麻烦的，
建议参考一下 Vonic 的那种  一步到位 多好用阿

**Comment by chenjiahan** [comment]
暂时没有计划修改喔，组件粒度小更加灵活
