### ISSUE TITLE
windows 系统 build生成的路径不对

### ISSUE THREAD

**Issue by linxun56** [youzan/vant#3377]
**Describe the bug**
下载的好的版本，run build:lib 生成的es文件下的每个组件的style文件下的js文件是这样的格式

![image](https://user-images.githubusercontent.com/50936829/58366444-efb93580-7f04-11e9-8f78-eaf05c8ed842.png)

babel-plugin-import使用按需导入，就说找不到css文件报错，

![image](https://user-images.githubusercontent.com/50936829/58366459-2f801d00-7f05-11e9-8d3b-a3d4242fb620.png)

![image](https://user-images.githubusercontent.com/50936829/58366450-11b2b800-7f05-11e9-8394-c193d1467929.png)
woxiugai我修改这样就好了，没报错。
是我使用的生成方式不对吗

**Comment by chenjiahan** [comment]
这里应该是 windows 下生成的路径问题，我们开发用的 mac，所以没发现...欢迎提 PR 帮我们修复

**Comment by chenjiahan** [comment]
已经增加 windows 下的路径兼容处理
