### ISSUE TITLE
image 组件丢失

### ISSUE THREAD

**Issue by chen-can** [youzan/vant#3379]
查看node包没有image文件夹
报错信息
* vant/es/image in ./src/lib/vant.js
* vant/es/image/style in ./src/lib/vant.js

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3364

**Comment by chen-can** [comment]
不是这个原因， 我是按需引入的

**Comment by chenjiahan** [comment]
Image 在 2.0 版本才有，要安装 2.0.0-beta.1
