### ISSUE TITLE
ssr

### ISSUE THREAD

**Issue by yangbai1991** [youzan/vant#338]
现在还不支持ssr吗
我在里面使用 有些组件就会有 "he client-side rendered virtual DOM tree is not matching server-rendered content..."的警告

**Comment by chenjiahan** [comment]
@yangbai1991 收到反馈，近期会对完善对 SSR 的支持

**Comment by chenjiahan** [comment]
已在 0.11.1 中修复 Sku、AddressEdit SSR 报错的问题
