### ISSUE TITLE
van-image 不存在

### ISSUE THREAD

**Issue by zjutjsj1004** [youzan/vant#3380]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
在文档：https://youzan.github.io/vant/#/zh-CN/image 中，提到使用 van-image,
但是在vant的dist目录下面，没有看到image相关文件夹，请问我需要如何进行使用

**Screenshots**
无.

**Environment**
 - Device: 微信开发者工具 1.02.1904090
 - Browser: 无
 - Vant Version: v2.0.0-beta.0

**Reproduce**
无

**Comment by chenjiahan** [comment]
请确认你安装了 beta 版本
