### ISSUE TITLE
tab组件缓存问题

### ISSUE THREAD

**Issue by lsxlsxxslxsl** [youzan/vant#3381]
用tab分页分别有上拉加载的功能，但是tab组件会把数据缓存下来，没法实时请求最新数据

**Comment by chenjiahan** [comment]
这个是默认逻辑呢，不是 Tab 缓存了数据。如果你想要每次切换 tab 的时候清空数据，监听 change 事件，然后自行处理就好

**Comment by Nick091608** [comment]
tab+list 为什么下拉刷新的时候会多次触发上拉加载事件
