### ISSUE TITLE
Search的搜索图标在左边，建议支持自定义放在左边或者右边。

### ISSUE THREAD

**Issue by benbenyao** [youzan/vant#3382]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
下个版本会支持自定义左侧或右侧的图标

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.2 版本支持
