### ISSUE TITLE
Pagination 分页组件total-items异步返回的问题

### ISSUE THREAD

**Issue by manfwh** [youzan/vant#3383]
当total-items异步返回，并且currentPage大于1的时候，会自动执行一次change函数，val值会是1，应该不自动执行change函数才对

![微信截图_20190527131805](https://user-images.githubusercontent.com/23977810/58397058-e86b6680-8081-11e9-99e1-138f15d413fb.png)

win7 chrome vant:^2.0.0-beta.1

https://codepen.io/manfwh/pen/MdXwVN?editors=1011

**Comment by chenjiahan** [comment]
下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 1.6.20 版本和 2.0.0-beta,2 版本修复
