### ISSUE TITLE
popup transform 导致 fixed 定位失效

### ISSUE THREAD

**Issue by macheteHot** [youzan/vant#3385]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
popup 使用transform 样式 导致内部fixed 定位失效

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: chrome
 - Vant Version: 1.6.19

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3365

**Comment by macheteHot** [comment]
牛逼 秒回, 不愧996

**Comment by chenjiahan** [comment]
😂😂
