### ISSUE TITLE
search组件聚焦后清除叉子在chrome64版本下，失效

### ISSUE THREAD

**Issue by 469598690** [youzan/vant#3387]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
search组件聚焦后清除叉子在chrome64版本下，失效

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
清除按钮监听的是 touch 事件，请使用 chrome 手机模式打开

**Comment by 469598690** [comment]
兼容pc端的页面如何处理

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/issues/637
