### ISSUE TITLE
search组件在pc端chrome版本下兼容不到touch事件，有没有配置可以隐藏叉子

### ISSUE THREAD

**Issue by 469598690** [youzan/vant#3388]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
search组件在pc端chrome版本下兼容不到touch事件，有没有配置可以隐藏叉子

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.2 版本支持
