### ISSUE TITLE
1.6版本升级2.0版本缺失文件报错

### ISSUE THREAD

**Issue by wananzys** [youzan/vant#3389]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
项目刚开始使用的是1.6版本, 使用 npm i vant@beta -S  安装2.0版本,运行出错, 按照提示安装缺失的文件失败, 请问怎么解决?

**Screenshots**
![image](https://user-images.githubusercontent.com/44047260/58445100-c7604f80-812d-11e9-8d2a-d61cd22e92a0.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 1.6升级2.0

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
请阅读更新日志，2.0 版本中个别组件命名有变化
