### ISSUE TITLE
ImagePreview显示问题

### ISSUE THREAD

**Issue by lianchangcode** [youzan/vant#339]
### 如何手动隐藏？
![image](https://user-images.githubusercontent.com/22534178/33130314-e3387a74-cfcd-11e7-9708-8b92c6bb1778.png)

**Comment by chenjiahan** [comment]
@lianchangcode 感谢反馈，ImagePreview 将会在下个版本中支持手动关闭

**Comment by chenjiahan** [comment]
@lianchangcode 已在 0.11.1 中支持手动关闭，文档地址：https://www.youzanyun.com/zanui/vant#/zh-CN/component/image-preview
