### ISSUE TITLE
按需引入时，某些模块会报错

### ISSUE THREAD

**Issue by vvhl** [youzan/vant#3390]
**Describe the bug**
按需引入vant时，某些某块可以正常引入某些会报错

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/15726547/58454052-dd7f0780-814f-11e9-9011-945f5842c272.png)

**Environment**
 - Device: windows10，nodev10.15.3
 - Browser: chrome
 - Vant Version: 2.0.0

**Comment by chenjiahan** [comment]
不规范的 issue
