### ISSUE TITLE
picker 切换没反应

### ISSUE THREAD

**Issue by chen-can** [youzan/vant#3391]
picker 必须点击文字后才有反应，用的是最新的beta2版本

**Comment by chen-can** [comment]
用change事件监听需要停留一会才会出现值

**Comment by chen-can** [comment]
<van-popup v-model="show" position="bottom" :overlay="true">
      <van-picker
        show-toolbar
        title="请选择区域代理城市"
        :columns="columns"
        @change="onChange"
        @confirm="onConfirm"
      />
    </van-popup>
export default {
  data() {
    return {
     show: false,
      columns: ['杭州', '宁波', '温州', '嘉兴', '湖州']
    }
  },
  methods: {
    onConfirm(value, index) {
      this.show = false
      console.log(`当前值：${value}, 当前索引：${index}`)
    },
    onChange(picker, value, index) {
      console.log(`当前值：${value}, 当前索引：${index}`)
    },
  }
};

**Comment by chenjiahan** [comment]
下个版本会优化 change 事件的触发延时，目前是因为动画结束的比较慢，所以要稍微等一下才触发

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.3 版本优化

**Comment by KID-joker** [comment]
目前有个问题是：picker嵌到popup中，当关闭popup时，picker的change事件还没触发，导致数据没有更新。
请问有什么解决方案吗？
