### ISSUE TITLE
list 一直加载直到值是total才结束加载。

### ISSUE THREAD

**Issue by zhangdoudou** [youzan/vant#3393]
我的代码为：
我想问下，我现在就是遇到了这个问题，使用list组件的时候，一共有12条数据，我每次只请求3条，但是list一直请求接口，一直到请求完才结束，期间我没有滚动屏幕，正常应该是加载一次就结束了，能麻烦您看下我的代码吗？
this.page++;
console.log( this.list.length)
this.loading = true
setTimeout(() => {
this.$http(
url.getAttentionList,
{ marketNum: this.marketNum, page: this.page, limit: 3 },
"post"
).then(res => {
// 数据全部加载完成
if (res.data) {
this.total = res.data.data.total;
if (res.data.data.rows.length > 0) {
let result = res.data.data;
result.rows.forEach(element => {
this.list.push(element);
});
// 加载状态结束
this.loading = false;
if (this.list.length >= result.total) {
this.finished = true;
this.loading = false;
}
} else {
this.finished = true;
this.loading = false;
}
}
});
}, 500);

**Environment**
 - Device: iphone
 - Browser: chrome
 - Vant Version: 1.6.20

麻烦大家看下，是我写的有问题吗？

**Comment by chenjiahan** [comment]
数据量无法填满一屏幕的情况下，会触发下一次 load

**Comment by zhangdoudou** [comment]
已经填满一屏幕了，我故意把每一条记录的高度设置得特别高 @chenjiahan

**Comment by chenjiahan** [comment]
能提供下 jsfiddle 么

**Comment by MaDCen** [comment]
我遇到过类似的问题,可能是由于你并没有给外层容器设置初始高度的原因

**Comment by zhangdoudou** [comment]
@MaDCen 麻烦问下 那个外层容器指的是那个呢？我list那块的结构是这样的
 <div class="recordList">
      <p class="listTit">已登记领取：{{total}}份</p>
      <div class="record">
        <div class="itemRecord recordHeader">
          <div class="mobile">手机号</div>
          <div class="plate">车牌号</div>
          <div class="state">状态</div>
          <div class="time">登记时间</div>
        </div>
        <van-list v-model="loading" :finished="finished" finished-text="没有更多了" @load="onLoad"  ref="list" >
          <div class="itemRecord" v-for="(item,index) in list">
            <div class="mobile">{{item.phoneNum}}</div>
            <div class="plate">{{item.plateNum}}</div>
            <div class="state" v-if="item.state==0">已登记</div>
            <div class="state" v-if="item.state==1">已核销</div>
            <div class="time">{{item.registrationTime}}</div>
          </div>
        </van-list>
      </div>
    </div>

**Comment by zhangdoudou** [comment]
``  <div class="recordList">
      <p class="listTit">已登记领取：{{total}}份</p>
      <div class="record">
        <div class="itemRecord recordHeader">
          <div class="mobile">手机号</div>
          <div class="plate">车牌号</div>
          <div class="state">状态</div>
          <div class="time">登记时间</div>
        </div>
        <van-list v-model="loading" :finished="finished" finished-text="没有更多了" @load="onLoad"  ref="list" >
          <div class="itemRecord" v-for="(item,index) in list">
            <div class="mobile">{{item.phoneNum}}</div>
            <div class="plate">{{item.plateNum}}</div>
            <div class="state" v-if="item.state==0">已登记</div>
            <div class="state" v-if="item.state==1">已核销</div>
            <div class="time">{{item.registrationTime}}</div>
          </div>
        </van-list>
      </div>
    </div>

**Comment by zhangdoudou** [comment]
![image](https://user-images.githubusercontent.com/28778859/58699016-0f51d180-83cf-11e9-804e-579fda5b7d82.png)

**Comment by zhangdoudou** [comment]
我发现问题了，是因为未指定高度。谢谢 @chenjiahan @MaDCen

**Comment by FlowerInSunnySun** [comment]
> 我发现问题了，是因为未指定高度。谢谢 @chenjiahan @MaDCen

你给那个元素指定高度就可以了呢，能否贴个demo。我这边也遇到过这个问题了，另外官网能否把这个坑补充在说明文档呢？

**Comment by 9yues** [comment]
我也遇到这个问题了，我一页请求50条数据足以撑高整个屏幕，但是list组件还是给我把剩下的几百条一块加载完了，头疼，声明：我的li标签没有设置float
