### ISSUE TITLE
[Feature Request] DropdownMenu是否考虑增加能配置上拉菜单

### ISSUE THREAD

**Issue by akebe** [youzan/vant#3394]
![image](https://user-images.githubusercontent.com/23068436/58524721-bed64a80-81fb-11e9-8d4e-ddcd3fa497e2.png)
正在写类似图中的窗口下部点击菜单弹出功能，如果2.0的`DropdownMenu`能配置菜单方向向上的话就可以即开即用了，因为赶进度先用`Popup`实现没时间写PR，如果改动不大的话建议添加这个配置项

**Comment by thtianhang** [comment]
我也遇到这个问题，希望能快速能修复下这个bug。

**Comment by chenjiahan** [comment]
我也是捉妖玩家，你是在做捉妖的页面吗 ^_^

这个功能近期会支持

**Comment by chenjiahan** [comment]
已在 2.0.1 版本支持
