### ISSUE TITLE
dialog auto show！ 

### ISSUE THREAD

**Issue by Popxie** [youzan/vant#3396]
**Describe the bug**
通过标签的形式来引用的时候，title， show-cancel-button 等属性不生效，且会自动显示不受v-modle绑定的值的控制！取消按钮也出不来， 点击确认还报错。。。不知道为什么··· 希望能给我回复。

**Screenshots**
![image](https://user-images.githubusercontent.com/24952644/58534030-b9d5c300-821c-11e9-97c7-eaf007f5bd95.png)
![image](https://user-images.githubusercontent.com/24952644/58534077-e25dbd00-821c-11e9-8c41-f79eb856044c.png)
![image](https://user-images.githubusercontent.com/24952644/58534090-ea1d6180-821c-11e9-9496-91cf996d028d.png)

**Environment**
 - Device:  mac pro
 - Browser: Chrome
 - Vant Version:   "^1.6.15"

**Reproduce**

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3322
