### ISSUE TITLE
GoodsAction 商品导航 不会渲染页面

### ISSUE THREAD

**Issue by wang131484** [youzan/vant#3397]
![360截图1679052897136126](https://user-images.githubusercontent.com/39394283/58534472-fe159300-821d-11e9-97fa-8e403191592b.png)

![360截图16501102235662](https://user-images.githubusercontent.com/39394283/58534496-0e2d7280-821e-11e9-8a1d-c6bb66afe70e.png)

请指教！

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3392
