### ISSUE TITLE
van-swipe在初始页面时隐藏，当切换显示的时候图片宽高为0

### ISSUE THREAD

**Issue by mengfei2611** [youzan/vant#3398]
![image](https://user-images.githubusercontent.com/22373868/58546921-fb746700-8238-11e9-8c1e-cb75bb70d099.png)
![image](https://user-images.githubusercontent.com/22373868/58547030-3080b980-8239-11e9-917d-0258c37adac4.png)
需要怎么处理宽高呢？

**Comment by mengfei2611** [comment]
我通过根据屏幕宽度，动态控制滑块大小。：width，解决了没有宽度的问题。但是这个组件是有问题的，不知道有什么更好的办法解决。

**Comment by chenjiahan** [comment]
display: none 的时候，Swipe 是获取不到宽高的，你可以添加 v-if 来延迟 Swipe 的渲染时机

**Comment by Gokeyoung** [comment]
刚遇见这个问题，考虑lazy-component会比较好，而且也不会有问题，v-if会导致每次打开都重新渲染，体验感不太好

**Comment by Orow** [comment]
> display: none 的时候，Swipe 是获取不到宽高的，你可以添加 v-if 来延迟 Swipe 的渲染时机

我這邊用 v-show，Swipe組件一開始在 v-show的條件是false(就是display: none)的狀況，之後改變條件讓v-show變成true，這時候Swipe的寬高也是0，有方式可以解決嗎？

**Comment by Gokeyoung** [comment]
> > display: none 的时候，Swipe 是获取不到宽高的，你可以添加 v-if 来延迟 Swipe 的渲染时机
> 
> 我這邊用 v-show，Swipe組件一開始在 v-show的條件是false(就是display: none)的狀況，之後改變條件讓v-show變成true，這時候Swipe的寬高也是0，有方式可以解決嗎？

为啥会收到邮件通知？？？

方法：使用lazy-component来加载

**效果图**
![image](https://user-images.githubusercontent.com/18525879/70987762-86e11700-20fb-11ea-915f-335820e35edc.png)

这里也会有一个问题懒加载不触摸页面不会加载，这里使用一个显示的时候手动触发

`
//事件在祖父级添加即可
  tabsClick() {
            // 手动触发 lazy load
            let event = document.createEvent('MouseEvents')
            event.initEvent('mousewheel', true, true)
            this.$el.dispatchEvent(event)
  },`

不知道有没有用，可以试试

**Comment by Orow** [comment]
稍微描述ㄧ下我的狀況，有兩個部分，一個是垂直模式，一個是水平閱讀模式
default 是垂直模式(isHorizontal: false)，執行 horizonMode() 後，改變 v-show 的值，但 swipe 組件的寬高都是0。

但是這時候去改變 initital-swipe的值，畫面就會正常顯示....
看起來是  swipe 組件在 display: none 變成 display: block 時的狀況

```
<div class="reader" @click="toggleInfo" v-show="isHorizontal">
      <van-swipe
        :show-indicators="false"
        :loop="false"
        :initial-swipe="imgIndex - 1"
      >
        <van-swipe-item class="item-horizontal" v-for="(item, index) in 圖片" :key="index">
          <img
            class="img"
            v-lazy="{ src: 圖片'}"
            :key="index"
          />
        </van-swipe-item>
      </van-swipe>
</div>
```

```
// 點擊改變水平垂直模式
horizonMode() {
 this.isHorizontal = !this.isHorizontal;
},
```

**Comment by Gokeyoung** [comment]
> 稍微描述ㄧ下我的狀況，有兩個部分，一個是垂直模式，一個是水平閱讀模式
> default 是垂直模式(isHorizontal: false)，執行 horizonMode() 後，改變 v-show 的值，但 swipe 組件的寬高都是0。
> 
> 但是這時候去改變 initital-swipe的值，畫面就會正常顯示....
> 看起來是 swipe 組件在 display: none 變成 display: block 時的狀況
> 
> ```
> <div class="reader" @click="toggleInfo" v-show="isHorizontal">
>       <van-swipe
>         :show-indicators="false"
>         :loop="false"
>         :initial-swipe="imgIndex - 1"
>       >
>         <van-swipe-item class="item-horizontal" v-for="(item, index) in 圖片" :key="index">
>           <img
>             class="img"
>             v-lazy="{ src: 圖片'}"
>             :key="index"
>           />
>         </van-swipe-item>
>       </van-swipe>
> </div>
> ```
> 
> ```
> // 點擊改變水平垂直模式
> horizonMode() {
>  this.isHorizontal = !this.isHorizontal;
> },
> ```

有设计稿或是截个图，看看我能不能解决，单纯的这样感觉很难解决问题

**Comment by Orow** [comment]
剛剛試了一下用樓主的給定寬度，是可以解決的。

我的案例是，一開始 swipe 組件是 display: none ，後來改變條件讓 display: block 後當下 swipe 組件是沒有寬高的，但去改變initial-swipe值，寬高又出現，畫面是正常顯示。

我剛剛測試是用 :width 這個參數用 computed 裡面去計算視窗寬度再 return 回來就可以了

**Comment by Gokeyoung** [comment]
> 剛剛試了一下用樓主的給定寬度，是可以解決的。
> 
> 我的案例是，一開始 swipe 組件是 display: none ，後來改變條件讓 display: block 後當下 swipe 組件是沒有寬高的，但去改變initial-swipe值，寬高又出現，畫面是正常顯示。
> 
> 我剛剛測試是用 :width 這個參數用 computed 裡面去計算視窗寬度再 return 回來就可以了

display: none是没有占位宽度的，好像这个问题使用swipe的ref，然后调用resize就可以了

![image](https://user-images.githubusercontent.com/18525879/71052677-1e3f7c00-2187-11ea-832f-c249f4e72e03.png)

```
//vant swipe代码
// initialize swipe position
    initialize: function initialize(active) {
      if (active === void 0) {
        active = this.initialSwipe;
      }

      clearTimeout(this.timer);

      if (this.$el) {
        var rect = this.$el.getBoundingClientRect();
        this.computedWidth = this.width || rect.width;
        this.computedHeight = this.height || rect.height;
      }

      this.swiping = true;
      this.active = active;
      this.offset = this.count > 1 ? -this.size * this.active : 0;
      this.swipes.forEach(function (swipe) {
        swipe.offset = 0;
      });
      this.autoPlay();
    },
    // @exposed-api
    resize: function resize() {
      this.initialize(this.activeIndicator);
    },
```
```
//通过延迟显示然后调用resize方法是可以的
setTimeout(() => {
                this.isSwipe = 1
            }, 1000)

            setTimeout(() => {
                this.$refs.sliderRef.resize()
            }, 1500)

//在watch里监听isSwipe，然后执行resize()方法。为了只执行一次这个方法，添加一个参数让resize()执行后不再重新执行
```

**Comment by Orow** [comment]
> > 剛剛試了一下用樓主的給定寬度，是可以解決的。
> > 我的案例是，一開始 swipe 組件是 display: none ，後來改變條件讓 display: block 後當下 swipe 組件是沒有寬高的，但去改變initial-swipe值，寬高又出現，畫面是正常顯示。
> > 我剛剛測試是用 :width 這個參數用 computed 裡面去計算視窗寬度再 return 回來就可以了
> 
> display: none是没有占位宽度的，好像这个问题使用swipe的ref，然后调用resize就可以了
> 
> ![image](https://user-images.githubusercontent.com/18525879/71052677-1e3f7c00-2187-11ea-832f-c249f4e72e03.png)
> 
> ```
> //vant swipe代码
> // initialize swipe position
>     initialize: function initialize(active) {
>       if (active === void 0) {
>         active = this.initialSwipe;
>       }
> 
>       clearTimeout(this.timer);
> 
>       if (this.$el) {
>         var rect = this.$el.getBoundingClientRect();
>         this.computedWidth = this.width || rect.width;
>         this.computedHeight = this.height || rect.height;
>       }
> 
>       this.swiping = true;
>       this.active = active;
>       this.offset = this.count > 1 ? -this.size * this.active : 0;
>       this.swipes.forEach(function (swipe) {
>         swipe.offset = 0;
>       });
>       this.autoPlay();
>     },
>     // @exposed-api
>     resize: function resize() {
>       this.initialize(this.activeIndicator);
>     },
> ```
> 
> ```
> //通过延迟显示然后调用resize方法是可以的
> setTimeout(() => {
>                 this.isSwipe = 1
>             }, 1000)
> 
>             setTimeout(() => {
>                 this.$refs.sliderRef.resize()
>             }, 1500)
> 
> //在watch里监听isSwipe，然后执行resize()方法。为了只执行一次这个方法，添加一个参数让resize()执行后不再重新执行
> ```

用這個方式測試一下後，setTimeout 延遲後去調用 resize 是可行的，不過我想主要應該是延遲這件事情，先前自己測試有用 resize 沒有作用。

不過我用 resize 的時候切過去的當下我這邊用的 lazyload 還會顯示是在loading，要點一下 畫面才會變成 loaded 的狀態，所以這邊我最後還是選擇給 width 來達成我要的狀況。

不過還是謝謝大大幫忙～

**Comment by Gokeyoung** [comment]
> > > 剛剛試了一下用樓主的給定寬度，是可以解決的。
> > > 我的案例是，一開始 swipe 組件是 display: none ，後來改變條件讓 display: block 後當下 swipe 組件是沒有寬高的，但去改變initial-swipe值，寬高又出現，畫面是正常顯示。
> > > 我剛剛測試是用 :width 這個參數用 computed 裡面去計算視窗寬度再 return 回來就可以了
> > 
> > 
> > display: none是没有占位宽度的，好像这个问题使用swipe的ref，然后调用resize就可以了
> > ![image](https://user-images.githubusercontent.com/18525879/71052677-1e3f7c00-2187-11ea-832f-c249f4e72e03.png)
> > ```
> > //vant swipe代码
> > // initialize swipe position
> >     initialize: function initialize(active) {
> >       if (active === void 0) {
> >         active = this.initialSwipe;
> >       }
> > 
> >       clearTimeout(this.timer);
> > 
> >       if (this.$el) {
> >         var rect = this.$el.getBoundingClientRect();
> >         this.computedWidth = this.width || rect.width;
> >         this.computedHeight = this.height || rect.height;
> >       }
> > 
> >       this.swiping = true;
> >       this.active = active;
> >       this.offset = this.count > 1 ? -this.size * this.active : 0;
> >       this.swipes.forEach(function (swipe) {
> >         swipe.offset = 0;
> >       });
> >       this.autoPlay();
> >     },
> >     // @exposed-api
> >     resize: function resize() {
> >       this.initialize(this.activeIndicator);
> >     },
> > ```
> > 
> > 
> > ```
> > //通过延迟显示然后调用resize方法是可以的
> > setTimeout(() => {
> >                 this.isSwipe = 1
> >             }, 1000)
> > 
> >             setTimeout(() => {
> >                 this.$refs.sliderRef.resize()
> >             }, 1500)
> > 
> > //在watch里监听isSwipe，然后执行resize()方法。为了只执行一次这个方法，添加一个参数让resize()执行后不再重新执行
> > ```
> 
> 用這個方式測試一下後，setTimeout 延遲後去調用 resize 是可行的，不過我想主要應該是延遲這件事情，先前自己測試有用 resize 沒有作用。
> 
> 不過我用 resize 的時候切過去的當下我這邊用的 lazyload 還會顯示是在loading，要點一下 畫面才會變成 loaded 的狀態，所以這邊我最後還是選擇給 width 來達成我要的狀況。
> 
> 不過還是謝謝大大幫忙～

好吧，我上面使用setTimeout，只是我这个边测试看resize是否有用，实际使用不需要，只需要**watch**监听**isHorizontal**的状态是否改变，有改变后调用**一次**resize方法就可以了，或者在你的切换事件里执行**一次**也是一样

**Comment by xisenbao** [comment]
> display: none 的时候，Swipe 是获取不到宽高的，你可以添加 v-if 来延迟 Swipe 的渲染时机
d大佬这边遇到一个类似的问题，控制隐藏实际还是渲染为0 还是偶现问题 https://github.com/youzan/vant/discussions/12850
