### ISSUE TITLE
List组件没有保持滚动位置

### ISSUE THREAD

**Issue by Dcell** [youzan/vant#3399]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
`            <keep-alive>
                <component  v-bind:is="currComponent">
                </component>
            </keep-alive>   
`
3个组件，其中第一个组件是用List组件。
1.滑动List组件
2.当切换到第二个组件，再切换回List组件后，回滚到顶部(没有保持在上次滑动的位置)（Bug？）

**Screenshots**
![May-30-2019 09-15-05](https://user-images.githubusercontent.com/4684864/58601553-e42a8d80-82bb-11e9-9789-b60a553a6ab2.gif)

**Environment**
 - Device: 
 - Browser: google
 - Vant Version: 2.0beta

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by Dcell** [comment]
组件是Keep-alive的。

**Comment by chenjiahan** [comment]
List 组件并不会保存滚动位置呢

**Comment by Dcell** [comment]
@chenjiahan 如果是正常用Div叠加是可以保持滚动位置，List组件应该可以的吧

**Comment by chenjiahan** [comment]
嗯，理论上来说是否使用 List，对滚动位置不会有任何影响

**Comment by Dcell** [comment]
嗯，我先自己排查下，应该不是List组件问题，打扰了

**Comment by WhityLL** [comment]
遇到同样的问题，使用list组件上拉加载后，点击进入下一页（ 当前页是Keep-alive的），返回后不会记住上一页的位置。

**Comment by y-MaxJh** [comment]
我也碰到类似的问题。页面使用了keepAlive, 当list区域设置了高度或定位后,跳转到其他页，返回都会回到list的顶部。

**Comment by wardenlzr** [comment]
> List 组件并不会保存滚动位置呢

有没有滚动的方法呢，自己做个滚动可以吗？

**Comment by chenjiahan** [comment]
@wardenlzr 可以用原生的 scrollTo 方法

**Comment by zhoudaobo** [comment]
我试了，在与组件van-pull-refresh 配合使用时就会出现这个情况
