### ISSUE TITLE
van-list 加载两次，要怎样去阻止？

### ISSUE THREAD

**Issue by lisun0459** [youzan/vant#3400]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
van-list 加载两次，使用了this.loading=false，this.$refs.list.check()也无效，到底要如何去设置才能阻止？

**Screenshots**
![屏幕快照 2019-05-30 上午9 48 57](https://user-images.githubusercontent.com/15245259/58602626-35d51700-82c0-11e9-9566-3ca8c410f823.png)
![屏幕快照 2019-05-30 上午9 49 48](https://user-images.githubusercontent.com/15245259/58602649-4be2d780-82c0-11e9-9b7b-ac388a5dd3ce.png)
![屏幕快照 2019-05-30 上午9 53 00](https://user-images.githubusercontent.com/15245259/58602825-de837680-82c0-11e9-9da2-e8aef7b90f91.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
贴一段 List 原理的介绍，不知道能否解答你的疑惑

- 非加载中，loading 为 false，此时会根据列表滚动位置判断是否触发 load 事件，列表内容不足一屏幕时，会直接触发
- 加载中，loading 为 true，表示正在发送异步请求，此时不会触发 load 事件
- 加载完成，finished 为 true，此时不会触发 load 事件
loading 在每次请求完毕后都会手动设置为 false。

**Comment by lisun0459** [comment]
找到了原因，好好理解了一下下面这句
【加载中，loading 为 true，表示正在发送异步请求，此时不会触发 load 事件】
所以，在load 事件中加载数据时去掉this.loading = false即可
感谢！感谢！

**Comment by chenjiahan** [comment]
客气哈

**Comment by Code1994** [comment]
你好,我也遇到了同样的问题.按照你说的'在load 事件中加载数据时去掉this.loading = false即可', 我试过了, 可还是有问题, 是我哪里理解的不对吗?

**Comment by Code1994** [comment]
`onLoad () {
      this.currentPage++
      setTimeout(() => {
        this.getList(() => {
          // this.upLoading = false
        })
      }, 500)
    },`
`// 封装请求列表方法
    getList (callBack) {
      // 请求之前判断下currentPage与totalPages
      if (this.currentPage > this.totalPages) {
        this.upLoading = false
        this.upFinished = true
        return
      }
      getPrettyList({
        currentPage: this.currentPage,
        rows: this.rows
      }).then((res) => {
        if (res.status.statusCode === 0) {
          console.log(res)
          // 如果当前currentPage是1,就将list清空为空数组,再重新concat
          if (this.currentPage === 1) {
            this.list = []
          }
          // 如果result中的list的长度小于rows,则证明'已无更多数据'
          if (res.result.list.length < this.rows) {
            this.upFinished = true
          }
          this.list = this.list.concat(res.result.list)
          this.totalPages = res.result.totalPages
          console.log('----------------')
          console.log(this.list)
          callBack && callBack()
        }
      })
    },`

**Comment by Code1994** [comment]
![1559268158(1)](https://user-images.githubusercontent.com/37331643/58676573-57e79b80-838b-11e9-8e78-c31d73a85076.png)
![1559268175(1)](https://user-images.githubusercontent.com/37331643/58676579-5c13b900-838b-11e9-974b-4708931bc1a4.png)

**Comment by Code1994** [comment]
![1559268158(1)](https://user-images.githubusercontent.com/37331643/58676604-6afa6b80-838b-11e9-9796-72fe9aaa877e.png)
![1559268175(1)](https://user-images.githubusercontent.com/37331643/58676612-7057b600-838b-11e9-83ba-83b1fdc47f3e.png)

**Comment by lisun0459** [comment]
去掉了onload里面的this.loading = false，但是请求方法里面请求结束后我没有去掉this.loading = false，并且我判断了下一次请求的pageIndex是否一致，一致的话就说明重复请求，就立即结束。但实际我试过去掉这种判断也是正常的只请求一次。
![屏幕快照 2019-05-31 上午10 22 48](https://user-images.githubusercontent.com/15245259/58677333-1c020580-838e-11e9-9b1e-a22ad5904aff.png)

**Comment by Code1994** [comment]
找到了问题所在, 需要利用props绑定immediate-check为false, 防止初始加载时来检测, 之前过于把注意力放在js代码上了.但是我觉得这vant组件库应该默认给false,真的给人十分大的困扰.

**Comment by mynameismaosheng** [comment]
> 贴一段 List 原理的介绍，不知道能否解答你的疑惑
> 
> * 非加载中，loading 为 false，此时会根据列表滚动位置判断是否触发 load 事件，列表内容不足一屏幕时，会直接触发
> * 加载中，loading 为 true，表示正在发送异步请求，此时不会触发 load 事件
> * 加载完成，finished 为 true，此时不会触发 load 事件
>   loading 在每次请求完毕后都会手动设置为 false。

根据屏幕的高度建议改成容器的高度; 因为可能只是在页面一部分去展示list,
