### ISSUE TITLE
Search组件与原生的input在v-model上的表现不一致

### ISSUE THREAD

**Issue by heihei001** [youzan/vant#3401]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
使用Search组件在中文输入法时，v-model绑定的值是实时更新的，而原生的input在使用v-model在中文输入法输入时是在输入完成后即敲下空格变成中文时才进行更新

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/17396846/58602864-0f63ab80-82c1-11e9-91cb-dc865738ee17.png)
![image](https://user-images.githubusercontent.com/17396846/58602905-30c49780-82c1-11e9-9614-56c713babedc.png)
![image](https://user-images.githubusercontent.com/17396846/58602936-55b90a80-82c1-11e9-8e5f-e33a6e108668.png)
![image](https://user-images.githubusercontent.com/17396846/58602947-636e9000-82c1-11e9-8ac0-ea4b9c35c5d6.png)

**Environment**
 - Device: pc模拟器
 - Browser: chrome
 - Vant Version: 2.0.0-beta.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by heihei001** [comment]
主要是想在输入后实时获取内容导致在pc模拟器造成不必要的查询，其实在移动端到没啥影响，移动端中文输入的时候是不进搜索框的。

**Comment by heihei001** [comment]
在ios和Android测试了下，小米的中文输入法输入时内容不进搜索框，ios输入时会进入搜索框
![image](https://user-images.githubusercontent.com/17396846/58620414-9b91c500-82f9-11e9-8e3d-a4336b6151d3.png)
![image](https://user-images.githubusercontent.com/17396846/58620425-a187a600-82f9-11e9-9400-254755254722.png)

**Comment by chenjiahan** [comment]
这里 Vue 是做了特殊处理的，我们后续会参照 Vue 内部实现做下处理

**Comment by heihei001** [comment]
@chenjiahan 棒棒的

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.3 版本优化

**Comment by heihei001** [comment]
@chenjiahan 感谢。
