### ISSUE TITLE
DatetimePicker 时间选择 不支持“秒”的单位

### ISSUE THREAD

**Issue by koibi2** [youzan/vant#3403]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
DatetimePicker 时间选择 不支持“秒”的单位。

**Describe the solution you'd like**
希望可以支持。

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by koibi2** [comment]
现在只能用 `Picker 选择器` 实现。
希望可以支持，减少重复劳动。

**Comment by koibi2** [comment]
我去找了下 vux 、 mint ，都没有只支持秒。难道广大群众都没有秒的需求？
震惊了、

**Comment by chenjiahan** [comment]
什么场景要选秒呢，好像不太常见

**Comment by koibi2** [comment]
领导让支持 `秒` 啊。。。 QAQ
我已用 `Picker 选择器` 实现了。
如果有谁需要，等我有空，把封装好的组件传到 `Github` 。

**Comment by zrqabc** [comment]
我也用到了

**Comment by shen-lan** [comment]
@koibi2 老哥有空发一下吧

**Comment by blogwy** [comment]
@koibi2 我也是领导非要加秒
