### ISSUE TITLE
picker组件的建议

### ISSUE THREAD

**Issue by yezhihao17** [youzan/vant#3407]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
使用picker组件，并且开启show-toolbar模式，当选择时快速滑动选项，动画没有结束点击确定按钮无法选择到值。必须要等动画结束后才能选择值。

**Describe the solution you'd like**
期望在动画没结束时点击确定按钮，动画立即停止，并选择当前选择区域的值。或者是提供类似的api，可供开发者自己选择是否开启这种模式。

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by ystarlongzi** [comment]
看了下其它组件的实现，好像交互并统一，当点击「确定」后，这块交互大致可以分为：

 - 立即结束动画，触发事件，且取消选中【iOS 系统、小程序】
 - 立即结束动画，触发事件，且选中目标元素【antd mobile】
 - 继续动画，在动画结束后，触发事件，然后选中目标元素【better-scroll】

从个人体验上说，antd mobile 的交互会相对舒服些。

但仔细想下，在用户点击「确定」时，由于滚动动画并未停止，在视觉上是无法确定选中项是哪一个，取消选中这种交互也是能理解的 😹😹

**Comment by chenjiahan** [comment]
个人倾向于 antd 的方案，直接选中目标元素。

原因是按照我们设定的贝塞尔曲线，动画接近结束的时候，缓动时间是比较长的，此时手速比较快的用户可能以为已经完成选中了，点击确认，就会发现没有选中预期的选项。

我在 iOS 上就时常碰到这种情况

**Comment by ystarlongzi** [comment]
[picker/PickerColumn.js](https://github.com/youzan/vant/blob/dev/packages/picker/PickerColumn.js) 里增加一个 `stopMomentum` 方法，然后在点击「确认」、「取消」按钮时，对所有 column 执行这个方法

这个方案可行不？

**Comment by chenjiahan** [comment]
我觉得 ok~

**Comment by zengnanhua** [comment]
我感觉不怎么好用这个组价   参考一下  vux 里面的这个组件

**Comment by ystarlongzi** [comment]
@zengnanhua 

我体验了下，感觉差别不大 😹😹。可以具体点说下是那一块不好用嘛，比如交互、UI、接口使用上？

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.3 版本发布
