### ISSUE TITLE
SubmitBar 控件有个左边的Slot就完美了

### ISSUE THREAD

**Issue by yajore** [youzan/vant#341]
**What is the current behavior?**
如题，对于微信里面的购物车，如果不分组，
全选按钮就应该至于底部左边的位置，所以加个左边的slot就基本完美了
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@yajore 收到，会在下个版本中添加

**Comment by chenjiahan** [comment]
@yajore 已在 0.11.1 中添加
