### ISSUE TITLE
优惠券coupon-list组件能否调换金额和单位的位置

### ISSUE THREAD

**Issue by hr799** [youzan/vant#3413]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

*需求是单位显示在金额左边: '$10', 但是目前组件只支持$符号在金额右边

*希望可以添加一个设置, 允许调整单位显示位置

*unitDescPosition: left|right

**Comment by chenjiahan** [comment]
可以不传 `unitDesc` 属性，把单位包含在 `valueDesc` 里

valueDesc: '$10'
