### ISSUE TITLE
list页面 打包成app后，在苹果手机上面，上拉加载无法使用

### ISSUE THREAD

**Issue by justdoitgo** [youzan/vant#3415]
Describe the bug
苹果浏览器下面的 list上拉加载无法试用

Vantlist页面打包成APP，在APP里面打开，安卓测试滚动没问题，苹果手机上面上拉加载无反应，下拉刷新可以正常~

**Comment by justdoitgo** [comment]
VUE版本3.5.5

**Comment by chenjiahan** [comment]
没复现此问题，不清楚你是通过什么方式进行打包成 App 的，建议看下是不是这个步骤有问题

**Comment by justdoitgo** [comment]
> 没复现此问题，不清楚你是通过什么方式进行打包成 App 的，建议看下是不是这个步骤有问题

用的的cordova+want打包的APP，安卓上面完全通过，苹果端，上拉加载无反应，页面缺少一个滚动DIV
![微信截图_20190531142637](https://user-images.githubusercontent.com/25169861/58686039-2fbe6380-83b0-11e9-9205-ef50074143d9.gif)

**Comment by justdoitgo** [comment]
就算不打包，官方的list也有问题
测试如下：
1-2 是其他框架的 下拉和上拉的样式，在苹果上面可以通过鼠标进行上拉加载。


3-4是vant 的下拉和上拉实例，在苹果浏览器上面，只有上拉操作可以成功，下拉页面无反应。
![1](https://user-images.githubusercontent.com/25169861/58686427-5af58280-83b1-11e9-8775-49be5d621de3.jpg)
![2](https://user-images.githubusercontent.com/25169861/58686429-5cbf4600-83b1-11e9-8462-7e38f8de847c.jpg)
![3](https://user-images.githubusercontent.com/25169861/58686432-5df07300-83b1-11e9-90c0-a2878b6ef3a8.jpg)
![4](https://user-images.githubusercontent.com/25169861/58686435-5fba3680-83b1-11e9-97e1-f36e468f6d4f.jpg)

**Comment by chenjiahan** [comment]
List 是瀑布流加载，不是上拉加载，他的加载不是通过拖动触发的，而是通过滚动事件触发的

**Comment by justdoitgo** [comment]
之前问题解决了，是cordova插件里面的键盘插件冲突了。现在问题是，苹果端，滚动的时候上下导航栏会一起滚动，可以固定上下导航不么？

**Comment by justdoitgo** [comment]
那苹果端，是如何解决这个问题的呢？
