### ISSUE TITLE
Tabs组件sticky模式导致组件抖动

### ISSUE THREAD

**Issue by honggu025** [youzan/vant#3416]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
我想实现一个永远在顶部的Tabs，但是添加sticky后，页面初始化时position是absolute状态，这就导致滚动页面时，tabs会随页面向上移动一两个像素，然后才触发事件，改变position为fixed，有一个明显的抖动。同样，向下滑动页面直到顶部，也会出现相似的抖动。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
你这种情况可以直接在 Tab 上面设置 fixed 样式，不需要使用 sticky 属性

**Comment by honggu025** [comment]
@chenjiahan 谢谢
经测试，直接设置样式不行，使用深度选择器
`.van-tabs >>> .van-tabs__wrap {
  top: 0;
  position: fixed;
}`
即可
