### ISSUE TITLE
cell,field等有下划线的组件,下划线显示问题

### ISSUE THREAD

**Issue by ZhaoLiangchuan** [youzan/vant#3418]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
cell,field等有下划线的组件,在安卓版微信浏览器中,有overflow:scroll的盒子中,下划线显示有问题,有的显示,有的不显示,去掉overflow:scroll属性后可以正常显示.ios版本没有此问题

**Screenshots**
![微信截图_20190531155056](https://user-images.githubusercontent.com/34114842/58690859-1a036b00-83bd-11e9-899c-3fcdeb8060b6.png)
![微信图片_20190531160325](https://user-images.githubusercontent.com/34114842/58691099-a877ec80-83bd-11e9-94fc-812bbb203f53.jpg)

**Environment**
 - Device: 安卓手机
 - Browser: 
安卓版微信浏览器
 - Vant Version: 
1.6.17
**Reproduce**
无

**Comment by fightingFan** [comment]
同问。。

**Comment by chenjiahan** [comment]
应该是浏览器的渲染 bug，目前没啥办法解决

**Comment by GongDeyuan** [comment]
试试修改边框样式
.van-cell:not(:last-child)::after {
  -webkit-transform: scaleY(1);
  transform: scaleY(1);
  top: 0;
}
