### ISSUE TITLE
请问popup案例的右侧弹出，是怎么出现铺满屏的效果的哈？

### ISSUE THREAD

**Issue by benbenyao** [youzan/vant#3419]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by jakietwo** [comment]
将popup 设置成width:100vw, height: 100vh 就可以了
