### ISSUE TITLE
field ref 获取焦点focus错误

### ISSUE THREAD

**Issue by 750973092** [youzan/vant#3421]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

<van-field ref="text" v-model="value" placeholder="请输入用户名"/>
this.$refs.text.focus()
报以下错误：
this.$refs.text.focus is not a function

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
ref 必须在 mounted 之后取

**Comment by 750973092** [comment]
是啊，这个我是点击事件触发在methods里的方法的

**Comment by 750973092** [comment]
但还是报错，但我用 document.querySelector('.van-field__control').focus()就没问题

**Comment by chenjiahan** [comment]
可以 console.log(this.$refs) 看下

**Comment by 750973092** [comment]
<van-field :ref="'text'+idx" type="textarea" v-model="value" placeholder="请输入用户名"/>
是不是我在循环的时候动态赋值的时候不行呢

**Comment by 750973092** [comment]
van-field :ref="'text'+idx" type="textarea" v-model="value" placeholder="请输入用户名"

**Comment by chenjiahan** [comment]
你的 ref 不是有加  idx 嘛，得用对应的 ref 去取

**Comment by 750973092** [comment]
![image](https://user-images.githubusercontent.com/22766860/58716060-d0397580-83fa-11e9-8cd1-6d3b81680106.png)
这是打印this.$refs的数据

**Comment by 750973092** [comment]
有用对应的text0去获取报错的

**Comment by chenjiahan** [comment]
首先这个问题和组件库没关系呢，其次你取到的 ref 是数组

**Comment by 750973092** [comment]
是啊，我只是循环而已，怎么取到的refs的text0，1这些是数组呢，

**Comment by chenjiahan** [comment]
建议不要加 idx，用同一个 ref 值，这样取到的 this.$refs.text 就是你所有 Field 组成的数组
