### ISSUE TITLE
ios上AddressEdit 地址编辑一方面不填写不弹toast;另一个问题是ios不动省市区组件直接点确定就选不上

### ISSUE THREAD

**Issue by iyaq** [youzan/vant#3423]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
没复现这两个问题，能提供下 jsfiddle 么

**Comment by iyaq** [comment]
没有，我给您地址可以吗  在微信浏览器打开，tab页“我的”地址编辑弹框操作：http://wechat.yinhangren.cn/#/home
谢谢

**Comment by chenjiahan** [comment]
用你的链接，第一个问题我试了下有 Toast，第二个问题是微信的 bug，点击区域偏移了，可以升级到最新的 1.6.21 试下，内部有加过兼容处理

**Comment by iyaq** [comment]
好的，谢谢您，是部分机型出现的
