### ISSUE TITLE
DropdownMenu与Area组合导致显示问题

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#3426]
**Describe the bug**
点击Area的确定/取消按钮, 会导致DropdownItem隐藏; 在Dialog中也有此问题.
场景: DropdownMenu做自定义筛选, 有筛选城市的需求

**Screenshots**
见jsfiddle

**Environment**
 - Device: PC
 - Browser: Chrome
 - Vant Version: v2.0.0-beta.3

**Reproduce**
https://jsfiddle.net/sylvaner/zfkctbrs/11/

**Comment by chenjiahan** [comment]
你把 ActionSheet 放到 DropdownMenu  的外部了，所以点击的时候会触发关闭事件，放到 DropdownItem 的子元素里，不会出现这个问题
