### ISSUE TITLE
Area组件列数columns-num改变后有显示问题

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#3427]
**Describe the bug**
Area组件列数columns-num改变后, 无法显示城市数据
场景: 筛选地区, 有时候仅筛选到省

**Screenshots**
见jsfiddle

**Environment**
 - Device: PC
 - Browser: Chrome
 - Vant Version: v2.0.0-beta.3

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/sylvaner/zfkctbrs/15/

**Comment by chenjiahan** [comment]
下个版本修复

**Comment by chenjiahan** [comment]
已在 1.6.22 版本修复
