### ISSUE TITLE
希望能有一个nuxt使用vant的简单demo

### ISSUE THREAD

**Issue by viiai** [youzan/vant#3428]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
vant配合nuxt使用，实现SSR的功能

**Describe the solution you'd like**
希望能有一个nuxt使用vant的简单demo

**What does the proposed API look like?**
NO

**Comment by chenjiahan** [comment]
麻烦到这个仓库下提 Demo 相关的 issue

https://github.com/youzan/vant-demo
