### ISSUE TITLE
微信升级7.0.4版本后，快速点击某个click事件会弹出一个黑屏loding

### ISSUE THREAD

**Issue by hello-lun** [youzan/vant#3429]
问题：
**安卓某些手机升级微信7.0.4版本后**，我在代码绑定了个click事件来切换页面，当连续快速点击同一个click事件，页面会无端端弹出一个黑屏的loding。这个黑屏loding只要轻点一下屏幕就会消失。经过排查，代码里面没有关于黑屏loding的代码，但这个黑屏是怎么来的呢？？？（苹果手机没有出现这个问题）
效果如下：
![image](https://user-images.githubusercontent.com/34638158/58772580-4c46df80-85ec-11e9-83ec-07241371cdef.png)

**Comment by chenjiahan** [comment]
请问这个问题跟 vant 有什么关系吗

**Comment by hello-lun** [comment]
> 请问这个问题跟 vant 有什么关系吗

我也不确定是不是vant的问题，但是这个loding好像就是vant的loding。所有想看看你们是什么建议

**Comment by chenjiahan** [comment]
这个不是 Vant 的 loading 呢，长得不一样
