### ISSUE TITLE
Dialog的close-on-click-overlay事件与cancle事件冲突

### ISSUE THREAD

**Issue by VenusPP** [youzan/vant#3431]
问题: 在使用Dialog时点击蒙层关闭会触发cancle事件。
期望: 把点击蒙层关闭事件与cancle事件分开单独处理。有些业务逻辑里cancle是有单独的业务处理。
版本: "vant": "1.6.18"

**Comment by chenjiahan** [comment]
试了下没这个问题呀，能提供 jsfiddle 么

**Comment by VenusPP** [comment]
> 试了下没这个问题呀，能提供 jsfiddle 么

我也想用jsfiddle啊，可它怎么着都打不开啊，翻了墙也不行（捂脸哭）
我用图片方式粘过来吧 
![image](https://user-images.githubusercontent.com/28476594/58783496-998a7780-8613-11e9-9850-1efdaf58c1da.png)
![image](https://user-images.githubusercontent.com/28476594/58783613-eb330200-8613-11e9-9cd1-03065e07f326.png)
![image](https://user-images.githubusercontent.com/28476594/58783701-1fa6be00-8614-11e9-93c2-22c4679db852.png)

**Comment by chenjiahan** [comment]
Dialog.catch 对应的是关闭事件，不是 cancel 事件

来自取消按钮的 cancel 事件可以这样判断：

```js
this.$dialog.confirm({
  message: 'text',
  closeOnClickOverlay: true
}).catch(action => {
  if (action === 'cancel') {
    // do someting
  }
});
```

**Comment by VenusPP** [comment]
> Dialog.catch 对应的是关闭事件，不是 cancel 事件
> 
> 来自取消按钮的 cancel 事件可以这样判断：
> 
> ```js
> this.$dialog.confirm({
>   message: 'text',
>   closeOnClickOverlay: true
> }).catch(action => {
>   if (action === 'cancel') {
>     // do someting
>   }
> });
> ```

好的，回头试试看，辛苦了。
