### ISSUE TITLE
van-button组件在jest中无法测试点击事件

### ISSUE THREAD

**Issue by leo0828** [youzan/vant#3432]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
van-button组件在jest中无法测试点击事件

**Screenshots**
在Vue文件中，我使用了van-button组件，代码运行正常：
index.vue
```
<van-button
      class="bottom-fixed"
      size="large"
      type="info"
      @click="handleClick"
    >click</van-button>
```
然后我尝试为这个按钮增加一个测试用例：
test.spec.js
```
it('触发底部按钮点击事件，应该调用"handleClick"', () => {
        const mockFn = jest.fn()
        wrapper.setMethods({
            handleClick: mockFn
        })
        wrapper.find('bottom-fixed').trigger('click')
        expect(mockFn).toHaveBeenCalled()
    })
```
当我运行测试命令时，我得到了一个报错:
bash:
```Expected mock function to have been called, but it was not called.```
Jest指出我mock的handleClick方法没有被调用，接着我将van-button替换为原生button，测试通过了
index.vue:
```
<button class="bottom-fixed" @click="handleClick">click</button>
```

**Environment**
 - Device: macOS Mojave 10.14.4
 - Browser: chrome@latest
 - Vant Version: 2.0.0-beta.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
这里选择器是不是有问题
```js
wrapper.find('bottom-fixed')
```

是不是`find('.bottom-fixed')`

**Comment by leo0828** [comment]
> 这里选择器是不是有问题
> 
> ```js
> wrapper.find('bottom-fixed')
> ```
> 
> 应该是`find('.bottom-fixed')`

这个是笔误，代码是正确的

**Comment by chenjiahan** [comment]
我试了下没问题呀，看图
![屏幕快照 2019-06-04 下午2 17 35](https://user-images.githubusercontent.com/7237365/58855804-8a6afe80-86d3-11e9-898d-35c1475608f9.png)
<img width="517" alt="屏幕快照 2019-06-04 下午2 17 41" src="https://user-images.githubusercontent.com/7237365/58855805-8b9c2b80-86d3-11e9-9a7f-eae022b251d5.png">

**Comment by leo0828** [comment]
> 我试了下没问题呀，看图
> ![屏幕快照 2019-06-04 下午2 17 35](https://user-images.githubusercontent.com/7237365/58855804-8a6afe80-86d3-11e9-898d-35c1475608f9.png)
> <img alt="屏幕快照 2019-06-04 下午2 17 41" width="517" src="https://user-images.githubusercontent.com/7237365/58855805-8b9c2b80-86d3-11e9-9a7f-eae022b251d5.png">

我找到我的问题了，我是使用的shallowMount渲染组件

**Comment by chenjiahan** [comment]
soga，还是用 mount 吧~

**Comment by yetrun** [comment]
> soga，还是用 mount 吧~

这么随意？
