### ISSUE TITLE
下拉菜单与弹出层冲突

### ISSUE THREAD

**Issue by Ancient-Ares** [youzan/vant#3434]
**What problem does this feature solve?**
下拉菜单内 自定义时间弹出层组件 点击时间选择取消或确定按钮 下拉菜单也会关闭
原因可能是 绑定body标签的class一样 都为 “van-overflow-hidden”

**Describe the solution you'd like**
可以将class改成不一样的

**What does the proposed API look like?**

![KMUWI{TR7A7M@(2TD@G YFF](https://user-images.githubusercontent.com/19995400/58781951-d94f6000-860f-11e9-805a-78e9f2b2bf29.png)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3426
