### ISSUE TITLE
全局引入vant之后，项目中的<input>无法获取焦点，vue也无法实现数据绑定

### ISSUE THREAD

**Issue by AtlantaCaesar** [youzan/vant#3435]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
全局引入vant，发现项目中的input无法获取焦点，
vue的v-model也无法实现数据绑定，
将input换成van-field一切正常

**Screenshots**
![TIM截图20190603155042](https://user-images.githubusercontent.com/22053304/58785121-7c57a800-8617-11e9-97a9-3b1055c0c5ad.png)
![TIM截图20190603155220](https://user-images.githubusercontent.com/22053304/58785187-9a250d00-8617-11e9-8216-f44c7fe6dbfb.png)
![issue1](https://user-images.githubusercontent.com/22053304/58785293-dd7f7b80-8617-11e9-9932-3effa474c27d.gif)

**Environment**
 - Device: win10
 - Browser: google
 - Vant Version: 1.6.19

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by AtlantaCaesar** [comment]
![issue2](https://user-images.githubusercontent.com/22053304/58785845-f0df1680-8618-11e9-820d-1611a7311626.gif)
将input换成van-field之后的gif

**Comment by chenjiahan** [comment]
麻烦提供下 jsfiddle

**Comment by AtlantaCaesar** [comment]
> 麻烦提供下 jsfiddle

jsfiddle中引入vant写input是没有问题的，可能项目中其他地方有问题，我再排查一下吧，谢谢了

**Comment by chenjiahan** [comment]
好的
