### ISSUE TITLE
全局引入vant导入不成功

### ISSUE THREAD

**Issue by changbb** [youzan/vant#3436]
基于vue的框架，按照官方快速入手指南：
![image](https://user-images.githubusercontent.com/23628509/58791611-1f62ee80-8625-11e9-9d54-f273590efd51.png)

显示为红色，npm run dev 提示
* vant/lib/index.css in ./src/main.js
* vant/lib/swipe-cell in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/view/shopCar/list.vue

To install them, you can run: npm install --save vant/lib/index.css vant/lib/swipe-cell

然而按照这个提示进行安装，却提示：
 Could not install from "vant\lib\index.css" as it does not contain a package.json file.

**Comment by chenjiahan** [comment]
建议参考一下我们示例仓库的配置：https://github.com/youzan/vant-demo
