### ISSUE TITLE
（求救！！！）List组件无限刷新，看了之前相似的，还是没解决

### ISSUE THREAD

**Issue by Frank-QI7** [youzan/vant#3437]
我也看了之前别人提的类似的问题，可是还没有解决
```js
      onLoad() {
        setTimeout(() => {
          if (this.search.page < this.totalPage) {
            this.search.page += 1;
            console.log("this.search.page: ",this.search.page);
            this.$http.post("/search/page",this.search).then(({data})=> {
              this.noitem = false;
              data.items.forEach(goods => {
                goods.skus = JSON.parse(goods.skus);
                goods.skus.forEach(sku => {
                  sku.price = this.formatPrice(sku.price);
                  sku.spuId = goods.id;
                  this.goodsList.push(sku);
                })
              });
            });
            // 加载状态结束
            this.loading = false;
            
          }else{
            this.finished = true;
          }
        }, 500);
      },
```
全部页面都给加载了
![image](https://user-images.githubusercontent.com/34501285/58795406-ba65c380-8639-11e9-811a-9b526b1fed1b.png)

**Comment by huangysss** [comment]
开始请求前: 
this.loading = true

**Comment by xiechao1211** [comment]
1、loading 是否有绑定v-modle
2、onLoad 是用 @事件绑定，而不是  : 属性 绑定。最好检查下这个。

**Comment by VenusPP** [comment]
类似于加载更多这类api 建议还是自己写比较好 利于以后的扩散

**Comment by Frank-QI7** [comment]
@huangysss 谢谢回复哦，请问在个地方哪加呢？

**Comment by Frank-QI7** [comment]
@xiechao1211 
```js
 <van-list
      v-model="loading"
      :finished="finished"
      :offset="offset"
      :immediate-check="immediatecheck"
      finished-text="没有更多了"
      @load="onLoad"
    >
```
是这样写的哦，可是就是解决不了

**Comment by Frank-QI7** [comment]
@huangysss  尝试了许多地方，还是不可以   :(

**Comment by Frank-QI7** [comment]
@VenusPP 谢谢建议

**Comment by ystarlongzi** [comment]
应该是 `loading` 赋值时机错误导致的

``` javascript
onLoad() {
        setTimeout(() => {
          if (this.search.page < this.totalPage) {
         
            // 👇👇👇 请求前要先设置标识
            this.loading = true;

            this.search.page += 1;
            console.log("this.search.page: ",this.search.page);
            this.$http.post("/search/page",this.search).then(({data})=> {

              // 👇👇👇👇👇👇
              // 加载状态结束
              this.loading = false;

              this.noitem = false;
              data.items.forEach(goods => {
                goods.skus = JSON.parse(goods.skus);
                goods.skus.forEach(sku => {
                  sku.price = this.formatPrice(sku.price);
                  sku.spuId = goods.id;
                  this.goodsList.push(sku);
                })
              });
            });
            
          }else{
            this.finished = true;
          }
        }, 500);
      },



```

**Comment by Frank-QI7** [comment]
@ystarlongzi 
```js
      <van-list
      v-model="loading"
      :finished="finished"
      :offset="offset"
      :immediate-check="immediatecheck"
      finished-text="没有更多了"
      @load="onLoad"
    >

      onLoad() {
          if (this.search.page < this.totalPage) {
            // 👇👇👇 请求前要先设置标识
            this.loading = true;

            this.search.page += 1;
            console.log("this.search.page: ",this.search.page);
            this.$http.post("/search/page",this.search).then(({data})=> {
              this.noitem = false;
              data.items.forEach(goods => {
                goods.skus = JSON.parse(goods.skus);
                goods.skus.forEach(sku => {
                  sku.price = this.formatPrice(sku.price);
                  sku.spuId = goods.id;
                  this.goodsList.push(sku);
                })
              });
            });
            // 加载状态结束
            this.loading = false;
            this.noitem = false;

          }else{
            this.finished = true;
          }
      },
```
我已经改成这样了，现在出现的问题是：我只要一滑动，就会去加载新的页面，停止滑动就不会去加载新的页面，比如现在加载到第 3 页了，我再滑动，就会加载第 4 页，请问是不是 offset 的问题？

**Comment by Frank-QI7** [comment]
@ystarlongzi  offset 不管设置多少都还是出现同样的问题
当刚访问页面的时候，它会去自动加第 2 页 ，:(

**Comment by ystarlongzi** [comment]
还是 `this.loading = false` 赋值时机错误，应该在 ajax 请求完成后赋值，仔细想想这里的逻辑

``` javascript
onLoad() {
  if (this.search.page < this.totalPage) {
    // 👇👇👇 请求前要先设置标识
    this.loading = true;

    this.search.page += 1;
    console.log("this.search.page: ",this.search.page);
    this.$http.post("/search/page",this.search).then(({data})=> {

      //  👉👉👉👉👉 要在请求结束后赋值为 false
      // 加载状态结束
      this.loading = false;
      this.noitem = false;
      
      data.items.forEach(goods => {
        goods.skus = JSON.parse(goods.skus);
        goods.skus.forEach(sku => {
          sku.price = this.formatPrice(sku.price);
          sku.spuId = goods.id;
          this.goodsList.push(sku);
        })
      });
    });
  }else{
    this.finished = true;
  }
},
```

**Comment by Frank-QI7** [comment]
@ystarlongzi  已经改成和你修改过后的一模一样了，还是不行 =。=

**Comment by Frank-QI7** [comment]
@ystarlongzi  是不是也是因为高度什么的原因呢？但是我给它专门套了一个 div，写了固定的 高度，还是没解决

**Comment by ystarlongzi** [comment]
在  `onLoad` 入口处，添加以下调试信息

``` javascript
onLoad {
  console.log(`loading = ${this.loading}, finished = ${this.finished}, now = ${Date.now()}`)
  // ....... 其它逻辑
}
```

**Comment by Frank-QI7** [comment]
@ystarlongzi 
![image](https://user-images.githubusercontent.com/34501285/58861242-16d5eb00-86ed-11e9-8d71-703512e85744.png)
结果是这样子的

**Comment by VenusPP** [comment]
> @ystarlongzi
> ![image](https://user-images.githubusercontent.com/34501285/58861242-16d5eb00-86ed-11e9-8d71-703512e85744.png)
> 结果是这样子的

你的offset是设置的多少，怎么设置的呢？

**Comment by ystarlongzi** [comment]
感觉应该是 [`isReachEdg`](https://github.com/youzan/vant/blob/dev/packages/list/index.js#L86-L104) 在某些场景下计算有点问题

@Frank-QI7 可以在 ajax 结束后，在打印下日志嘛

```javascript
onLoad {
  console.log(`loading = ${this.loading}, finished = ${this.finished}, now = ${Date.now()}`)
  // ....... 其它逻辑
  this.$http.post("/search/page",this.search).then(({data})=> {
    console.log('ajax done at ', Date.now())
    // ..... 其它逻辑
  })
}
```

**Comment by Frank-QI7** [comment]
@VenusPP 这样设置的
![image](https://user-images.githubusercontent.com/34501285/58865381-9ebff300-86f5-11e9-99d1-05b3f3df8f07.png)

![image](https://user-images.githubusercontent.com/34501285/58865423-aed7d280-86f5-11e9-86f6-bbf0dfbc6423.png)

**Comment by Frank-QI7** [comment]
@ystarlongzi  现在代码的逻辑是这样的，感觉是不是因为 created 里调用 loadData() 的问题呢？
![image](https://user-images.githubusercontent.com/34501285/58867592-e0eb3380-86f9-11e9-8152-ca4e0bc5e492.png)
![image](https://user-images.githubusercontent.com/34501285/58867725-21e34800-86fa-11e9-8729-ff82af04151f.png)

日志结果：
![image](https://user-images.githubusercontent.com/34501285/58867796-3fb0ad00-86fa-11e9-925c-2d753a8fb96a.png)

感谢大神～～

**Comment by ystarlongzi** [comment]
@Frank-QI7 可以帮忙在加下这段日志嘛 ☕️ ☕️

``` javascript
// 1. 为组件添加一个 refs 属性
<vant-list
  refs="list"
/>

<script>
//  2. 👇👇👇 最顶部加下三个帮助函数
function getScrollTop(ele) {
  return 'scrollTop' in ele ? ele.scrollTop : ele.pageYOffset;
}
function getElementTop(ele) {
  return (
    (ele === window ? 0 : ele.getBoundingClientRect().top) + getScrollTop(window)
  );
}
function getVisibleHeight(ele) {
  return ele === window ? ele.innerHeight : ele.getBoundingClientRect().height;
}
// 👆👆👆

// ........ 一些代码
onLoad() {
  console.log(`loading = ${this.loading}, finished = ${this.finished}, now = ${Date.now()}`)
  
  // 3. 👇👇👇 再添加以下日志  
  const { $el, scroller } = this.$refs.list
  console.log('$el === scroller', $el === scroller, $el, scroller)
  console.log('scrollerHeight =', getVisibleHeight(scroller))
  console.log('scrollTop(el) =', getScrollTop($el))
  console.log('scroller.scrollHeight =', scroller.scrollHeight)
  console.log('getElementTop(el) =', getElementTop($el))
  console.log('getVisibleHeight(el) =', getVisibleHeight($el))
  console.log('getElementTop(scroller) =', getElementTop(scroller))
 // 👆👆👆

  // ....... 其它逻辑
  this.$http.post("/search/page",this.search).then(({data})=> {
    console.log('ajax done at ', Date.now())
    // ..... 其它逻辑
  })
}

</script>

```

**Comment by Frank-QI7** [comment]
@ystarlongzi  已经添加好：
![image](https://user-images.githubusercontent.com/34501285/58871380-02035280-8701-11e9-876d-1163752304a9.png)

![image](https://user-images.githubusercontent.com/34501285/58871027-6eca1d00-8700-11e9-9998-1504008fe343.png)

日志信息： 出错啦，😄 
![image](https://user-images.githubusercontent.com/34501285/58871415-15162280-8701-11e9-824d-078c35d4a359.png)

**Comment by ystarlongzi** [comment]
第 3 部分的日子代码外用个 `if` 语句包括试下看

``` javascript
if (this.$refs.list) {
  // 第 3 部分的日志
  // 其实这里是想获取 `<van-list />` 实例的信息，你如果有其它办法能获取实例也可以，本地可以 debug 调试看下
  // .....
}
```

**Comment by Frank-QI7** [comment]
日志如下：
![image](https://user-images.githubusercontent.com/34501285/58872728-d9308c80-8703-11e9-90ce-750700dd7431.png)

![image](https://user-images.githubusercontent.com/34501285/58872758-e6e61200-8703-11e9-9718-7dbf3dc295c4.png)

![image](https://user-images.githubusercontent.com/34501285/58872791-f5342e00-8703-11e9-8a2f-1361447b2ca8.png)

![image](https://user-images.githubusercontent.com/34501285/58872803-00875980-8704-11e9-9e79-bc9f50f848bf.png)

**Comment by Frank-QI7** [comment]
@ystarlongzi 日志在上面，谢谢大神

**Comment by ystarlongzi** [comment]
可以提供下 `navigator.userAgent` 嘛？

另外第 3 部分的日志输出可以加下下面的日志嘛 ☕️ ☕️

``` javascript
console.log('$el.getBoundingClientRect()', JSON.stringify($el.getBoundingClientRect()))
```

**Comment by Frank-QI7** [comment]
@ystarlongzi 
```navigator.userAgent = Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1```

日志：
![image](https://user-images.githubusercontent.com/34501285/58874155-2e21d200-8707-11e9-807d-bf3fcefa1ad0.png)

剩下的都是一样的，再次感谢

**Comment by ystarlongzi** [comment]
样式里有设置 <van-list /> height: 0 嘛？




| |
子龙
|
|
邮箱：zhangzilong.zzl@163.com
|

签名由 网易邮箱大师 定制

在2019年06月04日 18:58，Frank-QI7 写道：

@ystarlongzi
navigator.userAgent = Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1

日志：


剩下的都是一样的，再次感谢

**Comment by Frank-QI7** [comment]
@ystarlongzi 没有呢，我没有给它设置任何 style

**Comment by Frank-QI7** [comment]
@ystarlongzi 应该是我其他的 style 影响到了  van-list，因为我把全部css都注释掉就正常了

**Comment by Frank-QI7** [comment]
@ystarlongzi 找到原因了，就是这个 css 导致错误的：

![image](https://user-images.githubusercontent.com/34501285/58877105-18b0a600-870f-11e9-85b3-9cbeb84abd28.png)

请问怎么修改呢？

**Comment by Frank-QI7** [comment]
@ystarlongzi 感谢大神的指导～～～～

**Comment by Middletwo-Kid** [comment]
写一个可能出现这样情况的解决方案：
按照上面请求前`this.loading = true` ，请求后设置`this.loading = false`，以及在`offset`属性下，仍然出现多次加载的情况，看一下父级容器是否出现`overflow:scroll`的属性，去掉即可。
