### ISSUE TITLE
你好，我想问下索引栏可以用吗？？为什么我vant的索引栏无法正常显示

### ISSUE THREAD

**Issue by xiaoyu-1234** [youzan/vant#3438]
你好，我想问下索引栏可以用吗？？为什么我vant的索引栏无法正常显示

**Comment by xiaoyu-1234** [comment]
`
<van-index-bar>
					<van-index-anchor index="A" />
					<van-cell title="文本" />
					<van-cell title="文本" />
					<van-cell title="文本" />
					<van-index-anchor index="B" />
					<van-cell title="文本" />
					<van-cell title="文本" />
					<van-cell title="文本" />
				</van-index-bar>
`

**Comment by xiaoyu-1234** [comment]
我这是官方的示例，无法正常显示

**Comment by chenjiahan** [comment]
请确认你安装了 2.0 beta 版本噢，1.x 版本是没有这个组件的
