### ISSUE TITLE
所有的popup组件在第一次点击触发时 显示正常，但之后再点击 遮罩层会有闪烁的情况

### ISSUE THREAD

**Issue by Hanabi90** [youzan/vant#3440]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
所有的popup组件在第一次点击触发时 显示正常，但之后再点击 遮罩层会有闪烁的情况
**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: windows&ios&and
 - Browser: chrome
 - Vant Version: beta和稳定版都存在这类情况

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle
