### ISSUE TITLE
NumberKeyboard组件在iOS10的Safari 的交互问题

### ISSUE THREAD

**Issue by snocc09** [youzan/vant#3441]
**Describe the bug**
1、项目中NumberKeyboard组件为blur事件增加了隐藏键盘的动作。
2、在iOS10的Safari系统上进行兼容性测试时出现点击键盘数字后键盘隐藏的情况。取消blur事件后正常。相同代码在iOS12的手机上从未出现过该情况。
3、跟踪分析发现问题出现的时候可以在window对象上收到”touchstart“的事件监听，因此目前的解决方案为在NumberKeyboard组件上取消“touchstart”的事件冒泡，暂时可以正常使用
4、该问题无法稳定复现，与PasswordInput组件一起使用时也有出现该情况

**Environment**
 - Device: iPhone 6Plus iOS10.3.3、iPhone 6S iOS10.2
 - Browser: Safari
 - Vant Version: 1.6.16

**Comment by chenjiahan** [comment]
使用的 Vue 版本是多少呢，建议用 vue@2.5.22 看看是不是正常的

**Comment by su358936838** [comment]
我也遇到这个问题 求大神解决
