### ISSUE TITLE
SwipeCell 自动计算right/left slot宽度功能不健全

### ISSUE THREAD

**Issue by zsimple** [youzan/vant#3442]
**SwipeCell 自动计算right/left宽度功能不健全**
2.0.0-beta3 引入的自动计算SwipeCell中left/right宽度的功能非常好用，只是没有考虑用户只提供一侧slot的情况，这种情况下代码会报错。

```js
  computed: {
    computedLeftWidth() {
      if (this.leftWidth) {
        return this.leftWidth;
      }
      const rect = this.$refs.left.getBoundingClientRect();
      return rect.width;
    },

    computedRightWidth() {
      if (this.rightWidth) {
        return this.rightWidth;
      }

      const rect = this.$refs.right.getBoundingClientRect();
      return rect.width;
    }
  },
```
建议`this.$refs.left.getBoundingClientRect()` 或 `this.$refs.right.getBoundingClientRect()` 在执行前应该先判定是否真实存在。

**截图**
![image](https://user-images.githubusercontent.com/9044544/58867408-f574ff00-86ec-11e9-8080-f37942c74256.png)

**Environment**
 - Device: Any
 - Browser: Any
 - Vant Version: 2.0.0-beta3

**Comment by chenjiahan** [comment]
感谢反馈喔，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.4 版本修复
