### ISSUE TITLE
<vant-list /> 边界判断优化

### ISSUE THREAD

**Issue by ystarlongzi** [youzan/vant#3443]
**What problem does this feature solve?**
简化边界判断逻辑

**Describe the solution you'd like**
只考虑手指上滑（即上拉加载更多）这个场景，判断是否触发 `load` 的一个逻辑，就是 `<van-list />` 底部和 `sroller` 容器底部差值是否小于 `offset`

有一个实现方案是可以在 `<van-list />` 底部放一个高度为 1p 但不占据空间的占位符 `<bottom-placeholder />`，再假设 `scroller` 是非 window 对象，因为所有元素通过  `getBoundingClientRect()` 获取的值都是相对于 window 的

因此，我们在手指上滑时只要判断 `scroller` 和 `<bottom-placholder />` 的 `getBoundingClient().bottom` 差值是否小于 `offset` 即可

对于 `scroller` 是 window 的这个场景，可以认为其 `rect.bottom = window.innerHeight`

同理，手指下滑（即下拉加载更多）也类似

**What does the proposed API look like?**
- 无

**Comment by chenjiahan** [comment]
看起来是可行的，可以试验看下这个方案在代码复杂度和性能上有多少的提升，欢迎 PR~

**Comment by ystarlongzi** [comment]
预计性能提升应该不会明显，我做下比较看
