### ISSUE TITLE
希望 Field 组件新增上下排列方式 Prop

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#3446]
**What problem does this feature solve?**
希望 Field 组件新增上下排列方式，开发 H5 时产品往往希望输入框大一些显示更多的内容，这样需要使用上下排列的方式，但是现在 Vant 不支持上下排列。

**Describe the solution you'd like**
下图是达到的效果：
![image](https://user-images.githubusercontent.com/16074662/59001445-29f9cf80-8841-11e9-91f6-3d1518162232.png)

**What does the proposed API look like?**
新增 Prop：label-position ，可选值为 top / left / right

**Comment by chenjiahan** [comment]
这个暂时不会做，一个是 DOM 结构不太好调整，要考虑到 icon 等因素，还有一个是目前没有对应的视觉规范。

可以考虑不使用 label 属性，自己在上方写一个 label

**Comment by shiroringo** [comment]
嗯，终于找到了这条，原来没有属性（泪

**Comment by chenjiahan** [comment]
最新版有的呢，这是 2019 年的 issue 了
