### ISSUE TITLE
希望 Field 组件新增自定义输入框插槽

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#3447]
**What problem does this feature solve?**
希望 Field 组件新增自定义输入框插槽，在开发，有遇到表单不只有输入框的时候，可能是下拉列表或上传图片或单项或多选。

**Describe the solution you'd like**
下图的效果是下拉列表：
![image](https://user-images.githubusercontent.com/16074662/59002294-7f83ab80-8844-11e9-973d-f62daee353bc.png)

**What does the proposed API look like?**
新增默认插槽，替换输入框部分的内容。

**Comment by chenjiahan** [comment]
可以有，下个版本支持

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.5 版本支持
