### ISSUE TITLE
toast.loading 渲染多个，clear只会清除1个。

### ISSUE THREAD

**Issue by linqiang007** [youzan/vant#3448]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
执行接口请求时，会显示loading效果。后来发现多次请求，只会隐藏1个。
debugger后发现，执行完并没有立即渲染，应该是存在内存中了，然后多个toast一起渲染。
项目用的是1.6.19版本，最新版本依然有这个问题。
我看了更新日志，刚好有更新Toast的内容，发现1.6.13以下正常。

**Screenshots**
Add screenshots to help explain your problem.
![代码](https://user-images.githubusercontent.com/12245095/59002254-5bc06580-8844-11e9-8851-23c1d9aa3e91.png)

![执行几次，就会渲染几个](https://user-images.githubusercontent.com/12245095/59002366-bce83900-8844-11e9-947d-e042502fa2bf.png)

**Environment**
 - Device: mac
 - Browser: chrome
 - Vant Version: 1.6.14

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://codesandbox.io/embed/vue-template-wcis7
重现是使用setTimeout模拟

**Comment by chenjiahan** [comment]
同步都次调用 Toast 的时候会有这个问题，下个版本修复

**Comment by chenjiahan** [comment]
已在 1.6.23 版本修复
