### ISSUE TITLE
Toast.loading 的 onClose 事件一直执行

### ISSUE THREAD

**Issue by hawtim** [youzan/vant#3449]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
```js
Toast.loading({
      duration: 1500,
      mask: false,
      message: '支付处理中…',
      onClose: () => {
        console.log('xxxxx')
        this.goToPage(`pages/poolSuccess/main?villageId=${this.villageId}`)
      }
    })
```

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/11072796/59005302-7e0bb080-884f-11e9-8614-8882c4562a23.png)

**Environment**
 - Device: PC
 - Browser: Chrome Version 74.0.3729.131 (Official Build) (64-bit)
 - Vant Version: v1.6.10

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
Nope

**Comment by hawtim** [comment]
使用方式为 全局注册 Toast ，按需引入
![image](https://user-images.githubusercontent.com/11072796/59005656-06d71c00-8851-11e9-8e93-954d5fa0c420.png)

**Comment by chenjiahan** [comment]
试了下没复现，建议看下是不是你的其他逻辑有问题

**Comment by DengMingHao** [comment]
我也发现有这个问题，只有onClose里面有，执行跳转路由的方法时，就会出现死循环。

**Comment by hawtim** [comment]
@DengMingHao 检查下你页面有没有 update 这个生命周期，我之前是用了 update 才导致的问题
