### ISSUE TITLE
cell 的value 英文字符多的时候不换行，丢失文本。

### ISSUE THREAD

**Issue by junj1e** [youzan/vant#3453]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
cell 的value 英文字符多的时候不换行，丢失文本。中文没问题。

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: Android ios
 - Browser: chrome safari
 - Vant Version: latest

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle 或代码片段

**Comment by junj1e** [comment]
https://github.com/youzan/vant/issues/3453#issuecomment-499426601
jsfiddle测试没问题
不知道cdn用的那个版本的vant

**Comment by chenjiahan** [comment]
jsfiddle 没问题，说明可能是你项目里的其他样式影响的

**Comment by chenjiahan** [comment]
CDN 用的是 1.6.22 版本
