### ISSUE TITLE
Switch 开关组件bug

### ISSUE THREAD

**Issue by ZhaoLiangchuan** [youzan/vant#3454]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
active-value,inactive-value 以上两项api使用时,inactive-color的值不生效,inactive-color的颜色为active-color的颜色

**Screenshots**
![微信截图_20190606180758](https://user-images.githubusercontent.com/34114842/59025177-2f2d3d80-8886-11e9-8bdd-f73891ce5954.png)
![微信截图_20190606180833](https://user-images.githubusercontent.com/34114842/59025181-30f70100-8886-11e9-830e-7eea6a6f5019.png)
![微信截图_20190606180849](https://user-images.githubusercontent.com/34114842/59025183-32c0c480-8886-11e9-88cb-d731b1480a10.png)
![微信截图_20190606180955](https://user-images.githubusercontent.com/34114842/59025255-5a179180-8886-11e9-8713-15a94b90572a.png)
![微信截图_20190606181001](https://user-images.githubusercontent.com/34114842/59025256-5b48be80-8886-11e9-9733-a85fc3dfd017.png)
![微信截图_20190606181010](https://user-images.githubusercontent.com/34114842/59025257-5c79eb80-8886-11e9-97de-f7f543e4b891.png)

**Environment**
 - Device: pc
 - Browser: 谷歌浏览器
 - Vant Version: 1.6.21

**Reproduce**
无

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复

**Comment by chenjiahan** [comment]
已在 1.6.23 版本修复

**Comment by YouthShouting** [comment]
点击开关的方法存在点透的bug

**Comment by YouthShouting** [comment]
点击开关的方法能传入自定义参数吗？
