### ISSUE TITLE
觉得索引列表右边的导航字体太小了，覆盖样式为什么不行？

### ISSUE THREAD

**Issue by wungjyan** [youzan/vant#3456]
效果图：

![image](https://user-images.githubusercontent.com/29590076/59032904-f1d2ab00-8899-11e9-93ba-9f51c41fbf12.png)

很多样式覆盖不成功，是操作不对？

**Comment by chenjiahan** [comment]
请确认下你使用了正确的选择器，打开控制台可以看生效的样式
