### ISSUE TITLE
AddressEdit 在ios12选择地址的时候，选择省市区的时候偶尔遮罩下面的页面在滚动导致地址选不上

### ISSUE THREAD

**Issue by iyaq** [youzan/vant#3458]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.

**Screenshots**
Add screenshots to help explain your problem.

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
下面的页面在滚动是什么意思呢

**Comment by iyaq** [comment]
页面是地址列表，点击新增地址，然后选择省市区的时候，省市区可以滚动鼠标选择省市区，滚动鼠标的时候，（省市区遮罩）地址列表跟着滚动。
我觉着：框架里面的地址编辑AddressEdit 在用到省市区这个插件的时候用到popup，popup有一个属性lock-scroll 这个怎么设置？

**Comment by chenjiahan** [comment]
lock-scroll 是默认开启的

**Comment by iyaq** [comment]
如果需要关闭了，有入口或者属性吗？

**Comment by chenjiahan** [comment]
没有喔，你这个场景不需要关闭吧

**Comment by iyaq** [comment]
我现在的场景就是滑动选择省市区的时候，地址列表偶尔会滚动，导致省市区选择不上， 目前小范围测试两台ios12都有这个问题

**Comment by chenjiahan** [comment]
与 https://github.com/youzan/vant/issues/3473 重复
