### ISSUE TITLE
Tabs使用的问题

### ISSUE THREAD

**Issue by HankChong36** [youzan/vant#3459]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
A clear description of what the bug is.
首次打开页面
van-tabs__line出会现位置跟长度不匹配的异常情况

**Screenshots**
Add screenshots to help explain your problem.
![code](https://hankchong-test.oss-cn-shanghai.aliyuncs.com/issues2.png)
![image](https://user-images.githubusercontent.com/21097018/59149047-0605dc00-8a43-11e9-82d2-21292cf71c76.png)
)
**Environment**
 - Browser: Chrome 75.0.3770.80
 - Vant Version: 2.0.0-beta.2

**Comment by chenjiahan** [comment]
未复现这个问题，麻烦提供一下 jsfiddle

**Comment by ihamlet** [comment]
上面的需要 在tab添加v-if=‘index == active’ 重新渲染dom 就不会出现这样的情况

**Comment by ihamlet** [comment]
可能会帮到您

**Comment by HankChong36** [comment]
谢谢。貌似是dev下加载 css 后于 hmlt，build 后就没有这个问题了。

**Comment by CracKerMe** [comment]
虽然在prod模式下 宽度正常了，但是任然希望官方能够修复dev下 宽度不正确的bug
