### ISSUE TITLE
微信小程序中使用van-radio，无法设置选中

### ISSUE THREAD

**Issue by liuya891012** [youzan/vant#3460]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
微信小程序中使用van-radio，无法设置选中

**Screenshots**
![QQ截图20190609192537](https://user-images.githubusercontent.com/17920896/59158457-f04cf100-8aec-11e9-8b23-8e0e2f6bf03a.png)
![QQ截图20190609192545](https://user-images.githubusercontent.com/17920896/59158459-f6db6880-8aec-11e9-9a21-466c295fdd22.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
小程序请到 vant-weapp 提问喔
