### ISSUE TITLE
Sidebar无法使用

### ISSUE THREAD

**Issue by Smile-dan** [youzan/vant#3461]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
页面使用sidebar后报错 These dependencies were not found
To install them, you can run: npm install --save vant/es/sidebar vant/es/sidebar-item vant/es/sidebar-item/style vant/es/sidebar/style

```
<van-sidebar :active-key="activeKey" @change="onChange">
  <van-sidebar-item title="标签名称" />
  <van-sidebar-item title="标签名称" info="8" />
  <van-sidebar-item title="标签名称" info="99" />
  <van-sidebar-item title="标签名称" info="99+" />
</van-sidebar>
```
```
<script>
import {Sidebar, SidebarItem } from 'vant';

components: {
        [Sidebar.name]: Sidebar,
        [SidebarItem.name]: SidebarItem
}
</script>
```

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/16626064/59163882-f1a40b00-8b38-11e9-9264-8a5017fc9fb9.png)

**Environment**
 - Vant Version: 2.0

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
请确认你安装了 2.0-beta 版本，可以打开 node_modules/vant 确认下
