### ISSUE TITLE
Popup 在结合 Animate 会出现定位错误

### ISSUE THREAD

**Issue by ihamlet** [youzan/vant#3462]
因为css用到了transform: translate3d(-50%,-50%,0); 进行居中定位  有没有什么其它办法

**Comment by chenjiahan** [comment]
你需要实现什么样的效果呢

**Comment by ihamlet** [comment]
Animate.css 有很多效果  Props的transition API 基本是没用的

**Comment by chenjiahan** [comment]
想直接套用 Animate.css 是不行的，你可以在 Animate.css 的基础上添加居中定位的 transform

**Comment by ihamlet** [comment]
> 想直接套用 Animate.css 是不行的，你可以在 Animate.css 的基础上添加居中定位的 transform

给你个赞

**Comment by chenjiahan** [comment]
客气哈
