### ISSUE TITLE
Field 建议加一个东西

### ISSUE THREAD

**Issue by HDONGDeveloper** [youzan/vant#3463]
![image](https://user-images.githubusercontent.com/31230864/59168954-b5899e00-8b6a-11e9-8b73-879242725d78.png)

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议用插槽自己做

**Comment by HDONGDeveloper** [comment]
> 暂无计划支持喔，建议用插槽自己做

可是现有插槽完不成这种效果 不能加一个输入框 左侧插槽吗？

**Comment by chenjiahan** [comment]
label 插槽就可以完成，而且 label 就是输入框左侧的内容
