### ISSUE TITLE
按需引入ActionSheet (上拉菜单)组件失败

### ISSUE THREAD

**Issue by sort48-cxx** [youzan/vant#3464]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
按需引入ActionSheet (上拉菜单)组件失败

**Screenshots**
![微信截图_20190610113602](https://user-images.githubusercontent.com/17314923/59171150-5466c800-8b74-11e9-953a-e77e650bd3c9.png)

**Environment**
 - Device: 
 - Browser: 谷歌
 - Vant Version: 1.6.22

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3364
