### ISSUE TITLE
van-field type 为textarea  autosize设置boolean和object无效，如何让文本域显示多行？

### ISSUE THREAD

**Issue by qianbimomo** [youzan/vant#3465]
van-field type 为textarea  autosize设置boolean和object无效，如何让文本域显示多行？？？

**Comment by chenjiahan** [comment]
不规范的 issue，请提供 jsfiddle

**Comment by qianbimomo** [comment]
<van-field v-model="REMARK" placeholder="请输入内容"  type="texarea" :autosize="{ maxHeight: 100, minHeight: 50 }"/>高度无效。多行显示文本域改如何写？

**Comment by qianbimomo** [comment]
`<van-field v-model="REMARK" placeholder="请输入内容"  type="texarea" :autosize="{ maxHeight: 100, minHeight: 50 }"/>`
autosize：高度属性并未生效，如何让文本域多行显示？

**Comment by chenjiahan** [comment]
type="texarea" 拼写错了

**Comment by F1yan9328** [comment]
> `<van-field v-model="REMARK" placeholder="请输入内容" type="texarea" :autosize="{ maxHeight: 100, minHeight: 50 }"/>`
> autosize：高度属性并未生效，如何让文本域多行显示？

===begin===
试试从js文件中获取autosize的值，如下:
wxml文件中:
<van-cell-group>
    <van-field type="textarea" autosize="{{autosize}}" />
</van-cell-group>
js文件中,page的data对象加入对应的autosize属性及其值:
data:{
    autosize:{maxHeight: 49, minHeight: 49},
}
===end===

**Comment by Zalazzz** [comment]
autosize:{maxHeight: 100, minHeight: 24}最小高度不生效是为什么

**Comment by tsurumure** [comment]
文档写的不清楚，楼上 F1yan9328 正解

**Comment by wangdong-0607** [comment]
文档写的不清楚，楼上 F1yan9328 正解

**Comment by inputherf** [comment]
> autosize:{maxHeight: 100, minHeight: 24}最小高度不生效是为什么

我也遇到这个问题了，请问你解决了嘛，最小高度不生效

**Comment by happy-le** [comment]
> > autosize:{maxHeight: 100, minHeight: 24}最小高度不生效是为什么
> 
> 我也遇到这个问题了，请问你解决了嘛，最小高度不生效

autosize="{{ { maxHeight: 100, minHeight: 50} }}"

**Comment by inputherf** [comment]
> > > autosize:{maxHeight: 100, minHeight: 24}最小高度不生效是为什么
> > 
> > 
> > 我也遇到这个问题了，请问你解决了嘛，最小高度不生效
> 
> autosize="{{ { maxHeight: 100, minHeight: 50} }}"

为啥多包一层就能生效。我用了更粗暴的方法让最小高度生效了

**Comment by happy-le** [comment]
> > > > autosize:{maxHeight: 100, minHeight: 24}最小高度不生效是为什么
> > > 
> > > 
> > > 我也遇到这个问题了，请问你解决了嘛，最小高度不生效
> > 
> > 
> > autosize="{{ { maxHeight: 100, minHeight: 50} }}"
> 
> 为啥多包一层就能生效。我用了更粗暴的方法让最小高度生效了

外面的两层双引号代表autosize绑定的是一个变量，里面的一层双引号代表这个变量是一个对象

**Comment by buoge** [comment]
组件假如被封装，还需要透传属性写法就是 ： <xxx-input type="textarea" rows="3" :autosize="{ maxHeight: 100，minHeight: 66}"></xxx-input>

**Comment by buoge** [comment]
> > > > > autosize:{maxHeight: 100, minHeight: 24}最小高度不生效是为什么
> > > > 
> > > > 
> > > > 我也遇到这个问题了，请问你解决了嘛，最小高度不生效
> > > 
> > > 
> > > autosize="{{ { maxHeight: 100, minHeight: 50} }}"
> > 
> > 
> > 为啥多包一层就能生效。我用了更粗暴的方法让最小高度生效了
> 
> 外面的两层双引号代表autosize绑定的是一个变量，里面的一层双引号代表这个变量是一个对象

假如组件被封装过就需要把属性透传下去：<x'x'x-input type="textarea" rows="3" :autosize="{ maxHeight: 100}"></xxx-input>
