### ISSUE TITLE
[Feature Request] Uploader 支持删除图片、放大预览图片

### ISSUE THREAD

**Issue by Kennersky** [youzan/vant#3469]
![TIM截图20190610172804](https://user-images.githubusercontent.com/2129521/59186326-2483e880-8ba5-11e9-9dab-e582ed62460f.png)
如图应该在相关的位置加个删除键，不然上传后就无法再改变了，这个体验不是很好。

**Comment by chenjiahan** [comment]
后续会加上

**Comment by quayquay** [comment]
理论上应该点击图片进行放大预览然后这个地方有一个删除的事件

**Comment by AK47-dadada** [comment]
赞一个，有赞这才是做技术应有的样子，不像x了么，反馈问题需要重重关卡，比相亲还难。

**Comment by chenjiahan** [comment]
删除功能已经在 2.0.0 版本支持了，图片放大预览后续会加上

**Comment by chenjiahan** [comment]
@AK47-dadada 项目规模大了以后，issue 格式就需要规范一些。。不然很容易充斥低质量的 issue，人力维护成本会很高

**Comment by Kennersky** [comment]
大赞。

**Comment by grace618** [comment]
官网示例有删除按钮，实际用的时候，怎么没有啊，请问一下
