### ISSUE TITLE
装了你们的框架后，就报错 Error: Can't resolve 'regenerator-runtime/runtime' in

### ISSUE THREAD

**Issue by ALNY-AC** [youzan/vant#3470]
装了你们的框架后，就报错
Loading...
ERROR in ./.nuxt/client.js
Module not found: Error: Can't resolve 'regenerator-runtime/runtime' in 'F:\river\code\Azure\Ruibei\Ruibei.VisionH5\.nuxt'

![image](https://user-images.githubusercontent.com/20777182/59192061-dc1ff700-8bb3-11e9-889e-26a599ba7fc2.png)

**Comment by chenjiahan** [comment]
Vant 中没有使用这个库，建议看下是不是使用了 async/await 之类的语法导致的

**Comment by ALNY-AC** [comment]
一直都是好好的，npm i vant 之后就报错

**Comment by ALNY-AC** [comment]
我模板都是正常可运行，装了vant就报错

**Comment by chenjiahan** [comment]
建议删除 node_modules 重新安装试下

**Comment by ALNY-AC** [comment]
你当我傻子吗，新手级别的解决方案我没用过？用你们框架多长时间了，都没有这种情况。

**Comment by ALNY-AC** [comment]
你们框架就这么不作为吗

**Comment by chenjiahan** [comment]
1. vant 不是框架
2. 目前没有其他用户遇到该问题
3. 如果你想寻求帮助，请提供一个复现仓库
