### ISSUE TITLE
希望单独提供Toast.loading功能

### ISSUE THREAD

**Issue by yujiaaoyujia** [youzan/vant#3472]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
toast里的loading，跟toast一起使用的话会造成关闭loading时关闭其他toast，使用allowMultiple()又有clear仅删除一个的bug，并且没有透明度过渡效果

**Describe the solution you'd like**
希望单独提供功能，类似mint-ui indicator，这样互斥开来本身也是合理的，渐变过渡也不会被覆盖。

**What does the proposed API look like?**
Indicator.show()
Indicator.hide()

**Comment by chenjiahan** [comment]
理论上 Toast.loading 和其他 Toast 不应该同时展示的，必定会存在一方盖住另一方。你是什么场景下需要同时展示嘞

**Comment by yujiaaoyujia** [comment]
@chenjiahan 场景是这样：
我们这边的项目将loading作为全局的方法，在调用接口的时候统一调用，接口请求完后关闭loading。
同时请求多个接口时，当所有接口都调用完成，才会关闭loading。
由于请求完毕后需要toast错误信息，当请求多个接口的时候，第一个接口请求完毕调用toast信息，就会把其他接口的loading关闭，会出现这个问题。

而且我们统一的toast都是position设置为bottom的，所以位置并不会盖住。

曾经尝试使用allowMultiple()来解决问题，但使用allowMultiple之后，toast.loading之后调用普通的toast，或者反之，弹出来的样式没有透明度过渡效果，非常生硬，所以体验不是很好

**Comment by chenjiahan** [comment]
我试了一下，allowMultiple 不会影响过渡效果，是不是你的用法有问题呢

**Comment by yujiaaoyujia** [comment]
会影响过渡效果，显示的时候是正常的，关闭的时候没有渐变了。

```
import { Toast } from 'vant'

const toast = Toast
// toast.allowMultiple()

const loading = {
  show() {
    toast({
      type: 'loading',
      forbidClick: true,
      duration: 0,
      className: 'van-loading-custom',
    })
  },
  hide() {
    toast.clear()
  },
}
```

如果toast.allowMultiple()执行了，调用loading.show()
之后再调用loading.hide()，关闭的时候没有渐变效果

普通的toast也同理

**Comment by chenjiahan** [comment]
明白你的意思了，开启 allowMultiple 后在关闭时没有渐变，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.0.1 版本修复
