### ISSUE TITLE
AddressEdit 在ios12选择地址的时候，选择省市区的时候,滚动省市区插件，插件下面的页面会滚动

### ISSUE THREAD

**Issue by iyaq** [youzan/vant#3473]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
AddressEdit 在ios12选择地址的时候，选择省市区的时候,滚动省市区插件，插件下面的页面会滚动

**Screenshots**

![微信截图_20190611113331](https://user-images.githubusercontent.com/22808934/59242177-24cfc280-8c3d-11e9-94f7-dca3a9b60a72.png)
lem.

**Environment**
 - Device: ios12
 - Browser: 微信浏览器
 - Vant Version: 1.6.10

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
和这个 issue 有什么区别吗
https://github.com/youzan/vant/issues/3458

**Comment by iyaq** [comment]
这个描述的清晰一些 ，我一直没有想明白为啥触发框框里面的区域滚动，下面的页面怎么滚动了

**Comment by chenjiahan** [comment]
移动端会有滚动穿透的问题，我们也在代码中加了一些防止穿透的操作，但是不能避免所有的情况。滑动这块区域应该不属于常规操作吧

**Comment by iyaq** [comment]
嗯，我也是查资料发现是滚动穿透的问题，看之前有个问题跟这个有关系，加了这个
`bodyScroll(event){
                event.preventDefault();
            },
            forbidBodyScroll () {
                document.getElementsByTagName('body')[0].addEventListener('touchmove', this.bodyScroll, false)
                $("body").css({"position":'fixed','height':'100%','overflow':'hidden'})
            },
            allowBodyScroll () {
                document.getElementsByTagName('body')[0].removeEventListener('touchmove', this.bodyScroll, false)
                $("body").css({"position":'static','height':'auto','overflow':'auto'})
            },`

**Comment by chenjiahan** [comment]
这个方法可以解决问题，也会带来一些副作用，比如弹窗内部的滚动条会失效。在这个场景下是可以使用的

**Comment by iyaq** [comment]
嗯嗯，谢谢您

**Comment by chenjiahan** [comment]
客气哈
