### ISSUE TITLE
你好，在升级版本之后发现配置主题后，主题颜色无法生效了

### ISSUE THREAD

**Issue by AK47-dadada** [youzan/vant#3476]
如题，vue-cli3.x
代码：
css: {
    // modules: false,
    // loaderOptions: {},
    loaderOptions: { // 向 CSS 相关的 loader 传递选项
      less: {
        modifyVars: { // vant全局变量的修改
          // red: '#03a9f4',
          // blue: '#3eaf7c',
          // orange: '#f08d49',
          // 'text-color': '#111',
          green: "#FF8D30"
        }
      },
      sass: { // 自己全局变量的引入
        data: ` @import "@/styles/var.scss"; `
      }
    }
  },

**Comment by chenjiahan** [comment]
是否引入了 vant 的 Less 样式呢

**Comment by AK47-dadada** [comment]
> 是否引入了 vant 的 Less 样式呢

引入了的，升级2.0.0-bate版本前我就是按照官网的配置标准来的，那时候还是生效的

**Comment by AK47-dadada** [comment]
可以关闭了，这是我自己自身原因构成的
