### ISSUE TITLE
uploader 上传图片后要是能够点击图片预览，以及可以删除就好了

### ISSUE THREAD

**Issue by zhangweijianNo1** [youzan/vant#3478]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by zhangweijianNo1** [comment]
uploader 目前上传图片后，无法对该图片进行删除。当只上传一张图片时，可以用在组件内部添加img标签的方式实现点击图片上传新图片替换之前上传的图片，但是多个的话，就不能对之前上传的图片进行重新上传，也不能删除

**Comment by chenjiahan** [comment]
重复issue https://github.com/youzan/vant/issues/3469
