### ISSUE TITLE
Tab 组件粘性布局是否可以加入自定义top功能

### ISSUE THREAD

**Issue by wungjyan** [youzan/vant#3481]
粘性布局可以满足一般吸顶效果，但是有时不需要它top=0，比如有一个固定的顶部导航菜单需要始终显示在顶部，此时也需要tabs的吸顶效果，但必须在顶部导航菜单之下，如下：
![image](https://user-images.githubusercontent.com/29590076/59322736-3cc14800-8d0a-11e9-85de-5860e2b003a5.png)

是否可以加入自定义top属性？谢谢。

**Comment by chenjiahan** [comment]
已经有了，`offset-top` 属性，见文档
