### ISSUE TITLE
DatetimePicker在手机字体放大后出现乱序的问题

### ISSUE THREAD

**Issue by lwh2015** [youzan/vant#3483]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Describe the bug**
DatetimePicker在手机字体放大后，点击出现选择时间框后样式错乱。

**Screenshots**
![image](https://user-images.githubusercontent.com/16028333/59334879-072e5600-8d2e-11e9-9a56-5191eebc2054.png)

**Environment**
 - Device: 
![image](https://user-images.githubusercontent.com/16028333/59334994-4361b680-8d2e-11e9-84a4-11ec5c947e2e.png)

 - Browser: 
 - Vant Version: 1.0.1

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
这个问题已经在新版本里修复了，建议升级到最新版试下

**Comment by lwh2015** [comment]
> 这个问题已经在新版本里修复了，建议升级到最新版试下

更新到2.0版本会有破坏性的更新吗？

**Comment by chenjiahan** [comment]
会有的，请查看更新日志。如果你暂时升级不了，可以加一行临时样式来解决

```css
.van-picker {
  -webkit-text-size-adjust: 100%;
}
```

**Comment by lwh2015** [comment]
> 会有的，请查看更新日志。如果你暂时升级不了，可以加一行临时样式来解决
> 
> ```css
> .van-picker {
>   -webkit-text-size-adjust: 100%;
> }
> ```

好的，我看看
