### ISSUE TITLE
Uploader 图片上传 file数据为空

### ISSUE THREAD

**Issue by faimaklg** [youzan/vant#3486]
**Describe the bug**
图片上传组件，不管是使用v-model还是after-read回调得到的数据里的file字段里都没有数据

**Screenshots**
![image](https://user-images.githubusercontent.com/18085334/59359532-14186d00-8d61-11e9-9daf-c5b515e3198b.png)

**Environment**
 - Device: 
 - Browser: 
 - Vant Version: 2.0.0

**Reproduce**
```
<van-uploader
    v-model="fileList"
    multiple
    :after-read="afterRead">
</van-uploader>
```

**Comment by Taaaaaaang** [comment]
到底为啥, 我也偶尔有这个奇葩问题

**Comment by LvJianfeng** [comment]
@faimaklg  请问是如何解决的哦，在iOS上选择后使用没有数据；

**Comment by PerfectYan** [comment]
> @faimaklg 请问是如何解决的哦，在iOS上选择后使用没有数据；

你解决了吗？我iOS11.2也遇到了这个问题

**Comment by weibalangzi** [comment]
如果你们是用的vconsole打印file，看到的确实是个{}，如果你查看file.name或者file.size，会发现file其实不为空
