### ISSUE TITLE
列表上拉刷新

### ISSUE THREAD

**Issue by ihamlet** [youzan/vant#3487]
列表上拉刷新 overflow-y: scroll;    体验很不好  请优化一下吧  给你们点赞哦

**Comment by chenjiahan** [comment]
具体是哪个组件呢？ 如果是你自己写的 `overflow-y: scroll`，可以加上`-webkit-overflow-scrolling: touch;`这个样式来解决

**Comment by ihamlet** [comment]
<van-list />  父组件使用   overflow-y: scroll  它的下拉加载失效

**Comment by ihamlet** [comment]
van-list

**Comment by ihamlet** [comment]
> 具体是哪个组件呢？ 如果是你自己写的 `overflow-y: scroll`，可以加上`-webkit-overflow-scrolling: touch;`这个样式来解决

父级div 如果使用 overflow-y: scroll   van-list 它的下拉加载就会失效

**Comment by ihamlet** [comment]
> 具体是哪个组件呢？ 如果是你自己写的 `overflow-y: scroll`，可以加上`-webkit-overflow-scrolling: touch;`这个样式来解决

对不起是我弄错了   非常感谢你
