### ISSUE TITLE
电脑端，在Actionsheet中，DatetimePicker、Area组件无法拖动

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#3489]
**Describe the bug**
电脑端，在Actionsheet中，DatetimePicker、Area组件无法拖动。只能一个一个点。

**Screenshots**
见jsfiddle

**Environment**
 - Device: pc
 - Browser: Chrome
 - Vant Version: 2.0.0-beta.2

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/sylvaner/wmd28n5g/9/

**Comment by chenjiahan** [comment]
桌面端使用，请参考 [快速上手](https://youzan.github.io/vant/#/zh-CN/quickstart) 最下面的章节
