### ISSUE TITLE
国际化修改异常

### ISSUE THREAD

**Issue by C009** [youzan/vant#3491]
**Describe the bug**
国际化修改不生效

**Environment**
 - Vant Version: 2.0.

**Reproduce**
import { Locale } from 'vant';
const messages = {
  'zh-CN': {
    vanCouponCell: {
      count: (count) =>`${count} 张`
    }
  }
}

Locale.add(messages);

**Comment by chenjiahan** [comment]
目前函数类型的国际化文案确实没办法修改，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.0.1 版本修复
