### ISSUE TITLE
van-list只能触发一次onload，滚动条到底部也不能再次触发

### ISSUE THREAD

**Issue by 18353230045** [youzan/vant#3492]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

bug描述：
van-list只能触发一次onload，滚动条到底部也不能再次触发

截图：
![image](https://user-images.githubusercontent.com/26160078/59404987-61d1bb80-8ddb-11e9-8bb3-0ca5cf15b12b.png)
![image](https://user-images.githubusercontent.com/26160078/59405030-90e82d00-8ddb-11e9-85b4-f041f8483111.png)
![image](https://user-images.githubusercontent.com/26160078/59405047-a9f0de00-8ddb-11e9-98ee-50511e5dc7e9.png)
![image](https://user-images.githubusercontent.com/26160078/59405061-bbd28100-8ddb-11e9-9ca2-111476b4fc48.png)
环境：
 - 设备: PC
 - 浏览器: chrome
 - Vant 版本: 1.6.10

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/522/

**Comment by chenjiahan** [comment]
加载完成后要将 loading 状态设置为 false 的，文档里有说明

**Comment by 18353230045** [comment]
> 加载完成后要将 loading 状态设置为 false 的，文档里有说明

在加载数据的时候已经设置为false,但是滚动条拉到底部还是没有再次触发onload

**Comment by chenjiahan** [comment]
麻烦提供一下复现的 jsfiddle

**Comment by 18353230045** [comment]
> 麻烦提供一下复现的 jsfiddle

VPN坏了，上不去jsfiddle，具体就是在load事件拿到数据后loading置为false，但是拉到列表底部不再触发onload

**Comment by chenjiahan** [comment]
可以使用 Codesandbox 喔，https://codesandbox.io/s/m5v3f

**Comment by GPPoseidon999** [comment]
同样出现上述问题

**Comment by ystarlongzi** [comment]
@18353230045 `loadOrderList` 方法的逻辑是什么？方便提供下嘛，`loading` 赋值是在这个函数里嘛

**Comment by fengyun2** [comment]
同样出现上述问题

**Comment by 18353230045** [comment]
问题已解决，如果初始给DOM设置高度为100%，就会导致该问题，移除该属性，list正常触发

**Comment by fengyun2** [comment]
> 问题已解决，如果初始给DOM设置高度为100%，就会导致该问题，移除该属性，list正常触发

能提供个在线demo么？

**Comment by 18353230045** [comment]
> > 问题已解决，如果初始给DOM设置高度为100%，就会导致该问题，移除该属性，list正常触发
> 
> 能提供个在线demo么？
导致该问题的原因是最外层html高度为100%，导致vant-list无法触发滚动条，可以参考http://ustbhuangyi.github.io/better-scroll/doc/zh-hans/#%E8%B5%B7%E6%AD%A5，滚动原理

**Comment by fengyun2** [comment]
@18353230045 本来body层就是要满屏了呢，这怎么整？

**Comment by 18353230045** [comment]
> @18353230045 本来body层就是要满屏了呢，这怎么整？

可以尝试给需要滚动的List设置一个固定高度，List实现原理应该是跟better-scroll一样的，这两个组件都是body高度100%就失效了

**Comment by ystarlongzi** [comment]
@fengyun2 @18353230045  

html、body 的样式是这样设置的嘛？

```css
html, body {
  height: 100%;
  overflow-y: scroll;
}

body {
  -webkit-overflow-scrolling: touch;
}
```

**Comment by ystarlongzi** [comment]
可关注 #3823

**Comment by xiehaoWeb** [comment]
在van-popup组件内写list 然后不触发，怎么办？

**Comment by zerotower69** [comment]
我也遇到这个问题，而且我是搭配pullRefresh使用，具体代码
```vue
<van-pull-refresh v-model="isDownLoading" @refresh="onRefresh()">
              <van-list
                v-model="loading"
                :finished="finished"
                finished-text="没有更多了"
                @load="onLoad"
                :immediate-check="false"
                :offset="20"
              >
                 ......
              </van-list>
</van-pull-refresh>
```
在chrome手机版 Edge、小米浏览器、safari(iPhone)测试通过，在QQ浏览器、华为浏览器、UC浏览器小米版测试失败
我看到说，给list的父容器增加 overflow-y:scroll以及height:100%能解决问题
但是我经过实际测试后，发现了overflow-y:scroll会导致list的load不断会触发。
于是，经过检查DOM，可以发现：
![list-error](https://i.postimg.cc/tgNC27vC/list-error.png) 
list的父级div,对齐强制样式覆盖
```scss
::v-deep .van-pull-refresh__track{
  height: 100%;
  overflow-y:auto ;
}
```
可以成功解决上述两个问题。

**Comment by ouzexi** [comment]
> 

请问这个问题您解决了吗，我也遇到了
