### ISSUE TITLE
van-list只能触发一次onload

### ISSUE THREAD

**Issue by skymon4** [youzan/vant#3496]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**
van-list只能触发一次onload，滚动条到底部也不能再次触发 模仿官方例子一次触发三次 并不触发第四次 滚动到底部 loading 依旧为false

**Screenshots 截图**
![image](https://user-images.githubusercontent.com/33510540/59416467-fb0ecb00-8df7-11e9-8df3-c95028173686.png)
![image](https://user-images.githubusercontent.com/33510540/59416497-0feb5e80-8df8-11e9-8935-ff3a76e98684.png)

**Environment 环境**

 - Device: pc
 - Browser: chrome
 - Vant Version: 1.6.10

**Reproduce 复现步骤**

请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by chenjiahan** [comment]
finished 的判断，不应该写在请求体的外面，而是写在请求完成后

**Comment by skymon4** [comment]
finish的判断卸载请求体内 依旧滚动到底部不触发onload

**Comment by chenjiahan** [comment]
@skymon4 建议按照文档示例去试下，理解一下这个组件的几种状态

**Comment by ystarlongzi** [comment]
@skymon4 在接口请求前，要主动设置 `this.loading = true`

**Comment by FlowerInSunnySun** [comment]
按照官网给的例子，也是不会滚动到最后就请求第二次、第三次...

**Comment by fengyun2** [comment]
同样出现上述问题

**Comment by ystarlongzi** [comment]
> 按照官网给的例子，也是不会滚动到最后就请求第二次、第三次...

见文档 [为什么会连续触发 load 事件？](https://youzan.github.io/vant/#/zh-CN/list)

@chenjiahan 这些场景问题可以加个锚点吧，方便跳转

**Comment by chenjiahan** [comment]
@ystarlongzi ok，后续会加上
