### ISSUE TITLE
List 列表元素的间隔横线为什么都是向右倾斜了？

### ISSUE THREAD

**Issue by iPhonePKAndroid** [youzan/vant#3500]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**

**Screenshots 截图**
![屏幕快照 2019-06-13 下午5 37 43](https://user-images.githubusercontent.com/44493686/59421992-2f878480-8e02-11e9-9b3c-d0b9f24516d1.png)

**Environment 环境**

 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce 复现步骤**

请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by chenjiahan** [comment]
这个跟 List 组件无关哈，因为里面使用的是 Cell 组件，Cell 的下划线默认是有左边距的
