### ISSUE TITLE
Tabbar 标签栏指定name的他又乱选中了

### ISSUE THREAD

**Issue by shijunti19** [youzan/vant#3502]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**
2个页面来回切换，我指定了name，他还是乱选中
你看下面的active的值当list的时候我切换回去的时候他选中了home根本没匹配，我没主动赋值，是本身的点击赋值的，纯粹2个页面来回切换根据变量判断的

注意，第一个图标我有if判断的（不是常规的一直显示的，当0的时候他可能是home也可能是list）
**Screenshots 截图**
![image](https://user-images.githubusercontent.com/5392211/59475743-dc541700-8e7f-11e9-875b-6700f229589f.png)
![image](https://user-images.githubusercontent.com/5392211/59475756-e5dd7f00-8e7f-11e9-9aa0-9c205ddf37de.png)

**Environment 环境**
什么都是最新的
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce 复现步骤**
代码太多了，我不弄
请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by jasconchen** [comment]
为什么不直接用computed计算属性呢
![image](https://user-images.githubusercontent.com/16459997/59477361-6b186200-8e87-11e9-84d8-1f72f6ac791b.png)

**Comment by shijunti19** [comment]
@jasconchen 我是觉得没必要多写这么多代码去优化，按逻辑，这就是组件本身的功能啊！

**Comment by jasconchen** [comment]
v-if的问题
我的解决方案是写两个tabbar,然后通过vuex全局控制

**Comment by chenjiahan** [comment]
没看懂你的描述，建议提供一个最简的 codesandbox

**Comment by shijunti19** [comment]
@chenjiahan 
![image](https://user-images.githubusercontent.com/5392211/59487450-5059e380-8eaf-11e9-9088-e96e69098b2b.png)
**active的当前值是list，但是如图他在home这个上高亮。**
点第3个页面，我第一个home会隐藏，list会变成第一个，这时候我点第一页list，回到之前页面，这时候home显示出来，组件会高亮6他，其实错误的，应该高亮第二个list，因为这时候第一个v-if判断显示了

**Comment by chenjiahan** [comment]
我试了下没问题，请确认你使用的是 2.0 版本，且用法和文档一致

**Comment by shijunti19** [comment]
@chenjiahan 
  "vant": "^2.0.0",
```js
import { Tabbar, TabbarItem } from 'vant'
 <van-tabbar v-model="active">
        <van-tabbar-item name="home" v-if="!$route.query.team" icon="notes-o" :to="{ name: 'index' }">
            主页
        </van-tabbar-item>
        <van-tabbar-item name="list" icon="user-circle-o" :to="{ name: 'team_list' }">
            {{ $t('menpai') }}列表
        </van-tabbar-item>
        <van-tabbar-item
            name="team"
            v-if="$route.query.team"
            icon="user-circle-o"
            :to="{ name: 'team_index', query: { team: $route.query.team } }"
        >
            {{ $t('menpai') }}
        </van-tabbar-item>
        <van-tabbar-item
            name="team_article"
            icon="notes-o"
            :to="{ name: 'team_article', query: { team: $route.query.team } }"
        >
            文章
        </van-tabbar-item>
        <van-tabbar-item
            name="word_add_add"
            v-if="$route.name == 'team_article' && $route.query.team"
            icon="records"
            :to="{ name: 'word_add', query: { team: $route.query.team } }"
        >
            发表文章
        </van-tabbar-item>
        <van-tabbar-item
            name="word_add_edit"
            v-else
            icon="records"
            :to="{ name: 'team_add', query: { team: $route.query.team } }"
        >
            {{ $route.query.team ? '编辑' : '申请' }}
        </van-tabbar-item>
    </van-tabbar>
```
