### ISSUE TITLE
tab组件在手机uc浏览器下点击无法切换问题

### ISSUE THREAD

**Issue by sjwwap** [youzan/vant#3506]
![微信图片_20190614140123](https://user-images.githubusercontent.com/18587035/59486806-2bfd0780-8ead-11e9-9a80-ebfa5f2c37d2.jpg)
zui最开始以为自己写的代码有问题，经反复测试，只有uc浏览器会出现点击无法跳转

**Comment by chenjiahan** [comment]
示例文档有同样的问题吗？如果能复现，麻烦提供一下机型
