### ISSUE TITLE
怎样在源码中新增组件？

### ISSUE THREAD

**Issue by Panseng** [youzan/vant#3508]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
在源码的packages文件中新增组件，在types/index.d.ts中export class
编译后在es和lib中的组件没有index.js & index.less文件

**Describe the solution you'd like**
我想在vant ui源码中新增组件
上午尝试将field组件复制重命名为field-test，同时修改sfc & bem名称、less类名、index.d.ts类名。
然后npm run build:lib，编译后，lib & es中的field-test文件夹中找不到index.js & index.less文件。

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
请阅读贡献指南中的『添加新组件』章节
https://youzan.github.io/vant/#/zh-CN/contribution

**Comment by Panseng** [comment]
还是出错，错误一样。
在 docs/src/doc.config.js配置了中文和因为的path和title，编译后还是没有index.js & index.less文件。
