### ISSUE TITLE
更新日志描述错误

### ISSUE THREAD

**Issue by Zeolion** [youzan/vant#3509]
更新日志中关于badge变动描述错误
SidebarItem写成了SlideBarItem
![image](https://user-images.githubusercontent.com/33861242/59491737-fb6f9a80-8eb9-11e9-9536-567e77e94d2b.png)

 - Device: PC
 - Browser: Chrome
 - Vant Version: 2.0.0

**Comment by chenjiahan** [comment]
感谢反馈，文档已更正
