### ISSUE TITLE
关于list的load事件

### ISSUE THREAD

**Issue by CoutinhoTTS** [youzan/vant#3510]
在最近使用vant的list列表组件时，其实在我页面进入的时候列表还是空的这时页面并没有出现滚动条。但这时load事件就自动执行了，所以我就将请求页面初始数据从created钩子函数放到了load中。当时我需要实现的功能是前进刷新，返回不刷新，所以我需要给列表页做缓存，离开的时候数据都存在了浏览器，再进去的时候判断是前进还是返回，当我是前进的时候起就将data里的数据全部初始化了，这个时候列表的数据也都没了页面也没有滚动条，他应该自动执行load从新请求刷新数据。也确实怎么实现了，但项目后面有一个模块的功能是先进去的时候执行load事件但不会给list添加数据，只有在点击搜索后才给list添加数据，点击搜索后数据添加成功，当滚动条滚到设定的位置时再次出发load事件这些都是正常的。但这个时候就问题也出现了当返回上级页面再从新进入列表页他不会自动执行load事件，但这个时候data里的数据全部都初始化了什么
finished，v-model都是设置了false。页面也没有出现加载动画，这是什么问题？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by chenjiahan** [comment]
不规范的 issue，麻烦按照 issue 格式提问
