### ISSUE TITLE
数字键盘-默认键盘收起-点击按钮触发键盘弹出-第一次点击数字不触发@input事件

### ISSUE THREAD

**Issue by 1297947244** [youzan/vant#3513]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**
数字键盘-自定义键盘
Vue项目中，默认键盘收起，点击按钮触发键盘弹出-第一次点击数字，不触发@input事件。

**Screenshots 截图**
![image](https://user-images.githubusercontent.com/18436456/59497280-b9e4ec80-8ec5-11e9-8ef3-79e007bd7a32.png)

**Environment 环境**
Chrome模拟手机模式
 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce 复现步骤**

请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by chenjiahan** [comment]
试了下没复现此问题，能否提供一下 codesandbox
