### ISSUE TITLE
cdn引入dialog组件before-close多次触发事件回调

### ISSUE THREAD

**Issue by MarcoBeer** [youzan/vant#3517]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**
我用cdn方法来引入的vant，以dialog组件方式调用,使用:before-close="handle()"
但不是在关闭dialog的时候触发，而是页面加载，显示，关闭的时候，都会触发
:before-close="handle()" 的回调函数
**Screenshots 截图**

**Environment 环境**
 

 - Device: 
 - Browser: 
 - Vant Version: 2.0.0

**Reproduce 复现步骤**

 <van-dialog
  v-model="showForm"
  :title="formTitle"
  show-cancel-button
  confirm-button-text='提交'
  :before-close="submit()"
  >
<p>一些自定义的html</p>
</van-dialog>

请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by chenjiahan** [comment]
请提供复现问题的 codesandbox

**Comment by MarcoBeer** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0, user-scalable=no">
<title>总后台管理</title>

<link rel="stylesheet" href="http://i.gtimg.cn/vipstyle/frozenui/2.0.0/css/frozen.css"/>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vant@2.0/lib/index.css">


<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vant@2.0/lib/vant.min.js"></script>

<style type='text/css'>
		.dialog-btn-item{
			width:50%;
		}
		
		
	</style>


</head>
<body>
	
	<section id="app" >
		


<header class="ui-header ui-header-stable ui-border-b" > <i class="ui-icon-return" onClick="location.href='baobiao.htm';"></i>
  <h1>虚拟商品管理</h1>
</header>



<div class="ui-tooltips ui-tooltips-guide ui-tooltips-function" style="margin-top: 45px;">
   
   
  <div class="ui-row-flex ui-whitespace">
    <div class="ui-col ui-col"> <button class="ui-btn-lg" onClick="location.href='bsjbaobiao.html';">收款设置</button></div>
    <div class="ui-col ui-col"> <button class="ui-btn-lg" onClick="location.href='bsqudao.html';">渠道设置</button></div>
    <div class="ui-col ui-col"> <button class="ui-btn-lg ui-btn-primary" onClick="location.href='shoplist.html';">商品库</button></div>
   
</div> 

</div>


<div class="ui-tooltips ui-tooltips-guide ui-tooltips-function" style="margin-top: 15px;">
   
       <div class="ui-tooltips-cnt ui-border-b"  style="margin-bottom:10px;">
        <i></i>您还没设置虚拟商品。<button class="ui-btn-s" @click="showForm=!showForm" >添加</button>
        
    </div>
</div>
   
</div>



<ul class="ui-list ui-list-nospace ui-border-tb">
    <li class="ui-border-t ui-arrowlink" onClick="location.href='shopshezhi.html';" >
       
        <div class="ui-list-info">
            <h4 class="ui-nowrap">房费</h4>
            
                  
        </div>
    </li>
    
	</ul>



<ul class="ui-list ui-list-nospace ui-border-tb">
    <li class="ui-border-t ui-arrowlink" onClick="location.href='shopshezhi.html';" >
       
        <div class="ui-list-info">
            <h4 class="ui-nowrap">零食</h4>
            
                  
        </div>
    </li>
    
	</ul>
    
    <ul class="ui-list ui-list-nospace ui-border-tb">
    <li class="ui-border-t ui-arrowlink" onClick="location.href='shopshezhi.html';" >
       
        <div class="ui-list-info">
            <h4 class="ui-nowrap">餐饮费</h4>
            
                  
        </div>
    </li>
    
	</ul>
    <ul class="ui-list ui-list-nospace ui-border-tb">
    <li class="ui-border-t ui-arrowlink" onClick="location.href='shopshezhi.html';" >
       
        <div class="ui-list-info">
            <h4 class="ui-nowrap">其他</h4>
            
                  
        </div>
    </li>
    
	</ul>
	
  <van-dialog
  v-model="showForm"
  :title="formTitle"
  show-cancel-button
  confirm-button-text='提交'
  :beforeClose="submit()"
  >

  <van-cell-group>
  
  <van-field
    v-model="form.username"
    required
    clearable
    label="商品名称"
    placeholder="请输入商品名称:房费"
    /> 
</van-cell-group>

<van-cell-group>	
	<van-switch-cell active-value="1" inactive-value="0" v-model="form.onOff" :title="form.onOff==1?'是否启用(已启用)':'是否启用(已关闭)'" />

</van-cell-group>





	

	







  
</van-dialog>
	
	
		
		
	</section>
</body>
<script>
var Vue = window.Vue;
var vant = window.vant;

// 注册组件
Vue.use(vant);

var v=new Vue({
	el:'#app',
	data()
	{
		return {
			title:'我是vue的标题',
			showForm:false,
			formTitle:'添加虚拟商品',
			form:{
				username:null,
				onOff:0
			}
		}
	},
	methods:{
		submit:function(e,done)
		{
			console.log(e,done,'submit,这个事件回调会多次触发');
			
			
			
			return;
			var loading=this.$toast.loading({
			  mask: true,
			  message: '提交中...',
			  icon:'spinner'
           });
		   
		   setTimeout(function(){
			   loading.clear();
		   },3000)
		 
			
			return false;
		},
		
		
	},
	mounted()
	{
		
	}
})




// 调用函数式组件
// vant.Toast('提示');
</script>
</html>
`

**Comment by MarcoBeer** [comment]
------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年6月14日(星期五) 晚上8:48
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "MarCoXiong"<314779559@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] cdn引入dialog组件before-close多次触发事件回调 (#3517)




请提供复现问题的 codesandbox

**Comment by MarcoBeer** [comment]
> 请提供复现问题的 codesandbox

已经发送到你的邮箱，是否能收到？就一个html文件，打开就可以运行

**Comment by chenjiahan** [comment]
没收到喔，最好提供 codesandbox，邮件太过低效

**Comment by MarcoBeer** [comment]
我不太会用github,不知道什么是codesandbox，就一个html文件，cdn方式引入的，要不你加 我的qq314779559，我直接发给你，或者你留一个邮箱，我发给你，打开文件，查看console.log就可以看到

**Comment by MarcoBeer** [comment]
这个bug在使用脚手架模式下，一样存在，请引起重视

**Comment by chenjiahan** [comment]
发我邮箱吧，chenjiahan@neverl.com

**Comment by chenjiahan** [comment]
看了下上面的代码是有问题的，before-close 传入的应是一个函数，而不是函数的执行结果
