### ISSUE TITLE
TS下没有声明Image标签

### ISSUE THREAD

**Issue by JaneCC** [youzan/vant#3519]
**Describe the bug 描述问题**
TS下没有声明Image标签

**Screenshots 截图**
![TIM截图20190615095019](https://user-images.githubusercontent.com/9154684/59545609-24903980-8f53-11e9-8e66-e755b526343d.png)

**Environment 环境**

 - Device: 
 - Browser:  
 - Vant Version:  2.0.0

**Reproduce 复现步骤**
typescript下vant@2.0.0引入Image即可，vant\types\index.d.ts里面没有声明

**Comment by chenjiahan** [comment]
已在 2.0.1 版本修复
