### ISSUE TITLE
有支持typescript的计划吗？

### ISSUE THREAD

**Issue by joel-chen** [youzan/vant#352]
想了解下支持typescript的安排和计划吗？

**Comment by chenjiahan** [comment]
@joel-chen 请问你指的支持 TS 具体是哪些方面？ 是提供 Toast/Dialog 这类函数组件对应的 d.ts 文件吗，还是其他方面

**Comment by chenjiahan** [comment]
@joel-chen 已在 0.11.4 中加入 TS 类型支持
