### ISSUE TITLE
vant明明有es版本，为何不用babel-plugin-import，打包后体积会很大？

### ISSUE THREAD

**Issue by anthinkingcoder** [youzan/vant#3523]
vant提供了`es`版本，应该是可以tree shaking的呀，像用ant-design，boostrap-vue这些，即使不用babel-plugin-import， 依然实现了按需加载，打包后的体积和使用babel-plugin-import差不多大(除了按需加载样式文件)。
[https://github.com/ant-design/babel-plugin-import/issues/328](url)

**Comment by chenjiahan** [comment]
感谢反馈，没加`sideEffects`导致的，下个版本加上

**Comment by chenjiahan** [comment]
已在 2.0.2 版本支持
