### ISSUE TITLE
希望添加Field组件对于van-field的点击事件

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#3525]
**What problem does this feature solve?**
对于Field组件，有时候我的期望是：让用户选择，而不是让用户填写。如下图：
![企业微信截图_20190617095847](https://user-images.githubusercontent.com/31810070/59574079-74543980-90e8-11e9-94ba-b958bd915a03.png)
但是在Field的click事件会传递到input里面，这会导致点击Field组件的非input区域无法捕获事件。
目前我通过改写为Cell组件实现点击功能，但是写起来感觉在绕弯路。
```
 <van-cell 
  class="van-cell--required" 
   :class="value ? 'van-cell--value':''" 
  title="所在行业" 
  :value="value || '请选择客户所在行业'" 
  is-link 
  @click="onClick" 
/>
```

**Describe the solution you'd like**
综上，希望添加Field组件对于van-field的点击事件

**What does the proposed API look like?**
```
<van-field
  @click-parent=“onClickParent”
/>
```

**Comment by chenjiahan** [comment]
2.0 版本已经支持 click 事件咯
