### ISSUE TITLE
滚动加载

### ISSUE THREAD

**Issue by GHUserZ** [youzan/vant#3527]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**

**Screenshots 截图**

**Environment 环境**

 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce 复现步骤**

请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by chenjiahan** [comment]
不规范的 issue
