### ISSUE TITLE
[Feature Request] NumberKeyboard 支持 v-model

### ISSUE THREAD

**Issue by Cheng007** [youzan/vant#3528]
**What problem does this feature solve?**
使用方便，不用每次都自己去处理相关事件回调，可以更好的和表单 model 进行交互

**Describe the solution you'd like**
自动响应 `input`，`delete` 事件

**What does the proposed API look like?**
添加 props: value 参数
使用方式如下：
`<van-number-keyboard v-model="model" />`

**Comment by chenjiahan** [comment]
想法不错，下个版本会支持

**Comment by chenjiahan** [comment]
已在 2.0.2 版本支持
