### ISSUE TITLE
vue vant插件中 轮播图组件在手机上有时不能手势滑动，安卓手机没有问题 iOS手机会时不时的能滑 不能划的情况出现！不知道是什么情况

### ISSUE THREAD

**Issue by cctvzqj008** [youzan/vant#3529]
vue vant插件中 轮播图组件在手机上有时不能手势滑动，安卓手机没有问题 iOS手机会时不时的能滑 不能划的情况出现！不知道是什么情况

**Comment by chenjiahan** [comment]
示例文档能复现吗？

**Comment by cctvzqj008** [comment]
<van-swipe :show-indicators="false" :loop="false" @change="onChange" :initial-swipe="current">
                <van-swipe-item v-for="(item,index) in fileList" :key="index" @click="clickimg(index)">
                    <div class="files_list">
                        < img :src="item.img" :alt="item.title">
                    </div>
                </van-swipe-item>
            </van-swipe>
用的就是文档里面的示例改的

**Comment by cctvzqj008** [comment]
<van-swipe :show-indicators="false" :loop="false" @change="onChange" :initial-swipe="current">
                <van-swipe-item v-for="(item,index) in fileList" :key="index" @click="clickimg(index)">
                    <div class="files_list">
                        < img :src="item.img" :alt="item.title">
                    </div>
                </van-swipe-item>
            </van-swipe>
用的就是示例的东西修改的

**Comment by chenjiahan** [comment]
我问的是示例文档喔，不是你修改后的代码
