### ISSUE TITLE
NavBar怎么获取左侧文案和右侧文案的单击事件？？？

### ISSUE THREAD

**Issue by luchuan163** [youzan/vant#353]
NavBar怎么获取左侧文案和右侧文案的单击事件？？？
NavBar怎么获取左侧文案和右侧文案的单击事件？？？

**Comment by chenjiahan** [comment]
@luchuan163 目前可以通过 clickLeft 和 clickRight 事件监听对应点击事件，文档会在后续补充。出于统一事件命名规范的考虑，我们会在下个版本中将事件名修改为 click-left 和 click-right，请知悉
