### ISSUE TITLE
WebStorm 出现 Unknown html tag 警告标识  

### ISSUE THREAD

**Issue by TY-LIU** [youzan/vant#3537]
**What problem does this feature solve?**
 ### WebStorm 出现 Unknown html tag 警告标识  ###
这个问题在webstorm中始终存在，并且组件没有智能提示，必须安装插件。
即使有了插件，使用组件会出现 “未知标签” 的警告，这让使用webstorm的玩家很难受，我必须写一句注释让webstorm忽略这个警告

![微信截图_20190617193930](https://user-images.githubusercontent.com/29595097/59601809-b9538c80-9137-11e9-9b57-842e80ceb156.png)

**Describe the solution you'd like**
希望可以像element-ui那样有智能提示(无需插件)，并且注册标签
![微信截图_20190617194335](https://user-images.githubusercontent.com/29595097/59602040-57475700-9138-11e9-98ad-adf824ce3002.png)

**Comment by ystarlongzi** [comment]
安装下插件，见 https://github.com/Rickykurt/VantPlugin

**Comment by coolkidxu** [comment]
![image](https://user-images.githubusercontent.com/74520733/117933982-bb7af180-b334-11eb-8c6e-d48026aabd21.png)
好多属性都不存在
