### ISSUE TITLE
页面Use Checkbox,CheckboxGroup组件后会使得顶部NavBar的fixed属性失效

### ISSUE THREAD

**Issue by gitEle** [youzan/vant#3539]
页面Use Checkbox,CheckboxGroup组件后会使得顶部NavBar的fixed属性失效,发现Vue.useCheckbox,CheckboxGroup后会添加一条样式

[class*=van-hairline] {
    position: relative;
}
覆盖了NavBar的样式
.van-tabbar--fixed {
    position: fixed;
    bottom: 0;
    left: 0;
}
![image](https://user-images.githubusercontent.com/21994548/59648233-f0b24f80-91b0-11e9-9266-6c48ed67c19c.png)

 - Device: win7
 - Browser: chome
 - Vant Version: 2.0.0

**Comment by chenjiahan** [comment]
你的样式引入顺序是怎样的呢，理论上不会发生覆盖的现象，最好能提供下复现方法

**Comment by gitEle** [comment]
main.js
`import {Button,Toast,Cell,CellGroup,Icon,Row,Col,Popup} from 'vant';
Vue.use(Button).use(Toast).use(Cell).use(CellGroup).use(Icon).use(Row).use(Col).use(Popup);
//表单组件
import {Field,Picker,Radio, RadioGroup ,SwitchCell} from 'vant';
Vue.use(Field).use(Picker).use(Radio).use(RadioGroup).use(SwitchCell);

//反馈组件
import { ActionSheet } from 'vant';
Vue.use(ActionSheet);
//展示组件
import { Collapse, CollapseItem ,List,Panel} from 'vant';
Vue.use(Collapse).use(CollapseItem).use(List).use(Panel);
//导航组件
import {NavBar,Tab, Tabs,Tabbar, TabbarItem} from 'vant';
Vue.use(NavBar).use(Tab).use(Tabs).use(Tabbar).use(TabbarItem);
//业务组件
import {Area,GoodsAction,GoodsActionIcon, GoodsActionButton,SubmitBar} from 'vant';
Vue.use(Area).use(GoodsAction).use(GoodsActionIcon).use(GoodsActionButton).use(SubmitBar);
//这儿必须要最后导入,我也不知道为啥,不然会有这个css [class*=van-hairline] 影响fixed的布局
import { Checkbox, CheckboxGroup} from 'vant';
Vue.use(Checkbox).use(CheckboxGroup);
`
我把 Checkbox,CheckboxGroup 这两个组件放在最后引入就没有覆盖样式了,当时如果放在其他组件前面引入就会出现这个问题

**Comment by chenjiahan** [comment]
我试了下没问题，建议检查下：
1. 是否使用了 `babel-plugin-import`
2. 是否有重复引入样式
