### ISSUE TITLE
商品sku规格里面价格计算怎么和后端给的数据相结合啊,

### ISSUE THREAD

**Issue by VioletDan** [youzan/vant#3541]
商品sku规格

商品sku规格里面价格计算怎么和后端给的数据相结合啊,

**What does the proposed API look like?**
拿到后端给的数据,不知道相应的价格如何计算

**Comment by chenjiahan** [comment]
不太清楚你的问题具体是什么，只要按照文档的数据格式传入，并监听对应的事件即可

**Comment by VioletDan** [comment]
我的意思是后台给的数据里每个规格都有价格.想知道,你们那边的价格是如何计算的,例如选了红色,XL 这个规格,价格是怎么计算出来的撒





------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 下午5:44
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "夏有乔木雅望天堂"<729374940@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] 商品sku规格里面价格计算怎么和后端给的数据相结合啊, (#3541)




不太清楚你的问题具体是什么，只要按照文档的数据格式传入，并监听对应的事件即可

**Comment by chenjiahan** [comment]
数据格式里不是有`price`字段嘛，计算就是根据选中的规格找到数据格式里对应的`price`值

**Comment by VioletDan** [comment]
好的,谢谢了,其实我就是想知道你们选择规格后计算价格的方法 或者思路,哈哈







------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 下午5:56
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "夏有乔木雅望天堂"<729374940@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] 商品sku规格里面价格计算怎么和后端给的数据相结合啊, (#3541)




数据格式里不是有price字段嘛，计算就是根据选中的规格找到数据格式里对应的price值

**Comment by chenjiahan** [comment]
看源码咯~

**Comment by VioletDan** [comment]
好的,谢谢,已经在看了





------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 晚上7:38
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "夏有乔木雅望天堂"<729374940@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] 商品sku规格里面价格计算怎么和后端给的数据相结合啊, (#3541)




看源码咯~
