### ISSUE TITLE
van-tabs ssr问题

### ISSUE THREAD

**Issue by wssll789** [youzan/vant#3543]
在使用van-tabs的时候不渲染内容 
如
`<van-tabs >
  <van-tab title="标签 1">内容 1</van-tab>
  <van-tab title="标签 2">内容 2</van-tab>
  <van-tab title="标签 3">内容 3</van-tab>
  <van-tab title="标签 4">内容 4</van-tab>
</van-tabs>`
或者
`<van-tabs>
  <van-tab v-for="index in 8" :title="'标签 ' + index">
    内容 {{ index }}
  </van-tab>
</van-tabs>`
以上代码在查看页面源代码view-source:时候都不能看到具体内容，如

`<div class="van-tabs__line"></div></div></div><div class="van-tabs__content"><div role="tabpanel" class="van-tab__pane" style="display:none;"><!----></div> <div role="tabpanel" class="van-tab__pane" style="display:none;"><!----></div> <div role="tabpanel" class="van-tab__pane" style="display:none;"><!----></div> <div role="tabpanel" class="van-tab__pane" style="display:none;"><!----></div></div></div>`

我使用的是nuxtjs
@chenjiahan

**Comment by chenjiahan** [comment]
没设置 active 吗？ 未选中的标签页默认是不渲染内容的，如果需要渲染，可以设置`lazy-render`为`false`

**Comment by wssll789** [comment]
通过lazy-render为false 已经解决了这个问题，谢谢

**Comment by powerlau** [comment]
我也遇到了这个问题，虽然通过设置lazy-render为false可以解决内容渲染，但是依然无法渲染出tab title的内容。

**Comment by lstrive-yn** [comment]
> 我也遇到了这个问题，虽然通过设置lazy-render为false可以解决内容渲染，但是依然无法渲染出tab title的内容。

遇到同样的问题

**Comment by lstrive-yn** [comment]
> 没设置 active 吗？ 未选中的标签页默认是不渲染内容的，如果需要渲染，可以设置`lazy-render`为`false`

这样可以解决内容渲染的问题，但是title就不渲染；请问如何解决，尝试了很多写法都没有效果

**Comment by lstrive-yn** [comment]
@chenjiahan 这样可以解决内容渲染的问题，但是title就不渲染；请问如何解决，尝试了很多写法都没有效果

**Comment by gengchen528** [comment]
> @chenjiahan 这样可以解决内容渲染的问题，但是title就不渲染；请问如何解决，尝试了很多写法都没有效果

同问这个问题，以前设置`lazy-render`成功过，但是升级最新版本后，静态网页内好像就渲染不出具体的title内容了

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5278

**Comment by ganshiqingyuan** [comment]
想知道还有哪些组件不支持服务端渲染，，省着用完发现有bug了。。。

**Comment by gdabs** [comment]
vue3.x的对应版出现的，现在有解决么

**Comment by vincenthou2016** [comment]
在app.vue套一层Suspense就可以了：
`<suspense>
            
            <template v-slot:default>
              <BasicComponent>
                <keep-alive>
                  <component :is="Component" :key="route.name"/>
                </keep-alive>
              </BasicComponent>
            </template>
            
            <template v-slot:fallback>加载中，请稍等。。。</template>
          </suspense>`
