### ISSUE TITLE
 Navbar在popup里 不能固定高度

### ISSUE THREAD

**Issue by 908023777** [youzan/vant#3544]
**Describe the bug 描述问题**

Navbar在popup里 不能固定高度

代码
<van-popup v-model="popupShow" position="right" style="width: 90%;height: 100%">
      <van-nav-bar title="标题" left-text="返回" :fixed="true" left-arrow/>
      <van-cell-group>
        <van-cell v-for="i in 100" :key="i" title="单元格" value="内容" label="描述信息"/>
      </van-cell-group>
    </van-popup>

**Screenshots 截图**
![image](https://user-images.githubusercontent.com/37042827/59658583-a8a62380-91d6-11e9-906b-6abcbc12b853.png)
![image](https://user-images.githubusercontent.com/37042827/59658641-d8552b80-91d6-11e9-8032-7966ddccba39.png)

**Environment 环境**

 - Device:  
 - Browser:  
 - Vant Version:  2.0.1

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3365

**Comment by 908023777** [comment]
> 参见 #3365

谢谢大佬,
