### ISSUE TITLE
Picker 选择器 能否动态添加 ‘列’

### ISSUE THREAD

**Issue by zhaoyuhang1033** [youzan/vant#3545]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**
我可能需要一个N级联动 并且根据我选择的内容渲染出更多的列
但现在colums 不是响应式的 他不会实时渲染 ‘列’

**Screenshots 截图**
![屏幕截图_2](https://user-images.githubusercontent.com/36781875/59661801-346f7e00-91de-11e9-8ef7-8b0b0c603d1b.png)
![屏幕截图_3](https://user-images.githubusercontent.com/36781875/59661804-35a0ab00-91de-11e9-8f09-285677f3f9a5.png)

**Environment 环境**

 - Device:  chrome
 - Browser:  google webview
 - Vant Version:  2.x

**Reproduce 复现步骤**
```
getLevelData(opt) {  // 这是一个获取下一级数据的函数
      return map(opt, item => ({
        id: item.id,
        text: item.label,
        disabled: item.isDisabled,
        children: item.children 
      }))
    },

changeEvent(picker, cur, index) {
      if (cur.children && cur[0].children.length) {  
        this.columns[1] = { values: this.getLevelData(cur[0].children) }
       // 我也尝试过 setcolumnValues 但也是没有效果
      }
      
    }
```
请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by zhaoyuhang1033** [comment]
补充： 在created() 中会渲染

**Comment by chenjiahan** [comment]
Picker 是支持动态渲染的，只是你的写法有问题，直接根据数据下标设置值是不会触发 Vue 的响应式更新的，你可以使用 `this columns.push` 或者 `this.columns = [...this.columns, options]`

**Comment by zhaoyuhang1033** [comment]
> Picker 是支持动态渲染的，只是你的写法有问题，直接根据数据下标设置值是不会触发 Vue 的响应式更新的，你可以使用 `this columns.push` 或者 `this.columns = [...this.columns, options]`

好的  谢谢
