### ISSUE TITLE
Radio 组件 自定义图标 官网 点击并不会切换图标

### ISSUE THREAD

**Issue by DaDaDaDaDaBocai** [youzan/vant#3546]
**Describe the bug 描述问题**
Radio 组件 自定义图标 点击并不会切换图标

**Screenshots 截图**
官网就是这样情况

**Comment by chenjiahan** [comment]
因为示例里只放了一个 Radio，只有多个 Radio 的情况下才会切换，不是 bug

**Comment by myron2016518** [comment]
> 因为示例里只放了一个 Radio，只有多个 Radio 的情况下才会切换，不是 bug

https://vant-contrib.gitee.io/vant/v3/#/zh-CN/radio#zi-ding-yi-tu-biao
这里 自定义图标  用你们的官方代码放进去，点击也不能切换，试过几次 
<img class="img-icon" :src="props.checked ? activeIcon : inactiveIcon" />
props.checked ? activeIcon : inactiveIcon 这里的判断没起作用
用的版本是"vant": "^3.2.6",
