### ISSUE TITLE
vant dialog 通过组件调用时，点击确认按钮默认给关闭了，设置了confirm回调函数也没有用

### ISSUE THREAD

**Issue by miuqiang** [youzan/vant#3547]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**

**Screenshots 截图**
![image](https://user-images.githubusercontent.com/19277011/59673804-83c0a900-91f4-11e9-8a1a-f30535345043.png)
![image](https://user-images.githubusercontent.com/19277011/59673818-891df380-91f4-11e9-859c-88201000e56f.png)
![image](https://user-images.githubusercontent.com/19277011/59673831-8fac6b00-91f4-11e9-8a7b-7d87d49a1c56.png)

**Environment 环境**

 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce 复现步骤**

请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by chenjiahan** [comment]
点击按钮是会默认关闭的，可以通过`before-close`属性阻止关闭
