### ISSUE TITLE
mpvue引入失败问题

### ISSUE THREAD

**Issue by victorliuboom** [youzan/vant#3549]
![image](https://user-images.githubusercontent.com/13329831/59729436-23bc1800-9271-11e9-84a5-dac7b8715720.png)
引入button可以这样引入，但是这里面完全没有dropdown啊 我怎么用
![image](https://user-images.githubusercontent.com/13329831/59729467-45b59a80-9271-11e9-9be8-2a0a68b33188.png)

**Comment by victorliuboom** [comment]
我服啦 别的都能引入 
![image](https://user-images.githubusercontent.com/13329831/59729570-94fbcb00-9271-11e9-8d0d-ef06b3a68edc.png)
唯独

**Comment by chenjiahan** [comment]
小程序版本目前没有 DropdownMenu 组件，你可能看错文档了
