### ISSUE TITLE
图片上传组件是不管接口返回数据，直接显示图片吗

### ISSUE THREAD

**Issue by grace618** [youzan/vant#3552]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.
接口请求没有完成，图片上传组件就先显示图片
**Describe the solution you'd like**
在一个表单提交里面要上传图片，会不会图片接口还没有返回数据，让用户误以为图片已经上传好了，就直接点提交了
**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
可以配合 Toast.loading 使用，给用户一个加载提示

**Comment by grace618** [comment]
> 可以配合 Toast.loading 使用，给用户一个加载提示

这个可以，thank you ,
