### ISSUE TITLE
van-pull-refresh 里面元素无法响应点击事件

### ISSUE THREAD

**Issue by dayexu** [youzan/vant#3553]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
![(GXI)E)OY3FQR2(JKKNV (8](https://user-images.githubusercontent.com/9266453/59734820-84555000-9285-11e9-8aa2-b5689c71a7a7.png)

**Describe the solution you'd like**
如图，我想在van-pull-refresh里面的子元素上添加click事件，但实际情况是无法响应这个事件

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by dayexu** [comment]
![2](https://user-images.githubusercontent.com/9266453/59734874-b4045800-9285-11e9-8dc7-5f7ecfb4b1fb.png)

**Comment by chenjiahan** [comment]
试了下没复现此问题，麻烦提供下复现链接
