### ISSUE TITLE
按需引入无效

### ISSUE THREAD

**Issue by yexiaodong** [youzan/vant#3555]
**Describe the bug 描述问题**
按需引入无效

**Screenshots 截图**
![image](https://user-images.githubusercontent.com/13914749/59736170-1449c880-928b-11e9-808b-c908f1f66db3.png)

**Environment 环境**

 - Device: PC
 - Browser: chrome
 - Vant Version: 2.0.1

**Reproduce 复现步骤**

![image](https://user-images.githubusercontent.com/13914749/59736203-37747800-928b-11e9-8fb3-af3a5eaf1060.png)

![image](https://user-images.githubusercontent.com/13914749/59736264-7dc9d700-928b-11e9-880c-9a4dfac96bd8.png)

**Comment by chenjiahan** [comment]
请按照文档进行注册组件
