### ISSUE TITLE
sku图片预览错误

### ISSUE THREAD

**Issue by zhangfei8080** [youzan/vant#3559]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**
当商品规格只有1个时,预览规格缩略图js报错

**Screenshots 截图**

**错误内容:**
TypeError: Cannot read property 'findIndex' of undefined
at a.onPreviewImage (vant.min.js:7)
at He (vue.min.js:6)
at wn.e.$emit (vue.min.js:6)
at click (vant.min.js:7)
at He (vue.min.js:6)
at HTMLDivElement.n (vue.min.js:6)
at HTMLDivElement.Yr.o._wrapper (vue.min.js:6)

**Environment 环境**

 - Device: 
 - Browser: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36
 - Vant Version: 2.0.1

**Reproduce 复现步骤**
商品数据:
{
        "id": 3,
        "title": "23",
        "picture": "http:\/\/api.aaa.com\/upload\/pic\/a\/a\/0\/aa01205ff0ab07c0c4752b27f6053c99.gif",
        "summary": "斯蒂芬是否玩儿玩儿人威尔威群二我发斯蒂芬",
        "thumb": ["http:\/\/api.aaa.com\/upload\/pic\/a\/f\/0\/af0326eaedd8a2ef7c6b219cdf3d5fa6.gif"],
        "content": "<p>斯蒂芬是否玩儿玩儿人威尔威群二我发斯蒂芬<\/p>",
        "sell": 10,
        "sku": {
            "tree": [{
                "k": "度数",
                "k_s": "s0",
                "v": [{
                    "id": 476,
                    "s_id": 167,
                    "name": "46",
                    "imgUrl": "http:\/\/api.aaa.com\/img\/def.png",
                    "sid": 167
                }]
            }],
            "list": [{
                "id": 167,
                "price": 1000,
                "cost_pice": 1000,
                "stock_num": 10,
                "s0": 476
            }],
            "price": "10.00",
            "stock_num": 10,
            "none_sku": false,
            "hide_stock": false
        }
    }
请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by zhangfei8080** [comment]
错误内容:
TypeError: Cannot read property 'findIndex' of undefined
    at a.onPreviewImage (vant.min.js:7)
    at He (vue.min.js:6)
    at wn.e.$emit (vue.min.js:6)
    at click (vant.min.js:7)
    at He (vue.min.js:6)
    at HTMLDivElement.n (vue.min.js:6)
    at HTMLDivElement.Yr.o._wrapper (vue.min.js:6)

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 2.0.2 版本修复
