### ISSUE TITLE
NoticeBar 内容改变后不滚动

### ISSUE THREAD

**Issue by zhaoxianbo** [youzan/vant#3561]
**Describe the bug 描述问题**
初始内容没有溢出不滚动，改变内容后溢出不滚动，希望内容改变后，根据溢出状态重新是否滚动状态，同理，初始溢出滚动，改变成没有异常时还是在滚动。

还有希望加个属性，可以让滚动内容滚完后，在间隔一段距离后接着开头滚动，而不是在全部滚完后出现很长一段空白。

**Screenshots 截图**

**Environment 环境**

 - Device: windows 7
 - Browser: Google Chrome 75.0.3770.90
 - Vant Version:  v1.6.23

**Reproduce 复现步骤**
https://jsfiddle.net/cw4svgfr/

**Comment by chenjiahan** [comment]
Vue 里面没法监听子元素的变化，建议使用 text 属性。

第二个功能会评估下

**Comment by chenjiahan** [comment]
第二点暂时不计划支持
