### ISSUE TITLE
upload组件的before-read不支持promise 模式

### ISSUE THREAD

**Issue by AfterThreeYears** [youzan/vant#3562]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
upload组件的before-read不支持promise 模式，在异步校验情况下无法使用，例如获取图片宽高

**Describe the solution you'd like**
支持promise模式

**What does the proposed API look like?**
期望类似antd的beforeUpload
https://ant.design/components/upload-cn/

**Comment by AfterThreeYears** [comment]
请问是有计划什么时候支持吗

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 2.0.2 版本支持
