### ISSUE TITLE
slider设置最大值和最小值问题

### ISSUE THREAD

**Issue by hs151991** [youzan/vant#3563]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**
slider滑块，设置最大值和最小值区间希望不限于0-100之间，可以设置由用户自己设置好值后然后slider根据值来自行判断显示。不要按着百分比来显示了，就像ele或者ivew的滑块效果一样，谢谢啦

**Screenshots 截图**

**Environment 环境**

 - Device: 
 - Browser: 
 - Vant Version: 

**Reproduce 复现步骤**

请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by chenjiahan** [comment]
确实是这样更合理，下个版本会优化下

**Comment by chenjiahan** [comment]
已在 2.0.2 版本支持
