### ISSUE TITLE
建议van-cell 支持 value 居左

### ISSUE THREAD

**Issue by Lettbee** [youzan/vant#3568]
在很多地方 需要用到 cell 内容居左对齐，
目前我是 重写样式 实现

希望官方可以更新一下。。

参考下面使用
`<van-cell title="订单编号" :value="value" align="left" title-width="74" />`
align=left 使内容居左
title-width  titile 宽度

**Comment by Lettbee** [comment]
![Image text](http://snappyimages.nextwavesrl.netdna-cdn.com/img/771413447164bb43d78282c5525c029c.png)

**Comment by chenjiahan** [comment]
`value-class`属性也可以实现的

**Comment by Lettbee** [comment]
> `value-class`属性也可以实现的

 用value-class  就需要title-class ，两个样式都需要重置一下
 
我目前是 这样来实现的，就比较简洁 
`
<van-cell title="订单编号" :value="value" align="left"/>
`

CSS
`
[align='left'] .van-cell__title {
    width: 70px;
    flex: none;
    color: #88898a;
}
[align='left'] .van-cell__value {
    text-align: left;
    color: #555657;
}
`

**Comment by chenjiahan** [comment]
你的样式里还包含了 color、width 等设置，这些都可以通过 `title-class`和`value-class`来实现，`align`的必要性不是很强

**Comment by CreazyBlade** [comment]
van-cell的value-class由BUG，不能使用外联样式，只能使用本当前页面定义的样式
