### ISSUE TITLE
SwipeCell 滑动单元格问题

### ISSUE THREAD

**Issue by metokk** [youzan/vant#3571]
iPhone7在使用此组件时右侧添加的两个button中间会出现缝隙，需要margin:0解决此问题，望修复，嘻嘻

**Comment by chenjiahan** [comment]
我试了没这个问题，能提供复现链接么

**Comment by metokk** [comment]
https://metokk.github.io/demoa/

**Comment by chenjiahan** [comment]
已复现，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.0.2 版本修复
