### ISSUE TITLE
页面中所以的checkBox怎么各自区分各自的change事件?

### ISSUE THREAD

**Issue by VioletDan** [youzan/vant#3576]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.
页面中所以的checkBox怎么各自区分各自的change事件?

页面中所以的checkBox怎么各自区分各自的change事件?

页面中所以的checkBox怎么各自区分各自的change事件?

**Comment by chenjiahan** [comment]
传入不同的函数即可

```html
<van-checkbox @change="onChange1">复选框 1</van-checkbox>

<van-checkbox @change="onChange2">复选框 2</van-checkbox>
```

```js
export default {
  methods: {
    onChange1() {},

    onChange2() {}
  }
}
```

**Comment by VioletDan** [comment]
但是,他会同时执行唉,我是购物车列表做全选和反选的时候residentClick是入驻商前面绑定的 cartsClick是每个入驻商下面的商品列表上绑的,






------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 晚上8:14
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "夏有乔木雅望天堂"<729374940@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] 页面中所以的checkBox怎么各自区分各自的change事件? (#3576)




传入不同的函数即可
 <van-checkbox @change="onChange1">复选框 1</van-checkbox> <van-checkbox @change="onChange2">复选框 2</van-checkbox>
 export default {   methods: {     onChange1() {},     onChange2() {}   } }

**Comment by chenjiahan** [comment]
不清楚你的业务场景，如果你要做区分，可以加参数解决

```html
<van-checkbox @change="onChange1('aaa')">复选框 1</van-checkbox>

<van-checkbox @change="onChange2('bbb')">复选框 2</van-checkbox>
```
```js
export default {
  methods: {
    onChange1(param) {},

    onChange2(param) {}
  }
}
```

**Comment by VioletDan** [comment]
好的,谢谢





------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 晚上8:22
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "夏有乔木雅望天堂"<729374940@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] 页面中所以的checkBox怎么各自区分各自的change事件? (#3576)




不清楚你的业务场景，如果你要做区分，可以加参数解决
 <van-checkbox @change="onChange1('aaa')">复选框 1</van-checkbox> <van-checkbox @change="onChange2('bbb')">复选框 2</van-checkbox>
 export default {   methods: {     onChange1(param) {},     onChange2(param) {}   } }
