### ISSUE TITLE
van-coupon-list优惠券的tab只有两个（可用和不可用），建议数量做成可控的tab

### ISSUE THREAD

**Issue by WuYiZhan** [youzan/vant#3579]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
暂时没计划支持

**Comment by WuYiZhan** [comment]
有一些优惠券的tab是三个的（未使用、使用过的，过期的）列表的内容都是一样的优惠券格式，tab做成可控的不难实现，规定下tab的传入格式，tab有传入就用传入的对象，没传入就默认现在的

**Comment by chenjiahan** [comment]
业务组件暂时没计划投入去做各种定制需求，sorry
