### ISSUE TITLE
希望把购物车的业务组件和订单结算的业务组件弄上就完美了

### ISSUE THREAD

**Issue by xudagehao** [youzan/vant#358]
希望把购物车的业务组件和订单结算的业务组件弄上就完美了

**Comment by chenjiahan** [comment]
@xudagehao 购物车可以参考 (Vant 示例)[https://www.youzanyun.com/zanui/vant#/zh-CN/component/demo] 订单结算不知道你具体指的是哪块

**Comment by xudagehao** [comment]
订单结算就是订单的详细信息， 有收货人、购买商品的列表、优惠券的选择、对支付金额的计算等。不过貌似可以用已有的组件来弄。如果有个实例的话，可以方便很多

**Comment by chenjiahan** [comment]
@xudagehao  后续会考虑增加对应示例
