### ISSUE TITLE
ActionSheet 上拉菜单在CDN载入情况下无法调用

### ISSUE THREAD

**Issue by timosss** [youzan/vant#3580]
ActionSheet 上拉菜单在CDN载入情况下无法调用

错误截图
http://i2.tiimg.com/596081/b7fe627705af9b09.png

**Comment by chenjiahan** [comment]
请提供复现链接

**Comment by WuYiZhan** [comment]
注意CDN引入的版本，2.0用van-action-sheet ，1.x版本用van-actionsheet
