### ISSUE TITLE
van-coupon-list优惠券列表项（每张优惠券）建议得提供一个按钮（立即使用）用方便跳转

### ISSUE THREAD

**Issue by WuYiZhan** [youzan/vant#3581]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**What problem does this feature solve?**
A clear description of what the problem is.

**Describe the solution you'd like**

**What does the proposed API look like?**
Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.

**Comment by chenjiahan** [comment]
业务组件暂时没计划投入去做各种定制需求，sorry
