### ISSUE TITLE
[Bug Report] Popup 和 ActionSheet 组件在 IOS 键盘出来后无法滚动

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#3587]
**Describe the bug 描述问题**
当 body 和 Popup（或 ActionSheet）组件都有滚动条时，Popup 里面有个 textarea 标签，我点击 textarea，输入键盘出来后，我在 Popup 内向下拉，想滚动看上面的内容，但是拉了没效果，滚动不了~

**Screenshots 截图**
![image](https://user-images.githubusercontent.com/16074662/59903164-d7b8d100-9432-11e9-8029-679829b19d19.png)
![image](https://user-images.githubusercontent.com/16074662/59903178-dedfdf00-9432-11e9-80b0-e47956672420.png)

**Environment 环境**

 - Device: 苹果7 和 苹果7P，IOS 11 和 IOS 13
 - Browser: 微信
 - Vant Version: 2.0.0

**codesandbox**
 https://codesandbox.io/s/vant-issue-moban-5dgti?fontsize=14

**Comment by chenjiahan** [comment]
请提供一下复现的 codesandbox 链接

**Comment by 1014156094** [comment]
> 请提供一下复现的 codesandbox 链接

codesandbox 链接更新进去了~

**Comment by chenjiahan** [comment]
我用 XR 试了下没问题喔，注意在 iOS 里要等背景的弹性滚动停止后，才能在前景里滑动

**Comment by 1014156094** [comment]
> 我用 XR 试了下没问题喔，注意在 iOS 里要等背景的弹性滚动停止后，才能在前景里滑动

必须要点击输入框让键盘弹出来后再滚动才能复现，不然你试试苹果7P。。

**Comment by chenjiahan** [comment]
这个是系统控制的，是系统在键盘弹出时把画面向上移动了一定位置，不是组件里的逻辑，你可以调整下弹窗高度来避免

**Comment by 1014156094** [comment]
> 这个是系统控制的，是系统在键盘弹出时把画面向上移动了一定位置，不是组件里的逻辑，你可以调整下弹窗高度来避免

我也觉得是系统问题，你看下这个复现视频确认下我们说的是不是同个问题，链接：https://pan.baidu.com/s/1m--RcfcrqgKYZS4nyatSBw 密码：fomh

**Comment by chenjiahan** [comment]
是同个问题，解决方案就是我上面说的，调整弹窗高度

**Comment by 1014156094** [comment]
> 是同个问题，解决方案就是我上面说的，调整弹窗高度

嗯嗯，只能调整弹窗高度了，试了没问题，谢谢~

**Comment by chenjiahan** [comment]
客气哈
