### ISSUE TITLE
toast显示问题

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#3588]
this.$toast.success({text: res.data.msg, icon: 'like-o'});
没有成功那样的方形框，也没有icon，和普通的toast样式一样
![image](https://user-images.githubusercontent.com/42930030/59903895-c1ac1000-9434-11e9-94f1-fa7b8a2c6856.png)

**Comment by chenjiahan** [comment]
请确认你升级到了最新版本

**Comment by cangyu1993** [comment]
![image](https://user-images.githubusercontent.com/42930030/59907840-962e2300-943e-11e9-9a80-bfa809e25570.png)
还是那个问题，已经是2.02版本

**Comment by chenjiahan** [comment]
我试了下没问题，能提供复现链接么

**Comment by cangyu1993** [comment]
https://yzgs.ewangke.com





------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午4:22
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "浅"<1765244720@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] toast显示问题 (#3588)




我试了下没问题，能提供复现链接么

**Comment by cangyu1993** [comment]
------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午4:22
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "浅"<1765244720@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] toast显示问题 (#3588)




我试了下没问题，能提供复现链接么

**Comment by cangyu1993** [comment]
ok,解决了，我重新安装了vant然后重启了vue项目，感谢关注





------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午4:22
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "浅"<1765244720@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] toast显示问题 (#3588)




我试了下没问题，能提供复现链接么
