### ISSUE TITLE
全局注册的组件在单文件中不识别

### ISSUE THREAD

**Issue by yajore** [youzan/vant#359]
**What is the current behavior?**
我在全局注册了布局组件
```javascript
import {Lazyload, Row, Col} from 'vant';
Vue.use(Row.name, Row);
Vue.use(Col.name, Col);
```
但是在vue中直接使用，但不识别
Unknown custom element: <van-col> - did you register the component correctly? For recursive components
像这种项目使用频率很高的组件，我一般会在全局注册一次，其他页面就不引用了，
问题出哪儿了
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
Vue.use 是注册插件用的，注册组件请使用 Vue.component

**Comment by yurizhang** [comment]
现在更新到新版本可以这样使用了。
