### ISSUE TITLE
使用 vant 中的IndexBar,IndexAnchor报错

### ISSUE THREAD

**Issue by 731ghyurt** [youzan/vant#3590]
vue 项目中是用 vant 报错，（vue版本为2.9.6，vant版本：1.4.5）具体使用如下：
import { IndexBar,IndexAnchor} from "vant";
components: {
    [IndexBar.name]:IndexBar,
    [IndexAnchor.name]:IndexAnchor
  }

运行项目报错如下：
[HMR] bundle has 4 errors
client.js?7955:189 ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/tabbar-home-xiaolu.vueModule not found: Error: Can't resolve 'vant/lib/index-anchor' in 'D:\gongsi\H5\jinzhishenghuofront-master\jinzhishenghuofront-master\src\views\home' @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/tabbar-home-xiaolu.vue 3:0-50 5:0-49 @ ./src/views/home/tabbar-home-xiaolu.vue @ ./src/vue/router/user.js @ ./src/vue/router/index.js @ ./src/main.js @ multi ./build/dev-client ./src/main.js./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/tabbar-home-xiaolu.vueModule not found: Error: Can't resolve 'vant/lib/index-anchor/style' in 'D:\gongsi\H5\jinzhishenghuofront-master\jinzhishenghuofront-master\src\views\home' @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/tabbar-home-xiaolu.vue 2:0-37 4:0-37 @ ./src/views/home/tabbar-home-xiaolu.vue @ ./src/vue/router/user.js @ ./src/vue/router/index.js @ ./src/main.js @ multi ./build/dev-client ./src/main.js./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/tabbar-home-xiaolu.vueModule not found: Error: Can't resolve 'vant/lib/index-bar' in 'D:\gongsi\H5\jinzhishenghuofront-master\jinzhishenghuofront-master\src\views\home' @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/tabbar-home-xiaolu.vue 7:0-44 9:0-43 @ ./src/views/home/tabbar-home-xiaolu.vue @ ./src/vue/router/user.js @ ./src/vue/router/index.js @ ./src/main.js @ multi ./build/dev-client ./src/main.js./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/tabbar-home-xiaolu.vueModule not found: Error: Can't resolve 'vant/lib/index-bar/style' in 'D:\gongsi\H5\jinzhishenghuofront-master\jinzhishenghuofront-master\src\views\home' @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/tabbar-home-xiaolu.vue 6:0-34 8:0-34 @ ./src/views/home/tabbar-home-xiaolu.vue @ ./src/vue/router/user.js @ ./src/vue/router/index.js @ ./src/main.js @ multi ./build/dev-client ./src/main.js

**Comment by chenjiahan** [comment]
IndexBar 在 2.0 版本开始支持，请注意文档版本
