### ISSUE TITLE
[Feature Request] ActionSheet组件可以给选中的action设置选中样式吗？

### ISSUE THREAD

**Issue by 941477276** [youzan/vant#3595]
### 这个功能解决了什么问题
简单的单选项可以设置选中样式

### 描述您想要的解决方案
目前ActionSheet组件中action选中后没有选中样式，也没有类似active这样的class，并且也没有办法设置选中样式，除了使用slot自定义action内容

### 建议的API是什么样的
希望可以有选中样式，可以自定义选中后的效果，最好是可以传递slot

**Comment by chenjiahan** [comment]
具体是什么样的效果呢？ ActionSheet 里的选项类似于按钮，只需要一个点击时的高亮效果，不会有持续选中的状态

**Comment by 941477276** [comment]
有时候我们会把ActionSheet当单选按钮来使用，单选的情况就需要有一个高亮样式，如果ActionSheet组件能有默认的选中高亮样式就更好了，最好可以使用插槽自定义选中后的图标。
就如DrowdownMenu中的选中高亮一样

![image](https://user-images.githubusercontent.com/20528541/59961221-83335580-9507-11e9-8b72-114f78bad7d8.png)

**Comment by chenjiahan** [comment]
这个用法是错误的，不符合 ActionSheet 的本意。

你如果要做单选的效果，最好是基于 Popup 和 Checkbox 完成
