### ISSUE TITLE
[Bug Report] list组件筛选数据

### ISSUE THREAD

**Issue by qq2499932100** [youzan/vant#3602]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.0.2

### Vue版本
2.6.10

### 重现链接
<a href="http://test.authj.com/app/index.php?i=2&c=entry&id=1&do=company&m=yc_youliao" target="_blank">http://test.authj.com/app/index.php?i=2&c=entry&id=1&do=company&m=yc_youliao</a>

### 描述问题
点击分类筛选，当选择全部时有滚动条，选择其他选项进行数据替换，这时候调用check检测失效，当不存在滚动条时，check检测有效

**Comment by qq2499932100** [comment]
如果我在切换数据的时候加入 window.scrollTo(0, 10); 这个问题将会得到解决，但是这会导致每次有滚动条切换的时候页面都会进行滚动一下再回到顶部

**Comment by chenjiahan** [comment]
你是在什么时机调用 check 的呢，需要在渲染完成后调用

**Comment by qq2499932100** [comment]
> 你是在什么时机调用check的呢，需要在渲染完成后调用

我是先将data清空，然后调用check，原意是想使用组件触发load事件，触发后发出请求。如果在渲染后调用，本身的问题并不会解决，而且如果check成功还会触发两次load

**Comment by chenjiahan** [comment]
data 清空后，要在 nextTick 回调里调用 check，以确保渲染完成
