### ISSUE TITLE
tabs和list一起用的时候，切换tab 数据请求两遍

### ISSUE THREAD

**Issue by AlsonYoung** [youzan/vant#3609]
getsaleListData() {
            // 异步更新数据
            setTimeout(() => {          
                let data = {
                    sid:1136,
                    currentPage:this.currentPage++,
                    pageSize:this.pageSize
                }
                saleList(data).then((res)=>{
                    console.log('出售列表：', res)
                    this.saleData = this.saleData.concat(res.result);
                    // 加载状态结束
                    this.loading = false;
                     // 数据全部加载完成
                    if (res.result.length<4) {
                    this.finished = true;
                    }
                })              
            }, 500);
        },

**Comment by chenjiahan** [comment]
不规范的 issue
