### ISSUE TITLE
GoodsAction商品导航组件，在import之后，其中GoodsActionIcon和GoodsActionButton这两个，Idea编辑器提示无法解析，让我验证es6的导入，export not found in vant，怎么解决，GoodsAction是可以正常使用的

### ISSUE THREAD

**Issue by Twndlt** [youzan/vant#3613]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by Twndlt** [comment]
npm i vant@2.0.0-beta.0 -S,我看了下版本发布公告，好像是之前版本的问题，更新到2.0的版本没问题了

**Comment by chenjiahan** [comment]
好的
