### ISSUE TITLE
[Bug Report] picker修改columns,同时为default-index重新赋值,没有重新渲染

### ISSUE THREAD

**Issue by wxfjamdc** [youzan/vant#3614]
### 设备 / 浏览器
Chrome

### Vant 版本
2.0.2

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vue-template-i5mtf" target="_blank">https://codesandbox.io/s/vue-template-i5mtf</a>

### 描述问题
```
<template>
  <div id="app">
    <van-picker :columns="popupColumn" show-toolbar :default-index="popupIndex"></van-picker>
    <van-button type="default" @click="switchBtn">切换列表</van-button>
  </div>
</template>

<script>
export default {
  name: "App",
  methods: {
    switchBtn() {
      console.log("switch");
      this.popupColumn = [4, 5, 6];
      this.popupIndex = 1;
    }
  },
  data() {
    return {
      popupColumn: [1, 2, 3],
      popupIndex: 1
    };
  }
};
</script>

```
修改columns后,default-index没有重新渲染

**Comment by wxfjamdc** [comment]
找到一个解决方法
`
      this.popupIndex = 0;
      this.$nextTick(() => {
        console.log("nextTick");
        this.popupIndex = 1;
      });
`

**Comment by chenjiahan** [comment]
上面的做法是可以的，也可以用 picker.setIndex 方法
