### ISSUE TITLE
tabs line的样式设置可以修改一下

### ISSUE THREAD

**Issue by NoahSun** [youzan/vant#3616]
https://github.com/youzan/vant/blob/edad95bc84919450f29df7704ffd207dec04d484/packages/tabs/index.js#L252

可以添加一个line-border-radius属性来设置

**Comment by chenjiahan** [comment]
太细节了，没必要

**Comment by NoahSun** [comment]
我需要把height设高一点，然后那个圆角就越明显了- -！

**Comment by NoahSun** [comment]
算了，不多说了。
