### ISSUE TITLE
picker 点击会跳到最后一项

### ISSUE THREAD

**Issue by transtone** [youzan/vant#362]
van-picker 组件中，如果点击选中的项，会跳到最末一项。

**Comment by chenjiahan** [comment]
@transtone 没能复现你的问题，能否详细描述一下出现的场景或系统？

**Comment by transtone** [comment]
直接用微信打开 https://www.youzanyun.com/zanui/vant#/zh-CN/component/picker 页面，点击选项三五下就会出现这个问题。

**Comment by chenjiahan** [comment]
@transtone 请问你使用的手机型号是？

**Comment by transtone** [comment]
在华为P9和谷歌pixel plus上均发现此问题。点击选中项的边缘，多点几次就好。

**Comment by chenjiahan** [comment]
@transtone 好的，我们会在近期修复此问题~

**Comment by chenjiahan** [comment]
已在 0.11.6 中修复
