### ISSUE TITLE
uploader上传图片capture=‘camera‘在安卓机下无效不能调摄像头，IOS下可以

### ISSUE THREAD

**Issue by WuYiZhan** [youzan/vant#3622]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
这个是 input 原生属性，系统不支持的话就不会生效

**Comment by WuYiZhan** [comment]
安卓系统虽然不支持这个属性，但作为uploader组件也得支持安卓的摄像头调用吧，还是得做一下兼容

**Comment by chenjiahan** [comment]
你需要达到什么样的兼容效果呢，我试了华为和三星都是支持的

**Comment by WuYiZhan** [comment]
<van-uploader v-model="fileList" preview-size="160px" :max-count="1" :after-read="afterReadFile" upload-text="拍照" capture="camera" accept="image/png,image/jpeg"></van-uploader>

在安卓下是打开相册，不是打开摄像头，在IOS下可以

**Comment by chenjiahan** [comment]
具体机型不能提供下么

**Comment by WuYiZhan** [comment]
魅族M3 note
还有朋友反映华为的也不行

**Comment by WuYiZhan** [comment]
解决了，原来是accept="image/png,image/jpeg"的问题，设置成accept="image/*"就没有问题了

**Comment by chenjiahan** [comment]
原来如此，解决了就好

**Comment by yexiaodong** [comment]
设置accept="video/*,image/*"就不行了，想同时支持图片、视频的上传，而且可以调用摄像头应该怎样写？

**Comment by Angle-bo** [comment]
有没有支持拍视频上传和预览的组件呀。。

**Comment by selina0628** [comment]
<van-uploader capture="camcorder" accept="video/*" >
capture="camcorder" accept="video/*" 这两个属性可以友好的解决安卓手机无法调起摄像头的问题。且ios也兼容通用。

**Comment by yiyezhiqiugithub** [comment]
ios支持，华为支持，小米不支持，为什么？
![image](https://user-images.githubusercontent.com/33708346/123384175-aa293400-d5c6-11eb-9ada-0c544ae7da4f.png)

**Comment by hWwXx** [comment]
> 

我加了这几个参数，但是安卓端，用cordova打包后调不了摄像头

**Comment by hWwXx** [comment]
> capture="camcorder/*" 这个属性可以调友好的解决安卓手机无法启动摄像头的问题。并且ios也接受两个通用手机。


我加了这几个参数，但是安卓端，用cordova打包后调不了摄像头

**Comment by lsyforget** [comment]
> > capture="camcorder/*" 这个属性可以调友好的解决安卓手机无法启动摄像头的问题。并且ios也接受两个通用手机。
> 
> 我加了这几个参数，但是安卓端，用cordova打包后调不了摄像头

哥们这个问题解决了吗，我的也是

**Comment by gaorui321** [comment]
解决了 谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 上午10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant] uploader上传图片capture=‘camera‘在安卓机下无效不能调摄像头，IOS下可以 (#3622)





   
capture="camcorder/*" 这个属性可以调友好的解决安卓手机无法启动摄像头的问题。并且ios也接受两个通用手机。
  
我加了这几个参数，但是安卓端，用cordova打包后调不了摄像头
  
哥们这个问题解决了吗，我的也是

**Comment by lsyforget** [comment]
> 解决了 谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "youzan/vant" ***@***.***&gt;; 发送时间:&nbsp;2022年10月10日(星期一) 上午10:23 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [youzan/vant] uploader上传图片capture=‘camera‘在安卓机下无效不能调摄像头，IOS下可以 (#3622) capture="camcorder/*" 这个属性可以调友好的解决安卓手机无法启动摄像头的问题。并且ios也接受两个通用手机。 我加了这几个参数，但是安卓端，用cordova打包后调不了摄像头 哥们这个问题解决了吗，我的也是 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

能请教一下吗，我跟你一样也是cordova打包后安卓调用不了摄像头

**Comment by lsyforget** [comment]
哥们能加个vx吗，请教一下这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant] uploader上传图片capture=‘camera‘在安卓机下无效不能调摄像头，IOS下可以 (#3622)





 解决了 谢谢 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年10月10日(星期一) 上午10:23 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [youzan/vant] uploader上传图片capture=‘camera‘在安卓机下无效不能调摄像头，IOS下可以 (#3622) 
 
 
 
 
 
     
 capture="camcorder/*" 这个属性可以调友好的解决安卓手机无法启动摄像头的问题。并且ios也接受两个通用手机。 
    
 我加了这几个参数，但是安卓端，用cordova打包后调不了摄像头 
    
 哥们这个问题解决了吗，我的也是

**Comment by gaorui321** [comment]
capture="camera"

给组件加上 这个属性 就可以直接调起摄像头昂，如果不加 默认会让你选择 照片库或者拍照上传，我目前项目上线了 也没有遇到安卓手机不能唤起摄像头的问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant] uploader上传图片capture=‘camera‘在安卓机下无效不能调摄像头，IOS下可以 (#3622)





  
解决了 谢谢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "youzan/vant" @.&gt;; 发送时间:&nbsp;2022年10月10日(星期一) 上午10:23 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [youzan/vant] uploader上传图片capture=‘camera‘在安卓机下无效不能调摄像头，IOS下可以 (#3622) capture="camcorder/" 这个属性可以调友好的解决安卓手机无法启动摄像头的问题。并且ios也接受两个通用手机。 我加了这几个参数，但是安卓端，用cordova打包后调不了摄像头 哥们这个问题解决了吗，我的也是 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.**&gt;
  
能请教一下吗，我跟你一样也是cordova打包后安卓调用不了摄像头

**Comment by weizhuanhua** [comment]
android的WebView里面加上capture="camera"还不生效的话 那就要看WebView有没有做限制操作 我遇到的不生效 找安卓开发看的 让他们改下逻辑就好了

**Comment by liuning66** [comment]
> 设置accept="video/_,image/_"就不行了，想同时支持图片、视频的上传，而且可以调用摄像头应该怎样写？

兄弟问下，这个问题解决了么？

**Comment by wenjie6687305** [comment]
<van-uploader capture="camera" accept="image/*" class="photodel"  v-model="fileList" :max-count="10" multiple
                  :before-delete="upLoaderFunDelete">
![image](https://github.com/youzan/vant/assets/101970262/7f88e61f-0014-431d-9a07-937f4e65ed8c)
使用 uploader上传方法时，安卓手机正常调用，苹果手机无法调用的情况， ，vant upload调起的是浏览器层级相机，不是系统级相机，请问下在不改变组件的情况下,还有什么解决方案呢

**Comment by summer123123123** [comment]
> ![image](https://user-images.githubusercontent.com/101970262/260612758-7f88e61f-0014-431d-9a07-937f4e65ed8c.png) 使用 uploader上传方法时，安卓手机正常调用，苹果手机无法调用的情况， ，vant upload调起的是浏览器层级相机，不是系统级相机，请问下在不改变组件的情况下,还有什么解决方案呢

请问解决了，我现在也有这个问题

**Comment by xiangrikuil** [comment]
> > ![image](https://user-images.githubusercontent.com/101970262/260612758-7f88e61f-0014-431d-9a07-937f4e65ed8c.png) 使用 uploader上传方法时，安卓手机正常调用，苹果手机无法调用的情况， ，vant upload调起的是浏览器层级相机，不是系统级相机，请问下在不改变组件的情况下,还有什么解决方案呢
> 
> 请问解决了，我现在也有这个问题

我也遇到了，尝试用[cordova-plugin-media-capture](https://github.com/apache/cordova-plugin-media-capture) 来解决问题

**Comment by hyyrz888** [comment]
鸿蒙系统 也不行  其他android手机可以
