### ISSUE TITLE
建议增加类似于cube-ui的scroll组件（内容滑动），很常用

### ISSUE THREAD

**Issue by WuYiZhan** [youzan/vant#3623]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持呢

**Comment by WuYiZhan** [comment]
这个功能其实你们已经实现了，只要提取出来就好了，就是Tab标签页组件的横向滚动略加封装

**Comment by chenjiahan** [comment]
Tab 横向滚动直接设置的 `overflow: scroll`，感觉没必要抽成组件
