### ISSUE TITLE
Sku组件的数据必须要和样例数据一样才有效果吗

### ISSUE THREAD

**Issue by wykolor** [youzan/vant#3624]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
结构要一致
