### ISSUE TITLE
datepicker 在苹果手机不显示 

### ISSUE THREAD

**Issue by fanchaot** [youzan/vant#3625]
![image](https://user-images.githubusercontent.com/32870484/60065260-dee32600-9735-11e9-9abe-d8801a07f910.png)
这是在真机上面的效果    机型是8P

![image](https://user-images.githubusercontent.com/32870484/60065286-f02c3280-9735-11e9-8865-c293b854ee9a.png)
这个是在 chrome 上面的效果

**Comment by chenjiahan** [comment]
请提供 codesandbox
