### ISSUE TITLE
[Bug Report] 使用v-if v-else渲染两个van-tabs组件会报错误

### ISSUE THREAD

**Issue by 941477276** [youzan/vant#3627]
### 设备 / 浏览器
Chrome（75.0.3770.100）

### Vant 版本
2.0.2

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-k3ge7" target="_blank">https://codesandbox.io/embed/vant-issue-moban-k3ge7</a>

### 描述问题
使用v-if v-else渲染两个van-tabs组件会报Cannot read property 'replaceChild' of null错误

**Comment by chenjiahan** [comment]
下个版本会修复，当前版本你可以在 tabs 上面加一个 key 来避免

**Comment by chenjiahan** [comment]
已在 2.0.3 版本修复
