### ISSUE TITLE
我更新到2.0版本自己写的路由在IOS 下面有时候不能点击了

### ISSUE THREAD

**Issue by zhaoqj008** [youzan/vant#3628]
刚更新了2.0版本后 <router-link :to="item.link">自己写的所有路由在IOS 下面有时候不能点击，只能刷新当前页面才可以点击，这个版本有什么控制吗

**Comment by chenjiahan** [comment]
路由指的是？看起来和 vant 没有关系

**Comment by zhaoqj008** [comment]
<router-link :to="item.link"> 这个我升级后 Ios点击有时候就不能用了

**Comment by chenjiahan** [comment]
建议自行排查下喔，如果你觉得是 vant 的问题，可以降级试试（大概率不是）

**Comment by zhaoqj008** [comment]
之前用的是1.6.13没有问题~早上我升级到了2.0.0 初始化页面的时候我自定义的vue路由全都不起作用了

**Comment by zhaoqj008** [comment]
之前用的是1.6.13没有问题~早上我升级到了2.0.0 初始化页面的时候我自定义的vue路由全都不起作用了，然后刷新当前页面就好了，在微信手机端

**Comment by chenjiahan** [comment]
麻烦提供下复现的 codesandbox 链接
