### ISSUE TITLE
[Feature Request] <van-tab>组件可以绑定name吗？

### ISSUE THREAD

**Issue by 941477276** [youzan/vant#3629]
### 这个功能解决了什么问题
目前<van-tab>组件v-model绑定的是当前激活的标签的索引，有时候想页面一进来就显示指定的标签，但标签个数是不确定的，此时使用索引就很难找到要显示的标签的索引，如果组件能绑定name，通过name来显示指定标签的话就方便很多了，就如同element-ui的tabs组件

### 描述您想要的解决方案
目前<van-tab>组件v-model绑定的是当前激活的标签的索引，有时候想页面一进来就显示指定的标签，但标签个数是不确定的，此时使用索引就很难找到要显示的标签的索引，如果组件能绑定name，通过name来显示指定标签的话就方便很多了，就如同element-ui的tabs组件

### 建议的API是什么样的
通过name来显示指定的标签

**Comment by chenjiahan** [comment]
可以的，后续支持

**Comment by chenjiahan** [comment]
已在 2.0.6 版本支持
