### ISSUE TITLE
[Bug Report] List组件的Load触发事件

### ISSUE THREAD

**Issue by CoutinhoTTS** [youzan/vant#3632]
### 设备 / 浏览器
电脑/谷歌浏览器

### Vant 版本
2.0.2

### Vue版本
2.6.10

### 重现链接
抱歉由于项目还在开发中，依赖于数据库不能提供链接
### 描述问题
很抱歉，由于项目与数据库链接还在开发中不好提供链接，抱歉。。
我在页面做了缓存，以用于实现前进刷新后退不刷新
当我页面属于前进时我就将data里的数据初始化这个时候内容并没有铺满一屏幕，但load没有触发
在路由里设置了判断条件,
其他的页面也使用了同样的判断条件但重新进入页面时会重新加载数据
![image](https://user-images.githubusercontent.com/48982306/60081698-e110a900-9764-11e9-9fae-64f013764542.png)
当页面第一次进入当前页面是列表为空并没有铺满整屏会触发load事件没有问题
![image](https://user-images.githubusercontent.com/48982306/60082676-cd664200-9766-11e9-8e5c-12c8b1b0b5d4.png)
加载成功：
![image](https://user-images.githubusercontent.com/48982306/60082822-22a25380-9767-11e9-9166-0ec5056d133c.png)
这是我代码里判断是前进还是后退，如果是前进就初始化data数据，返回的话就不初始化
![image](https://user-images.githubusercontent.com/48982306/60083071-99d7e780-9767-11e9-9c39-085819fadc17.png)
初始化的数据：
![image](https://user-images.githubusercontent.com/48982306/60083238-ec190880-9767-11e9-9c36-5b181eee6f29.png)
数据的渲染：
![image](https://user-images.githubusercontent.com/48982306/60083455-57fb7100-9768-11e9-970c-6764d3fcb970.png)
重新进入页面，打出关键值
![image](https://user-images.githubusercontent.com/48982306/60084126-89c10780-9769-11e9-92cb-0ad9e0d949d1.png)
![image](https://user-images.githubusercontent.com/48982306/60084061-6b5b0c00-9769-11e9-8a6d-20702429d28f.png)
页面中的效果：
![image](https://user-images.githubusercontent.com/48982306/60083695-c2acac80-9768-11e9-8b6c-237ba3d6ca4d.png)
### 并没有重新加载数据，页面内容也没有超出一屏，（我这里使用了标签页组件并在load方法中进行了判断当前是哪个标签页就加载当前标签页的内容，但当我点击第二个标签页是它会加载第二个标签页的内容）
![image](https://user-images.githubusercontent.com/48982306/60084636-75c9d580-976a-11e9-93a8-708df4e36890.png)
![image](https://user-images.githubusercontent.com/48982306/60084736-a6117400-976a-11e9-97f1-f35872ca3123.png)
![image](https://user-images.githubusercontent.com/48982306/60084778-bf1a2500-976a-11e9-875e-6d92ba2ff8a1.png)

**Comment by WuYiZhan** [comment]
注意onload的触发跟容量的高度有关，第一次进来之所以会触发onload就是当list有数据时内容高度由零增加到而触发onload

**Comment by CoutinhoTTS** [comment]
第一次进来，list数据为空，页面的容量高度页没有超过一屏，会触发自动触发load。所以我就没在created里请求数据，将数据请求放在了load里。当重新进入时我将data里的数据初始化，list也就初始化了为空，页面内容也就初始化了，页面的容量高度页没有超过一屏这个时候应该触发load事件重新请求数据，但并没有触发load事件

**Comment by chenjiahan** [comment]
文档里增加了 List 组件原理更多的介绍，可以看下

**Comment by ystarlongzi** [comment]
@CoutinhoTTS 建议先通过以下方案解决这个问题

 - 卡盘下的 `<List />` 组件都分配一个随机的 `key`，在切换到这个卡盘时，初始化数据 `this.list = []` 的同时更新这个 `key`，这样就相当于首次渲染 `<List />` 组件，它就会触发 `load` 事件

- 在切换到这个卡盘时，初始化数据 `this.list = []` 的同时主动调接口获取第一页的数据去初始化

**Comment by UmbraCi** [comment]
> 文档里增加了 List 组件更多的介绍，可以看下

文档看过了，也遇到了这个问题，就简单的一个refresh组件加上list组件，点击list组件内部的item跳转路由，然后回退的时候，list组件没有触发onload函数，比如手动check一次，请问原因是什么呢？第一次进页面初始化的时候会自动check然后触发onload，但是回退路由就不会

**Comment by UmbraCi** [comment]
> 第一次进来，list数据为空，页面的容量高度页没有超过一屏，会触发自动触发load。所以我就没在created里请求数据，将数据请求放在了load里。当重新进入时我将data里的数据初始化，list也就初始化了为空，页面内容也就初始化了，页面的容量高度页没有超过一屏这个时候应该触发load事件重新请求数据，但并没有触发load事件

请问你是如何解决的呢

**Comment by zheng013** [comment]
> 

解决了吗🤣

**Comment by UmbraCi** [comment]
> > 
> 
> 解决了吗🤣

时间太久远了，不记得当时具体怎么处理的了，不过你可以在chrome的source打个断点，断点位置在刷新组件的check函数附近，如果没记错的话，应该是路由视图动画导致的，导致切换路由的时候，页面有两个路由视图的dom，从而导致组件内部计算高度错误，你先试试把webviewe视图的mode设置为out-in试试

**Comment by zheng013** [comment]
就是跳转页的容器高度如果超过100vh就会出现无法 触发load的情况

**Comment by zheng013** [comment]
但是不知道原因是啥  我尝试用demo构造相同的场景，也没有复现

**Comment by UmbraCi** [comment]
> 就是跳转页的容器高度如果超过100vh就会出现无法 触发load的情况

打断点吧，vant组件内部打load触发的断点，看下为什么没有触发，talk is cheap，先动手，这种一般是由样式导致的

**Comment by zheng013** [comment]
好的 谢谢你
