### ISSUE TITLE
[Bug Report] IOS10 datetime-picker 在微信不兼容

### ISSUE THREAD

**Issue by kson34** [youzan/vant#3633]
### 设备 / 浏览器
IOS10 微信7.0.4

### Vant 版本
2.0.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/intro" target="_blank">https://youzan.github.io/vant/#/zh-CN/intro</a>

### 描述问题
我是扫你们demo 二维码测试的datetime-picker，上拉选择日期就整个页面也在动没办法正常使用。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3015
