### ISSUE TITLE
van-cell中to跳转不到子路由，只跳主路由

### ISSUE THREAD

**Issue by mengerwei521** [youzan/vant#3635]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by mengerwei521** [comment]
在使用  <van-cell title="我的余额"
                  is-link
                  to="Balance"
                  icon="balance-o" />中 Balance是子路由，点击跳转却变成主路由显示了

**Comment by chenjiahan** [comment]
不规范的 issue
