### ISSUE TITLE
[Feature Request] 考虑增加van-list 横向滚动的功能

### ISSUE THREAD

**Issue by zhouDCC** [youzan/vant#3637]
### 这个功能解决了什么问题
解决了 在移动端需要横向滚动的需求

### 描述您想要的解决方案
在vant-list 加一个参数 是能改变list为横向模式

### 建议的API是什么样的
水平方向 还是 垂直方向

**Comment by chenjiahan** [comment]
暂无计划支持喔，List 组件目前还是聚焦于竖直方向的瀑布流加载
