### ISSUE TITLE
[Feature Request] 建议uploader增加类似小程序的选择图片时设置来源功能

### ISSUE THREAD

**Issue by nicksun011** [youzan/vant#3641]
### 这个功能解决了什么问题
建议uploader增加类似小程序的选择图片时设置来源功能，可以设置只打开相机还是只从相册选择，还是两者都启用

### 描述您想要的解决方案
--

### 建议的API是什么样的
--

**Comment by chenjiahan** [comment]
文档里有 capture 属性，可以参考下。由于浏览器能力限制，做不到小程序那样可以自由选择

**Comment by nicksun011** [comment]
嗯，看到capture了，也就是说现在只支持单独直接打开摄像头？

**Comment by chenjiahan** [comment]
对的
