### ISSUE TITLE
[Bug Report] vue跳转外部链接，再返回以后，页面所有连接全部失效，点击没有反应

### ISSUE THREAD

**Issue by weinichengsan** [youzan/vant#3642]
### 设备 / 浏览器
ios最新版本12.3.1

### Vant 版本
1.6.23

### Vue版本
2.5.2

### 重现链接
<a href="http://prelinehcm.renshiren.com/dist/index.html#/find" target="_blank">http://prelinehcm.renshiren.com/dist/index.html#/find</a>

### 描述问题
vue跳转外部链接，再返回以后，页面所有连接全部失效，点击没有反应
页面中的京东618一起嗨，点击完后再返回，页面里的所有连接全部就失效了，页面刷新一下就好了，只有在最新的这个ios版本才会出现，并且是必现的

**Comment by chenjiahan** [comment]
试了下没复现呢，我是 iphone XR 12.3.1

**Comment by weinichengsan** [comment]
我刚才把vue的版本升级到2.6.10了，现在暂时没有看到这个情况了，在2.5.2的时候是必现的

**Comment by chenjiahan** [comment]
2.5.2 是两年前的 Vue 版本了，现在推荐使用 2.5.22 或者 2.6.10

**Comment by weinichengsan** [comment]
好的，现在我先用2.6.10的看看再说吧，再有什么问题咋，再来请教

**Comment by chenjiahan** [comment]
ok
