### ISSUE TITLE
[Bug Report] iPhone6p下拉选择滑动有问题

### ISSUE THREAD

**Issue by weinichengsan** [youzan/vant#3643]
### 设备 / 浏览器
iPhone6p 版本是10.1

### Vant 版本
1.6.23

### Vue版本
2.5.2

### 重现链接
<a href="http://prelinehcm.renshiren.com/dist/index.html#/index" target="_blank">http://prelinehcm.renshiren.com/dist/index.html#/index</a>

### 描述问题
只要是页面涉及到下来选择的，在这个手机上面滑动都会出现问题，可以点击，但是滑动的时候要么滑动失败，要么就是直接触发滑动这个页面了，尝试着把vant升级到最新的版本了，虽然可以解决这个问题，但是发现ios最新的版本上面全部出现首次加载链接全部失效的问题，无奈就先回退到这个版本吧，上面的这个情况在安卓都是正常的，只有这个版本

**Comment by chenjiahan** [comment]
没看懂你的描述，下来选择是什么组件，首次加载链接全部失效又是什么意思

**Comment by weinichengsan** [comment]
pick的组件，出现的这个问题，首次加载的那个是我上一个问题的遗留问题，已经解决了
![image](https://user-images.githubusercontent.com/51942914/60167683-29e46280-9836-11e9-975b-d405dce312bf.png)
不能滑动的就是这种

**Comment by chenjiahan** [comment]
这个问题参见 https://github.com/youzan/vant/issues/3015
