### ISSUE TITLE
[BUG Report] ImagePreview 预览图片，可以滚动背景页面 

### ISSUE THREAD

**Issue by LeeVicky** [youzan/vant#3644]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.0.3 版本修复
