### ISSUE TITLE
[Bug Report] 单选框使用文档示例中图标van-radio被居中显示

### ISSUE THREAD

**Issue by view868** [youzan/vant#3647]
### 设备 / 浏览器
firefox/chrome

### Vant 版本
2.0.2

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-rip8h?fontsize=14" target="_blank">https://codesandbox.io/s/vant-issue-moban-rip8h?fontsize=14</a>

### 描述问题
2.0版本“Radio 单选框”文档“与 Cell 组件一起使用”的示例中van-radio被居中显示
    <van-radio-group v-model="radio">
      <van-cell-group>
        <van-cell title="单选框 1" clickable @click="radio = '1'">
          <van-radio  name="1" />
        </van-cell>
        <van-cell title="单选框 2" clickable @click="radio = '2'">
          <van-radio name="2"  />
        </van-cell>
      </van-cell-group>
    </van-radio-group>
图标应使用插槽
slot="right-icon"
示例代码应改为
    <van-radio-group v-model="radio">
      <van-cell-group>
        <van-cell title="单选框 1" clickable @click="radio = '1'">
          <van-radio slot="right-icon" name="1" />
        </van-cell>
        <van-cell title="单选框 2" clickable @click="radio = '2'">
          <van-radio name="2" slot="right-icon" />
        </van-cell>
      </van-cell-group>
    </van-radio-group>

**Comment by chenjiahan** [comment]
感谢反馈，近期会更新下文档

**Comment by chenjiahan** [comment]
已更新
