### ISSUE TITLE
babel-plugin-import按需引入无效

### ISSUE THREAD

**Issue by liubin595338764** [youzan/vant#3650]
已经将问题包上传至github： 
https://github.com/liubin595338764/vantError

```js
import { Button } from 'vant'
// import Vue from 'vue'
// Vue.use(Button)    
```
 必须要用Vue.use(Button)  注册一下组件，否则组件在页面上会报错；

![image](https://user-images.githubusercontent.com/5274428/60173881-5ef6b200-9842-11e9-9708-a5c46163efc1.png)

*提 Issues 的模板无法选择vant版本*

**Comment by liubin595338764** [comment]
知道了，需要在components里面注册：
```js
components:{
   [Button.name]: Button
}
```
建议把这个关键放到文档里面啊，不然第一次来真的不知道。在例子里面找到的

**Comment by chenjiahan** [comment]
这个是常识

**Comment by liubin595338764** [comment]
@chenjiahan 要注册是常识，但是第一次来没人知道你要`Button.name`去注册。
而且要导入也是常识，你也干脆不用写出来了。

**Comment by chenjiahan** [comment]
文档里提供了 `Vue.use` 注册组件的介绍，这是最简单且推荐的方式，不清楚你为什么不使用这种方式。

通过`Button.name`注册是另一种方式，实际上还有更灵活的方式，但我们未必要把所有的注册方式都写到文档里，这会增添用户选择的负担。

**Comment by liubin595338764** [comment]
@chenjiahan 从体积考虑，我们是采用按需引入的方式，使用 `Vue.use` 的话需要在每个vue文件里面写入
`import Vue from 'vue'; Vue.use(Button)` 这样的代码，而且引入多个组件需要写多次use，或者再包装use。
引入→注册，这是最直接的，请问更灵活的方式是什么；

**Comment by chenjiahan** [comment]
不需要每个文件写一次，这是全局注册

**Comment by liubin595338764** [comment]
@chenjiahan  按需引入，又不确定用户先访问哪个页面，不是要每个页面上都写一次么。

**Comment by chenjiahan** [comment]
项目里一般会有一个基础的 js 文件，用于引入公共模块

**Comment by liubin595338764** [comment]
@chenjiahan 你说的是公共模块，可以用`Vue.use`注册，但是还有更多的非公共模块，还用`Vue.use`就出现上面说的情况了

**Comment by chenjiahan** [comment]
以 Button 为例，在一个公共模块内注册后，所有页面都可以使用 van-button 标签

**Comment by songyu0122** [comment]
如果大量的使用 组件岂不是要 vue.use().use()好多，你说的更加灵活的方式是什么？ 我只想在组件里面impor {Button} from 'vant‘  然后就可以使用。有办法么？

**Comment by chenjiahan** [comment]
没有
