### ISSUE TITLE
[Bug Report] van-stepper 组件，设置min和max属性之，不能清除输入框内容

### ISSUE THREAD

**Issue by aikokk** [youzan/vant#3653]
### 设备 / 浏览器
chrome浏览器

### Vant 版本
1.1.5

### Vue版本
2.5.22

### 重现链接
<a href="http://h5.nashi8.com/#/skillDetail?billno=SP201906041625220125" target="_blank">http://h5.nashi8.com/#/skillDetail?billno=SP201906041625220125</a>

### 描述问题
van-stepper组件设置min和max属性之后，输入框内的值不能清除，导致无法正确输入。

**Comment by huangysss** [comment]
升级一下vant试试，我尝试了1.6.23版本，可以正确删除。

**Comment by chenjiahan** [comment]
嗯，升级版本可以解决的
