### ISSUE TITLE
[Bug Report] Popup组件中的元素上下滑动会抖动

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#3654]
### 设备 / 浏览器
iPhone8

### Vant 版本
2.0.2

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-ifk78" target="_blank">https://codesandbox.io/s/vant-issue-moban-ifk78</a>

### 描述问题
Popup组件中的元素上下滑动会抖动，Popup设置为transition="none"，出现抖动的元素设置了position:fixed。
复现步骤：先上拉一小段距离，然后下拉一大段距离。

**Comment by chenjiahan** [comment]
Popup 默认开启了浏览器的弹性滚动 `-webkit-overflow-scrolling: touch;`，目测是弹性滚动把 Fixed 元素也弹了一下

你可以把这个属性设置成 none，或者把 List 改成局部滚动

**Comment by huangysss** [comment]
```
.van-popup {
  -webkit-overflow-scrolling: none !important;
}
```
我进行了上面的设置，发现并未有效果。
实际上，对List使用局部滚动效果会更好，因为不用去掉popup的transfrom.

**Comment by chenjiahan** [comment]
我试了下两种都可以呢，确实是局部滚动更优，体验比较好
