### ISSUE TITLE
[Bug Report] <list>组件在可视区域时会一直加载数据

### ISSUE THREAD

**Issue by 941477276** [youzan/vant#3657]
### 设备 / 浏览器
Chrome（75.0.3770.100）

### Vant 版本
2.0.2

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-2941v" target="_blank">https://codesandbox.io/s/vant-issue-moban-2941v</a>

### 描述问题
如果<van-list>标签在可视区域之内，<van-list>组件会一直加载数据，直到告诉组件已经没有数据可以再加载了。
正常情况应该是只需要加载一次就够了，如果再需要获取数据，那么就应该由用户往下拉的时候再去加载数据

**Comment by chenjiahan** [comment]
文档里增加了这部分逻辑的介绍，可以看下
https://youzan.github.io/vant/#/zh-CN/list
