### ISSUE TITLE
[Bug Report] overlay animation duration

### ISSUE THREAD

**Issue by a298003154** [youzan/vant#3665]
设备 / 浏览器
chrome

Vant 版本
dev

Vue版本
2.6.10

重现链接
无

描述问题
文件1：mixins/popup/index.js；行：174
文件2：overlay/index.tsx，行：39
合并 this.duration 到 overlay 的 style，而 duration 的设计是和定时器一样的ms，导致overlay的动画时间过长

**Comment by chenjiahan** [comment]
过长是指？ overlay 动画时间和 Popup 保持一致是比较合理的

**Comment by a298003154** [comment]
@chenjiahan 你checkout dev包 启动项目打开toast页的Loading提示就知道了
![image](https://user-images.githubusercontent.com/24939100/60272902-968b5a00-9927-11e9-8532-063569af76c4.png)

**Comment by chenjiahan** [comment]
get

**Comment by chenjiahan** [comment]
fixed
