### ISSUE TITLE
List组件重复触发load事件

### ISSUE THREAD

**Issue by Smile-dan** [youzan/vant#3666]
**设备 / 浏览器**
Chrome

**Vant 版本**
2.0.2

**Vue版本**
2.6.10

**描述问题**
初次请求没有充满页面的时候，会重复触发load事件。finished和loading都已设置，在onLoad中console.log(this.loading)为true，按说loading为true时不应该触发onLoad

```
onLoad() {
            console.log(this.loading)  //这里输出true
            this.loading = true;
            // 异步更新数据
            var curpn = parseInt(this.pagination.pn);
            var param = this.getSearchData();
            param.pn = curpn + 1;
            this.fetchList(param);
},
```
请求结束后
```
fetchList(param) {
            var that = this;
            this.$fetch({
                url: "",
                method: 'post',
                data: param
            }).then((res) => {
                if(res.retcode==0){//请求成功
                   ...省略
                    that.finished = res.pageInfo.pageNum == res.pageInfo.pages ? true : false;
                    that.loading = false;
                }else {//请求失败
                    that.loading = false;
                    that.error = true;
                    Toast(res.retmess);
                }
            }).catch(function (error) {
                that.loading = false;
                that.error = true;
            })       
        },
```

**Comment by chenjiahan** [comment]
给个复现链接吧，接口请求可以用 setTimeout 代替

**Comment by 941477276** [comment]
@chenjiahan https://github.com/youzan/vant/issues/3657 这个issue与楼主的问题是一直的，希望你们能尽快修复

**Comment by chenjiahan** [comment]
@941477276 你这个不是 bug，List 内容至少得填满当前屏幕，不然就会继续触发加载，这是符合期望的。你应该适当提高一次拉取的数据条数。

**Comment by fairok** [comment]
@chenjiahan 我1次加载的量远远超过屏幕高度，但和楼主的情况一样，依然会一次加载多页

**Comment by chenjiahan** [comment]
@fairok 上复现链接。

**Comment by 941477276** [comment]
@chenjiahan 我觉得 fairok 遇到的问题就跟我的是一样的，不知道<list>组件是不是只能是全屏的，站在使用者的角度来说我希望<list>组件在页面任何一个位置都能正常的实现上拉刷新功能，如同betters-scroll.js实现上拉刷新功能一样。建议给<list>组件传递一个最大高度，超过这个高度再往上滑就触发load事件，这样就避免了"List 内容至少得填满当前屏幕，不然就会继续触发加载"这个问题

**Comment by chenjiahan** [comment]
这个组件不是上拉刷新，是滚动加载，两者是完全不同的

**Comment by 941477276** [comment]
哦哦，好的。你这样一说就明白了，希望文档中能够说明这一点，很容易让人理解成上拉加载组件。另一个就是可以增加一个上拉加载组件吗？

**Comment by chenjiahan** [comment]
文档第一句话就是介绍。。上拉加载暂时没计划增加呢

**Comment by ystarlongzi** [comment]
> @chenjiahan 我1次加载的量远远超过屏幕高度，但和楼主的情况一样，依然会一次加载多页

看下这个有帮助没 https://github.com/youzan/vant/issues/3437#issuecomment-498638252

**Comment by ystarlongzi** [comment]
@941477276 
列表常见的加载操作交互不是
 - 下拉刷新（比如 [pull-refresh](https://youzan.github.io/vant/#/zh-CN/pull-refresh)）
 - 上拉加载更多（比如 [list](https://youzan.github.io/vant/#/zh-CN/list)）

你说的「上拉刷新」应用场景是什么

**Comment by ystarlongzi** [comment]
哦哦，上面说的「上拉刷新」里的「刷新」并不是指重新加载数据，而是指有用户主动触发「上拉」动作后，再去加载更多？

**Comment by RossiLc** [comment]
> @941477276 你这个不是 bug，List 内容至少得填满当前屏幕，不然就会继续触发加载，这是符合期望的。你应该适当提高一次拉取的数据条数。

有一些场景，当数据做筛选时，比如筛选今天的数据，服务端返回的数据很少，就会不足一屏，导致第二次加载。建议提供开关来配置此属性，不能一棒子打死。
