### ISSUE TITLE
vant2.0.2定制主题无效

### ISSUE THREAD

**Issue by chen-can** [youzan/vant#3668]
参考vant-demo 在main.js 引入
import 'vant/lib/index.css'
import { NavBar, Button } from 'vant';
Vue.use(NavBar).use(Button);
config.js 配置
 css: {
    loaderOptions: {
      less: {
        modifyVars: {
          red: '#333'
        }
      }
    }
  }
页面上主题颜色并没有更改

**Comment by chenjiahan** [comment]
要引用 less 文件，不是 css

**Comment by chen-can** [comment]
解决了 谢谢
