### ISSUE TITLE
[Bug Report] van-nav-bar使用 fixed= true 时， 左边空了1px（left=-1px

### ISSUE THREAD

**Issue by xiaozhanghui** [youzan/vant#3670]
### 设备 / 浏览器
iOS和 android都有

### Vant 版本
2.0.1

### Vue版本
2.5.2

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-kpg58" target="_blank">https://codesandbox.io/embed/vant-issue-moban-kpg58</a>

### 描述问题
van-nav-bar使用 fixed= true 时， 左边空了1px（left=-1px; 则正常）

**Comment by chenjiahan** [comment]
打开你的链接看了下，没发现有空隙呢，你是用什么手机看的

**Comment by xiaozhanghui** [comment]
> 打开你的链接看了下，没发现有空隙呢，你是用什么手机看的

样式被别人设置了1px border，sorry
