### ISSUE TITLE
[Feature Request] toast 组件 的props命名和使用

### ISSUE THREAD

**Issue by a298003154** [youzan/vant#3672]
设备 / 浏览器
chrome

Vant 版本
dev

Vue版本
2.6.10

重现链接
无

描述问题
1. overlay 命名不统一
使用overlay的大部分组件（包括popup dialog）都使用 overlay 控制是否显示蒙层
而toast反而叫做mask，使用起来有点让人捉急，虽然 toast 组件内部实现了 transformOptions 方法
2. toast 的props不够清晰
1）toast的函数式调用 有默认的defaultOptions，如下图1
2）toast的组件模板使用缺少props，如下图2。例：onOpened、 onClosed 和 duration 的props声明缺失但组件内有使用。onClosed在哪使用了暂未发现。
![image](https://user-images.githubusercontent.com/24939100/60276143-a312b100-992d-11e9-8aa3-65385b19a9c7.png)
![image](https://user-images.githubusercontent.com/24939100/60276154-aad25580-992d-11e9-8b53-754a8a5ce44d.png)

**Comment by chenjiahan** [comment]
1. 命名为 mask 而不是 overlay 是历史原因，修改命名会造成 breaking change，短时间内不会调整，3.0 版本会考虑。

2. Toast 目前不支持组件调用， props 不是组件使用者应该关心的，后续如果支持组件调用了，会完善这部分。

**Comment by a298003154** [comment]
我是fork下来，造轮子使用的时候发现的，所以提出疑问。
现在了解意图
