### ISSUE TITLE
如何在search，field，steps等组件内的属性上直接使用自己的图标库的图标。现在引入了自己的图标，然后用组件图标属性添自己的图标名字不行

### ISSUE THREAD

**Issue by shouwangshe** [youzan/vant#3674]
Vant 版本
2.0.1
Vue版本
2..6
描述问题
同标题
如何在search，field，steps等组件内的属性上直接使用自己的图标库的图标。现在引入了自己的图片，然后用组件图标属性添自己的图标名字不行
大致有如下组件：
field ------>    right-icon  right-icon
search ------>    right-icon  right-icon
rate ------>    icon  void-icon
button------>    icon
steps ------>    active-icon  inactive-icon
tabbar ------>    icon
GoodsAction ------>    icon
SubmitBar ------>    tip-icon
NoticeBar ------>    right-icon  right-icon
CollapseItem------>    icon  right-icon
有挺多有slot可以解决，有的没有提供slot。希望能改进一下。能支持自己的图标。
直接用我的图标的名字可以引入。

**Comment by JakeLaoyu** [comment]
请仔细看文档

![image](https://user-images.githubusercontent.com/16181940/60312588-6cb94e00-998e-11e9-9da2-a07f5e111784.png)

**Comment by JakeLaoyu** [comment]
你列举的这些组件大部分都支持icon slot

button组件的icon你可以写在标签内

vant组件的icon是基于 van-icon 组件的，所以不支持你自定义的图标，除非是链接。

**Comment by chenjiahan** [comment]
@JakeLaoyu 他的意思应该是 Icon 组件可以设置`class-prefix`来使用自定义组件库，但是其他组件的 icon 属性不支持这样使用

**Comment by JakeLaoyu** [comment]
@chenjiahan 我感觉其他组件没有必要支持，其他组件可以通过slot引入vant-icon

**Comment by shouwangshe** [comment]
@chenjiahan 感谢回复的这么快。就是这意思。我们的icon组件用了class-prefix方式自定义了图标了。别的组件好像不支持这样引自己的图标。

**Comment by chenjiahan** [comment]
@shouwangshe 建议是用 slot 去做，如果有哪个组件缺少 slot 的，可以反馈给我们

**Comment by shouwangshe** [comment]
@chenjiahan 好的。有空缕一缕反馈一下，或者用到时候在反馈。现在能记住的 Rate评分这个没有slot.嗯。别的好像还都有。

**Comment by chenjiahan** [comment]
这个 issue 先关闭咯，哪个组件需要加 slot，单独开 issue 提就好

**Comment by chenjiahan** [comment]
Rate 比较特殊，不能直接用 slot（因为有好几个 icon），可以使用 svg 图片

**Comment by nwdsl1982** [comment]
> @shouwangshe 建议是用 slot 去做，如果有哪个组件缺少 slot 的，可以反馈给我们

按钮似乎就不支持slot，至今没找到在按钮上使用第三方图标的办法
