### ISSUE TITLE
[Feature Request] Field组件添加Cell属性arrow-direction

### ISSUE THREAD

**Issue by smilecoder** [youzan/vant#3677]
### 这个功能解决了什么问题
扩展下拉选择时期望箭头向下

### 描述您想要的解决方案
添加Cell属性arrow-direction

### 建议的API是什么样的
arrow-direction

**Comment by chenjiahan** [comment]
下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.0.4 版本支持
