### ISSUE TITLE
2.x版本使用postcss-pxtorem无效

### ISSUE THREAD

**Issue by DemoHu** [youzan/vant#3678]
vant升级到2.0.x以后，生产环境下postcss-pxtorem不会将vant组件的px转为rem，本地环境正常

只能将vant回退到1.6.23

**Comment by chenjiahan** [comment]
我们示例仓库就是 2.0 版本，好像没遇到这个问题

https://github.com/youzan/vant-demo

**Comment by DemoHu** [comment]
@chenjiahan 2.0.3版本有这个问题

**Comment by chenjiahan** [comment]
试了 2.0.3 也没问题

**Comment by DemoHu** [comment]
@chenjiahan    啊啊啊！！！ 确实在我这里2.0.3有问题啊  回退到2.0.1 就好了  使用的是cnpm 安装的

**Comment by chenjiahan** [comment]
能提供个复现仓库吗，或者你自己排查下问题

**Comment by DemoHu** [comment]
@chenjiahan   我刚刚将`postcss-pxtorem` 换成 `postcss-plugin-px2rem` 就好了，2.0.3也正常了

**Comment by Crapulence** [comment]
我也遇到了`postcss-pxtorem`无效的问题，我的版本是 2.0.4

**Comment by chenjiahan** [comment]
如果出现 postcss.config.js 配置没对 vant 生效，原因是 vue-cli 优先读取了 vant 目录下的 postcss 配置

建议参考 vant 示例仓库的配置，这个是对所有包都能生效的：https://github.com/youzan/vant-demo/blob/master/viewport/vue.config.js 

下个版本我会过滤掉 vant 目录下的 postcss 配置

**Comment by ShangZhiLei** [comment]
大概7.8天前
用postcss-pxtorem还是有用的，但是这两天在配合vant使用，就没有效果了，照着你的配置下也没有用处，和这个该怎么办

**Comment by shen-lan** [comment]
> 大概7.8天前
> 用postcss-pxtorem还是有用的，但是这两天在配合vant使用，就没有效果了，照着你的配置下也没有用处，和这个该怎么办

解决了吗？ 之前我的都也是可以正常的。现在不行了

**Comment by chenjiahan** [comment]
@shen-lan 升级版本试下

**Comment by luandapoppy** [comment]
我之前也都是可以的，今天突然不能转换了呜呜呜呜
