### ISSUE TITLE
Field组件type设置为number，在iOS的webview加载后，仍然可以输入非数字字符

### ISSUE THREAD

**Issue by mcuking** [youzan/vant#368]
**What is the current behavior?**
Field组件type设置为number，在iOS的webview加载后，仍然可以输入非数字字符
web端和安卓的webview加载时生效的，无法输入非数字字符
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**
代码截图如下
![image](https://user-images.githubusercontent.com/22924912/33464404-02878fe0-d67d-11e7-8d99-811403ac8173.png)

**What is the expected behavior?**
希望在iOS的webview仍然生效
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@mcuking 收到反馈

**Comment by mcuking** [comment]
@chenjiahan 另外问下这个组件不能限制输入的字符数么？

**Comment by chenjiahan** [comment]
@mcuking 直接使用原生的 maxlength 属性就行

**Comment by chenjiahan** [comment]
已在 0.11.6 中修复
