### ISSUE TITLE
collapse无法完全展开

### ISSUE THREAD

**Issue by fengxingll** [youzan/vant#3685]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
代码片段如下：
`<my-collapse value="{{ activeName }}" bind:change="onChange" data-field="clickCollapse" accordion>
  <my-collapse-item title="选择班级" name="c">
    
    <my-cell title="年级" titleWidth="120rpx" isComplex border="{{false}}">
      <my-radio-group value="{{curScore.grade}}" bind:change="onChange" data-field="grade">
        <view wx:for="{{grade_info}}" wx:key="{{index}}" style='width:150rpx;display:inline-block'>
          <my-radio name="{{item.id}}">{{item.title}}</my-radio>
        </view>
      </my-radio-group>
    </my-cell>
    
    <my-cell wx:if="{{ curScore.grade }}" isComplex border="{{false}}">
      <my-radio-group value="{{curScore.class}}" bind:change="onChange" data-field="class">
        <view wx:for="{{grade_info[curScore.grade].classes}}" wx:key="{{index}}" style='width:100rpx;display:inline-block;margin-right:10rpx'>
          <my-radio name="{{item}}" simple>{{item}}</my-radio>
        </view>
      </my-radio-group>
    </my-cell>
  </my-collapse-item>`
**错误表现：点击年级按钮，班级列表应该相应的加载并显示，但是面板并未随着班级数据的加载而变高，而是被遮挡了。但是点击一次右边的箭头图标，使得面板折叠再展开一次后，变现就正常了。**

**Comment by chenjiahan** [comment]
不规范的 issue

**Comment by bolechen** [comment]
楼主这个问题解决了吗？
