### ISSUE TITLE
[Feature Request] 非常希望官方能出个上拉加载组件

### ISSUE THREAD

**Issue by 941477276** [youzan/vant#3687]
### 这个功能解决了什么问题
用了<vant>库后发现没有上拉加载组件，市面上又找不到ui与vant相匹配的上拉加载组件，这很蛋疼呀，用了vant组件还要去使用其他的插件

### 描述您想要的解决方案
希望官方能出个上拉加载组件

### 建议的API是什么样的
希望官方能出个上拉加载组件

**Comment by chenjiahan** [comment]
能否描述下你的使用场景，最好有截图

**Comment by 941477276** [comment]
![上拉加载下拉刷新](https://user-images.githubusercontent.com/20528541/60378486-b751cd80-9a55-11e9-94c2-261b1ccfa9b5.gif)
如我这个页面就需要有上拉加载的功能，像一般的商城系统在加载商品列表的时候也可以使用上拉加载功能呀(如淘宝的列表页)，如果没有上拉加载那么就需要有一个加载更多的按钮，这样的体验是很不友好的，目前我是找的一个插件来完成的，但我更希望<vant>自带上拉加载功能，这样开发者使用起来就轻松简单了，下拉刷新、上拉加载都内置，而不需要再去找额外的插件。

**Comment by chenjiahan** [comment]
上拉刷新这个交互是不常见的，下面是我对这三个交互的理解：

### 下拉刷新
即 Vant 中的`PullRefresh`组件，在区块顶部向下拖动，松开后刷新列表数据，这个手势在移动端很常见。

### 上拉加载
即 Vant 中的`List`组件，通过向上拖动的手势，使得页面滚动条下移，触发滚动事件，在滚动到底部时加载数据。

### 上拉刷新
即你图片中演示的操作，在区块底部向上拖动，松开后刷新列表数据。

这个操作是『反向的下拉刷新』，移动端用户没有这样的操作习惯，我觉得这样设计是不合理的。目前没有计划提供这样的组件。

如果你有更多上拉刷新的例子，可以发上来看看

**Comment by 941477276** [comment]
不是的，我的意思不是上拉刷新，而是希望有一个上拉加载组件。vant的list组件感觉只能是整个页面级别的上拉加载，而不能实现页面某个部分的上拉加载，如果在页面某个部分用了list组件就会出现 https://github.com/youzan/vant/issues/3666 这个问题

**Comment by chenjiahan** [comment]
你的图片里就是上拉刷新。

如果有局部上拉加载的例子，可以把图片贴上来看下

**Comment by 941477276** [comment]
![上拉加载](https://user-images.githubusercontent.com/20528541/60379751-ffc7b600-9a6a-11e9-9184-037b72231303.gif)
比如评论这里就需要使用上拉加载更多数据，如果不用上拉加载，那就需要有一个加载更多按钮了。如果用<list>组件的话是会出现load事件一直触发的问题的

**Comment by chenjiahan** [comment]
从截图上看，这里是完全可以使用 List 组件的，不知道你说的『一直触发』是指什么情况

**Comment by ystarlongzi** [comment]
@941477276 
1. `<List />` 组件是作用在 `overflow: scroll` 的祖先元素，不一定是作用在 body 上
2. `<List />` 组件「底部」只要在可视区域是会一直不断触发 `load` 事件的，个人感觉这样的交互会相对好一些，因为连续触发两次、三次....用来填满整个屏幕，理论上用户也是无感知的，但体验上会感觉列表数据是「连续」、「丰富」的

**Comment by ystarlongzi** [comment]
感觉在这个问题上，我们沟通、理解上都有偏差，建议图片 gif 示例碰到的问题，搞个 demo 放到 jsfiddle 或 codeopen 上，这样会更容易理解些

**Comment by Hideer** [comment]
发现在触发van-pull-refresh的下拉刷新的时候同事也会触发van-list的loading状态，相当于请求两次接口

**Comment by ystarlongzi** [comment]
@Hideer 可以提供一个复现的 demo 嘛 https://codesandbox.io/s/m5v3f
