### ISSUE TITLE
stepper当设置了min,max后用输入的限制无效，只有点击加减才有生效

### ISSUE THREAD

**Issue by Kennersky** [youzan/vant#3689]
如题，stepper当设置了min,max后，用输入的数字限制不生效，可以输入任意值，只有点击加减才有生效这个限制。 @chenjiahan

**Comment by chenjiahan** [comment]
Stepper 设置的最大值和最小值，在输入结束后（blur）才会生效。

这是为了保证用户在输入过程中不会受到范围限制而无法输入某些值

**Comment by Kennersky** [comment]
> Stepper 设置的最大值和最小值，在输入结束后（blur）才会生效。
> 
> 这是为了保证用户在输入过程中不会受到范围限制而无法输入某些值

隐藏操作啊
