### ISSUE TITLE
IndexBar在选中时建议增加选中class

### ISSUE THREAD

**Issue by zhangfei8080** [youzan/vant#3691]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
---------
建议在选中索引时赋予当前选中索引指定的CLASS方便在做特殊需求时样式更改,不仅仅是文字颜色
---------
https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
下个版本会加个

**Comment by chenjiahan** [comment]
已在 2.0.4 版本支持
