### ISSUE TITLE
van-goods-action-mini-btn不支持icon的自定义，默认带上了van-icon前缀，找不到图标。

### ISSUE THREAD

**Issue by benbenyao** [youzan/vant#3693]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
不规范的 issue
