### ISSUE TITLE
[Bug Report] van-goods-action-mini-btn组件的icon问题

### ISSUE THREAD

**Issue by benbenyao** [youzan/vant#3697]
### 设备 / 浏览器
浏览器

### Vant 版本
1.6.23

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/goods-action" target="_blank">https://youzan.github.io/vant/#/zh-CN/goods-action</a>

### 描述问题
里面icon="chat-o"，在页面转换成了van-icon-chat-o，也就是说，这个组件还不支持slot，我看里面的源码实现也没有，请问要添加自己的图标，现在该怎么弄呢？

**Comment by chenjiahan** [comment]
下个版本加个 slot

**Comment by chenjiahan** [comment]
已在 2.0.4 版本支持
