### ISSUE TITLE
[Bug Report] <van-picke>组件样式被污染问题

### ISSUE THREAD

**Issue by 941477276** [youzan/vant#3699]
### 设备 / 浏览器
Chrome（75.0.3770.100）

### Vant 版本
2.0.3

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-hqrgy" target="_blank">https://codesandbox.io/s/vant-issue-moban-hqrgy</a>
![picker组件样式污染](https://user-images.githubusercontent.com/20528541/60382449-c6587000-9a95-11e9-94c6-56740d2e78ca.gif)

### 描述问题
<van-picke>组件样式被污染,，.van-picker__columns必须设置为display: block才有用，如何设置为disply: flex，则 .van-picker-column 会没有宽度，即使给它设置宽度为100%也无效。这个问题好像只在我的项目中才会出现，我使用的是按需加载组件形式引入的<van-picke>组件

**Comment by chenjiahan** [comment]
<img src="https://user-images.githubusercontent.com/7237365/60408962-d4bc9e00-9bf3-11e9-9e2f-38c0641a47d1.png" width="300" >
你重复打包了两份 base 样式导致的，引入的第二份 base 文件把样式覆盖了，建议检查下打包配置
