### ISSUE TITLE
[Bug Report] mpvue中van-cell如何自定义title/value/label的样式

### ISSUE THREAD

**Issue by kongxubihai** [youzan/vant#3703]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.0.3

### Vue版本
2.6.10

### 重现链接 暂无
<a href="https://codesandbox.io" target="_blank">https://codesandbox.io</a>

### 描述问题
mpvue中van-cell 暂无发现如何自定义title/value/label的样式；需要自行去修改源码样式？

**Comment by chenjiahan** [comment]
请到小程序仓库下提问
