### ISSUE TITLE
[Bug Report] CDN 安装cell组件错位问题

### ISSUE THREAD

**Issue by starm328** [youzan/vant#3704]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.0.3

### Vue版本
2.6.10

### 重现链接
<a href="http://wjh.staff.3651it.com/shoufei/" target="_blank">http://wjh.staff.3651it.com/shoufei/</a>

### 描述问题
CND引入组件库，使用单元格组件，多条van-cell   会错位

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/461，这是模板本身的语法限制
