### ISSUE TITLE
关于 stepper 的一些建议

### ISSUE THREAD

**Issue by lswtmy** [youzan/vant#3706]
1. 希望 stepper 增加一个属性 size 来灵活控制stepper的大小，而不是只能用input-width来控制 
     input的width， 或者给几个固定的大小，比如： large、middle、small ？ 。
2. 希望 stepper 增加一个 input-color 来控制input字体的颜色。
3. 希望 stepper 增加长按快速加减功能，并且这个功能有个属性能控制是否支持长按快速加减， 目 
    前只能点一次加一次，或者直接输入数字。

**Comment by chenjiahan** [comment]
不错的建议，1 和 3 会考虑支持，2 没什么必要，直接用 css 覆盖就好

**Comment by chenjiahan** [comment]
已在 2.0.5 版本支持

**Comment by lear2012** [comment]
第二条，如果把disable-input打开，在微信web开发者工具看没问题，但是在手机ios微信里看无法覆盖颜色，总是浅灰色，就是disabled的颜色

**Comment by Michael2013518** [comment]
第三条在iOS上长按快速加减还不可以。目前使用vant 2.4.2-beta.2。只能点一次加一次，这个版本修复啦么？@chenjiahan

**Comment by chenjiahan** [comment]
@Michael2013518 长按手势是支持的

**Comment by Michael2013518** [comment]
连续点击加减，在iOS端是不会加减的吧。目前我测试是这样的，是否可以连续点击加减也可以操作？ @chenjiahan

**Comment by chenjiahan** [comment]
不太清楚你说的连续点击是什么场景，只要触发了 click 事件就会有加减操作
