### ISSUE TITLE
日期组件

### ISSUE THREAD

**Issue by SuperZhe** [youzan/vant#3713]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
日期组件，新增filter过滤方法，选中确认之后的返回结果是错误的，过滤为半小时
![image](https://user-images.githubusercontent.com/26376451/60436515-c21b8680-9c3e-11e9-9e4e-535c28b8fb5b.png)
选中之后是01分
![image](https://user-images.githubusercontent.com/26376451/60436557-d8c1dd80-9c3e-11e9-954d-b9b1870bd138.png)

**Comment by chenjiahan** [comment]
不规范的 issue
