### ISSUE TITLE
[Bug Report] Collapse 内有异步请求的时候，第一次点击导致高度不正确

### ISSUE THREAD

**Issue by bolechen** [youzan/vant#3720]
### 设备 / 浏览器
iOS 微信 7.0.4

### Vant 版本
2.0.4

### Vue版本
2.5.22

### 重现链接
<a href="https://codesandbox.io/s/collapse-bug-bk0cm?fontsize=14" target="_blank">https://codesandbox.io/s/collapse-bug-bk0cm?fontsize=14</a>

### 描述问题
Collapse 内有异步请求的时候，第一次点击导致高度不正确，收起后，第二次点击正常。参见上面的链接，用微信浏览器打开可以看到效果。

### 相关 issue
#3685 #2852 #2701

**Comment by chenjiahan** [comment]
感谢反馈，Safari 上渲染内容较多时会出现这个问题，下个版本会加一个 double raf 来解决

**Comment by chenjiahan** [comment]
已在 2.0.6 版本修复，麻烦试下
