### ISSUE TITLE
[Bug Report] 更新到2.0.5布局出错

### ISSUE THREAD

**Issue by LvJianfeng** [youzan/vant#3727]
### 设备 / 浏览器
chrome iphone x

### Vant 版本
2.0.5

### Vue版本
2.6.10

### 重现链接
<a href="http://127.0.0.1" target="_blank">http://127.0.0.1</a>

### 描述问题
Tabbar 布局出错

![image](https://user-images.githubusercontent.com/9586013/60503708-d325cf80-9cf2-11e9-9327-7df2a5220543.png)

**Comment by chenjiahan** [comment]
麻烦提供复现问题的 codesandbox 链接

**Comment by LvJianfeng** [comment]
@LvJianfeng  postcss的问题，谢谢了
