### ISSUE TITLE
Popup控件问题

### ISSUE THREAD

**Issue by yajore** [youzan/vant#373]
**What is the current behavior?**
// vant/packages/mixins/popup/index.js
```js
 遮罩层额外样式
    overlayStyle: {
      type: String,
      default: ''
    }
```
你这里和官网文档描述肯定有一个地方错了
https://www.youzanyun.com/zanui/vant#/zh-CN/component/popup
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@yajore 感谢反馈，这里应该是 Object 类型，下个版本修复

**Comment by chenjiahan** [comment]
已在 0.11.6 中修复
