### ISSUE TITLE
[Bug Report] popup 弹层内容过多，滚出弹层的时候，点击蒙版，结果弹层内部的 view 响应了点击事件

### ISSUE THREAD

**Issue by Norcy** [youzan/vant#3731]
### 设备 / 浏览器
iPhoneX

### Vant 版本
2.0.5

### Vue版本
2.6.10

### 重现链接
<a href="https://github.com/youzan/vant-weapp/issues/1664" target="_blank">https://github.com/youzan/vant-weapp/issues/1664</a>

### 描述问题
popup 弹层内容过多，滚出弹层的时候，点击蒙版，结果弹层内部的 view 响应了点击事件

**Comment by chenjiahan** [comment]
小程序的问题请到 vant-weapp 仓库下提问喔，感谢配合
