### ISSUE TITLE
[Bug Report] [Uploader] 拍照上传会刷新页面

### ISSUE THREAD

**Issue by jianyudahaoren** [youzan/vant#3732]
### 设备 / 浏览器
IOS 12/微信内置浏览器

### Vant 版本
1.6.24

### Vue版本
2.6.10

### 重现链接
没有链接可用

### 描述问题
拍照完成点击使用该照片时返回网页界面，页面会刷新，导致图片无法上传，表单内容丢失. (重现并非100%发生，是概率性发生，比较棘手)

**Comment by chenjiahan** [comment]
用官方示例试下能复现么

**Comment by jianyudahaoren** [comment]
没有办法100%的机率复现，但是我有录制一节视频在百度网盘上
链接：https://pan.baidu.com/s/1JpLv-acnYRriKQY9x0ctxA 
提取码：vuw6

**Comment by allen2001** [comment]
我们也出现了这个问题 
vant版本：1.6.9

并且部分安卓手机拍照选择图片上传后 不会进:after-read的回调 导致上传失效

**Comment by qhchen88g** [comment]
网上有说法是机身内存不足导致的刷新页面

**Comment by jianyudahaoren** [comment]
我在网上也看到了，就是手机内存的事，都两年多了都没有一个解决方案出来。不管了，估计WEB端是没有解药了，直接在上传哪里加了一小行字“如拍照上传失败请使用相册上传”

**Comment by chenjiahan** [comment]
如果是内存问题，应该暂时无解了，等硬件升级吧..

**Comment by shenguanjiejie** [comment]
我也遇到了类似这种情况, 我是 ( 第一次选择图片 && 拉伸镜头 ) 会导致刷新, 其他情况都不会刷新!
所以感觉不是简单的内存问题.
iPhone8
vant版本:2.5.5
微信内打开和手机Safari表现一致

**Comment by coderYuJie** [comment]
我们也有个别用户反馈有这个问题

**Comment by yihuan** [comment]
我把 capture 改成 user 就可以，`capture="user"`，不知道为什么官方文档里值提供了一种选项就是 `camera`。

**Comment by chenjiahan** [comment]
capture="user" 一般是指调用前置照相机，具体的行为是由系统浏览器决定的。

**Comment by yihuan** [comment]
对，但这个确实解决了我之前一直刷新的问题。不知道 Vant 里这个 camera 值是在哪儿用的，好像没找到。

**Comment by chenjiahan** [comment]
直接透传给原生的 input 标签的，没做处理

**Comment by yihuan** [comment]
但原生没有 camera 的值，不知道为什么要指定这个值。

**Comment by chenjiahan** [comment]
原生有的，只是不在 W3C 标准里了，属于浏览器自行实现的
