### ISSUE TITLE
van-icon图标错乱

### ISSUE THREAD

**Issue by BBBBBenk** [youzan/vant#3735]
1.说明
 + 通过npm安装的Vant版本1.6.11
 + 当我使用`<van-icon name="exchange" size="30px"></van-icon>`的时候出现的却是`name='points'`的图标

2.使用情景
 + ![useisu](https://user-images.githubusercontent.com/31638196/60568420-5e5c9f00-9d9f-11e9-87b5-d435334dc65d.png)

 + 图中可看到name确实是exchange

3.特殊说明
 + 只有部分name会错乱。`name=user-circle-o`又是正常的
 + 当我更改上面的content为\F024 出现了官方文档都没有的图标如下图
 + ![use2](https://user-images.githubusercontent.com/31638196/60568641-f5295b80-9d9f-11e9-9b3d-046b22b41d5a.png)

#### 请官方大佬指条明路！！

**Comment by chenjiahan** [comment]
没遇到过这个问题，建议升级版本试下

**Comment by BBBBBenk** [comment]
> 没遇到过这个问题，建议升级版本试下

升级版本会不会不兼容？

**Comment by chenjiahan** [comment]
可以升级到 1.6 的最新版，不会有不兼容更新，升级 2.0 的话需要看下更新日志里的改动
