### ISSUE TITLE
[Feature Request] IndexBar 希望新增Top字段，设置sticky的吸顶距离

### ISSUE THREAD

**Issue by q759410559** [youzan/vant#3737]
### 这个功能解决了什么问题
解决头部设置NavBar等等问题，现在手动css设置top距离会导致右侧索引字符栏点击移动距离不对应

### 描述您想要的解决方案
IndexBar 希望新增Top字段，设置sticky的吸顶距离

### 建议的API是什么样的
IndexBar 希望新增Top字段，设置sticky的吸顶距离

**Comment by chenjiahan** [comment]
后续会支持

**Comment by chenjiahan** [comment]
已在 2.0.7 版本支持
