### ISSUE TITLE
[Bug Report]datetime-picker组件有bug，只出现阴影层，内容不显示

### ISSUE THREAD

**Issue by a953043100** [youzan/vant#3738]
ios 12.3.1 
"vue": "^2.6.10",

在我的项目引用vant之后 调用datetime-picker的时候 datetime-picker并不显示 
pc端的chrome可以正常显示

<img width="457" alt="001" src="https://user-images.githubusercontent.com/8577290/60578861-8dc9d680-9db4-11e9-955e-0d8a983c0bc9.png">
![WechatIMG32714](https://user-images.githubusercontent.com/8577290/60578899-9f12e300-9db4-11e9-860d-e300bb5202fb.jpeg)

**Comment by a953043100** [comment]
<van-popup v-model="showTime" position="bottom" :overlay="true">
            <van-datetime-picker
              type="date"
              :min-date="minDate"
              :max-date="maxDate"
              @confirm="timeConfirmFn"
              @cancel="showTime = false"
            />
        </van-popup>

**Comment by chenjiahan** [comment]
不规范的 issue
