### ISSUE TITLE
Grid组件 gutter属性类型问题

### ISSUE THREAD

**Issue by skyshirt** [youzan/vant#3739]
**设备 / 浏览器**
win10 / chrome 75

**Vant 版本**
2.0.5

**Vue版本**
2.6.10

**描述问题**
Grid组件 gutter属性
文档中说明支持 String | Number
但控制台报错
`[Vue warn]: Invalid prop: type check failed for prop "gutter". Expected Number with value NaN, got String with value "1rem".`

**问题代码**
`<van-grid gutter="1rem">`

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.0.6 版本修复
