### ISSUE TITLE
[help] vant/touch-emulator + echarts，导致在手机端 echarts 的图表的点击事件触发两次

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#3740]
### 设备 / 浏览器
Chrome emulate devices iPhone6/ Mobile Browser

### Vant 版本
2.0.5

### vant/touch-emulator版本
1.0.0

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vanttouch-emulator-echarts-xfd1y" target="_blank">https://codesandbox.io/s/vanttouch-emulator-echarts-xfd1y</a>

### 复现步骤
1. 使用Chrome emulate devices iPhone6 / 手机浏览器打开网页，点击图表下方的选项；
2. 预期表现为选项变灰（即取消选择），实际表现为选项变灰后又再次变色；
3. 复现率高，在90%以上。

### 描述问题
我在`main.js`中引入了`@vant/touch-emulator`，这导致了在手机端 `echarts` 的图表的点击事件触发两次；
取消引入后，这个现象不再发生；
在PC浏览器中，这个现象也没有发生。

请问这是什么原因导致的呢？在不取消引入`@vant/touch-emulator`的前提下，有什么解决方法吗？
谢谢。

**Comment by chenjiahan** [comment]
升级 `@vant/touch-emulator@1.1.0` 版本试下，修复了手机端也会模拟事件的问题

**Comment by huangysss** [comment]
> 升级 `@vant/touch-emulator@1.1.0` 版本试下，修复了手机端也会模拟事件的问题

升级到`@vant/touch-emulator@1.1.0`后，问题得到解决。谢谢！
