### ISSUE TITLE
[Bug Report] van-uploader手机拍照后，图片旋转

### ISSUE THREAD

**Issue by lilw1020** [youzan/vant#3744]
### 设备 / 浏览器
安卓手机（三星，小米）

### Vant 版本
2.0.5

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-39trm" target="_blank">https://codesandbox.io/s/vant-issue-moban-39trm</a>

### 描述问题
app开发中有个拍照并上传的功能，利用了van-uploader组件，部分安卓手机（小米8）在拍照后预览回显时，照片被逆时针旋转了90度。请问有解决方案或者相应的思路吗？

**Comment by huangysss** [comment]
#2332

**Comment by lilw1020** [comment]
> #2332
> 
> > Uploader 里面嵌套的是原生的 input type="file"，所以这个问题是原生 input 框导致的，建议去网上查下解决方法，比如 https://zhuanlan.zhihu.com/p/27627436

这些方案我都已经看过了，还是希望官方能提供一个图片编辑的窗口，可以裁剪和编辑图片。

**Comment by chenjiahan** [comment]
暂时没有计划提供图片编辑功能

**Comment by lilw1020** [comment]
> 暂时没有计划提供图片编辑功能

谢谢回复
