### ISSUE TITLE
自定义组件无法转rem

### ISSUE THREAD

**Issue by pangangludd01** [youzan/vant#3745]
场景：
项目使用postcss-pxtorem
但自定义组件的单位无法自动转rem

**Comment by lilw1020** [comment]
这问题我也遇到了，感觉pxtorem不太好使，我是用的官方示例里的pxtoviewport做适配的，挺好用。

**Comment by chenjiahan** [comment]
2.0.4 版本可能会碰到这个问题，建议升级到 2.0.5 试下

**Comment by pangangludd01** [comment]
感谢回复，pxtoviewport方案确实能解决问题。

**Comment by shen-lan** [comment]
pxtoviewport  方案demo链接有吗
