### ISSUE TITLE
van-popup优惠券有效期建议加个属性控制是否显示时分秒，再者这个文字（有效期）建议可以修改

### ISSUE THREAD

**Issue by WuYiZhan** [youzan/vant#3748]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持喔
