### ISSUE TITLE
[Bug Report] PullRefresh在iOS上下拉的时候经常出现滑动整个页面

### ISSUE THREAD

**Issue by xiaoyueguang** [youzan/vant#3749]
设备 / 浏览器
iOS12.3.1 safari
iOS12.3.1 微信

Vant 版本
2.0.2

Vue版本
2.6.10

重现链接
vant官方list组件
https://youzan.github.io/vant/mobile.html#/zh-CN/list

![00EBE3E47969C4702B565F7BFB9AE658](https://user-images.githubusercontent.com/15521648/60645766-325b1f80-9e6c-11e9-992c-f6b1ef0931c6.gif)

**Comment by chenjiahan** [comment]
这个是 iOS 系统本身的滚动回弹效果，你要等回弹停止后再滑动

**Comment by xiaoyueguang** [comment]
> 这个是 iOS 系统本身的滚动回弹效果，你要等回弹停止后再滑动

明白. 但是用户不会管这个, 用户只会觉得, 我这样滑动一下, 没法继续滑动了. 会很难受...

我觉得可以参考一下 better-scroll 或 iscroll 的方案

**Comment by chenjiahan** [comment]
better-scroll 或 iscroll 是完全放弃原生滚动的方案，不适用 Vant

**Comment by xiaoyueguang** [comment]
> better-scroll 或 iscroll 是完全放弃原生滚动的方案，不适用 Vant

按理说一个UI框架, 不应该是考虑的用户的使用舒适度以及开发者调用的易用性么?
原生的滚动方案, 对用户使用来说, 在下拉这一方面其实是比较蛋疼的.

**Comment by chenjiahan** [comment]
大部分项目都在使用原生滚动，我们不能为了解决某个不核心的问题而强制让所有使用者都依赖类似 better-scroll or iScroll 的方案

另外我不认为 better-scroll or iScroll 在体验上会更好，下面是我的个人看法：

1. 滚动的手感会和原生体验不一致
2. 滚动回弹不自然
3. 干扰了 touch、click 等事件触发的机制
4. 样式更新和计算带来的性能损耗

**Comment by xiaoyueguang** [comment]
> 大部分项目都在使用原生滚动，我们不能为了解决某个不核心的问题而强制让所有使用者都依赖类似 better-scroll or iScroll 的方案
> 
> 另外我不认为 better-scroll or iScroll 在体验上会更好，下面是我的个人看法：
> 
> 1. 滚动的手感会和原生体验不一致
> 2. 滚动回弹不自然
> 3. 干扰了 touch、click 等事件触发的机制

嗯好. 明白了你们的考虑点了. 既然如此, 那我就关闭掉这个ISSUE吧.
感谢解答😁

**Comment by chenjiahan** [comment]
嗯嗯，客气啦
