### ISSUE TITLE
[Bug Report] SKU商品规格在切换属性时不能切换图片，有示例

### ISSUE THREAD

**Issue by cnlinjie** [youzan/vant#3754]
### 设备 / 浏览器
所有设备

### Vant 版本
2.0.5

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-22x3d" target="_blank">https://codesandbox.io/s/vant-issue-moban-22x3d</a>

### 描述问题
SKU商品规格在切换属性时不能切换图片
属性中有填写图片了，就是切换不了，奇怪。
重现代码:
https://codesandbox.io/s/vant-issue-moban-22x3d
预览:
https://22x3d.codesandbox.io/

**Comment by cnlinjie** [comment]
这个问题有人回复么

**Comment by chenjiahan** [comment]
数据格式错了，请按文档中描述的格式组织数据结构，

像`sellAttr_1552889853362`这些字段是不存在的，要提供`s1` `s2` 等

**Comment by cnlinjie** [comment]
好，我以为是通过"k_s" 这个参数指定属性值，原来是固定的，谢谢了。
