### ISSUE TITLE
DropdownMenu的向上箭头显示问题

### ISSUE THREAD

**Issue by WongYuYe** [youzan/vant#3757]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.
如下图
https://youzan.github.io/vant-issue-generater
![image](https://user-images.githubusercontent.com/23697313/60694827-15792780-9f12-11e9-996b-8759d59928bf.png)

**Comment by chenjiahan** [comment]
不规范的 issue
