### ISSUE TITLE
[Bug Report] vant中使用van-datetime-picker年月日组件在ios中无法正常显示

### ISSUE THREAD

**Issue by zhihaogood** [youzan/vant#3758]
### 设备 / 浏览器
ios手机都没有显示安卓能正常使用

### Vant 版本
2.0.5

### Vue版本
2.6.10

### 重现链接
<a href="http://datawisdom4.tmallok.cn/member/member_index.aspx" target="_blank">http://datawisdom4.tmallok.cn/member/member_index.aspx</a>

### 描述问题
进去链接以后点头像  里面的生日选择  在使用van-datetime-picker组件的时候 页面上能正常显示安卓手机上也能正常显示只有ios上弹出一个遮罩层没有弹出年月日的显示....

**Comment by HUGY1** [comment]
请问解决了吗？什么问题
