### ISSUE TITLE
Have a issue in NavBar document

### ISSUE THREAD

**Issue by yurizhang** [youzan/vant#376]
![image](https://user-images.githubusercontent.com/20555332/33546942-617b9620-d91d-11e7-86d1-72c39bcc18fc.png)

Here, @click-left="onClickLeft"  is a error, It should be @click.native="onClickLeft"

` <van-nav-bar title="我的首付出发" leftArrow leftText="返回"  @click.native="sayYes()">`

**Comment by yurizhang** [comment]
用@click-left是不对的，修改成@click.native 就可以了~

**Comment by chenjiahan** [comment]
@yurizhang @click-left 是监听左侧区域的点击事件，@click.native 是监听整个 NavBar 的点击事件，两者是有区别的噢

**Comment by yurizhang** [comment]
我的是0.11.2好像,@click-left不起作用,我明天发下代码 ~

**Comment by chenjiahan** [comment]
@yurizhang 嗯嗯，需要升级到 0.11.3+

**Comment by yurizhang** [comment]
是你们修复了吧,哈哈
我目前的项目里在用你们的这个.

**Comment by chenjiahan** [comment]
是在后来修复的哈，欢迎提出更多意见😆

**Comment by yurizhang** [comment]
为了这个我花了一个小时,查看了你们的源码,并没有 left 和  right, 我只能用@click了.
我目前也在写这样的类库iShow,不过我是用React.

我目前在处理webview加载这个的性能,后面我生成一个报告发给你们.
你们继续加油~~单元测试一定要覆盖全哈哈~

**Comment by chenjiahan** [comment]
源码里是有滴，在 packages/nav-bar/index.vue 文件下
单元测试的话我们会尽量保证~
