### ISSUE TITLE
[Feature Request] 「国际化」部分组件存在中文硬编码提示，在国际化方面能否支持

### ISSUE THREAD

**Issue by cnlinjie** [youzan/vant#3760]
### 这个功能解决了什么问题
 「国际化」方面，比如目前使用的SKU组件提示，诸多硬编码：“请先选择商品规格'”，“商品已经无法购买啦”，“库存不足”，“限购xx件”，“至少选择一件'”，等等，我理解开源方面的辛苦工作，如果有需要，我尝试提交PR ，感谢。

### 描述您想要的解决方案
i18n 国际化

### 建议的API是什么样的
i18n 国际化

![image](https://user-images.githubusercontent.com/3601638/60696780-cd5e0300-9f19-11e9-9efc-23b5548e1ec8.png)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/2913

**Comment by cnlinjie** [comment]
@chenjiahan  谢谢，我需要怎么处理这些非国际化的组件呢

**Comment by chenjiahan** [comment]
目前只能手动改这个组件的源码，后续我们会研究下有没有其他方式能解决

**Comment by chenjiahan** [comment]
已在 2.1.3 版本支持国际化，默认提供了中文的文案，其他语言可以自行配置

**Comment by ydcode** [comment]
非常感谢开源和持续完善这么优秀顶尖的组件库 🥇  ，谢谢~~~

已看到2.1.3版本国际化语言完善，
vant/src/sku/Sku.js  有部分中文硬编码待修改, 

例如: 
> 选择
> 商品已经无法购买啦
> 请先选择商品规格
> ...


再次致敬  👍

**Comment by y1324** [comment]
请问，我通过文档上修改中文提示，提示的还是原来的“请先选择商品规格”

const messages = {
  'zh-CN': {
    vanSku: {
      selectSku: '123123'
    }
  }
}

Locale.add(messages)

**Comment by y1324** [comment]
> 请问，我通过文档上修改中文提示，提示的还是原来的“请先选择商品规格”
> 
> const messages = {
> 'zh-CN': {
> vanSku: {
> selectSku: '123123'
> }
> }
> }
> 
> Locale.add(messages)

这个得需要在组件用地方修改吗？我在main中修改没生效，在用组件的页面修改?
