### ISSUE TITLE
[Bug Report] vant2.0.1版本。uploader组件before-read不支持Promise等情况

### ISSUE THREAD

**Issue by CheiZhei** [youzan/vant#3761]
### 设备 / 浏览器
all

### Vant 版本
2.0.1

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-vell7" target="_blank">https://codesandbox.io/s/vant-issue-moban-vell7</a>

### 描述问题
返回Promise.reject列表依然会加入，我看了一下源码，确实没有对Promise做过处理，是不是2.0.1不支持啊

**Comment by chenjiahan** [comment]
是呀，可以看更新日志

**Comment by CheiZhei** [comment]
好的。谢谢
