### ISSUE TITLE
Notice-Bar 的滚动内容可不可以是 v-html?

### ISSUE THREAD

**Issue by Cifer-Y** [youzan/vant#3763]
### 设备 / 浏览器
所有

### Vant 版本
2.0.5

### Vue版本
2.6.10

### 重现链接
无

### 描述问题
Notice-Bar 的内容是纯文字的时候没有任何问题, 但是我想滚动的内容是从服务器拿到的 html 文本, 我开始看到 notice-bar 有插槽, 所以我就写了 `<div v-html="xxx"></div> `,  但是用了 v-html 之后, 文字就不会滚动了, 请问我是否可以在 Notice-Bar 里使用 v-html 作为滚动内容呢?

**Comment by chenjiahan** [comment]
为啥不用插槽呢

**Comment by Cifer-Y** [comment]
@chenjiahan 我刚才尝试复现一下我遇到的问题, 发现是可以用你这种写法的, 我一开始也是用的这种写法, 不过我像你这样写的话内容无法滚动, 可能是因为我用了 better-scroll, 全局禁用滚动,然后在需要加滚动的地方加, 才导致这个问题....

**Comment by chenjiahan** [comment]
噢噢，明白啦
