### ISSUE TITLE
[Bug Report] 目录名字不对应

### ISSUE THREAD

**Issue by LOADINGG** [youzan/vant#3769]
### 设备 / 浏览器
chrome

### Vant 版本
2.0.6

### Vue版本
2.5.20

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?type=Bug" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?type=Bug</a>

### 描述问题
npm i vant -S 安装vant后文件目录 D:\VUE\yygh\node_modules\vant\es\action-sheet

npm run dev 报错 To install them, you can run: npm install --save vant/es/actionsheet vant/es/actionsheet/style

安装和引入名字不一致  引入vant方式babel-plugin-import

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3364
