### ISSUE TITLE
Popup组件滑动问题

### ISSUE THREAD

**Issue by ztplz** [youzan/vant#377]
**What is the current behavior?**
我在项目里用了Popup这个组件做弹框，弹框里面内容很多，超出了显示范围，我发现我没法滑动看到超出屏幕的部分，我能看到侧滑栏，但是我没办法滑动
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**
怎么样才可以滑动popup
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
谢谢！

**Comment by yurizhang** [comment]
在你的内容外加一个div，设置好max高度,然后 overflow-y:scroll 这样就可以了~

**Comment by chenjiahan** [comment]
楼上为正解，完整样式如下：
```css
max-height: 100%;
overflow-y: auto;
-webkit-overflow-scrolling: touch;
```

**Comment by ztplz** [comment]
@yurizhang  @chenjiahan     已顺利解决  非常感谢
