### ISSUE TITLE
[Bug Report] Field 输入框同时添加click，click-right-icon事件Bug

### ISSUE THREAD

**Issue by jasconchen** [youzan/vant#3770]
### 设备 / 浏览器
Chrome

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://isder.codesandbox.io/" target="_blank">https://isder.codesandbox.io/</a>

### 描述问题
1.同时添加click，click-right-icon事件
2.点击右侧icon的时候，先click-right-icon事件，再触发click事件
期望：
点击右侧icon不会触发click事件

**Comment by chenjiahan** [comment]
嗯，确实是不触发 click 比较合理，下个版本会修复

**Comment by huangysss** [comment]
> 嗯，确实是不触发 click 比较合理，下个版本会修复

这样改的话有个疑惑。
如果 Field 中的 right-icon 只是起到装饰作用，这样点击 right-icon 就不会触发 click  事件。
用 stop 修饰是否会好一点。

**Comment by chenjiahan** [comment]
用 stop 修饰符具体是指什么样的写法嘞

**Comment by huangysss** [comment]
```
<van-field @click-right-icon.stop="event" />
```

**Comment by chenjiahan** [comment]
喔我脑抽了。。用 modifiers 确实是更灵活的方式

@jasconchen 可以看下上面的写法，组件内还是不做处理更好

**Comment by jasconchen** [comment]
加了修饰符会报错

**Comment by chenjiahan** [comment]
下个版本会支持加修饰符，当前版本会报错

**Comment by jasconchen** [comment]
好的，谢谢

**Comment by chenjiahan** [comment]
已在 2.0.7 版本修复
