### ISSUE TITLE
[Bug Report] dropdown-item  position: fixed

### ISSUE THREAD

**Issue by vok123** [youzan/vant#3771]
### 设备 / 浏览器
任意浏览器

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://fb91o.codesandbox.io/" target="_blank">https://fb91o.codesandbox.io/</a>

### 描述问题
滑动之后, 下拉菜单定位位置出现问题

**Comment by chenjiahan** [comment]
这个问题是 better-scroll 导致的，他会在外层添加 transform 样式，导致内部的 fixed 定位失效

建议不要嵌套在 better-scroll 内使用

**Comment by vok123** [comment]
可否将节点移动到body?

**Comment by chenjiahan** [comment]
暂时做不了哈，移动节点会导致渲染有问题
