### ISSUE TITLE
IndexBar 在Popup弹出层中使用时，滚动时 索引和列表对应不上

### ISSUE THREAD

**Issue by shouwangshe** [youzan/vant#3773]
IndexBar 在Popup弹出层中使用时，开了sticky滚动时 索引和列表对应不上。不开sticky，索引不回有样式高亮。感觉在popup里面就都不太好使了。除了点击索引跳转对应位置是好使的。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
