### ISSUE TITLE
[Bug Report] NoticeBar 组件 @click.stop,@close.stop无法使用

### ISSUE THREAD

**Issue by woniu99** [youzan/vant#3777]
### 设备 / 浏览器
chrome69

### Vant 版本
2.0.5

### Vue版本
2.6.9

### 重现链接
<a href="https://www.baidu.om?无法提供" target="_blank">https://www.baidu.om?无法提供</a>

### 描述问题
NoticeBar 组件的点击事件无法使用.stop阻止事件冒泡

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.0.7 版本修复
