### ISSUE TITLE
求助，全局引用vant使用下拉菜单组件报错

### ISSUE THREAD

**Issue by BrokenSmoke** [youzan/vant#3779]
[Vue warn]: Unknown custom element: <van-dropdown-menu> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

[Vue warn]: Unknown custom element: <van-dropdown-item> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by chenjiahan** [comment]
确认下是不是引用了 2.0 版本的 vant，这个组件是新加的

**Comment by BrokenSmoke** [comment]
非常感谢，我是老项目一直用的，还是1.**版本，非常感谢 
------------------


 顺祝身体健康
      工作愉快！
  
 刘伯琛
  
天津金硕信息科技集团股份有限公司
   天津市南开区红旗南路251号新华园大厦9楼 

 手机：15102235016
邮编：300191


 




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年7月8日(星期一) 下午4:54
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "刘伯琛"<395478543@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] 求助，全局引用vant使用下拉菜单组件报错 (#3779)




确认下是不是引用了 2.0 版本的 vant，这个组件是新加的

**Comment by chenjiahan** [comment]
客气哈
