### ISSUE TITLE
[Feature Request] van-tag 颜色不能通过样式覆盖解决

### ISSUE THREAD

**Issue by pearlwang1106** [youzan/vant#3783]
### 这个功能解决了什么问题
个人理解 van-tag 的type 就是控制不同颜色的，可是颜色的实现竟然是通过dom的style属性实现，同时标枪上面不同type 的dom没有class标识出，非常不方便开发中样式覆盖

### 描述您想要的解决方案
建议不同 type 的dom 有不同的class，方便开发中整体样式的自定义覆盖

### 建议的API是什么样的
van-tag--primary 之类的

**Comment by chenjiahan** [comment]
👌下个版本会优化

**Comment by chenjiahan** [comment]
已在 2.0.7 版本优化
