### ISSUE TITLE
现在不能看demo源码了么

### ISSUE THREAD

**Issue by HuiGan-M** [youzan/vant#3785]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以直接打开源码目录看喔

https://github.com/youzan/vant/tree/dev/src
