### ISSUE TITLE
2.0.5版本dialog中加的closeOnPopstate在ts中没有定义type，会报错

### ISSUE THREAD

**Issue by GKLL** [youzan/vant#3786]
在ts中closeOnPopstate报argument of type '{ message: string; closeOnPopstate: boolean; }' is not assignable to parameter of type 'DialogOptions'.
  Object literal may only specify known properties, and 'closeOnPopstate' does not exist in type 'DialogOptions'.没有定义

**Comment by chenjiahan** [comment]
重复 issue https://github.com/youzan/vant/issues/3787
