### ISSUE TITLE
[Bug Report] 2.0.5版本dialog新加的closeOnPopstate在ts中使用报错

### ISSUE THREAD

**Issue by GKLL** [youzan/vant#3787]
### 设备 / 浏览器
ios

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.com" target="_blank">https://youzan.com</a>

### 描述问题
在ts中closeOnPopstate报argument of type '{ message: string; closeOnPopstate: boolean; }' is not assignable to parameter of type 'DialogOptions'.
  Object literal may only specify known properties, and 'closeOnPopstate' does not exist in type 'DialogOptions'.没有定义

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.0.7 版本修复
