### ISSUE TITLE
关于图片懒加载插槽使用

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#3792]
![image](https://user-images.githubusercontent.com/42930030/60871489-7338a700-a265-11e9-8c3c-9fb77ea57fdd.png)
这种写法是不是已经摒弃了，都提示警告了，
![image](https://user-images.githubusercontent.com/42930030/60871617-aed37100-a265-11e9-8f1b-d6a202059be1.png)
我使用 这种写法之后没出现加载动画，出现的默认的加载中静态图片，是我的写法问题吗？

**Comment by chenjiahan** [comment]
v-slot 的写法在 Vue 2.6 版本开始支持喔
