### ISSUE TITLE
[Bug Report] 在tab标签页下，van-tab内容中html元素添加点击事件无效

### ISSUE THREAD

**Issue by LiuQiangA** [youzan/vant#3796]
### 设备 / 浏览器
IOS和安卓

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/m5v3f" target="_blank">https://codesandbox.io/s/m5v3f</a>

### 描述问题
在tab标签页下，van-tab内容中html元素添加点击事件无效

**Comment by chenjiahan** [comment]
无效的复现链接
