### ISSUE TITLE
[Bug Report] ActionSheet组件在iPhone中的问题

### ISSUE THREAD

**Issue by 941477276** [youzan/vant#3797]
### 设备 / 浏览器
iPhone(12.1.4)

### Vant 版本
2.0.3

### Vue版本
2.6.10

### 重现链接
真机无法重新
**bug重新GIF图片**
[重现gif视频.zip](https://github.com/youzan/vant/files/3373638/gif.zip)

### 描述问题
ActionSheet组件在iPhone中第一次显示时会出现遮罩层先出现，ActionSheet再出现的bug，隐藏ActionSheet再次打开就很正常了

**Comment by chenjiahan** [comment]
已在 2.0.7 版本修复

**Comment by 941477276** [comment]
这个问题貌似并未修复，我现在用的版本时2.0.9(2.0.7版本也用了)，在iPhone中打开依然有这个问题，安卓上是没有问题的
[bug重现视频.zip](https://github.com/youzan/vant/files/3426860/bug.zip)

**Comment by chenjiahan** [comment]
下个版本会优化下设置 zIndex 的顺序，应该能避免这个问题

**Comment by chenjiahan** [comment]
已在 2.1.1 版本修复
