### ISSUE TITLE
[Feature Request] SwipeCell 可固定非滑动区域

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#3798]
### 这个功能解决了什么问题
```
<van-swipe-cell>
  <van-cell
    :border="false"
    title="单元格"
    value="内容"
  />
  <van-button
    slot="right"
    type="danger"
    text="删除"
  />
</van-swipe-cell>
```
左滑后仅```van-button```左移，```van-cell```固定，如图：
![企业微信截图_15627270232760](https://user-images.githubusercontent.com/31810070/60936721-a11ef980-a300-11e9-93ee-4e165cd56e1f.png)

### 描述您想要的解决方案
提供一个prop选择是否固定。

### 建议的API是什么样的
```
<van-swipe-cell no-move>
    ...
</van-swipe-cell>
```

**Comment by chenjiahan** [comment]
暂无计划支持这样的交互效果
