### ISSUE TITLE
Swipe轮播的 swipeTo 方法，建议增加一个不使用动画的参数

### ISSUE THREAD

**Issue by anrananran** [youzan/vant#3799]
需求是结合tab做了一个viewPager组件，如果tab过多，切换tab时swipe动画会非常快的划过，体验不好

**Comment by chenjiahan** [comment]
下个版本支持

**Comment by chenjiahan** [comment]
已在 2.0.7 版本支持

**Comment by niconicoZ** [comment]
现在2.07以下的版本的 swipeTo无法使用了

**Comment by niconicoZ** [comment]
this.$refs.swipe.swipeTo is not a function @chenjiahan

**Comment by chenjiahan** [comment]
@niconicoZ  Vue 中，refs 必须在 mounted 之后获取，建议你确认下组件是否已 mounted

**Comment by yibhou** [comment]
@chenjiahan `this.$refs.swipe.swipeTo(index, { immediate: true })` 还是会使用动画，是我用错了么，版本是最新的2.2.2

**Comment by chenjiahan** [comment]
@yibhou 可以提 issue，附上复现 codesandbox 链接
