### ISSUE TITLE
关于van-tabs绑定默认值问题

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#3801]
![image](https://user-images.githubusercontent.com/42930030/60948382-6085a700-a325-11e9-8112-41c96d8bc674.png)
点击餐单跳转到列表页，我是使用query传值
![image](https://user-images.githubusercontent.com/42930030/60948417-73987700-a325-11e9-9985-227368f264d8.png)
![image](https://user-images.githubusercontent.com/42930030/60948539-afcbd780-a325-11e9-9e29-10c4709b1164.png)

进来后页面是正常的，默认选中也是正常，但是刷新后就变成选中第一个了
![image](https://user-images.githubusercontent.com/42930030/60948566-c4a86b00-a325-11e9-8375-1add4c0d91ca.png)
关于默认值activeName的赋值和绑定 如下
![image](https://user-images.githubusercontent.com/42930030/60948617-e1dd3980-a325-11e9-9199-b89deec7f2f3.png)
![image](https://user-images.githubusercontent.com/42930030/60948628-f1f51900-a325-11e9-8dd6-376beaf7ac0e.png)
这算是bug吗？

**Comment by cangyu1993** [comment]
ok，解决了
![image](https://user-images.githubusercontent.com/42930030/60949473-e0147580-a327-11e9-9886-973c61ea75f3.png)
我在请求成功回调中通过index去设置 默认值，去掉了标签中的name刷新正常了，可是我第一种方法怎么会刷新之后失效呢

**Comment by chenjiahan** [comment]
query 中取到的值是 String 类型的，目测是类型和 name 没匹配
