### ISSUE TITLE
[Bug Report] 关于ImagePreview图片预览的支持问题

### ISSUE THREAD

**Issue by 15002076027** [youzan/vant#3803]
### 设备 / 浏览器
pc 360chrome

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
很喜欢vant组件，但是经常在pc web项目上做，请问ImagePreview图片预览组件，是否能支持鼠标点击和拖动呢？

**Comment by chenjiahan** [comment]
参见快速上手的最后一章

https://youzan.github.io/vant/#/zh-CN/quickstart
