### ISSUE TITLE
[Bug Report] van-dropdown-menu 和 popup混用问题

### ISSUE THREAD

**Issue by mengfairy** [youzan/vant#3806]
### 设备 / 浏览器
iphone 6s / safari & 微信内置浏览器

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-0s1qi" target="_blank">https://codesandbox.io/s/vant-issue-moban-0s1qi</a>

### 描述问题
van-dropdown-menu 和 popup混用使用，并设置 popup 挂载到body下，点击picker 取消 或 确认 关闭弹框时，van-dropdown-menu也会被关闭。pc和手机 都能复现

不设置 popup 挂载到body下，不会有这个问题，但是在手机端上，popup 内 picker  显示不完整，这个只有手机能复现

**Comment by chenjiahan** [comment]
Popup 被挂载到 body 下面后，会被视为菜单的外部元素，目前 DropdownMenu 在点击外部元素时，默认会关闭菜单，

下个版本会加个`close-on-click-outside`属性来控制此行为

**Comment by chenjiahan** [comment]
已在 2.0.7 版本添加

**Comment by NEWDSA** [comment]
DropdownMenu中增加，close-on-click-outside 也无效。
