### ISSUE TITLE
[Feature Request] PullRefresh 里的 Events 可否支持 下拉过程(@pulling)的方法 

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#3807]
### 这个功能解决了什么问题
可以在下拉过程拿到下拉高度在值，来做更多的事情

### 描述您想要的解决方案
PullRefresh 里的 Events 支持 pulling 方法 

### 建议的API是什么样的
@pulling

**Comment by chenjiahan** [comment]
具体是要用来实现什么样的效果嘞

**Comment by anihCevol** [comment]
拿到下拉高度的值，可以在自定义 slot =" pulling"  根据这个值，做动画效果之类的事情。（只是个建议，如过感觉没必要，请忽略）

**Comment by chenjiahan** [comment]
这个用 scoped-slot 参数来实现更加合适，下个版本会支持

**Comment by anihCevol** [comment]
好哒
