### ISSUE TITLE
building打包失败

### ISSUE THREAD

**Issue by IceCoCo** [youzan/vant#3808]
执行building命令，打包失败     $van-doc-simulator-width + $van-doc-padding
---
> node build/build.js

Error processing file: static/css/app.e7f7134e48c44e408a4092602bd8ec27.css
(node:18308) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: $van-doc-simulator-width + $van-doc-padding
^..^
(node:18308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by IceCoCo** [comment]
![image](https://user-images.githubusercontent.com/12823089/60961444-c03c7c00-a33e-11e9-8c24-a8fbb3aaa4aa.png)

**Comment by chenjiahan** [comment]
你这是引用的啥？ vant-doc 吗
