### ISSUE TITLE
SwipeItem平铺在swipe中，并将页面宽度扩大到swipeitem数量倍数

### ISSUE THREAD

**Issue by xukun1213** [youzan/vant#3809]
![image](https://user-images.githubusercontent.com/18310156/60962142-37264480-a340-11e9-89e0-e6cfce7b522c.png)

整个页面被Swipe给加宽了，Swipe中SwipeItem呈现平铺的状况

![image](https://user-images.githubusercontent.com/18310156/60962275-79e81c80-a340-11e9-8a32-98c133a3df89.png)

    <div class="van-hairline--bottom">PK榜</div>
    <div class="content">
      <swipe indicator-color="blue">
        <SwipeItem v-for="(item,index) in ranks" :key="index">
          <PkContent v-bind:rank="item" />
        </SwipeItem>
      </swipe>
    </div>

.content {
  width: 100%;
  height: 200px;
}

PKContent是一个组件

**Comment by xukun1213** [comment]
如果Swipe中有一个SwipeItem的时候页面是正常的。
如果多家一个SwipeItem页面就会变宽一倍

**Comment by chenjiahan** [comment]
未复现此问题，请提供复现链接

**Comment by iamkun** [comment]
1.6.14 遇到了同样的问题

**Comment by chenjiahan** [comment]
没复现的链接的话先 close 了，建议检查下是不是项目里全局样式干扰了
