### ISSUE TITLE
[Feature Request] 组件滚动体验优化

### ISSUE THREAD

**Issue by pearlwang1106** [youzan/vant#3810]
### 这个功能解决了什么问题
在真机上看，组件中有滚动的地方似乎都不太顺畅，比如 List ,DatetimePicker等

### 描述您想要的解决方案
建议添加样式 -webkit-overflow-scrolling: touch 提升用户体验

### 建议的API是什么样的
暂无

**Comment by chenjiahan** [comment]
List 里面没有局部滚动，所以不需要加，如果是使用者自己设置的局部滚动，可以自行添加

Picker 和 DatetimePicker 是模拟实现的滚动，这个属性是没用的，在 2.0 版本我们已经对 Picker 的滚动动画做了优化

**Comment by pearlwang1106** [comment]
好的，谢谢

**Comment by cangyu1993** [comment]
页顶使用tab切换（使用粘性布局），tab的content内是list，list中我使用了better-scroll，但是貌似两者不能共存，页面直接不能滑动，有考虑使用better-scroll优化滚动吗？就行使用v-lazy优化图片

**Comment by chenjiahan** [comment]
@cangyu1993 参见 https://github.com/youzan/vant/issues/3749
