### ISSUE TITLE
Field建议增加字数显示

### ISSUE THREAD

**Issue by zhangfei8080** [youzan/vant#3813]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater
---

建议在输入框增加字数限制 像element-ui一样显示限制多少个字符,已输入多少个字符
如在右下角显示 0/10

谢谢!

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
