### ISSUE TITLE
[Feature Request] toast 不能支持自己的 iconfont

### ISSUE THREAD

**Issue by pearlwang1106** [youzan/vant#3817]
### 这个功能解决了什么问题
toast 不能支持自己的 iconfont

### 描述您想要的解决方案
this.$toast({
    message: '已收藏',
    icon: 'my-icon',
});

希望可以通过这样使用，来使用自己的iconfont

### 建议的API是什么样的
暂无

**Comment by chenjiahan** [comment]
下个版本会加个 `iconPrefix` 的选项，用法和 Icon 组件的 `class-prefix` 一致，用来显示自定义的 iconfont

**Comment by chenjiahan** [comment]
已在 2.0.9 版本支持
