### ISSUE TITLE
[Feature Request] dropdownitem的options支持icon

### ISSUE THREAD

**Issue by willardwang** [youzan/vant#3818]
### 这个功能解决了什么问题
使选项更加形象化

### 描述您想要的解决方案
展示options的popup能够显示icon，如果选中以后的文字也能展示icon就更好了

### 建议的API是什么样的
options的格式改为：
Options: [
                    {text: '全部类型', value: "",icon:''},
                    {text: '发票', value: "invoice",icon:''},
                    {text: '火车票', value: "train",icon:''},
                    {text: '飞机票', value: "plane",icon:''},
                    {text: '其他', value: "manual",icon:''}
                ]

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 2.0.8 版本支持

**Comment by willardwang** [comment]
我这边不好使，确认更新到2.0.8了。
vant的package.json
"_from": "vant@2.0.8",
  "_id": "vant@2.0.8",
  "_inBundle": false,
  "_integrity": "sha1-K8Dcaf1MqjxqWMnCP1S3BGcK64s=",
  "_location": "/vant",
  "_phantomChildren": {
    "regenerator-runtime": "0.13.2"
  }
options的写法有问题吗：
invoiceTypeOptions: [
                    {text: '全部类型', value: "", icon: 'http://localhost:8078/portal/console/images/logo.png'},
                    {text: '发票', value: "invoice", icon: 'https://b.yzcdn.cn/vant/icon-demo-1126.png'},
                    {text: '火车票', value: "train", icon: 'like-o'},
                    {text: '飞机票', value: "plane", icon: 'like-o'},
                    {text: '其他', value: "manual", icon: 'like-o'}
                ]

**Comment by chenjiahan** [comment]
看起来没啥问题，能提供一下复现链接吗

**Comment by willardwang** [comment]
看看能访问吗
https://wangyuanyou.com/dist/invoice.html

**Comment by chenjiahan** [comment]
看了下，你的 vant 版本不对，不是 2.0.8，建议重新安装下最新版

**Comment by willardwang** [comment]
> 看了下，你的 vant 版本不对，不是 2.0.8，建议重新安装下最新版
原来是升级到vant2.0.8，试了试卸载重新安装可以了，非常感谢。
