### ISSUE TITLE
[Bug Report] Dialog组件方式调用，打开动画闪烁

### ISSUE THREAD

**Issue by 2015CbWithMe** [youzan/vant#3819]
### 设备 / 浏览器
IOS，ANDROID,微信浏览器

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io" target="_blank">https://youzan.github.io</a>

### 描述问题
使用van-list生成列表，点击某个列表项时弹出dialog，弹出动画不是平滑弹出，有闪烁，在安卓和ios上的微信浏览器同是如此，视觉上非常难受

**Comment by 2015CbWithMe** [comment]
问题出在我自己的样式表中

**Comment by 2015CbWithMe** [comment]
`   <van-list
                                  v-model="loading"
                                  :finished="finished"
                                  finished-text="没有更多了"
                                  @load="onLoad">
                                  <transition-group name="slide-fade" tag="van-row">
                                    <van-row  class="verItem" @click.native='handledialog(item)' v-for="(item,index) in list" :key="item">
                                        {{item.reqtime}}
                                        
                                    </van-row>
                                   </transition-group> 
                                  </van-list>`
发现问题是列表加载新元素时，添加了过渡动画，就会导致闪烁。

**Comment by 2015CbWithMe** [comment]
> 
           <van-list  v-model="loading"  :finished="finished"  finished-text="没有更多了" @load="onLoad">
                      <transition-group name="slide-fade" tag="van-row">
                                <van-row  class="verItem" @click.native='handledialog(item)' v-for=" 
                                       (item,index) in list" :key="item">

                                       {{item.reqtime}}
                                        
                                 </van-row>
                        </transition-group> 
            </van-list>

**Comment by chenjiahan** [comment]
使用 get-container 属性将 Dialog 挂载到 body 下即可

get-container 的用法参见 https://youzan.github.io/vant/#/zh-CN/popup

**Comment by 2015CbWithMe** [comment]
> 使用 get-container 属性将 Dialog 挂载到 body 下即可
> 
> get-container 的用法参见 https://youzan.github.io/vant/#/zh-CN/popup

试过了，但还是不行，我的布局是 van-tabs>van-pullrefresh>van-tab>van-list>transition-group>循环的元素
只有去掉transition-group 才没有问题

**Comment by chenjiahan** [comment]
理论上添加 get-container 是可以避免被父元素的动画干扰的，能提供复现的 codesandbox 链接不

**Comment by 2015CbWithMe** [comment]
> 理论上添加 get-container 是可以避免被父元素的动画干扰的，能提供复现的 codesandbox 链接不

https://codesandbox.io/s/vue-template-cgri9 代码就是这样，在手机上运行

**Comment by 2015CbWithMe** [comment]
问题已解决 @chenjiahan
