### ISSUE TITLE
[need help] list 滚动时如何保持 同级别的控件不滚动

### ISSUE THREAD

**Issue by dong136279559** [youzan/vant#3826]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

设备 / 浏览器

iphone6

Vant 版本

2.0.6

Vue版本

2.6.9

重现链接

问题描述就清楚了。

描述问题

我想设置list上部的search或者其他div在list滚动的时候保持位置不变,这个我该如何操作呢,文档中没有找到对应的设置.

**Comment by ystarlongzi** [comment]
`<van-list />` 组件上方的元素可以用固定、绝对进行定位嘛？如果可以，这样做最简单

**Comment by dong136279559** [comment]
list上方使用的是<van-search> 如果用固定定位的话,控件展示会有bug.

**Comment by ystarlongzi** [comment]
``` html
<div style="position: absolute; top: 100px; left: 0; right: 0; bottom: 0; overflow: auto; -webkit-overflow-scrolling: touch">
  <van-list />
</div>
```

试一下下面这个，其中 `top: 100px` 根据实际需求设置

**Comment by dong136279559** [comment]
好的,谢谢,这个问题已经解决了.
