### ISSUE TITLE
[Bug Report] Swipe组件图片设置为圆角滚动动画依然显示尖角

### ISSUE THREAD

**Issue by honggu025** [youzan/vant#3827]
### 设备 / 浏览器
微信浏览器

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://wx.sjzkz.com/vant" target="_blank">https://wx.sjzkz.com/vant</a>

### 描述问题
用css将swipe中的各层dom都设置为圆角，在图片静止时显示正常，但是在滚动动画执行时，方角就会出现，一直到动画结束才重新变回圆角。
另外，swipe最外层div（class="van-swipe"）高度比图片多出4px，使用自定义指示器时，需要指定bottom:4px，文字背景遮罩才会与图片底部对齐，这时，设置圆角会出现问题，因为圆角是设置的最外层div的圆角。

**Comment by honggu025** [comment]
已解决。

**Comment by hackerslizc** [comment]
> 已解决。

怎么解决的哇

**Comment by LvJianfeng** [comment]
@honggu025  大兄弟，我看这个链接https://wx.sjzkz.com/vant 没有解决哇，请问怎么解决的呢～～

**Comment by draculapile** [comment]
同样遇到了，老哥怎么解决的呀

**Comment by cangyu1993** [comment]
同样遇到了，老哥怎么解决的呀

**Comment by draculapile** [comment]
> 同样遇到了，老哥怎么解决的呀

一般都是层级的问题，好好调一下布局

**Comment by xwLyc** [comment]
给vant-swipe添加样式 transform: translateY(0);
