### ISSUE TITLE
升级vant到2.0.6，picker出现了问题

### ISSUE THREAD

**Issue by ztever** [youzan/vant#3828]
在把vant升级到2.0.6的时候，之前使用的vant picker的样试都变了，最后发现在1.X版本里，picker选择的数据，会有一个van-picker-column__item--selected的class名，而在新的版本里这个class没有了，请问是故意去掉了吗？这个class名还是有用的，希望后续版本里能加回来

**Comment by ztever** [comment]
在把vant升级到2.0.6的时候，之前使用的vant picker的样试都变了，最后发现在1.X版本里，picker选择的数据，会有一个van-picker-column__item--selected的class名，而在新的版本里这个class没有了，请问是故意去掉了吗？这个class名还是有用的，希望后续版本里能加回来

**Comment by chenjiahan** [comment]
可以的，下个版本会加回来

**Comment by chenjiahan** [comment]
已在 2.0.7 版本添加
