### ISSUE TITLE
下拉餐单是否可以异步打开？

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#3833]
![image](https://user-images.githubusercontent.com/42930030/61097101-84afc800-a48c-11e9-92cd-749c99f43d1a.png)
我想 点击整个单元格触发打开
![image](https://user-images.githubusercontent.com/42930030/61097126-998c5b80-a48c-11e9-9294-34d277482eab.png)
这样屏幕就是闪动一下，就像是立刻打开又关闭，我看官网时toggle关闭，不可以toggle打开吗？

**Comment by chenjiahan** [comment]
toggle 是可以打开的，另外点击 menu 的时候也会触发打开，你这样相当于调了两次

**Comment by cangyu1993** [comment]
嗯，我想就是只是打开，我试过.toggle()也就是不传参，也是闪动一下，官网的demo我复制了也是调用两次，怎么做才能只调用一次

**Comment by chenjiahan** [comment]
去掉手动调用就可以，组件本身在点击标题的时候就会触发 toggle 的

**Comment by cangyu1993** [comment]
![image](https://user-images.githubusercontent.com/42930030/61345831-40a43500-a889-11e9-9a80-d803250ebc70.png)
通过引入下拉餐单然后进行了样式覆盖变成了上述样子，我想点击整个单元格就触发相应的下拉菜单，目前是只能点击标题触发，现在线上方案就是我增加了padding-right撑起来，但是这样也是只能点击单元格右边触发

**Comment by chenjiahan** [comment]
你这个地方不应该用 DropdownMenu 的，场景不对，建议用 Picker

**Comment by cangyu1993** [comment]
我也想用上拉餐单加Picker选择，我感觉是最好的方案，但是产品经理------你懂的。。。。，其实通过ref.toggle()绑定点击事件打开就满足了，可是就是连续两次触发，立刻打开又立刻关闭是目前遇到的问题，我看官网的demo是通过ref关闭，不可以打开吗？

**Comment by chenjiahan** [comment]
下个版本会优化下，目前直接调用 toggle(true) 会有一点问题

**Comment by chenjiahan** [comment]
已在 2.0.9 版本优化

**Comment by cangyu1993** [comment]
调用 this.$refs.item.toggle()打开吗？还是传一个参数？

**Comment by chenjiahan** [comment]
`this.$refs.item.toggle(true)` 这样用

**Comment by cangyu1993** [comment]
666，感谢关注，感觉你们可以在官网加一个赞助

**Comment by chenjiahan** [comment]
不用哈，多给我们提建议或 PR 就好 ^_^
