### ISSUE TITLE
[Bug Report] van-number-keyboard 侧边高度写死了

### ISSUE THREAD

**Issue by Yuppiezero** [youzan/vant#3834]
### 设备 / 浏览器
谷歌浏览器,华为手机微信

### Vant 版本
2.0.7

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/number-keyboard" target="_blank">https://youzan.github.io/vant/#/zh-CN/number-keyboard</a>

### 描述问题
键盘右侧的确定和删除的高度在2.06之后就和左边的对不上了，主要体现在  theme="custom" 这个时候右侧的高度是138 不是108

**Comment by Yuppiezero** [comment]
临时的解决办法  直接修改了插件里面的样式 

.van-key {
    display: block;
    float: left;
    width: 33.33333333%;
    height: 54px;
    font-size: 24px;
    font-style: normal;
    line-height: 54px;
    text-align: center;
    vertical-align: middle;
}

**Comment by chenjiahan** [comment]
没明白你的问题，能提供下复现链接或截图吗

**Comment by Yuppiezero** [comment]
> 没明白你的问题，能提供下复现链接或截图吗

https://mail.163.com/js6/s?func=mbox:getMessageData&sid=FBSiwYDUaJouDHGhldUUZHJaHPwHlIUU&mid=38:1tbiJhXybVv2WzEk5gABso&part=3

**Comment by chenjiahan** [comment]
你是不是设置了什么全局样式干扰了组件样式，可以自行排查下，或者提供下复现问题的 codesandbox 链接
