### ISSUE TITLE
请问一下,有没有打算做分享功能呢,就是购物时分享商品图片到朋友圈或者是朋友

### ISSUE THREAD

**Issue by HuiGan-M** [youzan/vant#3835]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持呢

**Comment by HuiGan-M** [comment]
好的,谢谢
