### ISSUE TITLE
[Bug Report] 下拉菜单能否超出隐藏

### ISSUE THREAD

**Issue by lailai215215** [youzan/vant#3836]
DropdownMenu下拉菜单能否超出隐藏
![image](https://user-images.githubusercontent.com/19684446/61109307-2c41f000-a4b7-11e9-8949-0a17177b236f.png)

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 2.0.8 版本支持
