### ISSUE TITLE
NavBar固定在顶部会覆盖下面的列表内容

### ISSUE THREAD

**Issue by dududa2015** [youzan/vant#3837]
![1](https://user-images.githubusercontent.com/49772428/61115084-43d3a580-a4c4-11e9-8421-a919d1fd12b8.png)
没有fixed,第一行显示正常
![2](https://user-images.githubusercontent.com/49772428/61115086-47672c80-a4c4-11e9-88ff-096647cdd95c.png)
fixed，第一行数据被覆盖了
vant是最新版2.07，求大神解答，谢谢！

**Comment by wkl007** [comment]
列表加个padding-top
