### ISSUE TITLE
[Feature Request] progress 完成进度条长度 应该还要加上进度文字展示的一半宽度

### ISSUE THREAD

**Issue by Sonny9527** [youzan/vant#3840]
### 这个功能解决了什么问题
progress 完成进度条的正确显示长度

### 描述您想要的解决方案
progress 组件中
const portionStyle = {
      background,
      width: ((this.progressWidth - this.pivotWidth/2) * percentage) / 100   'px'
    };
宽度应该减去pivotWidth的一半

### 建议的API是什么样的
const portionStyle = {
      background,
      width: ((this.progressWidth - this.pivotWidth/2) * percentage) / 100   'px'
    };

**Comment by chenjiahan** [comment]
减去一半是有问题的，如果只减去一半的话，到 95 时进度条就满了
