### ISSUE TITLE
[Feature Request] 希望官方能出个上拉加载下拉刷新组件

### ISSUE THREAD

**Issue by 941477276** [youzan/vant#3842]
### 这个功能解决了什么问题
解决上拉加载下拉刷新的问题，目前vant官方是没有专门用于做上拉加载、下拉刷新的功能的组件的，现在只能去别的地方找组件
![需要上拉加载下拉刷新页面](https://user-images.githubusercontent.com/20528541/61170224-443d7080-a598-11e9-8be2-4d0526f5f2dc.gif)

### 描述您想要的解决方案
目前vant已有下拉刷新、list(滚动加载)组件，要想实现上拉加载、下拉刷新可以将这两个组件组合使用，但这两个组件组合在一起使用时会出现一些问题，比如上拉加载完成后，list组件的load事件又会立即被触发。
另一个list组件如下图中的效果应该是实现不了的(或许可能是我的使用方式不正确)
![需要上拉加载下拉刷新页面2](https://user-images.githubusercontent.com/20528541/61169571-dc842700-a591-11e9-89cc-781b77e3bc94.gif)

### 建议的API是什么样的
希望官方能出个上拉加载下拉刷新功能组合在一起的组件

**Comment by chenjiahan** [comment]
暂时没计划出这样的组件，如果使用现有的组件遇到问题，可以单独提 issue
