### ISSUE TITLE
vant icon 图片链接 怎么使用本地图片 路径别名@符号不管用

### ISSUE THREAD

**Issue by www-91shh-com** [youzan/vant#3843]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---vant icon 图片链接 怎么使用本地图片 路径别名@符号不管用

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by jasconchen** [comment]
请使用require('@/xxx/xxx.png')
