### ISSUE TITLE
sku商品规格报错

### ISSUE THREAD

**Issue by 13585691306** [youzan/vant#3846]
vue.esm.js?efeb:628 [Vue warn]: Error in render: "TypeError: Cannot read property 'map' of undefined"

found in

---> <VanSkuMessages>
       <VanPopup>
         <VanSku>
           <Product> at src/components/product.vue
             <App> at src/App.vue
               <Root>
warn @ vue.esm.js?efeb:628
logError @ vue.esm.js?efeb:1893
globalHandleError @ vue.esm.js?efeb:1888
handleError @ vue.esm.js?efeb:1848
Vue._render @ vue.esm.js?efeb:3553
updateComponent @ vue.esm.js?efeb:4069
get @ vue.esm.js?efeb:4482
Watcher @ vue.esm.js?efeb:4471
mountComponent @ vue.esm.js?efeb:4076
Vue.$mount @ vue.esm.js?efeb:9057
Vue.$mount @ vue.esm.js?efeb:11953
init @ vue.esm.js?efeb:3127
createComponent @ vue.esm.js?efeb:5983
createElm @ vue.esm.js?efeb:5930
createChildren @ vue.esm.js?efeb:6058
createElm @ vue.esm.js?efeb:5959
createChildren @ vue.esm.js?efeb:6058
createElm @ vue.esm.js?efeb:5959
patch @ vue.esm.js?efeb:6482
Vue._update @ vue.esm.js?efeb:3948
updateComponent @ vue.esm.js?efeb:4069
get @ vue.esm.js?efeb:4482
Watcher @ vue.esm.js?efeb:4471
mountComponent @ vue.esm.js?efeb:4076
Vue.$mount @ vue.esm.js?efeb:9057
Vue.$mount @ vue.esm.js?efeb:11953
init @ vue.esm.js?efeb:3127
createComponent @ vue.esm.js?efeb:5983
createElm @ vue.esm.js?efeb:5930
patch @ vue.esm.js?efeb:6521
Vue._update @ vue.esm.js?efeb:3951
updateComponent @ vue.esm.js?efeb:4069
get @ vue.esm.js?efeb:4482
run @ vue.esm.js?efeb:4557
flushSchedulerQueue @ vue.esm.js?efeb:4313
(anonymous) @ vue.esm.js?efeb:1989
flushCallbacks @ vue.esm.js?efeb:1915
Promise.then (async)
timerFunc @ vue.esm.js?efeb:1942
nextTick @ vue.esm.js?efeb:1999
queueWatcher @ vue.esm.js?efeb:4405
update @ vue.esm.js?efeb:4547
notify @ vue.esm.js?efeb:739
reactiveSetter @ vue.esm.js?efeb:1064
proxySetter @ vue.esm.js?efeb:4634
click @ product.vue?93d3:199
emit @ functional.js?ae18:39
onClick @ index.js?ab5b:14
emit @ functional.js?ae18:39
onClick @ index.js?492b:24
invokeWithErrorHandling @ vue.esm.js?efeb:1863
invoker @ vue.esm.js?efeb:2188
original._wrapper @ vue.esm.js?efeb:7559
Show 7 more frames
vue.esm.js?efeb:1897 TypeError: Cannot read property 'map' of undefined
    at Proxy.render (SkuMessages.js?f9f2:133)
    at VueComponent.Vue._render (vue.esm.js?efeb:3551)
    at VueComponent.updateComponent (vue.esm.js?efeb:4069)
    at Watcher.get (vue.esm.js?efeb:4482)
    at new Watcher (vue.esm.js?efeb:4471)
    at mountComponent (vue.esm.js?efeb:4076)
    at VueComponent.Vue.$mount (vue.esm.js?efeb:9057)
    at VueComponent.Vue.$mount (vue.esm.js?efeb:11953)
    at init (vue.esm.js?efeb:3127)
    at createComponent (vue.esm.js?efeb:5983)
logError @ vue.esm.js?efeb:1897
globalHandleError @ vue.esm.js?efeb:1888
handleError @ vue.esm.js?efeb:1848
Vue._render @ vue.esm.js?efeb:3553
updateComponent @ vue.esm.js?efeb:4069
get @ vue.esm.js?efeb:4482
Watcher @ vue.esm.js?efeb:4471
mountComponent @ vue.esm.js?efeb:4076
Vue.$mount @ vue.esm.js?efeb:9057
Vue.$mount @ vue.esm.js?efeb:11953
init @ vue.esm.js?efeb:3127
createComponent @ vue.esm.js?efeb:5983
createElm @ vue.esm.js?efeb:5930
createChildren @ vue.esm.js?efeb:6058
createElm @ vue.esm.js?efeb:5959
createChildren @ vue.esm.js?efeb:6058
createElm @ vue.esm.js?efeb:5959
patch @ vue.esm.js?efeb:6482
Vue._update @ vue.esm.js?efeb:3948
updateComponent @ vue.esm.js?efeb:4069
get @ vue.esm.js?efeb:4482
Watcher @ vue.esm.js?efeb:4471
mountComponent @ vue.esm.js?efeb:4076
Vue.$mount @ vue.esm.js?efeb:9057
Vue.$mount @ vue.esm.js?efeb:11953
init @ vue.esm.js?efeb:3127
createComponent @ vue.esm.js?efeb:5983
createElm @ vue.esm.js?efeb:5930
patch @ vue.esm.js?efeb:6521
Vue._update @ vue.esm.js?efeb:3951
updateComponent @ vue.esm.js?efeb:4069
get @ vue.esm.js?efeb:4482
run @ vue.esm.js?efeb:4557
flushSchedulerQueue @ vue.esm.js?efeb:4313
(anonymous) @ vue.esm.js?efeb:1989
flushCallbacks @ vue.esm.js?efeb:1915
Promise.then (async)
timerFunc @ vue.esm.js?efeb:1942
nextTick @ vue.esm.js?efeb:1999
queueWatcher @ vue.esm.js?efeb:4405
update @ vue.esm.js?efeb:4547
notify @ vue.esm.js?efeb:739
reactiveSetter @ vue.esm.js?efeb:1064
proxySetter @ vue.esm.js?efeb:4634
click @ product.vue?93d3:199
emit @ functional.js?ae18:39
onClick @ index.js?ab5b:14
emit @ functional.js?ae18:39
onClick @ index.js?492b:24
invokeWithErrorHandling @ vue.esm.js?efeb:1863
invoker @ vue.esm.js?efeb:2188
original._wrapper @ vue.esm.js?efeb:7559
Show 6 more frames

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
