### ISSUE TITLE
建议增加分享图标

### ISSUE THREAD

**Issue by luchuan163** [youzan/vant#385]
建议增加分享图标：
[常见分享图标](http://www.iconfont.cn/search/index?searchType=icon&q=%E5%88%86%E4%BA%AB)
http://www.iconfont.cn/search/index?searchType=icon&q=%E5%88%86%E4%BA%AB

**Comment by chenjiahan** [comment]
@luchuan163 好的，后续会考虑添加

**Comment by qianzhaoy** [comment]
比如箭头图标, 有右箭头, 却没有左箭头. 没有有星星图标...  有的线性的图标, 却没有对应的实体的图标.  非常喜欢你们的组件, 希望能越做越好. 加油~~

**Comment by chenjiahan** [comment]
哈哈~ 谢谢支持，图标我们后续会尽量完善

**Comment by chenjiahan** [comment]
@luchuan163 @qianzhaoy  已在 0.11.9 中添加分享图标和左侧箭头图标
