### ISSUE TITLE
DropdownMenu 建议增加sticky和offset-top

### ISSUE THREAD

**Issue by lyq027** [youzan/vant#3850]
DropdownMenu 建议增加sticky和offset-top

**Comment by JakeLaoyu** [comment]
请使用issue生成器，描述一下api的功能 https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?repo=Vant&type=Feature

**Comment by chenjiahan** [comment]
下个版本会新增一个 Sticky 组件，能实现同样的效果

**Comment by chenjiahan** [comment]
已在 2.0.9 版本增加 Sticky 组件
