### ISSUE TITLE
vue全局引入VantUI之后，部分组件无法使用

### ISSUE THREAD

**Issue by Tiramisu1** [youzan/vant#3851]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

--- vue全局引入VantUI之后，部分组件无法使用

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

你好！ 我在vue项目mian.js文件中全局引入vantUI（如下图1）但是我在个别页面引入CountDown组件并使用（如下图2），控制台报错<van-count-down> - did you register the component correctly? For recursive components, make sure to provide the "name" option.Divider组件也是如此其他插件没有问题，请问是什么原因呢？
图1：
![image](https://user-images.githubusercontent.com/29446127/61197833-7a4e3200-a709-11e9-8edc-8b88866b8c2c.png)
图2：
![image](https://user-images.githubusercontent.com/29446127/61197851-8f2ac580-a709-11e9-97b0-f284e82cd4e8.png)
![image](https://user-images.githubusercontent.com/29446127/61197860-9baf1e00-a709-11e9-8fd0-5c7acfa53120.png)
![image](https://user-images.githubusercontent.com/29446127/61197867-a49fef80-a709-11e9-9ab7-05aa06d2e63a.png)

**Comment by chenjiahan** [comment]
CountDown 在最新的 2.0.7 版本才支持喔，建议确认下你引入的版本是否正确

**Comment by Tiramisu1** [comment]
> CountDown在最新的2.0.7版本才支持喔，建议确认下你引入的版本是否正确

我去看看 谢谢你了

**Comment by wwdDongDong** [comment]
看看是不是最新版本，在package,json文件当中看看
