### ISSUE TITLE
[Bug Report] 文件上传预览问题

### ISSUE THREAD

**Issue by CoutinhoTTS** [youzan/vant#3852]
### 设备 / 浏览器
电脑/谷歌浏览器

### Vant 版本
2.0.7

### Vue版本
2.6.10

### 描述问题
图片文件上传预览失败

文件上传：
![image](https://user-images.githubusercontent.com/48982306/61203025-cb672180-a71b-11e9-8ef1-35e6651a2a29.png)
页面显示：
![image](https://user-images.githubusercontent.com/48982306/61203072-f18cc180-a71b-11e9-94bb-3a421d5740dd.png)
文件选择后的函数调用:
![image](https://user-images.githubusercontent.com/48982306/61203240-63650b00-a71c-11e9-872e-aa39a5aee567.png)
文件选择：
![image](https://user-images.githubusercontent.com/48982306/61203317-9dcea800-a71c-11e9-9aab-acfd00d58f1e.png)
console.log()出文件解析对象：
![image](https://user-images.githubusercontent.com/48982306/61203515-2d745680-a71d-11e9-9574-613a81a03b10.png)
但是当文件选择完后没有在页面上出现预览的而文件
![image](https://user-images.githubusercontent.com/48982306/61203671-9d82dc80-a71d-11e9-8035-dffc7a7901e9.png)

**Comment by chenjiahan** [comment]
你的用法是错误的，不需要手动往 fileList 里 push 内容，按文档来就可以

**Comment by CoutinhoTTS** [comment]
> 你的用法是错误的，不需要手动往fileList里推内容，按文档来就可以
![image](https://user-images.githubusercontent.com/48982306/61204007-9c9e7a80-a71e-11e9-957d-cc672f7b8e62.png)
![image](https://user-images.githubusercontent.com/48982306/61204019-a2945b80-a71e-11e9-9798-95ada5900bce.png)
没有网fileList里push按照文档里来的但还是预览不到

**Comment by chenjiahan** [comment]
能提供下复现链接么，或者打开 node_modules/vant/package.json 确认下你使用的是不是 2.0.7 版本

**Comment by CoutinhoTTS** [comment]
> 能提供下复现链接么，或者打开 node_modules/vant/package.json 确认下你使用的是不是 2.0.7 版本

![image](https://user-images.githubusercontent.com/48982306/61205022-85ad5780-a721-11e9-82a4-be4b98e3cf2c.png)
好像不是哎。。。。。。。。。。。。？？？？？！！！！！！！！！！

**Comment by chenjiahan** [comment]
那就是版本问题咯，你升级下版本应该就好了

**Comment by CoutinhoTTS** [comment]
> 那就是版本问题咯，你升级下版本应该就好了

OK谢谢了
