### ISSUE TITLE
[Feature Request] tab组件切换

### ISSUE THREAD

**Issue by southorange1228** [youzan/vant#3853]
### 这个功能解决了什么问题
tab组件v-model绑定了active，通过代码控制active改变，但是tab的选中样式不会改变。

### 描述您想要的解决方案
选中样式与v-model相关联，随之切换 类似与底部tab

### 建议的API是什么样的
组件内部实现

**Comment by JakeLaoyu** [comment]
没有复现，请提供代码，以及vant版本。https://codesandbox.io/s/m5v3f

**Comment by southorange1228** [comment]
[![Edit Vant issue 模板](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vant-issue-moban-edf1r?fontsize=14)

https://codesandbox.io/s/vant-issue-moban-edf1r?fontsize=14

vant-version:2.0.1

**Comment by JakeLaoyu** [comment]
button 并没有绑定点击事件

**Comment by southorange1228** [comment]
这只是展示 一时图快忘写了而已 情况就这样的 你们看一下是不支持还是说我没写对 找对方法

**Comment by JakeLaoyu** [comment]
当前标签2是 disabled状态

**Comment by JakeLaoyu** [comment]
这块是有bug

**Comment by JakeLaoyu** [comment]
这块的bug是disabled状态下点击的时候 标签2颜色变了，按理说应该不改变的。

所以如果你是在disabled的情况下 也不满足你说的要求

**Comment by JakeLaoyu** [comment]
@southorange1228  是否可以考虑这种写法 ，这个需求我们在代码里兼容感觉不是很合理

https://codesandbox.io/s/httpsgithubcomyouzanvantissues3853-gr6id

**Comment by southorange1228** [comment]
可以实现即可 但个人感觉这样有一点多余的代码 建议还是考虑一下我说的那种方法 比较符合逻辑思维

**Comment by JakeLaoyu** [comment]
考虑到你这种需求并不是很常见，如果在源码中加入 PR 的代码，对后面维护不是很好理解
