### ISSUE TITLE
[Feature Request] 日期组件

### ISSUE THREAD

**Issue by wwdDongDong** [youzan/vant#3856]
### 这个功能解决了什么问题
组件其实挺好用的。没有什么问题。

### 描述您想要的解决方案
希望添加可以添加 选择时间段 的日期选择框，比如选择2019-05-06到2019-06-09的时间段。跟elememt-ui的日期选择框类似的。实在是找不到在哪里提需求，就在这里写了

### 建议的API是什么样的
希望添加可以添加 选择时间段 的日期选择框，比如选择2019-05-06到2019-06-09的时间段。跟elememt-ui的日期选择框类似的。实在是找不到在哪里提需求，就在这里写了

**Comment by JakeLaoyu** [comment]
对于移动端ui库来说，这是不合理的，在小屏幕上不是很好展示和操作

**Comment by chenjiahan** [comment]
暂无计划支持喔
