### ISSUE TITLE
Uploader 不能预览网络图片

### ISSUE THREAD

**Issue by LiGuoBi** [youzan/vant#3858]
### Uploader  组件不能预览网络图片
我要实现表单数据可以保存，下次进入表单页面，保留上次填写的数据。

图1是已经上传的，图2和图3是还没有上传的。预览只能预览图2和图3。
![3](https://user-images.githubusercontent.com/37058788/61209444-56e8ae80-a72c-11e9-95f7-ca2978166d36.png)
![1](https://user-images.githubusercontent.com/37058788/61209346-15f09a00-a72c-11e9-881d-8b12846e17cd.png)
![2](https://user-images.githubusercontent.com/37058788/61209432-4fc1a080-a72c-11e9-83dc-7d111c4109a5.png)

**Comment by chenjiahan** [comment]
后续会支持下

**Comment by inooNgt** [comment]
`  onPreviewImage(item) {
      const imageFiles = this.fileList
        .map(item => item.content)
        .filter(content => isImageDataUrl(content));

      ImagePreview({
        images: imageFiles,
        startPosition: imageFiles.indexOf(item.content)
      });
    },`
@chenjiahan uploader里为什么需要判断isImageDataUrl才能预览图片，可以去掉吗？

**Comment by chenjiahan** [comment]
@inooNgt 后续会支持网络图片的 URL

**Comment by chenjiahan** [comment]
已在 2.0.9 版本支持
