### ISSUE TITLE
divider组件不能正常显示

### ISSUE THREAD

**Issue by bulemanking** [youzan/vant#3860]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by jeeinn** [comment]
更新下版本试试

`divider` 在 `version > 2.0.6` 才正常显示

**Comment by chenjiahan** [comment]
楼上正解
