### ISSUE TITLE
[Bug Report] PullRefresh下拉刷新组件的问题

### ISSUE THREAD

**Issue by dong136279559** [youzan/vant#3863]
[Bug Report] 手机端 iPhone6

问题描述: 
1. PullRefresh 与list 结合使用时 只有在list有数据时,在cell上下拉时才能触发下拉,在空白区下拉没有反应.

请问这是组件的问题吗?还是我使用组件的问题呢?

**Comment by chenjiahan** [comment]
你可以给 List 设置一个最小高度，撑开整个容器，PullRefresh 操作区域是和内容高度一致的

```html
<van-pull-refresh>
    <van-list style="min-height: 100vh">
    ...
    </van-list>
</van-pull-refresh>
```
