### ISSUE TITLE
[Feature Request] 建议 button等组件 line-height，换成flex去设置垂直居中显示

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#3865]
### 这个功能解决了什么问题
android ios line-height 存在兼容性问题，

### 描述您想要的解决方案
flex布局（其他组件类似如有类似问题，也可以看看可能这样修改）
    

### 建议的API是什么样的
flex布局
justify-content: center;
align-items: center;

**Comment by chenjiahan** [comment]
短期内没计划调整呢，改成 flex 布局会破坏现有用户的样式，如果要调整会放在下一个大版本里面
