### ISSUE TITLE
[Bug Report] Dialog组件中closeOnPopstate属性值无效的问题

### ISSUE THREAD

**Issue by LLawlight** [youzan/vant#3867]
### 设备 / 浏览器
all

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-b3zmc" target="_blank">https://codesandbox.io/embed/vant-issue-moban-b3zmc</a>

### 描述问题
文档中描述closeOnPopstate（是否在页面回退时自动关闭）的默认值为false，但是实际上不管设置为true还是false还是不设置，都会自动关闭。
原因就是vant\es\dialog\dialog.js中mixin的CloseOnPopstateMixin，mixin了BindEventMixin，而这个方法在mounted的时候一定会把事件给绑定上。
如果我们传入false或者不穿，CloseOnPopstateMixin触发不了watch，off不了事件，如果设为true，因为事件已经on了，就会维持on的状态，所以无论如何都会触发“自动关闭”。

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 2.0.9 版本修复

**Comment by qingqingke** [comment]
另外，路由需要加缓存
