### ISSUE TITLE
[Feature Request] 我使用tab标签页做二级路由页面，切换标签时为什么会多（4）次调用生命周期函数.

### ISSUE THREAD

**Issue by 121132839** [youzan/vant#3870]
### 这个功能解决了什么问题
每次created执行多次，会被后端拒绝多次请求，而且很不合理。

### 描述您想要的解决方案
有什么解决方法吗?

**Comment by chenjiahan** [comment]
麻烦提供一下复现问题的 codesandbox 链接

**Comment by 121132839** [comment]
> 麻烦提供一下复现问题的 codesandbox 链接

<van-tabs v-model="active" @click="onClick" animated>
        <van-tab v-for="index in tabs" :title="index.title"  :key="index.id">
          <router-view />
        </van-tab>
</van-tabs>

第一次访问没有问题，只执行一次，然后我再各个tab之间切换，就会出现生命周期反复执行多次的情况
beforecreatedRate.vue?e960:30
created!!Rate.vue?e960:41
mountedRate.vue?e960:38

beforecreatedRate.vue?e960:30
created!!Rate.vue?e960:41
mounted Rate.vue?e960:38

beforecreatedRate.vue?e960:30
created!!Rate.vue?e960:41
 mounted

**Comment by 121132839** [comment]
这个问题解决了，用条件渲染解决了没事了

**Comment by UmeusYoung** [comment]
> 这个问题解决了，用条件渲染解决了没事了

您好，我现在的问题跟你描述的一模一样，这个条件渲染是怎么做条件的？写在哪里，能讲一下吗？谢谢

**Comment by zhangjiaqifcb** [comment]
你好，可以借鉴一下van-tab 二级页面动态加载路由的code嘛

**Comment by nicky132** [comment]
> 这个问题解决了，用条件渲染解决了没事了

大佬,咋解决的,我也遇到这问题,嵌套路由,结果van-tabs点击后,二级路由页面的mounted执行了2次,那么接口就重复调用了1次,目前没啥好方法
父组件:
<div>
    <header>这是一级路由</header>
    <van-tabs v-model:active="active" @change="change">
      <van-tab name=“route1” title=“route1” to=“/home/index1/detail”>
        <router-view></router-view>
      </van-tab>
      <van-tab name=“route2” title=“route2” to=“/home/index2/detail”>
        <router-view></router-view>
      </van-tab>
    </van-tabs>
</div>

子组件:
<div>
      <header>这是二级路由</header>
      <router-view></router-view>
</div>
嵌套路由:
{
  path: '/',
  name: '',
  redirect: '/home'
},
{
  path: '/home',
  name: 'home',
  redirect: '/home/index1',
  component: () => import('@/views/Home.vue'),
  children: [
    {
      path: 'index1',
      name: 'index1',
      redirect: '/home/index1/detail',
      component: () => import('@/views/index1.vue'),
      children: [
        {
          path: 'detail',
          name: 'detail',
          component: () => import('@/views/detail/Index1Detail.vue')
        }
      ]
    },
    {
      path: 'index2',
      name: 'index3',
      redirect: '/home/index2/detail',
      component: () => import('@/views/index2.vue'),
      children: [
        {
          path: 'detail',
          name: 'detail',
          component: () => import('@/views/detail/Index2Detail.vue')
        }
      ]
    }
  ]
}
