### ISSUE TITLE
用area组件，在ios10.2版本上无法滑动，可以点击

### ISSUE THREAD

**Issue by kejiangtao** [youzan/vant#3871]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3015
