### ISSUE TITLE
import { Tab, Tabs } from 'vant'的问题

### ISSUE THREAD

**Issue by mayeyun** [youzan/vant#3873]
这个在vue里面用有问题 
![image](https://user-images.githubusercontent.com/32790679/61345624-84e30580-a888-11e9-8eb9-3287e1aa0fe5.png)
![image](https://user-images.githubusercontent.com/32790679/61345654-a512c480-a888-11e9-99d2-d6bb61bdc12e.png)
![image](https://user-images.githubusercontent.com/32790679/61345753-ec00ba00-a888-11e9-9fef-a6678bd094d6.png)
![image](https://user-images.githubusercontent.com/32790679/61345770-fc189980-a888-11e9-96fc-404e747991e1.png)
![image](https://user-images.githubusercontent.com/32790679/61345793-16527780-a889-11e9-9804-75a04d5cb5c3.png)
![image](https://user-images.githubusercontent.com/32790679/61345804-1eaab280-a889-11e9-8de8-05221768f48c.png)

有赞看看这是什么情况可能是react的组件和vue有一定的兼容性问题

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接
