### ISSUE TITLE
[Need Help] tabs在使用时产生警告

### ISSUE THREAD

**Issue by dong136279559** [youzan/vant#3877]
[[Need Help] 手机端 iPhone6
                        vue版本:2.6.10
                         vant版本:2.0.8
问题描述:

<Tabs v-model="active" class="tabContent" animated lazy-render swipeable >
	<Tab v-for="(item,index) in dataSource" :title='item' :name="index" :key="item">
		测试内容:之后看看展示什么 {{ item + index}}
	</Tab>
</Tabs>

当我在vue中这样写时,会产生警告如下图
![72AABF51-0C15-4F33-8AFE-AAE624772E5A](https://user-images.githubusercontent.com/20337504/61352481-0d20d500-a8a0-11e9-887c-2c4f9edc711d.png)

不影响使用,但是警告太多,影响测试.
当我使用低版本vant(1.6.11)时就没有这个问题,请问这是组件的问题吗?还是我使用组件的问题呢?

**Comment by chenjiahan** [comment]
看起来是使用的问题，建议自行排查下`contractFile`组件是否有写法问题

**Comment by dong136279559** [comment]
应该不是我的写法有问题,我在`contractFile `组件中 并没有使用 count,currentIndex这些属性值,在vantTab组件中发现有currentIndex,并且,只写比较简单的tabs包裹tab标签时也会报警告.

**Comment by chenjiahan** [comment]
能提供一下复现的 codesandbox 链接吗

**Comment by dong136279559** [comment]
https://pxn9j.codesandbox.io
抱歉,不知道为啥,UI显示不出来,但是这个没有显示警告,有点搞不懂了

**Comment by chenjiahan** [comment]
UI 没出来是因为样式没引入，链接里面的用法没问题，你还是检查下`contractFile`组件吧

**Comment by aloneWang** [comment]
我也是出现这样的问题，降到2.0.2，就不出现警告了，代码只是文档的demo.

**Comment by chenjiahan** [comment]
@aloneWang 麻烦提供下复现的 codesandbox 链接
