### ISSUE TITLE
小程序端使用vant，组件引入不完整

### ISSUE THREAD

**Issue by yangchin9** [youzan/vant#3879]
小程序端使用vant，组件引入不完整；安装vant过程中无异常，能正常使用但是缺少个别组件；比如grid、grid-item等

**Comment by chenjiahan** [comment]
小程序端目前不支持 grid 组件喔，开发小程序时，请参考 vant-weapp 文档

**Comment by yangchin9** [comment]
非常感谢你的回复！  我一直用的是https://youzan.github.io/vant/#/zh-CN/contribution这个，不知道有专门的小程序版本！！！ 太无知了……   非常感谢




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 下午5:50
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "🔑"<1352243861@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] 小程序端使用vant，组件引入不完整 (#3879)




小程序端目前不支持 grid 组件喔，开发小程序时，请参考 vant-weapp 文档

**Comment by chenjiahan** [comment]
客气哈 ^_^

**Comment by zuweie** [comment]
文档哪里写了不支持？害我瞎捣鼓一天
