### ISSUE TITLE
SwipeCell与Swipe组件一起使用时，会同时滑动

### ISSUE THREAD

**Issue by anrananran** [youzan/vant#3880]
有没有办法可以阻止一起滑动呀？左滑SwipeCell的时候，Swipe组件不应该一起滑动

**Comment by chenjiahan** [comment]
下个版本会处理下，SwipeCell 加个阻止事件冒泡

**Comment by chenjiahan** [comment]
已在 2.0.9 版本优化

**Comment by anrananran** [comment]
就喜欢你们的做事风格，神一般的执行力！

**Comment by chenjiahan** [comment]
😊

**Comment by chenjiahan** [comment]
阻止 touchmove 事件冒泡后导致了一些其他问题，如 https://github.com/youzan/vant/issues/3950

所以下个版本会加个开关来控制是否冒泡，对于需要阻止冒泡的情况，请加上`stop-propagation`属性。

```html
<van-swipe-cell stop-propagation>
  ...
</van-swipe-cell>
```

建议提前把这个属性加上，免得之后升级版本的时候出现问题

**Comment by anrananran** [comment]
thanks
