### ISSUE TITLE
vant-tabs中的animated问题

### ISSUE THREAD

**Issue by dududa2015** [youzan/vant#3882]
背景：vant-tabs中有两个tab分别为A和B，每个tab分别对应list A和list B，并增加**animated**属性
操作：当初始化页面后，先切换到tab B，并执行下拉操作，list B正常执行onLoad,再切回tab A并下拉，此时的list A一直处于loading状态，并不会加载数据。
如果去掉animated，list A是能正常加载的。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
