### ISSUE TITLE
[Feature Request] Dialog 组件新增右上角关闭按钮

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#3884]
### 这个功能解决了什么问题
开发 H5 一般有弹窗显示关闭按钮的需求，当2个按钮的文案都是某种操作时，这时就需要关闭按钮了，点击关闭按钮不进行任何操作~

### 描述您想要的解决方案
提供可选 prop showCloseButton，event close，before-close 回调的 action 添加 close

### 建议的API是什么样的
showCloseButton

**Comment by chenjiahan** [comment]
目前没有这块的视觉规范，所以暂时不会支持，建议通过 Popup 自行实现
