### ISSUE TITLE
Toast 和 Popup 同时存在的时候，Popup 里的元素不可点击

### ISSUE THREAD

**Issue by Priccc** [youzan/vant#3885]
先使用全局的Toast.loading
const toast = Toast.loading({
  duration: 0,       // 持续展示 toast
  forbidClick: true, // 禁用背景点击
  loadingType: 'spinner',
  message: '倒计时 3 秒'
});
这时弹出自定义的 Popup 弹框，在 Toast 不清除的情况下，弹窗里的内容不可点击

在把 forbidClick 设置为 false 的时候，就可以点击了

**Comment by Priccc** [comment]
查看了一下，forbidClick: true 会给 body 元素加一个类 `.van-toast--unclickable`，会给body增加一个属性 `pointer-events: auto;`，body 以下所有元素都会继承这个属性

**Comment by chenjiahan** [comment]
这个是正常的逻辑，当 Toast 设置 forbidClick 并展示后，其他内容都是无法点击的
