### ISSUE TITLE
Taost 自定义图片  图片未加载出来时  会有一个空白的占位图    影响loaidng界面美观

### ISSUE THREAD

**Issue by zxy89** [youzan/vant#3890]
<img width="277" alt="屏幕快照 2019-07-18 18 33 28" src="https://user-images.githubusercontent.com/23162186/61450864-a2989380-a98a-11e9-9a15-b1ff8e82f244.png">
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
下个版本会优化下

**Comment by chenjiahan** [comment]
已在 2.0.9 版本优化
