### ISSUE TITLE
Grid 组件文字为长英文时，会出现不受宽度限制问题

### ISSUE THREAD

**Issue by evont** [youzan/vant#3894]
当text 属性为较长的不间隔的英文时，单元宽度会不受flex-basis限制，导致其余组件被拉伸，建议使用 word-break: break-all; 对组件文字进行限制

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.0.9 版本优化

**Comment by bill80362** [comment]
問題沒有解決，目前要自行加上
  .van-grid-item__content{
    word-break: break-all;
  }

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.3 版本支持，后续的 2.10.10 版本也会同步该修复
