### ISSUE TITLE
[Feature Request] Dialog 组件新增 slot

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#3900]
### 这个功能解决了什么问题
解决对话框里面有放输入框或其他 HTML 标签的场景

### 描述您想要的解决方案
替换中间 message 内容部分

### 建议的API是什么样的
options message 支持 html ，新增 slot message

**Comment by chenjiahan** [comment]
默认 slot 就是 message，HTML 也是支持的

**Comment by 1014156094** [comment]
> 默认 slot 就是 message，HTML 也是支持的

文档木有写，不知道~ [捂脸.gif]

**Comment by 1014156094** [comment]
> > 默认 slot 就是 message，HTML 也是支持的
> 
> 文档木有写，不知道~ [捂脸.gif]

组件调用那里看到了
