### ISSUE TITLE
ImagePreview图片预览安卓后退键

### ISSUE THREAD

**Issue by rzh11111111** [youzan/vant#3902]
图片预览后安卓后退键关闭预览

我现在是通过vuex来判断，预览的时候把整个
this.$store.commit('SET_INSTANCE',ImagePreview({
          images: [
            ‘图片’
          ]
        }))
放进vuex，

然后点击后退键时在组件判断才能关闭，虽然实现了但是感觉很有问题。。
if (document.getElementsByClassName('van-image-preview').length) {
        if (this.$store.state.record.instance == 'on') {
          this.$store.commit('SET_INSTANCE', 'off')
        } else {
          this.$store.state.record.instance.close()
        }

      }

**Comment by chenjiahan** [comment]
可以直接用 `closeOnPopstate` 属性

**Comment by rzh11111111** [comment]
不是，安卓监听了用户的后退然后调用我的方法，预览的时候点击后退要关闭预览，没预览时后退才是后退

**Comment by chenjiahan** [comment]
那可以在打开 ImagePreview 的时候加个 hash，后退的时候去掉

**Comment by rzh11111111** [comment]
emm不太懂

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3240

大致用法是这样
```js
ImagePreview({ ... });
location.hash = 'xxx'
```
