### ISSUE TITLE
[Feature Request] Grid 宫格 自定义class

### ISSUE THREAD

**Issue by ShmmGood** [youzan/vant#3904]
### 这个功能解决了什么问题
我想要进行圆角化边框时不会污染其他页面的Grid 修改一系列的样式时不会污染到其他的组件这是个很好的帮助。

### 描述您想要的解决方案
希望添加个class自定义的方式。

### 建议的API是什么样的
:style-class

**Comment by chenjiahan** [comment]
直接添加 class 就可以的，Vue 组件默认会继承

**Comment by ShmmGood** [comment]
> 直接添加 class 就可以的，Vue 组件默认会继承

你说的没错，但是看下截图你就明白了，虽然我用 >>>解决这个问题了

![image](https://user-images.githubusercontent.com/38807792/61519644-f664b480-aa3e-11e9-80b9-870a5acd0902.png)
![image](https://user-images.githubusercontent.com/38807792/61519682-13998300-aa3f-11e9-9a34-6e5bf41173ea.png)

**Comment by chenjiahan** [comment]
所以添加 `style-class` 的必要性是？

**Comment by ShmmGood** [comment]
> 所以添加 `style-class` 的必要性是？

所以目前没有需要了谢谢
