### ISSUE TITLE
[Bug Report] van-tabs的bug反馈

### ISSUE THREAD

**Issue by sds0917** [youzan/vant#3913]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.0.9

### Vue版本
2.5.17

### 重现链接
<a href="https://teix5.codesandbox.io/" target="_blank">https://teix5.codesandbox.io/</a>

### 描述问题
van-tabs组件加了animated属性后，里面的van-index-bar组件会失效，具体是tabs上的transform: translate3d(0%, 0px, 0px);影响了index-bar组件。示例地址：https://codesandbox.io/embed/vant-issue-moban-teix5?fontsize=14

**Comment by chenjiahan** [comment]
这个是浏览器限制的，transform 元素内部的 fixed 会变成 absolute.

建议把 IndexBar 组件放到 Tabs 的外部，或者不使用 animated 属性

**Comment by sds0917** [comment]
好的，那我去掉animated属性
