### ISSUE TITLE
[Bug Report] 优惠券内容更新后再次打开列表显示错误

### ISSUE THREAD

**Issue by zhangfei8080** [youzan/vant#3915]
### 设备 / 浏览器
Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36

### Vant 版本
2.0.9

### Vue版本
2.6.10

### 重现链接
 ![image](http://www.19nu.cn/aaaaa.gif)

### 描述问题
当优惠券数据从可用移动到不可用或者从不可用移动到可用时出现如图问题

**Comment by chenjiahan** [comment]
能否提供一下复现的 codesandbox 链接

**Comment by zhangfei8080** [comment]
@chenjiahan 
这是复现地址
https://codesandbox.io/embed/vant-issue-moban-zl9wu

当打开并切换可用于不可用后再更改数量 就会出现图上的问题

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.1.0-beta.2 版本修复，正式版会在下周发布
