### ISSUE TITLE
[Feature Request] 是否会出布局容器?

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#3917]
### 这个功能解决了什么问题
目前的vant很好用 也很赞 但是在有导航栏和标签栏的时候出现了 顶部和底部的内容会被遮挡住
第二个问题就是滚动条会延长至顶部导航栏下拉的时候延长到底部的标签栏上!

### 描述您想要的解决方案
之前用过mui  它有一个布局容器的功能! 解决了使用布局容器后 有 顶部和底部以及中间的内容区域 内容区域的内容不会隐藏到顶部和底部里面去 而滚动条却只在中间的内容区域出现 不会出现在顶部以及底部!

### 建议的API是什么样的
有顶部以及底部内容区域的自定义 滚动条不会出现到顶部和底部 只允许在内容区域滚动

**Comment by chenjiahan** [comment]
暂时没有计划出这样的组件喔，这个问题有两种简单的解决方式：

1. NavBar 和 Tabbar 是 fixed 布局，所以你在页面顶部和底部加一个相同高度的 padding 就可以防止遮挡
2. 中间内容设置 `overflow: scroll`，变成局部滚动
