### ISSUE TITLE
[Feature Request] 多列联动如何设置某个选项为 disabled？

### ISSUE THREAD

**Issue by zaxlct** [youzan/vant#3918]
### 这个功能解决了什么问题
多列联动如何设置某个选项为 disabled？

### 描述您想要的解决方案
获取 picker 实例并调用实例方法，能实现吗

### 建议的API是什么样的
获取 picker 实例并调用实例方法，能实现吗

**Comment by chenjiahan** [comment]
可以通过`setColumnValue`实现，在 ColumnValue 的对应选项中，将 disabled 设置为 true
