### ISSUE TITLE
[Feature Request] AddressList在switchable=false时，没有点击事件

### ISSUE THREAD

**Issue by LvJianfeng** [youzan/vant#3924]
### 这个功能解决了什么问题
地址点击选择后直接返回

### 描述您想要的解决方案
点击事件

### 建议的API是什么样的
click

**Comment by chenjiahan** [comment]
下个版本会加个 `click-item` 事件

**Comment by LvJianfeng** [comment]
@chenjiahan  好的 感谢！

**Comment by chenjiahan** [comment]
已在 2.1.0-beta.1 版本发布（正式版预计下周发布）
