### ISSUE TITLE
[Bug Report] 首次加载icon图标不显示

### ISSUE THREAD

**Issue by qhchen88g** [youzan/vant#3925]
### 设备 / 浏览器
iphone6/企业微信内置浏览器

### Vant 版本
2.1.0-beta.0

### Vue版本
2.6.10

### 重现链接
<a href="http://xxx.com" target="_blank">http://xxx.com</a>

### 描述问题
1.iphone6下，企业微信里，h5页，首次加载时，字体图标不显示，关闭再次打开能正常；其他机型无此问题存在；
2. 字体文件是使用本地加载的方式引入 import 'vant/lib/icon/local.css';
3.详情如下图：
![image](https://user-images.githubusercontent.com/8456797/61621107-d6362f00-aca4-11e9-8c80-a0fa0f769f3c.png)

**Comment by chenjiahan** [comment]
本地的字体是 ttf 格式的，理论上在手机上不会有兼容性问题

麻烦看下：
1. 手机的 iOS 系统版本是多少
2. 用网络字体是否会有问题

**Comment by qhchen88g** [comment]
> 本地的字体是 ttf 格式的，理论上在手机上不会有兼容性问题
> 
> 麻烦看下：
> 
> 1. 手机的 iOS 系统版本是多少
> 2. 用网络字体是否会有问题

1. 系统版本12.1和12.3都出现该问题
2. 一开始用的是网络字体存在该问题，以为是加载问题换成了本地字体，问题依然存在

**Comment by chenjiahan** [comment]
同一个手机，在 safari 打开会有问题吗

**Comment by qhchen88g** [comment]
> 同一个手机，在 safari 打开会有问题吗

safari没问题
测试反馈是iphone7及以下机型都会出现该问题

**Comment by chenjiahan** [comment]
目前没找到复现方法，所以不太好排查，建议你用复现的手机调试下，或者看看其他的 iconfont 能否展示，比如 fontawesome

**Comment by qhchen88g** [comment]
> 目前没找到复现方法，所以不太好排查，建议你用复现的手机调试下，或者看看其他的 iconfont 能否展示，比如 fontawesome

icon组件是否考虑提供个svg格式的接入，使用svg不存在该问题；
网上也有说法在微信内置浏览器出现该问题，但是我按照他那样改还是不行。。
https://segmentfault.com/q/1010000013499384/a-1020000013499664

**Comment by chenjiahan** [comment]
svg 未来会支持，短期内没计划

你试过其他 iconfont 吗

**Comment by qhchen88g** [comment]
> svg 未来会支持，短期内没计划
> 
> 你试过其他 iconfont 吗

就试了阿里云的iconfont不行 就改为svg了

**Comment by chenjiahan** [comment]
这年头不支持 iconfont 的情况很稀有了，如果真的需要兼容，就先用 svg 吧

**Comment by qhchen88g** [comment]
> 这年头不支持 iconfont 的情况很稀有了，如果真的需要兼容，就先用 svg 吧

对于vant组件自带的icon（比如search搜索），也一个个的换成svg就太麻烦了，还是希望ui能尽快支持svg

**Comment by chenjiahan** [comment]
短期内不会

**Comment by MechaGirls** [comment]
应该是你设置的全局font-size覆盖了van-icon的字体设置
