### ISSUE TITLE
collapse折叠面板的属性“accordion”值为false就会报错：value.some is not a function"; 值为true正常；

### ISSUE THREAD

**Issue by zerolidao** [youzan/vant#3926]
collapse折叠面板的属性`accordion`值为false就会报错：`value.some is not a function`"; 值为true正常；
版本：2.0.9；

`<van-collapse v-model="active" accordion></van-collapse>`

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/61622340-2d3d0380-aca7-11e9-81df-ec56eee43b0c.png)
