### ISSUE TITLE
[Feature Request]Coupon 优惠券选择器

### ISSUE THREAD

**Issue by yoruponder** [youzan/vant#3927]
优惠券选择器的不可用优惠券列表为空时，里面的图片是否可以自定义
<img width="397" alt="WX20190722-195803@2x" src="https://user-images.githubusercontent.com/9858714/61630889-7e56f280-acbb-11e9-9fb5-c6d4b3916e99.png">

**Comment by chenjiahan** [comment]
可以的，下个版本会加一个属性

**Comment by chenjiahan** [comment]
已在 2.1.0-beta.1 版本发布（正式版预计下周发布）
