### ISSUE TITLE
[Feature Request] ImagePreview 可否优化长图的预览

### ISSUE THREAD

**Issue by VecHK** [youzan/vant#3928]
### 这个功能解决了什么问题
长图的预览

### 描述您想要的解决方案
打开长图后宽度会缩放到屏幕的宽度，同时位置移动到图片的最上面

### 建议的API是什么样的
能做到自动识别是否是长图的话最好。不行的话则暴露一个缩放长图的接口或者提供相关的配置参数

**Comment by chenjiahan** [comment]
后续会看下怎么优化这种情况

**Comment by waet** [comment]
这个组件怎么引入项目目录中的图片呢？ 本地路径和变量引入都找不到图片，只能引线上的图片？

**Comment by zhangliyuan-chance** [comment]
这个可以单独使用css优化实现的

**Comment by DickyNet** [comment]
我也希望有这样的功能。不知道是否已经实现了？

**Comment by DickyNet** [comment]
> 这个可以单独使用css优化实现的

如何实现呢？

我在使用下面这样的样式后，可以实现， 但是影响放大功能，超高的图片再放大后不能左右上下拖动了，或者只能拖动一部分，不能拖动显示图片的全貌：
`.van-image__img {
	height: auto!important;
}
.van-image-preview__image--vertical {
	overflow: auto;
}`

**Comment by sizhuxuan** [comment]
这个长图预览的功能一年多了，还没有优化或者实现吗

**Comment by chenjiahan** [comment]
还没嘞，不是很好实现。

**Comment by RockFane** [comment]
> 还没嘞，不是很好实现。

可以的话, 集成hammerjs来实现拖拽移动和缩放

**Comment by tsheng** [comment]
> 

这个还有更好的优化建议吗？超长图放大了，看不到左右侧的图了
