### ISSUE TITLE
[Feature Request] [tabbar] router mode should support reg router match

### ISSUE THREAD

**Issue by githoniel** [youzan/vant#3929]
### 这个功能解决了什么问题
Now the tabbar router mode active no corrent when using nested routers
eg
```
<van-tabbar route>
  <van-tabbar-item
    replace
    to="/home"
    icon="home-o"
  >
    Tab
  </van-tabbar-item>
  <van-tabbar-item
    replace
    to="/search"
    icon="search"
  >
    Tab
  </van-tabbar-item>
</van-tabbar>
```

if router is '/home/search', the  first tabbar-item will not active

### 描述您想要的解决方案
tabbar-item support `match` props

### 建议的API是什么样的
<van-tabbar-item
    replace
    match = "/^home/\./g"
    to="/search"
    icon="search"
>

**Comment by chenjiahan** [comment]
No plan to provide the `match` prop, please use index to control active tab in this case
