### ISSUE TITLE
0.11.7版Tabs 标签页在移动端问题

### ISSUE THREAD

**Issue by luchuan163** [youzan/vant#393]
0.11.7版Tabs 标签页在移动端问题：
1、滚动的时候很卡，动画不流畅
2、横向滚动：当前选中的不能定位到中间

**Comment by chenjiahan** [comment]
@luchuan163 感谢反馈，这两个问题将在下个版本中优化

**Comment by chenjiahan** [comment]
已在 0.11.8 中优化
