### ISSUE TITLE
Vant React 版本火热开发中 🔥

### ISSUE THREAD

**Issue by mxdi9i7** [youzan/vant#3930]
### 这个功能解决了什么问题
习惯用React的开发者可以更好地利用这个组件库

### 描述您想要的解决方案
我想献出我的一份力一起帮忙开发这个React组件库

### 建议的API是什么样的
N/A

仓库地址：https://github.com/mxdi9i7/vant-react

**Comment by chenjiahan** [comment]
抱歉，目前的我们没有精力去维护其他版本的 Vant，所以暂时没有计划推出 React 版本。

如果你有兴趣开发一个 React 版本，我们是很资瓷的 ^_^

**Comment by mxdi9i7** [comment]
好哇，我正好想弄个开源项目锻炼锻炼，你们这里有想业余时间一起做的小伙伴吗

**Comment by mxdi9i7** [comment]
React社区目前找不到vant这样高质量的移动端组件框架，我也不喜欢antd，我觉得是挺有用的

**Comment by chenjiahan** [comment]
可以在这个 issue 里征集一下有兴趣参与的小伙伴 ^_^

**Comment by chenjiahan** [comment]
好像没什么人响应，先 close 咯

**Comment by mxdi9i7** [comment]
我要开始开发React版本啦，感兴趣的小伙伴们看过来~ https://github.com/mxdi9i7/vant-react

**Comment by chenjiahan** [comment]
置顶咯，希望有更多小伙伴能一起参与😃

**Comment by wsh941102** [comment]
🔥加油

**Comment by PJing** [comment]
加油加油！！！超期待

**Comment by mxdi9i7** [comment]
希望有更多小伙伴可以加入到这个项目里面来，只要你有热情，都可以帮上忙
ps: 编写校对文档也是非常大的工作量

**Comment by richard1015** [comment]
加油👍

**Comment by noteScript** [comment]
有没有谁有兴趣开发一个flutter版本的vant

**Comment by mxdi9i7** [comment]
> 有没有谁有兴趣开发一个flutter版本的vant

可以可以，有这个项目的话我这边有四五个人会感兴趣一起做

**Comment by 1036225283** [comment]
大佬们，太好了！结合react-native简直无敌

**Comment by 1036225283** [comment]
能开个RN的项目吗，如果不考虑套壳的话，vue-vant足够了，我觉得继续搞react-vant意义不大。接套壳android的时候，发现没法使用websocket。RN才是android和ios的最好选择

**Comment by 1036225283** [comment]
我想直接把vant源码拷贝一份，然后一个一个组件转换成RN代码如何

**Comment by mxdi9i7** [comment]
> 我想直接把vant源码拷贝一份，然后一个一个组件转换成RN代码如何

你可以开一个RN项目，我们会全力支持

**Comment by mxdi9i7** [comment]
> 能开个RN的项目吗，如果不考虑套壳的话，vue-vant足够了，我觉得继续搞react-vant意义不大。直接套壳android的时候，发现没法使用websocket。RN才是android和ios的最好选择

技术社区里特别是国外用react的小伙伴也很多，所以vant react也会帮助到很多不用vue的前端项目

**Comment by 1036225283** [comment]
我直接初始化了一个RN项目，https://github.com/1036225283/react_native_vant.git

**Comment by huashaoZhao** [comment]
再把ng框架的Vant也开发一版就爽了

**Comment by frei-x** [comment]
支持一个

**Comment by chenjiahan** [comment]
文档里添加了 React 版本的链接，issue 先 close 了哈

**Comment by Allisonmrhuo** [comment]
力挺,支持 , react缺少一个美好的UI组件库, 如果vant官方提供了vant react移动端组件库,将一鸣惊人呀,目前市面上还没有react完善的移动端组件库, antd那个太不好用了,并且停止维护了

**Comment by mxdi9i7** [comment]
@Allisonmrhuo Antd移动UI库 停止维护了吗？有没有传送门

**Comment by pencilcheck** [comment]
would be nice to see official RN support
