### ISSUE TITLE
[Bug Report] tabs 在粘性布局下切换时自动滚动到顶部计算有误差

### ISSUE THREAD

**Issue by jamieYou** [youzan/vant#3931]
### 设备 / 浏览器
chrome

### Vant 版本
2.0.9

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/1th7c" target="_blank">hhttps://codesandbox.io/s/1th7c</a>

### 描述问题
当tabs处于吸顶状态时，切换tab后，代码的逻辑是滚动到刚好吸顶的位置
https://github.com/youzan/vant/blob/dev/src/tabs/index.js#L123
但实际情况可能会出现没有吸顶的情况，滚动的位置和预期的位置相差1px的可能。
因为我这边移动端为了做兼容，采用了 vw 作单位，实际计算的 px 会有小数

**Comment by Klozee** [comment]
我也遇到了,去官方发现给的示例也一样有这个问题,吸顶的bug这么明显什么时候修复啊

**Comment by chenjiahan** [comment]
有小数的情况下，这个 1px 应该是无法避免的，会造成什么问题嘛？

**Comment by jamieYou** [comment]
> 有小数的情况下，这个 1px 应该是无法避免的，会造成什么问题嘛？

示例那里可以看到，切换 tab 后，isFixed 从 true 变为 false，如果计算没有误差，isFixed 应该还是 true 的。
我这边的真实项目，isFixed 不同状态，ui 样式差异比较大，很容易看出切换时出现上面的问题

**Comment by jamieYou** [comment]
@chenjiahan 这个解决可以简单点
`setRootScrollTop(getElementTop(this.$el) - this.offsetTop);`
这一行代码，对有小数的情况进行一下补位即可 `Math.ceil()`

**Comment by chenjiahan** [comment]
试了下可以的，下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.1.0-beta.1 版本发布（正式版预计下周发布）

**Comment by BolinWang** [comment]
顺便可以把scrollIntoView()去掉么？第一次切换tab时  scrollIntoView很恶心

**Comment by chenjiahan** [comment]
为什么需要去掉呢
