### ISSUE TITLE
NumberKeyboard 数字键盘会卡顿

### ISSUE THREAD

**Issue by qinmanyu** [youzan/vant#3932]
2.0.5版本；使用数字键盘，在苹果手机会卡顿，输入过快，不灵敏

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by eliot-ye** [comment]
我也遇到这个问题了，有解决方法吗？

**Comment by lxc512157407** [comment]
> 2.0.5版本；使用数字键盘，在苹果手机会卡顿，输入过快，不灵敏

先修改源代码吧，用的click时间300毫秒的延迟，建议下期让官方去改：
代码位置是：node_modules/vant/es/number-keyboard/Key.js 文件 46、47、55、64行，vant版本是2.1.2
methods: {
    onFocus: function onFocus() {
      this.active = true;
    },
    onBlur: function onBlur() {
      this.active = false;
    },
    touchstart: function onClick() {
      this.onFocus();
      this.$emit('press', this.text, this.type);
    }
  },
  render: function render() {
    var h = arguments[0];
    var onBlur = this.onBlur;
    //如果有touch事件则绑定touchstart否则绑定click事件；
    var eventType=document.documentElement.ontouchstart?'touchstart':'click';
    return h("i", {
      "attrs": {
        "role": "button",
        "tabindex": "0"
      },
      "class": [BORDER, this.className],
      "on": {
        //把点击时间改为touchstar事件，避免ios的300毫米延迟的卡顿现象，即更改触发press的方式。
        [eventType]: this.touchstart,
        "touchmove": onBlur,
        "touchend": onBlur,
        "touchcancel": onBlur
      }

**Comment by chenjiahan** [comment]
目前存在点击延迟的情况很少了，除非是 UIWebView

**Comment by eliot-ye** [comment]
用的就是 UIWebView ……
