### ISSUE TITLE
[Bug Report] 吸顶功能在组件显示隐藏的时候错位

### ISSUE THREAD

**Issue by Klozee** [youzan/vant#3933]
### 设备 / 浏览器
safari/chrome

### Vant 版本
2.0.8

### Vue版本
2.5.2

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-em5ir?fontsize=14" target="_blank">https://codesandbox.io/embed/vant-issue-moban-em5ir?fontsize=14</a>

### 描述问题
我们有一个通讯录切换显示类型的功能,两个组件之间切换显示隐藏后,显示的组件的最后一个元素吸顶.已提供重现.

**Comment by chenjiahan** [comment]
已在 2.1.0-beta.1 版本发布（正式版预计下周发布）
