### ISSUE TITLE
datetimePicker v-model值随着滚动选择而发生改变，不是点击确定后改变

### ISSUE THREAD

**Issue by MaskHao** [youzan/vant#3934]
问题：
   `<van-cell size="large" required title="开始时间" :value="startTimeLabel" @click="selectStartTime" is-link/>
      <van-action-sheet v-model="startTimeShow">
        <van-datetime-picker
                v-model="currentDate"
                type="datetime"
                :min-date="minDate"
                :max-date="maxDate"
                @confirm="confirmStartTime"
                @cancel="cancelStartTimeShow"
                :formatter="formatter"
        />
      </van-action-sheet>`
v-model绑定时间，控件时间change的时候startTime值就会发生改变，如果想获取确定后时间才发生改变，只能调用confirm？？。如果我同一页面列表有多个时间控件，如何每个控件传入当前的ID?如
`<van-datetime-picker
                v-model="currentDate"
                type="datetime"
                :min-date="minDate"
                :max-date="maxDate"
                @confirm="(value, item.id)=>confirmStartTime(value, item.id)"
                @cancel="cancelStartTimeShow"
                :formatter="formatter"
        />`
这种??

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
