### ISSUE TITLE
配置自动按需引入组件，连续报出3条warning

### ISSUE THREAD

**Issue by gaojian88888888** [youzan/vant#3935]
在.babelrc引入如下图
![image](https://user-images.githubusercontent.com/33544855/61680761-61630380-ad3d-11e9-87c7-149ffd358b45.png)

编译时连续报3条warning，但暂时不影响功能使用
![image](https://user-images.githubusercontent.com/33544855/61680854-ad15ad00-ad3d-11e9-8a49-2d066a91168c.png)
请问该怎么解决

**Comment by chenjiahan** [comment]
建议看下是不是 `postcss-viewpost-units` 插件的问题

**Comment by gaojian88888888** [comment]
> 看下建议的英文不是`postcss-viewpost-units`插件的问题

感谢解答，好像并不是的，因为我的项目中并没有postcss-viewpost-units这个插件

**Comment by gaojian88888888** [comment]
> 建议看下是不是 `postcss-viewpost-units` 插件的问题

感谢解答，好像并不是的，因为我的项目中并没有postcss-viewpost-units这个插件

**Comment by chenjiahan** [comment]
你应该是间接引用了，因为报错信息是 `postcss-viewpost-units` 抛出的
