### ISSUE TITLE
[Bug Report] Dialog使用异步关闭，点击取消，报错 ' Uncaught (in promise) cancel '

### ISSUE THREAD

**Issue by AtlantaCaesar** [youzan/vant#3937]
### 设备 / 浏览器
google

### Vant 版本
2.0.9

### Vue版本
2.6.10

### 重现链接
<a href="https://tfxkq.codesandbox.io/" target="_blank">https://tfxkq.codesandbox.io/</a>

### 描述问题
vue单页面应用中，使用Dialog 异步关闭，点击取消按钮，google浏览器报错 ' Uncaught (in promise) cancel '，代码就是vant文档中Dialog异步关闭的代码。

**Comment by chenjiahan** [comment]
这个是 Promise reject 未被 catch 的正常提示，不影响页面运行，如果不想看到，可以加个 catch 处理一下

`Dialog().catch(() => {});`

**Comment by M69W** [comment]
https://vant-contrib.gitee.io/vant/#/zh-CN/dialog#yi-bu-guan-bi
或
https://youzan.github.io/vant/#/zh-CN/dialog#yi-bu-guan-bi
异步关闭
demo 也是报这个错误提示

**Comment by iShawnWang** [comment]
+1 遇到了同样的问题, 老项目 2.x 确实要手动 catch 一波, 最新版 4.x 已经不需要了
