### ISSUE TITLE
[Feature Request] 建议修改 Field 组件 error-message 位置

### ISSUE THREAD

**Issue by justjoker** [youzan/vant#3938]
### 这个功能解决了什么问题
现在的位置会把错误信息放到 harline 里边，感觉影响组件的整体性

### 描述您想要的解决方案
把错误信息放到 hairline下面

### 建议的API是什么样的
error-message-position 可选值 :  'inside','outside'

**Comment by chenjiahan** [comment]
暂无计划修改哈，目前我们倾向于放在内部，更直观。加个属性不是很有必要
