### ISSUE TITLE
[Bug Report] 在弹出窗体的beforeClose中显示错误并阻止窗体关闭失效

### ISSUE THREAD

**Issue by shengxq** [youzan/vant#3944]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.0-beta.0

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-y2qk7?fontsize=14" target="_blank">https://codesandbox.io/s/vant-issue-moban-y2qk7?fontsize=14</a>

### 描述问题
在弹出窗体的beforeClose中，如果有错误，显示错误，并且阻止窗体关闭失效
此代码在1.3版本中可以阻止窗体关闭，在1.6，2.0版本中均失效
```
            this.$dialog.confirm({
                title: '窗体1',
                message: '弹窗内容',
                beforeClose: function (action, done) {
                    this.$dialog.alert({ title: '窗体2', message: '错误提示' });
                    done(false);  //这里调用了done(false)，窗体1不应该关闭 
                }
            });
```

**Comment by chenjiahan** [comment]
页面上只会存在一个 Dialog，当你第二次调用弹出的时候，第一个弹窗就被覆盖掉了

如果你需要展示多个弹层，可以考虑用组件调用的方式

**Comment by shengxq** [comment]
相同的代码在1.3版本中可以啊
而且 这种需求挺正常的  比如基本资料的 修改界面
我修改完了  点击保存  提交到服务器后 再关闭窗体
点击保存的时候 如果有错误了，alert报个错
我的 Dialog.show的 这个Dialog是 组件方式调用的
1.3版本好用   1.6  2.0版本 均不好用

**Comment by shengxq** [comment]
> 页面上只会存在一个 Dialog，当你第二次调用弹出的时候，第一个弹窗就被覆盖掉了
> 如果你需要展示多个弹层，可以考虑用组件调用的方式
难道1.3版就  页面可以存在多个 Dialog??

**Comment by chenjiahan** [comment]
从交互上来说，报错建议用 Toast

另外目前版本的逻辑是正确的，如果有多个弹窗的需求，请使用组件调用 Dialog
