### ISSUE TITLE
[Bug Report] cell 的value 英文字母不能完全显示，中文显示正常

### ISSUE THREAD

**Issue by junj1e** [youzan/vant#3947]
### 设备 / 浏览器
chrome

### Vant 版本
2.0.9

### Vue版本
2.6.10

### 重现链接
<a href="https://jsfiddle.net/novawithu/qxatj6v7/1/" target="_blank">https://jsfiddle.net/novawithu/qxatj6v7/1/</a>

### 描述问题
cell 的value 英文字母不能完成显示，中文显示正常

**Comment by junj1e** [comment]
测试iphone x 华为mate20也有次bug

**Comment by huangysss** [comment]
```
.van-cell__value {
    word-break: break-word | break-all;
}
```
设置一下word-break试试。
