### ISSUE TITLE
[Feature Request] 球球提供指定兼容性版本的API，供我们选择

### ISSUE THREAD

**Issue by warmilk** [youzan/vant#3948]
### 这个功能解决了什么问题
这个功能解决了苹果和Google之间狗咬狗导致我们工程师工作量增多的问题。
安卓的机型千奇百怪，各种系统版本都有，绝大部分低端机甚至用的都是安卓4.0，里面搭载的浏览器，flex布局是阵亡的。。。另外Safari这个业界毒瘤/移动端IE就无需赘述了，css3 的 animation 在Safari里简直惨不忍睹，svg直接死亡。
我们有义务照顾那些用着廉价低端安卓手机的用户，让他们感受到没有被时代的潮流抛弃。

### 描述您想要的解决方案
将用到flex布局的组件，出多一个纯div布局的版本，简单粗暴点，直接两大版本算了，一个有用css3的，一个没有用css3的。或者你们做多一个类似 babel 的转译插件，能将最新的 css 代码，编译成指定版本的 css。

### 建议的API是什么样的
提供一个API，让我们在main.js里指定兼容到Android或者iOS的什么系统版本（准确来说，是浏览器的什么内核版本）。

**Comment by chenjiahan** [comment]
你说的这些 css3 属性，在移动端都支持的，配置一下 autoprefixer 就可以，而且 vant 提供的样式默认已经加上了 webkit 前缀

**Comment by warmilk** [comment]
> 你说的这些 css3 属性，在移动端都支持的，配置一下 autoprefixer 就可以，而且 vant 提供的样式默认已经加上了 webkit 前缀

主要是grid组件，用了flex弹性盒子布局，而不是传统的盒子布局。在低端机上是识别不了的，会出现大量样式错乱。

**Comment by chenjiahan** [comment]
flex 在移动端手机上都支持的，不会有你说的问题

https://caniuse.com/#search=flex

**Comment by warmilk** [comment]
> flex 在移动端手机上都支持的，不会有你说的问题
> 
> https://caniuse.com/#search=flex

这个我之前查过了。

但是真机上，flex的确是一大片排版错乱的。尤其是在做混合式开发时候，把网页嵌进去安卓原生webview，惨不忍睹

bug现场重现：小米4手机（2014年7月发布并销售）的微信app打开的网页

**Comment by warmilk** [comment]
主要是我接下来做的项目，面对的用户所用手机可能都是低端机，兼容性问题让人想想就瑟瑟发抖

**Comment by chenjiahan** [comment]
假设真的有一些上古机型不支持，我们也不计划提供 flex 的降级方案，抱歉喔

如果真的要兼容的话，你只能自己实现咯

**Comment by warmilk** [comment]
好的，也只能这样了【滚地哭

**Comment by chenjiahan** [comment]
哈哈，加油
