### ISSUE TITLE
SwipeCell和FastClick的冲突

### ISSUE THREAD

**Issue by diaobrother** [youzan/vant#3950]
浏览器：
chrome

vant版本：
2.0.9

vue版本：
2.6.10

问题描述：
SwipeCell阻止了横向touchmove的冒泡，导致FastClick在拖拽操作时，仍旧触发了点击事件。这个问题，我之前在用1.6.18版本中，没有出现

**Comment by diaobrother** [comment]
例子：
https://codesandbox.io/s/vue-template-3dnti?fontsize=14

**Comment by chenjiahan** [comment]
前个版本为了解决[这个问题](https://github.com/youzan/vant/issues/3880)，所以加了阻止冒泡的处理。

下个版本会加个属性来控制是否冒泡，默认会冒泡

**Comment by chenjiahan** [comment]
已在 2.1.0-beta.1 版本发布（正式版预计下周发布）
