### ISSUE TITLE
[Bug Report] 时间组件属性

### ISSUE THREAD

**Issue by SuperZhe** [youzan/vant#3951]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.0.0

### Vue版本
2.6.10

### 重现链接
<a href="https://0938w.codesandbox.io/" target="_blank">https://0938w.codesandbox.io/</a>

### 描述问题
日期选择组件，filter属性过滤出来日期选择间隔，选中确认后时间还是从1开始

**Comment by chenjiahan** [comment]
这个问题已经修复了，可以升级到最新版试下
