### ISSUE TITLE
ios10+ iphone6s SwipeCell 在微信上无法滑动

### ISSUE THREAD

**Issue by DelingAlieZ10** [youzan/vant#3953]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3015
