### ISSUE TITLE
能建交流群吗，小白使用过程中会遇到很多问题？

### ISSUE THREAD

**Issue by panggenhuang** [youzan/vant#3955]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/blob/dev/README.zh-CN.md
文档里有
