### ISSUE TITLE
DatetimePicker时间值问题

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#3956]
![image](https://user-images.githubusercontent.com/42930030/61844402-dd8e5000-aed1-11e9-9e3c-6233fb3ce713.png)
 最小时间，最大时间都是标准时间格式，为什么不支持时间戳呢？时间戳是一个很通用的东西，前后端都直接使用，vant组件时间格式和后端对接还有手动转换，毕竟要么是2018-05-01 15:11:00这周格式要么是时间戳，标准时间格式很烦

**Comment by codeamber** [comment]
你把下面这个方法写到确定按钮里面就可以进行标准时间的转换。
DateConfirm(val) {
      this.showTime = false
      var date = val;
      var seperator1 = "-";
      var seperator2 = ":";
      var month = date.getMonth() + 1;
      var strDate = date.getDate();
      var Hours = date.getHours();
      var Minutes = date.getMinutes();
      var Seconds = date.getSeconds();
      if (month >= 1 && month <= 9) {
        month = "0" + month;
      }
      if (strDate >= 0 && strDate <= 9) {
        strDate = "0" + strDate;
      }
      if (Hours >= 0 && Hours <= 9) {
        Hours = "0" + Hours;
      }
      if (Minutes >= 0 && Minutes <= 9) {
        Minutes = "0" + Minutes;
      }
      if (Seconds >= 0 && Seconds <= 9) {
        Seconds = "0" + Seconds;
      }
      val = date.getFullYear() + seperator1 + month + seperator1 + strDate + " " +
        Hours + seperator2 + Minutes + seperator2 + Seconds;
      this.eventForm.startTime  = val
    },

**Comment by chenjiahan** [comment]
时间戳和 Date 对象的转换成本并不高

```js
const timestamp = 1564036776927;
const date = new Date(timestamp)
```

**Comment by cangyu1993** [comment]
我知道成本不高，只是多了几步，从后端拿到得时间然后绑定默认值需要转换一次，提交更改后的时间给后端又转换了一次，写的时候感觉如果能支持时间戳那就爽了

**Comment by Rickykurt** [comment]
[dayjs](https://github.com/iamkun/dayjs)

**Comment by chenjiahan** [comment]
暂无计划支持哈
