### ISSUE TITLE
希望可以更加简单化文件上传功能

### ISSUE THREAD

**Issue by codeamber** [youzan/vant#3959]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
做一个图片多选上传和单个图片上传，前端处理的东西很多

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
