### ISSUE TITLE
[Bug Report] DatetimePicker时间选择器返回值出错问题

### ISSUE THREAD

**Issue by qc-web-y** [youzan/vant#3964]
### 设备 / 浏览器
所有

### Vant 版本
2.0.9

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/embed/vant-datetimepicker-bug-vsxoh" target="_blank">https://codesandbox.io/embed/vant-datetimepicker-bug-vsxoh</a>

### 描述问题
当type为time时，存在自定义formatter函数时，返回的值会为---NaN:NaN。
我看过之前有人提过同样的问题，测试了下发现在2.0.0是被修复了的，不知道是不是合并的时候弄错了，又出现了同样的错误，查看了最近的github源码是2.1.0-beta.1好像也仍然没有对type为time是的返回值进行单独的格式化处理。目前个人简单处理了下，不影响我自己项目的使用，但是还是希望官方尽早恢复哟！

**Comment by chenjiahan** [comment]
感谢反馈，这里确实因为最近的改动而出现了同样的错误，今天会修复掉

**Comment by chenjiahan** [comment]
已在 2.1.0-beta.2 版本修复，正式版会在下周发布

**Comment by yexiaodong** [comment]
"vant": "^3.1.0"，又出现改问题了。重新：第一次现在正常后，再选择一样的值时就会出现该问题

**Comment by chenjiahan** [comment]
@yexiaodong 能给个复现链接不

https://codesandbox.io/s/m5v3f
