### ISSUE TITLE
stepper 步进器怎样设置默认值为0?

### ISSUE THREAD

**Issue by wananzys** [youzan/vant#3965]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

![image](https://user-images.githubusercontent.com/44047260/61868629-590cf300-af0c-11e9-8d71-1a6bd9ed201c.png)
文档上没有相应属性

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
```html
<van-stepper v-model="value" :min="0" />
```

```js
export default {
  data() {
    return { value: 0 };
  }
}
```

这样即可
