### ISSUE TITLE
[Feature Request] 微信小程序团队开源了kbone工具，希望兼容下

### ISSUE THREAD

**Issue by stephenml** [youzan/vant#3968]
### 这个功能解决了什么问题
kbone工具是微信小程序团队开源的一款将Vue项目打包成微信小程序的工具，完整的移植了Vue Runtime，提供了微信小程序中运行的适配器，可以将现有的Vue项目直接打包成微信小程序代码

### 描述您想要的解决方案
在这个工具中试用了下你们的组件，大部分是可以直接运行的，但也有一些不兼容，在计算位置方面可能需要处理一下，例如：ImagePreview、Swipe等

### 建议的API是什么样的
N/A

**Comment by chenjiahan** [comment]
近期会调研一下

**Comment by chenjiahan** [comment]
看了下，这个工具目前还初步早期阶段，暂时不计划去兼容，后期如果有大量使用者，会考虑支持
