### ISSUE TITLE
尝试定制主题遇到的问题

### ISSUE THREAD

**Issue by TongZhangzt** [youzan/vant#397]
**What is the current behavior?**
Trying to create a custom theme by local build but failed.

**What is the expected behavior?**
Generate the style file and create a custom theme.

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
Vant: 0.11.8  Vue: 2.5.9  

-----

尝试定制主题，首先试了第二种本地构建，clone仓库后在运行npm run build的时候遇到错误，一直找不到postcss-easy-import包，安装之后还是报这个错误:
`Error: Cannot find module 'postcss-easy-import'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/.../vant/postcss.config.js:3:5)
    at Module._compile (module.js:570:32)
    at requireFromString (/Users/.../vant/packages/vant-css/node_modules/require-from-string/index.js:27:4)
    at /Users/.../vant/packages/vant-css/node_modules/cosmiconfig/lib/loadJs.js:11:15`

然后尝试了第一种用postcss，按照postcss要求安装配置了webpack:
` {
                test: /\.css$/,
                exclude: /node_modules/,
                use: [
                    { loader: 'style-loader' },
                    { loader: 'css-loader', options: { importLoaders: 1 } },
                    { loader: 'postcss-loader' }
                ],
                include: __dirname + '/src'
    }`
然后再启动文件中按文档引入base.css和对应组件的css，此时没有修改post.config文件，发现组件只有base样式，没有对应组件的样式，修改了post.config之后也没有变化，是步骤有遗漏吗？感谢！

**Comment by chenjiahan** [comment]
@TongZhangzt 

1. 本地构建需要安装好对应的 npm 依赖，执行 npm run bootstrap 即可安装。
2. 使用 postcss 时请注意保证配置了 vant 所依赖的插件，文档里的配置都需要有

**Comment by TongZhangzt** [comment]
之前是因为在vant-css目录执行了build script。感谢回复，问题已解决！
