### ISSUE TITLE
[Feature Request] list组件只能在整个页面下不能在父元素下滚动吗？

### ISSUE THREAD

**Issue by stalkercn** [youzan/vant#3971]
### 这个功能解决了什么问题
https://youzan.github.io/vant/mobile.html#/zh-CN/list
整个页面  包括底部tabbar  顶部navbar都会跟着滚动消失   难道滚动不应该是相对父元素滚动的吗

### 描述您想要的解决方案
内容随父元素滚动

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
局部滚动的话，在父元素上设置 `height: xxx px; overflow: scroll` 即可

**Comment by stalkercn** [comment]
由于移动端设备的多样性  导致在大多数情况下父元素的高度都是不固定的  而且嵌套很多层  我试了下  高度如果不是固定值而是百分比的话overflow: scroll是无效的

`<div style="display: flex; flex-direction: column;">
    <div style="height: 100px"></div>
    <div style="flex: auto">
        <div style="height: 100%">
             <div style="height: 100%">
                  <div class="van-list" style="height: 100%; overflow: scroll">
                      <div class="van-cell">...</div>
                      <div class="van-cell">...</div>
                       ...
                       ...
                      <div class="van-cell">...</div>
                  </div>
             </div>
        </div>
    </div>
</div>`

**Comment by chenjiahan** [comment]
tabbar 和 navbar 都可以设置为 fixed，这样就不会跟随滚动

**Comment by L-Jings** [comment]
> tabbar 和 navbar 都可以设置为 fixed，这样就不会跟随滚动
我头部和底部设置fixed固定定位，list不设置固定px高度，还是全屏滚导致头部nav看不见了
