### ISSUE TITLE
[Bug Report] 混合开发，swipe-cell拦截ios原生侧边手势

### ISSUE THREAD

**Issue by ZhengXiaowei** [youzan/vant#3976]
### 设备 / 浏览器
IOS

### Vant 版本
2.1.0-beta.2

### Vue版本
2.6.10

### 描述问题
在用vant进行混合开发的时候，在ios的wkwebview中，使用swipe-cell会阻止原生的侧边手势 不使用swipe-cell的时候则没这问题 是不是因为swipe-cell中的 touchmove Defaultprevent的原因？

**Comment by chenjiahan** [comment]
是的，从交互上来说，滑动 SwipeCell 的时候不应该触发侧边滑动，这个是符合预期的

**Comment by ZhengXiaowei** [comment]
有办法解决吗 我看了源码 在滑动的过程就会去prevent 而不会去在乎是否从哪个方向去滑动 不管那个方向是否开了cell

**Comment by chenjiahan** [comment]
下个版本会优化下，如果是打开的状态，会根据滑动方向来判断是否需要 prevent

**Comment by ZhengXiaowei** [comment]
好的 辛苦！

**Comment by chenjiahan** [comment]
已在 2.1.0 版本优化，可以试下

**Comment by tivisGu** [comment]
你好，我也发生了同样的问题。请问有样例代码么，IOS 向右滑动被cell的右滑事件阻止了
