### ISSUE TITLE
使用dialog里面的confirm，点击按钮报错

### ISSUE THREAD

**Issue by fuyidaotang** [youzan/vant#3978]
设备 / 浏览器
IOS

Vant 版本
2.1.0-beta.2

Vue版本
2.6.10

描述问题
使用confirm组件的时候报错，不管确定取消都会报这两个错误，touchstart of undefined  
click of undefined
![image](https://user-images.githubusercontent.com/15215747/61937911-7dc3a200-afc2-11e9-9c77-6da5cd2d2e42.png)

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接

**Comment by JacobMa1996** [comment]
请问这个问题解决了吗？我使用1.6.23的版本仍然出现这个问题

**Comment by fuyidaotang** [comment]
> 请问这个问题解决了吗？我使用1.6.23的版本仍然出现这个问题

解决了，是我的vue版本问题，更新到最新版本到vue后问题解决
