### ISSUE TITLE
[Feature Request] 建议picker组件增加多选及搜索功能，不然可选项非常多的时候，选择不方便

### ISSUE THREAD

**Issue by Kennersky** [youzan/vant#3979]
### 这个功能解决了什么问题
当picker选项相当多的情况下，可以通过搜索来快速定位并选择。

### 描述您想要的解决方案
选项上面增加搜索框，多选模式时选项可以有checked多选

### 建议的API是什么样的
multiple=true开启多选；
search=true开启搜索

**Comment by chenjiahan** [comment]
暂无计划支持呢，你说的交互更符合 Select 组件，移动端 Picker 交互里没有这样的设计

**Comment by Kennersky** [comment]
> 暂无计划支持呢，你说的交互更符合 Select 组件，移动端 Picker 交互里没有这样的设计

那有无做select组件的计划呢？

**Comment by chenjiahan** [comment]
木有
