### ISSUE TITLE
Radio 组 展示效果建议

### ISSUE THREAD

**Issue by yajore** [youzan/vant#398]
**What is the current behavior?**
Radio 组和Cell一起使用的时候，建议增加右侧Radio
选中和文字都集中在左侧，右侧空的很大很突兀
尤其在选择支付方式 目前 radio+图标+文字
如果变成 图标+文字  + radio（右侧） 展示方式比较好
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@yajore 好的，我们会优化这部分的示例~ 不过在项目中使用时还是需要自己写样式控制 Radio 的位置

**Comment by chenjiahan** [comment]
已优化~
