### ISSUE TITLE
[Bug Report] Sticky组件局部滚动bug

### ISSUE THREAD

**Issue by ljf15135429192** [youzan/vant#3981]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="https://暂无.com/" target="_blank">https://暂无.com/</a>

### 描述问题

body全局滚动下Sticky组件吸顶效果正常

局部滚动下Sticky组件会提前吸顶

观察源码,判断依据是
scrollTop   offsetTop > topToPageTop

getElementTop 获取值element.getBoundingClientRect().top   getRootScrollTop()组成

export function getRootScrollTop() {
  return window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0;
}
局部滚动下getRootScrollTop值是否应该为滚动元素的scrollTop而非body？？？
或者直接通过滚动值大于元素距离顶部值来判断？？？

**Comment by chenjiahan** [comment]
近期会看下这个问题

**Comment by chenjiahan** [comment]
已在 2.1.2 版本修复
