### ISSUE TITLE
[Bug Report] Sku组件在不填写messages报错

### ISSUE THREAD

**Issue by yangy9593** [youzan/vant#3986]
### 设备 / 浏览器
Chrome

### Vant 版本
2.1.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-mwmlq" target="_blank">https://codesandbox.io/s/vant-issue-moban-mwmlq</a>

### 描述问题
按照官方的实现，在sku对象中没有传入message报错" "TypeError: Cannot read property 'map' of undefined""

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.1.0 版本修复
