### ISSUE TITLE
sticky组件失效

### ISSUE THREAD

**Issue by Tiramisu1** [youzan/vant#3987]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
全局引入vantUI 在某页面使用sticky组件是既不报错也没有吸顶的效果，请问是什么原因呢

**Comment by chenjiahan** [comment]
建议看下是否安装了最新版本的 vant，Sticky 是新加入的组件

**Comment by Tiramisu1** [comment]
> 建议看下是否安装了最新版本的 vant，Sticky 是新加入的组件 vantui d版本是2.0.9

**Comment by 554894305** [comment]
我也是这样的， 既不报错也没有吸顶的效果，不知道什么原因

**Comment by liuxiaohui1218** [comment]
看下最近的非body祖先元素是否设置overflow-y:auto,但是没有设置高
