### ISSUE TITLE
ImagePreview预览多张图片

### ISSUE THREAD

**Issue by jswy** [youzan/vant#3989]
使用ImagePreview预览多张图片时，双击其中一张放大，展示其他的图片时也会按照刚才放大的倍率进行放大，请问有没有什么方法能在展示前，将图片还原成初始的默认状态？

**Comment by JakeLaoyu** [comment]
提供一下 vant版本

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
