### ISSUE TITLE
NoticeBar 滚动动画animationend事件兼容性问题

### ISSUE THREAD

**Issue by qianzhaoy** [youzan/vant#399]
问题: 
  NoticeBar 动画的 animationend 事件在某些浏览器内无效. 导致滚动行为只能执行一轮.

重现:
 Android 版本: 5.1.1 <夸克浏览器>  
 vue: 2.5.0
 vant: 0.11.4

建议: 
 加上兼容事件方式
 `@webkitAnimationEnd="onAnimationEnd"`

**Comment by chenjiahan** [comment]
@qianzhaoy 感谢反馈，将在下个版本中修复

**Comment by chenjiahan** [comment]
已在 0.11.9 中修复
