### ISSUE TITLE
[Bug Report] TreeSelect的click-nav和click-item事件穿透问题

### ISSUE THREAD

**Issue by jianggle** [youzan/vant#3991]
### 设备 / 浏览器
win10/chrome

### Vant 版本
2.0.9

### Vue版本
2.6.10

### 描述问题
TreeSelect的click-nav和click-item事件会存在穿透问题

**Comment by chenjiahan** [comment]
具体是指？

**Comment by jianggle** [comment]
> 具体是指？

比如把TreeSelect组件放在一个弹出的遮罩上，遮罩层有一个closeMask事件，click-nav和click-item事件最终都会触发closeMask事件，，我觉着应该是要在TreeSelect内部的click上加个.stop修饰符

**Comment by chenjiahan** [comment]
事件冒泡是正常的逻辑，如果想阻止冒泡，可以这样写

```html
<van-tree-select @click.native.stop />
```

**Comment by jianggle** [comment]
> 事件冒泡是正常的逻辑，如果想阻止冒泡，可以这样写
> 
> ```
> <van-tree-select @click.native.stop />
> ```

竟然忘了有这茬￣□￣｜｜ 谢谢
