### ISSUE TITLE
[Feature Request] Icon规范

### ISSUE THREAD

**Issue by YYN-MR** [youzan/vant#3992]
### 这个功能解决了什么问题
图标实底和线框映射统一；
如 balance-list-o -> balance-list;
而现有的 credit-pay -> credit;规范不一致；
且存在一些无法映射的图标；

### 描述您想要的解决方案
实底和线框 Icon应该一一对应；

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/2410
