### ISSUE TITLE
[Bug Report] ImagePreview v-slot:index 无效

### ISSUE THREAD

**Issue by qianbimomo** [youzan/vant#3999]
### 设备 / 浏览器
华为nova3

### Vant 版本
2.1.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vue-template-1b7iv" target="_blank">https://codesandbox.io/s/vue-template-1b7iv</a>

### 描述问题
预览图片v-slot:index ,插槽无效，不会显示

**Comment by qianbimomo** [comment]
超过手机屏幕长度图片，导致v-slot不显示，v-slot若要显示其他效果呢？
![preview](https://user-images.githubusercontent.com/25896015/62098425-dc3b9980-b2bc-11e9-97cc-b33b30870d74.png)

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.1.0 版本修复
