### ISSUE TITLE
2.0.9 Tabs 在 sticky 模式下滚动 滚动太长会导致tab不能持续固定

### ISSUE THREAD

**Issue by dhx1213** [youzan/vant#4001]
2.0.9 Tabs 在 sticky 模式下滚动 滚动太长会导致tab不能持续固定

**Comment by dhx1213** [comment]
![111](https://user-images.githubusercontent.com/35554865/62107073-6c87d780-b2d9-11e9-8552-d3a185737155.gif)

**Comment by JakeLaoyu** [comment]
提供复现demo https://codesandbox.io/s/m5v3f

**Comment by dhx1213** [comment]
demo 没重现问题，不过我重新使用1.6.24版本 代码不动的情况下 bug已经消失了

**Comment by chenjiahan** [comment]
麻烦试下 2.0.9 还会有问题吗

**Comment by dhx1213** [comment]
> 麻烦试下 2.0.9 还会有问题吗

有demo就是2.0.9，简单的demo没问题，不知道问题出在哪，100条数据滚动到51条的时候就会出现问题，滚动到列表总数的一半的时候就会出问题，我太菜了找不到bug，只能老办法用1.x

**Comment by chenjiahan** [comment]
无法复现的话先关闭咯
