### ISSUE TITLE
[Bug Report] datetimepicker 组件在ios10下浏览器打开时不能滚动只能点选

### ISSUE THREAD

**Issue by flyer153** [youzan/vant#4003]
### 设备 / 浏览器
ios10

### Vant 版本
2.1.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/datetime-picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/datetime-picker</a>

### 描述问题
datetimepicker 组件在ios10下浏览器打开时不能滚动只能点选。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3015
