### ISSUE TITLE
[Bug Report] ImagePreview无法阻止冒泡事件

### ISSUE THREAD

**Issue by wodelu** [youzan/vant#4005]
### 设备 / 浏览器
iphone6plus

### Vant 版本
2.1.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="https://7lzhk.csb.app/" target="_blank">https://7lzhk.csb.app/</a>

### 描述问题
有父组件A和子组件B，ImagePreview在B中调用，但是打开ImagePreview后点击图片会触发A组件中包含B组件的父元素的click事件，B组件中调用ImagePreview时使用了@click.stop，但是在安卓手机没问题，ios有问题

**Comment by chenjiahan** [comment]
ImagePreview 本身没有提供 click 事件，所以阻止冒泡需要写成 `@click.native.stop`

**Comment by wodelu** [comment]
你好，我是在调出ImagePreview后，点击图片的时候出现了外层函数执行，并不是在调出ImagePreview的时候。不知道您看得到我的源码吗？困扰已久，麻烦帮忙看看，谢谢！

**Comment by chenjiahan** [comment]
```html
<van-image-preview @click.native.stop />
```

这样写

**Comment by wodelu** [comment]
确实可以了！谢谢谢谢
