### ISSUE TITLE
循环遍历tab组件，在tab组件中，使用<van-dropdown-menu>组件，使用该组件animated属性，会导致切换tab栏，下拉菜单弹窗无法正常弹出，只会在索引为 0 的tab栏下弹出

### ISSUE THREAD

**Issue by duanxingyu** [youzan/vant#4006]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
