### ISSUE TITLE
[Bug Report] Dialog如何传入index或者自定义变量？

### ISSUE THREAD

**Issue by YJHecho** [youzan/vant#4012]
### 设备 / 浏览器
浏览器

### Vant 版本
2.1.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/checkbox" target="_blank">https://youzan.github.io/vant/#/zh-CN/checkbox</a>

### 描述问题
```
//删除功能
      catdelete(index){
        console.log(index);
        Dialog.confirm({
          title: '',
          message: '确认删除该商品吗？',
          cancelButtonColor:'#ff8c00',
          confirmButtonColor:'#cccccc',
        }).then((index) => {
          // on confirm
          console.log("确定删除"  this.index)
          this.catlist.splice(index, 1)
        }).catch((index) => {
          // on cancel
          console.log("取消删除"  index)
          // this.list.splice(index, 1)
        });
      },
```
输出的index是confirm或者cancel

**Comment by chenjiahan** [comment]
把`then((index) => {` 里的 `index` 去掉就可以

这个用法和 Dialog 无关，是你自己的函数传参问题

**Comment by YJHecho** [comment]
> 把`then((index) => {`里的`index`。去掉就可以
> 
> 这个用法和Dialog无关，是你自己的函数传参问题

十分感谢  解决了
