### ISSUE TITLE
[Bug Report] dateTimePicker无法滚动

### ISSUE THREAD

**Issue by RabbDream** [youzan/vant#4013]
### 设备 / 浏览器
ios 12.4

### Vant 版本
2.1.0-beta.2

### Vue版本
2.5.13

### 重现链接
<a href="http://www.360doc.com/relevant/308454596_more.shtml" target="_blank">http://www.360doc.com/relevant/308454596_more.shtml</a>

### 描述问题
在手机上,安卓没有问题,ios使用用日期选择无法滚动

**Comment by chenjiahan** [comment]
链接似乎和问题无关
