### ISSUE TITLE
索引报错Injection "vanIndexBar" not found

### ISSUE THREAD

**Issue by JasonOracle** [youzan/vant#4014]
`[Vue warn]: Injection "vanIndexBar" not found

found in

---> <VanIndexAnchor>
       <VanIndexBar>
         <VanPopup>
           <Home> at D:\vue\JiaRiShop\src\components\Home.vue
             <App> at D:\vue\JiaRiShop\src\App.vue
               <Root>`
不知道咋回事,引入方式没问题,根据官方的,vant版本是2.0
Injection "vanIndexBar" not found

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
