### ISSUE TITLE
[Bug Report] 引入grid组件Injection "vanGrid" not found

### ISSUE THREAD

**Issue by JasonOracle** [youzan/vant#4017]
### 设备 / 浏览器
chrome

### Vant 版本
2.0.9

### Vue版本
3.9.3

### 重现链接
<a href="http://127.0.0.1:8082/?#/" target="_blank">http://127.0.0.1:8082/?#/</a>

### 描述问题
正常引入grid组件,运行就报错,
vue.runtime.common.js?d43f:477 [Vue warn]: Injection "vanGrid" not found

found in

---> <VanGridItem>
       <VanGrid>
         <Home> at D:\vue\JiaRiShop\src\components\Home.vue
           <App> at D:\vue\JiaRiShop\src\App.vue
             <Root>

我再html中用的也是官方的示例
  <van-grid>
  <van-grid-item
    v-for="value in 4"
    :key="value"
    icon="photo-o"
    text="文字"
  />
</van-grid>
但是没用

![微信图片_20190731163616](https://user-images.githubusercontent.com/41275539/62197820-20a96100-b3b3-11e9-906c-b459357efdd9.png)
![微信图片_20190731163631](https://user-images.githubusercontent.com/41275539/62197821-2141f780-b3b3-11e9-964b-71a1a50502c6.png)
![微信图片_20190731163636](https://user-images.githubusercontent.com/41275539/62197822-2141f780-b3b3-11e9-9efc-b3567218213a.png)

**Comment by JasonOracle** [comment]
![微信图片_20190731165027](https://user-images.githubusercontent.com/41275539/62197947-5e0dee80-b3b3-11e9-9502-a9c4d96cd6b5.png)
y用的官方示例代码

**Comment by chenjiahan** [comment]
麻烦提供下 codesandbox 复现链接

**Comment by Wayne-007** [comment]
解决了吗？我也遇到了～
