### ISSUE TITLE
[Feature Request] van-tabs标签栏滚动 可以手动滚动吗

### ISSUE THREAD

**Issue by woodThunder** [youzan/vant#4018]
### 这个功能解决了什么问题
标签通过点击滚动

### 描述您想要的解决方案
类似今日头条手机网页版，在不切换的情况下，滚动查看其它标签

### 建议的API是什么样的
可以增加参数来判断点击滚动还是手动滚动

**Comment by chenjiahan** [comment]
你说的是标签栏较多时横向滚动吗，目前支持的

**Comment by woodThunder** [comment]
现在是点击标签才可以滚动的，可以不点击标签页能滚动吗？

**Comment by chenjiahan** [comment]
手势也可以滑动呀
