### ISSUE TITLE
vant支持富文本吗，遇到富文本编辑的内容怎么渲染的

### ISSUE THREAD

**Issue by dleomiss** [youzan/vant#4020]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
