### ISSUE TITLE
[Feature Request] sku组件默认选中的值能否动态改变

### ISSUE THREAD

**Issue by WWBingBing** [youzan/vant#4021]
### 这个功能解决了什么问题
在使用sku组件时，发现默认选中的选项值只能写死，不能更新。假如设置的默认选中的规格已经售完的话，显示出来的有问题。能够让默认选中的值可以动态改变。

### 描述您想要的解决方案
解决默认选中的值可以动态改变

### 建议的API是什么样的

 initialSku 对象结构
{
  // 键：skuKeyStr（sku 组合列表中当前类目对应的 key 值）
  // 值：skuValueId（规格值 id）
  s1: '30349',
  s2: '1193',
  // 初始选中数量
  selectedNum: 3
}

**Comment by Codpoe** [comment]
”动态改变“的意思是弹出`Sku`后再更新`initialSku`吗？

**Comment by WWBingBing** [comment]
> ”动态改变“的意思是弹出`Sku`后再更新`initialSku`吗？

数据请求回来时，可以根据库存去重置`initialSku`

**Comment by Codpoe** [comment]
近期会支持✨

**Comment by chenjiahan** [comment]
已在 2.1.6 版本支持
