### ISSUE TITLE
[Feature Request] van-upload的isImageUrl方法

### ISSUE THREAD

**Issue by confidenceAllen** [youzan/vant#4022]
### 这个功能解决了什么问题
文件上传

### 描述您想要的解决方案
fileList 参数支持传入的值为url，content等等。但是如果url的参数没有包括图片类型['jpeg', 'jpg', 'gif', 'png', 'svg']后缀则判断不是图片，有一下后端是只带文件id去拿图片的。希望去除这个isImageUrl方法判断。

### 建议的API是什么样的
希望去除这个isImageUrl方法判断。含有url参数就可以了。

**Comment by chenjiahan** [comment]
有些文件是无法预览的，比如 pdf，所以要对文件类型做校验

你说的文件 id 具体是什么格式呢

**Comment by confidenceAllen** [comment]
请求地址+'?fileId='+‘23213das5454’
组成的一串地址

**Comment by sevilen** [comment]
#4030 需要isImageUrl这个方法对文件类型判断，才能实现预览文件。但是用云存储的话，图片链接没有文件类型后缀也是常见的。好像也没有很好的办法对这类Url判断。

**Comment by chenjiahan** [comment]
对于这种特殊情况，后续会支持通过添加 `isImage` 标记来声明是图片类型

**Comment by chenjiahan** [comment]
已在 2.1.2 版本支持

**Comment by confidenceAllen** [comment]
哈哈哈 之前忘了回复了。就加一个属性就解决了

**Comment by JadeLiuYC** [comment]
fileList 里的url的值必须是路径吗？ base64 或者blob不能显示吗？@chenjiahan

**Comment by chenjiahan** [comment]
可以展示的，标记 isImage 就行

**Comment by JadeLiuYC** [comment]
> 可以展示的，标记 isImage 就行

fileList 数组里面每个对象需要填写哪些属性？
 {
    isImage: true,
    url: "blob:http://localhost:8080/3de774f6-6e66-4c80-8c5b-56448c52291f"
}
原本后台返回的只有个id，通过接口处理成blob格式，但是上面的格式直接赋给fileList不生效，但是直接把url的值赋给img就可以显示。
