### ISSUE TITLE
多个Popup同时触发时，底层的遮罩层消失。在微信浏览器与uc浏览器结果不统一

### ISSUE THREAD

**Issue by zwb474287221** [youzan/vant#4023]
问题：底层的遮罩层消失，新的部分不显示
https://wap.yangwuxian.cn
1、登陆
2、点击在首页的评论icon
3、点击评论的内容
在微信浏览器和uc浏览器出现
谷歌浏览器是好的

**Comment by chenjiahan** [comment]
应该是 Popup 嵌套导致的，可以在里面的 Popup 上添加 `get-container="body"` 试试

**Comment by zwb474287221** [comment]
可以了，谢谢

**Comment by zwb474287221** [comment]
@chenjiahan get-container="body" 一个组件只能一个吗，我里面有两个同级的Popup和一ActionSheet，我加上两个以上get-container="body" 这组件就加载不出来

**Comment by zwb474287221** [comment]
@chenjiahan 同一组件的两个同级的Popup不能同时挂载。

**Comment by chenjiahan** [comment]
应该可以的，你的写法具体是什么样呢
