### ISSUE TITLE
ImagePreview组件预览图片,点击安卓返回键,会返回上一页

### ISSUE THREAD

**Issue by wananzys** [youzan/vant#4024]
设备: 安卓

代码: 
ImagePreview({ 
       images: imageUrlList, 
       startPosition: position, 
       closeOnPopstate: true
 });

问题描述: 点击安卓返回键,  返回上一页面, ,没有停留在当前页

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3902

**Comment by wananzys** [comment]
> 参见 #3902

路由用的hash模式,不能用你这个方法,ImagePreview组件能否对安卓手机物理返回键做一下优化呢 @chenjiahan

**Comment by chenjiahan** [comment]
组件内无法对物理返回键做处理

**Comment by VenusPP** [comment]
主要使用浏览器history对象处理原生后退或前进事件
// 当图片放大时，使用pushState 塞入一个地址
history.pushState({}, '', location.href+'&XXX');
// 当点击图片缩小时，使用replaceState 替换地址，并手动后退
history.replaceState({}, '', location.href.split('&album=1')[0]);
history.back();
// 最后监听返回事件
window.addEventListener("popstate", function() {  
    if(逻辑处理条件){
        逻辑处理(主要是使遮罩层消失)
    }                     
});
@wananzys
