### ISSUE TITLE
[Bug Report] 更新2.1.0后DatetimePicker的confirm cancel 事件失效

### ISSUE THREAD

**Issue by likess921** [youzan/vant#4025]
### 设备 / 浏览器
ios12、ios10、android9，谷歌浏览器

### Vant 版本
2.1.0

### Vue版本
2.6.10

### 重现链接
<a href="http://www.baidu.com" target="_blank">http://www.baidu.com</a>

### 描述问题
vant更新2.1.0后，datetimepicker组件的确定 取消 事件失效。

**Comment by 908023777** [comment]
我试了下 确实失效了

**Comment by chenjiahan** [comment]
会马上发一个版本修复

**Comment by chenjiahan** [comment]
已在 2.1.1 版本修复
