### ISSUE TITLE
nuxtjs 引入出现错误

### ISSUE THREAD

**Issue by hehuachina** [youzan/vant#403]
Cannot read property 'requestAnimationFrame' of undefined
9476   var iRaf = global.requestAnimationFrame || global.webkitRequestAnimationFrame || fallback;

版本： "vue": "^2.5.3"

引入方法：
    plugins: [
        {src: '~plugins/vant'}
    ],

import Vue from 'vue';
import Vant from 'vant';
import 'vant/lib/vant-css/index.css';

Vue.use(Vant);

用只在客户端引入，没有此错误
    plugins: [
        {src: '~plugins/vant', ssr: false}
    ],

**Comment by chenjiahan** [comment]
感谢反馈，下个版本修复此问题

**Comment by chenjiahan** [comment]
已在 0.11.9 中修复

**Comment by QThans** [comment]
0.12.3 貌似还要这个问题

**Comment by chenjiahan** [comment]
@QThans 我试了下 0.12.3 是正常的噢
