### ISSUE TITLE
[Bug Report] Upload组件阿里云OSS图片链接无文件后缀无法显示

### ISSUE THREAD

**Issue by sevilen** [youzan/vant#4030]
### 设备 / 浏览器
Mbp mojave 10.14.5/

### Vant 版本
2.1.0

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-oqhg8" target="_blank">https://codesandbox.io/s/vant-issue-moban-oqhg8</a>

### 描述问题
使用upload组件时，需要展示服务端返回的图片地址，使用的阿里云OSS，发现图片URL没有带文件后缀，使用正常的img标签能正常显示。upload组件貌似识别不了。
我从vant 2.0.9升级到2.1.0也是如此。
使用正常带后缀的图片URL能正常显示，也测试过不同的赋值方式，结果一致。
若demo的阿里云OSS图片链接无法访问，请使用其他无文件后缀图片URL替换。

**Comment by chenjiahan** [comment]
跟这个 issue 类似，可以一起讨论
https://github.com/youzan/vant/issues/4022
