### ISSUE TITLE
[Bug Report] ios系统微信浏览器中van-cell-group里van-field组件若设置type='password',其他输入框输入法会受影响

### ISSUE THREAD

**Issue by mingshuai123** [youzan/vant#4031]
### 设备 / 浏览器
ios微信内置浏览器

### Vant 版本
2.1.1

### Vue版本
2.6.10

### 重现链接
<a href="https://www.baidu.com/不方便提供" target="_blank">https://www.baidu.com/不方便提供</a>

### 描述问题
ios系统微信浏览器中van-cell-group里van-field组件若设置type='password',其他输入框输入法会受影响，其他的输入框会输入不了中文，其他输入框设置type='text'也无效，默认还是英文。甚至搜狗输入法无法修改输入格式

**Comment by chenjiahan** [comment]
麻烦用 codesandbox 提供下复现链接

**Comment by adonis-lsh** [comment]
解决了吗? 我也遇到了

**Comment by renhuan** [comment]
也遇到了，我这里会影响到上一个
