### ISSUE TITLE
van-upload怎样自定义上传成功后的样式

### ISSUE THREAD

**Issue by 845321942** [youzan/vant#4033]
van-uploader怎样自定义上传成功后的样式

**Comment by 845321942** [comment]
van-uploader怎样自定义上传成功后的样式

**Comment by 845321942** [comment]
van-uploader怎样自定义上传成功后的样式

**Comment by RabbDream** [comment]
uploader自定义上传样式之后,再加个v-model进行预览,会发现预览的图片是原来vant自带的样式,而不是你自定义的样式去显示整个图片,真的很傻

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
