### ISSUE TITLE
TreeSelect 组件滚动穿透,不能锁定主页背景

### ISSUE THREAD

**Issue by wananzys** [youzan/vant#4037]
**设备 / 浏览器**
安卓

**Vant 版本**
2.1.1

**Vue版本**
2.6.10

**描述问题**
主页有滚动条,TreeSelect 触摸滚动主页跟随滚动

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接

**Comment by wananzys** [comment]
> 请提供 codesandbox 复现链接
我自己用js控制html是否滚动,解决了
