### ISSUE TITLE
[Bug Report] van-field input事件对绑定值做处理后重新赋值，组件值渲染不正确

### ISSUE THREAD

**Issue by mengfairy** [youzan/vant#4039]
### 设备 / 浏览器
iphone 6s， Chrome 73 模拟

### Vant 版本
2.1.1

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-60ty6" target="_blank">https://codesandbox.io/s/vant-issue-moban-60ty6</a>

### 描述问题
input 事件中对输入值进行转数字处理后，重新赋值，data里面value已改变，但是组件未改变。
看了下代码，个人觉得可能是 input 创建方式的问题，不确定。

**Comment by chenjiahan** [comment]
具体是输入什么值有问题？

**Comment by mengfairy** [comment]
> 具体是输入什么值有问题？

![GIF](https://user-images.githubusercontent.com/25881883/62505829-c97f1280-b830-11e9-922b-974a7fe28506.gif)

**Comment by chenjiahan** [comment]
当金额为 0 的时候，你继续输入字母，得到的 innerValue 始终为 0，这意味着 innerValue 的值没有发生变更，因此不会触发 Vue 的视图更新

**Comment by mengfairy** [comment]
对.....脑残了
