### ISSUE TITLE
picker Components without methods getIndexes、setIndexes、getColumnIndex、setColumnIndex that in documents

### ISSUE THREAD

**Issue by xxn520** [youzan/vant#404]
In the documents, picker has methods below：
![image](https://user-images.githubusercontent.com/8163035/33802018-4fafd71e-dda8-11e7-82e2-3785dc4d5316.png)
But，don't have setIndexes、getIndexes methods
![image](https://user-images.githubusercontent.com/8163035/33802028-84cc7d44-dda8-11e7-93c3-f98c5e585544.png)

**Comment by xxn520** [comment]
upgrade from 0.11.5 to 0.11.8 fix it........

**Comment by xxn520** [comment]
建议写好 changelog，文档也最好有版本，不然真的容易出屎！

**Comment by chenjiahan** [comment]
@xxn520 感谢反馈，文档版本目前比较难支持，我们会尽量编写详尽的 changelog
