### ISSUE TITLE
Uploader 图片上传，希望添加图片压缩功能

### ISSUE THREAD

**Issue by zenonux** [youzan/vant#4042]
### 这个功能解决了什么问题
图片上传时选本地图片或者手机拍摄时，压缩图片后再上传，尤其是手机拍摄后压缩上传是比较常见的需求

### 描述您想要的解决方案
属性添加一个quality字段，该字段仅在accept字段为image类型下才生效，字段范围为0-100

### 建议的API是什么样的
quality:80

**Comment by xujunjie10** [comment]
+1

**Comment by chenjiahan** [comment]
暂无计划支持，建议自行处理
