### ISSUE TITLE
indexBar开启sticky自动吸顶的层级问题

### ISSUE THREAD

**Issue by wananzys** [youzan/vant#4047]
**设备 / 浏览器**
安卓/谷歌

**Vant 版本**
2.1.1

**Vue版本**
2.6.10

**描述问题**
设置sticky为false时页面效果
![image](https://user-images.githubusercontent.com/44047260/62462909-35269880-b7bb-11e9-8315-7fd247429c42.png)

设置sticky为true时页面效果, A的层级始终在下拉菜单栏的上面
![image](https://user-images.githubusercontent.com/44047260/62462961-58514800-b7bb-11e9-9afb-7b4588bffeeb.png)

**代码**
```
<van-dropdown-menu :overlay="false" active-color="rgb(147, 32, 63)" :z-index="10">
           <van-dropdown-item v-model="value1" title="全部"/>
           <van-dropdown-item v-model="value2" title="排序" :options="option2" />
           <van-dropdown-item v-model="value3" title="城市">
                    <van-index-bar :sticky-offset-top="150" :z-index="1" :sticky="true">
                             <div v-for="(indexItem,itemIndex) in indexList" :key="itemIndex">
                                     <van-index-anchor :index="indexItem">{{indexItem}}</van-index-anchor>
                                     <van-cell title="文本" />
                                     <van-cell title="文本" />
                                     <van-cell title="文本" />
                              </div>
                     </van-index-bar>
            </van-dropdown-item>
            <van-dropdown-item v-model="value4" title="标签" :options="option4" />
</van-dropdown-menu>
```

**Comment by chenjiahan** [comment]
使用 `sticky-offset-top` 属性即可，这种情况吸顶的位置应固定在 DropdownMenu 的下方

**Comment by wananzys** [comment]
> 使用 `sticky-offset-top` 属性即可，这种情况吸顶的位置应固定在 DropdownMenu 的下方

代码中使用了 `sticky-offset-top` 属性,无论值为多少,  B吸顶,A的固定定位总是覆盖了DropdownMenu,且不论 DropdownMenu 的层级有多大

**Comment by chenjiahan** [comment]
你可以去了解一下 z-index 层叠的原理，跟元素的 position 有关的

**Comment by wananzys** [comment]
![Uploading image.png…]()
![image](https://user-images.githubusercontent.com/44047260/62523201-d9651980-b865-11e9-91b2-db4e74f45c3d.png)
感觉是这个transform的原因,去掉就不显示A了,不知道咋解决,我还是设置sticky="false"吧
