### ISSUE TITLE
输入框组件在禁用状态下依然可以触发点击事件

### ISSUE THREAD

**Issue by LonelyPH** [youzan/vant#4050]
输入框为disabled状态，但是点击旁边的label或者箭头，依然会触发点击事件弹窗picker，这个怎么解决呢？是组件的Bug还是什么？

**Comment by chenjiahan** [comment]
输入框 disabled 只是表示禁止输入，并不会影响 click 事件喔

你可以在 click 事件的回调函数里判断 disabled 状态
