### ISSUE TITLE
[Bug Report] actionSheet中使用picker选择器,无法上下滑动

### ISSUE THREAD

**Issue by DongJigong** [youzan/vant#4052]
### 设备 / 浏览器
iphone8plus

### Vant 版本
2.1.1

### Vue版本
2.6.10

### 重现链接
<a href="http://www.baidu.com" target="_blank">http://www.baidu.com</a>

### 描述问题
actionSheet中使用picker选择器,无法上下滑动

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接

**Comment by DongJigong** [comment]
没有公网上的链接.请问能否验证下,我们这边iphoneX是没问题的,iphone8P就有问题

**Comment by chenjiahan** [comment]
请问 iOS 系统版本是多少

能否请打开`vue.runtime.esm.js`，对下面这段代码进行调试

![image](https://user-images.githubusercontent.com/7237365/61864147-7b4e4300-af03-11e9-88a3-7cad5a41c0b9.png)

若能执行`original.apply(this, arguments)`，表示冒泡事情正常触发，若未执行，表示冒泡事件未能触发

**Comment by DongJigong** [comment]
ios 版本11.2.1,现在是第一次能滑动,之后就不能滑动了.感谢回复

**Comment by xiaochegnzi0** [comment]
大佬，我也发现了，我使用actionSheet然后中间加了个v-distpicker，导致我的省市区没法滑动

**Comment by DongJigong** [comment]
我这边测试人员描述第一次能滑动的场景是,先往下滑动接着再往上拉下就可以第一次滑动,希望能对解决问题有用

**Comment by chenjiahan** [comment]
能否按照我上面的代码调试下，或者打开 https://youzan.github.io/vant/mobile.html#/zh-CN/picker 看下是否能复现问题

**Comment by DongJigong** [comment]
@chenjiahan 感谢,现在在微信上打开链接是可以滑动了.难道是我们写法有误么?

**Comment by xiaochegnzi0** [comment]
> @chenjiahan感谢，现在在微信上打开链接是可以滑动了。难道是我们写法有误么？

啥意思，你的解决了？怎么解决的？我这边使用弹窗加载省市区的滑不动啊

**Comment by DongJigong** [comment]
@xiaochegnzi0 我这边使用[]( https://youzan.github.io/vant/mobile.html#/zh-CN/picker)这个链接是可以的

**Comment by xiaochegnzi0** [comment]
> @ xiaochegnzi0我这边使用[https://youzan.github.io/vant/mobile.html#/zh-CN/picker这个链接的英文可以的](https://youzan.github.io/vant/mobile.html#/zh-CN/picker%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E6%98%AF%E5%8F%AF%E4%BB%A5%E7%9A%84)

那你项目里也好了？

**Comment by xiaochegnzi0** [comment]
> 能否按照我上面的代码调试下，打开或者https://youzan.github.io/vant/mobile.html#/zh-CN/picker看下是否能复现问题

大佬，我插个楼，大佬，我想说，那个picker组件我不知道怎么让三个数据关联起来，就是因为使用V-distpicker无法滑动，然后我只能使用picker制作省市区三级联动

**Comment by chenjiahan** [comment]
有可能是写法问题，可以自行排查下

**Comment by chenjiahan** [comment]
省市区联动直接使用 Area 组件即可

**Comment by xiaochegnzi0** [comment]
> 省市区联动直接使用 Area 组件即可

我最开始就是用的那个，但是我们数据库里没有存code码，无法使用，想哭，我们这边项目就存了省市区的汉字

**Comment by xiaochegnzi0** [comment]
大佬，我在手机上录了van-popup或者 van-action-sheet 使用v-distpicker组件，无法滑动




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 上午10:20
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "这世道·贼无情 ゝ"<1501424594@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] actionSheet中使用picker选择器,无法上下滑动 (#4052)




有可能是写法问题，可以自行排查下

**Comment by DongJigong** [comment]
> > 省市区联动直接使用 Area 组件即可
> 
> 我最开始就是用的那个，但是我们数据库里没有存code码，无法使用，想哭，我们这边项目就存了省市区的汉字

我这边也是用action-sheet+picker出现的问题，现在正在找是不是写法有问题。用 @chenjiahan 刚发的链接在问题手机上测试时没发现问题了

**Comment by xiaochegnzi0** [comment]
> > > 省市区联动直接使用 Area 组件即可
> > 
> > 
> > 我最开始就是用的那个，但是我们数据库里没有存code码，无法使用，想哭，我们这边项目就存了省市区的汉字
> 
> 我这边也是用action-sheet+picker出现的问题，现在正在找是不是写法有问题。用 @chenjiahan 刚发的链接在问题手机上测试时没发现问题了

我现在是两难了，原本的省市区组件无法使用，使用action-sheet+v-distpicker不能滑动，使用action-sheet+picker又不会写picker三个数据联动起来

**Comment by DongJigong** [comment]
@chenjiahan 我们现在用完整的demo还是不可以，比对了下我们这边没有vant-mobile js请问 这个怎么加入进来
![image](https://user-images.githubusercontent.com/8855265/62672826-b9049e80-b9ce-11e9-87d1-25b7ea7eb937.png)

**Comment by chenjiahan** [comment]
跟小程序有啥关系喔，链接和 demo 是一致的

**Comment by xiaochegnzi0** [comment]
> 跟小程序有啥关系喔，链接和 demo 是一致的

大佬，vant省市区组件能加个参数，就是不填code码也可以使用的吗 @chenjiahan

**Comment by defypro** [comment]
> 跟小程序有啥关系喔，链接和 demo 是一致的

您好，我发现了一个问题，就是我通过手机打开https://youzan.github.io/vant/mobile.html#/zh-CN/然后进入到https://youzan.github.io/vant/mobile.html#/zh-CN/datetime-picker就会出现组件无法滚动的情况，如果直接进入该页面则可以进行滚动。
Iphone8P 11.2.5   微信7.0.3

**Comment by chenjiahan** [comment]
> vant省市区组件能加个参数，就是不填code码也可以使用的吗
这个暂时没计划支持喔

**Comment by defypro** [comment]
@chenjiahan 

有问题的手机升级过微信版本后就没有复现过了，后续有类似再来反馈

**Comment by chenjiahan** [comment]
好的👌

**Comment by xiaochegnzi0** [comment]
大佬，我发现，vant中使用别的组件会滑不顺畅，vant中加入ydui这个的省市区组件，选择地址时不太顺畅，qq浏览器中，和微信浏览器中都不行

**Comment by chenjiahan** [comment]
vant 不会影响其他组件，建议你看下是不是其他问题

**Comment by xiaochegnzi0** [comment]
> vant 不会影响其他组件，建议你看下是不是其他问题

大佬，我之前用过其他组件，是不会出现这样的问题的，我怀疑是有点事件冒泡了，因为滑动的时候，遮罩层下面的在随着手指滑动，大佬救救我

**Comment by chenjiahan** [comment]
麻烦提供下 codesandbox 复现链接

**Comment by xiaochegnzi0** [comment]
> vant 不会影响其他组件，建议你看下是不是其他问题

不然大佬你教我使用picker实现三级联动，== 我真的不会那个，我现在被省市区难住了，换了两个插件都不行，

**Comment by xiaochegnzi0** [comment]
> 麻烦提供下 codesandbox 复现链接

大佬，我可以私聊你吗，因为项目需要账号登录

**Comment by xiaochegnzi0** [comment]
@chenjiahan 大佬，我录了个视频发送到你邮箱了，

**Comment by chenjiahan** [comment]
@xiaochegnzi0 抱歉没有时间教你喔，自己加油吧，多看看文档

**Comment by xiaochegnzi0** [comment]
> @xiaochegnzi0 抱歉没有时间教你喔，自己加油吧，多看看文档

那大佬，我这个冒泡的问题怎么办呢？

**Comment by chenjiahan** [comment]
你先拿出复现链接来，把问题描述清楚，不然没法帮你

**Comment by xiaochegnzi0** [comment]
> 你先拿出复现链接来，把问题描述清楚，不然没法帮你

https://mall.tnomg.com/wap  移动端，直接输入手机号然后验证码，进入我的，地址选择，省市区里，微信和qq浏览器都这样，多滑几次和选择几次就出现了
