### ISSUE TITLE
[Bug Report] 2.0版本 van-icon 图标消失，线上手机端项目图标消失，电脑端有效

### ISSUE THREAD

**Issue by 841440416** [youzan/vant#4053]
![IMG_1437](https://user-images.githubusercontent.com/26712681/62594590-b68e4000-b90d-11e9-8dc4-4a5629d63106.PNG)

初步判断是    font: 14px/1 "vant-icon"; 这行样式不起作用了，van-icon自定义样式无效，还请官方大大及时解决，线上项目急急急！

**Comment by 841440416** [comment]
补充：
测试发现，我将vant版本从2.09降到1.6.23后，van-icon图标恢复显示了，所以基本能确定是新版本组件资源变更导致不能显示

**Comment by 841440416** [comment]
补充：
vant 2.0.9下，暂时发现iphone7在手机端（钉钉环境中）van-icon不能显示，iphone正常

**Comment by 841440416** [comment]
设备 / 浏览器
iphone7

Vant 版本
2.1.1

Vue版本
2.5.2

描述问题
van-icon 图标不显示

**Comment by chenjiahan** [comment]
麻烦确认下这几个问题：
- 是 2.0 以上都会出现这个问题吗
- iOS 系统版本是多少
- 使用其他 iconfont 是否能展示，比如 fontawesome

**Comment by 841440416** [comment]
> 麻烦确认下这几个问题：
> 
> * 是 2.0 以上都会出现这个问题吗
> * iOS 系统版本是多少
> * 使用其他 iconfont 是否能展示，比如 fontawesome

稍等，今天晚上我反馈给您

**Comment by 841440416** [comment]
iOS系统版本为 12.3.1
使用其它confont未发现问题
经测试：目前使用的2.0版本 van-icon 又恢复正常，因为我做的是钉钉原生内嵌的H5微应用，所以很可能是vebview加载出了问题

**Comment by chenjiahan** [comment]
和这个问题类似 https://github.com/youzan/vant/issues/3925 暂时没有解决方法

**Comment by baihuijun** [comment]
> iOS系统版本为 12.3.1 使用其它confont未发现问题 经测试：目前使用的2.0版本 van-icon 又恢复正常，因为我做的是钉钉原生内嵌的H5微应用，所以很可能是vebview加载出了问题

我也是钉钉内嵌应用 iphone能正常显示 安卓不行
