### ISSUE TITLE
请问使用Picker如何实现三级联动？

### ISSUE THREAD

**Issue by xiaochegnzi0** [youzan/vant#4054]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
跟文档里二级联动的做法一致，在 onChange 的第三个参数可以拿到变更的列的索引，然后去设置后续的数据即可
