### ISSUE TITLE
图片在苹果7以上机型放大图片很模糊（图片本身很大，而且图片如果直接在苹果机型上以链接形式打开，放大不模糊），啥原因。

### ISSUE THREAD

**Issue by freecodemakerxu** [youzan/vant#4057]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
