### ISSUE TITLE
[Bug Report] 命令行报错

### ISSUE THREAD

**Issue by wangjiahan** [youzan/vant#4059]
### 设备 / 浏览器
mac/google

### Vant 版本
2.1.1

### Vue版本
2.5.21

### 重现链接
<a href="https://www.baidu.com" target="_blank">https://www.baidu.com</a>

### 描述问题
运行时在终端报错，但不影响使用。报错信息：
Subsequent property declarations must have the same type.  Property '$notify' must be of type 'ElNotification', but here has type 'Notify'.
   declare module 'vue/types/vue' {
      interface Vue {
      $notify: Notify
    }
 }

抱歉暂时没有公网链接

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3324
