### ISSUE TITLE
Dialog 异步关闭时,在手机上 loading 显示很小

### ISSUE THREAD

**Issue by MengQingJunzz** [youzan/vant#4063]
![image](https://user-images.githubusercontent.com/30398163/62617155-d6d8f180-b943-11e9-8c67-a895dc1443ff.png)

**Comment by MengQingJunzz** [comment]
![61947f2f9d0a0098141713a832b7cc3](https://user-images.githubusercontent.com/30398163/62617246-0a1b8080-b944-11e9-824f-75b9aee1919e.jpg)

**Comment by MengQingJunzz** [comment]
![61947f2f9d0a0098141713a832b7cc3](https://user-images.githubusercontent.com/30398163/62617503-9168f400-b944-11e9-9993-f778c2ac163f.jpg)

**Comment by chenjiahan** [comment]
建议是否有覆盖 loading 组件样式的代码，产生了干扰
