### ISSUE TITLE
[Feature Request] 可以整合下拉刷新上拉加载吗

### ISSUE THREAD

**Issue by yangy9593** [youzan/vant#4065]
### 这个功能解决了什么问题
现在分为PullRefresh 下拉刷新 和 List 列表，把他们整合到（新增） Refresh 组件中

### 描述您想要的解决方案
新增一个刷新组件 Refresh 

### 建议的API是什么样的
pull-refresh 下拉刷新事件
pull-Refresh-text 下拉刷新描述文本
up-refresh 上拉加载事件
up-refresh-text 上拉加载描述文本

**Comment by chenjiahan** [comment]
暂无计划支持喔，组合使用即可

**Comment by zpedku** [comment]
组合使用,在有TabBar组件的情况如何布局?列表内容的底部和tabbar重合,会导致列表内容显示不全,请问要如何解决

**Comment by yangy9593** [comment]
最外层 margin-bottom 不行吗？
