### ISSUE TITLE
[Feature Request] AddressEdit 组件支持自定义邮编校验规则

### ISSUE THREAD

**Issue by die214144031** [youzan/vant#4066]
### 设备 / 浏览器
ios 安卓

### Vant 版本
2.1.1

### Vue版本
2.6.10

### 描述问题
我们有个项目是国外的  用到了这个组件 他们那里的邮编想要填入四位  但是我查看你们的源代码 写死了验证六位 还一定要验证  非常不灵活  希望赶紧支持下 谢谢

**Comment by chenjiahan** [comment]
下个版本会支持自定义校验规则

**Comment by chenjiahan** [comment]
已在 2.1.2 版本支持
