### ISSUE TITLE
NoticeBar组件数据是异步的时候不会滚动，本地死数据没有问题

### ISSUE THREAD

**Issue by yzbgyq** [youzan/vant#4081]
![image](https://user-images.githubusercontent.com/32931212/62773255-4d0c5e00-bad4-11e9-8983-88eb572f4afd.png)

**Comment by xg4** [comment]
异步数据可以通过 `text` 属性，`slot` 还不支持，只会在初始化的时候计算宽度，之后的数据变化并没有触发宽度的重新计算

```html
<van-notice-bar :text="msg" />
```

**Comment by kingport** [comment]
> 异步数据可以通过 `text` 属性，`slot` 还不支持，只会在初始化的时候计算宽度，之后的数据变化并没有触发宽度的重新计算
> 
> ```
> <van-notice-bar :text="msg" />
> ```

可以定义一个scrollable状态 每当异步请求时设置为false 成功后设置为true 就会每次计算宽度，利用vue的生命周期，虽然实现不是很好，但能解决问题

**Comment by kingport** [comment]
![image](https://user-images.githubusercontent.com/26566472/78008498-505d9e00-7372-11ea-8a05-3ccde9bacc2c.png)
