### ISSUE TITLE
van-tab click实践不能传值

### ISSUE THREAD

**Issue by liuxianghua1** [youzan/vant#4086]
<van-tab :title="item.title" v-for="item in cates" :key="item.id" @click="getPhotoList(item.id)">
无法为getPhotoList传入我的id
换个标签则可以实现
<a :title="item.title" v-for="item in cates" :key="item.id" @click="getPhotoList(item.id)">{{item.title}}</a>
很奇怪 我一开始以为我的代码写错了 后面才发现是这个问题

**Comment by chenjiahan** [comment]
van-tab 并没有提供 click 事件呢

**Comment by liuxianghua1** [comment]
好吧 心碎了 我折腾了一晚上 谢谢 可以给个加群链接吗？我加了有赞小秘书没有理我

**Comment by chenjiahan** [comment]
群超过 100 人了，放不了二维码，你可以留个微信号，我拉你进群

**Comment by liuxianghua1** [comment]
L1336159427 非常感谢大大

**Comment by chenjiahan** [comment]
加咯，评论帮你删了
