### ISSUE TITLE
[Bug Report] 异步获取tabs的数据时，选中的tab不能定位到中间

### ISSUE THREAD

**Issue by Leruiz** [youzan/vant#4090]
### 设备 / 浏览器
安卓/iphone/谷歌浏览器移动端调试模式

### Vant 版本
2.1.2

### Vue版本
2.5.21

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-zyv42" target="_blank">https://codesandbox.io/embed/vant-issue-moban-zyv42</a>

### 描述问题
当tabs中的数据是异步获取的，而tab列表的宽度已经超出了屏幕的宽度，初始加载页面的时候，选中的tab没有自动滚动到屏幕中间

理想情况是

![2](https://user-images.githubusercontent.com/20510533/62831897-a604ff00-bc58-11e9-81e1-ddf245100ad8.png)

而实际情况是
![1](https://user-images.githubusercontent.com/20510533/62831899-b0bf9400-bc58-11e9-850d-03d81e71add5.png)

**Comment by chenjiahan** [comment]
下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 2.1.3 版本修复
