### ISSUE TITLE
[Bug Report] Stepper async-change打开时@change trigger了两次。

### ISSUE THREAD

**Issue by PhantomRay** [youzan/vant#4092]
### 设备 / 浏览器
Chrome@latest

### Vant 版本
2.1.1

### Vue版本
2.6.10

### 描述问题
代码：
`<Stepper slot="num" :value="item.qty" async-change @change="onChange(item,$event)" min="0" max="99" />`

```
 onChange(item, value) {
     console.log('test');
}
```

当async-change去掉时只会执行一次

**Comment by chenjiahan** [comment]
能否一共一下 codesandbox 复现链接

**Comment by PhantomRay** [comment]
在codesandbox里复现不了，应该是自己的代码有问题。

**Comment by PhantomRay** [comment]
找到原因了，是因为计数器值修改了又出发了一次onChange。在实际项目中，我在前面加了一个判断，如果是第二次触发，则忽略onChange。

https://codesandbox.io/s/vant-issue-moban-w4zyk

**Comment by chenjiahan** [comment]
从逻辑上来说，当手动改变输入框值的时候也应该触发 change 事件，这是符合 change 事件的描述的

**Comment by PhantomRay** [comment]
我代码里@change里会发送请求到服务器，返回后model值变了，导致输入框变了，@change又被执行一次。因为第二次发送到服务器到请求值没变，所以model值为第一次改变时的值。

这样的逻辑是否合理？

**Comment by chenjiahan** [comment]
第二次请求不需要发，这个可能得在你自己的逻辑里判断
