### ISSUE TITLE
[Feature Request] tree-select右侧content能不能开个slot

### ISSUE THREAD

**Issue by likess921** [youzan/vant#4094]
### 这个功能解决了什么问题
tree-select右侧content内容没办法定制，某些情况下需要显示列表等样式效果

### 描述您想要的解决方案
tree-select增加default Slots，自定义van-tree-select__content 的内容

### 建议的API是什么样的
<van-tree-select
	:items="items"
	:main-active-index="mainActiveIndex"
	:active-id="activeId"
	@click-nav="onClickNav"
	@click-item="onClickItem"
>
	<div>hello world</div>
</van-tree-select>

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by likess921** [comment]
烦请增加一个props 自定义右侧conetent的height

**Comment by xuchengxue** [comment]
为什么我的 @click-nav="onClickNav" 不能点击

**Comment by idlesysman** [comment]
啥时候出啊，马上2021年了

**Comment by idlesysman** [comment]
现在的content插槽没法获取上下文啊

**Comment by sifongithub** [comment]
用ts怎们写@click-nav这个事件啊
