### ISSUE TITLE
ActionSheet 在vue项目中无法使用

### ISSUE THREAD

**Issue by 18sby** [youzan/vant#4095]
ActionSheet 在vue项目中无法使用 "vant": "^1.6.24", 别的可以用，目前发现这个不行，报错找不到依赖，  These dependencies were not found:

* vant/es/action-sheet in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/playDetail/index.vue?vue&type=script&lang=js&
* vant/es/action-sheet/style in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/playDetail/index.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save vant/es/action-sheet vant/es/action-sheet/style
执行上面那条命令也安装不上

**Comment by 18sby** [comment]
![image](https://user-images.githubusercontent.com/47735184/62846995-5e3cb100-bd06-11e9-86f8-88ad26abeb5e.png)
插件自动追踪的是action-sheet，但是nodemodules 里面文件名是actionsheet，所以没有找到依赖，希望尽快修复下哈，谢谢

**Comment by 18sby** [comment]
原来是版本问题，希望加一个版本提醒

**Comment by chenjiahan** [comment]
嗯，这个是版本问题，后续会在文档上标注
