### ISSUE TITLE
[Bug Report] DropdownMenu 下拉菜单在导航栏组件中显示错误

### ISSUE THREAD

**Issue by dongtsai** [youzan/vant#4096]
### 设备 / 浏览器
浏览器与iPhone均有问题

### Vant 版本
2.0.9

### Vue版本
2.6.6

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-jm5d9" target="_blank">https://codesandbox.io/s/vant-issue-moban-jm5d9</a>

### 描述问题
DropdownMenu 下拉菜单在导航栏组件中显示错位：
1、箭头与文字水平没有对齐
2、下拉页面每行没有对齐

**Comment by chenjiahan** [comment]
下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 2.1.3 版本修复
