### ISSUE TITLE
[Bug Report] 配置 pxtorem px 转rem后 input光标变粗

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#4097]
### 设备 / 浏览器
ios12.4  移动端safari

### Vant 版本
2.1.1

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/m5v3f" target="_blank">https://codesandbox.io/s/m5v3f</a>

### 描述问题
配置 pxtorem px转rem后 input光标变粗。去掉postcss-pxtorem 则显示正常。

**Comment by anihCevol** [comment]
这可能不是个bug，但是想问一下有没有处理方法~~

**Comment by chenjiahan** [comment]
没遇到过这种情况，有截图吗

**Comment by anihCevol** [comment]
![QQ图片20190812193455](https://user-images.githubusercontent.com/42430384/62862931-f1dba500-bd39-11e9-8796-c999a2122dff.png)
![QQ图片20190812193615](https://user-images.githubusercontent.com/42430384/62862937-f6a05900-bd39-11e9-8a33-7ba5e0afc13c.png)
![QQ截图20190812194243](https://user-images.githubusercontent.com/42430384/62862944-f99b4980-bd39-11e9-84e3-874b54579abf.png)
【移除px转rem的插件配置前后光标粗细对比】

**Comment by anihCevol** [comment]
能占个楼，提个新问题嘛。
ios12.4 手机chrome浏览，vant2.1.2  轮播组件 无 轮播过度动画。
![IMG_0097](https://user-images.githubusercontent.com/42430384/62863149-8fcf6f80-bd3a-11e9-9d4f-7bbe13adf4d9.PNG)

**Comment by chenjiahan** [comment]
光标这个应该不是组件的问题

轮播动画的问题我试了下没复现，不过我是 12.3 版本

**Comment by anihCevol** [comment]
好的。
您好，再问最后一个问题~
![FBFAE20DDFD3C5623B23FF39D54B6074](https://user-images.githubusercontent.com/42430384/62986369-d5408980-be6d-11e9-92e4-5408db813cd1.jpg)
现有的组件我可以实现这个popover效果嘛。如有可能，popover组件可以加入到Vant组件库中嘛。

**Comment by chenjiahan** [comment]
Popover 目前没提供喔，未来我们应该会支持

现有组件的话可以基于 Popup 实现

**Comment by anihCevol** [comment]
好的

**Comment by luhuaxin** [comment]
> 好的

你好，请问你解决了吗？我也遇到了，光标变粗的问题

**Comment by anihCevol** [comment]
还没处理。。
