### ISSUE TITLE
[Bug Report] 上传图片无法选中图片

### ISSUE THREAD

**Issue by Simlan** [youzan/vant#4103]
### 设备 / 浏览器
MI 9SE (android 9)

### Vant 版本
2.1.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/mobile.html#/zh-CN/uploader</a>

### 描述问题
使用https://youzan.github.io/vant/mobile.html#/zh-CN/uploader 在安卓测试上传，可以正常唤起拍照和选择相册，但是选择图片之后没有任何响应

**Comment by chenjiahan** [comment]
没有响应是指没有触发 after-read 吗？

**Comment by Simlan** [comment]
选择了照片之后会返回到上传页面，实际并未上传

**Comment by chenjiahan** [comment]
uploader 组件不会将文件上传到服务器，这一步需要你自己完成的

**Comment by Simlan** [comment]
是的，上传到服务器需要自己完成，选中照片后，返回上传页面会显示缩略图。

**Comment by Simlan** [comment]
是的，上传到服务器需要自己完成。

弹出相机和选择相册之后，从相册选择照片，返回到上传页面，不支持安卓微信浏览器吗？

**Comment by chenjiahan** [comment]
支持安卓微信浏览器的，选完照片回到上传页面是正常的流程，回到页面后会触发 after-read 回调，你可以从回调中取到 File 对象

**Comment by Simlan** [comment]
对呀，就是取不到，目前在安卓微信浏览器里部分机型有这个问题,我测试的MI9SE就有这个问题

**Comment by chenjiahan** [comment]
可以描述的清楚一点么，取不到是指 after-read 没有触发，还是触发了但是没有回调函数

**Comment by greedymonkey** [comment]
我也有这个问题，我的机型是MI note3，而且是没有触发after-read

**Comment by Simlan** [comment]
无法afterRead, 然后测试了一下weui, vant, iview这类前端框架，貌似都是一样的，无法选择图片上传，是因为安卓微信浏览器不支持input type=file的原因吗

**Comment by chenjiahan** [comment]
按理说 input type=file 肯定是支持的，要么是这款机型比较坑，要么是其他问题引起的

**Comment by Simlan** [comment]
IOS是没有问题的，目前测试到的小米不分机型，华为nova系列不分机型都有这个问题，实在无解呀

**Comment by chenjiahan** [comment]
不可能喔，我这边的小米和华为都是正常的

**Comment by Simlan** [comment]
我们测试到的MI9SE NOVA3都不同程度有这个问题，你是在微信里面测试的吗

**Comment by chenjiahan** [comment]
是的

**Comment by Simlan** [comment]
有其他的解决办法吗

**Comment by chenjiahan** [comment]
你可以用原生的 input type=file 试下看看

**Comment by Looper-01** [comment]
华为Honor V8，上传图片没反应，和楼主描述问题一致。

**Comment by pineappleok** [comment]
华为的荣耀20在app里也完全没法发唤起选图、选文件；但是在微信里打开组件demo倒是可以，微信里的组件demo也有个bug，设置了默认拍摄没起作用

**Comment by amorphis666** [comment]
更新到2.1.2版本后，安卓手机遇到了同样的问题，更新前忘记是什么版本没有这个问题

**Comment by chenjiahan** [comment]
@amorphis666 能否帮忙调试下，看看是否有报错，或者代码执行到哪一步停止了

**Comment by Simlan** [comment]
无解啊  微信里面看来只能使用JSSDK的方式了

**Comment by wangjun521** [comment]
你是用的微信分身吧?

**Comment by Simlan** [comment]
一语惊醒梦中人，回头测试一下， @Looper-01  @pineappleok 你们是这样吗

**Comment by wangjun521** [comment]
微信分身不支持的哦 原生type=file也不支持的哦 跟框架无关

**Comment by greedymonkey** [comment]
他说的对，我试了，是分身的原因，我直接在微信测试是好用的，不论是框架还是原生的都可以

**Comment by chenjiahan** [comment]
了解了 👌 那这个 issue 可以关掉了

**Comment by Looper-01** [comment]
这就关掉了？我的情况不是微信分身，楼主是分身吗？有一个人是分身，你们就感觉像是抓住了救命的稻草，直接关掉了？

**Comment by Looper-01** [comment]
@Simlan 我们的情况不是微信分身，华为Honor V8，刚刚把版本降到了v2.0.9就好了。

**Comment by Rickykurt** [comment]
参见：https://www.caniuse.com/#search=multiple
![image](https://user-images.githubusercontent.com/1176984/64139133-7352be80-ce32-11e9-957f-9e9413543a78.png)

**Comment by webylb** [comment]
一语惊醒梦中人 我刚被测试追着锤 现在我追着他锤
