### ISSUE TITLE
[Bug Report] DatetimePicker 兼容

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#4104]
### 设备 / 浏览器
ios

### Vant 版本
2.1.2

### Vue版本
2.5.20

### 重现链接
<a href="http://acone.ewangke.com/activePage?token=57f49935-674f-4491-903b-7a9f47a2a7e8&openid=on3s6woonFidmi6ibm90H0Xk3t_Q" target="_blank">http://acone.ewangke.com/activePage?token=57f49935-674f-4491-903b-7a9f47a2a7e8&openid=on3s6woonFidmi6ibm90H0Xk3t_Q</a>

### 描述问题
ios端时间选择组件空白，pc安卓正常
![image](https://user-images.githubusercontent.com/42930030/62858985-7de7cf80-bd2e-11e9-8cd4-564381e339e4.png)
ios如下
![image](https://user-images.githubusercontent.com/42930030/62859136-de770c80-bd2e-11e9-871c-9c8e84e31b6d.png)
， 重现连接在微信端打开
![image](https://user-images.githubusercontent.com/42930030/62859276-3d3c8600-bd2f-11e9-9df5-4ccf4e77bf2d.png)
手动按需引入

**Comment by chenjiahan** [comment]
我用 iphone XR 打开是正常的，建议你看下是否有代码报错了，可以通过这个库 https://github.com/Tencent/vConsole 查看

**Comment by cangyu1993** [comment]
真的是无解了，我装插件自动按需引入，pc和安卓都变空白了
![image](https://user-images.githubusercontent.com/42930030/62860712-a6be9380-bd33-11e9-8f96-88d76829185a.png)
![image](https://user-images.githubusercontent.com/42930030/62860718-ad4d0b00-bd33-11e9-8a3b-93eb83a2e322.png)
![image](https://user-images.githubusercontent.com/42930030/62860737-bdfd8100-bd33-11e9-9a8a-379cdf6013f7.png)

**Comment by chenjiahan** [comment]
是不是重复引入了 base.css，可以检查下 picker 的样式

**Comment by cangyu1993** [comment]
我发现在空白的时候van-picker-column的宽度是0，我现在改回了手动按需引入，先保证安卓能正常了，iso真是。。。。。

**Comment by pppshiwen** [comment]
我也遇到了同样的兼容问题，也是用于微信网页开发，出现问题的手机型号是 苹果xs 
iPhone XS 截图
![image](https://user-images.githubusercontent.com/40817872/62915601-a4a61480-bdc7-11e9-9895-00dceef92a45.png)

**Comment by cangyu1993** [comment]
我是时间组件不显示的问题，我用了mint-ui，单个引入时间选择

**Comment by pppshiwen** [comment]
我也是不显示，都是用DatetimePicke
安卓截图
![image](https://user-images.githubusercontent.com/40817872/62917149-b8547980-bdcd-11e9-9074-bdd295b7a7af.png)

**Comment by chenjiahan** [comment]
不显示的话可以看下代码是否有报错信息

**Comment by chenjiahan** [comment]
在 2.1.4 版本里修复了 Picker 样式被 base.css 覆盖导致无法展示的问题

**Comment by cangyu1993** [comment]
![IMG_0019](https://user-images.githubusercontent.com/42930030/63569945-f9a70f00-c5ad-11e9-96e0-82ed62da1532.PNG)
优秀，刚好发现上一个UI库时间选择的bug正愁没法解决呢，雪中送炭啊，谢谢开发者

**Comment by CaiZX94** [comment]
vant版本2.1.3vue版本

**Comment by CaiZX94** [comment]
vant版本2.1.3  vue版本2.5.2   在iOS  9.2.x，10.3.x版本下，datetimePicker和picker出现无法滚动的情况，请问是否和vant版本有关系

**Comment by chenjiahan** [comment]
@CaiZX94 锁定 Vue 版本到 2.5.22 即可

**Comment by cangyu1993** [comment]
最新版本的vant不是已经修复了ios的兼容问题，我已经换回了vant版本的时间选择，感觉用着还很好

**Comment by wangyumin184** [comment]
同问最新版是否有解决ios 9无法滚动问题，vue 降级2.5.22方案，由于项目使用了很多2.6特性，无法采用
