### ISSUE TITLE
[Feature Request] Collapse: 参数的类型问题

### ISSUE THREAD

**Issue by huangysss** [youzan/vant#4108]
### 这个功能解决了什么问题
Collapse 参数类型不明确

### 描述您想要的解决方案
1. Collapse 手风琴模式 (accordion)，如果没有展开，Event change 参数的值是 ```''```，在这种情况下，参数的值为 ```null``` 是否更好。

2. activeNames 实际上的类型，目前应该为``` (string | number)[] | (string | number)```; 因为这里的类型只限制了单个的 Item。
（```accordion```模式下，```activeNames``` 还可以为 ```null``` ）

补充例子：https://codesandbox.io/s/collapsetype-ty9en

### 建议的API是什么样的
1. 如果没有展开，Event change 参数为 ```null``` ;
2. (1)限定全部name为number/string；(2)修改文档；

ps: 
对比了ElementUI的Collapse，他们……
的activeNames限定为……
string。
:dog:

**Comment by chenjiahan** [comment]
> 如果没有展开，Event change 参数为 null

这个是合理的，欢迎 PR

> 限定全部name为number/string

这块不是很清楚，当前 name 的类型就是 `number | string` 嘛

**Comment by huangysss** [comment]
是这样的：
当前v-model和Event change params (#4106) 的类型为```string[] | number[] | string | number```;
但考虑一下这个情况：```[1, 2, '3']```;

**Comment by huangysss** [comment]
OK, (2)我晚点提，(1)我看看能不能修改。

**Comment by chenjiahan** [comment]
文档 PR 已合

另外未展开的情况下，目Event change 参数为空字符串，这个应该没有问题，Element 也是同样的处理
