### ISSUE TITLE
[Bug Report] van-sku 中 '已选' 文字没有国际化

### ISSUE THREAD

**Issue by liseipi** [youzan/vant#4109]
### 设备 / 浏览器
手机

### Vant 版本
2.1.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/sku" target="_blank">https://youzan.github.io/vant/#/zh-CN/sku</a>

### 描述问题
van-sku 中 '已选' 文字没有国际化，且没有Slots自定义

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3760

**Comment by liseipi** [comment]
@chenjiahan 能否单独加个自定义file ，处理部分组件的国际化文件，按需引入

**Comment by chenjiahan** [comment]
去上面的 issue 里提下哈，我们正在考虑方案
