### ISSUE TITLE
list组件一直加载数据

### ISSUE THREAD

**Issue by 2587593709** [youzan/vant#4110]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by 2587593709** [comment]
list组件一直加载数据

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by zhao-ping** [comment]
我这儿也是，根本停不下来，还有其他的组件也有问题，那个sticky也是，吸顶的那个属性根本不管用
