### ISSUE TITLE
[Bug Report] 二次开发的问题

### ISSUE THREAD

**Issue by fabin5** [youzan/vant#4111]
### 设备 / 浏览器
ThinkPad/chrome

### Vant 版本
2.1.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/theme" target="_blank">https://youzan.github.io/vant/#/zh-CN/theme</a>

### 描述问题
我想对vant进行二次开发，当修改组件，准备重新上传时，发现打包有误，比如 es/action-sheet/style/index.js 文件中的内容是这样的：
import '..\..\style\base.css';
import '..\index.css';

打包出来是这样错误的，请问怎么解决呢？谢谢！

**Comment by chenjiahan** [comment]
应该是 window 里的路径分隔符问题，可以打开 https://github.com/youzan/vant/blob/dev/build/build-style-entry.js 调试下
