### ISSUE TITLE
[Bug Report] NumberKeyboard IOS系统快速输入卡慢

### ISSUE THREAD

**Issue by lxc512157407** [youzan/vant#4112]
### 设备 / 浏览器
IOs

### Vant 版本
2.1.2

### Vue版本
2.6.10

### 重现链接
<a href="http://10.1.6.57" target="_blank">http://10.1.6.57</a>

### 描述问题
建议：把click触发press事件改为由touchstart触发，从而避免IOS的click300毫米延迟导致的卡顿。代码文件是：node_modules/vant/es/number-keyboard/Key.js  41、62行
methods: {
    onFocus: function onFocus() {
      this.$emit('press', this.text, this.type);
      this.active = true;
    },
    onBlur: function onBlur() {
      this.active = false;
    },
    onClick: function onClick() {
      this.$emit('press', this.text, this.type);
    }
  },
  render: function render() {
    var h = arguments[0];
    var onBlur = this.onBlur;
    return h("i", {
      "attrs": {
        "role": "button",
        "tabindex": "0"
      },
      "class": [BORDER, this.className],
      "on": {
        //把onclick触发onpress事件改为touchstar事件触发，避免ios的300毫米延迟的卡顿现象，
        "touchstart": this.onFocus,

**Comment by chenjiahan** [comment]
目前点击延迟的情况很少了，除非是 UIWebView

**Comment by lxc512157407** [comment]
是的,原生+h5混合开发app,在webview 里渲染h5 ios会卡顿，是平台问题。希望下次更新处理，touchstart触发press事件就避免了该情况，目前是在框架源码里改的，卡顿现象消失，使用流畅。移动端click 300毫米延迟




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 上午9:45
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "我爱你"<512157407@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] NumberKeyboard IOS系统快速输入卡慢 (#4112)




目前点击延迟的情况很少了，除非是 UIWebView

**Comment by lxc512157407** [comment]
和开发人员确定了下，用KWwebview也有此问题。




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 上午9:45
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "我爱你"<512157407@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] NumberKeyboard IOS系统快速输入卡慢 (#4112)




目前点击延迟的情况很少了，除非是 UIWebView

**Comment by lxc512157407** [comment]
是WKWebView，不好意思，刚刚打错了




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 上午9:45
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "我爱你"<512157407@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] NumberKeyboard IOS系统快速输入卡慢 (#4112)




目前点击延迟的情况很少了，除非是 UIWebView

**Comment by chenjiahan** [comment]
WKWebView 不会有问题，你可以去搜下

**Comment by chenjiahan** [comment]
viewport 要设置 user-scalable=no

**Comment by lxc512157407** [comment]
有设置的刚查阅的资料：
但是 WKWebView 在 iOS 9.3 的时候将这个问题给修复了。也就是说 iOS 9.3 之前 WKWebView 仍然是存在 300ms 延迟的问题的
https://www.jqhtml.com/44257.html




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 中午11:28
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "我爱你"<512157407@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] NumberKeyboard IOS系统快速输入卡慢 (#4112)




viewport 要设置 user-scalable=no

**Comment by chenjiahan** [comment]
下个版本会改成 touch 事件，不过 iOS 9 以下的占比已经很低了，可以有一定取舍

**Comment by lxc512157407** [comment]
嗯嗯，谢谢，刚好测试妹子有个测试机是ios 9的，嘤嘤，难受香菇。




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 中午11:38
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "我爱你"<512157407@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] NumberKeyboard IOS系统快速输入卡慢 (#4112)




下个版本会改成 touch 事件，不过 iOS 9 以下的占比已经很低了，可以有一定取舍

**Comment by lxc512157407** [comment]
问一个额外的问题就是省市区三级选择，什么时候可以自定义数据源，现在你们vant官方的数据源虽说是标准的，但是好多vant用户后端都是有自己的一套省市区id数据源，不可以自定义，不可能为了使用组建，去改动后端的数据，改动耦合性太强，这个组件不得不放弃。建议使用：
[
   //省列表
   {
      value: 1,
      text: '\u5317\u4eac',
      children: [
         //市列表
         {
            value: 35,
            text: '\u5317\u4eac\u5e02',
            children: [
               //区（县）列表
               { value: 36, text: '\u4e1c\u57ce\u533a' },
这种格式的话，你们组件遍历也好处理，用户按照这个格式也好自定义.
或许你们有更好的数据格式，看能否解决自定义数据源，我这边就是因为不可以自定义数据源不得不在主框架（vant）引用mint框架。UI风格没有更好的统一


------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 中午11:38
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "我爱你"<512157407@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] NumberKeyboard IOS系统快速输入卡慢 (#4112)




下个版本会改成 touch 事件，不过 iOS 9 以下的占比已经很低了，可以有一定取舍

**Comment by chenjiahan** [comment]
暂时没有计划支持自定义呢，你这种情况可以考虑用 Picker 去实现

**Comment by lxc512157407** [comment]
嗯，好的，有时间我去看看，谢谢你的回复，很及时。




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 中午11:56
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "我爱你"<512157407@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] NumberKeyboard IOS系统快速输入卡慢 (#4112)




暂时没有计划支持自定义呢，你这种情况可以考虑用 Picker 去实现

**Comment by chenjiahan** [comment]
已在 2.1.3 版本优化键盘点击
