### ISSUE TITLE
请问`uploader`组件`delete`事件如何阻止删除操作

### ISSUE THREAD

**Issue by aiyuchen** [youzan/vant#4114]
我是希望删除前能做个提醒，确定后再将其删除

测试代码如下，目前无法阻止删除
https://jsbin.com/yaqegec/edit?html,js,output

---

我是希望能够像`before-read`那样能支持返回一个`promise`，类似这样
```
onDel() {
    return new Promise((resolve, reject) => {
        Dialog.confirm({
            title: '你确定要删除图片吗？',
            message: '删除后需要重新选择图片进行提交'
        }).then(
            () => resolve()
        ).catch(
            () => reject()
        );
    });
}
```

**Comment by chenjiahan** [comment]
后续会支持下

**Comment by aiyuchen** [comment]
@chenjiahan 回调过来的参数也按照`before-read`那样传两个值吧，第一个是`file`，第二个是`detail`，比如我需要根据组件的name来进行判断，谢谢

**Comment by chenjiahan** [comment]
已在 2.1.3 版本支持 `before-delete` 属性
