### ISSUE TITLE
[Feature Request] Area 省市区选择

### ISSUE THREAD

**Issue by Mrwangfan** [youzan/vant#4127]
### 这个功能解决了什么问题
我用的我们公司自己的省市区数据，能不能把那个code大于9的都属于海外的改成传值的形式，不要直接写死值9

### 描述您想要的解决方案
动态传值

### 建议的API是什么样的
增加参数动态传值

**Comment by chenjiahan** [comment]
后续会看下怎么支持

**Comment by Mrwangfan** [comment]
好的  感谢

**Comment by chenjiahan** [comment]
已在 2.1.4 版本支持

**Comment by Mrwangfan** [comment]
感谢
