### ISSUE TITLE
定制主题的bug，我头痛了一天

### ISSUE THREAD

**Issue by Ficks** [youzan/vant#4129]
![image](https://user-images.githubusercontent.com/26001998/63154491-49805600-c043-11e9-8cd3-bbbee567f556.png)

按照官方文档走，一开始报错，然后下载了demo再复制了一遍可以了，然后下午的时候不知道为什么又莫名其妙的报错了

**Comment by chenjiahan** [comment]
建议检查下对应路径下的文件是否存在，或者删除 node_moduels 重新安装试下（可能是 cache-loader 缓存的问题）

**Comment by Ficks** [comment]
文件肯定是存在的，依赖也从新安装了几次，还是没效果，有效过一次，后面也没改什么，突然又报错，算了，不改主题了，直接覆盖样式算了😊




| |
ficksx
|
|
邮箱：ficksx@163.com
|

Signature is customized by Netease Mail Master

在2019年08月17日 11:01，neverland 写道：

建议检查下对应路径下的文件是否存在，或者删除 node_moduels 重新安装试下（可能是 cache-loader 缓存的问题）
