### ISSUE TITLE
[Bug Report] Uploader 文件上传单文件上传自动变为多文件上传

### ISSUE THREAD

**Issue by gloria912** [youzan/vant#4134]
### 设备 / 浏览器
ios/qq内置浏览器

### Vant 版本
2.1.3

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
在ios/qq内置浏览器下，所有文件上传都可以选择多张图片

**Comment by chenjiahan** [comment]
多选/单选是原生 input[type="file"] 标签的逻辑，组件提供的 multiple 也是原生属性

所以最终行为还是浏览器本身决定的，我们没有办法处理
