### ISSUE TITLE
[Bug Report] van-tabs使用自定义标签时内容无法显示

### ISSUE THREAD

**Issue by keffSha** [youzan/vant#4135]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.3

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vue-template-s05os?fontsize=14" target="_blank">https://codesandbox.io/s/vue-template-s05os?fontsize=14</a>

### 描述问题
给的链接仅仅是第一项无法显示，而我异步请求回来的数据用van-tabs组件的自定义标签全部无法正常渲染出来。

**Comment by chenjiahan** [comment]
你写的代码有问题，data2 没有初始值，onChange 是只有切换时才会触发的，所以你的第一项里面不会有内容

**Comment by keffSha** [comment]
那为什么切换回第一项时把值传过去了还是不行？
