### ISSUE TITLE
[Feature Request] 希望环形进度条的进度颜色支持渐变色

### ISSUE THREAD

**Issue by luffyli** [youzan/vant#4137]
### 这个功能解决了什么问题
丰富了进度条可定制的颜色

### 描述您想要的解决方案
可通过Prop传渐变色值实现渐变效果

### 建议的API是什么样的
N/A

**Comment by chenjiahan** [comment]
后续会看下怎么支持

**Comment by chenjiahan** [comment]
已在 2.1.4 版本支持
