### ISSUE TITLE
更新2.1.3版本后actionsheet组件报错

### ISSUE THREAD

**Issue by featnet** [youzan/vant#4138]
These dependencies were not found:

* vant/es/actionsheet in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/admin/clerkleader-wages.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/admin/order/order-list.vue?vue&type=script&lang=js& and 5 others
* vant/es/actionsheet/style in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/admin/clerkleader-wages.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/admin/order/order-list.vue?vue&type=script&lang=js& and 5 others

To install them, you can run: npm install --save vant/es/actionsheet vant/es/actionsheet/style

**Comment by chenjiahan** [comment]
见文档
https://youzan.github.io/vant/#/zh-CN/action-sheet#chang-jian-wen-ti

**Comment by featnet** [comment]
好了，谢谢！
