### ISSUE TITLE
PullRefresh  组件 与 Popup  一起使用时的问题

### ISSUE THREAD

**Issue by de1ck** [youzan/vant#414]
1. 在 PullRefresh  外面使用 Popup  失效 需要设置 padding 到一定距离才生效
2. 在 PullRefresh  内使用 当 PullRefresh   滚动条必须到 底部才能看到组件

**Comment by chenjiahan** [comment]
@deick 能否提供复现该问题的代码片段，或者 jsfiddle: https://jsfiddle.net/dfarLdko/1/

**Comment by de1ck** [comment]
@chenjiahan   https://jsfiddle.net/de1ck/x1y5wdL8/

**Comment by chenjiahan** [comment]
1. headHeight 顶部内容高度导致 button 点击失效确实是个问题，我们会在下个版本修复
2. Popup 内容在 scorller 底部出现的原因是 Chrome 的一个 bug，transform 元素内部的 fixed 定位是无效的，因此要避免在 PullRefresh 内部使用 Popup

**Comment by chenjiahan** [comment]
问题1已在 0.11.12 版本中修复
