### ISSUE TITLE
[Bug Report] tabbar 点击一个标签两次 报错 NavigationDuplicated

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#4141]
### 设备 / 浏览器
chorme

### Vant 版本
2.1.3

### Vue版本
2.5.20

### 重现链接
<a href="https://jsfiddle.net/906d3eun/26/" target="_blank">https://jsfiddle.net/906d3eun/26/</a>

### 描述问题
1:下面的tabbar 比如现在在首页 再点击首页就报错了
2: to的写法换成` :to="{name:'Home'}" `这样 标签就没有选中的状态了

![666789](https://user-images.githubusercontent.com/32523475/63220871-c423af80-c1c2-11e9-96f2-190598ae8444.png)

**Comment by chenjiahan** [comment]
这个是 VueRouter 新增加的一个重复跳转路由的报错提示，下个版本会兼容下

**Comment by lihaotian0607** [comment]
> 这个是VueRouter新增加的一个重复跳转路由的报错提示，下个版本会兼容下

to的写法换成:to="{name:'Home'}"这样标签就没有选中的状态了
这种写法也会在下个版本兼容么?

**Comment by chenjiahan** [comment]
这种写法理论上不会有你说的问题，能给个示例么

**Comment by lihaotian0607** [comment]
> 这种写法理论上不会有你说的问题，能给个示例么

https://jsfiddle.net/rjb6speq/3/

**Comment by chenjiahan** [comment]
ok，明白了，这个也会在下个版本支持

**Comment by chenjiahan** [comment]
已在 2.1.4 版本支持
