### ISSUE TITLE
[Feature Request] 建议增加popover组件

### ISSUE THREAD

**Issue by 2018Cool** [youzan/vant#4142]

**Comment by xujunjie10** [comment]
借个楼，ios微信浏览器在使用popup 组件最后一下有卡顿的问题。（iphonex，12.4）。谢谢

**Comment by ystarlongzi** [comment]
移动端应该很少有这种交互吧 [/疑惑]

**Comment by iseekTo** [comment]
你这样又增加了一次用户操作，没必要的。

**Comment by chenjiahan** [comment]
有这个需求的同学，可以把交互图发上来看下，我们评估下是否有必要实现

**Comment by 2018Cool** [comment]
交互类似微信点击右上角的加号按钮。见附件




| |
as
邮箱：zwccool@163.com
|

Signature is customized by Netease Mail Master

在2019年08月22日 15:32，neverland 写道：

有这个需求的同学，可以把交互图发上来看下，我们评估下是否有必要实现

**Comment by lihaotian0607** [comment]
@chenjiahan 
希望可以支持圆角  自定义图标等 

### 微信App:
![vant-微信](https://user-images.githubusercontent.com/32523475/63741888-65002200-c8c9-11e9-8969-b15129297126.png)

### QQApp:
![vant-qq](https://user-images.githubusercontent.com/32523475/63741895-6e898a00-c8c9-11e9-9648-252e03babb78.png)

### 支付宝App:
![vant-支付宝](https://user-images.githubusercontent.com/32523475/63741893-6a5d6c80-c8c9-11e9-8d84-a0c60cfb5e7e.png)

### 交通银行手机端:
![vant-手机银行](https://user-images.githubusercontent.com/32523475/63741872-53b71580-c8c9-11e9-9a5a-6e0b4b2824d6.png)

### 微博App
![vant-微博](https://user-images.githubusercontent.com/32523475/63741878-5b76ba00-c8c9-11e9-8ce3-31950c5f65f4.png)

![vant-酷狗](https://user-images.githubusercontent.com/32523475/63741866-49951700-c8c9-11e9-9e65-0bca5888d4d1.png)

**Comment by LynanBreeze** [comment]
之前用vant的popup魔改了一个这个

**Comment by Cifer-Y** [comment]
这种我都是用 popup 写的

**Comment by ChromeBing** [comment]
网页确定要弄得和APP一样，感觉很臃肿

**Comment by ErrorJe** [comment]
最近有类似需求，就是一种多选题，然后要对名词进行解释。目前用 v-tooltip 实现~~，希望 vant 也能够有

**Comment by xianshenglu** [comment]
我也觉得，不然我也要自己实现了

**Comment by xianshenglu** [comment]
譬如 https://mobile.ant.design/components/popover-cn/

**Comment by zhaoshuan** [comment]
产品偶尔会提这样的奇葩需求，所以觉得有必要添加下这个组件，比如，长按显示气泡

**Comment by wananzys** [comment]
最近几个项目,select下拉框用的也挺多...原生的太难看了

**Comment by zhuangxiaohui** [comment]
https://github.com/freeze-component/vue-popper

**Comment by HuberTRoy** [comment]
@zhaoshuan 
网页端的长按一般都会触发浏览器自带的各种事件吧。

**Comment by chocolate1** [comment]
![image](https://user-images.githubusercontent.com/26320639/91965015-78e32d00-ed42-11ea-8550-bf39b22d67cd.png)
建议增加气泡弹窗

**Comment by koeltp** [comment]
![image](https://user-images.githubusercontent.com/2775276/94354051-e5cfb580-00a9-11eb-84cd-1d5dcfa1d9c6.png)
还是希望能有气泡弹窗，比如这样的需求

**Comment by nyanboard** [comment]
我也强烈要求增加这个插件popover，这个插件感觉在移动端很常见

**Comment by liuyueqi18** [comment]
终于要增加了吗 哈哈哈 开心

**Comment by BirdLoveFish** [comment]
希望能增加这个component

**Comment by hzq-up** [comment]
> ![image](https://user-images.githubusercontent.com/26320639/91965015-78e32d00-ed42-11ea-8550-bf39b22d67cd.png)
> 建议增加气泡弹窗

王力宏？ 哈哈哈

**Comment by chenjiahan** [comment]
已在 2.11.0 版本增加 Popover 组件：https://youzan.github.io/vant/#/zh-CN/popover

**Comment by nyanboard** [comment]
nice

**Comment by An-mixiu** [comment]
Popover 组件不能使用for遍历多个，遍历后每次点击也全都同时打开了
![image](https://user-images.githubusercontent.com/43592453/102867326-9237f280-4473-11eb-9e8f-70d026c947fb.png)

**Comment by chenhaijun2019** [comment]
3.0版本 出现这个问题组件原因还是？
![e19536e4e37598433acc6f564fe3cae](https://user-images.githubusercontent.com/49867880/129836171-db17aa80-0cd3-426c-9cce-a207f936d7fe.png)

**Comment by 6LWa6ZKx** [comment]
> Popover 组件不能使用for遍历多个，遍历后每次点击也全都同时打开了
> ![image](https://user-images.githubusercontent.com/43592453/102867326-9237f280-4473-11eb-9e8f-70d026c947fb.png)

我也有这个问题，请问你如何处理的呢？

**Comment by guandaxia** [comment]
> Popover 组件不能使用for遍历多个，遍历后每次点击也全都同时打开了 ![image](https://user-images.githubusercontent.com/43592453/102867326-9237f280-4473-11eb-9e8f-70d026c947fb.png)

@you-heng @6LWa6ZKx 我是这么实现的  ` v-model="item.showPopover"`

```
<van-popover v-model="item.showPopover" placement="top" trigger="click">
              <van-grid
                square
                clickable
                :border="false"
                column-num="2"
                style="width: 100px;"
              >
                <van-grid-item
                  v-for="i in 2"
                  :key="i"
                  text="选项"
                  icon="photo-o"
                  @click="item.showPopover = false"
                />
              </van-grid>

     ...
```

**Comment by 6LWa6ZKx** [comment]
> 
非常感谢，晚上我试试。

**Comment by 6LWa6ZKx** [comment]
> > Popover 组件不能使用for遍历多个，遍历后每次点击也全都同时打开了 ![image](https://user-images.githubusercontent.com/43592453/102867326-9237f280-4473-11eb-9e8f-70d026c947fb.png)
> 
> @you-heng @6LWa6ZKx 我是这么实现的 ` v-model="item.showPopover"`
> 
> ```
> <van-popover v-model="item.showPopover" placement="top" trigger="click">
>               <van-grid
>                 square
>                 clickable
>                 :border="false"
>                 column-num="2"
>                 style="width: 100px;"
>               >
>                 <van-grid-item
>                   v-for="i in 2"
>                   :key="i"
>                   text="选项"
>                   icon="photo-o"
>                   @click="item.showPopover = false"
>                 />
>               </van-grid>
> 
>      ...
> ```

非常感谢，晚上我试试。
