### ISSUE TITLE
`field`字体错位问题

### ISSUE THREAD

**Issue by aiyuchen** [youzan/vant#4143]
输入框有个字体问题，不知道算不算BUG，找了一个多小时

-----

在官方演示网页的body里面有一段字体样式，这段样式应该是没有默认加到vant组件样式中的。如果缺少这段字体样式，输入框可能会错位，例如短信验证码输入框
```
font-family: 'PingFang SC', Helvetica, 'STHeiti STXihei', 'Microsoft YaHei', Tohoma, Arial, sans-serif;
```

我拿firefox做测试，可以看下截图
**正常的情况：**
![image](https://user-images.githubusercontent.com/578141/63227154-51442400-c216-11e9-8b8e-9b41671ba82b.png)

**错位的情况**
![image](https://user-images.githubusercontent.com/578141/63227184-83558600-c216-11e9-8ff5-65036e4b4792.png)

那么是不是应该在组件样式中添加上字体样式呢？

**Comment by chenjiahan** [comment]
本质上是 flex 布局的问题，按钮的宽度被 flex 压缩了，下个版本会修复

**Comment by yulimchen** [comment]
> 本质上是 flex 布局的问题，按钮的宽度被 flex 压缩了，下个版本会修复

在手机火狐上必现的 bug，电脑上复现不了比较难调试，看 commit 加了对 .van-field__control 加了 min-width: 0; 后果然奏效，感谢大佬😊~

**Comment by chenjiahan** [comment]
客气哈

**Comment by chenjiahan** [comment]
已在 2.1.4 版本修复
