### ISSUE TITLE
更新2.1.3后npm run出错

### ISSUE THREAD

**Issue by likess921** [youzan/vant#4145]
设备 / 浏览器
all

Vant 版本
2.1.3

Vue版本
2.6.10

重现链接
http://www.baidu.com

描述问题
Class constructor FileManager cannot be invoked without 'new' in undefined (line undefined, column undefined)

@ ./node_modules/_vant@2.1.3@vant/es/sidebar/index.less 4:14-254 14:3-18:5 15 2-262 @ ./node_modules/_vant@2.1.3@vant/es/sidebar/style/less.js @ ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./no _modules/_babel-loader@8.0.6@babel-loader/lib!./node_modules/_cache-loader@2.0 @cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.1@vue-load /lib??vue-loader-options!./src/views/goods/goodsselect/index.vue?vue&type=scri &lang=js& @ ./src/views/goods/goodsselect/index.vue?vue&type=script&lang=js& @ ./src/views/goods/goodsselect/index.vue @ ./src/router/index.js @ ./src/main.js @ multi ./node_modules/_webpack-dev-server@3.8.0@webpack-dev-server/client?ht ://10.68.105.172:13769/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

error in ./node_modules/_vant@2.1.3@vant/es/dialog/index.less

Module build failed (from ./node_modules/_less-loader@4.1.0@less-loader/dist/c .js):

Class constructor FileManager cannot be invoked without 'new' in undefined (line undefined, column undefined)

@ ./node_modules/_vant@2.1.3@vant/es/dialog/index.less 4:14-254 14:3-18:5 15: -262 @ ./node_modules/_vant@2.1.3@vant/es/dialog/style/less.js @ ./src/utils/message.js @ ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./no _modules/_babel-loader@8.0.6@babel-loader/lib!./node_modules/_cache-loader@2.0 @cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.1@vue-load /lib??vue-loader-options!./src/views/goods/index.vue?vue&type=script&lang=js& @ ./src/views/goods/index.vue?vue&type=script&lang=js& @ ./src/views/goods/index.vue @ ./src/router/index.js @ ./src/main.js @ multi ./node_modules/_webpack-dev-server@3.8.0@webpack-dev-server/client?ht ://10.68.105.172:13769/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

error in ./node_modules/_vant@2.1.3@vant/es/tabbar-item/index.less

Module build failed (from ./node_modules/_less-loader@4.1.0@less-loader/dist/c .js):

Class constructor FileManager cannot be invoked without 'new' in undefined (line undefined, column undefined)

@ ./node_modules/_vant@2.1.3@vant/es/tabbar-item/index.less 4:14-254 14:3-18: 15:22-262 @ ./node_modules/_vant@2.1.3@vant/es/tabbar-item/style/less.js @ ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./no _modules/_babel-loader@8.0.6@babel-loader/lib!./node_modules/_cache-loader@2.0 @cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.1@vue-load /lib??vue-loader-options!./src/components/common/Bottom.vue?vue&type=script&la =js& @ ./src/components/common/Bottom.vue?vue&type=script&lang=js& @ ./src/components/common/Bottom.vue @ ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./no _modules/_babel-loader@8.0.6@babel-loader/lib!./node_modules/_cache-loader@2.0 @cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.1@vue-load /lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js& @ ./src/App.vue?vue&type=script&lang=js& @ ./src/App.vue @ ./src/main.js @ multi ./node_modules/_webpack-dev-server@3.8.0@webpack-dev-server/client?ht ://10.68.105.172:13769/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

error in ./node_modules/_vant@2.1.3@vant/es/tabbar/index.less

Module build failed (from ./node_modules/_less-loader@4.1.0@less-loader/dist/c .js):

Class constructor FileManager cannot be invoked without 'new' in undefined (line undefined, column undefined)

@ ./node_modules/_vant@2.1.3@vant/es/tabbar/index.less 4:14-254 14:3-18:5 15: -262 @ ./node_modules/_vant@2.1.3@vant/es/tabbar/style/less.js @ ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./no _modules/_babel-loader@8.0.6@babel-loader/lib!./node_modules/_cache-loader@2.0 @cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.1@vue-load /lib??vue-loader-options!./src/components/common/Bottom.vue?vue&type=script&la =js& @ ./src/components/common/Bottom.vue?vue&type=script&lang=js& @ ./src/components/common/Bottom.vue @ ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./no _modules/_babel-loader@8.0.6@babel-loader/lib!./node_modules/_cache-loader@2.0 @cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.1@vue-load /lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js& @ ./src/App.vue?vue&type=script&lang=js& @ ./src/App.vue @ ./src/main.js @ multi ./node_modules/_webpack-dev-server@3.8.0@webpack-dev-server/client?ht ://10.68.105.172:13769/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

===package.json============================================ 
{
  "name": "myteam-mobile",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "devbuild": "vue-cli-service build --mode development",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "babel-plugin-import": "^1.12.0",
    "core-js": "^2.6.5",
    "lib-flexible": "^0.3.2",
    "moment": "^2.24.0",
    "npm": "^6.9.2",
    "postcss-px2rem": "^0.3.0",
    "px2rem-loader": "^0.1.9",
    "register-service-worker": "^1.6.2",
    "vant": "^2.1.3",
    "vue": "^2.6.10",
    "vue-amap": "^0.5.10",
    "vue-loader": "^15.7.1",
    "vue-router": "^3.0.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.9.0",
    "@vue/cli-plugin-eslint": "^3.9.0",
    "@vue/cli-service": "^3.9.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "less": "^3.0.4",
    "less-loader": "^4.1.0",
    "postcss-px2rem": "^0.3.0",
    "vue-loader": "^14.2.4",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}

**Comment by likess921** [comment]
不用cnpm就没问题，关了

**Comment by skyshirt** [comment]
同样的问题，没用cnpm，用的npm
更新less 3.10.1报错
把less降到3.9.0就没问题
