### ISSUE TITLE
[Bug Report] Toast动画效果错乱

### ISSUE THREAD

**Issue by Nancy2013** [youzan/vant#4146]
### 设备 / 浏览器
设备

### Vant 版本
2.1.2

### Vue版本
2.5.2

### 重现链接
<a href="http://10.10.30.70:8282/curtain/zh-cn/app.html#/portal" target="_blank">http://10.10.30.70:8282/curtain/zh-cn/app.html#/portal</a>

### 描述问题
移动端运行，同时安装ant-design-vue时，vant里Toast出现动画会乱掉，还有Toast.load的旋转动画也有问题，麻烦看一下

**Comment by chenjiahan** [comment]
试了下没问题，麻烦提供下复现的 codesandbox 链接

**Comment by Nancy2013** [comment]
> 试了下没问题，麻烦提供下复现的 codesandbox 链接

嗯嗯，试了一下，应该是别的地方有冲突，现在又可以了
