### ISSUE TITLE
[Feature Request] Uploader 上传图片后预览时返回上一页不关闭图片预览

### ISSUE THREAD

**Issue by liuxy0551** [youzan/vant#4149]
### 这个功能解决了什么问题
Uploader 上传图片后，点击图片预览。返回上一页时图片的预览不关闭。

### 描述您想要的解决方案
可以在 uploader 组件传入参数进行控制 预览图片返回上一页时是否自动关闭

### 建议的API是什么样的
在 vant/es/uploader 中的 onPreviewImage 方法中调用 ImagePreview 方法时传入参数 closeOnPopstate: true ，即使用图片预览组件的 closeOnPopstate 参数，建议把 closeOnPopstate 参数一并暴露给 uploader 组件

**Comment by chenjiahan** [comment]
这里确实应该默认设置为 true，不过暴露给 uploader 好像没什么必要

**Comment by liuxy0551** [comment]
好的，谢谢，等你们新版本

**Comment by chenjiahan** [comment]
已在 2.1.4 版本支持

**Comment by lgc2007** [comment]
可以把closeOnPopstate 暴露给uploader吗，因为我之前用的组件是返回的时候还可以预览，但是现在没有了，如果没有暴露的话，我就不能用预览的功能了。

**Comment by chenjiahan** [comment]
@lgc2007 可以新开一个 issue
