### ISSUE TITLE
Swipe组件的建议

### ISSUE THREAD

**Issue by cjx12580** [youzan/vant#4150]
Swipe组件建议增加一个每一页轮播开始就触发的事件

**Comment by chenjiahan** [comment]
具体使用场景是？

**Comment by zhaoshuan** [comment]
关于这个组件，我也有个建议，目前只能设置一屏显示一个slider，可否设置显示2个、2.5个或者更多

**Comment by zhaoshuan** [comment]
列表左滑，切换slider，场景使用挺多的

**Comment by BigCanZ** [comment]
我也觉得得有个轮播开始的事件，因为最近在项目中发现，手指滑动很容易误触点击跳转，不知道是不是我设置的不对，有个轮播开始事件和配合change事件就好处理这样的情况了

**Comment by chenjiahan** [comment]
> 关于这个组件，我也有个建议，目前只能设置一屏显示一个slider，可否设置显示2个、2.5个或者更多

可以用 width 属性来做

> Swipe组件建议增加一个每一页轮播开始就触发的事件

目前的 change 事件就是轮播开始就会触发的
