### ISSUE TITLE
[Feature Request] 求日历组件、带价格的日历组件、带打卡的日历组件

### ISSUE THREAD

**Issue by charliezzo** [youzan/vant#4153]
### 这个功能解决了什么问题
没有日历组件

### 描述您想要的解决方案
能用日历展示价格，用日历展示优惠信息，或者用日历展示打卡记录

### 建议的API是什么样的
一次传入需要展示的时间内的所有日期和价格或者其他信息

**Comment by chenjiahan** [comment]
暂无计划支持喔
