### ISSUE TITLE
actionsheet 无法使用

### ISSUE THREAD

**Issue by helen1314181** [youzan/vant#4154]
我现在用了actionsheet，但是界面上不显示，把show改为true的时候，当窗体加载完就进行了显示

我想要实现的效果，有一个输入框（可以使用cell），进行单击的时候弹出actionsheet框，进行选择，选择的内容添加到cell中

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
建议多看下 Vue 文档，补充下基础知识，大致写法是这样的

```html
<van-action-sheet :show="show" />

<van-cell @click="show = true" />
```

```js
export default {
  data() {
    return {
      show: false
    ;
  }
}
```
