### ISSUE TITLE
[Feature Request] tree-select左侧列表建议增加一个info实现列表图标右上角提示信息

### ISSUE THREAD

**Issue by likess921** [youzan/vant#4158]
### 这个功能解决了什么问题
效果类似于购物车右上角的数字提示信息，tree-select 2.1.3右侧content可以插槽自定义内容了，右侧列表选择内容后，左侧类别对应的显示info信息。

### 描述您想要的解决方案
tree-select左侧列表建议增加一个info实现列表图标右上角提示信息

### 建议的API是什么样的
Item 数据结构
items 整体为一个数组，数组内包含一系列描述分类的对象。

每个分类里，text 表示当前分类的名称。
info = 0 的时候不显示

[
  {
    // 导航名称
    text: '火锅',
    info: 0
  },
  {
    // 导航名称
    text: '炒菜',
    info: 5
  },
]

**Comment by chenjiahan** [comment]
后续会支持

**Comment by chenjiahan** [comment]
已在 2.2.0 版本支持
