### ISSUE TITLE
[Bug Report] van-image本地图片无法显示

### ISSUE THREAD

**Issue by lingkejia** [youzan/vant#4159]
### 设备 / 浏览器
Google Chrome 版本 76.0.3809.100（正式版本） （64 位）

### Vant 版本
2.1.3

### Vue版本
2.6.10

### 重现链接
<a href="http://crm.harmonye.cn:88" target="_blank">http://crm.harmonye.cn:88</a>

### 描述问题
使用van-image组件src路径为本地图片则无法显示，包括相对路径、绝对路径等方式，但加载远程图片正常

**Comment by likess921** [comment]
<img
      style="width:50px;height:50px;position: relative;top: 0.2rem;left: 0.4rem;"
      :src="require('@assets/img/jp/jp3.svg')"
 />

**Comment by likess921** [comment]
<img
      style="width:50px;height:50px;position: relative;top: 0.2rem;left: 0.4rem;"
      :src="require('@assets/img/jp/jp3.svg')"
 />

**Comment by likess921** [comment]
:src="require('@assets/img/jp/jp3.svg')"

**Comment by lingkejia** [comment]
it's fixed,thank you!

**Comment by Kawai-So** [comment]
如何解决？

**Comment by lingkejia** [comment]
> 如何解决？

:src="require('@assets/img/jp/jp3.svg')"

**Comment by Kawai-So** [comment]
不行 







------------------

Charles So
13352863258@qq.com



 




------------------ 原始邮件 ------------------
发件人: "Microwolf"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 下午4:47
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "Charles So"<248903778@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] van-image本地图片无法显示 (#4159)



 
如何解决？
  
:src="require('@assets/img/jp/jp3.svg')"

**Comment by lingkejia** [comment]
> 不行
> […](#)
> ------------------ Charles So 13352863258@qq.com
> ------------------ 原始邮件 ------------------ 发件人: "Microwolf"<notifications@github.com>; 发送时间: 2019年8月21日(星期三) 下午4:47 收件人: "youzan/vant"<vant@noreply.github.com>; 抄送: "Charles So"<248903778@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [youzan/vant] [Bug Report] van-image本地图片无法显示 (#4159) 如何解决？ :src="require('@assets/img/jp/jp3.svg')" — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

```
 <div class="user-box mb10">
        <div>
          <van-image round width="80" height="80" :src="require('@/assets/avatar.png')" />
          <p class="user-name">凌可佳</p>
        </div>
</div>
```

**Comment by qyqnl** [comment]
还是不行。。到底应该要怎么才能引用本地图片呢？特别是card里的thumb，有没有大佬指点一下，谢谢～

**Comment by snowdream** [comment]
> 还是不行。。到底应该要怎么才能引用本地图片呢？特别是card里的thumb，有没有大佬指点一下，谢谢～

指定图片宽高试试。
