### ISSUE TITLE
toast与其他组件库的toast冲突 

### ISSUE THREAD

**Issue by Niofh** [youzan/vant#4162]
估计大家都用Vue.prototype.$toast，这个怎么解决呢！！！

**Comment by chenjiahan** [comment]
$toast 这个命名不太好改了，改动影响太大

你可以直接 `import Toast from 'vant'`，然后自行挂载到 Vue 的原型上

**Comment by Niofh** [comment]
@chenjiahan 也不行，跟mand-ui冲突了...

**Comment by chenjiahan** [comment]
不明白你说的冲突指的是什么，上面提供的方法不会引起冲突

**Comment by tanshiqi** [comment]
遇到了同样的问题，我使用了
`import { Uploader } from "vant";`
估计是里面包含了toast组件，于是覆盖了我项目里原来定义的 Vue.prototype.$toast，请问如何才能禁用vant的toast
