### ISSUE TITLE
[Feature Request] Layout的row和col建议增加click事件

### ISSUE THREAD

**Issue by HuaChuDev** [youzan/vant#4165]
### 这个功能解决了什么问题
用layout做布局时经常需要在row或者col上加click事件，比如数据列表点击进入详情。

### 描述您想要的解决方案
希望在row和col上增加click事件

### 建议的API是什么样的
希望在row和col上增加click事件

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 2.1.4 版本支持
