### ISSUE TITLE
[Feature Request] [ 国际化」2.1.3更新后，vant/src/sku/Sku.js仍有一些中文硬编码待修改

### ISSUE THREAD

**Issue by ydcode** [youzan/vant#4166]
### 这个功能解决了什么问题
vant/src/sku/Sku.js 文件里，有“选择'”，“商品已经无法购买啦" 等中文硬编码待修改替换。

### 描述您想要的解决方案
参照2.1.3版本SKU国际化的改进方式。

### 建议的API是什么样的
参照2.1.3版本SKU国际化的改进方式。

**Comment by chenjiahan** [comment]
这里漏掉了，下个版本会改掉

**Comment by chenjiahan** [comment]
已在 2.1.4 版本修复
