### ISSUE TITLE
[Bug Report] 文件上传组件怎么获得未处理前的file 对象

### ISSUE THREAD

**Issue by s354988592** [youzan/vant#4168]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.3

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?type=Bug" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?type=Bug</a>

### 描述问题
文件上传组件怎么获得未处理前的file 对象

**Comment by chenjiahan** [comment]
能具体描述下么，具体是要用来做什么

**Comment by s354988592** [comment]
> 能具体描述下么，具体是要用来做什么

因为这个文件上传转的base64 并没有压缩图片
我需要在做一次压缩的操作 之后在传给后台 

现在还有个问题就是 在删除图片的预览时 回调里面是删除的文件对象 怎么拿到他的下标呢

**Comment by chenjiahan** [comment]
压缩图片的话，直接用 base64 或者里面的 File 对象都可以处理

下标用 indexOf 获取一下
