### ISSUE TITLE
[Feature Request] DatetimePicker 组件的 filter 属性，建议可以同时筛选不同属性

### ISSUE THREAD

**Issue by dreamqyq** [youzan/vant#4171]
### 这个功能解决了什么问题
目前 DatetimePicker 的 filter只能根据 type 单一的筛选某一个属性，比如day，month，year等，不同的属性时单独的数组，如果我筛掉了7月份，那么我就无法选择7月份所有的日子

### 描述您想要的解决方案
可以将DatetimePicker 的 选项数组（目前是分开的，比如年是一个数组，月是一个数组，日期是一个数组）整和成一个对象，这样就可以单独筛掉某一个日期（比如让7月4日不出现在选项中）

### 建议的API是什么样的
// 提供一个方法，传入一个对象，从而在现象中，月份选择7 时，day那一栏就不出现04这个选项，当选择8月份时，04选项仍然存在
     filter({
        year: '2019',
        month: '07',
        day: '04'
     })

**Comment by chenjiahan** [comment]
后续会看下能否支持

**Comment by chenjiahan** [comment]
看了下，暂时不会改成传入对象的方式，改动比较大。

这种情况可以用 Picker 自行实现
