### ISSUE TITLE
如何打包文档呀？

### ISSUE THREAD

**Issue by yinhui1129754** [youzan/vant#4174]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by yinhui1129754** [comment]
emmm 打包文档的命令为什么我这里只需要前面两条就可以了啊
![image](https://user-images.githubusercontent.com/19921594/63405310-fa5a6c80-c418-11e9-9af1-2fd94edda72f.png)
后面的命令貌似不用也可以啊 用了反而要报错呀 ？？？

**Comment by yinhui1129754** [comment]
后面的命令的作用是什么呀？

**Comment by yinhui1129754** [comment]
打包文档的命令在windows上面没法用 少了一个bat批处理的脚本

**Comment by chenjiahan** [comment]
后面的命令是部署文档网站用的，你可以忽略

> 打包文档的命令在windows上面没法用 少了一个bat批处理的脚本

具体指的是什么

**Comment by yinhui1129754** [comment]
1..sh在mac上可以正常使用 在windows上面没法用！
命令是这样用的 npm run release:site windows上没法用 mac可以正常用

2.还有就是内网开发的 有一个包没法用signale 这个包是控制台输出样式的 但是 cnpm没法同步到内网来 用不起 
3.然后 楼主如果有空 可以出一个自动加组件的命令 就是楼主的组件全部都在src下面 如果有一个可以自动加组件模板的命令就好了 每一个通用的组件 估计都需要一些特定的命令
4.px转rem的方法流程 有很大的问题 只把字体转了 然而宽度和高度等没有转 无语中...
