### ISSUE TITLE
van-pull-refresh 下拉刷新 提示居中

### ISSUE THREAD

**Issue by nickxin** [youzan/vant#4177]
van-pull-refresh 下拉过程中，“释放即可刷新” “ 加载中”居左了， 怎么自定义样式居中，可能是自己全局配置问题。

**Comment by nickxin** [comment]
在全局CSS中写了个 
=================
 .van-pull-refresh__head > * {
    text-align: center;
  }

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
