### ISSUE TITLE
倒计时组件

### ISSUE THREAD

**Issue by xqq0927** [youzan/vant#4178]
倒计时放在微信公众号 中 安卓显示 是对的 但是ios是NaN

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by haxuhaibing** [comment]
> 倒计时放在微信公众号 中 安卓显示 是对的 但是ios是NaN

`
//服务器获取的时间
let getdate = '2019-8-28 10:58:28'

//正则转换下格式
getdate.replace(/-/g,"/")  //2019/8/28 10:58:28
 `
