### ISSUE TITLE
[Bug Report] 为什么 vant area 的code必须是6位？

### ISSUE THREAD

**Issue by cnInkHao** [youzan/vant#4180]
### 设备 / 浏览器
h5

### Vant 版本
2.1.4

### Vue版本
2.6.10

### 重现链接
<a href="https://uat.x-vipay.com/h5-html" target="_blank">https://uat.x-vipay.com/h5-html</a>

### 描述问题
code大于6位时，无论怎么滑动都会处于第一位

**Comment by chenjiahan** [comment]
Area 是业务组件，有固定的数据格式，暂时没计划支持其他格式
