### ISSUE TITLE
[Bug Report] Uploader图片预览无法关闭

### ISSUE THREAD

**Issue by WPanglelina** [youzan/vant#4182]
### 设备 / 浏览器
iphone6s

### Vant 版本
2.1.1

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
图片预览打开后在iphone6s手机上无法关闭

**Comment by chenjiahan** [comment]
复现问题的 iOS 系统版本是？

**Comment by SharryXu** [comment]
Hi @chenjiahan,

我们在 FireFox 76.0.1 浏览器上用 2.5.9版本的 Vant，也遇到了同样的问题。请问有修复计划吗？或者有什么临时的解决办法去主动关闭这个预览？非常感谢！

**Comment by chenjiahan** [comment]
@SharryXu Firefox 是 PC 浏览器，参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

**Comment by SharryXu** [comment]
@chenjiahan 非常感谢！
