### ISSUE TITLE
一个非常严重的bug，van-popup，配合touchstart,touchmove,touchend等事件，弹窗一闪而过

### ISSUE THREAD

**Issue by ifxj** [youzan/vant#4185]
//绑定touchstart
  <li class="item rule" @touchstart ="setActivePop()">
                    <p class="tit">规则</p>
 </li>
//van-popup
 <van-popup v-model="showPop" >
                777777                
  </van-popup>
//事件方法
setActivePop(){
            this.showPop = true;
},
//弹窗一闪而过，自动关闭

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by ifxj** [comment]
已更改模板

**Comment by chenjiahan** [comment]
麻烦给个 codesandbox 复现链接哈
