### ISSUE TITLE
[Bug Report] 移动端touch事件控制van-popup，会出现一闪而过后自动关闭弹窗 

### ISSUE THREAD

**Issue by ifxj** [youzan/vant#4186]
### 设备 / 浏览器
安卓

### Vant 版本
2.1.4

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-7pppq" target="_blank">https://codesandbox.io/s/vant-issue-moban-7pppq</a>

<a href="https://7pppq.csb.app/" target="_blank">https://7pppq.csb.app/</a>

### 描述问题
移动端 https://7pppq.csb.app/

**Comment by chenjiahan** [comment]
这个问题的原因是：

click 事件是在 touchstart 之后触发的，你在 touchstart 的瞬间打开 Popup，紧接着 Popup 的蒙层上触发了 click 事件并关闭 Popup

这种情况把`close-on-click-overlay`属性设置成`false`即可避免

**Comment by divme** [comment]
vant 官方没有全量支持 touch 事件，排除 click 吗
