### ISSUE TITLE
[Bug Report] Area组件Bug

### ISSUE THREAD

**Issue by yxb941006** [youzan/vant#4194]
### 设备 / 浏览器
iOS、Chrome

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-xd8v3?fontsize=14" target="_blank">https://codesandbox.io/s/vant-issue-moban-xd8v3?fontsize=14</a>

### 描述问题
Area组件选择一级选择海外时，二级选择部分国家会直接跳到顶部，比如“乌干达”

**Comment by chenjiahan** [comment]
下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 2.1.5 版本修复
