### ISSUE TITLE
[Bug Report]  Grid组件 加上gutter属性边框有问题

### ISSUE THREAD

**Issue by jianyudahaoren** [youzan/vant#4198]
设备 / 浏览器
ios/微信内置浏览器、pc/谷歌浏览器

Vant 版本
2.1.4

Vue版本
2.6.10

描述问题
Grid组件 加上gutter属性边框会溢出宽度，左边框会变粗，与其他边框不一致

复现地址
https://youzan.github.io/vant/mobile.html#/zh-CN/grid

![微信图片_20190822200851](https://user-images.githubusercontent.com/11628312/63513437-cb2b2480-c518-11e9-8ba4-30e49450a377.png)
![微信图片_20190822201703](https://user-images.githubusercontent.com/11628312/63513846-dd599280-c519-11e9-919a-64bdc34e2e1a.png)

**Comment by chenjiahan** [comment]
跟这个是同个问题，会在下个版本修复

https://github.com/youzan/vant/issues/4181
