### ISSUE TITLE
Failed to load font https://img.yzcdn.cn/vant/vant-icon-3a7dc2.woff

### ISSUE THREAD

**Issue by chenyi5266** [youzan/vant#4199]
开发工具报错
Failed to load font https://img.yzcdn.cn/vant/vant-icon-3a7dc2.woff

有时手机的图标显示不出来，图标就一个框

**Comment by chenjiahan** [comment]
这种情况可能是网络问题，可以考虑使用本地图标，具体引入方式见 Icon 组件文档
