### ISSUE TITLE
[Bug Report]field的clearable失效

### ISSUE THREAD

**Issue by sanyu1225** [youzan/vant#4204]
"
<van-cell-group>
  <van-field
    v-model="username"
    required
    clearable
    label="用户名"
    right-icon="question-o"
    placeholder="请输入用户名"
    @click-right-icon="$toast('question')"
  />

  <van-field
    v-model="password"
    type="password"
    label="密码"
    placeholder="请输入密码"
    required
  />
</van-cell-group>

"
按照官網這樣子打 並且也有綁定v-model
clearable卻失效

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
