### ISSUE TITLE
van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？

### ISSUE THREAD

**Issue by wangdong1209** [youzan/vant#4207]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
用 filter 属性即可，文档里有示例

**Comment by cangyu1993** [comment]
哥们不看文档吗？

**Comment by wangdong1209** [comment]
再次研究哈





------------------ 原始邮件 ------------------
发件人: "徐勇"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午2:44
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




哥们不看文档吗？

**Comment by wangdong1209** [comment]
你说得是这种办法对吧<van-datetime-picker   v-model="currentTime"   type="time"   :filter="filter" /> export default {   data() {     return {       currentTime: '12:00'     };   },   methods: {     filter(type, options) {       if (type === 'minute') {         return options.filter(option => option % 30 === 0)       }       return options;     }   } }




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午2:43
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




用 filter 属性即可，文档里有示例

**Comment by cangyu1993** [comment]
难到你的需求不是这样吗？

**Comment by cangyu1993** [comment]
你的意思难道是数值正常显示，然后滑动一下立刻滑到30前或后？这样的话很难搞啊

**Comment by wangdong1209** [comment]
对，分钟的显示以半个小时为一个步长，最后分钟那个picker-view部分只显示00，30我做的小程序，这个可以搞不？




------------------ 原始邮件 ------------------
发件人: "徐勇"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午2:52
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




你的意思难道是数值正常显示，然后滑动一下立刻滑到30前或后？这样的话很难搞啊

**Comment by wangdong1209** [comment]
要求这种显示，能设置吗？


------------------ 原始邮件 ------------------
发件人: "徐勇"<notifications@github.com>;
发送时间: 2019年8月23日(星期五) 下午2:52
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "水月流星"<542495420@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




你的意思难道是数值正常显示，然后滑动一下立刻滑到30前或后？这样的话很难搞啊

**Comment by cangyu1993** [comment]
![image](https://user-images.githubusercontent.com/42930030/63573086-02e8a980-c5b7-11e9-90b5-62b802199e44.png)
它 返回的是数组，你想自定义只显示00和30那就自己写一个死的数组
![image](https://user-images.githubusercontent.com/42930030/63573092-0bd97b00-c5b7-11e9-98c5-8e56ef87f49e.png)
![Uploading image.png…]()
 我这是天，你改成分钟就可以了

**Comment by wangdong1209** [comment]
谢谢大神,我在试试




------------------ 原始邮件 ------------------
发件人: "徐勇"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午3:03
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)





 它 返回的是数组，你想自定义只显示00和30那就自己写一个死的数组
 
 
 我这是天，你改成分钟就可以了

**Comment by cangyu1993** [comment]
我估计你是没搞清楚过滤数组的规则，不想过滤就写死吧

**Comment by wangdong1209** [comment]
我用的组件,加formatter这个属性，滑动时，函数不执行





------------------ 原始邮件 ------------------
发件人: "徐勇"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午3:08
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




我估计你是没搞清楚过滤数组的规则，不想过滤就写死吧

**Comment by cangyu1993** [comment]
这和formatter没关系吧，它俩是相互独立的，formatter是格式化的，同时和filter使用应该没问题

**Comment by wangdong1209** [comment]
------------------ 原始邮件 ------------------
发件人: "徐勇"<notifications@github.com>;
发送时间: 2019年8月23日(星期五) 下午3:08
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "水月流星"<542495420@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




我估计你是没搞清楚过滤数组的规则，不想过滤就写死吧

**Comment by wangdong1209** [comment]
文档中就是这个属性，没有你说的filter




------------------ 原始邮件 ------------------
发件人: "徐勇"<notifications@github.com>;
发送时间: 2019年8月23日(星期五) 下午3:13
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "水月流星"<542495420@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




这和formatter没关系吧，它俩是相互独立的，formatter是格式化的，同时和filter使用应该没问题

**Comment by cangyu1993** [comment]
https://codesandbox.io/embed/vue-template-us3p8?fontsize=14

看看是这样吗？

**Comment by wangdong1209** [comment]
我用的原生微信小程序开发的，写法就是刚才给你的截图




------------------ 原始邮件 ------------------
发件人: "徐勇"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午3:20
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




https://codesandbox.io/embed/vue-template-us3p8?fontsize=14
 
看看是这样吗？

**Comment by cangyu1993** [comment]
那我感觉就是小程序版没有filter这个钩子，得@向开发者了

**Comment by wangdong1209** [comment]
还有个ui框架叫wux webapp,那个里边可以实现，但是一个项目引入两个ui框架，会冲突






------------------ 原始邮件 ------------------
发件人: "徐勇"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午3:28
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




那我感觉就是小程序版没有filter这个钩子，得@向开发者了

**Comment by chenjiahan** [comment]
小程序版目前不支持的，另外这里是 Vue 仓库

**Comment by wangdong1209** [comment]
好吧，官方文档给出的小程序引入，就是从这里获取组件的，谢谢你啦




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午3:31
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




小程序版目前不支持的，另外这里是 Vue 仓库

**Comment by cangyu1993** [comment]
对啊，搞了我看了半天，我还纳闷小程序的怎么跑到这里来了？小程序都是按自定义组件方式引入的，怎么会有冲突呢

**Comment by wangdong1209** [comment]
谢谢你们能耐心的帮我这个菜鸟解决问题，再次感谢你们的热情回复




------------------ 原始邮件 ------------------
发件人: "徐勇"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午3:34
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] van-datetime-picker组件，当type值为time时，怎么设置分钟数滑动一次相隔30分钟？ (#4207)




对啊，搞了我看了半天，我还纳闷小程序的怎么跑到这里来了？小程序都是按自定义组件方式引入的，怎么会有冲突呢
