### ISSUE TITLE
[Bug Report] 在an-pull-refresh内嵌套van-list，下拉刷新多次后，页面如果使用了定位布局，刷新后页面样式会出现错乱问题。

### ISSUE THREAD

**Issue by XiaoRIGE** [youzan/vant#4209]
### 设备 / 浏览器
安卓小米7.1.1

### Vant 版本
2.0.9

### Vue版本
2.5.2

### 重现链接
<a href="http://192.168.255.186:8080/#/JobHunting" target="_blank">http://192.168.255.186:8080/#/JobHunting</a>

### 描述问题
在an-pull-refresh内嵌套van-list，下拉刷新多次后，页面如果使用了定位布局，刷新后页面样式会出现错乱问题。当去掉页面定位的类样式，下拉刷新不会再出现问题。

**Comment by chenjiahan** [comment]
复现链接打不开，能否提供下 codesandbox 复现链接

**Comment by qwekelly** [comment]
@chenjiahan 你好，我这边确实也复现了。下面是复现的代码例子
<div>
    <div class="header_flex">
      <img class="logo" src="../../images/logo.png" alt="">
      <p>顶部flex定位块</p>
    </div>
    
    <van-pull-refresh class="refresh" v-model="pullLoading" @refresh="onRefresh">
      <van-list
        v-model="isLoading"
        :finished="finished"
        finished-text="没有更多了"
        @load="onLoad"
        :immediate-check="false">
        <div class="area_con">
          <company-card v-for="(item, index) in list"
                        :key="index"
                        :startDate="item.start_date"
                        :operName="item.oper_name"
                        :regCapi="item.reg_capi"
                        :logo="item.logo"
                        :id="item.id"
                        :name="item.name"/>
        </div>
      </van-list>
    </van-pull-refresh>
    <div class="footer_flex">
      <div class="record">
        <p>底部flex定位块</p>
      </div>
    </div>
  </div>

**Comment by chenjiahan** [comment]
@qwekelly 麻烦提供下 codesandbox 复现链接

**Comment by qwekelly** [comment]
@chenjiahan  重现链接
https://m-test.zdao.com/acah/3401/index_1.html
设备：vivo z1 chrome浏览器

**Comment by chenjiahan** [comment]
你的页面没法调试喔
