### ISSUE TITLE
picker 滑动出现弹跳回归

### ISSUE THREAD

**Issue by gy0831** [youzan/vant#4210]
设备 / 浏览器
iOS、Chrome

Vant 版本
2.1.4

Vue版本
2.6.10

按住拖动，松手时会跳回原值或不是滚动对应的值，android正常

**Comment by chenjiahan** [comment]
能否提供一下复现链接，或者录屏看下

**Comment by gy0831** [comment]
给您发了个邮件，您看下

**Comment by chenjiahan** [comment]
这个引入是 touch-emulator 或 fastclick 导致在滑动之后又触发了 click 事件引起的问题，下个版本会修复一下

**Comment by chenjiahan** [comment]
已在 2.1.8 版本修复

**Comment by chen-can** [comment]
测试了下2.1.8 版本和新版本中未修复 项目引入了fastclick
