### ISSUE TITLE
[Bug Report] field的clearable失效 

### ISSUE THREAD

**Issue by sanyu1225** [youzan/vant#4211]
设备 / 浏览器
iOS、Chrome

Vant 版本
2.0.6

Vue版本
2.6.10

重现链接
https://codesandbox.io/s/vant-issue-moban-9rg7p

描述问题
按照官網這樣子打 並且也有綁定v-model
clearable卻失效

**Comment by chenjiahan** [comment]
看了下没问题呀
<img width="396" alt="屏幕快照 2019-08-23 下午5 24 03" src="https://user-images.githubusercontent.com/7237365/63582004-d2126f80-c5ca-11e9-8612-902565824bb1.png">

**Comment by sanyu1225** [comment]
x點下去後 v-modal沒被清空

**Comment by chenjiahan** [comment]
这里使用的是 touch 事件，只在手机上或 chrome 手机模式会生效，如果你需要在桌面端使用，可以参考这篇文档 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong
