### ISSUE TITLE
[Bug Report] 手机QQ浏览器下Radio组件图标变形

### ISSUE THREAD

**Issue by yulimchen** [youzan/vant#4212]
设备 / 浏览器
Android 7.0、手机QQ浏览器

Vant 版本
2.1.4

Vue版本
2.6.10

重现：
![QQ图片20190823150654_副本](https://user-images.githubusercontent.com/5179249/63580763-16e8d700-c5c8-11e9-83e2-4b8175e27fb8.jpg)

描述问题
Radio 组件图标会有轻微变形，有些变扁，有些变高。

**Comment by chenjiahan** [comment]
能否提供一个 codesandbox 复现链接呢

**Comment by yulimchen** [comment]
> 能否提供一个 codesandbox 复现链接呢

很抱歉大佬，我用 codesandbox 尝试过复现不了，不知道具体哪个步骤出了问题。。项目里我基于的是 viewport 适配的移动端，结构是如下：

`<div class="goods-container">
        <van-radio-group v-if="gameName" v-model="goodsId">
          <van-row>
            <van-col v-for="(item, index) in goodsList" :key="index" class="radio-item" span="12">
              <van-radio :name="item.goods_id">{{ item.goods_name }}</van-radio>
            </van-col>
          
          </van-row>
        </van-radio-group>
        <div v-else>
          <h4 style="text-align: center; font-weight: 400;">请选择游戏</h4>
        </div>
      </div>`

**Comment by ystarlongzi** [comment]
上周我们业务上（没有用 vant）也有类似的问题， 也是部分手机上会出现椭圆的问题，猜测是对元素的宽高使用 rem 导致的，将 rem 换成 px 后就正常了

**Comment by yulimchen** [comment]
> 上周我们业务上（没有用 vant）也有类似的问题， 也是部分手机上会出现椭圆的问题，猜测是对元素的宽高使用 rem 导致的，将 rem 换成 px 后就正常了

好的了解~

**Comment by chenjiahan** [comment]
楼上正解哈，这个应该是浏览器对非整数宽高时的渲染问题，和组件无关
