### ISSUE TITLE
van-cell 图片

### ISSUE THREAD

**Issue by ChinaArJun** [youzan/vant#4213]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by ChinaArJun** [comment]
<van-cell   icon=""  设置为本地图片不显示

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
