### ISSUE TITLE
vant treeselect solts content  怎么使用？demo中只体现了 单选多选。。

### ISSUE THREAD

**Issue by dachie** [youzan/vant#4215]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
```html
<van-tree-select>
  <div slot="content">My Content</div>
</van-tree-select>
```
