### ISSUE TITLE
[Feature Request] Notify 建议增加类型 

### ISSUE THREAD

**Issue by jianyudahaoren** [youzan/vant#4220]
这个功能解决了什么问题
当通知是成功或者失败等常用类型时，不用需要再次定义类型样式，直接调用关键字就好，便于统一样式。

描述您想要的解决方案
就像button组件的那种 type默认default、primary、info、warning、danger五种类型可以选择。

建议的API是什么样的
Notify({
  message: '通知内容',
  duration: 1000,
  type: 'warning'
});

**Comment by chenjiahan** [comment]
可以的，会支持这个功能

**Comment by chenjiahan** [comment]
已在 2.1.6 版本支持
