### ISSUE TITLE
建议自定义键盘双向绑定的时候input能添加光标

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#4221]
### 这个功能解决了什么问题
比如一个页面有多个输入框使用了自定义键盘，键盘谈起的时候，没有光标提示，用户不知道对应的哪个，当然也可以用自定义键盘加title，但是体验可能没有虚拟光标好

### 描述您想要的解决方案
如上，大佬辛苦了

### 建议的API是什么样的
如上，大佬辛苦了

**Comment by chenjiahan** [comment]
可以的，后续会支持下

**Comment by chenjiahan** [comment]
已在 2.1.8 版本支持光标
