### ISSUE TITLE
[Bug Report] 虚拟键盘自定义键盘使用title时显示bug

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#4222]
### 设备 / 浏览器
ios

### Vant 版本
2.1.5

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/number-keyboard" target="_blank">https://youzan.github.io/vant/#/zh-CN/number-keyboard</a>

### 描述问题
当使用虚拟键盘自定一键盘的时候，设置了title，右侧的确认和删除按钮样式会往上顶

![image](https://user-images.githubusercontent.com/21211777/63635395-cc815c00-c694-11e9-9ad3-b0d73e6e8287.png)

**Comment by chenjiahan** [comment]
下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 2.1.6 版本修复
