### ISSUE TITLE
[Feature Request] image 组件支持圆角

### ISSUE THREAD

**Issue by kid1412621** [youzan/vant#4223]
### 这个功能解决了什么问题
给图片加圆角

### 描述您想要的解决方案
添加个圆角属性

### 建议的API是什么样的
添加个圆角属性 fillet

**Comment by chenjiahan** [comment]
下个版本会支持，属性名为`radius`

**Comment by chenjiahan** [comment]
已在 2.1.6 版本支持

**Comment by kid1412621** [comment]
哇，支持好快！个人建议组件上开启 `radius` ，但不填写数值，然后在忙 style 块中使用 `border-radius` 定义数值， 这样做的好处是能使用 postcss 来预处理。
