### ISSUE TITLE
[Bug Report] Tabbar 路由模式下激活项错误

### ISSUE THREAD

**Issue by Cheng007** [youzan/vant#4224]
### 设备 / 浏览器
chrome 76.0.3809.100

### Vant 版本
2.1.5

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-p0ygv" target="_blank">https://codesandbox.io/s/vant-issue-moban-p0ygv</a>

### 描述问题
Tabbar 路由模式下只要其中一项处于激活状态(点击其中一个TabbarItem)，
则其它 TabbarItem 也将处于激活状态(默认都显示为蓝色)
![image](https://user-images.githubusercontent.com/13946264/63635941-14a37d00-c69b-11e9-9722-dd873a0bd395.png)

**Comment by chenjiahan** [comment]
感谢反馈，最新版本里如果不指定 route 的 name 会出现这个问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.1.6 版本修复
