### ISSUE TITLE
[Bug Report] PullRefresh和List组合使用时，当finished为false时触发下拉刷新，不执行load检测

### ISSUE THREAD

**Issue by lifanlingjue** [youzan/vant#4225]
### 设备 / 浏览器
Chrome

### Vant 版本
2.1.3

### Vue版本
2.6.6

### 重现链接
<a href="http://39.97.176.59:8866/app/#/report?active=2" target="_blank">http://39.97.176.59:8866/app/#/report?active=2</a>

### 描述问题
这两个组件组合使用时，我在代码内写了一个简单的分页，请求第一页数据后 就填满了整个屏幕 所以此时的状态时loading是false，finished是false，这时当我下拉刷新时，我首先将分页信息reset， 再清空数据，这时finished还是false，loading也没有改变，所以watch监听就不会触发check，绑定的scroll事件也没有触发check  所以这个时候页面就不会执行load了。
但是第二种情况 在我所有数据都请求完以后再进行下拉刷新，这时finished的状态时true，我下拉刷新时 将分页信息重置了，所以finished的状态会变为false，会被watch监听到 从而触发check，执行load，这时就没有问题

我觉得既然使用了封装好的组件，就不应该让开发人员在业务代码部分去自己手动触发这个load。是不是应该完善一下监听的机制
或者您有什么好的解决方法，烦请指点指点我。

重现链接我为您创建一个临时账号，testbug/testbug,浏览器访问后请F12调制手机模式，登录后点击report 的tab页 就能复现

**Comment by chenjiahan** [comment]
这种情况可以在 reset 之后调一下 this.$refs.list.check

因为组件监听的是 scroll 事件，感知不到『列表内容被清空』这个动作

**Comment by lifanlingjue** [comment]
> 这种情况可以在 reset 之后调一下 this.$refs.list.check
> 
> 因为组件监听的是 scroll 事件，感知不到『列表内容被清空』这个动作

但是手动调check的时候  如果这时的分页加载完了 会死循环的无限调load方法，这个我没想明白是为什么。。。

**Comment by chenjiahan** [comment]
不会呀，分页加载完了意味着 finished 为 true，这时候调用 check 不会发生任何事情

**Comment by lifanlingjue** [comment]
> 不会呀，分页加载完了意味着 finished 为 true，这时候调用 check 不会发生任何事情

就是因为我得置为false后 才会check成功呀，这时watch监听到finished变化了会触发check   我再手动check一下 就会出现死循环，但是这个死循环我没想明白是在哪出现的。。。页面就卡死了  需要退出浏览器

**Comment by chenjiahan** [comment]
理论上不会有，建议检查下你的代码，确认下是否有循环调用

**Comment by ystarlongzi** [comment]
> 就是因为我得置为false后 才会check成功呀，这时watch监听到finished变化了会触发check 我再手动check一下

``` javascript
onRefresh() {
  this.finished = false;
  this.$refs.list.check();
}
```

再数据列表加载完成后，执行类似上面的逻辑，确实会连续触发两次 load，但理论上不会死循环

**Comment by ystarlongzi** [comment]
@lifanlingjue 我将 [demo 处的 `onRefresh` 的逻辑](https://github.com/youzan/vant/blob/dev/src/list/demo/index.vue#L109-L118)调整为如下，你可以参考下

``` javascript
onLoad(index) {
  const list = this.list[index];
  list.loading = true; // 🐞在每次获取数据前，一定定定将 loading 设置为 true

  setTimeout(() => {
    list.loading = false;
    list.refreshing = false; // 🐞在数据获取完成后，一定定定将 loading、refreshing 再设置为 false
    // ......... 其它逻辑
  }, 500) 
},

onRefresh(index) {
  const list = this.list[index];
      
  list.items = [];
  list.error = false;
  list.finished = false;

  // 🍉🍉 记得将两个 `<van-list ref="" />` 分别加上 ref 属性
  this.$refs[`list${index}`].check();
}
```
