### ISSUE TITLE
Notify教程参数和实际参数不一致，导致配置无效

### ISSUE THREAD

**Issue by jifeilong9** [youzan/vant#4226]
文档教程中的参数
![image](https://user-images.githubusercontent.com/24316291/63637043-4839d380-c6aa-11e9-9636-ece1eb575a2c.png)
代码中实际参数
![image](https://user-images.githubusercontent.com/24316291/63637055-64d60b80-c6aa-11e9-9ac5-74feb258728b.png)

**Comment by chenjiahan** [comment]
请注意你看的是 Vue 版本的文档还是小程序版本的文档，个别参数是不一样的
