### ISSUE TITLE
[Feature Request] Uploader 支持服务器返回的状态

### ISSUE THREAD

**Issue by jianyudahaoren** [youzan/vant#4231]
### 这个功能解决了什么问题

目前上传图片预览列表区无法给定服务器返回的状态，
例如上传中、上传失败、上传完成。
这样就能使用组件自带的列表，
必须得自定义个列表，
例如preview-size，preview-full-image，before-delete，max-count等这些功能都不能用了，
都要自己重写一遍，使得自带的组件的预览列表从某意义上来说失去了作用。

### 描述您想要的解决方案**

建议可以在绑定列表的数组里增加一个status属性，
当上传状态改变时改变这个属性值来控制显示列表中的文件上传状态，
然后可以在afterRead中实现状态变更

### 建议的API是什么样的

**v-model绑定的列表**
```
fileList: [{
    url: 'https://img.yzcdn.cn/vant/cat.jpeg' 
    status:'done' 状态有：uploading, done, error
}]
```
然后就可以在afterRead中实现状态变更

**或者像antdesign的上传组件那样，有个onChange上传文件改变时的状态**
https://2x.ant.design/components/upload-cn/

**Comment by chenjiahan** [comment]
后续会支持这个 feature

**Comment by chenjiahan** [comment]
已在 2.4.7 版本支持
