### ISSUE TITLE
NumberKeyboard 数字键盘 不显示

### ISSUE THREAD

**Issue by lhm96762186** [youzan/vant#4233]
Vant 版本
2.1.5

Vue版本
2.6.10

描述问题
![图片1](https://user-images.githubusercontent.com/34635987/63651042-bacab200-c783-11e9-9f80-48c9c5b4c705.png)
![图片2](https://user-images.githubusercontent.com/34635987/63651048-c3bb8380-c783-11e9-9e7c-4d7c3a81497c.png)
![图片3](https://user-images.githubusercontent.com/34635987/63651068-eea5d780-c783-11e9-80df-7744ea6d90ba.png)

数字键盘是按照上面的方式引入的，但是在浏览器中却没有显示。

**Comment by chenjiahan** [comment]
能否提供一下复现的 codesandbox 链接呢

另外 Vue 中的 data 应为一个函数，而不是对象

**Comment by lhm96762186** [comment]
codesandbox 链接：https://codesandbox.io/s/static-1mnuo

**Comment by lhm96762186** [comment]
codesandbox 链接：https://codesandbox.io/s/static-1mnuo
@chenjiahan

**Comment by chenjiahan** [comment]
你这个链接建的有问题，JS 没有被编译，在浏览器里直接报错了

**Comment by cangyu1993** [comment]
你这是按需引入，但是从你的代码看不出是自动按需引入还是手动按需引入，样式可能没引入，还有你引入vue为什么要嵌套那么多目录？可以这样吗？我没试过这样引入vue暂不说有没有问题，还有data是一个函数内部返回一个对象，对象内是变量
