### ISSUE TITLE
Dialog组件调用出现Vue warn：$attrs is readonly， $listeners is readonly

### ISSUE THREAD

**Issue by lhm96762186** [youzan/vant#4234]
Vant 版本
2.1.5

Vue版本
2.6.10

问题描述
![图片6](https://user-images.githubusercontent.com/34635987/63651342-30d01880-c786-11e9-8c0b-30730aee2575.png)
![图片4](https://user-images.githubusercontent.com/34635987/63651270-89eb7c80-c785-11e9-82e1-7fda699765cf.png)
![图片5](https://user-images.githubusercontent.com/34635987/63651281-a687b480-c785-11e9-8bab-e21c153becc7.jpg)

**Comment by chenjiahan** [comment]
建议确认下是否引入了多份 Vue 代码
