### ISSUE TITLE
关于时间选择器的问题

### ISSUE THREAD

**Issue by lc-Coco** [youzan/vant#4239]
设备 / 浏览器
Chrome

Vant 版本
2.1.6

Vue版本
2.5.2

      <van-datetime-picker
        v-model="currentDate"
        type="datetime"
        :min-date="minDate"
        :min-hour="0"
        :max-hour="24"
        :min-minute="0"
        :max-minute="0"
      />

这么写没反应， 分钟都不是00

这是效果图
https://resource.adongcar.com/1566791641428front.png

**Comment by chenjiahan** [comment]
`min-minute` 和 `max-minute` 是针对 `time` 类型的，文档里有描述

你这个可以用 `filter` 属性来实现
