### ISSUE TITLE
Cannot disable the checkbox if it's nested in the checkbox-group

### ISSUE THREAD

**Issue by chuangbo** [youzan/vant#424]
**What is the current behavior?**
When using the `van-checkbox` along with the `checkbox-group`, the `disabled` prop does not work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**
https://jsfiddle.net/61qyky3L/1/

**What is the expected behavior?**
Able to disable single checkbox if the parent group's `disabled` prop not set.

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

vant@0.11.10
vue@3.0.1

**Comment by Tinysymphony** [comment]
computed propterty `isDisabled` in checkbox component leads to this bug.

**Comment by chenjiahan** [comment]
Will be fixed in next version

**Comment by chenjiahan** [comment]
fixed in v0.11.11
