### ISSUE TITLE
怎么获取radio的文本

### ISSUE THREAD

**Issue by aierong** [youzan/vant#4240]
radio组件:

 ` <van-radio-group v-model="radioval"
                        >
            <van-radio  
                       :key="_index"
                       v-for="(item,_index) in radiolist"
                       :name="item.val">{{ item.txt }}
            </van-radio>
        </van-radio-group>`

数据源:
`radiolist : [
                    {
                        txt : '选择我1' ,
                        val : '1v'
                    } ,
                    {
                        txt : '选我2' ,
                        val : '2v'
                    } ,
                    {
                        txt : '点我3' ,
                        val : 'v3'
                    } ,

 ]`

我想获取txt中的值

**Comment by chenjiahan** [comment]
```js
export default {
  data() {
    return {
      radioVal: '1v',
      radioList: [
        { txt : '选我1' , val : '1v' } ,
        { txt : '选我2' , val : '2v' } ,
        { txt : '点我3' , val : '3v' } 
      ]
    };
  },

  computed: {
    // 通过计算属性映射一下
    radioTxt() {
      return this.radioList.filter(item => item.val === this.radioVal)[0].txt;
    }
  }
}
```
