### ISSUE TITLE
[Bug Report] van-stepper 异步变更会触发两次 change 事件

### ISSUE THREAD

**Issue by hooray** [youzan/vant#4241]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.6

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-wtxwo?fontsize=14" target="_blank">https://codesandbox.io/embed/vant-issue-moban-wtxwo?fontsize=14</a>

### 描述问题
可以打开console查看，每次异步变更都会触发两次 change 事件，在具体业务中会触发两次 ajax 请求

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4092
