### ISSUE TITLE
[Bug Report] van-field组件在disabled时right-icon仍然可点击

### ISSUE THREAD

**Issue by wuzhou98** [youzan/vant#4244]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.6

### Vue版本
2.5.22

### 重现链接
<a href="https://codesandbox.io/s/vue-template-ne5db" target="_blank">https://codesandbox.io/s/vue-template-ne5db</a>

### 描述问题
van-field组件在 :disabled='true'时，其 right-icon 仍可点击，并会触发 click-right-icon 事件。

**Comment by chenjiahan** [comment]
disabled 只是禁用输入，不会禁用按钮的点击事件喔，你可以在事件的回调函数里进行逻辑判断
