### ISSUE TITLE
还是打包问题

### ISSUE THREAD

**Issue by yinhui1129754** [youzan/vant#4245]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by yinhui1129754** [comment]
为什么自动生成的index.ts导入的组件首字母要大写啊 ？

**Comment by chenjiahan** [comment]
这是组件的命名规范，用首字母大写来表示这个是一个组件

**Comment by yinhui1129754** [comment]
好的 谢谢了
