### ISSUE TITLE
[Feature Request] Picker: support key-value pairs

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#4247]
Picker 选择器数据格式建议增加支持Object格式 keyvalue格式
具体可以参考下面截图的数据格式 如果是类似于多级联动的数据结构和一下一样的树形数据就行。
组件只需要默认获取value来做显示 然后用户在选择后将选择的对象数据一并返回（就是一下截图的value和code）

![image](https://user-images.githubusercontent.com/16772541/63743023-75b29700-c8cd-11e9-87f7-0a505bf4052e.png)

**Comment by Angle-bo** [comment]
只有一个数组，只能获取value和index，功能太少了，应该做成返回选中的对象。并且支持自定义keyvalue那种，像zTree那样就方便很多了。

**Comment by OnlyLady** [comment]
> 只有一个数组，只能获取value和index，功能太少了，应该做成返回选中的对象。并且支持自定义keyvalue那种，像zTree那样就方便很多了。

这个功能确实有点少,主要是现在很多业务数据都是采用的树形结构,这样就很不方便了 还要去拆成组件需要的数据结构才能使用

**Comment by NullYing** [comment]
原来用原生select的，极其需要kv形式的picker

**Comment by chenxi5211993** [comment]
这个8月opne到现在了，有没有什么可以使用的解决方法呀？

**Comment by NullYing** [comment]
> 这个8月opne到现在了，有没有什么可以使用的解决方法呀？

导入别的解决，我是导入了element的

**Comment by chenxi5211993** [comment]
> > 这个8月opne到现在了，有没有什么可以使用的解决方法呀？
> 
> 导入别的解决，我是导入了element的

麻烦问一下用的element的哪个组件？

**Comment by NullYing** [comment]
> element

select

**Comment by chenjiahan** [comment]
已在 2.4.5 版本支持

**Comment by emila-github** [comment]
已在 2.4.5 版本支持 这个文档中没有体现 具体怎么使用能提供一下说明吗 @ @chenxi5211993

**Comment by emila-github** [comment]
> 已在 2.4.5 版本支持

在文档中没找到key的使用示例和说明 求助
@chenjiahan

**Comment by chenjiahan** [comment]
https://youzan.github.io/vant/#/zh-CN/picker#ji-lian-xuan-ze

**Comment by emila-github** [comment]
> https://youzan.github.io/vant/#/zh-CN/picker#ji-lian-xuan-ze

级联选择 这块的文档我已经看了 为找到相关key字段的设置和返回

**Comment by chenjiahan** [comment]
这个 issue 说的就是级联选择，key 的设置目前只支持 value-key 属性

**Comment by emila-github** [comment]
> value-key

value-key 只能解决value到其他字段的映射关系， 我看大家都关心的是是否支持{id: xxx, text:'选项文本’}的这种格式， 选择返回 id 的问题。目前版本中是否已经支持了呢？

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5905
