### ISSUE TITLE
DropdownMenu 下拉菜单 建议增加按钮显示隐藏与触发自定义

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#4248]
DropdownMenu 下拉菜单 建议增加按钮显示隐藏与触发自定义

具体需求例如： 我这边不想通过组件自带的button按钮触发,同时不想让button按钮显示出来,
如果可以考虑的话 建议增加props自定义

**Comment by chenjiahan** [comment]
可以给个图看下具体的场景么

**Comment by OnlyLady** [comment]
> 可以给个图看下具体的场景么

具体图片我这边暂时不能给到您昂。但是有些业务需要就是这样子的呢。

**Comment by chenjiahan** [comment]
暂时不会支持这个需求

**Comment by annihilationism** [comment]
同样有这个需求
