### ISSUE TITLE
建议添加时间段选择插件

### ISSUE THREAD

**Issue by a948570206** [youzan/vant#4251]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持喔，可以考虑使用 DatetimePicker 或 Picker
