### ISSUE TITLE
[Bug Report]  Circle 环形进度条 stroke-width > 60 边界会出问题 

### ISSUE THREAD

**Issue by lifanlingjue** [youzan/vant#4254]
### 设备 / 浏览器
Chrome

### Vant 版本
2.1.7

### Vue版本
2.6.6

### 重现链接
<a href="http://使用该组件的页面.com" target="_blank">http://使用该组件的页面.com</a>

### 描述问题
当circle组件的stroke-width属性设置的值大于60的时候，边界会被削平。

**Comment by chenjiahan** [comment]
已在 2.1.8 版本修复

**Comment by lifanlingjue** [comment]
效率真高 NB
