### ISSUE TITLE
[Feature Request] 建议增加  '足迹' Footprint 图标

### ISSUE THREAD

**Issue by ydcode** [youzan/vant#4265]
### 这个功能解决了什么问题
历史访问记录的图标，感觉足迹(Footprint)标志相对于 眼睛标志(browsing-history-o)更直观具象一些。建议增加这个图标

### 描述您想要的解决方案
https://icons8.com/icon/814/foot
https://imgur.com/Fc1c0aC

### 建议的API是什么样的
https://imgur.com/Fc1c0aC

**Comment by chenjiahan** [comment]
暂无计划支持喔
