### ISSUE TITLE
upload 安卓机部分不兼容多选图片上传

### ISSUE THREAD

**Issue by xx929** [youzan/vant#4268]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

我发现这部分真的挺多的，华为，三星，小米主流机型基本都没有办法多张上传

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4103

**Comment by Rickykurt** [comment]
参见：https://www.caniuse.com/#search=multiple
![image](https://user-images.githubusercontent.com/1176984/64139133-7352be80-ce32-11e9-957f-9e9413543a78.png)
