### ISSUE TITLE
这里有一个非常疑惑的问题想请教下楼主

### ISSUE THREAD

**Issue by yinhui1129754** [youzan/vant#4269]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by yinhui1129754** [comment]
为什么你的样式布局不用rem+vw啦 为什么用px啦？ 因为我看好多开源的框架都是用的px那一套  很好奇 想请教下楼主

**Comment by yinhui1129754** [comment]
特别是当有需求要字体小于12px的时候 px就非常老火了 那个px转rem的方案也不当得行 因为只把字体转了 宽度高度那些没有和屏幕宽度挂钩 还是会看起比较怪异

**Comment by chenjiahan** [comment]
px 更通用，而且我们也提供了方案将 px 转换成 rem 或 vh，你说的『只转换字体』的问题应该是你的配置有误

**Comment by yinhui1129754** [comment]
嗯 好的 谢谢了 用px是为了适配非自动工程化开发的开发者吗

**Comment by chenjiahan** [comment]
嗯呐，px 是所有人都能用的，rem 则需要一定的工具去辅助
