### ISSUE TITLE
Picker组件column中text值传入html代码会执行

### ISSUE THREAD

**Issue by xycd1996** [youzan/vant#4270]
Picker组件column中text值传入html代码会执行，建议采用innerText进行文本插入防止XSS

**Comment by chenjiahan** [comment]
这个属于 breaking change 了，会在 3.0 版本里修改，默认使用 text，通过选项开启 html

**Comment by xycd1996** [comment]
因项目上线需要，我在2.x基础上直接PickerColumn.js中将
`
"domProps": {
          "innerHTML": _this2.getOptionText(option)
  }
`
修改为： 
`
"domProps": {
          "innerText": _this2.getOptionText(option)
  }
`
是否会造成其它不可预知的错误？

**Comment by chenjiahan** [comment]
理论上不会有问题

**Comment by xycd1996** [comment]
好的谢谢

**Comment by chenjiahan** [comment]
下个版本会加一个属性`allow-html`来控制是否允许 HTML 内容

**Comment by chenjiahan** [comment]
已在 2.1.8 版本支持
