### ISSUE TITLE
[Bug Report] treeSelect组件slot='content' 使用文档待补全

### ISSUE THREAD

**Issue by xiequanbin** [youzan/vant#4271]
### 设备 / 浏览器
any

### Vant 版本
2.1.7

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tree-select#slots" target="_blank">https://youzan.github.io/vant/#/zh-CN/tree-select#slots</a>

### 描述问题
TreeSelect 分类选择 slot='content' 后 该如何操作 slot

**Comment by chenjiahan** [comment]
文档已增加示例

**Comment by wumengzhuo** [comment]
按照文档操作  插槽内容无法展示

**Comment by chenjiahan** [comment]
@wumengzhuo 确认下你的 vant 版本是不是最新的

**Comment by wumengzhuo** [comment]
版本已经更新到最新




按照文档写法   也不报错  就是插槽不加载






------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 下午3:12
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "呵呵"<772696310@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [youzan/vant] [Bug Report] treeSelect组件slot='content' 使用文档待补全 (#4271)




@wumengzhuo 确认下你的 vant 版本是不是最新的

**Comment by chenjiahan** [comment]
可以给个复现的 codesandbox 链接看下

**Comment by wumengzhuo** [comment]
给了你个demo  刚才有点事  回复晚了  麻烦了




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 下午3:39
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "呵呵"<772696310@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] treeSelect组件slot='content' 使用文档待补全 (#4271)




可以给个复现的 codesandbox 链接看下

**Comment by chenjiahan** [comment]
demo 在哪，没看到耶

**Comment by wumengzhuo** [comment]
我刚才看了一下  就是直接写是可以的，但是我放到dropdown组件里做一个搜索下拉的树选择组件，就失效了，插槽没有加载







------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 下午3:58
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "呵呵"<772696310@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [youzan/vant] [Bug Report] treeSelect组件slot='content' 使用文档待补全 (#4271)




demo 在哪，没看到耶

**Comment by chenjiahan** [comment]
理论上不会出现这种情况，可以把 codesandbox 链接发我看下

**Comment by wumengzhuo** [comment]
https://jzuq2.csb.app/     
我重新写了个demo   第一张图可以了 第二张出不来




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 下午4:19
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "呵呵"<772696310@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [youzan/vant] [Bug Report] treeSelect组件slot='content' 使用文档待补全 (#4271)




理论上不会出现这种情况，可以把 codesandbox 链接发我看下

**Comment by chenjiahan** [comment]
@wumengzhuo HTML 里不支持写自闭合的自定义组件的，`<van-image />` 要写成 `<van-image></van-image>`

**Comment by wumengzhuo** [comment]
感谢感谢，问题已解决



------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 下午4:53
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "呵呵"<772696310@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [youzan/vant] [Bug Report] treeSelect组件slot='content' 使用文档待补全 (#4271)




@wumengzhuo HTML 里不支持写自闭合的自定义组件的，<van-image /> 要写成 <van-image></van-image>
