### ISSUE TITLE
van-tab 建议支持tab左右拖动

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#4274]
建议给tab增加左右拖动功能 并且允许用户是否启用左右滑动

具体左右拖动效果 请看
https://www.ctolib.com/ScoutYin-ly-tab.html

**Comment by chenjiahan** [comment]
顶部栏目前是支持左右拖动的，Tab 内容目前不支持，在这个 issue 里跟进https://github.com/youzan/vant/issues/1174
