### ISSUE TITLE
[Feature Request] 定制主题能否通过modifyVars中import less变量文件来覆盖

### ISSUE THREAD

**Issue by luffyli** [youzan/vant#4275]
### 这个功能解决了什么问题
解决了只能通过js对象来修改less变量的方式

### 描述您想要的解决方案
可以@import less变量文件覆盖原有变量

### 建议的API是什么样的
可参考 Ant Design 的做法

![image](https://user-images.githubusercontent.com/10166950/63848397-56496600-c9c2-11e9-81c1-97e6ec902b78.png)

**Comment by chenjiahan** [comment]
这种方式目前也是支持的喔，后续会在文档里标注下

**Comment by chenjiahan** [comment]
文档已更新
