### ISSUE TITLE
[Feature Request] treeSelect 扩展多级联动

### ISSUE THREAD

**Issue by peiili** [youzan/vant#4276]
### 这个功能解决了什么问题
使用treeSelect实现省市区三级联动

### 描述您想要的解决方案
使用treeSelect实现多级联动

### 建议的API是什么样的
const items = [
  {
    // 导航名称
    text: '广东省',
    // 该导航下所有的可选项
    children: [
      {
        // 名称
        text: '深圳市',
        // id，作为匹配选中状态的标识
        id: 1,
        children:[
         {
         id:1
          text:'南山区'
          }
       ]
      },
      {
        text: '东莞市',
        id: 2
      }
    ]
  }
]

**Comment by chenjiahan** [comment]
暂无计划支持喔

**Comment by Crash456** [comment]
现在支持吗
