### ISSUE TITLE
navbar组件，click-left事件不应该在我使用了left slot时还执行

### ISSUE THREAD

**Issue by anrananran** [youzan/vant#4280]
由于navbar组件到处都在用，且都需要返回事件，所以我自己再次包装成了navigation组件，这个组件上写上了click-left事件
![image](https://user-images.githubusercontent.com/12759613/63921780-02985480-ca76-11e9-9727-19f5dbfec32b.png)

然后在使用navigation时，left slot上绑定了其他事件，结果：两个事件都执行了

**Comment by chenjiahan** [comment]
这个是合理的，如果你不想触发，可以在 slot 内阻止事件冒泡

**Comment by anrananran** [comment]
OK
