### ISSUE TITLE
[Bug Report] SwipeCell 使用rem转px 之后  样式问题

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#4281]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.7

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/m5v3f" target="_blank">https://codesandbox.io/s/m5v3f</a>

### 描述问题
使用rem转px之后 滑动单元格 会有缝隙~~
![20190829150041](https://user-images.githubusercontent.com/42430384/63922225-db8e5280-ca76-11e9-8725-aa9caf692ef9.png)
![20190829150147](https://user-images.githubusercontent.com/42430384/63922234-df21d980-ca76-11e9-880a-01395251ee49.png)
![20190829150943](https://user-images.githubusercontent.com/42430384/63922240-e21cca00-ca76-11e9-87d6-df5301ddfd41.png)

**Comment by anihCevol** [comment]
使用rem转换px 之后的样式问题，咋整

**Comment by chenjiahan** [comment]
复现链接里没内容，麻烦更新下

**Comment by alisaWXtang** [comment]
同问
