### ISSUE TITLE
自定义主题的@dialog-confirm-button-text-color未生效

### ISSUE THREAD

**Issue by JacobMa1996** [youzan/vant#4285]
自定义主题，配置less变量，其他颜色都生效了，@dialog-confirm-button-text-color未能修改掉dialog的确认按钮的颜色，修改后，仅在:active时生效

![image](https://user-images.githubusercontent.com/13243784/63937403-e821a380-ca94-11e9-84f7-4320af6a5868.png)

![Uploading image.png…]()

**Comment by chenjiahan** [comment]
是否使用了 confirmButtonColor 属性？

**Comment by JacobMa1996** [comment]
> 是否使用了 confirmButtonColor 属性？

没有使用，这个颜色在组件中未生效，暂时先用confirmButtonColor属性解决了这个问题

**Comment by chenjiahan** [comment]
我试了下没问题，建议你看下是不是其他原因导致的
