### ISSUE TITLE
[Bug Report] Rate 组件无法设置到0星

### ISSUE THREAD

**Issue by xieyuh** [youzan/vant#4288]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.7

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/rate" target="_blank">https://youzan.github.io/vant/#/zh-CN/rate</a>

### 描述问题
Rate组件通过滑动最少只能设置到1星或半星，而无法设置到0星，官网示例即可复现

**Comment by chenjiahan** [comment]
这个不是 bug，本身就是这样的逻辑
