### ISSUE TITLE
[Bug Report] NumberKeyboard: 新增 focused 属性 无使用文档

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#4290]
NumberKeyboard: 新增 focused 属性 #4279 无使用文档
![image](https://user-images.githubusercontent.com/21211777/63988445-e85e8500-cb0e-11e9-935a-0b244f28bc57.png)

**Comment by chenjiahan** [comment]
抱歉上面的组件名打错了，是 PasswordInput 新增了 focused 属性，一会儿更正下文档

**Comment by Thlq** [comment]
NumberKeyboard双向绑定的能加吗
![image](https://user-images.githubusercontent.com/21211777/63988794-79822b80-cb10-11e9-8a59-4926fa7bc06c.png)
类似于这种

**Comment by chenjiahan** [comment]
原生输入框的光标，我们无法控制哈。

如果是 div 模拟的输入框，就属于一个独立的组件了，现阶段我们没有计划提供

**Comment by Thlq** [comment]
好的，谢谢
