### ISSUE TITLE
vant-toast-引用set报错

### ISSUE THREAD

**Issue by 651619994xhq** [youzan/vant#4295]
toast.set 修改为setData 这么明显的错误 竟然发生了 不可思议

**Comment by 651619994xhq** [comment]
toast.js
function Toast(toastOptions) {
    const options = Object.assign({}, currentOptions, parseOptions(toastOptions));
    const context = options.context || getContext();
    const toast = context.selectComponent(options.selector);
    if (!toast) {
        console.warn('未找到 van-toast 节点，请确认 selector 及 context 是否正确');
        return;
    }
    delete options.context;
    delete options.selector;
    toast.clear = () => {
        toast.setData({ show: false });
        if (options.onClose) {
            options.onClose();
        }
    };
    queue.push(toast);
    toast.setData(options);
    clearTimeout(toast.timer);
    if (options.duration > 0) {
        toast.timer = setTimeout(() => {
            toast.clear();
            queue = queue.filter(item => item !== toast);
        }, options.duration);
    }
    return toast;
}


set  替换成 setData

**Comment by chenjiahan** [comment]
1. 这里是 vue 版的仓库，不是小程序仓库
2. set 是 vant-weapp 内部定义的方法，没认真看过源码别瞎提问题
