### ISSUE TITLE
[Bug Report] numberkeyboard iphone xr 错位

### ISSUE THREAD

**Issue by Liupeng8** [youzan/vant#4298]
### 设备 / 浏览器
iphone/微信内置浏览器、支付宝内置浏览器

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-nte8j" target="_blank">https://codesandbox.io/s/vant-issue-moban-nte8j</a>

### 描述问题
真机测试错位，复现地址看不出，微信开发者工具XR调试没问题。
![微信图片_20190830133349](https://user-images.githubusercontent.com/23046680/63995936-c247dd80-cb2c-11e9-94ac-875a37e6284a.png)

**Comment by Liupeng8** [comment]
已测试过，vant 2.1.5 正常，2.1.6-2.1.8均错位了

**Comment by Liupeng8** [comment]
但是2.1.5加了title，右侧按钮会往上顶。辛苦老大解决一下

**Comment by chenjiahan** [comment]
下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 2.2.0 版本修复
