### ISSUE TITLE
ImagePreview使用组件调用放大后切换图片图片都默认放大

### ISSUE THREAD

**Issue by jswy** [youzan/vant#4301]
看来官网的更新说明在V2.10版本说修复 ImagePreview onClose 和 onChange 选项未被重置的问题，确实是的，但是是在非组件调用的情况下，使用组件调用调用时通过v-model="show"来控制图片的显示，当一张图片放大时，切换到另一张图片也是放大状态，关闭后，重新打开也是之前的放大状态，希望能解决下这个问题，好长一段时间都在用vant进行开发，希望vant越来越好，最后补充下，我用的是2.18刚升级的最新版

**Comment by jswy** [comment]
开启了异步关闭（:async-close="true"）,通过v-model="show"来控制图片的显示，才会出现上面所说的问题

**Comment by chenjiahan** [comment]
能否给个复现的 codesandbox 链接哇？ 描述的流程有点没看懂

**Comment by jswy** [comment]
主要代码如下
<van-image-preview
                        v-model="imagePreview"
                        :images="images"
                        :show-index="false"
                        :async-close="true"
                        :close-on-popstate="true"
                        :maxZoom="imgMaxZoom"
                        :minZoom="imgMaxZoom"
                        :className="zoomClass"
                >
                </van-image-preview>
功能描述：我有三张图片，每个图片都有一个放大按钮，然后通过上面van-image-preview组件调用代码放大预览，只不过是每次改变images的内容，所以当对一个图片双击放大后，在关闭（通过操作 v-model="imagePreview"手动关闭的），在预览第二张图片时，第二张图片也会以放大的状态进行展示

**Comment by jswy** [comment]
<van-image-preview
                        v-model="imagePreview"
                        :images="images"
                        :show-index="false"
                        :async-close="true"
                        :close-on-popstate="true"
                        :maxZoom="imgMaxZoom"
                        :minZoom="imgMaxZoom"
                        :className="zoomClass"
                >
                </van-image-preview>

**Comment by jswy** [comment]
<van-image-preview
                        v-model="imagePreview"
                        :images="images"
                        :show-index="false"
                        :async-close="true"
                        :close-on-popstate="true"
                        :maxZoom="imgMaxZoom"
                        :minZoom="imgMaxZoom"
                        :className="zoomClass"
                >
                </van-image-preview>

**Comment by jswy** [comment]
主要代码

**Comment by jswy** [comment]
（<van-image-preview
                        v-model="imagePreview"
                        :images="images"
                        :show-index="false"
                        :async-close="true"
                        :close-on-popstate="true"
                        :maxZoom="imgMaxZoom"
                        :minZoom="imgMaxZoom"
                        :className="zoomClass"
                >
                </van-image-preview>）

**Comment by jswy** [comment]
<van-image-preview>
   v-model="imagePreview"
    :images="images"
    :show-index="false"
    :async-close="true"
    :close-on-popstate="true"
    :maxZoom="imgMaxZoom"
    :minZoom="imgMaxZoom"
    :className="zoomClass"
</van-image-preview>

**Comment by jswy** [comment]
&lt;van-image-preview
                v-model="imagePreview"
                :images="images"
                :show-index="false"
                :async-close="true"
                :close-on-popstate="true"
                :maxZoom="imgMaxZoom"
                :minZoom="imgMaxZoom"
                :className="zoomClass"
                &gt;
                &lt;/van-image-preview &gt;

**Comment by chenjiahan** [comment]
明白了，下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 2.2.0 版本修复
