### ISSUE TITLE
swipe 建议

### ISSUE THREAD

**Issue by bigmgreen** [youzan/vant#4305]
能不能在给终端横屏竖屏切换时也给刷新下滚动项的宽高

**Comment by chenjiahan** [comment]
目前是监听了 resize 事件的，理论上横竖屏切换的时候也会触发 resize

你是在什么终端上出现未刷新的现象？

**Comment by Orow** [comment]
在iPhone上用描述檔包出來的檔案，直頻轉橫頻時，橫頻時兩個swipe-item在同一畫面，再轉回直頻內容變成只有原本swipe-item一半
一般的 iOS Safari 開啟網址則不會有這個問提

**Comment by lishaoxin123** [comment]
假设我是h5模拟的翻转那就没有效果了，所以希望可以出一个触发改变的函数
