### ISSUE TITLE
[Bug Report] vant路由后退高亮无法同步改变问题

### ISSUE THREAD

**Issue by YuuhangXie** [youzan/vant#4310]
### 设备 / 浏览器
Chrome 最新版本   Mac/Win

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://github.com/lurongtao/gp12-vue.js-maoyan" target="_blank">https://github.com/lurongtao/gp12-vue.js-maoyan</a>

### 描述问题
vant路由后退高亮无法同步改变问题，点击nav根据hash跳转到相应路由，并且active也会高亮显示，但是点击后退active却还停留在上一页面的hash路由的元素上。

**Comment by chenjiahan** [comment]
试了下没问题呀，你是怎么复现的
