### ISSUE TITLE
[Bug Report] ts下使用Dialog组件 确认按钮和取消按钮都显示undefined,传入confirmButtonText自定义也不行

### ISSUE THREAD

**Issue by answer33** [youzan/vant#4311]
### 设备 / 浏览器
所有

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 描述问题
ts下使用Dialog组件 确认按钮和取消按钮都显示undefined,传入confirmButtonText自定义也不行

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接
