### ISSUE TITLE
[Bug Report] image组件，onLoad和onError命名冲突

### ISSUE THREAD

**Issue by dingangang** [youzan/vant#4314]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="http://www.zanwu.com" target="_blank">http://www.zanwu.com</a>

### 描述问题
uni-app开发时，使用upload组件时，图片加载会有问题。
排查后发现是onLoad方法与onError方法与uni-app的命名起了冲突。
可否在组件中将这两个方法换个名称？

**Comment by dingangang** [comment]
我尝试在image中修改了onLoad和onError名称，组件就正常了。

**Comment by chenjiahan** [comment]
暂时没有计划修改，这个应该属于框架的 bug

**Comment by 1414044032** [comment]
@dingangang @chenjiahan ，我也是遇到这个问题。然后把 npm 下载的vant的包里面的onload 以及onerror 都修改了，就恢复正常了。同时我注意到 vant下有两个文件夹，一个是es  一个是lib 。我修改的es 里面的image，发现恢复正常了，不知道lib 文件夹 是干什么用的？？一直很迷惑

**Comment by chenjiahan** [comment]
es 导出的是 esmodule，lib 导出的是 commonjs 模块
