### ISSUE TITLE
tabbar底部导航，每个tab的文字能不能设置方向啊，文字需要在右边，图标左边

### ISSUE THREAD

**Issue by mualala** [youzan/vant#4316]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持，可以自行覆盖样式，比如`flex-direction: row;`
