### ISSUE TITLE
希望新增一个日历Calendar 组件

### ISSUE THREAD

**Issue by q759410559** [youzan/vant#4317]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

希望新增一个日历Calendar 组件，支持日期事件提示等等。

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持
