### ISSUE TITLE
[Bug Report] Uploader在安卓机不能能多选

### ISSUE THREAD

**Issue by zyHot** [youzan/vant#4318]
### 设备 / 浏览器
微信内置浏览器、UC浏览器

### Vant 版本
2.1.8

### Vue版本
2.5.22

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
在安卓机微信内置浏览器和uc浏览器都不能多选图片

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/1721

**Comment by Rickykurt** [comment]
参见：https://www.caniuse.com/#search=multiple
![image](https://user-images.githubusercontent.com/1176984/64139133-7352be80-ce32-11e9-957f-9e9413543a78.png)
