### ISSUE TITLE
引入divider报错，其它组件正常使用

### ISSUE THREAD

**Issue by Lkkpower** [youzan/vant#4322]
![image](https://user-images.githubusercontent.com/24646979/64098287-13f4a000-cd99-11e9-89d2-87620146c918.png)
![image](https://user-images.githubusercontent.com/24646979/64098354-3ab2d680-cd99-11e9-9c57-1ec6ebdd6dc0.png)
![image](https://user-images.githubusercontent.com/24646979/64098543-b90f7880-cd99-11e9-8f5c-89a5d510993b.png)

**Comment by chenjiahan** [comment]
请确认你的 vant 版本中是否包含了 Divider 组件，参考 https://github.com/youzan/vant/issues/3901

**Comment by Lkkpower** [comment]
> 请确认你的vant版本中是否包含了Divider组件，参考[＃3901](https://github.com/youzan/vant/issues/3901)

嗯，是版本问题，如何升级到最新版呢？

**Comment by chenjiahan** [comment]
npm i vant@2.1.8 -S
