### ISSUE TITLE
[Bug Report] DropdownMenu 下拉菜单

### ISSUE THREAD

**Issue by yanglei00** [youzan/vant#4329]
### 设备 / 浏览器
iOS12

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/dropdown-menu" target="_blank">https://youzan.github.io/vant/#/zh-CN/dropdown-menu</a>

### 描述问题
下拉菜单选项的选中态颜色不能自定义，active-color 只能设置菜单标题的颜色

**Comment by chenjiahan** [comment]
active-color 也可以作用于菜单选项的，不过当前版本的默认颜色有点问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.2.0 版本修复
