### ISSUE TITLE
slider value的默认值 应该为最小值 

### ISSUE THREAD

**Issue by realbasin** [youzan/vant#4335]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://www.baidu.com" target="_blank">https://www.baidu.com</a>

### 描述问题
v-model 绑定的值 为null时候，因为还没设置。默认值 应该为设置的最小值或者 0 ， 我设置了一个最小值为1的滑块，  value默认为0， 初始化时候滑块直接铺满了整条。

**Comment by chenjiahan** [comment]
下个版本会优化

**Comment by chenjiahan** [comment]
已在 2.2.0 版本修复
