### ISSUE TITLE
swipe建议

### ISSUE THREAD

**Issue by lololsiyuan** [youzan/vant#4339]
在使用swipe自定义宽度时，我需要item之间有10px的距离，我用css添加之后发现最后一个滑块不在一行了，因为容器的宽度是滑块的宽度相加，是不是应该添加一个属性来表示这个宽度呢？

![image](https://user-images.githubusercontent.com/8640364/64149836-9b094d00-ce59-11e9-9077-e3b778846b48.png)

![image](https://user-images.githubusercontent.com/8640364/64149813-8d53c780-ce59-11e9-8645-7ca041882b18.png)

**Comment by lololsiyuan** [comment]
我试着用swipe-item的padding去做，每个滑块设置padding-left:10px;但是无法满足最右边的10px，如果用last-child，那么最后一个滑块内容宽度就比前几个少10px

**Comment by landejin2016** [comment]
我也要提建议：1、可不可以添加个属性，控制指示器在itm里面或者外面，2、可不可以提供指示器没有选中时的颜色设置。

**Comment by chenjiahan** [comment]
暂时没有计划添加属性来支持这个特性，建议自行尝试用 css 实现，或者使用社区的轮播组件

@landejin2016 你的需求可以直接通过覆盖样式解决
