### ISSUE TITLE
uploader没有反应

### ISSUE THREAD

**Issue by hqqxxf** [youzan/vant#434]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@hqqxxf 能否具体描述下出现问题的场景？
