### ISSUE TITLE
[Bug Report] locale英文文档单词拼写错误

### ISSUE THREAD

**Issue by a298003154** [youzan/vant#4341]
### 设备 / 浏览器
无

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://github.com/youzan/vant/tree/dev/src/locale#switch-languages" target="_blank">https://github.com/youzan/vant/tree/dev/src/locale#switch-languages</a>

### 描述问题
段落“method allows you to switch to diffrent languages.” 里面 “diffrent”拼写错误了

![image](https://user-images.githubusercontent.com/24939100/64152220-bf1b5d00-ce5e-11e9-81c3-1f7f7c7d810f.png)

**Comment by chenjiahan** [comment]
可以帮忙提个 PR 修复一下喔
