### ISSUE TITLE
复选框组的状态问题

### ISSUE THREAD

**Issue by wumengzhuo** [youzan/vant#4344]
复选框组件的选中状态为false,未选中为true

**Comment by wumengzhuo** [comment]
默认给上true或者false没有问题，比如说默认给true, 是选中状态， 点击之后变成不选中，但是状态值依然是true，再次点击变成选中，状态变成false, 是不是取反规则不对

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
