### ISSUE TITLE
Field组件设置字体大小，placeholder属性iPhone7上文字不能上下居中

### ISSUE THREAD

**Issue by qwerlp** [youzan/vant#4345]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

![image](https://user-images.githubusercontent.com/42144393/64157056-98622400-ce68-11e9-8ec5-e85b204de12e.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
