### ISSUE TITLE
van-picker无法实现城市三级联动？

### ISSUE THREAD

**Issue by kgm1818** [youzan/vant#4346]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以实现的，参考示例或 Area 组件。

另外请按照模板创建 issue，感谢配合
