### ISSUE TITLE
[Bug Report] Dialog异步确认后，关闭后重新显示Dialog，确认按钮依然在转圈

### ISSUE THREAD

**Issue by Musiker1114** [youzan/vant#4348]
### 设备 / 浏览器
浏览器/移动端

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/embed/vue-template-mpuu9?fontsize=14" target="_blank">https://codesandbox.io/embed/vue-template-mpuu9?fontsize=14</a>

### 描述问题
DIalog显示显示后，异步关闭如果时间较长，确认按钮会显示loading，这个时候点击取消按钮并done()，然后重新显示Dialog，确认按钮依然处于loading状态

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.2.0 版本修复
