### ISSUE TITLE
[Bug Report] 复选框的选中状态问题

### ISSUE THREAD

**Issue by wumengzhuo** [youzan/vant#4349]
### 设备 / 浏览器
谷歌

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/checkbox" target="_blank">https://youzan.github.io/vant/#/zh-CN/checkbox</a>

### 描述问题
复选框的绑定值有问题，比如说一开始设置true, 是选中的，点击以后 成了不选中，但是绑定值还是true，   再次点击又选中， 但是绑定值成了false
复选框组也是，选中了不往绑定数组里添加，不选中往数组里添加一个

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by wumengzhuo** [comment]
https://dgj1x.csb.app/    这是复选框和复选框组都在这里，点击以后不选中绑定至为true,    选中为false




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年9月3日(星期二) 晚上9:01
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "呵呵"<772696310@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] [Bug Report] 复选框的选中状态问题 (#4349)




麻烦提供一下 codesandbox 复现链接

**Comment by chenjiahan** [comment]
toggle 是一个异步的操作，所以你在 toggle 之后立刻去获取 result，得到的是未改变的值，使用 setTimeout 可以解决这个问题

```js
this.$refs.checkboxes[index].toggle();
setTimeout(() => {
  console.log(this.result)
}, 0)
```

更好的方式是在 change 事件或通过 watch 去监听 result 的改变
