### ISSUE TITLE
[Feature Request] tabs点击事件返回数据 建议返回整个对象

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#4351]
tabs目前的点击事件只是返回了固定值？个人建议是直接返回当前点击的所有数据对象。这样可以方便然后用户决定需要取什么

**Comment by chenjiahan** [comment]
暂时没有计划调整目前的参数结构，如果添加第三个参数，显得太过冗余，调整现有参数则会造成不兼容更新。

你可以通过 name 或 index 去取到对应的数据对象

**Comment by boxshadow** [comment]
<img width="591" alt="WX20191027-002513@2x" src="https://user-images.githubusercontent.com/8577474/67622791-7c6b7500-f850-11e9-94f5-86d545dbe96e.png">
name 没有， index 没有， 截图就是绑定的方法的第一个参数的值
