### ISSUE TITLE
ImagePreview 打包真机预览图片显示不出来

### ISSUE THREAD

**Issue by qadcyygg** [youzan/vant#4355]
ImagePreview 打包后在真机预览图片，图片路径有问题，没有显示出来，图片传入方式是这样的
data() {
    return {
      show: false,
      index: 0,
      images: [
        'https://img.yzcdn.cn/1.jpg',
        'https://img.yzcdn.cn/2.jpg'
      ]
    };
  },
请问如何解决！！

**Comment by chenjiahan** [comment]
https://img.yzcdn.cn/1.jpg 不是真实的图片地址，是无法打开的

**Comment by qadcyygg** [comment]
图片是真实存在的地址，只是为了描述问题复制官网的代码，打包后在电脑上运行图片能够显示出来，但是真机上图片显示就有问题，请问这是什么原因

**Comment by qadcyygg** [comment]
> https://img.yzcdn.cn/1.jpg 不是真实的图片地址，是无法打开的
图片是真实存在的地址，只是为了描述问题复制官网的代码，打包后在电脑上运行图片能够显示出来，但是真机上图片显示就有问题，请问这是什么原因

**Comment by chenjiahan** [comment]
可以检查下是不是网络问题，或者提供复现的 codesandbox 链接看下

**Comment by qadcyygg** [comment]
> 可以检查下是不是网络或图片格式的问题，或者提供复现的 codesandbox 链接看下

这是打包后线上的地址 https://qadcyy.gitee.io/preview/#/community，这个页面图片预览在电脑上能正常显示，到手机上访问图片就显示不出来，请问有遇到过这个情况吗

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/64307101-a2e6ff80-cfc7-11e9-8504-052a1cb49fe7.png)
在电脑上也da'k打不开，你的图片链接应该有问题

**Comment by qadcyygg** [comment]
> ![image](https://user-images.githubusercontent.com/7237365/64307101-a2e6ff80-cfc7-11e9-8504-052a1cb49fe7.png)
> 在电脑上也打不开，你的图片链接应该有问题
这个地方目前没有加图片，现在只是占位，图片预览有加入真实的图片地址，需要点击这个地方
![image](https://user-images.githubusercontent.com/16434163/64307399-8e573700-cfc8-11e9-94de-886bb5af5370.png)

**Comment by chenjiahan** [comment]
一样打不开，403

**Comment by qadcyygg** [comment]
> > ![image](https://user-images.githubusercontent.com/7237365/64307101-a2e6ff80-cfc7-11e9-8504-052a1cb49fe7.png)
> > 在电脑上也打不开，你的图片链接应该有问题
> > 这个地方目前没有加图片，现在只是占位，图片预览有加入真实的图片地址，需要点击这个地方
> > ![image](https://user-images.githubusercontent.com/16434163/64307399-8e573700-cfc8-11e9-94de-886bb5af5370.png)

isShowPreview: false,
        previewIndex: 0,
        previewImgs: [
          'https://p1.ssl.qhimgs1.com/sdr/400__/t0192774d2e69db0521.jpg',
          'https://p0.ssl.qhimgs1.com/sdr/400__/t01d8a105fa304031e4.jpg'
        ] 这是实际的代码，图片链接是没有问题的

**Comment by chenjiahan** [comment]
是你的图片的问题，你可以换成 https://img.yzcdn.cn/vant/cat.jpeg 试下，应该是正常的

**Comment by qadcyygg** [comment]
> 一样打不开，403

是我电脑缓存的问题，但是图片路径是有的，为什么显示不出来呢
![image](https://user-images.githubusercontent.com/16434163/64307698-792ed800-cfc9-11e9-914d-b4a1fd150250.png)

**Comment by qadcyygg** [comment]
> https://img.yzcdn.cn/vant/cat.jpeg

的确是我图片的问题，十分感谢您的解答
