### ISSUE TITLE
[Bug Report] tabar 数组遍历

### ISSUE THREAD

**Issue by jiahui336** [youzan/vant#4358]
### 设备 / 浏览器
公众号 

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="http://192.168.1.63" target="_blank">http://192.168.1.63</a>

### 描述问题
我用tabar 用数组遍历 tabar的内容 然后首次进入页面 默认的active不显示

**Comment by chenjiahan** [comment]
重现链接打不开，麻烦提供 codesandbox 复现链接
