### ISSUE TITLE
circle进度条传color渐变提示期待String

### ISSUE THREAD

**Issue by whoopsHzh** [youzan/vant#4359]
![image](https://user-images.githubusercontent.com/32846446/64236445-02440180-cf2d-11e9-8e7f-717f4ef26f59.png)
![image](https://user-images.githubusercontent.com/32846446/64236453-0708b580-cf2d-11e9-8276-89567d77dd7b.png)
上面的例子是官网直接拿的，在控制台的报错在下方。觉得很奇怪。。

![image](https://user-images.githubusercontent.com/32846446/64236356-cf017280-cf2c-11e9-8888-336debf50d83.png)

**Comment by chenjiahan** [comment]
应该是版本问题，建议升级版本试下
