### ISSUE TITLE
[Feature Request] Tab 标签页组件中Tabs 的offset-top属性  可以支持百分比传入吗

### ISSUE THREAD

**Issue by ydcode** [youzan/vant#4369]
### 这个功能解决了什么问题
Tab 标签页组件，Tabs 的offset-top属性  
目前支持粘性定位布局下与顶部的最小距离，单位 px	number

有些情形计算布局，需要根据百分比进行sticky, 可以支持百分比传入吗

### 描述您想要的解决方案
例如： :offset-top="'30%'"
类似 Field 输入框组件的label-width属性  同时支持多种类型输入 string | number

### 建议的API是什么样的
类似 Field 输入框组件的label-width属性  同时支持多种类型输入 string | number

**Comment by chenjiahan** [comment]
无法支持喔，你可以换算成 px 传入
