### ISSUE TITLE
uploader上传图片在android端有bug

### ISSUE THREAD

**Issue by hbynlsl** [youzan/vant#4370]
uploader组件在 ios 端微信窗口中没有问题；在android端微信窗口，点击时，显示的是  最近的图片，选择图片不会显示图片也没有上传；只有选择文件列表中的“相册”才能上传图片。请问应该怎么设置默认在android端显示相册呢？

**Comment by chenjiahan** [comment]
无法上传的问题可以参考 https://github.com/youzan/vant/issues/4103

现在应该没有办法默认只显示相册
