### ISSUE TITLE
可以描述的清楚一点么，取不到是指 after-read 没有触发，还是触发了但是没有回调参数

### ISSUE THREAD

**Issue by hetchzhao** [youzan/vant#4371]
可以描述的清楚一点么，取不到是指 after-read 没有触发，还是触发了但是没有回调参数

_Originally posted by @chenjiahan in https://github.com/youzan/vant/issues/4103#issuecomment-520659323_

在android微信的内置浏览器上运行时，没有触发after-read回调函数

**Comment by chenjiahan** [comment]
4103 这个 issue 里已经有解释了
