### ISSUE TITLE
[Bug Report] 调用日期控件，导致页面异常刷新

### ISSUE THREAD

**Issue by Mr-xue** [youzan/vant#4374]
### 设备 / 浏览器
IphoneX

### Vant 版本
2.1.8

### Vue版本
2.5.22

### 重现链接
<a href="https://暂无链接.com" target="_blank">https://暂无链接.com</a>

### 描述问题
调用项目中有时调用日期组件，在微信浏览器和safari中都会刷新页面。录了一段bug视频，前半段是正常的，后半段是点击倒计时刷新页面的错误重现。
链接: https://pan.baidu.com/s/1WL9UTJviCsNrm4wjir2xLA 提取码: bqsa

**Comment by chenjiahan** [comment]
这个问题比较难定位，建议自行排查下，是否有死循环之类的逻辑
