### ISSUE TITLE
[Feature Request] Add Custom Close Button on Image Uploader Preview

### ISSUE THREAD

**Issue by parkmap** [youzan/vant#4375]
### What problem does this feature solve
Add Custom UX

### Describe the solution you'd like
Add Custom Close Button or @Action for close Preview

### What does the proposed API look like
@closePreview=""
:closeIcon=""

**Comment by chenjiahan** [comment]
There is currently no close icon in the ImagePreview component，so we have no plans to provide the `close-icon` prop.

The `close-preview` event will be added in next version.

**Comment by chenjiahan** [comment]
The `close-preview` has been added in v2.2.0
