### ISSUE TITLE
[Bug Report] 环形进度条默认值设置为100

### ISSUE THREAD

**Issue by BingKui** [youzan/vant#4377]
### 设备 / 浏览器
所有设备

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-memyj" target="_blank">https://codesandbox.io/s/vant-issue-moban-memyj</a>

### 描述问题

环形进度条在设置默认值为0 speed为100 rate 为100的时候，v-module的值会被强制设置为100

**Comment by BingKui** [comment]
代码地址：https://codesandbox.io/s/vant-issue-moban-mk4uf

**Comment by chenjiahan** [comment]
这个是符合预期的，rate 属性表示进度条的目标进度，v-model 会以 speed 的速度变化，直至达到 rate设定的值。
