### ISSUE TITLE
[Bug Report] Search 搜索 组件在Mac safari上 input 有边框，且位置偏了

### ISSUE THREAD

**Issue by varjay** [youzan/vant#4379]
### 设备 / 浏览器
macbook pro13/safari 12.1.2 (14607.3.9)

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/search" target="_blank">https://youzan.github.io/vant/#/zh-CN/search</a>

### 描述问题
官方的页面就可以100%重现，麻烦修正一下！

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.2.0 版本修复
