### ISSUE TITLE
引入图片懒加载组件时报错

### ISSUE THREAD

**Issue by 2017lhy** [youzan/vant#438]
引入Lazyload 组件时报错，具体如下：
引入方式：
import Vue from 'vue';
import { Lazyload } from 'vant';
Vue.component(Lazyload.name, Lazyload)  //这里不写就会出现 “options is not defined”的错误
Vue.use(Lazyload, options); //这里写不写都会报下面的错误
错误：
Cannot read property 'toLowerCase' of undefined

![image](https://user-images.githubusercontent.com/34560558/34024561-cae7f87c-e185-11e7-9ef3-861b5ae762a0.png)

**Comment by cookfront** [comment]
`Lazyload`不是一个组件，是一个`plugin`，不能使用`Vue.component`，去掉你代码中的这行。然后`options`没定义肯定会报错了。
