### ISSUE TITLE
[Bug Report] 请问文档网站右侧的Demo有开源么

### ISSUE THREAD

**Issue by arrayListTwo** [youzan/vant#4381]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/intro" target="_blank">https://youzan.github.io/vant/#/zh-CN/intro</a>

### 描述问题

咨询一个问题：
请问文档网站右侧的Demo有代码开源么？右侧：
https://upload.cc/i1/2019/09/05/eVaKXl.jpg

有开源的话，开源代码在哪里可以找到？

**Comment by chenjiahan** [comment]
有的，代码在这个目录下

https://github.com/youzan/vant/tree/dev/docs/site

**Comment by arrayListTwo** [comment]
谢谢  一直没有留意到  谢谢
