### ISSUE TITLE
楼主请教个问题 

### ISSUE THREAD

**Issue by yinhui1129754** [youzan/vant#4385]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by yinhui1129754** [comment]
那个从底部往上滑动的组件的动画楼主知道怎么做的吗?
我看了 vant的效果比较卡(跳帧) 但是有一个vux的ui库非常的流畅
但是我看了原理都是用的transform translate3d 然后放vue的transition上面进行过度出现就可以了 
但是我不知道为什么 vant比较卡 vux非常的流畅


手机是一个老年机了 安卓版本的6.0
手机浏览器是qq自带的浏览器
qq版本是v6.3.7.2795
vant是用的官方文档里面的地址选择的哪一个下滑出现的
vux是所有的下滑出现都非常流畅

**Comment by yinhui1129754** [comment]
vux和vant的从底部往中间滚动的那个都是在同一环境测试的
![image](https://user-images.githubusercontent.com/19921594/64401109-e4e47400-d0a1-11e9-9e05-30864fac3470.png)
就是这一个选择的出场动画

**Comment by chenjiahan** [comment]
能否帮忙加上 transition-property 测试一下

```css
    -webkit-transition-property: -webkit-transform;
    transition-property: -webkit-transform;
    transition-property: transform;
    transition-property: transform, -webkit-transform;
```

**Comment by yinhui1129754** [comment]
好的

**Comment by yinhui1129754** [comment]
![image](https://user-images.githubusercontent.com/19921594/64417517-cdba7c00-d0cb-11e9-82cf-7edaaafbb9d1.png)
还是一样的

**Comment by yinhui1129754** [comment]
就是那种一跳一跳的感觉

**Comment by chenjiahan** [comment]
可以把 lazy-render 属性关掉试一下

还有上面的截图你修改的是 less 文件，你是直接引入 less 文件进行编译的吗

**Comment by yinhui1129754** [comment]
就是直接修改的源码呀 好的我试试

**Comment by chenjiahan** [comment]
源码你应该修改 css 文件

**Comment by yinhui1129754** [comment]
emmm 我是下载的git源码 运行看的效果

**Comment by yinhui1129754** [comment]
我自己在看一看 我感觉像我眼睛看疲劳了一样 我先关了

**Comment by yinhui1129754** [comment]
我找到动画不流畅的问题了 是过度函数的问题 我把过度函数修改为ease 就变得非常流畅了 对于我的老年机来说 
同时知道了多个问题 下面说的都是用的transform之类的最优动画
过度的时候用百分比为单位 比用px卡
过度函数 ease是最流畅的
