### ISSUE TITLE
vant从1.52install2.20会影响到现在使用项目吗

### ISSUE THREAD

**Issue by song7777** [youzan/vant#4388]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
有部分不兼容更新，请参考更新日志进行升级

https://youzan.github.io/vant/#/zh-CN/changelog#bu-jian-rong-geng-xin
