### ISSUE TITLE
[Bug Report] ImagePreview缩放不跟手

### ISSUE THREAD

**Issue by myaisv** [youzan/vant#4391]
### 设备 / 浏览器
MIUI10.3.14, 小米浏览器

### Vant 版本
2.2.0

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-k897k" target="_blank">https://codesandbox.io/s/vant-issue-moban-k897k</a>

### 描述问题
ImagePreview缩放操作有点不跟手的感觉，有时会急速放大与缩小，请问是否有优化方案？

**Comment by chenjiahan** [comment]
没遇到过这个问题，是只在小米上出现吗

**Comment by myaisv** [comment]
iPad  Safari 12.0 没有问题
iPhone5s 12.3.1 Safari有类似的问题，但是比较轻微
感觉和屏幕大小有点关系

**Comment by chenjiahan** [comment]
有木有复现视频能看下

**Comment by 7115066** [comment]
之前用两点间的面积开方做变化比例的依据，应该用两点间的距离进行计算。
原算法在两点处于水平或垂直位置时面积为0，造成变化比例瞬间变化很大。
function getDistance(touches)修改为：
function getDistance(touches) {
  Math.sqrt(
    ((touches[0].clientX - touches[1].clientX) ** 2) +
    ((touches[0].clientY - touches[1].clientY) ** 2)
  );
}

**Comment by chenjiahan** [comment]
@7115066 确实是这个原因，欢迎 PR~

**Comment by chenjiahan** [comment]
已在 2.2.2 版本修复
