### ISSUE TITLE
[Feature Request] sku数据格式中能否加一个积分字段,就像price一样，可以随选择sku规格改变而改变

### ISSUE THREAD

**Issue by zhukun111** [youzan/vant#4399]
### 这个功能解决了什么问题
积分商城，一般由积分与金钱组合消费。

### 描述您想要的解决方案
在sku数据格式中加一个costpoint字段，当然在list数据格式中也要有这个字段，当选择不同sku规格时，会变化

### 建议的API是什么样的
 sku: {
        price: '11.00',
        costpoint:'20',
        stock_num: 227,
        none_sku: false,
        hide_stock: false,

        collection_id: 2261,
        tree: [
            {
                k: '颜色',
                k_id: '1',
                v: [
                    {
                        id: '30349',
                        name: '天蓝色',
                        imgUrl:
                            'https://img.yzcdn.cn/upload_files/2017/02/21/FjKTOxjVgnUuPmHJRdunvYky9OHP.jpg!100x100.jpg'
                    },
                    {
                        id: '1215',
                        name: '白色'
                    }
                ],
                k_s: 's1',
                count: 2
            },
            {
                k: '尺寸',
                k_id: '2',
                v: [
                    {
                        id: '1193',
                        name: '1'
                    },
                    {
                        id: '1194',
                        name: '2'
                    }
                ],
                k_s: 's2',
                count: 2
            }
        ],
        list: [
            {
                id: 2259,
                price: 100,
                costpoint:22,
                discount: 100,
                code: '',
                s1: '1215',
                s2: '1193',
                s3: '0',
                s4: '0',
                s5: '0',
                stock_num: 110,
                goods_id: 946755
            },
            {
                id: 2260,
                price: 100,
                costpoint:22,
                discount: 100,
                code: '',
                s1: '1215',
                s2: '1194',
                s3: '0',
                s4: '0',
                s5: '0',
                stock_num: 0,
                goods_id: 946755
            },
            {
                id: 2257,
                price: 100,
                costpoint:22,
                discount: 100,
                code: '',
                s1: '30349',
                s2: '1193',
                s3: '0',
                s4: '0',
                s5: '0',
                stock_num: 111,
                goods_id: 946755
            },
            {
                id: 2258,
                price: 100,
                costpoint:22,
                discount: 100,
                code: '',
                s1: '30349',
                s2: '1194',
                s3: '0',
                s4: '0',
                s5: '0',
                stock_num: 6,
                goods_id: 946755
            }
        ]

    }

**Comment by chenjiahan** [comment]
暂时没有计划支持，建议用插槽自定义
