### ISSUE TITLE
[Bug Report] Tabs组件里面使用 dropdownMenu 下拉内容显示有问题

### ISSUE THREAD

**Issue by lex-w** [youzan/vant#4400]
### 设备 / 浏览器
chrome 手机模拟器

### Vant 版本
2.2.0

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-kyvz4" target="_blank">https://codesandbox.io/s/vant-issue-moban-kyvz4</a>

### 描述问题
Tabs组件里面使用 dropdownMenu 下拉内容显示有问题, 
主要是因为 swipeable， animated 会影响

**Comment by chenjiahan** [comment]
这个是浏览器限制的，transform 元素内部的 fixed 会变成 absolute，导致布局有问题

目前暂时没有什么合适的解决方案，建议嵌套使用时不要使用 animated 属性

**Comment by shoo-be-doo** [comment]
> 这个是浏览器限制的，transform 元素内部的 fixed 会变成 absolute，导致布局有问题
> 
> 目前暂时没有什么合适的解决方案，建议嵌套使用时不要使用 animated 属性

找到一个临时的解决方法，目前尚未发现问题。

将 van-dropdown-item 的 position 改成 absolute，就不受 transform 影响了。
再将高度增加，top 固定，如果是向上展开，就 bottom 固定，100% 则是根据 van-dropdown-menu 的高度定位。
```
.van-dropdown-item {
  position: absolute;
  height: 100vh;
  top: 100% !important;
}
```

**Comment by shoo-be-doo** [comment]
https://codepen.io/shoo-be-doo/pen/bGbmwPB

**Comment by chenjiahan** [comment]
在 v2.2.5 版本开始，可以通过在 DropdownItem 上添加 get-container="body" 来避免这个问题
