### ISSUE TITLE
[Feature Request]Circle 环形进度条 能不能增加带缺口的

### ISSUE THREAD

**Issue by McakeChen** [youzan/vant#4403]
### What problem does this feature solve?
就是类似仪表盘一样，下方带缺口的那种环形进度条。

**Comment by McakeChen** [comment]
![微信图片_20190909174255](https://user-images.githubusercontent.com/12393503/64520843-83ced180-d329-11e9-9c56-8f0c792b0baa.png)

**Comment by chenjiahan** [comment]
暂无计划支持喔
