### ISSUE TITLE
[Bug Report] Uploader 上传大点文件

### ISSUE THREAD

**Issue by wangwj1227** [youzan/vant#4408]
### 设备 / 浏览器
小米6/自带浏览器

### Vant 版本
2.2.0

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
Uploader 移动上上传大点的文件会跳出当前网页到桌面，（比如选个几兆的可以，选个94M的跳到手机桌面了）https://pan.baidu.com/s/1Ch7P1Msce-xEjwysq2N6UA 提取码2uf7

**Comment by chenjiahan** [comment]
后续会看下能否对大文件优化

**Comment by chenjiahan** [comment]
大文件跳出的原因是 base64 编码开销太大，在 2.2.7 版本添加了 result-type 的 file 类型，可以避免这个问题
