### ISSUE TITLE
search的获取焦点以及失去焦点事件

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#441]
`@foucus`和`@focus.native`都不能触发，我想在搜索框获取焦点（以及失去焦点）的时候做点什么，但是目前似乎没有这些event！

**Comment by chenjiahan** [comment]
@YYQ8023 感谢反馈，我们会在下个版本支持

**Comment by YYQ8023** [comment]
还有` nav-bar`的（中间部分？）双击事件，主要是想实现一个双击标题回到顶部的功能，其实应该开放这些原生事件啊。是出于什么考虑木有开放呢，冲突吗？

**Comment by chenjiahan** [comment]
@YYQ8023 绑定事件是有开销的噢，所以会按需求来添加相应的事件，不会在一开始就加上所有区域的点击事件

**Comment by chenjiahan** [comment]
已在 0.11.13 中支持
