### ISSUE TITLE
[Bug Report] 倒计时组件

### ISSUE THREAD

**Issue by IHongTaoI** [youzan/vant#4413]
### 设备 / 浏览器
三星手机

### Vant 版本
2.2.0

### Vue版本
2.6.10

### 重现链接
<a href="https://h5-dsh-test.jianzhikeji.com/v3/" target="_blank">https://h5-dsh-test.jianzhikeji.com/v3/</a>

### 描述问题
倒计时显示 NAN， ，可在首页的限时秒杀处看到

**Comment by chenjiahan** [comment]
麻烦提供 codesandbox 复现链接

**Comment by IHongTaoI** [comment]
要在微信端打开

**Comment by IHongTaoI** [comment]
![image](https://user-images.githubusercontent.com/26668906/64600700-2ea8c380-d3ee-11e9-9a40-c8e9301cc47a.png)

![image](https://user-images.githubusercontent.com/26668906/64600722-37999500-d3ee-11e9-895d-2001c775e094.png)

**Comment by IHongTaoI** [comment]
我再检测一下代码
