### ISSUE TITLE
van-datetime-picker，在ios微信内置浏览器下显示不了。版本ios12

### ISSUE THREAD

**Issue by zhangjinning** [youzan/vant#4416]
<van-datetime-picker
        v-model="model.currentDate"
        type="year-month"
        @cancel="handleCancel('birthDate')"
        @confirm="handleBirthDateConfirm"
        :min-date="minDate"
        :formatter="formatter"
      />
苹果手机使用该组件一片空白

**Comment by chenjiahan** [comment]
请注意 iOS 初始化 Date 时不支持 2019-01-01 这样的格式，正确写法是 2019/01/01
