### ISSUE TITLE
[Bug Report] swipe 左右滑动会触发上层组件的的 touch 事件

### ISSUE THREAD

**Issue by yanglei00** [youzan/vant#4417]
### 设备 / 浏览器
iOS

### Vant 版本
2.1.4

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/swipe" target="_blank">https://youzan.github.io/vant/#/zh-CN/swipe</a>

### 描述问题
vue 单个路由页面定义了 touch 事件左右滑动切换页面，但引入了 swipe 组件之后，手势切换 swipe 也会触发页面的 touch 事件。给 swipe 容器增加 @touchmove.stop 也不起作用

**Comment by chenjiahan** [comment]
可以加 `@touchmove.native.stop` 试下

**Comment by yanglei00** [comment]
加上 @touchmove.native.stop 可以解决，谢谢
