### ISSUE TITLE
GoodsAction 组件, 当有三个mini-btn和两个big-btn的时候,big-btn文字显示不全

### ISSUE THREAD

**Issue by qianzhaoy** [youzan/vant#442]
当有三个mini-btn和两个big-btn的时候, 在小屏手机(如 iphone 5 )上 big-btn `加入购物车` 按钮会丢失 `车` 这个字.

我现在解决方法是
`.van-goods-action .van-button--normal{
	padding: 0;
}`
覆盖 ` .van-button--normal` 的 `padding` 值.

另有 在 `GoodsAction` 组件的 `mini-btn`上是否有计划加入,  `Badge` 组件里的 `info` API 呢?  可以用来显示购车商品数, 感觉还是挺有用的.

**Comment by chenjiahan** [comment]
@qianzhaoy 感谢反馈，这两个问题会在下个版本改进

**Comment by chenjiahan** [comment]
已在 0.11.13 中修复
