### ISSUE TITLE
Sketch

### ISSUE THREAD

**Issue by is-liyiwei** [youzan/vant#4421]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

请问能够提供Sketch的psd文件吗

**Comment by chenjiahan** [comment]
暂无计划呢
