### ISSUE TITLE
Uploader 如何上传 txt doc 等格式文件？

### ISSUE THREAD

**Issue by zhangsenhua** [youzan/vant#4423]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by zhangsenhua** [comment]
我想使用 Uploader 上传不仅仅是 image 类型的图片文件，还要上传其他文本文件，如 txt doc 等格式。我尝试修改了 accept 为 'text/*,image/*,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document' 但是不起作用，是我应该使用其他组件，还是用法有问题？

**Comment by Medicine4** [comment]
咋解决的呀
