### ISSUE TITLE
Uploader文件上传的疑问？？？

### ISSUE THREAD

**Issue by tygithub1** [youzan/vant#4430]
这个功能解决了什么问题
难道Uploader文件上传只是一个input type="file" ？并没有实现上传的功能？

描述您想要的解决方案
我怀疑这是一个假的上传组件

建议的API是什么样的
建议可以配置后端地址

**Comment by chenjiahan** [comment]
目前上传过程是需要自行完成的，组件只是对 input file 的一个基本封装。

暂时没有计划支持配置后端地址的功能
