### ISSUE TITLE
van-nav-bar 属性的使用

### ISSUE THREAD

**Issue by yu-bruce** [youzan/vant#4434]
van-nav-bar 这个组件中的属性例如title，border等，border前面添加：才会起作用，title添加和不添加都会起作用，请问这个是怎么个原理，哪些需要加哪些不需要加。

**Comment by chenjiahan** [comment]
不加冒号传的是字符串，加了冒号传的是变量，具体可以看 Vue 模板相关的文档

**Comment by yu-bruce** [comment]
基本语法明白  加冒号传递是变量，border我传递的是false或者true并不是变量额，其次你单纯的理解加了冒号传递的是变量，那么：border=‘true’作何解释

**Comment by chenjiahan** [comment]
准确来说，加了冒号传的是变量或值，不加的时候永远是 string
