### ISSUE TITLE
ssr项目，自动按需引入报错

### ISSUE THREAD

**Issue by FJHou** [youzan/vant#4435]
差不多的问题，我在用使用vue官网提供的ssr教程配置项目。当我使用babel-plugin-import引入vant的时候会出现
![import-err](https://user-images.githubusercontent.com/22517598/64677398-0d0d1200-d4aa-11e9-9fc5-c98949e653c6.png)
如果我用手动按需引入组件的时候会出现
![import-err2](https://user-images.githubusercontent.com/22517598/64677729-bbb15280-d4aa-11e9-86f0-65c8442c615f.png)
我分析的原因是在js文件里使用import引入css文件导致的，官方提供了[解决办法](https://ssr.vuejs.org/zh/guide/css.html#%E4%BB%8E%E4%BE%9D%E8%B5%96%E6%A8%A1%E5%9D%97%E5%AF%BC%E5%85%A5%E6%A0%B7%E5%BC%8F)，但是这个办法比较古老了，使用的插件（extract-text-webpack-plugin）是只支持webpack3.x，最新脚手架是4.x。在git里找了好几脚基于cli3改造ssr的项目，使用自动按需引入都出现了上面的问题。不知道能否提供下解决思路。

_Originally posted by @FJHou in https://github.com/youzan/vant/issues/1939#issuecomment-530264742_

**Comment by chenjiahan** [comment]
这个问题其实和组件库没有直接关系，请到相关仓库下提 issue 喔
