### ISSUE TITLE
[Bug Report] 折叠面板中自定义标题下面的一行会将上一行的内容所遮盖

### ISSUE THREAD

**Issue by WyxYyy** [youzan/vant#4439]
### 设备 / 浏览器
谷歌版本 76.0.3809.132（正式版本） （64 位）

### Vant 版本
2.2.0

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/collapse" target="_blank">https://youzan.github.io/vant/#/zh-CN/collapse</a>

### 描述问题
折叠面板中自定义标题下面的一行会将上一行的内容所遮盖

**Comment by chenjiahan** [comment]
麻烦提供下 codesandbox 复现链接
