### ISSUE TITLE
van-switch-cell 使用v-for循环 :v-model 如何使用？

### ISSUE THREAD

**Issue by johnsken-jerry** [youzan/vant#444]
示例代码

```
<van-cell-group>
          <van-switch-cell v-for="obj in array"
              :key="obj.pType"
              :v-model="obj.isOpen=='on'? 'true': 'false'"
              @click="changeSwitch(event)"
              :title="obj.name" />
        </van-cell-group>

```
：v-model  为什么不起作用呢？一定要每个checkModel都在data里声明吗？

**Comment by chenjiahan** [comment]
@johnsken-jerry v-model 需要绑定变量，而你的代码中实际上传入了 string

建议改成下面这样，isOpen 的类型为 boolean
```html
<van-cell-group>
  <van-switch-cell v-for="obj in array"
    :key="obj.pType"
    :v-model="obj.isOpen"
    @click="changeSwitch(event)"
    :title="obj.name" />
</van-cell-group>
```

**Comment by johnsken-jerry** [comment]
我按照这种方式做了，发现 :v-model 不能绑定变量， 而v-model却可以自由绑定，但使用 v-model不利于循环操作。

**Comment by chenjiahan** [comment]
@johnsken-jerry 没有 :v-model 这种用法，建议你先查阅下 Vue [官方文档](https://cn.vuejs.org/v2/guide/components.html#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6%E7%9A%84%E8%A1%A8%E5%8D%95%E8%BE%93%E5%85%A5%E7%BB%84%E4%BB%B6)
