### ISSUE TITLE
[Bug Report] checklist 的label包含html标签，怎么可以解析html标签

### ISSUE THREAD

**Issue by zhujinhu21** [youzan/vant#4440]
### 设备 / 浏览器
ios/wechat

### Vant 版本
2.2.0

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/embed/ovot7" target="_blank">https://codesandbox.io/embed/ovot7</a>

### 描述问题
checklist 的label 有html标签，可以解析htm标签，不要直接显示html代码

**Comment by chenjiahan** [comment]
```html
<van-checkbox
  v-for="(item, index) in list"
  :key="item"
  :name="item"
>
  <div v-html="item" />
</van-checkbox>
```
