### ISSUE TITLE
[Bug Report] PullRefresh 下拉刷新 slots如何使用

### ISSUE THREAD

**Issue by GHUserZ** [youzan/vant#4446]
### 设备 / 浏览器
pc

### Vant 版本
2.2.0

### Vue版本
2.6.10

### 描述问题
<van-pull-refresh v-model="isLoading" @refresh="onRefresh">
       <slot name="default">demo</slot>
</van-pull-refresh>

这样写无效

**Comment by GHUserZ** [comment]
您写的用法都试过，加上后不会替换默认的，不用下拉直接就显示了demo

**Comment by chenjiahan** [comment]
显示 demo 是什么意思呢，可以给下复现链接

**Comment by GHUserZ** [comment]
<van-pull-refresh v-model="isLoading" @refresh="onRefresh">
  <div slot="default">demo</div>
</van-pull-refresh>
就是这里边的自定义文字，是直接显示在页面上，而不是替换下拉后展示的文字

**Comment by GHUserZ** [comment]
https://codepen.io/ghuserz/pen/LYPBmKY?editors=1000
