### ISSUE TITLE
Using CDN version

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#4449]
Hi

I'm fairly new to this and would like to use the CDN version of your library. Can you please advise with an example of how to do that, even if its just for one example?

Thanks a lot.

**Comment by chenjiahan** [comment]
Here is a basic example in [quickstart](https://youzan.github.io/vant/#/en-US/quickstart#4.-cdn), you can refer to this tutorial.

```html
<!-- import style -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vant@2.2/lib/index.css" />

<!-- import script -->
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vant@2.2/lib/vant.min.js"></script>

<script>
var Vue = window.Vue;
var vant = window.vant;

// Register Lazyload component
Vue.use(vant.Lazyload);

// Call function components
vant.Toast('message');
</script>
```

**Comment by Mashiane** [comment]
Thanks, if you dont mind me asking, are there any other examples that are CDN based in your documentation that I can also look at? I did see this example and I was looking for something more advanced like buttons, images etc as this just shows a toast.

Do you perhaps have a 'playground' that has code snippets that one can explore?

**Comment by chenjiahan** [comment]
Here are some playground templates such as jsfiddle and codesandbox

https://jsfiddle.net/j7p9srLt/

https://codesandbox.io/s/m5v3f

**Comment by Mashiane** [comment]
Thank you so much!
