### ISSUE TITLE
clone 下来的代码不齐

### ISSUE THREAD

**Issue by zhouyujie15014426398** [youzan/vant#4451]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

为什么你们的文档都加了    switch-cell      stepper 组件     
git clone 下来的代码却没有      vant-weapp-dev       也没有

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/tree/dev/src/stepper
https://github.com/youzan/vant/tree/dev/src/switch-cell

有的
