### ISSUE TITLE
uploaded文件上传图片旋转

### ISSUE THREAD

**Issue by vencent2017** [youzan/vant#4457]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
vant:@2.2.1
vue:@3.8.2
uploaded 文件上传  在安卓端  读取到前置相机自拍类型的图片后，图片会顺时针旋转90度  图片本身没有问题，只是获取到的base64的预览图有问题

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3744
