### ISSUE TITLE
uploader组件能否在delete方法将删除的图片的下标暴露出去

### ISSUE THREAD

**Issue by GOGOGOSIR** [youzan/vant#4458]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by GOGOGOSIR** [comment]
![image](https://user-images.githubusercontent.com/26272801/64945520-47f4b880-d8a3-11e9-820d-a0e53a10c5b0.png)
由于业务的需要，可能要被删除图片的下标，希望能将index一起$emit出去

**Comment by chenjiahan** [comment]
可以的，下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.2.2 版本支持
