### ISSUE TITLE
[Feature Request] NoticeBar 通知栏建议添加上下滚动

### ISSUE THREAD

**Issue by zshaojie** [youzan/vant#4463]
### 这个功能解决了什么问题
NoticeBar 通知栏上下滚动可以作为新闻通知栏场景进行展示，方便通知多篇文章。

### 描述您想要的解决方案
NoticeBar 通知栏建议添加上下滚动

### 建议的API是什么样的
在NoticeBar 通知栏基础上滚动条件添加方向选项。

**Comment by chenjiahan** [comment]
暂无计划支持喔，你可以考虑使用 Swipe 组件去实现，Swipe 组件支持上下滚动的

**Comment by zshaojie** [comment]
好的，感谢。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: neverland <notifications@github.com>
发送时间: Tuesday, September 17, 2019 2:50:52 PM
收件人: youzan/vant <vant@noreply.github.com>
抄送: zhangsj <zhangsj_crmpd@outlook.com>; Author <author@noreply.github.com>
主题: Re: [youzan/vant] [Feature Request] NoticeBar 通知栏建议添加上下滚动 (#4463)


暂无计划支持喔，你可以考虑使用 Swipe 组件去实现，Swipe 组件支持上下滚动的

―
