### ISSUE TITLE
Uploader上传视频

### ISSUE THREAD

**Issue by poemxl** [youzan/vant#4465]
### 设备 / 浏览器
安卓手机、谷歌浏览器

### Vant 版本
2.1.8

### Vue版本
2.5.20

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
vant Uploader无法上传除图片外的文件吗

**Comment by Rickykurt** [comment]
![image](https://user-images.githubusercontent.com/1176984/65016666-6ddb9500-d957-11e9-8865-cf4628495379.png)

**Comment by poemxl** [comment]
谢谢回复
环境：我是在手机上使用，Android版本9，EMUI系统版本9.1.0
组件配置：accept 不设置，或者设置为video/*
结果：在打开上传选择的时候，不能像电脑那样手动切换上传文件的类型，会自动过滤掉视频文件，只能选择图片

**Comment by Rickykurt** [comment]
这些都能查到的，和vant关系不大
![image](https://user-images.githubusercontent.com/1176984/65018395-92397080-d95b-11e9-87a9-a59bbe580fb3.png)

**Comment by poemxl** [comment]
好的，非常感谢

**Comment by xiaojinping** [comment]
accept 设为 'video/* 可以上传视频格式，但是渲染的时候，发现没有渲染出来，是不是 直接用的 img 标签渲染
  
import { createNamespace, addUnit, noop } from '../utils';
import { toArray, readFile, isOversize, isImageFile } from './utils';
import Icon from '../icon';
import Image from '../image';
import ImagePreview from '../image-preview';

如果加一个 video 的渲染，会怎么样呢？
