### ISSUE TITLE
[Feature Request] 地址列表选择

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#4466]
### 这个功能解决了什么问题
 radio选择可以自定义颜色，现在选择的颜色直接写在标签的style里，没法通过css更改，例如我想要蓝色主题

### 描述您想要的解决方案
 radio选择可以自定义颜色，提供可修改的选中api

### 建议的API是什么样的
定义变量直接接受颜色数值
![image](https://user-images.githubusercontent.com/42930030/65021692-332b2a00-d962-11e9-8b1d-d9a3929428d8.png)

**Comment by chenjiahan** [comment]
后续会支持

**Comment by chenjiahan** [comment]
已在 2.2.2 版本支持，移除了内联样式，这样可以用 css 覆盖。以及增加了一个对应的 less 变量
