### ISSUE TITLE
请问SwitchCell 开关单元格 的循环判断

### ISSUE THREAD

**Issue by ioer2008** [youzan/vant#4470]
请问我有个使用v-for的用户列表,怎么判断是哪个用户点击了switch?
![微信截图_20190917180253](https://user-images.githubusercontent.com/12724988/65032335-88bd0200-d975-11e9-8f36-91f9a23cc9e0.png)

**Comment by chenjiahan** [comment]
```html
<van-switch v-for="index in list" @change="onChange(index, $event) /"
```

Vue 的事件绑定支持传参的，可以按上面这样写
