### ISSUE TITLE
List 组件

### ISSUE THREAD

**Issue by gengxueke** [youzan/vant#4472]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
refresh 组件嵌套 list组件，我们有一个功能是，点击列表里某一项，进入详情页，list的页面是内嵌h5，跳转的详情页是app页面，点击进入详情页，在回来，列表不会定位到之前进入的位置，并且滚动不会触发load事件
https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
