### ISSUE TITLE
[Bug Report] DatetimePicker formatter month 时纯字符串滑动时会卡住并且不报任何异常

### ISSUE THREAD

**Issue by Yashiro** [youzan/vant#4474]
### 设备 / 浏览器
chrome 76.0.3809.100

### Vant 版本
1.6.13

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
具体代码如下
formatter(type, value) {
      if (type === 'month') {
        if (value === '01') {
          return 'Jan'
        }
        return value   this.$t('month');
      }
      return value;
    },

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by Yashiro** [comment]
https://codesandbox.io/s/vant-issue-moban-oeot3

**Comment by Yashiro** [comment]
> 麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/vant-issue-moban-oeot3

**Comment by chenjiahan** [comment]
下个版本会修复这个问题

**Comment by Yashiro** [comment]
> 下个版本会修复这个问题

多谢及时处理，以下的问题帮忙回复一下
1、2.2.2 什么时候合并提交可以 npm i
2、我们现在使用1.6.13比较文档，升级到 2.2.2 是否会出现其他bug

如果周期较长或者稳定性问题，我打算使用scss绕过这个问题，thx

**Comment by chenjiahan** [comment]
1. 2.2.2 周五发布
2. 有破坏性更新，详见 2.0.0 更新日志

**Comment by chenjiahan** [comment]
已在 2.2.2 版本修复
