### ISSUE TITLE
[Feature Request] 建议新增多种商品卡片样式

### ISSUE THREAD

**Issue by ManiuLtd** [youzan/vant#4475]
### 这个功能解决了什么问题
vant用来做商城前端无疑是最佳选择，但是商城上展示量最大的莫过于商品列表；目前vant内置的商品卡片仅一种样式，建议官方可以内置多种风格的商品卡片

### 描述您想要的解决方案
默认的商品卡面为一行一个，为左右结构的，左边产品图右边商品属性描述等，
例如可以使用参数设置图片在上，商品属性描述价格等在下，也就是上下结构的，可以设置每行显示的商品数量，比如一行一个或者一行两个等
![03](https://user-images.githubusercontent.com/36794003/65052612-50c9b500-d99d-11e9-8336-c28a244c36cb.jpg)
![04](https://user-images.githubusercontent.com/36794003/65052637-558e6900-d99d-11e9-9b70-11a79e88d248.jpg)

### 建议的API是什么样的
由官方根据情况设定

**Comment by bolechen** [comment]
官网有支持更好，目前我的办法是用 flex 布局自己写，哈哈

**Comment by chenjiahan** [comment]
暂无计划支持呢，目前在业务组件方面不会投入更多的精力，建议自己写~
