### ISSUE TITLE
[Bug Report] <van-button size="mini">在手机上，文字不垂直居中。

### ISSUE THREAD

**Issue by microkof** [youzan/vant#4478]
### 设备 / 浏览器
微信浏览器in小米手机

### Vant 版本
2.2.1

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/button" target="_blank">https://youzan.github.io/vant/#/zh-CN/button</a>

### 描述问题
就看官网就好了，手机微信浏览器看官网button的DEMO。看size="mini"的那个。不垂直居中。

**Comment by ystarlongzi** [comment]
可以截图下嘛，感觉是 mini 下字体大小为 `10px` ，是奇数的两倍导致的 😹😹

 - https://github.com/o2team/H5Skills/issues/4
 - https://www.zhihu.com/question/39516424/answer/274374076

**Comment by ystarlongzi** [comment]
刚好前段时间业务上也碰到了这个问题，明天我提个 pr，用测试机验证看下

**Comment by ystarlongzi** [comment]
`<van-tag />` 应该也有类似的问题

**Comment by chenjiahan** [comment]
期待 PR~ 这个问题挺难解决的

**Comment by ystarlongzi** [comment]
@chenjiahan 刚才想了下，如果要兼容 `<van-button />` 子元素可能是任意元素的场景，确实比较难解决，可能需要在组件渲染时，也渲染出一个「子元素的副本」 😹😹

我这里项目是因为只考虑子元素是文本，所以实现起来就简单了很多，大致类似以下方案就能解决掉

``` html
<span data-text={text}>{text}</span>

<style>
span {
  position: relative;
  display: inline-block;
  font-size: 10px;

  // 将文案移除容器外
  height: 12px;
  padding-top: 20px;
  overflow: hidden;
  
  &:before {
    content: attr(data-text);
    position: absolute;
    top: 0;
    left: 0;
   
    // 先放大一倍，然后再缩小回去
    width: 200%
    height: 200%;
    font-size: 20px;
    transform-origin: 0 0;
    transform: scale(0.5);
  }
}
</style>
```

**Comment by chenjiahan** [comment]
嗯呐，缩放是可以解决问题的，但是太 hack 了，不适合用在组件库里。这个问题暂时木有代价较低的解决方式，权衡之下更倾向于保持现状。

**Comment by ystarlongzi** [comment]
嗯嗯，好的
