### ISSUE TITLE
[Bug Report] tabs标签首次显示第一个标签，line错位，宽度不对

### ISSUE THREAD

**Issue by linshuzhen** [youzan/vant#4480]
### 设备 / 浏览器
谷歌 模拟器 iphoneX

### Vant 版本
2.2.1

### Vue版本
2.6.10

### 重现链接
开发过程中 暂无复现链接

### 描述问题
开发过程出现得问题,输出第一个tab的tab.offsetWidth与console.dir(tab)中的offsetWidth不一样

![image](https://user-images.githubusercontent.com/31116700/65104270-7c7f8600-da03-11e9-9f42-ade7c508142c.png)
![image](https://user-images.githubusercontent.com/31116700/65104285-86a18480-da03-11e9-8b19-bd5b0b0e1b15.png)
![image](https://user-images.githubusercontent.com/31116700/65104303-90c38300-da03-11e9-9142-759782c7ee8f.png)

**Comment by linshuzhen** [comment]
![image](https://user-images.githubusercontent.com/31116700/65104346-b51f5f80-da03-11e9-8968-5c39ddbfb96e.png)
第一次标签错位

**Comment by chenjiahan** [comment]
能否提供下 codesandbox 复现链接呢

**Comment by linshuzhen** [comment]
![image](https://user-images.githubusercontent.com/31116700/65105567-ea2db100-da07-11e9-84f4-f5ef3785f6ed.png)
tabs外层设置宽度100%或者不设置就正常了，我原本设置了750，所以导致出错。现在可以了哈

**Comment by linshuzhen** [comment]
> 能否提供下 codesandbox 复现链接呢

可以了哦 是我自己设置了外层父元素宽度导致的，谢谢

**Comment by linshuzhen** [comment]
![image](https://user-images.githubusercontent.com/31116700/65105802-b69f5680-da08-11e9-9b2a-1e3016d310a9.png)
tabs外层设置宽度100%或者不设置就正常了，我原本设置了750，所以导致出错。现在可以了哈

**Comment by chenjiahan** [comment]
好的
