### ISSUE TITLE
tab标签套list列表，切换连续多次触发加载load事件

### ISSUE THREAD

**Issue by fanhu371328** [youzan/vant#4482]
tab标签里面嵌套list列表，初始化加载没问题，tab.id =1 是上拉加载三页数据，此时切换tab.id=2，onchange事件只执行一次，但是数据请求会执行2次或者3次。
次情况发生的场景：

如果加载完tab.id =1 的三页数据后将页面滑动到顶部，也就是第一条数据那里，再切换tab.id=2，此时加载数据正常为tab.id=2的第一页数据。

如果加载完tab.id =1 的三页数据后不将页面滑动到顶部，也就是还在最后一页数据那里不动，直接点或者左右滑动切换tab.id=2，此时加载数据或一次性触发多次请求。onchange事件中congsole.log只会打印一次，
问题最后跟踪到是切换tab后list列表的onLoad 事件会连续多次执行
一页数据有10条，可以占满两屏
求解决方案，

**Comment by fanhu371328** [comment]
获取页面的滚动高度，每次点击tab先让页面滚动到顶部，就可以解决这个问题，但是不知道咱们这个组件里是怎么弄的，scrollTop 的值不管怎么获取都是0，哭死😭

**Comment by chenjiahan** [comment]
描述不太直观，能提供 codesandbox 复现链接吗

**Comment by eastwillie** [comment]
你的list容器父一级高度是否固定了？

**Comment by ystarlongzi** [comment]
> onchange事件中congsole.log只会打印一次

`onchange` 是指的 tab 的事件？

---

> 切换tab后list列表的onLoad 事件会连续多次执行

确定下是否有动态绑定 `loading` 属性，如果有绑定，应该不会触发多次

---

> scrollTop 的值不管怎么获取都是0

能确定下滚动容器是浏览器窗口（html 或 body） 还是 list 容器的父容器

如果能提供一个复现链接更好了

**Comment by fanhu371328** [comment]
不管是html 或 body 还是 list 容器的父容器 获取到的都是0，各种兼容写法都试过，
loading属性通过v-modal绑定，load 之后自动变为true，请求完数据后手动赋值为false，
问题就在这里的load，如果是单个list组件，上拉加载是没有问题的，现在外面套了 tab组件，切换tab的时候触发tab的onchange事件，这个时候list的load不知道为啥会连续执行多次，这样描述能清楚吗

template：
`<van-tabs @change="onChange" sticky>
				<van-tab v-for="(item,index) in categorys" :title="item.name">
					<van-list
					  v-model="loading"
					  :finished="finished"
					  finished-text="没有更多了"
					  @load="onLoadData"
					>
					  	<goodsList v-if="goods" :goodsData="goods"></goodsList>
					</van-list>
				</van-tab>
			</van-tabs>`

script:
`methods: {
			onLoadData() {
				var that = this;
			    if(!that.finished){
			      	that.getGoodsList();
			    }
		     },
			goToUrl(pids, ids) {
				this.$router.push({
					name: "lists",
					params: {
						pid: pids,
						id: ids
					}
				});
			},
			onChange(name, title) {
				var that = this;
				that.page = 1;
				that.finished = false;
				that.categoryId = that.categorys[name].id;
				that.onLoadData();
			},
			getGoodsList() {
				var that = this;
				console.log("finished:"+that.finished);
				console.log("page:"+that.page);
				console.log("categoryId:"+that.categoryId);
				
				if(!that.isLoad){
					that.isLoad = true;
					post("/myCollect").then(res => {
						
						if(res.code == 0) {
							if(that.page == 1){
								that.goods = res.data.list;
							} else {
								that.goods = that.goods.concat(res.data.list);
							}
							console.log(that.goods);
							
							// 加载状态结束
					        that.loading = false;
					        that.isLoad = false;
					        that.page++;
					        
							if(res.data.page_count < that.page){
								
								this.finished = true;
							}
						};
					});
				}
			}
		},`

**Comment by eastwillie** [comment]
你的list父容器没有固定高度， 获取scrollTop当然是0

**Comment by ystarlongzi** [comment]
问题应该是在于多个 `<van-list />` 共用了同一个 `loading` 和 `finished` 吧

``` html
<van-tabs @change="onChange" sticky>
  <van-tab v-for="(item,index) in categorys" :title="item.name">
    <van-list
      v-model="loading"  👈👈👈👈👈
      :finished="finished"   👈👈👈👈👈
      finished-text="没有更多了"
      @load="onLoadData"
    >
      <goodsList
        v-if="goods" 
        :goodsData="goods"
      />
    </van-list>
  </van-tab>
</van-tabs>
```

**Comment by zehuichan** [comment]
```vue
<van-tabs v-model="status" sticky @click="handleClick">
  <van-tab v-for="(item, index) in categorys" :key="index" :title="item.name">
    <van-list
      v-model="loading"
      :finished="finished"
      finished-text="没有更多了"
      :immediate-check="false"
      @load="onload"
    >
      <goodsList
        v-if="goods" 
        :goodsData="goods"
      />
    </van-list>
  </van-tab>
</van-tabs>

<script>
export default {
  methods:{
    handleClick(name, title) {
      this.list = []
      this.page = 1
      this.onLoad()
    },
    onLoad(){
      post('/myCollect').then(res => {
         if(res.code === 0) {
           this.goods = [...this.goods, ...res.data.list]
           // 加载状态结束
           this.loading = false
           this.page++
           if(this.page >= res.data.page_count) {
             this.finished = true
           } else {
              this.finished = false
              this.dataForm.p += 1
            }
         }
      })
    }
  }
}
</script>
```

> 关键代码 `:immediate-check="false"`

**Comment by fanhu371328** [comment]
> 问题应该是在于多个 `<van-list />` 共用了同一个 `loading` 和 `finished` 吧
> 
> ```
> <van-tabs @change="onChange" sticky>
>   <van-tab v-for="(item,index) in categorys" :title="item.name">
>     <van-list
>       v-model="loading"  👈👈👈👈👈
>       :finished="finished"   👈👈👈👈👈
>       finished-text="没有更多了"
>       @load="onLoadData"
>     >
>       <goodsList
>         v-if="goods" 
>         :goodsData="goods"
>       />
>     </van-list>
>   </van-tab>
> </van-tabs>
> ```

应该是这个问题，但是不知道如何处理，他的这个loading 和 finished我没法控制

**Comment by fanhu371328** [comment]
> ```
> <van-tabs v-model="status" sticky @click="handleClick">
>   <van-tab v-for="(item, index) in categorys" :key="index" :title="item.name">
>     <van-list
>       v-model="loading"
>       :finished="finished"
>       finished-text="没有更多了"
>       :immediate-check="false"
>       @load="onload"
>     >
>       <goodsList
>         v-if="goods" 
>         :goodsData="goods"
>       />
>     </van-list>
>   </van-tab>
> </van-tabs>
> 
> <script>
> export default {
>   methods:{
>     handleClick(name, title) {
>       this.list = []
>       this.page = 1
>       this.onLoad()
>     },
>     onLoad(){
>       post('/myCollect').then(res => {
>          if(res.code === 0) {
>            this.goods = [...this.goods, ...res.data.list]
>            // 加载状态结束
>            this.loading = false
>            this.page++
>            if(this.page >= res.data.page_count) {
>              this.finished = true
>            } else {
>               this.finished = false
>               this.dataForm.p += 1
>             }
>          }
>       })
>     }
>   }
> }
> </script>
> ```
> 
> > 关键代码 `:immediate-check="false"`
> 
> 想要进入页面初始化数据的
> 
> ```
> created() {
>   this.onLoad()
> }
> ```

这个写法试过了，效果是一样的，都不行，谢谢

**Comment by bolechen** [comment]
参见 #3430

**Comment by nadirvishun** [comment]
同遇到此问题，好坑，我还不是用的tab，而是两个方法用同一个list，但原理和tab是一样的。
最终解决办法：
- 每次切换前将list重置为空：
```
if (arg === 1) {
  this.iPagination.pageNum = 1;//第一页
  this.list=[];//重置数据列表
  this.finished = false;//重置finished
}
```
- 在list组件中增加v-if
```
<van-list
      v-model="loading"
      :finished="finished"
      :finished-text="finishedText"
      @load="onLoad"
      :immediate-check="false"
      v-if="list.length>0" // 这里增加
    >
```
强制当list为空时，重置list组件，这样就不触发onLoad了，算是没办法的办法。

**Comment by fanqieo** [comment]
> 同遇到此问题，好坑，我还不是用的tab，而是两个方法用同一个list，但原理和tab是一样的。
> 最终解决办法：
> 
> * 每次切换前将list重置为空：
> 
> ```
> if (arg === 1) {
>   this.iPagination.pageNum = 1;//第一页
>   this.list=[];//重置数据列表
>   this.finished = false;//重置finished
> }
> ```
> 
> * 在list组件中增加v-if
> 
> ```
> <van-list
>       v-model="loading"
>       :finished="finished"
>       :finished-text="finishedText"
>       @load="onLoad"
>       :immediate-check="false"
>       v-if="list.length>0" // 这里增加
>     >
> ```
> 
> 强制当list为空时，重置list组件，这样就不触发onLoad了，算是没办法的办法。
> 
> 这个和tab貌似还是有不同的，只适用于每次tab点击重新加载的情况下可以用此方法。

还是你的方法好。。。。牛逼 了

**Comment by ea04lintong** [comment]
vant这个库问题很多，慎用。
