### ISSUE TITLE
[Feature Request] Picker 选择器建议 新增选项关键词筛选功能

### ISSUE THREAD

**Issue by taoguili** [youzan/vant#4484]
### 这个功能解决了什么问题
当选项数据过多时，可以通过关键词输入快速筛选出选项选中

### 描述您想要的解决方案
简单说下我现在这边业务的处理方案：对Picker 进行了第二次封装，借用了Picker 标题Slots，存放了一个Search 搜索组件。当开启筛选功能的时候，标题功能暂时失效，通过监听Search Value，匹配选项 文本 , 调用Picker setColumnValues() 更新数据选项，达到筛选效果。

### 建议的API是什么样的
新增 filterable 参数，启用搜索筛选功能。默认 匹配选项文本，此处可以考虑新增一个回调函数参数传入组件，做为其它形式的的过滤判断条件，更好的匹配多种使用场景。 mail:  wujie.jl@foxmail.com

**Comment by chenjiahan** [comment]
暂无计划支持呢，对于 Picker 而言这不是一个常规的交互
