### ISSUE TITLE
[Feature Request] ImagePreview可以在在图片放大的情况下也能切换图片吗

### ISSUE THREAD

**Issue by zhuyuesen** [youzan/vant#4487]
### 这个功能解决了什么问题
图片预览

### 描述您想要的解决方案
1. 想要预览时默认放大图片
2. 在图片放大的情况下也能切换图片

### 建议的API是什么样的
参考微信朋友圈的图片预览

**Comment by eliot-ye** [comment]
现在的api不就是这样吗？接受一个数组

**Comment by chenjiahan** [comment]
后续会考虑优化手势，跟微信一致

**Comment by git-wangchao** [comment]
pc端，图片预览不能滑动切换（又键长按才能滑动）

**Comment by git-wangchao** [comment]
我们就遇到一个需求，一种内嵌在APP里面的网页，可以分享到第三方社交平台，如果这时候接收人使用pc登录的社交平台，如qq或者微信，那么打开链接就会是在浏览器打开；事实证明，这种情况的占比还比较多，我们的方案是做一种pc端的版心设置，也能像在移动端使用；但是在pc端，vant的组件里，就发现imagePreview不好用，建议优化下

**Comment by chenjiahan** [comment]
@git-wangchao 桌面端使用：https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

**Comment by git-wangchao** [comment]
> @git-wangchao 桌面端使用：https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

谢谢您的回复，

我们用了这个方案，引入了@vant/touch-emulator，但是在PC端，使用ImagePreview，鼠标不能滑动切换图片。（鼠标右键长按是可以，但左边的长按不行，您可以尝试下）

**Comment by chenjiahan** [comment]
嗯，这个 CSS 是为了禁用桌面端浏览器的图片拖拽效果，后续会直接加到组件的样式里

**Comment by lndj** [comment]
借这 issue 咨询下，目前 imagePreview 针对很长的图片，比如手机滚动截图的 case ，处理不是很好，一边需要 1:1 展示，用户和浏览网页一样滚动看，但目前会按照屏幕缩小

**Comment by DickyNet** [comment]
> 借这 issue 咨询下，目前 imagePreview 针对很长的图片，比如手机滚动截图的 case ，处理不是很好，一边需要 1:1 展示，用户和浏览网页一样滚动看，但目前会按照屏幕缩小

同样需要此功能
