### ISSUE TITLE
[Bug Report] ActionSheet 上拉菜单组件actions里的disabled属性不支持变量？

### ISSUE THREAD

**Issue by yulimchen** [youzan/vant#4488]
### 设备 / 浏览器
PC / Chrome

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-wrif9" target="_blank">https://codesandbox.io/s/vant-issue-moban-wrif9</a>

### 描述问题
ActionSheet组件绑定的的actions数据里的disabled属性直接给true或false布尔值的话没问题，给变量的话不生效。具体见重现链接。

**Comment by chenjiahan** [comment]
建议理解一下 JS 里按值传递和按引用传递的区别
