### ISSUE TITLE
dialog在component之外的显示问题

### ISSUE THREAD

**Issue by zhfish** [youzan/vant#449]
目前问题是
```
const vm = new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App },
});

Vue.use(Utils.Http, vm);
···

http是我写的一个工具类,在网络请求错误的时候,可以统一弹窗
但是在httpUtil里面
`this.vm.$dialog`是不存在的
$dialog只存在于component的this里面

参考vux.li的AlertPlugin,
vm里面能找到$vux

预期是vant的组件能不能按照标准的VuePlugins写法, install简单方便啊

**Comment by chenjiahan** [comment]
@zhfish 首先 Vant 的组件是支持通过 Vue.use 的方式 install 的。对于 http 插件内调用的问题，请问this.vm 指向的是什么对象？

**Comment by zhfish** [comment]
vm指向的是一开始的new Vue
但vm里面却没有$dialog
···
export default {
  install(Vue, options) {
    Vue.prototype.$http = axios;
    Vue.http = axios;
    this.$vm = options;
  }
}
···

**Comment by chenjiahan** [comment]
@zhfish 我试了下是可以拿到的 $dialog 的，请确保你的 Vant 版本在 0.11.4 以上，并且引入了 Dialog 组件
