### ISSUE TITLE
目前的骨架屏组件还有待完善

### ISSUE THREAD

**Issue by xupengjilin** [youzan/vant#4490]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

What problem does this feature solve?
希望改善骨架屏Skeleton组件 目前还有待完善 组件 提升网站的加载体验 目前的组件提供的形式过于单一 除了横条和模拟图片就没有了

Describe the solution you'd like
希望 Skeleton骨架屏 组件能够自动识别被包裹html+css内容自动插入骨架屏

What does the proposed API look like?
希望 Skeleton骨架屏 组件能够自动识别被包裹html+css内容自动插入骨架屏

**Comment by chenjiahan** [comment]
自动识别不太好实现，你可以去找一些 webpack 插件去做
