### ISSUE TITLE
[Bug Report] List组件check同时watch两个状态会引发问题

### ISSUE THREAD

**Issue by eastwillie** [youzan/vant#4491]
### 设备 / 浏览器
所有设备

### Vant 版本
2.2.1

### Vue版本
2.6.10

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/src/list/index.js" target="_blank">https://github.com/youzan/vant/blob/dev/src/list/index.js</a>

### 描述问题
List 组件的check机制通过watch了loading 和 finished， 但是通常和refresh组件配合使用时这两个状态可能同时改变， 这回引起重复加载的问题， 建议给check函数加一个debouce

**Comment by chenjiahan** [comment]
refresh 的时候可以手动把 loading 设置成 true，避免这个问题

**Comment by eastwillie** [comment]
> refresh 的时候可以手动把 loading 设置成 true，避免这个问题
只是觉得这样不够优雅， 外部调用这个插件应该对这个无感知， 而且如果不看源代码可能想不到这边来， 文档里关于这个检查的机制没有详细说明， 建议也加上。

**Comment by ystarlongzi** [comment]
> 通常和refresh组件配合使用时这两个状态可能同时改变， 这回引起重复加载的问题

loading 和 finished 的值都分别是怎么变化的？

---

> ... 如果refresh我只是想重置数据，通过重新复制一个初始的数据对象来刷新

是指的在下拉刷新时，并不会主动调接口获取数据，而还是通过重置数据，来触发 load 事件，进而被动的去加载数据？

**Comment by eastwillie** [comment]
> > 通常和refresh组件配合使用时这两个状态可能同时改变， 这回引起重复加载的问题
> 
> loading 和 finished 的值都分别是怎么变化的？
> 
> > ... 如果refresh我只是想重置数据，通过重新复制一个初始的数据对象来刷新
> 
> 是指的在下拉刷新时，并不会主动调接口获取数据，而还是通过重置数据，来触发 load 事件，进而被动的去加载数据？

finished由true变为false触发一次加载, 然后如果不做判断继续调用loadMore又会触发一次。
是的， 打算重置数据， 然后执行check自动重新加载数据。 我认为刷新方法不应该负责加载方法的调用。

**Comment by ystarlongzi** [comment]
>  我认为刷新方法不应该负责加载方法的调用

下拉刷新时，「主动」加载下数据，应该也算是正常的逻辑吧 😄 😄 

另外，在请求数据的方法里，可能也要区分是下拉刷新，还是上拉加载更多，因为它们的逻辑会存在一些差异，如：
 - 下拉刷新：将 pageNo 重置为 1，或清空数据列表
 - 上拉加载：将 pageNo 加 1

你可以看下 demo 里怎么实现的下拉刷新的，还有，可以贴下你预期的组件使用方式是什么嘛 😄

**Comment by eastwillie** [comment]
<template>
    <div id="upload-page" class="page-container">
        <div class="discount-form">
            <el-form :model="productInfo" ref="productForm">
                <el-form-item prop="startTime">
                    <el-input :value="startShowTime" :placeholder="$t('placeholder.startTime')" :readonly="true" @focus="startTimeDialogVisible=true" suffix-icon="el-icon-date"></el-input>
                </el-form-item>
                <el-form-item prop="endTime">
                    <el-input :value="endShowTime" :placeholder="$t('placeholder.endTime')" :readonly="true" @focus="endTimeDialogVisible=true" suffix-icon="el-icon-date"></el-input>
                </el-form-item>
            </el-form>
        </div>
        <div class="start-time">
            <van-popup v-model="startTimeDialogVisible" position="bottom">
                <van-datetime-picker
                        v-model="startTimeHandle"
                        type="date"
                        show-toolbar
                        :min-date="moment().subtract(1, 'years').toDate()"
                        :confirm-button-text="$t('button.confirm')"
                        :cancel-button-text="$t('button.cancel')"
                        @cancel="startTimeDialogVisible=false"
                        @confirm="startTimeConfirm"
                ></van-datetime-picker>
            </van-popup>
        </div>
        <div class="end-time">
            <van-popup v-model="endTimeDialogVisible" position="bottom">
                <van-datetime-picker
                        type="date"
                        show-toolbar
                        :min-date="new Date()"
                        :confirm-button-text="$t('button.confirm')"
                        :cancel-button-text="$t('button.cancel')"
                        @cancel="endTimeDialogVisible=false"
                        @confirm="endTimeConfirm"
                ></van-datetime-picker>
            </van-popup>
        </div>
    </div>
</template>

<script>
    import moment from 'moment';

    export default {
        name: 'upload',
        data() {
            return {
                images: [],
                productInfo: {
                    startTime: undefined,
                    endTime: undefined,
                },
                startTimeHandle: new Date(),
                startTimeDialogVisible: false,
                endTimeDialogVisible: false,
                moment,
            };
        },
        methods: {
            startTimeConfirm(value) {
                this.productInfo.startTime = value;
                this.startTimeDialogVisible = false;
            },
            endTimeConfirm(value) {
                this.productInfo.endTime = value;
                this.endTimeDialogVisible = false;
            },

        },
        computed: {
            startShowTime() {
                if (this.productInfo.startTime) {
                    return moment(this.productInfo.startTime).format('DD/MM/YYYY');
                }
                return undefined;
            },
            endShowTime() {
                if (this.productInfo.endTime) {
                    return moment(this.productInfo.endTime).format('DD/MM/YYYY');
                }
                return undefined;
            },
        },
        watch: {
            startTimeHandle(value) {
                console.log(value);
            },
        },
    };
</script>

**Comment by eastwillie** [comment]
`<template>
    <div id="upload-page" class="page-container">
        <div class="discount-form">
            <el-form :model="productInfo" ref="productForm">
                <el-form-item prop="startTime">
                    <el-input :value="startShowTime" :placeholder="$t('placeholder.startTime')" :readonly="true" @focus="startTimeDialogVisible=true" suffix-icon="el-icon-date"></el-input>
                </el-form-item>
                <el-form-item prop="endTime">
                    <el-input :value="endShowTime" :placeholder="$t('placeholder.endTime')" :readonly="true" @focus="endTimeDialogVisible=true" suffix-icon="el-icon-date"></el-input>
                </el-form-item>
            </el-form>
        </div>
        <div class="start-time">
            <van-popup v-model="startTimeDialogVisible" position="bottom">
                <van-datetime-picker
                        v-model="startTimeHandle"
                        type="date"
                        show-toolbar
                        :min-date="moment().subtract(1, 'years').toDate()"
                        :confirm-button-text="$t('button.confirm')"
                        :cancel-button-text="$t('button.cancel')"
                        @cancel="startTimeDialogVisible=false"
                        @confirm="startTimeConfirm"
                ></van-datetime-picker>
            </van-popup>
        </div>
        <div class="end-time">
            <van-popup v-model="endTimeDialogVisible" position="bottom">
                <van-datetime-picker
                        type="date"
                        show-toolbar
                        :min-date="new Date()"
                        :confirm-button-text="$t('button.confirm')"
                        :cancel-button-text="$t('button.cancel')"
                        @cancel="endTimeDialogVisible=false"
                        @confirm="endTimeConfirm"
                ></van-datetime-picker>
            </van-popup>
        </div>
    </div>
</template>

<script>
    import moment from 'moment';

    export default {
        name: 'upload',
        data() {
            return {
                images: [],
                productInfo: {
                    startTime: undefined,
                    endTime: undefined,
                },
                startTimeHandle: new Date(),
                startTimeDialogVisible: false,
                endTimeDialogVisible: false,
                moment,
            };
        },
        methods: {
            startTimeConfirm(value) {
                this.productInfo.startTime = value;
                this.startTimeDialogVisible = false;
            },
            endTimeConfirm(value) {
                this.productInfo.endTime = value;
                this.endTimeDialogVisible = false;
            },

        },
        computed: {
            startShowTime() {
                if (this.productInfo.startTime) {
                    return moment(this.productInfo.startTime).format('DD/MM/YYYY');
                }
                return undefined;
            },
            endShowTime() {
                if (this.productInfo.endTime) {
                    return moment(this.productInfo.endTime).format('DD/MM/YYYY');
                }
                return undefined;
            },
        },
        watch: {
            startTimeHandle(value) {
                console.log(value);
            },
        },
    };
</script>
`

**Comment by eastwillie** [comment]
> <template>
    <div id="upload-page" class="page-container">
        <div class="discount-form">
            <el-form :model="productInfo" ref="productForm">
                <el-form-item prop="startTime">
                    <el-input :value="startShowTime" :placeholder="$t('placeholder.startTime')" :readonly="true" @focus="startTimeDialogVisible=true" suffix-icon="el-icon-date"></el-input>
                </el-form-item>
                <el-form-item prop="endTime">
                    <el-input :value="endShowTime" :placeholder="$t('placeholder.endTime')" :readonly="true" @focus="endTimeDialogVisible=true" suffix-icon="el-icon-date"></el-input>
                </el-form-item>
            </el-form>
        </div>
        <div class="start-time">
            <van-popup v-model="startTimeDialogVisible" position="bottom">
                <van-datetime-picker
                        v-model="startTimeHandle"
                        type="date"
                        show-toolbar
                        :min-date="moment().subtract(1, 'years').toDate()"
                        :confirm-button-text="$t('button.confirm')"
                        :cancel-button-text="$t('button.cancel')"
                        @cancel="startTimeDialogVisible=false"
                        @confirm="startTimeConfirm"
                ></van-datetime-picker>
            </van-popup>
        </div>
        <div class="end-time">
            <van-popup v-model="endTimeDialogVisible" position="bottom">
                <van-datetime-picker
                        type="date"
                        show-toolbar
                        :min-date="new Date()"
                        :confirm-button-text="$t('button.confirm')"
                        :cancel-button-text="$t('button.cancel')"
                        @cancel="endTimeDialogVisible=false"
                        @confirm="endTimeConfirm"
                ></van-datetime-picker>
            </van-popup>
        </div>
    </div>
</template>

`<script>
    import moment from 'moment';

    export default {
        name: 'upload',
        data() {
            return {
                images: [],
                productInfo: {
                    startTime: undefined,
                    endTime: undefined,
                },
                startTimeHandle: new Date(),
                startTimeDialogVisible: false,
                endTimeDialogVisible: false,
                moment,
            };
        },
        methods: {
            startTimeConfirm(value) {
                this.productInfo.startTime = value;
                this.startTimeDialogVisible = false;
            },
            endTimeConfirm(value) {
                this.productInfo.endTime = value;
                this.endTimeDialogVisible = false;
            },

        },
        computed: {
            startShowTime() {
                if (this.productInfo.startTime) {
                    return moment(this.productInfo.startTime).format('DD/MM/YYYY');
                }
                return undefined;
            },
            endShowTime() {
                if (this.productInfo.endTime) {
                    return moment(this.productInfo.endTime).format('DD/MM/YYYY');
                }
                return undefined;
            },
        },
        watch: {
            startTimeHandle(value) {
                console.log(value);
            },
        },
    };
</script>`

**Comment by eastwillie** [comment]
这个问题可能我理解错了， 我怀疑可能是picker组件公用一个实例导致的， 操作还是一样的，如果选到之前的时间 发现startTimeHandle的值改变了很多次， 在我实际项目里面picker更多， 不知道为什么就卡死了。

**Comment by eastwillie** [comment]
> refresh() {
            this.dataSet = JSON.parse(JSON.stringify(dataSet));
            this.$nextTick(() => {this.$refs.productList.check()});
        },

我是希望这样实现刷新， 这样refresh不就和loadmore的函数没关系了嘛^^

**Comment by ystarlongzi** [comment]
你看下这个 demo 里的写法，和你预期是否一致

https://codesandbox.io/embed/vant-issue-moban-86cwu?codemirror=1

**Comment by eastwillie** [comment]
> 你看下这个 demo 里的写法，和你预期是否一致
> 
> https://codesandbox.io/embed/vant-issue-moban-86cwu?codemirror=1

我现在就是这么写的， 也是直接调load方法 然后把isLoading设置为true。 其实和我上面写的只是形式上不一样。

**Comment by ystarlongzi** [comment]
demo 里下拉刷新和上拉加载更多都是正常的，你可以参照一下




| |
子龙
|
|
邮箱：zhangzilong.zzl@163.com
|

签名由 网易邮箱大师 定制

在2019年09月19日 21:33，Will Liu 写道：

你看下这个 demo 里的写法，和你预期是否一致

https://codesandbox.io/embed/vant-issue-moban-86cwu?codemirror=1

我现在就是这么写的， 也是直接调load方法 然后把isLoading设置为true。 其实和我上面写的只是形式上不一样。

**Comment by eastwillie** [comment]
demo我肯定都是读过了才用的啊， 但是真实项目里都是多tab 数据类型又复杂， 也不是传统分页模式， 对比以下两种写法哪种更好呢？

**Comment by ystarlongzi** [comment]
我个人认为第二种，因为第一种使用了 `$nextTick`，使用它也算是一种 「hack」吧

然后，如果使用第二种，除了设置 `isLoading = true`，同时还需要设置下 `finished = false` ，否则可能会出现多请求一次的现象，即：

``` javascript
refresh() {
  this.dataSet = JSON.parse(JSON.stringify(dataSet));

  // 下拉刷新时，需要同时设置下这两个属性
  this.dataSet[this.category].isLoading = true;
  this.dataSet[this.category].finished = false;
 
 this.loadMore(this.category);
}
```

**Comment by ystarlongzi** [comment]
> 我是希望这样实现刷新， 这样refresh不就和loadmore的函数没关系了嘛^^ 还是解耦有点强迫症

我的理解，refresh 和 loadMore 本质上就是有关联的，完全「解耦」反而不易理解代码

**Comment by eastwillie** [comment]
isfinished在重置数据时候就变回false了，不需要手动重置了。 
这两种只是写法的不同，因为也不影响功能实现，就用第二种写法吧，😁这个问题我先关掉了。
