### ISSUE TITLE
[Bug Report] DropdownMenu 在 Tab 中时，DropdownItem 只会第一个 TabItem 中展示；DropdownItem 与 DropdownMenu 之间有空行。

### ISSUE THREAD

**Issue by shoo-be-doo** [youzan/vant#4494]
### 设备 / 浏览器
76.0.3809.132

### Vant 版本
2.2.1

### Vue版本
2.6.10

### 重现链接
<a href="https://codepen.io/shoo-be-doo/pen/bGbmwPB" target="_blank">https://codepen.io/shoo-be-doo/pen/bGbmwPB</a>

### 描述问题
DropdownMenu 在 Tab 中使用时：
1、DropdownItem 展开后只会第一个 TabItem 中显示。
2、DropdownItem 与 DropdownMenu 之间有空行。
3、TabItem 的内容较少时，DropdownMenu 展开后不显示，需要把 .van-tab__pane 的高度增加才行。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4400
