### ISSUE TITLE
[Bug Report] Date picker边界情况可能造成死循环

### ISSUE THREAD

**Issue by eastwillie** [youzan/vant#4495]
### 设备 / 浏览器
所有设备

### Vant 版本
2.2.1

### Vue版本
2.6.10

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/src/datetime-picker/DatePicker.js" target="_blank">https://github.com/youzan/vant/blob/dev/src/datetime-picker/DatePicker.js</a>

### 描述问题
onChange方法没有对date < minDate的情况做处理， 这种情况是有可能发生的， 比如最小日期是2018-07-01, 先将picker选在2019-06-01, 再把year选到2018， 这时候由于进入formatValue函数会造成死循环对value赋值。

另外formatValue这个函数直接对参数对象进行赋值是否欠妥？ 是否应该再加一层变量。

**Comment by chenjiahan** [comment]
按你的描述试了下没问题，能提供下代码片段吗

**Comment by eastwillie** [comment]
这个问题可能我理解错了， 我怀疑可能是picker组件公用一个实例导致的， 操作还是一样的，如果选到之前的时间 发现startTimeHandle的值改变了很多次， 在我实际项目里面picker更多， 不知道为什么就卡死了。

**Comment by eastwillie** [comment]
> <template>
    <div id="upload-page" class="page-container">
        <div class="discount-form">
            <el-form :model="productInfo" ref="productForm">
                <el-form-item prop="startTime">
                    <el-input :value="startShowTime" :placeholder="$t('placeholder.startTime')" :readonly="true" @focus="startTimeDialogVisible=true" suffix-icon="el-icon-date"></el-input>
                </el-form-item>
                <el-form-item prop="endTime">
                    <el-input :value="endShowTime" :placeholder="$t('placeholder.endTime')" :readonly="true" @focus="endTimeDialogVisible=true" suffix-icon="el-icon-date"></el-input>
                </el-form-item>
            </el-form>
        </div>
        <div class="start-time">
            <van-popup v-model="startTimeDialogVisible" position="bottom">
                <van-datetime-picker
                        v-model="startTimeHandle"
                        type="date"
                        show-toolbar
                        :min-date="moment().subtract(1, 'years').toDate()"
                        :confirm-button-text="$t('button.confirm')"
                        :cancel-button-text="$t('button.cancel')"
                        @cancel="startTimeDialogVisible=false"
                        @confirm="startTimeConfirm"
                ></van-datetime-picker>
            </van-popup>
        </div>
        <div class="end-time">
            <van-popup v-model="endTimeDialogVisible" position="bottom">
                <van-datetime-picker
                        type="date"
                        show-toolbar
                        :min-date="new Date()"
                        :confirm-button-text="$t('button.confirm')"
                        :cancel-button-text="$t('button.cancel')"
                        @cancel="endTimeDialogVisible=false"
                        @confirm="endTimeConfirm"
                ></van-datetime-picker>
            </van-popup>
        </div>
    </div>
</template>

> <script>
    import moment from 'moment';

    export default {
        name: 'upload',
        data() {
            return {
                images: [],
                productInfo: {
                    startTime: undefined,
                    endTime: undefined,
                },
                startTimeHandle: new Date(),
                startTimeDialogVisible: false,
                endTimeDialogVisible: false,
                moment,
            };
        },
        methods: {
            startTimeConfirm(value) {
                this.productInfo.startTime = value;
                this.startTimeDialogVisible = false;
            },
            endTimeConfirm(value) {
                this.productInfo.endTime = value;
                this.endTimeDialogVisible = false;
            },

        },
        computed: {
            startShowTime() {
                if (this.productInfo.startTime) {
                    return moment(this.productInfo.startTime).format('DD/MM/YYYY');
                }
                return undefined;
            },
            endShowTime() {
                if (this.productInfo.endTime) {
                    return moment(this.productInfo.endTime).format('DD/MM/YYYY');
                }
                return undefined;
            },
        },
        watch: {
            startTimeHandle(value) {
                console.log(value);
            },
        },
    };
</script>

**Comment by chenjiahan** [comment]
:min-date="new Date()"

这样的写法是错误的，相当于每次渲染的时候都传入了一个新的最小时间，导致重新触发计算，这样就陷入了死循环
