### ISSUE TITLE
Using KeyValue Pairs for the Picker

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#4496]
Hi

I'm in a sitation where I need to specify my own key value pairs for the list for example

objList = [{"id":2, "value":"My Name"}, ...]

I understand that I can set the 'text' to be 'value' on the picker, instead of using the read 'index', how can I use my own defined key e.g. 'id' value in this case insteard of index 0?

Thanks

**Comment by chenjiahan** [comment]
Duplicated: https://github.com/youzan/vant/issues/4247
