### ISSUE TITLE
How to change search label on right?

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#4497]
How do I change the label on the right of the search?

https://youzan.github.io/vant-issue-generater
![vsearch](https://user-images.githubusercontent.com/5799306/65174770-d0b15700-da51-11e9-8bde-08bc9724fcb7.png)

**Comment by chenjiahan** [comment]
You can follow this demo: https://youzan.github.io/vant/#/en-US/search#custom-button

**Comment by chenjiahan** [comment]
Support in v2.2.2

**Comment by TKYV** [comment]
好像没有办法滚动
