### ISSUE TITLE
[Feature Request] Dialog 内容增加word-break换行

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#4503]
### 这个功能解决了什么问题
纯英文或数字不换行

### 描述您想要的解决方案
Dialog 内容增加word-break换行

### 建议的API是什么样的
word-break:break-all

**Comment by anihCevol** [comment]
![QQ截图20190919125720](https://user-images.githubusercontent.com/42430384/65216688-5ed61d80-dae4-11e9-9412-ea2bf78c72cc.png)

**Comment by chenjiahan** [comment]
下个版本会优化

**Comment by anihCevol** [comment]
好的。

**Comment by chenjiahan** [comment]
已在 2.2.2 版本优化
