### ISSUE TITLE
[Bug Report] swipe调用图片显示异常

### ISSUE THREAD

**Issue by niujinming** [youzan/vant#4504]
### 设备 / 浏览器
PC：chrom、firefox；手机：uc

### Vant 版本
2.2.0

### Vue版本
2.5.2

### 重现链接
无

### 描述问题
Swipe 轮播组件在页面中组合使用时样式错乱。
再现步骤：在Dialog组件中嵌入Swipe组件，此时图片显示不全；进而在Popup 弹出层组件中测试问题依旧。

**Comment by chenjiahan** [comment]
麻烦提供下 codesandbox 复现链接
