### ISSUE TITLE
vant 1.x版本图标都不显示了  本地和线上都是这样，现在用的1.5.2版本，本地和线上都是这样

### ISSUE THREAD

**Issue by song7777** [youzan/vant#4505]
vant 1.x版本图标都不显示了，官网也是这样。现在项目用的1.5.2版本，本地和线上都是这样，昨天好像还正常的，问题是更新后2.2.1后样式会有问题，现在新版本还在开发用的2.2.1，老版本还是要继续跑的，望解答

**Comment by chenjiahan** [comment]
能否打开网络请求界面，看下 ttf 文件是否正确加载了

**Comment by song7777** [comment]
手机用流量进项目可以正常显示了。公司wifi有毒

**Comment by anrananran** [comment]
@song7777  公司wifi估计做了限制
