### ISSUE TITLE
[Bug Report] PullRefresh 下拉刷新组件,加入调整下拉向下弹的距离的参数

### ISSUE THREAD

**Issue by HaiXuan123** [youzan/vant#4512]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.1

### Vue版本
2.6.10

### 重现链接
<a href="http://www.baidu.com" target="_blank">http://www.baidu.com</a>

### 描述问题
vue版本(3.11.0) PullRefresh 下拉刷新组件,下拉的时候，比如说下拉了20px,松开手后，他会自己弹到下拉50px的位置，然后再收起，这个50px的距离怎么能改小一点儿？在api中没有提供修改该距离的参数

**Comment by HaiXuan123** [comment]
这个属性我试过了，不可以，这个只是一个触发刷新的一个最小下拉距离，但是满足下拉距离以后，列表会往下拉大半个屏幕，然后收回，

**Comment by chenjiahan** [comment]
你说的下拉大半个屏幕应该是有问题的，可以给个复现的 codesandbox 链接看下
