### ISSUE TITLE
[Feature Request] swipe支持3d模式

### ISSUE THREAD

**Issue by evazc** [youzan/vant#4526]
### 这个功能解决了什么问题
无

### 描述您想要的解决方案
无

### 建议的API是什么样的
![image](https://user-images.githubusercontent.com/26076008/65371297-e1054400-dc94-11e9-86ef-f51fb8740560.png)

**Comment by chenjiahan** [comment]
暂无计划支持喔，vant 里的 swipe 是比较基础的，如果有这种复杂需求，建议使用社区的一些 swipe 库
