### ISSUE TITLE
popup无法显示close button

### ISSUE THREAD

**Issue by Dszshen** [youzan/vant#4527]
### 源码如下：
![image](https://user-images.githubusercontent.com/12539625/65382167-8b32a980-dd31-11e9-9d16-17c28bdf6b29.png)
### 显示结果如下：
![image](https://user-images.githubusercontent.com/12539625/65382184-c6cd7380-dd31-11e9-8a39-1ac0ded5d5ea.png)

### 版本描述：
1. vant版本：2.2.2
2. vue版本：2.6.10
![image](https://user-images.githubusercontent.com/12539625/65382193-f41a2180-dd31-11e9-83bc-d22126a0dd69.png)

**Comment by chenjiahan** [comment]
建议打开 node_modules/vant/package.json 检查下你是不是正确安装了 2.2.2 版本
