### ISSUE TITLE
[Bug Report] Dialog 弹出框以及Popup 弹出层transform动画会导致Chrome字体模糊

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#4528]
### 设备 / 浏览器
Chrome 76以及更低

### Vant 版本
2.2.2以及更低

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/?source=vuejsorg#/zh-CN/dialog" target="_blank">https://youzan.github.io/vant/?source=vuejsorg#/zh-CN/dialog</a>

### 描述问题
Dialog 弹出框(字体模糊出现在组件调用)以及Popup 弹出层在自定义内容层时transform动画会导致Chrome字体模糊

打开浏览器控制台 找到.van-dialog样式表将transform取消掉Chrome字体模糊就没有了
如果加上就会模糊  这个问题我在Dialog和Popup都有遇到

具体问题可以使用Chrome浏览器查看Dialog 弹出框的组件调用

百度查询了一下这个问题的原因貌似和Chrome浏览器兼容性有关

具体看截图

取消transform之后的显示效果

http://pxz0kovc3.bkt.clouddn.com/2019/09/22/65d9cc53-ed41-4960-9d21-e38a4b0570c5

加上transform之后的显示效果

http://pxz0kovc3.bkt.clouddn.com/2019/09/22/72df5d31-70a1-4a96-8a2b-6d30a4fb0b9c

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3746

暂时没有什么合适的解决方法
