### ISSUE TITLE
兼容问题  IPad  IOS9.3.5  Collapse 折叠面板 展开后有回弹效果

### ISSUE THREAD

**Issue by Ellen0604** [youzan/vant#4535]
Describe the bug
Collapse 折叠面板 展开后有回弹效果

Screenshots
![GIF (2)](https://user-images.githubusercontent.com/24667299/65398874-36a03480-ddec-11e9-8b36-07c997d2d886.gif)

Environment
IPad  ios 9.3.5

Device: App
Vue Versio: 2.5.2
Vant Version: 1.6.5

**Comment by chenjiahan** [comment]
可以升级最新版试下，已经修复了这个问题

**Comment by Ellen0604** [comment]
Vant Version: 2.2.2
已更新最新版本 还是有这个问题

**Comment by Ellen0604** [comment]
> 可以升级最新版试下，已经修复了这个问题

Vant Version: 2.2.2
已更新最新版本 还是有这个问题

**Comment by chenjiahan** [comment]
这个问题暂时没找到复现方法，且只在低版本 ipad 上出现，不影响使用，先 close 了
