### ISSUE TITLE
请问一下CellSwipe组件的回调函数怎么传入当前cell的业务数据？

### ISSUE THREAD

**Issue by erniu** [youzan/vant#454]
场景：
比如一个cell-group中有一堆cell，我在cell中删除其中一项的时候，需要传入当前cell的信息，比如id，用来在回调函数中调api做删除操作，这个怎么传呢？

**Comment by chenjiahan** [comment]
可以通过闭包实现

```html
<van-cell-swipe :right-width="65" :left-width="65" :on-close="onClose(id)">
  <span slot="left">选择</span>
  <van-cell-group>
    <van-cell title="单元格" value="内容" />
  </van-cell-group>
  <span slot="right">删除</span>
</van-cell-swipe>
```

```js
export default {
  methods: {
    onClose(id) {
      return (clickPosition, instance) => {
        console.log(id);
      }
    }
  }
}
```

**Comment by yuwengCipher** [comment]
> 可以通过闭包实现
> 
> ```
> <van-cell-swipe :right-width="65" :left-width="65" :on-close="onClose(id)">
>   <span slot="left">选择</span>
>   <van-cell-group>
>     <van-cell title="单元格" value="内容" />
>   </van-cell-group>
>   <span slot="right">删除</span>
> </van-cell-swipe>
> ```
> 
> ```js
> export default {
>   methods: {
>     onClose(id) {
>       return (clickPosition, instance) => {
>         console.log(id);
>       }
>     }
>   }
> }
> ```



> 可以通过闭包实现
> 
> ```
> <van-cell-swipe :right-width="65" :left-width="65" :on-close="onClose(id)">
>   <span slot="left">选择</span>
>   <van-cell-group>
>     <van-cell title="单元格" value="内容" />
>   </van-cell-group>
>   <span slot="right">删除</span>
> </van-cell-swipe>
> ```
> 
> ```js
> export default {
>   methods: {
>     onClose(id) {
>       return (clickPosition, instance) => {
>         console.log(id);
>       }
>     }
>   }
> }
> ```

完美解决。另外为了保证只能一个cell滑动，需加上instance.swipeMove(0);

**Comment by xiaohongzhou** [comment]
我打印出来item 是undefind，不行哇

**Comment by xingqiliudemao** [comment]
` <van-swipe-cell :right-width="65" :left-width="65" :on-close="function(clickPosition,instance{onClose('111',clickPosition,instance)}">
      <span slot="left">选择</span>
      <van-cell-group>
        <van-cell title="单元格" value="内容" />
      </van-cell-group>
      <span slot="right">删除</span>
    </van-swipe-cell>`
