### ISSUE TITLE
[Bug Report] van-list 怎么去除分割线

### ISSUE THREAD

**Issue by youmu178** [youzan/vant#4540]
### 设备 / 浏览器
Android

### Vant 版本
2.2.2

### Vue版本
2.6.10

### 重现链接
<a href="https://wkbox.imsupercard.com/app/index.html#/couponlist/3" target="_blank">https://wkbox.imsupercard.com/app/index.html#/couponlist/3</a>

### 描述问题
怎么去除列表item的分割线

**Comment by chenjiahan** [comment]
`<van-cell :border="false" />`

**Comment by youmu178** [comment]
谢谢啦
