### ISSUE TITLE
How to decrease the width of the collapseitem 'value'

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#4541]
Hi 

I'd like to make the width of the 'value' for the collapsible more smaller so that the 'label' content takes more of the row size. Can you please advise?

Thanks
![page04](https://user-images.githubusercontent.com/5799306/65403450-0e0c4080-ddd4-11e9-9904-0eaa7b650d65.png)

**Comment by chenjiahan** [comment]
```html
<van-collapse-item value-class="my-class" />
```

```css
.my-class {
  flex: 0.3;
}
```

**Comment by Mashiane** [comment]
Thank you.
