### ISSUE TITLE
[Bug Report] Uploader上传图片，点击预览，下标错误

### ISSUE THREAD

**Issue by wenguangyang** [youzan/vant#4543]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.0

### Vue版本
2.6.10

### 重现链接
无

### 描述问题
当上传几张图片相同的图片，因为图片的data-url是一样的，而判断图片下标是使用内容判断，startPosition: imageFiles.indexOf(item.content || item.url),，导致拿到的下标只能是相同图片中排在数组中最前面的那一张图片的下标

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 2.2.5 版本修复
