### ISSUE TITLE
[Bug Report] 全局引用方式的 swipe 组件懒加载图片失败

### ISSUE THREAD

**Issue by yi-huan** [youzan/vant#4545]
### 设备 / 浏览器
windows 10,  chrome 76

### Vant 版本
2.2.2

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-rve2w" target="_blank">https://codesandbox.io/s/vant-issue-moban-rve2w</a>

### 描述问题
错误信息： Failed to resolve directive: lazy

按理说都全局引用了。不需要我单独再引入吧

**Comment by chenjiahan** [comment]
`Lazyload`需要单独注册的哈，因为注册时可以需要传入 options
