### ISSUE TITLE
[Bug Report] 上传图片后预览时返回上一页关闭图片预览

### ISSUE THREAD

**Issue by lgc2007** [youzan/vant#4550]
### 设备 / 浏览器
H5网页

### Vant 版本
2.2.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
之前用的vant是返回页面时图片预览依旧存在符合需求，更新vant版本后，返回页面图片预览关闭了，导致预览不能使用，建议把 closeOnPopstate 参数一并暴露给 uploader 组件，以便用户选择

**Comment by lgc2007** [comment]
一个进件审核的表单，分为4个步骤，填完之后可以返回去修改（提交表单之前不提交数据，数据存在session），最后一步提交表单

**Comment by chenjiahan** [comment]
用户返回去修改表单，这时候关闭图片预览是合理的

**Comment by lgc2007** [comment]
返回去修改图片的时候已经看不到之前上传的图片是什么了，只显示个文件图标，是不是有点不大好
![image](https://user-images.githubusercontent.com/24352516/65577212-f4225780-dfa5-11e9-8477-e3678b22ce80.png)

**Comment by PerfectYan** [comment]
> 返回去修改图片的时候已经看不到之前上传的图片是什么了，只显示个文件图标，是不是有点不大好
> ![image](https://user-images.githubusercontent.com/24352516/65577212-f4225780-dfa5-11e9-8477-e3678b22ce80.png)

这是你没用对，list: [ url: 'xxxxxx.jgp' ]

**Comment by lgc2007** [comment]
尴尬了，组件更新后没细看对应的api，已解决，谢谢~
