### ISSUE TITLE
[Bug Report] ImagePreview 在苹果手机上放大后图片模糊

### ISSUE THREAD

**Issue by RinaDad** [youzan/vant#4553]
### 设备 / 浏览器
Iphone 7p / 微信浏览器 微信版本7.0.7

### Vant 版本
1.6.18

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-z63re?fontsize=14" target="_blank">https://codesandbox.io/s/vant-issue-moban-z63re?fontsize=14</a>

### 描述问题
ImagePreview在苹果手机上预览时，放大后图片很模糊，安卓手机正常；
见示例；
谢谢！

**Comment by PerfectYan** [comment]
而且，Safari上面点击大图不能关闭，不能左右滑动大图。iOS11.2

**Comment by chenjiahan** [comment]
下个版本会修复图片模糊的问题

**Comment by RinaDad** [comment]
好的，谢谢！！！
从1.6.18升级到2.2.4会有很多问题吗？

**Comment by sunxinyong** [comment]
请问van-area的样式在安卓上展示的非常好看，但是在iOS上 面样式非常的小，而且城市选择列表都是挤在一起的，是为什么啊？请指点一下，谢谢了。

**Comment by chenjiahan** [comment]
@RinaDad 升级时参考更新日志：https://youzan.github.io/vant/#/zh-CN/changelog#bu-jian-rong-geng-xin

@sunxinyong 检查下你的 viewport 是否正确设置

**Comment by RinaDad** [comment]
好的，谢谢！

**Comment by chennengbao** [comment]
ImagePreview 图片预览在iOS 10.3.3  微信7.0.8 预览异常  

1. 无法左右滑动查看上下张图片
2. 点击蒙层无法关闭图片

**Comment by chenjiahan** [comment]
@chennengbao 参见 https://github.com/youzan/vant/issues/3015

**Comment by RinaDad** [comment]
@chenjiahan 2.2.13版本，IOS手机图片放大还是模糊，麻烦帮忙看一下，谢谢！https://codesandbox.io/s/vant-issue-moban-z63re?fontsize=14

**Comment by chenjiahan** [comment]
还没修复嘞，这个比较难修

**Comment by RinaDad** [comment]
好的，没事的，预计在哪个版本可以搞定哈

**Comment by chenjiahan** [comment]
暂时木有预计时间，这个得重构组件的核心逻辑了。

safari 浏览器本身有 bug，通过 transform: scale 放大就会出现模糊的问题，必须通过其他方式去实现

**Comment by RinaDad** [comment]
好的，那再等等，谢谢！

**Comment by akaiya** [comment]
先放大在缩小会解决这个问题，但应该不是最终的解决方案

**Comment by mengxianghan** [comment]
把 translate3d 改成 translate 就不会模糊了

**Comment by chenjiahan** [comment]
> 把 translate3d 改成 translate 就不会模糊了

感谢反馈~ 试了下把 scale3d 改成 scale 确实能避免这个问题，下个版本会改掉

**Comment by chenjiahan** [comment]
已在 2.8.6 版本修复，可以试一试
