### ISSUE TITLE
[Bug Report] Stepper在IOS中会出现input无法聚焦输入的问题

### ISSUE THREAD

**Issue by sky1458** [youzan/vant#4556]
### 设备 / 浏览器
iphone 6s IOS13.0

### Vant 版本
2.2.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/stepper" target="_blank">https://youzan.github.io/vant/#/zh-CN/stepper</a>

### 描述问题
Android和浏览器都是正常的，但是在IOS中会出现输入框无法获得焦点的问题。
在测试中发现，点击输入区域会弹出软键盘，但是input区域未获得焦点，且无法输入数量。

**Comment by chenjiahan** [comment]
可以讲下 close 的原因嘛

**Comment by sky1458** [comment]
> 可以讲下 close 的原因嘛

最后发现是小伙伴在全局设置了 -webkit-user-select: none;来解决IOS上长按复制的问题，导致所有的Input均无法聚集光标输入内容。

**Comment by sky1458** [comment]
发现同样的问题可以尝试给input添加 -webkit-user-select: text;来解决

**Comment by sky1458** [comment]
发现同样的问题可以尝试给input添加 -webkit-user-select: text;来解决

**Comment by chenjiahan** [comment]
get 👌

**Comment by GRJser** [comment]
我已经给尝试给input添加 -webkit-user-select: text;来解决问题,但是 在安卓和 ios 上仍然出现 唤起键盘,但是无法输入和没有光标的问题
