### ISSUE TITLE
submitBar无法使用，其他组件正常

### ISSUE THREAD

**Issue by BenDaye** [youzan/vant#456]
使用 babel-plugin-import加载
Error in render: "TypeError: Cannot read property 'undefined' of undefined"

found in

---> <VanSubmitBar>

**Comment by chenjiahan** [comment]
@BenDaye 请检查下拼写是否正确，或者提供更多的报错信息

```js
import { SubmitBar } from 'vant';

Vue.use(SubmitBar);
```

**Comment by BenDaye** [comment]
@chenjiahan

**Comment by BenDaye** [comment]
@chenjiahan 
![image](https://user-images.githubusercontent.com/26397675/34239676-d8cf0292-e643-11e7-966b-2dca190ff772.png)
![image](https://user-images.githubusercontent.com/26397675/34239689-f40f032c-e643-11e7-9911-9595b4910b3b.png)
![image](https://user-images.githubusercontent.com/26397675/34239697-0e207ba6-e644-11e7-8d2c-2578be7bb5f2.png)

**Comment by zhihange** [comment]
我是引入全部组件的 也遇到这个问题了。。。

**Comment by chenjiahan** [comment]
@BenDaye 我升级了一下 vant-demo 购物车中的依赖版本，没有复现你的问题，请问你能帮忙定位下问题吗，或者升级下依赖版本再试

**Comment by BenDaye** [comment]
@chenjiahan 发现这个问题的版本是0.11.12，刚刚升级到14版。试着用vue-cli初始化vant的模板，不会有这个问题。但是按需导入的时候还是会出现上述一样的报错。
![image](https://user-images.githubusercontent.com/26397675/34260037-65830624-e69f-11e7-9698-7facd5a0b5a6.png)

**Comment by chenjiahan** [comment]
@BenDaye 抱歉没能复现你的问题，vant cli 默认使用了 babel-plugin-import 按需导入，且能正常使用 SubmitBar 组件
