### ISSUE TITLE
iOS11.2很多组件用不了

### ISSUE THREAD

**Issue by PerfectYan** [youzan/vant#4560]
vue 2.6.10 vant2.2.0，在iOS11.2的safari中
 涉及touch事件的，imageview，datepicker，area组件都无法滑动，选择，imageview预览的图片点击无法关闭。
uploader无法上传图片。

**Comment by PerfectYan** [comment]
vue 2.6.10 vant2.2.2

**Comment by chenjiahan** [comment]
可以降级到 Vue 2.5.22 试下

**Comment by PerfectYan** [comment]
> 可以降级到 Vue 2.5.22 试下

好的，我降级试试

**Comment by PerfectYan** [comment]
> 可以降级到 Vue 2.5.22 试下

大佬，什么原因呢？
降级后uploader无法上传图片没有解决，怎么办? 
其他都已经解决了

**Comment by PerfectYan** [comment]
@chenjiahan 大佬，看到你有动静...求帮忙看下上面问题

**Comment by chenjiahan** [comment]
没有遇到过无法上传图片的问题，你可以看下有没有报错

**Comment by PerfectYan** [comment]
> 没有遇到过无法上传图片的问题，你可以看下有没有报错

已解决，form.get的兼容问题。谢谢

**Comment by wenjie6687305** [comment]
请问下我的vant是  2.12.23版本,  也是 苹果手机点击 无法上传图片,安卓正常,请问你是如何解决的呢
![image](https://github.com/youzan/vant/assets/101970262/61e3fc2b-b035-413c-a170-a65c87586bdf)
