### ISSUE TITLE
Tab 标签页 宽度

### ISSUE THREAD

**Issue by PhantomRay** [youzan/vant#4563]
目前tab生成类似下面的代码：
`<div role="tab" class="van-tab" style="flex-basis: 22%;"><span class="van-ellipsis">保健</span></div>`

如果tab是两个字，那觉得间隔太宽。这个flex-basis好像在现有的tab属性里不可调。是否考虑加个参数？

**Comment by aleoyu** [comment]
flex-basis: 22%;     flex: 0 0 22%;  都是固定宽度，如果我把这些都定义为auto时，van-tabs__line 当窗口切换大小时无法正常计算。调用resize()方法也没用。
