### ISSUE TITLE
[Feature Request] 请问官方还会对1.4版本进行维护吗？我看1.5版本增加的特性，对于老项目不支持，我想针对1.4版本提交一个pr

### ISSUE THREAD

**Issue by tu6ge** [youzan/vant#4564]
### 这个功能解决了什么问题
咨询，如果不维护了，那我就不提pr了

### 描述您想要的解决方案
咨询，如果不维护了，那我就不提pr了

### 建议的API是什么样的
咨询，如果不维护了，那我就不提pr了

**Comment by chenjiahan** [comment]
不再维护 1.4 版本了喔，目前在维护的是 1.6.x 版本和 2.x 版本
