### ISSUE TITLE
less编译@toast-background-color: rgba(@text-color, .88);报错

### ISSUE THREAD

**Issue by hopcraft** [youzan/vant#4565]
Uncaught Error: Module build failed: 

@toast-border-radius: 4px;
@toast-background-color: rgba(@text-color, .88);
                       ^
Error evaluating function `rgba`: color functions take numbers as parameters
      in /Users/hopcraft/Documents/projects/meizhitec/light-lppz-h5/node_modules/vant/es/style/var.less (line 644, column 25)

**Comment by chenjiahan** [comment]
less 版本过低，升级下版本就行

**Comment by hopcraft** [comment]
@chenjiahan 能提供下您那边，less 跟 less-loader 的版本吗，我升级到一致试试。谢谢！

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/blob/dev/package.json
