### ISSUE TITLE
[Feature Request] 如何自定义grid组件渲染出的宫格背景色

### ISSUE THREAD

**Issue by sniperZj** [youzan/vant#4567]
### 这个功能解决了什么问题
想实现根据状态的不同显示不同背景色的grid

### 描述您想要的解决方案
增加配置属性

### 建议的API是什么样的
:color or :itemStyle

**Comment by chenjiahan** [comment]
这个 API 不是很有必要，直接通过 css 覆盖样式，动态切换不同的 className 即可
