### ISSUE TITLE
[Feature Request] picker组件的confirm回调不能添加第三个参数

### ISSUE THREAD

**Issue by zrqabc** [youzan/vant#4569]
### 这个功能解决了什么问题
confirm(value, index)回调默认只支持两个参数，如果pick组件是动态多个的，需要传递对应的id或index来匹配到相应修改的对象，所以需要传递第三个参数，类似confirm(value, index，id);如果默认这样传参confirm(value,index)，取不到第三个参数id，如果confirm(id)这样传参，取不到value、index,这样的结果是矛盾的，不能全部传3个参数,而我需要取到3个参数

### 描述您想要的解决方案
confirm(value, index,id),希望能传递第三个参数，这样我可以得到默认的value、index，和自定义的id

### 建议的API是什么样的
https://youzan.github.io/vant/#/zh-CN/picker
confirm(value, index,id)

**Comment by chenjiahan** [comment]
没必要，可以使用 dataset or 闭包传参

**Comment by Clare29** [comment]
楼主解决了吗，我也碰到了这个问题

**Comment by zrqabc** [comment]
没解决

> 楼主解决了吗，我也碰到了这个问题

好像没解决，只是我的需求好像后面变了，你可以试试别的方法

**Comment by Autismerzw** [comment]
> 楼主解决了吗，我也碰到了这个问题

我这边是在设置数据的时候 吧对应的标识 也传进去  类似 `[
        {
             text: '杭州',
             disabled: true,
            id: "test"
         },
]` 


这样在后面可以在confirm 的value参数中直接拿到
