### ISSUE TITLE
[Bug Report] van-field 无法失焦

### ISSUE THREAD

**Issue by daughterRui** [youzan/vant#4576]
### 设备 / 浏览器
所有安卓机型

### Vant 版本
2.0.2

### Vue版本
2.5.17

### 重现链接
<a href="https://smart-dev.gtdreamlife.com/parking/quickCar" target="_blank">https://smart-dev.gtdreamlife.com/parking/quickCar</a>

### 描述问题
van-field 在安卓手机上 点击除输入框区域或者关闭键盘，无法失焦

**Comment by chenjiahan** [comment]
麻烦提供 codesandbox 复现链接

**Comment by daughterRui** [comment]
http://smart-dev.gtdreamlife.com/parking/quickCar

**Comment by chenjiahan** [comment]
codesandbox 链接，不是你们业务的页面，业务页面没法排查代码

**Comment by daughterRui** [comment]
好的   这个看一下   https://codesandbox.io/embed/vue-template-ywmfe   在安卓手机上 点击除输入框区域或者关闭键盘，无法失焦

**Comment by daughterRui** [comment]
麻烦了

**Comment by chenjiahan** [comment]
用小米 8 试了下没复现

**Comment by daughterRui** [comment]
我这边找到问题了，不是组件的bug，是其他的原因
