### ISSUE TITLE
[Bug Report] Dialog中使用DropdownMenu下拉菜单组件失效

### ISSUE THREAD

**Issue by sniperZj** [youzan/vant#4588]
### 设备 / 浏览器
微信浏览器

### Vant 版本
2.2.3

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-20wzs?fontsize=14" target="_blank">https://codesandbox.io/s/vant-issue-moban-20wzs?fontsize=14</a>

### 描述问题
在Dialog弹窗中引入DropdownMenu组件无法正常使用点击下拉菜单遮罩消失,菜单数据并没展示出来

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4400
目前暂时没有解决方案
