### ISSUE TITLE
最新版本的cell箭头错位

### ISSUE THREAD

**Issue by yeahTibbers** [youzan/vant#459]
另外就是全局引用之后，webstorm识别不了vant的标签，像mint-ui就可以，建议参考一下
![image](https://user-images.githubusercontent.com/10751521/34209166-0acab098-e5cc-11e7-81eb-bd33a784f041.png)

![image](https://user-images.githubusercontent.com/10751521/34209196-30cf3796-e5cc-11e7-9689-5eee9c2eadf2.png)

**Comment by chenjiahan** [comment]
@感谢反馈，最新版本的 Cell 箭头样式确实存在问题，一会儿发版修复

**Comment by chenjiahan** [comment]
已在 0.11.14 版本修复
