### ISSUE TITLE
Progress动画中有残影现象

### ISSUE THREAD

**Issue by VictorWu90** [youzan/vant#4591]
设备：部分iOS13设备webkit浏览器
vant:2.2.3
Vue:2.5.16

截图
![file-read-14912](https://user-images.githubusercontent.com/7811456/65681962-8d2b9e00-e08c-11e9-8fef-67d38bd5dd8b.png)

**Comment by chenjiahan** [comment]
能给个 codesandbox 复现链接吗

**Comment by VictorWu90** [comment]
我们这是一个cordova本地项目，目前没有线上的链接

**Comment by chenjiahan** [comment]
我指的是用 https://codesandbox.io/s/m5v3f 创建一个复现问题的链接
