### ISSUE TITLE
[Feature Request] 请问upload组件有没有计划开发允许上传视频的功能

### ISSUE THREAD

**Issue by hiwebliu** [youzan/vant#4593]
### 这个功能解决了什么问题
貌似目前upload组件只能拍照和上传图片。请问后续会计划开发直接拍视频的功能么？

### 描述您想要的解决方案
目前调用拍照功能时只能拍照，没法直接拍摄视频然后上传。

### 建议的API是什么样的
可以在目前的拍照的功能上直接拍视频

**Comment by chenjiahan** [comment]
拍照/选取照片的界面是系统原生界面，我们没法控制哈

**Comment by xs47968224** [comment]
设置accept属性即可 `accept="video/*"`
