### ISSUE TITLE
[Bug Report] types 里没有 overlay 

### ISSUE THREAD

**Issue by akaxiaok** [youzan/vant#4599]
### 设备 / 浏览器
all

### Vant 版本
1.6.26

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/elated-booth-dt8wf?fontsize=14" target="_blank">https://codesandbox.io/s/elated-booth-dt8wf?fontsize=14</a>

### 描述问题
types 里没有 overlay

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.2.5 版本修复
