### ISSUE TITLE
0.11.14的card排版有问题

### ISSUE THREAD

**Issue by yeahTibbers** [youzan/vant#460]
这个是官方老版本的购物车
https://youzan.github.io/vant-demo/#/cart
![image](https://user-images.githubusercontent.com/10751521/34237611-9c03c5ce-e638-11e7-8b36-325d038fe0b1.png)
这个是0.11.14的购物车
![image](https://user-images.githubusercontent.com/10751521/34237617-a86e9988-e638-11e7-81d1-bdb623f6c5c0.png)

**Comment by chenjiahan** [comment]
@yeahTibbers 这个问题是由于 checkbox 样式更新导致的， 我已经在 vant-demo 中更新了相关样式，麻烦查看下最新的代码

**Comment by yeahTibbers** [comment]
@chenjiahan https://github.com/youzan/vant-demo/blob/master/src/view/cart/index.vue 代码似乎没有更新哦

**Comment by chenjiahan** [comment]
@yeahTibbers Sorry，现在已更新
