### ISSUE TITLE
[Bug Report] NumberKeyboard组件iphone 7 plus 兼容个问题

### ISSUE THREAD

**Issue by lioew** [youzan/vant#4604]
### 设备 / 浏览器
微信公众号内打开

### Vant 版本
2.1.3

### Vue版本
2.6.10

### 重现链接
<a href="http://community-web-test.gdgyun.com/#/login" target="_blank">http://community-web-test.gdgyun.com/#/login</a>

### 描述问题
点击数字键盘任意一个数字都会直接关闭掉，目前只在iphone 7 plus上发现这个问题，其他机型使用正常，另外在最新的ios13上会出现卡顿的情况,ios13升级前正常

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by chenjiahan** [comment]
1. iphone 7 plus 的系统版本是多少
2. iphone 7 plus 打开官方 demo 会出现这个问题吗

**Comment by lioew** [comment]
> 1. iphone 7 plus 的系统版本是多少
> 2. iphone 7 plus 打开官方 demo 会出现这个问题吗

我确认一下这个问题， 官方demo我没测试过，但我从我的代码里面看是没会出现那种关闭状态的

**Comment by chenjiahan** [comment]
iOS 13.0 卡顿的情况是系统 bug，最新的 13.1 已经不会卡顿了

**Comment by tinlee** [comment]
https://e80xz.csb.app/ 相同问题

**Comment by chenjiahan** [comment]
兼容问题在这个 issue 跟进：https://github.com/youzan/vant/issues

**Comment by wxwxwxwx** [comment]
6plus ios 12.4.2也遇到这个问题

**Comment by DelingAlieZ10** [comment]
最新13.4.1都一样会有卡顿效果
