### ISSUE TITLE
主题样式文件引入失败

### ISSUE THREAD

**Issue by Yin-Xie** [youzan/vant#4605]
![image](https://user-images.githubusercontent.com/24772971/65753724-1e108100-e142-11e9-944a-b161276838e9.png)

**Comment by Yin-Xie** [comment]
主题样式文件绝对路径是怎么引入的，试了好多遍无效

**Comment by chenjiahan** [comment]
可以使用 `path.join(__dirname, './my.less')` 这样的方式拼接绝对路径

**Comment by watsonhaw5566** [comment]
@Yin-Xie 
![image](https://user-images.githubusercontent.com/4210367/73838170-05ca1480-484e-11ea-9107-56251516f44f.png)
我是这样的哈，你可以参考一下，和@chenjinhan兄说的一样使用path.join就行了
