### ISSUE TITLE
uploader使用问题

### ISSUE THREAD

**Issue by guohuihot** [youzan/vant#4606]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
```
<van-uploader
            v-model="fileList"
            multiple
            :max-count="8"
            image-fit="fill"
            :before-read="beforeRead"
            :after-read="afterRead"
        />
```
uploader
1. 在读取后afterRead内部，上传前，图片就显示了，能不能不显示，一般需要的是上传成功后去更新fileList，才去显示图片
2. 如果设置preview-image=false无论怎么更新fileList都不会显示了

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
