### ISSUE TITLE
按官网实例本地测试 单元格显示嵌套问题

### ISSUE THREAD

**Issue by liu2010y** [youzan/vant#461]
**What is the current behavior?**
![vant cell](https://user-images.githubusercontent.com/3942145/34237893-042f3d94-e63a-11e7-995c-e865cc904554.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**
![jsfiddle](https://user-images.githubusercontent.com/3942145/34238093-e89c3392-e63a-11e7-9f76-725f2ed96f91.png)

`<div id="app">
            <section class="demo-panel demo-cell">
                <van-steps :active="active">
                    <van-step>基本信息</van-step>
                    <van-step>补充填写</van-step>
                    <van-step>联系人</van-step>
                </van-steps>
                <div class="van-doc-demo-block">
                <h2 class="van-doc-demo-block__title">基本用法</h2>
                </div>
                <van-cell-group>
                    <van-cell title="单元格" value="内容" />
                    <van-cell title="单元格" value="内容" label="描述信息" />
                </van-cell-group>
                <van-button size="small" @click="active -= 1">上一步</van-button>
                <van-button size="small">暂存</van-button>
                <van-button size="small" @click="active += 1">下一步</van-button>
            </section>
		</div>
		<script type="text/javascript">
            var app = new Vue({
                el: '#app',
                data:{
                    active:0
                }
            })
 </script>
`
**What is the expected behavior?**
希望像官网文档demo一样正常
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
vant 0.11.13
vue 2.5.11
Win 7 Chrome 60.0.3112.113（正式版本） （64 位）

**Comment by liu2010y** [comment]
第一次用，不知道是我写法问题还是咋回事，请多指导

**Comment by chenjiahan** [comment]
@liu2010y 在 HTML 模板中使用时，请不要使用自闭合标签，需要使用 <van-cell></van-cell> 这样的写法

**Comment by liu2010y** [comment]
@chenjiahan 好的，谢谢
