### ISSUE TITLE
[Feature Request] 列表的滑动过渡

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#4610]
### 这个功能解决了什么问题
ios上列表滑动很卡，即使家里scoll-touch也是很难受

### 描述您想要的解决方案
建议引入better-scroll，列表考虑丝滑体验

### 建议的API是什么样的
better-scroll兼容，顺便问一下，表单的验证会不会考虑一下？

**Comment by chenjiahan** [comment]
不会引入 better-scroll，表单验证会考虑做
