### ISSUE TITLE
[Bug Report] 2.2.4 新版本用babel-plugin-import import 'vant/lib/index.css' 报错

### ISSUE THREAD

**Issue by xiejunping** [youzan/vant#4612]
### 设备 / 浏览器
Google Chrome 版本 76.0.3809.132

### Vant 版本
2.2.4

### Vue版本
2.6.10

### 重现链接
<a href="https://www.jsvue.cn/owner/check" target="_blank">https://www.jsvue.cn/owner/check</a>

### 描述问题
2.2.4 新版本用babel-plugin-import import 'vant/lib/index.css' 报错

success Saved 3 new dependencies.
info Direct dependencies
└─ vant@2.2.4
info All dependencies
├─ @vant/icons@1.1.14
├─ vant@2.2.4
└─ vue-lazyload@1.2.3
Done in 8.43s.
PS F:\code\egg> yarn serve
yarn run v1.17.3
$ vue-cli-service serve
 INFO  Starting development server...
10% building 2/2 modules 0 activei ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from F:\code\egg\public
i ｢wds｣: 404s will fallback to /index.html
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                                                                                                             11:33:24 AM
This dependency was not found:

* vant/lib/index.css in ./src/main.js

To install it, you can run: npm install --save vant/lib/index.css

![UTOOLS1569642105522.png](https://i.loli.net/2019/09/28/PvrTRNiLjmSfWJC.png)

2.2.3 可以

**Comment by leo493852107** [comment]
![image](https://user-images.githubusercontent.com/9987499/65811590-79e41400-e1ed-11e9-8103-3c8a71855fe7.png)
同样的问题，降低版本也不行

**Comment by huipengke** [comment]
快点解决啊

**Comment by Gokeyoung** [comment]
版本回退到2.2.3是可以的（重启一下项目），感觉2.2.4不是完整的，样式加载有问题

**Comment by ctfwren** [comment]
刚更新,就出这个问题了...有vant的QQ群吗?

**Comment by papipapipia** [comment]
我也更新了 暂时 这样解决

import Vant from 'vant'
import './assets/css/index.css'
Vue.use(Vant)

**Comment by bhb603552916** [comment]
> 我也更新了 暂时 这样解决 改到别的路径
> 
> import Vant from 'vant'
> import './assets/css/index.css'
> Vue.use(Vant)

如何让版本回退？

**Comment by danceli** [comment]
node_modules里面没有index.css
<img width="549" alt="捕获" src="https://user-images.githubusercontent.com/50071099/65813771-069dca80-e20c-11e9-901c-d6f072481bf9.PNG">

**Comment by zouyn** [comment]
我也碰到这样的问题。今天发版报错。 2.24有问题 ， 暂时锁2.23的版本。

**Comment by chenjiahan** [comment]
2.2.4 版本的样式编译有问题，目前已修复并发布了 2.2.5 版本

今天白天有事情，没及时发现并处理这个问题，十分抱歉 😭

后续会优化构建流程，避免发布有问题的版本，2.2.5 版本的更新日志明早会更新
