### ISSUE TITLE
2.2.4版本使用按需加载安装时无法加载样式

### ISSUE THREAD

**Issue by yezhihao17** [youzan/vant#4613]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

复现条件
vant  v2.2.4
vue-cli3
babel-plugin-import  v1.12.2

按照官网配置样式无法加载

使用vant  v2.2.3则没有问题
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by n98745** [comment]
遇到同样的，我还没见过样式长什么样。0 0

**Comment by MrXFang** [comment]
前些日子创建一个新项目引入vant完美运行，今天在一个老项目引入vant样式却怎么都没有生效，还以为是哪里写错了，折腾半天也没发现哪里写得有问题，最后看了一下lssues才发现是vant2.2.4的bug。。。
(lll￢ω￢)

**Comment by chenjiahan** [comment]
2.2.4 版本的样式编译有问题，目前已修复并发布了 2.2.5 版本

今天白天有事情，没及时发现并处理这个问题，十分抱歉 😭

后续会优化构建流程，避免发布有问题的版本，2.2.5 版本的更新日志明早会更新
