### ISSUE TITLE
2.2.4版本npm包中各组件样式未导入 导致按需加载使用 所有样式失效！搞了大半天郁闷

### ISSUE THREAD

**Issue by jcdogecc** [youzan/vant#4615]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by jcdogecc** [comment]
对比2.2.3 nodemodules中vant各组件样式存在，2.2.4版本中文件打开均为空 导致无样式 ··· 请及时修复····

**Comment by fengxianqi** [comment]
同遇到这个问题，本来还想更新下。。

**Comment by chenjiahan** [comment]
2.2.4 版本的样式编译有问题，目前已修复并发布了 2.2.5 版本

今天白天有事情，没及时发现并处理这个问题，十分抱歉 😭

后续会优化构建流程，避免发布有问题的版本，2.2.5 版本的更新日志明早会更新
