### ISSUE TITLE
Picker 选择器可以支持鼠标滚轮选择吗

### ISSUE THREAD

**Issue by luojianet** [youzan/vant#4617]
### 设备 / 浏览器
电脑端企业微信

### Vant 版本
2.1.8

### Vue版本
2.6.6

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html#/zh-CN/picker" target="_blank">https://youzan.github.io/vant/mobile.html#/zh-CN/picker</a>

### 描述问题
picker不支持鼠标滚轮操作，在pc端选择很不方便。

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

**Comment by luojianet** [comment]
> 参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

安装了@vant/touch-emulator这个依赖了，这个依赖只支持桌面端的touch操作，有计划支持桌面端的滚轮操作吗？

**Comment by chenjiahan** [comment]
没计划支持喔
