### ISSUE TITLE
[Bug Report] PullRefresh 下拉刷新组件在微信浏览器中偶尔会拖动整个页面 不触发下拉刷新

### ISSUE THREAD

**Issue by by05021** [youzan/vant#4618]
### 设备 / 浏览器
安卓9.0 微信浏览器

### Vant 版本
2.1.3

### Vue版本
2.6.10

### 重现链接
<a href="http://sc.zzaofeng.cn/shop/#/push" target="_blank">http://sc.zzaofeng.cn/shop/#/push</a>

### 描述问题
PullRefresh 下拉刷新组件在微信浏览器中偶尔会拖动整个页面 不触发下拉刷新

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/2908

**Comment by luxuetong** [comment]
你好你们这个问题解决了吗

**Comment by luxuetong** [comment]
你发的这个链接是ios 的链接，人家测试的是安卓手机出现的问题

**Comment by luxuetong** [comment]
@chenjiahan
