### ISSUE TITLE
Uploader 这个组件  限制1张图片  苹果XR 连续拍照会导致页面刷新

### ISSUE THREAD

**Issue by wbjeln** [youzan/vant#4619]
Uploader 这个组件  限制1张图片  苹果XR 连续拍照会导致页面刷新

**Comment by wbjeln** [comment]
微信的浏览器 不是每次都出现  查了网上可能内存不足  有无办法可以限制吗？

**Comment by chenjiahan** [comment]
选取文件的时候是怎么连续拍照的，能给个录屏看下吗
