### ISSUE TITLE
demo中SwipeCell 取消删除事件报错

### ISSUE THREAD

**Issue by xiaochegnzi0** [youzan/vant#4624]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

demo中SwipeCell取消的时候报错了，
<van-swipe-cell :on-close="onClose">
  <template slot="left">
    <van-button square type="primary" text="选择" />
  </template>

  <van-cell :border="false" title="单元格" value="内容" />

  <template slot="right">
    <van-button square type="danger" text="删除" />
  </template>
</van-swipe-cell>
export default {
  methods: {
    // clickPosition 表示关闭时点击的位置
    onClose(clickPosition, instance) {
      switch (clickPosition) {
        case 'left':
        case 'cell':
        case 'outside':
          instance.close();
          break;
        case 'right':
          Dialog.confirm({
            message: '确定删除吗？'
          }).then(() => {
            instance.close();
          });
          break;
      }
    }
  }
}

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
这个是 Promise reject 的正常提醒，如果不想看到，在 Promise 后面加个 catch 即可
