### ISSUE TITLE
[Bug Report] ios10 密码输入框异常

### ISSUE THREAD

**Issue by tinlee** [youzan/vant#4626]
### 设备 / 浏览器
ios10 微信环境

### Vant 版本
2.2.5

### Vue版本
2.6.10

### 重现链接
<a href="https://e80xz.csb.app/" target="_blank">https://e80xz.csb.app/</a>

### 描述问题
ios10，输入任何数字，会触发隐藏

**Comment by chenjiahan** [comment]
这个问题的原因是 Vue 2.6 在 iOS 10 上事件冒泡不触发，跟这个 [issue](https://github.com/youzan/vant/issues/3015) 是同个问题

你可以把 Vue 降级到 2.5.22 版本来解决，后续我们会在 Vant 里添加兼容处理

**Comment by chenjiahan** [comment]
已在 2.2.6 版本兼容
