### ISSUE TITLE
[Bug Report] v-for 同时使用两个CountDown 倒计时组件的时候倒计时结果错误

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#4628]
### 设备 / 浏览器
PC/Mobile

### Vant 版本
2.2.5

### Vue版本
2.6.10

### 重现链接
<a href="http://pxz0kovc3.bkt.clouddn.com/2019/09/29/516ed9a0-2dd0-4aff-9313-f7c848073ba9" target="_blank">http://pxz0kovc3.bkt.clouddn.com/2019/09/29/516ed9a0-2dd0-4aff-9313-f7c848073ba9</a>

### 描述问题
v-for 同时使用两个CountDown 倒计时组件的时候倒计时结果错误

这个是我页面循环出来的组件
http://pxz0kovc3.bkt.clouddn.com/2019/09/29/478fd48b-4d43-42d8-a19f-58ebfa439b3f

这个是我的数据结构  closeTime和openTime时间同为秒级 有10秒的差距
http://pxz0kovc3.bkt.clouddn.com/2019/09/29/d26f00cc-c578-4be9-9387-8498addbdd8c

这个是渲染出来的结果 时间一致
http://pxz0kovc3.bkt.clouddn.com/2019/09/29/516ed9a0-2dd0-4aff-9313-f7c848073ba9

**Comment by chenjiahan** [comment]
给个 codesandbox 复现链接呗

**Comment by OnlyLady** [comment]
> 给个 codesandbox 复现链接呗

https://zb39q.csb.app/

**Comment by OnlyLady** [comment]
> 给个 codesandbox 复现链接呗

https://codesandbox.io/s/vant-issue-moban-zb39q

**Comment by chenjiahan** [comment]
建议再看一遍文档，大家的时间都很宝贵

<img width="351" alt="屏幕快照 2019-09-30 上午10 04 48" src="https://user-images.githubusercontent.com/7237365/65844683-c5233180-e369-11e9-8e27-36bd65db28fe.png">
