### ISSUE TITLE
Picker 选择器问题

### ISSUE THREAD

**Issue by liu2010y** [youzan/vant#463]
**What is the current behavior?**
![picker](https://user-images.githubusercontent.com/3942145/34243913-0f96b562-e65e-11e7-96c2-1ebed036d590.png)
是不是我写的问题，在本地和jsfiddle上都是这样....还是等1.0发布再来看吧 ::>_<::

**Comment by chenjiahan** [comment]
@liu2010y HTML 模板中的 props 请采用中划线写法，参见 https://www.youzanyun.com/zanui/vant#/zh-CN/component/quickstart

另外 1.0 版本会在近期发布

**Comment by liu2010y** [comment]
@chenjiahan 谢谢，我再试试
