### ISSUE TITLE
[Bug Report] van-card自定义slot="num"点击事件问题

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#4630]
### 设备 / 浏览器
win10/谷歌

### Vant 版本
2.2.1

### Vue版本
2.5.20

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-lkggd" target="_blank">https://codesandbox.io/s/vant-issue-moban-lkggd</a>

### 描述问题
自定义slot="num"我使用了步进器，但是发现 步进器的增减会触发van-card的点击事件，有什么办法能保留card的点击事件，同时和步进器的增减按钮不冲突呢

**Comment by cangyu1993** [comment]
![image](https://user-images.githubusercontent.com/42930030/65844303-437ed400-e368-11e9-9d70-bac5dd72487f.png)
我换成slot="footer"也会触发card点击事件

**Comment by chenjiahan** [comment]
阻止冒泡即可
```html
<van-stepper @click.native.stop />
```

**Comment by cangyu1993** [comment]
哦哦，才疏学浅了，我发现click-thumb和click也会点击前者同时触发后者，忘记冒泡这个东西了，不好意思哈

**Comment by chenjiahan** [comment]
么事哈
