### ISSUE TITLE
[Bug Report] uploader 在安卓手机上掉不出选择图片

### ISSUE THREAD

**Issue by 731ghyurt** [youzan/vant#4631]
### 设备 / 浏览器
安卓手机小程序

### Vant 版本
1.4.5

### Vue版本
2.5.16

### 重现链接
<a href="https://t.liyboo.com/wemall/user/add-work-order" target="_blank">https://t.liyboo.com/wemall/user/add-work-order</a>

### 描述问题
在使用web-view的小程序中使用uploader时在安卓手机上测试时出现掉不出相册或者手机搞图片，下面是我的代码
 <van-cell class="image_info">
                <van-uploader :afterRead="imageAfterRead">
                    <div class="image_upload">
                        <van-icon name="camera_full" />
                    </div>
                </van-uploader>
                <div>上传图片</div>
            </van-cell>

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues?utf8=%E2%9C%93&q=uploader+%E5%AE%89%E5%8D%93
