### ISSUE TITLE
search 在ios下不支持autofoucus属性，必须手动触发

### ISSUE THREAD

**Issue by liaowenqian** [youzan/vant#464]
![image](https://user-images.githubusercontent.com/34738355/34249821-026b2022-e676-11e7-9e47-6e929d3c688f.png)
![image](https://user-images.githubusercontent.com/34738355/34249868-30cc880c-e676-11e7-886d-4fcec9195e12.png)
已更新到0.11.14

**Comment by chenjiahan** [comment]
@liaowenqian autofoucus 是 input 原生属性，iOS 系统禁止页面输入框自动聚焦，只能在点击事件后触发 focus
