### ISSUE TITLE
NoticeBar 通知栏   为什么不能  让文字不溢出时就滚动

### ISSUE THREAD

**Issue by xutongkai** [youzan/vant#4641]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
没必要喔，目前设计的交互是只有溢出时才会滚动

**Comment by xutongkai** [comment]
建议咱们给个这种选择  因为我们开发时客户都是要不溢出也滚动的     给咱们团队回复速度点赞




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 下午3:02
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "徐同凯"<1781746787@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] NoticeBar 通知栏   为什么不能  让文字不溢出时就滚动 (#4641)




没必要喔，目前设计的交互是只有溢出时才会滚动

**Comment by chenjiahan** [comment]
有一些方法可以实现这个效果，比如在内部套一层 div

```html
<van-notice-bar>
  <div style="display: flex;">
    <div style="width: 100vw;">一行短文字</div>
    一行短文字
  </div>
</van-notice-bar>
```

**Comment by xutongkai** [comment]
谢谢




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 下午3:14
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "徐同凯"<1781746787@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] NoticeBar 通知栏   为什么不能  让文字不溢出时就滚动 (#4641)




有一些方法可以实现这个效果，比如在内部套一层 div
 <van-notice-bar>   <div style="display: flex;">     <div style="width: 100vw;">一行短文字</div>     一行短文字   </div> </van-notice-bar>

**Comment by suifengpiao3210** [comment]
@chenjiahan   但是你说的这个办法有些缺陷  就是会文字走完后，过很久才会重新播放下一轮文字，体验很不好，还有别的解决办法么

**Comment by chenjiahan** [comment]
目前只能通过手动设置内容宽度的方式来触发滚动，后续我们会看下能否优化

**Comment by suifengpiao3210** [comment]
这种方式我试了  效果有些不好  能有临时好点的解决办法么  很急  兄弟

**Comment by chenjiahan** [comment]
木有嘞，你可以自己研究下

**Comment by learnwritebug** [comment]
这个需求官方有计划加吗？比如一些获奖推送，是一个通知队列，有的标题短了， 就永远不更新了。虽然有方式实现，但是不那么完美，觉得官方封装下会更好。

**Comment by a497771654** [comment]
期待啊，就是有多条通知，但是每条都不超出一行，就尴尬了。
