### ISSUE TITLE
[Bug Report] vue-cli-service build --target lib 打包后运行失败，Vue 对象不存在？

### ISSUE THREAD

**Issue by gaollg** [youzan/vant#4645]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.5

### Vue版本
2.6.10

### 描述问题
1、使用全局引入的方式，即：
import Vant from 'vant';
import 'vant/lib/index.css';
Vue.use(Vant);

2、vue-cli-service build --target lib 打包

3、运行报错 “Uncaught TypeError: Cannot read property 'extend' of undefined”，源码位置：
```

/**
 * Use scopedSlots in Vue 2.6 
 * downgrade to slots in lower version
 */
import Vue from 'vue';
export var SlotsMixin = Vue.extend({
  methods: {
    slots: function slots(name, props) {
      if (name === void 0) {
        name = 'default';
      }

      var $slots = this.$slots,
          $scopedSlots = this.$scopedSlots;
      var scopedSlot = $scopedSlots[name];

      if (scopedSlot) {
        return scopedSlot(props);
      }

      return $slots[name];
    }
  }
});

```

### 运 行时 Debug 截图：
![image](https://user-images.githubusercontent.com/2359462/65959534-d2810e80-e484-11e9-99c8-0c96353cb060.png)

本地控制台录入，能找到 Vue，说明先导入进去了。
![image](https://user-images.githubusercontent.com/2359462/65959588-fc3a3580-e484-11e9-8adf-5462b43d91a3.png)
![image](https://user-images.githubusercontent.com/2359462/65959605-0d834200-e485-11e9-9851-82419588185b.png)

**Comment by chenjiahan** [comment]
这个和 Vant 没有关系喔，是你自己的打包配置问题，建议自行调试
