### ISSUE TITLE
[Feature Request] 适用于两排经典布局的商品卡片

### ISSUE THREAD

**Issue by Bean19940228** [youzan/vant#4646]
### 这个功能解决了什么问题
可以用于两列经典布局展示商品

### 描述您想要的解决方案
卡片分为上侧商品图片区,中间商品详情区(例如商品名称和价格等),和下侧操作区(例如可以有几个icon然后点击icon可以进行操作例如添加到购物车等)。

### 建议的API是什么样的
希望API可以类似于现有的商品卡片. 可以配合格栅使用.

**Comment by chenjiahan** [comment]
暂无计划支持喔
