### ISSUE TITLE
想问下为什么下拉菜单组件不能使用 会无法解析

### ISSUE THREAD

**Issue by 13535835319** [youzan/vant#4648]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

错误提示
in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/home/home.vue
Module not found: Error: Can't resolve 'vant/lib/dropdown-menu/style' in 'D:\vueprojects\vivo-shop-master\src\pages\home'

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
