### ISSUE TITLE
ImagePreview 图片预览切换时没有过渡效果，很生硬

### ISSUE THREAD

**Issue by qadcyygg** [youzan/vant#4651]
ImagePreview 图片预览，设置startPosition后切换时没有过渡效果，很生硬，请问如何解决？

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by qadcyygg** [comment]
> 请按照模板创建 issue，感谢配合

https://youzan.github.io/vant-issue-generater 这个地址点了发布没反应

**Comment by chenjiahan** [comment]
可能是网络问题，可以再试下
