### ISSUE TITLE
[Bug Report] 同页多个List会滚动时同时触发所有load

### ISSUE THREAD

**Issue by aosnow** [youzan/vant#4654]
### 设备 / 浏览器
iphone 8p/wexin

### Vant 版本
2.2.5

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/list" target="_blank">https://youzan.github.io/vant/#/zh-CN/list</a>

### 重现步骤
以上案例为例：
1、进入页面后，首个List首页被加载
2、切换到第个“错误提示标签”，等加载完成，点击“请求失败，点击重新加载”
3、一直滚动第二个tab到底部，模拟数据是40条
4、再切换到第一个标签
如此可发现，第一个tab其实在后台同步触发load，导致切换过来后，一直滚到底部直接加载满了40条，请注意观察并不会出现“加载中...”提示
另外，也可以“npm install”到本地随便写两个tab来测试，并在load中打印任何信息，会看到会在某个load触发时，同步打印所有load中的信息（后台全部触发了load，猜测应该是触发了所有scroll的监听）

### 描述问题
如果同一个页面存在多个List，例如tab页，那么会在某个tab页触发load时将所有tab的load同时触发，实际上不应该如此，会造成不必要的数据请求和资源消耗。
请查看官方文档 https://youzan.github.io/vant/#/zh-CN/list 就可以看出来问题：
“tab 错误提示”通过滚动加载所有数据到底部，然后回到“tab 基础用法标签”就可以看出所有数据同样加载完成了。

**Comment by chenjiahan** [comment]
我试了下没有你说的这个问题唉

**Comment by aosnow** [comment]
> 我试了下没有你说的这个问题唉

已经添加了详细重现步骤了，谢谢

**Comment by Jackzyy** [comment]
> 我试了下没有你说的这个问题唉

我在项目中也遇到相似问题，来看ISSUE，结果第一个就是。
其实 @aosnow 应该想说的是下面这种情况：
![image](https://user-images.githubusercontent.com/39424122/66374499-c09bf000-e9dd-11e9-912b-e934baa456e1.png)
我第一次进入该页面，切换至第二个Tab标签，然后向上滑动，结果发现第一个的上拉加载也被触发了。
我是给了每个tab标签都套了上拉和下拉。
Vant 版本：2.2.1

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3430
