### ISSUE TITLE
字体库资源加载慢  https://img.yzcdn.cn/vant/vant-icon-3a7dc2.woff2

### ISSUE THREAD

**Issue by h1215811677** [youzan/vant#4655]
### 设备 / 浏览器
移动端、浏览器

### Vant 版本
1.6.27

### Vue版本
2.6.10

### 重现链接
<a href="https://img.yzcdn.cn/vant/vant-icon-3a7dc2.woff2" target="_blank">https://img.yzcdn.cn/vant/vant-icon-3a7dc2.woff2</a>

### 描述问题
字体库22.8k 下载要500ms造成网页加载慢

**Comment by aosnow** [comment]
请官方考虑是否直接使用字体文件发布到项目中，由user构建，而不是写死cdn地址在less中

**Comment by chenjiahan** [comment]
文档里有说明本地字体文件的用法，可以参考下

https://youzan.github.io/vant/#/zh-CN/icon#shi-yong-ben-di-zi-ti-wen-jian
