### ISSUE TITLE
Picker、Popup、Dialog等在微信小程序中打开,未能覆盖原生背景

### ISSUE THREAD

**Issue by whlong789** [youzan/vant#4657]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
小程序的问题请到 vant-weapp 仓库下提问，感谢配合
