### ISSUE TITLE
优惠卷组件没有完全实现语言国际化

### ISSUE THREAD

**Issue by TangGe2010** [youzan/vant#4660]
![image](https://user-images.githubusercontent.com/42267099/66385623-627a0780-e9f3-11e9-9102-ec9e8cfc8267.png)
![image](https://user-images.githubusercontent.com/42267099/66385719-8dfcf200-e9f3-11e9-9544-218dd644fff5.png)
如上图所述，“3张可用”和“暂无优惠券”不支持其他语言替换

**Comment by chenjiahan** [comment]
支持的

**Comment by TangGe2010** [comment]
感谢回复，请问是怎么实现的？我看官网中没有单独的变量给它赋值啊




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 凌晨0:18
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "唐建兵"<294816099@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] 优惠卷组件没有完全实现语言国际化 (#4660)




支持的

**Comment by rex-zsd** [comment]
可以看下[国际化部分的文档](https://youzan.github.io/vant/#/zh-CN/locale)
自定义[国际化配置文件](https://github.com/youzan/vant/blob/dev/src/locale/lang/zh-CN.ts)
