### ISSUE TITLE
[Bug Report] IOS13 QQ中 NumberKeyboard控件 输入数字会弹出 呼叫 1234567890

### ISSUE THREAD

**Issue by chao-wu** [youzan/vant#4661]
### 设备 / 浏览器
IOS13 QQ环境

### Vant 版本
2.2.6

### Vue版本
2.6.10

### 描述问题
在ios13的 QQ环境下，点击数字键盘时，会弹出 呼叫菜单，呼叫内容为1234567890

**Comment by chenjiahan** [comment]
可以加上 `<meta name="format-detection" content="telephone=no">` 试下

**Comment by chao-wu** [comment]
> 可以加上 `<meta name="format-detection" content="telephone=no">` 试下

感谢，涨知识了！解决了我的问题
