### ISSUE TITLE
移动端图片预览异常

### ISSUE THREAD

**Issue by cq0702** [youzan/vant#4662]
设备 / 浏览器
ios 12.3

Vant 版本
2.2.6

Vue版本
2.6.10

重现链接
https://youzan.github.io/vant/#/zh-CN/image-preview

描述问题
用的函数调用，传了图片数组，按钮点击触发发现在手机上图片是上下排布的，而不是水平，很奇怪，还有一个就是图片很大，没有适配，超出了屏幕。以下是代码：
 ImagePreview({ 
  images: [ 
   'http://photocdn.sohu.com/20120708/Img347586981.jpg', 
   'http://photocdn.sohu.com/20120708/Img347586981.jpg', 
   'http://photocdn.sohu.com/20120708/Img347586981.jpg', 
  ], startPosition: 0, 
   closeOnPopstate: true, minZoom: 1, maxZoom: 2, showIndex: true, onClose() { // do something } });

**Comment by chenjiahan** [comment]
请确认下你是否正确引入了 vant 的样式
