### ISSUE TITLE
优惠券组建多语言翻译问题

### ISSUE THREAD

**Issue by TangGe2010** [youzan/vant#4664]
设备 / 浏览器
iphone 8p/wexin

Vant 版本
2.1.8

Vue版本
2.5.16

重现链接
https://youzan.github.io/vant/?source=vuejsorg#/zh-CN/coupon-list

描述问题
![image](https://user-images.githubusercontent.com/42267099/66445883-e3c8ad00-ea7a-11e9-956d-7b287d05c840.png)
如图优惠券组建中的文字“2张可用”,有变量可以替换它为其他的文字吗，不然多语言切换后只会显示中文

**Comment by chenjiahan** [comment]
这个 issue 里有回复，https://github.com/youzan/vant/issues/4660
