### ISSUE TITLE
[Bug Report] iOS 13 Popup 组件与 Field 组件一起使用时，输入框聚焦后 DOM 不弹起与光标消失

### ISSUE THREAD

**Issue by peng20017** [youzan/vant#4665]
### 设备 / 浏览器
iphone xr

### Vant 版本
2.2.6

### Vue版本
2.6.10

### 重现链接
<a href="https://2phtr.csb.app/" target="_blank">https://2phtr.csb.app/</a>

### 描述问题
Popup组件与Field组件一起使用时，输入框聚焦后DOM不会弹上去，也没有光标出现。

**Comment by peng20017** [comment]
应该是在IOS13下有这个问题，测试了IOS10，没有问题

**Comment by chenjiahan** [comment]
看起来是 iOS 13 的一个 bug，apple developer 有人反馈同样的问题，但暂时没有得到回应

https://forums.developer.apple.com/thread/123967

**Comment by GRJser** [comment]
我遇到了 ios 13.0.0 下,可能出现Diaog 里 点击input ,出现光标,但是没有唤起键盘的问题.

**Comment by eastwillie** [comment]
> 日期组件再ios13系统上嵌入popup也无法显示

我这边也遇到这个问题， 不过应该是ios13的事件机制有变化， 我用的vue， 事件绑定改为@click.native后就好了

**Comment by LLawlight** [comment]
> 看起来是 iOS 13 的一个 bug，transform 元素内无法获取到光标。
> 
> apple developer 有人反馈同样的问题，但暂时没有得到回应：
> https://forums.developer.apple.com/thread/123967

@chenjiahan @peng20017 
感觉跟transform单独的关系不大，因为直接在Popup中使用input是可以正常显示光标的。
根据排查，现在的解决方案就是：在不影响你样式的前提下，将van-cell和van-cell__value的overflow: hideen;改成overflow: visible;即可正常显示光标。

**Comment by peng20017** [comment]
@LLawlight 感谢大佬提供解决方案，经测试，Popup下只有一个Field组件时这种改动可以有效的弹出光标，但是发个一个规律问题，在Field组件上方加入元素，当Field组件被下移到一定位置后，不再显示光标（例如我在Field组件上方加入一个p标签时，仍然能显示光标，让加入两个p标签时，光标又不显示了）。

**Comment by peng20017** [comment]
apple在IOS13.2中修复了我上次说的问题

**Comment by Loserkeys** [comment]
![image](https://user-images.githubusercontent.com/41280598/68008056-8231e200-fcb8-11e9-90d7-1b3f30da6a7f.png)
/deep/.van-popup {
  position: absolute !important;
}
/deep/.van-popup--center {
  transform: unset !important;
  position: fixed !important;
  top: 50%;
  left: 50%;
  margin-left: -40vw;
  margin-top: -50%;
}
两个属性配合使用 可以解决

**Comment by chenjiahan** [comment]
经验证 iOS 13.2 版本已修复这个问题，如果需要兼容 13.0 ~ 13.1 版本的同学，可以参考下上面的方案

**Comment by Kchengz** [comment]
> 日期组件再ios13系统上嵌入popup也无法显示

我也是遇到这个问题

**Comment by cangyu1993** [comment]
我的是在form表单内出现这个问题，怎么解决？

**Comment by hasbug** [comment]
同样遇到，在popup组件用原生input或者Field，IOS13.0就出现没有光标的情况，但可以调起键盘输入内容，但，有时候删除输入内容的时候，删不完。

**Comment by cangyu1993** [comment]
> 同样遇到，在popup组件用原生input或者Field，IOS13.0就出现没有光标的情况，但可以调起键盘输入内容，但，有时候删除输入内容的时候，删不完。
> 尝试user-select: text;-webkit-user-select:text;无果

我是user-select：none造成的，去掉后就行了
