### ISSUE TITLE
[Bug Report] package.json 的 dependencies 的 vue-lazyload 错了

### ISSUE THREAD

**Issue by ctfwren** [youzan/vant#4667]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.6

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/m5v3f" target="_blank">https://codesandbox.io/s/m5v3f</a>

### 描述问题
引用 vue-lazyload 设置错了,package.json 的 dependencies 的 vue-lazyload   :  "vue-lazyload": "1.2.3"  ,  应该是    "@vue/vue-lazyload": "1.2.3"
少了 @vue

**Comment by chenjiahan** [comment]
没有错
https://www.npmjs.com/package/vue-lazyload

**Comment by ctfwren** [comment]
![QQ图片20191010110246](https://user-images.githubusercontent.com/9441374/66535835-8baeab00-eb4d-11e9-81a9-b9b8a092a02a.png)

我的意思是这个位置,通过vue ui 安装的 2.2.6 会提示 vue-lazyload 错误,因为这个位置写错了,应该是 
"@vue/vue-lazyload" : "1.2.3"

**Comment by chenjiahan** [comment]
没有 @vue/vue-lazyload 这个 package

**Comment by ctfwren** [comment]
![QQ图片20191010111055](https://user-images.githubusercontent.com/9441374/66536185-ad5c6200-eb4e-11e9-825e-b20b73668678.png)

你打开这个文件,就看到了

**Comment by chenjiahan** [comment]
建议你先了解一下 npm 包的规则

**Comment by ctfwren** [comment]
耽误你很多时间了,不好意思

我项目们来是  2.2.5的, 看到有2.2.6版本了,我就用那可视化界面, vue ui ,升级了下 2.2.6,编译就提示这 vue-lazyload 错误了,我项目里,安装过 vue-lazyload ,看错误提示,应该是 2.2.6包里的 package.json 里的 节点名字错了,少了  @ vue/,就是我上面发的2个图

**Comment by chenjiahan** [comment]
错误提示可以截图发一下喔
