### ISSUE TITLE
[Bug Report] 动态变更DatetimePicker的min-minute值确认后仍然是变更之前的值

### ISSUE THREAD

**Issue by Yankai17148** [youzan/vant#4668]
### 设备 / 浏览器
所有设备

### Vant 版本
2.0.6

### Vue版本
2.5.22

### 重现链接
<a href="https://codepen.io/yankai17148/pen/NWWqaEr" target="_blank">https://codepen.io/yankai17148/pen/NWWqaEr</a>

### 描述问题
问题重现如下：
第一次点击选择时间正常，第二次选择时间会动态变更min-minute值，此时UI显示正常，但是confirm事件中的value依旧是变更之前的值

**Comment by chenjiahan** [comment]
下个版本会修复此问题

**Comment by nightmaring** [comment]
Vant 版本
2.2.6

Vue版本
2.5.2


描述问题
min-date也一样，动态改变min-date，ui显示正常，v-model绑定的值还是之前的

**Comment by chenjiahan** [comment]
同理

**Comment by nightmaring** [comment]
为你们点赞

**Comment by chenjiahan** [comment]
已在 2.2.7 版本修复
