### ISSUE TITLE
[Proposal] Should use kebab-case props name in templates.

### ISSUE THREAD

**Issue by chuangbo** [youzan/vant#467]
As per vue official style guide https://vuejs.org/v2/style-guide/#Prop-name-casing-strongly-recommended

> Prop names should always use camelCase during declaration, but kebab-case in templates and JSX.

Would like to submit a pull request later if the proposal is accepted.

**Comment by chenjiahan** [comment]
Thanks for your proposal, we decide to follow the official style guide and glad that you can help us 😆

**Comment by chenjiahan** [comment]
Done
