### ISSUE TITLE
[Bug Report] 通过外链形式引入vant，van-swipe报错

### ISSUE THREAD

**Issue by xuejiangjun** [youzan/vant#4670]
### 设备 / 浏览器
Chrome

### Vant 版本
2.2.6

### Vue版本
2.6.10

### 重现链接
<a href="http://dist.xuejiangjun.com/" target="_blank">http://dist.xuejiangjun.com/</a>

### 描述问题
使用外链引入，如cdn，或者放在项目文件夹内，van-swipe-item创建失败，报错TypeError: Cannot read property 'push' of undefined，查看组件源码发现好像是 组件beforeCreate的时候  this.$parent.swipes.push(this);这个this.$parent.swipes没找到，通过npm import不会出现这个问题
![image](https://user-images.githubusercontent.com/16046545/66475339-b0f7d680-eac5-11e9-9a09-667d397e9a1c.png)
代码：
![image](https://user-images.githubusercontent.com/16046545/66475653-5c089000-eac6-11e9-9a5d-9eeb6a560dc3.png)

以上cdn来自于https://youzan.github.io/vant/#/zh-CN/quickstart#fang-shi-si.-tong-guo-cdn-yin-ru

**Comment by xuejiangjun** [comment]
通过vue-cli创建的项目

**Comment by chenjiahan** [comment]
能否提供一下 codesandbox 复现链接

**Comment by xuejiangjun** [comment]
我用codepen写了一下是没问题的，问题就是出在用vue-cli新建项目，然后用cdn引入vant，在空白界面创建swipe。（其他组件好像没发现问题）
![image](https://user-images.githubusercontent.com/16046545/66532682-c3fcbc00-eb42-11e9-84b2-35e8e9b5ba61.png)
总共代码就这些

**Comment by chenjiahan** [comment]
建议自行排查下，另外用 vue-cli 创建项目的话，推荐使用 npm 安装而不是 CDN 引入

**Comment by xuejiangjun** [comment]
很奇怪，以前的项目我都是这样引入没问题，新建的vue-cli这样引入就会有这个问题，看来下你们源码应该是这个没找到
![image](https://user-images.githubusercontent.com/16046545/66532901-a5e38b80-eb43-11e9-92d0-f3a9ffcd1331.png)

**Comment by chenjiahan** [comment]
可以检查下 van-swipe 组件是否正确渲染了

**Comment by xuejiangjun** [comment]
> 可以检查下 van-swipe 组件是否正确渲染了

并没有
![image](https://user-images.githubusercontent.com/16046545/66544979-3766f380-eb6c-11e9-8ad0-68504b73f1c0.png)
