### ISSUE TITLE
Stepper 小数加减的时候出现问题

### ISSUE THREAD

**Issue by fellowT** [youzan/vant#4672]
![image](https://user-images.githubusercontent.com/37097875/66533170-8d27a580-eb44-11e9-8cfc-c2a75a1c5fb7.png)
![image](https://user-images.githubusercontent.com/37097875/66533186-99abfe00-eb44-11e9-83d1-0ce3a885d3f9.png)
![image](https://user-images.githubusercontent.com/37097875/66533197-a2043900-eb44-11e9-8c9b-90eab41c0ba7.png)
当step为小数时，不能加减

**Comment by chenjiahan** [comment]
默认情况下最多支持两位小数，你可以使用 decimal-length 来调整，下个版本我们会优化下

**Comment by fellowT** [comment]
> 默认情况下最多支持两位小数，你可以使用 decimal-length 来调整，下个版本我们会优化下

我现在项目用的1.x版本，没有decimal-length属性

**Comment by chenjiahan** [comment]
已在 2.2.7 版本修复
