### ISSUE TITLE
vant DropdownMenu组件配合better-scroll使用高度不正确问题

### ISSUE THREAD

**Issue by suiyuex** [youzan/vant#4674]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.6

### Vue版本
2.6.10

### 重现链接
<a href="http://abc.com" target="_blank">http://abc.com</a>

### 描述问题
使用下拉框当页面滚动弹出时，下拉框位置不对！因为better-scroll改变了元素的transform属性，下拉框的fixed被限制了！求尽快给一个解决方案！不要时时点击更新top值！

**Comment by chenjiahan** [comment]
可以使用 get-container 挂载到 body 下

**Comment by DemoHu** [comment]
@chenjiahan  遇到了同样的问题，在页面滚动的时候，下拉框的位置不会跟随选择框，挂载到body下没有效果

**Comment by chenjiahan** [comment]
@DemoHu 可以给个 codesandbox 复现链接看看
