### ISSUE TITLE
安装2.2.6版本项目跑起来报错错误如下...

### ISSUE THREAD

**Issue by Daysons** [youzan/vant#4677]
These dependencies were not found:

* vant/es/goods-action-big-btn in ./src/config/vant.config.js
* vant/es/goods-action-big-btn/style in ./src/config/vant.config.js
* vant/es/goods-action-mini-btn in ./src/config/vant.config.js
* vant/es/goods-action-mini-btn/style in ./src/config/vant.config.js

**Comment by chenjiahan** [comment]
参见更新日志，不兼容更新部分

https://youzan.github.io/vant/#/zh-CN/changelog#bu-jian-rong-geng-xin
