### ISSUE TITLE
[Feature Request] DropdownMenu: 支持下拉选中选项与框内显示不同文本

### ISSUE THREAD

**Issue by webliving** [youzan/vant#4678]
### 这个功能解决了什么问题
比如这样的场景：一个商品检索功能，默认时是显示 '商品'，就是全部商品的意思，但下拉里面的选项列表中对应的文本叫 '全部商品'

### 描述您想要的解决方案
通过 computed['displayTitle'] 里的match的选项对象上增加一个类似 label 的字段，以做区分 text 呢？

### 建议的API是什么样的
选项数据增加一个字段即可，取名类似label, title都可以吧

**Comment by chenjiahan** [comment]
可以的，下个版本会支持

**Comment by chenjiahan** [comment]
目前提供的 title 属性可以实现这个需求的

**Comment by webliving** [comment]
> 目前提供的 title 属性可以实现这个需求的

这样要想实现动态变化的标题，可能还需要绑定change事件里做处理才行。是吧？

**Comment by chenjiahan** [comment]
对的，会稍微麻烦一点

**Comment by webliving** [comment]
👌 好吧，先这样用吧
