### ISSUE TITLE
大佬们好， 我们从小程序移植到h5想1rpx=1px postCss基础值设置75 Vant会缩小一倍 请问有全局的地方能控制所有vant样式放大一倍吗

### ISSUE THREAD

**Issue by sc544177047** [youzan/vant#4685]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---大佬们好， 我们从小程序移植到h5想1rpx=1px postCss基础值设置75 Vant会缩小一倍 请问有全局的地方能控制所有vant样式放大一倍吗

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
没有的喔，你可以研究下 postcss 插件，应该能实现
