### ISSUE TITLE
[Bug Report] 官方连接省市区组件无法滚动

### ISSUE THREAD

**Issue by defypro** [youzan/vant#4688]
### 设备 / 浏览器
IOS11,微信7.0.8

### Vant 版本
2.2.6

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html#/zh-CN/" target="_blank">https://youzan.github.io/vant/mobile.html#/zh-CN/</a>

### 描述问题
首次打开无法滑动（但是可以触碰上半部分滑动，滑动结束后无法再次滑动）
进入页面后刷新一下可以正常滑动
已经录制了视频

**Comment by defypro** [comment]
![swdoj-rzyie](https://user-images.githubusercontent.com/22924723/66623343-c7b14100-ec1d-11e9-92b3-660ca5fed1ad.gif)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3015
