### ISSUE TITLE
Pickerz在微信公众号ios上面滑动不友好

### ISSUE THREAD

**Issue by 1292150917** [youzan/vant#4689]
<van-picker
          show-toolbar
          value-key="patientname"
          @cancel="onCancel"
          @confirm="confirm"
          :columns="ofPatient"
        />

这段代码在ios上面 微信公众号里面滑动不友好，划不动 有益处到body的滑动

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
