### ISSUE TITLE
Icon does not align middle when use inline with text

### ISSUE THREAD

**Issue by chuangbo** [youzan/vant#469]
**What is the current behavior?**
Icons align to the top of the text.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**
https://jsfiddle.net/3w4h7poc/3/

**What is the expected behavior?**
Icons align middle.

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
Vant: 0.11.14
Vue: 2.5.13

**Comment by chenjiahan** [comment]
It's a normal behavior of iconfont
