### ISSUE TITLE
注意：配置 babel-plugin-import 插件后，将不允许以这种方式导入组件----这个地方只能不忽略node_modules吗？

### ISSUE THREAD

**Issue by zhengziyun** [youzan/vant#4692]
注意：配置 babel-plugin-import 插件后，将不允许以这种方式导入组件----这个地方只能不忽略node_modules吗？

![image](https://user-images.githubusercontent.com/24427587/66635315-83d03300-ec41-11e9-9be7-c14e1aa698b3.png)

**Comment by chenjiahan** [comment]
没理解你的意思
