### ISSUE TITLE
toast提示问题

### ISSUE THREAD

**Issue by helen1314181** [youzan/vant#4694]
const toast = Toast.loading({
  duration: 0,       // 持续展示 toast
  forbidClick: true, // 禁用背景点击
  loadingType: 'spinner',
  message: '倒计时 3 秒'
});

直接进去这个界面弹出的是不消失的toast提示，但要是一步一步流程走下来的话，弹出的提示有问题(直接把里面的内容输出来了)：
![image](https://user-images.githubusercontent.com/54263159/66643257-e846be80-ec50-11e9-8572-613189db9a25.png)

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
