### ISSUE TITLE
[Bug Report] 2.2.5 tabbar能不能实现这个样式？

### ISSUE THREAD

**Issue by snowdream** [youzan/vant#4695]
### 设备 / 浏览器
iphone/chrome

### Vant 版本
2.2.5

### Vue版本
2.5.2

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tabbar" target="_blank">https://youzan.github.io/vant/#/zh-CN/tabbar</a>

### 描述问题
tabbar能不能实现这个样式？

![tabbar](https://static.dingtalk.com/media/lALPDgQ9rGJDiVHNBxLNBDg_1080_1810.png_620x10000q90g.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%221790561%3A1790561%22%2C%22msgId%22%3A%221707041995665%22%7D&open_id=1790561)

**Comment by chenjiahan** [comment]
中间的『发布』样式需要自行实现，然后放到 tabbar-item 的中间即可
