### ISSUE TITLE
[Bug Report] toast提示有问题

### ISSUE THREAD

**Issue by helen1314181** [youzan/vant#4696]
### 设备 / 浏览器
谷歌

### Vant 版本
2.2.7

### Vue版本
2.6.10

### 重现链接
<a href="http://172.31.40.104:8080/#/home" target="_blank">http://172.31.40.104:8080/#/home</a>

### 描述问题
const toast = Toast.loading({
duration: 0, // 持续展示 toast
forbidClick: true, // 禁用背景点击
loadingType: 'spinner',
message: '倒计时 3 秒'
});

直接进去这个界面弹出的是不消失的toast提示，但要是一步一步流程走下来的话，弹出的提示有问题(直接把里面的内容输出来了)：

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接
