### ISSUE TITLE
使用Field 输入框，弹起键盘，安卓会页面缩小一下；关闭键盘，页面又缩小一下

### ISSUE THREAD

**Issue by xiabuyuanyu** [youzan/vant#4697]
<van-field v-model.trim="orderData.receiver" label="姓名" placeholder="请输入姓名" class="f30 f333 pt30 pb30 bborder" :border="false" clearable/>
使用Field 输入框，弹起键盘，安卓手机会页面缩小一下；关闭键盘，页面又缩小一下

**Comment by defypro** [comment]
是否使用了REM？

**Comment by defypro** [comment]
以前我也遇到过，是因为使用了REM并且在onresize中根据页面大小变化后重新设置font-size导致页面元素宽高发生改变，因为安卓手机唤起键盘页面宽高会发生改变。楼主如果不是请忽略。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by xiabuyuanyu** [comment]
@defypro 太感谢你了，终于找到问题了
