### ISSUE TITLE
[Bug Report] utils/router.js：Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by sninwo** [youzan/vant#4703]
### 设备 / 浏览器
Chrome

### Vant 版本
2.2.7

### Vue版本
2.6.10

### 重现链接
<a href="https://keyike.ltd/kesurong/" target="_blank">https://keyike.ltd/kesurong/</a>

### 描述问题
点击底部“我的”标签页，查看控制台。
开发环境的报错：
rejection error TypeError: Cannot read property 'name' of undefined
    at eval (webpack-internal:///./node_modules/vant/es/utils/router.js:19:17)

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.2.8 版本修复
