### ISSUE TITLE
[Bug Report] DatetimePicker时间选择组件导致网页窗口假死

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#4705]
### 设备 / 浏览器
Chrome

### Vant 版本
2.2.7

### Vue版本
2.6.10

### 重现连接

https://codesandbox.io/s/vant-issue-moban-l3y0p

### 描述问题
DatetimePicker时间选择组件刚开始正常使用，但是拖动一次过后会导致网页窗口卡死问题。回退到2.2.7以下版本不会出现这种问题

**Comment by chenjiahan** [comment]
哥们儿，提了这么多次 issue 了，记得把复现的 codesandbox 链接贴上

**Comment by OnlyLady** [comment]
> 哥们儿，提了这么多次 issue 了，记得把复现的 codesandbox 链接贴上

https://codesandbox.io/s/vant-issue-moban-l3y0p

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3046
