### ISSUE TITLE
提个小建议，所有props中参数不要定义成number,建议添加string，这样在做VW适配的时候更灵活

### ISSUE THREAD

**Issue by 531431988** [youzan/vant#4707]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

如题，这样就不会全局设置成VW适配后，不会因为部分传参默认设置的PX单位受影响
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/66724867-8909c980-ee5d-11e9-9ae0-965ba928db27.png)
props 只能传Number类型所以这种Px的单位和VW匹配有问题，目前只能通过css覆盖解决

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3305

**Comment by 531431988** [comment]
一看就是没看懂我的意思，全局所有的样式都通过VW转换做了适配，现在只有能过props传入的要求只能传入number的没有做到转换，所以我只能通过！important覆盖，是不是应该考虑props入参类型同时支持 number string

**Comment by chenjiahan** [comment]
上面的 issue 里说的很清楚了，没法支持其他单位
