### ISSUE TITLE
多张图片上传不支持吗？返回值只有一个file

### ISSUE THREAD

**Issue by hqqxxf** [youzan/vant#471]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@hqqxxf 目前不支持，我们会在后续优化

**Comment by chenjiahan** [comment]
已在 0.11.15 版本中支持，使用 `multiple` 属性即可
