### ISSUE TITLE
定制主题报错

### ISSUE THREAD

**Issue by jone8881** [youzan/vant#4710]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.7

### Vue版本
2.6.10

### 重现链接
<a href="http://localhost:8080/#/component/button-demo" target="_blank">http://localhost:8080/#/component/button-demo</a>

### 描述问题
您好：
我以这种方式
@import '~vant/lib/index.less';
@import './variable.less';
修改变量值重新定义主题，报错信息如下
Module build failed: 

@toast-border-radius: 4px;
@toast-background-color: rgba(@text-color, .88);
                       ^
Error evaluating function `rgba`: color functions take numbers as parameters
      in /Users/renliangqiong/worker/组件库/组件工程/component-mobile/node_modules/vant/lib/style/var.less (line 308, column 25)
 @ ./themes/default/src/index.less 2:14-137
 @ ./doc/mobile/main.js
麻烦解答下这是什么原因谢谢，链接暂无抱歉

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4565
