### ISSUE TITLE
[Bug Report] uploader上传图片，在安卓多开的多开微信里上传不了

### ISSUE THREAD

**Issue by lisun0459** [youzan/vant#4713]
### 设备 / 浏览器
安卓用户使用多开微信的情况下（小米，华为，三星等都出现该情况）

### Vant 版本
1.6.20

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/mobile" target="_blank">https://youzan.github.io/vant/mobile</a>

### 描述问题
uploader上传图片在用户安卓微信多开的情况下，多开的微信环境里上传图片上传不成功，拍照，选图都上传不了，似乎是拿不到图。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4103 微信分身本是不支持图片上传的
