### ISSUE TITLE
输入框类型为密码

### ISSUE THREAD

**Issue by liyuhong1998** [youzan/vant#4716]
输入框类型为密码时，第一次输入可视按钮能展示，点击能展示出密码的明文信息。当密码输入框失去聚焦之后，再继续输入，可视按钮就不再展示无法查看密码的明文信息
官网地址的文本框例子就是这样 
https://youzan.github.io/vant/#/zh-CN/field

**Comment by chenjiahan** [comment]
可视按钮是？

**Comment by liyuhong1998** [comment]
就是这个按钮

 



------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年10月14日(星期一) 下午4:42
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "夏凉"<849172809@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] 输入框类型为密码 (#4716)




可视按钮是？

**Comment by chenjiahan** [comment]
图片没传上来

**Comment by liyuhong1998** [comment]
![image](https://user-images.githubusercontent.com/56462321/66739252-e83dfd00-eea2-11e9-8c27-a5503529b854.png)
@chenjiahan

**Comment by liyuhong1998** [comment]
有QQ或者微信吗？我截图发给您。
 



------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年10月14日(星期一) 下午4:48
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "夏凉"<849172809@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] 输入框类型为密码 (#4716)




图片没传上来

**Comment by chenjiahan** [comment]
这是什么浏览器，是手机端吗

**Comment by liyuhong1998** [comment]
Edge浏览器

**Comment by chenjiahan** [comment]
首先 vant 是移动端组件库，不会特意适配 PC 端浏览器

其次这个明文功能是浏览器实现的，我们也无法控制
