### ISSUE TITLE
van-swipe轮播会导致 使用fixed的元素内容滑动

### ISSUE THREAD

**Issue by rufeng2015** [youzan/vant#4719]
设备 / 浏览器
Chrome

Vant 版本
2.2.7

Vue版本
2.6.10

问题描述
我使用swipe轮播功能，底部有一个积分兑换功能是用fixed写的，但是swipe功能会导致fixed元素内的文字在切换图片的时候上下浮动一下，请问该如何解决

代码 

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <!-- 引入样式文件 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vant@2.2.7/lib/index.css">

  <!-- 引入 Vue 和 Vant 的 JS 文件 -->
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vant@2.2.7/lib/vant.min.js"></script>
  <style>
    .goods_footer {
      position: fixed;
      width: 100%;
      height: 50px;
      line-height: 50px;
      color: #fff;
      font-size: 16px;
      text-align: center;
      background: rgba(104, 99, 255, 1);
    }
  </style>
</head>

<body>
  <div id="app">
    <van-swipe :autoplay="3000">
      <van-swipe-item v-for="(image, index) in images" :key="index">
        <van-image :src="image" />
      </van-swipe-item>
    </van-swipe>
    <div class="goods_footer">马上兑换</div>
  </div>
  <script>
    new Vue({
      el: '#app',
      data() {
        return {
          images: [
            'https://img.yzcdn.cn/vant/apple-1.jpg',
            'https://img.yzcdn.cn/vant/apple-2.jpg'
          ],
        }
      },
    });
  </script>
</body>

</html>
```

问题图片

![image](https://user-images.githubusercontent.com/14096175/66744131-399fb980-eeae-11e9-8910-f322d7781f0e.png)

**Comment by chenjiahan** [comment]
transform 元素内是不能使用 fixed 元素的，而且从布局上来说 Swipe 组件内也不应该嵌套 fixed 的元素

**Comment by rufeng2015** [comment]
> transform 元素内是不能使用 fixed 元素的，而且从布局上来说 Swipe 组件内也不应该嵌套 fixed 的元素

按你的解释,如果存在transform 样式的页面，不用使用fixed吗？   另外如果要使用该如何解决

**Comment by chenjiahan** [comment]
Chrome 上，transform 元素内部的 fixed 会变成 absolute，这个是浏览器本身的机制，

解决方法就是避免把 fixed 元素放在内部，因为 fixed 元素本就不依赖父元素的布局

**Comment by rufeng2015** [comment]
> Chrome 上，transform 元素内部的 fixed 会变成 absolute，这个是浏览器本身的机制，
> 
> 解决方法就是避免把 fixed 元素放在内部，因为 fixed 元素本就不依赖父元素的布局

我不是很明白你的意思，但是我按你们网站商品导航的样式写出来， 谢谢你们的框架。

**Comment by rufeng2015** [comment]
> Chrome 上，transform 元素内部的 fixed 会变成 absolute，这个是浏览器本身的机制，
> 
> 解决方法就是避免把 fixed 元素放在内部，因为 fixed 元素本就不依赖父元素的布局

解决问题的办法是fixed内部使用absolute,设置top:3px就可以了。具体为什么这样做我不是很清楚。
