### ISSUE TITLE
[Bug Report] uploader在安卓手机微信中频繁点击，会无法选择图片

### ISSUE THREAD

**Issue by 592192890** [youzan/vant#4725]
### 设备 / 浏览器
android

### Vant 版本
2.0.8

### Vue版本
2.5.22

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-ujw7f" target="_blank">https://codesandbox.io/s/vant-issue-moban-ujw7f</a>

### 描述问题
使用android手机中的微信访问，可以频繁的点击文件上传组件，导致选择图片时，依然让用户继续选择图片

**Comment by chenjiahan** [comment]
连续点击的情况无法避免喔，这里的行为是系统决定的
