### ISSUE TITLE
[Feature Request] stepper根据小数位数限制输入

### ISSUE THREAD

**Issue by liubin595338764** [youzan/vant#4726]
### 这个功能解决了什么问题
现在是用户输入完离开输入框之后，stepper组件再根据decimal-length小数位数处理用户输入的数字，从用户体验来说，我们尽量少的修改用户自己输入好的内容，他可能没有注意到自己的输入被更改了，所以我们可以限制用户输入比较合适。

### 描述您想要的解决方案
stepper能否根据小数位数限制输入，比如decimal-length设置为2，那么用户在输入框输入的时候就只能输入0.12，而不能输入0.123；

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
可以的，下个版本会优化掉

**Comment by chenjiahan** [comment]
已在 2.2.8 版本优化
