### ISSUE TITLE
[Feature Request] vue滚动tab跟随切换效果

### ISSUE THREAD

**Issue by earthaYan** [youzan/vant#4727]
### 这个功能解决了什么问题
vue滚动tab跟随切换效果

### 描述您想要的解决方案
能够实现淘宝详情页类似的vue滚动tab跟随切换的效果

### 建议的API是什么样的
希望在tab组件中，添加参数，可以使得上下滚动

**Comment by chenjiahan** [comment]
暂无计划支持喔
