### ISSUE TITLE
[Bug Report] iphoneXR,在有弹出键盘的页面使用Dialog.confirm，会出现按钮点击区域偏移问题

### ISSUE THREAD

**Issue by zelong-lin** [youzan/vant#4729]
### 设备 / 浏览器
iphoneXR，软件版本12.2，微信浏览器，微信版本是7.0.8

### Vant 版本
1.1.9

### Vue版本
2.6.10

### 描述问题
iphoneXR,软件版本12.2，微信浏览器，微信版本是7.0.8，微信浏览器在有弹出键盘的页面使用Dialog.confirm，会出现按钮点击区域偏移问题，点不到按钮，点击区域居然在按钮上方，我测试之后发现主要出现原因是因为ios键盘的弹出导致这个bug

**Comment by chenjiahan** [comment]
最新版有做兼容处理，可以升级试下

**Comment by zelong-lin** [comment]
项目原因升级会有一些问题，有什么可以兼容吗

**Comment by chenjiahan** [comment]
建议参考更新日志进行升级，重点关注『不兼容更新』内容

**Comment by shoyuf** [comment]
> 最新版 vant 有做兼容处理，可以升级试下

有相关的 commit 可以参考一下吗？
