### ISSUE TITLE
[Bug Report] sliderbar 在ios端上下滑动内容会出现空白

### ISSUE THREAD

**Issue by iyaq** [youzan/vant#4731]
### 设备 / 浏览器
ios系统版本13不兼容

### Vant 版本
2.2.0

### Vue版本
2.5.22

### 重现链接
<a href="http://corp.yinhangren.cn/#/yh" target="_blank">http://corp.yinhangren.cn/#/yh</a>

### 描述问题
项目需要下载“企业微信”跑，页面左侧是Sidebar 侧边导航，导航内容是31个城市（有滚动条），往上滑动导航下面空白，往下拉导航，上面部分空白。在导航空白处随便点一下，导航又显示全了，在android机和比较低版本12的ios系统正常。

**Comment by chenjiahan** [comment]
提供的链接无法正常打开，接口有报错
