### ISSUE TITLE
[Feature Request] 希望在Tag可以加入关闭的选项

### ISSUE THREAD

**Issue by jvhuaxia** [youzan/vant#4736]
### 这个功能解决了什么问题
可以很直观的显示出这个tag是可以点击取消的

### 描述您想要的解决方案
希望可以加入类似于iviewui Tag这样的可以点击关闭的属性 https://www.iviewui.com/components/tag

### 建议的API是什么样的
加入closable属性 在右侧显示关闭的X

**Comment by chenjiahan** [comment]
已在 2.2.9 版本支持
