### ISSUE TITLE
吸顶功能在组件显示隐藏的时候错位(旧issue未修复)

### ISSUE THREAD

**Issue by Klozee** [youzan/vant#4737]
设备 / 浏览器

safari/chrome

Vant 版本

2.0.8 - 2.2.7

Vue版本

2.5.2

重现链接

https://codesandbox.io/s/vant-issue-moban-pnwuq

描述问题

我们有一个通讯录切换显示类型的功能,两个组件之间切换显示隐藏后,显示的组件的最后一个元素吸顶.已提供重现.

**Comment by chenjiahan** [comment]
两个组件之间切换时请使用 v-if 而不是 v-show

如果使用 v-show，会在一开始就创建一个隐藏的 IndexBar，导致计算错误
