### ISSUE TITLE
imagePreview 轻触之后就直接关闭

### ISSUE THREAD

**Issue by DevaloperHH** [youzan/vant#4738]
设置了 :close-on-click-overlay="false"但是没有作用
 在轻触 遮罩层和图片的时候都会关闭 预览
```
<van-image-preview v-model="show"
                           :overlay="true"
                           :close-on-click-overlay="false"
                           :start-position="startIndex"
                           :images="images"
                           maxZoom="10"
                           @change="onChange">
            <template v-slot:index>
                <van-button @touchstart="read(index)">
                    查看原图
                </van-button>
            </template>

        </van-image-preview>
```

**Comment by chenjiahan** [comment]
ImagePreview 并没有提供 close-on-click-overlay 属性呢

**Comment by DevaloperHH** [comment]
> ImagePreview 并没有提供 close-on-click-overlay 属性呢

![image](https://user-images.githubusercontent.com/38316554/66886578-649f2000-f00a-11e9-8871-2d8adffa4a19.png)
我看源码里面有呀

**Comment by DevaloperHH** [comment]
> ImagePreview 并没有提供 close-on-click-overlay 属性呢
大佬 我想要实现的是 点击按钮查看原图 在预览的时候  但是现在一轻触就 关闭了  所以才有这个问题

**Comment by chenjiahan** [comment]
源码里的这个 close-on-click-overlay 是无用属性，后续会移除掉

目前版本里，你可以添加一个 @touchend.stop 来防止关闭

后续会对这块优化下

```html
<van-button @touchstart="read(index)" @touchend.stop>
  查看原图
</van-button>
```

**Comment by DevaloperHH** [comment]
> 源码里的这个 close-on-click-overlay 是无用属性，后续会移除掉
> 
> 目前版本里，你可以添加一个 @touchend.stop 来防止关闭
> 
> 后续会对这块优化下
> 
> ```
> <van-button @touchstart="read(index)" @touchend.stop>
>   查看原图
> </van-button>
> ```

十分感谢 我试一下

**Comment by xiaoForest** [comment]
你好，这个，怎么阻止轻触关闭预览呀，
 @touchend.stop 我加了，貌似没用

**Comment by DevaloperHH** [comment]
> 

这个问题很久了  已经忘了 @xiaoForest

**Comment by xiaoForest** [comment]
> > 
> 
> 这个问题很久了 已经忘了 @xiaoForest

我现在是组件调用的这个功能，看了异步的关闭的确好用，但我是组件调用那个
这个是我的提问 感谢
https://github.com/youzan/vant/issues/10444
