### ISSUE TITLE
popup van-area 使用后， 再用 popup与picker一起使用报错

### ISSUE THREAD

**Issue by lejiu** [youzan/vant#4740]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

报错
vue.min.js:6 TypeError: Cannot read property '_wrapper' of undefined
不知道是不是我的原因，搞不懂

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
