### ISSUE TITLE
[Bug Report] 环形进度条渐变色问题

### ISSUE THREAD

**Issue by luffyli** [youzan/vant#4742]
### 设备 / 浏览器
Chrome 77.0.3865.120

### Vant 版本
2.2.7

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-8efw2?fontsize=14" target="_blank">https://codesandbox.io/s/vant-issue-moban-8efw2?fontsize=14</a>

### 描述问题
渐变色不是按指定进度从进度的0%渐变到100%，而是从右到左渐变

**Comment by chenjiahan** [comment]
目前是存在这个问题的，暂时没找到合适的修复方式

**Comment by huangysss** [comment]
可否使用这个方法：
用两个半圆做渐变，连接处使用个过渡色块处理。

**Comment by chenjiahan** [comment]
@huangysss 欢迎 PR~

**Comment by huangysss** [comment]
@chenjiahan 尝试了一下，可以达到这样的效果（并未使用过渡）：
![企业微信截图_20191223175924](https://user-images.githubusercontent.com/31810070/71351328-5fcc8e80-25ae-11ea-9235-acc8a6060f8b.png)
但是如果要解决这个issue的话需要比较长的时间。

**Comment by chenjiahan** [comment]
@sylvaner-h 可以描述下具体的实现方式不，是否具有通用性

**Comment by sylvaner-h** [comment]
@chenjiahan 
原理是两个半圆作垂直方向的渐变，[参考了这个](https://www.zhangxinxu.com/study/201710/colorful-time-count-down-svg-circle.html)
需要在组件内部计算50%处的颜色值。
通用性会存在以下问题
1. 底部连接处并不是无缝渐变，某些情况下会出现明显色差，
```JS 
{'49%': '#FFF', '51%': '#000'}
```
2. 如果存在透明度渐变，如```{'0%': 'rgba(0,0,0,1)', '100%': 'rgba(0%, 0%, 0%, 0)'}```，```stroke-linecap```必须为```butt```；
3. 涉及计算，```{'0%': 'red'}```的这种写法是无效的。

**Comment by chenjiahan** [comment]
噢噢，明白了，那这种方式还是有一定的缺陷，暂时不太适合拿来解决当前的问题

**Comment by chenjiahan** [comment]
这个问题没有找到合适的解决方法，先 close 咯
