### ISSUE TITLE
能不能把右边示例完整的代码贴出来呢，比如这个骨架屏，右边的实例没有源码啊

### ISSUE THREAD

**Issue by mrmyn** [youzan/vant#4744]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by mrmyn** [comment]
https://youzan.github.io/vant/#/zh-CN/skeleton

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/blob/dev/src/skeleton/demo/index.vue
