### ISSUE TITLE
Dialog的回调里触发不了挂载到window上的方法

### ISSUE THREAD

**Issue by qimiaojiyihou** [youzan/vant#4745]
![bc33aa8238eee2316e7c81f0f7f77d0](https://user-images.githubusercontent.com/43678058/66896835-4c3dfe00-f028-11e9-8102-287cc68593de.png)
这两个与app交互的方法都无法触发，点击确定遇到这两个方法直接跳到取消的回调中。

**Comment by chenjiahan** [comment]
这个问题与 Dialog 无关，请确认你正确挂载了可访问的方法

**Comment by qimiaojiyihou** [comment]
> 这个问题与 Dialog 无关，请确认你正确挂载了可访问的方法

![0ceb38f981fe8bad8e66af1e38f0f6d](https://user-images.githubusercontent.com/43678058/66897465-a55a6180-f029-11e9-9d37-35abf345b827.png)
将调用放在dialog外可执行，所以才想是不是dialog里有什么阻止了

**Comment by chenjiahan** [comment]
Dialog 不会影响外部的函数喔

**Comment by qimiaojiyihou** [comment]
好吧，我再找找问题，谢谢
