### ISSUE TITLE
[Bug Report] van-radio-group选择延迟

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#4749]
### 设备 / 浏览器
ios/ Safari浏览器

### Vant 版本
2.2.7

### Vue版本
2.6.10

### 重现链接
<a href="http://mp.jbf.aijk.net/casher/index.html#/test" target="_blank">http://mp.jbf.aijk.net/casher/index.html#/test</a>

### 描述问题
van-radio-group在第一次进入页面的时候。选择正常，点击立即付款跳转到百度，然后返回，点击选择radio不生效

![image](https://user-images.githubusercontent.com/21211777/66906949-1bb38f80-f03b-11e9-9865-08e220a3f218.png)

**Comment by Thlq** [comment]
iphoeX   13.1.3

**Comment by chenjiahan** [comment]
试了下没复现，用的 iOS 13.1.2

**Comment by Thlq** [comment]
苹果X试下，麻烦了，谢谢

**Comment by chenjiahan** [comment]
可以再详细描述下么，或者给个 codesandbox 复现链接

**Comment by Thlq** [comment]
codesandbox ：https://codesandbox.io/s/vant-issue-moban-jk68u
我网络不好，codesandbox一直跑不出来，不知道有没有写错的
我再提供一份百度云视频
第一次进入页面的时候点击radio都是正常的，然后点击按钮到百度页面，然年返回回来，点击按钮就不渲染了，打开console看到数据更新了，点及console的那一刻可以看到试图才更新
链接: https://pan.baidu.com/s/14AE2LveeZuOFWhM_9LG6pg 提取码: wj9k

**Comment by chenjiahan** [comment]
看起来是 safari 的 bug，iOS 13 bug 挺多的

**Comment by Thlq** [comment]
我在微信浏览器来回多试几次，也会出现这个问题， safari 浏览器出现的概率最高

**Comment by Thlq** [comment]
我在页面上设置一个div显示选中的radio的modal，发现点击的时候div里面的视图是正常更新，但是radio标签没有正常渲染视图

**Comment by Thlq** [comment]
可能radio组件有些兼容问题，我记用css写radio在 safari可以正常显示

**Comment by Thlq** [comment]
麻烦，问下，这个问题后期会跟踪修复吗？谢谢啦

**Comment by chenjiahan** [comment]
抱歉这是浏览器的渲染 bug，暂时没有解决方法

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4887
