### ISSUE TITLE
引入失败

### ISSUE THREAD

**Issue by jsgr** [youzan/vant#475]
vue.esm.js?a915:574 [Vue warn]: Error in render: "TypeError: Cannot read property 'undefined' of undefined"
找不到组件，以及按照官网的方法引入了，就是报错。123三种方法都试了

**Comment by chenjiahan** [comment]
@jsgr 麻烦提供更详细的报错信息，或者对应的 jsfiddle 链接

**Comment by jsgr** [comment]
就是 提示组件无效啊，不能识别 组件

**Comment by chenjiahan** [comment]
@jsgr 这样的描述我没法定位问题噢，建议你先 check 下项目配置，或者打几个 log

**Comment by jsgr** [comment]
好的，具体信息，我待会试下。待会再给你反馈

**Comment by jsgr** [comment]
我试了其他组件，都正常就 城市选择器组件无法使用，我是通过vue-cli项目初始化的。

**Comment by chenjiahan** [comment]
@jsgr 未能复现你的问题，建议将 vant 升级到最新版再试

**Comment by jsgr** [comment]
"vant": "^0.11.14", 最新版本

**Comment by chenjiahan** [comment]
@jsgr 麻烦提供 jsfiddle 或者能复现的仓库

**Comment by jsgr** [comment]
@chenjiahan 
 城市选择组件终于可以使用，我删除 node_modules 文件夹，重新安装依赖就可以了。这就有点尴尬了。
有个疑问就是 时间选择组件为什么没有  秒，只能  年-月-日 时:分  这样子。这个是什么原因呢？

**Comment by chenjiahan** [comment]
@jsgr 时间选择秒数的情况比较少见，所以我们目前没有作支持噢

**Comment by jsgr** [comment]
@chenjiahan  目前就是有这个需求，需要精确到秒，请问有什么方法，可以在此基础上增加秒这个选择么？

**Comment by chenjiahan** [comment]
@jsgr 目前不太好扩展噢，你可以基于 Picker 组件去实现一个，DatetimePicker 也是基于 Picker 组件做的

**Comment by jsgr** [comment]
好的
