### ISSUE TITLE
checkbox的change事件无效

### ISSUE THREAD

**Issue by Ellen0604** [youzan/vant#4750]
设备 / 浏览器
IPad  IOS13.1.3

Vant 版本
2.2.2

Vue版本
2.5.22

描述问题
谷歌浏览器正常使用
IPad  IOS13.1.3点击无效
checkbox 使用了label-disabled 点击无反应  是否需要加click事件
![image](https://user-images.githubusercontent.com/24667299/66971436-cff8f880-f0c3-11e9-8ddb-10dd37eb3627.png)

使用change事件也无反应
![image](https://user-images.githubusercontent.com/24667299/66971378-93c59800-f0c3-11e9-89a9-6fdf3326eaf7.png)

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接
