### ISSUE TITLE
微信小程序原生 组件调用vant-dialog时,before-close属性怎么写

### ISSUE THREAD

**Issue by 741912526** [youzan/vant#4751]
微信小程序原生 组件调用vant-dialog时,before-close属性怎么写
//wxml
<van-dialog
      use-slot
      title="请填写咨询内容"
      show="{{ show }}"
      show-cancel-button
      before-close="{{beforeclose}}"
    >
    </van-dialog>

//js
beforeclose(action, done) {
    if (action === 'confirm') {
      setTimeout(done, 1000)
    } else if (action === 'cancel') {
      done() //关闭
    }
  }
上面代码写在Page({data{}})  里面？

**Comment by 741912526** [comment]
//wxml
<van-dialog
      use-slot
      show="{{ show }}"
      show-cancel-button
      before-close="beforeclose"
    >
    </van-dialog>

**Comment by chenjiahan** [comment]
小程序问题请到 vant-weapp 仓库提问，感谢配合
