### ISSUE TITLE
[Feature Request] Tab标签页使用sticky粘性定位布局属性时，如果内容是本来就是在顶部的，粘性布局无效，只有设置了offset-top=1时才有效

### ISSUE THREAD

**Issue by xiaofuliang** [youzan/vant#4754]
### 这个功能解决了什么问题
Tab标签页使用sticky粘性定位布局属性时，如果内容是本来就是在顶部的，粘性布局无效，只有设置了offset-top=1时才有效，但是这个时候会有1px的空隙

### 描述您想要的解决方案
无

### 建议的API是什么样的
希望不用设置offset-top =1时，也会定位在顶部

**Comment by chenjiahan** [comment]
如果元素本来就在顶部，为什么还需要粘性布局呢，能否给个复现链接看下是什么场景

**Comment by xiaofuliang** [comment]
我现在是tab页是在顶部，但是我每一个tab是列表，内容滚动时，tab页也会往上滚动，不会固定在顶部，只要设置了offset-top大于0就会固定在顶部了

**Comment by chenjiahan** [comment]
我试了下没这个问题耶，能提供下 codesandbox 复现链接么

**Comment by nightmaring** [comment]
我也出现了tab在顶部启用sticky无效的情况，
当offset-top = 1时有效
研究了一下，发现我的项目设置了
html, body{height:100%;overflow: auto;}
而sticky中获取的是window的scrollTop,
导致fixed判断出现问题，从而sticky无效，
写给后来人警示下吧

**Comment by Colinhongle** [comment]
> 我也出现了tab在顶部启用sticky无效的情况，
> 当offset-top = 1时有效
> 研究了一下，发现我的项目设置了
> html, body{height:100%;overflow: auto;}
> 而sticky中获取的是window的scrollTop,
> 导致fixed判断出现问题，从而sticky无效，
> 写给后来人警示下吧

我也是写了这个属性html, body{height:100%;overflow: auto;}就不行了，不知道有什么解决办法

**Comment by Colinhongle** [comment]
offset-top =1时设置下css  .van-sticky--fixed{ top: 0px!important; }能解决，但是不能加animated属性，会有其他问题

**Comment by xiaofuliang** [comment]
@nightmaring 是的，后来我也发现设置body {height:100,iverflow:auto}是会有问题
