### ISSUE TITLE
页面卡死,导致chrome无法关闭的问题

### ISSUE THREAD

**Issue by JustGogoing** [youzan/vant#4756]
环境
chrome 77  win
vant 2.2.7
vue@cli3
ts 3.4.3

在使用DatetimePicker组件时 
`
<datetime-picker
        v-model="birthday"
        type="date"
        :max-date="new Date()"
        :min-date="minDate"
      />
private birthday = ''
  private minDate = new Date(1900, 1, 1)
`

滚动日期中的年 直接该tab页面卡死, chrome无法关闭, 但是可以打开其他页面

同样的问题之前在 mac环境的chrome safri 也发生过 是 项目运行后 f12进入调试环境 界面从pc变为手机时, 无法刷新

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3046
