### ISSUE TITLE
[Bug Report]Progress组件在v-show里渲染后无法显示进度

### ISSUE THREAD

**Issue by zswek** [youzan/vant#4757]
以下代码复现
<pre>
&lt;template&gt;
  &lt;div id="app" v-show="show"&gt;
    &lt;van-progress :percentage="50" /&gt;
  &lt;/div&gt;
&lt;/template&gt;

&lt;script&gt;
export default {
  name: 'App',
  data () {
    return {
      show: false
    }
  },
  mounted() {
    this.show = true;
  }
}
&lt;/script&gt;

&lt;style&gt;
&lt;/style&gt;

</pre>

**Comment by chenjiahan** [comment]
下个版本会兼容下

**Comment by bolechen** [comment]
今天在项目中发现用 NoticeBar 的时候，如果加了 v-show 就会不能自动滚动，搜索到这里，猜测是同样的问题，在业务场景下又不用用 v-if，有没有好的解决方法？比如在 v-show 以后做一个回调处理？谢谢 @chenjiahan

**Comment by chenjiahan** [comment]
@bolechen 组件内部无法监听到 v-show 的变化。。
