### ISSUE TITLE
popup 控件引起的滚动异常

### ISSUE THREAD

**Issue by yajore** [youzan/vant#476]
**What is the current behavior?**
页面引用了popup选择sku，直接跳转到下单页面，之后其他的页面在安卓手机上滚动就诡异了，
在浏览器上滚动时有大量警告

index.js?ff82:90 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

popup manage  
watchTouchMove
中的代码异常
```js
 if (status !== '11' && isVertical && !(parseInt(status, 2) & parseInt(direction, 2))) {
        e.preventDefault();  // 这里
        e.stopPropagation();
      }
```
在新的路由页面，之前popup组件注册的事件好像没有销毁，还在继续监听touchstart ,touchmove
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@yajore 感谢反馈，目前确实存在这个问题，将在下个版本修复

**Comment by chenjiahan** [comment]
已在 0.11.15 中修复此问题
