### ISSUE TITLE
[Bug Report] Tab组件的ellipsis=false 不生效

### ISSUE THREAD

**Issue by lily9988** [youzan/vant#4761]
### 设备 / 浏览器
ios 12.4

### Vant 版本
2.2.7

### Vue版本
2.6.10

### 重现链接
<a href="https://ddq2p.csb.app/" target="_blank">https://ddq2p.csb.app/</a>

### 描述问题
Tab组件的ellipsis=false 不生效,tab导航文字还是出现点点点.同时 line-width 和 line-height 也不生效。不知是否是我的写法有问题，麻烦解答一下。

**Comment by chenjiahan** [comment]
```html
<van-tabs :ellipsis="false" />
```

ellipsis 前面要加冒号，才能传递 boolean，否则传递的是 string

**Comment by Leslie-Wong-H** [comment]
那vant-weapp中呢？

**Comment by Leslie-Wong-H** [comment]
<van-tabs sticky animated swipeable ellipsis="false" > ellipsis无效，设置成  :ellipsis 也一样，还是会出现省略号

**Comment by Leslie-Wong-H** [comment]
```
<van-tabs sticky animated swipeable ellipsis="false">
```
