### ISSUE TITLE
[Feature Request] 大佬问个问题，v-html="content" content 里的img如何实现懒加载

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#4765]
### 这个功能解决了什么问题
大佬问个问题，v-html="content" content 里的img如何实现懒加载

### 描述您想要的解决方案
搜了搜资料没找到处理方法~

### 建议的API是什么样的
我就问问，不方便回答可以直接关闭~

**Comment by chenjiahan** [comment]
这种情况的话，可以找一些与框架无关的 Lazyload 库去实现懒加载

**Comment by anihCevol** [comment]
好的，打扰了。
