### ISSUE TITLE
[Bug Report] 使用tab标签页时候input输入框无法获取光标

### ISSUE THREAD

**Issue by wangyong991** [youzan/vant#4770]
### 设备 / 浏览器
iphone7Plus 13.1.2

### Vant 版本
2.2.1

### Vue版本
2.5.20

### 重现链接
<a href="http://ullget-staging.oss-cn-shanghai.aliyuncs.com/sales/96/vanttab.mp4" target="_blank">http://ullget-staging.oss-cn-shanghai.aliyuncs.com/sales/96/vanttab.mp4</a>

### 描述问题
使用tab标签页的时候，在标签1和标签2内同时使用input输入框或者field表单。iphone7Plus 13.1.2版本，点击第一个标签内表单时候能唤起键盘并显示光标，而且当前点击的表单会滚动到键盘上面（不会被键盘遮挡）；切换到第二个标签，点击第二个标签内表单，能唤起键盘，但是不显示光标，而且输入区域会被键盘遮挡，滑动页面也无法滑动。但是使用另一个iphone7Plus 11.2.5,点击第一个和第二个标签内的表单，表现形式一样，都能唤起键盘，显示光标，当前输入区域弹起（不会被键盘遮挡）

**Comment by chenjiahan** [comment]
跟这个是同个问题，https://github.com/youzan/vant/issues/4665

关闭 animated 可以避免
