### ISSUE TITLE
[Bug Report] 复选框全选问题

### ISSUE THREAD

**Issue by zhangxin0w0** [youzan/vant#4771]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.9-beta.1

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-d3uhb" target="_blank">https://codesandbox.io/embed/vant-issue-moban-d3uhb</a>

### 描述问题
使用带全选的复选框时，提示找不到方法TypeError: this.$refs.checkboxGroup.toggleAll is not a function
这是怎么回事呢？

**Comment by chenjiahan** [comment]
版本不对，复现链接里用的是 2.0.0 版本，请升级到 2.2.6 以上的版本

**Comment by zhangxin0w0** [comment]
> 版本不对，复现链接里用的是 2.0.0 版本，请升级到 2.2.6 以上的版本

谢谢指正，项目使用的是2.2.4  没有及时更新，打扰了

**Comment by linheqin** [comment]
我用的2.2.14也是不行的，为什么啊

**Comment by linheqin** [comment]
`<template>
<div class="good-car-wrap">
	<div class="page-header">
		<van-nav-bar title="购物车">
			<van-icon name="arrow-left" slot="left" @click="$router.go(-1)"/>
		</van-nav-bar>
	</div>
	<div class="good-list-wrap card-goods">
		<div class="card-goods-item-div" v-for="(item,index) in goods" :key="index">
		    <van-checkbox-group v-model="checkedGoods" ref="checkboxGroup">
				<van-checkbox
					class="card-goods__item"
					checked-color="#fd7300"
					:v-model="item.checked"
					:key="item.id"
        			:name="item.id"
				>	
					<van-card
					:title="item.title"
					:desc="item.desc"
					:price="formatPrice(item.price)"
					:thumb="item.thumb"
					>
						<div slot="tags">
							<van-tag plain type="danger">变态辣</van-tag>
						</div>
					</van-card>
				</van-checkbox>
			</van-checkbox-group>
			<div class="tag-items">

			</div>
			<van-stepper v-model="item.num" :max="item.maxNum" integer />
		</div>
		
	</div>
	
	<van-submit-bar
		class="good-footer-btn"
		:price="totalPrice"
		:disabled="!checkedGoods.length"
		:button-text="submitBarText"
		@submit="onSubmit"
	>
		<van-checkbox checked-color="#fd7300" v-model="checked" @click="checkAll">全选</van-checkbox>
		<span slot="tip">
			你的收货地址不支持同城送, <span>修改地址</span>
		</span>
	</van-submit-bar>
</div>
</template>

<script>
import { NavBar,Stepper ,Checkbox, CheckboxGroup, Card, SubmitBar, Toast,Tag  } from "vant";


export default {
	components: {
		[Tag.name]: Tag,
		[Stepper.name]: Stepper,
		[NavBar.name]: NavBar,
		[Card.name]: Card,
		[Checkbox.name]: Checkbox,
		[SubmitBar.name]: SubmitBar,
		[CheckboxGroup.name]: CheckboxGroup
	},

	data() {
		return {
			checkedGoods: [],
			checked: false,
			goods: [
				{
					id: "1",
					title: "进口香蕉进口香蕉进口香蕉进口香蕉进口香蕉",
					desc: "约250g，2根",
					price: 2000000,
					num: 98,
					maxNum: 100,
					checked: true,
					thumb:
						"https://img.yzcdn.cn/public_files/2017/10/24/2f9a36046449dafb8608e99990b3c205.jpeg"
				},
				{
					id: "2",
					title: "陕西蜜梨",
					desc: "约600g",
					price: 6000090,
					num: 1,
					maxNum: 20,
					checked: false,
					thumb:
						"https://img.yzcdn.cn/public_files/2017/10/24/f6aabd6ac5521195e01e8e89ee9fc63f.jpeg"
				},
				{
					id: "3",
					title: "美国伽力果",
					desc: "约680g/3个",
					price: 2680,
					num: 1,
					maxNum: 10,
					checked: false,
					thumb:
						"https://img.yzcdn.cn/public_files/2017/10/24/320454216bbe9e25c7651e1fa51b31fd.jpeg"
				},
				{
					id: "4",
					title: "进口香蕉",
					desc: "约250g，2根",
					price: 200,
					num: 1,
					maxNum: 10,
					checked: false,
					thumb:
						"https://img.yzcdn.cn/public_files/2017/10/24/2f9a36046449dafb8608e99990b3c205.jpeg"
				},
				{
					id: "5",
					title: "陕西蜜梨",
					desc: "约600g",
					price: 690,
					num: 1,
					maxNum: 10,
					checked: false,
					thumb:
						"https://img.yzcdn.cn/public_files/2017/10/24/f6aabd6ac5521195e01e8e89ee9fc63f.jpeg"
				},
				{
					id: "6",
					title: "美国伽力果",
					desc: "约680g/3个",
					price: 2680,
					num: 1,
					maxNum: 10,
					checked: false,
					thumb:
						"https://img.yzcdn.cn/public_files/2017/10/24/320454216bbe9e25c7651e1fa51b31fd.jpeg"
				},
				{
					id: "7",
					title: "进口香蕉",
					desc: "约250g，2根",
					price: 200,
					num: 1,
					maxNum: 10,
					checked: false,
					thumb:
						"https://img.yzcdn.cn/public_files/2017/10/24/2f9a36046449dafb8608e99990b3c205.jpeg"
				},
				{
					id: "8",
					title: "陕西蜜梨",
					desc: "约600g",
					price: 690,
					num: 1,
					maxNum: 10,
					checked: false,
					thumb:
						"https://img.yzcdn.cn/public_files/2017/10/24/f6aabd6ac5521195e01e8e89ee9fc63f.jpeg"
				},
				{
					id: "9",
					title: "美国伽力果",
					desc: "约680g/3个",
					price: 2680,
					num: 1,
					maxNum: 10,
					checked: false,
					thumb:
						"https://img.yzcdn.cn/public_files/2017/10/24/320454216bbe9e25c7651e1fa51b31fd.jpeg"
				}
			]
		};
	},

	computed: {
		submitBarText() {
			const count = this.checkedGoods.length;
			return "结算" + (count ? `(${count})` : "");
		},

		totalPrice() {
			return this.goods.reduce(
				(total, item) =>
					total +
					(this.checkedGoods.indexOf(item.id) !== -1
						? item.price*item.num
						: 0),
				0
			);
		}
	},
	created(){
		
	},
	methods: {
		formatPrice(price) {
			return (price / 100).toFixed(2);
		},

		onSubmit() {
			Toast("点击结算");
		},
		checkAll() {
			console.log(this.$refs.checkboxGroup);
			this.$refs.checkboxGroup.toggleAll();
		}
		// goReturn
	}
};
</script>

<style lang="less">
.good-car-wrap {
	height: 100%;
	
	.card-goods {
		position: absolute;
		left: 0;
		top: 50px;
		right: 0;
		bottom: 50px;
		overflow: auto;
		-webkit-overflow-scrolling: touch;
		.card-goods-item-div {
			position: relative;
			margin-bottom: 10px;
			background-color: #fff;
		}
		.card-goods__item {
			background: none;
		}
		.van-stepper {
			position: absolute;
			right: 8px;
			bottom: 9px;
			width: 100%;
			text-align: right;
		}
		.van-card {
			padding: 10px 0 10px 15px;
			background: none;
		}
		.van-card__title {
			font-size: 16px;
			max-height: none;
			line-height: 20px;
		}
		.van-card__desc {
			font-size: 14px;
			margin: 5px 0;
		}
		.van-card__bottom {
			font-size: 14px;
		}
		.van-card__thumb {
			width: 110px;
			height: 110px;
		}
		&__item {
			position: relative;
			background-color: #fafafa;

			.van-checkbox__label {
				width: 100%;
				height: auto; // temp
				padding: 0 10px 0 15px;
				box-sizing: border-box;
			}

			.van-checkbox__icon {
				top: 50%;
				left: 10px;
				z-index: 1;
				position: absolute;
				margin-top: -10px;
			}

			.van-card__price {
				color:#fd7300;
			}
		}
	}
	.good-footer-btn {
		position: absolute;
		.van-submit-bar__price {
			color:#fd7300;
		}
		.van-button--danger {
			background-color: #fd7300;
			border: 0.02667rem solid #fd7300;
		}
		.van-checkbox {
			padding-left: 8px;
		}
	}
}

</style>
`
