### ISSUE TITLE
[Feature Request] NumberKeyboard input事件建议

### ISSUE THREAD

**Issue by whoishower** [youzan/vant#4772]
### 这个功能解决了什么问题
点击按键时触发

### 描述您想要的解决方案
目前该事件的触发是在修改变量前触发，触发后才会修改变量，然而不便于对输入的值进行检测，例如：官方提供的双绑实例中如需实现输入小数，并对小数的合法性进行校验，无法使用input事件。

### 建议的API是什么样的
建议增加阻断方案，从而阻断input的输入，如为函数增加return false 即可阻断输入

**Comment by chenjiahan** [comment]
sorry，无法实现 return false 的方案，你可以监听 update:value 事件，或者不使用双向绑定
