### ISSUE TITLE
[Feature Request] 希望Toast.loading能增加颜色参数

### ISSUE THREAD

**Issue by linhaihero** [youzan/vant#4774]
### 这个功能解决了什么问题
Toast.loading 行内样式锁死了loading的颜色，堵死了定制的可能。增加颜色参数可实现不同的样式需求。

### 描述您想要的解决方案
Options 增加 loadingColor 参数，在调用嵌套loading组件时传进去。
ps：此外，实际上整个Toast 组件的loading、success、fail 都建议各增加一个默认样式名，以区分不同的使用状态。例如 van-toast--loading 、van-toast--success、van-toast--fail 等

### 建议的API是什么样的
loadingColor : string
说明：加载图标的颜色
默认值："white"

**Comment by chenjiahan** [comment]
Toast 的样式是比较统一的，没见过其他颜色的，能发个图看看么

**Comment by linhaihero** [comment]
https://element.eleme.io/#/zh-CN/component/loading 
就是类似饿了么的全局loading，风格干净整洁一些，就一个遮罩，和一个转动的图标这样。这个时候就必须可以调整loading的颜色才行，否则实现不了。
当然，我可能可以手动创建一个loading组件（可定制）在body顶层，然后用全局变量来控制v-if，但这样远远没有使用Toast.loading方便

**Comment by linhaihero** [comment]
大佬，能不能把 Toast 组件增加默认样式名（对应不同的调用）也加一下？跪求。。
van-toast--text 、van-toast--loading 、van-toast--success、van-toast--fail

**Comment by chenjiahan** [comment]
其实还是比较推荐用现在这种样式的，微信的 Loading 就是这种风格，移动端用户是比较习惯的

van-toast--loading 这些类名后续会加上

**Comment by chenjiahan** [comment]
已在 2.2.9 版本支持
