### ISSUE TITLE
关于vant-uploder样式自定义问题

### ISSUE THREAD

**Issue by mitboy1983** [youzan/vant#4777]
最新版的vant 2.2.8 里面上传图片组件自定义上传区域和预览

官网有参数定义上传区域大小 preview-size，设置以后但是是正方形，遇到上传身份证这种，正方形就满足不了要求。

上传区域还好可以自己定义为长方形，但是上传成功以后，预览加载图片这里就又成了默认的 80*80的正方形。。。我设置的 preview-size为200，上传成功以后 预览加载图片的部分 css 如下：

<div class="van-image van-uploader__preview-image" style="width: 200px; height: 200px; overflow: hidden; border-radius: 4px;">

这个预览的图片大小还是个正方形，如果要自己修改 在当前页面设置  van-image 或者 van-uploader__preview-image的 css 为 !important 都不起作用，只能在 app.vue里面设置为全局才有效， 这又可能导致后面其他页面用到这个组件时候 样式全改了。。。

不知道 大佬有没有其他的办法来解决这个问题？

建议：既然上传样式可以自定义，希望 上传成功加载预览图片这个 样式也可以跟 上传的样式一样！

**Comment by mitboy1983** [comment]
奇怪上面发的 css 直接全部没有显示了。。。

补充一下
我设置的 preview-size为200，上传成功以后 预览加载图片的部分 css 如下：

`<div class="van-image van-uploader__preview-image" style="width: 200px; height: 200px; overflow: hidden; border-radius: 4px;">`

**Comment by mitboy1983** [comment]
搞定了，官网群里的大神 指点了一下 用 deep 穿透 就能解决了

**Comment by iexxk** [comment]
> 搞定了，官网群里的大神 指点了一下 用 deep 穿透 就能解决了

可以提供相关代码么
