### ISSUE TITLE
[Bug Report] ImagePreview预览打开图片无法关闭

### ISSUE THREAD

**Issue by wangyong991** [youzan/vant#4779]
### 设备 / 浏览器
iphone7Plus 11.2.5

### Vant 版本
2.2.9-beta.1

### Vue版本
2.6.10

### 重现链接
<a href="http://ullget-staging.oss-cn-shanghai.aliyuncs.com/sales/96/preview.mp4" target="_blank">http://ullget-staging.oss-cn-shanghai.aliyuncs.com/sales/96/preview.mp4</a>

### 描述问题
使用的是官网demo，直接点击能全屏展示图片，然后再次点击，无法关闭预览图片

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3015
可以降级到 Vue 2.5.22 试下

**Comment by wangyong991** [comment]
这个直接是用手机微信访问官网（https://youzan.github.io/vant/mobile.html#/zh-CN/image-preview）地址的时候也是这样。

**Comment by chenjiahan** [comment]
上面的 issue 里有解释

官方使用的也是 Vue 2.6.10
