### ISSUE TITLE
[Report] vue cli3在项目中使用本地字体文件还有引用cdn的

### ISSUE THREAD

**Issue by wxp732826840** [youzan/vant#4788]
### 设备 / 浏览器
safiri

### Vant 版本
2.2.8

### Vue版本
2.6.10

### 重现链接
<a href="https://github.com/wxp732826840/orm3.0.git" target="_blank">https://github.com/wxp732826840/orm3.0.git</a>

### 描述问题
在cli2创建的项目可以使用本地字体，但是搬到cli3上就一直访问cdn的，3还需要单独配置什么吗？

**Comment by wxp732826840** [comment]
请问3.0还需要单独配置什么吗

**Comment by chenjiahan** [comment]
不需要其他配置

**Comment by wxp732826840** [comment]
> 不需要其他配置

但是 我也添加了 url-loader ，其他的代码 cli2和cli3都是一样的，cli2的就是本地的，cli3不行，麻烦帮看一下呗，试了好多方法都不行

**Comment by wxp732826840** [comment]
> > 不需要其他配置
> 
> 但是 我也添加了 url-loader ，其他的代码 cli2和cli3都是一样的，cli2的就是本地的，cli3不行，麻烦帮看一下呗，试了好多方法都不行



> 不需要其他配置

这个是main.js,是添加到这个js里面吧

import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import './assets/css/iconfont/iconfont.css';
import 'vant/lib/icon/local.css';
Vue.config.productionTip = false

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app')

**Comment by hzyyy** [comment]
嗨，你解决了吗

**Comment by snowtreetree** [comment]
@wxp732826840 请问你这边解决了吗？

**Comment by hzyyy** [comment]
我这边解决了。但是时间有点久了，应该截图中的代码可以解决这个问题。
![image](https://user-images.githubusercontent.com/33852158/71758428-75a95000-2eda-11ea-95a9-a4a88724aacb.png)

**Comment by SeanKChan** [comment]
vant 2.5.1版本如何解决？

**Comment by hzyyy** [comment]
应该差不多吧，我的vant 版本是2.4.1

**Comment by 446104748** [comment]
> 应该差不多吧，我的vant版本是2.4.1

请教一下，你的url-loader怎么写的？我用了你同样的babe.config.js配置没效果。谢谢。

**Comment by hzyyy** [comment]
不行么?
我还给app.vue 文件的 style 手动引入了字体文件。：
@import '/assets/fonthttps://img.yzcdn.cn/vant/vant-icon-0bc654.woff2';

**Comment by 446104748** [comment]
那这样不还是引用vant的cdn吗？我是想不用cdn，用本地的的字体。cdn的字体图标在网络状况不太好的情况下会显示一个方格。

**Comment by hzyyy** [comment]
你看清楚哦。这是cdn 地址么？

**Comment by 446104748** [comment]
好的，谢谢

**Comment by 446104748** [comment]
多谢多谢，问题解决了。

**Comment by luckywangming** [comment]
需要配置url-loader吗
