### ISSUE TITLE
[Bug Report] popup弹出后 调用 dialog 提示窗口时，overlay 动画失效 

### ISSUE THREAD

**Issue by linhaihero** [youzan/vant#4791]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-2ttqs" target="_blank">https://codesandbox.io/embed/vant-issue-moban-2ttqs</a>

### 描述问题
overlay 动画失效

**Comment by chenjiahan** [comment]
这种弹窗叠加的情况下，蒙层已经展示了，只是调整了层级位置，所以不会有动画喔。

按照目前的方案也无法实现动画效果。

**Comment by linhaihero** [comment]
归根到底，就是蒙层目前是公用的。其实这有点不科学，做用户体验的话，肯定是要展示体验好一点。建议蒙层是单独的分开 多个就多个更黑一点无所谓，反正都要用户目光聚集，觉得这更科学一点。

**Comment by chenjiahan** [comment]
相较于过渡动画，我们认为多蒙层叠加导致的深色问题更加影响体验，因此不考虑改动蒙层逻辑
