### ISSUE TITLE
textarea 设置了autosize得minHeight 低于48px就不起作用

### ISSUE THREAD

**Issue by wbjeln** [youzan/vant#4792]
textarea 设置了autosize得minHeight 低于48px就不起作用

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by charmwf** [comment]
<van-field
      type="textarea"
      :autosize="{ maxHeight: 120, minHeight: 24 }"
      v-model="inputVal"
      @update:model-value="inputChange"
      @focus="inputFocus(true)"
      @blur="inputFocus(false)"
      placeholder="请输入消息" />
这里面的 minHeight: 24 没效果

**Comment by charmwf** [comment]
```
<van-field
type="textarea"
:autosize="{ maxHeight: 120, minHeight: 24 }"
v-model="inputVal"
https://github.com/update:model-value="inputChange"
@Focus="inputFocus(true)"
@blur="inputFocus(false)"
placeholder="请输入消息" />
```
这里面的 minHeight: 24 没效果
