### ISSUE TITLE
van-image 使用lazy-load图片会重复请求两次？

### ISSUE THREAD

**Issue by Gokeyoung** [youzan/vant#4793]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

**版本：2.2.7**

**代码片段：**
`<van-image
                                class="lazyload__img"
                                lazy-load
                                :src="$utils.imagePath(item.adimg)"
                            />`

**网络加载：**
![image](https://user-images.githubusercontent.com/18525879/67182324-710fe800-f411-11e9-9e91-cb307d9bc3b6.png)

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
不会的喔，你可以把控制台的 Disable cache 关掉看下

**Comment by yokiyokiyoki** [comment]
的确会
