### ISSUE TITLE
SwipeCell 滑动单元格点击自身van-swipe-cell时，获取到的数据不正确

### ISSUE THREAD

**Issue by xiaochegnzi0** [youzan/vant#4794]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

![image](https://user-images.githubusercontent.com/27406973/67184235-e7164e00-f415-11e9-83ac-bf7b75f9791b.png)
![image](https://user-images.githubusercontent.com/27406973/67184260-f4333d00-f415-11e9-954e-678665ed1e6b.png)
点击的是第一个，数据和下角标却显示为第二个的内容

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
