### ISSUE TITLE
[Feature Request] Popup 组件新增 title prop

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#4795]
### 这个功能解决了什么问题
实际开发许多弹窗都有标题，挺常用的~
![image](https://user-images.githubusercontent.com/16074662/67190447-8f321400-f422-11e9-9229-ccf79ed06459.png)

### 描述您想要的解决方案
传 title 则显示标题，不传则不显示

### 建议的API是什么样的
新增 title prop

**Comment by chenjiahan** [comment]
暂无计划支持喔，目前倾向于 Popup 只提供弹窗容器功能
