### ISSUE TITLE
数字键盘第一次按下打印出的绑定值是空串？

### ISSUE THREAD

**Issue by LonelyPH** [youzan/vant#4796]
![image](https://user-images.githubusercontent.com/47054165/67199996-26a06280-f435-11e9-9efd-39c534203c6f.png)

![image](https://user-images.githubusercontent.com/47054165/67200043-4d5e9900-f435-11e9-9eed-6318fd350240.png)

如上图，数字键盘绑定的值，第一次点击按键时在onInput中打印出来的是空值，第二次点击按键打印第一次的值，这样我怎么做金额格式限制？是要用nextTick吗

**Comment by chenjiahan** [comment]
可以使用 nextTick，或者 watch 绑定的值
