### ISSUE TITLE
[Feature Request] 类似Image的组件添加to或者url

### ISSUE THREAD

**Issue by kelvinBen** [youzan/vant#4797]
### 这个功能解决了什么问题
点击图片的时候跳转到其他页面或者url,使用宫图的to或者url有些大材小用，同时很多时候又没有必要使用点击事件进行跳转。

### 描述您想要的解决方案
类似Image的组件在标签中添加to或者url标签，方便快速跳转

### 建议的API是什么样的
多元化，便携式

**Comment by chenjiahan** [comment]
从组件定位上来说，导航功能不属于 Image 的一部分，因此我们不会在组件内部支持，建议自行实现
