### ISSUE TITLE
[Bug Report] 如何开启PC 中的 mouse事件   

### ISSUE THREAD

**Issue by zrnokia5230** [youzan/vant#4800]
### 设备 / 浏览器
PC/Chrome

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html#/zh-CN/picker" target="_blank">https://youzan.github.io/vant/mobile.html#/zh-CN/picker</a>

### 描述问题
vant  的demo 中  例如Picker  组件，Slider组件 查看监听的事件 发现多了mouse相关的事件    可以在PC 模式时鼠标拖动    
自己的业务中  发现 默认没有添加mouse相关的事件监听  如何加入 使组件兼容PC

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong
