### ISSUE TITLE
[Bug Report] Uploader组件弹出样式

### ISSUE THREAD

**Issue by tvideo2008** [youzan/vant#4801]
### 设备 / 浏览器
IOS12

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="https://1tit5.csb.app/" target="_blank">https://1tit5.csb.app/</a>

### 描述问题
使用Uploader组件上传图片，在iphone上运行，当点击上传时会跳转到了一个新的页面，并显示【拍照】、【照片图库】、【浏览】三个按钮并且没有返回按钮。希望实现从底部上滑出现【拍照】、【照片图库】、【浏览】并在下放有【取消】按钮，需要如何设置？

**Comment by chenjiahan** [comment]
这个是系统原生界面，无法定制喔

**Comment by tvideo2008** [comment]
我用HBuilder工具打包到手机上，会从底部滑入。同时的代码，用XCode创建工程后打包相同的手机，就是跳转到新的页面的。这个应该是可以配置的吧？

**Comment by chenjiahan** [comment]
这个不清楚噢，建议看下原生是否提供了这样的能力
