### ISSUE TITLE
DatetimePicker 选项过滤器bug

### ISSUE THREAD

**Issue by chen-can** [youzan/vant#4802]
van-datetime-picker
  v-model="currentTime"
  type="datetime"
  :filter="filter"
 @confirm="onConfirm"
/>
export default {
  data() {
    return {
      currentTime: new Date()
    };
  },

  methods: {
    filter(type, options) {
      if (type === 'minute') {
        return options.filter(option => option % 5 === 0)
      }

      return options;
    },
onConfirm(val){
console.log(val) //此处打印的时间错误，应该为过滤的时间
}
  }
}

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by chen-can** [comment]
无法复现吗 请提供模版示例，谢谢合作

**Comment by chenjiahan** [comment]
创建 issue 时有提供模板示例链接的

**Comment by chen-can** [comment]
@chenjiahan  issue已调整 此链接https://github.com/youzan/vant/issues/4819为调整后的问题

**Comment by chenjiahan** [comment]
好的
