### ISSUE TITLE
[Feature Request] 没有上拉刷新吗？

### ISSUE THREAD

**Issue by orochitian** [youzan/vant#4803]
### 这个功能解决了什么问题
可以解决移动端分页问题

### 描述您想要的解决方案
既然有下拉刷新，可以添加一个同样的上拉刷新的功能啊。

### 建议的API是什么样的
和下拉刷新保持一致，可以共用即可

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3687
