### ISSUE TITLE
[Feature Request] 关于van-button加载状态宽度变小

### ISSUE THREAD

**Issue by sc544177047** [youzan/vant#4804]
因为按钮用的padding 变为加载状态图标时 变小，在不定死宽度下请问怎么处理呢

**Comment by sc544177047** [comment]
我觉得可以 加载状态时 将字透明 显示加载图标 然后加载完在反过来这样就不会改变宽度了，希望能修改一下，现在我只能定死宽度来处理了

**Comment by chenjiahan** [comment]
建议固定宽度喔，暂时没有其他方案
