### ISSUE TITLE
ImagePreview图片预览滑动到最后一张继续往后滑或是滑动到第一张继续往前滑出现BUG

### ISSUE THREAD

**Issue by yxh410** [youzan/vant#4805]
![image](https://user-images.githubusercontent.com/36829582/67270698-c4eeff80-f4eb-11e9-9bbc-46ea440aadc3.png)
ImagePreview图片预览滑动到最后一张继续往后滑或是滑动到第一张继续往前滑图片无法显示，点击遮罩层也无法关闭

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
