### ISSUE TITLE
van-datetime-picker组件会造成页面死循环

### ISSUE THREAD

**Issue by hetchzhao** [youzan/vant#4808]
![image](https://user-images.githubusercontent.com/6813909/67353669-accbbe80-f585-11e9-9f1b-c169d7415722.png)
如果min-date,max-date的值采用new Date()的方式传入时，会造成页面死循环

```
......
watch: {
    filter: 'updateInnerValue',
    minDate: 'updateInnerValue',
    maxDate: 'updateInnerValue',
......
```

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3046
