### ISSUE TITLE
List组件不断触发底部加载  没有float

### ISSUE THREAD

**Issue by 2587593709** [youzan/vant#4810]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by 2587593709** [comment]
vant1版本一直没问题，2版本后这个问题一直没有解决，试了官方的方法都不行

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
