### ISSUE TITLE
[Feature Request] Toast 组件的 loading 方法持续时间默认永久

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#4811]
### 这个功能解决了什么问题
实际应用中，Toast.loading() 全是用在请求接口或等待某个操作的过程，现在所有页面用 loading 方法都要加个 duration，太重复繁琐了

### 描述您想要的解决方案
Toast.loading 方法持续时间默认永久

### 建议的API是什么样的
Toast.loading 方法持续时间默认永久

**Comment by chenjiahan** [comment]
暂无计划修改，这样修改会导致 breaking change

你可以用一个函数简单封装下
