### ISSUE TITLE
picker 还在滚动的时候，通过 ref 可以获取到 picker 实例的问题

### ISSUE THREAD

**Issue by Fangsiyu** [youzan/vant#4812]
当 picker 还在滚动的时候，通过 ref 可以获取到 picker 实例有点问题，因为惯性滑动比较慢，会导致获取到的 picker 值有问题，可以在官网尝试一下，惯性功能有点慢，能否开方惯性滚动时长？

**Comment by chenjiahan** [comment]
后续会加个属性支持配置惯性滚动时长

**Comment by chenjiahan** [comment]
已在 2.2.10 版本支持
