### ISSUE TITLE
评分组件的value

### ISSUE THREAD

**Issue by qimiaojiyihou** [youzan/vant#4813]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater
![QzpcVXNlcnNcdXNlclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNTg0Mzg5MTM5X3YyXEltYWdlRmlsZXNcMTU3MTgyMDg1NjA3NV83QUE0RDY4RC1DRkQyLTQwZWQtODBBNy1FOUJGQTUwNDJERTgucG5n](https://user-images.githubusercontent.com/43678058/67375829-c97fea80-f5b5-11e9-8d64-cff4863d7d11.png)

---请问怎么把评分的这个value使用v-for遍历的变量替代

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
