### ISSUE TITLE
[Bug Report] area如何通过code获取地区的中文名称呢？

### ISSUE THREAD

**Issue by xsdream** [youzan/vant#4815]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/m5v3f" target="_blank">https://codesandbox.io/s/m5v3f</a>

### 描述问题
能否提供一个方法，让area组件能通过后台返回的code编码查出地区的中文名称。

**Comment by chenjiahan** [comment]
直接去 area 数据里匹配就好
