### ISSUE TITLE
[Bug Report] vant 复选框全选问题

### ISSUE THREAD

**Issue by jiahui336** [youzan/vant#4817]
### 设备 / 浏览器
公众号 

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/checkbox" target="_blank">https://youzan.github.io/vant/#/zh-CN/checkbox</a>

### 描述问题
点击全选之后报错 this.$refs.checkboxGroup.toggleAll is not a function

**Comment by chenjiahan** [comment]
请注意升级到 2.2.6 及以上版本

**Comment by jiahui336** [comment]
> 请注意升级到2.2.6及更高版本
好了 谢谢
