### ISSUE TITLE
van-list组件会有一直自动重复请求的原因

### ISSUE THREAD

**Issue by Gokeyoung** [youzan/vant#4818]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

**问题：**

- van-list组件打开页面会一直执行@load方法？

**原因：**

1.  有一个官方说的使用float浮动所导致的，会一直执行。
2. （个人遇到）van-list使用组件祖父级scroller指向不是window基本就会一直请求。

**第二个原因解决：**

- 使用van-list组件外层有5个父级元素包裹，但是我在某一个祖父级添加了overflow样式，所以导致van-list所需的scroller指向该元素，让van-list获取页面数据的van-list__placeholder元素的bottom一直跟对比的bottom一样，所以导致会一直请求。

官方代码：
![image](https://user-images.githubusercontent.com/18525879/67381123-fafcb400-f5bd-11e9-9625-fbc862508daa.png)
当_this.scroller指向是window的时候就不会有问题。

**所以不要的使用van-list组件的外层元素添加overflow让页面可以滚动的样式（overflow:hidden目前可以）**

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by ellenging** [comment]
_this.scroller指向不是window， van-list 和 它的父级都不要添加 overflow: hidden; 或 overflow-x: hidden;
