### ISSUE TITLE
[Bug Report] DatetimePicker 选项过滤器返回结果错误

### ISSUE THREAD

**Issue by chen-can** [youzan/vant#4819]
### 设备 / 浏览器
chrome

### Vant 版本
2.0.6

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-lpdon?fontsize=14" target="_blank">https://codesandbox.io/s/vant-issue-moban-lpdon?fontsize=14</a>

### 描述问题
首次点击返回结果不正确，选择时间后再次点击返回结果是正确的

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复此问题

**Comment by chen-can** [comment]
@chenjiahan 有没有什么临时解决方案

**Comment by chenjiahan** [comment]
已在 2.2.10 版本修复

**Comment by chen-can** [comment]
如果是10.56分无法选择11点这个时段

**Comment by chenjiahan** [comment]
> 如果是10.56分无法选择11点这个时段

已在 2.2.13-beta.0 版本修复
