### ISSUE TITLE
[Bug Report] swipe组件，在swipe-item标签上增加@click.native,本来只是想拖动查看下一帧，结果触发点击这一帧页面跳转链接

### ISSUE THREAD

**Issue by seric705** [youzan/vant#4821]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 描述问题
swipe组件，在swipe-item标签上增加@click.native,本来只是想拖动查看下一帧，结果触发点击这一帧页面跳转链接

**Comment by seric705** [comment]
为什么在touchmove时，用的是event.stopPropagation，而不是event.preventDefault();，导致拖动的过程中被触发click事件

**Comment by chenjiahan** [comment]
这个是 fastclick 的问题，和组件无关

**Comment by seric705** [comment]
我把fastclick注释掉还是有问题，而且在vant的swipe展示demo里swipe-item直接添加click跳转链接，同样有这个问题

**Comment by seric705** [comment]
vant的一个历史版本上就是用event.preventDefault，不是用的event.stopPropagation

**Comment by chenjiahan** [comment]
我这没复现，可以提供 codesandbox 链接看下

**Comment by wuyuedefeng** [comment]
我这也遇到了这个问题 解决了吗,  vant version `2.2.5`
