### ISSUE TITLE
[Feature Request] ImagePreview 图片预览组件 浏览器支持特性增加

### ISSUE THREAD

**Issue by Rackar** [youzan/vant#4822]
### 这个功能解决了什么问题
ImagePreview 图片预览组件，当前只支持移动端的滑动切换左右图片，以及触摸退出。对浏览器的鼠标左右拖拽和点击退出不支持。

### 描述您想要的解决方案
增加左右导航按钮，及退出按钮
or
增加对鼠标动作的理解支持

### 建议的API是什么样的
showNaviButton:false,
showCloseButton:false,
enableMouseAction:false

**Comment by chenjiahan** [comment]
在桌面端使用参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

左右导航暂无计划支持，Vant 是面向移动端的
