### ISSUE TITLE
[Bug Report] dialog样式问题

### ISSUE THREAD

**Issue by yxHenry** [youzan/vant#4824]
### 设备 / 浏览器
ios

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 描述问题
2.2.9版本的dialog在ios中会向上移位一些，挡住了头部的边框，之前2.0.9版本没有这个问题

**Comment by chenjiahan** [comment]
头部边框指的是？

**Comment by yxHenry** [comment]
![image](https://user-images.githubusercontent.com/28614793/67459186-8c296480-f66a-11e9-8164-19ceb980d9b5.png)
这一部分

**Comment by yxHenry** [comment]
抱歉之前的描述不够准确，我弄了个例子[ https://codesandbox.io/s/vant-issue-moban-31d25](url)，这是2.0.9的版本，切换到2.2.9就不一样了

**Comment by chenjiahan** [comment]
在移动端浏览器上，顶部导航栏是不计入页面高度的，为了让弹窗的位置在『视觉上居中』，我们把弹窗的位置向上调整了一点（从 top 50% 变成 top 45%），所以会出现这个问题

你可以把弹窗的最大高度调小一点，就不会有这个问题了

**Comment by yxHenry** [comment]
@chenjiahan 好的老哥，感谢
