### ISSUE TITLE
[Feature Request] 支持导出框架自带的工具类

### ISSUE THREAD

**Issue by bigmeow** [youzan/vant#4825]
### 这个功能解决了什么问题
代码复用

### 描述您想要的解决方案
vant 自用的工具包中有些项目也可以用得上，希望能支持导出，并提供相应的d.ts文件

### 建议的API是什么样的
```js
import { Utils } from 'vant'
Utils.xxx()
```

**Comment by chenjiahan** [comment]
抱歉，暂时不会对外暴露，组件库本身不应该提供工具类，且内部的工具类是会发生变动的。

比如 Vue 内部也有很多工具类，但是 Vue 不会把工具类标注在文档里让开发者使用。
