### ISSUE TITLE
[Bug Report] 下拉刷新设置高度后无法滚动

### ISSUE THREAD

**Issue by sydyLiu** [youzan/vant#4828]
### 设备 / 浏览器
Google模拟器 iphoneX

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="https://aaa.bbb.com/" target="_blank">https://aaa.bbb.com/</a>

### 描述问题
首先.由于项目还在开发,我暂时无法提供<重现链接>  
我表述问题: 

使用下拉刷新时,如果给容器设置了高度,内容撑满溢出后,内容无法滚动.若不设置高度,下拉刷新可操作范围十分狭小.

再者, 我要如何开启上拉加载?为什么下拉刷新有了, 却没有上拉加载?

上述问题可以用官方事例重现, 只需将 子组件增加多个, 问题就会重现. 
希望不要把我这个问题刷掉, 我百度了很多, 发现没有人有我这个问题, 我不知道这是我一个人的问题,还是代码本身就有问题, 
希望给我解惑. 

如果我的问题有幸被看到,请尽快回复我.  谢谢

**Comment by chenjiahan** [comment]
能否用 codesandbox 提供一个重现链接

**Comment by sydyLiu** [comment]
`<template>
  <div id="app">
    <van-pull-refresh
      v-model="refreshData.isLoading"
      @refresh="onRefresh"
      :pulling-text="refreshData.pullingText"
      :loosing-text="refreshData.loosingText"
      :loading-text="refreshData.loadingText"
      :success-text="refreshData.successText"
      v-bind:style="'height:' + boxWh + 'px;'"
    >
      <div class="item" v-for="(item,index) in data" :key="index">{{item}}</div>
      
      <van-list
        @load="onDownRefresh"
        v-model="refreshUpData.isLoading"
        :finished="refreshUpData.upFinished"
        :finished-text="refreshUpData.finishedText"
      ></van-list>
    </van-pull-refresh>
  </div>
</template>



<script>
export default {
  data() {
    return {
      data: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
	  // data:[
		 //  1	
	  // ],
      boxWh: window.innerHeight, // 这是容器高度, 当内容溢出后, 容器内容无法滚动, 增加overflow-y 后,容器虽然会滚动, 但是下拉时不会到达顶部,而是直接下拉刷新.
      refreshData: {
        // 配置下拉刷新数据
        isLoading: false,
        count: 0,
        pullingText: "下拉既可刷新...",
        loosingText: "釋放立即刷新...",
        loadingText: "加載中...",
        successText: "刷新成功"
      },
      refreshUpData: {
        //配置上拉加载数据
        isLoading: false,
        upFinished: false,
        finishedText: "沒有更多數據了..."
      }
    };
  },
  components: {},
  methods: {
    onRefresh() {
      //下拉刷新回调
      setTimeout(() => {
        this.$toast("刷新成功");
        this.refreshData.isLoading = false;
        this.refreshData.count++;
      }, 500);
    },
    onDownRefresh() {
      //上拉加载回调
      setTimeout(() => {
        this.$toast("刷新成功");
        this.refreshUpData.isLoading = true;
      }, 500);
    }
  }
};
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

.item{
	height: 30vw;
	background-color: #fff;
	display: flex;
	align-items: center;
	justify-content: center;
}
</style>
`

**Comment by sydyLiu** [comment]
<template>
  <div id="app">
    <van-pull-refresh
      v-model="refreshData.isLoading"
      @refresh="onRefresh"
      :pulling-text="refreshData.pullingText"
      :loosing-text="refreshData.loosingText"
      :loading-text="refreshData.loadingText"
      :success-text="refreshData.successText"
      v-bind:style="'height:' + boxWh + 'px;'"
    >
      <div class="item" v-for="(item,index) in data" :key="index">{{item}}</div>
      
      <van-list
        @load="onDownRefresh"
        v-model="refreshUpData.isLoading"
        :finished="refreshUpData.upFinished"
        :finished-text="refreshUpData.finishedText"
      ></van-list>
    </van-pull-refresh>
  </div>
</template>



<script>
export default {
  data() {
    return {
      data: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
	  // data:[
		 //  1	
	  // ],
      boxWh: window.innerHeight, // 这是容器高度, 当内容溢出后, 容器内容无法滚动, 增加overflow-y 后,容器虽然会滚动, 但是下拉时不会到达顶部,而是直接下拉刷新.
      refreshData: {
        // 配置下拉刷新数据
        isLoading: false,
        count: 0,
        pullingText: "下拉既可刷新...",
        loosingText: "釋放立即刷新...",
        loadingText: "加載中...",
        successText: "刷新成功"
      },
      refreshUpData: {
        //配置上拉加载数据
        isLoading: false,
        upFinished: false,
        finishedText: "沒有更多數據了..."
      }
    };
  },
  components: {},
  methods: {
    onRefresh() {
      //下拉刷新回调
      setTimeout(() => {
        this.$toast("刷新成功");
        this.refreshData.isLoading = false;
        this.refreshData.count++;
      }, 500);
    },
    onDownRefresh() {
      //上拉加载回调
      setTimeout(() => {
        this.$toast("刷新成功");
        this.refreshUpData.isLoading = true;
      }, 500);
    }
  }
};
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

.item{
	height: 30vw;
	background-color: #fff;
	display: flex;
	align-items: center;
	justify-content: center;
}
</style>

**Comment by chenjiahan** [comment]
codesandbox 可以参考这个模板哈

https://codesandbox.io/s/m5v3f

**Comment by sydyLiu** [comment]
大佬  打开后一直在加载 无法预览




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>; 
发送时间: 2019年10月24日(星期四) 晚上7:00
收件人: "youzan/vant"<vant@noreply.github.com>; 
抄送: "う妖孽、从不妖艳/"<2877506846@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant] [Bug Report] 下拉刷新设置高度后无法滚动 (#4828)




codesandbox 可以参考这个模板哈
 
https://codesandbox.io/s/m5v3f

**Comment by sydyLiu** [comment]
https://codesandbox.io/s/vant-issue-moban-8bthk


已经重现好了  让您久等了




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 晚上7:00
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "う妖孽、从不妖艳/"<2877506846@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] 下拉刷新设置高度后无法滚动 (#4828)




codesandbox 可以参考这个模板哈
 
https://codesandbox.io/s/m5v3f

**Comment by sydyLiu** [comment]
早上好   


https://codesandbox.io/s/vant-issue-moban-kw33z


這裡重現出來了問題. 


------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 晚上7:00
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "う妖孽、从不妖艳/"<2877506846@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] 下拉刷新设置高度后无法滚动 (#4828)




codesandbox 可以参考这个模板哈
 
https://codesandbox.io/s/m5v3f

**Comment by sydyLiu** [comment]
你好, 冒昧的再次打扰您, 因为我这个需求很急, 但是目前有没有别的好办法, 希望您在看到邮件后能帮助我解决这个问题. 不胜感激!


------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 晚上7:00
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "う妖孽、从不妖艳/"<2877506846@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] 下拉刷新设置高度后无法滚动 (#4828)




codesandbox 可以参考这个模板哈
 
https://codesandbox.io/s/m5v3f

**Comment by sydyLiu** [comment]
您好, 冒昧的再次打扰您, 因为我这个需求很急, 但是目前有没有别的好办法, 希望您在看到邮件后能帮助我解决这个问题. 不胜感激!


------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 晚上7:00
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "う妖孽、从不妖艳/"<2877506846@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] 下拉刷新设置高度后无法滚动 (#4828)




codesandbox 可以参考这个模板哈
 
https://codesandbox.io/s/m5v3f

**Comment by chenjiahan** [comment]
你设置了固定高度，不就没法滚动了，应该设置 min-height
