### ISSUE TITLE
[Bug Report] SwipeCell 滑动单元格 

### ISSUE THREAD

**Issue by jiahui336** [youzan/vant#4829]
### 设备 / 浏览器
公众号 

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/swipe-cell" target="_blank">https://youzan.github.io/vant/#/zh-CN/swipe-cell</a>

### 描述问题
SwipeCell 滑动单元格  有多个cell 其他的又滑没有删除 只有第一个有

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by jiahui336** [comment]
?????????

**Comment by chenjiahan** [comment]
使用 https://codesandbox.io/s/m5v3f 创建一个复现该问题的 demo
