### ISSUE TITLE
用cdn的方式引入怎么解析出来的样式不对？

### ISSUE THREAD

**Issue by chaituan** [youzan/vant#483]
![_20171225235838](https://user-images.githubusercontent.com/26025563/34345702-e9da0b04-ea2b-11e7-8cd6-c663b2b963c2.png)

<script>
	new Vue({
	  el: '#app'
	});
</script>

解析出来的 cell  成了一行？

**Comment by chenjiahan** [comment]
见 https://github.com/youzan/vant/issues/461
