### ISSUE TITLE
[Bug Report] list组件触发多个异步onload时，都对list数据进行改写时，list数据不正确的问题

### ISSUE THREAD

**Issue by daniyyer** [youzan/vant#4833]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="https://shop240167.youzan.com/wscshop/showcase/feature/search?q=%E5%9D%9A%E6%9E%9C&kdt_id=47999" target="_blank">https://shop240167.youzan.com/wscshop/showcase/feature/search?q=%E5%9D%9A%E6%9E%9C&kdt_id=47999</a>

### 描述问题
重现链接中的例子为有赞官网良品铺子的案例。当搜索“坚果”关键字时，正确的结果数为15，此时点击销量排序，能正确返回15个结果。为了重现问题，把chrome的network中的throttling改成slow 3g，模拟较慢的网速，此时再点击销量排序后立即点击综合排序，返回的结果会把这两个请求的list拼接起来，个数为30个。想请教下如何处理这种情况比较好。

**Comment by chenjiahan** [comment]
这个其实和 List 关系不大，切换请求条件后，前一个异步请求应该被 cancel 的，但是没有去 cancel，所以出现了这个问题

**Comment by daniyyer** [comment]
是这个原因，只是想看下官方示例有没有比较好的写法。

**Comment by chenjiahan** [comment]
暂时木有示例喔，可以自行研究下..
