### ISSUE TITLE
[Bug Report] 咨询下vant图片上传在app混合开发webview里面会有问题吗，需要安卓设置什么吗

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#4834]
### 设备 / 浏览器
安卓

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/" target="_blank">https://youzan.github.io/vant/</a>

### 描述问题
如上

**Comment by chenjiahan** [comment]
对安卓不太了解，vant 的图片上传里面用的是原生的 input type="file"，应该不用需要额外的设置

**Comment by Thlq** [comment]
我们现在app里面嵌套的h5然后有一个点击上传图片的页面，这个页面在浏览器都是正常的（支付宝，微信，自带浏览器），但是在他们app里面点击上传图片没有反应，关于安卓这块我不是很懂，如果大佬知道的话，可以帮我解下疑惑，谢谢

**Comment by chenjiahan** [comment]
这块你应该找 app 的同学排查哈，我们也没法提供帮助

**Comment by Benny233** [comment]
> 对安卓不太了解，vant 的图片上传里面用的是原生的 input type="file"，应该不用需要额外的设置

你好 我也遇到这个问题 请问你最后解决了吗 可以告诉我是怎么解决的吗

**Comment by raybon-lee** [comment]
竟然没答案，这个安卓模拟器不支持，真机也不行， `this.$refs.uploadForm.chooseFile()` 调用方式是这种 苹果的正常
