### ISSUE TITLE
[Bug Report] array size is not a small enough positive intege报错 

### ISSUE THREAD

**Issue by watsonLidaye** [youzan/vant#4836]
### 设备 / 浏览器
苹果手机

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="http://test.manager.txlinker.com" target="_blank">http://test.manager.txlinker.com</a>

### 描述问题
测试账号zhongxin001 ,密码123456,
在主页面筛选列表，点击日期选择ios报错

**Comment by JakeLaoyu** [comment]
看不到源码

**Comment by watsonLidaye** [comment]
git@github.com:watsonLidaye/vue_vant_timePick_error.git  出错代码在 pages/main/main.vue

**Comment by watsonLidaye** [comment]
@JakeLaoyu 已经加你协作了

**Comment by JakeLaoyu** [comment]
`minDate: new Date('2000-1-1')` safari Date 不支持这种时间格式，可以去了解一下

**Comment by watsonLidaye** [comment]
为什么其他的地方，create.vue中采用这种方式是ok的？create.vue中也是用日期选择器
