### ISSUE TITLE
area 省市区数据来源vuex，切换省可以，滑动切换市，区时会自动恢复到默认第一个

### ISSUE THREAD

**Issue by hymore** [youzan/vant#4842]
省的编号：例：A12
市的编号：例：A12B345
区的编号：例：A12B345C798
当把area-list 数据在组件data中直接定义时，没有问题，但是取vuex中的数据作为area-list时就有这个问题，即使把vuex中的数据深拷贝到组件也不行

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
