### ISSUE TITLE
[Feature Request] Uploader组件before-delete等 Api 能否返回删除元素的下标

### ISSUE THREAD

**Issue by OoToToO** [youzan/vant#4844]
### 这个功能解决了什么问题
在删除图片时可以操作其它数组，仅仅靠before-delete返回的file参数有时候无法准确操作

### 描述您想要的解决方案
返回删除元素的下标

### 建议的API是什么样的
beforeDelete(file,index)

**Comment by chenjiahan** [comment]
现在就支持的，请仔细阅读文档

**Comment by OoToToO** [comment]
看到了，是我的版本没更新。 谢谢！


| |
hly5474
|
|
邮箱：hly5474@163.com
|

Signature is customized by Netease Mail Master

在2019年10月26日 15:00，neverland 写道：

Closed #4844.
