### ISSUE TITLE
[Bug Report] 同一级别多个field只显示一个

### ISSUE THREAD

**Issue by hainuo** [youzan/vant#4854]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://jsfiddle.net/wn3ajyec/15/" target="_blank">https://jsfiddle.net/wn3ajyec/15/</a>

### 描述问题
同一级别有多个van-field标签时 只编译一个 之后的都不显示。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/461
