### ISSUE TITLE
[Bug Report] vant-tab粘性布局，vant-sticky没作用

### ISSUE THREAD

**Issue by rookieliuyan** [youzan/vant#4857]
### 设备 / 浏览器
移动端，ios，安卓h5

### Vant 版本
2.2.9

### Vue版本
2.6.6

### 重现链接
<a href="https://www.baidu.com" target="_blank">https://www.baidu.com</a>

### 描述问题
vant-table不能吸顶,不知道是使用问题还是bug，因项目问题无法提供重现链接，只好用一个链接代替，望理解

**Comment by chenjiahan** [comment]
提供下代码截图？

**Comment by rookieliuyan** [comment]
![image](https://user-images.githubusercontent.com/26427898/67730157-20127c00-fa2f-11e9-9936-edd544f9071b.png)

**Comment by chenjiahan** [comment]
看起来没啥问题，能否提供一下 codesandbox 复现链接呢
