### ISSUE TITLE
[Bug Report] Checkbox 复选框 全选 反选

### ISSUE THREAD

**Issue by html972051267** [youzan/vant#4858]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/m5v3f" target="_blank">https://codesandbox.io/s/m5v3f</a>

### 描述问题
全选反选无问题，但是点击全选后，取消1个选择，点击反选，正常情况应该全部取消选中，但是会出现选择bug

**Comment by chenjiahan** [comment]
无效的复现链接，请提供正确的复现链接

**Comment by LooMr0** [comment]
反选 ：对已经选中的选项进行反向选择！这个不是BUG，您说的应该是全不选才对。

**Comment by chenjiahan** [comment]
是这样滴，全不选的话，`toggleAll(false)` 即可

**Comment by html972051267** [comment]
您好 ，我当前期望的点击全选全部选中，这个怎么满足呢 文档例子不足以支持，希望百忙中回复谢谢。这种状态下  点击反选 全部取消选中。



------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 下午5:47
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "蘑菇云.Six"<972051267@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] Checkbox 复选框 全选 反选 (#4858)




Closed #4858.

**Comment by chenjiahan** [comment]
上面写了呀，toggleAll(false) 是取消全选

**Comment by html972051267** [comment]
谢谢谢谢 ，解决了 没有注意到，非常感谢




------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 晚上7:20
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "蘑菇云.Six"<972051267@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Bug Report] Checkbox 复选框 全选 反选 (#4858)




上面写了呀，toggleAll(false) 是取消全选
