### ISSUE TITLE
弹出层Picker无法滑动选择

### ISSUE THREAD

**Issue by MrRiven** [youzan/vant#4860]
IOS : 10.2.1
微信：7.0.5

微信内小程序Webview打开弹出层Picker无法滑动选择

附官网demo：https://youzan.github.io/vant/mobile.html#/zh-CN/address-edit

微信中webview / H5 直接打开都存在问题

![image](https://user-images.githubusercontent.com/20854345/67666359-99b25780-f9a6-11e9-903e-c92c2ec0f169.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
