### ISSUE TITLE
[Feature Request] 新增 Empty 空状态组件

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#4862]
### 这个功能解决了什么问题
目前项目是自己写了个 Empty 组件来用，页面有内容为空时都要用到的，希望 VantUI 能提供此组件

### 描述您想要的解决方案
新增 Empty 空状态组件，可参考：https://vue.ant.design/components/empty-cn/

### 建议的API是什么样的
新增 Empty 空状态组件，可参考：https://vue.ant.design/components/empty-cn/

**Comment by chenjiahan** [comment]
会考虑添加这个组件

**Comment by 1014156094** [comment]
> 会考虑添加这个组件

阿里嘎多~

**Comment by chenjiahan** [comment]
已在 2.6.0 版本添加👌
