### ISSUE TITLE
Dialog自定义组件调用出错

### ISSUE THREAD

**Issue by mlb0315** [youzan/vant#4863]
Dialog自定义组件调用出错，遮罩层存在穿透问题，而且设置了确认，取消按钮，均无法正常关闭弹窗，而是点击除确认，取消按钮以外的任意一处，均可关闭弹窗。而采取this.$dialog.alert({message: '弹窗内容' });，则一切正常。希望官方能早点给答复！！！！！！

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
