### ISSUE TITLE
[bug report] uploader组件在安卓的qq和微信浏览器卡顿问题

### ISSUE THREAD

**Issue by zcxwhan** [youzan/vant#4864]
设备 / 浏览器:
移动端，安卓微信浏览器，qq浏览器

Vant 版本：
2.2.7

Vue版本：
2.6.10

描述问题：
uploader组件在安卓的qq和微信浏览器，点击预览图弹出大图滑动或者关闭时候都卡顿，安卓其他浏览器没问题，苹果的safari也没问题。求解决方案。
补充：
是点击拍照后，生成了预览图，然后点预览图到大图后就卡顿了。

**Comment by chenjiahan** [comment]
直接打开 ImagePreview 的示例文档，会有这个问题吗

**Comment by zcxwhan** [comment]
> 
> 
> 直接打开 ImagePreview 的示例文档，会有这个问题吗
============================================================
你好。ImagePreview没有问题。uploader如果没有上传新的图片也不会卡顿，所以很好奇问题原因。是不是因为图片转为base64卡顿了？但是在ios的微信浏览器以及安卓的其他浏览器如UC或者小米均没有问题。希望能帮忙排查下问题原因，谢谢。

**Comment by chenjiahan** [comment]
可能与 base64 有关，是不是图片很大，或者机器配置比较差？

**Comment by zcxwhan** [comment]
> 
> 
> 可能与 base64 有关，是不是图片很大，或者机器配置比较差？
==============================================================小米8，配置应该没问题，图片就是正常拍照上传的，一个4M，用UC或者小米浏览器都是没问题的，所以还是希望能详细查下问题具体原因。

**Comment by leedalei** [comment]
我有你这个类似的问题，我是点击上传的时候需要对base64裁剪掉前面的一部分字符串，刚开始也是很卡，后来我换成了异步裁剪就好多了。

**Comment by zhangliyuan-chance** [comment]
我也遇到这个问题了，图片大于3m左右就会很卡顿。

**Comment by Pingren** [comment]
这个问题我曾经用别的预览组件的时候也遇到过，当时的解决方案是自己参考网上的资料加了一个压缩方法，选择图片后先把图片压缩在存入预览组件。

压缩是利用 canvas 的，可以顺便修复手机拍照图像 EXIF 的 orientation 丢失问题。

**Comment by chenjiahan** [comment]
可以使用楼上的方法，通过压缩来解决图片性能问题
