### ISSUE TITLE
[Feature Request] search组件是否可以增加多个待选关键字阴影分割且末尾有清理按钮

### ISSUE THREAD

**Issue by jonnywang** [youzan/vant#4866]
### 这个功能解决了什么问题
美观实用，快速删除选定的待选关键词

### 描述您想要的解决方案
search组件是否可以增加多个待选关键字阴影分割且末尾有清理按钮，类似移动版京东，淘宝

### 建议的API是什么样的
设置开关是否开启

**Comment by chenjiahan** [comment]
暂无计划支持
