### ISSUE TITLE
[Bug Report] 使用NumberKeyboard数字键盘，对应 输入框没有光标

### ISSUE THREAD

**Issue by micky9292** [youzan/vant#4867]
### 设备 / 浏览器
ios

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?repo=Vant" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?repo=Vant</a>

### 描述问题
使用NumberKeyboard数字键盘，对应 输入框没有光标

**Comment by chenjiahan** [comment]
输入框光标和 NumberKeyboard 组件没有关联喔，输入框是完全独立的

**Comment by sanjin123** [comment]
我也遇到了这个问题，field和numberkeyboard双向绑定后，弹出numberkeyboard后field没有光标。

**Comment by xiang0308** [comment]
> 我也遇到了这个问题，field和numberkeyboard双向绑定后，弹出numberkeyboard后field没有光标。

@chenjiahan 没有光标的问题什么时候可以提供支持？还是挺影响用户体验的~~
