### ISSUE TITLE
Uploader 图片上传 安卓的浏览器，多选模式只能上传一张图片

### ISSUE THREAD

**Issue by fekata** [youzan/vant#487]
Uploader 图片上传  "vant": "^0.11.15";
安卓的浏览器，从相册选择多张图片后，before-read和after-read只能读取到单张图片；
multiple已经增加；
ps:ios正常

**Comment by chenjiahan** [comment]
@fekata uploader 使用了 原生的 multiple 属性，在安卓下确实存在兼容性问题，目前没有什么好的方式去解决 
https://caniuse.com/#search=multiple
