### ISSUE TITLE
[Bug Report] IOS13 van-popup position="bottom"  从右侧弹出，有卡顿

### ISSUE THREAD

**Issue by jewool** [youzan/vant#4870]
### 设备 / 浏览器
ios app 内嵌web

### Vant 版本
1.6.24

### Vue版本
2.6.10

### 重现链接
<a href="http://106.14.213.98:91/#/collection" target="_blank">http://106.14.213.98:91/#/collection</a>

### 描述问题
IOS13 van-popup position="bottom" [从右侧弹出，有卡顿。IOS12](url) android 浏览器均正常

   <van-popup v-model="showProviceCitysArea" position="bottom">
            <van-area :area-list="areaList" :columns-num="3" :value="defaultSelect" title="请选择省市区"
                      @cancel="showProviceCitysArea=false"
                      @confirm="areaSelectConfirm"/>
        </van-popup>

**Comment by chenjiahan** [comment]
如果是 app 内嵌出现这个问题的话，建议看下是不是用的 UIWebView，替换成 WKWebView 性能会好一些

**Comment by Jen0** [comment]
我也遇到了类似的问题，7PLUS IOS13 van-popup 设置 position="bottom" 效果却是，先从右侧弹出一半，然后全部弹出，带有卡顿。但是有时候却是正常的，时好时坏，异常效果出现概率在50%左右。请问问题解决了吗？

**Comment by zhangbinzhbb** [comment]
同上，ios13机器上会出现这个问题

**Comment by zhangbinzhbb** [comment]
ios13 第一次点击向右弹出，不会出现卡顿问题，第二次再次点击时，向右弹出失效了，直接先弹到中间，卡顿一会，然后就弹到顶部了
