### ISSUE TITLE
[Bug Report] 当<Tab>组件遇到<List>组件，会擦出怎么样火花？

### ISSUE THREAD

**Issue by microkof** [youzan/vant#4872]
### 设备 / 浏览器
任意

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/list" target="_blank">https://youzan.github.io/vant/#/zh-CN/list</a>

### 描述问题
目前有个项目，要把List组件塞到Tab组件里，默认状态下，确实挺好用的。

数据结构大致是：

```
tabList: [
  {
    title: 'A',
    loading: false,
    finished: false,
    itemList: [
      'a','b','c', .......
    ]
  },
  {
    title: 'B',
    loading: false,
    finished: false,
    itemList: [
      'a','b','c', .......
    ]
  }
]
```

后来我这有一个需求，就是在B List数据全加载之后，清空B List，重新onload B List。

这时候我的做法是将这个B的itemList清空，并且finished从true改回false，然而，切换AB，各种瞎按，也并不能让B重新onload

所以想问一下，如何让B重新onload？

**Comment by anrananran** [comment]
关闭List的自动onload，手动load第一页数据

**Comment by chenjiahan** [comment]
可以在切换后调用一下 List 的 check 方法
