### ISSUE TITLE
[Feature Request] Picker 组件是否可以给选项增加图标显示？

### ISSUE THREAD

**Issue by yulimchen** [youzan/vant#4878]
### 这个功能解决了什么问题
每个选项增加图标辨识，更加友好。最近业务需要在选择器里显示安卓   iOS 平台的游戏选择列表，能增加图标显示更好。
![Snipaste_2019-10-30_16-34-31](https://user-images.githubusercontent.com/5179249/67842324-e3c94380-fb34-11e9-8e1a-a126368186fd.png)

### 描述您想要的解决方案
Picker 中增加相关 API，或者 columns 中的每项数据增加个 icon 字段来显示图标。

### 建议的API是什么样的
`<van-picker :columns="columns" icon="xxx" />`

**Comment by chenjiahan** [comment]
Picker 的 text 可以传 html 的，可以通过 html 来实现。暂无计划在组件内支持喔
