### ISSUE TITLE
【BUG】版本1.6.19 list组件

### ISSUE THREAD

**Issue by q867427795** [youzan/vant#4881]
版本号：1.6.19
机型：苹果7，苹果8
浏览器：微信内置浏览器 H5页面
组件：popup 配合 list
业务逻辑： 弹出遮罩后，选择单个事项

愿景： 可以在ios上面进行滑动

结果： 苹果7手机只能通过手指点击，进行选择（偶尔能够进行滑动）
            苹果8手机没有任何问题

**Comment by chenjiahan** [comment]
能否提供 codesandbox 复现链接看下

**Comment by q867427795** [comment]
> 能否提供 codesandbox 复现链接看下

得用微信关注微信公众号，进行项目演示。现在已经上线使用了~~

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

issue 里需要提供能复现该问题的 codesandbox 链接
