### ISSUE TITLE
【Bug Report】版本V2.2.10 list组件会无线加载，达到页面底部后不会暂停

### ISSUE THREAD

**Issue by q867427795** [youzan/vant#4883]
版本号：2.2.10
浏览器：电脑端 Chrome浏览器 
               微信内置浏览器
组件：van-list组件
业务逻辑：无限滚动加载，内容到底底部后，依然会无限加载数据

愿景： 数据到达底部后，进行滑动才加载下一页数据

结果： 数据无限请求，只有当数据全部加载完毕，list的load才不会执行

在issues内，找到的 (https://github.com/youzan/vant/issues/4872)当<Tab>组件遇到<List>组件，会擦出怎么样火花？经测试无效，还是会出现问题

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

issue 里需要提供能复现该问题的 codesandbox 链接
