### ISSUE TITLE
vant-dialog 使用问题

### ISSUE THREAD

**Issue by wangybm** [youzan/vant#4884]
全局注册
![image](https://user-images.githubusercontent.com/22055254/67911395-597af100-fbc1-11e9-944c-d23a1e45f6a2.png)
FormDialog.vue中使用没有问题

![image](https://user-images.githubusercontent.com/22055254/67911406-64358600-fbc1-11e9-9d9d-0c6d42126eae.png)
TipDialog.vue中使用报错
![image](https://user-images.githubusercontent.com/22055254/67911451-8cbd8000-fbc1-11e9-8e5a-7f37afd508f4.png)
报错信息
![image](https://user-images.githubusercontent.com/22055254/67911471-9f37b980-fbc1-11e9-8260-ac9ef01f5899.png)

**Comment by chenjiahan** [comment]
仔细看报错信息，报错里面的标签名是 'vant-dialog'，正确的名称是 'van-dialog'
