### ISSUE TITLE
van-area 组件点击确定后会刷新页面！

### ISSUE THREAD

**Issue by xsdream** [youzan/vant#4885]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by xsdream** [comment]
如果页面在  localhost:8081/?#/entryRegistrationFormH5  下点确定按钮不会刷新
如果页面在  localhost:8081/#/entryRegistrationFormH5  下点确定按钮会刷新
区别在于 ？

**Comment by xsdream** [comment]
![image](https://user-images.githubusercontent.com/31870384/67914434-11f96280-fbcb-11e9-8ac6-b4b626c1f52f.png)

**Comment by xsdream** [comment]
如果使用路由的 history 模式，也会导致页面的刷新~

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by xsdream** [comment]
@chenjiahan https://codesandbox.io/s/vant-issue-moban-g574u?fontsize=14

**Comment by xsdream** [comment]
写在表单里面了，表单提交了，已解决。
