### ISSUE TITLE
[Bug Report] CheckBox组件在 bf-cahe（浏览器前进/后退缓存；访问其他链接如：百度）后CheckBox显示错误

### ISSUE THREAD

**Issue by Liuninggithub** [youzan/vant#4887]
### 设备 / 浏览器
iPhone8 iOS13.1.3 微信和Safari

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://metis-storm-test.oss-cn-hangzhou.aliyuncs.com/liun/bf-cache.html" target="_blank">https://metis-storm-test.oss-cn-hangzhou.aliyuncs.com/liun/bf-cache.html</a>

### 描述问题
iPhone8 iOS13.1.3 微信和Safari中 CheckBox组件在 bf-cahe（访问其他链接如：百度）后CheckBox显示错误; 选中的效果刚好相反；true的时候没有选中；false却选中了；哪怕手动刷新也不行

**Comment by Liuninggithub** [comment]
初步怀疑是 vue 的 transition 组件引起的因为我自己写了个测试的CheckBox 在不用transition组件的情况下是OK；一旦加上transition就出问题了

**Comment by chenjiahan** [comment]
跟这个问题类似：https://github.com/youzan/vant/issues/4749

由于是 iOS13.1 下 Vue 内置 transition 的问题，组件库内没有方法去处理，先 close 了。

这个问题要么等 Vue 去尝试兼容，要么等 iOS 修复了
