### ISSUE TITLE
[Bug Report] Sticky 粘性布局

### ISSUE THREAD

**Issue by html972051267** [youzan/vant#4888]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/sticky" target="_blank">https://youzan.github.io/vant/#/zh-CN/sticky</a>

### 描述问题
offset-top="50" 吸顶单位px    请问怎么设置rem 类型的

**Comment by chenjiahan** [comment]
由于 offset-top 涉及位置计算的逻辑，所以不支持 px 以外的单位，如果是 rem 单位，请自行计算并转换成 px 后传入
