### ISSUE TITLE
[Bug] 在 Nuxt.js 中， 修改样式变量无效

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#4889]
nuxt 版本：2.10.2

在 nuxt.config.js 中配置 less.modifyVars，颜色变量改为黑色
![image](https://user-images.githubusercontent.com/16074662/67932429-d9737c00-fbfe-11e9-8b6b-f2a52e11dc18.png)

结果还是绿色的，各种方法都试过了，结果都一样是绿色的~
![image](https://user-images.githubusercontent.com/16074662/67932639-3707c880-fbff-11e9-97fb-32341f728494.png)

另外建议文档增加 Nuxt.js 修改样式变量的方法，解决更多人在 Nuxt.js 中疑问，本来想给 codesandbox 链接的，在 codesandbox 安装 nuxt 后，一直显示 Resolving Dependencies...，完全卡住了[捂脸.jpg]

**Comment by chenjiahan** [comment]
提供个复现仓库看下？

**Comment by 1014156094** [comment]
> 提供个复现仓库看下？

不好意思，来晚了，地址：https://codesandbox.io/s/5dgti

**Comment by chenjiahan** [comment]
你得引入 less 文件，而不是 css 文件，仔细看文档

**Comment by 1014156094** [comment]
> 你得引入 less 文件，而不是 css 文件，仔细看文档

你是指哪里呢，我是写的 less 没错噢~

**Comment by 1014156094** [comment]
> 你得引入 less 文件，而不是 css 文件，仔细看文档

对不起，我的，没注意到 less。。
