### ISSUE TITLE
Tabs 标签页不能自定义颜色吗？

### ISSUE THREAD

**Issue by EdikWang** [youzan/vant#489]
Tabs 标签页不能自定义颜色吗？
![image](https://user-images.githubusercontent.com/23392780/34404074-f3eb2e90-ebe6-11e7-89ee-6fabb87f406d.png)

**Comment by chenjiahan** [comment]
@EdikWang 直接通过 css 覆盖样式即可

**Comment by EdikWang** [comment]
好的谢谢
