### ISSUE TITLE
[Feature Request] <Uploader>组件的预览图期望加上close方法（就像<ImagePreview>组件一样）

### ISSUE THREAD

**Issue by microkof** [youzan/vant#4893]
### 这个功能解决了什么问题
在安卓webview开发中，用户习惯上会使用物理回退键关闭《Uploader》组件的预览图。开发者可以通过拦截物理键点击，可以以编程方式执行关闭预览图的方法，但是。。。。Vant并没有提供关闭《Uploader》组件预览图的方法。

### 描述您想要的解决方案
希望提供编程方式关闭预览图的close方法，就像《ImagePreview》组件一样。

### 建议的API是什么样的
我暂时没建议，因为《Uploader》组件不是函数调用方式。请官方想想办法。

或者，由于Uploader是后台调用了ImagePreview组件的，所以，可以给Uploader组件设一个imagePreviewComponentName="abc"，然后，根据用户提供的名称来new ImagePreview组件，这样用户调用abc.close()就可以关闭预览图。

**Comment by chenjiahan** [comment]
下个版本会在 Uploader 上添加一个实例方法 closeImagePreview，通过 ref 可以拿到 Uploader 实例来调用该方法。

**Comment by chenjiahan** [comment]
已在 2.2.11 版本支持
