### ISSUE TITLE
[Feature Request] 建议把SwipeCell 滑动单元格，左右两边出来时，把主体内容区域的宽度变为减去左右两边出现的按钮的宽度

### ISSUE THREAD

**Issue by renlixin** [youzan/vant#4894]
### 这个功能解决了什么问题
如果内容过长，宽度100%的时候，往右边滑动单元格，动画直接把单元格直接往右移动，导致右半部分的内容被截断

### 描述您想要的解决方案
在滑块出现的时候，建议把主体内容的宽度减去左边或者右边出现的滑块的宽度，以适应屏幕

### 建议的API是什么样的
加一个属性或者是什么，autoSize：Boolean

**Comment by renlixin** [comment]
目前想实现这个功能还得改源码，
![image](https://user-images.githubusercontent.com/29976673/67938249-15600e80-fc0a-11e9-9ab9-060a61217c6b.png)
![image](https://user-images.githubusercontent.com/29976673/67938280-26a91b00-fc0a-11e9-96c9-826b2e6e8898.png)
很简单，但很实用

**Comment by renlixin** [comment]
如果可以我可以提个PR

**Comment by chenjiahan** [comment]
不是很明白你描述的场景，能提供个 codesandbox 链接看下吗
