### ISSUE TITLE
[Bug Report] 日期时间选择器为什么不支持选择秒

### ISSUE THREAD

**Issue by hkxxxx** [youzan/vant#4895]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
日期时间选择器控件不支持选择秒

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4259
