### ISSUE TITLE
van-list 上拉加载更多配合scrollTop的问题

### ISSUE THREAD

**Issue by hujindo123** [youzan/vant#4896]
**设备 / 浏览器**
谷歌浏览器移动端调试模式iPhone6/7/8

**Vant 版本**
2.2.5

**Vue版本**
2.6.10

**描述问题**
我使用van-list 做了一个聊天消息的功能，就像和微信一样，新的消息在底部，历史消息在顶部，上拉的时候历史消息会出现，我现在实现是用的普通的ajax请求，**现在的问题是** 我第一次进去加载的新消息通过：
  var scrollTop = this.$el.querySelector('.data_list');
   scrollTop.scrollTop = scrollTop.scrollHeight;
来控制最新的消息在底部  这也就触发了 onLoad 方法 一直是无限加载，求助怎么解决这个冲突

**Comment by chenjiahan** [comment]
能否提供下 codesandbox 复现链接看下

**Comment by gm-fire** [comment]
请问楼主解决了吗?能否分享一下解决方案,谢谢!
