### ISSUE TITLE
[Bug Report] 自动按需引入组件

### ISSUE THREAD

**Issue by HappyLeiLei** [youzan/vant#4897]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
暂无

### 描述问题
环境 macOS 10.14.6
编辑器 vscodde
使用环境 vuecli4.0.5

根据推荐配置按需加载模块配置后页面组件可渲染单样式文件没有按需加载
在main.js下引入全局样式文件后可正常渲染组件样式否则无法渲染样式

**Comment by chenjiahan** [comment]
请确认你正确配置了 babel-plugin-import 插件并生效
