### ISSUE TITLE
[Bug Report] Grid 组件 使用插槽slot 自定义 icon 后 ，设置dot 或 info 属性时  属性不生效

### ISSUE THREAD

**Issue by Gzbox** [youzan/vant#4899]
### 设备 / 浏览器
 MacOS 10.13.4 / Google Chrome 版本 78.0.3904.87（正式版本）（64 位） 

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://jsfiddle.net/DingZhen/k0j9r6o8/8/" target="_blank">https://jsfiddle.net/DingZhen/k0j9r6o8/8/</a>

### 描述问题
Grid 组件 使用插槽slot 自定义 icon 后 ，设置dot 或 info 属性时  属性不生效

**Comment by chenjiahan** [comment]
下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 2.2.11 版本修复

**Comment by jzyzxx** [comment]
2.12.16版本也存在这个问题
