### ISSUE TITLE
[Feature Request] Toast 组件API 可完善  例如closeOnClickOverlay参数 $on("closed")事件等

### ISSUE THREAD

**Issue by zrnokia5230** [youzan/vant#4900]
### 这个功能解决了什么问题
Toast 组件中的 onClose  API 介绍为关闭时的回调。  实测  duration 后的回调，主动点击关闭时不触发。
开启closeOnClick = true 参数后  主动点击后的关闭事件不会响应传进来的 onClose ，需用$on("closed")响应（API文档貌似没提及）。
设置 closeOnClickOverlay = true 后 点击 外部overlay也可以响应$on("closed")的事件 （API文档貌似没提及）

### 描述您想要的解决方案
1. closeOnClickOverlay参数  加入toast.d.ts 定义，并在文档中说明。
2. 文档和示例中提及$on("closed") 。
3. 内部执行 $emit("closed") 时 同时响应 传入的 onClose 。

### 建议的API是什么样的
1. closeOnClickOverlay参数  加入toast.d.ts 定义，并在文档中说明。
2. 文档和示例中提及$on("closed") 。
3. 内部执行 $emit("closed") 时 同时响应 传入的 onClose 。

![Snipaste_2019-11-01_18-56-05](https://user-images.githubusercontent.com/25945398/68020389-4d825280-fcd9-11e9-8d3f-7228cd07ed58.png)

**Comment by chenjiahan** [comment]
这些都属于未开放给使用者的属性，没写在文档里，我们会先评估下

**Comment by chenjiahan** [comment]
已在 2.2.13 版本支持 closeOnClickOverlay 参数，$on 绑定事件的用法不计划支持
