### ISSUE TITLE
[Bug Report] 无法引入tabs组件

### ISSUE THREAD

**Issue by chaoanweng** [youzan/vant#4904]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://www.baidu.com" target="_blank">https://www.baidu.com</a>

### 描述问题
在vue的main.js 全局引入Vant ， card组件可用，但是tabs组件不可用用。报这个错[Vue warn]: Injection "vanTabs" not found
Vue版本3.11.0

**Comment by chenjiahan** [comment]
请确认下你的 Vue 版本在 2.5.0 以上，并按照文档使用 Tab 组件

还有 3.11.0 是 vue-cli 版本，不是 Vue 版本
