### ISSUE TITLE
area 里面的columns-placeholder没效果

### ISSUE THREAD

**Issue by Dyoungb** [youzan/vant#4906]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
需要升级到 2.2.5 版本以上才支持喔，后续会在文档里标注下
