### ISSUE TITLE
[Bug Report] list 不断加载

### ISSUE THREAD

**Issue by 2587593709** [youzan/vant#4908]
### 设备 / 浏览器
Chrome

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="http://static.daily.yunhutech.com/mjkc-mall/#/goodList" target="_blank">http://static.daily.yunhutech.com/mjkc-mall/#/goodList</a>

### 描述问题
list 不断加载

**Comment by 2587593709** [comment]
官方提到的方法都试过了，没有得到解决

**Comment by chenjiahan** [comment]
麻烦提供下 codesandbox 复现链接

**Comment by yimihuakai** [comment]
我也遇到了 这个问题 。https://github.com/youzan/vant/issues/4941 @chenjiahan ，麻烦看下～

**Comment by 2587593709** [comment]
codesandbox 试过了是可以的，但是npm i vant -S到本地的就是有问题，希望官方检查一下

**Comment by chenjiahan** [comment]
建议你检查下是不是项目里有什么地方的代码引起了这个问题，codesandbox 和 npm 安装的组件代码是一样的

**Comment by 2587593709** [comment]
找到原因了#app {
  padding-bottom: 54px;
}
复现链接https://mftx2.csb.app/

**Comment by 2587593709** [comment]
https://mftx2.csb.app/
复现链接

**Comment by 2587593709** [comment]
问题解决了，html,body {overflow-x: hidden;}造成的

**Comment by chenjiahan** [comment]
@ystarlongzi 这种情况貌似确实会判断错误，当时 [issue](https://github.com/youzan/vant/issues/3823) 讨论的情况中没考虑到这块

**Comment by ystarlongzi** [comment]
嗯嗯，稍等我确认下这个问题

**Comment by ystarlongzi** [comment]
@chenjiahan 

感觉这个问题不大好修复，因为通常情况下，如果一个元素如果为滚动容器，那它需要满足
 1. `overflow-y` 取值为 `scroll` 或 `auto`
 2. 且显示设置了 `height` 属性（比如通过 `style` 或在 css 文件里设置）

但目前面临的问题是，通过 js 很难判断元素是否有显示设置过 `height` 属性。所以，代码里就隐藏着这样的逻辑，如果元素的 `overflow-y` 取值为 `scroll` 或 `auto` 时，我们就会假设用户应该是会对这个元素有显示设置了 `height` 属性，所以它是一个滚动容器

然后，回到这个问题上，因为对元素设置了 `overflow-x: hidden`，那该元素的 `overflow-y` 取值会是 `auto`，而不是默认值 `visible`（这个有点出乎意料），所以，下面两种写法是等价的：

``` less
// 法 1
html, body {
  overflow-x: hidden;
}

// 法 2
html, body {
  overflow-x: hidden;
  overflow-y: auto;
  // 理论情况下，因为设置了 overflow-y，所以，我们会期待这里会有个 height 设置的，比如：
  // height: 100%;
}
```

因此，会导致代码里获取的滚动容器是 body（但其实应该是 window），进一步导致下面的判断是恒为真，所以 list 会不断触发加载 :joy:

https://github.com/youzan/vant/blob/e21c047306d5c886f8ff60fca039312830889754/src/list/index.js#L98

**Comment by ystarlongzi** [comment]
我在想一下 #3443 提到的边界判断条件的方案是否合理，如果用最之前的方案会不会也会有这个问题

**Comment by chenjiahan** [comment]
> 通过 js 很难判断元素是否有显示设置过 height 属性

确实，判断 height 确实是比较困难的，尤其是可能存在 max-height 之类的属性..

> 我在想一下 #3443 提到的边界判断条件的方案是否合理，如果用最之前的方案会不会也会有这个问题

好的，辛苦 🙆

**Comment by ystarlongzi** [comment]
> 我在想一下 #3443 提到的边界判断条件的方案是否合理，如果用最之前的方案会不会也会有这个问题

https://github.com/youzan/vant/blob/537ecc521e394bcc7f28d2fa4ba82cdb80e6d046/packages/list/index.js#L102-L103

之前的方案也会有类似的问题，本质上它也是根据 `<vant-list />` 的高度和滚动容器高度的差值来判断是否到达底部

而如果滚动容器未显示的设置高度，那它的高度基本上可以等价于 `<vant-list />` 的高度，导致第 103 行也会一直返回 true

**Comment by chenjiahan** [comment]
嗯嗯，那这种情况先不考虑，或者在『常见问题』里给个提示

**Comment by heath-l** [comment]
这个问题怎么解决啊？

**Comment by ystarlongzi** [comment]
> 这个问题怎么解决啊？

@heath-l 如果你有这样设置样式 `html, body { overflow-x: hidden; }` ，就再加一个 `height: 100%;` 属性
