### ISSUE TITLE
[Feature Request] 图片预览组件（ImagePreview）的页面返回关闭，能不能先阻止页面返回再关闭

### ISSUE THREAD

**Issue by leedalei** [youzan/vant#4909]
### 这个功能解决了什么问题
现在的效果是，预览关闭了但是页面也返回了，这就很难受，其实大部分人只是想第一次返回先关闭预览，然后返回才回退页面。

### 描述您想要的解决方案
第一次返回是关闭图片预览，之后的返回才是回退页面。现在我是用路由守卫来实现这个功能，在打开预览和关闭预览的时候通过改变vuex全局变量传递给路由守卫来控制跳转，但是imagePreview这个组件也没有onOpen之类的事件回调，这就更难受了。

### 建议的API是什么样的
第一次返回是关闭图片预览，之后的返回才是回退页面。

**Comment by chenjiahan** [comment]
这个涉及到路由控制了，组件内不会去改变路由的，建议自行实现
