### ISSUE TITLE
[Bug Report] 微信中NoticeBar文字滚动时空心样式Tag边框显示有问题

### ISSUE THREAD

**Issue by abusym** [youzan/vant#4910]
### 设备 / 浏览器
微信

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="http://47.93.25.23/#/" target="_blank">http://47.93.25.23/#/</a>

### 描述问题
在华为手机浏览器、Chrome没有问题。用微信打开链接，如果NoticeBar文字滚动，页面最下方的空心样式Tag边框显示不全，如果减少NoticeBar文字数量，不滚动的话，显示是正常的。在其他页面也做了这个测试，问题能够复现。

**Comment by chenjiahan** [comment]
这个属于浏览器的渲染 bug，木有办法解决噢
