### ISSUE TITLE
[Bug Report] 魅族16s图片上传组件点击无反应

### ISSUE THREAD

**Issue by leedalei** [youzan/vant#4911]
### 设备 / 浏览器
小程序webview

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/" target="_blank">https://codesandbox.io/s/</a>

### 描述问题
网页放置在小程序webview中，暂无重现链接。手机是魅族flym8.0，其他的手机点击都有弹出选择文件，但是魅族点了没反应。

**Comment by chenjiahan** [comment]
建议找微信反馈下，这个不是组件的问题
