### ISSUE TITLE
Picker 选择器 

### ISSUE THREAD

**Issue by 810505339** [youzan/vant#4916]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/picker</a>

### 描述问题
点击取消或者点击空白部分的时候 defaultIndex 修改成已选择，并没有恢复到选择之前的

**Comment by chenjiahan** [comment]
defaultIndex 只是一个初始值，如果需要重置，请使用 setIndexes 等实例方法

**Comment by 810505339** [comment]
第一次还没有弹出的时候picker组件不存在 只有弹出以后这个节点才会存在 这个问题怎么解决呢？







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2019年11月4日(星期一) 晚上7:37
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "810505339"<810505339@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] Picker 选择器  (#4916)




defaultIndex 只是一个初始值，如果需要重置，请使用 setIndexes 等实例方法

**Comment by chenjiahan** [comment]
可以关闭弹窗的 lazy-render 属性

**Comment by 810505339** [comment]
请问一下文件上传Uploader&nbsp;capture=‘camera’&nbsp; 直接调用摄像头为什么没有效果呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2019年11月5日(星期二) 上午8:07
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "810505339"<810505339@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] Picker 选择器  (#4916)




可以关闭弹窗的 lazy-render 属性

**Comment by chenjiahan** [comment]
这个属性要看系统是否支持的喔
