### ISSUE TITLE
[Bug Report] list滚动加载

### ISSUE THREAD

**Issue by linshuoe** [youzan/vant#4917]
### 设备 / 浏览器
iphone7/微信浏览器

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="http://tmk.mowo.cn/h5/" target="_blank">http://tmk.mowo.cn/h5/</a>

### 描述问题
滚动没有惯性。卡卡的，很不顺畅

**Comment by chenjiahan** [comment]
滚动滚性和组件没有关系，可以自行在滚动容器上添加以下样式

```css
-webkit-overflow-scrolling: touch;
```
