### ISSUE TITLE
[Feature Request] DropdownMenu 建议增加title插槽

### ISSUE THREAD

**Issue by linhaihero** [youzan/vant#4920]
### 这个功能解决了什么问题
title有时候需要显示一些不一样的东西，例如浮动小图标、多行内容等。既然内容都有插槽了，显然是考虑到不同的情况是需要的，让有可以修改的空间

### 描述您想要的解决方案
增加title的插槽

### 建议的API是什么样的
名为title的slot，有原title、options之类的作用域参数

**Comment by linhaihero** [comment]
完全被无视了。。算了，用popup魔改了

**Comment by chenjiahan** [comment]
别急呀，这个我们还得评估一下实现方式，后续会给答复

**Comment by linhaihero** [comment]
哦哦好的

**Comment by chenjiahan** [comment]
已在 2.2.13 版本支持

**Comment by KarlHuang0509** [comment]
add title slot  添加title插槽，但不支持动态渲染。刚好有一个需求，就是标题要显示动态选中了多少个筛选条件。 未来版本能否添加title 动态渲染。

**Comment by chenjiahan** [comment]
估计会在 3.0 版本支持，目前不太好实现

**Comment by KarlHuang0509** [comment]
好的.谢谢拉.
