### ISSUE TITLE
[Bug Report] render函数封装field，value报错

### ISSUE THREAD

**Issue by icer714** [youzan/vant#4921]
### 设备 / 浏览器
微信开发者工具

### Vant 版本
1.6.22

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-rb88i" target="_blank">https://codesandbox.io/embed/vant-issue-moban-rb88i</a>

### 描述问题
render封装出的field组件， 在控制台会报错，error in mounted hook："TypeError:  cannot read property 'value' of undefined"

**Comment by chenjiahan** [comment]
看了下你提供的链接，里面并没有报错呢

**Comment by icer714** [comment]
> 看了下你提供的链接，里面并没有报错呢

好吧...今天更新了下vant, 就不会报错了 之前是2.2.9 更新到了11
但是这边又有一个问题 这么封装后 placeholder不生效

**Comment by icer714** [comment]
> 看了下你提供的链接，里面并没有报错呢

可以了 vant升级后就好了.
