### ISSUE TITLE
[Feature Request] Uploader组件中加入控制右上角X图标的属性

### ISSUE THREAD

**Issue by jvhuaxia** [youzan/vant#4924]
### 这个功能解决了什么问题
可以在控制Uploader组件右上角X图标的显示 隐藏

### 描述您想要的解决方案
希望加入类似于一个 showDeleteAble 的属性 可以控制右上角的X的显示隐藏

### 建议的API是什么样的
希望加入类似于一个 showDeleteAble 的属性 可以控制右上角的X的显示隐藏

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 2.2.12 版本支持
