### ISSUE TITLE
[Feature Request]Stepper 步进器增加计量单位

### ISSUE THREAD

**Issue by asdwer098** [youzan/vant#4926]
### 这个功能解决了什么问题
使用该组件的很多场景都是附带计量单位的，当前组件没有提供api，而且开发者也不便于添加

### 描述您想要的解决方案
能否在api中增加单位字段，可选

### 建议的API是什么样的
能否在api中增加单位字段，可选

**Comment by chenjiahan** [comment]
具体是什么样的效果呢，能否提供截图看下

**Comment by asdwer098** [comment]
类似这种，红色选框部分 可根据api传入的值改变
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午3:56
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"ら逺ㄡ〆壞ぶ"<331274285@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request]Stepper 步进器增加计量单位 (#4926)




具体是什么样的效果呢，能否提供截图看下

**Comment by chenjiahan** [comment]
@asdwer098 图片没传上来

**Comment by asdwer098** [comment]
![image](https://user-images.githubusercontent.com/49505023/68189235-e5d44c00-ffe5-11e9-8647-951a787908df.png)
类似这种。

**Comment by chenjiahan** [comment]
评估了一下，目前组件是基于输入 number 设计的，不太好支持这种效果，因此暂时不会支持
