### ISSUE TITLE
[Bug Report] Total组件中，onClose回调函数中，执行路由相关方法，会导致死循环。

### ISSUE THREAD

**Issue by DengMingHao** [youzan/vant#4927]
### 设备 / 浏览器
浏览器

### Vant 版本
2.2.11

### Vue版本
2.5.17

### 描述问题
```
Toast.loading({
      duration: 1500,
      mask: false,
      message: '支付处理中…',
      onClose: () => {
        console.log('xxxxx')
        // 执行路由相关方法，会出现死循环。
        this.$router.push('/')
      }
})
```
[控制台输出](https://user-images.githubusercontent.com/11072796/59005302-7e0bb080-884f-11e9-8614-8882c4562a23.png
)

**Comment by chenjiahan** [comment]
试了下没复现，建议你看下是不是项目里的路由配置有问题，或者提供一下 codesandbox 复现链接

**Comment by ZHUDECHENG** [comment]
我这边也出现这个问题了
