### ISSUE TITLE
[Bug Report] IOS13在使用Dialog 弹出框时弹出框会从旁边弹出而不是直接从中间弹出

### ISSUE THREAD

**Issue by KevinyLin** [youzan/vant#4928]
### 设备 / 浏览器
ios 13.1.3

### Vant 版本
2.2.11

### Vue版本
2.6.10

### 重现链接
<a href="http://energy.eybond.com/#/accout" target="_blank">http://energy.eybond.com/#/accout</a>

### 描述问题
IOS13在使用Dialog 弹出框时弹出框会从旁边弹出而不是直接从中间弹出 进入链接后点击订单 购物车 或者收货地址弹出Dialog或者新建的一个测试demo里面就放了个按钮引入了Dialog   用ios13来测试时Dialog弹出框从右边往中间很僵硬的弹出来,而在别的版本和安卓则没有这个问题

**Comment by chenjiahan** [comment]
未复现此问题，我用的 iOS 13.2

你可以试下官方示例是否能复现

**Comment by GRJser** [comment]
我遇到了这个问题 ,同样是13.1的版本

**Comment by chenjiahan** [comment]
@GRJser 可以试下是不是只在 13.1 出现，如果是的话，就是系统 bug 了

**Comment by PPPenny** [comment]
同样遇到，13.2同款bug

**Comment by PPPenny** [comment]
> @GRJser 可以试下是不是只在 13.1 出现，如果是的话，就是系统 bug 了
13.2 经常出现这个问题，从右下角移动过到中间来

**Comment by PPPenny** [comment]
.van-dialog {
    transform: translate(-50%,-50%);}就解决了，亲测有效!!!!它原来是translate3d,改成2d就行了，但是动画。。。。

**Comment by GRJser** [comment]
> -
awsome,tks

**Comment by study-loading** [comment]
出现这种情况是translate3d(-50%,-50%, 0) 在动画期间并没有生效，动画结束后恢复默认样式时才应用transition，而且这种情况是偶发的，猜想可能是渲染的快慢导致的，所以我覆盖默了认样式，加了个delay基本就没有上述问题了。
`
.van-dialog {
  transition-delay: 0.2s;
}
`

**Comment by linyi435892508** [comment]
我这边是 如果在接口返回之后调用Dialog 或者先设置setTimeout 在延时后调用Dialog 都会出现 从旁边弹出来的效果
