### ISSUE TITLE
AddressEdit 地址编辑组件设置默认地区

### ISSUE THREAD

**Issue by ZYLmiumiumiu** [youzan/vant#4929]
AddressEdit 地址编辑的地区选择是否支持设置默认地区，或者说在进行地区选择的时候可以自定义事件，因为单独的Area组件是支持设置默认地区的。
![微信截图_20191105164957](https://user-images.githubusercontent.com/39985412/68193710-84fd4180-ffee-11e9-9666-296f68adc79f.png)

**Comment by chenjiahan** [comment]
可以使用 area-columns-placeholder 属性
