### ISSUE TITLE
在vue.config.js中重置了text-color变量，在页面中没有生效

### ISSUE THREAD

**Issue by zhengziyun** [youzan/vant#4930]
![image](https://user-images.githubusercontent.com/24427587/68195292-9005a100-fff1-11e9-867d-2b8498b54e1d.png)
![image](https://user-images.githubusercontent.com/24427587/68195346-aad81580-fff1-11e9-9a5a-92857e90c4d4.png)

**Comment by chenjiahan** [comment]
看起来你引用了两份样式，建议检查下是不是引入写法有误，应该只引用 less 文件

**Comment by zhengziyun** [comment]
好的，找到问题了，谢谢
