### ISSUE TITLE
定制主题1px边框设置颜色无效

### ISSUE THREAD

**Issue by liuzengwei** [youzan/vant#4932]
你好！在使用定制主题 修改 1px 边框颜色`@border-color`的时候 发现修改无效，修改按钮颜色什么的都好使

- vant@^2.2.10
- vue@^2.6.10
![R657$(4{J@9QH 7_}37QDB4](https://user-images.githubusercontent.com/16730829/68198565-428c3280-fff7-11e9-9ec4-a88dc2ff7efe.png)
![KONWF O$HUXNO}4TI)9RKGX](https://user-images.githubusercontent.com/16730829/68198572-45872300-fff7-11e9-8a15-24c237da80fe.png)

**Comment by chenjiahan** [comment]
下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 2.2.12 版本修复
