### ISSUE TITLE
[Bug Report] IndexBar 索引栏

### ISSUE THREAD

**Issue by html972051267** [youzan/vant#4934]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.11

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/index-bar" target="_blank">https://youzan.github.io/vant/#/zh-CN/index-bar</a>

### 描述问题
样式异常。非问题提供样式展示，多次实验。

**Comment by chenjiahan** [comment]
没看懂你的问题描述，麻烦提供下 codesandbox 复现链接

**Comment by html972051267** [comment]
您好，就是将提供的代码复制到html页面&nbsp; 格式乱了。div层级异常，和官方提供的样式展示完全不一样呀
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 上午10:16
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"蘑菇云.Six"<972051267@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] IndexBar 索引栏 (#4934)




没看懂你的问题描述，麻烦提供下 codesandbox 复现链接

**Comment by chenjiahan** [comment]
由于 html 语法的限制，在 html 页面中使用时 Vue 组件时，不能使用自闭合标签

因此 `<van-cell title="文本" />` 要写成 `<van-cell title="文本"></van-cell>`

**Comment by html972051267** [comment]
收到 /谢谢！~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 上午10:25
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"蘑菇云.Six"<972051267@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] IndexBar 索引栏 (#4934)




由于 html 语法的限制，在 html 页面中使用时 Vue 组件时，不能使用自闭合标签
 
因此 <van-cell title="文本" /&gt; 要写成 <van-cell title="文本"&gt;</van-cell&gt;
