### ISSUE TITLE
[Bug Report] tag标记中可关闭标签demo代码错误

### ISSUE THREAD

**Issue by NPCBOSS** [youzan/vant#4937]
### 设备 / 浏览器
window系统，chrome浏览器

### Vant 版本
2.2.11

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tag" target="_blank">https://youzan.github.io/vant/#/zh-CN/tag</a>

### 描述问题
在tag可关闭标签的demo中，v-if="showPrimary"，下面的data中并没有这个属性，会报错，而且demo中tag并没有closeable属性，查看源码可知，md文档与源码不一致，建议修改md文档，

**Comment by chenjiahan** [comment]
感谢反馈，后续会修正文档

**Comment by chenjiahan** [comment]
已修正
