### ISSUE TITLE
vant怎么做rem自适应,覆盖框架内的样式吗

### ISSUE THREAD

**Issue by rainbowzx** [youzan/vant#494]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
目前只能通过覆盖样式的方式解决噢，后续我们会考虑增加对 rem 的支持方案
