### ISSUE TITLE
[Bug Report] 建议在swipe轮播滑动增加冒泡事件

### ISSUE THREAD

**Issue by Xhyen** [youzan/vant#4940]
### 设备 / 浏览器
移动端

### Vant 版本
2.2.11

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/swipe" target="_blank">https://youzan.github.io/vant/#/zh-CN/swipe</a>

### 描述问题
问题类似https://github.com/youzan/vant/issues/3976#issue-473217385 
混合开发时，在ios端，滑动轮播组件的时候 会响应app端的滑动导致页面滑动到另外一侧，建议和swiper-cell一样增加stop-propagation属性

**Comment by chenjiahan** [comment]
现在默认就会阻止冒泡的
