### ISSUE TITLE
[Bug Report] list一直触发load事件

### ISSUE THREAD

**Issue by yimihuakai** [youzan/vant#4941]
### 设备 / 浏览器
cheome

### Vant 版本
2.2.11

### Vue版本
2.6.10

### 重现链接
<a href="http://jsrun.pro/haWKp" target="_blank">http://jsrun.pro/haWKp</a>

### 描述问题
cell 里面使用了 van-col布局，按照官方说法清除了浮动，但是还是不可以，一直会触发load加载事件。（codesandbox 我这边 打不开，所以提供了上述链接，）,麻烦看下！
下面的链接是有源码的。
http://jsrun.pro/haWKp/edit

**Comment by yimihuakai** [comment]
就算我不用col布局 ，直接用一个普通的div也是 不可以，不知道哪里写错了？ @chenjiahan

**Comment by chenjiahan** [comment]
看了下你的 jsrun 链接，并没有一直触发 load 事件呢

**Comment by yimihuakai** [comment]
> 看了下你的 jsrun 链接，并没有一直触发 load 事件呢

我代码里面设置的是 如果数组长度大于 30，就结束加载，fininshed设为true,但是无效，往下拉还是可以无限加载！
我打断点， 往下拉，一直会触发load事件！我的意思是这个 ，我可能没有表达清楚？
 // 加载状态结束
        that.loading = false;

        // 数据全部加载完成
        if (that.activityListData.length >= 30) {
          that.fininshed = true;
        }

**Comment by chenjiahan** [comment]
fininshed 拼写错了，兄弟
