### ISSUE TITLE
希望能在遮罩层组件自定义自己的样式

### ISSUE THREAD

**Issue by OrdinaryPath** [youzan/vant#4944]
1. 使用Popup组件选择中间内容弹出的时候它中间是有一个白色的背景，无法完成我的项目需求。

2. 当我选择使用Overlay遮罩层组件的时候，它却不能自定义蒙层上的内容。

3.希望能在 Overlay遮罩层能够自定义内容，因为往往有时候可能需要在遮罩层的中间实现各种弹框需求。

参考地址：https://didi.github.io/mand-mobile/#/zh-CN/docs/components/business/landscape

**Comment by chenjiahan** [comment]
1. Popup 的白色背景可以通过 css 改成其他颜色的

2. Overlay 有默认插槽，可以直接插入内容

**Comment by OrdinaryPath** [comment]
> 1. Popup的白色背景可以通过css改成其他颜色的
> 2. 覆盖有尺寸插槽，可以直接插入内容

感谢！是我的疏忽
