### ISSUE TITLE
[Feature Request] 1、可以增加通知组件上下翻滚数据2、可以增加通知组件左右滚动无缝衔接3、上拉加载更多

### ISSUE THREAD

**Issue by JIUCHENGSHICI** [youzan/vant#4948]
### 这个功能解决了什么问题
样式多样性

### 描述您想要的解决方案
1、可以增加通知组件上下翻滚数据2、可以增加通知组件左右滚动无缝衔接3、上拉加载更多

### 建议的API是什么样的
1、可以增加通知组件上下翻滚数据2、可以增加通知组件左右滚动无缝衔接3、上拉加载更多

**Comment by KyoShio** [comment]
还有不超出一行也能强制滚动

**Comment by chenjiahan** [comment]
暂时没有计划支持这几个特性

第一点参见 https://github.com/youzan/vant/issues/4463
第二点参见 https://github.com/youzan/vant/issues/4641
第三点参见 https://github.com/youzan/vant/issues/3687
