### ISSUE TITLE
针对图片直播照片比较多，点击大图展示(ImagePreview组件调用)创建

### ISSUE THREAD

**Issue by zhangyanFE** [youzan/vant#4950]
### 设备 / 浏览器
ios、android

### Vant 版本
2.2.11

### Vue版本
2.6.10

### 重现链接
<a href="http://openpre.yladm.com/h5/livephoto/#/" target="_blank">http://openpre.yladm.com/h5/livephoto/#/</a>

### 描述问题
针对照片比较多的时候点击大图浏览，一次性创建的元素比较多，导致比较卡顿，这个有解决办法吗

**Comment by zhangyanFE** [comment]
这个现在有解决方法吗？

**Comment by chenjiahan** [comment]
目前没有对大量图片的情况做处理，建议你在产品交互上做下控制，避免一次性预览过多的图片
