### ISSUE TITLE
为什么SwipeCell 滑动单元格，复制文档demo不显示，其他的主键没有问题

### ISSUE THREAD

**Issue by qichenhaha** [youzan/vant#4952]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
由于 html 语法的限制，在 html 页面中使用时 Vue 组件时，不能使用自闭合标签

因此 `<van-cell title="文本" />` 要写成 `<van-cell title="文本"></van-cell>`
