### ISSUE TITLE
[Bug Report] 时间选择器api中show-toolbar的默认错误

### ISSUE THREAD

**Issue by NPCBOSS** [youzan/vant#4954]
### 设备 / 浏览器
window系统，chrome浏览器

### Vant 版本
2.2.11

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/datetime-picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/datetime-picker</a>

### 描述问题
时间选择器api中show-toolbar的默认为false，但是检查源码，发现默认值是true，
![image](https://user-images.githubusercontent.com/38394370/68379810-8fa00e00-0189-11ea-8df7-c03ba8ec778d.png)

**Comment by chenjiahan** [comment]
感谢反馈，这里是文档标注有误，后续会更正

**Comment by chenjiahan** [comment]
已更正
