### ISSUE TITLE
[Feature Request] 建议SwipeCell 增加opened事件

### ISSUE THREAD

**Issue by linhaihero** [youzan/vant#4955]
### 这个功能解决了什么问题
滑动到底快速操作，例如删除、标记已读等，无需再点多一次

### 描述您想要的解决方案
增加opened事件

### 建议的API是什么样的
增加opened事件，回调参数包括 方向 等

**Comment by chenjiahan** [comment]
后续会支持

**Comment by chenjiahan** [comment]
已在 2.2.13 版本支持
