### ISSUE TITLE
[Bug Report] 日期组件，filter方法相关bug

### ISSUE THREAD

**Issue by Jinchengawu** [youzan/vant#4956]
### 设备 / 浏览器
谷歌（并非兼容性原因）

### Vant 版本
2.0.9

### Vue版本
2.6.6

### 重现链接
<a href="https://scrm.ocheng.me/h5/gasfun/mydistribution/" target="_blank">https://scrm.ocheng.me/h5/gasfun/mydistribution/</a>

### 描述问题
filter返回年月日，当日为空时，月份选项无法变更；

**Comment by chenjiahan** [comment]
能否提供一下 codesandbox 复现链接呢

**Comment by Jinchengawu** [comment]
> 能否提供一下codeandbox重复现链接呢

https://scrm.ocheng.me/h5/gasfun/
不好意思上边链接多了段路由；
这个没办法提供单独的demo直接上线上环境就可以复现；
需要微信浏览器环境，因为要微信授权，是基于微信公众号的；
打开后需要注册，因为是在订单流程出现的该问题，依赖用户数据；
在创建订单页面的 送货日期选择中 将 时间选为 11月29日，
那么在回瓶日期就会复现出 该bug

**Comment by chenjiahan** [comment]
DatetimePicker 本身不适合做这么复杂的逻辑，每个属性变更都可能引起一些重新计算的逻辑

建议使用 Picker 实现该功能
