### ISSUE TITLE
时间组件， filter方法相关

### ISSUE THREAD

**Issue by Jinchengawu** [youzan/vant#4957]
### 设备 / 浏览器
谷歌（并非兼容性原因）

### Vant 版本
2.0.9

### Vue版本
2.6.6

### 重现链接
<a href="https://scrm.ocheng.me/h5/gasfun/" target="_blank">https://scrm.ocheng.me/h5/gasfun/</a>

### 描述问题
filter返回年月日，当日为空时，月份选项无法变更；

**Comment by chenjiahan** [comment]
重复 issue https://github.com/youzan/vant/issues/4956
