### ISSUE TITLE
[Feature Request] toast怎么设置让loading弹窗和toast信息同时存在

### ISSUE THREAD

**Issue by liubin595338764** [youzan/vant#4958]
### 这个功能解决了什么问题
toast怎么设置让loading弹窗和toast信息同时存在，loading类型弹窗同一时间只能有一个，toast弱提示类型的弹窗同一时间只能有一个，但是这两个类型的弹窗可以同时存在

### 描述您想要的解决方案
.

### 建议的API是什么样的
Toast.loading({
    duration:0,
    allowMultiple: true
});

**Comment by chenjiahan** [comment]
为什么需要同时展示呢，两者会互相遮挡的

**Comment by liubin595338764** [comment]
因为我在页面切换的时候可以显示loading效果，但是在这期间接收到websocket的通知的时候，我们有个弱提示的弹窗，进行弱提示之后，loading效果也没有了，但这时页面路由可能还没切换完成。

**Comment by chenjiahan** [comment]
暂时不会支持这样的写法，你可以使用 allowMultiple 方法去实现
