### ISSUE TITLE
TypeError: Cannot read property 'vanPullRefresh' of undefined

### ISSUE THREAD

**Issue by xiaolinFang** [youzan/vant#4959]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

[Vue warn]: Error in render: "TypeError: Cannot read property 'vanPullRefresh' of undefined"
![image](https://user-images.githubusercontent.com/31360941/68444091-ca00be00-0210-11ea-9df5-d5e868154e24.png)

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by xiaolinFang** [comment]
![image](https://user-images.githubusercontent.com/31360941/68444147-f9afc600-0210-11ea-9159-e3cf6c0d9054.png)
组件有引入，昨天还好好的 今天就出现这种情况了 不知道为什么

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by byk04712** [comment]
同问

**Comment by byk04712** [comment]
找到问题所在了，设置了语言国际化导致。
