### ISSUE TITLE
[Bug Report] PasswordInput输入字母问题

### ISSUE THREAD

**Issue by gcddblue** [youzan/vant#4962]
### 设备 / 浏览器
微信浏览器

### Vant 版本
2.2.12

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/password-input" target="_blank">https://youzan.github.io/vant/#/zh-CN/password-input</a>

### 描述问题
能否提供数字字母都能输入的功能

**Comment by chenjiahan** [comment]
暂无计划支持喔
