### ISSUE TITLE
[Bug Report] 页面切换会影响List的会触发scroll事件

### ISSUE THREAD

**Issue by nightmaring** [youzan/vant#4964]
### 设备 / 浏览器
chrome模拟器

### Vant 版本
2.2.7

### Vue版本
2.5.20

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-mn9oj" target="_blank">https://codesandbox.io/s/vant-issue-moban-mn9oj</a>

### 描述问题
从A页面（有滚动条）跳转至B页面（有list组件），再从B返回A，最后从A再次进入B，会触发scroll事件，从而触发load

**Comment by nightmaring** [comment]
vant已更新到2.2.12，还是有这个问题，codesandbox上不知道为什么没问题，但是我本地一直有问题，同时我拉了一个新项目，测试这一部分代码，发现也是有问题的

**Comment by chenjiahan** [comment]
这种情况下触发 scroll 事件是正常的，会导致什么问题吗？

**Comment by nightmaring** [comment]
如果immediate-check设置false，然后自己在加载页面之后请求了数据，会导致请求两次

**Comment by chenjiahan** [comment]
@nightmaring 如果自己手动请求了数据，需要在请求时把 loading 设置成 true，这样就不会重复触发了

**Comment by anjina** [comment]
> @nightmaring 如果自己手动请求了数据，需要在请求时把 loading 设置成 true，这样就不会重复触发了

如果想要做缓存呢，
