### ISSUE TITLE
[Bug Report] TreeSelect一级分类不能切换

### ISSUE THREAD

**Issue by songlipeng2003** [youzan/vant#4966]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.12

### Vue版本
2.6.10

### 重现链接
暂无

### 描述问题
TreeSelect一级分类不能切换，尝试切换了Vue到2.5.11也不行。

看了一下源代码：
sidebar-item/index.js

```javascript
    onClick: function onClick() {
      if (this.disabled) {
        return;
      }

      this.$emit('click', this.index);
      this.parent.$emit('input', this.index);
      this.parent.$emit('change', this.index);
      route(this.$router, this);
    }
```

这里虽然提交更新了父级的sidebar的事件，但是父级sidebar的activeKey并没有更新

**Comment by chenjiahan** [comment]
请确认下你正确绑定了 v-model="activeKey"，input 事件会更新 v-model 绑定的值的
