### ISSUE TITLE
[Feature Request] Swipe 增加可以设置是否允许冒泡

### ISSUE THREAD

**Issue by linhaihero** [youzan/vant#4970]
### 这个功能解决了什么问题
有些重叠的侧边菜单，滑动显示、隐藏，需要控制事件冒泡。源码里看到锁死默认是阻止冒泡

### 描述您想要的解决方案
增加可以设置是否允许冒泡

### 建议的API是什么样的
增加可以设置是否允许冒泡

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 2.2.13 版本支持
