### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Cwmmm** [youzan/vant#4971]
设备 / 浏览器:
chrome流浪器

Vant 版本：
2.2.10

Vue版本：
2.5.2

描述问题：
在dropdown-menu设置了id  然后在dropdownitem监听open事件 触发open之后
document.querySelector('#menu').scrollIntoView(true);
将menu滚动到顶部，然后如果menu一开始不在顶部的话 触发了open之后item里面的option会停留在原来的位置，不会跟着menu到顶部

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
