### ISSUE TITLE
[Feature Request] 希望能直接操作原生DOM，如textarea组件

### ISSUE THREAD

**Issue by qianlanse** [youzan/vant#4977]
### 这个功能解决了什么问题
这个功能让我能操作Dom,因为我需要获取selectionStart或selectionEnd等属性

### 描述您想要的解决方案
能有相应的接口实现

### 建议的API是什么样的
跟原生一样就行

**Comment by chenjiahan** [comment]
可以直接通过 querySelector 获取 DOM 哈
