### ISSUE TITLE
[Feature Request] 自定义数字键盘的关闭按钮能否覆盖颜色？如果不能，可否添加一个属性使颜色可自由配置？

### ISSUE THREAD

**Issue by LonelyPH** [youzan/vant#4978]
### 这个功能解决了什么问题
增加自定义键盘的可配置性

### 描述您想要的解决方案
为数字键盘增加一个属性，用来配置关闭按钮的颜色，或者将关闭按钮设置为可用slot替换

### 建议的API是什么样的
为数字键盘增加一个属性，用来配置关闭按钮的颜色，或者将关闭按钮设置为可用slot替换

**Comment by chenjiahan** [comment]
这个 issue 已经回答过了，https://github.com/youzan/vant/issues/4965

目前不考虑添加属性来配置，不是很有必要

**Comment by LonelyPH** [comment]
> 这个问题已经回答过了，[＃4965](https://github.com/youzan/vant/issues/4965)
> 
> 目前不考虑添加属性来配置，不是很有必要

那请问怎么能覆盖掉呢?要用到这个数字键盘，但是颜色跟页面有冲突，网上找方法试了都没成功
