### ISSUE TITLE
Swipe能否控制在可视区才开启自动轮播

### ISSUE THREAD

**Issue by wuxin2014** [youzan/vant#4979]
### 这个功能解决了什么问题
轮播图埋点，发现就算不在可视区内，依然会自动轮播，虽然可以通过是否在可视区来决定是否调用埋点api

### 描述您想要的解决方案
希望能提供一个属性，控制开启或关闭自动轮播

### 建议的API是什么样的
这个就留给大佬们去想啰

**Comment by chenjiahan** [comment]
把 autoplay 设置为 0 就可以关闭自动轮播
