### ISSUE TITLE
DateTimePicker可以设置列数吗?

### ISSUE THREAD

**Issue by Fo0tMan** [youzan/vant#498]
比如我只需要年和月两列

**Comment by chenjiahan** [comment]
@Fo0tMan 目前不支持噢，如果只需要年和月的话，可以使用 Picker 组件去实现，DateTimePicker 也是基于 Picker 组件封装的

**Comment by Fo0tMan** [comment]
@chenjiahan 感谢回复，现在就是用Picker组件实现了一个

**Comment by chenjiahan** [comment]
客气~ 后续我们会考虑让 DateTimePicker 更通用
