### ISSUE TITLE
[Bug Report] [Bug Report] van-popup弹窗样式问题

### ISSUE THREAD

**Issue by asdwer098** [youzan/vant#4981]
### 设备 / 浏览器
ios 12.4.1

### Vant 版本
2.2.13-beta.0

### Vue版本
2.6.10

### 重现链接
<a href="http://kingtreetest.baowuhk.com.cn:8092/#/demo/test" target="_blank">http://kingtreetest.baowuhk.com.cn:8092/#/demo/test</a>

### 描述问题
父组件中引入2个子组件，其中一个子组件中有vant-popup弹窗，若另一个组件是悬浮固定在底部，popup弹窗在ios上和安卓上有较大差异

**Comment by asdwer098** [comment]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by asdwer098** [comment]
在https://codesandbox.io 模板中未复现，本地环境会有该问题。。

**Comment by chenjiahan** [comment]
看起来是层级的问题，建议你在 Popup 上添加 get-container="body" 试下

**Comment by asdwer098** [comment]
加过了ios端依旧问题如上图，安卓和浏览器都是正常的。

**Comment by asdwer098** [comment]
好了。。 不好意思 刚才加的是时间弹窗
