### ISSUE TITLE
[Feature Request] Indexbar 官网文档对新手不友好

### ISSUE THREAD

**Issue by DLLW** [youzan/vant#4983]
在官方文档中：只引入了IndexBar,IndexAnchor，两个组件，在实际使用中还需要引入Cell组件，对新手不友好
import { IndexBar, IndexAnchor } from 'vant';
<van-index-bar>
  <van-index-anchor index="A" />
  <van-cell title="文本" />
  <van-index-anchor index="B" />
  <van-cell title="文本" />
</van-index-bar>

**Comment by chenjiahan** [comment]
文档会有所取舍，某些浅显的部分，需要使用者有一定的判断
