### ISSUE TITLE
使用 van-datetime-picker 中使用min-date max-date 值被改变

### ISSUE THREAD

**Issue by Jermyo** [youzan/vant#4984]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

使用 van-datetime-picker 来实现 开始日期(start_date) & 结束日期(end_date)：
开始日期设置了 : max-date="end_date",
结束日期设置了 : min-date="start_date",
问题：当我选择开始时间的时候，结束时间被同步更改了
理想结果：更改开始时间，显示最大值为结束时间，更改完成开始时间后，结束时间选种值应该仍是之前选择的日期

**Comment by Jermyo** [comment]
![image](https://user-images.githubusercontent.com/23717512/68656928-b1283d80-056d-11ea-84a3-85f8d3c8b33b.png)
最新的版本：  v2.2.12

**Comment by Jermyo** [comment]
看了你们的changlog，指定到了2.2.0之后，问题解决，应该是后期版本更新出现的问题

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by Jermyo** [comment]
呵呵：
&nbsp; &nbsp;我问题已经写得很清楚了，改不改随你们（没有表达任何对程序员的不敬，是对于查看回复邮件的人）
&nbsp;&nbsp;


&nbsp; &nbsp;致敬程序员






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午5:34
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"缘来如此"<710273510@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] 使用 van-datetime-picker 中使用min-date max-date 值被改变 (#4984)




请按照模板创建 issue，感谢配合

**Comment by chenjiahan** [comment]
遵守规则是对他人的尊重，不会花费你多少时间的

**Comment by Jermyo** [comment]
谢谢回复，问题我已经提了，改或者不改，not my problem，反正我已经不用了，Thank you come again

&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 晚上8:43
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"缘来如此"<710273510@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] 使用 van-datetime-picker 中使用min-date max-date 值被改变 (#4984)




遵守规则是对他人的尊重，不会花费你多少时间的
