### ISSUE TITLE
[Feature Request] ImagePreview 组件 抛出内部Swipe组件的width和height，以兼容外部容器缩放适配的项目

### ISSUE THREAD

**Issue by iam2r** [youzan/vant#4985]
![Snipaste_2019-11-12_20-04-31](https://user-images.githubusercontent.com/25945398/68670884-f4dc7080-0588-11ea-8fe6-ac5aebdfdf4e.png)
### 这个功能解决了什么问题
Swipe组件 内部有算swipe宽度的逻辑，但不适用于 外层有scale缩放的项目。
好在提供了width和height 我们可以传带有scale参与计算后的width    

ImagePreview组件中内部使用的Swipe组件  却未使用Swipe的width和height接口 。 
固我们项目需要对ImagePreview组件进行重写。

### 描述您想要的解决方案
给ImagePreview 新增 swipeWidth和swipeHeight props
内部传给Swipe 的width和height

### 建议的API是什么样的
ImagePreview.props.swipeWidth = Number;
ImagePreview.props.swipeHeight = Number;

h（Swipe，{attrs:{width:this.swipeWidth,height:this.swipeHeight}}）

**Comment by chenjiahan** [comment]
你指的是通过 viewpoint 对整个页面进行缩放的情况吗？

**Comment by zrnokia5230** [comment]
> 你指的是通过 viewpoint 对整个页面进行缩放的情况吗？

![image](https://user-images.githubusercontent.com/25945398/68673449-b2b62d80-058e-11ea-834f-557d5e3e635c.png)

外层 容器 通过 scale 适配的 我们H5游戏项目 会 用这种适配方式

**Comment by chenjiahan** [comment]
暂时不计划加属性，这个 case 不是很通用。你能否通过在 ImagePreview 上添加 scale 来解决呢

**Comment by zrnokia5230** [comment]
> 暂时不计划加属性，这个 case 不是很通用。你能否通过在 ImagePreview 上添加 scale 来解决呢


![Snipaste_2019-11-15_22-46-04](https://user-images.githubusercontent.com/25945398/68951826-c7e2c480-07f9-11ea-8eee-d8d45df00bf1.png)

不太好 。
如图所示为van-image-preview 组件 dom结构
1.transform 运动的```.van-swipe__track```盒子 内部为从左到右依次排列。
固如果缩放 需要```transform-origin: 0 center;```  以左边为基准缩放。
2. ```.van-image-preview__index``` 显示 index 的盒子在页面居中
如果参与缩放  需要```transform-origin: center center;``` 以中间为基准缩放。
3. 上面的分析知道 
scale 作用在1和2 所说的容器的父级容器 ```.van-image-preview ```或者 ```.van-swipe```上 不太合理。
4. 固只能作用在 ```.van-swipe__track ``` 容器上 以左边为基准缩放。
而此盒子为 内部swiper 滚动的盒子 transform一直在变 ，不合理。
5.终上，.若```.van-swipe__track``` 套一层盒子   ```.van-swipe__track__outer```
在```.van-swipe__track__outer```盒子上以0 center为原点进行缩放 才能解决。

我们暂时是重写了van的ImagePreview组件
```
ImagePreview.props.swipeWidth = Number;
ImagePreview.props.swipeHeight = Number;

h(Swipe,{attrs:{width:this.swipeWidth,height:this.swipeHeight}}）
```
如果暂时不考虑扩展此属性
我们后面应该会考虑利用vant的Swipe组件封装一个 自用的imagePreview
来解决问题

**Comment by chenjiahan** [comment]
抱歉，暂时不会扩展此属性哈，issue 先 close 了
