### ISSUE TITLE
stick控件用在popup控件内不起作用，

### ISSUE THREAD

**Issue by jwq212** [youzan/vant#4987]
你好，这样使用的话
![image](https://user-images.githubusercontent.com/38306178/68728123-5809e980-0601-11ea-9bc6-4256f6bbe386.png)

会导致顶部的button到顶后吸不住的现象，具体现象我查看了，stick的scoll事件里scrollTop一直都是0；

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
