### ISSUE TITLE
[Bug Report] Vant tabs 渲染和值绑定异常

### ISSUE THREAD

**Issue by Rtfsc-8** [youzan/vant#4988]
### 设备 / 浏览器
Chromium Version 76.0.3809.100 (Official Build) 

### Vant 版本
2.2.11

### Vue版本
2.6.10

### 重现链接
<a href="https://jsfiddle.net/Rtfsc8/Lpy7egk8/17/" target="_blank">https://jsfiddle.net/Rtfsc8/Lpy7egk8/17/</a>

### 描述问题
1. 值绑定异常
2. 渲染位置异常

**Comment by chenjiahan** [comment]
### 渲染位置异常

由于 html 语法的限制，在 html 页面中使用时 Vue 组件时，不能使用自闭合标签
因此 `<van-tab />` 要写成 `<van-tab></van-tab>`

### 值绑定异常

原因是 name 设置成空字符串或数字 0 时会被组件忽略，下个版本会兼容下

**Comment by chenjiahan** [comment]
已在 2.2.13 版修复
