### ISSUE TITLE
[Feature Request] 下拉菜单指定节点get-container 无法生效

### ISSUE THREAD

**Issue by gebilaofan** [youzan/vant#4989]
### 这个功能解决了什么问题
在使用下拉菜单时，需要指定在某个节点下面显示。get-container给了一个选择器没有作用
  <van-dropdown-menu class="area" active-color='#ffa31a'>
          <van-dropdown-item v-model="value" :options="option"  @change="getNum()" get-container='.area'/>
      </van-dropdown-menu>  
吧挂载的节点写成 body时就起效了，这是为啥？是因为当执行到这里，页面还没有渲染完成导致找到不节点元素？

### 描述您想要的解决方案
get-container里面指定的挂载元素生效

### 建议的API是什么样的
暂时没有

**Comment by chenjiahan** [comment]
> 是因为当执行到这里，页面还没有渲染完成导致找到不节点元素？

大概率是的

**Comment by gebilaofan** [comment]
> > 是因为当执行到这里，页面还没有渲染完成导致找到不节点元素？
> 
> 大概率是的
我是挂载到body上  然后再改样式
我试过通过异步的方式获取dom  然后再绑定到get-container  但似乎接受到不到异步获取的dom

**Comment by chenjiahan** [comment]
get-container 可以传入一个函数的，你可以动态地调整传入的函数
