### ISSUE TITLE
数字键盘 input 事件 目前是先触发input 后更新value ，能否先更新值，后触发input，便于操作

### ISSUE THREAD

**Issue by CatEarCoder** [youzan/vant#4990]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4772
