### ISSUE TITLE
[Bug Report] van-grid-item组件设置dot不生效

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#4991]
### 设备 / 浏览器
谷歌

### Vant 版本
2.2.13-beta.0

### Vue版本
2.6.10

### 重现链接
<a href="http://weishangxian无法提供连接.com" target="_blank">http://weishangxian无法提供连接.com</a>

### 描述问题
使用按需引入import {  Grid, GridItem } from 'vant';的方式使用九宫格，代码中也是按着文档的方式使用，然后在van-grid-item组件上添加了dot属性，但是没有出现小红点

**Comment by lmfuture** [comment]
请教一下是什么问题呢

**Comment by chenjiahan** [comment]
升级版本试下
