### ISSUE TITLE
[Bug Report] Sku组件bug：当有3个page可呼起sku，某种情况下会出现某个page的遮罩丢失

### ISSUE THREAD

**Issue by microkof** [youzan/vant#4992]
### 设备 / 浏览器
任意手机或者PC设备

### Vant 版本
2.2.12

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/sku" target="_blank">https://youzan.github.io/vant/#/zh-CN/sku</a>

### 描述问题
重现步骤：设有三个页面，都可以呼起sku。

让每个页面都呼起一次sku，即：呼起、关掉、路由到下一个页。

三个页面都做到呼起关闭之后，路由从第三页回到第一个页（或第二页），则第一个页（或第二页）的sku呼起之后，遮罩会丢失。

如果无法重现，可以考虑给三个页面设keep-alive

**Comment by chenjiahan** [comment]
能否提供个 codesandbox 复现链接看下

**Comment by microkof** [comment]
> 能否提供个 codesandbox 复现链接看下

可以。请看 http://hebeieditor.sinaapp.com/bug-sku/#/

源码请下载 http://hebeieditor.sinaapp.com/bug-sku/bug-sku.rar

复现必须满足：由vuex统一管理每个page里面的sku的显示隐藏。

复现操作：打开网址之后点击click呼出弹层，关掉，去下一个页面，呼出，关掉，再去下一个页面，呼出关掉，再随便点一个页面，呼出，弹层就会丢失。

**Comment by microkof** [comment]
> 能否提供个 codesandbox 复现链接看下

另外，必须是有2到3个页面设置了keep-alive

**Comment by chenjiahan** [comment]
这个问题的原因是你把一个 showSku 状态同时绑定在了多个 Sku 组件上，所以显示时每个 Sku 都触发了显示逻辑，导致蒙层没定位到正确的位置。

建议要么使用单个 Sku 组件（放到 router-view 外面），要么每个 Sku 设置单独的 showSku 状态
