### ISSUE TITLE
DropdownMenu多个item默认只会显示一个

### ISSUE THREAD

**Issue by DevaloperHH** [youzan/vant#4993]
版本：2.2
问题：多个item默认加载的时候只显示第一个item，点了一下之后显示正常了 但是第二个item的下拉出不来
重现地址：https://codepen.io/devaloperhh/pen/abbajaQ

**Comment by chenjiahan** [comment]
由于 html 语法的限制，在 html 页面中使用时 Vue 组件时，不能使用自闭合标签

因此 `<van-dropdown-item />` 要写成 `<van-dropdown-item></van-dropdown-item>`
