### ISSUE TITLE
[Feature Request] 建议文档中公开组件内部国际化接口，以便自身业务中需求国际化时也方便使用

### ISSUE THREAD

**Issue by zrnokia5230** [youzan/vant#4995]
![Snipaste_2019-11-13_15-03-11](https://user-images.githubusercontent.com/25945398/68742519-55bc8500-062b-11ea-8613-109952e9157a.png)
### 这个功能解决了什么问题
文档中只介绍了
import { Locale } from 'vant';
Locale.use 以切换vant组件库中的国际化的修改
而存在这种需求的项目基本上自身业务上也需要国际化
不研究vant内部国际化代码  很可能直接使用vue-i18n 代替 。
但没必要  直接使用vant内部的方案代码更精简
目前我们项目是利用内部的vant/lib/utils/create/i18n 中 createI18N 
创建命名空间手动挂载到Vue原型

### 描述您想要的解决方案
挂载$t到 vue 组件 实例中 业务中可以通过 this.$t(key) 执行  
提供一个方便的接口 方便把业务中的国际化文件与vant库中的融合
可统一由Locale.use方法 控制语言切换。

### 建议的API是什么样的
挂载$t到 vue 组件 实例中 业务中可以通过 this.$t(key) 执行  
提供一个方便的接口 方便把业务中的国际化文件与vant库中的融合
可统一由Locale.use方法 控制语言切换。

**Comment by chenjiahan** [comment]
目前内部的国际化方案是针对 Vant 设计的，比较精简，所以不计划对外提供接口。一旦对外的话，会有很多的需求，而国际化方案不属于组件库本身的职责。建议使用 vue-i18n，功能比较全面
