### ISSUE TITLE
[Feature Request] SwitchCell组件希望添加一个title的slot

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant#4996]
### 这个功能解决了什么问题
用户能够有更高的组件可定制化

### 描述您想要的解决方案
添加一个title插槽

### 建议的API是什么样的
添加一个title插槽

**Comment by chenjiahan** [comment]
SwipeCell 好像没有 title 喔？

**Comment by Gitsifu** [comment]
![image](https://user-images.githubusercontent.com/23445650/68745926-7fc57580-0632-11ea-903a-d98a80beacb0.png)
这个还是用Cell 和 Switch 组件代替吧，3.0之后都没有这个组件了

**Comment by chenjiahan** [comment]
喔 我看错了 SwitchCell 是不推荐使用的，用 Cell 和 Switch 就可以咯

**Comment by Gitsifu** [comment]
@chenjiahan 好的，谢谢！
