### ISSUE TITLE
[Bug Report] Area 省市区选择联动反应迟钝

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#4998]
### 设备 / 浏览器
谷歌

### Vant 版本
2.2.13-beta.0

### Vue版本
2.6.10

### 重现链接
<a href="http://weishangxian无法提供连接.com" target="_blank">http://weishangxian无法提供连接.com</a>

### 描述问题
Area 省市区选择联动反应迟钝，切换省份，市区切换的有些迟钝，请教一下有解决办法么

**Comment by chenjiahan** [comment]
目前有 1 秒的惯性滚动时间，下个版本会支持配置

**Comment by chenjiahan** [comment]
已在 2.2.13 版本支持

**Comment by lmfuture** [comment]
非常感谢，辛苦了
