### ISSUE TITLE
[Bug Report] 两个页面都引用List组件时，路由切换时某些情况下不触发onload事件

### ISSUE THREAD

**Issue by HelloDBA** [youzan/vant#4999]
### 设备 / 浏览器
android/chrome

### Vant 版本
2.2.12

### Vue版本
2.6.10

### 重现链接
<a href="http://fescoerp.vaiwan.com/" target="_blank">http://fescoerp.vaiwan.com/</a>

### 描述问题
重现：
第一步：两个页面A、B，都使用了van-list组件
第二步：先打开A页面van-list加载数据超过一屏
第三步：进入B页面，B页面van-list的load事件不触发
原因：
进入B页面时，list组件获取list.$refs.placeholder.getBoundingClientRect()的位置还是页面A的位置

**Comment by bolechen** [comment]
是否用了   transition
可参考 #4294

**Comment by HelloDBA** [comment]
> @kid1412621
> 
> 更严谨的说话应该是在页面切换动画完成之后在触发 `this.$refs.list.check();`
> 
> 但我发下在路由组件内部好像没办法监听切换动画是否完成，所以只能加个定时器了。如下：
> 
> ```js
> mounted() {
>   this.listCheckTimer = setTimeout(() => {
>   this.$refs.list.check();
> 
>   // 因为切换动画时长是 300ms，所以这个定时器的时间一定要大于 300ms
>   }, 350); 
> },
> 
> beforeDestroy() {
>   // 页面销毁前，记得清空计时器
>   clearTimeout(this.listCheckTimer)
> }
> ```

用此方法已暂时解决

**Comment by HelloDBA** [comment]
> 是否用了 transition
> 可参考 #4294

谢谢
