### ISSUE TITLE
有计划都生成vue版本吗

### ISSUE THREAD

**Issue by browneyedape** [youzan/vant#50]
### 请认真写 PR 的标题，会用于生成 change log。

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by cookfront** [comment]
生成vue版本是啥意思？

**Comment by browneyedape** [comment]
单文件组件

**Comment by cookfront** [comment]
```js
import { Button } from 'vant/lib/button'
```

就可以引入单个文件，为啥要生成单文件组件？
