### ISSUE TITLE
PC端iframe标签嵌套vant移动端时，选择器滚动失效

### ISSUE THREAD

**Issue by HuangqfGH** [youzan/vant#5000]
vant 开发的项目：
使用移动设备时，时间选择器，选择器滚动正常。
但是，PC端项目的iframe标签 引用vant项目后，由于是在PC浏览器 展示，导致选择器的滚动失效，望给个解决的办法！小弟感激不尽！！

**Comment by zehuichan** [comment]
估计是样式问题，可以参考vant主站，现成的套用iframe

**Comment by HuangqfGH** [comment]
> 估计是样式问题，可以参考vant主站，现成的套用iframe

感觉不像样式问题，因为鼠标按住拉动，也是不生效。
还是希望大佬们，能贴上代码，小弟感激不尽！

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

**Comment by HuangqfGH** [comment]
> 参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

感谢大佬。小弟感激不尽！赶紧不尽！！！
