### ISSUE TITLE
[Feature Request] ActionSheet 组件增加关闭按钮  prop 或 slot

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#5001]
### 这个功能解决了什么问题
产品不给用圆形的关闭按钮【捂脸.jpg】，希望就是普通的 x 按钮，如果可以提供个按钮 prop 或 slot 就好了，我们就无需自己各种弹窗重复写布局了~

### 描述您想要的解决方案
增加关闭按钮 prop 或 slot

### 建议的API是什么样的
增加关闭按钮 prop 或 slot

**Comment by chenjiahan** [comment]
下个版本会加个 prop

**Comment by chenjiahan** [comment]
已在 2.2.13 版本支持

**Comment by 1014156094** [comment]
> 已在 2.2.13 版本支持

文档没更新到 close-icon 噢

**Comment by chenjiahan** [comment]
文档漏了，后面会补上
