### ISSUE TITLE
[Bug Report] 使用文档推荐的rem方式影响组件样式

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#5003]
### 设备 / 浏览器
谷歌

### Vant 版本
2.2.13-beta.0

### Vue版本
2.6.10

### 重现链接
<a href="http://weishangxian无法提供连接.com" target="_blank">http://weishangxian无法提供连接.com</a>

### 描述问题
设计图的尺寸是750的，设置了postcss-pxtorem的rootValue为75，页面也是的正常，使用rem之后vant组件也转化为rem的问题怎么解决呢，vant组件转化为rem后尺寸肯定会相应的缩小了一半，请问这个该怎么设置呢？

**Comment by zrnokia5230** [comment]
![Snipaste_2019-11-14_11-01-20](https://user-images.githubusercontent.com/25945398/68823242-23b02f00-06ce-11ea-9c80-1107cd483b5c.png)
