### ISSUE TITLE
[Bug Report] ImagePreview 缩放失败

### ISSUE THREAD

**Issue by cn-zx** [youzan/vant#5008]
### 设备 / 浏览器
iOS 10.3.3

### Vant 版本
2.2.0

### Vue版本
2.5.2

### 重现链接
<a href="http://imgqn.没得.com/452569801.jpg" target="_blank">http://imgqn.没得.com/452569801.jpg</a>

### 描述问题
在iOS 10.3.3 手机上, vant2.1.8之后的版本 ImagePreview无法缩放 只能放大

**Comment by chenjiahan** [comment]
如果是 Vue 2.6 以上版本，参见 https://github.com/youzan/vant/issues/3015

**Comment by cn-zx** [comment]
> 如果是Vue 2.6以上版本，参见[＃3015](https://github.com/youzan/vant/issues/3015)

vue 版本是 2.5.2,  vant 2.1.8版本 ImagePreview能显示, 手指缩放正常, vant 2.1.8之后版本ImagePreview能显示, 手指缩放没有反应

**Comment by chenjiahan** [comment]
可以把 Vue 升级到 2.5.22 试下

**Comment by cn-zx** [comment]
> 可以把 Vue 升级到 2.5.22 试下

在vue升级到 2.5.22 后,  在vant2.2.13中ImagePreview缩放滑动正常.
