### ISSUE TITLE
源码field组件中45行 <icon :name="icon" />为什么不是<van-icon :name="icon" />

### ISSUE THREAD

**Issue by maite168** [youzan/vant#501]
源码field组件中45行 `<icon` :name="icon" `/>为什么不是<van-icon` :name="icon" />，却可以正常渲染出来，谢谢。

**Comment by chenjiahan** [comment]
@maite168 标签名是可以自由定义的，在 vant 内部处于简化代码的考虑，直接使用了 icon 标签，但在实际项目中还是推荐使用 van-icon

**Comment by maite168** [comment]
嗯，但是注册组件的时候使用的名字是van-icon，为什么可以简化，是有别的配置方式吗？

**Comment by chenjiahan** [comment]
可以参考这个文件，注册的时候就是 icon 
https://github.com/youzan/vant/blob/dev/packages/utils/create.js

**Comment by maite168** [comment]
谢谢，看懂了，看过这个工具函数，细节没注意到。非常感谢。

**Comment by chenjiahan** [comment]
客气~
