### ISSUE TITLE
[Bug Report] SwipeCell 滑动单元格 滑动触发点击事件

### ISSUE THREAD

**Issue by jiahui336** [youzan/vant#5011]
### 设备 / 浏览器
公众号 

### Vant 版本
2.2.13-beta.0

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/swipe-cell#onclose-can-shu" target="_blank">https://youzan.github.io/vant/#/zh-CN/swipe-cell#onclose-can-shu</a>

### 描述问题
设置了阻止冒泡没起作用

**Comment by chenjiahan** [comment]
使用了 fastclick 吗

**Comment by jiahui336** [comment]
@click

**Comment by chenjiahan** [comment]
麻烦提供一下复现问题的 codesandbox 链接
