### ISSUE TITLE
[Feature Request]search能增加field-class吗？让外部动态传参数改变样式

### ISSUE THREAD

**Issue by sc544177047** [youzan/vant#5018]
[Feature Request] search能增加field-class吗？让外部动态传参数改变样式

**Comment by zrnokia5230** [comment]
任何一个vue组件 可以直接接受:class  : id
等 应该直接在 van-search 添加:class 就能动态 改 van-search  根元素类名
根据父类重写字类就行了了

**Comment by chenjiahan** [comment]
楼上正解
