### ISSUE TITLE
[Bug Report] van-pull-refresh 与 微信公众号的下拉回弹效果冲突

### ISSUE THREAD

**Issue by Mrshihe** [youzan/vant#5022]
### 设备 / 浏览器
ios 10.3.3  6s 微信内置浏览器

### Vant 版本
2.1.8

### Vue版本
2.5.20

### 重现链接
<a href="http://jdshop666.jdetyy.com" target="_blank">http://jdshop666.jdetyy.com</a>

### 描述问题
用van-pull-refresh组件做下拉刷新功能，但是在ios机型上 ，微信浏览器下拉会出现 由XXX提供字样，导致下拉刷新功能不能正常使用，请问我该如何解决这一问题

**Comment by chenjiahan** [comment]
只有页面滚动条处于顶部的时候，才会触发下拉刷新，其他时候下拉会走默认的滚动逻辑

**Comment by chenjiahan** [comment]
后续会研究下是否有优化方案

**Comment by chenjiahan** [comment]
尝试了一下，目前没有找到方案在滚动过程中禁用掉浏览器的下拉回弹效果，issue 先 close 了

**Comment by chenjiahan** [comment]
尝试了一下，目前没有找到方案在滚动过程中禁用掉浏览器的下拉回弹效果，issue 先 close 了
