### ISSUE TITLE
[Bug Report] 表单输入框组件van-field 的v-model不支持过滤器

### ISSUE THREAD

**Issue by 18069776927** [youzan/vant#5023]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/m5v3f" target="_blank">https://codesandbox.io/s/m5v3f</a>

### 描述问题
重现链接还没有，我再本地测试的

问题：
vant2.x中表单输入框组件，标签van-field 的v-model属性，用于绑定值，进过测试，不支持过滤器......如底部代码：过滤器方法showName无效

说明：
因为van-field设计就是用于表单输入，我一个页面几十个字段，里面很多自多都只存了 code值，比如0,1,2 之类的，但显示上我肯定要转成code对应的名称，现在很尴尬啊....

代码例子：
【 1是 0否  注：showName方法，将1显示成 是，0显示成 否】
【van-field  label="是否计划内"  v-model="isPlan | showName" 】

**Comment by chenjiahan** [comment]
v-model 本身就不支持 filter 的，建议你用 computed 去实现
