### ISSUE TITLE
[Bug Report] DropdownMenu 的 item 设get-container后设不了自定义class、点击item被关闭

### ISSUE THREAD

**Issue by linhaihero** [youzan/vant#5025]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-cg7jz?fontsize=14" target="_blank">https://codesandbox.io/s/vant-issue-moban-cg7jz?fontsize=14</a>

### 描述问题
Item 上设的class是挂在一个过渡div上，而没有设在 van-dropdown-item 上，所以设置get-container后，脱离了这个div，等于无效

**Comment by linhaihero** [comment]
同时，设了 get-container 之后 ，close-on-click-outside 会把 Item 当 outside 了。。。点item任意地方不调用toggle()都会关掉

**Comment by linhaihero** [comment]
> 同时，设了 get-container 之后 ，close-on-click-outside 会把 Item 当 outside 了。。。点item任意地方不调用toggle()都会关掉

临时解决办法 给item内的容器手动加一个空事件 @click.stop=""

**Comment by chenjiahan** [comment]
后续会修复下

**Comment by chenjiahan** [comment]
已在 2.2.14 版本修复点击后关闭的问题，自定义 class 暂无计划支持
