### ISSUE TITLE
[Bug Report] SwipeCell 使用鼠标无法拉出右侧按钮

### ISSUE THREAD

**Issue by varjay** [youzan/vant#5026]
### 设备 / 浏览器
macOS 10.15 / chrome

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/swipe-cell" target="_blank">https://youzan.github.io/vant/#/zh-CN/swipe-cell</a>

### 描述问题
SwipeCell 使用鼠标无法拉出右侧按钮，我们公司的项目需要pc和移动兼容。请求优化！

**Comment by chenjiahan** [comment]
后续会看下怎么兼容 PC

**Comment by chenjiahan** [comment]
已在 2.2.14 版本修复

**Comment by xiaoer3301** [comment]
感谢！
