### ISSUE TITLE
[Bug Report] cell的value为连续数字或连续字母不换行

### ISSUE THREAD

**Issue by 89360944** [youzan/vant#5027]
### 设备 / 浏览器
iphone6 - 375 * 667

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="http://test-spj.feddon.com/test" target="_blank">http://test-spj.feddon.com/test</a>

### 描述问题
cell的value为连续数字或连续字母不换行

**Comment by chenjiahan** [comment]
后续会优化下

**Comment by chenjiahan** [comment]
已在 2.2.14 版本修复
