### ISSUE TITLE
swpie组件使用抖动的问题

### ISSUE THREAD

**Issue by AK47-dadada** [youzan/vant#5028]
机型：小米Mix、谷歌最新版本浏览器
移动端浏览器：UC最新版本

描述：在引入swipe组件之后，tag组件会在swipe每次滚动的时候抖动约1px的距离，之前在Issues里面查找了一下，确实存在这个情况，维护大神描述是可能是安卓旧版本问题引起的，但是新版本的安卓也存在这个问题，希望引起注意

![967172eb02ee1c55fee948dc1bb21e9b](https://user-images.githubusercontent.com/30396595/68996722-d81da100-08d8-11ea-8ee3-bdca6620510a.gif)

 国产视频转换软件实在无良，tx视频，微信用户不让上传视频，所以提供素材确实有点恶心，就这个，凑活着看吧，最好自己搞个demo演示一下，so sorry，大半夜了，肝不动了
维护大佬辛苦一下

**Comment by chenjiahan** [comment]
准确的说是 hairline 边框的渲染问题，目前没有发现什么好方法去避免这个问题，你可以帮忙研究下~
