### ISSUE TITLE
[Feature Request] Uploader 文件上传今后会有可以给照片打水印的功能么

### ISSUE THREAD

**Issue by xiaoxu7777** [youzan/vant#5032]
### 这个功能解决了什么问题
解决的可以给图片自定义加水印的功能

### 描述您想要的解决方案
上传照片完成时，开发可以自定义水印放置在照片上

### 建议的API是什么样的
可以覆盖一层透明的遮罩层，开发可以把水印画在遮罩层上。位置和文字大小开发者可以自定义。水印也可能是多行。

**Comment by chenjiahan** [comment]
暂无计划支持，这个不属于组件库的职责，建议找一些第三方开源库去实现
