### ISSUE TITLE
[Bug Report] Field输入框开启字数统计，在ios下换行出现输入BUG

### ISSUE THREAD

**Issue by leaper1** [youzan/vant#5033]
### 设备 / 浏览器
ios系统

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-r1rmm?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-r1rmm?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
Field输入框，启用字数统计，假设限制20个字。
在ios浏览器打开，输入17个字符后，换行，然后就只能再输入一个字符了就限制输入了。
可以多试几个换行，总的字数有问题，只在ios下出现，安卓没问题

**Comment by chenjiahan** [comment]
原生的 maxlength 对换行符的统计有问题，后续会修复下

**Comment by chenjiahan** [comment]
已在 2.2.14 版本修复
