### ISSUE TITLE
[Bug Report] dialog点击确定会自动关闭弹窗

### ISSUE THREAD

**Issue by grace618** [youzan/vant#5038]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
点击dialog 确认按钮，会自动关闭，只能通过异步关闭解决吗，为什么这样设计哇，不是有v-model是否显示弹窗吗

**Comment by chenjiahan** [comment]
默认情况下点击是会关闭的，可以通过 before-close 来改变这个行为
