### ISSUE TITLE
更最新版本后， ImagePreview使用报错

### ISSUE THREAD

**Issue by Obacm** [youzan/vant#504]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
请提供报错信息，谢谢

**Comment by Obacm** [comment]
[Vue warn]: $attrs is readonly.

found in

---> <VanSwipe>
       <Root>
[Vue warn]: Error in beforeCreate hook: "TypeError: Cannot read property 'swipes' of null"

(found in <Root>)
TypeError: Cannot read property 'swipes' of null
[Vue warn]: Error in render: "TypeError: Cannot read property 'width' of null"
TypeError: Cannot read property 'width' of null
