### ISSUE TITLE
[Bug Report] tab组件 v-model设置不生效

### ISSUE THREAD

**Issue by JadeLiuYC** [youzan/vant#5042]
### 设备 / 浏览器
移动端

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-ezbqg" target="_blank">https://codesandbox.io/s/vant-issue-moban-ezbqg</a>

### 描述问题
使用tab组件时，在created中获取上个页面传进来的值并赋给tab组件v-model绑定的active不会生效      created(){ this.active = this.$route.params.active }  
但是直接 created(){ this.active = 2 } 就会生效

**Comment by chenjiahan** [comment]
这个和组件没啥关系，你只要确保 data 里定义了 active，且正确赋值，就不会有问题
