### ISSUE TITLE
[Feature Request] 最新版本的vant,对vue版本有要求吗，vue可以使用3.x的吗

### ISSUE THREAD

**Issue by jyxnn** [youzan/vant#5044]
最新版本的vant,对vue版本有要求吗，vue可以使用3.x的吗

**Comment by chenjiahan** [comment]
vue 最新版是 2.6.10，你说的应该是 vue-cli 的版本。

目前我们要求 Vue 版本 >= 2.5.20，对 vue-cli 版本无要求
