### ISSUE TITLE
[Bug Report] Tabbar 标签栏 加上safe-area-inset-bottom后，布局出现问题，内容溢出（iPhoneX 需真机查看）

### ISSUE THREAD

**Issue by SakuraDoramon** [youzan/vant#5045]
### 设备 / 浏览器
iPhone 13.1.3

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://jsfiddle.net/13814066642/gw5mbry4/7/" target="_blank">https://jsfiddle.net/13814066642/gw5mbry4/7/</a>

### 描述问题
Tabbar 标签栏 加上safe-area-inset-bottom后，布局出现问题，内容溢出

**Comment by chenjiahan** [comment]
试了下没问题呢

![image](https://user-images.githubusercontent.com/7237365/69224379-65057a80-0bb7-11ea-928a-f94fa962aaf8.png)

**Comment by SakuraDoramon** [comment]
IPhone X （v13.1.3），微信（v7.0.8）扫码打开页面，meta里面设置了viewport-fit=cover。
如下图，底部标签栏溢出。
不知道你是否可以复现







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午5:02
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"清水镇外玟小六"<1160689507@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] Tabbar 标签栏 加上safe-area-inset-bottom后，布局出现问题，内容溢出（iPhoneX 需真机查看） (#5045)




试了下没问题呢

**Comment by chenjiahan** [comment]
你的图片没传上来

**Comment by SakuraDoramon** [comment]
可以看到了吗？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午5:19
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"清水镇外玟小六"<1160689507@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] Tabbar 标签栏 加上safe-area-inset-bottom后，布局出现问题，内容溢出（iPhoneX 需真机查看） (#5045)




你的图片没传上来

**Comment by chenjiahan** [comment]
没

**Comment by SakuraDoramon** [comment]
的确溢出了，如下图，iPhone真机截图
![ss](https://user-images.githubusercontent.com/20762953/69393661-c0994a80-0d14-11ea-8bb0-e92feaa7d6f4.png)

**Comment by chenjiahan** [comment]
明白了，应该是 box-sizing 的问题，下个版本会修复下

**Comment by SakuraDoramon** [comment]
> 明白了，应该是 box-sizing 的问题，下个版本会修复下

谢谢大大！

**Comment by chenjiahan** [comment]
已在 2.2.14 版本修复

**Comment by lilin87788** [comment]
大佬，为什么我的vant4.x还会出这个问题，能不能指教一下
