### ISSUE TITLE
popup 与 sticky一起使用

### ISSUE THREAD

**Issue by grace-yue** [youzan/vant#5050]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io" target="_blank">https://youzan.github.io</a>

### 描述问题
如下popup，在另一个popup中调起，设置position="right"时，sticky失效，van-index-anchor右侧位置固定也失效；设置position="bottom"时正常
`<van-popup v-model="showTeachers" position="right">
        <van-sticky>
          <van-nav-bar
            title="请选择"
            left-arrow
            @click-left="closeTeacherList"
          /></van-nav-bar>
        </van-sticky>
        <div class="teachers">
          <van-index-bar :index-list="indexList">
            <div v-for="(data, key) in teacherList" :key="key" class="contact-box">
              <van-index-anchor :index="data.title"></van-index-anchor>
              <van-cell v-for="(val, index) in data.items" @click="selectTeacher(val)" :key="index" >
                <div class="van-ellipsis">{{val.name}}</div>
              </van-cell>
            </div>
          </van-index-bar>
        </div>
      </van-popup>`

**Comment by chenjiahan** [comment]
Chrome 浏览器里，transform 元素内部不支持使用 fixed 布局，所以不支持 Popup 和 IndexBar sticky 模式一起使用喔
