### ISSUE TITLE
组件可添加重载方法吗

### ISSUE THREAD

**Issue by date-convert** [youzan/vant#5051]
例如：外层元素宽度变化时，重载组件使其适应外层Dom宽度 如 轮播 组件、标签页组件

**Comment by chenjiahan** [comment]
可以的，后续会在这两个组件里添加对应的重绘方法

**Comment by chenjiahan** [comment]
已在 2.2.14 版本支持

**Comment by date-convert** [comment]
> 已在 2.2.14 版本支持


> 已在 2.2.14 版本支持
已解决  , 感谢！！
