### ISSUE TITLE
[Feature Request] 项目用的是1.x版本的  换2.x版本的库会有问题吗

### ISSUE THREAD

**Issue by SmalldayEvil** [youzan/vant#5053]
### 这个功能解决了什么问题
项目用的是1.x版本的  换2.x版本的库会有问题吗

### 描述您想要的解决方案
项目用的是1.x版本的  换2.x版本的库会有问题吗

### 建议的API是什么样的
项目用的是1.x版本的  换2.x版本的库会有问题吗

**Comment by chenjiahan** [comment]
请参考 2.0 更新日志的不兼容更新部分进行升级

https://youzan.github.io/vant/#/zh-CN/changelog#bu-jian-rong-geng-xin
