### ISSUE TITLE
nuxt 如何配置按需加载呢？

### ISSUE THREAD

**Issue by levai** [youzan/vant#5054]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by gp0320** [comment]
我最近也在用nuxt, 按需加载已搞定，请看我的文章
https://juejin.im/post/5e012778518825127f085da8
