### ISSUE TITLE
Tab组件切换的时候,我想内容不重复的调用接口

### ISSUE THREAD

**Issue by OrdinaryPath** [youzan/vant#5055]
现在Tab组件里面的内容都是调用同一个接口(只有参数不同),但是我希望第一次切换的时候调用接口,但是后面的几次切换我不再调用接口直接赋值,
所以我想知道有没有监听切换是否是第一次

**Comment by chenjiahan** [comment]
组件内没有这样的参数，你可以自己维护一个变量去区分是否为第一次
