### ISSUE TITLE
Swipe

### ISSUE THREAD

**Issue by Wlisfes** [youzan/vant#5056]
### 设备 / 浏览器
ios11 Chrome

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vue-template-lcne2" target="_blank">https://codesandbox.io/s/vue-template-lcne2</a>

### 描述问题
Swipe vertical设置为true，loop设置为true，autoplay设置为3000   自动滚动到最后一个的时候会出现bug，loop感觉怪怪的！

**Comment by chenjiahan** [comment]
width/height 属性不能与循环播放同时使用喔，文档里只标注了 width，后续会把 height 的说明也补上
