### ISSUE TITLE
van-field使用

### ISSUE THREAD

**Issue by cengjiahao** [youzan/vant#5058]
<van-field  type="number"  v-model.trim="item.money" min="0" maxlength="25"  @input="onClickInputKeyBoard(item.money)"/>
当 type="number"  只能输入数字 和.(点) 但是发现如果先输入点的话会没有值 这个要怎么解决

**Comment by chenjiahan** [comment]
原生 number 类型的输入框就是这样的，只输入点号读取不到任何值
