### ISSUE TITLE
[Feature Request] Notice Bar 能否支援强制滚动

### ISSUE THREAD

**Issue by W-Lynn** [youzan/vant#5059]
### 这个功能解决了什么问题
字不够一行时定在那里很怪

### 描述您想要的解决方案
目前是超过一行才会开始滚动. 希望可以强制滚动, 即使只有5~6个字

### 建议的API是什么样的
接受一个props强制滚动

**Comment by chenjiahan** [comment]
暂无计划支持呢，有兴趣的话可以提个 PR
