### ISSUE TITLE
需要一个类似于scroll-view的组件

### ISSUE THREAD

**Issue by Jiang-YuXuan** [youzan/vant#5062]
在使用中发现已有组件nav-bar和tabbar，但发现并没有一个承载内容的盒子，类似scroll-view的东西！
有如下需求：
当首页相当于app时，有顶部nav和tab，内容部分滚动是否到底和内容滚动不受顶部和底部影响
我的实现
tabbar页面
<template>
  <section>
    <van-nav-bar :title="title" :left-arrow="false" :fixed="true" />
    <transition>
      <keep-alive>
        <home v-if="active==0"></home>
        <classify v-else-if="active==1"></classify>
        <shop-car v-else-if="active==2"></shop-car>
        <find v-else-if="active==3"></find>
        <mine v-else-if="active==4"></mine>
      </keep-alive>
    </transition>
    <van-tabbar v-model="active">
      <van-tabbar-item icon="home-o">首页</van-tabbar-item>
      <van-tabbar-item icon="apps-o">分类</van-tabbar-item>
      <van-tabbar-item icon="shopping-cart-o">购物车</van-tabbar-item>
      <van-tabbar-item icon="point-gift-o">发现</van-tabbar-item>
      <van-tabbar-item icon="user-o">我的</van-tabbar-item>
    </van-tabbar>
  </section>
</template>
<script>
import Home from "@/views/Home.vue";
import Classify from "@/views/Classify.vue";
import shopCar from "@/views/shopCar.vue";
import Find from "@/views/Find.vue";
import Mine from "@/views/Mine.vue";
export default {
  components: {
    home: Home,
    classify: Classify,
    "shop-car": shopCar,
    find: Find,
    mine: Mine
  },
  data() {
    return {
      active: 0
    };
  },
  computed: {
    title: function() {
      let title = "首页";
      switch (this.active) {
        case 0:
          title = "首页";
          break;
        case 1:
          title = "分类";
          break;
        case 2:
          title = "购物车";
          break;
        case 3:
          title = "发现";
          break;
        case 4:
          title = "我的";
          break;
      }
      return title;
    }
  },
  methods: {},
  mounted() {}
};
</script>
<style>
.van-nav-bar--fixed {
  background: linear-gradient(to right, #ff9700, #ed1c24);
}
.van-nav-bar__title {
  color: #fff;
}
.van-tabbar-item--active {
  color: #f65a10;
}
</style>
其中一个page页面
`<template>
  <scroll-view top="46px" bottom="50px" @getScrollTop="getScrollTop" @reachBottom="onReachBottom">
    <div id="page">
      <van-pull-refresh v-model="isLoading" @refresh="onRefresh">
        <div v-for="(item,index) in 100" :key="index">this is home</div>
      </van-pull-refresh>
    </div>
  </scroll-view>
</template>
<script>
import ScrollView from "@/components/ScrollView.vue";
export default {
  components: {
    "scroll-view": ScrollView
  },
  data() {
    return {
      isLoading: false
    };
  },
  methods: {
    onRefresh() {
      setTimeout(() => {
        this.$toast("刷新成功");
        this.isLoading = false;
        this.count++;
      }, 500);
    },
    getScrollTop(e){
      window.console.log(e)
    },
    //触底事件
    onReachBottom(){
      window.console.log('触底');
    }
  },
  mounted() {
    this.$toast("重载");
  }
};
</script>
<style scoped>
#page {
  width: 100%;
  min-height: 100%;
}
</style>`
其中主要的scroll-view的实现
`<template>
  <div id="contanier" @scroll="getScroll"  :style="`top:${top};bottom:${bottom};background-color:${backColor}`" >
    <slot></slot>
  </div>
</template>
<script>
export default {
  props: {
    top: {
      type: String,
      default: "0px"
    },
    bottom: {
      type: String,
      default: "0px"
    },
    backColor: {
      type: String,
      default: "#fff"
    }
  },
  data() {
    return {
      scrollTop: 0
    };
  },
  methods: {
    //滚动事件
    getScroll(e) {
      let wScrollY = e.target.scrollTop; // 当前滚动条位置
      this.scrollTop = wScrollY;
      let wInnerH = e.target.clientHeight; // 设备窗口的高度（不会变）
      let bScrollH = e.target.scrollHeight; // 元素总高度
      if (wScrollY + wInnerH >= bScrollH) {
        this.$emit("reachBottom");
      }
    }
  },
  activated() {
    this.$el.scrollTop = this.scrollTop;
    this.$emit('getScrollTop',{scrollTop:this.scrollTop});
  },
  updated() {},
  mounted() {}
};
</script>
<style scoped>
#contanier {
  width: 100%;
  position: fixed;
  z-index: 1;
  left: 0px;
  overflow-y: scroll;
  display: flex;
  display: -webkit-flex;
  flex-wrap: wrap;
}
</style>`

**Comment by yangshuyi** [comment]
后来你用什么方式实现的呢
