### ISSUE TITLE
[Bug Report] upload上传图片自定义图标bug

### ISSUE THREAD

**Issue by liRemons** [youzan/vant#5064]
### 设备 / 浏览器
oppo r17

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://app.alizhizhu.com" target="_blank">https://app.alizhizhu.com</a>

### 描述问题
oppo r17机型使用自定义图标时,出现上传图片前端页面不显示图片的bug,其他手机正常,(备注:重现上传的链接已替换成默认的上传图片,暂看不到此问题)

**Comment by chenjiahan** [comment]
自定义图标指的是？ 能提供下复现的 codesandbox 链接么

**Comment by liRemons** [comment]
应用已使用默认上传,暂时无法看到




详细说明:图片所指的上传图片的自定义样式,上传成功后应当会展示图片,但在部分机型中上传过后还是显示上传的按钮


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 晚上7:00
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"Remons"<remons@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] upload上传图片自定义图标bug (#5064)




自定义图标指的是？ 能提供下复现的 codesandbox 链接么

**Comment by chenjiahan** [comment]
这些机型使用 input type="file" 能正常工作么，是否有多开微信之类的操作

**Comment by liRemons** [comment]
换成vant默认的上传没问题,只是换成自定义图标的有问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2019年11月22日(星期五) 中午11:16
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "Remons"<remons@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] [Bug Report] upload上传图片自定义图标bug (#5064)




这些机型使用 input type="file" 能正常工作么，是否有多开微信之类的操作
 
&mdash;

**Comment by chenjiahan** [comment]
能否提供 codesandbox 复现链接看下

**Comment by liRemons** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 中午11:23
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"Remons"<remons@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] upload上传图片自定义图标bug (#5064)




能否提供 codesandbox 复现链接看下

**Comment by chenjiahan** [comment]
链接呢。。
