### ISSUE TITLE
我用vue-ui 更新vant  无限更新 已经2小时了 还在转。。。

### ISSUE THREAD

**Issue by wbjeln** [youzan/vant#5066]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
建议看下你的网络是否有问题，或者使用 taobao 源试下
