### ISSUE TITLE
[Bug Report] dropdownmenu组件当里面元素较多时，在移动端无法滑动

### ISSUE THREAD

**Issue by whucsfzf** [youzan/vant#5067]
### 设备 / 浏览器
android、ios

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://cd6pb.csb.app/" target="_blank">https://cd6pb.csb.app/</a>

### 描述问题
dropdownmenu组件当里面元素较多时，在移动端无法滑动。
另建议van-dropdown-item添加click事件

**Comment by chenjiahan** [comment]
试了下没问题呢，可以滑动，你是什么机型无法滑动

click 事件暂时无计划添加，可以使用 click.native

**Comment by whucsfzf** [comment]
好的  我再看下，后面发现单独用没问题，但是在原生里面用就有问题，可能是机型问题

**Comment by whucsfzf** [comment]
多谢解答
