### ISSUE TITLE
Vant文档建议

### ISSUE THREAD

**Issue by jinger7281** [youzan/vant#5068]
**这个功能解决了什么问题**

官方文档对于哪个版本新增的功能没有描述清楚，用户在使用旧的lib时按官方文档描述可能无法实现新版本中的东西，可能会以bug提交或者以为vant出现问题不再使用
**描述您想要的解决方案**

官方文档应该像php文档中标明哪个功能是在哪个版本中实现的

例如：overlay中在2.2.5 版本支持默认插槽，应该在默认插槽案例中标明2.2.5版本及以上可用
**建议的API是什么样的**

Overlay:

嵌入内容（2.2.5及以上版本可用）

通过默认插槽可以在遮罩层上嵌入任意内容

**Comment by chenjiahan** [comment]
目前 props 是有说明版本的，events 和 slots 暂时无版本说明，后续会考虑加上

**Comment by chenjiahan** [comment]
Overlay 组件已添加版本说明，其他组件后续会陆续补充
