### ISSUE TITLE
Popup中使用Dialog

### ISSUE THREAD

**Issue by vivian217** [youzan/vant#5074]
Popup中使用Dialog的话，如果不使用getContainer的话，Dialog的遮罩层不超过Popup的区域，如果使用getContainer,关闭Dialog以及Popup之后，切换页面报错：
`[Vue warn]: Error in beforeDestroy hook: "HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent."`
请问这个问题应该怎么解决？

**Comment by chenjiahan** [comment]
由于框架限制，使用了 get-container 的组件不能为根节点，如果出现这个提示，可以在该组件外层包裹一层 div

```html
<div>
  <van-popup get-container="body" />
</div>
```

**Comment by fellowT** [comment]
> 由于框架限制，使用了 get-container 的组件不能为根节点，如果出现这个提示，可以在该组件外层包裹一层 div
> 
> ```
> <div>
>   <van-popup get-container="body" />
> </div>
> ```

谢谢大佬，百度了好久

**Comment by aetherwu** [comment]
> ```
> get-container="body"
> ```

请问一下， 这个 get-container 到底是应该写 .class 还是可以写 #page 这样的Id，还是需要选 tag 名字（body像是一个html标签）？文档里啥也没写，太难受了。

如果是小程序里可以一样用吗？我反复尝试了各种写法，目前都没有效果。
