### ISSUE TITLE
[Bug Report] pull-refresh判断是否触顶所使用的scrollTop永远为0

### ISSUE THREAD

**Issue by Jim-Rae** [youzan/vant#5085]
### 设备 / 浏览器
MI 9 (MIUI 11.0.2, Android 10) / 微信自带浏览器，小米浏览器

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="http://jimrae.top/m" target="_blank">http://jimrae.top/m</a>

#### 复现操作
1. 用手机浏览器打开重现链接
2. 进入页面后随便注册一个账号登录到首页（在首页和我的订单页里都使用了pull-refresh   list的形式展示列表）
3. 往上滑动列表后，再往下滑动列表时无法滑动回顶部，且有bounce效果

#### 具体原因
根据问题表现出来的现象初步猜测是pull-refresh触顶判断错误的原因，本人阅读pull-refresh源码后，发现pull-refresh源码里有一个[getCeiling方法](https://github.com/youzan/vant/blob/c168cd3c12626ba560cd117627ae5de37dd814b8/src/pull-refresh/index.js#L117)用于判断是否触顶，其中使用了工具类里的一个[getScrollTop方法](https://github.com/youzan/vant/blob/c168cd3c12626ba560cd117627ae5de37dd814b8/src/utils/dom/scroll.ts#L32)，本人在[getScrollTop方法](https://github.com/youzan/vant/blob/c168cd3c12626ba560cd117627ae5de37dd814b8/src/utils/dom/scroll.ts#L32)加入了打印代码，分别打印出`element.scrollTop`和`element.pageYOffset`的值，发现在chrome的模拟移动端里打印出来的`element.scrollTop`是有值且正确的，但通过spy-debugger真机调试打印出来的`element.scrollTop`一直为0，也就导致pull-refresh一直判断为触顶状态，往下滑动列表时表现成下拉刷新。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4908#issuecomment-551362449

改下 body 的样式可以避免这个问题

**Comment by Jim-Rae** [comment]
@chenjiahan body的样式已经设了height: 100%; overflow-y: auto;  还是不行，overflow-y: scroll; 也不行

**Comment by chenjiahan** [comment]
把 height: 100% 和 overflow-x 去掉试下，如果想保证最小高度，推荐使用 min-height: 100vh

**Comment by Jim-Rae** [comment]
@chenjiahan 可以了，原来html, body设置了overflow-x: hidden;后，浏览器会默认把overflow-y设成auto，导致[getScrollEventTarget](https://github.com/youzan/vant/blob/c168cd3c12626ba560cd117627ae5de37dd814b8/src/utils/dom/scroll.ts#L7)获取到的scrollEl是body，然后document.body的onscroll事件浏览器不支持，才会导致scrollTop为0，如果html, body不设置overflow-x: hidden;的话，那么浏览器会默认把overflow-x和overflow-y设置成visible，这样子getScrollEventTarget获取到的scrollEl是window，而window的onscroll事件浏览器是支持的，所以能获取到正确的scrollTop。
最后，非常感谢您的解答！

**Comment by chenjiahan** [comment]
嗯嗯，是这样的，解决了就好
