### ISSUE TITLE
[Bug Report] field 组件clear 事件无法在pc浏览器上无法监听

### ISSUE THREAD

**Issue by coolkiller007** [youzan/vant#5088]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.14

### Vue版本
2.6.10

### 描述问题
field 组件clear 事件无法在pc浏览器上无法监听

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

**Comment by Zenquan** [comment]
按照以上给的地址找不到这个问题的解决，后面发现换了新的url了
参见：https://youzan.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei
