### ISSUE TITLE
[Bug Report] Swipe组件设置纵向滚动时高度丢失（第一次正常，刷新后高度为0）

### ISSUE THREAD

**Issue by SmalldayEvil** [youzan/vant#5090]
### 设备 / 浏览器
所有

### Vant 版本
1.5.6

### Vue版本
2.5.20

### 重现链接
<a href="https://fj.shangaofangjin.com/#/productDetail/wuXi" target="_blank">https://fj.shangaofangjin.com/#/productDetail/wuXi</a>

### 描述问题
Swipe组件设置纵向滚动时高度丢失（第一次正常，刷新后高度为0）

**Comment by chenjiahan** [comment]
麻烦看下官方示例是否能复现，或者升级 vant 版本试下
