### ISSUE TITLE
[Feature Request] Uploader 文件上传 》van-image__error 》希望这个icon可以自己定义

### ISSUE THREAD

**Issue by liuruiqi1993** [youzan/vant#5092]
### 这个功能解决了什么问题
我用Uploader去传用户头像，如果头像错误，我就想把它写成van-icon-user-o  
现在都是写死的van-icon-warning-o  
用dom改会有闪烁

### 描述您想要的解决方案
新增一个Props

### 建议的API是什么样的
error-icon

**Comment by chenjiahan** [comment]
什么情况下会出现 van-image__error 呢，理论上本地图片上传都会拿到正确的图片的
