### ISSUE TITLE
[Bug Report] CountDown组件不开启毫秒时,但实际会计算微秒级,就会让人觉得时间比实际计时少一秒

### ISSUE THREAD

**Issue by jimzbom** [youzan/vant#5094]
### 设备 / 浏览器
所有

### Vant 版本
2.2.10

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/count-down" target="_blank">https://youzan.github.io/vant/#/zh-CN/count-down</a>

### 描述问题
CountDown组件不开启毫秒时,但实际会计算微秒级,就会让人觉得时间比实际计时少一秒,比如到了0秒,但实际是0.xxx秒, 0.999=>0.000都有1秒时间,当显示0秒时,实际还要等1秒才结束

**Comment by chenjiahan** [comment]
是这样的，少于一秒的话会显示为 0 秒，

假如把 0.x 秒显示为 1 秒的话，那 1.x 秒就会显示为 2 秒，感觉这样不太合理。
