### ISSUE TITLE
Search搜索组件添加自动聚焦意见

### ISSUE THREAD

**Issue by hllive** [youzan/vant#5095]
在很多引用到搜索组件的时候会让搜索框自动聚焦，现目前组件中并没有自动聚焦的属性。
我采用的是
`this.$refs.searchid.children[0].children[0].children[1].children[0].children[0].focus();`
这种方式自动聚焦
或采用自定义指令
```
// 定义自动聚焦的指令
focus: {
  inserted: function(el) {
    setTimeout(() => {
      el.children[0].children[0].children[1].children[0].children[0].focus();
    }, 500);
  }
}
```
希望有赞团队能添加自动聚焦的属性【autofocus】
非常感谢

**Comment by chenjiahan** [comment]
autofocus 属性目前是支持的喔，这个是原生属性，但是在 iOS 上是无法生效的
