### ISSUE TITLE
数字键盘 blur事件触发时机有问题

### ISSUE THREAD

**Issue by NoahSun** [youzan/vant#5096]
https://github.com/youzan/vant/blob/dfd45e9299bf0376aad911e2dc340bbffdac450e/src/number-keyboard/index.js#L14

我觉得应该修改为这样，不然键盘初始设置为`show=false`的时候点任何位置都会触发一次blur事件
```javascript
if (this.hideOnClickOutside && this.show)
```

**Comment by chenjiahan** [comment]
是应该这样的，能否提个 PR 改下
