### ISSUE TITLE
[Bug Report] NumberKeyboard v-model 应支持数字

### ISSUE THREAD

**Issue by Cheng007** [youzan/vant#5097]
### 设备 / 浏览器
chrome 76.0.3809.100

### Vant 版本
2.2.14

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-lckod" target="_blank">https://codesandbox.io/s/vant-issue-moban-lckod</a>

### 描述问题
数字键盘应该支持输入纯数字，所以 Props 中的 `v-model` 应为 `string | number`，不然在设置纯数字如 `v-model: 100` 时会有 `[Vue warn]: Invalid prop`

**Comment by chenjiahan** [comment]
暂无计划支持，纯数字的话，0 开头的输入就无法支持了。建议自行转换一下类型
