### ISSUE TITLE
[Bug Report] v-lazy图片加载的时候会加载2次

### ISSUE THREAD

**Issue by vincent-cong** [youzan/vant#5098]
### 设备 / 浏览器
浏览器

### Vant 版本
2.2.11

### Vue版本
2.6.10

### 重现链接
<a href="https://www.zhbbroker.cn/zhb-ins-home/#/home?insurance_id=100" target="_blank">https://www.zhbbroker.cn/zhb-ins-home/#/home?insurance_id=100</a>

### 描述问题
network 下面查看 懒加载的图片都加载了2次，你们官网上面的示例也是一样的 图片加载2次
麻烦帮忙看看 灰常感谢

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3372

**Comment by vincent-cong** [comment]
突然发现 在 disable cash 模式下面 加载2次 。。正常情况下不会

**Comment by chenjiahan** [comment]
嗯呐
