### ISSUE TITLE
[Feature Request] 能否提供table的功能

### ISSUE THREAD

**Issue by LuoShouwei** [youzan/vant#5099]
### 这个功能解决了什么问题
数据显示是日常使用非常高的功能. 但是在vant的事例中并没有table的例子. 导致终端用户花费大量时间去设计, 调整table的样式

### 描述您想要的解决方案
在vant的事例中,给出例子如何快速建立一个table.

### 建议的API是什么样的
在vant的事例中,给出例子如何快速建立一个table.

**Comment by chenjiahan** [comment]
暂时计划支持喔，移动端 Table 不是很常见的
