### ISSUE TITLE
Cell 单元格貌似没有select 实例

### ISSUE THREAD

**Issue by muiccc** [youzan/vant#510]
Cell 单元格貌似没有select 实例

**Comment by chenjiahan** [comment]
@muiccc Select 实例指的是？

**Comment by muiccc** [comment]
@chenjiahan 选项呀 比如 选择 退款原因  然后点了 选择 退款 或者是等等

**Comment by chenjiahan** [comment]
@muiccc 你的需求应该是搭配 Popup 或者 Picker 实现比较好。不适合集成在 Cell 组件内
