### ISSUE TITLE
Card自定义价格下面slot bottom没有价格，就无法显示？

### ISSUE THREAD

**Issue by Gokeyoung** [youzan/vant#5101]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---
**card** 组件：

card组件在没有价格属性的时候bottom slot就是无效的，不知道是故意这样设计的，还是多了一下判断...?

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
这里应该可以优化下，没传 Price 的时候也可以有 bottom slot。

麻烦按照 issue 模板重新创建 issue，我们会优化此处的逻辑
