### ISSUE TITLE
[Feature Request] 【Picker 】Picker 选择器添加监听滑动开始

### ISSUE THREAD

**Issue by TomWangKing** [youzan/vant#5102]
### 这个功能解决了什么问题
多列联动中第二列是动态的需要时间处理数据，onChange的触发时间比较晚，在弱网环境下第二列数据还未更改的情况下，用户会点确定，导致选择错误数据，监听滑动开始添加状态，onChange请求网络数据并显示的时候解除状态，才可点击确定

### 描述您想要的解决方案
监听滑动开始

### 建议的API是什么样的
监听滑动开始，可修改对应的picker选择器列数据，添加自己想要的动作自定义的动作

**Comment by chenjiahan** [comment]
在请求数据的过程中加个 Loading 或者锁定状态不行嘛

**Comment by TomWangKing** [comment]
因为列表长，加Loading，onChange容易触发请求，会频繁出现Loading打断用户体验

**Comment by chenjiahan** [comment]
为什么会频繁出现 loading 嘞，不是每次滑动后触发 change，再触发请求吗

**Comment by TomWangKing** [comment]
因为列表很长，客户会看一下停一下确定是自己选择的内容，因为一行数据不多，会出现频繁切换，多个loading影响用户体验

**Comment by chenjiahan** [comment]
暂时没有计划支持这个事件，抱歉
