### ISSUE TITLE
[Bug Report] noticeBar通告栏在ios系统只循环出现了一周

### ISSUE THREAD

**Issue by yuyuhy** [youzan/vant#5104]
### 设备 / 浏览器
苹果X手机

### Vant 版本
2.2.14

### Vue版本
2.6.10

### 重现链接
<a href="http://wx.suxiangshijia.com/#/activeIndex？activeId=1" target="_blank">http://wx.suxiangshijia.com/#/activeIndex？activeId=1</a>

### 描述问题
进入页面公告栏在ios系统上只循环出现了一周之后就不再循环出现，在android系统上正常

**Comment by chenjiahan** [comment]
使用官方文档的示例能复现这个问题吗，iOS 系统版本是多少

**Comment by yuyuhy** [comment]
可以复现，ios版本13.2.3






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 中午11:54
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"撕夜"<2391749818@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] noticeBar通告栏在ios系统只循环出现了一周 (#5104)




使用官方文档的示例能复现这个问题吗，iOS 系统版本是多少

**Comment by chenjiahan** [comment]
我也是 13.2.3，试了下没问题呢

**Comment by yuyuhy** [comment]
不知道您那边怎样测试的，我是在ios系统下微信公众号里面，平板，手机都有这个问题只要是ios系统的
，刚才我又测试了一遍，发现此问题仍然存在，在不同的页面也是存在这个问题

**Comment by chenjiahan** [comment]
能否提供个官方示例的复现视频看下

**Comment by yuyuhy** [comment]
这个可能不是很方便，不过vue版本是2.9.6，npm版本6.9.0

**Comment by chenjiahan** [comment]
vue 没有 2.9.6 版本，你说的是 vue-cli 吧

**Comment by yuyuhy** [comment]
是的是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月29日(星期五) 上午9:49
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"撕夜"<2391749818@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] noticeBar通告栏在ios系统只循环出现了一周 (#5104)




vue 没有 2.9.6 版本，你说的是 vue-cli 吧

**Comment by chenjiahan** [comment]
提供的信息太少，且复现不了问题，建议你自行调试寻找下问题

**Comment by 313224646** [comment]
我也出现了一样的情况，微信h5，ios版本13.3.1，型号iphone8，vant2.5.1，vue2.6.10。
代码如下
`
<van-notice-bar 
          color="#ffffff" 
          background="rgba(26, 26, 26, .24)" 
          text="温馨提示：只能提前预约当天的班次，发车前1个小时不能退票。" 
          left-icon="volume-o" 
        />
`
