### ISSUE TITLE
[Feature Request] area.json数据问题

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#5107]
### 这个功能解决了什么问题
大佬，area.json数据市从哪个网站找的，和我公司先用的省市区库内容不一致，想统一一下数据。可以发一下网址吗

### 描述您想要的解决方案
暂无

### 建议的API是什么样的
暂无

**Comment by chenjiahan** [comment]
没有网址喔，是我们自己维护的

**Comment by anihCevol** [comment]
额，是这样的，我现在用的省市区库，部分省市区的数据和vant给的area.json的数据不一致，所以想问一下，贵公司整理area.json数据是根据哪个平台数据来的~

**Comment by chenjiahan** [comment]
国内的部分是按国家标准的省市区码来的

**Comment by anihCevol** [comment]
这个准吗~~
2019年中华人民共和国行政区划代码
http://www.mca.gov.cn/article/sj/xzqh/2019/。
http://www.mca.gov.cn/article/sj/xzqh/2019/2019/201911250933.html。
![QQ截图20191126120452](https://user-images.githubusercontent.com/42430384/69598778-7500dc80-1045-11ea-88e4-da98bc200e97.png)
![QQ截图20191126120611](https://user-images.githubusercontent.com/42430384/69598781-792cfa00-1045-11ea-8379-5f0027453873.png)

**Comment by chenjiahan** [comment]
高新区应该是比较特殊的，不属于行政区划，业务中不需要的话可以去掉
