### ISSUE TITLE
[Bug Report]下拉刷新往下拉范围距离太长的话，没有回弹调用refresh方法

### ISSUE THREAD

**Issue by yaowangmx** [youzan/vant#5109]
设备 / 浏览器
ios端 app：herobuy

Vant 版本
2.2.1

Vue版本
2.6.10

重现链接
ios端app：herobuy首页

描述问题
PullRefresh 下拉刷新组件生成的app中，往下拉动一段很长的距离有时候不会回弹，比如手指滑动范围到屏幕外，能不能下拉一定的距离就触发refresh方法呢？
![微信图片_20191126141206](https://user-images.githubusercontent.com/17875101/69603870-cfeeff80-1056-11ea-9dee-a6781a002f9c.jpg)

**Comment by chenjiahan** [comment]
正常情况下，滑动到屏幕外会触发 touchcancel 事件，然后触发回弹。

建议你看下是不是 webview 有问题

**Comment by Jam1zhu** [comment]
@yaowangmx 遇到了相同的问题，离开webview，就不触发刷新了。请问你解决了吗？
