### ISSUE TITLE
[Bug Report] @vant/touch-emulator 在火狐和IE下的部分问题

### ISSUE THREAD

**Issue by iam2r** [youzan/vant#5115]
### 设备 / 浏览器
PC 火狐 IE

### Vant 版本
2.2.14

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html#/zh-CN/slider" target="_blank">https://youzan.github.io/vant/mobile.html#/zh-CN/slider</a>

### 描述问题
1. fakeTouchSupport 函数  将 window.ontouchstart（'ontouchmove', 'ontouchcancel', 'ontouchend'） 从undefined 改为null
使得 'ontouchstart' in window;   等判断函数  恒为 true   促使别的类库 如pixi.js  游戏引擎 吧环境 当成 移动端  使用了一些移动端才有的变量
导致火狐 和 IE报错。 
猜想 hammer.js 中的源代码  是为了  保证 在PC端时 内部dom的 ['ontouchstart', 'ontouchmove', 'ontouchcancel', 'ontouchend'] 事件 在 PC端  强行注册成自定义事件     方便 后面的mouse事件 触发时  用   去 构造 事件对象 dispatchEvent  手动触发   ['ontouchstart', 'ontouchmove', 'ontouchcancel', 'ontouchend']  实现 PC   用mouse事件 代理  touch（自定义事件）  来兼容PC 端
但vant 内部的touch相关事件的注册是在vue render函数中 注册的   不存在 'ontouchstart' in window; 判断 来 是否 添加事件监听 touch事件是一定会被监听到的
故此处 强行将  window.ontouchstart（'ontouchmove', 'ontouchcancel', 'ontouchend'） 从undefined 改为null  是不需要的。 
实测 也可行

2.onMouse 函数 返回的闭包函数  中 用 ev.which!== 1  来判断 鼠标是否按下的状态   
火狐和IE 是 这个值是有问题的   永远为1    所以 火狐和ie上  鼠标抬起后  所有vant touch相关事件的组件 仍然 能够触发move事件
这里可以改为 ev.buttons !== 1 来 判断  可以兼容 chrom ie 和 火狐     

![image](https://user-images.githubusercontent.com/25945398/69623247-78b05580-107d-11ea-919d-3d78a487ee79.png)

**Comment by chenjiahan** [comment]
能否提个 PR 帮忙修复一下~

**Comment by iam2r** [comment]
> 能否提个 PR 帮忙修复一下~

OK。   ev.buttons  变量也不靠谱    存在浏览器兼容性问题
所以判断鼠标是否按下的状态 还是 用变量来控制状态靠谱一些
![image](https://user-images.githubusercontent.com/25945398/69626238-3558e580-1083-11ea-8bbe-ed63295ee337.png)

**Comment by chenjiahan** [comment]
已发布 @vant/touch-emulator@1.2.0 版本
