### ISSUE TITLE
[Feature Request] 文件上传时点击图片预览和ImagePreview图片预览问题

### ISSUE THREAD

**Issue by zhangliyuan-chance** [youzan/vant#5121]
### 这个功能解决了什么问题
图片预览打开或关闭时会卡顿，甚至卡顿很久（移动端）

### 描述您想要的解决方案
文件上传时点击图片预览和ImagePreview图片预览打开关闭时更加流畅

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
能提供下复现的 codesandbox 链接么

**Comment by zhangliyuan-chance** [comment]
http://luobozhang.gitee.io/vant_test/ 我上传到码云了 您可以微信打开然后上传以上大于4兆的图片 预览看一下什么问题

**Comment by zhangliyuan-chance** [comment]
> 能提供下复现的codeandbox链接么

http://luobozhang.gitee.io/vant_test/我上传到码云了您可以微信打开然后上传超过4兆的图片预览看一下什么问题

**Comment by zhangliyuan-chance** [comment]
> 能提供下复现的codeandbox链接么

http://luobozhang.gitee.io/vant_test/

**Comment by chenjiahan** [comment]
类似问题，在此 issue 中跟进：https://github.com/youzan/vant/issues/4864
