### ISSUE TITLE
官网文档经常性打不开，或者加载很久

### ISSUE THREAD

**Issue by kun910202** [youzan/vant#5122]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
官网是部署在 github pages 上的，建议你看下是不是访问 github 较慢，可以试下翻墙

**Comment by chenjiahan** [comment]
还可以访问我们的码云镜像 https://vant-contrib.gitee.io/vant
