### ISSUE TITLE
DatetimePicker时间选择器配合Popup 弹出层使用，在IOS设备不能滚动选择日期

### ISSUE THREAD

**Issue by linshupeng1** [youzan/vant#5123]
设备 / 浏览器
苹果设备

Vant 版本
2.2.14

Vue版本
2.6.10

描述问题
DatetimePicker时间选择器配合Popup 弹出层使用，在IOS设备不能滚动选择日期，但安卓设备正常

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/datetime-picker#zai-ios-xi-tong-shang-chu-shi-hua-zu-jian-shi-bai

**Comment by lwpassvoice** [comment]
https://github.com/youzan/vant/issues/3015

**Comment by yec520** [comment]
给时间选择器添加个伪元素就好了

**Comment by yec520** [comment]
> 设备 / 浏览器
> 苹果设备
> 
> Vant 版本
> 2.2.14
> 
> Vue版本
> 2.6.10
> 
> 描述问题
> DatetimePicker时间选择器配合Popup 弹出层使用，在IOS设备不能滚动选择日期，但安卓设备正常

给时间选择器添加个伪元素就好了

**Comment by linshupeng1** [comment]
> #3015



> > 设备 / 浏览器
> > 苹果设备
> > Vant 版本
> > 2.2.14
> > Vue版本
> > 2.6.10
> > 描述问题
> > DatetimePicker时间选择器配合Popup 弹出层使用，在IOS设备不能滚动选择日期，但安卓设备正常
> 
> 给时间选择器添加个伪元素就好了

已解决，感谢

**Comment by linshupeng1** [comment]
> 参见 https://youzan.github.io/vant/#/zh-CN/datetime-picker#zai-ios-xi-tong-shang-chu-shi-hua-zu-jian-shi-bai

试过，没有效果，我的IOS系统是10

**Comment by EVIL-lang** [comment]
看你上面说加个伪元素就解决了？

**Comment by chenjiahan** [comment]
iOS 10 可以参考这个 issue

https://github.com/youzan/vant/issues/3015
