### ISSUE TITLE
[Bug Report] tabs在使用sticky的时候offset-top： 0的时候，滚动有一点回弹

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#5124]
### 设备 / 浏览器
ios

### Vant 版本
2.2.14

### Vue版本
2.6.10

### 重现链接
<a href="http://dev.jbf.aijk.net/adminmall/mallc/index.html#/orderlist" target="_blank">http://dev.jbf.aijk.net/adminmall/mallc/index.html#/orderlist</a>

### 描述问题
tabs在使用sticky的时候offset-top： 0的时候，滚动有一点回弹，如果tabs最初不在最顶的时候，这个效果很好，但是一开始tabs就在最顶端，滑动的时候还要稍微的回弹下才在顶端固定，这个能优化下吗

**Comment by chenjiahan** [comment]
我看了下你提供的链接，没复现这个问题呢，具体是怎么操作的

**Comment by Thlq** [comment]
我这个现在改了组件的样式，没用哪个sticky，如果用了就会有我上面描述的那种情况，tab栏在最顶上的时候，设置sticky，offset-top=0，向上滑动的时候，tab还是有点向上飘一下，然后才固定在顶部，有抖动的效果

**Comment by chenjiahan** [comment]
能不能给个复现该问题的 codesandbox 链接呢

**Comment by youmu178** [comment]
我也遇到了 最后没用sticky  自己给内容设置了top
