### ISSUE TITLE
[Bug Report] 安卓浏览器使用多个Field,会出现闪动

### ISSUE THREAD

**Issue by chenyihao2621023** [youzan/vant#5125]
### 设备 / 浏览器
安卓手机

### Vant 版本
2.2.14

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-eqncu" target="_blank">https://codesandbox.io/s/vant-issue-moban-eqncu</a>

### 描述问题
当Field超过一屏时，点击聚焦任意一个Field，会导致下面的Field滚上来，然后再复原，出现闪动的情况

**Comment by chenjiahan** [comment]
具体是什么机型呢，userAgent 能否发下
