### ISSUE TITLE
[Feature Request]  Picker 选择器多列联动数据格式问题

### ISSUE THREAD

**Issue by chenxi5211993** [youzan/vant#5126]
### 这个功能解决了什么问题
可以增加多用应用场景；

### 描述您想要的解决方案
现在文档实例数据结构是：const citys = {
  '浙江': ['杭州', '宁波', '温州', '嘉兴', '湖州'],
  '福建': ['福州', '厦门', '莆田', '三明', '泉州']
};
但这种结构过于简单，我们后台取到的数据结构多数为tree类型的数组对象，甚至有可能为三级或者四级：
{
      label: '餐点',
      value: 0,
      children: [{
          label: '闽南菜',
          value: 0,
          children: [{
            label: '牛肉共',
            value: 0,
            children: [{
              label: '2块钱',
              value: 0,
            }, {
              label: '3KUAIQIAN',
              value: 1,
            }, ],
          }, ],
        },
      }
请问这种数据结构多列联动现在可以实现么？ 如过实现不了，vant里有可以推荐的插件么？

### 建议的API是什么样的
希望可以支持此种数据格式，应用场景非常多

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/4247
