### ISSUE TITLE
countdown 毫秒级显示只能3位数吗？想两位难道要改源码？希望给个配置

### ISSUE THREAD

**Issue by kimpyoon** [youzan/vant#5127]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以使用插槽自定义其他格式
