### ISSUE TITLE
[Feature Request] countdown 组件希望有毫秒级位数配置

### ISSUE THREAD

**Issue by kimpyoon** [youzan/vant#5129]
### 这个功能解决了什么问题
当我想要两位毫秒显示时，只能自己写个倒计时

### 描述您想要的解决方案
format 加个SS表示两位毫秒

### 建议的API是什么样的
format='HH:mm:ss:SS'

**Comment by chenjiahan** [comment]
后续会支持

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.1 版本支持
