### ISSUE TITLE
[Feature Request] NavBar 组件新增 prop

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#5131]
### 这个功能解决了什么问题
将 NavBar 放到全局 vue 文件，业务页面使用 store 来控制 NavBar 样式，这时需要传 prop 给  NavBar

### 描述您想要的解决方案
新增 wrapStyles prop 作为 NavBar 组件包裹的样式。
新增 titleStyles prop 作为 NavBar 组件标题的样式。
新增 leftStyles prop 作为 NavBar 组件左边的样式。
新增 rightStyles prop 作为 NavBar 组件右边的样式。

### 建议的API是什么样的
新增 wrapStyles prop 作为 NavBar 组件包裹的样式。
新增 titleStyles prop 作为 NavBar 组件标题的样式。
新增 leftStyles prop 作为 NavBar 组件左边的样式。
新增 rightStyles prop 作为 NavBar 组件右边的样式。

**Comment by chenjiahan** [comment]
暂无计划支持，建议通过动态设置 class 来调整样式
