### ISSUE TITLE
[Feature Request] sku组件，有什么办法能reset-selected-sku？

### ISSUE THREAD

**Issue by microkof** [youzan/vant#5132]
### 这个功能解决了什么问题
希望有办法，或者官方提供接口，能reset-selected-sku。但是不要给购买数量清0。

### 描述您想要的解决方案
请给一个操作data的方法，能reset-selected-sku，或者官方提供一个直接的resetSelectedSku方法。

### 建议的API是什么样的
直接调用API，显然就是resetSelectedSku了。或者给一个修改data的方法也行，因为我不知道修改哪里能reset-selected-sku。

**Comment by chenjiahan** [comment]
后续会看下能否支持

**Comment by chenjiahan** [comment]
已在 2.3.1 版本支持
