### ISSUE TITLE
[Bug Report] Do not use built-in or reserved HTML elements as component id: Image

### ISSUE THREAD

**Issue by sinhang** [youzan/vant#5135]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.14

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/image" target="_blank">https://youzan.github.io/vant/#/zh-CN/image</a>

### 描述问题
Do not use built-in or reserved HTML elements as component id: Image,使用图片组件的时候提示。
使用懒加载组件报：
Failed to resolve directive: lazy

**Comment by chenjiahan** [comment]
1. image 是原生标签，注册组件的时候记得注册为 van-image

2. 需要注册 Lazyload 组件
