### ISSUE TITLE
[Bug Report] TreeSelect 分类选择

### ISSUE THREAD

**Issue by JAYwind** [youzan/vant#5136]
### 设备 / 浏览器
浏览器

### Vant 版本
2.2.13

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-tyjwl" target="_blank">https://codesandbox.io/s/vant-issue-moban-tyjwl</a>

### 描述问题
点击选中或者取消右侧选项的时候，active-id这个值的变化有问题吧。不是应该没选择的时候删除，选中了把id加进去

**Comment by chenjiahan** [comment]
下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.1 版本修复
