### ISSUE TITLE
[Feature Request] Should we add a new hooks for Tab's first rendering？

### ISSUE THREAD

**Issue by joe223** [youzan/vant#5138]
### 这个功能解决了什么问题
There is no way for us to know whether the default tab-item is rendered successfully or not if `lazy-render` is set to `true`

### 描述您想要的解决方案
Add a new event named `rendered` when tab-item is rendered successfully in `lazy-render === true` situation.

### 建议的API是什么样的
Just like this:
```html
<van-tabs
    @rendered="handleTabItemRendered"
    ...

**Comment by chenjiahan** [comment]
Try this:

```html
<van-tabs v-model="active" @change="onChange">
  <van-tab name="a" />
  <van-tab name="b" />
  <van-tab name="b" />
</van-tabs>
```

```js
export default {
  data() {
    return {
      active: 'a',
      rendered: {
        a: true,
        b: false,
        c: false
      }
     };
  }
  methods: {
    onChange(name) {
      this.rendered[name] = true;
    }
  }
}
```

**Comment by joe223** [comment]
@chenjiahan So, could you tell me when tab-item `'a'` will be rendered at the first rendering without `$nextTick` hook ?

https://jsfiddle.net/6bfyq83m/4/

**Comment by chenjiahan** [comment]
It was my mistake, we should add the nextTick method to ensure that the rendering is complete, but we have no plans to add the rendered event in the Tab component.

**Comment by joe223** [comment]
We surly can use `$nextTick` without rendered event. It's won't be too inconvenient.
But using rendered event will be more accurate —— not just tab-item lazy-render will trigger `$nextTick`. This event can help programmer building succinct code.

**Comment by chenjiahan** [comment]
Can you make a PR to add this feature?

**Comment by joe223** [comment]
Of course. It just takes some times.

**Comment by chenjiahan** [comment]
done

**Comment by joe223** [comment]
Sadly, my PR is only a few hours late

**Comment by chenjiahan** [comment]
😂
