### ISSUE TITLE
字体建议

### ISSUE THREAD

**Issue by anjina** [youzan/vant#5140]
感觉原始字体14px 着实有点小了呀，希望官网能调整下，或者给出一个自定义全局字体的方式。一个个去覆盖样式有点麻烦

**Comment by chenjiahan** [comment]
可以通过定制主题的方式修改字体大小喔

https://youzan.github.io/vant/#/zh-CN/theme

**Comment by anjina** [comment]
> 可以通过定制主题的方式修改字体大小喔
> 
> https://youzan.github.io/vant/#/zh-CN/theme
好的 感谢！ 是我看文档不仔细。。。。
