### ISSUE TITLE
[Bug Report] SubmitBar 没有符号的话，文本的第一个数字样式错误

### ISSUE THREAD

**Issue by LvJianfeng** [youzan/vant#5141]
### 设备 / 浏览器
chrome iphone x

### Vant 版本
2.2.15

### Vue版本
2.6.10

### 重现链接
<a href="http://127.0.0.1" target="_blank">http://127.0.0.1</a>

### 描述问题
SubmitBar currency = ‘’ 为空的时候，文本的第一个数字样式错误

**Comment by Lindysen** [comment]
会在下个版本修复这个问题

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.1 版本修复

**Comment by LvJianfeng** [comment]
@chenjiahan 

小数位为0的时候，金额后面仍有小数点符号。
使用版本```2.3.0-beta.2```

**Comment by chenjiahan** [comment]
@Lindysen
