### ISSUE TITLE
[Bug Report] van-field--- show-word-limit字数统计没出来

### ISSUE THREAD

**Issue by pikachuWorld** [youzan/vant#5148]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.1.1

### Vue版本
2.6.10

### 重现链接
<a href="http://localhost:8000/#/maintain" target="_blank">http://localhost:8000/#/maintain</a>

### 描述问题
van-field组件--加了- show-word-limit字数统计没出来

**Comment by chenjiahan** [comment]
请注意 props 的版本要求

**Comment by pikachuWorld** [comment]
升级到最新版本好了

**Comment by pikachuWorld** [comment]
> 请注意 props 的版本要求

字数统计的内容目前是不是不可以自定义

**Comment by chenjiahan** [comment]
目前不支持喔，需要什么样的格式呢

**Comment by pikachuWorld** [comment]
> 目前不支持喔，需要什么样的格式呢

比如目前还可以输入50字等自定义类的

**Comment by chenjiahan** [comment]
可以新开一个 issue 提这个需求，我们加一个插槽来自定义
