### ISSUE TITLE
Stepper 组件样式有问题

### ISSUE THREAD

**Issue by 392241868** [youzan/vant#5149]
![image](https://user-images.githubusercontent.com/7981126/69853403-c3baaa80-12c1-11ea-8bd8-08d9d2ce9c3f.png)
有些时候，before伪元素定位不知道跑哪里去了，图标出不来，详情情况图片

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by lixiaofa** [comment]
> 请按照模板创建 issue，感谢配合

![image](https://user-images.githubusercontent.com/23230215/212314984-b9f2fff4-2302-4a1b-9d27-315603e29513.png)
![image](https://user-images.githubusercontent.com/23230215/212315034-705803b7-da9f-46f1-ab38-938244a9385f.png)
样式失效
@chenjiahan
