### ISSUE TITLE
tabbar 定制样式

### ISSUE THREAD

**Issue by KobeBryant824** [youzan/vant#5155]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

--- <div role="tab" class="van-tab" style="color: rgb(26, 26, 26); flex-basis: 22%;"><span class="van-ellipsis"><div style="flex-basis: 20%;"><span style="font-size: 14px;">受理中</span></div></span></div>

这个flex-basis: 22% 怎么设置20%呢

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by KobeBryant824** [comment]
:finished="finished"<div role="tab" class="van-tab" style="color: rgb(26, 26, 26); flex-basis: 22%;"><span class="van-ellipsis"><div style="flex-basis: 20%;"><span style="font-size: 14px;">受理中</span></div></span></div>

**Comment by KobeBryant824** [comment]
<div role="tab" class="van-tab" style="color: rgb(26, 26, 26); flex-basis: 22%;"><span class="van-ellipsis"><div style="flex-basis: 20%;"><span style="font-size: 14px;">受理中</span></div></span></div>

**Comment by chenjiahan** [comment]
你说的是 Tab 组件吧，这个是根据 swipe-threshold 计算出来的，可以调整 swipe-threshold 属性，或者通过 css 覆盖
