### ISSUE TITLE
Picker组件样式有问题

### ISSUE THREAD

**Issue by 13725102796** [youzan/vant#5156]
vant版本2.2.5
使用方式cdn引入
发现问题： .van-picker-column__item该类的宽度是通过flex: 1;控制
发现并不生效；

.city /deep/ .van-picker-column__item {
  width: 33.33vw!important;
}
.picker /deep/ .van-picker-column__item {
  width: 100vw!important;
}
用样式穿透强制对省市区联动 和 picker选择器进行强制重置了
同时还要强制重置以下父类
body /deep/ .van-picker-column {
  overflow: visible!important;
}
body /deep/ .van-picker__columns{
  overflow: hidden!important;
}
body /deep/ .van-picker-column__item {
  padding: 0!important;
}
才可以正常显示。

**Comment by chenjiahan** [comment]
`flex: 1`的样式会生效的，如果没生效的话，建议排查下是不是被其他样式干扰了

**Comment by 13725102796** [comment]
确实，我通过简单的html使用发现是正常的。现在项目用的是spa的方式，估计和某些包冲突了。等我找到原因再说。
