### ISSUE TITLE
[Feature Request] 希望宫格能够支持圆边设置、选中后背景颜色设置

### ISSUE THREAD

**Issue by udoinglike** [youzan/vant#5158]
### 这个功能解决了什么问题
能把grid用做于同类项目选择器 , 圆边能使格子更圆润更好看，选中后背景颜色够更清晰知道当前是选中哪项。

### 描述您想要的解决方案
提供border-radius 和 selected 样式的参数。

### 建议的API是什么样的
设置border-radius 和 selected 样式的参数  来设置 圆边效果和选中背景颜色。

**Comment by chenjiahan** [comment]
暂无计划提供这样的样式属性喔，建议直接通过 CSS 选择器覆盖对应的样式
