### ISSUE TITLE
建议统一价格单位

### ISSUE THREAD

**Issue by Lifaliang1996** [youzan/vant#5159]
“Card商品卡片”的价格的单位是“元”，“SubmitBar提交订单”与“Sku商品规格”的单位是“分”，建议统一下哦

**Comment by chenjiahan** [comment]
这里确实是统一比较好，不过这个改动会造成不兼容更新，因此短期内不会调整

**Comment by thinkif** [comment]
建议：在SubmitBar中加一个单位的属性，默认还用“分”，但是可以选择使用“元”

**Comment by greenhand-xj** [comment]
刚刚碰到了这个问题了
