### ISSUE TITLE
希望tabbar的title支持badge 或自定义slot 或者navbar一样的info属性

### ISSUE THREAD

**Issue by artiely** [youzan/vant#516]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@artiely 请问 tarbar 的 title 指的是？

**Comment by artiely** [comment]
就像navbar的info属性一样的效果

**Comment by chenjiahan** [comment]
@artiely Tabbar 也是有 info 属性的，麻烦再查看下文档

**Comment by artiely** [comment]
我说错了 希望tab也有和tabbar一样的info属性

**Comment by chenjiahan** [comment]
@artiely 目前没有在 Tab 上增加 info 属性的计划，欢迎你提 PR 增加这一功能
