### ISSUE TITLE
使用遮罩层时，进度条组件不能正常显示

### ISSUE THREAD

**Issue by 312798** [youzan/vant#5161]
使用遮罩层显示隐藏时，进度条显示不了数值，只显示背景
![Qe6VoT](https://user-images.githubusercontent.com/33946924/69911403-feede280-1455-11ea-9283-3bde05706bca.png)

**Comment by chenjiahan** [comment]
如果在父元素隐藏的情况下渲染 Progress，组件本身取不到元素宽度就会出现这个问题。

这个问题在 Popup 默认开启 lazy-render 的情况下应该不会出现，还有一种解决方案是在 Progress 上添加 v-if 来控制只在显示弹窗时渲染
