### ISSUE TITLE
Uploader max-size oversize

### ISSUE THREAD

**Issue by skyshirt** [youzan/vant#5164]
设备 / 浏览器
Chrome 78.0.3904.108

Vant 版本
v2.2.15

Vue版本
2.6.10

描述问题
当上传文件大小超过max-size，第2次选择相同文件，没有触发oversize事件

**Comment by chenjiahan** [comment]
下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.2 版本修复
