### ISSUE TITLE
建议Uploader增加删除指定已上传文件的实例方法

### ISSUE THREAD

**Issue by skyshirt** [youzan/vant#5165]
想通过其它交互，不局限在已上传图片右上角删除图标，来删除指定的已上传图片
比如Uploader可以点击图片，实现快速预览的功能，通过自定义删除按钮实现删除功能

**Comment by chenjiahan** [comment]
直接更新 v-model 绑定的 fileList，剔除要删除的图片即可，不需要提供实例方法
