### ISSUE TITLE
[Feature Request] 希望增加新的属性，控制ActionSheet 组件中button的默认提交事件

### ISSUE THREAD

**Issue by cmm-va** [youzan/vant#5166]
### 这个功能解决了什么问题
form表单中，点击菜单会触发默认事件

### 描述您想要的解决方案
希望增加一个新的属性

### 建议的API是什么样的
native-type

**Comment by chenjiahan** [comment]
这种通过 ActionSheet 来提交表单的情况不太常见，暂时没计划支持该属性。建议通过 JS 来提交表单

**Comment by pgonelover** [comment]
在form 里使用了action Sheet,因为不想用这个组件提交表单，但是点击组件之后会导致整个页面的刷新。------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>
发送时间: 2019年12月3日(星期二) 下午5:06
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "pgonelover"<867884660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Feature Request] 希望增加新的属性，控制ActionSheet 组件中button的默认提交事件 (#5166)



这种通过 ActionSheet 来提交表单的情况不太常见，暂时没计划支持该属性。建议通过 JS 来提交表单
 
&mdash;

**Comment by chenjiahan** [comment]
触发提交表单确实是不应该的，后续会改下，ActionSheet 里的 button 默认添加 type="button"

**Comment by pgonelover** [comment]
谢谢   辛苦 ------------------ 原始邮件 ------------------
发件人: "neverland"<notifications@github.com>
发送时间: 2019年12月3日(星期二) 下午5:35
收件人: "youzan/vant"<vant@noreply.github.com>;
抄送: "pgonelover"<867884660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant] [Feature Request] 希望增加新的属性，控制ActionSheet 组件中button的默认提交事件 (#5166)



触发提交表单确实是不应该的，后续会改下，ActionSheet 里的 button 默认添加 type="button"
 
&mdash;

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.2 版本修复
