### ISSUE TITLE
[Bug Report] SwipeCell 滑动单元格 PC上侧滑后松开鼠标按键，会触发 click 事件

### ISSUE THREAD

**Issue by varjay** [youzan/vant#5167]
### 设备 / 浏览器
macOS10.15 / chrome 78

### Vant 版本
2.2.15

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/swipe-cell" target="_blank">https://youzan.github.io/vant/#/zh-CN/swipe-cell</a>

### 描述问题
在电脑上使用 SwipeCell 滑动单元格，侧滑后松开鼠标按键，会触发 click 事件。按理说不应该触发，求修！

**Comment by chenjiahan** [comment]
最新版已经修复了这个问题，请确认下你的版本在 2.2.14 版本以上

**Comment by H-Sven** [comment]
@chenjiahan 这个问题依然存在  "vant": "^4.8.7",
