### ISSUE TITLE
[Bug Report] actionSheet上拉菜单将页面顶起

### ISSUE THREAD

**Issue by 841440416** [youzan/vant#5170]
### 设备 / 浏览器
ios/android/chorme

### Vant 版本
2.2.12

### Vue版本
2.6.10

### 重现链接
<a href="http://app-test.angelalign.com:8888/#/doctorDetail/d35843af-b2ef-6f74-896a-5de4bfb7776b" target="_blank">http://app-test.angelalign.com:8888/#/doctorDetail/d35843af-b2ef-6f74-896a-5de4bfb7776b</a>

### 描述问题
step1:访问链接页面，将“访问方式”、“个人说明”折叠面板展开直至内容大于手机可视区高度
![image](https://user-images.githubusercontent.com/26712681/70013657-59508580-15b3-11ea-98f5-cd8bd33c9714.png)
step2:点击“居住地”等唤起action-sheet组件
![image](https://user-images.githubusercontent.com/26712681/70013698-708f7300-15b3-11ea-88d2-a5624d4e9b90.png)
setp3:这时候会发现页面被顶至最顶部
![image](https://user-images.githubusercontent.com/26712681/70013738-91f05f00-15b3-11ea-87c3-4b76e0fc2373.png)

**Comment by chenjiahan** [comment]
ActionSheet 组件不会控制滚动条的位置，你可以把 lock-scroll 属性去掉试下

还有不建议在 body/html/app 上面设置 height: 100%，这样会导致元素高度不太正常

**Comment by 841440416** [comment]
> ActionSheet 组件不会控制滚动条的位置，你可以把 lock-scroll 属性去掉试下
> 
> 还有不建议在 body/html/app 上面设置 height: 100%，这样会导致元素高度不太正常

按照您的意见改了，但是还是会有顶起页面的问题

**Comment by chenjiahan** [comment]
能否提供一个复现问题的 codesandbox 链接呢

**Comment by 841440416** [comment]
> 能否提供一个复现问题的 codesandbox 链接呢

这周我会提供个demo给您

**Comment by chenjiahan** [comment]
好的

**Comment by 841440416** [comment]
> 好的

codesandbox 无法安装vant依赖，所以没有办法提供给你，能否加我WX:17621594177, 线下联系

**Comment by chenjiahan** [comment]
codesandbox 可以安装 vant 的，参见 https://codesandbox.io/s/m5v3f

**Comment by 841440416** [comment]
> codesandbox 可以安装 vant 的，参见 https://codesandbox.io/s/m5v3f

htt请参照ps://codesandbox.io/s/vant-issue-moban-ub1x6，是否有移动端模式，很奇怪，代码跟我项目几乎一模一样，可是我项目中就是会顶起，并发现只要是有van-pop弹出组件都有这个问题

**Comment by chenjiahan** [comment]
建议排查下是不是项目里的一些全局样式或逻辑导致的喔
