### ISSUE TITLE
苹果手机    van-swipe和fastclick 一起用的情况下  van-swipe一碰就触发点击事件 特别灵敏

### ISSUE THREAD

**Issue by buguima** [youzan/vant#5174]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
把 stop-propagation 设置为 false 可以避免这个问题
