### ISSUE TITLE
阿里云OSS多图片上传问题

### ISSUE THREAD

**Issue by wendesun** [youzan/vant#5184]
1、阿里云oss多图上传，我是在:before-read做异步校验，只有当oss上传成功后才返回resolve()，失败返回reject()， 单张图片上传没有问题。
2、如果是多张图片上传，oss上传部分成功呢，  这里应该怎么处理？

**Comment by skyshirt** [comment]
同上，图片一张一张上传，如果失败一张reject()，预览图全都看不到，resolve()不管成功失败全都能看到

**Comment by chenjiahan** [comment]
可以先 resolve，然后将 fileList 中未上传的图片通过 splice 剔除掉
