### ISSUE TITLE
您好，tab组件设置属性可能设置失败

### ISSUE THREAD

**Issue by liuxiaomounazhedao** [youzan/vant#5188]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by liuxiaomounazhedao** [comment]
怎么创建






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2019年12月4日(星期三) 晚上11:04
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "不知道"<3193025869@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] 您好，tab组件设置属性可能设置失败 (#5188)




请按照模板创建 issue，感谢配合

**Comment by chenjiahan** [comment]
通过 https://youzan.github.io/vant-issue-generater 创建
