### ISSUE TITLE
DatetimePicker在华为P20唤起选项列表后，无法点击确认

### ISSUE THREAD

**Issue by KingArticle** [youzan/vant#5189]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater
vant的DatetimePicke日期选择组件，在华为p20唤起选项列表后，经常出现确认点不动，有人反映在p30和Pro也有此情况
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
