### ISSUE TITLE
Apple IOS 13.0 访问使用NumberKeyboard 数字键盘会卡顿

### ISSUE THREAD

**Issue by Luckyre** [youzan/vant#5190]
设备 / 浏览器
IOS 13.0

Vant 版本
v2.2.6（升级 2.2.16也同样）

Nuxt版本
2.8.10

描述问题
￼￼￼￼1、使用Apple IOS 13.0 访问 https://youzan.github.io/vant/mobile.html#/zh-CN/password-input 输入有明显卡顿，不流畅问题
2、内嵌App webview 在此设备也有同样现象 ，

**Comment by chenjiahan** [comment]
iOS 13.0 卡顿的情况是系统 bug，升级系统版本即可解决，组件内暂时无兼容方案
