### ISSUE TITLE
[Bug Report] 折叠面板

### ISSUE THREAD

**Issue by guagezuishuai** [youzan/vant#5191]
### 设备 / 浏览器
浏览器

### Vant 版本
2.2.16

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/m5v3f" target="_blank">https://codesandbox.io/s/m5v3f</a>

### 描述问题
上面是无效连接，我是本地开发遇到的问题，
vue.min.js:6 TypeError: Cannot read property 'children' of null
    at a.ChildrenMixin.vue__WEBPACK_IMPORTED_MODULE_0__.default.extend.computed._computed.<computed> (relation.js?a55e:42)
    at fn.get (vue.min.js:6)
    at fn.evaluate (vue.min.js:6)
    at a.index (vue.min.js:6)
    at a.render (index.js?3e85:171)
    at a.e._render (vue.min.js:6)
    at a.r (vue.min.js:6)
    at fn.get (vue.min.js:6)
    at new fn (vue.min.js:6)
    at vue.min.js:6
以上为报错信息。

```
<van-collapse v-model="activeNames" accordion>
      <van-collapse-item
        :title="item.name"
        :name="index"
        icon="friends-o"
        v-for="(item,index) in list"
        :key="item.name index"
      >
        <van-list :finished="true">
          <van-cell
            v-for="(listItem,index1) in item.children"
            :key="listItem.name index1"
            :title="listItem.name"
            @click="listItemClick(listItem.tableId)"
          />
        </van-list>
      </van-collapse-item>
    </van-collapse>
```
以上是我的代码，我用div直接for循环是没问题的。所以我认为是组件的问题

**Comment by chenjiahan** [comment]
能否把你本地开发遇到的问题在 codesandbox 上尝试复现下呢

**Comment by guagezuishuai** [comment]
这个没什么复现的老哥，就是正常加载报错，完了页面就不渲染了，复现了也是一个空白页面。

**Comment by guagezuishuai** [comment]
> 能否把你本地开发遇到的问题在 codesandbox 上尝试复现下呢
这个没什么复现的老哥，就是正常加载报错，完了页面就不渲染了，复现了也是一个空白页面。

**Comment by chenjiahan** [comment]
你不提供复现代码，我们也没法帮你排查。

**Comment by guagezuishuai** [comment]
> 你不提供复现代码，我们也没法帮你排查。
我的问题里面我提供了我的代码了，错误提示我也提供了。应该能看到才对额。。

**Comment by guagezuishuai** [comment]
> 你不提供复现代码，我们也没法帮你排查。

对了，咱们的时间选择器能支持到选择秒么？我们对应pc的数据时间选择需要具体到秒的啊，，，

**Comment by chenjiahan** [comment]
> 我的问题里面我提供了我的代码了，错误提示我也提供了

你提供的代码只有 template 部分，而且中间有完全不正确的语句，比如`:key="listItem.name index1"`

> 咱们的时间选择器能支持到选择秒么

暂无计划支持
