### ISSUE TITLE
[Bug Report] notify组件文档描述和示例不一致

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant#5192]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.3.0-beta.1

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/notify#yin-ru" target="_blank">https://youzan.github.io/vant/#/zh-CN/notify#yin-ru</a>

### 描述问题
notify组件文档描述和示例不一致
![image](https://user-images.githubusercontent.com/23445650/70207575-26022800-1766-11ea-9642-46c94ef7f4f1.png)
![image](https://user-images.githubusercontent.com/23445650/70207596-34504400-1766-11ea-9acd-a2a0bf8966f2.png)

**Comment by chenjiahan** [comment]
`info` 应替换为 `success`，能否提个 PR 帮忙修正一下

**Comment by chenjiahan** [comment]
文档已更正
