### ISSUE TITLE
粘性布局吸顶时在IOS出现抖动

### ISSUE THREAD

**Issue by zhouguanglong** [youzan/vant#5193]
http://test-admin.skxny.bjoil.com/market/appPreview?id=38&origin=h5  请在IOS浏览器访问一下此链接，滑动到下面时出现抖动

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/70208132-b68d3800-1767-11ea-86db-69cd17b1a206.png)

Tab 设置了两栏标题？
