### ISSUE TITLE
轮播图怎么及时停止呢？

### ISSUE THREAD

**Issue by zhouguanglong** [youzan/vant#5196]
轮播图从0即将到1 ，怎么及时停止并留在0，怎么及时停止并立即到1？

**Comment by chenjiahan** [comment]
不是很懂你的意思，如果需要主动切换轮播位置，可以使用 swipeTo 方法

**Comment by zhouguanglong** [comment]
不是主动切换，而是及时停止轮播，类似于 jQuery 的 stop(true,false)

**Comment by chenjiahan** [comment]
不支持停止噢
