### ISSUE TITLE
[Bug Report] Picker和DatetimePicker，在华为P20无法点击确认

### ISSUE THREAD

**Issue by KingArticle** [youzan/vant#5200]
### 设备 / 浏览器
华为P20

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://www.baidu.com/" target="_blank">https://www.baidu.com/</a>

### 描述问题
Picker和DatetimePicker，在华为P20无法点击确认按钮，点击无效，弹框不会消失

**Comment by chenjiahan** [comment]
使用官网示例能复现这个问题吗？

**Comment by KingArticle** [comment]
在官网无法复现，我们项目是公司内部使用，地址是不允许放到外面，我在官网放那个链接只是为了顺利提交问题，现在提供照片一张，途中圈起来的位置，确认两个字无法点击





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 中午11:46
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"章"<1036547965@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] Picker和DatetimePicker，在华为P20无法点击确认 (#5200)




使用官网示例能复现这个问题吗？

**Comment by chenjiahan** [comment]
如果官网没问题的话，建议你看下是不是项目本身的代码逻辑有问题

**Comment by KingArticle** [comment]
在大多数手机都是没问题的，只是在华为p20有这个问题，不过也有网友说在p30和pro都有问题，这个目前没发现


---原始邮件---
发件人: &quot;neverland&quot;<notifications@github.com&gt;
发送时间: 2019年12月10日(周二) 中午11:55
收件人: &quot;youzan/vant&quot;<vant@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;Panda&quot;<1036547965@qq.com&gt;;
主题: Re: [youzan/vant] [Bug Report] Picker和DatetimePicker，在华为P20无法点击确认 (#5200)



如果官网没问题的话，建议你看下是不是项目本身的代码逻辑有问题
 
&mdash;

**Comment by chenjiahan** [comment]
由于官网不能复现，建议自行排查
