### ISSUE TITLE
[Feature Request] notify设置duration为0之后怎么手动关闭？

### ISSUE THREAD

**Issue by Lynn-cc** [youzan/vant#5201]
### 这个功能解决了什么问题
notify打开，并手动根据需要关闭

### 描述您想要的解决方案
返回一个实例，包含close方法

### 建议的API是什么样的
let notify = this.$notify(options);
notify.close();

**Comment by chenjiahan** [comment]
调用 `Notify.clear()` 即可

**Comment by Lynn-cc** [comment]
哦，是因为webapp那个文档里没有：https://youzan.github.io/vant-weapp/#/notify
两个文档非常像呀：
https://youzan.github.io/vant/#/zh-CN/notify

**Comment by chenjiahan** [comment]
噢噢，小程序文档里需要补充一下这个方法的说明
