### ISSUE TITLE
[Bug Report] 轮播图和van-tabs粘性布局同时使用时，吸顶时会出现闪动

### ISSUE THREAD

**Issue by zhouguanglong** [youzan/vant#5203]
### 设备 / 浏览器
iphone8Plus safari

### Vant 版本
2.2.16

### Vue版本
2.6.10

### 重现链接
<a href="http://test-admin.skxny.bjoil.com/market/appPreview?id=38&origin=h5" target="_blank">http://test-admin.skxny.bjoil.com/market/appPreview?id=38&origin=h5</a>

### 描述问题
轮播图与van-tabs粘性布局同时使用时，导航栏的tab吸顶时会出现闪动

**Comment by JakeLaoyu** [comment]
重现链接里没有轮播图
