### ISSUE TITLE
[Bug Report] van-tabs粘性布局切换tab后怎么保存位置，再切换回来怎么驱动回到刚才的位置

### ISSUE THREAD

**Issue by zhouguanglong** [youzan/vant#5205]
### 设备 / 浏览器
iphone8Plus safari

### Vant 版本
2.2.16

### Vue版本
2.6.10

### 重现链接
<a href="http://test-admin.skxny.bjoil.com/market/appPreview?id=38" target="_blank">http://test-admin.skxny.bjoil.com/market/appPreview?id=38</a>

### 描述问题
van-tabs粘性布局切换tab后怎么保存位置，再切换回来怎么驱动回到刚才的位置

**Comment by JakeLaoyu** [comment]
https://codesandbox.io/s/m5v3f  能否提供一下实现姿势

**Comment by JakeLaoyu** [comment]
@zhouguanglong 可以通过全局覆盖 .van-tab__pane-wrapper 样式实现
![image](https://user-images.githubusercontent.com/16181940/70300616-e9503280-1832-11ea-8cfc-c8720dd2ee97.png)

**Comment by Xiaoshizaizi** [comment]
> @zhouguanglong 可以通过全局覆盖 .van-tab__pane-wrapper 样式实现
> ![image](https://user-images.githubusercontent.com/16181940/70300616-e9503280-1832-11ea-8cfc-c8720dd2ee97.png)
也遇到了，当tab吸顶，切换时，列表数据又会跳转顶部

**Comment by linsywu** [comment]
@zhouguanglong 这个问题主要是多个tab同时都处于document这个滚动域中，滚动调位置会相互影响导致的，如果.van-tab__pane-wrapper 中的内容是盛满全屏的，可以绝对定位覆盖其样式，然后四个.van-tab__pane-wrapper 独立滚动就不会出现总是置顶的情况了。
但是看了你的例子，跟我的一样，页面上半部分是公共的，然后滚动到tabs区域的时候，tans吸顶，这时候.van-tab__pane-wrapper 才可以做撑满全屏幕处理？通过监听吸顶事件可以实现前期.van-tab__pane-wrapper 高度100%，禁止滚动，然后当tabs吸顶的时候.van-tab__pane-wrapper 内部可以滚动，这样.van-tab__pane-wrapper 内部滚动位置得到保留，但是整体的滚动再tabs吸顶的时候会有一个卡顿，不是很友好，不知道道友又没有更好的解决方案？

**Comment by youmu178** [comment]
可以利用骨架屏组件 解决

**Comment by Xiaoshizaizi** [comment]
> 可以利用骨架屏组件 解决

大佬讲下思路

**Comment by chenjiahan** [comment]
保存位置的逻辑可以自行实现，记录下滚动条位置即可，组件内暂时没有计划提供对应的功能，先 close 了
