### ISSUE TITLE
van-collapse-item 的 onTransitionEnd 事件 bug

### ISSUE THREAD

**Issue by linhaihero** [youzan/vant#5206]
当 van-collapse-item 内某连接点击跳转路由，并且触发了css 动画（例如:active伪类什么的） ，就会报错，排查源码发现绑定了 onTransitionEnd 这个事件，路由跳转后找不到原来原来页面的$refs.wrapper造成的。

**Comment by JakeLaoyu** [comment]
是在动画未执行完点了跳转链接么

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
