### ISSUE TITLE
iPhone XS   ios13    Popup bug

### ISSUE THREAD

**Issue by akaiya** [youzan/vant#5207]
设置从右弹出，总是先弹出半截以后，在全屏

**Comment by JakeLaoyu** [comment]
提供一下版本

**Comment by akaiya** [comment]
就是你们文档的cdn版本，直接引入的

在 2019-12-06 11:21:07，"Jake" <notifications@github.com> 写道：


提供一下版本

**Comment by JakeLaoyu** [comment]
我在 13.2.3 的版本上没有复现，能否提供一个简单的demo https://codesandbox.io/s/m5v3f

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
