### ISSUE TITLE
同一页面存在两个van-sticky，其中一个设置offset-top，但两个之间不会贴合

### ISSUE THREAD

**Issue by 21lin10** [youzan/vant#5211]
设备 / 浏览器
部分手机

Vant 版本
2.2.16

Vue版本
2.5.2

图片示例
![image](https://user-images.githubusercontent.com/40971359/70309468-941f1b80-1848-11ea-8f64-bf4df8faf703.png)

描述问题
同一页面存在两个 van-sticky组件 滑动两个不会贴合，会出现一条大概2px的间隙 部分手机才存在（水滴屏，流海屏）

**Comment by chenjiahan** [comment]
麻烦提供一下复现问题的 codesandbox 链接
