### ISSUE TITLE
[Bug Report] treeselect  如何使用插槽自定义内容

### ISSUE THREAD

**Issue by Safisun** [youzan/vant#5212]
### 设备 / 浏览器
iPhone

### Vant 版本
2.3.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tree-select" target="_blank">https://youzan.github.io/vant/#/zh-CN/tree-select</a>

### 描述问题
右侧如何动态绑定参数渲染带图片的item

**Comment by chenjiahan** [comment]
文档有示例代码 https://youzan.github.io/vant/#/zh-CN/tree-select#zi-ding-yi-nei-rong

**Comment by Safisun** [comment]
> 文档有示例代码 https://youzan.github.io/vant/#/zh-CN/tree-select#zi-ding-yi-nei-rong

我想要的是如何知道选择父级里面children值的调用方法，而不是静态的图片链接demo

**Comment by chenjiahan** [comment]
直接读取 active-id 即可

**Comment by liuzhenji** [comment]
> 直接读取 active-id 即可

渲染怎么渲染？

**Comment by liuzhenji** [comment]
看了下源码，不支持。只能自己用activeId取childern来渲染到content slots

**Comment by linxingli** [comment]
> 
数组已知，active-id也已知，就能渲染具体某一项item.children了
