### ISSUE TITLE
[Bug Report] v-lazy 会加载两次图片

### ISSUE THREAD

**Issue by macmatilda** [youzan/vant#5213]
### 设备 / 浏览器
Chrome

### Vant 版本
2.3.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-rpsfq?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-rpsfq?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
https://img.yzcdn.cn/vant/apple-1.jpg  会加载两次

<template>
    <div>
        <img v-lazy="image" />
    </div>
</template>
<script>
    export default {
        data() {
            return {
                image:'https://img.yzcdn.cn/vant/apple-1.jpg'
            }
        },
    }
</script>
<style scoped>
</style>

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3372
