### ISSUE TITLE
[Bug Report] 使用tab标签吸顶无效

### ISSUE THREAD

**Issue by y451687300** [youzan/vant#5216]
### 设备 / 浏览器
Chrome

### Vant 版本
2.3.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="http://test.tdh5.lingqian360.com/#/" target="_blank">http://test.tdh5.lingqian360.com/#/</a>

### 描述问题
我在项目中使用了tab组件   设置了吸顶属性   但是没有生效    tab组件外面有我使用的mescroll组件

**Comment by chenjiahan** [comment]
建议你看下是不是这个 mescroll 组件影响了 sticky，可以去掉 mescroll 试下。
