### ISSUE TITLE
Tabbar当我添加 to=""跳转的时候，active样式并没有添加到我所点击的那个地方，而是要再次点击才会添加

### ISSUE THREAD

**Issue by zengjingke** [youzan/vant#522]
![1](https://user-images.githubusercontent.com/31331515/34714680-286eb09c-f565-11e7-8c5e-4f71eccbb626.png)
![2](https://user-images.githubusercontent.com/31331515/34714683-2cf074a2-f565-11e7-978a-1dbe681a4747.png)

**Comment by chenjiahan** [comment]
@zengjingke 请确认下你的 active 值是否正确设置，谢谢

**Comment by zengjingke** [comment]
console.log出的值 是对应的，没错

**Comment by chenjiahan** [comment]
@zengjingke 你是不是在两个不同的视图分别渲染了 Navbar 组件，active 应该放到全局的状态里

**Comment by zengjingke** [comment]
的确是两个视图需要这个ui 我试一下 谢谢****

**Comment by zengjingke** [comment]
当组件全局的时候 是没有问题的，应该是进入另一个视图中那个tabbar active还没点击所以不会添加样式，ps：维护者的回复速度还是挺快的嘛，赞

**Comment by chenjiahan** [comment]
@zengjingke 嗯嗯，是这个原因 ^_^
