### ISSUE TITLE
[Bug Report] 使用tab标签吸顶无效

### ISSUE THREAD

**Issue by y451687300** [youzan/vant#5221]
### 设备 / 浏览器
Chrome

### Vant 版本
2.3.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="http://test.tdh5.lingqian360.com/#/" target="_blank">http://test.tdh5.lingqian360.com/#/</a>

### 描述问题
我使用tab组件设置了sticky属性   但是不吸顶   之前外面使用mescroll组件   我把组件替换成了 van-list 组件  tab依旧不吸顶   我在van-list中使用了card组件   有没有什么解决的方法   让tabs吸顶呢

**Comment by chenjiahan** [comment]
看了下你的复现链接，是可以正常吸顶的

**Comment by y451687300** [comment]
> 看了下你的复现链接，是可以正常吸顶的

今天不知道怎么又好了    可能是我的浏览器的手机模拟器有问题
