### ISSUE TITLE
nuxt 中直接以引入cdn组件报错

### ISSUE THREAD

**Issue by wlinglinux** [youzan/vant#5225]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
![image](https://user-images.githubusercontent.com/286261/70413115-8e684680-1a91-11ea-9bcd-b22ecf74c070.png)
 报错信息是<van-button> - did you register the component correctly?

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
