### ISSUE TITLE
[Feature Request] 能不能给全局和有 sticky/fixed 属性的模块加上 safe-area-inset-top 属性

### ISSUE THREAD

**Issue by questionlin** [youzan/vant#5226]
### 这个功能解决了什么问题
做成 webapp 的时候，对于有 sticky/fixed 属性的模块，会顶到顶部，被刘海覆盖。safe-area-inset-top 很难加到 offset-top 上。最好官方能直接在模块里面支持

### 描述您想要的解决方案
直接在模块里面支持

### 建议的API是什么样的
左括号 van-nav-bar fixed safe-area-inset-top 右括号
左括号 stycky safe-area-inset-top 右括号
左括号 van-tabs sticky safe-area-inset-top 右括号

**Comment by chenjiahan** [comment]
后续会评估下

**Comment by questionlin** [comment]
@chenjiahan 好像不用了，调节下状态览的参数就可以了
