### ISSUE TITLE
[Bug Report] card价格字体优化

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#5227]
### 设备 / 浏览器
ios

### Vant 版本
2.3.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant" target="_blank">https://youzan.github.io/vant</a>

### 描述问题
目前card价格结构是<div>¥<span class="van-card__price-integer">5</span>.<span class="van-card__price-decimal">88</span></div>,这样修改￥和·样式相对比较麻烦，能给￥和·包一个span加个class吗
![image](https://user-images.githubusercontent.com/21211777/70413794-3c282500-1a93-11ea-80e5-b69ae6c45776.png)

**Comment by chenjiahan** [comment]
价格符号可以加一个 class，点号似乎没什么必要，可以继承父标签样式的

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.4 版本优化
