### ISSUE TITLE
[Bug Report] 收货地址手机号显示多了一位

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#5228]
### 设备 / 浏览器
ios

### Vant 版本
2.3.0-beta.2

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant" target="_blank">https://youzan.github.io/vant</a>

### 描述问题
收货地址列表，手机号自动多了以为，查看vue里面的数据是正常的，同时设置未默认地址的那一项手机号显示也正常
![image](https://user-images.githubusercontent.com/21211777/70415226-1ef55580-1a97-11ea-97f4-52bd699a3ac2.png)
![image](https://user-images.githubusercontent.com/21211777/70415256-35031600-1a97-11ea-842f-cdeb6b05e7f5.png)

**Comment by Thlq** [comment]
找到原因了，之前源码的短路运算如果isDefault为false的情况false会渲染成0，所以不是默认地址的都会加一个0，把短路运算改成三目运算isDefault为false的情况渲染成空就行了
![image](https://user-images.githubusercontent.com/21211777/70417616-a2657580-1a9c-11ea-941b-03e9ba2aaa57.png)

**Comment by chenjiahan** [comment]
@rex-zsd

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.3 版本修复
