### ISSUE TITLE
集中反馈几个小问题

### ISSUE THREAD

**Issue by dzcms** [youzan/vant#523]
1.全局导入
`import Vue from 'vue';
import Vant from 'vant';
import 'vant/lib/vant-css/index.css';
Vue.use(Vant);`
提示： Vant is not defined
2.Toast 轻提示组件 use之后，如果页面没使用它，会弹出一段代码，这里不好截图
3.NavBar 导航栏 如果开启fixed 顶部固定，希望自动给顶部撑开46px的空间，现在需要手动处理

我的微信是：cys1004；目前正在使用zanui做项目，希望能加个微信！

**Comment by chenjiahan** [comment]
1. 如果使用了 babel-plugin-import，请按需引入组件，直接引入所有组件会报错
```js
import { Button } from 'vant';
```

2. 最好提供一下截图，不然无法定位你的问题
3. 组件不应该直接修改 body 的 padding，这里建议还是手动处理
4. 欢迎加入 vant 交流群一起讨论
<img src="https://user-images.githubusercontent.com/7237365/34752336-9b33004c-f5ec-11e7-9f39-c85b7b68c021.jpeg" width="300" />
