### ISSUE TITLE
使用遮罩层（Overlay）时文档中的show字段并不能控制遮罩层的显示隐藏

### ISSUE THREAD

**Issue by ydylh** [youzan/vant#5230]
使用遮罩层（Overlay）时文档中的show字段并不能控制遮罩层的显示隐藏，但是用visible好像可以正常使用。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

如果遇到与文档不一致的情况，建议你看下你安装的 Vant 版本是否和文档一致

**Comment by Augly** [comment]
Overlay遮罩层里面的东西怎么出不来？
代码如下：
`<van-overlay :show="show" @click="show = false" :z-index="99999">
      <div class="wrapper" @click.stop slot="default">
        <div class="tanchaung">
          <div class="wrap">
            <p>恭喜你获得{{ money }}元现金红包，马上去使用优惠劵！</p>
          </div>
          <div class="button">确定</div>
        </div>
      </div>
    </van-overlay>`
遮罩层出来了，但是里面内容没有出来
