### ISSUE TITLE
下拉刷新时refresh 和 load 同时执行了？而且还会重复请求接口

### ISSUE THREAD

**Issue by Nick091608** [youzan/vant#5234]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://gather7.cn/zhhq/#/taskOut/reservation

下拉刷新的时候
我把 finished 先设置成false，再把isLoading设置成 false，然后1秒以后请求接口，请求完成以后把loading设置成false，然后数据返回空或者数据不足一页的时候把finished 设置成true，有问题吗

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by Banlangenn** [comment]
我也出现了   解决办法：

```js
onRefresh() {
      // 清空列表数据
      this.finished = false;

      // 重新加载数据
      // 将 loading 设置为 true，表示处于加载状态
      this.loading = true;
       // this.onLoad();   把这一行去掉就行了 -- 看这儿--看这儿--看这儿--看这儿
    }
