### ISSUE TITLE
[Bug Report] Dialog组件化调用在ios不显示slot内容，只显示遮罩

### ISSUE THREAD

**Issue by Cicada7year** [youzan/vant#5236]
### 设备 / 浏览器
safari

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://m1.gojoy.cn/NiceGoods?hid=13" target="_blank">https://m1.gojoy.cn/NiceGoods?hid=13</a>

### 描述问题
Dialog组件化调用在ios不显示slot内容，只显示遮罩，步骤：点击右上角规则

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by Cicada7year** [comment]
![image](https://user-images.githubusercontent.com/31717528/70517915-61409480-1b74-11ea-9ab5-df16d08cf99b.png)
![image](https://user-images.githubusercontent.com/31717528/70517933-67cf0c00-1b74-11ea-8068-08281116d035.png)
![image](https://user-images.githubusercontent.com/31717528/70517936-6ac9fc80-1b74-11ea-9938-db88b4ec78ae.png)

**Comment by Cicada7year** [comment]
> 麻烦提供一下 codesandbox 复现链接

代码里封装的东西太多，不知道怎么往上放~囧..   截图劳烦看一下

![image](https://user-images.githubusercontent.com/31717528/70518083-ac5aa780-1b74-11ea-9e95-21d13f154ff4.png)
![image](https://user-images.githubusercontent.com/31717528/70518099-b8df0000-1b74-11ea-9760-d9da239171dc.png)

**Comment by chenjiahan** [comment]
代码看起来没啥问题，我在 iOS 上试了也是正常打开的

建议你自行调试排查下问题

**Comment by Cicada7year** [comment]
> 代码看起来没啥问题，我在 iOS 上试了也是正常打开的
> 
> 建议你自行调试排查下问题

ios12出不来

**Comment by chenjiahan** [comment]
你可以用 iOS 的手机调试看下是否有报错
