### ISSUE TITLE
popup组件结合better-scroll无法使用

### ISSUE THREAD

**Issue by daweiyong** [youzan/vant#5238]
<div>
<van-popup
      v-model="cdyshow"
      position="bottom"
      :get-container="getContainers"
      :style="{ height: '80%' }"
    >
      <div>
        <article ref="cdyswiper" style="height:200px;overflow:hidden;">
          <div class="hhh">
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
            <p>fewofjiewffjewfwefewfewfefewfefewfewfefefewfwfewfwef</p>
          </div>
        </article>
      </div>
    </van-popup>
</div>

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
