### ISSUE TITLE
[Bug Report] upload组件上传图片显示问题

### ISSUE THREAD

**Issue by dpp050700** [youzan/vant#5239]
### 设备 / 浏览器
谷歌

### Vant 版本
2.3.0-beta.3

### Vue版本
2.6.10

### 重现链接
<a href="https://cloud.21tb.com/sf-server/file/getFile/99db491f3e04092aba9215a9be0bd000-P_1523333333333/happy/5394d76a1e104fd8bbc208e72a981d0f_0100" target="_blank">https://cloud.21tb.com/sf-server/file/getFile/99db491f3e04092aba9215a9be0bd000-P_1523333333333/happy/5394d76a1e104fd8bbc208e72a981d0f_0100</a>

### 描述问题
如果上传后获取的图片地址是不携带后缀名的， upload就不能正确显示图片，被解析成文件了（图片地址见重现链接，无后缀名可正确显示）

**Comment by chenjiahan** [comment]
如果图片 URL 中不包含类型信息，可以添加 isImage 标记来声明，文档里有注释说明

https://youzan.github.io/vant/#/zh-CN/uploader#tu-pian-yu-lan
