### ISSUE TITLE
[Bug Report] 建议van-tab添加dot属性

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#5240]
### 设备 / 浏览器
谷歌

### Vant 版本
2.3.0-beta.3

### Vue版本
2.6.10

### 重现链接
<a href="http://weishangxian无法提供连接.com" target="_blank">http://weishangxian无法提供连接.com</a>

### 描述问题
因为项目需求，需要用到该属性，所以建议van-tab添加dot属性，只是建议，具体还是根据贵平台的要求实现

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.5 版本支持
