### ISSUE TITLE
[Feature Request] 2.2分支打包报错。能更新一下lazyload版本吗？

### ISSUE THREAD

**Issue by a350021757** [youzan/vant#5241]
通过CDN方式引入vant.min.js，里面的lazyload是1.2.3版本的，无法设置图片懒加载时加载图和错误图。于是克隆了2.2分支下来，升级lazyload到最新的1.3.3版后自己打包，结果报了许多eslint的错误。去除lint后打出的包达到效果了，但是比原来的大了3倍。
所以能帮忙更新一下lazyload的版本吗？

**Comment by chenjiahan** [comment]
1.2.3 版本是支持设置图片懒加载时加载图和错误图的

升级最新版的话会导致这个问题：https://github.com/hilongjw/vue-lazyload/issues/273

所以暂时不会升级，等后续 Vant 大版本更新时再考虑升级
