### ISSUE TITLE
[Bug Report] Dialog在keep-alive的页面中，跳转路由再回退，会被隐藏

### ISSUE THREAD

**Issue by songispm** [youzan/vant#5243]
### 设备 / 浏览器
Chrome

### Vant 版本
2.3.0-beta.3

### Vue版本
2.6.10

### 重现链接
<a href="https://codepen.io/songispm/pen/yLyOvBO" target="_blank">https://codepen.io/songispm/pen/yLyOvBO</a>

### 描述问题
Dialog在keep-alive的页面中，跳转路由再回退，会被隐藏

在keep-alive的页面中，路由跳转前v-model还是true，跳转后 v-model被自动 置为false了，

用户没有主动关闭，代码也没有主动 操作 v-model的情况下，应该v-model不变化

写上close-on-popstate 为false 也没用，v-model还是 被操作了

线上代码 https://codepen.io/songispm/pen/yLyOvBO 中有注释，感谢回复!

**Comment by chenjiahan** [comment]
目前的默认行为是在 deactivated 的时候关闭弹窗，我们评估下能否调整或提供配置项

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.5 版本修复
