### ISSUE TITLE
navBar 没有提供属性来改变背景色和字体颜色？

### ISSUE THREAD

**Issue by c1nso** [youzan/vant#5245]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
直接通过 css 覆盖样式即可
