### ISSUE TITLE
[Feature Request] Divider 分割线 期望支持 vertical

### ISSUE THREAD

**Issue by zehuichan** [youzan/vant#5246]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

What problem does this feature solve?
Divider 期望支持 vertical

What does the proposed API look like?
[type] [类型default = 'horizontal'] [‘horizontal’ | ‘vertical’]

```vue
// vertical 情况下 不支持文字
<van-divider type="horizontal | vertical"/>
```

**Comment by chenjiahan** [comment]
后续会考虑支持

**Comment by chenjiahan** [comment]
评估了一下，暂时不会支持垂直的分割线，不是很有必要，建议自行实现下

**Comment by hdyusf** [comment]
want to it

**Comment by hdyusf** [comment]
期待这个功能 手机端很常用
