### ISSUE TITLE
Collapse 每次展开van-collapse-item 内容字体大小不一样

### ISSUE THREAD

**Issue by MengQingJunzz** [youzan/vant#5247]
![image](https://user-images.githubusercontent.com/30398163/70629557-1eaab500-1c65-11ea-8e0a-3ce3c67e8ac5.png)

![image](https://user-images.githubusercontent.com/30398163/70629651-4863dc00-1c65-11ea-9305-a239b9a2b549.png)

请问px转rem 会影响这个字体大小吗？使用的是postcss-pxtorem

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

> 请问px转rem 会影响这个字体大小吗

理论上不会
