### ISSUE TITLE
upload 组件上传不能限制gif上传

### ISSUE THREAD

**Issue by mia330** [youzan/vant#5248]
设备 / 移动端
ipone

Vant 版本
2.2.16

Vue版本
2.5.2

代码
![image](https://user-images.githubusercontent.com/43930791/70676823-67478a00-1cc8-11ea-8f8f-a7354452d22a.png)
pc端确实过滤掉了gif,但是手机端还是能上传gif
![image](https://user-images.githubusercontent.com/43930791/70677177-59decf80-1cc9-11ea-8b88-49bb4eed9da7.png)

![image](https://user-images.githubusercontent.com/43930791/70677136-3c116a80-1cc9-11ea-8dc2-bb9820d841da.png)

描述问题
手机端不能限制上传gif

**Comment by mia330** [comment]
![image](https://user-images.githubusercontent.com/43930791/70677376-fb662100-1cc9-11ea-86e9-9e79a5182b2d.png)

**Comment by chenjiahan** [comment]
accept 是原生属性，上传限制是由对应的系统决定的喔，Vant 这边没法限制
