### ISSUE TITLE
popup弹出层在iphoneX移动端中会出现样式问题

### ISSUE THREAD

**Issue by chaode0620** [youzan/vant#5249]
popup弹出层在iphoneX移动端中会先出现小的页面。然后在慢慢放大。
![TIM图片20191212104633](https://user-images.githubusercontent.com/31196943/70678308-abd52480-1ccc-11ea-9e0d-30dc82e81cc2.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
