### ISSUE TITLE
upload 组件上传有before-read，multiple不能同时生效

### ISSUE THREAD

**Issue by mia330** [youzan/vant#5250]
设备 ： 浏览器(Google) 和 移动端
Vant 版本
2.2.16

Vue版本
2.5.2

代码（有multiple，没有before-read的时候）
![image](https://user-images.githubusercontent.com/43930791/70678359-cc9d7a00-1ccc-11ea-8dde-fe4f670c3dd2.png)
显示
![image](https://user-images.githubusercontent.com/43930791/70678789-133fa400-1cce-11ea-9f04-00ada3de4f4f.png)
![image](https://user-images.githubusercontent.com/43930791/70678808-1b97df00-1cce-11ea-9158-f09d6e5399f2.png)

代码（有multiple和before-read的时候）
![image](https://user-images.githubusercontent.com/43930791/70678422-ff477280-1ccc-11ea-8968-fa6cc9aca2f6.png)
显示（可以选中但是点击打开的时候图片不显示到上传组件上）
![image](https://user-images.githubusercontent.com/43930791/70678856-441fd900-1cce-11ea-8b52-33def37266cf.png)

![image](https://user-images.githubusercontent.com/43930791/70678863-4d10aa80-1cce-11ea-84da-a11618ce70bb.png)

**Comment by chenjiahan** [comment]
请确认下你的 before-read 函数中返回了 true 作为返回值
