### ISSUE TITLE
[Bug Report] nuxt 中直接以引入cdn，组件报错 

### ISSUE THREAD

**Issue by wlinglinux** [youzan/vant#5251]
### 设备 / 浏览器
chrome

### Vant 版本
2.3.0-beta.3

### Vue版本
2.6.10

### 重现链接
<a href="http://jianye.hd.weibo.com/site/?id=86" target="_blank">http://jianye.hd.weibo.com/site/?id=86</a>

### 描述问题
我想在nuxt中直接引用vant.min.js，但是在编译的时候就报错了，图片如图所示：https://user-images.githubusercontent.com/286261/70413115-8e684680-1a91-11ea-9bcd-b22ecf74c070.png

**Comment by chenjiahan** [comment]
重现链接无效，图片上的报错是组件未注册，说明没有正确引入 Vant 的组件

可以参考下我们提供的 CDN 引入 Demo：https://github.com/youzan/vant-demo/blob/master/cdn/index.html
