### ISSUE TITLE
[Feature Request] 建议增加车牌选择框(常规车牌和新能源)

### ISSUE THREAD

**Issue by a953043100** [youzan/vant#5252]
### 这个功能解决了什么问题
可以快速的解决用户输入错误车牌，导致一系列的问题

### 描述您想要的解决方案
弹出自定义键盘显示车牌省份以及字母和数字

### 建议的API是什么样的
类似vant开发的数字键盘

**Comment by chenjiahan** [comment]
暂无计划支持喔
