### ISSUE TITLE
[Feature Request] 大佬，全屏 Popup 安卓机返回键返回时如何只关Popup,不后退路由

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#5253]
### 这个功能解决了什么问题
全屏 Popup 安卓机返回键返回时只关Popup,不后退路由

### 描述您想要的解决方案
全屏 Popup 安卓机返回键返回时只关Popup,不后退路由

### 建议的API是什么样的
全屏 Popup 安卓机返回键返回时只关Popup,不后退路由

**Comment by anihCevol** [comment]
我好像把自己的问题解决了:
类似  #3902，还有sku图片预览，点击安卓返回键时， 是不是都可以在beforeRouteLeave 里面加判断这种方式去处理：有popup时，就先关闭popup,然后next(false)；没有popup就next()。这样合理吗

**Comment by chenjiahan** [comment]
看起来没啥问题

**Comment by anihCevol** [comment]
那就先这样整，应该没问题。
