### ISSUE TITLE
[Bug Report] tabs内部列表页滚动后，点击进入详情，然后返回总是回顶部

### ISSUE THREAD

**Issue by linsywu** [youzan/vant#5254]
### 设备 / 浏览器
chorme

### Vant 版本
2.2.12

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-ypuj3?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-ypuj3?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
再keep-alive缓存页面的情况下，全屏滚动的list在进入详情页后返回list页面，是可以保持之前的滚动位置的；
但是tab内部滚动域的list在进入详情页面返回的时候，总是回到顶部；
有什么好的解决办法？

**Comment by JakeLaoyu** [comment]
可以保存滚动位置，返回的时候处理一下
