### ISSUE TITLE
关于List上拉加载的问题

### ISSUE THREAD

**Issue by anjina** [youzan/vant#5259]
现在的List加载组件，如果设置了immediate-check为false，只能在第一次不触发自动加载，
如果存在tab标签栏，点了其他的tab，还是会自动请求，而且如果第一次请求数据为空，第二次再触发这个tab的点击，又不请求了。。。为什么不是只要当前的tab数据为空，就会自动请求呢？
不然只请求一次 在有些场景下很难满足。

**Comment by chenjiahan** [comment]
List 组件是不关心外部 Tab 数据的，你可以手动调用 check 方法来执行加载判断
