### ISSUE TITLE
 关于上传组件的一些功能扩展

### ISSUE THREAD

**Issue by de1ck** [youzan/vant#526]
1. 显示|清空 上传列表
2. 限制文件大小
3. 上传的地址 | 上传文件的钩子
。。。等等
现在这些都得自己手写去集成，希望官方可以提供一个完善的功能。

**Comment by chenjiahan** [comment]
感谢反馈，我们会在后续完善 uploader 组件

**Comment by chenjiahan** [comment]
已在 0.12.6 版本中支持 maxSize 属性去限制文件大小，显示上传列表和 ajax 上传暂时不准备在 uploader 中加入，推荐在 afterRead 后根据具体需求去实现
