### ISSUE TITLE
[Bug Report] 官网示例看不到了

### ISSUE THREAD

**Issue by qimiaojiyihou** [youzan/vant#5260]
### 设备 / 浏览器
谷歌

### Vant 版本
2.3.0-beta.3

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/dropdown-menu" target="_blank">https://youzan.github.io/vant/#/zh-CN/dropdown-menu</a>

### 描述问题
所有组件的示例都看不到了

**Comment by croson** [comment]
源码down下来run dev 也都是报错

**Comment by chenjiahan** [comment]
刚才在升级官网，有几分钟短暂的不可用

> 源码down下来run dev 也都是报错

源码下载后需要 yarn 一下
