### ISSUE TITLE
[Bug Report] Dialog 在关闭过程中快速点击，导致 beforeClose 重复触发

### ISSUE THREAD

**Issue by funnyPan** [youzan/vant#5263]
demo地址：https://codesandbox.io/s/eager-burnell-hur87

弹窗异步，点击一次确认后，再连续多次点击，会执行两次console.log，输出两个123

**Comment by chenjiahan** [comment]
提供的链接里未复现此问题

**Comment by funnyPan** [comment]
[屏幕录制2019-12-13下午2.55.32.mov.zip](https://github.com/youzan/vant/files/3959422/2019-12-13.2.55.32.mov.zip)
@chenjiahan

**Comment by funnyPan** [comment]
![demo](https://user-images.githubusercontent.com/12791216/70776976-8eca4f80-1db9-11ea-9e0e-a05e768af9d9.gif)

**Comment by chenjiahan** [comment]
明白了，在动画过程中快速点击，确实有可能触发第二次 beforeClose，下个版本会修复下

**Comment by funnyPan** [comment]
> 明白了，在动画过程中快速点击，确实有可能触发第二次 beforeClose，下个版本会修复下

能否提供解决办法？比较紧急的状况

**Comment by chenjiahan** [comment]
一会儿会发版

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.4 版本修复
