### ISSUE TITLE
[Feature Request] 希望tabs组件支持电梯模式

### ISSUE THREAD

**Issue by rzhang228** [youzan/vant#5264]
### 这个功能解决了什么问题
支持另一种tabs的交互形式

### 描述您想要的解决方案
具体还没想好

### 建议的API是什么样的
增加一个电梯模式的props  （elevator）
和sticky是两种能力，可以一起用，也可以分开用，正常都是一起用

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.5 版本支持
