### ISSUE TITLE
uniapp+vant写小程序使用tabs组件时，发现两个问题，第一绑定当前选中的标签页不生效，第二设置title文字过长省略显示为false也不生效

### ISSUE THREAD

**Issue by littleBelle** [youzan/vant#5265]
![image](https://user-images.githubusercontent.com/53242999/70776383-e2d43480-1db7-11ea-9ade-bc2cb65b6143.png)

![image](https://user-images.githubusercontent.com/53242999/70776413-f5e70480-1db7-11ea-8b96-45256e4409fa.png)
![image](https://user-images.githubusercontent.com/53242999/70776433-05664d80-1db8-11ea-9bd9-04c3b010e3c3.png)

**Comment by littleBelle** [comment]
麻烦指点一下怎么用，多谢

**Comment by chenjiahan** [comment]
小程序问题请到 vant-weapp 仓库下按照模板提问，感谢配合
