### ISSUE TITLE
[Bug Report] tabs 添加 animated属性后 tab中的DropdownMenu 只在第一个tab起作用

### ISSUE THREAD

**Issue by 267028826** [youzan/vant#5268]
### 设备 / 浏览器
chrome

### Vant 版本
2.1.7

### Vue版本
2.5.20

### 重现链接
<a href="https://codesandbox.io/s/busy-lumiere-94z16" target="_blank">https://codesandbox.io/s/busy-lumiere-94z16</a>

### 描述问题
tabs 添加 animated属性后 tab中的DropdownMenu 只在第一个tab起作用，在其它的tab下不起作用

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4400
