### ISSUE TITLE
These relative modules were not found

### ISSUE THREAD

**Issue by maria028** [youzan/vant#5269]
![image](https://user-images.githubusercontent.com/30227386/70788998-18cfe380-1dcd-11ea-98a5-0a47f44d8816.png)
这个问题是怎么回事？之前一直只引入了组件样式不生效，改着改着就这样了，重新安装依赖也不行

**Comment by maria028** [comment]
这个问题解决了，但css样式仍然失效

**Comment by JakeLaoyu** [comment]
babel-plugin-import 配置看一下

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
