### ISSUE TITLE
toast switch dialog 组件按需引入时报错

### ISSUE THREAD

**Issue by magicstf** [youzan/vant#5270]
import { Toast, Switch, Dialog } from 'vant';

Vue.use(Switch);
Vue.use(Dialog);
Vue.use(Toast);

控制台错误：

throw new Error(`Cannot map to variable name in module ${info.module.resource} (export '${exportName}')`);
						^

Error: Cannot map to variable name in module /Users/sutengfei/workspace/hotel-eb-app-vue/node_modules/vant/es/image/index.js (export 'default')

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合///////
