### ISSUE TITLE
textarea 设置了autosize 但是无法自适应高度，只能滚动条滚动。

### ISSUE THREAD

**Issue by Jason1213812138** [youzan/vant#5271]
配置如下：<van-field
                v-model="message"
                rows="1"
                :autosize="{maxHeight: 100, minHeight: 50}"
                label="留言"
                type="textarea"
                placeholder="请输入留言"
            />

**Comment by Jason1213812138** [comment]
配置如下：<van-field
                v-model="message"
                rows="1"
                :autosize="{maxHeight: 100, minHeight: 50}"
                label="留言"
                type="textarea"
                placeholder="请输入留言"
            />

**Comment by Jason1213812138** [comment]
<van-field
                v-model="message"
                rows="1"
                :autosize="{maxHeight: 100, minHeight: 50}"
                label="留言"
                type="textarea"
                placeholder="请输入留言"
            />

**Comment by Jason1213812138** [comment]
<van-field
  v-model="message"
                rows="1"
                :autosize="{maxHeight: 100, minHeight: 50}"
                label="留言"
                type="textarea"
                placeholder="请输入留言"
            />

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
