### ISSUE TITLE
[Bug Report] uploader组件上传图片缩略图旋转90°

### ISSUE THREAD

**Issue by 17639775152** [youzan/vant#5275]
### 设备 / 浏览器
微信公众号内置浏览器

### Vant 版本
2.3.0-beta.4

### Vue版本
2.6.11

### 重现链接
<a href="https://www.baidu.com" target="_blank">https://www.baidu.com</a>

### 描述问题
当使用uploader组件上传照片的时候,如果直接用相机拍照,拍完照片之后,部分手机生成的缩略图会旋转90°的情况,目前发现的机型 小米6; 这个重现的时候相当容易,不需要链接说明了,用小米6的手机调一下 上传照片,采用拍照的功能即可重现;

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/2332
