### ISSUE TITLE
[Bug Report] tab 组件的title无法ssr

### ISSUE THREAD

**Issue by powerlau** [youzan/vant#5278]
tab 组件的title无法ssr，而导致tab组件只会客户端渲染，当页面加载完成以后tab会从无到有一闪，用户体验变差。
代码如下：
     ` <van-tabs v-model="activeIndex" title-active-color="#333" :lazy-render="false">
        <van-tab title="选项1">内容1</van-tab>
        <van-tab title="选项2">内容2</van-tab>
        <van-tab title="选项3">内容3</van-tab>
        <van-tab title=“选项4”>内容4</van-tab>
      </van-tabs>`
通过设置lazy-render="false"的确可以做到内容部分ssr，但是title依然无法ssr，查看源码依然看不到title从服务端渲染出来。
服务端渲染出来的对应html为：
`<div class="van-tabs van-tabs--line"><div class="van-tabs__wrap van-hairline--top-bottom"><div role="tablist" class="van-tabs__nav van-tabs__nav--line"><div class="van-tabs__line"></div></div></div><div class="van-tabs__content"><div role="tabpanel" class="van-tab__pane" style="display:none;">内容1</div> <div role="tabpanel" class="van-tab__pane" style="display:none;">内容2</div> <div role="tabpanel" class="van-tab__pane" style="display:none;">内容3</div> <div role="tabpanel" class="van-tab__pane" style="display:none;">内容4</div></div></div></div></div></div>`
可以看到内容的确渲染出来了，title没有渲染出来。
@chenjiahan

**Comment by chenjiahan** [comment]
后续会看下能否优化

**Comment by chenjiahan** [comment]
Tab 组件的标题是从子组件获取的，在子组件挂载后才能取到 title 内容。在 SSR 的时候这个过程还未完成，因此无法渲染出标题。目前没发现合适的解决方案，建议增加占位内容或骨架屏来避免这个问题

**Comment by superche** [comment]
请问这个问题现在有解决方案吗？

**Comment by codeblockhead** [comment]
这个问题为什么不管了，明显是影响到使用的问题啊

**Comment by chenjiahan** [comment]
目前没有精力处理该问题，感兴趣的话欢迎贡献 PR

**Comment by gaoxiao6331** [comment]
能不能在官网加一个提示，tab不兼容SSR🤣
