### ISSUE TITLE
van-datetime-picker 日期选择面板无法直接定位到给定的日期

### ISSUE THREAD

**Issue by eMillet** [youzan/vant#5279]
你好，使用日期选择器组建时，设置类型type = “ date ", 给出 v-model = ” currentDate “， 且currentDate = new Date().toLocaleDateString();
 为什么无法在日期选择面板直接定位到给定的日期呢 ？是我的使用方式不对嘛 ？？
```
<van-datetime-picker type="date"
                           v-model="currentDate"
                           @confirm="confirmDate"
                           @cancel="cancelDate" />
```

**Comment by chenjiahan** [comment]
v-model 绑定的是 Date 对象，不是 string，需要把 toLocaleDateString() 去掉
