### ISSUE TITLE
Lazyload did you register the component correctly

### ISSUE THREAD

**Issue by a251115100** [youzan/vant#528]
use 
import {Lazyload,} from 'vant'
<lazy-component>
     <img v-lazy="posterPath"/>
</lazy-component>
Unknown custom element: <lazy-component> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by chenjiahan** [comment]
please provide more information

**Comment by a251115100** [comment]
已修复 
我用Vue.use(Lazyload)报错了
改成
Vue.use(Lazyload, {
  lazyComponent: true
})
就好了

**Comment by chenjiahan** [comment]
👌

**Comment by liguob666** [comment]
我也遇到同样的问题，谢谢 a251115100  的方案
