### ISSUE TITLE
[Bug Report] 购物车中van-checkbox-group中嵌套van-card中footerslot中加入Stepper 组件，当点击加减或者手动输入的时候，会冒泡导致checkbox来回选中

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#5280]
### 设备 / 浏览器
ios

### Vant 版本
2.3.0-beta.4

### Vue版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/stepper" target="_blank">https://youzan.github.io/vant/#/zh-CN/stepper</a>

### 描述问题
购物车中van-checkbox-group中嵌套van-card中footerslot中加入Stepper 组件，当点击加减或者手动输入的时候，会冒泡导致checkbox来回选中，希望在Stepper 加入一个属性，使事件不冒泡
![image](https://user-images.githubusercontent.com/21211777/70887263-6e4c0080-2018-11ea-80aa-57750ca52dfe.png)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4016
