### ISSUE TITLE
[Bug Report] van-tabs组件的animated属性在ios系统无过度动画

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#5281]
### 设备 / 浏览器
谷歌

### Vant 版本
2.3.0-beta.4

### Vue版本
2.6.11

### 重现链接
<a href="http://weishangxian无法提供连接.com" target="_blank">http://weishangxian无法提供连接.com</a>

### 描述问题
van-tabs组件的animated属性在ios系统滑动没有过度动画，而是直接切换的。

**Comment by chenjiahan** [comment]
用 iOS 手机试了一下没有问题，建议排查下是否是其他原因导致的

**Comment by lmfuture** [comment]
https://doc.baoxianxia.com.cn/1576490873161931.mp4

**Comment by lmfuture** [comment]
@chenjiahan 在安卓手机上是正常的，切滑动有中间过度动画，但是在ios手机上试了一下官方插件同样是没有过度动画，是直接切换的

**Comment by lmfuture** [comment]
@chenjiahan 这是在浏览器上，也是有这个过渡动画的，应该和用法没有关系，因为安卓也是可以的，是不是css3在ios浏览器内核上兼容性的问题。https://doc.baoxianxia.com.cn/1576491495266934.mp4

**Comment by lmfuture** [comment]
@chenjiahan 刚才试了下同事的iphone8,是有效果的，我的是iphone6P没有效果，可能跟版本有关系吧

**Comment by chenjiahan** [comment]
可以重启微信进程试下，微信里偶尔会出现 css 动画不生效的情况

**Comment by lmfuture** [comment]
@chenjiahan 好的，谢谢解答，昨晚更新了一下系统可以了，可能重启一下微信也是可以的，打扰了！啧啧
