### ISSUE TITLE
IndexBar 索引栏问题 -- 一直抖动, 无法下拉到底

### ISSUE THREAD

**Issue by PhoenixSlade** [youzan/vant#5282]
使用indexbar， 文档地址: https://youzan.github.io/vant/#/zh-CN/index-bar, 出现问题如下: 
1. 如果是最后一页，则无法点击到索引栏最后一个或多个。
2. 当数据过少时候, 用**手机端****微信公众号**上打开页面(**google chrome**和**微信web开发者工具**是正常的), 滚动到底部时一直住上拉, 无法下拉到底部
请尽快解决此问题, 谢谢~

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by shen-lan** [comment]
我的老哥  无法点击最后一个你怎么解决的 ？

**Comment by towry** [comment]
自定义cell和anchor的padding（增加）后，index list的高亮就会显示错误（应该显示B的，但是会显示A，但是列表和index是对照没问题的）。
