### ISSUE TITLE
[Feature Request] checkbox-group ,toggleAll() 数据量大，全选和取消全选中过程慢

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#5284]
### 这个功能解决了什么问题
checkbox toggleAll() 数据量大，全选和取消全选中过程慢:
```
<van-checkbox-group v-model="result" ref="checkboxGroup">
  <van-checkbox  :name="item" v-for="item in 100" :key="item">复选框 a</van-checkbox>
</van-checkbox-group>
```
拿文档例子，显示100个checkbox，进行全选和取消全选操作，尝试结果大概3s到5s才执行完成。

### 描述您想要的解决方案
暂无。

### 建议的API是什么样的
checkbox toggleAll() 数据量大时，缩短执行时间

**Comment by chenjiahan** [comment]
确实有这个问题，下个版本会优化下

**Comment by chenjiahan** [comment]
已在 2.3.0-beta.5 版本优化
