### ISSUE TITLE
DropdownMenu 下拉菜单，奇怪问题，在线等，

### ISSUE THREAD

**Issue by wanlinandkunping** [youzan/vant#5288]
问题描述：DropdownMenu 下拉菜单，刷新和第一次打开，设置了两个，或者三个目录，默认显示一个栏目，需要点击一次，才能全部显示出来。用的cdn引用，官方例子复制下来，使用都有问题。是bug吗？
![QQ截图20191217133444](https://user-images.githubusercontent.com/32283249/70967792-5933a800-20d2-11ea-8704-60bc97aecddb.png)
![QQ截图20191217133407](https://user-images.githubusercontent.com/32283249/70967794-59cc3e80-20d2-11ea-8940-79d07b199fea.png)

![1](https://user-images.githubusercontent.com/32283249/70967648-ca269000-20d1-11ea-83ad-861ce1d40bd5.gif)

功能链接：https://youzan.github.io/vant/?source=vuejsorg#/zh-CN/dropdown-menu#xiang-shang-zhan-kai

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by baiyis** [comment]
![image](https://user-images.githubusercontent.com/43742597/123741678-0b117e80-d8dd-11eb-910f-e822fa2b7dbe.png)
![image](https://user-images.githubusercontent.com/43742597/123741748-22e90280-d8dd-11eb-9864-c875cfdc1dd7.png)
