### ISSUE TITLE
想知道 2.3 正式版什么时候会上线，

### ISSUE THREAD

**Issue by liu983074833** [youzan/vant#5289]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by lmfuture** [comment]
+1

**Comment by chenjiahan** [comment]
这个月内会上线
