### ISSUE TITLE
样式覆盖不生效的问题 和 AddressEdit 组件中的小问题

### ISSUE THREAD

**Issue by HangCheung** [youzan/vant#529]
找到 Vant 源码中的类名，写了一个同类名的样式进行覆盖，更改后，只有在 Tabbar 的样式生效了，SubmitBar 和 AddressEdit 的样式不生效。另外，在 AddressEdit 组件中，参数 show-postal 和 show-set-default 的默认值为 true ，文档中为 false 。

**Comment by chenjiahan** [comment]
1. 样式覆盖是可以生效的，请注意你的样式引入顺序及选择器优先级
2. show-postal 和 show-set-default 的默认值是 false，如果出现和文档不符的情况，建议升级 vant 版本再试

**Comment by HangCheung** [comment]
好的，谢谢~ @chenjiahan
