### ISSUE TITLE
[Bug Report] Swipe 轮播

### ISSUE THREAD

**Issue by 2587593709** [youzan/vant#5290]
### 设备 / 浏览器
ios

### Vant 版本
2.3.0-beta.4

### Vue版本
2.6.11

### 重现链接
<a href="https://9u4ez.csb.app/" target="_blank">https://9u4ez.csb.app/</a>

### 描述问题
图片轮播时外层div设置的border-radius:10px;overflow:hidden;图片会变成正方形后又变圆角这个奇怪效果，只有在ios设备上才会这样，安卓正常。

**Comment by JakeLaoyu** [comment]
Safari border-radius + overflow: hidden + CSS transform 会导致圆角失效

**Comment by 2587593709** [comment]
谢谢
