### ISSUE TITLE
Popup 弹出层有bug，设置它的z-index为undefined

### ISSUE THREAD

**Issue by 3182779524qq** [youzan/vant#5291]
![image](https://user-images.githubusercontent.com/43661281/70969612-2a6c0080-20d7-11ea-92ad-5291397012d3.png)
![image](https://user-images.githubusercontent.com/43661281/70969639-39eb4980-20d7-11ea-9556-3fc26d205f4f.png)
Popup 弹出层有bug，设置他的z-index为undefined
<van-popup v-model="show">内容</van-popup>

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by gary123123** [comment]
> 请按照模板创建 issue，感谢配合

我也遇到同样的问题，就是按照官网的模板配的，版本是beta3，请核实一下

**Comment by impacnHo** [comment]
你好, 请问有什么解决方案吗?
