### ISSUE TITLE
popup 2.2.14版本可以正常使用，但是2.3.0不能使用

### ISSUE THREAD

**Issue by gary123123** [youzan/vant#5292]
popup 2.2.14版本可以正常使用，但是2.3.0-beta版本不能使用

**Comment by 3182779524qq** [comment]
谢谢

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by gary123123** [comment]
> 请按照模板创建 issue，感谢配合

我是按模板创建的，代码是同一套代码，我切换2.2.16版本，popup就能正常运行，切换到2.3.0之后，popup就不能用了，写法就是按照官方文档的写法

**Comment by chenjiahan** [comment]
麻烦提供下 codesandbox 复现链接

**Comment by FuYiCai** [comment]
**2020年1月8号，下面两个插件照demo不能用，其他的demo引用正常；咋改呀？**
<van-popup v-model="show">内容</van-popup> 这个插件不能用啦，还有<van-radio-group v-model="radio">
  <van-radio name="1">单选框 1</van-radio>
  <van-radio name="2">单选框 2</van-radio>
</van-radio-group>
