### ISSUE TITLE
[Bug Report] van-tab  sticky 属性，控制台报错了，但是功能正常

### ISSUE THREAD

**Issue by Farb** [youzan/vant#5295]
### 设备 / 浏览器
Chrome 版本 79.0.3945.79（正式版本） （64 位）

### Vant 版本
2.3.0-beta.4

### Vue版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-8mcgo?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-8mcgo?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
Vue版本 v 2.9.6
van-tab  sticky 属性，控制台报错了，但是功能正常

![image](https://user-images.githubusercontent.com/7587900/70981707-9dce3c00-20f0-11ea-92d9-3e39c5f9e3a5.png)

**Comment by chenjiahan** [comment]
提示的已经很明显了，传参类型应该为 boolean 类型

**Comment by Farb** [comment]
sticky="true" 这样传参不行吗？ @chenjiahan  😆

**Comment by chenjiahan** [comment]
前面加个冒号

**Comment by Farb** [comment]
Thanks a lot!
