### ISSUE TITLE
[Bug Report] 请问2.3.0正式版发布之后，2.3.0-beta.5还可以使用么

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#5296]
### 设备 / 浏览器
谷歌

### Vant 版本
2.3.0-beta.4

### Vue版本
2.6.11

### 重现链接
<a href="http://weishangxian无法提供连接.com" target="_blank">http://weishangxian无法提供连接.com</a>

### 描述问题
请问2.3.0正式版发布之后，2.3.0-bate.5还可以使用么

**Comment by chenjiahan** [comment]
可以的喔
