### ISSUE TITLE
[Bug Report] 图片预览

### ISSUE THREAD

**Issue by ILomoXin** [youzan/vant#5297]
### 设备 / 浏览器
pc android chrome 

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-6bxs6" target="_blank">https://codesandbox.io/s/vant-issue-moban-6bxs6</a>

### 描述问题
我想用自定义组件将ImagePreview封装一层，这样可以添加其他自定义组件，以便更好的在我的项目中使用。
在示例中我在自定义组件vantPreview1.vue添加header，content，footer，ImagePreview位于content中，这样图片预览时指定预览指定位置无效，在自定义组件vantPreview2.vue中，不添加header，footer，只添加content，ImagePreview位于content中，图片预览时指定预览指定位置正常，但这样我就无法达到添加自定义header，footer的目的.

**Comment by JakeLaoyu** [comment]
是你的 header 绝对定位覆盖到了 content

**Comment by JakeLaoyu** [comment]
看起来是组件渲染问题，可以 使用 `$nextTick` 规避

https://codesandbox.io/s/vant-issue-moban-y4jqy

**Comment by ILomoXin** [comment]
> 看起来是组件渲染问题，可以 使用 `$nextTick` 规避
> 
> https://codesandbox.io/s/vant-issue-moban-y4jqy

我通过设置自定义组件v-if指令为传入的props值show来控制整组件，并在computed创建一个showPreview，showPreview的值由show取得，并在你设置$nextTick的位置只设置index=start解决了我的问题，目前在我的项目中使用正常。
https://codesandbox.io/s/vant-issue-moban-6bxs6
