### ISSUE TITLE
[Feature Request] 现有sku组件是否支持：不设置总库存，不设置条码对应的库存。

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#5298]
### 这个功能解决了什么问题
现有sku组件是否支持：不设置总库存，不设置条码对应的库存，来实现可以选择规格和增减数量。需求基本的意思是：不限制购买数量，之前项目里商品数据，没有库存和规格，后来新加的规格设置，但要求，不限制库存。

### 描述您想要的解决方案
暂无

### 建议的API是什么样的
暂无

**Comment by chenjiahan** [comment]
没太理解，应该不会支持
