### ISSUE TITLE
[Feature Request] 建议布局中增加一个最大宽度的设置

### ISSUE THREAD

**Issue by agentwx** [youzan/vant#5299]
### 这个功能解决了什么问题
经常分享的链接在pc端打开后，铺满了整个屏幕，体验非常的不好。增加一个最大的宽度后，即使用pc的浏览器打开，也是现实的移动端的宽度，体验会比较好。

### 描述您想要的解决方案
在app.vue的，增加一个vant-layout的标签，默认有一个最大的宽度, nav-bar, tab-bar之类都会根据这个标签来自适应最大宽度

### 建议的API是什么样的
提供一个vant-layout标签

**Comment by chenjiahan** [comment]
暂无计划提供这样的组件呢，建议自行通过  来处理
