### ISSUE TITLE
van-datetime-picker confirm返回值不对

### ISSUE THREAD

**Issue by zlyinfo** [youzan/vant#530]
1.van-datetime-picker confirm返回值不对
示例地址：https://jsfiddle.net/zlyinfo/zgotzwzq/
2.Area 省市县选择组件 联动有问题
示例地址： 你们官网的例子好像就有问题https://www.youzanyun.com/zanui/vant/examples#/zh-CN/component/area

**Comment by chenjiahan** [comment]
1. DatetimePicker 在 datetime 和 date 模式下 confirm 事件返回的是一个 Date 对象，可以通过 Date 对象获取时间
2. 目前 Picker 点击选项时存在 bug，下个版本会修复

**Comment by zlyinfo** [comment]
好的，了解，麻烦了
