### ISSUE TITLE
引入Filed组件，css编译报错

### ISSUE THREAD

**Issue by hardmanhong** [youzan/vant#5302]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.9

### Vue版本
2.6.10

### 描述问题
引入Filed组件，css编译报错

### 解决
引入Filed组件，css编译报错，经过自己 调试，去掉下面代码编译通过
```
// field/index.css
...
.van-field--error .van-field__control::placeholder{
    color:#ee0a24;
    -webkit-text-fill-color:#ee0a24
}
...
```
PS:vue2.6版本导致的事件无法触发就只能降级版本解决吗？

**Comment by chenjiahan** [comment]
> 引入Filed组件，css编译报错

这个语法是没问题的，建议你看下是什么编译工具报错了

> vue2.6版本导致的事件无法触发就只能降级版本解决吗？

这个问题目前只能通过降级解决，后续我们看下是否要去掉事件冒泡来避免这个问题（会有一定性能开销）
