### ISSUE TITLE
[Feature Request] 类似原生input的datalist功能的组件和picker支持多选

### ISSUE THREAD

**Issue by WytheChan** [youzan/vant#5303]
这个功能解决了什么问题
在搜索框输入时datalist可以快速筛选出自己想要填写的值。 picker组件替代的是原生的select选择器功能，原生的支持多选，做为替代的picker为什么不可以呢

描述您想要的解决方案
datalist 功能可以作为搜索框组件的延展，或者参考element-ui，与select选择器结合在一起

建议的API是什么样的
搜索框组件增加属性 datalist来开启此功能，传入一个data 数组。

piceker组件增加multiple 属性来开启是否多选。

**Comment by chenjiahan** [comment]
Picker 和 Select 在交互上还是有一些区别的，我们目前没有计划在 Picker 内支持多选和筛选，sorry

**Comment by WytheChan** [comment]
感谢回答！
那Search 搜索组件可以加上类似原生input的datalist功能吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 下午5:25
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"嘎嘎 →_→"<976509300@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] 类似原生input的datalist功能的组件和picker支持多选 (#5303)




Picker 和 Select 在交互上还是有一些区别的，我们目前没有计划在 Picker 内支持多选和筛选，sorry

**Comment by chenjiahan** [comment]
也木有计划呢
