### ISSUE TITLE
[Feature Request] 监听物理返回键

### ISSUE THREAD

**Issue by littlesalt** [youzan/vant#5304]
### 这个功能解决了什么问题
有页面A和页面B,从A可到B，B有递归调用的业务，如文档管理，点击文件夹查看下层文件，此时应返回到B的上层，但物理返回键会返回到A。如果可以监听的返回键，可以自定义是否返回到A.

### 描述您想要的解决方案
类似于vue-awesome-mui

### 建议的API是什么样的
类似于vue-awesome-mui
`this.$mui.back = () => {
		//this.$router.go(-1);
};`

**Comment by chenjiahan** [comment]
暂无计划支持喔，这个功能和组件库关系不大
