### ISSUE TITLE
[Bug Report] DropdownMenu弹出层滑动问题

### ISSUE THREAD

**Issue by irockyan** [youzan/vant#5305]
### 设备 / 浏览器
*

### Vant 版本
2.2.16

### Vue版本
2.6.11

### 重现链接
<a href="https://utjqj.csb.app/" target="_blank">https://codesandbox.io/s/vant-issue-moban-utjqj</a>

### 描述问题
下拉菜单增加粘性布局，然后点击菜单，滑动菜单上边的其他内容，则菜单选项弹出层位置固定，菜单标题跟随滚动条滚动

**Comment by chenjiahan** [comment]
下个版本会修复此问题
