### ISSUE TITLE
[Feature Request]  DatetimePicker  时间控件能否支持秒

### ISSUE THREAD

**Issue by hezhico** [youzan/vant#5308]
这个功能解决了什么问题
时间控件支持秒

描述您想要的解决方案
商户交易有精确到秒的查询

建议的API是什么样的
这个直接原有column内置，或者提供一个扩展的api也行，毕竟秒列表不需要联动

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4259
