### ISSUE TITLE
[Bug Report] 请教下card组件如何使用图片懒加载

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#5309]
### 设备 / 浏览器
ios

### Vant 版本
2.3.0-beta.5

### Vue版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/" target="_blank">https://youzan.github.io/vant/#/zh-CN/</a>

### 描述问题
lazy-load这个设置为true，然后thumb的图片连接正常填写就行了嘛
Vue.use(Lazyload, {
  error: "https://img.yzcdn.cn/vant/t-thirt.jpg",
  loading: "https://img.yzcdn.cn/vant/t-thirt.jpg"
})

**Comment by Thlq** [comment]
有代码片段参考下嘛

**Comment by chenjiahan** [comment]
上面的用法是正确的，没有问题
