### ISSUE TITLE
[Feature Request] TreeSelect 组件在命名slot中如何获取传递过来的值

### ISSUE THREAD

**Issue by iamcoderloser** [youzan/vant#5314]
### 这个功能解决了什么问题
如果无法获取传递过来的值   这个命名就没有实际用途

### 描述您想要的解决方案
通过slot-scope

### 建议的API是什么样的
通过slot-scope

**Comment by chenjiahan** [comment]
需要传递什么值喔？

**Comment by iamcoderloser** [comment]
在我使用treeselect的时候，右侧的选择项的样式无法满足需求，于是我使用了slot定制我的样式，但是我还需要获取到原本传递给你们默认选项上的那些数据。由于你们文档上没有说明提供了slot-scope这个属性，所以我不知道是没有这个功能
&nbsp;&nbsp;


另外我觉得这个控件的灵活度还是太小，如果左右两边的都可以使用slot定制，那这个控件的使用范围将会变得大一些。（当然这个只是我个人的意见）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午5:53
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"受伤的人"<642872728@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] TreeSelect 组件在命名slot中如何获取传递过来的值 (#5314)




需要传递什么值喔？

**Comment by chenjiahan** [comment]
由于数据是开发者传入的，所以组件内部没必要再把数据传出来，因为开发者可以直接通过 this. items [this.activeIndex].children 获取到

至于左边的 slot，目前还没有计划支持喔

**Comment by iamcoderloser** [comment]
谢谢你的解答!!!&nbsp; &nbsp;是我理解错了你们的数据结构的意图，我以为右边的选择的是通过组件内部通过v-for一样的方式来实现列表的渲染的,而你们将右边的作为一个整体的slot来实现自定义的功能的&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 晚上9:03
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"受伤的人"<642872728@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] TreeSelect 组件在命名slot中如何获取传递过来的值 (#5314)




由于数据是开发者传入的，所以组件内部没必要再把数据传出来，因为开发者可以直接通过 this. items [this.activeIndex].children 获取到
 
至于左边的 slot，目前还没有计划支持喔

**Comment by chenjiahan** [comment]
嗯嗯，是这样的
