### ISSUE TITLE
[Feature Request] Uploader 文件上传 max-size 提示

### ISSUE THREAD

**Issue by cn-zx** [youzan/vant#5317]
### 这个功能解决了什么问题
Uploader 文件上传 设置了max-size的值, 在图片的size大于max-size时没有提示吗?

### 描述您想要的解决方案
上传图片size大于max-size时, 弹窗提示图片过大

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
过大时会抛出 oversize 事件，可以在事件的回调函数里进行提示喔
