### ISSUE TITLE
[Feature Request] SwipeCell 滑动单元格关闭时触发的问题

### ISSUE THREAD

**Issue by cactus-yan** [youzan/vant#5319]
### 这个功能解决了什么问题
可以监听到SwipeCell 滑动单元格关闭时触发的操作

### 描述您想要的解决方案
希望增加SwipeCell 滑动单元格关闭时触发的方法，谢谢！

### 建议的API是什么样的
能否在SwipeCell上加一个关闭时触发的方法

**Comment by chenjiahan** [comment]
后续会加上

**Comment by cactus-yan** [comment]
> 后续会加上

好的。谢谢！

**Comment by chenjiahan** [comment]
已在 2.3.0 版本支持
