### ISSUE TITLE
[Feature Request] Field控件是否支持toggle-group-button的展示效果

### ISSUE THREAD

**Issue by yangshuyi** [youzan/vant#5326]
### 这个功能解决了什么问题
功能类似radiobox或checkbox。
表现效果是 如果有3个选项，则展示3个横向排列的button，用户可单选或多选，选中的button高亮展示。

类似：“选择要提交 issue 的库” 的输入框

### 描述您想要的解决方案
功能类似radiobox或checkbox。
表现效果是 如果有3个选项，则展示3个横向排列的button，用户可单选或多选，选中的button高亮展示。

类似：“选择要提交 issue 的库” 的输入框

### 建议的API是什么样的
功能类似radiobox或checkbox。
表现效果是 如果有3个选项，则展示3个横向排列的button，用户可单选或多选，选中的button高亮展示。

类似：“选择要提交 issue 的库” 的输入框

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议组合 Field 和其他组件来实现这个功能
