### ISSUE TITLE
[Feature Request] 可拖拽的图形验证码业务组件

### ISSUE THREAD

**Issue by WytheChan** [youzan/vant#5328]
### 这个功能解决了什么问题
验证账号登录，替代单纯的字母或数字的验证码

### 描述您想要的解决方案
拖拽一个方块到底，或者一块拼图到合适的位置

### 建议的API是什么样的
单独引入一个业务组件

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议去社区看下是否有类似的组件

**Comment by wangjia2016** [comment]
这个需求量还蛮大的
