### ISSUE TITLE
[Bug Report] countdown组件在finish中重置count导致循环

### ISSUE THREAD

**Issue by xiamivm** [youzan/vant#5330]
### 设备 / 浏览器
chrome -79.0.3945.79

### Vant 版本
2.3.0

### Vue版本
2.6.11

### 重现链接
<a href="https://codepen.io/xiamivm/pen/vYExeoW?editors=1011" target="_blank">https://codepen.io/xiamivm/pen/vYExeoW?editors=1011</a>

### 描述问题

在countdown组件的finish回调事件中重置count（调用countDown.reset()）。

组件在【microTick/macroTick】中因为【remain】 被重置为新的值 不等于 0 导致循环

虽然可以在父组件中用一个新的data来绕过该问题，但个人觉得在countdown组件内部修改更合理(外加官网文档中【countdown组件页面--手动控制--methdos: finish】 与上文 template中的不一致 少了 【ed】)

可用的建议：
----------------------old-------------------------------------------------------------------------------
microTick() {
//....
if (this.remain !== 0) {
          this.microTick();
        }
},

macroTick() {
//....
if (this.remain !== 0) {
          this.macroTick();
        }
}
-------------------new--------------------------------------------------------------------------------

microTick() {
//....
if (this.remain !== 0 && this.counting) {
          this.microTick();
        }
},

macroTick() {
//....
if (this.remain !== 0 && this.counting) {
          this.macroTick();
        }
}

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 2.3.2 版本修复
