### ISSUE TITLE
[Feature Request] 希望能增加个支持safe-area-inset-bottom的容器组件

### ISSUE THREAD

**Issue by LvJianfeng** [youzan/vant#5331]
### 这个功能解决了什么问题
便于适配，便于自定义

### 描述您想要的解决方案
支持safe-area-inset-bottom的容器组件，便于适配，便于自定义

### 建议的API是什么样的
van-container / van-safe-container

**Comment by chenjiahan** [comment]
暂无计划支持喔，这个加几行样式就可以搞定的

```css
padding-bottom: constant(safe-area-inset-bottom);
padding-bottom: env(safe-area-inset-bottom);
```
