### ISSUE TITLE
[Feature Request] 组件的 methods 内写有 uniapp 的生命周期会报错！

### ISSUE THREAD

**Issue by JimboXie** [youzan/vant#5332]
### 这个功能解决了什么问题
用 uniapp 搭建 h5 的时候，引入 vant 组件，但是有些组件内的方法名字是 uniapp 的生命周期名，导致在执行的时候找不到该方法！

### 描述您想要的解决方案
建议把有关 uniapp 的生命周期的方法名更换掉！谢谢！

### 建议的API是什么样的
vant 的 Tab 标签页组件

**Comment by chenjiahan** [comment]
具体是什么方法名？

**Comment by JimboXie** [comment]
> 具体是什么方法名？

tabs 组件中的 onShow 方法、image 中的 onLoad 方法、onError方法，其他的组件没注意过。不一定没有哈

**Comment by chenjiahan** [comment]
抱歉，这些方法名都是很常见的，我们没有计划修改代码。建议向 uniapp 反馈该问题

**Comment by JimboXie** [comment]
> 抱歉，这些方法名都是很常见的，我们没有计划修改代码。建议向uniapp反馈该问题

ok，没事，已经本地化然后修改了，谢谢哈

**Comment by fcbflying** [comment]
@JimboXie 你好，具体是怎么本地化修改解决的呢？
