### ISSUE TITLE
Uploader上传组件开启multiple多选属性后，加入限制上传数量是5个 第一次上传2张，第二次上次4张，并没有限制，还是上传了6张

### ISSUE THREAD

**Issue by akastronger** [youzan/vant#5333]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
