### ISSUE TITLE
list  已经设置:immediate-check= "false"  但是在前一个页面滚动条滚动到底部之后  点击打开页面时load被即时触发  怎么回事

### ISSUE THREAD

**Issue by Mariah-feifei** [youzan/vant#5335]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
