### ISSUE TITLE
打包不能编译问题

### ISSUE THREAD

**Issue by oufish** [youzan/vant#5336]
Vant 版本
2.2.11

Vue版本
2.5.7
打包后
ERROR in static/js/vendor.9f43189fee76a470331d.js from UglifyJs
Unexpected token: operator (>) [./~/vant/es/index.js:171,0][static/js/vendor.9f43189fee76a470331d.js:19412,27]
经过查看代码后，发现打包出来的代码是ES6 （19412行）
----------------------------------
components.forEach(item => {
    if (item.install) {
      Vue.use(item);
    } else if (item.name) {
      Vue.component(item.name, item);
    }
  });
--------------------------------

**Comment by chenjiahan** [comment]
感谢反馈，已在 2.3.1 版本修复
