### ISSUE TITLE
ImagePreview组件 Close 方法执行两遍

### ISSUE THREAD

**Issue by anjina** [youzan/vant#5338]
你好，我把ImagePreview组件单独放在一个页面里， 图片预览时跳转至该页面， 触发close方法时，
onClose() {
   console.log(this.$router);
   this.$router.back();
}
代码如上，发现路由返回了上上个页面，调试的时候发现console执行了两次，我只点了一下，请问可能是什么原因呢？

**Comment by chenjiahan** [comment]
可能是多次调用 ImagePreview 导致的，下个版本会兼容下

**Comment by chenjiahan** [comment]
已在 2.3.2 版本修复

**Comment by anjina** [comment]
> 已在 2.3.2 版本修复

你好，安装了2.3.3的版本，貌似还是有这个问题呢。
![image](https://user-images.githubusercontent.com/32081858/71302422-b5a20a80-23e5-11ea-82d0-a6d150bc00ab.png)
close方法如上，
打印结果：
![image](https://user-images.githubusercontent.com/32081858/71302531-e20a5680-23e6-11ea-833e-2318da379606.png)

有一个和官网描述参数一样，有一个无参数，麻烦分析下 ，谢谢

**Comment by chenjiahan** [comment]
看起来没什么问题，能否提供下复现的 codesandbox 链接呢

**Comment by Zclhlmgqzc** [comment]
@chenjiahan 
应该是异步关闭的问题
```js
this.$emit('close', {
  index,
   url: this.images[index]
});

if (!this.asyncClose) {
  this.$emit('input', false);
 }

```

```js

if (!this.asyncClose) {
  this.$emit('close', {
    index,
    url: this.images[index]
  });

  this.$emit('input', false);
 }

```

**Comment by chenjiahan** [comment]
@Zclhlmgqzc 这里确实有问题，下个版本会修复下

**Comment by chenjiahan** [comment]
已在 2.4.0-beta.0 版本修复
