### ISSUE TITLE
ssr项目引入tabs时，静态化的代码还是<van-tabs>...<van-tabs>的形式

### ISSUE THREAD

**Issue by zionLu** [youzan/vant#5339]
ssr项目引入tabs组件时，静态化的代码还是<van-tabs>...<van-tabs>的形式，页面展示过程中，首屏还是会有一闪，之后才解析代码并正常显示
引入的方式是官网第一种的在babel.config.js中配置的方式。
请问是什么问题？谢谢

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
