### ISSUE TITLE
[Bug Report] Cannot find module '../index.css'

### ISSUE THREAD

**Issue by cocotyty** [youzan/vant#5343]
### 设备 / 浏览器
chrome 最新版本

### Vant 版本
2.3.2

### Vue版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-ihthe" target="_blank">https://codesandbox.io/s/vant-issue-moban-ihthe</a>

### 描述问题
Lazyload： Cannot find module '../index.css'

**Comment by chenjiahan** [comment]
感谢反馈，已在 2.3.3 版本修复
