### ISSUE TITLE
[Bug Report] 在list组件中循环生成的点击事件失效

### ISSUE THREAD

**Issue by zx143** [youzan/vant#5344]
### 设备 / 浏览器
chrome模拟iPhone6/7/8

### Vant 版本
2.2.14

### Vue版本
2.6.11

### 重现链接
<a href="http://192.168.7.170:8093/" target="_blank">http://192.168.7.170:8093/</a>

### 描述问题
列表页中使用card卡片组件循环生成列表时页面点击事件有效,使用list进行分页包裹card列表加载后,card中的click事件失效

**Comment by chenjiahan** [comment]
上面的链接打不开，麻烦提供一下 codesandbox 复现链接

**Comment by zx143** [comment]
感谢回复,已经解决了,通过对比其它滚动插件发现是因为我在滚动盒子上加入了相对定位引发的子元素上的点击事件失效,去掉滚动盒子上的相对定位就可以了.

**Comment by chenjiahan** [comment]
好的
