### ISSUE TITLE
TabBar切换颜色没有加深

### ISSUE THREAD

**Issue by oYangJingLun** [youzan/vant#535]
看到active的索引值发生了变化，但是颜色没有加深，但是Tab是能切换并且改变颜色的
安装的包：
    "vant": "^0.12.3",
    "vue": "^2.1.0",
    "vue-router": "^2.1.1",
    "vuex": "^2.0.0"
![image](https://user-images.githubusercontent.com/29701501/34916224-8e268708-f96f-11e7-9b65-9f7ad48cfd63.png)

**Comment by chenjiahan** [comment]
麻烦提供复现该问题的 jsfiddle 链接

**Comment by oYangJingLun** [comment]
jsfiddle不太会用。
全局注册vant，用TabBar的基础用法。
package.json
 "dependencies": {
    "better-scroll": "^0.1.15",
    "fastclick": "^1.0.6",
    "iscroll": "^5.2.0",
    "showdown": "^1.6.4",
    "vant": "^0.12.3",
    "vue": "^2.1.0",
    "vue-router": "^2.1.1",
    "vuex": "^2.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^6.4.0",
    "autoprefixer-loader": "^3.2.0",
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-plugin-import": "^1.6.3",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "babel-register": "^6.0.0",
    "babel-runtime": "^6.23.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.1.0",
    "cross-env": "^5.0.0",
    "css-loader": "^0.25.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.13.3",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "function-bind": "^1.0.2",
    "html-webpack-plugin": "^2.8.1",
    "http-proxy-middleware": "^0.17.2",
    "json-loader": "^0.5.4",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "node-gyp": "^3.4.0",
    "node-sass": "^4.5.0",
    "opn": "^4.0.2",
    "ora": "^0.3.0",
    "sass": "^0.5.0",
    "sass-loader": "^4.1.1",
    "scss": "^0.2.4",
    "scss-loader": "0.0.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.4",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "vue-loader": "^10.0.0",
    "vue-style-loader": "^1.0.0",
    "vue-template-compiler": "^2.1.0",
    "webpack": "^1.13.2",
    "webpack-dev-middleware": "^1.8.3",
    "webpack-dev-server": "^1.16.2",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1"
  }

**Comment by chenjiahan** [comment]
抱歉这样没法帮你定位问题，贴代码也行

**Comment by oYangJingLun** [comment]
只要package.json这样配置，TabBar就会有问题，拷我自己一个别的工程的package.json就是正常的。
我不知道是哪个依赖太旧了还是怎么回事

**Comment by chenjiahan** [comment]
升级下 vue 吧
