### ISSUE TITLE
[Bug Report] DropdownItem 下拉菜单,toggle(true)无法展开

### ISSUE THREAD

**Issue by xieahui** [youzan/vant#5358]
### 设备 / 浏览器
谷歌浏览器: 版本 79.0.3945.88（正式版本） （64 位）

### Vant 版本
2.3.3

### Vue版本
2.6.6

### 重现链接
<a href="https://github.com/youzan/vant/issues/5357" target="_blank">https://github.com/youzan/vant/issues/5357</a>

### 描述问题
toggle方法可以收起，无法展开。代码如下：

<template>
    <div class="home">
        <van-dropdown-menu>
            <van-dropdown-item v-model="value" :options="option"/>
            <van-dropdown-item title="筛选" ref="item">
                <van-cell-group>
                    <van-field
                            v-model="username"
                            required
                            clearable
                            label="用户名"
                            right-icon="question-o"
                            placeholder="请输入用户名"
                            @click-right-icon="$toast('question')"
                    />
                </van-cell-group>
                <van-button block type="info" @click="onConfirm">确认</van-button>
            </van-dropdown-item>
        </van-dropdown-menu>

        <van-button block type="info" @click="onOpen">展开</van-button>
    </div>
</template>

<script>
    export default {
        name: "home",
        data() {
            return {
                username: '',
                value: 0,
                option: [
                    {text: '全部商品', value: 0},
                    {text: '新款商品', value: 1},
                    {text: '活动商品', value: 2}
                ]
            };
        },
        methods: {
            onOpen() {
                window.console.log(1)
                this.$refs.item.toggle(true);
            },
            onConfirm() {
                this.$refs.item.toggle();
            }
        }
    };
</script>
<style lang="less" scoped>
    .home {
        width: 100%;
        height: 100%;
        background-color: #e4e4e4;
    }
</style>

**Comment by 925941723** [comment]
请问怎么解决的

**Comment by 925941723** [comment]
哦，我知道了。要放在同一个van-dropdown-menu下面才能控制
