### ISSUE TITLE
[Bug Report] 使用van-collapse时出现横线

### ISSUE THREAD

**Issue by CJWWW** [youzan/vant#5362]
### 设备 / 浏览器
Chrome/华为P30 pro自带浏览器

### Vant 版本
2.2.2

### Vue版本
2.6.10

### 重现链接
<a href="https://s2.ax1x.com/2019/12/23/lpC1IK.md.jpg" target="_blank">https://s2.ax1x.com/2019/12/23/lpC1IK.md.jpg</a>

### 描述问题
在使用van-collapse(折叠面板)的页面中，当页面高度为单数时，页面中间出现一条高度1px，宽度100%的横线。经过排查，发现是一个.van-hairline--top-bottom的class的border-bottom，去掉该class后页面正常

**Comment by chenjiahan** [comment]
这个是折叠面板本身的边框，不是 bug。如果是在页面中间出现的话，建议排查下是不是其他原因导致的

**Comment by ylxieg** [comment]
本身的边框如何去掉？还有collapse的内边距怎么去掉？都在van-cell的样式里封装的padding。无法修改啊
