### ISSUE TITLE
页面初始化swipe插件的时候 swipe的高度高于图片高度，需要loop一回后才恢复

### ISSUE THREAD

**Issue by ByeWord** [youzan/vant#5364]
<template>
    <div class="home-hot">
        <van-swipe>
            <van-swipe-item v-for="(image, index) in images" :key="index" @click="onClick">
                <img v-lazy="image" class="swipe-image"/>
            </van-swipe-item>
        </van-swipe>
    </div>
</template>
<script>
    export default {
        name: 'hot',
        data() {
            return {
                images: [
                    'https://img.yzcdn.cn/vant/apple-1.jpg',
                    'https://img.yzcdn.cn/vant/apple-1.jpg',
                    'https://img.yzcdn.cn/vant/apple-1.jpg',
                    'https://img.yzcdn.cn/vant/apple-1.jpg',
                ]
            }
        },
        methods: {
            onClick(event) {
                console.log(event);
            }
        }
    }
</script>
<style scoped lang="scss">
    .home-hot {
        width: 100%;
        height: 100%;
        padding-top: 44px;
        padding-bottom: 50px;
        background-color: gray;

        .van-swipe {
            .van-swipe-item {
                .swipe-image {
                    width: 100%;
                    display: block;
                }
            }
        }
    }
</style>

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
