### ISSUE TITLE
官网的示例  icon 不显示了。woff地址404了。

### ISSUE THREAD

**Issue by SkyGrass** [youzan/vant#5366]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
看了下没问题喔，可以正常加载的

https://img.yzcdn.cn/vant/vant-icon-d3825a.woff2
https://img.yzcdn.cn/vant/vant-icon-d3825a.woff
