### ISSUE TITLE
[Feature Request] 希望能增加一个calendar可定义的日程表组件

### ISSUE THREAD

**Issue by Bdarno** [youzan/vant#5367]
### 这个功能解决了什么问题
日程的安排

### 描述您想要的解决方案
一个类似于ant design mobile的calendar的组件，如果可以有可以添加日程的功能那就更好了

### 建议的API是什么样的
日程的安排

**Comment by chenjiahan** [comment]
正在开发中✌️

**Comment by chenjiahan** [comment]
已在 2.4.0-beta.0 版本支持
