### ISSUE TITLE
picker 组件文档

### ISSUE THREAD

**Issue by de1ck** [youzan/vant#537]
column中只发现 value 怎么设置key 
文档api选项里面有个 value-key
不知道怎么使用:flushed:

**Comment by de1ck** [comment]
columns 
1. 字符串数组  默认value === string
2. 对象数组  默认使用对象中text字段显示   onConfirm(value,index) value对应数组中的对象
3. 多重数组 
官网文档中关于这点写的不是很详细，使用起来很困难。可以完善一下。

**Comment by chenjiahan** [comment]
感谢反馈，后续会优化 Picke 文档

**Comment by chenjiahan** [comment]
文档已完善

**Comment by cnJLF** [comment]
Vant怎么用value-key文档解释写得有点简略啊，看不懂呐

**Comment by Airkro** [comment]
还是不知道如何使用

**Comment by hottaiger** [comment]
好像并没有完善
