### ISSUE TITLE
[Bug Report] 能否支持 quasar 的ssr模式？

### ISSUE THREAD

**Issue by xiaoer3301** [youzan/vant#5370]
### 设备 / 浏览器
macOS / chrome

### Vant 版本
2.3.3

### Vue版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/" target="_blank">https://youzan.github.io/vant/#/zh-CN/</a>
<a href="https://quasar.dev/start/pick-quasar-flavour" target="_blank">https://quasar.dev/start/pick-quasar-flavour</a>

### 描述问题
quasar 在 vue 官方是被推荐的，但是在使用quasar 导入 vant 时，会出现错误。

#### quasar 配置
入口文件：cli 执行 `$ quasar new boot vant`。生成文件在 `/src/boot/vant.js`
在 quasar.config.js 的 boot 数组加上 `'vant'`，这时就有入口文件了。
这时 各种方法的 import 组件都会报错

SSR 模式：`$ quasar dev -m ssr`

**Comment by chenjiahan** [comment]
没用过 quasar，能帮忙排查下报错原因吗

**Comment by chenjiahan** [comment]
这个报错应该是引入 esmodule 导致的，Vant 有提供 commonjs 和 esmodule 两种引入方式的，可以通过 babel-plugin-import 的 libraryDirectory 选项进行切换，将 libraryDirectory 设置为 lib 即可。
