### ISSUE TITLE
ActionSheet slot中增加checkbox等表单，不能及时渲染状态。

### ISSUE THREAD

**Issue by hallwong** [youzan/vant#5371]
<van-action-sheet v-model="show" title="标题">
  <p>
内容
<van-checkbox v-model="item.checked">复选框</van-checkbox>
</p>
</van-action-sheet>

这种深层数据绑定存在不能渲染的情况，当点击复选框并未及时更改状态

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
