### ISSUE TITLE
[Bug Report] card err layout

### ISSUE THREAD

**Issue by flmbbb** [youzan/vant#5376]
设备 / 浏览器
chrome

Vant 版本
2.2.16

Vue版本
3.12.0

重现链接
http://superjxc.kspace.top/SuperWeb/123.png

描述问题
card布局错误

**Comment by flmbbb** [comment]
设备 / 浏览器
chrome

Vant 版本
2.2.16

Vue版本
3.0.0-alpha.0

重现链接
http://superjxc.kspace.top/SuperWeb/123.png

描述问题
card布局错误

**Comment by flmbbb** [comment]
设备 / 浏览器
chrome

Vant 版本
2.2.16

Vue版本
3.12.0

重现链接
http://superjxc.kspace.top/SuperWeb/123.png

描述问题
card布局错误

**Comment by chenjiahan** [comment]
麻烦提供一下复现问题的 codesandbox 链接

**Comment by flmbbb** [comment]
我在当中插入了两个cell就正常了
![123](https://user-images.githubusercontent.com/17305384/71438413-a8ac5080-2730-11ea-9d9a-2018df99b519.png)
其结果如上...

**Comment by chenjiahan** [comment]
你指的是 SubmitBar 会盖住页面元素吗，它是 fixed 布局，所以会盖住是正常的。

加个 margin/padding 之类的都可以。
