### ISSUE TITLE
[Bug Report] AddressList 地址列表 设置 isDefault 失效

### ISSUE THREAD

**Issue by iyayaa** [youzan/vant#5377]
### 设备 / 浏览器
chrome

### Vant 版本
2.3.0

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-7j2hu" target="_blank">https://codesandbox.io/s/vant-issue-moban-7j2hu</a>

### 描述问题
地址列表对应的数据设置了 isDefault：true 然而并没有显示默认地址 ，查看页面元素发现也没有生成相应的 dom 元素

**Comment by chenjiahan** [comment]
如果需要展示标签的话，需要设置 `default-tag-text` 属性喔

**Comment by wencyGit** [comment]
@chenjiahan 效率这么低的吗，隔几天了还不把这个在文档补上去

**Comment by zhengcheng123** [comment]
加了default-tag-text也没用

**Comment by chenjiahan** [comment]
@zhengcheng123 确认下版本在 2.3.0 以上才行

**Comment by futurehu** [comment]
> 加了default-tag-text也没用

请问解决了吗？ 我版本是2.6.1 加了default-tag-text属性 也没有‘默认’,dom也没生成

**Comment by futurehu** [comment]
> 加了default-tag-text也没用

解决了
