### ISSUE TITLE
[Feature Request] Uploader 上传照片选择相册选择时自定义选择的照片数量。

### ISSUE THREAD

**Issue by xiaoxu7777** [youzan/vant#5378]
### 这个功能解决了什么问题
调用相册时可以选择无数张照片。

### 描述您想要的解决方案
新增一个multiple的值来定义最多在相册中最多可以选择的图片数量。

### 建议的API是什么样的
:multiple="9"

**Comment by chenjiahan** [comment]
图片选择是系统提供的能力，目前没有对应的属性来设置最大可选的图片数量。因此无法实现这个功能
