### ISSUE TITLE
tab标签页中使用PullRefresh组件中使用list组件，多个list列表中位于第一个位置的list列表会出现onload事件别循环调用，滚动条卡在底部一直不动

### ISSUE THREAD

**Issue by czgsnow** [youzan/vant#5380]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
