### ISSUE TITLE
vant tabs 在 v-show 下出现下标不显示的bug

### ISSUE THREAD

**Issue by dmskys** [youzan/vant#5381]
<Home v-show="active==='home'"></Home>
<Order v-if="active==='order'"></Order>

Home组件与Order都有一个tab标签栏
当前显示Home组件，但是当显示Order组件时，order组件内的tab标签指示显示不出来。
此问题与这篇博客一样：https://blog.csdn.net/qq_31001061/article/details/84797596

**Comment by chenjiahan** [comment]
这个问题无法解决呢，原因是 Tab 在隐藏状态下无法获取到自身的宽度，因此无法正确计算下标的位置。

用 v-if 是可以避免的
