### ISSUE TITLE
[Bug Report] tabbar随着列表上拉而向上拉动，没有始终固定在底部

### ISSUE THREAD

**Issue by vivian217** [youzan/vant#5382]
### 设备 / 浏览器
iPhone 6s  plus

### Vant 版本
2.3.3

### Vue版本
2.6.10

### 描述问题
tabbar在页面有列表的情况下，列表上拉加载的时候，底部tabbar也会随着上拉的动作而上移，没有始终固定在底部

**Comment by chenjiahan** [comment]
麻烦提供一下复现问题的 codesandbox 链接

**Comment by wswww** [comment]
设备 / 浏览器
iPhone 6s plus

Vant 版本
2.3.3

Vue版本
2.6.10

描述问题
你好 我没有用float布局 为什么会一直触发加载?
