### ISSUE TITLE
[Bug Report] 同时有多个loading时，去掉其中一个时，作用于body上的防止背景点击的class被去掉了

### ISSUE THREAD

**Issue by huanghe1991** [youzan/vant#5383]
当我同时开启多个loading，然后去掉其中一个时
![image](https://user-images.githubusercontent.com/26794809/71444752-b40e7480-274e-11ea-860c-ccfba6d2bc67.png)
body上的禁止背景点击的类被去掉了
![image](https://user-images.githubusercontent.com/26794809/71444784-f20b9880-274e-11ea-8287-8bef7951da8c.png)
此时剩下的loading就无法禁止背景点击了

loading尚未关闭时，body上有用于禁止背景点击的类
![image](https://user-images.githubusercontent.com/26794809/71444825-4d3d8b00-274f-11ea-9673-436563934759.png)

**Comment by chenjiahan** [comment]
能否提供一下复现该问题的 codesandbox 链接呢

**Comment by huanghe1991** [comment]
不好意思，提供不了链接

**Comment by chenjiahan** [comment]
已复现，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.4.0-beta.0 版本修复
