### ISSUE TITLE
[Feature Request] 希望list组件的finished-text支持自定义

### ISSUE THREAD

**Issue by y451687300** [youzan/vant#5384]
### 这个功能解决了什么问题
可以解决如果列表条数过少，尤其是不占满一屏幕高度时，提示信息不美观的问题

### 描述您想要的解决方案
可以自定义样式比如加入icon   

### 建议的API是什么样的
通过v-bind传入一个dom

**Comment by chenjiahan** [comment]
下个版本会加个插槽来自定义 finished-text

**Comment by wswww** [comment]
设备 / 浏览器
iPhone 6s plus

Vant 版本
2.3.3

Vue版本
2.6.10

描述问题
你好 list组件 我没有用float布局 为什么会一直触发加载?

**Comment by chenjiahan** [comment]
@wswww 可以提供 codesandbox 复现链接看下

**Comment by wswww** [comment]
@chenjiahan 你好 谢谢 找到原因了 html设置了/* overflow: hidden; */  /* overflow-y: scroll; */ 把它注释掉就不会一直触发加载了

**Comment by chenjiahan** [comment]
噢噢，了解

**Comment by chenjiahan** [comment]
已在 2.4.0-beta.0 版本支持
