### ISSUE TITLE
[Feature Request] 调用DateTimePicker时，界面数值默认locate到今天

### ISSUE THREAD

**Issue by impeiran** [youzan/vant#5385]
#### 这个功能解决了什么问题
大部分场景下，选择时间会靠近当前时间，如果默认locate到今天/当前时间的话，可以增加用户体验

#### 描述您想要的解决方案
提供一个prop表示绑定值为空的界面locate值，默认是new Date()，即今天

绑定值为空时，根据上述prop进行locate，若超出给定范围min-date ~ max-date，则locate到范围边界

#### 建议的API是什么样的
default-locate-time

**Comment by chenjiahan** [comment]
后续会评估下能否支持

**Comment by chenjiahan** [comment]
这个 API 没有太大的必要，因为当前是通过 v-model 绑定的，直接设置 v-model 的初始值就可以达成上述需求

**Comment by impeiran** [comment]
> 这个 API 没有太大的必要，因为当前是通过 v-model 绑定的，直接设置 v-model 的初始值就可以达成上述需求

这个操作是知道的，只是现在绝大部分UI框架，日期时间选择组件，交互体验上，打开之后数值面板都是locate到今天
https://didi.github.io/cube-ui/#/zh-CN/docs/date-picker

**Comment by chenjiahan** [comment]
按照文档示例写，默认就是 locate 到今天的

**Comment by yexiaodong** [comment]
问题是不希望设置默认值

**Comment by lvya-sy** [comment]
影响还挺大，换了UI库，从vux换过来，没注意默认值选得不对，结果被用户投述了

**Comment by lxltmx** [comment]
同样遇到这个问题，不希望设置默认值，但是用户选择时间时希望直接定位到当前时间，不然如果所选时间跨度较大，用户需要滑动好久。。。
