### ISSUE TITLE
[Feature Request] Uploader 预览图下能否加上图片描述，比如图片名称等

### ISSUE THREAD

**Issue by EVIL-lang** [youzan/vant#5386]
### 这个功能解决了什么问题
上传图片后预览时可以知道图片是哪一张

### 描述您想要的解决方案
于预览图下方添加字段描述

### 建议的API是什么样的
上传区域有upload-text	上传区域文字提示，图片区域也希望有相应功能

**Comment by chenjiahan** [comment]
后续会评估下能否支持

**Comment by chenjiahan** [comment]
这个需求暂不支持，如果有自定义图片预览的需求，建议把`preview-full-image`设置为`false`，然后手动调用 ImagePreview 组件来实现这个功能。
