### ISSUE TITLE
[Feature Request] tab页组件标题文字能否增加设置每个等间距全部显示

### ISSUE THREAD

**Issue by Dwyane-Wade** [youzan/vant#5387]
### 这个功能解决了什么问题
现在的tab页每个标题是定死的宽度，文字内容居中显示，显示不下的文字会变成.....   期望可以展示出全部的文字，每个标题之间等间距

### 描述您想要的解决方案
增加一个属性可以设置按文字多少自适应宽度，将全部显示出来，并且每个标题间的距离相等

### 建议的API是什么样的
增加一个属性可以设置按文字多少自适应宽度，将全部显示出来，并且每个标题间的距离相等

**Comment by chenjiahan** [comment]
ellipsis 设置为 false 即可
