### ISSUE TITLE
[Bug Report] GoodsAction 商品导航在uc浏览器，不固定在底部，随着滑动网页会往上跟随

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#5392]
### 设备 / 浏览器
ios

### Vant 版本
2.3.3

### Vue版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/goods-action" target="_blank">https://youzan.github.io/vant/#/zh-CN/goods-action</a>

### 描述问题
如上

**Comment by chenjiahan** [comment]
未复现此问题，建议看下是不是其他样式干扰了导致的
