### ISSUE TITLE
[Bug Report] upload上传图片后，部分图片旋转90度

### ISSUE THREAD

**Issue by dpp050700** [youzan/vant#5396]
### 设备 / 浏览器
谷歌

### Vant 版本
2.3.3

### Vue版本
2.6.11

### 重现链接
<a href="https://cloud.21tb.com/sf-server/file/getFile/95aa77b8e11240d15cf3b205b2262d9d-P_1523333333333/happy/842f0e22019541529ed37b0ffb9ef14b_0100" target="_blank">https://cloud.21tb.com/sf-server/file/getFile/95aa77b8e11240d15cf3b205b2262d9d-P_1523333333333/happy/842f0e22019541529ed37b0ffb9ef14b_0100</a>

### 描述问题
重现链接的图片是竖型的 但是上传后显示的图片被向左旋转了90度

**Comment by sylvaner-h** [comment]
#2332

**Comment by chenjiahan** [comment]
参见上述链接
