### ISSUE TITLE
vant的标签页使用粘性布局用offset-top会有间隙

### ISSUE THREAD

**Issue by YouthShouting** [youzan/vant#5397]
标签页给固定定位的下面的内容都滚动不了，设置offset-top的话在不同手机下看会有不同大小的间隙问题怎么解决？？？？？

**Comment by YouthShouting** [comment]
标签页给固定定位的下面的内容都滚动不了，设置offset-top的话在不同手机下看会有不同大小的间隙问题怎么解决？？？？？

**Comment by YouthShouting** [comment]
标签页给固定定位的下面的内容都滚动不了，设置offset-top的话在不同手机下看会有不同大小的间隙问题怎么解决？？？？？

**Comment by YouthShouting** [comment]
标签页给固定定位的下面的内容都滚动不了，设置offset-top的话在不同手机下看会有不同大小的间隙问题怎么解决？？？？？

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by helloZmy** [comment]
**“vant的标签页使用粘性布局用offset-top会有间隙”**
请问这个问题有没有解决

**Comment by helloZmy** [comment]
我也遇到了同样的问题。tab吸顶之后，滚动页面，会有1px的间隙

**Comment by monnai** [comment]
我是这样处理的：黏性布局会渲染成class="van-sticky van-sticky--fixed"的div元素，将这个元素的background设置和周围背景色相同，就看不出间隙了
