### ISSUE TITLE
ImagePreview 组件文档

### ISSUE THREAD

**Issue by xiewei1213** [youzan/vant#540]
文档中图片地址 https://img.yzcdn.cn/1.jpg 出错了。

**Comment by chenjiahan** [comment]
@xiewei1213 这只是个示例地址，请替换成实际使用的图片地址

**Comment by koala91** [comment]
@chenjiahan 好的，谢谢。只是感觉两张图片，第二张图片可以打开，第一张图片打不开有点奇怪。
