### ISSUE TITLE
[Feature Request] datepicker提供onInit事件，获取picker实例

### ISSUE THREAD

**Issue by JoyceYy** [youzan/vant#5401]
### 这个功能解决了什么问题
提前获取van-picker实例;目前开发中，需要手动调用onConfirm方法，完成时间选择，但是在选择器惯性滚动时，还没有触发onchange事件,拿不到picker实例；目前是通过datepicker.$children[0].$children[0]的方式获取的;

### 描述您想要的解决方案
组件挂载时，触发init事件，回调参数为picker 实例

### 建议的API是什么样的
组件挂载时，触发init事件，回调参数为picker 实例

**Comment by chenjiahan** [comment]
onConfirm 方法是内部方法，并不是提供给外部的 API，不建议直接调用的。

有什么场景需要手动调用 onConfirm 呢

**Comment by JoyceYy** [comment]
![image](https://user-images.githubusercontent.com/16013835/71537696-b0e7d400-295a-11ea-9e10-969e58c779a4.png)
目前场景是，自定义了一个时间区间选择器，配合dropdown使用，需要确认时获取日期，但是官方提供的toolbar样式不合适，需要自定义样式，此时需要手动调用onConfirm方法，停止惯性滚动。

**Comment by chenjiahan** [comment]
明白了，下个版本会添加两个方法：

DatetimePicker.getPicker()，用于获取 Picker 实例

Picker.confirm()，作为 onConfirm 对外暴露的方法名

**Comment by chenjiahan** [comment]
已在 2.4.0-beta.1 版本支持
