### ISSUE TITLE
[Bug Report] 图片预览 ImagePreview 缩放后位置错误

### ISSUE THREAD

**Issue by ILomoXin** [youzan/vant#5402]
### 设备 / 浏览器
android chrome 

### Vant 版本
2.3.3

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-rsmmg" target="_blank">https://codesandbox.io/s/vant-issue-moban-rsmmg</a>

### 描述问题
第一步：手机图片预览，放大图片，
第二步：滑动到最右边或者最左边，
第三步：再缩小图片，如果缩小到比一开始预览图片大，然后松手图片不能回到正确位置。如果缩小到比一开始预览图片小，松手后图片变成原来大小，能够回到正确位置。

**Comment by chenjiahan** [comment]
目前缩放确实有点问题，后续会优化下

**Comment by xiemf** [comment]
是否可以考虑使用scale属性，该属性safair下无问题

**Comment by chenjiahan** [comment]
已在 2.9.0-beta.2 版本修复
