### ISSUE TITLE
pop组件在多个的时候关闭会出现错误提示

### ISSUE THREAD

**Issue by sbiweeq** [youzan/vant#5405]
DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

**Comment by sbiweeq** [comment]
beforeDestroy: function beforeDestroy() {
    this.close();

    if (this.getContainer && this.$parent && this.$parent.$el) {
      this.$parent.$el.appendChild(this.$el);
    }
  },

错误函数
get-container="body"

**Comment by chenjiahan** [comment]
解决方法参见 https://github.com/youzan/vant/issues/5074
