### ISSUE TITLE
[Bug Report] 时间选择器DatePicker

### ISSUE THREAD

**Issue by MMangoo** [youzan/vant#5406]
<van-datetime-picker
        @cancel="selectTime = false"
        @confirm="timeSave"
        v-model="DateTime"
        :min-date="new Date()"
        type="dateTime"
      />

打开后渲染正常  但是滑动选择一松手就卡主 无报错cpu占用直接拉满  浏览器只能被强制关闭

**Comment by MMangoo** [comment]
:min-date="new Date()"    经测试  min-date  与max-date  都有这个问题

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/datetime-picker#she-zhi-min-date-huo-max-date-hou-chu-xian-ye-mian-qia-si-de-qing-kuang
