### ISSUE TITLE
[Bug Report] tag标记closeable属性动态设置true/false会复制该标签然后很快消失

### ISSUE THREAD

**Issue by Heather-Li** [youzan/vant#5407]
### 设备 / 浏览器
手机、PC端都会出现

### Vant 版本
2.3.3

### Vue版本
3.0.0-alpha.0

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-40nbg?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/embed/vant-issue-moban-40nbg?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
给tag标记设置closeable属性，动态设置true/false，会复制该标签然后很快消失

**Comment by chenjiahan** [comment]
确实有这个问题，是 transition 动画引起的，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.4.0-beta.0 版本修复
