### ISSUE TITLE
[Bug Report] 页面中有多个 count-down，如果页面是在Tab标签后台运行的话，会自动停掉

### ISSUE THREAD

**Issue by crazy-coder-man** [youzan/vant#5409]
### 设备 / 浏览器
Chrome

### Vant 版本
2.2.16

### Vue版本
2.6.11

### 描述问题
我的页面上有多个 van-count-down，如果页面是在Tab标签后台运行的话，会自动停掉

**Comment by crazy-coder-man** [comment]
现在发现有几率这样，并不是每次这样，还未找到原因

**Comment by chenjiahan** [comment]
能否提供复现问题的 codesandbox 链接看下
