### ISSUE TITLE
[Bug Report] 使用Swipe 组件内transform导致字体渲染模糊

### ISSUE THREAD

**Issue by czqclm** [youzan/vant#5415]
### 设备 / 浏览器
各个浏览器均出现

### Vant 版本
2.0.8

### Vue版本
2.6.10

### 重现链接
暂无上线

### 描述问题
swipe组件切换的时候会导致轮播以下的dom出现模糊的情况，在分辨率高的设备不明显，再分辨率低的设备上十分明显

**Comment by chenjiahan** [comment]
具体是什么设备，能否提供截图或复现的 codesandbox 链接看下
