### ISSUE TITLE
layout 24格栅布局 van-row type="flex", van-col 的样式竟然还是 靠的浮动 style:float

### ISSUE THREAD

**Issue by yangheng** [youzan/vant#5416]
24格栅 flex 布局的意义何在，van-col 应该是flex布局了啊，咋还都是float 布局，太坑了，弃了。

最重要的： flex 布局都是假的。。。。真服了

**Comment by chenjiahan** [comment]
不要看不起 float 布局喔，不喜欢的话可以不使用

**Comment by yangheng** [comment]
你这明明定义的是 type = flex, col 里面却是float, 你这怎么解释，跟喜不喜欢float有毛关系，请问的是你这flex布局到底是不是个幌子？还是你这就没整明白啥叫flex布局

**Comment by chenjiahan** [comment]
issue 是讨论问题的地方，有意见请友好讨论。
