### ISSUE TITLE
[Bug Report] van-tree-select控件中icon使用了行内样式，造成无法转换为rem

### ISSUE THREAD

**Issue by lauzean** [youzan/vant#5417]
### 设备 / 浏览器
-

### Vant 版本
2.3.3

### Vue版本
2.6.11

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/src/tree-select/index.tsx" target="_blank">https://github.com/youzan/vant/blob/dev/src/tree-select/index.tsx</a>

### 描述问题
van-tree-select控件中icon使用了行内样式，造成无法转换为rem
源代码：<Icon name="checked" size="16px" class={bem('selected')} />

**Comment by chenjiahan** [comment]
下个版本会去掉行内样式

**Comment by chenjiahan** [comment]
已在 2.4.0-beta.1 版本去除
