### ISSUE TITLE
密码输入框组件与数字键盘组件报错

### ISSUE THREAD

**Issue by NinjaJin** [youzan/vant#542]
按示例使用。。报错了，该怎么解决呢 
ERROR  Failed to compile with 2 errors                                 22:54:18

These dependencies were not found:

* vant/lib/number-key-board in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/RegisterView.vue
* vant/lib/number-key-board/style in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/RegisterView.vue

**Comment by NinjaJin** [comment]
NumberKeyboard报错，PasswordInput正常

**Comment by chenjiahan** [comment]
请注意拼写，不是 number-key-board，是 number-keyboard

**Comment by NinjaJin** [comment]
<van-number-keyboard
      :show="showKeyboard"
      @input="onInput"
      @delete="onDelete"
      @blur="showKeyboard = false"
    />
import { NumberKeyBoard } from 'vant'
components: {
    [NumberKeyBoard.name]: NumberKeyBoard
  }
我这样写，好像没拼写错误吧

**Comment by NinjaJin** [comment]
我明白了，应该要import { NumberKeyboard} from 'vant'
官网使用指南里是import { NumberKeyBoard } from 'vant'; 可以修改一下

**Comment by chenjiahan** [comment]
@NinjaJin 确实是文档的疏漏，感谢反馈

**Comment by zhanglongjiZLJ** [comment]
数字键盘还不可以使用

**Comment by zhanglongjiZLJ** [comment]
数字键盘还不可以使用,文档也没有更新过来

**Comment by MynameEric** [comment]
数字键盘里onPress事件在某些场景失效了，为啥不换成onClick事件呢

**Comment by MynameEric** [comment]
PasswordInput组件在谷歌浏览器翻译成中文也会出现布局错乱的问题
