### ISSUE TITLE
[Bug Report] Calendar 日历组件的 平铺展示 是不是有问题，并不能展示

### ISSUE THREAD

**Issue by microkof** [youzan/vant#5420]
### 设备 / 浏览器
chrome

### Vant 版本
2.4.0-beta.0

### Vue版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/calendar#ping-pu-zhan-shi" target="_blank">https://youzan.github.io/vant/#/zh-CN/calendar#ping-pu-zhan-shi</a>

### 描述问题
因为问题太明显，又是beta版，而且我觉得我不至于弄错问题，所以我就不提供重现链接了，日历组件的弹出是没问题的，按照范例平铺展示就出不来。把能弹出的日历加上平铺，也一样出不来。

**Comment by chenjiahan** [comment]
看了下，原因是示例里的 `poppable` 拼错了，后续会更正下

**Comment by microkof** [comment]
> 看了下，原因是示例里的 `poppable` 拼错了，后续会更正下

目前日历没有上一个月、下一个月的箭头，是不是未来会加上？

**Comment by chenjiahan** [comment]
暂时没有做其他交互方式的计划呢

**Comment by chenjiahan** [comment]
已更新文档
