### ISSUE TITLE
[Bug Report] picker滑动回弹问题

### ISSUE THREAD

**Issue by jingkewei** [youzan/vant#5421]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.0

### Vue版本
2.5.6

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/picker</a>

### 描述问题
电脑上picker在picker元素范围内滑动至某项后会回弹到鼠标开始滑动点击的位置（手机端没问题的）

**Comment by chenjiahan** [comment]
可以升级到最新版试下

**Comment by jingkewei** [comment]
升级到2.4.0还是不可以~

**Comment by chenjiahan** [comment]
是不是引入了其他库导致的呢，比如 fastclick，better-scroll

**Comment by jingkewei** [comment]
并没有  您可以看下vant官网上的demo  应该滑动和点击选择冲突了 我给您邮箱发个我录得视频

**Comment by chenjiahan** [comment]
我这里官网 demo 是正常的喔

**Comment by jingkewei** [comment]
您有收到我给您邮箱发的视频吗 你可以看下  那个视频就是我录得官网的demo   视频中有问题的复现

**Comment by chenjiahan** [comment]
收到了喔，近期会看下这个问题

**Comment by jingkewei** [comment]
辛苦 麻烦  感谢~~~

**Comment by chenjiahan** [comment]
已在 2.4.0-beta.1 版本修复
