### ISSUE TITLE
图片预览ImagePreview    微信浏览器点击查看大图无法关闭，不能左右拖动缩放， ios11.2

### ISSUE THREAD

**Issue by 15878345704** [youzan/vant#5423]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by chenjiahan** [comment]
无法操作可以参见 https://github.com/youzan/vant/issues/3015
