### ISSUE TITLE
[Bug Report] IndexBar 组件的滚动条跳动

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#5424]
### 设备 / 浏览器
任意

### Vant 版本
2.3.3

### Vue版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-zgt43" target="_blank">https://codesandbox.io/s/vant-issue-moban-zgt43</a>

### 描述问题
IndexBar 组件的滚动条跳动，注意观察右边的滚动条

**Comment by chenjiahan** [comment]
这里确实是有问题，目前版本中，把 `<template v-for="item in 60">`换成`<div v-for="item in 60">`可以解决。

下个版本会修复这个问题

**Comment by chenjiahan** [comment]
已在 2.4.0-beta.1 版本修复
