### ISSUE TITLE
[Bug Report]  Field 输入框 type =“number”IOS上的问题

### ISSUE THREAD

**Issue by NidhoggDJoking** [youzan/vant#5425]
### 设备 / 浏览器
IOS

### Vant 版本
2.3.2

### Vue版本
2.6.10

### 重现链接
<a href="http://127.0.0.1" target="_blank">http://127.0.0.1</a>

### 描述问题
[Bug Report] Field 输入框 type =“number”在Android上，input type=number是可以生效的。在iOS上即使做了限制，依旧可以键入字母
需要我们去掉type =“number”并添加正则限制才能达到效果.（前端还在开发中没有放置在服务器暂时没有链接）

**Comment by chenjiahan** [comment]
iOS keypress 事件不触发产生的问题，后续会修复

**Comment by NidhoggDJoking** [comment]
Stepper 步进器:中间的input框在IOS上字体不居中的问题也解决就更好了。

**Comment by chenjiahan** [comment]
已在 2.4.2-beta.1 版本修复输入问题，字体不居中问题未复现
