### ISSUE TITLE
ImagePreview  在ios微信浏览器下，点击图片背景会滚动

### ISSUE THREAD

**Issue by zhouxiankai** [youzan/vant#5426]
ImagePreview  在ios微信浏览器下，点击图片背景会滚动，
![image](https://user-images.githubusercontent.com/38032300/71573870-f1914a00-2b20-11ea-9699-5420d8ee035e.png)
点击后的图片也会弹到最上面，不在最中间显示
vant 2.2.2
ios 10.2

**Comment by zhouxiankai** [comment]
vue版本是2.6.6

**Comment by chenjiahan** [comment]
最上面蓝色的区域是什么内容喔？

**Comment by zhouxiankai** [comment]
上面蓝色的是app的头部，我写好蓝色下面的内容嵌入进去。
点击后 黑色背景的弹框高度跟我的页面高度是一样高的了  可以滚动的

**Comment by chenjiahan** [comment]
是只在 iOS 10 下出现吗

**Comment by zhouxiankai** [comment]
最新的也有

**Comment by chenjiahan** [comment]
我这儿没复现唉，能提供个复现问题的 codesandbox 链接么

**Comment by zhouxiankai** [comment]
![image](https://user-images.githubusercontent.com/38032300/71612725-37abe380-2bdd-11ea-87d6-e38b4e0cec16.png)
代码这块就这样，可以加我v 13587998239 ，我录屏给你看下问题

**Comment by chenjiahan** [comment]
抱歉不加 v，你可以把 ImagePreview 放到外层试下，可能被父元素的样式影响了

**Comment by zhouxiankai** [comment]
还是不行 ，是因为我的页面是镶在iframe下的原因么  
![image](https://user-images.githubusercontent.com/38032300/71616026-181db680-2bef-11ea-98b6-47f37514f7e4.png)

**Comment by chenjiahan** [comment]
跟 iframe 关系不大，有可能是组件样式被某些全局样式覆盖导致的

**Comment by 15878345704** [comment]
ios11.2 ，图片无法关闭，无法缩放拖动

**Comment by chenjiahan** [comment]
@15878345704 升级 2.4.0 试试

**Comment by 15878345704** [comment]
@chenjiahan 升级了2.4.0  图片可以关闭，但是无法缩放拖动

**Comment by chenjiahan** [comment]
目前在有兼容性的系统上只能做到正常关闭，问题的原因是：https://github.com/youzan/vant/issues/3015

**Comment by 15878345704** [comment]
@chenjiahan  关于图片无法缩放问题，我不能把vue版本降到2.5.22，会影响到我其他组件的使用，目前我的vue是2.6.10，请问还有其他方法么

**Comment by chenjiahan** [comment]
木有了
