### ISSUE TITLE
[Bug Report] Stepper步进器在安卓微信浏览器内加减号显示不全

### ISSUE THREAD

**Issue by ArtPop6** [youzan/vant#5434]
### 设备 / 浏览器
安卓微信浏览器

### Vant 版本
2.4.0-beta.1

### Vue版本
3.0.0-alpha.0

### 重现链接
<a href="http://localhost:10008/confirmOrder.html" target="_blank">http://localhost:10008/confirmOrder.html</a>

### 描述问题
Stepper步进器在安卓微信浏览器内加减号显示不全，会显示成两个减号或者完全没有显示

**Comment by chenjiahan** [comment]
能截个图看下吗，可以试试官网示例能否复现

**Comment by ArtPop6** [comment]
![image](https://user-images.githubusercontent.com/39336490/71619405-38ee0800-2bff-11ea-88f3-09d2d7b5d381.png)
 
![image](https://user-images.githubusercontent.com/39336490/71619562-ea8d3900-2bff-11ea-93cf-5fd1c2402ec9.png)

代码段
```
<div class="select">
     <van-stepper button-size="28px" input-width="50px" integer min="1" v-model="value" />
</div>
```
在微信打开项目链接就会这样，在浏览器打开就正常

**Comment by chenjiahan** [comment]
官网示例能复现吗

**Comment by ArtPop6** [comment]
重新开一个项目写有用，在自己项目好像就有问题，除了引入的vant.css没有引用其他别的样式,对stepper组件的样式也稍微自己手动做了些修改,是根据检查看到的元素进行的对应修改，也不知道为啥会这样。

**Comment by chenjiahan** [comment]
建议排查下是不是修改样式导致的问题喔

**Comment by xiaoqugreat** [comment]
两个项目都有这个问题

**Comment by liushasha0012** [comment]
您好，请问解决了吗？我在vivo X9上也遇到了同样的问题

**Comment by sifengyuan** [comment]
chorme也是这样 —— +号显示不全 圆角等样式无法显示

**Comment by wangfpp** [comment]
这个问题解决了吗？ @ArtPop6

**Comment by xiaoqugreat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wangfpp** [comment]
@liushasha0012 你解决这个问题了吗

**Comment by xiaoqugreat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
