### ISSUE TITLE
[Bug Report] SwipeCell 文档参数书写错误

### ISSUE THREAD

**Issue by Gyang18** [youzan/vant#5436]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.16

### Vue版本
3.0.0-alpha.0

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/swipe-cell" target="_blank">https://youzan.github.io/vant/#/zh-CN/swipe-cell</a>

### 描述问题
SwipeCell 组件的文档中，关闭前的回调函数的字段书写错误，文档中是before-close，实际源码中是onClose， 并且回调参数的格式也不正确

**Comment by Gyang18** [comment]
![image](https://user-images.githubusercontent.com/24975063/71616090-734fa900-2bef-11ea-9cb5-cd58875221ee.png)
![image](https://user-images.githubusercontent.com/24975063/71616099-819dc500-2bef-11ea-9576-693a98aa891f.png)

**Comment by chenjiahan** [comment]
我们计划在后续的大版本中废弃`on-close`方法，因此新增了`before-close`方法作为`on-close`的替代。

目前文档中是不包含 `on-close`的说明的（代码还留着），建议升级 Vant 版本并使用`beforec-lose`方法
