### ISSUE TITLE
[Bug Report] picker组件有行内样式，postcss无法转换，导致样式错乱

### ISSUE THREAD

**Issue by guagezuishuai** [youzan/vant#5440]
### 设备 / 浏览器
浏览器

### Vant 版本
2.4.0

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/picker</a>

### 描述问题
样式转换出现问题，因为有行内的样式，除了行内的样式其他的转换正常

**Comment by chenjiahan** [comment]
Picker 选项的高度是由 item-height 控制的，滚动过程中需要计算位置，所以会有行内样式。

具体样式错乱是什么表现呢？
