### ISSUE TITLE
[Bug Report] 日历 平铺展示

### ISSUE THREAD

**Issue by ZcpDream** [youzan/vant#5442]
### 设备 / 浏览器
iPhone6/7/8

### Vant 版本
2.4.0-beta.1

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-qr85e" target="_blank">https://codesandbox.io/s/vant-issue-moban-qr85e</a>

### 描述问题
把平铺展示demo,copy过来放在我的代码里,平铺日历没有在页面上展示出来,弹窗式的日历是可以展示出来 的,

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5420
