### ISSUE TITLE
[Bug Report] Calendar 日历组件代码演示问题

### ISSUE THREAD

**Issue by mypridelife** [youzan/vant#5444]
### 设备 / 浏览器
any

### Vant 版本
2.4.0

### Vue版本
3.0.0-alpha.0

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/calendar#yin-ru" target="_blank">https://youzan.github.io/vant/#/zh-CN/calendar#yin-ru</a>

### 描述问题
选择日期区间和选择单个日期的method反了，formatDate方法没有形参。:value绑定的值，不应该直接是[]。

**Comment by chenjiahan** [comment]
能否提个 PR 帮忙修正下~

**Comment by ZcpDream** [comment]
日历的当前回显时间:
今天是2012/01/02,周四,但是我看见官方的demo上显示的时间是2020/01/02,周三

**Comment by ZcpDream** [comment]
> 能否提个 PR 帮忙修正下~

日历的当前回显时间:
今天是2012/01/02,周四,但是我看见官方的demo上显示的时间是2020/01/02,周三

**Comment by aFishTail** [comment]
选择日期区间是否可以选中同一天？

**Comment by chenjiahan** [comment]
@aFishTail 后续应该会支持
