### ISSUE TITLE
[Bug Report] mini-css-extract-plugin Conflicting order

### ISSUE THREAD

**Issue by zaoyu63** [youzan/vant#5446]
### 设备 / 浏览器
macos/chrome

### Vant 版本
2.4.0

### Vue版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/calendar" target="_blank">https://youzan.github.io/vant/#/zh-CN/calendar</a>

### 描述问题
npm run build 
WARNING in chunk vant [mini-css-extract-plugin]
Conflicting order. Following module has been added

**Comment by chenjiahan** [comment]
能贴下完整的信息么

**Comment by zaoyu63** [comment]
![image](https://user-images.githubusercontent.com/30930585/71708224-aaf66500-2e2a-11ea-9073-9ced28705b63.png)

**Comment by chenjiahan** [comment]
从 2.4 版本开始，Vant 已经保证了组件样式的顺序，如果还是出现以上提示，建议把 `ignoreOrder`设置为`false`

```js
new MiniCssExtractPlugin({
  ignoreOrder: false, // Enable to remove warnings about conflicting order
})
```

**Comment by dongH555** [comment]
> 从 2.4 版本开始，Vant 已经保证了组件样式的顺序，如果还是出现以上提示，建议把 `ignoreOrder`设置为`false`
> 
> ```js
> new MiniCssExtractPlugin({
>   ignoreOrder: false, // Enable to remove warnings about conflicting order
> })
> ```

能否具体的说一下这个配置是在哪的？

**Comment by chenjiahan** [comment]
在 webpack 配置里

**Comment by FoooooooF** [comment]
在vue-cli的vue.config,js 中怎么设置?
