### ISSUE TITLE
popup mixin 里beforeDestory的处理有问题

### ISSUE THREAD

**Issue by wiorange** [youzan/vant#5448]
https://github.com/youzan/vant/blob/74c63ad2f02d1a6679ab42e969fee9ae9cf0877d/src/mixins/popup/index.js#L91

这里是否应该是先dom操作把元素归位 再调this.close呢 

我的场景是开着popup（container是document.body）浏览器返回 这个popup的内容还会一直显示
调换这个执行顺序问题就能解决

**Comment by chenjiahan** [comment]
是否有设置 close-on-popstate 属性？
