### ISSUE TITLE
[Bug Report] ImagePreview 组件放大高清图片模糊

### ISSUE THREAD

**Issue by xiemf** [youzan/vant#5449]
### 设备 / 浏览器
iphone6/微信浏览器

### Vant 版本
2.4.0

### Vue版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/image-preview" target="_blank">https://youzan.github.io/vant/#/zh-CN/image-preview</a>

### 描述问题
在ios系统浏览器预览图片 放大后导致高清图片模糊（推测为采用scale3d缩放图片导致）

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/4553

**Comment by woomins** [comment]
我也遇到了，请问怎么解决？

**Comment by xiemf** [comment]
style.transform = "scale3d(" + scale + ", " + scale + ", 1) translate(" + this.moveX / scale + "px, " + this.moveY / scale + "px)";

找到node_modules/vant 下的这句话
然后改成
style.transform = "scale(" + scale + ", " + scale + ") translate(" + this.moveX / scale + "px, " + this.moveY / scale + "px)";
将scale3d改用scale，后面的参数一改就ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "woomins"<notifications@github.com&gt;; 
发送时间: 2020年3月30日(星期一) 下午5:52
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "夏伤"<501235949@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] [Bug Report] ImagePreview 组件放大高清图片模糊 (#5449)





 
我也遇到了，请问怎么解决？

**Comment by woomins** [comment]
@xiemf  Ios始终不行，这个方法试过了，你的可以吗？？？
