### ISSUE TITLE
van-progress 希望进度条以后能支持拖动

### ISSUE THREAD

**Issue by BiuBiuKing** [youzan/vant#5450]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持，拖动请使用 Slider 组件
