### ISSUE TITLE
[Bug Report] 日历 时间

### ISSUE THREAD

**Issue by ZcpDream** [youzan/vant#5451]
### 设备 / 浏览器
iPhone6/7/8

### Vant 版本
2.4.0-beta.1

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-4vrxm" target="_blank">https://codesandbox.io/s/vant-issue-moban-4vrxm</a>

### 描述问题
今天是2012/01/02,周四,但是我看见官方的demo上显示的时间是2020/01/02,周三

**Comment by chenjiahan** [comment]
确实偏了一格。。下个版本修复

**Comment by ZcpDream** [comment]
请问什么时候可以发布新的版本

**Comment by chenjiahan** [comment]
今天会发一个

**Comment by chenjiahan** [comment]
已在 2.4.1 版本修复
