### ISSUE TITLE
V2.4版本Calendar 还是用不了

### ISSUE THREAD

**Issue by shangliaoyan** [youzan/vant#5454]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请打开 node_modules/vant/package.json 确认下你安装的版本是否正确
