### ISSUE TITLE
[Bug Report] collapse border属性无效

### ISSUE THREAD

**Issue by ylxieg** [youzan/vant#5457]
### 设备 / 浏览器
任意浏览器

### Vant 版本
2.4.1

### Vue版本
3.0.0-alpha.0

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-ofe0x?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-ofe0x?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
<van-collapse v-model="activeNames" border=false>
      <van-collapse-item name="1" class="van-collapse-item" border:false>
border无效

**Comment by chenjiahan** [comment]
:border="false"，前面要加冒号，不然传的是 string 不是 boolean
