### ISSUE TITLE
van-tabs配合van-list 第一次不 加载list

### ISSUE THREAD

**Issue by shiguangteng** [youzan/vant#5459]
路由的方式嵌入van-list:
<van-tab :title="tabLabels[0].label" to="taskList">
                <router-view></router-view>
            </van-tab>
路由到tasklist:
 <div class="list">
        <H1>31211</H1>
        <van-list
                ref="vanList"
                v-model="loading"
                :finished="finished"
                finished-text="没有更多了"
                :immediate-check="false"
                @load="onFetch1"
        >
            <TaskItem v-for="item in items" :p="item" type="RUNNINGTASK" v-if="items.length>0"></TaskItem>
        </van-list>
    </div>
router写法: path: "task",
            component: () => import("../pages/main/task"),
            redirect: "task/taskList",
            name: "Task",
            meta: {title: "任务"},
            children: [
                {
                    path: "taskList",
                    name: "TaskList",
                    component: () => import("../components/task-list"),
                }

第一次切换到taskList 也就是第一个tab页面时候list未加载为了测试特意写了个h1标签可以加载出内容来但是list不能.tab项切换,内容显示就正常,前端新手望指点

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
