### ISSUE TITLE
[Bug Report] tabs加list页面加载更多的时候当前页面会重复加载上一个页面的数据

### ISSUE THREAD

**Issue by qianlanse** [youzan/vant#5461]
### 设备 / 浏览器
mac/chrome

### Vant 版本
2.4.0

### Vue版本
2.6.10

### 重现链接
<a href="https://h.gojiapp.cn" target="_blank">https://h.gojiapp.cn</a>

### 描述问题
list页面
van-pull-refresh(v-model="refreshLoading" @refresh="handleRefresh")
        van-list.plr10.pt10.bg-dark-white(
            v-model="articleDataSource.loading"
            @load="handleArticleLoadMore"
            :offset="150"
            :immediate-check="false"
            :finished="articleDataSource.loaded"
            :finished-text="$i18n.noMoreData")
            m-loadmore(slot="loading" v-show="articleDataSource.totalPages")
            articlecomponent(:result="articleDataSource" :empty-text="articleEmptyText")
![image](https://user-images.githubusercontent.com/13144533/71702776-3e6c6d80-2e0c-11ea-9c98-329c1ef1c42d.png)

调用页面：
m-nav(:navs="navs" :current="currentTab" @change="handleChangeNav")
            article-list(
                v-for="(item, index) in navs"
                :key="index"
                :slot="item.slot"
                :ref="'list'   index"
                :tagId="item.id"
                search-type="index")
![image](https://user-images.githubusercontent.com/13144533/71702788-49bf9900-2e0c-11ea-897b-30f852bbaae3.png)

导航页面：
van-tabs(
                v-model="currentIndex"
                :ellipsis="false"
                :border="false"
                :sticky="sticky"
                :animated="animated"
                :swipeable="swipeable"
                :color="defaultColor"
                :offset-top="$pageConfig.headerHeight"
                @change="handleChangeNav")
                van-tab.color-title.bg-dark-1-white(
                    v-for="(nav, index) in navs"
                    :key="index"
                    :title="nav.name === 'foryou' ? $i18n.common.foryou : nav.name")
                    slot(:name="nav.slot")
![image](https://user-images.githubusercontent.com/13144533/71702790-50e6a700-2e0c-11ea-827c-1e8c12d9c6e8.png)

**Comment by qianlanse** [comment]
刚测试了下当animated为true的时候会出现这个问题，将animated设为false不会出现此问题

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3430
