### ISSUE TITLE
[Feature Request] 希望 Image 组件能新增 loading 和 error 提示 prop

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#5463]
### 这个功能解决了什么问题
方便全局修改 Image 组件的 loading 或 error 提示，不用每次都设置 loading 插槽

### 描述您想要的解决方案
新增 loading 和 error 提示 prop

### 建议的API是什么样的
新增 loading 和 error 提示 prop

**Comment by chenjiahan** [comment]
是指设置提示文字吗

**Comment by 1014156094** [comment]
> 是指设置提示文字吗

![image](https://user-images.githubusercontent.com/16074662/71709696-bb5f0d80-2e33-11ea-948b-e4a2924ff0f2.png)
是指这个

**Comment by chenjiahan** [comment]
暂时没有计划添加对应的文字属性，你可以用简单的封装一下哈，比如写一个 MyImage 组件，里面使用 van-image 并设置一个固定的 error slot，这样就不用每次去写了

**Comment by 1014156094** [comment]
> 暂时没有计划添加对应的文字属性，你可以用简单的封装一下哈，比如写一个 MyImage 组件，里面使用 van-image 并设置一个固定的 error slot，这样就不用每次去写了

加载中提示图片地址 prop 也不行么？

**Comment by chenjiahan** [comment]
没懂，给个大致的示例？

**Comment by 1014156094** [comment]
> 没懂，给个大致的示例？

例如：

<van-image
  width="100"
  height="100"
  src="https://img.yzcdn.cn/vant/cat.jpeg"
  loading="https://cdn.haosailei.cn/hsl-user/images/common/loading.gif"
/>

等于

<van-image src="https://img.yzcdn.cn/vant/cat.jpeg">
  <template v-slot:loading>
    <img src="https://cdn.haosailei.cn/hsl-user/images/common/loading.gif"/>
  </template>
</van-image>

**Comment by 1014156094** [comment]
> 没懂，给个大致的示例？
增加 loading prop ，例如：

<van-image
  width="100"
  height="100"
  src="https://img.yzcdn.cn/vant/cat.jpeg"
  loading="https://cdn.haosailei.cn/hsl-user/images/common/loading.gif"
/>

等于

<van-image src="https://img.yzcdn.cn/vant/cat.jpeg">
  <template v-slot:loading>
    <img src="https://cdn.haosailei.cn/hsl-user/images/common/loading.gif"/>
  </template>
</van-image>

**Comment by 1014156094** [comment]
增加 loading prop ，例如：

<van-image
  width="100"
  height="100"
  src="https://img.yzcdn.cn/vant/cat.jpeg"
  loading="https://cdn.haosailei.cn/hsl-user/images/common/loading.gif"
/>

等于

<van-image src="https://img.yzcdn.cn/vant/cat.jpeg">
  <template v-slot:loading>
    <img src="https://cdn.haosailei.cn/hsl-user/images/common/loading.gif"/>
  </template>
</van-image>

**Comment by 1014156094** [comment]
增加 loading prop ，例如：

```
<van-image
  width="100"
  height="100"
  src="https://img.yzcdn.cn/vant/cat.jpeg"
  loading="https://cdn.haosailei.cn/hsl-user/images/common/loading.gif"
/>
```

等于

```
<van-image src="https://img.yzcdn.cn/vant/cat.jpeg">
  <template v-slot:loading>
    <img src="https://cdn.haosailei.cn/hsl-user/images/common/loading.gif"/>
  </template>
</van-image>
```

**Comment by chenjiahan** [comment]
可以加个 loading-icon 和 error-icon 属性，能实现上面的需求

**Comment by chenjiahan** [comment]
已在 2.4.2-beta.0 版本支持
