### ISSUE TITLE
textarea字数统计无法显示

### ISSUE THREAD

**Issue by dev-kxy** [youzan/vant#5466]
<van-field
    v-model="message"
    rows="2"
    autosize
    label="留言"
    type="textarea"
    maxlength="50"
    placeholder="请输入留言"
    show-word-limit
  />

官网复制的demo，字符统计无法展示，不知道为什么，我本地应该也没有样式覆盖

**Comment by chenjiahan** [comment]
请确认下你使用的版本是否支持这个属性，版本过低的话可以升级下版本

**Comment by dev-kxy** [comment]
2.2.0版本

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/71713087-2237f300-2e43-11ea-90ea-9d22e8f4601c.png)

仔细看文档
