### ISSUE TITLE
希望日历可以增加“左右滑动切换功能“以及 “月历与周历切换功能“

### ISSUE THREAD

**Issue by 841440416** [youzan/vant#5467]
希望解决的问题：
1、支持左右滑动切换
2、支持左右切换年份、月份
3、支持月日历收缩成周历功能
4、希望加入农历及法定节假日字典功能
效果大致如钉钉日历:
![image](https://user-images.githubusercontent.com/26712681/71716811-f15eba80-2e50-11ea-8940-9d1e3ae66863.png)

**Comment by ZcpDream** [comment]
+1,希望可以新增支持左右滑动的功能

**Comment by chenjiahan** [comment]
暂时没计划做的这么复杂嘞
