### ISSUE TITLE
overlay嵌套失效

### ISSUE THREAD

**Issue by jiutianliminwang** [youzan/vant#5471]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant/#/zh-CN/overlay
-- 遮罩层的嵌套示范代码无法生效

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

另外请注意下 slot 的版本要求
