### ISSUE TITLE
图片懒加载不出来甚至出现错误标签 。image lazy loading  not work.

### ISSUE THREAD

**Issue by Farb** [youzan/vant#5472]
各位大佬好，我想在产品详情的页面上懒加载显示图片，但是折腾了很久都没成功，不知道是哪里出现了问题，使用方法是按照官方文档上来的。所使用的依赖截图如下：
![image](https://user-images.githubusercontent.com/7587900/71762908-ad32ef00-2f10-11ea-82bd-f77b7d5b3f54.png)

![image](https://user-images.githubusercontent.com/7587900/71763037-1ebf6d00-2f12-11ea-8343-b1fa081eb8f4.png)

写法1：页面代码如下，稍微解释一下，goods.info是一个数组，里面是产品详情图片的url数组：
`
	
			<div>
				<p v-for="item in goods.info" style="text-align:center;">
					<van-image lazy-load src="item">
						<template v-slot:loading>
						    <van-loading type="spinner" size="20" />
						  </template>
					</van-image>
				</p>
			</div>

`

显示效果不符合预期，如下：
![image](https://user-images.githubusercontent.com/7587900/71762944-fedb7980-2f10-11ea-8790-c6dfa118a571.png)
控制台没有报错，生成的dom元素如下：
![image](https://user-images.githubusercontent.com/7587900/71762955-26324680-2f11-11ea-91ef-9d8f3b3d874a.png)

写法2:代码如下：

`
 
       <p v-for="item in goods.info" style="text-align:center;">
	<van-image v-lazy="item">
		<template v-slot:loading>
		    <van-loading type="spinner" size="20" />
		  </template>
	</van-image>
    </p>

`

这种写法只显示加载中的插槽，一直显示加载中，就是看不到图片，但是看到dom已经生成了，如下所示：
![image](https://user-images.githubusercontent.com/7587900/71763018-ecae0b00-2f11-11ea-82b6-a19d0340de71.png)

请问这是问题出在什么地方了呢？请指教，多谢。

**Comment by Farb** [comment]
![image](https://user-images.githubusercontent.com/7587900/71763480-5f6db500-2f17-11ea-9c12-5afb1f9e871e.png)
这样写就可以了，但是有个问题，v-lazy指令不能用在van-image标签吗？

**Comment by chenjiahan** [comment]
v-lazy 指令不能用在 van-image 喔，组件内部会根据 lazy-load 属性自动判断的

**Comment by Farb** [comment]
> v-lazy 指令不能用在 van-image 喔，组件内部会根据 lazy-load 属性自动判断的

感谢回复，官方文档说的不是很详细
