### ISSUE TITLE
可以加一些表单验证功能 md5 这些功能

### ISSUE THREAD

**Issue by spark154204** [youzan/vant#5474]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持喔
