### ISSUE TITLE
倒计时组件(CountDown)在苹果手机上无效，即不倒计时，在安卓和浏览器上正常 

### ISSUE THREAD

**Issue by lahala** [youzan/vant#5476]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

另外 iOS 上如果遇到时间相关的问题，大概率是下面的原因：

> 请确认在创建 Date 对象时没有使用new Date('2020-01-01')这样的写法，iOS 不支持以中划线分隔的日期格式，正确写法是new Date('2020/01/01')。

**Comment by lahala** [comment]
好的 已解决 感谢哈
