### ISSUE TITLE
[Bug Report] swipe组件在刷新之后van-swipe-item内的布局出现问题

### ISSUE THREAD

**Issue by Middletwo-Kid** [youzan/vant#5477]
### 设备 / 浏览器
iphon6 和 华为荣耀

### Vant 版本
2.4.1

### Vue版本
3.0.0-alpha.1

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-qvisv?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-qvisv?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
swipe组件在【刷新】之后van-swipe-item内的布局出现问题，不同van-swipe-item的内容都挤在一起显示，.van-swipe__track的宽度为0，修改样式让其正确显示之后，不能滑动

**Comment by chenjiahan** [comment]
看了下链接里的代码没有问题喔，建议你尝试下官网示例是否存在该问题，如果官网没问题的话，可能是项目里的其他原因导致

**Comment by Middletwo-Kid** [comment]
谢谢。跟环境有点关系，已解决

**Comment by SenierLink** [comment]
可以问下什么环境导致的嘛？
我遇到的问题是，组件全部挤在一屏，没有按照预想的横着排开。
文档给的demo也不能正常使用，item全部竖着码在一起。滑动也没法让他们分开。
