### ISSUE TITLE
DatetimePicker组件getPicker方法为undefined

### ISSUE THREAD

**Issue by clown-wyj** [youzan/vant#5478]
当我使用DatetimePicker组件的时候如下：
```
<DatetimePicker ref="datetimePicker" type="time" ref="datetime" />
this.$refs.datetimePicker.getPicker     // undefined
```
我看文档提供了这个方法获取Picker实例，这让我很迷茫。

**Comment by chenjiahan** [comment]
需要升级到 2.4.0 版本才能使用喔，后续会在文档里加上版本提示

**Comment by clown-wyj** [comment]
我升级到了最新版本getPicker方法还是undefined。是不是我是用vue-jsx问题，但是我使用其他组件都没有发现这种情况。

**Comment by chenjiahan** [comment]
可以打开 node_modules/vant/package.json 确认下你的版本
