### ISSUE TITLE
AddressEdit 地址编辑  "show-set-default"  属性的文字 是否支持修改？ 

### ISSUE THREAD

**Issue by Gzbox** [youzan/vant#5482]
AddressEdit 地址编辑  "show-set-default"  属性的文字 是否支持修改？ 
在文档上面没看到。
![image](https://user-images.githubusercontent.com/21010051/71803720-86a1bf00-309c-11ea-914e-ff9509ef702f.png)

**Comment by chenjiahan** [comment]
可以通过 Locale 国际化组件修改文案

```js
import { Locale } from 'vant';

Locale.add({
  'zh-CN': {
    vanAddressEdit: {
      defaultAddress: '自定义默认地址文案'
    }
  }
});
```
