### ISSUE TITLE
[Feature Request] 建议Calender日历组件优化formatter函数

### ISSUE THREAD

**Issue by lx623** [youzan/vant#5483]
### 这个功能解决了什么问题
日历组件自定义提示内容

### 描述您想要的解决方案
formatter函数day参数对象是一个数组对象

### 建议的API是什么样的
formatter函数day参数对象是一个数组对象，直接引用后台传来的数组对象，减少代码量，代码更加简洁

**Comment by chenjiahan** [comment]
感谢反馈，评估了一下，鉴于目前日历组件的实现机制，暂时做不到直接使用外部传入的数组对象。建议还是通过文档里的方式进行使用~

**Comment by smartymoon** [comment]
> 感谢反馈，评估了一下，鉴于目前日历组件的实现机制，暂时做不到直接使用外部传入的数组对象。建议还是通过文档里的方式进行使用~

太可惜了，我还想着，滑到哪个月，用 api 动态渲染哪个月的日历。 @chenjiahan

**Comment by lm16** [comment]
搞不赢，日常另寻他法了。也是楼上这个需求
