### ISSUE TITLE
[Bug Report] stepper的默认值不是min

### ISSUE THREAD

**Issue by ChromeBing** [youzan/vant#5484]
### 设备 / 浏览器
windows 7/chrome

### Vant 版本
2.4.2-beta.0

### Vue版本
2.6.8

### 重现链接
<a href="https://jsbin.com/muyeroj/edit?html,js,output" target="_blank">https://jsbin.com/muyeroj/edit?html,js,output</a>

### 描述问题
stepper的默认值不是min

**Comment by chenjiahan** [comment]
这里是文档有误，当 v-model 不传或为 null 时，默认值是由 `default-value` 属性决定的，后续会补充下文档
