### ISSUE TITLE
uploader文件上传, 删除图片的按钮没有这个点击事件吗

### ISSUE THREAD

**Issue by zhouxx777** [youzan/vant#5485]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
有 delete 事件和 before-delete 属性喔

**Comment by zhouxx777** [comment]
> 有删除事件和before-delete属性喔
感谢, 刚开始试了一下delete事件, 发现页面初始化的时候也会执行, 最后选择了before-delete

**Comment by chenjiahan** [comment]
初始化的时候应该不会执行的，可能是写法有误？

**Comment by zhouxx777** [comment]
可能吧, 已经解决了, 感谢
