### ISSUE TITLE
[Bug Report] 上传图片无法获取到file文件信息

### ISSUE THREAD

**Issue by XWQ2018** [youzan/vant#5488]
### 设备 / 浏览器
ios移动端

### Vant 版本
2.2.15

### Vue版本
2.5.17

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/mobile.html#/zh-CN/uploader</a>

### 描述问题
uploader组件在安卓机上正常，ios点击添加图片上传，选择图片后在回调函数after-read取不到file。

**Comment by chenjiahan** [comment]
没有遇到过这个问题，可以用官方文档试下是否正常

**Comment by XWQ2018** [comment]
在电脑上试都是正常的，在项目里面放在手机看就是获取不到，安卓机就没问题，会不会是我的vant版本和vue不匹配呢？

**Comment by chenjiahan** [comment]
版本没问题哈，可以在 iOS 上调试一下看看

**Comment by XWQ2018** [comment]
用ip地址在ios手机访问就不行，不知啥情况？

**Comment by chenjiahan** [comment]
提供的信息太少，我们也没法帮你定位问题，建议自行排查该问题。组件本身是可以在 iOS 上使用的

**Comment by lozhu** [comment]
解决了吗大佬们，我也遇到同样的问题，只有一个base64
