### ISSUE TITLE
[Bug Report] 上传文件 Bug

### ISSUE THREAD

**Issue by xtuer** [youzan/vant#5489]
### 设备 / 浏览器
微信浏览器、夸克浏览器

### Vant 版本
2.4.1

### Vue版本
2.6.11

### 重现链接
<a href="https://nil.com/nil" target="_blank">https://nil.com/nil</a>

### 描述问题
在手机浏览器上，van-uploader 的 accept="image/*" 的时候可以正常选择图片，accept="image/jpg,image/jpeg" 时能看到图片，但是灰色的，不能进行选择，accept="application/pdf" 能选择非 pdf 文件。

在 PC 浏览器上这些都能正常操作。

**Comment by XWQ2018** [comment]
你这个版本在ios App上有没有出现获取不到文件信息的情况？

**Comment by xtuer** [comment]
accept="image/jpg,image/jpeg" 时 iOS Safari 里可以正常获取，Android 的浏览器不行

**Comment by XWQ2018** [comment]
打包成APP后有没有试过？

**Comment by xtuer** [comment]
没有打包成 App，只是一个 H5 页面，浏览器里访问。

**Comment by XWQ2018** [comment]
我的在项目里，用ip地址再苹果手机访问也不行，见鬼了，哈哈。

**Comment by XWQ2018** [comment]
以前在vant 1.47的还可以用

**Comment by xtuer** [comment]
可能是按钮浏览器的问题，用 file 的原生写法，结果和 Vant 里一样:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <input id="file" type="file" accept="image/jpeg">
    <div id="info">2</div>

    <script>
        // 选择文件的事件处理
        var file = document.querySelector('#file');
        file.addEventListener("change", function() {
            var curFile = file.files;
            document.querySelector('#info').innerHTML = curFile[0].name;
        });
    </script>
</body>
</html>
```

**Comment by chenjiahan** [comment]
accept 是原生属性，能否生效是由原生系统决定的，请使用系统支持的写法。

**Comment by raybon-lee** [comment]
> accept =“ image / jpg，image / jpeg”时iOS Safari里可以正常获取，Android的浏览器不行

安卓的现在调用原生的input file 拉不起来， 需要和原生做一个桥接，我们现在是这样子处理的

**Comment by raybon-lee** [comment]
> 可能是安卓浏览器的问题 (微信和夸克都试了)，用 file 的原生写法，结果和 Vant 里一样: 下面的代码，
> 
> * 能选择图片，但是不会执行 change 事件
> * 修改 accept="image/*" 的话会执行 change 事件，和期望一样
> * 去掉 accept 可以选择任意文件，执行 change 事件，选择图片执行结果和期望的一样，但是选择其他类型的文件如 a.log 得到的文件名不对
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>     <meta charset="UTF-8">
>     <title>Document</title>
> </head>
> <body>
>     <input id="file" type="file" accept="image/jpeg">
>     <div id="info">2</div>
> 
>     <script>
>         // 选择文件的事件处理
>         var file = document.querySelector('#file');
>         file.addEventListener("change", function() {
>             var curFile = file.files;
>             document.querySelector('#info').innerHTML = curFile[0].name;
>         });
>     </script>
> </body>
> </html>
> ```
这个现在安卓就是调不起来了，webkit 内核不支持 ，为了安全，关闭了这个入口
