### ISSUE TITLE
tab 的active 动态修改不i作用

### ISSUE THREAD

**Issue by GitHub-zhangshun** [youzan/vant#5490]
我tab的active默认是0，但页面过来会可能有参数，而这个参数则是active的值。我获取到这个参数 修改active值。tab选中不会改变

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by yizuochengchi** [comment]
@GitHub-zhangshun n你好 请问解决了吗 我也遇到了   onShow 重新加载设置active无效

**Comment by kuanke** [comment]
我也遇到同样的问题
