### ISSUE TITLE
[Bug Report]同时使用Swipe, SwipeItem,PullRefresh，当前的SwipeItem不是第一个，页面下拉刷新时页面会闪烁

### ISSUE THREAD

**Issue by yaowangmx** [youzan/vant#5491]
设备 / 浏览器
IOS端，安卓端正常

Vant 版本
2.2.1

Vue版本
2.6.10

重现链接

描述问题
在IOS端同时使用Swipe, SwipeItem,PullRefresh，并且当前的SwipeItem不是第一个，页面下拉刷新的时候页面会闪烁，但是在安卓上面显示正常

**Comment by chenjiahan** [comment]
麻烦提供一下 Codesandbox 复现链接

**Comment by yaowangmx** [comment]
内部项目，没有线上链接啊

**Comment by yaowangmx** [comment]
内部项目，没有线上链接啊

**Comment by chenjiahan** [comment]
Codesandbox 链接，不是你的项目链接
