### ISSUE TITLE
[Bug Report] 键盘问题

### ISSUE THREAD

**Issue by Tanglan123** [youzan/vant#5493]
### 设备 / 浏览器
移动端

### Vant 版本
2.2

### Vue版本
3.0.0-alpha.1

### 描述问题
当页面有滚动条，并且输入框在最底下，弹出NumberKeyboard或者PasswordInput键盘时，会遮挡输入框

**Comment by chenjiahan** [comment]
NumberKeyboard 不会像原生键盘一样自动将页面内容向上弹起，所以这种情况需要自行控制一下滚动条位置哈

**Comment by sldeng** [comment]
怎么解决的
