### ISSUE TITLE
tab 使用name匹配activeBUG

### ISSUE THREAD

**Issue by GitHub-zhangshun** [youzan/vant#5494]
设备 / 浏览器
所有

Vant 版本
2.2.15

Vue版本
2.6.10

重现链接
正在开发暂无链接

描述问题
首先 上一个页面进去到含有tab的页面时会在url携带一个参数。这个参数代表tab的选中项。
我在含有tab页里面的mounted里面会获取url的参数。并赋值给active来修改默认的选中项。
比如我active的默认值为0（number类型的），在tab里面没使用name字段。这时从上一个页面进入本页面，携带参数为1。tab会选中索引为1的那一项。当我在刷新页面的时候这个时候就不正确了。永远都是选中的索引为0的项。
我如果在tab中使用name 。那我默认值为active:'0'这样在页面刷新的时候是没有问题的，但初次进去页面就会有问题
我现在的解决方法是使用number  在获取query的值的时候直接转了类型赋值的

**Comment by GitHub-zhangshun** [comment]
我不知道这个是我用理解错了，还是你们更新是残留了bug。

**Comment by GitHub-zhangshun** [comment]
我之前是的项目 直接给active赋值 是没有任何问题的。但这次我还是用的同样的方式 。就出现问题了

**Comment by chenjiahan** [comment]
这个不是 bug，active 匹配必须是类型一致的，所以你需要把 query 上面的字符串转成 number 类型

1.4.8 版本会默认进行类型转换，而现在的最新版本为了支持 name 属性，则不会对 active 进行转换
