### ISSUE TITLE
[Bug Report] 在子组件中使用 Popup，当 closeable 为 true 时，点击关闭按钮，没有找到可用的回调方法

### ISSUE THREAD

**Issue by Mikasa33** [youzan/vant#5495]
### 设备 / 浏览器
Chrome

### Vant 版本
2.2

### Vue版本
2.6

### 描述问题
在子组件中使用 `Popup`，当 `closeable` 为 `true` 时，点击关闭按钮，没有找到可用的回调方法

**Comment by chenjiahan** [comment]
没有找到可用的回调方法指的是？

**Comment by Mikasa33** [comment]
点击遮罩层的时候，我是通过 `click-overlay`  方法修改值隐藏的弹出层，点击关闭按钮的时候，只有遮罩层关闭了，弹出层不会自动关闭。此时需要一个点击关闭按钮时触发的 `Event`。当然，也可能是我的用法不太对。。

**Comment by chenjiahan** [comment]
如果没绑定 v-model，请使用 value 属性和 input 事件来控制弹窗的显示

**Comment by Mikasa33** [comment]
啊。。把自己写懵逼了。十分抱歉，我自己的问题。
