### ISSUE TITLE
[Feature Request] 日历增加月份的左右切换功能，且能自动定位到某个日期

### ISSUE THREAD

**Issue by JeOam** [youzan/vant#5500]
### 这个功能解决了什么问题
在日期选择时，假如是一个过去的日期（2019/06/01）现在似乎没有办法打开日期选择时自动定位到 2019/06/01 所在的月份

### 描述您想要的解决方案
推荐一次只显示一个月份，然后左右切换，去掉默认的min-date max-date 限制

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
左右切换功能暂时没有计划支持喔，自动定位会评估一下

**Comment by JeOam** [comment]
@chenjiahan 谢谢。左右切换属于交互优化，自动定位是刚需，因为没有这个功能，现在用着 van-datetime-picker 替代着上不了日历

**Comment by chenjiahan** [comment]
已在 2.4.2-beta.1 版本支持自动定位到当前日期

**Comment by JeOam** [comment]
@chenjiahan 谢谢!
