### ISSUE TITLE
vant list 同一页面不同的入口进入，有时候能触发onload有时不能触发onload

### ISSUE THREAD

**Issue by Mariah-feifei** [youzan/vant#5502]
操作：
  A页面使用了上拉加载，分别可以从B、和C页面进入 。
  从B页面进入 ，A页面不触发onload事件  。
  从C页面进入时（在C页面需要滚动滚动条，找到点击位置），A页面onload被触发。
  问题： 我发现前一个页面滚动了滚动条，在进入页面后onload就被触发了。
  代码：
 <van-cell
            class="tc mt2"
            span="24"
            v-for="(item,index) in list"
            :key="index"
          >
</van-cell>
 methods: {
   onRefresh () {
      this.list = []
      this.notifyData = []
      this.finished = false
      this.loading = true
      this.total = 0
      this.page = 1
      if(this.loading){
        this.getNotifyMessage()
      }
    },
    onLoad () {
      setTimeout(() => {
        this.page++
        console.log(this.page)
        this.list = Array.from(new Set(this.list.concat(this.notifyData)))
        this.loading = false
        if (this.list.length >= this.Total) {
          this.finished = true
        }
      }, 300)
    },
    getNotifyMessage () {
      let params = {
        userId: this.$store.state.user.userId,
        page: this.page,
        size: '10'
      }
      getNotify(params).then(res => {
        if (res.data.Code === '-1') {
          this.$toast(res.data.Desc)
          this.Total = 0
          this.onLoad()
        } else if (res.data.Code === '1') {
          this.notifyData = res.data.Data
          this.Total = res.data.Total.toString()
          this.onLoad()
        }
      })
    },
}

mounted () {
    let _this = this
    setTimeout(function () {
        _this.onRefresh()
    },20)
  }

找了很久没有找到原因出在哪，烦劳帮忙看一下吧

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
