### ISSUE TITLE
van-cell click点击事件报错

### ISSUE THREAD

**Issue by jj-sun** [youzan/vant#5504]
在van-cell上使用 @click="" 点击事件报错。
谷歌浏览器console提示：Uncaught TypeError: Cannot read property 'click' of undefined
火狐浏览器提示：TypeError: t.listeners is undefined

`<van-list
                    v-model="loading"
                    :finished="finished"
                    finished-text="没有更多了"
                    @load="query()">
                <van-cell-group v-for="item in items"
                                :key="item.id"
                                :title="item.title"
                                border="true">
                    <van-cell :value="item.name"  @click="onClick(item)"></van-cell>
                    <van-cell :value=item.age" ></van-cell>
                    <van-divider />
                </van-cell-group>
            </van-list>`

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
