### ISSUE TITLE
下拉刷新存在bug

### ISSUE THREAD

**Issue by wanghe9583** [youzan/vant#5505]
我使用的vue开发，下拉刷新在移动端存在bug，
效果：
    在 van-pull-refresh 标签内 任何位置拖动都会执行下拉刷新
期待的效果，
    只有在 van-pull-refresh 标签内的顶部拖动才会执行下拉刷新

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by mack-wang** [comment]
苹果手机无此问题，安卓手机有此问题，最终我发现是因为我给`body`添加了`overflow-x: hidden`所导致的，删除此样式，一切恢复正常。
