### ISSUE TITLE
[Bug Report] 关于Tab组件animated属性的bug

### ISSUE THREAD

**Issue by lmx-Hexagram** [youzan/vant#5508]
### 设备 / 浏览器
chorme

### Vant 版本
2.4.1

### Vue版本
2.6.11

### 重现链接
<a href="https://github.com/lmx-Hexagram/debug_vant" target="_blank">https://github.com/lmx-Hexagram/debug_vant</a>
使用vue-cli创建的项目

### 描述问题
tab组件在添加了animated属性后,切换标签页,弹出层(Overlay,Popup等)会显示在第一个标签页中
且只要将tab的animated属性删去就一切正常

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/1146#issuecomment-392529583
