### ISSUE TITLE
Collapse 折叠面板的一些问题  

### ISSUE THREAD

**Issue by W-ChenAMG** [youzan/vant#5509]
Collapse 折叠面板     每一项 的 四周的圆角 8px怎么实现       点击前  和点击后  都是圆角  而且 .van-cell 和van-collapse-item__content  之间 是没有空隙的

**Comment by W-ChenAMG** [comment]
问题二    van-collapse-item  这个div    我需要 第一个离最上面的手机头 是12px     而 剩下的每个div上下都是8px      要求是   展开 和未展开后的距离都不能变   这个怎么实现

**Comment by W-ChenAMG** [comment]
问题3  折叠面板的箭头   我需要展开以后   在展开页的下面正中间显示       这个可以实现吗   展开之前 在原来的位置  展开后 箭头   在展开页的下面正中间显示

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by W-ChenAMG** [comment]
模板在哪里呀
