### ISSUE TITLE
[Feature Request] 日历控件增加可配置禁用日期

### ISSUE THREAD

**Issue by cl-k** [youzan/vant#5513]
### 这个功能解决了什么问题
当某些特定日期不允许选择时，可以快速配置

### 描述您想要的解决方案
对日期设置一个值，使得当前日期禁用

### 建议的API是什么样的
暂无

**Comment by chenjiahan** [comment]
可以通过 formatter 属性禁用日期喔，将 type 设置为 `disabled` 即可
