### ISSUE TITLE
[Bug Report] ImagePreview 图片预览-组件调用不生效

### ISSUE THREAD

**Issue by misterwang031** [youzan/vant#5518]
### 设备 / 浏览器
安卓/chrome

### Vant 版本
2.4.1

### Vue版本
2.6.10

### 重现链接
没有链接

### 描述问题
通过组件方式调用ImagePreview，v-model不生效。
<image-preview v-model="visible" :images="imgUrlList" :start-position="index" />

**Comment by chenjiahan** [comment]
麻烦提供下 codesandbox 复现链接

**Comment by misterwang031** [comment]
codesandbox ：Resolving Dependencies...   然后就卡死在这里，最后：
TypeError: Could not fetch dependencies, please try again in a couple seconds: Failed to fetch

**Comment by chenjiahan** [comment]
可以换 jsbin 试试喔
