### ISSUE TITLE
[Feature Request] 折叠面板 关于圆角的一些问题

### ISSUE THREAD

**Issue by W-ChenAMG** [youzan/vant#5523]
### 这个功能解决了什么问题
还是和之前一样 明显看到 是个直角和圆角切换闪 有没有可能把这个动画 速度啥的改改 实现不闪   .van-collapse-item {
    border-radius: 8px;
    overflow: hidden;
}

### 描述您想要的解决方案
还是和之前一样 明显看到 是个直角和圆角切换闪 有没有可能把这个动画 速度啥的改改 实现不闪   .van-collapse-item {
    border-radius: 8px;
    overflow: hidden;
}

### 建议的API是什么样的
wu

**Comment by chenjiahan** [comment]
请勿反复提重复 issue
