### ISSUE TITLE
Field组件怎么设置字体颜色

### ISSUE THREAD

**Issue by gu-xiaohui** [youzan/vant#5527]
Field scoped状态下组件如何设置文本框字体颜色

**Comment by chenjiahan** [comment]
https://vue-loader.vuejs.org/zh/guide/scoped-css.html#%E6%B7%B7%E7%94%A8%E6%9C%AC%E5%9C%B0%E5%92%8C%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F
