### ISSUE TITLE
list组件内容不满一屏自动加载简直是一个巨坑！与其它组件契合度低！

### ISSUE THREAD

**Issue by peiwenM** [youzan/vant#5530]
**触发前提条件：**
①同时使用PullRefresh组件和list组件：
```
<van-pull-refresh>
  <van-list></van-list>
</van-pull-refresh>
```
②首屏请求数目不能占满整屏
③下拉刷新页面，清空list，重新请求数据

**bug描述：**
数据重复加载！！！getData()方法被触发两次。
注：loading、finished、isrefresh确定有正确控制，因为多次测试下只有在条目不满屏的情况才会出现

**主要代码：**
**HTML：**
```
<van-pull-refresh v-model="isrefresh" @refresh="onRefresh">
 <van-list
  v-model="loading"
  :finished="finished"
  :offset="50"
  :immediate-check="false"
  @load="getData">
    <div v-for="(item, index) in goodsList" :key='index'  :index=index></div>
 </van-list>
</van-pull-refresh>
```

**js:**
```
onRefresh() {
  setTimeout(() => {
    this.$toast('刷新成功');
    this.page = 1;
    this.goodsList = [];
    this.isrefresh = false;
    this.getData();
   },500);
},

getData() {
// 处理数据进goodsList数组中
}
```

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/72061723-6dee0f00-3311-11ea-8357-0e9650cf34f5.png)

请仔细看文档

**Comment by chenjiahan** [comment]
如果手动触发了 getData，请将 loading 设置为 true

**Comment by peiwenM** [comment]
咦 将 loading 设置为 true 好使：）

**Comment by Farb** [comment]
@chenjiahan loading=true 好使  谢谢

**Comment by websrookie** [comment]
> ![image](https://user-images.githubusercontent.com/7237365/72061723-6dee0f00-3311-11ea-8357-0e9650cf34f5.png)
> 
> 请仔细看文档

如果数据本来就只有一两条屏幕不能铺满这个如何解决是好呢？大佬

**Comment by chenjiahan** [comment]
@websrookie 只有一两条的话，请求完成后把 finished 设置为 true，表示加载完成

**Comment by tianlong1998** [comment]
安卓环境下 只会加载一次 onload 不会铺满整屏
