### ISSUE TITLE
[bug report]Calendar组件在type为single时，自定义bottomInfo选中后消失

### ISSUE THREAD

**Issue by cherishh** [youzan/vant#5533]
设备 / 浏览器:
Mac OS 10.14.6
Chrome & 移动端

Vant 版本：
2.4.1

Vue版本：
2.6.10

描述问题：
单日期选择模式（type='single'）下给组件增添自定义bottomInfo，在日期未选中时bottomInfo可以正常显示；而一但选中某日期，被选择日期的bottomInfo消失。审查时发现被选中日期没有bottomInfo节点。
如下图，其中8、9、10、11均有bottomInfo，其中8号因为是过去的时间，11号因为已经约满而设为不可选。9、10号可选，但选中任意日期，bottomInfo消失，并且切换其他日期也不会再出现。
<img width="375" alt="1" src="https://user-images.githubusercontent.com/20265415/72065001-20c16b80-3318-11ea-81e7-e43482d840d9.png">
<img width="348" alt="2" src="https://user-images.githubusercontent.com/20265415/72065022-28811000-3318-11ea-932c-c49d3f724118.png">

目前通过监听`select`事件，纯DOM方式添加节点解决，但仍有两种情景无能为力：
1. 初始渲染默认选中当天，而当天正好可约（此时日期被选中，却没有手动触发`select`）。
2. 用户滚动到下个月再滚动回来的时候，已选日期的bottomInfo也会消失，尝试解决发现监听不到组件的`scroll`。

**Comment by chenjiahan** [comment]
现在确实是有这个问题，后续会看下怎么解决

**Comment by cherishh** [comment]
> 现在确实是有这个问题，后续会看下怎么解决

请问现在有没有什么办法可以hack解决，项目下周就上线了

**Comment by chenjiahan** [comment]
今天应该会发一个修复版本

**Comment by chenjiahan** [comment]
已在 2.4.2-beta.2 版本修复

**Comment by cherishh** [comment]
感谢极速响应👍
