### ISSUE TITLE
NumberKeyboard 在ios13 safari浏览器，快速点击数字按钮页面会被放大！

### ISSUE THREAD

**Issue by SJanJan** [youzan/vant#5537]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

--- Vue 2.6

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by SJanJan** [comment]
怎么能让它不被放大呢，会严重影响输入和用户体验哦

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
