### ISSUE TITLE
轮播图van-swipe 懒加载图片v-lazy 使用报错Failed to resolve directive: lazy

### ISSUE THREAD

**Issue by angelpig** [youzan/vant#554]
我是外链映入vant

**Comment by chenjiahan** [comment]
使用 Lazyload 前需要手动注册
```
Vue.use(vant.Lazyload);
```

**Comment by angelpig** [comment]
了解了，谢谢

**Comment by xtcel** [comment]
我使用Vue.use(vant.Lazyload);不能导入提示 Cannot read property 'install' of undefined
    at Function.Vue.use。
而
import lazyload from 'vant/lib/lazyload'
Vue.use(lazyload)
这样可以
