### ISSUE TITLE
滚动导航点击第二个tab回弹至第一个tab

### ISSUE THREAD

**Issue by PanP7** [youzan/vant#5542]
**设备 / 浏览器**
chrome

**Vant 版本**
2.4.1

**Vue版本**
2.5.2

**重现链接**
没有链接

**描述问题**
demo代码贴的不完整，点击tab回弹至前一个tab，是否有哪些地方需要注意？

**Comment by chenjiahan** [comment]
请使用 https://youzan.github.io/vant-issue-generater/dist/#/ 创建

**Comment by AlanFenng** [comment]
你们这个问题解决了就关闭，我也遇到同样的问题。

**Comment by earthaYan** [comment]
> 你们这个问题解决了就关闭，我也遇到同样的问题。

有解决方案么，试了下tab一多就会出现这种问题，

**Comment by simpleAndyoung** [comment]
iphone 13 会出现这种问题。PC调试不会 ，手机会
