### ISSUE TITLE
[Bug Report] vant 2.4.2 picker 渐变选中问题

### ISSUE THREAD

**Issue by wynova** [youzan/vant#5544]
### 设备 / 浏览器
iphone 6s ios 13 

### Vant 版本
2.4.2-beta.1

### Vue 版本
3.0.0-alpha.1

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/picker</a>

### 描述问题
picker组件 在 iphone 6s ios 13 系统中，无法正确显示选中高亮，选项色值全部是color：#000，渐变代码不兼容该系统
建议解决方案：
1、写兼容性代码
2、继续沿用1.x的方案，未选中的灰色.van-picker-column__item{ color: #969799 }，选中的 .van-picker-column__item--selected{ color: #000 }

以上仅供参考

**Comment by wynova** [comment]
.van-picker__mask的background-image 渐变代码不兼容

**Comment by chenjiahan** [comment]
确定是 iOS 13 吗？13 不应该有兼容性问题

**Comment by wynova** [comment]
> 确定是 iOS 13 吗？13 不应该有兼容性问题

我们开发的时候，6s的版本确实存在这个问题

**Comment by wynova** [comment]
> 确定是 iOS 13 吗？13 不应该有兼容性问题

上班之后我可以截图你看看

**Comment by chenjiahan** [comment]
好

**Comment by chenjiahan** [comment]
@wynova 能截个图吗

**Comment by wynova** [comment]
> @wynova 能截个图吗
对不起，我这边验证了，你的没有问题，我们这边用的有问题！sorry

**Comment by wynova** [comment]
> > @wynova 能截个图吗
> > 对不起，我这边验证了，你的没有问题，我们这边用的有问题！sorry

@chenjiahan

**Comment by chenjiahan** [comment]
好的👌

**Comment by StarkCwx** [comment]
> 我们这

我们也有同样的问题，可以请教一下是什么用法有问题吗？

**Comment by StarkCwx** [comment]
> > > @wynova 能截个图吗
> > > 对不起，我这边验证了，你的没有问题，我们这边用的有问题！sorry
> 
> @chenjiahan

我们也有同样的问题，可以请教一下是什么用法有问题吗？
