### ISSUE TITLE
[Bug Report] Tabbar 标签栏

### ISSUE THREAD

**Issue by liuzhichao2017** [youzan/vant#5547]
**设备 / 浏览器**
PC端chrome/iOS

**Vant 版本**
2.2.16

**Vue版本**
2.6.10

**重现链接**
没有链接

**描述问题**
使用路由模式的时候将路由跳转地址写在van-tabbar-item中（如<van-tabbar-item to="home2">)时，比如从**首页**跳到要另外一个tabbar页面**视频**页面，因为设计原因**视频**页面**没有底部栏**tabbar，所以在在**视频**页面左上角加了一个返回键调用### **this.$route.go(-1)**返回上一级页面，但问题来了，此时点击返回键无法正常返回上一个页面。
最后只能用监听底部栏点击的事件，用**this.$router.push**才解决改问题。

**Comment by chenjiahan** [comment]
没遇到过这个问题呢，麻烦提供一下 codesandbox 复现链接
