### ISSUE TITLE
[Bug Report] 组件冲突

### ISSUE THREAD

**Issue by amwydqqk** [youzan/vant#5549]
### 设备 / 浏览器
谷歌 74

### Vant 版本
2.0.1

### Vue 版本
2.5.6

### 重现链接
没有链接

### 描述问题
下拉刷新组件（PullRefresh）内使用弹出层组件（popup）跟选择器组件（picker）组合弹层，选择器组件的向下滑动会促发下拉刷新组件的下拉刷新。

**Comment by chenjiahan** [comment]
可以把 Popup 放到 body 底下，防止事件冲突：

```html
<van-popup get-container="body" />
```

或者这样阻止事件冒泡：

```html
<van-picker @touchmove.native.stop />
```
