### ISSUE TITLE
地址编辑 如何新增表单项？

### ISSUE THREAD

**Issue by lejsure** [youzan/vant#555]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@lejsure 目前不支持噢，后续会考虑优化地址组件的定制能力
--

**Comment by chenjiahan** [comment]
AddressEdit 在 0.12.6 版本中加入了一个默认 slot，可以插入一定的表单内容
