### ISSUE TITLE
[Feature Request] uploader组件需求

### ISSUE THREAD

**Issue by wynova** [youzan/vant#5550]
### 这个功能解决了什么问题
设置为摄像头的时候，可以定制前置摄像头还是后置摄像头

### 描述您想要的解决方案
增加一个参数，来标识前置摄像头还是后置摄像头

### 建议的API是什么样的
只有capture='camera'的时候设置才能生效

**Comment by chenjiahan** [comment]
可以试试 capture="user"

**Comment by wynova** [comment]
> 可以试试 capture="user"

OK
