### ISSUE TITLE
switch开关

### ISSUE THREAD

**Issue by YouthShouting** [youzan/vant#5551]
switch组件：点击开关时存在点透的bug，有个需求是点击开关传入自定义参数

**Comment by YouthShouting** [comment]
这个功能解决了什么问题
在异步控制中绑定的input事件中，只接收一个参数，不好监听是哪个开关触发的事件

描述您想要的解决方案
在异步控制中绑定的input事件中，增加一个参数

建议的API是什么样的
在异步控制中绑定的input事件中，增加一个参数，一个为cheaked值，另一个为绑定ID

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
