### ISSUE TITLE
[Feature Request] Calendar 自动滚动到当前选中的日期的位置优化

### ISSUE THREAD

**Issue by JeOam** [youzan/vant#5552]
### 这个功能解决了什么问题
目前日期的自动滚动，假设当前日期是 09/30，min-date 为八月份的，则会出现最上的 title 为 八月份的，而不是当前日期的九月份

![image](https://user-images.githubusercontent.com/1294533/72218325-f15b6a80-3574-11ea-8feb-71ea07b450cf.png)

### 描述您想要的解决方案
无

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
后续会修正下

**Comment by chenjiahan** [comment]
已在 2.4.2 版本修复

**Comment by JeOam** [comment]
谢谢!

**Comment by shaodushu** [comment]
@chenjiahan 这个功能，能不能加个开启关闭。日历平铺时，跳至有日历组件页面时，页面不在顶部。
