### ISSUE TITLE
van-image-preview预览加了时间戳的图片，无法显示图片，一片漆黑

### ISSUE THREAD

**Issue by value-red** [youzan/vant#5554]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by value-red** [comment]
在调用预览多次后，再次预览图片会显示不出来，但是close打印出来的图片的url是正常的，请问这个改怎么解决

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
