### ISSUE TITLE
[Bug Report] AddressEdit 地址编辑组件 删除弹窗内容可以自定义吗?

### ISSUE THREAD

**Issue by wswww** [youzan/vant#5556]
### 设备 / 浏览器
chrome

### Vant 版本
2.4.2-beta.2

### Vue 版本
3.0.0-alpha.1

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/address-edit" target="_blank">https://youzan.github.io/vant/#/zh-CN/address-edit</a>

### 描述问题
AddressEdit 地址编辑组件 删除弹窗内容可以自定义吗?默认是'确定要删除么',我需要改成'确定要删除吗'

**Comment by wswww** [comment]
![image](https://user-images.githubusercontent.com/27074739/72231608-6b343800-35f7-11ea-8235-f7ce56ea7b27.png)

**Comment by chenjiahan** [comment]
这里用『吗』会合适一点，后续会直接在组件内改掉

也可以通过 Locale 组件修改，参见 https://github.com/youzan/vant/issues/5482

**Comment by chenjiahan** [comment]
已在 2.4.2 版本更新文案

**Comment by wswww** [comment]
非常感谢您 @chenjiahan
