### ISSUE TITLE
[Bug Report] ImagePreview图片预览组件，在预览的时候图片不显示

### ISSUE THREAD

**Issue by value-red** [youzan/vant#5557]
### 设备 / 浏览器
chrome，移动端

### Vant 版本
2.4.1

### Vue 版本
2.6.10

### 重现链接
<a href="https://www.icarephone.com/wechat/#/pricetag" target="_blank">https://www.icarephone.com/wechat/#/pricetag</a>

### 描述问题
当我修改图片地址的数组后，点击预览图片，预览出来的图片为一片黑色，操作复现的步骤为，进入页面登录，选择专区，选择一款机型，然后预览价格牌图片，关闭预览，再输入价格，点击生成价格牌的按钮，再点击新生成的图片预览，就会出现预览不显示图片的状况

**Comment by QuincyX** [comment]
+1

**Comment by firefirstfu** [comment]
+1

**Comment by chenjiahan** [comment]
能否提供下复现的代码？

**Comment by value-red** [comment]
希望加载失败的时候有相关的回调方法，或者相关的图标提示

**Comment by value-red** [comment]
> 能否提供下复现的代码？
由于项目对此问题做了相应的修复，可能暂时没有线上复现的办法，可能是我图片路径后加了时间戳，作为图片缓存处理的影响

**Comment by chenjiahan** [comment]
@value-red 所以是图片加载失败了吗？

**Comment by value-red** [comment]
> @value-red 所以是图片加载失败了吗？
应该是吧，但是没有相关提示，close的方法是能返回该图片的路径，但是并不知道图片为何加载不出来，就暂且认为是失败，在下才疏学浅，抱歉打扰了

**Comment by value-red** [comment]
> > @value-red 所以是图片加载失败了吗？
> > 应该是吧，但是没有相关提示，close的方法是能返回该图片的路径，但是并不知道图片为何加载不出来，就暂且认为是失败，在下才疏学浅，抱歉打扰了

还有一个问题就是，一加载不出来图片，后续生成的新图片也加载不了，重新挂载组件才可以预览，但是一出现加载不出来图片，暂时就没解决办法

**Comment by chenjiahan** [comment]
我试了下倒没问题这个，这是我的测试代码：

```js
const images = [
  'https://img.yzcdn.cn/vant/apple-1.jpg',
  'https://img.yzcdn.cn/vant/apple-2.jpg',
  'https://img.yzcdn.cn/vant/apple-3.jpg',
  'https://img.yzcdn.cn/vant/apple-4.jpg'
];

const errorImage = ['xxx', 'xxx'];

ImagePreview({
  images: errorImage
});

setTimeout(() => {
  ImagePreview({
    images
  });
}, 2000);
```

**Comment by chenjiahan** [comment]
下个版本会优化下图片加载失败时的样式，变成这样：

![image](https://user-images.githubusercontent.com/7237365/72310983-3808ac00-36be-11ea-9a42-d4d347620789.png)

**Comment by value-red** [comment]
> 下个版本会优化下图片加载失败时的样式，变成这样：
> 
> ![image](https://user-images.githubusercontent.com/7237365/72310983-3808ac00-36be-11ea-9a42-d4d347620789.png)



> 下个版本会优化下图片加载失败时的样式，变成这样：
> 
> ![image](https://user-images.githubusercontent.com/7237365/72310983-3808ac00-36be-11ea-9a42-d4d347620789.png)

好的，谢谢回复，可能我测的是移动端的手机，上周五开始发现这个问题的，安卓和苹果都是在wifi下，也有出现相似的情况，找不到相关原因，所以反馈一下，可能是组件调用的情况吧，目前测试这两种方法都暂时没有测出来，vant版本2.3.3

**Comment by chenjiahan** [comment]
好的👌 图片加载失败时的样式已在 2.4.2 版本发布
