### ISSUE TITLE
[Feature Request] DropdownMenu 下拉菜单 建议增加按钮或者slot

### ISSUE THREAD

**Issue by lshz0088** [youzan/vant#5558]
### 这个功能解决了什么问题
下拉框选择后，希望自定义选择后结果的样式

### 描述您想要的解决方案

Example: 如下图为我希望实现的效果

![image](https://user-images.githubusercontent.com/27722002/72232362-b6e8e080-35fb-11ea-8ba1-1229476733d9.png)

> 选中后，可以显示一个带关闭按钮的tag

![image](https://user-images.githubusercontent.com/27722002/72232371-be0fee80-35fb-11ea-926f-1b3306927bee.png)

### 建议的API是什么样的
建议可以使用一个solt实现自定义选中后样式

**Comment by chenjiahan** [comment]
目前是有 title 插槽的，不过由于实现方式的原因，目前不支持动态渲染。这个需求应该不太好实现
