### ISSUE TITLE
文档打不开了

### ISSUE THREAD

**Issue by csj8520** [youzan/vant#5559]
文档打不开了
https://youzan.github.io/vant

**Comment by chenjiahan** [comment]
可能是国内访问 Github 网络波动，可以访问我们的 gitee 镜像:

http://vant-contrib.gitee.io/vant

**Comment by csj8520** [comment]
> 可能是国内访问 Github 网络波动，可以访问我们的 gitee 镜像:
> 
> http://vant-contrib.gitee.io/vant

多谢
