### ISSUE TITLE
stepper点击增加，达不到最大值增加按钮就不可点击了

### ISSUE THREAD

**Issue by cocola369** [youzan/vant#5561]
代码：	<van-stepper
					 :value="object.amount"
					 :decimal-length="2"
					 :step="1.00"
					 :max="object.transactableQty"
					 min="0.00"
					/>
点击增加到不可点击后 页面代码：
<div data-v-0265f33a="" class="van-stepper">
<button type="button" class="van-stepper__minus"></button>

<input type="number" role="spinbutton" aria-valuemax="721" aria-valuemin="0.00" aria-valuenow="8.00" class="van-stepper__input">

<button type="button" class="van-stepper__plus van-stepper__plus--disabled"></button></div>

**Comment by cocola369** [comment]
<van-stepper
					 :value="object.amount"
					 :decimal-length="2"
					 :step="1.00"
					 :max="object.transactableQty"
					 min="0.00"
					/>

**Comment by cocola369** [comment]
`<van-stepper
					 :value="object.amount"
					 :decimal-length="2"
					 :step="1.00"
					 :max="object.transactableQty"
					 min="0.00"
					/>`

**Comment by cocola369** [comment]
`<div data-v-0265f33a="" class="van-stepper"><button type="button" class="van-stepper__minus"></button>

<input type="number" role="spinbutton" aria-valuemax="721.00" aria-valuemin="0.00" aria-valuenow="8.00" class="van-stepper__input">

<button type="button" class="van-stepper__plus van-stepper__plus--disabled"></button></div>`

**Comment by cocola369** [comment]
`<div data-v-0265f33a="" class="van-stepper"><button type="button" class="van-stepper__minus"></button><input type="number" role="spinbutton" aria-valuemax="721" aria-valuemin="0.00" aria-valuenow="8.00" class="van-stepper__input"><button type="button" class="van-stepper__plus van-stepper__plus--disabled"></button></div>`

**Comment by cocola369** [comment]
[https://pan.baidu.com/s/1P3mVVx9lRZVlkJnZ1BpQFA](url)

**Comment by cocola369** [comment]
https://pan.baidu.com/s/1P3mVVx9lRZVlkJnZ1BpQFA

**Comment by cocola369** [comment]
"vant": "^2.3.3"

**Comment by chenjiahan** [comment]
试了下没问题，能提供一下复现问题的 codesandbox 链接吗
