### ISSUE TITLE
Vant 2020 年上半年开发计划 ✨

### ISSUE THREAD

**Issue by chenjiahan** [youzan/vant#5565]
## 发布 Vant 3.0 🔥

在 2020 年上半年，我们的主要目标是发布 Vant 3.0 版本，主要包含以下更新：

- 基于 Vue 3.0 开发，使用 [Composition API](https://vue-composition-api-rfc.netlify.com/) 重构所有组件，增强组件间的逻辑复用并减少包体积。
- 使用 TypeScript 重构所有代码，提供更完善的类型支持。
- 增加更多实用的基础组件，如 Form、Popover。
- 完善组件交互，如 Tab 增加滑动切换动画，ImagePreview 支持原生级的手势操作。
- 提供更好的文档、更丰富的示例，文档无止境。

由于 Vue 3.0 已经发布了第一个 alpha 版本，Vant 3.0 也将于近期正式启航。我们会在 [next](https://github.com/youzan/vant/tree/next) 分支进行 3.0 版本的开发工作，同时在 dev 分支持续维护 2.x 版本。
    
## 持续优化 Vant Cli 🌟

在 2019 年年底，我们悄悄发布了 [Vant Cli](https://github.com/youzan/vant/tree/dev/packages/vant-cli)，一个开箱即用的 Vue 组件库搭建工具（可以将它理解为面向组件库的 Vue Cli），其中包含了我们在开发 Vant 过程中所积累的工程化最佳实践。你可以使用 Vant Cli 搭建一套基于 Vant 的业务组件库，或是从零开始搭建一套 Vue 基础组件库。

Vant 从 2.3 版本开始接入了 Vant Cli 进行构建，同时 Vant Cli 也已在有赞内部的多套业务组件库中落地。

后续我们会持续优化 Vant Cli，主要目标是提供更丰富的配置项以及完善文档。希望它能够帮助大家更轻松地搭建一套完备的组件库。

## Vant Weapp 迭代 & 探索 🏃

上个月我们刚刚发布了 [Vant Weapp 1.0 版本](https://tech.youzan.com/vant-weapp-1-0-fa-bu/)，对齐了 Vant 2.0 的大部分功能，并基于 CSS Variables 提供了自定义主题的能力。

后续我们对 Vant Weapp 的规划是在 1.0 版本的基础上持续迭代，提高性能和稳定性，并跟进微信小程序框架的升级，探索小程序组件更多的可能性。

**Comment by MBearo** [comment]
可以参加新版的开发么？

**Comment by chenjiahan** [comment]
可以的喔，欢迎 PR

**Comment by ChangeZhang** [comment]
加油

**Comment by leecheehl** [comment]
可以提供改进意见么

**Comment by chenjiahan** [comment]
@leecheehl 这两个问题可以单独提 issue 反馈哈

**Comment by richard1015** [comment]
@chenjiahan   👍

**Comment by chenjiahan** [comment]
^_^

**Comment by lmfuture** [comment]
第一次看到这个平台就有耳目一新的感觉，功能完善，用户体极好。转眼间已经用了半年了，期间遇到问题楼主也积极的回答了问题，期待明年的迭代，非常感谢，祝Vant团队新年快乐！！！

**Comment by chenjiahan** [comment]
哈哈~ 感谢支持，新年快乐哟

**Comment by itben-cn** [comment]
官方有计划出 Vant Weapp的支付宝小程序版吗，一直在用Vant Weapp做微信小程序的开发，最近准备转支付宝小程序，通过一些工具将Vant Weapp转换成支付宝版发现bug还是不少，很多的组件无法呈现出百分百的效果。

**Comment by chenjiahan** [comment]
> 官方有计划出 Vant Weapp的支付宝小程序版吗

暂时没有喔，可以试试 https://github.com/ant-move/Vant-Aliapp

**Comment by hengshanMWC** [comment]
找了那么久，还是vant的日历组件看得舒服

**Comment by byan** [comment]
有 PC 版的 Vue 吗？zent 是用 React 的~

**Comment by chenjiahan** [comment]
> 有 PC 版的 Vue 吗？zent 是用 React 的~

没有喔

**Comment by wang475293638** [comment]
加油 喜欢 vant    希望越做越好！！

**Comment by wang475293638** [comment]
希望能增加一个时间范围选择的组件

**Comment by wykolor** [comment]
从自己的第一个项目开始就用vant 真心感谢vant团队 而且一直在更新和优化 庆幸自己一开始选择对了UI组件库也感谢vant团队对该组件库的持续支持，继续加油！祝越做越好

**Comment by chenjiahan** [comment]
感谢支持 ^_^

**Comment by a1455047031** [comment]
有没有啥群的 有问题好找大佬请教

**Comment by chenjiahan** [comment]
@a1455047031 README 文档的最底下有入群方式

**Comment by yogwang** [comment]
今天刚开始使用VantUI，但是在修改主题配色的感觉很多重复工作，每一个组件都要独自设定，
如果修改@green的话，虽然全部的primary-background都会变成我修改的颜色，但是部分success的颜色也会变成我修改的颜色，例如notify组件。
但是我只需要一种统一的主题色。其实增加一个@primary-color就行了，默认是@green，如果需要修改使用modifyVars修改@primary-color就可以，可以省略很多重复操作。

**Comment by chenjiahan** [comment]
@yogwang 感谢反馈，这块应该会在下个大版本梳理下

**Comment by wufei1310** [comment]
还是第一次在github上感受到这个浓烈的交流气息，vant ，真赞！

**Comment by jikoy** [comment]
很好。能增加table组件就完美了。

**Comment by Airkro** [comment]
picker 这个组件实在是难用，经常要二次定制才能满足需求

**Comment by GJune** [comment]
> picker 这个组件实在是难用，经常要二次定制才能满足需求

是的，实际项目里实在用不起来，你是否有定制好的可以共享出来？

**Comment by Airkro** [comment]
@GJune 自己弄的封装分散在不同项目里，很零碎，能有官方实现最好

Picker 现有的那些 `get*(),set*()` 方法用起来相当麻烦，作为 Vue 组件应该考虑用 `v-model` 提供更多便利。不同格式的 `options` 可与考虑自动判别 `array od string` 和 `array of object`，自动处理级联。并且建议内置 `popup`。

**Comment by chenjiahan** [comment]
>  很好。能增加 table 组件就完美了。

Table 暂时没有计划支持哈

> 作为 Vue 组件应该考虑用 v-model 提供更多便利

Picker 的 v-model 后续会考虑加上，可以提一个单独的 issue 反馈呢

> 不同格式的 options 可与考虑自动判别 array od string 和 array of object，自动处理级联

现在已经支持级联了，可以看下

> 建议内置 Popup

会考虑加上

**Comment by liushangdev** [comment]
weapp 上传组件，图片可以预览，如果视频也可以预览就完美了，老哥

**Comment by maicWorkGithub** [comment]
现在的和以后的能不能都加个声明文件，这样对IDE会更加友好一点。

**Comment by chenjiahan** [comment]
> weapp 上传组件，图片可以预览，如果视频也可以预览就完美了

视频预览暂时没有计划支持呢

> 现在的和以后的版本能不能都加个声明文件

具体是什么声明文件

**Comment by rukihu** [comment]
想问一下官网上的设计资源sketch啥时候更新，感谢！

**Comment by chenjiahan** [comment]
> 想问一下官网上的设计资源sketch啥时候更新

设计同学在整理，目前还没有具体的时间喔

**Comment by maicWorkGithub** [comment]
> > 现在的和以后的版本能不能都加个声明文件
> 
> 具体是什么声明文件

就像这个 https://github.com/ElemeFE/element/tree/dev/types。先谢谢啦

**Comment by zy19940510** [comment]
看了下next分支的源码，好像目前还没有使用到composition-api，不过组件也是基于函数式的，大概什么时候会引入composition-api呀，想学习下。

**Comment by chenjiahan** [comment]
> 就像这个 https://github.com/ElemeFE/element/tree/dev/types 。先谢谢啦

类型定义文件一直都有的喔

> 大概什么时候会引入 composition-api 呀

目前有几个文件是使用 composition api 的，参见：https://github.com/youzan/vant/tree/next/src/hooks

现在 Vue 3.0 的阶段还处于 alpha 的早期，所以还没正式开工，应该快了

**Comment by maicWorkGithub** [comment]
类型定义文件找到了，但是为啥element-ui的webstorm就能识别，vant的就不行呢？
![image](https://user-images.githubusercontent.com/15863224/77146110-41026900-6ac5-11ea-8b13-510c60edf05b.png)
![image](https://user-images.githubusercontent.com/15863224/77146132-4d86c180-6ac5-11ea-9452-cb1a106a2609.png)

我知道这不是你们的问题，能不能教教我，谢谢

**Comment by chenjiahan** [comment]
这个应该是 Webstorm 检测机制的问题，它只能识别特定格式导出的组件，在 vscode 里的话可以用 vetur 插件来识别

**Comment by van-chin** [comment]
赞，准备跟着Vant 3.0 版本学习，官方大概会在vue 3.0 beta版本正式启动还是RC版本才开始启动开发

**Comment by chenjiahan** [comment]
大概率 beta 就会正式启动咯

**Comment by maicWorkGithub** [comment]
> To improve code completion for different Vue.js component libraries, we have invented a special format of metadata, called web-types. web-types describe the library's components and their directives. In the future, it will support more types of information.

> If you're maintaining your own Vue.js component library, you can add description of the components in the web-types format to your module. To help the IDE to locate this file, a link to it should be added to the "web-types" field in library package.json.

> On http://github.com/JetBrains/web-types you can find the JSON schema, scripts that you can use to generate the metadata in the required format, as well as the latest versions of descriptions for the most popular Vue.js component libraries

@chenjiahan 我问Jetbrains了，他们这样回复的，你们愿意加这些配置么（先拜托了

**Comment by chenjiahan** [comment]
@maicWorkGithub 可以滴，单独提个 issue 把，我们后续支持

**Comment by richard1015** [comment]
@chenjiahan 
个人 cli 的两个建议  : )

- site 下的 desktop、mobile中的 router.js 可以再搭配 懒加载和预加载优化一波 

``` javascript
...
routes.push({
    path: '/' + item.name,
    components: {      
      default: Index,
      main: () => import(
        /* webpackPrefetch: true */
        /* webpackChunkName: "doc-[request]" */`./view/${pkgName}.vue`)
    },
    name: item.name
  });
...
```

- webpack 构建方面可以再加入 HappyPack 和  DLLPlugin 、DLLReferencePlugin 这些。构建速度应该会更快

**Comment by chenjiahan** [comment]
@richard1015 感谢建议~

1. 现在没使用懒加载的原因是异步 router 的 SPA 对 algolia 建立索引不是很友好，而且组件体积不大，一次性加载完也才 100 多 kb，没有异步组件的情况下切换路由反而更流畅。
2. 编译速度已经够快了，大型组件库也就 10~20 秒左右，等 webpack 5 出了还会更快。而 Dll 更适合代码量大的业务项目，牺牲复杂度换编译速度。

**Comment by 1025431504** [comment]
vant cli 是专门用来开发app的脚手架吗，可以支持打包成android 或者 ios 的 apk吗

**Comment by chenjiahan** [comment]
@1025431504 不是开发 APP 的呢，是开发组件库用的

**Comment by 1025431504** [comment]
在uniapp中引入使用没有样式 
![image](https://user-images.githubusercontent.com/48747641/77499822-20079280-6e8e-11ea-87de-ae55a7ea1e82.png)
![image](https://user-images.githubusercontent.com/48747641/77499837-2c8beb00-6e8e-11ea-8aa3-cc805921e8b9.png)
![image](https://user-images.githubusercontent.com/48747641/77499875-4af1e680-6e8e-11ea-8844-b50c95992ca1.png)
![image](https://user-images.githubusercontent.com/48747641/77499886-51805e00-6e8e-11ea-98e4-6b75d3ef0472.png)
新建的一个demo 按照步骤来的 没找到原因 是不是和uni-ui的样式冲突了

**Comment by van-chin** [comment]
@chenjiahan vant-cli 适合用来开发PC 的UI组件库么，如果用vant-cli 需要怎么去调整呢

vant-cli 的文档是否可以完善一下

**Comment by chenjiahan** [comment]
@van-chin 现阶段还不太适合开发 PC 端组件库呢，以后可能会支持下

**Comment by mw248** [comment]
@chenjiahan Vant Weapp中近期会考虑增加AddressEdit,AddressList,Contact,Coupon,Sku这些业务组件吗？
对开发微商城、会员系统等会很实用，特别是疫情影响，对电商交易需求更大，有这些业务组件可以大大加速开发，帮助到商家，渴望中~

**Comment by chenjiahan** [comment]
@mw248 暂时没有计划嘞，我们目前的精力还是以增加基础组件为主

**Comment by missop** [comment]
希望官网能够有复制代码按钮，可以一键复制

**Comment by chenjiahan** [comment]
> 希望官网能够有复制代码按钮，可以一键复制

考虑会在 3.0 版本的文档里加上👌

**Comment by hzyyy** [comment]
再次吐槽～picker 真的好难用···

**Comment by xts871722743** [comment]
期望能加个移动端的瀑布流组件就完美了

**Comment by chenjiahan** [comment]
> picker 真的好难用···

Picker 到 3.0 应该会整整

> 期望能加个移动端的瀑布流组件就完美了

瀑布流加载用 List 组件哈，布局用 flex 写下就行

**Comment by stys35** [comment]
非常感谢vant，中国开源之光，前端泥石流，吊打各种大厂

**Comment by chenjiahan** [comment]
o(*￣▽￣*)ブ

**Comment by ZhengXiaowei** [comment]
第一次使用后就喜欢了，在后来的项目中也一直在用，维护和解决问题的效率一直杠杠的。继续加油！

**Comment by hzyyy** [comment]
date-picker 时间选择组件，希望能够优化赋值；v-model 最好取的是String 类型的日期时间，而不是new Date()；

**Comment by hejianxian** [comment]
hello vant 

Vant 是我们公司H5开发的首选ui库，然后我们这边会采用你们官网上的设计资源，但是发现目前的资源好像有段时间没更新了，请问你们这边有更新设计资源的计划吗？

**Comment by chenjiahan** [comment]
> 第一次使用后就喜欢了，在后来的项目中也一直在用

感谢资瓷~

> date-picker 时间选择组件，希望能够优化赋值

这个暂时木有计划调整，不过在下个大版本里 DatetimePicker 会做一些优化

> 请问你们这边有更新设计资源的计划吗？

Sketch 在梳理中咯

**Comment by mhxy13867806343** [comment]
hello nav-bar中间能否也可以自定义 类似如下的
![333333](https://user-images.githubusercontent.com/4418166/79034936-1c913c80-7bec-11ea-8f36-36b57592575d.png)

**Comment by chenjiahan** [comment]
可以用 title 插槽

**Comment by mhxy13867806343** [comment]
炽

**Comment by mhxy13867806343** [comment]
ok

**Comment by pokect** [comment]
请问vantui有react版本的开发计划吗?

**Comment by chenjiahan** [comment]
> 请问vant有react版本的开发计划吗?

没有计划喔

**Comment by JohnieXu** [comment]
想参与新版本开发

**Comment by chenjiahan** [comment]
@JohnieXu 建议从参与处理 issue 开始 ^_^

**Comment by JohnieXu** [comment]
@chenjiahan  好呢

**Comment by zjj131415** [comment]
👍

**Comment by mhxy13867806343** [comment]
@chenjiahan  Toast希望增加类似Dialog.alert({
  title: '标题',
  message: '弹窗内容',
}).then(() => {
  // on close
});

Dialog.alert({
  message: '弹窗内容',
}).then(() => {
  // on close
});  then()和catch()方法

**Comment by chenjiahan** [comment]
Dialog 是通过按钮触发的，Toast 没有这种交互

**Comment by whenTheMorningDark** [comment]
虽然还没有使用到vant,但是这个ui设计还是很到位的。

**Comment by tangdw** [comment]
真.大佬，移动端因 vant 而选择 vue

**Comment by navcat** [comment]
希望有跟bootstrap一样的更多的公共样式类可以用：如text-danger，text-left之类的

**Comment by gaao** [comment]
啥时候更新下assets里的sketch资源～

**Comment by yancoo** [comment]
有考虑增加drawer抽屉组件吗，刚开始用vant～

**Comment by chenjiahan** [comment]
> 希望有跟bootstrap一样的更多的公共样式类可以用：如text-danger，text-left之类的

没有计划添加更多的样式类呢，更倾向于以组件的形式提供

> 啥时候更新下assets里的sketch资源～

新版设计稿已经在内部评审阶段了，最近 Vant 样式会有一波更新，更新完后会放出最新的视觉稿（预计在六月份）

> 有考虑增加drawer抽屉组件吗，刚开始用vant～

可以搭配 Popup 和 Cell 组件来实现喔

**Comment by wangchunhai818** [comment]
ios 13.4 长按图片异常突出，无法实现微信的保存和识别，如果不使用vant 就没问题，希望有解决方法

**Comment by Hisioni** [comment]
希望增加一个类似于NoticeBar并支持富文本插槽和纵向排列的播报组件，Vant太完美了，加油~

**Comment by Mr-xue** [comment]
优质的团队，优质的框架，加油~~

**Comment by xuanmos** [comment]
目前对于表单组件调用稍微有点麻烦，比如一个picker需要自己组装3个组件才能达到需求，是否可以考虑一下调用方式呢，在使用的过程中也是嫌调用比较麻烦，所以自己在vant基础上封装了一个表单组件：https://github.com/xuanmos/v-form

> 给团队点赞，加油~

**Comment by wendzhao** [comment]
想要一个签名组件，就是客户手写签名

**Comment by stys35** [comment]
希望 Popup 弹出层 新增一个标题属性

**Comment by chenjiahan** [comment]
> ios 13.4 长按图片异常突出，无法实现微信的保存和识别

参见 https://github.com/youzan/vant/issues/6269

> 希望增加一个类似于NoticeBar并支持富文本插槽和纵向排列的播报组件

暂无计划支持喔，纵向可以基于 Swipe 实现

> 想要一个签名组件

自己实现吧，哈哈

> 希望 Popup 弹出层 新增一个标题属性

参见 https://github.com/youzan/vant/issues/6257

**Comment by MBearo** [comment]
需要等到新的设计稿才可以开始写最新版么？

**Comment by chenjiahan** [comment]
> 需要等到新的设计稿才可以开始写最新版么？

不是呢，跟设计稿无关

**Comment by mhxy13867806343** [comment]
我又来提需求
Calendar组件，能否增加属性，就是可以从某天（如12号开始），手动移动到（如31号）？？？？？？？？

**Comment by chenjiahan** [comment]
@mhxy13867806343 不是很懂你的意思，直接修改 v-model 应该就可以实现该效果

**Comment by ecpanda** [comment]
vant这么出色的组件库为什么不开发react版本?

**Comment by ecpanda** [comment]
> > 请问vant有react版本的开发计划吗?
> 
> 没有计划喔

vant这么出色的组件库为什么不开发react版本?

**Comment by chenjiahan** [comment]
@ecpanda 社区有：https://github.com/mxdi9i7/vant-react

**Comment by xieyuh** [comment]
vant-cli 后续可以支持开发react组件吗 变成一个通用的组件开发脚手架

**Comment by chenjiahan** [comment]
@xieyuh 没有这方面的计划~

**Comment by rsaLive** [comment]
能增加table组件就完美了

**Comment by hzyyy** [comment]
table 没用；移动端摆不下。

**Comment by 1207145565** [comment]
想请问一下，源码下面生成的vetur/xx.json是如何使用的
