### ISSUE TITLE
页面手动刷新 tabbar 会 回到起始路由页面对应的 active icon

### ISSUE THREAD

**Issue by songhaoreact** [youzan/vant#557]
## demo演示

![image](http://oetr5vzir.bkt.clouddn.com/2222222.gif)

**Comment by celverbamboo** [comment]
我碰到了同样的问题，你是怎么解决的？

**Comment by celverbamboo** [comment]
手动设置active同样没有生效

**Comment by qianzhaoy** [comment]
@celverbamboo @songhaoreact 
可以参考一下[我的tab切换](https://github.com/qianzhaoy/vant--mobile-mall/blob/master/src/vue/components/Tabbar/index.vue)

**Comment by songhaoreact** [comment]
666 不同的是我icon用的是图片，不是字体图标，参考你的代码，稍微改了一下，完美解决！ 感谢 @qianzhaoy 

## 如果是icon是图片的话，可以这样配置

```js
 tabbar: [{
		name: "首页",
		path: "/",
		pathName: "index",
		icon: {
                        normal: require('./index.png'),
                        active: require('./index_active.png')
                 },
		dot: false,
		info: ""
	},
```
```html
<van-tabbar v-model="active">
      <van-tabbar-item v-for="(tab, index) in tabbar"
      :to="tab.path"
      :dot="tab.dot"
			:info="tab.info"
			:key="index"
      >
        <template slot="icon" slot-scope="props">
          <img :src="props.active ? tab.icon.active : tab.icon.normal" />
        </template>
        <span>{{tab.name}}</span>
      </van-tabbar-item>
    </van-tabbar>
```

**Comment by songhaoreact** [comment]
@celverbamboo

**Comment by celverbamboo** [comment]
@songhaoreact @qianzhaoy 谢谢

**Comment by celverbamboo** [comment]
@songhaoreact 但是为什么底层不设置一下呢?

**Comment by celverbamboo** [comment]
@qianzhaoy 利用路由来重新设置，我觉得这个东西功能本身就可以放在Tabbar组件

**Comment by qianzhaoy** [comment]
@celverbamboo 如果你有更好的想法，这个你可以再开一个 issue 提一下建议， 或者发PR。组件也是一步步完善的嘛。慢慢来

**Comment by qianzhaoy** [comment]
@celverbamboo 我也觉得增加 tabbar 组件增加路由匹配的的配置也挺好的，可以再开一个issue 讨论。毕竟我也不是vant的维护者。现在也和你一样， 正在用vant做项目。然后提一下bug和建议。
