### ISSUE TITLE
您好，使用vantH5组件中的filed里面字数统计show-word-limit报错

### ISSUE THREAD

**Issue by fugang1996** [youzan/vant#5571]
浏览器抛出错误为：[Vue warn]: Error in render: "TypeError: Cannot read property 'length' of null"
文档中介绍 show-word-limit 该字段类型为布尔类型

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by fugang1996** [comment]
您好，我是按照模板创建的，我在网上浏览也有不少人遇到了这个问题。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 中午12:58
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"付先森"<2218889604@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] 您好，使用vantH5组件中的filed里面字数统计show-word-limit报错 (#5571)




请按照模板创建 issue，感谢配合
