### ISSUE TITLE
[Feature Request] 异步控制switch开关

### ISSUE THREAD

**Issue by YouthShouting** [youzan/vant#5572]
### 这个功能解决了什么问题
for循环出来的switch开关，input事件不好监听是哪个switch开关触发的

### 描述您想要的解决方案
在异步控制switch开关的input事件中多开放一个参数，还有input事件触发会有点透的bug，给绑定的input事件中添加阻止冒泡

### 建议的API是什么样的
在异步控制switch开关的input事件中多开放一个参数，这个参数可以绑定为id

**Comment by chenjiahan** [comment]
加个参数就行

```html
<van-switch
  v-for="index in 3"
  @input="onInput(index, $event)"
/>
```
