### ISSUE TITLE
轮播 定位时 切换动画效果可以取消掉嘛

### ISSUE THREAD

**Issue by 15000940034** [youzan/vant#5573]
设备 / 浏览器
�移动端

Vant 版本
2.2.11

Vue版本
2.4.2

当我直接定位时 this.$refs.WanSwipe.swipeTo(21); 会出现一个动画切换效果 然后再定位到21  这个效果可以控制嘛？

**Comment by chenjiahan** [comment]
```js
this.$refs.WanSwipe.swipeTo(21, { immediate: true })
```
