### ISSUE TITLE
[Bug Report] Swipe 轮播 在iPhone XS真机上会抖动轮播

### ISSUE THREAD

**Issue by xts871722743** [youzan/vant#5578]
### 设备 / 浏览器
iPhone XS

### Vant 版本
2.4.1

### Vue 版本
2.6.6

### 重现链接
<a href="https://myshop1.zootopia.store/?showwxpaytitle=1#/home" target="_blank">https://myshop1.zootopia.store/?showwxpaytitle=1#/home</a>

### 描述问题
轮播在iphone xs上以抖动的方式进行轮播，条件有限，更高的iphone没有测试。想问一下解决办法

**Comment by xts871722743** [comment]
这个问题有人看一下吗

**Comment by chenjiahan** [comment]
复现链接无效，可以试下官方文档示例有没有这个问题

**Comment by xts871722743** [comment]
> 复现链接无效，建议试下官方文档示例有没有这个问题

这个我试了官方文档的实例，在真机上直接运行的  https://youzan.github.io/vant/mobile.html#/zh-CN/   这个地址  你们可以直接在iphone xs上看下

**Comment by xts871722743** [comment]
![1578906699807238](https://user-images.githubusercontent.com/22048388/72432971-4a283e80-37d3-11ea-9c41-da62d2939340.gif)

**Comment by xts871722743** [comment]
今天莫名的好了，据说有可能是手机重启了下之后好了。很奇怪。没法复现了。打扰了，这个issue可以关了。

**Comment by aleafo** [comment]
被这个问题折磨了 半下午， 后来看到这篇。。。一样的问题，真机卡顿，然后重启了下手机就好了。。。真是无语了。。。
