### ISSUE TITLE
如何动态换肤？

### ISSUE THREAD

**Issue by MaskHao** [youzan/vant#5580]
您好，目前vant支持定制主题，我想知道是否支持动态换肤功能
window.less.modifyVars({  // 调用 `less.modifyVars` 方法来改变变量值'
   '@primary-color': 'red',
 })

**Comment by chenjiahan** [comment]
目前不支持喔，可以考虑通过构建 less 生成两套样式

**Comment by qsy1403813547** [comment]
请问生成俩套的部分代码能不能附上 感谢！！！！！
