### ISSUE TITLE
Calendar 组件能否添加左右滑动切换月份功能呢

### ISSUE THREAD

**Issue by heda20** [youzan/vant#5581]
### 这个功能解决了什么问题
用户多样选择

### 描述您想要的解决方案
我没看源码，不过我的想法是可以嵌套在Swipe 组件中进行左右滑动

### 建议的API是什么样的
通过vertical 是否纵向滚动

**Comment by chenjiahan** [comment]
暂无计划支持喔

**Comment by kyan54** [comment]
<van-calendar
            ref="calendar"
            :poppable="false"
            :show-confirm="false"
            :min-date="minDate"
            :max-date="maxDate"
            :default-date="date"
            color="	#ee0a24"
            :style="{ height: '400px' }"
            :formatter="formatter"
            @select="calSelect"
    >
      <slot slot="title"  name="title"></slot>
      <template v-slot:title>
        <div>
          <van-icon name="arrow-left" style="float: left;padding: 13px 0px 0px 14px;" size="1.3em" v-on:click="onPre()"/>
          <van-icon name="arrow" style="float: right;padding: 13px 14px 0px 0px;" size="1.3em" v-on:click="onNext()"/>
        </div>
      </template>
    </van-calendar>

<style type="text/css">
  .twcl .van-calendar__header-title{
    /*display: none !important;*/
    height: 0px;
  }
  .twcl .van-cell__title{
    float: left !important;
    padding-left: 0px !important;
    position: absolute !important;
  }
  .twcl .van-cell__value--alone{
    color: #777779 !important;
  }
</style>



onPre(){
      debugger
      var m = moment(this.date);
      this.date = m.subtract(1, 'months').toDate();
      this.minDate=moment(m.format('YYYY-MM') + '-01').toDate();
      this.maxDate=moment(moment(this.minDate).subtract( -1,'months').add( -1,'days').format('YYYY-MM-DD')).toDate();
      this.$refs.calendar.scrollIntoView()
    },
    onNext(){
      debugger
      var m = moment(this.date);
      this.date = m.add(1, 'months').toDate();
      this.minDate=moment(m.format('YYYY-MM') + '-01').toDate();
      this.maxDate=moment(moment(this.minDate).subtract( -1,'months').add( -1,'days').format('YYYY-MM-DD')).toDate();
      this.$refs.calendar.scrollIntoView()
    },


![image](https://user-images.githubusercontent.com/2555542/74602917-afc85d00-50e8-11ea-82f3-41af7d9441fb.png)


暂时这样实现了。。

**Comment by biliboard** [comment]
> formatter

老哥有完整代码不，formatter这些都没写出来
