### ISSUE TITLE
ios 13.x系统 倒计时组件在微信里面会停止不动，滑动下页面就会动下，不滑不动

### ISSUE THREAD

**Issue by Lutz2015** [youzan/vant#5585]
<van-count-down :time="time" />
export default {
  data() {
    return {
      time: 30 * 60 * 60 * 1000
    };
  }
}
直接这么用的， 不是必现，偶然碰到过4，5次

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
