### ISSUE TITLE
苹果safari浏览器上 NoticeBar 只滚动一次就不再滚动

### ISSUE THREAD

**Issue by sydyLiu** [youzan/vant#5587]
### 设备 / 浏览器
iphone/safari 

### Vant 版本
2.4.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://hktest.ricepon.com:64377/foodstorys/index.html#/test" target="_blank">https://hktest.ricepon.com:64377/foodstorys/index.html#/test</a>

### 描述问题
NoticeBar  在苹果手机自带的safari 浏览器中,只会滚动一次. 在安卓上无问题.在苹果浏览器电脑端也会有一样的问题,但是官方示例没有问题

**Comment by chenjiahan** [comment]
官方示例没问题的话，建议看下是不是项目里其他因素导致的？

**Comment by sydyLiu** [comment]
你好&nbsp; 我尝试过查询冲突, 但是依旧没有头绪, 不知能否可以告知我 关于 通知栏 的源码位置,&nbsp;
值得一提的是, 这个问题只在苹果浏览器上会有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月15日(星期三) 晚上7:36
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"う妖孽、从不妖艳/"<2877506846@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] 苹果safari浏览器上 NoticeBar 只滚动一次就不再滚动 (#5587)




官方示例没问题的话，建议看下是不是项目里其他因素导致的？

**Comment by chenjiahan** [comment]
在 vant/es/notice-bar/index.js 里哈

**Comment by sydyLiu** [comment]
感谢告知


在查看代码后 发现经过了这里





修改了动画





但是我发现! 这代码在我这里很奇特, 苹果浏览器上 他代码也会有显示, 但是动画却没有执行, 需要将动画先取消 在选中 然后就会一直执行!


&nbsp;&nbsp;&nbsp;-------&gt;&nbsp;&nbsp;


可是我通过js去延时二次添加动画, 却并没有达到动画再执行的效果








不知道 是否是我的思路错了 , 还是有其他原因.&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月17日(星期五) 下午5:34
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"う妖孽、从不妖艳/"<2877506846@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] 苹果safari浏览器上 NoticeBar 只滚动一次就不再滚动 (#5587)




在 vant/es/notice-bar/index.js 里哈

**Comment by sydyLiu** [comment]
&nbsp; 感谢 已经弄好了&nbsp; 虽然有点愚蠢









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月17日(星期五) 下午5:34
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"う妖孽、从不妖艳/"<2877506846@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] 苹果safari浏览器上 NoticeBar 只滚动一次就不再滚动 (#5587)




在 vant/es/notice-bar/index.js 里哈

**Comment by chenjiahan** [comment]
好的👌
