### ISSUE TITLE
[Bug Report]Canlendar组件在typescript中缺少类型定义

### ISSUE THREAD

**Issue by fguizc** [youzan/vant#5588]
设备 / 浏览器
Mac/Chrome

Vant 版本
2.4.2

Vue 版本
2.6.10

重现链接
无须

描述问题
import { Calendar } from 'vant';

Module '"../../node_modules/vant/types"' has no exported member 'Calendar'.

**Comment by chenjiahan** [comment]
下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.4.3 版本修复
