### ISSUE TITLE
[Bug Report] Field disabled is not property but an attribute

### ISSUE THREAD

**Issue by joe223** [youzan/vant#5590]
### 设备 / 浏览器
All

### Vant 版本
2.4.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/youzan/vant/blob/dac60c8a37d3b2b3686dc25c1c34b4029a963d1b/src/field/index.js#L233" target="_blank">https://github.com/youzan/vant/blob/dac60c8a37d3b2b3686dc25c1c34b4029a963d1b/src/field/index.js#L233</a>

### 描述问题
Thanks for your hard work.

This implementation is conflict with documentation.

> https://youzan.github.io/vant/#/zh-CN/field
> Field - API - Props - disabled

We can not get `disabled` as props from Field Components.

My suggestion is that adding `disabled` to Field's props definition. Just likes:

```javasciprt
  props: {
    ...cellProps,
    error: Boolean,
    readonly: Boolean,
    disabled: Boolean,
    autosize: [Boolean, Object],
    leftIcon: String,
```

**Comment by chenjiahan** [comment]
PR welcome~

**Comment by chenjiahan** [comment]
已在 2.4.3 版本修复

**Comment by joe223** [comment]
Thanks.

I'm really busy this days 😂，can not get a leisure time

**Comment by chenjiahan** [comment]
Haha~ it doesn't matter
