### ISSUE TITLE
[Feature Request] area组件支持自定义行禁用

### ISSUE THREAD

**Issue by duhongjun** [youzan/vant#5591]
### 这个功能解决了什么问题
存在只允许修改指定层级的需求, 比如外部带入省市, 只可以修改区的这种需求

### 描述您想要的解决方案
增加以column为配置单元的disabled

### 建议的API是什么样的
类似于columns-placeholder
:disabled = [true, true, false]
禁用省市滚动修改, 只允许修改区

**Comment by chenjiahan** [comment]
暂无计划支持喔，目前 Picker 没有禁用列的交互
