### ISSUE TITLE
[Feature Request] swipe，设置宽度时，希望可以提供选项，设置最后一项是否滚到容器最左侧

### ISSUE THREAD

**Issue by wj20160318** [youzan/vant#5595]
### 这个功能解决了什么问题
目前给swipe设置宽度之后，最后一项是滚不到容器最左侧的，猜测当时这样设置是为了图片这种情况考虑的，但是，有时候，使用swipe并不是为了图片，上述情况就满足不了要求了

### 描述您想要的解决方案
希望提供选项可以设置上述情况

### 建议的API是什么样的
例如transformNormal:true

**Comment by chenjiahan** [comment]
最后一项滚动到容器最左侧的话，右侧就会有空隙无法填充，所以暂时没有计划修改或新增 API
