### ISSUE TITLE
[Bug Report] Uploader组件点击无效

### ISSUE THREAD

**Issue by taolin666** [youzan/vant#5601]
### 设备 / 浏览器
小米k30

### Vant 版本
2.2.16

### Vue 版本
2.5.2

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
vue 的h5项目嵌套在app里，所以没有链接

**Comment by chenjiahan** [comment]
Uploader 是基于 HTML 原生的 input type="file" 封装的，如果无法点击的话，一般是 App WebView 容器的问题，建议从原生侧进行排查
