### ISSUE TITLE
sku 选择规格时，可以选择其他规格并重新获取数据，而不是直接禁用其他规格，需要取消当前选择才可以更换选择

### ISSUE THREAD

**Issue by leecheehl** [youzan/vant#5602]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
