### ISSUE TITLE
[Feature Request] 建议新增移动端九宫格锁屏组件

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#5606]
### 这个功能解决了什么问题
移动端H5APP由于项目安全需要 实现九宫格或者密码锁屏功能

### 描述您想要的解决方案
移动端H5APP由于项目安全需要 实现九宫格或者密码锁屏功能

### 建议的API是什么样的
参考locker（手势图案锁屏）
地址: https://dcloud.io/hellomui/examples/locker-dom.html

**Comment by chenjiahan** [comment]
暂无计划支持喔
