### ISSUE TITLE
ssr项目使用时css加载错误

### ISSUE THREAD

**Issue by lmy1991** [youzan/vant#561]
基于vue官网的vue-hackernews-2.0改的一个项目。
加载vant组件时css报错了。
项目连接如下
[https://github.com/lmy1991/vue-ssr-vant](https://github.com/lmy1991/vue-ssr-vant)

**Comment by chenjiahan** [comment]
@lmy1991 请问问题解决了吗

**Comment by pandashuai** [comment]
ssr加载 直接报SyntaxError: Cannot use import statement outside a module
