### ISSUE TITLE
[Feature Request] 折叠面板    关于折叠面板展开的问题

### ISSUE THREAD

**Issue by W-ChenAMG** [youzan/vant#5611]
### 这个功能解决了什么问题
无

### 描述您想要的解决方案
 我的折叠面板上有12个条目，手风琴模式 activeNames: ' ',为空的。 但是每次跳转到这个页面的时候，会出现某个面板展开，然后瞬间合上的现象，  我的需求是  每次进来 所有的面板都是闭合的  不会出现  展开又瞬间合上的情况

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
试了下没复现唉，或许是初始状态设置的有问题，能否提供一下 codesandbox 复现链接
