### ISSUE TITLE
van-grid-item 无法使用本地自定义的font 字体

### ISSUE THREAD

**Issue by zhongminsheng** [youzan/vant#5612]
van-icon  API 有 class-prefix 属性， 但是 van-grid-item  不支持！

尝试 使用 slot  ：
      <van-grid-item
                text="成品库存表"
                to="/KctjList"
      >
         <van-icon class-prefix="icon" name="lajiche" />
      </van-grid-item>
 结果是 text被丢失，求解决愿意付出！！

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
使用 icon 插槽即可
