### ISSUE TITLE
[Feature Request] 建议Field组件的value prop类型支持Boolean Array Object

### ISSUE THREAD

**Issue by ErnestWangZuNian** [youzan/vant#5613]
### 这个功能解决了什么问题
在基于Field组件扩展表单的时候 因为value 只支持string Number 但是如果有单选框 复选框 下拉框的时候 他们的值大部分都是 Bool Array object 就会抛出警告

### 描述您想要的解决方案
建议Field组件的value prop类型支持Boolean Array Object

### 建议的API是什么样的
建议Field组件的value prop类型支持Boolean Array Object

**Comment by chenjiahan** [comment]
value 如果为 Array 或 Object 的时候，在输入框里该显示什么内容呢？

**Comment by ErnestWangZuNian** [comment]
不显示 input框了 通过slot input 定制一个单选框或者复选框 
`<template>
  <div class="component-formitem-container">
    <Field
      v-bind="$attrs"
      v-model="currentValue"
      :required="required"
      :error-message="filedInfo ? filedInfo.message : null"
      :readonly="$attrs.type === 'select'"
      @change="changeField"
      @focus="focusInput"
    >
      
      <RadioGroup
        slot="input"
        v-model="currentValue"
        v-if="$attrs.type === 'radio'"
        @change="changeRadioCheckbox($event, 'radio')"
      >
        <Radio
          :name="item.value"
          :key="index"
          v-for="(item, index) in radioList"
        >
          {{ item.label }}
        </Radio>
      </RadioGroup>
      
      <CheckboxGroup
        slot="input"
        v-model="currentValue"
        v-if="$attrs.type === 'checkbox'"
        @change="changeRadioCheckbox($event, 'checkbox')"
      >
        <checkbox
          shape="square"
          :name="item.value"
          :key="index"
          v-for="(item, index) in checkboxList"
        >
          {{ item.label }}
        </checkbox>
      </CheckboxGroup>
    </Field>
    
    <Popup v-model="selectShow" position="bottom">
      <Picker v-bind="$attrs" @change="changeSelect">
      </Picker>
    </Popup>
  </div>
</template>

<script>
import {
  Radio,
  RadioGroup,
  Checkbox,
  CheckboxGroup,
  Picker,
  Popup,
  Field
} from "vant";
export default {
  name: "ComponentFormItem",
  components: {
    Field,
    Radio,
    RadioGroup,
    Checkbox,
    CheckboxGroup,
    Picker,
    Popup
  },
  props: {
    value: {
      type: [String, Array, Number, Boolean, Object],
      defaultValue: null
    },
    radioList: {
      type: Array,
      defaultValue: []
    },
    checkboxList: {
      type: Array,
      defaultValue: []
    },
    filedInfo: {
      type: Object,
      defaultValue: null
    }
  },
  data() {
    return {
      currentValue: this.value,
      selectShow: false,
      required: this.filedInfo ? this.filedInfo.required : false
    };
  },
  computed: {
    // currentValue() {
    //   const result = this.value;
    //   // const { type, columns, valueKey } = this.$attrs;
    //   // if (type === "select") {
    //   //   if (columns.length) {
    //   //     if (Utils.isObject(columns[0])) {
    //   //       result = columns[0][valueKey || "text"];
    //   //     }else{
    //   //       result = columns[0];
    //   //     }
    //   //   }
    //   // }
    //   return result;
    // }
  },
  methods: {
    changeRadioCheckbox(value) {
      this.currentValue = value;
      this.$emit("input", value);
    },
    changeSelect(pickr, value) {
      if (value && Utils.isObject(value)) {
        this.currentValue = value[this.$attrs.valueKey || "text"];
      } else {
        this.currentValue = value;
      }
      this.$emit("input", value);
    },
    changeField(e) {
      this.$emit("input", e.target.value);
    },
    focusInput() {
      if (this.$attrs.type === "select") {
        this.selectShow = true;
      }
    }
  },
  beforeCreate() {},
  created() {},
  beforeMount() {},
  mounted() {},
  beforeUpdate() {},
  updated() {},
  beforeDestroy() {},
  destroyed() {}
};
</script>
<style lang="scss">
@import "./style.scss";
</style>

`

**Comment by ErnestWangZuNian** [comment]
如果外部故意传数组和对象boolean值的话 显示和空字符一样吧  还有种需求是不需要显示input框了 通过slot input显示单选框 复选框 在做表单提交验证的话 基于field就比较方便 

![WechatIMG762](https://user-images.githubusercontent.com/11648360/73279037-73ab8600-4227-11ea-82d2-551397285477.png)

像业务中经常这种需求还是很多的  相当于filed的v-model值可能是个Boolean Array object 但是显示可能就是一个单选框 输入框 下拉框   现在filed只有string和number 传入这些就会抛警告 类型不对

**Comment by chenjiahan** [comment]
> 如果外部故意传数组和对象boolean值的话 显示和空字符一样吧

这个不太合理，暂时没有计划支持

>  还有种需求是不需要显示input框了 通过slot input显示单选框 复选框 

这种可以使用 input 插槽，v-model 不传即可
