### ISSUE TITLE
[Bug Report] Picker多次更新数据视图不更新

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#5614]
### 设备 / 浏览器
Chrome

### Vant 版本
2.4.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-0xi1m" target="_blank">https://codesandbox.io/s/vant-issue-moban-0xi1m</a>

### 描述问题
Picker在多次点击更新需要显示的列表显示时，Picker绑定的数据已更新但是视图没有更新
2.4.4版本是可以正常更新的，但是2.4.5就不行

# 重现连接操作流程
第一步 点击打开Picker之后看到的列表数据是第一次。然后关闭picker，再次点击更新数据。
此时显示的列表数据在Vant 2.4.5版本下 实际上绑定的数据已经更新了但是页面视图数据并没有更新

将版本切换到2.4.4就可以正常更新了

**Comment by chenjiahan** [comment]
2.4.5 版本更新引入的问题，已在 2.4.6 版本修复
