### ISSUE TITLE
[Feature Request] DropdownMenu 下拉菜单options无法自定义数据结构

### ISSUE THREAD

**Issue by hardmanhong** [youzan/vant#5615]
### 这个功能解决了什么问题
支持开发者自定义options数据结构的键名

### 描述您想要的解决方案
DropdownMenu 下拉菜单options无法自定义数据结构

### 建议的API是什么样的
增加一个属性支持自定义传入的options数据结构键名

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议转换成组件所需的格式后传入

**Comment by Skura23** [comment]
vant貌似不支持修改数据键名, 这点还是elementui做得好, 可以修改键名, 更好用

**Comment by JasonSanYe** [comment]
都2022年了 还不支持 废了
