### ISSUE TITLE
vant-cli在windows上有一个bug

### ISSUE THREAD

**Issue by yinhui1129754** [youzan/vant#5618]
具体是脚手架的生成文档目录的地方
![image](https://user-images.githubusercontent.com/19921594/73710290-87328180-473e-11ea-8b22-8a96df5afc71.png)
这里所使用的遍历文件夹的库`fast-glob` 在windows上无法正确的获取文件然后就导致vue的路由报错
![image](https://user-images.githubusercontent.com/19921594/73710408-d5e01b80-473e-11ea-9ba4-3c8ed5c77291.png)
这是对代码进行的测试可以看到打印:
![image](https://user-images.githubusercontent.com/19921594/73710508-26577900-473f-11ea-9a7b-60d0ffb01b72.png)
具体环境:
node版本:v10.13.0
vue版本:3.10.0
webpack:4.41.5
@vant/cli: "^2.2.0"
希望楼主可以修改vant-cli支持windows系统

**Comment by chenjiahan** [comment]
手头没有 windows 的环境，能否提 PR 帮忙修复下

**Comment by yinhui1129754** [comment]
好的

**Comment by chenjiahan** [comment]
已发布 @vant/cli@2.2.2 版本，可以试一下~

**Comment by yinhui1129754** [comment]
好的
