### ISSUE TITLE
环形进度条v-model Bug

### ISSUE THREAD

**Issue by shenlanchenwei** [youzan/vant#5621]
vant 2.4.3版本中

`TestValue=0;`

`
<van-circle v-model="TestValue" :stroke-width="60" />
`
演示链接:
[https://codesandbox.io/embed/vant-issue-moban-xezus?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/vant-issue-moban-xezus?fontsize=14&hidenavigation=1&theme=dark)

初始化完成后会被组件赋值成100,也就是 TestValue=100,正常应该是0,然后进度也不会到100

**Comment by chenjiahan** [comment]
需要指定 rate 属性为 0，rate 才是进度条的目标进度
