### ISSUE TITLE
[Bug Report] 【适配】postcss-pxtorem无法转换组件内联样式

### ISSUE THREAD

**Issue by Msz0322** [youzan/vant#5622]
### 设备 / 浏览器
无

### Vant 版本
2.4.6

### Vue 版本
3.0.0-alpha.4

### 重现链接
<a href="http://www.wu.com/在引入lib-flexible后即可复现" target="_blank">http://www.wu.com/在引入lib-flexible后即可复现</a>

### 描述问题
部分组件含有内联样式 无法被postcss-pxtorem，导致移动端无法适配
.van-radio__icon.van-radio__icon--round
.van-picker__columns 等

**Comment by chenjiahan** [comment]
Picker 选项的高度是由 item-height 控制的，滚动过程中需要根据 item-height 计算滚动位置，所以会有行内样式。

Radio 目前是不含行内样式的，除非你使用了 icon-size 属性
