### ISSUE TITLE
环形进度条吗默认总显示100 什么都没设置

### ISSUE THREAD

**Issue by SuiFengErQu** [youzan/vant#5631]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以用 rate 属性设置进度
