### ISSUE TITLE
[Bug Report] css 添加 overflow 属性后 vant组件 van-list 无法触发 load 事件

### ISSUE THREAD

**Issue by Brannua** [youzan/vant#5634]
### 设备 / 浏览器
Google Chrome

### Vant 版本
2.4.7

### Vue 版本
3.0.0-alpha.4

### 重现链接
<a href="https://gitee.com/pj-l/van-list-demo/blob/master/src/App.vue" target="_blank">https://gitee.com/pj-l/van-list-demo/blob/master/src/App.vue</a>

### 描述问题
css 添加 overflow 属性后 vant组件 van-list 无法触发 load 事件

尝试注释掉css的overflow属性就可以触发load事件，而添加overflow属性就无法触发load事件，请教一下，谢谢

**Comment by Brannua** [comment]
经过尝试，我将 position : fixed; 改为 position : absolute; 可以触发 load 事件，但是不明白道理，希望作者给予指点，谢谢！

**Comment by chenjiahan** [comment]
滚动容器上必须要有滚动条。如果只设置 fixed 布局，没有设置滚动容器高度的话，是不会有滚动条的，所以 List 无法生效
