### ISSUE TITLE
tab组件scrollspy失效  

### ISSUE THREAD

**Issue by yuhonyon** [youzan/vant#5636]
描述:滚动条如果不在window上而是在某个dom上 scrollspy就失效了   并且使用 sticky 时  滚动条会导致tab nav 抖动   目前业务靠定位出来使滚动调在window上解决
触发设备:所有设备
版本:2.4.6

**Comment by chenjiahan** [comment]
确实存在这个问题，下个版本会修复下

**Comment by chenjiahan** [comment]
已在 2.5.0 版本修复

**Comment by a1455047031** [comment]
为什么我还是这个问题,我已经更新到2.5.0版本了, 滚动条在最外层div就scrollspy生效,滚动条在内层某一处div滚动就失效了

**Comment by chenjiahan** [comment]
@a1455047031 可以提供 codesandbox 复现链接看下

**Comment by LingRen** [comment]
`<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png" />
    <HelloWorld msg="Welcome to Your Vue.js App" />
    <van-tabs scrollspy sticky>
      <van-tab v-for="index in 80" :key="index" :title="'选项 ' + index">
        <p class="item">内容 {{ index }}</p>
      </van-tab>
    </van-tabs>
  </div>
</template>

<script>
// @ is an alias to /src
import HelloWorld from "@/components/HelloWorld.vue";

export default {
  name: "home",
  components: {
    HelloWorld
  },
  data() {
    return {
      a: 1
    };
  },
  created() {
    const a = "sasa";
    this.log(a);
  },
  methods: {
    log(a) {
      console.log(a + "......");
    }
  },
  beforeRouteEnter(to, from, next) {
    console.log("Home");
    next();
  }
};
</script>

<style lang="scss">
.home {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: auto;
  .item {
    margin: 20px;
  }
}
</style>
`
像这样的布局，怎么让他生效呢

**Comment by LingRen** [comment]
比如把他放到这样的盒子里面
`.home {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: auto;
}`
