### ISSUE TITLE
[Feature Request] Collapse 折叠面板 每次打开的时候  会出现瞬间展开   然后又自动关闭的问题，

### ISSUE THREAD

**Issue by W-ChenAMG** [youzan/vant#5638]
### 这个功能解决了什么问题
Collapse 折叠面板 每次打开的时候  会出现瞬间展开   然后又自动关闭的问题，    每次都会   尤其刷新的时候更明显  

### 描述您想要的解决方案
你是否有个网盘 啥的   我把文件传给你  你看看    上次你说   没有复现

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
在什么情况/环境下会出现呢，网盘没有喔

**Comment by W-ChenAMG** [comment]
那有什么办法 能让你看到我的代码      就是我引入了  Collapse 折叠面板   一共有12个面板   每次进去的时候都会出现      或者浏览器刷新的时候都会出现    或者布道服务器  在手机进去的 时候  也会出现

**Comment by chenjiahan** [comment]
可以用 codesandbox 创建一个复现链接

https://codesandbox.io/s/m5v3f

**Comment by W-ChenAMG** [comment]
有邮箱啥的吗？ 我直接都发你   因为我这个里面有图    这个 codesandbox  我不怎么会用

**Comment by chenjiahan** [comment]
图片可以直接粘贴到 issue 的，建议用 issue 沟通，邮件较多容易遗漏

**Comment by W-ChenAMG** [comment]
链接：https://pan.baidu.com/s/1x7JkLkZQX8X_P1uS-gCg8Q 
提取码：0o3j

这个是瞬间展开 然后又自动关闭的视频

**Comment by wangshaoqun** [comment]
这个问题解决了吗？我也出现了这个问题；
版本是2.10.5

**Comment by W-ChenAMG** [comment]
> 这个问题解决了吗？我也出现了这个问题；
> 版本是2.10.5

我看你提的issue ，上面的复现链接，没有出现这个问题啊

**Comment by wangshaoqun** [comment]
我这边IOS 9.3.5系统上出现，附件是出现操作视频

发送自 Windows 10 版邮件应用

发件人: 韦帆
发送时间: 2020年10月27日 18:36
收件人: youzan/vant
抄送: wangshaoqun; Comment
主题: Re: [youzan/vant] [Feature Request] Collapse 折叠面板 每次打开的时候 会出现瞬间展开 然后又自动关闭的问题， (#5638)

这个问题解决了吗？我也出现了这个问题；
版本是2.10.5
我看你提的issue ，上面的复现链接，没有出现这个问题啊
