### ISSUE TITLE
[Bug Report] uploader组件请求里面触发无法显示

### ISSUE THREAD

**Issue by wynova** [youzan/vant#5639]
### 设备 / 浏览器
iphone6

### Vant 版本
2.4.7

### Vue 版本
3.0.0-alpha.4

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
1、van-uploader id="uploadPhoto" ref="uploadPhoto" style="display: none" capture="user" :after-read="onRead" result-type="file”
2、var getUploader = document.getElementById("uploadPhoto");
3、请求里面根据条件判断，如果满足条件：getUploader.click();
问题：现在不在请求里面上述代码有效，可以展示。但是放入请求里面无法正常使用。不报错。调试下来，代码是执行了，UI界面没有出来！

**Comment by chenjiahan** [comment]
重现连接无效，请提供 codesandbox 链接

**Comment by wynova** [comment]
我这边是自己项目中的，无法提供链接，抱歉啊

**Comment by wynova** [comment]
> 重现连接无效，请提供 codesandbox 链接

我这边是自己项目中的，无法提供链接，抱歉啊

**Comment by chenjiahan** [comment]
可以用 codesandbox 这个工具把主要步骤重现出来的

**Comment by wynova** [comment]
> 可以用 codesandbox 这个工具把主要步骤重现出来的

解决了！谢谢！

**Comment by yexiaodong** [comment]
如何解决，我遇到这个问题
