### ISSUE TITLE
没有重置Sku下的规格选项

### ISSUE THREAD

**Issue by celverbamboo** [youzan/vant#564]
![效果图](https://i.loli.net/2018/01/23/5a66b04a85646.png)
![效果图](https://i.loli.net/2018/01/23/5a66b0a78161e.png)

**Comment by chenjiahan** [comment]
@celverbamboo 感谢反馈，我们会在后续支持

**Comment by w91** [comment]
#568 已增加resetSelectedSkuOnHide参数

**Comment by chenjiahan** [comment]
已在 0.12.6 版本中支持
