### ISSUE TITLE
使用 dropdown 和 van-list 组件配置时，出现无法完全遮盖的情况

### ISSUE THREAD

**Issue by sanri1993** [youzan/vant#5643]
您好：
 我在使用 dropdown-menu  配合 List 组件做一个列表筛选时，出现在 z-index 问题，经排查为 van-cell 的 position 冲突，去掉 van-cell 的  position 正常
但是 Circle 组件永远是浮在最上面，希望作者能把这个问题解决，或提供下解决办法，谢谢

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
