### ISSUE TITLE
[Bug Report] 使用TypeScript时无法按文档上的方式注册Dialog组件

### ISSUE THREAD

**Issue by HermitSun** [youzan/vant#5646]
### 设备 / 浏览器
Windows10，TypeScript 3.7.5

### Vant 版本
2.4.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/HermitSun/vant-dialog-type-issue" target="_blank">https://github.com/HermitSun/vant-dialog-type-issue</a>

### 描述问题
结合TypeScript使用时，无法按文档上写的方式注册Dialog组件，提示Property 'name' is a static member of type 'VanComponent'：
```ts
export default Vue.extend({
  components: {
    [Dialog.Component.name]: Dialog.Component
  }
})
```

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by HermitSun** [comment]
OK，谢谢

**Comment by chenjiahan** [comment]
已在 2.5.0 版本修复
