### ISSUE TITLE
[Bug Report] 使用babel-plugin-import引入了Icon组件但是图标不显示

### ISSUE THREAD

**Issue by y451687300** [youzan/vant#5647]
### 设备 / 浏览器
Chrome

### Vant 版本
2.4.7

### Vue 版本
3.0.0-alpha.4

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-mq17b?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-mq17b?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
使用了babel-plugin-impor引入了icon组件   但是icon组件不显示  别的组件没有问题

**Comment by chenjiahan** [comment]
上面的重现链接里没有引入样式，建议你看下项目里是否正确引入了样式文件
