### ISSUE TITLE
脚手架在windows系统上还有个样式打包bug

### ISSUE THREAD

**Issue by yinhui1129754** [youzan/vant#5648]
![image](https://user-images.githubusercontent.com/19921594/74300101-bb82ef00-4d89-11ea-9669-c6bcfece175a.png)
bug1：这里的获取的数组一直都是[]导致样式哪里打包的时候会缺少样式

![image](https://user-images.githubusercontent.com/19921594/74300154-ebca8d80-4d89-11ea-8641-933786e854ac.png)
bug2:这里生成样式的时候不知道为什么打包过后的相对地址由‘/‘变成‘\’

![image](https://user-images.githubusercontent.com/19921594/74300299-4fed5180-4d8a-11ea-9210-2babf07e1b15.png)

希望楼主可以修改为支持windows系统

**Comment by chenjiahan** [comment]
已发布 @vant/cli@2.2.4
