### ISSUE TITLE
多页应用按需引入vant打包的时候提示警告

### ISSUE THREAD

**Issue by SilentKc** [youzan/vant#5649]
chunk chunk._vant2.4.7@vant [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/_css-loader@3.4.2@css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--6-oneOf-3-2!./node_modules/_vant@2.4.7@vant/es/cell-group/index.css
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/_css-loader@3.4.2@css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--6-oneOf-3-2!./node_modules/_vant@2.4.7@vant/es/field/index.css
   - couldn't fulfill desired order of chunk group(s) , ,
   - while fulfilling desired order of chunk group(s) , , , , ,
 * css ./node_modules/_css-loader@3.4.2@css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--6-oneOf-3-2!./node_modules/_vant@2.4.7@vant/es/uploader/index.css
   - couldn't fulfill desired order of chunk group(s) ,
   - while fulfilling desired order of chunk group(s) ,

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5446

**Comment by SilentKc** [comment]
我参考#5446使用
new&nbsp;MiniCssExtractPlugin({
 ignoreOrder:&nbsp;false
})

结果警告更多了

我没使用new MiniCssExtractPlugin之前打包警告只有10个

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月12日(星期三) 下午5:46
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"Silent、"<532511275@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] 多页应用按需引入vant打包的时候提示警告 (#5649)




参见 #5446
