### ISSUE TITLE
[Bug Report] 请问有没有适合vant的表单验证插件

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#5650]
### 设备 / 浏览器
google

### Vant 版本
2.4.7

### Vue 版本
3.0.0-alpha.4

### 重现链接
<a href="http://123123213.com" target="_blank">http://123123213.com</a>

### 描述问题
请问有没有适合vant的表单验证插件

**Comment by chenjiahan** [comment]
下个版本会增加 Form 组件，也可以使用社区的 vee-validate 库
