### ISSUE TITLE
vant-list  求助

### ISSUE THREAD

**Issue by wang475293638** [youzan/vant#5652]
:我对获取到的数据进行过滤，然后搜索，然后再删掉关键字，就不能往下拉了，只有第一页数据
把过滤函数去掉就正常了，但我又不能不过滤。

```js
 const { data } = await this.$Parse.Cloud.run("getPartner", {
        name: this.searchValue,
        pageIndex: this.pageIndex,
        pageSize: this.pageSize
      });
      let newData = data[0]
      .filter(item => item.AA_Partner_partnerType!=226 ) // 不显示供应商
      this.partner.push(...newData);
      this.loading = false;
      if (data[0].length) {
        this.pageIndex++;
        //为了配合搜索框 finished = false 会继续触发 onLoad 事件
        this.finished = false;
      }
      if (!data[0].length || data[0].length < this.pageSize) {
        this.finished = true;
      }
```

**Comment by wang475293638** [comment]
把 filter 去掉就正常了

**Comment by chenjiahan** [comment]
上面的代码看起来没什么问题，可以确认下你在删掉关键字后是否重置了 finished、loading 等状态，或者提供下 codesandbox 复现链接呢

**Comment by wang475293638** [comment]
watch: {
    searchValue: debounce(async function(newValue, oldValue) {
      this.pageIndex = 0;
      this.partner = [];
      this.getPartner();
    }, 500)
  },
这是watch 里的，重置了loading，finished， 我修改了pageSize。好了。。

**Comment by wang475293638** [comment]
if (data[0].length) {
        this.pageIndex++;
        //为了配合搜索框 finished = false 会继续触发 onLoad 事件
        this.finished = false;
      }
      if (!data[0].length || data[0].length < this.pageSize) {
        this.finished = true;
      }
