### ISSUE TITLE
请问如何获取tabbar高度？

### ISSUE THREAD

**Issue by gm-fire** [youzan/vant#5656]
html
`<van-tabbar ref="tabbar" safe-area-inset-bottom v-model="active">`

js
`mounted() {
    console.log(this.$refs.tabbar.offsetHeight);
}`

不过输出的是 undefined

**Comment by chenjiahan** [comment]
`$refs.tabbar`拿到的是 Vue 组件实例，$el 才是 DOM 元素

```js
console.log(this.$refs.tabbar.$el.offsetHeight);
```
