### ISSUE TITLE
上面的重现链接里没有引入样式，建议你看下项目里是否正确引入了样式文件

### ISSUE THREAD

**Issue by y451687300** [youzan/vant#5657]
上面的重现链接里没有引入样式，建议你看下项目里是否正确引入了样式文件

_Originally posted by @chenjiahan in https://github.com/youzan/vant/issues/5647#issuecomment-585121066_

我在main.js中
import 'vant/lib/icon/style';也没用
而且使用了babel-plugin-import插件不是不用再次引入样式了吗
别的组件都是正常的  就是icon不行

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
