### ISSUE TITLE
[Feature Request]  Collapse 折叠面板   

### ISSUE THREAD

**Issue by W-ChenAMG** [youzan/vant#5659]
### 这个功能解决了什么问题
无

### 描述您想要的解决方案
 Collapse 折叠面板     里面有10几项的时候，然后展开的内容  也有700多px长， 这时候会出现   展开的时候    默认位置 在展开页的中间，或者展开页的下方，  影响用户体验，   如何 就是在很多项，并且展开里面的内容比较多的时候，   展开默认位置  是   标题栏   而不是里面展开页的其他内容  ，标题栏 都被顶在   最上面挡住了

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
可以自行控制滚动位置，或者适当限制下内容长度

**Comment by W-ChenAMG** [comment]
没有其他办法吗

**Comment by W-ChenAMG** [comment]
就是一展开的时候    是标题栏   不要让标题栏都被顶在 最上面挡住
