### ISSUE TITLE
[Bug Report] 使用babel-plugin-import引入了Icon组件但是图标不显示  别的组件是正常的

### ISSUE THREAD

**Issue by y451687300** [youzan/vant#5661]
### 设备 / 浏览器
Chrome

### Vant 版本
2.4.7

### Vue 版本
2.5.16

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-mq17b?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-mq17b?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
使用了babel-plugin-import按需引入了icon组件 但是icon组件不显示 别的组件没有问题
之前说是没有引入样式文件
我看官方文档说使用了babel-plugin-import就不用再单独引入样式文件了
而且我别的组件没有问题只有Icon这个组件有问题
我也试过在main.js import 'vant/lib/icon/style';
也不生效    难道还有别的什么引用样式方法？

**Comment by chenjiahan** [comment]
上面的重现链接是没问题的，能否提供一个能复现的链接?

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/issues/5677
