### ISSUE TITLE
[Bug Report] Picker级联 当不触发惯性滚动子选项不更新

### ISSUE THREAD

**Issue by Agnes77** [youzan/vant#5662]
### 设备 / 浏览器
3.0.0-alpha.4

### Vant 版本
2.4.7

### Vue 版本
3.0.0-alpha.4

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/picker</a>

### 描述问题
级联里面不触发惯性滚动时，子选项不更新，在官网例子中就能复现。

**Comment by chenjiahan** [comment]
已在 2.5.0 版本修复
