### ISSUE TITLE
[Bug Report] van-field的clearable属性不生效

### ISSUE THREAD

**Issue by HermitSun** [youzan/vant#5663]
### 设备 / 浏览器
Windows10, Chrome 79

### Vant 版本
2.5.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-field-cannot-clear-issue-p1f9k?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-field-cannot-clear-issue-p1f9k?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
给van-field设置了cleable属性后，点击后输入框的内容并没有没清空，clear事件也没有触发。
```vue
<van-field 
    v-model="value2" 
    clearable 
    label="文本" 
    left-icon="music-o" 
    placeholder="显示清除图标"
  />
```
但是官网上的示例却是可以运行的。

**Comment by chenjiahan** [comment]
在桌面端使用参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

**Comment by wuweikd** [comment]
？？？

**Comment by sotework** [comment]
在PC端使用确实不生效，如果是开发pc页面，不建议使用vant。如果是开发移动端页面，在模拟器下才可以正常触发清空。

**Comment by DylanMay** [comment]
微信的浏览器也会出现清除不了2.12.12

**Comment by DylanMay** [comment]
微信的浏览器也会出现清除不了2.12.12

**Comment by 1628610248** [comment]
这个问题手机上也不生效 2.12.12
