### ISSUE TITLE
Calendar组件 想通过按钮设置组件的日期，并且自动跳转到改日期的月份，要怎么操作？

### ISSUE THREAD

**Issue by kyan54** [youzan/vant#5664]
设备 / 浏览器
chrome

Vant 版本
2.5.0

Vue 版本
2.6.11

重现链接
https://codesandbox.io/s/vant-issue-moban-vr16d

描述问题
Calendar组件设置了下个月，为什么不会自动移动到3月份？
要怎么做才能自动跳转到对应选中日期的月份？

**Comment by chenjiahan** [comment]
目前版本里修改 default-date 不会自动跳转，下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.5.1 版本支持
