### ISSUE TITLE
Field组件type=number时不是唤起的数字键盘

### ISSUE THREAD

**Issue by CalmHarbin** [youzan/vant#5665]
设备 / 浏览器
Chrome

Vant 版本
2.4.7

Vue 版本
2.6.10

重现链接
https://youzan.github.io/vant/mobile.html#/zh-CN/field

描述问题
Field组件type=number时,虽然不能输入字母和汉字等,但是在手机上默认唤起的不是数字键盘,既然type=number肯定是想输入数字的,所以需要优化,

希望改成默认唤起数字键盘

**Comment by chenjiahan** [comment]
iOS 系统上没有带小数点的数字键盘，输入整数的话推荐使用 digit 类型，输入小数只能使用全键盘

**Comment by CalmHarbin** [comment]
> iOS 系统上没有带小数点的数字键盘，输入整数的话推荐使用 digit 类型，输入小数只能使用全键盘

input标签type=number时ios上可以唤起26键,默认的是数字26键而不是字母26键,
Field组件设置type=number,解析的input标签type是text,这样唤起的肯定就是字母26键
建议解析成input标签的type=number而不是type=text

**Comment by chenjiahan** [comment]
使用 type="number" 会在 iOS 上导致这个 issue：https://github.com/youzan/vant/issues/5425

还有一种可选的做法是在 iOS 上使用 type="text"，在安卓上使用 type="number"，这样在安卓上的体验会好一些，但组件的行为会不一致

**Comment by chenjiahan** [comment]
已在 2.5.5 版本优化，支持数字键盘

**Comment by lwm98** [comment]
你好大大，我想做一个ip地址的输入框，出现以下困惑。
如果用field组件，type为number时，没有办法输入第二个小数点。如果用type为tel时，安卓可以完成该需求，但是ios上的键盘没有小数点。
如果用新组件 NumberKeyboard 数字键盘，又没办法和输入框很好配合，比如原生键盘难以禁止弹出，如果用readonly禁止弹出后，那个输入光标又无法控制。
所以，综上，想请问一下大大怎么可以改type为number时 允许用户输入第二个小数点

**Comment by CalmHarbin** [comment]
> 你好大大，我想做一个ip地址的输入框，出现以下困惑。
> 如果用field组件，type为number时，没有办法输入第二个小数点。如果用type为tel时，安卓可以完成该需求，但是ios上的键盘没有小数点。
> 如果用新组件 NumberKeyboard 数字键盘，又没办法和输入框很好配合，比如原生键盘难以禁止弹出，如果用readonly禁止弹出后，那个输入光标又无法控制。
> 所以，综上，想请问一下大大怎么可以改type为number时 允许用户输入第二个小数点

方式1、直接使用text类型，在提交时用正则验证 ，推荐

2、使用NumberKeyboard 数字键盘。自己做一个假光标
