### ISSUE TITLE
[Feature Request] 建议所有可以设置字体图标的组件支持自定义图标

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#5666]
### 这个功能解决了什么问题
目前只有icon组件是可以支持开发者自定义字体的,但是其他组件好像不能支持自定义字体比如Grid 宫格。

### 描述您想要的解决方案
建议所有可以设置字体的组件新增自定义字体支持

### 建议的API是什么样的
新增class-prefix自定义支持

**Comment by chenjiahan** [comment]
后续会支持

**Comment by chenjiahan** [comment]
已在 2.5.3 版本支持（几个常用的组件）
