### ISSUE TITLE
针对于自定义的地区列表  编码超出6位了 在选择的时候就会有问题了

### ISSUE THREAD

**Issue by kim163** [youzan/vant#5667]
针对于自定义的地区列表  编码超出6位了 在选择的时候就会有问题了

比如新疆 地区 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/65.html

**Comment by choutuan** [comment]
我也遇到同样的问题，请问你解决了吗

**Comment by chenjiahan** [comment]
推荐使用 Cascader 组件来实现
