### ISSUE TITLE
复选框搭配单元格组件使用

### ISSUE THREAD

**Issue by RookieExperts** [youzan/vant#5671]
<van-checkbox-group v-model="result">
  <van-cell-group>
    <van-cell
      v-for="(item, index) in list"
      clickable
      :key="item"
      :title="`复选框 ${item}`"
    >
      <van-checkbox slot="right-icon" :name="item" ref="checkboxes" />
    </van-cell>
  </van-cell-group>
</van-checkbox-group>
当给van-cell加上参数to="index",复选框不能被点击

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
