### ISSUE TITLE
[Bug Report] [Bug Report] DatetimePicker 选项过滤器返回结果错误

### ISSUE THREAD

**Issue by yulai841415** [youzan/vant#5672]
### 设备 / 浏览器
chrome

### Vant 版本
2.4.7

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-9d1uo" target="_blank">https://codesandbox.io/s/vant-issue-moban-9d1uo</a>

### 描述问题
选择年或月，不选择日的情况，点击确认后获取的当前日期不正确

**Comment by monsterboom** [comment]
应该是同一类bug，我这边出现的datetimePicker的bug问题很严重，@change和@confirm，都无效

**Comment by chenjiahan** [comment]
@monsterboom 事件无效不太可能，是不是使用姿势有问题

**Comment by chenjiahan** [comment]
这个链接中的用法需要在 filter 函数中基于 currentDate 动态计算返回的选项，而选项变更又可能会引起 currentDate 变化，产生循环计算。

目前组件内部的机制无法支持这样的用法，先 close 了，建议试试其他实现方式。
