### ISSUE TITLE
Tab标签 scrollspy属性滚动导航问题

### ISSUE THREAD

**Issue by a1455047031** [youzan/vant#5673]
设备 / 浏览器
ios chrome 

Vant 版本
2.4.4

Vue版本
2.6.11

描述问题
 不知道是不是公司项目用了scroll-into-view插件的问题,Tab标签 使用scrollspy内容可以平铺展示 但是滚动的时候 效果出不来 滚动的时候 不能定位, 然后我用了scroll了,滚动的时候监听了 
![image](https://user-images.githubusercontent.com/59533359/74625249-a68dcd80-5186-11ea-8838-a459b87658de.png),scrollTop坐标一直为0,

**Comment by a1455047031** [comment]
公司项目用了scroll-into-view插件 不知道是不是这个问题

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by a1455047031** [comment]
> 麻烦提供一下codeandbox重复现链接
我这个问题跟上个哥们说的滚动条如果不在window上而是在某个DOM上scrollspy就失效了并且使用粘时滚动条会导致标签NAV抖动目前业务靠定位出来使滚动调在window解决上,
我已经更新版本解决了,打扰了
