### ISSUE TITLE
form表单组件的props参数文档错误

### ISSUE THREAD

**Issue by thisAries** [youzan/vant#5674]
`<van-form input-align="right" error-message-align="right"></van-form>`
_Invalid prop: type check failed for prop "errorMessageAlign". Expected Boolean, got String with value "right"._

error-message-align：错误提示文案对齐方式，可选值为 center right

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.5.1 版本修复
