### ISSUE TITLE
[Bug Report] Icon组件字体图标显示为小方块

### ISSUE THREAD

**Issue by y451687300** [youzan/vant#5677]
### 设备 / 浏览器
Chrome

### Vant 版本
2.5.0

### Vue 版本
2.5.16

### 重现链接
<a href="http://xxx.com" target="_blank">http://xxx.com</a>

### 描述问题
之前在排查以为是插件的引入有问题
现在发现是icon的字体图标 显示成了小方块
看了网络请求vant-icon-db1de1.woff2这个字体文件是请求了的
请问我是不是还有什么依赖需要安装   或者是如何排查字体图标不显示

**Comment by chenjiahan** [comment]
> 是不是还有什么依赖需要安装

不需要安装依赖，理论上 woff2 字体加载完就可以展示

> 如何排查字体图标不显示

可以看下是不是安装了其他字体，产生了冲突

**Comment by bluesky59** [comment]
我也遇上了，接入企业微信后，ios显示无误，部分安卓机显示无误，较老版本的安卓机显示一个x带边框，请问题主最后怎么解决的

**Comment by Jackfinal** [comment]
求解
