### ISSUE TITLE
ImagePreview组件在屏幕大小发送变化时，其中的swipe组件宽度计算异常

### ISSUE THREAD

**Issue by Limsanity** [youzan/vant#5678]
复现：
<img width="1523" alt="WX20200218-011014@2x" src="https://user-images.githubusercontent.com/31369862/74674242-ef2ba200-51eb-11ea-988f-0cd3ffd8a8a1.png">
<img width="1711" alt="WX20200218-011046@2x" src="https://user-images.githubusercontent.com/31369862/74674251-f18dfc00-51eb-11ea-9727-82d44198a728.png">

原因分析：全局注册的ImagePreview隐藏时，如果触发了resize事件，此时swipe组件内与宽度计算有关的$el的width值为0，导致子元素swipe-track、swipe-item计算宽度都为0，此时再次调用ImagePreivew(...)，图片则无法显示。

workaround：通过css控制元素宽度

**Comment by chenjiahan** [comment]
确实存在这个问题，下个版本会修复掉

**Comment by chenjiahan** [comment]
已在 2.5.1 版本修复

**Comment by linsywu** [comment]
2.5.8中的ImagePreview存在相同问题，当软键盘弹出改变视窗大小后，ImagePreview中的van-swipe-item宽度变为0,图片不显示
