### ISSUE TITLE
popup组件调不起来，控制台报错Error in nextTick: "TypeError: Cannot set property 'zIndex' of undefined"

### ISSUE THREAD

**Issue by 1784196067** [youzan/vant#5679]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater
<van-popup v-model="show">内容</van-popup>
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
