### ISSUE TITLE
网站mobile预览未打开

### ISSUE THREAD

**Issue by Asher-Tan** [youzan/vant#5682]
貌似构建有问题，这个文件没内容 https://b.yzcdn.cn/vant/site-mobile.4872baf5.js

**Comment by powerdong** [comment]
@Asher-Tan 我这边示例也不展示，还以为自己网络的问题...

**Comment by michaelxiaohan** [comment]
我他么心态崩了呀 开发到一半

**Comment by caozhong1996** [comment]
确实存在这个问题

**Comment by kylewuyinhai** [comment]
我还以为我网络出问题了

**Comment by Jakevin** [comment]
我也以為是瀏覽器 或是 CDN壞了

**Comment by OSpoon** [comment]
手机版的直接白屏,请处理

**Comment by chenjiahan** [comment]
感谢反馈，网站已恢复，问题出现的原因是这个文件的 CDN 上传失败了

**Comment by guixue** [comment]
本地编译后，文档是正常打开的。

估计superman-cdn  上传 site-mobile.XXXX.js 不成功。

也可以使用本地文档。

1. 在 /package.json 里添加：

"build-site": "vant-cli build-site",

2. 执行  npm run build-site
3.  把 /site/mobile.html 和 /site/index.html 中的 

https://b.yzcdn.cn/vant/  替换为空格 即可，直接打开就可以看本地了。
