### ISSUE TITLE
[Bug Report] 组件内元素继承父组件 scope id: data-v-xxx, 如何实现或避免？

### ISSUE THREAD

**Issue by LiangWei88** [youzan/vant#5683]
### 设备 / 浏览器
PC/chrome

### Vant 版本
2.4.0

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-m27o6?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-m27o6?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
在使用 nav-bar 组件的时候，发现中间的标题文字会收到页面 scoped 的 css 影响。
查看元素发现子组件里面的 dom 继承了外面页面的 scope Id, 在标签中有相同的 data-v-xxxx

希望请教
1. 这个有没有办法避免？
2. 如果我想要开发 vant-ui 组件， 如何实现这个效果？

十分感谢

**Comment by a1455047031** [comment]
首先你这是在一个vue文件的html和css是一个地方的,就算你在style写scope,html和css是在一个作用域的,比如:在一个a.vue文件在style写scope在b.vue文件有a.vue一样的标签名他的样式是不受a.vue影响的,如果你一个vue文件 有多的相同的组件 想让他们之间的样式不一样,多套一层div呗

**Comment by LiangWei88** [comment]
> 首先你这是在一个vue文件的html和css是一个地方的,就算你在style写scope,html和css是在一个作用域的,比如:在一个a.vue文件在style写scope在b.vue文件有a.vue一样的标签名他的样式是不受a.vue影响的,如果你一个vue文件 有多的相同的组件 想让他们之间的样式不一样,多套一层div呗

我在 codesandbox 做了一个复现 demo
我写的就只有一个 vue 文件, 但是使用 vant 组件时, 发现组件内的内容跟我写的 vue 文件使用同一个域., 也就是我的页面(a.vue) 影响到了 vant 的内容 (b.vue)
但是正如你所说, 正常情况下, 子组件的内容( b.vue) 是不应该受父组件(a.vue)影响的.

**Comment by chenjiahan** [comment]
> 引用一下 Vue 官方文档的说明：使用 scoped 后，父组件的样式将不会渗透到子组件中。不过一个子组件的根节点会同时受其父组件的 scoped CSS 和子组件的 scoped CSS 的影响。这样设计是为了让父组件可以从布局的角度出发，调整其子组件根元素的样式。

因此子组件的根节点上带有 scopeId 是正常的逻辑，这个问题与 Vant 无关喔

建议在写选择器时留意下，规避子组件的根节点

**Comment by LiangWei88** [comment]
> 引用一下 Vue 官方文档的说明：
> 
> > 使用 scoped 后，父组件的样式将不会渗透到子组件中。不过一个子组件的根节点会同时受其父组件的 scoped CSS 和子组件的 scoped CSS 的影响。这样设计是为了让父组件可以从布局的角度出发，调整其子组件根元素的样式。
> 
> 因此子组件的根节点上带有 scopeId 是正常的逻辑，这个问题与 Vant 无关喔
> 
> 建议在写选择器时留意下，规避子组件的根节点

我说的不是同一个问题...
不是子组件根节点, 不是.
为什么父组件scoped 的样式会影响到子组件 "非!" 根节点的内容
请问有打开过给出的例子么?

**Comment by LiangWei88** [comment]
> 引用一下 Vue 官方文档的说明：
> 
> > 使用 scoped 后，父组件的样式将不会渗透到子组件中。不过一个子组件的根节点会同时受其父组件的 scoped CSS 和子组件的 scoped CSS 的影响。这样设计是为了让父组件可以从布局的角度出发，调整其子组件根元素的样式。
> 
> 因此子组件的根节点上带有 scopeId 是正常的逻辑，这个问题与 Vant 无关喔
> 
> 建议在写选择器时留意下，规避子组件的根节点

不是根节点, 不是,
我知道根节点的话会受到影响
我说的是, vant 组件内部, 非根节点的 内容, 受到了我写的 scoped 样式影响
所以想请教, 请看看我给出的例子
里面的文字, 不是根节点, 本来不应该受到影响的.

**Comment by chenjiahan** [comment]
噢噢，这个是因为 NavBar 是 functional 组件，所以内部的元素也会受到 scoped 的影响。不过 Vant 里面的 CSS 选择器都是有 `van-` 前缀的，留意一下不要命名冲突就好

**Comment by LiangWei88** [comment]
> 噢噢，这个是因为 NavBar 是 functional 组件，所以内部的元素也会受到 scoped 的影响。不过 Vant 里面的 CSS 选择器都是有 `van-` 前缀的，留意一下不要命名冲突就好

噢噢噢, 谢啦
