### ISSUE TITLE
日历组件 如果类型为时间段的话 不能选择同一天 必须选两天以上

### ISSUE THREAD

**Issue by jingkewei** [youzan/vant#5685]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
