### ISSUE TITLE
Tabbar里来回切换页面如何保持它们的原有状态

### ISSUE THREAD

**Issue by PhantomRay** [youzan/vant#5686]
比如有若干个页面，分别由tabbar导航菜单进入。在来回切换页面时，之前加载显示过的页面会重新刷新。

请问可以保持之前的页面内容，且保持其页面scroll的高度？

**Comment by chenjiahan** [comment]
保持之前的页面内容 -> 可以使用 Vue 自带的 keep-alive 组件

保持其页面scroll的高度 -> 这个需要自行记录下位置，然后 scrollTo 到对应位置

**Comment by Lliuxs** [comment]
如果不是点击tabbar keep-alive可以记住scroll的位置 但是点击tabbar的就不行  这是为什么
