### ISSUE TITLE
是时候出一个Drawer组件了

### ISSUE THREAD

**Issue by 15152929190** [youzan/vant#5687]
你好  是否可以添加一个Drawer组件

![image](https://user-images.githubusercontent.com/34436948/74819080-c9f97980-533a-11ea-96f8-46c852efa716.png)
![image](https://user-images.githubusercontent.com/34436948/74819125-e0073a00-533a-11ea-8bd4-a04607d577c9.png)

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议通过 Popup 组件自己实现一下
