### ISSUE TITLE
[Feature Request] 日历组件 时间段类型可以选择同一天

### ISSUE THREAD

**Issue by jingkewei** [youzan/vant#5688]
### 这个功能解决了什么问题
如果类型是时间段的情况下  可以选择同一天 比如筛选同一天从早到晚的数据 即达到既可以选择时间段又可以开始结束时间都是同一天

### 描述您想要的解决方案
类型为时间段的情况下 日历中的某天双击 即可以选择开始和结束时间都是这一天

### 建议的API是什么样的
日历中的某天双击 可以设置开始和结束时间是同一天

**Comment by chenjiahan** [comment]
后续会考虑支持

**Comment by evanyangg** [comment]
+1

**Comment by evanyangg** [comment]
本来想提 PR 的，看了下源码，对于样式和当前的描述的修改，感觉有点力不从心，没有找到.
@chenjiahan 是否可以优先支持一下这个
想法：
compareDay === 0 时，原来第二个时期为 null ，现在this.select([startDay, date], true)
然后修改第二次点击同一天的样式 border-radius 改为四角圆角
同时把文案从 开始 改为  开始 结束，四个字试了一下 可以放下。
最后方案 还请您斟酌

**Comment by chenjiahan** [comment]
这块还在和设计同学沟通，所以会稍微晚一点

**Comment by evanyangg** [comment]
四月初能够支持吗？我们产品上线，希望能支持，感谢。

**Comment by chenjiahan** [comment]
@evanyangg  安排上了，这周会发个版本支持

**Comment by evanyangg** [comment]
@chenjiahan 非常感谢！🤗

**Comment by chenjiahan** [comment]
已在 2.5.6 版本支持，设置 allow-same-day 属性即可

**Comment by jingkewei** [comment]
感谢~感谢~

**Comment by obrcnh** [comment]
可以默认选中同一天吗
