### ISSUE TITLE
遍历对象数组动态生成tab，active不起效

### ISSUE THREAD

**Issue by mfq1020** [youzan/vant#569]
`<van-tabs :active="active" @click="handleTabClick">`
`<van-tab v-for="nav in navList" :title="nav.name">`
`</van-tab>`
`</van-tabs>`

**Comment by qianzhaoy** [comment]
@mfq1020  这个问题我也遇到了，看了源码发现。初始化的时候，你`navList`是空数组，这时候设置`active`是没用的。会默认成 `0`。而组件watch `tabs` 的时候，取的是 `curActive`， 所以不会有效果。

你可以这样。如果 navList 为 零就先不渲染。
`<van-tabs :active="active" v-if=“navList.length”>`

**Comment by chenjiahan** [comment]
目前确实存在这个问题，我们会在下个版本优化

**Comment by mfq1020** [comment]
@qianzhaoy 添加v-if="navList.length"   已经解决问题。感谢。

**Comment by mfq1020** [comment]
@chenjiahan 有没有交流群？？方便快速交流。

**Comment by chenjiahan** [comment]
@mfq1020 欢迎入群交流~
<img width="300" src="https://user-images.githubusercontent.com/7237365/35320813-1755f826-0120-11e8-97c6-3d29e108113e.jpeg">

**Comment by chenjiahan** [comment]
已在 0.12.6 版本中修复
