### ISSUE TITLE
[Bug Report] vant-tab组件中的vant-sticky组件不起作用

### ISSUE THREAD

**Issue by lmx-Hexagram** [youzan/vant#5691]
### 设备 / 浏览器
chorme

### Vant 版本
2.5.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-40xy1?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-40xy1?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
请问怎样才能在tab中让sticky起作用

**Comment by chenjiahan** [comment]
问题原因是 Tabs 的 animated 属性会引入 transform 样式，导致内部的 fixed 布局失效

这个问题暂时无解，可以考虑去掉 animated 属性

**Comment by lmx-Hexagram** [comment]
okk 多谢
