### ISSUE TITLE
ImagePreview在IOS下，导致页面重载

### ISSUE THREAD

**Issue by WACCYZ** [youzan/vant#5692]
### 设备 / 浏览器
IOS,微信H5

### Vant 版本
2.4.7

### Vue 版本
2.3.3

### 重现链接
<a href="https://live.kuaishou.com/u/front-endKing/3x2hvjk35tq8ch9" target="_blank">视频链接一</a>
<a href="https://live.kuaishou.com/u/front-endKing/3x92waivjxdetzs" target="_blank">视频链接二</a>

### 描述问题
ImagePreview在IOS下，当图片数量过多，或者网络较慢的情况下，点击图片预览，或者滑动下一张预览时会导致页面重载。具体效果请依据重现链接里面的视频链接。具体我是通过组件的方式使用了该组件。初步判断可能是swiper导致,具体原因不明。后续这边会继续研究，也请大佬们看看

**Comment by chenjiahan** [comment]
上面的链接打开是失效的

是不是机型比较旧，图片太大导致内存满了

**Comment by WACCYZ** [comment]
> 上面的链接打开是失效的
> 
> 是不是机型比较旧，图片太大导致内存满了，可以考虑在前端压缩下图片

https://live.kuaishou.com/u/front-endKing/3x2hvjk35tq8ch9?did=web_1ef80dff116608e58c4434dcf595a93a

**Comment by WACCYZ** [comment]
> 上面的链接打开是失效的
> 
> 是不是机型比较旧，图片太大导致内存满了，可以考虑在前端压缩下图片

不是，iphone X，XR，XS Max， IOS版本12.3.1, 13.x都有出现

视频链接一：https://live.kuaishou.com/u/front-endKing/3x2hvjk35tq8ch9?did=web_1ef80dff116608e58c4434dcf595a93a
视频链接二：https://live.kuaishou.com/u/front-endKing/3x92waivjxdetzs?did=web_1ef80dff116608e58c4434dcf595a93a

**Comment by WACCYZ** [comment]
@chenjiahan

**Comment by chenjiahan** [comment]
看到视频了，能提供个 codesandbox 复现链接吗

**Comment by WACCYZ** [comment]
https://codesandbox.io/s/elated-moon-8d6tu，不过好像ImagePreView这个组件不起作用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 晚上7:31
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"再见"<a623859363@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] ImagePreview在IOS下，导致页面重载 (#5692)




看到视频了，能提供个 codesandbox 复现链接吗

**Comment by chenjiahan** [comment]
100 多张图片吗？

**Comment by WACCYZ** [comment]
是的，有的更多，实际项目中，用了懒加载


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 晚上8:57
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"再见"<a623859363@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] ImagePreview在IOS下，导致页面重载 (#5692)




100 多张图片吗？

**Comment by chenjiahan** [comment]
这么多的图片暂时没法解决噢。。建议考虑调整下交互形式

**Comment by WACCYZ** [comment]
> 这么多的图片暂时没法解决噢。。建议考虑调整下交互形式

能说下具体是什么原因导致的吗？

**Comment by chenjiahan** [comment]
估计是元素过多触发了浏览器的内存上限之类的

**Comment by WACCYZ** [comment]
> 估计是元素过多触发了浏览器的内存上限之类的

但是我改用微信的previewImage接口就好了

**Comment by chenjiahan** [comment]
微信的 previewImage 是原生组件，不是 web 渲染的
