### ISSUE TITLE
van-goods-action-icon组件info属性bu'sheng'xiao

### ISSUE THREAD

**Issue by liufei0123** [youzan/vant#5694]
![32b4225b63e99fb3e442b9a6f37a506](https://user-images.githubusercontent.com/28746227/74912979-b1509880-53fa-11ea-8c61-45613943b709.png)
![e7e334d1d9c30a1ff150e46ede74fd0](https://user-images.githubusercontent.com/28746227/74912984-b281c580-53fa-11ea-9cd5-9ef4fdbf2d9c.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
