### ISSUE TITLE
[Feature Request] Calendar组件增加close事件

### ISSUE THREAD

**Issue by rexsyj** [youzan/vant#5697]
### 这个功能解决了什么问题
目前日历组件只有select和confirm事件，但有时候用户点开日历没选择日期的情况下也需要进行数据处理，目前只能通过watch日历的show参数解决，增加close事件可以解决这个问题

### 描述您想要的解决方案
Calendar组件增加close事件

### 建议的API是什么样的
<van-calendar v-model="show" type="range" @confirm="onConfirm" @close="onClose"/>

**Comment by chenjiahan** [comment]
下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.5.2 版本支持
