### ISSUE TITLE
[Feature Request] Tab 标签页组件使用scrollspy sticky后，点击导航栏页面不跟随导航位置滚动？

### ISSUE THREAD

**Issue by veraGe** [youzan/vant#5699]
### 这个功能解决了什么问题
Tab 标签页组件使用scrollspy sticky后，点击导航栏页面不跟随导航位置滚动？

### 描述您想要的解决方案
Tab 标签页组件使用scrollspy sticky后，点击导航栏页面内容不跟随导航位置滚动？

### 建议的API是什么样的
没有使用

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接
