### ISSUE TITLE
地址编辑 areaList 请求后 赋值不可以？

### ISSUE THREAD

**Issue by lejsure** [youzan/vant#570]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
可以的
