### ISSUE TITLE
[Feature Request]新增select下拉框组件

### ISSUE THREAD

**Issue by yunexuan** [youzan/vant#5701]
### 这个功能解决了什么问题
在一个表单里需要多个下拉选择时，需要封装picker和popup组件，且下拉选择数据一般都是value text格式，传后端的是value以及前端的回显等，需要额外处理，目前的picker处理这个场景不太友好

### 描述您想要的解决方案
期望可以出一个类似于cube-ui的select组件，以更好的解决上述场景

### 建议的API是什么样的
类似于element-ui的el-select组件的api，v-model绑定的是value，界面显示对应的text

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议还是通过 Picker 自行封装

**Comment by phpcxy** [comment]
select还有一个重要的特性，支持多选。现在picker好像无法支持多选的情况吧~

**Comment by fightingcat** [comment]
vote +1

**Comment by 785029615** [comment]
这个很常用，建议加一个这个组件
