### ISSUE TITLE
为什么npm安装就会报错 安装不上，cnpm就没事

### ISSUE THREAD

**Issue by DuoDir** [youzan/vant#5702]
为什么npm安装就会报错 安装不上，cnpm就没事  求告知

**Comment by chenjiahan** [comment]
可能是你的网络问题，我这边是正常滴

**Comment by DuoDir** [comment]
![image](https://user-images.githubusercontent.com/27777607/75014646-bcbac700-54c1-11ea-8ddf-bb9f0443e0ee.png)

**Comment by DuoDir** [comment]
这是让 测试那边构建上包 出现的错误  然后自己本地npm试了一下 安装也会报错 请问谁遇见过嘛

**Comment by chenjiahan** [comment]
可以确认下你使用的 npm registry 是哪个，我试了下通过 npm 安装 2.5.2 是正常的

![image](https://user-images.githubusercontent.com/7237365/75015952-cc87da80-54c4-11ea-9c81-ec2450424c22.png)
