### ISSUE TITLE
form表单校验runValidator函数建议把当前rule传过来，便于拓展可用性

### ISSUE THREAD

**Issue by wuhao-max** [youzan/vant#5704]
在动态渲染的循环列表时，当前校验是需要根据当前行的其他字段来校验，但是vant没有提供校验时拿到当前行数据，在阅读你们源码后发现在执行validator时只把formValue传过来了，所以我修改了一下你们的源码。
可以像element-ui一样，把rule和value都返回，这样用户随便在rule里面自定义传入自己想传的值。
其实也就是在这里改一下就行了`return this.runValidator(rule.validator, rule)`
然后再:

`runValidator(validator, rule) {
      return new Promise(resolve => {
        const returnVal = validator(this.formValue, rule);

        if (isPromise(returnVal)) {
          return returnVal.then(resolve);
        }

        resolve(returnVal);
      });
    },`
然后自己在定义rules的时候这样传过来 `[{ validator: this.planCountValidator, message: '取消件数不得大于剩余总数', data: row }]`

**Comment by wu6658658** [comment]
可以像element-ui一样，把rule和value都返回，这样用户随便在rule里面自定义传入自己想传的值

**Comment by chenjiahan** [comment]
感谢反馈，Form 是新加的组件，所以还有一些不完善的地方，后续会加上 rule 参数和自定义 message 的能力

**Comment by chenjiahan** [comment]
已在 2.5.3 版本支持
