### ISSUE TITLE
[Feature Request] Vant Calendar组件可以支持某个时间范围内不连续多选吗？

### ISSUE THREAD

**Issue by zhaogaolei** [youzan/vant#5705]
### 这个功能解决了什么问题
比如：设置某几天的库存量，用户可以在某个时间范围内，选择任意不连续日期，进行设置

### 描述您想要的解决方案
目前支持type="single"和type="range"两种选择方式，建议可以再灵活一点，比如多选，设置type="multiple",就可以实现了

### 建议的API是什么样的
目前支持type="single"和type="range"两种选择方式，建议可以再灵活一点，比如多选，设置type="multiple"

**Comment by chenjiahan** [comment]
后续会考虑支持

**Comment by zhaogaolei** [comment]
目前我修改了源码，支持了type='multiple'，还没发现问题，不知是否会带来新的bug

**Comment by chenjiahan** [comment]
已在 2.5.4 版本支持
