### ISSUE TITLE
请允许我爆一下粗口，area.js是哪个小白新手写的？

### ISSUE THREAD

**Issue by xujinliang** [youzan/vant#5706]
省市区的area.js为什么不弄成json格式？这是什么新型格式？你们vant团队研发的什么玩意？
让服务端怎么生成这样的格式

**Comment by OnlyLady** [comment]
这位大佬，不会用就是不会用。你可以不用area啊，用picker级联不就行了  服务端生成key,value格式的数据就好了

**Comment by wg5945** [comment]
消消气，类似这样的拿去改改呗

```js
function formatColumns (list, parent = 0, result = []) {
  const p = list.filter(x => x.parent === parent)
  if (p && p.length) {
    result.push({
      values: p.map(x => x.name)
    })
    result = formatColumns(list.filter(x => x.parent !== parent), p[0].value, result)
  }
  return result
}
```

**Comment by chenjiahan** [comment]
可以用楼上的方法转换下

**Comment by nongzhenli** [comment]
真心讲，这个组件的写的很不友好，数据格式鹤立鸡群、也不支持对象设置code/value，且只能默认选择 省份code，那默认的市、区/县 就不要了、、、无语了，自己看着Picker改吧

**Comment by lizy0329** [comment]
area 组件确实需要做到一份通用 json+组件的组合，json 可以上传到npm上

**Comment by Henry-WHY** [comment]
> 可以用楼上的方法转换下

请问一下，如果要固定选择某个省内的市、区，是不是只能自行处理 areaList，组件没有特定的Props处理？
谢谢解答

**Comment by WenkeChen** [comment]
> 这位大佬，不会用就是不会用。你可以不用area啊，用picker级联不就行了 服务端生成key,value格式的数据就好了

最烦这种傻x发言了，都像你这样的态度开源鸡毛啊
