### ISSUE TITLE
[Bug Report] form.validate验证单个表单项会触发其他项验证

### ISSUE THREAD

**Issue by akebe** [youzan/vant#5707]
### 设备 / 浏览器
所有设备

### Vant 版本
2.5.2

### Vue 版本
3.0.0-alpha.5

### 重现链接
<a href="https://codepen.io/asseek/pen/NWqbvBZ" target="_blank">https://codepen.io/asseek/pen/NWqbvBZ</a>

### 描述问题
当mobile为空的情况下点击发送验证码按钮下面的验证码框会被一并validate。
当mobile有值的情况下，不管是否error，点击2次以上下面的验证码框有几率触发validate。

我只需验证单个表单项，结果是对的，但表单表现很迷，完全不受控

**Comment by chenjiahan** [comment]
因为你使用了 Button 组件来发送验证码，在浏览者中 Button type 的默认值是 submit，会触发表单提交。

需要把 Button 的 native-type 设置为 text

**Comment by akebe** [comment]
> 因为你使用了 Button 组件来发送验证码，在浏览者中 Button type 的默认值是 submit，会触发表单提交。
> 
> 需要把 Button 的 native-type 设置为 text

我试着设置`native-type="text"`好像不起作用？不过原因应该就是你说的，我加上`@click.prevent`修饰符就可以了

**Comment by chenjiahan** [comment]
上面口误了，正确的方式设置 native-type="button"

下个大版本我们会把 native-type 的默认值改为 button，这样更加合理
