### ISSUE TITLE
[Bug Report] calendar组件空指针异常

### ISSUE THREAD

**Issue by wg5945** [youzan/vant#5708]
### 设备 / 浏览器
all

### Vant 版本
2.5.2

### Vue 版本
2.6.10

### 描述问题
https://github.com/youzan/vant/blob/a83082f599362456d85864904cb5f47b44138e43/src/calendar/index.js#L177

这行代码会出现空指针异常，建议加个非空判断

![image](https://user-images.githubusercontent.com/5310295/75084396-cb08f180-555a-11ea-83cf-b11a7c54168f.png)

**Comment by chenjiahan** [comment]
scrollIntoView 方法中目前有通过 nextTick 来保证能取到 refs，请问这个异常是在什么情况下出现的喔

**Comment by wg5945** [comment]
我对calendar组件又做了一次封装，default-date是异步设置(比如接口返回等场景)的

https://codesandbox.io/s/vant-issue-moban-11q25

如果不能异步设置的话，我只能添加v-if="currentValue"条件了

**Comment by chenjiahan** [comment]
明白了👌 你的用法没问题，下个版本会修复下这个问题

**Comment by ytxDaXiong** [comment]
this.$refs.xxxxx.reset();也会报Error in nextTick: "TypeError: Cannot read property '1' of undefined"
这样的空指针

**Comment by chenjiahan** [comment]
是同个问题哈，会一并修复

**Comment by ytxDaXiong** [comment]
奥利给 @chenjiahan

**Comment by chenjiahan** [comment]
已在 2.5.3 版本修复
