### ISSUE TITLE
Toast组件能否触发多个

### ISSUE THREAD

**Issue by lmy1991** [youzan/vant#571]
目前：Toast只能出现一个
目标：实现type多个状态同时出现。且Toast.clear可以实现关闭指定type
BUG：在ssr项目中调用时，client端渲染时Vue.prototype.$toast为undefined

**Comment by chenjiahan** [comment]
@Imy1991 目前 Toast 是单例模式的，后续我们会支持多个实例
对于 Vue.prototype.$toast 为 undefined 的问题能否详细描述下复现步骤

**Comment by lmy1991** [comment]
import { Toast } from 'vant';
console.log(Vue.prototype.$toast); // undefined
官方文档不是说直接引入组件就可以获取到$toast么

**Comment by chenjiahan** [comment]
麻烦 check 下是不是 import { Toast } from 'vant'; 这句话在编译的时候被 webpack 当做未使用的变量干掉了

**Comment by lmy1991** [comment]
是的，确实被webpack干掉了

**Comment by chenjiahan** [comment]
已在 0.12.7 中支持同时弹出多个 Toast，详见文档
