### ISSUE TITLE
[Feature Request] 时间选择组件DatetimePicker实例报错 :TypeError: this.$refs.dateTimepicker.getPicker is not a function

### ISSUE THREAD

**Issue by 741075253** [youzan/vant#5710]
### 这个功能解决了什么问题
通过实例获取值，但是文档上的说明有错误

### 描述您想要的解决方案
可以向picker实例一样，使用getValues获取数据

### 建议的API是什么样的
同上

**Comment by chenjiahan** [comment]
文档上说明了，v2.4.0 版本以上支持，建议你检查下 Vant 版本，以及调用时组件是否已挂载

**Comment by 741075253** [comment]
> 
> 
> 文档上说明了，v2.4.0 版本以上支持，建议你检查下 Vant 版本，以及调用时组件是否已挂载

版本是最新版的2.5.2，也确定挂载了，可以通过this.$refs.xxx.value获取到值，遍历了实例，没有看到类似的方法

**Comment by chenjiahan** [comment]
那麻烦提供一下 codesandbox 复现链接

**Comment by chenjiahan** [comment]
复现了，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.5.3 版本修复
