### ISSUE TITLE
upload组件上传1.83GB电影导致浏览器页面崩溃

### ISSUE THREAD

**Issue by dolphinfine** [youzan/vant#5711]
### 设备 / 浏览器
chrome80

### Vant 版本
2.5.1

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
选择一个官方demo上传，我这里选择的是1.83Gb的玩具总动员电影，选择之后没反应，等一会儿，浏览器页面就崩溃了。
试了elementui，完全正常。

**Comment by chenjiahan** [comment]
大文件请使用 file 类型

![image](https://user-images.githubusercontent.com/7237365/75093278-2b2f8000-55bb-11ea-979a-6b31e9d18676.png)
