### ISSUE TITLE
[Bug Report] Grid宫格显示错误

### ISSUE THREAD

**Issue by boxinl** [youzan/vant#5712]
### 设备 / 浏览器
Google

### Vant 版本
2.4.7

### Vue 版本
2.6.8

### 描述问题
Grid宫格van-grid-item4列无法正确显示，都包在一个div里面;
html代码
<div>
   <van-grid>
	<van-grid-item icon="photo-o" text="文字" />
	<van-grid-item icon="photo-o" text="文字" />
	 <van-grid-item icon="photo-o" text="文字" />
	<van-grid-item icon="photo-o" text="文字" />
  </van-grid>
</div>
![image](https://user-images.githubusercontent.com/61399749/75127483-39d08100-56fa-11ea-981d-46e161e4101a.png)

**Comment by boxinl** [comment]
html代码
![image](https://user-images.githubusercontent.com/61399749/75127540-a0559f00-56fa-11ea-8e3f-96ce0ac5995f.png)

**Comment by OnlyLady** [comment]
你这个是引入的vue.js？？

**Comment by OnlyLady** [comment]
如果你的项目表示使用的Vue-cli创建的项目，是不能直接在html里面写标签的 需要使用template去解析

**Comment by boxinl** [comment]
> 你这个是引入的vue.js？？

使用的是vue.min.js结合vant.min.js，index.css，html页面元素也是能渲染，你可以用html页面测试一下这个宫格组件显示就知道有什么问题，若用官方例子使用van-grid-item显示自定义内容，即图片，显示就是正常

**Comment by chenjiahan** [comment]
Vue 不支持在 HTML 里直接使用自闭合表情，Vue 官方文档里有说明的，请使用完整的标签
