### ISSUE TITLE
[Bug Report] ActionSheet、Dialog组件出现动画僵硬

### ISSUE THREAD

**Issue by renlindong** [youzan/vant#5713]
### 设备 / 浏览器
iphone xr/ios13.3/chrome

### Vant 版本
2.5.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/" target="_blank">https://youzan.github.io/vant/#/zh-CN/</a>

### 描述问题
demo就是vant官网，所以vant版本和vue版本我没好好选。
反馈组件下的大部分组件出现动画很僵硬，没有过渡效果

**Comment by chenjiahan** [comment]
什么环境？如果是微信的话可以关掉微信进程试下，微信 web-view 有 bug

**Comment by renlindong** [comment]
iphone xr/ios13.3/chrome，打开官网的demo就有这种情况

**Comment by chenjiahan** [comment]
我这没问题，录个屏看下？

**Comment by daughterRui** [comment]
我这边也遇到了，所有的动画变成这样了
