### ISSUE TITLE
佬大，能否完善下navbar吗

### ISSUE THREAD

**Issue by 104828720** [youzan/vant#5714]
### 这个功能解决了什么问题
这样能让组件更完善，不再需要用css自己去修改了，因为navbar是很常用控件，所以颜色需求肯定需要的，希望vant越来越好

### 描述您想要的解决方案
增加3个属性，背景样式，字体颜色，字体选中颜色

### 建议的API是什么样的
你们是大佬，我是小白，你设计我都喜欢

**Comment by chenjiahan** [comment]
这几个样式比较好改，建议还是直接通过 css 覆盖，暂时没有计划提供 API 哦
