### ISSUE TITLE
你好。Collapse 折叠面板在change事件中，如何判断是展开状态还是关闭状态。只能通过自定义变量的方式判断么？要是change事件的参数能有第二个参数，值是true，表示展开，false表示关闭就好了。

### ISSUE THREAD

**Issue by Fagaiweizhuren** [youzan/vant#5715]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
