### ISSUE TITLE
ActionSheet组件建议新增离开页面自动关闭的功能

### ISSUE THREAD

**Issue by 841440416** [youzan/vant#5716]
问题：当组件缓存情况下，ActionSheet为true时回退页面，再次打开页面时，ActionSheet为true，还显示
建议：新增离开页面默认关闭，v-modal值设置为false
tip: 2.0版本不存在这个问题

**Comment by 841440416** [comment]
@chenjiahan  您好，您可以在[官网ActionSheet组件](https://youzan.github.io/vant/#/zh-CN/action-sheet) 重现，打开组建后浏览器回退上一页后再前进回到当前页，组件依然是打开状态

**Comment by 841440416** [comment]
为何反馈此建议：
1、优化用户体验
2、升级2.3X版本后出现bug,打开页面需要每次都重新将v-modal设置为false

**Comment by chenjiahan** [comment]
2.3.0 版本以前的默认行为是 keep-alive 离开时会关闭弹窗，后来有收到反馈，keep-alive 不应该改变组件的状态（#5243），所以目前的默认行为是 keep-alive 再次渲染后保持原先的状态。

后续我们会考虑加个属性来控制这一行为。

**Comment by 841440416** [comment]
> 2.3.0 版本以前的默认行为是 keep-alive 离开时会关闭弹窗，后来有收到反馈，keep-alive 不应该改变组件的状态（#5243），所以改成了 keep-alive 重新渲染后恢复原先的状态。
> 
> 后续我们会考虑加个属性来控制这一行为。

谢谢，我会保持关注

**Comment by chenjiahan** [comment]
已在 2.5.3 版本增加 close-on-popstate 属性，设置后在离开页面时会自动关闭

**Comment by 841440416** [comment]
> 已在 2.5.3 版本增加 close-on-popstate 属性，设置后在离开页面时会自动关闭

非常感谢

**Comment by 841440416** [comment]
> 已在 2.5.3 版本增加 close-on-popstate 属性，设置后在离开页面时会自动关闭

您好，希望pop弹出层组件van-popu也新增这个控制开关属性，感谢

**Comment by chenjiahan** [comment]
Popup 一直有的

**Comment by 841440416** [comment]
> Popup

不好意思，没仔细看

**Comment by Acesarye** [comment]
popup所在A页面使用了keep-alive，然后通过按钮显示popup，点击popup的按钮跳转到页面B，先将popup的v-model置为false再进行的跳转，进入B页面后再返回A页面，又进入B页面，然后返回A页面，popup弹窗又显示了，状态被置为true了，popup组件添加了close-on-popstate=true，这是什么情况？

**Comment by BarrierLeo** [comment]
> 2.3.0 版本以前的默认行为是 keep-alive 离开时会关闭弹窗，后来有收到反馈，keep-alive 不应该改变组件的状态（#5243），所以改成了 keep-alive 重新渲染后恢复原先的状态。
> 
> 后续我们会考虑加个属性来控制这一行为。

我在最近使用的过程中，遇到了keep-alive离开时ActionSheet是关闭的状态，返回会自动开启ActionSheet的问题
提了[issue](https://github.com/youzan/vant/issues/8186)，可以帮忙看看吗
