### ISSUE TITLE
tabs滚动导航，源码中这里，if (top > this.scrollOffset) {           return index === 0 ? 0 : index - 1;         }有问题，在点击第三个tab的时候，偶尔会跳转到第二个去，是不是可以在判断那的右边加一个5或者10

### ISSUE THREAD

**Issue by 23Dreamer** [youzan/vant#5717]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
