### ISSUE TITLE
[Bug Report] picker/area组件行内样式item-height导致无法被postcss-px-to-viewport转换

### ISSUE THREAD

**Issue by ccxryan** [youzan/vant#5718]
### 设备 / 浏览器
华为mate 30 pro

### Vant 版本
2.5.2

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/picker</a>

### 描述问题
picker组件的选项高度item-height（默认是44）这个。 编译后产生的行内样式无法被postcss-px-to-viewport转换成vw，最后渲染出来还是px单位的，会导致在大屏手机上显示高度异常的矮，选项都挤在一起。area组件也有同样的问题
![image](https://user-images.githubusercontent.com/9367366/75164113-3d482480-575b-11ea-996a-c3647a88ee58.png)
![image](https://user-images.githubusercontent.com/9367366/75164134-446f3280-575b-11ea-9aea-a95f33f30d1c.png)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3128
