### ISSUE TITLE
[Feature Request] Area增加和Picker组件一样的slot功能,另外单独新增海外选择组件

### ISSUE THREAD

**Issue by CalmHarbin** [youzan/vant#5719]
### 这个功能解决了什么问题
扩展选择省市区功能,比如我现在需要选择一个地址,又不能把海外和国内分成两个,我想点击之后弹出一个上拉的弹框,里面可以选择省市区,也可以有自己扩增的按钮,点击后选择海外.
1.不建议将海外国家放在picker里面去选,几百个国家让用户去滑动体验很差,需要一个搜索功能
2.所以建议单独做个海外国家选择器,

### 描述您想要的解决方案
改善用户体验

### 建议的API是什么样的
海外国家选择器,
顶部有个搜索功能
有热门国家,全部国家列表,右侧有通讯录一样的快速导航

**Comment by chenjiahan** [comment]
slot 会加上，海外选择器暂时没有计划支持哦

**Comment by chenjiahan** [comment]
已在 2.5.3 版本支持插槽
