### ISSUE TITLE
PullRefresh 下拉刷新增加direction

### ISSUE THREAD

**Issue by boxinl** [youzan/vant#5721]
### 这个功能解决了什么问题
目前只有下拉刷新，移动端列表数据有分页，一般是下滑，即上拉刷新加载数据

### 描述您想要的解决方案
增加direction参数

### 建议的API是什么样的
增加direction参数，可选up/down，并有相应的监听事件

**Comment by chenjiahan** [comment]
暂无计划支持，参见 https://github.com/youzan/vant/issues/3687

**Comment by boxinl** [comment]
> 暂无计划支持，参见 #3687
![image](https://user-images.githubusercontent.com/61399749/75303416-a030dd00-587b-11ea-8050-489212a206fc.png)

截图是使用上拉加载数据的APP页面，而使用van-list会出现ajax请求两次接口，接口请求会延迟，finished只有请求完才能知道是否为true

**Comment by chenjiahan** [comment]
> 使用van-list会出现ajax请求两次接口

理论上不会有这个问题，可能提供个 codesandbox 链接看下

**Comment by TKYV** [comment]
顶部都是固定的 为什么搜索 不可以设置不固定？
