### ISSUE TITLE
[Feature Request] Tabs组件开启scrollspy的问题

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#5722]
### 这个功能解决了什么问题
这里有个需求是tabs默认是不显示菜单标题,滑动到内容区之后再显示标题，然后根据scroll方法下的isFixed控制tabs的标题的展示与隐藏之后，滚动导航由于没有占位就会盖住vant-pane的一部分内容，请寻求一个好的实现建议，谢谢

### 描述您想要的解决方案
这里有个需求是tabs默认是不显示菜单标题,滑动到内容区之后再显示标题，然后根据scroll方法下的isFixed控制tabs的标题的展示与隐藏之后，滚动导航由于没有占位就会盖住vant-pane的一部分内容，请寻求一个好的实现建议，谢谢

### 建议的API是什么样的
这里有个需求是tabs默认是不显示菜单标题,滑动到内容区之后再显示标题，然后根据scroll方法下的isFixed控制tabs的标题的展示与隐藏之后，滚动导航由于没有占位就会盖住vant-pane的一部分内容，请寻求一个好的实现建议，谢谢，或者增加一个默认不显示标题title的属性

**Comment by chenjiahan** [comment]
可以试试设置 `opacity: 0;`
