### ISSUE TITLE
[Bug Report] SubmitBar 无法设置整数

### ISSUE THREAD

**Issue by TerryTer** [youzan/vant#5723]
### 设备 / 浏览器
谷歌浏览器，微信开发者工具

### Vant 版本
2.5.2

### Vue 版本
3.0.0-alpha.6

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-rbzm4" target="_blank">https://codesandbox.io/s/vant-issue-moban-rbzm4</a>

### 描述问题
用了SubmitBar组件，填入整数后，结果变成了小数，设置decimal-length为0也不行

**Comment by chenjiahan** [comment]
复现链接里是正常里，另外请注意 price 的单位是“分”而不是“元”
