### ISSUE TITLE
Bug: 文件上传组件 Uploader，上传状态 done 无效。

### ISSUE THREAD

**Issue by surnde** [youzan/vant#5724]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant/#/zh-CN/uploader

上传状态
通过status属性可以标识上传状态，uploading表示上传中，failed表示上传失败，done表示上传完成（从 2.4.7 版本开始支持）

uploading failed 都可以，就done 不行。 最新版。

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
done 是没有任何 UI 提示的，只会展示预览图
