### ISSUE TITLE
[Bug Report] Tab粘性布局下滚动导航点击tab会回弹

### ISSUE THREAD

**Issue by zhengki** [youzan/vant#5727]
### 设备 / 浏览器
ios13.3/safari、微信

### Vant 版本
2.5.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://zhengki.github.io/" target="_blank">https://zhengki.github.io/</a>

### 描述问题
真机上Tab粘性布局下滚动导航点击tab会回弹至刚好到视窗顶部的tab

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.5.4 版本修复

**Comment by kykolion** [comment]
还有这个bug啊@chenjiahan

**Comment by kykolion** [comment]
2.8.4版本还有这个问题
