### ISSUE TITLE
rem适配，postcss-pxtorem的rootValue问题，750px设计稿

### ISSUE THREAD

**Issue by uudiv** [youzan/vant#5728]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by uudiv** [comment]
vue 移动端项目；使用amfe-flexible和postcss-pxtorem做rem适配问题，由于设计稿为750px，所以再vue.config.js文件是这样配置的；
```
module.exports = {
  css: {
    loaderOptions: {
      postcss: {
        plugins: [
          require("postcss-pxtorem")({
            rootValue: 75, // 换算的基数,按设计稿的750/75
            propList: ["*"]
          })
        ]
      }
    }
  }
};
```
这样后，使用vantUi框架出现尺寸缩小问题，只能设置rootValue: 37.5，但是这样会跟我原有的有冲突；
如果分开设置转换？或者有其它更好的办法？

**Comment by jonnywang** [comment]
postcss.config.js
```
module.exports = ({ file }) => {
    let remUnit
    if (file && file.dirname && file.dirname.indexOf("vant")>-1) {
        remUnit = 37.5
    } else {
        remUnit = 75
    }
    return {
        plugins: {
            'postcss-pxtorem': {
                rootValue: remUnit,
                propList: ['*']
            },
            'autoprefixer': {}
        }
    }
}
```

**Comment by uudiv** [comment]
> postcss.config.js
> 
> ```
> module.exports = ({ file }) => {
>     let remUnit
>     if (file && file.dirname && file.dirname.indexOf("vant")>-1) {
>         remUnit = 37.5
>     } else {
>         remUnit = 75
>     }
>     return {
>         plugins: {
>             'postcss-pxtorem': {
>                 rootValue: remUnit,
>                 propList: ['*']
>             },
>             'autoprefixer': {}
>         }
>     }
> }
> ```

使用的vue-cli 4.22脚手架搭的，不是再vue.config.js里面配置吗?

**Comment by lmfuture** [comment]
module.exports = {
  plugins: {
    'autoprefixer': {
      overrideBrowserslist: [
        "Android >= 4.0",
        "iOS >= 7"
      ]
    },
    'postcss-pxtorem': {
      rootValue: 75,
      propList: ['*'],
      selectorBlackList: ['van']
    }
  }
}

我这边直接把vant忽略，需要调整单独进行了设置

**Comment by chenjiahan** [comment]
上面两位同学的方法都是 ok 的

**Comment by nongzhenli** [comment]
you 

> module.exports = {
> plugins: {
> 'autoprefixer': {
> overrideBrowserslist: [
> "Android >= 4.0",
> "iOS >= 7"
> ]
> },
> 'postcss-pxtorem': {
> rootValue: 75,
> propList: ['*'],
> selectorBlackList: ['van']
> }
> }
> }
> 
> 我这边直接把vant忽略，需要调整单独进行了设置

请教个问，如果直接忽略掉vant 样式转换，那么适配的意义就不存在了呀。

**Comment by lmfuture** [comment]
@nongzhenli 需要严格全局的适配请按照楼上的方式

**Comment by lmfuture** [comment]
@nongzhenli 但是你还是需要根据自己的需求进行适当的调整vant-组件的样式，比如设计图是750，你需要将你用到的组件样式选择性的放大2倍

**Comment by Deeeeeee** [comment]
> postcss.config.js
> 
> ```
> module.exports = ({ file }) => {
>     let remUnit
>     if (file && file.dirname && file.dirname.indexOf("vant")>-1) {
>         remUnit = 37.5
>     } else {
>         remUnit = 75
>     }
>     return {
>         plugins: {
>             'postcss-pxtorem': {
>                 rootValue: remUnit,
>                 propList: ['*']
>             },
>             'autoprefixer': {}
>         }
>     }
> }
> ```

有试过在vite2.0  版本中使用吗？ 我在vite中 file 获取不到

**Comment by bienvenidoY** [comment]
> > postcss.config.js
> > ```
> > module.exports = ({ file }) => {
> >     let remUnit
> >     if (file && file.dirname && file.dirname.indexOf("vant")>-1) {
> >         remUnit = 37.5
> >     } else {
> >         remUnit = 75
> >     }
> >     return {
> >         plugins: {
> >             'postcss-pxtorem': {
> >                 rootValue: remUnit,
> >                 propList: ['*']
> >             },
> >             'autoprefixer': {}
> >         }
> >     }
> > }
> > ```
> 
> 有试过在vite2.0 版本中使用吗？ 我在vite中 file 获取不到

```javascript
plugins: [
  pxtorem({
    rootValue({ file }) {
      // 修改rootValue
      if (file && file.indexOf('vant') > -1) {
        return 37.5
      } else {
        return 75
      }
    },
    unitPrecision: 4, // 保留小数位
    propList: ['*'],
    // selectorBlackList: [''], //过滤的类名
    replace: true, // 默认直接替换属性
    mediaQuery: false,
    minPixelValue: 6 // 所有小于设置的样式都不被转换
  })
]
```

**Comment by gaoxianglyx** [comment]
> > > postcss.config.js
> > > ```
> > > module.exports = ({ file }) => {
> > >     let remUnit
> > >     if (file && file.dirname && file.dirname.indexOf("vant")>-1) {
> > >         remUnit = 37.5
> > >     } else {
> > >         remUnit = 75
> > >     }
> > >     return {
> > >         plugins: {
> > >             'postcss-pxtorem': {
> > >                 rootValue: remUnit,
> > >                 propList: ['*']
> > >             },
> > >             'autoprefixer': {}
> > >         }
> > >     }
> > > }
> > > ```
> > 
> > 
> > 有试过在vite2.0 版本中使用吗？ 我在vite中 file 获取不到
> 
> ```js
> plugins: [
>   pxtorem({
>     rootValue({ file }) {
>       // 修改rootValue
>       if (file && file.indexOf('vant') > -1) {
>         return 37.5
>       } else {
>         return 75
>       }
>     },
>     unitPrecision: 4, // 保留小数位
>     propList: ['*'],
>     // selectorBlackList: [''], //过滤的类名
>     replace: true, // 默认直接替换属性
>     mediaQuery: false,
>     minPixelValue: 6 // 所有小于设置的样式都不被转换
>   })
> ]
> ```

感谢感谢

**Comment by charles-chenguojun** [comment]
....很诡异 我按照这个方法设置 vite 打包的时候 会不定时的随机出现 某个页面的rem 被放大一倍的情况

**Comment by leegcc** [comment]
> ....很诡异 我按照这个方法设置 vite 打包的时候 会不定时的随机出现 某个页面的rem 被放大一倍的情况

同样的问题🙋

**Comment by keminu** [comment]
> ....很诡异 我按照这个方法设置 vite 打包的时候 会不定时的随机出现 某个页面的rem 被放大一倍的情况

同样的问题，有解决方法嘛？

**Comment by keminu** [comment]
> > ....很诡异 我按照这个方法设置 vite 打包的时候 会不定时的随机出现 某个页面的rem 被放大一倍的情况
> 
> 同样的问题，有解决方法嘛？

初步排查是postcss-pxtorem 6.0版本引起的，
解决方案：依赖降级，以下几个依赖降级到
"autoprefixer": "^9.8.8",    
"postcss": "^7.0.32",
"postcss-pxtorem": "^5.1.1",

我这边这样降级后解决。

package.json 文件
`
"dependencies": {
    "@ant-design/icons-vue": "^6.0.1",
    "@iconify/iconify": "^2.0.4",
    "@sentry/tracing": "^6.17.9",
    "@sentry/vue": "^6.17.9",
    "@vueuse/core": "^10.5.0",
    "amfe-flexible": "^2.2.1",
    "axios": "^0.23.0",
    "crypto-js": "^4.1.1",
    "js-base64": "^3.7.2",
    "js-cookie": "^3.0.1",
    "lodash-es": "^4.17.21",
    "ls": "^0.2.1",
    "moment": "^2.29.4",
    "node-forge": "^1.3.1",
    "pinia": "^2.1.3",
    "pinia-plugin-persistedstate": "^3.2.0",
    "qs": "^6.11.0",
    "vant": "^4.7.2",
    "vue": "^3.3.4",
    "vue-request": "^1.2.4",
    "vue-router": "^4.2.1",
    "vue-types": "^4.2.1",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@commitlint/cli": "^13.2.1",
    "@commitlint/config-conventional": "^13.2.0",
    "@iconify/json": "^1.1.416",
    "@purge-icons/generated": "^0.7.0",
    "@types/fs-extra": "^9.0.13",
    "@types/inquirer": "^8.1.3",
    "@types/lodash-es": "^4.17.5",
    "@types/node": "^16.11.1",
    "@typescript-eslint/eslint-plugin": "^5.1.0",
    "@typescript-eslint/parser": "^5.1.0",
    "@vitejs/plugin-legacy": "^2.2.0",
    "@vitejs/plugin-vue": "^3.1.0",
    "@vitejs/plugin-vue-jsx": "^2.0.1",
    "@vitest/coverage-c8": "^0.23.4",
    "@vitest/ui": "^0.23.4",
    "@vue/compiler-sfc": "3.2.20",
    "@vue/test-utils": "^2.0.2",
    "autoprefixer": "^9.8.8",
    "commitizen": "^4.2.4",
    "conventional-changelog-cli": "^2.1.1",
    "cross-env": "^7.0.3",
    "dayjs": "^1.10.5",
    "dotenv": "^10.0.0",
    "esbuild": "^0.14.54",
    "eslint": "^8.0.1",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-define-config": "^1.1.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-vue": "^7.19.1",
    "esno": "^0.10.1",
    "fs-extra": "^10.0.0",
    "http-server": "^14.0.0",
    "husky": "^7.0.2",
    "inquirer": "^8.2.0",
    "is-ci": "^3.0.0",
    "jsdom": "^20.0.0",
    "less": "^4.1.2",
    "lint-staged": "^11.2.3",
    "md5-file": "^5.0.0",
    "minimist": "^1.2.8",
    "mockjs": "^1.1.0",
    "npm-run-all": "^4.1.5",
    "postcss": "^7.0.32",
    "postcss-pxtorem": "^5.1.1",
    "prettier": "^2.4.1",
    "pretty-quick": "^3.1.1",
    "rimraf": "^3.0.2",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-visualizer": "^5.5.2",
    "stylelint": "^13.13.1",
    "stylelint-config-prettier": "^9.0.3",
    "stylelint-order": "^4.1.0",
    "ts-node": "^10.3.0",
    "typescript": "^4.4.4",
    "vconsole": "^3.15.1",
    "vite": "^3.1.1",
    "vite-plugin-compression": "^0.3.5",
    "vite-plugin-eslint": "^1.8.1",
    "vite-plugin-html": "^2.1.1",
    "vite-plugin-imagemin": "^0.4.6",
    "vite-plugin-mkcert": "1.9.0",
    "vite-plugin-purge-icons": "^0.9.1",
    "vite-plugin-pwa": "^0.13.0",
    "vite-plugin-style-import": "^1.2.1",
    "vite-plugin-svg-icons": "^1.0.5",
    "vite-plugin-vconsole": "^2.0.1",
    "vite-plugin-vue-setup-extend": "^0.1.0",
    "vitest": "^0.23.2",
    "vue-eslint-parser": "^9.0.3",
    "vue-tsc": "^0.28.7"
  },
`
