### ISSUE TITLE
步进器禁用输入框后修改颜色，ios仍置灰显示

### ISSUE THREAD

**Issue by cheng11231456** [youzan/vant#5729]
ios与安卓对比![image](https://user-images.githubusercontent.com/41932574/75423989-d4d78e00-597a-11ea-97e2-4a0227390195.png)
![image](https://user-images.githubusercontent.com/41932574/75424068-ede03f00-597a-11ea-940d-6c22b439d432.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
