### ISSUE TITLE
能否增加一个table组件？这个经常用到。

### ISSUE THREAD

**Issue by jikoy** [youzan/vant#5731]
仔细看了一下，确实很强大很漂亮。
能否增加一个table组件？这个经常用到。

https://youzan.github.io/vant-issue-generater

**Comment by jikoy** [comment]
墙裂建议增加table功能。

**Comment by chenjiahan** [comment]
暂时没有计划添加噢

**Comment by ffzhihua** [comment]
![image](https://user-images.githubusercontent.com/8053824/84629470-ee4a1900-af1c-11ea-9355-7c21b275d66b.png)
要求增加table

**Comment by iniwf** [comment]
要求增加table
