### ISSUE TITLE
使用checkbox时，点击无效

### ISSUE THREAD

**Issue by taeyeat** [youzan/vant#5732]
基本复制实例操作，点击cell单元格并未有效果
<van-checkbox-group v-model="result">
                <van-cell-group>
                    <van-cell
                            v-for="(item, index) in inventList"
                            clickable
                            :key="item"
                            :title="`${item}`"
                            @click="toggle(index)"
                    >
                        <van-checkbox slot="right-icon"  ref="checkboxes" ></van-checkbox>
                    </van-cell>
                </van-cell-group>
 </van-checkbox-group>

data() {
      return {
        inventList: ['a', 'b'],
        result: [],
        checked: false
      }
    },

toggle(index) {
        this.$refs.checkboxes[index].toggle()
 }

返回如图的错误后，再次点击并未报错，但是没有效果
![image](https://user-images.githubusercontent.com/20273085/75462014-8946d380-59be-11ea-8d5a-73a5954a3a02.png)

![image](https://user-images.githubusercontent.com/20273085/75461897-5ef51600-59be-11ea-8f1d-782d274e8031.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
