### ISSUE TITLE
[Bug Report] vant Calendar PullRefresh刷新冲突

### ISSUE THREAD

**Issue by zhanghongyi001** [youzan/vant#5733]
### 设备 / 浏览器
所有

### Vant 版本
2.5.2

### Vue 版本
3.0.0-alpha.7

### 重现链接
<a href="https://pb4ht.csb.app/" target="_blank">https://pb4ht.csb.app/</a>

### 描述问题
全局使用PullRefresh组件时Calendar组件无法使用滚动选择

**Comment by chenjiahan** [comment]
事件冒泡引起的，在 Calendar 上设置 get-container="body" 即可
