### ISSUE TITLE
[Bug Report] van-field 组件 调用移动端设备数字规则 使用input  pattern="\d.*" 无法正常使用 请使用手机测试

### ISSUE THREAD

**Issue by zhanghongyi001** [youzan/vant#5734]
### 设备 / 浏览器
all

### Vant 版本
2.5.2

### Vue 版本
3.0.0-alpha.7

### 重现链接
<a href="https://iopfj.csb.app/" target="_blank">https://iopfj.csb.app/</a>

### 描述问题
van-field 组件 调用移动端设备数字规则 使用input  pattern="\d.*" 无法正常使用 请使用手机测试
使用input pattern="\d.*"  可以调取手机数字加点键盘的  van-field无法直接调取数字加 . 全键盘 需求是要输入0.00

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5665
