### ISSUE TITLE
vant配置typescript使用按需加载的时候，打包样式没打包进来

### ISSUE THREAD

**Issue by ZhengXiaowei** [youzan/vant#5735]
使用vue+ts+vant开发环境中样式正常，打包后样式文件没打包进来，标签上是有vant样式名称的。
是否和vue-cli脚手架中`css.requireModuleExtension`属性有关，我关闭后打包出来的结果其实也一样。

**Comment by ZhengXiaowei** [comment]
解决了，应该是`ts-loader`在多线程下的打包会丢失组件库样式，只要在`vue.config.js`里设置`parallel :false`就可以解决。

**Comment by chenjiahan** [comment]
好的👌

**Comment by cp1001** [comment]
> 解决了，应该是`ts-loader`在多线程下的打包会丢失组件库样式，只要在`vue.config.js`里设置`parallel :false`就可以解决。

it works

**Comment by tcstory** [comment]
遇到同样的问题, 设置 `parallel :false` 就解决掉了, 不懂关闭后, 是不是会降低构建的速度
