### ISSUE TITLE
[Bug Report] 弹窗过渡动画失效

### ISSUE THREAD

**Issue by renlindong** [youzan/vant#5736]
### 设备 / 浏览器
iphone 11 pro/ios13.3/chrome

### Vant 版本
2.5.3

### Vue 版本
3.0.0-alpha.7

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/action-sheet" target="_blank">https://youzan.github.io/vant/#/zh-CN/action-sheet</a>

### 描述问题
抱歉，之前一直没时间去录视频。怀疑这是一个浏览器bug。在初次进入demo时，过渡动画是有效的。但是在切换了几次浏览器窗口之后，再回到vant demo页面，页面上所有过渡动画都失效了

**Comment by renlindong** [comment]
录屏我发送到你的邮箱了

**Comment by chenjiahan** [comment]
视频看到咯，看起来确实是浏览器的 bug

Vant 组件的动画逻辑是基于 Vue 的 transition 标签实现的，没有特殊逻辑，所以这个问题在组件层面应该无法解决，issue 先 close 咯
