### ISSUE TITLE
van-field input框 行高影响

### ISSUE THREAD

**Issue by Estelle00** [youzan/vant#5737]
希望在此添加，使其继承父类，避免normalize.css影响行高
```css
line-height: inherit;
```
https://github.com/youzan/vant/blob/a2911289fd05a035150f46de471eaea82512db85/src/field/index.less#L28-L40

**Comment by chenjiahan** [comment]
可以滴，下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.5.4 版本支持
