### ISSUE TITLE
[Bug Report] van-list 在iphone 8p 下 如果页面有弹层的input请求过滤数据，当关闭弹层重新请求数据会出现 第一条数据无法到0的位置

### ISSUE THREAD

**Issue by ijunwu** [youzan/vant#5738]
### 设备 / 浏览器
iPhone 8p

### Vant 版本
2.5.2

### Vue 版本
2.5.2

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/list" target="_blank">https://youzan.github.io/vant/#/zh-CN/list</a>

### 描述问题
van-list 在iphone 8p 下 如果页面有弹层的input请求过滤数据，当关闭弹层重新请求数据会出现 第一条数据无法到0的位置
或者请教van-list有没有强制办法回到页面顶部的 尝试过input失去焦点强制window.scrollTo(0,0) 并无效果

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

回到页面顶部用 scrollTo 是有效的，除非自定义了滚动容器
