### ISSUE TITLE
底部Tabbar被手机软键盘顶起

### ISSUE THREAD

**Issue by hopeaktian** [youzan/vant#5739]
**Describe the bug**
Tabbar和Form表单在一个页面中时，点击表单输入框，手机软键盘弹出，然后原本fixed在底部的Tabbar被顶起 
**Screenshots**
正常情况：
![S00301-20514305](https://user-images.githubusercontent.com/29337299/75626095-7838d500-5bff-11ea-9a08-3a248d9487e6.png)
输入时，底部Tabbar被顶起来：
![S00301-20504774](https://user-images.githubusercontent.com/29337299/75626098-7bcc5c00-5bff-11ea-850d-11bd48eeed04.png)

**Environment**
Device: 魅族16X
Browser: 微信浏览器
Vant Version: vant-2.5.2

**Reproduce**
http://ink.wayen.tech/#/mine/login

**Comment by chenjiahan** [comment]
可以设置个 `body { min-height: 100vh; };` 试下

**Comment by hopeaktian** [comment]
> 可以设置个 `body { min-height: 100vh; };` 试下

试了下，还是不行，虽然高度增加了，但是Tabbar依旧会被顶起

**Comment by chenjiahan** [comment]
这个是系统浏览器的行为决定的，组件层面暂时没有解决方法。

可以去网上搜一下，有一些 hack 的方案可以绕过这个问题（比如 focus 时隐藏 Tabbar）

**Comment by wzjiscode** [comment]
> 这个是系统浏览器的行为决定的，组件层面暂时没有解决方法。
> 
> 可以去网上搜一下，有一些 hack 的方案可以绕过这个问题（比如 focus 时隐藏 Tabbar）

我的输入框在底部不能隐藏怎么处理
