### ISSUE TITLE
[Bug Report] image 组件 Invalid prop: type check failed for prop "src". Expected String with value "[object Module]", got Module

### ISSUE THREAD

**Issue by HellsingMatt** [youzan/vant#5740]
### 设备 / 浏览器
Chrome 80.0.3987.122

### Vant 版本
2.5.3

### Vue 版本
2.6.10

### 重现链接
<a href="http://blah.blah" target="_blank">http://blah.blah</a>

### 描述问题
image 组件遇到个很奇怪的问题，引入某张本地图片 :src="require('@/assets/img/xxx.png')" 在浏览器控制台报错：Invalid prop: type check failed for prop "src". Expected String with value "[object Module]", got Module

但是另外一张图就正常，就很懵逼

**Comment by chenjiahan** [comment]
这个是 vue-loader 和 url-loader 的配置问题，参见 https://github.com/vuejs/vue-loader/issues/1612

**Comment by HellsingMatt** [comment]
这得咋学才能知道有这种配置啊orz

**Comment by chenjiahan** [comment]
善用 google，哈哈
