### ISSUE TITLE
Area组件，可否支持只选择一级？或者选择到第二级

### ISSUE THREAD

**Issue by candyAndBella** [youzan/vant#5741]
Area组件，3层的时候，默认就是选择到第三级了。默认就是北京市，北京市，东城区
能否支持，只选择第一级（北京市），只选择到第二级？（北京市，北京市）

**Comment by chenjiahan** [comment]
columns-num 属性。

**Comment by candyAndBella** [comment]
是三个模式同时支持。显示三级，可以只选一级，也可以选到第三级

**Comment by candyAndBella** [comment]
按城市筛选，可以筛选到整个河北省，可以筛选到整个河北省石家庄市，也可以筛选到河北省石家庄市长安区。

**Comment by chenjiahan** [comment]
这种模式暂时不会支持喔

**Comment by candyAndBella** [comment]
希望第二级和第三级，有默认的‘请选择’。这样就可以在三级的模式下，选择到第一级，和第二级

**Comment by chenjiahan** [comment]
你可以在 areaList 里加一个对应的字段试试
