### ISSUE TITLE
[Bug Report] babel-plugin-import无效，只能手动引入？

### ISSUE THREAD

**Issue by ZeronoFreya** [youzan/vant#5742]
### 设备 / 浏览器
谷歌浏览器80版本

### Vant 版本
2.5.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/ZeronoFreya/vant-demo" target="_blank">https://github.com/ZeronoFreya/vant-demo</a>

### 描述问题
我使用babel-plugin-import时，无法加载样式，但手动按需加载样式是可以显示的，
请问这是什么问题导致的呢？

**Comment by chenjiahan** [comment]
仓库里并没有配置 babel-plugin-import.
