### ISSUE TITLE
[Bug Report] Field 的 show-word-limit 属性有问题

### ISSUE THREAD

**Issue by wynova** [youzan/vant#5744]
### 设备 / 浏览器
任何平台

### Vant 版本
2.5.3

### Vue 版本
2.5.16

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-v2sf8" target="_blank">https://codesandbox.io/s/vant-issue-moban-v2sf8</a>

### 描述问题
<van-field label="备注" placeholder="请输入备注" :show-word-limit="true" maxlength="200" type="textarea" rows="3" autosize></van-field>
会报错：
TypeError: Cannot read property 'length' of undefined

**Comment by chenjiahan** [comment]
使用 Field 组件时，需要通过 v-model 绑定输入值

**Comment by wynova** [comment]
谢谢

> 使用 Field 组件时，需要通过 v-model 绑定输入值

谢谢指正
