### ISSUE TITLE
[Bug Report] ImagePreview 图片预览 黑屏（只显示遮罩层）

### ISSUE THREAD

**Issue by jojo-1995** [youzan/vant#5746]
### 设备 / 浏览器
pc （google） app(  ios  android )

### Vant 版本
2.4.1

### Vue 版本
2.5.16

### 重现代码  
image_preview() {
  if( this.setInfo && this.setInfo.photo && this.setInfo.photo['360']){ // 这边是对象传递 偶然会黑屏？
            ImagePreview({
              images: [
                 this.setInfo.photo['360']
               ],
              showIndex: false,
            });
          }
      }
![微信图片_20200302195828](https://user-images.githubusercontent.com/24888623/75674613-6a975400-5cc0-11ea-8a58-ac1c24462645.png)

### 描述问题
pc （google） app(  ios  android )，几乎在所有的机子上，图片预览，有时候会出现黑屏，也就是只出现遮罩层，没有图片。查看了下元素，img是在的，但是宽度是0，所以显示不出来。

**Comment by chenjiahan** [comment]
请确保传递了正确的图片 URL，重现链接无法运行

**Comment by jojo-1995** [comment]
你好，图片是正确的url，查看元素，图片是在的，但是width是0，所以图片显示不出来。以上是我在项目中的代码

**Comment by jojo-1995** [comment]
> 
> 
> 请确保传递了正确的图片 URL，重现链接无法运行

你好，图片是正确的url，查看元素，图片是在的，但是width是0，所以图片显示不出来。以下是我在项目中的代码
image_preview() {
if( this.setInfo && this.setInfo.photo && this.setInfo.photo['360']){ // 这边是对象传递 偶然会黑屏？
ImagePreview({
images: [
this.setInfo.photo['360']
],
showIndex: false,
});
}
}

**Comment by chenjiahan** [comment]
width 是 0 说明图片没有正常加载，你的图片 URL 是啥？

**Comment by jojo-1995** [comment]
> 
> 
> width 是 0 说明图片没有正常加载，你的图片 URL 是啥？

图片是http或者https的图片，有时候能显示出来，有时候就突然变成了width:0;
https://ecosaas-portal.oss-cn-hangzhou.aliyuncs.com/test/common/portal/headicon/986.7221361121403bayertest103513852.jpg?Expires=1583206196&OSSAccessKeyId=LTAIdA6HvWoakh2x&Signature=m4XcUslrbahTE6KNoktjh73bum4%3D&x-oss-process=image%2Fresize%2Cm_lfit%2Ch_600%2Cw_600

**Comment by chenjiahan** [comment]
这个大概率还是图片加载的问题，你可以抓包看下

**Comment by jojo-1995** [comment]
> 
> 
> 这个大概率还是图片加载的问题，你可以抓包看下

**Comment by jojo-1995** [comment]
> 
> 
> 这个大概率还是图片加载的问题，你可以抓包看下

**Comment by Jintao-Qu** [comment]
确实玄学，me too

**Comment by lunajing** [comment]
怎么就关闭了？ 读取本地图片时也会出现这样的问题，图片格式Base64； 有时候只显示黑色弹层

**Comment by ftsamoyed** [comment]
一样的问题，是移动端弹出输入法的时候，会自动把van-swipe__track和van-swipe__item的宽度都给置成0，再加载图片（即使是本地）也不出来，确实需要修复啊

**Comment by ftsamoyed** [comment]
害，vant升级到2.5.6一切无事发生了

**Comment by chenjiahan** [comment]
能复现的同学可以提供下 codesandbox 链接

**Comment by qiangf811** [comment]
我也遇到同样的问题~

**Comment by xfFelix** [comment]
原因是样式问题，width属性设置成了0，更新版本到2.9.3

**Comment by EmiyaGm** [comment]
升级到 2.10.12 又出现了
