### ISSUE TITLE
https://img.yzcdn.cn/vant/vant-icon-db1de1.woff2  微信认定为服务器证书无效

### ISSUE THREAD

**Issue by ccz-Eric** [youzan/vant#5747]
https://img.yzcdn.cn/vant/vant-icon-db1de1.woff2  微信认定为服务器证书无效。导致微信下所有图标失效
![image](https://user-images.githubusercontent.com/14230248/75693890-a3482500-5ce2-11ea-9ca0-306ead39c455.png)

**Comment by chenjiahan** [comment]
试了下官方文档可以正常展示呢，确定不是其他问题吗

**Comment by ccz-Eric** [comment]
https://img.yzcdn.cn/vant/vant-icon-db1de1.woff2  可以

> 试了下官方文档可以正常展示呢，确定不是其他问题吗

PC端是正常的。微信有https验证，可以尝试把这个链接https://img.yzcdn.cn/vant/vant-icon-db1de1.woff2   通过微信或者企业微信打开，将会得到错误提示

**Comment by ccz-Eric** [comment]
> 试了下官方文档可以正常展示呢，确定不是其他问题吗

就在刚刚我又尝试了下，已经恢复正常了。但是我能确定昨晚是肯定出现问题了。是否考虑将woff字体文件存放在本地，而不是去请求外部字体。对于一个UI框架来说，通过请求去拉取外部字体，我觉得是弊大于利的。

**Comment by chenjiahan** [comment]
文档里有本地字体的使用方式的

https://youzan.github.io/vant/#/zh-CN/icon#shi-yong-ben-di-zi-ti-wen-jian
