### ISSUE TITLE
[Bug Report] Checkbox 复选框

### ISSUE THREAD

**Issue by jiahui336** [youzan/vant#5748]
### 设备 / 浏览器
ios

### Vant 版本
2.5.3

### Vue 版本
3.0.0-alpha.7

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/checkbox" target="_blank">https://youzan.github.io/vant/#/zh-CN/checkbox</a>

### 描述问题
复选框没有水平排列的属性吗？

**Comment by chenjiahan** [comment]
有的，direction 属性，示例文档漏了，后续会补充下

**Comment by jiahui336** [comment]
但是我写上不起作用

**Comment by chenjiahan** [comment]
2.5.0 以上版本支持

**Comment by jiahui336** [comment]
我是2.5.3

**Comment by jiahui336** [comment]
我写错了 ，sorry
