### ISSUE TITLE
动态改变item.status，item.status = true 但是无效

### ISSUE THREAD

**Issue by webgj** [youzan/vant#5749]
"vant": "2.5.2"
代码：
`<van-cell v-for="(item,i) in list" :key="i">
  <van-button :disabled="item.status" size="mini" @click="onChangeItem(item)">按钮</van-button>
</van-cell>`
onChangeItem中设置 item.status = true， 但是按钮没变成disabled状态

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
