### ISSUE TITLE
[Bug Report]js Calendar 手动隐藏时，自动打开Calendar

### ISSUE THREAD

**Issue by zhuxinghan2016** [youzan/vant#5750]
设备 / 浏览器
浏览器

Vant 版本
2.5.3

Vue 版本
2.6.1

重现链接
https://youzan.github.io/vant/#/zh-CN/calendar

描述问题
用js实现vant，Calendar打开正常， 手动隐藏时，vant自动打开Calendar，无法关闭Calendar

**Comment by BellaHao** [comment]
已经解决了吗？怎么做的？
