### ISSUE TITLE
Calendar组件，我在平铺展示的时候，设置了日期的范围，并且设置了default-date，能否有办法主动跳转到default-date所在的日期，而非日期范围的开始日期呢？

### ISSUE THREAD

**Issue by CNliushuang** [youzan/vant#5753]
Calendar组件，我在平铺展示的时候，设置了日期的范围，并且设置了default-date，能否有办法主动跳转到default-date所在的日期，而非日期范围的开始日期呢？

**Comment by wang475293638** [comment]
你犯了和我同样的错误  日历是范围的时候  时间接收一个数组  时间范围的数组

**Comment by wang475293638** [comment]
[new Date(Date.now()-1000*3600*24),new Date()]

**Comment by wang475293638** [comment]
1000*3600*24 *号怎么复制没了

**Comment by smalltimoo** [comment]
[new Date(Date.now()-1000*3600*24),new Date()] 这个区间是给哪个props设置的

**Comment by smalltimoo** [comment]
不是选择日期区间，而是限制选择日期范围

**Comment by xiaoming0827** [comment]
这都是啥？不是选择区间呀，就是选择单个日期也无法定位啊

**Comment by xiaoming0827** [comment]
> 你犯了和我同样的错误 日历是范围的时候 时间接收一个数组 时间范围的数组

选择单个日期呢？和范围有啥关系呢？
