### ISSUE TITLE
[Bug Report] 不使用脚手架安装的项目，表单组件只渲染一个

### ISSUE THREAD

**Issue by heny** [youzan/vant#5754]
### 设备 / 浏览器
浏览器

### Vant 版本
2.5.3

### Vue 版本
3.0.0-alpha.7

### 重现链接
<a href="https://codesandbox.io/s/wispy-wave-nytnd" target="_blank">https://codesandbox.io/s/wispy-wave-nytnd</a>

### 描述问题
当使用vue脚手架用form组件时，可以正常渲染，重现链接：https://codesandbox.io/s/nifty-maxwell-y5hqp；
如果不使用脚手架的时候用form组件渲染，只渲染一个元素，重现链接：https://codesandbox.io/s/wispy-wave-nytnd；
我是直接复制vant官方的form组件第一个示例直接使用的

**Comment by chenjiahan** [comment]
Vue 不支持在 HTML 里直接使用自闭合标签，Vue 官方文档里有说明的，请使用完整的标签

**Comment by heny** [comment]
嗯，确实可以了，因为直接复制你们写的标签，所以没想到自闭合去；
刚测试又发现一个bug，提交功能用不了，在脚手架测试可用
重现链接：https://codesandbox.io/s/wispy-wave-nytnd，
写的验证功能不可用了，由于项目只有一个页面，所以没用脚手架，

**Comment by chenjiahan** [comment]
版本不对，你用的还是 2.4

**Comment by chenjiahan** [comment]
换成 `https://cdn.jsdelivr.net/npm/vant@2.5/lib/vant.min.js`

**Comment by heny** [comment]
可以了，谢谢，你们首页还没改过来=-=

**Comment by chenjiahan** [comment]
嗯嗯，首页这几天会改掉

**Comment by heny** [comment]
嗯，开发人员辛苦了
