### ISSUE TITLE
calendar组件不支持年份单独选择,设置最小日期和最大日期相差比较大时,加载很慢

### ISSUE THREAD

**Issue by Sjling** [youzan/vant#5756]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
时间跨度较大时，建议使用 DatetimePicker 组件呢
