### ISSUE TITLE
[Bug Report] tabs组件默认会选中第一个，无法更改

### ISSUE THREAD

**Issue by lisensen1126** [youzan/vant#5758]
### 设备 / 浏览器
pc,mobile

### Vant 版本
2.5.3

### Vue 版本
3.0.0-alpha.7

### 重现链接
<a href="https://uat-h5.nownews.com/" target="_blank">https://uat-h5.nownews.com/</a>

### 描述问题
在v-model中，设置了不是当前tabs的识别符，会自动设置为第一个为active.

**Comment by chenjiahan** [comment]
无效的重现链接
