### ISSUE TITLE
能否去除cell的下边框线

### ISSUE THREAD

**Issue by 2017lhy** [youzan/vant#576]
有没有参数可以决定是否显示cell单元格的下边框线，使用border=“false” 没什么用啊
![image](https://user-images.githubusercontent.com/34560558/35367213-3cdae3d4-01b8-11e8-805f-51219f961fa1.png)

**Comment by chenjiahan** [comment]
请问冒号加了吗，不加冒号的话属性会被识别成 string 类型
```
:border="false"
```

**Comment by 2017lhy** [comment]
哦，好吧，犯了个低级错误
