### ISSUE TITLE
[Bug Report] calendar 不能定位到

### ISSUE THREAD

**Issue by smalltimoo** [youzan/vant#5760]
### 设备 / 浏览器
任意设备

### Vant 版本
2.5.3

### Vue 版本
3.0.0-alpha.7

### 描述问题
vant calendar组件，设置了mindate maxdate defaultValue的值，默认值已经设置上了但是视图还是在开始日期上是咋回事

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接，或者看下是不是这个问题 https://github.com/youzan/vant/issues/5753

**Comment by smalltimoo** [comment]
他描述的不太详细，不过看情况应该是的
example：
vue： `<van-calendar color="#3d71ff" :min-date="minDate"
  :max-date="maxDate" :default-date="today"  v-model="showdatepicker" @confirm="onConfirm" />`
script: `minDate: new Date(2000, 0, 1),
      maxDate: new Date(2030, 0, 31),
      today:new Date()`
结果和我预期的不一样，应该是弹出日期选择框应该选择了今天并且可视区域应该是当前月份
但是测试结果却只选择了当前日期，可视区域却是设置的minDate月份

**Comment by smalltimoo** [comment]
不是选择日期区间，而是限制选择日期范围

**Comment by chenjiahan** [comment]
默认 showdatepicker 为 true 的话会出现这个问题，下个版本会修复下

**Comment by smalltimoo** [comment]
不，默认为false也会，点击按钮将showdatepicker 置为true 也会

**Comment by chenjiahan** [comment]
有 codesandbox 复现链接吗

**Comment by chenjiahan** [comment]
发了 2.5.4 版本，可以试下

**Comment by xiaoming0827** [comment]
> 发了 2.5.4 版本，可以试下

2.8.4 版本还有这个问题呢，设置default-date 平铺的日历不能定位到选中值这块，而是从nin-date开始，需要手动滚动才行

**Comment by chenjiahan** [comment]
@xiaoming0827 提供下 codesandbox 复现链接

**Comment by cnsilvan** [comment]
这个bug还是存在。展示的时候是min-date的位置，而不是default-date

**Comment by smalltimoo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
