### ISSUE TITLE
懒加载组件 ，图片被连续加载两次

### ISSUE THREAD

**Issue by jingxiaotian** [youzan/vant#5761]
### 设备 / 浏览器
Chrome模拟器

### Vant 版本
2.5.2

### Vue 版本
2.6.10

### 重现链接
<a href="http://meiyou.com" target="_blank">http://meiyou.com</a>

### 描述问题
反正就这个问题呀，链接不上了。使用懒加载组件在network中看到图片被加载了两次

**Comment by ZhengQingFeng** [comment]
你是不是把disable cache勾选了

**Comment by chenjiahan** [comment]
楼上正解，Chrome 控制台 disable cache 导致的

**Comment by cxyqts1024** [comment]
干得漂亮，一下解决了疑惑
