### ISSUE TITLE
Uploader组件上传视频获取到的文件大小file.size为0

### ISSUE THREAD

**Issue by nanaMonsoon** [youzan/vant#5762]
设备 / 浏览器
iphone6 6S XR等机型

Vant 版本
2.4.2

Vue 版本
2.6.10

重现链接

描述问题
h5 打包成ios之后 iphone6 iphone6s XR等多个机型  Uploader组件, 上传视频, 选择手机本地视频上传, 视频获取到的file.size为0, 文件名和文件类型可以拿到, 但是文件大小为0, 请问是什么原因?

**Comment by chenjiahan** [comment]
没有遇到过这种情况呢，建议看下在浏览器里是否正常。如果浏览器没问题，说明是打包成 App 导致的问题

**Comment by nanaMonsoon** [comment]
> 没有遇到过这种情况呢，建议看下在浏览器里是否正常。如果浏览器没问题，说明是打包成 App 导致的问题

@chenjiahan h5不打包, 直接在qq里面打开也是一样的, 文件名和文件类型可以拿到, 但是文件大小为0, 这个又是为什么呢

**Comment by chenjiahan** [comment]
用 XR 试了下没复现。文件大小的信息是系统返回的，组件内部没有做处理，如果系统没返回的话我们也木有办法

**Comment by tereseZXJ** [comment]
@nanaMonsoon 我也遇到了这个问题，你这边有进展吗
能确定什么情况才会触发吗
