### ISSUE TITLE
dateTimePicker 时间选择器  type 为time , 动态修改最小分钟,切换小时以后,获取到的分钟为00

### ISSUE THREAD

**Issue by Wster11** [youzan/vant#5766]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by Wster11** [comment]
<van-datetime-picker
        v-model="currentDate1"
        type="time"
        :min-hour="minHour"
        :min-minute="
          currentDate.getTime() < new Date().getTime()
            ? currentDate1.split(':')[0] > new Date().getHours()
              ? 0
              : new Date().getMinutes()
            : 0
        "
        @confirm="confirmDate"
        @cancel="cancleDate"
      />

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
