### ISSUE TITLE
[Bug Report] datetime-picker内存飙升，页面直接卡死

### ISSUE THREAD

**Issue by sds0917** [youzan/vant#5768]
### 设备 / 浏览器
Chrome/80.0.3987.132 Windows10

### Vant 版本
2.5.3

### Vue 版本
2.5.17

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-6s79r?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue" target="_blank">https://codesandbox.io/embed/vant-issue-moban-6s79r?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue</a>

### 描述问题
像上面demo那样操作，datetime-picker配置max-date和min-date属性，下拉按钮出不来，内存就一路飙升，最终浏览器就卡死。

**Comment by chenjiahan** [comment]
```html
<van-datetime-picker
  v-model="model.beginTime"
   :max-date="model.endTime"
  type="datetime"
/>
<van-datetime-picker
  v-model="model.endTime"
  :min-date="model.beginTime"
  type="datetime"
/>
```

你这段代码逻辑里本身就含有死循环，max-date 变化 -> v-model 对应的 beginTime 变化 -> min-date 变化 -> v-model 对应的 endTime 变化 -> max-date 变化
