### ISSUE TITLE
[Bug Report] dropdown-menu 的getBoundingClientRect 兼容问题

### ISSUE THREAD

**Issue by libin2866** [youzan/vant#5770]
### 设备 / 浏览器
any

### Vant 版本
2.5.3

### Vue 版本
2.5.22

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/src/dropdown-menu/index.js" target="_blank">https://github.com/youzan/vant/blob/dev/src/dropdown-menu/index.js</a>

### 描述问题
dropdown-menu 在 updateOffeset的方法中，使用getBoundingClientRect没有判断menu是否存在，建议加个错误兼容。
不然容易出现：
Cannot read property 'getBoundingClientRect' of undefined

**Comment by chenjiahan** [comment]
具体是什么情况下会出现 menu 不存在的情况呢

**Comment by chenjiahan** [comment]
已在 2.5.4 版本修复

**Comment by libin2866** [comment]
> 具体是什么情况下会出现 menu 不存在的情况呢

这个是我们监控系统里看到的，报错次数比较多。看到已经修复了，非常感谢~

**Comment by chenjiahan** [comment]
soga~
