### ISSUE TITLE
[Feature Request] Search组件可以自定义左侧按钮

### ISSUE THREAD

**Issue by yiyan0** [youzan/vant#5771]
### 这个功能解决了什么问题
在不使用导航栏的情况下，可以添加返回按钮

### 描述您想要的解决方案
自定义搜索框左侧按钮

### 建议的API是什么样的
自定义搜索框左侧按钮

**Comment by chenjiahan** [comment]
下个版本会加个插槽

**Comment by chenjiahan** [comment]
已在 2.5.4 版本支持
