### ISSUE TITLE
van-area怎么用?省市选择怎么搞

### ISSUE THREAD

**Issue by Chang-Hai** [youzan/vant#5772]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater
你们的文档上都没写清楚,我要哭了
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以参考示例文件的源码

https://github.com/youzan/vant/blob/dev/src/area/demo/index.vue
