### ISSUE TITLE
[Bug Report] calendar 组件 poppable false 时的 Bug

### ISSUE THREAD

**Issue by Pingren** [youzan/vant#5773]
使用 van-calendar, poppable 为 fasle。

在 data 创建赋值 minDate，maxDate，和 defaultDate 并绑定。  

1. 视图不能默认定位到 defaultDate。 （similar to #5760, 似乎最新的 dev 上已经尝试解决这个问题，但是我如何在发布新版前测试？修改 package.json 里 "vant": "youzan/vant#dev" 之后编译失败）。

2. 当 maxDate = defaultDate = new Date() 时，视图会直接变成空白，手动滑动一下才会显示。研究了下发现是内部组件 Month 的 visible 设置成了 false，似乎是和 visible 的计算错误有关系。

3. 当 maxDate = defaultDate = new Date() 时，顶部标题（.van-calendar__header > .van-calendar__month-title）将永远小于当前月份，即无法滚动到最后一个月。

**Comment by chenjiahan** [comment]
> 如何在发布新版前测试

可以运行 npm run build 进行构建，构建完通过 link 使用

> 视图会直接变成空白

这个问题试了下没复现，可以按照 issue 模板单独提个 issue，附上 codesandbox 链接

**Comment by Pingren** [comment]
> > 如何在发布新版前测试
> 
> 可以运行 npm run build 进行构建，构建完通过 link 使用
> 
> > 视图会直接变成空白
> 
> 这个问题试了下没复现，可以按照 issue 模板单独提个 issue，附上 codesandbox 链接

<img width="410" alt="image" src="https://user-images.githubusercontent.com/5123601/76157637-3a2f3a00-6146-11ea-8db2-fa4c99a9837c.png">

了解了，谢谢。刚刚升级了2.5.4，又试了下，问题 1 和问题 3都已经解决了。
我发现在项目中添加以下 CSS 导致导致显示空白，关闭就没问题了。
但是使用同样的 CSS 在 codesandbox 中没能复现该问题，也就是说可能还有其它因素共同导致的。

```css
/* 使用 >>> 穿透scoped */
>>> .van-calendar__header > .van-calendar__month-title {
  display: none;
}
```

未来是否考虑为 calendar 加入控制月份标题显示的 show-month-title 和 控制标题的 show-title props?
如果需要的话我可以另外开一个 Feature Request。

**Comment by chenjiahan** [comment]
> 未来是否考虑为 calendar 加入控制月份标题显示的 show-month-title 和 控制标题的 show-title props

会考虑加上，可以开个 issue 哈
