### ISSUE TITLE
[Bug Report] uploader组件预览图片直接黑屏

### ISSUE THREAD

**Issue by hu19940121** [youzan/vant#5775]
### 设备 / 浏览器
chorme浏览器

### Vant 版本
2.5.3

### Vue 版本
2.5.2

### 重现链接
<a href="http://opendev.steam001.com/#/sellerAuth" target="_blank">http://opendev.steam001.com/#/sellerAuth</a>

### 描述问题
uploader上传图片后 点击缩略图预览 直接黑屏

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接
