### ISSUE TITLE
npx create-vant-cli-app 执行之后报错控制台

### ISSUE THREAD

**Issue by wuyanwen** [youzan/vant#5776]
设备 / 浏览器
任意设备

描述问题
当在控制台运行npx create-vant-cli-app，报错 ，截图如下。node试了(v10.15.0或v12.14.0)多个版本都是同样的错误

![image](https://user-images.githubusercontent.com/7331663/76140254-2b3b7f80-6093-11ea-89b6-0b33e2012dcd.png)

**Comment by chenjiahan** [comment]
感谢反馈，是 yeoman 版本导致的，已修复
