### ISSUE TITLE
[Bug Report] Picker 级联选择器切换问题

### ISSUE THREAD

**Issue by codebug111** [youzan/vant#5777]
### 设备 / 浏览器
任意设备

### Vant 版本
2.5.3

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-89exx" target="_blank">https://codesandbox.io/s/vant-issue-moban-89exx</a>

### 描述问题
当切换到某一级children值为null时，切换前的数据不消失

**Comment by chenjiahan** [comment]
不支持这样的用法呢，级联选择时，不同选项的层级数必须是一致的。

你可以传入空的 text
