### ISSUE TITLE
Toast无法使用

### ISSUE THREAD

**Issue by kuailedechengxuyuan** [youzan/vant#5778]
链接如下：
https://youzan.github.io/vant/#/zh-CN/toast
问题描述：
我是全局引入vant，然后使用Toast()方法时，vue项目报错‘'Toast' is not defined’，但是当我使用this.$toast()时就对了，我怀疑你们没有封装好吧

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/76155510-c8e08e80-6127-11ea-8d1a-e11a7bf8c1d9.png)

**Comment by hezhongfeng** [comment]
我也是遇到这个问题了，感觉是说明文档的问题，截图是说CDN引入的，issue说的是全局引入。

**Comment by yywxf** [comment]
同问：
import Vant from 'vant' 后如何调用
Locale.use()

**Comment by qiaodaima** [comment]
@chenjiahan  
感觉这个回答有点答非所问，

一般学习写写demo,才会像截图那样 用`cdn ` `script`的方式引入，
我和楼主也遇到同样的问题，我是`全局导入vant,`  但是 提示 `Toast' is not defined`

文档需要修正：
[我是用这个例子发现的-动作面板文档里面的提示](https://youzan.github.io/vant/#/zh-CN/action-sheet)

用的楼主的方法可行` this.$toast('提示语')`
