### ISSUE TITLE
</van-cell-group>组件嵌套不正确

### ISSUE THREAD

**Issue by liuhuaxia** [youzan/vant#578]
![image](https://user-images.githubusercontent.com/30068808/35423246-cc38d91c-0287-11e8-951d-19d9a1b6a3b3.png)
![image](https://user-images.githubusercontent.com/30068808/35423253-d6f0e89a-0287-11e8-8495-ccb43a7ab566.png)
CDN方式

**Comment by chenjiahan** [comment]
HTML 模板不支持自闭和标签
