### ISSUE TITLE
swipe 在用描述檔(.mobileconfig)開啟的畫面，在橫屏直屏切換時大小異常

### ISSUE THREAD

**Issue by Orow** [youzan/vant#5781]
你好，
目前在開發 web app
在 iPhone 上用 .mobileconfig 安裝的檔案開啟後，畫面在切換橫屏直屏時，大小是異常的

ex. 
直屏時 van-swipe__track 的 width: 2800px , 有7個 swipe-item, 每個 item 的 width: 400px
轉為橫屏假設應該是要為 van-swipe__track 的 width:5950px, swipe-item 的 width: 850px

用 Xcode simulator 開啟 mobileconfig 的檔案後，用 web safari dev tool 去看van-swipe 的寬度在切換直屏/橫屏的 width，在第一次切換成橫屏時，寬度是沒有變化的
但是再度切換回直屏的時候，van-swipe__track 的 width 變成 橫屏應該有的 5950px, swipe-item 也變成 850px => 後來切換直屏/橫屏的寬度就都相反了。
也就是直屏顯示橫屏的寬度；橫屏顯示直屏的寬度。

ios 12 調用 resize 也是無效，
但在 ios 13 調用 resize 是成功的....
而且在這兩個 ios 下直接用 safari 開啟 相同網址是不需要額外調用 resize ，寬度就顯示正常的

是不是 resize() 在 mobileconfig 中 ios 12 跟 ios13 有衝突到呢？

**Comment by Orow** [comment]
因為用 mobileconfig的 關係 在 meta 的 viewport 有加入
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0, viewport-fit=cover">
有發現把這個 meta tag 拿掉後，直橫屏切換不需要調用 resize 切換直橫屏時寬度也顯示正常，但是 mobileconfig 需要給 width 跟 initial-scale 顯示手機裝置的大小，所以還是 po 上來 issue 看有沒有人有想法怎麼解決

**Comment by chenjiahan** [comment]
可以在 swipe/index.js 加入 `orientationchange` 事件试下：

```js
bind(window, 'orientationchange', this.resize);
```

![image](https://user-images.githubusercontent.com/7237365/76208964-b9eb0080-623b-11ea-9820-c2b4836cb17d.png)

**Comment by Orow** [comment]
vant 用 npm insall 的話，在node_moudels/vant/lib/swipe/index.js 裡面去改嗎？
我這樣改看起來是一樣沒有改善

原先我調用 resize 已經是監聽 orientationchange 去執行的了

```
window.addEventListener("orientationchange", this.$refs.swipe.resize());
```

**Comment by chenjiahan** [comment]
在 `node_modules/vant/es/swipe/index.js` 里改

如果没效果的话，你可以调试代码，看看取到的宽度是不是有问题

https://github.com/youzan/vant/blob/dev/src/swipe/index.js#L155

**Comment by Orow** [comment]
在 node_modules/vant/es/swipe/index.js 里改
```
bind(window, 'orientationchange', this.resize);
```
效果跟我原先自己寫下面這行一樣，我就不需要自己監聽 orientationchange 事件去調用 resize ，但在 ios 12 下的 device 切換直橫屏是顯示異常的
```
window.addEventListener("orientationchange", this.$refs.swipe.resize());
```

我用你提供的方式console.log this.computedWidth, this.width, rect.width
this.width 是 undefined
this.computedWidth = rect.width

看起來 resize 有調用，但是抓到的 rect.width 在觸發 orientationchange 之後，狀況都是
橫屏抓到的是直屏的寬度
直屏抓到橫屏的寬度

**Comment by chenjiahan** [comment]
看起来是 iOS 的 bug？rect.width 应该返回当前的屏幕宽度

**Comment by Orow** [comment]
是真的蠻奇怪，我在 meta tag 加上這行
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0, viewport-fit=cover">

有監聽 orientationchange ，直屏的時候不改變，橫屏的時候把 viewport-fit=cover 拿掉，這樣的話在ios 12 下的瀏海機(iPhoneX, iPhone Xs Max...等)再轉為橫屏的時候調用 resize 是顯示正常，但是轉回直屏又是顯示不正常了

我是想問問看有沒有人用 van-swipe 寫過 ios configuration 的
我目前公司同事是用別的 mobile UI(cube-ui)，也是在切換直橫屏調用slide 的 refresh，

**Comment by Orow** [comment]
我剛測試一下我同事的程式
他們在 ios 12 下看起來就算調用他們的 refresh 在橫屏直屏切換看起來也是有問題，只是他們 layout 的呈現看起來沒有我這邊的那麼明顯....

**Comment by chenjiahan** [comment]
只是在 simulator 上有问题吗？ 那应该可以忽略

**Comment by Orow** [comment]
同事的程式是用 cube-ui ，不是用 vant ，他們在 simulator ios 12 有狀況，實體機上基本上都正常，但很偶爾會出現異常....

我的程式用 vant 則是在 simulator 跟 實體機上都有狀況

**Comment by chenjiahan** [comment]
这个 issue 木有复现，目前也没有其他童鞋碰到类似的情况，所以先 close 咯
