### ISSUE TITLE
商品卡片价格显示

### ISSUE THREAD

**Issue by cheng11231456** [youzan/vant#5782]
**
![image](https://user-images.githubusercontent.com/41932574/76175060-bf1d6080-61e5-11ea-8951-e97644888655.png)
**
动态价格为1.00的时候，0自动隐藏，但是小数点仍显示

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by LOADINGG** [comment]
^4.9.0版本这个问题依旧在。
