### ISSUE TITLE
[Bug Report] Vant Touch Emulator on chrome extension CSP Error

### ISSUE THREAD

**Issue by lndj** [youzan/vant#5783]
### 设备 / 浏览器
Chrome extension

### Vant 版本
2.5.4

### Vue 版本
3.0.0-alpha.8

### 重现链接
<a href="https://github.com/lndj/do-not-need-demo" target="_blank">https://github.com/lndj/do-not-need-demo</a>

### 描述问题
在 Chrome 插件中使用了 Vant Touch Emulator，会触发 Chrome 的 Content Security Policy, 出现报错，影响部分功能。
报错信息如下：
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by chenjiahan** [comment]
Touch Emulator 没有适配过 Chrome extension 呢，如果有合适的兼容处理，欢迎提 PR
