### ISSUE TITLE
[Bug Report] Field嵌套Checkbox有bug

### ISSUE THREAD

**Issue by MrQiYin** [youzan/vant#5785]
### 设备 / 浏览器
Mac Chrome 模拟手机浏览器

### Vant 版本
2.5.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://output.jsbin.com/xuzukajivu" target="_blank">https://output.jsbin.com/xuzukajivu</a>

### 描述问题
van-field嵌套van-checkbox，会导致输入框无论输入什么东西，都会无法通过rules校验。目前仅测试了van-checkbox，其他组件嵌套在van-field下不知道还会不会有问题。
经测试，如果把van-field下van-checkbox删掉后，校验逻辑恢复正常。

**Comment by MrQiYin** [comment]
补充一下。。checkbox如果为true的话，校验逻辑又会恢复正常

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.5.5 版本修复

**Comment by MrQiYin** [comment]
> 已在 2.5.5 版本修复

辛苦辛苦！
