### ISSUE TITLE
[Bug Report] 日历组件Calendar 多选模式下，自定义主题色问题

### ISSUE THREAD

**Issue by zhaogaolei** [youzan/vant#5786]
### 设备 / 浏览器
*

### Vant 版本
2.5.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/src/calendar/components/Month.js#L191" target="_blank">https://github.com/youzan/vant/blob/dev/src/calendar/components/Month.js#L191</a>

### 描述问题
自定义主题色，
type='multiple' 模式下，
获取到的type='multiple-middle' ,但是上述链接中判断是有问题的，颜色改不了
-_-!

**Comment by chenjiahan** [comment]
multiple 模式下的 color 属性有问题，下个版本会修复下

**Comment by chenjiahan** [comment]
已在 2.5.5 版本修复
