### ISSUE TITLE
[Feature Request] Uploader 支持手动调用 input 点击事件

### ISSUE THREAD

**Issue by Pingren** [youzan/vant#5787]
### 这个功能解决了什么问题

可能需要外部组件控制 Uploader 内部原生 input 的点击事件，比如使用 Actionsheet 提供两个选项，决定选择图片还是拍照上传图片，改变 captrue props，调用 input 点击事件。

### 建议的 API 是什么样的 / 描述您想要的解决方案

为组件增加一个 chooseFile 方法。

**Comment by chenjiahan** [comment]
处于安全考虑，浏览器不支持主动调起文件上传的行为。

可以在按钮上面覆盖一个透明的 Uploader 来间接实现

**Comment by Pingren** [comment]
@chenjiahan 
这个方式只是通过执行 input 的 click 方法。浏览器应该没有安全限制吧。

可能我没表达清楚，CodeSandbox Demo：https://codesandbox.io/s/vant-issue-moban-64co2

```javascript
      this.captureMode = item.mode;
      this.$nextTick(() => {
        let uploaderInput = this.$refs.uploader.$el.getElementsByClassName(
          "van-uploader__input"
        )[0];
        uploaderInput.click();
      });
```
1. 绑定需要的 captrue 属性
2. 获得 input DOM 对象
3. 在 nextTick中 调用 click 事件

如果有暴露合适的方法，就不需要用类似 getElementsByClassName 或是在按钮上面覆盖一个透明的 Uploader 的 hack 来解决这个问题。

**Comment by chenjiahan** [comment]
在点击事件后调用是被浏览器允许的
