### ISSUE TITLE
[Bug Report] van-goods-action-icon的info配置不生效

### ISSUE THREAD

**Issue by liufei0123** [youzan/vant#5788]
### 设备 / 浏览器
微信浏览器

### Vant 版本
2.5.2

### Vue 版本
2.6.1

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/goods-action" target="_blank">https://youzan.github.io/vant/#/zh-CN/goods-action</a>

### 描述问题
van-goods-action-icon组件配置了info属性无效，info无论是动态的还是写死的数据都没有用
<van-goods-action-icon :info="cartNumber" text="购物车" @click="toShopcart">
          <img slot="icon" class="good-icon" :src="iconList[2]" />
        </van-goods-action-icon>

**Comment by chenjiahan** [comment]
使用 icon 插槽会导致这个问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.5.5 版本修复

**Comment by liufei0123** [comment]
好的，辛苦了
