### ISSUE TITLE
[Feature Request] 安卓系统调用Upload文件预览，可直接录制视频

### ISSUE THREAD

**Issue by asdwer098** [youzan/vant#5789]
### 这个功能解决了什么问题
安卓手机调用Upload文件上传时，只能拍照。上传小视频的话需要提前拍好，从文件中选择。

### 描述您想要的解决方案
安卓手机不能直接录制视频上传。

### 建议的API是什么样的
安卓可以和ios一样，可直接拍照或录像，然后上传。

**Comment by chenjiahan** [comment]
这个是原生系统决定的，组件内没有相关的逻辑
