### ISSUE TITLE
vant组件所有的px设置能否做适配处理？

### ISSUE THREAD

**Issue by lyq027** [youzan/vant#5790]
目前组件内大多设置宽高，要么是数字，要么是string,但是要传rem，这个就没效果。

**Comment by chenjiahan** [comment]
string 类型可以带单位的，比如 `2rem`

**Comment by lyq027** [comment]
@chenjiahan 你好，sticky组件使用 :offset-top="2rem"报错，使用 offset-top="2rem"无效，使用
:offset-top="46" 可用。要如何使用才能正确使用rem进行适配？

**Comment by chenjiahan** [comment]
sticky offset 需要进行数值计算，因此不支持 string 类型，必须传入 px 单位
