### ISSUE TITLE
[Bug Report] field输入框输入数字能支持调起数字键盘吗

### ISSUE THREAD

**Issue by jiahui336** [youzan/vant#5791]
### 设备 / 浏览器
ios

### Vant 版本
2.5.4

### Vue 版本
3.0.0-alpha.8

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/field" target="_blank">https://youzan.github.io/vant/#/zh-CN/field</a>

### 描述问题
field输入框输入数字能支持调起数字键盘吗，有这种需求 调起数字键盘的 只能输入整数，不能输入小数

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5665

**Comment by chenjiahan** [comment]
已在 2.5.5 版本优化，支持数字键盘
