### ISSUE TITLE
[Bug Report] Form 验证时 stepper为小数验证不通过

### ISSUE THREAD

**Issue by BurNing1993** [youzan/vant#5792]
### 设备 / 浏览器
Chrome

### Vant 版本
2.5.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/burning1993/pen/zYGpWPY?editors=1010" target="_blank">https://codepen.io/burning1993/pen/zYGpWPY?editors=1010</a>

### 描述问题
Form 验证时 stepper为小数验证不通过,stepper出现浏览器验证消息请输入有效值，两个最接近的有效值分别为...

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.5.5 版本修复
