### ISSUE TITLE
[Feature Request] 如何配置webpack忽略打包vant

### ISSUE THREAD

**Issue by hsingyin** [youzan/vant#5793]
### 这个功能解决了什么问题
可以走cdn引入不用打包进去

### 描述您想要的解决方案
我的config.external配置如下，但是vant始终被打包进去
config.externals = {
    'vue': 'Vue',
    'vue-router': 'VueRouter',
    'vuex': 'Vuex',
    'axios': 'axios',
    'vant': 'vant'
  },

### 建议的API是什么样的
请求指导一下正确写法

**Comment by chenjiahan** [comment]
上面的写法在不使用 babel-plugin-import 的情况下应该是有效的

在使用 babel-plugin-import 的情况下，vant 引入的路径是类似于 `vant/es/xxx.js` 这样的结构，可以用正则来匹配

```js
module.exports = {
  //...
  externals: [
    function(context, request, callback) {
      if (/^vant$/.test(request)){
        return callback(null, 'commonjs ' + request);
      }
      callback();
    }
  ]
};
```

**Comment by Yechuanjie** [comment]
> 上面的写法在不使用 babel-plugin-import 的情况下应该是有效的
> 
> 在使用 babel-plugin-import 的情况下，vant 引入的路径是类似于 `vant/es/xxx.js` 这样的结构，可以用正则来匹配
> 
> ```js
> module.exports = {
>   //...
>   externals: [
>     function(context, request, callback) {
>       if (/^vant$/.test(request)){
>         return callback(null, 'commonjs ' + request);
>       }
>       callback();
>     }
>   ]
> };
> ```

请教一下，在 `vue.config.js` 文件中的 configureWebpack里，如何使用正则的方式正确配置？
```js
configureWebpack: config => {
  config.externals = {
    'vant': 'vant'
  }
}
```

**Comment by chenjiahan** [comment]
一样的。

**Comment by huangxu510** [comment]
请问楼主解决了没
