### ISSUE TITLE
[Bug Report] tagbar设置active-color初始化项目时没有显示设置的颜色

### ISSUE THREAD

**Issue by Marico111** [youzan/vant#5794]
### 设备 / 浏览器
谷歌

### Vant 版本
2.5.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-4qdwk" target="_blank">https://codesandbox.io/s/vant-issue-moban-4qdwk</a>

### 描述问题
vue项目下使用tabbar组件时，设置active-color首次加载还是显示的默认值，需要点击切换才能正确展示

**Comment by shaodushu** [comment]
active值弄错了

**Comment by chenjiahan** [comment]
tabbar-item 没有设置 name 的情况下，active 为 item 的索引值

设置 name 的情况下，active 的值为对应的 name
