### ISSUE TITLE
iphoneX下PopUp如果内容是展开收缩会导致滚动不了

### ISSUE THREAD

**Issue by luchanan** [youzan/vant#5796]
### 设备 / 浏览器
iphonex/safari
系统 IOS12
user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

### Vant 版本
2.5.4

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-p99r3" target="_blank">https://codesandbox.io/s/vant-issue-moban-p99r3</a>

### 描述问题
有一个列表，列表可以点击弹窗；弹窗包含列表，点击箭头，可以展开和收缩，默认是收缩。这里有5行，分别从1点到5，等所有的内容展开出了屏幕外，发现滚动不了。iphoneX可以复现，但iphone6sp无此问题

**Comment by luchanan** [comment]
系统ios12
user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

**Comment by chenjiahan** [comment]
试了下木有复现，可以把 Popup 的 lock-scroll 设置为 false 试下

**Comment by luchanan** [comment]
![ss](https://user-images.githubusercontent.com/10396123/76494615-39611580-6470-11ea-9fef-cb721f3ec28d.gif)
这是我的录屏

**Comment by chenjiahan** [comment]
没复现呢，你试了 lock-scroll 了吗

**Comment by luchanan** [comment]
> 试了下木有复现，可以把 Popup 的 lock-scroll 设置为 false 试下

一样存在问题

**Comment by chenjiahan** [comment]
那就是浏览器 bug 咯，Popup 里面只有 lock-scroll 会影响滚动
