### ISSUE TITLE
日历传入格式

### ISSUE THREAD

**Issue by 1259549061** [youzan/vant#5797]
按官网代码传入最小最大和默认值，警告！
[Vue warn]: Invalid prop: type check failed for prop "minDate". Expected Date, got Date 
[Vue warn]: Invalid prop: type check failed for prop "maxDate". Expected Date, got Date 
[Vue warn]: Invalid prop: type check failed for prop "defaultDate". Expected Date, Array, got Date

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
