### ISSUE TITLE
[Bug Report] 项目打包后，css 样式覆盖问题

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#5798]
### 设备 / 浏览器
浏览器

### Vant 版本
2.4.1

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/image-preview" target="_blank">https://youzan.github.io/vant/#/zh-CN/image-preview</a>

### 描述问题
.van-image 样式覆盖.van-image-preview__image css  position，这是打包的问题还是。。
![QQ截图20200311094903](https://user-images.githubusercontent.com/42430384/76374540-7fd64780-637e-11ea-8762-33487eab6568.png)

**Comment by chenjiahan** [comment]
打包的问题，可以检查下是不是重复引入样式了
