### ISSUE TITLE
关闭sku层后，无法获取到skuData？

### ISSUE THREAD

**Issue by mfq1020** [youzan/vant#580]
sku层上点击加入购物车或者点击立即购买后有回调函数支持。

关闭sku后无法获取到sku的回调信息。不能支持关掉sku层后的加入购物车和立即购买。
如何实现关闭sku层后，能获取到选择的规格信息？？

**Comment by chenjiahan** [comment]
感谢反馈，后续会支持规格的获取

**Comment by chenjiahan** [comment]
在 0.12.7 版本中添加了 getSkuData 的方法，可以手动获取对应数据
