### ISSUE TITLE
[Bug Report] iOS下低电量模式会导致popup进入动画变形

### ISSUE THREAD

**Issue by hanyaonian** [youzan/vant#5800]
### 设备 / 浏览器
iOS移动设备

### Vant 版本
2.2.8

### Vue 版本
2.6.1

### 重现链接
<a href="https://codepen.io/hanyaonian/pen/qBdxbBR" target="_blank">https://codepen.io/hanyaonian/pen/qBdxbBR</a>

### 描述问题
iOS设备下，低电量模式popup进入动画会变形（不限于全屏）

**Comment by hanyaonian** [comment]
补充：
运行环境为WKwebview， ios版本13.3.1

**Comment by chenjiahan** [comment]
这个是系统问题，组件动画就是用了普通的 transition

**Comment by hanyaonian** [comment]
> 这个是系统问题，组件动画就是用了普通的 transition

离场不会出现变形，进场会，显得有些奇怪，正常低电量模式应该只会少帧吧，这个进场动画直接剩两帧了

**Comment by chenjiahan** [comment]
可以把 lazy-render 设置为 false 试下，首次进场的 render 也会耗费一些性能

**Comment by hanyaonian** [comment]
lazy-render设为false不太行。我这写了个demo，通过设置多一些动画关键帧可以减少低电量下的跳跃/闪烁，虽然有点麻烦但可以一试
