### ISSUE TITLE
[Bug Report] Calender组件建议添加快速切换“年”的按钮

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#5802]
### 设备 / 浏览器
all

### Vant 版本
2.5.4

### Vue 版本
3.0.0-alpha.8

### 重现链接
<a href="http://234.com" target="_blank">http://234.com</a>

### 描述问题
Calender组件建议添加快速切换“年”的按钮，日期范围如果过大上下滑动会不方便

**Comment by chenjiahan** [comment]
暂无计划支持呢，范围过大可以考虑用 DatetimePicker 组件
