### ISSUE TITLE
[Bug Report] Uploader 预览没有使用 EXIF orientation，导致移动设备拍照后预览方向错误。

### ISSUE THREAD

**Issue by Pingren** [youzan/vant#5804]
### 设备 / 浏览器
Android
截图是在微信 X5 里截取的，但应该和浏览器不相关，
和手机操作系统拍照之后对 EXIF 处理有关系。

### Vant 版本
2.5.4

### Vue 版本
2.6.11

### 重现链接
无，需在 Android 手机上使用 Uploader ，竖屏拍照提交图片。

### 描述问题
手机拍照时的照片 Portrait / Landscape 信息是保存在 EXIF 中的，不加处理直接显示图片，方向信息会丢失。

<img width="430" alt="截屏2020-03-11下午4 15 12" src="https://user-images.githubusercontent.com/5123601/76396107-8e8b2180-63b3-11ea-9153-dc4a5185e620.png">

![Screenshot_2020-03-11-16-12-44-058_com android camera](https://user-images.githubusercontent.com/5123601/76396427-1d983980-63b4-11ea-8441-4a82311e3207.jpg)

**Comment by Pingren** [comment]
Related：
https://medium.com/wassa/handle-image-rotation-on-mobile-266b7bd5a1e6
https://github.com/blueimp/JavaScript-Load-Image

**Comment by chenjiahan** [comment]
exif 会考虑内置到组件里，compress 暂时还没有计划加进去

**Comment by Pingren** [comment]
@chenjiahan 嗯，我想使用 Uploader 的 beforeRead 属性 + compressorjs 解决压缩，beforeRead 支持 Promise，适合这个需要压缩图片的场景。

但是 beforeRead 里返回的 file 并不会更新预览图，Uploader 的 fileList 没有更新，似乎是另一个Bug？还是设计本身如此？

**Comment by Pingren** [comment]
题外话：请教一下，为什么代码使用了那么多 _this，使用 arrow function 而不是 function () 就可以避免 this 上下文问题吧。

**Comment by chenjiahan** [comment]
> Promise.then 里面并没有使用 resolve 的参数，readFile 使用的还是原先的 files

这个后续会调整下

> 为什么代码使用了那么多 _this

你看的是编译后的代码，_this 是 babel 编译的结果

**Comment by Pingren** [comment]
> > Promise.then 里面并没有使用 resolve 的参数，readFile 使用的还是原先的 files
> 
> 这个后续会调整下
> 
> > 为什么代码使用了那么多 _this
> 
> 你看的是编译后的代码，_this 是 babel 编译的结果

没注意，我是直接 node_modules 看的😭。难怪感觉代码很难读懂，还好多问了一句哈哈哈

**Comment by Pingren** [comment]
@chenjiahan 

> > Promise.then 里面并没有使用 resolve 的参数，readFile 使用的还是原先的 files
> 
> 这个后续会调整下
> 

我可以提交 Pull Request 吗？，感觉这个问题挺容易处理的，更新下文档就可以了。

**Comment by chenjiahan** [comment]
可以的喔，欢迎 PR

**Comment by chenjiahan** [comment]
已发布 2.5.6 版本
