### ISSUE TITLE
Picker.setValues won't change cascade columns

### ISSUE THREAD

**Issue by Mitscherlich** [youzan/vant#5807]
I've tried to `setValues` on a cascade picker but only first column's value was setted properly. Then I find out `setValues` won't emit 'change' event on PickerColumn which causes this problem.

I'm not quite sure was this an issue. Just out of curiosity :)

https://github.com/youzan/vant/blob/1a25dc04d108f73d7d0f79a1d7b35225a759ac8b/src/picker/PickerColumn.js#L219-L226

**Comment by chenjiahan** [comment]
It's a bug, we will fix it later ^_^

**Comment by chenjiahan** [comment]
Fixed in v2.2.6

**Comment by Mitscherlich** [comment]
Thx! I'll try it out.
