### ISSUE TITLE
[Feature Request] van-cell增加value插槽

### ISSUE THREAD

**Issue by hongyuxuan** [youzan/vant#5808]
### 这个功能解决了什么问题
目前cell没有value插槽

### 描述您想要的解决方案
有时候cell的右侧希望有多行或者带颜色的元素，因此希望增加slot="value"，和van-collapse-item的value插槽一样

### 建议的API是什么样的
增加slot="value"

**Comment by chenjiahan** [comment]
Cell 的 default 插槽就是 value 的插槽
