### ISSUE TITLE
[Bug Report] 表单字段上的按钮点击后自动触发表单提交事件

### ISSUE THREAD

**Issue by largeTree** [youzan/vant#5809]
### 设备 / 浏览器
微信，chrome

### Vant 版本
2.5.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-o2e9n?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-o2e9n</a>

### 描述问题
表单内有一个手机号的Field，一个验证码的Field，验证码的Field上有个发送验证码的按钮，点击发送验证码的按钮会同时触发发送验证码的按钮事件和表单的提交事件

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5707
