### ISSUE TITLE
页面初始化后Toast自动弹出

### ISSUE THREAD

**Issue by LiZ2z** [youzan/vant#581]
页面加载完成后, Toast自动弹出, 显示内容如下:

![image](https://user-images.githubusercontent.com/30578440/35468140-1a547752-0353-11e8-8c74-59e391b446b6.png)

看到一个类似的问题

![image](https://user-images.githubusercontent.com/30578440/35468128-e732bb36-0352-11e8-988e-218d3d989afa.png)

**Comment by LiZ2z** [comment]
`Vue.use(Toast)
Toast.clear();`
我这么解决的

**Comment by chenjiahan** [comment]
Toast 组件不需要通过 use 注册的
