### ISSUE TITLE
[Bug Report] vue-2.4.1.min.js:6 TypeError: Cannot read property 'zIndex' of undefined

### ISSUE THREAD

**Issue by gyfeng1003** [youzan/vant#5810]
### 设备 / 浏览器
chrome

### Vant 版本
2.5.3

### Vue 版本
3.0.0-alpha.8

### 重现链接
<a href="http://ysh.visitshanghai.net/act/dengji/index/#/gymSubscribe" target="_blank">http://ysh.visitshanghai.net/act/dengji/index/#/gymSubscribe</a>

### 描述问题
本页面头部使用了van-dropdown-menu组件，在本地运行没问题，打包以后运行报错

**Comment by chenjiahan** [comment]
不支持 Vue 2.4 呢，建议使用 Vue >= 2.6
