### ISSUE TITLE
[Feature Request] panel的status可以增加状态颜色配置项吗？

### ISSUE THREAD

**Issue by deajax** [youzan/vant#5811]
### 这个功能解决了什么问题
panel的status默认只是红色，但是状态并不一定只是红色，可能会用到绿色、黄色、蓝色来表示不同的状态。想改变颜色就只能通过自定义来实现，写起来比较费劲。希望可以增加一个status-color配置来定义status的颜色

### 描述您想要的解决方案
panel 增加一个属性 status-color ，可以定义 status 字段的颜色

### 建议的API是什么样的
status-color="#faad14"
or
status-color="warning"
or
status-color="orange"

**Comment by chenjiahan** [comment]
暂无计划支持呢，可以直接通过 class 覆盖
