### ISSUE TITLE
[Feature Request] swipe自定义大小下支持循环以及可设置露出前后滑块的一部分

### ISSUE THREAD

**Issue by xuqian1004** [youzan/vant#5812]
### 这个功能解决了什么问题
前后滑块露出一部分，当前滑块放大，可以有更加立体的效果

### 描述您想要的解决方案
希望支持循环滚动，首尾衔接，以及支持设置滑块的前后边距，可以露出前/后滑块的一部分

### 建议的API是什么样的
类似于小程序的swiper组件

**Comment by chenjiahan** [comment]
暂无计划支持，需要实现复杂的 Swipe 效果，可以使用社区的 [vue-awesome-swiper]( https://github.com/surmon-china/vue-awesome-swiper)
