### ISSUE TITLE
[Bug Report] van-list的immediate-check在部分机型下不生效

### ISSUE THREAD

**Issue by OvOOvOff** [youzan/vant#5814]
### 设备 / 浏览器
iphone6，iphone7

### Vant 版本
2.5.5

### Vue 版本
3.0.0-alpha.8

### 重现链接
<a href="https://v2.wezan.net//0ane8150d8#/shop/goods-list/20" target="_blank">https://v2.wezan.net//0ane8150d8#/shop/goods-list/20</a>

### 描述问题
vant-list组件中设置immediate-check为false，在created时手动请求了数据，在iphone6和iphone7手机下首页加载数据时请求了二次

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

手动请求时需要将 loading 设置为 true
