### ISSUE TITLE
[Bug Report] 在vant-form组件上使用了scroll-to-error之后，页面中没有定位到错误位置，只是页面滚动条到了最底部

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#5816]
### 设备 / 浏览器
谷歌

### Vant 版本
2.5.2

### Vue 版本
3.0.0-alpha.8

### 重现链接
<a href="http://test-baobei.baoxianxia.com.cn/#/pro-form?planId=6&userId=1&premium=5&trialObj=%257B%2522insuredBirthday%2522%253A%25222002-03-14%2522%252C%2522insuredSex%2522%253A%25220%2522%252C%2522insPeriod%2522%253A%25221%2522%252C%2522additionalRisk%2522%253A%25220%2522%252C%2522planId%2522%253A6%257D" target="_blank">http://test-baobei.baoxianxia.com.cn/#/pro-form?planId=6&userId=1&premium=5&trialObj=%257B%2522insuredBirthday%2522%253A%25222002-03-14%2522%252C%2522insuredSex%2522%253A%25220%2522%252C%2522insPeriod%2522%253A%25221%2522%252C%2522additionalRisk%2522%253A%25220%2522%252C%2522planId%2522%253A6%257D</a>

### 描述问题
在vant-form组件上使用了scroll-to-error之后，页面中没有定位到错误位置，只是页面滚动条到了最底部

**Comment by chenjiahan** [comment]
Field 未设置 name 属性导致的，请设置 name 属性
