### ISSUE TITLE
[Bug Report] 华为荣耀20部分组件文本不居中，较为偏上

### ISSUE THREAD

**Issue by xuan-zi** [youzan/vant#5822]
### 设备 / 浏览器
华为荣耀20

### Vant 版本
2.5.2

### Vue 版本
2.6.11

### 重现链接
<a href="http://119.23.255.181/dist/index.html#/search" target="_blank">http://119.23.255.181/dist/index.html#/search</a>

### 描述问题
search组件，input里的占位符文本没有垂直居中，偏向上方

**Comment by chenjiahan** [comment]
能打开官网示例截图看下吗

**Comment by xuan-zi** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2020年3月16日(星期一) 下午5:10
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "子轩"<1023510044@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] [Bug Report] 华为荣耀20部分组件文本不居中，较为偏上 (#5822)





 
能打开官网示例截图看下吗

**Comment by xuan-zi** [comment]
&nbsp;
 &nbsp;
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"neverland"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年3月16日(星期一) 下午5:10
 收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
 抄送:&nbsp;"子轩"<1023510044@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [youzan/vant] [Bug Report] 华为荣耀20部分组件文本不居中，较为偏上 (#5822)

 

 

 
能打开官网示例截图看下吗
 
—官网示例基本上是好的

**Comment by chenjiahan** [comment]
图片没传上来

**Comment by xuan-zi** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 晚上7:37
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"子轩"<1023510044@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] 华为荣耀20部分组件文本不居中，较为偏上 (#5822)





 
图片没传上来

**Comment by chenjiahan** [comment]
还是没有，建议不要通过邮件回复

**Comment by xuan-zi** [comment]
![guanwang](https://user-images.githubusercontent.com/30305611/76853355-0cee3480-6888-11ea-9437-12330a3ab8a6.jpg)

**Comment by chenjiahan** [comment]
近期会找台类似的手机看下

**Comment by chenjiahan** [comment]
试了华为 P9 是正常的，这个问题应该是个别机型的渲染问题，暂时不会去兼容

**Comment by xuan-zi** [comment]
按钮，还有一些其他组件涉及到line-height的，文本都会偏上，试了好几个安卓机都这样，试了好几款安卓机都是这样的
