### ISSUE TITLE
在nuxt.js使用van-calendar会在服务端报 Invalid prop: type check failed for prop "minDate". Expected Date, got Date 

### ISSUE THREAD

**Issue by zkeyword** [youzan/vant#5823]
设备 / 浏览器
iphone6，iphone7

Vant 版本
2.5.5

Vue 版本
2.6.11

描述问题
在nuxt.js使用van-calendar会在服务端报 Invalid prop: type check failed for prop "minDate". Expected Date, got Date 

调用
```
<van-calendar
      v-model="show"
      color="#307EFE"
      :min-date="new Date(2000, 10, 1)"
      @confirm="onConfirm"
    />
```

错误信息：
```

[Vue warn]: Invalid prop: type check failed for prop "minDate". Expected Date, got Date 

found in

---> <VanCalendar>
       <Calendar> at components/Calendar/calendar.vue
         <Pages/rank/ranking/child/index.vue> at pages/rank/ranking/child/index.vue
           <Pages/rank/ranking/ranking.vue> at pages/rank/ranking/ranking.vue
             <Nuxt>
               <Layouts/default.vue> at layouts/default.vue
                 <Root>
```

**Comment by zkeyword** [comment]
`
<van-calendar
      v-model="show"
      color="#307EFE"
      :min-date="new Date(2000, 10, 1)"
      :default-date="new Date()"
      @confirm="onConfirm"
    />
`

日历的第一页会是2000.10.01 不会是当前日日期

**Comment by chenjiahan** [comment]
能否提供一个复现仓库看下

**Comment by zkeyword** [comment]
> 能否提供一个复现仓库看下

不好意思，现在刚有空建了个仓库
https://github.com/zkeyword/nuxt-vant-bug

**Comment by chenjiahan** [comment]
这是 nuxt 在 dev 模式下的 bug，目前还没有得到解决，参见 https://github.com/nuxt/nuxt.js/issues/5565

可以去 nuxt issue 里反馈此问题喔
