### ISSUE TITLE
发现button的一个bug

### ISSUE THREAD

**Issue by 240129745** [youzan/vant#5824]
你们给的issues链接也打不开，可能被墙了。现在我说一下我发现的bug:
图标按钮
通过icon属性设置按钮图标，支持 Icon 组件里的所有图标，也可以传入图标 URL

<van-button icon="star-o" type="primary" />
<van-button icon="star-o" type="primary">按钮</van-button>
这个icon根本显示不出来，不知道什么原因。我的邮箱547044063@qq.com

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
