### ISSUE TITLE
[Feature Request]vant DatetimePicker 有支持自动定位到当前日期吗

### ISSUE THREAD

**Issue by daimingchun** [youzan/vant#5827]
这个功能解决了什么问题
vant DatetimePicker 不支持自动定位到当前日期
![image](https://user-images.githubusercontent.com/6309807/76721802-27d38280-677c-11ea-865d-f32fce69884e.png)
现在默认最小时间
描述您想要的解决方案
无

建议的API是什么样的
无

**Comment by chenjiahan** [comment]
调整 v-model 绑定的日期即可定位到对应的日期
