### ISSUE TITLE
请问一下小程序中使用vant的全局方法Toast要怎么用呀。

### ISSUE THREAD

**Issue by XiaoWangS** [youzan/vant#5828]
请问一下在微信小程序中使用vant的全局方法Toast要怎么用呀，找不到用来import的文件。

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant-weapp/#/toast

path/to 替换为你项目中的 vant 路径

**Comment by ModeSpr** [comment]
<van-toast id="van-toast" />
不会要每个页面都要写吧？小程序没有app.wxml
