### ISSUE TITLE
文档中的插槽使用不规范

### ISSUE THREAD

**Issue by lmx-Hexagram** [youzan/vant#5836]
在[SwipeCell组件文档](https://youzan.github.io/vant/#/zh-CN/swipe-cell)中，推荐的slot使用方式是` slot="right"` 

在[自定义内容](https://youzan.github.io/vant/#/zh-CN/swipe-cell#zi-ding-yi-nei-rong)中也出现了这种操作

但是[vue官方文档](https://cn.vuejs.org/v2/guide/components-slots.html#%E5%BA%9F%E5%BC%83%E4%BA%86%E7%9A%84%E8%AF%AD%E6%B3%95)中,明确说明了这是已经废弃的语法,并将在Vue3中停止支持。

个人经过测试，发现全部可以使用官方推荐的`v-slot`取代,

这是一个简单的修改[样例](https://codesandbox.io/s/vant-issue-moban-hxpz0?fontsize=14&hidenavigation=1&theme=dark)

个人认为，应该修改vant的文档。如果不介意，我可以协助完成修改

**Comment by chenjiahan** [comment]
v-slot 只在 Vue 2.6 以上版本支持，之前还有较多开发者在使用 Vue 2.5，如果全部换成新语法，会有导致很多人复制示例代码后无法运行，所以目前文档里主要还是使用 slot 语法。

不过现在换成新语法也差不多了，欢迎提 PR
