### ISSUE TITLE
[Feature Request] Form是否可增加类型校验功能

### ISSUE THREAD

**Issue by jinhuang415** [youzan/vant#5839]
### 这个功能解决了什么问题
不需要手动写类型校验的表达式，方便使用

### 描述您想要的解决方案
提供 type 字段传入欲校验的类型，例如'number', 'phoneNumber', 'email', 'Array' 等等

### 建议的API是什么样的
提供 type 字段传入欲校验的类型，例如'number', 'phoneNumber', 'email', 'Array' 等等

**Comment by chenjiahan** [comment]
目前不想把 Form 做的太重，所以暂时不会添加特定格式的类型校验呢，现阶段建议通过 validator 自行校验
