### ISSUE TITLE
waterfall waterfall-offset  瀑布流 阀值

### ISSUE THREAD

**Issue by de1ck** [youzan/vant#584]
触发瀑布流加载的阈值waterfall-offset 

如果我没有理解错的话 应该是指加载的次数 还是滚动条距离底部的长度？

然而设置属性后无效。
https://jsfiddle.net/de1ck/by5h43xm/

**Comment by de1ck** [comment]
v-waterfall-upper  arguments （非箭头函数） 与  ...args 返回很奇怪的东西。
建议可以在触发事件的回调中添加一些有利于获取组件状态的参数

**Comment by chenjiahan** [comment]
@de1ck waterfall-offset 指的是滚动条距离底部的长度，Waterfall 组件目前问题比较多，我们计划在后续进行一次重构
