### ISSUE TITLE
[Bug Report] Tab 标签页 内容滚动 页面互相影响

### ISSUE THREAD

**Issue by wxxwtt** [youzan/vant#5841]
### 设备 / 浏览器
ios  android

### Vant 版本
2.4.0

### Vue 版本
2.5.20

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tab#yin-ru" target="_blank">https://youzan.github.io/vant/#/zh-CN/tab#yin-ru</a>

### 描述问题
tab 切换  如果其中一个页面有了滚动 会影响其他  切换到其他页面 也会滚动到相同位置  绑定key 也没有用

**Comment by chenjiahan** [comment]
Tab 组件默认不包含控制滚动的逻辑，如果开启了 sticky，切换后会滚动到顶部

如果需要手动控制滚动位置，可以通过 scrollTo 方法自行操作
