### ISSUE TITLE
checkbox sample error

### ISSUE THREAD

**Issue by Picktarget** [youzan/vant#5842]
### 设备 / 浏览器
chrome

### Vant 版本
2.5.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/checkbox#da-pei-dan-yuan-ge-zu-jian-shi-yong" target="_blank">https://youzan.github.io/vant/#/zh-CN/checkbox#da-pei-dan-yuan-ge-zu-jian-shi-yong</a>

### 描述问题
官方文档处，checkbox 所展示的全选与反选示例，以及搭配单元格组件使用示例存在问题。
具体表现为<van-checkbox-group v-model="result"> 这个result的值并不是期望的值 例如选择全选result：['a','b'],but got []

**Comment by chenjiahan** [comment]
不是很理解唉，示例里的 result 是默认值，默认情况下就是空数据

**Comment by Picktarget** [comment]
在点击checkbox的时候，比如选中了某个checkbox， result数组是不是应该记录这个checkbox的标记啊，示例中checkbox 绑定的name属性分别是['a','b']，那么勾选了这两个checkbox，result数组相应的应该也是['a','b']。但是实际在使用过程中，并不是这样的。

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/76840895-e4a80b00-6872-11ea-97bc-0e41c39c814c.png)

我试了下没问题，你是不是没绑定 v-model

**Comment by Picktarget** [comment]
麻烦您试一下搭配单元格组件使用这个例子 我扒下来 就是

![~X3YQ`4 WQ5 @WD2IJZFT8E](https://user-images.githubusercontent.com/12743709/76915705-31cec000-68f9-11ea-9cd0-ab6a49b2bc50.png)

![`X3ERZXLY``%ZA D 1S9NG6](https://user-images.githubusercontent.com/12743709/76915739-51fe7f00-68f9-11ea-80ae-4ffece0ddbc8.png)
![EO@PH$7J48C4F(LPOLR3$PC](https://user-images.githubusercontent.com/12743709/76915754-5b87e700-68f9-11ea-8e7b-aad38cc2fa63.png)

**Comment by chenjiahan** [comment]
console.log 不应该是在 toggle 之后吗，你在 toggle 之前 log，当然没变了

**Comment by Picktarget** [comment]
之前写 之后写效果一样的 我特意测试了的

**Comment by Picktarget** [comment]
![QWYG $T`YRXAW61(Y8WP{NQ](https://user-images.githubusercontent.com/12743709/76916936-01892080-68fd-11ea-983e-187092e05398.png)
![}4W5)NUV XNH1(D$QRVQ%DU](https://user-images.githubusercontent.com/12743709/76916938-04841100-68fd-11ea-9463-f760c04fb523.png)
![3E6A1{N9L{7)DRG}D DUULN](https://user-images.githubusercontent.com/12743709/76916944-077f0180-68fd-11ea-9989-09edabaa92a5.png)

**Comment by chenjiahan** [comment]
toggle 不是同步的，可以加个 nextTick 再取值

**Comment by Picktarget** [comment]
this.$refs.checkboxes[index].toggle()
      this.$nextTick(() => {
        // DOM 更新了
        console.log(this.result)
      })
打印的信息仍然不对

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/blob/3c3390c4fd85bab9e564508c0a332afa77194bf8/src/checkbox/index.js#L42-L50

我的锅我的锅，记错了，是 setTimeout

**Comment by Picktarget** [comment]
另外想请教一下关于vant-picker这个组件的@confirm=""这个事件  可以自定义传入的参数吗，因为某特殊场景的需要，我没办法直接控制该弹出关闭，并正确的赋值给表单控件

**Comment by Picktarget** [comment]
或者说我可以在van-popup中不适用tool-bar 然后自己写一个toolbar去替代呢

**Comment by chenjiahan** [comment]
toolbar 有提供插槽的，可以直接用
