### ISSUE TITLE
[Bug Report] van-popup内的van-field需要点多次才能唤起键盘

### ISSUE THREAD

**Issue by stewForAni** [youzan/vant#5843]
### 设备 / 浏览器
iphoneX

### Vant 版本
2.4.1

### Vue 版本
2.5.2

### 重现链接
<a href="https://shop.acekid.com/#/detail?sid=2" target="_blank">https://shop.acekid.com/#/detail?sid=2</a>

### 描述问题
初次进入页面的时候，点击购买课程按钮，弹出van-popup，van-popup内的van-field需要点多次才能唤起键盘，用的不是很顺畅（是否和fastclick会有冲突？）

**Comment by chenjiahan** [comment]
可以去掉 fastclick 试下

**Comment by stewForAni** [comment]
@chenjiahan    谢谢   去掉就好了

**Comment by AnsenJFY** [comment]
> 可以去掉 fastclick 试下

感谢
