### ISSUE TITLE
[Bug Report] List 组件与 PullRefresh 组件结合使用显示2个loading

### ISSUE THREAD

**Issue by vivian217** [youzan/vant#5844]
### 设备 / 浏览器
手机跟浏览器都会出现

### Vant 版本
2.5.5

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-qdtvg" target="_blank">https://codesandbox.io/s/vant-issue-moban-qdtvg</a>

### 描述问题
List 组件在与 PullRefresh 组件结合使用时，如果数据加载时添加loading状态，那么下拉刷新时会出现2个loading加载中

**Comment by chenjiahan** [comment]
这个可以自行控制的，不要同时把 refreshing 和 loading 设置为 true 就行
