### ISSUE TITLE
[Bug Report] 内置样式在页面不引用vant组件的时候不生效

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#5845]
### 设备 / 浏览器
window

### Vant 版本
2.5.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/style" target="_blank">https://youzan.github.io/vant/#/zh-CN/style</a>

### 描述问题
内置样式在页面不引用vant组件的时候不生效，只有当前页面引用了vant的组件才会生效

**Comment by chenjiahan** [comment]
不引组件的时候当然没有样式咯，你可以把一些基础组件放到公共文件里注册，这样就可以保证能引到了
