### ISSUE TITLE
为什么使用你们的组件在谷歌浏览器上会报错？

### ISSUE THREAD

**Issue by Adonis0123** [youzan/vant#5846]
为什么我使用你们的组件，在谷歌浏览器会报这个错误呢？任何一个组件都会
![image](https://user-images.githubusercontent.com/46788304/76940333-010c7c00-6935-11ea-9168-548078cf95c0.png)

VM4601:1 Uncaught SyntaxError: Identifier 'pleaseLetJsLoaded' has already been declared
    at <anonymous>:1:1

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

另外组件里没有包含上述代码
