### ISSUE TITLE
请问可以添加日历中日期全部可选择的api吗？

### ISSUE THREAD

**Issue by ymmagic** [youzan/vant#5848]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by ymmagic** [comment]
目前日历插件中当选择type为range的时候，无法选择今天以前的日期。

**Comment by chenjiahan** [comment]
可以设置 min-date 属性

**Comment by ymmagic** [comment]
设置了的那个min-date如果小于今天，最低还是会是今天
