### ISSUE TITLE
CDN导入有详细说明吗

### ISSUE THREAD

**Issue by villiamVIX** [youzan/vant#5850]
CDN导入后需要如何配置呢  在vue clii中

**Comment by chenjiahan** [comment]
Vue Cli 不需要使用 CDN 呢，直接通过 npm 包的方式引入即可

CDN 的引入介绍：
https://youzan.github.io/vant/#/zh-CN/quickstart#fang-shi-si.-tong-guo-cdn-yin-ru

**Comment by villiamVIX** [comment]
好的谢谢 cli中用cdn引入不是可以 减少打包速度提高性能吗

**Comment by chenjiahan** [comment]
对打包速度的影响不大哈，可以忽略。

通过 npm 安装的话，版本管理更方便

**Comment by tcstory** [comment]
@chenjiahan 有一个cdn 使用的文件是 vant.js, 但是里面包含了所有的组件, 体积挺大的, 请问一下, 有没有办法单独给每一个组件, 都打包出一个 cdn 可用的 js 文件呢?

**Comment by chenjiahan** [comment]
@tcstory 可以自行打包

**Comment by villiamVIX** [comment]
你好 cdn导入后 **lazyLoady**会报错 怎么解决呢

**Comment by chenjiahan** [comment]
@villiamVIX  要注册下 Lazyload

```js
Vue.use(vant.Lazyload);
```
