### ISSUE TITLE
关于 ImagePreview（图片预览）配合 keep-alive 缓存使用 不能正确预览问题

### ISSUE THREAD

**Issue by huchanghao** [youzan/vant#5851]
在列表使用  ImagePreview 组件方式 图片预览 配合 vue keep-alive 缓存使用，进入详情 在次返回列表，ImagePreview 预览 不会重新创建，导致图片的宽度是0px;使用close-on-popstate 参数配合也不行

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
