### ISSUE TITLE
关于IndexBar的问题

### ISSUE THREAD

**Issue by whsnr** [youzan/vant#5852]
在页面上采用两个组件，上部分用Search，下面紧跟着是IndexBar，如何设置可以固定Search组件呢？现在是整屏滚动，自己设置后，点击右边的索引会将IndexBar的top变为0（覆盖了上面的Search组件）

**Comment by whsnr** [comment]
补充：想实现的效果类似12306车站选择的效果，上面有搜索框，下面的索引滚动时不影响上面的搜索框

**Comment by lihaotian0607** [comment]
使用粘性布局:
https://youzan.github.io/vant/#/zh-CN/sticky

或者用局部滚动
