### ISSUE TITLE
图片预览 ImagePreview

### ISSUE THREAD

**Issue by huchanghao** [youzan/vant#5856]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by huchanghao** [comment]
组件图片预览配合 keep-alive 缓存 再次打开预览，不会计算图片的宽度

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
