### ISSUE TITLE
icon的介绍似乎出现乱码了

### ISSUE THREAD

**Issue by lmx-Hexagram** [youzan/vant#5857]
https://youzan.github.io/vant/#/zh-CN/icon#jie-shao

**Comment by lmx-Hexagram** [comment]
无法推断原本的文字应该是怎么样的。。。

**Comment by chenjiahan** [comment]
哪有乱码，木有看到

**Comment by lmx-Hexagram** [comment]
![image](https://user-images.githubusercontent.com/52130356/77061800-cc242600-6a15-11ea-963f-ab0fffa07207.png)

**Comment by chenjiahan** [comment]
确实有几个奇怪的字。。已删
