### ISSUE TITLE
<van-tabs>设置animated切换动画效果之后<van-popup>弹出位置错乱

### ISSUE THREAD

**Issue by BestCVerCN** [youzan/vant#5861]
在<van-tabs>中设置了4个标签页，其中第4个标签页中使用了<van-popup>。
当<van-tabs>没有添加animated时，<van-popup>底部弹出正常，设置animated之后，在第4个标签页触发弹出<van-popup>时，popup没有在第4个标签页弹出，而是在第1个标签页弹出了。

**Comment by chenjiahan** [comment]
transform 会导致 Popup 的 fixed 属性失效

解决方法是在 Popup 上添加 get-container="body" 属性

**Comment by AlanSean** [comment]
<van-tabs>设置animated切换动画效果之后<van-sticky>失效。

原因是tabs中的transform 把<van-sticky> 的fixed降级为了absolute,所以有没有什么兼容办法？
