### ISSUE TITLE
[Bug Report] vant field digit类型不能输入负数.比如-100

### ISSUE THREAD

**Issue by tsmoon** [youzan/vant#5863]
### 设备 / 浏览器
手机/浏览器

### Vant 版本
2.5.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### 描述问题
vant field digit类型不能输入负数.比如-100

**Comment by chenjiahan** [comment]
digit 只能输入正整数哈，负数请使用 number 类型，后续会在文档里说明下

**Comment by hyacinth-luck** [comment]
> digit 只能输入正整数哈，负数请使用 number 类型，后续会在文档里说明下

我选择输入的是type是number，也是能输入小数和整数，不支持输入负数
