### ISSUE TITLE
[Bug Report] 单独引入Image组件，没有渲染成vue组件

### ISSUE THREAD

**Issue by shlroland** [youzan/vant#5865]
### 设备 / 浏览器
Chrome 80.0.3987.132

### Vant 版本
2.5.5

### Vue 版本
2.6.10

### 重现链接
<a href="https://jsbin.com/cuqihozije/edit?html,output" target="_blank">https://jsbin.com/cuqihozije/edit?html,output</a>

### 描述问题
没有正常渲染，用as具名后可正常

**Comment by chenjiahan** [comment]
image 标签是 SVG 原生标签，不能被注册为组件名的，可以使用 VanImage 这样的写法

**Comment by chenjiahan** [comment]
已补充到文档
