### ISSUE TITLE
list组件中增加业务card组件出现class对第一个没作用

### ISSUE THREAD

**Issue by woue1989** [youzan/vant#5866]
尝试在list下循环显示商品，结果设置的class仅能对第二个开始的card才能起到作用
![366b0d2bfde7ceb6e2f84c72c9de7cf](https://user-images.githubusercontent.com/22586037/77130818-4dba9900-6a94-11ea-8f0c-a10335092c71.png)
![92ee6211da366aed2bddc43a798f046](https://user-images.githubusercontent.com/22586037/77130821-514e2000-6a94-11ea-9be2-3a7615149051.png)
![a543cddce917286f7657899f04b5eae](https://user-images.githubusercontent.com/22586037/77130823-5317e380-6a94-11ea-9e8d-8027a01c5236.png)

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/5867
