### ISSUE TITLE
[Bug Report] list组件中增加业务card组件出现class对第一个没作用

### ISSUE THREAD

**Issue by woue1989** [youzan/vant#5867]
### 设备 / 浏览器
谷歌

### Vant 版本
2.5.4

### Vue 版本
3.0.0-alpha.8

### 重现链接
<a href="http://localhost:8080/#/shop/order?classes=0" target="_blank">http://localhost:8080/#/shop/order?classes=0</a>

### 描述问题
尝试在list下循环显示商品，结果设置的class仅能对第二个开始的card才能起到作用
![366b0d2bfde7ceb6e2f84c72c9de7cf](https://user-images.githubusercontent.com/22586037/77130878-835f8200-6a94-11ea-8230-47ba6f07574c.png)
![92ee6211da366aed2bddc43a798f046](https://user-images.githubusercontent.com/22586037/77130881-865a7280-6a94-11ea-85c9-12479c7f8c26.png)
![a543cddce917286f7657899f04b5eae](https://user-images.githubusercontent.com/22586037/77130883-89edf980-6a94-11ea-9aef-0a6c51c0fb8d.png)

**Comment by chenjiahan** [comment]
原因应该和这个 issue 类似：https://github.com/youzan/vant/issues/2978

你的 localhost 链接是无效的，能否提供个 codesandbox 复现链接看下呢
