### ISSUE TITLE
[Bug Report] uploader作为slot时不会正常显示

### ISSUE THREAD

**Issue by Evangelione** [youzan/vant#5868]
### 设备 / 浏览器
所有

### Vant 版本
2.5.5

### Vue 版本
3.0.0-alpha.9

### 重现链接
<a href="https://codepen.io/evangelione/pen/ExjpXZw" target="_blank">https://codepen.io/evangelione/pen/ExjpXZw</a>

### 描述问题
作为field的slot = input 时，上传的图片不会显示，2.5.5以下版本正常

**Comment by chenjiahan** [comment]
已在 2.5.6 版本修复
