### ISSUE TITLE
[求教] Dialog.alert 的message可以是tab组件吗?

### ISSUE THREAD

**Issue by yurizhang** [youzan/vant#587]
我想在Dialog.alert里弹出一个tab标签组件，这个可以实现吗？
效果如下：
![image](https://user-images.githubusercontent.com/20555332/35505343-ce6e4b22-0520-11e8-9c2a-0820361a937c.png)

我看了文件 dialog的message只能是string和html. Message可以直接 是tab组件吗？

       Dialog.alert({
            title:'银行卡',
            message: banklist
          })
![image](https://user-images.githubusercontent.com/20555332/35505372-e7596194-0520-11e8-97ee-1f4d19f175c0.png)

**Comment by chenjiahan** [comment]
@yurizhang 不可以噢，建议使用 Popup
