### ISSUE TITLE
Tab、IndexBar等组件的吸顶模式能不能添加一个参数控制吸顶模块到顶部的距离

### ISSUE THREAD

**Issue by yaowangmx** [youzan/vant#5874]
设备 / 浏览器
所有浏览器

Vant 版本
2.5.2

Vue 版本
2.6.11

重现链接

描述问题
Tab、IndexBar等组件的吸顶模式能不能添加一个参数控制吸顶位置到顶部的距离。因为移动端的页面一般都会自定义一个头部，这样子吸顶模式下，就会被遮挡了。如果提供一个参数，比如页面公共头部的高度是0.8rem，然后吸顶的模块到顶部的距离为0.8rem，而不是直接吸在屏幕的最顶部。

**Comment by chenjiahan** [comment]
IndexBar 有 sticky-offset-top  属性，Tab 有 offset-top 属性

**Comment by yaowangmx** [comment]
但是页面布局的单位是rem自适应布局呢，限定px作为单位不好吧

**Comment by chenjiahan** [comment]
组件内部要进行位置计算，所以只能用 px

rem 可以转换成 px 传入
