### ISSUE TITLE
[Bug Report] van-picker级联选择时控制台报错

### ISSUE THREAD

**Issue by sds0917** [youzan/vant#5875]
### 设备 / 浏览器
Chrome/80.0.3987.132 Windows10

### Vant 版本
2.5.7

### Vue 版本
2.5.17

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-u937g?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue" target="_blank">https://codesandbox.io/embed/vant-issue-moban-u937g?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue</a>

### 描述问题
福建下面没有children节点，选择福建之后第二列的还显示的是杭州、温州，这时再选择第二列数据就报错。picker组件级联好像不支持这种不同深度的树形数据。官方文档也没有看到哪块注明不支持这种树形数据的说明。
![微信截图_20200320170406](https://user-images.githubusercontent.com/7779851/77149586-e705a180-6acc-11ea-9aa5-fd4c28909e35.png)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5777，后续会在文档里标注下
