### ISSUE TITLE
[Bug Report] ios微信内置浏览器picker样式异常

### ISSUE THREAD

**Issue by a-boom** [youzan/vant#5876]
### 设备 / 浏览器
iPhone 6s 微信内置浏览器

### Vant 版本
2.5.7

### Vue 版本
2.6.10

### 重现链接
<a href="https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx8e6c45b3d6f2268c&redirect_uri=https%3A%2F%2Fqrcode.jiahaofoods.com%2Fmobile%2Fmall&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect" target="_blank">https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx8e6c45b3d6f2268c&redirect_uri=https%3A%2F%2Fqrcode.jiahaofoods.com%2Fmobile%2Fmall&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect</a>

### 描述问题
关注公众号后输入 积分商城  点击注册链接 即可复现

**Comment by chenjiahan** [comment]
麻烦提供 codesandbox 复现链接
