### ISSUE TITLE
关于主题配置

### ISSUE THREAD

**Issue by goldenfireking** [youzan/vant#5877]
你好，我用vue cli4.2.2构建应用，想修改vant的样式变量，在vue.config.js里配置了重载用的less样式文件路径，但是不生效，请问是什么原因。

`css: {
    extract: IS_PROD,
    requireModuleExtension: true,
    loaderOptions: {
      less: {
        modifyVars: {
          hack: 'true; @import "~@/styles/vant-reset.less";'
        }
      },
      scss: {
        prependData: '@import "~@/styles/main.scss";'
      }
    }
  },`

**Comment by goldenfireking** [comment]
已解决，生效了

**Comment by haoyinag** [comment]
@goldenfireking @chuangbo 
抱歉请问怎么生效的  我的不生效

const path = require("path");
const myTheme = path.resolve(__dirname, "src/theme.less");

css: {
    loaderOptions: {
      less: {
        modifyVars: {
          // 或者可以通过 less 文件覆盖（文件路径为绝对路径）
          hack: `true; @import "${myTheme}";`
        }
      },
    }
  }

// src/theme.less
@green: #07c160;

@button-info-background-color: @green;
@button-primary-background-color: @green;

结构button还是蓝色背景

**Comment by slq0378** [comment]
vuecli2 配置主题，怎么配置都不生效，难道只能在vuecli3上使用vant

**Comment by Tindtily** [comment]
通过分析less-loader源码（5.x, 4.x)，6.x以前的，不需要配置lessOptions选项。vant文档只写了5.x不需要配置，略坑。花了我3个小时的时间。
因此解决方案是：需要核对less-loader版本，6.x以前的less-loader，不需要配置lessOptions。

6.x源码：https://github.com/webpack-contrib/less-loader/blob/73740a89aef0748e27657a06b80b327c90b6f2b4/src/utils.js#L143
5.x源码：https://github.com/webpack-contrib/less-loader/blob/821c12d407b36f49aacc506737a02d1dc46aee56/src/getOptions.js#L12

**Comment by xcsweb** [comment]
![image](https://user-images.githubusercontent.com/20693737/99399140-38965280-2920-11eb-91b7-67d9a02faf4d.png)
解决了，一定要加引号，less-loader 大于6，我用的7

**Comment by chenjiahan** [comment]
@Tindtily get，文档会优化下
