### ISSUE TITLE
[Bug Report] ios 浏览器，当预览图片在100+时就会出现重新刷新页面

### ISSUE THREAD

**Issue by songyajie** [youzan/vant#5879]
设备 / 浏览器
iPhone 6s   /  safari，微信内置浏览器，edge(目前测试了这3个)

Vant 版本
2.5.7

vue 版本
2.5.16

在预览图片比较少时没有在安卓的浏览器内顺畅，有卡顿感；
当图片过多的时候，还会直接刷新页面，没办法继续滑动预览。

**Comment by songyajie** [comment]
设备 / 浏览器
iPhone 6s 微信内置浏览器

Vant 版本
2.5.7

vue 版本
2.5.16

**Comment by chenjiahan** [comment]
原因参见：https://github.com/youzan/vant/issues/5692

下个版本会通过 lazy-render 优化下

**Comment by songyajie** [comment]
在 ios 浏览器中无论几张图片，都会有滑动预览不流畅的问题也会一起解决吗

**Comment by chenjiahan** [comment]
具体是怎么不流畅呢，可以录个屏看下

**Comment by songyajie** [comment]
由于链接是内部的测试环境，不太方便发出来；我这有视频，没找到在这怎么发给你呢

**Comment by songyajie** [comment]
可以邮箱吗，我录了一个小视频，但是这个上没看到有能发视频的地方，由于是测试环境，所以还不太方便把链接地址给你

**Comment by chenjiahan** [comment]
邮箱：chenjiahan@buaa.edu.cn

**Comment by songyajie** [comment]
邮箱已经发过您了，麻烦有时间看一下，邮件名称：测试视频

**Comment by chenjiahan** [comment]
@songyajie 看了下应该是节点太多导致的性能问题，下个版本会得到改善，到时候可以再观察下

**Comment by songyajie** [comment]
好的，谢谢

**Comment by chenjiahan** [comment]
已在 2.5.8 版本优化
