### ISSUE TITLE
[Bug Report] ImagePreview 关闭图标

### ISSUE THREAD

**Issue by Zclhlmgqzc** [youzan/vant#5880]
### Vant 版本
2.5.7

### Vue 版本
2.6.11

### 描述问题
[#5654](https://github.com/youzan/vant/pull/5654) 
异步关闭的时候，点击关闭图标也应该关闭

**Comment by chenjiahan** [comment]
异步关闭的时候，关闭行为是由外部控制的，组件内部不会主动触发关闭

**Comment by Zclhlmgqzc** [comment]
我的理解是异步关闭时不让人点击界面任何地方就关闭 现在组件有关闭按钮应该是在异步关闭抢上用处比较大 
非异步 点哪里都能关
异步 点按钮关
而且不影响你说的理由 不必显示关闭按钮 
既然异步关闭且要显示关闭按钮 那不就是为了关闭他

**Comment by Zclhlmgqzc** [comment]
我想到一个业务场景 比如广告 几秒后自动关闭 或者点击图标关闭

**Comment by chenjiahan** [comment]
> 一按照异步关闭 纯外部关闭 那么关闭按钮没有配置得必要 配了也不渲染

确实，异步的情况下没有必要配置关闭按钮，开发者不去设置就行。

暂时不计划在组件内部进行主动屏蔽

> 我想到一个业务场景 比如广告 几秒后自动关闭 或者点击图标关闭

这种场景可以通过 cover 插槽加个倒计时的展示
