### ISSUE TITLE
van-popup  v-model=‘’show“  vue中@click=“show=true;”  导致页面刷新

### ISSUE THREAD

**Issue by DelingAlieZ10** [youzan/vant#5881]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
鹿港镇
