### ISSUE TITLE
在安卓中 input 输入时 Tabbar 会自动变化高度。

### ISSUE THREAD

**Issue by dowhilenet** [youzan/vant#5885]
```
    "vant": "^2.5.7",
    "vue": "^2.6.11",
```
设备 小米8 
现象
input 没有聚焦前

![WechatIMG25](https://user-images.githubusercontent.com/10379476/77300582-3fd17600-6d29-11ea-951c-c02f5e925408.jpeg)
input 聚焦后
![WechatIMG26](https://user-images.githubusercontent.com/10379476/77300614-49f37480-6d29-11ea-864b-9eb222eba358.jpeg)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
