### ISSUE TITLE
[Bug Report] search事件监听在popup中在ios上有bug

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#5886]
### 设备 / 浏览器
ios

### Vant 版本
2.5.7

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/search#shi-jian-jian-ting" target="_blank">https://youzan.github.io/vant/#/zh-CN/search#shi-jian-jian-ting</a>

### 描述问题
search事件监听在popup中在ios上有bug，多次点击键盘搜索失焦，然后再点击搜索框聚焦，多次尝试后会偶发的无法聚焦搜索框，感觉是页面失去了响应一样

**Comment by chenjiahan** [comment]
看起来是系统 bug 喔，跟组件没什么关系
