### ISSUE TITLE
tabs组件问题

### ISSUE THREAD

**Issue by yajore** [youzan/vant#589]
**What is the current behavior?**
上代码吧
```js
  <van-tabs :active="tabIndex" sticky
            @click="handleTabClick">
    <van-tab v-for="(item,index) in list"
             :key="index"
             :title="item.label">
    </van-tab>
  </van-tabs>
```
tabIndex在父组件中改变索引值为9，
目前的情况是，active值为9，但是swipe-threshold并没有触发，没有滚动到tabIndex所在位置
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by qianzhaoy** [comment]
把 Vant 版本更新到最新版，应该就好了。 这个问题在 `0.12.6` 版本已经修复了
