### ISSUE TITLE
[Bug Report] vant移动端适配样式字体有问题，渲染会缩小【vant-field、vant-button】里面的字体

### ISSUE THREAD

**Issue by 806computervision** [youzan/vant#5891]
### 设备 / 浏览器
苹果IOS  8plus

### Vant 版本
2.5.2

### Vue 版本
3.0.0-alpha.9

### 重现链接
<a href="https://github.com/806computervision" target="_blank">https://github.com/806computervision</a>

### 描述问题
浏览器手机模式开发样式正常，但是部署到真机上字体样式会缩小，vant其余控件显示正常，目前发现vant-field,vant-button里的字体会特别小

**Comment by 806computervision** [comment]
![image](https://user-images.githubusercontent.com/18653957/77323794-c5b4e780-6d50-11ea-9639-02a5f2f9abc7.png)
![image](https://user-images.githubusercontent.com/18653957/77323958-fe54c100-6d50-11ea-92f0-70228e30a7e4.png)

**Comment by chenjiahan** [comment]
麻烦提供一下复现链接

**Comment by 806computervision** [comment]
内部线上系统，可以发截图么？

**Comment by chenjiahan** [comment]
可以的，建议检查下 viewport 设置了没有

**Comment by 806computervision** [comment]
方便的话可以加个微信聊么？我试了一下还是不行



在 2020-03-24 15:16:23，"neverland" <notifications@github.com> 写道：

可以的，建议检查下 viewport 设置了没有

**Comment by 806computervision** [comment]
viewport 设置了的，我的vx: u86868 希望可以加一下，解决一下，感谢~



在 2020-03-24 15:16:23，"neverland" <notifications@github.com> 写道：

可以的，建议检查下 viewport 设置了没有

**Comment by chenjiahan** [comment]
不加 vx 喔，抱歉。

在 issue 讨论吧

**Comment by AlanKnightly** [comment]
@806computervision  今天遇到一样的问题，排查了好久都不知道怎么回事，请问什么原因导致的呢？该怎么解决呀？

**Comment by zishuYM** [comment]
@AlanKnightly @chenjiahan  碰到了同样的问题，请问什么原因导致的呀！
