### ISSUE TITLE
[Feature Request] 增加对IDE WebStorm 标签类型支持

### ISSUE THREAD

**Issue by maicWorkGithub** [youzan/vant#5893]
### 这个功能解决了什么问题
使用WebStorm开发的时候，所有的vant标签都是Unknown html tag。

### 描述您想要的解决方案
增加web-types

> To improve code completion for different Vue.js component libraries, we have invented a special format of metadata, called web-types. web-types describe the library's components and their directives. In the future, it will support more types of information.

> If you're maintaining your own Vue.js component library, you can add description of the components in the web-types format to your module. To help the IDE to locate this file, a link to it should be added to the "web-types" field in library package.json.

> On http://github.com/JetBrains/web-types you can find the JSON schema, scripts that you can use to generate the metadata in the required format, as well as the latest versions of descriptions for the most popular Vue.js component libraries

### 建议的API是什么样的
如上描述

**Comment by chenjiahan** [comment]
后续会加上👌

**Comment by chenjiahan** [comment]
已在 2.5.8 版本支持，可以试下

**Comment by maicWorkGithub** [comment]
![image](https://user-images.githubusercontent.com/15863224/77735527-b205cb80-7045-11ea-898b-f4bfd8eac033.png)

给力！！！

**Comment by chenjiahan** [comment]
O(∩_∩)O

**Comment by zehuichan** [comment]
@maicWorkGithub 如何设置webstrom，求教

**Comment by chenjiahan** [comment]
@zehuichan 不用设置，默认就有

**Comment by cangyu1993** [comment]
我的webstrom还是未识别的样的？怎么设置的？

**Comment by cangyu1993** [comment]
> ![image](https://user-images.githubusercontent.com/15863224/77735527-b205cb80-7045-11ea-898b-f4bfd8eac033.png)
> 
> 给力！！！

怎么设置的？我的是webstrom2018.2版本的总是不识别
