### ISSUE TITLE
[Bug Report] checkbox 遍历和checkboxgroup组合使用。group的v-model第一次选中无选中值

### ISSUE THREAD

**Issue by wynova** [youzan/vant#5894]
### 设备 / 浏览器
所有平台

### Vant 版本
2.5.7

### Vue 版本
3.0.0-alpha.9

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-7q0n7" target="_blank">https://codesandbox.io/s/vant-issue-moban-7q0n7</a>

### 描述问题
checkbox 遍历和checkboxgroup组合使用。group的v-model第一次选中无选中值

**Comment by chenjiahan** [comment]
checkbox 值的变化是异步的，可以加个 setTimeout 再取值，或者在 change 事件中获取
