### ISSUE TITLE
通过vant-cli去开发组件库，如果依赖vant，可以按需加载打包vant吗？

### ISSUE THREAD

**Issue by JinJieTan** [youzan/vant#5897]
我使用了vant-cli去开发一个组件库，在这个组件库中我要依赖vant这个组件库，可以按需加载吗

**Comment by chenjiahan** [comment]
可以的呢，vant-cli 里默认就配置了按需加载 vant 的

**Comment by JinJieTan** [comment]
谢谢您，我看了我的组件库打包过后，生成的源码，是require形势继续引入vant/下的文件，那这样我实际项目用我的组件库时候，还需要引入vant（按需加载）吗？

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: neverland <notifications@github.com&gt;
发送时间: 2020年3月24日 18:46
收件人: youzan/vant <vant@noreply.github.com&gt;
抄送: Peter <453089136@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[youzan/vant] 通过vant-cli去开发组件库，如果依赖vant，可以按需加载打包vant吗？ (#5897)





 
可以的呢，vant-cli 里默认就配置了按需加载 vant 的

**Comment by chenjiahan** [comment]
要的喔，你可以把 vant 加到你的组件库的 dependencies 里

**Comment by JinJieTan** [comment]
好滴，非常感谢vant !!!!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 晚上6:53
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"Peter"<453089136@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] 通过vant-cli去开发组件库，如果依赖vant，可以按需加载打包vant吗？ (#5897)





 
要的喔，你可以把 vant 加到你的组件库的 dependencies 里

**Comment by coderShiHui** [comment]
那相当于，我实际项目里面不仅需要安装我自己基于vant cli开发的组件库，还得安装vant组件库，感觉这样有点麻烦呢，就算吧vant加到我组件库的dependecies里貌似也解决不了这个问题
