### ISSUE TITLE
[Bug Report] Form 中 field组件点击弹出 Popup,导致其他field关联的字段清空

### ISSUE THREAD

**Issue by yetuweiba** [youzan/vant#5898]
### 设备 / 浏览器
chrome

### Vant 版本
2.5.7

### Vue 版本
2.5.2

### 重现链接
<a href="https://codepen.io/yetuweiba/project/editor/ZdWQzW" target="_blank">https://codepen.io/yetuweiba/project/editor/ZdWQzW</a>

### 描述问题
在Form组件中,设置field为可点击,点击后弹出弹框,会把其他field数据清空

**Comment by chenjiahan** [comment]
1. field 绑定值要使用 v-model
2. 是 van-form，不是 vant-form

**Comment by yetuweiba** [comment]
...多谢指正
