### ISSUE TITLE
[Bug Report] 使用Vant-cli构建组件，使用scss，build后出现深度选择器（::v-deep）未解析问题 

### ISSUE THREAD

**Issue by simmzl** [youzan/vant#5899]
### 设备 / 浏览器
mac pro / chrome
### @vant/cli 版本
2.2.8
### Vue 版本
2.6.11

### 重现链接
<a href="http://js.jirengu.com/pucugeropa/1/edit?html,output" target="_blank">http://js.jirengu.com/pucugeropa/1/edit?html,output</a>

### 描述问题
使用scss，在组件中使用深度选择，
1. 使用::v-deep ，在npm run dev 下 ，正常。npm run build时，构建出来的未解析 ::v-deep 
2. 使用 /deep/ ，dev和build下直接报错
3. 使用 >>> ，这个一般css用，我也试了。dev 下 ，正常，build下未解析

打开上面重现链接，在控制台搜索"update__"就可以看到未解析的css代码了，见下图：
https://static.cdn.soulapp.cn/image/test/WechatIMG551.png

在dev下，是正确的解析：https://static.cdn.soulapp.cn/image/test/WechatIMG552.png

在build-site打包的站点文件里，也是正确解析的。

### 原因

npm run build跑的是@vant/cli/lib/config/webpack.package.js配置导致的？

**Comment by chenjiahan** [comment]
目前 build 命令还不支持解析 scoped 样式，后续会支持下

**Comment by chenjiahan** [comment]
已在 @vant/cli 2.3.0 版本支持
