### ISSUE TITLE
业务组件比如地址编辑，按钮文本支持修改吗？（比如保存改成提交）

### ISSUE THREAD

**Issue by lejsure** [youzan/vant#590]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
对于一些固定文案，可以通过 Locale 组件修改语言配置，参考下面的例子：

```js
import { Locale } from 'vant';

Locale.add({
  'zh-CN': {
    vanAddressEdit: {
      save: '提交'
    }
  }
});
```

详细文档：https://www.youzanyun.com/zanui/vant#/zh-CN/component/i18n

**Comment by lejsure** [comment]
so thanks
