### ISSUE TITLE
[Bug Report] Calendar 多选情况下，设置 default-date 报错

### ISSUE THREAD

**Issue by zehuichan** [youzan/vant#5901]
vant版本v2.5.7
vue版本v2.6.11

```
<van-calendar
      v-model="show"
      type="multiple"
      :default-date="currentDate"
      get-container="body"
      @confirm="onConfirm"
    />
```

发现`type=multiple`的情况下，且设置`default-date`的情况下，报错

[附：codesandbox](https://oz66s.csb.app/)

**Comment by JakeLaoyu** [comment]
codesandbox 能否给一下源码

**Comment by zehuichan** [comment]
@JakeLaoyu 
[codesandbox 源码](https://codesandbox.io/s/vant-calendar-issue-oz66s)

**Comment by chenjiahan** [comment]
已在 2.5.8 版本修复
