### ISSUE TITLE
引起报错 DOMException: Failed to execute 'appendChild' on 'Node':

### ISSUE THREAD

**Issue by mikeFM123** [youzan/vant#5902]
引起报错 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

所在页面 vant/src/mixins/popup/index.js 
94行
this.$parent.$el.appendChild(this.$el);

**Comment by wangkui1991** [comment]
我的情况是dev环境没问题，build后start，van-popup和van-search组件没生效，同时控制台报错Failed to execute 'appendChild' on 'Node': This node type does not support this method
