### ISSUE TITLE
[Bug Report] uploader 组件在支付宝端无法选择图片

### ISSUE THREAD

**Issue by asd8855** [youzan/vant#5906]
### 设备 / 浏览器
华为mate20

### Vant 版本
2.5.7

### Vue 版本
2.6.10

### 重现链接
<a href="https://www.baidu.com" target="_blank">https://www.baidu.com</a>

### 描述问题
用华为mate20支付宝扫一扫，扫官方的vanth5二维码,即可复现。ps:直接拍照是可以的，选择不了图片

**Comment by asd8855** [comment]
用华为mate20支付宝扫一扫，扫官方的vanth5二维码,即可复现。ps:直接拍照是可以的，选择不了图片

**Comment by JakeLaoyu** [comment]
支付宝webview不支持上传图片哦
参见  https://opendocs.alipay.com/mini/006kw7

![image](https://user-images.githubusercontent.com/16181940/77715033-7521e080-7015-11ea-8f85-6836d799c37a.png)

**Comment by chenjiahan** [comment]
可以试下用 input type="file" 能选择图片不

**Comment by besswang** [comment]
三星手机不兼容啊，文件中的图片上传不了，小米，华为上传没啥问题的

**Comment by asd8855** [comment]
> 可以试下用 input type="file" 能选择图片不

也不行，好像是支付宝吧onload事件重写了

**Comment by chenjiahan** [comment]
目前看来是支付宝端的问题，在组件层面暂时没有解决方案，先 close 咯
