### ISSUE TITLE
[Bug Report] Swipe 自定义滑块大小，取消autoplay, 滑到最后一屏，在屏幕高度或者宽度发生变化时，最后一屏会左对齐，官网的文档例子可以重现

### ISSUE THREAD

**Issue by bellorchid** [youzan/vant#5912]
### 设备 / 浏览器
ALL/UC 浏览器

### Vant 版本
2.5.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/swipe" target="_blank">https://youzan.github.io/vant/#/zh-CN/swipe</a>

### 描述问题
Swipe 自定义滑块大小，取消autoplay, 滑到最后一屏，在屏幕高度或者宽度发生变化时，最后一屏会左对齐，官网的文档例子可以重现，Chrome浏览器切换成手机模式再切换回来，就可以重现

**Comment by chenjiahan** [comment]
确实存在这个问题，下个版本会修复下

**Comment by bellorchid** [comment]
响应太快了，有赞！

**Comment by chenjiahan** [comment]
已在 2.5.8 版本修复✌️

**Comment by bellorchid** [comment]
哈哈哈，还寻思vant BUG上线要等几周，结果我这边做的兼容代码还没上线就可以删除了😆

**Comment by chenjiahan** [comment]
一般每周都会发版的 ^_^
