### ISSUE TITLE
Sidebar 侧边导航不能垂直滚动，能支持下吗

### ISSUE THREAD

**Issue by dream-lmc** [youzan/vant#5914]
Sidebar 侧边导航不能垂直滚动，能支持下吗。菜单项多了就不能滚动了

**Comment by chenjiahan** [comment]
可以的，组件上可以添加一个 `overflow-y: auto;` 样式，高度由开发者自行控制，内容超过高度时就会触发滚动

**Comment by dream-lmc** [comment]
感谢大佬，完美解决.

**Comment by chenjiahan** [comment]
已在 2.5.8 版本支持

**Comment by dream-lmc** [comment]
> 已在 2.5.8 版本支持

你好问下文档更新了，在最新版本中如何使用呢？

**Comment by chenjiahan** [comment]
加个高度限制就行，overflow: auto 已经默认加上了
