### ISSUE TITLE
[Bug Report] youzan.github.io在chrome于firefox打开报错，提示非私密链接，safari可以正常打开

### ISSUE THREAD

**Issue by nikungea** [youzan/vant#5915]
### 设备 / 浏览器
mac10.15.4 chrome80.0.3987.149,firefox74.0

### Vant 版本
2.5.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io" target="_blank">https://youzan.github.io</a>

### 描述问题
youzan.github.io在chrome于firefox打开报错，提示非私密链接，safari可以正常打开
别的网站都是正常的

**Comment by nikungea** [comment]
又可以了，不好意思

**Comment by chenjiahan** [comment]
可能是 github pages 的证书问题

官网进不去的话可以先用 gitee 镜像：https://vant-contrib.gitee.io/vant
