### ISSUE TITLE
官网炸了！貌似是https到期了。

### ISSUE THREAD

**Issue by DaDaDaBocai** [youzan/vant#5916]
![image](https://user-images.githubusercontent.com/54394452/77616459-aabebf00-6f6c-11ea-9aed-2e2d5cfa77f4.png)

**Comment by chenjiahan** [comment]
官网进不去的可以先用 gitee 镜像：https://vant-contrib.gitee.io/vant

**Comment by Martin-Chen** [comment]
我的也进不去

**Comment by Mr-lrf** [comment]
是证书到期了吗

**Comment by JakeLaoyu** [comment]
域名是 github 的

**Comment by chenjiahan** [comment]
来自维基百科：

> 2020 年 3 月 26 日，GitHub Pages 遭到了中间人的攻击，经网友发现，该签署过的证书来自广东省深圳市，过期时间为 2029 年 9 月 23 日。当前尚未结束。[11]

https://zh.wikipedia.org/wiki/%E5%AF%B9GitHub%E7%9A%84%E5%AE%A1%E6%9F%A5%E5%92%8C%E5%B0%81%E9%94%81
