### ISSUE TITLE
关于Icon图标组件使用本地字体的问题

### ISSUE THREAD

**Issue by buliwangzhu** [youzan/vant#592]
文档中关于Icon图标组件使用本地字体的说明如下：
```
使用本地字体文件
Icon 组件默认引用 yzcdn.cn 域名下的字体文件，如果想要使用本地字体文件，请引入下面的 css 文件
import 'vant/lib/vant-css/icon-local.css';
```
但是没有其他的详细说明，不是很明白，官方的人可以在这里说明下吗？比如我想使用Iconfont-阿里巴巴矢量图标库里的字体，该怎么操作呢

**Comment by chenjiahan** [comment]
本地字体指的是引用本地的 ttf 文件，目前还不支持使用第三方字体噢

**Comment by buliwangzhu** [comment]
我看了源码后，发现icon-local.css这里的字体文件是写死的，代码是：
`@font-face{font-style:normal;font-weight:400;font-family:vant-icon;src:url(vant-icon-dc7d92.ttf) format('truetype')}`
那我应该怎么应用本地字体文件呢？

**Comment by buliwangzhu** [comment]
是不是文档里说的本地字体，指的是yzcdn.cn这里的字体本地化了？而不是自定义的第三方字体？

**Comment by qianzhaoy** [comment]
@buliwangzhu 因为以前的字体文件是 cdn， 后来改成本地化了。我现在也是用的 iconfont 的字体图标。 做法就是直接写样式覆盖原样式了。

[我的做法](https://github.com/qianzhaoy/vant--mobile-mall/blob/master/src/assets/scss/iconfont/iconfont.css)

**Comment by chenjiahan** [comment]
目前可以参考 @qianzhaoy  的做法~ 我们后续看看有没有更方便的方式
