### ISSUE TITLE
官网无法访问的解决方法

### ISSUE THREAD

**Issue by chenjiahan** [youzan/vant#5920]
目前 Vant 的文档网站部署在 Github Pages 上，今天疑似有人攻击 Github Pages，导致官网因证书问题无法访问。

from [维基百科](https://zh.wikipedia.org/wiki/%E5%AF%B9GitHub%E7%9A%84%E5%AE%A1%E6%9F%A5%E5%92%8C%E5%B0%81%E9%94%81)：

> 2020 年 3 月 26 日，GitHub Pages 遭到了中间人的攻击，经网友发现，该签署过的证书来自广东省深圳市，过期时间为 2029 年 9 月 23 日。当前尚未结束。[11]

解决方法：

使用 Gitee 镜像网站 https://vant-contrib.gitee.io/vant

**Comment by wzc0x0** [comment]
昨天已发现，还好挂了代理，目前是没有了响应
