### ISSUE TITLE
使用babel-plugin-import按需加载组件失败

### ISSUE THREAD

**Issue by MaMaFish** [youzan/vant#5923]
今天新建项目，发现当使用babel-plugin-import v1.13.0 按需加载组件会找不到相关的依赖
These dependencies where not found

把babel-plugin-import 版本降到v1.12.0，就可以正常按需加载了。

vant v2.5.7

**Comment by chenjiahan** [comment]
我这边是没问题的呢，可以提供个复现仓库看下

**Comment by MaMaFish** [comment]
> 我这边是没问题的呢，可以提供个复现仓库看下

用家里的PC试了一下没有复现成功，可能之前没处理正确，感谢
