### ISSUE TITLE
[Feature Request] 希望 Form 表单验证可以使用 Toast 提示失败的消息

### ISSUE THREAD

**Issue by lipengzhou** [youzan/vant#5924]
### 这个功能解决了什么问题
自定义消息提示方式

### 描述您想要的解决方案
支持自定义消息提示方式

### 建议的API是什么样的
建议给 `Form` 组件增加一个属性：
属性名：`show-error-message`
属性值：布尔值，`true`（作为默认值） 显示错误提示消息，`false` 不显示错误提示消息
用户可以在 Form 组件的 `failed` 事件中使用 `Toast` 等方式提示验证失败消息

**Comment by chenjiahan** [comment]
可以的，下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.5.8 版本支持

**Comment by lipengzhou** [comment]
> 已在 2.5.8 版本支持

效率太高了，非常感谢。

**Comment by chenjiahan** [comment]
要取消标红的话

**Comment by chenjiahan** [comment]
考虑了下，会新加一个 `show-error` 属性，这样能比较灵活地控制

**Comment by chenjiahan** [comment]
已在 2.6.0-beta.0 版本支持

**Comment by fengyun2** [comment]
> 考虑了下，会新加一个 `show-error` 属性，这样能比较灵活地控制

2.8.2 show-error = false 不生效

**Comment by chenjiahan** [comment]
@fengyun2 提供下 codesandbox 复现链接

**Comment by lipengzhou** [comment]
> > 考虑了下，会新加一个 `show-error` 属性，这样能比较灵活地控制
> 
> 2.8.2 show-error = false 不生效

怀疑你的代码写成这样了：`show-error="false"`，这种语法任何数据都会当作字符串来处理，没有任何数据类型。

如果要绑定布尔值 `false` 的话，需要使用 `v-bind` 指令，使用了 `v-bind` 语法绑定的所有内容都会当作 JavaScript 来处理。

```html
v-bind:show-error="false"
```

在 Vue 中，`v-bind` 指令可以简写为一个英文半角冒号，所以也可以这样：

```html
:show-error="false"
```
