### ISSUE TITLE
Picker 增加滑动系数

### ISSUE THREAD

**Issue by lihentian** [youzan/vant#5925]
滑动偏灵敏无法准确定位到目标选项，
是否可增加滑动系数，
优化TouchMove体验

**Comment by chenjiahan** [comment]
Picker 有 swipe-duration 属性，可以试下能否满足你的需求

**Comment by lihentian** [comment]
@chenjiahan  不能 ，是滑动距离过快造成定位不精确， 加大动画时间体验会很糟糕
swipe-duration 2s   1s  100px -> 2s 100px
系数0.5  1s 100px -> 1s 50px

**Comment by chenjiahan** [comment]
滑动系数最好是在组件内调整到一个最佳状态，而不是在外部控制

具体是什么情况下会出现定位不精确呢，是选项数量很多吗

**Comment by lihentian** [comment]
是单纯的太好滑了， 看了源码是1:1

**Comment by chenjiahan** [comment]
现在确实是滑的快了些，下个版本会调整下，尽量和 iOS 原生的速率一致

**Comment by chenjiahan** [comment]
已在 2.6.0-beta.0 版本优化
