### ISSUE TITLE
[Bug Report] NumberKeyboard 的 show-delete-key属性没有起作用

### ISSUE THREAD

**Issue by suciy** [youzan/vant#5929]
### 设备 / 浏览器
iphone x

### Vant 版本
2.5.7

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-xv6pw" target="_blank">https://codesandbox.io/s/vant-issue-moban-xv6pw</a>

### 描述问题
使用show-delete-key隐藏删除按钮，但是页面依然显示删除按钮。

**Comment by chenjiahan** [comment]
确实有问题，下个版本会修复下

**Comment by chenjiahan** [comment]
已在2.5.9-beta.0 版本修复

**Comment by suciy** [comment]
perfect!
