### ISSUE TITLE
[Bug Report] icon图标在真机上会出现无法对齐

### ISSUE THREAD

**Issue by leaper1** [youzan/vant#5930]
### 设备 / 浏览器
手机

### Vant 版本
2.5.8

### Vue 版本
3.0.0-alpha.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-xd891" target="_blank">https://codesandbox.io/s/vant-issue-moban-xd891</a>

### 描述问题
icon图标与文字一行时，会出现无法对齐的情况，不同手机下展示不同。例如NabBar导航在魅族16sPro下就出现错位

**Comment by leaper1** [comment]
![image](https://user-images.githubusercontent.com/25759296/77741439-dcf51d00-704f-11ea-8001-c49ac1ab0c22.png)

**Comment by leaper1** [comment]
![vant-demo](https://user-images.githubusercontent.com/25759296/77741517-fa29eb80-704f-11ea-86b9-866b0e0bba48.jpg)

**Comment by chenjiahan** [comment]
目前是通过 inline-block + vertical-align: middle 对齐的，下个版本会改成 flex 居中试下

**Comment by chenjiahan** [comment]
已在 2.6.0-beta.0 版本优化
