### ISSUE TITLE
[Bug Report] 下拉刷新无法自动撑满

### ISSUE THREAD

**Issue by shlroland** [youzan/vant#5932]
### 设备 / 浏览器
Chrome

### Vant 版本
2.5.5

### Vue 版本
2.6.10

### 重现链接
<a href="https://jsbin.com/qasajuvuyo/edit?html,output" target="_blank">https://jsbin.com/qasajuvuyo/edit?html,output</a>

### 描述问题
下拉刷新官网文档示例中的van-pull-refresh__track类，css有height:100%，2.5.5版本没有自动填写，导致无法撑开，需用深度选择器设置。

**Comment by chenjiahan** [comment]
升级到 2.5.8 版本就可以咯，刚加的
