### ISSUE TITLE
tag组件，plain和非plain，高度不一致，组件加上style="line-height: 1.5"后，正常

### ISSUE THREAD

**Issue by macmatilda** [youzan/vant#5936]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

##不正常 左边的组件比右边的组件低一个像素
```
<van-tag type="danger" plain>剩余100人次</van-tag>
<van-tag type="danger">总需500人次</van-tag>
```
调试css，由style="line-height: normal"引起
##正常，加上style="line-height: 1.5"，
```
<van-tag type="danger" plain style="line-height: 1.5">剩余100人次</van-tag>
<van-tag type="danger" style="line-height: 1.5">总需500人次</van-tag>
```

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/77895779-d8c43c00-72a9-11ea-8dd9-4d221cf567d3.png)

试了下在 chrome 和 safari 上都是正常的，可能是个别机型的渲染问题

用 `line-height: normal` 是为了安卓机型上文字能居中对齐，使用 line-height: 1.5 会经常出现文字偏高的问题
