### ISSUE TITLE
android_23 save事件里获取到的中文，get请求显示乱码？需要转码？这个问题我也再看看，先看看大家有遇到过没？

### ISSUE THREAD

**Issue by lejsure** [youzan/vant#594]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by lejsure** [comment]
![image](https://user-images.githubusercontent.com/10054695/35621165-6258eec0-06be-11e8-8482-3a408fecc13c.png)

**Comment by lejsure** [comment]
似乎跟机型有关，现在处理方式 传送接收数据编码解码

**Comment by chenjiahan** [comment]
sorry 不是很懂你的问题
