### ISSUE TITLE
[Feature Request] 希望 Area 地区选择提供异步获取功能

### ISSUE THREAD

**Issue by powerdong** [youzan/vant#5942]
## 这个功能解决了什么问题

可以不用一次性获取全部的area数据

## 描述您想要的解决方案

希望通过选择省数据后异步获取市数据，然后更新视图

##  目前情况

目前areaList更新后未实现视图更新

**Comment by chenjiahan** [comment]
暂无计划支持喔，你可以通过 Picker 组件来实现这个功能

**Comment by lx815** [comment]
如果不支持异步获取数据，麻烦在文档中标注一下。试了半天，发现不能异步获取数据
