### ISSUE TITLE
[Feature Request] calendar组件默认选中日期

### ISSUE THREAD

**Issue by WYDgits** [youzan/vant#5944]
### 这个功能解决了什么问题
组件挺好用的

### 描述您想要的解决方案
之前我看到过一个 issue ，说是calendar组件默认显示日期月份 是min-date 而不是 now-date，我也遇到了这样的问题，并且希望得到解决，但是后来就找不到这个issue

### 建议的API是什么样的
不知道是否现在解决了这个问题，所有问一下

**Comment by chenjiahan** [comment]
这个问题已经解决过了，可以升级最新版试下
