### ISSUE TITLE
[Bug Report] Button组件使用自定义图标无效, 即icon-prefix不生效

### ISSUE THREAD

**Issue by yguilai** [youzan/vant#5945]
### 设备 / 浏览器
Chrome

### Vant 版本
2.5.8

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/quizzical-dust-hojqm" target="_blank">https://codesandbox.io/s/quizzical-dust-hojqm</a>

### 描述问题
Button组件使用自定义图标无效
审查元素发现默认的van-icon类并没有被替换
我使用Icon组件
`<van-icon class-prefix="iconfont" name="fenlei"></van-icon>`
确认了我的iconfont.css是没问题的

**Comment by chenjiahan** [comment]
确实有问题，下个版本会修复下

**Comment by chenjiahan** [comment]
已在 2.6.0-beta.0 版本修复
