### ISSUE TITLE
使用PullRefresh组件赋予高度之后导致无法下拉

### ISSUE THREAD

**Issue by Arainersky** [youzan/vant#5946]
使用PullRefresh组件赋予class高度之后，打包到移动端没有办法上划。下拉刷新可以正常使用，以下为代码。
Vue代码
`<PullRefresh class="drag-drop" v-model="isLoading" success-text="刷新成功" @refresh="onRefresh">
        <data-list-loading :load-type="loadType" />
        <div v-for="(item,index) in dataList" :key="index" class="item-panel">
          <Panel :title="item.pickingRecordCode" :status="item.updaterName">
            <div @click="clickDataInfo(item)">
              <CellGroup>
                <Cell title="销售单号" :value="item.saleOrderCode" />
                <Cell title="批次" :value="item.productCode" />
                <Cell title="数量" :value="item.quantity" />
              </CellGroup>
            </div>
            <template #footer class="btnList">
              <Button size="small" type="info" @click="clickResult(item)">出货</Button>
            </template>
          </Panel>
        </div>
        <NoDataList :data-type="dataType" />
      </PullRefresh>`
css代码
//.drag-drop{
//  height:calc(100vh - 110px);
//}

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
