### ISSUE TITLE
为什么引用的插件在微信编辑器里可以正常使用，在手机上Toast的提示成功的对号图片就不显示了？

### ISSUE THREAD

**Issue by Cuiwenfeng** [youzan/vant#595]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@Cuiwenfeng 未能复现你的问题，麻烦提供下复现步骤
