### ISSUE TITLE
[Bug Report] 使用PullRefre组件赋予高度之后导致无法上拉

### ISSUE THREAD

**Issue by Arainersky** [youzan/vant#5950]
### 设备 / 浏览器
安卓设备，Chrome

### Vant 版本
2.5.9-beta.0

### Vue 版本
3.0.0-alpha.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/pull-refresh" target="_blank">https://youzan.github.io/vant/#/zh-CN/pull-refresh</a>

### 描述问题
使用PullRefre组件赋予高度之后导致内容无法上拉滑动，下拉刷新正常

**Comment by chenjiahan** [comment]
写死高度的话，可能是没设置 `overflow-y: auto`，可以加上试下
