### ISSUE TITLE
与android 原生交互

### ISSUE THREAD

**Issue by chhyu** [youzan/vant#5952]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

项目中涉及到一些硬件，请问怎么跟原生android交互

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
硬件交互与组件库无关，请自行实现
