### ISSUE TITLE
[Bug Report]打扰了，van-nav-bar服务端渲染时报window is not defined

### ISSUE THREAD

**Issue by Huitimkit** [youzan/vant#5958]
设备 / 浏览器
Chrome

Vant 版本
2.5.8

Vue 版本
2.6.11

重现链接
无

描述问题
van-nav-bar服务端渲染时报window is not defined
![1](https://user-images.githubusercontent.com/3151868/77978358-7cf2c500-7334-11ea-8b82-a73b24696618.png)

**Comment by jurieo** [comment]
我也出现了同样的问题，发现是粘性布局那个地方使用了window

**Comment by cilla123** [comment]
我这边解决办法只能<client-only></client-only>包起来了，nuxt

**Comment by chenjiahan** [comment]
一会儿发个修复版本👌

**Comment by chenjiahan** [comment]
已在 2.5.9 版本修复
