### ISSUE TITLE
Waterfall 和 PullRefresh 在同个页面时，会有冲突

### ISSUE THREAD

**Issue by linqiang007** [youzan/vant#596]
Waterfall 设置了高度
**1.Waterfall 包含或与 PullRefresh 同级**
  Waterfall加载更多正常使用，上拉后再往下拉后，下拉滚动条失效，会自动触发PullRefresh，。

**2.PullRefresh 包含 Waterfall**
Waterfall列表无法滚动。

**Comment by chenjiahan** [comment]
感谢反馈，近期会看一下这个问题

**Comment by chenjiahan** [comment]
已在 1.0 版本中新增了 List 组件作为 Waterfall 的替代，支持和 PullRefresh 同时使用
