### ISSUE TITLE
[Bug Report] 【van-stepper】disable-input属性下ios会出现'完成一栏'

### ISSUE THREAD

**Issue by YeKao** [youzan/vant#5961]
### 设备 / 浏览器
iPhone

### Vant 版本
2.5.9

### Vue 版本
2.5.17

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/stepper" target="_blank">https://youzan.github.io/vant/#/zh-CN/stepper</a>

### 描述问题
【van-stepper】disable-input属性下，点击输入框，ios数字键盘没有弹出，但是底部会出现'完成'一栏，

**Comment by chenjiahan** [comment]
用 iOS 试了下没复现，具体是什么机型，系统版本多少喔？

**Comment by YeKao** [comment]
> 用 iOS 试了下没复现，具体是什么机型，系统版本多少喔？

iPhone8 系统版本11.1.2
iPhone6 系统版本10.3.2
上面两个会出现
iPhone10是正常的

**Comment by chenjiahan** [comment]
明白了👌 这个是旧版 Safari 的 bug，下个版本会兼容一下

**Comment by chenjiahan** [comment]
已在 2.6.0-beta.0 版本兼容

**Comment by YeKao** [comment]
> 已在 2.6.0-beta.0 版本兼容

yarn 怎么更新到 v2.6.0-beta.0？

**Comment by chenjiahan** [comment]
```bash
yarn add vant@2.6.0-beta.0
```
