### ISSUE TITLE
[Bug Report] van-tabs标签的offset-top属性 写成字符串时sticky失效

### ISSUE THREAD

**Issue by gaga1233** [youzan/vant#5962]
### 设备 / 浏览器
google

### Vant 版本
2.5.9

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/gaga1233/pen/oNXmRPV?editors=1111" target="_blank">https://codepen.io/gaga1233/pen/oNXmRPV?editors=1111</a>

### 描述问题
van-tabs标签的offset-top属性为string时  sticky失效

**Comment by chenjiahan** [comment]
offset-top 不支持传入单位喔，可以把 px 后缀去掉
