### ISSUE TITLE
[Bug Report] van-field使用了v-if判断，切换两次验证会有点问题

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#5964]
### 设备 / 浏览器
谷歌

### Vant 版本
2.5.9

### Vue 版本
3.0.0-alpha.10

### 重现链接
<a href="http://暂无链接.com" target="_blank">http://暂无链接.com</a>

### 描述问题
使用一个pciker去控制一个证件类型type值，根据type值使用v-if去控制出生日期和性别的展示,，但是切换两次之后，当选择“身份证”，隐藏掉出生日期之后，出生日期这个表单还是走了验证，请问有没有好的解决办法呢，使用了v-show控制，并且动态的去修改了验证的required值，效果还是一样的，请加一下，有没有好的解决办法

**Comment by lmfuture** [comment]
发现一个问题就是：提交某个

**Comment by suguoyao** [comment]
请问这个问题解决了吗？
