### ISSUE TITLE
[Bug Report] uploader组件无法显示微信聊天中保存到手机里的图片

### ISSUE THREAD

**Issue by nicksun011** [youzan/vant#5965]
### 设备 / 浏览器
Huawei mate9 pro

### Vant 版本
2.5.7

### Vue 版本
3.0.0-alpha.10

### 重现链接
<a href="https://youzan.github.io/vant/mobile" target="_blank">https://youzan.github.io/vant/mobile</a>

### 描述问题
微信聊天中接收到一张图片，保存到手机，使用Uploader组件选择图片后，无法预览。官方demo就可以复现。另外这种图片也无法读取到图片type，返回的base64数据中也缺少类似image/jpeg的标示。另外如果url中没有后缀名，也无法预览图片

**Comment by chenjiahan** [comment]
这个是图片格式的问题，组件也无能为力喔
