### ISSUE TITLE
[Bug Report] 动态插入van-field节点验证顺序的问题

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant#5966]
### 设备 / 浏览器
谷歌

### Vant 版本
2.5.9

### Vue 版本
3.0.0-alpha.10

### 重现链接
<a href="http://www.暂无.com" target="_blank">http://www.暂无.com</a>

### 描述问题
我现在有一个下拉框选择的是证件类型(身份证和户口本)，选择身份证时不需要显示生日(日期的picker)并且不验证；选择户口本时需要选择生日；
当我第一时间选择了户口本并且点击了提交表单，此时生日输入框的验证触发并报错；这时候我没有 立即去选择生日，当我切换到身份证时，点提交感觉前面操作的生日报错还是给我拦截了；怎样操作才能避免呢？
https://res-hx-bj.baoxianxia.com.cn/WechatIMG601.png
https://res-hx-bj.baoxianxia.com.cn/WechatIMG603.png
这里我对出生日期框进行了自定义验证，做了两种证件的判断，但是都是提前预加载完的，还是没生效，不知道有没有解决办法

**Comment by lmfuture** [comment]
`
				<div v-show='applicant.cardType != "01"' class="juge_co">
					
					<van-field name="" label="性别">
					  <template #input>
					    <van-radio-group @change="changeSex('tbr')" v-model="applicant.sex" direction="horizontal">
					      <van-radio name="0">男</van-radio>
					      <van-radio name="1">女</van-radio>
					    </van-radio-group>
					  </template>
					</van-field>
					
					<van-field 
						name='applicantBirth' 
						:rules='[{ validator: regBirthday, message: "请选择出生日期" ,cardType: applicant.cardType}]' 
						@click='showBirthdayDate("applicant","")' 
						v-model="applicant.birthday" 
						readonly is-link 
						placeholder='请选择出生日期' 
						label="出生日期"
					/>
				</div>
`

`//验证出生日期
export function regBirthday(value,rule){
    if(rule.cardType != '01'){//户口本
        if(value == ""){
            return false;
        }else{
            return true;
        }
    }else{//生日
        return true;
    }
    return false;
}`

**Comment by lmfuture** [comment]
<div v-show='applicant.cardType != "01"' class="juge_co">
					
					<van-field name="" label="性别">
					  <template #input>
					    <van-radio-group @change="changeSex('tbr')" v-model="applicant.sex" direction="horizontal">
					      <van-radio name="0">男</van-radio>
					      <van-radio name="1">女</van-radio>
					    </van-radio-group>
					  </template>
					</van-field>
					
					<van-field 
						name='applicantBirth' 
						:rules='[{ validator: regBirthday, message: "请选择出生日期" ,cardType: applicant.cardType}]' 
						@click='showBirthdayDate("applicant","")' 
						v-model="applicant.birthday" 
						readonly is-link 
						placeholder='请选择出生日期' 
						label="出生日期"
					/>
				</div>


//验证出生日期
export function regBirthday(value,rule){
    if(rule.cardType != '01'){//户口本
        if(value == ""){
            return false;
        }else{
            return true;
        }
    }else{//生日
        return true;
    }
    return false;
}

**Comment by lmfuture** [comment]
https://media.baoxianxia.com.cn/checkBirth.mov

**Comment by lmfuture** [comment]
https://media.baoxianxia.com.cn/checkBirth.mov 这是视频链接，有没有办法可以在我选择身份证时将未关闭的生日的错误验证关掉呢

**Comment by chenjiahan** [comment]
把 v-show 改成 v-if 应该就可以，v-show 只是隐藏了元素，但表单项依然存在于表单中

**Comment by lmfuture** [comment]
@chenjiahan 开始用的是v-if，但是应该是生命周期的原因在渲染时，验证并没有加上；切换成其他证件我的出生日期的验证并没有触发

**Comment by lmfuture** [comment]
@chenjiahan 之前用了v-if上面说的那个问题是可以解决，但是使用v-if切换过来的表单(出生日期),并没有按顺序验证，只有在所有其他表单验证通过之后才会再来验证这个框，分别换了trigger：onBlur和onChange都是在最后只剩下这个没填才会去验证，不清楚什么原因

**Comment by chenjiahan** [comment]
动态插入的节点确实存在校验顺序问题，后续会修复下

**Comment by lmfuture** [comment]
好的，谢谢啦，辛苦团队了

**Comment by chenjiahan** [comment]
已在 2.6.0-beta.0 版本修复

**Comment by alisaWXtang** [comment]
"name": "vant",
  "version": "4.6.6",

**Comment by alisaWXtang** [comment]
"name": "vant",
"version": "4.6.6"
该问题依然存在 @chenjiahan

**Comment by alisaWXtang** [comment]
"name": "vant",
"version": "4.6.6",
该问题依然存在 @chenjiahan

**Comment by chenjiahan** [comment]
@alisaWXtang 可以新建 issue 并附上复现问题的 codesandbox 链接
