### ISSUE TITLE
[Feature Request] Calendar 组件

### ISSUE THREAD

**Issue by WYDgits** [youzan/vant#5967]
### 这个功能解决了什么问题
弹窗展示能够默认显示当前月份

### 描述您想要的解决方案
平埔展示，本来进入页面能够默认显示当前页面，但是切换页面后再次回到日历页面的时候，有副标题和星期，但是日期是空白，必须通过滑动才能显示月份，而且非当前月份

### 建议的API是什么样的
希望能够得到回复

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by WYDgits** [comment]
emmm 没搞过那个 我列下 我代码
```
<van-calendar
        type="single" 
	v-model="initshow"
	:show-mark="true" 
	color="#4ea1fa" 
	:min-date="minDate"
	:max-date="maxDate" 
	:show-title="false"
	:show-subtitle="true"
	:default-date="defaultDate" 
	:poppable="false" 
	:show-confirm="false" 
	:style="{ height: '400px' }"
	:formatter="formatter">
</van-calendar>
```
initshow是初始化mounted函数执行后设置的一个值，当前设置，首次加载页面的时候能够正常显示，但是跳转到其他页面再返回本页面的时候，日期未显示，滚动能够显示。另外，我设置了 路由keep-alive

**Comment by chenjiahan** [comment]
已在 2.6.0-beta.0 版本修复
