### ISSUE TITLE
[Bug Report] uploader组件在小米手机APP内的h5点击无效果

### ISSUE THREAD

**Issue by gch2010net** [youzan/vant#5969]
### 设备 / 浏览器
小米手机   点金台APP内的h5网页

### Vant 版本
2.5.9

### Vue 版本
3.0.0-alpha.10

### 重现链接
<a href="https://www.51djt.com" target="_blank">https://www.51djt.com</a>

### 描述问题
uploader组件在小米手机APP内的h5点击无效果

**Comment by chenjiahan** [comment]
APP 内无法上传一般是 APP 的 WebView 配置问题，可以找原生开发同学一起排查下
