### ISSUE TITLE
使用PostCSS 插件定制主题报错，找不到$poses变量

### ISSUE THREAD

**Issue by functionwell** [youzan/vant#597]
**What is the current behavior?**
使用PostCSS 插件定制主题报错，找不到$poses变量
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**
在js中引入了对应的postcss 源码，webpack构建时报找不到$poses变量，在\vant-css\src\mixins\border-retina.css第5行
**What is the expected behavior?**
![default](https://user-images.githubusercontent.com/18190879/35659545-bec8dd7c-0741-11e8-97e2-1fac1727aba3.png)
![default](https://user-images.githubusercontent.com/18190879/35659556-cccedd90-0741-11e8-84b6-b57bbafde84b.png)
![default](https://user-images.githubusercontent.com/18190879/35659560-d4dcfbac-0741-11e8-84ac-a4c5c3083db1.png)
![default](https://user-images.githubusercontent.com/18190879/35659562-db7bd2ee-0741-11e8-9ced-fef1a260dc81.png)

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
vue 2.5.13
vant 0.12.7

**Comment by chenjiahan** [comment]
@functionwell 试了下没能复现你的问题，能否提供一个复现该问题的仓库？
