### ISSUE TITLE
[Bug Report] lazyload background-image adapter

### ISSUE THREAD

**Issue by evechiu** [youzan/vant#5970]
### 设备 / 浏览器
chrome

### Vant 版本
2.3.3

### Vue 版本
2.6.10

### 重现链接
<a href="https://codepen.io/evechiu/pen/RwPdQxd" target="_blank">https://codepen.io/evechiu/pen/RwPdQxd</a>

### 描述问题
想要在 lazyload background-image 添加 adapter 侦测图片错误,但似乎不起作用

**Comment by chenjiahan** [comment]
Lazyload 是直接使用的 [vue-lazyload](https://github.com/hilongjw/vue-lazyload) 库，可以到该仓库下体温
