### ISSUE TITLE
[Bug Report] Uploader上传图片在部分设备不兼容，图片角度旋转

### ISSUE THREAD

**Issue by gch2010net** [youzan/vant#5971]
### 设备 / 浏览器
Uploader上传图片在部分设备不兼容，图片角度旋转

### Vant 版本
2.5.9

### Vue 版本
3.0.0-alpha.10

### 重现链接
<a href="https://www.51djt.com" target="_blank">https://www.51djt.com</a>

### 描述问题
Uploader上传图片在部分设备不兼容，图片角度旋转

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5804，可以在 before-read 里自行处理下
