### ISSUE TITLE
[Feature Request] van-tabbar组件fixed时,导致页面底部被遮挡

### ISSUE THREAD

**Issue by lsxm** [youzan/vant#5972]
### 这个功能解决了什么问题
使用底部标签栏时,会使页面底部的内容一起被标签栏遮挡住

### 描述您想要的解决方案
NavBar 组件也有类似问题,不过在2.5.9版本时解决了,新增placeholder属性,让fixed的外层再包一层有高度的div

### 建议的API是什么样的
:placeholder="true"

**Comment by chenjiahan** [comment]
后续会加一个

**Comment by chenjiahan** [comment]
已在 2.6.0-beta.0 版本支持

**Comment by wh469012917** [comment]
@lsxm 2.5.9 是怎么解决的，有没有例子
