### ISSUE TITLE
使用 field 和 picker 组件下划线不展示

### ISSUE THREAD

**Issue by jc840031139** [youzan/vant#5974]
![WeChatd9b4d6675dcd4a419db7090308c029be](https://user-images.githubusercontent.com/34274229/78109803-865f5880-742c-11ea-817d-0e1de0f68e13.png)
这样写在页面中调用的话 外层是div 不会自动展示下划线 有什么办法解决嘛

**Comment by chenjiahan** [comment]
目前没有特别好的方法，可以通过 van-hairline--bottom 加一条边框，或者把 Popup 放到组件外部

**Comment by jc840031139** [comment]
这个直接放到 组件上无效诶

**Comment by jc840031139** [comment]
这个是内置样式嘛

**Comment by chenjiahan** [comment]
是滴
