### ISSUE TITLE
[Bug Report] Tab标签页

### ISSUE THREAD

**Issue by jiahui336** [youzan/vant#5975]
### 设备 / 浏览器
ios 安卓

### Vant 版本
2.5.9

### Vue 版本
3.0.0-alpha.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tab" target="_blank">https://youzan.github.io/vant/#/zh-CN/tab</a>

### 描述问题
用tab标签点点击切换后，Popup弹出层的遮罩层不显示，只有点击切换后在回到当前就会出现此问题

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by jiahui336** [comment]
codesandbox  是啥

**Comment by jiahui336** [comment]
就是用tab标签页 里面加了popup弹出层，来回切换之后在点击显示弹出层，然后遮罩层不显示

**Comment by chenjiahan** [comment]
用这个网站创建一个复现问题的链接：https://codesandbox.io/s/m5v3f

**Comment by jiahui336** [comment]
重现链接：https://8qvr6.csb.app/

**Comment by chenjiahan** [comment]
两个 Popup 不能绑定同一个 show 变量，建议用两个变量控制

**Comment by jiahui336** [comment]
我感觉是循环的原因啊，tab要是用循环就会出现这样的问题，
