### ISSUE TITLE
vue开发中报t._g is not a function，是版本原因？

### ISSUE THREAD

**Issue by NBAUser** [youzan/vant#598]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
@NBAUser 没遇到过这个问题，建议升级版本再试
