### ISSUE TITLE
使用vant-cli构建build组件库之后，之前yarn dev的站点去哪里了？

### ISSUE THREAD

**Issue by JinJieTan** [youzan/vant#5981]
如题！

由于文档上没有找到，我使用yarn build 之后，这个站点应该如何访问呢 

![image](https://user-images.githubusercontent.com/47209029/78207453-4e135500-74d4-11ea-8e1d-98c85b077697.png)

**Comment by JinJieTan** [comment]
就是yarn build后，如何访问yarn dev的那个站点

**Comment by chenjiahan** [comment]
build 出来的是静态文件，在 site 目录下，可以部署到服务器或者 Github Pages 上面
