### ISSUE TITLE
表单选择器不是从网页最底端弹出选项

### ISSUE THREAD

**Issue by ymmagic** [youzan/vant#5982]
![image](https://user-images.githubusercontent.com/16641312/78217317-642e0f00-74ee-11ea-902a-405b3b009092.png)

![image](https://user-images.githubusercontent.com/16641312/78217339-6f813a80-74ee-11ea-98df-990923daf42c.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
