### ISSUE TITLE
sku规格选择的问题

### ISSUE THREAD

**Issue by kuangxianfeng** [youzan/vant#5983]
在选择规格时侯 如果组合选择没有选择完 点击加入购物车或者是购买就会弹出库存不足的情况，我看了api里面没有看到相关的设置，是不是我看漏了什么？
比如有颜色（黄色、黑色） 尺寸（S、M），只选择了黄色 尺寸不选择 点击购物车会弹出库存不足

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by y1324** [comment]
@kuangxianfeng 请问解决了吗？

**Comment by y1324** [comment]
> @kuangxianfeng 请问解决了吗？

提示库存不足时因为sku属性下的stock_num为0引起的。
