### ISSUE TITLE
[Bug Report] 没法让Field 输入框不弹出输入法

### ISSUE THREAD

**Issue by Arainersky** [youzan/vant#5984]
### 设备 / 浏览器
移动端设备/安卓/苹果

### Vant 版本
2.6.0-beta.0

### Vue 版本
3.0.0-alpha.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/field" target="_blank">https://youzan.github.io/vant/#/zh-CN/field</a>

### 描述问题
没有任何办法能让输入框不弹出系统自带的输入法，能否添加属性，控制一下，让他不弹出输入法

**Comment by chenjiahan** [comment]
只有 readonly 和 disabled 能阻止弹出系统输入法，木有其他方法
