### ISSUE TITLE
[Bug Report] sku规格选择问题

### ISSUE THREAD

**Issue by kuangxianfeng** [youzan/vant#5985]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.5.2

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/sku" target="_blank">https://youzan.github.io/vant/#/zh-CN/sku</a>

### 描述问题
颜色和尺寸两个规格组合 如果只选颜色 点击加入购物车会弹出库存不足，并没有进入加入购物车的回调，可能是我看api不够仔细，还望告知。

**Comment by y1324** [comment]
请问解决了吗？我是不选规格，点添加购买会提示

**Comment by y1324** [comment]
> 请问解决了吗？我是不选规格，点添加购买会提示

提示库存不足时因为sku属性下的stock_num为0引起的。
