### ISSUE TITLE
[Bug Report] pull-refresh v-model绑定问题

### ISSUE THREAD

**Issue by nicholasyum** [youzan/vant#5986]
### 设备 / 浏览器
chrome

### Vant 版本
2.5.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/pull-refresh" target="_blank">https://youzan.github.io/vant/#/zh-CN/pull-refresh</a>

### 描述问题
pull-refresh 页面mounted 时候 设置v-model=true "加载中"的动画效果不出来
现在想让页面加载数据的效果一致，第一次加载数据的时候也想让pull-refresh的 loading 动画出现 不知道支持这种方式吗？

**Comment by chenjiahan** [comment]
目前不支持这种方式呢，近期会评估下

**Comment by chenjiahan** [comment]
暂时不会支持这种使用方式，可以通过 loading 组件去实现
