### ISSUE TITLE
picker组件在h5中滑不动

### ISSUE THREAD

**Issue by liugang1988** [youzan/vant#5987]
设备 / 浏览器
谷歌浏览器

Vant 版本
2.5.3

Vue 版本
3.0.5

重现链接
https://youzan.github.io/vant/#/zh-CN/picker

描述问题
在移动端滑动会出现卡顿，滑不动，非常不顺畅，如图所示，一次只能移动十几个像素
![image](https://user-images.githubusercontent.com/11206849/78317125-06540280-7594-11ea-92e6-70328bfd8651.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
