### ISSUE TITLE
[Feature Request] 建议swiper强化下

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#5988]
### 这个功能解决了什么问题
移动端经常出现的轮播图，中间大两边小，有点类似3d效果

### 描述您想要的解决方案
移动端经常出现的轮播图，中间大两边小，有点类似3d效果

### 建议的API是什么样的
移动端经常出现的轮播图，中间大两边小，有点类似3d效果

**Comment by chenjiahan** [comment]
暂时没有计划支持喔，如果需要比较复杂的轮播效果，建议使用专门的 Swiper 库，比如 vue-awesome-swiper
