### ISSUE TITLE
van-area是否有更新，怎么突然渲染不了数据了

### ISSUE THREAD

**Issue by lisun0459** [youzan/vant#5993]
### 设备 / 浏览器
所有

### Vant 版本
1.6.20

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/area" target="_blank">https://youzan.github.io/vant/#/zh-CN/area</a>

### 描述问题
组件使用
并未动到项目，也没有更新area.js
<van-area    :area-list="areaList"  @confirm="selectedCity" />

json是官方提供的area.js

**Comment by chenjiahan** [comment]
最近木有更新呢，麻烦提供一下 codesandbox 复现链接

**Comment by 343195246** [comment]
我也遇到了同样的问题,没动项目,并且已经拿到了area.js的数据,但是无法渲染列表的问题
