### ISSUE TITLE
[Feature Request] CSS Modules?

### ISSUE THREAD

**Issue by boreek** [youzan/vant#5997]
### What problem does this feature solve
CSS modules doesn't work

### Describe the solution you'd like
Update `webpack.base.ts`

### What does the proposed API look like
https://vue-loader.vuejs.org/guide/css-modules.html#opt-in-usage

**Comment by chenjiahan** [comment]
Vant Cli use @vue/component-compiler-utils rather than webpack to compile SFC in production mode, updating `webpack.base.ts` is not enough to support CSS modules.

AndI think using CSS modules in UI library is not a good practice, it will make it difficult for users to customize the style.

**Comment by boreek** [comment]
Okay, how can I use modules in locally project?

1. If I override module rule, then a get error on console
```
Failed to compile with 1 errors  
error  in ./node_modules/@boreek/mf-icons/dist/mf-icons.css
Syntax Error: SyntaxError
(1:1) Unknown word
> 1 | var api = require("!../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js");
```

2. In my commit a make module loader is optional. (This variant work for me)

3. Why css-modules is bad practice?

4. Can you make a config path for `css-loader`. Like it https://github.com/youzan/vant/blob/dev/packages/vant-cli/src/config/webpack.base.ts#L25 ?

```js
loader: 'css-loader',
    options: {
      config: {
        path: CSS_CONFIG_FILE,
      },
    },
```

**Comment by chenjiahan** [comment]
> how can I use modules in locally project?

If you want to use components in your project, you must build and publish them (in production mode)

> why css-modules is bad practice?

it will make it difficult for UI component users to customize the style.

> Can you make a config path for css-loader

Can't.
