### ISSUE TITLE
[Bug Report] form表单验证不通过（输入框内放置上传文件组件）

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#5999]
### 设备 / 浏览器
所有浏览器

### Vant 版本
2.5.9

### Vue 版本
2.5.20

### 重现链接
<a href="https://codesandbox.io/s/vue-template-l2rhn" target="_blank">https://codesandbox.io/s/vue-template-l2rhn</a>

### 描述问题
顶部和最下面两个上传图片行，field增加必须验证，表单绑定值为图片base64，按照require验证，绑定变量长度存在就应该为true，但是结果为无论绑定值是否存在都不通过验证

**Comment by cangyu1993** [comment]
我查到了原因，我用solt='input'让输入框失去原有属性，而插槽内是文件上传，我不需要文件上传预览，但是放置在表单内，表单验证会找插槽内的绑定数据，我不写上传文件的绑定数据验证就找不到，所以怎么也通过不了验证，但是我写上绑定数据又出现了文件预览列表，这不是我想要的

**Comment by cangyu1993** [comment]
![image](https://user-images.githubusercontent.com/42930030/78557337-2b21d180-7843-11ea-9967-b43ad8197fb3.png)
发现formValue拿不到值，可都是solt插槽另一个picker就能验证，这个就验证不通过，拿不到值

**Comment by cangyu1993** [comment]
发现表单项无论有没有值，computed的formValue拿到的都是一个空数组，其他表单项没有值之前都是空，唯独这几个上传图片的都是空数组，想知道这个formValue是怎么拿的值

**Comment by chenjiahan** [comment]
为啥不按照示例写呢，v-model 应该绑定在 Uploader 上

**Comment by cangyu1993** [comment]
v-model 应该绑定在 Uploader 上就是图片组预览，我不需要预览功能的

**Comment by chenjiahan** [comment]
把 preview-image 设置为 false

**Comment by cangyu1993** [comment]
同样是绑定在field上，picker的验证就是正常的，这个让我很迷惑

**Comment by chenjiahan** [comment]
Picker 的值是你在 confirm 的时候设置到 Field 上的

**Comment by cangyu1993** [comment]
![image](https://user-images.githubusercontent.com/42930030/78623149-97d7b300-78b9-11ea-9a49-3670717e7d05.png)
    max-count="1"的时候上传成功后就把上传隐藏了，我增加了这个上限虽然上传显示了，但数据push到fileList里了，验证算是完成了，我自己去修改数组吧，谢谢作者
