### ISSUE TITLE
vant 升级到2.5后，引用form组件，$attrs is readonly

### ISSUE THREAD

**Issue by nixinxin0518** [youzan/vant#6002]
Vant 版本
2.5.0

Vue 版本
2.6.10

描述问题
vant 升级后form组件出现$attrs is readonly
![issue](https://user-images.githubusercontent.com/42535103/78621185-9c4d9d00-78b4-11ea-8021-6be498efd5b5.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
