### ISSUE TITLE
Ratio一定要配合Ratio Group使用吗？我只有一个Ratio组件的时候无法切换状态。

### ISSUE THREAD

**Issue by huyaxiong** [youzan/vant#6005]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
是的，如果想单个切换，可以使用 Checkbox
