### ISSUE TITLE
[Feature Request] grid 组件的 icon 希望能支持设置图标颜色

### ISSUE THREAD

**Issue by jacky8466** [youzan/vant#6006]
### 这个功能解决了什么问题
可以让grid使用的图标个性化，而不是通过使用图片的方式展现不同的色彩

### 描述您想要的解决方案
新增 icon-style 属性，让用户自定义grid的icon

### 建议的API是什么样的
<van-grid-item icon="photo-o" icon-style="类名或者直接写样式属性" text="文字" />

**Comment by chenjiahan** [comment]
后续会加个属性

**Comment by sylvaner-h** [comment]
用CSS不久好了么
```css
.van-icon {
  color: #121212;
}
```

**Comment by chenjiahan** [comment]
嗯，直接 css 覆盖很方便。。还是不加属性了
