### ISSUE TITLE
您好 vant的组件可以定制吗

### ISSUE THREAD

**Issue by heliang0915** [youzan/vant#6007]
比如我只是用vant的button 在资源打包是不想吧整个vant库打包进来

**Comment by chenjiahan** [comment]
参见文档的按需引入章节：https://youzan.github.io/vant/#/zh-CN/quickstart#fang-shi-yi.-zi-dong-an-xu-yin-ru-zu-jian-tui-jian

**Comment by heliang0915** [comment]
![image](https://user-images.githubusercontent.com/15813705/78642922-0cc0e200-78e6-11ea-9493-7a6794d791ac.png)
但是我发现我按需引入之后库文件依然很大

**Comment by chenjiahan** [comment]
可以检查下你的 babel 配置有没有生效
