### ISSUE TITLE
在路由发生变化的时候，如何高亮 Tabbar?

### ISSUE THREAD

**Issue by wh469012917** [youzan/vant#6008]
如题，比如有这样的一个 Tabbar ：
```
<van-tabbar route>
  <van-tabbar-item to="/home" icon="home-o">
    标签1
  </van-tabbar-item>
  <van-tabbar-item to="/search" icon="search">
    标签2
  </van-tabbar-item>
</van-tabbar>
```
当我在 `/home` 的时候会高亮 标签1，那么在 `/home/foo` 这个路由(这个时候已经没有任何高亮)，该如何高亮 标签1？

查看了源码发现，高亮的判断是通过路由的 path 或者 name 来判断的，可是一个 van-tabbar-item 只能设置一个 to 或者 name 属性，但是该标签下会有无数个的页面，那么该怎么处理这个问题？

如果把该标签下的路由名称都设定为一样，当然就可以，但是这样会有一个警告

**Comment by chenjiahan** [comment]
目前路由匹配不支持这种多级路由的情况，建议用 name 属性进行匹配
