### ISSUE TITLE
[Bug Report] uploader组件在ios特定手机系统拍照上传会造成页面刷新

### ISSUE THREAD

**Issue by 12baby** [youzan/vant#6009]
### 设备 / 浏览器
iOS 12.4.6 微信浏览器

### Vant 版本
2.5.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
我们的h5页面用了uploader组件，还在测试阶段，不方便放链接，特地用官网的demo测试了一下，是有手机拍照上传页面刷新的问题，重现链接用了官网的demo，用ios12.4.6 （目前就这个ios12.4.6系统有问题）微信打开 在文件预览 一直用手机拍照上传 会复现页面刷新

**Comment by chenjiahan** [comment]
是反复上传才会出现吗？ 可以用原生的 input type="file" 试下，是不是也有同样的问题

**Comment by 12baby** [comment]
不一定是反复上传，有时候是，只要选择拍照上传，会复现页面刷新。刚试了原生的input，也有这个问题🤭


| |
武嘉琪
|
|
邮箱：w524105035@163.com
|

签名由 网易邮箱大师 定制

在2020年04月07日 17:32，neverland 写道：

是反复上传才会出现吗？ 可以用原生的 input type="file" 试下，是不是也有同样的问题

**Comment by chenjiahan** [comment]
> 刚试了原生的input，也有这个问题🤭

那就是浏览器内核问题咯，暂时无解，可以去网上找找看有没有兼容的方法

**Comment by ShulicTian** [comment]
这个问题我碰到过，安卓和ios都会出现这个情况，初步判断是微信内置浏览器的内存管理机制导致的，手机后台应用过多时会导致运存占用过大，达到一个阈值后会触发微信的这个机制，我目前的解决方案是让用户清理后台运行的应用释放运存，经过多次的试验，确实有效
