### ISSUE TITLE
[Bug Report] how to modify the height of title in vant-tab？

### ISSUE THREAD

**Issue by uniquexiaobai** [youzan/vant#6011]
### 设备 / 浏览器
所有设备

### Vant 版本
2.6.0-beta.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/youzan/vant/blob/v2.6.0-beta.0/src/tabs/index.less#L132" target="_blank">https://github.com/youzan/vant/blob/v2.6.0-beta.0/src/tabs/index.less#L132</a>

### 描述问题
why the class 'van-tabs__wrap' has a fixed height, I have to modify the CSS to overwrite it. Is there a better or flexible way to customize it?

**Comment by chenjiahan** [comment]
It is recommended to use css to overwrite the origin style, and there is currently no other way

**Comment by BigBen3918** [comment]
I have same issue. But I can't use global css because I used vant-tab in many place...
Please help me.
