### ISSUE TITLE
[Bug Report] vant文档与代码不符

### ISSUE THREAD

**Issue by Wster11** [youzan/vant#6012]
### 设备 / 浏览器
chorme

### Vant 版本
2.5.9

### Vue 版本
2.6.7

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-3xrn8" target="_blank">https://codesandbox.io/s/vant-issue-moban-3xrn8</a>

### 描述问题
1. 官方描述 form :show-error 可以控制是否显示输入框本身的校验提示
    但是在2.5.9的 vant版本中 并没有该属性。

**Comment by captain-c** [comment]
https://youzan.github.io/vant/#/zh-CN/changelog   v2.6.0-beta.0

**Comment by chenjiahan** [comment]
版本号标错了，后续会修正下
