### ISSUE TITLE
[Bug Report] 按需加载组件报错

### ISSUE THREAD

**Issue by cqupt-yifanwu** [youzan/vant#6014]
### 设备 / 浏览器
谷歌

### Vant 版本
2.5.9

### Vue 版本
2.6.2

### 重现链接
<a href="http://mas.zyebank.net:8762/mini/index/" target="_blank">http://mas.zyebank.net:8762/mini/index/</a>

### 描述问题
按需引入的方式使用vant，但是项目本身存在external vue，导致访问时报错

项目的external
```
  {
    'vue': 'zyThirdVendors.vue',
    'vuex': 'zyThirdVendors.Vuex',
    'vue-router': 'zyThirdVendors.Router',
    // 'mint-ui': 'zyThirdVendors.MintUi',
    'vconsole': 'zyThirdVendors.vconsole',
    'config': 'zyThirdVendors.config',
    'native': 'zyThirdVendors.native',
    'utils': 'zyThirdVendors.utils'
  },
  configExtrenal
```
项目将公共部分external出去，打成公共包，包括vue在内，这时访问页面报错如下

![image](https://user-images.githubusercontent.com/13469100/78740710-0e43e600-798a-11ea-9dea-885ce9fdd083.png)

**Comment by chenjiahan** [comment]
这个是项目本身配置的问题了，只要保证组件库能访问到 Vue 对象就可以

可以试试这样写：

```js
externals: {
  vue: {
    root: 'Vue',
    commonjs: 'vue',
    commonjs2: 'vue',
    amd: 'vue',
  },
},
```
