### ISSUE TITLE
[Bug Report] Toast,Dialog冲突，Toast未关闭时，弹出Dialog，Dialog中的按钮无法点击

### ISSUE THREAD

**Issue by wang4978** [youzan/vant#6018]
### 设备 / 浏览器
chrome

### Vant 版本
2.5.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsbin.com/dewowey/edit?html,css,js,output" target="_blank">https://jsbin.com/dewowey/edit?html,css,js,output</a>

### 描述问题
Toast,Dialog冲突，Toast未关闭时，弹出Dialog，Dialog中的按钮点击无效.需要先执行Toast.clear()才能使Dialog的按钮点击有效

Toast({
        message: error_message,
        overlay: true,
        icon: 'close'
      }); 

Dialog.alert({
        title: '温馨提示',
        message: '提交错误',
      });

**Comment by chenjiahan** [comment]
Toast 的 overlay 选项会显示一个遮罩层，并屏蔽点击事件，把 overlay 去掉就可以了
