### ISSUE TITLE
QA: questions for your builds-tools 

### ISSUE THREAD

**Issue by tenjj** [youzan/vant#602]
Thank you for your great ui, it save me time, i am glad to use this, then i read your building tools, i am a newer to vue plugins, so i am confused above this:

<img width="542" alt="2018-02-02 12 46 07" src="https://user-images.githubusercontent.com/8084634/35716959-13c19ca8-0817-11e8-977b-cdab225e2f8b.png">

what is the purpose of using  

> **sfc.install = sfc.install || install;**

need for your answer, tk

**Comment by chenjiahan** [comment]
The install method allows user to register component by Vue.use
```js
import { Button } from 'vant';
Vue.use(Button);
```

Official guide: https://vuejs.org/v2/api/#Vue-use

**Comment by tenjj** [comment]
Thank you for your reply !
but why can i directly use Vue.component('button', Button)?, what is the difference...
and i read from utils/install , show 
`Vue.component(this.name, this);`

i mean why directly use this, Instead use some function call do the somethings?

**Comment by chenjiahan** [comment]
Because `Vue.use(Button)` is simpler than `Vue.component(Button.name, Button)` ^_^

And vant will not register component globally by default, unless you import all components.

**Comment by tenjj** [comment]
if i only import some what i want

do like this ?

```
import { Button, Popup, Search, .....} from 'vant'

Vue.use(Button)
Vue.use(Popup)
Vue.use(Search)
....
....
```

in main.js ?

**Comment by chenjiahan** [comment]
yes

**Comment by tenjj** [comment]
thk
