### ISSUE TITLE
[Bug Report] Dialog自定义组件中，before-close 失效

### ISSUE THREAD

**Issue by fudaoji** [youzan/vant#6020]
### 设备 / 浏览器
apple6  ios10 / 微信浏览器

### Vant 版本
2.5.9

### Vue 版本
2.6.11

### 重现链接
抱歉，因为是本地开发环境，无法提供链接。

### 描述问题
确认过代码没有报错，点击确定后，弹框直接关闭，没有走到自定义的beforeClose中。代码如下

template中：
`
<van-dialog
                v-model="show"
                title="修改姓名"
                show-cancel-button
                class="set-dialog"
                @confirm="onClickSaveName"
                @before-close="beforeClose"
        >
            <van-field clearable v-model="username" placeholder="请输入用户名" />
        </van-dialog>
`

js中：
`beforeClose(action, done){
                console.log(action);
                done(false);
            }`

**Comment by chenjiahan** [comment]
before-close 是一个 prop，不是 event，用冒号而不是 @
