### ISSUE TITLE
组件按需加载

### ISSUE THREAD

**Issue by magicstf** [youzan/vant#6022]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

import { Dialog } from 'vant';
// import { RadioGroup } from 'vant';
// import { Radio } from 'vant';
Vue.use(Dialog);
// Vue.use(Radio);
// Vue.use(RadioGroup);

如上图， 引入单个组件时没有问题，可以正常使用，引入多个组件时，项目就报错无法运行了

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
