### ISSUE TITLE
[Bug Report] van-cell 组件触发单击时 Uncaught TypeError: Cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by github-linong** [youzan/vant#6024]
### 设备 / 浏览器
chrome 77.0.3865.90（正式版本） （64 位）

### Vant 版本
2.6.0

### Vue 版本
2.2.0

### 重现链接
<a href="https://www.lilnong.top/static/html/vant@2.6-vue@2.2-vantCell-click-bug.html" target="_blank">https://www.lilnong.top/static/html/vant@2.6-vue@2.2-vantCell-click-bug.html</a>

### 描述问题
Uncaught TypeError: Cannot read property 'click' of undefined
Vue.js v2.2.0

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by github-linong** [comment]
http://jsrun.net/iDfKp/edit

试一下。如果不行，我再放到codepen上面。

**Comment by chenjiahan** [comment]
Vant 已经不支持 Vue 2.2 版本了，请使用 Vue 2.5 以上版本
