### ISSUE TITLE
日历组件

### ISSUE THREAD

**Issue by zhqg** [youzan/vant#6025]
### 设备 / 浏览器
所有平台

### Vant 版本
2.6.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://lingxi.applinzi.com/attrec/index.php" target="_blank">https://lingxi.applinzi.com/attrec/index.php</a>

### 描述问题
如今天是4月10日，一般来说日历初始渲染时应定位到今天所在的月份，但将日历组件的 min-date 设置为 1月1日，max-date 设置为4月30日，日历组件默认显示到了1月份，不太符合用户操作习惯，能否将当天所在当月作为默认显示月份，而不是显示最小日期的月份。谢谢！

**Comment by chenjiahan** [comment]
日历默认会定位到 default-date 对应的日期，跟当前日期无关

**Comment by zhqg** [comment]
我指的不是 default-date 的定位，而是定义了min-date后，显示区域默认显示到了 min-date 的月份

**Comment by zhqg** [comment]
请看上面的重现链接

**Comment by chenjiahan** [comment]
我看了。你设置了错误的 default-date

**Comment by chenjiahan** [comment]
默认值确实有问题，下个版本修复

**Comment by aetherwu** [comment]
我设置了
:default-date="currentDate"
使得日历可以默认选中今天。
但因为 min-date 在三个月以前，日历打开的时候，现实的日历月份没有定位到今天。
我是下载安装的，不知道怎么找版本号，不过安装文件夹的日期显示 vant 2020-7-25.
