### ISSUE TITLE
【BUG】Dialog 不支持按需引入 同时不支持组件调用

### ISSUE THREAD

**Issue by JdesEva** [youzan/vant#6026]
版本 v2.6.0

实测 Dialog 只能全局安装之后使用 this.$dialog.alert(option)方法调用 不支持组件内调用
同时 Dialog 接收props 并没有 value 也没使用 modal 意味着它并不支持 v-model !!!!!!!
![image](https://user-images.githubusercontent.com/37232561/78981394-6cbbc080-7b52-11ea-83a3-fb2cde354646.png)

如果需要展示内容 直接 使用如下方法
![image](https://user-images.githubusercontent.com/37232561/78981493-9bd23200-7b52-11ea-8f66-567e7498ff60.png)

message填入HTML字符串 会自动转义成DOM

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by IOLOII** [comment]
v-model配置了就是不显示
