### ISSUE TITLE
[Bug Report] Overlay内的block在移动端无法滚动

### ISSUE THREAD

**Issue by ssshooter** [youzan/vant#6032]
### 设备 / 浏览器
移动浏览器

### Vant 版本
2.6.0

### Vue 版本
3.0.0-alpha.12

### 重现链接
<a href="https://bxwcz.csb.app/" target="_blank">https://bxwcz.csb.app/</a>

### 描述问题
Overlay内的block在移动端无法滚动，PC端正常

**Comment by chenjiahan** [comment]
为了锁定滚动，Overlay 默认加了 @touchmove.prevent 阻止冒泡，所以会有这个问题

后续会考虑加个配置

**Comment by ssshooter** [comment]
明白

**Comment by chenjiahan** [comment]
已在 2.6.2 版本新增 lock-scroll 属性，设置为 false 后即可避免此问题

另外对于复现链接里的场景，建议使用 Popup 组件

**Comment by yiyou1992** [comment]
我用的是popup组件，内容里的元素是动态生成的，Lock-scroll设置了false，但是当内容滚动到底部或顶部时继续滚动的话会滚动穿透，导致overlay遮盖层下面的元素相应滚动。这个问题有没有什么办法解决

**Comment by uniquexiaobai** [comment]
@yiyou1992 手动 body-scroll-lock

**Comment by anming-john** [comment]
> @yiyou1992 手动 body-scroll-lock

这个是怎么配置， 能具体说下吗
