### ISSUE TITLE
编辑地址按钮无法点击

### ISSUE THREAD

**Issue by liuskr** [youzan/vant#6034]
<template>
  <div class="addresedit">
    <Header title="地址编辑"></Header>
    <van-address-edit
      :area-columns-placeholder="['请选择', '请选择', '请选择']"
      :areaList="areaList"
      @delete="onDelete"
      @save="asss"
      show-delete
      show-set-default
    />
  </div>

1. 

</template>

<script>
import { AddressEdit, Toast } from 'vant'
import areaList from './area.json'
import Header from '../../components/header'
export default {
  data() {
    return {
      areaList,
      searchResult: []
    }
  },
  methods: {
    onSave(content) {
      console.log(content)
      console.log('231321')
    },
}
我点击onsava按钮没有反应

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
