### ISSUE TITLE
[Bug Report] ImagePreview 图片预览问题（第一次能预览，反复预览关闭几次操作后不能再预览）

### ISSUE THREAD

**Issue by yak-ok** [youzan/vant#6036]
### 设备 / 浏览器
iphone safiri / 微信

### Vant 版本
2.6.0

### Vue 版本
3.0.0-alpha.12

### 重现链接
<a href="http://47.104.193.233/mobile/localStore/store" target="_blank">http://47.104.193.233/mobile/localStore/store</a>

### 描述问题
每开打页面时，图片可预览
返回点击图片预览--关闭，多操作几次，图片不能预览。
或点击 编辑 不操作 返回来，再点预览，图片预览不了。
在编辑页面的Upload组件也有同样的问题， PC的Chrome也能重现 ，但机率小一点。

**Comment by chenjiahan** [comment]
官方示例能复现吗

**Comment by yak-ok** [comment]
> 官方示例能复现吗

可以的

**Comment by chenjiahan** [comment]
复现了✌️ 原因是在隐藏的状态下触发了浏览器的 resize 事件，导致轮播组件计算宽度错误，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.6.2 版本修复
