### ISSUE TITLE
Cell 组件，title 属性传递数字 0时，不显示内容

### ISSUE THREAD

**Issue by zaxlct** [youzan/vant#604]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**
titile 传递数字 0 ，也可以展示为 0

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
0.12.6

**Comment by chenjiahan** [comment]
@zaxlct title 请使用 String 格式
