### ISSUE TITLE
请问下，怎么才能动态的绑定van-cell的value的color属性，我想动态的改变字体颜色

### ISSUE THREAD

**Issue by jaycethanks** [youzan/vant#6040]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by sylvaner-h** [comment]
使用 `#default`；
e.g. https://codesandbox.io/s/diy-van-cell-label-92510?file=/src/App.vue

**Comment by jaycethanks** [comment]
> 使用 `#default`；
> e.g. https://codesandbox.io/s/diy-van-cell-label-92510?file=/src/App.vue

非常感谢你！！！！！

**Comment by jaycethanks** [comment]
## 感谢指导，后来我这样写的，完美！希望给有需要的朋友参考
```vue
<van-cell class="status" title="状态" size="large" >
    <template>
	<p style="margin:0" :style={color:bindcolor}>{{value}}</p>
    </template>
</van-cell>
```
```vue
export default {
    data(){
        return{
            bindcolor:"#f40",
            value:"这是绑定值"
        }
    }
}
```
![image](https://user-images.githubusercontent.com/44388103/80792014-f1d04d80-8bc5-11ea-87f1-65db35bf0899.png)
