### ISSUE TITLE
[Feature Request] Empty中的“network”图片地址建议改为DataURL

### ISSUE THREAD

**Issue by yiyan0** [youzan/vant#6041]
### 这个功能解决了什么问题
在断网情况下无法加载图片

### 描述您想要的解决方案
将“network”图片地址改为DataURL

### 建议的API是什么样的
将“network”图片地址改为DataURL

**Comment by chenjiahan** [comment]
可以的，后续会把这个图片做成内置的 SVG or dataURI

**Comment by chenjiahan** [comment]
已在 2.6.2 版本支持

**Comment by sbyps** [comment]
@chenjiahan default error等类型的图片也不应该用vant cdn的网络图片，应该也和network一样
