### ISSUE TITLE
2.6.0bug，轮播图在iphone上图片高度变成了0，不展示，pc上模拟正常

### ISSUE THREAD

**Issue by xni220** [youzan/vant#6044]
2.6.0bug，轮播图在iphone上图片高度变成了0，不展示，pc上模拟正常

**Comment by xni220** [comment]
> 2.6.0bug，轮播图在iphone上图片高度变成了0，不展示，pc上模拟正常

以下是微信开发者工具中模拟生成的代码（不正常）
<div class="van-swipe">
    <div class="van-swipe__track" style="**width: 0px;** transition-duration: 500ms; transform: translateX(0px);">
        <div class="van-swipe-item" style="**width: 0px;**"><img src="/upfile/3494/20191109/462fed43c1856cb12990688486040509.jpg"></div>
        <div class="van-swipe-item" style="**width: 0px;**"><img src="/upfile/3494/20191109/462fed43c1856cb12990688486040509.jpg"></div>
    </div>
    <div class="van-swipe__indicators"><i class="van-swipe__indicator van-swipe__indicator--active"></i><i class="van-swipe__indicator"></i></div>
</div>

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by xfFelix** [comment]
我的实在安卓上会这样，更新版本，我更新到了2.9.3就行了
