### ISSUE TITLE
[Bug Report] Image 组件冲突

### ISSUE THREAD

**Issue by biggerbird** [youzan/vant#6047]
### 设备 / 浏览器
所有

### Vant 版本
2.6.1

### Vue 版本
3.0.0-alpha.12

### 重现链接
<a href="https://codepen.io/biggerbird/pen/jObbrKK" target="_blank">https://codepen.io/biggerbird/pen/jObbrKK</a>

### 描述问题
引入Image组件后，无法通过new Image()创建img对象 ,TypeError: vant__WEBPACK_IMPORTED_MODULE_7__.Image is not a constructor

**Comment by chenjiahan** [comment]
可以这样写：

```js
import { Image as VanImage } from 'vant';
```

后续会加到文档里

**Comment by BoBoooooo** [comment]
太难了，卡了10分钟原来是重名了
