### ISSUE TITLE
[Bug Report] 键盘响应丢失

### ISSUE THREAD

**Issue by Jackbar** [youzan/vant#6052]
### 设备 / 浏览器
ios 13.4.1 微信

### Vant 版本
2.6.1

### Vue 版本
3.0.0-alpha.12

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/number-keyboard" target="_blank">https://youzan.github.io/vant/#/zh-CN/number-keyboard</a>

### 描述问题
快速输入存在用户输入丢失的问题

**Comment by chenjiahan** [comment]
一般是 UIWebView 导致的，参见 https://github.com/youzan/vant/issues/4112

**Comment by PEDx** [comment]
ios 13.4.1   safari 浏览器 touchstart 会出现延迟现象, 导致输入丢失，经过测试 iOS 12.x 版本不会
