### ISSUE TITLE
[Feature Request]  增加一个 组件路由配置，可自定义配置目录

### ISSUE THREAD

**Issue by ZzNb0813** [youzan/vant#6054]
现在 所有的路由组件 全部在src 目录 同层级下，不好区分 ，希望增加 目录配置

**Comment by chenjiahan** [comment]
源代码目录的路径可以通过 build.srcDir 进行配置

不同层级的配置暂时没有计划支持，因为不同层级会导致无法使用 babel-plugin-import 按需加载
