### ISSUE TITLE
[Feature Request] vant 转 rem 报错

### ISSUE THREAD

**Issue by luo963827954** [youzan/vant#6057]
### 这个功能解决了什么问题
vant转Rem 报错，

=====================  报错信息

ERROR in ./node_modules/vant/lib/index.css (./node_modules/css-loader!./node_modules/postcss-loader/src??ref--5-2!./node_modules/style-loader!./node_modules/css-loader!./node_modules/postcss-loader/src!./node_modules/vant/lib/index.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(2:1) Unknown word

  1 | 
> 2 | var content = require("!!../../css-loader/index.js!../../postcss-loader/src/index.js!./index.css");

============================   webpack 配置 

{
	test: /\.css$/,
             use: ['style-loader', 'css-loader', 'postcss-loader'],
},

=============================    postcss.config.js  配置

module.exports = {
  plugins: {
    'autoprefixer': {
      browsers: ['Android >= 4.0', 'iOS >= 7',"> 0.01%"]
    },
    'postcss-pxtorem': {
      rootValue: 37.5,
      propList: ['*']
    }  
  }
}
 

### 描述您想要的解决方案
请教各位大佬问题如何解决

### 建议的API是什么样的
包版本

"postcss": "^7.0.18",
 "postcss-pxtorem": "^4.0.1",

**Comment by chenjiahan** [comment]
从上面的配置里看不出有效信息，建议你参考示例进行配置：https://github.com/youzan/vant-demo/tree/master/vant/rem
