### ISSUE TITLE
[Feature Request] form表单增加重置清空表单功能

### ISSUE THREAD

**Issue by pxyyyy** [youzan/vant#6058]
### 这个功能解决了什么问题
实现重置功能

### 描述您想要的解决方案
新增通过ref获取到的方法 可以重置清空表单内容

### 建议的API是什么样的
this.$refs.****.resetFields()

**Comment by chenjiahan** [comment]
现在 Form 里的 Field 都是受控组件，没有 default-value 的概念，所以目前不会提供 resetFields 方法哈

**Comment by li308870559** [comment]
所以还是得一个一个清除吗？

**Comment by JunmeiChen** [comment]
我是通过更新 formKey 的值来实现清空效果的
`
<van-form  :key="formKey">

 </van-form>
`

**Comment by JunmeiChen** [comment]
我是通过更新 formKey 的值来实现清空效果的
`html
  <van-form  :key="formKey">
  
  </van-form>
`

**Comment by JunmeiChen** [comment]
我是通过更新 formKey 的值来达到清空效果的

```
<van-form :key="formKey">

</van-form>
```
