### ISSUE TITLE
SwipeCell 滑动单元格显示异常

### ISSUE THREAD

**Issue by maomi20150102** [youzan/vant#6059]
直接在一个空白div里面添加的滑动单元格基础用法的示例代码，左右两边按钮没有正常显示。
1、代码
![1](https://user-images.githubusercontent.com/15665502/79405392-db6fa280-7fc6-11ea-9f4b-3e8a9434cdd7.png)
2、显示效果
![2](https://user-images.githubusercontent.com/15665502/79405396-e0345680-7fc6-11ea-81d7-9cd705980c35.png)

**Comment by maomi20150102** [comment]
如果改成下面这种写法
![1](https://user-images.githubusercontent.com/15665502/79405601-7b2d3080-7fc7-11ea-9e80-26fb1d30a5e9.png)
仍然不能正常工作
![2](https://user-images.githubusercontent.com/15665502/79405636-8aac7980-7fc7-11ea-9c5e-fbe2204f29e6.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
