### ISSUE TITLE
van-tabs 组件 @click事件 只能传入Index吗。是否可把van-tab绑定的item 传入处理。

### ISSUE THREAD

**Issue by uddsoft** [youzan/vant#606]
van-tabs 组件 @click事件 只能传入Index吗。是否可把van-tab绑定的item 传入处理。有时index传入@click事件不能满足需求。需要把van-tab的对应Id传入@click事件进行处理。

**Comment by chenjiahan** [comment]
@uddsoft 通过 index 可以定位到对应的 item 的，而且 tab 组件并不关心 item 对象
