### ISSUE TITLE
[Bug Report] 1.x升级到2.x出现的van-dialog问题

### ISSUE THREAD

**Issue by Nicholas003** [youzan/vant#6060]
### 设备 / 浏览器
全部

### Vant 版本
2.6.1

### Vue 版本
3.0.0-alpha.13

### 重现链接
<a href="http://love.goodboss.club/Middle?mm_token=32261fa6ff5db008b41bf97e2071a453" target="_blank">http://love.goodboss.club/Middle?mm_token=32261fa6ff5db008b41bf97e2071a453</a>

### 描述问题
升级组件库之后，使用van-dialog组件会出现Unknown custom element: <van-dialog> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
没改过代码，这个是升级之后的问题，之前1.X是没有问题的，我手滑更新后出现了问题

**Comment by chenjiahan** [comment]
请按照 2.x 的文档注册 Dialog 组件即可
