### ISSUE TITLE
[Feature Request] 建议Uploader组件增加lazy参数,便于图片懒加载

### ISSUE THREAD

**Issue by FrontendFish** [youzan/vant#6061]
### 这个功能解决了什么问题
过多的图片导致加载慢,流量消耗大,增加懒加载来加快加载速度减少消耗

### 描述您想要的解决方案
Uploader组件增加lazy参数,在Uploader组件里的Image组件外层包裹VueLazyload组件

### 建议的API是什么样的
Uploader组件增加lazy参数

**Comment by chenjiahan** [comment]
一般来说图片都是本地上传的，没有加载问题，你的场景是展示很多服务器端的图片吗

**Comment by chenjiahan** [comment]
已在 2.6.2 版本新增 lazy-load 属性
