### ISSUE TITLE
[Bug Report] Slider组件在同时设置了vertical和bar-height会出现ui偏转

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant#6062]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.6.1

### Vue 版本
2.6.10

### 描述问题
slider组件在设置了vertical之后，如果再设置bar-height，当bar-height比较大的时候，这个组件中间的按钮没有居中显示，如下图所示：
![image](https://user-images.githubusercontent.com/23445650/79413164-c51f1200-7fd9-11ea-9972-e9b4d1d5bde4.png)

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.6.2 版本修复
