### ISSUE TITLE
[Feature Request] CheckboxGroup全选反选问题

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#6064]
### 这个功能解决了什么问题
click事件绑定值和change事件绑定值相等

### 描述您想要的解决方案
发现click事件发生后，拿到的v-model值是变化前的值，而change值变化了，也就是说两者发生后v-model的值是相互取反的值，click发生后大概40毫秒v-model的值才变化，目前是放在异步里确保绑定值是变化后的

### 建议的API是什么样的
同步click和change事件的时间差，或者能拿到相同的值

**Comment by chenjiahan** [comment]
有道理，下个版本会把 click 事件放到 v-model 变化之后，这样就能拿到准确的值了
