### ISSUE TITLE
[Bug Report] SwipeCell 滑动单元格显示异常

### ISSUE THREAD

**Issue by maomi20150102** [youzan/vant#6068]
### 设备 / 浏览器
微信浏览器

### Vant 版本
2.6.1

### Vue 版本
2.5.6

### 重现链接
<a href="https://www.xinfow.com/Test" target="_blank">https://www.xinfow.com/Test</a>

### 描述问题
滑动单元格基础用法的示例代码，左右两边按钮没有正常显示。

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-html-zhong-wu-fa-zheng-que-xuan-ran-zu-jian

**Comment by maomi20150102** [comment]
![1](https://user-images.githubusercontent.com/15665502/79536034-9ffdd280-80b1-11ea-8a1a-a68c304735e5.png)
同样的没有正常渲染

**Comment by chenjiahan** [comment]
注意 #left 是 Vue 2.6.0 以上版本支持的语法

**Comment by maomi20150102** [comment]
正常渲染了，感谢感谢！
@chenjiahan
