### ISSUE TITLE
Waterfall 跳转路由触发

### ISSUE THREAD

**Issue by GalinaGao123** [youzan/vant#607]
滚动到底部触发了waterfall以后，跳转路由还会触发一次。
不知道这个会是什么情况呢？
谢谢！

**Comment by qianzhaoy** [comment]
@GalinaGao123 

我觉得吧, 可能是你waterfall的指令上的那个组件没有滚动条, 所以 scroll 事件就绑定到了上级元素里了, 当切换路由的时候, 滚动条瞬间消失, 等于到底了, 所以就触发了.

最好就每个绑定waterfall指令的组件高度设置好, `overflow-y: scoll `设置起来.  指令在哪, 滚动条就在哪, 应该就没这个问题了. 可以检查一下你指令绑定的那个dom元素是不是设置了滚动条.

**Comment by GalinaGao123** [comment]
@qianzhaoy 你说的对。加上滚动条以后没问题了。非常感谢！
@chenjiahan 是我使用姿势不对。。。。。
