### ISSUE TITLE
Popup组件，v-model=true的时候，报Cannot set property 'zIndex' of undefined"

### ISSUE THREAD

**Issue by guyuejinshang** [youzan/vant#6070]
我是单纯的过来吐槽一下，这个问题从去年7月份就有人提了。
每次官方人员就一句“请按照格式提问”，然后就没有下文！
官方的人能不能稍微的检查一下？没有问题谁会无缘无故跑到这里来提问？如果自己随便检查一下就能解决的问题，谁会浪费这时间到这里提问然后等你们回复？

this.$el指向的是注释节点"&lt;!----&gt;"

**Comment by chenjiahan** [comment]
这个问题是同时引入多份 Vue 代码导致的，之前的 issue 中有过明确回复：https://github.com/youzan/vant/issues/5943

**Comment by wangxue** [comment]
我的情况是因为组件中另有如下代码
`import {Dialog} from "vant";`

删除上述import然后按照如下方式使用Dialog后vant-popup就可以正常弹出了
`vant.Dialog.confirm()`
