### ISSUE TITLE
[Feature Request] 建议Uploader组件增加clip参数，用于图片裁剪

### ISSUE THREAD

**Issue by heyuhua-github** [youzan/vant#6071]
### 这个功能解决了什么问题
例如用户上传头像时，需要手动裁剪图片

### 描述您想要的解决方案
Uploader组件增加clip参数

### 建议的API是什么样的
Uploader组件增加clip参数

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5035
