### ISSUE TITLE
[Feature Request] NoticeBar 能否开放 animationend 动画完成事件

### ISSUE THREAD

**Issue by yangmi0829** [youzan/vant#6072]
应用场景:
  后端往前端推送消息，前端需要把原来的text滚动完成后才修改成新的text

**Comment by chenjiahan** [comment]
会考虑加一个

**Comment by chenjiahan** [comment]
已在 2.6.2 版本新增 replay 事件

**Comment by yangmi0829** [comment]
replay 只有在第一次动画结束后会触发，
源码是第一次触发结束后，更改了动画，并且动画次数不限制，无法监听到每一次动画结束，希望添加animationiteration事件，同时触发replay&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 下午4:10
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"杨密"<yangmi0829@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] NoticeBar 能否开放 animationend 动画完成事件 (#6072)





 
已在 2.6.2 版本新增 replay 事件

**Comment by chenjiahan** [comment]
只触发一次是 bug，后续会修复下

animationiteration 和 replay 有什么区别吗

**Comment by yangmi0829** [comment]
sry，描述有误，我期望的效果就是每一次滚完的时候都emit一个事件，也就是您那边定义的replay，也就是希望动画触发animationiteration事件的时候也emit('replay')




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 上午10:18
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"杨密"<yangmi0829@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] NoticeBar 能否开放 animationend 动画完成事件 (#6072)





 
只触发一次是 bug，后续会修复下
 
animationiteration 和 replay 有什么区别吗

**Comment by chenjiahan** [comment]
animationiteration 事件浏览器支持度比较差，得找找其他方案了

**Comment by yangmi0829** [comment]
animationiteration 兼容性跟animationstart，animationend是一样的，看源码中改变动画用的就是这两个事件，个人觉得这个兼容性应该是可以接受的。如果采用其它方案，肯定会有时间误差。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 上午10:23
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"杨密"<yangmi0829@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] NoticeBar 能否开放 animationend 动画完成事件 (#6072)





 
animationiteration 事件浏览器支持度比较差，得找找其他方案了

**Comment by chenjiahan** [comment]
看起来是有兼容性问题的：https://caniuse.com/#feat=mdn-api_document_animationiteration_event

**Comment by yangmi0829** [comment]
如果考虑兼容性的话，动画会考虑换成requestAnimationFrame吗
https://caniuse.com/#search=requestAnimationFrame
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 上午10:49
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"杨密"<yangmi0829@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] NoticeBar 能否开放 animationend 动画完成事件 (#6072)





 
看起来是有兼容性问题的：https://caniuse.com/#feat=mdn-api_document_animationiteration_event

**Comment by chenjiahan** [comment]
嗯呢，需要改动画方案，不过这样改动会比较大

**Comment by yangmi0829** [comment]
2.x版本应该不会动了把，3.x有考虑改变动画实现吗。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 中午11:30
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"杨密"<yangmi0829@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] NoticeBar 能否开放 animationend 动画完成事件 (#6072)





 
嗯呢，需要改动画方案，不过这样改动会比较大

**Comment by chenjiahan** [comment]
近期会评估一下

**Comment by yangmi0829** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 中午11:54
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"杨密"<yangmi0829@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] NoticeBar 能否开放 animationend 动画完成事件 (#6072)





 
近期会评估一下

**Comment by jacky8466** [comment]
> 会考虑加一个


> 近期会评估一下

NoticeBar 能支持显示多条消息，上下滚动轮播显示吗？不要通过Swipe 轮播组件模拟

**Comment by chenjiahan** [comment]
已在 2.8.2 版本修复 replay 只能执行一次的问题，内部的动画机制由 animation 改成了 transition
