### ISSUE TITLE
[Bug Report] android部分机型van-uploader控件点击不能选择拍照

### ISSUE THREAD

**Issue by panning1990** [youzan/vant#6073]
### 设备 / 浏览器
matePro20以及Honor V10

### Vant 版本
2.6.1 或 2.4.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://ocr.hkritaikoohui.cn/pod-open/taiguhui/photo.html" target="_blank">https://ocr.hkritaikoohui.cn/pod-open/taiguhui/photo.html</a>

### 描述问题
微信小程序调用H5页面，使用van-uploader控件点击拍照时选择不到拍照选项，直接跳转到选择文件页面
重现的手机型号：matePro20以及Honor V10
手机微信版本：Version  7.0.13 最新版本

代码参照：

      <div class="upload">
          <van-uploader :after-read="afterRead" v-if="!file" ref="upload">
            <div class="photo">
              <van-icon class-prefix="iconfont iconxiangji" name="extra" />
              <p>点击拍照</p>
            </div>
          </van-uploader>
          <div class="photo" v-else @click="openPreviewFunc(false)" style="border:none">
            <div>
              <img :src="filePath" alt srcset />
            </div>
          </div>
        </div>

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/6015
