### ISSUE TITLE
[Bug Report] textarea autosize 输入光标被 Tabbar 遮挡

### ISSUE THREAD

**Issue by Rickykurt** [youzan/vant#6075]
### 设备 / 浏览器
macOS 10.15.4 | Firefox 75.0 | Chrome 80.0.3987.163

### Vant 版本
2.6.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-gbtlk?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-gbtlk?file=/src/App.vue</a>

### 描述问题
textarea autosize 输入光标被 Tabbar 遮挡
![vant](https://user-images.githubusercontent.com/1176984/79523744-73d25980-8091-11ea-9ecf-d31ad65822c8.gif)

**Comment by chenjiahan** [comment]
Textarea 是无法判断出页面上有 fixed 元素把底部遮挡住了的，通过 maxHieght 来避免这个问题

```html
<template>
  <van-field  : autosize="{ maxHeight } />
</template>

<script>
export default {
  data() {
    return {
      maxHeight: window.innerHeight - 100
    };
  };
};
</script>
```

**Comment by Rickykurt** [comment]
@chenjiahan 
不好意思呀，我这里还是有点问题，因为我这里需求要求页面上有多个textarea，使用了maxHeight效果还是不是很好，只有第一个输入框能保证 textarea的光标不被fixed元素遮挡，后面的第二个和第三个还是会被遮挡：
https://codesandbox.io/s/vant-issue-moban-gbtlk?file=/src/App.vue

希望您能给一些建议。

![vant](https://user-images.githubusercontent.com/1176984/79540835-5e722500-80bb-11ea-8758-dd4f6b15b79e.gif)

**Comment by chenjiahan** [comment]
那你得自行控制滚动条咯，比如在输入的时候把页面往上滚一些
