### ISSUE TITLE
[Feature Request] 能否让 Popup 弹出层支持动态渲染

### ISSUE THREAD

**Issue by lipengzhou** [youzan/vant#6078]
### 这个功能解决了什么问题
我有很多场景需要每次弹层显示都请求展示最新内容，但是弹层第一次完成渲染之后就是切换显示和隐藏了，我只能通过 v-if 等方式来控制它条件渲染，一个两个还好，如果多了就感觉有点麻烦。

### 描述您想要的解决方案
让 Popup 弹出层支持关闭显示重新渲染的功能，当弹出层关闭，销毁里面的内容，当弹出层显示出来，重新渲染里面的内容。

### 建议的API是什么样的
建议给 Popup 弹出层增加一个属性：force-render，强制渲染。每次关闭销毁内容，每次显示重新渲染内容。

**Comment by chenjiahan** [comment]
这个场景不是很常见，而且加一个 v-if 还是蛮方便的。。暂时没有计划在组件里支持呢
