### ISSUE TITLE
[Bug Report] 嵌套tabs，里面的tabs的active失效或切换动画跟不上

### ISSUE THREAD

**Issue by hzj9400** [youzan/vant#6081]
### 设备 / 浏览器
PC浏览器手机模式

### Vant 版本
2.5.9

### Vue 版本
3.0.0-beta.1

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-gjym4?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-gjym4?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
嵌套tabs后里面的tabs切换和外面的tabs切换会导致里面tabs的高亮状态与里面tabs的显示内容不一致，内容是正确的，但是高亮的样式是不正确的

**Comment by chenjiahan** [comment]
for 循环生成的多个 Tabs 不能绑定同一个 activeName 变量
