### ISSUE TITLE
picker通过v-for使用，数据怎么都是最后一条的选择数据。

### ISSUE THREAD

**Issue by xingaojie** [youzan/vant#6085]
<van-cell v-for="(item,key) in dataList" :key="key">
          <tr class="information">
            <td class="mytd" style="width:25%">{{item.showName}}：</td>
            <td class="mytd" style="width:35%">{{item.beforeModify}}</td>
            <td class="mytd" style="width:40%">
             
              <template v-if="item.dictCode==2">
                <van-field
                  readonly
                  clickable
                  v-model="allKey[item.columnId]"
                  :name="item.columnId"
                  placeholder="点击选择"
                  @click="showPic(item.columnId)"
                />
                <van-field v-show="false" :name="item.columnId" v-model="keyid" />
                <van-popup v-model="showPicker" position="bottom">
                  {{item.showName}}
                  <van-picker
                    show-toolbar
                    :columns="item.columns"
                    @confirm="onConfirmPicker"
                    @cancel="showPicker = false"
                  />
                </van-popup>
              </template>

**Comment by xingaojie** [comment]
请尽快回复

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by 923372148** [comment]
您这个问题解决了么，我也是哎。。

**Comment by Syrup-Bunny** [comment]
同样的问题。。
