### ISSUE TITLE
[Feature Request] 希望Skeleton组件的图片和段落占位能支持设置高度

### ISSUE THREAD

**Issue by changeplango** [youzan/vant#6086]
### 这个功能解决了什么问题
比如要设置一个长方形图片占位

### 描述您想要的解决方案
希望Skeleton组件的图片和段落占位能支持设置高度

### 建议的API是什么样的
希望Skeleton组件的图片和段落占位能支持设置高度

**Comment by chenjiahan** [comment]
直接通过 CSS 去设置高度就可以喔
