### ISSUE TITLE
[Feature Request] 希望Icon组件能增加svg支持

### ISSUE THREAD

**Issue by changeplango** [youzan/vant#6087]
### 这个功能解决了什么问题
项目中需要有些地方需要使用到多色图标，为统一icon用法，希望Icon组件能增加svg支持

### 描述您想要的解决方案
项目中需要有些地方需要使用到多色图标，为统一icon用法，希望Icon组件能增加svg支持

### 建议的API是什么样的
项目中需要有些地方需要使用到多色图标，为统一icon用法，希望Icon组件能增加svg支持

**Comment by chenjiahan** [comment]
暂无计划支持呢，iconfont 会比 svg 体积小很多
