### ISSUE TITLE
[Feature Request] Calendar组件不支持过滤非工作日不可选

### ISSUE THREAD

**Issue by umi-soft** [youzan/vant#6089]
### 这个功能解决了什么问题
办理业务时，通过非工作日是不可选择的，目前并不支持非工作日禁用选项

### 描述您想要的解决方案
提供pros支持禁用对非工作日的选择

### 建议的API是什么样的
disable-weekday: true/false

**Comment by chenjiahan** [comment]
使用 formatter 属性，把非工作日的 type 设置成 disabled 就可以。

暂时没有计划在组件内部提供非工作日的处理。
