### ISSUE TITLE
[Bug Report] Swipe组件如果一开始v-show="false"，再转换成v-show="true"会滑动异常

### ISSUE THREAD

**Issue by Rangocold** [youzan/vant#6090]
### 设备 / 浏览器
设备

### Vant 版本
2.6.2

### Vue 版本
2.6.10

### 重现链接
<a href="https://github.com/Rangocold/Issue/blob/master/issue/src/vant/swipe.txt" target="_blank">https://github.com/Rangocold/Issue/blob/master/issue/src/vant/swipe.txt</a>

### 描述问题
我在业务上有一个需求，我有两组轮播组件，但某一个时刻只能看到其中一组，另外一组会使用v-show隐藏起来。
当我使用v-show去控制这两组轮播组件的时候，先显示的可以正常使用，但后显示的不能正常使用。我拉取了vant的源码本地调试了一下，发现是因为在初始化的时候swipe的initRect方法没有正确运行导致的，希望能得到修复

**Comment by chenjiahan** [comment]
v-show 为 false 时，组件无法获取到自身的宽度，会导致计算错误，这个问题在组件内部不太好解决。

你这个场景换成 v-if 就可以了

**Comment by swiminthecodelan** [comment]
Cascader 组件也有相同问题，vant 这种响应式触发 render 函数时，没有组件初始计算样式需要的条件。还有一种解决办法，v-show 条件在  data 中先设为 true，生命周期 mounted 中使用 nextTick 钩子设置为 false。
