### ISSUE TITLE
[Feature Request] List能增加横向加载更多的功能吗

### ISSUE THREAD

**Issue by gp3098** [youzan/vant#6091]
### 这个功能解决了什么问题
解决手机端用户横向滑动图片或者列表内容加载更多数据的功能。

### 描述您想要的解决方案
看代码里好像是支持上下两个方向的，能加上左右吗？

### 建议的API是什么样的
direction	滚动触发加载的方向，可选值为up|down|left|right 	类型string	默认值down

**Comment by chenjiahan** [comment]
暂无计划支持喔
