### ISSUE TITLE
[Feature Request] 功能改进 picker 打印完整数据项

### ISSUE THREAD

**Issue by thisAries** [youzan/vant#6094]
### 这个功能解决了什么问题
picker组件没有办法打印Array(Object)这样的数据。picker，不论是$refs还是内置的方法，都不能直接获取到数据的完整项。比如说我想拿到下拉数据的id。这就不能，我必须自己用string去查询id。而我们的项目是存在text可能有多个重复的情况。单纯的告诉我index和text，远远不够。

### 描述您想要的解决方案
因为在我的认知里，任何下拉数据都必须是有id的，除非后端没给id。如果有id则必须要用id保证每个选项的唯一性。像需要依赖这个id去联动或者查询默认信息这类的需求就非常需要这个功能。

### 建议的API是什么样的
Events：confirm 选中值文本，选中值对应的索引，选中值。
方法：getValues、getColumnValue、getColumnValues。
同时在没有数据的情况下，我希望picker有一个默认无数据的展示形式。
我希望上述返回值都加上源渲染数据。而不是单单的返回text，或者index。

在此之前我会自己想办法标记id，希望你们的组件越来越好，加油~。【icon】

**Comment by chenjiahan** [comment]
可以看下是不是跟这个 issue 的需求重复：https://github.com/youzan/vant/issues/5905
