### ISSUE TITLE
[Bug Report] field组件，number类型的不能输入负数，负号被replace了

### ISSUE THREAD

**Issue by liangzhicong** [youzan/vant#6096]
### 设备 / 浏览器
iphone6s

### Vant 版本
2.5.6

### Vue 版本
2.6.10

### 重现链接
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### 描述问题
formatNumber函数把负号替换掉了，导致无法输入负号

**Comment by chenjiahan** [comment]
iOS 上的数字键盘是不提供负号的，如果需要输入负数，建议还是使用 text 类型
