### ISSUE TITLE
[Bug Report] 右弹出框 与下拉刷新冲突 弹出框一起下拉了 原则上是不下拉的

### ISSUE THREAD

**Issue by zhaojinxiong** [youzan/vant#6098]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by zhaojinxiong** [comment]
[图片](https://zjxitalker.oss-cn-beijing.aliyuncs.com/0d94caf5a5b8b7ffcce5fc492a2aae0.png)

**Comment by chenjiahan** [comment]
在 Popup 上设置 get-container="body" 即可
