### ISSUE TITLE
Picker级联选择不能设置默认选中值

### ISSUE THREAD

**Issue by chua1989** [youzan/vant#6099]
查看了文档和源码。没有支持picker多级级联的时候设置默认选中值。
default-index只能设置一个数字

这个应该是比较基本的功能吧，考虑什么时候加上？

**Comment by sylvaner-h** [comment]
以文档为例
```javascript
export default {
  data() {
    return {
      columns: [
        {
          text: '浙江',
+         defaultIndex: 1,
          children: [
            {
              text: '杭州',
              children: [{ text: '西湖区' }, { text: '余杭区' }],
            },
            {
              text: '温州',
              children: [{ text: '鹿城区' }, { text: '瓯海区' }],
            },
          ],
        },
        {
          text: '福建',
          children: [
            {
              text: '福州',
              children: [{ text: '鼓楼区' }, { text: '台江区' }],
            },
            {
              text: '厦门',
              children: [{ text: '思明区' }, { text: '海沧区' }],
            },
          ],
        },
      ],
    };
  },
};
```

**Comment by bluesky59** [comment]
同求，自己设置了defaultIndex不生效

**Comment by napoleon-he** [comment]
这问题怎么还有，请问现在解决了？

**Comment by Silent-Jude** [comment]
> 以文档为例
> 
> ```js
> export default {
>   data() {
>     return {
>       columns: [
>         {
>           text: '浙江',
> +         defaultIndex: 1,
>           children: [
>             {
>               text: '杭州',
>               children: [{ text: '西湖区' }, { text: '余杭区' }],
>             },
>             {
>               text: '温州',
>               children: [{ text: '鹿城区' }, { text: '瓯海区' }],
>             },
>           ],
>         },
>         {
>           text: '福建',
>           children: [
>             {
>               text: '福州',
>               children: [{ text: '鼓楼区' }, { text: '台江区' }],
>             },
>             {
>               text: '厦门',
>               children: [{ text: '思明区' }, { text: '海沧区' }],
>             },
>           ],
>         },
>       ],
>     };
>   },
> };
> ```

no，你这样写，只能对杭州温州这里起效，也就是第二级有效！
同理，在第二级的children里写只能对第三级有效。
那么问题来了，我想要对第一级有效怎么办呢。。。。。？
