### ISSUE TITLE
CheckboxGroup 里面的chekBox的prop, name的类型效验

### ISSUE THREAD

**Issue by AlanZou007** [youzan/vant#610]
name是我购物车一件商品的对象, 是否可以这个效验去掉呢. 
name如果传一个对象, 我想会方便很多

![image](https://user-images.githubusercontent.com/24911981/35847092-22e485f2-0b54-11e8-950e-d93573675675.png)

**Comment by AlanZou007** [comment]
@chenjiahan 是这样子的, 后台返回给我是一个二维数组, 相同的店铺合并了到了一下, 在购物车我要进行一系列的操作. 如果是id的话, 每次都有遍历, 请问有什么好的方法吗?

**Comment by chenjiahan** [comment]
请问每次都遍历指的是？

**Comment by AlanZou007** [comment]
如果要删除对应的id, 就是遍历二维数组找到对应的删除掉...

**Comment by chenjiahan** [comment]
@AlanZou007 可以用 Array.filter 处理
