### ISSUE TITLE
[Bug Report] List组件中v-model属性的值在setTimeout()内设置为false，加载UI依然存在

### ISSUE THREAD

**Issue by 104828720** [youzan/vant#6103]
### 设备 / 浏览器
chrome

### Vant 版本
2.6.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-9rwns" target="_blank">https://codesandbox.io/s/vant-issue-moban-9rwns</a>

### 描述问题
  // 正常状态：如果这样写, 加载就不出现
      
  this.loading = false;

  // BUG情况：如果使用setTimeout()，加载还是存在
     
 setTimeout(() => {
        this.loading = false;
      }, 2000);

如上图代码所示，为何在setTimeout内改变loading的值，加载不消失？

**Comment by chenjiahan** [comment]
List 是在 updated 事件中去更新内部的 loading 状态的，如果你不需要加载任何数据，直接把 finished 设置为 true 就可以了
