### ISSUE TITLE
如何配置vant不支持的多语言啊

### ISSUE THREAD

**Issue by LiuNing244871946** [youzan/vant#6105]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以提 PR 来增加相应的语言包
