### ISSUE TITLE
 show-error和show-error-message 无效

### ISSUE THREAD

**Issue by territoryfan** [youzan/vant#6106]
###  :show-error="false"和 :show-error-message="false"  ，两个无效
`<van-field
                v-model="email"
                required
                input-align="right"
                label="邮箱"
                name="email"
                :show-error="false"
                :show-error-message="false"
                placeholder="请输入邮箱"
                clearable
                :rules="validate.email"
            >
            </van-field>`
**版本**
"vant": "^2.6.3",

**Comment by chenjiahan** [comment]
这两个是 Form 的属性，不是 Field 的

**Comment by starlet0822** [comment]
不能独立控制某个 flield的show-error-message属性？？
