### ISSUE TITLE
form组件field ios13.3.1无法显示光标和输入

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#6107]
https://youzan.github.io/vant-issue-generater/dist/#/打不开，提一个issues

form组件field ios13.3.1无法显示光标和输入

问题：点击能吊起键盘但无法显示光标也无法输入,查了上几个isssus没找到解决办法，很着急啊，项目马上就验收了

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by cangyu1993** [comment]
官网的form表单demo能正常用，为何项目中的就有问题，很烦这个

**Comment by cangyu1993** [comment]
![image](https://user-images.githubusercontent.com/42930030/79952899-b17a1c80-84ad-11ea-8bf9-06b04bf8de1d.png)
解决了------欲哭无泪啊，自己作孽啊，css不允许复制我加到了全局，哎。。。。打扰了

**Comment by chenjiahan** [comment]
😂
