### ISSUE TITLE
vant通过cdn引入，部分组件用不了

### ISSUE THREAD

**Issue by yang-jian-bing** [youzan/vant#6108]
### 设备 / 浏览器
谷歌最新浏览器

### Vant 版本
2.6.3

### Vue 版本
3.0.0-beta.3

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
Calendar 日历这个组件就用不了

**Comment by chenjiahan** [comment]
建议你检查下 CDN 链接上的版本号，较早的版本里没有 Calendar 组件

下面这个是 2.6 版本的 CDN：
https://cdn.jsdelivr.net/npm/vant@2.6/lib/vant.min.js

**Comment by yang-jian-bing** [comment]
感谢，确实是这个原因，非常的感谢
