### ISSUE TITLE
[Bug Report] 通过cdn的方式引入vant，部分组件打开，关闭不了

### ISSUE THREAD

**Issue by yang-jian-bing** [youzan/vant#6112]
### 设备 / 浏览器
谷歌最新浏览器

### Vant 版本
2.6.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/youzan/vant/issues/new" target="_blank">https://github.com/youzan/vant/issues/new</a>

### 描述问题
Calendar组件打开，关闭不了

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接 https://codesandbox.io/s/m5v3f

**Comment by yang-jian-bing** [comment]
问题解决了，如果是通过cdn方式引入的，必须要标签闭合
错误：
<van-calendar v-model="show1" @confirm="onConfirm"/>
正确：
<van-calendar v-model="show1" @confirm="onConfirm"></van-calendar>
