### ISSUE TITLE
[Bug Report] 上传组件message视图不能更新

### ISSUE THREAD

**Issue by gapkukb** [youzan/vant#6113]
### 设备 / 浏览器
chrome 版本 81.0.4044.113（正式版本） （64 位）

### Vant 版本
2.6.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/carlosJoo/pen/RwWKVPP" target="_blank">https://codepen.io/carlosJoo/pen/RwWKVPP</a>

### 描述问题
组件上传中，希望展示上传进度。发现改变message并没有更新视图。使用的axios

**Comment by chenjiahan** [comment]
确实存在这个问题，message 没定义初始值导致的，下个版本会修复下

**Comment by chenjiahan** [comment]
已在 2.7.0 版本修复
