### ISSUE TITLE
tab 使用v-for 动态绑定name属性 切换事件返回的name不对

### ISSUE THREAD

**Issue by huran19941010** [youzan/vant#6114]
![image](https://user-images.githubusercontent.com/24221243/80057538-61f12a80-8559-11ea-8388-98a321e7ca43.png)
![image](https://user-images.githubusercontent.com/24221243/80057554-6e758300-8559-11ea-905e-3c4c983d19f1.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
