### ISSUE TITLE
[Bug Report] 图片上传组件在安卓无法多选(ios可以)

### ISSUE THREAD

**Issue by YIngChenIt** [youzan/vant#6115]
### 设备 / 浏览器
安卓

### Vant 版本
2.6.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/form" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
使用van-uploader的时候设置了multiple，但是在真机安卓上无法多选图片，ios可以，应该是安卓本身不支持的问题，看下能否可以支持安卓多选

**Comment by chenjiahan** [comment]
无法支持呢
