### ISSUE TITLE
[Bug Report] dialog中的slider滑动时偶尔会穿透

### ISSUE THREAD

**Issue by MBearo** [youzan/vant#6117]
### 设备 / 浏览器
IOS safari

### Vant 版本
2.6.3

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-z920b?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-z920b?file=/src/App.vue</a>

### 描述问题
dialog中的slider滑动时偶尔会穿透。横向拖动滑块时，手势稍微往上或者往下偏，容易触发。

**Comment by chenjiahan** [comment]
我用 safari 试了下没复现耶，iphoneXR, iOS 13.3.1

**Comment by MBearo** [comment]
> 我用 safari 试了下没复现耶，iphoneXR, iOS 13.3.1

iOS13和安卓我给手动处理了一下，可以正常使用。但是iOS12搞不定。

**Comment by MBearo** [comment]
> 我用 safari 试了下没复现耶，iphoneXR, iOS 13.3.1

弹窗显示的时候给body加这个属性，但是iOS12不支持。
.modal-active{
  touch-action: none;
  overscroll-behavior: none;
  -webkit-overflow-scrolling: auto;
  overflow: hidden;
}

**Comment by chenjiahan** [comment]
某些较低的系统版本存在滚动穿透是有可能的，其实弹窗里不太适合放 Slider 这种交互，如果真的要加的话，可以试试下面的写法，阻止滚动事件冒泡

```html
<van-slider @touchmove.native.prevent.stop />
```
