### ISSUE TITLE
[Bug Report] tab在子组件中乱序

### ISSUE THREAD

**Issue by qqcbqqkcel** [youzan/vant#6118]
### 设备 / 浏览器
chrome

### Vant 版本
2.6.3

### Vue 版本
2.6.10

### 重现链接
<a href="https://www.yuque.com/docs/share/a09ed6de-be3d-4a3d-82d7-d40135aec8da?#" target="_blank">https://www.yuque.com/docs/share/a09ed6de-be3d-4a3d-82d7-d40135aec8da?#</a>

### 描述问题
van-tab如果写在其他组件中，然后使用会出现乱序问题

**Comment by chenjiahan** [comment]
确实有这个问题，后续会修复下

**Comment by chenjiahan** [comment]
已在 2.7.0 版本修复
