### ISSUE TITLE
[Bug Report] calendar中formatter报错

### ISSUE THREAD

**Issue by y135213** [youzan/vant#6120]
### 设备 / 浏览器
Chrome

### Vant 版本
2.6.3

### Vue 版本
2.5.2

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-jsyux?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-jsyux?file=/src/App.vue</a>

### 描述问题
calendar中的formatter  console.log(day)报错  TypeError: Cannot read property 'type' of undefined

**Comment by sylvaner-h** [comment]
```js
formatter(day){
      console.log(day);
 +   return day; 
 }  
```

**Comment by y135213** [comment]
OK，解决了，谢谢
