### ISSUE TITLE
[Bug Report] Swipe 轮播 滑动的时候 切换到下一个栏目了怎么阻止 滑动传递

### ISSUE THREAD

**Issue by wade419** [youzan/vant#6122]
### 设备 / 浏览器
app

### Vant 版本
2.6.3

### Vue 版本
3.0.0-beta.3

### 描述问题
我们的项目是移动 web项目 ，嵌入到一个app中，app上方有很多菜单，我们的系统里面有一个  Swipe 轮播 功能，目前的问题是 滑动的时候会滑动到 另一个页面（也就是app本身的滑动机制被触发了），需要实现的是 滑动轮播图的时候不进行网页 滑动

**Comment by chenjiahan** [comment]
可以阻止 touch 直接冒泡

```html
<van-swipe
  @touchstart.native.stop
  @touchmove.native.stop
  @touchend.native.stop
>
```

**Comment by wade419** [comment]
<van-swipe class="my-swipe" :autoplay="3000" indicator-color="white" 
                                @touchstart.native.stop 
                                @touchmove.native.stop 
                                @touchend.native.stop>
                            <van-swipe-item><img src="__ROOT__/uploads/banner/lb2.jpg" width="100%"></van-swipe-item>
                            <van-swipe-item><img src="__ROOT__/uploads/banner/lb3.jpg" width="100%"></van-swipe-item>
                            <van-swipe-item><img src="__ROOT__/uploads/banner/lb4.jpg" width="100%"></van-swipe-item>
                            <van-swipe-item><img src="__ROOT__/uploads/banner/lb5.jpg" width="100%"></van-swipe-item>

                        </van-swipe>


你好这样写吗，还是不起作用，滑动的时候触发了 app的滑动事件

**Comment by wade419** [comment]
stop-propagation  这个参数文档写的可以 阻止滑动事件冒泡 ，设置了 不起作用什么原因

**Comment by chenjiahan** [comment]
app 的滑动可以再加个 .prevent

**Comment by wade419** [comment]
> app 的滑动可以再加个 .prevent

谢谢，我试下

**Comment by lianvicky** [comment]
你好 请问解决了吗？我试了加了.prevent也还是会触发app的滑动

**Comment by lianvicky** [comment]
你好 请问解决了吗？我试了加了.prevent也还是会触发app的滑动
