### ISSUE TITLE
Tab + List 切换tab时onLoad 被多次触发

### ISSUE THREAD

**Issue by ziruolu** [youzan/vant#6123]
### Vant 版本
2.6.3

### Vue 版本
2.6.10

### 重现链接: 
https://svqie.csb.app/

---

### 描述问题：
 **在tab里包含list组件，当在第一个tab进行多次下拉加载时， 切换到第二个tab, onLoad 被多次触发； 当在第一个tab时不进行下拉加载，切换到第二个tab正常，没有触发onLoad**

**Comment by chenjiahan** [comment]
多个 List 组件需要分别绑定不同的 loading/finished 变量，而不是绑定同一个变量
