### ISSUE TITLE
van-grid-item 如何去除自带padding

### ISSUE THREAD

**Issue by stewForAni** [youzan/vant#6125]
vant:2.5.9

van-grid-item 如何去除自带padding?

**Comment by chenjiahan** [comment]
直接通过 CSS 覆盖就可以的

```html
<template>
  <van-grid-item class="my-grid-item" />
</template>

<style>
.my-grid-item .van-grid-item__content {
  padding: 0;
}
</style>
```

**Comment by stewForAni** [comment]
> 直接通过 CSS 覆盖就可以的
> 
> ```
> <template>
>   <van-grid-item class="my-grid-item" />
> </template>
> 
> <style>
> .my-grid-item .van-grid-item__content {
>   padding: 0;
> }
> </style>
> ```

你好，按照你的写法我加上去了，可是无效诶，还是自带padding（上下16px，左右8px）

**Comment by wujingquan** [comment]
@stewForAni 我的可以，刚开始直接复制style的样式，但是template没有改class，后来细看了一下，style里面的是my-grid-item而不是van-grid-item，给template里的组件加对应的class名称就行了。或者把不加也行，把style的my-grid-item改为van-grid-item。

**Comment by wujingquan** [comment]
@chenjiahan 去掉这个内边距我的第一反应是到文档去找，是否有api可以去掉内边距，不知道大佬觉得加个开关是否是个好的方案？

**Comment by chenjiahan** [comment]
目前看没必要加 API

**Comment by marren06** [comment]
@chenjiahan  小程序版本怎么设置

<template>
  <van-grid-item class="my-grid-item" />
</template>

<style>
.my-grid-item .van-grid-item__content {
  padding: 0;
}
</style>

这段代码怎么加？

**Comment by wordscode** [comment]
> > 直接通过 CSS 覆盖就可以的
> > ```
> > <template>
> >   <van-grid-item class="my-grid-item" />
> > </template>
> > 
> > <style>
> > .my-grid-item .van-grid-item__content {
> >   padding: 0;
> > }
> > </style>
> > ```
> 
> 你好，按照你的写法我加上去了，可是无效诶，还是自带padding（上下16px，左右8px）

vue3这样写可以
:deep() {
    .van-grid-item__content {
      // padding: 0;
      padding: 2px;
    }
  }
