### ISSUE TITLE
[Bug Report] imagePreview 轻触之后等待300ms关闭太长

### ISSUE THREAD

**Issue by aosnow** [youzan/vant#6128]
### 设备 / 浏览器
chrome

### Vant 版本
2.6.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/image-preview" target="_blank">https://youzan.github.io/vant/#/zh-CN/image-preview</a>

### 描述问题
默认情况下 ImagePreview 组件为了实现双击放大图片的功能，而让正常需要立即关闭的场景等待过长，非常不友好，有明显的延迟/卡顿错觉。
建议 ImagePreview 组件的 162-174 行代码修改减少延迟等待的时间表为 200ms
```js
      if (deltaTime < 200 && offsetX < 10 && offsetY < 10) {
        if (!this.doubleClickTimer) {
          this.doubleClickTimer = setTimeout(function () {
            _this3.emitClose();

            _this3.doubleClickTimer = null;
          }, 200);
        } else {
          clearTimeout(this.doubleClickTimer);
          this.doubleClickTimer = null;
          this.toggleScale();
        }
      }
```
这样可以更好的取得一个中间平衡点，既不影响双击放大功能也能优化不能即时关闭的需求。

**Comment by chenjiahan** [comment]
可以的，这个数值我调试下看看

**Comment by chenjiahan** [comment]
查了下资料，iOS 上默认的 double click 间隔是 250ms，200ms 太考验手速了。

下个版本会调整为 250ms

**Comment by chenjiahan** [comment]
已在 2.7.0 版本调整

**Comment by xiaoForest** [comment]
怎么阻止关闭呀，让它有特定的位置去点击关闭。
