### ISSUE TITLE
[Bug Report] ios 下 Picker 选择器 双击会放大

### ISSUE THREAD

**Issue by wannvmi** [youzan/vant#6129]
### 设备 / 浏览器
ios 13.2.3 ios 10.3.3

### Vant 版本
2.6.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/picker</a>

### 描述问题
在 ios 13.2.3 ios 10.3.3 下 ，双击Picker会发生放大效果 
安卓不会，不清楚发生的原因

**Comment by chenjiahan** [comment]
可以在 head 标签里加下 viewport 设置

```html
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,viewport-fit=cover">
```

**Comment by wannvmi** [comment]
非常感谢
