### ISSUE TITLE
不能修改van-field样式

### ISSUE THREAD

**Issue by studiousryan** [youzan/vant#6131]
想修改van-field的字体颜色、placeholder颜色。
尝试过：
- 修改 `.van-field__control`的，但是完全没有被覆盖
- 通过custom-style属性修改颜色，也完全没作用 `<van-field custom-style="color: blue; background-color: red" v-model="phone.val" type="tel" :label="$t('my.phone')" :placeholder="$t('common.phone_remind')" />`

就因为这问题痛苦了一晚上了，头发都要扯完了。求拯救

**Comment by JohnieXu** [comment]
麻烦提供一下所用的版本，最好有可复现的 demo 链接

**Comment by cangyu1993** [comment]
可以自己心脏类，然后deep
类似：
![image](https://user-images.githubusercontent.com/42930030/80299048-eba43080-87c3-11ea-9ca5-6c51f62a3f73.png)

**Comment by yexianingyue** [comment]
需要在wxss中这样定义
```css
.field_test{
  color: blue !important;
}
```
然后在wxml中使用`<van-field label-class="field_test">`即可，后面的`!important`盲猜作用和覆盖一样
