### ISSUE TITLE
[Bug Report] Tab 标签页组件使用scrollspy sticky后，点击导航栏页面不跟随导航位置滚动？

### ISSUE THREAD

**Issue by lmz216** [youzan/vant#6132]
### 设备 / 浏览器
Android 

### Vant 版本
2.6.3

### Vue 版本
3.0.0-beta.4

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-4zg73?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-4zg73?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
安卓系统不跟随点击导航栏页面定位到指定位置

**Comment by chenjiahan** [comment]
用 iphone 和华为 mate20 试了下，未复现该问题

**Comment by lmz216** [comment]
是我没有设置高度

**Comment by chenjiahan** [comment]
get👌
