### ISSUE TITLE
[Bug Report] van-dropdown-menu中，van-dropdown-item排序有时错乱

### ISSUE THREAD

**Issue by wen19911030** [youzan/vant#6135]
### 设备 / 浏览器
chrome

### Vant 版本
2.6.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-q5qw1" target="_blank">https://codesandbox.io/s/vant-issue-moban-q5qw1</a>

### 描述问题
van-dropdown-menu中，如果有van-dropdown-item是以组件引入，会导致排序错乱

**Comment by chenjiahan** [comment]
跟这个 issue 是同个问题，下个版本会修复：https://github.com/youzan/vant/issues/6118
