### ISSUE TITLE
[Feature Request] 可以在无 webpack 的开发环境里按需使用组件吗？

### ISSUE THREAD

**Issue by ejlchina** [youzan/vant#6138]
### 这个功能解决了什么问题
在无 webpack 的环境里按需使用组件

### 描述您想要的解决方案
可以在无 webpack 的环境里按需使用组件

### 建议的API是什么样的
可以在无 webpack 的环境里按需使用组件

**Comment by chenjiahan** [comment]
不可以呢，没有构建的话只能通过 CDN 全量引入

**Comment by ejlchina** [comment]
好的，谢谢
