### ISSUE TITLE
vant组件非常不错,已应用到公司项目中了,还支持ssr.但是能否加一个list组件(带可以展开和收起那种)

### ISSUE THREAD

**Issue by a251115100** [youzan/vant#615]

**Comment by chenjiahan** [comment]
看了一下，这个组件的布局部分和 Vant 中的 Cell 组件比较相似，区别比较大的是多了一个 Expansion 的 panel，这个 Expansion 功能我们不倾向于集成在 Cell 中，如果需要的话，应该会提供一个单独的组件

**Comment by a251115100** [comment]
还是你想的周到 -_- ,单独提供一个Collapse这组件也能实现Expansion功能

**Comment by chenjiahan** [comment]
哈哈，Collapse 已加入开发计划，我们会在后续支持

**Comment by Airkro** [comment]
也希望增加常用组件中的Grid

**Comment by chenjiahan** [comment]
已在 1.0.0 版本中新增了 Collapse 组件，详见文档
https://www.youzanyun.com/zanui/vant#/zh-CN/collapse
