### ISSUE TITLE
不是bug讨论使用

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#6154]
遇到局域网开发问题，icon什么的都拉不下来，都是小方框□，怎么解决，太多使用了

**Comment by chenjiahan** [comment]
可以引本地 iconfont：https://youzan.github.io/vant/#/zh-CN/icon#shi-yong-ben-di-zi-ti-wen-jian

**Comment by cangyu1993** [comment]
不光是icon还有很多需要链接互联网的资源，很多都是图片什么的

**Comment by chenjiahan** [comment]
其他资源你自己解决呀，可以转 base64 内联，或者放本地相对路径

**Comment by cangyu1993** [comment]
有没有所以的icon都引用本地的?还是说用多少引多?

**Comment by chenjiahan** [comment]
上面的用法就是 Vant 里的所有 IconFont 引本地。
