### ISSUE TITLE
[Bug Report] form组件文档和代码不一致

### ISSUE THREAD

**Issue by Chryseis** [youzan/vant#6156]
### 设备 / 浏览器
chrome

### Vant 版本
2.6.3

### Vue 版本
2.6.3

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/form#xiao-yan-gui-ze" target="_blank">https://youzan.github.io/vant/#/zh-CN/form#xiao-yan-gui-ze</a>

### 描述问题
https://github.com/youzan/vant/blob/acfefe6518ffebab584bd697165e729349dd0c39/src/form/demo/ValidateRules.vue#L70
in demo code ``` validator(val) {
        return val === '1234';
      },```
in md
```
   validator(val) {
      return /1\d{10}/.test(val);
    },
```

**Comment by chenjiahan** [comment]
可以提个 PR 帮忙统一成文档里的写法😄

**Comment by JohnieXu** [comment]
大佬们的响应速度好快👍👍
