### ISSUE TITLE
能否在popup组件被激活时,给body增加一个className?

### ISSUE THREAD

**Issue by zhuxianbin** [youzan/vant#6157]
这个功能解决了什么问题
能通过样式,能将遮罩后面的容器进行一个美化,如 transform: scale(0.95);

描述您想要的解决方案
在body标签里增加一个  popup 被 active 的样式名称

建议的API是什么样的
你们是大佬,你们说了算...

**Comment by chenjiahan** [comment]
暂时没有计划添加呢，建议 watch Popup show 并自行添加

**Comment by zhuxianbin** [comment]
无意发现,当popup被激活时,你们已经给body加上了一个 van-overflow-hidden 样式,感谢.
