### ISSUE TITLE
一些小小提议

### ISSUE THREAD

**Issue by de1ck** [youzan/vant#616]
1. 版本预览以及发布计划（提前预知后面几个版本的改动与task进度）
2. 组件的丰富度，可能vant团队是做商城的团队，很多组件会往跟商城有关的业务相关。希望可以抽出时间开发更多大众的组件，可能会吸引更多的开发者使用。

题外话： 使用vant一段时间了，踩过一些坑，提过几个issue，整体感觉很棒，感谢vant团队的开源。 @chenjiahan

**Comment by chenjiahan** [comment]
感谢你的建议~
1. 版本更新内容：我们主要关注 Github 的 issue 以及一些内部的需求，比较大的改动我们会列在 Github 的 Project 下面，可以在这里查看： https://github.com/youzan/vant/projects/1

2. 基础组件我们也在不断完善中，有需求欢迎提出来 我们会评估优先级并加入后续的开发计划 ^_^
