### ISSUE TITLE
[Feature Request] 支持样式单独提取到css文件

### ISSUE THREAD

**Issue by gapkukb** [youzan/vant#6163]
### 这个功能解决了什么问题
解决样式多次引入的问题

### 描述您想要的解决方案
经过多次实验结论如下：
不管是使用babel-plugin-import 还是 ts-import-plugin 。都存在一个问题。假如在两个组件中局部引入了 同样的vant组件。那么会生成重复内容的单独css文件。
如：两个路由组件 A.vue B.vue 。同时局部引入了van-button组件。那么打包后会生成a.css b.css 两个css文件，都是一模一样，即：将vant-button的样式打包了两次。
如果在 main.js 全局引入组件可以解决这个问题。但是会造成主包太大。
请问有什么解决方法吗

使用vue/cli生成的项目，路由组件A.vue B.vue 是异步组件。改为同步组件没有此问题，同样也会造成主包太大

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
这个和组件库没关系，是项目打包配置的问题，可以通过配置把重复引入的样式抽到公共文件里（比如 vendor）
