### ISSUE TITLE
[Feature Request] 新版设计规范，落实了吗，期待ing~

### ISSUE THREAD

**Issue by luckymore** [youzan/vant#6164]
![image](https://user-images.githubusercontent.com/5390013/80472544-72e5d580-8977-11ea-8ea4-a7b5017c41a7.png)

### 这个功能解决了什么问题
想膜拜下新的设计规范

### 描述您想要的解决方案
想膜拜下新的设计规范，给我们的设计师参考

### 建议的API是什么样的
想膜拜下新的设计规范，给我们的设计师参考

**Comment by chenjiahan** [comment]
已经在内测了，最近 Vant 样式会有一波更新，更新完后会放出最新的视觉稿（预计在六月份的样子）
