### ISSUE TITLE
[Bug Report] layout布局间距计算错误

### ISSUE THREAD

**Issue by wh469012917** [youzan/vant#6166]
### 设备 / 浏览器
chrome iphonex

### Vant 版本
2.7.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-7pysd" target="_blank">https://codesandbox.io/s/vant-issue-moban-7pysd</a>

### 描述问题
1. layout 里面设置了gutter，但是实际渲染出来的gutter计算明显错误
2. layout布局里面的span加起来不等于24的情况下，会使得布局很混乱。虽然说这个用法可能是错误的，但是实际业务中确实会出现这样的应用场景。比如一个无限下拉的卡片列表，一行是两个元素

这里还有一个疑问，为什么这个layout布局不按照bootstrap的形式，在row外层增加 一个container来解决间距的问题呢？或者说是否可以考虑使用ant design的方式，row设置负值的margin，然后col设置正值的padding，当一行元素超出24之后，多余的就另起一行

抽空帮忙答疑一下，谢谢了~

**Comment by chenjiahan** [comment]
目前版本（2.7.0 ~ 2.7.1）的 gutter 计算确实有问题，后续会修复下

bootstrap 的方案会参考下

Row 不设置负 margin 的原因可以看这个 issue：https://github.com/youzan/vant/issues/6130

**Comment by yangyangsensen** [comment]
![image](https://user-images.githubusercontent.com/28916197/80668495-9eca9d80-8ad4-11ea-99e0-3a835092092b.png)
layout 更新后 页面都错乱了

**Comment by wh469012917** [comment]
@chenjiahan 并不会的，你可以试一下这样：
```
<div class='row'>
    <div class='col'></div>
    <div class='col'></div>
</div>

.row {
    margin: 0px -4px
}
.col {
    padding: 0px 4px
    width: 50%;
}
```
那么这样gutter就是8，卡片宽度是50%

**Comment by chenjiahan** [comment]
@wh469012917 2.7.0 以前就是这样实现的。

**Comment by wh469012917** [comment]
@chenjiahan 确实，只能考虑看看用bootstrap的那种方案了

**Comment by chenjiahan** [comment]
试了下，bootstrap 的方案也不太适用，还是得在 JS 中计算边距

**Comment by chenjiahan** [comment]
已在 2.8.0 版本支持
