### ISSUE TITLE
期待checkbox支持最大选择数量功能

### ISSUE THREAD

**Issue by mpandar** [youzan/vant#617]
mintui有此功能，http://mint-ui.github.io/docs/#/en2/checklist  它们提供了max参数，可以控制checkbox group最大选中数量，期望vant也支持此功能~，当然，我也期望自己能贡献这个功能

**Comment by chenjiahan** [comment]
@mpandar 欢迎贡献代码 ^_^

**Comment by chenjiahan** [comment]
#631
