### ISSUE TITLE
[Bug Report] van-list

### ISSUE THREAD

**Issue by wang475293638** [youzan/vant#6170]
### 设备 / 浏览器
guge

### Vant 版本
2.5.2

### Vue 版本
3.0.0-beta.4

### 重现链接
<a href="https://www.buhui.com" target="_blank">https://www.buhui.com</a>

### 描述问题
切换筛选条件 顶部loading动画就没了，只有页面初始化的时候出现一次，页面下拉出现一次

     const { data } = await this.$Parse.Cloud.run("getOrder", {
        pageSize: this.pageSize,
        pageIndex: this.pageIndex,
        startTime: this.startTime,
        endTime: this.endTime,
        name: this.searchValue,
        state: this.state
      });
      this.order.push(...data);
      this.loading = false;
      if (orderList.length) {
        this.pageIndex  ;
        this.finished = false;
      }
      if (!orderList.length) {
        this.finished = true;
      }
    // 改变订单状态值进行筛选
    async changeState(orderState) {
      this.state = orderState;
      this.pageIndex = 0;
      this.order = [];
      this.onLoad();
     },

**Comment by wang475293638** [comment]
页面拖动出现一次 这里描述的不准确，应该是 页面上滑或者距离底部不足offset时，有loading动画，切换了筛选条件没有动画

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by wang475293638** [comment]
> 麻烦提供一下codeandbox重复现链接

没用过 codesandbox   不知道咋弄      尴尬

**Comment by chenjiahan** [comment]
直接在这个链接里提供复现的示例即可

https://codesandbox.io/s/m5v3f
