### ISSUE TITLE
[Bug Report] 【Uploader 文件上传】在使用浏览器上传微信图片时上传不了

### ISSUE THREAD

**Issue by SunnyEdith** [youzan/vant#6171]
### 设备 / 浏览器
安卓/谷歌浏览器

### Vant 版本
2.7.1

### Vue 版本
3.0.0-beta.4

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/mobile.html/#/zh-CN/uploader</a>

### 描述问题
【Uploader 文件上传】组件使用基础用法在谷歌浏览器上传图库分类微信里面的图片时上传不了图片以及使用限制上传数量时上传了显示不了图片

**Comment by chenjiahan** [comment]
什么设备？ 最好来个视频看下

**Comment by SunnyEdith** [comment]
> 什么设备？ 最好来个视频看下

就安卓手机，使用谷歌浏览器使用上传图片组件库单个照片上传的或者多照片上传限制上传数量为1，
点击上传组件找到微信保存的图片，上传不上

**Comment by chenjiahan** [comment]
没复现，麻烦提供复现的 codesandbox 链接及具体型号

**Comment by SunnyEdith** [comment]
> 没复现，麻烦提供复现的 codesandbox 链接及具体型号

1.使用安卓手机（Android 8.0及以上）打开谷歌浏览器（chrome 81.0.4044.117）
2.进入谷歌浏览器之后打开https://youzan.github.io/vant/mobile.html#/zh-CN/uploader这个网址
3.（情况一）然后就可以看到基础用法这个上传框，点击然后到选择图片的一个页面，选择下方的浏览选项，进入到图片文件夹选择的页面，选择名 WeiXin 的这个文件夹 找到一张是微信上保存下来的图片，点击选择，然后会发现并没有上传到
4.（情况二）或者是选择限制上传数量这个用法，点击然后到选择图片的一个页面，选择下方的浏览选项，进入到图片文件夹选择的页面，选择名 WeiXin 的这个文件夹 找到一张是微信上保存下来的图片，点击选择，然后发现只能显示图片文件名， 显示不了图片。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5965

**Comment by SunnyEdith** [comment]
上传图片的基础用法是什么浏览器都不行，但是其他用法，我试过火狐可以，QQ浏览器也可以，但是就是谷歌不行

**Comment by chenjiahan** [comment]
你可以看下图片格式是不是跟上面 issue 里反馈的一样

**Comment by SunnyEdith** [comment]
手机谷歌浏览器上传的图片名字确实是没有后缀名，所以我获取上传文件信息后，从base64码中获取它的信息，这样就准确无误了，已经解决了，谢谢
