### ISSUE TITLE
[Bug Report] van-field输入框在安卓手机输入的时候导致页面变形

### ISSUE THREAD

**Issue by haoyinag** [youzan/vant#6181]
### 设备 / 浏览器
安卓

### Vant 版本
2.0.5

### Vue 版本
2.6.1

### 重现链接
<a href="http://weidingbh.lwina.com/weixinweb/#/assure_search" target="_blank">http://weidingbh.lwina.com/weixinweb/#/assure_search</a>

### 描述问题
在ios中输入没有问题，在安卓输入的时候页面会变形   主要是form会整个变形

**Comment by chenjiahan** [comment]
1. 安卓什么机型？
2. 官网示例能复现吗？
3. 能提供截图看下吗
