### ISSUE TITLE
[Bug Report] Tab List初次加载数据时，切换到tab自动load

### ISSUE THREAD

**Issue by qinZhenGitHub** [youzan/vant#6182]
### 设备 / 浏览器
浏览器

### Vant 版本
2.5.9

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/qinzhenzhen/pen/RwWZJpY" target="_blank">https://codepen.io/qinzhenzhen/pen/RwWZJpY</a>

### 描述问题
项目处理：监听Tabs的change事件，使用标志位，确定首次切换到此tab时才请求该tab的content数据。
Bug：如果ATab项触发了load,则跳转到BTab后BTab项会自动load一次（同理Btab也是）。
猜测Tab是需要在所有tab项都获取数据之后，List才能确定load事件的处理机制。

**Comment by chenjiahan** [comment]
如果不需要自动 Load，可以把 List 的 immediate-check 设置为 false。

另外滚动事件也会触发 List 的加载
