### ISSUE TITLE
[Feature Request]Calendar 日历组件需要更多功能

### ISSUE THREAD

**Issue by wTrMilkBall** [youzan/vant#6184]
在制作简单的定制计划相关的项目时，日历多选不连续日期功能就非常好用。所以希望添加几个功能。
日历组件type为multiple（多选）时，
1.可以限制多选日期的最大数量
2.可以监控取消选中的事件
希望能考虑加上，谢谢

**Comment by chenjiahan** [comment]
后续会支持

**Comment by chenjiahan** [comment]
已在 2.8.0 版本支持
