### ISSUE TITLE
NoticeBar 通知栏 动态修改 scrollable 表现异常

### ISSUE THREAD

**Issue by www8531692** [youzan/vant#6185]
设备 / 浏览器
chrome

Vant 版本
2.7.1

Vue 版本
2.6.11

重现链接
https://codesandbox.io/s/vant-issue-moban-gic64?fontsize=14&hidenavigation=1&theme=dark&file=/src/main.js

描述问题
vant 和 vant-weapp 都有这个问题
现在当我动态修改它的scrollable 的时候 如果是滚动状态 会依然保持滚动，文本是隐藏的状态。
我希望修改 scrollable 的时候 如果它处于滚动状态可以停止滚动变成文本隐藏的状态，如果处于隐藏状态可以变为滚动状态

**Comment by chenjiahan** [comment]
已在 2.8.0 版本修复
