### ISSUE TITLE
[Bug Report] Checkbox 组件不同版本执行点击事件后 model 值状态不一致

### ISSUE THREAD

**Issue by LTNSs** [youzan/vant#6186]
### 设备 / 浏览器
iPhone X

### Vant 版本
2.6.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsbin.com/lijusikata/edit?html,console,output" target="_blank">https://jsbin.com/lijusikata/edit?html,console,output</a>

### 描述问题
点击 checkbox 组件，在 model 改变状态之前，根据当时的 model 值来判断该按钮状态。不同版本更新 model 的时机可能不同，可查看 demo 点击复选框重现

**Comment by chenjiahan** [comment]
在 2.6.2 版本中修复了 Checkbox 在 click 事件的回调中获取到的 value 未改变的问题，所以会出现这个差异

参见更新日志：https://youzan.github.io/vant/#/zh-CN/changelog

**Comment by LTNSs** [comment]
谢谢大兄弟！
