### ISSUE TITLE
[Feature Request] Field  v-model (value)增加接收类型及增强表单验证及表单数据双向绑定

### ISSUE THREAD

**Issue by van-chin** [youzan/vant#6187]
### 这个功能解决了什么问题
1. Field 组件 v-model (value) 类型再现有的 number | string 之后增加boolean，有时是需要更多类型的
2. 增强表单验证相关的功能
3. 是否有计划能在表单上做数据绑定

### 描述您想要的解决方案
1.v-model (value) prop 增加一个boolean类型，或者any
2. 结合vee-validate 或 async-validator 增强表单验证
3. 表单数据绑定

### 建议的API是什么样的
暂无

**Comment by chenjiahan** [comment]
1. 参见 https://github.com/youzan/vant/issues/5613
2. 这个由开发者自行结合使用，不会内置
3. 暂无计划支持 Form 双向绑定
