### ISSUE TITLE
[Feature Request] 希望Toast.loading增加延迟显示的属性

### ISSUE THREAD

**Issue by lid1987** [youzan/vant#6188]
### 这个功能解决了什么问题
加载提示用在了请求后台接口前，如果请求时间很短，会出现加载提示闪一下的情况

### 描述您想要的解决方案
增加一个延迟多少时间再显示加载框的属性，如果在延迟时间内取消了加载框，则加载框不显示；如果超过延迟时间，再开始显示加载框

### 建议的API是什么样的
Toast.loading({
  message: '加载中...',
  delay: 500,   -----延迟500毫秒再显示
  loadingType: 'spinner',
});

**Comment by chenjiahan** [comment]
暂无计划在组件内提供，这个能力可以自己简单封装下
