### ISSUE TITLE
兄弟，Sketch文件再不更新我们的设计团队就要放弃vant了！！！！！

### ISSUE THREAD

**Issue by zhuyuqian** [youzan/vant#6191]
同标题。。。。
Sketch文件赶紧更新啊！！！！！
我们前端兄弟不想自己造轮子啊..........

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6164

**Comment by zhuyuqian** [comment]
卧槽，给力！回复的好快！！！好评！
