### ISSUE TITLE
Field字段能否colon 属性可配置

### ISSUE THREAD

**Issue by zhuangxiaohui** [youzan/vant#6192]
设备 / 浏览器
chrome

Vant 版本
2.7.1

Vue 版本
2.6.11

描述问题
Field字段能否colon 属性可配置，我自定义组件，不需要colon字段，但还是显示出来

**Comment by chenjiahan** [comment]
下个版本会加个

**Comment by chenjiahan** [comment]
已在 2.8.0 版本支持
