### ISSUE TITLE
[Feature Request] Collapse 折叠面板

### ISSUE THREAD

**Issue by WYDgits** [youzan/vant#6196]
### 这个功能解决了什么问题
我用List列表展示 图书名，然后使用Collapse 折叠面板点击触发，来查询图书的更多信息。

### 描述您想要的解决方案
collapse的activeNames感觉有点局限了，如果用手风琴模式，那我每点击一次图片，都要进行一次请求，如果用默认模式，数组形式也很难搞；
还有，就是这个组件触发函数有点少，我觉得可以加些其他函数

### 建议的API是什么样的
1.多加点触发函数
2.完善下下拉内容的选择，看能不能把手风琴模式和默认模式 折中一下

**Comment by chenjiahan** [comment]
没理解你提到的触发函数和折中是什么意思，给个具体的示例？

**Comment by WYDgits** [comment]
就是  触发事件 ，当前的Collapse Events只有一个 change，但是无法选取到相应元素的id；
手风琴模式和默认模式折中：activeNames不用数组形式，但是实现 默认模式的多个显示，每次触发change事件的时候，只把相应的 name 回调

**Comment by chenjiahan** [comment]
1. name 作为唯一标识符，与 id 是等价的
2. 暂时没有计划调整参数，你如果需要判断具体是哪个面板变化了，可以 watch v-model，并对比 oldVal 和 newVal
