### ISSUE TITLE
[Feature Request] card 商品卡片建议增加CheckBox

### ISSUE THREAD

**Issue by lovefox666** [youzan/vant#6199]
### 这个功能解决了什么问题
1、方便操作购物车选择结算的商品
2、删除选中商品

### 描述您想要的解决方案
card 商品卡片建议增加CheckBox

### 建议的API是什么样的
在card商品左侧，有checkbox

**Comment by chenjiahan** [comment]
暂无计划支持，可以使用插槽实现
