### ISSUE TITLE
[Feature Request] 商品双向联动列表

### ISSUE THREAD

**Issue by xzncit** [youzan/vant#6200]
### 这个功能解决了什么问题
商品双向联动列表、导航与列表双向联动组件，这种功能在开发web app时商城时基本每个商城都是需要这个功能的，希望能增加这个功能。

### 描述您想要的解决方案
可以像展示组件一样调用

### 建议的API是什么样的
可以像展示组件一样调用

**Comment by chenjiahan** [comment]
暂无计划支持
