### ISSUE TITLE
[Feature Request] 请务必增强对Picker异步列表数据的支持

### ISSUE THREAD

**Issue by aosnow** [youzan/vant#6201]
### 这个功能解决了什么问题
解决异步获取多列clumns数据后的正确显示children的values，目前不支持异步刷新

### 描述您想要的解决方案
目前picker只支持同步列表的设置，虽然有一个 loading，但仅仅只是视觉上给了个表现而矣。
真正的问题在于，picker只考虑了“不更改columns数据”的前提下，若change任何一列的选项，会立即根据“当前columns的chilren”立即应用修改的change index，问题就在于此，因为若于异步数据，此时列表的children根本还没有过来，一般只是个空数组或者只是个占位{name:'请选择'}对象。
功能的关键在于以下代码（node_modules/vant/es/picker/index.js 125-135行）：
```js
    onChange: function onChange(columnIndex) {
      if (this.dataType === 'cascade') {
        this.onCascadeChange(columnIndex); // 异步column的情况下这里不能立即执行，而应该watch.columns后执行
      }

      if (this.dataType === 'text') {
        this.$emit('change', this, this.getColumnValue(0), this.getColumnIndex(0));
      } else {
        this.$emit('change', this, this.getValues(), columnIndex);
      }
    }
```

### 建议的API是什么样的
不涉及到新的API，主要是完善和升级picker的change逻辑处理：
异步column的情况下这里不能立即执行，而应该watch.columns后执行，且若是如“省市区”的关联列的话，需要等最后一列完成后设置setColumnValues列的显示数据。
如此，比现有的Area组件更具质量和通用性，以上完善后Area可以考虑废弃。

**Comment by aosnow** [comment]
因此，异步多级联动目前的怪异效果如下：
1、设置初始columns（内部转换为values，并设置默认defaultIndex=0）
2、选项change，picker内部立即change(index)，显示当前选项和占位对象数据
3、外部接收到change，触发异步request拿取columns数据设置到目前的children替换占位数据
4、从外部刷新columns到picker，内部重新生成values结构，当前列后续defaultIndex都为0，如第一列change，效果就是第一列（往往columns不变动）保持不动，后续列全部使用item[0]的children导致显示错位，根本没有显示当前第一列的children

**Comment by aosnow** [comment]
目前我只能二次封装，在外部进行转换为{values}，来自行维护defaultIndex
1、在columns改变时，自行转换，并设置picker.getIndexes()的对应当前索引
2、在change时，又是按picker.getIndexes()对应列索引切换新的{values}
幸亏内部设置了 Object 类型可以直接绕过 formatter，否则只能眼巴巴等你们更新

**Comment by chenjiahan** [comment]
组件内置的级联选择是适用于同步场景的，异步场景建议还是通过实例方法去操作，比如 setColumnValues

**Comment by aosnow** [comment]
```js
    // 改进后的 fomatter
    formatCascade(val) {

      let indexes = [];
      const picker = this.$refs.picker;

      if (picker) indexes = picker.getIndexes();

      // 每次重新由 options 生成列数据，会导致运行时的 defaultIndex 永远指向 0
      // 即使加载了新的列的 children 数据，也只能永远显示每列的第 0 个子级
      // 需要想办法保留 defaultIndex 的运行时值，才能完整实现滚动到指定列，动态加载并显示指定列的子列
      const formatted = [];
      let cursor = { children: val };
      let step = 0;

      while (cursor && cursor.children) {
        // 关键在于此处，没有保留当前各列的 index，而你们维护的 index，都是与colums独立无绑定关系的 
        const defaultIndex = cursor.defaultIndex || (step < indexes.length ? indexes[step++] : 0);

        // 利用 Picker 的 values type 来设置选择集
        formatted.push({
          values: cursor.children.map((item) => {
            return item[this.labelKey];
          }),
          className: cursor.className,
          defaultIndex: defaultIndex
        });
        cursor = cursor.children[defaultIndex];
      }

      return formatted;
    }
```

**Comment by chenjiahan** [comment]
欢迎 PR 喔

**Comment by aosnow** [comment]
好的，有时间我改好推过去
