### ISSUE TITLE
请问官方网站的右边的demo示例有吗？

### ISSUE THREAD

**Issue by 285979593** [youzan/vant#6204]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
在每个组件的 demo 目录下：https://github.com/youzan/vant/tree/dev/src/button/demo

**Comment by 285979593** [comment]
嗯谢谢了
