### ISSUE TITLE
Actionsheet 没有设置默认选中的啊

### ISSUE THREAD

**Issue by LOADINGG** [youzan/vant#621]
如题~

**Comment by chenjiahan** [comment]
Actionsheet 没有选中状态喔，不知道你说的默认选中是什么样子

**Comment by LOADINGG** [comment]
编辑某个信息的时候要选中之前提交的值，而不是还是弹出Actionsheet还是选中的第一个~

**Comment by chenjiahan** [comment]
抱歉，不懂你说的选中是什么意思。。

**Comment by LOADINGG** [comment]
![default](https://user-images.githubusercontent.com/6230922/35958343-422f469e-0cdb-11e8-8bfa-95238438e6da.png)
设置默认选中女，而不是男，很难明白吗？

**Comment by chenjiahan** [comment]
亲，这是 Picker 组件，不是 Actionsheet
