### ISSUE TITLE
steps步骤条自定义样式时出现bug——颜色

### ISSUE THREAD

**Issue by MarioTed** [youzan/vant#6210]
我在使用步骤条组件时，自定义的颜色有bug，
 active-color="#38f" 该属性只能对当前的active生效，对已完成的圆角图标不起作用，任然是默认的绿色
![image](https://user-images.githubusercontent.com/46783216/80964968-58629f00-8e44-11ea-8672-351ac0d551a9.png)

**Comment by MarioTed** [comment]
如果有我没想到的解决办法还请告知，谢谢！

**Comment by yoruponder** [comment]
应该可以重写css解决

**Comment by chenjiahan** [comment]
下个版本会修复下

**Comment by chenjiahan** [comment]
已在 2.8.1 版本修复

**Comment by MarioTed** [comment]
谢谢
