### ISSUE TITLE
Calendar 建议在确定按钮旁边增加一个重置按钮

### ISSUE THREAD

**Issue by zjyau** [youzan/vant#6211]
Calendar 建议在确定按钮旁边增加一个重置按钮
因为用户的习惯是从弹出窗口设置,重置时,还在弹出窗口中重置
还有父页面没有再单独放一个重置按钮,浪费空间

**Comment by chenjiahan** [comment]
暂无计划支持呢，你可以使用 footer 插槽自定义

**Comment by zjyau** [comment]
非常感谢,没仔细看到文档中有footer
