### ISSUE TITLE
van-field左边图标大小不能定义

### ISSUE THREAD

**Issue by dream-lmc** [youzan/vant#6212]
van-field左边图标大小不能定义，如何解决 定义  大小

**Comment by chenjiahan** [comment]
直接通过 CSS 覆盖样式即可

**Comment by dream-lmc** [comment]
我覆盖了不起作用，不知道是什么情况，求指点，覆盖哪个class

**Comment by dream-lmc** [comment]
![image](https://user-images.githubusercontent.com/26358429/80978032-1c393980-8e58-11ea-9713-21405b33375e.png)
![image](https://user-images.githubusercontent.com/26358429/80978066-26f3ce80-8e58-11ea-9ed8-cef5f33f4d9c.png)
这样覆盖不起作用，求zhi指点。

**Comment by chenjiahan** [comment]
一般是这样用：

```html
<van-field class="my-field" />
```

```css
.my-field .van-icon {
  font-size: 16px;
}
```

**Comment by willenzheng** [comment]
同样有该问题，直接覆盖样式还是不行。
