### ISSUE TITLE
[Bug Report] van-tabs tab切换的时候没缓存位置

### ISSUE THREAD

**Issue by sll8233** [youzan/vant#6213]
### 设备 / 浏览器
chrome

### Vant 版本
2.7.1

### Vue 版本
3.0.0-beta.8

### 重现链接
<a href="http://localhost:8080/home" target="_blank">http://localhost:8080/home</a>

### 描述问题
van-tabs、 tab切换的时候没缓存之前滚动的位置，切换后都是默认最顶端，是我用的姿势不对吗

**Comment by chenjiahan** [comment]
Tab 组件没有缓存滚动位置的功能，建议自行实现
