### ISSUE TITLE
vue预渲染问题

### ISSUE THREAD

**Issue by xiaomun** [youzan/vant#6216]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

使用prerender-spa-plugin对VUE项目进行预渲染时，vant组件显示如正常显示？
问题表现为：1、van-icon无法显示
2、van-button  size="large"，但是渲染出来 有点像 迷你按钮

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
