### ISSUE TITLE
2.6.3版本，AddressList不显示tag默认标签

### ISSUE THREAD

**Issue by lichunze** [youzan/vant#6217]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by lichunze** [comment]
![image](https://user-images.githubusercontent.com/24243394/81099454-85df4380-8f3d-11ea-809d-52bc6e8a95e2.png)
![image](https://user-images.githubusercontent.com/24243394/81099503-9b546d80-8f3d-11ea-9a82-ed7eadedd30e.png)

**Comment by lichunze** [comment]
<img width="1253" alt="qq1" src="https://user-images.githubusercontent.com/24243394/81099721-eec6bb80-8f3d-11ea-9b7b-040f86592176.png">
<img width="663" alt="qq2" src="https://user-images.githubusercontent.com/24243394/81099726-f1c1ac00-8f3d-11ea-9402-28c5340d7bec.png">

**Comment by chenjiahan** [comment]
建议打开 node_modules/vant/package.json，确认下你安装的版本是否正确

**Comment by lichunze** [comment]
![image](https://user-images.githubusercontent.com/24243394/81176497-cee3d600-8fd7-11ea-9394-c35cd268feed.png)

**Comment by chenjiahan** [comment]
你的代码里没有设置 isDefault 字段

**Comment by lichunze** [comment]
原来是这样，感谢
