### ISSUE TITLE
pull-refresh

### ISSUE THREAD

**Issue by de1ck** [youzan/vant#622]
normal 默认>pulling 下拉>loosing 释放>loading 加载 > success 为什么不提供一个加载成功后的钩子呢
[vant website](https://www.youzanyun.com/zanui/vant#/zh-CN/component/pull-refresh)

**Comment by chenjiahan** [comment]
@de1ck 感谢反馈，目前可以通过 watch isLoading 来实现，后续我们会加个事件，更加直观些

**Comment by chenjiahan** [comment]
已在 0.12.9 中添加 refresh 事件
