### ISSUE TITLE
[Feature Request]能不能增加聊天组件啊

### ISSUE THREAD

**Issue by AnLiBoBo** [youzan/vant#6221]
自从用了vant后,感觉越来越好用,把自己都用懒了 哈哈哈哈..

color-ui 有一个聊天相关组件
https://github.com/weilanwl/ColorUI/

如果可以的话,我觉得考虑加个这样的组件
最好就是能支持多种消息类型,比如:文本,图片,语音,视频,红包... 这些

实在不想写了,坐等大佬们造轮子

**Comment by chenjiahan** [comment]
暂无计划支持哈，还是自己实现叭
