### ISSUE TITLE
[Bug Report] stepper组件的减事件处理有错误

### ISSUE THREAD

**Issue by myMengyou** [youzan/vant#6222]
### 设备 / 浏览器
chrome浏览器

### Vant 版本
2.6.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/mymengyou/pen/vYNdEZo" target="_blank">https://codepen.io/mymengyou/pen/vYNdEZo</a>

### 描述问题
例子：stepper组件的step设置为10，输入值为2。此时按减号按钮，值会变成8，而不是变成最小值的1 。
原因推测：从源码中可以看到，在进行减操作后，数据会被先转成了正数（负号被替换成空字符了）再和最小值比较。

**Comment by chenjiahan** [comment]
确实存在此问题，后续会修复下

**Comment by chenjiahan** [comment]
已在 2.8.1 版本修复
