### ISSUE TITLE
[Bug Report] less 6.0 自定义主题失败

### ISSUE THREAD

**Issue by dongsuo** [youzan/vant#6223]
### 设备 / 浏览器
All

### Vant 版本
2.7.1

### Vue 版本
2.6.10

### 重现链接
<a href="https://github.com/ant-design/ant-design/issues/23624" target="_blank">https://github.com/ant-design/ant-design/issues/23624</a>

### 描述问题
请忽略上面的重现链接。
less6.0.0 引入了breaking change，目前文档中的自定义主题配置会失败，具体描述参照：https://github.com/ant-design/ant-design/issues/23624

**Comment by chenjiahan** [comment]
欢迎提 PR 帮我们完善下文档
