### ISSUE TITLE
[Bug Report] 上传组件，上传多张图片时，图片上传的顺序是按照手机相册排序

### ISSUE THREAD

**Issue by NickYangZY** [youzan/vant#6226]
### 设备 / 浏览器
iPhone6s

### Vant 版本
2.2.12

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
手机上传多张图片时，图片上传的顺序是按照手机相册排序合理的逻辑应该是用户选择图片的顺序才对。希望能修改一下，谢谢！

**Comment by chenjiahan** [comment]
这个顺序是浏览器返回的，组件里无法决定顺序喔

**Comment by NickYangZY** [comment]
能否给个解决方案，我看看微信、微博他们的图片上传顺序都是按用户选择的顺序上传的，希望大神能挑战一下，不要直接就关闭了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 上午10:59
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"义行天下"<1083731887@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] 上传组件，上传多张图片时，图片上传的顺序是按照手机相册排序 (#6226)





 
这个顺序是浏览器返回的，组件里无法决定顺序喔

**Comment by chenjiahan** [comment]
微信、微博是原生 APP，跟 JS 能力不同
