### ISSUE TITLE
[Bug Report] 上传组件，上传多张图片时，图片上传的顺序是按照手机相册排序

### ISSUE THREAD

**Issue by NickYangZY** [youzan/vant#6227]
### 设备 / 浏览器
iPhone6s

### Vant 版本
2.2.12

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
手机上传多张图片时，图片上传的顺序是按照手机相册排序合理的逻辑应该是用户选择图片的顺序才对。望能修改一下，谢谢！（希望不要直接关闭我的issue，可以延后解决什么的）

**Comment by chenjiahan** [comment]
请勿重复创建 issue

https://github.com/youzan/vant/issues/6226
