### ISSUE TITLE
DatetimePicker 在oppo手机中点击确定无反应没找到原因希望团队看一下

### ISSUE THREAD

**Issue by zhaoqj008** [youzan/vant#6228]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater
最近做项目发现DatetimePicker 在OPPO手机下点击确定无反应，别的机型都可以不知道什么原因

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
