### ISSUE TITLE
Button组件Iphone文字显示不居中

### ISSUE THREAD

**Issue by LH040707** [youzan/vant#6231]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以试下 2.8.1-beta.0 版本

**Comment by LH040707** [comment]
> 已经修复了，可以试下2.8.1-beta.0版本

好的,谢谢

**Comment by chenjiahan** [comment]
已发布 2.8.1 正式版

**Comment by LH040707** [comment]
> 已发布2.8.1正式版
iPhone6 版本 10.3.2 存在bug

**Comment by lhaiqing** [comment]
可以在样式文字添加
    /deep/ .van-button__text {
        margin: 0 auto;
    }

**Comment by chenjiahan** [comment]
@LH040707 参见 https://github.com/youzan/vant/issues/6307
