### ISSUE TITLE
[Bug Report] 中文文档 图片预览组件描述错误

### ISSUE THREAD

**Issue by yykb** [youzan/vant#6233]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.0

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/image-preview#han-shu-diao-yong" target="_blank">https://youzan.github.io/vant/#/zh-CN/image-preview#han-shu-diao-yong</a>

### 描述问题
文档中，图片预览 - 函数调用部分引入组建错误
import { Dialog } from 'vant';  应为 import { ImagePreview } from 'vant';

**Comment by chenjiahan** [comment]
可以提个 PR 帮忙修正下哈

**Comment by chenjiahan** [comment]
已修正
