### ISSUE TITLE
[Feature Request] 希望滑块能支持范围选择，并且支持在滑块下方显示刻度值

### ISSUE THREAD

**Issue by badongdyc** [youzan/vant#6234]
### 这个功能解决了什么问题
能选择数值区间，并且在滑块下方显示具体的刻度值

### 描述您想要的解决方案
比如我想选择一个数值区间，例如50-100

### 建议的API是什么样的
能选择数值区间，并且在滑块下方显示具体的刻度值

**Comment by badongdyc** [comment]
参考element ui
![1](https://user-images.githubusercontent.com/17975624/81278491-52f59680-9088-11ea-9c2e-86e3657d584d.png)

**Comment by chenjiahan** [comment]
刻度暂时没有计划支持喔，区间后续会支持，参见 https://github.com/youzan/vant/issues/3503

**Comment by babydada** [comment]
支持了吗，我怎么好像钱几天看到了，今天突然没了

**Comment by chenjiahan** [comment]
目前还没支持喔
