### ISSUE TITLE
希望代码示例中增加一个code playground方便在线修改

### ISSUE THREAD

**Issue by tcmdxc430** [youzan/vant#6235]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划添加喔，可以使用 codesandbox

https://codesandbox.io/s/m5v3f
