### ISSUE TITLE
[Bug Report] vant-field 组件提供点击van-field__value才触发的一个事件方法

### ISSUE THREAD

**Issue by fengyun2** [youzan/vant#6239]
### 设备 / 浏览器
小米8/自带浏览器

### Vant 版本
2.5.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-h85gu?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-h85gu?file=/src/App.vue</a>

### 描述问题
我希望只有点击Input区域才捕获某个事件，并且 vant-field同时含有这两个属性`readonly`, `clickable`，只是为了防止页面需要滚动时，很容易触发 vant-field 的 `click` 事件。
![image](https://user-images.githubusercontent.com/8147202/81317867-fada8680-90bf-11ea-9e78-a728cc1d3e94.png)

**Comment by chenjiahan** [comment]
可以加一个点击输入框的事件

**Comment by chenjiahan** [comment]
已在 2.8.1 版本新增 click-input 事件，可以试下
