### ISSUE TITLE
[Feature Request] van-form 监听到回车事件会自动提交

### ISSUE THREAD

**Issue by caoxqian** [youzan/vant#6240]
<van-form @submit="onSubmit">，van-form定义了submit事件后，按回车键会自动提交submit方法，如何屏蔽回车事件，element UI 的做法是 在form表单中加入@submit.native.prevent，不知道 Vant UI 有没有类似的做法

**Comment by chenjiahan** [comment]
submit.prevent 没用的，要在 Field 里 prevent 回车的 keypress 事件，下个版本会处理下

**Comment by chenjiahan** [comment]
已在 2.8.1 版本处理

**Comment by mudoo** [comment]
这个处理有点不妥吧，默认form交互就是在input里按回车就提交，field里强制preventDefault，那不是怎么都无法实现回车提交了

**Comment by mudoo** [comment]
我说怎么就无法回车登录了，原来是版本升了导致的。
 @chenjiahan 这个还是再斟酌下吧，input回车保持跟原生一致没什么不对，并不是BUG。
有问题的是form那边，因为form元素绑定了onSubmit，而且preventDefault了，所以外面无法阻止提交

**Comment by chenjiahan** [comment]
@mudoo Vant 是移动端组件库，在移动端的键盘中不存在回车按钮（在 iOS 中默认为右下角换行按钮），点击“换行”显然不应该触发表单提交

**Comment by mudoo** [comment]
@chenjiahan 我看了下iOS，text是换行，password的是return，会触发submit
而且安卓是支持切换到下一个字段，最后个字段会触发submit，移动端也是有这些基础操作支持的，比较人性化

**Comment by chenjiahan** [comment]
参考了一下 Ant Design 的[说明](https://github.com/ant-design/ant-design/issues/10861)，默认情况下回车事件确实应该触发表单提交，下个版本会调整下。

另外下个版本会加一个开关属性 submitOnEnter，用于禁用这个行为。

**Comment by chenjiahan** [comment]
已在 2.8.3 版本调整

**Comment by hzyyy** [comment]
最新：IOS 14.2 系统键盘换行，也会触发form表单的提交。
