### ISSUE TITLE
[Bug Report] CountDown 倒计时 自定义样式， 示例  style 中 .item 应改为 .block

### ISSUE THREAD

**Issue by cokery** [youzan/vant#6244]
### 设备 / 浏览器
MS/Edge

### Vant 版本
2.8.1-beta.0

### Vue 版本
3.0.0-beta.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/count-down" target="_blank">https://youzan.github.io/vant/#/zh-CN/count-down</a>

### 描述问题
CountDown 倒计时 自定义样式， 示例  style 中 .item 应改为 .block

**Comment by chenjiahan** [comment]
欢迎提 PR 帮我们修正~

**Comment by chenjiahan** [comment]
已修正👌

**Comment by cokery** [comment]
中文版的没改动呢

**Comment by chenjiahan** [comment]
站点刚部署，可以刷新看下
