### ISSUE TITLE
nuxt下的axios封装的响应拦截器中无法使用Toast

### ISSUE THREAD

**Issue by guoxiangdejian** [youzan/vant#6247]
// 添加响应拦截器
instance.interceptors.response.use(function (response) {
  console.log('response:'+response.data.code)
  let response_code = response.data.code;
  if (response_code != 200) {
    Toast(response_code)  //问题所在，不显示轻提示
  }
  return response.data;
}, function (error) {
  console.log(error.response.status)
  Vue.prototype.$toast(error.message);
  // Vue.prototype.$toast(error.response.status);
  return Promise.reject(error);
});

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by wangbaiwang** [comment]
你好，这个问题找到解决办法了吗？

**Comment by guoxiangdejian** [comment]
> 你好，这个问题找到解决办法了吗？

因为发送请求时是服务端渲染，不存在window对象，所以不能使用toast提醒。
