### ISSUE TITLE
钉钉微应用ios下多层Popup弹出 内容不显示 好像有点遮挡住了，遮罩层也不见了

### ISSUE THREAD

**Issue by zhanggaoke** [youzan/vant#6248]
设备 / 浏览器
ios
Vant 版本

2.8.1
Vue 版本

3.0.0-beta.10

描述问题

钉钉微应用ios下多层Popup弹出 内容不显示 好像有点遮挡住了，遮罩层也不见了。 安卓没这个问题

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
