### ISSUE TITLE
[Feature Request] NoticeBar 考虑支持多消息轮播显示

### ISSUE THREAD

**Issue by jacky8466** [youzan/vant#6249]
### 这个功能解决了什么问题
通知消息有多条时，可以上下滚动显示，类似Swipe 轮播组件的上下滚动，但两者不冲突

### 描述您想要的解决方案
可以新增轮播属性，显示的条数，停留时间等属性

### 建议的API是什么样的
direction:vertical
display-count:5

**Comment by chenjiahan** [comment]
暂无计划支持喔，可以使用 Swipe 实现
