### ISSUE TITLE
[Bug Report] van-form 标签内 有2个按钮，都会导致触发submit

### ISSUE THREAD

**Issue by Dcell** [youzan/vant#6250]
### 设备 / 浏览器
google

### Vant 版本
2.8.1

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-0648j?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-0648j?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
            <div class="btns">
                <van-button round block type="info" @click="onClickLeft" size="small">上一步</van-button>
                <van-button round block type="info" native-type="submit" size="small">提交</van-button>
            </div>
        </van-form>

点击上一步也会触发 submit

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/form#dian-ji-biao-dan-zhong-de-pu-tong-an-niu-wei-shi-me-hui-chu-fa-biao-dan-ti-jiao

**Comment by fengmumu1** [comment]
https://juejin.cn/post/6894496489905930253
手动指定submit的类型
