### ISSUE TITLE
[Feature Request] 新 Picker 组件的相关建议

### ISSUE THREAD

**Issue by Airkro** [youzan/vant#6251]
根据 [Vant 2020 年上半年开发计划](https://github.com/youzan/vant/issues/5565) 中对 Picker 的意见整理如下：

#### 表单场景的使用过于复杂

目前要在表单当中使用 Picker ，参考[官方示例](https://youzan.github.io/vant/#/zh-CN/picker#da-pei-dan-chu-ceng-shi-yong)，需要连接三个组件 （Popup 和 Fields），处理状态联动与还原。如果一个页面有多个picker，问题会更明显。即便是自行封装成一个组件，也存在很多问题，例如在如何 Form 当中使用等等。（datepicker也有一样的问题）

#### 赋值与联动的处理困难

目前要进行赋值操作，不支持 v-model，不仅要使用 `setValues()/setIndexes()/setColumnValue()` 等等的API，要对 value 和 index 进行相互转换。如果涉及联动，还需要进行递进的操作，增加了使用成本。

相关问题：https://github.com/youzan/vant/issues/5905 ，https://github.com/youzan/vant/issues/6201 ，https://github.com/youzan/vant/issues/5565

### 描述您想要的解决方案
提供一个新的组件，与现有的 Picker 不同，新的 Picker 整合 Popup 和 Fields，成为一个新的组件。外观与 Fields 一致，无需人为处理显示的逻辑，Popup 关闭时，未确认的选择会被还原（类似PC版Antd）。

与此同时发挥 vue 组件数据绑定便利的特点， 提供更容易使用的 API：消除 index 的存在感你，完全使用 v-model 赋值。多级选项应自动进行联动，父级被选择时，自动替换子级选项。

### 建议的API是什么样的
假定新的 Picker 命名为 Selector，则：

```vue
<template>
  <van-selector v-model="value" :options="options" />
</template>

<script>
export default {
  data() {
    return {
      options: [2013, 2014, 2015, 2016, 2017, 2018],
      value: 2016,
    }
  }
};
</script>

<script>
const options = [
  {
    value: '110000',
    label: '北京市',
    child: [
      { value: '110101', label: '东城区' },
      { value: '110102', label: '西城区' }
    ]
  },
  {
    value: '120000',
    label: '天津市',
    child: [
      { value: '120101', label: '和平区' }
    ]
  }
];

export default {
  data() {
    return {
      options,
      value: ['120000', '120101'],
    }
  }
};
</script>
```

参考对象： 

- https://didi.github.io/cube-ui/#/zh-CN/docs/select
- https://didi.github.io/mand-mobile/#/zh-CN/docs/components/feedback/selector
- https://ant.design/components/select-cn/
- https://ant.design/components/cascader-cn/

如果官方团队愿意，或许不必不替换现有 picker ，而是提供一个新的组件（本身差异也很大）。也就不必等到 3.0 版本提供。毕竟 vue 3 和 vant 3 的大范围应用肯定还需要很长时间，而现有的 Picker 组件的开发体验十分有限。

**Comment by chenjiahan** [comment]
提供这样的组件是可行的，但相比与自行组装组件，灵活度会低很多。

Picker/Field/Popup 三个组件加起来有 60 多个 props，在这个组件中显然不可能提供这么多 props，那就势必会降低组件本身的可定制化程度。

**Comment by Airkro** [comment]
或许可以考虑基于插槽或其他方式的解决方案，而非单纯地把组件封装到一起。目前自行封装的问题就是，外面要套一个div，用于显示的层用 Field 和 Cell 都可以（官方这样做了，我自己很多时候也会这样），又被 Form 和 CellGroup 影响了布局和逻辑。

Field 的 input 插槽很是相当好的思路，或许能从这个方向走。如果封装能更加无痛，就不需要整合了

**Comment by chenjiahan** [comment]
明白你的意思了，如果是为了解决 Cell 边框显示的问题，我们下个版本会加个插槽来解决

**Comment by chenjiahan** [comment]
已在 2.8.2 版本增加 extra 插槽，用法示例：

```html
<van-field>
  <van-popup
    v-model="showPicker"
    slot="extra"
    position="bottom"
    get-container="body"
  >
    <van-picker  />
  </van-popup>
</van-field>
```

这样可以比较低成本地解决 Cell 边框的问题

Picker API 的话放到 3.0 版本再优化把~

**Comment by Airkro** [comment]
实际使用的效果不错，解决了一些问题，建议在文档中优先使用这个方法。

但几个插槽的命名上还是怪怪的，不直观，3.0可以考虑改改

**Comment by chenjiahan** [comment]
有什么命名建议吗

**Comment by Airkro** [comment]
这个 field 的 extra 插槽和 input 插槽的差异就很不直观，如果去比较 cell 的 extra 插槽就更乱了

**Comment by chenjiahan** [comment]
Field 的 extra 插槽和 Cell 的 extra 插槽是等价的，你说的差异指的是？

**Comment by Airkro** [comment]
认真检查了一遍确实是等价的，看来是搞错了，抱歉

**Comment by chenjiahan** [comment]
👌
