### ISSUE TITLE
[Bug Report] Button组件Iphone文字显示不居中

### ISSUE THREAD

**Issue by LH040707** [youzan/vant#6252]
### 设备 / 浏览器
iPhone6 版本 10.3.2

### Vant 版本
2.8.1

### Vue 版本
2.6.1

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-43jmb" target="_blank">https://codesandbox.io/s/vant-issue-moban-43jmb</a>

### 描述问题
iPhone6 版本 10.3.2 按钮文字不居中

**Comment by chenjiahan** [comment]
截图看下？

**Comment by chenjiahan** [comment]
只有 iphone6 这样吗？ 能否提供截图看下

**Comment by candyAndBella** [comment]
不只是Button，Dialog组件也是，按钮全部居左

**Comment by chenjiahan** [comment]
未复现这个问题，建议你看下是不是被其他全局样式影响了

另外 Button 是基于 flex 布局的，可以看下 autoprefixer 的配置是否正确

**Comment by 13751139402** [comment]
我也遇到了这个问题 iPhone6 版本整体按钮全部居左了

**Comment by chenjiahan** [comment]
@13751139402 升级 2.8.3 版本即可
