### ISSUE TITLE
[Bug Report] unexist children property of Field instance

### ISSUE THREAD

**Issue by hq229075284** [youzan/vant#6255]
### 设备 / 浏览器
chrome

### Vant 版本
2.6.3

### Vue 版本
2.6.11

### 重现链接
无

### 描述问题
https://github.com/youzan/vant/blob/09fdde8c56903030692544c12a97b299701d8de1/src/field/index.js#L134-L139
在Field.js中，实例上什么时候会存在children属性？
***
https://github.com/youzan/vant/blob/09fdde8c56903030692544c12a97b299701d8de1/src/field/index.js#L135-L137
如果意图是获取子组件的value属性的话，直接判断$scopedSlots.input和$slots.input就可以了

**Comment by chenjiahan** [comment]
子组件会通过 FieldMixin 注入 children 到 Field 上。

直接获取 $scopedSlots.input.value 不可靠，比如以下情况

```html
<van-field name="checkbox" label="复选框">
  <template #input>
    <div>
      <van-checkbox v-model="checkbox" shape="square" />
    </div>
  </template>
</van-field>
```
