### ISSUE TITLE
[Feature Request] Popup弹出层增加标题栏

### ISSUE THREAD

**Issue by Twining** [youzan/vant#6257]
### 这个功能解决了什么问题
Popup没有标题栏，自己写的标题栏想要跟随滚动的fixed效果与本身充突，使用Sticky也是。

### 描述您想要的解决方案
增加自带标题栏，另外关闭按钮也可整合进去。

### 建议的API是什么样的
title="标题"

**Comment by chenjiahan** [comment]
暂无计划支持喔，标题栏直接写在 Popup 内就行，滚动不会有什么冲突的，内部搞个局部滚动的容器就可以

**Comment by Twining** [comment]
有道理，是我自己想岔了
