### ISSUE TITLE
[Feature Request] list 组件长列表渲染性能怎么样？是否支持虚拟列表渲染？

### ISSUE THREAD

**Issue by lgw42032** [youzan/vant#6258]
### 这个功能解决了什么问题
移动端长列表渲染优化

### 描述您想要的解决方案
list 组件下拉加载更多，页面会生成越来越多的dom，重绘成本比较高，是否支持虚拟列表优化？

### 建议的API是什么样的
支持长列表渲染优化

**Comment by chenjiahan** [comment]
List 不支持虚拟列表，也暂时没有计划支持喔

**Comment by Sirros** [comment]
> List 不支持虚拟列表，也暂时没有计划支持喔

不打算支持出于什么考虑哦

**Comment by chenjiahan** [comment]
虚拟滚动需要引入比较复杂的计算逻辑，Vant 的 List 组件是轻量级实现，没有计划支持这样的复杂功能。
