### ISSUE TITLE
[Bug Report] NumberKeyboard和PasswordInput组合使用时，快速输入时密码框无法及时响应

### ISSUE THREAD

**Issue by DanielYu8899** [youzan/vant#6259]
### 设备 / 浏览器
Android/iOS

### Vant 版本
2.8.1

### Vue 版本
3.0.0-beta.10

### 重现链接
<a href="https://youzan.github.io/vant/#/en-US/password-input" target="_blank">https://youzan.github.io/vant/#/en-US/password-input</a>

### 描述问题
官网示例即可重现。
当NumberKeyboard和PasswordInput组合使用时，快速输入时密码框无法及时响应：
比如快速点击键盘上的1、2、3、4、5、6键，密码框却只能显示前3个键，似乎密码框的响应有延时。

**Comment by chenjiahan** [comment]
NumberKeyboard 监听的就是普通的 click 事件，建议你看下是不是因为在 UIWebView 内有 300ms 延迟

**Comment by DanielYu8899** [comment]
> NumberKeyboard 监听的就是普通的 click 事件，建议你看下是不是因为在 UIWebView 内有 300ms 延迟

是的，300ms延迟的问题。

**Comment by jiyingzhi** [comment]
> NumberKeyboard 监听的就是普通的 click 事件，建议你看下是不是因为在 UIWebView 内有 300ms 延迟

应该不是这个问题，300ms 延迟是混合使用 click 和 touch 事件才会出现的吧，而且我做了处理，去除了 300ms 延迟，还是有这个问题

**Comment by jiyingzhi** [comment]
> NumberKeyboard 监听的就是普通的 click 事件，建议你看下是不是因为在 UIWebView 内有 300ms 延迟

看了一下代码，NumberKeyboard 监听的 touch 事件，应该不是这个原因
