### ISSUE TITLE
[Bug Report] vant-field textarea 不能换行,回车无效

### ISSUE THREAD

**Issue by zhaogaolei** [youzan/vant#6261]
### 设备 / 浏览器
pc / 手机 浏览器

### Vant 版本
2.8.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-sw6w6?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-sw6w6?file=/src/App.vue</a>

### 描述问题
vant-field textarea 不能换行,回车无效

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.8.2 版本修复
