### ISSUE TITLE
[Bug Report] list下拉刷新不能释放

### ISSUE THREAD

**Issue by mengyu8941** [youzan/vant#6262]
### 设备 / 浏览器
android手机下的QQ浏览器

### Vant 版本
2.8.1

### Vue 版本
3.0.0-beta.12

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/list" target="_blank">https://youzan.github.io/vant/#/zh-CN/list</a>

### 描述问题
最新版本android手机下的QQ浏览器，list和下拉刷新组合使用，一下拉就卡住了，不能释放刷新。官网上的例子就有此问题。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3225

**Comment by mengyu8941** [comment]
> 参见 #3225
跟#3225不是一回事，我没有滑动到浏览器窗口的外面，就是android的QQ浏览器无法使用，卡顿和不回弹刷新，你们需要仔细测测和改进！

**Comment by chenjiahan** [comment]
我这边的华为手机是可以正常回弹刷新的呢，你可以换个手机试试？

**Comment by mengyu8941** [comment]
必须是QQ浏览器，下拉刷新+列表的不能回弹，多试几次，很容易重现的。

**Comment by chenjiahan** [comment]
能录个视频看下吗
