### ISSUE TITLE
[Feature Request]NumberKeyboard 可否有两个extra-key

### ISSUE THREAD

**Issue by llystar** [youzan/vant#6264]
### 这个功能解决了什么问题
Field中type=“number”渲染成html是inputmode=decimal，这在IOS中只能调出带"."的键盘，而没有负号。需要输入负值的场景就让人觉得很难受。需要vant的NumberKeyboard的支持。
### 描述您想要的解决方案
需要NumberKeyboard支持"."和"-"两个extra-key。
参考功能：https://github.com/woheduole/EBCustomControls

**Comment by chenjiahan** [comment]
两个 extra-key 放不下唉

**Comment by llystar** [comment]
https://github.com/llystar/test/blob/master/issue.png
自己魔改了下css，不知类似这样的布局是否可行？

**Comment by chenjiahan** [comment]
左图是可以的，右图显然不行

**Comment by llystar** [comment]
不知是否有机会，在用户选择左图这种形式（带右侧栏的键盘）的情况下，支持第二个extra-key？

**Comment by llystar** [comment]
https://github.com/llystar/test/blob/master/issue2.png

**Comment by chenjiahan** [comment]
左图这种应该可以支持，我们评估下

**Comment by chenjiahan** [comment]
已在 2.8.2 版本支持定义两个 extra-key（在 custom theme 下）
