### ISSUE TITLE
[Bug Report] 多文件上传部分机型只能一张一张选择上传

### ISSUE THREAD

**Issue by YQmomo** [youzan/vant#6267]
### 设备 / 浏览器
华为P30，mate30pro等

### Vant 版本
2.0.0-beta.3

### Vue 版本
2.6.10

### 重现链接
<a href="http://guominghtml.yuuwei.com" target="_blank">https://github.com/youzan/vant/issues/6267</a>

### 描述问题
多文件上传，部分机型只能一张一张选择上传，希望可以像浏览器一样一次性可以选择多个上传（链接不方便提供，需要账户密码，应该很好复现）

**Comment by chenjiahan** [comment]
multiple 是浏览器原生属性，是否支持多选是由系统决定的呢，组件里是没法控制的
