### ISSUE TITLE
tab吸顶是否可以吸到指定元素的底部，而不是屏幕的顶部？

### ISSUE THREAD

**Issue by wh469012917** [youzan/vant#6268]
比如我做一个直播页面，希望上面是视频，下面是一个tab用来用户发聊天 评论等等，但是目前tab配置吸顶默认会吸到屏幕顶部，这就使得tab里面内容多了之后上下滑动tab会跑到顶部上去，体验很不好

**Comment by chenjiahan** [comment]
可以使用 offset-top 属性

**Comment by LongYue9608** [comment]
@chenjiahan offset-top 能否支持vw

**Comment by chenjiahan** [comment]
@LongYue9608 后续会支持下
