### ISSUE TITLE
[Bug Report] ios 13.4 长按图片识别异常突出

### ISSUE THREAD

**Issue by wangchunhai818** [youzan/vant#6269]
### 设备 / 浏览器
IOS 13.4 / 微信内置浏览器

### Vant 版本
2.6.3

### Vue 版本
2.6.10

### 重现链接
<a href="https://wangchunhai.com/games/22" target="_blank">https://wangchunhai.com/games/22</a>

### 描述问题
IOS系统升级到13.4版本后，van-popup弹出框中有普通图片或者二维码图片，长按会触发手机系统识别功能，导致无法触发微信的识别图片功能，期望提供一个解决思路或者方法，感谢！

**Comment by chenjiahan** [comment]
这个是系统和 App 层面的问题，估计要等微信适配，可以参考这个链接：https://developers.weixin.qq.com/community/develop/doc/00028ae6fec0c06b654ae5a185b000

**Comment by wangchunhai818** [comment]
好的，感谢
