### ISSUE TITLE
Uploader上传组件不可以默认展示多个选择框 只能展示一个 上传之后才能展示下一个

### ISSUE THREAD

**Issue by ink6** [youzan/vant#6275]
Uploader上传组件我想默认的时候展示三个选择框而不是选择一个之后再出现第二个 不知道该如何配置

**Comment by wuxinzhe097** [comment]
我也遇到了这样的问题，希望可以解决

**Comment by chenjiahan** [comment]
这个效果有点怪，你可以使用 for 循环生成多个 Uploader 组件来实现这个效果

**Comment by ink6** [comment]
有时候 我需要上传 身份证正面 反面 手持证件照 类似于这种情况需要默认展示三个
