### ISSUE TITLE
[Bug Report] 自定义弹窗中使用Swipe组件出现样式错误~~！

### ISSUE THREAD

**Issue by Wlisfes** [youzan/vant#6278]
### 设备 / 浏览器
Google Chrome 81.0.4044.138（正式版本） （64 位）

### Vant 版本
2.8.1

### Vue 版本
2.6.1

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-n29m6?file=/src/App.vue:1184-1189" target="_blank">https://codesandbox.io/s/vant-issue-moban-n29m6?file=/src/App.vue:1184-1189</a>

**Comment by Wlisfes** [comment]
补充 https://codesandbox.io/s/vant-issue-moban-n29m6?file=/src/App.vue

**Comment by chenjiahan** [comment]
对于 Swipe 组件来说，外层容器的宽度变化是无感知的，所以做不到在动画结束后自动更新 Swipe 宽度

你可以在动画结束后主动调用 Swipe 的 resize 方法
