### ISSUE TITLE
修改地址时，怎么设置默认值 

### ISSUE THREAD

**Issue by StriveTeam** [youzan/vant#628]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
可以使用 `address-info` 这个 prop，传入一个默认地址数据对象
