### ISSUE TITLE
[Bug Report] radio在popup上失效

### ISSUE THREAD

**Issue by iyaq** [youzan/vant#6281]
### 设备 / 浏览器
微信开发者工具

### Vant 版本
2.8.1

### Vue 版本
3.0.0-beta.12

### 重现链接
<a href="http://wechat.gubangjiaoyu.com/#/home" target="_blank">http://wechat.gubangjiaoyu.com/#/home</a>

### 描述问题
进入点击第一个课程，点击购买会弹出popup，popup上有规格选择   规格用单选框不起作用，吧文档的demo复制到popup里面 还是不起作用，正常页面radio正常

**Comment by chenjiahan** [comment]
麻烦给个 codesandbox 复现链接

**Comment by iyaq** [comment]
https://codesandbox.io/s/clever-mclaren-ku6o5?file=/src/components/HelloWorld.vue
   不太会用这个  我把代码写上去了   好像模拟不了移动端

**Comment by chenjiahan** [comment]
上面的链接里，Radio 是可以正常使用的，建议你看下是不是用法有问题

**Comment by leite-nie** [comment]
我也遇到同样的问题，在popup 里面引入 van-radio-group 点击单选按钮会失效。 不放在popup里面ok
