### ISSUE TITLE
type 设置为range，能否支持只选一天，即为开始日期也为结束日期

### ISSUE THREAD

**Issue by garfield02** [youzan/vant#6283]
<van-calendar type="range"></van-calendar> 时间选择组件，如果设置了 range，不能只选单个日期~ 有什么方法能兼容只选一个日期作为区间吗？ 选择同一天作为区间也是符合业务场景的吧~ 能否支持呢？

**Comment by chenjiahan** [comment]
设置 allow-same-day 属性即可

**Comment by garfield02** [comment]
> 设置 allow-same-day 属性即可

好的，谢谢！不好意思，是我没认真看文档，打扰了！

**Comment by JoyZ-nineteen** [comment]
> 设置 allow-same-day 属性即可

设置成allow-same-day后 :show-confirm="false"快捷选择，选择一天不能确认

**Comment by chenjiahan** [comment]
@JoyZ-nineteen 快捷选择选择一天没法确认，目前没有这个交互
