### ISSUE TITLE
[Bug Report] NumberKeyboard 数字键盘 控件，居然要求当前输入值是String；

### ISSUE THREAD

**Issue by hzyyy** [youzan/vant#6284]
### 设备 / 浏览器
macos chrome 84.0

### Vant 版本
2.8.1

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-uv69z?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-uv69z?file=/src/App.vue</a>

### 描述问题
吐槽：NumberKeyboard 数字输入控件，居然要求传入的数据格式是String。因为在很多业务场景当中，涉及到这个控件的基本都是一些金额输入和数量的输入；否则我每次使用这个控件，都需要提前转换格式成String，调用接口保存时；还得进行一次格式转换。

**Comment by chenjiahan** [comment]
NumberKeyboard 是可以自定义 Key 的，里面除了数字，还可能出现各种符号，所以输出只能是 String。

格式转换一下也不会很麻烦的
