### ISSUE TITLE
dropdownMenu 会关闭Popup 弹出层 overlay

### ISSUE THREAD

**Issue by zhuangxiaohui** [youzan/vant#6288]
设备 / 浏览器
chrome

Vant 版本
v2.8.1

Vue 版本
2.6.11

描述问题

在Popup  下的dropdownMenu 会关闭Popup 弹出层 overlay
![image](https://user-images.githubusercontent.com/5791725/82108187-59a69c80-975f-11ea-988f-93b961d2f920.png)

**Comment by chenjiahan** [comment]
由于多个 Overlay 叠加会导致颜色过深，在 Vant 里所有弹层组件是共用一个 Overlay 的。

你的情况看起来比较诡异，没太理解你的布局是什么样子的，能提供个 codesandbox 复现链接看下么

**Comment by zhuangxiaohui** [comment]
![image](https://user-images.githubusercontent.com/5791725/82185980-aa172900-991c-11ea-97dc-a011d88e5d39.png)
codesandbox ：https://codesandbox.io/s/vant-issue-moban-09bzl
已经补充codesandbox ，你看你那边能复现吗？还是我写代码错误

**Comment by JohnieXu** [comment]
@chenjiahan @zhuangxiaohui 我把 codesandbox 例子本地跑了下，确实发现有 bug

![May-19-2020 10-38-26](https://user-images.githubusercontent.com/21156871/82278531-05005d00-99bd-11ea-94e9-036703ccbb3a.gif)

**Comment by chenjiahan** [comment]
要解决这个问题，得为每个弹窗创建一个 Overlay 遮罩层，近期会尝试下

**Comment by chenjiahan** [comment]
已在 2.8.4 版本修复

**Comment by JohnieXu** [comment]
处理得很快👍
