### ISSUE TITLE
建议Toast.loading 增加一个 loading关闭api

### ISSUE THREAD

**Issue by celverbamboo** [youzan/vant#629]
如果只有Toast.clear(),会把全部Toast都给关闭，有些业务情况需要，单独关闭loading或者Toast提示信息.
比如这个，我只想关闭loading，但却关闭全部提示信息。
![效果图](https://i.loli.net/2018/02/09/5a7d39abf29f5.png)

**Comment by chenjiahan** [comment]
可以使用 Toast.allowMultiple

**Comment by celverbamboo** [comment]
@chenjiahan 好的，个人还是觉得不要控制同一个Toast比较好。这样子比较灵活
