### ISSUE TITLE
search组件问题反馈

### ISSUE THREAD

**Issue by niexiaozhou** [youzan/vant#6294]
目前使用vant 2.8.2版本, 使用search组件时 使用自动获取焦点，安卓设备有概率不触发。于是用 直接操作dom或者ref属性直接操作该元素触发focus事件，键盘会被拉起，安卓设备上正常，ios会把整个页面顶起来，本次反馈主要不是这个问题，回到上句话，触发focus之后，如果不做任何输入或者其他处理，直接做路由返回，返回后的页面 并无input 元素，但是会出现页面被截掉半屏的情况，多次测试后证明是跳转前的search组件触发了focus，但在离开时没有触发blur，没有收起键盘导致，于是触发了该元素的blur，兄弟/父级元素的click事件、以及body.blur()/body.click()等，都无法触发blur，无法收起键盘，但是在移动设备内vconsole内可以触发对应代码，也会收起键盘.目前暂无好的解决方式，我在返回后出发了路由刷新，用以解决该问题。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
