### ISSUE TITLE
dialog组件在ios11上的兼容问题

### ISSUE THREAD

**Issue by ywlang** [youzan/vant#6295]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by ywlang** [comment]
在vue开发的微信h5网页中使用dialog的confirm时，偶尔弹出框会从屏幕偏左下角位置弹出，再到屏幕中间

**Comment by xiaoyudesu** [comment]
同样发现了这个问题
