### ISSUE TITLE
[Bug Report] 在kbone模板中引用，编译到小程序代码后，组件不显示

### ISSUE THREAD

**Issue by chenp1204** [youzan/vant#6302]
### 设备 / 浏览器
微信小程序开发者工具

### Vant 版本
2.8.2

### Vue 版本
2.6.10

### 重现链接
无

### 描述问题
在kbone模板中引用，编译到小程序代码后，组件不显示

**Comment by chenjiahan** [comment]
Vant 没有专门适配 kbone，使用有问题请到 kbone 仓库下创建 issue 喔
