### ISSUE TITLE
[Bug Report] field type=digit时可以输入字符串'123-123'

### ISSUE THREAD

**Issue by weiyuc** [youzan/vant#6305]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.2

### Vue 版本
3.0.0-beta.14

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/field" target="_blank">https://youzan.github.io/vant/#/zh-CN/field</a>

### 描述问题
field type=digit时可以输入字符串'123-123'，需要校验减号只能出现在第一位

**Comment by chenjiahan** [comment]
已发布 2.8.3 版本
