### ISSUE TITLE
[Bug Report] 设计资源下载不了

### ISSUE THREAD

**Issue by vevina123** [youzan/vant#6306]
### 设备 / 浏览器
Chrome、Safari

### Vant 版本
2.8.2

### Vue 版本
3.0.0-beta.14

### 重现链接
<a href="https://raw.githubusercontent.com/youzan/vant/dev/docs/assets/design.sketch" target="_blank">https://raw.githubusercontent.com/youzan/vant/dev/docs/assets/design.sketch</a>

### 描述问题
设计资源下载链接不可用

**Comment by chenjiahan** [comment]
可能是 Github 网络问题，可以访问国内镜像：https://gitee.com/vant-contrib/vant/raw/dev/docs/assets/design.sketch
