### ISSUE TITLE
[Bug Report] 【Dialog】iPhone 6s下 确认/取消按钮 文字位置不居中是居左的

### ISSUE THREAD

**Issue by YeKao** [youzan/vant#6307]
### 设备 / 浏览器
iPhone 6s  ML7C2CH/A

### Vant 版本
2.2.10

### Vue 版本
2.5.17

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/dialog" target="_blank">https://youzan.github.io/vant/#/zh-CN/dialog</a>

### 描述问题
【Dialog】组件，iPhone 6s下 确认/取消按钮 文字位置不居中是居左的，最新的Vant@2.8.2试了下官网文档也有这个问题

**Comment by chenjiahan** [comment]
系统版本是多少？

**Comment by YeKao** [comment]
10.3.2（14F89）

**Comment by chenjiahan** [comment]
iOS 10 按理说没问题的，能截官方文档的图看下吗

**Comment by YeKao** [comment]
![微信图片_20200519175145](https://user-images.githubusercontent.com/22538331/82312400-91c90c00-99f9-11ea-81f1-0442fa76b5a0.jpg)
我们这边的测试说就这一个机型有这个问题 其他应该是正常的

**Comment by chenjiahan** [comment]
get，我去找测试机试试

**Comment by chenjiahan** [comment]
这个问题的原因是 Button 在低版本浏览器上不能作为 flex 容器使用，后续会修复下

**Comment by YeKao** [comment]
好的

**Comment by chenjiahan** [comment]
已在 2.8.3 版本修复
