### ISSUE TITLE
[Bug Report] picker 为什么不是泛型 而是字符串?

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#6310]
### 设备 / 浏览器
chrom

### Vant 版本
2.8.2

### Vue 版本
2.6.11

### 描述问题
picker 设置的时候设置了对象  使用ref获取的时候就出问题了! 获取到的是string[] 但是设置的时候却是 Type[] 获取到后没法做后续操作

自己修改了一下 不知道官方是否会支持呢?

<img width="815" alt="1" src="https://user-images.githubusercontent.com/32523475/82303451-8a036a80-99ed-11ea-9aed-4ff59a930f74.png">

**Comment by lihaotian0607** [comment]
突然想到 有其他一部分组件也是依赖于该组件 官方是考虑到修改类型的工作量吗???😂

**Comment by chenjiahan** [comment]
这里确实有问题，可以提个 PR 喔

**Comment by lihaotian0607** [comment]
> 这里确实有问题，可以提个 PR 喔

但是会不会牵一发动全身 例如 `DatetimePicker` `area`组件之类的!

**Comment by lihaotian0607** [comment]
> > 这里确实有问题，可以提个 PR 喔
> 
> 但是会不会牵一发动全身 例如 `DatetimePicker` `area`组件之类的!

多虑了 pr: https://github.com/youzan/vant/pull/6313

**Comment by chenjiahan** [comment]
是不是加个 `T = string` 比较好

**Comment by lihaotian0607** [comment]
> 是不是加个 `T = string` 比较好

已重新提交

**Comment by chenjiahan** [comment]
已发布 2.8.3 版本
