### ISSUE TITLE
某些情况下field组件打包后样式变化，label与value的宽度变成相同

### ISSUE THREAD

**Issue by Eating23** [youzan/vant#6312]
field组件再调试模式下正常，但是再打包之后发现label与value的宽度会变成相同。
经检查发现.van-cell__title, .van-cell__value这两个类都有“flex：1”这个属性，这使得在field组件设置“label-width”属性有时不会生效。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by androidxu** [comment]
这个问题好烦人啊

**Comment by kkarry** [comment]
此问题有解决吗  我也遇到了相同的问题

**Comment by androidxu** [comment]
我的问题解决了，是多次引用导致的。

**Comment by zdhzhongtao** [comment]
> 我的问题解决了，是多次引用导致的。

这个怎么处理，现在发现使用按需加载，每个子组件比如都引入一次v-cell组件就会导致重复加载。
