### ISSUE TITLE
NavBar 导航栏怎么全局自定义返回键的图片

### ISSUE THREAD

**Issue by Torin2876** [youzan/vant#6316]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以使用 left 插槽
