### ISSUE TITLE
[Bug Report] TreeSelect 分类选择组件内使用-webkit-overflow-scrolling: touch之后在手机端不能滑动/滚动

### ISSUE THREAD

**Issue by daisty** [youzan/vant#6318]
### 设备 / 浏览器
华为手机微信浏览器

### Vant 版本
2.8.1

### Vue 版本
2.6.10

### 重现链接
<a href="https://0vo7q.csb.app/" target="_blank">https://0vo7q.csb.app/</a>

### 描述问题
在使用分类选择组件的内容过多的时候浏览器会出现滚动条，但在手机微信浏览器上面访问滑不上去，滑动不生效，我觉得是-webkit-overflow-scrolling: touch导致的bug，希望能处理一下，谢谢

**Comment by chenjiahan** [comment]
华为什么型号？ 我用 iOS 试了是正常的

**Comment by daisty** [comment]
不好意思，是我页面定位的问题，哈哈哈哈哈，给你添麻烦了，可以把这个问题关了

**Comment by chenjiahan** [comment]
好滴
