### ISSUE TITLE
[Bug Report] van-tabs 出现点击 item，总回到初始状态

### ISSUE THREAD

**Issue by mlyz-wdy** [youzan/vant#6319]
### 设备 / 浏览器
iPhone5 

### Vant 版本
2.8.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://szjsc-test.hzcitybrain.com/cockpit/m/global/?token=token-1b8eb789a7d869e54890a7741521ef74#/" target="_blank">https://szjsc-test.hzcitybrain.com/cockpit/m/global/?token=token-1b8eb789a7d869e54890a7741521ef74#/</a>

### 描述问题
iPhone5 上面，版本是 iOS12.4 ，点击标题vant-tabs，属性是scrollspy sticky，点击其它标签，其它手机正常定位到锚点，这个手机还有些其它的会刷新页面，导致 tab 回到第一个初始状态

**Comment by chenjiahan** [comment]
iPhone5 内存太小了吧，这样的机型现在基本不支持的
