### ISSUE TITLE
这个参数到底是毫秒还是秒，还是分钟呀？！

### ISSUE THREAD

**Issue by celverbamboo** [youzan/vant#632]
优惠券业务组件
![效果](https://i.loli.net/2018/02/09/5a7d570ead515.png)

**Comment by chenjiahan** [comment]
时间戳，单位毫秒，后续我们会在文档里标注下

**Comment by celverbamboo** [comment]
@chenjiahan 这个好像不是毫秒

**Comment by celverbamboo** [comment]
![效果图](https://i.loli.net/2018/02/09/5a7d5a71ea049.png)
我getTime()之后要 除以1000才正确！

**Comment by chenjiahan** [comment]
@celverbamboo sorry，单位是秒，看错了

**Comment by celverbamboo** [comment]
我的天

**Comment by celverbamboo** [comment]
我又试了，也不是秒.看图
![](https://i.loli.net/2018/02/09/5a7d5b4e5f6de.png)
![](https://i.loli.net/2018/02/09/5a7d5b4e61114.png)

**Comment by celverbamboo** [comment]
@chenjiahan

**Comment by chenjiahan** [comment]
时间戳 / 1000

**Comment by celverbamboo** [comment]
嗯
