### ISSUE TITLE
页面有三处选择时间，共用一个picker组件，再次选择，保留着之前的数据，怎么清除？

### ISSUE THREAD

**Issue by candyAndBella** [youzan/vant#6321]
![微信截图_20200520164751](https://user-images.githubusercontent.com/34698384/82426095-fe0b4480-9ab9-11ea-8cd6-3cc17afb6f29.png)
![微信截图_20200520164817](https://user-images.githubusercontent.com/34698384/82426101-ff3c7180-9ab9-11ea-831e-70389fcb7e8e.png)
![微信截图_20200520164832](https://user-images.githubusercontent.com/34698384/82426107-019ecb80-9aba-11ea-9e54-8321d61227e3.png)

**Comment by candyAndBella** [comment]
比如早餐选择了7:00-9:00.
我选择午餐，picker选择器，还是选择7:00-9:00为选中状态。
我希望打开午餐显示00:00-00:00.
选择完午餐，比如11:30-13:30。
再点早餐是7:00-9:00,点午餐是11:30-13:30，再点晚餐，是00:00-00:00

**Comment by candyAndBella** [comment]
![微信截图_20200520170831](https://user-images.githubusercontent.com/34698384/82428088-90144c80-9abc-11ea-9c8f-c20ac3c3fa6e.png)

**Comment by chenjiahan** [comment]
调用 `setColumnIndex` 可以实现这个功能（注意要在组件 mounted 之后才能调用）

**Comment by candyAndBella** [comment]
> 调用 `setColumnIndex` 可以实现这个功能（注意要在组件 mounted 之后才能调用）

我是调用的这个方法啊。。。在mounted之后？我是展开popup的时候，在方法里调用的。我上传的图片里有。

**Comment by chenjiahan** [comment]
展开 Popup 的时候可以先调下 nextTick

**Comment by candyAndBella** [comment]
> 展开 Popup 的时候可以先调下 nextTick

还是报错哦

**Comment by candyAndBella** [comment]
给popup加了一个:lazy-render='false' 
能够得到this.$refs.mypicker了
但是this.$refs.mypicker.setColumnIndex(this.breakfastIndex[0],this.breakfastIndex[1],this.breakfastIndex[2],this.breakfastIndex[3]);
方法，没有任何效果，还是无法清除之前的选中
