### ISSUE TITLE
[Bug Report] list组件在做基于定位的瀑布流的时候，会一直触发load事件，直到加载结束，怎么解决？

### ISSUE THREAD

**Issue by xts871722743** [youzan/vant#6322]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.4.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/list" target="_blank">https://youzan.github.io/vant/#/zh-CN/list</a>

### 描述问题
猜测是因为瀑布流是定位的，所以list组件无法获取位置信息，一直重复加载，请问如何解决

**Comment by chenjiahan** [comment]
麻烦提供下 codesandbox 复现链接

**Comment by xts871722743** [comment]
链接：https://x1xqy.csb.app/
我在load里面打印的console

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/list#shi-yong-float-bu-ju-hou-yi-zhi-chu-fa-jia-zai
