### ISSUE TITLE
[Bug Report] rules的匹配规则没有返回索引  & rules匹配有时不生效 #6320

### ISSUE THREAD

**Issue by oldpubcat** [youzan/vant#6324]
### 设备 / 浏览器
Chrome

### Vant 版本
2.8.2

### Vue 版本
3.0.0-beta.14

### 重现链接
<a href="https://github.com/oldpubcat/vantRules/tree/master/vantrules" target="_blank">https://github.com/oldpubcat/vantRules/tree/master/vantrules</a>

### 描述问题
问题一：
在匹配规则的validator函数里面，没有index 索引返回，如果数据是循环，并且回填出来的，没办法做比较，一个不匹配会全面报错。

下面是复现的示例：
示例：https://github.com/oldpubcat/vantRules/tree/master/vantrules

问题二：
动态回填的表单，然后再次输入匹配规则不生效，只能当再执行其他输入or交互型的操作之后上一次的匹配才会触发，（这个问题我在上面复现的项目中未成功复现，在开发的项目中有这个问题，暂时没找到原因）我录了个屏
录屏：https://github.com/oldpubcat/vantRules
由录屏下的控制台打印可见，在回填后报错的地方进行修改，匹配规则并未触发。

功能需求一：
希望rules的自定义规则可以返回一个index索引

**Comment by chenjiahan** [comment]
问题一：
你可以在 rule 里返回一个 index

```html
<template>
  <van-field :rule="getRule(0)" />
  <van-field :rule="getRule(1)" />
</template>

<script>
export default {
  methods: {
    getRule(index) {
      return {
        index,
        validator: this.validator
      };
    },
    validator(value, rule) {
      console.log(rule.index);
    }
  }
}
</script>
```

**Comment by chenjiahan** [comment]
问题二没懂，建议你提供一个最小的复现代码

**Comment by oldpubcat** [comment]
好的，谢谢，我感觉问题一可以解决的话，问题二应该不会出现，我明天试试，如果问题二还有问题，再找找原因看看如何复现

**Comment by chenjiahan** [comment]
好

**Comment by oldpubcat** [comment]
你好，我按您提供的代码尝试后，发现`validator`并未执行。我把代码提交到上面复现的库里面了。
代码地址是： https://github.com/oldpubcat/vantRules/blob/master/vantrules/src/App.vue    
还得麻烦您帮忙看看。

**Comment by chenjiahan** [comment]
上面的 rule 拼错了，是 rules

**Comment by oldpubcat** [comment]
好了，谢谢！！！！！！！！！
然后`getRule`函数里面的返回值方式也需要改一下,需要返回一个数组~~

```js
getRule(index) {
      return [
        {index, validator: this.validator, message: '包材领取数量不能大于余量', trigger: 'onChange'}
      ];
    },
```
