### ISSUE TITLE
[Bug Report] van-tabbar在路由模式下点击颜色不改变

### ISSUE THREAD

**Issue by xuzining** [youzan/vant#6326]
### 设备 / 浏览器
火狐和谷歌

### Vant 版本
2.8.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tabbar" target="_blank">https://youzan.github.io/vant/#/zh-CN/tabbar</a>

### 描述问题
van-tabbar在路由模式下点击颜色不改变
![image](https://user-images.githubusercontent.com/16344817/82517554-f1d1c680-9b4f-11ea-826f-93ed8d8da4c9.png)

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by xuzining** [comment]
就你们官网的路由跳转示例，复制粘贴一下就可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"neverland"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 中午11:54
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"小提摩太"<1379540723@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] van-tabbar在路由模式下点击颜色不改变 (#6326)





 
麻烦提供一下 codesandbox 复现链接

**Comment by chenjiahan** [comment]
官网的示例是没问题的，建议你看下你的 router 配置是否正确

**Comment by gap1994** [comment]
路由带参数的就会颜色不变的
