### ISSUE TITLE
[Bug Report]上传组件在荣耀v20上没有摄像头选项，直接进入相册了

### ISSUE THREAD

**Issue by Vasilis-wx** [youzan/vant#6327]
设备 / 浏览器
华为v20/微信内置浏览器/谷歌浏览器/夸克浏览器

Vant 版本
2.6.0

Vue 版本
2.5.2

描述问题
上传组件在华为p30上拉不起摄像头，直接进入相册了

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/6015
