### ISSUE TITLE
[Feature Request] 日历组件是否可以支持选择日期区间时开始和结束选择同一天呢？

### ISSUE THREAD

**Issue by xiaoming0827** [youzan/vant#6328]
### 这个功能解决了什么问题
在使用vant组件库的日历组件时候发现单元日期和区间选择日期是通过两个属性控制的，这样不能让一个组件既支持选择单个日期又可以选择日期区间，建议将两者合并，支持开始和结束都选择同一天，开始和结束都输出同一天也没问题

### 描述您想要的解决方案
希望日历组件选择日期区间功能支持开始和结束选择同一天，这样可以和选择单个日期完美融合，谢谢

### 建议的API是什么样的
希望日历组件选择日期区间功能支持开始和结束选择同一天，这样可以和选择单个日期完美融合，谢谢

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6283
