### ISSUE TITLE
[Feature Request] 点击出现波纹效果

### ISSUE THREAD

**Issue by shlroland** [youzan/vant#6329]
### 这个功能解决了什么问题
增加点击反馈效果

### 描述您想要的解决方案
1.以指令形式如v-wave配置
2.可以配置波纹的形状，大小，颜色，速度，曲线函数等等
3.不仅仅局限于按钮，可以使导航栏，表单组件等等

### 建议的API是什么样的
https://codepen.io/finnhvman/pen/MQyJxV?editors=1100

**Comment by chenjiahan** [comment]
Vant 的设计规范里没有这个效果，建议自行实现喔
