### ISSUE TITLE
tabar-item用自定义图标，如果当前不在第一项，一刷新图标会重置为第一项选中的图标，而不是当前项的图标

### ISSUE THREAD

**Issue by LiuNing244871946** [youzan/vant#6330]
`<van-tabbar-item name="发现" to="/find">
          <span>发现</span>
          <template #icon="find">
            <img :src="find.active ? iconFind.active : iconFind.inactive" />
          </template>
 </van-tabbar-item>
 <van-tabbar-item name="分析" to="/analysis">
          <span>分析</span>
          <template #icon="analysis">
            <img
              :src="
                analysis.active ? iconAnalysis.active : iconAnalysis.inactive
              "
            />
          </template>
        </van-tabbar-item>
        <van-tabbar-item replace name="我的" to="/about">
          <span>我的</span>
          <template #icon="about">
            <img :src="about.active ? iconMy.active : iconMy.inactive" />
          </template>
        </van-tabbar-item>`

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
