### ISSUE TITLE
为什么vant组件里面没有table组件

### ISSUE THREAD

**Issue by yanghao-blip** [youzan/vant#6332]
希望可以加入table组件

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3271

**Comment by ffzhihua** [comment]
![image](https://user-images.githubusercontent.com/8053824/84629087-564c2f80-af1c-11ea-8c9f-399149a66cdc.png)
强烈要求table组件

**Comment by ffzhihua** [comment]
![image](https://user-images.githubusercontent.com/8053824/84629087-564c2f80-af1c-11ea-8c9f-399149a66cdc.png)
![image](https://user-images.githubusercontent.com/8053824/84629198-7ed42980-af1c-11ea-8245-99934f707dd0.png)

强烈要求table组件

**Comment by ffzhihua** [comment]
https://upload-images.jianshu.io/upload_images/2407186-f90dbc755ee9285c.gif?imageMogr2/auto-orient/

**Comment by ffzhihua** [comment]
![image](https://user-images.githubusercontent.com/8053824/84629302-ac20d780-af1c-11ea-8a29-997b2091bed6.png)
要这种效果
