### ISSUE TITLE
[Bug Report] nav-bar fixed会影响form组件scroll-to-error

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#6334]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsfiddle.net/cLu89p53/50/" target="_blank">https://jsfiddle.net/cLu89p53/50/</a>

### 描述问题
nav-bar fixed会影响form组件scroll-to-error

```
 scrollToField: function scrollToField(name) {
      this.fields.forEach(function (item) {
        if (item.name === name) {
    // 使用false 貌似可以解决
          item.$el.scrollIntoView(false);
        }
      });
    },
```

**Comment by chenjiahan** [comment]
`scrollIntoView(false)` 表示元素滚动到贴底位置，不适用于大部分场景。

你这个情况只能手动设置滚动条的位置了，Form 组件本身无法感知到 NavBar 的存在

**Comment by lihaotian0607** [comment]
> `scrollIntoView(false)` 表示元素滚动到贴底位置，不适用于大部分场景。
> 
> 你这个情况只能手动设置滚动条的位置了，Form 组件本身无法感知到 NavBar 的存在

那如果改为参数传递呢 可以增加一个scrollIntoView支持的参数

**Comment by chenjiahan** [comment]
可以的，下个版本加上

**Comment by chenjiahan** [comment]
已在 2.8.3 版本添加参数
