### ISSUE TITLE
tab下data数据更新后手机端浏览器页面无法刷新

### ISSUE THREAD

**Issue by hjyeah** [youzan/vant#6337]
- 首先PC上调试没有任何问题
- 手机端访问就无法更新界面数据，无论是Chrome还是safari
## 代码布局描述
tabs下分2个tab，其中一个tab下有两个按钮，用来切换对应的div（本质就是v-show参数改变下），我在发起ajax请求返回更新数据后，tab下的界面数据却没有更新，但是奇怪的是我点击下切换的按钮那一瞬间，可以看到数据更新了…就只是切换了下，这是bug吧…

**Comment by yiliang114** [comment]
同遇到了。。。。。

**Comment by yiliang114** [comment]
看时间是 1 小时之前发布了版本，所版本 2.8.2 之后发现可以 @hjyeah  你可以试试

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

另外 2.8.2 版本中没有涉及 Tab 的改动

**Comment by hjyeah** [comment]
> 看时间是 1 小时之前发布了版本，所版本 2.8.2 之后发现可以 @hjyeah 你可以试试

我刚升级到了2.8.3，tab还是老问题，没解决

**Comment by hjyeah** [comment]
> 请按照模板创建 issue，感谢配合
> 
> 另外 2.8.2 版本中没有涉及 Tab 的改动

提问格式已修改，不过这个问题我升级到2.8.3还是没解决额

**Comment by chenjiahan** [comment]
提供下 codesandbox 复现链接

**Comment by hjyeah** [comment]
> 提供下 codesandbox 复现链接

https://codesandbox.io/s/tab-ios-problem-kyvb3?file=/src/App.vue 基本代码就这样，用了tab，ios试下可以的，但是在我工程里面总量就不会更新，一定要切换tab后才会更新
