### ISSUE TITLE
[Bug Report] van-submit-bar组件问题

### ISSUE THREAD

**Issue by liseipi** [youzan/vant#6339]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.3

### Vue 版本
3.0.0-beta.14

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/submit-bar" target="_blank">https://youzan.github.io/vant/#/zh-CN/submit-bar</a>

### 描述问题
```
<van-submit-bar :price="3050" button-text="提交订单" @submit="onSubmit">
  <van-checkbox v-model="checked">全选</van-checkbox>
  <div slot="tip" v-if="status">
    你的收货地址不支持同城送, <span @click="onClickEditAddress">修改地址</span>
  </template>
</van-submit-bar>
```
<div slot="tip" v-if="status"><div>
在 slot="tip"中加入判断时，浏览器报如下错误信息：
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

**Comment by wustzhaohui** [comment]
这么快有人开始使用vue3了啊

**Comment by chenjiahan** [comment]
这是 nuxt 提示你在服务端和客户端输出的 DOM 不一致，可能是你的 status 值不一致导致的，跟组件本身没有关系
