### ISSUE TITLE
van-stepper  的异常

### ISSUE THREAD

**Issue by shiyuegongsui** [youzan/vant#634]
<van-stepper v-model="buyCount"  @change="changeBuyCount" />

使用van-stepper的时候,直接在input输入，可以把数值清空，无法用change事件 监听返回的值，watch也无法监听buyCount的改变。

**Comment by chenjiahan** [comment]
已在 0.12.10 版本中修复

**Comment by dongjunmei** [comment]
修复好了吗 为啥我这边用的还存在呢
