### ISSUE TITLE
[Bug Report] vant-list 在安卓webview中首次加载不执行

### ISSUE THREAD

**Issue by 2125zyrc** [youzan/vant#6340]
### 设备 / 浏览器
华为p30/安卓10

### Vant 版本
2.8.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
1.由于在浏览器中以及ios中都是正常执行的，所以很抱歉无法提供代码
2.vant-list 在安卓webview中首次加载不执行
3.我的解决办法是关闭immediate-check，然后手动执行

**Comment by 2125zyrc** [comment]
`<template>
  <div>
    <Nav :detail="userData"/>
    <div class="user-lists">
      <van-list
        v-model="loading"
        :finished="finished"
        :error.sync="error"
        finished-text=""
        error-text="请求失败，点击重新加载"
        :immediate-check="false"
        @load="listsOnLoad()"
      >
        <user-item class="item" v-for="(item, index) in inviterLists" :key="index" :detail="item"/>
      </van-list>
    </div>
  </div>
</template>

<script>
import Nav from "./components/Nav"
import UserItem from "./components/UserItem"
import { inviterRosters, getInviterList } from '@/api/invite'
import Vue from 'vue'
import { List } from 'vant'

Vue.use(List)

export default {
  components:{ Nav, UserItem },
  data(){
    return {
      page: 0,
      limit: 10,
      userData: {},
      inviterLists: [],
      loading: false, // 显示加载
      finished: false, // 加载完成
      error: false // 加载错误
    }
  },
   methods: {
    //名单列表 + 下滑加载
    listsOnLoad(){
      this.getLists()
    },
    //1.获取列表数据 这里在安卓手机中有bug  issue: 页面初始化时load方法不执行
    //2.在ios中以及在浏览器中时可以手动执行的
    //3.所以需要手动关闭第一次执行  :immediate-check="false"
    //4.在created中手动调用一次
    getLists(){
        let { uuid } = this.$route.query
        if(Array.isArray(uuid)){ //因为这个地方app内部会再加一次uuid
          uuid = uuid[0]
        }
        const query = {
          uuid,
          start: this.page * this.limit,
          rows: this.limit
        }
        getInviterList(query).then(res=>{
          this.loading = false
          if (res && res.data) {
            if (res.data.inviterList.length < this.limit) {
              this.finished = true
            }
            this.page += 1
            this.inviterLists.push(...res.data.inviterList)
          } else {
            this.finished = true
          }
        }).catch(e=>{
          console.log(e)
          this.error = true
          this.finished = true
        })
    },
    //初始化头部信息
    async init(){
      try{
        let { uuid } = this.$route.query //因为这个地方app内部会再加一次uuid
        if(Array.isArray(uuid)){
          uuid = uuid[0]
        }
        const res = await inviterRosters({ uuid })
        this.userData = res.data.userData
      }catch(e){
        console.log(e)
      }
    }
  },
  created() {
    this.getLists()
    this.init()
  }
}
</script>`

**Comment by chenjiahan** [comment]
理论上来说首次加载是会执行的，建议你看下是不是业务里的其他代码影响了 List 的判断，可以在 List 的 check 方法里调试看下

**Comment by 2125zyrc** [comment]
我测试的时候把多余的代码删除了   在ios和web中确实是可以执行的   但是在安卓的webview中非常大的概率是不执行首次加载的

**Comment by chenjiahan** [comment]
你可以直接试下官网的示例
