### ISSUE TITLE
Calendar日历能不能设置禁止选择周末日期

### ISSUE THREAD

**Issue by taotao6** [youzan/vant#6343]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以通过 formatter 属性把周末日期的 type 设置为 disabled
