### ISSUE TITLE
vant icon突然变为了方块 

### ISSUE THREAD

**Issue by luckywangming** [youzan/vant#6344]
### 设备 / 浏览器
移动端

### Vant 版本
2.8.3

### Vue 版本
2.6.3

### 重现链接
<a href="http://huzi3.hndszx.com/#/index/home" target="_blank">http://huzi3.hndszx.com/#/index/home</a>

### 描述问题
公众号项目 在浏览器和微信开发者工具突然都变为了方块 试了vant2.6.1和2.8.3版本均不行

**Comment by chenjiahan** [comment]
图标是通过网络加载的字体文件，网络差的情况下可能会变成方块，你可以参考文档的方式来使用本地的字体文件

https://youzan.github.io/vant/#/zh-CN/icon#shi-yong-ben-di-zi-ti-wen-jian
