### ISSUE TITLE
[Bug Report] Uploader组件 在微信浏览器点击上传图片无响应

### ISSUE THREAD

**Issue by lb02** [youzan/vant#6346]
### 设备 / 浏览器
微信浏览器

### Vant 版本
2.8.3

### Vue 版本
3.0.0-beta.14

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
Uploader组件 在微信浏览器点击上传图片无响应

**Comment by chenjiahan** [comment]
具体是什么机型，能提供复现视频看下吗

**Comment by cangyu1993** [comment]
ios上拍照图片会倾斜

**Comment by mengerwei521** [comment]
今天发现，在安卓）微信浏览器上，输入弹出框点击确认时，系统键盘收起卡顿，，，在手机自带浏览器上没有问题，在ios微信浏览器上也没有问题

**Comment by chenjiahan** [comment]
报问题的时候都提供下截图或视频哈

**Comment by zhichao8756** [comment]
今天也遇到相同的问题,原因可能在于http返回状态码 413 Request Entity Too Large(请求实体过大)
如果前端是部署在nginx容器中,可修改配置:
nginx默认上传文件的大小是1M
打开nginx配置文件 nginx.conf。
在server{}段中加入 client_max_body_size 20m; 20m为允许最大上传的大小。
保存后重启nginx

**Comment by liuxin24** [comment]
我这也出现了兼容性问题，微信浏览器中uploader组件有些机型选择图片后没反应，before-read,after-read无效，手机型号华为MATE 20，系统版本10.0.0.200 微信版本7.0.10。

**Comment by chenjiahan** [comment]
是不是图片格式的问题呢，可以换原生 input type="file" 尝试下是否有同样问题

**Comment by sduqlsc** [comment]
同出现问题，微信浏览器不正常，safari 可以

**Comment by lwm98** [comment]
同出现了，安卓微信浏览器，上传完文件之后就会卡顿，表单都没法输入了，怎么办啊老大 好卡 @chenjiahan

**Comment by chenjiahan** [comment]
可以调整 resultType 试试

![image](https://github.com/youzan/vant/assets/7237365/29b0b78c-737c-47fa-a9e4-178797c23822)

**Comment by lwm98** [comment]
> 今天发现，在安卓）微信浏览器上，输入弹出框点击确认时，系统键盘收起卡顿，，，在手机自带浏览器上没有问题，在ios微信浏览器上也没有问题

+1 我也出现了，请问后面解决了吗

**Comment by lwm98** [comment]
> 可以调整 resultType 试试
> 
> ![image](https://user-images.githubusercontent.com/7237365/249970478-29b0b78c-737c-47fa-a9e4-178797c23822.png)

但是老大，这个也只是3m大小的图片，以前微信浏览器是不会卡的。现在如果改成file之后，即时预览再做另外的处理吗？

**Comment by chenjiahan** [comment]
3m 的图片正常来说不会有问题，你可以新建一个 issue 并提供复现的 codesandbox 链接看一下
