### ISSUE TITLE
[Bug Report] Search组件自定义右侧内容search事件回调拿不到搜索框值

### ISSUE THREAD

**Issue by OrdinaryPath** [youzan/vant#6350]
### 设备 / 浏览器
chrome 83.0.4103.61

### Vant 版本
2.8.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/search" target="_blank">https://youzan.github.io/vant/#/zh-CN/search</a>

### 描述问题
Search组件自定义右侧内容search事件回调拿不到搜索框值，例子：官方DEMO自定义按钮

**Comment by chenjiahan** [comment]
直接取 v-model 绑定的值就可以
