### ISSUE TITLE
[Feature Request] AddressList 地址列表 的新增地址按钮在ios设备微信浏览器上会被底部的横条遮挡

### ISSUE THREAD

**Issue by 17779286189** [youzan/vant#6351]
### 这个功能解决了什么问题
AddressList 地址列表 的新增地址按钮在ios设备上会被底部的横条遮挡

### 描述您想要的解决方案
发现按钮是窗口定位，buttom：0，在微信自带浏览器打开会被挡住

### 建议的API是什么样的
在微信自带浏览器打开会被挡住

**Comment by chenjiahan** [comment]
下个版本会加个底部安全区适配

**Comment by chenjiahan** [comment]
已在 2.8.4 版本支持
