### ISSUE TITLE
Area组件不设置默认值得情况，城市列表渲染为空

### ISSUE THREAD

**Issue by syymo** [youzan/vant#6352]
Area组件不设置默认值得情况，城市列表不会取默认第一个，希望能优化。

![WeChat Work Screenshot_20200523175827](https://user-images.githubusercontent.com/26571594/82727756-07e1b180-9d1f-11ea-9409-52a6477c638d.png)
![WeChat Work Screenshot_20200523175757](https://user-images.githubusercontent.com/26571594/82727760-1203b000-9d1f-11ea-9ce6-b48c9ffe6d65.png)

**Comment by chenjiahan** [comment]
下个版本会优化下

**Comment by chenjiahan** [comment]
已在 2.8.4 版本修复
