### ISSUE TITLE
[Feature Request] Sidebar 侧边导航滚动优化

### ISSUE THREAD

**Issue by changeplango** [youzan/vant#6353]
### 这个功能解决了什么问题
侧边栏如果内容过多的时候（很多内容不在可视范围内），能否做一个滚动优化，向上向下滚动的时候可以让选中栏维持在中间。

### 描述您想要的解决方案
侧边栏如果内容过多的时候（很多内容不在可视范围内），能否做一个滚动优化，向上向下滚动的时候可以让选中栏维持在中间。

**Comment by changeplango** [comment]
Tab组件就有这种效果，希望团队可以在Sidebar组件也加上

**Comment by jerryyan1990** [comment]
+1 希望可以像tab一样可以自己滚动

**Comment by chenjiahan** [comment]
暂无计划支持哦，Sidebar 目前不提供滚动相关的逻辑，可以自行实现一下
