### ISSUE TITLE
vue.config.js 修改样式变量 配置

### ISSUE THREAD

**Issue by Fallen-down** [youzan/vant#6362]
这是我的示例，我配置了rem 然后 修改样式变量的时候遇到了问题……
https://github.com/Fallen-down/some-exercises/tree/master/demo/Vue.js/axios-vue

下面是报错信息
 ERROR  Failed to compile with 5 errors                                                                          9:01:34

 error  in ./node_modules/vant/es/button/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):
ValidationError: Invalid options object. Less Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'modifyVars'. These properties are valid:
   object { lessOptions?, prependData?, appendData?, sourceMap?, implementation? }
    at validate (D:\some-exercises\demo\Vue.js\axios-vue\node_modules\schema-utils\dist\validate.js:88:11)
    at Object.lessLoader (D:\some-exercises\demo\Vue.js\axios-vue\node_modules\less-loader\dist\index.js:22:28)

 @ ./node_modules/vant/es/button/index.less 4:14-198 14:3-18:5 15:22-206
 @ ./node_modules/vant/es/button/style/less.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.133:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by chenjiahan** [comment]
less-loader 6.0 版本的配置项改了，modifyVars 外面要套一层 lessOptions 选项，参见

https://youzan.github.io/vant/#/zh-CN/theme#bu-zou-er-xiu-gai-yang-shi-bian-liang

**Comment by Fallen-down** [comment]
太感谢了，解决问题太高效了。
