### ISSUE TITLE
[BUG]Toast.loading组件bug

### ISSUE THREAD

**Issue by ShuaiChangZhe** [youzan/vant#6363]
Toast组件的loding功能使用时会在一段端渲染出一个黑点，无法去除

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by lifbliu** [comment]
> Toast组件的loding功能使用时会在一段端渲染出一个黑点，无法去除

我也遇到了这个问题，pc端浏览器没有问题，放在手机上就会有这个问题了。关闭loading以后，页面左上角会出现一个黑点
