### ISSUE TITLE
[Bug Report] 使用本地字体后是否可以不下载远程cdn字体文件

### ISSUE THREAD

**Issue by heart-er** [youzan/vant#6364]
### 设备 / 浏览器
mac 10.14.6  chrome

### Vant 版本
2.8.1

### Vue 版本
2.6.8

### 重现链接
无(隐私问题无法提供链接)

### 描述问题
使用本地字体后是否可以不下载远程cdn字体文件，目前使用了本地文件后，还是下载了远程cdn文件

**Comment by chenjiahan** [comment]
local.css 需要和 Icon 的样式打包在同一个样式文件里，这样就不会下载远程 CDN 文件。

**Comment by heart-er** [comment]
![image](https://user-images.githubusercontent.com/24717511/82861423-2fb75c00-9f4f-11ea-8be5-00feeef20ccb.png)
![image](https://user-images.githubusercontent.com/24717511/82861440-3ba31e00-9f4f-11ea-9382-f132581c0efa.png)
我在这边手动使用了本地字体 但是控制台在下载了本地字体后 又再次下载了cdn字体文件
![image](https://user-images.githubusercontent.com/24717511/82861491-6a20f900-9f4f-11ea-83c5-301eed04b3e4.png)

**Comment by chenjiahan** [comment]
能不能给个链接瞅瞅

**Comment by heart-er** [comment]
是在使用了babel-plugin-import的情况下，他会自动引入 请问有相关不会下载cdn的demo参考吗

**Comment by heart-er** [comment]
在lib目录下的index.css文件的打包压缩文件中改为本地路径就正常了 但是这是在node_modules里的,能否有办法在外部引用不需要每次修改node_modules里的内容且不下载cdn的办法？

**Comment by chenjiahan** [comment]
上面已经说得很清楚了，你需要确认 local.css 和 Icon 的样式是不是打包在同一个样式文件里
