### ISSUE TITLE
有关上传图片的问题在华为手机 上

### ISSUE THREAD

**Issue by mhxy13867806343** [youzan/vant#6365]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
在华为手机 上，无法上传图片，如下的视频

因为是视频
所以放在第三方地址了
https://streamable.com/40lf82 链接地址
截图下
![11111](https://user-images.githubusercontent.com/4418166/82785725-bf98cf80-9e95-11ea-9783-b700dcd0b9f5.jpg)

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by mhxy13867806343** [comment]
https://streamable.com/40lf82 链接地址  需要翻墙操作

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
