### ISSUE TITLE
vant-search组件在pc（非移动端模式下） clear事件不触发

### ISSUE THREAD

**Issue by Live-forever** [youzan/vant#6367]
vant： 2.2.10       
chrome： 81.0.4044.138
vue： 2.6.10

描述： vant-search组件在 pc 模式下  输入文本后想要清除 点击 右边的 X 未能触发clear事件， clear图标消失 但是文本未被清除

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

**Comment by Live-forever** [comment]
真的有问题，文档我看了，用的应该没毛病呀！因为我们的页面是放在企业微信里的，用户可能通过pc上的企业微信来访问！麻烦告知下原因，谢谢！


| |
陆文祥
|
|
邮箱：18056613516@163.com
|

签名由 网易邮箱大师 定制

在2020年05月25日 16:17，neverland 写道：

参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-zhuo-mian-duan-shi-yong

**Comment by chenjiahan** [comment]
确认 touch-emulator 引了？

**Comment by Live-forever** [comment]
我下午看源码才知道这里用的是touch事件，明天试一下！多谢🤝


| |
陆文祥
|
|
邮箱：18056613516@163.com
|

签名由 网易邮箱大师 定制

在2020年05月25日 19:59，neverland 写道：

确认 touch-emulator 引了？
