### ISSUE TITLE
[Bug Report]vant-search 组件 clear事件 pc 端不触发

### ISSUE THREAD

**Issue by Live-forever** [youzan/vant#6369]
设备 / 浏览器
chrome浏览器

Vant 版本
2.2.1

Vue 版本
2.6.1

描述问题
vant-search组件在 pc 模式下 输入文本后想要清除 点击 右边的 X 未能触发clear事件， clear图标消失 但是文本未被清除

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/6367
