### ISSUE TITLE
[Bug Report] @vant/cli安装失败

### ISSUE THREAD

**Issue by yoruponder** [youzan/vant#6370]
### 设备 / 浏览器
npm 6.14.5    node  10.15.3   mac 10.15.2

### Vant 版本
2.8.3

### Vue 版本
2.6.11

### 描述问题
安装失败

➜  vant git:(d97c18527) npm i @vant/cli -D
npm ERR! Unexpected end of JSON input while parsing near '...edSize":58729,"npm-si'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2020-05-25T11_24_49_905Z-debug.log

➜  vant git:(dev) npm i @vant/cli -D
npm ERR! Unexpected end of JSON input while parsing near '...dEWnmCRA9TVsSAnZWagAA'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2020-05-25T11_26_33_638Z-debug.log

**Comment by yoruponder** [comment]
vant库拷下来运行npm i同样报错

➜  vant git:(dev) npm i
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm ERR! Unexpected end of JSON input while parsing near '...dEWnmCRA9TVsSAnZWagAA'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2020-05-25T11_22_02_852Z-debug.log

**Comment by chenjiahan** [comment]
安装的问题，和 vant-cli 无关。

参见 https://stackoverflow.com/questions/47675478/npm-install-errorunexpected-end-of-json-input-while-parsing-near-nt-webpack
