### ISSUE TITLE
[Feature Request] 上拉加载，下拉刷新能否支持自定义loading呢？能否支持自定义loading呢？

### ISSUE THREAD

**Issue by gengbingbing** [youzan/vant#6375]
### 这个功能解决了什么问题
自定义loading

### 描述您想要的解决方案
支持上拉加载，下拉刷新能否支持自定义loading

### 建议的API是什么样的
支持上拉加载，下拉刷新能否支持自定义loading

**Comment by ZhengXiaowei** [comment]
`List`组件用`loading slot`就可以自定义你想要的`loading`
`pullrefresh`使用`#pulling #loosing #loading`三个状态就而已自定义`loading`效果了。。这些文档上有的。。
