### ISSUE TITLE
[Bug Report] van-upload怎样自定义上传成功后的样式

### ISSUE THREAD

**Issue by Asuraliu** [youzan/vant#6377]
### 设备 / 浏览器
移动端

### Vant 版本
2.8.3

### Vue 版本
3.0.0-beta.14

### 重现链接
<a href="http://note.youdao.com/noteshare?id=6d7fea5d3239ee73c9ff6edb0772f759&sub=A5798ED8897F459DB3458909789F2057" target="_blank">http://note.youdao.com/noteshare?id=6d7fea5d3239ee73c9ff6edb0772f759&sub=A5798ED8897F459DB3458909789F2057</a>

### 描述问题
修改上传accept为application/*后，上传后显示的样式还是默认的图片样式，想请教一下是不是可以修改上传后的显示样式？或者是不是已经有了成功的解决方案我不知道的，希望给个链接？

**Comment by chenjiahan** [comment]
简单的场景可以通过覆盖 CSS 来修改样式。

如果是上图里的布局，跟 Uploader 的默认布局差别较大，建议将 preview-image 属性设置为 false，然后自行实现预览图的样式。
