### ISSUE TITLE
[Bug Report] van-field 设置error为false，输入内容或placeholder依然标红

### ISSUE THREAD

**Issue by fengyun2** [youzan/vant#6378]
### 设备 / 浏览器
win 10/chrome 83

### Vant 版本
2.5.8

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-h85gu?file=/src/form.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-h85gu?file=/src/form.vue</a>

### 描述问题
van-field 设置error为false，输入内容或placeholder依然标红

```vue
  <van-field
      v-model="username"
      name="用户名"
      label="用户名"
      placeholder="用户名"
      required
      :error="false"
      :rules="[{ required: true, message: '请填写用户名' }]"
    />
```
![image](https://user-images.githubusercontent.com/8147202/82866611-d99ce580-9f5b-11ea-826c-e47e0c07c8b7.png)

**Comment by chenjiahan** [comment]
目前在 Form 内不支持禁用单个 Field 的 error 提示，可以通过 Form 的 show-error 属性禁用所有 Field 的 error 提示。

下个版本会调整下，支持禁用单个 Field 的 error 提示

**Comment by fengyun2** [comment]
@chenjiahan 我们不是希望禁用rules的校验提示信息，是希望输入内容和placeholder不要标红

**Comment by chenjiahan** [comment]
嗯，是这个意思。已经在 2.8.4 版本调整
