### ISSUE TITLE
[Bug Report] Sidebar的change事件没有触发

### ISSUE THREAD

**Issue by AndyChYL** [youzan/vant#6379]
### 设备 / 浏览器
Windows / Chrome  83.0.4103.61

### Vant 版本
2.8.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/hardcore-field-2xojt" target="_blank">https://codesandbox.io/s/hardcore-field-2xojt</a>

### 描述问题
手动改变activeKey时，没有触发change事件

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.8.4 版本修复
