### ISSUE TITLE
[Bug Report] from表单下设置van-field为number提交时字段输出为带双引号的字符串并非number类型

### ISSUE THREAD

**Issue by sniperZj** [youzan/vant#6380]
### 设备 / 浏览器
微信开发者工具

### Vant 版本
2.8.3

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-jt1os?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-jt1os?file=/src/App.vue</a>

### 描述问题
from表单下设置van-field为number提交时字段输出为带双引号的字符串并非number类型

**Comment by sniperZj** [comment]
@chenjiahan 呼叫大神

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6374
