### ISSUE TITLE
[Feature Request] DatetimePicker 时间选择组件可否增加选择月日的类型

### ISSUE THREAD

**Issue by hxqiao** [youzan/vant#6381]
### 这个功能解决了什么问题
目前不能只选择月日两项，但是有时数据里只有月份和日期，这样年份就会空出来，造成数据不能正确显示

### 描述您想要的解决方案
增加选择月日的类型

### 建议的API是什么样的
参数type增加可选类型month-day

**Comment by chenjiahan** [comment]
已在 2.8.4 版本支持
