### ISSUE TITLE
[Feature Request] 日期选择器增加自定义月份

### ISSUE THREAD

**Issue by gapkukb** [youzan/vant#6384]
### 这个功能解决了什么问题
在许多场景下，日期选择并不仅仅只是选择1-12月份。很多时候需要有更多自定义的选项。比如全年，第一季度，第二季度，1-12月此种月份选项个数大于12个的需求。

### 描述您想要的解决方案
新增绑定属性，允许用户自定义月份开始和结束即可，结合formatter功能，可以实现更丰富细致的需求

### 建议的API是什么样的
父级传值。如:startMonth="0" :endMonth="14" .

**Comment by chenjiahan** [comment]
用 filter 属性可以实现的喔

**Comment by gapkukb** [comment]
filter只能过滤吧。我的意思是月份选择可能会大于12选项而不是仅仅只选择1-12月。filter能做到吗

**Comment by gapkukb** [comment]
比如月份选项我会有如下item:
全年，第一季度，第二季度，第三季度，第四季度，01，02，03，04，05，06，07，08，09，10，11，12 
一共17个选项。
我目前使用了 picker组件。datapicker组件我暂时没有发现实现的方式。你说的 filter我不是很明白怎么做

**Comment by gapkukb** [comment]
filter中我试了对 options 进行unshift或者push。视图上是有效的。但是无法被选中，你内部的逻辑限定死了 max month  = 12和min-month=1。大于12小于1就会跳转到上下年份

**Comment by chenjiahan** [comment]
这种需求建议用 Picker 实现呢
