### ISSUE TITLE
组件库是不是缺少列表类型的呢

### ISSUE THREAD

**Issue by tianr1190** [youzan/vant#6386]
组件库里缺少文章类型的列表组件
建议可以增加多这种类型的列表组件，不知道vant weapp出于什么原因考虑，没有做列表类型的组件。
比如文章列表组件，带图文内容的列表组件等等。
当然开发者也可以自己用原生的wxml自己做列表，但是感觉如果vant weapp 能提供统一UI的类似的组件库就更完善了。

**Comment by chenjiahan** [comment]
这里是 Vant 的仓库呢，Vant Weapp 的问题请到对应仓库下按照模板创建
