### ISSUE TITLE
[Feature Request] van-dropdown-menu组件能否设置与van-field组件输入框的宽度保持一致?

### ISSUE THREAD

**Issue by fengyun2** [youzan/vant#6387]
### 这个功能解决了什么问题
目前van-dropdown-menu组件使用fixed定位会把van-field的label遮盖住，第一个方面影响页面的使用，第二个方面影响页面的美观度

![image](https://user-images.githubusercontent.com/8147202/82963670-0a315d80-9ff6-11ea-99d8-d63f4eecd3c6.png)
![image](https://user-images.githubusercontent.com/8147202/82963681-14535c00-9ff6-11ea-9de0-17a78f0f2244.png)

### 描述您想要的解决方案
van-dropdown-menu组件能否设置与van-field组件输入框的宽度保持一致?

![image](https://user-images.githubusercontent.com/8147202/82959898-81152900-9feb-11ea-9ee0-b61019f325be.png)

### 建议的API是什么样的
inputWidth

**Comment by chenjiahan** [comment]
这个需求暂时没有计划支持呢，DropdownMenu 不是放在表单内用的，表单内选择请使用 Picker 组件。
