### ISSUE TITLE
DropdownMenu 组件项目构建后van-dropdown-menu__bar层级div丢失

### ISSUE THREAD

**Issue by syymo** [youzan/vant#6388]
本地dev的dom结构
![image](https://user-images.githubusercontent.com/26571594/82969387-1e7b5780-a002-11ea-8b5c-16bd24ec5267.png)

build之后的dom结构
![image](https://user-images.githubusercontent.com/26571594/82969409-305cfa80-a002-11ea-847a-b55560359143.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by liuhao1025** [comment]
> 本地dev的dom结构
> ![image](https://user-images.githubusercontent.com/26571594/82969387-1e7b5780-a002-11ea-8b5c-16bd24ec5267.png)
> 
> build之后的dom结构
> ![image](https://user-images.githubusercontent.com/26571594/82969409-305cfa80-a002-11ea-847a-b55560359143.png)

这个是版本的问题，2.6.3 之前的版本没有生成 .van-dropdown-menu__bar 这个 div，2.6.3 改了 dropdown-menu 的 render 方法，加了一层，可以看一下这个 commit， #7db744909。可以看一下 dev 和 build 时 vant 的版本是不是不一样 ？
