### ISSUE TITLE
[Feature Request] 会增加商品视频播放,放在轮播时展示吗

### ISSUE THREAD

**Issue by ttupup** [youzan/vant#6389]
### 这个功能解决了什么问题
增加商品视频播放,放在轮播时展示

### 描述您想要的解决方案
增加商品视频播放,放在轮播时展示

### 建议的API是什么样的
增加商品视频播放,放在轮播时展示

**Comment by chenjiahan** [comment]
暂无计划支持喔，轮播的内容是可以自定义的
