### ISSUE TITLE
上传组件限制数量，在小米10手机上选择达到上限数量时，手机闪黑白屏异常。

### ISSUE THREAD

**Issue by yangmin7799** [youzan/vant#6390]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
