### ISSUE TITLE
[Bug Report] get-container挂载问题

### ISSUE THREAD

**Issue by xiaomun** [youzan/vant#6391]
### 设备 / 浏览器
google chrome

### Vant 版本
2.3.3

### Vue 版本
2.5.2

### 重现链接
<a href="https://github.com/xiaomun" target="_blank">https://github.com/xiaomun</a>

### 描述问题
van-action-sheet添加get-containe="#app" 运行后，提示错误：
Error in beforeDestroy hook: "HierarchyRequestError: Failed to execute 'appendChild' on 'Node': This node type does not support this method."found in ...

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/2608

**Comment by xiaomun** [comment]
> 
> 
> 参见 [https://github.com/youzan/vant/issues/2608，https://github.com/youzan/vant/issues/4760](https://github.com/youzan/vant/issues/2608%EF%BC%8Chttps://github.com/youzan/vant/issues/4760)
您这个地址打开后找不到东西。

**Comment by xiaomun** [comment]
您这个地址打开后找不到东西。

**Comment by chenjiahan** [comment]
这是俩链接。

**Comment by xiaomun** [comment]
哦  不好意思，谢谢啊
