### ISSUE TITLE
vue.esm.js?f1a5:628 [Vue warn]: Error in render: "TypeError: Cannot read property 'zIndex' of null"

### ISSUE THREAD

**Issue by whoopsHzh** [youzan/vant#6392]
van-dropdown-item
![image](https://user-images.githubusercontent.com/32846446/82993299-efc9a500-a032-11ea-99a8-6ee0d53c9068.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

另外建议检查下是不是打包了多份 Vue 代码，当项目中存在多份 Vue 代码时可能出现此问题
