### ISSUE TITLE
项目打包后线上字体文件变为了cdn，但是本地是正常的

### ISSUE THREAD

**Issue by heart-er** [youzan/vant#6393]
设备 / 浏览器
mac 10.14.6 chrome

Vant 版本
2.8.1

Vue 版本
2.6.8

重现链接
无(隐私问题无法提供链接)

描述问题
使用本地字体，没有下载远程cdn文件，但是打包后为什么字体路径变成了cdn，我已经把相关字体路径在本地都改为本地字体文件路径了！

**Comment by chenjiahan** [comment]
重复 issue: https://github.com/youzan/vant/issues/6364
