### ISSUE TITLE
DatetimePicker 时间选择 在手机端快速上下滑动以后，日期会自己自动的上下滚动

### ISSUE THREAD

**Issue by fuxinking** [youzan/vant#6394]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by 1179806811** [comment]
DatetimePicker 时间选择 在手机端快速上下滑动以后，日期会自己自动的上下滚动
