### ISSUE TITLE
[Bug Report] 上传组件限制数量，在小米10手机上选择达到上限数量时，手机闪现黑白条纹的异常。

### ISSUE THREAD

**Issue by yangmin7799** [youzan/vant#6396]
### 设备 / 浏览器
小米10

### Vant 版本
2.4.0

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater" target="_blank">https://youzan.github.io/vant-issue-generater</a>

### 描述问题
上传组件设置了限制数量，在小米10手机上选择到最大数量后，手机闪现黑白条纹的异常。

**Comment by chenjiahan** [comment]
能截图或录屏看下吗，感觉是系统问题

**Comment by yangmin7799** [comment]
截图和录屏不能发这上面呢

**Comment by chenjiahan** [comment]
可以发的

**Comment by yangmin7799** [comment]
![ab6ff1bdeb4c481a0d27ad13185f362](https://user-images.githubusercontent.com/44486854/83105301-fd436580-a0ec-11ea-8620-bff0e3d7dd66.jpg)

**Comment by yangmin7799** [comment]
选择到上限数量后就是这种反应

**Comment by chenjiahan** [comment]
从图片上看是系统的渲染问题，建议你调低数量上限试试，或者在前端进行一下图片压缩，减小图片体积
