### ISSUE TITLE
[Feature Request] nav-bar组件希望能给与设定自定义样式。特别是其背景色及字体颜色，

### ISSUE THREAD

**Issue by xiechuntao** [youzan/vant#6398]
### 这个功能解决了什么问题
自定义nav-bar样式

### 描述您想要的解决方案
项目中nav-bar的要求并总不是白底黑字，这时候就需要样式的自定义，之前总会使用外部样式 important覆盖的方式，但这次更新组件库后发现覆盖不上的情况。顾此建议增加自定义nav-bar样式的配置项

### 建议的API是什么样的
可以传入自定义class和style。

**Comment by chenjiahan** [comment]
暂无计划提供喔，通过样式直接覆盖是可以生效的，如果没生效，建议看下是不是选择器没选对

**Comment by xiechuntao** [comment]
> 暂无计划提供喔，通过样式直接覆盖是可以绩效的，如果没绩效，建议看下是不是选择器没选对

已经发现解决了，之前写在后代选择器中使用important的确覆盖不了（老版本2.2.x可以覆盖），刚在全局状态下用标签选择器则成功覆盖了默认样式。
