### ISSUE TITLE
DropdownMenu 下拉菜单多选

### ISSUE THREAD

**Issue by Nick091608** [youzan/vant#6400]
重现地址：https://youzan.github.io/vant/#/zh-CN/dropdown-menu#dai-ma-yan-shi
因项目需求在官网找了好久都没找到下拉可以支持多选的配置，
可以增加多选item需求吗

**Comment by chenjiahan** [comment]
暂无计划支持多选呢，如果需要多选可以通过插槽自行实现

**Comment by Nick091608** [comment]
文档没说插槽怎么用啊

**Comment by chenjiahan** [comment]
有的 https://youzan.github.io/vant/#/zh-CN/dropdown-menu#zi-ding-yi-cai-dan-nei-rong

**Comment by Nick091608** [comment]
就是自定义菜单 的筛选那一项是吗
