### ISSUE TITLE
[Bug Report] 下拉菜单在better-scroll滚动时使用异常

### ISSUE THREAD

**Issue by Candane** [youzan/vant#6404]
我在cell单元格的右边内容默认#default插槽中使用下拉菜单van-dropdown-menu，外层有better-scroll组件，一旦往下滚动后，下拉菜单显示列表就会错乱

**Comment by chenjiahan** [comment]
这是 better-scroll 设置 transform 导致子元素的 fixed 属性失效了，可以设置 get-container：

```html
<van-dropdown-item get-container="body" />
```
