### ISSUE TITLE
van-datetime-picker type=date时，v-model有时候默认选中日期不正确

### ISSUE THREAD

**Issue by zjxlbw** [youzan/vant#6405]
手动改变v-model值和使用选择器 改变v-model的值配合使用的话，默认选中日期不正确。

比如：
① 使用年月日时间选择器 选中了2020-05-28
② 然后手动改变v-model的值为2020-05-27
③ 再打开时间选择器，此时还是默认选中2020-05-28，并没有选中2020-05-27

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
