### ISSUE TITLE
[Bug Report] van-field组件排列和聚焦问题

### ISSUE THREAD

**Issue by 695648896** [youzan/vant#6406]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.4

### Vue 版本
2.6.9

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/field" target="_blank">https://youzan.github.io/vant/#/zh-CN/field</a>

### 描述问题
field支持左侧label和input的上下排列吗?
field支持点击label聚焦相应的input吗？

**Comment by chenjiahan** [comment]
不支持的喔，暂时没有计划在组件内支持这两个功能，排列可以通过覆盖样式来实现，聚焦可以自己监听下 label 的点击事件
