### ISSUE TITLE
2.5.8版本及以后的版本中ImagePreview组件会出现预览图片报错的现象

### ISSUE THREAD

**Issue by inyoureyes** [youzan/vant#6408]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

按照文档中，组件调用的方式，点击图片进行预览，会报错，导致图片预览失败
经测试，2.5.7版本正常，2.5.8版本及以上均会报错
![Uploading 批注 2020-05-28 222027.png…]()

---
![Uploading 批注 2020-05-28 221939.png…]()

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by inyoureyes** [comment]
[](url)
![批注 2020-05-28 221939](https://user-images.githubusercontent.com/20148021/83154317-921c8200-a132-11ea-934b-8cc9136dda01.png)
![批注 2020-05-28 222027](https://user-images.githubusercontent.com/20148021/83154353-9c3e8080-a132-11ea-8e0c-d22235960ace.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
