### ISSUE TITLE
[Bug Report] Tabs粘性布局offset-top=0的时候在企业微信浏览器会出现抖动现象

### ISSUE THREAD

**Issue by xiong201** [youzan/vant#6409]
### 设备 / 浏览器
企业微信浏览器

### Vant 版本
2.6.1

### Vue 版本
2.6.6

### 重现链接
<a href="https://codesandbox.io/s/determined-shirley-76kxj?file=/src/components/VantTabs.vue" target="_blank">https://codesandbox.io/s/determined-shirley-76kxj?file=/src/components/VantTabs.vue</a>

### 描述问题
tab嵌套使用粘性布局固定在头部，但是设置offset-top=0的时候在企业微信浏览器会出现抖动现象。能不能给tab添加个fixed属性和top属，就不需要使用sticky

**Comment by chenjiahan** [comment]
直接设置就可以的呢

```css
.van-tabs__wrap {
  position: fixed;
}
```

**Comment by xiong201** [comment]
直接设置position: fixed是可以固定。但是我这边tab嵌套tab，两个tab都要固定，直接设置position: fixed的话，两个tab都是这个样式，就会有个tab被另一个tab覆盖住了。

**Comment by xiong201** [comment]
@chenjiahan

**Comment by chenjiahan** [comment]
还可以设置 top 呀。

**Comment by xiong201** [comment]
@chenjiahan 设置top的话，两个嵌套tab也是这个top值。现在情况是这样的，我这边设置两个嵌套tab，父tab设置.van-tabs__wrap {position: fixed;top:0}会作用到子tab。就是说父tab和子tab的van-tabs__wrap在嵌套tab无法做出区分

**Comment by chenjiahan** [comment]
加个 class 不就可以区分了吗

```html
<van-tabs class="parent">
  <van-tab>
    <van-tabs />
  </van-tab>
</van-tabs>
```

```css
.parent .van-tabs__wrap {
  position: fixed;
}
```

**Comment by xiong201** [comment]
感谢你的解答，因为我这边给style标签加上了scope，所以只能使用深度选择器进行设置。现在我将父tabs的scope去掉就可以直接设置了。
