### ISSUE TITLE
Vue.prototype.$toast = Toast

### ISSUE THREAD

**Issue by shijunti19** [youzan/vant#641]
vue init youzan/vue-cli-template-vant projectName
main.js里面加入下面2行按需引入组件
import { Toast } from 'vant';
Vue.use(Toast);
然后他提示vue的错误

注意，我要全局 引入所有的Vue.prototype.$toast = Toast 这种
vux里就是这样做的
方式二. 按需引入组件
import { Toast } from 'vant'
Vue.use(Toast)

会提示：
`function Vue$3(options) {
  if ("development" !== 'production' &&
    !(this instanceof Vue$3)
  ) {
    warn('Vue is a constructor and should be called with the `new` keyword');
  }
  this._init(options);
}`

`this.$toast('复制成功，发给好友吧')`
我要使用上面这个，他报错，我应该怎么用

**Comment by chenjiahan** [comment]
不需要通过 Vue.use 注册 Toast，通过 import 引入 Toast 组件即可，会自动在 prototype 上添加 $toast 方法

**Comment by shijunti19** [comment]
@chenjiahan import引入Toast 是必须要使用的，例如我在自己的文件里引入，不是vue组件
`import { Toast } from 'vant';`
Toast 这时候没用到，vscode会提示你这个代码没用到非常不友好。
this.$toast('复制成功，发给好友吧')
这个的话，可以全局引入了！
vux里就有解决
`import { AlertPlugin, ToastPlugin } from 'vux'

Vue.use(AlertPlugin)
Vue.use(ToastPlugin)`
按需引入，我只需要main.js里引入我需要的全局插件，例如Toast ，alert等等都应该是全局，因为不是template也会用到
