### ISSUE TITLE
van-field 的 rules 验证问题。

### ISSUE THREAD

**Issue by Asagiqianmu** [youzan/vant#6411]
van-field 赋值为0的时候 触发了 rules 未通过
但是手动输入0的时候 没有触发。看一下可以帮忙解决一下

**Comment by Asagiqianmu** [comment]
![image](https://user-images.githubusercontent.com/26704836/83218380-76e85b80-a1a0-11ea-95e4-c65c36eb6c8e.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
