### ISSUE TITLE
[Bug Report] 加载按钮垂直错位

### ISSUE THREAD

**Issue by Duncanxyz** [youzan/vant#6413]
### 设备 / 浏览器
Chrome 版本 83.0.4103.61（正式版本） （64 位）

### Vant 版本
2.8.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/duncan248/pen/qBOzMeV" target="_blank">https://codepen.io/duncan248/pen/qBOzMeV</a>

### 描述问题
加载状态按钮与旁边普通按钮错位(没有水平对齐)

**Comment by Duncanxyz** [comment]
#6414

**Comment by chenjiahan** [comment]
👍

**Comment by chenjiahan** [comment]
已发布 2.8.5 版本
