### ISSUE TITLE
[Bug Report] notice-bar 页面在第二次进入时 不会滚动

### ISSUE THREAD

**Issue by a497771654** [youzan/vant#6415]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.4

### Vue 版本
3.0.0-beta.14

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html#/zh-CN/" target="_blank">https://youzan.github.io/vant/mobile.html#/zh-CN/</a>

### 描述问题
首次点击到notice-bar页面时正常的,返回后第二次进入notice-bar页面显示不正常,不滚动。

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.8.5 版本修复
