### ISSUE TITLE
自定义样式

### ISSUE THREAD

**Issue by Wangsenshuai** [youzan/vant#6416]
### 这个功能解决了什么问题
1.自定义样式，例如一些组件内部按钮样式。

### 描述您想要的解决方案
1.能否提供class命名入口，以修改组件内部样式。

**Comment by yuxiaolei1989** [comment]
可通过 [深度作用选择器](https://vue-loader.vuejs.org/zh/guide/scoped-css.html#%E6%B7%B1%E5%BA%A6%E4%BD%9C%E7%94%A8%E9%80%89%E6%8B%A9%E5%99%A8)解决你的问题。

例如：
```
<style scoped>
.a >>> .b { /* ... */ }
</style>
```

**Comment by Wangsenshuai** [comment]
1.深度选择器会带来其他兼容性等新问题
2.还有一些组件结构上的问题，例如：AddressEdit组件选择区域不是一个整体，进而无法设置圆角等问题，

**Comment by yuxiaolei1989** [comment]
> 1.深度选择器会带来其他兼容性等新问题

这个具体会带来什么问题呢？

**Comment by Wangsenshuai** [comment]
之前有碰到编译错误问题，当然也是开发时可以处理的事情，只是我在想能否暴露出一部分class命名空间，尽量减少深度选择器的使用。

**Comment by Wangsenshuai** [comment]
主要是使用时候感觉受限比较大。其实都是可以解决的。
甚至我需不需要按钮都没有选择的余地，只能通过css样式进行隐藏等等。

**Comment by chenjiahan** [comment]
暂时没有计划提供更多 class 命名的入口，大部分场景都可以通过直接覆盖样式解决的。

```html
<van-button class="my-button" />
```

```css
.my-button {
  height: 60px;
}
```
