### ISSUE TITLE
[Bug Report]ImagePreview在微信内置浏览器无法进行手势操作

### ISSUE THREAD

**Issue by MrRabbit1993** [youzan/vant#6417]
设备 / 浏览器
微信内置浏览器

Vant 版本
2.8.4

Vue 版本
2.6.11

重现链接
https://youzan.github.io/vant/#/zh-CN/image-preview

描述问题
用微信内置浏览器访问官网的image-preview，无法进行手势操作
如：对单个预览图片进去放大滑动查看

**Comment by chenjiahan** [comment]
我试了下是可以的喔，建议你换个手机试试
