### ISSUE TITLE
[Bug Report] sku中图片预览蒙版出错

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#6418]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/sku" target="_blank">https://youzan.github.io/vant/#/zh-CN/sku</a>

### 描述问题
图片会穿透蒙版，应该是2.8.4更新后的遮罩层未适配

**Comment by chenjiahan** [comment]
重复唤起 Sku 时会有这个问题，后续会修复下

**Comment by chenjiahan** [comment]
已在 2.8.5 版本修复
