### ISSUE TITLE
官方可以在release里面提供编译后的js文件吗，可以直接用在html里面那种

### ISSUE THREAD

**Issue by fushall1104** [youzan/vant#642]
如题，
直接在html文件里面写类似这样的：
<link href="vant/xxxx/style.css" rel="stylesheet"> 
<script src="vue/xxxx/vue.js"></script>
<script src="vant/xxxx/index.js"> </script>
刚才clone了一个，没发现类似dist的文件夹

然后直接可以再html页面里面写：
<van-button size="large">按钮</van-button>

**Comment by chenjiahan** [comment]
可以直接使用 CDN 链接，详见文档
https://www.youzanyun.com/zanui/vant#/zh-CN/quickstart

**Comment by fushall1104** [comment]
@chenjiahan   谢谢:)
