### ISSUE TITLE
[Feature Request] van-list 建议加上虚拟列表功能

### ISSUE THREAD

**Issue by mingtianyihou33** [youzan/vant#6421]
### 这个功能解决了什么问题
当列表数据非常多时生成的dom节点过多导致页面卡顿。

### 描述您想要的解决方案
使用常用的虚拟列表方案即可，比如动态的padding值，只显示滚动到列表内容，不要把每一项都渲染出来

### 建议的API是什么样的
默认就支持就行

**Comment by chenjiahan** [comment]
暂无计划支持喔，目前 List 组件子元素的渲染是完全由使用者控制的，List 无法感知到子元素的结构，比如有这样的用法：

```html
<van-list>
  <div>
    <van-cell />
    <van-cell /> 
    <van-cell />
  </div>
</van-list>
```

这时候 List 需要操作 div 的子节点 cell 来实现虚拟滚动，但 List 无法判断应该操作 div 还是 cell，因此 List 组件本身是无法实现虚拟滚动的。

**Comment by ShuangDa1018** [comment]
> 暂无计划支持喔，目前 List 组件子元素的渲染是完全由使用者控制的，List 无法感知到子元素的结构，比如有这样的用法：
> 
> ```
> <van-list>
>   <div>
>     <van-cell />
>     <van-cell /> 
>     <van-cell />
>   </div>
> </van-list>
> ```
> 
> 这时候 List 需要操作 div 的子节点 cell 来实现虚拟滚动，但 List 无法判断应该操作 div 还是 cell，因此 List 组件本身是无法实现虚拟滚动的。

找的理由太垃夸了，有没有vue3其他ui库推荐
