### ISSUE TITLE
It is invalid to set [badge = "100"] in wechat applet, and directly modify the official sample program van weapp.

### ISSUE THREAD

**Issue by zack542** [youzan/vant#6423]
1.It is invalid to set [badge = "100"] in wechat applet, and directly modify the official sample program van weapp.
2..It is invalid to set [ icon-size="5rem"] in wechat applet, and directly modify the official sample program van weapp.

**Comment by chenjiahan** [comment]
请到 vant-weapp 仓库下反馈，感谢配合
