### ISSUE TITLE
VANT在微信小程序中部分属性无效

### ISSUE THREAD

**Issue by zack542** [youzan/vant#6424]
如下代码
` <van-grid column-num="3" icon-size="5rem" >
    <van-grid-item badge="100"  icon="https://yanxuan.nosdn.127.net/c6fd8835a6400b7da7a016ad85506b69.png" text="文字" />
    <van-grid-item icon="photo-o" text="文字" />
    <van-grid-item icon="photo-o" text="文字" />
    <van-grid-item icon="photo-o" text="文字" />
  </van-grid>`
在网页中能正常生效badge和 icon-size  但是在微信小程序中缺不能生效，无法改变里面图片的大小
我导入的组件如下
`{
  "navigationBarBackgroundColor":"#00BEAF",
  "usingComponents": {
    "van-grid": "/dist/grid/index",
    "van-grid-item": "/dist/grid-item/index"
    
  }
}`
最开始我以为是我代码问题，结果我去下载了官方示例程序vant-weapp ，然后直接在vant-weapp的example中去 加上这两个属性也无效，如果无效我该这么设置图片大小

**Comment by chenjiahan** [comment]
vant-weapp 的 Grid 组件目前不支持 badge 属性喔，以文档为准。

如果需要此功能，可以到 vant-weapp 仓库下提 issue
