### ISSUE TITLE
[Feature Request] keyboard弹起时可以把input顶到视图里面吗

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#6428]
### 这个功能解决了什么问题
keyboard弹起时可以把input顶到视图里面吗，类似原生虚拟键盘弹起时，页面上移，把正在输入的input顶到试图上，这样就可以看到输入的内容。

### 描述您想要的解决方案
keyboard弹起时可以把input顶到视图里面吗，类似原生虚拟键盘弹起时，页面上移，把正在输入的input顶到试图上，这样就可以看到输入的内容。

### 建议的API是什么样的
无~

**Comment by chenjiahan** [comment]
暂无计划支持呢，建议自行控制一下滚动条位置哈
