### ISSUE TITLE
新增加的功能

### ISSUE THREAD

**Issue by misskter** [youzan/vant#643]
希望可以增加一个类似于9宫格那样的布局，类似于京东首页中间那块，标签是京东超市，签到等等那样的布局方式。现在我在使用这个前台框架，开发起来真的很快，而且也有例子，很感谢开发人员

**Comment by misskter** [comment]
缺少自动补全的功能，这个可以实现的

**Comment by chenjiahan** [comment]
感谢你的建议~
1. 九宫格布局：后续我们通过升级 Layout 组件并支持 flex 布局，届时可以通过 Layout 组件来实现类似的布局
2. 自动补全：不知道你指的是哪种场景，移动端自动补全应该比较少见

**Comment by misskter** [comment]
在搜索那里的自动补全，就是输入内容以后出现一块div里面是个List形式展示与之相关的数据，电商的网站经常见到的一个场景

**Comment by chenjiahan** [comment]
这个建议根据实际需求自己实现，布局可以使用 Cell 组件
