### ISSUE TITLE
Uploader 文件上传组件设置capture为camera想直接调起摄像头，部分安卓手机还是可以选择相册

### ISSUE THREAD

**Issue by qq423803750** [youzan/vant#6430]
Uploader 文件上传组件设置capture为camera想直接调起摄像头，部分安卓手机还是可以选择相册

**Comment by qq423803750** [comment]
手机型号为realme X

**Comment by sdfjshdjwenwen** [comment]
我也是同样的问题你解决了吗

**Comment by qq423803750** [comment]
> 我也是同样的问题你解决了吗

没有，坐等大佬回复

**Comment by chenxi5211993** [comment]
很多安卓手机，掉不起来照相机，不知道你们遇到了没，点击相机，没有反应

**Comment by qq423803750** [comment]
> 很多安卓手机，掉不起来照相机，不知道你们遇到了没，点击相机，没有反应

对的，安卓兼容难做

**Comment by chenxi5211993** [comment]
> > 很多安卓手机，掉不起来照相机，不知道你们遇到了没，点击相机，没有反应
> 
> 对的，安卓兼容难做

之前是可以的啊，我测试了，昨天测试告诉我打不开摄像头，用原生input type=‘file’也打不开，在手机浏览器中能打开，webapp中就打不开了。。咋整

**Comment by cuiwang** [comment]
【华为 Android10.0】调用不起来摄像头，选文件可以。（不是权限问题，其他控件可以调用摄像头）

**Comment by chenjiahan** [comment]
这个是系统本身的问题，和组件无关呢，跟这个问题类似：https://github.com/youzan/vant/issues/6015

**Comment by zech126** [comment]
一样踩坑了，，华为手机调不起相机
