### ISSUE TITLE
[Bug Report] van-radio-group 默认选中问题

### ISSUE THREAD

**Issue by DavidLeeForWin** [youzan/vant#6431]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.4

### Vue 版本
2.9.6

### 描述问题
单选框
van-radio-group v-model="userInfo.sex" 
 v-model 只能是字符串数字  不能是int类型

**Comment by DavidLeeForWin** [comment]
如:
"0" 就可以  
0 则不可以

**Comment by chenjiahan** [comment]
v-model 的值是和 Radio 的 name 值对应的，如果 name 是 number 类型，v-model 就可以是数字 0
