### ISSUE TITLE
[Bug Report] 在created执行Toast之后, 数据更改无法重新渲染DOM

### ISSUE THREAD

**Issue by way-huang** [youzan/vant#6433]
### 设备 / 浏览器
MacOS,iOS/Safari

### Vant 版本
2.8.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/wayh/pen/WNrevZe" target="_blank">https://codepen.io/wayh/pen/WNrevZe</a>

### 描述问题
当 DOM 结构存在 iframe 并且 created 执行 Toast, 数据更改无法出发 DOM 渲染;

以下3个方法任意1个都可以暂时解决问题
- 移除 iframe
- mounted 执行 Toast 
- forceUpdate

**Comment by chenjiahan** [comment]
试了下复现链接里可以正常触发渲染呢，你是怎么操作的

**Comment by way-huang** [comment]
> 试了下复现链接里可以正常触发渲染呢，你是怎么操作的

直接用 safari 打开，点击 reverse 按钮，Hello 并没有变化，必须ForceUpdate之后才行

![CleanShot 2020-06-01 at 22.08.32.gif](https://i.loli.net/2020/06/01/RYeq7BEkDGM2g6d.gif)

**Comment by chenjiahan** [comment]
感觉是浏览器内核的 bug，组件没什么可以兼容的。。
