### ISSUE TITLE
van-field设置type="number"，在ios设备及安卓8以下版本无法唤起数字键盘

### ISSUE THREAD

**Issue by linxingli** [youzan/vant#6434]
van-field 设置 type="number，在ios设备及安卓8以下版本无法唤起数字键盘

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
这个问题是因为 inputmode 属性在低版本系统不支持，因此会自动降级到 text 键盘，不影响使用
