### ISSUE TITLE
[Feature Request] Notify组件支持组件调用

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#6436]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.4

### Vue 版本
2.6.11

### 描述问题
Notify只能显示文本 为什么不支持组件调用呢 例如想弹出的消息中显示图片和文字

**Comment by chenjiahan** [comment]
后续会支持

**Comment by chenjiahan** [comment]
已在 2.8.5 版本支持
