### ISSUE TITLE
[Bug Report] 图标在移动端浏览器渐变色有问题

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#6437]
### 设备 / 浏览器
iphone11ProMax

### Vant 版本
2.8.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsfiddle.net/h63efaq5/17/" target="_blank">https://jsfiddle.net/h63efaq5/17/</a>

### 描述问题
下图是pc端的
![image](https://user-images.githubusercontent.com/32523475/83453320-dbe7ce00-a48c-11ea-9a43-91f86b20be20.png)

但是在移动端图标就被干掉了 看不见了

最后经过调试发现 是`@vant/icon/src/index.less`下的
```
 &::before {
    display: inline-block;
  }
```
这里导致的 
修改成 `display: block`可以解决
![IMG_2272](https://user-images.githubusercontent.com/32523475/83453547-439e1900-a48d-11ea-9ded-ecadb796ad84.PNG)

**Comment by chenjiahan** [comment]
这里的布局暂时没有计划调整，如果你的场景是需要设置为 block 的，手动覆盖下样式就可以了
