### ISSUE TITLE
van-uploader__input-wrapper建议加上width: 100%;

### ISSUE THREAD

**Issue by tyzChar** [youzan/vant#6440]
**这个功能解决了什么问题**
由于自定义上传样式，涉及到设置自定义样式的宽度问题。所有的自定义控件都包裹在van-uploader__input-wrapper中，如果width不设置为100%，自定义控件没办法自动填充100%宽度。

**描述您想要的解决方案**
为van-uploader__input-wrapper加上width: 100%;即可为自定义控件的父控件默认为100%宽度

**建议的API是什么样的**
`.van-uploader__input-wrapper { position: relative; width: 100%; }`

**Comment by tyzChar** [comment]
https://youzan.github.io/vant-issue-generater 此链接无法创建，显示404

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/83512741-3facde00-a503-11ea-8571-d07f0f5f717b.png)

设置 width: 100% 的话，会导致上传区域和预览图片不在一行上，所以不准备默认添加该样式。

如果有需要的话，自行覆盖样式即可
