### ISSUE TITLE
[Feature Request] 下拉菜单 DropdownMenu 增加 ssr 特性 

### ISSUE THREAD

**Issue by ltinyho** [youzan/vant#6444]
### 这个功能解决了什么问题
使 DropdownMenu 支持 ssr

### 描述您想要的解决方案
`DropdownMenu` 或者 `DropdownItem ` 增加 `lazy-render`  `props` 控制 `Popup` 的 `lazy-render`属性

### 建议的API是什么样的
```js
  props: {
    lazyRender: {
      type: Boolean,
      default: true,
    },
  },
```

**Comment by chenjiahan** [comment]
下个版本加上

**Comment by ltinyho** [comment]
> 下个版本加上

已提 PR,下个版本预计什么时候 release 呢?

**Comment by chenjiahan** [comment]
@ltinyho 提重复了 https://github.com/youzan/vant/pull/6454

**Comment by ltinyho** [comment]
@chenjiahan 2333,是一周左右一个小版本吗?

**Comment by chenjiahan** [comment]
嗯呐，一般每周结束的时候会发个版本

**Comment by chenjiahan** [comment]
已在 2.8.5 版本支持
