### ISSUE TITLE
[Bug Report] indexbar组件ios下开启-webkit-overflow-scrolling: touch后fixed定位的sidebar失效会跟随滚动

### ISSUE THREAD

**Issue by Cristop3** [youzan/vant#6448]
### 设备 / 浏览器
ios

### Vant 版本
2.8.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/index-bar" target="_blank">https://youzan.github.io/vant/#/zh-CN/index-bar</a>

### 描述问题
您好！indexbar组件ios下开启-webkit-overflow-scrolling: touch后fixed定位的sidebar失效会跟随滚动

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by Cristop3** [comment]
> 麻烦提供一下 codesandbox 复现链接
只有在ios真机环境下才能复现，这里我贴个gif图上来
![indexbar](https://user-images.githubusercontent.com/15847123/83705392-5c522e80-a647-11ea-8aa6-cc904e41066c.gif)
布局大致为：
html:
<div class="home">
     <van-index-bar>
          <van-index-anchor :index="item.index" v-for="item in ds" :key="item.index" />
     </van-index-bar>
</div>
css:
.home{
    overflow-x:hidden;
    overflow-y:auto;
     -webkit-overflow-scrolling:touch;
}

**Comment by Cristop3** [comment]
@chenjiahan thx

**Comment by chenjiahan** [comment]
我试了下没问题呢，你是不是在父元素加了 tramsform，导致 fixed 失效了

**Comment by MyCodeMyWorld** [comment]
我的也是，安卓环境是好的，IOS不行。
