### ISSUE TITLE
[Bug Report] 苹果手机，当表单过长，点击文本框，弹起软键盘，nav-bar顶部固定fixed失效

### ISSUE THREAD

**Issue by yuchuanchuan** [youzan/vant#6450]
### 设备 / 浏览器
苹果手机/微信浏览器

### Vant 版本
2.8.4

### Vue 版本
2.6.1

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/nav-bar" target="_blank">https://youzan.github.io/vant/#/zh-CN/nav-bar</a>

### 描述问题
苹果手机，当表单过长，点击文本框，弹起软键盘，nav-bar顶部固定fixed失效；且滚动时，nav-bar跟随区域内容滚动，不能在顶部进行固定定位

**Comment by chenjiahan** [comment]
请确认下你是否正确设置了 fixed 属性，以及组件的父元素中没有设置 transform 属性（transform 会导致 fixed 失效）

**Comment by yuchuanchuan** [comment]
是苹果手机，组件和父元素没有用transform。而且，苹果手机，软键盘弹起，会造成fixed失效；这个问题很普遍。

**Comment by chenjiahan** [comment]
这个是系统本身的问题了，木有什么好办法处理
