### ISSUE TITLE
缺少 van-field__label--left样式

### ISSUE THREAD

**Issue by 98oi98** [youzan/vant#6452]
![image](https://user-images.githubusercontent.com/6896883/83626319-d04cf200-a5c7-11ea-87d7-ffe37d1d319e.png)

**Comment by chenjiahan** [comment]
默认就是 left

**Comment by 98oi98** [comment]
下面是demo代码和效果,并不能左对齐，查看样式,只有right和center，并不存在left的样式
![image](https://user-images.githubusercontent.com/6896883/83702946-c0252900-a640-11ea-8d33-5f6d3154e73f.png)
![image](https://user-images.githubusercontent.com/6896883/83702962-cb785480-a640-11ea-9ad0-717882ceb2ec.png)

**Comment by 98oi98** [comment]
> 默认就是 left
下面是demo代码和效果,并不能左对齐，查看样式,只有right和center，并不存在left的样式
![image](https://user-images.githubusercontent.com/6896883/83703190-607b4d80-a641-11ea-828f-873db8afa11b.png)

<template>
    <van-form label-align="left" >
      <van-field
        label="公司名称"
        placeholder="请输入公司名称"
      />
      <van-field
        label="联系人"
        placeholder="请输入联系人"
      />
      <div style="margin: 16px;">
        <van-button round block type="info" native-type="submit">
          提交
        </van-button>
      </div>
  </van-form>
</template>
<script>
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  }
}
</script>

**Comment by chenjiahan** [comment]
因为浏览器默认就是 left 呀，你是不是在父级设置了 `text-align: center`

**Comment by 98oi98** [comment]
> 因为浏览器默认就是 left 呀，你是不是在父级设置了 `text-align: center`

感谢您的回复。

是的，这个问题我发现了，但是个人觉得既然是组件并且提供了可以设置的属性，这个结果似乎并不是很合理。并且官方文档上也没有说明，容易让人产生误解。

谢谢

**Comment by chenjiahan** [comment]
下个版本会加一个默认值 `text-align: left;`，这样就不会被父级元素的样式影响了

**Comment by diaoduobao** [comment]
label的字体颜色怎么自定义？？
