### ISSUE TITLE
下拉刷新问题，和建议出个表单重置的功能

### ISSUE THREAD

**Issue by zhaungsheng** [youzan/vant#6457]
1.下拉刷新时，下拉列表有滚动条时，无法滚动到顶部，需要动态计算滚动条高度去禁用启用下拉刷新，希望能解决这个问题。
2.希望增加重置表单功能，和回到顶部功能

**Comment by chenjiahan** [comment]
第一点没看懂，麻烦按照模板创建 issue，提供下 codesandbox 复现链接

表单重置参见 https://github.com/youzan/vant/issues/6058

回到顶部暂无计划支持
