### ISSUE TITLE
[Bug Report] 重复点击 tabbar item 触发路由错误

### ISSUE THREAD

**Issue by Airkro** [youzan/vant#6458]
### 设备 / 浏览器
All

### Vant 版本
2.8.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-zvu56?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-zvu56?file=/src/App.vue</a>

### 描述问题
不管是不是路由模式，使用 to 定义路由跳转，当处于当前页面时，点击对应链接会触发错误。

![image](https://user-images.githubusercontent.com/12206891/83722388-77389900-a66f-11ea-93fb-0ee654d8d04a.png)

**Comment by noteScript** [comment]
这不是vant的bug范畴，即便你使用原生的router-link也无法避免。
你可以参考这里修改：https://codesandbox.io/s/vant-issue-moban-d5q5g?file=/src/Main.vue

**Comment by Airkro** [comment]
router-link 不会触发这个问题，demo 已更新

**Comment by chenjiahan** [comment]
代码里本身有处理重复路由的错误的，不过 vue-router 3.3 版本改了 Error 的 name，导致代码失效了，下个版本会兼容一下

**Comment by vvni** [comment]
-。-我也遇到了，那我就不pr了

**Comment by chenjiahan** [comment]
已在 2.8.6 版本修复
