### ISSUE TITLE
Popup以及Picker同时使用时存在的一个问题，是否能考虑在Popup点击遮罩层关闭时提供相应的事件

### ISSUE THREAD

**Issue by MinimalistYing** [youzan/vant#646]
**What is the current behavior?**
将Picker放在Popup中，当用户点击选项时弹出Popup进行选择
如果用户滑动了选择项但并没有点击确认，而是点击遮罩层将Popup隐藏了，取消了这次操作
再次点击选项时Picker的位置停留在关闭前滑动结束的位置

**What is the expected behavior?**
我们希望再用户再次点击选项时Picker的位置仍停留在上次确认的选择项上，而不是上次滑动后停留的最后选项上

通过查阅API我们现在选择的实现方式是在点击取消按钮时通过以下方式实现
```
cancel() {
	this.show = false //关闭popup
	this.columns = [{
		values: ['杭州', '宁波', '温州', '嘉兴', '湖州'],
		defaultIndex: this.selectedIndex // 切换回最近一次的选择
	}]
}
```

现在的问题时，我们找不到相应的方式来判断用户在隐藏Popup时究竟是点击确认按钮后隐藏的
或是点击取消按钮后隐藏的
又或是点击遮罩隐藏的

PS: 当然我们也可以选择禁止用户通过点击遮罩来隐藏Popup
但是我觉得Popup组件在自身因点击遮罩层而关闭时能emit相应的事件
这样我们才能在期间处理一定逻辑

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
win7
vant version: 0.12.5

**Comment by chenjiahan** [comment]
感谢反馈，后续会添加 click-overlay 对应的事件

**Comment by chenjiahan** [comment]
已在 0.12.11 版本中支持

**Comment by MinimalistYing** [comment]
谢谢~ 效率真高 赞！
