### ISSUE TITLE
[Feature Request] AddressEdit 省市区选择器没有选项改变时change时间

### ISSUE THREAD

**Issue by 5guang** [youzan/vant#6466]
### 这个功能解决了什么问题
需要通过接口调用回去省市区列表

### 描述您想要的解决方案
省市区选择器增加选项改变时change事件

### 建议的API是什么样的
和Area组件的change事件一样

**Comment by chenjiahan** [comment]
change 事件有的，只是文档里没标注，后续会完善下文档

**Comment by chenjiahan** [comment]
目前 AddressEdit 已经对外提供出很多事件了，比如 change-area，如果再新增一个选项改变的事件，在命名上会有冲突，而且必要性不是很强，所以暂时不会提供这个事件。
