### ISSUE TITLE
以js方式引入<template #left>这种标签不起作用

### ISSUE THREAD

**Issue by hsdtk** [youzan/vant#6467]
<template #left>

**Comment by hsdtk** [comment]
<van-swipe-cell>
  <template #left>
    <van-button square type="primary" text="选择" />
  </template>
  <van-cell :border="false" title="单元格" value="内容" />
  <template #right>
    <van-button square type="danger" text="删除" />
    <van-button square type="primary" text="收藏" />
  </template>
</van-swipe-cell>
类似这种 在html中就不起作用

**Comment by hsdtk** [comment]
`<van-swipe-cell>
  <template #left>
    <van-button square type="primary" text="选择" />
  </template>
  <van-cell :border="false" title="单元格" value="内容" />
  <template #right>
    <van-button square type="danger" text="删除" />
    <van-button square type="primary" text="收藏" />
  </template>
</van-swipe-cell>`
类似这种，页面直接js引入vant 这种就不起作用

**Comment by chenjiahan** [comment]
注意 Vue 版本要大于 2.6.0 才能使用 #left 的语法

**Comment by chenjiahan** [comment]
另外需要留意下这个问题：https://youzan.github.io/vant/#/zh-CN/quickstart#zai-html-zhong-wu-fa-zheng-que-xuan-ran-zu-jian
