### ISSUE TITLE
[Bug Report] field 组件formater方法在数据改动后不会重新执行

### ISSUE THREAD

**Issue by fengyun2** [youzan/vant#6476]
### 设备 / 浏览器
小米8/自带浏览器

### Vant 版本
2.8.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-h85gu?file=/src/App.vue:4030-4041" target="_blank">https://codesandbox.io/s/vant-issue-moban-h85gu?file=/src/App.vue:4030-4041</a>

### 描述问题
field 组件formater方法在数据改动后不会重新执行

![image](https://user-images.githubusercontent.com/8147202/83957994-60788900-a89f-11ea-9aa1-1e8c898084e0.png)

![image](https://user-images.githubusercontent.com/8147202/83958009-75551c80-a89f-11ea-9bc7-1ae9d1a031c9.png)

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.8.6 版本修复
