### ISSUE TITLE
vant-dialog  内部better-scroll 无法滚动

### ISSUE THREAD

**Issue by Live-forever** [youzan/vant#6480]
浏览器
chrome最新版

Vant 版本
2.2.10

Vue 版本
2.6.10

描述问题

dialog 里面用了 better-scroll 导致无法滚动， 没有dialog包裹则可以正常滚动

示例代码： 

![image](https://user-images.githubusercontent.com/30582050/83989538-4a3efb80-a979-11ea-93bf-332d748ee762.png)

**Comment by chenjiahan** [comment]
可以把 lock-scroll 属性关掉试下，另外 Vant 不会专门去适配 better-scroll

**Comment by Live-forever** [comment]
谢谢，这是这个属性影响了！已解决.


| |
陆文祥
|
|
邮箱：18056613516@163.com
|

签名由 网易邮箱大师 定制

在2020年06月08日 19:07，neverland 写道：

可以把 lock-scroll 属性关掉试下，另外 Vant 不会专门去适配 better-scroll

**Comment by cuiWant** [comment]
我解决了这个问题，但是遇到了 复选框无法使用的问题 。。。
