### ISSUE TITLE
[Bug Report] van-field在ios系统自动带入验证码功能时无法成功赋值

### ISSUE THREAD

**Issue by waitssnull** [youzan/vant#6482]
### 设备 / 浏览器
ios 系统大于13.4.1苹果手机

### Vant 版本
2.2.0

### Vue 版本
2.5.2

### 重现链接
<a href="http://192.168.10.79:8080/car-insurance/home链接bug已修复，无法查看了" target="_blank">http://192.168.10.79:8080/car-insurance/home链接bug已修复，无法查看了</a>

### 描述问题
vant 2.2.0  ~ 2.8.5 在系统大于13.4.1后的输入框，当获取验证码，使用苹果手机键盘的自动带入功能时，输入框赋值无效

**Comment by chenjiahan** [comment]
是在 vant 2.2.0 之前的版本没有这个问题嘛？比如 2.1.8
