### ISSUE TITLE
[Feature Request] 请问官方能出一套uniapp版的vant ui吗

### ISSUE THREAD

**Issue by 104828720** [youzan/vant#6484]
### 这个功能解决了什么问题
现在国内很多公司和个人都使用uniapp开发，但vantui中有些组件方法（例如：onShow）与uniapp中生命周期冲突

### 描述您想要的解决方案
希望官方能为uniapp出个ui版本，让vant应用面扩大，更加完善

### 建议的API是什么样的
希望官方能为uniapp出个ui版本，让vant应用面扩大，更加完善

**Comment by chenjiahan** [comment]
除了 onShow 还有其他冲突吗？ 如果只是 onShow，可以考虑调整一下命名

**Comment by 104828720** [comment]
暂时发现是这个

**Comment by chenjiahan** [comment]
onShow 下个版本会改掉

**Comment by chenjiahan** [comment]
onShow 下个版本会改掉

**Comment by chenjiahan** [comment]
已在 2.8.6 版本调整命名
