### ISSUE TITLE
[Bug Report] 按需引入组件，打包时出现警告

### ISSUE THREAD

**Issue by dongH555** [youzan/vant#6486]
### 设备 / 浏览器
macos/chrome

### Vant 版本
2.8.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/theme" target="_blank">https://youzan.github.io/vant/#/zh-CN/theme</a>

### 描述问题
chunk chunk-025dcc0e [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--10-oneOf-3-1!./node_modules/postcss-loader/src??ref--10-oneOf-3-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-3-3!./node_modules/vant/es/field/index.less
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--10-oneOf-3-1!./node_modules/postcss-loader/src??ref--10-oneOf-3-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-3-3!./node_modules/vant/es/button/index.less
   - couldn't fulfill desired order of chunk group(s)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5446

**Comment by dongH555** [comment]
> 参见 #5446

已经配置了ignoreOrder，但是还是报一样的警告

**Comment by chenjiahan** [comment]
如果配置了还是不生效，可以到 mini-css-extract-plugin 仓库下反馈

**Comment by dongH555** [comment]
> 如果配置了还是不生效，可以到 mini-css-extract-plugin 仓库下反馈

babel.config.js
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset',
  ],
  plugins: [
    [
      'import',
      {
        libraryName: 'vant',
        libraryDirectory: 'es',
        // 指定样式路径
        style: (name) => `${name}/style/less`,
      },
      'vant',
    ],
  ],
};

vue.config.js
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  publicPath: '',
  outputDir: 'dist',
  lintOnSave: false,
  configureWebpack : {
    plugins: [
      new MiniCssExtractPlugin({
        ignoreOrder: true
      })
    ],
    // cdn预加载使用
    externals: {
      'vue': 'Vue',
      'vue-router': 'VueRouter',
      'vuex': 'Vuex',
      'axios': 'axios'
    },
    resolve: {
      alias: {
        '@': path.join(__dirname, 'src'),
      }
    }
  },
  
}

**Comment by dongH555** [comment]
配置了ignoreOrder,打包时的css会有两份
dist/js/chunk-vendors.e7254e77.js       125.35 KiB        42.23 KiB
  dist/js/chunk-736c56be.bcc6db25.js      55.20 KiB         17.65 KiB
  dist/js/app.de9e62c6.js                 16.11 KiB         5.79 KiB
  dist/js/chunk-f7bdb060.5c996f25.js      12.48 KiB         4.83 KiB
  dist/js/chunk-025dcc0e.48fd285f.js      11.85 KiB         4.06 KiB
  dist/js/chunk-3cb30525.97fc9ef7.js      8.27 KiB          3.26 KiB
  dist/js/chunk-5584911d.7ca849b8.js      0.80 KiB          0.56 KiB
  dist/css/chunk-vendors.07ef5b17.css     19.39 KiB         4.05 KiB
  dist/chunk-vendors.css                  19.39 KiB         4.05 KiB
  dist/chunk-025dcc0e.css                 5.72 KiB          1.48 KiB
  dist/css/chunk-025dcc0e.918e4027.css    5.72 KiB          1.48 KiB
  dist/chunk-3cb30525.css                 4.15 KiB          1.20 KiB
  dist/css/chunk-3cb30525.04267664.css    4.15 KiB          1.20 KiB
  dist/app.css                            0.57 KiB          0.35 KiB
  dist/css/app.7babd9b8.css               0.57 KiB          0.35 KiB
  dist/css/chunk-736c56be.fa496d01.css    0.40 KiB          0.26 KiB
  dist/chunk-736c56be.css                 0.40 KiB          0.26 KiB
  dist/chunk-5584911d.css                 0.18 KiB          0.14 KiB
  dist/css/chunk-5584911d.9144da21.css    0.18 KiB          0.14 KiB

**Comment by chenjiahan** [comment]
你这样可能是重复配置 MiniCssExtractPlugin 插件了，因为 vue-cli 默认就会配置一份，你应该是通过 webpack-chain 去修改它的选项

**Comment by kangforceking** [comment]
不用在webpack-chain里再配置的，
```
module.exports = {
  ...
css: {
    extract: {
      ignoreOrder: true
    }
  }
}
```
像这样直接加上去就行了
