### ISSUE TITLE
picker如何设置初始选中默认值？

### ISSUE THREAD

**Issue by yunuli** [youzan/vant#649]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
使用对象配置 columns，传入 `defaultIndex ` 属性

**Comment by yunuli** [comment]
谢谢，看到了，看的英文文档没看懂。看中文的才懂了。。。
