### ISSUE TITLE
[Bug Report] 安卓深色模式下dialog标题或描述变透明

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#6491]
### 设备 / 浏览器
小米mix3,note3

### Vant 版本
2.6.3

### Vue 版本
2.5.2

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
安卓深色模式下dialog标题或描述变透明，链接为假的，讨论性问题，有没有遇到相同问题的

**Comment by MBearo** [comment]
什么浏览器呢？

**Comment by cangyu1993** [comment]
微信浏览器，目前这样搞了一下，看看vant什么时候适配暗黑模式吧
![image](https://user-images.githubusercontent.com/42930030/84097281-b03d8880-aa36-11ea-8811-399b01dc08f9.png)

**Comment by chenjiahan** [comment]
用米 8 试了下没复现，这个先自行适配把，Vant 近期还木有计划做暗黑模式
