### ISSUE TITLE
[Feature Request] 怎么私有化部署vant的文档

### ISSUE THREAD

**Issue by itlixiaolong** [youzan/vant#6492]
### 这个功能解决了什么问题
公司要求内网访问,我们的项目又应用了vant组件库,我们只能是用其他连外网看文档,查看很不方便,有时候官网访问速度也很慢

### 描述您想要的解决方案
可以私有化部署文档

### 建议的API是什么样的
文档可以单独部署

**Comment by chenjiahan** [comment]
可以直接 clone 仓库，然后在本地运行 yarn dev，这样就会有一个文档的 Dev Server

也可以在 vant.config.js 中修改 publicPath，然后运行 vant-cli build-site 构建文档网站，最后将构建结果部署到私有服务器上。
