### ISSUE TITLE
van-tabs这个组件下标签切换时不会缓冲每个标签页面内容滚动条的位置吗？

### ISSUE THREAD

**Issue by suyuwen1** [youzan/vant#6497]
van-tabs这个组件下标签切换时不会缓冲每个标签页面内容滚动条的位置吗？
tabs组件，在切换选项卡的时候，新切换的页面总是会保持上个页面的滚动位置

**Comment by suyuwen1** [comment]
有什么解决方法吗？

**Comment by chenjiahan** [comment]
不会的喔，有需要的话可以自行保存滚动条位置，然后通过 scrollTo 进行滚动
