### ISSUE TITLE
[Bug Report] NumberKeyboard 在 safari 上点击卡顿

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#6498]
### 设备 / 浏览器
iphone7 safari

### Vant 版本
2.8.5

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html#/zh-CN/number-keyboard" target="_blank">https://youzan.github.io/vant/mobile.html#/zh-CN/number-keyboard</a>

### 描述问题
umber-keyboard输入卡顿，快速输入时1，2，3 只能输1。可以用手机浏览器试试～ 有啥办法嘛

**Comment by anihCevol** [comment]
ios 13.4.1

**Comment by chenjiahan** [comment]
感觉是系统问题，click 事件的处理有卡顿

**Comment by chenjiahan** [comment]
试了下，确实是系统在快速点击时没触发 touch 事件，复现 demo：https://codesandbox.io/s/vant-issue-moban-0djoq?file=/src/main.js

暂时没找到兼容方案，可以等 iOS 系统更新再试下

**Comment by anihCevol** [comment]
好的

**Comment by dingjunwei1314** [comment]
有什么解决办法吗

**Comment by biaowork** [comment]
这个问题一直都存在，手机输入绝对算是个大bug，体验差的一逼，只能自己重写一个

**Comment by biaowork** [comment]
这个问题应该不是系统问题，安卓、ios都存在，手机输入绝对算是个大bug，体验差，自己重写一个没有问题

**Comment by chenjiahan** [comment]
已经在 2.9.0-beta.4 版本优化了，可以试下
