### ISSUE TITLE
[Feature Request]IndexBar可以分支出来一个这种选择组件吗

### ISSUE THREAD

**Issue by chongweishi** [youzan/vant#6500]
![image](https://user-images.githubusercontent.com/18224115/84226587-5e673200-ab0c-11ea-9207-7ee9c5c89086.png)
这种比较适合几百个选项的选择功能，左边的数据可以只显示有数据的字母，右边字母索引保留所有字母，这种在某些场景应该比TreeSelect的选择更方便一点

**Comment by chenjiahan** [comment]
选择的逻辑建议自行实现哈，IndexBar 组件不会提供

只显示有数据的字母可以通过传入 index-list 属性实现
