### ISSUE TITLE
[Bug Report] van-tabs 使用sticky粘性布局，滚动内容后再切换tab，吸顶部分会上移

### ISSUE THREAD

**Issue by kykolion** [youzan/vant#6502]
### 设备 / 浏览器
iphone8P,IOS12.4.1/微信、safari

### Vant 版本
2.8.4

### Vue 版本
2.6.10

### 重现链接
<a href="https://devspa.jiliguala.com/store-dia/index.html#/" target="_blank">https://devspa.jiliguala.com/store-dia/index.html#/</a>

### 描述问题
van-tabs 使用sticky粘性布局，滚动内容后再切换tab，吸顶部分会上移

**Comment by chenjiahan** [comment]
上面的链接打不开，麻烦提供个 codesandbox 复现链接

**Comment by kykolion** [comment]
> 上面的链接打不开，麻烦提供个 codesandbox 复现链接
还没上线，是在测试的链接，方便我给你发录屏？@chenjiahan

**Comment by kykolion** [comment]
录屏发到这个邮箱了chenjiahan@buaa.edu.cn

**Comment by chenjiahan** [comment]
使用这个创建一个复现 demo：https://codesandbox.io/s/m5v3f

**Comment by kykolion** [comment]
好奇怪啊，同样的代码和版本，我本地的两个tab内容都是先滚动一部分距离后，再点击切换tab,这个时候，内容还是会停留在之前滚动的位置那里，但是我在https://codesandbox.io/s/vant-issue-moban-uyhke?file=/src/App.vue这里编辑的代码，链接放在手机上调试，无论两个tab的内容之前是滚动到哪里，只要点击tab后，都会回到顶部，这样就复现不了了 @chenjiahan

**Comment by chenjiahan** [comment]
可以排查下是不是项目里的布局影响了

**Comment by kykolion** [comment]
我把 .van-sticky 换成position: sticky; 就没问题

**Comment by kykolion** [comment]
position: fixed;改成 position: sticky; 就好了

**Comment by kykolion** [comment]
不好意思，我再研究下，可能是我布局影响了，打扰大佬了 @chenjiahan

**Comment by chenjiahan** [comment]
好滴

**Comment by y1324** [comment]
> 不好意思，我再研究下，可能是我布局影响了，打扰大佬了 @chenjiahan

怎么样？研究出来了吗？我也是这情况。
