### ISSUE TITLE
Popup 样式错位

### ISSUE THREAD

**Issue by yangfandashuaige** [youzan/vant#6503]
### 复现的场景：
**版本：**"vant": "^2.5.3",

**注入：**
![image](https://user-images.githubusercontent.com/14069048/84246178-ccc1e980-ab38-11ea-8799-36a1a2205db4.png)

**复现**
在页面直接使用Popup弹层、弹出的效果直接偏离
目前项目中就发现这一个问题：
初步定位的问题 是样式 加载的问题，重复加载了动画的样式

请相关的作者尽快修复

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
