### ISSUE TITLE
Calendar 日历组件移动端无法滚动选择其他月份

### ISSUE THREAD

**Issue by ResponseState200** [youzan/vant#6505]
`      <van-calendar v-model="showTime" :lock-scroll="false" :row-height="56" :show-confirm="false" :show-title="false"  :style="{ height: '288px' }"   :poppable="false" type="range"  color="#39a0fb" @confirm="onConfirm" />`

在移动端渲染时,无法滚动选择其他月份,其他操作正常

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
