### ISSUE TITLE
Calendar日历组件在移动端无法滚动选择其他月份

### ISSUE THREAD

**Issue by ResponseState200** [youzan/vant#6507]
设备 / 浏览器
手机移动端,

Vant 版本
2.8.5

Vue 版本
3.0.0-beta.14

描述问题
使用Calendar日历组件,在谷歌浏览器中使用鼠标滚轮选择不同月份可正常操作,在移动端无法滑动选择其他月份,PS:项目正在开发中,未有外网链接可访问

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
