### ISSUE TITLE
[Bug Report] list的onLoad触发2次

### ISSUE THREAD

**Issue by White-Lee** [youzan/vant#6509]
### 设备 / 浏览器
Chrome 83.0.4103.97

### Vant 版本
2.8.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://1kmyn.codesandbox.io/#/" target="_blank">https://1kmyn.codesandbox.io/#/</a>

### 描述问题
当前页面滚动条不在顶部时跳转到其他带有onLoad的方法的页面，onLoad会加载2次

**Comment by chenjiahan** [comment]
List 组件需要使用 v-model 绑定 loading 状态，请参考文档用法使用

**Comment by Give-me-sweets** [comment]
兄弟，你那个解决了吗？

**Comment by White-Lee** [comment]
> 兄弟，你那个解决了吗？

解决了，就是加在前加loading。

**Comment by Give-me-sweets** [comment]
可以看一下吗？因为我加了loading还是会触发。
