### ISSUE TITLE
vant里的loading变量和原来项目的冲突，怎么重命名loading

### ISSUE THREAD

**Issue by 285878535** [youzan/vant#6512]
设备 / 浏览器
手机移动端,

Vant 版本
2.1.8

Vue 版本
2.5.2

描述问题
项目是医院项目，需要体检产生订单，所以无法提供链接
![image](https://user-images.githubusercontent.com/25810268/84339087-45c05000-abd0-11ea-9003-8b732b23f9d4.png)
如图

**Comment by chenjiahan** [comment]
不是很懂你的意思，如果是变量名的话，可以随意替换
