### ISSUE TITLE
[Feature Request] vant日历组件如何设置不可选日期？

### ISSUE THREAD

**Issue by luxiaoweb** [youzan/vant#6515]
### 这个功能解决了什么问题
需求是只能选择今天及以前的日期，今天及以后的日期不可选。请问如何设置？

### 描述您想要的解决方案
直接添加某个属性实现其功能。或者设置一个函数来实现

### 建议的API是什么样的
:options=options
 options: {
                    disabledDate (date) {
                        return date && date.valueOf() < Date.now() - 86400000;
                    }
                },

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5513
