### ISSUE TITLE
[Feature Request] Stepper 步进器希望可以添加placeholder属性的配置

### ISSUE THREAD

**Issue by yanxuequan** [youzan/vant#6517]
### 这个功能解决了什么问题
当没有值的时候可以展示提示内容，提示用户输入值的规范

### 描述您想要的解决方案
placeholder属性可配置

### 建议的API是什么样的
:placeholder="placeholder"

**Comment by chenjiahan** [comment]
已在 2.8.6 版本支持

**Comment by yanxuequan** [comment]
> 已在 2.8.6 版本支持
谢谢大佬更新的这么及时，虽然已经自己写了组件
在失去焦点后其实是想保留占位符的显示，不填充值的，不知这部分可以考虑再改进改进不

**Comment by chenjiahan** [comment]
这块应该暂时不会调整呢
