### ISSUE TITLE
[Feature Request] ActionSheet希望可以增加多选功能，并且增加事件

### ISSUE THREAD

**Issue by huanghe1991** [youzan/vant#6522]
![image](https://user-images.githubusercontent.com/26794809/84456294-373a6d00-ac92-11ea-9ede-63e659f86b70.png)
希望可以增加多选功能，并且区分一下底部的按钮和右上角的关闭按钮事件，目前是共用一个cancel事件，使得无法区分这两个动作

**Comment by chenjiahan** [comment]
多选功能暂时没有计划支持喔，建议用插槽自行实现。

底部按钮的时间和关闭按钮的事件确实应该区分下，但是改动事件名会引起 breaking change，所以短期内不会调整，在 3.0 版本中会考虑区分下命名。
