### ISSUE TITLE
如何屏蔽微信内置底部前进后退按钮

### ISSUE THREAD

**Issue by 1514100951** [youzan/vant#6525]
设备 / 浏览器
ios- 微信

Vant 版本
^2.8.5

Vue 版本
2.6.11

描述问题
微信访问并tabbar 跳转路由 ,微信下方出现内置底部前后退按钮,除了重定向调转,还有什么方式可以解决

**Comment by chenjiahan** [comment]
这个是微信本身的机制，只要 history 里不止一个路由，就会展示底部的按钮栏。

可以试试 replace 属性，估计也没啥其他方法了
