### ISSUE TITLE
[Bug Report] collapse 设置border='false' 还是有边框

### ISSUE THREAD

**Issue by zhuangxiaohui** [youzan/vant#6526]
### 设备 / 浏览器
浏览器

### Vant 版本
2.8.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-3xxdc" target="_blank">https://codesandbox.io/s/vant-issue-moban-3xxdc</a>

### 描述问题
collapse 设置border='false' 还是有边框,看源代码，
     border: this.index

**Comment by chenjiahan** [comment]
CollapseItem 的 border 属性没生效，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.8.6 版本修复

**Comment by TomorrowLM** [comment]
3.2.6也不行
