### ISSUE TITLE
Icon 浏览器兼容

### ISSUE THREAD

**Issue by a251115100** [youzan/vant#653]
搜狗浏览器(最新版)van-icon显示成小方块

**Comment by a251115100** [comment]
部分van-icon显示成小方块

**Comment by chenjiahan** [comment]
@a251115100 请问 ttf 文件加载完成了吗

**Comment by a251115100** [comment]
已经加载完了,我网站首页没显示图标,下一页显示的van-icon.我看我们官网也
![9090jjjj](https://user-images.githubusercontent.com/3240441/36729221-6b53f4ac-1bfe-11e8-8b9d-98acc0c3b384.png)
有这个问题.

**Comment by chenjiahan** [comment]
@a251115100 vant 图标采用的是 ttf 格式，在移动端各个机型可以正常加载的，PC 浏览器不会单独去做兼容

**Comment by a251115100** [comment]
ok  没问题

**Comment by wut1** [comment]
移动端也显示
![image](https://user-images.githubusercontent.com/6711217/71139820-4643e380-224a-11ea-9b99-bb1bf2c8a324.png)
