### ISSUE TITLE
[Bug Report] 多文件上传

### ISSUE THREAD

**Issue by SuperZhe** [youzan/vant#6531]
### 设备 / 浏览器
安卓/ios

### Vant 版本
2.8.5

### Vue 版本
3.0.0-beta.14

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
多文件上传，部分安卓机型不支持，可否给出具体的机型，测试现在所有安卓机型都不支持

**Comment by SuperZhe** [comment]
多文件上传，部分安卓机型不支持，可否给出具体的机型，测试现在所有安卓机型都不支持

**Comment by chenjiahan** [comment]
没有具体的机型列表呢，这个是 HTML 原生属性，可以自行搜索下
