### ISSUE TITLE
[Bug Report] Form rules使用validator 时有如下几个问题

### ISSUE THREAD

**Issue by payallmoney** [youzan/vant#6535]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
Form组件 rules使用validator 时有如下几个问题
1, validator 与 required 或 pattern 同时存在时,不生效  , 是否意味着validator  的优先级低于required 和pattern ?  正常理解来说 validator  是对原来的校验方法的覆盖 , 优先级应该是最高的才对
2, 在不设置message时 , 只有validator 方法, 无法触发failed事件 , 不管校验是否通过

**Comment by chenjiahan** [comment]
1. required（或 pattern）和 validator 同时设置时，会先执行 required 的校验，再执行 validator 校验，这个是符合预期的。如果不需要 required 规则的话，不设置就行。

2. 目前必须要有 message 才会触发校验，后续会优化下，支持不设置 message

**Comment by payallmoney** [comment]
> 1. required（或 pattern）和 validator 同时设置时，会先执行 required 的校验，再执行 validator 校验，这个是符合预期的。如果不需要 required 规则的话，不设置就行。
required 为true 或者有 pattern 值的时候 , validator 不会执行

**Comment by chenjiahan** [comment]
1. 如果 required 校验没通过，就不会继续执行 validator 了
2. 已在 2.8.7 版本支持不设置 message 字段

**Comment by xiaogaofudao** [comment]
发现2.8.7 存在form 校验bug
如果<van-form> 里面的 <van-field> 是通过 v-if 动态切换的时候。<van-form :failed 收集错误信息。存在错位现象

**Comment by xiaogaofudao** [comment]
目前通过 监听 van-field 变化。调用 this.$refs.form.resetValidation(); 暂时解决

**Comment by chenjiahan** [comment]
@xiaogaofudao 可以提供个 codesandbox 复现链接看下

**Comment by UmbraCi** [comment]
> 1. required（或 pattern）和 validator 同时设置时，会先执行 required 的校验，再执行 validator 校验，这个是符合预期的。如果不需要 required 规则的话，不设置就行。
> 2. 目前必须要有 message 才会触发校验，后续会优化下，支持不设置 message

你好，请问validator函数如何传参呢，看到默认传参是(value,rule)，其中value是表单域绑定的值，我想传个值作为这个函数的第三个实参用来跟value值进行比较，请问如何实验呢
