### ISSUE TITLE
[Bug Report] Null 显示出来了

### ISSUE THREAD

**Issue by qqcbqqkcel** [youzan/vant#6537]
### 设备 / 浏览器
win10 / chrome

### Vant 版本
2.8.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://www.yuque.com/docs/share/57f5658c-d720-4f7b-b205-0e6214d72485?#" target="_blank">https://www.yuque.com/docs/share/57f5658c-d720-4f7b-b205-0e6214d72485?#</a>

### 描述问题
Null 显示出来了

**Comment by chenjiahan** [comment]
下个版本会修复下，另外建议默认值用空字符串

**Comment by chenjiahan** [comment]
已在 2.8.7 版本修复
