### ISSUE TITLE
[Feature Request] 组件颜色不可配置

### ISSUE THREAD

**Issue by Dream2Land** [youzan/vant#6538]
### 这个功能解决了什么问题
目前组件的颜色bg,color有小部分可配置，大部分不可配置，无法按需统一风格。自己重写必须穿透全局样式。

### 描述您想要的解决方案
组件的颜色bg,color可配置，按需统一风格。

### 建议的API是什么样的
组件的颜色bg,color可配置，按需统一风格。需要的修改页面动态配置即可，无需全局穿透。

**Comment by chenjiahan** [comment]
目前没有计划给所有组件都加上 color 属性，建议通过主题定义来实现这个需求哈：https://youzan.github.io/vant/#/zh-CN/theme
