### ISSUE TITLE
建议增加Scroller组件，能够无限加载，下拉刷新

### ISSUE THREAD

**Issue by cjzu888** [youzan/vant#654]
建议增加Scroller组件，能够无限加载，下拉刷新。
这类应用场景蛮多的。从目前来看，需要Waterfall 和 PullRefresh配合，且有冲突的地方。

**Comment by chenjiahan** [comment]
@cjzu888 目前没有计划去实现这个组件，后续会解决 Waterfall 和 PullRefresh 的冲突，这样组合使用两个组件就能满足需求了
