### ISSUE TITLE
[Bug-Report] vant 全局引入

### ISSUE THREAD

**Issue by mawei75** [youzan/vant#6540]
有部分组件需要全局引入，利用for循环在全局引入过程中出现未注册的情况：
`import { Dialog, Notify, Toast, Loading, Button } from 'vant';
const commonComponents = [Dialog, Notify, Toast, Loading, Button];
for (let item in commonComponents) {
  Vue.use(item);
}
//Vue.use(Loading).use(Button);
`
Loading与Button出现未注册错误，但是把Loading和Button链式引用则不报错

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
