### ISSUE TITLE
h5  使用 Picker 选择的时候 会让无缘无故的 让选中的值回到顶部

### ISSUE THREAD

**Issue by yancylin** [youzan/vant#6543]
https://shop45304453.m.youzan.com/wscgoods/detail/35wt7vust1xod

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by chenjiahan** [comment]
我用上述链接未复现你说的问题，能否提供一个复现视频或 codesandbox 复现链接看下呢

https://codesandbox.io/s/m5v3f

**Comment by yancylin** [comment]
https://yzyimg.zhaocaihuo.com/2020-06-06%2010.46.55.mp4
录制了一个视频 主要是移动端有问题
