### ISSUE TITLE
[Feature Request] 使用popup或日历组件会导致底层页面向上滚动

### ISSUE THREAD

**Issue by luxiaoweb** [youzan/vant#6544]
### 这个功能解决了什么问题
页面有多屏，输入的时候不希望页面向上滚动，保持不变。使用了lock-scroll和其他多种方式依然无效

### 描述您想要的解决方案
添加属性直接固定底层页面

### 建议的API是什么样的
lock-scroll

**Comment by chenjiahan** [comment]
滚动是什么意思，能录个屏看下吗

**Comment by mawei75** [comment]
有点像滑动穿透问题
