### ISSUE TITLE
[Bug Report] vant 全局引入问题

### ISSUE THREAD

**Issue by mawei75** [youzan/vant#6546]
### 设备 / 浏览器
微信开发者工具

### Vant 版本
2.8.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-2itui?file=/src/main.js" target="_blank">https://codesandbox.io/s/vant-issue-moban-2itui?file=/src/main.js</a>

### 描述问题
凡是需要用到van-前缀的组件，无法通过for循环注册，只能通过单独引用或者链式引用完成，导致需要全局用到的组件需要分两部分注册

**Comment by sylvaner-h** [comment]
试一下 ```for ... of```

**Comment by mawei75** [comment]
3Q，能够通过for...of批量引用。
