### ISSUE TITLE
九宫格问题

### ISSUE THREAD

**Issue by wqnmlgbb** [youzan/vant#6547]
九宫格布局为啥是从底部开始 ，我一个页面只有一排数据，但是是在页面底部，而不是在页面顶部
还是我使用问题
另一个问题   轮播图插件是没有吗

**Comment by wqnmlgbb** [comment]
因为我放在了view标签里面，应该放在最外层

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

轮播图请使用 Swipe 组件
