### ISSUE TITLE
[Bug Report] ImagePreview自定义类

### ISSUE THREAD

**Issue by HuiGan-M** [youzan/vant#6548]
### 设备 / 浏览器
win10/Chrome

### Vant 版本
2.6.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-uq913?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-uq913?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
我想自定义类,但是我发现函数调用ImagePreview方法,其生成的组件不在app内,不是app的子元素,因此使用less自定义类是无效的,请教下如何才能使其生效呢

**Comment by ZhengXiaowei** [comment]
有个`className`属性，设置自己想要的类名，然后针对这个类名去做自己想要的样式优化就好了

**Comment by HuiGan-M** [comment]
我用了,但是生效的地方只能在vue中的index.html中写才行,而且只能是页内样式才行,外联样式不行

**Comment by ZhengXiaowei** [comment]
几个方式吧，因为我也不知道你是不是样式就写在单文件组件里的。
一个就是你利用`className`将你要的样式提取放在一个类似common.scss/stylus/less文件里，全局引用。毕竟你样式都自定义了，也不会存在样式错乱的问题。
一个就是在单文件里写样式的时候不用`scoped`属性。
一个就是看看官方能不能提供一个`get-container`的属性，指定`ImagePreview`组件的挂载节点，这样也方便你自己操作。

**Comment by HuiGan-M** [comment]
开始写在.vue单文件组件,后来发现app并没没有包裹着ImagePreview组件,所以就在index.html里面页内样式处理,但是觉得后面可能会多次出现这种情况就换成外联样式,当然问题就是没生效.不用scoped当时也想到,但是会造成全局污染,所以放弃了

**Comment by ZhengXiaowei** [comment]
你外联是怎么联的，直接在style标签里import的还是在main.js里import的？

**Comment by HuiGan-M** [comment]
没有import,  这样子<link rel="stylesheet" type="text/css" href="static/wap_vant.css">,难道是我搞错了?

**Comment by ZhengXiaowei** [comment]
我也不知道你怎么写的，要么html引入一个css文件，要么在你的共用样式里写了 在main.js里import下

**Comment by HuiGan-M** [comment]
就是在index.html直接引入的

**Comment by ZhengXiaowei** [comment]
那没道理的，因为我刚也试了 是ok的

**Comment by HuiGan-M** [comment]
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
  <link rel="icon" href="<%= BASE_URL %>index.ico">
  <title>官网</title>
  <link rel="stylesheet" type="text/css" href="static/wap_vant.css">
</head>
我就是这样的 你也是么

**Comment by HuiGan-M** [comment]
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
  <link rel="icon" href="<%= BASE_URL %>index.ico">
  <title>官网</title>
  <link rel="stylesheet" type="text/css" href="static/wap_vant.css">
</head>
我是这样的

**Comment by HuiGan-M** [comment]
<head></head>里面引入么

**Comment by HuiGan-M** [comment]
head里面引入么

**Comment by ZhengXiaowei** [comment]
恩 `<link ref="stylesheet" ref="xxx.css">`这样 生效是肯定会生效的 就是权级的问题会不会被覆盖的问题

**Comment by HuiGan-M** [comment]
那我自己再试试吧,谢谢了呢

**Comment by sylvaner-h** [comment]
看了下源码，是可以使用```get-container```属性的，[用法实例](https://youzan.github.io/vant/#/zh-CN/popup#zhi-ding-gua-zai-wei-zhi)

**Comment by HuiGan-M** [comment]
对哦,我咋忘记这个了呢,可以指定节点挂入. 谢谢呢! 我试试
