### ISSUE TITLE
[Bug Report] List组件滚动值

### ISSUE THREAD

**Issue by OrdinaryPath** [youzan/vant#6549]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.0

### Vue 版本
2.6.1

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/list" target="_blank">https://youzan.github.io/vant/#/zh-CN/list</a>

### 描述问题
当List组件在页面向下滚动后，如果不刷新页面的前提下，假如点一个筛选按钮再获取一次同一个请求接口，List组件就会记录当前位置的页数然后自动发起请求，并不会像页面刚进来的时候只加载一次数据

**Comment by chenjiahan** [comment]
1. 点击筛选按钮时，通常会重置各个变量的状态（v-model、loading、finished 等）。

2. 关于 load 事件触发的时机：List 会监听浏览器的滚动事件并计算列表的位置，当列表底部与可视区域的距离小于 offset 时，List 会触发一次 load 事件。

3. List 不会关心页数，页数是在组件外部自行控制的。
