### ISSUE TITLE
[Bug Report] tab页中如果使用下拉刷新上拉加载控件，在切换tab后，再切换回来，列表总是没有保存状态

### ISSUE THREAD

**Issue by 104828720** [youzan/vant#6551]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://wxur2.csb.app/" target="_blank">https://wxur2.csb.app/</a>

### 描述问题
tab页面中使用下拉刷新上拉加载控件，在切换tab后，再切换回来列表tab，总是没有保留之前列表滚动位置的状态，而是从第一条数据显示

**Comment by 104828720** [comment]
大神，求教下

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6497

**Comment by 104828720** [comment]
大神，的确是可以通过保存状态来实现，但感觉不符合用户使用场景，我见你tab切换只是通过隐藏页面来实现的，为何不能把状态保留下来呢？这样更符合用户使用习惯吧，如果你要切换刷新的话，大可在切换回调函数内自己处理啊，而且我的tab页面是上拉加载下来刷新的页面，你不单单要保留滑动位置，还需要把当前加载的页数保留下来，还要一次过从新加载这批数据，对性能不好，望佬大能在tab切换时把状态保留下来

**Comment by 104828720** [comment]
> 参见 #6497
大神，的确是可以通过保存状态来实现，但感觉不符合用户使用场景，我见你tab切换只是通过隐藏页面来实现的，为何不能把状态保留下来呢？这样更符合用户使用习惯吧，如果你要切换刷新的话，大可在切换回调函数内自己处理啊，而且我的tab页面是上拉加载下来刷新的页面，你不单单要保留滑动位置，还需要把当前加载的页数保留下来，还要一次过从新加载这批数据，对性能不好，望佬大能在tab切换时把状态保留下来

**Comment by chenjiahan** [comment]
抱歉，目前没有计划在组件内实现该功能呢

**Comment by 104828720** [comment]
希望vantui越来越好

**Comment by chenjiahan** [comment]
^_^

**Comment by 104828720** [comment]
大神，请问，checkboxGroup能否通过chang事件获取到我选择或取消选择的checkbox元素自定义属性呢？

**Comment by chenjiahan** [comment]
没法直接获取呢，可以通过 name 映射一下

**Comment by HuirongWow** [comment]
刷博客时看到类似问题，vue里可以通过keep-alive解决，而且保持tab页状态的需求应该还挺常见的，能够有类似的功能支持吗
