### ISSUE TITLE
[Bug Report] Field  type="tel" 无效

### ISSUE THREAD

**Issue by a497771654** [youzan/vant#6552]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.6

### Vue 版本
3.0.0-beta.15

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html#/zh-CN/field" target="_blank">https://youzan.github.io/vant/mobile.html#/zh-CN/field</a>

### 描述问题

<van-field v-model="tel" type="tel" label="手机号" />
可以输入任何字符。应该只能输入数字类型手机号格式。

**Comment by chenjiahan** [comment]
手机号并不只有数字，在不同的区域手机号有不同的格式，比如 - 号、# 号等，如果需要输入纯数字，建议使用 degit 类型
