### ISSUE TITLE
使用collapse组件,路由跳转动画失效

### ISSUE THREAD

**Issue by 1514100951** [youzan/vant#6557]
设备 / 浏览器
iphonex

Vant 版本
2.8.6

Vue 版本
2.6.11

描述问题
浏览器模拟手机端:路由跳转渐入渐出动画正常显示 iphonex:微信浏览器浏览,添加collapse的 页面,路由跳转动画失效

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
