### ISSUE TITLE
[Bug Report] vant-datetime-picker v-model 值变动 未渲染

### ISSUE THREAD

**Issue by FlyDancing** [youzan/vant#6558]
### 设备 / 浏览器
chrome  83.0.4103.106

### Vant 版本
2.8.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-datetime-3sv05?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-datetime-3sv05?file=/src/App.vue</a>

### 描述问题
修改model值 界面显示未更新

**Comment by chenjiahan** [comment]
直接在 mounted 里面修改 v-model 是无效的，这是因为在目前的实现里，DatetimePicker 在初始化时会重置一下 value，覆盖了 mounted 里设置的值。

在 mounted 里面加一个 setTimeout 可以避免这个问题
