### ISSUE TITLE
[Feature Request] field组件的formatter方法能否定义在field失去焦点之后再触发

### ISSUE THREAD

**Issue by cgd199158** [youzan/vant#6560]
### 这个功能解决了什么问题
field formatter实时变化会导致用户输入不了特殊的字符

### 描述您想要的解决方案
field 的formatter的触发事件改为onblur失去焦点触发

### 建议的API是什么样的
@blur="formater"

**Comment by chenjiahan** [comment]
下个版本会加一个参数来控制 formatter 触发的时机

**Comment by chenjiahan** [comment]
已在 2.8.7 版本支持
