### ISSUE TITLE
[Bug Report] SwipeCell 滑动单元格 问题

### ISSUE THREAD

**Issue by pant33** [youzan/vant#6561]
### 设备 / 浏览器
微信开发工具

### Vant 版本
2.8.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://pant33.github.io/nesm/test.html" target="_blank">https://pant33.github.io/nesm/test.html</a>

### 描述问题
会产生渲染方面的问题，页面需浏览器手机调试状态下

**Comment by chenjiahan** [comment]
具体是啥问题，没看出来

**Comment by pant33** [comment]
可能是CDNS引入方式的问题，右插件 放在主体后渲染会无法渲染出来，然后右滑 有两个按钮<vand-btn />方式会使两个按钮重叠

**Comment by pant33** [comment]
> 具体是啥问题，没看出来

可能是CDNS引入方式的问题，右插件 放在主体后渲染会无法渲染出来，然后右滑 有两个按钮方式会使两个按钮重叠

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-html-zhong-wu-fa-zheng-que-xuan-ran-zu-jian
