### ISSUE TITLE
[Bug Report] switch组件的active-value和inactive-value不生效

### ISSUE THREAD

**Issue by chenwanzhao** [youzan/vant#6562]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.8.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsbin.com/nolacay/2/edit?html,output" target="_blank">https://jsbin.com/nolacay/2/edit?html,output</a>

### 描述问题
switch组件的active-value和inactive-value不生效

**Comment by chenjiahan** [comment]
正确写法:https://jsbin.com/tajujaruxi/edit?html,output

**Comment by chenwanzhao** [comment]
嗯，我理解错了，我以为active-value和inactive-value的UI表现和ElementUI一样呢，ElementUI的表现是在switch左右显示文字，激活时switch右边的文字变色，未激活时switch左侧的文字变色！
