### ISSUE TITLE
文本框初始值设为null对时候直接把null显示出来了

### ISSUE THREAD

**Issue by linbingrong** [youzan/vant#6563]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6537
