### ISSUE TITLE
[Bug Report] Filed多个页面应用导致van-field__label的flex:none不会覆盖van-cell__title的flex:1

### ISSUE THREAD

**Issue by xuzhiguang** [youzan/vant#6567]
### 设备 / 浏览器
移动端浏览器亲测都会发生，IOS和安卓都会发生

### Vant 版本
2.8.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://member.bjhuaguan.com" target="_blank">https://member.bjhuaguan.com</a>

### 描述问题
打开链接需要先登录，然后打开个人信息，加载一次Filed，再返回，打开账号与安全>手机号>更换手机号。问题重现

**Comment by chenjiahan** [comment]
这个和组件库无关，建议你检查下打包配置，尽量把组件放在 vendors 里面加载，注意不要重复加载同个组件的样式

**Comment by xuzhiguang** [comment]
我组件的样式加载交给了babel-plugin-import，没有手动引入， 打包我也没加额外配置，是vue-cli3生成的。能告诉我怎么解决这个问题吗

**Comment by xuzhiguang** [comment]
> 这个和组件库无关，建议你检查下打包配置，尽量把组件放在 vendors 里面加载，注意不要重复加载同个组件的样式

我组件的样式加载交给了babel-plugin-import，没有手动引入， 打包我也没加额外配置，是vue-cli3生成的。能告诉我怎么解决这个问题吗

**Comment by chenjiahan** [comment]
@xuzhiguang 可以提供一个最小复现仓库看下

**Comment by androidxu** [comment]
同样的问题，我用深层选择器覆盖了样式，但是ios里的微信浏览器没有覆盖到，androi和网页都覆盖住了，绝望中。。。

**Comment by androidxu** [comment]
已解决，不要重复引入组件。按需引入直接在main.js里引入（麻烦），不要在每个页面里引入

**Comment by zdhzhongtao** [comment]
我复现的结果是：
在生产环境才会有这个问题，在开发环境下如果是使用按需引入，只会引入一次。

但是通过 npm run build 打包后就会每个页面引入一次，都会生成对应组件的css。导致重复引入，后面的覆盖前面的。
