### ISSUE TITLE
Search组件输入内容在 iphone 内显示不完整

### ISSUE THREAD

**Issue by qianzhaoy** [youzan/vant#657]
![image](https://user-images.githubusercontent.com/14267409/36825022-47d866fa-1d40-11e8-848e-5ca48b9e2e05.png)

如图， 左下角缺了一块。
```
机型： iphone6
ios版本： 10.3.2
```

**Comment by chenjiahan** [comment]
@qianzhaoy Sorry 没复现这个问题，能否帮忙定位或者修复下~

**Comment by qianzhaoy** [comment]
@chenjiahan  恩恩。好的。我再拿一些机型测试一下。如果发现问题并且能修复的话，再发PR

**Comment by chenjiahan** [comment]
好的，感谢~
