### ISSUE TITLE
移动端的filed文本框组件，通过打包到app，双向绑定失效，获取不了手持机终端扫码的值，只能通过this.$refs.xx.$refs.input.value来获取扫码的值

### ISSUE THREAD

**Issue by Quietlywind** [youzan/vant#6572]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
