### ISSUE TITLE
Field动态赋值时@input事件被触发导致业务出错

### ISSUE THREAD

**Issue by 13469960854** [youzan/vant#6575]
设备 / 浏览器
android chrome

Vant 版本
2.2.15

Vue版本
2.6.6

重现链接
http://jxcloud.uat.jxintell.com/jxcloud-mobile/#/saleBillAaa?isAdd=true&onlySaleOut=true

描述问题
整单折扣中设置折扣，动态获取数据赋值后导致触发了Field绑定得input事件触发，从而影响商品中单个折扣被动修改

**Comment by chenjiahan** [comment]
描述问题时，请脱离具体的业务场景，使用 codesandbox 提供一个最小的复现 demo
