### ISSUE TITLE
Uploader 文件上传result-type为dataUrl时，before-read、after-read、before-delete回调参数表现不一致

### ISSUE THREAD

**Issue by ZhaoLiangchuan** [youzan/vant#6576]
Uploader 文件上传result-type为dataUrl时，before-read、after-read、before-delete回调参数表现不一致。
before-read的file为file类型，fter-read、before-delete的file为dataUrl类型。
![微信截图_20200619120107](https://user-images.githubusercontent.com/34114842/85095643-97965500-b224-11ea-8a79-0bb5a60cd675.png)

**Comment by Duncanxyz** [comment]
before-read是在文件解析前触发的 所以😂

**Comment by chenjiahan** [comment]
楼上正解
