### ISSUE TITLE
[Bug Report] picker组件使用树形的结构disabled不生效

### ISSUE THREAD

**Issue by cyh41** [youzan/vant#6578]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-je6t7?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/embed/vant-issue-moban-je6t7?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
使用二维数组的形式可以生效，但是我们有需求（搜索过滤功能）只能使用树形比较方便。

**Comment by chenjiahan** [comment]
确实有这个问题，下个版本会修复

**Comment by cyh41** [comment]
> 确实有这个问题，下个版本会修复

非常感谢～幸苦巨佬

**Comment by chenjiahan** [comment]
已在 2.9.0-beta.0 版本修复，可以试一下✌️
