### ISSUE TITLE
checkbox/radio选项不支持溢出文本

### ISSUE THREAD

**Issue by Penggggg** [youzan/vant#658]
**What is the current behavior?**
当checkbox/radio的选项文本过长时，样式乱了。
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**
当checkbox/radio的选项文本过长时，样式正常。
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
vue: 2.5.0
vant: 0.12.0
> 附官网测试截图（图片稍大，需要加载）

![官网例子](https://images2018.cnblogs.com/blog/896425/201803/896425-20180301113138681-1395712987.png)

**Comment by chenjiahan** [comment]
@Penggggg Checkbox 不会为 content 添加额外的样式，这部分的样式可以自由定制
