### ISSUE TITLE
van-dropdown-item lazy-render为true时van-calendar的展示问题

### ISSUE THREAD

**Issue by shujiawei** [youzan/vant#6587]
设备 / 浏览器
chrome

Vant 版本
2.8.5

Vue 版本
2.6.11

van-dropdown-item 组件lazy-render设置为true，嵌套的组件van-calendar会有问题

van-calendar: 设置defaultDate为new Date()。打开会默认展示的时间为前一年的六月份，然后滚动到今年的六月会看到选中了，并且van-calendar 设置属性lazy-render好像一直为true

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by shujiawei** [comment]
> f
https://q23py.csb.app/ 麻烦您看下哈

**Comment by shujiawei** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f
https://codesandbox.io/s/vant-issue-moban-40eus?file=/src/App.vue

**Comment by shujiawei** [comment]
https://codesandbox.io/s/vant-issue-moban-40eus?file=/src/App.vue

**Comment by chenjiahan** [comment]
设置 lazy-render 为 false 确实会导致这个问题

原因：日历组件初始化时会自动滚动到当前日期的位置，但是如果嵌套在 DropdownItem 内，日历组件初始化时是处于不可见的状态，此时组件内部的滚动逻辑会失效。

解决方法：在 DropdownItem 打开时，手动调用日历的 reset 方法，使其滚动到对应位置。

**Comment by shujiawei** [comment]
> 设置lazy-render为false确实会导致这个问题
> 
> 原因：日历组件初始化时会自动滚动到当前日期的位置，但是如果嵌套在DropdownItem内，日历组件初始化时是处于不可见的状态，则组件内部的滚动逻辑会无效。
> 
> 解决方法：在DropdownItem：时，手动调用日历的reset方法，转到滚动到对应位置。

https://codesandbox.io/s/vant-issue-moban-rhyvg?file=/src/App.vue
给van-calendar设置高度 会出现van-calendar的标题不变化
