### ISSUE TITLE
[Feature Request] Tab 标签页 ，左右手势滑动的时候建议加入滑动动画。而不是手势完了才滑动过来。

### ISSUE THREAD

**Issue by pushuo** [youzan/vant#6588]
### 这个功能解决了什么问题
用户体验提升。

### 描述您想要的解决方案
在用户左右滑动的同时，类似轮播图左右手势滑动，而不是手势滑动完了，才有动画。

### 建议的API是什么样的
如题。

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/1174
