### ISSUE TITLE
Sku组件有问题

### ISSUE THREAD

**Issue by celverbamboo** [youzan/vant#659]
![screenshot 2018-03-01_16-20-46](https://user-images.githubusercontent.com/24216880/36834093-a97aadc4-1d6c-11e8-9584-a9a998ebd215.png)
![screenshot 2018-03-01_16-20-59](https://user-images.githubusercontent.com/24216880/36834094-a9a97b9a-1d6c-11e8-9078-8fc46d488102.png)
显示没有库存的商品之后,在点击其它有库存的商品,购买数量没有改过来

**Comment by w91** [comment]
@celverbamboo sku组件上加reset-stepper-on-hide参数应该就可以了
