### ISSUE TITLE
[Bug Report] NumberKeyboard / PasswordInput

### ISSUE THREAD

**Issue by KevinAccupass** [youzan/vant#6594]
设备 / 浏览器
Web Chrome / Android Chrome / iOS safari

Vant 版本
2.8.7

Vue 版本
2.6.10

重现链接
[https://youzan.github.io/vant/#/zh-CN/password-input](https://youzan.github.io/vant/#/zh-CN/password-input)

[https://i.imgur.com/sx6Dnyf.png](https://i.imgur.com/sx6Dnyf.png)

描述问题
官方Demo裡，Number Keyboard會遮蓋輸入框

**Comment by chenjiahan** [comment]
图片无法打开呢

与系统的虚拟键盘不同，NumberKeyboard 弹出时不会将页面向上弹起，因此这个场景需要使用者自行控制页面滚动条的位置，可以使用 scrollTo 或 scrollIntoView 等方法
