### ISSUE TITLE
[Feature Request] vant-swipe 支持类似 swiper 的 centeredSlides属性

### ISSUE THREAD

**Issue by kykolion** [youzan/vant#6597]
### 这个功能解决了什么问题
轮播居中，支持设置滑块边距

### 描述您想要的解决方案
实现类似中间放大，两边显示部分内容

### 建议的API是什么样的
支持类似 swiper 的 centeredSlides属性，slidesPerView属性

**Comment by chenjiahan** [comment]
暂无计划支持喔，像这种复杂的轮播效果，建议直接使用 swiper 库
