### ISSUE TITLE
[Bug Report] Layout布局的问题

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#6601]
### 设备 / 浏览器
win10 chrome84

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-kzqbv" target="_blank">https://codesandbox.io/s/vant-issue-moban-kzqbv</a>

### 描述问题
当col不填满一行，就会出现多一块的情况，发生偏移。理想状态是每一块的宽度一致，gutter对齐。
![image](https://user-images.githubusercontent.com/38392315/85377327-870b1500-b56b-11ea-8462-b7c6b50cc203.png)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6224
