### ISSUE TITLE
[Feature Request] 建议增加PullRefresh下拉刷新后不自动跳到最顶端

### ISSUE THREAD

**Issue by deific** [youzan/vant#6603]
描述：
建议增加PullRefresh下拉刷新后不自动跳到最顶端。

场景：
历史聊天记录页面，下拉刷新时加载前一页数据，数据加载后保持在当前位置，而不是跳转到最顶端位置。

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议自行控制滚动条的位置

**Comment by wordscode** [comment]
+1啊，我也需要这个
cy，有人解决@我
