### ISSUE TITLE
[Bug Report] tab 组件在隐藏状态下，切回显示状态，默认选中不生效

### ISSUE THREAD

**Issue by huangshuwei** [youzan/vant#6606]
### 设备 / 浏览器
chrome 83.0.4103.106

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-f8iyr?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-f8iyr?file=/src/App.vue</a>

### 描述问题
tab 组件在隐藏状态下，切回显示状态，默认选中不生效

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5381

**Comment by huangshuwei** [comment]
> 参见 #5381

使用 `v-f` tab 选中状态无法保持，要做一些额外的处理。
我尝试使用官方提供的 `resize()`方法，但是也不生效，建议可以在 tab 组件的`resize()`方法里做些处理，这样使用起来会方便很多

**Comment by chenjiahan** [comment]
resize 是有效的，可能你的调用时机不对，可以加个 nextTick

**Comment by huangshuwei** [comment]
> resize 是有效的，可能你的调用时机不对，可以加个 nextTick

示例已修改：https://codesandbox.io/s/vant-issue-moban-wlyyf?file=/src/App.vue
`resize()`方法的确是生效的，可能实际业务场景比较复杂，我再排查下。感谢回复
