### ISSUE TITLE
[Feature Request] 2.8.7版本field当type="number"时,实际使用的input为text类型

### ISSUE THREAD

**Issue by cgd199158** [youzan/vant#6608]
### 这个功能解决了什么问题
在移动端呼出的键盘为纯数字键盘

### 描述您想要的解决方案
input类型改为number
![image](https://user-images.githubusercontent.com/18514077/85535104-78dcf780-b644-11ea-802f-9b95555380e5.png)

### 建议的API是什么样的
field

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6374
