### ISSUE TITLE
[Feature Request] 建议所有组件新增移动端tap事件支持

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#6612]
### 设备 / 浏览器
Chrome

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 描述问题
Vant作为移动端UI库。移动端默认的Click事件存在300ms的延迟。所以需要用到tap事件来处理点击延迟问题。目前Vant所有组件紧支持click事件  不能绑定自定义的tap事件。 fastClick使用之后存在很多问题，所以我个人使用的是tap事件。

建议：新增tap事件绑定支持 或者UI库内置tap事件来解决点击延迟问题

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/1501
