### ISSUE TITLE
目前轮播不支持在循环滚动模式下自定义滑块大小，因此需要将 loop 设置为 false，啥时候可以支持下。

### ISSUE THREAD

**Issue by hwgq2005** [youzan/vant#6617]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
短期内不会支持喔

**Comment by myccckkk** [comment]
设置为true的话可以 但是第一个滑块会有不连贯情况
