### ISSUE TITLE
[Feature Request] Uploader组件增加一个slot-scope便于展示图片信息

### ISSUE THREAD

**Issue by YangFeiLiang9836** [youzan/vant#6618]
### 这个功能解决了什么问题
对于单个图片可以额外展示一些信息，如图片名称

### 描述您想要的解决方案
增加一个slot-scope便于展示图片的额外信息，在v-for图片的时候都会渲染这个slot-scope

### 建议的API是什么样的
Uploader组件增加一个slot-scope

**Comment by YangFeiLiang9836** [comment]
![微信截图_20200630122034](https://user-images.githubusercontent.com/45174648/86083183-21b7a680-bacc-11ea-9ac0-f7a24ef5d7dc.png)
如图

**Comment by chenjiahan** [comment]
下个版本会加上

**Comment by chenjiahan** [comment]
已在 2.9.1-beta.1 版本支持

**Comment by flyjin** [comment]
发现这个拿不到file的值啊
