### ISSUE TITLE
[Feature Request] van-field组件接受数据类型不支持数组，多文件上传数据为数组类型， 在表单中校验不通过

### ISSUE THREAD

**Issue by rainLRQ** [youzan/vant#6619]
### 这个功能解决了什么问题
van-field 组件支持数组类型数据，并且支持多文件上传表单校验

### 描述您想要的解决方案
van-field 组件支持数组类型数据，并且支持多文件上传表单校验

### 建议的API是什么样的
van-field 组件支持数组类型数据，并且支持多文件上传表单校验

**Comment by tianleiyiji123** [comment]
是的，如何校验数组类型？
