### ISSUE TITLE
Tabs 组件的sticky设置

### ISSUE THREAD

**Issue by xiaoNiuNew** [youzan/vant#662]
设置了sticky后，scroll到一定位置后，tab位置会被设置到底部，能否让使用者自行决定是否自动设置到底部？

**Comment by chenjiahan** [comment]
现在 Tab sticky 只有在 Tab 位置触底时才会被固定在底部喔，不知道你想要的效果是怎样的？

**Comment by xiaoNiuNew** [comment]
发现是我使用有点问题
