### ISSUE TITLE
[Bug Report] vant在vue移动端微信环境下（ 公众号和小程序 ）中使用field组件ios点击不灵敏

### ISSUE THREAD

**Issue by maruihua1997** [youzan/vant#6622]
### 设备 / 浏览器
ios

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-t7f2v?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-t7f2v?file=/src/App.vue</a>

### 描述问题
在ios手机中，微信环境下，点击 field的输入框，需要慢慢点，要有明显的停顿时间才能被触发

**Comment by chenjiahan** [comment]
组件本身没有对点击事件做处理，建议你看下是不是没有在 HTML 中设置 viewport

```html
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,viewport-fit=cover"/>
```

**Comment by AndyLue** [comment]
太感谢了！！困扰很久的问题
