### ISSUE TITLE
[Bug Report] cdn引入模式下表单里的输入框只显示一个

### ISSUE THREAD

**Issue by kevinriver** [youzan/vant#6625]
### 设备 / 浏览器
windows10,chrome

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsbin.com/bunevimuxo/edit?html,output" target="_blank">https://jsbin.com/bunevimuxo/edit?html,output</a>

### 描述问题
cdn引入模式下表单里的输入框只显示一个，第一个框之后的所有内容都不显示了

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-html-zhong-wu-fa-zheng-que-xuan-ran-zu-jian
