### ISSUE TITLE
[Feature Request] 按钮尺寸的建议

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#6632]
### 这个功能解决了什么问题
按钮的适用性会提高

### 描述您想要的解决方案
现在large、normal、small、mini按钮高度分别是50px、44px、30px、20px，在用的最多的32-40px中却没有很好的值可以选择

### 建议的API是什么样的
希望size的尺寸能更合理些，如标准值设为36px-40px，或者支持number类型的高度

**Comment by chenjiahan** [comment]
按钮尺寸暂时没有计划调整哈，可以直接通过设置 CSS 调整高度

```html
<template>
  <van-button class="my-button">Button</van-button>
</template>

<style>
.my-button {
  height: 36px;
}
</style>
```
