### ISSUE TITLE
[Bug Report] steps组件vertical状态下，active="1"颜色不正确

### ISSUE THREAD

**Issue by cfy2015** [youzan/vant#6636]
### 设备 / 浏览器
Chrome

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-h5579?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/embed/vant-issue-moban-h5579?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
steps组件vertical状态下，active="1"颜色不正确
非激活状态的图标和线条的颜色变成了绿色，active="0"正常

**Comment by chenjiahan** [comment]
上面的链接里是正常的，这个问题在之前的版本里已经修复过了，建议你升级最新版试下
