### ISSUE TITLE
[Bug Report] 数字键盘在ios中仍然存在延时现象不会即时响应

### ISSUE THREAD

**Issue by chinesehope** [youzan/vant#6637]
### 设备 / 浏览器
ios

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="http://192.168.9.45:8080/" target="_blank">http://192.168.9.45:8080/</a>

### 描述问题
数字键盘在ios中仍然存在延时现象不会即时响应经常会慢个0.3秒左右 做不到像微信支付键盘的即时性

**Comment by dingjunwei1314** [comment]
+1

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6498

**Comment by xiaosaFB** [comment]
你发个内网链接，让他们怎么调试
