### ISSUE TITLE
[Bug Report] 多个popup的遮罩层层级问题

### ISSUE THREAD

**Issue by miterwan** [youzan/vant#6640]
### 设备 / 浏览器
谷歌模拟器及移动端

### Vant 版本
2.8.7

### Vue 版本
2.6.1

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-6jppy?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-6jppy?file=/src/App.vue</a>

### 描述问题
不知道哪里看到popup是公用一个遮罩层，多层级最终也只会生成一个遮罩层
现在是生成了两个导致遮罩层颜色加深
还请大佬们可以教导一下使用方式

**Comment by chenjiahan** [comment]
最新版是每个 Popup 都会创建独立的遮罩层了，加深是符合预期的

**Comment by miterwan** [comment]
测了下2.8.7版本是非公用一个遮罩层。在2.5.0以前是只有一个遮罩层的。2.5.0-2.8.6之间未测试

**Comment by miterwan** [comment]
@chenjiahan 哦哦。原来是这样子。想咨询下一般的需求都是不希望遮罩层加深的。像新版这样的话需要怎么解决呀？

**Comment by chenjiahan** [comment]
其实遮罩层叠加是合理的，原生 APP 也是这样的效果。

如果不想要叠加效果，可以把遮罩层的颜色调浅一些，这样加深效果不会很明显，或者把第二层弹窗的遮罩层颜色设置为透明。

**Comment by miterwan** [comment]
@chenjiahan 额。。旧版本的模式多好- -。不用再去判断动态弹窗的遮罩层是否需要加深或变浅

**Comment by chenjiahan** [comment]
旧版本在某些场景下是有 bug 的，比如：https://github.com/youzan/vant/issues/6288

**Comment by miterwan** [comment]
@chenjiahan codesandbox的例子好像被重置为其他代码了。看gif的展示是popup的遮罩层实际是变成了dropdownMenu下拉时的遮罩层。挂载节点改成body下会不会就好了。。让遮罩层依旧是全屏

**Comment by chenjiahan** [comment]
不能挂载在 body 下，他的场景就是嵌套使用。

**Comment by miterwan** [comment]
@chenjiahan 哦哦。那只能用着低版本先啦。希望后面有兼容～谢谢解答
