### ISSUE TITLE
[Bug Report] Safari浏览器中，长按图片会放大变形

### ISSUE THREAD

**Issue by xiaosaFB** [youzan/vant#6642]
### 设备 / 浏览器
iPhoneX/Safari

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/image-preview" target="_blank">https://youzan.github.io/vant/#/zh-CN/image-preview</a>

### 描述问题
1.在iPhone/Safari中打开链接
2.点击【预览图片】按钮
3.长按图片，图片会放大到全屏并变形

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.9.0-beta.2 版本修复
