### ISSUE TITLE
[Bug Report] 页面停留过久后，动画会有卡顿的现象

### ISSUE THREAD

**Issue by qingqingke** [youzan/vant#6643]
最近我发现一个动画卡顿的现象，不知道你们有没有过这种情况。

我在微信小程序，H5都用的是vant，正常打开都是好着，当页面停留时间过长（包括长时间锁屏）

**再次使用后，弹出层等的那些动画效果都会失效（小程序），或者卡顿（H5）**

机型：iPhone8
软件版本：13.2.3

（Android暂时未知）

**Comment by chenjiahan** [comment]
这个应该是浏览器内核的问题，和组件没有关系哈，一般重新打开页面或 APP 就会恢复正常。
