### ISSUE TITLE
[Bug Report] picker选择器组件bug

### ISSUE THREAD

**Issue by a2774206** [youzan/vant#6644]
### 设备 / 浏览器
移动端

### Vant 版本
2.8.3

### Vue 版本
3.0.0-beta.15

### 重现链接
<a href="https://jsjingsui.oss-ap-northeast-1.aliyuncs.com/Video_20200629_042633_576.gif" target="_blank">点击查看复现gif</a>

### 描述问题
picker选择器选项在滑动中触摸会导致选择偏差。（重现连接含重现 gif）

**Comment by tangjian1891** [comment]
手动给一个 :item-height="45" 或其他值可以解决。 但是不要给44。

**Comment by chenjiahan** [comment]
链接里没找到对应的内容

**Comment by a2774206** [comment]
> 链接里没找到对应的内容

链接里是复现 gif 图片

**Comment by levi7754** [comment]
datepicker同样有这样的问题

**Comment by a2774206** [comment]
> 手动给一个：item-height =“ 45”或其他值可以解决。但是不要给44。

没有解决

**Comment by chenjiahan** [comment]
试了下没复现，能给个 codesandbox 复现链接不

**Comment by zlh** [comment]
> 试了下没复现，能给个 codesandbox 复现链接不

我是在模拟器下出现 真机是没有问题，：item-height =“ 45”这个设置成45确实解决了，但不明白为什么

**Comment by a2774206** [comment]
> 试了下没复现，能给个 codesandbox 复现链接不

官网的例子就可以复现（各种版本都试过），快速滑动选择的时候触摸屏幕（减速）找到选择目标选择时就会复现，复现几率大概二十分之一，

**Comment by chenjiahan** [comment]
你有使用 rem 单位转换吗，如果有的话可以参考这个 issue：https://github.com/youzan/vant/issues/6602

**Comment by a2774206** [comment]
> 你有使用 rem 单位转换吗，如果有的话可以参考这个 issue：#6602

没有使用 rem 转换，官网的示例也会有这个 bug，item 越多越容易复现，ios 复现几率较大。
复现方法：用力一滑列表，然后过程中手指触摸长按到停止自动滑动时松开 点击确定，然后选择会偏差。

**Comment by a2774206** [comment]
![Video_20200701_020216_287](https://user-images.githubusercontent.com/22309314/86208805-d40e6d00-bba3-11ea-83b7-00d0c63a83f2.gif)


> 你有使用 rem 单位转换吗，如果有的话可以参考这个 issue：#6602
官方复现：
![Video_20200701_020216_287](https://user-images.githubusercontent.com/22309314/86208805-d40e6d00-bba3-11ea-83b7-00d0c63a83f2.gif)

**Comment by chenjiahan** [comment]
复现了，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.9.1-beta.1 版本修复
