### ISSUE TITLE
[Bug Report] Stepper 步进器-触发disable-minus bug

### ISSUE THREAD

**Issue by yanye411325** [youzan/vant#6645]
### 设备 / 浏览器
pc/Google 版本 83.0.4103.116（正式版本） （64 位）

### Vant 版本
2.9.0-beta.1

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/nostalgic-curie-6d5f3?file=/src/App.vue" target="_blank">https://codesandbox.io/s/nostalgic-curie-6d5f3?file=/src/App.vue</a>

### 描述问题
Stepper 步进器 - 限制输入范围[50,9000],默认值100，输入1001 ，编辑状态触发了disable-minus

**Comment by chenjiahan** [comment]
确实有问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.9.0-beta.2 版本修复
