### ISSUE TITLE
Checkbox 复选框的bind-group只在刚开始渲染的时候有效，渲染后再更改不生效

### ISSUE THREAD

**Issue by lkhchen** [youzan/vant#6647]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by lkhchen** [comment]
版本是2.8.3

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
