### ISSUE TITLE
[Bug Report] ios 下 tabs   line下划线错位

### ISSUE THREAD

**Issue by Chasen-Zhang** [youzan/vant#6649]
### 设备 / 浏览器
ios

### Vant 版本
2.5.3

### Vue 版本
2.6.10

### 重现链接
<a href="http://www.baidu.com" target="_blank">http://www.baidu.com</a>

### 描述问题
ios 下 tabs   line下划线错位     偶发不一定出现

**Comment by Chasen-Zhang** [comment]
![image](https://user-images.githubusercontent.com/15354455/86077019-cd0d2f00-babd-11ea-9974-9004df892d55.png)

**Comment by Chasen-Zhang** [comment]
![image](https://user-images.githubusercontent.com/15354455/86087296-73fdc500-bad6-11ea-8d4d-03b416014343.png)

**Comment by Chasen-Zhang** [comment]
解决了
ios下加上这个代码
mounted() {
    if (isIos) {
      this.iosFix();
    }
  },
  methods: {
    iosFix() {
      this.$nextTick(()=>{
        let width = document.getElementsByClassName('import-export')[0].clientWidth; // import-export 最外层div
        let halfWidth = width/2 + 'px'; 
        document.getElementsByClassName('van-tab--active')[0].style.width = halfWidth;
        document.getElementsByClassName('van-tabs__line')[0].style.transform = `translateX(${halfWidth}) translateX(-50%)`;
      });
    }
  }

**Comment by chenjiahan** [comment]
可以用 resize 方法，效果一样的，参见 https://youzan.github.io/vant/#/zh-CN/tab#tabs-fang-fa

**Comment by Chasen-Zhang** [comment]
> 可以用 resize 方法，效果一样的，参见 https://youzan.github.io/vant/#/zh-CN/tab#tabs-fang-fa

resize是无效的，我试了，

**Comment by chenjiahan** [comment]
理论上是有效的， 可以来个 codesandbox 复现链接看下 

https://codesandbox.io/s/m5v3f

**Comment by SmallishJoker** [comment]
遇到了同样的问题，但是使用nextTick无效，换成setTimeout则可以
