### ISSUE TITLE
[Feature Request] 希望swipe动画效果增加渐变

### ISSUE THREAD

**Issue by ghtao666** [youzan/vant#6654]
### 这个功能解决了什么问题
更通用，更好看

### 描述您想要的解决方案
增加渐变

### 建议的API是什么样的
effect，动画效果，可取 scrollx,  scrolly, fade

**Comment by chenjiahan** [comment]
暂无计划支持喔，这种复杂的轮播效果建议使用社区的轮播库，比如 https://github.com/surmon-china/vue-awesome-swiper
