### ISSUE TITLE
DatePick组件使用filter属性过滤出分钟为00、30的形式，在切换月份的时候，直接点击确认，获取到的时间有问题（不是00、30的时间格式）

### ISSUE THREAD

**Issue by Summer-zx** [youzan/vant#6655]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
