### ISSUE TITLE
[Bug Report] DatetimePicker插件使用filter属性过滤出分钟格式为00、30，在切换月份的时候直接点击确认，回调事件里面返回的value值有问题

### ISSUE THREAD

**Issue by Summer-zx** [youzan/vant#6657]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.9.0-beta.1

### Vue 版本
3.0.0-beta.16

### 重现链接
<a href="http://www.baidu.com?本地调试的项目" target="_blank">http://www.baidu.com?本地调试的项目</a>

### 描述问题
DatetimePick插件最小时间为当前时间，最大时间往后推7天，使用filter属性过滤出分钟数为00、30的格式，在切换月份的时候，往上切换月份直接点击确定，回调方法里面返回的值为设置的最小时间（期望分钟数为filter过滤过的00、30格式-当前实际选中的时间）、往下切换月份直接点击确定回调方法里面返回的值为设置的最大时间（期望分钟数为filter过滤过的00、30格式-当前实际选中的时间）-----个人怀疑是filter属性这块貌似延迟了

**Comment by Summer-zx** [comment]
![QQ图片20200630162230](https://user-images.githubusercontent.com/29565582/86107358-4c1d5a00-baf4-11ea-8b61-4194c9064f60.png)

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接 

https://codesandbox.io/s/m5v3f

**Comment by Summer-zx** [comment]
https://codesandbox.io/s/vant-issue-moban-1isyc?file=/src/App.vue

**Comment by Summer-zx** [comment]
直接选择7月份的时间，点击确定，console出来的时间是2020-07-07 23：59：59

**Comment by sylvaner-h** [comment]
`filter`是`选项过滤函数`，不是`值过滤函数`。

**Comment by Summer-zx** [comment]
选项过滤了，在切换月份的时候，页面上显示的是选择的30分，点击确定出来的值是59分，这个明显是有问题的啊

**Comment by Summer-zx** [comment]
问题链接稍作修改，只有在切换月份的时候会有问题

**Comment by chenjiahan** [comment]
```js
if (type === 'minute') {
  return options.filter((option) => option === '00' || option === '30');
}
```

这段逻辑有问题，使用 filter 的时候需要保证返回值不能为空，假如现在是 35 分，上面的判断会返回一个空数组，导致 DatetimePicker 无法正确工作。

你可以在数据为空的情况下返回一个默认值，比如：

```js
if (type === 'minute') {
  const filtered = options.filter((option) => option === '00' || option === '30');
  if (filtered.length === 0) {
    filtered.push('00');
  }
  return filtered;
}
```
