### ISSUE TITLE
图标有点少

### ISSUE THREAD

**Issue by hubgitjiang** [youzan/vant#6658]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划添加更多图标，可以使用自定义图标
