### ISSUE TITLE
[Feature Request] Checkbox 复选框的bind-group属性只在刚开始渲染的时候有效，渲染后再更改不生效

### ISSUE THREAD

**Issue by lkhchen** [youzan/vant#6659]
### 这个功能解决了什么问题
目前Checkbox 复选框的bind-group属性只在刚开始渲染的时候有效，希望bind-group可以绑定变量， 变量修改时动态的与复选框组绑定或不绑定。就像disable属性那样

### 描述您想要的解决方案
目前Checkbox 复选框的bind-group属性只在刚开始渲染的时候有效，希望bind-group可以绑定变量， 变量修改时动态的与复选框组绑定或不绑定。就像disable属性那样

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
现在应该是支持动态绑定的，你是在什么场景下没生效，可以提供个 codesandbox 复现链接看下

https://codesandbox.io/s/m5v3f

**Comment by lkhchen** [comment]
> 现在应该是支持动态绑定的，你是在什么场景下没生效，可以提供个 codesandbox 复现链接看下
> 
> https://codesandbox.io/s/m5v3f

https://codesandbox.io/s/vant-issue-moban-je0qz?file=/src/App.vue   你试下

**Comment by chenjiahan** [comment]
这个链接里的示例看起来没啥问题呀

**Comment by lkhchen** [comment]
> 这个链接里的示例看起来没啥问题呀
您现在再看下， 我改了下，前两天有点错误。   是这样的： 如果一开始就给bind-group赋值为true，  以后动态改变为false或者true都没有问题。 但是如果一开始bind-group赋值为false， 那以后再动态改变的话会有问题

**Comment by chenjiahan** [comment]
get 了，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.9.1-beta.1 版本修复
