### ISSUE TITLE
项目编译时报CSS minification error

### ISSUE THREAD

**Issue by yanglinxu** [youzan/vant#6662]
项目依赖 vant-2.8.7  vue-2.6.11 vue-cli-4.4.0  
项目中全局引用import "vant/lib/index.css"  当运行npm run build时会出现如下错误  导致编译失败
![Snipaste_2020-07-01_12-08-37](https://user-images.githubusercontent.com/31086948/86202608-4d529380-bb95-11ea-8c93-2410f8b47ea6.png)
当运行npm run serve时  可以编译成功 但是样式未生效 如下图
![Snipaste_2020-07-01_12-10-50](https://user-images.githubusercontent.com/31086948/86202719-a8848600-bb95-11ea-9397-44124b180083.png)
所有van类名前面都莫名被自动加上.index类名  
请问是什么原因呢

**Comment by chenjiahan** [comment]
这个问题与 vant 无关，建议你检查下自己的编译配置，或到 vant-cli 仓库下反馈
