### ISSUE TITLE
[Bug Report] Dialog文档漏写allow-html属性

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#6665]
### 设备 / 浏览器
win10

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/dialog" target="_blank">https://youzan.github.io/vant/#/zh-CN/dialog</a>

### 描述问题
Dialog文档漏写allow-html属性

**Comment by chenjiahan** [comment]
感谢反馈，近期会加上

**Comment by chenjiahan** [comment]
文档已更新
