### ISSUE TITLE
提问：van-action-sheet页面渲染不出来，也不报错

### ISSUE THREAD

**Issue by tianfuzhou** [youzan/vant#6669]
提问：van-action-sheet页面渲染不出来，也不报错
版本：2.2.9
场景：nuxt
方式：自动按需引入组件
![WX20191025-134940](https://user-images.githubusercontent.com/13144533/67546210-5cdc2b80-f72e-11e9-840e-9eb3f1f52038.png)

_Originally posted by @qianlanse in https://github.com/youzan/vant/issues/3364#issuecomment-546211306_

**Comment by tianfuzhou** [comment]
我也遇到这个问题了 什么原因

**Comment by chenjiahan** [comment]
ActionSheet 绑定的是 v-model，不是 v-show

**Comment by JenayLee** [comment]
绑定v-model依然有这个问题

**Comment by lp13762436965** [comment]
我也有这个问题 ， 明明v-model设置了  但是就是不渲染， vue3.x  vant: 3.4.0

**Comment by lp13762436965** [comment]
> 这个问题了 什么原因

现在还是有这个问题哦 确认是绑定的v-model  用的vite   vue3.x vant: 3.4.0 跟这个一样  
![image](https://user-images.githubusercontent.com/20530414/148634512-169fb4bb-e5d1-4507-9ccd-b02122368611.png)
显示的这个
