### ISSUE TITLE
关于输入框禁用样式

### ISSUE THREAD

**Issue by nikezhenji86** [youzan/vant#667]
输入框禁用的字体颜色目前采用#999，苹果端颜色显示太浅近乎透明，建议调整

**Comment by chenjiahan** [comment]
感谢反馈，safari 会默认将 disabled 的输入框设置 opacity，将在下个版本修复

**Comment by chenjiahan** [comment]
已在 0.12.12 版本中修复

**Comment by DivXPro** [comment]
好像现在的版本 disabled 颜色还是淡的可怕啊
