### ISSUE TITLE
[Bug Report] popup滚动锁定bug

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#6673]
### 设备 / 浏览器
win10

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-vt2ug" target="_blank">https://codesandbox.io/s/vant-issue-moban-vt2ug</a>

### 描述问题
当popup销毁后再次渲染，背景滚动锁定失效。demo中第二次点击打开popup锁定失效

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.9.1-beta.1 版本修复
