### ISSUE TITLE
[Bug Report] vant 更新到2.8.7版本后 ,npm run dev 报错

### ISSUE THREAD

**Issue by dream1009** [youzan/vant#6676]
### 设备 / 浏览器
windows 64

### Vant 版本
2.8.7

### Vue 版本
2.6.10

### 重现链接
<a href="https://github.com/dream1009/hbp-app.git" target="_blank">https://github.com/dream1009/hbp-app.git</a>

### 描述问题
更新vant 版本后，运行项目，报错：
This dependency was not found:

* vant/lib/mixins/router-link in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/CardList/index.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/LcCard/index.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save vant/lib/mixins/router-link

在原来的 /mixins 组件有一个 router-link.js 文件，但是现在没有。如果需要使用最新版的 vant , 这个需要怎么解决

**Comment by chenjiahan** [comment]
router-link.js 是 Vant 内部的文件，并不是对外暴露的接口，所以开发者是不能直接引用的，不推荐这样的用法。

如果你已经在项目里依赖了这个文件，可以从旧版本 Vant 里找到这个文件并拷贝到项目中使用。
