### ISSUE TITLE
[Bug Report] 选择器在手机上选择的内容不能垂直居中显示在框里面

### ISSUE THREAD

**Issue by zhou-zc** [youzan/vant#6677]
### 设备 / 浏览器
三星s8

### Vant 版本
2.8.7

### Vue 版本
2.6.1

### 重现链接
<a href="http://ww1.sinaimg.cn/large/005HMZIIly1ggcsitdgxkj30py1hc41r.jpg" target="_blank">http://ww1.sinaimg.cn/large/005HMZIIly1ggcsitdgxkj30py1hc41r.jpg</a>

### 描述问题
在手机上面选择器不能正常显示选择的内容，pxtorem设置的37.5

**Comment by chenjiahan** [comment]
已经在 2.9.0-beta.4 版本修复了，参见 https://github.com/youzan/vant/issues/6602
