### ISSUE TITLE
求你们别写这些辣鸡东西出来了好吗

### ISSUE THREAD

**Issue by cnvoid** [youzan/vant#6678]
求你们别写这些辣鸡东西出来了好吗？？ 一堆bug , 各种不好用。 一点都不专业。 尼玛。 快关了吧。求你们了

**Comment by cnvoid** [comment]
完全按文档写的。 出来的效果居然恶心巴拉。 你大爷的

**Comment by chenjiahan** [comment]
不送。

**Comment by cnvoid** [comment]
<van-dialog v-model="showCancelDlg" title="标题" @confirm="cancel" show-cancel-button>
          <div class="mt-15 ov-hidden bg-fff fz-14 pd-15">
          <van-dropdown-menu >
            <van-dropdown-item :lazy-render="false"  v-model="cancelReson" :options="cancelResonOpts" />
          </van-dropdown-menu>
        </div>
      </van-dialog>


你们执行下这个， 是不是样式全部出问题了
