### ISSUE TITLE
undefined is not an object (evaluating 't.offsetWidth')

### ISSUE THREAD

**Issue by GiantZero-x** [youzan/vant#668]
**What is the current behavior?**
收到报错
![image](https://user-images.githubusercontent.com/21251584/37014325-d687a1d8-213a-11e8-978f-a61ae6b940fe.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**
![image](https://user-images.githubusercontent.com/21251584/37014350-fd310f18-213a-11e8-8a7a-b7bae5c298c5.png)
点击几次tab正常，再次点击时随机发生，用户触发，开发中无法复现

**What is the expected behavior?**
兼容不报错

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

* vant@0.10.7
* vue@2.5.13
* iPhone 9.3.2
* 最早1个月前发生，最近今天发生
* UA: `Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 MicroMessenger/6.6.3 NetType/4G Language/zh_CN`

--

**Comment by chenjiahan** [comment]
感谢反馈，我们会在此处加上兼容处理，预防报错

**Comment by GiantZero-x** [comment]
好的，并非必现因此会先有一段时间进行观察。
