### ISSUE TITLE
[Bug Report] vant-cli 无法 import dplayer库

### ISSUE THREAD

**Issue by DougFlands** [youzan/vant#6680]
### 设备 / 浏览器
83.0.478.54

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/Flands/pen/JjGMOqj" target="_blank">https://codepen.io/Flands/pen/JjGMOqj</a>

### 描述问题
run cmd
```
 npx create-vant-cli-app
 yarn add dplayer
 npm run dev
```
在demo页内加入
```
import DPlayer from 'dplayer';

console.log(DPlayer)
```
提示
```
Compiled with 1 warnings
in ./src/demo-button/demo/index.vue?vue&type=script&lang=js&
"export 'default' (imported as 'DPlayer') was not found in 'dplayer'
```

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/86503430-afeb9f80-bde0-11ea-865a-3fb65b7debd3.png)

我这边按步骤测试了一下是正常的，建议你重新再试一下喔，或者直接提供一个复现问题的仓库

**Comment by DougFlands** [comment]
> ![image](https://user-images.githubusercontent.com/7237365/86503430-afeb9f80-bde0-11ea-865a-3fb65b7debd3.png)
> 
> 我这边按步骤测试了一下是正常的，建议你重新再试一下喔，或者直接提供一个复现问题的仓库

https://github.com/DougFlands/vant-issues
复现仓库

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/86506164-77a78980-bdff-11ea-979a-69cf3baaf6e8.png)

我用你的仓库试了下，编译是正常的

你的 node 版本多少，可以切到 node 12 试下

**Comment by DougFlands** [comment]
> ![image](https://user-images.githubusercontent.com/7237365/86506164-77a78980-bdff-11ea-979a-69cf3baaf6e8.png)
> 
> 我用你的仓库试了下，编译是正常的
> 
> 你的 node 版本多少，可以切到 node 12 试下

WSL Ubuntu里运行正常。
windows 下 node = 12.18.2 yarn = 1.22.4 不行
你们有 windows 的机器嘛？可以测试一下。

**Comment by chenjiahan** [comment]
没有 windows 机器。。

**Comment by DougFlands** [comment]
> 没有 windows 机器。。

应该是 babel 或是 webpack 哪里配置有点问题。
linux 下正常，windows 下不行，同事的 windows 试了也不行。这个能修复嘛？
目前暂时用下面的方式 hack 掉了
```js
let dplayer = null
import('dplayer').then(() => {
  dplayer()
})

export default {
  created() {
    dplayer = () => {
      // 已加载 dplayer
      console.log(window.DPlayer)
    }
  },
}
```

**Comment by chenjiahan** [comment]
能否帮忙排查下呢
