### ISSUE TITLE
[Feature Request] search有参数时候的逻辑

### ISSUE THREAD

**Issue by wfq1095745112** [youzan/vant#6681]
### 这个功能解决了什么问题
能够不用聚焦了，才能点清除icon

### 描述您想要的解决方案
有参数的时候 清除icon不隐藏

### 建议的API是什么样的
暂无

**Comment by chenjiahan** [comment]
下个版本会加一个参数，来控制是否需要聚焦才显示清除 icon

**Comment by chenjiahan** [comment]
已在 2.9.1-beta.1 版本支持
