### ISSUE TITLE
vant  中indexBar  ios 在索引栏 滑动时  或者在列表中滚动时 样式混乱 

### ISSUE THREAD

**Issue by likailun101929** [youzan/vant#6683]
vant  中indexBar  ios 在索引栏 滑动时  或者在列表中滚动时 样式混乱 
![f38fdcbd054619ac94ce90f42dab102](https://user-images.githubusercontent.com/56298365/86428739-0e9d1480-bd20-11ea-89fd-6b558634c758.png)

**Comment by likailun101929** [comment]
左边字母 样式乱了

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
