### ISSUE TITLE
[Feature Request] Make tabs width adapt to content

### ISSUE THREAD

**Issue by soylomass** [youzan/vant#6684]
### 这个功能解决了什么问题
Currently when tabs exceed the maximum amount and become swipeable, their width becomes 22% of the screen width, too small for most long words  so they get cut and ellipsis appear.

### 描述您想要的解决方案
Add possibility to make tabs width adapt to their content, maybe with a max-width limit.

### 建议的API是什么样的
Add auto-width (boolean) and max-width (number) as props to van-tab

**Comment by soylomass** [comment]
Also if there is any css or js workaround for now, I'd be extremely thankful. I couldn't work it out by myself.

**Comment by chenjiahan** [comment]
try this:

```html
<van-tabs :ellipsis="false" />
```

**Comment by soylomass** [comment]
That worked, thanks!

**Comment by chenjiahan** [comment]
👌
