### ISSUE TITLE
[Bug Report] Tab标签页如何阻止切换

### ISSUE THREAD

**Issue by wangximeng0801** [youzan/vant#6685]
### 设备 / 浏览器
谷歌

### Vant 版本
2.9.0-beta.4

### Vue 版本
3.0.0-beta.18

### 重现链接
<a href="https://jsbin.com/?html,output" target="_blank">https://jsbin.com/?html,output</a>

### 描述问题
tab标签页组件切换时要加验证，满足条件才能切换，否则不允许切换，怎么阻止切换啊？

**Comment by chenjiahan** [comment]
下个版本会添加一个 `before-change` 属性，用于在切换标签前执行判断逻辑

**Comment by chenjiahan** [comment]
已在 2.9.3 版本支持
