### ISSUE TITLE
[Feature Request] vant-cli install配置修改

### ISSUE THREAD

**Issue by JohnYu588** [youzan/vant#6689]
设备 / 浏览器
chrome

Vant 版本
最新

Vue版本
最新

重现链接

描述问题
有个组件需要自定义install传参，index.js的配置怎么修改
这部分没看到有api，建议这个可以加个参数配置：
![11](https://user-images.githubusercontent.com/49671649/86442070-c7bf1700-bd3f-11ea-9954-82d2755219e9.png)

**Comment by JohnYu588** [comment]
多提一句：①woff和ttf资源无法打包（建议添加file-loader）；②yarn release一直报请先登录，这里分开两步骤 npm build和npm release之后可通过

**Comment by chenjiahan** [comment]
> 有个组件需要自定义install传参，index.js的配置怎么修改

这种需要传参的情况，可以使用 build.skipInstall 来跳过，参见 https://github.com/youzan/vant/blob/dev/vant.config.js

> woff和ttf资源无法打包（建议添加file-loader）

这个建议自己配置 loader，cli 里不会内置

> yarn release一直报请先登录，这里分开两步骤 npm build和npm release之后可通过

没懂你的意思，现在的执行顺序是 build -> changelog -> release-it
