### ISSUE TITLE
van-tabbar 在vue的使用中，初始化页面调用接口的路由，将标签栏默认选中第一个菜单，高亮，而且显示其内容

### ISSUE THREAD

**Issue by BellaLiu000** [youzan/vant#6690]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

van-tabbar 在vue的使用中，初始化页面调用接口的路由，将标签栏默认选中第一个菜单，高亮，而且显示其内容，这个怎么写？大佬们可以给个说明不？
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
