### ISSUE TITLE
[Feature Request] UI暗黑模式

### ISSUE THREAD

**Issue by heii** [youzan/vant#6692]
### 这个功能解决了什么问题
1、coding <=> preview 不晃眼；
2、用户体验更好。

### 描述您想要的解决方案
虽然定制主题可以实现，但官方能出个最好，Zan Design全套UI都支持暗黑模式最好不过~

### 建议的API是什么样的
可根据系统主题自动适配暗黑/明亮模式，也可以强制使用其中一种模式：
```
<body data-vant-theme="light">
    ...
</body>
```
参考[WeUI](https://github.com/Tencent/weui/wiki)

**Comment by chenjiahan** [comment]
目前我们的设计规范里没有暗黑模式，所以暂时不会支持喔，建议先通过主题定制来实现
