### ISSUE TITLE
带有遮罩层的组件以及折叠面板，点击显示后延迟不止有0.3S，响应速度太慢，体验太差

### ISSUE THREAD

**Issue by 1037055457** [youzan/vant#6693]
小程序基础库：2.11.3，
vant-weapp版本：1.3.3，
测试手机：华为p30pro，红米K30，其他手机还没有测试

在小程序真机或者预览中只要是包含了遮罩层的组件以及折叠面板，响应速度太慢，体验效果不好，尤其是重复点击之后更是。后面就自己写了个遮罩层对比，速度明显都不一样了，点击能立马响应出来。

希望官方处理下这个问题

**Comment by chenjiahan** [comment]
小程序的问题请到 vant-weapp 仓库下反馈，感谢配合
