### ISSUE TITLE
[Feature Request] ImagePreview、Popup、Overlay等组件期望触发回退事件后关闭遮罩但路由不回退

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#6694]
### 这个功能解决了什么问题
部分用户习惯通过回退键关闭遮罩层，而不希望路由同时回退。目前解决方法是监听popstate，重写回退事件，但是效率较低。

### 描述您想要的解决方案
ImagePreview、Popup、Overlay等组件增加一个属性，控制回退键关闭遮罩后路由是否回退

### 建议的API是什么样的
参数：close-on-route-back
类型：boolean

**Comment by chenjiahan** [comment]
暂时没有计划在组件内部增加操作路由的逻辑，这个能力建议自行封装下
