### ISSUE TITLE
[Feature Request] NoticeBar 这个文字支持无缝滚动和反向滚动吗

### ISSUE THREAD

**Issue by 951759534** [youzan/vant#6695]
### 设备 / 浏览器
chrome

### Vant 版本
2.9.0

### Vue 版本
3.0.0-beta.18

### 重现链接
<a href="https://jsbin.com/?html,output" target="_blank">https://jsbin.com/?html,output</a>

### 描述问题
[Feature Request] NoticeBar 这个文字支持无缝滚动吗

**Comment by chenjiahan** [comment]
不支持喔，目前没有计划支持
