### ISSUE TITLE
vant 线上打包报app.8c7fb6c2.js:1 Uncaught ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by gethubHanSo** [youzan/vant#6701]
vant 本地调试正常，线上打包后报app.8c7fb6c2.js:1 Uncaught ReferenceError: Vue is not defined
请问这是什么问题？我vue本地是安装好的，要不然本地调试肯定是有问题。

**Comment by gethubHanSo** [comment]
vant开发环境是按照vant官网流程搭建的

**Comment by chenjiahan** [comment]
请确认你引入了 Vue，建议检查下打包配置
