### ISSUE TITLE
[Bug Report] van-popup 

### ISSUE THREAD

**Issue by mofei031026** [youzan/vant#6704]
### 设备 / 浏览器
多台设备  多种浏览器

### Vant 版本
2.8.5

### Vue 版本
3.0.0-beta.18

### 重现链接
<a href="http://47.105.211.203:8096" target="_blank">http://47.105.211.203:8096</a>

### 描述问题
在页面上使用按钮能各种浏览器中能正常使用van-popup，但是咋地图中点击图标（代码与按钮触发代码相同）却无法弹出popup，经过对比发现使用按钮触发popup，body元素上会加上类van-overflow-hidden，而点击地图中的poi却不会再body上加上v类an-overflow-hidden

**Comment by chenjiahan** [comment]
Popup 的 v-model 变为 true 时就会展示，与触发方式无关。

建议你检查下：是否正确触发了地图的点击事情并将 Popup 的 v-model 设置为 true

**Comment by mofei031026** [comment]
v-model已经设置为true了的，否则也不会在部分手机浏览器上能正常打开，在某些手机上打不开的现象，建议大佬们排查一下吧

**Comment by chenjiahan** [comment]
提供一下 codesandbox 复现链接以及复现问题的机型、系统，不然没法帮你排查

https://codesandbox.io/s/m5v3f

**Comment by mofei031026** [comment]
针对这个问题专门部署了一个网站，地址：http://47.105.211.203:8096
微信内置的浏览器、魅族16，三星S9、华为P30

**Comment by mofei031026** [comment]
在微信内置浏览中，点击地图中的点位，页面会闪烁一下，但不会弹出popup
