### ISSUE TITLE
[Feature Request] uploader 文件上传时默认压缩及增加裁剪功能

### ISSUE THREAD

**Issue by illusory-love** [youzan/vant#6705]
### 这个功能解决了什么问题
手机用户直接拍照上传因图片过大导致显示过慢的问题

### 描述您想要的解决方案
1、针对图片增加尺寸设置，默认将图片按指定尺寸缩放后上传。如果仅指定宽或高，则进行等比缩放。
2、在指定缩放后，还可设置是否允许用户进行裁剪操作。

### 建议的API是什么样的
1、针对图片增加尺寸设置，默认将图片按指定尺寸缩放后上传。如果仅指定宽或高，则进行等比缩放。
2、在指定缩放后，还可设置是否允许用户进行裁剪操作。

**Comment by chenjiahan** [comment]
暂无计划支持喔，可以在 after-read 中自行处理
