### ISSUE TITLE
[Feature Request] 希望van-button能增加dataset自定义属性

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant#6706]
### 这个功能解决了什么问题
像html5的 data-属性名 那样传值，现在不得不使用原生的button。

### 描述您想要的解决方案
像html5原生的那样就行

### 建议的API是什么样的
data-id或者data-自定义

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/86529309-45bb2380-bee2-11ea-9362-5b8ec203926c.png)

组件本身就支持的，可以直接设置
