### ISSUE TITLE
[Bug Report] image-preview 声明文件错误

### ISSUE THREAD

**Issue by xiaoyueguang** [youzan/vant#6708]
### 设备 / 浏览器
Any

### Vant 版本
2.9.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/xiaoyueguang/vant-issue-image-preview" target="_blank">https://github.com/xiaoyueguang/vant-issue-image-preview</a>

### 描述问题
image-preview的声明文件有错误声明.
强制性要求ImagePreviewOptions接收swipeTo. 导致编译无法通过

**Comment by chenjiahan** [comment]
欢迎 PR 喔

**Comment by chenjiahan** [comment]
已在 2.9.1-beta.1 版本修复
