### ISSUE TITLE
给van-calendar设置高度 会出现van-calendar的标题不变化

### ISSUE THREAD

**Issue by shujiawei** [youzan/vant#6709]
设备 / 浏览器
chrome

Vant 版本
2.8.5

Vue 版本
2.6.11

https://codesandbox.io/s/vant-issue-moban-rhyvg?file=/src/App.vue
给van-calendar设置高度 会出现van-calendar的标题不变化

**Comment by chenjiahan** [comment]
嵌套在 DropdownItem 里且设置 lazy-render 为 false 时会有此问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.9.1-beta.1 版本修复

**Comment by shujiawei** [comment]
2.9.1-beta.1已解决
