### ISSUE TITLE
使用babel-plugin-import 出错

### ISSUE THREAD

**Issue by jiamianmao** [youzan/vant#671]
```{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": [
    ["import", { "libraryName": "vant", "style": true }]
  ],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}
```
这是小弟的.babelrc文件
在组件中引用的时候
```import { CellSwipe } from 'vant'```
但是报错

> vue.esm.js?57ca:578 [Vue warn]: Unknown custom element: <van-number-keyboard> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Product> at C:\Users\zhulihulian\Desktop\ff\src\pages\product\product.vue
       <App> at C:\Users\zhulihulian\Desktop\ff\src\App.vue
         <Root>

**Comment by chenjiahan** [comment]
可以 `console.log(CellSwipe);` 看下是否正确引用了组件

**Comment by jiamianmao** [comment]
`{render: ƒ, name: "van-cell-swipe", props: {…}, directives: {…}, data: ƒ, …}`  确实是引用进去了，但是依旧报上面的错误。

**Comment by chenjiahan** [comment]
麻烦贴一下你注册组件以及调用组件的代码

**Comment by jiamianmao** [comment]
template: 
```
<van-cell-swipe :right-width="65" v-for='(item, index) of arr' :key='index'>
    <van-cell-group>
    </van-cell-group>
    <div class='deltext1' slot="right" @click='delOne(item.brand_id)'>删除</div>
</van-cell-swipe>
```

script:
```
import { CellSwipe } from 'vant'
export default {
  components: {
    CellSwipe
  }
}
```

**Comment by chenjiahan** [comment]
@jiamianmao 你注册的是 cell-swipe 而不是 van-cell-swipe

**Comment by jiamianmao** [comment]
知道了，我是看
```
```

**Comment by jiamianmao** [comment]
知道了，我是看 `CellSwipe` 使用指南上直接``` import { CellSwipe } from 'vant' ```  引入的。
刚听你一说，看了下示例页面的三个代码，改为:
```
import { CellSwipe, CellGroup } from 'vant'
components: {
      [CellSwipe.name]: CellSwipe,
      [CellGroup.name]: CellGroup
    }
```
这样ok了

**Comment by TuDoudong** [comment]
你好，我遇到了相同的问题，但是我是
`import { ActionSheet } from 'vant';`
`components: {
    [ActionSheet.name]: ActionSheet
  },`
但是仍旧没有解决问题，相类似的vue.use 同样没有解决，需要你的帮助，谢谢~
