### ISSUE TITLE
[Feature Request] 注册vue-lazyload，van-image组件服务端渲染内存占用不释放

### ISSUE THREAD

**Issue by YouthBaby** [youzan/vant#6711]
### 这个功能解决了什么问题
van-image组件服务端渲染内存占用不释放

说明： van-image组件在created钩子中 会执行 $Lazyload.$on('loaded', this.onLazyLoaded); 阅读过vue-lazyload源码后发现，是往$Lazyload.Event.listeners['loaded']这个数组中push this.onLazyLoaded 这个函数。在SSR时，created钩子也会执行，这个函数就一直储存在node的堆内存中，不会被gc掉，渲染的越多，内存占用越大，最终crash掉整个应用。

### 描述您想要的解决方案
在 van-image created 钩子中判断一下是否在客户端执行 或者 使用客户端渲染专有钩子 beforeMount

### 建议的API是什么样的
无变化

**Comment by YouthBaby** [comment]
@chenjiahan 请看一下这个issue

**Comment by chenjiahan** [comment]
明白，下个版本会优化下

**Comment by chenjiahan** [comment]
已在 2.9.1-beta.1 版本修复
