### ISSUE TITLE
[Feature Request] Uploader 文件上传设置disabled时，应该设置图片不可预览，删除不可用

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#6714]
### 这个功能解决了什么问题
Uploader 文件上传设置disabled时，已经上传过图片后应该设置图片不可预览，删除不可用

### 描述您想要的解决方案
如上

### 建议的API是什么样的
如上

**Comment by chenjiahan** [comment]
disabled 只是禁用上传功能，其余两个行为可以通过 deletable 和 preview-full-image 属性来控制是否开启
