### ISSUE TITLE
[Bug Report] vant-popup内容滚动条件下，vant-swipe自动轮播的分页器会闪烁

### ISSUE THREAD

**Issue by kykolion** [youzan/vant#6715]
### 设备 / 浏览器
IPhone8P 的 IOS13.5.1/所有浏览器

### Vant 版本
2.9.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://devspa.jiliguala.com/store-dia/#/items" target="_blank">https://devspa.jiliguala.com/store-dia/#/items</a>

### 描述问题
使用vant-popup弹窗，在弹窗内容过多出现滚动条的情况下，弹窗内的vant-swipe自动轮播的【分页器】会出现闪烁。当我设置弹窗容器为【overflow-y: hidden;】时，就没有问题。但是这个弹窗需求是需要滚动的，所以看看是不是有什么bug

**Comment by kykolion** [comment]
@chenjiahan 请问能看下这个问题吗？

**Comment by chenjiahan** [comment]
这个问题大概率是浏览器渲染的问题，不一定能兼容

**Comment by kykolion** [comment]
ios11、12、13都有这个问题

**Comment by kykolion** [comment]
是发生了重排吗 @chenjiahan

**Comment by chenjiahan** [comment]
跟重不重排不一定有关系，总之是触发了 safari 的渲染 bug，看了下没什么好办法兼容，先 close 啦
