### ISSUE TITLE
[Bug Report] 地区选择器显示错位

### ISSUE THREAD

**Issue by aegis-jzl** [youzan/vant#6717]
### 设备 / 浏览器
所有设备

### Vant 版本
2.8.6

### Vue 版本
2.6.10

### 重现链接
<a href="https://t-shop.zhimaopened.com" target="_blank">https://t-shop.zhimaopened.com</a>

### 描述问题
在用户中心的收货地址添加时，地区选择器显示错位

**Comment by chenjiahan** [comment]
这个问题已经在 2.9.0 版本修复，建议升级试下

**Comment by aegis-jzl** [comment]
好的，我试一下

**Comment by aegis-jzl** [comment]
还是不行，已经是2.9.0了

**Comment by chenjiahan** [comment]
还是不行吗？ 能否提供一下 codesandbox 复现链接
