### ISSUE TITLE
[Feature Request] Field输入框组件建议增加换行Slots，类似cell组件的label

### ISSUE THREAD

**Issue by Candane** [youzan/vant#6719]
#### 这个功能解决了什么问题
label提示文字过多造成输入框宽度过小
#### 描述您想要的解决方案
提供一个slots位于label下方，并让label独占一行

**Comment by chenjiahan** [comment]
现有的 label 插槽应该能实现该功能，就不再新增插槽了

**Comment by Candane** [comment]
Field组件就是没有提供label插槽呀

**Comment by Candane** [comment]
> 直接使用现有的 label 插槽应该能实现该功能，就不再新增插槽了

Field组件就是没有提供label插槽呀

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/86760200-a16ae580-c077-11ea-902d-7272742449d4.png)

这个

**Comment by Candane** [comment]
> ![image](https://user-images.githubusercontent.com/7237365/86760200-a16ae580-c077-11ea-902d-7272742449d4.png)
> 
> 这个
你是指设置label的宽度为100%，并在label插槽里面自定义上下结构的label+textarea来实现是吗？
![expamle](https://user-images.githubusercontent.com/23361322/86762914-8b5e2480-c079-11ea-9a74-e66181807043.png)

**Comment by chenjiahan** [comment]
都可以哈

**Comment by Candane** [comment]
> 都可以哈，如果只是上下布局的话，直接通过样式设置 flex-direction 应该就可以

> 好的，了解了，不过还是没有像cell组件一样提供title和label插槽方便一些，O(∩_∩)O~
