### ISSUE TITLE
[Feature Request] Steps 组件建议增加未激活状态颜色属性

### ISSUE THREAD

**Issue by Candane** [youzan/vant#6720]
#### 这个功能解决了什么问题
设置:active="-1"时可直接当成显示组件显示，例如51job H5端简历显示教育经历，工作经历等场景
#### 描述您想要的解决方案
:inactive-color

**Comment by chenjiahan** [comment]
可以的，后续会加上

**Comment by chenjiahan** [comment]
已在 2.9.1 版本支持
