### ISSUE TITLE
swiper组件先隐藏后显示

### ISSUE THREAD

**Issue by wangyangyong** [youzan/vant#6722]
### 设备 / 浏览器
谷歌

### Vant 版本
2.9.0

### Vue 版本
3.0.0-beta.18

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/swipe" target="_blank">https://youzan.github.io/vant/#/zh-CN/swipe</a>

### 描述问题
在页面中调用组件，组件中使用swiper，先隐藏组件，后显示导致swiper不能用

**Comment by chenjiahan** [comment]
隐藏会导致 Swiper 无法正确获取到自身的宽高，导致计算出错。

你可以使用 v-if，或者在显示后调用 reisze 方法
