### ISSUE TITLE
uploader组件反填不刷新的问题

### ISSUE THREAD

**Issue by 1273082756** [youzan/vant#6725]
VantWeapp 版本:1.3.3
截图链接:图1(https://sm.ms/image/7DfLOMhs2G395cY)
图2(https://sm.ms/image/eR73NVOv4qUnLk2)
设备:iPhone X
基础库版本:2.8.7
BUG说明:
在使用uploader组件的时候,我用v-model绑定了一个fileList的变量,该变量为一个数组,每个数组元素为一个对象 { url:'xxx',isImage: true },我在用户选中下拉菜单的项目后,加载对应项目的文件列表,我选择操作fileList变量来将文件反填到uploader组件上,该操作在安卓设备上(Chrome)表现正常,在iPhone X设备上(Chrome/Safari)上表现为如图所示的图片不显示,我通过检查元素发现,图片的链接已经在图2所示的位置已经成功挂载到img标签的src属性上,并且在network下查看图片资源已经成功下载,随后我通过手动触发uploader组件刷新,该图片才正常显示

**Comment by chenjiahan** [comment]
VantWeapp 问题请到 vant-weapp 仓库下反馈，感谢配合

**Comment by 1273082756** [comment]
感谢您的回复
