### ISSUE TITLE
微信公众号使用vant-picker组件,会出现定位不准确问题

### ISSUE THREAD

**Issue by xiaoxiaodemeng** [youzan/vant#6728]
选中位置处于俩项中间

vant 版本 2.8.4

使用了
"postcss-loader": "^3.0.0",
"postcss-pxtorem": "^5.1.1",

https://youzan.github.io/vant/#/zh-CN/picker

![微信图片_20200707170923](https://user-images.githubusercontent.com/30209304/86756019-a5493880-c074-11ea-84d0-6ca37a4f93ef.jpg)

**Comment by xiaoxiaodemeng** [comment]
微信开发工具没有问题，真机就会出现定位问题，最后一项划不到

**Comment by chenjiahan** [comment]
这个问题已经在 2.9.0 版本修复了，可以升级试下
