### ISSUE TITLE
请问picker赋值只能通过赋index吗 不能通过value或者v-model赋初始值吗

### ISSUE THREAD

**Issue by lwm98** [youzan/vant#6733]
你好，请问一下。就是后台返回的数据，我需要给picker赋值，但是看手册api 只能通过default-index来默认选中。
我只能拿到这个值，去比对我的 option 找到 index 才能给picker赋初始选中的那一项吗..
谢谢大佬

**Comment by Airkro** [comment]
目前看是这样的，相关建议已经有几个issue提出，vant 3 的picker有可能支持 v-model 赋值， 但 2.x 应该是没戏了。

**Comment by lwm98** [comment]
没关系，多写一个方法。
```
this.timeDefaultIndex = this.timeOption.findIndex(item => {
      return item.value == this.form.timeId
})
```

**Comment by chenjiahan** [comment]
用上面的方法就可以，我们争取在 3.x 版本里优化下
