### ISSUE TITLE
[Bug Report] vant包内嵌资源使用xx/yzcdn.cn域名问题

### ISSUE THREAD

**Issue by garrettzxd** [youzan/vant#6734]
### 设备 / 浏览器
拼多多商家版APP内嵌

### Vant 版本
2.8.5

### Vue 版本
2.5.22

### 重现链接
<a href="http://www.google.com" target="_blank">http://www.google.com</a>

### 描述问题
1.在APP为宿主的环境下，问题连接贴不出来
2.由于某些APP不允许使用任何跨域资源（比如拼多多APP），导致APP内嵌网页请求跨域资源报错（也不能通过样式或者内容覆盖操作来解决），无法正常使用
3.希望能资源本地化或者提供替换资源的方法

**Comment by yulimchen** [comment]
> ### 设备 / 浏览器
> 拼多多商家版APP内嵌
> 
> ### Vant 版本
> 2.8.5
> 
> ### Vue 版本
> 2.5.22
> 
> ### 重现链接
> http://www.google.com
> 
> ### 描述问题
> 1.在APP为宿主的环境下，问题连接贴不出来
> 2.由于某些APP不允许使用任何跨域资源（比如拼多多APP），导致APP内嵌网页请求跨域资源报错（也不能通过样式或者内容覆盖操作来解决），无法正常使用
> 3.希望能资源本地化或者提供替换资源的方法

有使用本地资源的办法的：`import 'vant/lib/icon/local.less'`

**Comment by chenjiahan** [comment]
字体图标可以使用上面的方式，Empty 组件可以参考：https://github.com/youzan/vant/issues/6779

其他组件暂时没有计划调整
