### ISSUE TITLE
[Feature Request] stepper 支持空值

### ISSUE THREAD

**Issue by Airkro** [youzan/vant#6735]
### 这个功能解决了什么问题
stepper 组件目前要求一定要有值，当 min 不等于0 的时候，用户无法选择不填。

如果组件支持空值，则可以在不违背 min 的情况下使用

### 描述您想要的解决方案
这是一个我在使用的临时解决方案，用在值不为 0 的场景，能解决基本问题，但仍会显示 0：

https://codesandbox.io/s/vant-stepper-nullable-e7pd3

在这个示例中，如果 value - step = min，则按下减号按钮会将值清零，希望官方有更好地实现。

### 建议的API是什么样的
未知

**Comment by chenjiahan** [comment]
按照步进器的交互规范，是一定会有一个值的，你是在什么场景里不需要填写输入的值喔

**Comment by Airkro** [comment]
场景很多，例如一个体温记录项 <stepper min=35 max=40 /> 

假设页面逻辑是可以不填，则应该默认使用空值。但由于 min 不等于 0，界面便强制使用了 35

**Comment by chenjiahan** [comment]
默认交互是不会轻易改的，不过可以增加一个配置项，allow-empty，开启这个属性可以允许空值

**Comment by kooriookami** [comment]
stepper有个疑问，手动输入的值打印出来是string，清空值打印的是的是空字符串，照理说应该都是number类型吧

**Comment by Airkro** [comment]
@kooriookami 你说这个问题市面上很多组件库里的 number-input 都不能完美解决，因为牵扯到原生 input 的特性以及格式化等需求，尤其是当键盘输入未完成的数字的时候，做类型转换会阻碍输入。

**Comment by chenjiahan** [comment]
已在 2.9.1 版本支持

**Comment by Airkro** [comment]
@chenjiahan 

十分感谢，现在新的组建效果良好

但又因此发现了一个 bug，使用 `disable-minus` 的优先级小于 `min` 对 `minus` 按钮的影响

**Comment by chenjiahan** [comment]
@Airkro 这个不属于 bug，目前就是这么设计的
