### ISSUE TITLE
在使用的过程中发现，进度条组件时而走，时而不走，有时候刷新一下就走，有时候光百分比变动，但是进度条并无变动

### ISSUE THREAD

**Issue by mrzhouxl** [youzan/vant#6737]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
