### ISSUE TITLE
Grid 可以设置图标大小却不能设置文字大小

### ISSUE THREAD

**Issue by ge123567** [youzan/vant#6738]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
文字大小建议直接通过 css 选择器覆盖样式来调整
