### ISSUE TITLE
[Feature Request] SubmitBar按钮自定义颜色

### ISSUE THREAD

**Issue by graysole** [youzan/vant#6740]
### 这个功能解决了什么问题
自定义SubmitBar中的按钮颜色

### 描述您想要的解决方案
可自定义SubmitBar中的按钮颜色，以适配自己的页面

### 建议的API是什么样的
描述更详尽

**Comment by chenjiahan** [comment]
后续会支持

**Comment by chenjiahan** [comment]
已在 2.9.1 版本支持
