### ISSUE TITLE
[Feature Request] List组件向上滚动很容易触发PullRefresh组件下拉刷新

### ISSUE THREAD

**Issue by xuncong** [youzan/vant#6741]
### 这个功能解决了什么问题
List组件向上滚动时不会误触发PullRefresh组件刷新事件

### 描述您想要的解决方案
PullRefresh组件所包裹的组件的scrollTop=0的前提下，下拉触发刷新

### 建议的API是什么样的
可以提供一个属性，用来控制下拉刷新的临界点（touch start事件结合touch end事件）

**Comment by chenjiahan** [comment]
PullRefresh 内部是做了判断的，只有滚动容器的 scrollTop 为 0 时才能够触发下拉刷新

如果某些特殊场景需要自定义下拉刷新的触发时机，可以使用 PullRefresh 的 disabled 属性来作为开关

**Comment by SeekerGAO** [comment]
尝试设置PullRefresh为实际滚动区域[#6955](https://github.com/youzan/vant/issues/6955)
