### ISSUE TITLE
下拉刷新在魅族手机下拉时，有时候出现内容视觉叠加的情况

### ISSUE THREAD

**Issue by hasbug** [youzan/vant#6742]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

魅族手机，下拉刷新，有很大机率会拖拽出一层同样的DOM元素，形成叠加的情况。。。。
![UmZHaR.png](https://s1.ax1x.com/2020/07/09/UmZHaR.png)

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
