### ISSUE TITLE
[Bug Report] van-uploader 移动端图片方向会旋转

### ISSUE THREAD

**Issue by yangyuanftl** [youzan/vant#6744]
### 设备 / 浏览器
小米手机/微信浏览器

### Vant 版本
2.9.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsbin.com/wituwup/1/edit?html,css,js" target="_blank">https://jsbin.com/wituwup/1/edit?html,css,js</a>

### 描述问题
CDN引入vant.js，在微信浏览器图片方向会改变，而且前置摄像头和后置摄像头表现不一致。请问有没有什么优化方案

**Comment by kooriookami** [comment]
可以用exif-js获取图片旋转信息
```js
     Exif.getData(file.file, () => {
        let orientation = Exif.getTag(file.file, 'Orientation');
     });
```
然后用canvas手动旋转。。

**Comment by chenjiahan** [comment]
楼上正解

**Comment by yangyuanftl** [comment]
[解决代码.txt](https://github.com/youzan/vant/files/4900629/default.txt)
