### ISSUE TITLE
van-calendar

### ISSUE THREAD

**Issue by yuyuabc1** [youzan/vant#6745]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

vant-calendar当切换最大时间范围的时候会出现白屏情况,如同所示

![image](https://user-images.githubusercontent.com/26144081/87019849-b37a8e80-c205-11ea-8bb1-1a240c46b28d.png)

**Comment by yuyuabc1** [comment]
http://chuantu.xyz/t6/739/1594285384x-1404755214.png

**Comment by yuyuabc1** [comment]
把max-date调小再调大之后就可以复现

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
