### ISSUE TITLE
[Bug Report] 在使用中提示  unused local variable 

### ISSUE THREAD

**Issue by helloCx** [youzan/vant#6747]
### 设备 / 浏览器
webStorm

### Vant 版本
2.8.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsbin.com/?html,output" target="_blank">https://jsbin.com/?html,output</a>

### 描述问题
vant 标签 v-for 显示参数未使用，需要设置什么吗？
![image](https://user-images.githubusercontent.com/26318927/87105738-5f67bc80-c28e-11ea-91e9-cd9134578396.png)

**Comment by chenjiahan** [comment]
这个和 vant 没关系，属于编辑器本身的提示

**Comment by helloCx** [comment]
在 van-steps 是可以正常识别的。我需要在webStorm设置什么吗？

**Comment by chenjiahan** [comment]
理论上是不需要设置的喔，而且 van-step 和 van-steps 标签应该没有区别才对
