### ISSUE TITLE
[Bug Report] 对已经生成的van-calendar进行修改max-date操作会导致日历白屏没有数据的情况

### ISSUE THREAD

**Issue by yuyuabc1** [youzan/vant#6749]
### 设备 / 浏览器
任何模拟器都可

### Vant 版本
2.9.1-beta.1

### Vue 版本
2.6.1

### 重现链接
<a href="https://codepen.io/yuyuabc1/pen/abdKbPq?editors=1011" target="_blank">https://codepen.io/yuyuabc1/pen/abdKbPq?editors=1011</a>

### 描述问题
van-calendar更换max-date会导致白屏问题

**Comment by chenjiahan** [comment]
按上面的步骤试了下并没有复现呢，Chrome 浏览器

**Comment by yuyuabc1** [comment]
你等页面加载完了 再试一次，先点击显示日历 然后看一下 应该显示到8月份再点击切换max-date，然后再往下拉 会发现9月份和10月份都是空白的，你稍微多试几次一定能复现的，chrome浏览器可以

**Comment by chenjiahan** [comment]
还是没复现，能录个屏看下吗

**Comment by yuyuabc1** [comment]
http://www.56.com/u57/v_MTY1Mjg3Mjc4.html
这是视频地址，复现用的就是上述codepen链接

**Comment by yuyuabc1** [comment]
> 还是没复现，能录个屏看下吗
http://www.56.com/u57/v_MTY1Mjg3Mjc4.html
这是视频地址，复现用的就是上述codepen链接

**Comment by chenjiahan** [comment]
没复现，尝试在 2.9.3 版本修复了一下，可以升级试试
