### ISSUE TITLE
[Bug Report] 上传组件的upload-text不起作用？slot自定义区域不能点击？

### ISSUE THREAD

**Issue by limchen233** [youzan/vant#6751]
### 设备 / 浏览器
华为mate20

### Vant 版本
2.9.1-beta.1

### Vue 版本
3.0.0-beta.20

### 重现链接
<a href="https://github.com/limchen233/Front-Web/tree/master/11%20vant_issue" target="_blank">https://github.com/limchen233/Front-Web/tree/master/11%20vant_issue</a>

### 描述问题
上传组件是封装的一个动态表单的公共组件，根据后端返回数据类型去渲染动态表单。上传图片、预览都没问题。
1、加了upload-text属性，不起作用。
2、用slot="default"添加自定义上传区域，然后给区域添加了点击事件，点击事件不起作用。

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
