### ISSUE TITLE
[Bug Report] list列表数据不足一屏连续触发onload

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#6752]
### 设备 / 浏览器
所有

### Vant 版本
2.6.3

### Vue 版本
2.6.5

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?type=Bug" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?type=Bug</a>

### 描述问题
不是bug，讨论使用，我初次数据不够一屏，文档说理想数据满一屏，当我不足一屏该怎么不让onload触发呢

**Comment by chenjiahan** [comment]
不满一屏的时候，继续触发请求是合理的，否则页面将无法滚动。不让 onLoad 触发的方法是将 finished 设置为 true
