### ISSUE TITLE
[Bug Report] WKWebView 中 ImagePreview 旋转异常

### ISSUE THREAD

**Issue by 867380699** [youzan/vant#6753]
### 设备 / 浏览器
iPhone11 Pro 模拟器

### Vant 版本
2.6.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html" target="_blank">https://youzan.github.io/vant/mobile.html</a>

### 描述问题
在 WKWebView 打开官网的 ImagePreview
横屏转到竖屏，图片很大，屏幕仅显示左半边图片
竖屏转至横屏，会同时显示两张小尺寸的图片

一个可复现问题的工程： https://github.com/867380699/WKDemo

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5781

**Comment by 867380699** [comment]
iPhoneX真机也是稳定复现...

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/87424518-a77c3b80-c60e-11ea-92f6-5add1d9d5662.png)

用微信试了下没问题呢，iphoneXR

**Comment by 867380699** [comment]
嗯嗯，微信和webview应该不一样，iPhone X 真机 Safari上是好的 ，webView 里就会有问题...

**Comment by chenjiahan** [comment]
能提供一个具体的复现场景吗，比如某个常见 APP 的 WebView

**Comment by 867380699** [comment]
上面有个 ios的demo工程额(iOS 13+)， 我用的就是最基本的 webkit 提供的 webview

https://developer.apple.com/documentation/webkit/wkwebview

**Comment by chenjiahan** [comment]
试了下加个 orientationchange 的监听可以解决，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.10.0-beta.0 版本修复

**Comment by 867380699** [comment]
iOS13上已解决，但是又发现 iOS11 上问题还在...
