### ISSUE TITLE
[Bug Report] van-checkbox默认插槽中使用Stepper ，如何阻止步进器的事件向上冒泡？

### ISSUE THREAD

**Issue by h-hong** [youzan/vant#6764]
### 设备 / 浏览器
谷歌

### Vant 版本
2.9.1-beta.1

### Vue 版本
3.0.0-beta.20

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-sc8tr?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-sc8tr?file=/src/App.vue</a>

### 描述问题
在checkbox默认插槽中使用Stepper 
Stepper 点击增加/减少时，会同时更改到checkbox的选中状态
怎么去阻止Stepper 的事件冒泡到checkbox上

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4016

建议提问之前先自行搜索一下
