### ISSUE TITLE
在 Uni app中使用VanTabs 的一个问题。请问怎么解决？

### ISSUE THREAD

**Issue by ww33980639** [youzan/vant#6770]
在 Uni app框架下： 
.在使用<van-tabs>的时候，控制台会报错[Vue warn]: Error in mounted hook: "TypeError: this.onShow is not a function"
11:07:23.230 found in---> <VanTabs> . 虽然对使用没影响，但是请问如何解决掉这个东西。

**Comment by chenjiahan** [comment]
这是内部的 onShow 方法与 uniapp 命名冲突了，升级到最新版即可解决
