### ISSUE TITLE
[Bug Report] 引入vant组件后所有点击事件都报错: undefined is not an object (evaluating 'context.listeners[eventName]')

### ISSUE THREAD

**Issue by Jingxizi** [youzan/vant#6772]
### 设备 / 浏览器
所有

### Vant 版本
2.9.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsbin.com/?html,output" target="_blank">https://jsbin.com/?html,output</a>

### 描述问题
所有点击事件都是, button ,actionsheet, 等等, 显示都是正常的. 
TypeError: undefined is not an object (evaluating 'context.listeners[eventName]')
引用方式也是最简单的引用, 没有任何嵌套

function emit(context, eventName) {
  for (var _len = arguments.length, args = new Array(_len > 2 ? _len - 2 : 0), _key = 2; _key < _len; _key  ) {
    args[_key - 2] = arguments[_key];
  }

  var listeners = context.listeners[eventName];

  if (listeners) {
    if (Array.isArray(listeners)) {
      listeners.forEach(function (listener) {
        listener.apply(void 0, args);
      });
    } else {
      listeners.apply(void 0, args);
    }
  }
} 

报错就报在var listeners = context.listeners[eventName];一行

**Comment by chenjiahan** [comment]
可以看下是不是 Vue 版本太低了，建议使用 2.6.0 以上版本
