### ISSUE TITLE
[Bug Report] form.validate验证单个表单项在dialog组件的before-close事件中不能工作

### ISSUE THREAD

**Issue by YangPengFe1** [youzan/vant#6773]
### 设备 / 浏览器
版本 83.0.4103.116（正式版本） （64 位）

### Vant 版本
2.9.0

### Vue 版本
2.6.1

### 重现链接
<a href="https://codepen.io/yangpengfe1/pen/WNrKqRL" target="_blank">https://codepen.io/yangpengfe1/pen/WNrKqRL</a>

### 描述问题
我尝试在dialog关闭之前验证表单，但是表单的验证方法似乎不能有效的为我工作

**Comment by chenjiahan** [comment]
在 2.8.7 版本以前，Field rule 属性里的 message 不能为空，否则无法触发校验。

你可以升级到 2.8.7 版本试下
