### ISSUE TITLE
[Bug Report] Tab 使用 sticky 粘性布局在 IOS 上会出现卡顿的现象

### ISSUE THREAD

**Issue by Lkx2217** [youzan/vant#6775]
### 设备 / 浏览器
iphoneX XR SE2 等...

### Vant 版本
2.9.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tab" target="_blank">https://youzan.github.io/vant/#/zh-CN/tab</a>

### 描述问题
Tab 使用 sticky 粘性布局在 IOS 上会出现卡顿的现象，请问这个大家的怎么解决的

**Comment by chenjiahan** [comment]
如果是 UIWebView 的话，换成 WKWebView 即可。

UIWebView 限制了 scroll 事件的触发时机，所以会有卡顿
