### ISSUE TITLE
[Feature Request] Swipe 轮播组件能否实现如下样式

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant#6778]
![image](https://user-images.githubusercontent.com/23445650/87407928-675c8f00-c5f5-11ea-8d49-fbb7f14d2c21.png)

### 这个功能解决了什么问题
样式多样化，有的可能用到这样的样式

### 描述您想要的解决方案
多添加一个可配置的参数，不同样式

### 建议的API是什么样的
多添加一个可配置的参数，设置不同样式

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/swipe#swipe-zu-jian-gong-neng-tai-shao-wu-fa-shi-xian-fu-za-xiao-guo
