### ISSUE TITLE
[Feature Request] Empty中的图片地址建议改为DataURL

### ISSUE THREAD

**Issue by sbyps** [youzan/vant#6779]
### 这个功能解决了什么问题
在断网/内网情况下无法加载图片

### 描述您想要的解决方案
将empty组件中的图片地址改为DataURL，default error search

### 建议的API是什么样的
将empty组件中的图片地址改为DataURL，default error search

**Comment by chenjiahan** [comment]
将全部图片改成 DataURL 会导致代码体积过大，所以暂时不计划调整。

内网情况可以自行传入本地图片地址

**Comment by sbyps** [comment]
@chenjiahan 能否设置一个css变量来做这个事情

**Comment by chenjiahan** [comment]
目前是在 JS 内拼接的 URL，所以没法通过 CSS 变量来解决呢
