### ISSUE TITLE
[Bug Report] vant-icon 组件如何使用 symbol 引用方式的图标?

### ISSUE THREAD

**Issue by taadis** [youzan/vant#6784]
### 设备 / 浏览器
Firefox

### Vant 版本
2.9.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/icon" target="_blank">https://youzan.github.io/vant/#/zh-CN/icon</a>

### 描述问题
<vant-icon> 图标组件中如何使用 symbol 引用方式的 iconfont 图标

**Comment by chenjiahan** [comment]
Icon 组件不支持使用 symbol 引用的图标喔，需要自行封装
