### ISSUE TITLE
[Feature Request] Sidebar能否实现如下图左右联动效果

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant#6787]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/23445650/87542386-7286ec00-c6d5-11ea-94fa-eacb51c18f35.png">

### 这个功能解决了什么问题
组件功能更多，实现复杂需求

### 描述您想要的解决方案
提供左右联动的接口，用于实现复杂功能

**Comment by chenjiahan** [comment]
暂无计划支持喔，可以自行实现
