### ISSUE TITLE
[Bug Report] van-image-preview 图片预览

### ISSUE THREAD

**Issue by baijing19920921** [youzan/vant#6792]
### 设备 / 浏览器
手机端

### Vant 版本
2.8.7

### Vue 版本
2.6.1

### 重现链接
<a href="http://wx.boluozaixian.net/#/homeworkDetails?id=160&status=2" target="_blank">http://wx.boluozaixian.net/#/homeworkDetails?id=160&status=2</a>

### 描述问题
van-image-preview 图片预览，两个手操作，边左滑边放大，图片会错位，应该在左滑的时候禁止放大，放大的时候禁止左滑

**Comment by chenjiahan** [comment]
手势已经优化过了，可以升级到最新版试下。不过个别情况下还是会有图片错位的问题，下个版本会修复

**Comment by baijing19920921** [comment]
收到，感谢！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;neverland&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月18日(星期六) 下午5:46
收件人:&nbsp;&quot;youzan/vant&quot;<vant@noreply.github.com&gt;;
抄送:&nbsp;&quot;baijing19920921&quot;<1186611465@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] van-image-preview 图片预览 (#6792)

**Comment by chenjiahan** [comment]
已在 2.9.3 版本修复
