### ISSUE TITLE
DropdownMenu 下拉菜单希望新增配置项

### ISSUE THREAD

**Issue by thegithubs** [youzan/vant#6793]
<van-dropdown-item v-model="value1" :options="option1" :props="props" />
data(){
  return {
    props: {
      text: 'label',
      value: 'id'
    }
  }
}
很多时候返回字段未必和官方文档相同  此时设置props  把label和id替换默认的text和value

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
