### ISSUE TITLE
npm run dev 起不来

### ISSUE THREAD

**Issue by ImKarson** [youzan/vant#6794]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
![image](https://user-images.githubusercontent.com/58545926/87653751-8e979580-c788-11ea-8611-c2b5a5f55a0c.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
