### ISSUE TITLE
[Bug Report] tab滚动导航设置默认选中标签内容不跟随滚动

### ISSUE THREAD

**Issue by wujiayi-hb** [youzan/vant#6795]
### 设备 / 浏览器
chrome

### Vant 版本
2.9.2

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-mnpy6" target="_blank">https://codesandbox.io/s/vant-issue-moban-mnpy6</a>

### 描述问题
tab滚动导航，初始化页面设置默认选中标签，标签变了，但是内容不跟随滚动。点击的时候可正常滚动

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.9.3 版本支持
