### ISSUE TITLE
时间选择器错位问题

### ISSUE THREAD

**Issue by zyxextern** [youzan/vant#6798]
vue版本：2.6.11
vue-cli 版本：4.3.1
vant版本：2.8.7
设备：谷歌/手机火狐/手机qq浏览器/微信浏览器/钉钉浏览器
内容：使用时间选择器组件，年月居中，日无法居中，使用了弹出层加时间选择器的写法
![image](https://user-images.githubusercontent.com/56788661/87666881-028f6900-c79c-11ea-8628-3e282dfb25a0.png)

**Comment by zyxextern** [comment]
不单单年月日组件，年月日时分秒组件也会有这样的问题

**Comment by chenjiahan** [comment]
已经修复了，升级到最新版即可
