### ISSUE TITLE
[Bug Report] IOS10.2.1及IOS9 NumberKeyboard 数字键盘样式有问题，flex不兼容

### ISSUE THREAD

**Issue by Peter-Success** [youzan/vant#6799]
### 设备 / 浏览器
IOS10.2.1

### Vant 版本
2.9.2

### Vue 版本
2.5.22

### 重现链接
<a href="https://h5.tianhongjijin.com.cn/weixin-vue/wx.html#/binding" target="_blank">https://h5.tianhongjijin.com.cn/weixin-vue/wx.html#/binding</a>

### 描述问题
样式错乱，自己排查是flex属性没有生效

**Comment by chenjiahan** [comment]
建议你检查下项目里的 autoprefixer 和 browserslists 配置是否正确

**Comment by chenjiahan** [comment]
应该和这个问题类似，下个版本会修复 https://github.com/youzan/vant/issues/6307

**Comment by chenjiahan** [comment]
已在 2.9.3 版本修复
