### ISSUE TITLE
picker连级默认选中值，我已经写好demo，仅供参考给大伙们一起使用！！！

### ISSUE THREAD

**Issue by yongheng798** [youzan/vant#6808]
我的demo是完整的介绍和使用vant+antv f2的演示项目，目前已经集合了picker连级默认选中值和赋值、取值功能，仅供参考。
demo地址：https://github.com/yongheng798/vant-demo3

**Comment by chenjiahan** [comment]
demo 不适合放在 issue 里面，先 close 了哈。以后 Github 会出讨论区的功能，届时可以放在里面
