### ISSUE TITLE
feature request： PullRefresh 的效果支持手动触发

### ISSUE THREAD

**Issue by Airkro** [youzan/vant#681]
实际的业务场景里（例如商品列表），除了下拉刷新，也会需要通过其他交互行为（比如点击按钮， 切换tab，搜索等）触发刷新。为了效果的一致，能否为PullRefresh添加手动触发的api ? 这样其他的刷新行为便可以使用与PullRefresh相同的刷新效果。

目前我的处理方式：
```js
manualEffect() {
  this.scrollToTop();
  this.isLoading = true;
  this.$refs.pullRefresh.height = 50;
  this.$refs.pullRefresh.status = 'loading';
}
```

但我也期待官方实现

**Comment by Airkro** [comment]
目前 PullRefresh 的v-model设为true时，并没有展示动画。

**Comment by chenjiahan** [comment]
@Airkro 明白了，我们会在下个版本支持

**Comment by chenjiahan** [comment]
已在 1.0.0 版本中支持，直接将 v-model 设置为 true 即可触发

**Comment by baloyou** [comment]
在 2.0beta 中设置v-model = true，未能触发动画，是我的问题吗？

**Comment by baloyou** [comment]
> 在 2.0beta 中设置v-model = true，未能触发动画，是我的问题吗？

@chenjiahan

**Comment by baloyou** [comment]
> > 在 2.0beta 中设置v-model = true，未能触发动画，是我的问题吗？
> 
> @chenjiahan

不好意思，我已经找到答案了，我不应该在 created 中使用它，应该在 模版渲染完毕后的生命钩子中使用。

**Comment by baloyou** [comment]
> > 在 2.0beta 中设置v-model = true，未能触发动画，是我的问题吗？
> 
> @chenjiahan

不好意思，我大概找到问题了，

我之前在created中触发它，改成mounted，并且将pull-refresh设置CSS样式`min-height:50px` 就可以了。
