### ISSUE TITLE
[Bug Report] Upload组件引起的 van-field__label 样式异常

### ISSUE THREAD

**Issue by qq71151461** [youzan/vant#6818]
### 设备 / 浏览器
所有

### Vant 版本
2.9.3

### Vue 版本
2.6.11

### 重现链接
<a href="http://mh5.0577love.net/register" target="_blank">http://mh5.0577love.net/register</a>

### 描述问题
如果没有用到upload组件，field组件，左右正常。
一旦用了，则左右成1：1结构了。
dev下正常，build:prod下有问题

**Comment by qq71151461** [comment]
应该是打包时，样式先后顺序引起的问题

**Comment by qq71151461** [comment]
![图片](https://user-images.githubusercontent.com/464274/87889364-caba4700-ca63-11ea-920c-249460dd4f1a.png)

**Comment by qq71151461** [comment]
![图片](https://user-images.githubusercontent.com/464274/87889796-02c28980-ca66-11ea-951f-4004af0945cd.png)

**Comment by qq71151461** [comment]
第一次在 带有 Uploader组件的页面里的Field样式正常。
切换到其它表单页面，就出问题了。
再切回到Uploader页面，同样也有问题。

**Comment by chenjiahan** [comment]
这个问题应该是重复引入了不同的样式，建议检查一下打包配置，可以把常用的组件统一放到一个公共模块里去加载

**Comment by qq71151461** [comment]
组件是babel 按需引入的。
如果是这个问题引起的，您的建议，是全局加载所有组件了？
现在测试过来，就是组件样式先后加载引起的问题。
比如
A页面，只有Field组件
B页面，只有Cell组件
先访问A页面，再访问B页面，再回到A页面，A页面的样式就被B页面的Cell组件的样式打乱了。被强制成左右1：1了
