### ISSUE TITLE
[Feature Request] indexBar 索引加强

### ISSUE THREAD

**Issue by Dcell** [youzan/vant#6819]
### 这个功能解决了什么问题
默认的indexbar 索引滑动，整体提示效果较弱，无法明确感知当前索引内容。

### 描述您想要的解决方案
类似中间提示或者右侧索引气泡提示功能

### 建议的API是什么样的
参考#6746 或者微信效果

**Comment by chenjiahan** [comment]
抱歉，评估了一下，暂无计划在 Vant 里内置这样的提示效果，如果有需求可以基于 select 事件自行拓展。
