### ISSUE TITLE
[Feature Request] Vant框架英文发音是什么？

### ISSUE THREAD

**Issue by wangjia1110** [youzan/vant#6821]
### 这个功能解决了什么问题
对Vant的准确定义

### 描述您想要的解决方案
实现与框架开发者意图一致的框架定义

### 建议的API是什么样的
读音是“万特”还是“威昂特”？？

**Comment by kooriookami** [comment]
vant [vænt]

**Comment by wangjia1110** [comment]
Thanks！

**Comment by akbot48** [comment]
是 laji
