### ISSUE TITLE
[Bug Report] IOS10及以下版本NumberKeyboard右侧栏按钮样式错乱

### ISSUE THREAD

**Issue by Peter-Success** [youzan/vant#6823]
### 设备 / 浏览器
IOS10

### Vant 版本
2.9.3

### Vue 版本
2.5.22

### 重现链接
<a href="https://h5.tianhongjijin.com.cn/weixin-vue/wx.html#/deal/nonMontyPurchase?fundCode=000961" target="_blank">https://h5.tianhongjijin.com.cn/weixin-vue/wx.html#/deal/nonMontyPurchase?fundCode=000961</a>

### 描述问题
点击重现链接后需要点击输入框才可以出现键盘，IOS10的safari打开Vant官网也可以复现问题

**Comment by Peter-Success** [comment]
![image](https://user-images.githubusercontent.com/23651918/87933526-fec35580-cabf-11ea-87f5-8a16c2a832d3.png)

**Comment by Peter-Success** [comment]
请问这个怎么解决？

**Comment by chenjiahan** [comment]
手头暂时没有复现的机型，你可以先调试看下是哪个样式没生效

**Comment by chenjiahan** [comment]
已复现，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.10.0-beta.5 版本修复
