### ISSUE TITLE
[Feature Request] 希望在DatetimePicker文档和API中添加[秒]

### ISSUE THREAD

**Issue by HebutShuji** [youzan/vant#6829]
### 这个功能解决了什么问题
在timepicker中datetime类型中，如果精确到秒，可以和web端系统时间"YY-MM-DD HH-mm-SS"进行数据上的同步

### 描述您想要的解决方案
DatetimePicker可以加入second，picker中能够选择年/月/日/时/分/秒。

### 建议的API是什么样的
DatetimePicker时间选择组件中API[columns-order]自定义列排序数组, 子项可选值为year、month、day、hour、minute、second

**Comment by chenjiahan** [comment]
暂无计划支持喔
