### ISSUE TITLE
 Error in render: "TypeError: Cannot read property 'hide_stock' of undefined"

### ISSUE THREAD

**Issue by lintiansheng** [youzan/vant#6832]
麻烦帮忙看一下是那里的问题？vant版本是2.9.3

以下是currentSkuData数据：
{
"goods_id": "1285480562290589696",
"quota": 0,
"quota_used": 0,
"start_sale_num": 1,
"goods_info": {
"price": 11,
"title": "qw",
"picture": "https://xxx.com/user/images/6b41b60e59032f4e/20200721/1595317402684.jpg"
},
"sku": {
"price": 11,
"stock_num": 11,
"none_sku": false,
"hide_stock": false,
"collection_id": "1285480563511132160",
"tree": [
{
"k": "尺寸",
"k_s": "sku1",
"k_id": 1,
"v": [
{
"id": 1,
"name": "24cm"
},
{
"id": 2,
"name": "22cm"
}
]
},
{
"k": "材质",
"k_s": "sku2",
"k_id": 2,
"v": [
{
"id": 1,
"name": "铸铁"
}
]
}
],
"list": [
{
"id": "1285480563511132160",
"price": 1100,
"stock_num": 0,
"sku1": 2,
"sku2": 1
},
{
"id": "1285480563511132161",
"price": 1100,
"stock_num": 11,
"sku1": 1,
"sku2": 1
}
]
}
}
以下是currentInitialSku数据：
{"sku1":1,"sku2":1}

以下是customSkuValidator数据：
customSkuValidator: () => '请选择规格',

以下是代码部分：
            <van-sku
            v-model="showPicker"
            :sku="currentSkuData.sku"
            :quota="currentSkuData.quota"
            :goods="currentSkuData.goods_info"
            :goods-id="currentSkuData.goods_id"
            :quota-used="currentSkuData.quota_used"
            :hide-stock="currentSkuData.sku.hide_stock"
            :start-sale-num="currentSkuData.start_sale_num"
            :custom-sku-validator="customSkuValidator"
            :initial-sku="currentInitialSku"
            disable-stepper-input
            reset-stepper-on-hide
            safe-area-inset-bottom
            reset-selected-sku-on-hide
            @buy-clicked="onBuyClicked"
            @add-cart="onAddCartClicked"
          />
        </div>

**Comment by lintiansheng** [comment]
看到麻烦回复一下，谢谢

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
