### ISSUE TITLE
2.9.2版本使用List组件ios滑动不流畅

### ISSUE THREAD

**Issue by afu5235** [youzan/vant#6834]
已经解决，希望能完善代码
ios端触发touch事件是在手指在屏幕上的操作期间。
例如touchend事件，是在你手指离开屏幕时就立即触发。而不是在滑动停止时触发，需要在代码中增加
 -webkit-overflow-scrolling: touch;

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
