### ISSUE TITLE
<van-loading>加载中...</van-loading> 加载中不显示，审查元素加载中...显示undefined

### ISSUE THREAD

**Issue by cqgsm** [youzan/vant#6835]
van-pull-refresh 和 van-list 的 loading-text 不管设不设置 ，都显示成了undefined

vant: 2.9.3
vue: 2.6.11

**Comment by cqgsm** [comment]
如果导入所有组件使用Vue.use(Vant)没有问题，配置按需加载后就会出现上述问题

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by fbixiaoyu** [comment]
我也复现了，一样的代码在不同的项目仓库中运行，loading-text显示是undefined或者设置的文字两种结果
