### ISSUE TITLE
[Bug Report] NumberKeyboard 组件 extra-key  @click事件不生效

### ISSUE THREAD

**Issue by webzhouyan** [youzan/vant#6836]
### 设备 / 浏览器
chrome 64

### Vant 版本
2.9.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-sf21o?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-sf21o?file=/src/App.vue</a>

### 描述问题
NumberKeyboard 组件自定义slot  extra-key  @click事件不生效
CodeSandbox中可以打印，但是在chrome 手机模拟模式或者手机浏览器中都无法触发click事件。只好用touchend事件代替

**Comment by chenjiahan** [comment]
为了消除在 safari 上的 touch 事件触发延迟，NumberKeyboard 里面在 touchend 的时候调用了 preventDefault，所以不会触发 click 事件。

后续会看下怎么兼容这种用法

**Comment by chenjiahan** [comment]
已在 2.10.7 版本修复
