### ISSUE TITLE
[Bug Report] 表单验证submit和failed事件的使用问题

### ISSUE THREAD

**Issue by Pascoe555** [youzan/vant#6837]
### 设备 / 浏览器
chrome

### Vant 版本
2.9.4-beta.0

### Vue 版本
3.0.0-rc.4

### 重现链接
<a href="https://jsbin.com/tatadoxode/edit?html" target="_blank">https://jsbin.com/tatadoxode/edit?html</a>

### 描述问题
按照手册代码测试过程中，表单提交一旦触发failed事件，后续就不会触发submit事件，会一直触发failed，打印errorInfo。打印的对象errorInfo中的属性errors值不准确，errors的值会累积不会重置，而对象中属性values的值会正常更新，希望手册表达可以更明确一些

**Comment by Pascoe555** [comment]
![0200723045527](https://user-images.githubusercontent.com/59481706/88227896-ea8a7e80-cca0-11ea-8437-f26919f8d0b2.png)
注意第三次提交的表单。。表单值跟第一次一样，应该打印submit,而不是failed。。。什么原因？

**Comment by Pascoe555** [comment]
研究了一下。。。failed事件的函数是重复使用的，没有重新渲染？？？？，加个:key重新渲染？？？

**Comment by Pascoe555** [comment]
测试了一下，failed事件添加forceUpdate方法强制重新渲染也无效，只有在van-form标签添加:key属性，failed事件改变key值才能正常使用

**Comment by chenjiahan** [comment]
message 为空的情况确实会有问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.10.0-beta.0 版本修复
