### ISSUE TITLE
[Bug Report] stepper组件小数位数限制带来的问题

### ISSUE THREAD

**Issue by webproblem** [youzan/vant#6838]
### 设备 / 浏览器
无

### Vant 版本
2.9.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/stepper" target="_blank">https://youzan.github.io/vant/#/zh-CN/stepper</a>

### 描述问题
使用stepper组件时，添加decimal-length prop 限制小数位数。现在存在的问题是，加入限制2位小数，如果输入的的值为'37.03'，输入的值拿到的是Number类型的数值，如果输入的是'37'， 那么输入的值是String类型的'37.00'，所以输入的值拿去做加减计算的话，需要先将String类型转换成Number类型才能正常计算。

**Comment by chenjiahan** [comment]
这是因为用户输入过程中可能出现小数点或空值，比如 `1.`，这种情况下  组件会抛出字符串类型。

如果希望 value 保持 number 类型，可以在 v-model 上添加 `number` 修饰符：

```html
<van-stepper v-model.number="value" />
```
