### ISSUE TITLE
文档-tabs-API-Tabs Props-swipeable

### ISSUE THREAD

**Issue by chenlang0311** [youzan/vant#6842]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater
文档-tabs-API-Tabs Props-**swipeable**应该是**swiperable**,单词拼写错误
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenlang0311** [comment]
然后tabs在sticky情况下，如果触发sticky前的宽度和触发sticky后的宽度不一致的时候，van-tabs__line这个底部的线不是响应式的

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

另外 swipeable 的拼写没有问题
