### ISSUE TITLE
[Bug Report] SwipeCell使用Web Components存在异常

### ISSUE THREAD

**Issue by Soonze** [youzan/vant#6843]
### 设备 / 浏览器
移动端

### Vant 版本
2.9.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/brave-silence-ojw2u?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/brave-silence-ojw2u?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
使用vue-cli用Web Components模式构建出来的组件，使用SwipeCell时，将打开状态的单元格滑动关闭时出现抖动

**Comment by chenjiahan** [comment]
用 Chrome 和小米 10 试了下没复现

另外 Vant 没有对 Web Components 模式做单独适配，建议自行排查
