### ISSUE TITLE
[Bug Report] Field组件在小键盘弹出后不会进行切换

### ISSUE THREAD

**Issue by edwards19900128** [youzan/vant#6850]
### 设备 / 浏览器
华为荣耀10青春版/安卓webview

### Vant 版本
2.9.1

### Vue 版本
2.6.10

### 重现链接
<a href="http://qdydsmxue.bkt.clouddn.com/vant%E8%BE%93%E5%85%A5%E6%B3%95bug.mp4" target="_blank">http://qdydsmxue.bkt.clouddn.com/vant%E8%BE%93%E5%85%A5%E6%B3%95bug.mp4</a>

### 描述问题
如链接中视频所见,如果在小键盘已经弹出后，切换不同的Field组件中type类型不一致也不会切换键盘，IOS端没有问题

**Comment by cangyu1993** [comment]
华为手机多少都有点兼容问题，不知道他们遵守的哪套标准

**Comment by chenjiahan** [comment]
这个是系统的兼容问题呢，组件使用的是浏览器标准属性

如果要兼容的话，你可以考虑试试其他的 type，或者在安卓上统一用 text
