### ISSUE TITLE
[Bug Report] Filed组件的rules属性不设置可选message属性时校验问题

### ISSUE THREAD

**Issue by yyj912838423** [youzan/vant#6852]
### 设备 / 浏览器
全部浏览器

### Vant 版本
2.9.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/yyj912838423/pen/zYrbdeO" target="_blank">https://codepen.io/yyj912838423/pen/zYrbdeO</a>

### 描述问题
问题描述：在Form组件中嵌套使用Field组件，若Field组件设置rules且rules中没有设置可选message属性，会导致某些情况下校验异常。
重现步骤：
​	步骤一：点击聚焦“验证码”输入框，不做任何输入；
​	步骤二：点击外部使“验证码”输入框失焦，触发该组件校验，placeholder内容变红；
​	步骤三：再次点击聚焦“验证码”输入框，输入符合规则正常内容，输入内容呈现红色；
​	步骤四：再次点击外部使“验证码”输入框失焦，校验未重新执行，输入内容依然呈现红色；
​	步骤五：输入“手机号码”，并点击“提交”，无法触发Form组件submit事件。
补充：
        触发问题后只能通过刷新页面解决；
        输入框直接选择填入历史输入记录没有此问题。

**Comment by chenjiahan** [comment]
跟这个 issue 是同个问题：https://github.com/youzan/vant/issues/6837

下个版本会修复
