### ISSUE TITLE
[Feature Request] Swipe 轮播能否增加设置四个圆角

### ISSUE THREAD

**Issue by bydongxin** [youzan/vant#6854]
### 这个功能解决了什么问题
样式问题

### 描述您想要的解决方案
可以单独四个圆角的大小

### 建议的API是什么样的
border-radius:10px 10px 10px 10px;

**Comment by bydongxin** [comment]
自己写的样式在ios上有兼容问题，图片切换时，圆角会消失

**Comment by chenjiahan** [comment]
这个不会在组件内提供哈

解决方案：https://github.com/youzan/vant/issues/5290
