### ISSUE TITLE
[Bug Report] SwipeCell滑动单元格beforeClose事件能否支持传入业务参数

### ISSUE THREAD

**Issue by StupidSummer** [youzan/vant#6859]
### 设备 / 浏览器
Chrome浏览器手机调试模式

### Vant 版本
2.9.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://9tj0n.csb.app/" target="_blank">https://9tj0n.csb.app/</a>

### 描述问题
SwipeCell点击右侧按钮后并不能根据业务需求对相应的单元格做出.点击删除的时候将对应的sapn从数组中删除

**Comment by chenjiahan** [comment]
不支持传入业务参数喔，你可以用 name 属性作为标识符，去匹配对应的业务数据

**Comment by sdauxing** [comment]
通过把业务参数放在name 属性中，可以传参数
`<van-swipe-cell v-for="(item, subIndex) in items" :key="item.id" :before-close="beforeClose" :name="item.id+ '/' + subIndex>`
在从beforeClose 方法中取回name 中的参数
`beforeClose({ name, position, instance }) {
            switch (position) {
                case 'left':
                case 'cell':
                case 'outside':
                instance.close();
                    break;
                case 'right':
                   console.log(name)
               break
            }
        }`
