### ISSUE TITLE
[Bug Report] van-number-keyboard不能挂载到app下

### ISSUE THREAD

**Issue by qwqwzheng** [youzan/vant#6864]
### 设备 / 浏览器
所有

### Vant 版本
2.9.4-beta.0

### Vue 版本
3.0.0-rc.4

### 重现链接
<a href="https://codepen.io/qwqwzheng/pen/vYLPaaq" target="_blank">https://codepen.io/qwqwzheng/pen/vYLPaaq</a>

### 描述问题
van-number-keyboard放在popup里面，不能定位到窗口底部，只能定位到弹框底部

**Comment by chenjiahan** [comment]
下个版本会加一个 get-container 属性

**Comment by chenjiahan** [comment]
已在 2.10.0-beta.0 版本支持
