### ISSUE TITLE
请问 sku的多选，是如何实现的？能否提供json格式的数据

### ISSUE THREAD

**Issue by ImSuperFei** [youzan/vant#6865]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
通过 properties 这个对象实现的，完整数据可以参考 https://github.com/youzan/vant/blob/dev/src/sku/demo/data.ts
