### ISSUE TITLE
[Bug Report] Calendar 日历 组件，在切换页面时，自动获取焦点，导致页面不在顶部

### ISSUE THREAD

**Issue by markofred** [youzan/vant#6866]
### 设备 / 浏览器
Chrome

### Vant 版本
2.9.4-beta.0

### Vue 版本
2.6.4

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/calendar" target="_blank">https://youzan.github.io/vant/#/zh-CN/calendar</a>

### 描述问题
Calendar 日历 组件，在切换页面时，自动获取焦点，导致页面不在顶部；
开发指南 右侧示例，刷新后，平铺展示 的类型 将会自动获取焦点，导致页面不在顶部；

**Comment by chenjiahan** [comment]
后续会优化下

**Comment by chenjiahan** [comment]
已在 2.10.0-beta.2 版本修复
