### ISSUE TITLE
[Feature Request] Tab 标签页样式添加阴影

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#6877]
### 这个功能解决了什么问题
DropdownMenu 下拉菜单默认是带阴影的，希望tab也有，可以通过属性控制是否启用

### 描述您想要的解决方案
无

### 建议的API是什么样的
shadow: string/boolean （自定义阴影样式/启用禁用）

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议自行覆盖样式
