### ISSUE TITLE
[Feature Request] Tag 标记能否有更小的尺寸

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#6880]
### 这个功能解决了什么问题
目前默认的size在手机上一些场景还是很大
![QQ图片20200727142704_看图王](https://user-images.githubusercontent.com/38392315/88510404-7f7cd700-d015-11ea-9da0-40dd34ab7d12.jpg)

![QQ图片20200727142709_看图王](https://user-images.githubusercontent.com/38392315/88510422-8572b800-d015-11ea-8698-9f2389126300.jpg)

默认尺寸和京东的tag对比的图

### 描述您想要的解决方案
字体可以到10px或更小，边框的粗细也做适应

### 建议的API是什么样的
size可选small和mini

**Comment by chenjiahan** [comment]
10px 字体在安卓上会出现文字不居中的问题，所以不推荐使用 10px 字体

如果有这个需求，建议自行覆盖样式实现呢
