### ISSUE TITLE
[Bug Report] vant collapse组件postcss-viewport-units 错误

### ISSUE THREAD

**Issue by fengyun2** [youzan/vant#6884]
### 设备 / 浏览器
win10/chrome 84.0.4147.89

### Vant 版本
2.9.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/ly2011/vant-collapse-error" target="_blank">https://github.com/ly2011/vant-collapse-error</a>

### 描述问题
vant collapse组件postcss-viewport-units 错误
![image](https://user-images.githubusercontent.com/8147202/88522104-79442600-d028-11ea-956b-2abc654686af.png)

**Comment by chenjiahan** [comment]
具体是指啥问题？

**Comment by fengyun2** [comment]
@chenjiahan 2.8.2版本没有展示viewport-units-bug字眼

**Comment by chenjiahan** [comment]
这个边距是新加的

**Comment by fengyun2** [comment]
自我补充一下答案：

```js
require('postcss-viewport-units')({
  silence: true,
  filterRule : rule => rule.selector.indexOf( ':after') === -1 && rule.selector.indexOf( ':before') === -1
})
```

**Comment by fengyun2** [comment]
自我补充一下答案：

```js
require('postcss-viewport-units')({
  silence: true,
  filterRule : rule => rule.selector.indexOf( ':after') === -1 && rule.selector.indexOf( ':before') === -1
})
```
