### ISSUE TITLE
[Bug Report] Calendar组件在上下滑动时日历副标题中月份与当前显示月份有时不一致

### ISSUE THREAD

**Issue by dandelionwindy** [youzan/vant#6885]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.6

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/calendar#ping-pu-zhan-shi" target="_blank">https://youzan.github.io/vant/#/zh-CN/calendar#ping-pu-zhan-shi</a>

### 描述问题
Calendar组件在上下滑动时日历副标题中月份与当前显示月份有时不一致

**Comment by chenjiahan** [comment]
能否提供下复现的链接或视频

**Comment by dandelionwindy** [comment]
这个情况在vant说明文档上在上下滑动Calendar组件时就会复现的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2020年7月28日(星期二) 晚上7:26
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "赵祖会"<1455686361@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] [Bug Report] Calendar组件在上下滑动时日历副标题中月份与当前显示月份有时不一致 (#6885)





 
能否提供下复现的链接或视频

**Comment by chenjiahan** [comment]
我试了下没问题，注意月份的标题触顶时才会更新头部的月份

**Comment by dandelionwindy** [comment]
这个问题其实在下滑的时候不是很明显，上滑的时候就很明显，可以说是操作的问题，但是体验上不是很好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 下午4:50
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "赵祖会"<1455686361@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] [Bug Report] Calendar组件在上下滑动时日历副标题中月份与当前显示月份有时不一致 (#6885)





 
我试了下没问题，注意月份的标题触顶时才会更新头部的月份
