### ISSUE TITLE
[Feature Request] 怎么自定义form item

### ISSUE THREAD

**Issue by xiangfengsu** [youzan/vant#6891]
### 这个功能解决了什么问题
怎么自定义实现一个表单组件

### 描述您想要的解决方案

```javascript
<van-field name="customField" label="自定义组件">
  <template #input>
    <customFormItem v-model="custom" />
  </template>
</van-field>


```

### 建议的API是什么样的
可以和目前的表单组件一样，自动校验，收集数据

**Comment by xiangfengsu** [comment]
我看了源码，mixins: [FieldMixin], 就可以了

**Comment by xiangfengsu** [comment]
好奇怪，循环自定义表单，所有的值都绑定到最后一表单中，改怎么自定义呢？

**Comment by chenjiahan** [comment]
@xiangfengsu 可以提供个 codesandbox 复现链接看下

**Comment by xiangfengsu** [comment]
是我自己的问题，就是mixins: [FieldMixin], 就可以了，谢谢
