### ISSUE TITLE
官方API文档无法访问

### ISSUE THREAD

**Issue by peamed** [youzan/vant#6893]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by Lan-megumi** [comment]
同，国内访问返回404
就算搭梯子也是404

**Comment by p4fl** [comment]
同，刚刚国内镜像还能访问。现在也不能。估计是缓存更新了。

**Comment by chenjiahan** [comment]
可以访问了：https://vant-contrib.gitee.io/vant/#/zh-CN/

**Comment by ling317** [comment]
> 可以访问了：[https](https://vant-contrib.gitee.io/vant/#/zh-CN/) : [//vant-contrib.gitee.io/vant/#/zh-CN/](https://vant-contrib.gitee.io/vant/#/zh-CN/)

还是访问不了，不过手机UC，夸克浏览器可以。这是啥原因啊。为啥不能访问了。

**Comment by Lan-megumi** [comment]
电信 Chorme 可以访问

> > 可以访问了：[https](https://vant-contrib.gitee.io/vant/#/zh-CN/) : [//vant-contrib.gitee.io/vant/#/zh-CN/](https://vant-contrib.gitee.io/vant/#/zh-CN/)
> 
> 还是访问不了，不过手机UC，夸克浏览器可以。这是啥原因啊。为啥不能访问了。
