### ISSUE TITLE
vant Field组件高度自适应在华为手机文字超出一行，末尾会显示大光标

### ISSUE THREAD

**Issue by huahua13007343846** [youzan/vant#6894]
华为手机上显示：
https://imgchr.com/i/aZ3mbd

代码：
 <van-field 
       v-model="remarks"
       type="textarea"
       autosize
       class="address addressEdit" 
       placeholder="*如有顺丰寄回单号，请在备注填写，方便售后师傅对应准确订单哦"
  />

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by huahua13007343846** [comment]
> 请按照模板创建 issue，感谢配合

链接打不开
