### ISSUE TITLE
[Bug Report] tab 手势滑动不会触发before-change

### ISSUE THREAD

**Issue by c33286** [youzan/vant#6895]
### 设备 / 浏览器
chrome

### Vant 版本
2.9.4

### Vue 版本
2.6.10

### 重现链接
<a href="https://jsbin.com/zeyirec/edit?html,js,output" target="_blank">https://jsbin.com/zeyirec/edit?html,js,output</a>

### 描述问题
Tab组件通过手势滑动没有触发before-change函数

**Comment by chenjiahan** [comment]
在目前的设计里，手势滑动是不会触发 before-change 的，因为之后手势滑动会增加过渡动画效果，如果在动画过渡完成后再通过 before-change 拦截滑动，会导致交互很奇怪。
