### ISSUE TITLE
vant Field组件高度自适应在华为手机文字超出一行，末尾会显示大光标

### ISSUE THREAD

**Issue by huahua13007343846** [youzan/vant#6896]
设备 / 浏览器
华为荣耀10

Vant 版本
2.9.4

Vue 版本
2.6.11

重现链接
https://imgchr.com/i/aZ3mbd

描述问题
使用vant Field组件高度自适应，在华为荣耀10手机上，文字输入超过一行，则末尾会显示一根大光标，高度和输入内容高度一致，ios手机没有

代码：
 <van-field 
       v-model="remarks"
       type="textarea"
       autosize
       class="address addressEdit" 
       placeholder="*如有顺丰寄回单号，请在备注填写，方便售后师傅对应准确订单哦"
  />

**Comment by chenjiahan** [comment]
这是滚动条吧？

**Comment by huahua13007343846** [comment]
> 这是滚动条吧？

不是滚动条，我把滚动条设为了0，还是这样
::-webkit-scrollbar {
  width: 0 !important;
  background: transparent !important;
}

**Comment by huahua13007343846** [comment]
> 这是滚动条吧？

解决了，谢谢您。还真的是滚动条! 样式没设置对。

.aftersale /deep/ .van-field__control::-webkit-scrollbar {
  display: none; /* 隐藏滚动条 */
}
