### ISSUE TITLE
[Feature Request] 在form表单中field组件现在通过js改变value的值无法触发rules的验证规则

### ISSUE THREAD

**Issue by cgd199158** [youzan/vant#6897]
### 这个功能解决了什么问题
解决JS改变value时能触发input的onchange事件

### 描述您想要的解决方案
是否能给field组件添加一个类似于$JQuery.trigger('change')的方法,实现在value值改变的是否手动触发input的onchange事件并触发相应的form表单验证规则

### 建议的API是什么样的
是否能给field组件添加一个类似于$JQuery.trigger('change')的方法,实现在value值改变的是否手动触发input的onchange事件并触发相应的form表单验证规则

**Comment by chenjiahan** [comment]
暂无计划添加喔，可以通过调用 Form 的 validate 方法来触发表单校验
