### ISSUE TITLE
[Bug Report] 官网css文件cdn地址都报403了

### ISSUE THREAD

**Issue by angeldong666** [youzan/vant#6900]
### 设备 / 浏览器
iPhone

### Vant 版本
2.8.0

### Vue 版本
2.6.2

### 重现链接
<a href="https://cdn.jsdelivr.net/npm/vant@2.8/lib/index.css" target="_blank">https://cdn.jsdelivr.net/npm/vant@2.8/lib/index.css</a>

### 描述问题
cdn引入文件地址报403

**Comment by zf1067517249** [comment]
我也是 怎么解决啊

**Comment by angeldong666** [comment]
> 我也是 怎么解决啊

不知道是不是官网限制ip了，，我vpn可以访问到，然后copy了一份放本地了

**Comment by zf1067517249** [comment]
哎哎

**Comment by yaowangmx** [comment]
我挂了vpn都打不开

**Comment by chenjiahan** [comment]
Github 上文档访问不了的话，可以访问国内镜像文档：https://vant-contrib.gitee.io/vant/#/zh-CN/
