### ISSUE TITLE
我在vue项目中使用van-collapse组件时，在ios系统上，超出了屏幕的折叠面板部分就会被隐藏掉，安卓中没有问题

### ISSUE THREAD

**Issue by Yangxiucheng1002** [youzan/vant#6901]
设备 / 浏览器
iPhone

Vant 版本
2.8.5

Vue 版本
2.6.11

描述问题
在ios系统中，折叠面板版超出屏幕高度会被隐藏剩余内容，无法滑动

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
