### ISSUE TITLE
官网 cdn 都挂了 访问不到 403？？？

### ISSUE THREAD

**Issue by zf1067517249** [youzan/vant#6903]
所有版本都不行

**Comment by Jon-Millent** [comment]
那是 `https://cdn.jsdelivr.net/` 挂了好吧，和`vant`没关系

**Comment by Jon-Millent** [comment]
`https://cdn.jsdelivr.net/npm/vant@2.9.4/lib/index.min.js` 试试这个，403和vant没关系

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6900
