### ISSUE TITLE
[Bug Report] flex布局，对于flex:1，overflow:scroll的元素可以使用List的上拉更多功能，滚动一直在触发load事件

### ISSUE THREAD

**Issue by bluescurry** [youzan/vant#6904]
### 设备 / 浏览器
IOS

### Vant 版本
2.9.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### 描述问题
如题

**Comment by chenjiahan** [comment]
无效的重现链接。
