### ISSUE TITLE
[Bug Report] GoodsAction样式炸了

### ISSUE THREAD

**Issue by HankGuo** [youzan/vant#6905]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.0-beta.0

### Vue 版本
2.6.10

### 重现链接
<a href="https://jsbin.com/komikexuzi/edit?html,output" target="_blank">https://jsbin.com/komikexuzi/edit?html,output</a>

### 描述问题
按照官方文档例子使用goodsAction组件，样式错乱

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/quickstart#chang-jian-wen-ti

**Comment by HankGuo** [comment]
感谢，已解决
