### ISSUE TITLE
https://youzan.github.io/无法访问

### ISSUE THREAD

**Issue by 18876406890** [youzan/vant#6906]
亲爱的各位前辈你们好，从昨天早上发现贵公司的https://youzan.github.io/站点已无法正常访问，烦请排查下问题，其他方式无法联系到你们，才出此下策，望海涵。

**Comment by chenjiahan** [comment]
Github Pages 的问题

可以访问国内镜像文档：https://vant-contrib.gitee.io/vant/#/zh-CN/
