### ISSUE TITLE
stepper 输入达到最大值，如10，后面输入0变为100，value值正确，但是input显示100很尴尬

### ISSUE THREAD

**Issue by dylan921208** [youzan/vant#691]
建议在oninput方法加一个覆盖input的value的方法
onInput(event) {
      const { value } = event.target;
      this.currentValue = value ? this.correctValue(+value) : value;
     **event.target.value = this.currentValue;**
      this.emitInput();
    },

**Comment by zaxlct** [comment]
测试小姐姐给也我提了这么一个 BUG，很尴尬。。。
