### ISSUE TITLE
打不开官网https://youzan.github.io/vant

### ISSUE THREAD

**Issue by geasscai** [youzan/vant#6915]
打不开官网https://youzan.github.io/vant

**Comment by linupychiang** [comment]
https://vant-contrib.gitee.io/vant-weapp

**Comment by geasscai** [comment]
> https://vant-contrib.gitee.io/vant-weapp

这个可以,谢谢

**Comment by geasscai** [comment]
https://youzan.github.io/vant 翻墙可以打开
