### ISSUE TITLE
[Feature Request] 希望在 DropdownMenu下拉菜单 中加入多选的功能

### ISSUE THREAD

**Issue by jr1260** [youzan/vant#6916]
### 这个功能解决了什么问题
现在的 DropdownMenu下拉菜单 只能单选，不能多选。希望能出一个多选的功能

### 描述您想要的解决方案
希望在 DropdownMenu下拉菜单 中加入多选的功能

### 建议的API是什么样的
默认是单选，可以通过参数配置成多选

**Comment by chenjiahan** [comment]
暂无计划支持喔，可以通过插槽来实现

**Comment by xiang0308** [comment]
> 暂无计划支持喔，可以通过插槽来实现

@jr1260  同求！大佬，非常希望支持多选功能~~

**Comment by iyanming** [comment]
同求
