### ISSUE TITLE
[Bug Report] tabs 滑动不触发事件

### ISSUE THREAD

**Issue by jiahui336** [youzan/vant#6922]
### 设备 / 浏览器
ios

### Vant 版本
2.9.4

### Vue 版本
3.0.0-rc.5

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tab" target="_blank">https://youzan.github.io/vant/#/zh-CN/tab</a>

### 描述问题
tabs 滑动不触发事件 点击 可以 但是滑动不行

**Comment by chenjiahan** [comment]
什么事件？
