### ISSUE TITLE
[Bug Report] tabs里面用全选反选会报错 

### ISSUE THREAD

**Issue by jiahui336** [youzan/vant#6923]
### 设备 / 浏览器
公众号

### Vant 版本
2.9.4

### Vue 版本
2.6.0

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/checkbox" target="_blank">https://youzan.github.io/vant/#/zh-CN/checkbox</a>

### 描述问题
tabs里面用全选反选会报错  放在van-tab 外面就可以

**Comment by chenjiahan** [comment]
建议把 lazy-render 设置为 false 试下
