### ISSUE TITLE
Form 组件 scroll-to-error 滚动至错误表单属性无效

### ISSUE THREAD

**Issue by 841440416** [youzan/vant#6928]
设备 / 浏览器
ios/android/chrome 64

Vant 版本
2.8.7

Vue 版本
2.6.11

描述问题
scroll-to-error属性设置为true的时候，点击提交按钮触发校验，当第一个表单校验不通过时页面会滚动至最下方，而不是第一个错误的表单初

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
