### ISSUE TITLE
[Bug Report] 项目添加rem适配后，日历组件显示空白bug

### ISSUE THREAD

**Issue by wuliankui86** [youzan/vant#6929]
### 设备 / 浏览器
iPhone 7 Plus

### Vant 版本
2.10.0-beta.1

### Vue 版本
3.0.0-rc.5

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/calendar" target="_blank">https://youzan.github.io/vant/#/zh-CN/calendar</a>

### 描述问题
项目添加rem适配后，日历组件显示空白bug，需滑动部分距离后才能正常显示。建议：在进行dom操作时，元素样式用rem赋值，或提供rem/px赋值方法。

**Comment by chenjiahan** [comment]
能否提供一下复现问题的仓库

**Comment by wuliankui86** [comment]
> 能否提供一下复现问题的仓库

https://github.com/wuliankui86/vant-demo

**Comment by chenjiahan** [comment]
试了下没复现，是在特定设备下出现吗，能否录个屏看下

**Comment by wuliankui86** [comment]
![image](https://user-images.githubusercontent.com/51112588/89479153-a7fa9300-d7c4-11ea-9822-9e78e3b20e4b.png)
无法滚动到底部，滚动区域会一直跳动。
![image](https://user-images.githubusercontent.com/51112588/89479259-edb75b80-d7c4-11ea-9853-46030fda54db.png)
ipad初始化时显示空白

**Comment by wuliankui86** [comment]
> 复现了，下个版本会修复

感动啊！
但是只要是通过操作dom赋值的组件，rem适配都没法转换，这个问题也是头疼。

**Comment by chenjiahan** [comment]
这个没办法，DOM 里的内联样式转不了滴

**Comment by chenjiahan** [comment]
已在 2.10.3 版本修复滚动区域跳动的问题

**Comment by zzyseven** [comment]
> 复现了，下个版本会修复

最新版iphone还有这个问题，type是range
