### ISSUE TITLE
[Feature Request] Vant dark themes

### ISSUE THREAD

**Issue by minhngvan** [youzan/vant#6930]
Anyone have dark theme define for var.less?

**Comment by chenjiahan** [comment]
Sorry, we currently have no plans to support dark mode.

**Comment by vinyll** [comment]
It seems like dark theme [is now in Vant](https://github.com/youzan/vant/blob/64f5ebd56bcd6ab034234042e57e80f918e06861/packages/vant/src/popover/demo/index.vue#L52)  :)
