### ISSUE TITLE
[Bug Report] Popup顶部出现1px背景色

### ISSUE THREAD

**Issue by wht300** [youzan/vant#6932]
### 设备 / 浏览器
所有

### Vant 版本
2.9.4

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/hungry-bash-k4opr" target="_blank">https://codesandbox.io/s/hungry-bash-k4opr</a>

### 描述问题
当Popup设置高度100%展示时且容器高度变化时，顶部会出现约1px的缝隙，露出底部内容
场景：安卓触发输入框导致页面高度改变时易触发
复现方式：打开https://codesandbox.io/s/hungry-bash-k4opr后拖动视口改变预览区域高度顶部会出现1px缝隙，露出底部红色背景内容

**Comment by chenjiahan** [comment]
这个是浏览器本身的渲染精度导致的（Popup 上有 transform 属性）

如果介意的话，可以把 transform 干掉：

```html
<van-popup
  v-model="showRight"
  position="right"
  transition="van-slide-right"
  :style="{
    width: '30%',
    height: '100%',
    top: 0,
    bottom: 0,
    transform: 'none',
  }"
/>
```
