### ISSUE TITLE
[Bug Report]  业务组件 "AddressEdit 地址编辑 " 中 按钮莫名丢失的BUG

### ISSUE THREAD

**Issue by 1414044032** [youzan/vant#6933]
## 设备 / 浏览器
Chrom

## Vant 版本
2.9

## Vue版本
2.6.10

## 重现链接
[https://codepen.io/1414044032/pen/QWNLJaV](https://codepen.io/1414044032/pen/QWNLJaV)

## 描述问题
AddressEdit 地址编辑 这个业务组件。
我想复用在  新增地址 以及 修改地址的 业务逻辑中。
我用 isShow 这个变量来控制是新增地址，还是修改地址。当业务是修改地址时， 显示删除按钮以及设置默认收获地址。
当我如此操作时，我发现设置isShow 为false，然后再设置为true时，删除按钮 以及 保存按钮 都不在了。

## 预期效果
当isShow为true 时，显示删除按钮，设置默认收获地址，保存按钮。当isShow为false时，只显示保存。

## 实际效果
初次打开页面。isShow默认为为true 时，显示删除按钮，设置默认收获地址，保存按钮。当isShow为false时，只显示保存。==》当再次点击按钮修改isShow为true时，保存按钮，删除按钮 都将莫名消失。

**Comment by 1414044032** [comment]
@chenjiahan 大佬，看看codepen，救救孩子吧！

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.10.0-beta.5 版本修复
