### ISSUE TITLE
单元格Cell label插槽不生效

### ISSUE THREAD

**Issue by hzr1140521792** [youzan/vant#6940]
### 设备 / 浏览器
mac/chrome

### Vant 版本
2.10.0-beta.4

### Vue 版本
3.0.0-rc.5

### 重现链接
<a href="https://codesandbox.io/s/m5v3f?file=/src/App.vue" target="_blank">https://codesandbox.io/s/m5v3f?file=/src/App.vue</a>

### 描述问题
 `<van-cell
        v-for="item in list"
        :key="item.id"
        :title="item.name   '['   item.fundcode   ']'"
        size="large"
      />
      <template slot="label">
        <div>11</div>
        
      </template>`

**Comment by chenjiahan** [comment]
注意 `<template slot="label">` 语法从 Vue 2.6 版本开始支持

**Comment by chenjiahan** [comment]
我试了下没问题，建议你重新试下，或者提供正确的 codesandbox 复现链接
