### ISSUE TITLE
[Bug Report] tab的active异常

### ISSUE THREAD

**Issue by 1259549061** [youzan/vant#6941]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.0-beta.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsbin.com/hocidiwixa/1/edit?html,output" target="_blank">https://jsbin.com/hocidiwixa/1/edit?html,output</a>

### 描述问题
由于v-if的不确定，刚开始tab可能是3个，然后动态增加一个之后v-model绑定的active失效了，默认到了第一个

**Comment by chenjiahan** [comment]
复现链接无效，建议提供可用的复现链接。
