### ISSUE TITLE
[Bug Report] Uploader 文件上传组件设置capture为camera后:after-read和:before-read不生效

### ISSUE THREAD

**Issue by ymmagic** [youzan/vant#6943]
### 设备 / 浏览器
iphone11

### Vant 版本
2.10.0-beta.4

### Vue 版本
3.0.0-rc.5

### 重现链接
<a href="https://codepen.io/MingEric/pen/GRZRNep?editors=1010" target="_blank">https://codepen.io/MingEric/pen/GRZRNep?editors=1010</a>

### 描述问题
Uploader 文件上传组件设置capture为camera后:after-read和:before-read不生效,但是如果不使用capture为camera是生效的

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/6939

**Comment by liuxiaoning96** [comment]
你好👋, 请问问题解决了吗?  我现在也遇到了上边的问题, 设置capture属性, after-read不生效, 期待你的回复, 谢谢
