### ISSUE TITLE
搭建了一个离线文档库，但是很多静态资源项目中没有！

### ISSUE THREAD

**Issue by xiafeifei** [youzan/vant#6944]
你好，我们公司开发环境是内网！我搭建了一个离线文档库，但是很多静态资源（图片、图标）项目中没有！
克隆了 Vant 后编译成文档的版本中有大量资源指向了以下网址
https://b.yzcdn.cn/vant/*
https://img.yzcdn.cn/vant/*
翻遍了你们的项目，没有类似的 资源仓库。
请问是否可以提供一个离线静态资源的压缩包！谢谢！

**Comment by chenjiahan** [comment]
暂无计划提供喔，可以直接通过 URL 把这些资源下载到本地替换一下
