### ISSUE TITLE
[Bug Report] Uploader 文件上传组件设置capture为camera，:accept="'video/*'" 出现闪退现象

### ISSUE THREAD

**Issue by asdwer098** [youzan/vant#6945]
### 设备 / 浏览器
安卓手机

### Vant 版本
2.3.3

### Vue 版本
2.5.20

### 重现链接
<a href="https://codepen.io/asdwer098/pen/JjXjVjG" target="_blank">https://codepen.io/asdwer098/pen/JjXjVjG</a>

### 描述问题
录像时间超过十几秒后，就会造成调用的相关应用直接闪退，不在触发afterRead方法，猜测是安卓的录像过大导致的。在小米6 小米9 华为Mate30上均出现该问题

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/89525085-3fd59c80-d818-11ea-9d76-59f1af2c4350.png)
