### ISSUE TITLE
[Bug Report] 当picker组件使用级联的场景下，在为数字0的情况下defaultIndex会失效

### ISSUE THREAD

**Issue by AfterThreeYears** [youzan/vant#6947]
### 设备 / 浏览器
Chrome84.0.4147.105 

### Vant 版本
2.9.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-mk57i?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-mk57i?file=/src/App.vue</a>

### 描述问题
在级联菜单里设置defaultIndex，在为数字0的情况下，结果与预期的不一样

**Comment by chenjiahan** [comment]
已在 2.10.0-beta.5 版本修复
