### ISSUE TITLE
[Feature Request] button加载功能新增

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#6950]
### 这个功能解决了什么问题
加载icon只能使用vant自带的icon，希望新增loading插槽(可以放置logo图片)

### 描述您想要的解决方案
希望新增loading插槽，用户自定义loading旋转样式

### 建议的API是什么样的
希望新增loading插槽

**Comment by chenjiahan** [comment]
已在 2.10.1 版本支持
