### ISSUE TITLE
[Feature Request] ShareSheet增加取消按钮是否显示属性

### ISSUE THREAD

**Issue by chue4909** [youzan/vant#6951]
### 这个功能解决了什么问题
当shareSheet直接展示到页面上，不需要通过其他方式触发显示与隐藏，此时取消按钮不需要展示

### 描述您想要的解决方案
增加新属性控制取消按钮是否显示

### 建议的API是什么样的
增加is-cancel属性，默认true

**Comment by chenjiahan** [comment]
直接把 cancel-text 设置为空就可以隐藏取消按钮

```html
<van-share-sheet
  v-model="show"
  :options="options"
  cancel-text=""
/>
```
