### ISSUE TITLE
vant-contrib.gitee.io/vant 搜索结果跳转链接还是 https://youzan.github.io/vant/#/zh-CN/

### ISSUE THREAD

**Issue by M69W** [youzan/vant#6954]
这个项目很赞，必须有赞！

https://youzan.github.io/vant 解析IP 是 `127.0.0.1`后
在 GitHub 看到 Vant 提供了 [vant-contrib.gitee.io/vant](vant-contrib.gitee.io/vant)
新域名文档里面的搜索结果跳转的链接还是 https://youzan.github.io/vant/#/zh-CN/

比如说搜索 `dialog`  即 `https://youzan.github.io/vant/#/zh-CN/dialog`
而不是`https://vant-contrib.gitee.io/vant/#/zh-CN/dialog`

虽然浏览器自动搜索也能用，
这个可以改下吗

谢谢，再次感谢你们

**Comment by chenjiahan** [comment]
搜索的跳转地址确实得优化下，我们近期看看

**Comment by chenjiahan** [comment]
链接已修复
