### ISSUE TITLE
pullrefresh 内部嵌套list，向下滚动后，再想向上滚动，此时会触发刷新直接回到顶部了。咋整？

### ISSUE THREAD

**Issue by lkbtt** [youzan/vant#6955]
能否控制 只在顶部，下拉才刷新？

**Comment by lkbtt** [comment]
`# 研究了很久，监听滚动条，计算高度，最后简单处理，让refresh scroll,list高度自动【原本是list滚动】
.van-pull-refresh {
  height: calc(100vh - 100px) !important;
  overflow: auto !important;
}
.row-list {
  height: auto !important;
}`

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by SeekerGAO** [comment]
> # 研究了很久，监听滚动条，计算高度，最后简单处理，让refresh scroll,list高度自动【原本是list滚动】
> `.van-pull-refresh { height: calc(100vh - 100px) !important; overflow: auto !important; } .row-list { height: auto !important; }`

在安卓微信内置浏览器、夸克浏览器下会出现只要往上滑动，scrollTop就会为0，导致往上滑就会触发下拉刷新，已通过以上方式解决
主要就是让van-pull-refresh包裹的内容为实际的滚动区域。

**Comment by AlanKnightly** [comment]
@chenjiahan 这个问题怎么看都是bug，请问会解决吗

**Comment by chenjiahan** [comment]
不是 bug 喔，是使用组件时外部样式不正确导致的

**Comment by AlanKnightly** [comment]
@chenjiahan 抱歉是我误会了，我看了pull-refresh源码里，发现触发refresh的条件是看pull-refresh组件的直接父级DOM的scrollTop是否为0。这个条件直接决定了用户在使用组件时需要特别留意样式布局或通过js控制disabled prop来实现业务场景需要。不过这个触发refresh的条件好像在3.2的文档里没提到，建议还是补充地提一下吧。

**Comment by chenjiahan** [comment]
已补充到文档

**Comment by xhc-code** [comment]
我现在在vant4也遇到了，这个问题就是矛盾，首先想在一个固定高度div盒子里展示列表，给div盒子设置一个100%高度，van-pull-refresh组件也设置100%高度？这时下拉刷新是可以了，但是当元素过多，不会出现滚动条。因为van-pull-refresh 组件是监测父dom的滚动条，而下拉刷新滑动是基于van-pull-refresh的内容元素的高度而定。van-pull-refresh下的列表组件，进行上滑的时候，会导致直接触发下滑刷新，无法进行上滑数据。我也不清楚有没有给描述明白。。。太难了。

van-pull-refresh组件设置固定的高度加上可滚动的样式，就能解决了。

**Comment by xhc-code** [comment]
> [@chenjiahan](https://github.com/chenjiahan) 抱歉是我误会了，我看了pull-refresh源码里，发现触发refresh的条件是看pull-refresh组件的直接父级DOM的scrollTop是否为0。这个条件直接决定了用户在使用组件时需要特别留意样式布局或通过js控制disabled prop来实现业务场景需要。不过这个触发refresh的条件好像在3.2的文档里没提到，建议还是补充地提一下吧。

我感觉是bug，van-pull-refresh组件下拉刷新监听父dom的scrollY，下拉刷新滑动的空白区域是监听van-pull-refresh组件的子dom。那么问题就来了，如何做到空白区域支持下拉刷新，同时又能上滑列表数据呢？因为van-pull-refresh组件的父dom的scrollY肯定是0位置。

**Comment by HWT-coder** [comment]
建议通过 disabled 结合滚动位置。scrollTop非顶部位置或在底部时`disabled=!isAtTop ||  isBottom` 直接禁用下拉刷新
