### ISSUE TITLE
[Bug Report] vant tab组件滚动导航没法滚动到最后一个tab

### ISSUE THREAD

**Issue by fengyun2** [youzan/vant#6960]
### 设备 / 浏览器
win10/Chrome 84.0.4147.89

### Vant 版本
2.9.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/competent-roentgen-3vk8f" target="_blank">https://codesandbox.io/s/competent-roentgen-3vk8f</a>

### 描述问题
vant tab组件滚动导航没法滚动到最后一个tab,例如在demo中当向下滚动时，tab标签没法滚动到【内容-19 tab栏】和【内容-20 tab栏】
![image](https://user-images.githubusercontent.com/8147202/89638713-d8365480-d8de-11ea-8ba2-464e57aa6d30.png)

**Comment by chenjiahan** [comment]
这个是正常的，因为你设置的内容高度比较小，滚动条的最终位置只到内容 - 18

**Comment by fengyun2** [comment]
> 这个是正常的，因为你设置的内容高度比较小，滚动条的最终位置只到内容 - 18

必须设置内容高度等于或大于100vh才可以正确滚动到【内容-20 tab栏】吗？

**Comment by fengyun2** [comment]
> 这个是正常的，因为你设置的内容高度比较小，滚动条的最终位置只到内容 - 18

但是实际上，某个Tab栏的内容本就是很少，需要这样限制不是很好吧

**Comment by chenjiahan** [comment]
不是限制，按目前的交互是没法做到的，现在的逻辑是滚动位置触达内容的顶部时激活标签
