### ISSUE TITLE
[Bug Report] van-field的v-model如果设置null会被自动转化成空字符串

### ISSUE THREAD

**Issue by frankyeyq** [youzan/vant#6963]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/frankyeyq/pen/rNeaPXp" target="_blank">https://codepen.io/frankyeyq/pen/rNeaPXp</a>

### 描述问题
van-field的v-model如果设置null会被自动转化成空字符串，并且就算手动设置null也无效

**Comment by chenjiahan** [comment]
这个是正常逻辑喔，v-model 对应的值会自动格式化为字符串格式，如果想输入 null，应该是字符串 `'null'`

**Comment by frankyeyq** [comment]
> 这个是正常逻辑喔，v-model 对应的值会自动格式化为字符串格式，如果想输入 null，应该是字符串 `'null'`

如果可以设置成null或者对象会有什么问题？

**Comment by chenjiahan** [comment]
问题是输入框的显示值和 value 不一致。

你可以看下浏览器原生 input 的 value，同样不会有 null

**Comment by rainy-rainy** [comment]
同样问题，会改变原来的值，null值会被转换成空串。原生input和textarea不会
