### ISSUE TITLE
输入框组件field设置autosize，无法根据内容自适应高度，只会显示右侧滚动条。

### ISSUE THREAD

**Issue by 18870559800** [youzan/vant#6964]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
