### ISSUE TITLE
van-radio-group样式不一致

### ISSUE THREAD

**Issue by Penggggg** [youzan/vant#697]
**What is the current behavior?**

van-radio-group的样式与官网不一致

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

相同的代码，官网的按钮在右，实际上的按钮在左

> 代码／图片如下（稍大）

```    
<van-popup
  v-model="showPop"
  position="bottom"
  class="more-choice-popup"
>
      <p class="title">客户等级</p>
      <van-radio-group v-model="radio">
        <van-cell-group>
          <van-cell><van-radio name="1">单选框 1</van-radio></van-cell>
          <van-cell><van-radio name="2">单选框 2</van-radio></van-cell>
        </van-cell-group>
      </van-radio-group>
</van-popup>
```

![官网例子](https://images2018.cnblogs.com/blog/896425/201803/896425-20180315152755112-184052189.png)

![我的代码](https://images2018.cnblogs.com/blog/896425/201803/896425-20180315152811592-2102554256.png)

![实际例子](https://images2018.cnblogs.com/blog/896425/201803/896425-20180315152829693-1759417572.png)

**What is the expected behavior?**

van-radio-group的样式应该与官网一致

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
- Vant: 0.12.10
- Vue: 2.5.12

**Comment by chenjiahan** [comment]
@Penggggg 官网的是 Demo，样式可以自已去调整
