### ISSUE TITLE
[Bug Report] upload插件如果只使用照相功能上传图片，则无法调用上传图片接口

### ISSUE THREAD

**Issue by ymmagic** [youzan/vant#6973]
### 设备 / 浏览器
iphone11

### Vant 版本
2.10.0

### Vue 版本
3.0.0-rc.5

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-x45x9?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-x45x9?file=/src/App.vue</a>

### 描述问题
upload插件如果选择是可以通过相册上传图片，图片通过调用后端的接口可以上传到后端的服务器上，但是如果选择的是通过照相上传图片，则无法调用后端的接口上传

**Comment by chenjiahan** [comment]
重现链接不完整，能否贴一个可以运行的示例？

**Comment by ymmagic** [comment]
[https://codepen.io/MingEric/pen/poyJLzR](url)
我加上去了，这个如果在电脑端打开没法打开camera，必须用手机打开

**Comment by ymmagic** [comment]
是不是直接选择拍照的文件后缀不支持？

**Comment by ymmagic** [comment]
我使用安卓手机也试了下使用拍照上传，也不行

**Comment by ymmagic** [comment]
终于解决了这个问题，是因为如果使用照相功能，拍摄的图片太大了，而不能调用上传的接口。。。。。

**Comment by chenjiahan** [comment]
明白👌 那可以做一下图片压缩，不是组件的问题
