### ISSUE TITLE
[Bug Report] Picker选择器组件 confirm和cancel事件点击没有反应

### ISSUE THREAD

**Issue by leecuteee** [youzan/vant#6974]
### 设备 / 浏览器
IOS

### Vant 版本
2.9.3

### Vue 版本
2.5.20

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-5mtd2?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-5mtd2?file=/src/App.vue</a>

### 描述问题
项目上线一个月后有两个苹果手机用户（目测是iphone7和iphoneXR/11机型，系统不知道多少）反馈选完选项以后确认或者取消点击没有反应，不会关闭选项弹出框。但是本人iphone11，系统13.1，可以正常打开确认关闭，同事的安卓手机也没有问题。

**Comment by chenjiahan** [comment]
可以访问官网示例试试，看看能否正常关闭

**Comment by leecuteee** [comment]
> 可以访问官网示例试试，看看能否正常关闭

都可以啊 部分手机是正常打开关闭的。

**Comment by chenjiahan** [comment]
官网示例没问题的话，建议排查下你自己的代码逻辑，看看是否有兼容性问题或是其他问题
