### ISSUE TITLE
[Bug Report] 2.10.0版本tab字体显示不全

### ISSUE THREAD

**Issue by xiong201** [youzan/vant#6976]
### 设备 / 浏览器
荣耀V30Pro/企业微信浏览器

### Vant 版本
2.10.0

### Vue 版本
2.6.0

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tab" target="_blank">https://youzan.github.io/vant/#/zh-CN/tab</a>

### 描述问题
[图片]

**Comment by xiong201** [comment]
![TIM截图20200810165627](https://user-images.githubusercontent.com/28087433/89766897-7585c880-db2b-11ea-9c41-7fe3dd98b8b3.png)

**Comment by chenjiahan** [comment]
目前 Tab 没有设置行高，会继承外部的样式，可能出现这个问题。

下个版本会优化一下

**Comment by xiong201** [comment]
好的

**Comment by xiong201** [comment]
好的

**Comment by xiong201** [comment]
好的

**Comment by xiong201** [comment]
好的

**Comment by xiong201** [comment]
好的

**Comment by xiong201** [comment]
好的

**Comment by xiong201** [comment]
好的

**Comment by chenjiahan** [comment]
已在 2.10.2 版本修复
