### ISSUE TITLE
area.js需要更新一下子

### ISSUE THREAD

**Issue by bianchengcaiji-crt** [youzan/vant#6977]
在山东省烟台市蓬莱市和长岛县已经规划为蓬莱区，而area.js还是蓬莱市和长岛县

**Comment by axetroy** [comment]
建议从采用数据

https://github.com/modood/Administrative-divisions-of-China

**Comment by chenjiahan** [comment]
可以提个 PR 喔

**Comment by chenjiahan** [comment]
看了下最新的官方数据，蓬莱还没更新。等更新后再改吧

http://www.mca.gov.cn///article/sj/xzqh/2020/2020/2020072805001.html
