### ISSUE TITLE
list能否支持局部上拉加载

### ISSUE THREAD

**Issue by chenshaxuanjing** [youzan/vant#6978]
目前list组件只能全屏使用，我只想用在页面的局部，比如弄一个父div包裹list，父div给一个高度，
这样使用后,list是不会触发onLoad事件了
请问是我使用有误，还是list的确不支持局部的上拉加载

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
