### ISSUE TITLE
在2.10.1版本中 好几个d.ts文件错误

### ISSUE THREAD

**Issue by jiangmingwen** [youzan/vant#6981]
` tsc
node_modules/vant/types/dialog.d.ts:27:34 - error TS2304: Cannot find name 'Element'.

27   getContainer?: string | (() => Element);
                                    ~~~~~~~

node_modules/vant/types/form.d.ts:10:51 - error TS2304: Cannot find name 'ScrollIntoViewOptions'.

10   scrollToField(name: string, options?: boolean | ScrollIntoViewOptions): void;
                                                     ~~~~~~~~~~~~~~~~~~~~~

node_modules/vant/types/image-preview.d.ts:22:38 - error TS2304: Cannot find name 'Element'.

22       getContainer?: string | (() => Element);
                                        ~~~~~~~

node_modules/vant/types/notify.d.ts:16:22 - error TS2304: Cannot find name 'Event'.

16   onClick?: ((event: Event) => void) | null;
                        ~~~~~

node_modules/vant/types/toast.d.ts:26:34 - error TS2304: Cannot find name 'Element'.

26   getContainer?: string | (() => Element);
                                    ~~~~~~~

node_modules/vue/types/options.d.ts:81:8 - error TS2304: Cannot find name 'Element'.

81   el?: Element | string;
          ~~~~~~~

node_modules/vue/types/options.d.ts:188:7 - error TS2304: Cannot find name 'HTMLElement'.

188   el: HTMLElement,
          ~~~~~~~~~~~

node_modules/vue/types/vnode.d.ts:20:9 - error TS2304: Cannot find name 'Node'.

20   elm?: Node;
           ~~~~

node_modules/vue/types/vue.d.ts:24:17 - error TS2304: Cannot find name 'Element'.

24   readonly $el: Element;
                   ~~~~~~~

node_modules/vue/types/vue.d.ts:29:42 - error TS2304: Cannot find name 'Element'.

29   readonly $refs: { [key: string]: Vue | Element | Vue[] | Element[] };
                                            ~~~~~~~

node_modules/vue/types/vue.d.ts:29:60 - error TS2304: Cannot find name 'Element'.

29   readonly $refs: { [key: string]: Vue | Element | Vue[] | Element[] };
                                                              ~~~~~~~

node_modules/vue/types/vue.d.ts:40:30 - error TS2304: Cannot find name 'Element'.

40   $mount(elementOrSelector?: Element | string, hydrating?: boolean): this;`

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
