### ISSUE TITLE
文档编写错误

### ISSUE THREAD

**Issue by qiuchengxin** [youzan/vant#6983]
文档地址：
https://youzan.github.io/vant/#/zh-CN/form

 
  <van-field
    v-model="value2"
    name="validator"
    placeholder="函数校验"
    :rules="[{ validator, message: '请输入正确内容' }]"
  />
form表单文档中，自定义校验函数应为：   :rules="[{ validator: function, message: '请输入正确内容' }]"

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
写法没问题啊。用的是 shorthand
