### ISSUE TITLE
强烈建议不要废弃van-panel，布局很方便；一些erp，crm企业内部管理系统中大量使用。

### ISSUE THREAD

**Issue by zwljava** [youzan/vant#6986]
强烈建议不要废弃van-panel，布局很方便；一些erp，crm企业内部管理系统中大量使用。

**Comment by chenjiahan** [comment]
目前看到用这个组件的场景非常少，能看下你业务的截图吗

**Comment by zwljava** [comment]
大量使用了panel组件header,default,footer三段式的布局模式，很方便很实用。
![aaa](https://user-images.githubusercontent.com/29765156/89987288-62503580-dcb0-11ea-8176-2e7d58628545.png)

**Comment by lsxm** [comment]
不一定那么依赖基础组件,可以自己封装一个类似复合组件

**Comment by zwljava** [comment]
> 不一定那么依赖基础组件,可以自己封装一个类似复合组件

基础组件不要随便废弃啊，已经使用的项目代码量大，改动麻烦啊。

**Comment by chenjiahan** [comment]
虽然废弃了，但是我们会把 Panel 拆分为一个单独的 npm 包，老项目还是可以继续用的，所以不存在改动量的问题
