### ISSUE TITLE
NavBar导航栏组件，当底部输入框点击弹起键盘时，导航栏会被顶出屏幕

### ISSUE THREAD

**Issue by wangweifan** [youzan/vant#6989]
Describe the bug
NavBar导航栏组件，当底部输入框点击弹起键盘时，导航栏会被顶出屏幕

Screenshots
![微信图片_20200812104603](https://user-images.githubusercontent.com/22409524/89969871-0a9ed380-dc8a-11ea-8c07-2b97eaff39ce.jpg)
![微信图片_20200812104609](https://user-images.githubusercontent.com/22409524/89969877-0f638780-dc8a-11ea-9cdf-aa02dee62e6a.jpg)

Environment

Device: 苹果8plus
Browser: 小程序
Vant Version: 1.3.0
Reproduce
无

**Comment by chenjiahan** [comment]
小程序问题请到 vant-weapp 仓库下反馈，感谢配合
