### ISSUE TITLE
文档有一处错误，建议修改

### ISSUE THREAD

**Issue by imhxc** [youzan/vant#699]
文档错误地址：https://www.youzanyun.com/zanui/vant#/zh-CN/address-edit
错误位置: 在该文档底部，介绍`addressInfo` 数据格式的地方，`key`等于`is_default`这里。
错误描述：文档中写的`is_default`类型为`String`，但是实际开发中需要用Boolean类型。

**Comment by chenjiahan** [comment]
感谢反馈~ 会在近期修正

**Comment by chenjiahan** [comment]
已修正
