### ISSUE TITLE
[Bug Report] Dialog中文乱码

### ISSUE THREAD

**Issue by jzyzxx** [youzan/vant#6992]
### 设备 / 浏览器
小米6/chrome74.0.3729.169

### Vant 版本
2.8.3

### Vue 版本
3.0.0-rc.5

### 重现链接
<a href="https://emergency.fubangnet.cn/#/" target="_blank">https://emergency.fubangnet.cn/#/</a>

### 描述问题
打包成webapp,小米6手机Dialog里面中文乱码，浏览器版本没有乱码

**Comment by chenjiahan** [comment]
乱码和组件无关，建议自行排查下。

**Comment by chenjiahan** [comment]
乱码和组件无关，建议自行排查下。
