### ISSUE TITLE
[Feature Request] 如何使用form表单完成动态校验

### ISSUE THREAD

**Issue by dingZilong-Spce** [youzan/vant#6994]
### 这个功能解决了什么问题
根据不同条件选择，动态控制表单项是否进行验证判断
如：选择通讯类型为手机，则必须填手机号验证，如选其他，则手机号一项不必验证

### 描述您想要的解决方案
使用validator 发现并不能实现一个数据发生变化，是否验证

### 建议的API是什么样的
可以实现数据动态变化的验证

**Comment by chenjiahan** [comment]
1. 切换类型时，可以动态传入不同的 validator
2. 可以调用 Form 的 validate 方法来主动执行校验

**Comment by dingZilong-Spce** [comment]
抱歉在form文档 中并未看到validate的配置

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/90089875-1f946900-dd55-11ea-8af6-64e2b44cc173.png)

**Comment by dingZilong-Spce** [comment]
感谢大佬
