### ISSUE TITLE
slider 组件还是不支持两端滑动吗

### ISSUE THREAD

**Issue by d623141153** [youzan/vant#6999]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
还没嘞，最近比较忙，欢迎 PR
