### ISSUE TITLE
请问一下能自己添加语言吗？

### ISSUE THREAD

**Issue by ansonhorse** [youzan/vant#700]
刚了解到vant，第一印象感觉挺不错的。暂时没有找到其他咨询的途径，所以请容许我通过issue来请教一下。
问题如题，比如我想添加一个语言：马来语，能否实现？如果可以，大致的思路是什么？
谢谢！

**Comment by cookfront** [comment]
可以看下这里：[国际化](https://www.youzanyun.com/zanui/vant#/zh-CN/i18n)

**Comment by ansonhorse** [comment]
@cookfront 非常感谢
