### ISSUE TITLE
[Feature Request] popup

### ISSUE THREAD

**Issue by renshengwuhui** [youzan/vant#7000]
### 这个功能解决了什么问题
文字模糊

### 描述您想要的解决方案
设定popup的width和height时，会造成文字模糊，主要是这个translate3d造成的

### 建议的API是什么样的
建议不使用该css3，或有没有靠谱的解决方案
![1](https://user-images.githubusercontent.com/22539244/90092840-9f720180-dd5c-11ea-9233-35950b880e68.png)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3746，把宽度设置成偶数试试

**Comment by renshengwuhui** [comment]
没卵用，如果设置偶数，也是样式那的50%改成偶数，更没意义。对于PC端来说就是个废的组件

**Comment by beifeng5620** [comment]
popup的translate3d会让设置了opacity子元素文字模糊
