### ISSUE TITLE
[Feature Request] tab组件支持无内容单独使用

### ISSUE THREAD

**Issue by mudoo** [youzan/vant#7001]
### 这个功能解决了什么问题
单独使用tab组件
```
<van-tabs v-model="active" sticky :sticky-container="container">
  <van-tab title="A" />
  <van-tab title="B" />
</van-tabs>
```
### 描述您想要的解决方案
有些场景下，tab作用只是取一个值，业务逻辑较复杂，目前的这种标签与内容绑定的使用方式并不适用。
不指定内容的时候，会输出空的内容容器，且sticky无效，因为Sticky组件指定了container=this.$el
https://github.com/youzan/vant/blob/dev/src/tabs/index.js#L422

新增个stickyContainer参数暂时能满足使用，但是会输出空的内容容器

### 建议的API是什么样的
新增个stickyContainer属性，指定sticky组件的容器
内容是空的时候，不输出内容容器

**Comment by mudoo** [comment]
我看了下代码，标签是用this.children遍历生成的，如果不输出内容，貌似也生成不了标签...
https://github.com/youzan/vant/blob/dev/src/tabs/index.js#L369-L392

**Comment by chenjiahan** [comment]
暂无计划支持喔，Sticky 直接用 Sticky 组件也能满足的
