### ISSUE TITLE
[Bug Report] 如何通过confirm获取picker的选中值

### ISSUE THREAD

**Issue by ymmagic** [youzan/vant#7003]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.2

### Vue 版本
3.0.0-rc.5

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-n37b0?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-n37b0?file=/src/App.vue</a>

### 描述问题
如何让循环状态的picker选择确认后获取到选中的值

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3914
