### ISSUE TITLE
[Bug Report] Toast添加getContainer属性，返回上个界面，再次进入不生效

### ISSUE THREAD

**Issue by Roninwz** [youzan/vant#7006]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.2

### Vue 版本
3.0.0-rc.5

### 重现链接
<a href="https://codepen.io/roninwz/pen/poygMKL" target="_blank">https://codepen.io/roninwz/pen/poygMKL</a>

### 描述问题
引入Toast组件，使用getContainer属性把它挂载到div上，第一次进入该页面可以正常使用，
返回上一个界面后，再次进入该页面Toast没有反应。 除非再次手动刷新才可以再次使用。
和  https://github.com/youzan/vant/issues/3101   问题类似

**Comment by chenjiahan** [comment]
已在 2.10.3 版本修复

**Comment by yoyo837** [comment]
我咋还是有这个问题呢？

**Comment by warriorwz** [comment]
您好！来信收到，谢谢

**Comment by yoyo837** [comment]
我发现是另一个问题：

SPA时，若在A页面调用过 Dialog.confirm，点击同意或者拒绝，然后前进到B页面，再浏览器返回A页面，此时无法重新调用Dialog.confirm，因为被监听popstate onPopstate执行了this.close
