### ISSUE TITLE
vant-tabbar 在iphone 11 proMax 上不适配

### ISSUE THREAD

**Issue by haocaiMP** [youzan/vant#7008]
![{15056638-1C38-421F-95D9-5FB07FEDE527}_20200815132457](https://user-images.githubusercontent.com/23466224/90305971-d3832900-defa-11ea-9771-c3546e57c982.jpg)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by wulucxy** [comment]
@haocaiMP 解决了么，同样遇到了
