### ISSUE TITLE
[Bug Report] Uploader组件点击删除图片的按钮之后会被点击到新增图片的按钮

### ISSUE THREAD

**Issue by xiaoxiaodemeng** [youzan/vant#7009]
Vant 版本
2.9.4

Vue 版本
2.6.11

描述问题
当我点击删除图片按钮的之后会弹出新增图片的：如图地址
https://files.catbox.moe/nbhr5f.jpg

**Comment by chenjiahan** [comment]
建议你检查下是不是用了 fastclick 之类的库导致点击事件触发不正常
