### ISSUE TITLE
uploader上传组件在小米mix2中不能打开本地文件，默认只能选择相机，摄像机和录音

### ISSUE THREAD

**Issue by chaozhen** [youzan/vant#7011]
大家有没有遇到过uploader上传组件在小米mix2中不能打开本地文件，默认只能选择相机，摄像机和录音，但在其他的手机上是可以正常打开本地相册的，这个问题要怎么解决呢？

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
