### ISSUE TITLE
[Feature Request] 日历组件如何清除默认选择和已选择的

### ISSUE THREAD

**Issue by dingZilong-Spce** [youzan/vant#7013]
### 这个功能解决了什么问题
不需要默认选项日期及需要清除已选日期

### 描述您想要的解决方案
提供一个默认配置可以设置为空，或者提供一个绑定数据控制是否清除

### 建议的API是什么样的
:value

**Comment by chenjiahan** [comment]
已在 2.10.5 版本支持将 default-date 设置为 null
