### ISSUE TITLE
[Feature Request] van-circle 遮挡了van-dropdown-menu向上弹出的选项

### ISSUE THREAD

**Issue by zaoshang67dian** [youzan/vant#7018]
### 这个功能解决了什么问题
求解决方法

### 描述您想要的解决方案
不遮挡

### 建议的API是什么样的
求

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by zaoshang67dian** [comment]
> 麻烦提供一下 codesandbox 复现链接

没法提供啊， 我是在微信小程序中用的，我看下给你截个图看看吧。

**Comment by chenjiahan** [comment]
小程序应该是原生组件层级导致的（Circle 使用了 canvas 原生组件），请到 vant-weapp 仓库下反馈
