### ISSUE TITLE
[Bug Report] Form组件validate方法验证顺序问题

### ISSUE THREAD

**Issue by DiamondsZz** [youzan/vant#7019]
### 设备 / 浏览器
Chrome

### Vant 版本
2.10.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/diamondszz/pen/poyEErE" target="_blank">https://codepen.io/diamondszz/pen/poyEErE</a>

### 描述问题
点击登录先验证的是密码，正常不应该先是手机号吗

**Comment by JokerLoLgrey** [comment]
兄弟， 你可以参考一下我这种写法

先简单封装一下 field

![image](https://user-images.githubusercontent.com/33446705/90713466-f84f1600-e2d7-11ea-819e-0d86f1c42a98.png)

然后调用

![image](https://user-images.githubusercontent.com/33446705/90713539-203e7980-e2d8-11ea-867b-fc95d5883155.png)

最后一键检验

![image](https://user-images.githubusercontent.com/33446705/90713655-64317e80-e2d8-11ea-96c9-3f4d2b656113.png)

表现形式为这样

![image](https://user-images.githubusercontent.com/33446705/90713991-339e1480-e2d9-11ea-91d2-f1062c8e2f42.png)

**Comment by DiamondsZz** [comment]
@JokerLoLgrey  呃。。。感谢分享。:laughing: 我想知道我这个问题是什么原因？  是我使用的方式不对吗？:sweat_smile:

**Comment by JokerLoLgrey** [comment]
> @JokerLoLgrey 呃。。。感谢分享。😆 我想知道我这个问题是什么原因？ 是我使用的方式不对吗？😅

我看了一下，应该是toast覆盖了， 最好不要用toast
