### ISSUE TITLE
Field 组件高度自适应建议加入一个限制最高高度

### ISSUE THREAD

**Issue by Link-X** [youzan/vant#702]
不知道有么有 文档好像没有写可以限制最高高度

**Comment by chenjiahan** [comment]
感谢反馈，我们会在后续支持

**Comment by chenjiahan** [comment]
已在 1.0.0 版本中支持，autosize 可以传入对象并配置最大/最小高度 
https://www.youzanyun.com/zanui/vant#/zh-CN/field
