### ISSUE TITLE
[Feature Request] 关于Uploader 文件上传，希望可以增加拍照或者选择图片后可以进行压缩、旋转 

### ISSUE THREAD

**Issue by zhanghanhzgl** [youzan/vant#7022]
### 这个功能解决了什么问题
Uploader 文件上传解决拍照或选择的图片过大或不是正向显示

### 描述您想要的解决方案
希望Uploader 文件上传组件可以拍照或者选择图片后能进行压缩、旋转图片

### 建议的API是什么样的
有属性进行配置压缩比例或者有方法能判断图片的旋转方向

**Comment by chenjiahan** [comment]
暂无计划支持喔，可以在 after-read 中自行处理，网上有一些开源的方案来修正旋转方向的
