### ISSUE TITLE
[Bug Report] checkbox的异步写法，会导致无法阻止事件冒泡

### ISSUE THREAD

**Issue by luanwulin** [youzan/vant#7023]
设备 / 浏览器
chrome

Vant 版本
2.10.2

Vue 版本
2.6.11

描述问题

checkbox源码中，settimeout再去emit事件的方式，会导致外面的事件捕捉，无法调用event.stopPropagation

**Comment by chenjiahan** [comment]
嗯，这个问题暂时没法在组件内部处理，涉及一些不兼容更新，可以先用 click.native.catch 来捕获

```html
<van-checkbox @click.native.catch />
```

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.3 版本修复
