### ISSUE TITLE
[Feature Request] Grid宫格希望  badge 可以自己用自己图片，并且我的grid是遍历出来的，怎么让在某一个上面显示

### ISSUE THREAD

**Issue by W-ChenAMG** [youzan/vant#7025]
### 这个功能解决了什么问题
Grid宫格希望  badge 可以自己用自己图片，并且我的grid是遍历出来的，怎么让在某一个上面显示

### 描述您想要的解决方案
Grid宫格希望  badge 可以自己用自己图片，并且我的grid是遍历出来的，怎么让在某一个上面显示

### 建议的API是什么样的
Grid宫格希望  badge 可以自己用自己图片，并且我的grid是遍历出来的，怎么让在某一个上面显示

**Comment by chenjiahan** [comment]
可以使用插槽来自定义内容喔

遍历的话可以根据 index 或其他标识符来渲染对应的内容

**Comment by W-ChenAMG** [comment]
我要改的是grid宫格，某一个的右上角
badge徽标   想自定义这个     这个也是插槽?  但是我用插槽放在van-grid-item内，然后这些grid宫格 内容都不显示了
- [ ] #

**Comment by W-ChenAMG** [comment]
那我有啥办法 实现这个功能吗

**Comment by W-ChenAMG** [comment]
> 不支持单独修改 badge 的内容喔，抱歉

那我有啥办法 实现这个功能吗

**Comment by chenjiahan** [comment]
使用插槽自定义内容，然后 Badge 也自行实现

**Comment by W-ChenAMG** [comment]
> 使用插槽自定义内容，然后 Badge 也自行实现

<van-grid-item
            v-for="(item,i) in list"
            :key="i"
            :icon="item.imgUrl"
            :text="item.menuName"
            @click="goAction(item)"
            badge="NEW"
 >
</van-grid-item>

现在所有的宫格 都会带new这个徽标， 我如何 只让 特定的某一个显示这个new徽标    我可以根据我的:text="item.menuName"名字做区分 ，  但是我不知道怎么写

**Comment by W-ChenAMG** [comment]
> 使用插槽自定义内容，然后 Badge 也自行实现
<van-grid-item
            v-for="(item,i) in list"
            :key="i"
            :icon="item.imgUrl"
            :text="item.menuName"
            @click="goAction(item)"
            badge="NEW"
            v-if="item.menuName == '云程序'"
          >
</van-grid-item>

现在所有的宫格 都会带new这个徽标， 我如何 只让 特定的某一个显示这个new徽标 我可以根据我的:text="item.menuName"名字做区分 ， 但是我不知道怎么写

**Comment by W-ChenAMG** [comment]
> 使用插槽自定义内容，然后 Badge 也自行实现

<van-grid-item
v-for="(item,i) in list"
:key="i"
:icon="item.imgUrl"
:text="item.menuName"
@click="goAction(item)"
badge="NEW"
>
</van-grid-item>

现在所有的宫格 都会带new这个徽标， 我如何 只让 特定的某一个显示这个new徽标 我可以根据我的:text="item.menuName"名字做区分 ， 但是我不知道怎么写

**Comment by chenjiahan** [comment]
`:badge="i = 0 ? 'NEW' : null"`
