### ISSUE TITLE
List和PullRefresh组件在keepAlive时，无法获取scrollTop导致返回时总是回到顶部

### ISSUE THREAD

**Issue by JeasonLaung** [youzan/vant#7034]
设备 / 浏览器
浏览器

Vant 版本
2.4.7

Vue 版本
2.6.11

重现链接
暂无

描述问题
List和PullRefresh组件在keepAlive时，无法获取scrollTop导致返回该页面时总是回到顶部，如果直接用overflow:auto的原生元素我可以通过@scroll获取这个scrollTop来设置返回后的页面高度然后设置对应的scrollTop，但现在无法捕捉scroll事件和获取scrollTop，用户体验极差。

期待，添加滚动事件或获取当前的位置的接口。

**Comment by LDXu** [comment]
@JeasonLaung  最后咋解决的?

**Comment by zhoupeihuang** [comment]
貌似只能通过分页来实现，也就是说 数据增加，页面下滑，这个插件真的是把我坑的哭了好几天
