### ISSUE TITLE
Vant 3.0 RC 版本发布 🔥🔥🔥

### ISSUE THREAD

**Issue by chenjiahan** [youzan/vant#7035]
目前 Vant 已完成了对 Vue 3.0 的绝大部分适配工作，并发布了 Vant 3.0 RC 版本，欢迎大家在新项目中尝试 Vant 3.0。

### 背景知识

在使用 Vant 3.0 前，请先了解一下 Vue 3.0 的变更内容：[Vue 3.0 官方文档](https://v3.cn.vuejs.org/)

### 安装 Vant 3.0

```bash
#npm
npm i vant@next -S

# yarn
yarn add vant@next
```

安装完成后，请参考 Vant 3.0 的文档使用：

- [Vant 3.0 在线文档](https://vant-contrib.gitee.io/vant/next)
- [Vant 3.0 更新日志](https://vant-contrib.gitee.io/vant/next/#/zh-CN/changelog-v3)
- [Vant 3.0 迁移指南](https://vant-contrib.gitee.io/vant/next/#/zh-CN/migrate-from-v2)
- [Vant 3.0 源代码](https://github.com/youzan/vant)

### 后续计划

我们计划在十二月发布 Vant 3.0 正式版，目前正在进行的工作有：

- 对外提供 Vant 内部使用的 Composition API 模块，封装为  **@vant/use** 库（已完成）
- 使用 Composition API 重构所有组件（已完成）
- 使用 TypeScript 重构所有组件
- 完善单元测试并修复发现的问题
- 增加新组件和更多 Feature

### 注意事项

1. Sku 组件还未完成 Vue 3 适配，因此在 Vant 3.0 RC 版本中暂时不可用
2. beta 版本迭代过程中可能会引入少量的不兼容改动，在升级时请仔细阅读更新日志

### 视觉规范升级

近期我们还发布了 Vant 视觉规范 3.0，详见：[Vant 设计规范 3.0 发布](https://github.com/youzan/vant/issues/7147)

### 问题反馈

使用 Vant 3.0 过程中遇到问题时，请通过 issue 的形式进行反馈~

**Comment by Yankai17148** [comment]
强啊，有考虑从webpack换vite开发吗？

**Comment by chenjiahan** [comment]
会考虑滴，等 Vant 3.0 完工先

**Comment by ZhengXiaowei** [comment]
也可以抛出一些composition api的常用工具方法

**Comment by chenjiahan** [comment]
> 可以抛出一些composition api的常用工具方法

这部分要等内部使用稳定后才会考虑抛出

**Comment by heart-er** [comment]
建议在使用cdn 比如图片 不要在css文件里内置有赞本身的cdn，而是对外暴露出来，否则对于某些使用字体需要放到自己cdn的用户，会很难受，会意外的下载有赞的字体

**Comment by chenjiahan** [comment]
@heart-er 这块会改掉

**Comment by vvni** [comment]
注意样式对ie11的兼容哦~ 2.x版本还存在一些问题。

**Comment by chenjiahan** [comment]
@vvni 具体是啥问题

**Comment by vvni** [comment]
> @vvni 具体是啥问题，Vant 是移动端组件库，不会专门兼容 IE11

目前看到的是组件样式的居中问题，以及input文字被截断，emm，我晚点提几个issues

**Comment by vvni** [comment]
> @vvni 具体是啥问题，Vant 是移动端组件库，不会专门兼容 IE11

因为vant有PC端兼容嘛，所以处理一下ie11也好呀。

**Comment by chenjiahan** [comment]
> 目前看到的是组件样式的居中问题，以及input文字被截断，emm，我晚点提几个issues

好滴

**Comment by NidhoggDJoking** [comment]
效率是真的高

**Comment by lg751551023** [comment]
Uploader 组件调用摄像头拍照后部分华为手机不支持上传功能

**Comment by muzaisimao** [comment]
这, 二维码失效了呀....

**Comment by chenjiahan** [comment]
@muzaisimao 已更新

**Comment by puzzle9** [comment]
`tabbar` 在没有 `route` 的时候 会报
```
Property "$route" was accessed during render but is not defined on instance
```

**Comment by puzzle9** [comment]
不知道是不是我操作问题
用 vite 在 main 中引入的话

```
import Vant from 'vant'
import 'vant/lib/index.css'
app.use(Vant)
```

这么写 打包的时候 不能把 `css` 打包进去

如果用

```
import Vant from 'vant'
import '/@modules/vant/lib/index.css'
app.use(Vant)
```

是正常的

**Comment by snowdream** [comment]
加油，搞起来。

**Comment by mazixiao** [comment]
您好，van-tabs加了sticky属性用浏览器的前进后退来跳转路由会报错，不加sticky属性是没有问题的
1.
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Unhandled error during execution of unmounted hook 
  at <VanSticky container= <div class=​"van-tabs van-tabs--line" modelvalue=​"0">​…​</div>​ offsetTop=0 onScroll=fn<bound onSticktScroll> > 
  at <VanTabs modelValue=0 onUpdate:modelValue=fn sticky="" > 
  at <Home onVnodeMounted=fn<onVnodeMounted> onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {getCode: ƒ, commit: ƒ, …} > > 
  at <RouterView> 
  at <App>

2.
Uncaught (in promise) TypeError: Failed to execute 'unobserve' on 'IntersectionObserver': parameter 1 is not of type 'Element'.

**Comment by ctwowt** [comment]
https://github.com/youzan/vant/blob/c8d573cbe785cb0f171a127c54da8c7698d5e382/src/field/index.js#L327

`vant-next` 当没有使用 v-model 时， `event.target.composing ` 总是为 false 

导致输入框在 ios 下输入中文会有问题，

似乎这里没有使用 vue3,  v-model 内部 `vModelText` 指令 设置 event.target.composing 值

```js
    onInput(event) {
      // not update v-model when composing
      if (event.target.composing) {
        return;
      }

      this.updateValue(event.target.value);
    },
```

**Comment by 13810768336** [comment]
vue:3.12.1
vant:3.0.0
main.js中引入vant
import Vant from 'vant';
import 'vant/lib/index.css';

Vue.use(Vant);

顺便说一下，交流群过期了！！！
但是运行的时候报错，如下：

main.js?56d7:13 Uncaught ReferenceError: Vant is not defined
    at eval (main.js?56d7:13)
    at Module../src/main.js (app.js:4269)
    at __webpack_require__ (app.js:833)
    at fn (app.js:130)
    at Object.1 (app.js:4355)
    at __webpack_require__ (app.js:833)
    at app.js:971
    at app.js:974

**Comment by 13810768336** [comment]
> vue:3.12.1
> vant:3.0.0
> main.js中引入vant
> import Vant from 'vant';
> import 'vant/lib/index.css';
> 
> Vue.use(Vant);
> 
> 顺便说一下，交流群过期了！！！
> 但是运行的时候报错，如下：
> 
> main.js?56d7:13 Uncaught ReferenceError: Vant is not defined
> at eval (main.js?56d7:13)
> at Module../src/main.js (app.js:4269)
> at **webpack_require** (app.js:833)
> at fn (app.js:130)
> at Object.1 (app.js:4355)
> at **webpack_require** (app.js:833)
> at app.js:971
> at app.js:974

安装vant的时候提示：但我的已经是vue3.12.1了
npm WARN vant@3.0.0-alpha.5 requires a peer of vue@3.0.0-0 but none is installed.

**Comment by xilianfuhua** [comment]
可以再发一遍群二维码吗？？

**Comment by chenjiahan** [comment]
二维码已更新

**Comment by apem789** [comment]
vue3.0 正式版 昨天发布了。移动端可以全面换vant3.0+vue3了

**Comment by 89360944** [comment]
sku组件， 大概哪个版本能上，都beta0了

**Comment by vvni** [comment]
> sku组件， 大概哪个版本能上，都beta0了

不要做伸手党还在催，来提提PR撒...

**Comment by Yjp1120** [comment]
uploader在安卓机上进行拍照上传后，会自动旋转90°，之前处理过，但是还是想让vant3.0把这个修改一下

**Comment by ranmogit** [comment]
Area component has imported and set default area-list<object>, but browser throw the error with 'TypeError: column.setIndex is not a function...'

**Comment by Anima-No** [comment]
配置完了 。页面显示
Uncaught ReferenceError: global is not defined
    at vant.js:362
有没有遇到的

**Comment by linglingyun10** [comment]
刚刚发布的beta1.0版本，启动报错vant.js:362 Uncaught ReferenceError: global is not defined
    at vant.js:362

**Comment by chenjiahan** [comment]
@Anima-No @linglingyun10 已在 3.0.0-beta.2 版本修复

**Comment by ctwowt** [comment]
目前 vant-next 分支在 windows 下克隆，会出现 babel 转换问题：

重现： 
```
git clone -b next https://gitee.com/vant-contrib/vant.git vant-next
cd vant-next
yarn
yarn dev

```

![image](https://user-images.githubusercontent.com/37615488/94542528-7dd0c900-027b-11eb-8890-c77413e5d640.png)

下面是 mac 和 windows 对比

![image](https://user-images.githubusercontent.com/37615488/94541980-d2277900-027a-11eb-904c-418606c6c334.png)

似乎是 babel-preset 配置文件 不起作用

![image](https://user-images.githubusercontent.com/37615488/94542677-a8228680-027b-11eb-9c21-598c1ae664f9.png)

**Comment by ctwowt** [comment]
vant-cli 页面更新问题： 

![image](https://user-images.githubusercontent.com/37615488/94544568-fa64a700-027d-11eb-8501-3e4c8897688d.png)

**Comment by ZhongMingKun** [comment]
使用vite创建的vue3项目，求一个自动按需引入的方法

**Comment by heemoe** [comment]
二维码过期了

**Comment by jiesir** [comment]
头疼，下载运行组件库后就报错“Uncaught TypeError: activePostFlushCbs[postFlushIndex] is not a function”，各位大神有遇到的吗

**Comment by Nick930826** [comment]
vant3.0 swipe 轮播图组件，动态获取的数据，轮播图无法滑动

**Comment by jonnywang** [comment]
postcss.config.js 如何区分750设计稿，动态设置rootValue

**Comment by chenjiahan** [comment]
@Nick930826 已经在 vant@3.0.0-beta.5 版本修复了

**Comment by Augly** [comment]
大佬们能不能出一个react版本的?

**Comment by OctoberToEscape** [comment]
文档还是vue2.0的写法 能不能实时更新成3.0的写法，大佬

**Comment by chenjiahan** [comment]
> 大佬们能不能出一个react版本的?

https://github.com/mxdi9i7/vant-react

> 文档还是vue2.0的写法 能不能实时更新成3.0的写法

等正式版发布以后，会陆续把文档改成 setup 的写法

**Comment by lilililee** [comment]
> 头疼，下载运行组件库后就报错“Uncaught TypeError: activePostFlushCbs[postFlushIndex] is not a function”，各位大神有遇到的吗

+1

**Comment by Nick930826** [comment]
> 大佬们能不能出一个react版本的?

https://github.com/mxdi9i7/vant-react

**Comment by jiesir** [comment]
> 目前 vant-next 分支在 windows 下克隆，会出现 babel 转换问题：
> 
> 重现：
> 
> ```
> git clone -b next https://gitee.com/vant-contrib/vant.git vant-next
> cd vant-next
> yarn
> yarn dev
> ```
> 
> ![image](https://user-images.githubusercontent.com/37615488/94542528-7dd0c900-027b-11eb-8890-c77413e5d640.png)
> 
> 下面是 mac 和 windows 对比
> 
> ![image](https://user-images.githubusercontent.com/37615488/94541980-d2277900-027a-11eb-904c-418606c6c334.png)
> 
> 似乎是 babel-preset 配置文件 不起作用
> 
> ![image](https://user-images.githubusercontent.com/37615488/94542677-a8228680-027b-11eb-9c21-598c1ae664f9.png)

大神，这个问题解决了吗

**Comment by chenjiahan** [comment]
@lilililee @jiesir 感谢帮忙排查，babel loose 选项已经在最新的 next 分支移除了

**Comment by zmj0920** [comment]
> 大佬们能不能出一个react版本的?

react为啥不考虑antd呢组件那么全

**Comment by yoonasy** [comment]
@chenjiahan  vite 中按需导入怎么实现呢

**Comment by chenjiahan** [comment]
> vite 中按需导入怎么实现呢

Vant 支持 tree shaking，在 vite build 时默认就是按需引入的

**Comment by yoonasy** [comment]
@chenjiahan 好的 感谢。

```
// import 'vant/lib/index.css'
import 'vant/lib/button/index.less'
```

上面是全局引入编译好的`css`，如果我修改按钮主题变量我需要下面这种引入，那很多的情况下 我需要引入更多。

有没有一种方式`import 'vant/lib/index.less` 直接全局导入`less`便于修改主题呢，之前通过`babel-import-plugin`可以直接导入，当`vite`时候`rollup`没有这种方式

这种路径方式会报错
```
[vite] error applying css transforms: 
[LessError] {
  message: undefined,
  stack: undefined,
  type: 'Syntax',
  filename: '/Users/cssr/xxx2-wap/node_modules/vant/lib/icon/index.less',
  index: 24,
  line: 2,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [
    "@import '../style/var';",
    "@import '~@vant/icons/src/encode-woff2.less';",
    ''
  ]
} 0 [
....
```

**Comment by SharpWuqing** [comment]
在使用 v-lazy 全局注册时候 
![image](https://user-images.githubusercontent.com/22254169/100591516-d894a880-3330-11eb-8b85-e267f47629a5.png)
报错
![image](https://user-images.githubusercontent.com/22254169/100591568-ec400f00-3330-11eb-9043-24fe8142c569.png)
在 lazyload.d.ts文件 中发现
![image](https://user-images.githubusercontent.com/22254169/100591673-0aa60a80-3331-11eb-8759-8c7d0dd49e5a.png)

**Comment by chenjiahan** [comment]
@SharpWuqing Lazyload 在下个 beta 版本会支持

**Comment by lycHub** [comment]
你好，为什么vue3的源码是ts和js混合的呢

**Comment by chenjiahan** [comment]
> 为什么vue3的源码是ts和js混合的呢

TS 改造还在持续进行中

**Comment by Nick930826** [comment]
使用 Vite 创建的项目，如何修改主题色配置？

**Comment by yoonasy** [comment]
> 使用 Vite 创建的项目，如何修改主题色配置？

我是通过引入`less`组件样式文件
然后在`less`配置中修改变量颜色，配置和之前使用方式一样

**Comment by Nick930826** [comment]
你好，方便把你的配置截个图参考一下吗，vite.config.js。



---原始邮件---
发件人: "yoonasy"<notifications@github.com&gt;
发送时间: 2020年12月8日(周二) 凌晨3:49
收件人: "youzan/vant"<vant@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"ChenNick"<xianyou1993@qq.com&gt;;
主题: Re: [youzan/vant] Vant 3.0 Beta 版本发布 🔥🔥🔥 (#7035)




  
使用 Vite 创建的项目，如何修改主题色配置？
  
我是通过引入less组件样式文件
 然后在less配置中修改变量颜色，配置和之前使用方式一样

**Comment by jiesir** [comment]
vite.config.js里面的cssPreprocessOptions属性，        less: {
            modifyVars: {'primary-color': 'red'},
            javascriptEnabled: true
        },
大概就这样

**Comment by 3285177808** [comment]
阿里云双12大促进行中【免费送1核2G5M服务器，需要购买联系我，先到先得！】
1核2G内存5M带宽：57/半年
2核4G内存1M带宽:847元/3年
2核4G内存3M带宽：1107元/3年
2核8G内存3M带宽：1431元/3年
4核8G内存3M带宽：2691元/3年
8核16G内存5M带宽：7353/3年
双12主会场：https://www.aliyun.com/minisite/goods?taskCode=pintuan20201212&recordId=293114&userCode=wbqjs7bw

腾讯云秒杀活动进行中
1核2G1M50G盘，99元/1年，298元/3年
2核4G3M150G盘，586元/1年
2核4G5M(企业用户专区，限购3台)：1821元/3年
2核8G5M(企业用户专区，限购3台)：2205元/3年
4核8G5M(企业用户专区，限购3台)：3242元/3年
腾讯云活动地址：
https://curl.qcloud.com/7uwmNRdR
(建议买3年，一年的明年续费贵，腾讯云新老用户采购前私聊可在上述价格上再优惠，腾讯云续费也优惠)
联系QQ：454160064

**Comment by hj624608494** [comment]
ActionSheet, Dialog, Popup 这些类似组件在关闭显示的时候，没有动画过渡呢？

**Comment by chenjiahan** [comment]
@hj624608494 https://github.com/youzan/vant/issues/7709

**Comment by TencentIT** [comment]
强啊

**Comment by FrankFan** [comment]
> 头疼，下载运行组件库后就报错“Uncaught TypeError: activePostFlushCbs[postFlushIndex] is not a function”，各位大神有遇到的吗

2021年，我也遇到了， 环境信息：

vant:  3.0.13
vite: 2.1.3
node: 12
Android: 6.0.1 chrome51(webview)
UA: `"Mozilla/5.0 (Linux; Android 6.0.1; vivo Y66 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.3"`

![image](https://user-images.githubusercontent.com/1589433/114969252-9a94bd00-9eaa-11eb-8439-dac01f162a29.png)

查看了所有issue相关的，看到楼上2位讨论和webpack的配置项loose有关，还有一个[PR](https://github.com/youzan/vant/commit/eda6798f5d22b6102a07a81a58cdee40e2bf0e65), 又查了vant源代码，这个loose选项后面有做过修改。

稍后提供一个minimal的重现repo.


有谁知道如何解决麻烦回复下，谢谢了。

**Comment by KableShow** [comment]
> > 头疼，下载运行组件库后就报错“Uncaught TypeError: activePostFlushCbs[postFlushIndex] is not a function”，各位大神有遇到的吗
> 
> 2021年，我也遇到了， 环境信息：
> 
> vant: 3.0.13
> vite: 2.1.3
> node: 12
> Android: 6.0.1 chrome51(webview)
> UA: `"Mozilla/5.0 (Linux; Android 6.0.1; vivo Y66 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.3"`
> 
> ![image](https://user-images.githubusercontent.com/1589433/114969252-9a94bd00-9eaa-11eb-8439-dac01f162a29.png)
> 
> 查看了所有issue相关的，看到楼上2位讨论和webpack的配置项loose有关，还有一个[PR](https://github.com/youzan/vant/commit/eda6798f5d22b6102a07a81a58cdee40e2bf0e65), 又查了vant源代码，这个loose选项后面有做过修改。
> 
> 稍后提供一个minimal的重现repo.
> 
> 有谁知道如何解决麻烦回复下，谢谢了。

this is @vitejs/plugin-legacy 的锅......
