### ISSUE TITLE
[Bug Report] vant3.0文档中复选框checkbox部分的bug

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#7039]
### 设备 / 浏览器
chrome84

### Vant 版本
3.0.0-alpha.0

### Vue 版本
3.0.0-rc.7

### 重现链接
<a href="https://youzan.github.io/vant/next/#/zh-CN/checkbox" target="_blank">https://youzan.github.io/vant/next/#/zh-CN/checkbox</a>

### 描述问题
文档最下面搭配单元格组件使用的复选框，点击报错

**Comment by liyu24** [comment]
@kooriookami  能请教一下您是怎么在vue3 中引入vant的吗，我在use(Button) 的时候就会报错 ，类型“typeof Button”的参数不能赋给类型“Plugin_2”的参数。

**Comment by chenjiahan** [comment]
已在 3.0.0-alpha.3 版本修复
