### ISSUE TITLE
Sku.skuConstants   这个是干啥的 没找到    sku  步进器设置的时候 customStepperConfig

### ISSUE THREAD

**Issue by whl122677** [youzan/vant#7041]
sku  步进器设置的时候 customStepperConfig
 // const { LIMIT_TYPE } = Sku.skuConstants;
                            if (limitType === LIMIT_TYPE.QUOTA_LIMIT) {
                                let msg = `单次限购${quota}件`;
                                if (quotaUsed > 0) msg += `，你已购买${quotaUsed}`;
                                this.$toast(msg);
                            } else {
                                // this.$toast('库存不够了');
                                this.$toast(`最多购买${quotaUsed}件`);
                            }

 // const { LIMIT_TYPE } = Sku.skuConstants;   
if (limitType === LIMIT_TYPE.QUOTA_LIMIT)      这个判断里面的 Sku.skuConstants;      是做什么的

**Comment by whl122677** [comment]
已找到原因

**Comment by chenjiahan** [comment]
👌

**Comment by OrangeSAM** [comment]
> 已找到原因

老哥，啥原因啊，能不能贴一段你使用customStepperConfig的代码啊。我在源码中找到这个limit_type就两个值，一个是库存，一个是限购。
