### ISSUE TITLE
Calendar 日历bug样式Ver2.10.2

### ISSUE THREAD

**Issue by 91xtw** [youzan/vant#7043]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
**版本**
vue版，版本v2.10.2
**问题组件**
Calendar 日历
**问题描述**
组件有一个行高参数：row-height ，默认64.
当 我设定其它值时，选中的高亮色模式，却还是64千万样式混乱。

**其它提议**
因为van vue不是真正意义上的响应式的组件。所以在平板，大手机，小手机上上显示，整体会显得很小（稍微大点的手机），这认为是最不完美的地方，整体偏小，其实很好理解。因为你们坚持使用的是px.希望你们自带响应式单位（当前你们提供了转换方法），但这是治标不治本。希望你们使用vw,vh单位，或者说你们js内部自行根据屏幕dpi进行转换。谢谢你们的努力。这是我的一个小建议。

**Comment by chenjiahan** [comment]
row-height 的问题下个版本会修复

vw/vh 单位不适合作为组件库的默认单位，存在兼容性问题，而且不适合所有场景（比如大屏）

**Comment by 91xtw** [comment]
> row-height 的问题下个版本会修复
> 
> vw/vh 单位不适合作为组件库的默认单位，存在兼容性问题，而且不适合所有场景（比如大屏）

另外我想提下，什么时候支持按年滑动。现要选去年或者明年，不得滑死人么。不晓得你们当时做这个组件的应用场景是什么情况下只可选月。

**Comment by chenjiahan** [comment]
@91xtw 可以打开美团酒店或飞猪看看，都是这种日历。

目前没计划支持按年滑动，建议使用 DatetimePicker

**Comment by chenjiahan** [comment]
已在 2.10.4 版本修复样式问题
