### ISSUE TITLE
最近在用咱们的sku  这块

### ISSUE THREAD

**Issue by whl122677** [youzan/vant#7045]
customSkuValidator: () => '请选择xxx' 
   

'请选择xxx'    点击下单的时候   这个请选择的内容能动态吗 ？  好像没有地方可以修改

**Comment by chenjiahan** [comment]
可以通过国际化组件修改的喔，参见 https://youzan.github.io/vant/#/zh-CN/locale#xiu-gai-mo-ren-wen-an

**Comment by whl122677** [comment]
嗯   当我点击立即下单的时候    如果颜色没选择的话  我想提示请选择颜色         内存没选择的话  提示请选择内容 这样子的

**Comment by chenjiahan** [comment]
可以的，customSkuValidator 的第一个参数是组件实例，可以通过判断组件实例来动态返回一些文案

**Comment by whl122677** [comment]
老师  有例子吗  我不知道怎么下手    
 customSkuValidator:function (val) {
                    console.log(val)
                    return "11";
                },     会报错

**Comment by whl122677** [comment]
Property or method "toJSON" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property
