### ISSUE TITLE
建议：我能给你们提供一套完整，几乎一模一样的axure 元件库，便于产品经理使用Vant

### ISSUE THREAD

**Issue by axure-tczy** [youzan/vant#7049]
只是建议，我发现你们的设计资源里面只有Sketch组件与图标，对产品经理这个岗位不是很友好的，如果能提供axure元件库，从源头就拓展了业务场景，产品能更好的使用Vant，前端才能快捷的选用对应的组件。如果你们团队没人可以做的话，我能给你们提供。

**Comment by chenjiahan** [comment]
支持~ 欢迎 PR

**Comment by MaybeQHL** [comment]
感谢大佬。

**Comment by axure-tczy** [comment]
> 支持〜欢迎PR

https://www.pmdaniu.com/storage/121830/c08d7cc4acdf191a5ae5ea6cc59fda51-27391/start.html#g=1&p=组件库演示

元件库演示地址，可以看下，问下你们老大要不要搞套提供给用vant的产品狗狗们用用。我感觉还蛮香的。

**Comment by chenjiahan** [comment]
很棒喔，我觉得可以加到这个页面里面：https://youzan.github.io/vant/#/zh-CN/design

**Comment by axure-tczy** [comment]
> 很棒喔，我觉得可以加到这个页面里面：[https](https://youzan.github.io/vant/#/zh-CN/design) ://youzan.github.io/vant/#/zh-CN/design[](https://youzan.github.io/vant/#/zh-CN/design)

可以的，你给我个邮箱，我把源文件发你，无偿的，只是想方便我们产品这个岗位使用Vant强大的组件，我把文件相关敏感的内容删除，修正好发你，有任何问题也可以邮箱回复我。

**Comment by chenjiahan** [comment]
好的喔，麻烦发到 chenjiahan@youzan.com

**Comment by axure-tczy** [comment]
> 好的喔，[麻烦](mailto:chenjiahan@youzan.com)发到[chenjiahan@youzan.com](mailto:chenjiahan@youzan.com)

发给你了，让你们的人自己改改审核审核吧，如果需要帮助的邮箱找我。

**Comment by chenjiahan** [comment]
收到~

**Comment by chenjiahan** [comment]
已更新到官方文档，再次感谢~

**Comment by yuxiaolei1989** [comment]
感谢，推进组件库的应用，需要从源头开始，更利于下游的使用，所以给产品经理使用的 Axure 元件库就非常重要了

**Comment by Sean-Wang** [comment]
Sketch 资源有没有 @2x 的版本呢。
