### ISSUE TITLE
van-checkbox-group组件，边框不显示

### ISSUE THREAD

**Issue by 2014guai** [youzan/vant#7051]
设备 / 浏览器
IOS13.6/safari

Vant 版本
2.10.2

Vue 版本
2.6.11

重现链接

![64747bed450039ca0d5dbdc456a7c58](https://user-images.githubusercontent.com/22672617/91375729-04922080-e84e-11ea-9bd3-05c37358f5f4.jpg)

描述问题
 ```
<van-checkbox-group class="common-list" v-model="result">
              <van-checkbox
                class="common-list-item"
                v-for="item in list"
                shape="square"
                :name="item.id"
                :key="item.id">{{ item.namecn }}
              </van-checkbox> 
</van-checkbox-group>
```
van-checkbox-group组件，加载数据后，首屏显示checkbox边框，第二屏就不显示边框

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by alone-lmh** [comment]
请问您解决了吗？什么原因？同样碰到这个问题
