### ISSUE TITLE
在 iphone7 版本11.3.1   Field 内容过多无法拖动内容

### ISSUE THREAD

**Issue by zDOUBEL** [youzan/vant#7052]
### 设备 / 浏览器
iphone7  版本11.3.1

### Vant 版本
2.10.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/field" target="_blank">https://youzan.github.io/vant/#/zh-CN/field</a>

### 描述问题
利用官网的连接在手机上打开，也可重现这个问题

**Comment by chenjiahan** [comment]
是指无法滑动页面？ 能否录个屏看下

**Comment by zDOUBEL** [comment]
你好，感谢您的回复，我已经录制了一段视频
就是在iphone7文本框输入超过一行的文字，无法左右滑动显示它的内容，安卓机上是可以的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午3:59
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"Q"<2511048530@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] 在 iphone7 版本11.3.1   Field 内容过多无法拖动内容 (#7052)





 
是指无法滑动页面？ 能否录个屏看下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

VID_20200827_160224.mp4 (23.73M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=78313265ff09b3c866be99f0453605190602535107530e5719520703051b035356091f075b060f1b50520551055252020d540655632137607d756d57530407060c03053a5200070406051c081302370b&t=exs_ftn_download&code=412ec676

**Comment by chenjiahan** [comment]
这个是系统下浏览器本身的交互，和组件无关喔，你可以用原生 input 标签试下

**Comment by TheKingAlwaysLuckey** [comment]
楼主怎么解决的 我也遇到这个问题了
