### ISSUE TITLE
[Feature Request] ActionSheet增加description插槽

### ISSUE THREAD

**Issue by lizhancheng** [youzan/vant#7055]
### 这个功能解决了什么问题
自定义description，有时候description里面需要用到类似于v-html的功能，展示包含html的字符串

### 描述您想要的解决方案
\<template #description\>\<div v-html="description" \/\>\</template\>

### 建议的API是什么样的
description类型为  string | slot

**Comment by chenjiahan** [comment]
已在 2.10.4 版本支持
