### ISSUE TITLE
[Bug Report] picker组件onChange，索引字段显示为undefined

### ISSUE THREAD

**Issue by fengyun2** [youzan/vant#7058]
### 设备 / 浏览器
win10/chrome 84.0.4147.125

### Vant 版本
3.0.0-alpha.0

### Vue 版本
3.0.0-rc.9

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/next/#/zh-CN/picker" target="_blank">https://vant-contrib.gitee.io/vant/next/#/zh-CN/picker</a>

### 描述问题
picker组件onChange，索引字段显示为undefined

![image](https://user-images.githubusercontent.com/8147202/91450071-7601bb80-e8ae-11ea-9d57-70fbdcc5298b.png)

**Comment by chenjiahan** [comment]
已经修复咯

**Comment by LIJUN-XU** [comment]
第几个版本修复啦？

**Comment by LIJUN-XU** [comment]
> 已经修复咯

第几个版本修复啦？3.0.0-beta.8 这个版本还是有这个问题的

**Comment by LIJUN-XU** [comment]
3.0.5也有这个问题
