### ISSUE TITLE
[Feature Request] van-area省市县选择

### ISSUE THREAD

**Issue by Hellosyikai** [youzan/vant#7059]
### 这个功能解决了什么问题
当前 使用 :columns-num="2" 时，直辖市比如北京，不能选择区显示的结果是北京市北京市

### 描述您想要的解决方案
希望使用 :columns-num="2" 时，直辖市比如北京，能选择北京市东城区

### 建议的API是什么样的
当我把area里边county_list属于北京市 区级别的内容 复制到 city_list时，滚动选择后会回到顶部，建议市区通过parent关联

**Comment by chenjiahan** [comment]
组件内部暂时没计划添加这样的特殊逻辑，你可以通过处理 areaList 源数据来实现这个效果
