### ISSUE TITLE
[Feature Request] 给tabbar增加before-change回调函数

### ISSUE THREAD

**Issue by cloydlau** [youzan/vant#7062]
### 这个功能解决了什么问题
可以异步切换 如果不满足条件还可以不予切换 主要原因是tab组件都有这个api tabbar却没有 不统一

### 描述您想要的解决方案
给tabbar增加before-change回调函数

### 建议的API是什么样的
before-change

**Comment by cloydlau** [comment]
目前的解决方案：阻止click事件冒泡

**Comment by chenjiahan** [comment]
已在 2.10.4 版本支持
