### ISSUE TITLE
[Feature Request] textarea 支持渲染 raw html

### ISSUE THREAD

**Issue by fengyun2** [youzan/vant#7064]
### 这个功能解决了什么问题

管理端备注等字段信息使用富文本编辑器录入数据，会拥有 `<p>`，`<b>`，`<div>` 等标签，回填到移动端 textarea 会导致现在html标签

### 描述您想要的解决方案

管理端备注等字段信息使用富文本编辑器录入数据，在移动端textarea能正确解析出 `<p>`，`<b>`，`<div>` 等标签

### 建议的API是什么样的

```js
<van-field
  v-model="message"
  rows="1"
  autosize
  label="留言"
  type="textarea"
  allow-html //  是否允许 textarea 内容中渲染 HTML
  placeholder="请输入留言"
/>
```

**Comment by chenjiahan** [comment]
暂无计划支持喔，可以用插槽自己做
