### ISSUE TITLE
vant 表单rules不是必填的问题

### ISSUE THREAD

**Issue by yoonasy** [youzan/vant#7067]
### 设备 / 浏览器
all

### Vant 版本
2.10.3

### Vue 版本
2.6.12

### 重现链接
<a href="http://xxx.com" target="_blank">http://xxx.com</a>

### 描述问题
```
<van-field
      v-if="config.see.mobile === 1"
      v-model="form.phone"
      name="手机号"
      label="手机号"
      placeholder="请输入手机号码"
      :required="config.required.phone"
      :rules="[
        { message: '请输入正确手机号码', pattern:/^1[3456789]\d{9}$/ },
      ]"
    />
```

`:required="config.required.phone"  `  
`required` 属性只改变了当前是否必填红色星星的状态，当为`false`不是必填项且没有输入内容时，目前还是会调用`rules`集中进行验证。

#### 当前方案：
目前解决方案是使用`validator`字段函数形式去判断为空情况，表单验证较多会比较繁琐要写多个`validator`去验证，表单是处于接口返回动态的设置的，可以设置是否必填以及是否显示。

#### 期望：
`required` 为`false`跳过`rules`字段中所有验证，并验证通过

**Comment by yoonasy** [comment]
![image](https://user-images.githubusercontent.com/24489180/91585286-ebc85e80-e964-11ea-9e2f-9c44fa9e7f89.png)
这样书写起来会更爽 更加便捷🤣

**Comment by chenjiahan** [comment]
目前 required 属性只是用于控制是否展示星号，而表单验证的 required 是由 rule 中的 required 字段控制的。

这样设计是为了把 UI 和逻辑分开，使用者可以根据自己的需求灵活选择
