### ISSUE TITLE
按照官方文档写show-action为什么会报错

### ISSUE THREAD

**Issue by wupuyi** [youzan/vant#707]
```html
<van-search
  v-model="value"
  show-action
  @search="onSearch"
>
  <div slot="action" @click="onSearch">搜索</div>
</van-search>
````

代码的show-action这么写会报错。

**Comment by wupuyi** [comment]
@chenjiahan 

vue.esm.js?caeb:591 [Vue warn]: Error in render: "TypeError: Cannot read property 'undefined' of undefined"

found in

---> <VanSearch>
       <Search> at src\components\Search\Search.vue
         <App> at src\App.vue
           <Root>

**Comment by chenjiahan** [comment]
@wupuyi 没能复现你的问题，早期版本中 Search 存在类似的问题，麻烦升级 vant 版本再试，

**Comment by wupuyi** [comment]
@chenjiahan 使用npm安装的vant，刚刚更新了一下试了，还是会出现这样的问题。我是按照文档中的方式三导入所有组件的。

**Comment by wupuyi** [comment]
vue版本 2.9.3
vant版本 0.12.14

**Comment by chenjiahan** [comment]
Vue 最新版本是 2.5.16 喔，还没到 2.9 版本

**Comment by wupuyi** [comment]
2.5.2，看错地方了= =

**Comment by chenjiahan** [comment]
再次试了下，还是没复现噢，能否提供一个 jsfiddle 链接呢
https://jsfiddle.net/dfarLdko/1/

**Comment by wupuyi** [comment]
jsfiddle我试过了，确实没问题，能够正常显示。
我是用vue-cli搭的，然后再进入的vant。如果添加show-action就报错。
[![我的截图](https://s1.ax1x.com/2018/03/19/9oWSeJ.png)](https://imgchr.com/i/9oWSeJ)

**Comment by wupuyi** [comment]
版本更新到1.0.0就可以用了，感谢

**Comment by chenjiahan** [comment]
好的~

**Comment by KaivOU** [comment]
@wupuyi @chenjiahan 我也更新到1.0.0了，但还是不行，时间选择器也是报这个错误，
![image](https://user-images.githubusercontent.com/36435545/37725041-ff246638-2d6c-11e8-8014-fe48b1fff526.png)

![image](https://user-images.githubusercontent.com/36435545/37725086-1cf6ed02-2d6d-11e8-8e27-2245bde25b8e.png)
![image](https://user-images.githubusercontent.com/36435545/37725159-4a49ab00-2d6d-11e8-8be9-aa57c0378bdb.png)

**Comment by wupuyi** [comment]
@KaivOU 我当时是把node_modules整个文件夹删了，重新npm install

**Comment by KaivOU** [comment]
@wupuyi @chenjiahan 谢啦哥们，果然要把整个node_modules删掉，我cnpm的

**Comment by wupuyi** [comment]
@KaivOU 同cnpm，哈哈。解决就好。
