### ISSUE TITLE
[Feature Request]省市区组件禁用问题

### ISSUE THREAD

**Issue by ZhouNick** [youzan/vant#7070]
不好意思,链接打不开,只能在这提了
![image](https://user-images.githubusercontent.com/22462099/91710757-5b358c80-ebb7-11ea-9042-71a6a9ca031e.png)
这个省市区组件没有禁用功能,回显的时候可以用到,比如查看详情是不能编辑的,建议加一个disabled属性

**Comment by chenjiahan** [comment]
可以的，后续加一个 readonly 属性来实现这个需求

**Comment by chenjiahan** [comment]
已在 2.10.5 版本支持 readonly 属性
