### ISSUE TITLE
van-list 组件loading一直是加载中状态，为什么我设置了loading=false还是处于加载中状态？我的html和body也没有设置overflow

### ISSUE THREAD

**Issue by isharryyy** [youzan/vant#7072]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
