### ISSUE TITLE
van-tabs在sticky模式下滚动到一定高度时会导致标题丢失

### ISSUE THREAD

**Issue by GaryZhang-Dev** [youzan/vant#7074]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

您好，当tabs在sticky模式下时，我发现offset-top超出一定高度会导致title消失
具体审查为<div class="van-sticky van-sticky--fixed" style="top: 2112px; transform: translate3d(0px, -347px, 0px);">
我使用的demo
<template>
<van-popup v-model="value" id="popup" :style="{ width: '100%', height:'100%' }" safe-area-inset-bottom @on-visible-change="onModalChange">
 <van-sticky :offset-top="offsetHeight">
         <van-nav-bar title="标题" id="nav">
                  <van-icon name="cross" slot="right" @click="cancel" />
         </van-nav-bar>
 </van-sticky>
                <van-tabs v-model="tabName"  :ellipsis="false" sticky @scroll="handleScroll" :offset-top="offsetHeight+offsetTab">
                    <van-tab v-for="(item,index) in items" :key="index" :name="item.estimateRecordId">
                        <template slot="title">
                            {{自定义标题}}
                            <van-icon name="delete" color="red" size="18" @click="" />
                        </template>
                    </van-tab>
                </van-tabs>
</van-popup>
</template>
method:{
handleScroll() {
                this.offsetTab = document.querySelector("#nav").offsetHeight;

                let scrollTop = document.querySelector("#popup").scrollTop;
                if (popup.scrollTop > this.offsetTab) {
                    this.offsetHeight = scrollTop;  // 获取元素距离顶部的高度
                } else {
                    this.offsetHeight = 0;
                }
                return { scrollTop: this.offsetHeight + this.offsetTab, isFixed: true }
        }
}

**Comment by GaryZhang-Dev** [comment]
版本号"vant": "^2.10.3"

**Comment by lintiansheng** [comment]
因为css样式问题；滚动导航的父盒子样式不能有overflow-y: auto;这个样式会导致滚动导航不生效

**Comment by GaryZhang-Dev** [comment]
换了一个方式解决：不使用粘性布局，使用的tabs内tab添加固定高度，overflow-y:auto实现粘性布局相同效果

**Comment by L1uFei** [comment]
1
