### ISSUE TITLE
[Feature Request] ImagePreview可以支持close-on-click-overlay和click-overlay吗？

### ISSUE THREAD

**Issue by 695648896** [youzan/vant#7075]
### 这个功能解决了什么问题
通过设置close-on-click-overlay为false，和监听click-overlay, 通过自己的方法来关闭。

### 描述您想要的解决方案
新增close-on-click-overlay和click-overlay

### 建议的API是什么样的
close-on-click-overlay
click-overlay

**Comment by chenjiahan** [comment]
ImagePreview 不是基于 Popup 实现的，所以这两个事件不太好加哈。可以试下 asyncClose 属性，效果类似
