### ISSUE TITLE
[Bug Report] List组件滚动异常

### ISSUE THREAD

**Issue by LemonAppleMo** [youzan/vant#7079]
### 设备 / 浏览器
Chrome

### Vant 版本
2.10.3

### Vue 版本
2.6.12

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-du5u4?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-du5u4?file=/src/App.vue</a>

### 描述问题
给List外层Div一个style（overflow-x: hideen; overflow-y:scroll），List将会一直加载，直到完成所有加载项才会停止。如果没有预设置list数据，List将不会执行onLoad函数。

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/list#zai-html-body-shang-she-zhi-overflow-hou-yi-zhi-chu-fa-jia-zai
