### ISSUE TITLE
checkbox, switch开关等能否通过css或者属性绑定设置尺寸

### ISSUE THREAD

**Issue by junk123321** [youzan/vant#708]
如题，谢谢

**Comment by chenjiahan** [comment]
直接通过覆盖 css 样式的方式修改尺寸即可

**Comment by junk123321** [comment]
switch开关要改的css地方有好几处：
.van-switch的width、height
.van-switch__node的width、height
还有其他地方还没找到
如果能通过van-switch的类似于font-size来修改就好了

**Comment by chenjiahan** [comment]
感谢反馈，我们会在后续支持 props 调整尺寸
