### ISSUE TITLE
Vant3的Grid组件样式不生效

### ISSUE THREAD

**Issue by micodecc** [youzan/vant#7085]
### 设备 / 浏览器
macbook/chrome latest 85.0.4183.83

### Vant 版本
3.0.0-alpha.3

### Vue 版本
3.0.0-rc.10

### 重现链接
无，采用构建工具

### 描述问题
所有工具均使用最新版构建
用vite创建项目，引入vant，并套用官网van-grid 简单例子，开发模式下样式正常，build后运行样式不生效

**Comment by M69W** [comment]
目前只找到 一个vue3 + vant3 + vite的 [临时解决设置](https://github.com/youzan/vant/issues/7035#issuecomment-689311465)

**Comment by micodecc** [comment]
@M69W 谢谢，不过目前我用的解决方案是这样的，先在根目录下建一个index.css，引入vant的css文件，再在main.js中引入这个index.css，就可以生效了，我找到了另一种解决方案所以就关闭了这个Issue，不过今天才看到你回的消息给的另一种解决方案，致谢！

**Comment by leewithyuan** [comment]
我觉得这个问题不应该被关闭，应该出一个解决方案！
