### ISSUE TITLE
van-image的Slots为default时的问题

### ISSUE THREAD

**Issue by qq277470897** [youzan/vant#7087]
`<van-image width="200" height="100" fit="contain" src="https://img.yzcdn.cn/vant/cat.jpeg">
            <template v-slot:default><div class="imgtitle">描述信息</div></template>
</van-image>`
如果图片是正确的，那么这个“描述信息”是在图片下方。如果图片地址是错误的，那么“描述信息”这个容器到了图片的底下，因为图片错误时，v-slot:error里的类的css是position的，不再占位，文字就顶上去了。
这个问题是故意这样实现的么？再就是v-slot:default这个东西，什么情况会用到？

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
