### ISSUE TITLE
Form 组件 scroll-to-error 滚动至错误表单属性无效

### ISSUE THREAD

**Issue by 841440416** [youzan/vant#7088]
设备 / 浏览器
chrome 64

Vant 版本
2.10.3

Vue 版本
2.6.11

重现链接
https://codesandbox.io/s/brave-mahavira-iz3so?file=/package.json

描述问题:
当表单长度超出屏幕高度，scroll-to-error属性设置为true的时候，点击提交按钮触发校验，当第一个表单校验不通过时页面不会滚动至错误项

**Comment by chenjiahan** [comment]
多个表单项的 name 不能是同一个值，否则每个 name 为 “用户名” 的选项都会触发一次滚动效果

**Comment by 841440416** [comment]
> 多个表单项的 name 不能是同一个值，否则每个 name 为 “用户名” 的表单项都会触发一次滚动效果

明白了。非常感谢

**Comment by 841440416** [comment]
> 多个表单项的 name 不能是同一个值，否则每个 name 为 “用户名” 的表单项都会触发一次滚动效果

是否form中每一项都要有name属性，并且值唯一此功能才能真确使用

**Comment by chenjiahan** [comment]
对的
