### ISSUE TITLE
在使用van-field type=digit时发现无法禁止输入负号

### ISSUE THREAD

**Issue by GaryZhang-Dev** [youzan/vant#7089]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

在使用van-field type=digit时发现无法禁止输入负号，但是根据文档注释显示type='digit'时是只能输入正整数的，这里是否有bug？

**Comment by chenjiahan** [comment]
已在 2.10.5 版本修复
