### ISSUE TITLE
[Feature Request] 日历组件的formatter函数可以手动触发么？

### ISSUE THREAD

**Issue by Michael-C-H** [youzan/vant#7090]
### 这个功能解决了什么问题
解决从后台异步获取数据后，能将当前显示区域的日历重新格式化一下

### 描述您想要的解决方案
提供可调用方法，从后台异步获取数据后，能将当前显示区域的日历重新格式化一下

### 建议的API是什么样的
formatterCurrent()

**Comment by chenjiahan** [comment]
formatter 不需要手动触发把，当数据变更时会自动触发的。

如果是 formatter 内部的逻辑发生了变更， 你可以传入一个新的 formatter 函数，这样也会触发重新计算

**Comment by Michael-C-H** [comment]
> formatter 不需要手动触发把，当数据变更时会自动触发的。
> 
> 如果是 formatter 内部的逻辑发生了变更， 你可以传入一个新的 formatter 函数，这样也会触发重新计算

我是在month-show事件中发起请求后台数据，然后在formatter中利用数据进行格式化；现状是我请求还没完成（异步），formatter就已经执行完了。后续必须得点击一下才会渲染；按照你的说法，我应该在请求成功结束后怎么重传formatter函数呢？
