### ISSUE TITLE
[Bug Report] form表单存在验证不通过的情况

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#7092]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.4

### Vue 版本
2.6.12

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-xz8rs" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-xz8rs</a>

### 描述问题
先填写第二个表单项，例如：10，然后填写第一个表单项，例如：10，表单验证失败。

**Comment by chenjiahan** [comment]
已在 2.10.5 版本修复
