### ISSUE TITLE
[Bug Report] 同时执行多个Toast.loading会导致无法关闭

### ISSUE THREAD

**Issue by baoanj** [youzan/vant#7093]
### 设备 / 浏览器
Chrome 84

### Vant 版本
2.10.4

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-0g27m" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-0g27m</a>

### 描述问题
https://github.com/youzan/vant/commit/a78a7b6aa89db2fa775d53391bcc4a74bb9756b7
此次提交的【queue = queue.filter((item) => isInDocument(item.$el));】这行代码会导致：同时执行多个Toast.loading时queue只会保留最后一个，因为此时元素还未真正存在于DOM中，这样前几个loading就被挂起在DOM无法关闭。

**Comment by chenjiahan** [comment]
已在 2.10.5 版本修复
