### ISSUE TITLE
[Feature Request] 日历组件禁用主动选中问题

### ISSUE THREAD

**Issue by baaaaazinga** [youzan/vant#7094]
### 这个功能解决了什么问题
当日历仅作为打卡功能展示时，用户无需进行日历的选择操作

### 描述您想要的解决方案
新增属性‘开启/禁止’点击选中的功能

### 建议的API是什么样的
:disabled

**Comment by chenjiahan** [comment]
已在 2.10.5 版本支持将 default-date 设置为 null
