### ISSUE TITLE
vant打包之后报错：Uncaught Error: Cannot find module "../../style/base.css"

### ISSUE THREAD

**Issue by xxuyang** [youzan/vant#7095]
在vue项目中全局引入或按需引入时，打包到生产环境时报错：Uncaught Error: Cannot find module "../../style/base.css"
vant安装版本为2.10.4

按需引入时报错位置在node_modules的checkbox-group中style/index.js——import '../../style/base.css';
把对checkbox-group的引用去除后，又在checkbox中style/index.js报同样错误——import '../../style/base.css';
最后尝试全局引入组件，结果也还是一样的报错——import '../../style/base.css';
没有百度到该问题的解决方法，请求解答一下谢谢~！

**Comment by xxuyang** [comment]
![image](https://user-images.githubusercontent.com/29146291/92221830-a65de100-eed0-11ea-835d-0f9ddba05df4.png)

**Comment by xxuyang** [comment]
![image](https://user-images.githubusercontent.com/29146291/92221858-b2e23980-eed0-11ea-851c-b1a392210475.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
