### ISSUE TITLE
[Bug Report] vant3.0的文档中Switch的代码示例有错误

### ISSUE THREAD

**Issue by JanzenZhang** [youzan/vant#7098]
### 设备 / 浏览器
Mac/Chrome

### Vant 版本
3.0.0-alpha.3

### Vue 版本
3.0.0-rc.10

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/next/#/zh-CN/switch" target="_blank">https://vant-contrib.gitee.io/vant/next/#/zh-CN/switch</a>

### 描述问题
Switch的异步控制代码<van-switch :model-value="checked" @update:model:value="onUpdateValue" />，其中@update:model:value错误，应该为@update:model-value

**Comment by chenjiahan** [comment]
感谢反馈，近期会更新下文档站点
