### ISSUE TITLE
为什么Collapse报错了

### ISSUE THREAD

**Issue by a851870** [youzan/vant#710]
提示 Cannot resolve dependency 'vant/lib/collapse'

加载了最新版的npm的vant包中lib目录页没找到collapse

**Comment by a851870** [comment]
还有cell 为什么没有点击事件

**Comment by chenjiahan** [comment]
1. Collapse 将在下个版本中加入，由于我们的失误提前把文档放出来了，Sorry
2. Cell 是有点击事件的，文档会在后续补齐

**Comment by chenjiahan** [comment]
已修复

**Comment by a851870** [comment]
谢谢! 我很喜欢vant

**Comment by chenjiahan** [comment]
谢谢你的支持 ^_^
