### ISSUE TITLE
[Bug Report] 在手机端使用van-dialog后，每次都跳到页面顶端

### ISSUE THREAD

**Issue by ymmagic** [youzan/vant#7111]
### 设备 / 浏览器
iphone11

### Vant 版本
2.10.4

### Vue 版本
3.0.0-rc.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-cqhiq?file=/public/index.html" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-cqhiq?file=/public/index.html</a>

### 描述问题
van-dialog 点击之后滚动条回到顶部,但是不我知道为啥用的你的这个模块后并没有出现回到顶部的效果

**Comment by chenjiahan** [comment]
试了下没问题，建议看下是不是其他因素导致的，或者把 lockScroll 属性禁用试试
