### ISSUE TITLE
[Feature Request] 如何支持 vant picker item 自定义样式？

### ISSUE THREAD

**Issue by ly525** [youzan/vant#7113]
### 这个功能解决了什么问题
支持 vant picker item 自定义className

### 描述您想要的解决方案
支持 className 配置

### 建议的API是什么样的
columns: [
{
   optionClassName
}

]

**Comment by chenjiahan** [comment]
Columns 有 className 选项的，可以再看下文档

**Comment by ly525** [comment]
> Columns 有 className 选项的，可以再看下文档

这个 className 是针对 columns的，在类型为 text的时候，就失效了

**Comment by chenjiahan** [comment]
失效是啥意思，能给个示例代码看下么

**Comment by kelvshi** [comment]
![image](https://github.com/youzan/vant/assets/10411251/1aa689f7-535d-4d0a-a821-968e31f381cb)
看了一下picker的源码，当默认是text的时候，直接把formattedColumns 重新赋值了，丢失了className属性，后面渲染的时候就失效了
![image](https://github.com/youzan/vant/assets/10411251/4ee7d225-6b5e-421e-890a-d520f2f0154c)
