### ISSUE TITLE
Badge 如何单独抽离使用

### ISSUE THREAD

**Issue by cyanwin** [youzan/vant#7118]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

version："vant": "^2.10.4"

想单独使用 Badge 但是都是在其他组件中绑定使用，有没有办法能单独使用

**Comment by chenjiahan** [comment]
后续会单独提供 Badge 组件，参见 https://github.com/youzan/vant/issues/6573
