### ISSUE TITLE
如何改变checkBox 选中状态van-checkbox--checked：background-color呢 已经做了样式覆盖,确未生效

### ISSUE THREAD

**Issue by VenusPP** [youzan/vant#712]
如题如题~~~

**Comment by chenjiahan** [comment]
我试了下是可以的，请确认下你的样式是否正确覆盖了

**Comment by VenusPP** [comment]
HTML

<div class="hello">
    <van-checkbox v-model="checked">Checkbox 1</van-checkbox>
  </div>


CSS

<style scoped>
(试图改变背景色为pink)
  .van-checkbox--checked {
    color: #fff;
    border-color: pink;
    background-color: pink;
  }
</style>

样式依旧为默认颜色

**Comment by VenusPP** [comment]
"vant": "^0.12.14",
"vue": "^2.5.2",

**Comment by VenusPP** [comment]
最后把此类样式放于vue APP.vue里加载成功。
不知还有其他方法吗？

**Comment by chenjiahan** [comment]
请注意 scoped 属性的使用会改变 class 名称，不清楚的话可以查询 Vue 官方文档

**Comment by VenusPP** [comment]
好的 感谢
