### ISSUE TITLE
[Bug Report] 日历组件在readonly状态下仍可操作问题

### ISSUE THREAD

**Issue by baaaaazinga** [youzan/vant#7120]
### 设备 / 浏览器
Chrome

### Vant 版本
2.10.5

### Vue 版本
2.6.12

### 重现链接
<a href="https://output.jsbin.com/rezatam" target="_blank">https://output.jsbin.com/rezatam</a>

### 描述问题
日历组件在readonly状态下点击默认选中的日期仍会取消日期的选中。

**Comment by chenjiahan** [comment]
multiple 模式下有问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.10.6 版本修复
