### ISSUE TITLE
[Bug Report] v-for 作用在van-cell上，scoped style没有作用到所有dom上

### ISSUE THREAD

**Issue by AngryChocobo** [youzan/vant#7121]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/ancient-snowflake-p99qo?file=/src/App.vue" target="_blank">https://codesandbox.io/s/ancient-snowflake-p99qo?file=/src/App.vue</a>

### 描述问题
v-for 循环渲染的van-cell，对van-cell绑定了class，style 是 scoped，但是渲染结果中某些cell的dom上没有data-xxx的属性，导致样式显示异常

**Comment by chenjiahan** [comment]
下个版本修复

**Comment by chenjiahan** [comment]
已在 2.10.6 版本修复
