### ISSUE TITLE
ImagePreview性能问题

### ISSUE THREAD

**Issue by elenva** [youzan/vant#7122]
### 设备 / 浏览器
华为X10等安卓手机

### Vant 版本
2.10.5

### Vue 版本
2.6.10

### 重现链接
<a href="https://gldpartner.keruyun.com/gateway-fronend/mobile.html#/commentH5?brandId=32314&shopId=810094302&tradeId=390505046679404544&userId=" target="_blank">https://gldpartner.keruyun.com/gateway-fronend/mobile.html#/commentH5?brandId=32314&shopId=810094302&tradeId=390505046679404544&userId=</a>

### 描述问题
ImagePreview组件在预览较多图时（9张）或者图片较大时候页面卡顿、不可滑动（安卓）

**Comment by chenjiahan** [comment]
1. 图片数量理论上不会影响性能，ImagePreview 默认做了延迟渲染
2. 图片较大的问题可以通过前端图片压缩来优化（通过 canvas 做一次压缩）

**Comment by elenva** [comment]
> 1. 图片数量理论上不会影响性能，ImagePreview 默认做了延迟渲染
> 2. 图片较大的问题可以通过前端图片压缩来优化（通过 canvas 做一次压缩）

实际开发过程中，使用canvas做过压缩处理。处理后的图片都不超过1M.
这个地址更能凸显问题
https://gldpartner.keruyun.com/gateway-fronend/mobile.html#/commentH5?brandId=32314&shopId=810094302&tradeId=390505046679404544&userId=1231111111111
可用手机实测

**Comment by chenjiahan** [comment]
用的官方的图片上传示例会有问题么

**Comment by elenva** [comment]
> 你这个链接确实很卡，是不是做了什么特殊逻辑？
> 
> 用的官方的图片上传示例会有问题么

已经找到原因：
object-fit: cover;时页面出现卡顿

解决方案：
transform: translate3d(0, 0, 0)；
或者设置其他属性

**Comment by chenjiahan** [comment]
图片预览默认设置的是 object-fit: contain;，你说的 object-fit: cover; 指的是 Uploader 的预览小图吗

**Comment by elenva** [comment]
> 图片预览默认设置的是 object-fit: contain;，你说的 object-fit: cover; 指的是 Uploader 的预览小图吗

不好意思没说清楚，是页面上使用了van-image组件。fit设置了cover；
我没有使用你们上传的fileList

**Comment by chenjiahan** [comment]
哦哦，明白

**Comment by elenva** [comment]
> 哦哦，明白
你可以测试一下，多图片使用object-fit: cover; 时候的性能

**Comment by chenjiahan** [comment]
好的，我有空测试下
