### ISSUE TITLE
[Bug Report] NoticeBar在多页应用下返回上一页会出现内容空白

### ISSUE THREAD

**Issue by ding-love-yu** [youzan/vant#7132]
### 设备 / 浏览器
IOS手机

### Vant 版本
2.10.5

### Vue 版本
2.6.12

### 重现链接
<a href="http://study.mikeding.cn/test.html" target="_blank">http://study.mikeding.cn/test.html</a>

### 描述问题
NoticeBar在多页应用下返回上一页会出现内容空白  点击新链接后按手机下方返回按钮即可重现！

**Comment by ding-love-yu** [comment]
> 😂 试了试 我这儿没啥问题

要用真机测试才行哦，我发现了问题所在是真机上IOS （微信内置浏览器和safari）返回上一页页面不会刷新所致，组件的mounted钩子函数都不会再次触发 而安卓和浏览器都会刷新页面且会触发生命周期函数的

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.10.7 版本修复

**Comment by HellsingMatt** [comment]
在桌面 Chrome 环境也出现了呢，Tabbar 标签栏切换到另一页再回来，NoticeBar 文字就不见了
