### ISSUE TITLE
[Bug Report] magepreview 修改 class 为 van-image-preview 的高度，图片放大无法上下移动

### ISSUE THREAD

**Issue by spriteSunnyChen** [youzan/vant#7133]
### 设备 / 浏览器
微信内置浏览器

### Vant 版本
2.4.1

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/image-preview" target="_blank">https://youzan.github.io/vant/#/zh-CN/image-preview</a>

### 描述问题
Imagepreview 修改 class 为 van-image-preview 的高度，预览图片时，手势放大图片 或者双击放大图片，图片可左右移动，但是无法上下移动

**Comment by chenjiahan** [comment]
请提供一下复现问题的 codesandbox 链接

https://codesandbox.io/s/m5v3f

**Comment by spriteSunnyChen** [comment]
https://37jd2.csb.app/

**Comment by chenjiahan** [comment]
这个用法有点神奇。。下个版本会兼容下

**Comment by chenjiahan** [comment]
已在 2.10.7 版本修复
