### ISSUE TITLE
[Bug Report] van-tabs粘性布局设置了offset-top，点击tab项，页面滚动条会滚动到顶部，tabs不再吸附在顶部

### ISSUE THREAD

**Issue by shenghuitian** [youzan/vant#7135]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.10.2

### Vue 版本
2.6.11

### 复现链接
https://mzqvl.csb.app/

### 描述问题
van-tabs粘性布局设置了offset-top后，点击tab项，标签页切换时，页面滚动条会滚动到顶部，tabs不再吸附在顶部

**Comment by chenjiahan** [comment]
请提供一下复现问题的 codesandbox 链接

https://codesandbox.io/s/m5v3f

**Comment by shenghuitian** [comment]
复现链接
https://mzqvl.csb.app/

**Comment by chenjiahan** [comment]
目前版本里传入带单位的 offsetTop 会有问题，可以直接传入 50，是正常的

下个版本会修复此问题

**Comment by chenjiahan** [comment]
已在 2.10.7 版本修复
