### ISSUE TITLE
[Feature Request] sku样式

### ISSUE THREAD

**Issue by guoyuexu** [youzan/vant#7137]
### 这个功能解决了什么问题
能使sku这个组件更通用，现在固定的样式限制了太多。

### 描述您想要的解决方案
sku可以修改样式吗？比如sku我只想要显示sku选项和加减，加减的图片也能替换，sku选中也能改变的那种

### 建议的API是什么样的
sku可以修改样式吗？比如sku我只想要显示sku选项和加减，加减的图片也能替换，sku选中也能改变的那种

**Comment by chenjiahan** [comment]
可以通过插槽来实现的一些样式定制
