### ISSUE TITLE
cdn 方式引入vant ，我在使用滑动单元格，左边的渲染出来了，右边没有渲染出来。

### ISSUE THREAD

**Issue by shaxus** [youzan/vant#7138]
![image](https://user-images.githubusercontent.com/37354089/92477753-bbf64200-f213-11ea-9444-6bfce4a3bd28.png)
![image](https://user-images.githubusercontent.com/37354089/92477803-cf091200-f213-11ea-8ba9-a407754ba11c.png)
查看dom结构，
![image](https://user-images.githubusercontent.com/37354089/92477851-e5af6900-f213-11ea-87c6-e41982a28bfa.png)
项目中
![image](https://user-images.githubusercontent.com/37354089/92477908-f6f87580-f213-11ea-9bce-0e96aeea0cfd.png)
，

**Comment by shaxus** [comment]
是不是缺少依懒项

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/quickstart#zai-html-zhong-wu-fa-zheng-que-xuan-ran-zu-jian
