### ISSUE TITLE
vant 语言国际化这块有详细的文档吗

### ISSUE THREAD

**Issue by 18716752349** [youzan/vant#7139]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/locale
