### ISSUE TITLE
[Bug Report] van-picker在线文档实例代码错误

### ISSUE THREAD

**Issue by DwArFeng** [youzan/vant#7141]
### 设备 / 浏览器
firefox

### Vant 版本
3.0.0-alpha.4

### Vue 版本
3.0.0-rc.10

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/next/#/zh-CN/picker" target="_blank">https://vant-contrib.gitee.io/vant/next/#/zh-CN/picker</a>

### 描述问题
搭配弹出层使用示例代码中

```
<van-popup v-model="showPicker" round position="bottom">
  <van-picker
    :columns="columns"
    @cancel="showPicker = false"
    @confirm="onConfirm"
  />
</van-popup>
```

 v-model="showPicker" 语句错误，应该为 v-model:show="showPicker" 或者 :show="showPicker"

**Comment by chenjiahan** [comment]
感谢反馈，文档已修正，后续会更新下站点
