### ISSUE TITLE
Vant 设计规范 3.0 发布 🎈🎈🎈

### ISSUE THREAD

**Issue by chenjiahan** [youzan/vant#7147]
经过设计团队的不懈努力，Vant 设计规范 3.0 终于出炉了~

来看看我们的规范都有啥：

### 色彩规范

![](https://img.yzcdn.cn/vant/color_202009101415.png)

### 字体规范

![](https://img.yzcdn.cn/vant/words_202009101415.png)

### 组件规范

![](https://img.yzcdn.cn/vant/tab_202009101415.png)

### 彩蛋🥚

除了现有的组件外，设计稿中还“剧透”了一下我们即将发布的新组件：

#### Popover 气泡弹出框

![](https://img.yzcdn.cn/vant/popover_202009101415.png)

#### Cascader 级联选择器

![](https://img.yzcdn.cn/vant/cascader_202009101415.png)

### 下载地址

更详细的内容可在 Sketch 文件里查看。

- [Vant 3.0 设计稿](https://github.com/youzan/vant/blob/dev/docs/assets/design.sketch?raw=true)
- [Vant 图标库](https://github.com/youzan/vant-icons/blob/master/assets/icons.sketch?raw=true)
- [Vant Axure 元件库](https://b.yzcdn.cn/vant/vant-axure-20200905.zip)，由社区的 [@axure-tczy](https://github.com/axure-tczy) 同学贡献。

**Comment by CondiGao** [comment]
up

**Comment by workwsl** [comment]
up

**Comment by Mikasa33** [comment]
👍

**Comment by Bestbbb** [comment]
顶起

**Comment by kooriookami** [comment]
哦吼 太棒了

**Comment by kooriookami** [comment]
字体的话建议加一个'miui'（小米兰亭），不然tag标签可能会不居中

**Comment by tangjian1891** [comment]
Popover 终于要来了。

**Comment by chenjiahan** [comment]
> 字体的话建议加一个'miui'（小米兰亭），不然tag标签可能会不居中

确实是这样，我们补充一下

**Comment by zlfeeling** [comment]
Popover比较期待

**Comment by lihaotian0607** [comment]
3.0是rem还是px???

**Comment by chenjiahan** [comment]
默认 px

**Comment by yuxiaolei1989** [comment]
太及时了

**Comment by towry** [comment]
❓ 组件库为啥要给 body 设置字体？？有什么好的理由吗。这要使用者要多折腾一下有啥用。

**Comment by chenjiahan** [comment]
内置字体是为了使组件在默认情况下能有良好的视觉体验，如果需要自定义字体，简单覆盖一下就好咯

**Comment by towry** [comment]
建议通过 class 来实现。

**Comment by chenjiahan** [comment]
没有计划调整。

**Comment by hezhongfeng** [comment]
支持

**Comment by hezongtan** [comment]
大力支持！！！如果说能增加一个苹方的字体库应该效果会更好！

**Comment by hezongtan** [comment]
大力支持

**Comment by luichooy** [comment]
新的规范是 vant3.0+实现还是  2.0 也会修改

**Comment by chenjiahan** [comment]
@luichooy 都会修改

**Comment by makejun168** [comment]
效率拉满，有赞团队牛的

**Comment by freetwh** [comment]
感谢分享呢

**Comment by akangwu** [comment]
求问Sketch的设计稿有计划出一版吗

**Comment by akangwu** [comment]
![image](https://user-images.githubusercontent.com/43903377/99142756-1b008900-2693-11eb-917b-d5aeadfa073f.png)
sketch的设计稿这种显示是不是不正常呀？
没有VantUI官网的input、Toast、Dialog、Filed这写组件

**Comment by akangwu** [comment]
> ![image](https://user-images.githubusercontent.com/43903377/99142756-1b008900-2693-11eb-917b-d5aeadfa073f.png)
> sketch的设计稿这种显示是不是不正常呀？
> 没有VantUI官网的input、Toast、Dialog、Filed这写组件

使用Ant的组件库是正常的。同时icons我这里也没有显示。官方大大可以回答一下吗

**Comment by qianxiaocang** [comment]
404 ?

**Comment by chenjiahan** [comment]
@qianxiaocang 链接有更新，请访问 https://github.com/youzan/vant/blob/2.x/docs/assets/design.sketch?raw=true
