### ISSUE TITLE
[Feature Request] 自定义sku-stepper插槽时，触发加减的方法是什么

### ISSUE THREAD

**Issue by guoyuexu** [youzan/vant#7148]
### 这个功能解决了什么问题
自定义sku-stepper插槽时，开发者能知道触发加减的方法

### 描述您想要的解决方案
在提供了sku-stepper插槽时，提供开发文档说明出发加减法的方法，让开发者可以灵活运用。
不止是这个插槽的使用，其他可以用通过插槽定制的，开发者不知道出发的方法，还是不能更高效的复用。

### 建议的API是什么样的
比如sku购物车的插槽，添加购物车的触发方法就是“skuEventBus.$emit('sku:buy')”；
那加减的触发方法呢？

**Comment by chenjiahan** [comment]
可以通过 `sku:numChange` 来触发。

```js
skuEventBus.$emit('sku:numChange', value);
```

Sku 的接口较为复杂，欢迎提 PR 帮我们补充文档
