### ISSUE TITLE
vant field number iOS不可以输入负数，只能输入正数或者小数

### ISSUE THREAD

**Issue by hyacinth-luck** [youzan/vant#7149]
vue项目

vant版本：2.9.1

设备：iOS11pro

复现demo：官网demo输入支持小数的那个可以复现

**Comment by chenjiahan** [comment]
键盘是通过 inputmode 属性设置的，在 iOS 上确实不会显示减号，如果需要输入负数，可以使用 text 类型哈

![image](https://user-images.githubusercontent.com/7237365/92981423-4c5eac00-f4cc-11ea-9a6a-eb7284a6e39e.png)
