### ISSUE TITLE
请问AddressEdit 地址编辑 里如何显示删除操作呢？

### ISSUE THREAD

**Issue by VenusPP** [youzan/vant#715]
api中有delete操作但页面视图中却未发现delete按钮

**Comment by chenjiahan** [comment]
现在的逻辑是判断地址数据中是否有 `id` 字段来展示删除按钮的，考虑到这种做法不够通用，我们会在下个版本中添加 `show-delete` 属性来控制删除按钮的展示

**Comment by chenjiahan** [comment]
已在 1.0.0 版本中添加 `show-delete` 属性
