### ISSUE TITLE
[Bug Report] form表单 v-if会出现渲染重复的问题

### ISSUE THREAD

**Issue by liuyueqi18** [youzan/vant#7156]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.10.6

### Vue 版本
2.6.12

### 重现链接
<a href="https://codepen.io/liuyueqi18/pen/OJNveEj" target="_blank">https://codepen.io/liuyueqi18/pen/OJNveEj</a>

### 描述问题
1.表单中有一个switch开关 如果开启 某些字段需要填写；如果关闭 则不需要填写
2.我用v-if来处理field的显示与隐藏 
3.页面渲染switch开启的时候会正常显示
4.swicth开关一次以后就会特别诡异
5.会出现某个field出现两次的情况

**Comment by liuyueqi18** [comment]
手动在field加入了key 就可以解决了 但是终究还是个bug

**Comment by chenjiahan** [comment]
这个不是 Field 的 bug，属于 Vue 本身的 vnode 渲染机制问题，解决方法就是添加 key

**Comment by viulu5824** [comment]
> 这个不是 Field 的 bug，属于 Vue 本身的 vnode 渲染机制问题，解决方法就是添加 key

field本身不是有name属性吗，Field内部不会默认应用name做key吗；这样用户每一个Field都要多加一个key，不如Field内部用唯一的name属性当key
