### ISSUE TITLE
uploader组件在部分手机选择截屏的png文件后，在组件中显示数字名称的非图片文件

### ISSUE THREAD

**Issue by lilinpu221** [youzan/vant#7157]
vant版本：2.10.6
代码片段：
```
<van-row>
         <van-uploader
            v-model="advise.pic"
            multiple
            :max-count="3"
            :max-size="5000 * 1024"
            :before-read="beforeRead"
            @oversize="onOversize" />
</van-row>
```
点击打开
![image](https://user-images.githubusercontent.com/3397864/92843125-fa0f8380-f416-11ea-95ae-0cf96a8d8e69.png)
上传后显示数字
![image](https://user-images.githubusercontent.com/3397864/92843163-085d9f80-f417-11ea-925c-70a6b1e2d9f2.png)
实际图片
![image](https://user-images.githubusercontent.com/3397864/92843404-4955b400-f417-11ea-9873-2a5c4d6aacd6.png)
手机型号
![image](https://user-images.githubusercontent.com/3397864/92843524-6b4f3680-f417-11ea-919f-4fe85b05e549.png)

**Comment by chenjiahan** [comment]
可以在 onAfterRead 里把 file.type 输出看下是什么类型，估计是一些特殊类型的图片无法被识别。

手动设置一下 `isImage` 字段可以避免这个问题

![image](https://user-images.githubusercontent.com/7237365/92981637-559c4880-f4cd-11ea-8632-8dc893f78e85.png)
