### ISSUE TITLE
Form field rules 验证

### ISSUE THREAD

**Issue by z050301402** [youzan/vant#7158]
`<van-form @submit="onSubmit">

      <van-field
        v-model="tel"
        :rules="[
          { pattern: /^1[3456789]\d{9}$/, message: '手机号码格式错误！' }
        ]"
        type="tel"
        label="联系方式"
        placeholder="手机号码"
        clearable
      />
      <div style="margin: 16px;">
        <van-button round block type="info" native-type="submit">
          提交
        </van-button>
      </div>
    </van-form>
`
rules 我没加required 必填项  我不输入值提交form表单 会提示 手机号码格式错误 验证 
应该是没输入值就不去验证
输入了值才会去验证吧
版本"vant": "^2.10.6",

**Comment by chenjiahan** [comment]
不管是否输入，都会通过 pattern 进行校验

**Comment by rockey2020** [comment]
@chenjiahan validator也会校验 这样逻辑是否不太对   个人觉得required就应该具有控制校验的唯一性  但是现在声明在这里却没有起到对应的效果

**Comment by rockey2020** [comment]
我的版本是 "vant": "^3.0.16",

**Comment by chenjiahan** [comment]
required 并不控制是否校验，required 本身只提供一个必填项的校验能力

**Comment by zettle** [comment]
这点的确不方便，想着用户输入了就用正则校验，没有输入内容就校验，不为空才校验

**Comment by zettle** [comment]
> required 并不控制是否校验，required 本身只提供一个必填项的校验能力

这个的确不太方便，本意是想允许为空，用户没有输入内容是允许，输入内容就要校验正则

**Comment by lizy-CZ** [comment]
> @chenjiahan validator也会校验 这样逻辑是否不太对 个人觉得required就应该具有控制校验的唯一性 但是现在声明在这里却没有起到对应的效果

你是对的，required 若为 false，值为空的情况下 pattern 这些通通都不需要校验才是符合逻辑
