### ISSUE TITLE
[Feature Request] Uploader 文件上传组件希望增加图片压缩和水印功能

### ISSUE THREAD

**Issue by Mikerui** [youzan/vant#7160]
### 这个功能解决了什么问题
移动端上面选择的图片太大，解决了服务器的资源占用

### 描述您想要的解决方案
可以自定义水印，和压缩比列

### 建议的API是什么样的
watermarkText:'自定义水印'
compression: 0.9  //压缩比例 0 - 1

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5032
