### ISSUE TITLE
[Feature Request] Sku 商品规格建议给每个sku值设置custom-stepper-config

### ISSUE THREAD

**Issue by ctfwren** [youzan/vant#7161]
### 这个功能解决了什么问题
目前custom-stepper-config是给 Sku整个组建,设置  步进器 设置参数.这样单独设置某个sku的步进就比较麻烦了
比如蓝色sku最小起订量是20,红色sku最小起订量是30,就没办法设定了

### 描述您想要的解决方案
能否把custom-stepper-config参数设置在所有 sku 的组合列表里

### 建议的API是什么样的
把custom-stepper-config参数设置在所有 sku 的组合列表里

**Comment by chenjiahan** [comment]
暂无计划支持喔，欢迎提 PR
