### ISSUE TITLE
[Bug Report] body通过css选择模拟横屏后，picker的交互变得难用，不能正常上下滚动

### ISSUE THREAD

**Issue by steady-join** [youzan/vant#7163]
### 设备 / 浏览器
ios 、 chrome等等

### Vant 版本
2.10.6

### Vue 版本
3.0.0-rc.10

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/picker#ding-bu-lan" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/picker#ding-bu-lan</a>

### 描述问题
body通过css选择模拟横屏后，picker的交互变得难用，不能正常上下滚动。希望可以上下滚动

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

**Comment by steady-join** [comment]
@chenjiahan  已提供demo，请问有什么办法可以解决吗

**Comment by steady-join** [comment]
https://codesandbox.io/s/vant-issue-moban-forked-w1p3l?file=/src/App.vue
@chenjiahan

**Comment by chenjiahan** [comment]
你这种写法没法兼容。。

你只是通过 css 在视觉上旋转了组件，组件内部判断的 touch 坐标还是按正常的坐标系来的，所以拖拽的方向还是上下而不是左右。

**Comment by steady-join** [comment]
这种场景虽然少，但是也会遇见吧，比如app内嵌h5没有权限对横竖屏进行操作，就只能模拟横竖屏了，是不是应该考虑一下呢

**Comment by chenjiahan** [comment]
不会考虑喔。场景过于特殊，而且适配成本不低
