### ISSUE TITLE
[Bug Report] vant-tabs标签栏滚动，若内容过多，切换后的页面位置与前一页面同步

### ISSUE THREAD

**Issue by muxu85** [youzan/vant#7164]
### 设备 / 浏览器
Google、微信

### Vant 版本
2.10.6

### Vue 版本
3.0.0-rc.10

### 重现链接
<a href="https://m5v3f.csb.app/" target="_blank">https://m5v3f.csb.app/</a>

### 描述问题
vant-tabs，两个tab，若两者内容都很多，且在其中一个页面的内容中进行点击跳转到另一页面，切换后，之后的页面位置与前一页面同步，切换后的页面怎样不同步位置（怎样能够从头开始显示内容，而不是从中间显示）

**Comment by chenjiahan** [comment]
可以通过 `window.scrollTo` 方法自行控制页面的滚动条位置

**Comment by muxu85** [comment]
好的，谢谢
