### ISSUE TITLE
[Feature Request] validate-trigger能否增加一个onSubmit的触发方式

### ISSUE THREAD

**Issue by mirari** [youzan/vant#7168]
### 这个功能解决了什么问题
希望表单项的校验在onChange和onBlur的时候都不触发，只有最终表单提交时才校验

### 描述您想要的解决方案
validate-trigger增加一个onSubmit配置项

### 建议的API是什么样的
validate-trigger增加一个onSubmit配置项

**Comment by chenjiahan** [comment]
当前版本就支持的，可以直接用喔

后续会在文档里补充下

**Comment by H402861965** [comment]
> 当前版本就支持的，可以直接用喔
> 
> 周末会在文档里补充下

![image](https://user-images.githubusercontent.com/31874808/145766279-f2def595-0f71-4c18-bbd3-e781493dd9f2.png)
这样写 无效 新建数组还是会自动检查
