### ISSUE TITLE
[Bug Report] van-tabs加了sticky属性用浏览器的前进后退来跳转路由会报错，不加sticky属性是没有问题的

### ISSUE THREAD

**Issue by mazixiao** [youzan/vant#7169]
### 设备 / 浏览器
谷歌

### Vant 版本
3.0.0-alpha.4

### Vue 版本
3.0.0-rc.10

### 重现链接
<a href="https://github.com/mazixiao/vue-cli3-test" target="_blank">https://github.com/mazixiao/vue-cli3-test</a>

### 描述问题
van-tabs加了sticky属性用浏览器的前进后退来跳转路由会报错，不加sticky属性是没有问题的

报错1
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Unhandled error during execution of unmounted hook
at <VanSticky container= <div class=​"van-tabs van-tabs--line" modelvalue=​"0">​…​​ offsetTop=0 onScroll=fn >
at
at <Home onVnodeMounted=fn onVnodeUnmounted=fn ref=Ref< Proxy {getCode: ƒ, commit: ƒ, …} > >
at
at

报错2
Uncaught (in promise) TypeError: Failed to execute 'unobserve' on 'IntersectionObserver': parameter 1 is not of type 'Element'.

**Comment by chenjiahan** [comment]
已在 3.0.0-alpha.5 版本修复

**Comment by mazixiao** [comment]
收到，辛苦了，谢谢您。
