### ISSUE TITLE
在使用vant时,首次加载页面时组件尺寸大小正常,再次刷新后组件尺寸缩小

### ISSUE THREAD

**Issue by VenusPP** [youzan/vant#717]
"vant": "^0.12.14",
 "vue": "^2.4.2",
"webpack": "^2.6.1",

**Comment by chenjiahan** [comment]
@VenusPP 不是很理解这个问题，能否提供更多的信息或者截图

**Comment by VenusPP** [comment]
首次加载时组件大小正常
![image](https://user-images.githubusercontent.com/28476594/37575294-65682c3a-2b61-11e8-9fc3-d50a2791e903.png)

页面刷新后组件尺寸缩小
![Uploading image.png…]()

**Comment by VenusPP** [comment]
首次加载时组件尺寸
![image](https://user-images.githubusercontent.com/28476594/37575356-aff9e1f8-2b61-11e8-8dd9-cf97baf44852.png)

刷新页面时组件尺寸发生改变
![image](https://user-images.githubusercontent.com/28476594/37575375-c743d03a-2b61-11e8-9a3f-e07ac03fb557.png)

"vant": "^0.12.14",
"vue": "^2.4.2",
"webpack": "^2.6.1",
项目中使用了sass 和淘宝flexible.js

**Comment by chenjiahan** [comment]
@VenusPP 这个问题和 Vant 无关，建议你了解一下 flexible 的原理
