### ISSUE TITLE
[Bug Report] 日历bug，滑动日历至两个月份的交界点时日期title和日历会一直抖动

### ISSUE THREAD

**Issue by xiang1128** [youzan/vant#7170]
### 设备 / 浏览器
红米K30 pro/UC浏览器13.1.0.1090，iphone 6/7/8 plus

### Vant 版本
2.10.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://gitee.com/Mango28/vant-demo.git" target="_blank">https://gitee.com/Mango28/vant-demo.git</a>

### 描述问题
项目中引入amfe-flexible后滑动日历至两个月份的交界处时日历和日历title会一直抖动，日历title会一直变化月份，需要滑出两个月份交界处才会恢复正常
我专门用手机录屏了重现的bug

**Comment by tuborhaung** [comment]
问题解决了吗，我这边也遇到这个问题

**Comment by 5265liu** [comment]
metoo

**Comment by xiang1128** [comment]
> 问题解决了吗，我这边也遇到这个问题

还没有解决

**Comment by chenjiahan** [comment]
下个版本修复

**Comment by chenjiahan** [comment]
已在 2.10.7 版本修复

**Comment by 5265liu** [comment]
我用的是适配vue3的vant ,修复了吗

**Comment by chenjiahan** [comment]
还没
