### ISSUE TITLE
[Bug Report] 3.0文档错误

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#7172]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0-alpha.4

### Vue 版本
3.0.0-rc.10

### 重现链接
无

### 描述问题
dialog组件文档 组件调用

```jsx
<van-dialog v-model="show" title="标题" show-cancel-button>
```

应该是 `v-model:show`吧

**Comment by chenjiahan** [comment]
感谢反馈，文档已修正

**Comment by NullYing** [comment]
eslint校验不过，触发vue/no-v-model-argument规则

**Comment by chenjiahan** [comment]
@NullYing 升级 eslint-plugin-vue 7.0

**Comment by NullYing** [comment]
> @NullYing 升级 eslint-plugin-vue 7.0

版本是
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.1.0",

**Comment by chenjiahan** [comment]
确认下你继承的是 vue3 的校验规则，而不是 vue2
