### ISSUE TITLE
Calendar 日历title slot 放置单选框选择,点击任意单选框不会立即变化,再选择日历单选框才发生变化

### ISSUE THREAD

**Issue by LKF123LKF** [youzan/vant#7177]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
