### ISSUE TITLE
[Bug Report] 日历选择时间范围后，开始时间和结束时间如何选择同一天 

### ISSUE THREAD

**Issue by yexiaodong** [youzan/vant#7178]
### 设备 / 浏览器
Android

### Vant 版本
2.10.5

### Vue 版本
2.6.12

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/calendar" target="_blank">https://youzan.github.io/vant/#/zh-CN/calendar</a>

### 描述问题
希望日历的时间范围的开始时间和结束时间可以是统一天

**Comment by chenjiahan** [comment]
设置 allow-same-day 属性即可
