### ISSUE TITLE
[Bug Report] toast 自定义class类不起作用

### ISSUE THREAD

**Issue by jiahui336** [youzan/vant#7179]
### 设备 / 浏览器
ios

### Vant 版本
3.0.0-alpha.5

### Vue 版本
3.0.0-rc.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/toast" target="_blank">https://youzan.github.io/vant/#/zh-CN/toast</a>

### 描述问题
 this.$toast({
              message: "回答正确",
              duration: 0,
              icon: "checked",
              className: "aaaaa",
            }); 不起作用

**Comment by chenjiahan** [comment]
试了下没问题，建议你再检查下，或者提供下复现问题的 codesandbox 链接
