### ISSUE TITLE
NoticeBar 通知栏 不适配ios14系统，h5页面，滚动栏只滚动一遍，不循环滚动了，

### ISSUE THREAD

**Issue by zhufanayi14** [youzan/vant#7182]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by leenannan** [comment]
解决了吗请问

**Comment by tzy19920902** [comment]
刚也遇到这个问题，在ios中动画滚动一次后文字就消失了。我的解决方案是给noticebar组件加上一个key，replay事件中把key的值+1，这样vue会重新渲染这个组件，达到文字继续滚动显示的效果，在ios14中测试后有效，其他ios版本未验证。

**Comment by dzlkuboy** [comment]
> 刚也遇到这个问题，在ios中动画滚动一次后文字就消失了。我的解决方案是给noticebar组件加上一个key，replay事件中把key的值+1，这样vue会重新渲染这个组件，达到文字继续滚动显示的效果，在ios14中测试后有效，其他ios版本未验证。

但是这样会出现闪一下的情况

**Comment by chenjiahan** [comment]
已经在最新版兼容了
