### ISSUE TITLE
van-grid-item相关问题

### ISSUE THREAD

**Issue by bhwebxu** [youzan/vant#7185]
1，提issue规范链接无法访问
2，提issue规范链接手机端不好操作
3，grid-item中的icon无法使用图片相对路径，但在issue提问中，看到有人使用，建议完善文档，如何使用图片篇章
4，grid-item中的icon也无法使用自定义font，经查issue有人问，回答是用插槽处理，怎么个处理也没有在文档中有篇幅介绍，建议完善到文档，首先值得肯定，这ui很好，但对于新手这个很烂，文档很烂

我目前关心的问题，第四第五点怎么处理，能否提供一个简单实际，谢谢

**Comment by chenjiahan** [comment]
图片相对路径：https://youzan.github.io/vant/#/zh-CN/image#ru-he-yin-yong-ben-di-tu-pian

插槽：

```html
<van-grid-item text="文字">
  <template #icon>
    <van-icon name="success" />
  </template>
</van-grid-item>
```
