### ISSUE TITLE
[Bug Report] 依赖自相矛盾了导致文档无法预览效果

### ISSUE THREAD

**Issue by tendey** [youzan/vant#7186]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.10.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/tendey/pen/WNwyWjJ" target="_blank">https://codepen.io/tendey/pen/WNwyWjJ</a>

### 描述问题
我checkout开发版源代码下来，下载依赖的时候有警告。第一条和第二条警告内容不是自相矛盾吗
npm WARN vue-jest@4.0.0-beta.2 requires a peer of jest@^24.x but none is installed. You must install peer dependencies yourself.
npm WARN ts-jest@23.10.5 requires a peer of jest@>=22 <24 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by chenjiahan** [comment]
这个 jest 版本冲突可以忽略，不影响文档预览
