### ISSUE TITLE
[Bug Report] NoticeBar 通知栏,ios14系统h5页面，通知栏滚动，只滚动了一遍，

### ISSUE THREAD

**Issue by zhufanayi14** [youzan/vant#7187]
### 设备 / 浏览器
iphone xsmax ios14 ，safari

### Vant 版本
3.0.0-alpha.5

### Vue 版本
3.0.0-rc.10

### 重现链接
<a href="http://www.dengdaideche.com" target="_blank">http://www.dengdaideche.com</a>

### 描述问题
ios14系统的h5页面，通知栏允许滚动，只滚动了一遍，后面没有循环滚动，

**Comment by chenjiahan** [comment]
目前 iOS 14 还是预览版，可以等推送正式版了再试下

**Comment by zhufanayi14** [comment]
ios14已经推送正式版了，看过了，这个情况还是有的，

**Comment by chenjiahan** [comment]
看了下应该是 safari 的 bug，暂时没发现兼容方法，等苹果修复吧

**Comment by zenonux** [comment]
同样的问题，微信浏览器也一样

**Comment by talenHuang** [comment]
等待苹果修复中………… @chenjiahan 能不能告知下是什么原因引起的这个问题？

**Comment by chenjiahan** [comment]
浏览器没正确触发 transition

**Comment by hyx0217** [comment]
一样的问题，看来是ios14的坑

**Comment by wangmingshuo-wms** [comment]
还没有修复么?  有什么替代的解决方案?

**Comment by shit-hao** [comment]
同

**Comment by leenannan** [comment]
有什么方案可以解决了吗

**Comment by bolechen** [comment]
原来是 iOS 14 的锅……

**Comment by bolechen** [comment]
mac 下 Safari 开发模式下响应式设计调试下，也可以重现此问题，Safari Version 14.0 (15610.1.28.1.9, 15610)

**Comment by chenjiahan** [comment]
已在 2.10.13 版本兼容此问题

**Comment by francyfrees** [comment]
@chenjiahan 好了😁
