### ISSUE TITLE
[Bug Report] IndexBar 索引列表组件在安卓手机上点击计算activeAnchorIndex会不准确

### ISSUE THREAD

**Issue by wxpeanut** [youzan/vant#7195]
### 设备 / 浏览器
安卓手机

### Vant 版本
2.6.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/wxpeanut/pen/xxVaqde?editors=1010" target="_blank">https://codepen.io/wxpeanut/pen/xxVaqde?editors=1010</a>

### 描述问题
在安卓手机上“点击”右侧快捷入口时，dom滚动后，计算出来的activeAnchorIndex和点击的不一致。

**Comment by chenjiahan** [comment]
麻烦提供完整的复现 demo
