### ISSUE TITLE
[Bug Report] 日历bug，日历在重载页面后首次打开日历视图无法定位当前日期

### ISSUE THREAD

**Issue by xiang1128** [youzan/vant#7198]
### 设备 / 浏览器
红米K30 pro/UC浏览器13.1.0.1090，iphone 6/7/8 plus

### Vant 版本
2.10.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://gitee.com/Mango28/vant-demo.git" target="_blank">https://gitee.com/Mango28/vant-demo.git</a>

### 描述问题
比如设置日历  minDate: new Date(2020, 0, 1), maxDate: new Date(2020, 11, 6)时，在页面加载后首次打开日历视图无法定位到当前日期，在不重新加载页面的情况下再次打开日历就会恢复正常。如果把上面的maxDate: new Date(2020, 11, 6)改成new Date(2022, 11, 6)，在首次打开也是正常的，似乎当最大日期值小于某个值时首次打开就无法定位到当前时期了。

**Comment by xu-code** [comment]
今天更新也遇到这个问题，而且标题的时间跟当前月份对应不上，我这边相差了一个月
![image](https://user-images.githubusercontent.com/55622423/93574983-a4654900-f9cb-11ea-96ab-f11ec2b6521f.png)

**Comment by wxlaionangog** [comment]
这个版本我也出现这个问题了,  回退版本了

**Comment by xiang1128** [comment]
是的，如果最大日期就在当前月份的时候，日期title显示的是上个月，这个问题一直都存在

**Comment by wxlaionangog** [comment]
自己模拟了一个title展示,我把它自带的都隐藏了

**Comment by chenjiahan** [comment]
下个版本修复

**Comment by DOUdzl** [comment]
请问，我设置了minDate:new Date(2020,6,1)，然后maxDate:new Date()，但是打开页面直接定位到7月份，但是选定的日期还是当天的，怎么设置能让定位到当前月份啊

**Comment by chenjiahan** [comment]
已在 2.10.8 版本修复
