### ISSUE TITLE
[Feature Request] 建议 sidebarItem 有个默认插槽，可以自定义内容

### ISSUE THREAD

**Issue by flycj** [youzan/vant#7201]
### 这个功能解决了什么问题
可以自定sideBarItem 中的内容

### 描述您想要的解决方案
sideBarItem中有可选 ```<slot></slot>```

### 建议的API是什么样的
如果设置了 title 则没有 ```<slot></slot>``` , 不设置 title 则 ```<slot></slot>``` 存在

**Comment by chenjiahan** [comment]
下个版本支持

**Comment by chenjiahan** [comment]
已在 2.10.8 版本支持
