### ISSUE TITLE
[Bug Report] 使用vw单位后，Swipe 轮播组件loop设置为false，滑动到最后一页仍能滑动

### ISSUE THREAD

**Issue by wyyx50** [youzan/vant#7204]
### 设备 / 浏览器
华为p30/微信内置浏览器、夸克浏览器、华为内置浏览器

### Vant 版本
2.10.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://2e4ly.csb.app/" target="_blank">https://2e4ly.csb.app/</a>

### 描述问题
在我们的项目中发现：Swipe 轮播组件loop设置为false会失效，滑动最后一页仍能滑动，会切换到第一页。
经过反复测试，发现swiper组件的外层嵌套的元素的padding和margin不能使用css3中的vw单位，否则就会出现这个问题。
我们移动端的项目需要适配不同分辨率的屏幕，所以我们结合使用了vw单位和rem单位，html根元素定义font-size: calc(10/375*100vw);，页面元素使用rem单位，然后就出现了上述问题。
CodeSandbox链接：https://codesandbox.io/s/vant-issue-moban-forked-2e4ly?file=/src/App.vue

**Comment by chenjiahan** [comment]
宽度是小数时可能出现该情况，下个版本修复

**Comment by chenjiahan** [comment]
已在 2.10.8 版本修复
