### ISSUE TITLE
[Bug Report] tab标签页 标题 兼容性

### ISSUE THREAD

**Issue by zhuo-xiang** [youzan/vant#7209]
### 设备 / 浏览器
mac chrome

### Vant 版本
2.8.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://user-images.githubusercontent.com/61954852/93657407-38372380-fa65-11ea-8cb2-1d5a1e5db951.png" target="_blank">https://user-images.githubusercontent.com/61954852/93657407-38372380-fa65-11ea-8cb2-1d5a1e5db951.png</a>

### 描述问题
正常效果 windowpc uc浏览器, android微信浏览器 https://user-images.githubusercontent.com/61954852/93657439-9532d980-fa65-11ea-9b02-3a3ff2d98a22.png.
非正常效果  mac chrome, iOS手机未测试 https://user-images.githubusercontent.com/61954852/93657407-38372380-fa65-11ea-8cb2-1d5a1e5db951.png
非正常效果 span标签的 display: -webkit-box 样式去掉后能正常显示

提交issue 这个页面非常卡,  打个字得反应3,4秒

**Comment by chenjiahan** [comment]
把 ellipsis 属性设置为 false 即可
