### ISSUE TITLE
[Bug Report] Vant 更新至 2.10.7 版本后，日历组件初始值出错

### ISSUE THREAD

**Issue by hwjfqr** [youzan/vant#7216]
### 设备 / 浏览器
Chrome

### Vant 版本
2.10.7

### Vue 版本
2.6.12

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-tto1z?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-tto1z?file=/src/App.vue</a>

### 描述问题
Vant 更新至 2.10.7 版本后，日历组件在首次打开后，不显示选中的日期，关闭后再次打开才会显示。

**Comment by chenjiahan** [comment]
这个问题下个版本会修复，参见 https://github.com/youzan/vant/issues/7198
