### ISSUE TITLE
[Feature Request] 分页增加自定义按钮内容的插槽

### ISSUE THREAD

**Issue by zhujianxiong** [youzan/vant#7217]
### 这个功能解决了什么问题
目前的分页只有上一页和下一页，文字显示

### 描述您想要的解决方案
期待分页的上一页和下一页除了用文字显示之外，还可以用icon来显示

### 建议的API是什么样的
期待分页的上一页和下一页除了用文字显示之外，还可以用icon来显示，如：< 12...345 >

**Comment by chenjiahan** [comment]
已在 2.10.9 版本支持
