### ISSUE TITLE
[Bug Report] 新版14.0ios系统下tabs组件，偶尔会出现不能滚动问题

### ISSUE THREAD

**Issue by wf1205952124** [youzan/vant#7219]
### 设备 / 浏览器
Apple手机，新版14.0ios系统

### Vant 版本
2.10.6

### Vue 版本
2.5.22

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/tab" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/tab</a>

### 描述问题
新版14.0ios系统下tabs组件，在有多个tab时，切换到前几个tab时，偶尔会出现不能滚动问题

**Comment by chenjiahan** [comment]
是标题栏不能左右滑动吗，还是页面无法上下滚动

**Comment by MGsniper** [comment]
上下滚动会抽搐
