### ISSUE TITLE
 vant组件文档开发

### ISSUE THREAD

**Issue by effortComeOn** [youzan/vant#7221]
### 设备 / 浏览器
浏览器

### Vant 版本
2.10.8

### Vue 版本
3.0.0

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/notify" target="_blank">https://youzan.github.io/vant/#/zh-CN/notify</a>

### 描述问题
您好，请问下，你们的组件开发的文档是怎么生成的，或者是怎么写的呢？有没有对应框架可以生成你们组件文档的模版，非常喜欢你们组件文档的样式，感谢回复

我看到了你们的vant-cli，可以对应生成文档，有没有可以支持react的文档组件cli？

**Comment by chenjiahan** [comment]
React 的 cli 目前没有喔，可以看一下 umi 提供的文档工具

https://github.com/umijs/dumi
