### ISSUE TITLE
版本： 2.10.8      Slider 滑块组件 drag-start 、drag-end 2个事件无效，打印结果为 undefined

### ISSUE THREAD

**Issue by wangchenyi1996** [youzan/vant#7223]
<template>
  <div class="find-box">
    <van-slider v-model="percent" @drag-start="dragStart" @drag-end="dragEnd"/>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
@Component
export default class extends Vue {
  private percent: number = 0;

  // 开始滑动
  dragStart(e:any){
    console.log(e)
  }
  // 结束滑动
  dragEnd(e:any){
    console.log(e)
  }

}
</script>

<style lang="scss" scoped>
.find-box {
  padding: 0 0.3rem;
}
</style>

**Comment by chenjiahan** [comment]
这两个事件本来就没有入参的
