### ISSUE TITLE
List 组件可以与 PullRefresh 组件结合使用

### ISSUE THREAD

**Issue by DouNingNing** [youzan/vant#7224]
描述问题
list组件设置高度后，只要是下拉都会触发下拉刷新，list列表没有办法滑动
<img width="404" alt="微信图片_20200922150848" src="https://user-images.githubusercontent.com/19701281/93852992-9d994780-fce5-11ea-8adf-b792ea3572cd.png">

**Comment by zhaoshuan** [comment]
不需要设置高度吧，另外检查一下html、body有没有设置overflow:hidden，如果有，需要去掉
