### ISSUE TITLE
[Bug Report] yarn test 单个文件，但测试了所有

### ISSUE THREAD

**Issue by gd4Ark** [youzan/vant#7225]
### 设备 / 浏览器
所有

### Vant 版本
2.10.8

### Vue 版本
3.0.0

### 重现链接
<a href="https://i.loli.net/2020/09/22/vOa17w64SXdBUWe.png" target="_blank">https://i.loli.net/2020/09/22/vOa17w64SXdBUWe.png</a>

### 描述问题
执行
```bash
 yarn test src/address-list/test/index.spec.js
```

但执行了所有测试文件

![image.png](https://i.loli.net/2020/09/22/vOa17w64SXdBUWe.png)

**Comment by chenjiahan** [comment]
vant-cli 目前不支持测试单个文件喔
