### ISSUE TITLE
van-field的label属性没法使用中文空格

### ISSUE THREAD

**Issue by georgewei** [youzan/vant#7228]
我用vant 2.5.3，vue 2.6.11，在代码里有这两行：

```
<van-field v-model="reportData.check_date_from" label="检查日期" placeholder="请选择开始日期"/>
<van-field v-model="reportData.check_date_to" label="　　　至" placeholder="请选择结束日期"/>
```
第二行代码中的label属性的值"　　　至"的前三个为中文空格，这样做的目的是让label右对齐。在VS Code中保存代码后报错：

> error  in ./src/views/home/xxxx.vue
> 
> Module Error (from ./node_modules/_eslint-loader@2.2.1@eslint-loader/index.js):
> 
> /Users/xxxx/Projects/xxxx/src/views/xxxx.vue
>   36:75  error  Irregular whitespace not allowed  no-irregular-whitespace
> 
> ✖ 1 problem (1 error, 0 warnings)

我尝试在/.eslintrc.js中配置了如下选项

```
rules: {
    'no-irregular-whitespace': 'off'
}
```

配置好后在VS Code的代码编辑窗口里不再出现红色波浪线了，但编译仍然报以上错误，页面也无法正常显示。请问应该怎么解决？

**Comment by xiaolonggee** [comment]
![微信图片_20200923090528](https://user-images.githubusercontent.com/30064467/93952647-f0254300-fd7b-11ea-9751-d6246316a132.png)
![微信图片_20200923090533](https://user-images.githubusercontent.com/30064467/93952662-f7e4e780-fd7b-11ea-8b85-fb44f9e4a90a.png)
按照你说的我放了没问题，你直接把eslint先关了试一下，或者你给 至 前边加几个透明的字应该也可以解决

**Comment by georgewei** [comment]
谢谢，已经解决了，是/.eslintrc.js中parser的配置不正确导致的
