### ISSUE TITLE
van-button 同时使用vfor和ref 获取ref只会得到最后一个元素 而不是一个数组

### ISSUE THREAD

**Issue by Syntax-J** [youzan/vant#7229]
```html
<van-button v-for="i in 10" :key="i" ref="btn"></van-button>
```
```js
console.log(this.$refs.btn) //只能获得最后一个button元素
```

**Comment by Syntax-J** [comment]
测试发现是这里少定义了一个vue属性 **refInFor**
https://github.com/youzan/vant/blob/106114333b197cbfadbbdeb299326b59819f28dc/src/utils/functional.ts#L8-L17

https://github.com/youzan/vant/blob/106114333b197cbfadbbdeb299326b59819f28dc/src/utils/functional.ts#L22-L39
 所以导致inherit后表现形式与原生vue文档中提及的ref与vfor同时使用所不同，

> 当 ref 和 v-for 一起使用的时候，你得到的 ref 将会是一个包含了对应数据源的这些子组件的数组。

没有refInFor时候如果直接使用
```js
ref="foo"
```
最后个dom会覆盖掉之前，而使用
```js
:ref="someKey" 
```
这种情况下可以得到每个dom
目前项目里是用的:ref="someKey"来获取每个元素的 不知道这是这样设计的还是可能要改动的地方

**Comment by chenjiahan** [comment]
确实漏了 refInFor 属性，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.10.9 版本修复
