### ISSUE TITLE
[Bug Report] van-tabs中的van-tabs_line位置不正确

### ISSUE THREAD

**Issue by xiaomun** [youzan/vant#7232]
### 设备 / 浏览器
Android系统

### Vant 版本
2.3.3

### Vue 版本
2.5.2

### 重现链接
<a href="https://github.com/youzan/vant/issues/7231" target="_blank">https://github.com/youzan/vant/issues/7231</a>

### 描述问题
van-tabs左右两侧加上van-icon后，第一次启动时 第一个van-tab下面的van-tabs_line（横线）位置不对。
图片见  https://github.com/youzan/vant/issues/7231

**Comment by chenjiahan** [comment]
刚试了下，最新版是没问题的，可以升级下版本

**Comment by xiaomun** [comment]
> 
> 
> 刚试了下，最新版是没问题的，可以升级下版本
好的 谢谢

**Comment by xiaomun** [comment]
> 
> 
> 刚试了下，最新版是没问题的，可以升级下版本

好的 谢谢

**Comment by xiaomun** [comment]
> 
> 
> 刚试了下，最新版是没问题的，可以升级下版本

我刚试了下 还是不行

**Comment by chenjiahan** [comment]
能否提供 codesandbox 复现链接看下

https://codesandbox.io/s/m5v3f

**Comment by qlp504847629** [comment]
3.0版本也有这个问题的

**Comment by l123456789jy** [comment]
已经找到必现原因，数据加载之前如果是隐藏状态，数据加载之后再显示就会出现这样问题 @chenjiahan

**Comment by chenjiahan** [comment]
@l123456789jy 来个复现链接 https://codesandbox.io/s/m5v3f

**Comment by l123456789jy** [comment]
@chenjiahan  https://codesandbox.io/s/vant-issue-moban-forked-b3k6q?file=/src/App.vue

**Comment by chenjiahan** [comment]
这种情况确实有问题，而且没法在组件内部避免。这是因为 Tab 挂载的时候会初始化并获取自身宽度，如果处于隐藏状态下，Tab 是获取不到自身宽度的，因此底部条的位置没法正确计算。

解决方法是在展示 Tab 的时候，调用 Tab 实例上的 resize 方法。
