### ISSUE TITLE
updateInnerValue 同步更新当前picker值，致使无法友好的在两个picker之间控制选择范围。

### ISSUE THREAD

**Issue by mikepxq** [youzan/vant#7233]
minDate: 'updateInnerValue',
maxDate: 'updateInnerValue',
如果修改minDate、maxDate,同步更新当前picker值，致使无法友好的在两个picker之间控制选择范围。
比如：两个时间选择器，结束时间的minDate为开始时间的值。当开始大于结束时间时，可以同步设置结束时间为开始时间。再把开始时间设置小于结束时间时，由于结束时间的minDate追随开始时间更改，内部picker也调用updateInnerValue，也使当前picker选项动态更改了，这里其实是不友好的！！！。应该是添加选项，控制样式，使picker 保持在用户之前的交互状态下。
或者不用v-model，但change事件不要只抛出picker实例，如果是DatePicker组件，至少是DatePicker的实例，这样可以直接处理Date类型的值。

**Comment by mikepxq** [comment]
发现可以直接监听input事件
@input="onInputDatePicker($event, 'end')"

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
