### ISSUE TITLE
[Feature Request] Tab 标签页 tabcontent可以为空

### ISSUE THREAD

**Issue by balge** [youzan/vant#7236]
### 这个功能解决了什么问题
只需要用到tab中的to属性跳转url，并不需要切换content

### 描述您想要的解决方案
van-tab 标签内空内容时，不渲染van-tabs__content节点

### 建议的API是什么样的
van-tab标签内空内容时，不渲染van-tabs__content节点

**Comment by chenjiahan** [comment]
可以的，后续优化下

**Comment by chenjiahan** [comment]
已在 2.10.9 版本优化
