### ISSUE TITLE
[Bug Report] @vant包下index.less的字体文件路径

### ISSUE THREAD

**Issue by heart-er** [youzan/vant#7239]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0-beta.0

### Vue 版本
3.0.0

### 重现链接
无链接

### 描述问题
@vant包下的index.less的字体文件的路径是有赞cdn，https://img.yzcdn.cn/vant/vant-icon-0c347b.ttf，为什么不改成@vant包里的字体文件呢，因为我们想自己替换成自己的cdn，导致出现一个问题，就是即下载了有赞的cdn，也下载了我们自己的cdn字体文件

**Comment by chenjiahan** [comment]
可以替换的喔，注意下覆盖 fontface 的样式要和 Icon 组件本身的样式在同一个 CSS 文件里加载

默认的 CDN 地址会在 3.0 版本优化下，默认使用本地的
