### ISSUE TITLE
希望calender可以做成左右滑动切换月份，并且支持周显示和月显示的切换，就像钉钉日历一样，思路是swiper

### ISSUE THREAD

**Issue by hxzsj** [youzan/vant#7240]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持喔
