### ISSUE TITLE
DatetimePicker 开发环境正常打包后 时间出现NAN

### ISSUE THREAD

**Issue by chenxueling** [youzan/vant#7241]
设备 / 浏览器
chrome
Vant 版本
2.10.8
Vue 版本
2.5.2
描述问题
DatetimePicker 开发环境正常打包后 时间出现NAN 
 <van-datetime-picker
      v-model="currentDate"
      type="datetime"
      title="选择完整时间"
      :min-date="minDate"
      :formatter="formatter"
      :show-toolbar="false"
      visible-item-count="5"
      item-height="42"
      @change = "changePicker"
    />

formatter函数返回的值打印也出现NAN

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
