### ISSUE TITLE
[Bug Report] DatetimePicker 开发环境正常，打包后 时间显示出现NAN

### ISSUE THREAD

**Issue by chenxueling** [youzan/vant#7242]
设备 / 浏览器
chrome
Vant 版本
2.10.8
Vue 版本
2.5.2
描述问题
DatetimePicker 开发环境正常打包后 时间出现NAN 
 <van-datetime-picker
      v-model="currentDate"
      type="datetime"
      title="选择完整时间"
      :min-date="minDate"
      :formatter="formatter"
      :show-toolbar="false"
      visible-item-count="5"
      item-height="42"
      @change = "changePicker"
    />

formatter函数返回的值打印也出现NAN

**Comment by chenxueling** [comment]
https://home-new.roadshowchina.cn//public/activity/20200716/bug.png

**Comment by chenjiahan** [comment]
请检查下你的 formatter 是否正确返回了正确的字符内容

**Comment by chenxueling** [comment]
图片已经打印了formatter，返回的内容不正确    https://home-new.roadshowchina.cn//public/activity/20200716/bug.png

**Comment by chenjiahan** [comment]
那就是你的 formatter 本身处理的问题

**Comment by cqzongjian** [comment]
type="date"也有该问题，没有使用formatter

```
<van-datetime-picker
   @confirm="confirm"
   @cancel="cancel"
   v-model="currentDate"
   type="date"/>
```

![image](https://user-images.githubusercontent.com/24648402/94383829-b1c0c700-0173-11eb-901a-908813bb0a6f.png)

**Comment by chenxueling** [comment]
webpack 打包压缩引起的
