### ISSUE TITLE
[Feature Request] validate-trigger 能否支持多种

### ISSUE THREAD

**Issue by Sevenonclick** [youzan/vant#7243]
### 这个功能解决了什么问题
表单验证多种触发机制并行，onSubmit 和 onBlur

### 描述您想要的解决方案
表单验证多种触发机制并行，onSubmit 和 onBlur

### 建议的API是什么样的
string 可以变更为数组，同时支持多种表单触发机制

**Comment by chenjiahan** [comment]
目前 onBlur = onBlur + onSubmit，不需要设置数组，后续会在文档里说明下
