### ISSUE TITLE
Tabs 标签组件 滑动切换问题

### ISSUE THREAD

**Issue by oliver34** [youzan/vant#725]
按照官方文档，tabs 标签上加了swipeable 属性，但是还是不能左右滑动
{
  "vue": "^2.5.2",
  "vant": "^0.12.4"
}

**Comment by cookfront** [comment]
请将`vant`版本升级到`1.0.0`

**Comment by chenzhongbin99** [comment]
请教一下，按照官方文档，tabs 标签上加了swipeable 属性，但是还是不能左右滑动。安装的vant是1.2.1
