### ISSUE TITLE
[Bug Report] datetimepicker动态修改mindate或maxdate问题

### ISSUE THREAD

**Issue by Zohar727** [youzan/vant#7253]
### 设备 / 浏览器
2.6.10

### Vant 版本
2.10.8

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-f8lep?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-f8lep?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
动态修改mindate或maxdate后，当前显示选中的值会变

1. 默认初始日期2020.9.26
2. 选择日期为2020.9.22
3. 触发change事件修改mindate为2020.9.22
4. 此时datetimepicker显示当前选中日期为2039.11.30

**Comment by q807175022** [comment]
同一个页面使用两个datetimepicker组件并且有动态修改mindate或maxdate,会出现页面卡死,浏览器崩溃的情况

**Comment by JasperGreat** [comment]
什么时候能修复这个问题啊  datetimepicker动态修改mindate或maxdate问题

**Comment by nemo-shen** [comment]
@Zohar727 @q807175022  @JasperGreat  @chenjiahan 

原因应该是在`updateColumnValue`方法里存在`nextTick`，导致如果在`updateInnerValue`里面直接去取的话取的index会不正确

近期会修复

**Comment by chenjiahan** [comment]
已在 2.12.16 版本修复
