### ISSUE TITLE
van-overlay 遮照层和van-progress 同时使用， :show设为false 时，  van-progress 的precentage不可用

### ISSUE THREAD

**Issue by websmallrabbit** [youzan/vant#7256]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以在 Progress 上添加一个 v-if="show"

```html
<van-progress v-if="show" />
```
