### ISSUE TITLE
step步骤条,如何将已完成节点,进行中的节点,未完成的节点分别单独设置图标?

### ISSUE THREAD

**Issue by fei3977071** [youzan/vant#7258]

**Comment by fei3977071** [comment]
现在未完成和已完成的节点图标只能设置成一致的, 这个能否改一下?

**Comment by fei3977071** [comment]
![image](https://user-images.githubusercontent.com/35058190/94358057-be401380-00d0-11eb-96df-2a157b7b5209.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
