### ISSUE TITLE
[Bug Report] Popup 与 DropdownItem 打包后 CSS 代码顺序问题，导致候选项定位有误

### ISSUE THREAD

**Issue by onlyling** [youzan/vant#7259]
### 设备 / 浏览器
all

### Vant 版本
2.10.8

### Vue 版本
2.6.12

### 重现链接
无

### 描述问题
`vue-cli` 创建默认项目，`vue.config.js` 中增加 `optimization.splitChunks`，添加 `vant: { name: 'vendors-vant', test: /[\\/]node_modules[\\/]vant[\\/]/, chunks: 'all', reuseExistingChunk: true, enforce: true, priority: 10 }`，比较常规的提取所有组件中使用的 `vant` 代码。

项目中多处使用 `Popup` 组件。

打包后提取 CSS 到 `vendors-vant.[hash].css` 文件，CSS 代码中 `.van-dropdown-item__content` 在 `.van-popup` 前，导致下拉菜单的候选项呈现有误（开发模式下无问题）。

目前通过项目全局样式重新声明 `.van-dropdown-item__content` 的 `position` 能决绝问题，总感觉有点不棒，这边有没有比较好的方案决绝呢？

<img width="360" alt="WX20200927-151404@2x" src="https://user-images.githubusercontent.com/9999765/94358512-36f49f00-00d4-11eb-8c6b-bb9074d543c3.png">

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/94557245-e37b8000-0290-11eb-8a5c-4e6ec22fed9c.png)

Vant 代码里是遵循样式引入顺序的，先引入 popup.css，再引入 dropdown-iten.css，理论上不会出现你遇到的这种情况。

如果有问题的话，建议检查下打包配置，这边也没什么方案可以提供..
