### ISSUE TITLE
[Feature Request] Collapse 折叠面板，新增展开收起的回调函数

### ISSUE THREAD

**Issue by lx815** [youzan/vant#7260]
### 这个功能解决了什么问题
在实际的业务场景中，有时会需要在自定义的title的上面加radio按钮等操作。由于折叠面板没有展开收起的回调函数，所以在选择radio按钮的时候，没办法进行控制。

### 描述您想要的解决方案
Collapse 折叠面板，新增展开收起的回调函数。能够在点击了按钮之后，自行决定是否展开或收起这个折叠面板

### 建议的API是什么样的
跟以前的组件API一致

**Comment by chenjiahan** [comment]
已在 2.10.9 版本支持
