### ISSUE TITLE
[Bug Report] DropdownMenu中的Dropitem下放置popup picker在ios下无法显示

### ISSUE THREAD

**Issue by linxiaowang** [youzan/vant#7261]
### 设备 / 浏览器
ios

### Vant 版本
2.10.8

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-tpvgs?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-tpvgs?file=/src/App.vue</a>

### 描述问题
点击dropdownItem中的内容弹出popup picker，在ios下picker不显示，但是遮罩层有出现

**Comment by chenjiahan** [comment]
用 iphoneXR 试了下没问题，建议你再试下。

可以考虑在 Popup 上添加 get-container="body" 属性

**Comment by linxiaowang** [comment]
在iphone11上试了，点击内容还是弹不出picker啊TT, 加了get-container=“body”也还是一样

**Comment by zayne0618** [comment]
iphone x也是有问题。怎么解决？

**Comment by mineMineGo** [comment]
![image](https://user-images.githubusercontent.com/21363757/151090993-e3f21e2e-e47b-40ec-a808-9ef076dad03d.png)
上面的链接打开以后，我看控制台报错了
