### ISSUE TITLE
[Bug Report] DatetimePicker 不能返回“yyyy-MM-dd HH:mm:ss”格式

### ISSUE THREAD

**Issue by landonzeng** [youzan/vant#7262]
### 设备 / 浏览器
所以设备

### Vant 版本
2.10.8

### Vue 版本
3.0.0

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/datetime-picker" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/datetime-picker</a>

### 描述问题
DatetimePicker 的datetime类型不能返回“yyyy-MM-dd HH:mm:ss”格式，返回的是 “Sun Sep 27 2020 21:57:00 GMT 0800 (中国标准时间)”这样的格式，是否可以提供个符合国内时间格式的选项，目前这样用起来真的非常不方便，谢谢！

**Comment by chenjiahan** [comment]
返回的是 Date 对象，你可以通过 [dayjs](https://github.com/iamkun/dayjs) 这样的时间库进行转换
