### ISSUE TITLE
[Bug Report] DatetimePicker 开发环境正常，打包后时间显示出现NAN

### ISSUE THREAD

**Issue by cqzongjian** [youzan/vant#7264]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.8

### Vue 版本
3.0.0

### 描述问题
DatetimePicker 开发环境正常打包后时间出现NAN

                       <van-datetime-picker
                            @confirm="confirm"
                            @cancel="cancel"
                            v-model="currentDate"
                            type="date"
                        />

**Comment by cqzongjian** [comment]
![image](https://user-images.githubusercontent.com/24648402/94384217-95715a00-0174-11eb-863a-41250f70d8d5.png)

**Comment by wodeluck** [comment]
同问

**Comment by chenjiahan** [comment]
给个能复现问题的仓库看下？

**Comment by leishiwo31** [comment]
这个关闭了，但是最后解决方案是啥啊，我也遇到这种问题的

**Comment by chenxueling** [comment]
这个是webpack 压缩打包引起的

> 这个关闭了，但是最后解决方案是啥啊，我也遇到这种问题的

**Comment by chenjiahan** [comment]
@chenxueling 具体是 webpack 的什么原因引起的，有相关的 issue 吗~

**Comment by chenxueling** [comment]
> @chenxueling 具体是 webpack 的什么原因引起的，有相关的 issue 吗~ 

 // new UglifyJsPlugin({
    //   uglifyOptions: {
    //     compress: {
    //       warnings: false
    //     },
    //   },
    //   sourceMap: config.build.productionSourceMap,
    //   parallel: true,
    // }),

没有 注释这个就正常了，我之前也提过 https://github.com/youzan/vant/issues/7242

**Comment by chenjiahan** [comment]
get，现在 Webpack 默认用 TerserPlugin 压缩了，应该不存在此问题
