### ISSUE TITLE
版本1到2升级导致的Slider组件问题

### ISSUE THREAD

**Issue by is-liyiwei** [youzan/vant#7269]
<van-slider v-model="value" max="200" />

value: 100

在版本1里面，value = 100的时候进度条是满的了，不受max属性形象
但是在版本2里面进度条只有50%，似乎版本2是根据max来作为参考的

这个有什么办法能够指定为版本1的方式吗

**Comment by chenjiahan** [comment]
这个没法指定呢，直接调整 max 的值就行
