### ISSUE TITLE
使用Tabbar组件时自定义图标，通过webpack工具如何使用本地路径？

### ISSUE THREAD

**Issue by Kennersky** [youzan/vant#727]
自定义图标使用本地路径 问题
export default {
  data() {
    return {
      active: 0,
      icon: {
        normal: '//img.yzcdn.cn/1.png',
        active: '//img.yzcdn.cn/2.png'
      }
    }
  }
}
这里面的图标路径不能为本地路径吗，我改成本地的预览不显示

**Comment by chenjiahan** [comment]
@Kennersky 这个问题和组件库无关噢，是 webpack 配置的问题，请到对应的地方提问~

**Comment by svenjia** [comment]
同样的问题，如果是引入本地路径，如何设置
![image](https://user-images.githubusercontent.com/29444841/50322098-afe1c280-050e-11e9-9261-cc963d192960.png)
这样设置webpack不会解析，该怎么写相对路径呢

**Comment by svenjia** [comment]
#1913

**Comment by RememberingYourDream** [comment]
normal: require('路径'),

**Comment by chenjinshu123** [comment]
先在script顶部导入图片，再在data里使用就可以import WorkorderPageInActiv from '@/assets/icon/WorkorderPageInActive.png'
