### ISSUE TITLE
[Feature Request] 私有化部署vant文档

### ISSUE THREAD

**Issue by keejo125** [youzan/vant#7271]
### 这个功能解决了什么问题
内网私有化部署有赞文档

### 描述您想要的解决方案
目前通过vant-cli生成的文档包含了很多cdn的地址，还有百度的api，需要一个纯静态的私有本地部署方法

### 建议的API是什么样的
提供一个私有部署，不含任何cdn的文档，谢谢

**Comment by chenjiahan** [comment]
暂无计划提供呢

**Comment by alvin0216** [comment]
@chenjiahan 你好，请问 vant-cli 脚手架可以安装 vue3 吗？如何安装，没找到文档，谢谢

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/7478
