### ISSUE TITLE
使用 ImagePreview 图片预览组件，图片过长导致宽度太小，宽度不能铺满屏幕，希望可以宽度铺满，下拉的效果

### ISSUE THREAD

**Issue by lisir2** [youzan/vant#7273]
> 样式问题

使用 ImagePreview 图片预览，图片过长导致宽度太小，宽度不能铺满屏幕，希望可以宽度铺满，下拉的效果

**Comment by lisir2** [comment]
使用 ImagePreview 图片预览，图片过长导致宽度太小，宽度不能铺满屏幕，希望可以宽度铺满，下拉的效果

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3928

**Comment by DickyNet** [comment]
同样需要这样的功能。希望官方提供优化方案。加油
