### ISSUE TITLE
[Bug Report] area 组件是否支持 429004001 这样的省市区 数据

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#7274]
### 设备 / 浏览器
ios

### Vant 版本
2.8.5

### Vue 版本
2.6.10

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/area" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/area</a>

### 描述问题
area 组件是否支持 429004001 这样的省市区数据
![image](https://user-images.githubusercontent.com/42430384/94510483-7395d700-0249-11eb-8291-e08a6bb52364.png)

**Comment by anihCevol** [comment]
![20200929114917](https://user-images.githubusercontent.com/42430384/94510652-dd15e580-0249-11eb-8e4b-f01bfe0ed46a.jpg)

**Comment by anihCevol** [comment]
![Uploading image.png…]()

**Comment by anihCevol** [comment]
![image](https://user-images.githubusercontent.com/42430384/94510748-19e1dc80-024a-11eb-9eae-3872168291c4.png)

**Comment by anihCevol** [comment]
文档提供的area.json 文件 是从何处导的 为何和网上查的数据不一样

**Comment by chenjiahan** [comment]
429004001 这样的数据是不支持的，area code 必须是六位数字

文档提供的 area.json 文件仅供参考，实际项目中可以自行调整
