### ISSUE TITLE
List 组件与 PullRefresh 组件结合使用时，下拉出现两个加载中.....

### ISSUE THREAD

**Issue by goHaoliyou** [youzan/vant#7276]
描述一下问题
List 组件与 PullRefresh 组件结合使用是，下来出现两个加载中.....
van-pull-refresh下有个van-loading, van-list__loading里也有个loading, loading-text=""已设空了。

[环境]

设备: chrome浏览器,safari浏览器，小米手机,,,,,都有
基础库版本: 2.10.8

**Comment by goHaoliyou** [comment]
van-pull-refresh的loading-text=" " ，van-list的loading-text=" "两个都设为空，下拉还是有两个加载状态，可以关闭一个状态么？有加载不显示的状态么

**Comment by goHaoliyou** [comment]
有处理了，在onRefresh() 里马上this.refreshing = false;

**Comment by lmxin123** [comment]
我也遇到同样的问题，请问是怎么解决的？急啊，这明显是bug

**Comment by goHaoliyou** [comment]
> 
> 
> 我也遇到同样的问题，请问是怎么解决的？急啊，这明显是bug

我是这么解决的，原因是触发了refreshing的loading和下拉加载的loading两个。关掉一个就行了，不知道你是不是这原因。
