### ISSUE TITLE
[Feature Request] @vant/markdown-vetur可以调整下支持windows系统

### ISSUE THREAD

**Issue by yuningjiang123** [youzan/vant#7277]
### 这个功能解决了什么问题
https://github.com/youzan/vant/blob/dev/packages/vant-markdown-vetur/src/parser.ts
TABLE_REG这个正则无法在windows系统下匹配md文件中的table

### 描述您想要的解决方案
将/^\|. \n\|\s*- /  调整为/^\|. \r?\n\|\s*- /

### 建议的API是什么样的
将/^\|. \n\|\s*- /  调整为/^\|. \r?\n\|\s*- /

**Comment by chenjiahan** [comment]
欢迎 PR

**Comment by chenjiahan** [comment]
已发布 @vant/markdown-vetur@2.0.2

**Comment by yuningjiang123** [comment]
> 已发布 @vant/markdown-vetur@2.0.2

@vant/cli中package.json的@vant/markdown-vetur版本号能否同步更新下呢

**Comment by chenjiahan** [comment]
已发布 @vant/cli 2.6.1 版本
