### ISSUE TITLE
calendar日历月份触顶后标题中的月份不变，还得往下划一点才变

### ISSUE THREAD

**Issue by ATaurenRideRocket** [youzan/vant#7278]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/7279
