### ISSUE TITLE
[Bug Report] calendar日历月份触顶后标题中的月份不变，还得往下划一点才变

### ISSUE THREAD

**Issue by ATaurenRideRocket** [youzan/vant#7279]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/changelog" target="_blank">https://youzan.github.io/vant/#/zh-CN/changelog</a>

### 描述问题
calendar日历月份触顶后标题中的月份不变，还得往下划一点才变，我试了下vant2.10.6版本就有这个问题了，降版本到2.10.0才正常。

**Comment by chenjiahan** [comment]
这个已经在最新版修复了，可以升级试下
