### ISSUE TITLE
关于vant中swiper的使用问题

### ISSUE THREAD

**Issue by Bluesbutterfly** [youzan/vant#7285]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
在使用swiper中，在移动端宽度高度均为100，竖向滚动，滚动过程中在ios端会有突发的白框闪动一下然后消失，影响到了使用

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
