### ISSUE TITLE
[Bug Report] van-address-edit组件tel-validator报错

### ISSUE THREAD

**Issue by qlp504847629** [youzan/vant#7286]
### 设备 / 浏览器
谷歌浏览器84

### Vant 版本
3.0.0-beta.2

### Vue 版本
3.0.0

### 重现链接
<a href="https://codepen.io/qlp504847629/pen/qBZGYLq" target="_blank">https://codepen.io/qlp504847629/pen/qBZGYLq</a>

### 描述问题
编辑地址组件有个tel-validator属性,对手机号进行校验,文档中提示填string => boolean
但是浏览器会一直报Uncaught TypeError: props.telValidator is not a function,
应写成如下格式
@tel-validator="isMobile"

**Comment by chenjiahan** [comment]
不是 @tel-validator，是 :tel-validator
