### ISSUE TITLE
[Bug Report] van-search插件的  input-align对齐功能 整体偏右

### ISSUE THREAD

**Issue by quiklyrun** [youzan/vant#7288]
### 设备 / 浏览器
google chrome

### Vant 版本
3.0.0-beta.2

### Vue 版本
3.0.0

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
van-search插件的  input-align对齐功能 整体偏右，焦点无法控制在最左侧

**Comment by quiklyrun** [comment]
有什么方法调到最左侧吗

**Comment by chenjiahan** [comment]
这个没有办法呢，焦点是跟着对齐方向走的
