### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by qadcyygg** [youzan/vant#7289]
Pagination组件 Slots自定义内容没有效果

**Comment by chenjiahan** [comment]
插槽是在 2.10.9 版本新增的，需要升级一下版本

**Comment by qadcyygg** [comment]
1

**Comment by chenjiahan** [comment]
https://cdn.jsdelivr.net/npm/vant@2.10/lib/vant.min.js
https://cdn.jsdelivr.net/npm/vant@2.10/lib/index.css
