### ISSUE TITLE
我想进微信交流群

### ISSUE THREAD

**Issue by chaituan** [youzan/vant#729]

**Comment by chenjiahan** [comment]
欢迎进群~
<img src="https://user-images.githubusercontent.com/7237365/37596482-3fb34c62-2bb7-11e8-97c9-6a6e1c41ad50.jpeg" width="300" />

**Comment by webofrxy** [comment]
二维码失效了，请问可以更新一下吗

**Comment by cookfront** [comment]
![wechatimg92](https://user-images.githubusercontent.com/4829465/38228050-ee4dbc80-3733-11e8-8d90-3895fb29ef1e.jpeg)

**Comment by syncml** [comment]
二维码失效了，请问可以更新一下吗

**Comment by mhxy13867806343** [comment]
二维码失效了，请问可以更新一下吗
