### ISSUE TITLE
vant3.0在vue3.0中如何自动按需引入组件

### ISSUE THREAD

**Issue by suyuwen1** [youzan/vant#7290]
vant3.0在vue3.0中如何自动按需引入组件

**Comment by chenjiahan** [comment]
按需引入和 2.x 一样，使用 babel-plugin-import 即可

**Comment by suyuwen1** [comment]
@ chenjiahan 在main.js里引入可以正常，在home.vue文件里按文档给的方法引入提示无法成功加载组件

**Comment by chenjiahan** [comment]
你是怎么引的

**Comment by suyuwen1** [comment]
@chenjiahan 

home.vue文件：
import { createApp } from 'vue'
import { Button } from 'vant'

const app = createApp()
app.use(Button)

babel.config.js文件：
plugins: [
    ['import', {
      libraryName: 'vant',
      libraryDirectory: 'es',
      style: true
    }, 'vant']
]

console提示：
[Vue warn]: Failed to resolve component: van-button

**Comment by suyuwen1** [comment]
@chenjiahan 
home.vue文件：
```
import { createApp } from 'vue'
import { Button } from 'vant'

const app = createApp()
app.use(Button)
```

babel.config.js文件：
```
plugins: [
['import', {
libraryName: 'vant',
libraryDirectory: 'es',
style: true
}, 'vant']
]
```

console提示：
[Vue warn]: Failed to resolve component: van-button

**Comment by chenjiahan** [comment]
你没挂载到正确的 App 上

**Comment by suyuwen1** [comment]
怎么能正确使用，给个示例吧，谢谢！




| |
suyuwen
邮箱：suyuwen1@126.com
|

Signature is customized by Netease Mail Master

在2020年10月02日 15:07，neverland 写道：

你没挂载到正确的 App 上

**Comment by chenjiahan** [comment]
自己看文档 https://v3.cn.vuejs.org/guide/migration/global-api.html

**Comment by suyuwen1** [comment]
等于没说




| |
suyuwen
邮箱：suyuwen1@126.com
|

Signature is customized by Netease Mail Master

在2020年10月02日 16:50，neverland 写道：

自己看文档 https://v3.cn.vuejs.org/guide/migration/global-api.html

**Comment by liming1515** [comment]
我找到vue3.0按需求引入的方法了  想了解的 541177535@qq.com  联系我

**Comment by hellowrenfei** [comment]
> vant3.0在vue3.0中如何自动按需引入组件
import { Button } from 'vant';
export default {
  components: {
    [Button.name]: Button
  }

**Comment by liming1515** [comment]
我是想把引入的部分单独提取出来 你这样写只能写到mainjs里边------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;hellowrenfei&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月4日(星期一) 晚上8:34
收件人:&nbsp;&quot;youzan/vant&quot;<vant@noreply.github.com&gt;;
抄送:&nbsp;&quot;liming1515&quot;<541177535@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] vant3.0在vue3.0中如何自动按需引入组件 (#7290)

**Comment by trtst** [comment]
> 我是想把引入的部分单独提取出来 你这样写只能写到mainjs里边------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;hellowrenfei&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月4日(星期一) 晚上8:34 收件人:&nbsp;&quot;youzan/vant&quot;<vant@noreply.github.com&gt;; 抄送:&nbsp;&quot;liming1515&quot;<541177535@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [youzan/vant] vant3.0在vue3.0中如何自动按需引入组件 (#7290)

所以，您解决了这个问题了麽？   我也是想的一样提出来。

**Comment by liming1515** [comment]
解决了







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 上午10:24
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"别看~我有兄弟^ω^ "<541177535@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] vant3.0在vue3.0中如何自动按需引入组件 (#7290)





  
我是想把引入的部分单独提取出来 你这样写只能写到mainjs里边------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"hellowrenfei"<notifications@github.com&gt; 发送时间:&nbsp;2021年1月4日(星期一) 晚上8:34 收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;; 抄送:&nbsp;"liming1515"<541177535@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [youzan/vant] vant3.0在vue3.0中如何自动按需引入组件 (#7290)
  
所以，您解决了这个问题了麽？   我也是想的一样提出来。

**Comment by trtst** [comment]
能知道 您是如何解决的麽？     会像2.x提取引入那样的麽？  谢谢~

**Comment by liming1515** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "别看~我有兄弟^ω^ "                                                                                    <541177535@qq.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 下午5:13
收件人:&nbsp;"刘亚辉"<1019049568@qq.com&gt;;

主题:&nbsp;回复：



 设置了一个 公共的 引入 vue的js文件&nbsp; 然后再把

app 在main.js引入

在按需引入的文件也引入app







------------------ 原始邮件 ------------------
发件人: "刘亚辉"<1019049568@qq.com&gt;; 
发送时间: 2021年1月14日(星期四) 下午5:03
收件人: "别看~我有兄弟^ω^ "<541177535@qq.com&gt;; 
主题: 



请问下 vue3.0的按需导入，怎么弄的，&nbsp; 告知之一下可以吗？

**Comment by trtst** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "别看~我有兄弟^ω^ " <541177535@qq.com&gt;; 发送时间:&nbsp;2021年1月14日(星期四) 下午5:13 收件人:&nbsp;"刘亚辉"<1019049568@qq.com&gt;; 主题:&nbsp;回复： 设置了一个 公共的 引入 vue的js文件&nbsp; 然后再把 app 在main.js引入 在按需引入的文件也引入app
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "刘亚辉"<1019049568@qq.com&gt;; 发送时间: 2021年1月14日(星期四) 下午5:03 收件人: "别看~我有兄弟^ω^ "<541177535@qq.com&gt;; 主题: 请问下 vue3.0的按需导入，怎么弄的，&nbsp; 告知之一下可以吗？

thx~   可以了！

**Comment by davidweining2333** [comment]
> > vant3.0在vue3.0中如何自动按需引入组件
> > import { Button } from 'vant';
> > export default {
> > components: {
> > [Button.name]: Button
> > }
> > }

牛皮，这才是正解，其实报错也很明显了，没有name属性，现在组件的调用van-，如果直接{Button}明显name不对， {[Button.name]: Button }这种配置是oK的，这样配置省去了use，赞，看了这么多，终于找到靠谱的
