### ISSUE TITLE
vue3.0使用vant的tab组件，会报出警告

### ISSUE THREAD

**Issue by lehui521** [youzan/vant#7295]
[Vue warn]: A plugin must either be a function or an object with an "install" function.
[Vue warn]: Property "inited" was accessed during render but is not defined on instance. 
  at <VanTab title="标签 1" > 
  at <VanTabs count=0 animated=false duration=0.3  ... > 
  at <VanTabs active=1 onUpdate:active=fn color="#1989fa"  ... > 
  at <Order onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
[Vue warn]: Property "stickyFixed" was accessed during render but is not defined on instance. 
  at <VanTab title="标签 1" > 
  at <VanTabs count=0 animated=false duration=0.3  ... > 
  at <VanTabs active=1 onUpdate:active=fn color="#1989fa"  ... > 
  at <Order onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
[Vue warn]: Property "inited" was accessed during render but is not defined on instance. 
  at <VanTab title="标签 1" > 
  at <VanTabs count=0 animated=false duration=0.3  ... > 
  at <VanTabs active=1 onUpdate:active=fn color="#1989fa"  ... > 
  at <Order onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

**Comment by lehui521** [comment]
`vue
<template>
  <pay-nav-bar title="配送自提订单" back>
    <template v-slot:right>
      <span class="search">检索</span>
    </template>
  </pay-nav-bar>
  <van-tabs v-model:active="tabActive" color="#1989fa" sticky>
    <van-tab title="标签 1"></van-tab>
    <van-tab title="标签 2"></van-tab>
    <van-tab title="标签 3"></van-tab>
    <van-tab title="标签 4"></van-tab>
  </van-tabs>
</template>
<script>
import {ref} from "vue"
import PayNavBar from "@/components/nav-bar";
import { Tab, Tabs, Popup } from "vant";
export default {
  components: {
    "pay-nav-bar": PayNavBar,
    "van-tabs": Tabs,
    "van-tab": Tab,
  },
  setup() {
    const tabActive = ref(1);
    return {
      tabActive,
    };
  },
};
</script>
<style lang="scss" scoped>
.search {
  color: $blue;
  font-size: 15px;
}
</style>

`

**Comment by lehui521** [comment]
`
<template>
  <pay-nav-bar title="配送自提订单" back>
    <template v-slot:right>
      <span class="search">检索</span>
    </template>
  </pay-nav-bar>
  <van-tabs v-model:active="tabActive" color="#1989fa" sticky>
    <van-tab title="标签 1"></van-tab>
    <van-tab title="标签 2"></van-tab>
    <van-tab title="标签 3"></van-tab>
    <van-tab title="标签 4"></van-tab>
  </van-tabs>
</template>
<script>
import {ref} from "vue"
import PayNavBar from "@/components/nav-bar";
import { Tab, Tabs, Popup } from "vant";
export default {
  components: {
    "pay-nav-bar": PayNavBar,
    "van-tabs": Tabs,
    "van-tab": Tab,
  },
  setup() {
    const tabActive = ref(1);
    return {
      tabActive,
    };
  },
};
</script>
<style lang="scss" scoped>
.search {
  color: $blue;
  font-size: 15px;
}
</style>

`

**Comment by lehui521** [comment]
`
<template>
  <pay-nav-bar title="配送自提订单" back>
    <template v-slot:right>
      <span class="search">检索</span>
    </template>
  </pay-nav-bar>
  <van-tabs v-model:active="tabActive" color="#1989fa" sticky>
    <van-tab title="标签 1"></van-tab>
    <van-tab title="标签 2"></van-tab>
    <van-tab title="标签 3"></van-tab>
    <van-tab title="标签 4"></van-tab>
  </van-tabs>
</template>
`
`
import {ref} from "vue"
import PayNavBar from "@/components/nav-bar";
import { Tab, Tabs, Popup } from "vant";
export default {
  components: {
    "pay-nav-bar": PayNavBar,
    "van-tabs": Tabs,
    "van-tab": Tab,
  },
  setup() {
    const tabActive = ref(1);
    return {
      tabActive,
    };
  },
};
`

**Comment by lehui521** [comment]
[https://xfc-jh.oss-cn-beijing.aliyuncs.com/bug/0a03cab2ca78deeaa5ffc1211a6d8bb.png](url)

**Comment by lehui521** [comment]
[](https://xfc-jh.oss-cn-beijing.aliyuncs.com/bug/0a03cab2ca78deeaa5ffc1211a6d8bb.png)

**Comment by lehui521** [comment]
![Uploading 0a03cab2ca78deeaa5ffc1211a6d8bb.png…]()

**Comment by lehui521** [comment]
![0a03cab2ca78deeaa5ffc1211a6d8bb](https://user-images.githubusercontent.com/34447721/95413946-4939cd00-095f-11eb-96cf-0c0d31c4888e.png)

**Comment by chenjiahan** [comment]
这个问题已经修复了，可以升级 3.0.0-beta.3 试下

**Comment by figtherfastest** [comment]
我现在是用的是 3.0.0-beta.5，这个问题还在（在全局引入的情况下）

**Comment by chenjiahan** [comment]
@figtherfastest 可以打开 node_modules/vant/package.json 确认下版本
