### ISSUE TITLE
建议-业务组件包含商品详情-订单详情-首页

### ISSUE THREAD

**Issue by wangjia2016** [youzan/vant#7299]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
建议-业务组件包含
1、商品详情
2、订单详情
3、首页
4、商品列表
5、订单列表

**Comment by chenjiahan** [comment]
没有计划提供呢
