### ISSUE TITLE
Collapse 还是不能用

### ISSUE THREAD

**Issue by a851870** [youzan/vant#730]
Vue.use(Swipe).use(SwipeItem).use(Tab).use(Tabs).use(Collapse).use(Cell).use(CellGroup);
我按需使用了Collapse ,结果Collapse和cell的也是都不行了,昨天没更新vant的时候cell的样式是有的
![tim 20180319235714](https://user-images.githubusercontent.com/22281806/37606891-8b17f4b8-2bd1-11e8-9ef3-c9e75c28758c.png)
![tim 20180319235721](https://user-images.githubusercontent.com/22281806/37606901-92138f16-2bd1-11e8-92c1-236cd38caaee.png)

**Comment by chenjiahan** [comment]
CollapseItem 组件也是需要注册的，抱歉文档中遗漏了，我们会在后续补齐

```js
import { Collapse, CollapseItem } from 'vant';

Vue.use(Collapse).use(CollapseItem);
```

**Comment by a851870** [comment]
![tim 20180320000623](https://user-images.githubusercontent.com/22281806/37607280-955a86f6-2bd2-11e8-8d18-c24475596cf3.png)
还是不可以

**Comment by chenjiahan** [comment]
请确认下 v-model 的传值是否正确

**Comment by a851870** [comment]
没有报错了,但是没有样式出来
![tim 20180320001857](https://user-images.githubusercontent.com/22281806/37607992-513e0f18-2bd4-11e8-8143-9f673f40d5ad.png)

**Comment by chenjiahan** [comment]
你使用的组件引入方式是？ 可以看下组件样式是否正确引入了

**Comment by a851870** [comment]
我在main.js引用的 Swipe和Tab的样式是正常的
昨天 vant 的0.12.14版本用的cell的样式是可以的,今天更新后就没有了
import { Swipe, SwipeItem, Tab, Tabs, Cell, CellGroup, Collapse,CollapseItem } from 'vant';
Vue.use(Swipe).use(SwipeItem).use(Tab).use(Tabs).use(Collapse).use(CollapseItem).use(Cell).use(CellGroup);

**Comment by a851870** [comment]
我更新下的lib\cell\style目录中的index.js中只有require('../../vant-css/base.css');
于是我添加了require('../../vant-css/cell.css');有样式了,但是cell和collapse的图标(就是icon的箭头),而且也collapse点击也没有折叠效果

**Comment by chenjiahan** [comment]
@a851870 base.css 中包含了 cell.css，所以不会出现 cell 样式未引入的问题。建议你重新编译试下

**Comment by a851870** [comment]
可以用了,谢谢你的帮助
今天早上我用cnpm重新安装vant后了,而且collapse点击也没有折叠效果是因为我在父元素中有添加event.preventDefault() 语句,导致没有效果,抱歉呢,给你添加了这么多麻烦

**Comment by chenjiahan** [comment]
客气~ 能解决问题就好
