### ISSUE TITLE
v1.x版本地址无法访问

### ISSUE THREAD

**Issue by seechangan** [youzan/vant#7301]
设备 / 浏览器
chrome  V86.0.4209.2

Vant 版本
^1.3.10

Vue 版本
^2.5.17

重现链接
https://vant-contrib.gitee.io/vant/1.x/

描述问题
官网右上角版本下拉框v1.x版本地址无法访问

**Comment by chenjiahan** [comment]
我这边是可以访问的，不过 1.x 版本的静态资源是部署在 Github Pages 上的，可能是你所在的区域访问 Github Pages 存在问题，建议翻墙或修改 host 试下

**Comment by seechangan** [comment]
非常感谢！
