### ISSUE TITLE
[Feature Request] 该如何更改input点击清空的图标

### ISSUE THREAD

**Issue by zpcgx** [youzan/vant#7306]
### 这个功能解决了什么问题
无法更改input点击清空的图标  clearable

### 描述您想要的解决方案
跟更改(自定义)头部和尾部图标一样暴露出插槽

### 建议的API是什么样的
跟更改(自定义)头部和尾部图标一样暴露出插槽

**Comment by zpcgx** [comment]
在线等

**Comment by chenjiahan** [comment]
目前不支持替换图标呢，你是什么场景需要更换图标

**Comment by zpcgx** [comment]
> 目前不支持替换图标呢，你是什么场景需要更换图标

唉 公司ui要求图标是个比较大的叉号

**Comment by yuningjiang123** [comment]
> > 目前不支持替换图标呢，你是什么场景需要更换图标
> 
> 唉 公司ui要求图标是个比较大的叉号

把input的clearable禁掉   把你们要求的图标放进尾部插槽   自定义清空事件   这样不就ok了

**Comment by chenjiahan** [comment]
这个需求不是很通用，所以就不加新属性来支持咯，可以用楼上的方法
