### ISSUE TITLE
[Bug Report] Uploader 文件上传会随着拍照数量的增加而越发卡顿

### ISSUE THREAD

**Issue by Silent-Jude** [youzan/vant#7307]
### 设备 / 浏览器
安卓手机

### Vant 版本
2.10.9

### Vue 版本
2.6.12

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
我使用Uploader做了一个拍照上传的系统，发现不限制拍照梳理的情况下，会越来越卡，甚至拍完照片之后会十秒才显示图片。
于是使用官网例子链接，依然复现该问题。【拍照数量超过5张以后，每多一张照片，卡顿时间增加1秒左右的样子，5张以上照片时特别明显】，希望能够早日优化。
我现在只能使用自己写的上传来解决问题了。。。。

**Comment by aloneZERO** [comment]
应该是展示图片 base64 导致的。现在手机拍一张照片至少4、5M，之前我也发现卡顿，后来压缩图片大小就好了

**Comment by mengerwei521** [comment]
:after-read="afterRead" ，中file为啥是{}，如果是{}，那示例写的file.type,那里来的

**Comment by W23mq** [comment]
> :after-read="afterRead" ，中file为啥是{}，如果是{}，那示例写的file.type,那里来的
    这个问题解决了没，我也是 ，在手机端是file为空，但是再pc上file可以拿到

**Comment by chenjiahan** [comment]
已在 2.12.36 版本优化 Uploader 中 ImagePreview 卡顿的问题
