### ISSUE TITLE
网络问题

### ISSUE THREAD

**Issue by DonyFang** [youzan/vant#7310]
使用了Vant 中的Field组件，在有网络情况下设置 right-icon="arrow"。显示正常，在内网环境下（不可防问互联网）情况下right-icon 显示出问题，是必须要在有网络的环境下吗？
<van-field
    v-model="value1"
    label="文本"
    right-icon="arrow"
    placeholder="显示图标"
  />

**Comment by chenjiahan** [comment]
可以使用本地的字体文件，参见 https://youzan.github.io/vant/#/zh-CN/icon#shi-yong-ben-di-zi-ti-wen-jian

**Comment by DonyFang** [comment]
你给的网址 https://youzan.github.io/vant/#/zh-CN/icon#shi-yong-ben-di-zi-ti-wen-jian访问不了啊，而且这个是图片问题和本地字体文件有啥关系啊

**Comment by chenjiahan** [comment]
Vant 里的图标是通过 iconfont 实现的
