### ISSUE TITLE
[Bug Report] 路由跳转时，List的check方法会被意外触发

### ISSUE THREAD

**Issue by mirari** [youzan/vant#7311]
### 设备 / 浏览器
Windows 10 / Chrome

### Vant 版本
2.10.9

### Vue 版本
2.6.12

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-4efet" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-4efet</a>

### 描述问题
我希望List组件不要在mounted时自动触发check方法进行查询操作，而由父节点来控制，所以按照文档，设置了`:immediate-check="false"`。
但实际使用时发现，check方法仍然被执行了，而且Call Stack中看不到上级调用者。通过进一步调试确认，这个check方法不是由List组件的mounted里执行的，而是mixins里的以下这段代码触发的：
```
bind(this.scroller, 'scroll', this.check);
```

具体的行为表现为：
- SPA页面路由跳转时，如果上一个页面滚动到了某个位置，这时候跳转到带有List的新页面时，就会触发check查询。
- 如果先将上一个页面的滚动条回到顶部，再跳转到List页面，就不会触发check。

也就是说，路由跳转过程中，因为新页面的长度等关系导致List组件的this.scroller(我这里就是指向window)触发了scroll事件，导致check方法被意外执行。

我试过在路由上加了scrollBehavior，让页面跳转时总是回到顶部，但window的scoll事件仍然会被触发。

**Comment by chenjiahan** [comment]
这个没法避免呢，只要 scroll 事件被触发了，就一定会触发 List 的检测。

可以考虑在 List 上添加 v-if，或者在页面跳转时把 finished 状态设置为 true

**Comment by mirari** [comment]
搜了下这个问题很普遍，相当于immediate-check这个属性没有起到预期的作用，建议在文档里补充描述一下并提供规避方法。
