### ISSUE TITLE
[Bug Report] Image组件，同一张图片会请求两次。

### ISSUE THREAD

**Issue by ZhenYu-Lin** [youzan/vant#7312]
### 设备 / 浏览器
微信开发者工具

### Vant 版本
2.10.9

### Vue 版本
2.6.10

### 重现链接
<a href="https://www.mroyewubiji.com/about" target="_blank">https://www.mroyewubiji.com/about</a>

### 描述问题
同一张图片会请求两次。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5761
