### ISSUE TITLE
[Feature Request] Sku可以控制是否显示规格图片吗

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#7316]
### 这个功能解决了什么问题
大图模式下没有规格图片会这样
![image](https://user-images.githubusercontent.com/38392315/95810815-6d712180-0d44-11eb-898a-adcc5ff98192.png)

### 描述您想要的解决方案
sku中，和largeImageMode同一级添加一个showImage字段

### 建议的API是什么样的
showImage：Boolean

**Comment by chenjiahan** [comment]
大图模式下是必须要有规格图片的，如果没图片，建议不要开启大图模式
