### ISSUE TITLE
Form表单中随意一个van-button点击会默认触发submit

### ISSUE THREAD

**Issue by JohnGene** [youzan/vant#7319]
代码如下：
&lt;van-form @submit=&quot;onSubmit&quot;&gt;
    &lt;van-button round  block  type=&quot;info&quot;  @click=&quot;calculateAllData&quot; &gt;  计算  &lt;/van-button&gt;
    &lt;van-button  round  block type=&quot;info&quot; native-type=&quot;submit&quot; &gt; 保存 &lt;/van-button&gt;
&lt;/van-form&gt;

这两个按钮点击都会触发onSubmit事件

其中计算的那个按钮生成的html如下：
&lt;div class=&quot;bot_btn&quot;&gt;&lt;button class=&quot;van-button van-button--info van-button--normal van-button--block van-button--round&quot;&gt;&lt;div class=&quot;van-button__content&quot;&gt;&lt;span class=&quot;van-button__text&quot;&gt;计算&lt;/span&gt;&lt;/div&gt;&lt;/button&gt;&lt;/div&gt;

通过百度发现一个问题：button中不带有type属性会默认触发Form表单的submit事件....

**Comment by kooriookami** [comment]
在Vant 3.x 版本中，native-type 的默认值由 submit 调整为 button，2.x 还是默认触发 submit的。

**Comment by JohnGene** [comment]
好的懂了
