### ISSUE TITLE
pick时间能否加上分的参数设置

### ISSUE THREAD

**Issue by nikezhenji86** [youzan/vant#732]
目前pick时间类型只能设置小时，不能设置分钟

**Comment by junk123321** [comment]
datetimepicker建议加上单位，目前是类似于2018 03 20 15 30的样式，数字多了不直观，如果加上单位显示为2018年03月20日 15点30分，那就太好了

**Comment by chenjiahan** [comment]
感谢反馈，我们后续会对 DatetimePicker 做一波优化，支持更灵活的配置

**Comment by CandiJoke** [comment]
iphoneX ，DatetimePicker时间设置为new Date('yyyy-MM-dd hh:mm') 将无法成功唤起时间控件，设置为 new Date('yyyy-MM-dd')可以

**Comment by CandiJoke** [comment]
iphoneX ，DatetimePicker时间设置为new Date('yyyy-MM-dd hh:mm') 将无法成功唤起时间控件，设置为 new Date('yyyy-MM-dd')可以

**Comment by chenjiahan** [comment]
目前已支持分钟的选择
