### ISSUE TITLE
[Bug Report] 文档小错误

### ISSUE THREAD

**Issue by wman0211** [youzan/vant#7320]
### 设备 / 浏览器
PC

### Vant 版本
2.10.9

### Vue 版本
3.0.0

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/calendar#range-props" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/calendar#range-props</a>

### 描述问题
https://vant-contrib.gitee.io/vant/#/zh-CN/calendar#range-props
文档有个单词应该错了
allow-same-day v2.5.6 	是否允许日期范围的起止时间为同一天 	boolean 	fasle

"fasle"应为"false"

**Comment by chenjiahan** [comment]
欢迎提 PR 来修复喔
