### ISSUE TITLE
[Bug Report] 如何使用Tabs标签中的自定义标签图标在点击时出现

### ISSUE THREAD

**Issue by register2019** [youzan/vant#7322]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.9

### Vue 版本
2.6.12

### 重现链接
<a href="https://m.ctrip.com/webapp/you/gspoi/sight/2/762.html?seo=0&isHideNavBar=YES&from=https%3A%2F%2Fm.ctrip.com%2Fwebapp%2Fyou%2Fplace%2F2.html%3Fishideheader%3Dtrue%26secondwakeup%3Dtrue%26dpclickjump%3Dtrue%26allianceid%3D564348%26sid%3D1435827%26from%3Dhttps%253A%252F%252Fm.ctrip.com%252Fhtml5%252F" target="_blank">https://m.ctrip.com/webapp/you/gspoi/sight/2/762.html?seo=0&isHideNavBar=YES&from=https%3A%2F%2Fm.ctrip.com%2Fwebapp%2Fyou%2Fplace%2F2.html%3Fishideheader%3Dtrue%26secondwakeup%3Dtrue%26dpclickjump%3Dtrue%26allianceid%3D564348%26sid%3D1435827%26from%3Dhttps%253A%252F%252Fm.ctrip.com%252Fhtml5%252F</a>

### 描述问题
像链接中的预定、玩法、点评这一行一样 默认图标在第一个上 点击其他Tab 图标出现在当前点击的tab上 其他的tab上不显示图标

**Comment by chenjiahan** [comment]
在 van-icon 上加一个 `v-if="active === index"` 判断就行

```html
<van-tabs v-model="active">
  <van-tab v-for="index in 2" :key="index">
    <template #title> <van-icon v-if="active === index" name="more-o" />选项 </template>
    内容 {{ index }}
  </van-tab>
</van-tabs>
```
