### ISSUE TITLE
Vue - vant 的 Picker选择器，级联选择 （使用 columns 的 children 字段可以实现选项级联的效果（从 2.4.5 版本开始支持）如何设置默认值，

### ISSUE THREAD

**Issue by snail714** [youzan/vant#7324]
以官网例子为例：
 columns: [
        {
          text: '浙江',
          children: [
            {
              text: '杭州',
              children: [{ text: '西湖区' }, { text: '余杭区' }],
            },
            {
              text: '温州',
              children: [{ text: '鹿城区' }, { text: '瓯海区' }],
            },
          ],
        },
        {
          text: '福建',
          children: [
            {
              text: '福州',
              children: [{ text: '鼓楼区' }, { text: '台江区' }],
            },
            {
              text: '厦门',
              children: [{ text: '思明区' }, { text: '海沧区' }],
            },
          ],
        },
      ],，
没有支持picker多级级联的时候设置默认选中值。 default-index只能设置一个数字

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
