### ISSUE TITLE
[Feature Request] Tab 标签页添加阴影功能

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#7325]
### 这个功能解决了什么问题
像这样
![image](https://user-images.githubusercontent.com/38392315/95947669-b4811480-0e21-11eb-8ef3-e7d3af938eeb.png)

另外希望下拉菜单的阴影也能手动控制

### 描述您想要的解决方案
添加一个属性，控制阴影的开关

### 建议的API是什么样的
shadow: Boolean

**Comment by chenjiahan** [comment]
暂时没有计划添加属性来调整阴影样式，你可以直接通过 CSS 覆盖样式来调整
