### ISSUE TITLE
[Bug Report] Tag swipe-threshold 属性无效

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#7326]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.9

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-c9h7e" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-c9h7e</a>

### 描述问题
demo中swipe-threshold设置3，并没有用。

**Comment by chenjiahan** [comment]
swipe-threshold 的描述不太准确，这个属性是在标签数量超过阈值且总宽度超过标签栏宽度时开始进入横向滚动模式，具体能展示几个标签，还是由标签宽度决定的。

后续会更正下文档
