### ISSUE TITLE
Uploader 文件上传-自定义预览样式-自定义覆盖在预览区域上方的内容preview-cover的取值使用#preview-cover="{ file }"无效

### ISSUE THREAD

**Issue by RidingACodeToStray** [youzan/vant#7327]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

使用#preview-cover="{ file }"无效，使用#preview-cover="file"有效
`<van-uploader v-model="fileList">
  <template #preview-cover="file">
    <div class="preview-cover van-ellipsis">{{ file.name }}</div>
  </template>
</van-uploader>`

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
