### ISSUE TITLE
[Bug Report] Icon 两个图标问题

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#7328]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0-beta.3

### Vue 版本
3.0.0

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/icon" target="_blank">https://youzan.github.io/vant/#/zh-CN/icon</a>

### 描述问题
cash-back-record和after-sale的￥符号中间空白
![image](https://user-images.githubusercontent.com/38392315/95950939-18a6d700-0e28-11eb-9aa5-f860406a8c19.png)

**Comment by chenjiahan** [comment]
在真机上显示不完整，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.10.10 版本修复
