### ISSUE TITLE
[Bug Report] Calendar does not show current month with larger screen sizes 

### ISSUE THREAD

**Issue by Muffinman** [youzan/vant#7329]
### Device / Browser
Chrome Desktop

### Vant Version
2.10.9

### Vue Version
2.6.11

### Reproduction Link
<a href="https://codesandbox.io/s/vant-calendar-issue-5meu0" target="_blank">https://codesandbox.io/s/vant-calendar-issue-5meu0</a>

### Describe the bug
When opening the calendar, it will not show the current month if the browser window height is above 1120px.

At a window height below 1120px it works as expected.

**Comment by Muffinman** [comment]
Below 1120px:

![Screenshot 2020-10-14 at 11 18 22](https://user-images.githubusercontent.com/1319568/95976178-0f5d4080-0e0f-11eb-9fde-91a1c8c5b090.png)

Above 1120px:

![Screenshot 2020-10-14 at 11 18 33](https://user-images.githubusercontent.com/1319568/95976204-15ebb800-0e0f-11eb-84dc-1ece007ad5ff.png)

**Comment by chenjiahan** [comment]
Will be fixed in the next version 👌

**Comment by JunIce** [comment]
@chenjiahan  这个问题我看是代码中是初始化时只渲染上个月，当前月和下个月，因为Month是lazyRender，初始化时不能获取到month-body高度，所以请教下修改方向
`
months.forEach((month, index) => {
        month.visible = index >= visibleIndex - 1 && index <= visibleIndex + 1;
});
`

**Comment by chenjiahan** [comment]
In the current version, you can disable the lazy-render prop to avoid this problem

```html
<van-calendar :lazy-render="false" />
```

In the next version, we will adjust the logic of lazy render to avoid this issue.

**Comment by chenjiahan** [comment]
Fixed in version 2.10.10.
