### ISSUE TITLE
上传组件

### ISSUE THREAD

**Issue by songxianling** [youzan/vant#733]
上传组件能不能加上进度条；上传个数的限制；也没有action的属性；要上传到的路径怎么写啊；还有当前已经上传的展示；哈哈

**Comment by chenjiahan** [comment]
需求好多哈哈~
上传组件现在功能比较纯粹，仅仅是对原生 input 的一个封装。后续我们会逐渐丰富这个组件的功能。
像上传路径、已上传的展示之类的功能，都是可以自己去灵活搭配的，组件内不会封装
