### ISSUE TITLE
van-tabs的粘性布局sticky属性无效

### ISSUE THREAD

**Issue by ofooo** [youzan/vant#7334]
### 设备 / 浏览器
windows10、crhome版本 86.0.4240.75

### Vant 版本
3.0.0-beta.3

### Vue 版本
2.6.12

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/tab" target="_blank">https://youzan.github.io/vant/#/zh-CN/tab</a>

### 描述问题
官方说明文档里的van-tabs的粘性布局sticky属性无效
往上滑界面，粘性tabs会停留一小段距离，再往上滑tabs就上去了

滑到最底下的时候“标签栏滚动”tabs能够实现真正的吸顶效果。
请检查一下普通的吸顶为什么失效了？

**Comment by ofooo** [comment]
滑动之前
![image](https://user-images.githubusercontent.com/6046155/96036989-d3ba8900-0e97-11eb-9a0c-6175cd3fedff.png)

一小段距离内能吸顶
![image](https://user-images.githubusercontent.com/6046155/96037050-e634c280-0e97-11eb-8e9a-eef82e350985.png)

继续往上滑动，然后吸顶效果就失效了
![image](https://user-images.githubusercontent.com/6046155/96037130-ffd60a00-0e97-11eb-8cd2-e45c47c2186c.png)

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/7333

**Comment by jiangyi215** [comment]
请问下这个问题是解决了才关闭的？` <van-tabs sticky>
        <van-tab v-for="cl in classify" :key="`cl-${cl.id}`" :title="cl.name">
          内容 {{ cl.name }}
        </van-tab>
      </van-tabs>`
直接这样使用，没有效果，放在<van-sticky></van-sticky>里可以吸顶。。。没看懂怎么解决的。。

**Comment by hah159** [comment]
好家夥，四年前的問題我現在來看也是沒解決方案的嗎
