### ISSUE TITLE
[Bug Report] [Uploader 文件上传-自定义预览样式-自定义覆盖在预览区域上方的内容]无效

### ISSUE THREAD

**Issue by RidingACodeToStray** [youzan/vant#7335]
### 设备 / 浏览器
谷歌浏览器PC

### Vant 版本
2.10.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/dg78p" target="_blank">https://codesandbox.io/s/dg78p</a>

### 描述问题
文档上的使用#preview-cover="{ file }"无效，改成#preview-cover="file"有效

**Comment by chenjiahan** [comment]
这个不是 Bug，preview-cover 传入的参数是 fileList 中的单个 item，所以你的 fileList 列表要按照标准的结构来传入：

```js
export default {
  data() {
    return {
      fileList: [
        {
          url: "https://img.yzcdn.cn/vant/leaf.jpg",
          // 这里加个 file
          file: {
            name: "刘昊然",
          }
        },
      ],
    };
  },
};
```
