### ISSUE TITLE
建议 所有组件都可以自定义颜色，去覆盖颜色，特别是点击的颜色超级男更改

### ISSUE THREAD

**Issue by 1501104069** [youzan/vant#7337]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持呢，建议通过 CSS 覆盖
