### ISSUE TITLE
[Bug Report] VanImage 无法加载手机里面绝对路径图片

### ISSUE THREAD

**Issue by chhyu** [youzan/vant#7338]
### 设备 / 浏览器
android 7.1.1

### Vant 版本
3.0.0-beta.3

### Vue 版本
3.0.0

### 重现链接
<a href="http://www.baidu.com" target="_blank">http://www.baidu.com</a>

### 描述问题
使用相机拍照后返回照片的绝对途径，VanImage无法加载

**Comment by chenjiahan** [comment]
原生的 img 标签可以加载吗？
