### ISSUE TITLE
[Bug Report] Calendar 设置 default-date 后，第一次显示面版，无法滚动到默认值所在位置

### ISSUE THREAD

**Issue by ken1987** [youzan/vant#7339]
### 设备 / 浏览器
chrome v80

### Vant 版本
2.10.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-foeuu?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-foeuu?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
Calendar 设置 default-date ，并且不是今日。
1. 第一次显示面版，无法滚动到默认值所在位置
2. 关闭后，第二次显示可以

**Comment by ken1987** [comment]
第一次执行 scrollIntoView 方法时，this.refs.body 对应的 DOM 还未渲染

**Comment by chenjiahan** [comment]
这个问题已经修复了的，可以升级 2.10.9 版本试下
