### ISSUE TITLE
van-list， ios下滑动加载数据时，偶尔会出现页面重载刷新问题； 有遇到的嘛？

### ISSUE THREAD

**Issue by Jensonhui** [youzan/vant#7340]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
