### ISSUE TITLE
[Bug Report] popup在IOS的兼容问题

### ISSUE THREAD

**Issue by zhongchuihan** [youzan/vant#7341]
### 设备 / 浏览器
IOS大部分

### Vant 版本
3.0.0-beta.3

### Vue 版本
3.0.0

### 重现链接
<a href="http://vant-contrib.gitee.io/-CN（没有链接，只有一张图片）" target="_blank">http://vant-contrib.gitee.io/-CN（没有链接，，本来想给张图片的）</a>

### 描述问题
popup做的H5页面嵌入在IOS手机APP，，，因为IOS底部自带的功能栏，所以被挡住了一部分的内容，，
![image](https://user-images.githubusercontent.com/48168268/96122904-b8e22600-0f24-11eb-800e-5da0f87accbb.png)

**Comment by chenjiahan** [comment]
这个是微信 WebView 的底部功能栏把，属于微信的 bug，从组件层面没法兼容喔
