### ISSUE TITLE
[Bug Report] field输入框label-align的问题

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#7343]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.9

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-89wp2" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-89wp2</a>

### 描述问题
当label-align为left时候，能一行显示下6个字，切换为right只能显示5位
![image](https://user-images.githubusercontent.com/38392315/96201343-e6fc5000-0f8e-11eb-92f1-faef7b8b967d.png)
![image](https://user-images.githubusercontent.com/38392315/96201351-e9f74080-0f8e-11eb-9112-b97ebd6a104c.png)

**Comment by yuningjiang123** [comment]
遇到这种问题我一般直接加个white-space: nowrap解决

**Comment by chenjiahan** [comment]
确实有问题，多了 16px 的 padding，下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.10.10 版本修复
