### ISSUE TITLE
[Bug Report] Cell title 颜色和 Field label 颜色不一致

### ISSUE THREAD

**Issue by onlyling** [youzan/vant#7345]
### 设备 / 浏览器
all

### Vant 版本
2.10.9

### Vue 版本
2.6.12

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/field" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/field</a>

### 描述问题
Field 基于 Cell 实现的，两者大体上是一样的，如果混用，现在就会出现左侧标题/文字颜色不同；

```less
@text-color: @gray-8;
@cell-text-color: @text-color;
@field-label-color: @gray-7;
```

是有意做这样的区分？

**Comment by chenjiahan** [comment]
目前设计规范里是这样的，已反馈给设计同学

**Comment by chenjiahan** [comment]
跟设计同学沟通了下，这块色值暂时没有调整的计划，可以根据实际场景自行覆盖样式喔
