### ISSUE TITLE
[Bug Report] 使用日历组件报type为undefined的错

### ISSUE THREAD

**Issue by cuiqi423** [youzan/vant#7346]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
3.0.0-beta.3

### Vue 版本
3.0.1

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater" target="_blank">https://youzan.github.io/vant-issue-generater</a>

### 描述问题
我使用van-calendar组件   代码如下
<van-calendar
        title="请选择时间" 
        :type="range" 
       :formatter="formatter"
        :poppable="false"
        :show-confirm="false"
      />
报错显示
 Error in render: "TypeError: Cannot read property 'type' of undefined"

found in

---> <VanCalendarMonth>
       <VanCalendar>
         <SendInterview> at src/views/teacher/personalCenter/ResumeManagement/SendInterview.vue
           <App> at src/App.vue
             <Root>
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'type' of undefined

**Comment by chenjiahan** [comment]
`:type="range" ` 前面的冒号去掉。
