### ISSUE TITLE
List 列表加载更多问题

### ISSUE THREAD

**Issue by luchuan163** [youzan/vant#735]
在better-scroll里面使用List 列表的时候，滚动到底部不能加载更多

**Comment by chenjiahan** [comment]
@luchuan163 List 是基于原生滚动条的，与 better-scroll 不兼容喔

**Comment by luchuan163** [comment]
那有没有办法解决？？？

**Comment by chenjiahan** [comment]
@luchuan163 不使用 better-scroll 即可

**Comment by qinxm** [comment]
新安装的包里没有List组件
