### ISSUE TITLE
[Bug Report] 最新版本v2.10.9新增特性‘Tab: 当标签页内容为空时，不再渲染空的 van-tab-pane 节点’，当部分空van-tab组合使用animated时会有问题

### ISSUE THREAD

**Issue by suwenwin** [youzan/vant#7353]
### 设备 / 浏览器
所有

### Vant 版本
2.10.9

### Vue 版本
2.6.1

### 重现链接
<a href="http://suwenwin.com/" target="_blank">http://suwenwin.com/</a>

### 描述问题

 最新版本v2.10.9新增特性‘Tab: 当标签页内容为空时，不再渲染空的 van-tab-pane 节点’
 当部分tab为空并使用animated动画时， vant不会渲染空tab，但是动画会计算此tab的位置，导致切换过程的tab错位问题，
如上可复现地址，  当切换到tab 2时，由于tab1为空所以不渲染，但是动画依然计算了tab1的位置，所以对tab2应用transform: translate(-100%)，导致tab2错位不显示。

**Comment by chenjiahan** [comment]
确实存在这个问题，下个版本会调整下，设置 animated 时保持之前的逻辑，渲染一个空节点

**Comment by chenjiahan** [comment]
已在 2.10.10 版本修复
