### ISSUE TITLE
唯一的遗憾是缺少区域滚动组件，建议增加vant-scroll组件。

### ISSUE THREAD

**Issue by zhouj0920** [youzan/vant#7362]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater
   作为一款移动端ui组件库，感觉唯一的遗憾就是少了区域滚动组件，在实际开发中，ios端运用浏览器原生的overflow: scroll滚动的话会卡顿，开发者不得不单独引用像better-scroll等第三方插件,但过程中会有很多与vant的list组件相冲突的地方。希望有朝一日官方能推出自己的区域滚动组件。

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
这个暂时没计划支持呢，平滑滚动可以添加下面的属性

```css
overflow: scroll;
-webkit-overflow-scrolling: touch;
```
