### ISSUE TITLE
van-field 组件怎么不能双向绑定

### ISSUE THREAD

**Issue by pendyliu** [youzan/vant#7363]
van-field 通过V-model绑定一个对象后，再录入数据后，这个控件的值会自动变回去，我只有一个一个控件通过input事件去判断把变化的值赋值给绑定的对象，有没有其它更好的方法，谢谢！

**Comment by CalmHarbin** [comment]
用value传递数据 不用 v-model
获取数据时通过 Form 组件的submit方法去统一获取

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by pendyliu** [comment]
@chenjiahan 好的！下次改进。

**Comment by chenjiahan** [comment]
👍

**Comment by Coder-Star** [comment]
请问最终是怎么解决的

**Comment by Coder-Star** [comment]
> van-field 通过V-model绑定一个对象后，再录入数据后，这个控件的值会自动变回去，我只有一个一个控件通过input事件去判断把变化的值赋值给绑定的对象，有没有其它更好的方法，谢谢！

请问最后是怎么解决的
