### ISSUE TITLE
[Bug Report] safari中van-image设置showloading时dom异常

### ISSUE THREAD

**Issue by 1259549061** [youzan/vant#7365]
### 设备 / 浏览器
safari

### Vant 版本
2.10.10

### Vue 版本
2.6.11

### 重现链接
<a href="https://test-www.onesports.com/basketball/match/fujian-sichuan-pinsheng-whale-2472715755087094" target="_blank">https://test-www.onesports.com/basketball/match/fujian-sichuan-pinsheng-whale-2472715755087094</a>

### 描述问题
safari中使用van-image,在开启loading的时候 ，loading和loading之后的图片dom同时存在, 提供的链接拉到最下面看图片

**Comment by chenjiahan** [comment]
用 iphoneXR 试了下没复现，能提供一下 codesandbox 复现链接吗

https://codesandbox.io/s/m5v3f

**Comment by 1259549061** [comment]
@chenjiahan 可能是在ssr渲染的时候不能开启show-loading
我加了个环境判断图片渲染正常了

**Comment by 1259549061** [comment]
> 用 iphoneXR 试了下没复现，能提供一下 codesandbox 复现链接吗
> 
> https://codesandbox.io/s/m5v3f

**Comment by 1259549061** [comment]
> 用 iphoneXR 试了下没复现，能提供一下 codesandbox 复现链接吗
> 
> https://codesandbox.io/s/m5v3f

可能是在ssr渲染的时候不能开启show-loading
我加了个环境判断图片渲染正常了

**Comment by 1259549061** [comment]
![Pasted Graphic](https://user-images.githubusercontent.com/28998743/96668001-c1a38380-138c-11eb-9146-0ce08a380a72.png)
复现

**Comment by chenjiahan** [comment]
我这边测试的结果是 SSR 时确实会产生一个 loading 节点，但是页面加载完成后就不再存在了。可能是某些特殊情况下直出的 loading 节点没有被正确移除。

loading 节点在 SSR 时是多余的，下个版本会移除掉。

**Comment by chenjiahan** [comment]
恢复了 SSR 期间的 loading 节点，参见：https://github.com/youzan/vant/issues/7721

**Comment by snoobcn** [comment]
好奇这个BUG最终解决的方式是？

**Comment by 1259549061** [comment]
我记得当时vant最新版本不行，后来迭代之后可以了，有一个版本log是有写解决了这个问题了



---原始邮件---
发件人: "snoob(Liu ***@***.***&gt;
发送时间: 2022年4月13日(周三) 晚上8:24
收件人: ***@***.***&gt;;
抄送: "personal ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [youzan/vant] [Bug Report] safari中van-image设置showloading时dom异常 (#7365)




 
好奇这个BUG最终解决的方式是？

**Comment by 1259549061** [comment]
建议showloading别用环境判断，直接在知道加载哪个图片路径之后关了就行



---原始邮件---
发件人: "snoob(Liu ***@***.***&gt;
发送时间: 2022年4月13日(周三) 晚上8:34
收件人: ***@***.***&gt;;
抄送: "personal ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [youzan/vant] [Bug Report] safari中van-image设置showloading时dom异常 (#7365)




 
环境判断关闭show-loading   有警告。。client 和 server 对不上dom
