### ISSUE TITLE
[Bug Report] PasswordInput 密码输入框限制位数失效

### ISSUE THREAD

**Issue by sangjunke** [youzan/vant#7367]
### 设备 / 浏览器
浏览器

### Vant 版本
2.10.10

### Vue 版本
2.6.12

### 重现链接
<a href="https://jsbin.com/halecenoge/edit?html,output" target="_blank">https://jsbin.com/halecenoge/edit?html,output</a>

### 描述问题
PasswordInput 密码输入框默认输入6位，但仍可输入，打印发现绑定值没有限制；自定义长度也失效；需watch监听进行截取

**Comment by chenjiahan** [comment]
你忘了在 NumberKeyboard 上设置 maxlength 属性，参见 https://youzan.github.io/vant/#/zh-CN/number-keyboard#shuang-xiang-bang-ding
