### ISSUE TITLE
下载源码运行报如下错误是为什么？

### ISSUE THREAD

**Issue by huxc** [youzan/vant#7368]
`  Compiled with some errors in 26.30s

 ERROR  Failed to compile with 1 errors                                                                                                                        10:59:17
 error  in ./node_modules/@vant/cli/dist/package-style.less                                                                                                    10:59:17
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'config'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap? }
    at validate (D:\gitDownload\vant-next\vant-next\node_modules\postcss-loader\node_modules\schema-utils\dist\validate.js:104:11)
    at Object.loader (D:\gitDownload\vant-next\vant-next\node_modules\postcss-loader\dist\index.js:43:29)

                                                                                                          10:59:20
TS2345: Argument of type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>' is not assignable to parameter of type 'ComponentPublicInstance<{ replace: boolean; } & { to?: RouteLocation | undefined; url?: string | undefined; }, {}, {}, {}, {}, {}, { 
replace: boolean; } & { to?: RouteLocation | undefined; url?: string | undefined; }, {}, false, ComponentOptionsBase<...>>'.
  Type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>' is not assignable to type '{ $: ComponentInternalInstance; $data: {}; $props: { replace: boolean; } & { to?: RouteLocation | undefined; url?: string | undefined; }; $attrs: Record<...>; ... 9 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; }'.
    Types of property '$props' are incompatible.
      Type '{}' is not assignable to type '{ replace: boolean; } & { to?: RouteLocation | undefined; url?: string | undefined; }'.
        Property 'replace' is missing in type '{}' but required in type '{ replace: boolean; }'.
    32 |   const vm = getCurrentInstance()!.proxy!;
    33 |   return () => {
  > 34 |     route(vm);
       |           ^^
    35 |   };
    36 | }
    37 | 
`

**Comment by chenjiahan** [comment]
是 next 分支吗？我这边试了下是 ok 的，你可以拉取最新的代码重新试一下，记得跑一下 yarn
