### ISSUE TITLE
[Bug Report] 小米手机上传部分区域黑屏

### ISSUE THREAD

**Issue by Nice-C** [youzan/vant#7374]
### 设备 / 浏览器
小米 红米

### Vant 版本
2.10.11-beta.0

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-xvy23?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-xvy23?file=/src/App.vue</a>

### 描述问题
小米手机 拍照上传后 小图黑色 有时候会闪屏黑色 部分区域html代码被遮盖黑色

**Comment by chenjiahan** [comment]
我用小米 10 试了下没复现呢，是不是低端机内存不足，可以在 before-read 中对图片进行压缩，这样性能会好一些

**Comment by Nice-C** [comment]
用手机拍照 点选原图  多上传几张
