### ISSUE TITLE
Vant3.0.0-beta.4+Vue3+Typescript按需加载问题

### ISSUE THREAD

**Issue by xiaoai7904** [youzan/vant#7378]
@作者你好， 在使用vant3.0版本和Vue3+Typescript的按需引入组件

### 源代码
![image](https://user-images.githubusercontent.com/40415469/96715309-92f9cd00-13cd-11eb-8b77-552f73f3499d.png)
### 错误提示
![image](https://user-images.githubusercontent.com/40415469/96715390-b3298c00-13cd-11eb-8532-95506e13682d.png)
### ts-import-plugin配置
![image](https://user-images.githubusercontent.com/40415469/96715519-e835de80-13cd-11eb-8404-42a831df64bc.png)

麻烦作者帮忙解答一下,谢谢

**Comment by chenjiahan** [comment]
这个问题在 3.0.0-alpha.3 版本已经修复了的，建议你再检查下安装的 vant 版本

**Comment by xiaoai7904** [comment]
检查了版本确定是`3.0.0-beta.4`,在main.ts文件可以使用
![image](https://user-images.githubusercontent.com/40415469/96952727-bfbafb00-1519-11eb-9b7a-98c6c9e85251.png)

我在其他组件或者页面里面使用还是会报类型不兼容问题

![image](https://user-images.githubusercontent.com/40415469/96952799-e1b47d80-1519-11eb-9814-f55d570438e9.png)
![image](https://user-images.githubusercontent.com/40415469/96952880-0a3c7780-151a-11eb-9530-47a39647063c.png)

**Comment by xiaoai7904** [comment]
@chenjiahan  你好，我通过`yarn add vant@next`这个方式安装下来是`v3.0.0-beta.4`,
我看官方文档最近一次发布版本是`v3.0.0-beta.3`，是文档还没有更新吗？

**Comment by chenjiahan** [comment]
文档是 beta.4 呀。
