### ISSUE TITLE
「只有一个sku规格值时默认选中」逻辑问题

### ISSUE THREAD

**Issue by Naraku777** [youzan/vant#738]
**What is the current behavior?**

目前，vant/packages/sku/Sku.vue 文件内有逻辑 「只有一个sku规格值时默认选中」，组件初始化的时候会执行这个逻辑，但是没有做一个该 sku 是否可用情况的判断（没有库存），正常来说没有库存的商品应该不予 sku 的选择，但是如果实在想显示一下该产品有什么 sku，且只有一个时会引起这个 bug，具体是该 van-sku-row__item 既不可用也作出了选中的样式。

是否可以提供一下解决方案？或者只能隐藏掉触发弹出 sku 的行为的按钮？

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

有且只有一个 sku 选项，且没库存的情况下

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

vue@2.5
vant@0.12.9

**Comment by w91** [comment]
@Naraku777  vant@1.0.2版本已修复，会先检查库存再决定是否默认选中。

**Comment by w91** [comment]
#752
