### ISSUE TITLE
vant-grid水平无效

### ISSUE THREAD

**Issue by yanquanfu** [youzan/vant#7382]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---
![image](https://user-images.githubusercontent.com/26216899/96730433-bb42f500-13e8-11eb-88fc-44838a0eccbf.png)

代码：

            <van-grid column-num="2"  direction="horizontal" >
              <van-grid-item icon="comment-o" text="打卡详情" ></van-grid-item>
              <van-grid-item icon="share" text="分享" ></van-grid-item>
            </van-grid>

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
direction 是 2.8.2 版本新增的属性，请确认你安装的 vant 版本在 v2.8.2 版本以上

**Comment by yanquanfu** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 晚上10:08
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"哎斯哆嚕"<346859456@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] vant-grid水平无效 (#7382)





 
direction 是 2.8.2 版本新增的属性，请确认你安装的 vant 版本在 v2.8.2 版本以上
