### ISSUE TITLE
[Bug Report] 当actions过多时，action-sheet样式会出现问题

### ISSUE THREAD

**Issue by Middletwo-Kid** [youzan/vant#7385]
## 设备 / 浏览器
所有移动端

### Vant 版本
2.10.11-beta.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-g6c2b?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-g6c2b?file=/src/App.vue</a>

### 描述问题
使用action-sheet组件时，如果action数量过多:
1. 滑动时，超过border-radius的部分在ios系统上没有被隐藏；
2. 若使用了取消按钮，action过多时，取消按钮不是固定在底部的，需要滑动到最下面才会出现。

**Comment by chenjiahan** [comment]
已在 2.10.12 版本修复
