### ISSUE TITLE
[Feature Request] Toast提示的onClose回调改成promise

### ISSUE THREAD

**Issue by greatWeber** [youzan/vant#7388]
### 这个功能解决了什么问题
不喜欢使用回调，平时写的时候都是简写Toast('xxx');但是写回调的时候，要改成 Toast({messsage:'xxx',onClose(){...}}); 感觉很麻烦

### 描述您想要的解决方案
回调改成 primose

### 建议的API是什么样的
Toast('xxx').then(()=>{
  // 关闭后执行
})

**Comment by chenjiahan** [comment]
目前调用 Toast 会 return 组件实例，这个暂时没有计划修改。
