### ISSUE TITLE
vant-tabs 点击切换或者滑动切换操作过快会有闪屏现象

### ISSUE THREAD

**Issue by Clairegirls** [youzan/vant#7391]
### 设备 / 浏览器
移动端（iphone、小米、oppo等）

### Vant 版本
2.10.0

### Vue 版本
2.6.0

### 重现链接
<a href="https://jsbin.com/denadat/edit?html,output" target="_blank">https://jsbin.com/denadat/edit?html,output</a>

### 描述问题
vant-tabs 点击切换或者滑动切换操作过快会有闪屏现象，就是会一直处于来回切换状态直至结束。重现链接只放了大致html结构。

**Comment by chenjiahan** [comment]
麻烦提供有效的重现链接。
