### ISSUE TITLE
van-list组件 自动加载后滚动条会回到头部

### ISSUE THREAD

**Issue by Bendjen** [youzan/vant#7392]
![image](https://user-images.githubusercontent.com/20695625/96855022-c3ee0680-148e-11eb-8d25-9cc92981aea8.png)

![image](https://user-images.githubusercontent.com/20695625/96854464-15e25c80-148e-11eb-862d-35614ce8cde9.png)
onload调用代码如上

每次自动加载后都会回到第一条，要重新向下拉才看得到新的

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by gebilaofan** [comment]
解决了？？？

**Comment by seehuang** [comment]
检查一下组件在上拉加载里面，是不是用了Toast，可能是全局的Toast导致滚动条回到顶部，注释掉应该就可以了。或者自己写一个loading

**Comment by ilaipi** [comment]
貌似跟toast也没啥关系，给外层容器增加个`height: 100%; overflow-y: auto;` 样式，应该就可以解决了
