### ISSUE TITLE
vue3 项目 全局 toast 报错

### ISSUE THREAD

**Issue by laijinxian** [youzan/vant#7393]
vue3 项目中注册全局toast； setup 函数中没有this； 该怎么使用全局$toast

**Comment by chinaliuming123** [comment]
https://youzan.github.io/vant/next/#/zh-CN/toastyin-ru

**Comment by chinaliuming123** [comment]
import { Toast } from 'vant';

**Comment by chinaliuming123** [comment]
vue3哪还有全局的，都写成函数式的了，直接封装好了import引用

**Comment by chenjiahan** [comment]
setup 里需要通过 import 来引入使用。
