### ISSUE TITLE
[Bug Report] Toast forbidClick 禁止背景点击无效

### ISSUE THREAD

**Issue by Mikasa33** [youzan/vant#7395]
### 设备 / 浏览器
Google Chrome 86.0.4240.80

### Vant 版本
3.0.0-beta.4

### Vue 版本
3.0.2

### 重现链接
<a href="https://jsbin.com/beturah/1/edit?html,css,js,console,output" target="_blank">https://jsbin.com/beturah/1/edit?html,css,js,console,output</a>

### 描述问题
如题，依旧可以点击页面中的按钮

**Comment by Mikasa33** [comment]
#7396

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.5 版本修复
