### ISSUE TITLE
[Bug Report] NumberKeyboard身份证号键盘弹出问题

### ISSUE THREAD

**Issue by niping1234** [youzan/vant#7397]
### 设备 / 浏览器
ios 安卓

### Vant 版本
2.9.3

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/late-butterfly-js2tr?file=/src/App.vue" target="_blank">https://codesandbox.io/s/late-butterfly-js2tr?file=/src/App.vue</a>

### 描述问题
vue  H5页面 输入框在页面底部  点击输入框 弹出身份证号键盘 没有将页面顶起来 遮挡输入框

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5493
