### ISSUE TITLE
[Bug Report] 当tabs 组件拥有 animated  || swipeable 属性的时候 tab组件渲染会出问题 

### ISSUE THREAD

**Issue by 810505339** [youzan/vant#7399]
### 设备 / 浏览器
都有

### Vant 版本
3.0.0-beta.5

### Vue 版本
3.0.2

### 重现链接
<a href="https://github.com/810505339/vant3-tsx/blob/master/src/App.tsx" target="_blank">https://github.com/810505339/vant3-tsx/blob/master/src/App.tsx</a>

### 描述问题
子组件setup会同时触发前3个子组件setup  并切换会出现子组件setup 随意触发问题 ，触发不确定

**Comment by chenjiahan** [comment]
1. 设置 animated 后触发前3个子组件的 setup，这个是正常现象，因为要提前渲染左侧和右侧的节点，来保证动画过程是平滑的

2. 切换到第二个 Tab 时，会看到第三个 Tab 的内容被提前初始化了，这个也是跟上面一样的逻辑，为了保证动画顺畅。

**Comment by 810505339** [comment]
但是会频繁触发setup即使已经初始化好,感觉不是提前渲染左侧跟右侧, 当我设置v-model第四个时 触发了所有的setup



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2020年10月26日(星期一) 晚上8:27
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "810505339"<810505339@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] [Bug Report] 当tabs 组件拥有 animated  || swipeable 属性的时候 tab组件渲染会出问题  (#7399)





  
 
设置 animated 后触发前3个子组件的 setup，这个是正常现象，因为要提前渲染左侧和右侧的节点，来保证动画过程是平滑的
 
 
 
切换到第二个 Tab 时，会看到第三个 Tab 的内容被提前初始化了，这个也是跟上面一样的逻辑，为了保证动画顺畅。

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.6 版本修复
