### ISSUE TITLE
[Feature Request] 倒计时组件能不能添加‘正计时’属性

### ISSUE THREAD

**Issue by zaxlct** [youzan/vant#7402]
### 这个功能解决了什么问题
有时候需求是计算时间的增加。。如果能加个属性，就好了

### 描述您想要的解决方案
有时候需求是计算时间的增加。。如果能加个属性，就好了

### 建议的API是什么样的
添加个prop，是否是正计时，默认为false

**Comment by chenjiahan** [comment]
暂无计划支持呢
