### ISSUE TITLE
[Bug Report] van-tab 在第一个tab处，页面下滑，会出现回弹闪烁

### ISSUE THREAD

**Issue by L1uFei** [youzan/vant#7404]
### 设备 / 浏览器
ios 微信浏览器

### Vant 版本
2.10.4

### Vue 版本
2.5.2

### 描述问题
van-tab 在第一个tab处，页面下滑，会出现回弹闪烁。我在tab上面有一个搜索框，我offset-top是获取搜索框高度的，offset-top设置为0就不会闪烁了，然后我有用滚动导航和吸顶

**Comment by L1uFei** [comment]
需要在手机复现

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接喔

https://codesandbox.io/s/m5v3f
