### ISSUE TITLE
[Feature Request] 需要添加缅甸、越南、阿拉伯三个语种，提PR大概多久能使用？

### ISSUE THREAD

**Issue by wrngdy** [youzan/vant#7406]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
一周内发版
