### ISSUE TITLE
van-list 与 el-table组合使用，但是滚动加载，会一直触发load，这个怎么解决

### ISSUE THREAD

**Issue by sjh0824** [youzan/vant#7409]
官方给出的几个解决办法都试了，还是不行，不知道要怎么解决

![image](https://user-images.githubusercontent.com/18656791/97155168-e7c38c00-17af-11eb-9f1d-662e91667c00.png)

慢慢下滑滚动可以，但是直接到底部出现加载中，就会停到最底部一直触发load，去请求接口
![image](https://user-images.githubusercontent.com/18656791/97160134-df228400-17b6-11eb-9702-21421101c4ff.png)

有知道的大佬吗，请回答一下，非常感谢

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
