### ISSUE TITLE
Tabs组件，swipeable属性问题

### ISSUE THREAD

**Issue by oliver34** [youzan/vant#741]
升级到最新版的vant后，Tabs组件使用swipeable后可以实现左右切换标签页，
但是又遇到另一个问题：
1. 标签页内的元素变得无法点击，有时点击边缘处直接切换标签页了。
2. 标签页内如果使用了list组件，则失效

**Comment by cookfront** [comment]
感谢反馈，我们看下这个问题

**Comment by cookfront** [comment]
@oliver34  `标签页内如果使用了list组件，则失效` 这个问题能具体描述下么？不是太明白

**Comment by oliver34** [comment]
list组件失效，无法实现“无限加载”的功能
