### ISSUE TITLE
[Bug Report] van-list 与 el-table组合使用，但是滚动加载，会一直触发load，这个怎么解决 

### ISSUE THREAD

**Issue by sjh0824** [youzan/vant#7410]
### 设备 / 浏览器
手机端，浏览器手机模拟

### Vant 版本
2.2.11

### Vue 版本
2.6.10

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/list" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/list</a>

### 描述问题
van-list 与 el-table组合使用，但是滚动加载，会一直触发load，这个怎么解决 
官方给出的几个解决办法都试了，还是不行，不知道要怎么解决
慢慢下滑滚动可以，但是直接到底部出现加载中，就会停到最底部一直触发load，去请求接口
https://user-images.githubusercontent.com/18656791/97155168-e7c38c00-17af-11eb-9f1d-662e91667c00.png
https://user-images.githubusercontent.com/18656791/97160134-df228400-17b6-11eb-9702-21421101c4ff.png

有知道的大佬吗，请回答一下，非常感谢

**Comment by chenjiahan** [comment]
麻烦提供下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by ncumovi** [comment]
> ### 设备 / 浏览器
> 手机端，浏览器手机模拟
> 
> ### Vant 版本
> 2.2.11
> 
> ### Vue 版本
> 2.6.10
> 
> ### 重现链接
> https://vant-contrib.gitee.io/vant/#/zh-CN/list
> 
> ### 描述问题
> van-list 与 el-table组合使用，但是滚动加载，会一直触发load，这个怎么解决
> 官方给出的几个解决办法都试了，还是不行，不知道要怎么解决
> 慢慢下滑滚动可以，但是直接到底部出现加载中，就会停到最底部一直触发load，去请求接口
> https://user-images.githubusercontent.com/18656791/97155168-e7c38c00-17af-11eb-9f1d-662e91667c00.png
> https://user-images.githubusercontent.com/18656791/97160134-df228400-17b6-11eb-9702-21421101c4ff.png
> 
> 有知道的大佬吗，请回答一下，非常感谢

解决了吗 老哥
