### ISSUE TITLE
[Bug Report] Vant3中的Calendar组件，异步设置min-date与max-date时，下个月日期不显示

### ISSUE THREAD

**Issue by micodecc** [youzan/vant#7412]
### 设备 / 浏览器
chrome latest

### Vant 版本
3.0.0-beta.5

### Vue 版本
3.0.2

### 重现链接
<a href="https://codesandbox.io/s/frosty-morning-bvcvp" target="_blank">https://codesandbox.io/s/frosty-morning-bvcvp</a>

### 描述问题
当采用异步方式获取数据并设置min-date与max-date时，只能正确显示当月日期，下月日期不显示，需要滚动一下Calendar后才会显示出来

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.6 版本修复

**Comment by micodecc** [comment]
@chenjiahan 经测试好像还是没有修复，见Issue中的链接，我更新依赖至3.0.0-beta6，现在是显示空白了

**Comment by Meqn** [comment]
弹窗形式，设置了最大和最小日期，在iPhoneX及以上版本 经常出现白屏问题，Android上都正常。
希望这个问题可以排查下。

**Comment by Meqn** [comment]
> 弹窗形式，设置了最大和最小日期，在iPhoneX及以上版本 经常出现白屏问题，Android上都正常。
> 希望这个问题可以排查下。

`vant@2.10.12`

**Comment by chenjiahan** [comment]
> 经测试好像还是没有修复，见Issue中的链接，我更新依赖至3.0.0-beta6，现在是显示空白了

已在 3.0.0-beta.7 版本修复

> 弹窗形式，设置了最大和最小日期，在iPhoneX及以上版本 经常出现白屏问题，Android上都正常。
希望这个问题可以排查下。

麻烦提供下 codesandbox 复现链接
