### ISSUE TITLE
[Feature Request] 输入框为number类型时，没有min和max属性

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#7413]
### 这个功能解决了什么问题
可输入范围，现在设置了min及max无效

### 描述您想要的解决方案
可输入范围

### 建议的API是什么样的
允许min及max属性

**Comment by cangyu1993** [comment]
现在使用格式化输入完成的需求，未来会支持吗？
```js
//从业年限允许0-30年
    formatterJobYear(value) {
      if (Number(value) > 30) {
        this.$toast('从业年限为0-30年')
        return 30
      } else {
        return value
      }
    },
```

**Comment by ZhengXiaowei** [comment]
可以试试`stepper`组件

**Comment by cangyu1993** [comment]
> 可以试试`stepper`组件

图是输入框，stepper不符合设计

**Comment by ZhengXiaowei** [comment]
> > 可以试试`stepper`组件
> 
> 图是输入框，stepper不符合设计

提了pr 不知道能merge不

**Comment by cangyu1993** [comment]
> > > 可以试试`stepper`组件
> > 
> > 图是输入框，stepper不符合设计
> 
> 提了pr 不知道能merge不

我就是觉得这个是原生属性可以考虑有，当然实现功能的方法很多

**Comment by ZhengXiaowei** [comment]
vant里field的type=number并不是原生的 而是基于现代浏览器支持的inputmode来实现的

**Comment by chenjiahan** [comment]
这个不计划在 Field 里面支持呢，用 formatter 自行实现把
