### ISSUE TITLE
[Bug Report] 怎么修改dialog弹出的位置，让它位于屏幕底部，而不是居中

### ISSUE THREAD

**Issue by jhxxs** [youzan/vant#7414]
### 设备 / 浏览器
手机

### Vant 版本
^2.10.5

### Vue 版本
^2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-fj6q8?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-fj6q8?file=/src/App.vue</a>

### 描述问题
产品设计需求，dialog的弹出位置位于屏幕下方，但vant默认是全屏居中，通过给dialog设置`top:70%`，可以让弹窗位于下方，但百分比并不是一个好的选择，在不同的屏幕高度下，位置也会不统一，设置`bottom`属性，弹窗会变形，请问有什么好的方法吗？
![Snipaste_2020-10-27_10-47-53.png](https://i.loli.net/2020/10/27/3ltJznkYcah1LgK.png)

**Comment by ZhengXiaowei** [comment]
要么自己给`dialog`外层加个样式，用`rem/viewport`的方式调整位置，这样可以避免变形或者位置不统一的问题，要么改用`actionsheet`组件，自己稍微调整下样式 一样可以达到效果

**Comment by jhxxs** [comment]
> 要么自己给`dialog`外层加个样式，用`rem/viewport`的方式调整位置，这样可以避免变形或者位置不统一的问题，要么改用`actionsheet`组件，自己稍微调整下样式 一样可以达到效果

`actionsheet`不太行，它的弹出动画是从下面弹出来的，而且和底部没有间隔。

**Comment by chenjiahan** [comment]
这个效果建议用 Popup 或 ActionSheet 来实现，可以自行添加一个 className，然后调整一下弹窗的位置

```html
<van-popup class="my-popup" position="bottom" />
```

```css
.my-popup {
  left: 20px;
  right: 20px;
  bottom: 20px;
  width: auto;
}
```
