### ISSUE TITLE
日期选择器在ios 11 存在兼容问题

### ISSUE THREAD

**Issue by yinyouyu1234** [youzan/vant#7415]
<van-calendar 
          min-date={new Date('2000-1-1')} 
          max-date={new Date()}
          default-date={new Date(activeDate)}
          on-input={val => this.calendarShow = val}
          on-confirm={(time) => this.selectTime(time)}
          value={calendarShow} 
          round={false} 
          position="right" />

调用这个组件，安卓手机可以打开  在 iOS 部分机型  打不开页面。无法渲染，白屏。
更换其他控件恢复正常！

**Comment by Krryxa** [comment]
请确认在创建 Date 对象时没有使用new Date('2020-01-01')这样的写法，iOS 不支持以中划线分隔的日期格式，正确写法是new Date('2020/01/01')
