### ISSUE TITLE
[Bug Report] van-tabs数据导致active被修改问题

### ISSUE THREAD

**Issue by lizhancheng** [youzan/vant#7417]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.11

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-vsxmg?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-vsxmg?file=/src/App.vue</a>

### 描述问题
数据生成van-tab，对数据进行unshift操作会导致v-model被修改，有重现链接

**Comment by chenjiahan** [comment]
这种情况通过名称匹配就可以了，参见 https://youzan.github.io/vant/#/zh-CN/tab#tong-guo-ming-cheng-pi-pei

**Comment by lizhancheng** [comment]
> 这种情况通过名称匹配就可以了，参见 https://youzan.github.io/vant/#/zh-CN/tab#tong-guo-ming-cheng-pi-pei

我就是用的名称匹配啊，unshift进去的结构就是{ name: 'xxx', title: 'xxx' }

**Comment by chenjiahan** [comment]
sorry，看漏了，这里是有问题的，后续修复

**Comment by chenjiahan** [comment]
已在 2.10.12 版本修复
