### ISSUE TITLE
van-dropdown-item 组件通过类选择器更改不了此组件样式，原因是此组件缺少data-v-59c35ec8属性导致

### ISSUE THREAD

**Issue by 184289542** [youzan/vant#7418]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by 184289542** [comment]
回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 晚上8:45
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"江山此夜寂"<184289542@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] van-dropdown-item 组件通过类选择器更改不了此组件样式，原因是此组件缺少data-v-59c35ec8属性导致 (#7418)





 
Closed #7418.
