### ISSUE TITLE
[Bug Report] Collapse在IOS 9系统上展开会出现瞬间展开收缩又展开

### ISSUE THREAD

**Issue by wangshaoqun** [youzan/vant#7419]
### 设备 / 浏览器
IOS 9.x.x

### Vant 版本
2.10.5

### Vue 版本
2.6.12

### 重现链接
<a href="https://www.gattefossechina.cn/wx/#/personal-case-formula?openId=oCDBp51cJAJhEFa1FQxCC79PuiVk&channelId=668" target="_blank">https://www.gattefossechina.cn/wx/#/personal-case-formula?openId=oCDBp51cJAJhEFa1FQxCC79PuiVk&channelId=668</a>

### 描述问题
在IOS 9上展开内容时会出现瞬间展开收缩又展开的问题

**Comment by chenjiahan** [comment]
这个是系统问题，iOS 的占比已经极少了，所以不考虑单独兼容
