### ISSUE TITLE
[Bug Report] swipe 有漏边

### ISSUE THREAD

**Issue by hezedu** [youzan/vant#7422]
### 设备 / 浏览器
chrome  80  

### Vant 版本
2.10.11

### Vue 版本
2.6.12

### 重现链接
<a href="https://jsbin.com/fiwedos/edit?html,output" target="_blank">https://jsbin.com/fiwedos/edit?html,output</a>

### 描述问题
增加对像素小数点支持

**Comment by chenjiahan** [comment]
后续会优化下

**Comment by chenjiahan** [comment]
已在 2.10.14 版本修复
