### ISSUE TITLE
[Bug Report] vant tabs组件选中下划线位置异常

### ISSUE THREAD

**Issue by haobaic** [youzan/vant#7424]
### 设备 / 浏览器
谷歌

### Vant 版本
2.10.9

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-mwkz9?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-mwkz9?file=/src/App.vue</a>

### 描述问题
点击显示第一下划线位置不正确  第二次就对了  在刷新还是不对

**Comment by haobaic** [comment]
![image](https://user-images.githubusercontent.com/32922661/97385682-29b61480-190d-11eb-9a6d-c1220bd6d765.png)
这是显示图片

**Comment by haobaic** [comment]
**全部代码**
```
<template>
  <div id="app">
    <van-button type="primary" @click="isShow = !isShow">点击显示</van-button>
    <div v-show="isShow">
      <van-tabs v-model="active">
        <van-tab title="标签 1">内容 1</van-tab>
        <van-tab title="标签 2">内容 2</van-tab>
        <van-tab title="标签 3">内容 3</van-tab>
        <van-tab title="标签 4">内容 4</van-tab>
      </van-tabs>
    </div>
  </div>
</template>
<script>
export default {
  name: "App",
  data() {
    return {
      active: 2,
      isShow: false,
    };
  },
};
</script>
```

**Comment by chenjiahan** [comment]
这种情况确实有问题，而且没法在组件内部避免。问题出现的原因是 Tab 挂载的时候会初始化并获取自身宽度，如果处于隐藏状态下，Tab 是获取不到自身宽度的，因此底部条的位置没法正确计算。

解决方法是在展示 Tab 的时候，调用 Tab 实例上的 resize 方法。

**Comment by haobaic** [comment]
好 大佬解决了
