### ISSUE TITLE
[Feature Request] 建议增加Scroller加载组件

### ISSUE THREAD

**Issue by sapida** [youzan/vant#7425]
### 这个功能解决了什么问题
解决移动端常见的上拉加载和下拉刷新问题

### 描述您想要的解决方案
目前Vant虽然已经有了PullRefresh 下拉刷新和List 列表，两者结合使用，实现下拉刷新的效果。但是缺少回弹效果，滑动不自然。建议增加Scroller组件，支持自定义下拉刷新/上拉加载/数据滚动等。

### 建议的API是什么样的
类似cube-ui 的Scroll组件，better-scroll组件或者vue-scroller组件

**Comment by chenjiahan** [comment]
暂无计划支持呢，有需求可以使用 better-scroll
