### ISSUE TITLE
[Bug Report] uploader图片上传在android的拍照模式下兼容问题

### ISSUE THREAD

**Issue by xiasha1** [youzan/vant#7428]
### 设备 / 浏览器
android

### Vant 版本
2.10.8

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/mobile.html#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/mobile.html#/zh-CN/uploader</a>

### 描述问题
 uploader图片上传在android的拍照模式下显示的是一个文件名而不是图片

**Comment by hzq-up** [comment]
uploader组件在苹果手机浏览器上能用吗？我的在苹果手机上显示不出来

**Comment by xiasha1** [comment]
> uploader组件在苹果手机浏览器上能用吗？我的在苹果手机上显示不出来

可以显示的，我的主要是在我们自己的app webkit 浏览器不兼容android的拍照模式

**Comment by chenjiahan** [comment]
可以把 file.type log 出来看一下，Uploader 是根据 file.type 来判断是否是图片的
