### ISSUE TITLE
[Bug Report] 使用grid-item的badge 添加徽标时，控制台出现警告

### ISSUE THREAD

**Issue by SignDawn** [youzan/vant#7429]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.10.11

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/signdawn/pen/VwjrBvV" target="_blank">https://codepen.io/signdawn/pen/VwjrBvV</a>

### 描述问题
怀疑就是 gird-item 内部的 icon  使用了 info 导致警告

**Comment by chenjiahan** [comment]
确实有问题，下个版本会移除

**Comment by chenjiahan** [comment]
已在 2.10.12 版本修复
