### ISSUE TITLE
编辑地址时，不能默认地址v1.0.1，上个版本还是可以的

### ISSUE THREAD

**Issue by xqsapper** [youzan/vant#743]
编辑地址时，不能默认地址，v1.0.1上个版本还是可以的

**Comment by chenjiahan** [comment]
@xqsapper 可以详细描述一下你的问题吗

**Comment by xqsapper** [comment]
我点选收货地址进行编辑，到编辑页面时其他值能获取到原有值，【收件地址】无变化，还是选择省份，选择城市，没有编辑值

**Comment by chenjiahan** [comment]
@xqsapper 感谢反馈，已复现这个问题，下个版本修复

**Comment by chenjiahan** [comment]
已在 1.0.2 版本修复
