### ISSUE TITLE
[Feature Request] Calendar在日历上添加月份，年份切换功能

### ISSUE THREAD

**Issue by cuivip** [youzan/vant#7430]
### 这个功能解决了什么问题
当前Calendar功能在range模式下，选择一个起点，一个终点，如果时间跨度大，需要不停做滚动。操作不方便。

### 描述您想要的解决方案
是否可以在Calendar左右上叫加 月份，年份切换功能。

《 <  2020 年10 月  > 》

      此处为日历区域

其中：

《  为年份切换

 <   为同一年下的月份切换

### 建议的API是什么样的
无

**Comment by cuivip** [comment]
vant 版本为2.10.11

**Comment by chenjiahan** [comment]
暂无计划支持喔

**Comment by wangyong93** [comment]
> 暂无计划支持喔

为啥不支持呢？  这个需求很常见呀。一直滑对用户来说很痛苦啊

**Comment by Chevsky-G** [comment]
> > 暂无计划支持喔
> 
> 为啥不支持呢？ 这个需求很常见呀。一直滑对用户来说很痛苦啊

有解决办法么

**Comment by wangyong93** [comment]
您好，您发来的邮件我已收到！

**Comment by Chevsky-G** [comment]
确实low
