### ISSUE TITLE
Collapse 折叠面板 问题

### ISSUE THREAD

**Issue by zp18823358143** [youzan/vant#7431]
从官网引入3.0版本的vant  Collapse 折叠面板组件（基础用法），vue版本3.0.0-0，测试用例参考视频，麻烦看一下问题，谢谢。
[b20abc0b395a6d82880112d358eb3af9.zip](https://github.com/youzan/vant/files/5450581/b20abc0b395a6d82880112d358eb3af9.zip)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by zp18823358143** [comment]
Why is my question closed




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2020年10月28日(星期三) 晚上6:12
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "张沛"<986068176@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] Collapse 折叠面板 问题 (#7431)





 
Closed #7431.
