### ISSUE TITLE
[Bug Report] swipe并没有修复，

### ISSUE THREAD

**Issue by 810505339** [youzan/vant#7436]
### 设备 / 浏览器
都存在

### Vant 版本
3.0.0-beta.5

### Vue 版本
3.0.2

### 重现链接
<a href="https://810505339.github.io/vant3-tsx/dist/index.html" target="_blank">https://810505339.github.io/vant3-tsx/dist/index.html</a>

### 描述问题
swipe需要发生重绘才能生效， 异步获取swipe 图片页不能滑动

**Comment by 810505339** [comment]
![Uploading image.png…]()

**Comment by 810505339** [comment]
![企业微信截图_16039442914943](https://user-images.githubusercontent.com/50100966/97524191-03f94000-19df-11eb-9b7c-0288cf7e286d.png)

**Comment by chenjiahan** [comment]
这个问题和异步加载没有关系。

当 Swipe 放在 Tab 内部时，Swipe 组件初始化时处于隐藏状态，因此无法获取到自身的正确宽度，会导致计算错误，这个问题在组件内部不太好解决。

你可以手动调用 Swipe 组件的 resize 方法来避免这个问题
