### ISSUE TITLE
[Bug Report] Stop putting non production ready code as your release!

### ISSUE THREAD

**Issue by frostcodes** [youzan/vant#7437]
### 设备 / 浏览器
ALL

### Vant 版本
2.10.11

### Vue 版本
2.6.12

### 重现链接
<a href="https://youzan.github.io/" target="_blank">https://youzan.github.io/</a>

### 描述问题
Too many Bugs!! Please people use your library in production and this is a real problem. I thought we had a bug for a week till i found out its from your framework . Time was wasted for no reason on trying to fix this bug from you.

van Dialog doesn't hide overlay when closed via v-model , also dialog with option has a weird look the buttons are on new lines for no reason

**Comment by chenjiahan** [comment]
Please provide a valid link to reproduce the problem, thanks
