### ISSUE TITLE
vue3.0 iconfont van-field 插入图标不显示，单独div 图标是正常显示的

### ISSUE THREAD

**Issue by xlanghejianfeng** [youzan/vant#7438]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater
  <van-field
                            v-model="formData.username"
                            name="用户名"
                            placeholder="请输入用户名"
                            left-icon="user"
                            :rules="[
                                { required: true, message: '请填写用户名' },
                            ]"
                        >
                            <van-icon
                                class="iconfont"
                                class-prefix="icon"
                                slot="left-icon"
                                name="user"
                            ></van-icon>
                        </van-field>
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
