### ISSUE TITLE
[Bug Report] 3.0中以下组件ActionBar, ActionBarIcon, ActionBarButton未在types/index.d.ts文件中声明

### ISSUE THREAD

**Issue by quliangen** [youzan/vant#7440]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0-beta.5

### Vue 版本
3.0.0

### 重现链接
<a href="https://youzan.github.io/vant/next/#/zh-CN/action-bardai-ma-yan-shi" target="_blank">https://youzan.github.io/vant/next/#/zh-CN/action-bardai-ma-yan-shi</a>

### 描述问题
3.0.0-beta.5中以下组件ActionBar, ActionBarIcon, ActionBarButton未在types/index.d.ts文件中声明。
ActionBar, ActionBarIcon, ActionBarButton组件文档：https://youzan.github.io/vant/next/#/zh-CN/action-bardai-ma-yan-shi 
3.0.0-beta.5 types文件：https://github.com/youzan/vant/blob/v3.0.0-beta.5/types/index.d.ts

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.6 版本修复
