### ISSUE TITLE
[Feature Request] SubmitBar可否支持两个按钮的操作，或支持右侧按钮区域也可自定义呢？

### ISSUE THREAD

**Issue by wangyibinwangyi** [youzan/vant#7441]
### 这个功能解决了什么问题
需求是底部提交订单栏需要支持‘预览订单’及‘提交订单’两个功能，目前组件不支持该操作。

### 描述您想要的解决方案
希望可以支持一下右侧按钮区域的插件

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
已在 2.10.12 版本支持
