### ISSUE TITLE
[Bug Report] npm run build 之后，tabs的布局全都变成了swipe的布局

### ISSUE THREAD

**Issue by skyopens** [youzan/vant#7443]
### 设备 / 浏览器
Chrome、Safari（ IOS ）

### Vant 版本
3.0.0-beta.0

### Vue 版本
3.0.0

### 重现链接
<a href="http://rt.rt" target="_blank">http://rt.rt</a>

### 描述问题
在vue3中使用了tabs和tab插件来装一些列表数据，本地环境一切正常。
但是通过jenkins打包构建到服务器上后，列表直接不加载。
关闭lazyload，列表可以正常显示，但是不能切换。
查看F12，van-tabs__content 这个类的div里面的所有布局都换成了swipe的布局和类名，但是标签是正常的。
项目未上线，无法填写重现链接，请见谅。

**Comment by chenjiahan** [comment]
这个看起来不像是 vant 的问题呢，建议自己排查下，是不是打包问题或其他问题
