### ISSUE TITLE
[Bug Report] Uploader安卓手机点击没有反应无法打开图库

### ISSUE THREAD

**Issue by lahala** [youzan/vant#7444]
### 设备 / 浏览器
安卓手机

### Vant 版本
2.10.11

### Vue 版本
3.0.1

### 重现链接
<a href="https://edutest.yokelly.com.cn/gift/once/?activityApplyType=2" target="_blank">https://edutest.yokelly.com.cn/gift/once/?activityApplyType=2</a>

### 描述问题
在我们的APP上，有些页面使用的是Vue开发，然后就使用了vant，现在在使用Uploader时，苹果手机点击可以打开图库，安卓手机点击却没有反应，相机等手机权限已打开了

**Comment by chenjiahan** [comment]
这个是 WebView 本身配置的问题，与组件无关呢

网上有一些解决方案，可以参考下，比如 https://stackoverflow.com/questions/5907369/file-upload-in-webview
