### ISSUE TITLE
[Feature Request] 希望van-image的icon能开放class-prefix

### ISSUE THREAD

**Issue by gap1994** [youzan/vant#7446]
### 这个功能解决了什么问题
这样就能自定义使用icon

### 描述您想要的解决方案
van-image的icon组件能暴露class-prefix，不然只能用插槽自定义

### 建议的API是什么样的
van-image暴露class-prefix
![image](https://user-images.githubusercontent.com/9198081/97651327-ac1e1000-1a96-11eb-814e-c2c82970c9a0.png)

**Comment by chenjiahan** [comment]
已在 2.10.12 版本支持
