### ISSUE TITLE
[Bug Report] checkbox-group下的checkbox bind-group=false 无效

### ISSUE THREAD

**Issue by Becessary** [youzan/vant#7447]
### 设备 / 浏览器
PC Android

### Vant 版本
3.0.0-beta.4

### Vue 版本
3.0.2

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-uk2j0?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-uk2j0?file=/src/App.vue</a>

### 描述问题
如题；
在codesandbox上用beta.5测，一样情况。

**Comment by chenjiahan** [comment]
目前 3.0 里 bind-group 有问题，后续修复

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.9 版本修复
