### ISSUE TITLE
[Bug Report] tabs切换组件在开启切换回调函数后，还可以通过滑动继续

### ISSUE THREAD

**Issue by gzg1023** [youzan/vant#7449]
### 设备 / 浏览器
chrome84

### Vant 版本
2.10.11

### Vue 版本
2.5.22

### 重现链接
<a href="https://codesandbox.io/s/goofy-forest-v8i1q?file=/src/App.vue" target="_blank">https://codesandbox.io/s/goofy-forest-v8i1q?file=/src/App.vue</a>

### 描述问题
我在使用van-tabs组件的时候，用到了swipeable的滑动属性，但是tab内部我还有要滑动的内容。这样就会出发tab的滑动导致滑到了下一个tab里面。
我看到v2.9.3新增了before-change函数，但是如果使用这个函数我返回false，不能通过点击tab切换了但是滑动依然生效。

希望可以添加tab内部的一些参数，控制滑动tab某个区域时候不触发发布的滑动时间，并且使用before-change回调函数时候，可以合理控制滑动事件，现在
静止了上面，下面还可以滑动明显是不合理的，谢谢。

**Comment by gzg1023** [comment]
具体来说不止chrome84，我在真机看了也是这种情况。看了下源码好像是没相关操作的代码

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6895

**Comment by gzg1023** [comment]
好的，谢谢回复。但是这种需求也可能会经常碰到。会不会考虑添加一个prop 默认是保持现状，开启后可以同时  控制滑动和tab点击的切换呢

**Comment by chenjiahan** [comment]
感谢建议，后续会再评估下这块的实现
