### ISSUE TITLE
Checkbox组件change事件触发不了

### ISSUE THREAD

**Issue by devtip** [youzan/vant#745]
如题：Checkbox组件change事件触发不了

CheckboxGroup组件的change事件可以触发，而Checkbox组件的change事件却触发不了

版本：
-  Vant 1.0.1

代码：
``` html
  <van-checkbox-group
      v-model="result"
    >
      <van-checkbox
        @change="changeItem"
        v-for="(item) in list"
        :key="item"
        :name="item"
      >
        复选框 {{ item }}
      </van-checkbox>
    </van-checkbox-group>
```

PS:
- 很多组件涉及到支持的事件方法方面，基本上没有例子！
- Col组件无法绑定click方法

**Comment by chenjiahan** [comment]
1. 如果使用了 checkbox-group，change 事件是绑定在 checkbox-group 上的。
   如果单独使用 checkbox 组件，则 change 事件绑定在 checkbox 上
2. Col 组件直接绑定 @click.native 即可

**Comment by devtip** [comment]
@chenjiahan 谢谢回复了，看来是时候也要更新文档了...

**Comment by chenjiahan** [comment]
嗯嗯，文档会逐渐完善
