### ISSUE TITLE
[Bug Report] sidebar组件在都是数字的情况下不会自动换行

### ISSUE THREAD

**Issue by ipconfig12138** [youzan/vant#7455]
---sidebar侧边栏组件，当名称为都是数字时不能自动换行。。。
具体效果看下图
![Screenshot_20201030_232501_com quark browser](https://user-images.githubusercontent.com/29529193/97724216-9d237600-1b07-11eb-8121-d87c1279343f.png)

**Comment by chenjiahan** [comment]
已在 2.10.12 版本修复
