### ISSUE TITLE
[Bug Report] 3.0版本，Uploader 文件上传设置file.status为done依旧停留在上传中

### ISSUE THREAD

**Issue by NullYing** [youzan/vant#7462]
### 设备 / 浏览器
chome

### Vant 版本
3.0.0-beta.5

### Vue 版本
3.0.2

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-lhwp1?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-lhwp1?file=/src/App.vue</a>

### 描述问题
3.0版本，Uploader 文件上传设置file.status为done依旧停留在上传中

**Comment by NullYing** [comment]
同样failed也不会生效，代码是文档里面的代码，如果不先设置uploading，是可以直接跳到done

**Comment by chenjiahan** [comment]
这个可能是 Vue 3 的响应式 bug，Uploader 的内部逻辑和 2.x 版本是一致的

**Comment by NullYing** [comment]
> 这个可能是 Vue 3 的响应式 bug，Uploader 的内部逻辑和 2.x 版本是一致的

Vue 3 应该可以使用Proxy来监听这个变化，不需要 2.x的方法（没有了解）

**Comment by hqwjj1314** [comment]
源码检测不到item变化，在不修改源码条件下，外部v-model绑定的数组在异步请求之后先length++，紧接着length--，强行触发更新，因为数组长度变化了但是新加的是空内容会报错，把新加的减回去，这样就不会报错，也解决了这个状态问题，这只是暂时的，希望官方能注意到这个问题，从源码角度修改，可能这种隐患会在其他地方出现

**Comment by hqwjj1314** [comment]
回调钩子里面设置file的属性变化并不会使得modelValue改变从而触发重渲染， 所以item无变化，在不修改源码条件下，外部v-model绑定的数组在异步请求之后先length++，紧接着length--，强行触发modelValue变化使得更新，但是因为数组长度变化了又是新加的是空内容所以会报错，把新加的减回去，这样就不会报错，暂时hacker这个问题。
