### ISSUE TITLE
[Bug Report] vue-cli后安装了vant，使用按需引入并注册组件[Button.name]: Button会报错

### ISSUE THREAD

**Issue by XdyGoGo** [youzan/vant#7467]
### 设备 / 浏览器
Mac / safari

### Vant 版本
2.10.11

### Vue 版本
2.6.1

### 重现链接
<a href="http://localhost:8080" target="_blank">http://localhost:8080</a>

### 描述问题

This dependency was not found:

* core-js/modules/es.function.name in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save core-js/modules/es.function.name

**Comment by l-xue-yu** [comment]
我的也是，用vue/cli生成的项目，跟着vant官网文档，安装，自动按需引入之后就不行，组件都不能用。感觉是版本不兼容。
![image](https://user-images.githubusercontent.com/42016055/98342206-08f76880-204b-11eb-8130-e237f3f905ce.png)

**Comment by dishcheng** [comment]
一样
