### ISSUE TITLE
文件上传bug

### ISSUE THREAD

**Issue by binrege** [youzan/vant#7471]
### 文件上传bug
点击文件上传后会弹出选择拍照和选择文件的界面,这里会有一个遮罩层.点击拍照和选择文件不会出现问题,但是如果点击遮罩层后页面会关闭,此时文件上传就无法点击了.只能重新打开app才能继续使用文件上传

**Comment by binrege** [comment]
> ### 文件上传bug
> 点击文件上传后会弹出选择拍照和选择文件的界面,这里会有一个遮罩层.点击拍照和选择文件不会出现问题,但是如果点击遮罩层后页面会关闭,此时文件上传就无法点击了.只能重新打开app才能继续使用文件上传

**Comment by binrege** [comment]
文件上传bug
点击文件上传后会弹出选择拍照和选择文件的界面,这里会有一个遮罩层.点击拍照和选择文件不会出现问题,但是如果点击遮罩层后页面会关闭,此时文件上传就无法点击了.只能重新打开app才能继续使用文件上传

**Comment by 980864138** [comment]
2.10.1版本，选择文件或者拍照后，页面没有任何反应，也没进入到beforeRead方法，请问是怎么回事

**Comment by binrege** [comment]
> 2.10.1版本，选择文件或者拍照后，页面没有任何反应，也没进入到beforeRead方法，请问是怎么回事

不太清除,我之前用的是2.5.5的版本,没有你那个问题,刚刚换成新版本也没有你那个问题啊.但是我的问题还是存在

**Comment by chenjiahan** [comment]
遮罩层和选择文件的界面都是原生系统提供的交互，和 Uploader 组件本身没有关系，Uploader 只是对 HTML5 里面的 input type="file" 做了一层封装。

你这个问题可能是 App 侧的 bug，可以找客户端同学排查下
