### ISSUE TITLE
3.0 中DropdownMenu 是不是没有close-on-click-overlay这个属性了？

### ISSUE THREAD

**Issue by zhanghaoranas** [youzan/vant#7472]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
有的
