### ISSUE TITLE
[Bug Report] dropdownMenu时展开状态后当点击Popup组件时两个同时hide

### ISSUE THREAD

**Issue by zhanghaoranas** [youzan/vant#7473]
### 设备 / 浏览器
Edge

### Vant 版本
3.0.0-beta.6

### Vue 版本
3.0.2

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-k2y5g?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-k2y5g?file=/src/App.vue</a>

### 描述问题
在下拉菜单中点击某一元素使Popup组件弹出， 点击Popup之后，Popup隐藏，但是菜单也收缩了。

**Comment by chenjiahan** [comment]
当点击 DropdownMenu 的外部时，会自动关闭菜单。

你可以把 close-on-click-outside 属性设置为 false，来关闭这个行为

**Comment by zhanghaoranas** [comment]
@chenjiahan 抱歉，我当时的vant版本和vue 版本弄错了，现在改了，而且添加上了close-on-click-outside属性了，但是依旧会出现那个问题。能麻烦再看一下吗，我看了一下代码 并没有props中没有定义closeOnClickOutside这个属性，而且useClickAway这个hook 也没有接收options。（可能是我看的不仔细/(ㄒoㄒ)/~~）

**Comment by chenjiahan** [comment]
确实有问题，后续会修复

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.7 版本修复

**Comment by kgysf** [comment]
> 已在 3.0.0-beta.7 版本修复

我遇到了与这个问题一摸一样的情况，唯一的不同点是我是再dropdownmenu中嵌套的Calendar 日历组件，我已经升级到了beta.7，但是依然有这个问题
