### ISSUE TITLE
[Feature Request] tag多标签关闭，没有回调参数，无法确认当前操作的是哪个

### ISSUE THREAD

**Issue by xuanyanwow** [youzan/vant#7474]
### 这个功能解决了什么问题
多选标签列表，可以删除某个标签。

### 描述您想要的解决方案
携带回调参数，可以获取到dom的data-*属性，通过index删除数组

### 建议的API是什么样的
deleteTag(e){
    console.log(e)
},

**Comment by chenjiahan** [comment]
直接传参就好

```html
<van-tag @close="onClose(1)" />
<van-tag @close="onClose(2)" />
```
