### ISSUE TITLE
van-sticky组件offset-top支持单位vw不合理

### ISSUE THREAD

**Issue by hwyue** [youzan/vant#7476]
van-sticky组件offset-top支持单位中的“vw”并不符合offset-top的意图，个人认为它应该是“vh”更为贴切。
如果直接设定为offset-top="80vh"，却被当作为offset-top="80px”渲染。
https://vant-contrib.gitee.io/vant/#/zh-CN/sticky

**Comment by chenjiahan** [comment]
目前不支持 vh 呢，你是希望增加对 vh 的支持么

**Comment by hwyue** [comment]
vw指的是宽度，vh才是高度；offset-top是表示顶端距离，所以我认为vh才更新为合理。

**Comment by chenjiahan** [comment]
已在 2.10.13 版本支持 vh 单位
