### ISSUE TITLE
vant-cli创建等项目，哪里可以配置或者覆盖@van-doc-simulator-width？重新定义模拟器等宽度？

### ISSUE THREAD

**Issue by chenliang123** [youzan/vant#7477]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
目前暂不支持覆盖。
