### ISSUE TITLE
@chenjiahan 你好，请问 vant-cli 脚手架可以安装 vue3 吗？如何安装，没找到文档，谢谢

### ISSUE THREAD

**Issue by boliangleung** [youzan/vant#7478]
@chenjiahan 你好，请问 vant-cli 脚手架可以安装 vue3 吗？如何安装，没找到文档，谢谢

我现在也遇到这个问题 请问你解决了吗

**Comment by chenjiahan** [comment]
目前 vant-cli 是基于 Vue 2 的，基于 Vue 3 的版本还在开发中，如果需要使用，可以安装 @vant/cli@beta 版本

**Comment by boliangleung** [comment]
因为vue-template-compiler最新是2.6.12版本，vue是3.0版本。装了最新会提示版本不一，无法启动

**Comment by boliangleung** [comment]
> 目前 vant-cli 是基于 Vue 2 的，基于 Vue 3 的版本还在开发中，如果需要使用，可以安装 @vant/cli@beta 版本，并将项目内的 vue 和 vue-template-compiler 替换为新版



> 目前 vant-cli 是基于 Vue 2 的，基于 Vue 3 的版本还在开发中，如果需要使用，可以安装 @vant/cli@beta 版本，并将项目内的 vue 和 vue-template-compiler 替换为新版

因为vue-template-compiler最新是2.6.12版本，vue是3.0版本。装了最新会提示版本不一，无法启动

**Comment by chenjiahan** [comment]
Vue3 用的是 @vue/compiler-sfc，不是 vue-template-compiler

**Comment by boliangleung** [comment]
我试过用 @vue/compiler-sfc 但是也不可以 @chenjiahan 。
![image](https://user-images.githubusercontent.com/33867249/98077845-eda22700-1eab-11eb-917d-a234dc5d33d5.png)
![image](https://user-images.githubusercontent.com/33867249/98077809-e1b66500-1eab-11eb-9ec0-fc2087a6c255.png)

疑惑的是 我mac电脑可以 window电脑却报这个错误

**Comment by chenjiahan** [comment]
这个 windows 的兼容问题已经在 @vant/cli 的 3.0.0-beta.13 版本修复

**Comment by boliangleung** [comment]
@chenjiahan 作者 请问一下 vant-cli 搭建的话，开发环境 如何开启热更新。
我用webpack配置了  没有效果

**Comment by chenjiahan** [comment]
刚升级了 Webpack5，热更新还有问题，后续会修复

**Comment by boliangleung** [comment]
哈喽，作者。请问现在vant-cli的热更新问题 解决了吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 晚上7:58
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"伯伯伯亮"<786981510@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] @chenjiahan 你好，请问 vant-cli 脚手架可以安装 vue3 吗？如何安装，没找到文档，谢谢 (#7478)





 
刚升级了 Webpack5，热更新还有问题，后续会修复

**Comment by chenjiahan** [comment]
还没，webpack-dev-server 还没发正式版
