### ISSUE TITLE
@chenjiahan 你好，请问 vant-cli 脚手架可以安装 vue3 吗？现在想用类似 npx create-vant-cli-app的项目，但是此项目的vue是2.6.11的。请问有vue3.0的吗

### ISSUE THREAD

**Issue by boliangleung** [youzan/vant#7479]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/7478
