### ISSUE TITLE
Dialog消息确认 取消按钮与确认按钮 苹果手机上没有评分布局

### ISSUE THREAD

**Issue by xiao0413** [youzan/vant#7482]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---
![2504e791873c2b0f3f22ef095c5e943](https://user-images.githubusercontent.com/31560719/97965773-dacd1b00-1df5-11eb-8633-634597a0f189.png)
![2504e791873c2b0f3f22ef095c5e943](https://user-images.githubusercontent.com/31560719/97965796-e28cbf80-1df5-11eb-8f23-9fe65913ccc9.png)

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
