### ISSUE TITLE
[Bug Report] 当下拉菜单放在tab标签中时无法使用

### ISSUE THREAD

**Issue by cleverbao** [youzan/vant#7483]
### 设备 / 浏览器
windows/chrome/firefox

### Vant 版本
3.0.0-beta.6

### Vue 版本
3.0.2

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-tgcq4?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-tgcq4?file=/src/App.vue</a>

### 描述问题
当下拉菜单放在tab标签中时无法使用，当放入默认显示标签时，通过修改高度可用，但是显示有误，其他的标签则不能用，包括根据文档加入重绘的代码也不行。

```html
html:
<van-tabs animated ref="tabs" @change="onChange">

js:
onChange(){
        this.$refs.tabs.resize();
        console.log(this.$refs.tabs);
}
```

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4400

设置 teleport="body" 即可

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4400

设置 teleport="body" 即可
