### ISSUE TITLE
在Android webview中偶尔出现乱码

### ISSUE THREAD

**Issue by qinfeiyang** [youzan/vant#7485]
我实在不知道是webview问题 还是vant问题 所以求救,只是偶尔情况下,并不是每次都有乱码.
编码这些我都是设置了的. 请见图片http://mp.baofy.com/123.jpg
[http://mp.baofy.com/123.jpg](url)

**Comment by chenjiahan** [comment]
目测是 WebView 的问题喔，Vant 不会对文本内容做任何处理
