### ISSUE TITLE
[Bug Report] picker第一个一级区域失效，第二个区域无法选择

### ISSUE THREAD

**Issue by wendzhao** [youzan/vant#7487]
设备 / 浏览器
chrome 86

Vant 版本
2.10.12

Vue 版本
3.0.2

重现链接
http://jsrun.net/zKwKp/edit

描述问题
二级联动的picker，左侧一列，前几个都是disabled: true，只有一个是可选的情况下 picker带出来的，第二列数据和第一列不对应，且无法修改

**Comment by wendzhao** [comment]
还是有一点问题，如果数组中的数据全是disabled话，picker会显示第一列为数组第一个，第二列为children中最后一个。
目前我在您昨天提交的代码基础上，做下列修改，可以解决
cursor = children[defaultIndex].disabled ? children[0] : children[defaultIndex];
@chenjiahan

**Comment by chenjiahan** [comment]
了解了，这种情况我再优化下

**Comment by chenjiahan** [comment]
已在 2.10.13 版本修复
