### ISSUE TITLE
[Bug Report] Toast单例模式问题

### ISSUE THREAD

**Issue by yanyuku** [youzan/vant#7488]
### 设备 / 浏览器
微信开发者工具

### Vant 版本
2.10.12

### Vue 版本
2.6.12

### 重现链接
<a href="https://codepen.io/yanyuku/pen/OJXEBMy?editors=1111" target="_blank">https://codepen.io/yanyuku/pen/OJXEBMy?editors=1111</a>

### 描述问题
Toast单例模式下。
1、创建一个Toast，并设置onClose回调。
2、之后调用Toast.clear()方法会不断出发1中创建的Toast的onClose事件。

**Comment by chenjiahan** [comment]
已在 2.10.13 版本修复
