### ISSUE TITLE
轮播-异步获取轮播图图片-原始图片数组需有默认值占位长度，且长度需要不小于异步获取的图片数量，否则轮播图始终显示第一张

### ISSUE THREAD

**Issue by zxf20090120** [youzan/vant#7492]
轮播-异步获取轮播图图片-原始图片数组需有默认值占位长度，且长度需要不小于异步获取的图片数量，否则轮播图始终显示第一张
e.g.1
data .........  pics:[]
axios.......... {this.pics=['1.jpg','2.jpg']}   
显示1.jpg 

e.g.2
data ........... pics:[,,,]  //初始占位4个长度
axios ......... {this.pics=['1.jpg','2.jpg']}   
正常轮播

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
