### ISSUE TITLE
[Bug Report] uploader  beforeRead  不往下走

### ISSUE THREAD

**Issue by 89360944** [youzan/vant#7493]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0-beta.6

### Vue 版本
3.0.2

### 重现链接
<a href="https://codesandbox.io/s/youthful-cherry-349sk?file=/src/App.vue" target="_blank">https://codesandbox.io/s/youthful-cherry-349sk?file=/src/App.vue</a>

### 描述问题
组件uploader  方法beforeRead  返回return true 不往下走

**Comment by chenjiahan** [comment]
下个版本修复

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.7 版本修复
