### ISSUE TITLE
[Bug Report] ActionBar 和 Switch 样式重叠

### ISSUE THREAD

**Issue by 89360944** [youzan/vant#7494]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0-beta.6

### Vue 版本
3.0.2

### 重现链接
<a href="https://codesandbox.io/s/gallant-smoke-z82p7?file=/src/App.vue" target="_blank">https://codesandbox.io/s/gallant-smoke-z82p7?file=/src/App.vue</a>

### 描述问题
ActionBar 和 Switch  出现在同一位置，Switch 开关（圆圈）在ActionBar之上

**Comment by chenjiahan** [comment]
加个 z-index 就行

```html
<van-action-bar style="z-index: 10">
  <van-action-bar-button type="danger" text="立即购买" />
</van-action-bar>
```
