### ISSUE TITLE
[Feature Request] calendar 可以横向滚动

### ISSUE THREAD

**Issue by gannianyi** [youzan/vant#7495]
### 这个功能解决了什么问题
解决手机端 日历组件横向滚动

### 描述您想要的解决方案
手机端 只显示一横排的几天。左右滑动显示前后的日历。方便在固定的一段时间内，完成日历中设定的日程或者培训内容。

### 建议的API是什么样的
1、起始日期 2、内否左右滑动 3、上下滑动。

**Comment by chenjiahan** [comment]
暂无计划支持呢

**Comment by shimangdian** [comment]
希望可以添加支持

**Comment by Soonze** [comment]
希望可以添加支持
