### ISSUE TITLE
Use babel-plugin-import报错

### ISSUE THREAD

**Issue by xdliuyong** [youzan/vant#750]
ERROR  Failed to compile with 2 errors                                                                                                                                   11:38:01

These dependencies were not found:

* vant/lib/name in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Home.vue
* vant/lib/name/style in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Home.vue

To install them, you can run: npm install --save vant/lib/name vant/lib/name/style

**Comment by xdliuyong** [comment]
.babelrc文件
`{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": [
    "transform-runtime",
    ["import", [{ "libraryName": "vant", "style": true }]]
  ],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}`

**Comment by chenjiahan** [comment]
@xdliuyong babelrc 配置没问题，可以看下你是否引用了错误的组件名称

**Comment by devtip** [comment]
@xdliuyong 你用这个来初始化项目，babelrc配置早已配置好啦。。


![](http://i1.bvimg.com/622450/8f19bcc882b2f579.jpg)

直接像下面这种方式使用就可以了，可能这是最为简单的方式。

``` javascript
// *.vue
import {
  Cell
} from 'vant';

export default {
  components: {
    [Cell.name]: Cell,
  }
}
```

**Comment by wangjun521** [comment]
这个确实有问题 我也这样引用过 压根css样式什么的都没有

**Comment by marscheng1988** [comment]
"style": true  改为  "style": "index.css"
