### ISSUE TITLE
[Feature Request] Area组件希望可以提供一个getValsName的方法

### ISSUE THREAD

**Issue by mynameismaosheng** [youzan/vant#7500]
### 这个功能解决了什么问题
我们通常在表单里提交Area, 而参数也只是保存省市区的code. 但是在查看详情的时候我们碰到了一些问题; 我们只能拿到保存的code 如果想拿到name还需要使用areaList去遍历; 既然Area支持value属性 那是否可以再支持一个方法 比如refs.area.getValsName 获取value所定位到的城市名称数组

### 描述您想要的解决方案
我希望是如果可以添加一个ref增加一个方法 可以过去传入value的对应的城市名称的数组就好了

### 建议的API是什么样的
暂无想法

**Comment by chenjiahan** [comment]
暂无计划支持喔，这个自行遍历就好，在目前的数据格式下是很容易遍历的
