### ISSUE TITLE
SwipeCell 描述自定义换行

### ISSUE THREAD

**Issue by li308870559** [youzan/vant#7501]
![image](https://user-images.githubusercontent.com/46514939/98183661-9e0f3a00-1f43-11eb-9712-7169f74247aa.png)

参考 #7480 

这样是可以进行换行，但是我想自自定义换行可以实现吗？比如加个<br>
或者其他方法换行。因为我显示的东西可能不是一样的不想在同一行，目前是长度达到随机换行，需要自定义换行进行显示。

**Comment by ZhengXiaowei** [comment]
这一块是`swipe-cell`包裹着`card`组件吧？`card`组件的`desc`可以是插槽 可以自定义这块的结构的

**Comment by li308870559** [comment]
> 这一块是`swipe-cell`包裹着`card`组件吧？`card`组件的`desc`可以是插槽 可以自定义这块的结构的

是在van-swipe-cell 标签下的。desc如何进行自定义？目前是这样子的字符串
![image](https://user-images.githubusercontent.com/46514939/98186750-66f05700-1f4a-11eb-9730-77022a2013a5.png)

**Comment by ZhengXiaowei** [comment]
这是`card`组件的事了 和`swipe-cell`关系不大。
你可以试试
```
<van-card title="商品标题">
    <div slot="desc">
       <p>描述一</p>
       <p>描述二</p>
    </div>
</van-card>
```
这样试试

**Comment by li308870559** [comment]
> 这是`card`组件的事了 和`swipe-cell`关系不大。
> 你可以试试
> 
> ```
> <van-card title="商品标题">
>     <div slot="desc">
>        <p>描述一</p>
>        <p>描述二</p>
>     </div>
> </van-card>
> ```
> 
> 这样试试

好的，感谢！我也找到另外一种方法了

<van-card title="商品标题">
     <template #bottom>
           <p>描述一</p>
           <p>描述二</p>
     </template>
</van-card>

**Comment by li308870559** [comment]
> > 这是`card`组件的事了 和`swipe-cell`关系不大。
> > 你可以试试
> > ```
> > <van-card title="商品标题">
> >     <div slot="desc">
> >        <p>描述一</p>
> >        <p>描述二</p>
> >     </div>
> > </van-card>
> > ```
> > 
> > 
> > 这样试试
> 
> 好的，感谢！我也找到另外一种方法了

`</van-card>
     <template #bottom>
              <p>描述一</p>
              <p>描述二</p>
        </template>
  </van-card>`

**Comment by ZhengXiaowei** [comment]
你这也是插槽 `card`组件几乎所有位置都可以用插槽自定义
