### ISSUE TITLE
[Bug Report] swipe轮播重影

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#7502]
### 设备 / 浏览器
苹果6s-ios13.4.1-微信浏览器7.0.17

### Vant 版本
2.10.1

### Vue 版本
2.5.20

### 重现链接
<a href="https://codesandbox.io/s/vue-template-forked-sm8df?file=/src/components/HelloWorld.vue" target="_blank">https://codesandbox.io/s/vue-template-forked-sm8df?file=/src/components/HelloWorld.vue</a>

### 描述问题
轮播图出现重影，我将vant升级到最新版本（2.10.12），bug消失，由于信息保密原因不方便公开代码！
视频为证（vant-2.10.1）
<a href="https://v.youku.com/v_show/id_XNDk0Mjk5NDk0MA==.html" target="_blank">https://v.youku.com/v_show/id_XNDk0Mjk5NDk0MA==.html</a>

**Comment by chenjiahan** [comment]
既然最新版没问题，那就升级呗

**Comment by cangyu1993** [comment]
不行了，上午还好好的，下午最新版本又重现了。。。。

**Comment by chenjiahan** [comment]
目测是浏览器的渲染问题，组件这边没啥能处理的
