### ISSUE TITLE
[Bug Report] NavBar无法兼容IOS设备

### ISSUE THREAD

**Issue by cf1991** [youzan/vant#7503]
### 设备 / 浏览器
iPhone 7plus

### Vant 版本
2.10.3

### Vue 版本
2.6.1

### 重现链接
<a href="https://gitee.com/wangding1044/solax-cloud/issues/I2437O" target="_blank">https://gitee.com/wangding1044/solax-cloud/issues/I2437O</a>

### 描述问题
顶部导航与手机状态栏重合

**Comment by chenjiahan** [comment]
已在 2.10.13 版本新增 safe-area-inset-top 属性，开启后会自动适配 iOS 顶部安全区
