### ISSUE TITLE
van-uploader在安卓Apk中multiple不起效果，只能选一张图片

### ISSUE THREAD

**Issue by chenxwei** [youzan/vant#7505]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/98243421-e3b21e00-1fa8-11eb-8f62-f56dc9e948e2.png)
