### ISSUE TITLE
[Bug Report] van-uploader在安卓apk中multiple不生效，只能选一张图片

### ISSUE THREAD

**Issue by chenxwei** [youzan/vant#7506]
### 设备 / 浏览器
安卓手机

### Vant 版本
3.0.0-beta.6

### Vue 版本
3.0.2

### 重现链接
<a href="http://vant-contrib.gitee.io/vant-issue-generater/#/zh-CN" target="_blank">http://vant-contrib.gitee.io/vant-issue-generater/#/zh-CN</a>

### 描述问题
在手机端浏览器是可以选多张，打包成apk就只能选一张。

**Comment by snowdream** [comment]
同问。
