### ISSUE TITLE
[Bug Report] sku 设置 initial-sku 2.8.7版本还是正常的，2.9.0及之后的版本设置initial-sku 无效

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant#7509]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.7

### Vue 版本
2.6.10

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/sku" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/sku</a>

### 描述问题
sku 设置 initial-sku 2.8.7版本还是正常的，用getSkuData 可以获取到设置的默认sku值，升级 2.9.0及之后的版本，设置initial-sku 无效，getSkuData 获取不到设置的sku

**Comment by anihCevol** [comment]
initial-sku 的值是按文档上格式设置的，应该是没问题的，升级2.9.0之前是正常的。

**Comment by anihCevol** [comment]
![image](https://user-images.githubusercontent.com/42430384/98315718-d4b48580-2013-11eb-8a0e-3add5397dbc1.png)
![image](https://user-images.githubusercontent.com/42430384/98315757-f6ae0800-2013-11eb-9f5e-30c2b051e3ed.png)

**Comment by anihCevol** [comment]
第一个图vant版本是2.9.0 ，第二个图是2.8.7 。

**Comment by chenjiahan** [comment]
能提供个 codesandbox 复现链接么
