### ISSUE TITLE
[Bug Report] Checkbox 复选框问题

### ISSUE THREAD

**Issue by yanyuku** [youzan/vant#7511]
### 设备 / 浏览器
微信开发者工具

### Vant 版本
2.10.12

### Vue 版本
2.6.12

### 重现链接
<a href="https://codepen.io/yanyuku/pen/gOMjVEq" target="_blank">https://codepen.io/yanyuku/pen/gOMjVEq</a>

### 描述问题
当复选框disabled属性为true时，调用toggle或者toggleAll方法还能切换状态。

**Comment by xiaotiansky1** [comment]
我不觉得这是bug

**Comment by chenjiahan** [comment]
toggle 和 toggleAll 是由开发者主动触发的，所以 disabled 不会阻止这两个行为，建议自行判断一下，并跳过 disabled 的复选框
