### ISSUE TITLE
[Bug Report] van-calendar组件加入formatter函数会报type of undefined

### ISSUE THREAD

**Issue by HuangWeiBin2** [youzan/vant#7512]
### 设备 / 浏览器
微信开发工具

### Vant 版本
2.10.12

### Vue 版本
2.6.12

### 重现链接
<a href="https://codepen.io/huangweibin2/pen/qBNMBNe" target="_blank">https://codepen.io/huangweibin2/pen/qBNMBNe</a>

### 描述问题
  <van-calendar
                    type="single"
                    :color="'#1296DB'"
                    :show-title="false"
                    :show-subtitle="false"
                    :poppable="false"
                    :show-confirm="false"
                    :row-height="50"
                    :min-date="minDate"
                    :default-date="defaultDate"
                    @select="calendarSelect"
                    :style="{ height: '25rem' }"
                    :month-show="monthShowMethods"
                    :formatter="formatter"
            >
            </van-calendar>
cdn引入方式

**Comment by chenjiahan** [comment]
请按照文档里的用法来使用 formatter，在 formatter 中需要返回 day 对象

**Comment by HuangWeiBin2** [comment]
> 请按照文档里的用法来使用 formatter，在 formatter 中需要返回 day 对象

好的，这疏忽了。谢谢。
但是还有个问题，平铺模式下，@month-show 这个默认会触发四个日期。一个是控制的最小日期，一个是最小日期+1月。另外三个是当前月份、当前月份前后一月都会触发出来。。然后滑动触发也是有bug。  向下滑动@month-show回调函数Date会变成当前月份+1月。向上滚动会变成当前月份-1月。不知道这个是怎么回事。始终不能回调当前月份。这个怎么解决？

**Comment by chenjiahan** [comment]
month-show 的问题已在 2.10.14 版本优化

**Comment by HuangWeiBin2** [comment]
> month-show 的问题已在 2.10.14 版本优化

 <van-calendar
                    type="single"
                    lazy-render
                    :color="'#1296DB'"
                    :show-title="false"
                    :show-subtitle="false"
                    :poppable="false"
                    :show-confirm="false"
                    :row-height="50"
                    :min-date="minDate"
                    :default-date="defaultDate"
                    @select="calendarSelect"
                    :style="{ height: '25rem' }"
                    @month-show="monthShowMethods"
                    :formatter="formatter"
            >
            </van-calendar>

引入cdn最新版本后，@month-show默认会触发几个月。上下滑动也是一样触发不了。

**Comment by HuangWeiBin2** [comment]
![image](https://user-images.githubusercontent.com/57486245/99204645-44cfc200-27f1-11eb-8866-d41d208e90b4.png)

**Comment by chenjiahan** [comment]
来个 codesandbox 复现链接看下？

**Comment by HuangWeiBin2** [comment]
> 来个 codesandbox 复现链接看下？
> 
> https://codesandbox.io/s/m5v3f

https://codesandbox.io/s/vant-issue-moban-forked-8inuq?file=/src/App.vue:0-1179
我不知道为什么。现在复现链接是可以向下滑动触发，触发之后向上不触发，第二次下滑不触发。搞不懂

**Comment by chenjiahan** [comment]
每个月份的 month-show 只会触发一次喔

**Comment by xinnianyoulin** [comment]
现在有个需求就是日历和外部快捷选择月份的Picker可以互相联动，但是现在只触发一次没法监听变化了 T.T
