### ISSUE TITLE
[Feature Request] [van-index-anchor] Automatic generation of index Anchor

### ISSUE THREAD

**Issue by stritti** [youzan/vant#7518]
### What problem does this feature solve
Generation of index list with automatic alphabetic anchors

### Describe the solution you'd like
just pass a list of alphabetic sorted items

### What does the proposed API look like
<van-index-bar index-anchors="auto|alpha|custom">

**Comment by stritti** [comment]
Could simplify for example this component:
https://github.com/stritti/covid-ampel-widget/blob/main/src/components/Landkreise.vue

**Comment by chenjiahan** [comment]
Thanks for the suggestion, but we currently have no plans to support this feature.

There are some user-defined components between each index anchor, it's hard to design an API to automatically generate index anchors.
