### ISSUE TITLE
[Bug Report] calendar 组件 default-date 属性导致日历不显示

### ISSUE THREAD

**Issue by Elvmx** [youzan/vant#7519]
### 设备 / 浏览器
Google Chrome 86.0.4240.80

### Vant 版本
3.0.0-beta.7

### Vue 版本
3.0.2

### 重现链接
<a href="https://jsbin.com/lahasavoyu/edit?html,output" target="_blank">https://jsbin.com/lahasavoyu/edit?html,output</a>

### 描述问题
calendar 组件 default-date 属性设置为 null 会导致日历不显示

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.8 版本修复
