### ISSUE TITLE
vant safe-area-inset-top属性无效

### ISSUE THREAD

**Issue by cf1991** [youzan/vant#7520]
### 设备 / 浏览器
iPhone 7 plus

### Vant 版本
2.10.13

### Vue 版本
2.6.11

### 重现链接
<a href="https://gitee.com/wangding1044/solax-cloud/issues/I24FVZ" target="_blank">https://gitee.com/wangding1044/solax-cloud/issues/I24FVZ</a>

### 描述问题
根据官方文档升级了vant版本，在navbar上增加了safe-area-inset-top属性，但是在真机上运行时还是无法进行安全区域适配

**Comment by chenjiahan** [comment]
需要配置 viewport，参见 https://youzan.github.io/vant/#/zh-CN/advanced-usage#di-bu-an-quan-qu-gua-pei
