### ISSUE TITLE
TreeSelect 分类选择支持多级选择吗？目前只支持了两级

### ISSUE THREAD

**Issue by mawen741** [youzan/vant#7529]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
不支持呢，暂时没有计划支持多级选择

**Comment by JackDan9** [comment]
您好！如果不支持多级我觉得是不是可以在文档上增加一下说明了，TreeSelect组件只支持两级。

[https://youzan.github.io/vant/#/zh-CN/tree-select](https://youzan.github.io/vant/#/zh-CN/tree-select)

 @chenjiahan

**Comment by naifen00** [comment]
可以用slot 套娃🪆

**Comment by SheepYang1993** [comment]
套娃样式看起来很丑
