### ISSUE TITLE
[Bug Report] Vant-Cli  postcss自定义配置不支持数组格式插件

### ISSUE THREAD

**Issue by luichooy** [youzan/vant#7530]
### 设备 / 浏览器
 alll

### Vant 版本
2.10.13

### Vue 版本
3.0.2

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/packages/vant-cli/src/config/postcss.config.ts" target="_blank">https://github.com/youzan/vant/blob/dev/packages/vant-cli/src/config/postcss.config.ts</a>

### 描述问题
Vant-Cli 工具将  postcss 配置对象中的 plugins 定义为一个对象，并且采用对象合并，导致自定义的插件无法以数组形式传入。
![postcss](https://user-images.githubusercontent.com/26423033/98622500-a355f580-2344-11eb-8d1e-ca59907d5d4b.png)

**Comment by chenjiahan** [comment]
已在 @vant/cli@2.6.2 版本支持
