### ISSUE TITLE
[Bug Report] build后 van-dialog渲染失败

### ISSUE THREAD

**Issue by caojian123** [youzan/vant#7536]
### 设备 / 浏览器
pc，手机

### Vant 版本
2.10.8

### Vue 版本
2.5.7

### 描述问题
van-dialog 标签未正确渲染, 可以打开开发者面板查看 Elements
![image](https://user-images.githubusercontent.com/10811653/98754889-85e76100-2402-11eb-8711-63f32d8195b9.png)

```
import {Toast, Dialog } from 'vant';
Vue.use(Dialog)
```

**Comment by caojian123** [comment]
已解决

**Comment by alwio** [comment]
> 已解决

怎么解决的？
