### ISSUE TITLE
[Bug Report] 商品sku初始化商品选择数量无效

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant#7537]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.9.2

### Vue 版本
2.6.11

### 描述问题
![image](https://user-images.githubusercontent.com/23445650/98761572-b504cf00-2410-11eb-94af-6f364ba7e763.png)
如上图，initialSku.selectedNum初始化之后，展示sku，默认选择数量依然是1

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by Gitsifu** [comment]
复现链接：[https://codesandbox.io/s/vant-issue-moban-forked-6y4fm](https://codesandbox.io/s/vant-issue-moban-forked-6y4fm)
原因如下图，不清楚具体原因，难道这两种写法，赋值出来的对象会不一样吗？
![image](https://user-images.githubusercontent.com/23445650/98887993-f3ae8e00-24d1-11eb-965b-57261e4bd621.png)

**Comment by chenjiahan** [comment]
在 Vue 里需要使用第一种的写法，否则不会触发响应式更新
