### ISSUE TITLE
[Feature Request] picker/cascader组件加入value配置

### ISSUE THREAD

**Issue by zsjyjishukong** [youzan/vant#7538]
### 这个功能解决了什么问题
当picker组件使用的数据和显示不一致时，简化开发者操作

### 描述您想要的解决方案
picker column配置: [{value: 1, label: 'a'}, {value: 2, label: 'b'}]，可绑定value，唤起通过value自动定位至所选择位置， cascader（级联选择）同理，具体参考ant-design-vue 对选择器和级联选择器的处理

### 建议的API是什么样的
暂无api

**Comment by Becessary** [comment]
多列 columns 级联选择模式 ，有初始值 情况下，通过当前的再各个对象中设置 defaultIndex 是一个非常不友好的方式。
建议 增加 多列模式下 设置 defaultIndex 为数组。各自对应选中索引值。

**Comment by chenjiahan** [comment]
新增 Cascader 组件提供了 value 配置，可以先试下。

Picker 后续跟进

**Comment by zsjyjishukong** [comment]
> 新增 Cascader 组件提供了 value 配置，可以先试下。
> 
> Picker 后续跟进

OK，很强！

**Comment by JasonBoy** [comment]
> 新增 Cascader 组件提供了 value 配置，可以先试下。
> 
> Picker 后续跟进

大佬Picker跟进了没？

**Comment by JasonBoy** [comment]
> > 新增 Cascader 组件提供了 value 配置，可以先试下。
> > Picker 后续跟进
> 
> 大佬Picker跟进了没？

似乎可以同 `value-key="value"` , 然后label显示用 `option` slot

**Comment by zsjyjishukong** [comment]
> > 新增 Cascader 组件提供了 value 配置，可以先试下。
> > Picker 后续跟进
> 
> 大佬Picker跟进了没？

看起来似乎还没有跟进，不过picker还算比较简单，最近用到的时候拿到返回的label后对原数据find就可以找到，不过就是不太方便，希望尽快解决吧

**Comment by Becessary** [comment]
你好，不好意思，最近再忙其他事情，还没有看。不过，相信你们的，肯定会越来越好。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 晚上8:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] picker/cascader组件加入value配置 (#7538)





  
新增 Cascader 组件提供了 value 配置，可以先试下。
 
Picker 后续跟进
  
大佬Picker跟进了没？

**Comment by shady-xia** [comment]
希望能够早点提上日程，在下拉菜单中，key-value形式的数据更加标准化

**Comment by chenjiahan** [comment]
4.0 版本会重构 Picker 组件，参见 https://github.com/youzan/vant/pull/10208
