### ISSUE TITLE
 官方对于van-calendar  的文档 <van-calendar v-model="show" :show-confirm="false"/>

### ISSUE THREAD

**Issue by puremdq** [youzan/vant#7540]
官方对于   calendar  的文档 <van-calendar v-model="show" :show-confirm="false"/>有误应该为
 <van-calendar v-model:show="show" :show-confirm="false"/>

**Comment by chenjiahan** [comment]
请确认你看的是 Vant 3.x 版本的文档

**Comment by puremdq** [comment]
当然是Vant 3.x

**Comment by chenjiahan** [comment]
目前搜索确实有问题，后续会优化下
