### ISSUE TITLE
[Bug Report] 分页组件 v-model 无法手动设置当前页

### ISSUE THREAD

**Issue by gdrpAPeng** [youzan/vant#7541]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.2

### Vue 版本
3.0.2

### 重现链接
<a href="https://codepen.io/gdrpapeng/pen/OJXaEGe" target="_blank">https://codepen.io/gdrpapeng/pen/OJXaEGe</a>

### 描述问题
使用 v-model 无法手动设置当前页，使用 :value 可以，但是！！！！文档并没有 value 这个字段描述！！！！
由于时间问题，重现链接只提供了 html 样板，无法提供 demo，请见谅！！
 "nuxt": "^2.0.0",  "vant": "^2.10.2",

**Comment by chenjiahan** [comment]
v-model 是一个语法糖，它本身就是可以和 value 互相转换的，你可以看下 Vue 官方文档里对 v-model 的解释。

另外我这边 v-model 是可以使用的，建议你再试下。
