### ISSUE TITLE
[Bug Report] popup组件在谷歌浏览器下有弹出卡顿问题

### ISSUE THREAD

**Issue by OctoberToEscape** [youzan/vant#7542]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
3.0.0-beta.7

### Vue 版本
3.0.0

### 重现链接
<a href="https://e.coding.net/xiaoyatech/zhishiquan/zhishiquan.git" target="_blank">https://e.coding.net/xiaoyatech/zhishiquan/zhishiquan.git</a>

### 描述问题
弹出层弹出的时候，应该是有个从底部弹出来的效果，可是浏览器警告Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.，然鹅这个弹出效果就会很卡顿，就像display：block控制的一样

**Comment by chenjiahan** [comment]
链接无法打开，麻烦提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by chinarma** [comment]
同样问题，

-----------main.js---------
const app = createApp(App);
import { Dialog } from "vant";
app.use(Dialog);
----------component 内部--------
setup()=>{
        const app = getCurrentInstance();

   const showDialog=()=>{
            app.ctx.$dialog({ message: "提示" });

}

return {showDialog}

}
---------chrome 输出-------
runtime-dom.esm-bundler-e3c9346b.js:8230 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
