### ISSUE TITLE
[Bug Report] vant click-preview事件点击预览图没有触发

### ISSUE THREAD

**Issue by zDOUBEL** [youzan/vant#7543]
### 设备 / 浏览器
谷歌

### Vant 版本
2.10.13

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
图片上传图片成功后，点击预览图， 使用click-preview   事件没有触发，控制台未打印，
因为不能上传图，是不是属性之间有冲突，还是使用方式不对，求助，谢谢大佬
   <van-uploader :click-preview="showRreview" :disabled="item.editable==0?true:false" :deletable="!(item.editable==0?true:false)" accept='image/*' :multiple="true" type='file'
                              :name="item.fieldname" :after-read="afterRead" preview-size="80px" v-model="item.filelist" :preview-options="prview" />

methods ：
    showRreview(file, detail) {
      console.log(1, file)
    },

**Comment by zDOUBEL** [comment]
这是我的代码：  
  <van-uploader :click-preview="showRreview" :disabled="item.editable==0?true:false" :deletable="!(item.editable==0?true:false)" accept='image/*' :multiple="true" type='file'
                              :name="item.fieldname" :after-read="afterRead" preview-size="80px" v-model="item.filelist" :preview-options="prview" />
官方的代码：
<van-uploader v-model="fileList" multiple :click-preview="aa" />

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by zDOUBEL** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

你好，https://codesandbox.io/s/vant-issue-moban-forked-fyf0w?file=/src/App.vue  麻烦看看谢谢

**Comment by chenjiahan** [comment]
Vue 里事件监听的写法是 @click-preview，而不是 :click-preview

**Comment by zDOUBEL** [comment]
> Vue 里事件监听的写法是 @click-preview，而不是 :click-preview

非常感谢，我可能脑子离家出走了... 硬是没有想到...捂脸.jpg
