### ISSUE TITLE
[Feature Request] 急！ DropdownMenu 下拉菜单 增加icon插槽

### ISSUE THREAD

**Issue by jiahuamld** [youzan/vant#7547]
### 这个功能解决了什么问题
DropdownMenu 下拉菜单上部点击是只可以设置title 无法slot 放置图标 紧急

### 描述您想要的解决方案
van-dropdown-item(:title="标题",:icon="chat",ref="baseCheckboxList")    增加 :icon="chat" 或加一个slot   配置顶部title区域内容

### 建议的API是什么样的
van-dropdown-item(:title="标题",:icon="chat",ref="baseCheckboxList")    增加 :icon="chat" 或加一个slot   配置顶部title区域内容

**Comment by jiahuamld** [comment]
> ### 这个功能解决了什么问题
> DropdownMenu下拉菜单顶部点击是只可以传title无法slot 自定义图标 或者布局
> 
> ### 描述您想要的解决方案
> van-dropdown-item（：title =“标题”，：icon =“ chat”，ref =“ baseCheckboxList”）增加：icon =“ chat”或加一个插槽配置顶部标题区域内容
> 
> ### 建议的API是某种的
> van-dropdown-item（：title =“标题”，：icon =“ chat”，ref =“ baseCheckboxList”）增加：icon =“ chat”或加一个插槽配置顶部标题区域内容

**Comment by jiahuamld** [comment]
> ### 这个功能解决了什么问题
> DropdownMenu 下拉菜单上部点击是只可以设置title 无法slot 放置图标 紧急
> 
> ### 描述您想要的解决方案
> van-dropdown-item(:title="标题",:icon="chat",ref="baseCheckboxList") 增加 :icon="chat" 或加一个slot 配置顶部title区域内容
> 
> ### 建议的API是什么样的
> van-dropdown-item(:title="标题",:icon="chat",ref="baseCheckboxList") 增加 :icon="chat" 或加一个slot 配置顶部title区域内容

vant 2.10

**Comment by chenjiahan** [comment]
DropdownItem 目前就有 title 插槽的，可以用于自定义内容
