### ISSUE TITLE
[Bug Report] IndexBar 索引栏 在dialog中展示的位置偏移

### ISSUE THREAD

**Issue by mbsg** [youzan/vant#7548]
### 设备 / 浏览器
Firefox 82/Chrome 86

### Vant 版本
2.10.13

### Vue 版本
2.6.12

### 重现链接
<a href="https://sm.ms/image/oWCUS3kuV5JBePG" target="_blank">https://sm.ms/image/oWCUS3kuV5JBePG</a>

![Screenshot_2020-11-13 预约单详情.png](https://i.loli.net/2020/11/13/oWCUS3kuV5JBePG.png)

### 描述问题
当在dialog中使用IndexBar时，激活状态的indexbar会偏移dialog的宽度

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接
