### ISSUE TITLE
[Feature Request] Automatic support of dark mode

### ISSUE THREAD

**Issue by stritti** [youzan/vant#7551]
### What problem does this feature solve
Would be awesome if the components could respect dark mode if enabled in operating system.

### Describe the solution you'd like
two sets of colour variables which will be switched automatic.

See at https://github.com/stritti/covid-ampel-widget
There I tried to start partial solution.

### What does the proposed API look like
No special API required.

**Comment by stritti** [comment]
See here for possible start: https://github.com/stritti/covid-ampel-widget/blob/5ccb1710ffaf38e88da6df82337d7533cb4dc7af/src/assets/theme-vars.less#L73

**Comment by chenjiahan** [comment]
We have plans to support dark mode, but currently our design specifications do not include the dark mode UI, and we need to discuss with our designers first.

Maybe in Vant 4.0 we will provide automatic support of dark mode.
