### ISSUE TITLE
地址列表组件,超过最大高度后不显示滚动条

### ISSUE THREAD

**Issue by ipconfig12138** [youzan/vant#7553]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---在Dialog组件中放入AddressList组件。当地址数量超过列表的最大高度后不显示滚动条

如图所示

> 
![VE}`6`HCY}0Z$YKXD你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---在Dialog组件中放入AddressList组件。当地址数量超过列表的最大高度后不显示滚动条

如图所示

> 
XIHM](https://user-images.githubusercontent.com/29529193/99143365-beec3380-2697-11eb-8358-f4f2ec7cf8eb.png)

**Comment by chenjiahan** [comment]
可以在 Dialog 或 AddressList 上设置 overflow-y: scroll
