### ISSUE TITLE
picker和area建议

### ISSUE THREAD

**Issue by linwenfeng122** [youzan/vant#756]
正常来说pick和area最好做成按钮点击（带背景）弹出来的，不然感觉自己还要去布局组件的样式，感觉有点奇怪。希望能优化

**Comment by chenjiahan** [comment]
一般是搭配 Popup 组件

**Comment by linwenfeng122** [comment]
哦，这样啊。感觉可以在picker和area那边添加一个建议，如果要实现点击弹出，推荐和popup组件使用

**Comment by chenjiahan** [comment]
好的，我们会在文档里补充

**Comment by chenjiahan** [comment]
已补充
