### ISSUE TITLE
[Feature Request] NumberKeyBoard数字键盘组件，定位问题

### ISSUE THREAD

**Issue by liuyilong830** [youzan/vant#7563]
### 这个功能解决了什么问题
由于该组件使用了position：fixed进行定位，那么如果该组件使用在祖先元素有transform属性的元素中，则会导致定位问题出错

### 描述您想要的解决方案
希望设置一个renderOfBody的方式，将其渲染在body元素下，方可解决这类问题

### 建议的API是什么样的
<number-keyboard v-model="value" :show="show" @blur="show = false" renderOfBody></number-keyboard>

**Comment by chenjiahan** [comment]
使用 get-container  属性即可
