### ISSUE TITLE
[Feature Request] 使用 Calendar 选择时  期望能 开始日期和结束日期是同一天  怎么整

### ISSUE THREAD

**Issue by qwer630701** [youzan/vant#7568]
### 这个功能解决了什么问题
当日期范围允许 条件的开始时间和结束时间是同一天时  进行查询

### 描述您想要的解决方案
当日期范围允许 条件的开始时间和结束时间是同一天时  进行查询

### 建议的API是什么样的
如果可以的话  直接允许 开始时间 和 结束时间为同一天  不是更好么

**Comment by chenjiahan** [comment]
设置 allow-same-day 属性即可。
