### ISSUE TITLE
请问用webstorm时template里面写组件时为什么不能自动联想补全

### ISSUE THREAD

**Issue by xuuuu** [youzan/vant#757]

**Comment by PedroGao** [comment]
ide对.vue文件的支持并不是特别好

**Comment by xuuuu** [comment]
@PedroGao 我最新的webstorm已经加入了对vue的支持, mint-ui的都能直接联想补全的, 这个只能提示个vant-node, 不懂, 不知道是哪里的问题

**Comment by chenjiahan** [comment]
@xuuuu 感谢反馈，后续会看一下这个问题

**Comment by xuuuu** [comment]
@chenjiahan 谢谢:)

**Comment by PedroGao** [comment]
没用过webstorm，用不起😩

**Comment by xuuuu** [comment]
@PedroGao 哈哈, 没事, 我也可以试试vs code, 就是idea全家桶用习惯了

**Comment by Estelle00** [comment]
我也是这个问题 请问最后怎么解决的呢

**Comment by chenjiahan** [comment]
目前可以通过 idea 插件进行自动联想补全
插件地址：https://github.com/Rickykurt/VantPlugin
