### ISSUE TITLE
[Feature Request] popup 新增 close-icon 的点击事件

### ISSUE THREAD

**Issue by Becessary** [youzan/vant#7570]
### 这个功能解决了什么问题
采用 非 v-model:show 形式情况下，想通过点击 x 关闭popup，简直不行。close竟然只是 popup关闭后的回调，这不是反人类么。如果仅是单纯的v-model:show值为false的回调，用watch不一样了嘛。

### 描述您想要的解决方案
给close-icon加一个回调，或者 close上。

### 建议的API是什么样的
点击 close-icon，close事件被调

**Comment by chenjiahan** [comment]
已在 3.0.0-beta.9 版本增加 click-close-icon 事件
