### ISSUE TITLE
[Feature Request] Rate组件允许小数显示

### ISSUE THREAD

**Issue by 297cwrun** [youzan/vant#7571]
### 这个功能解决了什么问题
当使用Rate组件显示可读状态的多人评分结果时，当前的设计难以支持这种显示。例如3.4与3.5实际上区别不大，但却一个显示3星，一个显示3.5星，显得不太合理。

### 描述您想要的解决方案
支持设置allow-half后，显示例如3.4/3.8分这类的结果。

### 建议的API是什么样的
与原有保持一致，只对生成半星的逻辑进行改动。

**Comment by chenjiahan** [comment]
已在 3.0.14 版本支持
