### ISSUE TITLE
[Bug Report] icon全部没了

### ISSUE THREAD

**Issue by is-liyiwei** [youzan/vant#7575]
### 设备 / 浏览器
移动端

### Vant 版本
2.10.14

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/" target="_blank">https://codesandbox.io/</a>

### 描述问题
上面的重现链接可以忽略，就是今天启动一个项目，发现vant里面的icon全部都没有了

**Comment by chenjiahan** [comment]
链接无效，麻烦重新提供下

**Comment by is-liyiwei** [comment]
抱歉，原来是我们自己设置了font-family的important的问题，导致覆盖了vant的字体优先级，问题已经解决了

**Comment by chenjiahan** [comment]
好的👌
