### ISSUE TITLE
Picker 选择器级联选择怎么设置默认值

### ISSUE THREAD

**Issue by wade419** [youzan/vant#7576]
Picker 选择器级联选择怎么设置默认值，比如修改页面需要查看已经保存的值，怎么设置

**Comment by Silent-Jude** [comment]
这么巧啊，我也在提这个问题哈哈哈哈哈。刚写完issue，发现你也提了一个

**Comment by wade419** [comment]
> 这么巧啊，我也在提这个问题哈哈哈哈哈。刚写完issue，发现你也提了一个

是啊，vant文档不全，弄了半天还没解决

**Comment by Silent-Jude** [comment]
> > 这么巧啊，我也在提这个问题哈哈哈哈哈。刚写完issue，发现你也提了一个
> 
> 是啊，vant文档不全，弄了半天还没解决

我有一个歪主意，搞定了需求。
我发现级联的时候，给每一级设置defaultIndex，会对下一级生效，也就是第二级会成功设置默认效果。
那么第一级怎么办呢？
pickerData是原来的数组，然后给第一级包一层，变成这个结构：
[
        {
          defaultIndex: 1,
          children: this.pickerData,
          text: ''
        }
]
这样第一级就生效了。
缺点是，会多出一列空白的 。

然后再想办法把这一列给删除掉就可以    (*^▽^*)   你也可以试试

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/7577

**Comment by wade419** [comment]
> > > 这么巧啊，我也在提这个问题哈哈哈哈哈。刚写完issue，发现你也提了一个
> > 
> > 
> > 是啊，vant文档不全，弄了半天还没解决
> 
> 我有一个歪主意，搞定了需求。
> 我发现级联的时候，给每一级设置defaultIndex，会对下一级生效，也就是第二级会成功设置默认效果。
> 那么第一级怎么办呢？
> pickerData是原来的数组，然后给第一级包一层，变成这个结构：
> [
> {
> defaultIndex: 1,
> children: this.pickerData,
> text: ''
> }
> ]
> 这样第一级就生效了。
> 缺点是，会多出一列空白的 。
> 
> 然后再想办法把这一列给删除掉就可以 (_^▽^_) 你也可以试试

你使用setIndexes这个解决了没

**Comment by Silent-Jude** [comment]
> > > > 这么巧啊，我也在提这个问题哈哈哈哈哈。刚写完issue，发现你也提了一个
> > > 
> > > 
> > > 是啊，vant文档不全，弄了半天还没解决
> > 
> > 
> > 我有一个歪主意，搞定了需求。
> > 我发现级联的时候，给每一级设置defaultIndex，会对下一级生效，也就是第二级会成功设置默认效果。
> > 那么第一级怎么办呢？
> > pickerData是原来的数组，然后给第一级包一层，变成这个结构：
> > [
> > {
> > defaultIndex: 1,
> > children: this.pickerData,
> > text: ''
> > }
> > ]
> > 这样第一级就生效了。
> > 缺点是，会多出一列空白的 。
> > 然后再想办法把这一列给删除掉就可以 (_^▽^_) 你也可以试试
> 
> 你使用setIndexes这个解决了没

我并没有使用setIndexes ，用的是上述我说的方案。
遍历数组，增加默认的defaultIndex，
而最外层就再包一层，同时增加defaultIndex，这样最前面会多出一列空白的。
然后通过css深度选择器，找到多出来的这一列，设置display:none，效果挺不错的。
