### ISSUE TITLE
[Bug Report] Picker 选择器中，多列级联选择如何设置默认选中项？

### ISSUE THREAD

**Issue by Silent-Jude** [youzan/vant#7577]
### 设备 / 浏览器
安卓

### Vant 版本
2.10.14

### Vue 版本
3.0.2

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/picker#column-shu-ju-jie-gou" target="_blank">https://youzan.github.io/vant/#/zh-CN/picker#column-shu-ju-jie-gou</a>

### 描述问题
请问 Picker 选择器中，多列级联选择如何设置默认选中项？
看文档中只有单列时使用：default-index
多列非级联时使用：defaultIndex
但是多列级联时，应该如何默认选中呢？

**Comment by chenjiahan** [comment]
除了 defaultIndex 外，还可以通过实例上的 setIndexes 方法设置直接设置。

后续会支持更简单的设置方式，比如通过 value 设置，参见 https://github.com/youzan/vant/issues/7538

**Comment by wade419** [comment]
> setIndexes

setIndexes 怎么设置多列的默认值啊？
