### ISSUE TITLE
关于Tab组件的点击事件

### ISSUE THREAD

**Issue by VenusPP** [youzan/vant#758]
给Tab组件绑定点击事件时只能获取索引号作为参数,可否以title或其它值作为参数呢?

**Comment by cookfront** [comment]
点击事件有什么场景会用到title？

**Comment by VenusPP** [comment]
起初后台需要传title作为参数,后已协商好.

**Comment by cookfront** [comment]
这个tabs数据是动态获取的么？存了索引就能从tabs存的数据里取到title等任何其他信息了
