### ISSUE TITLE
"export 'picker' was not found in 'vant' 在vant中找不到picker

### ISSUE THREAD

**Issue by jojoname** [youzan/vant#7582]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

安装Vant 2.x 版本： 安装卸载了多次但是依旧提示未能找到

**Comment by chenjiahan** [comment]
picker 是大写的，Picker
