### ISSUE TITLE
[Bug Report] can not reset datetime picker value properly

### ISSUE THREAD

**Issue by hirohe** [youzan/vant#7589]
### 设备 / 浏览器
Windows 10 / Chorme 87

### Vant 版本
2.10.14

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-3bj7l" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-3bj7l</a>

### 描述问题
I am using `van-field` and `van-datetime-picker` to make a date select field with reset feature.

[codesandbox](https://codesandbox.io/s/vant-issue-moban-forked-3bj7l)

setting `van-field` 's `right-icon` as clear button to reset date value

```vue
<template>
  <div id="app">
    <van-field
      label="date"
      :value="formattedDate"
      clickrable
      :right-icon="date === null ? '' : 'clear'"
      @click-right-icon.stop="date = null"
      @click="show = true"
    ></van-field>
    <van-popup v-model="show" round position="bottom">
      <van-datetime-picker
        v-model="date"
        @confirm="show = false"
        @cancel="show = false"
      ></van-datetime-picker>
    </van-popup>
  </div>
</template>
```

steps to reproduce
- 1. click field to open datetime picker popup, and select a date value
- 2. close popup, click field right icon, the field value will set to `2010-01-01`
- 3. click field right icon again, than field value become empty successfully

here's screenshot

![example](https://user-images.githubusercontent.com/14357567/99615326-30d8ca00-2a56-11eb-8fb1-1c71ae4596e9.gif)

**Comment by chenjiahan** [comment]
In the current version, the default value of DatetimePicker is min-date, the result in the screenshot is as expected.

What is your expected behavior?

**Comment by hirohe** [comment]
binding `date` to DatetimePicker through `v-model`, by assign `date` to null, i think DatetimePicker shouldn't be min-date.

**Comment by hirohe** [comment]
this function on DatePicker, so i cannot clear DatetimePicker's value by assign `date` to null as you said, will change to min-date

```js
formatValue(value) {
  if (!isDate(value)) {
    value = this.minDate;
  }

  value = Math.max(value, this.minDate.getTime());
  value = Math.min(value, this.maxDate.getTime());

  return new Date(value);
},
```

**Comment by chenjiahan** [comment]
Reference: https://github.com/youzan/vant/issues/7592
