### ISSUE TITLE
[Bug Report] 关于 Fied 组件 readonly 下操作问题

### ISSUE THREAD

**Issue by leowang199303** [youzan/vant#7590]
### 设备 / 浏览器
所有移动设备

### Vant 版本
2.10.14

### Vue 版本
3.0.2

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-j95q3?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-j95q3?file=/src/App.vue</a>

### 描述问题
注意：请一定要使用移动设备打开链接重现，不要使用浏览器模拟真机环境
Field 组件设置成 readonly 模式，当内容超出容器高度时会成为滚动条，此时不能选中滚动等系列操作。
readonly 时，应该是只读模式，而不应该阻断用户的点击，滑动，选中等操作；disabled 设置才应该阻断这些模式。这两个设置还是有一些区别的，希望能恢复在 readonly 模式下对组件的控制

**Comment by chenjiahan** [comment]
readonly 是 HTML 原生属性，组件内部没有针对滑动、选中做特殊处理呢
