### ISSUE TITLE
[Bug Report] 修改主题样式变量不生效

### ISSUE THREAD

**Issue by yoonasy** [youzan/vant#7591]
### 设备 / 浏览器
all

### Vant 版本
3.0.0-beta.8

### Vue 版本
3.0.2

### 重现链接
<a href="http://baidu.com" target="_blank">http://baidu.com</a>

### 描述问题
在`vite.config.ts`中配置的全局，不生效，不会替换van默认的变量。相同的在less 选项中可以配置

```
cssPreprocessOptions: {
  less: {
      modifyVars: {
        'text-color': 'red', // 不生效
        'button-primary-background-color': 'red', // 不生效
        // hack: `true; @import "${join( // 相对路径和绝对路径也不生效
        //   __dirname,
        //   './src/assets/styles/themes/vant.theme.var.less'
        // )}";`,
      },
    }
...
```

**Comment by yoonasy** [comment]
已解决

**Comment by yoonasy** [comment]
配置不生效 以及寻求按需导入的问题

**Comment by chenjiahan** [comment]
主题配置在这个 issue 里已经解决了：https://github.com/vitejs/vite/issues/1107

按需导入的问题，目前 vite 没有按需引入插件，但 vite build 基于 rollup 实现，默认支持 tree shaking，所以 JS 部分已经通过 tree shaking 完成了按需引入，样式体积不大，全量引入不会有体积负担。

**Comment by yoonasy** [comment]
@chenjiahan  不好意思 如果我是想通过less变量去更改默认的主题的变量，这时候我应该是需要引入less文件的嘛 但是我直接引入
```
import 'vant/lib/index.less'
```

会报less错误，应该是路径错误导致的，所以我应该怎么办呢，麻烦看一下 谢谢🙏
```
[LessError] {
  message: undefined,
  stack: undefined,
  type: 'Syntax',
  filename: '/Users/cssr/cash2-wap/node_modules/vant/lib/icon/index.less',
  index: 24,
  line: 2,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [
    "@import '../style/var';",
    "@import '~@vant/icons/src/encode-woff2.less';",
    ''
  ]
} 0 [
  [LessError] {
    message: undefined,
    stack: undefined,
    type: 'Syntax',
    filename: '/Users/cssr/cash2-wap/node_modules/vant/lib/icon/index.less',
    index: 24,
    line: 2,
    column: 0,
    callLine: NaN,
    callExtract: undefined,
    extract: [
      "@import '../style/var';",
      "@import '~@vant/icons/src/encode-woff2.less';",
      ''
    ]
  }
]

```

**Comment by yoonasy** [comment]
@chenjiahan  不好意思 如果我是想通过less变量去更改默认的主题的变量，这时候我应该是需要引入less文件的嘛 但是我直接引入
```
import 'vant/lib/index.less'
```

会报less错误，看样子应该是图标路径错误导致的，所以我应该怎么办呢，麻烦看一下 谢谢🙏
```
[LessError] {
  message: undefined,
  stack: undefined,
  type: 'Syntax',
  filename: '/Users/cssr/xxx2-wap/node_modules/vant/lib/icon/index.less',
  index: 24,
  line: 2,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [
    "@import '../style/var';",
    "@import '~@vant/icons/src/encode-woff2.less';",
    ''
  ]
} 0 [
  [LessError] {
    message: undefined,
    stack: undefined,
    type: 'Syntax',
    filename: '/Users/cssr/xxx2-wap/node_modules/vant/lib/icon/index.less',
    index: 24,
    line: 2,
    column: 0,
    callLine: NaN,
    callExtract: undefined,
    extract: [
      "@import '../style/var';",
      "@import '~@vant/icons/src/encode-woff2.less';",
      ''
    ]
  }
]

```

**Comment by chenjiahan** [comment]
图标路径是没问题的呢，建议你自行搜索看下是什么问题

**Comment by Jarrett817** [comment]
> @chenjiahan 不好意思 如果我是想通过less变量去更改默认的主题的变量，这时候我应该是需要引入less文件的嘛 但是我直接引入
> 
> ```
> import 'vant/lib/index.less'
> ```
> 
> 会报less错误，看样子应该是图标路径错误导致的，所以我应该怎么办呢，麻烦看一下 谢谢🙏
> 
> ```
> [LessError] {
>   message: undefined,
>   stack: undefined,
>   type: 'Syntax',
>   filename: '/Users/cssr/xxx2-wap/node_modules/vant/lib/icon/index.less',
>   index: 24,
>   line: 2,
>   column: 0,
>   callLine: NaN,
>   callExtract: undefined,
>   extract: [
>     "@import '../style/var';",
>     "@import '~@vant/icons/src/encode-woff2.less';",
>     ''
>   ]
> } 0 [
>   [LessError] {
>     message: undefined,
>     stack: undefined,
>     type: 'Syntax',
>     filename: '/Users/cssr/xxx2-wap/node_modules/vant/lib/icon/index.less',
>     index: 24,
>     line: 2,
>     column: 0,
>     callLine: NaN,
>     callExtract: undefined,
>     extract: [
>       "@import '../style/var';",
>       "@import '~@vant/icons/src/encode-woff2.less';",
>       ''
>     ]
>   }
> ]
> ```
我也碰到了这个问题，请问解决了吗

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/7986

**Comment by LYao0919** [comment]
同求
