### ISSUE TITLE
[Feature Request] DatetimePicker 建议不用 min-date 设置当前时间

### ISSUE THREAD

**Issue by 1847211504** [youzan/vant#7592]
### 这个功能解决了什么问题
业务中某些日期选择，年份较久，例如 1900 年，切日期默认为空，用日期选择组件会发现 v-model 默认将 min-date 设置为 绑定值，这样会造成该字段有默认，实际情况可能客户并不想输入这一项，造成业务冲突，这样并不符合实际情况。

按我的业务来看的话，我更希望能灵活一些，我设置 min-date 为 1900 年，界面弹出选择在当前日期，但 v-model 为空，只有客户确定输入的时候，才给 v-model 的值，点击取消或关闭时不影响原来的值，以符合实际情况。

ps：我是结合弹窗使用 日期选择的。

### 描述您想要的解决方案
建议不将 min-date 设置为默认 v-model，或者有一个开关来标识是否需要默认设置，更灵活一些，符合实际使用，我看有不少小伙伴在实际当中会遇到这样的情况，希望官方予以考虑。

### 建议的API是什么样的
官方定。

**Comment by chenjiahan** [comment]
已在 2.12.7 版本优化
