### ISSUE TITLE
[Bug Report] 附件上传状态问题

### ISSUE THREAD

**Issue by made-02** [youzan/vant#7593]
### 设备 / 浏览器
谷歌/苹果

### Vant 版本
3.0.0-beta.8

### Vue 版本
3.0.0

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/next/#/zh-CN/uploadershang-chuan-zhuang-tai" target="_blank">https://vant-contrib.gitee.io/vant/next/#/zh-CN/uploadershang-chuan-zhuang-tai</a>

### 描述问题
目前使用附件上传功能设置图片状态,在上传前设置uploading,上传成功时设置状态为done,但是没有生效.目前官方beta.8版本也出现了此问题,2.0版本是好的。官方文档写出设置一秒后设置状态为failed，但是图片状态还是为uploading没有反应，希望vant官方可以做出调整

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/7462
