### ISSUE TITLE
vant文档地址打不开了

### ISSUE THREAD

**Issue by wuzhiquan** [youzan/vant#7597]
https://vant-contrib.gitee.io/vant/#/zh-CN/这个地址404打不开，请问有哪个地址能打开吗

**Comment by Sinosaurus** [comment]
+1

**Comment by yq121** [comment]
+1

**Comment by tsurumure** [comment]
同问

**Comment by Get-wy** [comment]
+1

**Comment by mark0325** [comment]
+1 打不开，估计周一才能修复吧

**Comment by chenjiahan** [comment]
gitee pages 挂了，已通过重新部署恢复

另外 Vant 目前有两套官网，可以互为备份：

- https://vant-contrib.gitee.io/vant/
- https://youzan.github.io/vant/
