### ISSUE TITLE
[Bug Report] vant-list一直触发加载

### ISSUE THREAD

**Issue by samxxxxx** [youzan/vant#7605]
### 设备 / 浏览器
Windows 10 / Chorme 87

### Vant 版本
2.10.10

### Vue 版本
2.6.12

### 重现链接
<a href="https://codepen.io/samxxxxx/pen/PozMbBq" target="_blank">https://codepen.io/samxxxxx/pen/PozMbBq</a>

### 描述问题
麻烦看一下是什么问题，我有设置了body的height:100%，没有多余的代码，是直接拿的https://vant-contrib.gitee.io/vant/#/zh-CN/list 链接里基本用法的代码

**Comment by xinconan** [comment]
不要在body上设置 `overflow-x: hidden`，文档中最后有写的，https://youzan.github.io/vant/#/zh-CN/list#zai-html-body-shang-she-zhi-overflow-hou-yi-zhi-chu-fa-jia-zai

**Comment by samxxxxx** [comment]
> 不要在body上设置 `overflow-x: hidden`，文档中最后有写的，https://youzan.github.io/vant/#/zh-CN/list#zai-html-body-shang-she-zhi-overflow-hou-yi-zhi-chu-fa-jia-zai

我刚才去掉了，还是一样的重复

**Comment by chenjiahan** [comment]
事件绑定写错了，不是 `v-bind:load="this.onLoad()"`，而是 `@load="onLoad"`，请仔细看文档

**Comment by samxxxxx** [comment]
因为我是在asp.net页面里写的，@符号在razor里冲突， 所以特意是这种写法

**Comment by samxxxxx** [comment]
> 事件绑定写错了，不是 `v-bind:load="this.onLoad()"`，而是 `@load="onLoad"`，请仔细看文档

因为我是在asp.net页面里写的，@符号在razor里冲突， 所以特意是这种写法

**Comment by chenjiahan** [comment]
那你也得写成 v-on: 啊，v-bind 是绑定属性的

**Comment by samxxxxx** [comment]
> 那你也得写成 v-on: 啊，v-bind 是绑定属性的

好的 可以了 非常感谢
