### ISSUE TITLE
[Bug Report] NavBar在设置 :border=false 的情况下 z-index 会失效

### ISSUE THREAD

**Issue by whzxc** [youzan/vant#7606]
### 设备 / 浏览器
chrome

### Vant 版本
2.11.0

### Vue 版本
2.6.12

### 重现链接
<a href="https://jsbin.com/doyokiq/edit?html,output" target="_blank">https://jsbin.com/doyokiq/edit?html,output</a>

### 描述问题
看了下应该是之前2.10.13版本更新的时候把nav bar自带的`position: relative`去掉了导致的，改动链接：https://github.com/youzan/vant/commit/be25a478dfbc599cdb27ba09d2d72858037c1700

不设置 `:border=false` 的时候会有 `van-hairline--bottom` 带的 `position: relative`，所以 `z-index` 有效

**Comment by chenjiahan** [comment]
感谢反馈，后续会加回来，也欢迎提 PR 喔
