### ISSUE TITLE
[Bug Report] van-list配合van-tabs使用，@load事件持续响应

### ISSUE THREAD

**Issue by luncang** [youzan/vant#7607]
### 设备 / 浏览器
chrome

### Vant 版本
2.10.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/luncang/vue-wanandroid-mobile" target="_blank">https://github.com/luncang/vue-wanandroid-mobile</a>

### 描述问题
1.van-tabs配合van-list使用，既多个tab下面嵌套van-list，每个van-list的@refresh事件响应是正常的，但是当多个tab完成初始化也就是多个van-list初始化完成后，多个van-list会同时触发@load事件，并且一直响应。
2. 测试，需要登陆，用户名：luncang，密码：123456。登录成功后，切换到项目，在项目页面，切换到动画tab，然后上拉加载更多就能看到这种现象，

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3430
