### ISSUE TITLE
[Bug Report] Checkbox-group toggleAll 会选中disabled checkbox

### ISSUE THREAD

**Issue by wrck** [youzan/vant#7608]
### 设备 / 浏览器
All

### Vant 版本
3.0.0-beta.10

### Vue 版本
3.0.2

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/next/#/zh-CN/checkbox" target="_blank">https://vant-contrib.gitee.io/vant/next/#/zh-CN/checkbox</a>

### 描述问题
Checkbox-group toggleAll方法会同样触发已经禁用的checkbox 选中状态

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/7511

**Comment by wrck** [comment]
> 参见 #7511
对于CheckBox toggle事件没有异议，但对于CheckGroup toggleAll事件，最初的设计初衷应该是简化重复勾选的操作步骤，既然单一勾选无法选中失效节点Checkbox，那么基于这个目的实现的批处理方法应该也是全选或反选生效节点的状态，而非所有节点。或者增加曝露filter方法

**Comment by chenjiahan** [comment]
后续会考虑加个参数来控制该行为

**Comment by chenjiahan** [comment]
已在 2.11.1 版本支持
