### ISSUE TITLE
[Bug Report] Tabbar无法定位到手机底部

### ISSUE THREAD

**Issue by cf1991** [youzan/vant#7609]
### 设备 / 浏览器
iPhone 7 plus

### Vant 版本
2.10.14

### Vue 版本
2.6.11

### 重现链接
<a href="https://gitee.com/wangding1044/solax-cloud/issues/I26L9K" target="_blank">https://gitee.com/wangding1044/solax-cloud/issues/I26L9K</a>

### 描述问题
tabbar无法定位到手机底部，而且在真机运行时，底部一直会出现留白现象

**Comment by chenjiahan** [comment]
组件开启了底部安全区适配，如果不需要，可以把 safe-area-inset-bottom 设置为 false
