### ISSUE TITLE
[Bug Report] circle当前进度超过100时，始终显示100

### ISSUE THREAD

**Issue by vivian217** [youzan/vant#7610]
### 设备 / 浏览器
Google

### Vant 版本
3.0.0-beta.10

### Vue 版本
3.0.2

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-ucp56?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-ucp56?file=/src/App.vue</a>

### 描述问题
circle的当前进度值超过100时，文字始终显示100

**Comment by chenjiahan** [comment]
rate 的含义是百分比，因此最大值就是 100。

如果想显示超过 100 的数值，可以在百分比和数值之间做转换。
