### ISSUE TITLE
[Bug Report] 下拉菜单的位置不对

### ISSUE THREAD

**Issue by bbboyvips** [youzan/vant#7613]
### 设备 / 浏览器
edge

### Vant 版本
2.11.0

### Vue 版本
2.6.12

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-nus0m" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-nus0m</a>

### 描述问题
van-tabs只要给这个组件加上animated这个属性,如果在这个组件内部使用DropdownMenu  下拉菜单组件会出现问题
 "vant": "^2.2.8", 出现的情况: 菜单项直接不展示 
"vant": "^2.11.0"出现的情况: 下拉的菜单项的位置离得很远  没有像官网实例那样紧紧贴在一起

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/4400

**Comment by bbboyvips** [comment]
> 参见 #4400

谢谢
