### ISSUE TITLE
[Bug Report] tabbar无法定位到手机底部

### ISSUE THREAD

**Issue by cf1991** [youzan/vant#7614]
### 设备 / 浏览器
iPhone 7 plus

### Vant 版本
2.10.14

### Vue 版本
2.6.11

### 重现链接
<a href="https://gitee.com/wangding1044/solax-cloud/issues/I26L9K" target="_blank">https://gitee.com/wangding1044/solax-cloud/issues/I26L9K</a>

### 描述问题
代码中去掉底部安全区，但是tabbar还是无法定位到手机底部

**Comment by chenjiahan** [comment]
我测试了一下是没问题的，建议你重新试一下，或者提供有效的 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
