### ISSUE TITLE
[Bug Report] 图标按钮与非图标按钮水平不对齐

### ISSUE THREAD

**Issue by cnazev** [youzan/vant#7617]
### 设备 / 浏览器
mbp macOS Catalina 10.15.7 edge(chrome)[86.0.622.63] 仿真手机界面(Moto G4) 
ip6s 14.0  微信[7.0.17]内置浏览器

### Vant 版本
2.11.0

### Vue 版本
2.6.12

### 重现链接
<a href="https://codepen.io/cnazev/pen/oNLKQPj" target="_blank">https://codepen.io/cnazev/pen/oNLKQPj</a>

### 描述问题
容器同时置放图标按钮与非图标按钮时，这些按钮上边缘未能对齐。

**Comment by chenjiahan** [comment]
可以先在 button 上添加 `vertical-align: middle;` 来避免这个问题

**Comment by chenjiahan** [comment]
已在 2.11.1 版本修复
