### ISSUE TITLE
[Feature Request] 新增的popover组件实现机制的探讨

### ISSUE THREAD

**Issue by yuningjiang123** [youzan/vant#7618]
### 这个功能解决了什么问题
我看文档介绍说  reference插槽用于触发Popover的显隐  但是我看源码就是单纯地把reference插槽渲染出来 并没有在内部封装触发Popover显隐的操作 包括Demo中也是在插槽中控制show变量的

### 描述您想要的解决方案
触发Popover的显隐应该是一个常见的操作 建议可以像ElementUI那样增加一个trigger让用户选择是reference自带触发显隐还是用户手动操作显隐

### 建议的API是什么样的
例如  新增trigger: 'click' | 'manual'  用户选择click时由组件内部实现点击toggle显隐  manual时由用户控制show进行显隐

**Comment by chenjiahan** [comment]
可以的，后续会加上

**Comment by chenjiahan** [comment]
已在 2.11.1 版本支持
