### ISSUE TITLE
[Feature Request] 建议日历组件增加快捷选择年月

### ISSUE THREAD

**Issue by spatack** [youzan/vant#7619]
### 这个功能解决了什么问题
解决某些业务需要向前或向后选择某年的日期，目前有些业务允许的日期选择范围是  向前3年，向后半年，这样的话 如果我们需要不停地滑动日历，非常不方便。

### 描述您想要的解决方案
增加 选择 年月 的快捷选择

### 建议的API是什么样的
vant 团队来定

**Comment by chenjiahan** [comment]
暂无计划支持喔，目前还没有相应的视觉规范
