### ISSUE TITLE
如何移动端适配

### ISSUE THREAD

**Issue by rookiewp** [youzan/vant#7620]
你好，vant中都是使用px，我的问题是：
1：那该如何进行移动端适配呢？是使用px2rem或者px2vw这样的插件吗？
2：可以定制全局样式吗？就是使用我自己设计一套主题样式

**Comment by yuningjiang123** [comment]
移动端适配：
https://youzan.github.io/vant/#/zh-CN/advanced-usage#liu-lan-qi-gua-pei

主题定制：
https://youzan.github.io/vant/#/zh-CN/theme

文档都写得很清楚的

**Comment by liuxsen** [comment]
> 移动端适配：
> https://youzan.github.io/vant/#/zh-CN/advanced-usage#liu-lan-qi-gua-pei
> 
> 主题定制：
> https://youzan.github.io/vant/#/zh-CN/theme
> 
> 文档都写得很清楚的

官方使用px开发，是为了更好的适配（通过插件转换为 rem，vw）？
