### ISSUE TITLE
[Bug Report] IndexBar定位不准确

### ISSUE THREAD

**Issue by wjzhang-ty** [youzan/vant#7622]
### 设备 / 浏览器
iphone7

### Vant 版本
2.10.14

### Vue 版本
2.6.0

### 重现链接
<a href="https://www.baidu.com/" target="_blank">https://www.baidu.com/</a>

### 描述问题
IndexBar的右侧导航，在屏幕比较小的的手机上无法准确定位。原因是部分小屏手机索引条目行高挤压变化所致。之前看到类似的问题，希望可以有些许帮助。

**Comment by chenjiahan** [comment]
具体是什么样子，能否提供截图看下？
