### ISSUE TITLE
[Bug Report] 在组件的导航守卫中加入Dialog.confirm，只能触发一次

### ISSUE THREAD

**Issue by yuka0723** [youzan/vant#7625]
### 设备 / 浏览器
所有

### Vant 版本
2.11.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/yuka0723/pen/VwjoNVy" target="_blank">https://codepen.io/yuka0723/pen/VwjoNVy</a>

### 描述问题
在组件内的beforeRouteLeave导航守卫，使用confirm提示用户即将离开，在confirm的成功回调中next()，取消回调中next(false)，但实际工程中表现为，没有等待confirm的回调，路由已经发生了变化（界面渲染内容并未更改）。并且如果不使用F5刷新，第二次进入该界面，回退时只会闪一下遮罩（进入了beforeRouteLeave），确认弹框不会渲染

**Comment by chenjiahan** [comment]
把 Dialog 的 closeOnPopstate 设置为 false，即可避免此问题

**Comment by 971389117** [comment]
> 把 Dialog 的 closeOnPopstate 选项设置为 false，即可避免此问题

我设置了closeOnPopstate ，但是还是只显示一次
![image](https://user-images.githubusercontent.com/29219980/100175135-ccf84a80-2f08-11eb-83fe-ad841ec533b0.png)

**Comment by chenjiahan** [comment]
要升级到最新版喔

![image](https://user-images.githubusercontent.com/7237365/100204171-80c7fd00-2f3e-11eb-9e49-cac4117ab282.png)
