### ISSUE TITLE
Vant-V2.10.0 - NoticeBar 通知栏 在IOS14版本scrollable失效

### ISSUE THREAD

**Issue by Yang9725** [youzan/vant#7628]
### 设备 / 浏览器
ios14

### Vant 版本
2.10.0-beta.0

### Vue 版本
2.6.10

### 重现链接
<a href="https://f4gv8.csb.app/" target="_blank">https://f4gv8.csb.app/</a>

### 描述问题
NoticeBar 通知栏在IOS14版本不能重复滚动

**Comment by chenjiahan** [comment]
已经修复了，可以升级到 Vant 2.11.0 版本试下
