### ISSUE TITLE
[Bug Report] APP首次启动tabbar无法固定在底部

### ISSUE THREAD

**Issue by cf1991** [youzan/vant#7629]
### 设备 / 浏览器
iPhone 7 plus

### Vant 版本
2.10.14

### Vue 版本
2.6.11

### 重现链接
<a href="https://www.iqiyi.com/v_208vnqwc3e0.html" target="_blank">https://www.iqiyi.com/v_208vnqwc3e0.html</a>

### 描述问题
上面的链接是我用手机录制的真机运行视频，当APP首次启动时，tabbar无法固定在手机底部，与底部会有25PX左右的距离，但是当我按下home键，让APP在后台运行几秒后，重新再次进入APP，发现此时的tabbar又可以准确的定位在手机底部，我的代码页面中没有使用特殊的样式布局，只是根据vant的官方文档引入了navbar和tabbar，navbar使用safe-area-inset-top开启了顶部安全区适配，tabbar无论有没有使用safe-area-inset-bottom开启底部安全区适配，都会出现上述问题。

**Comment by chenjiahan** [comment]
如果没有开启底部安全区适配，说明不是组件自身样式引起的底部边距，建议自行排查一下问题的原因

**Comment by supuwoerc** [comment]
> ### 设备 / 浏览器
> iPhone 7 plus
> 
> ### Vant 版本
> 2.10.14
> 
> ### Vue 版本
> 2.6.11
> 
> ### 重现链接
> https://www.iqiyi.com/v_208vnqwc3e0.html
> 
> ### 描述问题
> 上面的链接是我用手机录制的真机运行视频，当APP首次启动时，tabbar无法固定在手机底部，与底部会有25PX左右的距离，但是当我按下home键，让APP在后台运行几秒后，重新再次进入APP，发现此时的tabbar又可以准确的定位在手机底部，我的代码页面中没有使用特殊的样式布局，只是根据vant的官方文档引入了navbar和tabbar，navbar使用safe-area-inset-top开启了顶部安全区适配，tabbar无论有没有使用safe-area-inset-bottom开启底部安全区适配，都会出现上述问题。

请教下大佬后续的解决方法，我现在也遇到了=。=||
