### ISSUE TITLE
希望加个滚动组件，类似于iscroll

### ISSUE THREAD

**Issue by jifengdehao** [youzan/vant#763]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
暂无支持这方面的计划喔
