### ISSUE TITLE
SwipeCell 标识符类型异常问题

### ISSUE THREAD

**Issue by li308870559** [youzan/vant#7630]
类型不能为json数据吗？如何纠正
![image](https://user-images.githubusercontent.com/46514939/100201411-fa5dec00-2f3a-11eb-8b51-8ff49d403e86.png)
![image](https://user-images.githubusercontent.com/46514939/100201432-034ebd80-2f3b-11eb-95f6-6e99b6b345db.png)

**Comment by chenjiahan** [comment]
目前只接受 number 和 string 类型呢
