### ISSUE TITLE
SwipeCell 滑动单元格 beforeClose 参数触发无法判断指定按钮

### ISSUE THREAD

**Issue by li308870559** [youzan/vant#7631]
设备 / 浏览器
iphone6s

Vant 版本
2.6.3

Vue 版本
2.6.11

重现链接
本地开发，没有重现链接

描述问题
当使用 position | 关闭时的点击位置 (left right cell outside) 时，right存在两个以上按钮，分别对应不同业务。
如何进行区分不同按钮
![image](https://user-images.githubusercontent.com/46514939/100203857-1adb7580-2f3e-11eb-85ac-4fc379c58d1a.png)

**Comment by chenjiahan** [comment]
可以单独监听这两个按钮的 click 事件
