### ISSUE TITLE
[Bug Report] swipe设置width, 滚动的距离bug

### ISSUE THREAD

**Issue by duanhuajian** [youzan/vant#7633]
### 设备 / 浏览器
iphone

### Vant 版本
2.11.0

### Vue 版本
2.5.21

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/swipe" target="_blank">https://youzan.github.io/vant/#/zh-CN/swipe</a>

### 描述问题
swipe设置width, 滚动的距离bug：滑动到最后一页时，滚动的距离比实际设置的要小

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by duanhuajian** [comment]
code: 
https://codesandbox.io/s/vant-issue-moban-forked-7p2ve?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675

url: 
https://7p2ve.csb.app/

设置的width="300", 但滑动到最后一个item,  translateX 为-825px，应该为-900px;

**Comment by duanhuajian** [comment]
导致最后一个item，不能显示完全

**Comment by chenjiahan** [comment]
这个滑动距离是正确的，不能显示完全是因为你设置了 margin

**Comment by duanhuajian** [comment]
和设置margin有啥关系，请问为啥最后 translateX 为-825px，而不是-900px

**Comment by chenjiahan** [comment]
-900px，右边不就空了一大块?

**Comment by duanhuajian** [comment]
我这的需求就是第一个左边要有20px的空隙，滑块中间有10px的空隙。好像你们的组件搞不定呀 😢

**Comment by rookie-hhm** [comment]
> 我这的需求就是第一个左边要有20px的空隙，滑块中间有10px的空隙。好像你们的组件搞不定呀 😢

请问解决了吗？ 我也有这个需求
