### ISSUE TITLE
能否增加表单校验？

### ISSUE THREAD

**Issue by BigKongfuPanda** [youzan/vant#764]
目前移动端的 ui 库，基本都没有提供表单校验的功能，包括 mint-ui。但是表单校验的功能还是非常常用的，不知道你们这个 ui 库，能否提供这个功能呢

**Comment by cookfront** [comment]
目前移动端的表单都比较简单，所以并没有加入表单校验，我们后续会调研下，考虑是否加入这个功能。

**Comment by linwenfeng122** [comment]
我感觉这个并没有多需要，因为移动端毕竟发布的内容不会很多。直接用正则即可
