### ISSUE TITLE
The V2.11.0 version will report an error under nuxt

### ISSUE THREAD

**Issue by shanks-xc** [youzan/vant#7642]
(function (exports, require, module, __filename, __dirname) { import { popperGenerator, detectOverflow } from "./createPopper.js";
  ^^^^^^
  SyntaxError: Cannot use import statement outside a module

I know it's because import doesn't support it, but why does this version report this error?
V2.10.14 I tried, and there was no mistake

What should I do about it?

**Comment by chenjiahan** [comment]
Refer: https://github.com/youzan/vant/issues/7626
