### ISSUE TITLE
sku组件如何实现表单输入框，以及表单校验，当点击sku buy-clicked事件时获取填写表单的数据

### ISSUE THREAD

**Issue by li308870559** [youzan/vant#7643]
设备 / 浏览器
iphone6s

Vant 版本
2.6.3

Vue 版本
2.6.11

重现链接
本地开发，没有重现链接

描述问题
如何实现配置表单输入框及输入框校验及buy-clicked事件获取表单数据
![image](https://user-images.githubusercontent.com/46514939/100334812-395d7180-300f-11eb-95a4-58ded8d7a5e5.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
