### ISSUE TITLE
popover和navbar 右侧按钮 怎么联合使用？

### ISSUE THREAD

**Issue by javacode321** [youzan/vant#7648]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
可以使用插槽来插入 Popover 和按钮

**Comment by javacode321** [comment]
this.$router.back() 返回到 有Popover组件后，点击两下才会弹出PopOver
