### ISSUE TITLE
[Bug Report] Field组件文档错误

### ISSUE THREAD

**Issue by Mrchangchang** [youzan/vant#7649]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0-beta.10

### Vue 版本
3.0.3

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/next/#/zh-CN/field" target="_blank">https://vant-contrib.gitee.io/vant/next/#/zh-CN/field</a>

### 描述问题
https://img02.sogoucdn.com/app/a/100520146/d977f2ee897863d117feea063aa2b494
Fiele 文档， v-model(value)，vue3版本应为v-model(model-value)

**Comment by chenjiahan** [comment]
确实有问题，欢迎提 PR 喔

**Comment by Mrchangchang** [comment]
谢谢， Checkbox   DatetimePicker  NumberKeyboard  NumberKeyboard  Radio  Rate  Search  Slider  Stepper Switch  之类组件也能存在相似的问题。

**Comment by wuzaofeng** [comment]
input 事件第一个参数是event, 而不是value值

**Comment by chenjiahan** [comment]
上述问题已经在最新版文档中修正咯
