### ISSUE TITLE
[Feature Request] Tab 标签页建议新增title显示与隐藏支持

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#7651]
### 这个功能解决了什么问题
在某些特殊的业务需求下需要不显示title。但是目前官方没有提供方案。所以只能通过原生js去控制显示与隐藏。

### 描述您想要的解决方案
提供ref 方法控制title标题的显示与隐藏

### 建议的API是什么样的
显示: this.$refs.tabs.show();
隐藏: this.$refs.tabs.hide();

**Comment by chenjiahan** [comment]
暂无计划支持，直接通过 css 添加 `display: none` 就行

**Comment by syt-honey** [comment]
> 暂无计划支持，直接通过 css 添加 `display: none` 就行

**目的：** 根据某一条件 `v` 设置 title 是否显示

**问题：** 类型为 `sticky` 时，设置 `display: none` 后上下滑动页面，设置的样式会丢掉。

**步骤：**
1. 进入页面时根据条件 `v` 判断是否将 class 为 `van-sticky` 的元素设置为 `display: none`(代码如下)
2. 刷新 Web 页面，初始时状态正确
3. 下滑页面再上滑页面，title 再次显示

猜测：应该是上划的时候会把之前设置的 class 清空。

实现代码: 
```js
  const el = document.getElementsByClassName("van-sticky")[0];
  if (el) {
    el.classList.toggle("display-none", v === false);
  }
```

该方式会出现上面提到的问题：上滑时设置的样式会被清除。

**另外：**
本来尝试直接设置属性，但是在 `v` 为真的情况下，设置的 `display: block` 会导致下滑时 tabs bottom bar 不准（似乎相差的高度刚好为 title 的高度）。

实现代码:
```js
  const el = document.getElementsByClassName("van-sticky")[0];
  if (el) {
    el.style.display = `${v ? 'block' : 'none'}`
  }
```

**Comment by chenjiahan** [comment]
@syt-honey 通过 JS 设置是不对的，Vue 重新 render 的时候就覆盖掉了。

**Comment by syt-honey** [comment]
> @syt-honey 通过 JS 设置是不对的，Vue 重新 render 的时候就覆盖掉了。

你好，我还是不太理解。不通过 JS 直接用 CSS 设置，怎么做判断呢？

**Comment by Caveolaes** [comment]
> 暂无计划支持，直接通过 css 添加 `display: none` 就行

进入页面需要van-tabs__nav隐藏，当滚动条滑动到一定位置，van-tabs__nav显示，并吸顶。
出现的问题是：如果手动隐藏后，nav获取不到高度，导致滚动位置不准确

**Comment by inottn** [comment]
> > 暂无计划支持，直接通过 css 添加 `display: none` 就行
> 
> 进入页面需要van-tabs__nav隐藏，当滚动条滑动到一定位置，van-tabs__nav显示，并吸顶。 出现的问题是：如果手动隐藏后，nav获取不到高度，导致滚动位置不准确

可以设置 opacity 为 0 并设置 pointer-events 为 none

**Comment by Caveolaes** [comment]
> 
opacity:0虽然隐藏，但是空间位置还在

**Comment by yoyo837** [comment]
这个功能还是很常用的, 就是需要完全定制title, 无法通过title的slot轻易做到的那种. 希望支持
