### ISSUE TITLE
[Bug Report] DatetimePicker v-model属性卡死

### ISSUE THREAD

**Issue by webMagicX** [youzan/vant#7652]
### 设备 / 浏览器
chrome 浏览器 86.0.4240.198

### Vant 版本
2.11.1

### Vue 版本
2.5.2

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/datetime-picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/datetime-picker</a>

### 描述问题
根据官方的 DatetimePicker demo，v-model 属性一存在浏览器就卡死，您可本地自行测试

**Comment by chenjiahan** [comment]
建议先看下常见问题。

https://youzan.github.io/vant/#/zh-CN/datetime-picker#chang-jian-wen-ti

**Comment by webMagicX** [comment]
非常感谢！
