### ISSUE TITLE
[Feature Request] TreeSelect右侧选择项支持添加描述、支持下拉加载数据

### ISSUE THREAD

**Issue by yujieQian** [youzan/vant#7654]
### 这个功能解决了什么问题
（1）TreeSelect右侧选择项支持添加描述:解决需要添加描述信息的场景。例如显示商品领取地址时，希望一行显示店铺名称，一行显示对应的地址。
（2）TreeSelect右侧选择项支持下拉加载数据：解决分页请求的数据显示问题

### 描述您想要的解决方案
（1）TreeSelect右侧选择项支持添加描述:Item的children中添加helpDesc字段，用于展示描述信息。
（2）TreeSelect右侧选择项支持下拉加载数据：类似List。

### 建议的API是什么样的
（1）TreeSelect右侧选择项支持添加描述:Item的children中添加helpDesc字段；样式类似Cell中的描述信息。
（2）TreeSelect右侧选择项支持下拉加载数据：类似List。

**Comment by chenjiahan** [comment]
暂无计划支持呢，可以通过插槽来实现上述功能。

**Comment by yujieQian** [comment]
好的，感谢回复～




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月29日(星期天) 上午9:34
收件人:&nbsp;"youzan/vant"<vant@noreply.github.com&gt;;
抄送:&nbsp;"钱玉洁"<1030176770@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant] [Feature Request] TreeSelect右侧选择项支持添加描述、支持下拉加载数据 (#7654)





 
暂无计划支持呢，可以通过插槽来实现上述功能。
