### ISSUE TITLE
[Feature Request] 怎么用vite按需加载样式

### ISSUE THREAD

**Issue by luocong2016** [youzan/vant#7656]
### 这个功能解决了什么问题
Q&A 文档描述

### 描述您想要的解决方案
文档描述

### 建议的API是什么样的
文档描述

**Comment by chenjiahan** [comment]
Vite 不支持 babel，所以不能使用 babel-plugin-import 来自动按需引入，如果需要按需引入样式，只能通过手动引入的方式来实现：

```js
import 'vant/lib/button/style';
import 'vant/lib/cell/style';
```

**Comment by psaren** [comment]
@luocong2016 可以试下 [vite-plugin-imp](https://www.npmjs.com/package/vite-plugin-imp)
