### ISSUE TITLE
[Feature Request] 关于【@vant/cli】组件库内部自带图片的引用？

### ISSUE THREAD

**Issue by miterwan** [youzan/vant#7657]
### 这个功能解决了什么问题
我将这个脚手架clone下来生成适配公司ui的组件库。我添加了url-loader对图片进行处理。但生成组件库的时候发现组件内部的图片引入相对路径报错。

### 描述您想要的解决方案
因为公司内部组件有一些默认图片的站位。图片大的不好转成base64。故想这个脚手架可以支持组件内部图片的引入

### 建议的API是什么样的
在开发组件的时候。引入当前组件下images下的图片不会报错

**Comment by miterwan** [comment]
![屏幕快照 2020-11-30 下午4 37 14](https://user-images.githubusercontent.com/29746948/100586825-b13add00-332a-11eb-946c-40962f102992.png)
![屏幕快照 2020-11-30 下午4 38 27](https://user-images.githubusercontent.com/29746948/100586841-b9931800-332a-11eb-9f49-c842f494d8fe.png)
这是图片loader配置后打包失败的情况

**Comment by chenjiahan** [comment]
只能在 js 里 import 图片喔，在 css 里引入是不支持的

**Comment by kekexunxun** [comment]
@chenjiahan `请问一下如果在组件中引入额外的图片资源？使用url-loader之后，dev是正常的，但是到了打包就会报异常
```js
ERROR in ./es/searchbar/index.js
Module not found: Error: Can't resolve './imgs/icon_search.png' in '/Users/xxx/Documents/components/es/searchbar'
```

然后我发现
![image](https://user-images.githubusercontent.com/44473551/118099754-41b43800-b408-11eb-9150-16acf5e3f110.png)
这个会把额外的资源文件直接移除

**Comment by kekexunxun** [comment]
@chenjiahan 请问怎么样可以支持组件中引入额外的图片资源？

**Comment by kekexunxun** [comment]
@miterwan 老哥有解决方案吗？是不是需要自己改compile

**Comment by miterwan** [comment]
@kekexunxun 是的。我自己简单添加了对资源类的编译处理
![屏幕快照 2021-05-13 下午4 42 34](https://user-images.githubusercontent.com/29746948/118101530-4a0d7280-b40a-11eb-890c-8a4d89e132a6.png)
![屏幕快照 2021-05-13 下午4 42 55](https://user-images.githubusercontent.com/29746948/118101543-4d086300-b40a-11eb-9a76-702ac8f0b6cc.png)

**Comment by kekexunxun** [comment]
@miterwan 那在js中怎么引用，用相对路径好像不太行啊；那是直接在src中用require还是先在js import再在src中使用？

**Comment by miterwan** [comment]
@kekexunxun 正常使用吧。我基本用的是背景图。背景图用的相对路径是ok的。你可以自己尝试下

**Comment by kekexunxun** [comment]
@miterwan 好嘞！谢谢老哥

**Comment by ZhaoyangRao** [comment]
vant-cli是怎么看到配置文件的 不是只要vant.config.js么
