### ISSUE TITLE
[Bug Report] 按需加载引入 less 文件有问题

### ISSUE THREAD

**Issue by luichooy** [youzan/vant#7658]
### 设备 / 浏览器
chorme

### Vant 版本
2.11.1

### Vue 版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/quickstart" target="_blank">https://youzan.github.io/vant/#/zh-CN/quickstart</a>

### 描述问题
按照官方文档中的如下配置进行按需加载：
```
{
  "plugins": [
    ["import", {
      "libraryName": "vant",
      "libraryDirectory": "es",
      "style": true
    }]
  ]
}
```
style设置为 true 时，按照 `babel-plugin-import`的说法，加载的应该是 less文件，实际测试中发现加载的是css 文件

**原因如下：** 

style 设置为 true 时，`babel-plugin-import` 插件加载路径为： `vant/es/button/style`，对应实际加载的文件为`vant/es/button/style/index.js`,此文件内部导入的都是 css 文件，所以无法做到按需加载 less 文件

要使 `babel-plugin-import` 插件正常工作，实际打包生成的组件 style 目录中应该包括 css.js(导入 css) 和 index.js(加载 less)

可能需要修改@vant/cli的下图逻辑 
![image](https://user-images.githubusercontent.com/26423033/100582939-f9570100-3324-11eb-96b1-61971d6ed22b.png)

**Comment by luichooy** [comment]
![image](https://user-images.githubusercontent.com/26423033/100587810-01ff0580-332c-11eb-959a-8c85d7367231.png)

[babel-plugin-import](https://github.com/ant-design/babel-plugin-import)的官方文档说明

**Comment by chenjiahan** [comment]
Vant 默认引入的是 css 格式，而不是 less 格式。如果默认引入 less 文件，每个用户都需要配置 less-loader，不太友好。

定制主题的方式在文档里已经很清楚了，可以参考文档：https://youzan.github.io/vant/#/zh-CN/theme

**Comment by luichooy** [comment]
> Vant 默认引入的是 css 格式，而不是 less 格式。如果默认引入 less 文件，每个用户都需要配置 less-loader，不太友好。
> 
> 定制主题的方式在文档里已经很清楚了，可以参考文档：https://youzan.github.io/vant/#/zh-CN/theme

个人觉得 按需加载如果是要引入 css 格式，应该手动设置 style: 'css' ，否则设置 style: true 跟 babel-plugin-import 的默认行为不一致很容易让人迷惑。如果希望用户默认 使用 css 格式，应该从文档上加以引导或说明

**Comment by chenjiahan** [comment]
babel-plugin-import 的默认值并不合理，它是为了 antd 设计的。

默认引入 css 是一个理所当然的事情，不需要额外说明。
