### ISSUE TITLE
Calendar 设置 default-date 为null后，显示面版，默认值不是当前月 

### ISSUE THREAD

**Issue by greenmonking** [youzan/vant#7659]
**vant版本**
2.10.5

复现链接
https://jsbin.com/tanefojesa/4/edit?html,console,output

**Comment by greenmonking** [comment]
打开面板默认显示当前月的日历

**Comment by chenjiahan** [comment]
已经修复了，可以升级最新版试下

**Comment by chenqiuling** [comment]
> 已经修复了，可以升级最新版试下
版本：2.12.2
calendar 选择日期区间，default-date 传入 null，默认打开还是最小日期，而不是当前月
`<van-calendar
    v-model="showDatePicker"
    type="range"
    :min-date="new Date(2010, 0, 1)"
    :max-date="new Date(2020, 0, 1)"
    :default-date="null"
/>`

**Comment by chenjiahan** [comment]
> 一次滚动一整个月，每次只显示一个月呢

现在就是按需渲染的。

> calendar 选择日期区间，default-date 传入 null，默认打开还是最小日期，而不是当前月

可以调用 scrollToDate 方法

**Comment by chenqiuling** [comment]
> 现在就是按需渲染的。
请问是需要升级到3.x版本吗？我在2.12.2版本设置的最小和最大日期是前后50年，然后组件一渲染就创建了1200个dom（<div class="van-calendar__month"></div>）

> 可以调用 scrollToDate 方法
感谢，已解决。

**Comment by chenjiahan** [comment]
每个月份会创建一个占位 div，所以 50 年确实会出现卡顿的情况，不推荐使用这么长的跨度呢，对用户也不太友好
