### ISSUE TITLE
vant tab的badge 在动态设置值后会自动加上单位‘个’

### ISSUE THREAD

**Issue by myGit-Account** [youzan/vant#7662]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater
![1606730570](https://user-images.githubusercontent.com/53161048/100595789-58714180-3336-11eb-9940-e56719b23da6.png)
![1606730570(1)](https://user-images.githubusercontent.com/53161048/100595795-5a3b0500-3336-11eb-9e84-8c01b8dfbb47.png)
在页面执行完成后有60%左右的概率出现单位
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
