### ISSUE TITLE
[Bug Report] popup组件锁定背景滚动会overflow：hidden后在顶部锁定

### ISSUE THREAD

**Issue by OctoberToEscape** [youzan/vant#7665]
### 设备 / 浏览器
ios14.0系统以上的机器

### Vant 版本
3.0.0-beta.10

### Vue 版本
3.0.2

### 重现链接
appstore 搜索知鸦 下载后进入到知识圈板块 点击投票进入详情页然后点击列表的介绍然后会弹出popup

### 描述问题
popup组件从弹出锁定背景滚动会overflow：hidden后在顶部锁定,而不是在当前位置锁定------举个例子：首次登陆，我现在滚动到1000px的位置有个元素点击弹出层后，锁定背景滚动会回到顶部而不是在当前位置锁定。然后我退出登录后再次登陆进入到知识圈板块相同的位置这个时候overflow:hidden失效了，不再锁定滚动

**Comment by OctoberToEscape** [comment]
> ### 设备 / 浏览器
> ios14.0以上版本的机器
> 
> ### Vant 版本
> 3.0.0-beta.10
> 
> ### Vue 版本
> 3.0.2
> 
> ### 重现链接
> http://home.huobite.club/voteDetails?id=n2YDKayeKX3j&types_vote=%E4%B8%93%E9%A2%98&title=%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E4%B8%93%E9%A2%98%E6%8A%95%E7%A5%A8&top_titles=%E7%AC%AC9%E5%AD%A3%E7%AC%AC8%E6%9C%9F
> 
> ### 描述问题
> popup组件从底部弹出锁定背景滚动会overflow：hidden后在顶部锁定,而不是在当前位置锁定------举个例子：我现在滚动到1000px的位置有个元素点击弹出层后，锁定背景滚动会回到顶部而不是在当前位置锁定。（点击链接后，点击投票列表选项的介绍会从底部弹出，但是会锁定回顶部这个bug，只有在真机才能重现，）

**Comment by chenjiahan** [comment]
麻烦提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
