### ISSUE TITLE
webpack 打包 npm i vant   <van-popup> - did you register the component correctly

### ISSUE THREAD

**Issue by sweat1992** [youzan/vant#7666]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.
![image](https://user-images.githubusercontent.com/75289114/100692281-75a12100-33c5-11eb-8642-38df4654fdc5.png)
![image](https://user-images.githubusercontent.com/75289114/100692298-805bb600-33c5-11eb-9662-b4c04eb7fe67.png)

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
