### ISSUE TITLE
Toast.clear(); 后背景蒙层依然存在

### ISSUE THREAD

**Issue by ccp2435** [youzan/vant#767]
Toast.loading({
        forbidClick: true, // 禁用背景点击
        message: '加载中...'
      });
      setTimeout(()=>{
          Toast.clear();
      },5000)
背景蒙层依然存在

**Comment by chenjiahan** [comment]
已在 1.0.3 版本中修复

**Comment by yumeiqiang** [comment]
vant 1.5.1，Toast.clear()也偶尔会出现无法关闭蒙层

**Comment by qiuyoo** [comment]
1.5.2 也存在

**Comment by zjhcn** [comment]
2.0.0偶现
