### ISSUE TITLE
cdn  script 标签好像没更新，还是2.10

### ISSUE THREAD

**Issue by HuangWeiBin2** [youzan/vant#7672]
cdn  script 标签好像没更新，还是2.10

**Comment by chenjiahan** [comment]
👌已更新

**Comment by HuangWeiBin2** [comment]
> 👌已更新

更新了吗？好像还不能用那个popover组件。

**Comment by chenjiahan** [comment]
要替换下链接

https://cdn.jsdelivr.net/npm/vant@2.11/lib/index.css
https://cdn.jsdelivr.net/npm/vant@2.11/lib/vant.min.js
