### ISSUE TITLE
[Bug Report] van-field绑定:rules[]下的validator不能自定义传值

### ISSUE THREAD

**Issue by MarkKasl** [youzan/vant#7673]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0-rc.1

### Vue 版本
3.0.3

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
```html
<van-field
                  v-else
                  v-model="work.selfRating"
                  name="自评分"
                  type="number"
                  label="自评分"
                  :rules="[{ required: true, message: `评分范围【${work.scoreStart}】至【${work.scoreEnd}】`  },
                  {validator: validatorTargetScore(work),message: `评分范围【${work.scoreStart}】至【${work.scoreEnd}】` }]"
                />
```
----
validatorTargetScore(work)这个方法不管return true or false 都不生效， 除非改成{validator: validatorTargetScore,message: `评分范围【${work.scoreStart}】至【${work.scoreEnd}】` }这样的才能生效。但是这样没法动态校验

**Comment by chenjiahan** [comment]
validatorTargetScore 可以返回一个 validate 函数，这样是可以的
