### ISSUE TITLE
你们是不是得罪百度了，百度搜出来的都是啥呀

### ISSUE THREAD

**Issue by Nicolas-shanpao** [youzan/vant#7674]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
![image](https://user-images.githubusercontent.com/28480091/100824046-61762600-3490-11eb-9934-98488707c4d9.png)

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/100826630-c08a6980-3495-11eb-8061-87371355176c.png)

百度辣鸡，推荐用 Google

**Comment by chenjiahan** [comment]
已经在处理搜索结果的优化了，过一阵子会好些
