### ISSUE TITLE
从vant 2.10.10升级到vant 3.0.0-rc.1后，打包体积变大30%

### ISSUE THREAD

**Issue by 1000010000** [youzan/vant#7675]
同样的配置，同样的页面，升级后打包体积变大

**Comment by chenjiahan** [comment]
具体引入了哪些组件，配置按需引入了么？

我们在 3.0 做了体积优化的，比 2.0 的包大小降低了 13%，可以对比下面的链接看下

https://cdn.jsdelivr.net/npm/vant@2/lib/vant.min.js
https://cdn.jsdelivr.net/npm/vant@next/lib/vant.min.js

**Comment by 1000010000** [comment]
谢谢你能回复我
是按需引入的

Vant 3


Vant 2


好像是个别组件体积变大了，但是整体体积也变大了

**Comment by chenjiahan** [comment]
具体用了哪些组件喔，可以用 https://www.npmjs.com/package/webpack-bundle-analyzer 分析一下体积

**Comment by chenjiahan** [comment]
3.0.0-rc.2 版本优化了一波体积，可以升级试下

**Comment by 1000010000** [comment]
升级到3.0.0-rc.2，整体体积从836.38kb => 767.92kb，但是还是大于原来的715.69kb，
通过webpack-bundle-analyzer分析，其中一个页面体积增加较多，从26.66kb => 41.42kb，这个页面使用了 Stepper, Icon, Skeleton, Toast这几个组件，增大的部分来自于field，form，cell模块，我并未引用form，cell模块，core-js模块也有所增大

**Comment by chenjiahan** [comment]
这个问题下个 rc 版本会处理掉
