### ISSUE TITLE
当在Popup组件中嵌套Stepper组件时，禁用输入的情况下，点击输入框页面会下滑一下

### ISSUE THREAD

**Issue by 1000010000** [youzan/vant#7677]
版本:vant 2.11.1
环境:iOS 上的Safari和微信浏览器
问题描述:当在Popup组件中嵌套Stepper组件时，Stepper的disable-input=true，点击输入框会导致页面下滑一下，然后又恢复，疑似触发了虚拟键盘。将readonly改为disabled，就不会出现这个问题

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
