### ISSUE TITLE
this.$router.back() 返回到 有Popover组件的页面后，点击两下才按钮会弹出Popover

### ISSUE THREAD

**Issue by javacode321** [youzan/vant#7679]
<van-nav-bar title="违建" left-arrow @click-left="$router.back()">
          <template #right>
            <van-popover
              v-model="showPopover"
              trigger="click"
              :actions="actions"
              @select="onSelect"
              placement="bottom-end"
              @close="$router.currentRoute.meta.overlay.close('task/operator')"
              @open="$router.currentRoute.meta.overlay.open('task/operator',()=>{showPopover = false})"
            >
              <template #reference>
         ```
       <span>选项</span>
              </template>
            </van-popover>
          </template>
        </van-nav-bar>
```
前提条件  从上一个页面$router.back()返回到上面的页面，点击两下“选项”才能弹出popover,  使用了keep-alived

**Comment by javacode321** [comment]
是keepalive缓存了popup的状态为true,  点击this.$router.push(), 这时popup消失，但是状态还是true, 在返回的上一界面,点击"选项"，现在popup 状态为true, 所有不弹出pop, 但修改了popup的状态为false,再点击 “选项" 正常弹出pop了。
keepalive 导致 popover状态不统一 的bug。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by talkbear** [comment]
所以问题还是没解决吗

**Comment by fuiyu** [comment]
同问，我这也有类似的问题

**Comment by javacode321** [comment]
事件的问题  显示状态的问题  显隐要同步控制发自我的华为手机-------- 原始邮件 --------发件人： fuiyu ***@***.***>日期： 2021年4月23日周五 10:34收件人： youzan/vant ***@***.***>抄送： javacode321 ***@***.***>, Author ***@***.***>主    题： Re: [youzan/vant] this.$router.back() 返回到 有Popover组件的页面后，点击两下才按钮会弹出Popover (#7679)

同问，我这也有类似的问题

**Comment by fuiyu** [comment]
> 事件的问题 显示状态的问题 显隐要同步控制发自我的华为手机-------- 原始邮件 --------发件人： fuiyu ***@***.***>日期： 2021年4月23日周五 10:34收件人： youzan/vant ***@***.***>抄送： javacode321 ***@***.***>, Author ***@***.***>主 题： Re: [youzan/vant] this.$router.back() 返回到 有Popover组件的页面后，点击两下才按钮会弹出Popover (#7679) 同问，我这也有类似的问题 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

如何同步控制？
