### ISSUE TITLE
sku组件，在ios上面输入购买数量软键盘抬起的时候，有横向滚动条，希望给个解决思路

### ISSUE THREAD

**Issue by wangminglmm** [youzan/vant#768]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by w91** [comment]
@wangminglmm 能否提供下相关截图和示例代码

**Comment by wangminglmm** [comment]
刚用官网上面再手机上面看了下，发现是没有问题的，可能是我布局有问题，我先检查检查，还有文档上面的demo用的vant版本是哪个呢？
