### ISSUE TITLE
uploader组件在afterRead回调修改上传状态不生效

### ISSUE THREAD

**Issue by caozhong1996** [youzan/vant#7680]
uploader组件在afterRead回调修改上传状态不生效，一直为uploading，在官网3.0版本可以复现
https://vant-contrib.gitee.io/vant/next/#/zh-CN/uploader
![image](https://user-images.githubusercontent.com/26522151/100874612-cefd7300-34df-11eb-9797-e47608bd4037.png)

**Comment by chenjiahan** [comment]
重复 issue，先 close 咯

https://github.com/youzan/vant/issues/7462
