### ISSUE TITLE
[Feature Request] area-list文件里的所属地区怎么还有芬兰

### ISSUE THREAD

**Issue by hetianyu0315** [youzan/vant#7682]
### 这个功能解决了什么问题
这个js显示国内省市区县数据，但为什么会有国外的地区，而且很多，包括俄罗斯，芬兰等

### 描述您想要的解决方案
去掉国外的部分

### 建议的API是什么样的
与现在格式一致即可，只是去掉国外的地区

**Comment by chenjiahan** [comment]
自己删掉就行
