### ISSUE TITLE
[Feature Request] uploader上传图片能否对每张图片设置单独的样式或配置

### ISSUE THREAD

**Issue by ZH4L** [youzan/vant#7683]
比如类似的需求：
列表中某张图片不能删除，其他的可以删除，如果设置了`deletable=false`，那都不能删除了，可能只能通过自定义`preview-cover`的形式去实现删除，就显得很繁琐

**Comment by chenjiahan** [comment]
已在 2.12.0-beta.0 版本支持

**Comment by ZH4L** [comment]
> 已在 2.12.0-beta.0 版本支持

👏👏👏
