### ISSUE TITLE
[Feature Request] DemoBlock.vue可以单独作为一个组件吗？

### ISSUE THREAD

**Issue by LEOLEMON** [youzan/vant#7689]
### 这个功能解决了什么问题
在你们的官方演示上用了DemoBlock.vue来展示每个组件的工作，简单又美观，但是在你们的官网文档没有这个样式，找了好久找到。

### 描述您想要的解决方案
将DemoBlock.vue单独作为一个组件发布。

### 建议的API是什么样的
将DemoBlock.vue单独作为一个组件发布。

**Comment by chenjiahan** [comment]
抱歉，暂时没有这个计划喔，这只是一个示例组件，代码逻辑比较简单

源代码地址：https://github.com/youzan/vant/blob/dev/packages/vant-cli/site/mobile/components/DemoBlock.vue

**Comment by chenjiahan** [comment]
后续会和设计同学沟通下，看是否要抽成官方组件
