### ISSUE TITLE
[Bug Report] 当在Popup组件中嵌套Stepper组件时，禁用输入的情况下，点击输入框页面会下滑一下

### ISSUE THREAD

**Issue by 1000010000** [youzan/vant#7690]
### 设备 / 浏览器
iPhone /微信浏览器、Safari

### Vant 版本
2.11.1

### Vue 版本
2.6.5

### 重现链接
<a href="http://webapptest.lvyouquan.com/skb/details.html?productId=86ff97c82d23446aa74380d6c26b34ea&distributionId=158661405a174886a36f1b5c56b1afcc" target="_blank">http://webapptest.lvyouquan.com/skb/details.html?productId=86ff97c82d23446aa74380d6c26b34ea&distributionId=158661405a174886a36f1b5c56b1afcc</a>

### 描述问题
点击在线预订，点击Stepper组件的输入框，当在Popup组件中嵌套Stepper组件时，Stepper的disable-input=true，点击输入框会导致页面下滑一下，然后又恢复，疑似触发了虚拟键盘。将readonly改为disabled，就不会出现这个问题

**Comment by chenjiahan** [comment]
后续会兼容下

**Comment by chenjiahan** [comment]
已在 2.11.2 版本修复
