### ISSUE TITLE
[Feature Request] IndexBar实现默认展现定位到自定义的一个索引模块

### ISSUE THREAD

**Issue by liang-jingjing** [youzan/vant#7695]
### 这个功能解决了什么问题
初始化加载时候可以根据给定的值进行默认定位

### 描述您想要的解决方案
比如indexList为A-Z,，但默认加载进来的时候能否直接定位到 van-index-anchor index="C" 这个模块呢，目前在文档中没有发现这种定位属性，只有点击或滑动才能触发定位

### 建议的API是什么样的
IndexBar Props
to
<van-index-bar :index-list="indexList" :to="D">

</van-index-bar>

**Comment by chenjiahan** [comment]
后续可以加一个 scrollTo 方法

**Comment by chenjiahan** [comment]
已在 2.12.2 版本支持，scrollTo 方法
