### ISSUE TITLE
[Bug Report] uploader在multiple模式下，after-read如何拿到每张图片的index？

### ISSUE THREAD

**Issue by ZH4L** [youzan/vant#7696]
### 设备 / 浏览器
Chrome 87

### Vant 版本
2.11.1

### Vue 版本
2.6.12

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-n6k54?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-n6k54?file=/src/App.vue</a>

### 描述问题
在`multiple`模式下选多张图片，after-read调用时file是一个数组，但detail里面的index和name都只有一个值，如果我想在某张图片上传失败的时候直接删除掉，那根本不知道是哪个index的图片失败了？

**Comment by chenjiahan** [comment]
file 数组里对应的 index + 传参带过来的 index
