### ISSUE TITLE
[Bug Report] 使用createVNode的方式创建Dialog，slot部分提示undefined

### ISSUE THREAD

**Issue by ZhengXiaowei** [youzan/vant#7700]
### 设备 / 浏览器
Mac OS - Chrome

### Vant 版本
3.0.0-rc.2

### Vue 版本
3.0.4

### 重现链接
<a href="https://codesandbox.io/s/vue3-vant-dialog-report-1669h" target="_blank">https://codesandbox.io/s/vue3-vant-dialog-report-1669h</a>

### 描述问题
使用`createVNode`的方式创建`Dialog`组件 会出现`slot`不显示的情况

**Comment by chenjiahan** [comment]
这个和 Dialog 没什么关系，Dialog 内部就是按常规写法读取的 slot。

建议你自行排查下是不是使用姿势有问题。

**Comment by ZhengXiaowei** [comment]
```
const container = document.createElement("div");
document.body.append(container);

const vm = createVNode(  
  Dialog,
   { show: true, title: "测试" },
  {
     default: () => "默认插槽内容"
   }
 );

  render(vm, container);
```
就这样的

**Comment by chenjiahan** [comment]
可以使用 createApp 来挂载的
