### ISSUE TITLE
[Bug Report] 栅格布局不对齐

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#7704]
### 设备 / 浏览器
chrome87

### Vant 版本
3.0.0-rc.2

### Vue 版本
3.0.4

### 重现链接
https://codesandbox.io/s/vant-issue-moban-forked-wfouk?file=/src/main.js

Vant 2.x
栅格异常
![image](https://user-images.githubusercontent.com/38392315/101427935-c58a6580-393a-11eb-9c2c-674c8087b815.png)

Vant 3.x
栅格不对齐
![image](https://user-images.githubusercontent.com/38392315/101428086-05514d00-393b-11eb-9316-fb8c9b872732.png)

### 描述问题
栅格布局不对齐

**Comment by 0xbul1** [comment]
对不齐是应该的呀，
第一行一个占12份，中间20的空隙
第二行6+6+12，中间40的空隙，
如果对齐了，它的宽度岂不是变化了？

**Comment by chenjiahan** [comment]
楼上正解
