### ISSUE TITLE
[Bug Report] filed输入表情发生截取，造成提交数据异常

### ISSUE THREAD

**Issue by Reset0921** [youzan/vant#7706]
### 设备 / 浏览器
iphone x

### Vant 版本
3.0.0-rc.2

### Vue 版本
3.0.4

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater" target="_blank">https://youzan.github.io/vant-issue-generater</a>

### 描述问题
field组件在使用maxlength后输入表情会出现超过或接近最大长度时，发生表情截取，导致数据提交异常。

**Comment by chenjiahan** [comment]
具体输入的内容是？

**Comment by Reset0921** [comment]
比如说maxlength限制是20，当我输入中文输入到19个字，然后输入一个表情，此时字数统计展示为20个字，刚才输入的表情没有展示出来。

**Comment by Reset0921** [comment]
原生input表情占位好像多数都是占一位的长度，而field占位长度大多都是2
