### ISSUE TITLE
[Bug Report] tab开启sticky布局时，tab栏会消失

### ISSUE THREAD

**Issue by hongcareer** [youzan/vant#7707]
### 设备 / 浏览器
chrome

### Vant 版本
1.6.9

### Vue 版本
2.5.2

### 重现链接
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### 描述问题
tab开启sticky布局时，初始化的时候tab栏会消失,鼠标滚动时才会显示

**Comment by chenjiahan** [comment]
重新链接无效，且 vant 1.x 已经不再维护了，请升级到 vant 2.x
