### ISSUE TITLE
[Feature Request] Popup交互性优化，同2.x版本的vant

### ISSUE THREAD

**Issue by lehui521** [youzan/vant#7709]
目前3.x版本vant的Popup组件在打开的时候会有一个动画效果，例如：从下到上的一个滑动动画
但是关闭的时候动画就没有了，突然就关闭了就很突兀。
这个问题是出现在^3.0.0-rc.2版本，2.x版本没有此问题。

**Comment by chenjiahan** [comment]
这个是 Vue 3.0.4 版本 transition 组件的 bug，可以先把 Vue 版本降级到 3.0.3，动画就正常了

**Comment by chenjiahan** [comment]
相关 issue：https://github.com/vuejs/vue-next/issues/2757

**Comment by lehui521** [comment]
好的，谢谢
