### ISSUE TITLE
[Bug Report] Vant 3版本Popup关闭时未显示过渡动画

### ISSUE THREAD

**Issue by xLong1029** [youzan/vant#7714]
![无过渡动画](https://user-images.githubusercontent.com/18066675/101613370-a37e0980-3a46-11eb-8479-c82c50c64938.gif)
### 设备 / 浏览器
不限设备和浏览器

### Vant 版本
3.0.0-rc.2

### Vue 版本
3.0.4

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-hxtxb" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-hxtxb</a>

### 描述问题
在Vant 3版本下Popup显示时有显示上滑的动画效果，但是关闭时未显示下滑的动画效果，而是直接关闭了，在Vant 2版本下2者都有动画效果，因为项目需求原因需要用Vant 3开发

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/7709

**Comment by xLong1029** [comment]
> 参见 #7709

好的，谢谢
