### ISSUE TITLE
PC版微信小程序NumberKeyboard 数字键盘不能点击也不能关闭

### ISSUE THREAD

**Issue by LKF123LKF** [youzan/vant#7715]
<van-number-keyboard
                    v-model="value"
                    :show="show3"
                    @blur="show3 = false"
                    z-index="9999"
            />

**Comment by chenjiahan** [comment]
参见 https://youzan.github.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei

**Comment by LKF123LKF** [comment]
![image](https://user-images.githubusercontent.com/31716525/101615886-a29aa700-3a49-11eb-8385-48b65476ec54.png)
![image](https://user-images.githubusercontent.com/31716525/101615934-b34b1d00-3a49-11eb-96fe-2fe0077ba268.png)
是配置过了也不行

**Comment by chenjiahan** [comment]
麻烦提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by LKF123LKF** [comment]
没有很复杂的代码，可能关键在于那个z-index：9999，就是PC版微信小程序数字键盘弹出来了不能点击，点击外面也不会关闭






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2020年12月9日(星期三) 晚上6:13
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "晓风残月"<2451207443@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] PC版微信小程序NumberKeyboard 数字键盘不能点击也不能关闭 (#7715)





 
麻烦提供 codesandbox 复现链接
 
https://codesandbox.io/s/m5v3f
