### ISSUE TITLE
[Bug Report] tabs组件手动修改active值始终变为0

### ISSUE THREAD

**Issue by carrywu** [youzan/vant#7717]
### 设备 / 浏览器
 chrome 87.0.4280.88

### Vant 版本
3.0.0-rc.2

### Vue 版本
3.0.1

### 重现链接
<a href="https://codesandbox.io/s/amazing-tree-p1nw7?file=/src/components/test.vue" target="_blank">https://codesandbox.io/s/amazing-tree-p1nw7?file=/src/components/test.vue</a>

### 描述问题
在重现链接的中，通过click事件去修改active=3,active先改变3最后改变成0了，click修改active值始终会变为0

**Comment by chenjiahan** [comment]
确实有问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 3.0.0-rc.3 版本修复
