### ISSUE TITLE
[Bug Report] Vant项目预览路由问题

### ISSUE THREAD

**Issue by AdamCaoQAQ** [youzan/vant#7719]
### 设备 / 浏览器
PC / Chrome

### Vant 版本
3.0.0-rc.2

### Vue 版本
3.0.4

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/packages/vant-cli/site/desktop/router.js" target="_blank">https://github.com/youzan/vant/blob/dev/packages/vant-cli/site/desktop/router.js</a>

### 描述问题
我注意到最近vant cli已经将vue版本升级到3.0了，在vant项目预览的时候，我发现文档无法根据卡片标题进行定位，路由跳转后的scrollBehavior是失效的。经过确认发现在packages/vant-cli/site/desktop/router.js代码仍然使用了 return { selector: to.hash };这种用法，但是vue-router-next中这里的入参key已经变为el 了，同时配套使用的vant-markdown-loader中在push路由的逻辑中已经将hash的逻辑移除了，不知道这里能不能统一改一下，通过hash及scrollBehavior api 将这里的逻辑重新完善一下

**Comment by AdamCaoQAQ** [comment]
```
// vant/node_modules/@vant/markdown-loader/src/index.js


scrollToAnchor(event) {
  if (event.target.id) {
    this.$router.push({
      name: this.$route.name,
      hash: '#'+ event.target.id
    })
  }
}

//  vant/packages/vant-cli/site/desktop/router.js
export const router = createRouter({
  history: createWebHashHistory(),
  routes: getRoutes(),
  scrollBehavior(to) {
    if (to.hash) {
      return {el: to.hash };
    }

    return { x: 0, y: 0 };
  },
});
```

我目前在这两个文件进行上述修改可以完善整个展示效果↑↑↑

**Comment by chenjiahan** [comment]
可以的，试了下上述修改是没问题的，能否提个 PR~

**Comment by AdamCaoQAQ** [comment]
我已经提交了PR  
https://github.com/youzan/vant/pull/7745
但我理解还需要你们再发布@vant/markdown-loader 和 @vant/cli 这两个包才算修复这个问题

**Comment by chenjiahan** [comment]
已发布 @vant/cli 3.1.5 版本
