### ISSUE TITLE
[Bug Report] Mismatching childNodes vs. VNodes

### ISSUE THREAD

**Issue by liseipi** [youzan/vant#7721]
### 设备 / 浏览器
chrome

### Vant 版本
2.11.2

### Vue 版本
2.6.1

### 重现链接
<a href="http://192.168.0.87:8089/" target="_blank">http://192.168.0.87:8089/</a>

### 描述问题
在nuxt下使用SSR后，只要使用vant-image组件后就报如下错，改用img元素后就没有问题。
 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

**Comment by chenjiahan** [comment]
已在 2.12.1 版本修复
