### ISSUE TITLE
vant2.11 van-form 提交没有反应

### ISSUE THREAD

**Issue by sngdtian** [youzan/vant#7726]
使用CDN引入方式，复制官方的例子创建 van-form，点击提交没有任何反应，控制台能捕捉到 onSubmit事件，但却不提交表单。把van-form换成普通的form表单运行正常。这是怎么回事？
<van-form @submit="onSubmit">
  <van-field
    v-model="username"
    name="用户名"
    label="用户名"
    placeholder="用户名"
    :rules="[{ required: true, message: '请填写用户名' }]"
  />
  <van-field
    v-model="password"
    type="password"
    name="密码"
    label="密码"
    placeholder="密码"
    :rules="[{ required: true, message: '请填写密码' }]"
  />
  <div style="margin: 16px;">
    <van-button round block type="info" native-type="submit">
      提交
    </van-button>
  </div>
</van-form>

**Comment by chenjiahan** [comment]
VanForm 只会触发 submit 事件，不会提交表单

**Comment by sngdtian** [comment]
> VanForm 只会触发 submit 事件，不会提交表单

那要如何才能提交表单？

**Comment by chenjiahan** [comment]
通过 ajax 提交数据即可

**Comment by sngdtian** [comment]
> 通过 ajax 提交数据即可
谢谢

**Comment by sngdtian** [comment]
> 通过 ajax 提交数据即可
ajax提交的表单没办法像正常表单提交一样跳转。vanForm有办法可以像正常表单一样提交吗？

**Comment by chenjiahan** [comment]
不支持喔
