### ISSUE TITLE
请问indexbar怎么实现局部滚动？要改源码吗？

### ISSUE THREAD

**Issue by oyjq** [youzan/vant#7734]
请问indexbar怎么实现局部滚动？要改源码吗？

**Comment by chenjiahan** [comment]
不需要喔，可以直接嵌套在局部滚动的容器内使用。

**Comment by oyjq** [comment]
我想用IndexBar实现这样的功能，当match[0].top为x（不为零）时候，当前索引active为true。当click索引时候，对应match[0].top为x（不为零）我改了源码虽然实现了，但是如果局部滚动也可以实现，我更想用局部滚动。
