### ISSUE TITLE
[Bug Report] iOS中Popup内容层会有滚动穿透

### ISSUE THREAD

**Issue by llllllllllx** [youzan/vant#7738]
### 设备 / 浏览器
iOS/Safari12.1.2

### Vant 版本
3.0.0-rc.3

### Vue 版本
3.0.4

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/next/mobile.html#/zh-CN/popup" target="_blank">https://vant-contrib.gitee.io/vant/next/mobile.html#/zh-CN/popup</a>

### 描述问题
在iOS中，打开popup组件后遮罩层滑动不会触发滚动穿透，在内容层滑动会触发滚动穿透

**Comment by wuzaofeng** [comment]
安卓也是内容层滑动穿透

**Comment by chenjiahan** [comment]
已在 3.0.1 版本修复

**Comment by lee8519** [comment]
相同的问题,ios内部内容滑动会出现穿透,vant的版本怎么解决啊2.12.7,不想升级3.x,因为要和vue一起升级比较麻烦
