### ISSUE TITLE
[Feature Request] 请问怎么录音、拍视频并播放、保存和上传 

### ISSUE THREAD

**Issue by NickLoveSunny** [youzan/vant#7742]
### 这个功能解决了什么问题
Android和IOS录音、拍视频并播放、保存和上传

### 描述您想要的解决方案
录音、停止、播放、下载、上传
视频拍摄、停止、播放、下载、上传

### 建议的API是什么样的
Uploader

**Comment by chenjiahan** [comment]
这个问题和组件无关，请自行解决喔
