### ISSUE TITLE
[Feature Request] Radio 增加圈和点展示形式

### ISSUE THREAD

**Issue by wjw-gavin** [youzan/vant#7743]

**Comment by chenjiahan** [comment]
这个是 Vant 的设计规范喔，圆形样式也是很常见的

**Comment by DivLovesSpan** [comment]
专为这个问题而来，公司UI给的设计稿是根据vant官方给的设计资料设计的，radio有圆形和一个圈加一个点形，我翻遍了文档发现没有一个圈加一个点的，我问UI为啥有这样的形状，他给我看了设计资料，里面确实有一个圈加一个点形的，迷惑。。。

**Comment by chenjiahan** [comment]
我现在感觉这个需求有必要支持一下

@wjw-gavin 没想到是你提的😂

**Comment by wjw-gavin** [comment]
> 我现在感觉这个需求有必要支持一下
> 
> @wjw-gavin 没想到是你提的😂

我去，挖坟级 issues 啊😂，周末我看看可以搞下

**Comment by wjw-gavin** [comment]
我来求助了...，这里 checkbox 和 radio 的 props 使用的是同一个 shape 类型，怎么能区分组件创建呢 。如果像现在加上 dot，checkbox 也支持了圆点形状，但是它又不适合 checkbox 😭，怎么办... @chenjiahan 

<img width="587" alt="image" src="https://github.com/youzan/vant/assets/19986739/293c008e-7438-40ad-96f0-286e7fef9884">

**Comment by inottn** [comment]
> 我来求助了...，这里 checkbox 和 radio 的 props 使用的是同一个 CheckerShape 类型，怎么能区分组件创建呢 。如果像现在加上 dot，checkbox 也支持了圆点形状，但是它又不适合 checkbox 😭，怎么办... @chenjiahan

如果不需要支持 checkbox 的话，可以参照 [TimePicker](https://github.com/youzan/vant/blob/main/packages/vant/src/time-picker/TimePicker.tsx#L56) 的 filter，把 radio 的 shape 拆出来。

**Comment by wjw-gavin** [comment]
> > 我来求助了...，这里 checkbox 和 radio 的 props 使用的是同一个 CheckerShape 类型，怎么能区分组件创建呢 。如果像现在加上 dot，checkbox 也支持了圆点形状，但是它又不适合 checkbox 😭，怎么办... @chenjiahan
> 
> 如果不需要支持 checkbox 的话，可以参照 [TimePicker](https://github.com/youzan/vant/blob/main/packages/vant/src/time-picker/TimePicker.tsx#L56) 的 filter，把 radio 的 shape 拆出来。

好的好的，我参考下哈，多谢~

**Comment by chenjiahan** [comment]
嗯嗯，拆分下类型好了
