### ISSUE TITLE
[Feature Request] NavBar 右边添加多个自定义按钮

### ISSUE THREAD

**Issue by 971389117** [youzan/vant#7744]
### 这个功能解决了什么问题
默认按钮和自定义按钮共存的问题

### 描述您想要的解决方案
假如右边有一个默认按钮，每个页面都有，还有一些页面有自己独特的按钮，通过目前的 right 插槽好像无法实现

### 建议的API是什么样的
比如right1 ,  right2

PS：想到了一个兼容的写法，在NavBar组件的right插槽中使用v-html动态绑定父组件传过来的内容

**Comment by 971389117** [comment]
兼容的写法有个问题，vant可能把right插槽认为是一个按钮，所以点击编辑任意一个按钮，所有按钮的动画效果（变亮）都会触发
![Uploading image.png…]()

**Comment by 0xbul1** [comment]
这种和业务紧密结合的特殊情形vant应该是不会增加api的

如果非要用vant的navbar,可以在vant，right插槽中添加自己的具名插槽。我试了一下是可以实现的。

关于你说的`right插槽认为是一个按钮，所有按钮的动画效果（变亮）都会触发`,这个应该是vant的active添加的```opacity:0.7```样式，去除即可

**Comment by 971389117** [comment]
> 这种和业务紧密结合的特殊情形vant应该是不会增加api的
> 
> 如果非要用vant的navbar,可以在vant，right插槽中添加自己的具名插槽。我试了一下是可以实现的。
> 
> 关于你说的`right插槽认为是一个按钮，所有按钮的动画效果（变亮）都会触发`,这个应该是vant的active添加的`opacity:0.7`样式，去除即可

的确是可以通过在right插槽中添加具名插槽，这样就相当于爷爷给孙子写插槽，可以实现功能点。

Thank you
