### ISSUE TITLE
【BUG】2.11.1版本中Dialog、divider等组件引部分组件引入报错

### ISSUE THREAD

**Issue by 13247711709** [youzan/vant#7747]
【BUG】2.11.1版本中Dialog、divider等组件引部分组件引入报错

望尽快修复

Vant 版本：2.11.1
Vue 版本 ：2.6.10

错误
![image](https://user-images.githubusercontent.com/26455028/102204191-82189400-3f04-11eb-9f56-3ca870cd3380.png)

报错代码
![image](https://user-images.githubusercontent.com/26455028/102204311-ad02e800-3f04-11eb-8232-efdc1e579e00.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
