### ISSUE TITLE
【BUG】2.11.1版本中Dialog、divider等组件引部分组件引入报错

### ISSUE THREAD

**Issue by 13247711709** [youzan/vant#7748]
**这是一个私有项目且未上线，无法提供链接，所以无法在http://vant-contrib.gitee.io/vant-issue-generater/#/zh-CN 这个地址上提issue**

【BUG】2.11.1版本中Dialog、divider等组件引部分组件引入报错

望尽快修复

Vant 版本：2.11.1
Vue 版本 ：2.6.10

错误
image

报错代码
image

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
