### ISSUE TITLE
picker动态设置选项时，怎么设置disabled

### ISSUE THREAD

**Issue by WuZheXiao** [youzan/vant#7749]
picker动态设置选项时，怎么设置disabled
![微信截图_20201216091829](https://user-images.githubusercontent.com/26809951/102292239-bd0bdd80-3f7f-11eb-9641-b0411b179d46.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，或者到[讨论区](https://github.com/youzan/vant/discussions)进行提问，感谢配合
