### ISSUE TITLE
collapse的一些问题，vant版本是0.12.3

### ISSUE THREAD

**Issue by BibBin** [youzan/vant#775]
custom element: <van-collapse> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Unknown custom element: <van-collapse-item> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

 main.js里面是全局注册的vant
import Vant from 'vant'
import 'vant/lib/vant-css/index.css'
Vue.use(Vant)

然后我去查了node_modules里面没有这个组件，我去....说明情况

**Comment by BibBin** [comment]
<van-dialog v-model="show"></van-dialog>
用这个组件也是报这个错误...但是这个组件我看是有的

**Comment by chenjiahan** [comment]
请升级到 1.0.3 版本再试

**Comment by BibBin** [comment]
@chenjiahan 升级之后就好了，是什么原因呢

**Comment by chenjiahan** [comment]
@BibBin Collapse 是 1.0 版本新增的组件喔
