### ISSUE TITLE
定制主题

### ISSUE THREAD

**Issue by king-ying** [youzan/vant#7752]
### 设备 / 浏览器
移动端

### Vant 版本
2.11.2

### Vue 版本
3.0.4

### 重现链接
<a href="http://localhost:8081/mobile.html#/button" target="_blank">http://localhost:8081/mobile.html#/button</a>

### 描述问题
使用vant-cli构建工程，并定制主题，调试出现两份样式代码，一份是css 一份是less
![image](https://user-images.githubusercontent.com/18572260/102325558-3e826080-3fbe-11eb-83ac-8a6d9ba80558.png)
我不使用@vant/cli/presets，也是同样的效果
presets: [
    '@vue/cli-plugin-babel/preset',
    ],
  plugins: [
    [
      'import',
      {
        libraryName: 'vant',
        libraryDirectory: 'es',
        // 指定样式路径
        style: (name) => `${name}/style/less`,
      },
      'vant',
    ],

**Comment by chenjiahan** [comment]
如果使用了定制主题，所有引入样式的地方都需要引入 less 格式的样式。如果有任意地方引入了 css 格式，就会出现重复。
