### ISSUE TITLE
[Bug Report] Tabs change事件，滑动到首个Tab不会触发方法

### ISSUE THREAD

**Issue by jcllonglong** [youzan/vant#7754]
### 设备 / 浏览器
Chrome

### Vant 版本
2.11.1

### Vue 版本
2.6.11

### 重现链接
<a href="http://47.95.223.112/" target="_blank">http://47.95.223.112/</a>

### 描述问题
滑动切换中部车型图，每次滑回至第一个Tab时，控制台未打印索引及名称

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by jcllonglong** [comment]
> 请提供 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

沙箱链接：https://codesandbox.io/s/vant-issue-moban-forked-nonyr?file=/src/App.vue

**Comment by chenjiahan** [comment]
使用 Tabs 组件时，需用使用 v-model:active 绑定当前 active 的标签索引喔，不然组件内部无法知道当前的 Tab 是哪一个，就无法正确触发 change 事件了

**Comment by johnseed** [comment]
> 
> 
> 使用 Tabs 组件时，需用使用 v-model:active 绑定当前 active 的标签索引喔，不然组件内部无法知道当前的 Tab 是哪一个，就无法正确触发 change 事件了

文档里写的还是v-model，实际是 v-model:active

**Comment by Knightluozichu** [comment]
正解是不用number，用string
