### ISSUE TITLE
[Bug Report] Lazyload在use的时候报错install类型不兼容

### ISSUE THREAD

**Issue by JustGogoing** [youzan/vant#7757]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0-rc.3

### Vue 版本
3.0.4

### 重现链接
<a href="https://codepen.io/china_hero/pen/xEYooQ" target="_blank">https://codepen.io/china_hero/pen/xEYooQ</a>

### 描述问题
在项目中使用LazyLoad组件时 ts报错 `
类型“Lazyload”的参数不能赋给类型“Plugin_2”的参数。
  不能将类型“Lazyload”分配给类型“{ install: PluginInstallFunction; }”。
    属性“install”的类型不兼容。
`

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 3.0.0-rc.4 版本修复
