### ISSUE TITLE
tabs 启用animated属性后 list 滚动 load 事件只触发最后一个tabs下的list

### ISSUE THREAD

**Issue by mazhenxiao** [youzan/vant#7761]
vue版本：3.0 + ts
vant版本：3.0.0-beta.7
问题描述：
tabs 开启animated 滑屏动画后，list 滚动触发load事件，this指向为最后一个tabs下list。
解决方法：
给 tabs 下的 list 添加 v-show 来屏蔽非当前活动（active）标签name。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
