### ISSUE TITLE
[Feature Request] Picker 级联 Column数据结构的children字段支持自定义

### ISSUE THREAD

**Issue by code-farmer-i** [youzan/vant#7762]
### 这个功能解决了什么问题
减少使用者的递归数据处理

### 描述您想要的解决方案
Picker 级联 Column数据结构的children字段支持自定义

### 建议的API是什么样的
新增一个例如 column-children-key 属性

现在我有一个省市区的级联场景，数据源返回的数据结构中子节点的字段并不是children，那么我需要递归来处理数据结构使其能让Picker级联组件工作。

**Comment by chenjiahan** [comment]
已在 3.0.2 版本支持，2.x 就不支持咯
