### ISSUE TITLE
[Bug Report] ImagePreview 预览失败

### ISSUE THREAD

**Issue by w-z-z** [youzan/vant#7766]
### 设备 / 浏览器
pc&移动端

### Vant 版本
2.11.2

### Vue 版本
2.6.12

### 重现链接
<a href="https://github.com/w-z-z/vant_issue" target="_blank">https://github.com/w-z-z/vant_issue</a>

### 描述问题
点击预览出现错误：
 Error in nextTick: "TypeError: Cannot read property 'key' of undefined"

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/102677075-96e27980-41db-11eb-8017-750281cc0e1a.png)

这里漏了 @Component，加上就好了

**Comment by w-z-z** [comment]
> ![图片](https://user-images.githubusercontent.com/7237365/102677075-96e27980-41db-11eb-8017-750281cc0e1a.png)
> 
> 这里漏了@component，加上就好了

嗯没问题了，谢谢。
