### ISSUE TITLE
Popover clickoutside does not works version 3.0.0-rc.3

### ISSUE THREAD

**Issue by megafetis** [youzan/vant#7767]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

I tried to use manual `import { useClickAway } from '@vant/use';` and trigger manually. It doesnt works.

I tried `import { onClickOutside} from '@vueuse/core'` and it works.

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
Can you provide a codesandbox link to reproduce this issue?

https://codesandbox.io/s/m5v3f

**Comment by megafetis** [comment]
Please look codesandbox link: 

https://codesandbox.io/s/vant-issue-popover-clickoutside-8qzud

**Comment by chenjiahan** [comment]
Popover listens to touch event, and it won't trigger in desktop browsers, you can use [@vant/touch-emulator](https://youzan.github.io/vant/#/en-US/advanced-usage#adapt-to-pc-browsers) to adapt to PC Browsers.

**Comment by megafetis** [comment]
Thank you very much!
