### ISSUE TITLE
[Feature Request] form validate 怎么校验多个字段？

### ISSUE THREAD

**Issue by sanheng** [youzan/vant#7769]
### 这个功能解决了什么问题
看文档 validate 只支持传入一个 name，是否支持传入多个 name

比如点击获取验证码只需要校验“身份证”和“手机号”
点击提交需要校验“姓名”、“身份证”和“手机号”

### 描述您想要的解决方案
validate 支持传入多个 name

### 建议的API是什么样的
validate(name: string[]): boolean

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 2.12.1 版本支持
