### ISSUE TITLE
[Bug Report] AddressEdit组件中点击保存后如何清空内容

### ISSUE THREAD

**Issue by OrdinaryPath** [youzan/vant#7770]
### 设备 / 浏览器
chrome

### Vant 版本
2.11.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/address-edit" target="_blank">https://youzan.github.io/vant/#/zh-CN/address-edit</a>

### 描述问题
在输入框中输入内容后，点击保存之后如何把输入框中的内容清除?

**Comment by chenjiahan** [comment]
可以把 address-info 属性设置为空对象
