### ISSUE TITLE
[Bug Report] keepalive页面使用Tabs标签

### ISSUE THREAD

**Issue by RionZZZ** [youzan/vant#7772]
### 设备 / 浏览器
Chrome

### Vant 版本
3.0.0-rc.3

### Vue 版本
3.0.0

### 描述问题
HOME主页使用keepalive，添加Tabs标签使用animated、swipeable后，选中非第一个tab后跳转到下一页面再返回到HOME页时，active的标签title显示正常，但是tab内容始终显示第一个tab内容。不使用animated、swipeable就没有问题，页面:active数据正常，应该是css没更新的问题。

![image](https://user-images.githubusercontent.com/18389241/102686530-4727a080-4223-11eb-89b0-f3b6e3b6859a.png)

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接 

https://codesandbox.io/s/m5v3f

**Comment by RionZZZ** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

https://i69f3.csb.app/  麻烦看一下，我现在后退back时用局部组件强制刷新暂时解决这个问题。

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 3.0.1 版本修复
