### ISSUE TITLE
[Feature Request] Stepper 增加控制「是否显示输入框」的选项

### ISSUE THREAD

**Issue by craigary** [youzan/vant#7773]
### 这个功能解决了什么问题
目前 Stepper 只能控制是否显示「加号」和「减号」，但我的需求是只有当 Stepper 的值大于 0 时，才显示减号和输入框，因为没有对应的 API，只能通过样式覆盖来解决。

### 描述您想要的解决方案
增加一个控制是否在 Stepper 中显示输入框的 API。

### 建议的API是什么样的
| Props | Desc | Type | Default |
| :----: | :----: | :----: | :------: |
| show-input | 是否显示输入按钮 | boolean | true |

另，Vant 是在我完成个人项目的时候最能够满足需求的组件，非常感谢 <3

**Comment by chenjiahan** [comment]
好的👌 后续加个属性控制

**Comment by chenjiahan** [comment]
已在 2.12.1 版本支持
