### ISSUE TITLE
图片上传底部有margin，显示不正常

### ISSUE THREAD

**Issue by TuiMao233** [youzan/vant#7774]
版本号：3.0.0-rc.3
使用设备：谷歌浏览器手机调试模式
问题：上传组件图片蒙版超出

![image](https://user-images.githubusercontent.com/49724027/102703685-ffe5f200-42ac-11eb-9cda-476a049434d7.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
