### ISSUE TITLE
为什么tab栏切换 滚动条会置顶是什么情况

### ISSUE THREAD

**Issue by 1047820921** [youzan/vant#7775]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://www.weibanglove.com/mobile/dayTaoker/index.html#/taobao/dayTaoBao

麻烦解答一下

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
