### ISSUE TITLE
省市区选择组件，点击确认后我咋能拿到选中的城市啊？谁知道赛？

### ISSUE THREAD

**Issue by mywebc** [youzan/vant#778]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
通过 confirm 事件回调参数，详见文档
