### ISSUE TITLE
[Bug Report] Stepper的change事件在离开焦点后再次触发

### ISSUE THREAD

**Issue by OrdinaryPath** [youzan/vant#7780]
### 设备 / 浏览器
chrome

### Vant 版本
2.11.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/stepper#events" target="_blank">https://youzan.github.io/vant/#/zh-CN/stepper#events</a>

### 描述问题
在输入框输入值后会触发一次change事件，但是焦点离开输入框以后还会再次触发一次，这是官方设计的时候就这样的吗？

**Comment by ZhengXiaowei** [comment]
`blur`的时候会对`input.value`进行格式校验，并将校验后的值重新赋值回去，这个过程会重新触发一次`change`

**Comment by OrdinaryPath** [comment]
> `blur`的时候`input.value`进行进行格式校验，替换校正后的值重新赋值回去，这个过程会重新触发一次`change`

那如何去掉这次事件，或者在blur事件的时候如何取到回调的值呢？

**Comment by ZhengXiaowei** [comment]
`stepper`是支持`v-model`的吧，你可以直接在`blur`事件里直接去绑定的那个值就行了。如果手动输入`input value`的需求不大的话，可以`disable-input`先禁用input输入，这样可以避免`blur`这个事件。
如果都想要，那得看下作者对这块有什么优化建议了。

**Comment by chenjiahan** [comment]
下个版本会优化下

**Comment by chenjiahan** [comment]
已在 2.12.1 版本修复
