### ISSUE TITLE
希望van-calendar组件可以提供组件里的scrollIntoView方法，可以自动滚动到指定月份

### ISSUE THREAD

**Issue by OTT179** [youzan/vant#7781]
你好，van-calendar组件不设置默认值（default-date）时，当前视图显示为开始可选月份，且无法调整。
希望可以提供组件里的scrollIntoView方法，可以 配置视图月份 或者 初始化时 滚动到指定月份。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
