### ISSUE TITLE
[Bug Report] Vant Cli 编译 Less 不支持 javascriptEnabled 选项

### ISSUE THREAD

**Issue by king-ying** [youzan/vant#7784]
### 设备 / 浏览器
PC

### Vant 版本
2.11.3

### Vue 版本
3.0.4

### 重现链接
<a href="http://localhost:8080/" target="_blank">http://localhost:8080/</a>

### 描述问题
场景：使用vant-cli 2.6.2 构建组件库。
因为引入了使用函数式编码的less文件
![image](https://user-images.githubusercontent.com/18572260/102756257-8b917880-43aa-11eb-8936-d75a73ad4ebf.png)
本地运行报错，提示
![image](https://user-images.githubusercontent.com/18572260/102756278-951ae080-43aa-11eb-9c86-5efc2ea50060.png)
于是添加less配置
![image](https://user-images.githubusercontent.com/18572260/102756152-613fbb00-43aa-11eb-8184-3aea853198dc.png)
本地运行回复正常，但是在执行 npm run build 时依然提示以上错误

**Comment by chenjiahan** [comment]
Vant Cli 编译样式时是不通过 Webpack 的，所以这个选项不会生效。

后续看下怎么支持

**Comment by king-ying** [comment]
好的，感谢跟进，因为我现在是封装组件库，用到了定制主题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 晚上8:25
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "王英"<1195976374@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] [Bug Report] Vant Cli 编译 Less 不支持 javascriptEnabled 选项 (#7784)





 
Vant Cli 编译样式时是不通过 Webpack 的，所以这个选项不会生效。
 
后续看下怎么支持

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/103146620-3c22c200-4787-11eb-9392-51208eccc92e.png)

这个选项已经被废弃了，所以不没有计划在 Vant Cli 中添加，抱歉。
