### ISSUE TITLE
[Bug Report] vant-list 监听的scroll事件 和 vue-router的push后维持scroll冲突

### ISSUE THREAD

**Issue by wall-git** [youzan/vant#7786]
### 设备 / 浏览器
chrome

### Vant 版本
2.11.3

### Vue 版本
3.0.4

### 重现链接
<a href="https://github.com/vuejs/vue-router/issues/3424" target="_blank">https://github.com/vuejs/vue-router/issues/3424</a>

### 描述问题
已经到router那边问过，跳转后有个维持滚动的特性，所以在第一个界面有滚动条时，第二个界面进入后会先调用下scroll 事件，此时lvan-list则会自动加载一遍，导致设置:immediate-check="false"无效，需要根据是否是初始路由判断是否执行第一次scroll事件响应，所以到你们这了，你们怎么看？

**Comment by chenjiahan** [comment]
关于路由的判断需要使用者自己来做，组件内部不会实现这部分逻辑。

**Comment by wall-git** [comment]
> 关于路由的判断需要使用者自己来做，组件内部不会实现这部分逻辑。

我是说你们能不能判断是系统调用的还是touch move ? ，如果我们自己做需要判断是否是第一个界面，然后再判断第一个界面是否滚动了，然后再加载数据，咦真优雅！！！！

**Comment by chenjiahan** [comment]
> 能不能判断是系统调用的还是touch move

不行呢，List 不是基于 touch 事件实现的。

**Comment by wall-git** [comment]
> > 能不能判断是系统调用的还是touch move
> 
> 不行呢，List 不是基于 touch 事件实现的。

清楚，你们监听的scroll,多加个判断呢能行不？还不行，我们只能二次封装了。。。

**Comment by chenjiahan** [comment]
不行唉，二次封装把~

**Comment by justyeh** [comment]
造成原因是进入之前的页面滑动过，进入`van-list`页后会自动触发一次`scroll`事件

我目前也遇到这样的问题，会造成两个坑：

一，首页到列表页，会导致`:immediate-check="false"`无效，如果在load事件里面处理了页码，会导致页码不正确
```html
<van-list
    v-model:loading="listLoading"
    :finished="listFinish"
    :finished-text="listFinishedText"
    :immediate-check="false"
    @load="onListLoad"
  >

...

// 自动加载更多
function onListLoad() {
  state.pageIndex++
  getListData()
}
```

二，详情页回列表页，同样的自动load，会导致缓存逻辑失效
```js
onMounted(async () => {
  await Promise.all([initDict(['lead_process_status']), initCustLeadRule()])
  hasPageCache() ? restorePageCache() : getListData()
})
```

 目前的解决办法：参考 @wall-git 的办法，让van-list于router的scroll发生后再加载，暂时解决了问题，感觉不优雅，哪位有好的解决办法（阻止vue-router的自动scroll？？？）请@我

```html
<template v-if="isMounted">
  <div class="list-box">
    <van-list
      v-model:loading="listLoading"
      :finished="listFinish"
      :finished-text="listFinishedText"
      :immediate-check="false"
      @load="onListLoad"
    >
    ...
</template>
```

```js
onMounted(async () => {
  isMounted.value = true
  await Promise.all([initDict(['lead_process_status']), initCustLeadRule()])
  hasPageCache() ? restorePageCache() : getListData()
})
```

**Comment by hexianzhi** [comment]
先把 finished 属性设置成true，手动加载后再设置成 false
