### ISSUE TITLE
van-list网络错误后无限触发load

### ISSUE THREAD

**Issue by riceeeee** [youzan/vant#7788]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

--- load加载数据方法如下，正常情况下没问题，在网络错误后设置error=true,之后网络恢复后点击errot-text,就一直不停的触发load方法
 `
onLoad() {

      this.loading = true;

      this.finished = false;

      this.page += 1;
      getOrderList(this.page, this.filterParams)
        .then((res) => {
          this.loading = false;
          this.error = false;
          this.list = this.list.concat(res.data.list);
          if (this.list.length >= res.data.total) {
            this.finished = true;
          }
        })
        .catch(() => {
          this.loading = false;
          this.error = true;
        });
    }`

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
