### ISSUE TITLE
[Bug Report] search组件的cancel方法不会触发

### ISSUE THREAD

**Issue by neohan666** [youzan/vant#7792]
### 设备 / 浏览器
chrome87、android9.0 webview

### Vant 版本
3.0.0-rc.2

### Vue 版本
3.0.4

### 重现链接
<a href="http://localhost:8080" target="_blank">http://localhost:8080</a>

### 描述问题
van-search，@cancel绑定的事件无法触发

**Comment by ZhengXiaowei** [comment]
能上代码吗？你是不是用了插槽了

**Comment by neohan666** [comment]
> 能上代码吗？你是不是用了插槽了

是的，使用了插槽，但不是取消按钮的插槽会有影响吗？代码如下：
```js
<van-search
  v-model="searchVal"
  shape="round"
  placeholder="输入用户ID或手机号码"
  @search="onSearch"
  @input="onInput"
  @cancel="onCancel"
>
  <template #left-icon>
    <i class="leftIcon"></i>
  </template>
  <template #right-icon>
    <button class="rightIcon" @click="onSearch">搜索</button>
  </template>
</van-search>
```

**Comment by ZhengXiaowei** [comment]
需要设置`show-action`属性后 才会有`cancel`事件的派发。

**Comment by neohan666** [comment]
> show-action

show-action是搜索框外面右侧的取消按钮，我这里是指搜索里面右侧的清除图标，是clearable属性，默认值是true，点击这个图标没有触发cancel方法。

**Comment by neohan666** [comment]
> 需要设置`show-action`属性后 才会有`cancel`事件的派发。

好吧，又看了下文档，我应该绑定clear事件。。。我有点怀疑人生了，之前2.x就是绑定的cancel正常使用，今天突然注意到还有clear事件，我怀疑你们偷偷改了文档，但我没有证据~囧
