### ISSUE TITLE
[Feature Request] Loading组件支持字体颜色prop

### ISSUE THREAD

**Issue by botaoboyang** [youzan/vant#7795]
### 这个功能解决了什么问题
目前Loading组件所有字体颜色都和主题中定制的颜色一样。加入textColor属性后不同组件颜色可以不同

### 描述您想要的解决方案
在Loading组件中加入textColor支持更换字体颜色

### 建议的API是什么样的
参数：text-color
说明：字体颜色
类型：string
默认：#c9c9c9

**Comment by chenjiahan** [comment]
已在 2.12.2 版本支持
