### ISSUE TITLE
[Bug Report] Dialog组件问题

### ISSUE THREAD

**Issue by gsdfly** [youzan/vant#7796]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0-rc.5

### Vue 版本
3.0.4

### 重现链接
<a href="https://jsbin.com/wuziloseza/1/edit?html,output" target="_blank">https://jsbin.com/wuziloseza/1/edit?html,output</a>

### 描述问题
Dialog.js 里面Popup组件 'onUpdate:show': onUpdateShow 会导致关闭时onUpdateShow 方法被调用2次
如果Dialog组件已经挂载的话，在beforeRouteLeave里面调用弹窗会显示不了  因为PopUp监听了popstate事件 弹窗根本不会显示 
Dialog.js 里面Popup组件 'onUpdate:show': onUpdateShow 好像是没有必要加的

**Comment by chenjiahan** [comment]
onUpdate:show 是有必要的喔，因为点击 overlay 的时候需要监听 Popup 触发的事件。

beforeRouteLeave 的问题可以通过把 closeOnPopstate 属性设置为 false 来解决。
