### ISSUE TITLE
[Bug Report] Tabs标签页组件-滚动导航模式下 连续点击导航栏bug问题

### ISSUE THREAD

**Issue by Eliaukk** [youzan/vant#7798]
### 设备 / 浏览器
ios/安卓/谷歌浏览器

### Vant 版本
2.10.13

### Vue 版本
2.6.12

### 重现链接
<a href="https://m.sd.10086.cn/act_service/fe/sd1119/index.do" target="_blank">https://m.sd.10086.cn/act_service/fe/sd1119/index.do</a>

### 描述问题
Tabs标签页组件-滚动导航模式下 连续点击两次导航栏bug问题 
1、滚动导航模式、默认选中第一个tab,快速点击第三个tab，第三个tab会被激活后 被激活的tab切换为第二个。同理，选中任一个tab  连续点击两次与之相隔一、多个的tab也会发生错乱bug

**Comment by chenjiahan** [comment]
上面这个链接登录不进去，能否提供一下 codesandbox 复现链接？

https://codesandbox.io/s/m5v3f
