### ISSUE TITLE
[Feature Request] area组件无法自定义排序

### ISSUE THREAD

**Issue by laoheiyang** [youzan/vant#7799]
### 这个功能解决了什么问题
因有时候热门地区需要放到前面，所以需要自定义

### 描述您想要的解决方案
因area组件键值对为数字型，导致js默认排序为数字从小到大，无法自定义排序。

### 建议的API是什么样的
建议调整读取结构，我现在自己手写了一个三级省市区才解决

**Comment by laoheiyang** [comment]
补充，之前查明无法自定义排序的原因是手动修改js顺序以后 但是AreaList 会自动把值排序

**Comment by chenjiahan** [comment]
Area 组件内的省市区顺序确实没法调换，推荐使用新出的 Cascader 级联选择组件，交互上更加友好

https://vant-contrib.gitee.io/vant/#/zh-CN/cascader
