### ISSUE TITLE
[Bug Report] Calendar组件文档示例代码错误

### ISSUE THREAD

**Issue by zlienqwe** [youzan/vant#7803]
设备 / 浏览器
chrome

Vant 版本
3.0.0

Vue 版本
3.0.4

重现链接
https://vant-contrib.gitee.io/vant/next/#/zh-CN/calendar

描述问题
![image](https://user-images.githubusercontent.com/8232140/103056023-c5df5d80-45d6-11eb-92b0-1bd56c4d15e7.png)

Calendar 文档， date参数和变量重复，需要更换名字

**Comment by chenjiahan** [comment]
感谢反馈，文档已更正
