### ISSUE TITLE
vant部分字体乱码现在怎么处理

### ISSUE THREAD

**Issue by songquan123** [youzan/vant#7804]
目前出现在上拉加载和Dialog 弹出框的确认字体乱码
![image](https://user-images.githubusercontent.com/64070942/103065898-a9e9b500-45f2-11eb-9d92-b6898ed4a4e8.png)
![image](https://user-images.githubusercontent.com/64070942/103065942-bf5edf00-45f2-11eb-8a3d-26bfdfc3a414.png)

**Comment by songquan123** [comment]
![1608790866(1)](https://user-images.githubusercontent.com/64070942/103066039-ffbe5d00-45f2-11eb-909f-daed44357210.jpg)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
