### ISSUE TITLE
popover组件，设置偏移后，那个小三角也会一起偏移！

### ISSUE THREAD

**Issue by lwm98** [youzan/vant#7805]
因为这边需求要做的是，点击问号，打开一个popover展示，设置的是居中的popover

使用的时候发现几个弊端：
1.设置偏移后 小三角一起偏移了
2.设置偏移后 无法根据屏幕大小变动自适应了（就是小屏幕设置偏移多少，到大屏幕还是偏移多少，对不准了）

**Comment by chenjiahan** [comment]
小三角跟随偏移是符合预期的，没有问题。

另外 Popover 的定位目前没有自适应的逻辑，可以监听 resize 事件并动态进行设置。
