### ISSUE TITLE
[Bug Report] count-down组件在服务端渲染时由于auto-start默认为true导致内存无法释放

### ISSUE THREAD

**Issue by windinsky** [youzan/vant#7807]
### 设备 / 浏览器
linux nodejs

### Vant 版本
2.12.0

### Vue 版本
2.6.12

### 重现链接
<a href="http://www.服务端渲染问题，没法加链接.com" target="_blank">http://www.服务端渲染问题，没法加链接.com</a>

### 描述问题
服务端渲染的时候会触发reset方法，由于autoStart属性默认是true，会调用tick方法开始启动循环timer计时，导致该对象在timer结束之前都释放不掉，内存持续囤积。

例如页面上有一个倒计时到一周之后结束，一旦有人访问了这个页面，该countdown组件渲染过程中产生的模版字符串/Vue对象以及该timeout的运行链全部会在内存中驻留一周，除非该进程重启。

建议该属性的默认值在server端设置为false

**Comment by chenjiahan** [comment]
可以的，后续优化下

**Comment by chenjiahan** [comment]
已在 2.12.1 版本修复
