### ISSUE TITLE
[Bug Report] Field组件click-input事件不生效

### ISSUE THREAD

**Issue by fengyun2** [youzan/vant#7813]
### 设备 / 浏览器
win10/Chrome v87.0.4280.88

### Vant 版本
3.0.0

### Vue 版本
3.0.4

### 重现链接
<a href="https://codesandbox.io/s/vant3-demo-enrlc?file=/src/components/HelloWorld.vue" target="_blank">https://codesandbox.io/s/vant3-demo-enrlc?file=/src/components/HelloWorld.vue</a>

![image](https://user-images.githubusercontent.com/8147202/103089245-67db6600-4628-11eb-84cd-33fd00e927ce.png)

### 描述问题
Field组件click-input事件不生效

**Comment by chenjiahan** [comment]
codesandbox 链接里确实没生效，但我本地试了下是正常的，原因待排查

**Comment by chenjiahan** [comment]
本地依然没有复现，先 close 咯。

如果能提供复现的 demo 仓库最好~

**Comment by fengyun2** [comment]
@chenjiahan 从这个代码仓库 https://codesandbox.io/s/vant3-demo-enrlc?file=/src/components/HelloWorld.vue 下载下来，在本地使用 `yarn` 安装运行，点击也可复现

![image](https://user-images.githubusercontent.com/8147202/135789853-3ccffe18-5d91-4f32-b2f2-2de2bcb66062.png)
