### ISSUE TITLE
[Bug Report] field组件value属性无效，页面不显示内容。

### ISSUE THREAD

**Issue by hiQbit** [youzan/vant#7817]
### 设备 / 浏览器
edge

### Vant 版本
3.0.0

### Vue 版本
3.0.4

### 重现链接
<a href="https://jsbin.com/yolilaw/edit?html,output" target="_blank">https://jsbin.com/yolilaw/edit?html,output</a>

### 描述问题
<van-cell-group>
  <van-field label="文本" value="输入框只读" readonly />
  <van-field label="文本" value="输入框已禁用" disabled />
</van-cell-group>

![微信截图_20201225143342](https://user-images.githubusercontent.com/30611253/103124093-8d687e00-46c1-11eb-84eb-b68b54282001.png)
![微信截图_20201225143453](https://user-images.githubusercontent.com/30611253/103124096-8e99ab00-46c1-11eb-91e2-19d115b33166.png)

**Comment by xderorschach** [comment]
同样的问题，希望尽快修复，这个比较重要

**Comment by chenjiahan** [comment]
在 Vue 3 中，v-model 对应的 props 为 model-value，而不是 Vue 2 中的 value 属性。

迁移指南里有提到： https://youzan.github.io/vant/next/#/zh-CN/migrate-from-v2#biao-dan-xing-zu-jian-v-model-nei-bu-zhi-bian-geng

**Comment by hiQbit** [comment]
> 在 Vue 3 中，v-model 对应的 props 为 model-value，而不是 Vue 2 中的 value 属性。
> 
> 迁移指南里有提到： https://youzan.github.io/vant/next/#/zh-CN/migrate-from-v2#biao-dan-xing-zu-jian-v-model-nei-bu-zhi-bian-geng

谢谢解答，建议文档demo代码中，不要写 `:value=""` 这类了，修正为 `:model-value="value"` 可能更利于用户理解。

**Comment by chenjiahan** [comment]
好的，有部分地方改漏了，近期会修正
