### ISSUE TITLE
[Feature Request] Calendar 日历 选择日期区间的时候，能选择同一天

### ISSUE THREAD

**Issue by value-red** [youzan/vant#7819]
### 这个功能解决了什么问题
解决定义选择日期区间的情景下，只选择当某一天

### 描述您想要的解决方案
开启开始和结束能否选择同一天

### 建议的API是什么样的
添加选项 开始和结束能选择同一天

**Comment by chenjiahan** [comment]
可以通过设置 allow-same-day 属性来允许选择同一天，文档里有写。
