### ISSUE TITLE
[Bug Report]SSR is not support?

### ISSUE THREAD

**Issue by falstack** [youzan/vant#782]
![1](https://user-images.githubusercontent.com/16357724/37943948-5a214e82-31ac-11e8-9231-f8386fbf08b3.png)
![2](https://user-images.githubusercontent.com/16357724/37943949-5a5de2e8-31ac-11e8-96a5-11cffcc9a8b4.png)
![3](https://user-images.githubusercontent.com/16357724/37943950-5a94a8e6-31ac-11e8-833e-88ae26c6ed02.png)
![4](https://user-images.githubusercontent.com/16357724/37943952-5ac9ca12-31ac-11e8-8446-4799c1375a90.png)

vant 整体感觉很棒，打算在之后的项目中使用，并且因为 mintUI 部分组件不支持 SSR 所以打算使用 vant。
vant 说是支持 SSR，但是部分组件还是没有支持的，希望能够在之后对 SSR 有更好的支持，这样使用的人会更多吧。

感谢开源！

**Comment by chenjiahan** [comment]
SSR 是支持的，但是现在 babel-plugin-import 和 nuxt 有冲突，所以使用 nuxt 的话建议手动按需引入组件

**Comment by guojingwen** [comment]
@chenjiahan 预计多久能支持ssr

**Comment by chenjiahan** [comment]
@meowforwhat 样式按正常方式引入就行
@guojingwen vant 是支持 SSR 的，目前的问题是 babel-plugin-import 这个插件不支持

**Comment by guojingwen** [comment]
@chenjiahan 
![image](https://user-images.githubusercontent.com/12098305/40398742-35baa3b2-5e6c-11e8-90d7-6c24bffd8439.png)
这种是否OK?

**Comment by ailuyao** [comment]
现在使用 babel-plugin-import, ssr  还存在问题...

**Comment by PepperYan** [comment]
今天解决了这个问题, 分享一下, 本人使用nuxt ssr (未试过测试普通ssr) 按照官方文档使用babel-plugin-import的时候出现该issue的错误 [https://github.com/youzan/vant/issues/765](url)

然后改用 babel-plugin-component 如下配置以后,亲测可用 (nuxt-edge 2.0)
这里只贴babel部分配置
![88a7aa12-40f9-4598-bc23-44f6eb1c4b92](https://user-images.githubusercontent.com/2188161/43718091-2dc82eaa-99bc-11e8-9542-ee6229ea26b4.png)


值得注意的是, vant中有部分组件(应该逻辑组件)不带css文件, 直接引用会报错, 需要小改一下.

![ac767d04-9f18-4983-bc62-027d4c9026f5](https://user-images.githubusercontent.com/2188161/43718064-15b22cb2-99bc-11e8-8a25-0cddfe0a203f.png)

**Comment by KidneyFlower** [comment]
现在有个问题，通过配置 babel-plugin-component 成功实现按需引入组件和组件样式了，但是一些公共样式并没有被引入，会导致一些小问题（如 Button 组件点击后会有 outline 等等），看了下 vant 并没有 base.css 这种公用的样式文件，请问如何解决这个问题，可否提供一份与组件无关的样式呢？

**Comment by zionLu** [comment]
您好，我这边在ssr的项目中引入vant的tab组件时发现页面加载初期审查的元素还是<van-tabs>...</van-tabs>这样的形式，请问怎样才能在静态化时就将组件的代码打进html中？谢谢

**Comment by lienonegithub** [comment]
list组件loading在nuxt中怎么处理@chenjiahan

**Comment by gaoxianglyx** [comment]
> 您好，我这边在ssr的项目中引入vant的tab组件时发现页面加载初期审查的元素还是...这样的形式，请问怎样才能在静态化时就将组件的代码打进html中？谢谢

我也遇到这个问题
