### ISSUE TITLE
可不可以出一套  后台管理模板。包括菜单、路由这些。类似vue-element-admin或者 iview 的后台脚手架

### ISSUE THREAD

**Issue by Nassicy** [youzan/vant#7823]
http://vant-contrib.gitee.io/vant-issue-generater

 可不可以出一套  后台管理模板。包括菜单、路由这些。类似vue-element-admin或者 iview 的后台脚手架

**Comment by chenjiahan** [comment]
暂无计划支持喔，Vant 是移动端的，场景不同。

**Comment by Nassicy** [comment]
> 暂无计划支持喔，Vant 是移动端的，场景不同。

好的吧，多谢
