### ISSUE TITLE
[Bug Report] swipe loop模式下滚动到最后会闪动

### ISSUE THREAD

**Issue by ZhengXiaowei** [youzan/vant#7828]
### 设备 / 浏览器
macOS / mobile

### Vant 版本
3.0.1

### Vue 版本
3.0.4

### 重现链接
<a href="http://normal-image.xiaovv-web.com/normal/2020-12-28-swipe-bug.gif" target="_blank">http://normal-image.xiaovv-web.com/normal/2020-12-28-swipe-bug.gif</a>

### 描述问题
loop滚动问题

**Comment by ZhengXiaowei** [comment]
用的是最简单的demo
```
const renderSwipes = () => {
      return (
        <van-swipe class="my-swipe" autoplay={3000} height={250}>
          <van-swipe-item>1</van-swipe-item>
          <van-swipe-item>2</van-swipe-item>
          <van-swipe-item>3</van-swipe-item>
          <van-swipe-item>4</van-swipe-item>
        </van-swipe>
      );
    };
```

**Comment by chenjiahan** [comment]
可以用 Vue 3.0.3 试下，参见 https://github.com/youzan/vant/issues/7709
