### ISSUE TITLE
[Feature Request] 数字键盘键入数字随机排列

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#7831]
### 这个功能解决了什么问题
数字键盘1-9随机排列，提高安全性

### 描述您想要的解决方案
加入一个字段设置是否随机排列数字，true为随机，false为不随机

### 建议的API是什么样的
numberRandom：true随机排列数字，false不随机排列数字

![image](https://user-images.githubusercontent.com/21211777/103253152-e6cef680-49ba-11eb-8fe7-5037f75064aa.png)

![image](https://user-images.githubusercontent.com/21211777/103253205-23025700-49bb-11eb-9608-216e88e88f2c.png)

**Comment by chenjiahan** [comment]
已在 2.12.2 版本支持，random-key-order 属性
