### ISSUE TITLE
[Feature Request]calendar组件中加入当前视口月份参数

### ISSUE THREAD

**Issue by OTT179** [youzan/vant#7833]
### 这个功能解决了什么问题
calendar 无 default-date 时，当前视口月份为第一个可选月，无法自动滚动至最后一个可选月；
常见业务场景：选择历史记录，打开日期选择，可选日期为 XXXX-XX-XX 至 今天，视口月份为 当前月;
目前我的解决方法：使用内部实例方法 scrollIntoView，但上个月标题要滚动才能出来
```
const _picker$refs = this.$refs.datePicker.$refs
const body = _picker$refs.body
const months = _picker$refs.months
months[months.length - 2] && (months[months.length - 2].visible = true)
if (months[months.length - 1]) {
  months[months.length - 1].visible = true
  months[months.length - 1].scrollIntoView(body)
}
```

### 描述您想要的解决方案
在calendar组件中加入当前视口月份 参数

### 建议的API是什么样的
参数：view-month
说明：视口月份
类型：string | object
默认：''

**Comment by value-red** [comment]
const _picker$refs = this.$refs.datePicker.$refs
const body = _picker$refs.body
const months = _picker$refs.months
months[months.length - 1].scrollIntoView(body)
滚动到默认传入选中日期的首屏会出现白屏，日期的数据没有进入渲染

**Comment by value-red** [comment]
![image](https://user-images.githubusercontent.com/35253868/103329339-50bcce00-4a97-11eb-88fb-5f73a5038e14.png)

**Comment by OTT179** [comment]
> const _picker$refs = this.$refs.datePicker.$refs
> const body = _picker$refs.body
> const months = _picker$refs.months
> months[months.length - 1].scrollIntoView(body)
> 滚动到默认传入选中日期的首屏会出现白屏，日期的数据没有进入渲染

有的浏览器会这样，试一下改成下面这样，但上个月标题要滚动才能出来
```
const _picker$refs = this.$refs.datePicker.$refs
const body = _picker$refs.body
const months = _picker$refs.months
months[months.length - 2] && (months[months.length - 2].visible = true)
if (months[months.length - 1]) {
  months[months.length - 1].visible = true
  months[months.length - 1].scrollIntoView(body)
}
```

**Comment by chenjiahan** [comment]
已在 2.12.2 版本新增 scrollToDate 方法

**Comment by starlet0822** [comment]
vant ^2.9.4 怎么访问不到  scrollToDate 方法

**Comment by shimangdian** [comment]
@starlet0822  更新到2.12.2 版本 ，但是这个方法 无效，下面是我的代码
```vue
<template>
        <Calendar
            ref='calendar'
            :first-day-of-week="0"
            :poppable="false"
            :show-confirm="false"
            :show-mark='false'
            :show-title='false'
            :show-subtitle='false'
            :row-height='30'
            :style="{ height: '60px' }"
        />
</template>
<script>
import { Calendar } from 'vant';
export default {
    components: {
        Calendar,
    },
mounted() {
        this.$nextTick(() => {
            this.$refs.calendar.scrollToDate(new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 365));
        });
    },
  }
</script>

```

**Comment by shimangdian** [comment]
我无法跳转是因为 组件默认 最大时间为未来6个月，而我跳转到下一年了。😅
