### ISSUE TITLE
[Bug Report] Popup等弹窗组件，导致页面没法滚动

### ISSUE THREAD

**Issue by rxyshww** [youzan/vant#7835]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0

### Vue 版本
3.0.4

### 描述问题
能不能组件内部UnMounted时候，消除van-overflow-hidden样式，打开popup，然后点击浏览器后退时，或者直接跳转页面，这个样式不能自己清除，导致页面不能滚动，而且自己手动清了这个样式，重新打开popup，样式也不会再加上去

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 3.0.2 版本修复
