### ISSUE TITLE
[Bug Report] stepper组件的change事件不是在增、减按钮时触发

### ISSUE THREAD

**Issue by OrdinaryPath** [youzan/vant#7836]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/stepper" target="_blank">https://youzan.github.io/vant/#/zh-CN/stepper</a>

### 描述问题
stepper组件的change事件在其他操作下改变了v-model的值也会触发change事件，我希望是点击增减、减少或者在input输入的时候才触发change事件

**Comment by chenjiahan** [comment]
这个行为是符合预期的喔，暂无计划更改
