### ISSUE TITLE
[Bug Report] calendar中的month组件getDate方法props.data的错误

### ISSUE THREAD

**Issue by sanfengliao** [youzan/vant#7837]
### 设备 / 浏览器
所欲设备

### Vant 版本
3.0.1

### Vue 版本
3.0.4

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/src/calendar/components/Month.js#L68" target="_blank">https://github.com/youzan/vant/blob/dev/src/calendar/components/Month.js#L68</a>

### 描述问题
calendar中的month组件getDate方法应该是要返回props.date，但是代码中写成了props.data
```
 const getDate = () => props.data;
```
应该是要
```
const getDate = () => props.date;
```

**Comment by chenjiahan** [comment]
已修正👌
