### ISSUE TITLE
Icon组件在iphone6：Safari 无法看见,希望改善一下兼容性

### ISSUE THREAD

**Issue by InMath** [youzan/vant#784]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
麻烦提供一下截图，最好是打开官网文档确认下
