### ISSUE TITLE
mac air m1下 执行dev命令 就直接内存溢出了

### ISSUE THREAD

**Issue by fangkyi03** [youzan/vant#7840]
[36593:0x118008000]    59683 ms: Scavenge (reduce) 2037.7 (2053.7) -> 2037.0 (2053.9) MB, 1.6 / 0.0 ms  (average mu = 0.239, current mu = 0.010) allocation failure 
[36593:0x118008000]    60211 ms: Mark-sweep (reduce) 2037.8 (2050.9) -> 2037.0 (2051.9) MB, 526.7 / 0.4 ms  (average mu = 0.149, current mu = 0.035) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1012e3d85 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a6239 node::Abort() [/usr/local/bin/node]
 3: 0x1000a639f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001e8e47 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001e8de3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100397cd5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x10039979a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x100394e69 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x100392701 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x1003a0f9a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x1003a1021 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x10036e9c7 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
13: 0x1006ed708 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x100a7a059 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]

我自己去掉了test文件以后 虽然可以成功跑起来了 但是运行了几秒钟以后 又内存溢出了 又空可以看一看

**Comment by fangkyi03** [comment]
自己本地其他的前端项目都好使 就唯独你们的这个项目不行

**Comment by chenjiahan** [comment]
抱歉，没有 M1 的机器，建议自行排查下

**Comment by fangkyi03** [comment]
没有m1的机器 也不能直接关闭吧 以后都是m1的 难道就不解决了？

**Comment by chenjiahan** [comment]
没有按模板创建的 issue 都会直接关闭。

**Comment by fangkyi03** [comment]
mac m1 内存泄漏的原因我找到了
  cache: {
    type: 'filesystem',
    buildDependencies: {
      config: [__filename],
    },
  },
就在于这一行代码 去掉以后就再也没有出现过内存泄漏问题

**Comment by chenjiahan** [comment]
这个是 webpack 本身的缓存机制，可以等 webpack 进行适配

**Comment by fangkyi03** [comment]
但是这个代码是你们加的 我觉得你们可以先去除这部分代码 至少可以让所有m1的设备不报错 毕竟加跟不加 并不会有很大的影响 如果等后期webpack升级了 你们可以在加回来 不然现在所有用m1的都是直接崩溃报错 何必呢 明明去掉就可以用的

**Comment by chenjiahan** [comment]
直接禁用不是很合适，会影响编译性能，node.js 里有方式能判断机器是否为 m1 么？

**Comment by fangkyi03** [comment]
我在写一套新的编译了 用deno做底层 将你们的那套东西直接用deno来跑 每个项目都搞一个node_module 实在是看得起我m1 256的体积了 扛不住
