### ISSUE TITLE
[Bug Report] stepper组件change事件触发问题

### ISSUE THREAD

**Issue by OrdinaryPath** [youzan/vant#7842]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/coolTea/pen/MWjQvxY" target="_blank">https://codepen.io/coolTea/pen/MWjQvxY</a>

### 描述问题
当我点击button组件改变stepper组件中v-model绑定值得时候，也会触发change事件(我并不希望这样),请问这个也是产品当初设计好的嘛？(demo可以点击我提供的连接)，我希望可以像elementUI中InputNumber组件一样,不会触发change事件

**Comment by chenjiahan** [comment]
这个是设计好的喔，暂时没有计划调整这部分逻辑（属于不兼容改动）。
