### ISSUE TITLE
[Bug Report] 在ts环境下，@vant/use使用useToggle，提示toggle()报错

### ISSUE THREAD

**Issue by aloha66** [youzan/vant#7843]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.1

### Vue 版本
3.0.5

### 重现链接
<a href="https://github.com/youzan/vant/tree/dev/packages/vant-use/src/useToggle" target="_blank">https://github.com/youzan/vant/tree/dev/packages/vant-use/src/useToggle</a>

### 描述问题
找了很久不知道怎么解决

const toggle: Ref<boolean> | ((value?: boolean) => void)
This expression is not callable.
  Not all constituents of type 'Ref<boolean> | ((value?: boolean) => void)' are callable.
    Type 'Ref<boolean>' has no call signatures.Vetur(2349)

**Comment by chenjiahan** [comment]
能否看一下你的复现代码

**Comment by aloha66** [comment]
```vue
<script lang="ts">
import {defineComponent} from "vue";
import {useToggle} from "@vant/use";
export default defineComponent({
  name: "Home",
  setup() {
    const [state, toggle] = useToggle();
    toggle(true);
    console.log(state.value); // -> true
  },
});
</script>
```

@vue/cli 4.5.9下，tsconfig.json的默认配置
```json

{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": ["webpack-env", "jest"],
    "paths": {
      "@/*": ["src/*"]
    },
    "lib": ["esnext", "dom", "dom.iterable", "scripthost"]
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue", "tests/**/*.ts", "tests/**/*.tsx"],
  "exclude": ["node_modules"]
}

```

我对ts不熟，尝试改成"strict": false,也是报这个错
![image](https://user-images.githubusercontent.com/20942781/103402248-4bd74780-4b87-11eb-81c1-e572264f25bd.png)

**Comment by chenjiahan** [comment]
类型定义确实有问题，已经在 @vant/use 1.0.2 版本修复咯
