### ISSUE TITLE
van-datetime-picker的type="year-month"时报错,空指针异常

### ISSUE THREAD

**Issue by zongrenCode** [youzan/vant#7848]
https://vant-contrib.gitee.io/vant-weapp/#/datetime-picker
![image](https://user-images.githubusercontent.com/38056993/103472586-12dae500-4dca-11eb-8ceb-e73f78eb26f8.png)
![image](https://user-images.githubusercontent.com/38056993/103472591-25edb500-4dca-11eb-8b70-6ab7bb97ab39.png)
![image](https://user-images.githubusercontent.com/38056993/103472601-39991b80-4dca-11eb-887d-e0fe8663eb00.png)

**Comment by chenjiahan** [comment]
小程序问题请到 vant-weapp 仓库下按照模板反馈，感谢配合
