### ISSUE TITLE
[Feature Request] DatetimePicker组件type=time时，value是否应该支持Date属性

### ISSUE THREAD

**Issue by nemo-shen** [youzan/vant#7849]
### 这个功能解决了什么问题
DatetimePicker在type=time时，value值能够是Date属性

### 描述您想要的解决方案
是否可能，有时候会在value中传递一个Date属性，例如`new Date(2020, 0, 1, 12, 12)`
```js
<van-datetime-picker
  :value="new Date(2020, 0, 1, 12, 12)"
  type="time"
/>
```

其实我们可以从这里获取到时间的，但是我在看`vant/src/datetime-picker/TimePicker.js` 中的`formatValue`方法时，好像默认只判断value是否为空值，如果是的话直接用min(Hour|Minute)进行赋值，没有做其他的处理，这里是否有必要做一些优化呢？

### 建议的API是什么样的
![image](https://user-images.githubusercontent.com/13480805/103475060-e8e2ec00-4de4-11eb-8889-acbee1a87ce5.png)

**Comment by chenjiahan** [comment]
没有必要，当 type 为 time 时，v-model 值的类型就是 string。

如果既要支持 string，又要支持 Date，在输入和输出的格式上会变得很混乱。
