### ISSUE TITLE
[Bug Report] Checkbox 复选框选中图标展示不出来

### ISSUE THREAD

**Issue by MissZhoudada** [youzan/vant#7850]
### 设备 / 浏览器
iphone/原生默认

### Vant 版本
2.10.11

### Vue 版本
2.5.2

### 重现链接
<a href="https://jsbin.com/?html,output" target="_blank">https://jsbin.com/?html,output</a>

### 描述问题
v2.10.11的Checkbox 复选框选在iphone的版本14.2以上选中之后勾选的图标展示不出来，切换成^v2.6.0 的也不行，所有的iphone手机上14.2版本以上的图标无法展示的问题都可以重现，我们的vue版本是^2.5.2,希望团队帮忙看看

**Comment by chenjiahan** [comment]
麻烦提供有效的复现链接

https://codesandbox.io/s/m5v3f

**Comment by Mr-Plants** [comment]
+1，希望团队帮看一下

**Comment by chenjiahan** [comment]
未复现，先 close 咯
