### ISSUE TITLE
上传组件:after-read="afterRead" ，中file在手机端为{}，在pc上可以正常返回

### ISSUE THREAD

**Issue by W23mq** [youzan/vant#7851]
### 设备 / 浏览器
iphone

### Vant 版本
2.12.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
文件上传组件:after-read="afterRead" 中file在移动端返回为{},在pc上可正常返回

**Comment by chenjiahan** [comment]
麻烦提供有效的 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by W23mq** [comment]
> 麻烦提供有效的 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

https://codesandbox.io/s/vant-issue-moban-forked-w5qmv?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675

https://w5qmv.csb.app/  

麻烦用手机进行测试并查看输出

**Comment by chenjiahan** [comment]
手机端是能正确获取到 file 对象的喔，看到 {} 应该只是因为 vconsole 不支持输出完整的对象
