### ISSUE TITLE
[Bug Report] 在动态路由中，按需引入Dialog、Notify导致Popup发生样式覆盖

### ISSUE THREAD

**Issue by sylvaner-h** [youzan/vant#7854]
### 设备 / 浏览器
All

### Vant 版本
3.0.2

### Vue 版本
3.0.4

### 重现链接
<a href="https://github.com/sylvaner-h/v3-vant-popup-style-override" target="_blank">https://github.com/sylvaner-h/v3-vant-popup-style-override</a>

### 描述问题
仅在打包后出现，复现步骤：
1.pageA，执行Notify()
2.跳转至pageB:，执行Dialog.alert()
3.跳转至pageA，执行Notify()，此时Notify的background-color被Popup的样式覆盖，如图：
![image](https://user-images.githubusercontent.com/31810070/103507430-16d63800-4e9a-11eb-839c-f3a76701e3ae.png)

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/103523141-688cbb80-4eb6-11eb-8f17-91460ff5276a.png)

打包了两份 Popup 的代码，建议自行排查下打包逻辑。组件内部的样式顺序是没问题的。

**Comment by sylvaner-h** [comment]
是的，Popup分别是来自Notify和Dialog，如果在入口页同时引入就没有问题。

**Comment by chenjiahan** [comment]
不建议在组件内部解决，这样的优先级问题是无法穷举的

**Comment by Youcongcong** [comment]
@sylvaner-h 请问有解决吗。我用的是vite打包也出现了覆盖现象
![Uploading image.png…]()

**Comment by Youcongcong** [comment]
@sylvaner-h 请问有解决吗。我用的是vite打包也出现了覆盖现象 <img width="577" alt="image" src="https://user-images.githubusercontent.com/20183676/119484903-124ae700-bd89-11eb-9e9f-b096a96d7a16.png">

**Comment by EthanVn** [comment]
// 解决Vant样式冲突, Notify被Popup覆盖
.van-notify--primary {
  background-color: var(--van-notify-primary-background) !important;
}
.van-notify--success {
  background-color: var(--van-notify-success-background) !important;
}
.van-notify--danger {
  background-color: var(--van-notify-danger-background) !important;
}
.van-notify--warning {
  background-color: var(--van-notify-warning-background) !important;
}
