### ISSUE TITLE
[Bug Report] van-search 无法通过ref获取输入框实例

### ISSUE THREAD

**Issue by Longqiliang** [youzan/vant#7855]
### 设备 / 浏览器
Google Chrome

### Vant 版本
2.12.1

### Vue 版本
2.6.12

### 重现链接
<a href="https://codepen.io/long_ql/pen/ZEpxZgz" target="_blank">https://codepen.io/long_ql/pen/ZEpxZgz</a>

### 描述问题
vant3.0以下 van-search 无法通过ref获取到输入框实例。
期望：通过 ref 可以获取到 Field 实例并调用实例方法。

**Comment by chenjiahan** [comment]
vant 2.x 里的 Search 是 functional component，所以没法获取实例。

这个改动属于不兼容更新，所以没法在 2.x 版本里调整。
