### ISSUE TITLE
用了@vant/touch-emulator后tinymce富文本编辑在电脑端就无法点击了，请问有好的解决办法么

### ISSUE THREAD

**Issue by 79229788** [youzan/vant#7857]
用了@vant/touch-emulator后在使用tinymce编辑器在电脑端就无法点击了（主要是编辑器的工具栏的按钮大部分都点击都无效了），应该是两者冲突，请问有好的解决办法么

**Comment by 79229788** [comment]
tinymce@5.1.4版本正常可用（之前的没测试），而之后的版本以及最新版本都不可用（未来版本也很可能无法使用了），暂时先用到老版本吧，这个tinymce很出名，用的人很多，也没其它代替方案，幸好老版本可用，新版本也不知道具体哪里出现了冲突，所以无从下手

**Comment by chenjiahan** [comment]
不考虑其他库的兼容问题，建议自行排查喔。

**Comment by tanker5258** [comment]
> 用了@vant/touch-emulator后在使用tinymce编辑器在电脑端就无法点击了（主要是编辑器的工具栏的按钮大部分都点击都无效了），应该是两者冲突，请问有好的解决办法么


我出的问题是  另外一个编辑器，touch-emulator插件 跟 jodit富文本编辑器冲突
只要一引入touch-emulator   jodit编辑器里面的文本内容就无法选中（无法进行框选）



以下是我自己的解决办法
这个创建拖放记录表的函数，如果里面能够做个过滤，只针对 某个Target作监测就可以了。
因此，我创建了一个 if判断，如果 目前拖放的 Target目标的id， 包含特定的字符串（"自己定一个字符串"），那么就把这个目标的所有拖放事件放入拖放记录池。其余对象说明跟 拖放事件无关，就不加监测，过滤掉。
下面就是我修改的 import '@vant/touch-emulator'; （index.js）

function createTouchList(mouseEv) {
//创建一条if过滤，id包含自定义字符串的，才加入拖放列表池，否则忽略掉。
if (eventTarget.id.indexOf("dpk_touch") != -1) {
//console.log(eventTarget);
var touchList = TouchList();
touchList.push(new Touch(eventTarget, 1, mouseEv, 0, 0));
return touchList;
}
}

**Comment by tanker5258** [comment]
其实就加了一句代码，实现了  对特定组件的 按需拖放，其他正常组件，不让 touch-emulator 插件生效。
我认为这是目前为止最好的解决办法，因此，该插件目前是 不管三七二十一，所有鼠标拖动事件，全部要经过该插件处理一遍，显然不科学。
只要把有限的几个在电脑端拖动有问题的  组件监测起来，用上这个插件就行了。

if (eventTarget.id.indexOf("dpk_touch") != -1)     //加这一句 判断足以  需要监视的组件，可以起名 dpk_touch_01 02 03.......。
既然官方 认为这不是一个BUG，那么只能咱们自己改造了。。
