### ISSUE TITLE
如何获取vant-tabs的高度？ vue中使用ref以及操作dom元素都没有办法获取到

### ISSUE THREAD

**Issue by BekeWorker** [youzan/vant#7858]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
ref 可以获取的，通过 this.$refs.tab.$el 获取到对应的节点。
