### ISSUE TITLE
可以修改基础字体的大小吗？

### ISSUE THREAD

**Issue by wlinglinux** [youzan/vant#7859]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by wlinglinux** [comment]
自定义主题可以修改的font-size-xs这样的字体的大小，但是我的设计稿是750和vant不一样，我想覆盖基础的字体大小，不知道有基础变量可以覆盖的？

**Comment by chenjiahan** [comment]
没有喔
