### ISSUE TITLE
[Bug Report] 如何实时获取sku中的 "已选择 xx"与"请选择 xx"部分的内容

### ISSUE THREAD

**Issue by bestitxq** [youzan/vant#7860]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.10.10

### Vue 版本
2.6.1

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/sku" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/sku</a>

### 描述问题
商品详情页用到了sku中已选择未选择的内容，请问， 如何实时获取sku中的 "已选择 xx"与"请选择 xx"部分的内容？
（getSkuData这个方法1.全部选择完成才能出现已选择的商品信息，不符合需求。2.规格字段都是动态的从此方法中获取比较繁琐）

**Comment by chenjiahan** [comment]
Sku 组件不支持实时获取以上信息喔，暂时没有计划提供 API 来获取
