### ISSUE TITLE
[Bug Report] Popover 气泡弹出框 循环选择问题

### ISSUE THREAD

**Issue by wozhish** [youzan/vant#7862]
### 设备 / 浏览器
PC

### Vant 版本
3.0.2

### Vue 版本
3.0.0

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/popover" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/popover</a>

### 描述问题
文章列表进行循环之后，点击气泡弹出框，每条文章都会打开一个气泡

**Comment by chenjiahan** [comment]
麻烦提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
