### ISSUE TITLE
优化建议：Vant2中像是AddressEdit之类包含其他组件的组件 能否暴露更多参数来支持自定义？

### ISSUE THREAD

**Issue by KLaw1iet** [youzan/vant#7863]
像是Area支持item-height调整每一项的高度
但是如果用AddressEdit之后 Area的每一项高度就无法单独定义了
就是写死的44px
能否增加一些参数保证这些融合小组件组成的集合组件依然可以对其中的小组件进行自定义？
非常感谢

**Comment by chenjiahan** [comment]
子组件的可选参数太多了，所以没有计划挨个添加喔，如果有单个属性的需求，可以按照模板单独提 issue~
