### ISSUE TITLE
多列下picker组件的键值问题

### ISSUE THREAD

**Issue by hugeng1979** [youzan/vant#7864]
版本：2.10.2
单列时是正常的。

单列时情况：
 <van-picker
        :columns="moduleTypecolumns"
        value-key="text"
        show-toolbar
        :title="$attrs.label"
        @cancel="show = !show"
        @confirm="onConfirm"
      />
 moduleTypecolumns: [
        { keyId: '01', text: '传感器、指示器' },
        { keyId: '02', text: '读卡器' }]

onConfirm(value) {
      console.log('value的值为:' + JSON.stringify(value))
}

输出的可看到是：
value的值为:{"keyId":"01","text":"传感器、指示器"}

以上是单列时的情况，在confirm事件是value是可返回 keyId与text
当多列时：
`columns: [
        {
          text: '浙江',
          keyId: '01',
          children: [
            {
              text: '杭州',
              keyId: '0101',
              children: [
                { text: '西湖区', keyId: '010101' },
                { text: '余杭区', keyId: '010102' }
              ]
            },
            {
              text: '温州',
              keyId: '0102',
              children: [
                { text: '鹿城区', keyId: '010201' },
                { text: '瓯海区', keyId: '010202' }
              ]
            }
          ]
        },
        {
          text: '福建',
          keyId: '02',
          children: [
            {
              text: '福州',
              keyId: '0201',
              children: [
                { text: '鼓楼区', keyId: '020101' },
                { text: '台江区', keyId: '020102' }
              ]
            },
            {
              text: '厦门',
              keyId: '0202',
              children: [
                { text: '思明区', keyId: '020201' },
                { text: '海沧区', keyId: '020202' }
              ]
            }
          ]
        }
      ]`
confirm事件输出是：
value的值为:["浙江","杭州","西湖区"]

我希望在多列时，也能拿到选项的KeyId，有什么办法吗？

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5905
