### ISSUE TITLE
[Bug Report] 效果图裂了

### ISSUE THREAD

**Issue by sfy666666** [youzan/vant#7866]
### 设备 / 浏览器
Chrome

### Vant 版本
3.0.2

### Vue 版本
3.0.5

### 重现链接
<a href="https://github.com/youzan/vant-weapp" target="_blank">https://github.com/youzan/vant-weapp</a>

### 描述问题
所有效果图裂开，看不到效果，不知道要不要使用

**Comment by chenjiahan** [comment]
具体是什么图？

**Comment by sfy666666** [comment]
> 具体是什么图？

所有的图都是裂的，我看别的项目的效果图是正常的

**Comment by chenjiahan** [comment]
我这边都是正常的呢，建议你检查下网络，如果是 Github markdown 里的图片，可能需要翻墙才能看到
