### ISSUE TITLE
[Feature Request] 级联选择器不支持动态加载选项

### ISSUE THREAD

**Issue by kdx168** [youzan/vant#7867]
### 这个功能解决了什么问题
解决级联选择器可以动态加载选项

### 描述您想要的解决方案
场景： 现在有个居民得房屋地址需要去选择到具体室（例如： 上海市/浦东新区/988弄/海州桃花园/70号/503室），这样如果后台一次性返回数据量比较多比较大影响渲染，希望能够选择988弄得时候调接口拿到下一层得数据，但是vant得级联在渲染数据得时候，重新给options赋值不会立马更新数据然后渲染，他会关闭选择框再去打开选择，不友好

### 建议的API是什么样的
希望像antdesign vue组件那样在级联上增加一个loadData（api）用于动态加载选项,具体使用方式可以参考antdesign vue

**Comment by chenjiahan** [comment]
可以参考文档里的 [异步加载选项](https://vant-contrib.gitee.io/vant/#/zh-CN/cascader#yi-bu-jia-zai-xuan-xiang) 示例喔，不会出现你说的 `关闭选择框再去打开选择` 的问题
