### ISSUE TITLE
为什么无法修改 tabs的样式

### ISSUE THREAD

**Issue by PrintingChen** [youzan/vant#787]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
直接通过 class 名覆盖样式即可
