### ISSUE TITLE
[Bug Report] popover组件在每次点击弹出后，点击gird下的girditem组件去触发click时间，首次无效。

### ISSUE THREAD

**Issue by 444136347** [youzan/vant#7870]
### 设备 / 浏览器
google chome

### Vant 版本
2.12.2

### Vue 版本
2.5.2

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/popover" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/popover</a>

### 描述问题
使用了 https://vant-contrib.gitee.io/vant/#/zh-CN/popover里的自定义内容案例

**Comment by 444136347** [comment]
弄错了vant的版本是2.12.2

**Comment by chenjiahan** [comment]
我这边是正常的，能否提供一下 codesandbox 复现链接呢

https://codesandbox.io/s/m5v3f
