### ISSUE TITLE
[Feature Request] sku通过插槽自定义的时候，除了price别的值都获取不到

### ISSUE THREAD

**Issue by ZLBuddy** [youzan/vant#7873]
### 这个功能解决了什么问题
无

### 描述您想要的解决方案
1、请问库存值怎么获取，除了price别的都获取不到
2、默认价格能弄价格区间吗？最小值-最大值这种

### 建议的API是什么样的
解决问题

**Comment by cklwblove** [comment]
可以参考 https://segmentfault.com/q/1010000038887783/a-1020000038890725
