### ISSUE TITLE
[Bug Report] upload组件上传完后点击图片出现的ImagePreview卡顿感严重

### ISSUE THREAD

**Issue by 862881015** [youzan/vant#7874]
### 设备 / 浏览器
iphone X

### Vant 版本
2.8.4

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
upload组件上传完后点击图片出现的ImagePreview卡顿感严重

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/7307
