### ISSUE TITLE
[Feature Request] 请问官方计划开发适配uniapp版的vant ui吗？

### ISSUE THREAD

**Issue by Airam1016** [youzan/vant#7878]
### 这个功能解决了什么问题
之前一直用的van功能非常多，很好用。虽然现在有一些uniapp的UI，但感觉做的远不如vantUI强大好用。希望官方大大可以考虑一下做个uniapp的版本。

### 描述您想要的解决方案
希望官方能为uniapp出个ui版本，让vant应用面扩大，更加完善

### 建议的API是什么样的
希望官方能为uniapp出个ui版本，让vant应用面扩大，更加完善

**Comment by chenjiahan** [comment]
没有计划喔，我们公司没有使用 uni-app 的场景
