### ISSUE TITLE
[Bug Report] navbar  + dropdown +  treeselect 操作时背景透明闪烁

### ISSUE THREAD

**Issue by zhaoyongjiang** [youzan/vant#7879]
### 设备 / 浏览器
google chrome

### Vant 版本
2.8.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://raw.githubusercontent.com/zhaoyongjiang/issues/master/vant/屏幕录制2021-01-09%20上午11.32.13.mov" target="_blank">https://raw.githubusercontent.com/zhaoyongjiang/issues/master/vant/屏幕录制2021-01-09%20上午11.32.13.mov</a>

![image](https://user-images.githubusercontent.com/15276597/104088809-766e8200-52a4-11eb-9b9e-086f9604c305.png)

### 描述问题
navbar上放置dropdown组件，dropdown内嵌入的是treeselect，操作treeselect的时候，背景会透明闪烁，具体请看视频：https://raw.githubusercontent.com/zhaoyongjiang/issues/master/vant/屏幕录制2021-01-09%20上午11.32.13.mov

**Comment by chenjiahan** [comment]
能否提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by zhaoyongjiang** [comment]
> 能否提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f


https://codesandbox.io/s/vant-issue-moban-forked-7utic?file=/src/App.vue

谢谢

**Comment by zhaoyongjiang** [comment]
@chenjiahan https://codesandbox.io/s/vant-issue-moban-forked-7utic?file=/src/App.vue   谢谢

**Comment by chenjiahan** [comment]
这是因为触发了 navbar 按钮点击透明效果导致的。

在 van-dropdown-item 上添加 get-container="body" 属性即可。

**Comment by zhaoyongjiang** [comment]
@chenjiahan perfect 非常感谢
