### ISSUE TITLE
imagePreview的close-on-popstate失效

### ISSUE THREAD

**Issue by jikoy** [youzan/vant#7880]
手机：华为P30Pro，在使用imagePreview时，返回后没有自动关闭。查得资料close-on-popstate默认为true，不用设置的。请测试人员确认此问题。

**Comment by jikoy** [comment]
![image](https://user-images.githubusercontent.com/10125432/104111112-8b392d00-5319-11eb-8dad-a38251187827.png)
用法如上图。

**Comment by jikoy** [comment]
`methods:{
      showPic(url){
        ImagePreview([url]);
      }
    }`

**Comment by jikoy** [comment]
在微信开发工具上调试，问题依然存在。当地址返回时，imagePreview未自动关闭。

**Comment by jikoy** [comment]
vue3.x + vant 3.0.2

**Comment by chenjiahan** [comment]
已在 3.0.3 版本修复
