### ISSUE TITLE
下拉刷新组件设置宽度100%，然后子元素设置百分比宽度就无效

### ISSUE THREAD

**Issue by Lex1022** [youzan/vant#7881]
http://vant-contrib.gitee.io/vant-issue-generater
这个链接我填完了给我报错400错误，什么鬼
---

下拉刷新组件设置宽度100%，然后子元素设置百分比宽度就无效，给van-pull-refresh__track这个元素添加百分比宽度就可以

**Comment by Lex1022** [comment]
https://codepen.io/lex1022/pen/bGwxGGm
这是代码地址

**Comment by chenjiahan** [comment]
CSS 里百分比是相对于父元素的，这个现象没问题。

如果你想设置子元素样式，可以设置 `width: 100vw`
