### ISSUE TITLE
[Bug Report] tabs+ animated + input 在ios13.0上不显示光标和全选粘贴Tooltips

### ISSUE THREAD

**Issue by jiayisheji** [youzan/vant#7882]
### 设备 / 浏览器
iPhone7 / ios 13.0

### Vant 版本
2.8.4

### Vue 版本
2.6.11

### 描述问题

在tabs组件里面加上动画切换属性`animated`，会导致input输入框没有光标，也不会显示iPhone的全选粘贴Tooltips，去掉`animated`就正常。

**Comment by chenjiahan** [comment]
animated 会在 Tab 上添加 transform 属性，可能引发了 iOS 系统的渲染 bug。

这个从组件层面没有解决方案喔，如果需要兼容，建议不使用 animated 属性。
