### ISSUE TITLE
Popup 弹出层

### ISSUE THREAD

**Issue by yeguicheng** [youzan/vant#7883]
### 设备 / 浏览器
Chrome

### Vant 版本
2.10.11

### Vue 版本
2.5.2

### 重现链接
<a href="http://yeguicheng.gitee.io/bug-vant" target="_blank">http://yeguicheng.gitee.io/bug-vant</a>

### 描述问题
在使用Popup 弹出层的页面中进行路由缓存，页面内的数据除了"Popup 弹出层组件"的v-model内，都不会改变

**Comment by chenjiahan** [comment]
你预期的行为是什么样的？

复现的源代码能否提供下？
