### ISSUE TITLE
[Bug Report] toast组件打包后警告export 'default' (imported as '_extends') was not found，部署在服务器上报错

### ISSUE THREAD

**Issue by YueCynthia** [youzan/vant#7884]
### 设备 / 浏览器
chorme

### Vant 版本
3.0.3

### Vue 版本
3.0.4

### 重现链接
<a href="http://www.无.com" target="_blank">http://www.无.com</a>

### 描述问题
使用Vue Cli脚手架
安装了vant、babel-plugin-import
按需引入
import { Dialog, Toast } from 'vant'
挂到全局
app.config.globalProperties.$dialog = Dialog
app.config.globalProperties.$toast = Toast
app.use(router).use(Dialog).use(Toast).mount('#app')

并且配置了babel.config.js
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset',
  ],
  plugins: [
    ['import', {
      libraryName: 'vant',
      libraryDirectory: 'es',
      style: true
    }, 'vant']
  ]
}

build之后会出现以下警告
warning in ./node_modules/@vant/use/dist/esm/useRelation/useChildren.js
export 'default' (imported as '_extends') was not found in '@babel/runtime/helpers/esm/extends' (possible exports: )

 warning  in ./node_modules/@vant/use/dist/esm/useRelation/useParent.js
export 'default' (imported as '_objectWithoutPropertiesLoose') was not found in '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose' (possible exports: )

服务器上报错：
Uncaught ReferenceError: exports is not defined
    at eval (extends.js:4)
    at Module../node_modules/@babel/runtime/helpers/esm/extends.js (app.js:1795)
    at __webpack_require__ (app.js:3561)
    at eval (index.js:3)
    at Module../node_modules/vant/es/toast/index.js (app.js:2927)
    at __webpack_require__ (app.js:3561)
    at eval (main.js:7)
    at app.js:3643
    at app.js:3644
    at app.js:3645

**Comment by chenjiahan** [comment]
麻烦提供一个复现问题的仓库

**Comment by YueCynthia** [comment]
> 麻烦提供一个复现问题的仓库

非常感谢能回复我，我弄了个demo，放到github了：https://github.com/YueCynthia/customer-view，yarn install后npm run build-test就会出现那个警告

**Comment by chenjiahan** [comment]
vue-cli 的 test 模式用于 vue-cli-service test:unit，为啥要在 build 的时候使用呢

**Comment by YueCynthia** [comment]
> vue-cli 的 test 模式用于 vue-cli-service test:unit，为啥要在 build 的时候使用呢

我是有三个环境，分别是production, development, test，yarn run build-test是对应的build test环境的包
 "build-test": "vue-cli-service build --mode test" ，是这样写不对吗?

**Comment by John60676** [comment]
这个测试环境是用于跑单元测试的，并不是你所理解的测试环境
参考： https://cli.vuejs.org/zh/guide/mode-and-env.html#%E6%A8%A1%E5%BC%8F

**Comment by YueCynthia** [comment]
非常感谢，问题果然出在这，非常不好意思，怪我还没有太理解这个环境配置，.env.test 文件中NODE_ENV=test，所以"build-test": "vue-cli-service build --mode test"，就走到单元测试去了，然后NODE_ENV=production或者development，就是我理解的测试环境了
