### ISSUE TITLE
[Bug Report] List组件 immediate-check=false失效

### ISSUE THREAD

**Issue by justyeh** [youzan/vant#7885]
### 设备 / 浏览器
所有

### Vant 版本
3.0.3

### Vue 版本
3.0.5

### 重现链接
<a href="https://codesandbox.io/s/affectionate-kirch-z7ceq?file=/src/views/List.vue" target="_blank">https://codesandbox.io/s/affectionate-kirch-z7ceq?file=/src/views/List.vue</a>

### 描述问题
即使immediate-check为false，但是router.push引起的scroll事件会触发van-list的load事件，导致这一机制失效，会造成比较严重的bug

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/7786
