### ISSUE TITLE
[Bug Report] 红米手机微信浏览器中upload无法显示图片

### ISSUE THREAD

**Issue by BullG** [youzan/vant#7886]
### 设备 / 浏览器
红米微信浏览器

### Vant 版本
3.0.2

### Vue 版本
3.0.5

### 重现链接
<a href="https://github.com/youzan/vant/issues?page=2&q=upload" target="_blank">https://github.com/youzan/vant/issues?page=2&q=upload</a>

### 描述问题
红米手机上传图片无法显示，似乎没有获取到文件。
机型：redmi 8A   
Android   9

**Comment by chenjiahan** [comment]
麻烦提供复现问题的 codesandbox 链接

https://codesandbox.io/s/m5v3f

**Comment by BullG** [comment]
vant@3.0.2版本，image组件，该台红米手机图片也不能显示。切换到3.0.3版本可以了

**Comment by chenjiahan** [comment]
升级版本可以解决就行👌
