### ISSUE TITLE
[Bug Report] radio组件值为boolean时，必填验证无法通过

### ISSUE THREAD

**Issue by xyj040303** [youzan/vant#7887]
设备 / 浏览器
chrome 87

Vant 版本
2.10.11

Vue 版本
2.6.10

重现链接
https://codesandbox.io/s/vant-issue-moban-forked-w8774?file=/src/App.vue

描述问题
选中radio值为false的选项时，表单必填校验无法正常通过。

**Comment by chenjiahan** [comment]
表单项的值为 false 时，是会被视为校验不通过的喔，建议把 name 改成字符串类型，可以规避这个问题

**Comment by mogody** [comment]
值为int类型的话，这个必填校验也是无法通过的

**Comment by mogody** [comment]
checkbox 的值为int类型的话，这个必填校验也是无法通过的
