### ISSUE TITLE
[Feature Request] swipe组件是否可以将滑块的宽度和动画的距离分离

### ISSUE THREAD

**Issue by sxy1992** [youzan/vant#7888]
### 这个功能解决了什么问题
当我开发业务时，业务需要 滑块的滑动距离与滑块的宽度不一致，现在是直接取滑块的宽度。导致最后一个滑块只能紧贴右侧边沿。无法居中。

### 描述您想要的解决方案
在swipe中加一个选填的滑动距离的prop，若存在取对应值，若不存在取滑块宽度。

### 建议的API是什么样的
export default createComponent({
  props: {
    width: [Number, String],
    slideWidth: [Number, String],
  }
  computed: {
      trackSize() {
        return this.count * (this.slideWidth || this.size);
    },
  }
})

**Comment by sxy1992** [comment]
这个也应该是常见的效果图，

**Comment by chenjiahan** [comment]
暂无计划支持呢，Vant 中的 Swipe 组件是比较轻量的，因此功能也比较基础。如果需要更复杂的轮播效果，推荐使用社区里一些优质的轮播库，比如 vue-awesome-swiper。

https://github.com/surmon-china/vue-awesome-swiper
