### ISSUE TITLE
[Bug Report] Uploader组件在三星机型after-read回调失效

### ISSUE THREAD

**Issue by ChhXin** [youzan/vant#7889]
### 设备 / 浏览器
android 11

### Vant 版本
2.11.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-3jqk3?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-3jqk3?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
ios，华为小米常见机型可以，试了原生的<input type="file" @change="change" /> 也是可以获取到文件的，使用uploader组件after-read回调没有执行，求解答

**Comment by chenjiahan** [comment]
控制台是否有报错呢？

可以把 result-type 设置成 file 试下
