### ISSUE TITLE
collapse折叠面板不设置accordion时报错Error in render: "TypeError: activeNames.some is not a function"

### ISSUE THREAD

**Issue by junk123321** [youzan/vant#789]
activeNames.some 是啥功能
版本是1.0.3

**Comment by cookfront** [comment]
没复现这个报错，能否提供一下代码或者在 [https://jsfiddle.net/dfarLdko/1/](https://jsfiddle.net/dfarLdko/1/)提供一个demo

**Comment by zerolidao** [comment]
van-collapse 的属性“accordion”值为false就会报错：value.some is not a function";
值为true正常；
版本：2.0.9
