### ISSUE TITLE
[Feature Request] van-calendar 自定义文案显示，不可以重新渲染

### ISSUE THREAD

**Issue by huchanghao** [youzan/vant#7890]
### 这个功能解决了什么问题
使用日历实现房间预约功能，通过文案显示预约和不可预约，但是当房间选择变化时候，日历不能再次渲染文案信息

### 描述您想要的解决方案
日历可以手动渲染日历，或者每次打开是否从新渲染参数

### 建议的API是什么样的
最好是参数形式，是否打开重新渲染日历

**Comment by chenjiahan** [comment]
麻烦提供复现问题的 codesandbox 链接

https://codesandbox.io/s/m5v3f
