### ISSUE TITLE
[Bug Report] 动态添加的 Checkbox 组件，必填验证无法通过

### ISSUE THREAD

**Issue by mogody** [youzan/vant#7891]
### 设备 / 浏览器
全部

### Vant 版本
2.12.3

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-jiwmq?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-jiwmq?file=/src/App.vue</a>

### 描述问题
如题，通过后端返回的变量，动态更改组件的显示之后，checkbox的必填校验永远无法通过
![image](https://user-images.githubusercontent.com/10496478/104327133-69ac9100-5525-11eb-91ea-fb68575c89b2.png)

**Comment by mogody** [comment]
该重现连接中，如果把 radio 组件去掉，那么就没问题， 非常诡异

**Comment by John60676** [comment]
参考 Vue 文档：“[**用 key 管理可复用的元素**](https://cn.vuejs.org/v2/guide/conditional.html#%E7%94%A8-key-%E7%AE%A1%E7%90%86%E5%8F%AF%E5%A4%8D%E7%94%A8%E7%9A%84%E5%85%83%E7%B4%A0)”

参考：https://codesandbox.io/s/vant-issue-moban-forked-zgose?file=/src/App.vue
