### ISSUE TITLE
[Feature Request] button怎么设置文字大小和颜色

### ISSUE THREAD

**Issue by Wangtao-ETO** [youzan/vant#7892]
### 这个功能解决了什么问题
按钮中间的文字不能设置大小和颜色

### 描述您想要的解决方案
button设置了class
custom-class="btn_text" 

.btn_text{
    font-size: 28rpx;
    font-weight: 500;
    color: red;
}
没有效果，请问怎么设置啊？

### 建议的API是什么样的
text-color:#xxxxx
text-size:xx

**Comment by chenjiahan** [comment]
设置通过 css 覆盖样式即可

```html
<van-button class="my-button" />
```

```css
.my-button {
  font-size: 20px;
}
```
