### ISSUE TITLE
[Feature Request] 希望在编译前有增加js文件的入口，可以使用公共js函数等功能

### ISSUE THREAD

**Issue by zghuan** [youzan/vant#7895]
### 这个功能解决了什么问题
我想组件库里利用js打印组件库版本，用于判断一些业务情况，但看了脚手架只能写纯vue，并没有js的文件

### 描述您想要的解决方案
在src里可以定义一个index.js文件，会在编译时加载里面的逻辑

### 建议的API是什么样的
可以在组件库按需引用，组件库的公共js工具函数

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议在组件内部自行 import。
