### ISSUE TITLE
[Feature Request] Cell 组件希望 is-link 和 clickable 可以共存

### ISSUE THREAD

**Issue by bolechen** [youzan/vant#7896]
某些特定场景下，希望模拟原生 app 的体验，不希望出现点击反馈。is-link = true 的情况下 点击反馈 clickable 好像关不掉。

目前的做法如下，略显麻烦：

```html
<van-cell :to='xxx'>
 <template #right-icon><van-icon class='van-cell__right-icon' name="arrow" /></template>
</van-cell>
```

![image](https://user-images.githubusercontent.com/195015/104530978-21d25a80-5648-11eb-9b25-c34a875d4332.png)

期望改成

```html
<van-cell is-link :to='xxx' :clickable="false" />
```

希望官方能改进一下～ 感谢！

**Comment by chenjiahan** [comment]
下个版本优化👌

**Comment by bolechen** [comment]
Field 输入框 也有同样的需求，辛苦了哈～

**Comment by chenjiahan** [comment]
已在 2.12.4 版本支持咯
