### ISSUE TITLE
[Bug Report] Circle组件渐变色不生效

### ISSUE THREAD

**Issue by yfl365** [youzan/vant#7897]
### 设备 / 浏览器
chrome

### Vant 版本
2.11.2及以上

### Vue 版本
2.6.12

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/circle" target="_blank">https://youzan.github.io/vant/#/zh-CN/circle</a>

### 描述问题
像是v2.11.2新增Circle组件的@circle-color变量导致

**Comment by chenjiahan** [comment]
已在 2.12.4 版本修复
