### ISSUE TITLE
van-field v-model="number"的时候可以输入.开头，能不能限制第一位不要输入.

### ISSUE THREAD

**Issue by hasbug** [youzan/vant#7899]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/field" target="_blank">https://youzan.github.io/vant/#/zh-CN/field</a>

### 描述问题
field type=number时可以输入.开头的数字, 目前官网也存在这种问题

**Comment by chenjiahan** [comment]
已在 2.12.4 版本优化
