### ISSUE TITLE
[Feature Request] van-calendar组件区间日期建议添加清除按钮

### ISSUE THREAD

**Issue by iyu98** [youzan/vant#7903]
### 这个功能解决了什么问题
当选择区间日期的时候, 如果要取消日期筛选条件可以清除当前已经选择的日期.

### 描述您想要的解决方案
区间日期添加是否显示清除当前选择日期按钮配置

### 建议的API是什么样的
标签添加 clear-show.
把确认按钮宽度调整, 防止两个按钮, 左侧清除, 右边确定.

**Comment by chenjiahan** [comment]
暂无计划支持呢，你可以通过插槽和 reset 方法来实现

**Comment by iyu98** [comment]
> 暂无计划支持呢，你可以通过插槽和 reset 方法来实现

抱歉, 使用的时候略过了slot方式, 问题已解决, 谢谢.
