### ISSUE TITLE
[Bug Report] window下使用create-vant-cli-app无法生成模板文件, mac os下正常

### ISSUE THREAD

**Issue by YaoXiangMei** [youzan/vant#7904]
**系统**：window 7
**create-vant-cli-app 版本**：1.0.1
**重现步骤**
1.yarn add create-vant-cli-app -g
2.create-vant-cli-app
**测试结果**
没有生成docs、src、vant.config.js、babel.config.js、package.json等目录和文件
**期望结果**
正常生成模板文件

**Comment by chwech** [comment]
我也遇到这个bug，window 10系统，运行```yarn create vant-cli-app```，结果只有：
```
node_modules
  |__.yarn-integrity
yarn.lock
```

**Comment by chenjiahan** [comment]
已发布 create-vant-cli-app 1.0.2 版本，可以重新创建试下
