### ISSUE TITLE
文件上传,开启multiple,大部分手机不支持

### ISSUE THREAD

**Issue by gogopaner** [youzan/vant#7906]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
这个是原生属性，系统不支持也没办法的喔

**Comment by annihilationism** [comment]
我在微信打开无法多张上传，但是在QQ浏览器支持多张
