### ISSUE TITLE
[Feature Request] van-cascader options数据格式

### ISSUE THREAD

**Issue by iyu98** [youzan/vant#7908]
### 这个功能解决了什么问题
用户自定义绑定的 text 和 children 字段，前端做展示的时候，都是根据后端的数据来渲染的，但是后台返回的字段的 key 不一定是 text 可能是 name / label 字段. 如果前端取到数据之后再做处理, 有些麻烦。后端一直使用的是 label 或 name。希望能添加让用户自定义配置。

### 描述您想要的解决方案
在组件添加 prop 属性, 可用于用户自定义options 格式

### 建议的API是什么样的
:prop="{ text: 'name', children: 'child' }"
prop 为对象格式, 可以让用户自己定义用来展示的字段 和 children 的字段

**Comment by chenjiahan** [comment]
后续会支持，类似 Picker 的 `columns-field-names` 属性

**Comment by chenjiahan** [comment]
已在 2.12.4 版本支持 `field-names` 属性
