### ISSUE TITLE
Circle 组件能否对中间内容提供slot支持

### ISSUE THREAD

**Issue by yajore** [youzan/vant#791]
**What is the current behavior?**
如题，目前只支持text
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by cookfront** [comment]
中间内容已经提供了slot支持，文档中应该少写了，文档我们补充一下。有一个默认的slot就是自定义中间内容的。
