### ISSUE TITLE
van-picker 颜色不一致

### ISSUE THREAD

**Issue by Peng-Kun-Dai** [youzan/vant#7911]
通过主题定制的方式修改picker-background-color的属性值之后，选择器的背景颜色会发生改变，但是当 visible-item-count的值大于1时，中间栏的上下会出现白色区域，似乎这部分不受picker-background-color属性的控制。
![1610701496](https://user-images.githubusercontent.com/41935435/104704982-529fb600-5754-11eb-86ef-4315252a876b.jpeg)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by zhangmingwalker1633** [comment]
你好，这个问题解决了吗
