### ISSUE TITLE
[Bug Report] 克隆的git源码编译后运行报错

### ISSUE THREAD

**Issue by kooriookami** [youzan/vant#7912]
### 设备 / 浏览器
chrome87

### Vant 版本
3.0.3

### Vue 版本
3.0.5

### 重现链接
暂无

### 描述问题
如下步骤，分支为`dev`
1. `git clone`
2. `yarn install`
3. `npm run dev`
4. 在浏览器访问地址报错，看起来是模块引用的错误
![image](https://user-images.githubusercontent.com/38392315/104707003-cb077680-5756-11eb-8eaa-5fbbb6555a81.png)

**Comment by chenjiahan** [comment]
没复现唉，重新 yarn 试试？

**Comment by kooriookami** [comment]
我换成下载zip包运行，也还是一样的错误。可以看到运行是成功的，为什么没有复现就不知道了。。
![image](https://user-images.githubusercontent.com/38392315/104873291-2de15380-598b-11eb-8dc0-5e63c1d4459e.png)
![image](https://user-images.githubusercontent.com/38392315/104873487-96303500-598b-11eb-9013-a27f450b72a1.png)

**Comment by chenjiahan** [comment]
已降级 webpack-dev-server 版本，可以再试下
