### ISSUE TITLE
vant文档怎么404了？

### ISSUE THREAD

**Issue by dream-one** [youzan/vant#7913]
https://vant-contrib.gitee.io/vant/#/zh-CN/

**Comment by John60676** [comment]
可以先用 github 版本：https://youzan.github.io/vant/#/zh-CN/

**Comment by dream-one** [comment]
> 可以先用 github 版本：https://youzan.github.io/vant/#/zh-CN/

仍然打不开

**Comment by chenjiahan** [comment]
已恢复
