### ISSUE TITLE
文档一直404中，有点久了

### ISSUE THREAD

**Issue by lichunze** [youzan/vant#7914]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---
![image](https://user-images.githubusercontent.com/24243394/104731339-85f33c80-5776-11eb-99d6-c97a13248472.png)

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by John60676** [comment]
可以先用 github 版本：https://youzan.github.io/vant/#/zh-CN/

**Comment by chenjiahan** [comment]
已恢复
