### ISSUE TITLE
有关vant  toast  bug

### ISSUE THREAD

**Issue by mhxy13867806343** [youzan/vant#7915]
设备 / 浏览器
安卓（app软件上面）

Vant 版本
2.11.2

Vue 版本
2.6.11

基本代码如下
Toast.loading({
  message: '',
  forbidClick: true,
  loadingType: 'spinner',
duration:0
});

描述问题
你好，在使用的toast组件时，时，当请求的接口很慢时（比如一个接口请求下来的要5s后）toast会在3s后，就隐藏，中间会出现2s的空白时间，然后才会出现数据，

**Comment by John60676** [comment]
我没能复现你描述的现象，提供一份重现代码？

**Comment by mhxy13867806343** [comment]
没有办法给，项目在内网里面，不好意思

**Comment by John60676** [comment]
不要你的全部代码，你提供一个最小的重现示例就可以了 https://codesandbox.io/s/m5v3f

**Comment by chenjiahan** [comment]
未复现此问题，建议看下 duration 是否正确设置了
