### ISSUE TITLE
[Bug Report] pagination 使用插槽自定义分页按钮无效

### ISSUE THREAD

**Issue by iyu98** [youzan/vant#7917]
### 设备 / 浏览器
mac OS / chrome

### Vant 版本
2.12.1

### Vue 版本
2.6.1

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-6quec?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-6quec?file=/src/App.vue</a>

### 描述问题
分页组件使用slot设置自定义分页按钮的时候不生效, 没有变化, 显示的还是默认的按钮
![image](https://user-images.githubusercontent.com/52142803/104795088-ba9edc80-57e6-11eb-8106-a736ad63e971.png)

**Comment by chenjiahan** [comment]
注意 vant 版本需要在 2.10.9 版本以上

**Comment by iyu98** [comment]
可是我的vant 版本是 2.12.1版本的啊

**Comment by chenjiahan** [comment]
复现链接里是正常的呢，没有问题

**Comment by huangAG** [comment]
> 复现链接里是正常的呢，没有问题

我也遇到了分页组件使用slot设置自定义分页按钮的时候不生效, 没有变化, 显示的还是默认的按钮，代码跟题主的一样

**Comment by huangAG** [comment]
> 可是我的vant 版本是 2.12.1版本的啊

你好，你的问题解决了吗？怎么解决的

**Comment by iyu98** [comment]
> > 可是我的vant 版本是 2.12.1版本的啊
> 
> 你好，你的问题解决了吗？怎么解决的

我更换了其他方式, 没有再使用 按钮分页组件.

**Comment by huangAG** [comment]
> 注意 vant 版本需要在 2.10.9 版   
2.12.4版也是无效的
