### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by HuiGan-M** [youzan/vant#7918]
现在我想做个和安卓一样,每个tab对应的不同的内容,而内容是可以左右滑动,滑动时是可以切换选中的tab的.我是用了tab+swiper结合实现了,但是现在遇到一个问题就是,内容(swiper区块)的高度不是独立的 一个,导致一个区块没有内容但是高度被有内容的区块撑起来了

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
