### ISSUE TITLE
[Feature Request] 请教下问题

### ISSUE THREAD

**Issue by HuiGan-M** [youzan/vant#7919]
### 这个功能解决了什么问题
现在我想做个和安卓一样,每个tab对应的不同的内容,而内容是可以左右滑动,而且有阀值得滑动,滑动时是可以切换选中的tab的

### 描述您想要的解决方案
我是用了tab swiper结合实现了,但是现在遇到一个问题就是,内容(swiper区块)的高度不是独立的,导致一个区块没有内容但是高度被有内容的区块撑起来了

### 建议的API是什么样的
我想每个swipe的区块的高度都是独立的

**Comment by chenjiahan** [comment]
Swipe 区块的高度没法独立呢，你可以考虑用局部滚动试试
