### ISSUE TITLE
vant 的标签 <van-button/> 的click属性不好用

### ISSUE THREAD

**Issue by yangyuling520** [youzan/vant#792]
尴尬：第一次用
html代码：`<van-button size="small" click="doSave">小型按钮</van-button>`
或：
`<van-button size="small" @click="doSave">小型按钮</van-button>`
js代码：
export default {
methods: {
doSave:function(){
console.log("1111111111111111`");
},
}
}
点击事件进不去，log打不出来

**Comment by cookfront** [comment]
请将详细问题描述在issue内容中，不要全部写在标题中。

**Comment by yangyuling520** [comment]
尴尬：第一次用
html代码：
 <van-button size="small" click="doSave">小型按钮</van-button>
或：
<van-button size="small" @click="doSave">小型按钮</van-button>
js代码：
        methods: {
            doSave:function(){
                console.log("1111111111111111`");
            },
}
点击事件进不去，log打不出来

**Comment by cookfront** [comment]
请你检查下代码是不是正确的，`<van-button size="small" @click="doSave">小型按钮</van-button>` 这种写法是对的

**Comment by yangyuling520** [comment]
`<van-button size="small" click="doSave">小型按钮</van-button>`这种写法页不好用

**Comment by cookfront** [comment]
这种写法是不对的，麻烦看下 Vue 事件相关的文档哦。。
