### ISSUE TITLE
[Bug Report] 把van-uploader的v-model拆为:value @input后，图片数据无法回显预览了

### ISSUE THREAD

**Issue by tangjian1891** [youzan/vant#7920]
### 设备 / 浏览器
PC端chrome78

### Vant 版本
2.11.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-g3i51?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-g3i51?file=/src/App.vue</a>

### 描述问题
把van-uploader的v-model拆为:value @input后，图片数据无法回显预览了。 因为页面要保证刷新图片的url仍然存在，所以数据通过vuex持久化了。 拆过vant别的组件的v-model为:value @input都是没问题的，现在就上传组件卡住了

**Comment by chenjiahan** [comment]
不是 :value，是 :file-list

**Comment by tangjian1891** [comment]
> 不是 :value，是 :file-list

已解决。感谢周末答疑！
