### ISSUE TITLE
关于 vant 样式适配

### ISSUE THREAD

**Issue by cocody** [youzan/vant#793]
**What is the current behavior?**
现在很多UI框架都是使用通用样式单位，即 iPhone 6 设计稿像素（width：750px），写在CSS上就是逻辑像素（width：375px）。但现在有很多是采用在CSS上写设计稿像素（width：750px），然后再使用 viewport 兼容或者 postcss 来编译出逻辑像素，这时候再引入第三方插件就会导致样式偏小问题。

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**
期望做一个 FullPixel 版本

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
All Versions

**Comment by cookfront** [comment]
是指类似 rem 自适应么？

**Comment by cocody** [comment]
可以有一个全局配置，类似于
vant.init({
  devicePixelRatio: 2 // 默认为1
})

然后样式整体放大两倍
这样在那些 FullPixel 的网页里引用 vant 就不会遇到需要重新修改样式问题。

**Comment by cookfront** [comment]
那你这个就是类似 rem 适配了，这个我们还在调研中，如果实现没问题我们就会支持。

**Comment by ExploreDuo** [comment]
是的，在项目中使用的是750*1334的单位，但是使用第三方库中用的都是375*667，目前有什么兼容方案吗。

**Comment by alianggitok** [comment]
这个问题为什么关了？是解决了吗？
