### ISSUE TITLE
[Bug Report] Vant3缺少两个Vant2中的组件

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant#7930]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.3

### Vue 版本
3.0.5

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/submit-bar" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/submit-bar</a>

### 描述问题
我的项目原来是VUE2 VANT2，近期想升级为VUE3 VANT3，却发现VANT3缺少了两个项目中常用到的组件：GoodsActions与Sku商品规格。请问这两个组件何时能补充到VANT3上？

**Comment by chenjiahan** [comment]
GoodsActions 重命名为 ActionBar 了，请参考迁移指南。

Sku 后续会拆分为单独的 npm 包并提供，时间待定。

**Comment by sdlddr** [comment]
> GoodsActions 重命名为 ActionBar 了，请参考迁移指南。
> 
> Sku 后续会拆分为单独的 npm 包并提供，时间待定。
能否在过年之前发布Sku组件？

**Comment by chenjiahan** [comment]
不确定喔

**Comment by lixiaofa** [comment]
> ### 设备 / 浏览器
> chrome
> 
> ### Vant 版本
> 3.0.3
> 
> ### Vue 版本
> 3.0.5
> 
> ### 重现链接
> https://vant-contrib.gitee.io/vant/#/zh-CN/submit-bar
> 
> ### 描述问题
> 我的项目原来是VUE2 VANT2，近期想升级为VUE3 VANT3，却发现VANT3缺少了两个项目中常用到的组件：GoodsActions与Sku商品规格。请问这两个组件何时能补充到VANT3上？

我迁移了vant2.x的sku
https://www.npmjs.com/package/vant-sku?activeTab=readme
