### ISSUE TITLE
[Bug Report] Tabbar标签栏不能自动更改标签选中状态

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant#7931]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.3

### Vue 版本
3.0.5

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/v3/#/zh-CN/tabbar" target="_blank">https://vant-contrib.gitee.io/vant/v3/#/zh-CN/tabbar</a>

### 描述问题
最近在项目开发中发现：通过程序对Tabbar标签栏的v-model参数的动态修改，不能自动更改标签选中状态。请问这个BUG能否修正？

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by sdlddr** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

在线demo中，使用简单模式是正常的，但我在项目里，v-model是来自于vuex中的getters的一个自定义属性值，该属性值通过mutations进行变更操作，且是发生在路由守卫beforeEach内部的mutations操作。

**Comment by chenjiahan** [comment]
没链接我们也没法帮你排查喔。

你可以把 v-model 拆分为 :value 属性和 @input 事件试下。

**Comment by sdlddr** [comment]
你们给的链接无法使用路由和VUEX，只能在你的本机上做测试

**Comment by chenjiahan** [comment]
codesandbox 可以使用的喔，把 vue-router 和 vuex 加入到左侧栏的依赖项里即可

**Comment by chenxi2008** [comment]
:route="true"  这个属性去掉貌似就好了
