### ISSUE TITLE
【BUG】touch-emulator插件 跟 jodit富文本编辑器冲突，只要一引入touch-emulator，jodit编辑器里面的文本内容就无法选中（无法进行框选）

### ISSUE THREAD

**Issue by tanker5258** [youzan/vant#7934]
【BUG】touch-emulator插件 跟 jodit富文本编辑器冲突
  只要一引入touch-emulator
jodit编辑器里面的文本内容就无法选中（无法进行框选）

**Comment by tanker5258** [comment]
以下是我自己的解决办法
      这个创建拖放记录表的函数，如果里面能够做个过滤，只针对 某个Target作监测就可以了。
     因此，我创建了一个  if判断，如果 目前拖放的 Target目标的id， 包含特定的字符串（"自己定一个字符串"），那么就把这个目标的所有拖放事件放入拖放记录池。其余对象说明跟 拖放事件无关，就不加监测，过滤掉。
     下面就是我修改的   import '@vant/touch-emulator';  （index.js）


function createTouchList(mouseEv) {
  //创建一条if过滤，id包含自定义字符串的，才加入拖放列表池，否则忽略掉。
  if (eventTarget.id.indexOf("dpk_touch") != -1) {
    //console.log(eventTarget);
    var touchList = TouchList();
    touchList.push(new Touch(eventTarget, 1, mouseEv, 0, 0));
    return touchList;
  }
}

**Comment by chenjiahan** [comment]
暂无计划支持 jodit 呢
