### ISSUE TITLE
[Bug Report] 使用图片懒加载功能，会导致错误占位图片失效

### ISSUE THREAD

**Issue by Lex1022** [youzan/vant#7936]
### 设备 / 浏览器
mac chrome桌面版，版本87.0.4280.141

### Vant 版本
3.0.4

### Vue 版本
2.6.1

### 重现链接
<a href="https://codepen.io/lex1022/pen/eYdxmvY" target="_blank">https://codepen.io/lex1022/pen/eYdxmvY</a>

### 描述问题
使用图片懒加载功能，会导致错误占位图片失效

**Comment by JensenWei** [comment]
因为官方的错误图的路径变了，旧版本的全都会失效，除非更新到最新版

**Comment by Lex1022** [comment]
好的，谢谢了

JensenWei <notifications@github.com> 于2021年1月18日周一 上午10:00写道：
