### ISSUE TITLE
[Bug Report] jsx按需引入组件，样式没有自动引入

### ISSUE THREAD

**Issue by wtto00** [youzan/vant#7937]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.4

### Vue 版本
3.0.5

### 重现链接
<a href="https://codesandbox.io/s/awesome-albattani-7ybtd?file=/src/App.jsx" target="_blank">https://codesandbox.io/s/awesome-albattani-7ybtd?file=/src/App.jsx</a>

### 描述问题
按照官网上的文档，自动按需引入组件：
https://youzan.github.io/vant/v3/#/zh-CN/quickstart#fang-shi-yi.-zi-dong-an-xu-yin-ru-zu-jian-tui-jian

使用jsx，组件的样式没有自动引入进来。可查看复现链接。  
或者是我引入的方式不对，请教下怎么引入的？  
我的想法是不在`main.js`中按需引入，只在组件中引入所需要的组件！

**Comment by wtto00** [comment]
经过测试，即使在`main.js`中引入组件，样式依然不能自动按需引入进来
https://codesandbox.io/s/charming-firefly-t94fh?file=/src/main.js

只有引入全部css: `import "vant/lib/index.css";`才有效

**Comment by chenjiahan** [comment]
babel 插件配置正确吗？可以提供一个复现仓库看下

**Comment by wtto00** [comment]
@chenjiahan 上面都附有复现链接，你看看🌺🌺

**Comment by wtto00** [comment]
@chenjiahan 呃，抱歉了，好像今天又正常了。demo没复现出来，我自己的项目昨天死活出不来样式，今天也莫名其妙的好了。

**Comment by wtto00** [comment]
因为我在 `vue.config.js` 中配置了
```js
{
  css:{
    requireModuleExtension: false,
  }
}
```
这样导致 `vant` 的组件样式也被当成  `css-moudle`，从而样式的className都加上了hash唯一标识，而组件中引入的样式还是原始className，样式类名不匹配，导致组件样式不生效。

注释掉 `requireModuleExtension: false,` 即可解决。
不过自己的组件引入`css-moudle` 文件名就需要加上`moudle`，例如： `[name].module.less`

**Comment by bgyhnddr** [comment]
我也一样。。。出不来。。。请问楼主解决了吗
