### ISSUE TITLE
area 控件设置value会出现问题，我设置了350104

### ISSUE THREAD

**Issue by linwenfeng122** [youzan/vant#794]
![qq 20180328201949](https://user-images.githubusercontent.com/19618653/38028390-5f69992a-32c5-11e8-9721-ef2f90fcf951.png)
 
结果是这样的
   
![city](https://user-images.githubusercontent.com/19618653/38028439-831a7c36-32c5-11e8-8267-e18b04212203.png)

**Comment by cookfront** [comment]
能描述下具体出现啥问题么

**Comment by linwenfeng122** [comment]
@cookfront  首先这个省份就不对了，应该是福建省，其次我所指的地区是仓山区

**Comment by cookfront** [comment]
你省市县数据用的是哪里的数据啊？vant自带的么

**Comment by linwenfeng122** [comment]
@cookfront 服务器带的，我测试过正常滚动的时候，所对应省市县是没有问题的

**Comment by linwenfeng122** [comment]
@cookfront 找到原因了跟数据库返回的是繁体有关

**Comment by linwenfeng122** [comment]
@cookfront 我现在才知道原因，因为你的value不是动态的值可能导致了这种原因，但是我的城市列表的数据却是动态生成了的，这过程会导致这样的结果，你value的值已经传递了，但是我的城市的列表还没有传递过去。
