### ISSUE TITLE
[Feature Request] 日历组件通过函数方式选择日期

### ISSUE THREAD

**Issue by toolse** [youzan/vant#7943]
### 这个功能解决了什么问题
实现了基础的日历签到功能

### 描述您想要的解决方案
在日历只读的情况下，依然可以指定的去选择多个或单个日期

### 建议的API是什么样的
通过组件底部按钮以函数形式去选择多个或单个日期存储到一个响应式变量中
如1：变量中没有日期，则没有日期被选择
如2：变量中有日期，则日期被自动选择

**Comment by chenjiahan** [comment]
已在 2.12.5 版本支持，可以在调用 reset 方法时传入指定日期

**Comment by toolse** [comment]
最终问题：
1.怎么让日历初始化之后默认不会选中任何日期，点击按钮触发函数以后再选中日期
2.是否可以增加一个手动控制日历按钮的禁用状态参数
