### ISSUE TITLE
[Bug Report] swipe-threshold失效

### ISSUE THREAD

**Issue by sxpdy8571** [youzan/vant#7945]
### 设备 / 浏览器
ios/safari

### Vant 版本
2.10.12

### Vue 版本
2.6.10

### 重现链接
<a href="https://jsbin.com/?html,output" target="_blank">https://jsbin.com/?html,output</a>

### 描述问题
swipe-threshold设置超过 4 个启用滚动失效

**Comment by chenjiahan** [comment]
复现链接为空，请提供有效的复现链接。
