### ISSUE TITLE
[Feature Request] ImagePreview 在缩放操作后使用 swipeTo 方法，上一页是否应该重置 style？

### ISSUE THREAD

**Issue by joo1es** [youzan/vant#7946]
### 这个功能解决了什么问题
更符合直觉，目前每次 swipeTo 切回去的时候，都会保持原来的缩放状态

### 描述您想要的解决方案
新建一个 Prop 或者 Options 配置项 ，可选使用 swipeTo 方法后，重置 style

### 建议的API是什么样的
Options 里添加一个配置项

**Comment by joo1es** [comment]
另外，目前通过点击图片的方式关闭 ImagePreview 组件时，会有约 300ms 的延迟，不知是 bug 还是 feature？

**Comment by chenjiahan** [comment]
后续会考虑支持

> 会有约 300ms 的延迟

是 feature，为了判断是否为双击缩放操作

**Comment by chenjiahan** [comment]
已在 2.12.5 版本调整，现在会自动重置缩放状态
