### ISSUE TITLE
[Feature Request] 请问Field是否支持嵌套

### ISSUE THREAD

**Issue by zlyyyy** [youzan/vant#7947]
### 这个功能解决了什么问题
物流场景详细地址时用到

### 描述您想要的解决方案
目前我用的时两个Field分开的，导致校验错误也会分开，是否支持Field分组，错误统一
![image](https://user-images.githubusercontent.com/22760932/104998448-3a86aa00-5a66-11eb-89ca-2f1770993aeb.png)

### 建议的API是什么样的
物流场景详细地址时用到

**Comment by chenjiahan** [comment]
不支持嵌套喔，这种场景可以考虑用插槽试试

**Comment by zlyyyy** [comment]
好的。用两个field搭配rule解决了
