### ISSUE TITLE
[Bug Report] Tab标签页组件有bug

### ISSUE THREAD

**Issue by MooreLxr** [youzan/vant#7950]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.4

### Vue 版本
3.0.5

### 重现链接
<a href="https://youzan.github.io/vant/v3/#/zh-CN/tab" target="_blank">https://youzan.github.io/vant/v3/#/zh-CN/tab</a>

### 描述问题
初始化时van-tabs__line位置计算错误

**Comment by chenjiahan** [comment]
麻烦提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by MooreLxr** [comment]
https://codesandbox.io/s/m5v3f&nbsp; 这个链接按官网上的写法会报错，我直接提供截图可以吗？








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neverland"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 晚上7:13
收件人: "youzan/vant"<vant@noreply.github.com&gt;; 
抄送: "连雪如"<1052777399@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant] [Bug Report] Tab标签页组件有bug (#7950)





 
麻烦提供 codesandbox 复现链接
 
https://codesandbox.io/s/m5v3f

**Comment by chenjiahan** [comment]
截图没法排查喔
