### ISSUE TITLE
[Bug Report] 使用van-grid出现问题

### ISSUE THREAD

**Issue by JIE-JIE-JIANG** [youzan/vant#7953]
### 设备 / 浏览器
Iphone

### Vant 版本
2.10.12

### Vue 版本
2.6.12

### 重现链接
<a href="https://gitee.com/riocento/dashboard/projects/riocento/zhitui-cloud-mobile/" target="_blank">https://gitee.com/riocento/dashboard/projects/riocento/zhitui-cloud-mobile/</a>

### 描述问题
使用van-grid制作微信内置网页，安卓手机端和微信开发工具显示正常，但是苹果手机打开就会被拉长,如图所示
![image](https://user-images.githubusercontent.com/51015520/105152673-70995c00-5b42-11eb-9b67-f86d421f1b0e.png)
代码如下
![image](https://user-images.githubusercontent.com/51015520/105152710-7db64b00-5b42-11eb-9717-5ef269b77f62.png)
这是正常显示的
![image](https://user-images.githubusercontent.com/51015520/105152732-873fb300-5b42-11eb-906a-4bc1fc37d109.png)

**Comment by chenjiahan** [comment]
链接无法打开，请提供有效的 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
