### ISSUE TITLE
[Bug Report] swipe 设置圆角在切换瞬间会变成直角（手机端）

### ISSUE THREAD

**Issue by z138141855** [youzan/vant#7955]
### 设备 / 浏览器
设备

### Vant 版本
2.12.4

### Vue 版本
2.6.11

### 重现链接
<a href="http://cx.qunje.com:9999/login?losetoken=true" target="_blank">http://cx.qunje.com:9999/login?losetoken=true</a>

### 描述问题
在手机端，自动轮播时,或手动滑动松开时会有一瞬间四个角变成直角，可以在微信网页测试

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5290
