### ISSUE TITLE
List列表,触发load事件后,自动回弹到顶部

### ISSUE THREAD

**Issue by atom-7** [youzan/vant#7956]
![image](https://user-images.githubusercontent.com/53164898/105274045-5fe6f580-5bd7-11eb-8e8a-70392cc26c99.png)
触底事件触发后,自动置顶,跟数据无关,只要触发load事件,自动回弹到顶部,

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by xu-Aurora** [comment]
我也碰到这个问题了，在android会出现，在ios是正常的。请问解决了嘛？

**Comment by dadaguai-git** [comment]
> 我也碰到这个问题了，在android会出现，在ios是正常的。请问解决了嘛？

哈喽 请问你解决了么，我们也遇到这种问题了
