### ISSUE TITLE
[Feature Request] Cascader绑定的value重置后视图中的tab没有重置

### ISSUE THREAD

**Issue by zlyyyy** [youzan/vant#7959]
### 这个功能解决了什么问题
Cascader绑定的value重置后视图中的tab没有重置
![image](https://user-images.githubusercontent.com/22760932/105319444-d7c91600-5bff-11eb-9229-237c9f44a170.png)

### 描述您想要的解决方案
Cascader绑定的value重置后视图中的tab没有重置

### 建议的API是什么样的
Cascader绑定的value重置后视图中的tab重置

**Comment by zlyyyy** [comment]
搭配popup的话不加v-if不会重置，加了才可以

**Comment by Mrchangchang** [comment]
我定位了一下，是因为级联组件被popup组件包裹，当改变级联组件绑定的值时，级联组件的状态为display:none；导致级联组件里面swpe和setline样式计算不对

**Comment by zlyyyy** [comment]
@Mrchangchang 我现在用v-if让他整个重新渲染解决了问题，但是不太好感觉，有没有refs的方式可以单独重新渲染tab的呢

**Comment by Mrchangchang** [comment]
没有找到，搭配popup的时候你给Cascader一个key，每次给Cascader的value赋值的时候，就把key自增1，跟v-if的原理一样，

**Comment by zlyyyy** [comment]
@Mrchangchang 感谢解答，现在也只能先这么处理了。后续如果可以像vue一样有单独的$forceUpdate()那就方便多了

**Comment by Mrchangchang** [comment]
看了一下，应该要在popup组件里面使用useChildren，让子组件处理onShow事件，这样改动太多，应该只有作者来改了

**Comment by zlyyyy** [comment]
此处应手动求助作者 @chenjiahan

**Comment by chenjiahan** [comment]
子组件比较难感知到父组件的 display 值变化，目前有几种处理方法：

1. 通过 v-if 或 key 来避免
2. 直接调用组件的 vm.$forceUpdate()，应该是有效的
3. 在组件内部通过 IntersectionObserver 来监听显示状态变化，IntersectionObserver 有兼容性问题，所以暂时不考虑
4. 子组件监听 Popup 的切换事件，这种方式耦合比较严重，而且也不能解决非 Popup 导致的问题，不考虑
