### ISSUE TITLE
[Bug Report] @vant/cli升级导致项目无法正常启动

### ISSUE THREAD

**Issue by Mrchangchang** [youzan/vant#7960]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.4

### Vue 版本
3.0.5

### 重现链接
<a href="https://img04.sogoucdn.com/app/a/100520146/83592559f21262b49f0741c84886773c" target="_blank">https://img04.sogoucdn.com/app/a/100520146/83592559f21262b49f0741c84886773c</a>

### 描述问题
项目源码依赖重新安装后，运行会报错，经过测试，原因@vant/cli版本由3.3.0升级3.4.0导致，切换至原版本项目正常启动

**Comment by chenjiahan** [comment]
跟这个 issue 应该是同个问题：https://github.com/youzan/vant/issues/7912

先 close 了哈，在上个 issue 中统一跟进
