### ISSUE TITLE
[Bug Report] 有多个Dialog，且配置的 allowHtml 不同时，message没有渲染出来

### ISSUE THREAD

**Issue by ssheryf** [youzan/vant#7963]
### 设备 / 浏览器
Chrome

### Vant 版本
3.0.4

### Vue 版本
3.0.5

### 重现链接
<a href="https://codepen.io/xxtxxf/pen/NWRVWdP" target="_blank">https://codepen.io/xxtxxf/pen/NWRVWdP</a>

### 描述问题
在相同 allowHtml 配置的 Dialog 之间切换点击，message 显示正常。<br />
不同 allowHtml 之间切换，message 没有显示。

**Comment by chenjiahan** [comment]
目测是 Vue 3 的问题，下个版本会兼容下

**Comment by chenjiahan** [comment]
已在 3.0.5 版本兼容
