### ISSUE TITLE
[Bug Report] Tab滑动切换不触发before-change

### ISSUE THREAD

**Issue by PingTouG** [youzan/vant#7964]
### 设备 / 浏览器
*

### Vant 版本
3.0.4

### Vue 版本
3.0.4

### 重现链接
<a href="https://github.com/PingTouG/vant-tab/tree/main" target="_blank">https://github.com/PingTouG/vant-tab/tree/main</a>

### 描述问题
before-change是切换标签前的回调函数，那滑动切换应该也触发。现在是只有点击切换的时候触发。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6895
