### ISSUE TITLE
关于文档中 Badge 与 Cell 的引入问题

### ISSUE THREAD

**Issue by cocody** [youzan/vant#797]
**What is the current behavior?**
问题1：
在文档中，关于 Badge 的引入是这样定义的：
`import { Badge } from 'vant';
Vue.use(Badge);`

而关于 Cell 的引入是这样定义的：
`import { Cell, CellGroup } from 'vant';
Vue.use(Cell).use(CellGroup);`

但问题是，看源码 ~packages/*
Badge 与 Cell 一样都有各自对应的 Badge-Group Cell-Group

那为什么 Badge 不需要这样引入呢？
``import { Badge, BadgeGroup } from 'vant';`

问题2：
在 ~packages/index.js

`  Tabs,
  Tag,
  Toast,
  TreeSelect,
  Uploader
];

const install = Vue => {
  components.forEach(Component => {
    Vue.use(Component);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}`

是这样注册组件的，但为什么在HTML中却要写上 van- 前缀呢？

看源码的一点疑惑，求解~~

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by cookfront** [comment]
1. 文档漏写了，近期会改掉
2. 加前缀是为了统一vant组件使用方式

**Comment by cocody** [comment]
问题2我可能表达得不太清楚，我是想问：
既然注册是 Tag 那么些在 html 上不应该是 <Tag></Tag> 么 为什么是 <van-tag></van-tag>呢，在那个文件加入了前缀的注册？

**Comment by cookfront** [comment]
https://github.com/youzan/vant/blob/dev/packages/utils/create-basic.js

**Comment by cocody** [comment]
thx, 看漏了还有一个 create 函数
