### ISSUE TITLE
[Bug Report] Calendar $refs上不存在scrollToDate方法

### ISSUE THREAD

**Issue by kukuyuhai** [youzan/vant#7978]
### 设备 / 浏览器
iphone

### Vant 版本
3.0.5

### Vue 版本
3.0.5

### 重现链接
<a href="http://vant-contrib.gitee.io/vant-issue-generater" target="_blank">http://vant-contrib.gitee.io/vant-issue-generater</a>

### 描述问题
我在日历组件中设置type="range",default-date="null",想让日历显示当月的时间周期，调用实例scrollToDate方法,发现不存在该方法，实例只有reset方法。

**Comment by chenjiahan** [comment]
已在 3.0.6 版本修复
