### ISSUE TITLE
[Feature Request] 希望tabs的滑动支持滑动位置跟随手势移动，像swiper一样，而不是死的，手势结束才判断位置

### ISSUE THREAD

**Issue by ganshiqingyuan** [youzan/vant#7980]
### 这个功能解决了什么问题
体验更好

### 描述您想要的解决方案
跟随touchmove，计算组件的transform

### 建议的API是什么样的
直接修改swipeable的表现形式

**Comment by chenjiahan** [comment]
已经在 3.0 版本支持了喔，2.x 版本暂无计划支持（改动较大，属于不兼容更新）
