### ISSUE TITLE
[Bug Report] calendar组件在父容器旋转横屏后的里面渲染空白

### ISSUE THREAD

**Issue by steady-join** [youzan/vant#7981]
### 设备 / 浏览器
ios/chrome/Safire

### Vant 版本
2.12.3

### Vue 版本
2.6.12

### 重现链接
![image](https://user-images.githubusercontent.com/29935583/105656474-44dcf400-5efd-11eb-9c8d-fcb572082d84.png)

### 描述问题
父元素通过css旋转后，calendar组件渲染异常

**Comment by chenjiahan** [comment]
通过 css 渲染的话，组件是感知不到的喔，你可以把 lazy-render 设置为 false 来避免这个问题

**Comment by steady-join** [comment]
> 通过 css 渲染的话，组件是感知不到的喔，你可以把 lazy-render 设置为 false 来避免这个问题

已解决，谢谢

**Comment by cseve123** [comment]
> > 通过 css 渲染的话，组件是感知不到的喔，你可以把 lazy-render 设置为 false 来避免这个问题
> 
> 已解决，谢谢

道友是怎么解决的，能提供一下方法吗，我也碰到了这个问题
