### ISSUE TITLE
[Bug Report] ios下Field下动态设置placeholder不显示

### ISSUE THREAD

**Issue by terryz95** [youzan/vant#7985]
### 设备 / 浏览器
iphone 6s / ios12.3.1 / safari （iphone 7p / ios13.7也有同样问题）

### Vant 版本
2.10.4

### Vue 版本
2.6.12

### 重现链接
<a href="https://jsbin.com/hataneh/edit?html,js" target="_blank">https://jsbin.com/hataneh/edit?html,js</a>

### 描述问题
ios下如果给Field type=textarea设置了rows，则动态设置的placeholder不会立刻显示，需要点击输入框才显示。
demo预览地址https://output.jsbin.com/hataneh/1

**Comment by terryz95** [comment]
经验证原生textarea元素也存在这样的问题，即placeholder从空字符串改写成其他字符串时，placeholder总是不会立即变化显示，而是需要点击文本域placeholder才会显示出来

**Comment by chenjiahan** [comment]
这个属于原生 Textarea 标签的渲染问题咯，Vant 这边无法解决呢
