### ISSUE TITLE
[Bug Report] 在vite2 下如何引入库中的less及定制主题

### ISSUE THREAD

**Issue by van-chin** [youzan/vant#7986]
### 设备 / 浏览器
chrome 88

### Vant 版本
3.0.5

### Vue 版本
3.0.5

### 重现链接
<a href="https://github.com/van-chin/vanttest.git" target="_blank">https://github.com/van-chin/vanttest.git</a>

### 描述问题
vite 2下如何导入 vant库的less 及对less变量进行修改 定制主题
导入less之后会进行报错
具体的问题在 https://github.com/van-chin/vanttest.git 中 烦请 clone 运行查看

**Comment by chenjiahan** [comment]
Vite 目前似乎还不支持波浪号 `~` 前缀的 import，所以会报错

**Comment by adndyxu** [comment]
this will work
```js
//vant.theme.less
@import 'vant/lib/index.less';
@tabs-default-color:#ccc;

//main.js
import '@/assets/style/theme/vant.theme.less'


//vite.config.js
resolve: {
	alias: [
		{ find: /^~/, replacement: '' }
	]
}
```

**Comment by hcw2175** [comment]
i got a better way!

**按需引入**

需要使用插件：[vite-plugin-imp](https://github.com/onebay/vite-plugin-imp)

vite.config.ts 配置如下：

```
import vitePluginImp from 'vite-plugin-imp';
{
  plugins: [
    // 按需加载依赖库
    vitePluginImp({
      libList: [
        {
          libName: 'vant',
          style(name) {
            if (/CompWithoutStyleFile/i.test(name)) {
              // This will not import any style file
              return false;
            }
            // 注意此处必须引入less，否则自定义主题不起作用
            return `vant/es/${name}/index.less`;
          }
        }
      ]
    })
  ]
}
```

**主题定制**

vite.config.ts 配置如下：

```
css: {
  preprocessorOptions: {
    // 全局注入变量
    scss: {
      additionalData: `$injectedColor: orange;`
    },

    // 自定义vant样式主题
    less: {
      modifyVars: {
        hack: `true; @import "./src/assets/css/vant.theme.less";`,
      }
    }
  }
}
```

vant.theme.less 文件内容：

```
// Button
@button-primary-background-color: red;
```

**实例**



![image](https://user-images.githubusercontent.com/8132286/109124684-2715df80-7786-11eb-87d8-80913f241c49.png)

**Comment by adndyxu** [comment]
> i got a better way!
> 
> **按需引入**
> 
> 需要使用插件：[vite-plugin-imp](https://github.com/onebay/vite-plugin-imp)
> 
> vite.config.ts 配置如下：
> 
> ```
> import vitePluginImp from 'vite-plugin-imp';
> {
>   plugins: [
>     // 按需加载依赖库
>     vitePluginImp({
>       libList: [
>         {
>           libName: 'vant',
>           style(name) {
>             if (/CompWithoutStyleFile/i.test(name)) {
>               // This will not import any style file
>               return false;
>             }
>             // 注意此处必须引入less，否则自定义主题不起作用
>             return `vant/es/${name}/index.less`;
>           }
>         }
>       ]
>     })
>   ]
> }
> ```
> 
> **主题定制**
> 
> vite.config.ts 配置如下：
> 
> ```
> css: {
>   preprocessorOptions: {
>     // 全局注入变量
>     scss: {
>       additionalData: `$injectedColor: orange;`
>     },
> 
>     // 自定义vant样式主题
>     less: {
>       modifyVars: {
>         hack: `true; @import "./src/assets/css/vant.theme.less";`,
>       }
>     }
>   }
> }
> ```
> 
> vant.theme.less 文件内容：
> 
> ```
> // Button 修改主要按钮背景颜色-红色
> @button-primary-background-color: red;
> ```
> 
> **实例**
> 
> ```
> <van-button type="primary" @click="hello()">立即保存</van-button>
> ```
> 
> ![image](https://user-images.githubusercontent.com/8132286/109124684-2715df80-7786-11eb-87d8-80913f241c49.png)

First not every component has index.less file, like [form], this should be changed like this:
```js
vitePluginImp({
	libList: [
		{
			libName: 'vant',
			style(name) {
				if (/form/i.test(name)) {
					// This will not import any style file
					return false
				}
				return `vant/lib/${name}/index.less`
			},
		},
	],
})
```
besides , when I run build, the css package size is not right(4MB). So I roll back to global import.

**Comment by HuangYiLin** [comment]
使用插件：vite-plugin-imp 
导入Lazyload 组件会报错， 原因是Lazyload组件没有index.less文件

**Comment by jayfongs** [comment]
> 我有更好的办法！
> 
> **按需约会**
> 
> 需要使用插件：[vite-plugin-imp](https://github.com/onebay/vite-plugin-imp)
> 
> vite.config.ts配置如下：
> 
> ```
> import vitePluginImp from 'vite-plugin-imp';
> {
>   plugins: [
>     // 按需加载依赖库
>     vitePluginImp({
>       libList: [
>         {
>           libName: 'vant',
>           style(name) {
>             if (/CompWithoutStyleFile/i.test(name)) {
>               // This will not import any style file
>               return false;
>             }
>             // 注意此处必须引入less，否则自定义主题不起作用
>             return `vant/es/${name}/index.less`;
>           }
>         }
>       ]
>     })
>   ]
> }
> ```
> 
> **主题定制**
> 
> vite.config.ts配置如下：
> 
> ```
> css: {
>   preprocessorOptions: {
>     // 全局注入变量
>     scss: {
>       additionalData: `$injectedColor: orange;`
>     },
> 
>     // 自定义vant样式主题
>     less: {
>       modifyVars: {
>         hack: `true; @import "./src/assets/css/vant.theme.less";`,
>       }
>     }
>   }
> }
> ```
> 
> vant.theme.less文件内容：
> 
> ```
> // Button 修改主要按钮背景颜色-红色
> @button-primary-background-color: red;
> ```
> 
> **实例**
> 
> ```
> <van-button type="primary" @click="hello()">立即保存</van-button>
> ```
> 
> ![图像](https://user-images.githubusercontent.com/8132286/109124684-2715df80-7786-11eb-87d8-80913f241c49.png)

大佬，这种方式还有一个问题。就是比如我用Button组件需要使用加载状态，加载状态内部调用的Loading组件。此刻Loading组件的样式不会被加载。List组件也有，其它有相关依赖的应该都会有这种问题

**Comment by liugangtaotie** [comment]
// 步骤一：官网复制theme.less文件到  src/assets/css/theme.less

...
// Tabs
@tabs-default-color: #2abc6d;
...

// 步骤二：引入全局样式

...
import { xxx } from "vant";
import "vant/lib/index.less"; // 全局引入样式
Vue.use(xxx);
...

// 步骤三：vite.config.ts

...
import path, { resolve } from "path";
...
export default defineConfig({
...
 // 配置别名
  resolve: {
    alias: [
      {
        find: /^~/,
        replacement: "",
      },
      {
        find: "@",
        replacement: resolve(__dirname, "src"),
      },
      {
        find: "@ASS",
        replacement: resolve(__dirname, "src/assets"),
      },
      ... 
    ],
  },
...

css: {
    preprocessorOptions: {
      less: {
        modifyVars: {
          hack: `true; @import "@ASS/css/theme.less";`,
        },
      },
    },
  },

...


![Screenshot 2021-04-04 at 4 56 01 PM](https://user-images.githubusercontent.com/22477383/113503802-b9b85400-9566-11eb-82db-c2b8f81a9ba7.png)

**Comment by chenjiahan** [comment]
vant-demo 仓库中添加了 vite-theme 示例，可以参考下：https://github.com/youzan/vant-demo/tree/master/vant/vite-theme

**Comment by mqhe2007** [comment]
> modifyVars: {
>         hack: `true; @import "./src/assets/css/vant.theme.less";`,
>       }

你好，请问
```js
modifyVars: {
  hack: `true; @import "./src/assets/css/vant.theme.less";`,
}
```
这种写法在哪可以查到官方资料？
