### ISSUE TITLE
Toast组件创建销毁逻辑异常

### ISSUE THREAD

**Issue by wensc1996** [youzan/vant#7988]
Toast组件创建和销毁逻辑异常

异常问题点见图
![IMG_20210125_150108](https://user-images.githubusercontent.com/23137960/105671922-7b773680-5f1e-11eb-865a-d9688e1e654f.jpg)

Toast.clear = function (all) {
  if (queue.length) {
    if (all) {
      queue.forEach(function (toast) {
        toast.clear();
      });
      queue = [];
    } else if (!multiple) {
      queue[0].clear();
    } else {
      // 源代码：queue.shift().clear();
      queue.pop().clear(); // 建议
    }
  }
  console.log(queue)
};

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
