### ISSUE TITLE
日历组件使用没有报错，不能正常弹出，文档中的demo同样

### ISSUE THREAD

**Issue by dleomiss** [youzan/vant#7993]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by dleomiss** [comment]
![image](https://user-images.githubusercontent.com/24615724/105692178-0ebd6580-5f39-11eb-9d98-c6f67edc5ce8.png)
demo绑定方法不正确

**Comment by dleomiss** [comment]
![image](https://user-images.githubusercontent.com/24615724/105692178-0ebd6580-5f39-11eb-9d98-c6f67edc5ce8.png)
demo绑定方法不正确

**Comment by chenjiahan** [comment]
感谢反馈，文档已修正，近期会更新站点
