### ISSUE TITLE
关于在van-field中通过 readonly 将输入框设置为只读状态不显示value值的问题

### ISSUE THREAD

**Issue by wuchuzhengzhong** [youzan/vant#7995]
在官方文档中设置readonly可以设置只读输入框<van-field label="手机号" :value="phone" readonly ></van-field>，但在实际项目中这样设置不会显示value，
看源码是:model-value="t('inputReadonly')"这样设置属性，我尝试使用v-model设置能正确显示<van-field label="手机号" v-model="phone" readonly></van-field>

**Comment by wuchuzhengzhong** [comment]
vant版本3.0.4

**Comment by chenjiahan** [comment]
需要使用 model-value 来设置输入框的值喔，文档里写错了，会修正下
