### ISSUE TITLE
[Bug Report] Toast组件在多实例下创建销毁逻辑异常

### ISSUE THREAD

**Issue by wensc1996** [youzan/vant#7996]
### 设备 / 浏览器
Chrome/IOS/Android

### Vant 版本
3.0.5

### Vue 版本
3.0.5

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-220bh?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-220bh?file=/src/App.vue</a>

### 描述问题
修改建议：
Toast.clear = function (all) {
if (queue.length) {
if (all) {
queue.forEach(function (toast) {
toast.clear();
});
queue = [];
} else if (!multiple) {
queue[0].clear();
} else {
// 源代码：queue.shift().clear();
queue.pop().clear(); // 建议
}
}
console.log(queue)
};

**Comment by wensc1996** [comment]
> 这里按照队列clear，没有问题。你这个demo单独应该使用实例上面的clear方法。建议Toast.clear(all=true)，这样就可以避免这个问题。 @chenjiahan

如果这样，就会产生一种迷惑行为：在本demo中，3S的ToastA会因为0.5S的ToastB提前关闭。其实无论是shift,或者pop都不完善，基于异步的ToastB可能出现在栈顶，可能出现在栈尾，甚至中间。这里期望是能提供一种精确识别这种异步手动关闭的ToastB,并将其销毁，因为ToastA自身是有准确销毁自己的能力。

**Comment by chenjiahan** [comment]
调用 Toast 时，会返回对应的实例，直接调用实例上的 `clear` 方法就可以精准关闭某一个 Toast，文档里有的。

```js
const toast1 = Toast('第一个 Toast');
const toast2 = Toast.success('第二个 Toast');

toast2.clear();
```

**Comment by wensc1996** [comment]
> 调用 Toast 时，会返回对应的实例，直接调用实例上的 `clear` 方法就可以精准关闭某一个 Toast，文档里有的。
> 
> ```js
> const toast1 = Toast('第一个 Toast');
> const toast2 = Toast.success('第二个 Toast');
> 
> toast2.clear();
> ```

了解，谢谢，埋个坑在这，不读源码还发现不了问题出在哪。
