### ISSUE TITLE
vant里面的图标地址失效了

### ISSUE THREAD

**Issue by hzq-up** [youzan/vant#7997]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater
vant里面的图标地址失效了，https://img.yzcdn.cn/vant/vant-icon-96970a.woff2
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by hzq-up** [comment]
翻墙就能访问，没翻墙就没有，不知道为什么

**Comment by liangshenghua** [comment]
我的项目也是，不知道是不是24号更新的问题，图标全部失效

**Comment by Acesarye** [comment]
> 翻墙可以访问，没翻墙就没有，不知道为什么

刚刚也发现了，还想到这找方案。。。

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/7987
