### ISSUE TITLE
area.js哈密市编码为652200请更正

### ISSUE THREAD

**Issue by dingfeipeng** [youzan/vant#7999]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by dingfeipeng** [comment]
设备 / 浏览器
iOS/safori

Vant 版本
3.0.5

Vue 版本
3.0.5

重现链接
https://github.com/youzan/vant/blob/dev/src/area/demo/area.js

描述问题
哈密市编码为652200
