### ISSUE TITLE
外联引用vant，<van-cell-group>组件渲染出错

### ISSUE THREAD

**Issue by abaozhizhong** [youzan/vant#800]
![temp](https://user-images.githubusercontent.com/22359458/38075389-c9377422-3364-11e8-909d-6d0fb2fa16a2.png)
如上如图

**Comment by cookfront** [comment]
是指样式问题么？

**Comment by abaozhizhong** [comment]
这里会有出现嵌套的情况 不是样式问题吧

**Comment by cookfront** [comment]
`<van-cell></van-cell>` 要使用闭合标签的这种写法哦

**Comment by liguyu** [comment]
Trapped in the same way.
