### ISSUE TITLE
[Bug Report] empty组件图片失效

### ISSUE THREAD

**Issue by atom-7** [youzan/vant#8002]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.5

### Vue 版本
2.6.11

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/empty" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/empty</a>

### 描述问题
图片找不到,显示的图片都没有了,一看官网的也挂了

**Comment by chenjiahan** [comment]
已在 2.12.6 版本修复，原因参见 https://github.com/youzan/vant/issues/7987
