### ISSUE TITLE
tab 标签页

### ISSUE THREAD

**Issue by zhweb** [youzan/vant#801]
tab 标签页设置点击的时候click console index title  在左右滑动的时候没有用

**Comment by cookfront** [comment]
能具体描述下么，或者贴下代码，没太看明白你的问题，左右滑动没用是指？

**Comment by qianzhaoy** [comment]
@cookfront  应该是说左右滑动切换 `tab` 后, 没有 `emit('click')` 吧

**Comment by cookfront** [comment]
@zhweb  升级到最新版本的 `vant`，这个问题已经修复了
