### ISSUE TITLE
[Bug Report] Vue3.0, 表单中绑定的值无法在Vue Devtools中同步更改

### ISSUE THREAD

**Issue by muzaisimao** [youzan/vant#8014]
### 设备 / 浏览器
Chrome

### Vant 版本
3.0.5

### Vue 版本
3.0.5

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-ferwd?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-ferwd?file=/src/App.vue</a>

### 描述问题
Vue3.0中表单中绑定的值无法在Vue Devtools中同步更改, 去掉`<van-form>`就没问题了, 目前还不确定是Vant的问题, 还是Devtools的问题,重现链接中有放截图...

**Comment by muzaisimao** [comment]
![image](https://user-images.githubusercontent.com/31382094/106086449-24ab7000-615d-11eb-9639-7199f6864891.png)
展示图片~

**Comment by chenjiahan** [comment]
看起来应该是 Devtools 的问题喔，建议到 Devtools 仓库下进行反馈
