### ISSUE TITLE
关于V-for与field同时使用时焦点问题

### ISSUE THREAD

**Issue by AdamChipsK** [youzan/vant#8017]
<div v-for="(item,index) in list" :key="index" :id="item.user_id">
            <div style="margin-top: 20px">
                <span style="margin-left: 10px;">{{item.org_name}}:</span>
                <van-field style="margin-top: 10px" v-model="pf[index]" type="digit" :title="item.user_name" maxlength="2" :key="index" placeholder="请输入分数" :blur="checkMax()" :label="item.user_name" ></van-field>
            </div>
        </div>
我使用这样一段代码来批量使用输入框，但这些输入框在每次输入的时候都会调用失去焦点的方法，不知道是本身组件问题还是我的写法有问题

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
