### ISSUE TITLE
vant3 popup的v-model:show在tsx下如何使用

### ISSUE THREAD

**Issue by sangshaofeng** [youzan/vant#8019]
在使用vue3 + vant3 + tsx时，对于popup类似的组件都换成了v-model-show，可是tsx不支持这种语法。直接使用show可以打开，但不能双向绑定。请问tsx该怎么使用这个指令双向绑定popup的show属性。

**Comment by sangshaofeng** [comment]
代码如下：

`<van-popup
  show={showAreaPopup.value}
  round
  position="bottom"
  close-on-popstate={true}
>
  <van-area
    title="选择省市区"
    area-list={area}
    onCancel={() => {
      showAreaPopup.value = false
    }}
    onConfirm={(val: AreaItem[]) => {
      areaText.value = val[0].name + val[1].name + val[2].name
      showAreaPopup.value = false
    }}
  />
</van-popup>`

**Comment by chenjiahan** [comment]
看文档。

https://github.com/vuejs/jsx-next#directives

**Comment by sangshaofeng** [comment]
谢谢！
