### ISSUE TITLE
[Bug Report] [PullRefresh] not pullable

### ISSUE THREAD

**Issue by stritti** [youzan/vant#8020]
### Device / Browser
Desktop/Chrome

### Vant Version
3.0.5

### Vue Version
3.0.5

### Reproduction Link
<a href="https://covid-ampel-widget-git-pull-to-refresh.stritti.vercel.app" target="_blank">https://covid-ampel-widget-git-pull-to-refresh.stritti.vercel.app</a>

### Describe the bug
I try o add `<PullRefresh>` to my app. It should refresh the initial page (home) after selecting one *"Landkreis"* in the *"Einstellungen"*, but the view is not pullable for refresh.

See the associated PR with the changes here: https://github.com/stritti/covid-ampel-widget/pull/37

**Comment by stritti** [comment]
Okay, i noticed that it is working on real mobile device ( iPhone + Safari) in contrast to emulator of Chrome on Windows.

**Comment by chenjiahan** [comment]
See: [Adapt to PC Browsers](https://youzan.github.io/vant/#/en-US/advanced-usage#adapt-to-pc-browsers)
