### ISSUE TITLE
[Features Request]popover组件自定义内容，增加样式修改className属性

### ISSUE THREAD

**Issue by HOKET** [youzan/vant#8021]
现在的popover组件只能给actions添加className修改样式，但是在自定义内容时，是用不到actions的，例如我现在有一个需求只是点击弹窗显示一段文字，但是样式调不了，自己添加styles的话，气泡只有一行，内容很容易超过屏幕

**Comment by chenjiahan** [comment]
自定义内容的样式完全可以自行控制的，没 get 你的意思。

**Comment by HOKET** [comment]
> 自定义内容的样式完全可以自行控制的，没 get 你的意思。

我已经自己搞定了

我的意思是popover组件弹窗后的节点是在app的外层，所以无法通过app.vue那里给定样式，只能自己在自定义的内容那边的html元素上在style属性那里写样式，但如果自定义内容多，涉及的样式也比较多，不想把样式写在html那层上，所以想popover组件有一个属性可以赋值一个类名，这个类名的样式可以直接在style那层写

**Comment by chenjiahan** [comment]
明白👌 暂时没计划加这个能力喔
