### ISSUE TITLE
[Bug Report] 字体图标打不开了

### ISSUE THREAD

**Issue by lml6060** [youzan/vant#8024]
### 设备 / 浏览器
谷歌

### Vant 版本
2.8.6

### Vue 版本
2.5.6

### 重现链接
<a href="https://img.yzcdn.cn/vant/vant-icon-6ae417.woff2" target="_blank">https://img.yzcdn.cn/vant/vant-icon-6ae417.woff2</a>

### 描述问题
字体文件访问出错

**Comment by xiaozhanghui** [comment]
他们CDN好像挂了

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/7987
