### ISSUE TITLE
[Bug Report] Swipe设置loop为false时，页面无法滑动

### ISSUE THREAD

**Issue by dh13899396662** [youzan/vant#8025]
### 设备 / 浏览器
安卓

### Vant 版本
2.6.2

### Vue 版本
2.6.11

### 重现链接
<a href="http://localhost:8080/matrix_project/entertainment_city/challenge_activity/#/fissionDetail?isBlowUp=1" target="_blank">http://localhost:8080/matrix_project/entertainment_city/challenge_activity/#/fissionDetail?isBlowUp=1</a>

### 描述问题
当Swipe在H5页面最底部时，设置loop为false，位置索引值为0时，这时手向下滑动也确实无法滚动到最后一帧，但是页面也滑不上去。

**Comment by chenjiahan** [comment]
重现链接无效，请提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
