### ISSUE TITLE
[Bug Report] vite   tsx 怎么使用插槽

### ISSUE THREAD

**Issue by zh-lc** [youzan/vant#8026]
### 设备 / 浏览器
 Microsoft Edge 版本 87.0.664.75 (官方内部版本) (64 位)

### Vant 版本
3.0.5

### Vue 版本
3.0.5

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/v3/#/zh-CN/cell#cell-slots" target="_blank">https://vant-contrib.gitee.io/vant/v3/#/zh-CN/cell#cell-slots</a>

### 描述问题
基于vite构建vue3，插槽无法使用

const SwitchSlots = {
      'right-icon': () => (
        <Switch size="24" />
      ),
    };
<Cell title="默认地址" v-slots={SwitchSlots}></Cell>

**Comment by zh-lc** [comment]
``const SwitchSlots = {
      'right-icon': () => (
        <Switch size="24" />
      ),
    };

<Cell title="默认地址" v-slots={SwitchSlots}></Cell>


``
这是代码

**Comment by zh-lc** [comment]
![image](https://user-images.githubusercontent.com/49424265/106075516-b9f03980-6148-11eb-831a-0b4e743f9bf6.png)
这是代码

**Comment by chenjiahan** [comment]
麻烦提供一下复现问题的仓库

**Comment by zh-lc** [comment]
> 麻烦提供一下复现问题的仓库
> 
> Please provide the warehouse in which the recurrence problem occurred

https://github.com/zh-lc/vue3-app

**Comment by zh-lc** [comment]
> 麻烦提供一下复现问题的仓库
> 
> Please provide the warehouse in which the recurrence problem occurred
你好，下面是仓库地址
https://github.com/zh-lc/vue3-app

**Comment by John60676** [comment]
`v-slots` 是 `jsx-next` 的做的兼容语法。不支持 **vite 1.x**。 参考：vuejs/jsx-next#118

另外，**vite 1.x** 不推荐使用，建议升级为 **vite 2.x**
