### ISSUE TITLE
[Bug Report] 下拉菜单 DropdownItem value无法赋值

### ISSUE THREAD

**Issue by Nana-Cti** [youzan/vant#8027]
### 设备 / 浏览器
Chrome

### Vant 版本
3.0.4

### Vue 版本
3.0.4

### 重现链接
<a href="https://codepen.io/nana-cti/pen/LYRwqzY" target="_blank">https://codepen.io/nana-cti/pen/LYRwqzY</a>

### 描述问题
DropdownItem 文档中value	当前选中项对应的 value，可以通过v-model双向绑定, 实际源码中使用的是modelValue, 给value赋值无法生效

![image](https://user-images.githubusercontent.com/39090154/105967738-2a537800-60c1-11eb-8f34-d545b3ba2361.png)
![image](https://user-images.githubusercontent.com/39090154/105967843-4820dd00-60c1-11eb-9abc-57ce57c41409.png)

**Comment by chenjiahan** [comment]
在 Vant 3.x 版本中，需要写成 :model-value 喔

文档有误，已修正

**Comment by chenjiahan** [comment]
在 Vant 3.x 版本中，需要写成 :model-value 喔

文档有误，已修正
