### ISSUE TITLE
dialog 在ios 动画效果出现偏移

### ISSUE THREAD

**Issue by linyi435892508** [youzan/vant#8028]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---
一开始是在接口返回后 调用dialog 出现的动画效果偏移 本来是从中间弹出 但却从右下角弹回中间
后面通过测试 做了一个对照组
第一个方法是 直接调用dialog 
method1() {
  this.$dialog.alert({
    message: '您的帐号已被关入小黑屋，可联系客服人员处理',
    confirmButtonColor: '#06C1AF'
  })
}
第二个方法是 加个延时 模拟接口调用 再调用dialog
method2() {
  setTimeout(() => {
     this.$dialog.alert({
        message: '您的帐号已被关入小黑屋，可联系客服人员处理',
        confirmButtonColor: '#06C1AF'
      })
  }, 1000)
}
发现 方法2 出现的效果和在接口返回中调用dialog 效果一样 都不是从正中间弹出 而是从右下角弹出回归正中间
这两个方法在html层面根本没有改变任何东西 脑子陷入了迷茫 求教

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
