### ISSUE TITLE
布局都是PX，没有用rem。

### ISSUE THREAD

**Issue by shen-lan** [youzan/vant#803]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by shen-lan** [comment]
实际开发的时候 都是直接写px吗？高度px，宽度百分比或者flex之类的？

**Comment by cocody** [comment]
是的，你可以用postcss转换成rem

**Comment by linwenfeng122** [comment]
我感觉第三方用px感觉还好，不然你自己的布局会导致第三方出问题，这样你还得改第三方的样式
