### ISSUE TITLE
picker组件建议加入一种滑动动画（当前选项放大显示）

### ISSUE THREAD

**Issue by bromiao** [youzan/vant#8030]
如图所示：
![093606_G0GK_2613440](https://user-images.githubusercontent.com/19767083/106093209-d2714b80-616a-11eb-8657-0a2eb56edf15.gif)
![25102425_pciG](https://user-images.githubusercontent.com/19767083/106093212-d43b0f00-616a-11eb-90c8-985d4a44f4a7.gif)

**Comment by chenjiahan** [comment]
暂无计划支持喔
