### ISSUE TITLE
[Bug Report] Toast组件添加closeOnClickOverlay: true属性点击遮罩并不会关闭

### ISSUE THREAD

**Issue by EchoesR** [youzan/vant#8031]
### 设备 / 浏览器
Chrome

### Vant 版本
3.0.5

### Vue 版本
3.0.5

### 重现链接
<a href="https://codepen.io/echoesr-the-styleful/pen/gOLYXbx" target="_blank">https://codepen.io/echoesr-the-styleful/pen/gOLYXbx</a>

### 描述问题
Toast组件添加closeOnClickOverlay: true属性点击遮罩并不会关闭。源码中点击遮罩触发的update:show事件并没有在Toast组件中监听。

**Comment by chenjiahan** [comment]
已在 3.0.6 版本修复
