### ISSUE TITLE
[Bug Report]  WARN  [Vant] Icon: "info" prop is deprecated, use "badge" prop instead. 

### ISSUE THREAD

**Issue by liseipi** [youzan/vant#8032]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.6

### Vue 版本
2.6.11

### 重现链接
<a href="http://localhost:3300" target="_blank">http://localhost:3300</a>

### 描述问题
```SSR使用 <van-goods-action-icon icon="cart-o" text="购物车" badge="5" /> 这个组件时警告 ```

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.12.7 版本修复
