### ISSUE TITLE
通过system.js无法加载，必须是在vue加载成功以后才能加载到vant

### ISSUE THREAD

**Issue by coolliyong** [youzan/vant#8034]
我们使用了微前端的架构做的项目，在通过systemjs引入的时候会偶先 vant
 无法被正常初始化，必须是先加载vue，然后再加载vant，这样才不会有问题，我想有没有独立版本，不传入vue，也能正常的初始化的方式。

![11](https://user-images.githubusercontent.com/25497230/106220645-e83c4a80-6216-11eb-8f58-e77dbff7fd8a.png)

![22](https://user-images.githubusercontent.com/25497230/106220659-ef635880-6216-11eb-9e55-dfb0e54b20aa.png)

如果把vue去掉，则只能拿到一个 "{}"，有没有什么方式不 通过两次加载的形式解决这个问题？

**Comment by chenjiahan** [comment]
> 我想有没有独立版本，不传入vue，也能正常的初始化的方式。

没有的喔，CDN 版本的 Vant 初始化是依赖 Vue 的。

建议你看下如何保证脚本加载顺序是稳定的。
