### ISSUE TITLE
from 效验规则 -> 异步函数校验 输入框，鼠标移开的时候屏幕一直闪动

### ISSUE THREAD

**Issue by hzd1219809916** [youzan/vant#8036]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

--- https://vant-contrib.gitee.io/vant/v3/#/zh-CN/form

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
