### ISSUE TITLE
picker组件onChange，索引字段显示为undefined

### ISSUE THREAD

**Issue by LIJUN-XU** [youzan/vant#8037]
picker组件绑定onChange，索引字段显示为undefined，之前有同样的issues，维护人员显示已经解决，但是，3.0.5都依然存在这个问题。望核实。

**Comment by chenjiahan** [comment]
我试了下没问题，建议你对照文档再试下

https://vant-contrib.gitee.io/vant/v3/#/zh-CN/picker

**Comment by LIJUN-XU** [comment]
> 我试了下没问题，建议你对照文档再试下
> 
> https://vant-contrib.gitee.io/vant/v3/#/zh-CN/picker

通过实例可以获取，但是change 传入的参数确实没有，为undefined

**Comment by FFFlower** [comment]
我这也是undefined
