### ISSUE TITLE
[Bug Report] Popover打包之后样式权重问题

### ISSUE THREAD

**Issue by ht159357** [youzan/vant#8039]
### 设备 / 浏览器
Chrome

### Vant 版本
2.12.3

### Vue 版本
2.6.10

### 重现链接
<a href="http://test.wstong.iwanzhuan.com/h5//tk/goods.html#/cashEarnings?areaCode=331000000000&areaName=%E5%8F%B0%E5%B7%9E&merchantId=11093160585621632&userId=100108278" target="_blank">http://test.wstong.iwanzhuan.com/h5//tk/goods.html#/cashEarnings?areaCode=331000000000&areaName=%E5%8F%B0%E5%B7%9E&merchantId=11093160585621632&userId=100108278</a>

### 描述问题
点击页面问号icon
在打包完的样式中.van-popup优先级高过了.van-popover，变现异常
而在开发环境中正常，.van-popover优先级高过.van-popup，表现正常

![image](https://user-images.githubusercontent.com/22785090/106265923-b5b83f00-6262-11eb-8e52-eb1393b989b4.png)
![image](https://user-images.githubusercontent.com/22785090/106265933-b8b32f80-6262-11eb-96b6-cb5fa510c00c.png)

**Comment by chenjiahan** [comment]
组件内部引入的 CSS 顺序是正常的喔，建议你检查下项目的构建配置
