### ISSUE TITLE
jsx语法使用list频繁触发onLoad

### ISSUE THREAD

**Issue by ZanyZephy** [youzan/vant#8041]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

import { defineComponent, reactive } from "vue";
import { PullRefresh, List, Cell } from "vant";
export default defineComponent({
  setup() {
    interface State {
      list: Array<number>;
      loading: boolean;
      finished: boolean;
      refreshing: boolean;
    }

    const state: State = reactive({
      list: [],
      loading: false,
      finished: false,
      refreshing: false,
    });

    const onLoad = () => {
      setTimeout(() => {
        if (state.refreshing) {
          state.list = [];
          state.refreshing = false;
        }

        for (let i = 0; i < 10; i++) {
          state.list.push(state.list.length + 1);
        }
        state.loading = false;

        if (state.list.length >= 40) {
          state.finished = true;
        }
      }, 1000);
    };

    const onRefresh = () => {
      // 清空列表数据
      state.finished = false;

      // 重新加载数据
      // 将 loading 设置为 true，表示处于加载状态
      state.loading = true;
      onLoad();
    };
    return () => (
      <>
        <PullRefresh v-model={state.refreshing} onRefresh={onRefresh}>
          <List
            loading={state.loading}
            // finished={state.finished}
            finished-text="没有更多了"
            onLoad={onLoad}
          >
            {{
              default: () =>
                state.list.map((item, index) => {
                  return <Cell key={index} title={item}></Cell>;
                }),
            }}
          </List>
        </PullRefresh>
      </>
    );
  },
});

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请绑定 v-model:loading

`v-model={[state.loading, 'loading']}`
