### ISSUE TITLE
Cell组件为什么不开放value的slot？

### ISSUE THREAD

**Issue by yajore** [youzan/vant#805]
**What is the current behavior?**
如题，另外新的cell布局（flex）
如果value没有设置
van-cell__title样式的需要设置flex:1，不然不会是100%的宽度，导致之前的样式全乱了

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
1. Cell 的 default slot 就是 value
2. 目前看应该不需要默认设置 title 的 flex 为 1，如果需要的话可以手动加一下

**Comment by chenjiahan** [comment]
将在下个版本添加  .van-cell__title { flex: 1 }
