### ISSUE TITLE
[Feature Request] ImagePreview组件路由跳转不会自动关闭

### ISSUE THREAD

**Issue by 321802282** [youzan/vant#8053]
### 这个功能解决了什么问题
在页面回退的时候不会关闭图片预览

### 描述您想要的解决方案
增加和Dialog一样的close-on-popstate Api

### 建议的API是什么样的
close-on-popstate	是否在页面回退时自动关闭	boolean

**Comment by chenjiahan** [comment]
closeOnPopstate 现在就支持的
