### ISSUE TITLE
imagePreview  点击  触发缩放和关闭事件  ？怎么禁止

### ISSUE THREAD

**Issue by qsw-net** [youzan/vant#8054]
--<template >
  <van-image-preview 
    v-model:show="show"
    :show-indicators="true"
    :images="images"
    :startPosition="index"
    :swipeDuration="500"
    :closeable="true"
    @change="onChange"
    @close="imageClick"
    
  >
  </van-image-preview>
--</template>
vant 3.0+

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
