### ISSUE TITLE
[Bug Report] Notify 不显示message文字

### ISSUE THREAD

**Issue by 823697223** [youzan/vant#8058]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.6

### Vue 版本
2.6.12

### 重现链接
<a href="http://localhost:8080" target="_blank">http://localhost:8080</a>

### 描述问题
Notify 不显示message文字，观察到挂载时候没有message属性，_props里面message为undefined，不知道是不是这个问题。

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
