### ISSUE TITLE
[Bug Report] ImagePreview图片显示异常

### ISSUE THREAD

**Issue by weiyuc** [youzan/vant#8059]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.6

### Vue 版本
3.0.5

### 重现链接
<a href="https://sy6ii.csb.app/" target="_blank">https://sy6ii.csb.app/</a>

### 描述问题
两次调用ImagePreview, 如果第二次调用图片数量少于第一次且则会显示异常, 2.x版本没问题

**Comment by chenjiahan** [comment]
已在 3.0.7 版本修复
