### ISSUE TITLE
关于checkbox

### ISSUE THREAD

**Issue by VenusPP** [youzan/vant#807]
在购物车选择状态使用组件checkbox，后台返回的数据中并无‘true’或‘false’value值，我需要做的是根据checkbox的选中状态与否返给后台该id，选中传id，我的思路是data一个新数组selectArray,在checkbox的v-model=“selectArray” @change="handleChange(v.cart.id)"  methods: {handleChange(id) {this.selectArray.push(id)}} // 报错this.selectArray is not a function 。无法根据选中状态推送id

**Comment by cookfront** [comment]
你这个报错应该和checkbox组件无关呀
