### ISSUE TITLE
请问vant3,针对vue3,会开发sku商品规格的业务组件吗？

### ISSUE THREAD

**Issue by yang-git-hub** [youzan/vant#8073]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
后续会提供的喔，短期内可能没有，近期开发投入比较有限

**Comment by lixiaofa** [comment]
> 你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
> 
> http://vant-contrib.gitee.io/vant-issue-generater
> 
> Please use the link below to create a new issue, the non-standard issue will be closed.
> 
> https://youzan.github.io/vant-issue-generater

我迁移了vant2.x 的sku
https://www.npmjs.com/package/vant-sku?activeTab=readme
