### ISSUE TITLE
地址编辑 收取不到地区数据

### ISSUE THREAD

**Issue by zhweb** [youzan/vant#808]
首先我是用的CDN方式引用的Vant
    
![image](https://user-images.githubusercontent.com/20854070/38135476-e00bba50-344a-11e8-98dd-2ce8a3d9fbcb.png)

然后别的地方我现在不知道
     只知道现在选择地址那块用CDN是不出来数据
![cc07d5365399477562b50389da62b76](https://user-images.githubusercontent.com/20854070/38136459-037347a0-3451-11e8-8728-9c40ee6f51e8.png)
![5cefe9590d78af05a020e7f1601967a](https://user-images.githubusercontent.com/20854070/38136464-073537fe-3451-11e8-9cf6-5b7ad251ed7b.png)
一直在转圈，怎么办。。

**Comment by cookfront** [comment]
`areaList` 这个数据没有看到你定义啊。。
