### ISSUE TITLE
swipe-cell 在ios设备上ontouch事件没有触发

### ISSUE THREAD

**Issue by mazhenxiao** [youzan/vant#8082]
设备： iphone7
版本： 11.3
node_modules\vant\es\swipe-cell\index.js
描述： touch事件未生效
onTouchStart,onTouchmove,onTouchend 事件未生效，触发无反应，toggle 函数未执行。
未找到有效解决办法，android和其他ios版本无此问题。
1、出现问题源码断点截取如下
 return function () {
      var wrapperStyle = {
        transform: "translate3d(" + state.offset + "px, 0, 0)",
        transitionDuration: state.dragging ? '0s' : '.6s'
      };
      return _createVNode("div", {
        "ref": root,
        "class": bem(),
        "onClick": getClickHandler('cell'),
        "onTouchstart": onTouchStart,
        "onTouchmove": onTouchMove,
        "onTouchend": onTouchEnd,
        "onTouchcancel": onTouchEnd
      }, [_createVNode("div", {
        "class": bem('wrapper'),
        "style": wrapperStyle
      }, [renderSideContent('left', leftRef), slots.default == null ? void 0 : slots.default(), renderSideContent('right', rightRef)])]);
    };
  }

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
