### ISSUE TITLE
[Bug Report] ActionSheet 组件 safe-area-inset-bottom 不生效

### ISSUE THREAD

**Issue by Elvmx** [youzan/vant#8083]
### 设备 / 浏览器
iPhoneX

### Vant 版本
3.0.6

### Vue 版本
3.0.5

### 重现链接
<a href="https://output.jsbin.com/vutidav" target="_blank">https://output.jsbin.com/vutidav</a>

### 描述问题
使用 ActionSheet 组件时，发现不管是否设置 safe-area-inset-bottom 属性，都没有生效

**Comment by chenjiahan** [comment]
已在 3.0.7 版本修复
