### ISSUE TITLE
[Bug Report] NavBar in standalone mode on iOS

### ISSUE THREAD

**Issue by stritti** [youzan/vant#8084]
### Device / Browser
Safari standalone

### Vant Version
3.0.6

### Vue Version
3.0.5

### Reproduction Link
<a href="https://covid-ampel.vercel.app/" target="_blank">https://covid-ampel.vercel.app/</a>

### Describe the bug
If the PWA app is installed on iOS as standalone app (add to Homescreen) the icons of NavBar are behind the system generated line:

![2393F5C5-8E3F-4522-A2C0-7815601E3D30](https://user-images.githubusercontent.com/184547/106918645-aaa15b00-6709-11eb-97bc-70023c943cd3.jpeg)

There should be some more bottom spacing on iOS in standalone mode at iPhone.

**Comment by chenjiahan** [comment]
NavBar is expected be placed at the top of page, not the bottom, so we did not add the `safe-area-inset-bottom` prop.

You can add the following CSS manually:

```css
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
```

**Comment by stritti** [comment]
Sorry, you are right NavBar is placed at top of page. It is `<van-tabbar>` which is IMHO intended to be placed at bottom of page. Sorry for confusion in naming.

**Comment by stritti** [comment]
Okay, now I noticed, there is already a flag to enable this feature:
`<van-tabbar safe-area-inset-bottom="true">`

**Comment by stritti** [comment]
BTW for calculation I fond now following article which could be helpful to improve CSS:
https://medium.com/@draganeror/iphone-x-layout-features-with-css-environment-variables-d57423433dec

**Comment by chenjiahan** [comment]
> BTW for calculation I fond now following article which could be helpful to improve CSS

Thanks for the suggestion, we will refer to it.
