### ISSUE TITLE
[Feature Request] Steps步骤条，自定义图标

### ISSUE THREAD

**Issue by featnet** [youzan/vant#8093]
### 这个功能解决了什么问题
现有的Step只能自定义已激活/未激活的图标，希望可以自定义已完成步骤的图标，比较灵活。

### 描述您想要的解决方案
现有的Step只能自定义已激活/未激活的图标，希望可以自定义已完成步骤的图标，比较灵活。

### 建议的API是什么样的
建议Step Slots添加自定义已完成步骤的图标，或者直接添加一个图标的slot，并在slot-scope传当前步骤状态的参数

**Comment by chenjiahan** [comment]
已在 2.12.7 版本支持
