### ISSUE TITLE
[Feature Request] Cascader 级联选择的数据回显

### ISSUE THREAD

**Issue by wall-git** [youzan/vant#8094]
### 这个功能解决了什么问题
可以回显指定区划

### 描述您想要的解决方案
可以根据tabIndex设置默认选择的value
可以在chrildren赋值后默认

### 建议的API是什么样的
defvalue:[
{tabIdex:0,vlaue:"320323000000"},
{tabIdex:1,vlaue:"320323010000"},
{tabIdex:2,vlaue:"320323010200"},
]

**Comment by wall-git** [comment]
设置默认value之后，自动触发点击事件。

**Comment by chenjiahan** [comment]
没明白你的需求，能否详细描述下？

如果是想设置当前选中项，直接修改 v-model 对应的 value 即可。

**Comment by wall-git** [comment]
> 没明白你的需求，能否详细描述下？
> 
> 如果是想设置当前选中项，直接修改 v-model 对应的 value 即可。

你好，这个是级联的，如果我只是设置 v-model  是不是只能设置当前级的？如何自动触发加载之前的呢？

**Comment by chenjiahan** [comment]
v-model 是设置当前级的，你说的「自动触发加载之前的」是指？

**Comment by wall-git** [comment]
> v-model 是设置当前级的，你说的「自动触发加载之前的」是指？

可能我描述的不够清楚，举个栗子：我是用的省市县三级地址，最终保存的是县级行政区划编码，此时关闭界面，再次打开时界面上已经显示了县级编码，此时点击选择级联区划，该如何将县级的市级和省级自动加载出来并自动选中？而不是再次手工一级级点开。不知这样描述是否清楚，感谢关注！

**Comment by chenjiahan** [comment]
> 该如何将县级的市级和省级自动加载出来并自动选中

市级和省级的数据如果是同步加载的话，会默认选中。

如果是异步加载的话，目前不支持呢。

**Comment by wall-git** [comment]
> 如果是异步加载的话，目前不支持呢。
好吧，我的问题里没提到异步加载，确实是需要异步加载的数据回显，能否加入开发计划希望下一个版本用上，谢谢。。

**Comment by wall-git** [comment]
> 如果是异步加载的话，目前不支持呢。
好吧，我的问题里没提到异步加载，确实是需要异步加载的数据回显，能否加入开发计划，希望下一个版本用上，谢谢。。

**Comment by chenjiahan** [comment]
异步加载的话，需要由组件的使用者来自行设置数据。

具体做法是：当你需要异步加载某个县的数据时，把对应的上级省市数据也设置上去，这样应该是能正常展示的

**Comment by dk-leegen** [comment]
> v-model 是设置当前级的，你说的「自动触发加载之前的」是指？

这样会出现一个问题，如果子级的value并不是唯一的，就会出现一个bug；例如初始化反绑'tab'的时候cascade就只会找到最后一个包含'tab'的父级

**Comment by towry** [comment]
似乎移动端还没有很好的多选cascader组件。

**Comment by chenjiahan** [comment]
> 这样会出现一个问题，如果子级的value并不是唯一的，就会出现一个bug；例如初始化反绑'tab'的时候cascade就只会找到最后一个包含'tab'的父级

value 必须是唯一值喔。

> 似乎移动端还没有很好的多选cascader组件。

Cascader 暂不支持多选~
