### ISSUE TITLE
中文 Dialog 弹出框 文档一处单词错误

### ISSUE THREAD

**Issue by puzzle9** [youzan/vant#8101]
<https://vant-contrib.gitee.io/vant/v3/#/zh-CN/dialog>

![深度截图_选择区域_20210207235908](https://user-images.githubusercontent.com/13518196/107151995-9460fc80-69a0-11eb-9b0e-4c16b67b505a.png)

`Promsie` 应为 `Promise`

**Comment by chenjiahan** [comment]
感谢反馈，已修正
