### ISSUE TITLE
[Bug Report] 请问是否有主题系列颜色的生成函数

### ISSUE THREAD

**Issue by chris1299** [youzan/vant#8104]
### 设备 / 浏览器
浏览器

### Vant 版本
2.12.6

### Vue 版本
2.5.15

### 重现链接
<a href="https://github.com/R-Von/vant-theme" target="_blank">https://github.com/R-Von/vant-theme</a>

### 描述问题
我需要vant的主题系列颜色生成函数，类似@ant-design/colors的色彩生成函数，以实现通过webpack-theme-color-replacer插件实现动态切换主题

**Comment by chenjiahan** [comment]
木有喔，暂时没有支持的计划
