### ISSUE TITLE
当有一个van-popup组件弹出时，如果再触发toast组件 弹出提示

### ISSUE THREAD

**Issue by Link-X** [youzan/vant#814]
当有一个van-popup组件弹出时，如果再触发toast组件 弹出提示，toast组件层级在 van-popup组件下面。直到过1秒才层级才提升到van-popup 上

**Comment by Link-X** [comment]
版本号 0.12.14

**Comment by cookfront** [comment]
升级到最新版本的 vant 试试，看看还会不会有对应的问题，toast组件最近有修复过一些bug

**Comment by Link-X** [comment]
已经修复好啦 thank
