### ISSUE TITLE
[Feature Request] 以后会不会加上卡片视图和小图标集合呢

### ISSUE THREAD

**Issue by summerlemons** [youzan/vant#8149]
### 这个功能解决了什么问题
布局更加优美，小图标省去了自己引入图片

### 描述您想要的解决方案
新曾这两项视图

### 建议的API是什么样的
卡片视图就是类似<van-card></van-card> 这样的，小图标则通过 i 标签引入， 目前 tabar 中引入了四种图标，我觉得都挺好，可以多拓展点

**Comment by chenjiahan** [comment]
图标可以直接使用 Icon 组件喔，卡片暂无计划调整
