### ISSUE TITLE
急急急！！Popup在安卓手机上出现严重问题

### ISSUE THREAD

**Issue by VenusPP** [youzan/vant#815]
vue: 2.4,
vant: 0.12.14
安卓：4.4.4
[](url)
h5嵌套app 点击弹出popup时出现严重位置偏移，项目急上线，求解啊！！！

**Comment by VenusPP** [comment]
[[]()](url)

**Comment by cookfront** [comment]
麻烦最好提供截图看下，以及出bug对应的代码

**Comment by VenusPP** [comment]
bug已经解决 在css中设置样式并覆盖
     left: 0
    -webkit-transform: translate3d(0,0,0);
    transform: translate3d(0%,0,0);
    即可解决在安卓低版本手机出现定位严重偏移问题
    测试的是安卓<4..4.4 组件Toast  Dialog 等涉及c3转换的组件都会出现此情况

**Comment by cookfront** [comment]
这个应该是安卓低版本手机导致的
