### ISSUE TITLE
vite 不支持 less ~

### ISSUE THREAD

**Issue by zhangchenna** [youzan/vant#8155]
vite 不支持 less ~ 符号 目前解决方案 postinstall-postinstall @import '~@vant/icons/src/encode-woff2.less'; 改为 @import '@vant/icons/src/encode-woff2.less'; 期待vant 提供更好的方案

**Comment by chenjiahan** [comment]
这个问题已知喔，最好是等 vite2 支持 less 的波浪号

参见 https://github.com/youzan/vant/issues/7986

**Comment by jiyingzhi** [comment]
@chenjiahan 
![image](https://user-images.githubusercontent.com/21698836/130541853-929e819a-7b56-4f4d-92b3-92c7ed4a0f3b.png)
最新版的 less-loader 和 sass-loader 都已经支持不带波浪号了，并且加波浪号是一个被废弃的特性，Vite 也是因为这个不加波浪号的，所以 Vant 可以支持下这个特性吗

**Comment by chenjiahan** [comment]
最新版 Vant 不需要用 less 了，直接使用 ConfigProvider 组件即可

**Comment by jiyingzhi** [comment]
但是Vant2还是有很多人用的

**Comment by landejin** [comment]
在vite中添加别名可以解决：

{ find: /^~@vant/, replacement: resolve('node_modules/@vant') },
