### ISSUE TITLE
关于修改控件默认样式及尺寸的问题

### ISSUE THREAD

**Issue by miaovictor** [youzan/vant#816]
您好，请问对于一个控件，如何修改其默认样式及尺寸呢？我看到的建议都是样式覆盖，但是对于一个控件我该如何快速找到对应的样式名称呢？

**Comment by cookfront** [comment]
1. 如果只是主题修改可以看这里：[https://www.youzanyun.com/zanui/vant#/zh-CN/theme](https://www.youzanyun.com/zanui/vant#/zh-CN/theme)
2. 其他的样式只能自己覆盖了，就浏览器的开发者工具查看对应的css了
