### ISSUE TITLE
滑动tabs 和Swipe同时使用滑动优先级问题怎么处理

### ISSUE THREAD

**Issue by ZC1993** [youzan/vant#817]
在可滑动的tabs 中添加swipe 滑动swipe tabs跟着切换了，请问下有没有添加手势优先级的方法

**Comment by ZC1993** [comment]
![default](https://user-images.githubusercontent.com/16315014/38192357-27c2626c-369f-11e8-9f65-e9abc101d709.png)

**Comment by cookfront** [comment]
感谢反馈，我们会看下有啥好的解决方案

**Comment by chenjiahan** [comment]
下个版本修复此问题

**Comment by chenjiahan** [comment]
已在 1.0.5 版本修复

**Comment by ZC1993** [comment]
十分感谢

**Comment by GHUserZ** [comment]
请问在没解决的我也在van-tabs里边使用了swiper 滑动swiper内容会切换van-tabs
