### ISSUE TITLE
[Feature Request] PullRefresh 下拉到一定的位置触发下拉刷新

### ISSUE THREAD

**Issue by mp0907** [youzan/vant#8171]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/pull-refresh#zi-ding-yi-ti-shi" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/pull-refresh#zi-ding-yi-ti-shi</a>

### 描述问题
PullRefresh “下拉到一定位置”再触发下拉刷新, 真机测试只要轻轻下拉就会触发刷新，很容易误操作 ，建议加上一个pull-height属性 number | string

**Comment by chenjiahan** [comment]
可以试试 `head-height` 属性

**Comment by mp0907** [comment]
![image](https://user-images.githubusercontent.com/32899094/108177871-ab6bc100-70fb-11eb-91bd-3ae9b4327e4f.png)
head-height 这个属性要设置很高才能有效控制，但是这样的话，顶部会留下很大一片白

**Comment by chenjiahan** [comment]
已在 2.12.8 版本支持
