### ISSUE TITLE
[Feature Request] Steps 步骤条组件可以没有 active

### ISSUE THREAD

**Issue by joo1es** [youzan/vant#8172]
### 这个功能解决了什么问题
竖向步骤条，有时用作时间轴显示，不需要用到active api

### 描述您想要的解决方案
添加一个api，屏蔽active的作用

### 建议的API是什么样的
Steps Props 添加一个 finished: Boolean，若为 true，active不起作用

**Comment by chenjiahan** [comment]
暂无计划添加喔，你可以把 active 设置为 -1 或者 999
