### ISSUE TITLE
[Bug Report] 网站经常挂，打不开

### ISSUE THREAD

**Issue by zhujianxiong** [youzan/vant#8174]
### 设备 / 浏览器
谷歌/火狐

### Vant 版本
3.0.6

### Vue 版本
3.0.5

### 重现链接
<a href="https://youzan.github.io/vant" target="_blank">https://youzan.github.io/vant</a>

### 描述问题
网站经常挂，打不开，不稳定

**Comment by nemo-shen** [comment]
尝试用一下科学上网？github.io可能会有`DNS污染`之类的问题，可以百度/谷歌一下相关问题，我这边目前是可以正常打开的哦~

**Comment by zhujianxiong** [comment]
不太懂，不过建议vant优化一下，他这个就是提示无法链接服务器：youzan.github.io 拒绝了我们的连接请求

**Comment by chenjiahan** [comment]
https://youzan.github.io/vant 是部署在 Github Pages 的。

建议使用国内镜像：https://vant-contrib.gitee.io/vant/#/zh-CN/
