### ISSUE TITLE
can't load encode-woff2.less on the vite 

### ISSUE THREAD

**Issue by difflib** [youzan/vant#8175]
Issue 类型:bug
版本:
 "vant": "^3.0.6",
 "vue": "^3.0.5",
"vite": "^2.0.0-beta.67",
描述问题:
[plugin:vite:css] '~@vant/icons/src/encode-woff2.less' wasn't found. Tried - /home/whois/vue/vmall/node_modules/vant/lib/icon/~@vant/icons/src/encode-woff2.less,node_modules/~@vant/icons/src/encode-woff2.less,npm://~@vant/icons/src/encode-woff2.less,~@vant/icons/src/encode-woff2.less
/home/whois/vue/vmall/node_modules/vant/lib/icon/index.less:2:0
1  |  @import '../style/var';
   |                          ^
2  |  @import '~@vant/icons/src/encode-woff2.less';

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/7986
