### ISSUE TITLE
[Bug Report] DropdownMenu在van-tabs 中使用定位异常

### ISSUE THREAD

**Issue by hjm100** [youzan/vant#8185]
### 设备 / 浏览器
浏览器

### Vant 版本
3.0.6

### Vue 版本
3.0.5

### 重现链接
<a href="https://developer.mozilla.org/zh-CN/docs/Web/CSS/position" target="_blank">https://developer.mozilla.org/zh-CN/docs/Web/CSS/position</a>

### 描述问题
因为 tabs的切换使用了  transform: translateX(0px);而DropdownMenu中的van-dropdown-item没有放在body中且使用了定位 position: fixed;，这样的话定位参考为 tabs，如果我的页面下面还有van-tabbar的话，最后的bottom高度就会多出来50px，这样的话你的van-dropdown-item就远离了DropdownMenu 50px，建议将这种弹出层使用position: fixed的放在body中这样的话就不会有这种transform与flex冲突的发生

**Comment by chenjiahan** [comment]
将 DropdownItem 的 teleport 属性设置为 body 即可

**Comment by hjm100** [comment]
刚才看文档找到了，本来要过来自己关闭的，谢谢
