### ISSUE TITLE
[Bug Report] ActionSheet因为shouldReopen属性，会导致返回时自动打开ActionSheet

### ISSUE THREAD

**Issue by BarrierLeo** [youzan/vant#8186]
### 设备 / 浏览器
安卓

### Vant 版本
2.11.3

### Vue 版本
2.6.12

### 重现链接
<a href="https://codepen.io/barrierleo/pen/VwmzraV" target="_blank">https://codepen.io/barrierleo/pen/VwmzraV</a>

### 描述问题
前提：ActionSheet组件在keep-alive的页面（以 A页面 代称）中，开启close-on-click-action属性

触发：在A页面点击ActionSheet的按钮，跳到B页面（任意），再返回A页面，重复上述操作一次，此时会自动打开ActionSheet

问题分析：返回时会触发deactivated钩子，源码中根据 value 和 shouldReopen属性判断是否需要打开ActionSheet，但是close-on-click-action属性触发的关闭ActionSheet事件，没有更新value的值，导致自动开启了ActionSheet

**Comment by chenjiahan** [comment]
> 但是close-on-click-action属性触发的关闭ActionSheet事件，没有更新value的值

这里会更新 value 的值

> https://codepen.io/barrierleo/pen/VwmzraV

这个链接的用法错误喔，不应该在 ActionSheet 再添加 v-show，这样会覆盖默认的 display 值

我试了下没复现问题，建议重新提供下 codepen 链接~

**Comment by BarrierLeo** [comment]
> > 但是close-on-click-action属性触发的关闭ActionSheet事件，没有更新value的值
> 
> 这里会更新 value 的值
> 
> > https://codepen.io/barrierleo/pen/VwmzraV
> 
> 这个链接的用法错误喔，不应该在 ActionSheet 再添加 v-show，这样会覆盖默认的 display 值
> 
> 我试了下没复现问题，建议重新提供下 codepen 链接~

@chenjiahan 我使用v-show是想要模拟deactivated，用的方法不对，不好意思！
用codepen无法模拟出我的问题，不知道下面的描述能否清楚地传达我的意思：

我发现问题是在ActionSheet中的这段代码
`if (props.closeOnClickAction) {
    emit(ctx, 'input', false);
}`
用emit更新value的值似乎需要一段时间（40多毫秒）
deactivated 触发的时间会在 更新value的值 完成之前，所以在deactivated 钩子中value值会为true，导致返回时重新打开ActionSheet

**Comment by chenjiahan** [comment]
已在 2.12.8 版本修复
