### ISSUE TITLE
vant-weapp，van-uploader插件显示不了微信头像

### ISSUE THREAD

**Issue by youupiup** [youzan/vant#8188]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

![1613815967(1)](https://user-images.githubusercontent.com/39479677/108592124-450acb00-73a7-11eb-9c8b-9ddfb4883277.jpg)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
