### ISSUE TITLE
[Bug Report] vant  Tab 标签页  标签栏滚动 的话 个数过多 滚动会出现bug!!!

### ISSUE THREAD

**Issue by davidgww** [youzan/vant#8189]
### 设备 / 浏览器
google  360  ie 等

### Vant 版本
2.10.2

### Vue 版本
2.5.2

### 重现链接
<a href="https://hqhhtest.hqhh520.cn/h5/#/encyclopediaClassification?scId=8031885176529682434&oneName=%E5%A9%9A%E5%AB%81%E4%B9%A0%E4%BF%97" target="_blank">https://hqhhtest.hqhh520.cn/h5/#/encyclopediaClassification?scId=8031885176529682434&oneName=%E5%A9%9A%E5%AB%81%E4%B9%A0%E4%BF%97</a>

### 描述问题
使用  Tab 标签页  超过5个滚动的话 如果里面个数过多的话 滚动就会出现bug

**Comment by nemo-shen** [comment]
能否描述一下bug的具体表现:)
