### ISSUE TITLE
tabs组件里用List组件，在切换tab时候，List组件的onLoad 方法会执行请求上一个tab的数据

### ISSUE THREAD

**Issue by xjphhh** [youzan/vant#8191]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
