### ISSUE TITLE
Vant 3是否需要将*.legacy.js中的单元测试迁移到index.spec.ts中

### ISSUE THREAD

**Issue by nemo-shen** [youzan/vant#8198]
看了一下Vant 3，好像以前Vant 2中的*.spec.js大部分都调整成了*.legacy.js文件，`Coverage`从\~90%+下降到了\~77%+。

这些文件应该是等待迁移的单元测试吧？

## 目前已知信息
1. *.legacy.js不参与单元测试
2. *.legacy.js中的单测应该全部都是从Vant 2搬过来的
3. 看起来目前Vant 3中是希望将多个spec.js文件合并成一个index.spec.js文件
4. 单元测试需要支持typescript

## 我想怎么做
1. 将*.legacy.js中的单测尽可能不做调整进行迁移，确保测试结果的正确性
2. 将多个*.legacy.js单测文件合并成一个index.spec.js文件
3. 将demo.spec.js和index.spec.js调整成demo.spec.ts和index.spec.ts

## 希望能知道的信息
1. 现在做单元测试的时机是否合适？（考虑到可能Vant 3可能还有其他优先级较高的事情需要做）
2. 目前Vant 3的开发进度是如何的？
3. 我的处理方式是否是正确的？还有什么没有考虑到的点？

看了下现在的commits，重点好像是在增加typescript语法支持上。

**Comment by chenjiahan** [comment]
> 将*.legacy.js中的单测尽可能不做调整进行迁移，确保测试结果的正确性

这一点没问题~ 基本上 Vue 2 的单测都可以平移到 Vue 3

> 将多个*.legacy.js单测文件合并成一个index.spec.js文件

文件酌情进行合并即可，不强制

> 将demo.spec.js和index.spec.js调整成demo.spec.ts和index.spec.ts

单测是需要使用 TS 写的，目前 demo.spec.js 已经全部迁移晚了，index.spec.js 还在迁移过程中

> 现在做单元测试的时机是否合适？

是合适的喔，我们下一步的重点就是迁移单测，欢迎 PR~

> 目前Vant 3的开发进度是如何的？

除了 Sku 组件，已经全部开发完成了

> 我的处理方式是否是正确的？还有什么没有考虑到的点？

有一点需要注意，单测依赖的 vue-test-utils 有大版本升级，需要使用新版本的 API
