### ISSUE TITLE
[Bug Report] feild输入框文本域在IOS环境无法输入

### ISSUE THREAD

**Issue by lsm1998** [youzan/vant#8199]
### 设备 / 浏览器
iphone6、iphonexs等

### Vant 版本
2.12.6

### Vue 版本
2.5.2

### 重现链接
<a href="https://github.com/youzan/vant/没有重现链接，但是必填项，请忽略" target="_blank">https://github.com/youzan/vant/没有重现链接，但是必填项，请忽略</a>

### 描述问题
feild输入框，type指定为文本域，在安卓手机和浏览器都可以输入，IOS设备下点击输入，出现键盘按钮，但不出现光标，无法正常输入。

**Comment by chenjiahan** [comment]
没复现问题喔，建议用原生 input 标签试下是否有同样的问题，如果有的话，可能是项目中其他库影响的。
