### ISSUE TITLE
[Bug Report] Stepper步进器禁用状态和圆角风格结合使用时，ios系统不显示输入框文本

### ISSUE THREAD

**Issue by zengfanyu1** [youzan/vant#8200]
### 设备 / 浏览器
ios系统

### Vant 版本
2.10.10

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/zengfanyu1/pen/PobONPK" target="_blank">https://codepen.io/zengfanyu1/pen/PobONPK</a>

### 描述问题
使用 圆角风格的步进器   禁用状态时，在ios系统上输入框的默认值不显示，在浏览器能正常显示

**Comment by chenjiahan** [comment]
已在 2.12.8 版本修复
