### ISSUE TITLE
在Popup 弹出层中使用IndexBar 索引栏会导致阴影层下的内容滚动

### ISSUE THREAD

**Issue by BekeWorker** [youzan/vant#8203]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---测试手机iPhonexr 版本号12.1.2 iPhone11 版本号未知 
1.阴影层下的内容滚动
2.popup中van-index-bar__sidebar滚动，隐藏
Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
