### ISSUE TITLE
GHSL-2020-343: seeking security contact for your project

### ISSUE THREAD

**Issue by anticomputer** [youzan/vant#8211]
The GitHub Security Lab reported a potential security vulnerability (GHSL-2020-343) in your project (youzan/vant). We are approaching 90 days since our initial report and as per our [coordinated disclosure policy](https://securitylab.github.com/advisories#policy), we intend to publish a public advisory detailing this issue. If you wish to discuss or further coordinate a response to this issue with the GitHub Security Lab, please contact us at securitylab@github.com within the next 7 days in reference to GHSL-2020-343 and we would love to help you resolve these issues. If not, feel free to close this issue and we will proceed with advisory publication on expiration.

**Comment by chenjiahan** [comment]
Thanks for the suggestion! we will deal with it in the next few days.

**Comment by chenjiahan** [comment]
@anticomputer The security issue has been fixed in vant v3.0.7

**Comment by anticomputer** [comment]
> @anticomputer The security issue has been fixed in vant v3.0.7
>

Great, thank you for the update.

**Comment by liujiajie32** [comment]
当前最新的 [v2.12.43](https://github.com/youzan/vant/releases/tag/v2.12.43) 版本依然存在高危漏洞GHSL-2020-343，可否在 Vant 2 发布修复此漏洞的版本？谢谢！

**Comment by chenjiahan** [comment]
@liujiajie32 可以的，一会儿修复
