### ISSUE TITLE
[Bug Report] 真机运行无法直接调用摄像头

### ISSUE THREAD

**Issue by tjh906434588** [youzan/vant#8217]
### 设备 / 浏览器
华为 Honor 6X

### Vant 版本
2.12.6

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/tjh906434588/dome" target="_blank">https://github.com/tjh906434588/dome</a>

### 描述问题
capture="camera"这个属性无效

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6015
