### ISSUE TITLE
[Bug Report] 部分组件标签，webstorm仍不识别

### ISSUE THREAD

**Issue by topoge** [youzan/vant#8219]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.6

### Vue 版本
2.6.12

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/col" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/col</a>

### 描述问题
van-row,van-col
目前是发现这两个

![Snipaste_2021-02-25_19-13-12](https://user-images.githubusercontent.com/36975447/109145583-a06cfc80-779d-11eb-94a0-61acb7962142.png)

**Comment by chenjiahan** [comment]
目前生成的 web-types.json 定义还不够完善，后续会优化下

**Comment by topoge** [comment]
> 
> 
> 目前生成的 web-types.json 定义还不够完善，后续会优化下

一些业务组件的tag也不识别，比如van-coupon-cell，van-coupon-list估计还要其他的零散的组件
希望能够ide友好，像element ui那样完善

**Comment by chenjiahan** [comment]
已在 2.12.12 和 3.0.12 版本修复，可以试下
