### ISSUE TITLE
Uploader 图片上传  的属性disable  资料有误！

### ISSUE THREAD

**Issue by uddsoft** [youzan/vant#822]
Uploader 图片上传  的属性disable  资料有误！

**Comment by cookfront** [comment]
能具体说下怎么有误么？以便我们更正

**Comment by uddsoft** [comment]
地址：https://www.youzanyun.com/zanui/vant#/zh-CN/uploader
Api属性列表  disable 需要改成 disabled  。可以禁用该控件使用。
