### ISSUE TITLE
[Bug Report] 引入Popover失败

### ISSUE THREAD

**Issue by 18258639001** [youzan/vant#8222]
### 设备 / 浏览器
电脑端谷歌浏览器

### Vant 版本
3.0.6

### Vue 版本
3.0.6

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/popover" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/popover</a>

### 描述问题
Module '"../../node_modules/vant/types"' has no exported member 'Popover'.

**Comment by chenjiahan** [comment]
Popover 有的，建议检查下你的 Vant 版本是否大于 2.11
