### ISSUE TITLE
van-field中使用type="date"无效

### ISSUE THREAD

**Issue by PuRonglong** [youzan/vant#823]
**van-field中使用type="date"无效**

**van-field中使用type="date"，在iOS 11.3，微信6.6.6中点击什么反应都没有，在安卓7.0系统和微信6.6.5中点击却可以出来时间选择**

**期望在field中可以填写时间**

**Vant 1.0.3 and Vue 2.5.16**

**Comment by cookfront** [comment]
暂时不支持的，后续会加个slot来支持这种情况

**Comment by PuRonglong** [comment]
@cookfront 你好，使用type="date“无效呢

**Comment by cookfront** [comment]
`type="date"` 我试了是正常的

**Comment by PuRonglong** [comment]
我又试了下还是不行，请问要怎么给你复现呢，需要真机才能复现，微信开发工具上不行，jsbin在线地址也无法复现，录个视频发微信还是怎么呢？

**Comment by PuRonglong** [comment]
@cookfront 我发现怎么触发了，就是type="date" type="date" v-model="listDetail.supplyTime"，如果v-model刚开始是空字符串也就是没有值的时候，点击这个不会出来时间选择，如果这个v-model有值，比如2018年4月3日的时候，点击就可以正常出来时间选择。你那边能复现吗？

**Comment by cookfront** [comment]
你提供个  https://jsfiddle.net/dfarLdko/1/  类似的demo吧

**Comment by cookfront** [comment]
https://github.com/youzan/vant/issues/729  这里有交流群的二维码

**Comment by PuRonglong** [comment]
OK，我在群里说
