### ISSUE TITLE
[Bug Report] Picker 选择器部分示例文档较为古老

### ISSUE THREAD

**Issue by liuyinghui5** [youzan/vant#8230]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.6

### Vue 版本
3.0.6

### 重现链接
https://youzan.github.io/vant/v3/#/zh-CN/picker

### 描述问题
比如 : Picker 选择器中 "搭配弹出层使用" 
<template 模板内绑定为 <van-popup v-model:show="showPicker"   
<script 中定义为 const state = reactive({value: '',showPicker: false,});  

期待完善
也许 v-show="state.showPicker" 对初次使用者更友好一些

**Comment by chenjiahan** [comment]
已修正，近期会更正文档
