### ISSUE TITLE
国际化相关

### ISSUE THREAD

**Issue by dean16930** [youzan/vant#8233]
### 这个功能解决了什么问题
目前vant版本中支持的语言包太少，如果用户需要新增语言包，就必须通过Pull Request 的方式通过官方在版本中增加新的语言包

### 描述您想要的解决方案
建议官方通过提供语言包配置模版，用户在项目中自己导入需要支持的语言包来扩展。

### 建议的API是什么样的
比如：
 ```
  import Vue from 'vue'
  import { Locale } from 'vant'
  import th from '/mylocalPath/th_TH.js' // 自己的语言包

  Vue.use(Locale)

  // 切换至泰语，并且需要导入泰语语言包
  Locale.use('th', th)
```

**Comment by chenjiahan** [comment]
没有模板喔，直接参考项目里现有的语言包就行。

还是比较推荐发 Pull Request，这样能保证同步更新，而且能造福其他开发者
