### ISSUE TITLE
[Bug Report] vant list 组件direction属性设置'up', 数据多次加载

### ISSUE THREAD

**Issue by Hzhxi9** [youzan/vant#8234]
### 设备 / 浏览器
Google Chrome

### Vant 版本
3.0.6

### Vue 版本
3.0.6

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-51u3e?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-51u3e?file=/src/App.vue</a>

### 描述问题
当list属性设置为up 数据多次加载

**Comment by chenjiahan** [comment]
设置 up 后，当滚动条处于页面顶部时，本身就是会触发加载的。

建议在 Load 触发后将滚动条滚动至底部。

**Comment by Hzhxi9** [comment]
请求第一次的时候就把将页面滚动到底部的意思吗

**Comment by chenjiahan** [comment]
对的
