### ISSUE TITLE
field组件宽度异常的问题

### ISSUE THREAD

**Issue by AK47-dadada** [youzan/vant#8242]
版本：3.0.7
vue版本：3.0.6

问题：默认会使用van-cell__title这个样式 且flex:1 导致宽度按照flex属性在走

![image](https://user-images.githubusercontent.com/30396595/109467359-07dcc200-7aa6-11eb-8f4f-544cea97d06c.png)

查过issues找到过这个，这边官方的回答是引入了两次cell但实际情况是我删除了所有引入的组件 只引入了一次field，结果还是这样
label-width设置宽度无效：当然这个跟flex: 1有直接的关系
最后解决方案当然有 但是个人觉得框架这边还需要做一下处理

临时解决方案：这是我的处理方案
` ::v-deep .van-cell__title {
   flex: unset;
}`

以上如果有正在使用的朋友，如果遇到这样的问题 可以参照上面的解决方案

也希望作者能及时解决 谢谢

**Comment by AK47-dadada** [comment]
只有在页面引入具体组件的时候才会有这个问题

在mainjs引入，在use是不会存在这个问题的

奉上代码

`<template>
  <van-form @submit="onSubmit" class="appointment-info">
    <van-field v-model="appointmentInfo.name"
      label="应聘途径"
      placeholder="请输入您的姓名"/>
    <van-field v-model="appointmentInfo.name"
      label="姓名"
      placeholder="请输入您的姓名" />
    <van-field v-model="appointmentInfo.name"
      label="电话号码"
      placeholder="请输入您的姓名" />
    <van-field v-model="appointmentInfo.name"
      label="面试职位"
      placeholder="请输入您的姓名" />
    <van-field v-model="appointmentInfo.name"
      label="学历"
      placeholder="请输入您的姓名" />
    <van-field v-model="appointmentInfo.name"
      label="预约时间"
      placeholder="请输入您的姓名" />
    <van-button size="large"
      type="primary"
      native-type="submit"
      round
      :loading="loading">按钮</van-button>
  </van-form>
</template>

<script>
import { Field, Button, Form } from 'vant'

export default {
  components: {
    [Field.name]: Field,
    [Button.name]: Button,
    [Form.name]: Form
  },
  data () {
    return {
      appointmentInfo: {
        name: undefined
      },
      loading: false
    }
  },
  methods: {
    onSubmit () {}
  }
}
</script>

<style lang="less" scoped>
.appointment-info {
  padding: 6px
}
// ::v-deep .van-cell__title {
//   flex: unset;
// }
</style>`

**Comment by chenjiahan** [comment]
能否提供一个复现问题的 codesandbox 链接或仓库？

https://codesandbox.io/s/m5v3f

**Comment by AK47-dadada** [comment]
> 能否提供一个复现问题的 codesandbox 链接或仓库？
> 
> https://codesandbox.io/s/m5v3f

vant-demo--vant--vue3.0--新增vue文件，引入field就会发现这个问题

**Comment by chenjiahan** [comment]
请提供复现链接喔，否则无法进行排查。

**Comment by Ttou** [comment]
看来是按需加载引起的，在开发阶段 flex:1规则优先级低，不会生效，编译后优先级变高了。
#6567 #6312

**Comment by achenjs** [comment]
按照 @AK47-dadada 的方案可以解决这个问题，不能在组件中引入使用。 

main.ts 中注册 Field，组件中直接通过 <van-field /> 这样使用，打包之后才不会出现这个问题。
蛋疼的用法，插个眼后续有更优的方案请 @我

**Comment by jiaerxiao** [comment]
按需加载这个在版本 3.4.7 中好像 还是没有修复。我是在使用的页面中增加了这个
`.van-field__label {
      flex: none;
    }`

**Comment by BaoXianSheng** [comment]
2022年快结束了，我还是碰到这个问题了

**Comment by flymorn** [comment]
使用 unplugin-vue-components 按需加载，也会出现样式覆盖问题，目前依然未修复：
"vant": "^4.0.0",
"vue": "^3.0.0",

临时解决方案：在每个引用van-field的页面里 添加样式：
<style lang="less" scoped>
.van-cell{
  :deep(.van-cell__title){ flex: none; }
}
</style>
