### ISSUE TITLE
[Feature Request] 展示/隐藏 ImagePreview 组件时自定义 transition 过渡效果

### ISSUE THREAD

**Issue by joo1es** [youzan/vant#8248]
### 这个功能解决了什么问题
展示/隐藏 ImagePreview 组件时自定义 transition 过渡效果，目前只能使用默认的 van-fade

### 描述您想要的解决方案
类似于 popup ，加一个 transition 的 prop，可以自定义 transition 

### 建议的API是什么样的
transition: {
    Type: String,
    Default: 'van-fade'
}

**Comment by chenjiahan** [comment]
已在 2.12.8 版本支持

**Comment by a798032825** [comment]
想请教下，添加自定义 transition之后，本地写的进入和离开动画的样式，组件如何生效使用
