### ISSUE TITLE
[Bug Report] Vant 3.0.7 在tsx文件里按需引用问题

### ISSUE THREAD

**Issue by rpdg** [youzan/vant#8249]
![image](https://user-images.githubusercontent.com/1169162/109611054-a29dd500-7b68-11eb-9887-2ccd7415a1c7.png)

改用全部引入 `import {Button} from 'vant';` 
可以编译，但是在tsx里面没有代码提示，
请作者帮忙解答一下，谢谢

**Comment by chenjiahan** [comment]
目前通过 `vant/lib/button` 路径引入会有类型缺失，后续会修复

**Comment by greenking19** [comment]
请教一下，我也想tsx用vant。 但是我发现好像没有提示的。  vant有tsx的示例吗？ 我都没找到。

**Comment by chenjiahan** [comment]
已在 3.0.8 版本修复类型定义。

> 请教一下，我也想tsx用vant。 但是我发现好像没有提示的

有类型提示的喔，示例暂无

**Comment by greenking19** [comment]
> 已在3.0.8版本修复类型定义。
> 
> > 请教一下，我也想tsx用vant。但是我发现好像没有提示的
> 
> 有类型提示的喔，示例暂无

好的，tsx组件api在官网有文档吗？ 我没找到。
