### ISSUE TITLE
[Feature Request] ImagePreview组件的小问题

### ISSUE THREAD

**Issue by DickyNet** [youzan/vant#8250]
### 这个功能解决了什么问题
希望ImagePreview组件在调用超高图片时，可以提供接口实现默认图片显示的宽度为100%（即屏幕的最大宽度），高度为自适应，同时在图片用手势或双击放大时不影响上下左右拖动。目前图片高度特别高时，默认显示的是整个图片的全览图，太小了看不清。

### 描述您想要的解决方案
希望ImagePreview组件在调用超高图片时，可以提供接口实现默认图片显示的宽度为100%（即屏幕的最大宽度），高度为自适应，同时在图片用手势或双击放大时不影响上下左右拖动。目前图片高度特别高时，默认显示的是整个图片的全览图，太小了看不清。

### 建议的API是什么样的
vant.ImagePreview({
        imageWidth: '100%',
        imageHeight: 'auto'
      });

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/3928，先 close 咯

后续会考虑支持喔，也欢迎提 PR

**Comment by DickyNet** [comment]
希望尽快提供支持哈，加油，奥力给
