### ISSUE TITLE
2.12.7版本中，Picker级联选择器设置初始值的问题

### ISSUE THREAD

**Issue by gaojian88888888** [youzan/vant#8252]
1.配合弹出层Popup组件使用时，在mounted中使用this.$refs.picker1.setIndexes()找不到实例组件，排查问题是未初始化实例picker组件。
2.这时不使用Popup组件，在mounted中使用this.$refs.picker1.setIndexes()方法是可以设置的，但是不生效，this.$refs.picker1.getIndexes()获取到的数组是设置的值，但是组件中并没有生效

**Comment by chenjiahan** [comment]
1. 把 Popup 的 lazy-render 属性设置为 false 即可
2. 没懂，可以提供复现问题的 codesandbox 链接看下

**Comment by gaojian88888888** [comment]
> 1. lazy-render
问题1已解决，感谢！
