### ISSUE TITLE
vue jsx 3.0.7版本swipe使用插槽空白，退回3.0.6版本正常

### ISSUE THREAD

**Issue by ZanyZephy** [youzan/vant#8268]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---
 <Swipe class={styles["Swipe"]} onChange={onChange}>
          {{
            default: () => (
              <>
                {detail.value &&
                  detail.value.imgs.map((item: any) => {
                    return (
                      <SwipeItem class={styles["SwipeItem"]}>
                        <img
                          class={styles["SwipeItem_img"]}
                          src={imgUrl + item.path}
                        />
                      </SwipeItem>
                    );
                  })}
                ,
              </>
            ),
       }}
 </Swipe>
Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
