### ISSUE TITLE
area.json 数据  215090 没有父节点

### ISSUE THREAD

**Issue by qinxm** [youzan/vant#827]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by cookfront** [comment]
感谢反馈，我们确认一下
