### ISSUE TITLE
[Bug Report] TS 可选链语法问题

### ISSUE THREAD

**Issue by Sphinm** [youzan/vant#8287]
代码位置：https://github.com/youzan/vant/blob/dev/src/field/index.tsx#L163

```js
const runValidator = (value: unknown, rule: FieldRule) =>
  new Promise((resolve) => {
    const returnVal = rule.validator!(value, rule);

    if (isPromise(returnVal)) {
      return returnVal.then(resolve);
    }

    resolve(returnVal);
  });
```

由于 `validator` 是可选的，所以这里为了保证 `validator` 是有的，加了 `!` 保证，但是这个感叹号是告诉编译器这个字段肯定存在，但事实并不是的，在 babel 编译看一下就知道了。

建议改成如下方式兼容

`rule.validator && rule.validator(value, rule)`

**Comment by chenjiahan** [comment]
调用的地方已经对 rule.validator 进行了非空判断

https://github.com/youzan/vant/blob/08086c8002086a93b9f82aa642485c95ddbaf143/src/field/index.tsx#L201-L212
