### ISSUE TITLE
Stepper 按钮怎么阻止冒泡

### ISSUE THREAD

**Issue by ybbhzb** [youzan/vant#829]
类似于淘宝
购物车中,有Stepper 修改购买数量,点击商品跳转到商品页面
这时候操作Stepper 会冒泡 触发跳转到商品页面.怎么解决

![image](https://user-images.githubusercontent.com/25059371/38321900-6fcf5f1a-386b-11e8-915e-039cd3de46a4.png)

**Comment by VenusPP** [comment]
换个思路呢,点击去详情不包含stepper。

**Comment by cookfront** [comment]
目前就是需要判断下 `currentTarge`了，后续我们考虑加个参数把冒泡去掉

**Comment by chenjiahan** [comment]
在 stepper 的父层 div 绑定 @click.stop 即可
