### ISSUE TITLE
[Bug Report] DropdownMenu 下拉菜单

### ISSUE THREAD

**Issue by JsLing** [youzan/vant#8290]
### 设备 / 浏览器
ios

### Vant 版本
2.12.7

### Vue 版本
2.6.1

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-gf4nf" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-gf4nf</a>

### 描述问题
在项目中使用的是手动按需引入组件

**Comment by chenjiahan** [comment]
```js
components: {
  [DropdownMenu.name]: DropdownMenu,
  [DropdownMenu.name]: DropdownItem,
}
```

组件注册写错了
