### ISSUE TITLE
[Bug Report] ImagePreview 组件自定义过渡动画时的BUG

### ISSUE THREAD

**Issue by joo1es** [youzan/vant#8299]
### 设备 / 浏览器
Windows10 / Chrome 88.0.4324.190

### Vant 版本
2.12.8

### Vue 版本
2.6.12

### 重现链接
<a href="https://7yliw.csb.app/" target="_blank">https://7yliw.csb.app/</a>

### 描述问题
当过渡动画中出现 transform: scaleX 有关参数就会出现排版错误

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.12.10 版本修复
