### ISSUE TITLE
[Bug Report] 3.0.7-3.0.8

### ISSUE THREAD

**Issue by jiatingx** [youzan/vant#8300]
### 设备 / 浏览器
mac/chrome 版本 89.0.4389.82（正式版本） (x86_64)

### Vant 版本
3.0.8

### Vue 版本
3.0.7

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/src/style/var.less" target="_blank">https://github.com/youzan/vant/blob/dev/src/style/var.less</a>

### 描述问题
版本升级最新3.0.8后，定制主题覆盖样式失效，回归3.0.7版本恢复正常，无任何代码改动
//vue.config.js
      less: {
        lessOptions: {
          modifyVars: {
            // 或者可以通过 less 文件覆盖（文件路径为绝对路径）
            hack: `true; @import "~@/assets/styles/_variables.less";`
          }
        }
      }

**Comment by chenjiahan** [comment]
已在 3.0.9 版本修复
