### ISSUE TITLE
[Bug Report] tsx下，组件缺少事件的typescript定义

### ISSUE THREAD

**Issue by rpdg** [youzan/vant#8302]
vant：3.0.8
typescript：4.2.3

![image](https://user-images.githubusercontent.com/1169162/110266590-13c20a00-7ff9-11eb-961c-c267fc73256f.png)

**Comment by chenjiahan** [comment]
这是 Vue 类型定义的问题，参见 https://github.com/vuejs/vue-next/issues/1553

**Comment by yeojongki** [comment]
不是 Vue 类型定义的问题把 ? 现在引入的是 vant 的组件库，类型就应该由组件库定义才对把？
![image](https://user-images.githubusercontent.com/21023676/111035676-75013780-8456-11eb-8dc4-bf68c8574800.png)

![image](https://user-images.githubusercontent.com/21023676/111035639-500cc480-8456-11eb-8b2e-f955b03cafd5.png)

**Comment by chenjiahan** [comment]
上面的链接里写的很清楚了

**Comment by yeojongki** [comment]
@chenjiahan 在 vue 类型定义不支持的情况下，是否应该由 UI 库本身在 props 中定义 ？因为之前在用 ant-design-vue 没有遇到这种情况，所以才会提出这个疑问

**Comment by chenjiahan** [comment]
props 中的 `onFoo` 和 emits 里的 `foo` 会有冲突，而且 props 是运行时代码，不应该只为了 typing 服务。

ant-design-vue 也会有同样的问题，只是 ant-design-vue 的 Button 恰巧提供了 onClick prop。

**Comment by yeojongki** [comment]
@chenjiahan 
1. 你说的冲突确实是另外一个问题。
2. 这应该不是恰巧吧？反倒认为是故意为之，比如 Form，同样的 ant-design-vue 也提供了 [onSubmit 的 prop](https://github.com/vueComponent/ant-design-vue/blob/next/components/form/Form.tsx#L60)。
3. 当前这种情况下，用户有什么办法可以解决？

**Comment by chenjiahan** [comment]
加个 shim：https://github.com/youzan/vant/blob/dev/src/vue-tsx-shim.d.ts

**Comment by chenjiahan** [comment]
我不认为给 Button 提供 onClick 事件是更合理的选择，这和 Vue 的 emits 在设计上是矛盾的，更类似于 React 的写法（ant-design-vue 是由 React 版衍生出的）

**Comment by wustzhaohui** [comment]
> 我不认为给 Button 提供 onClick prop 是更合理的选择，这和 Vue 的 emits 在设计上是矛盾的，更类似于 React 的写法（ant-design-vue 是由 React 版衍生出的）

其实你不得不说vue3现在越来越像react的语法了。所以真的很想你们提供这个props

**Comment by chenjiahan** [comment]
下个版本会内置一个 onClick 的 shim
