### ISSUE TITLE
[Feature Request] 下拉刷新列表可否在增加分页配置

### ISSUE THREAD

**Issue by Mrwangfan** [youzan/vant#8304]
### 这个功能解决了什么问题
可以让用户知道目前在第几页了和共多少条数据 体验效果更佳

### 描述您想要的解决方案
类似于jd 这个  https://so.m.jd.com/ware/search.action?keyword=零食%20京东超市#listMode=1
![image](https://user-images.githubusercontent.com/22339042/110287175-091b6b00-8021-11eb-9ef5-e8333dd32e69.png)

### 建议的API是什么样的
list 列表一起就可以

**Comment by chenjiahan** [comment]
暂无计划支持喔，建议自行实现
