### ISSUE TITLE
[Bug Report] 按需引入Button组件报错

### ISSUE THREAD

**Issue by s7venteen** [youzan/vant#8305]
### Vant 版本
3.0.8
###  Vue 版本
3.0.0
### 描述问题
按需引入Button组件报错

![1615187483(1)](https://user-images.githubusercontent.com/75529848/110287950-403e4c00-8022-11eb-80a6-47fa9686b4a6.jpg)

**Comment by chenjiahan** [comment]
已在 3.0.9 版本修复
