### ISSUE TITLE
[Bug Report] DropdownMenu下拉菜单显示异常，在带animated属性的Tab 标签页中

### ISSUE THREAD

**Issue by proper128** [youzan/vant#8307]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.8

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-c2n5s?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-c2n5s?file=/src/App.vue</a>

### 描述问题
现象：DropdownMenu下拉菜单显示异常；
重现步骤：Tab 标签页，使用了 切换动画属性 animated，并且Tab 标签页内容有 DropdownMenu 下拉菜单组件，会导致下拉菜单显示异常！

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/8185
