### ISSUE TITLE
AddressEdit 地址编辑 cdn引用方式使用有问题

### ISSUE THREAD

**Issue by zlyinfo** [youzan/vant#831]
示例页面 https://jsfiddle.net/eywraw8t/21938/
保存时，值没有改变

**Comment by chenjiahan** [comment]
正确使用姿势是通过 save 事件回调函数的第一个参数去拿到表单内容，你传入的 addressInfo 只是一个初始值喔

**Comment by zlyinfo** [comment]
但是为什么以前的版本0.12.11，可以直接取到

**Comment by chenjiahan** [comment]
@zlyinfo 以前的版本会对初始值进行修改，这其实是一个错误的做法，在后面的版本修复了这个问题

**Comment by zlyinfo** [comment]
好的，明白了，谢谢
