### ISSUE TITLE
[Bug Report] Field 输入框在 readonly 或 disabled 状态下，无法监听 input 事件

### ISSUE THREAD

**Issue by minspy** [youzan/vant#8312]
### 设备 / 浏览器
All

### Vant 版本
2.9.3

### Vue 版本
2.6.12

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-44xhw?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-44xhw?file=/src/App.vue</a>

### 描述问题
Field 输入框在 readonly 或 disabled 状态下，当值改变时， input 事件无法执行

**Comment by chenjiahan** [comment]
这个是符合预期的，如果想监听值的改变，可以通过 watch 来监听

**Comment by chenjiahan** [comment]
get👌
