### ISSUE TITLE
[Bug Report] van-radio 选中状态不显示

### ISSUE THREAD

**Issue by JackSengKing** [youzan/vant#8316]
### 设备 / 浏览器
浏览器

### Vant 版本
2.12.9

### Vue 版本
2.6.11

### 重现链接
无链接

### 描述问题
当我使用npm install   vant 2.12.9版本代码时，发现 van-radio 选中状态不显示，但是  使用 2.8.0版本时，是可以的
![image](https://user-images.githubusercontent.com/29450408/110439749-cc1fa900-80f2-11eb-8fb2-8dbf5d8224b1.png)

**Comment by chenjiahan** [comment]
麻烦提供下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by xie4hao** [comment]
> 麻烦提供下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

我也碰到了，请问有解决方案吗？
