### ISSUE TITLE
[Bug Report] 级联选择 市级 视图 不出现 

### ISSUE THREAD

**Issue by PlayGuitar-CoderQ** [youzan/vant#8320]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.12.9

### Vue 版本
3.0.7

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/cascader" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/cascader</a>

### 描述问题
级联选择组件： 前两个例子：基础用法 和 自定义颜色 两个例子， 选择省之后到市级选择，但是市级并未出现，而是空白一片，打开检查，可以发现，url 下面的 span标签是空的，但是点击空白的span部分却有市级数据显示在input里，所以可能是没有渲染出来

**Comment by nemo-shen** [comment]
应该是deepClone有问题，没有完成深拷贝 `src/cascader/demo/index.vue line 192`

实际使用应该不会遇到这样的问题

**Comment by chenjiahan** [comment]
已修复
