### ISSUE TITLE
[Bug Report] Calendar type=range触发select事件后得到的value，在vant2和vant3中有不同的表现

### ISSUE THREAD

**Issue by nemo-shen** [youzan/vant#8328]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.9

### Vue 版本
3.0.7

### 描述问题
我正在为vant3的Calendar组件增加测试用例，但是当我在调整`select event when type is range`这个测试用例的时候发现，select事件似乎在vant2和vant3中的表现有点不太一样

**在vant2中**
第一次点击，select事件返回`[Date, null]`
第二次点击，select事件返回`[Date, Date]`

***在vant3中**
第一次点击，select事件返回`[Date]`
第二次点击，select事件返回`[Date, Date]`

#### 🤔所以有几个疑问
1. vant3中的改动是更好的处理方式吗？是基于什么考虑，将null占位值去掉了呢？
2. 我应该调整vant3组件中select事件的代码还是调整测试用例以兼容新版本的select事件呢？

#### 🧐我的思考
由于vant3和vant2在这一部分的文档描述是相同的，而实际表现并不相同，在`从2.x迁移`的迁移指南中也并未提及。**这是否可能对原先开发者或者想要从2.x迁移的应用造成影响**

**Comment by chenjiahan** [comment]
1. vant3中的改动是更好的处理方式吗？是基于什么考虑，将null占位值去掉了呢？

去掉 null 主要是为了保证 select 事件参数的类型一致性，即抛出 `Data[]` 而不是 `Array<Date | null>`

2. 我应该调整vant3组件中select事件的代码还是调整测试用例以兼容新版本的select事件呢？

修改测试用例即可~

3. 从2.x迁移的迁移指南中也并未提及

迁移指南中确实遗漏了这部分，欢迎在 PR 中帮忙加上~
