### ISSUE TITLE
Bug：Popup弹出层 滚动穿透至父层

### ISSUE THREAD

**Issue by Rickykurt** [youzan/vant#833]
**What is the current behavior?**
1.父层使用List组件，单击List中的cell
2.弹出全屏popup，popup中有一个cell 单击这个cell
3.弹出80%宽度的popup，然后点击遮罩，80%popup消失，List组件滚动条出现
模拟代码见：https://jsfiddle.net/chromeos/LgL93qty/1/ 
具体表现见附件动图
![untitled](https://user-images.githubusercontent.com/1176984/38464235-82e9fdca-3b3c-11e8-8aba-1f7c2cf8a5ac.gif)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/chromeos/LgL93qty/1/ or similar.**

**What is the expected behavior?**
弹出80%宽度的popup，然后点击遮罩，80%popup消失，List组件滚动条不出现
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
目前在弹出多个 popup 的时候，lock-scroll 属性确实存在问题，会在下个版本进行修复

**Comment by Rickykurt** [comment]
目前使用的策略是 
将需要popup的组件改为自定义子组件调用 
子组件destroyed的时候给body赋回 van-overflow-hidden 的class
不知道官方有没有什么更好的建议

**Comment by chenjiahan** [comment]
已在 1.0.4 版本修复，可以升级试试

**Comment by chenjiahan** [comment]
iOS 下仍存在可滚动的问题
