### ISSUE TITLE
List 列表 瀑布流滚动加载

### ISSUE THREAD

**Issue by zhweb** [youzan/vant#834]
![Uploading image.png…]()
![Uploading b79c9121a849586433a015ca190f4da.png…]()
这是我的JS部门
![Uploading image.png…]()
页面布局部分
![Uploading image.png…]()
JSON格式
接下来才是重点
![Uploading image.png…]()
我console了一次 打印了三遍
![Uploading image.png…]()
请求数据请求了三遍

**Comment by zhweb** [comment]
没有图。。。  我重新在后面发一次吧
![_20180408163926](https://user-images.githubusercontent.com/20854070/38465214-d1a14d74-3b4b-11e8-961e-b49d48c5e35f.png)
![_20180408164003](https://user-images.githubusercontent.com/20854070/38465217-d6540e92-3b4b-11e8-82c0-518f2d247036.png)
这个是我的JS部分
![image](https://user-images.githubusercontent.com/20854070/38465246-fbfcf2a8-3b4b-11e8-8b60-bbf5dcf1eedc.png)
页面布局方面
![image](https://user-images.githubusercontent.com/20854070/38465253-19712886-3b4c-11e8-9438-631f29f5a5a9.png)
JSON格式
接下来才是重点
![2](https://user-images.githubusercontent.com/20854070/38465379-817bf2e8-3b4d-11e8-8a88-152646e81708.png)
![3](https://user-images.githubusercontent.com/20854070/38465386-8a4773d4-3b4d-11e8-9225-3def99d19839.png)

请求数据请求了三遍

**Comment by chenjiahan** [comment]
能否提供一个复现问题的 jsfiddle
