### ISSUE TITLE
[Bug Report] ImagePreview设置startPosition，在多个组件间切换预览时图片不能预览

### ISSUE THREAD

**Issue by BlackJackSen** [youzan/vant#8341]
### 设备 / 浏览器
iphonex，安卓机，谷歌浏览器等等 

### Vant 版本
2.12.9

### Vue 版本
3.0.7

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/image-preview" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/image-preview</a>

### 描述问题
1.问题前提封装了一个共用组件，此组件被项目v-for 循环复用N次，每个单独的里面会有不能数量图片
举例组件被复用三次，分别命名为A 和B 和C
A有一张图 A1，B有2张图 B1  B2 ， C有4张图 C1  C2 C3 C4
问题描述:点击B2之后点击A1图片无法显示，如果再次点击B1之后返回再次点击A1图片可以正常显示，B和C之间不出现预览异常的问题
总结：只要点击一个组件上的非0索引的图片再点击单张图的时候加载会出现异常
设置了startPosition参数 之后会出现以上描述问题
            var instance = ImagePreview({
                images: imageArry,
                closeable: true,
                startPosition: index
            });
![image](https://user-images.githubusercontent.com/50441255/111094627-a4a76100-8576-11eb-86bf-29377d2151d8.png)

**Comment by BlackJackSen** [comment]
![image](https://user-images.githubusercontent.com/50441255/111249087-18646f00-8646-11eb-9e01-20ca9831f52f.png)
求大佬指点

**Comment by BlackJackSen** [comment]
<template>
    <span @click="showTitle">点击我</span>
    <van-dialog v-model="showDig" title="标题">
        <img src="https://img01.yzcdn.cn/vant/apple-3.jpg" />
    </van-dialog>
</template>

<script>
import { ref, onMounted } from 'vue';
import { Dialog } from 'vant';
export default {
    props: {
        objData: {
            type: Array,
            defaule: []
        },
        startIndex: {
            type: Number,
            defaule: undefined
        }
    },
    components: {
        [Dialog.Component.name]: Dialog.Component
    },
    setup(props) {
        const showDig = ref(true);
        const imageList = ref([
            'https://img01.yzcdn.cn/vant/apple-1.jpg',
            'https://img01.yzcdn.cn/vant/apple-2.jpg',
            'https://img01.yzcdn.cn/vant/apple-3.jpg',
            'https://img01.yzcdn.cn/vant/apple-4.jpg'
        ]);
        const showTitle = () => {
            console.log([Dialog.Component.name]); //输出内容  ["van-dialog"]
            showDig.value = true;
            console.log(showDig.value); /// 输出内容 true
        };
        onMounted(() => {});
        return {
            imageList,
            showDig,
            showTitle
        };
    }
};
</script>
--------------
以上按照官网说明引入使用 并未有任何弹框效果，也没有错误提示。另外建议官方文档写的尽量详细一些，对于小白来说真的很伤脑筋

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by BlackJackSen** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

-------------------------------
直接用我写的demo试一下吧，复现率100%，不知道是不是我写的有问题，组件调用方式没有问题，仅函数调用
-------------------------------
<template>
    <div>
        <template v-for="(itemc, indexc) in imgs" :key="indexc">
            <van-image
                @click="viewImages(itemc, index)"
                fit="cover"
                radius="14px"
                style="height: 200px;"
                v-for="(item, index) in itemc"
                :key="index"
                :src="item"
            />
        </template>
    </div>
</template>

<script>
import { ref, reactive, onMounted } from 'vue';
import { Image as VanImage } from 'vant';
import { ImagePreview } from 'vant';
export default {
    components: {
        [VanImage.name]: VanImage
    },
    setup() {
        const imgs = ref([
            ['https://img.yzcdn.cn/vant/apple-1.jpg', 'https://img.yzcdn.cn/vant/apple-2.jpg'],
            ['https://img.yzcdn.cn/vant/apple-1.jpg']
        ]);
        const viewImages = (imageArry, index) => {
            var instance = ImagePreview({
                images: imageArry,
                closeable: true,
                startPosition: index
            });
        };
        onMounted(() => {});
        return {
            viewImages,
            imgs
        };
    }
};
</script>

**Comment by BlackJackSen** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f
------------------------------------------------------
直接用我写的demo试一下吧，复现率100%，不知道是不是我写的有问题，组件调用方式没有问题，仅函数调用
------------------------------------------------------
<template>
    <div>
        <template v-for="(itemc, indexc) in imgs" :key="indexc">
            <van-image
                @click="viewImages(itemc, index)"
                fit="cover"
                radius="14px"
                style="height: 200px;"
                v-for="(item, index) in itemc"
                :key="index"
                :src="item"
            />
        </template>
    </div>
</template>

<script>
import { ref, reactive, onMounted } from 'vue';
import { Image as VanImage } from 'vant';
import { ImagePreview } from 'vant';
export default {
    components: {
        [VanImage.name]: VanImage
    },
    setup() {
        const imgs = ref([
            ['https://img.yzcdn.cn/vant/apple-1.jpg', 'https://img.yzcdn.cn/vant/apple-2.jpg'],
            ['https://img.yzcdn.cn/vant/apple-1.jpg']
        ]);
        const viewImages = (imageArry, index) => {
            var instance = ImagePreview({
                images: imageArry,
                closeable: true,
                startPosition: index
            });
        };
        onMounted(() => {});
        return {
            viewImages,
            imgs
        };
    }
};
</script>

**Comment by BlackJackSen** [comment]
> > 麻烦提供一下 codesandbox 复现链接
> > https://codesandbox.io/s/m5v3f
> 
> ## 直接用我写的demo试一下吧，复现率100%，不知道是不是我写的有问题，组件调用方式没有问题，仅函数调用
> <template>
    <div>
        <template v-for="(itemc, indexc) in imgs" :key="indexc">
            <van-image
                @click="viewImages(itemc, index)"
                fit="cover"
                radius="14px"
                style="height: 200px;"
                v-for="(item, index) in itemc"
                :key="index"
                :src="item"
            />
        </template>
    </div>
</template>

**Comment by BlackJackSen** [comment]
> > > 麻烦提供一下 codesandbox 复现链接
> > > https://codesandbox.io/s/m5v3f
> > 
> > 
> > ## 直接用我写的demo试一下吧，复现率100%，不知道是不是我写的有问题，组件调用方式没有问题，仅函数调用
> > 
> > 
> > ```
> > <div>
> >     <template v-for="(itemc, indexc) in imgs" :key="indexc">
> >         <van-image
> >             @click="viewImages(itemc, index)"
> >             fit="cover"
> >             radius="14px"
> >             style="height: 200px;"
> >             v-for="(item, index) in itemc"
> >             :key="index"
> >             :src="item"
> >         />
> >     </template>
> > </div>
> > ```

<script>
import { ref, reactive, onMounted } from 'vue';
import { Image as VanImage } from 'vant';
import { ImagePreview } from 'vant';
export default {
    components: {
        [VanImage.name]: VanImage
    },
    setup() {
        const imgs = ref([
            ['https://img.yzcdn.cn/vant/apple-1.jpg', 'https://img.yzcdn.cn/vant/apple-2.jpg'],
            ['https://img.yzcdn.cn/vant/apple-1.jpg']
        ]);
        const viewImages = (imageArry, index) => {
            var instance = ImagePreview({
                images: imageArry,
                closeable: true,
                startPosition: index
            });
        };
        onMounted(() => {});
        return {
            viewImages,
            imgs
        };
    }
};
</script>

**Comment by BlackJackSen** [comment]
> > > 麻烦提供一下 codesandbox 复现链接
> > > https://codesandbox.io/s/m5v3f
> > 
> > 
> > ## 直接用我写的demo试一下吧，复现率100%，不知道是不是我写的有问题，组件调用方式没有问题，仅函数调用
> > 
> > 
> > ```
> > <div>
> >     <template v-for="(itemc, indexc) in imgs" :key="indexc">
> >         <van-image
> >             @click="viewImages(itemc, index)"
> >             fit="cover"
> >             radius="14px"
> >             style="height: 200px;"
> >             v-for="(item, index) in itemc"
> >             :key="index"
> >             :src="item"
> >         />
> >     </template>
> > </div>
> > > ><script>
> >import { ref, reactive, onMounted } from 'vue';
> >import { Image as VanImage } from 'vant';
> >import { ImagePreview } from 'vant';
> >export default {
> >    components: {
> >        [VanImage.name]: VanImage
> >    },
> >    setup() {
> >        const imgs = ref([
> >            ['https://img.yzcdn.cn/vant/apple-1.jpg', 'https://img.yzcdn.cn/vant/apple-2.jpg'],
> >            ['https://img.yzcdn.cn/vant/apple-1.jpg']
> >        ]);
> >        const viewImages = (imageArry, index) => {
> >            var instance = ImagePreview({
> >                images: imageArry,
> >                closeable: true,
> >                startPosition: index
> >            });
> >        };
> >        onMounted(() => {});
> >        return {
> >            viewImages,
> >            imgs
> >        };
> >    }
> >};
> ></script>

**Comment by BlackJackSen** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f
------------------------------------------------
直接用我写的demo试一下吧，复现率100%，不知道是不是我写的有问题，组件调用方式没有问题，仅函数调用
------------------------------------------------
> ><template>
> >    <div>
> >        <template v-for="(itemc, indexc) in imgs" :key="indexc">
> >            <van-image
> >                @click="viewImages(itemc, index)"
> >                fit="cover"
> >                radius="14px"
> >                style="height: 200px;"
> >                v-for="(item, index) in itemc"
> >                :key="index"
> >                :src="item"
> >            />
> >        </template>
> >    </div>
> ></template>
> ><script>
> >import { ref, reactive, onMounted } from 'vue';
> >import { Image as VanImage } from 'vant';
> >import { ImagePreview } from 'vant';
> >export default {
> >    components: {
> >        [VanImage.name]: VanImage
> >    },
> >    setup() {
> >        const imgs = ref([
> >            ['https://img.yzcdn.cn/vant/apple-1.jpg', 'https://img.yzcdn.cn/vant/apple-2.jpg'],
> >            ['https://img.yzcdn.cn/vant/apple-1.jpg']
> >        ]);
> >        const viewImages = (imageArry, index) => {
> >            var instance = ImagePreview({
> >                images: imageArry,
> >                closeable: true,
> >                startPosition: index
> >            });
> >        };
> >        onMounted(() => {});
> >        return {
> >            viewImages,
> >            imgs
> >        };
> >    }
> >};
> ></script>

**Comment by BlackJackSen** [comment]
> > 麻烦提供一下 codesandbox 复现链接
> > https://codesandbox.io/s/m5v3f
> 
> ## 直接用我写的demo试一下吧，复现率100%，不知道是不是我写的有问题，组件调用方式没有问题，仅函数调用
> > > <script>
> > > import { ref, reactive, onMounted } from 'vue';
> > > import { Image as VanImage } from 'vant';
> > > import { ImagePreview } from 'vant';
> > > export default {
> > >    components: {
> > >        [VanImage.name]: VanImage
> > >    },
> > >    setup() {
> > >        const imgs = ref([
> > >            ['https://img.yzcdn.cn/vant/apple-1.jpg', 'https://img.yzcdn.cn/vant/apple-2.jpg'],
> > >            ['https://img.yzcdn.cn/vant/apple-1.jpg']
> > >        ]);
> > >        const viewImages = (imageArry, index) => {
> > >            var instance = ImagePreview({
> > >                images: imageArry,
> > >                closeable: true,
> > >                startPosition: index
> > >            });
> > >        };
> > >        onMounted(() => {});
> > >        return {
> > >            viewImages,
> > >            imgs
> > >        };
> > >    }
> > > };
> > > </script>
> ><template>
> >    <div>
> >        <template v-for="(itemc, indexc) in imgs" :key="indexc">
> >            <van-image
> >                @click="viewImages(itemc, index)"
> >                fit="cover"
> >                radius="14px"
> >                style="height: 200px;"
> >                v-for="(item, index) in itemc"
> >                :key="index"
> >                :src="item"
> >            />
> >        </template>
> >    </div>
> ></template>

**Comment by BlackJackSen** [comment]
-----------------------
直接用下面这个demo就行，组件调用方式没问题，仅函数调用出现异常
-----------------------
<template>
    <div>
        <template v-for="(itemc, indexc) in imgs" :key="indexc">
            <van-image
                @click="viewImages(itemc, index)"
                fit="cover"
                radius="14px"
                style="height: 200px;"
                v-for="(item, index) in itemc"
                :key="index"
                :src="item"
            />
        </template>
    </div>
</template>

<script>
import { ref, reactive, onMounted } from 'vue';
import { Image as VanImage } from 'vant';
import { ImagePreview } from 'vant';
export default {
    components: {
        [VanImage.name]: VanImage
    },
    setup() {
        const imgs = ref([
            ['https://img.yzcdn.cn/vant/apple-1.jpg', 'https://img.yzcdn.cn/vant/apple-2.jpg'],
            ['https://img.yzcdn.cn/vant/apple-1.jpg']
        ]);
        const viewImages = (imageArry, index) => {
            var instance = ImagePreview({
                images: imageArry,
                closeable: true,
                startPosition: index
            });
        };
        onMounted(() => {});
        return {
            viewImages,
            imgs
        };
    }
};
</script>


> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

**Comment by BlackJackSen** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

<template>
    <div>
        <template v-for="(itemc, indexc) in imgs" :key="indexc">
            <van-image
                @click="viewImages(itemc, index)"
                fit="cover"
                radius="14px"
                style="height: 200px;"
                v-for="(item, index) in itemc"
                :key="index"
                :src="item"
            />
        </template>
    </div>
</template>

**Comment by BlackJackSen** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

<template>
    <div>
        <template v-for="(itemc, indexc) in imgs" :key="indexc">
            <van-image
                @click="viewImages(itemc, index)"
                fit="cover"
                radius="14px"
                style="height: 200px;"
                v-for="(item, index) in itemc"
                :key="index"
                :src="item"
            />
        </template>
    </div>
</template>

**Comment by BlackJackSen** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f
 
    <div>
        <template v-for="(itemc, indexc) in imgs" :key="indexc">
            <van-image
                @click="viewImages(itemc, index)"
                fit="cover"
                radius="14px"
                style="height: 200px;"
                v-for="(item, index) in itemc"
                :key="index"
                :src="item"
            />
        </template>
    </div>

**Comment by peachapp** [comment]
你好 你在浏览器上也会有这个问题吗

**Comment by BlackJackSen** [comment]
> 你好 你在浏览器上也会有这个问题吗

有这个问题，你copy下上面我提供的demo代码试下,我上面的代码运行环境
 "vant": "^3.0.6", "vue": "^3.0.0",chrom 版本 83.0.4103.97（正式版本） （32 位）

**Comment by weiyuc** [comment]
duplicate #8060 
3.0.7已经修复这个问题了

**Comment by peachapp** [comment]
> > 你好 你在浏览器上也会有这个问题吗
> 
> 有这个问题，你copy下上面我提供的demo代码试下,我上面的代码运行环境
> "vant": "^3.0.6", "vue": "^3.0.0",chrom 版本 83.0.4103.97（正式版本） （32 位）

根据你的提示确实可以复现出问题，不过我用的不是这个版本，而且我的问题是偶现的。。你这个问题在新版本已经修复了，已经用到vue3了啊，好用吗？

**Comment by BlackJackSen** [comment]
> > > 你好 你在浏览器上也会有这个问题吗
> > 
> > 
> > 有这个问题，你copy下上面我提供的demo代码试下,我上面的代码运行环境
> > "vant": "^3.0.6", "vue": "^3.0.0",chrom 版本 83.0.4103.97（正式版本） （32 位）
> 
> 根据你的提示确实可以复现出问题，不过我用的不是这个版本，而且我的问题是偶现的。。你这个问题在新版本已经修复了，已经用到vue3了啊，好用吗？

vue3好用，写起来代码简洁很多，加上ts,很多模块组件化封装管理，方便很多。基本上封装出来项目中常用的模块之后，单个页面上面基本不怎么写JS部分的代码。
