### ISSUE TITLE
[Feature Request] vant-cli 支持 PC 组件预览

### ISSUE THREAD

**Issue by HaoChuan9421** [youzan/vant#8342]
### 这个功能解决了什么问题
目前 vant-cli 生成的项目只支持在右侧手机模拟器里预览移动端组件，对于开发 PC 端组件来说，这个预览区就显得有些局促了，需要支持编写文档的同时，能在文档区域实时预览 PC 的 Demo 代码。

### 描述您想要的解决方案
优化 vant-markdown-loader，支持在 README 文档中，引入 demo 文件

### 建议的API是什么样的
`<demo-code>demo/MyDemo.vue</demo-code>`

**Comment by chenjiahan** [comment]
已发布 @vant/cli 2.9.0 & 3.7.0 版本

👏
