### ISSUE TITLE
[Bug Report] 在vite项目中按需导入修改主题不生效

### ISSUE THREAD

**Issue by wozien** [youzan/vant#8344]
### 设备 / 浏览器
chrome 89

### Vant 版本
3.0.9

### Vue 版本
3.0.7

### 重现链接
<a href="https://github.com/anncwb/vite-plugin-style-import/issues/10" target="_blank">https://github.com/anncwb/vite-plugin-style-import/issues/10</a>

### 描述问题
在项目导出的组件样式中，es和lib对应的less不一致：
比如在lib中按钮的less， vant/lib/button/style/less.js:

"use strict";

require('../../style/base.less');

require('../../badge/index.less');

require('../../icon/index.less');

require('../../cell/index.less');

require('../index.less');

在es中， vant/es/button/style/less.js:

import '../../style/base.css';
import '../../badge/index.css';
import '../../icon/index.css';
import '../../cell/index.css';
import '../index.css';

为啥不是导入less？

**Comment by chenjiahan** [comment]
这个问题已经在 3.0.9 修复咯
