### ISSUE TITLE
[Bug Report] DatetimePicker 

### ISSUE THREAD

**Issue by cocomilk2012** [youzan/vant#8347]
### 设备 / 浏览器
IOS

### Vant 版本
2.12.9

### Vue 版本
2.6.12

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/datetime-picker#dai-ma-yan-shi" target="_blank">https://youzan.github.io/vant/#/zh-CN/datetime-picker#dai-ma-yan-shi</a>

### 描述问题
v-model="currentDate"
currentDate: new Date(),

显示的不是当时的时间。

**Comment by chenjiahan** [comment]
重现链接无效。

**Comment by cocomilk2012** [comment]
![image](https://user-images.githubusercontent.com/10562677/111744601-6e474a00-88c6-11eb-814d-c92dad1207b6.png)

**Comment by cocomilk2012** [comment]
上图，默认值是当前时间，可是组件中显示的并不是当前时间。

**Comment by chenjiahan** [comment]
示例代码与文档不一致导致的，后续会修复

**Comment by chenjiahan** [comment]
文档已修正
