### ISSUE TITLE
关于 postcss 的配置和版本问题

### ISSUE THREAD

**Issue by Tyh2001** [youzan/vant#8357]
## 关于 postcss 的配置和版本问题

在之前我曾经写的项目中，通过 `postcss` 官方文档的指令安装，可以直接在项目中使 px 转换为 rem，但是昨天（2021-3-15），通过官网的安装命令：

```shell
npm install postcss postcss-pxtorem --save-dev
```

安装只后又在项目的根目录创建了 `postcss.config.js` 配置文件，代码如下：

```js
module.exports = {
    plugins: {
        autoprefixer: {
            browsers: ['Android >= 4.0', 'iOS >= 8']
        },
        'postcss-pxtorem': {
            rootValue: 37.5,
            propList: ['*']
        }
    }
}
```

> 注：是直接在 Vant 官网下面的基本配置中复制的代码

但是这样配置会报错，附图：

<img src="http://r.photo.store.qq.com/psc?/V52OzcjM296N4D3IEo5e1DfOQZ2trftl/45NBuzDIW489QBoVep5mcUSLdmYfYKDVzYGS4oiRFXRTG4fmlUCP4UmuJGPgd0wAJk9piIvQ9GHrx8YOoyw*Fes7pyaeyjqDorSsDeeBPiA!/r" alt="img" style="zoom:50%;" />

<img src="http://r.photo.store.qq.com/psc?/V52OzcjM296N4D3IEo5e1DfOQZ2trftl/45NBuzDIW489QBoVep5mcUSLdmYfYKDVzYGS4oiRFXS3RJjaO.sMopoHfedE1apH2L4X.9TueKNBds1ttRtB5drIl69h4n7Qr4eE2loRI58!/r" alt="img" style="zoom:50%;" />

上图可见，最新的安装命令可以直接安装两个包

但是项目启动之后就会报错

<img src="http://r.photo.store.qq.com/psc?/V52OzcjM296N4D3IEo5e1DfOQZ2trftl/45NBuzDIW489QBoVep5mcQzKx8IQpl6cGJ5zJ3wsvJw9eQcZeqkTNAucTpD3doSMklwIjtdhjjojEzrFqSKgQSgiBQJRaB1iFaOA70OJfuc!/r" alt="img" style="zoom:50%;" />

经过反复的尝试，最终得到解决方式为：

之前下载的两个包，改为以下的一个包，和以下的版本，并重新安装依赖即可解决问题

<img src="http://r.photo.store.qq.com/psc?/V52OzcjM296N4D3IEo5e1DfOQZ2trftl/45NBuzDIW489QBoVep5mcQzKx8IQpl6cGJ5zJ3wsvJzgyUU85I2NpLIPMNAjaPlpHtgH9NerFJ7*UXGGIr5F7Hv2nFcleY4sFu7uPRclWmM!/r" alt="img" style="zoom:50%;" />

我不清楚是什么原因造成的，但是通过这样不友好的方式解决的。。。

**建议：**

在 Vant 官网能够有更加详细的 PostCSS 配置方法，只是丢出一段代码，也没有说明放在哪个目录下、创建什么文件、文件名是什么。

既然写了，就希望可以写的更详细一点，对于新手来讲，根本不知道往哪里写这个代码

希望建议能得到采用

希望 Vant 变得更好！

反馈邮箱：1469442737@qq.com

**Comment by Zclhlmgqzc** [comment]
跟 vant 没关系 postcss 8 的 postcss-loader 依赖 webpack 5

**Comment by chenjiahan** [comment]
楼上正解，另外我们有提供示例仓库：https://github.com/youzan/vant-demo，可以作为参考
