### ISSUE TITLE
tab默认加载active延伸全部拉通了1.0.3版本

### ISSUE THREAD

**Issue by xcondor** [youzan/vant#836]
截图如下：
![image](https://user-images.githubusercontent.com/3349113/38468158-c5713aea-3b74-11e8-8e7c-dfb2f5e9787d.png)

<div class="tabs">
    <van-tabs swipeable :active="active" v-if="tabType.length" sticky>
            <van-tab v-for="item in tabType" :title="item.text">
                <order-items></order-items>
                <order-empty></order-empty>
            </van-tab>
    </van-tabs>
</div>
代码如下。

**Comment by chenjiahan** [comment]
麻烦贴一下复现代码

**Comment by VenusPP** [comment]
会不会是有页面使用tab组件样式上做了调整,到此页面时tab的样式被覆盖了

**Comment by xcondor** [comment]
外层没有样式限制啊
`<div class="tabs">
    <van-tabs @click="handlerTabClick" swipeable sticky>
        <van-tab v-for="item in tabType" :title="item.text" :key="item.tab">
        </van-tab>
    </van-tabs>
    <order-items :order-data="orderList"></order-items>
    <div v-show="isData">
        <order-empty></order-empty>
    </div>
</div>
`
代码调用就是这样。点击一次就恢复了。就是默认加载进来的时候出现的这个问题。

**Comment by chenjiahan** [comment]
未复现的问题
