### ISSUE TITLE
[Bug Report] Calendar组件，IOS真机上，初次打开空白没有显示日期，需要动一下才显示

### ISSUE THREAD

**Issue by K0rbin** [youzan/vant#8361]
### 设备 / 浏览器
夸克浏览器，微信端

### Vant 版本
2.10.9

### Vue 版本
2.6.12

### 重现链接
<a href="https://qooqv.csb.app/" target="_blank">https://qooqv.csb.app/</a>

### 描述问题
Calendar组件，IOS真机上，初次打开空白没有显示日期，需要动一下才显示
安卓上正常
<a href="https://codesandbox.io/s/vant-issue-moban-forked-qooqv?file=/src/App.vue"  target="_blank">代码地址</a>

**Comment by chenjiahan** [comment]
iphoneXR 未复现，如果你的 vant 版本是 2.10.9 的话，建议升级到最新版试下

**Comment by K0rbin** [comment]
> iphoneXR未复现，如果你的vant版本是2.10.9的话，建议升级到最新版试下

奇怪，现在这个链接在我手机现在也重现不了，但是我项目里就是更新到`latest`版本更新到线上还是有该问题，我有空的时候再看看

**Comment by K0rbin** [comment]
> iphoneXR未复现，如果你的vant版本是2.10.9的话，建议升级到最新版试下

奇怪，现在这个链接在我手机现在也重现不了，但是我项目里就是更新到`latest`(2.12.9)版本更新到线上还是有该问题，我有空的时候再看看

**Comment by chenjiahan** [comment]
好的

**Comment by FoooooooF** [comment]
我用的ios vant2.12.20也有这个问题

**Comment by yangtoude** [comment]
我也复现这个问题了

iPhone 8P ios 11.4 无问题
ios13.3.1 iphoneXR 有问题
ios 16.0.2 iphone 11 Pro Max 有问题
