### ISSUE TITLE
[Bug Report] popup组件在接口请求后变为true，但是弹出层闪消失了

### ISSUE THREAD

**Issue by woodThunder** [youzan/vant#8372]
### 设备 / 浏览器
百度app

### Vant 版本
2.11.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://activeuat.feihe.com/test/index.html#/test" target="_blank">https://activeuat.feihe.com/test/index.html#/test</a>

### 描述问题
进入页面调用接口，根据返回数据显示popup弹出层，弹出层闪消失;isInactivePeriod默认false，
<van-popup v-model="isInactivePeriod" round :close-on-click-overlay='false' :lock-scroll="false"></van-popup>
getAvailability() {
                getAvailabilityAPI({activeId: this.activeId}).then(res => {
                    // console.log(res,'获取时间段')
                    if (res.status == '0') {this.isInactivePeriod=true}})}

其他点击按钮弹出popup不闪退

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by woodThunder** [comment]
https://codesandbox.io/s/vant-issue-moban-forked-p5mp4这是复现链接，亲测没有问题，但是我的项目还是不行https://activeuat.feihe.com/test/index.html#/test大概逻辑也是在created里面调用接口，赋值显示弹窗

**Comment by chenjiahan** [comment]
项目里不行的话，建议自行排查下，是否为用法问题，或者其他逻辑对组件产生了干扰。

**Comment by woodThunder** [comment]
百度app popup组件闪退问题，已经解决，在popup组建内有class类名为”close“的元素，更改class类名即可。
