### ISSUE TITLE
[Bug Report] van-nav-bar 与 van-tabs 吸顶冲突

### ISSUE THREAD

**Issue by DarkLove** [youzan/vant#8373]
### 设备 / 浏览器
google浏览器

### Vant 版本
2.12.9

### Vue 版本
2.6.12

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-qtj6m?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-qtj6m?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
van-nav-bar  fixed 与 van-tabs  sticky 吸顶冲突， van-nav-bar 被van-tabs遮挡，正 常的需求应该是
tabs的吸顶应该在van-nav-bar的下方。这个问题希望解决一下。

**Comment by chenjiahan** [comment]
设置 offset-top 属性即可

```html
<van-tabs sticky offset-top="44">
```
