### ISSUE TITLE
vue3项目 toast使用问题：如何全局引入toast

### ISSUE THREAD

**Issue by hyoukaija** [youzan/vant#8380]
看官网写着可以全局引入Toast
import { Toast } from 'vant'
app.use(Toast)

在setup中使用时：
Toast('hi') 
报错，Toast找不到
这里全局引入怎么可以直接使用呢

**Comment by hyoukaija** [comment]
补充
在单页中引入
import { Toast } from 'vant' 
之后可以使用，但是这样全局引入不是没有意义了，而且每次都引入还很麻烦

**Comment by chenjiahan** [comment]
在 setup 内只能通过 import 引入喔，因为 setup 内没有 this，只能通过这种方式引入
