### ISSUE TITLE
[Bug Report] van-list 内容用slot填充 无法检测到高度，导致不会触发load

### ISSUE THREAD

**Issue by w550** [youzan/vant#8384]
### 设备 / 浏览器
chrome 最新版 

### Vant 版本
2.12.10

### Vue 版本
2.6.11

### 重现链接
<a href="https://jsbin.com/guqovamiro/edit?html,output" target="_blank">https://jsbin.com/guqovamiro/edit?html,output</a>

### 描述问题
```
<van-list
        ref="list"
        v-model="currentLoading"
        :finished="finished"
        finished-text="没有更多了"
        :error.sync="error"
        error-text="请求失败"
        @load="load"
    >
        <div class="van-clearfix">
            <slot></slot>
        </div>
    </van-list>
```

solt 内容是传进来的。

**Comment by chenjiahan** [comment]
List 监听的是滚动事件，如果是其他情况需要触发滚动检测的，可以手动执行组件提供的 `check` 方法

**Comment by w550** [comment]
> 列出监听的是滚动事件，如果是其他情况需要触发滚动检测的，可以手动执行组件提供的`check`方法

试了，主动check  也是不行的亲，我的解决方案，是slot 外面加个div 设置最小高度1px
