### ISSUE TITLE
[Bug Report] swipe 组件滑动会出现Cannot read property 'width' of null

### ISSUE THREAD

**Issue by ShikiNatsumeYuzu** [youzan/vant#8385]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by ShikiNatsumeYuzu** [comment]
vite环境下出现的问题，首次打开正常，刷新一次页面后就出现报错

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
