### ISSUE TITLE
在使用sku弹层的时候  van-sku-row的高度会被设置的rem影响

### ISSUE THREAD

**Issue by huixu123** [youzan/vant#839]
1.`<html style="font-size: 16px;">`的时候
    `<div class="van-sku-row">`的高度正常
![m6 _ t364_eqvd1i amgq](https://user-images.githubusercontent.com/13418365/38489571-6129b97c-3c19-11e8-8629-b6f7786a018e.png)

2.`<html style="font-size: 50px;">`
![_ e 1j_ 5jw s2bp 4e h4f](https://user-images.githubusercontent.com/13418365/38489529-425456b0-3c19-11e8-9df7-f9216ac1013e.png)

**Comment by chenjiahan** [comment]
感谢反馈，会在下个版本修复

**Comment by huixu123** [comment]
下个版本是什么时候啊？或者有什么补救的办法吗

**Comment by chenjiahan** [comment]
下个版本会在本周内发布喔，你可以在 van-sku-row 上设置 font-size 临时解决一下

**Comment by chenjiahan** [comment]
已在 1.0.4 版本修复
