### ISSUE TITLE
[Bug Report] pull-refresh严重bug

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant#8390]
### 设备 / 浏览器
手机浏览器

### Vant 版本
2.12.10

### Vue 版本
2.6.12

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/list" target="_blank">https://youzan.github.io/vant/#/zh-CN/list</a>

### 描述问题
pull-refresh组件与list组合使用实现瀑布流加载时，只能往下拉，内容列表，如果想往上翻看原来载入的列表内容，立刻触发了重刷新。

**Comment by chenjiahan** [comment]
请提供有效的 codesandbox 复现链接
