### ISSUE TITLE
[Feature Request] 希望 vant-taro 加入到 vant 家族。

### ISSUE THREAD

**Issue by tgioer** [youzan/vant#8391]
你好，Vant 组件库的大佬。
我正在开发一个 vant 的 taro 版本，希望能加入 vant 家族。

源码地址：[https://gitee.com/mallfoundry/vant-taro.git](https://gitee.com/mallfoundry/vant-taro.git)

**Comment by chenjiahan** [comment]
看了下目前组件还不是很多，可以继续完善，等有 30~40 个组件后，可以加入到官方文档站点里~
