### ISSUE TITLE
[Bug Report] vant Field formatter 格式化后会改变原来的值

### ISSUE THREAD

**Issue by fengyun2** [youzan/vant#8392]
### 设备 / 浏览器
 win10 / Chrome 89.0.4389.90

### Vant 版本
2.12.10

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/inspiring-keller-cmz4b?file=/src/App.vue" target="_blank">https://codesandbox.io/s/inspiring-keller-cmz4b?file=/src/App.vue</a>

### 描述问题
目前使用 `Field组件` 的 `formatter` 方法 会改变原来v-model的值，如果重新渲染几次，会一直改变原来的值，能否只是改变展示效果，例如filter的效果，而不是直接改变原来的值，这样会产生意想不到的情况。或者提供一个新方法可以达到这种效果。

**Comment by HZZformGD** [comment]
@fengyun2  小兄弟 可以用 :modal-value="someFormat" 我刚刚就提了一个issue  也是跟这个有关的

**Comment by fengyun2** [comment]
> @fengyun2 小兄弟 可以用 :modal-value="someFormat" 我刚刚就提了一个issue 也是跟这个有关的

@HZZformGD 你这个是Vant 3.0的语法哦

**Comment by nemo-shen** [comment]
@fengyun2 
`formatter`方法本意是`格式化用户输入的内容`。例如：我们不希望用户输入数字，如果是数字全部剔除，这时候就可以通过`formatter`对用户输入的内容进行格式化处理。可以参考官网的示例demo

我想你希望达到的效果应该是**用户输入的value不被格式化污染**，其实我们可以利用computed进行处理。
这边给你提供了一个在线demo，希望能帮助到你（实现方法有好几种，如果一定要用formatter处理也是可以做到的）

https://codesandbox.io/s/cool-resonance-xs10j?file=/src/App.vue

**Comment by fengyun2** [comment]
> @fengyun2
> `formatter`方法本意是`格式化用户输入的内容`。例如：我们不希望用户输入数字，如果是数字全部剔除，这时候就可以通过`formatter`对用户输入的内容进行格式化处理。可以参考官网的示例demo
> 
> 我想你希望达到的效果应该是**用户输入的value不被格式化污染**，其实我们可以利用computed进行处理。
> 这边给你提供了一个在线demo，希望能帮助到你（实现方法有好几种，如果一定要用formatter处理也是可以做到的）
> 
> https://codesandbox.io/s/cool-resonance-xs10j?file=/src/App.vue

我们的使用场景是，在form组件里边循环 `van-field` 组件，渲染出表单页面，这个时候有什么办法对每个字段都进行定制格式化呢，且不改变原数据。
具体demo: https://codesandbox.io/s/rough-breeze-81muo?file=/src/App.vue

**Comment by fengyun2** [comment]
> > @fengyun2
> > `formatter`方法本意是`格式化用户输入的内容`。例如：我们不希望用户输入数字，如果是数字全部剔除，这时候就可以通过`formatter`对用户输入的内容进行格式化处理。可以参考官网的示例demo
> > 我想你希望达到的效果应该是**用户输入的value不被格式化污染**，其实我们可以利用computed进行处理。
> > 这边给你提供了一个在线demo，希望能帮助到你（实现方法有好几种，如果一定要用formatter处理也是可以做到的）
> > https://codesandbox.io/s/cool-resonance-xs10j?file=/src/App.vue
> 
> 我们的使用场景是，在form组件里边循环 `van-field` 组件，渲染出表单页面，这个时候有什么办法对每个字段都进行定制格式化呢，且不改变原数据。
> 具体demo: https://codesandbox.io/s/rough-breeze-81muo?file=/src/App.vue

@nemo-shen

**Comment by nemo-shen** [comment]
@fengyun2 
我理解你所描述的场景，但是这个已经超出组件库范畴了，可能你需要通过业务代码或者产品设计去处理。

比如我给到的demo思路是通过计算属性去实现

---

**但是我个人并不建议在同一个field里面既要是format value还要是input value**
因为你会遇到一些很棘手的问题，比如：
1. 如何界定数据是被格式化过的还是未被格式化过的？
2. 如何防止格式化数据二次格式化？

因为当你input的时候你没办法确定这个值如何处理才是正确的，它的边界在哪里？
比如说

> 123万元
> 123万123元
> 123万元123

更棘手的可能是
> foo => bar
> bar => baz

bar同时可能是format value也可能是input value

### 如果一定要实现一个field可以支持format和input两种value，这边给你提供几个思路：
1. [思路1] 是否可以通过两个field，一个是readonly field，一个是input field，正常显示readonly field（显示格式化数据），用户点击之后显示input field(允许用户输入)这种方式处理？
2. [思路2] `onBlur`之后formatter，并且每次用户点击之后`自动全选`field中的value，让用户重新输入
3. [思路3] 如果并不是很复杂的format，而是加个后缀这种，可以通过`right-icon`
```vue
<van-field
  v-model="value"
  label="label"
  placeholder="placeholder"
>
  <template #right-icon>万元</template>
</van-field>
```

🌚感觉超纲回答了~

**Comment by fengyun2** [comment]
谢谢

**Comment by lizy-CZ** [comment]
明显就是个 api 设计错误，在其他UI库中 formatter 这个props 是用于 value 与 showValue 分离的，而在这里却强制改变了 value

**Comment by chenjiahan** [comment]
@lizy-CZ Vant Field 里 formatter 的定位类似于原生 input 的 pattern 属性，跟其他 UI 库的 formatter 不是一个东西。

**Comment by lizy-CZ** [comment]
> @lizy-CZ Vant Field 里 formatter 的定位类似于原生 input 的 pattern 属性，跟其他 UI 库的 formatter 不是一个东西。

这就涉及到认知问题了，使用 Vant Field formater props 99% 的人都会用错，觉得怪异，跟之前用的库不一样。这就好比微信右上角的 + 号，将 icon 换成了“我的” icon，怪异。或许可以改为 pattern ？

**Comment by chenjiahan** [comment]
不知道你这里的 99% 是怎么得出来的，目前反馈这个问题的用户非常少。

**Comment by wolfmanfxm** [comment]
> > @fengyun2
> > `formatter`方法本意是`格式化用户输入的内容`。例如：我们不希望用户输入数字，如果是数字全部剔除，这时候就可以通过`formatter`对用户输入的内容进行格式化处理。可以参考官网的示例demo
> > 我想你希望达到的效果应该是**用户输入的value不被格式化污染**，其实我们可以利用computed进行处理。
> > 这边给你提供了一个在线demo，希望能帮助到你（实现方法有好几种，如果一定要用formatter处理也是可以做到的）
> > https://codesandbox.io/s/cool-resonance-xs10j?file=/src/App.vue
> 
> 我们的使用场景是，在form组件里边循环 `van-field` 组件，渲染出表单页面，这个时候有什么办法对每个字段都进行定制格式化呢，且不改变原数据。 具体demo: https://codesandbox.io/s/rough-breeze-81muo?file=/src/App.vue

兄弟这个问题解决了吗，我现在也遇到这个问题😂，前面那个回答没get到点，想要的效果只是视图展示的码值转义，并不想改变原值啊😆

**Comment by tmaclucien** [comment]
我也遇到这个问题，目前来看用formatter无法达到展示层和输入层分离哇
