### ISSUE TITLE
[Bug Report] swiper圆点指示器# 不圆 畸形。。。

### ISSUE THREAD

**Issue by iT-lijun** [youzan/vant#8394]
设备 / 浏览器
安卓/微信&企业微信的内置浏览器

Vant 版本
3.0.7

Vue 版本
3.0.7

重现链接
https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/546d40ac81b341a18d9d0ed4edac28f8~tplv-k3u1fbpfcp-zoom-mark-crop-v2:460:460:0:0.awebp
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/546d40ac81b341a18d9d0ed4edac28f8~tplv-k3u1fbpfcp-zoom-mark-crop-v2:460:460:0:0.awebp)
描述问题
#swiper圆点指示器# 不圆 畸形。。。 个人微信&企业微信的内置浏览器&QQ浏览器都表现一致。。。

**Comment by chenjiahan** [comment]
用官方示例能复现吗？
