### ISSUE TITLE
3.0版本添加sku组件

### ISSUE THREAD

**Issue by easydowork** [youzan/vant#8396]
这么好的框架缺失了2.0版本sku可惜了,希望后续加上.

**Comment by chenjiahan** [comment]
后续会加的喔

**Comment by lixiaofa** [comment]
> 这么好的框架缺失了2.0版本sku可惜了,希望后续加上.

我迁移了vant2.x 的sku
https://www.npmjs.com/package/vant-sku?activeTab=readme
