### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by consolezt** [youzan/vant#8398]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

DatetimePicker 组件不能隐藏。

官方文档上的例子选择时间后组件没有隐藏，和input 输入框连用时 DatetimePicker 组件也不隐藏

**Comment by consolezt** [comment]
https://vant-contrib.gitee.io/vant/#/zh-CN/datetime-picker

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
