### ISSUE TITLE
[Bug Report] 当调用全局方法$toast后，在调用getCurrentInstance()返回null

### ISSUE THREAD

**Issue by iamoldli** [youzan/vant#8401]
### 设备 / 浏览器
Edge

### Vant 版本
3.0.10

### Vue 版本
3.0.7

### 重现链接
<a href="https://github.com/iamoldli/vant-demo" target="_blank">https://github.com/iamoldli/vant-demo</a>

### 描述问题
当调用全局方法$toast后，在调用getCurrentInstance()返回null，我自己添加了一个全局属性没有这个问题，不确定是不是bug

**Comment by chenjiahan** [comment]
$toast 会创建一个 Toast 组件实例并挂载到 document 上，所以 getCurrentInstance 的指向就变化了，这个应该不属于 bug，是 Vue 3 本身的机制
