### ISSUE TITLE
Form校验Field组件，错误信息异常消失

### ISSUE THREAD

**Issue by wang-ky** [youzan/vant#8402]
### 设备 / 浏览器
安卓

### Vant 版本
3.0.10

### Vue 版本
3.0.5

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-8yb7d?fontsize=14&hidenavigation=1&theme=dark&file=/src/main.js" target="_blank">https://8yb7d.csb.app/</a>

### 描述问题
设置Form组件的validate-trigger为onChange，输入校验错误之后，点击空白处，失去焦点，错误信息就消失了

**Comment by wang-ky** [comment]
不明白这里 `defaultTrigger` 为false的时候，为什么不直接return
```javascript
const validateWithTrigger = (trigger) => {
      if (form && props.rules) {
        const defaultTrigger = form.props.validateTrigger === trigger;
        const rules = props.rules.filter((rule) => {
          if (rule.trigger) {
            return rule.trigger === trigger;
          }

          return defaultTrigger;
        });

        validate(rules);
      }
    };
```

**Comment by chenjiahan** [comment]
已在 3.0.11 版本修复
