### ISSUE TITLE
[Bug Report] popup和datetime-picker一起使用时无法滚动

### ISSUE THREAD

**Issue by hyoukaija** [youzan/vant#8404]
### 设备 / 浏览器
macOS 10.15.7/Chrome 89.0.4389.90

### Vant 版本
3.0.9

### Vue 版本
3.0.7

### 重现链接
<a href="https://codepen.io/hyoukaija/pen/QWdbYMq" target="_blank">https://codepen.io/hyoukaija/pen/QWdbYMq</a>

### 描述问题
pc端在中间显示时无法滚动

**Comment by chenjiahan** [comment]
参见 [桌面端适配](https://vant-contrib.gitee.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei)
