### ISSUE TITLE
[Bug Report] Vant Cli 的2.x 热更新失败，当默认端口被占用时

### ISSUE THREAD

**Issue by hetianhe** [youzan/vant#8405]
**设备 / 浏览器**
Mac10.15.7

**版本信息**
Vant Cli 2.9.0
Vue 2.6.11

**重现步骤**
1. ` npm create vant-cli-app  `
2. 选择 vue2 并 `npm install`
3. `npm run dev`
4. 默认端口8080已被占用
5. 访问本地链接 http://localhost:8081/#/
6. 修改并保存代码

**实际结果**
修改并保存代码后不能热更新

**期望结果**
修改并保存代码后能热更新

**Comment by nemo-shen** [comment]
@hetianhe 
的确存在问题，是由于`vant-cli/src/config/webpack.site.dev.ts line 50`中的`devServer`设置了`8080`为默认端口导致的

临时的建议方案：
1. 可以kill占用8080端口的进程，8080给到vant即可正常热更新
2. 打开项目中的`node_modules/@vant/cli/lib/config/webpack.site.dev.js`大约在`line 40`找到端口号，改成想要的端口；之后重新`npm run dev`即可正常热更新

这两种方案目前都可以作为临时替代方案使用

**Comment by chenjiahan** [comment]
已在 2.9.1 版本修复，感谢 @nemo-shen 的 PR~
