### ISSUE TITLE
在vant-cli生成的组件库项目中使用vant 组件，未被编译，并且使用第三方插件等 都未编译生效，是需要怎么配置么？

### ISSUE THREAD

**Issue by houkeepmoving** [youzan/vant#8406]
1、yarn create vant-cli-app生成的项目

2、vue2.x版本

3、使用的第三方插件未生效

![CD026CCC-4C3D-4d9c-8257-75FC6F6A68FC](https://user-images.githubusercontent.com/29296595/112405977-4a648800-8d4e-11eb-9cda-6846a06389fd.png)

4、vant模板未编译成功

![3F5D8E57-7B6A-4790-BA83-CC700066E4DF](https://user-images.githubusercontent.com/29296595/112406042-61a37580-8d4e-11eb-83c2-9e0c716bc0f3.png)

5、构建后的es包下的组件

![1](https://user-images.githubusercontent.com/29296595/112406308-eb534300-8d4e-11eb-9a49-2b5a027f8263.png)

**Comment by chenjiahan** [comment]
当你使用 Vue.use 的时候，请确认你是否注册到了正确的 Vue 实例上（代码中可能打包了多份 Vue 代码）

**Comment by houkeepmoving** [comment]
> 当你使用 Vue.use 的时候，请确认你是否注册到了正确的 Vue 实例上（代码中可能打包了多份 Vue 代码）

是正确注册了，es下的包里还是存在vant组件dom，未编译成功。
npm上发布的包名称  carserviceui

**Comment by chenjiahan** [comment]
dom 指的是？

**Comment by houkeepmoving** [comment]
> dom 指的是？

我的问题就是  我用vant cli  生成了一个组件库，组件库里用到了vant组件，build出来的组件在使用的时候报  vant里的组件未注册。

![1](https://user-images.githubusercontent.com/29296595/112569843-e3af9f00-8e1f-11eb-97e7-e668e18d403e.png)

**Comment by chenjiahan** [comment]
建议你把 Vue.use 改成局部注册
