### ISSUE TITLE
[Bug Report] Uploader组件，在浙政钉android端中设置capture="camera"的呈现问题

### ISSUE THREAD

**Issue by leedom92** [youzan/vant#8410]
### 设备 / 浏览器
android / 浙政钉内置浏览器

### Vant 版本
2.12.7

### Vue 版本
2.5.22

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater" target="_blank">https://youzan.github.io/vant-issue-generater</a>

### 描述问题
Uploader组件，在浙政钉android端中设置capture="camera"，不会直接调取相机，而是出现相机、文件的弹窗选项，估计是浙政钉内置浏览器的兼容问题，希望能做一下处理

**Comment by chenjiahan** [comment]
这个是浏览器原生属性，Uploader 组件只是透传了一下，在组件层面没法做兼容喔
