### ISSUE TITLE
[Feature Request] calendar 组件期待可以添加异步设置

### ISSUE THREAD

**Issue by shiliangL** [youzan/vant#8411]
### 这个功能解决了什么问题
通过传入 formatter 函数来对日历上每一格的内容进行格式化。但是如果数据是异步返回回来后再设置，那就无法实现了。
类似样例有。打卡情况记录。需要显示当天是否打卡正常、异常

### 描述您想要的解决方案
提供可以设置每一格的内容进行格式化的方法。

### 建议的API是什么样的
回调出每天信息对象。在配置中添加修改当天显示情况

**Comment by chenjiahan** [comment]
异步的话，可以把 formatter 设置为一个计算属性喔，当 formatter 变化时，组件内部也会重新执行

```js
export default {
  computed: {
    formatter() {
       if (// 异步数据未返回) {
         return (day) => day;
       }
       return (day) => {
         day.text = 'xxx';
         return day;
       }
    }
  }
}
```

**Comment by vw331** [comment]
> 异步的话，可以把 formatter 设置为一个计算属性喔，当 formatter 变化时，组件内部也会重新执行渲染
> 
> ```js
> export default {
>   computed: {
>     formatter() {
>        if (// 异步数据未返回) {
>          return (day) => day;
>        }
>        return (day) => {
>          day.text = 'xxx';
>          return day;
>        }
>     }
>   }
> }
> ```

bad idea

**Comment by chenjiahan** [comment]
把 formatter 作为一个纯函数使用，而不是一个与异步请求耦合的函数，我觉得没有什么不合理的
