### ISSUE TITLE
建议对vant v2版本也增加autocomplate

### ISSUE THREAD

**Issue by 1969267902** [youzan/vant#8415]
[在有些情况下，确实不需要自动输入信息，查看了V2和V3版本的源码，V3版本已经加入了autocomplate属性，v2版本缺没有此属性，建议也加上。
![QQ20210327-203508](https://user-images.githubusercontent.com/25898740/112720899-fcad7280-8f3b-11eb-9881-be64b905ce6e.png)

**Comment by chenjiahan** [comment]
v2 版本目前就支持的，文档后续补上
