### ISSUE TITLE
[Feature Request] 函数调用 dialog 时 message 是否能支持 jsx

### ISSUE THREAD

**Issue by atmfans** [youzan/vant#8416]
version: 3.x

### 这个功能解决了什么问题
用jsx 编写 dialog message 内容

### 描述您想要的解决方案
dialog.confirm({
message: \<Field\>xxxxxx\<\/Field\>
})

### 建议的API是什么样的
dialog.confirm({
message: \<Field\>xxxxxx\<\/Field\>
})

**Comment by chenjiahan** [comment]
已在 3.0.11 版本支持传入 render 函数
