### ISSUE TITLE
为什么我用vant-cli打包出来的组件里没包含install方法，不能使用vue.use()注册组件，只能局部注册。

### ISSUE THREAD

**Issue by houkeepmoving** [youzan/vant#8418]
1、vant组件有install方法

![2](https://user-images.githubusercontent.com/29296595/112780412-5d8f9480-907b-11eb-8985-2e4313379a83.png)

2、这是我打包出来的es组件包里的组件

![1](https://user-images.githubusercontent.com/29296595/112780459-75ffaf00-907b-11eb-93e5-6c32235bdfc7.png)

**Comment by chenjiahan** [comment]
install 方法需要自行挂载，跟 vant-cli 没有关系喔

参考：https://github.com/youzan/vant/blob/dev/src/utils/with-install.ts
