### ISSUE TITLE
[Bug Report] 官方文档网页 翻页快捷键（ctrl   ←/→）可以选择性关闭吗？  windows切屏（ctrl   开始   ←/→）会触发，每次都要再重新找

### ISSUE THREAD

**Issue by huangyixu** [youzan/vant#8421]
### 设备 / 浏览器
all

### Vant 版本
2.12.10

### Vue 版本
3.0.9

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/datetime-picker" target="_blank">https://youzan.github.io/vant/#/zh-CN/datetime-picker</a>

### 描述问题
官方文档网页 翻页快捷键（ctrl   ←/→）可以选择性关闭吗？  windows切屏（ctrl   开始   ←/→）会触发，每次都要再重新找

**Comment by chenjiahan** [comment]
暂无计划提供选项喔，可以看看有没有其他方法避免这个问题...

**Comment by huangyixu** [comment]
> 暂无计划提供选项喔，可以看看有没有其他方法避免这个问题...

[视频示例](https://616d-ammmm-fb4162-1302301674.tcb.qcloud.la/demo.mkv)
大哥，加一个吧，我发个视频你看看 ，体验真的太难受了。好不容易翻到下面看api了，切回去写完代码，再切回来就无了!!

**Comment by chenjiahan** [comment]
可以考虑在 windows 上关闭此行为

**Comment by huangyixu** [comment]
> 可以考虑在 windows 上关闭此行为

好的

**Comment by nemo-shen** [comment]
@huangyixu 

**临时解决方案：**
1. fork vant && clone
2. `vim ~/vant/packages/vant-cli/site/desktop/components/index.vue`
3. 跳转到大概第84行，找到`keyboardNav`方法，return掉
4. `vim ~/vant/package.json` line 20 将dev script改成
```js
"dev": "./packages/vant-cli/lib/index.js dev",
````
5. yarn dev

**Comment by huangyixu** [comment]
> @huangyixu
> 
> **临时解决方案：**
> 
> 1. fork vant && clone
> 2. `vim ~/vant/packages/vant-cli/site/desktop/components/index.vue`
> 3. 跳转到大概第84行，找到`keyboardNav`方法，return掉
> 4. `vim ~/vant/package.json` line 20 将dev script改成
> 
> ```js
> "dev": "./packages/vant-cli/lib/index.js dev",
> ```
> 
> 1. yarn dev

OK我试试

**Comment by huangyixu** [comment]
> @huangyixu
> 
> **临时解决方案：**
> 
> 1. fork vant && clone
> 2. `vim ~/vant/packages/vant-cli/site/desktop/components/index.vue`
> 3. 跳转到大概第84行，找到`keyboardNav`方法，return掉
> 4. `vim ~/vant/package.json` line 20 将dev script改成
> 
> ```js
> "dev": "./packages/vant-cli/lib/index.js dev",
> ```
> 
> 1. yarn dev

git@github.com:youzan/vant.git克隆的dev分支。按照步骤改了，最后提示找不到该路径
$ ./packages/vant-cli/lib/index.js dev
系统找不到指定的路径。
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by nemo-shen** [comment]
@huangyixu 
`./packages/vant-cli/lib`确定这个目录存在，如果没有的话在`~/vant/packages/vant-cli`目录下`yarn dev`先 生成一下

**Comment by chenjiahan** [comment]
以上方法可以临时解决，官方文档暂不调整
