### ISSUE TITLE
[Feature Request] 输入框的清除按钮及右边icon事件冲突问题

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#8423]
### 这个功能解决了什么问题
通过样式发现
.van-field__clear, .van-field__right-icon {
    margin-right: -8px;
    padding: 0 8px;
    line-height: inherit;
}
清除按钮和右边icon都加上了-8px边距，开发者的目的是让清除按钮通过负边距让dom重叠，这样看上去清除按钮与右icon相差8px，当右icon存在点击事件时，点击清除icon会触发右icon点击事件

### 描述您想要的解决方案
取消清除按钮的右边负边距

### 建议的API是什么样的
取消清除按钮的右边负边距

**Comment by nemo-shen** [comment]
@cangyu1993 能提供在线demo吗？

**Comment by cangyu1993** [comment]
这个在pc端没什么问题，我也觉得没什么问题！但这个问题是线上用户反馈的，可能用户手指比较粗吧！根据反馈就是点清除按钮会触发右icon点击事件，我只能把清除按钮右margin加到正数，让用户不误点。无伤大雅这个问题，个别用户而已，项目使用人很多就一个反馈这个问题
![image](https://user-images.githubusercontent.com/42930030/112924545-e7eefb80-9142-11eb-9e4a-190a2142f47e.png)
我给他隔开距离了，没事，就是难看了点

**Comment by nemo-shen** [comment]
@cangyu1993 
抛开组件库，如果从产品的角度考虑，这个产品原型设计肯定是会让用户有这样的困扰的，建议`可以在用户已经有内容输入的时候仅显示clear-icon，如果用户没有输入或者已经clear了仅显示contact-icon`，可以参考`支付宝话费充值`、`微信小程序话费充值（微信搜索[话费充值]）`的产品设计方式

### 参考的demo
```vue
 <van-field
  v-model="value"
  clearable
  :right-icon="value.length > 0 ? '' : 'smile-o'"
  @click-right-icon="clickRightIcon"
  label="label"
  placeholder="placeholder"
>
</van-field>
```

**Comment by cangyu1993** [comment]
这个设计是想在h5调通讯录。。。。。我。。。只能改成最近的充值手机号。可以关掉了。无伤大雅就行，毕竟只是极少用户（1个）反馈
