### ISSUE TITLE
[Feature Request] vue3版计划支持ssr么

### ISSUE THREAD

**Issue by Ben199011** [youzan/vant#8426]
### 这个功能解决了什么问题
服务端渲染需要支持ssr

### 描述您想要的解决方案
ssr

### 建议的API是什么样的
ssr

**Comment by chenjiahan** [comment]
目前就支持的。

**Comment by Ben199011** [comment]
@chenjiahan 我使用阿里的服务端框架渲染就失败了，框架链接是https://github.com/ykfe/ssr，作者说vant的local不支持ssr

**Comment by chenjiahan** [comment]
是支持的呢，如果 SSR 遇到问题，可以反馈具体的内容
