### ISSUE TITLE
[Bug Report] dynamic import error in ssr Element is not defined

### ISSUE THREAD

**Issue by zhangyuang** [youzan/vant#8429]
### 设备 / 浏览器
node12

### Vant 版本
3.0.10

### Vue 版本
3.0.9

### 重现链接
<a href="https://github.com/zhangyuang/vant-error" target="_blank">https://github.com/zhangyuang/vant-error</a>

### 描述问题
dynamic import 的时候会报错 Element is not defined，直接import 具体文件则不会。推测是3.29半个月内vant的commit导致的。半个月前测试dynamic import 可以。https://github.com/youzan/vant/commit/2cad166226d5cf2e9ab151185edaa741adfeb6de 或许跟这个commit有关

**Comment by zhangyuang** [comment]
![image](https://user-images.githubusercontent.com/17424434/112832639-2f847180-90c8-11eb-8501-4f994c28ab8b.png)

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/8403
