### ISSUE TITLE
标签页切换后导致左边tab标签页的分页方法失效，求大神解答。

### ISSUE THREAD

**Issue by LiliQQ** [youzan/vant#843]
tab标签页切换后导致左边tab标签页的分页方法失效。使用的是youzan瀑布流。
![image](https://user-images.githubusercontent.com/24430608/38540775-9226fbaa-3ccf-11e8-89c9-9f2058126755.png)

![image](https://user-images.githubusercontent.com/24430608/38540833-cc2dc612-3ccf-11e8-91bc-5f7a8979f349.png)

![image](https://user-images.githubusercontent.com/24430608/38540754-8aaf025a-3ccf-11e8-9c7b-563d7a20055a.png)
![image](https://user-images.githubusercontent.com/24430608/38540840-d45597ac-3ccf-11e8-9a94-c442a5fd33c9.png)

**Comment by LiliQQ** [comment]
右边的标签页分页方法却不受影响，我已经把该区分的参数给分开来了。

**Comment by chenjiahan** [comment]
Waterfall 组件已经不再维护，建议使用 List 组件代替
