### ISSUE TITLE
[Bug Report] van-datetime-picker type=date时，v-model有时候默认选中日期不正确

### ISSUE THREAD

**Issue by HZZformGD** [youzan/vant#8433]
### 设备 / 浏览器
微信

### Vant 版本
3.0.10
### Vue 版本
3.0.5

### 重现链接
<a href="http://jsrun.net/IRNKp/edit" target="_blank">http://jsrun.net/IRNKp/edit</a>

### 描述问题
初始值设置date-picker 无法默认选中

**Comment by nemo-shen** [comment]
@HZZformGD
我尝试修改了一下你提供的在线demo，DatePicker好像没有问题，应该是写法上有点不对

### 调整后的重现链接
http://jsrun.net/8RNKp/edit

**Comment by HZZformGD** [comment]
> @HZZformGD
> 我尝试修改了一下你提供的在线demo，DatePicker好像没有问题，应该是写法上有点不对
> 
> ### 调整后的重现链接
> http://jsrun.net/8RNKp/edit

多谢哈。  照着你那个改 发现可以了  估计是field 用了  v-model + formatter   formatter 把value format 之后  datepicker 又读取了这个formated的value 导致没办法选中
