### ISSUE TITLE
vant-cli 生成的项目，如何封装函数调用性组件呢？我封装了toast组件，只能注册调用，不知怎么函数调用，有参考么？

### ISSUE THREAD

**Issue by houkeepmoving** [youzan/vant#8434]
基于vue2.x开发

1、目录结构

![1](https://user-images.githubusercontent.com/29296595/112960770-5057d000-9177-11eb-98bb-584ee54f91be.png)

2、组件方法封装

![2](https://user-images.githubusercontent.com/29296595/112960834-65346380-9177-11eb-885e-b6178a508656.png)

**Comment by chenjiahan** [comment]
就导出一个函数呗。

```ts
import { Toast } from 'vant';

export default function myToast() {
  return Toast();
}
```
