### ISSUE TITLE
[Feature Request] 如何实现表单自定义组件

### ISSUE THREAD

**Issue by daisybaicai** [youzan/vant#8435]
### 这个功能解决了什么问题
实现自定义的van-field，就是Form.Item.如何给自定义组件绑定上表单的value，以及onchange的方法

### 描述您想要的解决方案
能够提供自定义的demo

### 建议的API是什么样的
```
<van-field name="customField" label="自定义组件">
  <template #input>
    <customFormItem v-model="custom" @change="??"/>
  </template>
</van-field>
```
能这样实现吗

**Comment by chenjiahan** [comment]
目前不支持自定义表单项喔，后续会看下如何支持

**Comment by chenjiahan** [comment]
已支持，参见 https://github.com/youzan/vant/issues/9123
