### ISSUE TITLE
<van-tabbar-item info="5">标签</van-tabbar-item>中info应该要支持Number类型

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant#844]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
下个版本支持
