### ISSUE TITLE
CDN 引入 样式会偏小

### ISSUE THREAD

**Issue by wfs498121294** [youzan/vant#8447]
你好  为什么我用CDN的方式引入的话  用rem适配会偏小
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vant@2.12/lib/index.css" />
    
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6/dist/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vant@2.12/lib/vant.min.js"></script>
    

![image](https://user-images.githubusercontent.com/12890610/113373415-58915480-939d-11eb-9f7d-2aead3f2613b.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by adoin** [comment]
> 你好 为什么我用CDN的方式引入的话 用rem适配会偏小 <script src="https://cdn.jsdelivr.net/npm/vue@2.6/dist/vue.min.js"></script> <script src="https://cdn.jsdelivr.net/npm/vant@2.12/lib/vant.min.js"></script>
> 
> ![image](https://user-images.githubusercontent.com/12890610/113373415-58915480-939d-11eb-9f7d-2aead3f2613b.png)

这个后面咋解决的呢 我也要用cdn的 但是 单位都是px 没有转为rem
