### ISSUE TITLE
Toast 轻提示组件报错

### ISSUE THREAD

**Issue by pengbeirong** [youzan/vant#8448]
设备 / 浏览器
chrome浏览器web端

Vant 版本
3.0.10

Vue 版本
3.0.7

描述问题

- [ ] ![image](https://user-images.githubusercontent.com/60093749/113373566-adcd6600-939d-11eb-869e-492b22497013.png)

不影响功能使用，就是会有这个报错

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by pengbeirong** [comment]
> 麻烦提供一下 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

我看了一下是因为Vue.js devtools 6.0.0 beta 7发出的错误，只有在使用弹窗popup.js的时候会触发这个chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/backend.js ，不是vant的问题，谢了
