### ISSUE TITLE
[Bug Report] 在微信中打开van-feild type=text 时 , 无法手写输入

### ISSUE THREAD

**Issue by payallmoney** [youzan/vant#8451]
### 设备 / 浏览器
android/微信

### Vant 版本
2.12.11

### Vue 版本
3.0.11

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/field" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/field</a>

### 描述问题
1, 在微信中打开https://vant-contrib.gitee.io/vant/#/zh-CN/field

2, 设置输入法为手写输入法 (我的是小米手机 , 其他android手机也会发生问题 , iphone未测试)

3, 点击主页中的"用户名"输入框

4, 手写输入法会弹起后马上就收回了 , 无法手写输入

**Comment by payallmoney** [comment]
又搜索了下 , 估计是微信的bug
https://developers.weixin.qq.com/community/develop/doc/00026427478ee0e2e1ebdad355b000?highLine=%25E6%2589%258B%25E5%2586%2599

**Comment by chenjiahan** [comment]
嗯，这个不是组件的问题喔
