### ISSUE TITLE
[Bug Report] Popup 文档示例代码错误

### ISSUE THREAD

**Issue by zjxpcyc** [youzan/vant#8454]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.11

### Vue 版本
3.0.11

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/popup" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/popup</a>

### 描述问题
源文档示例  `<van-popup v-model="show">内容</van-popup>`  实际上 应该是 

```html
// 少了一个 :show
<van-popup v-model:show="show">内容</van-popup>
```

**Comment by chenjiahan** [comment]
请注意文档版本，v2 是 v-model，v3 是 v-model:show
