### ISSUE TITLE
当页面设置van-slide-left ，van-slide-right的转场动画的时候，Popover组件定位不正确，导致组件不显示

### ISSUE THREAD

**Issue by jinghh** [youzan/vant#8458]
当页面设置van-slide-left ，van-slide-right的转场动画的时候，页面中Popover组件定位不正确，导致组件不显示，应该是动画还没结束的时候获取了当前元素的位置，导致定位偏移了，目前是改成fade效果才可以，看看这个能否优化,在动画结束时候计算定位，或者新增一个api可以手动调重新定位的方法
![image](https://user-images.githubusercontent.com/18163968/113648634-7f15ff00-96bf-11eb-8da0-490899b2026e.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
