### ISSUE TITLE
[Feature Request] 如何动态关闭Popup、Dialog？

### ISSUE THREAD

**Issue by y13818463245** [youzan/vant#8463]
### 这个功能解决了什么问题
我要实现android 返回键监听的功能，流程如下：
如果有dialog弹出框优先关闭、如果有popup弹出层优先关闭。

### 描述您想要的解决方案
怎么在全局js里面实现动态选择dialog、popup？
怎么动态关闭dialog和popup？

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
- Dialog 可以通过 Dialog.close 关闭
- Popup 可以通过修改 v-model 绑定的值进行关闭
