### ISSUE TITLE
Uploader 文件上传 安卓手机不支持HEIC图片格式

### ISSUE THREAD

**Issue by yeluowuhen52** [youzan/vant#8465]
设备 / 浏览器
小米10

Vant 版本
2.12.12

Vue 版本
2.6.11
小米10使用Uploader 文件上传 选择了本地HEIC图片格式图片，页面上显示一个叉号！fileList中的content是有内容的！

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
