### ISSUE TITLE
[Bug Report] 上传组件在小米10选择HEIC格式的照片之后，不能正常显示图片

### ISSUE THREAD

**Issue by yeluowuhen52** [youzan/vant#8466]
### 设备 / 浏览器
小米10

### Vant 版本
3.0.12

### Vue 版本
3.0.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/uploader" target="_blank">https://youzan.github.io/vant/#/zh-CN/uploader</a>

### 描述问题
上传组件在小米10选择HEIC格式的照片之后，不能正常显示图片，但是file List的content是有值的！

**Comment by chenjiahan** [comment]
跟组件没关系，Chrome 浏览器本身就不支持展示 heic 格式的图片。

**Comment by chenjiahan** [comment]
参见 https://caniuse.com/?search=heic
