### ISSUE TITLE
使用Tab标签页嵌入高德地图导致高德地图找不到地图容器

### ISSUE THREAD

**Issue by Wangjiateng666** [youzan/vant#8468]
场景：在tab1中有列表，点击列表跳转到tab2中所对应的轨迹点。
尝试使用其他标签多层嵌套，依旧可以找到地图容器，但是使用van-tabs就会出现找不到，导致地图无法展示

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
