### ISSUE TITLE
部分样式无法覆盖 ，现项目中有些细节需要修改样式表 我是在vue文件里覆盖修改的 但是有些可以覆盖有效 有些覆盖无效

### ISSUE THREAD

**Issue by StrangeClow** [youzan/vant#847]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
建议看下是否使用了正确的选择器以及优先级

**Comment by StrangeClow** [comment]
还是无效  覆盖样式中 有一个重新设置高的有效   但是覆盖字体大小的无效    报告大佬

**Comment by chenjiahan** [comment]
能否贴下代码以及控制台截图

**Comment by StrangeClow** [comment]
我从邮件里回复时显示 无法发送 地址错误    这里也不能发图片

**Comment by chenjiahan** [comment]
这里可以发图片的，没有具体信息的话我们也没办法帮你定位问题
