### ISSUE TITLE
[Feature Request] Sticky 组件在粘性状态变化时通知使用者

### ISSUE THREAD

**Issue by joshchiucn** [youzan/vant#8476]
### 这个功能解决了什么问题
页面滚动时，什么时候元素是粘性的没法知道。

### 描述您想要的解决方案
在粘性状态变化时，使用组件的地方能收到通知。

### 建议的API是什么样的
sticky组件内，在状态变化后emit一个事件，并附带相关信息，告知外部现在是否是粘性的。

**Comment by SGB555** [comment]
![image](https://user-images.githubusercontent.com/22334195/113990245-d5cc3600-9883-11eb-9559-fcdbf2c99cea.png)

**Comment by chenjiahan** [comment]
3.x 版本有提供 change 事件，2.x 目前还不支持，后续加上

**Comment by chenjiahan** [comment]
已在 2.12.13 版本支持
