### ISSUE TITLE
实例页面购物车 van-submit-bar__bar里的van-submit-bar__price文字会被设置的rem影响不能居中

### ISSUE THREAD

**Issue by maoqiwu** [youzan/vant#848]
1.`<html style="font-size: 16px;">` 的时候 ，`<div class="van-submit-bar__bar">`是正常的
![image](https://user-images.githubusercontent.com/17698509/38590722-a0e68e58-3d65-11e8-95b0-66ed865e1994.png)

2.`<html style="font-size: 64.6875px;">` 的时候 ，`<div class="van-submit-bar__bar">`
![image](https://user-images.githubusercontent.com/17698509/38590570-8a337dfc-3d64-11e8-8399-f6573055151f.png)

**Comment by maoqiwu** [comment]
补充一下   <van-checkbox v-model="checked">全选</van-checkbox> 提交订单栏的文字默认的是html的文字大小 ，也会被rem重置以后的px影响

**Comment by chenjiahan** [comment]
感谢反馈，下个版本修复此问题

**Comment by chenjiahan** [comment]
已在 1.0.5 版本修复
