### ISSUE TITLE
[Bug Report] 使用 jsx/tsx 开发时 v-model 失效，Search 组件在使用 tsx 开发时 placeholder 类型校验错误

### ISSUE THREAD

**Issue by wjq990112** [youzan/vant#8484]
### 设备 / 浏览器
 OnePlus 8 Pro / Chrome Android

### Vant 版本
3.0.12

### Vue 版本
3.0.11

### 重现链接
<a href="https://codesandbox.io/s/zen-fire-0b8mg?file=/src/App.tsx&resolutionWidth=320&resolutionHeight=675" target="_blank">https://codesandbox.io/s/zen-fire-0b8mg?file=/src/App.tsx&resolutionWidth=320&resolutionHeight=675</a>

### 描述问题
使用 jsx/tsx 开发时设定组件 v-model 无法实现双向绑定的功能，查阅 @vue/babel-plugin-jsx 文档未能解决，查阅组件测试用例也未能解决，此处可能存在使用姿势不正确的可能，望指教。

![image](https://user-images.githubusercontent.com/45777252/114044277-a89a7a80-98b9-11eb-8fc2-d917bae5cc3e.png)

同时在使用 tsx 开发，运用 Searh 组件时，placeholder 无法通过类型校验，翻阅相应的 d.ts 文件发现组件并未对外暴露此接口，翻阅源码发现其中的 Search 中的 input 由 Field 组件负责渲染，初步判断可能是 Search 组件的接口未继承 Field，望协助解决！

![image](https://user-images.githubusercontent.com/45777252/114043511-efd43b80-98b8-11eb-98fa-47a4f9a8a88b.png)

非常感谢！

**Comment by wjq990112** [comment]
关于 v-model 失效的问题，已经发现问题所在，不能使用解构将 modelValue 解构出来。

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by wjq990112** [comment]
@chenjiahan 在 JSX 中应该如何使用组件内 emit 的事件？
例如：`Button` 组件的 `click` 事件：

```tsx
setup() {
  return () => (
    <Button onClick={handleClick}>button</Button>
  );
}
```

tsx 中 `onClick` 会缺失类型，会报错，是否是使用姿势不正确？还请多多指教！

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/8302

**Comment by wjq990112** [comment]
> 参见 #8302

Get，感谢指教！

**Comment by chenjiahan** [comment]
> 下个版本会修复 placeholder 缺少类型定义的问题

已在 3.0.13 版本修复
