### ISSUE TITLE
Field组件，type="number“；时区为德国时，小数点为英文逗号，点击无反应，无法获取到值

### ISSUE THREAD

**Issue by ChaoZhQua** [youzan/vant#8494]

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by ierye** [comment]
iPhone
版本: vant 4.9.21
设置
type="text"
inputmode="decimal"
亲测可以解决这个问题
type是告诉Field接受text内容输入
inputmode是设置系统小数数字键盘
然后通过formatter把,替换为.
