### ISSUE TITLE
Collapse 的 title 以 slot 方式包含按钮，按钮在loading状态下不对齐

### ISSUE THREAD

**Issue by Rickykurt** [youzan/vant#850]
**What is the current behavior?**
Collapse 的 title 以 slot 方式包含按钮，按钮在loading状态下不对齐
示例代码 https://jsfiddle.net/7wwyytk0/3/
![untitled](https://user-images.githubusercontent.com/1176984/38598949-09edd12e-3d91-11e8-9eae-b6f4729b216e.gif)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**
Collapse 的 title 以 slot 方式包含按钮，按钮在loading状态下应该对齐
**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by Rickykurt** [comment]
现在这么解决，感觉会有副作用😓 
`.van-loading__spinner{
    vertical-align: -5.5px;
  }`

**Comment by chenjiahan** [comment]
目前 Button 在 loading 状态下确实存在不对齐的问题，我们会在下个版本修复~

**Comment by chenjiahan** [comment]
已在 1.0.5 版本修复
