### ISSUE TITLE
[Bug Report] Tabs 中若 Tab 高度不一致，在开启 swipeable/animated 后 Tab 被截断

### ISSUE THREAD

**Issue by wjq990112** [youzan/vant#8501]
### 设备 / 浏览器
OnePlus 8 Pro/Chrome Android

### Vant 版本
3.0.12

### Vue 版本
3.0.11

### 重现链接
<a href="https://codesandbox.io/s/zen-fire-0b8mg?file=/src/App.tsx&resolutionWidth=320&resolutionHeight=675" target="_blank">https://codesandbox.io/s/zen-fire-0b8mg?file=/src/App.tsx&resolutionWidth=320&resolutionHeight=675</a>

### 描述问题
当 Tab 高度不一致时，从高度较小的 Tab 滑动/切换至高度较大的 Tab 时，高度较大的 Tab 超出的部分会被截断，初步判断是外层容器没有限定高度，也许可以将外层容器的高度设定为高度最大的 Tab，不确定是否可行，望协助解决。

演示链接：https://0b8mg.csb.app/
相关代码：https://codesandbox.io/s/zen-fire-0b8mg?file=/src/App.tsx&resolutionWidth=320&resolutionHeight=675

**Comment by chenjiahan** [comment]
演示链接的内容和描述的问题不一致，麻烦确认下

**Comment by wjq990112** [comment]
> 演示链接的内容和描述的问题不一致，麻烦确认下

不好意思，上次不小心改动了，稍等一下。

**Comment by wjq990112** [comment]
@chenjiahan 已复现

**Comment by chenjiahan** [comment]
目前默认是使用「当前激活 Tab」的高度，非激活 Tab 的高度会被设置为 0，这样能保证在当前 Tab 底部不会有一段空白区域。

如果想改变这个行为，可以手动设置一个最小高度试试

**Comment by wjq990112** [comment]
@chenjiahan Get，尝试一下，非常感谢！

**Comment by wjq990112** [comment]
@chenjiahan 我觉得这个情况应该还是一个 bug，非激活的 Tab 高度设置为 0 的时间应该为动画执行结束后。目前的情况是动画还未执行完成高度就发生了坍塌。

**Comment by chenjiahan** [comment]
> 非激活的 Tab 高度设置为 0 的时间应该为动画执行结束后。目前的情况是动画还未执行完成高度就发生了坍塌。

其实坍塌发生在任何时机都会造成画面的跳跃感，更好的解决方式是：

1. 不开启左右滑动的动画
2. 把 Tab 页设置为局部滚动，让几个 Tab 页的高度保持一致，在内部进行滚动
