### ISSUE TITLE
[Bug Report] Field组件在输入数字时，过滤掉了英文逗号

### ISSUE THREAD

**Issue by ChaoZhQua** [youzan/vant#8504]
### 设备 / 浏览器
iPhone

### Vant 版本
2.9.2

### Vue 版本
2.6.11

### 重现链接
<a href="https://h5.miracare.dev/status?token=414295-38ef24d8-972e-4ebc-9e6f-6c7f8e7e029a" target="_blank">https://h5.miracare.dev/status?token=414295-38ef24d8-972e-4ebc-9e6f-6c7f8e7e029a</a>

### 描述问题
在时区设置为一些地区，比如德国时，数字输入法（在修改体温和体重时，iPhone输入法）的小数点会以英文逗号显示；但是Field组件在type为number时，会过滤掉英文逗号。请问有遇到过该问题的朋友吗，是如何解决的？

**Comment by ChaoZhQua** [comment]
我把Field组件提出来改了下，朋友们或者Vant官方有什么解决方案

**Comment by chenjiahan** [comment]
还在调研中，相关文章：https://www.ctrl.blog/entry/html5-input-number-localization.html

**Comment by Sphinm** [comment]
是否可以通过 `Intl.NumberFormat` 来判断下不同国家的千分位和小数点的格式，然后再过滤呢

**Comment by ChaoZhQua** [comment]
> 是否可以通过 `Intl.NumberFormat` 来判断下不同国家的千分位和小数点的格式，然后再过滤呢

非常感谢~

**Comment by huangliangb0** [comment]
我觉得可以自己解决，自己对组件二次封装，输入focus状态的时候type为number，blur状态改成text，text的回显自行处理

**Comment by chenjiahan** [comment]
组件层面比较难支持，还是自行封装来解决吧~

**Comment by ierye** [comment]
iPhone
版本: vant 4.9.21
设置
type="text"
inputmode="decimal"
亲测可以解决这个问题
type是告诉Field接受text内容输入
inputmode是设置系统小数数字键盘
然后通过formatter把,替换为.
