### ISSUE TITLE
vant-cli build 时没有合并根目录的 webpack 配置

### ISSUE THREAD

**Issue by JokerLZD** [youzan/vant#8505]
操作系统： macOS 10.15.7
Node 版本：12.21.0
yarn 版本：1.22.5
操作过程：
  1. 使用  yarn create vant-cli-app 新建项目
  2. 添加了 element-ui 和 @vue/composition-api 依赖
  3. 配置了 element 的按需引用
  4. 随便做了个组件
  5. 使用 yarn build 然后报 error  in ./node_modules/element-ui/lib/theme-chalk/fonts/element-icons.ttf
  6. 根目录下 新建 webpack.config.js 并配置，yarn add -D file-loader
  7. yarn build  之后依然报错

相关配置截图：
  1. babel
 ![image](https://user-images.githubusercontent.com/10861421/114331751-4cfd1500-9b77-11eb-9874-224513edcba5.png)
  2. webpack
 ![image](https://user-images.githubusercontent.com/10861421/114331792-6605c600-9b77-11eb-8fe4-84c8f23533d6.png)
  3. package.json 
 ![image](https://user-images.githubusercontent.com/10861421/114331845-833a9480-9b77-11eb-9781-721a13d32ee6.png)
  4. 组件 
![image](https://user-images.githubusercontent.com/10861421/114332108-212e5f00-9b78-11eb-8e5e-309d53c3c6ce.png)
  5. 报错信息  
![image](https://user-images.githubusercontent.com/10861421/114331914-ab29f800-9b77-11eb-90da-d0a6cdba86e6.png)

**Comment by chenjiahan** [comment]
能提供下复现仓库吗？

**Comment by chenjiahan** [comment]
提供个复现仓库看下？

**Comment by JokerLZD** [comment]
> 提供个复现仓库看下？

https://github.com/JokerLZD/vant-cli-8505

这个仓库，您看下

**Comment by chenjiahan** [comment]
你的 webpack.config.js 拼写错误了，少了个 i
