### ISSUE TITLE
[Bug Report] Calendar组件副标题切换日期不更新的问题

### ISSUE THREAD

**Issue by suntao2yl** [youzan/vant#8509]
### 设备 / 浏览器
iMac pro/Chrome

### Vant 版本
2.12.13

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-cri34?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-cri34?file=/src/App.vue</a>

### 描述问题
由于业务需求特殊，我们要求要通过按钮控制月份显示（副标题必须显示在顶部），实际操作是通过控制min和max的值进行控制。但此过程中副标题无法刷新。

**Comment by chenjiahan** [comment]
已在 2.12.14 版本修复
