### ISSUE TITLE
如果所在页面是通过vue router懒加载的方式，Field控件的Label宽度显示异常

### ISSUE THREAD

**Issue by xingda** [youzan/vant#8511]
没办法提供codepen或者jsbin的页面。
我尽量描述一下。

同样一个页面
如果使用vue-router做页面的动态加载，语法类似这样：
const Home = () => import('../page/Home.vue')
这样展示的field控件的label宽度显示异常，而且label-width也不起作用
改成正常的加载
import Home from '../page/Home.vue'
后就正常了

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

没法提供复现链接的话，提供复现的最小仓库也可以，不然我们没法排查。

**Comment by chenjiahan** [comment]
另外建议你看下是不是样式被项目中的全局样式覆盖了

**Comment by xingda** [comment]
抱歉回复晚了，问题已经解决，解决方法供参考哈。
我那个出现错误的页面里面同时使用了cell 和 field两个控件，但是cell控件属于v-if下的隐藏控件，我就忘了按需import控件了
当我加载上以后，问题就解决了。
不过这里面还是有可能存在bug的哈。
但查起来可能会比较费劲，复现的方式可以按照我的描述试试，不过这个问题优先级应该不高
