### ISSUE TITLE
[Feature Request] cascader 无tab选项回调

### ISSUE THREAD

**Issue by aleoyu** [youzan/vant#8515]
### 这个功能解决了什么问题
解决当前切换选项卡的值 

### 描述您想要的解决方案
回调中增加一个TAB

### 建议的API是什么样的
回调中增加一个TAB

**Comment by chenjiahan** [comment]
没明白你的意思，能否具体说明下？

**Comment by nemo-shen** [comment]
@chenjiahan 

应该是希望知道`Cascader`里面tab切换后`state.activeTab`值的变化

@aleoyu 有什么实际使用场景吗？

**Comment by chenjiahan** [comment]
已增加 click-tab 事件

**Comment by pocketChao** [comment]
> 

能否在2.x版本支持下
