### ISSUE TITLE
countDown 组件自定义显示毫秒默认为3位，如何设置为2位

### ISSUE THREAD

**Issue by Jackkuangkuang** [youzan/vant#8517]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by nemo-shen** [comment]
@Jackkuangkuang 

**我猜你是想在自定义样式的时候，让毫秒显示2位？**

如果是的话，可能你需要自己处理一下

参考代码：
```vue
<van-count-down millisecond :time="time">
  <template #default="currentTime">
    {{ currentTime.hours }}:{{ currentTime.minutes }}:{{ currentTime.seconds }}:{{ currentTime.milliseconds.toString().slice(0, 2) }}
  </template>
</van-count-down>
```

**下次提issue请使用[vant-issue-generater](http://vant-contrib.gitee.io/vant-issue-generater)创建**
