### ISSUE TITLE
[Bug Report] popup 二次封装时需要注意。

### ISSUE THREAD

**Issue by HuangWeiBin2** [youzan/vant#8518]
### 设备 / 浏览器
谷歌

### Vant 版本
3.0.13

### Vue 版本
3.0.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-5wmjl?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-5wmjl?file=/src/App.vue</a>

### 描述问题
没有代码。懒得复现。
二次封装popup的时候，控制弹出   需要把v-model:show  改为 :show   不然会报不能在子组件改props。

<template>
  <van-popup :show="showPicker" round position="bottom" safe-area-inset-bottom transition-appear>
    <van-picker
        :columns="columns"
        @cancel="onCancel"
        @confirm="onConfirm"
    />
  </van-popup>
</template>
<script>
import {defineComponent, getCurrentInstance, ref} from "vue";

export default defineComponent({
  name: "vPopupPicker",
  props: {
    columns: {
      type: Array,
      default: []
    },
    showPicker: {
      type: Boolean,
      default: false
    }
  },
  emits: ['onConfirm', 'onCancel'],
  setup: (props, context) => {
    const {proxy} = getCurrentInstance();
    const parent = {...context}
    const onConfirm = (value) => {
      parent.emit('onConfirm', value)
    }
    const onCancel = () => {
      parent.emit('onCancel')
    }
    return {
      onCancel,
      onConfirm,
    };
  },
});
</script>

<style scoped>

</style>

**Comment by chenjiahan** [comment]
是这样的，这个是 v-model 本身的特性。

**Comment by atdow** [comment]
如果想二次封装组件，并且该封装组件上想使用v-modal，请参考官网例子：[自定义组件的 v-model](https://cn.vuejs.org/v2/guide/components-custom-events.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E7%9A%84-v-model)
