### ISSUE TITLE
[Bug Report] van-tabs sticky没法设置偏移量和vant-sticky 冲突

### ISSUE THREAD

**Issue by yehoan** [youzan/vant#8519]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.12.6

### Vue 版本
2.6.12

### 重现链接
<a href="https://codesandbox.io/s/beautiful-star-8ewl6?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675" target="_blank">https://codesandbox.io/s/beautiful-star-8ewl6?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675</a>

### 描述问题
van-tabs sticky没法设置偏移量和vant-sticky 冲突    具体效果请看链接  希望能得到答复

**Comment by yehoan** [comment]
希望就是tab的sticky 能一直在个人信息的下面  而不是覆盖

**Comment by chenjiahan** [comment]
使用 `offset-top` 属性即可
