### ISSUE TITLE
一个页面多个field组件同时存在时，当从一个聚焦的field组件聚焦到另一个field组件时，页面会被调起的软键盘弹起滚动到错乱布局

### ISSUE THREAD

**Issue by CoolHenry** [youzan/vant#8523]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
