### ISSUE TITLE
[Bug Report] 下拉刷新组件bug

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#8525]
### 设备 / 浏览器
浏览器

### Vant 版本
3.0.13

### Vue 版本
3.0.11

### 重现链接
<a href="http://dev.jbf.aijk.net/casher/index.html#/paysuc1" target="_blank">http://dev.jbf.aijk.net/casher/index.html#/paysuc?tradeNo=1000000003647826</a>

### 描述问题
vue3在dev环境下下拉刷新正常，打包后第一次下拉刷新显示正常，第二次的时候直接就显示loading状态，不显示pulling和loosing的状态

**Comment by Thlq** [comment]
自定义提示的时候会有这个问题

**Comment by Thlq** [comment]
http://dev.jbf.aijk.net/casher/index.html#/paysuc2这个是没有自定义提示的显示正常
http://dev.jbf.aijk.net/casher/index.html#/paysuc1这个是有自定义提示的，就会出现描述出现的问题

**Comment by Thlq** [comment]
官方demo上，自定义发现如果把:style="{ transform: `scale(${props.distance / 80})` }"这个去掉也会出现问题

**Comment by Thlq** [comment]
上面的链接已改成非自定义，非自定义好像没有问题，问题查看请看下面链接
http://dev.jbf.aijk.net/casher/index.html#/paysuc1   这个是pulling，loosing，loading都自定义的状态，会出现上面描述的问题
http://dev.jbf.aijk.net/casher/index.html#/paysuc2   这个是只loading自定义的状态，正常

**Comment by chenjiahan** [comment]
上述链接打开后提示「无访问权限」，麻烦提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by Thlq** [comment]
> 上述链接打开后提示「无访问权限」，麻烦提供 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f

这个地址可以的
http://dev.jbf.aijk.net/cashertest/index.html#/paysuc1 这个是pulling，loosing，loading都自定义的状态，会出现上面描述的问题
http://dev.jbf.aijk.net/cashertest/index.html#/paysuc2 这个是只loading自定义的状态，正常

**Comment by chenjiahan** [comment]
你给的地址我没法看到复现代码。请提供 codesandbox 链接。

**Comment by Pizhong** [comment]
> 上面的链接已改成非自定义，非自定义好像没有问题，问题查看请看下面链接 http://dev.jbf.aijk.net/casher/index.html#/paysuc1 这个是pulling，loosing，loading都自定义的状态，会出现上面描述的问题 http://dev.jbf.aijk.net/casher/index.html#/paysuc2 这个是只loading自定义的状态，正常

我也碰到这个问题，请问已经解决了吗
