### ISSUE TITLE
[Bug Report] 使用vite + vite-plugin-imp 按需加载，全局注册lazyload，导致的问题

### ISSUE THREAD

**Issue by githublxx** [youzan/vant#8526]
"vant": "^3.0.13",
 "vue": "^3.0.5",
  "vite": "^2.0.5",
  "vite-plugin-imp": "^2.0.5"
  
  使用vite + vite-plugin-imp 按需加载，在main.ts全局注册lazyload，
 写出以下内容就会报错
 app.use(Lazyload, {
  lazyComponent: true,
 })
 
 具体报错信息：
 [plugin:vite:import-analysis] Failed to resolve import "vant/es/lazyload/index.css" from "src\main.ts". Does the file exist?

**Comment by chenjiahan** [comment]
这是 vite-plugin-imp 的问题，Lazyload 组件本身不存在样式文件，不应该去引用样式


![image](https://user-images.githubusercontent.com/7237365/114676990-6ef3c480-9d3c-11eb-9493-32e7987a5962.png)

可以参考上述配置

**Comment by githublxx** [comment]
ok 明白了 谢谢
