### ISSUE TITLE
微信小程序当渲染tab后 ，标签出现错位

### ISSUE THREAD

**Issue by yumaorourou** [youzan/vant#8527]
![image](https://user-images.githubusercontent.com/65656391/114675909-5931cf80-9d3b-11eb-89b8-cc0be4e5a393.png)
![image](https://user-images.githubusercontent.com/65656391/114675987-6bac0900-9d3b-11eb-97f2-c1a4b9bc9892.png)
![image](https://user-images.githubusercontent.com/65656391/114676072-7ebed900-9d3b-11eb-9b70-8e7662818eeb.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
