### ISSUE TITLE
ImagePreview 组件的问题

### ISSUE THREAD

**Issue by chaituan** [youzan/vant#853]
由于安卓机 点击图片会自动放大，当使用 ImagePreview 的时候 第二次 就会弹出2次图片， 组件里面是否可以禁用 自带的点击放大功能。    苹果机正常使用！

**Comment by chenjiahan** [comment]
请问具体的安卓机型是？

**Comment by chaituan** [comment]
@chenjiahan   小米5  miui系统

**Comment by ReZhangxin** [comment]
如果滑动过快，会退出预览功能

**Comment by chenjiahan** [comment]
@ReZhangxin  滑动过快退出的问题已修复

**Comment by chenjiahan** [comment]
点击图片未放大的问题未复现
