### ISSUE TITLE
[Bug Report] 圆角风格的Radio和Stepper在手机上显示扭曲

### ISSUE THREAD

**Issue by zsg179** [youzan/vant#8533]
### 设备 / 浏览器
安卓设备

### Vant 版本
2.12.1

### Vue 版本
2.5.2

### 重现链接
<a href="https://pensionlife.95522.cn/szyl_vote/zgh/#/index" target="_blank">https://pensionlife.95522.cn/szyl_vote/zgh/#/index</a>

### 描述问题
发现在安卓设备，比如荣耀，小米设备上圆角风格的Radio和Stepper扭曲，变成椭圆，在ipad7和iphonese2上显示正常。

**Comment by zsg179** [comment]
git仓库：https://github.com/zsg179/zgh

**Comment by chenjiahan** [comment]
是用了 rem 适配么，rem 会导致出现小数单位，可能会渲染不准确，这个和组件本身无关。

**Comment by zsg179** [comment]
> 
> 
> 是用了 rem 适配么，rem 会导致出现小数单位，可能会渲染不准确，这个和组件本身无关。
> 
> 可以打开官方示例看下是否正常。

是用了rem适配，但是不用rem该怎么适配呢？

**Comment by chenjiahan** [comment]
可以配置一下 rem 转换插件，把 Radio 和 Stepper 的选择器过滤掉。

或者通过 Radio 的 icon-size 属性设置一个固定大小。

**Comment by zsg179** [comment]
> 
> 
> 可以配置一下 rem 转换插件，把 Radio 和 Stepper 的选择器过滤掉。
> 
> 或者通过 Radio 的 icon-size 属性设置一个固定大小。
在rem转换插件里忽略了变形的选择器解决了问题。谢谢您的热心回答！
