### ISSUE TITLE
vant-cli build-site命令，readme中的<demo-code>无法解析（pc端）

### ISSUE THREAD

**Issue by taotao4840** [youzan/vant#8537]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by git-lt** [comment]
@zhengguorong 
如果你只是想在pc页面展示出来，源码可以这样改，在 site/desktop/main.js 中加入下面的代码（DemoBlock.vue 和 DemoSection.vue可以定义为一个空的容器组件）
```js
import DemoBlock from './components/DemoBlock.vue';
import DemoSection from './components/DemoSection.vue';
import { decamelize } from '../common/index.js';
import { demos } from 'site-mobile-shared';

Vue.component(DemoBlock.name, DemoBlock);
Vue.component(DemoSection.name, DemoSection);
Object.keys(demos).forEach(name=> {
  Vue.component(`pc-${decamelize(name)}`, demos[name]);
})
```

在组件库如 button 下的 README.md 中这样用就能展示了

```html
<pc-demo-button />
```
