### ISSUE TITLE
Row组件单行一个无法正确显示

### ISSUE THREAD

**Issue by san-wi** [youzan/vant#8538]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

代码示例：
```
<van-row
  gutter="8"
>
  <van-col span="8"></van-col>
  <van-col span="8"></van-col>
  <van-col span="8"></van-col>

  // 如果下面Col单独一个便不会有padding样式，导致会比其它dom大
  <van-col span="8"></van-col>
</van-row>
```
效果截图：

![image](https://user-images.githubusercontent.com/73974709/114845007-f0ffee00-9e0d-11eb-89f1-a9deaa10d1e0.png)

运行截图：

![image](https://user-images.githubusercontent.com/73974709/114845144-17258e00-9e0e-11eb-8c2a-07c423e22ef9.png)

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6224
