### ISSUE TITLE
[Discuss] vant 的 Icon 默认使用本地字体，造成打包体积变大

### ISSUE THREAD

**Issue by Dante-dan** [youzan/vant#8539]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.13

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/icon#shi-yong-ben-di-zi-ti-wen-jian" target="_blank">https://youzan.github.io/vant/#/zh-CN/icon#shi-yong-ben-di-zi-ti-wen-jian</a>

### 描述问题
> Tips: 从 2.10.13 版本开始，Vant 会默认使用 woff2 格式的本地字体文件，只有在不支持 woff2 字体的低端浏览器上才会加载有赞 CDN 的网络图标。

对于期望使用 CDN 图标的用户来说，默认使用本地字体文件将直接导致包体过大。

是否有配置可以默认使用 CDN 图标的呢？

如果没有，那我认为本地字体文件应该是选配，允许用户做加法。而不是由用户去做减法。

**Comment by Dante-dan** [comment]
只能 `webpack emit` 暴力解法吗？

**Comment by Dante-dan** [comment]
或者像 `antd` 那样，需要手动安装 `@antd/icons`。

我看 `vant/lib/icon/local.less` 就是这么实现的。🌚🌚

**Comment by chenjiahan** [comment]
本地字体和 CDN 字体的体积大小是大致一样的，现在只是默认将字体文件打包到了 Vant 的 CSS 样式文件里。

这样的好处有以下几个：

1. 首屏渲染时，避免了图标在加载过程中会闪烁的问题
2. 避免直接依赖有赞 CDN，部分开发者的应用是内网环境，无法访问有赞 CDN

有什么场景是一定需要引用 CDN 的吗？

**Comment by Dante-dan** [comment]
这是其实是两个问题，可能我上面没有表述清楚：

1. 图标是必选项还是可选项，我认为应该是可选项。
2. 默认应该是本地文件还是 CDN 文件，这个我觉得本地文件是更合适的。

但是现在图标是必选项，本来我是可能通过覆盖 `@font-face` 的方式不请求 CDN 资源。（**类可选项**）

而将本地图标作为默认项之后，无论我使用图标与否，最终这段字体文件都会出现在包体中。

**Comment by chenjiahan** [comment]
明白你的意思了，目前大部分组件都依赖了 Icon 组件，且 Icon 组件是基于 iconfont 而不是 SVG 的，所以没法做到你想要的优化效果。

如果要实现类似于 antd 的图标按需加载，需要有大版本的更新，改变 Icon 的格式和引入方式，这个会考虑在 Vant 4.0 进行支持。

**Comment by Dante-dan** [comment]
好的~

话说 `vue` 未来可能很长一段时间会存在 `2.7` 和 `3.x` 两个版本，这对 `vant` 会带来新的维护挑战吗？
未来还会跟进 `vue 2.x` 版本的更新吗

**Comment by chenjiahan** [comment]
Vant 2 会持续进行维护的，以 bugfix 为主，feature 迭代会逐步放缓。

新功能我们会优先在 Vant 3 中支持，如果 Vant 2 的开发者有对应的需求，我们也会考虑在 Vant 2 中同步实现。

**Comment by Dante-dan** [comment]
emmmmmm，我写了一个插件在 `chunk-vendor` 打包到 `build` 之前，将本地字体变成 `CDN`地址。

如果需要可以踢我一下。

**Comment by 134355** [comment]
> emmmmmm，我写了一个插件在`chunk-vendor`打包到`build`之前，将本地字体变成`CDN`地址。
> 
> 如果需要可以踢我一下。

代码发出来

**Comment by Dante-dan** [comment]
```
class RemoveVantIconPlugin {
  constructor(options) {}
  apply(compiler) {
    compiler.hooks.emit.tap('RemoveVantIconPlugin', (compilation) => {
      const vendorFile =
        compilation.assets[
          Object.keys(compilation.assets).filter((filename) => filename.indexOf('static/css/chunk-vendor') !== -1)[0]
        ];
      const newSource = vendorFile
        .source()
        .replace(
          /@font-face{(.*?)}/,
          `@font-face{font-weight:400;font-family:vant-icon;font-style:normal;font-display:auto;src:url(https://img01.yzcdn.cn/vant/vant-icon-f463a9.woff2)format("woff2"),url(https://img01.yzcdn.cn/vant/vant-icon-f463a9.woff)format("woff"),url(https://img01.yzcdn.cn/vant/vant-icon-f463a9.ttf)format("truetype")}`,
        );
      vendorFile.source = () => newSource;
    });
  }
}
module.exports = RemoveVantIconPlugin;
```
