### ISSUE TITLE
[Bug Report] 倒计时组件自定义样式，时间最小单位如何设置成小时

### ISSUE THREAD

**Issue by Sherrychen1** [youzan/vant#8544]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.13

### Vue 版本
3.0.11

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/count-down#timedata-ge-shi" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/count-down#timedata-ge-shi</a>

### 描述问题
我想超过24小时也显示小时，而不显示天数。

**Comment by chenjiahan** [comment]
设置 format 属性的时候，不要设置 `DD` 就可以咯。

**Comment by Sherrychen1** [comment]
我设置了，但是自定义样式的时候format就失效了

**Comment by Sherrychen1** [comment]
> 设置 format 属性的时候，不要设置 `DD` 就可以咯。

我设置了，但是自定义样式的时候format就失效了

**Comment by chenjiahan** [comment]
自定义样式的话，可以把 days * 24 并累加到 hours 上。
