### ISSUE TITLE
[Bug Report] 将direction 属性设置为 horizontal 后，单选框组在移动端无法实现横向排列

### ISSUE THREAD

**Issue by xiehflg** [youzan/vant#8547]
### 设备 / 浏览器
Android/Ios

### Vant 版本
2.2.10

### Vue 版本
2.6.10

### 重现链接
<a href="https://i9obs.csb.app/" target="_blank">https://i9obs.csb.app/</a>

### 描述问题
Radio单选框组将direction 属性设置为 horizontal 后，在浏览器手机模拟器上可以实现单选框组横向排列，但在App中打开页面单选框组还是纵向排列

**Comment by chenjiahan** [comment]
打开官方示例会有问题吗？App 的系统版本多少，能否截图看下
