### ISSUE TITLE
van-tabs 和 vant-list一起使用时，切换Tab时，有时会触发vant-list的onLoad事件，但实际上没有做列表下拉操作

### ISSUE THREAD

**Issue by EdisonVan** [youzan/vant#8550]
van-tabs 和 vant-list一起使用时，切换Tab时，有时会触发vant-list的onLoad事件，但实际上没有做列表下拉操作

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/8551
