### ISSUE TITLE
[Bug Report] van-tabs 和 vant-list一起使用时，切换Tab时，有时会触发vant-list的onLoad事件，但实际上没有做列表下拉操作

### ISSUE THREAD

**Issue by EdisonVan** [youzan/vant#8551]
### 设备 / 浏览器
iPhone6/7/8

### Vant 版本
2.9.3

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/youzan/vant/issues/8550" target="_blank">https://github.com/youzan/vant/issues/8550</a>

### 描述问题
van-tabs 和 vant-list一起使用时，切换Tab时，有时会触发vant-list的onLoad事件，但实际上没有做列表下拉操作

**Comment by chenjiahan** [comment]
只要浏览器的 scroll 事件触发，就会触发 List 的 load 事件，参见 https://vant-contrib.gitee.io/vant/#/zh-CN/list#list-de-yun-xing-ji-zhi-shi-shi-me

**Comment by Huangfuyuru** [comment]
> 只要浏览器的 scroll 事件触发，就可能会触发 List 的 load 事件，参见 https://vant-contrib.gitee.io/vant/#/zh-CN/list#list-de-yun-xing-ji-zhi-shi-shi-me

那怎么解决这个问题呢？有两个tab页签，第一个tab页面中的vant-list下拉到了第二页，然后切换到tab，这个时候第二个tab的vant-list也会直接滚动到第二页，感觉不太优化，求教
