### ISSUE TITLE
van-dialog报错

### ISSUE THREAD

**Issue by NiBoTe** [youzan/vant#8552]
Unknown custom element: <van-dialog> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

node: v14.16.0
npm：6.14.11

**Comment by NiBoTe** [comment]
<van-dialog v-model="show" title="标题" show-cancel-button>
  <img src="https://img01.yzcdn.cn/vant/apple-3.jpg" />
</van-dialog> 用的例子

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
