### ISSUE TITLE
NoticeBar 在微信端 iPhone12 系统版本14.1下 滚动失效

### ISSUE THREAD

**Issue by cantatas** [youzan/vant#8553]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by cantatas** [comment]
滚动1-2次后停止滚动，看不到文本内容。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
