### ISSUE TITLE
[Bug Report] Field 样式错误

### ISSUE THREAD

**Issue by wjq990112** [youzan/vant#8554]
### 设备 / 浏览器
OnePlus 8 Pro / Chrome Android

### Vant 版本
3.0.13

### Vue 版本
3.0.11

### 重现链接
<a href="https://vue3-jsx-template.vercel.app/" target="_blank">https://vue3-jsx-template.vercel.app/</a>

### 描述问题
 Field 样式错误，label 宽度过大，与输入框各占一半了。
左侧的 label 的 flex 属性无法被覆盖，初步判断是按需引入 babel-plugin-import 的问题，查看 style 标签后发现 van-field__label 类所在的 style 标签在 van-cell__title 类所在的 style 标签前，导致后者将前者的 flex 属性覆盖。

![image](https://user-images.githubusercontent.com/45777252/115106016-e6239580-9f94-11eb-8057-f14dc03681b5.png)

![image](https://user-images.githubusercontent.com/45777252/115106078-4b778680-9f95-11eb-8cd5-4afc6fa3ba6f.png)

![image](https://user-images.githubusercontent.com/45777252/115106094-5f22ed00-9f95-11eb-9fe4-05c663745885.png)

首次启动 devServer 时样式正常，刷新后复现。

**Comment by wjq990112** [comment]
@chenjiahan  麻烦看一下，问题比较奇怪，之前 build 后问题就消失了，现在即使 build 问题依然存在。

**Comment by chenjiahan** [comment]
给个仓库链接？

**Comment by wjq990112** [comment]
https://github.com/wjq990112/Vue3-JSX-Template

**Comment by wjq990112** [comment]
@chenjiahan 仓库已提供，麻烦看一下。

**Comment by chenjiahan** [comment]
定位了，下个版本修复

**Comment by wjq990112** [comment]
收到，感谢！

**Comment by wjq990112** [comment]
当前 bug 在 DevServer 中已修复，但在 build 后首次加载时仍然存在 @chenjiahan

**Comment by chenjiahan** [comment]
@wjq990112 还是上面的复现链接么

**Comment by wjq990112** [comment]
> @wjq990112 还是上面的复现链接么

是的

**Comment by chenjiahan** [comment]
@wjq990112 我 build 试了下没问题，并且这部分的逻辑在 dev 和 build 是一致的

如果有差异，建议自行检查下构建配置，是不是有样式重复打包了

**Comment by dongH555** [comment]
同样的问题，我在3.2.2版本也出现了
![WechatIMG38](https://user-images.githubusercontent.com/31405731/132616221-f2574b9a-ae61-4d22-9cb9-b4b649ecddd8.png)
![WechatIMG37](https://user-images.githubusercontent.com/31405731/132616227-4500bca4-4213-4d10-90cb-43612729f08e.png)

**Comment by BruceLanCode** [comment]
vant@2.12.27按需加载也存在这个问题呢，如果先进入有Field组件的页面，先注入了van-field__label样式，Filed页面是正常显示的，但下一个页面如果引入Cell组件，后面注入的van-cell__title样式会覆盖van-field__label关于flex的设置，导致上面的label过宽的问题
