### ISSUE TITLE
CellSwipe  和 list 在一起使用，往下滑动的时候，很容易就触发了CellSwipe 的左滑或者右滑事件，

### ISSUE THREAD

**Issue by shiqian123** [youzan/vant#856]
手机 vivo ，vant版本 1.0.4，
![1523498136 1](https://user-images.githubusercontent.com/9497069/38652257-bb86b8a0-3e37-11e8-8966-1c85e4b47828.jpg)
```
<template>
<div>
  <van-pull-refresh v-model="isLoading" @refresh="onRefresh">
    <van-list
        v-model="loading"
        :finished="finished"
        @load="onLoad"
        >
          <!-- <van-cell v-for="item in list" :key="item" :title="item + '点击进入商品列表页'" @click="goShopDetail"/> -->
          <van-cell-swipe :right-width="65" :left-width="65" v-for="item in list" :key="item">
            <span slot="left">选择</span>
            <van-cell-group>
                <van-cell :title="item + '点击进入商品列表页'" @click="goShopDetail" />
            </van-cell-group>
            <span slot="right" class="right">删除</span>
          </van-cell-swipe>
        </van-list>
  </van-pull-refresh>
</div>

</template>

```

**Comment by shiqian123** [comment]
手机 vivo ，vant版本 1.0.4，
<template>
<div>
  <van-pull-refresh v-model="isLoading" @refresh="onRefresh">
    <van-list
        v-model="loading"
        :finished="finished"
        @load="onLoad"
        >
          
          <van-cell-swipe :right-width="65" :left-width="65" v-for="item in list" :key="item">
            <span slot="left">选择</span>
            <van-cell-group>
                <van-cell :title="item + '点击进入商品列表页'" @click="goShopDetail" />
            </van-cell-group>
            <span slot="right" class="right">删除</span>
          </van-cell-swipe>
        </van-list>
  </van-pull-refresh>
</div>

</template>

**Comment by chenjiahan** [comment]
感谢反馈，目前 CellSwipe 在滑动时确实过于容易触发，下个版本优化

**Comment by chenjiahan** [comment]
已在 1.0.5 版本修复
