### ISSUE TITLE
[Bug Report] cdn引入失败

### ISSUE THREAD

**Issue by toesbieya** [youzan/vant#8560]
### 设备 / 浏览器
Chrome

### Vant 版本
2.12.14

### Vue 版本
2.6.12

### 重现链接
<a href="https://codepen.io/toesbieya/pen/LYxJRXm" target="_blank">https://codepen.io/toesbieya/pen/LYxJRXm</a>

### 描述问题
cdn上提供的文件是node环境的？导致浏览器上引入时报错

是不再提供commonjs，只支持webpack环境吗？

![微信截图_20210419091048](https://user-images.githubusercontent.com/45418945/115168969-4c243000-a0ef-11eb-8ce6-60d8b898d756.png)
![微信截图_20210419091100](https://user-images.githubusercontent.com/45418945/115168971-4d555d00-a0ef-11eb-8ed0-6633703e2aaf.png)

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/115172473-f1430680-a0f7-11eb-83e0-9ead109201c4.png)

是 vant.min.js，不是 index.min.js。

注意看文档

**Comment by toesbieya** [comment]
尴尬

不过建议jsdeliver上的默认文件通过package.json改成vant.min.js

**Comment by chenjiahan** [comment]
好的，下个版本会加上
