### ISSUE TITLE
[Bug Report] Internationalization-zh-HK weekdays issue

### ISSUE THREAD

**Issue by sammimk830** [youzan/vant#8562]
### 设备 / 浏览器
Win10/Chrome

### Vant 版本
3.0.14

### Vue 版本
3.0.11

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/src/locale/lang/zh-HK.ts" target="_blank">https://github.com/youzan/vant/blob/dev/src/locale/lang/zh-HK.ts</a>

### 描述问题
weekdays: ['日', '壹', '二', '三', '四', '五', '六'] need change to: ['日', '一', '二', '三', '四', '五', '六'],
香港也不會用到"壹"作為日曆顯示

**Comment by chenjiahan** [comment]
欢迎 PR 喔

**Comment by chenjiahan** [comment]
已在 2.12.15 版本优化
