### ISSUE TITLE
[Bug Report] 部分手机微信浏览器picker无法滑动

### ISSUE THREAD

**Issue by zhangyan1994** [youzan/vant#8563]
### 设备 / 浏览器
iPhone 7 Plus / 微信浏览器 7.0.15

### Vant 版本
3.0.14

### Vue 版本
3.0.0

### 重现链接
<a href="http://h5.zhongxinfu.cn/student/index.html#/" target="_blank">http://h5.zhongxinfu.cn/student/index.html#/</a>

### 描述问题
该设备下，选择性别年纪省市区picker，需要等待几秒钟后 才能进行正常滑动，刚进页面无法触发

**Comment by chenjiahan** [comment]
麻烦提供下 https://codesandbox.io/s/m5v3f 复现链接
