### ISSUE TITLE
[Bug Report] DropdownMenu组件在绝对定位和偏移组合居中时，下拉框无法显示

### ISSUE THREAD

**Issue by toxicantcc** [youzan/vant#8565]
### 设备 / 浏览器
Chrome

### Vant 版本
2.12.13

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/toxicantcc/vant_issue_demo/blob/main/demo.vue" target="_blank">https://github.com/toxicantcc/vant_issue_demo/blob/main/demo.vue</a>

### 描述问题
DropdownMenu组件在绝对定位和偏移组合居中时，下拉框无法显示

**Comment by chenjiahan** [comment]
把 `DropdownMenu` 嵌套在 `Tabs` 等组件内部使用时，可能会遇到下拉菜单位置错误的问题。这是因为在 Chrome 浏览器中，transform 元素内部的 fixed 布局会降级成 absolute 布局，导致下拉菜单的布局异常。

将 `DropdownItem` 的 `get-container` 属性设置为 `body` 即可避免此问题：

```html
<van-dropdown-menu>
  <van-dropdown-item get-container="body" />
  <van-dropdown-item get-container="body" />
</van-dropdown-menu>
```
