### ISSUE TITLE
[Bug report] 在钉钉 APP 中，引入 vant 3.x 的样式文件会导致页面空白 

### ISSUE THREAD

**Issue by zhengxs2018** [youzan/vant#8566]
### 设备 / 浏览器
安卓 华为 p30 钉钉 app 6.0.13

### Vant 版本
3.0.12

### Vue 版本
3.0.11

### 重现链接
<a href="https://codesandbox.io/s/happy-archimedes-7jv2e" target="_blank">https://codesandbox.io/s/happy-archimedes-7jv2e</a>

### 描述问题
在 vitejs 中使用 vant3.x 版本，只要引入 css ，不管是 `vant/lib/index.css` 还是 独立的组件样式，只要引入就显示空白，但编译正常，使用 `eruda` 工具查看也是无任何异常，只要去掉样式，单独引入组件是正常的。

> 注意：不管是什么浏览器，显示都正常，同时用同样的环境 `ant-design-vue 2.x` 引入 css 也正常

**Comment by zhengxs2018** [comment]
但切换到 less 文件却没有问题，有点无奈了

**Comment by chenjiahan** [comment]
用官网示例会有问题不？

**Comment by Ttou** [comment]
我用的是 vite-plugin-style-import 插件，没碰到这种情况

**Comment by zhengxs2018** [comment]
@Ttou 求示例

**Comment by Ttou** [comment]
@zhengxs2018
代码：https://gitee.com/jh_shot/mobile-template
演示：http://jh_shot.gitee.io/mobile-template/#/

**Comment by Ttou** [comment]
@chenjiahan 
用了按需加载的话 Field 组件的 .van-cell 样式在生产环境会丢失，现在临时全局引入 Cell 组件解决，有什么其它办法？

**Comment by zhengxs2018** [comment]
@chenjiahan 一样，我手机显示空白

**Comment by zhengxs2018** [comment]
> @zhengxs2018
> 代码：https://gitee.com/jh_shot/mobile-template
> 演示：http://jh_shot.gitee.io/mobile-template/#/

🙏

**Comment by zhengxs2018** [comment]
@chenjiahan 发现了，只是 vite 编译才有这个问题，vue3 使用 @vue/cli 模式就没这个问题

**Comment by chenjiahan** [comment]
如果只有 vite 不行，那应该是编译层面的问题，组件这边不一定能解决。

**Comment by zhengxs2018** [comment]
@chenjiahan  那我是要先关闭么？

**Comment by chenjiahan** [comment]
先关闭把~ 建议到 vite 仓库下反馈并提供可复现的仓库喔
