### ISSUE TITLE
移动端适配的问题,  我看单位用的是px, 那这样的话我们本身基于rem做的适配是不是对组件就没有效果了

### ISSUE THREAD

**Issue by Mmpc1994** [youzan/vant#859]
我看单位用的都是px 那么这样的话我们项目里面用rem 或者 vw 应该对组件就没有效果了 
我看了文档没有统一的解决方案

**Comment by chenjiahan** [comment]
是的，不过可以配合一些 loader 去转换，之后我们也会提供官方方案
