### ISSUE TITLE
[Feature Request] 竟然没有input / textarea 咱能不能先停一下拥抱vue3，回来抱一抱vue2加上这俩基础组件

### ISSUE THREAD

**Issue by hugselina2019** [youzan/vant#8591]
### 这个功能解决了什么问题
说实话 UI的设计真跟form组件搭不上什么边。。。还得用基础组件自定义。 没有我只能去怼UI了。。

### 描述您想要的解决方案
出一下van-input / van-textarea吧，

### 建议的API是什么样的
样式   v-modal就好

**Comment by chenjiahan** [comment]
https://vant-contrib.gitee.io/vant/#/zh-CN/field

眼神不好？

**Comment by Ttou** [comment]
输入一直是 field 吧 😒

**Comment by zhoucan38** [comment]
略微尴尬😒

**Comment by hugselina2019** [comment]
> https://vant-contrib.gitee.io/vant/#/zh-CN/field
> 
> 眼神不好？

可能大佬不太理解，实际项目中很多页面field不符合UI需求。 需要一个类似于element 的 el-input 或者是 antd-vue 的a-input。 好久前的问题了 感谢回答
