### ISSUE TITLE
[Bug Report] ssr tab window is not defined

### ISSUE THREAD

**Issue by laizp** [youzan/vant#8594]
### 设备 / 浏览器
win10 / chrome

### Vant 版本
3.0.14

### Vue 版本
3.0.11

### 重现链接
<a href="https://github.com/laizp/vant-ssr-test" target="_blank">https://github.com/laizp/vant-ssr-test</a>

### 描述问题
1. **切换到 `tab-test` 分支**
2. `npm run build && node server.js`
3. 浏览器打开，随即控制台报错：
```sh
[Vue warn]: Unhandled error during execution of setup function 
  at <VanTabs>
(node:4844) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at useScrollParent (E:\**\node_modules\@vant\use\dist\cjs\useScrollParent\index.js:35:37)
    at setup (E:\**\node_modules\vant\lib\tabs\Tabs.js:91:45)
……
```
即ssr下window未定义的问题

**Comment by chenjiahan** [comment]
下个版本修复

**Comment by chenjiahan** [comment]
已在 3.0.15 版本修复
