### ISSUE TITLE
[Bug Report] ssr SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by laizp** [youzan/vant#8595]
### 设备 / 浏览器
win10 / Chrome

### Vant 版本
3.0.14

### Vue 版本
3.0.11

### 重现链接
<a href="https://github.com/laizp/vant-ssr-test" target="_blank">https://github.com/laizp/vant-ssr-test</a>

### 描述问题
确保在`master`分支
 `npm run build && node server.js`
运行`server.js`会报错：
```sh
E:\**\node_modules\vant\es\tabs\style\index.js:1
import '../../style/base.css';
^^^^^^

SyntaxError: Cannot use import statement outside a module
……
```

**Comment by chenjiahan** [comment]
SSR 不支持 ESModule，把 `import 'vant/es/tabs/style';` 改成 `import 'vant/lib/tabs/style';` 即可
