### ISSUE TITLE
[Bug Report] tab list组合时，keep-alive无法保留list滚动位置

### ISSUE THREAD

**Issue by Jinni6012** [youzan/vant#8596]
### 设备 / 浏览器
微信浏览器

### Vant 版本
2.6.0

### Vue 版本
2.6.11

### 重现链接
<a href="http://view.tinsine.cn/merch/orders" target="_blank">http://view.tinsine.cn/merch/orders</a>

### 描述问题
使用van-tab   van-pull-refresh   van-list组合开发订单页面，keep-alive模式下从下一页面返回时仅缓存了tab标签的位置，但无法恢复list之前的滚动位置。

**Comment by chenjiahan** [comment]
List 组件仅负责加载滚动内容，滚动位置和组件没有关系。

**Comment by weijiatan456** [comment]
假如我记录了滚动高度，van-list能提供一下回滚高度的方法吗？

**Comment by weijiatan456** [comment]
解决了，大致讲一下思路：
**1、现在状态里面记录**
`mutations: {
    SETKEEPALIVE(state, param){
        const index = state.keepAlive.findIndex(function(item) {
            return item.obj === param.obj;
        });
        if(index != -1){//编辑
            state.keepAlive[index] = param
        }else{//新增
            state.keepAlive.push(param);
        }
    },
    REMOVEKEEPALIVE(state, param) {
        const index = state.keepAlive.findIndex(function(item) {
            return item.obj === param.obj;
        });
        if (index != -1) {
            state.keepAlive.splice(index, 1)
        }
    }
},`

**2、在页面滚动元素，滚动高度，include的对象把这些存储到状态里面去**
`beforeRouteLeave(to, from, next) {
    if (to.name === 'detail'){ // 列表页前进到详情
        let el = document.getElementById('content') // 滚动元素
        this.$store.commit('SETKEEPALIVE', {obj:'list',scrollNode:el,scrollTop:el.scrollTop})
    } else {// 列表页返回其他页
        this.$store.commit('REMOVEKEEPALIVE', {obj:'list',scrollNode:'',scrollTop:0})
    }
    next()
}`


**3、大家在各自的路由处理一下要存储的页面：**
`<keep-alive :include="Array.from(new Set(keepAlive.map(item=>item.obj))).join(',')">
    <component :is="Component" class="child-view" />
</keep-alive>`

注：keep-alive的include用法可以看官方文档：https://v3.cn.vuejs.org/api/built-in-components.html#keep-alive

**4、在缓存的页面出发activated**
`onActivated(() => {
    store.state.keepAlive.forEach(item=>{
        if(item.obj == 'list'){
            item.scrollNode.scrollTop = item.scrollTop
        }
    })
})`

ok，大功告成！

**Comment by tongteng** [comment]
let el = document.getElementById('content') // 滚动元素
你这个content是给哪个元素的，为什么我获取不到元素的滚动高度，给外层wrapper  pullrefresh van-list 都拿不到scrollTop
