### ISSUE TITLE
[Bug Report] css兼容性：表单验证radio，checkbox ，样式出问题

### ISSUE THREAD

**Issue by MEEllis** [youzan/vant#8598]
### 设备 / 浏览器
qq浏览器，Safari浏览器

### Vant 版本
2.12.14

### Vue 版本
2.6.11

### 重现链接
<a href="http://www.h-service.cn/surveyfronttest/#/questionPart3" target="_blank">http://www.h-service.cn/surveyfronttest/#/questionPart3</a>

### 描述问题
重新步骤：
1.使用qq浏览器或者Safari浏览器 打开重现链接
2.直接点击最下面的提交按钮
3..van-field--error .van-field__contro 下-webkit-text-fill-color: currentColor; 这个属性存在兼容性问题;
4.报错截图已经放在问题的最底部！

**Comment by chenjiahan** [comment]
这个已经修复了，升级最新版即可。
