### ISSUE TITLE
上传组件在部分安卓机型点击没有任何反应 无法弹出选择文件弹框

### ISSUE THREAD

**Issue by muyi0728** [youzan/vant#860]
![image](https://user-images.githubusercontent.com/23134854/38655379-d218822e-3e46-11e8-863f-695a8029623c.png)
![image](https://user-images.githubusercontent.com/23134854/38655402-ff4c6ada-3e46-11e8-9950-983523829754.png)

**Comment by chenjiahan** [comment]
请问具体的安卓机型和浏览器是？

**Comment by muyi0728** [comment]
机型：oppo A57  android版本： 6.0.1  浏览器： 微信浏览器

**Comment by chenjiahan** [comment]
参考 https://github.com/youzan/vant/issues/910
