### ISSUE TITLE
[Bug Report] Dialog 不能作为JSX使用

### ISSUE THREAD

**Issue by rpdg** [youzan/vant#8600]
### Vant 版本
3.0.12

### Vue 版本
3.0.11

### 描述问题
我想在 Dialog 里嵌入自己的组件，然而在TSX方式下写，vscode报错如下

![image](https://user-images.githubusercontent.com/1169162/115681224-e81b9900-a386-11eb-8f9c-003a480f08f3.png)

**Comment by chenjiahan** [comment]
Dialog 是函数，组件是 Dialog.Component
