### ISSUE TITLE
[Feature Request] French Language Support

### ISSUE THREAD

**Issue by rsaf** [youzan/vant#8605]
### What problem does this feature solve
French Language Support on Vant components

### Describe the solution you'd like
I'm building an application that displays content in French. Currently there no way to switch components to display in French language. It would be great to have that.

### What does the proposed API look like
Locale.use('fr-FR', frFR);

**Comment by chenjiahan** [comment]
If you can’t find the language you need, please send us a Pull Request to add the new language pack, you can refer to Add [German language pack PR](https://github.com/youzan/vant/pull/7245).
