### ISSUE TITLE
[Bug Report] picker设置columns-field-names对于非嵌套数据解析失败

### ISSUE THREAD

**Issue by ParkerFiend** [youzan/vant#8607]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.14

### Vue 版本
3.0.11

### 重现链接
<a href="https://codesandbox.io/s/3c5y2" target="_blank">https://codesandbox.io/s/3c5y2</a>

### 描述问题
非嵌套数据如果传入value-key可正常解析，
如果替换为columns-field-names对象后，导致dataType解析为object导致渲染失败。

**Comment by chenjiahan** [comment]
你的用法有错误。

columns-field-names 对象中的 `text` 字段对应旧版的 `value-key` 属性；values 指的是嵌套的子列表信息，是一个数组，传入 number 会导致报错。

**Comment by QianTangrong** [comment]
values为什么会表示子列表信息，那children字段表示什么
