### ISSUE TITLE
引用toast组件会出现警告信息

### ISSUE THREAD

**Issue by zhaofengping** [youzan/vant#861]
import { Toast } from 'vant';
FeedbackInfoService.replyFeedback(params, replyData).then(response => {
        if (response.status == 200) {
          Toast.success('回复成功');
        }
      });
![123](https://user-images.githubusercontent.com/30971327/38659984-48027974-3e5e-11e8-9d66-59e3c5b02a4c.png)

**Comment by chenjiahan** [comment]
如果 Vue 版本在 2.4 以下，建议升级 Vue 版本再试

**Comment by FFFEGG** [comment]
vue2.5  也提示Toast is not defined

**Comment by zhaofengping** [comment]
Vue版本是2.5.2

**Comment by chenjiahan** [comment]
能否提供一个复现问题的 jsfiddle
