### ISSUE TITLE
[Bug Report] Uploader 自定义上传区域时，一次性多选图片到maxCount张，再删除一张，上传图标没有出现

### ISSUE THREAD

**Issue by LiZhaji** [youzan/vant#8610]
### 设备 / 浏览器
chrome 83.0.4103.61

### Vant 版本
2.10.12

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-cw7xz?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-cw7xz?file=/src/App.vue</a>

### 描述问题
重现：
Uploader 自定义上传区域时，一次性多选图片到maxCount张(或者大于一张，多选几次)，再删除一张，上传图标没有出现，需要把所有的图片都删掉才会出现。

前提：
单文件组件对该自定义区域使用了区域样式（scoped）。

原因：
重新渲染时该样式没有添加上scoped标识导致样式丢失。

临时解决方法：
不使用区域样式。

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 2.12.15 版本修复
