### ISSUE TITLE
[Feature Request] 日历组件

### ISSUE THREAD

**Issue by 863062879** [youzan/vant#8611]
### 这个功能解决了什么问题
日历选择区间跨度比较大时   会一次性渲染所有的月份数据  会导致渲染变慢 卡顿   比如：要选2010-01-01-2021-04-25  就必须设定最大最小可选范围大于要选范围  建议使用异步加载

### 描述您想要的解决方案
使用异步加载渲染  首次只渲染当前月   当向上滚动加载显示上月 以此类推  向下滚动加载下月  

### 建议的API是什么样的
asyncLoad

**Comment by 863062879** [comment]
@chenjiahan 下版本会不会考虑支持这个功能了  大概啥时候

**Comment by chenjiahan** [comment]
目前日历组件是默认开启 lazy-render（按需渲染） 能力的

**Comment by ErvingZheng** [comment]
> 目前日历组件是默认开启 lazy-render（按需渲染） 能力的

设置了min-date和max-date以后，lazy-render会失效
