### ISSUE TITLE
Toast 显示异常

### ISSUE THREAD

**Issue by xingda** [youzan/vant#8612]
全局注册Toast，同样的使用
this.$toast('bla bla')
在首页加载的时候就正常显示，
在其他页面使用的时候，变成白色的方块，文字也没有了。

请问是不是使用上有啥问题，网上找了半天没有查到解决方案。甚至都没有找到出现过类似的问题;-(

**Comment by xingda** [comment]
补充一点，是不是因为我在调用了toast之后，马上做了vue router的跳转？
但这应该也是个常用的场景吧？

**Comment by xingda** [comment]
我用的vue3，vant版本3.0.10

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by LDXu** [comment]
@xingda  后面有解决吗？

**Comment by LDXu** [comment]
@xingda  解决了。发现调用了二次。后面那次没传入字符串
