### ISSUE TITLE
[Bug Report] VanStepper组件中输入以"0"开头，后边跟上其他数字，例如输入了："02"，在事件处理函数中无法修改其绑定的值。

### ISSUE THREAD

**Issue by geeklibin** [youzan/vant#8615]
### 设备 / 浏览器
Chrome

### Vant 版本
3.0.9

### Vue 版本
3.0.0

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-p0ne8?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-p0ne8?file=/src/App.vue</a>

### 描述问题
功能主要实现的是，当在Stepper组件中自定义输入数值，并在Stepper 失焦@blur后去检查当前输入的值是否为5的倍数，如果不是则向下改成5的倍数。
``` html
<van-stepper :min="0" :step="step" v-model="count" @blur="e => checkCount(e)"/>
<input :min="0" type="number" v-model="count" @blur="e => checkCount(e)"/>
```
``` javascript
...
setup() {
    let step = 5;
    let count = ref(0)
    let checkCount = (e) => {
      /**如果输入的不是step的倍数，则向下改成step的倍数 */
      if(parseInt(e.target.value) % step !== 0) {
        count.value = parseInt(e.target.value) - (parseInt(e.target.value) % step)
      }
    }
    return {
      step,
      count,
      checkCount
    }
  }
...
```
正常输出：
- 输入16；输出 15;
- 输入12；输出 10;
- 输入7 ；输出 5;
- 输入3 ；输出 0;

一开始看起来功能是正常的，但是只要在Stepper输入框前面多一个"0"，功能就变的不对了
异常输出：
- 输入016；输出16；
- 输入012；输出12；
- 输入07；输出7；
- 输入03；输出3；

预想中的结果：
- 输入016；输出15；
- 输入012；输出10；
- 输入07；输出5；
- 输入03；输出0；

**Comment by chenjiahan** [comment]
已在 3.0.16 版本修复
