### ISSUE TITLE
[Bug Report] Cannot read property 'width' of null

### ISSUE THREAD

**Issue by taotao7** [youzan/vant#8616]
### 设备 / 浏览器
chrome edge safari

### Vant 版本
3.0.14

### Vue 版本
3.0.11

### 重现链接
<a href="https://codepen.io/moca_tao7/pen/mdRvpGR" target="_blank">https://codepen.io/moca_tao7/pen/mdRvpGR</a>

### 描述问题
 <van-swipe :autoplay="3000" :show-indicators="false" class="logo-swipe">
        <van-swipe-item class="logos">
          <img
            v-for="(item, key) in logosArrayOne"
            :src="item"
            :key="key"
            alt=""
          />
        </van-swipe-item>
        <van-swipe-item class="logos">
          <img
            v-for="(item, key) in logosArrayTwo"
            :src="item"
            :key="key"
            alt=""
          />
        </van-swipe-item>
      </van-swipe>

轮播图报错
Cannot read property 'width' of null
无法滚动轮播图
![image](https://user-images.githubusercontent.com/24582204/115982907-da595400-a5d0-11eb-8c34-d8889d5afe4f.png)

**Comment by chenjiahan** [comment]
复现链接无法运行，麻烦重新提供下
