### ISSUE TITLE
使用 Search 组件的search 方法获取不到值

### ISSUE THREAD

**Issue by wpbjiuy** [youzan/vant#8617]
`<van-search
    show-action
    placeholder="请输入搜索关键词"
    @search="value => searchText = value"
    @cancel="() => showSlcAddress = false"
  />`
  输入值后回车触发search， value 的值是 undefined

**Comment by chenjiahan** [comment]
请先绑定 v-model 属性

**Comment by wpbjiuy** [comment]
> 请先绑定 v-model 属性

绑定了也是一样的， 而且绑定了之后会多一些额外的代码逻辑。比如只有在确认后才把值给到对应的地方
