### ISSUE TITLE
[Feature Request] Uploader增加对不同类型限制不同文件大小的功能

### ISSUE THREAD

**Issue by Tindtily** [youzan/vant#8618]
### 这个功能解决了什么问题
我们有需求：对GIF限制在5MB，JPG限制在10MB。目前这个组件不支持这样使用。

### 描述您想要的解决方案
可以对不同类型图片限制不同的文件大小

### 建议的API是什么样的
:max-size= [{type:'jpg', size: '1024*1024'},{type:'default', size: '1024* 1024  * 10'}]

**Comment by chenjiahan** [comment]
已在 2.12.20 和 3.0.17 版本支持函数格式

**Comment by pocketChao** [comment]
麻烦问下 设置了max-size 在选择视频的时候可以过滤掉吗  现在在chorme上无法过滤掉大与max-size的视频
