### ISSUE TITLE
[Bug Report] Vant Tabs 从第三方页面回到主页面，在ios13.1.3系统的手机下，回显 tab 的active 时，激活的active没有滚动到可视窗口中

### ISSUE THREAD

**Issue by jzsn2018** [youzan/vant#8619]
### 设备 / 浏览器
ios 13.1.3

### Vant 版本
2.8.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-cnkw7?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-cnkw7?file=/src/App.vue</a>

### 描述问题
Vant Tabs 从第三方页面回到主页面( 主页面跳转到第三方页面之前发生了上下滚动)，在ios13.1.3 系统的手机下，回显 tab 的active 时，激活的active没有滚动到可视窗口中, 在其他设备中没有出现这个问题。目前只在ios13.1.3设备中出现了这种情况
![image](https://user-images.githubusercontent.com/33984354/115984884-d2eb7800-a5db-11eb-91a2-8c2db5528434.png)
谢谢~

**Comment by chenjiahan** [comment]
手头没有 iOS 13.1.3 的机器，用 iOS 14 试了下没复现，如果是个别系统版本的问题，组件层面估计不会考虑兼容

**Comment by jzsn2018** [comment]
> 手头没有 iOS 13.1.3 的机器，用 iOS 14 试了下没复现，如果是个别系统版本的问题，组件层面估计不会考虑兼容

谢谢回复 ; 我自己的ios14也是没有复现,但是测试的测试机出现了这个bug. 哎 , 我再看看有没有折中的办法.

**Comment by chenjiahan** [comment]
嗯嗯，有合适的兼容方案可以提 Pull Request 喔
