### ISSUE TITLE
[Bug Report] tab 组件滚动导航 控制台报 el.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by GryphonWang** [youzan/vant#8621]
服务端渲染  vant 2.12.4
页面滑动控制台持续报错
页面中有节点是v-if渲染
有部分节点是
![image](https://user-images.githubusercontent.com/31873094/115990352-56659300-a5f5-11eb-89ec-2b01d5d377de.png)
导致页面控制台持续报错
@chenjiahan 打扰帮忙查看

**Comment by chenjiahan** [comment]
麻烦提供一下最小复现仓库

**Comment by changweihua** [comment]
可以考虑在onMounted内，使用nextTick，保证页面渲染后加载数据

**Comment by yanstars** [comment]
我这之前是传入了 scrollspy 属性但是没有在 vant-tab插入slot报错的 可以检查下 有没有slot  或者关掉  scrollspy
