### ISSUE TITLE
Toast显示异常，我已经找到问题的原因并解决了，但Vant代码可能还是需要优化一下，但应该不是严重问题

### ISSUE THREAD

**Issue by xingda** [youzan/vant#8622]
@chenjiahan 辛苦再看一遍哈

问题是这样的，如果我在某个vue的页面中包含了某个vue控件，而这个控件恰巧局部注册并使用了Popup控件，而我在这个vue页面中局部注册并使用Toast控件，就会出现显示异常的问题，所有Toast的属性都失灵了。
因为我查看了一下页面元素的css，发现vant-toast类的background-color被vant-popup的属性给覆盖了，可能其他属性也存在类似问题，所以导致上述问题。
解决方法很简单，就是在这个页面中也局部注册一下Popup控件，即使不使用该控件，更准确的说是import一下即可，不需要在vue component中注册Popup控件。

这种使用场景是不是不多？所以，出现这个问题的概率不大？否则，应该是一碰一个准儿吧。

再说一下我的环境：
  "dependencies": {
    "vant": "^3.0.10",
    "vue": "^3.0.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.1.5",
    "@vue/compiler-sfc": "^3.0.5",
    "vite": "^2.0.5",
    "vite-plugin-imp": "^2.0.4",
    "vue-router": "^4.0.3"
  }
另外，所有页面通过router-view懒加载和keep-alive，但感觉这个应该没啥影响吧

**Comment by chenjiahan** [comment]
提供下复现仓库？

**Comment by xingda** [comment]
稍等回头我做一个哈
