### ISSUE TITLE
使用 pointer 事件 替换 touch 事件

### ISSUE THREAD

**Issue by defghy** [youzan/vant#8625]
设备 / 浏览器
pc/chrome

Vant 版本
2.12.15

Vue 版本
2.6.12

重现链接

描述问题
touch事件兼容性没有pointer好，pc端无法使用，h5页面有时候会在pc端打开，需要保证基本的可交互性

**Comment by chenjiahan** [comment]
参见 https://vant-contrib.gitee.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei

**Comment by defghy** [comment]
感谢
