### ISSUE TITLE
日历控件 日期文案 formatter

### ISSUE THREAD

**Issue by x79818253** [youzan/vant#8632]
日历控件 日期文案  通过异步请求来显示文案、日历滑动到下个月份、导致上个月份的底部文案消失
![QQ图片20210428183045](https://user-images.githubusercontent.com/46957229/116389843-01718900-a850-11eb-9c2e-5d9bb1a39fea.png)
![QQ图片20210428183113](https://user-images.githubusercontent.com/46957229/116389847-02a2b600-a850-11eb-8058-0cfa8a11b212.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
