### ISSUE TITLE
[Bug Report] 在使用Popovertan气泡弹出框组件时，项目中使用了fastclick，会造成点击失效，要点击两次才行

### ISSUE THREAD

**Issue by sijinglei** [youzan/vant#8633]
### 设备 / 浏览器
ios移动端浏览器

### Vant 版本
2.12.15

### Vue 版本
2.6.12

### 重现链接
<a href="https://blog.csdn.net/weixin_30788619/article/details/97074942" target="_blank">https://blog.csdn.net/weixin_30788619/article/details/97074942</a>

### 描述问题
在使用Popovertan气泡弹出框组件时，项目中使用了fastclick，会造成点击失效，要点击两次才行

**Comment by chenjiahan** [comment]
这个是 fastclick 的问题，建议不要使用 fastclick
