### ISSUE TITLE
[Bug Report] cascader组件在popup中使用，v-model绑定的值清空时，cascader组件显示错误

### ISSUE THREAD

**Issue by buxiuchen** [youzan/vant#8634]
### 设备 / 浏览器
Microsoft Edge  90.0.818.49

### Vant 版本
3.0.13

### Vue 版本
3.0.5

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-us3qb?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-us3qb?file=/src/App.vue</a>

### 描述问题
将cascader组件放在popup组件中，打开popup，cascader选完值之后popup隐藏，之后将cascader组件v-model绑定的值清空，打开popup，此时cascader组件显示错误

**Comment by chenjiahan** [comment]
原因跟这个类似：https://github.com/youzan/vant/issues/2750

后续会在组件内部加一些适配逻辑。

**Comment by chenjiahan** [comment]
已在 3.0.16 版本修复
