### ISSUE TITLE
[Feature Request] Cascader级联选择器，希望增加最后一级多选功能

### ISSUE THREAD

**Issue by heweilong-hub** [youzan/vant#8637]
### 这个功能解决了什么问题
目前使cascader组件时候，遇到了需要多选的需求，比如医院环境下开立处方，检查等

### 描述您想要的解决方案
cascader增加一个是否多选的参数，或者用一个新的组件cascader-multiple代表多选组件

### 建议的API是什么样的
建议cascader增加一个是否多选的参数

**Comment by chenjiahan** [comment]
暂无计划支持呢

**Comment by itchaox** [comment]
我也遇到的同样的需求，也是最后一级需要多选操作，需要自己重写级联，确实有点做不来哦

itchao
2022年5月11日16:22:58

**Comment by f8q8** [comment]
> 我也遇到的同样的需求，也是最后一级需要多选操作，需要自己重写级联，确实有点做不来哦
> 
> itchao 2022年5月11日16:22:58

你怎么做的，能不能分享一下demo
