### ISSUE TITLE
NavBar标题栏文字过长会重叠左右按键空间

### ISSUE THREAD

**Issue by pylee** [youzan/vant#865]
效果如图，
![image](https://user-images.githubusercontent.com/965874/38712524-e28abf56-3efe-11e8-8254-70217fe2a0fb.png)
不知道这种效果算不算bug呢？是不是加个van-ellipsis这种样式处理会好一点？
非常感谢团队付出。

**Comment by chenjiahan** [comment]
感谢反馈，下个版本加上最大宽度的限制

**Comment by chenjiahan** [comment]
已在 1.0.5 版本修复
