### ISSUE TITLE
[Bug Report] 日历

### ISSUE THREAD

**Issue by xiao-shuai-01** [youzan/vant#8651]
### 设备 / 浏览器
手机、官网

### Vant 版本
3.0.15

### Vue 版本
3.0.11

### 重现链接
<a href="http://vant-contrib.gitee.io/vant-issue-generater/#/zh-CN" target="_blank">http://vant-contrib.gitee.io/vant-issue-generater/#/zh-CN</a>

### 描述问题
日历选择之后显示都是错误的

**Comment by chenjiahan** [comment]
请提供有效的重现链接

https://codesandbox.io/s/m5v3f
