### ISSUE TITLE
我做一个组件能够动态加载省、市、县地区信息，比较奇怪的是我必须点击父选项两次，子选项才显示。点击一次的话子选项不显示

### ISSUE THREAD

**Issue by starwk** [youzan/vant#8657]
![image](https://user-images.githubusercontent.com/44156971/116870276-d79bd600-ac44-11eb-8d24-c1a39d643404.png)
![image](https://user-images.githubusercontent.com/44156971/116870314-eedac380-ac44-11eb-9fd9-2866ba9bf12e.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by chengyaojun** [comment]
我也遇到同样的问题，异步加载省市区，需要点击两次才能显示子的tab。排查了一下发现是因为：
`
onSelect: function onSelect(option, tabIndex) {
....
 if (option[this.childrenKey]) {
        var nextTab = {
          options: option[this.childrenKey],
          selectedOption: null
        };

        if (this.tabs[tabIndex + 1]) {
          this.$set(this.tabs, tabIndex + 1, nextTab);
        } else {
          this.tabs.push(nextTab);
        }

        this.$nextTick(function () {
          _this3.activeTab++;
        });
      }
....
}
`
中的option[this.childrenKey]判断引起的。因为我的省市区请求过来的对象是没有children字段的，请求之后再发赋值。现在我默认设置应一个children = []。就没有这个问题了

**Comment by starwk** [comment]
> 请按照模板创建 issue，感谢配合
好的

**Comment by starwk** [comment]
> 我也遇到同样的问题，异步加载省市区，需要点击两次才能显示子的tab。排查了一下发现是因为：
> `
> onSelect: function onSelect(option, tabIndex) {
> ....
> if (option[this.childrenKey]) {
> var nextTab = {
> options: option[this.childrenKey],
> selectedOption: null
> };
> 
> ```
>     if (this.tabs[tabIndex + 1]) {
>       this.$set(this.tabs, tabIndex + 1, nextTab);
>     } else {
>       this.tabs.push(nextTab);
>     }
> 
>     this.$nextTick(function () {
>       _this3.activeTab++;
>     });
>   }
> ```
> 
> ....
> }
> `
> 中的option[this.childrenKey]判断引起的。因为我的省市区请求过来的对象是没有children字段的，请求之后再发赋值。现在我默认设置应一个children = []。就没有这个问题了

我也发现了。但是我的实际情况是可能不太一样，我的地址有的是四级，有的只有三级，这个只有请求了接口之后才知道
