### ISSUE TITLE
vant-taro 申请加入 vant 家族

### ISSUE THREAD

**Issue by tgioer** [youzan/vant#8675]
项目地址：https://gitee.com/mallfoundry/taroify 
文档地址：https://taroify.gitee.io/taroify.com/introduce/

一个采用与 vant 相同视觉的 taro 组件库。

**Comment by chenjiahan** [comment]
👏 近期会添加到文档中，期待继续维护和完善喔

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify
我有的时候会同步

**Comment by chenjiahan** [comment]
文档已添加✌️
