### ISSUE TITLE
安装报错  uniapp 创建后添加 vant 报错

### ISSUE THREAD

**Issue by Tonysmark** [youzan/vant#8676]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

问题截图
![image](https://user-images.githubusercontent.com/22767695/117436566-b1867680-af61-11eb-9efc-a6011111857c.png)

复现方式

1. `vue create -p dcloudio/uni-preset-vue vue2-ts`
2. 'yarn add vant'
3. 修改 babel.config.js 
```js
plugins.push([
  "import",
  {
    libraryName: "vant",
    libraryDirectory: "es",
    style: true,
  },
  "vant",
]);
```

4. 引入组件
```vue
<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import { Button  } from "vant";
@Component({
  components: {
    Button ,
  },
})
export default class IndexPage extends Vue {
  title = "aaaa";
  onLoad() {
    console.log("indexPage load");
  }
  mounted() {
    console.log(this);
  }
}
</script>
```
依赖版本
```json
{
    "babel-plugin-import": "^1.13.3",
    "@babel/runtime": "~7.12.0",
    "vant": "^2.12.16",
    "typescript": "^3.0.0",
    "vue": "^2.6.11",
    "vue-template-compiler": "^2.6.11"
    "vue-class-component": "^7.2.6",
    "vue-property-decorator": "^9.1.2",
}
```
Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by Tonysmark** [comment]
![Screenshot_2021-05-07-18-51-56-237_com.tencent.mm.jpg](https://user-images.githubusercontent.com/22767695/117439367-56ef1980-af65-11eb-9774-8d85ddcf336d.jpg)
顺便说一下官方小程序demo这里也有问题

**Comment by chenjiahan** [comment]
vant 没有专门适配 uni-app 喔，建议自行排查。

小程序 demo 的问题后续会修复，感谢反馈
