### ISSUE TITLE
[Bug Report] 在使用Popovertan气泡弹出框组件时，会造成点击失效，要点击两次才行

### ISSUE THREAD

**Issue by y1324** [youzan/vant#8678]
### 设备 / 浏览器
ios端app内嵌h5

### Vant 版本
2.12.10

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-fu7yg?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-fu7yg?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675</a>

### 描述问题
谷歌浏览器打开开发者工具，设置设备仿真，设置成iphonex 刷新一下页面。点击就会复现双击才能实现，安卓和关闭设备仿真不会出现。谷歌查了一个跟hover有关，ios上会把hover当成点击事件，所以就出现了一个问题。我看了一下样式，并没有hover样式。就很头疼。前来请教一下。

项目中没有使用fastclick。

代码在这上面是没有复现。本地

**Comment by y1324** [comment]
已经找到问题所在，因为fastClick.js导致的，所用项目因为是老项目，所以安了一个插件。然后现在问题是，如果处理安装这个插件后，与该组件冲突？领导说这个插件应该没发去，只能自己做兼容。求助看有什么处理办法。

**Comment by y1324** [comment]
找到解决办法了，“请立刻阅读我们的文档”

Ignore certain elements with needsclick
Sometimes you need FastClick to ignore certain elements. You can do this easily by adding the needsclick class.

<a class="needsclick">Ignored by FastClick</a>

**Comment by Anima-No** [comment]
<van-popover
  v-model="showPopover"
  trigger="click"
  :actions="actions"
class="needsclick"
  @select="onSelect"
>
  <template #reference>
    <van-button type="primary">浅色风格</van-button>
  </template>
</van-popover>


加了class="needsclick"  没效果，怎么办
