### ISSUE TITLE
[Feature Request] vant-cli build 没有使用 webpack 吗？

### ISSUE THREAD

**Issue by WenhanDo** [youzan/vant#8681]
### 这个功能解决了什么问题
配了 ts & pug 但是打包一直出问题，最后没办法看了源码发现打包过程似乎是自己写了一个脚本来操作 @vue/component-compiler-utils 直接手动解析编译了 sfc，而并没有使用任何webpack 配置，请问为什么这里没有考虑使用 webpack 来打生产包呢？

### 描述您想要的解决方案
我希望这里至少能支持编译template lang="pug" & script lang="ts"

### 建议的API是什么样的
不需要改动API， compileSfc 通过 descriptor.script.lang & descriptor.template.lang 自动识别编译目标使用的语法
或者支持某种插件模式

**Comment by chenjiahan** [comment]
build 没有使用 webpack 呢，是直接对单个文件进行的编译，目的是为了尽可能精简编译后的文件大小。

如果通过 webpack 编译，会引入很多冗余代码。

**Comment by WenhanDo** [comment]
> build 没有使用 webpack 呢，是直接对单个文件进行的编译，目的是为了尽可能精简编译后的文件大小。
> 
> 如果通过 webpack 编译，会引入很多冗余代码。

或许我可以在使用 vant-cli 打包之前，先手动编译一遍 pug & 通过 tsc/ ts-loader 提取类型定义，然后再把产物送给 vant-cli 的 build.srcDir 这样是不是就可以满足我的需求了？这是一个正确的方式吗？

**Comment by chenjiahan** [comment]
@vue/component-compiler-utils 是可以支持编译不同的 html 模板语言的（vue-loader 底层也是 @vue/component-compiler-utils），欢迎提 PR 来进行支持

**Comment by chenjiahan** [comment]
> 先手动编译一遍 pug & 通过 tsc/ ts-loader 提取类型定义

这个方案不是很可行
