### ISSUE TITLE
[Feature Request] 是否可以考虑升级一下@vant/cli v2版本的依赖

### ISSUE THREAD

**Issue by kekexunxun** [youzan/vant#8698]
### 这个功能解决了什么问题
使用@vant/cli v2时，会发现比较多的依赖出现了滞后

### 描述您想要的解决方案
升级相关依赖

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
具体是哪个依赖呢

**Comment by kekexunxun** [comment]
@chenjiahan 我发现我自己使用时，缺少部分loader，所以我就单独fork下来重新调整和使用了
