### ISSUE TITLE
Calendar日历 day数据结构问题

### ISSUE THREAD

**Issue by HuangWeiBin2** [youzan/vant#8699]
Day 数据结构 不太满足需求、可否考虑将

topInfo | 上方的提示信息 

-- | -- | --
bottomInfo | 下方的提示信息

这两个变成插槽形式、
因为 如果我再bottonmInfo下面需要加几个div [(显示背景颜色。加点显示状态)。就满足不了需求 
![image](https://user-images.githubusercontent.com/57486245/117952375-b2dfe680-b347-11eb-8036-83e41c3cd96d.png)

**Comment by chenjiahan** [comment]
已在 2.12.20 和 3.0.17 版本支持

**Comment by HuangWeiBin2** [comment]
谢谢大佬、烦请同步更新文档。

**Comment by HuangWeiBin2** [comment]
> 已在 2.12.20 和 3.0.17 版本支持
谢谢大佬、烦请同步更新2.12.20以及3.0.17文档。

**Comment by chenjiahan** [comment]
好的

**Comment by HuangWeiBin2** [comment]
只更新了V3版本的。并无更新V2版本代码和文档


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月23日(星期天) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant] Calendar日历 day数据结构问题 (#8699)





 
已在 2.12.20 和 3.0.17 版本支持

**Comment by HuangWeiBin2** [comment]
V3版本更新了。V2版本2.12.20 代码和文档没有更新

**Comment by chenjiahan** [comment]
已在 2.12.22 版本加上
