### ISSUE TITLE
二次封装vant组件时继承原组件所有的属性

### ISSUE THREAD

**Issue by yangss3** [youzan/vant#8701]
### 这个功能解决了什么问题
方便在二次封装vant组件时继承原组件的所有prop，让新组件具有与原组件完全相同的API

### 描述您想要的解决方案
在导出的组件对象上添加包含所有prop定义的Props属性，或者可以单独导出组件的props定义对象

### 建议的API是什么样的
方案一：在导出的组件对象上添加Props属性
```ts
// MyNavBar.ts
import { NavBar } from 'vant'
import { defineComponent } from 'vue'
export default defineComponent({
    props: {
        ...NavBar.Props
    },
   // ...
})
```
方案二： 支持直接导出组件Props定义对象
```ts
// MyNavBar.ts
import { NavBar } from 'vant'
import { Props } from 'vant/lib/nav-bar'
import { defineComponent } from 'vue'
export default defineComponent({
    props: {
       ...Props
    },
   // ...
})
```

**Comment by zhoucan38** [comment]
v-attr不是可以么

**Comment by yangss3** [comment]
> v-attr不是可以么

能给个例子吗，非常感谢

**Comment by zhoucan38** [comment]
https://www.vue3js.cn/docs/zh/guide/component-attrs.html#attribute-%E7%BB%A7%E6%89%BF

 v-bind="$attrs"

**Comment by yangss3** [comment]
> https://www.vue3js.cn/docs/zh/guide/component-attrs.html#attribute-%E7%BB%A7%E6%89%BF
> 
> v-bind="$attrs"

我指的是props，不是attrs，props是组件向外定义的接口，在二次封装vant组件时需要能方便的继承原组件定义的props，这样就能完全兼容原组件接口，而不需要再手动去一个个定义，特别是在搭配TS的场景下，还可以得到原组件props的类型提示

比如我要在`NavBar`的基础上封装自己的`MyNavBar`，实现一些定制化的逻辑，但是需要它接受与`NavBar`完全相同的props，可以这样做：

```ts
import { NavBar } from 'vant'
import { defineComponent, h, PropType } from 'vue'
import { useRouter } from 'vue-router'
export default defineComponent({
  name: 'MyNavBar',
  props: { 
    // 继承NavBar的props
    ...NavBar.props,  
   // 自定义prop
    onClickLeft: {
      type: Function as PropType<() => void>,
    }
  }，
  setup(props, { attrs, slots }) {
    const router = useRouter()
    return ()  => h(
      NavBar,
      {
        ...props,
        ...attrs,
        'onClick-left': props.onClickLeft || () => router.back()
      },
      slots
    )
  }
})
```

**Comment by chenjiahan** [comment]
每个组件本身都是有 props 定义的，只是经过 `defineComponent` 处理后，props 对应的类型定义无法获取到了。

这个应该是 Vue 框架层面解决的问题。

**Comment by zhoucan38** [comment]
> > https://www.vue3js.cn/docs/zh/guide/component-attrs.html#attribute-%E7%BB%A7%E6%89%BF
> > v-bind="$attrs"
> 
> 我指的是props，不是attrs，props是组件向外定义的接口，在二次封装vant组件时需要能方便的继承原组件定义的props，这样就能完全兼容原组件接口，而不需要再手动去一个个定义，特别是在搭配TS的场景下，还可以得到原组件props的类型提示
> 
> 比如我要在`NavBar`的基础上封装自己的`MyNavBar`，实现一些定制化的逻辑，但是需要它接受与`NavBar`完全相同的props，可以这样做：
> 
> ```ts
> import { NavBar } from 'vant'
> import { defineComponent, h, PropType } from 'vue'
> import { useRouter } from 'vue-router'
> export default defineComponent({
>   name: 'MyNavBar',
>   props: { 
>     // 继承NavBar的props
>     ...NavBar.props,  
>    // 自定义prop
>     onClickLeft: {
>       type: Function as PropType<() => void>,
>     }
>   }，
>   setup(props, { attrs, slots }) {
>     const router = useRouter()
>     return ()  => h(
>       NavBar,
>       {
>         ...props,
>         ...attrs,
>         'onClick-left': props.onClickLeft || () => router.back()
>       },
>       slots
>     )
>   }
> })
> ```
> 
> 这样在使用 `MyNavBar` 时，用法能基本和`NavBar`保持一致：
> 
> ```
> <my-nav-bar title="标题" left-arrow right-text="保存" />
> <van-nav-bar title="标题" left-arrow right-text="保存" @click-left="() => router.back()"/>
> ```

你这样不是已近实现了么，原有组件的属性也继承了，难道你仅仅是想要一点点提示？

**Comment by yangss3** [comment]
> > > https://www.vue3js.cn/docs/zh/guide/component-attrs.html#attribute-%E7%BB%A7%E6%89%BF
> > > v-bind="$attrs"
> > 
> > 
> > 我指的是props，不是attrs，props是组件向外定义的接口，在二次封装vant组件时需要能方便的继承原组件定义的props，这样就能完全兼容原组件接口，而不需要再手动去一个个定义，特别是在搭配TS的场景下，还可以得到原组件props的类型提示
> > 比如我要在`NavBar`的基础上封装自己的`MyNavBar`，实现一些定制化的逻辑，但是需要它接受与`NavBar`完全相同的props，可以这样做：
> > ```ts
> > import { NavBar } from 'vant'
> > import { defineComponent, h, PropType } from 'vue'
> > import { useRouter } from 'vue-router'
> > export default defineComponent({
> >   name: 'MyNavBar',
> >   props: { 
> >     // 继承NavBar的props
> >     ...NavBar.props,  
> >    // 自定义prop
> >     onClickLeft: {
> >       type: Function as PropType<() => void>,
> >     }
> >   }，
> >   setup(props, { attrs, slots }) {
> >     const router = useRouter()
> >     return ()  => h(
> >       NavBar,
> >       {
> >         ...props,
> >         ...attrs,
> >         'onClick-left': props.onClickLeft || () => router.back()
> >       },
> >       slots
> >     )
> >   }
> > })
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > 这样在使用 `MyNavBar` 时，用法能基本和`NavBar`保持一致：
> > ```
> > <my-nav-bar title="标题" left-arrow right-text="保存" />
> > <van-nav-bar title="标题" left-arrow right-text="保存" @click-left="() => router.back()"/>
> > ```
> 
> 你这样不是已近实现了么，原有组件的属性也继承了，难道你仅仅是想要一点点提示？

现在通过`NavBar.props` 拿不到 `NavBar` 的 props 定义

**Comment by GapMAX** [comment]
> 每个组件本身都是有 props 定义的，只是经过 `defineComponent` 处理后，props 对应的类型定义无法获取到了。
> 
> 这个应该是 Vue 框架层面解决的问题。

别张嘴就来框架层面的问题，defineComponent本来就只是一个函数，难道你用ts在写函数的时候能从返回值获取到参数类型？简单一句话就是vant自己本身没有把props的类型导出来而已。

**Comment by GapMAX** [comment]
> > > https://www.vue3js.cn/docs/zh/guide/component-attrs.html#attribute-%E7%BB%A7%E6%89%BF
> > > v-bind="$attrs"
> > 
> > 
> > 我指的是props，不是attrs，props是组件向外定义的接口，在二次封装vant组件时需要能方便的继承原组件定义的props，这样就能完全兼容原组件接口，而不需要再手动去一个个定义，特别是在搭配TS的场景下，还可以得到原组件props的类型提示
> > 比如我要在`NavBar`的基础上封装自己的`MyNavBar`，实现一些定制化的逻辑，但是需要它接受与`NavBar`完全相同的props，可以这样做：
> > ```ts
> > import { NavBar } from 'vant'
> > import { defineComponent, h, PropType } from 'vue'
> > import { useRouter } from 'vue-router'
> > export default defineComponent({
> >   name: 'MyNavBar',
> >   props: { 
> >     // 继承NavBar的props
> >     ...NavBar.props,  
> >    // 自定义prop
> >     onClickLeft: {
> >       type: Function as PropType<() => void>,
> >     }
> >   }，
> >   setup(props, { attrs, slots }) {
> >     const router = useRouter()
> >     return ()  => h(
> >       NavBar,
> >       {
> >         ...props,
> >         ...attrs,
> >         'onClick-left': props.onClickLeft || () => router.back()
> >       },
> >       slots
> >     )
> >   }
> > })
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > 这样在使用 `MyNavBar` 时，用法能基本和`NavBar`保持一致：
> > ```
> > <my-nav-bar title="标题" left-arrow right-text="保存" />
> > <van-nav-bar title="标题" left-arrow right-text="保存" @click-left="() => router.back()"/>
> > ```
> 
> 你这样不是已近实现了么，原有组件的属性也继承了，难道你仅仅是想要一点点提示？

那样并不能获取到props，人家只是写个样子，表示想要这样的功能。还有什么叫仅仅为了一点点提示？写ts难道不就是为了检查和提示吗？

**Comment by Zclhlmgqzc** [comment]
改为这样看看能解决问题吗
import NavBar from 'vant/es/nav-bar/NavBar'

**Comment by chenjiahan** [comment]
> 别张嘴就来框架层面的问题，defineComponent本来就只是一个函数，难道你用ts在写函数的时候能从返回值获取到参数类型？简单一句话就是vant自己本身没有把props的类型导出来而已。

`defineComponent` 是一个类型转换的函数，组件本身是一个对象，对象里有 props 这个属性，但经过 `defineComponent` 转换后，组件的类型会变成一个映射后的构造函数，构造函数上不再存在 props 属性。

ps，如果不能友好讨论问题的话，这里不欢迎你。

**Comment by GapMAX** [comment]
> > 别张嘴就来框架层面的问题，defineComponent本来就只是一个函数，难道你用ts在写函数的时候能从返回值获取到参数类型？简单一句话就是vant自己本身没有把props的类型导出来而已。
> 
> `defineComponent` 是一个类型转换的函数，组件本身是一个对象，对象里有 props 这个属性，但经过 `defineComponent` 转换后，组件的类型会变成一个映射后的构造函数，构造函数上不再存在 props 属性。
> 
> ps，如果不能友好讨论问题的话，这里不欢迎你。

咳咳，刚吵完架，语气不太友好不要见怪。正如你说的defineComponent是一个类型转换函数，那我觉得defineComponent并没有义务帮我们保留类型。当然或许之后也会演变成如你想的那样，但现在官方并没有实现，是不是应该把组件Props的类型导出来比较合理？

**Comment by chenjiahan** [comment]
嗯呢，导出 Props 这个改动我们会评估一下，同时也建议到 vue-next 仓库下提一个相关的 issue，看看能否在 defineComponent 时进行处理

**Comment by chenjiahan** [comment]
Vue 仓库已有相关 PR：https://github.com/vuejs/vue-next/pull/3798

组件库就不做调整了，等框架发版吧

**Comment by Cyxwmm** [comment]
请问一下，二次封装的时候 遇到类似CheckboxGroup这种组件，需要ref获取实例方法的情况 怎么处理？

**Comment by TuiMao233** [comment]
我是这样解决了，不知道能不能帮到你。
![image](https://user-images.githubusercontent.com/49724027/123552571-5591de80-d7a9-11eb-8b3e-5311c8f7afa7.png)

**Comment by TuiMao233** [comment]
我是这样解决的，不知道能不能帮到你。
![image](https://user-images.githubusercontent.com/49724027/123552764-3051a000-d7aa-11eb-9111-7cbb9ee72642.png)
![image](https://user-images.githubusercontent.com/49724027/123552773-3ba4cb80-d7aa-11eb-99f5-ea910d4b741c.png)

**Comment by agileago** [comment]
@TuiMao233 强啊，兄弟， 不过用类组件解决HOC的问题轻而易举

**Comment by jawa0919** [comment]
我是这样写的

```ts
import { NavBar, NavBarProps } from "vant";
import { defineComponent, h, ExtractPropTypes } from "vue";

const myNavBarProps = {
  routerMode: Boolean,
};

type MyNavBarProps = ExtractPropTypes<typeof myNavBarProps>;

export default defineComponent<NavBarProps & MyNavBarProps>({
  name: "MyNavBar",
  setup(props, { attrs, slots }) {
    console.log(typeof props.routerMode == "boolean");
    console.log(typeof props.title == "string");
    return () =>
      h(
        NavBar,
        {
          ...props,
          ...attrs,
        },
        slots
      );
  },
});
```

![QQ截图20220326012522](https://user-images.githubusercontent.com/18129670/160171665-cfe28dab-92bb-4d46-aabf-d328a449d67f.png)

**Comment by yhhcg** [comment]
> Vue 仓库已有相关 PR：[vuejs/core#3798](https://github.com/vuejs/core/pull/3798)
> 
> 组件库就不做调整了，等框架发版吧

发版了吗

**Comment by xiangshu233** [comment]
@yangss3 请问该 issues 解决了吗，可以 直接使用 ...NavBar.Props 导出了吗

**Comment by chenjiahan** [comment]
@xiangshu233 Vant 4 导出了所有组件的 props 值
