### ISSUE TITLE
[Feature Request] 希望van-field的文档里能够完善一下[2.x版本]

### ISSUE THREAD

**Issue by toesbieya** [youzan/vant#8702]
### 这个功能解决了什么问题
van-field里用于表单校验的`formValue`会优先使用`input`插槽的`value`值，而文档里并没有提到

个人认为这个会导致在不看源码的前提下很难排查问题

### 描述您想要的解决方案
在van-field文档的“常用问题”里加上这个描述

### 建议的API是什么样的
比如：

#### 校验规则里的validator的第一个参数为什么不是传入的value?

van-field会优先使用input插槽中组件的value，比如当van-field配合van-uploader使用时

**Comment by chenjiahan** [comment]
文档已补充，感谢反馈~

**Comment by supuwoerc** [comment]
请教下作者大佬源码部分的解释：
```
formValue() {
      if (this.children && (this.$scopedSlots.input || this.$slots.input)) {
        return this.children.value;
      }
      return this.value;
    }
```
这里的计算属性获取的formValue在没使用input插槽时是获取field组件的value值，但是在使用了input插槽时我打上断点发现this.children一直为undefined，在源码中也没发现this.children指的是什么.....我自定义了input插槽，但是做完整性验证时一直获取不到value，定位到了这里，希望指教一下。

**Comment by supuwoerc** [comment]
> 这里的 children 是通过 Vant 内部的 mixin 关联上的组件。
> 
> 在 Vant 3 中，可以通过 [useCustomFieldValue](https://youzan.github.io/vant/#/zh-CN/use-custom-field-value) 来自定义表单项，Vant 2 不支持该功能。

感谢回复，我在这条issue中看到了和我遇到的一样的问题：https://github.com/youzan/vant/issues/9417
在这种场景下的表单验证只能手动通过error-message来完成吗？或者更好的方式？=。=

**Comment by supuwoerc** [comment]
> 是的，更好的方式是升级 Vue 3 和 Vant 3

收到~  ヾ(◍°∇°◍)ﾉﾞ
