### ISSUE TITLE
多级选择器动态加载数据需要重复点击

### ISSUE THREAD

**Issue by starwk** [youzan/vant#8706]
设备 / 浏览器
最新谷歌浏览器

Vant 版本
2.12.18

Vue 版本
2.6.1

描述问题
我做一个组件能够动态加载省、市、县地区信息，比较奇怪的是我必须点击父选项两次，而且我的地址有的是四级，有的只有三级，这个只有请求了接口之后才知道
![image](https://user-images.githubusercontent.com/44156971/118346981-3e3cc000-b572-11eb-944e-a4bb6aa16a23.png)
![image](https://user-images.githubusercontent.com/44156971/118346991-5280bd00-b572-11eb-8456-cafd9a3b6ce1.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
