### ISSUE TITLE
tab标签页布局展示问题

### ISSUE THREAD

**Issue by starwk** [youzan/vant#8707]
设备 / 浏览器
最新谷歌浏览器

Vant 版本
2.12.18

Vue 版本
2.6.1

描述问题
我想做一个像下图那样的一个二级分类的功能，当我分类数据少的时候（不够排满一排）时，组件默认是的是均分排列，这样就导致，我只有两个分类或者三个分类的时候，每个分类中间会有空白间隔，展示出来的效果不是很好，所以我想把把中间的间隔去掉，让它全部左对齐，把空白全部留在右侧就行了，不知道这个是否可以实现
![image](https://user-images.githubusercontent.com/44156971/118347073-f8342c00-b572-11eb-889a-897a0a4b975f.png)

**Comment by chenjiahan** [comment]
这个红框区域是什么组件？没看出来，最好给个复现链接

**Comment by starwk** [comment]
> 这个红框区域是什么组件？没看出来，最好给个复现链接

https://mshop291.helixinxuan.com/#/Classify
母婴玩具，一二级都是分别用的两个tab来做的，只是第二个tab加了个图片；我后面自己改了个样式，具体看下图
![Uploading image.png…]()

**Comment by chenjiahan** [comment]
嗯，通过 justify-content 来覆盖样式是可行的喔，组件层面暂时没有计划提供相关的属性
