### ISSUE TITLE
SubmitBar 组件的人民币符号建议可配置 

### ISSUE THREAD

**Issue by yajore** [youzan/vant#871]
**What is the current behavior?**
￥符号被写死了，不利于全球化
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
感谢反馈，后续加个属性定制

**Comment by chenjiahan** [comment]
已在 1.0.7 版本中支持
