### ISSUE TITLE
[Bug Report] Picker 选择器传递的值存在

### ISSUE THREAD

**Issue by Bai-xiaoxiao** [youzan/vant#8711]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.16

### Vue 版本
3.1.0-beta.3

### 重现链接
<a href="http://192.168.1.7:8080/inputGoods" target="_blank">http://192.168.1.7:8080/inputGoods</a>

### 描述问题
picker中的columns存在对象时：
 const columns = [
      { text: '杭州', disabled: true },
      { text: '宁波' },
      { text: '温州' },
    ];
disbaled属性不受proxy控制，响应对象中的disabled修改了，但组件选项任然可点击

**Comment by chenjiahan** [comment]
复现链接无法打开，能否通过 codesandbox 提供一个复现示例

https://codesandbox.io/s/m5v3f
