### ISSUE TITLE
[Feature Request] 希望函数式组件能继承key[2.x]

### ISSUE THREAD

**Issue by toesbieya** [youzan/vant#8717]
### 这个功能解决了什么问题
在 vant 里，所有函数式组件都不会继承`key`属性，导致在循环动态生成这些组件时，会有更新问题

复现：[codepen](https://codepen.io/toesbieya/pen/XWMjzaL)

操作：

- 点击上方用了van-cell-group的增加按钮，增加三行，依次输入`1, 2,  3`，删除第二行，发现显示效果上是第三行被干掉了
- 换到下方使用了继承key的组件，按照上一步的步骤来，发现没有问题

vant 相关源码

https://github.com/youzan/vant/blob/13cdc6e7c9a80b358da8361b34c60c5fd3738d64/src/utils/functional.ts#L8-L18

又或者不继承`key`是有什么考虑吗？

### 描述您想要的解决方案
`inheritKey`里加入`key`

### 建议的API是什么样的
```js
const inheritKey = [
  'ref',
  'key',   // 增加一个key
  'style',
  'class',
  'attrs',
  'refInFor',
  'nativeOn',
  'directives',
  'staticClass',
  'staticStyle',
];
```

**Comment by chenjiahan** [comment]
感谢反馈，后续会默认继承 key

**Comment by chenjiahan** [comment]
已在 2.12.20 版本修复
