### ISSUE TITLE
[tip]Calendar组件无法关闭的问题

### ISSUE THREAD

**Issue by blankzust** [youzan/vant#8719]
出现问题的代码：
`
<cell title="生效日期" :value="form.effectiveDate" @click="showDatePick" is-link>
  <calendar v-model="showEffectiveDate" @confirm="setEffectiveDate"></calendar>
</cell>
`
正确的代码：
`
<cell title="生效日期" :value="form.effectiveDate" @click="showDatePick" is-link>
</cell>
 <calendar v-model="showEffectiveDate" @confirm="setEffectiveDate"></calendar>
`
calendar无法放到cell内部

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
