### ISSUE TITLE
Uploader 小米5S的微信浏览器上传回调不成功

### ISSUE THREAD

**Issue by jkaltopp** [youzan/vant#872]
Uploader 小米5S的微信浏览器上传after-read事件回调没有任何反应

**Comment by terranc** [comment]
同样遇到这个问题

**Comment by jkaltopp** [comment]
@terranc 我的加上这个就好了，你可以试试   accept="image/gif,image/jpg, image/jpeg"

**Comment by jkaltopp** [comment]
我的问题搞定，多加 image/jpg 就可以了

**Comment by terranc** [comment]
我也解决了，我的改成了accept="image/*"
