### ISSUE TITLE
无法导入Badge 组件, 组件不存在

### ISSUE THREAD

**Issue by sixsixsix516** [youzan/vant#8722]
![image](https://user-images.githubusercontent.com/45815935/118780147-55571700-b8be-11eb-99ba-31307d005bc0.png)
![image](https://user-images.githubusercontent.com/45815935/118780173-5c7e2500-b8be-11eb-9dea-391e547bc727.png)

其他组件都可以引用, 这个组件导入不成功

**Comment by chenjiahan** [comment]
Badge 组件是在 Vant 2.11 版本新增的，建议升级版本试一下
