### ISSUE TITLE
[Bug Report] 区域选择区域码超过6位后，选择区域出现错乱

### ISSUE THREAD

**Issue by choutuan** [youzan/vant#8723]
### 设备 / 浏览器
所有平台

### Vant 版本
3.0.1

### Vue 版本
3.0.0

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/area" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/area</a>

### 描述问题
区域选择区域码超过6位后，选择区域时，选择的区并未选中，而是滚动选择了另外的区，出现错乱，比如广东省东莞市下级区域码超过6位

**Comment by chenjiahan** [comment]
Area 组件的区域码必须是 6 位格式，如果需要使用其他格式，建议使用 Picker 或 Cascader 组件自行封装
