### ISSUE TITLE
vant-cli 中 webpack.config.js 和 postcss.config.js 影响范围

### ISSUE THREAD

**Issue by AnyGong** [youzan/vant#8726]
目前使用 `vant-cli `生成了一个组件库，配置`postcss.config.js`时使用到了`vw`的转义插件，但是这也影响到了`docs`文档的页面样式，也是以`vw`为单位显示了。
期望是`postcss.config.js`仅是组件会应用到该配置，是不是合理一些？
`docs`应该仅是作为插件存在，不应该共享`postcss.config.js`配置。

当前的话应该如何修改，可以通过`webpack.config.js` 吗 @chenjiahan ，期盼回复，感谢!

**Comment by chenjiahan** [comment]
可以参考这个文件：https://github.com/youzan/vant/blob/dev/webpack.config.js

加一个 process.env.BUILD_TARGET 的判断

**Comment by AnyGong** [comment]
@chenjiahan 这个只能在`build`的阶段可以使用，如何在`dev`的时候判断

**Comment by AnyGong** [comment]
`webpack.config.js`文件配置了`url-loader`，但是 `vant-cli build`的时候还是报错,`vant-cli dev`时候是可以的
```js
ERROR in ./es/header/src/main.js
Module not found: Error: Can't resolve './assets/images/back-white.png' in '/Users/any/pipiweb/pi-mobile/es/header/src'
 @ ./es/header/src/main.js 4:0-59
 @ ./es/header/index.js
 @ ./es/index.js

 ERROR  Build failed 
```
`webpack.config.js`
```js
const path = require('path');

module.exports = {
  resolve: {
    alias: {
      "@utils": path.resolve(__dirname, "packages/utils"),
      "@": path.resolve(__dirname, "packages/utils"),
    },
  },
  module: {
    rules: [
      {
        test: /\.(png|jpe?g|gif)$/i,
        loader: 'url-loader',
        options: {
          limit: 1,
          name: '[name].[hash:5].[ext]',
        },
      },
    ],
  },
}
```

**Comment by chenjiahan** [comment]
> 这个只能在build的阶段可以使用，如何在dev的时候判断

dev 的时候没法区分喔，毕竟是同一次 webpack 构建

> webpack.config.js文件配置了url-loader，但是 vant-cli build的时候报错

组件 build 时是直接通过 babel 编译的，没走 webpack，建议把组件内部的图片放到 CDN 上

**Comment by AnyGong** [comment]
非常感谢！
