### ISSUE TITLE
[Bug Report] Popover需要点击2次才触发select事件

### ISSUE THREAD

**Issue by skyshirt** [youzan/vant#8727]
### 设备 / 浏览器
ios 14.5.1 Mozilla/5.0 (iPhone; CPU iPhone OS 14_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

### Vant 版本
2.12.19

### Vue 版本
2.6.12

### 重现链接
<a href="http://nolinknow.com" target="_blank">http://nolinknow.com</a>

### 描述问题
ios safari 微信h5点击 popover弹出层，第一次没反应，再次点击才会触发select事件。 暂时先把fastclick关掉，能解决此问题。

**Comment by Anima-No** [comment]
解决了吗

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/8678
