### ISSUE TITLE
[Feature Request] 表单提交与按钮loading加载

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant#8728]
### 这个功能解决了什么问题
form表单的提交事件与提交按钮的加载状态无关，非表单按钮在出于加载状态时点击事件不可用，但在表单中按钮的加载状态为true时依然能触发表单的提交，用户在点击一次提交后按钮处于加载状态但仍然可以快速点击表单提交事件

### 描述您想要的解决方案
表单提交时检测提交按钮的加载状态

### 建议的API是什么样的
表单提交时检测提交按钮的加载状态

**Comment by cangyu1993** [comment]
链接 
`https://codesandbox.io/s/vue-template-forked-h0gmb?file=/src/components/HelloWorld.vue`

**Comment by chenjiahan** [comment]
这个问题在 3.x 版本修复过，回头我在 2.x 也补一个

https://github.com/youzan/vant/pull/8018
