### ISSUE TITLE
tabs 的 click 希望多传回一个 e 对象

### ISSUE THREAD

**Issue by terranc** [youzan/vant#873]
由于 tabs 绝对定位，下方还有其它元素的事件，现在没办法阻止冒泡

**Comment by chenjiahan** [comment]
考虑了一下这个需求比较冷门，就不再新增参数了，可以通过下面的方式解决

```html
<van-tabs @click.native.stop>
```

**Comment by terranc** [comment]
这不能解决吧，你们的 tabs 这个组件是自定义的 click 事件。`.native.stop`这个不会传导到 emit上去吧

https://github.com/youzan/vant/blob/dev/packages/tabs/index.vue

**Comment by chenjiahan** [comment]
@terranc 试了再说。

**Comment by terranc** [comment]
确实可以，刚好我的项目加上也触发了下层的事件，最后发现是sticky相关问题导致的。
