### ISSUE TITLE
vue3 ts toast.clear() 显示异常

### ISSUE THREAD

**Issue by Xukaixin97** [youzan/vant#8730]
<img width="220" alt="Screen Shot 2021-05-20 at 5 48 30 PM" src="https://user-images.githubusercontent.com/44264523/118958068-a6850a80-b993-11eb-9aa3-be529d5c63b6.png">

调用 this.$toast().clear() 出现图片中的效果

**Comment by Xukaixin97** [comment]
使用的是一次性引入全部组件

后来使用如下，未出现问题
import { Toast } from 'vant';
Toast.clear()

**Comment by chenxi5211993** [comment]
兄弟，这是啥原因，我也遇到了。。。。
