### ISSUE TITLE
[Feature Request] Vnat3 能否考虑支持tap事件

### ISSUE THREAD

**Issue by OnlyLady** [youzan/vant#8732]
### 这个功能解决了什么问题
在特定的开发环境中使用到的组件默认只允许tap事件，click事件被禁止。导致使用Vant组件无法触发点击事件。这个问题很头疼。

### 描述您想要的解决方案
增加对tap事件支持

### 建议的API是什么样的
组件默认使用@click 支持指定使用tap或者click

**Comment by chenjiahan** [comment]
暂无计划支持喔，你可以监听组件的 touchstart 和 touchend 事件，或者用其他方式来 trigger click 事件
