### ISSUE TITLE
[Bug Report] van-search使用了show-action，并且自定义了右侧按钮，右侧按钮不显示

### ISSUE THREAD

**Issue by inputherf** [youzan/vant#8733]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.12.19

### Vue 版本
2.5.17

### 重现链接
<a href="https://codepen.io/inputherf/pen/YzZNOOr" target="_blank">https://codepen.io/inputherf/pen/YzZNOOr</a>

### 描述问题
链接没办法打开.我用了show-action之后，也使用了template #action，但是本来应该出现搜索的文字和对应的事件才对。但是这里依然是取消按钮，并且没有事件。只是第一个问题。第二个问题是开了clearable的时候，清楚了值，但是搜索条件还是有值。不知道是不是本身就是这样设计的。

**Comment by chenjiahan** [comment]
codepen 无法运行，麻烦提供有效的复现链接喔

https://codesandbox.io/s/m5v3f
