### ISSUE TITLE
[Bug Report] Calendar 组件month-show事件选择日历第二次滚动到可视区域时无法监听到当前可视区域的日期

### ISSUE THREAD

**Issue by ll-lili** [youzan/vant#8756]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.17

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/ll-lili/pen/dyvWWyN" target="_blank">https://codepen.io/ll-lili/pen/dyvWWyN</a>

### 描述问题
Calendar 组件month-show事件选择日历第二次滚动到可视区域时无法监听到当前可视区域的日期

**Comment by Timecur** [comment]
Calendar 组件中每个月份都对应一个 showed 属性，每当月份滚动到可视区会将 showed 属性设为 true。在滚动可视区时，会根据月份是否在可视区 和 showed 属性值是否为false 来判断是否触发 month-show 方法。

**Comment by Timecur** [comment]
Calendar 组件中每个月份都对应一个 showed 属性，每当月份滚动到可视区会将 showed 属性设为 true。在滚动可视区时，会根据月份是否在可视区 和 showed 属性值是否为false 来判断是否触发 month-show 方法。

**Comment by Timecur** [comment]
Calendar 组件中每个月份都对应一个 showed 属性，每当月份滚动到可视区会将 showed 属性设为 true。在滚动可视区时，会根据月份是否在可视区 和 showed 属性值是否为false 来判断是否触发 month-show 方法。
    但是在处理滚动事件时，没有处理已展示过且不在可视区的月份的 showed 值，导致其一直为 true，再次回到可视区时页不触发 month-show 方法。

**Comment by ll-lili** [comment]
> ```
> Calendar 组件中每个月份都对应一个 showed 属性，每当月份滚动到可视区会将 showed 属性设为 true。在滚动可视区时，会根据月份是否在可视区 和 showed 属性值是否为false 来判断是否触发 month-show 方法。
> 但是在处理滚动事件时，没有处理已展示过且不在可视区的月份的 showed 值，导致其一直为 true，再次回到可视区时页不触发 month-show 方法。
> ```

1.暂时没有办法将showed 值设为false?
2.lazy-render属性 是否只渲染可视区域的内容； 并没有起作用 所有月份全部渲染了

**Comment by chenjiahan** [comment]
1. 每个月份的 month-show 事件只会触发一次喔

2. lazy-render 属性是有效的，如果未生效，可以提供复现链接看下 https://codesandbox.io/s/m5v3f
