### ISSUE TITLE
[Bug Report] CellGroup使用title插槽时会导致更新错误[2.x]

### ISSUE THREAD

**Issue by toesbieya** [youzan/vant#8768]
### 设备 / 浏览器
Chrome 80 

### Vant 版本
2.12.20

### Vue 版本
2.6.12

### 重现链接
<a href="https://codepen.io/toesbieya/pen/XWMjzaL" target="_blank">https://codepen.io/toesbieya/pen/XWMjzaL</a>

###  重现步骤

1. 点上方的增加按钮3次，依次输入1， 2， 3
2. 删除第二个输入框，发现只剩两个输入框，且第二个输入框内容被清空
3. 按照前两步操作下方对照组，发现表现正常

### 描述问题

循环生成CellGroup时，如果使用了title插槽，会导致更新出问题，反之不使用，那就没问题

**Comment by chenjiahan** [comment]
已在 2.12.21 版本修复
