### ISSUE TITLE
uploader拍照上传

### ISSUE THREAD

**Issue by Fxf621621** [youzan/vant#8769]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by Fxf621621** [comment]
uploader拍照上传无法调取后台接口会出错，请尽快排查

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
