### ISSUE TITLE
[Bug Report] Popover引入之后点击报错

### ISSUE THREAD

**Issue by zhu-ml** [youzan/vant#8770]
### 设备 / 浏览器
chorm90.0.4430.212

### Vant 版本
2.12.20

### Vue 版本
2.6.10

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/popover" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/popover</a>

### 描述问题
[Vue warn]: Error in nextTick: "TypeError: map.set is not a function"

found in

---> <VanPopover>

**Comment by chenjiahan** [comment]
请提供有效的复现链接

https://codesandbox.io/s/m5v3f
