### ISSUE TITLE
[Feature Request] 是否会在dialog组件中增加右上角的关闭按钮？

### ISSUE THREAD

**Issue by kekexunxun** [youzan/vant#8772]
### 这个功能解决了什么问题
当dialog中需要关闭，但是按钮为功能按钮，并且不显示取消按钮，就需要额外的关闭按钮

### 描述您想要的解决方案
增加dialog组件右上角按钮

### 建议的API是什么样的
showCornorIcon: false, // 是否开启角落的按钮
cornorIconName: 'close' // 支持vant icon name属性

或者只需要单纯的使用 van-icon name="close"来实现
仅配置是否显示即可

点击即是触发before-close 

![image](https://user-images.githubusercontent.com/44473551/119796469-fa4fa080-bf0b-11eb-81b9-22961f3896b1.png)

**Comment by kekexunxun** [comment]
之前也有一个这样的问题，当时的回复是没有相关视觉规范， #3884

**Comment by kekexunxun** [comment]
请问现在是否有考虑增加？

**Comment by chenjiahan** [comment]
不考虑喔，可以通过 title 插槽实现
