### ISSUE TITLE
[Bug Report] Multi language switching error  Unexpected token 'export' 

### ISSUE THREAD

**Issue by lllomh** [youzan/vant#8774]
### 设备 / 浏览器
Chrome 

### Vant 版本
2.12.20

### Vue 版本
3.1.0-beta.5

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/en-US/locale" target="_blank">https://vant-contrib.gitee.io/vant/#/en-US/locale</a>

### 描述问题
Multi language switching error Unexpected token 'export' 

Switch languages
Vant supports multiple languages with the Locale component, and the Locale.use method allows you to switch to different languages.

import { Locale } from 'vant';
import enUS from 'vant/es/locale/lang/en-US';

Locale.use('en-US', enUS);

**Comment by chenjiahan** [comment]
麻烦提供一下有效的复现链接
