### ISSUE TITLE
[Bug Report] 使用vant-cli开发桌面端组件预览时收到样式污染

### ISSUE THREAD

**Issue by xieyuh** [youzan/vant#8775]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.17

### Vue 版本
3.1.0-beta.5

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/</a>

### 描述问题
在使用 vant-cli 开发桌面端组件并预览时，如果组件中包含有 ul, ol, li 等元素，样式会被 .van-doc-content 这个css 类下的样式污染

**Comment by chenjiahan** [comment]
已在 @vant/cli@3.10.5 版本修复
