### ISSUE TITLE
[Bug Report] NoticeBar 放在 Dialog 中出现显示问题

### ISSUE THREAD

**Issue by limingqian** [youzan/vant#8777]
### 设备 / 浏览器
小米笔记本ubuntu16.04 / 版本 91.0.4472.77（正式版本） （64 位）

### Vant 版本
2.12.19

### Vue 版本
2.6.12

### 重现链接
<a href="https://jsbin.com/hiwacez/edit?html,output" target="_blank">https://jsbin.com/hiwacez/edit?html,output</a>

### 描述问题
NoticeBar 放在 Dialog 中， Dialog 第一次显示滚动正常。Dialog 隐藏后再次显示，NoticeBar显示空白，刷新后正常。尝试用不同key的方法强制刷新组件，虽然文字显示但是滚动失效。

**Comment by chenjiahan** [comment]
已在 2.12.21 版本修复
