### ISSUE TITLE
[Bug Report] van-swipe-item动画卡顿

### ISSUE THREAD

**Issue by Ziluu** [youzan/vant#8778]
### 设备 / 浏览器
安卓、ios

### Vant 版本
2.12.7

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-gr142?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-gr142?file=/src/App.vue</a>

### 描述问题
van-swipe-item中添加src为base64格式的img标签时会造成动画卡顿。具体就是拖拽动画明显反应迟钝，案例里特地丢上去了三张图片做对比，明显感觉到第二张图片的拖拽会有延迟感。pc端没有问题，安卓明显较卡，ios情况有所缓和。经测试后发现图片src长度越长动画越卡。因为没怎么用过sandbox所以就把项目里的依赖都丢上去了（

**Comment by Ziluu** [comment]
顺便借楼问一下为什么自定义indicator样式时，当position设置为absolute时只能停留在van-swipe-item范围中。利用负margin或者bottom,top等属性将indicator移出去的时候会不显示或者是说被盖住（？） 手动增大indicator的z-index或者减小其他元素的z-index也不行。要想实现这个效果只能像案例中那样使用fixed定位。
以及在我个人的项目中进行调试使用浏览器内置的移动端机型时，indicator会变得不那么圆，尝试了几种机型发现有时是第一个indicator有时是第二个indicator会变形成为坨圆或变方。不过案例中的项目没重现，只能在这里空口问一问。

**Comment by chenjiahan** [comment]
1. base64 格式图片卡顿，图片较大时会占用较多浏览器内存，这个和 Swipe 组件没什么关系，建议把图片压缩一下，或者使用 CDN URL
2. 消失是因为 Swipe 声明了 `overflow: hidden;`，如果要实现外部 indicator，建议直接把对应的元素放在 Swipe 组件外部
3. indicator 不圆一般是因为开启了 rem 适配导致的

**Comment by Ziluu** [comment]
但是图片并不大呀，我使用的是一张原图为250KB大小的图片，转换为base64格式后放进src中。之所以这样是因为需求要求合成图片，所以使用了canvas的api合成base64格式的图片。并且动画卡顿现象不仅是第一次渲染出现，图片加载完毕后仍一直存在。

**Comment by Ziluu** [comment]
但是图片并不大呀，我使用的是一张原图为250KB大小的图片，转换为base64格式后放进src中。之所以这样是因为需求要求合成图片，所以使用了canvas的api合成base64格式的图片。并且动画卡顿现象不仅是第一次渲染出现，图片加载完毕后仍一直存在。

> 1. base64 格式图片卡顿，图片较大时会占用较多浏览器内存，这个和 Swipe 组件没什么关系，建议把图片压缩一下，或者使用 CDN URL
> 2. 消失是因为 Swipe 声明了 `overflow: hidden;`，如果要实现外部 indicator，建议直接把对应的元素放在 Swipe 组件外部
> 3. indicator 不圆一般是因为开启了 rem 适配导致的

但是图片并不大呀，我使用的是一张原图为250KB大小的图片，转换为base64格式后放进src中。之所以这样是因为需求要求合成图片，所以使用了canvas的api合成base64格式的图片。并且动画卡顿现象不仅是第一次渲染出现，图片加载完毕后仍一直存在。
