### ISSUE TITLE
van-image报错Invalid handler for event "load"

### ISSUE THREAD

**Issue by CaraChen2690** [youzan/vant#8779]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
版本2.12.20
使用van-image会报错如下图内容
![image](https://user-images.githubusercontent.com/40829070/120061181-95708380-c08e-11eb-9d19-c3bea35883a3.png)

**Comment by chenjiahan** [comment]
请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater
