### ISSUE TITLE
[Bug Report] 编译报错

### ISSUE THREAD

**Issue by ywachao** [youzan/vant#8782]
### 设备 / 浏览器
node v15.9.0

### Vant 版本
3.0.17

### Vue 版本
3.1.0-beta.6

### 重现链接
<a href="https://www.baidu.com" target="_blank">https://www.baidu.com</a>

### 描述问题
This dependency was not found:

* vue in ./node_modules/@vant/use/dist/esm/onMountedOrActivated/index.js, ./node_modules/@vant/use/dist/esm/useClickAway/index.js and 26 others

To install it, you can run: npm install --save vue

我的package.json中的依赖
  "dependencies": {
    "async-validator": "^3.5.2",
    "axios": "^0.21.1",
    "core-js": "^3.6.5",
    "qs": "^6.10.1",
    "vant": "^3.0.17",
    "vue": "^3.0.11",
    "vue-router": "^4.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "^3.3.1",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "babel-plugin-import": "^1.13.3",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0"
  },

**Comment by chenjiahan** [comment]
麻烦提供一下最小复现仓库喔

**Comment by wkstudy** [comment]
> 麻烦提供一下最小复现仓库喔
我也遇到相同情况了
https://github.com/wkstudy/music-demo

**Comment by wkstudy** [comment]
> 麻烦提供一下最小复现仓库喔
![image](https://user-images.githubusercontent.com/37066894/120798904-9dd62c00-c570-11eb-9701-ec39130324b6.png)

我也遇到相同情况了
https://github.com/wkstudy/music-demo

**Comment by wkstudy** [comment]
> > 麻烦提供一下最小复现仓库喔
> > ![image](https://user-images.githubusercontent.com/37066894/120798904-9dd62c00-c570-11eb-9701-ec39130324b6.png)
> 
> 我也遇到相同情况了
> https://github.com/wkstudy/music-demo

解决了，是因为vue.config.js的配置问题
![image](https://user-images.githubusercontent.com/37066894/120879664-9efe6c00-c5f7-11eb-9dd8-0f0a9d69eaea.png)
去掉这个hong kuang红框里的配置就ok了
