### ISSUE TITLE
[Bug Report] Cascader 级联选择问题

### ISSUE THREAD

**Issue by shier-c** [youzan/vant#8785]
### 设备 / 浏览器
小米10 Pro/ 钉钉(6.0.17)内置浏览器

### Vant 版本
3.0.17

### Vue 版本
3.0.11

### 重现链接
<a href="https://codesandbox.io/s/n3psx" target="_blank">https://codesandbox.io/s/n3psx</a>

### 描述问题
![1622452947894722.2021-05-31 17_44_07.gif](https://i.loli.net/2021/05/31/9Oxut1sgDMBjWEf.gif)
数据格式在重现链接里，用CodeSandbox的链接在钉钉内置浏览器里打开不会重现bug，不知道是不是钉钉内置浏览器内核版本低的原因

**Comment by chenjiahan** [comment]
我试了下没问题喔。

CodeSandbox 没能复现的话，说明不是组件的问题，建议在项目中排查找找原因
