### ISSUE TITLE
dialog  use-solt 属性    使用field组件input-align="right"属性时，当弹窗为true的情况下   赋值后会有从左边跳到右边的一个动画效果，这是个Bug，是dialog的某个动画触发了

### ISSUE THREAD

**Issue by gk524-best** [youzan/vant#8796]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
<van-dialog
  use-slot
  show="{{ shareShow }}"
  show-confirm-button="{{false}}"
  bind:close="onClose"
  width="303px"
  theme='round-button'
  custom-style="shareDialog"
  style="height:447rpx"
>

  <view class="imgBox" bindtap="shareClose">
    <image src="/assets/common/close.svg"></image>
  </view>
  <view class="borderBox">
    <van-field 
      bind:input="digitInput" 
      input-class="field-input"
      wx:if="{{type==='share'}}"
      label="分享人奖励" 
      label-class="labelClass" 
      type="digit" 
      data-key="{{shareRewardEdit}}"
      value="{{shareRewardEdit}}"
      data-type="{{type}}" 
      input-align="right" 
      use-button-slot  
      border="{{false}}" 
      placeholder="0.00" 
      bind:change="shareRewardEdit">
      <text slot="button">礼金</text>
    </van-field>
    <van-field 
      wx:if="{{type === 'sign'}}"
      input-class="field-input"
      bind:input="digitInput" 
      label="每次签到得奖励" 
      label-class="labelClass" 
      type="number" 
      data-key="shareRewardEditSign"
      value="{{shareRewardEditSign}}"
      data-type="{{type}}" 
      input-align="right" 
      use-button-slot  
      border="{{false}}" 
      placeholder="0.00" 
      bind:change="shareRewardEdit">
      <text slot="button">礼金</text>
    </van-field>
  </view>
  <view class="borderBox firend" wx:if="{{type==='share'}}">
    <van-field label="好友奖励"  
      bind:input="digitInput" 
      type="digit" 
      data-key="friendRewardEdit" 
      value="{{friendRewardEdit}}" 
      input-align="right" 
      use-button-slot 
      border="{{false}}" 
      placeholder="0.00" 
      bind:change="friendRewardEdit">
      <text slot="button">礼金</text>
    </van-field>
  </view>
  <view class="actions">
    <button bindtap="shareConfirm" class="confirm-btn" type="default" loading="{{shareConfirmLoading}}">确认</button>
  </view>
</van-dialog>

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
