### ISSUE TITLE
同一个vue页面弹出两个Dialog窗口，结果只显示一个。

### ISSUE THREAD

**Issue by zhangliangming** [youzan/vant#8799]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
通过函数来调用弹窗组件时，默认只展示一个喔。

如果需要展示多个 Dialog，建议通过组件调用的方式来使用
