### ISSUE TITLE
PopUp click-overlay 事件无效

### ISSUE THREAD

**Issue by uddsoft** [youzan/vant#880]
PopUp click-overlay 事件无效

**Comment by uddsoft** [comment]
vant版本: 0.11.14
使用方式：
 <van-popup v-model="showInput"  position="bottom" :overlay="true" style="width: 100%;height: 80px;"  @click-overlay=“userClick”>
内容
  </van-popup>

**Comment by chenjiahan** [comment]
请升级到最新版再试

**Comment by wb121017405** [comment]
必须要把 :overlay="true"加上才能使用@click-overlay=“userClick”👏
