### ISSUE TITLE
[Bug Report] 循环collapse设置ref失效

### ISSUE THREAD

**Issue by ycyreddevil** [youzan/vant#8803]
### 设备 / 浏览器
pc/edge

### Vant 版本
2.12.21

### Vue 版本
2.6.13

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/collapse" target="_blank">https://youzan.github.io/vant/#/zh-CN/collapse</a>

### 描述问题
collapse设置为手风琴后，mounted中加载数据，在v-collapse上循环，collapse内部的v-form我加了ref，但是只有展开的一个加上了ref，剩下折叠起来的没有加上ref。

**Comment by chenjiahan** [comment]
麻烦提供有效的 codesandbox 复现链接
