### ISSUE TITLE
[Bug Report] list 底部加载 重置

### ISSUE THREAD

**Issue by AmKang** [youzan/vant#8808]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.0

### Vue 版本
2.6.1

### 重现链接
<a href="http://localhost:8080/#/company?id=123" target="_blank">http://localhost:8080/#/company?id=123</a>

### 描述问题
您好
使用List 底部加载更多，请求数据填充到列表数组dataList[]中，没问题。js清空dataList[]，没有出发onLoad方法，不能重新加载数据。

请问可以主动重新初始化onLoad，或者重新初始化底部加载更多吗？

**Comment by chenjiahan** [comment]
直接手动调用 onLoad 方法即可，或者调用 List 组件的 check 方法
