### ISSUE TITLE
sku组件提供的getSkuData()方法，应该如何使用，希望能在文档上加个例子

### ISSUE THREAD

**Issue by huixu123** [youzan/vant#882]
![1](https://user-images.githubusercontent.com/13418365/38854039-c195f012-4251-11e8-9a71-51add1453b36.png)

**Comment by jerryni** [comment]
直接通过ref来获取sku实例，`this.$refs['sku'].getSkuData()`，不过这里建议你直接用onAddCartClicked返回的参数的skuData，这个后面文档再优化下

```js
onAddCartClicked(skuData) {
 // ..
}
```

[vue ref使用方法](https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements)
