### ISSUE TITLE
[Bug Report]在tsx中使用Picker组件函数报错

### ISSUE THREAD

**Issue by liangliangMirror** [youzan/vant#8830]
使用onConfirm时ts会报错
'{ columns: string[]; onConfirm: (e: string) => void; onCancel: () => any; }' is not assignable to type 'IntrinsicAttributes & Partial<{ loading: boolean; readonly: boolean; allowHtml: boolean; itemHeight: string | number; swipeDuration: string | number; visibleItemCount: string | number; ... 4 more ...; valueKey: string; }> & Pick<...> & { ...; }'.
  Property 'onConfirm' does not exist on type 'IntrinsicAttributes & Partial<{ loading: boolean; readonly: boolean; allowHtml: boolean; itemHeight: string | number; swipeDuration: string | number; visibleItemCount: string | number; ... 4 more ...; valueKey: string; }> & Pick<...> & { ...; }'.
  然后我改成on-confirm不会报错但是会没有作用
  在vue文件中使用是正常的

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/8302

**Comment by liangliangMirror** [comment]
> 参见#8302

谢谢
