### ISSUE TITLE
有赞版本2.12.21未能解决滑动视图的卡顿问题，效果在iPhone12上很明显的卡顿，第一张图划过有空白留底大概三分一，第二张图有三分之二的留白。请联系我，qq：185367688

### ISSUE THREAD

**Issue by jackchan1314** [youzan/vant#8832]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
