### ISSUE TITLE
[Bug Report] van-swipe在多张滚动图上的时候回会有空白显示出来，滑动卡顿

### ISSUE THREAD

**Issue by jackchan1314** [youzan/vant#8833]
### 设备 / 浏览器
iPhone12 iOS14以上版本，公众号

### Vant 版本
2.12.21

### Vue 版本
2.5.20

### 重现链接
<a href="https://mall-test.rlyfl.com/#/" target="_blank">https://mall-test.rlyfl.com/#/</a>

### 描述问题
左滑右滑会有明显卡顿，会有留白的地方，第一张为3分1，第二张是3分2.如果可以我发视频给你看。

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by zhuwei** [comment]
我这边也出现了。左右回滚时，左边会有多个1px，导致有问题

**Comment by zhuwei** [comment]
而且卡顿、空白。这个太容易出现了。

**Comment by Joffey** [comment]
为啥关闭了呢这个问题

**Comment by zhuwei** [comment]
直接换了个控件解决
