### ISSUE TITLE
[Bug Report] tabs change 事件触发两次

### ISSUE THREAD

**Issue by CracKerMe** [youzan/vant#8834]
### 设备 / 浏览器
mac edge

### Vant 版本
3.0.17

### Vue 版本
3.0.5

### 重现链接
<a href="https://codesandbox.io/embed/funny-mountain-4i39g?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/embed/funny-mountain-4i39g?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
查看你们的源代码，发现 change事件本身触发了一次，watch当前index 又触发了一次 请给予答复和解决

**Comment by CracKerMe** [comment]
经本地代码测试，**click** 事件也触发了 **onChange** 的回调事件，导致 **onChange** 的回调**_触发了两次_**，**请尽快修复**

**Comment by chenjiahan** [comment]
v-model 绑错了，正确写法是 `v-model:active`

**Comment by CracKerMe** [comment]
不知道你看了实例没有 即使加了`:active` , onChange 的回调事件依然执行了2次啊

**Comment by lzp0301** [comment]
为什么不写v-model:active也会触发两次？
