### ISSUE TITLE
Toast 使用getcontainer 指定容器后，每次调用都会生成一个新的vant-toast, 请问这是正常的吗？

### ISSUE THREAD

**Issue by kido050313** [youzan/vant#8836]
![image](https://user-images.githubusercontent.com/29145782/121163054-0c70fd80-c881-11eb-990b-db943e28c484.png)
![image](https://user-images.githubusercontent.com/29145782/121163133-1eeb3700-c881-11eb-9cb4-af726e476901.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
