### ISSUE TITLE
[Feature Request] Checkbox's icon slot parameter has no disabled

### ISSUE THREAD

**Issue by mayuxian** [youzan/vant#8838]
### 这个功能解决了什么问题
When customizing an icon, change the style according to the disabled

### 描述您想要的解决方案
Parameter contains the "disabled" value

### 建议的API是什么样的
icon slot parameters:  checked: boolean,disabled:boolean

**Comment by chenjiahan** [comment]
已在 3.1.0-beta.0 版本支持
