### ISSUE TITLE
[Bug Report] Tab 标签页组件 SSR 模式没有正确的渲染 ｜The tabs component is not rendered correctly in ssr mode

### ISSUE THREAD

**Issue by starriv** [youzan/vant#8840]
设备 / 浏览器
任意设备
------------
Device / browser
Any device

Vant 版本
2.12.10
------------
Vant version
2.12.10

Vue 版本
3.0.4
------------
Vue version
3.0.4

重现链接
https://starriv.coding.net/public/playground/nuxt-demo/git/files

- 拉取项目
- 安装依赖
- yarn run
- 浏览器控制检查 html

------------
Demo site
https://starriv.coding.net/public/playground/nuxt-demo/git/files
- pull remo
- install dependencies
- yarn run
- inspect the dom structure in the browser console

描述问题
SSR 模式没有正确的渲染
如下使用 Nuxt 渲染出来的结构
------------
Describe the problem
SSR mode does not render correctly. Structure rendered using Nuxt
input
```js
<template>
  <div>
    <van-tabs v-model="active">
      <van-tab title="标签 1">内容 1</van-tab>
      <van-tab title="标签 2">内容 2</van-tab>
      <van-tab title="标签 3">内容 3</van-tab>
      <van-tab title="标签 4">内容 4</van-tab>
    </van-tabs>
  </div>
</template>
<script>
export default {
  data() {
    return {
      active: 1,
    };
  },
};
</script>
<style>
</style>

```
render
```html
  <div class="van-tabs van-tabs--line">
    <div class="van-tabs__wrap">
      <div role="tablist" class="van-tabs__nav van-tabs__nav--line">
        <div class="van-tabs__line"></div>
      </div>
    </div>
    <div class="van-tabs__content">
      <div role="tabpanel" class="van-tab__pane" style="display:none;">
        <!---->
      </div>
      <div role="tabpanel" class="van-tab__pane" style="display:none;">
        <!---->
      </div>
      <div role="tabpanel" class="van-tab__pane" style="display:none;">
        <!---->
      </div>
      <div role="tabpanel" class="van-tab__pane" style="display:none;">
        <!---->
      </div>
    </div>
  </div>
```
可以看到没有渲染出 tabs (标题栏) 和对应 active 的 content
------------
As shown above, the expected dom structure (complete title bar and activated content) does not appear

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5278
