### ISSUE TITLE
[Feature Request] van-calendar 日期组件default-date确定不更新而是通过事件回传新字段

### ISSUE THREAD

**Issue by zhengbaofeng** [youzan/vant#8841]
**这个功能解决了什么问题**
有些需求会导致van-calendar组件需要和每个表单一一对应，如果有页面有多个日期范围选择就会创建多个van-calendar

**描述您想要的解决方案**
确定事件直接更新 default-date 数据

**Comment by chenjiahan** [comment]
暂无计划调整喔
