### ISSUE TITLE
Collapse组件希望可以添加item头部背景色参数

### ISSUE THREAD

**Issue by ClyingDeng** [youzan/vant#8845]
设备 / 浏览器
安卓手机

Vant 版本
3.0.18

重现链接
https://vant-contrib.gitee.io/vant/v3/#/zh-CN/collapse

描述问题
![image](https://user-images.githubusercontent.com/33626292/121454238-0429d700-c9d5-11eb-8ca7-d809bac7b57f.png)

通过传入不同背景色值，控制面板各个头部背景色

**Comment by chenjiahan** [comment]
暂无计划支持呢，建议自行覆盖组件样式，参见 https://youzan.github.io/vant/v3/#/zh-CN/quickstart#ru-he-zi-ding-yi-vant-zu-jian-de-yang-shi
