### ISSUE TITLE
vue + ts + vant 使用Dialog调用组件时类型错误

### ISSUE THREAD

**Issue by Ashesoft** [youzan/vant#8846]
<van-dialog v-model:show="show" title="标题" show-cancel-button>
 
</van-dialog>
ts会提示类型“{ show: boolean; title: "标题"; showCancelButton: true; 'show-cancel-button': true; }”的参数不能赋给类型“DialogOptions”的参数。
请问这个报错的问题怎么解决

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
