### ISSUE TITLE
[Feature Request] 从版本v3.0.10开始var.less 怎么只有部分了

### ISSUE THREAD

**Issue by jayfongs** [youzan/vant#8850]
### 这个功能解决了什么问题
https://github.com/youzan/vant/blob/v3.0.10/src/style/var.less

从这个版本开始为什么只有部分样式变量了？是故意这样做的还是有bug？
如果是故意这么做的那么其它的组件如何自定义主题？

### 描述您想要的解决方案
--

### 建议的API是什么样的
--

**Comment by chenjiahan** [comment]
组件的样式变量依然存在，只是放到了组件目录下进行管理：

https://github.com/youzan/vant/blob/dev/src/button/var.less
