### ISSUE TITLE
[Bug Report] van-calendar跟本无法使用

### ISSUE THREAD

**Issue by flmbbb** [youzan/vant#8851]
### 设备 / 浏览器
chrom

### Vant 版本
3.0.18

### Vue 版本
3.1.1

### 重现链接
<a href="https://github.com/flmbbb/test.git" target="_blank">https://github.com/flmbbb/test.git</a>

### 描述问题
van-calendar跟本无法使用，就一个控件摆上去，没有多余的东东

**Comment by flmbbb** [comment]
van-calendar搞不懂，就一个基本控件摆上去，没办法使用。。。。。求大大看看，项目已上传

**Comment by sunkint** [comment]
https://github.com/flmbbb/test/blob/c47ddc2068df6451f5ebb572298dc9c4966826f3/src/App.vue#L4

`<van-calendar v-model="show" />` -> `<van-calendar v-model:show="show" />`

**Comment by flmbbb** [comment]
。。。文档变了。我了个去，经测试可以了。。。。。。我就不明白这么多人多没人说过吗。。。。主要我还是不明白 同样的是VUE3+TS+VANT 
v-model="show“是可以的，但有的工程 就是不行。。是不是有什么外在环境影响到。。比如LESS版本。。。sass版本之类的。。。
导至出现偏差。。。如果有，文档上面也要写全啊。。

**Comment by flmbbb** [comment]
> https://github.com/flmbbb/test/blob/c47ddc2068df6451f5ebb572298dc9c4966826f3/src/App.vue#L4
> 
> `<van-calendar v-model="show" />` -> `<van-calendar v-model:show="show" />`
。。。文档变了。我了个去，经测试可以了。。。。。。我就不明白这么多人多没人说过吗。。。。主要我还是不明白 同样的是VUE3+TS+VANT
v-model="show“是可以的，但有的工程 就是不行。。是不是有什么外在环境影响到。。比如LESS版本。。。sass版本之类的。。。
导至出现偏差。。。如果有，文档上面也要写全啊。。

**Comment by sunkint** [comment]
> > https://github.com/flmbbb/test/blob/c47ddc2068df6451f5ebb572298dc9c4966826f3/src/App.vue#L4
> > `<van-calendar v-model="show" />` -> `<van-calendar v-model:show="show" />`
> > 。。。文档变了。我了个去，经测试可以了。。。。。。我就不明白这么多人多没人说过吗。。。。主要我还是不明白 同样的是VUE3+TS+VANT
> > v-model="show“是可以的，但有的工程 就是不行。。是不是有什么外在环境影响到。。比如LESS版本。。。sass版本之类的。。。
> > 导至出现偏差。。。如果有，文档上面也要写全啊。。

https://github.com/youzan/vant/blob/dafea4e1e8f9879c5598abe2a7bf13e17eb2987a/src/calendar/Calendar.tsx#L427

`v-model="show"` 是 Vant2 的写法，Vant3 使用 `v-model:show`

**Comment by chenjiahan** [comment]
注意文档是有多个版本的喔，右上角可以切换版本
