### ISSUE TITLE
Contact 联系人组件是否有考虑增加一个  地址 类型？

### ISSUE THREAD

**Issue by huixu123** [youzan/vant#886]
Contact 联系人组件是否有考虑增加一个  地址类型？
目前只有edit和add两个类型,

![333](https://user-images.githubusercontent.com/13418365/38909115-d0d65234-42f5-11e8-906d-9373279c76dd.png)

**Comment by chenjiahan** [comment]
暂时不考虑喔，地址和联系人是独立的组件

**Comment by rainbowMorelhahahah** [comment]
> Contact 联系人组件是否有考虑增加一个 地址类型？
> 目前只有edit和add两个类型,
> 
> ![333](https://user-images.githubusercontent.com/13418365/38909115-d0d65234-42f5-11e8-906d-9373279c76dd.png)

你的 是自己写还是什么？ 求分享 组件 伸手了
