### ISSUE TITLE
按官网介绍按需引入后，打包体积过大

### ISSUE THREAD

**Issue by xueyanruby** [youzan/vant#8862]
我不引入vant组件，打包后1kb，引入vant的swipe组件，贴官网示例的第一个例子，打包后，79kb。。。

babel.config.js：
module.exports = {
    presets: ['@babel/preset-env'],
    plugins: ['@babel/plugin-transform-runtime', '@babel/plugin-proposal-class-properties', 
    ["@nutui/babel-plugin-separate-import", {
        "style": "scss"
    }],
    ["import", {
        "libraryName": "vant",
        "libraryDirectory": "es",
        "style": true
      },'vant']]
}
（nutui官网给的列子按需引入，引入swiper，打包后只有几kb）

以上都是将vue单独拎出来后的大小。

**Comment by chenjiahan** [comment]
Vant 的 Swipe 组件并没有这么大体积喔，麻烦提供一下复现问题的仓库

**Comment by xueyanruby** [comment]
https://github.com/xueyanruby/vant-test-demo 辛苦查看

**Comment by xueyanruby** [comment]
因为项目需要，所以抽离了vue，在没有抽离vue时，相差十几kb，没啥问题，应该是插件内inport了vue

**Comment by xueyanruby** [comment]
externals: {
        'vue': 'Vue'
    }
问题已经解决，果然是插件中有引入vue，加入这个就可以啦

**Comment by chenjiahan** [comment]
好的
