### ISSUE TITLE
[Bug Report] 表单下的radio组件在v-else不显示

### ISSUE THREAD

**Issue by lalahuang** [youzan/vant#8868]
### 设备 / 浏览器
无

### Vant 版本
2.12.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-trdbh?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-trdbh?file=/src/App.vue</a>

### 描述问题
表单下的radio组件在v-else不显示

**Comment by chenjiahan** [comment]
应该是 Vue diff 算法的问题，建议加一个 `key` 来进行纠正

![image](https://user-images.githubusercontent.com/7237365/122317987-f9c98900-cf50-11eb-963d-a57e5026b12f.png)
