### ISSUE TITLE
Swipe与ImagePreview冲突

### ISSUE THREAD

**Issue by CnSnaker** [youzan/vant#8869]
2.12.21版本，组件引用方式引用Swipe导致ImagePreview无法正常使用，
![image](https://user-images.githubusercontent.com/85993884/122199021-43bc5b80-cecc-11eb-9acc-e0dc8136f63c.png)
在swipe-item的index.js中为空。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
