### ISSUE TITLE
[Bug Report] vant-demo 中用vant-cli例子代码报错

### ISSUE THREAD

**Issue by libbyyounh** [youzan/vant#8870]
### 设备 / 浏览器
pc,chrome

### Vant 版本
3.1.0-beta.0

### Vue 版本
3.1.1

### 重现链接
<a href="https://gitee.com/libbyyounh/demo-ui" target="_blank">https://gitee.com/libbyyounh/demo-ui</a>

### 描述问题
vant-demo 中用vant-cli例子代码报错:
采用了vant-demo中的vant-cli例子，然后在src/my-button/README.md中添加了<demo-code>./demo/MyDemo.vue</demo-code>
然后报错：
 ERROR  Failed to compile with 1 errors                                                                      下午6:04:02

* C:workspaceBNCdemo    est-uisrcmy-buttondemoMyDemo.vue in ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/vue-loader/lib??ref--5-1!./node_modules/@vant/markdown-loader/src!./src/my-button/README.md?vue&type=script&lang=js&

To install it, you can run: npm install --save C:workspaceBNCdemo       est-uisrcmy-buttondemoMyDemo.vue
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

**Comment by chenjiahan** [comment]
@HaoChuan9421 桌面端组件的问题，有空帮看下喔~

**Comment by chenjiahan** [comment]
在这个 issue 中统一跟进：https://github.com/youzan/vant/issues/9043

看起来比较类似
