### ISSUE TITLE
[Bug Report] 上传组件van-uploader在一些安卓手机上选择图片后卡死，并未触发after-read函数

### ISSUE THREAD

**Issue by liukang-1998** [youzan/vant#8873]
### 设备 / 浏览器
honor 8A(安卓9)，oppok3(安卓10)，安卓11

### Vant 版本
2.12.21

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/liukang-1998/pen/MWpLXjJ" target="_blank">https://codepen.io/liukang-1998/pen/MWpLXjJ</a>

### 描述问题
项目是h5和原生混合开发，前端使用vue，在3个安卓机测试上传组件，都能调起选择图片，但是选择完后页面直接卡死，也没有触发:after-read函数，我就写的官网实例最简单的第一个调试都未触发

**Comment by liukang-1998** [comment]
补充一下，有两个安卓机无法触发，有一个安卓机可以，ios的手机没问题

**Comment by chenjiahan** [comment]
从之前的反馈来看，一般都是安卓 WebView 的配置问题。

建议检查下：安卓 App 的 WebView 配置是否正确、图片格式是否合法。

**Comment by 15562401205** [comment]
> 从之前的反馈来看，一般都是安卓WebView的配置问题。
> 
> 建议检查下：安卓 App 的 WebView 配置是否正确、图片格式是否合法。

您好，可以分享下具体是WebView 什么配置不对导致的吗
