### ISSUE TITLE
Vue3 调用子组件方法，IDE爆红，但是可以正常运行

### ISSUE THREAD

**Issue by DanceLynx** [youzan/vant#8874]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---
![微信截图_20210617150020](https://user-images.githubusercontent.com/21261123/122360439-fce06b80-cf88-11eb-96ff-69352b2c7a4b.png)
![微信截图_20210617150053](https://user-images.githubusercontent.com/21261123/122360448-feaa2f00-cf88-11eb-9287-e4279a4f8ad1.png)
![微信截图_20210617150118](https://user-images.githubusercontent.com/21261123/122360456-feaa2f00-cf88-11eb-9c2f-4ac8b58a676d.png)

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
给 ref 加个类型定义就好：

```ts
import { ComponentPublicInstance } from 'vue';

const formRef = ref<ComponentPublicInstance<{}, any>>(null);
```
