### ISSUE TITLE
[Bug Report] PasswordInput密码输入框与NumberKeyboard数字键盘配合使用问题

### ISSUE THREAD

**Issue by lovehebe330** [youzan/vant#8875]
### 设备 / 浏览器
pc端谷歌

### Vant 版本
3.1.0-beta.0

### Vue 版本
3.0.0

### 重现链接
<a href="https://github.com/lovehebe330/lovehebe330" target="_blank">https://github.com/lovehebe330/lovehebe330</a>

### 描述问题
当在数字键盘输入超过密码长度的指定字符时，再点击删除键，最后一个输入框的数字不能马上删除，要连续点击删除键指定次数才能删除输入框数字。 比如 密码文本框有4个，输入4个数字后再点击数字键3次，再点击删除键不能马上删除最后一个文本框的数字，要点击3次删除键后才能删除文本框最后一个数字， 官方文档没问题， 但是代码复制到实际项目中就出了问题

**Comment by chenjiahan** [comment]
设置 `maxlength`  属性为 4 即可。
