### ISSUE TITLE
[Bug Report] van-button SSR下服务器端与客户端渲染不一致。

### ISSUE THREAD

**Issue by HuberTRoy** [youzan/vant#8876]
### 设备 / 浏览器
nuxt

### Vant 版本
2.12.21

### Nuxt 版本
2.15

### 描述问题
随便写一个button即可得到此提示：[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

Ps. http://vant-contrib.gitee.io/vant-issue-generater/#/zh-CN 提Issue链接每次在输入框里打字都会导致CPU100%。

**Comment by chenjiahan** [comment]
未复现该问题，nuxt 版本 2.15.7.

麻烦提供一下复现问题的最小仓库
