### ISSUE TITLE
[Bug Report] @vant/touch-emulator broke my aliyun verification service

### ISSUE THREAD

**Issue by yoyo837** [youzan/vant#8879]
Follow this discussion here https://github.com/youzan/vant/pull/8767#issuecomment-863165323

**Comment by yoyo837** [comment]
> maybe 可以增加一个 className 的白名单，忽略白名单内的 DOM 节点

So, 是否考虑我们先定位一下是不是本身代码的兼容问题呢？但直接支持忽略百名单DOM也许比较节省成本.

**Comment by chenjiahan** [comment]
> 是否考虑我们先定位一下是不是本身代码的兼容问题呢

这个需要有复现问题的代码才能定位喔。

> 直接支持忽略百名单DOM也许比较节省成本.

是的呢，欢迎提 PR 来进行支持。

目前 touch-emulator 是在 import 之后自动执行的，并对所有 DOM 元素生效，把 point 事件转化为 touch 事件。可以从 touch-emulator 中导出一个配置白名单的方法，来进行白名单配置。

**Comment by yoyo837** [comment]
我email给你可以吗？复现包里有我的appKey，不方便公开，阿里云的。

**Comment by yoyo837** [comment]
如果是简单能修复的问题，还是修复为首选，不行或者成本太高我再PR。

**Comment by l-zoy** [comment]
通过设置DOM的attributes 排除怎么样🤔

**Comment by chenjiahan** [comment]
> 我email给你可以吗？复现包里有我的appKey，不方便公开，阿里云的。

算了哈，排查你这边的代码过于繁琐。

> 通过设置DOM的attributes 排除怎么样🤔

是一个不错的思路喔

**Comment by yoyo837** [comment]
> > 我email给你可以吗？复现包里有我的appKey，不方便公开，阿里云的。
> 
> 算了哈，排查你这边的代码过于繁琐。
> 
> > 通过设置DOM的attributes 排除怎么样🤔
> 
> 是一个不错的思路喔

👌，那我就直接PR了。

**Comment by chenjiahan** [comment]
好滴
