### ISSUE TITLE
[Bug Report] 想要实现获取van-field 焦点时弹出键盘 、一些van-tag标签固定在键盘顶部显示

### ISSUE THREAD

**Issue by lovehebe330** [youzan/vant#8881]
### 设备 / 浏览器
pc/谷歌

### Vant 版本
3.1.0-beta.0

### Vue 版本
3.1.1

### 重现链接
<a href="https://github.com/lovehebe330/lovehebe330" target="_blank">https://github.com/lovehebe330/lovehebe330</a>

### 描述问题
实现获取van-field焦点时弹出键盘  一些van-tag标签固定在键盘顶部显示 点击van-tag后内容显示在van-field内， 一些van-tag标签固定在键盘顶部显示要如何做？

**Comment by chenjiahan** [comment]
非 bug/feature 请到讨论区进行讨论：

https://github.com/youzan/vant/discussions
