### ISSUE TITLE
tab组件需求

### ISSUE THREAD

**Issue by acegank** [youzan/vant#8884]
现在tab组件是多个tab在一起，应该有很多业务是不需要这样，大部分可能是顶部tab一排，内容层一个，根据tab触发请求加载到内容层呢

**Comment by chenjiahan** [comment]
这种情况可以不在 Tab 组件中插入内容。

而是在外部单独放一个自定义的 div 元素，并根据 Tab 组件的 v-model 进行动态更新。

**Comment by acegank** [comment]
感谢！
