### ISSUE TITLE
[Bug Report] 适配有点变形

### ISSUE THREAD

**Issue by WaJueZhe** [youzan/vant#8887]
### 设备 / 浏览器
华为 mate 30

### Vant 版本
2.12.21

### Vue 版本
2.6.1

### 重现链接
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### 描述问题
按着文档的说明，做好适配，rootValue：37.5，然后其他手机显示都正常，除了华为mate 30曲面屏看起来回有一点变形，例如NavBar 导航栏，行高会有点不正确，高度会有点缩小，整体都会缩小一点。

**Comment by chenjiahan** [comment]
rem 适配就在不同机型下是有可能出现一些变形的，因为 rem 会渲染成带小数的长度，而 px 会始终保持整数，渲染精度比较高。

建议对于这种个别情况，可以在 rem 适配的白名单中忽略这些元素。
