### ISSUE TITLE
[Bug Report] 按需引入时，Field组件样式出现差异

### ISSUE THREAD

**Issue by jerry4718** [youzan/vant#8888]
### 设备 / 浏览器
所有设备，所有浏览器

### Vant 版本
3.0.18

### Vue 版本
3.1.1

### 描述问题
我是用的是vite构建，配置了按需引入之后build了生产版本，Field的样式中flex:none属性会被Cell样式的flex:1覆盖掉

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/8554
