### ISSUE TITLE
[Bug Report] vant@2.x  Slider 组件绑定的值被格式化了

### ISSUE THREAD

**Issue by rni-l** [youzan/vant#8889]
### 设备 / 浏览器
Chrome

### Vant 版本
2.12.20

### Vue 版本
2.6.13

### 重现链接
<a href="https://codepen.io/rnil_777/project/editor/ZzpWRW?__cf_chl_captcha_tk__=900af2ef9c64e6e986a8d63456ac38e62fe95cb3-1624006671-0-ASc-S7UWYNyxnTiX5LSVBBisQhyE537H6Xcj6KREE9cIZpVp2QB5DRlrnGa4vDEDeiXKQBcnGpzU-791l5aoAWRuYfuVJK3rV8En44-ZhKCHgsxrbGXLCj1TP5Oep_DNKtgGDoDh_BidKGkRZKHlgmkmwCLbBYaZ8K_KjSorJK8yXIBHKQJw-XOlymToh3eGnpq8Kv8TXQfrsbNj2-8lHx-QB_DmpdqVMMRIJWFzf94pIqfSj0ULiKvWWI6KWGak9gzWq845khOxNkqWoWmwsfkq7Im6FJudRzKURaYqF6MUrwbgZCoLZbtB18iV4ZcLs6-7XRk0Vigarw9UUvh254W6SGuKSObVxF8cp7nkphtTG_sKe0IuF2tu_fIJAoF_w0cNXCfV3xdQi3ZoaKWxTtQmIr6sXuUDpG9gVLFLyoTNsPfL5KK75HfBtbZsHGmMGeI2U38ohxS-8FsodNlqYfi2V-hdhwrMMZ6WQtZ-eQs_dj5gygH55mwDoYDnSp2cJ_7-2ozzYGl6JcnsUSdg0jX3jfNZSX-i9qRoV7QbAvWRtybTffLCPIKKUn5-dcl54S4ksywT9ac-HdFapQfrElaOFXCHLZq-XXArulVL5tgMhab0hAPlrB-w0fPn69BGN-LCLZRo7tPbrOPlt3U2_g7ZxlCW6jVD0s-iaW8eehIYePNYylNKym7tX01ka8pkPq5xFVvkgKsC_nQEU4w-jcE" target="_blank">https://codepen.io/rnil_777/project/editor/ZzpWRW?__cf_chl_captcha_tk__=900af2ef9c64e6e986a8d63456ac38e62fe95cb3-1624006671-0-ASc-S7UWYNyxnTiX5LSVBBisQhyE537H6Xcj6KREE9cIZpVp2QB5DRlrnGa4vDEDeiXKQBcnGpzU-791l5aoAWRuYfuVJK3rV8En44-ZhKCHgsxrbGXLCj1TP5Oep_DNKtgGDoDh_BidKGkRZKHlgmkmwCLbBYaZ8K_KjSorJK8yXIBHKQJw-XOlymToh3eGnpq8Kv8TXQfrsbNj2-8lHx-QB_DmpdqVMMRIJWFzf94pIqfSj0ULiKvWWI6KWGak9gzWq845khOxNkqWoWmwsfkq7Im6FJudRzKURaYqF6MUrwbgZCoLZbtB18iV4ZcLs6-7XRk0Vigarw9UUvh254W6SGuKSObVxF8cp7nkphtTG_sKe0IuF2tu_fIJAoF_w0cNXCfV3xdQi3ZoaKWxTtQmIr6sXuUDpG9gVLFLyoTNsPfL5KK75HfBtbZsHGmMGeI2U38ohxS-8FsodNlqYfi2V-hdhwrMMZ6WQtZ-eQs_dj5gygH55mwDoYDnSp2cJ_7-2ozzYGl6JcnsUSdg0jX3jfNZSX-i9qRoV7QbAvWRtybTffLCPIKKUn5-dcl54S4ksywT9ac-HdFapQfrElaOFXCHLZq-XXArulVL5tgMhab0hAPlrB-w0fPn69BGN-LCLZRo7tPbrOPlt3U2_g7ZxlCW6jVD0s-iaW8eehIYePNYylNKym7tX01ka8pkPq5xFVvkgKsC_nQEU4w-jcE</a>

### 描述问题
```
// a: 31
<van-slider :min="29" :max="39" step="2" v-model="a" />
```
组件渲染后， a 的值会变成 32。能否不格式化？

**Comment by chenjiahan** [comment]
已在 2.12.22 版本修复
