### ISSUE TITLE
使用vant-cli搭建组件库，使用ts，.vue 文件会被  buildTypeDeclarations 这个任务处理，tsc 直接编译.vue文件 template中的内容丢失了

### ISSUE THREAD

**Issue by Cyxwmm** [youzan/vant#8890]
## vant-cli 中间执行的task
![image](https://user-images.githubusercontent.com/22393346/122536359-0506dc80-d057-11eb-85b0-e0b5ece6e466.png)
## 这个配置tsconfig配置应该是当时用vant-cli创建项目时生成的
![image](https://user-images.githubusercontent.com/22393346/122536459-210a7e00-d057-11eb-869f-24368bffcada.png)
## 这是编写的测试组件Table.vue
![image](https://user-images.githubusercontent.com/22393346/122536543-37b0d500-d057-11eb-80c6-55d5de56b339.png)
## 这是经过 buildTypeDeclarations 这个任务处理后的Table.js, 模板部分丢失了
![image](https://user-images.githubusercontent.com/22393346/122536784-7d6d9d80-d057-11eb-83d5-e4baf50ab708.png)

**Comment by chenjiahan** [comment]
tsc 和模板编译没有任何关系的，麻烦提供一下复现问题的仓库

**Comment by Cyxwmm** [comment]
> tsc 和模板编译没有任何关系的，麻烦提供一下复现问题的仓库

[复现仓库](https://gitee.com/cyxwmm/vant-cli-test)

**Comment by chenjiahan** [comment]
已在 @vant/cli@3.10.8 版本修复

**Comment by Cyxwmm** [comment]
> 已在 @vant/cli@3.10.8 版本修复

非常感谢！！
