### ISSUE TITLE
使用 定制主题 和axios 封装使用 Dialog等插件 出现的BUG

### ISSUE THREAD

**Issue by LuoKaijin** [youzan/vant#8892]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---当我使用Vant的定制时，我自己封装的axios又使用了 组件Dialog就会直接报错，找不到 自定义的样式文件

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
