### ISSUE TITLE
[Bug Report] van-tabs的change事件未触发

### ISSUE THREAD

**Issue by babalrlr** [youzan/vant#8895]
### 设备 / 浏览器
与设备无关

### Vant 版本
3.1.0-beta.0

### Vue 版本
3.1.1

### 重现链接
<a href="https://codepen.io/LDD-/pen/xxqBNaW" target="_blank">https://codepen.io/LDD-/pen/xxqBNaW</a>

### 描述问题
如题，选择【2】或【3】后，再选择【1】，change事件未触发

**Comment by chenjiahan** [comment]
Tabs 组件需要绑定 `v-model:active` 属性喔

**Comment by lihuangshuaige** [comment]
遇见了  切换到第一个时不触发
