### ISSUE TITLE
vant使用uploader上传视频无法获取视频时长

### ISSUE THREAD

**Issue by lacusrinz** [youzan/vant#8896]
由于需要在上传前判断上传视频的时长是否超过限制，需要用视频的duration来判断，但是uploader的file对象中没有duration属性，这个应该怎么处理

**Comment by chenjiahan** [comment]
File 是浏览器原生对象，如果没有对应属性的话，需要自己进行获取喔。

可以参考 https://zhuanlan.zhihu.com/p/154456790
