### ISSUE TITLE
[Feature Request] 现有阶段下,如何使用 Vant3 的情况下和 Vant2 SKU 组件共存.

### ISSUE THREAD

**Issue by hoythan** [youzan/vant#8899]
### 这个功能解决了什么问题
现在的情况下,短期内可能无法对 Vant3 提供 sku 组件支持

### 描述您想要的解决方案
是否有什么两者兼容的方案,让 vant3 能同时使用 vant2 的 sku 组件

**Comment by chenjiahan** [comment]
没有办法共存喔，两者基于的 Vue 版本是不同的，如果着急的话，可以先自行把 Sku 组件适配到 Vue 3

**Comment by lixiaofa** [comment]
> ### 这个功能解决了什么问题
> 现在的情况下,短期内可能无法对 Vant3 提供 sku 组件支持
> 
> ### 描述您想要的解决方案
> 是否有什么两者兼容的方案,让 vant3 能同时使用 vant2 的 sku 组件
> 
> ### 建议的API是什么样的

我迁移了vant2.x 的sku 
https://www.npmjs.com/package/vant-sku?activeTab=readme
