### ISSUE TITLE
[Bug Report] field的type为textarea的时候，ios输入点击完成文字会消失

### ISSUE THREAD

**Issue by jiaxiaon** [youzan/vant#8902]
### 设备 / 浏览器
设备：iPhone 11  系统：ios14.4.2

### Vant 版本
2.12.21

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/jiaxiaon/test/blob/main/README.md" target="_blank">https://github.com/jiaxiaon/test/blob/main/README.md</a>

### 描述问题
field的type为textarea的时候，ios输入点击完成按钮文字会消失

**Comment by jiaxiaon** [comment]
> ### 设备 / 浏览器
> 设备：iPhone 11 系统：ios14.4.2
> 
> ### Vant 版本
> 2.12.21
> 
> ### Vue 版本
> 2.6.11
> 
> ### 重现链接
> https://github.com/jiaxiaon/test/blob/main/README.md
> 
> ### 描述问题
> field的type为textarea的时候，ios输入点击完成按钮文字会消失

**Comment by santeacher** [comment]
+1
