### ISSUE TITLE
[Bug Report] vant-cli的postcss配置问题

### ISSUE THREAD

**Issue by chenyulun** [youzan/vant#8905]
### 设备 / 浏览器
node

### Vant 版本
3.1.0-beta.0

### Vue 版本
3.1.1

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/packages/vant-cli/src/config/postcss.config.ts" target="_blank">https://github.com/youzan/vant/blob/dev/packages/vant-cli/src/config/postcss.config.ts</a>

### 描述问题
当用户的postcss.config.js为数组的时候,如下
```js
const autoprefixer = require('autoprefixer')
module.exports = {
  plugins: [
autoprefixer({
      flexbox: 'no-2009'
    }),
]
}
```
内部应该判断用户有没有传入自己的autoprefixer配置，从而隐藏脚手架里面的autoprefixer配置
```js
  if (Array.isArray(plugins)) {
// 下面没做判断
    return [require('autoprefixer'), ...plugins];
  }
```
修复方案
```js
 if (Array.isArray(plugins)) {
   // 可能是字符串，可能是对象
    const hasApf = plugins.find(i => i === 'autoprefixer' && i.postcssPlugin === 'autoprefixer');
    return [hasApf && require('autoprefixer'), ...plugins].filter(Boolean);
}

```
具体需求就是我需要自定义autoprefixer里面的配置，
希望同时在2.x和3.x的vant-cli同时修复

**Comment by chenjiahan** [comment]
已发布 2.10.4 和 3.10.7 版本

**Comment by chenyulun** [comment]
效率有点高，谢谢了
