### ISSUE TITLE
[Bug Report] NoticeBar 多页面切换（隐藏显示）文字不见了

### ISSUE THREAD

**Issue by y13818463245** [youzan/vant#8906]
### 设备 / 浏览器
chrome

### Vant 版本
3.1.0-beta.0

### Vue 版本
3.1.1

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/v3/#/zh-CN/notice-bar" target="_blank">https://vant-contrib.gitee.io/vant/v3/#/zh-CN/notice-bar</a>

### 描述问题
给任何一个 NoticeBar 组件 自身或者父级 添加 display:none后再移除(模拟多页面切换) 文字就不见了。

**Comment by chenjiahan** [comment]
由于组件内部无法监听到外部 display 的变化，需要在外部手动调用来触发组件的重新渲染。

可以升级到 3.1.1 版本，然后主动调用 NoticeBar 的 reset 方法，即可避免这个问题。
