### ISSUE TITLE
[Bug Report] datetimePicker的v-model的值和视图显示的值不一样

### ISSUE THREAD

**Issue by 1024-KB** [youzan/vant#8907]
在使用datetimePicker的时候，出现了类似这个链接中的issue的情况，https://github.com/youzan/vant/issues/1550#issue-345462394
我是用的vant的版本是："vant": "^2.12.17",
![屏幕截图 2021-06-22 122334](https://user-images.githubusercontent.com/52350477/122863523-7bf0ed80-d355-11eb-835e-2008295b9199.png)

组件调用：
![pop](https://user-images.githubusercontent.com/52350477/122863555-89a67300-d355-11eb-8402-94ddb0d392b5.png)

绑定数据：
![data](https://user-images.githubusercontent.com/52350477/122863632-b65a8a80-d355-11eb-963d-9a2214cb4083.png)

使用filter过滤分钟:
![minute](https://user-images.githubusercontent.com/52350477/122864145-aabb9380-d356-11eb-8db6-a524393c21b0.png)

日期显示：
![showTime](https://user-images.githubusercontent.com/52350477/122863589-a3e05100-d355-11eb-88f7-3ab9ceb5603b.png)

当我选择的时间比min-date小的时候，就会出现currentDate和视图现实的值不一样：如下图：
![result](https://user-images.githubusercontent.com/52350477/122863787-08031500-d356-11eb-81f5-59e992bd09cf.png)

其他情况正常，不知道为什么？求大神帮忙解决一下

**Comment by chenjiahan** [comment]
麻烦提供一下 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by 1024-KB** [comment]
复现地址：https://github.com/1024-KB/vant-issue-template
目前本人有个发现：就是不加选项过滤器的时候，绑定的值才可以和视图的显示的值保持一致，不知道是不是因为过滤器的问题？

**Comment by 1024-KB** [comment]
@chenjiahan 麻烦您有时间帮我看看，复现地址已经附上了

**Comment by 1024-KB** [comment]
@chenjiahan 请问上面的问题会在哪个版本进行更新？

**Comment by chenjiahan** [comment]
预计下个版本修复，一周左右

**Comment by chenjiahan** [comment]
已在 2.12.24 版本修复
