### ISSUE TITLE
[Feature Request] list后台地址错误的时候一直发送请求

### ISSUE THREAD

**Issue by ZhangXuKai0620** [youzan/vant#8908]
### 这个功能解决了什么问题
list后台地址错误的时候一直发送请求

### 描述您想要的解决方案
如何在后台关闭时，只发送一次请求

### 建议的API是什么样的
如何在后台关闭时，只发送一次请求

**Comment by ZhangXuKai0620** [comment]
![image](https://user-images.githubusercontent.com/69288762/122881276-920aa800-d36d-11eb-84e4-4f0d37e6a375.png)

**Comment by ZhangXuKai0620** [comment]
![image](https://user-images.githubusercontent.com/69288762/122881335-a2228780-d36d-11eb-928d-b67b98a55111.png)

**Comment by chenjiahan** [comment]
把 error 设置成 true
