### ISSUE TITLE
[Feature Request] van-tabs （Tabs Slots）在标题左侧和右侧都有插槽，能不能在标题下面也加个插槽？

### ISSUE THREAD

**Issue by czxiang97** [youzan/vant#8909]
这个功能解决了什么问题
在van-tabs 标题下增加插槽，适应多种场景，便捷开发者开发

描述您想要的解决方案
现在有很多种场景需要在tabs标题和tab页之间有所有tab页通用的内容，跟随tabs标题的sticky，不需要跟随tab页的切换。比如 tabs标题是商品分类，tab页是商品列表。tabs标题和tab页之间可能会有一些筛选条件，这些筛选条件是适用于所有tab页面的，这种场景下，筛选条件和tabs标题一样是固定不动的。希望可以考虑一下，非常感谢！

建议的API是什么样的
暂无api

**Comment by czxiang97** [comment]
非常感谢！

**Comment by chenjiahan** [comment]
已在 3.1.1 版本支持
