### ISSUE TITLE
关于rem布局问题

### ISSUE THREAD

**Issue by sizhuxuan** [youzan/vant#8911]
在van-image组件外包一个div用作定位父元素，在机型为iphone6时，一样大。当切换机型的时候，外边的div会变大，导致定位错乱。无论外边的div不设宽高或者和van-image宽高设一样，div都会变大。我用官方vant-demo中的rem案例也是这样，这是怎么回事?
![image](https://user-images.githubusercontent.com/16433804/123052073-ffcdd700-d434-11eb-99e2-6894afd3694e.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
