### ISSUE TITLE
[Feature Request] 组件radio/ checkbox, disable = true时, 选中项能否保留原激活色(checked-color)

### ISSUE THREAD

**Issue by gita-tt** [youzan/vant#8918]
### 这个功能解决了什么问题
视觉优化: 表单编辑disable = false或查看 disable = true时, radio/checkbox 选中项, 保留原激活色.

### 描述您想要的解决方案
表单组件: radio / checkbox
禁用状态时, 被选中的选项不置灰, 保留原激活色

### 建议的API是什么样的
.van-radio__icon--disabled.van-radio__icon--checked .van-icon {
    color: #c8c9cc;
    background-color: #1989fa;  // 保留红, 不要被覆盖为灰
    border-color: #1989fa; // 保留红, 不要被覆盖为灰
}
.van-radio__icon--disabled .van-icon {
    background-color: #ebedf0; // 灰
    border-color: #c8c9cc; // 灰
}
.van-radio__icon--checked .van-icon {
    background-color: #1989fa; // 红
    border-color: #1989fa; // 红
}

**Comment by chenjiahan** [comment]
这个不计划调整呢，可以自行覆盖组件样式喔

**Comment by gita-tt** [comment]
激活色是通过checked-color这个属性, 动态添加的, 所以无法通过覆盖样式去变更
现在解决方案, 只能在查看时, 用其他元素替代~
