### ISSUE TITLE
希望form里面增加一个select的组件

### ISSUE THREAD

**Issue by syncml** [youzan/vant#892]
移动端UI最终选择了这个，主要是看在更新非常频繁，以后一定能成为一个star多多的通用ui库
所以希望能有一个样子长成 `<van-cell title="单元格" is-link value="内容" />`的select控件。好多移动端的选择都是这种方式，拜托了。

返回顶部的插件也是常见的，也希望能增加.我现在项目中引用的这个：https://github.com/caiofsouza/vue-backtotop

**Comment by chenjiahan** [comment]
1. 移动端推荐使用 Picker 而不是 Select
2. 返回顶部暂无支持计划
