### ISSUE TITLE
[Bug Report]vue3调用dialog

### ISSUE THREAD

**Issue by liangliangMirror** [youzan/vant#8923]
Vant 版本
3.0.0-beta.2

Vue 版本
3.0.0-0

描述问题
我在子组件里面使用dialog组件报错如下
![image](https://user-images.githubusercontent.com/49984570/123198986-a0c59c00-d4e0-11eb-8e72-fde4e7920ed3.png)
![image](https://user-images.githubusercontent.com/49984570/123199006-aa4f0400-d4e0-11eb-9bfe-179d4ec1adf5.png)

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/123266507-ac3fb400-d52e-11eb-9bfd-4fd03f55b8fb.png)
