### ISSUE TITLE
[Bug Report] vue3 van-list 重复触发load事件

### ISSUE THREAD

**Issue by FangzhengZhou0120** [youzan/vant#8927]
### 设备 / 浏览器
chrome

### Vant 版本
3.1.0

### Vue 版本
3.1.2

### 重现链接
<a href="https://codesandbox.io/s/eager-ardinghelli-3kdzj?file=/src/components/OrderList.vue" target="_blank">https://codesandbox.io/s/eager-ardinghelli-3kdzj?file=/src/components/OrderList.vue</a>

### 描述问题
一次下滑多次出发load事件，请求前将loading设置为true依然无法解决
<template>
  <van-list
    v-model="loading"
    :immediate-check="false"
    :finished="finished"
    finished-text="没有更多了"
    offset="50"
    @load="onLoad"
  >
    <van-cell
      style="height: 200px"
      v-for="item in orders"
      :key="item"
      :title="item"
    />
  </van-list>
</template>
<script>
import { defineComponent, ref } from "vue";

export default defineComponent({
  setup() {
    const loading = ref(false);
    const finished = ref(false);
    const orders = ref([1, 2, 3, , 4, 5, 6]);
    const onLoad = () => {
      loading.value = true;
      console.log(loading.value);
      setTimeout(() => {
        for (let i = 0; i < 10; i  ) {
          orders.value.push(orders.value.length   1);
        }
        if (orders.value.length > 50) {
          finished.value = true;
        }
        loading.value = false;
      }, 1000);
    };
    return {
      loading,
      finished,
      orders,
      onLoad,
    };
  },
});
</script>

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/123374358-97f4c900-d5b9-11eb-9e1c-1ee53dc8faa3.png)

List 组件在 Vant 3 里的 v-model 写法有变化
