### ISSUE TITLE
使用@vant/touch-emulator后出现length报错

### ISSUE THREAD

**Issue by Gachel** [youzan/vant#8928]
import '@vant/touch-emulator' 后， 页面的mouse事件可以使用了，但是控制台出现了来自于popmotion.es.js:1443 的报错信息，报错内容如下：
![image](https://user-images.githubusercontent.com/1669788/123364109-6aeaeb00-d5a6-11eb-8fb5-b404c0a2b969.png)

鼠标移动或者点击的时候持续报错'length' of undefined 

来源文件：
![image](https://user-images.githubusercontent.com/1669788/123364363-d59c2680-d5a6-11eb-96e2-32e08a7ed58a.png)

虽然报错，但似乎不太影响使用，

查了网上没有类似错误，请问是哪里使用不对造成的？

**Comment by chenjiahan** [comment]
能提供一个 codesandbox 复现链接或复现仓库吗？

**Comment by Gachel** [comment]
https://gitee.com/gachel/vant-touch-emulator-error.git
复现地址如上

**Comment by Gachel** [comment]
> 能提供一个 codesandbox 复现链接或复现仓库吗？

https://gitee.com/gachel/vant-touch-emulator-error.git
复现地址如上

**Comment by chenjiahan** [comment]
试了下没复现呢

**Comment by Gachel** [comment]
> 试了下没复现呢

抱歉，用其他浏览器测试了一下，确实正常，网上也没有看到大家有反馈类似问题，估计是自己浏览器特地降级存在一些差异。

仓库assets资源附加一段报错录屏（测试环境： chrome  89.0.4389.114（正式版本） （32 位））仅供参考

该错误应该可以忽略了，感谢解答

**Comment by chenjiahan** [comment]
嗯呐，也可能是某些浏览器插件导致的
