### ISSUE TITLE
[Bug Report] vant list 组件传入slot, 会导致蒙层出现问题

### ISSUE THREAD

**Issue by NewWorld2** [youzan/vant#8930]
### 设备 / 浏览器
chrome 91.0.44

### Vant 版本
2.9.2

### Vue 版本
2.6.10

### 重现链接
<a href="https://jsbin.com/miyifigosa/edit?html,js,console,output" target="_blank">https://jsbin.com/miyifigosa/edit?html,js,console,output</a>

### 描述问题
list是我自己使用van-list封装的组件, 传入了slot内容, 会导致蒙层出现问题, 会遮住所有的东西, 设置z-index 无效

**Comment by chenjiahan** [comment]
听起来和 List 组件没什么关系，建议你自行排查下蒙层的样式
