### ISSUE TITLE
[Bug Report] Picker组件数字类型数组会报错

### ISSUE THREAD

**Issue by hxdyj** [youzan/vant#8931]
### 设备 / 浏览器
Chrome

### Vant 版本
3.1.0

### Vue 版本
3.1.2

### 重现链接
[https://codesandbox.io/s/keen-lewin-88icx?file=/index.html](url)

### 描述问题
Picker组件数字类型数组会报错

**Comment by chenjiahan** [comment]
请提供有效的重现链接

https://codesandbox.io/s/m5v3f

**Comment by hxdyj** [comment]
https://codesandbox.io/s/keen-lewin-88icx?file=/index.html

**Comment by chenjiahan** [comment]
目前 columns 的内容必须为 string 类型，后续会评估下是否要支持 number 类型

**Comment by chenjiahan** [comment]
已在 3.1.2 版本支持 number 类型
