### ISSUE TITLE
[Feature Report] stepper在开启async-change希望能让blur后的值也交由开发者控制

### ISSUE THREAD

**Issue by Suzuku** [youzan/vant#8932]
### 设备 / 浏览器
Chrome

### Vant 版本
2.12.18

### Vue 版本
2.5.22

### 重现链接
<a href="https://jsbin.com/sevitic/edit?js,console,output" target="_blank">https://jsbin.com/sevitic/edit?js,console,output</a>

### 描述问题
首先场景是这样的，假定此时max为10，但是由于种种原因，实际上发给后端大于3的值后端就会返回报错，此时我期望

1.用户从输入框输入超过3的值，给后端传值，此时返回一个reject

2.然后stepper的值退回上一个change的值，比如由1改到14，blur的时候 应当退回到1

然而实际上，请具体看链接里的代码：

1.当用户从1开始，输入4-10的值，比如8，值直接到了8，此时组件内部currentValue为8，而传入的值仍为1

2.当用户从1开始，传入大于10的值，比如12，值直接到了10，此时组件内部currentValue为10，而传入的值仍为1，现象就是stepper上显示值是10，无法通过重新赋值传参来更改视图，只能通过赋值内部的currentValue来改变

我想请教下，在开启async-change后，组件的值是否应该全交由开发者控制？组件默认的比如blur事件对于value的处理（比如输入的值超过max，自动置为max），是否应当交给开发者控制

**Comment by chenjiahan** [comment]
开启 async-change 属性时，onBlur 时确实不应该直接修改 currentValue，下个版本会调整下

**Comment by chenjiahan** [comment]
已在 2.12.23 版本修复
