### ISSUE TITLE
ImagePreview 在ios14.6 微信8.0.7无打开，安卓可以打开

### ISSUE THREAD

**Issue by superla** [youzan/vant#8935]
ImagePreview 在ios14.6 微信8.0.7无打开，安卓可以打开
vant版本：2.12.22
vue:2.6.14
代码如下

![1624776527(1)](https://user-images.githubusercontent.com/26450818/123535533-06bb5900-d757-11eb-8ba0-54737d32d034.png)
![1624776565(1)](https://user-images.githubusercontent.com/26450818/123535536-0d49d080-d757-11eb-96da-18fb05d43f35.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
