### ISSUE TITLE
[Feature Request] 什么时候支持暗黑模式？

### ISSUE THREAD

**Issue by cuiliang0302** [youzan/vant#8941]
使用ConfigProvider 全局配置处理暗黑模式需要配置每个组件的样式变量，比较麻烦。期待官方适配组件的暗黑模式，通过引入样式文件变量或者API的方式便于使用。

**Comment by chenjiahan** [comment]
近期没有设计资源来支持暗黑模式喔，预计要在几个月以后咯

**Comment by wltj920** [comment]
期待暗黑模式，或者官方给出ConfigProvider 全局配置的参数

**Comment by chenjiahan** [comment]
4.0 版本会支持，预计下个月发布

**Comment by wltj920** [comment]
> 4.0 版本会支持，预计下个月发布

谢谢，万众期待~
