### ISSUE TITLE
[Feature Request] Cascader 级联选择选项最后一级增加设置disabled属性

### ISSUE THREAD

**Issue by WuYiZhan** [youzan/vant#8943]
### 这个功能解决了什么问题
Cascader 级联选择选项增加设置disabled属性解决禁用项

### 描述您想要的解决方案
 options: [
        {
          text: '浙江省',
          value: '330000',
          disabled: true,
          children: [],
        }
      ]

### 建议的API是什么样的
增加disabled禁用项

**Comment by chenjiahan** [comment]
已在 3.1.2 版本支持
