### ISSUE TITLE
van-uploader 上传图片至服务器后将图片链接存fileList，会显示两张图，

### ISSUE THREAD

**Issue by nongwenze** [youzan/vant#8944]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---fileList中会有两个数组，一个不知道在哪存进去的，另一个是自己存的上传后图片地址

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by LOADINGG** [comment]
同样问题，请问如何解决，afterRead后本地file对象会存进filelist，服务端返回后的图片地址放进数组显示两张图。

**Comment by LxsZxh** [comment]
同样的问题，请问解决了吗
