### ISSUE TITLE
[Bug Report] vue3版本的calendar组件使用min-date和max-date设置区间过大，打卡卡顿，手机滑动超卡

### ISSUE THREAD

**Issue by zengjie911** [youzan/vant#8948]
### 设备 / 浏览器
chrome，Android，ios

### Vant 版本
3.1.1

### Vue 版本
3.1.1

### 重现链接
<a href="https://jsbin.com/juvunikete/edit?html,js,output" target="_blank">https://jsbin.com/juvunikete/edit?html,js,output</a>

### 描述问题
使用vue3版本的calendar组件，使用min-date和max-date设置了可选区间，在chrome上，打开卡顿，滑动没问题，但是在手机上，苹果8和X打开也卡顿，滑动还算正常，在安卓手机上，红米k30s，华为p30，一加6，都是打开卡顿，滑动非常卡顿。如果可选区间较小，就没有任何问题

**Comment by chenjiahan** [comment]
已在 3.1.2 版本做一定程度的优化，不过在超过 20 年的情况下还是会有卡顿现象，并且 Calendar 本身的交互就不适合选择太长的跨度

**Comment by leiyunkang7** [comment]
4.0.11版本设置5年还是很卡, 大佬有考虑基于虚拟滚动实现吗?
