### ISSUE TITLE
[Bug Report] van-field 中的按钮触发表单校验时的错误处理

### ISSUE THREAD

**Issue by rockjaylee** [youzan/vant#8949]
### 设备 / 浏览器
chrome 91.0.4472.114

### Vant 版本
2.12.22

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-from-rowg-kohx5" target="_blank">https://codesandbox.io/s/vant-issue-from-rowg-kohx5</a>

### 描述问题
当van-form中的按钮触发van-field的表单校验时, 若错误的选择了不存在的van-field, try-catch无法捕捉到此错误并给到开发者提示, catch到的error只返回一个undefined.
可以参考重现链接中LoginIndex.vue文件的line82-line96.

**Comment by chenjiahan** [comment]
目前组件内部进行静默处理没有太大问题，而且这个逻辑如果调整的话，会对现有使用者有 breaking 的可能性，因此不计划调整喔。

如果要避免这个问题，还是尽量保证传入正确的 name，或者自行校验 name 的正确性。
