### ISSUE TITLE
sku在部分手机出现了两遍

### ISSUE THREAD

**Issue by Marcoyanghui** [youzan/vant#895]
![image](https://user-images.githubusercontent.com/24379488/38978950-75d7e414-43eb-11e8-92d1-6b4c50f4a063.png)
![image](https://user-images.githubusercontent.com/24379488/38978966-81ba08de-43eb-11e8-98a8-021b1c497947.png)
请教下sku组件出现这种情况的原因

**Comment by jyx12138** [comment]
数据重复了吧
