### ISSUE TITLE
[Bug Report] toast弹出文字显示不全

### ISSUE THREAD

**Issue by czl0325** [youzan/vant#8959]
### 设备 / 浏览器
chrome

### Vant 版本
3.1.1

### Vue 版本
3.1.2

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-726go?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-726go?file=/src/App.vue</a>

### 描述问题
toast弹出文字显示不全

**Comment by chenjiahan** [comment]
已在 3.1.2 版本修复
