### ISSUE TITLE
[Bug Report] Area.js 未能预留#default 接口传入 Picker.js

### ISSUE THREAD

**Issue by NaCoLiu** [youzan/vant#8963]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater
设备 / 浏览器
MacOS / Chrome

Vant 版本
3.1.1

Vue 版本
3.1.2

重现链接
https://codepen.io/nacoliu/pen/zYwGGqp

描述问题
多栏选择器的default 没有传入picker.js 应该留有default 让开发者做选择
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by NaCoLiu** [comment]
Area.js : 277
`return () => {
      var columns = state.columns.slice(0, +props.columnsNum);  
      return _createVNode(Picker, _mergeProps({
        "ref": pickerRef,
        "class": bem(),
        "columns": columns,
        "valueKey": "name",
        "onChange": onChange,
        "onConfirm": onConfirm
      }, pick(props, ['title', 'loading', 'readonly', 'itemHeight', 'swipeDuration', 'visibleItemCount', 'cancelButtonText', 'confirmButtonText'])), pick(slots, ['default','title', 'columns-top', 'columns-bottom']));
    };`

**Comment by chenjiahan** [comment]
下个版本会新增 `toolbar` 插槽，跟 Picker 的 default 插槽效果一致

**Comment by NaCoLiu** [comment]
When will it be released to Releases?

**Comment by chenjiahan** [comment]
一周内。

**Comment by NaCoLiu** [comment]
Thank All.
