### ISSUE TITLE
环形进度条始终填满

### ISSUE THREAD

**Issue by cloud-mouse** [youzan/vant#8970]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

vue3使用vant v3
--- "vant": "^3.0.18",

代码
```
<van-circle
    v-model:current-rate="currentRate"
    :rate="rate"
    :stroke-width="60"
    layer-color="#F7F8FA"
    color="#FF7410"
  >
    <template #default>
      <div class="score-dial-content">
        <span>健康指数</span>
        <p>400</p>
      </div>
    </template>
  </van-circle>
```

currentRate：100
rate：500

![image](https://user-images.githubusercontent.com/37036541/124213947-07236d80-db24-11eb-9254-fdae9d0f2deb.png)

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
