### ISSUE TITLE
[Feature Request] 使用vite创建vue3项目，在script setup中怎么按需引入组件

### ISSUE THREAD

**Issue by yyj961010** [youzan/vant#8973]
### 这个功能解决了什么问题
按需引入组件的问题

### 描述您想要的解决方案
求助，暂时不知道咋弄

### 建议的API是什么样的
暂无建议

**Comment by chenjiahan** [comment]
参考：https://github.com/youzan/vant-demo/blob/master/vant/vite/vite.config.js

**Comment by ukhack** [comment]
> 参考：https://github.com/youzan/vant-demo/blob/master/vant/vite/vite.config.js

题主不是这个意思。
`<script setup>`
标签中没有
`
   components:{
     [Button.name]: Button
   }
`
这种写法。我也试过import {default as Button} from 'vant/es/button'; 不能加载进来

**Comment by yyj961010** [comment]
已经解决了
用vite的vite-plugin-components插件可以实现自动导入

`import Vue from '@vitejs/plugin-vue'
import ViteComponents, { VantResolver } from 'vite-plugin-components'
import path from "path"
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [
    Vue(),
    ViteComponents({
      customComponentResolvers: [
        VantResolver()
      ]
    })
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src")
    }
  }
})
`

**Comment by ukhack** [comment]
赞！你的方案是对的
