### ISSUE TITLE
[Bug Report] tabs在html引入方式设置active会被重置

### ISSUE THREAD

**Issue by wensc1996** [youzan/vant#8974]
### 设备 / 浏览器
Chrome

### Vant 版本
2.12.22

### Vue 版本
2.6.14

### 重现链接
<a href="https://codesandbox.io/embed/ecstatic-minsky-jxop8?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/embed/ecstatic-minsky-jxop8?fontsize=14&hidenavigation=1&theme=dark</a>

### 描述问题
mounted设置当前激活的标签设置会被重置，但是在Node环境的vant不会出现这个问题

**Comment by chenjiahan** [comment]
参见 https://vant-contrib.gitee.io/vant/#/zh-CN/quickstart#zai-html-zhong-wu-fa-zheng-que-xuan-ran-zu-jian

**Comment by wensc1996** [comment]
看一下这个例子是怎么回事呀，需求是获取url参数之后改变active，实际函数也只执行了一次，赋值成功，但是被重置了
https://codesandbox.io/embed/vigilant-dream-gclbx?fontsize=14&hidenavigation=1&theme=dark

@chenjiahan
