### ISSUE TITLE
[Feature Request] van-slider 自定义两个按钮怎么区分第一个和第二个

### ISSUE THREAD

**Issue by Ninshar** [youzan/vant#8979]
### 这个功能解决了什么问题
自定义单独定义两个滑块的样式

### 描述您想要的解决方案
设置slot button-1/button-2

### 建议的API是什么样的
设置slot button-1/button-2

**Comment by Ninshar** [comment]
@chenjiahan 谢谢大佬

**Comment by chenjiahan** [comment]
已在 3.1.3 版本支持
