### ISSUE TITLE
Uploader 图片上传组件存在BUG，同时使用:before-read，:after-read参数，后者不触发

### ISSUE THREAD

**Issue by ljy-git** [youzan/vant#898]
Uploader 图片上传组件，如下，同时使用  :before-read 与 :after-read参数
<van-uploader    :before-read="beforeUpload" :after-read="afterUpload">
此时，before-read（读取前的回调函数）能够触发，after-read（读取完成后的回调函数） “不能触发”

**Comment by ljy-git** [comment]
已解决，before-read的函数里面，加 return true,就会执行 after-read了

**Comment by cjsky666** [comment]
好大一个坑，感谢@ljy-git
