### ISSUE TITLE
[Bug Report] 修改vant-cli

### ISSUE THREAD

**Issue by woaini22pk** [youzan/vant#8983]
### 设备 / 浏览器
浏览器

### Vant 版本
3.1.2

### Vue 版本
3.0.0

### 重现链接
<a href="https://www.npmjs.com/package/bamboocliaaa" target="_blank">https://www.npmjs.com/package/bamboocliaaa</a>

### 描述问题
修改vant-cli package.json name和版本号后重新引用，发现文档打不开了。
请问是否不能定制化vant-cli这个工程？
报错信息为：
Uncaught TypeError: Cannot read property 'syncPathFromSimulator' of undefined

**Comment by chenjiahan** [comment]
麻烦提供一下复现问题的最小仓库

**Comment by woaini22pk** [comment]
> 麻烦提供一下复现问题
https://gitee.com/lianshangche/testvant 这是我提交的仓库。
我的操作是
1、基于目前最新的源码修改了vant-cli
2、主要是修改了package.json 里面的name然后发布到了npm仓库
3、在vant里面引用我发布的cli工程
4、无法打开文档

**Comment by chenjiahan** [comment]
Fork vant-cli 是没问题的，但是我们不保证 fork 后代码的可用性，请自行保证喔。

发布时，注意要执行 yarn release 命令。

**Comment by woaini22pk** [comment]
> Fork vant-cli 是没问题的，但是我们不保证 fork 后代码的可用性，请自行保证喔。
> 
> 发布时，注意要执行 yarn release 命令。

1、感谢作者回复。执行过yarn release 。
2、修改过babel.config.js  presets 路径，因为这个配置里面写死了@vant/cli 名称。不修改项目无法启动，修改了包名后能启动，但是无法打开文档。
