### ISSUE TITLE
可以在组件中添加个回到顶部的功能吗?

### ISSUE THREAD

**Issue by hixiaodeng** [youzan/vant#8985]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---比如说看一篇文章滑到底部了，想立即回到顶部。在滑到一定距离的时候出现回到顶部的按钮，按回到顶部按钮就立即回到顶部了，这样用户就可以不用手指滑了

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
暂无计划支持喔
