### ISSUE TITLE
[Feature Request] vant-cli开发组件库如何进行国际化？

### ISSUE THREAD

**Issue by MandaJC** [youzan/vant#8988]
### 这个功能解决了什么问题
使用vant-cli build的组件库如何实现国际化切换

### 描述您想要的解决方案
使用vant-cli build的组件库如何在组件库和引用组件的工程中配合实现国际化

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
在 vant.config.js 里配置 locales 字段即可，可以参考 

https://github.com/youzan/vant/blob/dev/vant.config.js
