### ISSUE TITLE
[Bug Report] 关于List与PullRefresh同时使用时的scrollTop

### ISSUE THREAD

**Issue by Ziluu** [youzan/vant#8991]
### 设备 / 浏览器
移动端

### Vant 版本
2.12.23

### Vue 版本
2.6.14

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/mobile.html#/zh-CN/list" target="_blank">https://vant-contrib.gitee.io/vant/mobile.html#/zh-CN/list</a>

### 描述问题
![Snipaste_2021-07-07_16-29-55](https://user-images.githubusercontent.com/68973195/124728625-544b7900-df42-11eb-90b9-42792e0c3ef4.png)

直接引用的官网给的DEMO，如图，无论是van-list还是van-pull-refresh的scrollTop均保持0。这也是我目前遇到的问题。
我的目的是做一个聊天系统，当用户发送消息后页面自动触底。现在由于scrollTop的错误，导致我无法正确设置list或者refresh组件的scrollTop。
别说是获取正确的高度，我甚至无法手动设置高度。尝试直接设置999或者获取低端元素高度再赋值给list或者refresh组件均不行。
请问这个是特性还是谷歌浏览器的BUG还是说其它原因引起的。如果是特性的话请问如何实现我说的需求呢。
顺带一提翻了翻其它issue，body和html我没有设置overflow属性，项目里只设置了Height和Width100%。

**Comment by chenjiahan** [comment]
给个复现链接？

https://codesandbox.io/s/m5v3f

**Comment by Ziluu** [comment]
> 给个复现链接？
> 
> https://codesandbox.io/s/m5v3f

https://codesandbox.io/s/vant-issue-moban-forked-r21qt?file=/src/App.vue
...就是官方的demo，把代码丢进去打印了一下对应元素的scrollTop。
本来想用ref获取元素，结果获取后发现没有scrollTop属性，迷惑。

**Comment by chenjiahan** [comment]
PullRefresh 的触发条件是「父级滚动元素的滚动条在顶部位置」。

- 如果最近一个可滚动的父级元素是 `window`，则要求 `window.pageYOffset === 0`。
- 如果最近一个可滚动的父级元素是 `Element`，则要求 `Element.scrollTop === 0`。

**Comment by xhc-code** [comment]
> PullRefresh 的触发条件是「父级滚动元素的滚动条在顶部位置」。
> 
> * 如果最近一个可滚动的父级元素是 `window`，则要求 `window.pageYOffset === 0`。
> * 如果最近一个可滚动的父级元素是 `Element`，则要求 `Element.scrollTop === 0`。

我现在在vant4也遇到了，这个问题就是矛盾，首先想在一个固定高度div盒子里展示列表，给div盒子设置一个100%高度，van-pull-refresh组件也设置100%高度？这时下拉刷新是可以了，但是当元素过多，不会出现滚动条。因为van-pull-refresh 组件是监测父dom的滚动条，而下拉刷新滑动是基于van-pull-refresh的内容元素的高度而定。van-pull-refresh下的列表组件，进行上滑的时候，会导致直接触发下滑刷新，无法进行上滑数据。我也不清楚有没有给描述明白。。。

**Comment by HWT-coder** [comment]
> > PullRefresh 的触发条件是「父级滚动元素的滚动条在顶部位置」。
> > 
> > * 如果最近一个可滚动的父级元素是 `window`，则要求 `window.pageYOffset === 0`。
> > * 如果最近一个可滚动的父级元素是 `Element`，则要求 `Element.scrollTop === 0`。
> 
> 我现在在vant4也遇到了，这个问题就是矛盾，首先想在一个固定高度div盒子里展示列表，给div盒子设置一个100%高度，van-pull-refresh组件也设置100%高度？这时下拉刷新是可以了，但是当元素过多，不会出现滚动条。因为van-pull-refresh 组件是监测父dom的滚动条，而下拉刷新滑动是基于van-pull-refresh的内容元素的高度而定。van-pull-refresh下的列表组件，进行上滑的时候，会导致直接触发下滑刷新，无法进行上滑数据。我也不清楚有没有给描述明白。。。

van-list里面又包了div导致pullRefresh的判断为真。手势往下想把内容往下滑看到顶部内容时会触发下拉刷新。现在只好通过disabled属性去控制pullrefresh，disabled=!isAtTop || isBottom
