### ISSUE TITLE
使用vant-cli的时候全局引入element-ui报错  Cannot set property 'Popper' of undefined

### ISSUE THREAD

**Issue by jolyPan** [youzan/vant#8996]
设备 / 浏览器
PC端

Vant-cli 版本
2.11.1

element-ui 版本
2.15.3

发现是编译后的popper.js有问题

这是使用vant-cli编译后文件
![image](https://user-images.githubusercontent.com/40552479/124857220-78f52e80-dfde-11eb-9f8c-f92b56d0b3de.png)
这是单独使用webpack编译后文件
![image](https://user-images.githubusercontent.com/40552479/124857316-ae018100-dfde-11eb-91ca-b91c88fa28a4.png)
这是未编译的文件
![image](https://user-images.githubusercontent.com/40552479/124857399-ce314000-dfde-11eb-83b1-bb2d58ea6a3c.png)
运行的时候会导致Uncaught ReferenceError: define is not defined

**Comment by chenjiahan** [comment]
这里 `typeof define` 是 umd 的模块加载器在进行模块类型判断，理论上不影响。

麻烦按照模板创建 issue，提供复现链接或仓库

**Comment by jolyPan** [comment]
复现仓库链接，https://github.com/jolyPan/vant-examples.git

**Comment by jolyPan** [comment]
> 这里`typeof define`是 umd 的模块加载器在进行模块类型判断，不会影响。
> 
> 麻烦按照模型创建问题，提供复现链接或仓库

复现仓库链接https://github.com/jolyPan/vant-examples.git

**Comment by chenjiahan** [comment]
复现仓库链接里只有一个示例 Button 组件，并没有找到你在 issue 里反馈的问题。
