### ISSUE TITLE
[Bug Report] 竖向步骤条小圆点遮盖标签栏

### ISSUE THREAD

**Issue by ushuz** [youzan/vant#8999]
### 设备 / 浏览器
macOS Edge 90.0.818.66

### Vant 版本
2.12.23

### Vue 版本
2.6.11

### 重现链接
<a href="https://output.jsbin.com/yigokogije" target="_blank">https://output.jsbin.com/yigokogije</a>

### 描述问题
竖向步骤条小圆点 `z-index: 2` 大于标签栏 `z-index: 1`，导致重叠时会出现遮盖

<img src=https://user-images.githubusercontent.com/1430856/124876695-26385a00-df7f-11eb-9601-0f98a4f1d526.png width=300>

相关代码：
https://github.com/youzan/vant/blob/e1656e103a48bd0ffc2b3f812f32509a160e814f/src/step/index.less#L120-L128
https://github.com/youzan/vant/blob/e1656e103a48bd0ffc2b3f812f32509a160e814f/src/tabbar/var.less#L4

**Comment by chenjiahan** [comment]
已在 3.1.3 版本修复，2.x 后续也会发个版
