### ISSUE TITLE
radio组件没有挂载

### ISSUE THREAD

**Issue by 13725102796** [youzan/vant#900]
**What is the current behavior?**
<van-radio-group> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
radio组件 按照官网的例子出来后，报这个错，疑似内部没有对它做处理

![2018-04-21_213007](https://user-images.githubusercontent.com/23430123/39084650-7c02ee08-45ab-11e8-8f19-2988a93ed354.jpg)
![2018-04-21_213106](https://user-images.githubusercontent.com/23430123/39084652-8094829c-45ab-11e8-855e-f7758e73b2dc.jpg)

**Comment by jerryni** [comment]
这个最好截图一下吧

**Comment by 13725102796** [comment]
是不是这个组件还要依赖什么
