### ISSUE TITLE
看一下这个例子是怎么回事呀，需求是获取url参数之后改变active，实际函数也只执行了一次，赋值成功，但是被重置了

### ISSUE THREAD

**Issue by wensc1996** [youzan/vant#9002]
看一下这个例子是怎么回事呀，需求是获取url参数之后改变active，实际函数也只执行了一次，赋值成功，但是被重置了
https://codesandbox.io/embed/vigilant-dream-gclbx?fontsize=14&hidenavigation=1&theme=dark

@chenjiahan

_Originally posted by @wensc1996 in https://github.com/youzan/vant/issues/8974#issuecomment-875386009_

**Comment by chenjiahan** [comment]
在不指定 name 的情况下，active 是索引值，需要传入 number 类型

```js
this.current = Number(this.getUrlParameter("current"));
```

**Comment by wensc1996** [comment]
> 在不指定 name 的情况下，active 是索引值，需要传入 number 类型
> 
> ```js
> this.current = Number(this.getUrlParameter("current"));
> ```

强 ，确实没注意到这茬
