### ISSUE TITLE
[Feature Request] van-cascader 可不可以添加一个内容的插槽

### ISSUE THREAD

**Issue by ZonghengKaren** [youzan/vant#9011]
### 这个功能解决了什么问题
这样开发者可以自定义选型内容，现在只是文字展示太单一。例如我们要在每个选项前面加一个图标，或者要区分当前选项是否存在字迹，给有存在子级的选项加一个向右的箭头。  现在要实现以上功能只能自己写一个组件。

### 描述您想要的解决方案
如果Slots能多加一个内容插槽就好了

### 建议的API是什么样的
Slots名字：content； 使用： <template  #content> </template>

**Comment by chenjiahan** [comment]
已在 3.1.4 版本支持
