### ISSUE TITLE
[Bug Report] ios环境出现类名已经去掉了，但是样式还在

### ISSUE THREAD

**Issue by W-ChenAMG** [youzan/vant#9014]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.23

### Vue 版本
2.6.11

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/</a>

### 描述问题
<van-cell
            title="预约时间"
            style="height: 0.88rem"
            :center="true"
            @click="setCommandResnTime()"
            :class="{ grayScaleContent: !resnTimeSwitch }"
          >
</van-cell>
在iOS上，当开关没开的时候，grayScaleContent加一个灰色字体的类名，当开关打开，这个类名消失，显示cell自带的黑色字体，但是实际上使用的时候，当开关打开，灰色的类名已经没了，但是样式还是灰色的，

**Comment by chenjiahan** [comment]
麻烦提供一下复现链接：https://codesandbox.io/s/m5v3f

**Comment by W-ChenAMG** [comment]
<template>
  <div id="app">
    <van-cell-group title="预约洗涤">
      <van-cell title="预约" style="height: 0.88rem" :center="true">
        <template #right-icon>
          <van-switch
            v-model="resnTimeSwitch"
            @input="handleChangeResnTime"
            size="30"
          ></van-switch>
        </template>
      </van-cell>

      <van-cell
        title="预约时间"
        style="height: 0.88rem; color: #c7c7c7; pointer-events: none"
        :center="true"
        v-if="!resnTimeSwitch"
      >
        <template #right-icon>
          <span class="rightValue">
            {{ resnTimeDefaultValue }}
            <van-icon size="22" name="arrow" color="#ccc" />
          </span>
        </template>
      </van-cell>
      <van-cell
        title="预约时间"
        style="height: 0.88rem"
        :center="true"
        @click="setCommandResnTime()"
        v-else
      >
        <template #right-icon>
          <span class="rightValue">
            {{ resnTimeDefaultValue }}1
            <van-icon size="22" name="arrow" color="#ccc" />
          </span>
        </template>
      </van-cell>
    </van-cell-group>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      resnTimeSwitch: false,
      resnTimeDefaultValue: "2h",
    };
  },
};
</script>

**Comment by W-ChenAMG** [comment]
https://codesandbox.io/s/vant-issue-moban-forked-h4bn7?file=/src/App.vue
@chenjiahan 
在ios上颜色不更新，chrome浏览器正常

**Comment by W-ChenAMG** [comment]
pointer-events: none  最终多次调试发现是  pointer-events: none这个属性影响的，没搞懂为啥这个会影响
