### ISSUE TITLE
[Bug Report] Tabs 吸顶 在手机键盘开启时，在tab内容滚动的时候，activetab位置切换不准确

### ISSUE THREAD

**Issue by keaixx365** [youzan/vant#9018]
### 设备 / 浏览器
ios chrome

### Vant 版本
2.12.24

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/elegant-brattain-x5wpn?file=/src/components/HelloWorld.vue" target="_blank">https://codesandbox.io/s/elegant-brattain-x5wpn?file=/src/components/HelloWorld.vue</a>

### 描述问题
Tabs scrollspy sticky模式，在tab内容的input的手机键盘打开的模式下，屏幕上移， 然后scroll的时候 active tab的切换位置不准确

**Comment by keaixx365** [comment]
调用过resize，好像也没有用。只在手机端重现

**Comment by chenjiahan** [comment]
这种属于某些系统下的兼容问题了，暂时没有解决方法喔，组件是根据滚动位置来判断当前 Active Tab 的。
