### ISSUE TITLE
[Bug Report] 【Field 输入框】 文本居右，星号（*）和文本距离太远了

### ISSUE THREAD

**Issue by zhuangxiaohui** [youzan/vant#9020]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.12.24

### Vue 版本
2.6.14

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-fbc23?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-fbc23?file=/src/App.vue</a>

### 描述问题
文本居右，星号（*）和文本距离太远了
![image](https://user-images.githubusercontent.com/5791725/125408289-581d4680-e3ed-11eb-9d26-b5b6df6fe389.png)
希望类型element-ui 这样不用太远
![image](https://user-images.githubusercontent.com/5791725/125408416-77b46f00-e3ed-11eb-9e40-2452d598ce6f.png)

**Comment by chenjiahan** [comment]
已在 3.1.4 版本修复

**Comment by zhuangxiaohui** [comment]
不能在v2版本修复吗？

**Comment by zhuangxiaohui** [comment]
> 已在 3.1.4 版本修复

不能在v2版本修复吗？

**Comment by zhuangxiaohui** [comment]
@chenjiahan 请帮忙在v2版本修复吗？谢谢
