### ISSUE TITLE
NumberKeyboard左下角那个"下拉收起"的按钮是干什么的，又为什么要搞一个 close-button-text="关闭"来当关闭。

### ISSUE THREAD

**Issue by tustzdm** [youzan/vant#9024]
![image](https://user-images.githubusercontent.com/24249412/125490586-636fd12a-2a9c-4865-9c6a-04469da6842d.png)
左下角的按钮触发的是@blur，真尼玛shab，我不想对键盘设置blur事件，左下角那个按键就没有作用了。

**Comment by chenjiahan** [comment]
请文明反馈。
