### ISSUE TITLE
[Bug Report] tabs组件搭配popup弹出层弹出层

### ISSUE THREAD

**Issue by y451687300** [youzan/vant#9025]
### 设备 / 浏览器
Chrome

### Vant 版本
2.12.24

### Vue 版本
2.6.12

### 重现链接
<a href="https://gitee.com/xue-kaiyu/aggregate-takeout" target="_blank">https://gitee.com/xue-kaiyu/aggregate-takeout</a>

### 描述问题
使用tabs组件中的tab组件使用按钮触发popup显示    这里的问题是如果我弹出的popup的tab不是第一个的话  popup会被显示到第一个tab中   请问有什么解决方法

**Comment by y451687300** [comment]
popup在tabs中的显示被穿透了

**Comment by chenjiahan** [comment]
链接无法访问，请提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
