### ISSUE TITLE
Picker Selector Can I add a mouse to scroll selection on the PC? 

### ISSUE THREAD

**Issue by lllomh** [youzan/vant#9026]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---
Picker Selector Can I add a mouse to scroll selection on the PC? 

https://vant-contrib.gitee.io/vant/#/en-US/picker

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
