### ISSUE TITLE
[Bug Report] Picker Selector Can I add a mouse to scroll selection on the PC? 

### ISSUE THREAD

**Issue by lllomh** [youzan/vant#9027]
### Device / Browser
all

### Vant Version
2.12.24

### Vue Version
3.1.4

### Reproduction Link
<a href="https://vant-contrib.gitee.io/vant/#/en-US/picker" target="_blank">https://vant-contrib.gitee.io/vant/#/en-US/picker</a>

### Describe the bug
Picker Selector Can I add a mouse to scroll selection on the PC?

**Comment by chenjiahan** [comment]
在 PC 使用请参考：https://vant-contrib.gitee.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei
