### ISSUE TITLE
picker嵌到popup中，当关闭popup时，picker的change事件还没触发，导致数据没有更新。

### ISSUE THREAD

**Issue by KID-joker** [youzan/vant#9028]
目前有个问题是：picker嵌到popup中，当关闭popup时，picker的change事件还没触发，导致数据没有更新。
请问有什么解决方案吗？

_Originally posted by @KID-joker in https://github.com/youzan/vant/issues/3391#issuecomment-878117238_

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
