### ISSUE TITLE
[Bug Report] [bug] 可以左右移动的情况下,(宽度超出屏幕) 使用van-sticky会出现问题

### ISSUE THREAD

**Issue by NewWorld2** [youzan/vant#9030]
### 设备 / 浏览器
chrome 57

### Vant 版本
2.12.24

### Vue 版本
2.6.13

### 重现链接
<a href="https://jsbin.com/yewiyicixo/edit?html,output" target="_blank">https://jsbin.com/yewiyicixo/edit?html,output</a>

### 描述问题
使用van-sticky会出现问题, 有时候不会悬浮在顶部, 有时候悬浮了不会消失, 左右移动, sticky的title不会跟着移动

**Comment by chenjiahan** [comment]
看了下重新链接，似乎挺正常的，没明白你的问题
