### ISSUE TITLE
[Feature Request]  tabs  click和change事件  只抛出name和title 参数   事件对象$event没抛出

### ISSUE THREAD

**Issue by ZKdwzh** [youzan/vant#9034]
设备 / 浏览器
chrome 57

Vant 版本
2.12.6

Vue 版本
2.6.10

问题图片

<img width="654" alt="a" src="https://user-images.githubusercontent.com/25242060/125720670-c91aabb2-c004-4cf4-a5d4-d4ea1ae98f12.png">

描述问题
vant   tabs  click和change事件  只抛出name和title 参数   事件对象$event没抛出，无法使用$event
麻烦帮忙更新处理下 。抛下事件对象$event。

qq联系人：
1298946488

**Comment by chenjiahan** [comment]
已在 3.1.4 版本支持 click-tab 事件，里面包含了这个参数
