### ISSUE TITLE
[Bug Report] Vant-cli 使用桌面端组件报错 

### ISSUE THREAD

**Issue by guozqgzq** [youzan/vant#9043]
# 设备 / 浏览器
pc,chrome

# Vant-cli 版本
2.0.0

# Vue 版本
2.6.11

# 描述问题
### 使用桌面阅览组件（<demo-code>./demo/myButton.vue</demo-code>），运行 yarn dev 报错：
![image](https://user-images.githubusercontent.com/20923168/125887247-aaf304ae-303c-4656-98ea-1d39df743a5b.png)
### 查看源代码发现在：extract-demo.js 中 使用了绝对路径，在markdown-load/index.js中 import  组件 from  '绝对路径'，如下图所示

markdown-loader/extract-demo.js
![image](https://user-images.githubusercontent.com/20923168/125887507-fad9aa18-36a3-4ad8-9ec9-87511136b953.png)

markdown-loader/index.js
![image](https://user-images.githubusercontent.com/20923168/125888061-595b162d-8358-4897-92bc-3405be504f83.png)

### 想知道是不是我少配置了什么参数？？？

**Comment by guozqgzq** [comment]
![image](https://user-images.githubusercontent.com/20923168/125888917-6998d6f2-8862-41ab-9ca5-c67edc719d93.png)
  
![image](https://user-images.githubusercontent.com/20923168/125889015-185d3158-08dd-4c8f-abae-687adc8aa45f.png)

**Comment by chenjiahan** [comment]
@HaoChuan9421 桌面端组件的问题，有空帮看下喔~

**Comment by HaoChuan9421** [comment]
不好意思晚了点，这是 windows 下引入组件时路径格式的问题，之前用 Mac 开发的，没注意到，已提 MR 了。

**Comment by chenjiahan** [comment]
高效~

**Comment by chenjiahan** [comment]
已修复
