### ISSUE TITLE
下拉刷新组件bug 

### ISSUE THREAD

**Issue by giserman001** [youzan/vant#9044]
给下拉刷新组件添加高度 
![image](https://user-images.githubusercontent.com/24283342/125888771-8b90f02f-8275-41fb-aac7-8a54bec4e634.png)
会出现两个加载中

![image](https://user-images.githubusercontent.com/24283342/125888720-e0e17655-5646-49df-b492-c35a0d7a14bc.png)

**Comment by giserman001** [comment]
![image](https://user-images.githubusercontent.com/24283342/125889157-f555c446-6e20-4773-a6b3-aa8d7354a0af.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
