### ISSUE TITLE
[Bug Report] 移动端上传功能调用不了相册

### ISSUE THREAD

**Issue by cxlogin** [youzan/vant#9048]
### 设备 / 浏览器
华为P40pro

### Vant 版本
2.12.24

### Vue 版本
3.1.4

### 重现链接
<a href="http://118.242.17.126:10001/RyjoinTeam/FansApp.git" target="_blank">http://118.242.17.126:10001/RyjoinTeam/FansApp.git</a>

### 描述问题
移动端在使用uploader上传功能时，点击事件调用不了相册，无反应

**Comment by chenjiahan** [comment]
从之前的反馈来看，一般都是安卓 WebView 的配置问题。

建议检查下安卓 App 的 WebView 配置是否正确。

**Comment by cxlogin** [comment]
> 从之前的反馈来看，一般都是安卓WebView的配置问题。
> 
> 建议检查下安卓 App 的 WebView 配置是否正确。
大部分的都配置好了

**Comment by cxlogin** [comment]
为何vant上传图片的时候没用返回 file文件格式


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant] [Bug Report] 移动端上传功能调用不了相册 (#9048)





 
Closed #9048.
