### ISSUE TITLE
文档中checkbox组件内容错误

### ISSUE THREAD

**Issue by bigdriedfish** [youzan/vant#9054]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

--- 3.1.3的文档当中的Checkbox复选框 全选与反选 以及限制最大可选数 中的  v-model="result" 写错了。按照上面的内容下来应该是 checked

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
感谢反馈，已修正
