### ISSUE TITLE
[Bug Report]  ios环境出现类名已经去掉了，但是样式还在

### ISSUE THREAD

**Issue by W-ChenAMG** [youzan/vant#9057]
### 设备 / 浏览器
浏览器和设备都是

### Vant 版本
2.12.24

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-h4bn7?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-h4bn7?file=/src/App.vue</a>

### 描述问题
在ios设备上，包括mac浏览器，开关打开，但是下面的cell样式不更新，正常情况下，应该是灰色变成黑色。

pointer-events: none 最终多次调试发现是 pointer-events: none这个属性影响的，没搞懂为啥这个会影响

**Comment by chenjiahan** [comment]
pointer-events: none 是你自己设置的属性把？和组件本身没有关系喔，建议自行排查。

或者使用其他方式来实现也可以的，不一样要使用 pointer-events
