### ISSUE TITLE
Toast 引用错误

### ISSUE THREAD

**Issue by yyues** [youzan/vant#9058]
https://vant-contrib.gitee.io/vant/#/zh-CN/toast

问题梗概： 对于Toast 在按需引入下得使用描述不清楚
问题描述：
使用中，由于在单独的js文件下实现vant的按需引入，使用了Vue.use（Toast）,但是在具体的项目method中，没有办法直接使用Toast（‘something’）！！！
 
解决的方法是在按需引入中对toast进行vue全局引用Vue.prototype.$Toast = Toast;，在具体项目中使用的是this.$Toast

关于此次问题注意事项：
1、没有直接测试在单页面下引入Toast
2、没有查看有关Toast在按需引用下的配置

**Comment by chenjiahan** [comment]
注意看文档，可以使用 this.$toast 来使用的。
