### ISSUE TITLE
[Feature Request] 希望可以考虑兼容h5页面横屏之后, van-list等组件的滚动事件的功能

### ISSUE THREAD

**Issue by NewWorld2** [youzan/vant#9060]
### 这个功能解决了什么问题
van-list等组件的滚动事件的功能, 横屏的滚动监听会有问题

### 描述您想要的解决方案
,横屏的滚动监听没问题

### 建议的API是什么样的
自动兼容

**Comment by chenjiahan** [comment]
我在模拟器上试了下没问题，理论上横屏以后也是 scroll 事件，没有差别的
