### ISSUE TITLE
Overlay 遮罩层不能铺满

### ISSUE THREAD

**Issue by 904079904** [youzan/vant#9063]
![image](https://user-images.githubusercontent.com/18653565/126103493-e1ce42e9-3e95-455e-96bb-bdf6bfee31a8.png)
![image](https://user-images.githubusercontent.com/18653565/126103524-f1f9c638-a25b-4e06-af59-a6231c82b8de.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
