### ISSUE TITLE
[Feature Request] 输入框内字体太小

### ISSUE THREAD

**Issue by o-shoushouya** [youzan/vant#9064]
### 这个功能解决了什么问题
输入框输入的字体太小

### 描述您想要的解决方案
请问有什么接口可以修改输入框输入的文字的字体吗

### 建议的API是什么样的
接口

**Comment by chenjiahan** [comment]
参见 https://vant-contrib.gitee.io/vant/v3/#/zh-CN/quickstart#ru-he-zi-ding-yi-vant-zu-jian-de-yang-shi
