### ISSUE TITLE
van-dropdown-menu 在可视窗底部会出现渲染问题

### ISSUE THREAD

**Issue by dengshicheng1996** [youzan/vant#9069]
##版本
"vant": "^2.12.6",
"vue": "^2.6.11",

## 问题组件
van-dropdown-menu

## 描述
1. 在可视窗底部使用该组件时会出现滚动条
2. 通过滚动条或者可视窗判断当前所在的视窗位置动态修改direction：up 或 down 时，第一次渲染会到随机的某个可视窗位置上

## 期望
判断当前item 的占用的大小可自动展示朝上或者朝下，亦或者可以通过滚动条的时候动态修改方向后，可以正常渲染道正常的位置上

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
