### ISSUE TITLE
picker 选择器在IOS设备上选中偏移

### ISSUE THREAD

**Issue by Notdefind** [youzan/vant#907]
iphone 7 iphone 6 设备上有问题
![wechatimg16](https://user-images.githubusercontent.com/17826565/39091498-a0a67bea-4627-11e8-8b73-7f616ac3ae2e.jpeg)

**Comment by chenjiahan** [comment]
是否有其他样式造成了干扰？

**Comment by Notdefind** [comment]
官方示例在IOS设备上也出现了同样的问题
选择器item上有 text-size-adjust: 94%;样式
给body添加 text-size-adjust: 100% !important; 解决了这个问题

**Comment by chenjiahan** [comment]
这应该是 iOS 的字体缩放导致的，我们后续会在 Picker 选项加上 -webkit-text-size-adjust: 100%; 样式
