### ISSUE TITLE
stepper beforechange 旧值 参数

### ISSUE THREAD

**Issue by zezhongmiao** [youzan/vant#9072]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

 current.value
怎么修改源码 ？？
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by zezhongmiao** [comment]
var setValue = value => {
      if (props.beforeChange) {
        callInterceptor({
          args: [value],
          interceptor: props.beforeChange,

          done() {
            current.value = value;
          }

        });
      } else {
        current.value = value;
      }
    };



    var setValue = value => {
      if (props.beforeChange) {
        callInterceptor({
          args: [value，current.value],
          interceptor: props.beforeChange,

          done() {
            current.value = value;
          }

        });
      } else {
        current.value = value;
      }
    };

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
