### ISSUE TITLE
[Bug Report] tabs组件设置了sticky后初始化出现置顶

### ISSUE THREAD

**Issue by harrietjia** [youzan/vant#9073]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.12.22

### Vue 版本
2.5.16

### 重现链接
<a href="https://y.taoyouclub.com/addons/yun_shop/?menu#/newDiy?page_id=219&i=57" target="_blank">https://y.taoyouclub.com/addons/yun_shop/?menu#/newDiy?page_id=219&i=57</a>

### 描述问题
tabs组件设置了sticky后初始化出现直接置顶
![image](https://user-images.githubusercontent.com/30305708/126309518-49b17f54-77a6-4439-8388-56eedd9c855d.png)

**Comment by chenjiahan** [comment]
可能是项目内的某些样式导致的，麻烦提供一下 codesandbox 复现链接：

https://codesandbox.io/s/m5v3f

**Comment by harrietjia** [comment]
> 可能是项目内的某些样式导致的，麻烦提供一下 codesandbox 复现链接：
> 
> https://codesandbox.io/s/m5v3f

![image](https://user-images.githubusercontent.com/30305708/126313714-7bdf7c19-f728-4bfd-a704-95fd83f63138.png)
这边排查看到tabs组件在已进入页面的时候就设置了van-sticky--fixed

**Comment by chenjiahan** [comment]
光给链接，看不到你的代码，没法排查喔，最好提供 codesandbox

**Comment by harrietjia** [comment]
> 光给链接，看不到你的代码，没法排查喔，最好提供 codesandbox

codesandbox复现不出来   想其他办法处理了   谢谢

**Comment by chenjiahan** [comment]
好的
