### ISSUE TITLE
问个vant-grid 的问题

### ISSUE THREAD

**Issue by xingBaGan** [youzan/vant#9078]
![image](https://user-images.githubusercontent.com/53329437/126457468-4aa02a7f-83a6-46ac-9558-5fee97b75cde.png)
我想将 gird-item 的事件委托给 grid 组件，或者说 grid 组件 怎么捕获 gird-item 的组件。
大佬求解决！！

**Comment by xingBaGan** [comment]
我尝试过用@click.capture 但是然并软。有谁用这个组件有这个需求啊

**Comment by toesbieya** [comment]
每个`grid-item`加上`ref`
在`van-grid`上用`@click.native`监听
通过`event.target`拿到触发事件的`dom`
判断`event.target`是否包含`van-grid-item`类名，没有则根据`parentNode`往上找直到找到为止
根据`ref`拿到全体`grid-item`组件实例，找出`$el`与上一步找到的`dom`相等的实例
结果即所求

**Comment by xingBaGan** [comment]
谢谢，使用native 修饰符就能捕获到事件了
