### ISSUE TITLE
[Bug Report] 运行npm run bootstrap 时，出现错误提示

### ISSUE THREAD

**Issue by heroghost** [youzan/vant#9079]
### 设备 / 浏览器
win10

### Vant 版本
3.1.4

### Vue 版本
3.2.0-beta.3

### 重现链接
<a href="https://gitee.com/vant-contrib/vant" target="_blank">https://gitee.com/vant-contrib/vant</a>

### 描述问题
下载vant源码，进行二次开发，根据文档说明运行npm run bootstrap时，出现错误提示：
npm ERR! Missing script: "bootstrap"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:

**Comment by chenjiahan** [comment]
这个命令不需要了，直接 yarn 就好
