### ISSUE TITLE
在Google Chrome 67.0.3396.10版本（32位）下Button按钮没有点击效果

### ISSUE THREAD

**Issue by Jameswain** [youzan/vant#908]
https://www.youzanyun.com/zanui/vant#/zh-CN/button
我在Google Chrome 67.0.3396.10版本下打开以上网址测试Button没有点击效果
但是在Firefox、Edge和Chromium53.0.2785.104下测试Button就有点击效果

**Comment by chenjiahan** [comment]
Chrome 67 是 beta 版本吧？

**Comment by Jameswain** [comment]
是正式版本噢
