### ISSUE TITLE
[Bug Report] 使用ConfigProvider组件无法修改被继承的 CSS 变量

### ISSUE THREAD

**Issue by yyj961010** [youzan/vant#9080]
### 设备 / 浏览器
Chrome  92.0.4515.107

### Vant 版本
3.1.4

### Vue 版本
3.1.5

### 重现链接
<a href="https://codepen.io/YuenChi/pen/bGWrPdV" target="_blank">https://codepen.io/YuenChi/pen/bGWrPdV</a>

### 描述问题
使用ConfigProvider将--van-blue变量值改为red
![image](https://user-images.githubusercontent.com/42398073/126481667-e2b41f0e-0d87-4ec8-b98e-64c53aecee12.png)
开发者工具显示变量已被覆盖，但--van-primary-color变量引用的值还是默认值
![image](https://user-images.githubusercontent.com/42398073/126481861-66d7cdfb-09c5-437c-83e9-7fd151dc5c5a.png)

**Comment by chenjiahan** [comment]
ConfigProvider 的子组件颜色会变化。

你看的是 root 节点，root 是不受影响的。

**Comment by yyj961010** [comment]
你看我写的codepen示例，Button组件是放在ConfigProvider下的
![image](https://user-images.githubusercontent.com/42398073/126581979-7b8500a0-c7ce-4b45-8850-291c54dd5921.png)

**Comment by chenjiahan** [comment]
目前被继承的 CSS 变量确实没法被 ConfigProvider 修改，直接读取到了 root 上的值，后续看下怎么解决

**Comment by yyj961010** [comment]
--van-button-primary-background-color引用--van-primary-color
--van-primary-color引用--van-blue
你的意思是我要改Button组件的background-color只能改--van-button-primary-background-color的值
而不能改--van-primary-color或--van-blue是吗

**Comment by chenjiahan** [comment]
目前是的，或者可以直接这样写:

```css
:root {
  --van-primary-color: red;
}
```

**Comment by yyj961010** [comment]
好的 谢谢

**Comment by chenjiahan** [comment]
文档已更新相关说明
