### ISSUE TITLE
[Bug Report] Tag背景色alpha通道兼容问题

### ISSUE THREAD

**Issue by jackjtr** [youzan/vant#9083]
### 设备 / 浏览器
QQ内置浏览器/部分安卓内置浏览器

### Vant 版本
3.1.1

### Vue 版本
3.1.5

### 重现链接
<a href="https://codesandbox.io/s/tag-bg-alpha-8qn4v?file=/src/App.vue" target="_blank">https://codesandbox.io/s/tag-bg-alpha-8qn4v?file=/src/App.vue</a>

### 描述问题
给Tag设置color属性时如果设置了透明度，在特定浏览器下背景色是黑色

**Comment by chenjiahan** [comment]
这个色值写法本来就是有兼容性问题的，和组件没关系，请使用 rgba 代替。

**Comment by jackjtr** [comment]
> 这个色值写法本来就是有兼容性问题的，和组件没关系，请使用 rgba 代替。

十六进制格式兼容性问题第一次遇到，本来是考虑定义text-color后拼接一个`1a`传递给color就能简单实现透明度效果了
目前已经通过公共方法传入十六进制格式和透明度参数转rgba格式解决，缺点就是每个实例都要多写一段代码

vant会不会考虑把兼容性处理集成到组件里呢？

**Comment by chenjiahan** [comment]
目前没有计划喔
