### ISSUE TITLE
[Bug Report] checkbox验证非空失败

### ISSUE THREAD

**Issue by limchen233** [youzan/vant#9084]
### 设备 / 浏览器
win10模拟Iphone6,7,8/chrome 90.0.4430.212

### Vant 版本
2.8.6

### Vue 版本
2.5.2

### 重现链接
<a href="https://zo8ki.csb.app/" target="_blank">https://zo8ki.csb.app/</a>

### 描述问题
原本是用<van-row>和<van-col>包裹的checkbox，验证非空失败，而同样包裹的单选框和输入框则验证成功。
现在全部是用div包裹的，van-checkbox还是验证非空失败。
只在输入框的外面包裹van-row，都可以验证成功

**Comment by chenjiahan** [comment]
表单内容太多了，能不能把无效内容删掉？没看出问题在哪

**Comment by limchen233** [comment]
我试了几次减少数据，并没有试出来。
这个表单有固定的8个一级事项，每个一级事项下有对应的二级事项。只有在一级事项选`是`的情况下才出现二级事项。
你可以这样操作，第一个一级事项选`是`，然后会出现它的二级事项，是一个多选。其它事项全部选否即可。
问题是：在多选已经勾选的情况下，验证没通过。
