### ISSUE TITLE
[Bug Report] Picker 在企业微信侧边栏 桌面端 选项无法滑动，卡卡的，只能点某个选项

### ISSUE THREAD

**Issue by 651584008** [youzan/vant#9086]
### 设备 / 浏览器
企业微信电脑端侧边栏h5

### Vant 版本
2.12.22

### Vue 版本
2.6.11

### 重现链接
<a href="https://www.hao123.com/" target="_blank">https://www.hao123.com/</a>

### 描述问题
Picker 在企业微信侧边栏 桌面端 选项无法滑动，卡卡的，只能点某个选项

**Comment by chenjiahan** [comment]
参见桌面端适配：https://vant-contrib.gitee.io/vant/#/zh-CN/advanced-usage#zhuo-mian-duan-gua-pei
