### ISSUE TITLE
Damn, why don't you have a table component?Our project needs this component. If you don't have it, do you need me to write one to help you

### ISSUE THREAD

**Issue by xgyuyu** [youzan/vant#9092]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
There is no plan to provide the table component yet, you can use Cell or CellGroup.
