### ISSUE TITLE
[Feature Request] Popover 气泡弹出框点击 reference 时阻止事件冒泡

### ISSUE THREAD

**Issue by joo1es** [youzan/vant#9098]
### 这个功能解决了什么问题
Popover 气泡弹出框点击 reference 时，目前没有办法处理事件冒泡，导致会触发父级的点击事件

### 描述您想要的解决方案
增加一个Prop，可以设置是否阻止事件冒泡

### 建议的API是什么样的
prop:
stop: {
    type: Boolean,
    default: false
}

**Comment by chenjiahan** [comment]
可以在 Popover 外面包裹一层 div，然后阻止这个 div 的 click 事件冒泡
