### ISSUE TITLE
[Feature Request] NumberKeyboard 数字键盘 close,blur,hide

### ISSUE THREAD

**Issue by EastemChen** [youzan/vant#9102]
点击关闭按钮和非键盘区域时都会触发 close -> blur ->hide ,如何能判断点击的是非键盘区域还是关闭按钮呢?

我想在点击非键盘区域时只是关闭键盘,点关闭按钮时校验输入的数据

vant版本:3.1.4 
测试环境:谷歌和360浏览器

![image](https://user-images.githubusercontent.com/19586337/126731375-c8e3ef19-727b-4b97-b9ea-03e4ee6a5f6d.png)

**Comment by EastemChen** [comment]
希望在使用theme="custom"样式时,提供右下角完成按钮的插槽,不要强制绑定close的回调

**Comment by EastemChen** [comment]
希望在使用theme="custom"样式时,提供右下角完成按钮的插槽,不要强制绑定close的回调

**Comment by chenjiahan** [comment]
这是 3.x 版本的 bug，点击非键盘区域时不应该触发 close 事件，下个版本会修复

**Comment by chenjiahan** [comment]
已在 3.1.5 版本修复 close 事件的问题
