### ISSUE TITLE
[Feature Request] 【F】希望可以加上表格固定列

### ISSUE THREAD

**Issue by NewWorld2** [youzan/vant#9104]
### 这个功能解决了什么问题
希望可以加上表格固定列, 在表格超宽, 超长的时候, 对手机屏幕比较友好

### 描述您想要的解决方案
类似elementUI的表格固定列

### 建议的API是什么样的
固定列: fixed 属性

**Comment by chenjiahan** [comment]
Vant 里没有表格组件喔
