### ISSUE TITLE
[Feature Request] 希望在 vant2 中添加 van-cascader options内容插槽

### ISSUE THREAD

**Issue by lqk9511** [youzan/vant#9105]
### 这个功能解决了什么问题
用户可以自定义列表项的渲染格式，现在只是文字展示太单一。

### 描述您想要的解决方案
目前我看到 vant3 上面已经实现了 options 插槽的但是 vant2 上面并没有

### 建议的API是什么样的
<template #options>...</template>

**Comment by chenjiahan** [comment]
已在 2.12.25 版本支持

**Comment by lqk9511** [comment]
@chenjiahan 非常感谢，但是2.12.25 npm install 不到，是你们还有发布包嘛？`No matching version found for vant@^2.12.25.`

**Comment by chenjiahan** [comment]
有的.

https://www.npmjs.com/package/vant/v/2.12.25
