### ISSUE TITLE
[Bug Report] tab组件开启了swipeable， 并不会触发before-change

### ISSUE THREAD

**Issue by yi-xiao** [youzan/vant#9114]
### 设备 / 浏览器
all

### Vant 版本
3.1.4

### Vue 版本
3.0.5

### 重现链接
<a href="http://vant-contrib.gitee.io/vant-issue-generater/?repo=VantWeapp#/zh-CN?repo=Vant&type=Bug" target="_blank">http://vant-contrib.gitee.io/vant-issue-generater/?repo=VantWeapp#/zh-CN?repo=Vant&type=Bug</a>

### 描述问题
如题，tab组件开启了swipeable， 虽然会触发change事件，但并不会触发before-change，不知道算不算bug，因demo是本地开发的，暂无复现线上链接，抱歉

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/6895
