### ISSUE TITLE
checkbox非空验证失败

### ISSUE THREAD

**Issue by limchen233** [youzan/vant#9121]
### 设备 / 浏览器
win10模拟iphone6

### Vant 版本
2.8.6

### Vue 版本
2.5.20

### 重现链接
<a href="https://2jy29.csb.app/" target="_blank">https://2jy29.csb.app/</a>

### 描述问题
表单数据已减少。
表单有固定的几个一级事项，每个一级事项下有对应的二级事项。只有在一级事项选是的情况下才出现二级事项。只要出现的事项都是必选。
现在的问题：
1、第一个一级事项选是，然后会出现它的二级事项，是一个多选。在多选已勾选的情况下，验证没通过。
2、按步骤1操作完后，第一个事项改为否，第二个事项又验证不通过。
3、先全部选否，验证通过。这时取消发送请求，第一个一级事项改为是，它的二级事项不选择，验证通过。

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/126979626-9b9082e2-5733-4202-a0d3-e66ab7714104.png)

在 Vue 里用 index 作为 key 是错误的，会导致 Vue 无法正确计算组件。改成 name 就可以了。

**Comment by limchen233** [comment]
谢谢！我大意了！
