### ISSUE TITLE
[Bug Report] van-field组件在大多数ios手机中都要点击2次输入框才能聚焦

### ISSUE THREAD

**Issue by lovehebe330** [youzan/vant#9126]
### 设备 / 浏览器
苹果手机

### Vant 版本
3.1.0-beta.0

### Vue 版本
3.0.0

### 重现链接
<a href="https://github.com/lovehebe330/lovehebe330/blob/main/src/views/login/signin.vue" target="_blank">https://github.com/lovehebe330/lovehebe330/blob/main/src/views/login/signin.vue</a>

### 描述问题
van-field在大部门苹果手机上要点击2次才能聚焦 希望点击输入框一次实现聚焦

**Comment by chenjiahan** [comment]
未复现该问题，建议看下是不是其他原因导致的。
