### ISSUE TITLE
H5页面，vant-field组件，如何取vant-field中的name值

### ISSUE THREAD

**Issue by candyAndBella** [youzan/vant#9133]
遍历数组list，

《div v-for="(item,index) in list" :key="index"》

<van-field :value="item.name" :name="index" @input="changeName" />

<van-field :value="item.phone" :name="index" @input="changePhone" />

《/div》

changeName(value){

let index=this.target.dataset.name;//取name值，报错，这里该如何取值？

this.list[index].name=value;

}

请教大家，H5页面，使用vant组件，如何取到vant-field中name的值？

**Comment by chenjiahan** [comment]
非 bug 反馈，请移步讨论区 https://github.com/youzan/vant/discussions
