### ISSUE TITLE
dialog在华为P30  pro上显示有问题

### ISSUE THREAD

**Issue by xu-Aurora** [youzan/vant#9134]
在华为P30  pro上多出来一条线，ios机型上没有看到
![4601627442515_ pic](https://user-images.githubusercontent.com/35291465/127259995-08bbeb33-3eb2-45e5-b038-c0e08979e443.jpg)

**Comment by xu-Aurora** [comment]
![image](https://user-images.githubusercontent.com/35291465/127260110-2b404e21-0cc0-42fd-a084-f8e5b2fea3d8.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
