### ISSUE TITLE
[Bug Report] 直接调用Notify()函数会覆盖默认设置

### ISSUE THREAD

**Issue by angelwgh** [youzan/vant#9135]
### 设备 / 浏览器
Edge

### Vant 版本
3.1.3

### Vue 版本
3.0.0

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-gnup2?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-gnup2?file=/src/App.vue</a>

### 描述问题
调用一次Notify()函数后会覆盖默认设置
在自己的项目里用的时候有一个Notify设置了onClose，然后发现后面每次调用Notify()都会调用这个回调函数
不知道这个算不算bug，看源码是用Object.assign处理参数的

**Comment by chenjiahan** [comment]
已在 3.2.0 版本修复
