### ISSUE TITLE
[Feature Request] Calendar区间选择可以选同一天

### ISSUE THREAD

**Issue by leiyunjn** [youzan/vant#9137]
### 这个功能解决了什么问题
希望区间起止日期选择可以选择同一天

### 描述您想要的解决方案
正在创建一个出租物品的网站，有当天归还物品的需求，目前的Calendar还无法实现

### 建议的API是什么样的
可参照“神州租车”网的日期选择页面

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/127288280-0d4a5155-eea1-4c44-9c77-29d2d301c6a4.png)
