### ISSUE TITLE
关于图片VanImage ，设置radius 或者round 为Ture时，会在style中加上overflow：hidden属性

### ISSUE THREAD

**Issue by qianjue520** [youzan/vant#9141]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
设置 overflow 主要是为了保证插槽内容也是圆角的，如果不需要，可以自行覆盖样式，设置成其他值
