### ISSUE TITLE
[Feature Request] 是否可以增加禁用动画的属性 涉及Overlay 和 Popup组件

### ISSUE THREAD

**Issue by han8435762** [youzan/vant#9143]
### 这个功能解决了什么问题
增加禁用动画的属性 更方便使用
最好是所有涉及动画的组件都做支持

### 描述您想要的解决方案
增加disableAnimation的props

### 建议的API是什么样的
disableAnimation: boolean
默认为false

pr: https://github.com/youzan/vant/pull/9144

**Comment by chenjiahan** [comment]
直接把 duration 设置为 0 就可以喔，没必要添加一个新的属性

**Comment by zhangxinmiao-study** [comment]
直接把 duration 设置为 0 会闪一下再出现 弹窗
