### ISSUE TITLE
[Bug Report] [Vant] Cell: "default" slot is deprecated, please use "value" slot instead.

### ISSUE THREAD

**Issue by shiwanjun1995** [youzan/vant#9145]
### 设备 / 浏览器
谷歌

### Vant 版本
3.0.10

### Vue 版本
3.0.9

### 重现链接
<a href="https://github.com/shiwanjun1995" target="_blank">https://github.com/shiwanjun1995</a>

### 描述问题
控制台提示该警告⚠️

**Comment by chenjiahan** [comment]
Cell 组件的 default 插件已经被废弃了，请使用 value 插槽喔。

旧：写法

```html
<van-cell>
  Value
</van-cell>
```

新写法：

```html
<van-cell>
  <template #value>Value</template>
</van-cell>
```

**Comment by shiwanjun1995** [comment]
原来如此!感谢噢～ 2668923029 ***@***.*** 签名由 网易邮箱大师 定制 On 07/29/2021 15:23, neverland wrote: Cell 组件的 default 插件已经被废弃了，请使用 value 插槽喔。 旧：写法 <van-cell>

  Value

</van-cell> 新写法： <van-cell>

  <template #value>Value</template>

</van-cell> — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lixiaofa** [comment]
`<template #value>
          <van-button round type="success" size="mini">优惠券</van-button>
        </template>`
`"vant": "4.0.0-beta.0",`
 not work    
@chenjiahan

**Comment by chenjiahan** [comment]
@lixiaofa Please open a new issue and provide a reproduce link.
