### ISSUE TITLE
[Feature Request] 希望Field组件能有带输入建议的功能

### ISSUE THREAD

**Issue by yyj961010** [youzan/vant#9146]
### 这个功能解决了什么问题
根据用户输入提供建议列表应该是个比较常用的功能

### 描述您想要的解决方案
功能大致跟elementui的el-autocomplete组件类似

### 建议的API是什么样的
可以自定义搜索，下拉框样式可以自定义，可以自定义获取输入建议的去抖延时

**Comment by chenjiahan** [comment]
暂无计划支持喔

**Comment by liuzengwei** [comment]
> 暂无计划支持喔

未来有计划支持吗？^_^

**Comment by chenjiahan** [comment]
还没有哈，可以自行封装一下

**Comment by xiangnanscu** [comment]
@chenjiahan 能否提示一下自行封装的思路?比如那个下拉框可以用vant的什么组件, 或者有什么第三方的组件作为例子
