### ISSUE TITLE
[Feature Request] Collapse组件加入异步展开events

### ISSUE THREAD

**Issue by pei-zheng-yi** [youzan/vant#9155]
### 这个功能解决了什么问题
某些场景下CollapseItem 内容较多，根据Collapse 来决定加载对应的内容，需要异步加载

### 描述您想要的解决方案
加入一个expand 事件，通过resolve/reject 决定是否展开
同时右侧图标可改为loading样式，类似按钮的loading状态，loading状态下不再触发expand事件

### 建议的API是什么样的

```html
<van-collapse @expand=“handleExpand”>

<script>
// ....
handleExpand(){
  // some async network request or something else
 resolve(true)  // 展开面板
  // or
resolve(false) // 不展开
// or
reject() // 不展开
}
// ....
</script>
```

**Comment by chenjiahan** [comment]
> 加入一个expand 事件，通过resolve/reject 决定是否展开

你可以把 v-model 拆分成 :model-value 和 @update:model-value，然后在 @update:model-value 内部控制展开的时机

> 同时右侧图标可改为loading样式，类似按钮的loading状态，loading状态下不再触发expand事件

这个用插槽做就行
