### ISSUE TITLE
[Bug Report] keep-alive导致van-radio报错

### ISSUE THREAD

**Issue by yexiaodong** [youzan/vant#9160]
### 设备 / 浏览器
chorme92

### Vant 版本
3.1.5

### Vue 版本
3.1.5

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-vgvnn" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-vgvnn</a>

### 描述问题
使用keep-alive单向缓存表单页时，重新激活页面后，van-radio组件点击报错。

**Comment by chenjiahan** [comment]
你的 keep-alive 用法问题，动态修改 keepAliveComponents 的时候，导致 Radio 组件没法获取自身的 ref 了

可以考虑使用固定的 keepAliveComponents 值

**Comment by yexiaodong** [comment]
若使用固定值，页面的数据处理逻辑会非常麻烦，能否优化一下

**Comment by chenjiahan** [comment]
这个优化和组件本身无关，组件内部的 ref 写法是规范的
