### ISSUE TITLE
[Bug Report] iPhone 12 pro max Dialog组件没有显示隐藏动画

### ISSUE THREAD

**Issue by Peter-Success** [youzan/vant#9167]
### 设备 / 浏览器
IOS14.6

### Vant 版本
2.12.25

### Vue 版本
2.5.22

### 重现链接
<a href="https://testcdn.tianhongjijin.com.cn/weixin-vue/wx.html#/wxInviteFriend/wxActivityHome?activityId=bEdoDctsxIEXrhCVUZWrvg==" target="_blank">https://testcdn.tianhongjijin.com.cn/weixin-vue/wx.html#/wxInviteFriend/wxActivityHome?activityId=bEdoDctsxIEXrhCVUZWrvg==</a>

### 描述问题
iPhone 12 pro max点击页面中的活动规则弹窗出现和隐藏没有动画，经查证为IOS14上CSS的transform属性失效导致。

**Comment by Peter-Success** [comment]
?没人关注吗

**Comment by chenjiahan** [comment]
链接打不开喔，麻烦提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f

**Comment by Peter-Success** [comment]
iPhone 12 pro max IOS14.6系统直接打开vant的dialog页面即可复现，可以拿真机看下。

**Comment by chenjiahan** [comment]
试了下没复现，如果是 iOS 14 transform 失效的话，组件层面也没有什么可以配合修改的
