### ISSUE TITLE
[Bug Report] field设置为textarea且添加autosize属性，在行数多的情况下出现bug

### ISSUE THREAD

**Issue by yanluohao** [youzan/vant#9178]
### 设备 / 浏览器
移动端和mac的webview都存在问题

### Vant 版本
3.0.18

### Vue 版本
3.0.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-5tpzl?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-5tpzl?file=/src/App.vue</a>

### 描述问题
field为textarea，且添加了autosize的属性的时候，如果输入框内的内容已经是超过当前页面一屏的情况下，在任意输入框位置进行输入 ，会直接把整个输入框滚动到最上方的位置，看了代码，应该是在resize的时候，每次都把input.style.height = 'auto'的缘故。

**Comment by chenjiahan** [comment]
已在 3.2.0 版本修复

**Comment by Bin851908788** [comment]
2.0版本也有这个问题啊大佬 怎么解决一下 急！！！
