### ISSUE TITLE
[Bug Report] Cascader 级联选择 设置选中value不生效

### ISSUE THREAD

**Issue by niceMoonMaker** [youzan/vant#9187]
### 设备 / 浏览器
google

### Vant 版本
2.12.25

### Vue 版本
2.6.14

### 重现链接
<a href="http://localhost:9981/#/pickCode" target="_blank">http://localhost:9981/#/pickCode</a>

### 描述问题
Cascader 级联选择 设置选中value不生效

**Comment by niceMoonMaker** [comment]
![image](https://user-images.githubusercontent.com/29392743/128281994-f0de3d39-1a09-466e-82ef-c50bb04208fd.png)

**Comment by niceMoonMaker** [comment]
testValue: value(Sting)

**Comment by chenjiahan** [comment]
请提供有效的复现链接

https://codesandbox.io/s/m5v3f
