### ISSUE TITLE
Circle 环形进度条字体大小设置

### ISSUE THREAD

**Issue by ggxing** [youzan/vant#9188]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
https://vant-contrib.gitee.io/vant/v3/#/zh-CN/quickstart#ru-he-zi-ding-yi-vant-zu-jian-de-yang-shi
