### ISSUE TITLE
[Bug Report] 【rate】Rate 评分这个count设置比较多的

### ISSUE THREAD

**Issue by zhuangxiaohui** [youzan/vant#9189]
### 设备 / 浏览器
谷歌

### Vant 版本
2.12.25

### Vue 版本
2.6.14

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-3vemc?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-3vemc?file=/src/App.vue</a>

### 描述问题
Rate 评分这个count设置比较多的 会被遮挡，应该换行
![image](https://user-images.githubusercontent.com/5791725/128315081-eefe77c5-fdb1-4323-bc31-a0efb3c2640f.png)

### 期望预期

![image](https://user-images.githubusercontent.com/5791725/128315048-5ec65a53-03f7-44de-b69c-ebbc02c6e4f3.png)

**Comment by zhuangxiaohui** [comment]
能否修复到v2的版本了

**Comment by chenjiahan** [comment]
也修了。

**Comment by chenjiahan** [comment]
已在 3.2.0 版本修复
