### ISSUE TITLE
[Bug Report] Toast 动态更新提示message 错误

### ISSUE THREAD

**Issue by Yee1014** [youzan/vant#9190]
### 设备 / 浏览器
Chrome

### Vant 版本
3.0.18

### Vue 版本
3.1.1

### 重现链接
<a href="https://codesandbox.io/s/blissful-ptolemy-2oot3" target="_blank">https://codesandbox.io/s/blissful-ptolemy-2oot3</a>

### 描述问题
使用Toast.message 动态更新之后,clear没有清除message, 导致其他Toast message使用无效!

**Comment by chenjiahan** [comment]
已在 3.2.0 版本修复
