### ISSUE TITLE
[Feature Request] Circle / Slider 支持起始位置定义

### ISSUE THREAD

**Issue by Airkro** [youzan/vant#9191]
### 这个功能解决了什么问题
`Circle` 进度条支持从圆环底部开始。

垂直 `Slider` 支持底部为 min，顶部为 max

### 描述您想要的解决方案
添加参数以用于控制

### 建议的API是什么样的
```vue
<van-circle start-on-bottom />
<van-slider vertical="reverse" />
```

**Comment by chenjiahan** [comment]
已在 3.2.1 版本支持

**Comment by Airkro** [comment]
2.x 是否有可能支持？

**Comment by chenjiahan** [comment]
@Airkro 精力有限喔，欢迎把相关 MR 的功能迁移到 2.x 分支，然后提一个新的 MR
