### ISSUE TITLE
能不能考虑增加一个分页功能？

### ISSUE THREAD

**Issue by leftstyle** [youzan/vant#92]
###  分页功能还是很常用的，能不能增加一个？

**Comment by chenjiahan** [comment]
@leftstyle 移动端场景里分页功能不太常见，更多时候会使用瀑布流组件。能描述下你的业务场景吗

**Comment by leftstyle** [comment]
@chenjiahan 一个小型的电商站，列表页需要翻页的功能。

**Comment by chenjiahan** [comment]
@leftstyle 请问是这种效果吗
<img width="361" alt="2017-08-29 3 53 13" src="https://user-images.githubusercontent.com/7237365/29810435-567ec234-8cd2-11e7-9c5c-cc67c36b3fc2.png">

**Comment by leftstyle** [comment]
比这个显示的页码要多一些，最好是可以灵活配置。我目前使用的是这款，自己加了一些逻辑进去。

https://github.com/sant123/vuejs-uib-pagination

**Comment by chenjiahan** [comment]
@leftstyle 了解了，这个组件会加到后续的开发计划当中，感谢反馈~

**Comment by chenjiahan** [comment]
@leftstyle 分页组件已在 0.11.0 中添加
