### ISSUE TITLE
[Feature Request] v-model:show导致eslint报错

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant#9210]
### 这个功能解决了什么问题
v-model:show导致eslint报错

### 描述您想要的解决方案
将v-model:show替换，使用其它属性写法，避免eslint报错

### 建议的API是什么样的
将v-model:show替换，使用其它属性写法，避免eslint报错

**Comment by chenjiahan** [comment]
这是 Vue3 标准语法，请升级你的 eslint-plugin-vue 到 7.0 以上版本
