### ISSUE TITLE
[Bug Report] vant没有导出UploaderInstance类型

### ISSUE THREAD

**Issue by CaicoLeung** [youzan/vant#9211]
### 设备 / 浏览器
chrome

### Vant 版本
3.1.5

### Vue 版本
3.1.5

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-0r7pt?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-0r7pt?file=/src/App.vue</a>

### 描述问题
Module '"../node_modules/vant/types"' has no exported member 'UploaderInstance'

根据Uploader组件文档"类型定义"处的代码示例
![image](https://user-images.githubusercontent.com/36806569/128655350-53ab69bb-d622-4aaf-a4f2-74b1d435181d.png)

**Comment by chenjiahan** [comment]
这是 3.2.0 新增的，本周发布

**Comment by pocketChao** [comment]
太负责了，还未新增文档就更上了👍

**Comment by chenjiahan** [comment]
😂意外意外，文档站点自动部署了

**Comment by CaicoLeung** [comment]
其他组件例如SwipeCell未导出SwipeCellInstance, Checkbox未导出CheckboxInstance、CheckboxGroupInstance也是一样的问题吗

**Comment by chenjiahan** [comment]
一样的

**Comment by chenjiahan** [comment]
已发布 3.2.0 版本
