### ISSUE TITLE
[Bug Report] 主题变量配置未导出

### ISSUE THREAD

**Issue by JacksMaster** [youzan/vant#9212]
### 设备 / 浏览器
Chrome

### Vant 版本
3.1.5

### Vue 版本
3.2.0-beta.8

### 重现链接
暂无

### 描述问题
ActionSheet 未导出按钮 按下背景色配置
NumberKeyboard 和PasswordInput 未导出数字按钮背景色与数字文字颜色配置
ShareSheet 未导出弹出框背景色配置

目前就发现这几个。但是还是希望官方能够提供一键切换到夜间模式 此功能可以参考：<a href="https://www.naiveui.com/zh-CN/os-theme/components/config-provider" target="_blank">naiveui</a>
如果一个组件的去配置夜间模式 写的配置太多了很耗时间，而且还有一些问题

**Comment by chenjiahan** [comment]
夜间模式暂时没资源支持喔，变量后续会加上

**Comment by JacksMaster** [comment]
> 夜间模式暂时没资源支持喔，变量后续会加上

追加一个 Cascader 级联选择没有导出修改tabs下面的选中配色js变量
DatetimePicker 时间选择 没有导出选中时间以及背景色的less和js变量
其他还有一些组件没有列出来，你们修改的时候看一下吧

**Comment by chenjiahan** [comment]
> ActionSheet 未导出按钮 按下背景色配置

已有变量：`--van-active-color`

> ShareSheet 未导出弹出框背景色配置

已有变量：`--van-popup-background-color`

> NumberKeyboard 和PasswordInput 未导出数字按钮背景色与数字文字颜色配置

后续添加

>  Cascader 级联选择没有导出修改tabs下面的选中配色js变量

已有变量：`--van-tabs-bottom-bar-color`

> DatetimePicker 时间选择 没有导出选中时间以及背景色的less和js变量

继承的 Picker

**Comment by chenjiahan** [comment]
已在 3.2.1 版本支持

**Comment by jiajiaxing1** [comment]
> 已在 3.2.1 版本支持

DatetimePicker样式修改，修改了背景颜色，但是还有个蒙层的颜色不知道是哪个变量？

https://github.com/youzan/vant/discussions/13457
