### ISSUE TITLE
[Feature Request] TreeSelect 分类选择，items可以支持自定义id、text和children的键名吗？

### ISSUE THREAD

**Issue by wangbaiwang** [youzan/vant#9215]
### 这个功能解决了什么问题
Item 数据结构与项目实际使用中的键名不同，需要对数据进行遍历，使用文档中的键名，才能正常使用。

### 描述您想要的解决方案
items可以支持自定义id、text和children的键名

### 建议的API是什么样的
Props = {
    value: 'id',
    text: 'name',
    children: 'cities'
  };

**Comment by chenjiahan** [comment]
暂时不考虑支持喔，抱歉
