### ISSUE TITLE
PullRefresh 触发机制

### ISSUE THREAD

**Issue by sAnChu2shushu** [youzan/vant#922]
PullRefresh 是否能在子组件滚动条已到页面最顶部才能生效?

在预览中的页面中使用的固定高度.
`.demo-pull-refresh .van-pull-refresh, .demo-pull-refresh .van-pull-refresh__track {
    height: calc(100vh - 50px);
}`
我给的是100%,子组件100%,overflow-y.
`
  .van-pull-refresh,.van-pull-refresh__track{
    height: 100%;
  }
  .refreshLayout{
    height: 100%;
    overflow-y: auto;
    .spItem{
      height: 60px;
    }
  }
`

**Comment by chenjiahan** [comment]
能否提供一个 jsfiddle?
