### ISSUE TITLE
[Bug Report] tab 组件切换动画在 iOS 设备表现卡顿现象

### ISSUE THREAD

**Issue by WuChenDi** [youzan/vant#9225]
### 设备 / 浏览器
iPhone X 

### Vant 版本测试
2.12.25
2.12.23

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/tab" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/tab</a>

### 描述问题
目前在项目使用 tab 组件切换动画在 iOS 设备表现卡顿现象，底部条line会比字体显示慢的情况；
已新建干净项目测试表现相同情况，目前官网 https://vant-contrib.gitee.io/vant/#/zh-CN/tab 表现相同；

复现设备：iPhone X 软件版本为14.5

**Comment by chenjiahan** [comment]
具体卡顿是什么样子，有视频吗

**Comment by WuChenDi** [comment]
就是线条与字体的动画之间存在卡顿。
但是昨天升级了iOS版本到 14.7.1 问题未复现了

**Comment by chenjiahan** [comment]
那就是系统本身的问题喔，修复了就 ok
