### ISSUE TITLE
[Bug Report] CountDown设置auto-start为false后，必须触发点击事件才能开始

### ISSUE THREAD

**Issue by coderang** [youzan/vant#9227]
### 设备 / 浏览器
chrome 内核86

### Vant 版本
2.12.25

### Vue 版本
2.6.10

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/count-down" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/count-down</a>

### 描述问题
必须将this.$refs.countDown.start();放在页面的点击事件方法中执行才能手动开启，无法直接在钩子函数中直接调用this.$refs.countDown.start();开启

**Comment by chenjiahan** [comment]
复现链接无效，请提供有效的复现链接

https://codesandbox.io/s/m5v3f
