### ISSUE TITLE
col not work

### ISSUE THREAD

**Issue by yecao007** [youzan/vant#923]
<van-row gutter="20">
  <van-col span="8">span: 8</van-col>
  <van-col span="8">span: 8</van-col>
  <van-col span="8">span: 8</van-col>
</van-row>

import { Row, Col } from 'vant';

引入了Row和Col，最后row解析正常，col解析不行，可能跟table的col冲突了，重名其他名字之后就可以

**Comment by chenjiahan** [comment]
注册时不要使用存在冲突的组件名
