### ISSUE TITLE
3.1.5  form 文档包含了 FormInstance；但是3.1.5 代码还未有 FormInstance；FormInstance这个是在你们 dev 分支； 请修改。

### ISSUE THREAD

**Issue by huangd-d** [youzan/vant#9239]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/9219
