### ISSUE TITLE
[Bug Report] uniapp 中使用 vant，ImagePreview 报错

### ISSUE THREAD

**Issue by liuzhenghe30265** [youzan/vant#9241]
### 设备 / 浏览器
移动、pc/谷歌

### Vant 版本
2.12.25

### Vue 版本
2.6.14

### 重现链接
<a href="https://images.gitee.com/uploads/images/2021/0811/155652_ccdc56a1_5249485.png" target="_blank">https://images.gitee.com/uploads/images/2021/0811/155652_ccdc56a1_5249485.png</a>

### 描述问题
uniapp 中使用 vant，ImagePreview 报错
Invalid handler for event "load": got undefined
![输入图片说明](https://images.gitee.com/uploads/images/2021/0811/155652_ccdc56a1_5249485.png "屏幕截图.png")

**Comment by chenjiahan** [comment]
Vant 没有专门适配 uni-app 喔，建议自行排查。
