### ISSUE TITLE
[Bug Report] webpack5按需加载vant无效

### ISSUE THREAD

**Issue by Yeahgw** [youzan/vant#9242]
### 设备 / 浏览器
mac/chrome

### Vant 版本
3.1.5

### Vue 版本
3.2.1

### 重现链接
<a href="https://github.com/Yeahgw/webpackvant.git" target="_blank">https://github.com/Yeahgw/webpackvant.git</a>

### 描述问题
webpack5项目按需引入vant的组件后，只得到一个空对象，是我babel配置少了什么插件吗？

![image](https://user-images.githubusercontent.com/10267554/129011998-bcbb302c-8118-4d96-a7f5-cf3723c44da6.png)

**Comment by u4989190** [comment]
我用vite构建的项目，按需加载也是无效。。。全局倒是可以。没搞清楚是不是哪里配置的不对

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-demo
