### ISSUE TITLE
按需引入DatetimePicker组件时出现错误

### ISSUE THREAD

**Issue by op8278** [youzan/vant#925]
![default](https://user-images.githubusercontent.com/16401198/39174737-176a54ae-47db-11e8-9d95-623b3aa46b08.PNG)

vue,vant版本如下
```
    "vant": "^1.0.8",
    "vue": "^2.5.13",
```
以下是我的引入方式
```
    <van-datetime-picker
      v-model="currentDate"
      type="datetime"
      :min-date="minDate"
      :max-date="maxDate"
    />
```
```
import vanDatetimePicker from 'vant/lib/datetime-picker';
export default {
 data() {
    return {
      minHour: 10,
      maxHour: 20,
      minDate: new Date(),
      maxDate: new Date(2019, 10, 1),
    }
  },
  components: {
    vanDatetimePicker,
  },
}
```

补充:
我全局引用之后,也是如此
![1](https://user-images.githubusercontent.com/16401198/39175194-4847d866-47dc-11e8-9cab-967f55646ee1.PNG)
![3](https://user-images.githubusercontent.com/16401198/39175196-4b37c8ba-47dc-11e8-93dd-ae8392ce4b5b.PNG)

**Comment by jerryni** [comment]
`import vanDatetimePicker from 'vant/lib/datetime-picker';`  这个模块没注册过的不能这样引用，除非你设置了 alias之类；

你说的全局引用出问题，这个应该不会，建议你重新排查下别的方面的问题; 引用方式参考这里：https://www.youzanyun.com/zanui/vant#/zh-CN/datetime-picker
