### ISSUE TITLE
[Bug Report] van-sticky 吸底 无效。一直在顶部

### ISSUE THREAD

**Issue by LCBbest** [youzan/vant#9250]
### 设备 / 浏览器
谷歌

### Vant 版本
3.0.16

### Vue 版本
3.2.2

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/v3/#/zh-CN/sticky" target="_blank">https://vant-contrib.gitee.io/vant/v3/#/zh-CN/sticky</a>

### 描述问题
van-sticky 吸底 无效。一直在顶部
```
<template>
  <van-sticky :offset-bottom="50" position="bottom">
    <van-button type="primary">吸底距离</van-button>
  </van-sticky>
</template>
```
改成top再改回来 不刷新界面 可以吸底，但是刷新界面 就失效。（van-sticky-fixed没加载出来）
![image](https://user-images.githubusercontent.com/12879534/129182268-2c036a96-e5cb-41b4-9e09-a6c7f0755939.png)

![image](https://user-images.githubusercontent.com/12879534/129292690-f1ee07ef-9890-46bd-b9ef-c088179c2b39.png)

**Comment by chenjiahan** [comment]
复现链接无效，请提供有效的复现链接

https://codesandbox.io/s/m5v3f

**Comment by LCBbest** [comment]
> 复现链接无效，请提供有效的复现链接
> 
> https://codesandbox.io/s/m5v3f

https://5y7pv.csb.app/
这是复现连接。
