### ISSUE TITLE
[Bug Report] search组件点击×号 无反应

### ISSUE THREAD

**Issue by wty8023** [youzan/vant#9251]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.25

### Vue 版本
2.5.8

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-q7m7u" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-q7m7u</a>

### 描述问题
点击search组件右边叉号 没有调用clear 事件

**Comment by toesbieya** [comment]
在移动端试，[官方文档](https://vant-contrib.gitee.io/vant/#/zh-CN/search#chang-jian-wen-ti)

**Comment by xixihappy** [comment]
所以只能在移动端？ 但目前有人用浏览器打开 这个clear 就无效了 必须调成手机模式才可以
