### ISSUE TITLE
[Feature Request] vant-cli如何定义全局样式，注册全局组件

### ISSUE THREAD

**Issue by RenJie0813** [youzan/vant#9258]
### 这个功能解决了什么问题
无法定义全局样式，Vue.use形式注册全局组件

### 描述您想要的解决方案
默认获取src下index.js与index.css全局加载注册

### 建议的API是什么样的
提供入口js能挂载到Vue对象

**Comment by chenjiahan** [comment]
可以通过 webpack.config.js 的 entry 字段插入一些自定义的逻辑，参见 https://github.com/youzan/vant/blob/dev/webpack.config.js

**Comment by RenJie0813** [comment]
> 可以通过 webpack.config.js 的 entry 字段插入一些自定义的逻辑，参见 https://github.com/youzan/vant/blob/dev/webpack.config.js

![Uploading image.png…]()
打包出来会有问题

**Comment by RenJie0813** [comment]
> 可以通过 webpack.config.js 的 entry 字段插入一些自定义的逻辑，参见 https://github.com/youzan/vant/blob/dev/webpack.config.js
![image](https://user-images.githubusercontent.com/22877978/129519217-939c2f73-52ad-40cb-a311-4d3d03307f02.png)

打包出来会有问题
