### ISSUE TITLE
[Bug Report] DropdownMenu 在 Dialog 中的显示问题

### ISSUE THREAD

**Issue by songhn233** [youzan/vant#9259]
### 设备 / 浏览器
Chrome 92

### Vant 版本
2.12.25

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-8nq45?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-8nq45?file=/src/App.vue</a>

### 描述问题
现在 DropdownMenu 的样式在 Dialog 中难以以一个合适的方式展示。

并且现在 DropdownMenu 组件在 Dialog 处于完全不可用的状态。是否考虑以一种降级的方式来处理？

**Comment by jessica2010** [comment]
我也遇到相同问题了，是在popup中使用dropdown，也是这样情况。看css可以发现弹窗的top值不对。目前还没找到解决办法。

**Comment by ascodelife** [comment]
这个问题的原因是，弹出层默认被挂载在了父组件下，因为弹出层脱离了文档流不会撑开父组件，而父组件原来的高度不够，所以弹出层没法显示出来。一般解决方案为默认挂载到body下，但是需要计算一下top left值，现在代码里没有这块计算逻辑，具体实现可以参考https://github.com/popperjs/popper-core

**Comment by jessica2010** [comment]
谢谢，应该是这个原因。可惜我把这段代码删除了，没办法测试。

**Comment by songhn233** [comment]
@chenjiahan Hello, 这个 issue 关闭的原因是什么，看起来在最新版本中 codesandbox 依然可以复现

**Comment by chenjiahan** [comment]
组件内部去吃掉这个逻辑比较困难，现在 DropdownItem 有提供 teleport 属性的。
