### ISSUE TITLE
使用vite使用按需引入vant组件为什么报[vite:css] variable '--van-gray-5' is undefined and used without a fallback，并且没有:root{}节点

### ISSUE THREAD

**Issue by chchenhu** [youzan/vant#9261]
使用vite使用按需引入vant组件为什么会报[vite:css] variable '--van-gray-5' is undefined and used without a fallback，并且没有:root{}节点，我想使用ConfigProvider 全局配置改变主题

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
