### ISSUE TITLE
[Bug Report] Sticky吸底无效

### ISSUE THREAD

**Issue by LCBbest** [youzan/vant#9264]
### 设备 / 浏览器
谷歌

### Vant 版本
3.2.0

### Vue 版本
3.2.2

### 重现链接
<a href="https://codesandbox.io/s/gifted-edison-krssh" target="_blank">https://codesandbox.io/s/gifted-edison-krssh</a>

### 描述问题
Sticky吸底无效

```
<van-sticky :offset-bottom="50" position="bottom">
  <van-button type="primary">吸底距离</van-button>
</van-sticky>

```

**Comment by chenjiahan** [comment]
页面滚动到底部时才会吸底的，在重现链接中未发现问题
