### ISSUE TITLE
vue2  tabs   sticky 属性  失效问题

### ISSUE THREAD

**Issue by ARE123123** [youzan/vant#9266]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
![image](https://user-images.githubusercontent.com/56105589/129651716-76ba461a-44fa-4702-96b2-bf5392e13849.png)
通过图片这么设置就是有问题的   粘性定位

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
