### ISSUE TITLE
vant-tabs 设置sticky出现bug

### ISSUE THREAD

**Issue by xuhang1993** [youzan/vant#9271]
我打开sticky功能 一开始是有效的,但是当滑动手机屏幕长度时,tabs就会跟着向上滑动

![59a3faf65d5424eeb218438c01f27ad](https://user-images.githubusercontent.com/12042799/129676251-b46f1ab3-c13e-4d5b-b0c3-c904db1c6ffb.jpg)

![9f009bb01086242d572dff62d80e079](https://user-images.githubusercontent.com/12042799/129676274-137babc9-afd0-40e5-9542-2e28bddcd82c.jpg)

![c716c47a9b4158f7d12e17b2f7e6d99](https://user-images.githubusercontent.com/12042799/129676325-a48737e8-baa1-4405-ab77-e82ef955d3a0.jpg)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
