### ISSUE TITLE
[Bug Report] vant3的tab页标签使用echarts图表不能正确渲染

### ISSUE THREAD

**Issue by icnz** [youzan/vant#9272]
### 设备 / 浏览器
Microsoft Edge92.0.902.73

### Vant 版本
3.2.0

### Vue 版本
3.2.3

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-qfzm1?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-qfzm1?file=/src/App.vue</a>

### 描述问题
项目使用vant3的tab页标签显示echarts图表，图表的宽度不能100%展示在容器，而是一个100px * 200px的图表。
在非tab页正确显示没有问题，查阅了各种资料，也做了尝试，但都不能解决问题。
代码如CodeSandbox中所示。
说明：代码在本地显示vant3的tab页标签显示是正常的，在CodeSandbox中虽不正常但功能正常；echarts显示问题和CodeSandbox一样。

**Comment by chenjiahan** [comment]
延迟渲染一下就好，参见 https://codesandbox.io/s/vant-issue-mo-ban-forked-0qrnx?file=/src/App.vue

**Comment by icnz** [comment]
感谢大神的解答
