### ISSUE TITLE
van-swipe ios 11 微信环境手滑切换存在卡顿

### ISSUE THREAD

**Issue by songzy1993** [youzan/vant#9273]
下面是测试链接： 
https://qf.jfshou.cn/coolcard/mall/#/index?alias=%E6%88%91%E7%9A%84%E5%95%86%E5%9F%8E&authCode=EdCVAawmOJtGDwqP
安卓环境 不存在卡顿  只有ios 11 存在问题；而且必现； swipe 手动切换存在这个问题

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
