### ISSUE TITLE
[Feature Request] van-tree-select 左侧列表可否自定义某个颜色

### ISSUE THREAD

**Issue by yimity** [youzan/vant#9277]
### 这个功能解决了什么问题
在左侧列表中，业务需求某个列表项需要有特殊的颜色或者视觉效果。例如可以最后增加一项：没有找到，添加 。但是需要颜色不同。

### 描述您想要的解决方案
可以在 van-tree-select__content 这个 <view/> 中的 class 加上 item 的 id 或者 text 或者 其他字段来生成唯一的跟列表项相关的 class，用户即可自定义颜色等。或者同时可以在数据顶层及 badge 同一层定义 classKey 类似的字段，来确定在 view 的 class 中使用那个 字段。

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/130060360-ee0aa042-bb9c-45db-93ec-a77ddc7aa563.png)

可以用这个字段
