### ISSUE TITLE
vue 版本3.0          vant版本3.0  无法正常使用vant-popover

### ISSUE THREAD

**Issue by chenhaijun2019** [youzan/vant#9280]
![image](https://user-images.githubusercontent.com/49867880/129837113-cd78b84b-0fd8-4483-9ecc-34f95c044eba.png)
![image](https://user-images.githubusercontent.com/49867880/129837137-97eb9cfb-9d84-42fa-8974-8863f36a520a.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
