### ISSUE TITLE
[Bug Report] vant-cli下的demo文件夹里可以建多个.vue文件以后路由如何访问

### ISSUE THREAD

**Issue by qianzhangsheng** [youzan/vant#9284]
### 设备 / 浏览器
macOS/Chrome 92.0.4515.159

### Vant 版本
2.12.26

### Vue 版本
2.6.13

### 描述问题
vant-cli下的demo文件夹里可以建多个.vue文件以后路由如何访问？现在只能访问index.vue，如果在建一个index1.vue需要如何访问

**Comment by chenjiahan** [comment]
没有提供这种能力，只能访问 index.vue
