### ISSUE TITLE
[Bug Report] upload上传会导致页面刷新

### ISSUE THREAD

**Issue by jiaxiaon** [youzan/vant#9287]
### 设备 / 浏览器
IOS

### Vant 版本
3.1.3

### Vue 版本
3.0.0

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-7i70q?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-7i70q?file=/src/App.vue</a>

### 描述问题
当用户上传选择图片之后，部分用户会出现刷新浏览器的bug

**Comment by chenjiahan** [comment]
可能图片太大了，导致内存溢出，可以压缩图片试试，或者把 Uploader 的 `result-type` 设置为 `file`
