### ISSUE TITLE
[Bug Report] datetimepicker设置最小时间无效

### ISSUE THREAD

**Issue by czl0325** [youzan/vant#9288]
### 设备 / 浏览器
所有

### Vant 版本
3.2.0

### Vue 版本
3.2.4

### 重现链接
<a href="https://codesandbox.io/s/practical-hopper-cirql?file=/src/main.js" target="_blank">https://codesandbox.io/s/practical-hopper-cirql?file=/src/main.js</a>

### 描述问题
<van-datetime-picker type="date"  v-model="currentDate" :min-data="minDate"/>
minDate = new Date()
设置了允许选择的最小时间为当天，但是还是可以选择以前的时间。请问能和ios的选择器一样，选择了之前的时间就会自动滑回来吗？

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/131234356-bc6ea3f1-0a2c-49bc-8dac-b340aeb17176.png)

单词拼错了，是 min-date
