### ISSUE TITLE
[Bug Report] 引入vant组件库报非相关的错误

### ISSUE THREAD

**Issue by lovehebe330** [youzan/vant#9289]
### 设备 / 浏览器
pc

### Vant 版本
3.1.0-beta.0

### Vue 版本
3.2.4

### 重现链接
<a href="http://vant-contrib.gitee.io/vant-issue-generater/#/zh-CN" target="_blank">http://vant-contrib.gitee.io/vant-issue-generater/#/zh-CN</a>

### 描述问题
引入vant组件库控制台报错帮忙排查下原因 删掉重新安装node_modules依旧没效果
![image](https://user-images.githubusercontent.com/20655248/130020059-28616f0c-1a10-4b9c-8b22-8574e75eb544.png)
![image](https://user-images.githubusercontent.com/20655248/130020083-abb0b4f3-e03c-49be-879b-caed20d9778d.png)
![image](https://user-images.githubusercontent.com/20655248/130020106-6f119e20-ceb7-4abb-9ef0-17d015091399.png)
![image](https://user-images.githubusercontent.com/20655248/130020120-cb37ab16-53ea-424f-b07b-19be0cb36396.png)

**Comment by chenjiahan** [comment]
从截图上看和 Vant 没有关系呢，建议自行排查
