### ISSUE TITLE
vant2的select下拉框升级到vant3消失了，请问vant2可以和vant3同时使用吗？

### ISSUE THREAD

**Issue by jessica2010** [youzan/vant#9296]
vant2的select下拉框升级到vant3消失了，vant3并没有同样好的组件可以替代，请问vant2可以和vant3同时使用吗？

**Comment by chenjiahan** [comment]
Vant 2 没有提供 Select 下拉框组件呢

**Comment by jessica2010** [comment]
vant2也没有下拉框，是我搞错了，非常抱歉误导大家了。
