### ISSUE TITLE
[Bug Report] Dialog会直接显示出来

### ISSUE THREAD

**Issue by StoneShiLei** [youzan/vant#9297]
### 设备 / 浏览器
chrome 版本 91.0.4472.124

### Vant 版本
3.2.0

### Vue 版本
3.2.0

### 重现链接
<a href="https://jsbin.com/wodejuketa/2/edit?html,js,output" target="_blank">https://jsbin.com/wodejuketa/2/edit?html,js,output</a>

### 描述问题
Dialog在页面加载后悔自动显示出来   即使show为false也是      推测是因为不兼容script setup？  有什么办法可以解决

控制台警告如下[Vue warn]: Extraneous non-props attributes (show, title, show-cancel-button) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <Dialog show=false onUpdate:show=fn title="新增"  ... > 
  at <Type onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >

**Comment by chenjiahan** [comment]
Dialog 是兼容 script setup 的，可以参考 demo 代码：https://github.com/youzan/vant/blob/dev/src/dialog/demo/index.vue

建议自行排查下，看看是不是调用方法有问题

**Comment by gg343917542** [comment]
Dialog如果用组件调用的方式使用，注册的应该是Dialog.Component，但setup script那种方式应该是不行了

**Comment by chenjiahan** [comment]
可以这样试试：

```jsx
const VanDialog = Dialog.Component;

<VanDialog />
```

**Comment by gg343917542** [comment]
@chenjiahan 嗯，这种可以。

**Comment by GIS90** [comment]
完美

**Comment by GIS90** [comment]
完美解决，秀儿
