### ISSUE TITLE
rem还没解决方案吗，可以提供些思路怎么快速解决

### ISSUE THREAD

**Issue by lyseky** [youzan/vant#931]
px是写死的，不好做动态适配，还是得靠rem

**Comment by chenjiahan** [comment]
组件样式默认使用`px`作为单位，如果需要使用`rem`作为单位，推荐使用以下两个工具

- [postcss-pxtorem](https://github.com/cuth/postcss-pxtorem) 用于将单位转化为 rem
- [lib-flexible](https://github.com/amfe/lib-flexible) 用于设置 rem 基准值

**Comment by lyseky** [comment]
我就是用这两个，导入官方样式会变小

**Comment by chenjiahan** [comment]
变小是什么意思

**Comment by lyseky** [comment]
@chenjiahan 整体都缩小了

**Comment by chenjiahan** [comment]
是你 rem 配置的问题

**Comment by ExploreDuo** [comment]
整体变小的原因 应该是因为设置单位是75，而vant使用的是设计图尺寸/2的单位（37.5吧），所以不同。。。

**Comment by ExploreDuo** [comment]
刚刚测试，可以使用“postcss-px2rem-exclude” 这个工具，忽略vant不使用rem！
`require('postcss-px2rem-exclude')({
        remUnit: 75, // 转换基本单位
        exclude: /node_modules|vant/
      })`

**Comment by BreezeDealer** [comment]
还有用大漠提供的转vw的方案也会造成vant的缩放有问题，所以我想到的一个笨方法就是样式多写个/2，配置文件也改为/2。
