### ISSUE TITLE
[Bug Report] swipe无法横向拖动

### ISSUE THREAD

**Issue by benjaken** [youzan/vant#9310]
### 设备 / 浏览器
all

### Vant 版本
3.2.1

### Vue 版本
3.2.4

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/v3/#/zh-CN/swipe" target="_blank">https://vant-contrib.gitee.io/vant/v3/#/zh-CN/swipe</a>

### 描述问题
官网的demo就能复现，vue3的swipe横向无法拖动到下一个

**Comment by Amy0714Angela** [comment]
请问找到问题原因了吗？我这儿也无法实现横向拖动，对比官网缺少mouse3个事件

**Comment by Amy0714Angela** [comment]
https://codesandbox.io/s/vant-issue-mo-ban-forked-48qvx?file=/src/App.vue

**Comment by Amy0714Angela** [comment]
重现链接
https://codesandbox.io/s/vant-issue-mo-ban-forked-48qvx?file=/src/App.vue

**Comment by Amy0714Angela** [comment]
找到原因了，使用pc端谷歌浏览器直接浏览器不起作用，![image](https://user-images.githubusercontent.com/27943611/139801452-ca8b478c-48d2-4f05-be16-48c7c19c87f7.png)
模拟手机设备后swipe是起作用的
