### ISSUE TITLE
[Feature Request] 如何在vant-cli创建出来的项目中，引入vant基础组件库？

### ISSUE THREAD

**Issue by dyh333** [youzan/vant#9315]
### 这个功能解决了什么问题
希望利用vant-cli来构建一套基于vant的“业务”组件库，即在vant基础上再封装一层业务相关的组件

### 描述您想要的解决方案
目前在vant.config.js中未发现入口，请给点提示

### 建议的API是什么样的
希望能提供部分参考代码

**Comment by chenjiahan** [comment]
直接 import Vant 组件就好，不需要什么配置

**Comment by dyh333** [comment]
![image](https://user-images.githubusercontent.com/1221313/132184390-07ee0ff4-3d98-4e42-8f46-f8929b64927b.png)
![image](https://user-images.githubusercontent.com/1221313/132184438-e8532f45-744f-4ac5-8660-eab5e549955c.png)

直接在组件中引入vant后 并不能正确识别出vant组件
@chenjiahan

**Comment by chenjiahan** [comment]
注册方式不对

https://vant-contrib.gitee.io/vant/#/zh-CN/advanced-usage#zu-jian-yong-fa

**Comment by dyh333** [comment]
谢谢大佬！

**Comment by Laumlin** [comment]
> 谢谢大佬！

我遇到了相同的问题，这三种写法都出现这种报错，请问您是怎么注册组件的呢？
![image](https://user-images.githubusercontent.com/31385709/143234056-453da168-5b72-411e-b14b-da9a0677b20c.png)
![image](https://user-images.githubusercontent.com/31385709/143234133-266824b8-0afd-4ed4-b4a6-7faeecc4f262.png)
![image](https://user-images.githubusercontent.com/31385709/143234237-d61e2f17-8003-414c-9f92-911187843b5c.png)
![image](https://user-images.githubusercontent.com/31385709/143234270-c78f42cd-6869-43f7-bf09-b3ef875914cd.png)

**Comment by dyh333** [comment]
@Laumlin

**Comment by dyh333** [comment]
![image](https://user-images.githubusercontent.com/1221313/143804910-c761a60d-8d99-43c0-a892-802e44275ea9.png)

**Comment by Laumlin** [comment]
我图片的第一种写法就是，还是报错
