### ISSUE TITLE
NavBar 导航栏 可以增加字体大小 颜色 选择吗？

### ISSUE THREAD

**Issue by Zhishuiii** [youzan/vant#9321]
NavBar 导航栏 可以增加字体大小 颜色 选择吗？

**Comment by chenjiahan** [comment]
直接用 https://vant-contrib.gitee.io/vant/v3/#/zh-CN/config-provider 组件进行主题定制即可

**Comment by Zhishuiii** [comment]
thank you

**Comment by Zhishuiii** [comment]
谢谢  我才发现vant出v3了

**Comment by Zhishuiii** [comment]
> 直接用 https://vant-contrib.gitee.io/vant/v3/#/zh-CN/config-provider 组件进行主题定制即可

谢谢 我才发现 vant出v3了
