### ISSUE TITLE
[Feature Request] Field组件添加validateFailed class定义

### ISSUE THREAD

**Issue by weiyuc** [youzan/vant#9324]
### 这个功能解决了什么问题
方便用户重写组件样式，如：
产品同学提了需求当校验错误时给field添加红色边框

### 描述您想要的解决方案
当Field组件校验错误时，添加'van-field_error' class定义

### 建议的API是什么样的
当Field组件校验错误时，添加'van-field_error' class定义

**Comment by chenjiahan** [comment]
可以滴，下个版本加上

**Comment by chenjiahan** [comment]
已在 3.2.2 版本支持
