### ISSUE TITLE
[Feature Request] van-tab的badge为0时隐藏badge

### ISSUE THREAD

**Issue by czl0325** [youzan/vant#9328]
### 这个功能解决了什么问题
当van-tab的badge>0的时候才显示，<=0的时候不显示出来

### 描述您想要的解决方案
<van-tab v-for="type in msgTypes" :key="type.typeId" :title="type.typeName" :badge="type.countMsg" :name="type.typeId"/>
badge不确定，是后端获取的，如果=0还是显示一个0的数字很奇怪，希望提供<=0的时候隐藏

### 建议的API是什么样的
可以在判断badge<=0的时候自动隐藏

**Comment by chenjiahan** [comment]
已在 3.2.2 版本支持 show-zero-badge 属性
