### ISSUE TITLE
[Bug Report] van-form中show-error属性默认值标示错误

### ISSUE THREAD

**Issue by XiaoHu-Producer** [youzan/vant#9332]
### 设备 / 浏览器
chrom

### Vant 版本
3.2.1

### Vue 版本
3.2.6

### 重现链接
<a href="https://gitee.com/uenHacker/press-mobile.git" target="_blank">https://gitee.com/uenHacker/press-mobile.git</a>

### 描述问题
在使用van-form标签的show-error属性时，发现Api中这个属性的默认值应该为 true 默认标红 而不是false

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/130763574-b5a3fc10-479f-400d-b8ed-72bc4f566f83.png)

从 3.0.6 版本开始，默认值为 false，目前来说更推荐通过 error message 进行提示，而不是把输入框标红
