### ISSUE TITLE
[Feature Request] 请为Icon图标库组件增加一个皇冠图标

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant#9345]
### 这个功能解决了什么问题
让vant自带图标库能支持更多场景

### 描述您想要的解决方案
请为Icon图标库组件增加一个皇冠图标

### 建议的API是什么样的
<van-icon name="crown-o" />
<van-icon name="crown" />

**Comment by chenjiahan** [comment]
暂无计划支持喔，可以按照文档使用自定义图标
