### ISSUE TITLE
[Feature Request] checkbox max=1即为单选模式，期待不要求先取消上一个选中的才能选中下一个值。

### ISSUE THREAD

**Issue by szuprefix** [youzan/vant#9350]
### 这个功能解决了什么问题
使用checkbox的max=1可以实现单选框功能，这有时很有用， 但现在不如意的地方是得先取消上一个选中的才能选中下一个值。 单选框不应有此限制。

### 描述您想要的解决方案
期望max=1的checkbox能像单选框那样操作顺畅不作限制。

### 建议的API是什么样的
建议参考 vux的checklist控件， 其很好的解决了此问题。

**Comment by chenjiahan** [comment]
单选请直接使用 Radio 组件
