### ISSUE TITLE
[Bug Report] Redmi某款手机对Field组件的适配

### ISSUE THREAD

**Issue by doYouHearPeopleSing** [youzan/vant#9351]
### 设备 / 浏览器
Redmi K20 pro

### Vant 版本
2.12.25

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-n8qdz?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-n8qdz?file=/src/App.vue</a>

### 描述问题
在使用<vant-field>的过程中,发现在 RedmiK20Pro手机上当内容过长,field高度固定时,可以自动发生滚动,但是不会显示显示滚动条

**Comment by chenjiahan** [comment]
请提供有效的重现链接
