### ISSUE TITLE
[Feature Request] Search组件input数据框设置type为search

### ISSUE THREAD

**Issue by CaicoLeung** [youzan/vant#9352]
### 这个功能解决了什么问题
Search聚焦后软键盘的回车键应该显示"Search"或"搜索"

### 描述您想要的解决方案
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input/search

### 建议的API是什么样的
优化用户体验

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/131329014-7fa049d0-a41f-4cf7-aba1-a187279adcad.png)

现在就是
