### ISSUE TITLE
[Bug Report] list卡死

### ISSUE THREAD

**Issue by xinghe94** [youzan/vant#9356]
### 设备 / 浏览器
chrome 版本 92.0.4515.159（正式版本） (x86_64)

### Vant 版本
3.1.0

### Vue 版本
3.2.0

### 重现链接
<a href="https://lightning.xiake.red/list" target="_blank">https://lightning.xiake.red/list</a>

### 描述问题
这个页面切换到Test视图就会卡死 页面是pullrefresh里包了一个list

**Comment by chenjiahan** [comment]
麻烦提供 codesandbox 复现链接喔，不然我们不好排查

https://codesandbox.io/s/m5v3f
