### ISSUE TITLE
[Feature Request] 可以给form表单加个可选的距离顶部scroll-to-error的滚动阈值吗？

### ISSUE THREAD

**Issue by wang0129** [youzan/vant#9357]
### 这个功能解决了什么问题
如果跟tab组件一起使用并且开启sticky布局的时候，tab头部是浮动的 那么校验不通过时滚动至错误的表单项时，tab头部会挡住一部分的输入框。

### 描述您想要的解决方案
可以通过api自定义滚动距离顶部的阈值。

### 建议的API是什么样的
设定一个可以通过px控制的api。

**Comment by zhaoyu69** [comment]
同样的期望，目前滚动位置到0，上面会有sticky元素挡住

**Comment by chenjiahan** [comment]
目前组件内部是通过 scrollIntoView API 实现的滚动，不太好实现这个功能，建议自行处理
