### ISSUE TITLE
[Bug Report] ios 按钮等操作元素，点击/触摸时效果无效

### ISSUE THREAD

**Issue by hwenjie** [youzan/vant#9360]
### 设备 / 浏览器
iphone

### Vant 版本
3.2.1

### Vue 版本
3.2.6

### 重现链接
<a href="https://github.com/youzan/vant/issues" target="_blank">https://github.com/youzan/vant/issues</a>

### 描述问题
css :active 伪类在ios上无效

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/3060
