### ISSUE TITLE
[Bug Report] 3.2.1的文档useRect代码错误

### ISSUE THREAD

**Issue by LoveofRedMoon** [youzan/vant#9366]
### 设备 / 浏览器
*.*

### Vant 版本
3.2.1

### Vue 版本
3.2.6

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/v3/#/zh-CN/use-rect" target="_blank">https://vant-contrib.gitee.io/vant/v3/#/zh-CN/use-rect</a>

### 描述问题
```ts
export default {
  setup() {
    const root = ref();
    /* -- */ const rect = useRect();
    /*    */ const rect = useRect(root);

    console.log(rect); // -> 元素的大小及其相对于视口的位置

    return { root };
  },
};
```

**Comment by chenjiahan** [comment]
感谢反馈，已修正文档
