### ISSUE TITLE
[Bug Report] Picker 选择器文档错误

### ISSUE THREAD

**Issue by nishuer** [youzan/vant#9367]
### 设备 / 浏览器
Chrome

### Vant 版本
3.2.1

### Vue 版本
3.2.6

### 重现链接
<a href="https://youzan.github.io/vant/v3/#/zh-CN/picker" target="_blank">https://youzan.github.io/vant/v3/#/zh-CN/picker</a>

### 描述问题
API表格区，参数“columns-field-names”的默认值，values应该改为value

**Comment by chenjiahan** [comment]
代码里就是 values，没问题

**Comment by nishuer** [comment]
values报错，value可以

**Comment by chenjiahan** [comment]
可以提供 codesandbox 复现链接看下

https://codesandbox.io/s/m5v3f
