### ISSUE TITLE
3.2.1版本List列表基本用例错误

### ISSUE THREAD

**Issue by crush12132** [youzan/vant#9368]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

List列表基本用例错误
原来的：
<van-list
  v-model:loading="loading"
  :finished="finished"
  finished-text="没有更多了"
  @load="onLoad"
>
改正后：
 <van-list
      v-model="loading"
      :finished="finished"
      finished-text="没有更多了"
      @load="onLoad"
    >

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
正确用法就是 v-model:loading，文档没有问题

**Comment by crush12132** [comment]
是这个吧


&nbsp;v-model="loading"，但文档那样子飘红欸： v-model:loading="loading"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant]3.2.1版本List列表基本用例错误 (#9368)





 
正确用法就是 v-model:loading，文档没有问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenjiahan** [comment]
请注意你的 vant 版本，vant2 为 v-model 没有 loading
