### ISSUE TITLE
[Bug Report] van-pick中show-toolbar与文档中描述不一致

### ISSUE THREAD

**Issue by waston123** [youzan/vant#9373]
### 设备 / 浏览器
chrome

### Vant 版本
3.2.1

### Vue 版本
3.2.6

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-c7nej?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-c7nej?file=/src/App.vue</a>

### 描述问题
van-pick中show-toolbar与文档中描述不一致
文档中描述默认为true,但是不设置show-toolbar 会默认不显示
把show-toolbar后才会显示

**Comment by chenjiahan** [comment]
请注意文档版本，vant 2 和 vant 3 的 api 略有不同，站点右上角可以切换文档版本
