### ISSUE TITLE
[Bug Report] van-uploader组件显示默认图片因为体积过大无法显示

### ISSUE THREAD

**Issue by lovehebe330** [youzan/vant#9374]
### 设备 / 浏览器
iphone

### Vant 版本
3.1.0-beta.0

### Vue 版本
3.2.4

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/v3/#/zh-CN/uploader" target="_blank">https://vant-contrib.gitee.io/vant/v3/#/zh-CN/uploader</a>

### 描述问题
van-uploader组件显示默认图片因为体积过大无法显示
使用v-model属性
![image](https://user-images.githubusercontent.com/20655248/131653013-47a3f7ea-d68b-4020-b214-7abe3e536e96.png)

![image](https://user-images.githubusercontent.com/20655248/131653040-da943188-1df9-414e-9de6-a51b57b01f52.png)
![image](https://user-images.githubusercontent.com/20655248/131653211-e71c8fa4-fe7b-4c1f-bd39-9020cf5f7af6.png)
![微信图片_20210901180924](https://user-images.githubusercontent.com/20655248/131653555-1a323428-e87f-499c-b1e6-f494a6cf2cf3.jpg)
发现在pc端图片默认显示正常的， 但在iphone手机端却无法显示图片，发现用官方的图片可以， 最后排查出好像是图片太大因此无法在手机上默认显示图片，请问这个要咋解决 800多kb的图片都无法在手机上默认显示 图片地址https://jzt1-oss.jztclub.com/1432244496682213378/202109/h5_msg.jpg

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/9375
