### ISSUE TITLE
[Bug Report] van-uploader组件显示默认图片因为体积过大无法显示

### ISSUE THREAD

**Issue by lovehebe330** [youzan/vant#9375]
### Vant 版本
3.1.0-beta.0

### Vue 版本
3.2.4

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/v3/#/zh-CN/uploader" target="_blank">https://vant-contrib.gitee.io/vant/v3/#/zh-CN/uploader</a>

### 描述问题
van-uploader组件显示默认图片因为体积过大无法显示
使用v-model属性
![image](https://user-images.githubusercontent.com/20655248/131653013-47a3f7ea-d68b-4020-b214-7abe3e536e96.png)
![image](https://user-images.githubusercontent.com/20655248/131654131-fc4ce80d-7531-45f4-a763-e7ff20451995.png)
![image](https://user-images.githubusercontent.com/20655248/131654254-d57f1af2-e88c-4d45-8577-e12aad549771.png)
![微信图片_20210901180924](https://user-images.githubusercontent.com/20655248/131653555-1a323428-e87f-499c-b1e6-f494a6cf2cf3.jpg)
发现在pc端图片默认显示正常的， 但在iphone6s手机端却无法显示图片，发现用官方的图片可以，（https://img.yzcdn.cn/vant/tree.jpg 这个图片好像30多kb） 最后排查出好像是图片太大因此无法在手机上默认显示图片，请问这个要咋解决 这个800多kb的图片都无法在手机上默认显示 图片地址（https://jzt1-oss.jztclub.com/1432244496682213378/202109/h5_msg.jpg）

发现上传一张10M的图片成功后也会存在图片没法现实的问题
![微信图片_20210903104404](https://user-images.githubusercontent.com/20655248/131942764-20d3c7e0-6d9e-40e7-859c-85dc0dd57d0c.jpg)

**Comment by chenjiahan** [comment]
旧手机的内存比较小，所以无法展示比较大的图片，可以通过压缩图片来试试

解决方法可以参考 https://vant-contrib.gitee.io/vant/#/zh-CN/uploader#pai-zhao-shang-chuan-de-tu-pian-bei-xuan-zhuan-90-du
