### ISSUE TITLE
[Bug Report] Calendar 日历 组件scrollToDate方法 没有反应

### ISSUE THREAD

**Issue by L5280999** [youzan/vant#9376]
### 设备 / 浏览器
Google

### Vant 版本
2.12.26

### Vue 版本
2.6.11

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/calendar" target="_blank">https://youzan.github.io/vant/#/zh-CN/calendar</a>

### 描述问题
没有任何反应

![image](https://user-images.githubusercontent.com/40187408/131767455-b7851cb5-2202-4f26-afa0-0045ee96f2b5.png)
![image](https://user-images.githubusercontent.com/40187408/131767422-271df596-8291-45a6-83ff-8b230e171a19.png)

![image](https://user-images.githubusercontent.com/40187408/131767428-19450f9e-b0b1-49eb-8fd7-2314b9f89834.png)

**Comment by chenjiahan** [comment]
请提供有效的 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
