### ISSUE TITLE
小米max3图片上传，无法触发 vant 2.12.24  vue:2.6.11

### ISSUE THREAD

**Issue by coderyufeng1994** [youzan/vant#9383]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by coderyufeng1994** [comment]
<van-uploader
                            :after-read="uploadOpenImg"
                            :before-delete="deleteOpenImg"
                            v-model="bizImgList"
                            :max-count="1"
                            :max-size="10 * 1024 * 1024"
                            accept="image/*"
                            @oversize="onOversize"
                        >
                            <img src="../../assets/store/biz-img.png" alt="" />
                        </van-uploader>

**Comment by coderyufeng1994** [comment]
<van-uploader
                            :after-read="uploadOpenImg"
                            :before-delete="deleteOpenImg"
                            v-model="bizImgList"
                            :max-count="1"
                            :max-size="10 * 1024 * 1024"
                            accept="image/*"
                            @oversize="onOversize"
                        >
                            <img src="../../assets/store/biz-img.png" alt="" />
                        </van-uploader>

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
