### ISSUE TITLE
[Bug Report] van-list组件。ios13.3无法触发下拉加载（14.2可以正常触发下拉刷新）

### ISSUE THREAD

**Issue by loca-spirit** [youzan/vant#9386]
### 设备 / 浏览器
Safari

### Vant 版本
3.2.2

### Vue 版本
3.1.5

### 重现链接
<a href="http://vant-contrib.gitee.io/vant-issue-generater/#/zh-CN" target="_blank">http://vant-contrib.gitee.io/vant-issue-generater/#/zh-CN</a>

### 描述问题
van-list组件。ios13.3无法触发下拉加载（14.2可以正常触发下拉刷新）
我们是飞书内置webview的浏览器，Safari的浏览器也不好使。目前看来是和操作系统有关系

**Comment by chenjiahan** [comment]
使用 Vant 官方示例能复现此问题吗？
