### ISSUE TITLE
 CouponList组件disabled-doupons参数无效

### ISSUE THREAD

**Issue by huixu123** [youzan/vant#939]
![0msotbhw 2_x 1or3ds5e0](https://user-images.githubusercontent.com/13418365/39236118-6773118c-48aa-11e8-823d-4a1ddc0cad7d.png)
![1 2](https://user-images.githubusercontent.com/13418365/39235904-d3cb719a-48a9-11e8-8176-fefcd624bfe8.png)
![idku p3nsd30 wdi a5yhzw](https://user-images.githubusercontent.com/13418365/39236017-23861b04-48aa-11e8-9229-84ecb2802654.png)

**Comment by jerryni** [comment]
disabled-doupons => disabled-coupons 拼写错误

**Comment by huixu123** [comment]
![image](https://user-images.githubusercontent.com/13418365/39237265-92947bdc-48ad-11e8-86c8-3cdb4ce8a1a9.png)
文档错了。。

**Comment by jerryni** [comment]
坑了。。。 那这个要改下了~

**Comment by chenjiahan** [comment]
已在 1.1.0 版本中修复
