### ISSUE TITLE
Vue2 var.less文件变量错误 @field-error-message-text-color: 12px;

### ISSUE THREAD

**Issue by gegenisang** [youzan/vant#9391]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by gegenisang** [comment]
@field-error-message-text-color: 12px;  更改为@field-error-message-text-font-size

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/9392
