### ISSUE TITLE
[Bug Report] vue2 var.less变量错误

### ISSUE THREAD

**Issue by gegenisang** [youzan/vant#9392]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.27-beta.0

### Vue 版本
2.6.1

### 重现链接
<a href="https://github.com/youzan/vant/blob/dev/src/style/var.less" target="_blank">https://github.com/youzan/vant/blob/dev/src/style/var.less</a>

### 描述问题
@field-error-message-text-color: 12px;  应该为 @field-error-message-text-font-size:12px

**Comment by chenjiahan** [comment]
这块确实是命名错误了，下个版本会修正

**Comment by chenjiahan** [comment]
已在 2.12.27 版本修复
