### ISSUE TITLE
[Bug Report] dialog弹框应用切后台再切回来消失

### ISSUE THREAD

**Issue by DongyaGe** [youzan/vant#9395]
### 设备 / 浏览器
安卓、IOS

### Vant 版本
2.5.9

### Vue 版本
2.6.11

### 重现链接
<a href="https://mas.zybank.com.cn:8443/mini/activitys/friendInvite/#/index?activeId=MAS_001836_20201213005941_001&nodeId=-4&channel=phone" target="_blank">https://mas.zybank.com.cn:8443/mini/activitys/friendInvite/#/index?activeId=MAS_001836_20201213005941_001&nodeId=-4&channel=phone</a>

### 描述问题
dialog弹框应用切后台再切回来消失，自己的APP和微信打开都是这种情况

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接喔，否则无法排查

https://codesandbox.io/s/m5v3f

另外可以把 Dialog 的 closeOnPopstate 选项设置为 false 试试

**Comment by DongyaGe** [comment]
> 请提供 codesandbox 复现链接喔，否则无法排查
> 
> https://codesandbox.io/s/m5v3f
> 
> 另外可以把 Dialog 的 closeOnPopstate 选项设置为 false 试试

这个属性试过了，不起作用（这个属性好像和切换页面有关系，这种切后台的没用）
