### ISSUE TITLE
swiper-item 加了页面跳转事件或者a 标签，swiper 组件中含 swipe-item 滑动时，会触发页面跳转，在ios 中会出现

### ISSUE THREAD

**Issue by livi12** [youzan/vant#940]
在index.js 中添加以下两行代码即可 
onTouchEnd: function onTouchEnd() {
      if (this.deltaX) {
        event.preventDefault();      //阻止默认事件
        event.stopPropagation();  // 阻止冒泡即可
        this.move(this.offsetX > 50 ? this.deltaX > 0 ? -1 : 1 : 0);
        this.currentDuration = this.duration;
      }
      this.autoPlay();
    },

**Comment by livi12** [comment]
忽略我吧 ，引用了 fastclick 引起的

**Comment by YanJunXie** [comment]
请问这两行代码在哪加啊，index.js是谁的js
