### ISSUE TITLE
[Bug Report] Vant3的ImagePreview组件在UC内核的浏览器上异常

### ISSUE THREAD

**Issue by JuliusNan** [youzan/vant#9400]
### 设备 / 浏览器
三星S9/夸克（UC内核）

### Vant 版本
3.2.2

### Vue 版本
3.0.0

### 重现链接
<a href="https://jhmr0.csb.app/" target="_blank">https://jhmr0.csb.app/</a>

### 描述问题
Vant3的ImagePreview组件在UC内核的浏览器上（夸克，支付宝内置浏览器等），有卡顿、图片不显示、无法循环滑动图片的问题。
当然，在同一个手机的谷歌浏览器上，是完全正常的。
要重现问题需要在UC内核的浏览器上打开重现链接。
Vant3的ImagePreview组件很棒，希望开发者能考虑这个组件能兼容UC内核的浏览器。

**Comment by JuliusNan** [comment]
重现链接源代码：https://codesandbox.io/s/vant-issue-mo-ban-forked-jhmr0

**Comment by chenjiahan** [comment]
我用 UC 浏览器（小米 11）试了下，没有遇到卡顿和无法循环滑动的问题喔。

至于图片不展示，我看有几张图片在 Chrome 上也是无法展示的，应该和组件没关系。

![image](https://user-images.githubusercontent.com/7237365/145713594-b991c7fc-8467-4137-b4a6-5965a4a58f08.png)

**Comment by chenjiahan** [comment]
夸克也试了下，滑动是正常的，没有卡顿现象。

如果是低端机卡顿的话，可能是图片太大了导致的，可以降低图片大小试试。
