### ISSUE TITLE
[Bug Report] configProvider渐变色无法显示

### ISSUE THREAD

**Issue by xingyucat** [youzan/vant#9401]
### 设备 / 浏览器
Chrome

### Vant 版本
3.2.2

### Vue 版本
3.2.8

### 重现链接
<a href="https://codepen.io/xing-yu/pen/xxrEEeg" target="_blank">https://codepen.io/xing-yu/pen/xxrEEeg</a>

### 描述问题
组件变量使用configProvider组件配置渐变色无法正常显示

**Comment by xingyucat** [comment]
把 `background-color` 改为 `background` 就可以了
`background: var(--van-button-primary-background-color);`

**Comment by chenjiahan** [comment]
已在 3.2.3 版本修复
