### ISSUE TITLE
[Bug Report] field 自定义 input 设置高度 内容将不会被显示 

### ISSUE THREAD

**Issue by wywsoor** [youzan/vant#9404]
### 设备 / 浏览器
pc

### Vant 版本
2.12.27-beta.0

### Vue 版本
3.2.9

### 重现链接
<a href="http://vant-contrib.gitee.io/vant-issue-generater/?repo=VantWeapp#/zh-CN" target="_blank">http://vant-contrib.gitee.io/vant-issue-generater/?repo=VantWeapp#/zh-CN</a>

### 描述问题
    <van-field required label='宣传时段' >
            <view slot='input' style="background:red;height: 100px;">
           123
            </view>
        </van-field>

**Comment by chenjiahan** [comment]
H5 上没有 view 标签。

如果是小程序问题，请到 vant-weapp 仓库下反馈。
