### ISSUE TITLE
请发一份这个实例的代码参考一下  https://youzan.github.io/vant/mobile#/en-US/

### ISSUE THREAD

**Issue by HachuneMiku** [youzan/vant#9405]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

https://youzan.github.io/vant/mobile#/en-US/
就是这个地址的代码，能否发一份参考，文档的代码不全

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/tree/dev/packages/vant-cli/site/mobile

以及每个组件目录下的 demo 目录
