### ISSUE TITLE
[Feature Request] 建议useRect根据入参改造为响应式

### ISSUE THREAD

**Issue by LoveofRedMoon** [youzan/vant#9407]
### 这个功能解决了什么问题
在大多数场景下, ref在setup阶段为null, 会导致在setup中基本无法使用useRect

### 描述您想要的解决方案
根据入参是否为Ref响应为不同的返回类型

### 建议的API是什么样的
```ts
function useRect(
  element: Element | Window
): DOMRect;
function useRect(
  element: Ref<Element | Window | undefined>
): Ref<DOMRect>
```

**Comment by chenjiahan** [comment]
这个改动属于 breaking change 了，因此暂时不考虑调整喔

可以使用 computed 封装一下
