### ISSUE TITLE
商品规格展示区添加标签

### ISSUE THREAD

**Issue by Amayjin** [youzan/vant#9408]
![image](https://user-images.githubusercontent.com/47651446/132310878-734daad7-0724-45d1-8769-c3837ba96400.png)
商品展示区怎么添加这种**热销**标签

**Comment by Sepush** [comment]
你可以使用  `<van-badge/>` 组件来实现这种效果。
具体的用法请参考链接里的 demo 代码。

https://github.com/youzan/vant/blob/dev/packages/vant/src/badge/demo/index.vue
