### ISSUE TITLE
Uploader组件chooseFile方法，移动端无效。

### ISSUE THREAD

**Issue by apgyapgy** [youzan/vant#9410]
**设备 / 浏览器**
移动端

**Vant 版本**
2.12.26

**Vue 版本**
2.6.11

**描述问题**
使用vant的uploader组件，我想实现的功能是组件外面有个按钮，点击这个按钮调用chooseFile方法，调起文件选择，在浏览器上使用是可以的，在移动端IOS手机和部分Android手机上失败，有没有人遇到过类似问题？

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/132483455-686e697e-28c9-4e6b-a53e-8f232c88822d.png)

一般来说，在点击 button 的 click 事件回调中同步执行，是可以唤起的

**Comment by apgyapgy** [comment]
我这属于在点击button的click事件回调中同步执行吗？
![image](https://user-images.githubusercontent.com/22905115/132484021-eb14e128-b16e-4a9b-96f1-a2d32fab7482.png)

**Comment by chenjiahan** [comment]
不算，nextTick 是异步方法

**Comment by xu-Aurora** [comment]
我也碰到你这个问题了，请问解决了嘛？android可以调取，但ios必要双击才可以调取，点击不能调取

**Comment by xu-Aurora** [comment]
我也碰到你这个问题了，请问解决了嘛？android可以调取，但ios必要双击才可以调取，单击不能调取

**Comment by zhou-tao** [comment]
> ![image](https://user-images.githubusercontent.com/7237365/132483455-686e697e-28c9-4e6b-a53e-8f232c88822d.png)
> 
> 一般来说，在点击 button 的 click 事件回调中同步执行，是可以唤起的

都没用的，直接使用button的click内调用chooseFile也不能触发。
