### ISSUE TITLE
[Feature Request] 使用vant-cli脚手架如何在build后生成.d.ts文件？

### ISSUE THREAD

**Issue by dyh333** [youzan/vant#9416]
### 这个功能解决了什么问题
使用vant-cli脚手架build后未在组件如demo-button看到.d.ts文件，请问下vant中是如何生成的？跟是否用tsx的写法无关吧？

### 描述您想要的解决方案
希望能给点提示

### 建议的API是什么样的
希望能给点提示

**Comment by chenjiahan** [comment]
已在 @vant/cli 4.0.0-rc.1 版本支持对 .vue 文件生成 .d.ts 类型定义
