### ISSUE TITLE
[Bug Report] van-field在使用input slot的时候无法校验自定义组件的value值

### ISSUE THREAD

**Issue by memory1668** [youzan/vant#9417]
### 设备 / 浏览器
Chrome

### Vant 版本
2.12.27

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/van-field-validate-pk2b2?file=/src/App.vue" target="_blank">https://codesandbox.io/s/van-field-validate-pk2b2?file=/src/App.vue</a>

### 描述问题
[文档](https://vant-contrib.gitee.io/vant/#/zh-CN/field )的描述是“在 Form 组件进行表单校验时，会使用 input 插槽中子组件的 value，而不是 Field 组件的 value。”，经过测试“子组件”只能是vant中的表单组件，子组件是自定义组件时没有使用自定义组件的value值进行校验。而且当自定义组件中使用了vant中的表单组件时, Form会直接使用该表单组件的value值进行校验。如重现链接所示，第三个表单项“爱好”，在只选中“打篮球”时校验通过，只选中”阅读“时校验却不通过，通过检查发现van-field组件用于校验的值formValue在只选中“打篮球”时为true, 只选中”阅读“时为false, 期待的值应该是自定义组件中的value值（数组）。所以请问是我对文档的理解有偏差呢还是van-form没法校验自定义组件的value值？

**Comment by chenjiahan** [comment]
Vant 2.x 的表单中只能使用 Vant 组件作为表单项

Vant 3.x 支持自定义表单项组件，参见 https://vant-contrib.gitee.io/vant/v3/#/zh-CN/use-custom-field-value

**Comment by EverChan6** [comment]
![image](https://github.com/youzan/vant/assets/20378229/962e8061-4a18-403f-b4a2-a6a017b84736)
hack一下，我在自定义组件里边加这行代码，加上了有v-model的vant组件，然后校验就可以使用了😂😶
