### ISSUE TITLE
[Bug Report] van-field组件在很多iphone手机中在微信中打开需要连续点击多次输入框才能聚焦

### ISSUE THREAD

**Issue by lovehebe330** [youzan/vant#9419]
### 设备 / 浏览器
iphone手机微信中

### Vant 版本
3.2.2

### Vue 版本
3.2.4

### 重现链接
<a href="https://h5.jurenmai.cn/jztAppH5/dist/index.html#/signin" target="_blank">https://h5.jurenmai.cn/jztAppH5/dist/index.html#/signin</a>

### 描述问题
使用van-field组件在iphonex手机微信中第一次页面载入时需要连续点击多次才能聚焦，在其它手机的浏览器中没问题，就只在iphone手机微信中第一次页面加载时需要连续点击多次才能聚焦，之后点击都没问题能马上聚焦，就第一次需要多次点击才能聚焦
代码如图
![image](https://user-images.githubusercontent.com/20655248/132467709-8183d67e-5e0e-4acf-a31f-19fd422c85b9.png)
![image](https://user-images.githubusercontent.com/20655248/132467863-68c6a267-bc8b-4716-8e8a-7442aecd8240.png)

**Comment by chenjiahan** [comment]
使用官方文档中的示例能否复现呢？

**Comment by Xyuan-abs** [comment]
"vant": "^2.12.26",
"vue": "^2.6.11",
在ios任何浏览器上都无法聚焦
