### ISSUE TITLE
slider 2个重大BUG。

### ISSUE THREAD

**Issue by shiyuegongsui** [youzan/vant#942]
1、slider， min设置负数会有问题
2、slider后面的dom无法渲染

       <div style="width:100%; padding:10px;">
            {{value}}
            <van-slider v-model="value" v-bind:min="-100" v-bind:max="100" />
         
            <div>我无法渲染了 {{value}}</div>
        </div>

**Comment by chenjiahan** [comment]
1. 百分比不支持负数
2. HTML 模板不能使用自闭和标签
