### ISSUE TITLE
vue2.x的项目使用了vant 开发模式想升级vite，如何解决vant一些组件requrie的问题？

### ISSUE THREAD

**Issue by CooLNuanfeng** [youzan/vant#9422]
在vue2.x的项目中使用了vant，在迁移成vite 使用esmodule模式时，vant中存在require问题，想请教下如何解决，试了几种方式 optimizeDeps，@rollup/plugin-commonjs 等没有解决

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
