### ISSUE TITLE
Coupon组件超过屏幕高度的时候不会出现滚动条

### ISSUE THREAD

**Issue by huixu123** [youzan/vant#943]
Coupon组件超过屏幕高度的时候不会出现滚动条,无法选择顶部的选项，.van-coupon-list__list 的max-height:100%似乎无效的样子
![2](https://user-images.githubusercontent.com/13418365/39281093-87db06c4-4935-11e8-93a5-2bb2ab66a30a.png)

![1 3](https://user-images.githubusercontent.com/13418365/39281009-126ac8c0-4935-11e8-940d-34f4e57b5f6b.png)
修改成固定的高度就正常
![6](https://user-images.githubusercontent.com/13418365/39281348-aa42cf20-4936-11e8-9f04-9876bf75fabc.png)

![44](https://user-images.githubusercontent.com/13418365/39281382-d6012350-4936-11e8-855b-99950c206d2c.png)

**Comment by chenjiahan** [comment]
需要设置 Popup 最大高度
