### ISSUE TITLE
[Bug Report] vue2.x的项目使用了vant 开发模式想升级vite，如何解决vant一些组件requrie的问题？

### ISSUE THREAD

**Issue by CooLNuanfeng** [youzan/vant#9431]
### 设备 / 浏览器
chorme

### Vant 版本
2.12.27

### Vue 版本
3.2.11

### 重现链接
<a href="https://github.com/youzan/vant/issues/9421" target="_blank">https://github.com/youzan/vant/issues/9421</a>

### 描述问题
在vue2.x的项目中使用了vant，在迁移成vite 使用esmodule模式时，vant中存在require问题，像van-image 组件等，想请教下如何解决，试了几种方式 optimizeDeps，@rollup/plugin-commonjs, cjs2esmVitePlugin 等没有解决

**Comment by chenjiahan** [comment]
van-image 组件并没有使用 require 呢，提供个复现仓库看看？

**Comment by liugangtaotie** [comment]
@CooLNuanfeng  可以查看这个demo解决方案：https://github.com/liugangtaotie/vite2-vue2-ts

1. 开发环境，秒级更新，vite2成功构建vue2；
2. 使用postcss-px-to-viewport 插件，实现响应式布局（任意屏幕适配）；
3. 根据vant2 自定义主题颜色；
4. 加入eslint、stylelint、prettier等插件，制定代码统一规范。

**Comment by CooLNuanfeng** [comment]
> van-image 组件并没有使用 require 呢，提供个复现仓库看看？

目前无法提供复现仓库，就是配置好vite后运行  使用vant的一些组件 浏览器会报require not undefined 之类的报错

**Comment by CooLNuanfeng** [comment]
> @CooLNuanfeng 可以查看这个demo解决方案：https://github.com/liugangtaotie/vite2-vue2-ts
> 
> 1. 开发环境，秒级更新，vite2成功构建vue2；
> 2. 使用postcss-px-to-viewport 插件，实现响应式布局（任意屏幕适配）；
> 3. 根据vant2 自定义主题颜色；
> 4. 加入eslint、stylelint、prettier等插件，制定代码统一规范。

thanks
