### ISSUE TITLE
[Bug Report] vant uploader组件在IOS上打开相册不受应用权限限制。（比如应用没有开启相册权限，但是uploader一样能打开相册

### ISSUE THREAD

**Issue by ltm4545** [youzan/vant#9433]
### 设备 / 浏览器
Iphone12/ipad 

### Vant 版本
2.12.27

### Vue 版本
3.2.11

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/v3/#/zh-CN/uploader" target="_blank">https://vant-contrib.gitee.io/vant/v3/#/zh-CN/uploader</a>

### 描述问题
vant uploader组件在IOS上打开相册不受应用权限限制。（比如应用没有开启相册权限，但是uploader一样能打开相册。 重现步骤：在微信，飞书，钉钉上打开https://vant-contrib.gitee.io/vant/v3/#/zh-CN/uploader，点击上传，在应用没有授权相册权限的情况下，能直接打开相册。 在安卓上无此问题

**Comment by chenjiahan** [comment]
Uploader 使用了 HTML 原生的 input file 标签，这个行为不是 Vant 内部控制的，是系统和浏览器决定的
