### ISSUE TITLE
[Bug Report] swipe点击跳转到新页面再返回后autoplay停止工作

### ISSUE THREAD

**Issue by jackjtr** [youzan/vant#9436]
### 设备 / 浏览器
Chrome 92

### Vant 版本
3.1.1

### Vue 版本
3.1.2

### 重现链接
<a href="https://codesandbox.io/s/vant3-swipe-cgo2w" target="_blank">https://codesandbox.io/s/vant3-swipe-cgo2w</a>

### 描述问题
点击某个轮播跳转到新页面，然后返回，autoplay不会自动生效，但只要手指触发移动一点点距离就会继续自动播放

可能需要设计一个方法重新激活autoplay相关事件

注：本地代码放到CodeSandbox上无法运行

**Comment by chenjiahan** [comment]
已在 3.2.3 版本修复
