### ISSUE TITLE
Stepper 步进器可以输入小数

### ISSUE THREAD

**Issue by ollieSk8** [youzan/vant#944]
Stepper 步进器 可以输入小数比如1.23
能不能加个属性控制小数点的位数，或者输入的时候可以指定是整数或者小数

**Comment by ollieSk8** [comment]
因为购物车场景选择数量的时候，用户输入了小数，但业务上商品数量不可以是小数，所以组件能否加个输入整数或者小数的选项？

**Comment by chenjiahan** [comment]
感谢反馈，后续会支持只输入整数

**Comment by chenjiahan** [comment]
已在 1.1.2 版本增加 integer 属性
