### ISSUE TITLE
请问 toast 在 webview 中 关闭后 出现 小黑点 怎么解决

### ISSUE THREAD

**Issue by JokerPawn** [youzan/vant#9441]
手机和电脑浏览器中正常，在app的webview中toast消失后会出现小黑点

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by zoujinglong666** [comment]
请问 toast 在 webview 中 点击之后就会一直显示 不会自己关闭 有遇到这个问题吗
