### ISSUE TITLE
[Bug Report] van-goods-action-icon点击事件失效

### ISSUE THREAD

**Issue by wangh1998** [youzan/vant#9447]
### 设备 / 浏览器
IOS 系统15版本

### Vant 版本
2.12.26

### Vue 版本
2.6.11

### 重现链接
<a href="https://devtest.chunyutianxia.com/v-m-mall/product/T-6010215?from=%E5%A6%87%E7%A7%91" target="_blank">https://devtest.chunyutianxia.com/v-m-mall/product/T-6010215?from=%E5%A6%87%E7%A7%91</a>

### 描述问题
登录 15931879827 111111
复现步骤：该链接点击下方购物车图标按钮 -> 跳转路由->返回时注意：手势滑动返回
预期：再点击购物车图标按钮，可跳转
实际：第一次不可跳转，第二次可跳转

备注：如果使用物理返回键返回，不会出现该问题

**Comment by chenjiahan** [comment]
从现象来看，是浏览器本身的 bug，不是组件的问题喔，组件里也只是使用了原生的 click 事件。

如果是 iOS 15 的话，目前还处于 beta 状态，有 bug 是正常的，可以等 apple 修复。
