### ISSUE TITLE
[Feature Request] CSS variable for to change `font-size` in uploader delete icon

### ISSUE THREAD

**Issue by adarshmadrecha** [youzan/vant#9449]
### What problem does this feature solve
Ability to fine tune the appearance of `uploader-delete-icon` for `Uploader` component. https://vant-contrib.gitee.io/vant/v3/#/en-US/uploader

### Describe the solution you'd like
For `Uploader` https://vant-contrib.gitee.io/vant/v3/#/en-US/uploader
Add CSS variable for to change `font-size` in `.van-uploader__preview-delete-icon` class.

### What does the proposed API look like
When I use the `–van-uploader-delete-icon-size` CSS variable to increase the clickable area, the cross `x` remain small.

### More details / Explanations 
The desired UI 
![image](https://user-images.githubusercontent.com/11911938/132869274-9005b824-26cb-4a97-9e3d-1f8ebf655b60.png)

The default UI
![image](https://user-images.githubusercontent.com/11911938/132869497-36e8c846-4d0a-4a01-9b8a-2e610d0def38.png)

UI when I set the `–van-uploader-delete-icon-size` css variable to `30px`
![image](https://user-images.githubusercontent.com/11911938/132869802-63ef0dc5-3d61-4834-8abf-2febc9d7c203.png)

As you can see, the problem is just by setting the icon size, the desired effect is not achieved. The reason for this is the cross is controlled by `.van-uploader__preview-delete-icon` class. and it has `font-size: 16px`.
![image](https://user-images.githubusercontent.com/11911938/132870349-0684fc30-1cb3-434a-9891-285ae30deef9.png)

**Comment by chenjiahan** [comment]
Fixed in v3.2.3
