### ISSUE TITLE
[Bug Report] button type="success" 无样式

### ISSUE THREAD

**Issue by toxicantcc** [youzan/vant#9457]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.27

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/toxicantcc/vant_issue_demo/blob/main/demo.vue" target="_blank">https://github.com/toxicantcc/vant_issue_demo/blob/main/demo.vue</a>

### 描述问题
van-button type 为success时，样式是灰色的，和文档不一致，麻烦看一下

**Comment by chenjiahan** [comment]
Vant 2 的 Button 没有 success 类型，Vant 3 有，请注意区分文档版本
