### ISSUE TITLE
[Bug Report] Overlay组件的lock-scroll不生效

### ISSUE THREAD

**Issue by zengjie911** [youzan/vant#9461]
### 设备 / 浏览器
chrome

### Vant 版本
3.2.2

### Vue 版本
3.2.11

### 重现链接
<a href="https://jsbin.com/soreroxiwe/edit?html,output" target="_blank">https://jsbin.com/soreroxiwe/edit?html,output</a>

### 描述问题
使用overlay组件时，看文档lock-scroll参数是默认true，锁定背景滚动，但实际并无效果，看别的反馈组件也有lock-scroll参数默认true，是给body加上了名为van-overflow-hidden的class，overlay组件没有，官网文档的例子也是无效的

**Comment by chenjiahan** [comment]
Overlay 组件会禁用自身的 touchmove 事件来阻止页面滚动。

你是在 PC 端使用的吗？ PC 端确实可能出现此问题

**Comment by zengjie911** [comment]
> Overlay 组件会禁用自身的 touchmove 事件来阻止页面滚动。
> 
> 你是在 PC 端使用的吗？ PC 端确实可能出现此问题

是pc上，我在手机上试了，确实和pc不一样，谢谢，那就没问题了
