### ISSUE TITLE
[Bug Report] 在Radio组件 default slot 使用 van-dropdown-menu, 在 van-dropdown-menu的点击事件里切换路由报错

### ISSUE THREAD

**Issue by sevenbluecity** [youzan/vant#9462]
### 设备 / 浏览器
chrome: 93.0.4577.63

### Vant 版本
2.12.22

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-zo71j" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-zo71j</a>

### 描述问题
radio组件 default slot 使用 van-dropdown-menu，在 van-dropdown-menu的点击事件里切换路由报错，已提供重现链接。重现步骤：在重现链接里点击展开下拉菜单，在下拉菜单里点击最下方的manage按钮。

**Comment by chenjiahan** [comment]
已在 2.12.28 版本修复
