### ISSUE TITLE
[Bug Report] 引入@vant/touch-emulator，但tab组件仍不能监听mouseenter事件

### ISSUE THREAD

**Issue by dzih526** [youzan/vant#9463]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.27

### Vue 版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-xg9ch?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-xg9ch?file=/src/App.vue</a>

### 描述问题
引入@vant/touch-emulator，但tab组件仍不能监听mouseenter事件，添加了native也是如此

**Comment by sevenbluecity** [comment]
![image](https://user-images.githubusercontent.com/45512700/133060728-824c0439-0d48-4a73-95bb-2877c333ca47.png)
你好像没导入   import '@vant/touch-emulator';
试了一下导入之后，再加 native 可以触发

**Comment by dzih526** [comment]
> ![image](https://user-images.githubusercontent.com/45512700/133060728-824c0439-0d48-4a73-95bb-2877c333ca47.png)
> 你好像没导入 import '@vant/touch-emulator';
> 试了一下导入之后，再加 native 可以触发

嗯，手动导入是可以的；
但我修改了一下，使用了v-for，绑定了title和name，让demo更贴近实际业务，重现了这个问题
https://codesandbox.io/s/vant-issue-mo-ban-forked-xg9ch?file=/src/App.vue

**Comment by chenjiahan** [comment]
@vant/touch-emulator 并没有提供 mouseenter 事件的模拟，也没有计划提供喔。
