### ISSUE TITLE
[Bug Report] vue-cli创建项目，使用van-tabbar报错

### ISSUE THREAD

**Issue by Tanglan123** [youzan/vant#9472]
### 设备 / 浏览器
谷歌浏览器

### Vant 版本
2.12.27

### Vue 版本
2.6.1

### 重现链接
<a href="http://localhost:8080/index" target="_blank">http://localhost:8080/index</a>

### 描述问题
vue-cli创建项目，vant引入，初始化后，使用van-tabbar，报错：
Error in render: "TypeError: Cannot read property 'route' of null"
found in

---> <VanTabbarItem>
       <Tabbar> at src/components/tabbar.vue
         <App> at src/App.vue
           <Root>

**Comment by chenjiahan** [comment]
无效的重现链接，请提供有效链接
