### ISSUE TITLE
[Feature Request] tabs sticky粘性布局 吸顶可否支持距离设置？

### ISSUE THREAD

**Issue by yanghuanrong** [youzan/vant#9473]
### 这个功能解决了什么问题
在移动端会存在自己编写的header 吸顶不设置距离。会把header覆盖住

### 描述您想要的解决方案
希望可以设置 offset-top

### 建议的API是什么样的
通van-sticky组件一样的  offset-top

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/133236573-49494776-0d4e-444d-9ec5-09095a7f5793.png)
