### ISSUE TITLE
[Bug Report] tabs 滚动导航通过scrollTo方法设置tab位置，tabs导航菜单选中有误

### ISSUE THREAD

**Issue by Gyang18** [youzan/vant#9474]
### 设备 / 浏览器
chrome

### Vant 版本
3.2.2

### Vue 版本
3.2.6

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-0rh35?file=/src/views/home.vue" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-0rh35?file=/src/views/home.vue</a>

### 描述问题
有A、B 两个页面，在B页面中使用tab滚动导航。

问题一：

当我从A页面跳过到B
页面时，进行类似锚点的操作后，tab导航栏无法正确的选中对应的tab菜单（如果选中的是tabs中最后的一个tab），会自动选中到上一个tab菜单，但scrollTo方法跳转的位置并没有问题，
也尝试过resize方法，此问题还是存在

问题二：

当我进入B页面后，已经滚动到指定位置后，此时刷新页面，滚动导航出现异常。

注：我的复现环境是chrome浏览器中的device模式下，或手机上通过浏览器访问均有此问题。

复现代码已在codesandbox中编写，但由于模拟器原因，好像无法正确执行相关逻辑

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/134480590-c5b7ef38-d071-4d54-9a52-afe50b5539af.png)

这两个问题我都没有复现喔，使用的是 Chrome 的 device 模式和 codesandbox 中的复现代码。
