### ISSUE TITLE
[Feature Request] 可以给遮罩层里的动作面板和picker选择器的选项加一个isActive的属性吗？当选中那个的时候给他置为红色字体？

### ISSUE THREAD

**Issue by qi25045** [youzan/vant#9475]
### 这个功能解决了什么问题
解决了用户每次打开遮罩层，遮罩层里面的动作面板和picker选择器显示了用户已选的内容选项，这样用户每次打开都知道自己之前选了什么！优化体验！

### 描述您想要的解决方案
可不可以加一个isActive属性，当变量为true的时候可以为激活状态，且可以自定义激活的文字颜色

### 建议的API是什么样的
给动作面板加一个currentActive属性，他可以自己去遍历选项，当currentActive等于选项里的值的时候，就把该选项置为红色，告知用户上次选了什么！

**Comment by chenjiahan** [comment]
暂无计划支持呢，可以自行实现该逻辑，ActionSheet 有提供 color 选项来设置颜色
