### ISSUE TITLE
[Bug Report] ImagePreview放大后不能滑动切换图片

### ISSUE THREAD

**Issue by wangh1998** [youzan/vant#9482]
### 设备 / 浏览器
移动端

### Vant 版本
2.12.26

### Vue 版本
2.6.11

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/image-preview" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/image-preview</a>

### 描述问题
ImagePreview放大后不能滑动切换图片

**Comment by chenjiahan** [comment]
暂不支持放大后切换喔
