### ISSUE TITLE
[Bug Report] 红米k30手机上传文件组件点击后无法拍照, 且不能正常从图库中上传图片

### ISSUE THREAD

**Issue by sixsixsix516** [youzan/vant#9484]
### 设备 / 浏览器
红米k30

### Vant 版本
2.8.2

### Vue 版本
2.5.22

### 重现链接
<a href="https://github.com/youzan/vant/issues?q=k30" target="_blank">https://github.com/youzan/vant/issues?q=k30</a>

### 描述问题
上传组件无法正常使用
红米k30手机上传文件组件点击后无法拍照, 且不能正常从图库中上传图片

**Comment by chenjiahan** [comment]
是在浏览器中，还是在 App 的 WebView 中呢？

**Comment by chenjiahan** [comment]
Uploader 采用了 HTML 原生的 `<input type="file />` 标签进行上传，能否上传取决于当前系统和浏览器的兼容性。当遇到无法上传的问题时，一般有以下几种情况：

1. 遇到了安卓 App WebView 的兼容性问题，需要在安卓原生代码中进行兼容，可以参考此[文章](https://blog.csdn.net/qq_32756581/article/details/112861088)。
2. 图片格式不正确，在当前系统/浏览器中无法识别，比如 `webp` 或 `heic` 格式。
3. 其他浏览器兼容性问题。

**Comment by sixsixsix516** [comment]
> Uploader 采用了 HTML 原生的 `<input type="file />` 标签进行上传，能否上传取决于当前系统和浏览器的兼容性。当遇到无法上传的问题时，一般有以下几种情况：
> 
> 1. 遇到了安卓 App WebView 的兼容性问题，需要在安卓原生代码中进行兼容，可以参考此[文章](https://blog.csdn.net/qq_32756581/article/details/112861088)。
> 2. 图片格式不正确，在当前系统/浏览器中无法识别，比如 `webp` 或 `heic` 格式。
> 3. 其他浏览器兼容性问题。



使用的是webapp模式!!!

**Comment by chenjiahan** [comment]
可以试一下原生的 `<input type="file />` 是否有相同问题？
