### ISSUE TITLE
[Bug Report] Toast在computed加if/else返回时调用会报错

### ISSUE THREAD

**Issue by wensc1996** [youzan/vant#9487]
### 设备 / 浏览器
Chrome

### Vant 版本
3.2.3

### Vue 版本
3.2.11

### 重现链接
<a href="https://codesandbox.io/s/vant3-computed-toast-m1viz?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant3-computed-toast-m1viz?file=/src/App.vue</a>

### 描述问题
Toast在computed加if/else且return时调用Toast会报错"el is undefined"

**Comment by chenjiahan** [comment]
看起来是 Vue 内部的错误，不太像是组件本身的逻辑问题

**Comment by wensc1996** [comment]
> 看起来是 Vue 内部的错误，不太像是组件本身的逻辑问题

    const name = computed(() => {
      if (x.value == 0) {
        return "张三";
      } else {
        nextTick(() => {
          Toast("你好");
        });
        return "李四";
      }
    });

估计是computed有更新机制，但是创建Toast尚未完成，el为null，通知el更新就报错了

**Comment by wensc1996** [comment]
> 看起来是 Vue 内部的错误，不太像是组件本身的逻辑问题

我又看了看是不是getCurrentInstance的问题
https://codesandbox.io/embed/vant3-computed-toast-forked-t9re8?fontsize=14&hidenavigation=1&theme=dark

**Comment by chenjiahan** [comment]
组件层面暂无处理方式，先 close 了
