### ISSUE TITLE
[Bug Report] Calendar 日历 移动端不能手指滚动

### ISSUE THREAD

**Issue by L5280999** [youzan/vant#9488]
### 设备 / 浏览器
Chrome/移动端

### Vant 版本
2.12.27

### Vue 版本
2.5.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-ipveh" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-ipveh</a>

### 描述问题
Calendar 日历 移动端不能手指滚动  只能鼠标滑轮滚动

**Comment by chenjiahan** [comment]
未复现此问题，建议看下是不是项目中其他因素导致的
