### ISSUE TITLE
与vw适配不兼容

### ISSUE THREAD

**Issue by shi995548347** [youzan/vant#949]
使用大漠的vw方案适配，默认单位宽高都失效，目前只支持rem适配嘛

**Comment by chenjiahan** [comment]
具体不兼容的地方是？

**Comment by shi995548347** [comment]
默认宽高样式没有了

**Comment by BreezeDealer** [comment]
好像确实有这个问题，转成vw后高度变得异常矮。

**Comment by alanoy** [comment]
postcss-px-to-viewport 设置不编译 'van'

**Comment by Tyrone2333** [comment]
postcss-px-to-viewport 设置 `  selectorBlackList: [/van-\w+/,/base-\w+/] ` 把van-的样式都过滤掉就可以了

**Comment by nongzhenli** [comment]
我不明白过滤后，意义何在！过滤后，px单位没有转成vw，那么适配的意义就没有了哇

**Comment by Tyrone2333** [comment]
> 我不明白过滤后，意义何在！过滤后，px单位没有转成vw，那么适配的意义就没有了哇

vw 适配的是你自己的代码,vant 的样式一直是正常的

**Comment by nongzhenli** [comment]
> > 我不明白过滤后，意义何在！过滤后，px单位没有转成vw，那么适配的意义就没有了哇
> 
> vw 适配的是你自己的代码,vant 的样式一直是正常的

是的，我现在是使用 postcss-px-to-viewport 对所有px 都进行了 vw转换！假设如果我使用了vant  组件 button，如果不对vant ui  button 的样式也转成vw的话，会不会不够优雅呀。就是在适配上。

不过其实我现在遇到个问题，vant 的样式已经全部转成vw了，但是假如我按照750的设计稿的话，vant 的单位长度并没有扩展成2倍的基数....

**Comment by CookyG** [comment]
cube那边使用postcss-design-convert 解决的
我这边尝试了下 也可以解决适配
