### ISSUE TITLE
[Bug Report] Cascader 级联选择 bug

### ISSUE THREAD

**Issue by JaneII** [youzan/vant#9494]
### 设备 / 浏览器
钉钉

### Vant 版本
3.2.3

### Vue 版本
3.1.5

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/v3/#/zh-CN/cascader" target="_blank">https://vant-contrib.gitee.io/vant/v3/#/zh-CN/cascader</a>

### 描述问题
我们的项目用到了cascader级联，在钉钉里打开，经过操作后点击级联tab会有错误。用官网的链接去测试也同样有这个问题。我录了个在钉钉里复现bug视频，上传git上了，https://github.com/JaneII/vant-cascader-bug.git

**Comment by chenjiahan** [comment]
从这个表现看，应该是响应式数据更新不正确，怀疑是框架层的兼容问题

**Comment by chenjiahan** [comment]
组件层面暂无处理方式，先 close 了

**Comment by Wenguanming** [comment]
这个问题半年后也没有解决呐

**Comment by y1324** [comment]
这bug，可真离谱
