### ISSUE TITLE
[Feature Request] imagePreview支持跟随手势设置图片缩放原点

### ISSUE THREAD

**Issue by ghost** [youzan/vant#9500]
### 这个功能解决了什么问题
现在都是以图片中心为原点缩放，支持跟随手势中心为原点缩放图片

### 描述您想要的解决方案
组件内部解决   外部传布尔值选择

### 建议的API是什么样的
布尔值   默认true为图片中心  false为跟随手势

**Comment by Alanscut** [comment]
@ghost
“跟随手势中心为原点”，是指双指操作时两个手指的中心吗？

**Comment by nideajun** [comment]
我在这里借个位置，顺便说一下backtop这个功能在nuxt3里开启 keepalive时，会重复插入这个功能代码，造成重影，不用keepalive时就正常。

**Comment by chenjiahan** [comment]
@nideajun 有问题建议新开一个 issue 呢
