### ISSUE TITLE
[Feature Request] ActionSheet从其他方向弹出

### ISSUE THREAD

**Issue by zhangrunhao** [youzan/vant#9502]
这个功能解决了什么问题
解决了ActionSheet从其他方向弹出的需求

描述您想要的解决方案
新增api, 支持从其他方向弹出

建议的API是什么样的
<van-action-sheet v-model:show="show" :actions="actions" @select="onSelect" direction="left" />

**Comment by chenjiahan** [comment]
从 UI 规范上来说，不会有从其他方向弹出的 ActionSheet。

如果有这方面的需求，可以通过 Popup 组件自行实现
