### ISSUE TITLE
[Bug Report] Vant 3.2.2 Dialog组件多语言渲染问题

### ISSUE THREAD

**Issue by JacksMaster** [youzan/vant#9507]
### 设备 / 浏览器
Chrome 95

### Vant 版本
3.2.3

### Vue 版本
3.2.12

### 描述问题
我这边对多语言文件做了模块化 ，页面显示没有问题 vant除dialog组件外其他渲染都没有问题 ，目前发现dialog渲染不出来
![image](https://user-images.githubusercontent.com/85353476/133869251-4695d726-0ba3-487a-867e-13a4084d5be6.png)

**Comment by JacksMaster** [comment]
![image](https://user-images.githubusercontent.com/85353476/133869243-e9d157a1-bff3-4ec6-8472-e78faafdb2ba.png)

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
