### ISSUE TITLE
[Bug Report]van-button组件使用问题, 传入内容变成了undefined

### ISSUE THREAD

**Issue by sunjianfengHub** [youzan/vant#9508]
遇到了非常奇怪奇幻的问题。
![image](https://user-images.githubusercontent.com/52647113/133869709-54d6149c-d979-4e56-a353-d5e4f4c1dad3.png)

![image](https://user-images.githubusercontent.com/52647113/133869718-493c9646-0bf6-4e9e-a0cf-b0458c179b3b.png)

![image](https://user-images.githubusercontent.com/52647113/133869731-e8ef161a-a418-4fc2-8799-5fb5806a5b0c.png)

![image](https://user-images.githubusercontent.com/52647113/133869734-65246acb-e0d5-4cd8-a884-59924262eba1.png)

node V : 10 +
yarn V 1.22
vant V ^2.12.27
vue V ^2.6.11
typescript V 4+

**Comment by chenjiahan** [comment]
从图片上未看出问题，可以提供一个复现链接看下

**Comment by bird0113** [comment]
我也遇到了这个问题，而且所有用到vant icon都会报错，请问你后来怎么解决的
