### ISSUE TITLE
cellGroup和Cell组合使用异常

### ISSUE THREAD

**Issue by Unskillful-panda** [youzan/vant#9509]
环境：
谷歌浏览器
vant版本：https://cdn.jsdelivr.net/npm/vant@2.12/lib/vant.min.js
vue版本：https://cdn.jsdelivr.net/npm/vue@2.6/dist/vue.min.js
样式版本：https://cdn.jsdelivr.net/npm/vant@2.12/lib/index.css

**理想效果**
CellGroup下有多个Cell理应和官网文档效果一致

**异常效果**
使用cdn版本 多个Cell只显示了一个

js bin地址演示： https://jsbin.com/cefomaz/2/edit?html,css,output

希望官方尽快解决

**Comment by toesbieya** [comment]
`/>` -> `</van-cell>`

**Comment by chenjiahan** [comment]
https://vant-contrib.gitee.io/vant/#/zh-CN/quickstart#zai-html-zhong-wu-fa-zheng-que-xuan-ran-zu-jian
