### ISSUE TITLE
[Bug Report] [bug feature]使用setup script语法时，Dialog组件异常。

### ISSUE THREAD

**Issue by Qishierhao** [youzan/vant#9510]
### 设备 / 浏览器
PC/Chrome

### Vant 版本
3.1.5

### Vue 版本
3.2.6

### 重现链接
<a href="https://gitee.com/jiangboenoch/test.git" target="_blank">https://gitee.com/jiangboenoch/test.git</a>

### 描述问题
[bug] 使用setup script语法时，import组件Dialog自动注册。当直接使用<Dialog>时，vue发出警告，使用异常。
[feature] 希望官网能增加setup script的引入|使用方法

![image](https://user-images.githubusercontent.com/43943555/133879484-57104880-351a-41e4-8ca4-85f027f05af8.png)

**Comment by chenjiahan** [comment]
已补充文档，可以参考 https://github.com/youzan/vant/pull/9517/files
