### ISSUE TITLE
[Bug Report] Field在Iphone上无法输入，连续点击键盘还会失去焦点

### ISSUE THREAD

**Issue by xjcjackin** [youzan/vant#9511]
### 设备 / 浏览器
Iphone

### Vant 版本
3.2.3

### Vue 版本
3.2.12

### 重现链接
<a href="https://youzan.github.io/vant/v3/#/zh-CN/field" target="_blank">https://youzan.github.io/vant/v3/#/zh-CN/field</a>

### 描述问题
Field在Iphone上无法输入，发生在拥有自定义右侧按钮（按钮的文案是动态变化的，例如“59秒后可再次发送”，不断倒计时）的情况下。
失去焦点是在上述状态下，获取Field焦点，连续点击按键即可失去焦点

**Comment by chenjiahan** [comment]
请提供有效的 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
