### ISSUE TITLE
[Bug Report] 华为nova6SE和荣耀30pro的Upload组件有问题

### ISSUE THREAD

**Issue by linjiadashaoye** [youzan/vant#9513]
### 设备 / 浏览器
华为nova6SE和荣耀30pro

### Vant 版本
2.12.27

### Vue 版本
2.6.1

### 重现链接
<a href="https://yuejueng.zheliju.cn" target="_blank">https://yuejueng.zheliju.cn</a>

### 描述问题
拍照之后选择确认，uploader组件的aftereade和beforeread都不执行，其他机型上没有问题。因为是政务服务所以暂不重现链接。

**Comment by chenjiahan** [comment]
Uploader 采用了 HTML 原生的 `<input type="file />` 标签进行上传，能否上传取决于当前系统和浏览器的兼容性。当遇到无法上传的问题时，一般有以下几种情况：

1. 遇到了安卓 App WebView 的兼容性问题，需要在安卓原生代码中进行兼容，可以参考此[文章](https://blog.csdn.net/qq_32756581/article/details/112861088)。
2. 图片格式不正确，在当前系统/浏览器中无法识别，比如 `webp` 或 `heic` 格式。
3. 其他浏览器兼容性问题。

**Comment by lzc991016** [comment]
解决了吗
