### ISSUE TITLE
[Bug Report] Toast.loading 自定义类名的样式被覆盖

### ISSUE THREAD

**Issue by JessieChen5** [youzan/vant#9514]
### 设备 / 浏览器
chrome

### Vant 版本
3.2.3

### Vue 版本
3.2.12

### 重现链接
<a href="http://www.baidu.com" target="_blank">http://www.baidu.com</a>

### 描述问题
//axios.js里面
// service.interceptors.request.use(
//   config => {
//     if (!config.hideloading) { 
      Toast.loading({
        duration: 10000,
        className: 'public-loading-color',   //.public-loading-color {background-color: red}  自定义样式被覆盖了
        forbidClick: true
  //     })
  //   }
  // })

**Comment by chenjiahan** [comment]
请提供有效的 codesandbox 复现链接

https://codesandbox.io/s/m5v3f
