### ISSUE TITLE
在表单中的输入框输入值失焦时会自动消失

### ISSUE THREAD

**Issue by xinhaojie** [youzan/vant#9515]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater
你好，我是vue新手在用咱们的框架做一个demo。但是在创建表单的时候发现一个问题。如下代码
![image](https://user-images.githubusercontent.com/19681117/133884280-6a76fa2c-4de9-4acd-95c8-15360a6d5bdc.png)
以上这段代码是用了setup函数中的一个对象变量绑定了表单中的所有项。但是在使用的时候在所有的框内输入值后点击其他框原来输入的框里面的内容就会消失。但是经过打印发现输入的值已经赋值给了变量。另一种情况见下图。
![image](https://user-images.githubusercontent.com/19681117/133884339-f5178a50-1e79-4b23-ba1b-c728b436aa01.png)
上图中，不使用对象，只用一个变量绑定一个输入框的情况下就是正常的。我想问一下是为什么，是我代码哪里有问题。还是这个地方不能使用对象进行绑定

**Comment by chenjiahan** [comment]
Vue 中响应式数据需要通过 reactive 或 ref 定义，不了解的话可以先多看看 Vue 官方文档
