### ISSUE TITLE
[Feature Request] tabbar不能在路由为子路由的时候高亮

### ISSUE THREAD

**Issue by HIKALU-Z** [youzan/vant#9516]
### 这个功能解决了什么问题
当路由有嵌套时
例如tabbar的to指定为/data,但是此路由下有两个子路由需要展示
/data/micro
/data/macro
此时，tabbar在对应的子路由下不会高亮

### 描述您想要的解决方案
能在路由为子路由时高亮tabbar

### 建议的API是什么样的
可以增加一个activeInChild，或者判断active的时候不用相等而是包含关系

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant/issues/9173
