### ISSUE TITLE
[Bug Report] 输入框输入数字之后失焦后消失

### ISSUE THREAD

**Issue by xinhaojie** [youzan/vant#9518]
### 设备 / 浏览器
chrome90

### Vant 版本
3.2.3

### Vue 版本
3.2.12

### 重现链接
<a href="http://www.baidu.com" target="_blank">http://www.baidu.com</a>

### 描述问题
<script>
	import {
		ref
	} from 'vue';
	import {
		Toast
	} from 'vant';

	export default {
		name: "Baodan",
		setup() {
			const checked = ref('1');
			const from_data = {
				type: 2,
				zfb: "",
				wx: '',
				pd: '',
				danhao: '',
				remask: ''
			};

			function r_click(n) {
				console.log("dianjile"   n)
				from_data.type = n
				console.log(from_data.type)
			};

			function onSubmit() {
				console.log(from_data.danhao, from_data.zfb, from_data.type, from_data.remask);
				var msg = "报单类型："   from_data.type   "\n"  
					"支付宝账号："   from_data.zfb   "\n";
				Toast.success(msg);
			};

			function losejiaodian() {
				console.log(from_data.zfb)
			};

			function getjiaodian() {
				console.log(from_data.zfb)
			};
			return {
				checked,
				from_data,
				r_click,
				onSubmit,
				losejiaodian,
				getjiaodian,
			};
		}
	};
</script>
以上为出错的代码，我在视图里面绑定 from_data  这个对象里面的元素。在页面输入之后输入框失焦的时候输入的内容会消失。但是我加了打印，发现对象的属性值已经改变成我输入的内容了。如果我绑定的不是对象的属性，而是定义的一个变量就不会消失。代码如下：
<script>
	import { ref } from 'vue';
	export default{
		setup(){
			const digit = ref('');
			return {
				digit
			}
		},
		data(){
			return {
				tel:''
			}
		}
	}
</script>
这段代码里我用输入框绑定digit输入内容后失焦就不会消失。

我想问一下是我不能用对象的属性绑定视图的值么？？？？？还是框架有BUG

**Comment by chenjiahan** [comment]
这个 issue 中已经回答过了，请勿重复创建

https://github.com/youzan/vant/issues/9515
