### ISSUE TITLE
[Feature Request] Search组件可以把autocomplete属性加上

### ISSUE THREAD

**Issue by san-wi** [youzan/vant#9546]
### 需求

`Search` 组件增加 `autocomplete` 属性

https://github.com/youzan/vant/blob/70eec20d25098e86a768983a94658d56ee0ab21c/packages/vant/src/field/Field.tsx#L111

https://github.com/youzan/vant/blob/70eec20d25098e86a768983a94658d56ee0ab21c/packages/vant/src/search/Search.tsx#L24

### 问题

`Search` 组件直接使用 `autocomplete` 属性ts验证不通过，DOM上也会在组件父级增加属性

![image](https://user-images.githubusercontent.com/73974709/134445274-c8f4faa1-339f-45c8-9b15-f808da55c371.png)

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
已在 3.2.4 版本支持
