### ISSUE TITLE
[Bug Report] 文档错误，van-number-keyboard缺少theme="custom"

### ISSUE THREAD

**Issue by cn1001wang** [youzan/vant#9549]
### 设备 / 浏览器
any

### Vant 版本
2.12.29

### Vue 版本
2.6.11

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/number-keyboard#pei-zhi-duo-ge-an-jian" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/number-keyboard#pei-zhi-duo-ge-an-jian</a>

### 描述问题
V2版本文档中<van-number-keyboard “配置多个按键” 示例缺少theme="custom"

**Comment by chenjiahan** [comment]
感谢反馈，文档已修正
