### ISSUE TITLE
你好，我打算用这个也淘宝的flexible，做适配，vue项目，但是这个应该怎么适配呢

### ISSUE THREAD

**Issue by GreatHonour** [youzan/vant#955]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
参见 https://www.youzanyun.com/zanui/vant#/zh-CN/quickstart

**Comment by VenusPP** [comment]
可以把其样式copy 改写为rem
