### ISSUE TITLE
[Feature Request] 倒计时组件CountDown传入millisecond为false时启用setTimeout进行计算

### ISSUE THREAD

**Issue by hxj9102** [youzan/vant#9564]
### 这个功能解决了什么问题
这个功能解决了js无效的计算问题。

### 描述您想要的解决方案
当传入的millisecond为false时，将macroTick函数requestAnimationFrame计算改为setTimeout计算。
当millisecond为false时，虽然原来的计算方式可以1s渲染一次，但js代码却每16ms执行一次，如果页面中有很多定时器，势必会造成队列任务过长而引发的性能问题。
当millisecond为false时，使用setTimeout可以减少无谓的计算，从而提高性能。

### 建议的API是什么样的
当传入的millisecond为false时，macroTick函数用setTimeout替代requestAnimationFrame计算。

**Comment by chenjiahan** [comment]
目前 requestAnimationFrame 中的计算量还好吧？ 而且使用 setTimeout 的话会导致时间显示有误差，比如 setTimeout 1000，就相当于每秒才计算一次，可能会出现跳秒的情况
