### ISSUE TITLE
[Bug Report]  Uncaught TypeError: Cannot read properties of null (reading 'width')

### ISSUE THREAD

**Issue by FengWanMin** [youzan/vant#9566]
### 设备 / 浏览器
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

### Vant 版本
2.12.24

### Vue 版本
2.6.11

### 重现链接
<a href="https://github.com/FengWanMin/issues-demo-code/blob/main/vant-swipe-issues" target="_blank">https://github.com/FengWanMin/issues-demo-code/blob/main/vant-swipe-issues</a>

### 描述问题
1、demo上，直接渲染Swipe组件，会报错Uncaught TypeError: Cannot read properties of null (reading 'width')。
2、按照文档，使用resize，需要延迟近5s才能达到正常预期。

业务的初衷：展示对应的轮播，没有所谓的切换展示轮播，所以并需要要v-show\v-if切换

**Comment by chenjiahan** [comment]
在将 v-if 设置为 true 以后，还需要等待一个 nextTick 的时间才能获取到正确的 DOM，这个是 Vue 的渲染机制。

从 demo 中，没看出来你为什么需要调用 resize 方法，直接 v-if 就行。
