### ISSUE TITLE
[Feature Request] 为什么折叠板点击面板就可以进行缩放，为什么不是点击箭头才进行缩放。

### ISSUE THREAD

**Issue by su-zhenghui** [youzan/vant#9567]
### 这个功能解决了什么问题
这个功能我觉得让折叠面板凝固了不够灵活了。

### 描述您想要的解决方案
我希望是只点击箭头才有缩放的功能，点击面板其他没有。或者弄一个兼容的，可以选择点击面板任何一处都有反应，也可以选择只点击箭头才有反应。

### 建议的API是什么样的
抱歉，没有具体的API。

**Comment by chenjiahan** [comment]
这个是交互规范喔，暂无计划调整。
