### ISSUE TITLE
Vite打包时 Popover actions类型不正确

### ISSUE THREAD

**Issue by hongliang-Lu** [youzan/vant#9568]
node_modules/vant/lib/popover/Popover.d.ts:11:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

[key: PropertyKey]: any

移除就好了。。请审查一下

**Comment by chenjiahan** [comment]
升级一下项目中的 typescript 版本即可

**Comment by shaonianzhentan** [comment]
我升级到了最新版本，并没有解决这个问题
![image](https://user-images.githubusercontent.com/5294022/142808894-c0403cfc-d24c-4f5c-b2ec-d53f6260faab.png)
![image](https://user-images.githubusercontent.com/5294022/142808958-7b06e3e8-c269-4be3-808d-69e38effa765.png)

**Comment by shaonianzhentan** [comment]
`vue-tsc` 升级到最新版，解决了这个问题

**Comment by hongliang-Lu** [comment]
收到，感谢



---原始邮件---
发件人: "Monkey • D • ***@***.***&gt;
发送时间: 2021年11月22日(周一) 下午2:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [youzan/vant] Vite打包时 Popover actions类型不正确 (#9568)




 
vue-tsc 升级到最新版，解决了这个问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
