### ISSUE TITLE
[Feature Request] 本地图片等资源处理太麻烦

### ISSUE THREAD

**Issue by MiSheep** [youzan/vant#9573]
### 这个功能解决了什么问题
vite+vue3，无webpack，发现src/assets下的本地图片无法加载，查文档发现无法直接src=xxxx，需要require转换。使用后报错`Uncaught (in promise) ReferenceError: require is not defined`，想起用的不是webpack，到处找vite怎么解决。。。
就不能和普通<img>等一样提供简单一点的方式嘛。。

### 描述您想要的解决方案
和普通<img>等一样提供简单一点的引入方式

### 建议的API是什么样的
如上

**Comment by chenjiahan** [comment]
这个和组件库没有关系喔，建议自行寻找解决方案
