### ISSUE TITLE
[Bug Report] vant-cli初始化项目后，项目无法启动

### ISSUE THREAD

**Issue by rainydayDY** [youzan/vant#9578]
### 设备 / 浏览器
chrome

### Vant 版本
3.2.4

### Vue 版本
3.2.19

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/icon" target="_blank">https://youzan.github.io/vant/#/zh-CN/icon</a>

### 描述问题
首先链接是乱填的。
我要描述的问题是vant-cli，yarn dev执行后✖ ｢wdm｣: ERROR in ./docs/home.md 2:0
Module parse failed: Unexpected token (2:0)
File was processed with these loaders:
 * ./node_modules/vue-loader/dist/index.js
 * ./node_modules/@vant/markdown-loader/src/index.js
You may need an additional loader to handle the result of these loaders.
就报错了

**Comment by Bald-mans** [comment]
请问你的问题解决了吗

**Comment by chenjiahan** [comment]
看了一下，是 vue-loader >= 16.6.0 的 bug，vant-cli 依赖的 vue-loader 的版本已经降低到 16.5.0，可以升级 @vant/cli 到 3.11.4 版本来解决。

```bash
yarn add @vant/cli@3.11.4
```
