### ISSUE TITLE
[Bug Report] Toast.clear() 同步调用不能关闭

### ISSUE THREAD

**Issue by TzcTzcTzc** [youzan/vant#9583]
Toast.loading({
      message: "加载中...",
      forbidClick: false,
      loadingType: "spinner",
      duration: 0,
    });
    Toast.clear();

版本：3.2.4

**Comment by TzcTzcTzc** [comment]
谢谢啦！

**Comment by chenjiahan** [comment]
已在 3.2.5 版本修复
