### ISSUE TITLE
[Bug Report] picker组件如何修改选中项的背景颜色

### ISSUE THREAD

**Issue by Reeyc** [youzan/vant#9587]
### 设备 / 浏览器
chrome

### Vant 版本
3.2.4

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-bdo73?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-bdo73?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675</a>

### 描述问题
修改.van-picker__frame会直接覆盖.van-picker-column__item的样式，因为它是absolute的。
修改.van-picker-column__item--selected在滚动的时候总会有一点延迟的效果。

**Comment by chenjiahan** [comment]
目前是推荐使用 `.van-picker-column__item--selected` 进行修改，有延迟是因为惯性滚动的动画导致的，暂无计划提供其他方式喔。

**Comment by Reeyc** [comment]
@chenjiahan 将来有打算出一个Props来设置吗，毕竟这样的UI需求还是蛮常见的

**Comment by rurushakiki** [comment]
我找到了一个可以解决的办法，但是在色值上需要ui配合一下。

给van-picker__frame的背景色加透明度，如：background: rgba(0,0,0,0.1);

<img width="354" alt="Image" src="https://github.com/user-attachments/assets/3fd5bf7c-a31c-40c2-8ab7-3be9b9562dee" />
