### ISSUE TITLE
List 选项卡切换后 无法加载

### ISSUE THREAD

**Issue by shiyuegongsui** [youzan/vant#959]
https://jsfiddle.net/dfarLdko/79/

**Comment by shiyuegongsui** [comment]
点击 点击切换到PostList  无法发起请求

**Comment by shiyuegongsui** [comment]
能否帮忙看下这个问题

**Comment by chenjiahan** [comment]
1. data 应为函数
2. template 拼写错误
3. 这是 Vue 的 Bug，简单来说，vue 将两个 template 中的 List 视为同一个组件，导致 List 的生命周期函数只触发了一次，建议去 Vue 仓库下提 issue

**Comment by shiyuegongsui** [comment]
如果 要做选项卡 要如何 操作呢
