### ISSUE TITLE
github文档打开有时候非常慢，可不可以在gitee上放一份。

### ISSUE THREAD

**Issue by webSongNO1** [youzan/vant#9594]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by chenjiahan** [comment]
https://vant-contrib.gitee.io/vant/#/zh-CN/
