### ISSUE TITLE
关于组件事件的设计思路

### ISSUE THREAD

**Issue by HannibalKcc** [youzan/vant#960]
**What is the current behavior?**
目前CellSwipe（还有部分其他）组件的事件调用行为是父组件传一个callback进去，而不是子组件emit一个事件出来。

**What is the expected behavior?**
CellSwipe组件emit出onClose 事件到父级。
我目前见到的大部分UI组件库都是emit事件出来，而不是传cb进去。
就像标签语义化很重要一样，指令的语义化也相当有必要，除非这样有什么非常好的优点而我没有发现（如果是，望指教~）

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**
--vant1.0.4

**Comment by chenjiahan** [comment]
CellSwipe 的 api 设计有点问题，以后会优化

**Comment by deepkolos** [comment]
通过这种方式嵌入的组件就似乎不能用$emit
```js
var Tpl = Vue.extend('xxx.vue');
var vm = new Tpl ({
   el: document.createElement('div')
}); 

this.$refs.box.appendChild(vm.$el)
```

**Comment by chenjiahan** [comment]
更正一下，CellSwipe 是故意设计成传入 onClose 而不是 emit 事件的。因为 CellSwipe 有两种行为，不传入 onClose 时，点击特定区域自动关闭 Swipe。传入 onClose 时，可以异步控制 Swipe 的关闭行为。用 emit 无法做到这点

**Comment by HannibalKcc** [comment]
这并不困难。

只需要简单的$emit('onChange', {position, instance: this})交给父组件去决定同步异步关闭就可以了。

决定权在你手上，目前CellSwipe的cb依旧能让组件看起来运作良好。但是使用它可能并没有让人感到那么习惯。

通过$emit的设计成为常见的行为不是没有道理的。

比如：父组件的handleEmit可以增加更多的参数
```
<van-cell-swipe
            :right-width="1 * baseRem"
            @comClick="handleSwipeDel(index, $event)">
    <div slot="right" class="btnDel fs30">删除</div>
</van-cell-swipe>
```

**Comment by whosa** [comment]
我也觉得这样的设计有问题，最主要的是跟别的组件逻辑不一致，用的时候习惯性的@on-closse() ，结果发现不行，才注意到这是个回调而不是个事件。 至于说的onClose有两种行为的问题，我觉得多加一个prop：{auto Close：Boolean}就行了，相比之下，我还是觉得保持api的一致性更重要。
