### ISSUE TITLE
vant-cli自动创建项目报错

### ISSUE THREAD

**Issue by Bald-mans** [youzan/vant#9623]
https://youzan.github.io/vant-issue-generater

问题如图所示，使用yarn create vant-cli-app命令创建的vue3项目在dev执行后显示空白页面，并报错3个error，都是这种.md文件的问题
![屏幕截图 2021-10-02 152402](https://user-images.githubusercontent.com/57175015/135707622-37c04488-51f2-43b4-b35a-6e3915be4568.png)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/9578
