### ISSUE TITLE
[Bug Report] 3.2.4版本使用vite编译后样式出错

### ISSUE THREAD

**Issue by kyour-cn** [youzan/vant#9628]
### 设备 / 浏览器
Edge,微信

### Vant 版本
3.2.4

### Vue 版本
3.2.11

### 重现链接
<a href="http://localhost:3000/#/find/stem" target="_blank">http://localhost:3000/#/find/stem</a>

### 描述问题
在使用3.2.4版本时编译后，Tabbar将不在底部悬浮，还有大量其他样式异常出现，但是切换回3.2.3就一切正常，使用的是vite2.5.3

**Comment by chenjiahan** [comment]
请提供有效的复现链接或复现仓库喔
