### ISSUE TITLE
list 组件快速划到底部 多次加载 有点问题吧？

### ISSUE THREAD

**Issue by taylor-swift-1989** [youzan/vant#963]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
能否提供一个复现问题的 jsfiddle?

**Comment by taylor-swift-1989** [comment]
data () {
    return {
       	isBotflag:true,
    }
  }, 

 if (reachBottom&&this.isBotflag) {
      	this.isBotflag=false;
        this.$emit('input', true);
        this.$emit('load');       	
        setTimeout(()=>{
        	 this.isBotflag=true;  
       },380)
      }
不好意思 ， 算不上bug ，个人加了个开关  已解决

**Comment by taylor-swift-1989** [comment]
个人已解决，加个thtottle时间开关了。已经，另外，list加载中，还在加载中，快速点击跳转页面，上一个的页面的请求还持续，发现 this.$nextTick(this.onScroll);  这边导致。也额外加了个开关。其他吧，现在的官网demo，我的ios uc ，红米5a  UC   滚动加载到底不，加载中 的提示文案 看不到，不兼容。

**Comment by chenjiahan** [comment]
看不懂。
