### ISSUE TITLE
[Bug Report] useCustomFieldValue自定义表单项不生效

### ISSUE THREAD

**Issue by zbjy** [youzan/vant#9639]
### 设备 / 浏览器
Google Chrome  78.0.3904.70

### Vant 版本
3.2.4

### Vue 版本
3.0.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-e94sb" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-e94sb</a>

### 描述问题
useCustomFieldValue自定义表单项，没有将自定义组件的值回传到field组件中，导致表单校验的时候不生效

**Comment by chenjiahan** [comment]
在目前的版本中全量引入 Vant 会有这个问题，原因是全量引入时单独打包了一份 @vant/use，导致代码中存在两份 @vant/use。

这个问题会在 3.2.5 版本修复，或者可以先改成按需引入组件来避免此问题。
