### ISSUE TITLE
vant-upload 上传不成功，而且各种报错，且找不到报错原因

### ISSUE THREAD

**Issue by danchaotaiyang** [youzan/vant#9643]
chunk-vendors.js:29188 [Vue warn]: Invalid handler for event "load": got undefined

found in

<VanImage>
       <VanUploader>
         <VanField>
           <VanForm>

chunk-vendors.js:29188 [Vue warn]: Invalid handler for event "error": got undefined

found in

<VanImage>
       <VanUploader>
         <VanField>
           <VanForm>

**Comment by xieyu376** [comment]
请问后来解决了吗，我这边也一样的问题。。感觉是van-image在uni-app里不适配的问题造成的

**Comment by 1817889821** [comment]
![image](https://user-images.githubusercontent.com/85100667/217996581-243d6cf8-82b6-449e-b0a2-43423cb3548b.png)

**Comment by 1817889821** [comment]
> ![image](https://user-images.githubusercontent.com/85100667/217996581-243d6cf8-82b6-449e-b0a2-43423cb3548b.png)

![image](https://user-images.githubusercontent.com/85100667/218009965-90402640-6223-4035-979f-805e9bf6e727.png)

**Comment by 1817889821** [comment]
> > ![image](https://user-images.githubusercontent.com/85100667/217996581-243d6cf8-82b6-449e-b0a2-43423cb3548b.png)
> 
> ![image](https://user-images.githubusercontent.com/85100667/218009965-90402640-6223-4035-979f-805e9bf6e727.png)

![image](https://user-images.githubusercontent.com/85100667/218010057-aeb7967e-57a3-4aca-8a68-d26dcb19bb10.png)
