### ISSUE TITLE
Vant的说明文档总是被墙

### ISSUE THREAD

**Issue by wltj920** [youzan/vant#9649]
## 你没看错，就是这个域名**vant-contrib.gitee.io**被墙，建议有赞考虑一下更换别的域名。已测试过3大运营商的宽带都是，但神奇的是用电信4G网络就可以访问。

经测试是由于DNS将域名解析到了`127.0.0.1`，而且是所有DNS都这样，怀疑是比运营商更高级的部门进行了封堵。

![image](https://user-images.githubusercontent.com/10513736/136665321-d5aed168-974e-462b-a560-df72232161a0.png)

请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater

如果遇到了用法上的问题或想法，建议在 [Discussions 讨论区](https://github.com/youzan/vant/discussions) 发帖进行讨论。

**Comment by wltj920** [comment]
一样的有问题，最后我用了`https://vant-contrib.oschina.io/vant/v3/#/zh-CN`解决了

**Comment by chenjiahan** [comment]
了解👌 可以先用这个域名过渡下
