### ISSUE TITLE
vant 3.2.5版本按需引入

### ISSUE THREAD

**Issue by peiaobo** [youzan/vant#9655]
3.2.5内按需引入Popover体积直接飙升到180k左右，3.2.0按需引入则没有这个问题

**Comment by chenjiahan** [comment]
未复现此问题：

![image](https://user-images.githubusercontent.com/7237365/136779623-dbb3381e-7caa-4d40-ba3c-08b9fbb96fef.png)

可以提供复现问题的最小仓库链接看看。
