### ISSUE TITLE
[Bug Report] @vant/cli没有锁定vite版本号

### ISSUE THREAD

**Issue by ChpShy** [youzan/vant#9670]
在vite版本好升级至2.6.7时，yarn dev不会输出服务的url信息。

**Comment by chenjiahan** [comment]
这个问题已经在 @vant/cli@4.0.0-rc.0 版本修复了，参见 https://github.com/youzan/vant/pull/9667

**Comment by ChpShy** [comment]
@chenjiahan 收到，我试试
