### ISSUE TITLE
[Feature Request] 建议可否新增下拉筛选菜单组件

### ISSUE THREAD

**Issue by miaovictor** [youzan/vant#968]
建议增加如下的下拉筛选菜单组件
![qq20180501-0](https://user-images.githubusercontent.com/5133301/39477455-f6946104-4d91-11e8-8030-95463496a0bb.PNG)
![qq20180501-1](https://user-images.githubusercontent.com/5133301/39477458-f7dfd96c-4d91-11e8-9765-0c530722fd68.PNG)
![qq20180501-2](https://user-images.githubusercontent.com/5133301/39477461-f9f31368-4d91-11e8-8ec9-7bcbcec92155.PNG)

**Comment by chenjiahan** [comment]
会在后续版本支持

**Comment by Ttou** [comment]
期待

**Comment by VancySavoki** [comment]
这个功能一直想要，临时用Cell+Popup(top)代替的

**Comment by kbgyf** [comment]
什么时候能加入啊 大佬

**Comment by Chasers9527** [comment]
同求

**Comment by Chasers9527** [comment]
@VancySavoki 3Q 可以先按照你所想的试试

**Comment by ChiJohn** [comment]
> 这个功能一直想要，临时用Cell+Popup(top)代替的
怎样设置弹出的初始位置

**Comment by ChiJohn** [comment]
> 这个功能一直想要，临时用Cell+Popup(top)代替的

@VancySavoki 您好，请教下你Popup(top)弹出的初始位置怎样设置？

**Comment by chenjiahan** [comment]
会在 2.0 版本支持该组件

**Comment by webzhouyan** [comment]
同求

**Comment by misshu** [comment]
同求

**Comment by chenjiahan** [comment]
已在 2.0.0-beta.0 版本支持
