### ISSUE TITLE
[Bug Report] @vant/cli@4.0.0-rc.0的build:site的bug

### ISSUE THREAD

**Issue by ChpShy** [youzan/vant#9685]
### 设备 / 浏览器
谷歌

### Vant 版本
3.2.5

### Vue 版本
3.2.20

### 重现链接
<a href="https://codesandbox.io/s/m5v3f?file=/src/main.js" target="_blank">https://codesandbox.io/s/m5v3f?file=/src/main.js</a>

### 描述问题
问题： build:site生成的组件预览页面没有demo里面写的样式

复现：
1.将dev分支的vant拷贝出去
2. yarn
3. yarn build:site
4. 部署

结果如下：

https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/7221b3951a7d460f85934be90bf57974~tplv-k3u1fbpfcp-watermark.image

**Comment by chenjiahan** [comment]
看了下确实是少了 css 文件，没看出原因，不知道是不是 vite 的 bug，要不升级 @vant/cli 4.0.0-rc.1 试试？

**Comment by chenjiahan** [comment]
此问题无法复现，先 close 咯
