### ISSUE TITLE
[Feature Request] [vant-cli] 代码复制功能

### ISSUE THREAD

**Issue by TinsFox** [youzan/vant#9692]
### 这个功能解决了什么问题
提高使用者的体验

### 描述您想要的解决方案
在代码块增加代码复制按钮/提示之类的，点击之后可以一键复制当前代码块的所有代码到剪切版

### 建议的API是什么样的
在cli中暴露代码复制功能配置

**Comment by xiaohp** [comment]
![image](https://user-images.githubusercontent.com/23056320/143732724-086b1a53-475a-4026-9e26-7b9ce22c4dc9.png)
类似 antd 这里的复制，如果有 `在 CodeSandbox 中打开` 更好
