### ISSUE TITLE
[Bug Report] Dialog 弹出框

### ISSUE THREAD

**Issue by zenlinuxs** [youzan/vant#9695]
### 设备 / 浏览器
Android和iOS

### Vant 版本
2.12.30

### Vue 版本
3.2.20

### 重现链接
<a href="https://github.com/youzan/vant/issues/new" target="_blank">https://github.com/youzan/vant/issues/new</a>

### 描述问题
1.弹出窗口后是方形的然后过一秒变为长方形的。Dialog 弹出框 文字长的情况下。在加载中和加载时完成弹窗清空。具体比较难复现。就一两个地方存在，毕竟全局使用的。重现地址怎么死必填？能给你反馈问题就谢天谢地了。

**Comment by chenjiahan** [comment]
无法重现的的问题会被 close，感谢配合。
