### ISSUE TITLE
[Bug Report] Field 输入框 设置成 textarea，clearable，自适应高度问题

### ISSUE THREAD

**Issue by wuzaofeng** [youzan/vant#9715]
### 设备 / 浏览器
Chrome

### Vant 版本
2.12.30

### Vue 版本
2.6.14

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-gx4hc?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-gx4hc?file=/src/App.vue</a>

### 描述问题
Field 输入框 设置成 textarea, clearable, autosize，输入内容刚好一行时，由于触发焦点会添加删除icon, 两个事件的计算高度不一致的情况。

foucs 焦点事件和blur 失去焦点事件应重新计算高度,

**Comment by chenjiahan** [comment]
已在 2.12.31 版本修复
