### ISSUE TITLE
tab标签页，滑动切换 怎么监听滑动切换的事件 ， 比如滑动到了第几个模块， 有没有相应的事件？

### ISSUE THREAD

**Issue by soulToken** [youzan/vant#973]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

**Comment by chenjiahan** [comment]
watch `v-model` 绑定的变量即可
