### ISSUE TITLE
[Bug Report] [Bug Report] DateTimePicker，选择的时间与得到的时间不一致

### ISSUE THREAD

**Issue by lxt1994** [youzan/vant#9733]
### 设备 / 浏览器
Chrome

### Vant 版本
2.12.30

### Vue 版本
2.6.1

### 重现链接
<a href="https://jsbin.com/jejoworafe/edit?html,js,console,output" target="_blank">https://jsbin.com/jejoworafe/edit?html,js,console,output</a>

### 描述问题
首先定义最小时间为2021/09/26，这时候先选择一个日期，比如2021/10/01，这时候得到的日为01，再选择9月，直接点确定，得到的日依旧为01

**Comment by chenjiahan** [comment]
有一个相同的反馈，统一在这个 issue 中跟进哈：https://github.com/youzan/vant/issues/9775

**Comment by lxt1994** [comment]
好的，感谢
