### ISSUE TITLE
[Bug Report] vue中使用vant-ui的popup>picker组件在ios中出现底部弹出层高度丢失问题

### ISSUE THREAD

**Issue by zhujianxiong** [youzan/vant#9735]
### 设备 / 浏览器
iPhone12

### Vant 版本
2.12.29

### Vue 版本
2.6.1

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/popup#events" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/popup#events</a>

### 描述问题
<div>
      <van-popup v-model="showPicker" position="bottom" :style="{height:'40%'}" get-container="myTicket">
        <div class="myTicket">
          <van-picker
            title="请选择保存方式"
            show-toolbar
            :columns="columns[columnType]"
            @confirm="onConfirm"
            @cancel="onCancel"
          />
        </div>
      </van-popup>
    </div>

在iOS设备上iphone12真机测试下无法生效，无论get-container的值是什么，都一样

**Comment by zhujianxiong** [comment]
> 请提供有效的 codesandbox 复现链接
> 
> https://codesandbox.io/s/m5v3f
[
](https://codesandbox.io/s/vant-issue-mo-ban-forked-k7v6k?file=/src/App.vue)

**Comment by zhujianxiong** [comment]
https://codesandbox.io/s/vant-issue-mo-ban-forked-k7v6k?file=/src/App.vue

**Comment by zhujianxiong** [comment]
![image](https://user-images.githubusercontent.com/45658422/142125587-9ba0baa5-21a7-4fe3-9fa2-e0c4430fe84b.png)

**Comment by chenjiahan** [comment]
使用你提供的复现链接，在 iOS 下未复现该问题。

从截图来看，是 Picker 选项的高度不正确，建议你看下是否是由于 rem 或 vh 等配置引起的，或者由其他自定义样式导致。
