### ISSUE TITLE
Vant 2.12.30版本的Locale 与最新的Vue2.6.14版本起冲突

### ISSUE THREAD

**Issue by wfymalong** [youzan/vant#9748]
设备 / 浏览器

Chrome
Vant 版本

**2.12.30**
Vue 版本

**2.6.14**
重现链接
暂无
描述问题
在这个版本中Locale 组件，vant/src/locale/index.ts :7  定义的util 会与原本Vue 定义的util 起冲突导致打包不起
declare module 'vue' {
  interface VueConstructor {
    util: {
      defineReactive(obj: object, key: string, value: any): void;
    };
  }
}
Vue 2.6.14 版本新加的一行代码如下
vue/types/vue.d.ts:124 
util: {
    warn(msg: string, vm?: InstanceType<VueConstructor>): void;
  };

**Comment by chenjiahan** [comment]
已在 2.12.31 版本修复
