### ISSUE TITLE
[Bug Report] vant-progress在移动端进行横竖屏切换的时候进度显示异常

### ISSUE THREAD

**Issue by wuxiaolin171988835** [youzan/vant#9755]
### 设备 / 浏览器
手机

### Vant 版本
2.12.30

### Vue 版本
3.0.1

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-9691d?file=/src/App.vue&resolutionWidth=675&resolutionHeight=320" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-9691d?file=/src/App.vue&resolutionWidth=675&resolutionHeight=320</a>

### 描述问题
场景一：progress组件在竖屏模式下进度条显示正常,切换至横屏时进度条显示不到100%
场景二：progress组件在横屏模式下进度条显示正常，切换至竖屏模式进度条超出屏幕

**Comment by chenjiahan** [comment]
已在 2.12.31 版本修复

**Comment by wuxiaolin171988835** [comment]
# 2.12.31版本完成度为100%的时候，横屏转换为竖屏还是有问题

**Comment by wuxiaolin171988835** [comment]
2.12.31版本完成度为100%的时候，横屏转换为竖屏还是有问题

**Comment by wuxiaolin171988835** [comment]
100%的时候横屏转换为竖屏，进度小于100%

**Comment by chenjiahan** [comment]
我这边验证没问题呢，可以给个视频看下

**Comment by wuxiaolin171988835** [comment]
https://user-images.githubusercontent.com/22812710/140007090-4ca578b5-2b85-46aa-ae8a-18c2a448367c.mp4

**Comment by chenjiahan** [comment]
看视频确实是有问题，用 codesandbox 能复现吗

**Comment by wuxiaolin171988835** [comment]
![1635926063045](https://user-images.githubusercontent.com/22812710/140025347-138eb934-6dfa-47e2-ae73-6c30d734f13c.jpg)

**Comment by wuxiaolin171988835** [comment]
https://codesandbox.io/s/busy-knuth-vxdkx?file=/src/App.vue&resolutionWidth=675&resolutionHeight=320

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/140445342-1795b1c6-fae8-4eca-8f83-1fa4660f633b.png)

![image](https://user-images.githubusercontent.com/7237365/140445363-f5c7f37f-a9fa-4e56-9d8e-a8f0aa6eceb6.png)

在我这是正常的，你可以审查 DOM 元素看一下，是不是 px 出现小数单位导致的？

**Comment by wuxiaolin171988835** [comment]
你切换成我示例的尺寸呢

**Comment by chenjiahan** [comment]
换成你示例的尺寸也没法复现。

另外，Vant 3 已经更改了 Progress 的实现方式，应该不会出现类似的问题，这个 issue 先 close 了。
