### ISSUE TITLE
[Bug Report] Coupon  - last Item

### ISSUE THREAD

**Issue by Rasool-deldar** [youzan/vant#9777]
### Device / Browser
Mobile / Firefox

### Vant Version
3.2.6

### Vue Version
3.2.20

### Reproduction Link
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-cbctp" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-cbctp</a>

### Describe the bug
In different sizes, the last item goes under the button (the end is scrolling). Please solve this problem.

Coupon

// firefox - mobile
![image](https://user-images.githubusercontent.com/58503211/139672088-7d9ad8ca-9460-4a1e-b37e-99d71423c6f8.png)

// chrome - desktop - windows  10 ( 21-inch monitor )
![image](https://user-images.githubusercontent.com/58503211/139673350-5cff0ada-7aae-47be-afe6-91563c0284ec.png)

https://codesandbox.io/s/vant-issue-mo-ban-forked-p0kxt (v 2.13.31)

**Comment by chenjiahan** [comment]
Fixed in v3.3.0
