### ISSUE TITLE
[Bug Report]  not assignable to type 'PluginInstallFunction'

### ISSUE THREAD

**Issue by Soner2333** [youzan/vant#9789]
### 设备 / 浏览器
chrme

### Vant 版本
2.12.31

### Vue 版本
3.2.21

### 重现链接
<a href="http://172.16.10.113:8080/home" target="_blank">http://172.16.10.113:8080/home</a>

### 描述问题
ts 引入vant报错

**Comment by chenjiahan** [comment]
无效的重现链接。
