### ISSUE TITLE
Stepper 步进器出现错位

### ISSUE THREAD

**Issue by shejicq** [youzan/vant#979]
![tim 20180503173535](https://user-images.githubusercontent.com/1435789/39569531-0e51c982-4ef8-11e8-9a84-fd0fcf7a0434.jpg)
是样式没有引用正确吗

**Comment by chenjiahan** [comment]
浏览器是？

**Comment by shejicq** [comment]
谷歌浏览器

**Comment by chenjiahan** [comment]
未复现此问题
