### ISSUE TITLE
[Bug Report] 在微信中访问h5页面，使用uploader组件时，安卓机没有拍照的选项

### ISSUE THREAD

**Issue by fuguxu** [youzan/vant#9797]
### 设备 / 浏览器
华为mate30 plus

### Vant 版本
2.12.29

### Vue 版本
2.6.10

### 重现链接
<a href="https://fhysale.bgy.com.cn/sale-h5/partner/mobile.html#/newTaskInfoSettings" target="_blank">https://fhysale.bgy.com.cn/sale-h5/partner/mobile.html#/newTaskInfoSettings</a>

### 描述问题
在微信中访问h5页面，使用uploader组件时，安卓机没有拍照的选项，只有相册的选项，而苹果机两者选项都有

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/140314382-e45687a2-c1aa-4b83-b03d-fbc39411daa8.png)

这是浏览器原生属性喔，请自行解决。
