### ISSUE TITLE
[Bug Report]在v3.2.5上， click-tab要比before-change先执行，没法在点击生效前做作拦截。

### ISSUE THREAD

**Issue by 973257307** [youzan/vant#9803]
### 设备 / 浏览器
手机

Vant ### 版本
3.2.5

Vue ### 版本
3.2.2

### 描述问题
场景一：click-tab要比before-change先执行，没法在点击生效前做作拦截。

**Comment by chenjiahan** [comment]
下个版本会调整下触发顺序

**Comment by chenjiahan** [comment]
不过 before-change 只会拦截 Tab 切换，并不会拦截 click-tab 事件。

因为 click-tab 表示「点击了一个标签」，这个动作是不受 beforec-change 影响的。

**Comment by 973257307** [comment]
只要 before-change 这个在click-tab之前执行就可以达到效果了。谢谢！

**Comment by chenjiahan** [comment]
ok~

**Comment by chenjiahan** [comment]
已在 3.2.8 版本修复
