### ISSUE TITLE
[Bug Report]v2.12.31,area省市区的cancel事件没法触发

### ISSUE THREAD

**Issue by SomnusQiu** [youzan/vant#9807]
看了下源码，发现没有定义cancel方法，不过cancel按钮名称是可以修改的，而且<van-area>的ref上也没找到cancel属性
` render: function render() {
    var h = arguments[0];

    var on = _extends({}, this.$listeners, {
      change: this.onChange,
      confirm: this.onConfirm
    });

    return h(Picker, {
      "ref": "picker",
      "class": bem(),
      "attrs": {
        "showToolbar": true,
        "valueKey": "name",
        "title": this.title,
        "columns": this.displayColumns,
        "loading": this.loading,
        "readonly": this.readonly,
        "itemHeight": this.itemHeight,
        "swipeDuration": this.swipeDuration,
        "visibleItemCount": this.visibleItemCount,
        "cancelButtonText": this.cancelButtonText,
        "confirmButtonText": this.confirmButtonText
      },
      "scopedSlots": pickSlots(this, ['title', 'columns-top', 'columns-bottom']),
      "on": _extends({}, on)
    });
  }`

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/140444758-743dffce-2cbd-4edd-ad82-7ec02dbdf4d6.png)

cancel 事件直接继承给 Picker 组件的。如果使用有问题，请提供 codesandbox 复现链接喔
