### ISSUE TITLE
[Bug Report] popup的get-container='body'在页面中有节点变化的时候，设置无效

### ISSUE THREAD

**Issue by renjing940419** [youzan/vant#9814]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.31

### Vue 版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-mo-ban-forked-ttn4o?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-mo-ban-forked-ttn4o?file=/src/App.vue</a>

### 描述问题
popup的get-container='body'在页面中有节点变化的时候，且popup不在html的最开始或最后面的时候，设置无效

**Comment by chenjiahan** [comment]
这个和 Vue 的渲染机制有关系，在 Vant 2 中我们是通过移动 DOM 来实现的 get-container 属性，在 Vant 3 中我们使用了 Vue 3 提供的 Teleport 组件。

这个问题在 Vant 2 不太好解决，把 Popup 放到底部可以解决，或者升级到 Vant 3 也可以。
