### ISSUE TITLE
[Feature Request] 希望增加对tsx render更好的支持

### ISSUE THREAD

**Issue by fangkyi03** [youzan/vant#9816]
### 这个功能解决了什么问题
让tsx在render中也能得到更好的补全 vant:3.2.7

### 描述您想要的解决方案
```javascript
const fs = require('fs')
const vant = require('vant')
const filter = Object.keys(vant).filter((e)=>!['__esModule','default','install','version','Lazyload','Toast','Notify','Dialog','Locale','ImagePreview'].includes(e))
let text = ''
let importText = []

function addImport(name) {
    importText.push(name)
    if (vant[name].props) {
        importText.push(name   'Props')
    }
}

function getImportText() {
    return `import {${importText.toString()}} from 'vant' \n`
}
function addComponent(name) {
    if (vant[name].props) {
        return `export const V${name} = (props:${name}Props) => <${name} {...props}/> \n`
    }else {
        return `export const V${name} = (props:any) => <${name} {...props}/> \n`
    }
}
filter.forEach((e)=>{
    addImport(e)
    text  = addComponent(e)
})
text = getImportText()  + text
fs.writeFileSync('./src/vantLib/index.tsx',text)
```

### 建议的API是什么样的
我已经给你们写好了
目前你们这个版本的组件有以下问题
1.部分export的props命名没有驼峰
2.所有的props都是强制 没有加? 导致即使按照我上面的方式引入了 依旧要填所有参数 这个也需要你们排查一下 
3.还有就是有props但是没有export的也有很多 老实说 我写的这个转换脚本 都快成测试工具了 排查你们哪些代码写的不规范

**Comment by chenjiahan** [comment]
1.部分export的props命名没有驼峰

具体是指？

2.所有的props都是强制没有加 `?`

这个是你的 Vue 版本太低了，升级一下就好。

3. 漏了 `SubmitBarProps`, `PasswordInputProps`, `NavBarProps` `CouponProps`，下个版本会补上

**Comment by fangkyi03** [comment]
我用的是vite vue3的已经是最新版本的了 当然我说的还是tsx格式的 如果用vue格式然后script tsx那种的话是正常的 你可以运行一下我的代码就知道了

**Comment by fangkyi03** [comment]
在tsx文件格式下 你们现在的那种props都是强制的 必须所有属性都必填才可以

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/140629927-6a792380-9fba-4107-999f-859651e26aeb.png)

并没有必填呢，你的 Vue 版本是？

**Comment by chenjiahan** [comment]
上述问题已在 3.2.8 版本修复

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/140883018-35a0a438-49a1-4528-8a37-5b4f304d7b7d.png)

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/140883443-46912ee3-c755-434a-85ca-7fdce00d5726.png)
我得把这个button所有参数都挂上去以后 这边才不提示错误了 否则一直提示

**Comment by chenjiahan** [comment]
提供个最小复现仓库看下？

**Comment by fangkyi03** [comment]
我是tsx格式的文件 不是script type='tsx'这样在写的

**Comment by chenjiahan** [comment]
我上面的例子也是 tsx。

**Comment by fangkyi03** [comment]
import { defineComponent } from 'vue'
import styles from './test.module.less'
import { VButton } from './vantLib'
export default defineComponent({
    props:{
        type:{
            type:String,
            default:'test'
        }
    },
    render() {
        return (
            <div class={styles.main}>
                <VButton >ceshi</VButton>
            </div>
        )
    }
})
