### ISSUE TITLE
Slider滑块组件，step设置小数时，拖动滑块数值有时会错乱

### ISSUE THREAD

**Issue by Mr-xue** [youzan/vant#9823]
### 重现链接

本地开发环境，无法提供链接

### Vant 版本

2.9.2

### 描述一下你遇到的问题。

Slider滑块组件，当把step设置为0.1时，拖动滑块数值有时会错乱，并且圆点定位也出现错误。设置成整数没问题。
以下未操作时的录屏
![2021-11-09 10 15 38](https://user-images.githubusercontent.com/11676811/140849860-f881a1ce-687e-40a5-be6e-abe606683c95.gif)

### 重现步骤

1.step设置为0.1
2.拖动滑块

### 设备/浏览器

iphone、mac、安卓暂没测试

**Comment by chenjiahan** [comment]
麻烦更正一下标题。

**Comment by chenjiahan** [comment]
这个问题在 2.12.22 版本修复过，可以升级试下
