### ISSUE TITLE
[Bug Report] progress 组件 percentage 值大小影响到 border-radius 的大小

### ISSUE THREAD

**Issue by itxcc** [youzan/vant#9825]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-448bc?file=/src/main.js

### Vant 版本

3.2.5

### 描述一下你遇到的问题。

请看复现链接：

percentage 值越小，border-radius 越受影响

### 重现步骤

请看复现链接：

percentage 值越小，border-radius 越受影响

### 设备/浏览器

all

**Comment by chenjiahan** [comment]
已在 3.2.8 版本修复

**Comment by itxcc** [comment]
👍好快的响应
