### ISSUE TITLE
[Feature Request] vant-uploader上传视频后列表显示第一帧图片

### ISSUE THREAD

**Issue by zhidazhou** [youzan/vant#9830]
### 这个功能解决了什么问题
这个功能能解决上传视频后，视频列表丑的问题

### 描述您想要的解决方案
就是上传时vant-uploader可以识别是视频类型文件，上传成功后，能在列表显示第一帧图片，最好是跟照片一样能预览。预览功能我已经自己写dialog实现了。主要是列表显示视频第一帧图片问题

### 建议的API是什么样的
同上

**Comment by chenjiahan** [comment]
暂无计划支持视频预览喔，可以通过插槽自行实现。
