### ISSUE TITLE
希望增加 排版，图文，列表到详情相关组件

### ISSUE THREAD

**Issue by lmxin123** [youzan/vant#9831]
类似于uni-app 里面的
Typography
media list（图文列表）
链接如：
https://hellouniapp.dcloud.net.cn/pages/template/list2detail-list/list2detail-list

组件丰富度来说 uni-app远胜一筹
美工上来说Vant 略胜一筹

### 这个功能解决了什么问题？
它解决了数据展示问题

### 你期望的 API 是什么样子的？
<vant-media-list>

**Comment by chenjiahan** [comment]
暂无计划支持喔。
