### ISSUE TITLE
[Bug Report] Tabbar set route mode, before-change props not working

### ISSUE THREAD

**Issue by pandaTerminator** [youzan/vant#9833]
### Reproduction Link

https://codesandbox.io/s/vant-issue-mo-ban-forked-76j9k

### Vant Version

2.12.31

### Describe the Bug

When executing the before-change callback function, if the return is false, It should be prevented change. The route should not update.

### Reproduce Steps

Click the search tab.

**Comment by chenjiahan** [comment]
已在 2.12.32 版本修复
