### ISSUE TITLE
Switch 组件 van-switch__node 元素的font-size属性 没有继承父元素大小

### ISSUE THREAD

**Issue by zhaoweihan** [youzan/vant#9839]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-5dg5t

### Vant 版本

2.12.27

### 描述一下你遇到的问题。

通过 通配符* 设置默认字号font-size为14px。但Switch组件默认字号font-size为30px，此时组件内的van-switch__node元素大小没有继承父元素大小，导致样式异常；
并且设置Switch组件size Prop，也无效；

### 重现步骤

1、通过css 改变跟全局font-size
2、引入Switch组件，此时样式异常

### 设备/浏览器

Chrome 浏览器

**Comment by chenjiahan** [comment]
已在 2.12.32 版本修复
