### ISSUE TITLE
swipe组件在nuxt generate下无效果

### ISSUE THREAD

**Issue by z448401921** [youzan/vant#984]
**plugin.js** 
```
import Vue from 'vue'
import VueAwesomeSwiper from 'vue-awesome-swiper/dist/ssr'
Vue.use(VueAwesomeSwiper)
```
nuxt.config.js
`  plugins: ['~/plugins/vant.js','~/plugins/axios.js'], //插件引入配置`

nuxt start效果
![image](https://user-images.githubusercontent.com/9210994/39610610-2f26cc20-4f84-11e8-814c-5fd7bef2700b.png)

nuxt generate
`<div class="swiper-box" data-v-1b011d9c="" data-v-60ebb926=""><div class="van-swipe" data-v-1b011d9c=""><div class="van-swipe__track"><div class="van-swipe-item" data-v-1b011d9c="" style="width:0;transform:translate(0,0)"><img data-v-1b011d9c="" src="/images/tjzx-banner01.jpg" alt=""></div><div class="van-swipe-item" data-v-1b011d9c="" style="width:0;transform:translate(0,0)"><img data-v-1b011d9c="" src="/images/tjzx-banner01.jpg" alt=""></div></div><!----></div></div>`

**Comment by chenjiahan** [comment]
具体问题是？
