### ISSUE TITLE
[Bug Report] picker组件的columns-field-names values 参数异常

### ISSUE THREAD

**Issue by vkcyan** [youzan/vant#9846]
### 重现链接

https://codesandbox.io/embed/agitated-wildflower-w104b?fontsize=14&hidenavigation=1&theme=dark

### Vant 版本

3.2.8

### 描述一下你遇到的问题。

按文档说明 picker组件中 columns-field-names 参数的默认说明为 { text: 'text', values: 'values', children: 'children' }，实际编写使用文档实例`values`,字段无法正常使用

发现问题的项目中vant版本为3.0.16版本，codesandbox中测试3.2.8这个问题依旧存在

### 重现步骤

查看codesandbox

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/141615151-3ec2d403-e63a-4383-b005-6fa3e3648406.png)

注意用法，values 是一个选项数组，不是单个选项。

**Comment by vkcyan** [comment]
大哥你看了codesandbox里面的样式了吗，我这里是单列数据
是在自定义 columns 结构中的字段这里出现了问题
按照文档的columnsFieldNames默认字段给值，values是无法正常渲染的

**Comment by vkcyan** [comment]
https://github.com/youzan/vant/issues/9367

这个是一样的问题，在这个issues的codesandbox就有复现，存在一个多个人提出这个问题，麻烦您重视一下

**Comment by chenjiahan** [comment]
我看过了。

单列数据不应该使用 values 字段，values 是给多列选择用的。

**Comment by vkcyan** [comment]
目前文档API部 包括实例 没有明显提现 ，values 是给多列选择用的，value给单列使用，挺容易造成误解的，麻烦您优化一下文档，辛苦了🤞

**Comment by chenjiahan** [comment]
好的，后续会优化下
