### ISSUE TITLE
在 beforeRouteLeave函数中使用 Dialog 会一闪而过。

### ISSUE THREAD

**Issue by HuangWeiBin2** [youzan/vant#9847]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-myhf5?file=/src/App.vue

### Vant 版本

2.12.6

### 描述一下你遇到的问题。

 methods:{},
 beforeRouteLeave(to, from, next) { //离开路由之前执行的函数
         console.log('第二次页面只执行到这里')
       this.$dialog.confirm({
           title: title,
           message: message,
         }).then(() => {
           console.log('第一次进入页面可以执行完')
      })
}

### 重现步骤

 methods:{},
 beforeRouteLeave(to, from, next) { //离开路由之前执行的函数
         console.log('第二次页面只执行到这里')
       this.$dialog.confirm({
           title: title,
           message: message,
         }).then(() => {
           console.log('第一次进入页面可以执行完')
      })
}

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
将 `closeOnPopstate` 属性设置为 false 即可。

```js
Dialog.alert({
  title: '标题',
  message: '弹窗内容',
  closeOnPopstate: false,
}).then(() => {
  // on close
});
```
