### ISSUE TITLE
倒计时功能count-down组件

### ISSUE THREAD

**Issue by dj835638078** [youzan/vant#9849]
### 重现链接

https://testonline-us.vesync.com/

### Vant 版本

2.12.22

### 描述一下你遇到的问题。

用到倒计时count-down组件时，传入的值为后台取的时间，在手机真机上改变系统时间时，倒计时会加上改动的后时间差，必须手动刷新才能返回原值

### 重现步骤

1、打开页面
2、打开手机设置，修改手机系统时间
3、查看倒计时，此时倒计时时间会加上或减去改动后的时间差

**Comment by chenjiahan** [comment]
这个现象是正常的，因为倒计时每一次计算时间差时，都需要通过 Date.now() 获取当前系统时间，用户修改系统时间会影响 Date.now() 的结果。

这种情况只影响前端展示，后端依然可以在接口层面进行拦截。

**Comment by caomeibuaichibaicai** [comment]
> 这个现象是正常的，因为倒计时每一次计算时间差时，都需要通过 Date.now() 获取当前系统时间，用户修改系统时间会影响 Date.now() 的结果。
> 
> 这种情况只影响前端展示，后端依然可以在接口层面进行拦截。

不是很理解，倒计器功能为什么非要依赖系统时间呢，本身就是一个固定时间的倒计时，跟系统时间没有关系的吧，底层为什么不使用定时器实现，而要用系统时间减差值来计算呢？麻烦解答一些～
