### ISSUE TITLE
[Feature Request] Nuxt 3 compatibility

### ISSUE THREAD

**Issue by Extarys** [youzan/vant#9860]
### What problem does this feature solve?

Being able to use Vant with Nuxt 3 and Vue 3.

(Note: I never used Vant before but seems to be a nice UI for a new project)

### What does the proposed API look like?

Like other Vue 3/Nuxt 3 implementation I guess

**Comment by chenjiahan** [comment]
We will provide a nuxt 3 + vant demo later.

**Comment by chenjiahan** [comment]
vant v3.3.3 added support for nuxt3.

Demo project: https://github.com/youzan/vant-demo/tree/master/vant/nuxt3

We found that the load event of van-image cannot be triggered in nuxt 3, maybe we should wait for the nuxt team to fix this problem.
