### ISSUE TITLE
[Bug Report] NoticeBar显示隐藏后调用reset()重绘，文字无法滚动

### ISSUE THREAD

**Issue by NRMrYang** [youzan/vant#9861]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-7v09w?file=/src/App.vue

### Vant 版本

2.12.31

### 描述一下你遇到的问题。

遇到[#8906](https://github.com/youzan/vant/issues/8906)中的问题，切换后使用`this.$refs.noticeBar.reset()`重绘，但是发现原本设置的可滚动`scrollable`却不再滚动[](url)

### 重现步骤

烦请点击重现链接里的按钮两次，即可重现

### 设备/浏览器

移动端和PC端浏览器均有

**Comment by NRMrYang** [comment]
刚刚又发现[#8777](https://github.com/youzan/vant/issues/8777)似乎也是同样问题，说2.12.21已修复，但是我用的2.12.31

**Comment by chenjiahan** [comment]
#8906 是针对 Vant 3 做的修复，上述链接中使用的是 Vant 2，并没有提供同样的修复，后续会同步到 Vant 2 上。

#8777 不是同个问题。

**Comment by NRMrYang** [comment]
好的，如果修复了，烦请更新一下文档，感谢

**Comment by chenjiahan** [comment]
👌

**Comment by chenjiahan** [comment]
已在 2.12.32 版本支持
