### ISSUE TITLE
Swipe 组件在移动端 想要内部纵向滚动 无法实现

### ISSUE THREAD

**Issue by cyanwin** [youzan/vant#9867]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-xj9h9

### Vant 版本

3.2.6

### 描述一下你遇到的问题。

在移动端创建一个高度 70vh 的弹窗 使用 swipe 组件，内部内容可能会超出高度，想要纵向滚动，但是无法实现，添加 ：stop-propagation=“false” 也无法触发滚动，只能通过鼠标滚轮 滚动

### 重现步骤

1、swipe 组件外部固定高度
2、swipe 内部内容超出容器高度

### 设备/浏览器

移动端

**Comment by chenjiahan** [comment]
在重现链接中未复现你描述的问题，Chrome 模拟机/安卓真机均可正常滚动。
