### ISSUE TITLE
[Bug Report] nuxt项目Image组件使用lazy-load无效

### ISSUE THREAD

**Issue by laozb** [youzan/vant#9868]
### 重现链接

无

### Vant 版本

2.12.14

### 描述一下你遇到的问题。

nuxt项目按照Image组件图片懒加载部分文档编写代码，图片无法实现懒加载效果。是否是因为nuxt项目的原因

### 重现步骤

1.按照Image组件图片懒加载部分文档编写代码
2.无法实现懒加载效果

### 设备/浏览器

微信开发者工具-网页开发模式

**Comment by chenjiahan** [comment]
我试了下没问题，建议再检查下自己的代码，或者提供一个最小复现仓库地址。
