### ISSUE TITLE
Use the latest vant in nuxtjs ssr rendering, “error window is  not undefined”

### ISSUE THREAD

**Issue by Tengjungui** [youzan/vant#9873]
### 重现链接

No

### Vant 版本

v2.12.32

### 描述一下你遇到的问题。

Use the latest vant in nuxtjs ssr rendering, “error window is  not undefined”

### 重现步骤

cnpm run build  or yarn build
cnpm run start  or yarn start

 ERROR  window is not defined

  at Object.<anonymous> (node_modules/vant/lib/picker/PickerColumn.js:46:39)

**Comment by chenjiahan** [comment]
Fixed in v2.12.33
