### ISSUE TITLE
upload图片上传的preview-cover插槽参数问题

### ISSUE THREAD

**Issue by likandroid** [youzan/vant#9890]
### Reproduction Link

https://vant-contrib.gitee.io/vant/#/zh-CN/uploader

### Vant Version

2.12.25

### Describe the Bug

当我使用这段代码示例时，视图不显示应有的效果，且控制台会报错
<van-uploader v-model="fileList">
  <template #preview-cover="{ file }">
    <div class="preview-cover van-ellipsis">{{ file.name }}</div>
  </template>
</van-uploader>

### Reproduce Steps

![image](https://user-images.githubusercontent.com/32593986/142181437-d25a7e8a-bd9a-4441-b85c-d4311d0098ed.png)
这就代表file是undefined，那么这个示例是不是错误的？正确的示例是什么呢

### Device / Browser

google

**Comment by chenjiahan** [comment]
示例没问题，建议你检查下

- vue 版本是否 >= 2.6.0
- vant 版本是否 >= 2.9.1

**Comment by yufanshan** [comment]
那个file并不是指item对象 而是指item里面的字段，之所以报错是因为你的item里面没有file，你可以将file改成其他字段，或者在item里新建一个file
