### ISSUE TITLE
[Bug Report] ImagePreview组件调用vivo手机第一次无法展示第一张照片需要后划几张再次返回才能展示

### ISSUE THREAD

**Issue by xuyanming** [youzan/vant#9891]
### 重现链接

https://vant-contrib.gitee.io/vant/v3/#/zh-CN/image-preview

### Vant 版本

3.2.0

### 描述一下你遇到的问题。

 ImagePreview组件调用vivo手机第一次无法展示第一张照片需要后划几张再次返回才能展示；函数调用时showIndex页码快速滑动时数量超出图片总数 手机vivo y38

### 重现步骤

 ImagePreview组件调用vivo手机第一次无法展示第一张照片需要后划几张再次返回才能展示；函数调用时showIndex页码快速滑动时数量超出图片总数 手机vivo y38

### 设备/浏览器

vivo

**Comment by chenjiahan** [comment]
使用文档示例能复现吗？麻烦提供一下复现视频，问题描述看不懂。
