### ISSUE TITLE
scrollToDate 失效

### ISSUE THREAD

**Issue by catherchen** [youzan/vant#9892]
当van-calendar__body高度只展示两周时，scrollToDate只会滚动到指定日期当月，无法滚动到指定日期
![1637148223(1)](https://user-images.githubusercontent.com/30284748/142191690-7e338841-4c59-4fca-ba45-cfe7ea0d7b91.jpg)
![1637148233(1)](https://user-images.githubusercontent.com/30284748/142191699-226dd409-ee3f-4273-b08a-2fe4b5c417a6.jpg)

**Comment by chenjiahan** [comment]
请使用 issue 模板进行反馈，并提供复现链接。
