### ISSUE TITLE
[Bug Report] Calendar 日历 scrollToDate 失效问题

### ISSUE THREAD

**Issue by catherchen** [youzan/vant#9894]
### 重现链接

https://github.com/catherchen/my-vite-app

### Vant 版本

3.2.6

### 描述一下你遇到的问题。

设置van-calendar为指定高度，使日历高度仅显示少于一个月时，scrollToDate方法无法精准定位到指定日期，只定位到指定日期当月

### 重现步骤

git clone https://github.com/catherchen/my-vite-app.git
yarn install
yarn run dev
访问 http://localhost:3001/#/home

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
已在 3.3.2 版本修复
