### ISSUE TITLE
SSR uses popover component to say 'Document is not defined'

### ISSUE THREAD

**Issue by Ben-Ben-B** [youzan/vant#9897]
### 重现链接

https://github.com/Ben-Ben-B/vant-popover-ssr-error

### Vant 版本

3.2.8

### 描述一下你遇到的问题。

[ Midway ] [Vue warn]: Unhandled error during execution of setup function 
  at <VanPopover show=false onUpdate:show=fn<onUpdateShow> className="l-toolbar-popover van-popup van-popover van-popover--light"  ... >

[ Midway ] 
  ReferenceError: document is not defined
      at useClickAway (/Users/ben/work/isle-mobile/node_modules/@vant/use/dist/cjs/index.js:294:50)

### 重现步骤

useClickAway 在SSR下使用了document，导致在服务端找不到

**Comment by chenjiahan** [comment]
已在 3.3.0 版本修复

**Comment by Ben-Ben-B** [comment]
@chenjiahan Document的问题是好了，但是它报另一个错runtime-core.esm-bundler.js:6589 [Vue warn]: Hydration node mismatch:
