### ISSUE TITLE
使用asyncComputed方法调用一个含有toast手动关闭的异步函数，导致异步函数无限执行

### ISSUE THREAD

**Issue by yyl0828** [youzan/vant#9900]
### 重现链接

https://github.com/yyl0828/vant-issue-asynccomputed

### Vant 版本

^2.12.31

### 描述一下你遇到的问题。

使用asyncComputed方法调用一个含有toast手动关闭的异步函数，导致异步函数无限执行

### 重现步骤

运行代码就能看到控制台一直在输出，弹窗无限重复

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
建议你到 vue-async-computed 这个库进行反馈，Vant 没有对其进行适配。
