### ISSUE TITLE
[Bug Report] 配置sass-resources-loader全局变量注入后运行正常但构建报错

### ISSUE THREAD

**Issue by RenJie0813** [youzan/vant#9902]
### 重现链接

https://gitee.com/shuaigememeda/cli-app

### Vant Cli 版本

2.11.3

### 描述一下你遇到的问题。

配置了全局的scss变量，dev环境运行成功，build报错未定义的scss变量以及scss的mixins，webpack配置如下
`
 {
        test: /\.scss$/,
        use: [
          'sass-loader',
          {
            loader: 'sass-resources-loader',
            options: {
              _resources: path.resolve(__dirname, './src/scss/common.scss'),
              get resources() {
                return this._resources
              },
              set resources(value) {
                this._resources = value
              },
            },
          },
        ],
      },
`

### 重现步骤

1. 拉取项目
2. yarn
3. yarn dev  成功运行
4. yarn build 失败

**Comment by chenjiahan** [comment]
vant-cli 在 build 时是直接编译单文件的，并没有经过 Webpack loader，因此会构建失败。

并且 vant-cli 4.0 rc 版本已经完全迁移到 vite，不再支持 webpack 了。

**Comment by RenJie0813** [comment]
> vant-cli 在 build 时是直接编译单文件的，并没有经过 webpack loader，因此会构建失败。
> 
> 并且 vant-cli 4.0 rc 版本已经完全迁移到 vite，不再支持 webpack 了。

谢谢解答，祝发财
