### ISSUE TITLE
[Feature Request] 希望在文档项目中插入自定义的样式

### ISSUE THREAD

**Issue by zuolung** [youzan/vant#9907]
### 这个功能解决了什么问题？

1. markdown的table里面由html转义标签格式化的代码被最大宽度打乱格式
2. a标签active的样式很丑
![image](https://user-images.githubusercontent.com/28145148/142606040-12bc79b9-bf9e-4001-bda7-a023e05c8fdc.png)

### 你期望的 API 是什么样子的？

希望vant.config.js中可以配置外部样式文件的引入

**Comment by Banlangenn** [comment]
说的对

**Comment by chenjiahan** [comment]
暂时不计划支持自定义样式喔。

像 active 样式这种问题，可以提 PR 帮忙完善下默认样式
