### ISSUE TITLE
IndexBar真机无法滚动

### ISSUE THREAD

**Issue by say1921** [youzan/vant#9911]
### 重现链接

https://scrm-h5-fat.lctest.cn/flow/#/booking?couponNum=112039744236&couponSecret=_WJhUG7D

### Vant 版本

3.2

### 描述一下你遇到的问题。

IndexBar，真机上，页面无法滚动

### 重现步骤

点击选择城市，请在真机查看

### 设备/浏览器

移动端都会出现

**Comment by chenjiahan** [comment]
可以把 Overlay 的 lock-scroll 属性关掉，另外，这个场景更适合用 Popup

**Comment by say1921** [comment]
嗯，排查已解决，感谢
