### ISSUE TITLE
使用component动态生成组件，search和field的清空按钮失效

### ISSUE THREAD

**Issue by LadyChatterleyLover** [youzan/vant#9914]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-dqoou?file=/src/App.vue

### Vant 版本

3.2.0

### 描述一下你遇到的问题。

使用component动态生成组件，search和field的清空按钮失效, 有时候v-model也会失效，不能输入值

### 重现步骤

1. 输入值
2. 点击清空按钮无反应

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/143384744-06d240cd-a3de-4f18-872b-14d69afb6564.png)

我试了下上面的链接在移动端没问题。
