### ISSUE TITLE
van-circle 进度显示不正确

### ISSUE THREAD

**Issue by 362228416** [youzan/vant#9919]
### 重现链接

#

### Vant 版本

3.2.6

### 描述一下你遇到的问题。

van-circle 进度显示不正确，
![image](https://user-images.githubusercontent.com/5248797/143027103-fb92548b-2a0e-44f9-8a1a-29ec15e90dd3.png)

App.vue
```vue
<template>
  <div>
    <van-circle
        v-model="currentRate"
        :rate="30"
        :speed="100"
        :text="text"
    />
  </div>
</template>

<script>

export default{
  data(){
    return{
      currentRate:20
    };
  },
  computed:{
    text(){
      return this.currentRate.toFixed(0)+'%'
    }
  }
};
</script>

<style scoped>

</style>

```

### 重现步骤

1、vite 创建项目 vue3 项目
2、main.js 代码如下
```js
import { createApp } from 'vue'
import App from './App.vue'
import vant, {Toast} from 'vant'
import 'vant/lib/index.css'

const app = createApp(App)
app.use(vant)
app.mount('#app')
```
其他组件显示都挺正常，就是van-circle组件的进度值有问题，值怎么调都不生效不知道什么原因

### 设备/浏览器

chrome 95.0.4638.69，苹果手机浏览器

**Comment by 362228416** [comment]
解决了，是用法的问题

**Comment by chenjiahan** [comment]
请查看 vant 3 文档。

https://vant-contrib.gitee.io/vant/v3/#/zh-CN/circle
