### ISSUE TITLE
van-uploader组件无法实现只能拍照功能

### ISSUE THREAD

**Issue by zhujianxiong** [youzan/vant#9922]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-uvs3g

### Vant 版本

"vue": "^2.6.10",

### 描述一下你遇到的问题。

使用van-uploader组件打包成apk之后，无法实现只能拍照功能

### 重现步骤

1.使用van-uploader组件编写；
2.打包成apk;
3.点击拍照

### 设备/浏览器

安卓手机和苹果手机

**Comment by zhujianxiong** [comment]
![image](https://user-images.githubusercontent.com/45658422/143162411-fa917c4a-21ff-4673-bd9c-603c8c2b717f.png)

**Comment by zhujianxiong** [comment]
![image](https://user-images.githubusercontent.com/45658422/143162451-7b8d1808-9fee-4679-ad74-910c8d5bbd76.png)
期待的效果

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/143167237-2f0ed401-805d-4f0c-a692-f60ac5165212.png)

这个是浏览器能力，vant 只做了属性透传。
