### ISSUE TITLE
[Bug Report] DatetimePicker 配合 Popup 使用，给 picker 设置 min-date，设置 popup visible 为 true 时，页面卡死

### ISSUE THREAD

**Issue by KamiC6238** [youzan/vant#9923]
### 重现链接

https://codesandbox.io/s/vant3-demo-forked-nv89k?file=/src/components/HelloWorld.vue

### Vant 版本

3.2.6

### 描述一下你遇到的问题。

在 vue3 项目中使用 3.2.6 版本的 vant，使用 popup 配合 DateTimePicker 组件，给 DateTimePicker 组件设置 min-date，之后修改 popup v-model 绑定的值为 true，此时 picker 没有弹出，并且页面卡死。

![image](https://user-images.githubusercontent.com/23523595/143173266-403b1330-15bd-49aa-8c70-ad040062cb22.png)

### 重现步骤

1. Popup 包裹 DateTimePicker
2. 设置 DateTimePicker 的 min-date 属性，例如 <DateTimePicker :min-date="new Date(2020, 10, 24)" />
3. 修改 popup v-model 绑定的值为 true
4. 页面卡死

**Comment by KamiC6238** [comment]
有点需要提一下，就是我在 codesandbox 尝试了一下发生可以正常工作，不知为什么在自己代码里会卡死。

**Comment by chenjiahan** [comment]
从 codesandbox 看没发现问题，建议你再自行排查下自己项目中的逻辑是否有异常，或者升级 vue/vant 试试。

**Comment by EleShader** [comment]
我也遇到这样的问题

**Comment by SJW2017** [comment]
我也遇到这样的问题 好像是打开多个popup就容易卡
