### ISSUE TITLE
急！！一直在线上跑着的版本，20多天未发版，今天突然所有页面样式错乱！！！急！！！

### ISSUE THREAD

**Issue by ruanhaikun** [youzan/vant#9925]
### 重现链接

https://www.myutopa.com/m/template/#/signin?activityId=2012&crm_channel_id=107291

https://www.myutopa.com/m/scrm/#/home
### Vant 版本

^3.0.6

### 描述一下你遇到的问题。

急！！一直在线上跑着的版本，20多天未发版，今天突然所有页面样式错乱！！！急！！！
凡是用到vant组件 或者vant类名的地方，css都不起作用了！！

两条链接都是对应两个不同项目，但是两个项目同时都有问题了
### 重现步骤

急！！一直在线上跑着的版本，20多天未发版，今天突然所有页面样式错乱！！！急！！！
凡是用到vant组件 或者vant类名的地方，css都不起作用了！！

### 设备/浏览器

所有浏览器

**Comment by chenjiahan** [comment]
从你提供的链接上，未发现与 Vant 相关的问题。

建议先自行排查下，如果定位到是 Vant 代码的问题，再通过 issue 进行反馈。
