### ISSUE TITLE
线上运行以及本地运行和本地打包遇到样式缺少的问题。

### ISSUE THREAD

**Issue by ruanhaikun** [youzan/vant#9930]
### 重现链接

https://www.myutopa.com/m/template/#/signin?activityId=2012&crm_channel_id=107291

### Vant 版本

^3.0.6

### 描述一下你遇到的问题。

两个项目基础架构都是vite+vue3+vant3。
然后今天中午12点-15点多暂时性同时出现了vant相关组件样式缺少问题，以及同时修复了，但是我这边都没有动代码以及发版
![image](https://user-images.githubusercontent.com/42954555/143199342-f824bc9e-899c-4b68-9c5b-484699cabc66.png)

对比图：![image](https://user-images.githubusercontent.com/42954555/143199362-2266a135-403f-49bf-8729-472b3a8aa3b6.png)
对比图：![image](https://user-images.githubusercontent.com/42954555/143199369-e439375e-1018-405f-82ce-f910fa283e3d.png)

正常图：
![image](https://user-images.githubusercontent.com/42954555/143199425-a8c7a45a-7add-48ef-8771-e051a2be229b.png)

想问一下这是vant的问题吗，是的话该怎么预防再次出现

### 重现步骤

两个项目基础架构都是vite+vue3+vant3。
然后今天中午12点-15点多暂时性同时出现了vant相关组件样式缺少问题，以及同时修复了，但是我这边都没有动代码以及发版
![image](https://user-images.githubusercontent.com/42954555/143199342-f824bc9e-899c-4b68-9c5b-484699cabc66.png)

对比图：![image](https://user-images.githubusercontent.com/42954555/143199362-2266a135-403f-49bf-8729-472b3a8aa3b6.png)
对比图：![image](https://user-images.githubusercontent.com/42954555/143199369-e439375e-1018-405f-82ce-f910fa283e3d.png)

正常图：
![image](https://user-images.githubusercontent.com/42954555/143199425-a8c7a45a-7add-48ef-8771-e051a2be229b.png)

想问一下这是vant的问题吗，是的话该怎么预防再次出现

### 设备/浏览器

所有浏览器

**Comment by chenjiahan** [comment]
考虑到稳定性，线上业务要避免直接引用 cdn.jsdelivr.net 上的 CDN 文件。（jsdelivr 是一项免费、面向开源的 CDN 服务）

最好是通过 npm 引入 vant，或者上传到你们自己的 CDN 上。

**Comment by ruanhaikun** [comment]
> 首先这不是 vant 的问题，vant 3 今天没有发版。
> 
> 从现象看，有可能是 jsdelivr 的问题，jsdelivr 是一项免费、面向开源的 CDN 服务。考虑到业务稳定性，线上业务要避免直接引用 cdn.jsdelivr.net 上的 CDN 文件。
> 
> 最好是通过 npm 引入 vant，或者上传到你们自己的 CDN 上。

我没有用cdn，用的vite里面package.json dependencies里面安装的依赖

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/143347947-d5b9f4f3-d996-47da-835e-1907bdfac9e5.png)

这个不是？
