### ISSUE TITLE
ios系统下外层盒子设置了圆角，overflow: hidden; swipe组件切换时，会把圆角失效后，切换完成，又变回圆角

### ISSUE THREAD

**Issue by 5SUPERMAN** [youzan/vant#9931]
### 重现链接

https://testact.udaer.net/famousProductIntegralIndex

### Vant 版本

^2.12.29

### 描述一下你遇到的问题。

ios系统下外层盒子设置了圆角，并且overflow: hidden; 
但是swipe组件切换时，会把圆角失效后，切换完成后，又变回圆角

### 重现步骤

swipe切换时出现

### 设备/浏览器

ios系统的手机

**Comment by xiaobeifeng** [comment]
可以注意下层级和 css 的设置问题，你参考下我的

```
.m-banner {
  margin: 8px 8px 8px 8px;
  overflow: hidden;
  border-radius: 5px;
  &-swipe {
    transform: translateY(0);
    border-radius: 5px;
    &-item {
      background-color: white;
    }
  }
}
```

```
<div class="m-banner">
        <van-swipe
          class="m-banner-swipe"
          :autoplay="3000"
          duration="1000"
          indicator-color="#1E8BF6"
          height="180"
        >
          <van-swipe-item
            class="m-banner-swipe-item"
            v-for="item in bannerList"
            :key="item.id"
            @click="swipeClick(item)"
          >
            <van-image fit="fill" :src="item.imageUrl" height="180px" width="100%" />
          </van-swipe-item>
        </van-swipe>
      </div>
```

**Comment by chenjiahan** [comment]
已在 2.12.35 版本修复

**Comment by 5SUPERMAN** [comment]
> 已在 2.12.35 版本修复

好的，麻烦了！

**Comment by 5SUPERMAN** [comment]
> 可以注意下层级和 css 的设置问题，你参考下我的
> 
> ```
> .m-banner {
>   margin: 8px 8px 8px 8px;
>   overflow: hidden;
>   border-radius: 5px;
>   &-swipe {
>     transform: translateY(0);
>     border-radius: 5px;
>     &-item {
>       background-color: white;
>     }
>   }
> }
> ```
> 
> ```
> <div class="m-banner">
>         <van-swipe
>           class="m-banner-swipe"
>           :autoplay="3000"
>           duration="1000"
>           indicator-color="#1E8BF6"
>           height="180"
>         >
>           <van-swipe-item
>             class="m-banner-swipe-item"
>             v-for="item in bannerList"
>             :key="item.id"
>             @click="swipeClick(item)"
>           >
>             <van-image fit="fill" :src="item.imageUrl" height="180px" width="100%" />
>           </van-swipe-item>
>         </van-swipe>
>       </div>
> ```

加上这个transform: translateZ(0); 就可以了
