### ISSUE TITLE
tab标签可以自定义选中的样式

### ISSUE THREAD

**Issue by zoozoocat** [youzan/vant#9936]
### 这个功能解决了什么问题？

tab组件 选中只有2种类型的背景样式选择，line和card,希望可以自定义样式### 

### 你期望的 API 是什么样子的？

tab组件 选中只有2种类型的背景样式选择，line和card,希望可以自定义样式###

**Comment by chenjiahan** [comment]
自定义样式的方法参见：https://vant-contrib.gitee.io/vant/v3/#/zh-CN/faq
