### ISSUE TITLE
[Bug Report] Calendar 组件在show-confirm属性为false的时候可以选择到超过日期区间范围外的日期

### ISSUE THREAD

**Issue by wuchuzhengzhong** [youzan/vant#9937]
### 重现链接

https://github.com/youzan/vant/issues?page=6&q=Calendar

### Vant 版本

3.2.3

### 描述一下你遇到的问题。

Calendar 组件在show-confirm属性为false的时候可以选择到超过日期区间范围外的日期

### 重现步骤

<van-calendar v-model:show="showDate" type="range"  :max-range="3" :show-subtitle="false":show-confirm="false" :closeable="false":style="{ height: '500px' }" />

可以选择到超出3天的时间

**Comment by chenjiahan** [comment]
已在 3.3.2 版本修复
