### ISSUE TITLE
[Bug Report] DropdownMenu 组件在NavBar 组件中使用时 点击页面闪烁

### ISSUE THREAD

**Issue by 521314xiongCheng** [youzan/vant#9941]
### 重现链接

https://codesandbox.io/s/vant-issue-mo-ban-forked-3mt3w?file=/src/App.vue

### Vant 版本

2.12.34/2.12.7/2.9.2

### 描述一下你遇到的问题。

当我在NavBar 组件中嵌套DropdownMenu组件，下拉菜单展开时，我点击任意地方，页面出现闪烁透明
![image](https://user-images.githubusercontent.com/54136501/143412253-239c4d75-fe1c-404b-9a8e-6f9e0e52acda.png)
我在多个项目中尝试都会有这种情况，只要不放在NavBar中就是正常的。这个问题当我设置get-container=“body”时可以得到解决，但是有其他问题，不符合我的需求。很尴尬的一点是，这个问题在codesandbox中没有重现

### 重现步骤

1、点击右上角 全部商品，展开下拉菜单
2、点击页面遮罩层

### 设备/浏览器

浏览器 android上都有这个问题

**Comment by 521314xiongCheng** [comment]
我新建了一个空白项目"vant": "^2.12.34", "vue": "^2.6.11"，同样有这个问题

**Comment by chenjiahan** [comment]
这个现象是由于 NavBar 的按钮有一个「点击透明」的反馈效果，你把 DropdownMenu 放在 Right 按钮内部的时候，也受到了这个样式影响：

```css
.van-nav-bar__right:active {
    opacity: .7;
}
```

解决方法就是设置 get-container 属性，或者把上面这个样式覆盖掉。

**Comment by 521314xiongCheng** [comment]
好的 谢谢
