### ISSUE TITLE
uploader组件-accept属性部分机型有问题

### ISSUE THREAD

**Issue by 17864307898** [youzan/vant#9943]
给uploader组件设置的accept限制了jpg和png类型，大部分机型生效，在华为手机上仍然可以上传限制类型外的图片（如gif图）

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/143167237-2f0ed401-805d-4f0c-a692-f60ac5165212.png)

这个是浏览器能力，vant 只做了属性透传。
