### ISSUE TITLE
vant Picker组件columns-field-names参数 values文档显示错误

### ISSUE THREAD

**Issue by cyanwin** [youzan/vant#9946]
### 重现链接

https://vant-contrib.gitee.io/vant/v3/#/zh-CN/picker

### Vant Cli 版本

^3.2.6

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/45061152/143539381-1d8c3fd5-04f8-4a0e-865e-37571e86230b.png)

文档显示使用values，实际应该使用value

### 重现步骤

官方文档显示错误

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/9846
