### ISSUE TITLE
field组件无法在ios上唤醒键盘

### ISSUE THREAD

**Issue by person001** [youzan/vant#9950]
### 重现链接

https://www.pgyer.com/opsmaster-test

### Vant 版本

2.12.3

### 描述一下你遇到的问题。

头一次进来 鼠标点也要点几次， 触发过一次键盘响应，后面再点就正常了

### 重现步骤

头一次进来 鼠标点也要点几次，触发过一次键盘响应，后面再点就正常了

### 设备/浏览器

iphone x  ios13.5；

**Comment by chenjiahan** [comment]
从描述看，这个问题和组件无关，建议你从其他角度排查下，看看是否有其他因素影响，或者可以用原生 input 标签测试下。

**Comment by chaihe** [comment]
> 从描述看，这个问题和组件无关，建议你从其他角度排查下，看看是否有其他因素影响，或者可以用原生 input 标签测试下。

 额 我情况是h5 跑在微信里 也遇到了 单击不能聚焦 必须快速点击 才可以聚焦

**Comment by person001** [comment]
我在安卓机器上没发先类似的问题，猜测是否存在适配的问题

**Comment by Fun005** [comment]
我也遇到了，包括field、search

**Comment by Fun005** [comment]
我也遇到了，点击无法获取焦点，必须连续点击（双击）才能正常获取焦点，包括field、search

**Comment by hmyjyghh** [comment]
我是安卓上不会自动聚焦，ios 第一次进来是自动聚焦，再次进入也不能自动聚焦了
