### ISSUE TITLE
[Bug Report] 打包了有异步组件的包使用时会报错

### ISSUE THREAD

**Issue by gitbu** [youzan/vant#9954]
### 重现链接

https://github.com/gitbu/vite-cli-demo

### Vant Cli 版本

2.11.3

### 描述一下你遇到的问题。

使用打包了含有异步组件的包，会报错
报错截图如下：
![image](https://user-images.githubusercontent.com/14817184/143795485-01897dc3-8a57-4c34-b6eb-6b2efc8f5a5d.png)
![image](https://user-images.githubusercontent.com/14817184/143795498-61418ccc-33c7-4800-8732-5d5f34dcdca4.png)
我把vue-cli打包好的文件和vant-cli打包好的文件对比了一下，发现是下面这一行没有加括号的问题
`var jsonpArray = typeof self !== 'undefined' ? self : this["webpackJsonpvant_demo"] = typeof self !== 'undefined' ? self : this["webpackJsonpvant_demo"] || [];`
修改后就没得问题了
`var jsonpArray = (typeof self !== 'undefined' ? self : this)["webpackJsonpvant_demo"] = (typeof self !== 'undefined' ? self : this)["webpackJsonpvant_demo"] || [];`

### 重现步骤

运行打包后的代码

**Comment by gitbu** [comment]
@chenjiahan这个问题是解决了吗? 我需要在重新安装一下vant-cli吗？

**Comment by chenjiahan** [comment]
已在 @vant/cli@2.11.4 解决，可以升级试下

**Comment by gitbu** [comment]
@chenjiahan 我试过可，可以的，多谢大佬

**Comment by chenjiahan** [comment]
客气咯
