### ISSUE TITLE
vant3.3 使用vite-plugin-style-import按需引入报错

### ISSUE THREAD

**Issue by cinob** [youzan/vant#9957]
### 重现链接

https://github.com/cinob/vant3.3-issue-demo

### Vant 版本

3.3

### 描述一下你遇到的问题。

使用vite-plugin-style-import按需引入报错
Internal server error: Failed to resolve import "xxx/vant-test/node_modules/.pnpm/vant@3.3.2_vue@3.2.23/node_modules/vant/lib/vant/es/button/style" from "src\pages\index.vue". Does the file exist?

降级到vant3.2使用正常

### 重现步骤

https://github.com/cinob/vant3.3-issue-demo

**Comment by zguiyang** [comment]
我也出现了此问题

**Comment by yc-yangchen** [comment]
尝试使用yarn进行安装命令

**Comment by G-LiHuan** [comment]
> 我也出现了此问题, 我的vant版本是3.2.6，好像是vite-plugin-style-import插件的问题，版本降到1.1.0就打包成功了

3.2.6是可以的，把package.json里面vant依赖版本^符号去掉就行。有这个符号安装的时候会选择最新的安装

**Comment by chenjiahan** [comment]
这个是 vite-plugin-style-import 的 bug，我已经创建了对应的 issue 进行反馈：https://github.com/anncwb/vite-plugin-style-import/issues/52

**Comment by zhoucan38** [comment]
> 这个是 vite-plugin-style-import 的 bug，我已经创建了对应的 issue 进行反馈：[anncwb/vite-plugin-style-import#52](https://github.com/anncwb/vite-plugin-style-import/issues/52)

@chenjiahan 建议这个vite插件vant自己实现好了，方便控制

**Comment by thpngj** [comment]
![image](https://user-images.githubusercontent.com/43071845/143981127-58e0eaac-485f-4a8d-8c46-9705c927328c.png)

我在 vite.config.js 的配置里 resolveStyle 里面的返回路径加上 /node_modules/ 不会报错了， 暂时先这么解决吧～

**Comment by chenjiahan** [comment]
> @chenjiahan 建议这个vite插件vant自己实现好了，方便控制

没必要重复建设哈，交给社区就好

**Comment by atom78** [comment]
这个应该是3.2.2之后的版本起用了package.json的exports引起的问题，把nodejs升级到12.20以上的版本应该就可以

**Comment by RookieDouby** [comment]
> ![image](https://user-images.githubusercontent.com/43071845/143981127-58e0eaac-485f-4a8d-8c46-9705c927328c.png)
> 
> 我在 vite.config.js 的配置里 resolveStyle 里面的返回路径加上 /node_modules/ 不会报错了， 暂时先这么解决吧～

这个可以呀，我也按照你这样处理了
