### ISSUE TITLE
[Bug Report] 在popup组件中使用search组件，search组件输入内容后失焦时导致popup组件被关闭

### ISSUE THREAD

**Issue by duious** [youzan/vant#9965]
### 重现链接

https://github.com/duious/vant-demo

### Vant 版本

3.3.0

### 描述一下你遇到的问题。

popup组件内的search组件，打包后，当search内输入内容后失焦时会导致popup组件被异常关闭

### 重现步骤

1、打开popup弹窗
2、在search组件内输入内容
3、点击popup组件内其他区域
4、popup组件被异常关闭

### 设备/浏览器

chrome，安卓、ios

**Comment by chenjiahan** [comment]
无法运行该仓库，@pplmc/util 依赖不存在。

请提供最小可用复现仓库。

**Comment by duious** [comment]
已删除无关依赖,请重新构建

**Comment by chenjiahan** [comment]
试了下并没有你描述的问题，失焦后弹窗正常。

![image](https://user-images.githubusercontent.com/7237365/144423295-279658ec-3bce-4c2c-8671-428bd8436080.png)

**Comment by duious** [comment]
问题发生在打包后,本地运行是正常的

**Comment by duious** [comment]
请问这个问题有进展了没?
