### ISSUE TITLE
[Bug Report]生成文档后异步组件的demo不会显示

### ISSUE THREAD

**Issue by gitbu** [youzan/vant#9968]
### 重现链接

https://github.com/gitbu/vite-cli-demo

### Vant Cli 版本

2.11.4

### 描述一下你遇到的问题。

生成文档后异步组件的demo不会显示

### 重现步骤

运行：npm run build-site

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/144176617-7d431cff-3520-43de-a83f-054894e15bb4.png)


vant-cli 不支持这种写法，也不计划支持。有需求的话可以 fork 一下自己实现。
