### ISSUE TITLE
ImagePreview 升级到最新版本，我们项目内使用有问题

### ISSUE THREAD

**Issue by niehuaming** [youzan/vant#9974]
### 重现链接

https://m5v3f.csb.app/

### Vant 版本

3.3.3

### 描述一下你遇到的问题。

我们项目内使用就是用问题，通过你们的在线连接去编写没有问题，很奇怪，这个问题只有在**钉钉内**打开连接，然后查看图片就回有问题，我上传一个视频你们看看。[https://v.youku.com/v_show/id_XNTgyNDEwMjM1Mg==.html](url)

### 重现步骤

请看上面的视频

**Comment by chenjiahan** [comment]
@niehuaming 回退到 3.3.2 试试有问题不
