### ISSUE TITLE
[Bug Report] navbar fix在android刘海屏无效

### ISSUE THREAD

**Issue by lishichao1002** [youzan/vant#9978]
### 重现链接

无

### Vant 版本

latest

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/13584162/144224717-47da662b-1029-4ed2-a82f-c26dd13579d9.png)

env(safe-area-inset-top) 在 android 手机上无效好像是共识，好奇vant是如何适配android的刘海屏手机的

https://stackoverflow.com/questions/52476016/envsafe-area-inset-top-not-working-on-android-pie-webview-69

### 重现步骤

直接使用android刘海屏全屏打开页面，不要客户端自己的导航栏

### 设备/浏览器

android刘海屏手机

**Comment by chenjiahan** [comment]
部分手机不支持的话，需要使用者手动进行兼容了，Vant 目前没有计划去进行兼容。

参见 https://zhuanlan.zhihu.com/p/373745323
