### ISSUE TITLE
[Bug Report] 使用Field组件出现失去焦点，双击输入框后焦点上下闪烁跳动

### ISSUE THREAD

**Issue by linmengyu** [youzan/vant#9979]
### 重现链接

https://m5v3f.csb.app/

### Vant 版本

2.12.35

### 描述一下你遇到的问题。

第一次进入界面正常，双击准备在空白处输入文本后，焦点上下不停跳动闪烁，并产生界面抖动
由于代码内网无法重现，敬请作者仔细测试BUG

### 重现步骤

第一次进入界面正常，双击准备在空白处输入文本后，焦点上下不停跳动闪烁，并产生界面抖动

### 设备/浏览器

Chrome

**Comment by chenjiahan** [comment]
无效的重现链接。
