### ISSUE TITLE
vite报错 Internal server error: Missing "./es" export in "vant" package

### ISSUE THREAD

**Issue by AIxiuxiu** [youzan/vant#9980]
### 重现链接

https://github.com/AIxiuxiu/vant-bug

### Vant 版本

3.3.4

### 描述一下你遇到的问题。

vite使用unplugin-vue-components导入报错 [vite] Internal server error: Missing "./es" export in "vant" package

### 重现步骤

安装依赖 yarn
启动 yarn start
打开浏览器不错

### 其他
使用3.2.8版本就不会报错

_No response_

**Comment by chenjiahan** [comment]
已在 3.3.5 版本修复
