### ISSUE TITLE
【BUG】使用postcss-pxtorem后，button组件的位置产生偏移

### ISSUE THREAD

**Issue by ALL-STACK** [youzan/vant#9981]
### 重现链接

git@github.com:ALL-STACK/h5.git

### Vant 版本

3.3.0

### 描述一下你遇到的问题。

使用postcss-pxtorem后，button组件的位置产生偏移
![image](https://user-images.githubusercontent.com/24264872/144346206-c449cfd7-54f7-42c9-b713-3277e71effa7.png)

### 重现步骤

在dashboard页，button组件位置偏移

**Comment by chenjiahan** [comment]
这个问题和 vant 没啥关系，基础的 inline-block 布局问题，可以改成 flex。
