### ISSUE TITLE
[Feature Request] 如何定义全局css

### ISSUE THREAD

**Issue by MaybeQHL** [youzan/vant#9990]
### 这个功能解决了什么问题？

导入打包全局css

### 你期望的 API 是什么样子的？

导入打包全局css

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/144554077-0b353ce1-c2ba-44a9-a95d-44b128d6ae6a.png)

**Comment by MaybeQHL** [comment]
文档模式下呢

**Comment by chenjiahan** [comment]
可以通过 webpack.config.js 自己配

**Comment by MaybeQHL** [comment]
配置
![image](https://user-images.githubusercontent.com/34638673/144558366-39c942c5-63ce-4e1a-98c9-3d79c74d48d4.png)
![image](https://user-images.githubusercontent.com/34638673/144558220-2b63f036-dd8f-4538-9760-1ceab71bf935.png)
样式：
![image](https://user-images.githubusercontent.com/34638673/144558386-3a05ee2e-53f6-4897-803c-3e51c55bbbb0.png)
结果：
![image](https://user-images.githubusercontent.com/34638673/144558418-d5d4664c-46b9-4f1c-84e0-4647d50d4d18.png)

**Comment by MaybeQHL** [comment]
![image](https://user-images.githubusercontent.com/34638673/144559916-3c444b3c-bb15-484c-a6f8-400d0a809cbc.png)
在index.css @import 资源 构建的产物中不包含。
![image](https://user-images.githubusercontent.com/34638673/144559984-15f63f75-205a-4804-8203-9ede51bd2dfa.png)
