### ISSUE TITLE
表单效验form时不时就有问题，也没有标红，onFailed函数打印出来说第一个验证有问题

### ISSUE THREAD

**Issue by pjy7** [youzan/vant#9994]
![Snipaste_2021-12-03_14-16-01](https://user-images.githubusercontent.com/65715299/144555032-a5482c13-4fa8-4802-9b17-4e96d1ec67f4.png)
![Snipaste_2021-12-03_14-16-59](https://user-images.githubusercontent.com/65715299/144555036-b06a1ecb-89d4-482d-9b4d-a1ef64659ff7.png)
![Snipaste_2021-12-03_14-17-21](https://user-images.githubusercontent.com/65715299/144555040-66891eb8-0a69-489e-a2b3-d1ae3e067dd7.png)

**Comment by chenjiahan** [comment]
请按照模板进行 issue 反馈，并提供有效的 codesandbox 复现链接
