### ISSUE TITLE
[Bug Report] VanTab 通过v-for出来，默认选中失效

### ISSUE THREAD

**Issue by SnowdropK** [youzan/vant#9995]
### 重现链接

https://vant-contrib.gitee.io/vant/v3/#/zh-CN/tab

### Vant 版本

3.2.5

### 描述一下你遇到的问题。

`
      <VanTabs v-model:active="activeScene" type="card" class="showing">
        <VanTab v-for="item in activitySceneList" :key="item.autoId" :name="item.autoId">
          <template #title>
            <div>
              <p class="time">{{ item.startTime }}-{{ item.endTime }}</p>
              <p class="status">{{ item.sceneStatusTitle }}</p>
            </div>
          </template>
        </VanTab>
      </VanTabs>
const activeScene = ref(0);
`

以上代码，默认选中无效
但是换成下面的形式，就能默认选中
`
        <VanTab :name="item.autoId">
          <template #title>
            <div>
              1
            </div>
          </template>
        </VanTab>
        <VanTab :name="item.autoId">
          <template #title>
            <div>
              2
            </div>
          </template>
        </VanTab>
        <VanTab :name="item.autoId">
          <template #title>
            <div>
              3            </div>
          </template>
        </VanTab>
`

### 重现步骤

      <VanTabs v-model:active="activeScene" type="card" class="showing">
        <VanTab v-for="item in activitySceneList" :key="item.autoId" :name="item.autoId">
          <template #title>
            <div>
              <p class="time">{{ item.startTime }}-{{ item.endTime }}</p>
              <p class="status">{{ item.sceneStatusTitle }}</p>
            </div>
          </template>
        </VanTab>
        <VanTab :name="item.autoId">
          <template #title>
            <div>
              1
            </div>
          </template>
        </VanTab>
      </VanTabs>

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
无效的重现链接。
