### ISSUE TITLE
[Feature Request] v2版本的slider，双滑块模式插槽只有一个，希望改成v3一样的

### ISSUE THREAD

**Issue by black-star123** [youzan/vant#9996]
### 这个功能解决了什么问题？

需要双滑块自定义按钮内容时，无法实现

### 你期望的 API 是什么样子的？

    <van-slider
      bar-height="4px"
      active-color="#f33"
      inactive-color="#ffffff"
      range
      v-model="value"
      :barHeight="6"
      @change="handleChange"
    >
      <template #buttonLeft>
        <div class="custom-button">{{ value[0] }}</div>
      </template>
<template #buttonRight>
        <div class="custom-button">{{ value[1] }}</div>
      </template>
    </van-slider>

**Comment by chenjiahan** [comment]
v2 版本不再新增功能了哈，不过有需要的话可以参照 v3 的实现，提 PR 到 2.x 分支。
