### ISSUE TITLE
[Bug Report] 官方文档中  “Field 输入框”  示例中多个输入框一起展示时没有使用完整的闭合标签，也会导致新手写BUG

### ISSUE THREAD

**Issue by fb1220** [youzan/vant#9997]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/field

### Vant 版本

2.12

### 描述一下你遇到的问题。

https://vant-contrib.gitee.io/vant/#/zh-CN/field  此页面中，自定义类型多个同时展示时，

应该是:

`
 < !-- 输入任意文本 -- >
 < van-field v-model="text" label="文本" > </van-field> 
 < !-- 输入手机号，调起手机号键盘 --> 
 < van-field v-model="tel" type="tel" label="手机号" > </van-field> 
 < !-- 允许输入正整数，调起纯数字键盘 --> 
 < van-field v-model="digit" type="digit" label="整数" > </van-field> 
 < !-- 允许输入数字，调起带符号的纯数字键盘 --> 
 < van-field v-model="number" type="number" label="数字" > </van-field> 
 < !-- 输入密码 --> 
 < van-field v-model="password" type="password" label="密码" > </van-field> 
`

而非:

`
< !-- 输入任意文本 -->
< van-field v-model="text" label="文本" />
< !-- 输入手机号，调起手机号键盘 -->
< van-field v-model="tel" type="tel" label="手机号" />
< !-- 允许输入正整数，调起纯数字键盘 -->
< van-field v-model="digit" type="digit" label="整数" />
< !-- 允许输入数字，调起带符号的纯数字键盘 -->
< van-field v-model="number" type="number" label="数字" />
< !-- 输入密码 -->
< van-field v-model="password" type="password" label="密码" />
`

从element ui转过来的新手习惯性直接拷贝示例代码，然后顺利遇到BUG，疑惑了半天，然后百度，然后才想起来文档的快速上手部分已经说过，但是没用啊，不记得，而且任务紧，所以写出了新手BUG~

### 重现步骤

1、示例代码直接拷贝，运行
2、没有显示和示例一样的效果，而是只展示了第一个文本输入框

**Comment by chenjiahan** [comment]
考虑到大部分用户都是使用 .vue 文件，而不是 HTML 中直接使用，所以文档采用了更简洁的自闭合标签。

这个不计划修改。
