### ISSUE TITLE
Cannot find module './dist/vant.cjs.min.js'

### ISSUE THREAD

**Issue by l1shu** [youzan/vant#9998]
### 重现链接

no link

### Vant 版本

3.3.5

### 描述一下你遇到的问题。

ssr 引入时，require('vant') -> node_modules/vant/lib/ssr.js:

```
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./dist/vant.cjs.min.js');
} else {
  module.exports = require('./dist/vant.cjs.js');
};

```
实际上没有这个dist路径，直接相对路径即可： ./vant.cjs.js

### 重现步骤

require('vant')

**Comment by chenjiahan** [comment]
已在 3.2.6 版本修复
